Mantid: Mantid::DataHandling::LoadEventNexus Class Reference
Mantid::DataHandling::LoadEventNexus Class Reference
Load Event Nexus files.
#include <Nexus/LoadEventNexus.h>
Public Member Functions
const std::string category () const override
Category.
int confidence (Nexus::NexusDescriptor &descriptor) const override
Return the confidence with with this algorithm can load the file.
LoadEventNexus ()
Empty default constructor.
const std::string name () const override
function to return a name of the algorithm, must be overridden in all algorithms
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Version.
Public Member Functions inherited from Mantid::API::NexusFileLoader
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
void exec () override final
Virtual method - must be overridden by concrete algorithm.
virtual const std::shared_ptr< Mantid::Nexus::NexusDescriptor > getFileInfo () const noexcept
Required to pass m_fileInfo to static functions Keeping it shared_ptr to match setFileInfo signature (although passing ownership is not the main goal).
virtual std::string getFilenamePropertyName () const
virtual void setFileInfo (std::shared_ptr< Mantid::Nexus::NexusDescriptor > fileInfo)
Public Member Functions inherited from Mantid::API::IFileLoader< Mantid::Nexus::NexusDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Static Public Member Functions
static int checkForCorruptedPeriods (std::unique_ptr< Kernel::TimeSeriesProperty< int > > tempPeriodLog, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > &periodLog, const int &nPeriods, const std::string &nexusfilename, std::string &status)
Check for corrupted period logs If data is historical (1 periods, period is labelled 0) then change period labels to 1 If number of periods does not match expected number of periods then throw an error.
template<typename T >
static void loadEntryMetadata (const std::string &nexusfilename, T WS, const std::string &entry_name, const Nexus::NexusDescriptor &descriptor)
Load the run number and other meta data from the given bank.
template<typename T >
static bool loadInstrument (const std::string &nexusfilename, T localWorkspace, const std::string &top_entry_name, Algorithm *alg, const Nexus::NexusDescriptor *descriptor=nullptr)
Load instrument from Nexus file if possible, else from IDF spacified by Nexus file.
static void loadSampleDataISIScompatibility (Nexus::File &file, EventWorkspaceCollection &WS)
Load information of the sample.
static std::string readInstrumentFromISIS_VMSCompat (Nexus::File &hFile)
method used to return instrument name for some old ISIS files where it is not written properly within the instrument
template<>
bool runLoadIDFFromNexus (const std::string &nexusfilename, EventWorkspaceCollection_sptr localWorkspace, const std::string &top_entry_name, Algorithm *alg)
Load the instrument from the nexus file.
template<typename T >
static bool runLoadIDFFromNexus (const std::string &nexusfilename, T localWorkspace, const std::string &top_entry_name, Algorithm *alg)
Load instrument for Nexus file.
template<>
bool runLoadInstrument (const std::string &nexusfilename, EventWorkspaceCollection_sptr localWorkspace, const std::string &top_entry_name, Algorithm *alg, const Nexus::NexusDescriptor *descriptor)
Load the instrument definition file specified by info in the NXS file for a EventWorkspaceCollection.
template<typename T >
static bool runLoadInstrument (const std::string &nexusfilename, T localWorkspace, const std::string &top_entry_name, Algorithm *alg, const Nexus::NexusDescriptor *descriptor=nullptr)
Load instrument from IDF file specified by Nexus file.
template<>
std::shared_ptr< BankPulseTimes > runLoadNexusLogs (const std::string &nexusfilename, EventWorkspaceCollection_sptr localWorkspace, API::Algorithm &alg, bool returnpulsetimes, int &nPeriods, std::unique_ptr< const TimeSeriesProperty< int > > &periodLog)
Load the instrument from the nexus file.
template<>
std::shared_ptr< BankPulseTimes > runLoadNexusLogs (const std::string &nexusfilename, EventWorkspaceCollection_sptr localWorkspace, API::Algorithm &alg, bool returnpulsetimes, int &nPeriods, std::unique_ptr< const TimeSeriesProperty< int > > &periodLog, const std::vector< std::string > &allow_list, const std::vector< std::string > &block_list)
Load the instrument from the nexus file.
template<typename T >
static std::shared_ptr< BankPulseTimes > runLoadNexusLogs (const std::string &nexusfilename, T localWorkspace, Algorithm &alg, bool returnpulsetimes, int &nPeriods, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > &periodLog)
Load the log from the nexus file.
template<typename T >
static std::shared_ptr< BankPulseTimes > runLoadNexusLogs (const std::string &nexusfilename, T localWorkspace, Algorithm &alg, bool returnpulsetimes, int &nPeriods, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > &periodLog, const std::vector< std::string > &allow_list, const std::vector< std::string > &block_list)
Load the log from the nexus file.
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes
std::shared_ptr< Mantid::Kernel::TimeROI > bad_pulses_timeroi
size_t bad_tofs
Count of all the "bad" tofs found.
bool compressEvents
double compressTolerance
Tolerance for CompressEvents; use -1 to mean don't compress.
size_t discarded_events
A count of events discarded because they came from a pixel that's not in the IDF.
bool filter_bad_pulses {false}
Mantid::Types::Core::DateAndTime filter_time_start
Filter by start time.
Mantid::Types::Core::DateAndTime filter_time_stop
Filter by stop time.
double filter_tof_max
Filter by a maximum time-of-flight.
double filter_tof_min
Filter by a minimum time-of-flight.
bool filter_tof_range
Tof range is being filtered.
double longest_tof
Limits found to tof.
std::shared_ptr< BankPulseTimes > m_allBanksPulseTimes
Pulse times for ALL banks, taken from proton_charge log.
std::unique_ptr< Nexus::File > m_file
std::string m_filename
The name and path of the input file.
bool m_is_time_filtered {false}
if wall-clock filtering was requested
int32_t m_specMax
Maximum spectrum to load.
int32_t m_specMin
Minimum spectrum to load.
std::mutex m_tofMutex
Mutex protecting tof limits.
std::string m_top_entry_name
name of top level NXentry to use
std::shared_ptr< EventWorkspaceCollection > m_ws
The workspace being filled out.
double shortest_tof
Limits found to tof.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Private Member Functions
DataObjects::EventWorkspace_sptr createEmptyEventWorkspace ()
void createSpectraMapping (const std::string &nxsfile, const bool monitorsOnly, const std::vector< std::string > &bankNames=std::vector< std::string >())
Create the required spectra mapping.
void deleteBanks (const EventWorkspaceCollection_sptr &workspace, const std::vector< std::string > &bankNames)
Deletes banks for a workspace given the bank names.
void execLoader () override
Execution code.
template<>
void filterDuringPause (EventWorkspaceCollection_sptr workspace)
template<typename T >
void filterDuringPause (T workspace)
template<>
EventWorkspaceCollection_sptr filterEventsByTime (EventWorkspaceCollection_sptr workspace, Mantid::Types::Core::DateAndTime &startTime, Mantid::Types::Core::DateAndTime &stopTime)
template<typename T >
T filterEventsByTime (T workspace, Mantid::Types::Core::DateAndTime &startTime, Mantid::Types::Core::DateAndTime &stopTime)
Filter the events by pulse time - no in place version so have to return workspace.
void init () override
Intialisation code.
void loadEvents (API::Progress *const prog, const bool monitors)
Load events from the file.
std::unique_ptr< std::pair< std::vector< int32_t >, std::vector< int32_t > > > loadISISVMSSpectraMapping (const std::string &entry_name)
Load a spectra mapping from the given file.
void runLoadMonitors ()
Load the Monitors from the NeXus file into a workspace.
void safeOpenFile (const std::string &fname)
to open the nexus file with specific exception handling/message
void setTimeFilters (const bool monitors)
Set the filters on TOF.
void setTopEntryName ()
Set the top entry field name.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
Private Attributes
bool event_id_is_spec
True if the event_id is spectrum no not pixel ID.
bool loadlogs
Do we load the sample logs?
bool m_instrument_loaded_correctly
Was the instrument loaded?
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Load Event Nexus files.
Required Properties:
Filename - The name of and path to the input NeXus file
Workspace - The name of the workspace to output
Date
Sep 27, 2010
Definition at line 74 of file LoadEventNexus.h.
Constructor & Destructor Documentation
LoadEventNexus()
Mantid::DataHandling::LoadEventNexus::LoadEventNexus ()
Empty default constructor.
Definition at line 78 of file LoadEventNexus.cpp.
References compressTolerance, and Mantid::EMPTY_DBL().
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadEventNexus::category () const inline override virtual
Category.
Reimplemented from Mantid::API::Algorithm.
Definition at line 93 of file LoadEventNexus.h.
checkForCorruptedPeriods()
int Mantid::DataHandling::LoadEventNexus::checkForCorruptedPeriods (std::unique_ptr< Kernel::TimeSeriesProperty< int > > tempPeriodLog, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > & periodLog, const int & nPeriods, const std::string & nexusfilename, std::string & status) static
Check for corrupted period logs If data is historical (1 periods, period is labelled 0) then change period labels to 1 If number of periods does not match expected number of periods then throw an error.
Parameters
tempPeriodLog :: a temporary local copy of period logs, which will change
periodLog :: unique pointer which will point to period logs once they have been changed
nPeriods :: the value in the nperiods log of the run. Number of expected periods
nexusfilename :: the filename of the run to load
status :: will contain any status message. Empty if no problems.
Returns
Number of periods with data
Definition at line 779 of file LoadEventNexus.cpp.
References std::to_string().
Referenced by runLoadNexusLogs(), and runLoadNexusLogs().
confidence()
int Mantid::DataHandling::LoadEventNexus::confidence (Nexus::NexusDescriptor & descriptor) const override virtual
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::NexusFileLoader.
Definition at line 92 of file LoadEventNexus.cpp.
References confidence(), Mantid::Nexus::NexusDescriptor::getAllEntries(), and Mantid::Nexus::NexusDescriptor::isEntry().
Referenced by confidence(), and Mantid::DataHandling::UpdateInstrumentFromFile::exec().
createEmptyEventWorkspace()
DataObjects::EventWorkspace_sptr Mantid::DataHandling::LoadEventNexus::createEmptyEventWorkspace () private
References Mantid::DataHandling::loadEvents().
createSpectraMapping()
void Mantid::DataHandling::LoadEventNexus::createSpectraMapping (const std::string & nxsfile, const bool monitorsOnly, const std::vector< std::string > & bankNames = std::vector<std::string>()) private
Create the required spectra mapping.
If the file contains an isis_vms_compat block then the mapping is read from there, otherwise a 1:1 map with the instrument is created (along with the associated spectra axis)
Parameters
nxsfile :: The name of a nexus file to load the mapping from
monitorsOnly :: Load only the monitors is true
bankNames :: An optional bank name for loading specified banks
Definition at line 1401 of file LoadEventNexus.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::DataHandling::LoadEventNexusIndexSetup::eventIDLimits(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::isDefault(), loadISISVMSSpectraMapping(), m_specMax, m_specMin, m_top_entry_name, m_ws, Mantid::DataHandling::LoadEventNexusIndexSetup::makeIndexInfo(), and Mantid::Kernel::Logger::warning().
Referenced by loadEvents().
deleteBanks()
void Mantid::DataHandling::LoadEventNexus::deleteBanks (const EventWorkspaceCollection_sptr & workspace, const std::vector< std::string > & bankNames) private
Deletes banks for a workspace given the bank names.
Parameters
workspace :: The workspace to contain the spectra mapping
bankNames :: Bank names that are in Nexus file
Definition at line 1315 of file LoadEventNexus.cpp.
References Mantid::Geometry::d, and workspace.
execLoader()
void Mantid::DataHandling::LoadEventNexus::execLoader () override private virtual
Execution code.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Implements Mantid::API::NexusFileLoader.
Definition at line 407 of file LoadEventNexus.cpp.
References compressEvents, compressTolerance, discarded_events, filterDuringPause(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isDefault(), loadEvents(), loadlogs, m_file, m_filename, m_ws, Mantid::Kernel::ProgressBase::report(), runLoadMonitors(), safeOpenFile(), Mantid::Kernel::IPropertyManager::setProperty(), and setTopEntryName().
filterDuringPause() [1/2]
template<> void Mantid::DataHandling::LoadEventNexus::filterDuringPause (EventWorkspaceCollection_sptr workspace) private
Definition at line 366 of file LoadEventNexus.cpp.
References workspace.
filterDuringPause() [2/2]
template<typename T > void Mantid::DataHandling::LoadEventNexus::filterDuringPause (T workspace) private
Definition at line 342 of file LoadEventNexus.cpp.
References Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::API::g_log, m_ws, Mantid::Kernel::Logger::notice(), and workspace.
Referenced by execLoader(), and runLoadMonitors().
filterEventsByTime() [1/2]
template<> EventWorkspaceCollection_sptr Mantid::DataHandling::LoadEventNexus::filterEventsByTime (EventWorkspaceCollection_sptr workspace, Mantid::Types::Core::DateAndTime & startTime, Mantid::Types::Core::DateAndTime & stopTime) private
Definition at line 392 of file LoadEventNexus.cpp.
References workspace.
filterEventsByTime() [2/2]
template<typename T > T Mantid::DataHandling::LoadEventNexus::filterEventsByTime (T workspace, Mantid::Types::Core::DateAndTime & startTime, Mantid::Types::Core::DateAndTime & stopTime) private
Filter the events by pulse time - no in place version so have to return workspace.
Definition at line 379 of file LoadEventNexus.cpp.
References Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::API::g_log, Mantid::Kernel::Logger::information(), and workspace.
init()
void Mantid::DataHandling::LoadEventNexus::init () override private virtual
Intialisation code.
Initialisation method.
Implements Mantid::API::Algorithm.
Definition at line 108 of file LoadEventNexus.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::Kernel::IS_NOT_DEFAULT, Mantid::API::FileProperty::Load, Mantid::Kernel::Direction::Output, Mantid::Kernel::IPropertyManager::setPropertyGroup(), and Mantid::Kernel::IPropertyManager::setPropertySettings().
loadEntryMetadata()
template<typename T > void Mantid::DataHandling::LoadEventNexus::loadEntryMetadata (const std::string & nexusfilename, T WS, const std::string & entry_name, const Nexus::NexusDescriptor & descriptor) static
Load the run number and other meta data from the given bank.
Definition at line 599 of file LoadEventNexus.h.
References NXnumtype::CHAR, Mantid::Nexus::NexusDescriptor::isEntry(), std::to_string(), and value.
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), and Mantid::DataHandling::LoadTOFRawNexus::exec().
loadEvents()
void Mantid::DataHandling::LoadEventNexus::loadEvents (API::Progress *const prog, const bool monitors) private
Load events from the file.
Parameters
prog :: A pointer to the progress reporting object
monitors :: If true the events from the monitors are loaded and not the main banks
This also loads the instrument, but only if it has not been set in the workspace being used as input (m_ws data member). Same applies to the logs.
Definition at line 880 of file LoadEventNexus.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), bad_pulses_timeroi, bad_tofs, Mantid::Kernel::DateAndTimeHelpers::createFromSanitizedISO8601(), createSpectraMapping(), Mantid::Kernel::Logger::debug(), Mantid::API::Progress::doReport(), Mantid::EMPTY_DBL(), Mantid::Kernel::Logger::error(), filter_bad_pulses, filter_time_start, filter_time_stop, Mantid::DataHandling::firstLastPulseTimes(), Mantid::API::g_log, Mantid::API::NexusFileLoader::getFileInfo(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isDefault(), loadInstrument(), loadlogs, loadSampleDataISIScompatibility(), m_allBanksPulseTimes, m_file, m_filename, m_instrument_loaded_correctly, m_is_time_filtered, m_top_entry_name, m_ws, Mantid::DataHandling::numEvents(), READ, Mantid::Kernel::ProgressBase::report(), safeOpenFile(), setTimeFilters(), and tmp.
Referenced by execLoader().
loadInstrument()
template<typename T > bool Mantid::DataHandling::LoadEventNexus::loadInstrument (const std::string & nexusfilename, T localWorkspace, const std::string & top_entry_name, Algorithm * alg, const Nexus::NexusDescriptor * descriptor = nullptr) static
Load instrument from Nexus file if possible, else from IDF spacified by Nexus file.
Load the instrument from the nexus file if property LoadNexusInstrumentXML is set to true.
If instrument XML not found from the IDF file (specified by the info in the Nexus file) load the IDF.
Parameters
nexusfilename :: The Nexus file name
localWorkspace :: templated workspace in which to put the instrument geometry
top_entry_name :: entry name at the top of the Nexus file
alg :: Handle of the algorithm
descriptor :: The Nexus HDF5 file descriptor
Returns
true if successful
Definition at line 726 of file LoadEventNexus.h.
References Mantid::API::Algorithm::existsProperty(), and Mantid::API::Algorithm::getProperty().
Referenced by Mantid::DataHandling::LoadNexusMonitors2::exec(), and loadEvents().
loadISISVMSSpectraMapping()
std::unique_ptr< std::pair< std::vector< int32_t >, std::vector< int32_t > > > Mantid::DataHandling::LoadEventNexus::loadISISVMSSpectraMapping (const std::string & entry_name) private
Load a spectra mapping from the given file.
This currently checks for the existence of an isis_vms_compat block in the file, if it exists it pulls out the spectra mapping listed there
Parameters
entry_name :: name of the NXentry to open.
Returns
True if the mapping was loaded or false if the block does not exist
Definition at line 1489 of file LoadEventNexus.cpp.
References Mantid::Kernel::Logger::debug(), event_id_is_spec, Mantid::API::g_log, and m_file.
Referenced by createSpectraMapping().
loadSampleDataISIScompatibility()
void Mantid::DataHandling::LoadEventNexus::loadSampleDataISIScompatibility (Nexus::File & file, EventWorkspaceCollection & WS) static
Load information of the sample.
It is valid only for ISIS it get the information from the group isis_vms_compat.
If it does not find this group, it assumes that there is nothing to do. But, if the information is there, but not in the way it was expected, it will log the occurrence.
Note
: It does essentially the same thing of the method: LoadISISNexus2::loadSampleData
Parameters
file : handle to the nexus file
WS : pointer to the workspace
Definition at line 1587 of file LoadEventNexus.cpp.
References Mantid::DataHandling::EventWorkspaceCollection::setGeometryFlag(), Mantid::DataHandling::EventWorkspaceCollection::setHeight(), Mantid::DataHandling::EventWorkspaceCollection::setThickness(), and Mantid::DataHandling::EventWorkspaceCollection::setWidth().
Referenced by loadEvents().
name()
const std::string Mantid::DataHandling::LoadEventNexus::name () const inline override virtual
function to return a name of the algorithm, must be overridden in all algorithms
Implements Mantid::API::Algorithm.
Definition at line 79 of file LoadEventNexus.h.
readInstrumentFromISIS_VMSCompat()
std::string Mantid::DataHandling::LoadEventNexus::readInstrumentFromISIS_VMSCompat (Nexus::File & hFile) static
method used to return instrument name for some old ISIS files where it is not written properly within the instrument
Parameters
hFile :: A reference to the NeXus file opened at the root entry
Definition at line 1264 of file LoadEventNexus.cpp.
Referenced by Mantid::DataHandling::LoadNexusMonitors2::exec(), and runLoadInstrument().
runLoadIDFFromNexus() [1/2]
template<> bool Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus (const std::string & nexusfilename, EventWorkspaceCollection_sptr localWorkspace, const std::string & top_entry_name, Algorithm * alg) static
Load the instrument from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: EventWorkspaceCollection in which to put the instrument geometry
top_entry_name :: entry name at the top of the Nexus file
alg :: Handle of the algorithm
Returns
true if successful
Definition at line 1250 of file LoadEventNexus.cpp.
runLoadIDFFromNexus() [2/2]
template<typename T > bool Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus (const std::string & nexusfilename, T localWorkspace, const std::string & top_entry_name, Algorithm * alg) static
Load instrument for Nexus file.
Load the instrument from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: templated workspace in which to put the instrument geometry
top_entry_name :: entry name at the top of the Nexus file
alg :: Handle of the algorithm
Returns
true if successful
Definition at line 753 of file LoadEventNexus.h.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::getLogger(), and Mantid::Kernel::Logger::information().
Referenced by Mantid::DataHandling::LoadISISNexus2::exec().
runLoadInstrument() [1/2]
template<> bool Mantid::DataHandling::LoadEventNexus::runLoadInstrument (const std::string & nexusfilename, EventWorkspaceCollection_sptr localWorkspace, const std::string & top_entry_name, Algorithm * alg, const Nexus::NexusDescriptor * descriptor) static
Load the instrument definition file specified by info in the NXS file for a EventWorkspaceCollection.
Parameters
nexusfilename :: Used to pick the instrument.
localWorkspace :: EventWorkspaceCollection in which to put the instrument geometry
top_entry_name :: entry name at the top of the NXS file
alg :: Handle of the algorithm
descriptor :: input containing metadata information
Returns
true if successful
Definition at line 1299 of file LoadEventNexus.cpp.
runLoadInstrument() [2/2]
template<typename T > bool Mantid::DataHandling::LoadEventNexus::runLoadInstrument (const std::string & nexusfilename, T localWorkspace, const std::string & top_entry_name, Algorithm * alg, const Nexus::NexusDescriptor * descriptor = nullptr) static
Load instrument from IDF file specified by Nexus file.
Load the instrument definition file specified by info in the NXS file.
Parameters
nexusfilename :: Used to pick the instrument.
localWorkspace :: Templated workspace in which to put the instrument geometry
top_entry_name :: entry name at the top of the NXS file
alg :: Handle of the algorithm
descriptor :: The Nexus HDF5 file descriptor
Returns
true if successful
Definition at line 469 of file LoadEventNexus.h.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::Nexus::NexusDescriptor::getAllEntries(), Mantid::API::InstrumentFileFinder::getInstrumentFilename(), Mantid::API::Algorithm::getLogger(), Mantid::Kernel::Logger::information(), Mantid::DataHandling::LoadGeometry::isNexus(), n, readInstrumentFromISIS_VMSCompat(), and value.
Referenced by Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs().
runLoadMonitors()
void Mantid::DataHandling::LoadEventNexus::runLoadMonitors () private
Load the Monitors from the NeXus file into a workspace.
The original workspace name is used and appended with _monitors.
Definition at line 1433 of file LoadEventNexus.cpp.
References Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::API::Algorithm::declareProperty(), filterDuringPause(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_filename, m_ws, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by execLoader().
runLoadNexusLogs() [1/4]
template<> std::shared_ptr< BankPulseTimes > Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs (const std::string & nexusfilename, EventWorkspaceCollection_sptr localWorkspace, API::Algorithm & alg, bool returnpulsetimes, int & nPeriods, std::unique_ptr< const TimeSeriesProperty< int > > & periodLog) static
Load the instrument from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: EventWorkspaceCollection in which to put the instrument geometry
alg :: Handle of the algorithm
returnpulsetimes :: flag to return shared pointer for BankPulseTimes, otherwise NULL.
nPeriods : Number of periods (write to)
periodLog : Period logs DateAndTime to int map.
Returns
Pulse times given in the DAS logs
Definition at line 779 of file LoadEventNexus.cpp.
runLoadNexusLogs() [2/4]
template<> std::shared_ptr< BankPulseTimes > Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs (const std::string & nexusfilename, EventWorkspaceCollection_sptr localWorkspace, API::Algorithm & alg, bool returnpulsetimes, int & nPeriods, std::unique_ptr< const TimeSeriesProperty< int > > & periodLog, const std::vector< std::string > & allow_list, const std::vector< std::string > & block_list) static
Load the instrument from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: EventWorkspaceCollection in which to put the instrument geometry
alg :: Handle of the algorithm
returnpulsetimes :: flag to return shared pointer for BankPulseTimes, otherwise NULL.
nPeriods : Number of periods (write to)
periodLog : Period logs DateAndTime to int map.
allow_list log entry that will be loaded
block_list log entry that will be excluded
Returns
Pulse times given in the DAS logs
Definition at line 779 of file LoadEventNexus.cpp.
runLoadNexusLogs() [3/4]
template<typename T > std::shared_ptr< BankPulseTimes > Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs (const std::string & nexusfilename, T localWorkspace, API::Algorithm & alg, bool returnpulsetimes, int & nPeriods, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > & periodLog) static
Load the log from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: Templated workspace in which to put the instrument geometry
alg :: Handle of the algorithm
returnpulsetimes :: flag to return shared pointer for BankPulseTimes, otherwise NULL.
nPeriods : Number of periods (write to)
periodLog : Period logs DateAndTime to int map.
Returns
Pulse times given in the DAS logs
Attempt to make a gonoimeter from the logs
Definition at line 573 of file LoadEventNexus.cpp.
References checkForCorruptedPeriods(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::getLogger(), Mantid::API::LogManager::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::LogManager::getPropertyValueAsType(), Mantid::API::LogManager::hasProperty(), Mantid::Kernel::Logger::information(), Mantid::Geometry::Goniometer::makeUniversalGoniometer(), Mantid::Kernel::TimeSeriesProperty< TYPE >::timesAsVector(), Mantid::Kernel::Property::value(), and Mantid::Kernel::Logger::warning().
runLoadNexusLogs() [4/4]
template<typename T > std::shared_ptr< BankPulseTimes > Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs (const std::string & nexusfilename, T localWorkspace, API::Algorithm & alg, bool returnpulsetimes, int & nPeriods, std::unique_ptr< const Kernel::TimeSeriesProperty< int > > & periodLog, const std::vector< std::string > & allow_list, const std::vector< std::string > & block_list) static
Load the log from the nexus file.
Parameters
nexusfilename :: The name of the nexus file being loaded
localWorkspace :: Templated workspace in which to put the instrument geometry
alg :: Handle of the algorithm
returnpulsetimes :: flag to return shared pointer for BankPulseTimes, otherwise NULL.
nPeriods : Number of periods (write to)
periodLog : Period logs DateAndTime to int map.
allow_list list of properties that will be loaded
block_list list of properties that will be excluded from loading
Returns
Pulse times given in the DAS logs
Attempt to make a gonoimeter from the logs
Definition at line 676 of file LoadEventNexus.cpp.
References checkForCorruptedPeriods(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::getLogger(), Mantid::API::LogManager::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::LogManager::getPropertyValueAsType(), Mantid::API::LogManager::hasProperty(), Mantid::Kernel::Logger::information(), Mantid::Geometry::Goniometer::makeUniversalGoniometer(), Mantid::Kernel::TimeSeriesProperty< TYPE >::timesAsVector(), and Mantid::Kernel::Logger::warning().
safeOpenFile()
void Mantid::DataHandling::LoadEventNexus::safeOpenFile (const std::string & fname) private
to open the nexus file with specific exception handling/message
Makes sure that m_file is a valid and open Nexus::File object.
Throws if there is an exception opening the file.
Parameters
fname name of the nexus file to open
Definition at line 1623 of file LoadEventNexus.cpp.
References m_file, m_filename, and READ.
Referenced by execLoader(), and loadEvents().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadEventNexus::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 90 of file LoadEventNexus.h.
setTimeFilters()
void Mantid::DataHandling::LoadEventNexus::setTimeFilters (const bool monitors) private
Set the filters on TOF.
Parameters
monitors :: If true check the monitor properties else use the standard ones
Definition at line 1549 of file LoadEventNexus.cpp.
References Mantid::EMPTY_DBL(), filter_tof_max, filter_tof_min, filter_tof_range, and Mantid::API::Algorithm::getProperty().
Referenced by loadEvents().
setTopEntryName()
void Mantid::DataHandling::LoadEventNexus::setTopEntryName () private
Set the top entry field name.
set the name of the top level NXentry m_top_entry_name
Definition at line 319 of file LoadEventNexus.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), m_file, and m_top_entry_name.
Referenced by execLoader().
summary()
const std::string Mantid::DataHandling::LoadEventNexus::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 82 of file LoadEventNexus.h.
validateInputs()
std::map< std::string, std::string > Mantid::DataHandling::LoadEventNexus::validateInputs (void) override private virtual
Perform validation of ALL the input properties of the algorithm.
This is to be overridden by specific algorithms. It will be called in dialogs after parsing all inputs and setting the properties, but BEFORE executing.
Returns
a map where: Key = string name of the property; Value = string describing the problem with the property.
Reimplemented from Mantid::API::Algorithm.
Definition at line 296 of file LoadEventNexus.cpp.
References Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::isDefault(), Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::Kernel::Logger::warning().
version()
int Mantid::DataHandling::LoadEventNexus::version () const inline override virtual
Version.
Implements Mantid::API::Algorithm.
Definition at line 89 of file LoadEventNexus.h.
Member Data Documentation
bad_pulses_timeroi
std::shared_ptr<Mantid::Kernel::TimeROI> Mantid::DataHandling::LoadEventNexus::bad_pulses_timeroi
Definition at line 164 of file LoadEventNexus.h.
Referenced by loadEvents().
bad_tofs
size_t Mantid::DataHandling::LoadEventNexus::bad_tofs
Count of all the "bad" tofs found.
These are events with TOF > 2e8 microsec
Definition at line 175 of file LoadEventNexus.h.
Referenced by loadEvents().
compressEvents
bool Mantid::DataHandling::LoadEventNexus::compressEvents
Definition at line 182 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::DefaultEventLoader::DefaultEventLoader(), execLoader(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
compressTolerance
double Mantid::DataHandling::LoadEventNexus::compressTolerance
Tolerance for CompressEvents; use -1 to mean don't compress.
Definition at line 181 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::DefaultEventLoader::DefaultEventLoader(), execLoader(), LoadEventNexus(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
discarded_events
size_t Mantid::DataHandling::LoadEventNexus::discarded_events
A count of events discarded because they came from a pixel that's not in the IDF.
Definition at line 178 of file LoadEventNexus.h.
Referenced by execLoader().
event_id_is_spec
bool Mantid::DataHandling::LoadEventNexus::event_id_is_spec private
True if the event_id is spectrum no not pixel ID.
Definition at line 231 of file LoadEventNexus.h.
Referenced by loadISISVMSSpectraMapping().
filter_bad_pulses
bool Mantid::DataHandling::LoadEventNexus::filter_bad_pulses {false}
Definition at line 163 of file LoadEventNexus.h.
Referenced by loadEvents(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
filter_time_start
Mantid::Types::Core::DateAndTime Mantid::DataHandling::LoadEventNexus::filter_time_start
Filter by start time.
Definition at line 157 of file LoadEventNexus.h.
Referenced by loadEvents().
filter_time_stop
Mantid::Types::Core::DateAndTime Mantid::DataHandling::LoadEventNexus::filter_time_stop
Filter by stop time.
Definition at line 159 of file LoadEventNexus.h.
Referenced by loadEvents().
filter_tof_max
double Mantid::DataHandling::LoadEventNexus::filter_tof_max
Filter by a maximum time-of-flight.
Definition at line 147 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run(), and setTimeFilters().
filter_tof_min
double Mantid::DataHandling::LoadEventNexus::filter_tof_min
Filter by a minimum time-of-flight.
Definition at line 145 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run(), and setTimeFilters().
filter_tof_range
bool Mantid::DataHandling::LoadEventNexus::filter_tof_range
Tof range is being filtered.
Definition at line 149 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run(), and setTimeFilters().
loadlogs
bool Mantid::DataHandling::LoadEventNexus::loadlogs private
Do we load the sample logs?
Definition at line 229 of file LoadEventNexus.h.
Referenced by execLoader(), and loadEvents().
longest_tof
double Mantid::DataHandling::LoadEventNexus::longest_tof
Limits found to tof.
Definition at line 170 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run().
m_allBanksPulseTimes
std::shared_ptr<BankPulseTimes> Mantid::DataHandling::LoadEventNexus::m_allBanksPulseTimes
Pulse times for ALL banks, taken from proton_charge log.
Definition at line 185 of file LoadEventNexus.h.
Referenced by loadEvents(), and Mantid::DataHandling::LoadBankFromDiskTask::loadPulseTimes().
m_file
std::unique_ptr<Nexus::File> Mantid::DataHandling::LoadEventNexus::m_file
Definition at line 189 of file LoadEventNexus.h.
Referenced by execLoader(), loadEvents(), loadISISVMSSpectraMapping(), safeOpenFile(), and setTopEntryName().
m_filename
std::string Mantid::DataHandling::LoadEventNexus::m_filename
The name and path of the input file.
Definition at line 139 of file LoadEventNexus.h.
Referenced by execLoader(), loadEvents(), Mantid::DataHandling::LoadBankFromDiskTask::run(), runLoadMonitors(), and safeOpenFile().
m_instrument_loaded_correctly
bool Mantid::DataHandling::LoadEventNexus::m_instrument_loaded_correctly private
Was the instrument loaded?
Definition at line 226 of file LoadEventNexus.h.
Referenced by loadEvents().
m_is_time_filtered
bool Mantid::DataHandling::LoadEventNexus::m_is_time_filtered {false}
if wall-clock filtering was requested
Definition at line 161 of file LoadEventNexus.h.
Referenced by loadEvents(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
m_specMax
int32_t Mantid::DataHandling::LoadEventNexus::m_specMax
Maximum spectrum to load.
Definition at line 154 of file LoadEventNexus.h.
Referenced by createSpectraMapping(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
m_specMin
int32_t Mantid::DataHandling::LoadEventNexus::m_specMin
Minimum spectrum to load.
Definition at line 152 of file LoadEventNexus.h.
Referenced by createSpectraMapping(), and Mantid::DataHandling::LoadBankFromDiskTask::run().
m_tofMutex
std::mutex Mantid::DataHandling::LoadEventNexus::m_tofMutex
Mutex protecting tof limits.
Definition at line 167 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run().
m_top_entry_name
std::string Mantid::DataHandling::LoadEventNexus::m_top_entry_name
name of top level NXentry to use
Definition at line 188 of file LoadEventNexus.h.
Referenced by createSpectraMapping(), loadEvents(), Mantid::DataHandling::LoadBankFromDiskTask::run(), and setTopEntryName().
m_ws
std::shared_ptr<EventWorkspaceCollection> Mantid::DataHandling::LoadEventNexus::m_ws
The workspace being filled out.
Definition at line 142 of file LoadEventNexus.h.
Referenced by createSpectraMapping(), execLoader(), filterDuringPause(), loadEvents(), and runLoadMonitors().
shortest_tof
double Mantid::DataHandling::LoadEventNexus::shortest_tof
Limits found to tof.
Definition at line 172 of file LoadEventNexus.h.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::run().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
Framework/DataHandling/src/LoadEventNexus.cpp