Mantid: MantidQt::MantidWidgets::Batch::RowLocation Class Reference
MantidQt::MantidWidgets::Batch::RowLocation Class Reference
#include <RowLocation.h>
Public Member Functions
RowLocation child (int n) const
int depth () const
bool isChildOf (RowLocation const &other) const
bool isChildOrSiblingOf (RowLocation const &other) const
bool isDescendantOf (RowLocation const &other) const
bool isRoot () const
bool isSiblingOf (RowLocation const &other) const
bool operator!= (RowLocation const &other) const
bool operator< (RowLocation const &other) const
bool operator<= (RowLocation const &other) const
bool operator== (RowLocation const &other) const
bool operator> (RowLocation const &other) const
bool operator>= (RowLocation const &other) const
RowLocation parent () const
RowPath const & path () const
RowLocation relativeTo (RowLocation const &ancestor) const
RowLocation ()=default
RowLocation (RowPath path)
int rowRelativeToParent () const
Private Attributes
RowPath m_path
Detailed Description
Definition at line 22 of file RowLocation.h.
Constructor & Destructor Documentation
RowLocation() [1/2]
MantidQt::MantidWidgets::Batch::RowLocation::RowLocation () default
Referenced by child(), parent(), and relativeTo().
RowLocation() [2/2]
MantidQt::MantidWidgets::Batch::RowLocation::RowLocation (RowPath path)
Definition at line 20 of file RowLocation.cpp.
Member Function Documentation
child()
RowLocation MantidQt::MantidWidgets::Batch::RowLocation::child (int n) const
Definition at line 45 of file RowLocation.cpp.
References m_path, n, and RowLocation().
depth()
int MantidQt::MantidWidgets::Batch::RowLocation::depth () const
Definition at line 51 of file RowLocation.cpp.
References m_path.
Referenced by MantidQt::MantidWidgets::Batch::hasSubtreeRootDeeperThanFirstRoot(), MantidQt::MantidWidgets::Batch::hasSubtreeRootShallowerThanFirstRoot(), isChildOf(), isDescendantOf(), isSiblingOf(), MantidQt::MantidWidgets::Batch::maximumIncreaseInDepthIsOne(), MantidQt::MantidWidgets::Batch::ExtractSubtrees::operator()(), MantidQt::MantidWidgets::Batch::pathsSameUntilDepth(), and relativeTo().
isChildOf()
bool MantidQt::MantidWidgets::Batch::RowLocation::isChildOf (RowLocation const & other) const
Definition at line 24 of file RowLocation.cpp.
References depth(), boost::algorithm::equal(), isRoot(), and m_path.
Referenced by isChildOrSiblingOf().
isChildOrSiblingOf()
bool MantidQt::MantidWidgets::Batch::RowLocation::isChildOrSiblingOf (RowLocation const & other) const
Definition at line 98 of file RowLocation.cpp.
References isChildOf(), and isSiblingOf().
isDescendantOf()
bool MantidQt::MantidWidgets::Batch::RowLocation::isDescendantOf (RowLocation const & other) const
Definition at line 100 of file RowLocation.cpp.
References depth(), boost::algorithm::equal(), isRoot(), m_path, and path().
Referenced by MantidQt::MantidWidgets::Batch::allNodesDescendedFromParentOfFirstRoot(), and relativeTo().
isRoot()
bool MantidQt::MantidWidgets::Batch::RowLocation::isRoot () const
Definition at line 23 of file RowLocation.cpp.
References m_path.
Referenced by MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexIfExistsAt(), isChildOf(), isDescendantOf(), isSiblingOf(), and parent().
isSiblingOf()
bool MantidQt::MantidWidgets::Batch::RowLocation::isSiblingOf (RowLocation const & other) const
Definition at line 89 of file RowLocation.cpp.
References depth(), boost::algorithm::equal(), isRoot(), and m_path.
Referenced by isChildOrSiblingOf().
operator!=()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator!= (RowLocation const & other) const
Definition at line 68 of file RowLocation.cpp.
operator<()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator< (RowLocation const & other) const
Definition at line 70 of file RowLocation.cpp.
References path().
operator<=()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator<= (RowLocation const & other) const
Definition at line 76 of file RowLocation.cpp.
operator==()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator== (RowLocation const & other) const
Definition at line 66 of file RowLocation.cpp.
References path().
operator>()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator> (RowLocation const & other) const
Definition at line 80 of file RowLocation.cpp.
operator>=()
bool MantidQt::MantidWidgets::Batch::RowLocation::operator>= (RowLocation const & other) const
Definition at line 78 of file RowLocation.cpp.
parent()
RowLocation MantidQt::MantidWidgets::Batch::RowLocation::parent () const
Definition at line 40 of file RowLocation.cpp.
References assertOrThrow(), isRoot(), m_path, and RowLocation().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::replaceSubtreeAt().
path()
RowPath const & MantidQt::MantidWidgets::Batch::RowLocation::path () const
Definition at line 21 of file RowLocation.cpp.
References m_path.
Referenced by isDescendantOf(), operator<(), MantidQt::MantidWidgets::Batch::operator<<(), operator==(), MantidQt::MantidWidgets::Batch::pathsSameUntilDepth(), and MantidQt::MantidWidgets::Batch::RowLocationAdapter::walkFromRootToParentIndexOf().
relativeTo()
RowLocation MantidQt::MantidWidgets::Batch::RowLocation::relativeTo (RowLocation const & ancestor) const
Definition at line 82 of file RowLocation.cpp.
References assertOrThrow(), depth(), isDescendantOf(), m_path, and RowLocation().
Referenced by MantidQt::MantidWidgets::Batch::ExtractSubtrees::makeSubtreeFromRows().
rowRelativeToParent()
int MantidQt::MantidWidgets::Batch::RowLocation::rowRelativeToParent () const
Definition at line 22 of file RowLocation.cpp.
References m_path.
Referenced by MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexIfExistsAt(), and MantidQt::MantidWidgets::Batch::JobTreeView::replaceSubtreeAt().
Member Data Documentation
m_path
RowPath MantidQt::MantidWidgets::Batch::RowLocation::m_path private
Definition at line 45 of file RowLocation.h.
Referenced by child(), depth(), isChildOf(), isDescendantOf(), isRoot(), isSiblingOf(), parent(), path(), relativeTo(), and rowRelativeToParent().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/RowLocation.h
qt/widgets/common/src/Batch/RowLocation.cpp