Mantid: Mantid::Kernel::PropertyManagerOwner Class Reference
Mantid::Kernel::PropertyManagerOwner Class Reference
Kernel/PropertyManagerOwner.h.
#include <PropertyManagerOwner.h>
Public Member Functions
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
void clear () override
Clears all properties under management.
virtual void copyPropertiesFrom (const PropertyManagerOwner &po)
Make m_properties point to the same PropertyManager as po.
void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
void declareProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
const std::vector< Property * > & getProperties () const override
Get the list of managed properties.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
bool isDefault (const std::string &name) const
PropertyManagerOwner & operator= (const PropertyManagerOwner &)
Assignment operator.
size_t propertyCount () const override
Count the number of properties under management.
PropertyManagerOwner ()
Default constructor.
PropertyManagerOwner (const PropertyManagerOwner &)
Copy constructor.
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const override
std::unique_ptr< Property > takeProperty (const size_t index) override
Removes the property from management returning a pointer to it.
bool validateProperties () const override
Validates all the properties in the collection.
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Attributes
std::shared_ptr< PropertyManager > m_properties
Shared pointer to the 'real' property manager.
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Detailed Description
Kernel/PropertyManagerOwner.h.
Implementation of IPropertyManager which allows sharing the same set of Properties between several instances.
Author
Roman Tolchenov, Tessella plc
Date
03/03/2009
Definition at line 33 of file PropertyManagerOwner.h.
Constructor & Destructor Documentation
PropertyManagerOwner() [1/2]
Mantid::Kernel::PropertyManagerOwner::PropertyManagerOwner ()
Default constructor.
Definition at line 24 of file PropertyManagerOwner.cpp.
PropertyManagerOwner() [2/2]
Mantid::Kernel::PropertyManagerOwner::PropertyManagerOwner (const PropertyManagerOwner & po)
Copy constructor.
Definition at line 27 of file PropertyManagerOwner.cpp.
Member Function Documentation
afterPropertySet()
void Mantid::Kernel::PropertyManagerOwner::afterPropertySet (const std::string & name) override virtual
Override this method to perform a custom action right after a property was set.
The argument is the property name. Default - do nothing.
The argument is the property name. Default - do nothing.
Parameters
name :: A property name.
Reimplemented from Mantid::Kernel::IPropertyManager.
Definition at line 272 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::afterPropertySet(), setPropertyOrdinal(), setPropertyValue(), and setPropertyValueFromJson().
asJson()
Json::Value Mantid::Kernel::PropertyManagerOwner::asJson (bool withDefaultValues = false) const override virtual
Return the property manager serialized as a json object.
Parameters
withDefaultValues :: If true then the value of default parameters will be included
Returns
A jsonValue of the manager
Implements Mantid::Kernel::IPropertyManager.
Definition at line 239 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::asJson(), and Mantid::API::Algorithm::toJson().
asString()
std::string Mantid::Kernel::PropertyManagerOwner::asString (bool withDefaultValues = false) const override virtual
Return the property manager serialized as a string.
The format is propName=value,propName=value,propName=value
Parameters
withDefaultValues :: If true then the value of default parameters will be included
Returns
A stringized version of the manager
Implements Mantid::Kernel::IPropertyManager.
Definition at line 230 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::asString().
clear()
void Mantid::Kernel::PropertyManagerOwner::clear () override virtual
Clears all properties under management.
Implements Mantid::Kernel::IPropertyManager.
Definition at line 264 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::clear().
copyPropertiesFrom()
virtual void Mantid::Kernel::PropertyManagerOwner::copyPropertiesFrom (const PropertyManagerOwner & po) inline virtual
Make m_properties point to the same PropertyManager as po.
Definition at line 67 of file PropertyManagerOwner.h.
declareOrReplaceProperty()
void Mantid::Kernel::PropertyManagerOwner::declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string & doc = "") override virtual
Add or replace property in the list of managed properties.
Parameters
p :: The property object to add
doc :: A description of the property that may be displayed to users
Implements Mantid::Kernel::IPropertyManager.
Definition at line 49 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::declareOrReplaceProperty().
declareProperty() [1/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const std::string & doc, IValidator_sptr validator = std::make_shared<NullValidator>(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The (optional) documentation string
validator :: Pointer to the (optional) validator. Ownership will be taken over.
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 165 of file IPropertyManager.h.
declareProperty() [2/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const unsigned int direction) inline
Add a property of string type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 182 of file IPropertyManager.h.
declareProperty() [3/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = std::string(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator. Ownership will be taken over.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 136 of file IPropertyManager.h.
declareProperty() [4/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const std::string & doc, const unsigned int direction = Direction::Input) inline
Add a property to the list of managed properties with no validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The documentation string
direction :: The (optional) direction of the property, in (default), out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 97 of file IPropertyManager.h.
declareProperty() [5/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const unsigned int direction) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 112 of file IPropertyManager.h.
declareProperty() [6/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = "", const unsigned int direction = Direction::Input) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 80 of file IPropertyManager.h.
declareProperty() [7/8]
void Mantid::Kernel::PropertyManagerOwner::declareProperty (std::unique_ptr< Property > p, const std::string & doc = "") override virtual
Add a property to the list of managed properties.
Parameters
p :: The property object to add
doc :: A description of the property that may be displayed to users
Exceptions
Exception::ExistsError if a property with the given name already exists
Implements Mantid::Kernel::IPropertyManager.
Definition at line 41 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::declareProperty().
declareProperty() [8/8]
virtual void Mantid::Kernel::IPropertyManager::declareProperty (std::unique_ptr< Property > p, const std::string & doc = "") virtual
Function to declare properties (i.e. store them)
Implements Mantid::Kernel::IPropertyManager.
existsProperty()
bool Mantid::Kernel::PropertyManagerOwner::existsProperty (const std::string & name) const override virtual
Checks whether the named property is already in the list of managed property.
Parameters
name :: The name of the property (case insensitive)
Returns
True if the property is already stored
Implements Mantid::Kernel::IPropertyManager.
Definition at line 136 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::existsProperty().
filterByProperty()
void Mantid::Kernel::PropertyManagerOwner::filterByProperty (const TimeSeriesProperty< bool > & , const std::vector< std::string > &) inline override virtual
Implements Mantid::Kernel::IPropertyManager.
Definition at line 107 of file PropertyManagerOwner.h.
filterByTime()
void Mantid::Kernel::PropertyManagerOwner::filterByTime (const Types::Core::DateAndTime & , const Types::Core::DateAndTime &) inline override virtual
Implements Mantid::Kernel::IPropertyManager.
Definition at line 99 of file PropertyManagerOwner.h.
getDeclaredPropertyNames()
std::vector< std::string > Mantid::Kernel::PropertyManagerOwner::getDeclaredPropertyNames () const override virtual noexcept
Return the list of declared property names.
Returns
A vector holding strings of property names
Implements Mantid::Kernel::IPropertyManager.
Definition at line 186 of file PropertyManagerOwner.cpp.
References getProperties().
Referenced by Mantid::API::Algorithm::getDeclaredPropertyNames().
getPointerToProperty()
Property * Mantid::Kernel::PropertyManagerOwner::getPointerToProperty (const std::string & name) const override virtual
Get a property by name.
Parameters
name :: The name of the property (case insensitive)
Returns
A pointer to the named property
Exceptions
Exception::NotFoundError if the named property is unknown
Implements Mantid::Kernel::IPropertyManager.
Definition at line 163 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::getPointerToProperty(), and Mantid::API::Algorithm::isDefault().
getPointerToPropertyOrdinal()
Property * Mantid::Kernel::PropertyManagerOwner::getPointerToPropertyOrdinal (const int & index) const override virtual
Get a property by an index.
Parameters
index :: The name of the property (case insensitive)
Returns
A pointer to the named property
Exceptions
std::runtime_error if the property index is too high
Implements Mantid::Kernel::IPropertyManager.
Definition at line 172 of file PropertyManagerOwner.cpp.
References index, and m_properties.
Referenced by Mantid::API::Algorithm::getPointerToPropertyOrdinal(), and Mantid::API::Algorithm::setPropertyOrdinal().
getProperties()
const std::vector< Property * > & Mantid::Kernel::PropertyManagerOwner::getProperties () const override virtual
Get the list of managed properties.
The properties will be stored in the order that they were declared.
Returns
A vector holding pointers to the list of properties
Implements Mantid::Kernel::IPropertyManager.
Definition at line 180 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by getDeclaredPropertyNames(), and Mantid::API::Algorithm::getProperties().
getProperty()
IPropertyManager::TypedValue Mantid::Kernel::PropertyManagerOwner::getProperty (const std::string & name) const override virtual
Get the value of a property.
Allows you to assign directly to a variable of the property's type (if a supported type).
*** This method does NOT work for assigning to an existing std::string. In this case you have to use getPropertyValue() instead. Note that you can, though, construct a local string variable by writing, e.g. std::string s = getProperty("myProperty"). ***
Parameters
name :: The name of the property
Returns
The value of the property. Will be cast to the desired type (if a supported type).
Exceptions
std::runtime_error If an attempt is made to assign a property to a different type
Exception::NotFoundError If the property requested does not exist
Implements Mantid::Kernel::IPropertyManager.
Definition at line 211 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::getProperty().
getPropertyValue()
std::string Mantid::Kernel::PropertyManagerOwner::getPropertyValue (const std::string & name) const override virtual
Get the value of a property as a string.
Parameters
name :: The name of the property (case insensitive)
Returns
The value of the named property
Exceptions
Exception::NotFoundError if the named property is unknown
Implements Mantid::Kernel::IPropertyManager.
Definition at line 154 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::getPropertyValue().
isDefault()
bool Mantid::Kernel::PropertyManagerOwner::isDefault (const std::string & name) const
Parameters
name
Returns
True if the property is its default value.
Definition at line 219 of file PropertyManagerOwner.cpp.
References m_properties.
operator=()
PropertyManagerOwner & Mantid::Kernel::PropertyManagerOwner::operator= (const PropertyManagerOwner & po)
Assignment operator.
Definition at line 30 of file PropertyManagerOwner.cpp.
References m_properties.
propertyCount()
size_t Mantid::Kernel::PropertyManagerOwner::propertyCount () const override virtual
Count the number of properties under management.
Returns
The number of properties being managed
Implements Mantid::Kernel::IPropertyManager.
Definition at line 147 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::propertyCount().
removeProperty()
void Mantid::Kernel::PropertyManagerOwner::removeProperty (const std::string & name, const bool delproperty = true) override virtual
Removes the property from management.
Removes the property from properties map.
Parameters
name :: Name of the property to be removed.
delproperty :: if true, delete the named property
Implements Mantid::Kernel::IPropertyManager.
Definition at line 248 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::removeProperty().
resetProperties()
void Mantid::Kernel::PropertyManagerOwner::resetProperties () override virtual
Reset property values back to initial values (blank or default values)
Implements Mantid::Kernel::IPropertyManager.
Definition at line 55 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::resetProperties().
setProperties() [1/2]
void Mantid::Kernel::PropertyManagerOwner::setProperties (const ::Json::Value & jsonValue, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>(), bool createMissing = false) override virtual
Sets all the declared properties from a json object.
Parameters
jsonValue :: A json name value pair collection
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Implements Mantid::Kernel::IPropertyManager.
Definition at line 79 of file PropertyManagerOwner.cpp.
References m_properties.
setProperties() [2/2]
void Mantid::Kernel::PropertyManagerOwner::setProperties (const std::string & propertiesJson, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>(), bool createMissing = false) override virtual
Set the ordered list of properties by one string of values, separated by semicolons.
The string should be a json formatted collection of name value pairs
Parameters
propertiesJson :: The string of property values
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Exceptions
invalid_argument if error in parameters
Implements Mantid::Kernel::IPropertyManager.
Definition at line 68 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::setProperties().
setPropertiesWithString()
void Mantid::Kernel::PropertyManagerOwner::setPropertiesWithString (const std::string & propertiesString, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>()) override virtual
Sets all the declared properties from a string.
Parameters
propertiesString :: A list of name = value pairs separated by a semicolon
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
Implements Mantid::Kernel::IPropertyManager.
Definition at line 90 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::setPropertiesWithString().
setPropertyOrdinal()
void Mantid::Kernel::PropertyManagerOwner::setPropertyOrdinal (const int & index, const std::string & value) override virtual
Set the value of a property by an index N.B.
bool properties must be set using 1/0 rather than true/false
Parameters
index :: The index of the property to assign
value :: The value to assign to the property
Exceptions
std::runtime_error if the property index is too high
Implements Mantid::Kernel::IPropertyManager.
Definition at line 126 of file PropertyManagerOwner.cpp.
References afterPropertySet(), index, m_properties, and value.
Referenced by Mantid::API::Algorithm::setPropertyOrdinal().
setPropertyValue()
void Mantid::Kernel::PropertyManagerOwner::setPropertyValue (const std::string & name, const std::string & value) override virtual
Set the value of a property by string N.B.
bool properties must be set using 1/0 rather than true/false
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError if the named property is unknown
std::invalid_argument If the value is not valid for the property given
Implements Mantid::Kernel::IPropertyManager.
Definition at line 103 of file PropertyManagerOwner.cpp.
References afterPropertySet(), m_properties, and value.
Referenced by Mantid::API::Algorithm::setPropertyValue().
setPropertyValueFromJson()
void Mantid::Kernel::PropertyManagerOwner::setPropertyValueFromJson (const std::string & name, const Json::Value & value) override virtual
Set the value of a property by Json::Value object.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError if the named property is unknown
std::invalid_argument If the value is not valid for the property given
Implements Mantid::Kernel::IPropertyManager.
Definition at line 115 of file PropertyManagerOwner.cpp.
References afterPropertySet(), m_properties, and value.
Referenced by Mantid::API::Algorithm::setPropertyValueFromJson().
splitByTime()
void Mantid::Kernel::PropertyManagerOwner::splitByTime (std::vector< SplittingInterval > & , std::vector< PropertyManager * >) const inline override virtual
Implements Mantid::Kernel::IPropertyManager.
Definition at line 102 of file PropertyManagerOwner.h.
takeProperty()
std::unique_ptr< Property > Mantid::Kernel::PropertyManagerOwner::takeProperty (const size_t index) override virtual
Removes the property from management returning a pointer to it.
Removes a property from the properties map by index and return a pointer to it.
Parameters
index :: index of the property to be removed
Returns
:: pointer to the removed property if found, NULL otherwise
Implements Mantid::Kernel::IPropertyManager.
Definition at line 257 of file PropertyManagerOwner.cpp.
References index, and m_properties.
Referenced by Mantid::API::Algorithm::takeProperty().
validateProperties()
bool Mantid::Kernel::PropertyManagerOwner::validateProperties () const override virtual
Validates all the properties in the collection.
Returns
True if all properties have a valid value
Implements Mantid::Kernel::IPropertyManager.
Definition at line 141 of file PropertyManagerOwner.cpp.
References m_properties.
Referenced by Mantid::API::Algorithm::validateProperties().
Member Data Documentation
m_properties
std::shared_ptr<PropertyManager> Mantid::Kernel::PropertyManagerOwner::m_properties private
Shared pointer to the 'real' property manager.
Definition at line 118 of file PropertyManagerOwner.h.
Referenced by afterPropertySet(), asJson(), asString(), clear(), declareOrReplaceProperty(), declareProperty(), existsProperty(), getPointerToProperty(), getPointerToPropertyOrdinal(), getProperties(), getProperty(), getPropertyValue(), isDefault(), operator=(), propertyCount(), removeProperty(), resetProperties(), setProperties(), setPropertiesWithString(), setPropertyOrdinal(), setPropertyValue(), setPropertyValueFromJson(), takeProperty(), and validateProperties().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/PropertyManagerOwner.h
Framework/Kernel/src/PropertyManagerOwner.cpp