Mantid: Mantid::Algorithms::MultipleScatteringCorrection Class Reference
Mantid::Algorithms::MultipleScatteringCorrection Class Reference final
MultipleScatteringCorrection : TODO: DESCRIPTION.
#include <MultipleScatteringCorrection.h>
Public Member Functions
const std::string category () const override
Algorithm's category.
const std::string name () const override
Algorithm's name.
const std::vector< std::string > seeAlso () const override
Algorithm's see also.
const std::string summary () const override
Algorithm's summary.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Protected Attributes
Kernel::V3D m_beamDirection
The direction of the beam.
double m_containerElementSize
the size of the integration element for container in meters
API::MatrixWorkspace_sptr m_inputWS
A pointer to the input workspace.
int64_t m_num_lambda
The number of points in wavelength, the rest is interpolated linearly.
double m_sampleElementSize
The size of the integration element for sample in meters.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Private Member Functions
void calculateL12s (const MultipleScatteringCorrectionDistGraber &distGraber, std::vector< double > &L12s, const Geometry::IObject &shape)
calculate L12 for single component case
void calculateL12s (const MultipleScatteringCorrectionDistGraber &distGraberContainer, const MultipleScatteringCorrectionDistGraber &distGraberSample, std::vector< double > &L12sContainer, std::vector< double > &L12sSample, const Geometry::IObject &shapeContainer, const Geometry::IObject &shapeSample)
void calculateL2Ds (const MultipleScatteringCorrectionDistGraber &distGraber, const IDetector &detector, std::vector< double > &L2Ds, const Geometry::IObject &shape) const
Calculate distance between exiting element to the detector for single component case.
void calculateL2Ds (const MultipleScatteringCorrectionDistGraber &distGraberContainer, const MultipleScatteringCorrectionDistGraber &distGraberSample, const IDetector &detector, std::vector< double > &container_L2Ds, std::vector< double > &sample_L2Ds, const Geometry::IObject &shapeContainer, const Geometry::IObject &shapeSample) const
void calculateLS1s (const MultipleScatteringCorrectionDistGraber &distGraber, std::vector< double > &LS1s, const Geometry::IObject &shape) const
compute LS1s within given shape for single component case
void calculateLS1s (const MultipleScatteringCorrectionDistGraber &distGraberContainer, const MultipleScatteringCorrectionDistGraber &distGraberSample, std::vector< double > &LS1sContainer, std::vector< double > &LS1sSample, const Geometry::IObject &shapeContainer, const Geometry::IObject &shapeSample) const
compute LS1s within given shape for sample and container case
void calculateSampleAndContainer (const API::MatrixWorkspace_sptr &outws)
calculate the multiple scattering factor (0, 1) for sample and container case
void calculateSingleComponent (const API::MatrixWorkspace_sptr &outws, const Geometry::IObject &shape, const double elementSize)
calculate the correction factor per detector for sample only case
void exec () override
execute the algorithm
void init () override
interface initialisation method
void pairWiseSum (double &A1, double &A2, const double linearCoefAbs, const MultipleScatteringCorrectionDistGraber &distGraber, const std::vector< double > &LS1s, const std::vector< double > &L12s, const std::vector< double > &L2Ds, const int64_t startIndex, const int64_t endIndex) const
void pairWiseSum (double &A1, double &A2, const double linearCoefAbsContainer, const double linearCoefAbsSample, const int64_t numVolumeElementsContainer, const int64_t numVolumeElementsTotal, const double totScatterCoefContainer, const double totScatterCoefSample, const std::vector< double > &elementVolumes, const std::vector< double > &LS1sContainer, const std::vector< double > &LS1sSample, const std::vector< double > &L12sContainer, const std::vector< double > &L12sSample, const std::vector< double > &L2DsContainer, const std::vector< double > &L2DsSample, const int64_t startIndex, const int64_t endIndex) const
void parseInputs ()
parse and assign corresponding values from input properties
std::map< std::string, std::string > validateInputs () override
validate the inputs
Private Attributes
int64_t m_xStep
The step in bin number between adjacent points for linear interpolation.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
MultipleScatteringCorrection : TODO: DESCRIPTION.
Definition at line 22 of file MultipleScatteringCorrection.h.
Member Function Documentation
calculateL12s() [1/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateL12s (const MultipleScatteringCorrectionDistGraber & distGraber, std::vector< double > & L12s, const Geometry::IObject & shape) private
calculate L12 for single component case
Parameters
distGraber
L12s
shape
Definition at line 639 of file MultipleScatteringCorrection.cpp.
References Mantid::Geometry::Track::clearIntersectionResults(), Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Geometry::Track::reset(), and Mantid::Kernel::threadSafe().
Referenced by calculateSampleAndContainer(), and calculateSingleComponent().
calculateL12s() [2/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateL12s (const MultipleScatteringCorrectionDistGraber & distGraberContainer, const MultipleScatteringCorrectionDistGraber & distGraberSample, std::vector< double > & L12sContainer, std::vector< double > & L12sSample, const Geometry::IObject & shapeContainer, const Geometry::IObject & shapeSample) private
Definition at line 684 of file MultipleScatteringCorrection.cpp.
References Mantid::Geometry::Track::clearIntersectionResults(), Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Geometry::Track::reset(), and Mantid::Kernel::threadSafe().
calculateL2Ds() [1/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds (const MultipleScatteringCorrectionDistGraber & distGraber, const IDetector & detector, std::vector< double > & L2Ds, const Geometry::IObject & shape) const private
Calculate distance between exiting element to the detector for single component case.
Parameters
distGraber Pointer of distGraber that helps discretize the shape
detector Pointer of the detector object (pixel)
L2Ds Vector to container the distance from 2nd scattering element to detector within the material
shape Pointer of the shape object
Definition at line 754 of file MultipleScatteringCorrection.cpp.
References Mantid::Geometry::Track::clearIntersectionResults(), Mantid::Geometry::IDetector::getPhi(), Mantid::Geometry::IComponent::getPos(), Mantid::Geometry::IDetector::getTwoTheta(), Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, Mantid::Geometry::IDetector::nDets(), Mantid::Kernel::V3D::norm(), Mantid::Geometry::Track::reset(), and Mantid::Kernel::V3D::spherical().
Referenced by calculateSampleAndContainer(), and calculateSingleComponent().
calculateL2Ds() [2/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds (const MultipleScatteringCorrectionDistGraber & distGraberContainer, const MultipleScatteringCorrectionDistGraber & distGraberSample, const IDetector & detector, std::vector< double > & container_L2Ds, std::vector< double > & sample_L2Ds, const Geometry::IObject & shapeContainer, const Geometry::IObject & shapeSample) const private
Definition at line 776 of file MultipleScatteringCorrection.cpp.
References Mantid::Geometry::IDetector::getPhi(), Mantid::Geometry::IComponent::getPos(), Mantid::Geometry::IDetector::getTwoTheta(), Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, Mantid::Geometry::IDetector::nDets(), Mantid::Kernel::V3D::norm(), Mantid::Kernel::V3D::spherical(), and vec.
calculateLS1s() [1/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateLS1s (const MultipleScatteringCorrectionDistGraber & distGraber, std::vector< double > & LS1s, const Geometry::IObject & shape) const private
compute LS1s within given shape for single component case
Parameters
distGraber Pointer to distGraber instance that does the heavy lifting for discretization
LS1s Vector to store source -> 1st scattering element distance within material
shape Object shape that defines the boundary of material
Definition at line 560 of file MultipleScatteringCorrection.cpp.
References Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, and vec.
Referenced by calculateSampleAndContainer(), and calculateSingleComponent().
calculateLS1s() [2/2]
void Mantid::Algorithms::MultipleScatteringCorrection::calculateLS1s (const MultipleScatteringCorrectionDistGraber & distGraberContainer, const MultipleScatteringCorrectionDistGraber & distGraberSample, std::vector< double > & LS1sContainer, std::vector< double > & LS1sSample, const Geometry::IObject & shapeContainer, const Geometry::IObject & shapeSample) const private
compute LS1s within given shape for sample and container case
Parameters
distGraberContainer Pointer of distGraber that helps discretize container
distGraberSample Pointer of distGraber that helps discretize sample
LS1sContainer Vector to store source -> 1st scattering element distance within container
LS1sSample Vector to store source -> 1st scattering element distance within sample
shapeContainer Pointer of shape object defines the container
shapeSample Pointer of shape object defines the sample
Definition at line 587 of file MultipleScatteringCorrection.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementPositions, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, Mantid::Kernel::Logger::notice(), and vec.
calculateSampleAndContainer()
void Mantid::Algorithms::MultipleScatteringCorrection::calculateSampleAndContainer (const API::MatrixWorkspace_sptr & outws) private
calculate the multiple scattering factor (0, 1) for sample and container case
Parameters
outws pointer for workspace containing the multiple scattering correction factor for each detector.
Definition at line 371 of file MultipleScatteringCorrection.cpp.
References Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::cacheLS1(), calculateL12s(), calculateL2Ds(), calculateLS1s(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_beamDirection, m_containerElementSize, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementVolumes, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, m_sampleElementSize, m_xStep, Mantid::Kernel::Logger::notice(), pairWiseSum(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Kernel::ProgressBase::report(), and Mantid::Kernel::threadSafe().
Referenced by exec().
calculateSingleComponent()
void Mantid::Algorithms::MultipleScatteringCorrection::calculateSingleComponent (const API::MatrixWorkspace_sptr & outws, const Geometry::IObject & shape, const double elementSize) private
calculate the correction factor per detector for sample only case
Parameters
outws
shape
elementSize length of cube size used to rasterize given shape
Definition at line 255 of file MultipleScatteringCorrection.cpp.
References Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::cacheLS1(), calculateL12s(), calculateL2Ds(), calculateLS1s(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_beamDirection, m_inputWS, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, m_xStep, Mantid::Geometry::IObject::material(), Mantid::Kernel::Logger::notice(), pairWiseSum(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Kernel::ProgressBase::report(), rho, and Mantid::Kernel::threadSafe().
Referenced by exec().
category()
const std::string Mantid::Algorithms::MultipleScatteringCorrection::category () const inline override virtual
Algorithm's category.
Implements Mantid::API::IAlgorithm.
Definition at line 31 of file MultipleScatteringCorrection.h.
exec()
void Mantid::Algorithms::MultipleScatteringCorrection::exec () override private virtual
execute the algorithm
Implements Mantid::API::Algorithm.
Definition at line 143 of file MultipleScatteringCorrection.cpp.
References calculateSampleAndContainer(), calculateSingleComponent(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getProperty(), group, m_containerElementSize, m_inputWS, m_sampleElementSize, parseInputs(), and Mantid::Kernel::IPropertyManager::setProperty().
init()
void Mantid::Algorithms::MultipleScatteringCorrection::init () override private virtual
interface initialisation method
Implements Mantid::API::Algorithm.
Definition at line 75 of file MultipleScatteringCorrection.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::API::SampleValidator::Material, Mantid::Kernel::Direction::Output, and Mantid::API::SampleValidator::Shape.
name()
const std::string Mantid::Algorithms::MultipleScatteringCorrection::name () const inline override virtual
Algorithm's name.
Implements Mantid::API::Algorithm.
Definition at line 25 of file MultipleScatteringCorrection.h.
pairWiseSum() [1/2]
void Mantid::Algorithms::MultipleScatteringCorrection::pairWiseSum (double & A1, double & A2, const double linearCoefAbs, const MultipleScatteringCorrectionDistGraber & distGraber, const std::vector< double > & LS1s, const std::vector< double > & L12s, const std::vector< double > & L2Ds, const int64_t startIndex, const int64_t endIndex) const private
Definition at line 818 of file MultipleScatteringCorrection.cpp.
References Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_elementVolumes, Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::m_numVolumeElements, and pairWiseSum().
Referenced by calculateSampleAndContainer(), calculateSingleComponent(), pairWiseSum(), and pairWiseSum().
pairWiseSum() [2/2]
void Mantid::Algorithms::MultipleScatteringCorrection::pairWiseSum (double & A1, double & A2, const double linearCoefAbsContainer, const double linearCoefAbsSample, const int64_t numVolumeElementsContainer, const int64_t numVolumeElementsTotal, const double totScatterCoefContainer, const double totScatterCoefSample, const std::vector< double > & elementVolumes, const std::vector< double > & LS1sContainer, const std::vector< double > & LS1sSample, const std::vector< double > & L12sContainer, const std::vector< double > & L12sSample, const std::vector< double > & L2DsContainer, const std::vector< double > & L2DsSample, const int64_t startIndex, const int64_t endIndex) const private
Definition at line 861 of file MultipleScatteringCorrection.cpp.
References pairWiseSum().
parseInputs()
void Mantid::Algorithms::MultipleScatteringCorrection::parseInputs () private
parse and assign corresponding values from input properties
Definition at line 222 of file MultipleScatteringCorrection.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isDefault(), m_beamDirection, m_containerElementSize, m_inputWS, m_num_lambda, m_sampleElementSize, and m_xStep.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::Algorithms::MultipleScatteringCorrection::seeAlso () const inline override virtual
Algorithm's see also.
Implements Mantid::API::IAlgorithm.
Definition at line 40 of file MultipleScatteringCorrection.h.
summary()
const std::string Mantid::Algorithms::MultipleScatteringCorrection::summary () const inline override virtual
Algorithm's summary.
Implements Mantid::API::Algorithm.
Definition at line 34 of file MultipleScatteringCorrection.h.
validateInputs()
std::map< std::string, std::string > Mantid::Algorithms::MultipleScatteringCorrection::validateInputs (void) override private virtual
validate the inputs
Returns
std::map<std::string, std::string>
Implements Mantid::API::IAlgorithm.
Definition at line 115 of file MultipleScatteringCorrection.cpp.
References Mantid::API::Algorithm::getProperty(), and m_inputWS.
version()
int Mantid::Algorithms::MultipleScatteringCorrection::version () const inline override virtual
Algorithm's version.
Implements Mantid::API::Algorithm.
Definition at line 28 of file MultipleScatteringCorrection.h.
Member Data Documentation
m_beamDirection
Kernel::V3D Mantid::Algorithms::MultipleScatteringCorrection::m_beamDirection protected
The direction of the beam.
Definition at line 46 of file MultipleScatteringCorrection.h.
Referenced by calculateSampleAndContainer(), calculateSingleComponent(), and parseInputs().
m_containerElementSize
double Mantid::Algorithms::MultipleScatteringCorrection::m_containerElementSize protected
the size of the integration element for container in meters
Definition at line 49 of file MultipleScatteringCorrection.h.
Referenced by calculateSampleAndContainer(), exec(), and parseInputs().
m_inputWS
API::MatrixWorkspace_sptr Mantid::Algorithms::MultipleScatteringCorrection::m_inputWS protected
A pointer to the input workspace.
Definition at line 45 of file MultipleScatteringCorrection.h.
Referenced by calculateL12s(), calculateL12s(), calculateLS1s(), calculateLS1s(), calculateSampleAndContainer(), calculateSingleComponent(), exec(), parseInputs(), and validateInputs().
m_num_lambda
int64_t Mantid::Algorithms::MultipleScatteringCorrection::m_num_lambda protected
The number of points in wavelength, the rest is interpolated linearly.
Definition at line 47 of file MultipleScatteringCorrection.h.
Referenced by parseInputs().
m_sampleElementSize
double Mantid::Algorithms::MultipleScatteringCorrection::m_sampleElementSize protected
The size of the integration element for sample in meters.
Definition at line 48 of file MultipleScatteringCorrection.h.
Referenced by calculateSampleAndContainer(), exec(), and parseInputs().
m_xStep
int64_t Mantid::Algorithms::MultipleScatteringCorrection::m_xStep private
The step in bin number between adjacent points for linear interpolation.
Definition at line 106 of file MultipleScatteringCorrection.h.
Referenced by calculateSampleAndContainer(), calculateSingleComponent(), and parseInputs().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/MultipleScatteringCorrection.h
Framework/Algorithms/src/MultipleScatteringCorrection.cpp