Mantid: Framework/PythonInterface/mantid/api/src/Exports/IPreview.cpp File Reference
IPreview.cpp File Reference
#include "MantidAPI/IPreview.h"
#include "MantidAPI/Workspace.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/register_ptr_to_python.hpp>
Functions
void export_IPreview ()
Function Documentation
export_IPreview()
void export_IPreview ()
Definition at line 26 of file IPreview.cpp.
References Mantid::API::IPreview::facility(), Mantid::API::IPreview::IVIEW, Mantid::API::IPreview::name(), Mantid::API::IPreview::PLOT1D, Mantid::API::IPreview::PLOT2D, Mantid::API::IPreview::SVIEW, Mantid::API::IPreview::technique(), and Mantid::API::IPreview::type().