Mantid: Mantid::DataObjects::CalculateReflectometryKiKf Class Reference
Mantid::DataObjects::CalculateReflectometryKiKf Class Reference
class CalculateReflectometryKiKf: Calculation type for converting to ki or kf given a theta value (in degrees) and a wavelength
#include <CalculateReflectometryKiKf.h>
Public Member Functions
double calculateDim0 (double wavelength) const override
Executes the calculation to determine Ki.
double calculateDim1 (double wavelength) const override
Executes the calculation to determine Kf.
CalculateReflectometryKiKf (int version)
Constructor.
Mantid::Geometry::Quadrilateral createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) override
void setThetaFinal (double thetaFinal) override
Setter for the final theta value require for the calculation.
void setTwoTheta (double twoTheta) override
Set the final theta value from the detector twoTheta angle.
void updateThetaIncident (double thetaIncident) override
Setter for the incident theta value require for the calculation.
Public Member Functions inherited from Mantid::DataObjects::CalculateReflectometry
CalculateReflectometry (int version)
void setThetaIncident (double thetaIncident)
Setter for the incident theta value require for the calculation.
virtual ~CalculateReflectometry ()=default
Private Attributes
double m_sin_theta_f
double m_sin_theta_i
Additional Inherited Members
Protected Attributes inherited from Mantid::DataObjects::CalculateReflectometry
double m_theta_i {0.0}
int m_version
const double to_radians_factor = M_PI / 180.0
Detailed Description
class CalculateReflectometryKiKf: Calculation type for converting to ki or kf given a theta value (in degrees) and a wavelength
Definition at line 17 of file CalculateReflectometryKiKf.h.
Constructor & Destructor Documentation
CalculateReflectometryKiKf()
Mantid::DataObjects::CalculateReflectometryKiKf::CalculateReflectometryKiKf (int version) inline
Constructor.
Definition at line 26 of file CalculateReflectometryKiKf.h.
Member Function Documentation
calculateDim0()
double Mantid::DataObjects::CalculateReflectometryKiKf::calculateDim0 (double wavelength) const inline override virtual
Executes the calculation to determine Ki.
Parameters
wavelength : wavelength in Angstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 57 of file CalculateReflectometryKiKf.h.
References m_sin_theta_i.
Referenced by createQuad().
calculateDim1()
double Mantid::DataObjects::CalculateReflectometryKiKf::calculateDim1 (double wavelength) const inline override virtual
Executes the calculation to determine Kf.
Parameters
wavelength : wavelength in Angstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 66 of file CalculateReflectometryKiKf.h.
References m_sin_theta_f.
Referenced by createQuad().
createQuad()
Mantid::Geometry::Quadrilateral Mantid::DataObjects::CalculateReflectometryKiKf::createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) inline override virtual
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 70 of file CalculateReflectometryKiKf.h.
References Mantid::Geometry::Quadrilateral::at(), calculateDim0(), calculateDim1(), setTwoTheta(), Mantid::Geometry::Quadrilateral::shiftVertexesClockwise(), Mantid::Kernel::V2D::X(), and Mantid::Kernel::V2D::Y().
setThetaFinal()
void Mantid::DataObjects::CalculateReflectometryKiKf::setThetaFinal (double thetaFinal) inline override virtual
Setter for the final theta value require for the calculation.
Internally pre-calculates and caches to cos theta_f for speed.
Parameters
thetaFinal final theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 40 of file CalculateReflectometryKiKf.h.
References m_sin_theta_f, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Referenced by setTwoTheta().
setTwoTheta()
void Mantid::DataObjects::CalculateReflectometryKiKf::setTwoTheta (double twoTheta) inline override virtual
Set the final theta value from the detector twoTheta angle.
Parameters
twoTheta detector twoTheta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 46 of file CalculateReflectometryKiKf.h.
References Mantid::DataObjects::CalculateReflectometry::m_theta_i, Mantid::DataObjects::CalculateReflectometry::m_version, setThetaFinal(), and Mantid::Kernel::twoTheta.
Referenced by createQuad().
updateThetaIncident()
void Mantid::DataObjects::CalculateReflectometryKiKf::updateThetaIncident (double thetaIncident) inline override virtual
Setter for the incident theta value require for the calculation.
Internally pre-calculates and caches to cos theta for speed.
Parameters
thetaIncident incident theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 33 of file CalculateReflectometryKiKf.h.
References m_sin_theta_i, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Member Data Documentation
m_sin_theta_f
double Mantid::DataObjects::CalculateReflectometryKiKf::m_sin_theta_f private
Definition at line 20 of file CalculateReflectometryKiKf.h.
Referenced by calculateDim1(), and setThetaFinal().
m_sin_theta_i
double Mantid::DataObjects::CalculateReflectometryKiKf::m_sin_theta_i private
Definition at line 19 of file CalculateReflectometryKiKf.h.
Referenced by calculateDim0(), and updateThetaIncident().
The documentation for this class was generated from the following file:
Framework/DataObjects/inc/MantidDataObjects/CalculateReflectometryKiKf.h