Mantid: Mantid::DataObjects::EventWorkspace Class Reference
Mantid::DataObjects::EventWorkspace Class Reference
This class is intended to fulfill the design specified in <https://github.com/mantidproject/documents/tree/master/Design/Event WorkspaceDetailed Design Document.doc>
#include <EventWorkspace.h>
Public Member Functions
std::size_t blocksize () const override
Get the blocksize, aka the number of bins in the histogram.
void clearMRU () const override
Clears the MRU lists.
std::unique_ptr< EventWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< EventWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
const MantidVec & dataDx (const std::size_t) const override
Deprecated, use dx() instead.
MantidVec & dataDx (const std::size_t) override
Deprecated, use mutableDx() instead.
const MantidVec & dataE (const std::size_t) const override
Deprecated, use e() instead.
MantidVec & dataE (const std::size_t) override
Deprecated, use mutableE() instead.
const MantidVec & dataX (const std::size_t) const override
Deprecated, use x() instead.
MantidVec & dataX (const std::size_t) override
Deprecated, use mutableX() instead.
const MantidVec & dataY (const std::size_t) const override
Deprecated, use y() instead.
MantidVec & dataY (const std::size_t) override
Deprecated, use mutableY() instead.
EventWorkspace ()
void generateHistogram (const std::size_t index, const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const override
Generate a new histogram from specified event list at the given index.
void generateHistogramPulseTime (const std::size_t index, const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const
Generate a new histogram from specified event list at the given index.
Mantid::API::EventType getEventType () const override
Get the EventType of the most-specialized EventList in the workspace.
double getEventXMax () const
Get them maximum x-value for the events themselves, ignoring the histogram representation.
double getEventXMin () const
Get them minimum x-value for the events themselves, ignoring the histogram representation.
void getEventXMinMax (double &xmin, double &xmax) const
Get them minimum and maximum x-values for the events themselves, ignoring the histogram representation.
void getIntegratedSpectra (std::vector< double > &out, const double minX, const double maxX, const bool entireRange) const override
Integrate all the spectra in the matrix workspace within the range given.
std::size_t getMaxNumberBins () const override
Returns the maximum number of bins in a workspace (works on ragged data).
size_t getMemorySize () const override
Returns the amount of memory used in bytes.
std::size_t getNumberBins (const std::size_t &index) const override
Returns the number of bins for a given histogram index.
std::size_t getNumberEvents () const override
The total number of events across all of the spectra.
std::size_t getNumberHistograms () const override
Get the number of histograms, usually the same as the number of pixels or detectors.
Mantid::Types::Core::DateAndTime getPulseTimeMax () const override
Get the maximum pulse time for events accross the entire workspace.
Mantid::Types::Core::DateAndTime getPulseTimeMin () const override
Get the minimum pulse time for events accross the entire workspace.
void getPulseTimeMinMax (Mantid::Types::Core::DateAndTime &xmin, Mantid::Types::Core::DateAndTime &xmax) const
Get the maximum and mimumum pulse time for events accross the entire workspace.
EventSortType getSortType () const
const EventList & getSpectrum (const size_t index) const override
Return const reference to EventList at the given workspace index.
EventList & getSpectrum (const size_t index) override
Return the underlying ISpectrum ptr at the given workspace index.
EventList * getSpectrumUnsafe (const size_t index)
Returns a pointer to the EventList for a given spectrum in a timely manner.
Mantid::Types::Core::DateAndTime getTimeAtSampleMax (double tofOffset=0) const override
Get the maximum time at sample for events across the entire workspace.
Mantid::Types::Core::DateAndTime getTimeAtSampleMin (double tofOffset=0) const override
Get the minimum time at sample for events across the entire workspace.
double getTofMax () const override
double getTofMin () const override
const std::string id () const override
Return the workspace typeID.
void init (const HistogramData::Histogram &histogram) override
void init (const std::size_t &, const std::size_t &, const std::size_t &) override
Initialize the pixels.
bool isHistogramData () const override
Returns true always - an EventWorkspace always represents histogramm-able data.
bool isRaggedWorkspace () const override
Returns true if the workspace is ragged (has differently sized spectra).
std::size_t MRUSize () const
Return how many entries in the Y MRU list are used.
EventWorkspace & operator= (const EventWorkspace &other)=delete
Kernel::cow_ptr< HistogramData::HistogramX > refX (const std::size_t) const override
Deprecated, use sharedX() instead.
void resetAllXToSingleBin () override
Set all Histogram X vectors to a single bin with boundaries that fit the TOF of all events across all spectra.
void setAllX (const HistogramData::BinEdges &x) override
Set all histogram X vectors.
std::size_t size () const override
The total size of the workspace.
void sortAll (EventSortType sortType, Mantid::API::Progress *prog) const
void switchEventType (const Mantid::API::EventType type)
Switch all event lists to the given event type.
bool threadSafe () const override
Returns true if the EventWorkspace is safe for multithreaded operations.
~EventWorkspace () override
Public Member Functions inherited from Mantid::API::IEventWorkspace
IEventWorkspace_uptr clone () const
Returns a clone of the workspace.
IEventWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
IEventWorkspace ()
IEventWorkspace & operator= (const IEventWorkspace &)=delete
Public Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace_uptr clone () const
Returns a clone of the workspace.
MatrixWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const Indexing::IndexInfo & indexInfo () const
Returns a const reference to the IndexInfo object of the workspace.
void initialize (const Indexing::IndexInfo &indexInfo, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const std::size_t &XLength, const std::size_t &YLength)
Initialize the workspace.
MatrixWorkspace & operator= (const MatrixWorkspace &other)=delete
void setIndexInfo (const Indexing::IndexInfo &indexInfo)
Sets the IndexInfo object of the workspace.
const std::string toString () const override
Serializes the object to a string.
const std::string toString () const override
String description of state.
~MatrixWorkspace () override
Delete.
std::shared_ptr< const Geometry::IDetector > getDetector (const size_t workspaceIndex) const
Get the effective detector for the given spectrum.
double detectorTwoTheta (const Geometry::IDetector &det) const
Returns the 2Theta scattering angle for a detector.
double detectorSignedTwoTheta (const Geometry::IDetector &det) const
Returns the signed 2Theta scattering angle for a detector.
virtual void updateSpectraUsing (const SpectrumDetectorMapping &map)
void rebuildSpectraMapping (const bool includeMonitors=true, const specnum_t specNumOffset=1)
Build the default spectra mapping, most likely wanted after an instrument update.
spec2index_map getSpectrumToWorkspaceIndexMap () const
Return a map where: KEY is the Spectrum # VALUE is the Workspace Index.
detid2index_map getDetectorIDToWorkspaceIndexMap (bool throwIfMultipleDets=false, bool ignoreIfNoValidDets=false) const
Return a map where: KEY is the DetectorID (pixel ID) VALUE is the Workspace Index.
virtual std::vector< size_t > getDetectorIDToWorkspaceIndexVector (detid_t &offset, bool throwIfMultipleDets=false) const
Return a vector where: The index into the vector = DetectorID (pixel ID) + offset The value at that index = the corresponding Workspace Index.
virtual std::vector< size_t > getSpectrumToWorkspaceIndexVector (specnum_t &offset) const
Return a vector where: The index into the vector = spectrum number + offset The value at that index = the corresponding Workspace Index.
std::vector< size_t > getIndicesFromSpectra (const std::vector< specnum_t > &spectraList) const
Converts a list of spectrum numbers to the corresponding workspace indices.
size_t getIndexFromSpectrumNumber (const specnum_t specNo) const
Given a spectrum number, find the corresponding workspace index.
std::vector< size_t > getIndicesFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding workspace indices.
std::vector< specnum_t > getSpectraFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding spectrum numbers.
bool hasGroupedDetectors () const
Does the workspace has any grouped detectors?
virtual size_t getMemorySizeForXAxes () const
Returns the memory used (in bytes) by the X axes, handling ragged bins.
void setTitle (const std::string &) override
Sets MatrixWorkspace title.
const std::string getTitle () const override
Gets MatrixWorkspace title (same as Run object run_title property)
void setPlotType (const std::string &)
Sets MatrixWorkspace plot_type.
std::string getPlotType () const
Gets MatrixWorkspace plot_type.
void setMarkerStyle (const std::string &markerType)
Set the marker style for plotting.
std::string getMarkerStyle () const
Get the marker style for plotting.
void setMarkerSize (const float markerSize)
Set the size of the marker for plotting.
float getMarkerSize () const
Get the size of the marker for plotting.
virtual Types::Core::DateAndTime getFirstPulseTime () const
Return the time of the first pulse received, by accessing the run's sample logs to find the proton_charge.
Types::Core::DateAndTime getLastPulseTime () const
Return the time of the last pulse received, by accessing the run's sample logs to find the proton_charge.
std::size_t yIndexOfX (const double xValue, const std::size_t &index=0, const double tolerance=0.0) const
Returns the y index which corresponds to the X Value provided.
HistogramData::Histogram histogram (const size_t index) const
Returns the Histogram at the given workspace index.
template<typename... T>
void setHistogram (const size_t index, T &&...data) &
void convertToCounts (const size_t index)
void convertToFrequencies (const size_t index)
HistogramData::BinEdges binEdges (const size_t index) const
HistogramData::Points points (const size_t index) const
HistogramData::PointStandardDeviations pointStandardDeviations (const size_t index) const
template<typename... T>
void setBinEdges (const size_t index, T &&...data) &
template<typename... T>
void setPoints (const size_t index, T &&...data) &
template<typename... T>
void setPointVariances (const size_t index, T &&...data) &
template<typename... T>
void setPointStandardDeviations (const size_t index, T &&...data) &
HistogramData::Counts counts (const size_t index) const
HistogramData::CountVariances countVariances (const size_t index) const
HistogramData::CountStandardDeviations countStandardDeviations (const size_t index) const
HistogramData::Frequencies frequencies (const size_t index) const
HistogramData::FrequencyVariances frequencyVariances (const size_t index) const
HistogramData::FrequencyStandardDeviations frequencyStandardDeviations (const size_t index) const
template<typename... T>
void setCounts (const size_t index, T &&...data) &
template<typename... T>
void setCountVariances (const size_t index, T &&...data) &
template<typename... T>
void setCountStandardDeviations (const size_t index, T &&...data) &
template<typename... T>
void setFrequencies (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyVariances (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyStandardDeviations (const size_t index, T &&...data) &
const HistogramData::HistogramX & x (const size_t index) const
const HistogramData::HistogramY & y (const size_t index) const
const HistogramData::HistogramE & e (const size_t index) const
const HistogramData::HistogramDx & dx (const size_t index) const
HistogramData::HistogramX & mutableX (const size_t index) &
HistogramData::HistogramDx & mutableDx (const size_t index) &
HistogramData::HistogramY & mutableY (const size_t index) &
HistogramData::HistogramE & mutableE (const size_t index) &
Kernel::cow_ptr< HistogramData::HistogramX > sharedX (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramY > sharedY (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramE > sharedE (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramDx > sharedDx (const size_t index) const
void setSharedX (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &x) &
void setSharedDx (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramDx > &dx) &
void setSharedY (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramY > &y) &
void setSharedE (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramE > &e) &
void resizeHistogram (const size_t index, size_t n) &
size_t histogramSize (const size_t index) const
const MantidVec & readX (std::size_t const index) const
Deprecated, use x() instead.
const MantidVec & readY (std::size_t const index) const
Deprecated, use y() instead.
const MantidVec & readE (std::size_t const index) const
Deprecated, use e() instead.
const MantidVec & readDx (size_t const index) const
Deprecated, use dx() instead.
virtual double getXMin () const
virtual double getXMax () const
virtual void getXMinMax (double &xmin, double &xmax) const
virtual void setX (const std::size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual void setX (const std::size_t index, const std::shared_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual bool hasDx (const std::size_t index) const
Probes if DX (X Error) values were set on a particular spectrum.
std::vector< double > getIntegratedCountsForWorkspaceIndices (const std::vector< size_t > &workspaceIndices, const double minX, const double maxX, const bool entireRange) const
std::pair< size_t, double > getXIndex (size_t i, double x, bool isLeft=true, size_t start=0) const
Return an index in the X vector for an x-value close to a given value.
int axes () const
virtual Axis * getAxis (const std::size_t &axisIndex) const
Get a non owning pointer to a workspace axis.
void replaceAxis (const std::size_t &axisIndex, std::unique_ptr< Axis > newAxis)
Replaces one of the workspace's axes with the new one provided.
size_t numberOfAxis () const
Will return the number of Axis currently stored in the workspace it is not always safe to assume it is just 2.
virtual bool isCommonLogBins () const
Returns true if the workspace contains common X bins with log spacing.
virtual bool isCommonBins () const
Returns true if the workspace contains common X bins.
virtual bool isIntegerBins () const
Returns true if the workspace has common, integer X bins.
const std::string & YUnit () const
void setYUnit (const std::string &newUnit)
Sets a new unit for the data (Y axis) in the workspace.
std::string YUnitLabel (bool useLatex=false, bool plotAsDistribution=false) const
Returns a caption for the units of the data in the workspace.
void setYUnitLabel (const std::string &newLabel)
Sets a new caption for the data (Y axis) in the workspace.
bool isDistribution () const
Are the Y-values dimensioned?
void setDistribution (bool newValue)
Set the flag for whether the Y-values are dimensioned.
void maskBin (const size_t &workspaceIndex, const size_t &binIndex, const double &weight=1.0)
Called by the algorithm MaskBins to mask a single bin for the first time, algorithms that later propagate the the mask from an input to the output should call flagMasked() instead.
void flagMasked (const size_t &index, const size_t &binIndex, const double &weight=1.0)
Writes the masking weight to m_masks (doesn't alter y-values).
bool hasMaskedBins (const size_t &workspaceIndex) const
Does this spectrum contain any masked bins.
bool hasAnyMaskedBins () const
Does this workspace contain any masked bins.
const MaskList & maskedBins (const size_t &workspaceIndex) const
Returns the list of masked bins for a spectrum.
std::vector< size_t > maskedBinsIndices (const size_t &workspaceIndex) const
void setMaskedBins (const size_t workspaceIndex, const MaskList &maskedBins)
Set the list of masked bins for given workspaceIndex.
void setUnmaskedBins (const size_t workspaceIndex)
Removes the mask from an index.
virtual void setMonitorWorkspace (const std::shared_ptr< MatrixWorkspace > &monitorWS)
Sets the internal monitor workspace to the provided workspace.
std::shared_ptr< MatrixWorkspace > monitorWorkspace () const
Returns a pointer to the internal monitor workspace.
void loadInstrumentNexus (Nexus::File *file)
size_t getNumDims () const override
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const override
Get a dimension.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const override
Get a dimension.
uint64_t getNPoints () const override
Gets the number of points available on the workspace.
uint64_t getNEvents () const override
Get the number of points available on the workspace.
LinePlot getLinePlot (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const override
Generate a line plot through the matrix workspace.
signal_t getSignalAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
signal_t getSignalWithMaskAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
std::vector< std::unique_ptr< IMDIterator > > createIterators (size_t suggestedNumCores=1, Mantid::Geometry::MDImplicitFunction *function=nullptr) const override
Create iterators.
void setMDMasking (std::unique_ptr< Mantid::Geometry::MDImplicitFunction > maskingRegion) override
Apply masking.
void clearMDMasking () override
Clear exsting masking.
Mantid::Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const override
virtual bool hasOrientedLattice () const override
virtual std::pair< int64_t, int64_t > findY (double value, const std::pair< int64_t, int64_t > &idx={0, 0}) const
Find first index in Y equal to value.
std::pair< size_t, size_t > getImageStartEndXIndices (size_t i, double startX, double endX) const
Get start and end x indices for images.
MantidImage_sptr getImageY (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Ys.
MantidImage_sptr getImageE (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Es.
virtual void setImageY (const MantidImage &image, size_t start=0, bool parallelExecution=true)
Copy the data (Y's) from an image to this workspace.
virtual void setImageE (const MantidImage &image, size_t start=0, bool parallelExecution=true)
Copy the data from an image to this workspace's errors.
void invalidateCachedSpectrumNumbers ()
void invalidateCommonBinsFlag ()
Invalidates the commons bins flag.
Public Member Functions inherited from Mantid::API::IMDWorkspace
std::string changeQConvention ()
virtual void clearFileBacked (bool)
if a workspace was filebacked, this should clear file-based status, delete file-based information and close related files.
std::unique_ptr< IMDWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< IMDWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
std::unique_ptr< IMDIterator > createIterator (Mantid::Geometry::MDImplicitFunction *function=nullptr) const
Creates a single iterator and returns it.
virtual MDNormalization displayNormalization () const
virtual MDNormalization displayNormalizationHisto () const
const std::string & getConvention () const
signal_t getSignalAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates.
signal_t getSignalWithMaskAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates or 0 if masked.
IMDWorkspace ()
Default constructor.
virtual bool isMDHistoWorkspace () const
virtual ITableWorkspace_sptr makeBoxTable (size_t, size_t)
this is the method to build table workspace from any workspace.
IMDWorkspace & operator= (const IMDWorkspace &other)=delete
void setConvention (std::string convention)
Sets the convention of the workspace.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::MDGeometry
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (Nexus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instument group if found there.
void loadSampleAndLogInfoNexus (Nexus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (Nexus::File *file, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (Nexus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (Nexus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Protected Member Functions
EventWorkspace (const EventWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::API::IEventWorkspace
IEventWorkspace (const IEventWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace (const MatrixWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
MatrixWorkspace ()
Default constructor.
void updateCachedDetectorGrouping (const size_t index) const override
Update detector grouping for spectrum with given index.
std::string getDimensionIdFromAxis (const int &axisIndex) const
Getter for the dimension id based on the axis.
Protected Member Functions inherited from Mantid::API::IMDWorkspace
IMDWorkspace (const IMDWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void makeSinglePointWithNaN (std::vector< coord_t > &x, std::vector< signal_t > &y, std::vector< signal_t > &e) const
Make a single point with NaN as the signal and error This can be returned when there would otherwise be nothing to plot.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::MDGeometry
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
Private Member Functions
EventWorkspace * doClone () const override
Virtual clone method. Not implemented to force implementation in children.
EventWorkspace * doCloneEmpty () const override
Virtual cloneEmpty method.
EventList & getSpectrumWithoutInvalidation (const size_t index) override
Return const reference to EventList at the given workspace index.
Private Attributes
std::vector< std::unique_ptr< EventList > > data
A vector that holds the event list for each spectrum; the key is the workspace index, which is not necessarily the pixelid.
std::unique_ptr< EventWorkspaceMRU > mru
Container for the MRU lists of the event lists contained.
Additional Inherited Members
Public Types inherited from Mantid::API::MatrixWorkspace
using MaskList = std::map< size_t, double >
Masked bins for each spectrum are stored as a set of pairs containing <bin index, weight>
Static Public Attributes inherited from Mantid::API::MatrixWorkspace
static const std::string xDimensionId = "xDimension"
Dimension id for x-dimension.
static const std::string yDimensionId = "yDimension"
Dimensin id for y-dimension.
Protected Attributes inherited from Mantid::API::MatrixWorkspace
std::vector< std::unique_ptr< Axis > > m_axes
A vector of pointers to the axes for this workspace.
Protected Attributes inherited from Mantid::API::MDGeometry
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Detailed Description
This class is intended to fulfill the design specified in <https://github.com/mantidproject/documents/tree/master/Design/Event WorkspaceDetailed Design Document.doc>
Definition at line 31 of file EventWorkspace.h.
Constructor & Destructor Documentation
EventWorkspace() [1/2]
Mantid::DataObjects::EventWorkspace::EventWorkspace ()
Definition at line 47 of file EventWorkspace.cpp.
~EventWorkspace()
Mantid::DataObjects::EventWorkspace::~EventWorkspace () override
Definition at line 60 of file EventWorkspace.cpp.
References data.
EventWorkspace() [2/2]
Mantid::DataObjects::EventWorkspace::EventWorkspace (const EventWorkspace & other) protected
Protected copy constructor. May be used by childs for cloning.
Definition at line 49 of file EventWorkspace.cpp.
References data, and mru.
Member Function Documentation
blocksize()
size_t Mantid::DataObjects::EventWorkspace::blocksize () const override virtual
Get the blocksize, aka the number of bins in the histogram.
Returns
the number of bins in the Y data
Implements Mantid::API::MatrixWorkspace.
Definition at line 155 of file EventWorkspace.cpp.
References data.
clearMRU()
void Mantid::DataObjects::EventWorkspace::clearMRU () const override virtual
Clears the MRU lists.
Implements Mantid::API::IEventWorkspace.
Definition at line 481 of file EventWorkspace.cpp.
References mru.
Referenced by setAllX().
clone()
std::unique_ptr< EventWorkspace > Mantid::DataObjects::EventWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 44 of file EventWorkspace.h.
cloneEmpty()
std::unique_ptr< EventWorkspace > Mantid::DataObjects::EventWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 47 of file EventWorkspace.h.
dataDx() [1/2]
const MantidVec & Mantid::DataObjects::EventWorkspace::dataDx (const std::size_t index) const override virtual
Deprecated, use dx() instead.
Returns
the const data X error vector at a given workspace index
Parameters
index :: workspace index
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 537 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::DataObjects::EventList::readDx().
dataDx() [2/2]
MantidVec & Mantid::DataObjects::EventWorkspace::dataDx (const std::size_t index) override virtual
Deprecated, use mutableDx() instead.
Return the data X error vector at a given workspace index
Parameters
index :: the workspace index to return
Returns
A reference to the vector of binned error values
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 509 of file EventWorkspace.cpp.
References Mantid::DataObjects::EventList::dataDx(), getSpectrum(), and index.
dataE() [1/2]
const MantidVec & Mantid::DataObjects::EventWorkspace::dataE (const std::size_t index) const override virtual
Deprecated, use e() instead.
Returns
the const data E (error) vector at a given workspace index
Parameters
index :: workspace index
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 547 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::API::ISpectrum::readE().
dataE() [2/2]
MantidVec & Mantid::DataObjects::EventWorkspace::dataE (const std::size_t) override virtual
Deprecated, use mutableE() instead.
Return the data E vector at a given workspace index Note: these non-const access methods will throw NotImplementedError
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 523 of file EventWorkspace.cpp.
dataX() [1/2]
const MantidVec & Mantid::DataObjects::EventWorkspace::dataX (const std::size_t index) const override virtual
Deprecated, use x() instead.
Returns
the const data X vector at a given workspace index
Parameters
index :: workspace index
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 532 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::DataObjects::EventList::readX().
dataX() [2/2]
MantidVec & Mantid::DataObjects::EventWorkspace::dataX (const std::size_t index) override virtual
Deprecated, use mutableX() instead.
Return the data X vector at a given workspace index
Parameters
index :: the workspace index to return
Returns
A reference to the vector of binned X values
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 503 of file EventWorkspace.cpp.
References Mantid::DataObjects::EventList::dataX(), getSpectrum(), and index.
dataY() [1/2]
const MantidVec & Mantid::DataObjects::EventWorkspace::dataY (const std::size_t index) const override virtual
Deprecated, use y() instead.
Returns
the const data Y vector at a given workspace index
Parameters
index :: workspace index
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 542 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::API::ISpectrum::readY().
dataY() [2/2]
MantidVec & Mantid::DataObjects::EventWorkspace::dataY (const std::size_t) override virtual
Deprecated, use mutableY() instead.
Return the data Y vector at a given workspace index Note: these non-const access methods will throw NotImplementedError
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 514 of file EventWorkspace.cpp.
doClone()
EventWorkspace * Mantid::DataObjects::EventWorkspace::doClone () const inline override private virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::IEventWorkspace.
Definition at line 155 of file EventWorkspace.h.
doCloneEmpty()
EventWorkspace * Mantid::DataObjects::EventWorkspace::doCloneEmpty () const inline override private virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::IEventWorkspace.
Definition at line 156 of file EventWorkspace.h.
generateHistogram()
void Mantid::DataObjects::EventWorkspace::generateHistogram (const std::size_t index, const MantidVec & X, MantidVec & Y, MantidVec & E, bool skipError = false) const override virtual
Generate a new histogram from specified event list at the given index.
Using the event data in the event list, generate a histogram of it w.r.t TOF.
Parameters
index :: workspace index to generate
X :: input X vector of the bin boundaries.
Y :: output vector to be filled with the Y data.
E :: output vector to be filled with the Error data (optionally)
skipError :: if true, the error vector is NOT calculated. This may save some processing time.
Implements Mantid::API::IEventWorkspace.
Definition at line 566 of file EventWorkspace.cpp.
References data, index, and Mantid::Geometry::Y.
generateHistogramPulseTime()
void Mantid::DataObjects::EventWorkspace::generateHistogramPulseTime (const std::size_t index, const MantidVec & X, MantidVec & Y, MantidVec & E, bool skipError = false) const
Generate a new histogram from specified event list at the given index.
Using the event data in the event list, generate a histogram of it w.r.t PULSE TIME.
Parameters
index :: workspace index to generate
X :: input X vector of the bin boundaries.
Y :: output vector to be filled with the Y data.
E :: output vector to be filled with the Error data (optionally)
skipError :: if true, the error vector is NOT calculated. This may save some processing time.
Definition at line 583 of file EventWorkspace.cpp.
References data, index, and Mantid::Geometry::Y.
getEventType()
Mantid::API::EventType Mantid::DataObjects::EventWorkspace::getEventType () const override virtual
Get the EventType of the most-specialized EventList in the workspace.
Returns
the EventType of the most-specialized EventList in the workspace
Implements Mantid::API::IEventWorkspace.
Definition at line 446 of file EventWorkspace.cpp.
References data, Mantid::API::TOF, and Mantid::API::WEIGHTED_NOTIME.
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), and Mantid::MDAlgorithms::IntegrateFlux::integrateSpectra().
getEventXMax()
double Mantid::DataObjects::EventWorkspace::getEventXMax () const
Get them maximum x-value for the events themselves, ignoring the histogram representation.
Returns
The maximum x-value for the all events.
This does copy some of the code from getEventXMinXMax, but that is because getting both min and max then throwing away the min is significantly slower on an unsorted event list.
Definition at line 388 of file EventWorkspace.cpp.
References data, getNumberEvents(), getSpectrum(), and Mantid::DataObjects::EventList::getTofMax().
Referenced by getTofMax().
getEventXMin()
double Mantid::DataObjects::EventWorkspace::getEventXMin () const
Get them minimum x-value for the events themselves, ignoring the histogram representation.
Returns
The minimum x-value for the all events.
This does copy some of the code from getEventXMinXMax, but that is because getting both min and max then throwing away the max is significantly slower on an unsorted event list.
Definition at line 363 of file EventWorkspace.cpp.
References data, getNumberEvents(), getSpectrum(), and Mantid::DataObjects::EventList::getTofMin().
Referenced by getTofMin().
getEventXMinMax()
void Mantid::DataObjects::EventWorkspace::getEventXMinMax (double & xmin, double & xmax) const
Get them minimum and maximum x-values for the events themselves, ignoring the histogram representation.
Since this does not modify the sort order, the method will run significantly faster on a TOF_SORT event list.
Definition at line 409 of file EventWorkspace.cpp.
References data, getNumberEvents(), getSpectrum(), Mantid::DataObjects::EventList::getTofMax(), and Mantid::DataObjects::EventList::getTofMin().
Referenced by resetAllXToSingleBin().
getIntegratedSpectra()
void Mantid::DataObjects::EventWorkspace::getIntegratedSpectra (std::vector< double > & out, const double minX, const double maxX, const bool entireRange) const override virtual
Integrate all the spectra in the matrix workspace within the range given.
Default implementation, can be overridden by base classes if they know something smarter!
Parameters
out :: returns the vector where there is one entry per spectrum in the workspace. Same order as the workspace indices.
minX :: minimum X bin to use in integrating.
maxX :: maximum X bin to use in integrating.
entireRange :: set to true to use the entire range. minX and maxX are then ignored!
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 703 of file EventWorkspace.cpp.
References data, getNumberHistograms(), Mantid::DataObjects::EventList::integrate(), and PARALLEL_FOR_NO_WSP_CHECK.
getMaxNumberBins()
std::size_t Mantid::DataObjects::EventWorkspace::getMaxNumberBins () const override virtual
Returns the maximum number of bins in a workspace (works on ragged data).
Returns
the maximum number of bins in a workspace.
Implements Mantid::API::MatrixWorkspace.
Definition at line 184 of file EventWorkspace.cpp.
References data.
getMemorySize()
size_t Mantid::DataObjects::EventWorkspace::getMemorySize () const override virtual
Returns the amount of memory used in bytes.
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 484 of file EventWorkspace.cpp.
References data, Mantid::API::Run::getMemorySize(), Mantid::API::MatrixWorkspace::getMemorySizeForXAxes(), and Mantid::API::ExperimentInfo::run().
getNumberBins()
std::size_t Mantid::DataObjects::EventWorkspace::getNumberBins (const std::size_t & index) const override virtual
Returns the number of bins for a given histogram index.
Parameters
index :: The histogram index to check for the number of bins.
Returns
the number of bins for a given histogram index.
Implements Mantid::API::MatrixWorkspace.
Definition at line 173 of file EventWorkspace.cpp.
References data, index, and std::to_string().
getNumberEvents()
size_t Mantid::DataObjects::EventWorkspace::getNumberEvents () const override virtual
The total number of events across all of the spectra.
Returns
The total number of events
Implements Mantid::API::IEventWorkspace.
Definition at line 437 of file EventWorkspace.cpp.
References data.
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), getEventXMax(), getEventXMin(), and getEventXMinMax().
getNumberHistograms()
size_t Mantid::DataObjects::EventWorkspace::getNumberHistograms () const override virtual
Get the number of histograms, usually the same as the number of pixels or detectors.
Returns
the number of histograms / event lists
Implements Mantid::API::MatrixWorkspace.
Definition at line 202 of file EventWorkspace.cpp.
References data.
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::Algorithms::WorkspaceJoiners::execEvent(), getIntegratedSpectra(), Mantid::MDAlgorithms::IntegrateFlux::integrateSpectraEvents(), sortAll(), and Mantid::Algorithms::GenerateGoniometerIndependentBackground::validateInputs().
getPulseTimeMax()
DateAndTime Mantid::DataObjects::EventWorkspace::getPulseTimeMax () const override virtual
Get the maximum pulse time for events accross the entire workspace.
Returns
maximum pulse time as a DateAndTime.
Implements Mantid::API::IEventWorkspace.
Definition at line 257 of file EventWorkspace.cpp.
References data, Mantid::DataObjects::EventList::getPulseTimeMax(), and getSpectrum().
getPulseTimeMin()
DateAndTime Mantid::DataObjects::EventWorkspace::getPulseTimeMin () const override virtual
Get the minimum pulse time for events accross the entire workspace.
Returns
minimum pulse time as a DateAndTime.
Implements Mantid::API::IEventWorkspace.
Definition at line 239 of file EventWorkspace.cpp.
References data, Mantid::DataObjects::EventList::getPulseTimeMin(), and getSpectrum().
getPulseTimeMinMax()
void Mantid::DataObjects::EventWorkspace::getPulseTimeMinMax (Mantid::Types::Core::DateAndTime & Tmin, Mantid::Types::Core::DateAndTime & Tmax) const
Get the maximum and mimumum pulse time for events accross the entire workspace.
Parameters
Tmin minimal pulse time as a DateAndTime.
Tmax maximal pulse time as a DateAndTime.
Definition at line 275 of file EventWorkspace.cpp.
References data, Mantid::DataObjects::EventList::getPulseTimeMinMax(), and getSpectrum().
getSortType()
EventSortType Mantid::DataObjects::EventWorkspace::getSortType () const
Definition at line 661 of file EventWorkspace.cpp.
References data, getSortType(), and Mantid::DataObjects::UNSORTED.
Referenced by getSortType(), and sortAll().
getSpectrum() [1/2]
const EventList & Mantid::DataObjects::EventWorkspace::getSpectrum (const size_t index) const override virtual
Return const reference to EventList at the given workspace index.
Implements Mantid::API::IEventWorkspace.
Definition at line 212 of file EventWorkspace.cpp.
References data, and index.
getSpectrum() [2/2]
EventList & Mantid::DataObjects::EventWorkspace::getSpectrum (const size_t index) inline override virtual
Return the underlying ISpectrum ptr at the given workspace index.
Implements Mantid::API::IEventWorkspace.
Definition at line 75 of file EventWorkspace.h.
References index.
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), dataDx(), dataDx(), dataE(), dataX(), dataX(), dataY(), Mantid::Algorithms::WorkspaceJoiners::execEvent(), getEventXMax(), getEventXMin(), getEventXMinMax(), Mantid::MDAlgorithms::IntegrateFlux::getMaxNumberOfPoints(), getPulseTimeMax(), getPulseTimeMin(), getPulseTimeMinMax(), getSpectrumWithoutInvalidation(), getTimeAtSampleMax(), getTimeAtSampleMin(), Mantid::MDAlgorithms::IntegrateFlux::integrateSpectraEvents(), Mantid::DataObjects::EventSortingTask::operator()(), and refX().
getSpectrumUnsafe()
EventList * Mantid::DataObjects::EventWorkspace::getSpectrumUnsafe (const size_t index)
Returns a pointer to the EventList for a given spectrum in a timely manner.
Very minimal checking and preprocessing is performed by this function and it should only be used in tight loops where getSpectrum is too costly.
See the implementation of the non-const getSpectrum to see what is missing.
Parameters
index Workspace index
Returns
Pointer to EventList
Definition at line 229 of file EventWorkspace.cpp.
References data, and index.
getSpectrumWithoutInvalidation()
EventList & Mantid::DataObjects::EventWorkspace::getSpectrumWithoutInvalidation (const size_t index) override private virtual
Return const reference to EventList at the given workspace index.
Implements Mantid::API::IEventWorkspace.
Definition at line 205 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::API::ISpectrum::setMatrixWorkspace().
getTimeAtSampleMax()
DateAndTime Mantid::DataObjects::EventWorkspace::getTimeAtSampleMax (double tofOffset = 0) const override virtual
Get the maximum time at sample for events across the entire workspace.
Parameters
tofOffset :: Time of flight offset. defaults to zero.
Returns
maximum time at sample as a DateAndTime.
Implements Mantid::API::IEventWorkspace.
Definition at line 333 of file EventWorkspace.cpp.
References data, getSpectrum(), Mantid::DataObjects::EventList::getTimeAtSampleMax(), and Mantid::API::ExperimentInfo::spectrumInfo().
getTimeAtSampleMin()
DateAndTime Mantid::DataObjects::EventWorkspace::getTimeAtSampleMin (double tofOffset = 0) const override virtual
Get the minimum time at sample for events across the entire workspace.
Parameters
tofOffset :: Time of flight offset. defaults to zero.
Returns
minimum time at sample as a DateAndTime.
Implements Mantid::API::IEventWorkspace.
Definition at line 307 of file EventWorkspace.cpp.
References data, getSpectrum(), Mantid::DataObjects::EventList::getTimeAtSampleMin(), and Mantid::API::ExperimentInfo::spectrumInfo().
getTofMax()
double Mantid::DataObjects::EventWorkspace::getTofMax () const override virtual
Implements Mantid::API::IEventWorkspace.
Definition at line 233 of file EventWorkspace.cpp.
References getEventXMax().
getTofMin()
double Mantid::DataObjects::EventWorkspace::getTofMin () const override virtual
Implements Mantid::API::IEventWorkspace.
Definition at line 231 of file EventWorkspace.cpp.
References getEventXMin().
id()
const std::string Mantid::DataObjects::EventWorkspace::id () const inline override virtual
Return the workspace typeID.
Reimplemented from Mantid::API::IEventWorkspace.
Definition at line 35 of file EventWorkspace.h.
init() [1/2]
void Mantid::DataObjects::EventWorkspace::init (const HistogramData::Histogram & histogram) override virtual
Implements Mantid::API::MatrixWorkspace.
Definition at line 111 of file EventWorkspace.cpp.
References data, Mantid::API::MatrixWorkspace::histogram(), Mantid::API::MatrixWorkspace::m_axes, mru, Mantid::API::ExperimentInfo::numberOfDetectorGroups(), and Mantid::API::ISpectrum::setHistogram().
init() [2/2]
void Mantid::DataObjects::EventWorkspace::init (const std::size_t & NVectors, const std::size_t & XLength, const std::size_t & YLength) override virtual
Initialize the pixels.
Parameters
NVectors :: The number of vectors/histograms/detectors in the workspace. Does not need to be set, but needs to be > 0
XLength :: The number of X data points/bin boundaries in each vector (ignored)
YLength :: The number of data/error points in each vector (ignored)
Implements Mantid::API::MatrixWorkspace.
Definition at line 80 of file EventWorkspace.cpp.
References data, Mantid::API::MatrixWorkspace::m_axes, mru, and Mantid::API::ISpectrum::setHistogram().
isHistogramData()
bool Mantid::DataObjects::EventWorkspace::isHistogramData () const override virtual
Returns true always - an EventWorkspace always represents histogramm-able data.
Returns
If the data is a histogram - always true for an eventWorkspace
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 472 of file EventWorkspace.cpp.
isRaggedWorkspace()
bool Mantid::DataObjects::EventWorkspace::isRaggedWorkspace () const override virtual
Returns true if the workspace is ragged (has differently sized spectra).
Returns
true if the workspace is ragged.
Implements Mantid::API::MatrixWorkspace.
Definition at line 134 of file EventWorkspace.cpp.
References data.
MRUSize()
size_t Mantid::DataObjects::EventWorkspace::MRUSize () const
Return how many entries in the Y MRU list are used.
Only used in tests. It only returns the 0-th MRU list size.
Returns
:: number of entries in the MRU list.
Definition at line 478 of file EventWorkspace.cpp.
References mru.
operator=()
EventWorkspace & Mantid::DataObjects::EventWorkspace::operator= (const EventWorkspace & other) delete
refX()
Kernel::cow_ptr< HistogramData::HistogramX > Mantid::DataObjects::EventWorkspace::refX (const std::size_t index) const override virtual
Deprecated, use sharedX() instead.
Returns
a pointer to the X data vector at a given workspace index
Parameters
index :: workspace index
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 552 of file EventWorkspace.cpp.
References getSpectrum(), index, and Mantid::DataObjects::EventList::ptrX().
resetAllXToSingleBin()
void Mantid::DataObjects::EventWorkspace::resetAllXToSingleBin () override virtual
Set all Histogram X vectors to a single bin with boundaries that fit the TOF of all events across all spectra.
Implements Mantid::API::IEventWorkspace.
Definition at line 610 of file EventWorkspace.cpp.
References getEventXMinMax(), and setAllX().
setAllX()
void Mantid::DataObjects::EventWorkspace::setAllX (const HistogramData::BinEdges & x) override virtual
Set all histogram X vectors.
Parameters
x :: The X vector of histogram bins to use.
Implements Mantid::API::IEventWorkspace.
Definition at line 594 of file EventWorkspace.cpp.
References clearMRU(), data, Mantid::API::MatrixWorkspace::invalidateCommonBinsFlag(), and Mantid::Geometry::x.
Referenced by resetAllXToSingleBin().
size()
size_t Mantid::DataObjects::EventWorkspace::size () const override virtual
The total size of the workspace.
Returns
the number of single indexable items in the workspace
Implements Mantid::API::MatrixWorkspace.
Definition at line 147 of file EventWorkspace.cpp.
References data, and value.
sortAll()
void Mantid::DataObjects::EventWorkspace::sortAll (EventSortType sortType, Mantid::API::Progress * prog) const
Definition at line 676 of file EventWorkspace.cpp.
References data, getNumberHistograms(), getSortType(), and Mantid::Kernel::ProgressBase::reportIncrement().
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), and Mantid::MDAlgorithms::IntegrateFlux::integrateSpectraEvents().
switchEventType()
void Mantid::DataObjects::EventWorkspace::switchEventType (const Mantid::API::EventType type)
Switch all event lists to the given event type.
Parameters
type :: EventType to switch to
Definition at line 464 of file EventWorkspace.cpp.
References data.
threadSafe()
bool Mantid::DataObjects::EventWorkspace::threadSafe () const override virtual
Returns true if the EventWorkspace is safe for multithreaded operations.
WARNING: This is only true for OpenMP threading. EventWorkspace is NOT thread safe with Poco threads or other threading mechanisms.
Reimplemented from Mantid::API::Workspace.
Definition at line 66 of file EventWorkspace.cpp.
Referenced by Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces().
Member Data Documentation
data
std::vector<std::unique_ptr<EventList> > Mantid::DataObjects::EventWorkspace::data private
A vector that holds the event list for each spectrum; the key is the workspace index, which is not necessarily the pixelid.
Definition at line 163 of file EventWorkspace.h.
Referenced by blocksize(), EventWorkspace(), generateHistogram(), generateHistogramPulseTime(), getEventType(), getEventXMax(), getEventXMin(), getEventXMinMax(), getIntegratedSpectra(), getMaxNumberBins(), getMemorySize(), getNumberBins(), getNumberEvents(), getNumberHistograms(), getPulseTimeMax(), getPulseTimeMin(), getPulseTimeMinMax(), getSortType(), getSpectrum(), getSpectrumUnsafe(), getTimeAtSampleMax(), getTimeAtSampleMin(), init(), init(), isRaggedWorkspace(), setAllX(), size(), sortAll(), switchEventType(), and ~EventWorkspace().
mru
std::unique_ptr<EventWorkspaceMRU> Mantid::DataObjects::EventWorkspace::mru mutable private
Container for the MRU lists of the event lists contained.
Definition at line 166 of file EventWorkspace.h.
Referenced by clearMRU(), EventWorkspace(), init(), init(), and MRUSize().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/EventWorkspace.h
Framework/DataObjects/src/EventWorkspace.cpp