Mantid: Mantid::DataObjects::LeanElasticPeaksWorkspace Class Reference
Mantid::DataObjects::LeanElasticPeaksWorkspace Class Reference
The class LeanElasticPeaksWorkspace stores information about a set of SCD lean peaks.
#include <LeanElasticPeaksWorkspace.h>
Public Types
using ColumnAndDirection = std::pair< std::string, bool >
Public Member Functions
void addPeak (const Geometry::IPeak &peak) override
Add a peak to the list.
void addPeak (const Kernel::V3D &position, const Kernel::SpecialCoordinateSystem &frame) override
Add a peak to the list.
void addPeak (LeanElasticPeak &&peak)
Move a peak object into this peaks workspace.
void appendFile (std::string filename, Geometry::Instrument_sptr inst)
std::unique_ptr< LeanElasticPeaksWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< LeanElasticPeaksWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
size_t columnCount () const override
Number of columns in the workspace.
API::ITableWorkspace_sptr createDetectorTable () const override
Creates a new TableWorkspace giving the IDs of the detectors that contribute to the peaks within the workspace.
std::unique_ptr< Geometry::IPeak > createPeak () const override
Create a Peak using default values.
std::unique_ptr< Geometry::IPeak > createPeak (const Kernel::V3D &Position, const Kernel::SpecialCoordinateSystem &frame) const override
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
std::unique_ptr< Geometry::IPeak > createPeak (const Kernel::V3D &QLabFrame, std::optional< double > detectorDistance=std::nullopt) const override
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
std::unique_ptr< Geometry::IPeak > createPeakHKL (const Kernel::V3D &HKL) const override
Create a Peak from a HKL value provided by the client.
std::unique_ptr< Geometry::IPeak > createPeakQSample (const Kernel::V3D &position) const override
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
bool customSort () const override
std::shared_ptr< const Mantid::API::Column > getColumn (const std::string &name) const override
Gets the shared pointer to a column by name.
std::shared_ptr< Mantid::API::Column > getColumn (const std::string &name) override
Gets the shared pointer to a column by name.
API::Column_const_sptr getColumn (size_t index) const override
Gets the shared pointer to a column by index - return none-modifyable column.
std::shared_ptr< Mantid::API::Column > getColumn (size_t index) override
Gets the shared pointer to a column by index.
virtual size_t getColumnIndex (const std::string &name) const
std::vector< std::string > getColumnNames () const override
Returns a vector of all column names.
std::string getConvention () const override
API::LogManager_const_sptr getLogs () const override
Get constant access to shared pointer containing workspace porperties; Copies logs into new LogManager variable Meaningfull only for some multithereaded methods when a thread wants to have its own copy of logs.
size_t getMemorySize () const override
Return the memory used in bytes.
int getNumberPeaks () const override
const LeanElasticPeak & getPeak (size_t const peakNum) const override
Return a const reference to the Peak.
LeanElasticPeak & getPeak (size_t const peakNum) override
Return a reference to the Peak.
std::vector< LeanElasticPeak > & getPeaks ()
Return a reference to the Peaks vector.
const std::vector< LeanElasticPeak > & getPeaks () const
Return a const reference to the Peaks vector.
Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const override
Get the special coordinate system.
bool hasIntegratedPeaks () const override
Getter for the integration status.
const std::string id () const override
Return the workspace typeID.
LeanElasticPeaksWorkspace ()
Register the workspace as a type.
API::LogManager_sptr logs () override
Get access to shared pointer containing workspace porperties.
LeanElasticPeaksWorkspace & operator= (const LeanElasticPeaksWorkspace &other)=delete
std::vector< std::pair< std::string, std::string > > peakInfo (const Kernel::V3D &qFrame, bool labCoords) const override
Returns selected information for a "peak" at QLabFrame.
int peakInfoNumber (const Kernel::V3D &qFrame, bool labCoords) const override
Returns selected information for a "peak" at QLabFrame.
void removePeak (int peakNum) override
Removes the indicated peak.
void removePeaks (std::vector< int > badPeaks) override
Removes multiple peaks.
size_t rowCount () const override
Number of rows in the workspace.
void saveNexus (Nexus::File *file) const override
void setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem) override
Set the special coordinate system.
void sort (std::vector< ColumnAndDirection > &criteria) override
Sort the peaks by one or more criteria.
bool threadSafe () const override
This is always threadsafe.
Public Member Functions inherited from Mantid::API::IPeaksWorkspace
IPeaksWorkspace_uptr clone () const
Returns a clone of the workspace.
Mantid::Geometry::IPeak * getPeakPtr (size_t const peakNum)
Return a pointer to the Peak.
IPeaksWorkspace ()
Ctor.
IPeaksWorkspace & operator= (const IPeaksWorkspace &other)=delete
Public Member Functions inherited from Mantid::API::ITableWorkspace
TableRowHelper appendRow ()
Appends a row.
Boolean & Bool (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is bool.
template<class T >
T & cell (size_t row, size_t col)
Get the reference to the element in row row and column col.
ITableWorkspace_uptr clone () const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneColumns (const std::vector< std::string > &colNames) const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
double & Double (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is double.
TableRowHelper getFirstRow ()
Creates a TableRow object for the first row (row == 0).
template<class T >
T & getRef (const std::string &name, size_t index)
Get a reference to a data element.
TableRowHelper getRow (size_t row)
Creates a TableRow object for row row.
TableColumnHelper getVector (const std::string &name)
Access the column with name name trough a ColumnVector object.
TableConstColumnHelper getVector (const std::string &name) const
Access the column with name name trough a ColumnVector object.
int & Int (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is int.
ITableWorkspace ()
Constructor.
void modified ()
If the workspace is the AnalysisDataService sends AfterReplaceNotification.
ITableWorkspace & operator= (const ITableWorkspace &)=delete
virtual void sort (std::vector< std::pair< std::string, bool > > &criteria)
Overridable method to custom-sort the workspace.
std::string & String (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is std::string.
const std::string toString () const override
Serializes the object to a string.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
virtual const std::string getTitle () const
Get the workspace title.
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
virtual void setTitle (const std::string &)
Set the title of the workspace.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (Nexus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instument group if found there.
void loadSampleAndLogInfoNexus (Nexus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (Nexus::File *file, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (Nexus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (Nexus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Protected Member Functions
LeanElasticPeaksWorkspace (const LeanElasticPeaksWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::API::IPeaksWorkspace
IPeaksWorkspace (const IPeaksWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::ITableWorkspace
void insertInColumn (Column *c, size_t index)
Insert a new element into a column.
ITableWorkspace (const ITableWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void removeFromColumn (Column *c, size_t index)
Remove an element from a column.
void resizeColumn (Column *c, size_t size)
Resize a column.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
virtual void updateCachedDetectorGrouping (const size_t index) const
Update detector grouping for spectrum with given index.
Private Member Functions
API::Column_sptr addColumn (const std::string &, const std::string &) override
Creates a new column.
bool addColumns (const std::string &, const std::string &, size_t) override
Creates n new columns of the same type.
void addPeakColumn (const std::string &name)
Adds a new PeakColumn of the given type.
LeanElasticPeaksWorkspace * doClone () const override
Virtual clone method. Not implemented to force implementation in children.
ITableWorkspace * doCloneColumns (const std::vector< std::string > &colNames) const override
LeanElasticPeaksWorkspace * doCloneEmpty () const override
Virtual cloneEmpty method.
void find (API::Boolean, size_t &, size_t) override
find method to get the index of API::Boolean value cell in a table workspace
void find (const Mantid::Kernel::V3D &, size_t &, size_t) override
find method to get the index of Mantid::Kernel::V3D cell value in a table workspace
void find (const std::string &, size_t &, size_t) override
find method to get the index of cellstd::string value in a table workspace
void find (double, size_t &, size_t) override
find method to get the index of double cell value in a table workspace
void find (float, size_t &, size_t) override
find method to get the index of float cell value in a table workspace
void find (size_t, size_t &, size_t) override
find method to get the index of integer cell value in a table workspace
void initColumns ()
Initialize the table structure.
size_t insertRow (size_t) override
Inserts a row before row pointed to by index and fills it with default vales.
void removeColumn (const std::string &) override
Removes a column.
void removeRow (size_t) override
Delets a row if it exists.
void setRowCount (size_t) override
Resizes the workspace.
Private Attributes
std::vector< std::string > m_columnNames
Column names.
std::vector< std::shared_ptr< Mantid::DataObjects::PeakColumn< LeanElasticPeak > > > m_columns
Column shared pointers.
Kernel::SpecialCoordinateSystem m_coordSystem
Coordinates.
std::vector< LeanElasticPeak > m_peaks
Vector of Peak contained within.
Additional Inherited Members
Public Attributes inherited from Mantid::API::IPeaksWorkspace
std::string m_convention
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Detailed Description
The class LeanElasticPeaksWorkspace stores information about a set of SCD lean peaks.
Author
Ruth Mikkelson, SNS ORNL
Date
3/10/2010
Definition at line 37 of file LeanElasticPeaksWorkspace.h.
Member Typedef Documentation
ColumnAndDirection
using Mantid::DataObjects::LeanElasticPeaksWorkspace::ColumnAndDirection = std::pair<std::string, bool>
Definition at line 39 of file LeanElasticPeaksWorkspace.h.
Constructor & Destructor Documentation
LeanElasticPeaksWorkspace() [1/2]
Mantid::DataObjects::LeanElasticPeaksWorkspace::LeanElasticPeaksWorkspace ()
Register the workspace as a type.
Constructor. Create a table with all the required columns.
Definition at line 31 of file LeanElasticPeaksWorkspace.cpp.
LeanElasticPeaksWorkspace() [2/2]
Mantid::DataObjects::LeanElasticPeaksWorkspace::LeanElasticPeaksWorkspace (const LeanElasticPeaksWorkspace & other) protected
Protected copy constructor. May be used by childs for cloning.
Copy constructor.
Parameters
other :: other LeanElasticPeaksWorkspace to copy from
Definition at line 44 of file LeanElasticPeaksWorkspace.cpp.
References initColumns(), and Mantid::API::ExperimentInfo::setNumberOfDetectorGroups().
Member Function Documentation
addColumn()
API::Column_sptr Mantid::DataObjects::LeanElasticPeaksWorkspace::addColumn (const std::string & type, const std::string & name) inline override private virtual
Creates a new column.
Parameters
type :: The datatype of the column
name :: The name to assign to the column
Returns
True if the column was successfully added
Implements Mantid::API::ITableWorkspace.
Definition at line 179 of file LeanElasticPeaksWorkspace.h.
addColumns()
bool Mantid::DataObjects::LeanElasticPeaksWorkspace::addColumns (const std::string & type, const std::string & name, size_t n) inline override private virtual
Creates n new columns of the same type.
Parameters
type :: The datatype of the column
name :: The name to assign to the column
n :: The number of columns to create
Returns
True if the column was successfully added
Reimplemented from Mantid::API::ITableWorkspace.
Definition at line 184 of file LeanElasticPeaksWorkspace.h.
addPeak() [1/3]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::addPeak (const Geometry::IPeak & ipeak) override virtual
Add a peak to the list.
Parameters
ipeak :: Peak object to add (copy) into this.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 143 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
Referenced by addPeak().
addPeak() [2/3]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::addPeak (const Kernel::V3D & position, const Kernel::SpecialCoordinateSystem & frame) override virtual
Add a peak to the list.
Parameters
position :: position on the peak in the specified coordinate frame
frame :: the coordinate frame that the position is specified in
Implements Mantid::API::IPeaksWorkspace.
Definition at line 156 of file LeanElasticPeaksWorkspace.cpp.
References addPeak(), createPeak(), and position.
addPeak() [3/3]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::addPeak (LeanElasticPeak && peak)
Move a peak object into this peaks workspace.
Add a peak to the list.
Parameters
peak :: Peak object to add (move) into this.
Definition at line 165 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
addPeakColumn()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::addPeakColumn (const std::string & name) private
Adds a new PeakColumn of the given type.
Add a PeakColumn.
Parameters
name :: The name of the column
Definition at line 373 of file LeanElasticPeaksWorkspace.cpp.
References m_columnNames, m_columns, m_peaks, and name.
Referenced by initColumns().
appendFile()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::appendFile (std::string filename, Geometry::Instrument_sptr inst)
clone()
std::unique_ptr< LeanElasticPeaksWorkspace > Mantid::DataObjects::LeanElasticPeaksWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 61 of file LeanElasticPeaksWorkspace.h.
cloneEmpty()
std::unique_ptr< LeanElasticPeaksWorkspace > Mantid::DataObjects::LeanElasticPeaksWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 66 of file LeanElasticPeaksWorkspace.h.
columnCount()
size_t Mantid::DataObjects::LeanElasticPeaksWorkspace::columnCount () const inline override virtual
Number of columns in the workspace.
Implements Mantid::API::ITableWorkspace.
Definition at line 124 of file LeanElasticPeaksWorkspace.h.
createDetectorTable()
API::ITableWorkspace_sptr Mantid::DataObjects::LeanElasticPeaksWorkspace::createDetectorTable () const override virtual
Creates a new TableWorkspace giving the IDs of the detectors that contribute to the peaks within the workspace.
Creates a new TableWorkspace with detailing the contributing Detector IDs.
The table will have 2 columns: Index & DetectorID, where Index maps into the current index within the LeanElasticPeaksWorkspace of the peak
Implements Mantid::API::IPeaksWorkspace.
Definition at line 342 of file LeanElasticPeaksWorkspace.cpp.
createPeak() [1/3]
std::unique_ptr< IPeak > Mantid::DataObjects::LeanElasticPeaksWorkspace::createPeak () const override virtual
Create a Peak using default values.
Returns
a point to a new peak object
Implements Mantid::API::IPeaksWorkspace.
Definition at line 289 of file LeanElasticPeaksWorkspace.cpp.
Referenced by addPeak(), and createPeak().
createPeak() [2/3]
std::unique_ptr< Geometry::IPeak > Mantid::DataObjects::LeanElasticPeaksWorkspace::createPeak (const Kernel::V3D & position, const Kernel::SpecialCoordinateSystem & frame) const override virtual
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
Parameters
position :: position of the center of the peak, in reciprocal space
frame :: the coordinate system that the position is specified in detector. You do NOT need to explicitly provide this distance.
Returns
a pointer to a new Peak object.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 211 of file LeanElasticPeaksWorkspace.cpp.
References createPeak(), createPeakHKL(), createPeakQSample(), Mantid::Kernel::HKL, position, and Mantid::Kernel::QLab.
createPeak() [3/3]
std::unique_ptr< Geometry::IPeak > Mantid::DataObjects::LeanElasticPeaksWorkspace::createPeak (const Kernel::V3D & QLabFrame, std::optional< double > detectorDistance = std::nullopt) const override virtual
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
Parameters
QLabFrame :: Q of the center of the peak, in reciprocal space
detectorDistance :: optional distance between the sample and the detector. You do NOT need to explicitly provide this distance.
Returns
a pointer to a new Peak object.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 198 of file LeanElasticPeaksWorkspace.cpp.
createPeakHKL()
std::unique_ptr< IPeak > Mantid::DataObjects::LeanElasticPeaksWorkspace::createPeakHKL (const Kernel::V3D & HKL) const override virtual
Create a Peak from a HKL value provided by the client.
Parameters
HKL : reciprocal lattice vector coefficients
Returns
Fully formed peak.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 262 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::Run::getGoniometer(), Mantid::API::Sample::getOrientedLattice(), Mantid::API::ExperimentInfo::getRunNumber(), Mantid::API::ExperimentInfo::run(), and Mantid::API::ExperimentInfo::sample().
Referenced by createPeak().
createPeakQSample()
std::unique_ptr< IPeak > Mantid::DataObjects::LeanElasticPeaksWorkspace::createPeakQSample (const Kernel::V3D & position) const override virtual
Creates an instance of a Peak BUT DOES NOT ADD IT TO THE WORKSPACE.
Parameters
position :: QSample position of the center of the peak, in reciprocal space detector. You do NOT need to explicitly provide this distance.
Returns
a pointer to a new Peak object.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 228 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::ExperimentInfo::getRunNumber(), position, and Mantid::API::ExperimentInfo::run().
Referenced by createPeak().
customSort()
bool Mantid::DataObjects::LeanElasticPeaksWorkspace::customSort () const inline override virtual
Returns
true because this type of the workspace needs custom sorting calls
Reimplemented from Mantid::API::ITableWorkspace.
Definition at line 74 of file LeanElasticPeaksWorkspace.h.
doClone()
LeanElasticPeaksWorkspace * Mantid::DataObjects::LeanElasticPeaksWorkspace::doClone () const inline override private virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 166 of file LeanElasticPeaksWorkspace.h.
doCloneColumns()
ITableWorkspace * Mantid::DataObjects::LeanElasticPeaksWorkspace::doCloneColumns (const std::vector< std::string > & colNames) const override private virtual
Implements Mantid::API::ITableWorkspace.
Definition at line 679 of file LeanElasticPeaksWorkspace.cpp.
doCloneEmpty()
LeanElasticPeaksWorkspace * Mantid::DataObjects::LeanElasticPeaksWorkspace::doCloneEmpty () const inline override private virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::ITableWorkspace.
Definition at line 167 of file LeanElasticPeaksWorkspace.h.
find() [1/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (API::Boolean , size_t & , size_t) inline override private virtual
find method to get the index of API::Boolean value cell in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 224 of file LeanElasticPeaksWorkspace.h.
find() [2/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (const Mantid::Kernel::V3D & , size_t & , size_t) inline override private virtual
find method to get the index of Mantid::Kernel::V3D cell value in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 234 of file LeanElasticPeaksWorkspace.h.
find() [3/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (const std::string & , size_t & , size_t) inline override private virtual
find method to get the index of cellstd::string value in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 229 of file LeanElasticPeaksWorkspace.h.
find() [4/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (double , size_t & , size_t) inline override private virtual
find method to get the index of double cell value in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 215 of file LeanElasticPeaksWorkspace.h.
find() [5/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (float , size_t & , size_t) inline override private virtual
find method to get the index of float cell value in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 219 of file LeanElasticPeaksWorkspace.h.
find() [6/6]
void Mantid::DataObjects::LeanElasticPeaksWorkspace::find (size_t , size_t & , size_t) inline override private virtual
find method to get the index of integer cell value in a table workspace
Implements Mantid::API::ITableWorkspace.
Definition at line 211 of file LeanElasticPeaksWorkspace.h.
getColumn() [1/4]
std::shared_ptr< const Mantid::API::Column > Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumn (const std::string & name) const inline override virtual
Gets the shared pointer to a column by name.
Implements Mantid::API::ITableWorkspace.
Definition at line 135 of file LeanElasticPeaksWorkspace.h.
References name.
getColumn() [2/4]
std::shared_ptr< Mantid::API::Column > Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumn (const std::string & name) inline override virtual
Gets the shared pointer to a column by name.
Implements Mantid::API::ITableWorkspace.
Definition at line 130 of file LeanElasticPeaksWorkspace.h.
References name.
getColumn() [3/4]
std::shared_ptr< const Mantid::API::Column > Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumn (size_t index) const override virtual
Gets the shared pointer to a column by index - return none-modifyable column.
Gets the shared pointer to a column by index.
Implements Mantid::API::ITableWorkspace.
Definition at line 399 of file LeanElasticPeaksWorkspace.cpp.
References index, and m_columns.
getColumn() [4/4]
std::shared_ptr< Mantid::API::Column > Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumn (size_t index) override virtual
Gets the shared pointer to a column by index.
Implements Mantid::API::ITableWorkspace.
Definition at line 391 of file LeanElasticPeaksWorkspace.cpp.
References index, and m_columns.
getColumnIndex()
size_t Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumnIndex (const std::string & name) const virtual
Returns
the index of the column with the given name.
Definition at line 382 of file LeanElasticPeaksWorkspace.cpp.
References m_columns, and name.
getColumnNames()
std::vector< std::string > Mantid::DataObjects::LeanElasticPeaksWorkspace::getColumnNames () const inline override virtual
Returns a vector of all column names.
Implements Mantid::API::ITableWorkspace.
Definition at line 153 of file LeanElasticPeaksWorkspace.h.
getConvention()
std::string Mantid::DataObjects::LeanElasticPeaksWorkspace::getConvention () const override virtual
Returns
the convention
Implements Mantid::API::IPeaksWorkspace.
Definition at line 110 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::IPeaksWorkspace::m_convention.
Referenced by saveNexus().
getLogs()
API::LogManager_const_sptr Mantid::DataObjects::LeanElasticPeaksWorkspace::getLogs () const override virtual
Get constant access to shared pointer containing workspace porperties; Copies logs into new LogManager variable Meaningfull only for some multithereaded methods when a thread wants to have its own copy of logs.
Implements Mantid::API::ITableWorkspace.
Definition at line 675 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::ExperimentInfo::run().
getMemorySize()
size_t Mantid::DataObjects::LeanElasticPeaksWorkspace::getMemorySize () const override virtual
Return the memory used in bytes.
Implements Mantid::API::Workspace.
Definition at line 332 of file LeanElasticPeaksWorkspace.cpp.
References getNumberPeaks().
getNumberPeaks()
int Mantid::DataObjects::LeanElasticPeaksWorkspace::getNumberPeaks () const override virtual
Returns
the number of peaks
Implements Mantid::API::IPeaksWorkspace.
Definition at line 105 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
Referenced by getMemorySize().
getPeak() [1/2]
const LeanElasticPeak & Mantid::DataObjects::LeanElasticPeaksWorkspace::getPeak (size_t const peakNum) const override virtual
Return a const reference to the Peak.
Parameters
peakNum :: index of the peak to get.
Returns
a reference to a Peak object.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 184 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
getPeak() [2/2]
LeanElasticPeak & Mantid::DataObjects::LeanElasticPeaksWorkspace::getPeak (size_t const peakNum) override virtual
Return a reference to the Peak.
Parameters
peakNum :: index of the peak to get.
Returns
a reference to a Peak object.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 172 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
getPeaks() [1/2]
std::vector< LeanElasticPeak > & Mantid::DataObjects::LeanElasticPeaksWorkspace::getPeaks ()
Return a reference to the Peaks vector.
Definition at line 312 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
getPeaks() [2/2]
const std::vector< LeanElasticPeak > & Mantid::DataObjects::LeanElasticPeaksWorkspace::getPeaks () const
Return a const reference to the Peaks vector.
Definition at line 315 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
getSpecialCoordinateSystem()
Kernel::SpecialCoordinateSystem Mantid::DataObjects::LeanElasticPeaksWorkspace::getSpecialCoordinateSystem () const override virtual
Get the special coordinate system.
Returns
the special Q3D coordinate system.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 661 of file LeanElasticPeaksWorkspace.cpp.
References m_coordSystem.
hasIntegratedPeaks()
bool Mantid::DataObjects::LeanElasticPeaksWorkspace::hasIntegratedPeaks () const override virtual
Getter for the integration status.
Returns
TRUE if it has been integrated using a peak integration algorithm.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 320 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::ExperimentInfo::run(), and value.
id()
const std::string Mantid::DataObjects::LeanElasticPeaksWorkspace::id () const inline override virtual
Return the workspace typeID.
Reimplemented from Mantid::API::ITableWorkspace.
Definition at line 42 of file LeanElasticPeaksWorkspace.h.
initColumns()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::initColumns () private
Initialize the table structure.
Initialize all columns.
Definition at line 348 of file LeanElasticPeaksWorkspace.cpp.
References addPeakColumn().
Referenced by LeanElasticPeaksWorkspace().
insertRow()
size_t Mantid::DataObjects::LeanElasticPeaksWorkspace::insertRow (size_t index) inline override private virtual
Inserts a row before row pointed to by index and fills it with default vales.
Implements Mantid::API::ITableWorkspace.
Definition at line 200 of file LeanElasticPeaksWorkspace.h.
logs()
API::LogManager_sptr Mantid::DataObjects::LeanElasticPeaksWorkspace::logs () override virtual
Get access to shared pointer containing workspace porperties.
This function is there to provide common interface of iTableWorkspace Despite it is non-constant method, one should be very carefull using it to change the log values when cloning of a table workspace can occur as the changes may depend on the order of PeakWorkspace cloning & changes applyed through this pointer. See PeakWorkspaceTest (test_getSetLogAccess) – for example of this behaviour. Use mutableRun interface to change log values rather then this method.
Implements Mantid::API::ITableWorkspace.
Definition at line 668 of file LeanElasticPeaksWorkspace.cpp.
References Mantid::API::ExperimentInfo::mutableRun().
operator=()
LeanElasticPeaksWorkspace & Mantid::DataObjects::LeanElasticPeaksWorkspace::operator= (const LeanElasticPeaksWorkspace & other) delete
peakInfo()
std::vector< std::pair< std::string, std::string > > Mantid::DataObjects::LeanElasticPeaksWorkspace::peakInfo (const Kernel::V3D & qFrame, bool labCoords) const override virtual
Returns selected information for a "peak" at QLabFrame.
Parameters
qFrame An arbitrary position in Q-space. This does not have to be the position of a peak.
labCoords Set true if the position is in the lab coordinate system, false if it is in the sample coordinate system.
Returns
a vector whose elements contain different information about the "peak" at that position. each element is a pair of description of information and the string form for the corresponding value.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 251 of file LeanElasticPeaksWorkspace.cpp.
peakInfoNumber()
int Mantid::DataObjects::LeanElasticPeaksWorkspace::peakInfoNumber (const Kernel::V3D & qFrame, bool labCoords) const override virtual
Returns selected information for a "peak" at QLabFrame.
Parameters
qFrame An arbitrary position in Q-space. This does not have to be the position of a peak.
labCoords Set true if the position is in the lab coordinate system, false if it is in the sample coordinate system.
Returns
a vector whose elements contain different information about the "peak" at that position. each element is a pair of description of information and the string form for the corresponding value.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 306 of file LeanElasticPeaksWorkspace.cpp.
removeColumn()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::removeColumn (const std::string & name) inline override private virtual
Removes a column.
Implements Mantid::API::ITableWorkspace.
Definition at line 189 of file LeanElasticPeaksWorkspace.h.
removePeak()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::removePeak (int peakNum) override virtual
Removes the indicated peak.
Parameters
peakNum the peak to remove. peakNum starts at 0
Implements Mantid::API::IPeaksWorkspace.
Definition at line 116 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
removePeaks()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::removePeaks (std::vector< int > badPeaks) override virtual
Removes multiple peaks.
Parameters
badPeaks peaks to be removed
Implements Mantid::API::IPeaksWorkspace.
Definition at line 126 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
removeRow()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::removeRow (size_t index) inline override private virtual
Delets a row if it exists.
Implements Mantid::API::ITableWorkspace.
Definition at line 205 of file LeanElasticPeaksWorkspace.h.
rowCount()
size_t Mantid::DataObjects::LeanElasticPeaksWorkspace::rowCount () const inline override virtual
Number of rows in the workspace.
Implements Mantid::API::ITableWorkspace.
Definition at line 127 of file LeanElasticPeaksWorkspace.h.
saveNexus()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus (Nexus::File * file) const override virtual
Implements Mantid::API::IPeaksWorkspace.
Definition at line 405 of file LeanElasticPeaksWorkspace.cpp.
References NXnumtype::CHAR, Mantid::DataObjects::BasePeak::getAbsorptionWeightedPathLength(), Mantid::DataObjects::BasePeak::getBinCount(), getConvention(), Mantid::DataObjects::LeanElasticPeak::getDSpacing(), Mantid::DataObjects::BasePeak::getGoniometerMatrix(), Mantid::DataObjects::BasePeak::getH(), Mantid::DataObjects::BasePeak::getIntensity(), Mantid::DataObjects::BasePeak::getIntHKL(), Mantid::DataObjects::BasePeak::getIntMNP(), Mantid::DataObjects::BasePeak::getK(), Mantid::DataObjects::BasePeak::getL(), Mantid::DataObjects::BasePeak::getPeakNumber(), Mantid::DataObjects::BasePeak::getPeakShape(), Mantid::DataObjects::LeanElasticPeak::getQLabFrame(), Mantid::DataObjects::BasePeak::getRunNumber(), Mantid::DataObjects::LeanElasticPeak::getScattering(), Mantid::DataObjects::BasePeak::getSigmaIntensity(), Mantid::DataObjects::LeanElasticPeak::getWavelength(), m_coordSystem, m_peaks, name, Mantid::Geometry::PeakShape::toJSON(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
setCoordinateSystem()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem) override virtual
Set the special coordinate system.
Set the special Q3D coordinate system.
Parameters
coordinateSystem : Option to set.
Implements Mantid::API::IPeaksWorkspace.
Definition at line 654 of file LeanElasticPeaksWorkspace.cpp.
References m_coordSystem.
setRowCount()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::setRowCount (size_t count) inline override private virtual
Resizes the workspace.
Implements Mantid::API::ITableWorkspace.
Definition at line 195 of file LeanElasticPeaksWorkspace.h.
sort()
void Mantid::DataObjects::LeanElasticPeaksWorkspace::sort (std::vector< ColumnAndDirection > & criteria) override
Sort the peaks by one or more criteria.
Parameters
criteria : a vector with a list of pairs: column name, bool; where bool = true for ascending, false for descending sort. The peaks are sorted by the first criterion first, then the 2nd if equal, etc.
Definition at line 97 of file LeanElasticPeaksWorkspace.cpp.
References m_peaks.
threadSafe()
bool Mantid::DataObjects::LeanElasticPeaksWorkspace::threadSafe () const inline override virtual
This is always threadsafe.
Reimplemented from Mantid::API::Workspace.
Definition at line 155 of file LeanElasticPeaksWorkspace.h.
Member Data Documentation
m_columnNames
std::vector<std::string> Mantid::DataObjects::LeanElasticPeaksWorkspace::m_columnNames private
Column names.
Definition at line 248 of file LeanElasticPeaksWorkspace.h.
Referenced by addPeakColumn().
m_columns
std::vector<std::shared_ptr<Mantid::DataObjects::PeakColumn<LeanElasticPeak> > > Mantid::DataObjects::LeanElasticPeaksWorkspace::m_columns private
Column shared pointers.
Definition at line 245 of file LeanElasticPeaksWorkspace.h.
Referenced by addPeakColumn(), getColumn(), getColumn(), and getColumnIndex().
m_coordSystem
Kernel::SpecialCoordinateSystem Mantid::DataObjects::LeanElasticPeaksWorkspace::m_coordSystem private
Coordinates.
Definition at line 251 of file LeanElasticPeaksWorkspace.h.
Referenced by getSpecialCoordinateSystem(), saveNexus(), and setCoordinateSystem().
m_peaks
std::vector<LeanElasticPeak> Mantid::DataObjects::LeanElasticPeaksWorkspace::m_peaks private
Vector of Peak contained within.
Definition at line 242 of file LeanElasticPeaksWorkspace.h.
Referenced by addPeak(), addPeak(), addPeakColumn(), getNumberPeaks(), getPeak(), getPeak(), getPeaks(), getPeaks(), removePeak(), removePeaks(), saveNexus(), and sort().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/LeanElasticPeaksWorkspace.h
Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp