Mantid: FindReplaceDialog Class Reference
FindReplaceDialog Class Reference
Raises a dialog allowing the user to find/replace text in the editor.
#include <FindReplaceDialog.h>
Public Member Functions
FindReplaceDialog (ScriptEditor *editor)
Constructor.
Public Member Functions inherited from MantidQt::API::MantidDialog
MantidDialog (QWidget *parent=nullptr, const Qt::WindowFlags &flags=Qt::WindowCloseButtonHint|Qt::WindowType::WindowTitleHint)
DefaultConstructor.
~MantidDialog () override
Destructor.
Protected Slots
void clearEditorSelection ()
Clear the editor selection.
bool find (bool backwards=false)
Find.
void findClicked ()
A slot for the findClicked button.
void findNotInProgress ()
Set the flag about whether we are currently finding.
void replace ()
Replace slot.
void replaceAll ()
Replace all slot.
void resetSearchFlags ()
Reset the search flags due to changes.
Protected Member Functions
void addReplaceBox ()
Add replace box.
void addReplaceButtons ()
Add the replace buttons.
void initLayout ()
Create the layout.
Protected Member Functions inherited from MantidQt::API::MantidDialog
virtual void handleException (const std::exception &e)
Override this method to handle an exception in a derived class.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Private Member Functions
void showEvent (QShowEvent *event) override
Called when the widget is shown.
Private Attributes
QCheckBox * boxCaseSensitive
Case-sensitive check box.
QComboBox * boxFind
Find box.
QCheckBox * boxRegex
Treat as regular expressions.
QComboBox * boxReplace
Replace box.
QCheckBox * boxSearchBackwards
Search backwards.
QCheckBox * boxWholeWords
Whole words check box.
QCheckBox * boxWrapAround
Wrap around.
QPushButton * buttonCancel
Cancel dialog button.
QPushButton * buttonNext
Find next match button.
QPushButton * buttonReplace
Replace text button.
QPushButton * buttonReplaceAll
Replace all text button.
ScriptEditor * m_editor
The text editor we are working on.
bool m_findInProgress
If a find is in progress.
QGridLayout * m_topLayout
QVBoxLayout * m_vb2
Additional Inherited Members
Signals inherited from MantidQt::API::MantidDialog
void runAsPythonScript (const QString &code, bool)
Static Public Member Functions inherited from MantidQt::API::MantidDialog
static bool handle (QObject *receiver, const std::exception &e)
Handles the exception caught in an event handler.
Detailed Description
Raises a dialog allowing the user to find/replace text in the editor.
Definition at line 31 of file FindReplaceDialog.h.
Constructor & Destructor Documentation
FindReplaceDialog()
FindReplaceDialog::FindReplaceDialog (ScriptEditor * editor)
Constructor.
Definition at line 28 of file FindReplaceDialog.cpp.
References initLayout().
Member Function Documentation
addReplaceBox()
void FindReplaceDialog::addReplaceBox () protected
Add replace box.
Definition at line 112 of file FindReplaceDialog.cpp.
References boxReplace, and m_topLayout.
Referenced by initLayout().
addReplaceButtons()
void FindReplaceDialog::addReplaceButtons () protected
Add the replace buttons.
Definition at line 127 of file FindReplaceDialog.cpp.
References buttonReplace, buttonReplaceAll, m_vb2, replace(), and replaceAll().
Referenced by initLayout().
clearEditorSelection
void FindReplaceDialog::clearEditorSelection () protected slot
Clear the editor selection.
Clear the selection in the editor.
Definition at line 248 of file FindReplaceDialog.cpp.
References m_editor.
Referenced by resetSearchFlags().
find
bool FindReplaceDialog::find (bool backwards = false) protected slot
Find.
Find the current search term.
Parameters
backwards :: If true then the search procedes backwards from the cursor's current position
Returns
A boolean indicating success/failure
Definition at line 146 of file FindReplaceDialog.cpp.
References boxCaseSensitive, boxFind, boxRegex, boxWholeWords, boxWrapAround, m_editor, and m_findInProgress.
Referenced by findClicked(), and replace().
findClicked
void FindReplaceDialog::findClicked () protected slot
A slot for the findClicked button.
Find button clicked slot.
Definition at line 229 of file FindReplaceDialog.cpp.
References boxSearchBackwards, and find().
Referenced by initLayout().
findNotInProgress
void FindReplaceDialog::findNotInProgress () protected slot
Set the flag about whether we are currently finding.
Flip the in-progress flag.
Definition at line 243 of file FindReplaceDialog.cpp.
References m_findInProgress.
Referenced by resetSearchFlags().
initLayout()
void FindReplaceDialog::initLayout () protected
Create the layout.
Create the widgets and lay them out.
Definition at line 37 of file FindReplaceDialog.cpp.
References addReplaceBox(), addReplaceButtons(), boxCaseSensitive, boxFind, boxRegex, boxSearchBackwards, boxWholeWords, boxWrapAround, buttonCancel, buttonNext, findClicked(), m_topLayout, m_vb2, and resetSearchFlags().
Referenced by FindDialog::FindDialog(), and FindReplaceDialog().
replace
void FindReplaceDialog::replace () protected slot
Replace slot.
Replace the next occurrence of the search term with the replacement text.
Definition at line 174 of file FindReplaceDialog.cpp.
References boxFind, boxReplace, find(), and m_editor.
Referenced by addReplaceButtons().
replaceAll
void FindReplaceDialog::replaceAll () protected slot
Replace all slot.
Replace all occurrences of the current search term with the replacement text.
Definition at line 200 of file FindReplaceDialog.cpp.
References boxCaseSensitive, boxFind, boxRegex, boxReplace, boxSearchBackwards, boxWholeWords, boxWrapAround, m_editor, and ScriptEditor::replaceAll().
Referenced by addReplaceButtons().
resetSearchFlags
void FindReplaceDialog::resetSearchFlags () protected slot
Reset the search flags due to changes.
Definition at line 235 of file FindReplaceDialog.cpp.
References clearEditorSelection(), and findNotInProgress().
Referenced by initLayout().
showEvent()
void FindReplaceDialog::showEvent (QShowEvent * event) override private
Called when the widget is shown.
Parameters
event :: Parameterizes the dialog
Definition at line 254 of file FindReplaceDialog.cpp.
References boxFind, and m_editor.
Member Data Documentation
boxCaseSensitive
QCheckBox* FindReplaceDialog::boxCaseSensitive private
Case-sensitive check box.
Definition at line 84 of file FindReplaceDialog.h.
Referenced by find(), initLayout(), and replaceAll().
boxFind
QComboBox* FindReplaceDialog::boxFind private
Find box.
Definition at line 79 of file FindReplaceDialog.h.
Referenced by find(), initLayout(), replace(), replaceAll(), and showEvent().
boxRegex
QCheckBox* FindReplaceDialog::boxRegex private
Treat as regular expressions.
Definition at line 92 of file FindReplaceDialog.h.
Referenced by find(), initLayout(), and replaceAll().
boxReplace
QComboBox* FindReplaceDialog::boxReplace private
Replace box.
Definition at line 81 of file FindReplaceDialog.h.
Referenced by addReplaceBox(), replace(), and replaceAll().
boxSearchBackwards
QCheckBox* FindReplaceDialog::boxSearchBackwards private
Search backwards.
Definition at line 88 of file FindReplaceDialog.h.
Referenced by findClicked(), initLayout(), and replaceAll().
boxWholeWords
QCheckBox* FindReplaceDialog::boxWholeWords private
Whole words check box.
Definition at line 86 of file FindReplaceDialog.h.
Referenced by find(), initLayout(), and replaceAll().
boxWrapAround
QCheckBox* FindReplaceDialog::boxWrapAround private
Wrap around.
Definition at line 90 of file FindReplaceDialog.h.
Referenced by find(), initLayout(), and replaceAll().
buttonCancel
QPushButton* FindReplaceDialog::buttonCancel private
Cancel dialog button.
Definition at line 76 of file FindReplaceDialog.h.
Referenced by initLayout().
buttonNext
QPushButton* FindReplaceDialog::buttonNext private
Find next match button.
Definition at line 70 of file FindReplaceDialog.h.
Referenced by initLayout().
buttonReplace
QPushButton* FindReplaceDialog::buttonReplace private
Replace text button.
Definition at line 72 of file FindReplaceDialog.h.
Referenced by addReplaceButtons().
buttonReplaceAll
QPushButton* FindReplaceDialog::buttonReplaceAll private
Replace all text button.
Definition at line 74 of file FindReplaceDialog.h.
Referenced by addReplaceButtons().
m_editor
ScriptEditor* FindReplaceDialog::m_editor private
The text editor we are working on.
Definition at line 68 of file FindReplaceDialog.h.
Referenced by clearEditorSelection(), find(), replace(), replaceAll(), and showEvent().
m_findInProgress
bool FindReplaceDialog::m_findInProgress private
If a find is in progress.
Definition at line 95 of file FindReplaceDialog.h.
Referenced by find(), and findNotInProgress().
m_topLayout
QGridLayout* FindReplaceDialog::m_topLayout private
Definition at line 97 of file FindReplaceDialog.h.
Referenced by addReplaceBox(), and initLayout().
m_vb2
QVBoxLayout* FindReplaceDialog::m_vb2 private
Definition at line 98 of file FindReplaceDialog.h.
Referenced by addReplaceButtons(), and initLayout().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FindReplaceDialog.h
qt/widgets/common/src/FindReplaceDialog.cpp