Mantid: Framework/PythonInterface/mantid/api/src/Exports/IFunction.cpp File Reference
IFunction.cpp File Reference
#include "MantidAPI/CompositeFunction.h"
#include "MantidAPI/FunctionDomain.h"
#include "MantidAPI/Jacobian.h"
#include "MantidAPI/MatrixWorkspace.h"
#include "MantidCurveFitting/Jacobian.h"
#include "MantidKernel/IPropertyManager.h"
#include "MantidKernel/PropertyWithValue.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/api/FitFunctions/IFunctionAdapter.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/IsNone.h"
#include "MantidPythonInterface/kernel/Registry/PropertyValueHandler.h"
#include "MantidPythonInterface/kernel/Registry/TypeRegistry.h"
#include "MantidPythonInterface/kernel/Registry/TypedPropertyValueHandler.h"
#include <boost/python/class.hpp>
#include <boost/python/def.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/manage_new_object.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/to_python_value.hpp>
#include <memory>
#include <string>
Functions
void export_IFunction ()
Function Documentation
export_IFunction()
void export_IFunction ()
Definition at line 179 of file IFunction.cpp.
References Mantid::API::IFunction::addConstraints(), Mantid::API::IFunction::addTies(), Mantid::API::IFunction::asString(), Mantid::PythonInterface::IFunctionAdapter::category(), Mantid::API::IFunction::clone(), Mantid::PythonInterface::IFunctionAdapter::createPythonEquivalentFunctions(), Mantid::PythonInterface::IFunctionAdapter::declareAttribute(), Mantid::PythonInterface::IFunctionAdapter::declareFitParameter(), Mantid::PythonInterface::IFunctionAdapter::declareFitParameterNoDescr(), Mantid::PythonInterface::IFunctionAdapter::declareFitParameterZeroInit(), Mantid::API::IFunction::fix(), Mantid::API::IFunction::fixAll(), Mantid::API::IFunction::fixParameter(), Mantid::API::IFunction::getAttributeNames(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::API::IFunction::getError(), Mantid::API::IFunction::getFunction(), Mantid::API::IFunction::getNumberDomains(), Mantid::API::IFunction::getParameter(), Mantid::API::IFunction::hasAttribute(), Mantid::API::IFunction::hasParameter(), Mantid::API::IFunction::initialize(), Mantid::API::IFunction::isExplicitlySet(), Mantid::API::IFunction::isFixed(), Mantid::API::IFunction::name(), Mantid::API::IFunction::nAttributes(), Mantid::API::IFunction::nParams(), Mantid::API::IFunction::parameterDescription(), Mantid::API::IFunction::parameterIndex(), Mantid::API::IFunction::parameterName(), Mantid::API::IFunction::removeConstraint(), Mantid::API::IFunction::removeTie(), Mantid::PythonInterface::IFunctionAdapter::setAttributePythonValue(), Mantid::API::IFunction::setConstraintPenaltyFactor(), Mantid::API::IFunction::setError(), Mantid::API::IFunction::setParameter(), Mantid::API::IFunction::tie(), Mantid::API::IFunction::unfix(), Mantid::API::IFunction::unfixAll(), Mantid::API::IFunction::unfixParameter(), Mantid::API::IFunction::writeConstraints(), and Mantid::API::IFunction::writeTies().