Mantid: ICat4::ns1__investigationType Class Reference
ICat4::ns1__investigationType Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__investigationType ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * description
ns1__facility * facility
std::vector< ns1__investigation * > investigations
std::string * name
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1956 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__investigationType()
ICat4::ns1__investigationType::ns1__investigationType () inline
Definition at line 1970 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__investigationType::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12487 of file ICat4C.cpp.
References description, facility, investigations, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigation().
Referenced by ICat4::soap_in_ns1__investigationType(), ICat4::soap_new_req_ns1__investigationType(), and ICat4::soap_new_set_ns1__investigationType().
soap_get()
void * ICat4::ns1__investigationType::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12652 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__investigationType().
soap_in()
void * ICat4::ns1__investigationType::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12541 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__investigationType().
Referenced by ICat4::soap_in_ns1__investigationType().
soap_out()
int ICat4::ns1__investigationType::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12509 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__investigationType().
Referenced by soap_put().
soap_put()
int ICat4::ns1__investigationType::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12645 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__investigationType.
soap_serialize()
void ICat4::ns1__investigationType::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12497 of file ICat4C.cpp.
References description, facility, investigations, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigation().
Referenced by ICat4::soap_serialize_PointerTons1__investigation().
soap_type()
int ICat4::ns1__investigationType::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1963 of file ICat4Stub.h.
Member Data Documentation
description
std::string* ICat4::ns1__investigationType::description
Definition at line 1958 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
facility
ns1__facility* ICat4::ns1__investigationType::facility
Definition at line 1959 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigations
std::vector<ns1__investigation *> ICat4::ns1__investigationType::investigations
Definition at line 1960 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__investigationType::name
Definition at line 1961 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp