Mantid: Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy Class Reference
Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy Class Reference
#include <FindSXPeaksHelper.h>
Public Member Functions
PeakList dofindSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const HistogramData::HistogramE &e, Bound low, Bound high, const int workspaceIndex) const override
NSigmaPeaksStrategy (const API::SpectrumInfo &spectrumInfo, const double nsigma=EMPTY_DBL(), const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
Public Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
PeakList findSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const HistogramData::HistogramE &e, const int workspaceIndex) const
PeakFindingStrategy (const BackgroundStrategy *backgroundStrategy, const API::SpectrumInfo &spectrumInfo, const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
void setMinNBinsPerPeak (int minBinsPerPeak)
virtual ~PeakFindingStrategy ()=default
Private Member Functions
std::vector< std::unique_ptr< PeakContainer > > getAllNSigmaPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const HistogramData::HistogramE &e, Bound low, Bound high) const
Private Attributes
const double m_nsigma
Additional Inherited Members
Protected Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
double calculatePhi (size_t workspaceIndex) const
Calculates the average phi value if the workspace contains multiple detectors per spectrum, or returns the value of phi if it is a single detector to spectrum mapping.
PeakList convertToSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const std::vector< std::unique_ptr< PeakContainer > > &peaks, const int workspaceIndex) const
double convertToTOF (const double xValue, const size_t workspaceIndex) const
void filterPeaksForMinBins (std::vector< std::unique_ptr< PeakContainer > > &inputPeakList) const
BoundsIterator getBounds (const HistogramData::HistogramX &x) const
double getXValue (const HistogramData::HistogramX &x, const size_t peakLocation) const
Protected Attributes inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
const BackgroundStrategy * m_backgroundStrategy
const double m_maxValue = EMPTY_DBL()
int m_minNBinsPerPeak = EMPTY_INT()
const double m_minValue = EMPTY_DBL()
const API::SpectrumInfo & m_spectrumInfo
const XAxisUnit m_units
Detailed Description
Definition at line 211 of file FindSXPeaksHelper.h.
Constructor & Destructor Documentation
NSigmaPeaksStrategy()
Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy::NSigmaPeaksStrategy (const API::SpectrumInfo & spectrumInfo, const double nsigma = EMPTY_DBL(), const double minValue = EMPTY_DBL(), const double maxValue = EMPTY_DBL(), const XAxisUnit units = XAxisUnit::TOF)
Definition at line 536 of file FindSXPeaksHelper.cpp.
Member Function Documentation
dofindSXPeaks()
PeakList Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy::dofindSXPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, const HistogramData::HistogramE & e, Bound low, Bound high, const int workspaceIndex) const override virtual
Implements Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy.
Definition at line 540 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::convertToSXPeaks(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::filterPeaksForMinBins(), getAllNSigmaPeaks(), Mantid::Geometry::x, and Mantid::Geometry::y.
getAllNSigmaPeaks()
std::vector< std::unique_ptr< PeakContainer > > Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy::getAllNSigmaPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, const HistogramData::HistogramE & e, Bound low, Bound high) const private
Definition at line 552 of file FindSXPeaksHelper.cpp.
References m_nsigma, NSIGMA_COMPARISON_THRESHOLD, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by dofindSXPeaks().
Member Data Documentation
m_nsigma
const double Mantid::Crystal::FindSXPeaksHelper::NSigmaPeaksStrategy::m_nsigma private
Definition at line 225 of file FindSXPeaksHelper.h.
Referenced by getAllNSigmaPeaks().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
Framework/Crystal/src/FindSXPeaksHelper.cpp