Mantid: Mantid::Kernel::IPropertyManager::TypedValue Struct Reference
Mantid::Kernel::IPropertyManager::TypedValue Struct Reference
Utility class that enables the getProperty() method to effectively be templated on the return type.
#include <IPropertyManager.h>
Public Member Functions
operator bool ()
explicit specialization for bool()
operator double ()
explicit specialization for double()
operator int16_t ()
operator int32_t ()
operator int64_t ()
template<typename T >
operator Matrix< T > ()
explicit version for Matrices
operator OptionalBool ()
operator Property * ()
explicit specialization for Property*()
template<typename T >
operator std::shared_ptr< const T > ()
explicit specialization for std::shared_ptr to const T
template<typename T >
operator std::shared_ptr< T > ()
explicit specialization for std::shared_ptr
operator std::string ()
explicit specialization for std::string()
template<typename T >
operator std::vector< std::vector< T > > ()
explicit specialization for std::vector
template<typename T >
operator std::vector< T > ()
explicit specialization for std::vector
operator uint16_t ()
operator uint32_t ()
operator uint64_t ()
TypedValue (const IPropertyManager &p, const std::string &name)
Constructor.
Public Attributes
const IPropertyManager & pm
Reference to the containing PropertyManager.
const std::string prop
The name of the property desired.
Detailed Description
Utility class that enables the getProperty() method to effectively be templated on the return type.
Definition at line 374 of file IPropertyManager.h.
Constructor & Destructor Documentation
TypedValue()
Mantid::Kernel::IPropertyManager::TypedValue::TypedValue (const IPropertyManager & p, const std::string & name) inline
Constructor.
Definition at line 381 of file IPropertyManager.h.
Member Function Documentation
operator bool()
Mantid::Kernel::IPropertyManager::TypedValue::operator bool ()
explicit specialization for bool()
operator double()
Mantid::Kernel::IPropertyManager::TypedValue::operator double ()
explicit specialization for double()
operator int16_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator int16_t ()
operator int32_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator int32_t ()
operator int64_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator int64_t ()
operator Matrix< T >()
template<typename T > Mantid::Kernel::IPropertyManager::TypedValue::operator Matrix< T > () inline
explicit version for Matrices
Definition at line 423 of file IPropertyManager.h.
References Mantid::Kernel::IPropertyManager::getValue().
operator OptionalBool()
Mantid::Kernel::IPropertyManager::TypedValue::operator OptionalBool ()
operator Property *()
Mantid::Kernel::IPropertyManager::TypedValue::operator Property * ()
explicit specialization for Property*()
operator std::shared_ptr< const T >()
template<typename T > Mantid::Kernel::IPropertyManager::TypedValue::operator std::shared_ptr< const T > () inline
explicit specialization for std::shared_ptr to const T
Definition at line 421 of file IPropertyManager.h.
References Mantid::Kernel::IPropertyManager::getValue().
operator std::shared_ptr< T >()
template<typename T > Mantid::Kernel::IPropertyManager::TypedValue::operator std::shared_ptr< T > () inline
explicit specialization for std::shared_ptr
Definition at line 419 of file IPropertyManager.h.
References Mantid::Kernel::IPropertyManager::getValue().
operator std::string()
Mantid::Kernel::IPropertyManager::TypedValue::operator std::string ()
explicit specialization for std::string()
operator std::vector< std::vector< T > >()
template<typename T > Mantid::Kernel::IPropertyManager::TypedValue::operator std::vector< std::vector< T > > () inline
explicit specialization for std::vector
Definition at line 415 of file IPropertyManager.h.
References Mantid::Kernel::IPropertyManager::getValue().
operator std::vector< T >()
template<typename T > Mantid::Kernel::IPropertyManager::TypedValue::operator std::vector< T > () inline
explicit specialization for std::vector
Definition at line 413 of file IPropertyManager.h.
References Mantid::Kernel::IPropertyManager::getValue().
operator uint16_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator uint16_t ()
operator uint32_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator uint32_t ()
operator uint64_t()
Mantid::Kernel::IPropertyManager::TypedValue::operator uint64_t ()
Member Data Documentation
pm
const IPropertyManager& Mantid::Kernel::IPropertyManager::TypedValue::pm
Reference to the containing PropertyManager.
Definition at line 376 of file IPropertyManager.h.
prop
const std::string Mantid::Kernel::IPropertyManager::TypedValue::prop
The name of the property desired.
Definition at line 378 of file IPropertyManager.h.
The documentation for this struct was generated from the following file:
Framework/Kernel/inc/MantidKernel/IPropertyManager.h