Mantid: Mantid::Kernel::Units::Label Class Reference
Mantid::Kernel::Units::Label Class Reference
Label unit.
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
Label ()
Constructor.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
Label (const std::string &caption, const std::string &label)
void setLabel (const std::string &cpt, const UnitLabel &lbl=UnitLabel(""))
Set a caption and a label.
const std::string unitID () const override
"Label"
Public Member Functions inherited from Mantid::Kernel::Units::Empty
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
double conversionTOFMin () const override
Empty ()
Constructor.
void init () override
Finalize the initialization.
bool isConvertible () const override
Returns if the unit can be used in conversions.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"Empty"
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Private Attributes
std::string m_caption
Caption.
UnitLabel m_label
Label.
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Label unit.
Definition at line 263 of file Unit.h.
Constructor & Destructor Documentation
Label() [1/2]
Mantid::Kernel::Units::Label::Label ()
Constructor.
Definition at line 255 of file Unit.cpp.
Referenced by clone().
Label() [2/2]
Mantid::Kernel::Units::Label::Label (const std::string & caption, const std::string & label)
Definition at line 257 of file Unit.cpp.
References caption(), label(), and setLabel().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::Label::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Reimplemented from Mantid::Kernel::Units::Empty.
Definition at line 266 of file Unit.h.
Referenced by Label().
clone()
Unit * Mantid::Kernel::Units::Label::clone () const override virtual
Returns
a cloned instance of the other
Reimplemented from Mantid::Kernel::Units::Empty.
Definition at line 269 of file Unit.cpp.
References Label().
label()
const UnitLabel Mantid::Kernel::Units::Label::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Reimplemented from Mantid::Kernel::Units::Empty.
Definition at line 252 of file Unit.cpp.
Referenced by Label().
setLabel()
void Mantid::Kernel::Units::Label::setLabel (const std::string & cpt, const UnitLabel & lbl = UnitLabel(""))
Set a caption and a label.
Definition at line 264 of file Unit.cpp.
References m_caption, and m_label.
Referenced by export_Label(), and Label().
unitID()
const std::string Mantid::Kernel::Units::Label::unitID () const override virtual
"Label"
Reimplemented from Mantid::Kernel::Units::Empty.
Member Data Documentation
m_caption
std::string Mantid::Kernel::Units::Label::m_caption private
Caption.
Definition at line 276 of file Unit.h.
Referenced by setLabel().
m_label
UnitLabel Mantid::Kernel::Units::Label::m_label private
Label.
Definition at line 278 of file Unit.h.
Referenced by setLabel().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp