Mantid: MantidQt::MantidWidgets::FunctionModelDataset Struct Reference
MantidQt::MantidWidgets::FunctionModelDataset Struct Reference
#include <FunctionModelDataset.h>
Public Member Functions
const std::string & datasetName () const noexcept
std::vector< std::string > domainNames () const
Returns the names given to each domain (i.e.
FunctionModelDataset (std::string workspaceName, FunctionModelSpectra spectra)
std::size_t numberOfSpectra () const noexcept
Private Attributes
FunctionModelSpectra m_spectra
std::string m_workspaceName
Detailed Description
Definition at line 24 of file FunctionModelDataset.h.
Constructor & Destructor Documentation
FunctionModelDataset()
MantidQt::MantidWidgets::FunctionModelDataset::FunctionModelDataset (std::string workspaceName, FunctionModelSpectra spectra)
Definition at line 14 of file FunctionModelDataset.cpp.
Member Function Documentation
datasetName()
const std::string & MantidQt::MantidWidgets::FunctionModelDataset::datasetName () const inline noexcept
Definition at line 28 of file FunctionModelDataset.h.
domainNames()
std::vector< std::string > MantidQt::MantidWidgets::FunctionModelDataset::domainNames () const
Returns the names given to each domain (i.e.
spectrum) in this dataset. This is required for display in the EditLocalParameter Dialog.
Returns
the names given to each domain (i.e. spectrum) in this dataset.
Definition at line 23 of file FunctionModelDataset.cpp.
References MantidQt::MantidWidgets::FunctionModelSpectra::begin(), MantidQt::MantidWidgets::FunctionModelSpectra::end(), m_spectra, m_workspaceName, MantidQt::MantidWidgets::FunctionModelSpectra::size(), and MantidQt::MantidWidgets::IndexType< Class >::value.
numberOfSpectra()
std::size_t MantidQt::MantidWidgets::FunctionModelDataset::numberOfSpectra () const inline noexcept
Definition at line 31 of file FunctionModelDataset.h.
Member Data Documentation
m_spectra
FunctionModelSpectra MantidQt::MantidWidgets::FunctionModelDataset::m_spectra private
Definition at line 35 of file FunctionModelDataset.h.
Referenced by domainNames().
m_workspaceName
std::string MantidQt::MantidWidgets::FunctionModelDataset::m_workspaceName private
Definition at line 34 of file FunctionModelDataset.h.
Referenced by domainNames().
The documentation for this struct was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h
qt/widgets/common/src/FunctionModelDataset.cpp