Mantid: MantidQt::MantidWidgets::FitScriptGeneratorPresenter Class Reference
MantidQt::MantidWidgets::FitScriptGeneratorPresenter Class Reference
#include <FitScriptGeneratorPresenter.h>
Public Member Functions
FitScriptGeneratorPresenter (IFitScriptGeneratorView *view, IFitScriptGeneratorModel *model, QStringList const &workspaceNames=QStringList(), double startX=0.0, double endX=0.0)
void notifyPresenter (ViewEvent const &event, FittingMode fittingMode) override
void notifyPresenter (ViewEvent const &event, std::string const &arg1="", std::string const &arg2="") override
void notifyPresenter (ViewEvent const &event, std::vector< std::string > const &vec) override
void openFitScriptGenerator () override
void setGlobalParameters (std::vector< GlobalParameter > const &globalParameters) override
void setGlobalTies (std::vector< GlobalTie > const &globalTies) override
~FitScriptGeneratorPresenter () override
Public Member Functions inherited from MantidQt::MantidWidgets::IFitScriptGeneratorPresenter
virtual void notifyPresenter (ViewEvent const &event, FittingMode fittingMode)=0
virtual void notifyPresenter (ViewEvent const &event, std::string const &arg1="", std::string const &arg2="")=0
virtual void notifyPresenter (ViewEvent const &event, std::vector< std::string > const &vec)=0
virtual void openFitScriptGenerator ()=0
virtual void setGlobalParameters (std::vector< MantidQt::MantidWidgets::GlobalParameter > const &globalParameters)=0
virtual void setGlobalTies (std::vector< MantidQt::MantidWidgets::GlobalTie > const &globalTies)=0
virtual ~IFitScriptGeneratorPresenter ()=default
Private Member Functions
void addFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)
void addWorkspace (Mantid::API::MatrixWorkspace_const_sptr const &workspace, double startX, double endX)
void addWorkspace (Mantid::API::MatrixWorkspace_const_sptr const &workspace, WorkspaceIndex workspaceIndex, double startX, double endX)
void addWorkspace (std::string const &workspaceName, double startX, double endX)
void addWorkspace (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX)
void addWorkspaces (std::vector< Mantid::API::MatrixWorkspace_const_sptr > const &workspaces, std::vector< WorkspaceIndex > const &workspaceIndices)
void checkForWarningMessages ()
std::tuple< std::string, std::string > convertFunctionIndexOfParameterTie (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &parameter, std::string const &tie) const
template<typename Generator >
void generateFitScript (Generator &&func) const
void generateScriptToClipboard () const
void generateScriptToFile () const
std::vector< FitDomainIndex > getDomainsWithLocalParameter (std::string const &parameter) const
std::vector< FitDomainIndex > getRowIndices () const
void handleAddDomainAccepted ()
void handleAddDomainClicked ()
void handleADSClearEvent ()
void handleADSDeleteEvent (std::string const &workspaceName)
void handleADSRenameEvent (std::string const &workspaceName, std::string const &newName)
void handleAttributeChanged (std::string const &attribute)
void handleEditLocalParameterClicked (std::string const &parameter)
void handleEditLocalParameterFinished ()
void handleEndXChanged ()
void handleFittingModeChanged (FittingMode fittingMode)
void handleFunctionAdded (std::string const &function)
void handleFunctionRemoved (std::string const &function)
void handleFunctionReplaced (std::string const &function)
void handleGenerateScriptToClipboardClicked ()
void handleGenerateScriptToFileClicked ()
void handleGlobalParametersChanged (std::vector< std::string > const &globalParameters)
void handleOutputBaseNameChanged (std::string const &outputBaseName)
void handleParameterChanged (std::string const &parameter)
void handleParameterConstraintChanged (std::string const &functionIndex, std::string const &constraint)
void handleParameterConstraintRemoved (std::string const &parameter)
void handleParameterTieChanged (std::string const &parameter, std::string const &tie)
void handleRemoveDomainClicked ()
void handleSelectionChanged ()
void handleStartXChanged ()
void insertLocalParameterData (std::string const &parameter, std::vector< std::string > &workspaceNames, std::vector< std::string > &domainNames, std::vector< double > &values, std::vector< bool > &fixes, std::vector< std::string > &ties, std::vector< std::string > &constraints) const
void insertLocalParameterDataForDomain (FitDomainIndex domainIndex, std::string const &parameter, std::vector< std::string > &workspaceNames, std::vector< std::string > &domainNames, std::vector< double > &values, std::vector< bool > &fixes, std::vector< std::string > &ties, std::vector< std::string > &constraints) const
template<typename Function , typename... Args>
void invokeFunctionForDomain (FitDomainIndex domainIndex, Function &&func, Args... arguments)
void removeDomains (std::vector< FitDomainIndex > const &domainIndices)
void removeFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)
void removeParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &parameter)
void setFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)
void setLocalParameterDataForDomain (FitDomainIndex domainIndex, std::string const &parameter, double value, bool fix, std::string const &tie, std::string const &constraint)
void setWorkspaces (QStringList const &workspaceNames, double startX, double endX)
void updateAttributeValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullAttribute, Mantid::API::IFunction::Attribute const &newValue)
void updateEndX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double endX)
void updateFunctionInViewFromModel (FitDomainIndex domainIndex)
template<typename UpdateFunction , typename... Args>
void updateFunctionsInModel (UpdateFunction &&updateFunction, Args... arguments)
template<typename UpdateFunction >
void updateFunctionStructure (UpdateFunction &&updateFunction, std::string const &function)
void updateParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex, std::string const &constraint)
void updateParameterTie (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &parameter, std::string const &tie)
void updateParameterValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &parameter, double newValue)
void updateStartX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX)
template<typename GetX , typename UpdateX >
void updateXLimitForDomain (GetX &&getX, UpdateX &&updateX)
Private Attributes
IFitScriptGeneratorModel * m_model
IFitScriptGeneratorView * m_view
std::vector< std::string > m_warnings
Detailed Description
Definition at line 30 of file FitScriptGeneratorPresenter.h.
Constructor & Destructor Documentation
FitScriptGeneratorPresenter()
MantidQt::MantidWidgets::FitScriptGeneratorPresenter::FitScriptGeneratorPresenter (IFitScriptGeneratorView * view, IFitScriptGeneratorModel * model, QStringList const & workspaceNames = QStringList(), double startX = 0.0, double endX = 0.0)
Definition at line 25 of file FitScriptGeneratorPresenter.cpp.
References m_model, m_view, setWorkspaces(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::subscribePresenter(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::subscribePresenter().
~FitScriptGeneratorPresenter()
MantidQt::MantidWidgets::FitScriptGeneratorPresenter::~FitScriptGeneratorPresenter () override default
Member Function Documentation
addFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) private
Definition at line 389 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::addFunction(), and m_model.
Referenced by handleFunctionAdded().
addWorkspace() [1/4]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace (Mantid::API::MatrixWorkspace_const_sptr const & workspace, double startX, double endX) private
Definition at line 297 of file FitScriptGeneratorPresenter.cpp.
References addWorkspace(), index, and workspace.
addWorkspace() [2/4]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace (Mantid::API::MatrixWorkspace_const_sptr const & workspace, WorkspaceIndex workspaceIndex, double startX, double endX) private
Definition at line 303 of file FitScriptGeneratorPresenter.cpp.
References addWorkspace(), and workspace.
addWorkspace() [3/4]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace (std::string const & workspaceName, double startX, double endX) private
Definition at line 291 of file FitScriptGeneratorPresenter.cpp.
References addWorkspace(), and Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by addWorkspace(), addWorkspaces(), and setWorkspaces().
addWorkspace() [4/4]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) private
Definition at line 308 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::addWorkspaceDomain(), MantidQt::MantidWidgets::IFitScriptGeneratorView::addWorkspaceDomain(), m_model, m_view, and m_warnings.
addWorkspaces()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspaces (std::vector< Mantid::API::MatrixWorkspace_const_sptr > const & workspaces, std::vector< WorkspaceIndex > const & workspaceIndices) private
Definition at line 280 of file FitScriptGeneratorPresenter.cpp.
References addWorkspace(), checkForWarningMessages(), and workspace.
Referenced by handleAddDomainAccepted().
checkForWarningMessages()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::checkForWarningMessages () private
Definition at line 512 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), m_view, and m_warnings.
Referenced by addWorkspaces(), handleParameterTieChanged(), and setWorkspaces().
convertFunctionIndexOfParameterTie()
std::tuple< std::string, std::string > MantidQt::MantidWidgets::FitScriptGeneratorPresenter::convertFunctionIndexOfParameterTie (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & parameter, std::string const & tie) const private
Definition at line 503 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentFunctionIndexForDomain(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentParameterTieForDomain(), and m_model.
Referenced by updateParameterTie().
generateFitScript()
template<typename Generator > void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateFitScript (Generator && func) const private
Definition at line 521 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::isValid(), m_model, and m_view.
Referenced by handleGenerateScriptToClipboardClicked(), and handleGenerateScriptToFileClicked().
generateScriptToClipboard()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToClipboard () const private
Definition at line 539 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::fitOptions(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::generatePythonFitScript(), m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::saveTextToClipboard(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::setSuccessText().
Referenced by handleGenerateScriptToClipboardClicked().
generateScriptToFile()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToFile () const private
Definition at line 531 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::filepath(), MantidQt::MantidWidgets::IFitScriptGeneratorView::fitOptions(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::generatePythonFitScript(), m_model, m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::setSuccessText().
Referenced by handleGenerateScriptToFileClicked().
getDomainsWithLocalParameter()
std::vector< FitDomainIndex > MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getDomainsWithLocalParameter (std::string const & parameter) const private
Definition at line 491 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFullParameter(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::hasParameter(), m_model, and m_view.
Referenced by handleEditLocalParameterFinished().
getRowIndices()
std::vector< FitDomainIndex > MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getRowIndices () const private
Definition at line 442 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows(), MantidQt::MantidWidgets::IFitScriptGeneratorView::applyFunctionChangesToAll(), m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::selectedRows().
Referenced by updateFunctionsInModel().
handleAddDomainAccepted()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAddDomainAccepted () private
Definition at line 151 of file FitScriptGeneratorPresenter.cpp.
References addWorkspaces(), MantidQt::MantidWidgets::IFitScriptGeneratorView::getDialogWorkspaceIndices(), MantidQt::MantidWidgets::IFitScriptGeneratorView::getDialogWorkspaces(), and m_view.
Referenced by notifyPresenter().
handleAddDomainClicked()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAddDomainClicked () private
Definition at line 149 of file FitScriptGeneratorPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::openAddWorkspaceDialog().
Referenced by notifyPresenter().
handleADSClearEvent()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSClearEvent () private
Definition at line 140 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows(), m_view, and removeDomains().
Referenced by notifyPresenter().
handleADSDeleteEvent()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSDeleteEvent (std::string const & workspaceName) private
Definition at line 131 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows(), index, m_view, removeDomains(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceName().
Referenced by notifyPresenter().
handleADSRenameEvent()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSRenameEvent (std::string const & workspaceName, std::string const & newName) private
Definition at line 142 of file FitScriptGeneratorPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorModel::renameWorkspace(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::renameWorkspace().
Referenced by notifyPresenter().
handleAttributeChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAttributeChanged (std::string const & attribute) private
Definition at line 195 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::attributeValue(), m_view, updateAttributeValue(), and updateFunctionsInModel().
Referenced by notifyPresenter().
handleEditLocalParameterClicked()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEditLocalParameterClicked (std::string const & parameter) private
Definition at line 228 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getAdjustedFunctionIndex(), insertLocalParameterData(), m_model, m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::openEditLocalParameterDialog().
Referenced by notifyPresenter().
handleEditLocalParameterFinished()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEditLocalParameterFinished () private
Definition at line 238 of file FitScriptGeneratorPresenter.cpp.
References getDomainsWithLocalParameter(), MantidQt::MantidWidgets::IFitScriptGeneratorView::getEditLocalParameterResults(), handleSelectionChanged(), m_view, and setLocalParameterDataForDomain().
Referenced by notifyPresenter().
handleEndXChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEndXChanged () private
Definition at line 173 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::endX(), updateEndX(), and updateXLimitForDomain().
Referenced by notifyPresenter().
handleFittingModeChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleFittingModeChanged (FittingMode fittingMode) private
Definition at line 253 of file FitScriptGeneratorPresenter.cpp.
References handleSelectionChanged(), m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::setFittingMode().
Referenced by notifyPresenter().
handleFunctionAdded()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleFunctionAdded (std::string const & function) private
Definition at line 181 of file FitScriptGeneratorPresenter.cpp.
References addFunction(), and updateFunctionStructure().
Referenced by notifyPresenter().
handleFunctionRemoved()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleFunctionRemoved (std::string const & function) private
Definition at line 177 of file FitScriptGeneratorPresenter.cpp.
References removeFunction(), and updateFunctionStructure().
Referenced by notifyPresenter().
handleFunctionReplaced()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleFunctionReplaced (std::string const & function) private
Definition at line 185 of file FitScriptGeneratorPresenter.cpp.
References setFunction(), and updateFunctionStructure().
Referenced by notifyPresenter().
handleGenerateScriptToClipboardClicked()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleGenerateScriptToClipboardClicked () private
Definition at line 262 of file FitScriptGeneratorPresenter.cpp.
References generateFitScript(), and generateScriptToClipboard().
Referenced by notifyPresenter().
handleGenerateScriptToFileClicked()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleGenerateScriptToFileClicked () private
Definition at line 258 of file FitScriptGeneratorPresenter.cpp.
References generateFitScript(), and generateScriptToFile().
Referenced by notifyPresenter().
handleGlobalParametersChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleGlobalParametersChanged (std::vector< std::string > const & globalParameters) private
Definition at line 219 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), handleSelectionChanged(), m_model, m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::setGlobalParameters().
Referenced by notifyPresenter().
handleOutputBaseNameChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleOutputBaseNameChanged (std::string const & outputBaseName) private
Definition at line 249 of file FitScriptGeneratorPresenter.cpp.
References m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::setOutputBaseName().
Referenced by notifyPresenter().
handleParameterChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterChanged (std::string const & parameter) private
Definition at line 189 of file FitScriptGeneratorPresenter.cpp.
References handleSelectionChanged(), m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::parameterValue(), updateFunctionsInModel(), and updateParameterValue().
Referenced by notifyPresenter().
handleParameterConstraintChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterConstraintChanged (std::string const & functionIndex, std::string const & constraint) private
Definition at line 213 of file FitScriptGeneratorPresenter.cpp.
References handleSelectionChanged(), updateFunctionsInModel(), and updateParameterConstraint().
Referenced by notifyPresenter().
handleParameterConstraintRemoved()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterConstraintRemoved (std::string const & parameter) private
Definition at line 208 of file FitScriptGeneratorPresenter.cpp.
References handleSelectionChanged(), removeParameterConstraint(), and updateFunctionsInModel().
Referenced by notifyPresenter().
handleParameterTieChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterTieChanged (std::string const & parameter, std::string const & tie) private
Definition at line 200 of file FitScriptGeneratorPresenter.cpp.
References checkForWarningMessages(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getGlobalTies(), handleSelectionChanged(), m_model, setGlobalTies(), updateFunctionsInModel(), and updateParameterTie().
Referenced by notifyPresenter().
handleRemoveDomainClicked()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleRemoveDomainClicked () private
Definition at line 147 of file FitScriptGeneratorPresenter.cpp.
References m_view, removeDomains(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::selectedRows().
Referenced by notifyPresenter().
handleSelectionChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged () private
Definition at line 159 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::clearFunction(), MantidQt::MantidWidgets::IFitScriptGeneratorView::currentRow(), MantidQt::MantidWidgets::IFitScriptGeneratorView::hasLoadedData(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::isSimultaneousMode(), m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::setSimultaneousMode(), and updateFunctionInViewFromModel().
Referenced by handleEditLocalParameterFinished(), handleFittingModeChanged(), handleGlobalParametersChanged(), handleParameterChanged(), handleParameterConstraintChanged(), handleParameterConstraintRemoved(), handleParameterTieChanged(), notifyPresenter(), and removeDomains().
handleStartXChanged()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleStartXChanged () private
Definition at line 169 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::startX(), updateStartX(), and updateXLimitForDomain().
Referenced by notifyPresenter().
insertLocalParameterData()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterData (std::string const & parameter, std::vector< std::string > & workspaceNames, std::vector< std::string > & domainNames, std::vector< double > & values, std::vector< bool > & fixes, std::vector< std::string > & ties, std::vector< std::string > & constraints) const private
Definition at line 446 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows(), insertLocalParameterDataForDomain(), and m_view.
Referenced by handleEditLocalParameterClicked().
insertLocalParameterDataForDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain (FitDomainIndex domainIndex, std::string const & parameter, std::vector< std::string > & workspaceNames, std::vector< std::string > & domainNames, std::vector< double > & values, std::vector< bool > & fixes, std::vector< std::string > & ties, std::vector< std::string > & constraints) const private
Definition at line 460 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getDomainName(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterConstraint(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterTie(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterValue(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::hasParameter(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::isParameterFixed(), m_model, m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceName().
Referenced by insertLocalParameterData().
invokeFunctionForDomain()
template<typename Function , typename... Args> void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::invokeFunctionForDomain (FitDomainIndex domainIndex, Function && func, Args... arguments) private
Definition at line 434 of file FitScriptGeneratorPresenter.cpp.
References m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceIndex(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceName().
Referenced by updateFunctionsInModel(), and updateXLimitForDomain().
notifyPresenter() [1/3]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, FittingMode fittingMode) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 119 of file FitScriptGeneratorPresenter.cpp.
References handleFittingModeChanged().
notifyPresenter() [2/3]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, std::string const & arg1 = "", std::string const & arg2 = "") override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 35 of file FitScriptGeneratorPresenter.cpp.
References handleAddDomainAccepted(), handleAddDomainClicked(), handleADSClearEvent(), handleADSDeleteEvent(), handleADSRenameEvent(), handleAttributeChanged(), handleEditLocalParameterClicked(), handleEditLocalParameterFinished(), handleEndXChanged(), handleFunctionAdded(), handleFunctionRemoved(), handleFunctionReplaced(), handleGenerateScriptToClipboardClicked(), handleGenerateScriptToFileClicked(), handleOutputBaseNameChanged(), handleParameterChanged(), handleParameterConstraintChanged(), handleParameterConstraintRemoved(), handleParameterTieChanged(), handleRemoveDomainClicked(), handleSelectionChanged(), and handleStartXChanged().
notifyPresenter() [3/3]
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, std::vector< std::string > const & vec) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 109 of file FitScriptGeneratorPresenter.cpp.
References handleGlobalParametersChanged().
openFitScriptGenerator()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::openFitScriptGenerator () override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 129 of file FitScriptGeneratorPresenter.cpp.
References m_view.
removeDomains()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeDomains (std::vector< FitDomainIndex > const & domainIndices) private
Definition at line 318 of file FitScriptGeneratorPresenter.cpp.
References handleSelectionChanged(), index, m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeDomain(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::removeDomain().
Referenced by handleADSClearEvent(), handleADSDeleteEvent(), and handleRemoveDomainClicked().
removeFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) private
Definition at line 384 of file FitScriptGeneratorPresenter.cpp.
References m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeFunction().
Referenced by handleFunctionRemoved().
removeParameterConstraint()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & parameter) private
Definition at line 369 of file FitScriptGeneratorPresenter.cpp.
References m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeParameterConstraint().
Referenced by handleParameterConstraintRemoved().
setFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) private
Definition at line 394 of file FitScriptGeneratorPresenter.cpp.
References m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::setFunction().
Referenced by handleFunctionReplaced().
setGlobalParameters()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setGlobalParameters (std::vector< GlobalParameter > const & globalParameters) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 270 of file FitScriptGeneratorPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::setGlobalParameters().
Referenced by updateFunctionInViewFromModel().
setGlobalTies()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setGlobalTies (std::vector< GlobalTie > const & globalTies) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorPresenter.
Definition at line 266 of file FitScriptGeneratorPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IFitScriptGeneratorView::setGlobalTies().
Referenced by handleParameterTieChanged().
setLocalParameterDataForDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain (FitDomainIndex domainIndex, std::string const & parameter, double value, bool fix, std::string const & tie, std::string const & constraint) private
Definition at line 474 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFullParameter(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::hasParameter(), m_model, MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterConstraint(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterFixed(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterTie(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterValue(), and value.
Referenced by handleEditLocalParameterFinished().
setWorkspaces()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setWorkspaces (QStringList const & workspaceNames, double startX, double endX) private
Definition at line 274 of file FitScriptGeneratorPresenter.cpp.
References addWorkspace(), and checkForWarningMessages().
Referenced by FitScriptGeneratorPresenter().
updateAttributeValue()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateAttributeValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullAttribute, Mantid::API::IFunction::Attribute const & newValue) private
Definition at line 352 of file FitScriptGeneratorPresenter.cpp.
References m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateAttributeValue().
Referenced by handleAttributeChanged().
updateEndX()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateEndX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double endX) private
Definition at line 336 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::resetSelection(), and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateEndX().
Referenced by handleEndXChanged().
updateFunctionInViewFromModel()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel (FitDomainIndex domainIndex) private
Definition at line 399 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFunction(), MantidQt::MantidWidgets::IFitScriptGeneratorModel::getGlobalParameters(), m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::setFunction(), setGlobalParameters(), MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceIndex(), and MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceName().
Referenced by handleSelectionChanged().
updateFunctionsInModel()
template<typename UpdateFunction , typename... Args> void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionsInModel (UpdateFunction && updateFunction, Args... arguments) private
Definition at line 427 of file FitScriptGeneratorPresenter.cpp.
References getRowIndices(), and invokeFunctionForDomain().
Referenced by handleAttributeChanged(), handleParameterChanged(), handleParameterConstraintChanged(), handleParameterConstraintRemoved(), handleParameterTieChanged(), and updateFunctionStructure().
updateFunctionStructure()
template<typename UpdateFunction > void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionStructure (UpdateFunction && updateFunction, std::string const & function) private
Definition at line 416 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::clearFunction(), MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), MantidQt::MantidWidgets::IFitScriptGeneratorView::hasLoadedData(), m_view, and updateFunctionsInModel().
Referenced by handleFunctionAdded(), handleFunctionRemoved(), and handleFunctionReplaced().
updateParameterConstraint()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & functionIndex, std::string const & constraint) private
Definition at line 375 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentFunctionIndexForDomain(), m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterConstraint().
Referenced by handleParameterConstraintChanged().
updateParameterTie()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterTie (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & parameter, std::string const & tie) private
Definition at line 358 of file FitScriptGeneratorPresenter.cpp.
References convertFunctionIndexOfParameterTie(), m_model, m_warnings, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterTie().
Referenced by handleParameterTieChanged().
updateParameterValue()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & parameter, double newValue) private
Definition at line 345 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentFunctionIndexForDomain(), m_model, and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterValue().
Referenced by handleParameterChanged().
updateStartX()
void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateStartX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX) private
Definition at line 327 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning(), m_model, m_view, MantidQt::MantidWidgets::IFitScriptGeneratorView::resetSelection(), and MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateStartX().
Referenced by handleStartXChanged().
updateXLimitForDomain()
template<typename GetX , typename UpdateX > void MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateXLimitForDomain (GetX && getX, UpdateX && updateX) private
Definition at line 407 of file FitScriptGeneratorPresenter.cpp.
References MantidQt::MantidWidgets::IFitScriptGeneratorView::currentRow(), MantidQt::MantidWidgets::IFitScriptGeneratorView::hasLoadedData(), invokeFunctionForDomain(), and m_view.
Referenced by handleEndXChanged(), and handleStartXChanged().
Member Data Documentation
m_model
IFitScriptGeneratorModel* MantidQt::MantidWidgets::FitScriptGeneratorPresenter::m_model private
Definition at line 148 of file FitScriptGeneratorPresenter.h.
Referenced by addFunction(), addWorkspace(), convertFunctionIndexOfParameterTie(), FitScriptGeneratorPresenter(), generateFitScript(), generateScriptToClipboard(), generateScriptToFile(), getDomainsWithLocalParameter(), handleADSRenameEvent(), handleEditLocalParameterClicked(), handleFittingModeChanged(), handleGlobalParametersChanged(), handleOutputBaseNameChanged(), handleParameterTieChanged(), handleSelectionChanged(), insertLocalParameterDataForDomain(), removeDomains(), removeFunction(), removeParameterConstraint(), setFunction(), setLocalParameterDataForDomain(), updateAttributeValue(), updateEndX(), updateFunctionInViewFromModel(), updateParameterConstraint(), updateParameterTie(), updateParameterValue(), and updateStartX().
m_view
IFitScriptGeneratorView* MantidQt::MantidWidgets::FitScriptGeneratorPresenter::m_view private
Definition at line 147 of file FitScriptGeneratorPresenter.h.
Referenced by addWorkspace(), checkForWarningMessages(), FitScriptGeneratorPresenter(), generateFitScript(), generateScriptToClipboard(), generateScriptToFile(), getDomainsWithLocalParameter(), getRowIndices(), handleAddDomainAccepted(), handleAddDomainClicked(), handleADSClearEvent(), handleADSDeleteEvent(), handleADSRenameEvent(), handleAttributeChanged(), handleEditLocalParameterClicked(), handleEditLocalParameterFinished(), handleGlobalParametersChanged(), handleParameterChanged(), handleRemoveDomainClicked(), handleSelectionChanged(), insertLocalParameterData(), insertLocalParameterDataForDomain(), invokeFunctionForDomain(), openFitScriptGenerator(), removeDomains(), setGlobalParameters(), setGlobalTies(), updateEndX(), updateFunctionInViewFromModel(), updateFunctionStructure(), updateStartX(), and updateXLimitForDomain().
m_warnings
std::vector<std::string> MantidQt::MantidWidgets::FitScriptGeneratorPresenter::m_warnings private
Definition at line 145 of file FitScriptGeneratorPresenter.h.
Referenced by addWorkspace(), checkForWarningMessages(), and updateParameterTie().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorPresenter.h
qt/widgets/common/src/FitScriptGeneratorPresenter.cpp