Mantid: Mantid Namespace Reference
Mantid Namespace Reference
Helper class which provides the Collimation Length for SANS instruments.
Namespaces
namespace Algorithms
namespace API
namespace Beamline
namespace Crystal
namespace CurveFitting
namespace DataHandling
namespace DataObjects
namespace FrameworkTestHelpers
namespace Geometry
namespace Histogram
namespace HistogramData
namespace ICat
namespace Indexing
namespace IndirectFitDataCreationHelper
namespace Instrumentation
namespace Kernel
namespace LegacyNexus
namespace mathLevel
namespace mathSupport
namespace MDAlgorithms
namespace Nexus
Header for a base Nexus::Exception.
namespace NexusGeometry
namespace PhysicalConstants
A namespace containing physical constants that are required by algorithms and unit routines.
namespace PropertyNames
namespace PythonInterface
namespace SingleCrystalDiffractionTestHelper
namespace Types
namespace WorkflowAlgorithms
Classes
class DTriple
Triple of three different things.
class NoDeleting
An object for constructing a shared_ptr that won't ever delete its pointee.
class TestChannel
class Triple
Triple of three identical types.
Typedefs
using coord_t = float
Typedef for the data type to use for coordinate axes in MD objects such as MDBox, MDEventWorkspace, etc.
using det2group_map = std::unordered_map< detid_t, std::set< detid_t > >
Map single det ID of group to its members.
using detid2det_map = std::map< detid_t, Geometry::IDetector_const_sptr >
Typedef of a map from detector ID to detector shared pointer.
using detid2index_map = std::unordered_map< detid_t, size_t >
Map with key = detector ID, value = workspace index.
using detid_t = int32_t
Typedef for a detector ID.
using MantidVec = std::vector< double >
typedef for the data storage used in Mantid matrix workspaces
using MantidVecPtr = Kernel::cow_ptr< MantidVec >
typedef for the pointer to data storage used in Mantid matrix workspaces
using signal_t = double
Typedef for the signal recorded in a MDBox, etc.
using spec2index_map = std::unordered_map< specnum_t, size_t >
Map with key = spectrum number, value = workspace index.
using specnum_t = int32_t
Typedef for a spectrum Number.
Functions
constexpr double EMPTY_DBL () noexcept
Returns what we consider an "empty" double within a property.
constexpr int EMPTY_INT () noexcept
Returns what we consider an "empty" integer within a property.
constexpr int64_t EMPTY_INT64 () noexcept
Returns what we consider an "empty" int64_t within a property.
constexpr long EMPTY_LONG () noexcept
Returns what we consider an "empty" long within a property.
double gsl_costFunction (const gsl_vector *x, void *params)
template<typename CInputIter >
int solveCubic (const CInputIter Coef, std::complex< double > &AnsA, std::complex< double > &AnsB, std::complex< double > &AnsC)
Solves Cubic equation.
template<typename InputIter >
MANTID_GEOMETRY_DLL int solveCubic (InputIter, std::complex< double > &, std::complex< double > &, std::complex< double > &)
Solve a Cubic equation.
template<typename InputIter >
int solveQuadratic (const InputIter Coef, std::pair< std::complex< double >, std::complex< double > > &OutAns)
Solves Complex Quadratic.
template<typename InputIter >
MANTID_GEOMETRY_DLL int solveQuadratic (InputIter, std::pair< std::complex< double >, std::complex< double > > &)
Solve a Quadratic equation.
MANTID_KERNEL_DLL std::string welcomeMessage ()
Returns the welcome message for Mantid.
Variables
const std::vector< std::string > validMarkerStyles
const std::vector< std::string > validPlotTypes {"plot", "marker", "histogram", "errorbar_x", "errorbar_y", "errorbar_xy"}
Detailed Description
Helper class which provides the Collimation Length for SANS instruments.
A bug in earlier boost versions, <= boost 1.41, means that using boost::register_ptr_to_python for const pointers gives a compiler error.
Policy that can convert to return type to a super type.
Defines a helper function to check whether an object is of Python type None.
This file defines error handling code that transforms a Python error state to a C++ exception.
Converter to generate a python dictionary from a std::map.
ContainerDtype Header File.
An algorithm used to crop an MDHistoWorkspace based on the first non-zero signals found in each dimension.
Define a.
StringTokenizer: A simple tokenizer that splits a string into tokens, which are separated by separator characters.
NearestNeighbours is a thin wrapper class around the ANN library for finding the k nearest neighbours.
This file contains functions to define empty values, i.e EMPTY_INT();.
This file contains typedefs for entities relating to multi-dimensional geometry.
LoadPSIMuonBin : Loads a bin file from the PSI facility for muon spectroscopy.
Shows integer offsets for each peak of their h,k and l values, along with max offset and run number and detector number.
Finds Goniometer angles for a 2nd run with the same chi and omega rotationa and only phi rotation changes by a specified amount.
A validator which checks that a workspace has an oriented lattice attached to it.
A validator which checks that the frame of the MDWorkspace referred to by a WorkspaceProperty is the expected one.
XML Parser for parameter types for ImplicitFunctions.
DetectorSearcher is a helper class to find a specific detector within the instrument geometry.
This class solves the problem of finding a detector given a Qlab vector. Two search strategies are used depending on the instrument's geometry.
1) For rectangular detector geometries the InstrumentRayTracer class is used to recursively search the instrument tree.
2) For geometries which do not use rectangular detectors ray tracing to every component is very expensive. In this case it is quicker to use a NearestNeighbours search to find likely detector positions.
Author
Samuel Jackson
Date
2017
Author
Owen Arnold, Tessella plc
Date
01/10/2010
Author
Ruth Mikkelson, SNS, ORNL
Date
04/15/2013
Author
Ruth Mikkelson, SNS, ORNL
Date
05/13/2013
Author
Martyn Gigg, Tessella plc
Given a vector of Eigen::Vectors this class will generate a KDTree. The tree can then be interrogated to find the closest k neighbours to a given position.
This classes is templated with a parameter N which defines the dimensionality of the vector type used. i.e. if N = 3 then Eigen::Vector3d is used.
Author
Samuel Jackson
Date
2017
An iterator or index can used to iterate over all tokens or the result returned as a std::vector<std::string>>
Author
Matt King
Date
02-10-2015
A helper free function to allow identification of data type being used by providing a numpy friendly string (using the numpy array interface).
Author
Lamar Moore STFC, Bhuvan Bezawada STFC
Date
21/06/2018
The boost::python::object method is_none was only added in version 1.43 and we still support some versions prior to this
This means that automatic conversion from const to non-const pointers in return values and function arguments is suppressed.
These policies simply removes the const from the returned pointer and emits the corresponding Python object using the registered converters. Two policies are defined:
RemoveConst: Bare pointers, return type must be "const T*"
RemoveConstSharedPtr: SharedPtr to const object, return type must be std::shared_ptr<const T>
Typedef Documentation
coord_t
using Mantid::coord_t = typedef float
Typedef for the data type to use for coordinate axes in MD objects such as MDBox, MDEventWorkspace, etc.
This could be a float or a double, depending on requirements. We can change this in order to compare performance/memory/accuracy requirements.
Definition at line 27 of file MDTypes.h.
det2group_map
using Mantid::det2group_map = typedef std::unordered_map<detid_t, std::set<detid_t> >
Map single det ID of group to its members.
Definition at line 22 of file SpectraDetectorTypes.h.
detid2det_map
using Mantid::detid2det_map = typedef std::map<detid_t, Geometry::IDetector_const_sptr>
Typedef of a map from detector ID to detector shared pointer.
Definition at line 27 of file Instrument.h.
detid2index_map
using Mantid::detid2index_map = typedef std::unordered_map<detid_t, size_t>
Map with key = detector ID, value = workspace index.
Definition at line 20 of file SpectraDetectorTypes.h.
detid_t
typedef int32_t Mantid::detid_t
Typedef for a detector ID.
Definition at line 21 of file SpectrumInfo.h.
MantidVec
using Mantid::MantidVec = typedef std::vector<double>
typedef for the data storage used in Mantid matrix workspaces
Definition at line 172 of file cow_ptr.h.
MantidVecPtr
using Mantid::MantidVecPtr = typedef Kernel::cow_ptr<MantidVec>
typedef for the pointer to data storage used in Mantid matrix workspaces
Definition at line 175 of file cow_ptr.h.
signal_t
using Mantid::signal_t = typedef double
Typedef for the signal recorded in a MDBox, etc.
Note: MDEvents use 'float' internally to save memory
Definition at line 36 of file MDTypes.h.
spec2index_map
using Mantid::spec2index_map = typedef std::unordered_map<specnum_t, size_t>
Map with key = spectrum number, value = workspace index.
Definition at line 18 of file SpectraDetectorTypes.h.
specnum_t
using Mantid::specnum_t = typedef int32_t
Typedef for a spectrum Number.
Definition at line 14 of file IDTypes.h.
Function Documentation
EMPTY_DBL()
constexpr double Mantid::EMPTY_DBL () constexpr noexcept
Returns what we consider an "empty" double within a property.
Returns
An flag value
Definition at line 42 of file EmptyValues.h.
Referenced by Mantid::CurveFitting::Functions::ProcessBackground::addRegion(), Mantid::Crystal::SCDCalibratePanels2::adjustComponent(), Mantid::Algorithms::ExportTimeSeriesLog::calculateTimeSeriesRangeByTime(), Mantid::Algorithms::ReplaceSpecialValues::checkifPropertyEmpty(), Mantid::Kernel::Detail::checkIsEmpty(), Mantid::DataHandling::ChopperConfiguration::ChopperConfiguration(), Mantid::Algorithms::GetEiMonDet3::computeTOF(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::Algorithms::CorrectTOFAxis::correctManually(), Mantid::WorkflowAlgorithms::MuonProcess::correctWorkspace(), Mantid::CurveFitting::Functions::FunctionQDepends::declareAttributes(), Mantid::CurveFitting::IMWDomainCreator::declareDatasetProperties(), Mantid::CurveFitting::TableWorkspaceDomainCreator::declareDatasetProperties(), Mantid::Algorithms::CylinderAbsorption::defineProperties(), Mantid::Algorithms::ReplaceSpecialValues::defineProperties(), Mantid::CurveFitting::Functions::ProcessBackground::deleteRegion(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::GetEi2::exec(), Mantid::Algorithms::LineProfile::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadSpiceXML2DDet::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::SaveSESANS::exec(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Kernel::TimeSeriesProperty< TYPE >::expandFilterToRange(), Mantid::Algorithms::ExportTimeSeriesLog::exportLog(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionMD(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionSD(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::function1D(), Mantid::CurveFitting::Functions::InelasticDiffSphere::function1D(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::getBounds(), MantidQt::MantidWidgets::FunctionTreeView::getConstraint(), WorkflowAlgorithmHelpers::getDblPropOrParam(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::Algorithms::ConvertSpectrumAxis2::getEfixed(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::getFilterROI(), Mantid::Algorithms::RemovePromptPulse::getFrequency(), MantidQt::MantidWidgets::FunctionTreeView::getFunctionAndConstraint(), Mantid::API::MatrixWorkspace::getImageStartEndXIndices(), Mantid::DataHandling::LoadHelper::getInstrumentProperty(), Mantid::Algorithms::FindPeaksConvolve::getKernelBinCount(), Mantid::WorkflowAlgorithms::DgsReduction::getParameter(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::getParameter(), Mantid::DataHandling::ChopperConfiguration::getParameter(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::getPeakParameter(), Mantid::Algorithms::RemoveLowResTOF::getTminData(), Mantid::Algorithms::UnwrapSNS::getTofRangeData(), Mantid::CurveFitting::IMWDomainCreator::getXInterval(), Mantid::CurveFitting::TableWorkspaceDomainCreator::getXInterval(), Mantid::Algorithms::AbsorptionCorrection::init(), Mantid::Algorithms::AddTimeSeriesLog::init(), Mantid::Algorithms::ApplyTransmissionCorrection::init(), Mantid::Algorithms::AverageLogData::init(), Mantid::Algorithms::CalculateCountRate::init(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::CalculateEfficiency::init(), Mantid::Algorithms::CalculateFlatBackground::init(), Mantid::Algorithms::CalculatePlaczek::init(), Mantid::Algorithms::CalculatePlaczekSelfScattering::init(), Mantid::Algorithms::CalculatePlaczekSelfScattering2::init(), Mantid::Algorithms::ChopData::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::ConvertSpectrumAxis::init(), Mantid::Algorithms::ConvertSpectrumAxis2::init(), Mantid::Algorithms::ConvertUnits::init(), Mantid::Algorithms::CopyDataRange::init(), Mantid::Algorithms::CorrectKiKf::init(), Mantid::Algorithms::CorrectTOFAxis::init(), Mantid::Algorithms::CreateFlatEventWorkspace::init(), Mantid::Algorithms::CreateFloodWorkspace::init(), Mantid::Algorithms::CropWorkspace::init(), Mantid::Algorithms::CrossCorrelate::init(), Mantid::Algorithms::DetectorDiagnostic::init(), Mantid::Algorithms::DetectorEfficiencyCor::init(), Mantid::Algorithms::DetectorEfficiencyCorUser::init(), Mantid::Algorithms::DetectorEfficiencyVariation::init(), Mantid::Algorithms::DetermineSpinStateOrder::init(), Mantid::Algorithms::EditInstrumentGeometry::init(), Mantid::Algorithms::ElasticWindow::init(), Mantid::Algorithms::EQSANSCorrectFrame::init(), Mantid::Algorithms::EstimateResolutionDiffraction::init(), Mantid::Algorithms::ExportTimeSeriesLog::init(), Mantid::Algorithms::ExtractMaskToTable::init(), Mantid::Algorithms::ExtractSpectra::init(), Mantid::Algorithms::FilterByLogValue::init(), Mantid::Algorithms::FilterByXValue::init(), Mantid::Algorithms::FilterEvents::init(), Mantid::Algorithms::FindCenterOfMassPosition2::init(), Mantid::Algorithms::FindDeadDetectors::init(), Mantid::Algorithms::FindDetectorsOutsideLimits::init(), Mantid::Algorithms::FindPeaks::init(), Mantid::Algorithms::FindPeaksConvolve::init(), Mantid::Algorithms::FitPeak::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::GenerateEventsFilter::init(), Mantid::Algorithms::GetEi2::init(), Mantid::Algorithms::GetEiMonDet3::init(), Mantid::Algorithms::GetTimeSeriesLogInformation::init(), Mantid::Algorithms::HRPDSlabCanAbsorption::init(), Mantid::Algorithms::HyspecScharpfCorrection::init(), Mantid::Algorithms::Integration::init(), Mantid::Algorithms::LineProfile::init(), Mantid::Algorithms::Max::init(), Mantid::Algorithms::MaxMin::init(), Mantid::Algorithms::MedianDetectorTest::init(), Mantid::Algorithms::Min::init(), Mantid::Algorithms::ModeratorTzeroLinear::init(), Mantid::Algorithms::MultipleScatteringCorrection::init(), Mantid::Algorithms::NormaliseToMonitor::init(), Mantid::Algorithms::NormaliseToUnity::init(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::init(), Mantid::Algorithms::PDCalibration::init(), Mantid::Algorithms::PDFFourierTransform::init(), Mantid::Algorithms::PDFFourierTransform2::init(), Mantid::Algorithms::RemoveBins::init(), Mantid::Algorithms::RemoveLowResTOF::init(), Mantid::Algorithms::RemovePromptPulse::init(), Mantid::Algorithms::SphericalAbsorption::init(), Mantid::Algorithms::Stitch1D::init(), Mantid::Algorithms::SumRowColumn::init(), Mantid::Algorithms::TOFSANSResolution::init(), Mantid::Algorithms::UnwrapSNS::init(), Mantid::Crystal::AnvredCorrection::init(), Mantid::Crystal::CombinePeaksWorkspaces::init(), Mantid::Crystal::FilterPeaks::init(), Mantid::Crystal::FindSXPeaks::init(), Mantid::Crystal::MaskPeaksWorkspace::init(), Mantid::Crystal::SaveHKL::init(), Mantid::Crystal::SaveLauenorm::init(), Mantid::Crystal::SCDCalibratePanels::init(), Mantid::Crystal::SCDCalibratePanels2::init(), Mantid::CurveFitting::Algorithms::Fit1D::init(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::init(), Mantid::CurveFitting::Algorithms::LeBailFit::init(), Mantid::CurveFitting::Functions::ProcessBackground::init(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), Mantid::DataHandling::CompressEvents::init(), Mantid::DataHandling::DetermineChunking::init(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadBBY2::init(), Mantid::DataHandling::LoadDiffCal::init(), Mantid::DataHandling::LoadEventAsWorkspace2D::init(), Mantid::DataHandling::LoadEventNexus::init(), Mantid::DataHandling::LoadHFIRSANS::init(), Mantid::DataHandling::LoadILLReflectometry::init(), Mantid::DataHandling::LoadPLN::init(), Mantid::DataHandling::LoadSampleEnvironment::init(), Mantid::DataHandling::LoadSpice2D::init(), Mantid::DataHandling::LoadSpiceXML2DDet::init(), Mantid::DataHandling::PatchBBY::init(), Mantid::DataHandling::PDLoadCharacterizations::init(), Mantid::DataHandling::SaveGSASInstrumentFile::init(), Mantid::DataHandling::SaveNXSPE::init(), Mantid::DataHandling::SaveSESANS::init(), Mantid::DataHandling::SetSampleMaterial::init(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::init(), Mantid::MDAlgorithms::CalculateCoverageDGS::init(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::init(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::init(), Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD::init(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::init(), Mantid::MDAlgorithms::IntegratePeaksCWSD::init(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::init(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::init(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::init(), Mantid::WorkflowAlgorithms::DgsReduction::init(), Mantid::WorkflowAlgorithms::EQSANSLoad::init(), Mantid::WorkflowAlgorithms::HFIRLoad::init(), Mantid::WorkflowAlgorithms::MuonProcess::init(), Mantid::WorkflowAlgorithms::SANSBeamFinder::init(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::init(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::init(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::init(), Mantid::WorkflowAlgorithms::SofTwoThetaTOF::init(), Mantid::WorkflowAlgorithms::StepScan::init(), Mantid::DataHandling::LoadEMU< FD >::init(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initInstance(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initInstance(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::integratePeak(), Mantid::Algorithms::Integration::integrateSpectrum(), Mantid::DataHandling::ReadMaterial::isEmpty(), Mantid::Kernel::PropertyHistory::isEmptyDefault(), Mantid::WorkflowAlgorithms::SANSBeamFinder::loadBeamFinderFile(), Mantid::DataHandling::LoadEventNexus::LoadEventNexus(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::loadSpiceData(), Mantid::Kernel::TimeSeriesProperty< TYPE >::makeFilterByValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::makeFilterByValue(), Mantid::API::TextAxis::operator()(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::Crystal::SCDCalibratePanels2::optimizeL1(), Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::outputAxisProfiles(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::processInputProperties(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::Algorithms::GetTimeSeriesLogInformation::processTimeRange(), Mantid::Algorithms::SphericalAbsorption::retrieveBaseProperties(), Mantid::Crystal::AnvredCorrection::retrieveBaseProperties(), Mantid::Algorithms::DetectorEfficiencyCor::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveProperties(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::Algorithms::HRPDSlabCanAbsorption::runFlatPlateAbsorption(), Mantid::Kernel::MaterialBuilder::setEffectiveNumberDensity(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::CurveFitting::Functions::FunctionQDepends::setMatrixWorkspace(), Mantid::Kernel::MaterialBuilder::setNumberDensity(), Mantid::Kernel::MaterialBuilder::setPackingFraction(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), Mantid::DataHandling::LoadEventNexus::setTimeFilters(), Mantid::Kernel::MaterialBuilder::setTotalScatterXSection(), Mantid::Algorithms::CorrectTOFAxis::validateInputs(), Mantid::Crystal::AnvredCorrection::validateInputs(), Mantid::Crystal::SCDCalibratePanels2::validateInputs(), Mantid::DataHandling::LoadEventAsWorkspace2D::validateInputs(), Mantid::DataHandling::SaveSESANS::validateInputs(), Mantid::Algorithms::FindPeaksConvolve::validatePeakExtentInput(), and Mantid::DataHandling::SaveGSASInstrumentFile::writePRMSingleBank().
EMPTY_INT()
constexpr int Mantid::EMPTY_INT () constexpr noexcept
Returns what we consider an "empty" integer within a property.
Returns
An flag value
Definition at line 24 of file EmptyValues.h.
Referenced by Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Kernel::Detail::checkIsEmpty(), Mantid::DataHandling::LoadRawHelper::checkOptionalProperties(), Mantid::DataHandling::LoadISISNexus2::checkOptionalProperties(), Mantid::DataHandling::LoadNexusProcessed::checkOptionalProperties(), Mantid::CurveFitting::Functions::FunctionQDepends::declareAttributes(), Mantid::Algorithms::SpectrumAlgorithm::declareWorkspaceIndexSetProperties(), Mantid::Algorithms::CalculateZscore::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::CopySample::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::FFT::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SetUB::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadLog::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::Algorithms::ExportTimeSeriesLog::exportLog(), Mantid::DataHandling::LoadEventNexusIndexSetup::filterIndexInfo(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::filterPeaksForMinBins(), Mantid::Algorithms::ProcessIndirectFitParameters::getEndRow(), Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getFinalPeaks(), WorkflowAlgorithmHelpers::getIntPropOrParam(), Mantid::DataHandling::MaskDetectors::getRanges(), Mantid::Algorithms::ProcessIndirectFitParameters::getStartRow(), Mantid::Crystal::MaskPeaksWorkspace::getWkspIndex(), Mantid::DataHandling::SaveNexusProcessed::getWSIndexList(), Mantid::Algorithms::AbsorptionCorrection::init(), Mantid::Algorithms::AnnularRingAbsorption::init(), Mantid::Algorithms::AppendSpectra::init(), Mantid::Algorithms::CalculateFlatBackground::init(), Mantid::Algorithms::CalculateTransmission::init(), Mantid::Algorithms::CalculateZscore::init(), Mantid::Algorithms::ChopData::init(), Mantid::Algorithms::CompareWorkspaces::init(), Mantid::Algorithms::CopyDataRange::init(), Mantid::Algorithms::CopySample::init(), Mantid::Algorithms::CorelliCrossCorrelate::init(), Mantid::Algorithms::CreateFloodWorkspace::init(), Mantid::Algorithms::CreateGroupingWorkspace::init(), Mantid::Algorithms::CropWorkspace::init(), Mantid::Algorithms::DetectorDiagnostic::init(), Mantid::Algorithms::DetectorEfficiencyVariation::init(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::init(), Mantid::Algorithms::ExportTimeSeriesLog::init(), Mantid::Algorithms::ExtractSpectra::init(), Mantid::Algorithms::FFT::init(), Mantid::Algorithms::FilterEvents::init(), Mantid::Algorithms::FindDetectorsOutsideLimits::init(), Mantid::Algorithms::FindPeakBackground::init(), Mantid::Algorithms::FindPeaks::init(), Mantid::Algorithms::FindPeaksConvolve::init(), Mantid::Algorithms::FitPeak::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::GenerateEventsFilter::init(), Mantid::Algorithms::GetAllEi::init(), Mantid::Algorithms::GetEi2::init(), Mantid::Algorithms::GetEiMonDet3::init(), Mantid::Algorithms::HRPDSlabCanAbsorption::init(), Mantid::Algorithms::Integration::init(), Mantid::Algorithms::Max::init(), Mantid::Algorithms::MaxMin::init(), Mantid::Algorithms::MedianDetectorTest::init(), Mantid::Algorithms::Min::init(), Mantid::Algorithms::MonteCarloAbsorption::init(), Mantid::Algorithms::MultipleScatteringCorrection::init(), Mantid::Algorithms::MultiplyRange::init(), Mantid::Algorithms::NormaliseToUnity::init(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::init(), Mantid::Algorithms::PDCalibration::init(), Mantid::Algorithms::RemoveBins::init(), Mantid::Algorithms::ScaleX::init(), Mantid::Algorithms::SolidAngle::init(), Mantid::Algorithms::StripPeaks::init(), Mantid::Algorithms::StripVanadiumPeaks::init(), Mantid::Algorithms::SumRowColumn::init(), Mantid::Algorithms::SumSpectra::init(), Mantid::Crystal::FindSXPeaks::init(), Mantid::Crystal::SaveHKL::init(), Mantid::Crystal::SaveLauenorm::init(), Mantid::Crystal::SetUB::init(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), Mantid::DataHandling::LoadAscii::init(), Mantid::DataHandling::LoadAscii2::init(), Mantid::DataHandling::LoadEventNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::LoadISISNexus2::init(), Mantid::DataHandling::LoadLog::init(), Mantid::DataHandling::LoadMuonNexusV2::init(), Mantid::DataHandling::LoadNexus::init(), Mantid::DataHandling::LoadNexusProcessed::init(), Mantid::DataHandling::LoadNGEM::init(), Mantid::DataHandling::LoadPreNexus::init(), Mantid::DataHandling::LoadPSIMuonBin::init(), Mantid::DataHandling::LoadRaw3::init(), Mantid::DataHandling::LoadRawBin0::init(), Mantid::DataHandling::LoadTOFRawNexus::init(), Mantid::DataHandling::MaskDetectors::init(), Mantid::DataHandling::PatchBBY::init(), Mantid::DataHandling::SaveAscii::init(), Mantid::DataHandling::SaveAscii2::init(), Mantid::DataHandling::SaveFullprofResolution::init(), Mantid::DataHandling::SaveNexus::init(), Mantid::DataHandling::SaveNexusProcessed::init(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::init(), Mantid::WorkflowAlgorithms::DgsReduction::init(), Mantid::WorkflowAlgorithms::MuonProcess::init(), Mantid::Algorithms::ProcessIndirectFitParameters::init(), Mantid::Kernel::PropertyHistory::isEmptyDefault(), Mantid::DataHandling::LoadTOFRawNexus::loadBank(), Mantid::DataHandling::LoadEventNexusIndexSetup::makeIndexInfo(), Mantid::DataHandling::LoadBankFromDiskTask::prepareEventId(), Mantid::DataHandling::LoadAscii2::processHeader(), Mantid::DataHandling::LoadAscii::processHeader(), Mantid::Crystal::FindSXPeaksHelper::SimpleReduceStrategy::reducePeaksFromNumberOfSpectras(), Mantid::Algorithms::MedianDetectorTest::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyVariation::retrieveProperties(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::CurveFitting::Functions::FunctionQDepends::setMatrixWorkspace(), Mantid::DataHandling::DefaultEventLoader::setupChunking(), Mantid::Algorithms::FindPeaksConvolve::storeClassProperties(), Mantid::Algorithms::FFT::validateInputs(), Mantid::Algorithms::FindPeaksConvolve::validatePeakExtentInput(), Mantid::DataHandling::SaveAscii2::write1DHistoCut(), and Mantid::DataHandling::SaveAscii2::writeTableWorkspace().
EMPTY_INT64()
constexpr int64_t Mantid::EMPTY_INT64 () constexpr noexcept
Returns what we consider an "empty" int64_t within a property.
Returns
An flag value
Definition at line 36 of file EmptyValues.h.
EMPTY_LONG()
constexpr long Mantid::EMPTY_LONG () constexpr noexcept
Returns what we consider an "empty" long within a property.
Returns
An flag value
Definition at line 30 of file EmptyValues.h.
Referenced by Mantid::Kernel::Detail::checkIsEmpty(), and Mantid::Kernel::PropertyHistory::isEmptyDefault().
gsl_costFunction()
double Mantid::gsl_costFunction (const gsl_vector * x, void * params)
Referenced by Mantid::CurveFitting::Algorithms::Fit1D::exec().
solveCubic() [1/2]
template<typename CInputIter > int Mantid::solveCubic (const CInputIter Coef, std::complex< double > & AnsA, std::complex< double > & AnsB, std::complex< double > & AnsC)
Solves Cubic equation.
Parameters
Coef :: iterator over all the coefients in the order
\[ Ax^3+Bx^2+Cx+D \]
.
AnsA,AnsB,AnsC :: complex roots of the equation
Returns
number of unique solutions
Definition at line 68 of file mathSupport.cpp.
References Mantid::Geometry::d, and solveQuadratic().
solveCubic() [2/2]
template<typename InputIter > MANTID_GEOMETRY_DLL int Mantid::solveCubic (InputIter , std::complex< double > & , std::complex< double > & , std::complex< double > &)
Solve a Cubic equation.
solveQuadratic() [1/2]
template<typename InputIter > int Mantid::solveQuadratic (const InputIter Coef, std::pair< std::complex< double >, std::complex< double > > & OutAns)
Solves Complex Quadratic.
Solve a Quadratic equation.
Parameters
Coef :: iterator over all the coefients in the order
\[ Ax^2+Bx+C \]
.
OutAns :: complex roots of the equation
Returns
number of unique solutions
Definition at line 23 of file mathSupport.cpp.
Referenced by Mantid::Geometry::Line::intersect(), Mantid::Geometry::Line::intersect(), Mantid::Geometry::Line::intersect(), and solveCubic().
solveQuadratic() [2/2]
template<typename InputIter > MANTID_GEOMETRY_DLL int Mantid::solveQuadratic (const InputIter Coef, std::pair< std::complex< double >, std::complex< double > > & OutAns)
Solve a Quadratic equation.
Solve a Quadratic equation.
Parameters
Coef :: iterator over all the coefients in the order
\[ Ax^2+Bx+C \]
.
OutAns :: complex roots of the equation
Returns
number of unique solutions
Definition at line 23 of file mathSupport.cpp.
Referenced by Mantid::Geometry::Line::intersect(), Mantid::Geometry::Line::intersect(), Mantid::Geometry::Line::intersect(), and solveCubic().
welcomeMessage()
std::string Mantid::welcomeMessage ()
Returns the welcome message for Mantid.
Get the welcome message for Mantid.
Returns
A string containing the welcome message for Mantid.
Definition at line 77 of file ConfigService.cpp.
References Mantid::Kernel::MantidVersion::doi(), Mantid::Kernel::MantidVersion::paperCitation(), and Mantid::Kernel::MantidVersion::version().
Referenced by Mantid::API::FrameworkManagerImpl::FrameworkManagerImpl().
Variable Documentation
validMarkerStyles
const std::vector<std::string> Mantid::validMarkerStyles
Definition at line 36 of file MatrixWorkspace.h.
Referenced by Mantid::API::MatrixWorkspace::setMarkerStyle().
validPlotTypes
const std::vector<std::string> Mantid::validPlotTypes {"plot", "marker", "histogram", "errorbar_x", "errorbar_y", "errorbar_xy"}
Definition at line 35 of file MatrixWorkspace.h.
Referenced by Mantid::API::MatrixWorkspace::setPlotType().