Mantid: Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm > Class Template Reference
Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm > Class Template Reference
Provides a layer class for boost::python to allow C++ virtual functions to be overridden in a Python object that is derived an Algorithm.
#include <AlgorithmAdapter.h>
Public Member Functions
AlgorithmAdapter ()=delete
Disable default constructor - The PyObject must be supplied to construct the object.
AlgorithmAdapter (const AlgorithmAdapter &)=delete
Disable copy operator.
AlgorithmAdapter (PyObject *self)
A constructor that looks like a Python init method.
AlgorithmAdapter & operator= (const AlgorithmAdapter &)=delete
Disable assignment operator.
void setWikiSummary (const std::string &summary)
Set the summary text.
Algorithm virtual methods
const std::string name () const override
Returns the name of the algorithm.
int version () const override
Returns a version of the algorithm.
const std::string summary () const override
Returns the summary for the algorithm.
const std::string category () const override
Returns a category of the algorithm.
const std::vector< std::string > seeAlso () const override
Returns seeAlso related algorithms.
const std::string alias () const override
Allow the method returning the algorithm aliases to be overridden.
const std::string aliasDeprecated () const override
Returns optional documentation URL of the algorithm.
const std::string helpURL () const override
Optional documentation URL of the algorithm, empty string if not overridden.
bool isRunning () const override
Allow the isRunning method to be overridden.
void cancel () override
Allow the cancel method to be overridden.
bool checkGroups () override
A return of false will allow processing workspace groups as a whole.
std::map< std::string, std::string > validateInputs () override
Returns the validateInputs result of the algorithm.
Private Types
using SuperClass = BaseAlgorithm
Property declarations
The first function matches the base-classes signature so a different name is used consistently to avoid accidentally calling the wrong function internally From Python they will still be called declareProperty
PyObject * m_self
The Python portion of the object.
PyObject * m_isRunningObj
A pointer to an overridden isRunning method.
std::string m_wikiSummary
Here for deprecated setWikiSummary method.
static void declarePyAlgProperty (boost::python::object &self, Kernel::Property *prop, const std::string &doc="")
Declare a preconstructed property.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator=boost::python::object(), const std::string &doc="", const int direction=Kernel::Direction::Input)
Declare a property using the type of the defaultValue with a validator and doc string.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const std::string &doc, const int direction=Kernel::Direction::Input)
Declare a property with a documentation string.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const int direction)
Declare a property using the type of the defaultValue.
static void declareOrReplacePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator=boost::python::object(), const std::string &doc="", const int direction=Kernel::Direction::Input)
Declare or replace a property using the type of the defaultValue with a validator and doc string.
PyObject * getSelf () const
Returns the PyObject that owns this wrapper, i.e.
void init () override
Private init for this algorithm.
void exec () override
Private exec for this algorithm.
Detailed Description
template<typename BaseAlgorithm>
class Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >
Provides a layer class for boost::python to allow C++ virtual functions to be overridden in a Python object that is derived an Algorithm.
The templated-base class provides a mechanism to reuse the same adapter class for other classes that inherit from a different Algorithm sub class
Definition at line 27 of file AlgorithmAdapter.h.
Member Typedef Documentation
SuperClass
template<typename BaseAlgorithm > using Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::SuperClass = BaseAlgorithm private
Definition at line 28 of file AlgorithmAdapter.h.
Constructor & Destructor Documentation
AlgorithmAdapter() [1/3]
template<typename BaseAlgorithm > Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::AlgorithmAdapter (PyObject * self)
A constructor that looks like a Python init method.
Construct the "wrapper" and stores the reference to the PyObject.
Parameters
self A reference to the calling Python object
Definition at line 35 of file AlgorithmAdapter.cpp.
References Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::m_isRunningObj, and Mantid::PythonInterface::typeHasAttribute().
AlgorithmAdapter() [2/3]
template<typename BaseAlgorithm > Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::AlgorithmAdapter () delete
Disable default constructor - The PyObject must be supplied to construct the object.
AlgorithmAdapter() [3/3]
template<typename BaseAlgorithm > Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::AlgorithmAdapter (const AlgorithmAdapter< BaseAlgorithm > &) delete
Disable copy operator.
Member Function Documentation
alias()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::alias () const override
Allow the method returning the algorithm aliases to be overridden.
Returns the aliases of the algorithm.
If not overridden returns the base algorithm implementation
Definition at line 113 of file AlgorithmAdapter.cpp.
aliasDeprecated()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::aliasDeprecated () const override
Returns optional documentation URL of the algorithm.
Returns the expiration date (in ISO8601 format) of algorithm aliases.
Allow the method returning the expiration date (in ISO8601 format) for the algorithm aliases to be overridden
If not overridden, returns the base algorithm implementation
Definition at line 125 of file AlgorithmAdapter.cpp.
cancel()
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::cancel () override
Allow the cancel method to be overridden.
Definition at line 177 of file AlgorithmAdapter.cpp.
category()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::category () const override
Returns a category of the algorithm.
Returns the category of the algorithm.
If not overridden it return defaultCategory()
Definition at line 80 of file AlgorithmAdapter.cpp.
checkGroups()
template<typename BaseAlgorithm > bool Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::checkGroups () override
A return of false will allow processing workspace groups as a whole.
Returns checkGroups.
If false, workspace groups will be treated as a whole If true, the algorithm will act on each component of the workspace group individually
Definition at line 68 of file AlgorithmAdapter.cpp.
declareOrReplacePyAlgProperty()
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::declareOrReplacePyAlgProperty (boost::python::object & self, const std::string & name, const boost::python::object & defaultValue, const boost::python::object & validator = boost::python::object(), const std::string & doc = "", const int direction = Kernel::Direction::Input) static
Declare or replace a property using the type of the defaultValue with a validator and doc string.
Declare or replace a property using the type of the defaultValue, a documentation string and validator.
Parameters
self A reference to the calling Python object
name :: The name of the new property
defaultValue :: A default value for the property. The type is mapped to a C++ type
validator :: A validator object
doc :: The documentation string
direction :: The direction of the property
Definition at line 323 of file AlgorithmAdapter.cpp.
References Mantid::PythonInterface::Registry::PropertyWithValueFactory::create(), and name.
declarePyAlgProperty() [1/4]
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::declarePyAlgProperty (boost::python::object & self, const std::string & name, const boost::python::object & defaultValue, const boost::python::object & validator = boost::python::object(), const std::string & doc = "", const int direction = Kernel::Direction::Input) static
Declare a property using the type of the defaultValue with a validator and doc string.
Declare a property using the type of the defaultValue, a documentation string and validator.
Parameters
self A reference to the calling Python object
name :: The name of the new property
defaultValue :: A default value for the property. The type is mapped to a C++ type
validator :: A validator object
doc :: The documentation string
direction :: The direction of the property
Definition at line 265 of file AlgorithmAdapter.cpp.
References Mantid::PythonInterface::Registry::PropertyWithValueFactory::create(), and name.
declarePyAlgProperty() [2/4]
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::declarePyAlgProperty (boost::python::object & self, const std::string & name, const boost::python::object & defaultValue, const int direction) static
Declare a property using the type of the defaultValue.
Parameters
self A reference to the calling Python object
name :: The name of the new property
defaultValue :: A default value for the property. The type is mapped to a C++ type
direction :: The direction of the property
Definition at line 304 of file AlgorithmAdapter.cpp.
References name.
declarePyAlgProperty() [3/4]
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::declarePyAlgProperty (boost::python::object & self, const std::string & name, const boost::python::object & defaultValue, const std::string & doc, const int direction = Kernel::Direction::Input) static
Declare a property with a documentation string.
Declare a property using the type of the defaultValue and a documentation string.
Parameters
self A reference to the calling Python object
name :: The name of the new property
defaultValue :: A default value for the property. The type is mapped to a C++ type
doc :: The documentation string
direction :: The direction of the property
Definition at line 286 of file AlgorithmAdapter.cpp.
References Mantid::PythonInterface::Registry::PropertyWithValueFactory::create(), and name.
declarePyAlgProperty() [4/4]
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::declarePyAlgProperty (boost::python::object & self, Kernel::Property * prop, const std::string & doc = "") static
Declare a preconstructed property.
Declare a specialized property
Parameters
self A reference to the calling Python object
prop :: A pointer to a property
doc :: An optional doc string
Definition at line 243 of file AlgorithmAdapter.cpp.
References Mantid::Kernel::Property::clone().
exec()
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::exec () override private
Private exec for this algorithm.
Expected to be overridden in the subclass by a function named PyExec
Definition at line 350 of file AlgorithmAdapter.cpp.
getSelf()
template<typename BaseAlgorithm > PyObject * Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::getSelf () const inline protected
Returns the PyObject that owns this wrapper, i.e.
self
Returns
A pointer to self
Definition at line 118 of file AlgorithmAdapter.h.
References Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::m_self.
helpURL()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::helpURL () const override
Optional documentation URL of the algorithm, empty string if not overridden.
Definition at line 148 of file AlgorithmAdapter.cpp.
init()
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::init () override private
Private init for this algorithm.
Expected to be overridden in the subclass by a function named PyInit
Definition at line 342 of file AlgorithmAdapter.cpp.
isRunning()
template<typename BaseAlgorithm > bool Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::isRunning () const override
Allow the isRunning method to be overridden.
Returns
True if the algorithm is considered to be running
Definition at line 159 of file AlgorithmAdapter.cpp.
References GNU_DIAG_OFF, and GNU_DIAG_ON.
name()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::name () const override
Returns the name of the algorithm.
Returns the name of the algorithm
This cannot be overridden in Python.
Definition at line 47 of file AlgorithmAdapter.cpp.
operator=()
template<typename BaseAlgorithm > AlgorithmAdapter & Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::operator= (const AlgorithmAdapter< BaseAlgorithm > &) delete
Disable assignment operator.
seeAlso()
template<typename BaseAlgorithm > const std::vector< std::string > Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::seeAlso () const override
Returns seeAlso related algorithms.
If not overridden it returns an empty vector of strings
Definition at line 99 of file AlgorithmAdapter.cpp.
setWikiSummary()
template<typename BaseAlgorithm > void Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::setWikiSummary (const std::string & summary)
Set the summary text.
Parameters
summary Wiki text
Definition at line 222 of file AlgorithmAdapter.cpp.
summary()
template<typename BaseAlgorithm > const std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::summary () const override
Returns the summary for the algorithm.
Returns the summary of the algorithm.
If not overridden it returns defaultSummary
Definition at line 137 of file AlgorithmAdapter.cpp.
validateInputs()
template<typename BaseAlgorithm > std::map< std::string, std::string > Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::validateInputs () override
Returns the validateInputs result of the algorithm.
Perform validation of ALL the input properties of the algorithm.
This is to be overridden by specific algorithms. It will be called in dialogs after parsing all inputs and setting the properties, but BEFORE executing.
Returns
a map where: Key = string name of the property; Value = string describing the problem with the property.
Definition at line 188 of file AlgorithmAdapter.cpp.
References value.
version()
template<typename BaseAlgorithm > int Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::version () const override
Returns a version of the algorithm.
Returns the version of the algorithm.
If not overridden it returns 1
Definition at line 55 of file AlgorithmAdapter.cpp.
Member Data Documentation
m_isRunningObj
template<typename BaseAlgorithm > PyObject* Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::m_isRunningObj private
A pointer to an overridden isRunning method.
Definition at line 132 of file AlgorithmAdapter.h.
Referenced by Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::AlgorithmAdapter().
m_self
template<typename BaseAlgorithm > PyObject* Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::m_self private
The Python portion of the object.
Definition at line 130 of file AlgorithmAdapter.h.
Referenced by Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::getSelf().
m_wikiSummary
template<typename BaseAlgorithm > std::string Mantid::PythonInterface::AlgorithmAdapter< BaseAlgorithm >::m_wikiSummary private
Here for deprecated setWikiSummary method.
Definition at line 135 of file AlgorithmAdapter.h.
The documentation for this class was generated from the following files:
Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/PythonAlgorithm/AlgorithmAdapter.h
Framework/PythonInterface/mantid/api/src/PythonAlgorithm/AlgorithmAdapter.cpp