Mantid: MantidQt::MantidWidgets::MantidWSIndexWidget Class Reference
MantidQt::MantidWidgets::MantidWSIndexWidget Class Reference
#include <MantidWSIndexDialog.h>
Classes
class QLineEditWithErrorMark
Auxiliary class to wrap the QLineEdit allowing warning to the user for invalid inputs.
struct UserInput
struct UserInputAdvanced
Plain old data structures to hold all user-selected input.
Public Member Functions
QMultiMap< QString, std::set< int > > getPlots () const
Returns the QMultiMap that contains all the workspaces that are to be plotted, mapped to the set of workspace indices.
UserInput getSelections ()
Returns a structure holding all of the selected options.
bool is1DPlotSelected () const
Returns whether the simple 1D plot option has been selected.
bool isContourPlotSelected () const
Returns whether contour plot is selected.
bool isErrorBarsSelected () const
Returns whether the error bars option has been selected.
bool isSurfacePlotSelected () const
Returns whether surface plot is selected.
bool isTiledPlotSelected () const
Returns whether the tiled plot option has been selected.
bool isWaterfallPlotSelected () const
Returns whether the waterfall option has been selected.
MantidWSIndexWidget (QWidget *parent, const Qt::WindowFlags &flags, const QList< QString > &wsNames, const bool showWaterfallOption=false, const bool showTiledOption=false, const bool isAdvanced=false)
Constructor - same parameters as one of the parent constructors, along with a list of the names of workspaces to be plotted.
bool plotAllRequested ()
Called by dialog when plot all requested.
bool plotRequested ()
Called by dialog when plot requested.
bool validatePlotOptions ()
Validate plot options when either plot or plot all is requested.
Static Public Attributes
static const QString CONTOUR_PLOT = "Contour Plot"
static const QString CUSTOM = "Custom"
The string "Custom".
static const QString SIMPLE_PLOT = "1D Plot"
Strings for plot types.
static const QString SURFACE_PLOT = "Surface Plot"
static const QString WATERFALL_PLOT = "Waterfall Plot"
static const QString WORKSPACE_INDEX = "Workspace index"
static const QString WORKSPACE_NAME = "Workspace name"
The string "Workspace index".
Private Slots
void editedSpectraField ()
Called when the spectraField has been edited.
void editedWsField ()
Called when the wsField has been edited.
void onLogSelected (const QString &logName)
Called when the log selection is changed.
void onPlotOptionChanged (const QString &logName)
Called when the plot option has changed.
Private Member Functions
void checkForSpectraAxes ()
Check to see if all workspaces have a spectrum axis.
void generateSpectraNumIntervals ()
Generates an IntervalList which defines which spectra IDs the user can ask to plot.
void generateWsIndexIntervals ()
Generates an IntervalList which defines which workspace indices the user can ask to plot.
const QString getAxisName () const
Gets the axis name.
const std::set< double > getCustomLogValues () const
Get the set of custom log values.
const QString getLogName () const
Gets the log name.
int getPlotIndex () const
Get the plot index.
Mantid::API::MatrixWorkspace_const_sptr getWorkspace (const QString &workspaceName) const
Get a handle a workspace by name.
void init ()
Initializes the layout of the dialog.
void initLogs ()
Initializes the layout of the log options.
void initOptionsBoxes ()
Initialize the layout of the options check boxes.
void initSpectraBox ()
Initializes the layout of the spectra ID section of the dialog.
void initWorkspaceBox ()
Initializes the layout of the workspace index section of the dialog.
bool isSuitableForContourOrSurfacePlot () const
Check if workspaces are suitable for contour or surface plot.
bool isSuitableForLogValues (const QString &plotOption) const
Check if workspaces are suitable for use of log values.
void populateLogComboBox ()
Populate the log combo box.
void showPlotOptionsError (const QString &message)
Provide warning if there are plot errors.
bool usingSpectraNumbers () const
Whether or not there are any common spectra IDs between workspaces.
Private Attributes
bool m_advanced
Is the plotting advanced?
QLabel * m_axisLabel
QLineEditWithErrorMark * m_axisNameEdit
QLabel * m_customLogLabel
QVBoxLayout * m_logBox
QLabel * m_logLabel
QGroupBox * m_logOptionsGroup
QComboBox * m_logSelector
QLineEditWithErrorMark * m_logValues
QVBoxLayout * m_optionsBox
QLabel * m_orMessage
QVBoxLayout * m_outer
QLabel * m_plotOptionLabel
QComboBox * m_plotOptions
QCheckBox * m_showErrorBars
bool m_spectra
Do we allow the user to ask for a range of spectra IDs or not?
QVBoxLayout * m_spectraBox
QLineEditWithErrorMark * m_spectraField
QLabel * m_spectraMessage
IntervalList m_spectraNumChoice
IntervalList m_spectraNumIntervals
bool m_tiled
Do we allow the display of the tiled option.
bool m_usingSprectraNumChoice = false
bool m_usingWsIndexChoice = false
Flags to indicate which one of the two interval lists above is chosen by user.
bool m_waterfall
Do we allow the display of the waterfall option.
QVBoxLayout * m_wsBox
QLineEditWithErrorMark * m_wsField
IntervalList m_wsIndexChoice
IntervalLists for the range of indices/numbers CHOSEN by the user.
IntervalList m_wsIndexIntervals
IntervalLists for the range of indices/numbers AVAILABLE to the user.
QLabel * m_wsMessage
Pointers to the obligatory Qt objects:
QList< QString > m_wsNames
A list of names of workspaces which are to be plotted.
Detailed Description
Definition at line 200 of file MantidWSIndexDialog.h.
Constructor & Destructor Documentation
MantidWSIndexWidget()
MantidQt::MantidWidgets::MantidWSIndexWidget::MantidWSIndexWidget (QWidget * parent, const Qt::WindowFlags & flags, const QList< QString > & wsNames, const bool showWaterfallOption = false, const bool showTiledOption = false, const bool isAdvanced = false)
Constructor - same parameters as one of the parent constructors, along with a list of the names of workspaces to be plotted.
Construct a widget of this type.
Parameters
parent :: The owning dialog
flags :: Window flags that are passed the the QWidget constructor
wsNames :: the names of the workspaces to be plotted
showWaterfallOption :: true if waterfall plot enabled
showTiledOption :: true if tiled plot enabled
isAdvanced :: true if advanced plotting has been selected
Definition at line 54 of file MantidWSIndexDialog.cpp.
References checkForSpectraAxes(), generateSpectraNumIntervals(), generateWsIndexIntervals(), init(), and m_spectra.
Member Function Documentation
checkForSpectraAxes()
void MantidQt::MantidWidgets::MantidWSIndexWidget::checkForSpectraAxes () private
Check to see if all workspaces have a spectrum axis.
Check to see if all workspaces have a spectrum axis.
If even one does not have a spectra axis, then we wont ask the user to enter spectra Numberss - only workspace indices.
Definition at line 678 of file MantidWSIndexDialog.cpp.
References hasSpectra, Mantid::Kernel::SingletonHolder< T >::Instance(), m_spectra, and m_wsNames.
Referenced by MantidWSIndexWidget().
editedSpectraField
void MantidQt::MantidWidgets::MantidWSIndexWidget::editedSpectraField () private slot
Called when the spectraField has been edited.
Called when user edits spectra field.
Definition at line 276 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_wsField, and MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::setError().
Referenced by initSpectraBox().
editedWsField
void MantidQt::MantidWidgets::MantidWSIndexWidget::editedWsField () private slot
Called when the wsField has been edited.
Called when user edits workspace field.
Definition at line 268 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_spectraField, and MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::setError().
Referenced by initWorkspaceBox().
generateSpectraNumIntervals()
void MantidQt::MantidWidgets::MantidWSIndexWidget::generateSpectraNumIntervals () private
Generates an IntervalList which defines which spectra IDs the user can ask to plot.
Get available intervals for spectra Numbers.
Definition at line 730 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::addInterval(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::IntervalList::intersect(), m_spectraNumIntervals, m_wsNames, and MantidQt::MantidWidgets::IntervalList::setIntervalList().
Referenced by MantidWSIndexWidget().
generateWsIndexIntervals()
void MantidQt::MantidWidgets::MantidWSIndexWidget::generateWsIndexIntervals () private
Generates an IntervalList which defines which workspace indices the user can ask to plot.
Get the available interval for each of the workspaces, and then present the user with interval which is the INTERSECTION of each of those intervals.
Definition at line 704 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::addInterval(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::IntervalList::intersect(), m_wsIndexIntervals, m_wsNames, and MantidQt::MantidWidgets::IntervalList::setIntervalList().
Referenced by MantidWSIndexWidget().
getAxisName()
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::getAxisName () const private
Gets the axis name.
Gets the name that the user gave for the Y axis of the surface plot.
Returns
Name input by user for axis
Definition at line 176 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), and m_axisNameEdit.
Referenced by getSelections().
getCustomLogValues()
const std::set< double > MantidQt::MantidWidgets::MantidWSIndexWidget::getCustomLogValues () const private
Get the set of custom log values.
If "Custom" is selected as log, returns the list of values the user has input into the edit box, otherwise returns an empty set.
Note that the set is ordered by definition, and values are only added if they are successfully converted to a double.
Returns
Set of numerical log values
Definition at line 157 of file MantidWSIndexDialog.cpp.
References CUSTOM, MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_logSelector, m_logValues, and value.
Referenced by getSelections().
getLogName()
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::getLogName () const private
Gets the log name.
Gets the log that user selected to plot against.
Returns
Name of log, or "Workspace index"
Definition at line 182 of file MantidWSIndexDialog.cpp.
References m_logSelector.
Referenced by getSelections().
getPlotIndex()
int MantidQt::MantidWidgets::MantidWSIndexWidget::getPlotIndex () const private
Get the plot index.
Returns the workspace index to be plotted.
Returns
Workspace index to be plotted
Definition at line 121 of file MantidWSIndexDialog.cpp.
References getPlots().
Referenced by getSelections().
getPlots()
QMultiMap< QString, std::set< int > > MantidQt::MantidWidgets::MantidWSIndexWidget::getPlots () const
Returns the QMultiMap that contains all the workspaces that are to be plotted, mapped to the set of workspace indices.
Returns the user-selected plots.
Returns
Plots selected by user
Definition at line 188 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::getIntSet(), MantidQt::MantidWidgets::IntervalList::getList(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_spectraNumChoice, m_wsIndexChoice, and m_wsNames.
Referenced by getPlotIndex(), MantidQt::MantidWidgets::MantidWSIndexDialog::getPlots(), and getSelections().
getSelections()
MantidWSIndexWidget::UserInput MantidQt::MantidWidgets::MantidWSIndexWidget::getSelections ()
Returns a structure holding all of the selected options.
Returns the user-selected options.
Returns
Struct containing user options
Definition at line 73 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::accepted, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::advanced, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::axisName, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::contour, CUSTOM, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::customLogValues, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::errors, getAxisName(), getCustomLogValues(), getLogName(), getPlotIndex(), getPlots(), is1DPlotSelected(), MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::isAdvanced, isContourPlotSelected(), isErrorBarsSelected(), isSurfacePlotSelected(), isTiledPlotSelected(), isWaterfallPlotSelected(), MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::logName, m_advanced, m_wsNames, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::plotIndex, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::plots, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::simple, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::surface, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::tiled, MantidQt::MantidWidgets::MantidWSIndexWidget::UserInput::waterfall, WORKSPACE_INDEX, WORKSPACE_NAME, and MantidQt::MantidWidgets::MantidWSIndexWidget::UserInputAdvanced::workspaceNames.
Referenced by MantidQt::MantidWidgets::MantidWSIndexDialog::getSelections().
getWorkspace()
Mantid::API::MatrixWorkspace_const_sptr MantidQt::MantidWidgets::MantidWSIndexWidget::getWorkspace (const QString & workspaceName) const private
Get a handle a workspace by name.
Definition at line 659 of file MantidWSIndexDialog.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by populateLogComboBox().
init()
void MantidQt::MantidWidgets::MantidWSIndexWidget::init () private
Initializes the layout of the dialog.
Set up widget UI.
Definition at line 419 of file MantidWSIndexDialog.cpp.
References initLogs(), initOptionsBoxes(), initSpectraBox(), initWorkspaceBox(), m_advanced, and m_outer.
Referenced by MantidWSIndexWidget().
initLogs()
void MantidQt::MantidWidgets::MantidWSIndexWidget::initLogs () private
Initializes the layout of the log options.
Definition at line 514 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_axisLabel, m_axisNameEdit, m_customLogLabel, m_logBox, m_logLabel, m_logOptionsGroup, m_logSelector, m_logValues, m_outer, onLogSelected(), and populateLogComboBox().
Referenced by init().
initOptionsBoxes()
void MantidQt::MantidWidgets::MantidWSIndexWidget::initOptionsBoxes () private
Initialize the layout of the options check boxes.
Set up Options boxes UI.
Definition at line 481 of file MantidWSIndexDialog.cpp.
References CONTOUR_PLOT, isSuitableForContourOrSurfacePlot(), m_advanced, m_optionsBox, m_outer, m_plotOptionLabel, m_plotOptions, m_showErrorBars, m_tiled, m_waterfall, onPlotOptionChanged(), SIMPLE_PLOT, SURFACE_PLOT, and WATERFALL_PLOT.
Referenced by init().
initSpectraBox()
void MantidQt::MantidWidgets::MantidWSIndexWidget::initSpectraBox () private
Initializes the layout of the spectra ID section of the dialog.
Set up Spectra box UI.
Definition at line 455 of file MantidWSIndexDialog.cpp.
References editedSpectraField(), MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_orMessage, m_outer, m_spectraBox, m_spectraField, m_spectraMessage, m_spectraNumIntervals, spectraNumbers, MantidQt::MantidWidgets::IntervalList::toQString(), and usingSpectraNumbers().
Referenced by init().
initWorkspaceBox()
void MantidQt::MantidWidgets::MantidWSIndexWidget::initWorkspaceBox () private
Initializes the layout of the workspace index section of the dialog.
Set up Workspace box UI.
Definition at line 433 of file MantidWSIndexDialog.cpp.
References editedWsField(), MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_outer, m_wsBox, m_wsField, m_wsIndexIntervals, m_wsMessage, and MantidQt::MantidWidgets::IntervalList::toQString().
Referenced by init().
is1DPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::is1DPlotSelected () const
Returns whether the simple 1D plot option has been selected.
Whether the user selected "1D plot".
Returns
True if 1D plot selected
Definition at line 233 of file MantidWSIndexDialog.cpp.
References m_plotOptions, and SIMPLE_PLOT.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::is1DPlotSelected().
isContourPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isContourPlotSelected () const
Returns whether contour plot is selected.
Whether the user selected contour plot.
Returns
True if surfarce plot selected
Definition at line 257 of file MantidWSIndexDialog.cpp.
References CONTOUR_PLOT, and m_plotOptions.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::isContourPlotSelected().
isErrorBarsSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isErrorBarsSelected () const
Returns whether the error bars option has been selected.
Whether the user has selected plot with error bars.
Returns
True if error bars are selected
Definition at line 263 of file MantidWSIndexDialog.cpp.
References m_showErrorBars.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::isErrorBarsSelected().
isSuitableForContourOrSurfacePlot()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isSuitableForContourOrSurfacePlot () const private
Check if workspaces are suitable for contour or surface plot.
Definition at line 665 of file MantidWSIndexDialog.cpp.
References m_wsNames.
Referenced by initOptionsBoxes().
isSuitableForLogValues()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isSuitableForLogValues (const QString & plotOption) const private
Check if workspaces are suitable for use of log values.
Definition at line 668 of file MantidWSIndexDialog.cpp.
References CONTOUR_PLOT, SIMPLE_PLOT, SURFACE_PLOT, and WATERFALL_PLOT.
Referenced by onPlotOptionChanged().
isSurfacePlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isSurfacePlotSelected () const
Returns whether surface plot is selected.
Whether the user selected surface plot.
Returns
True if surfarce plot selected
Definition at line 251 of file MantidWSIndexDialog.cpp.
References m_plotOptions, and SURFACE_PLOT.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::isSurfacePlotSelected().
isTiledPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isTiledPlotSelected () const
Returns whether the tiled plot option has been selected.
Whether the user selected "tiled".
Returns
True if tiled plot selected
Definition at line 245 of file MantidWSIndexDialog.cpp.
References m_plotOptions.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::isTiledPlotSelected().
isWaterfallPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::isWaterfallPlotSelected () const
Returns whether the waterfall option has been selected.
Whether the user selected "waterfall".
Returns
True if waterfall plot selected
Definition at line 239 of file MantidWSIndexDialog.cpp.
References m_plotOptions, and WATERFALL_PLOT.
Referenced by getSelections(), and MantidQt::MantidWidgets::MantidWSIndexDialog::isWaterfallPlotSelected().
onLogSelected
void MantidQt::MantidWidgets::MantidWSIndexWidget::onLogSelected (const QString & logName) private slot
Called when the log selection is changed.
Called when log selection changed If "Custom" selected, enable the custom log input box.
Otherwise, it is read-only. Also put the log name into the axis name box as a default choice.
Parameters
logName :: [input] Text selected in combo box
Definition at line 554 of file MantidWSIndexDialog.cpp.
References CUSTOM, MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_axisNameEdit, and m_logValues.
Referenced by initLogs().
onPlotOptionChanged
void MantidQt::MantidWidgets::MantidWSIndexWidget::onPlotOptionChanged (const QString & plotOption) private slot
Called when the plot option has changed.
Called when plot option is changed.
Parameters
plotOption :: [input] New plot option
Definition at line 564 of file MantidWSIndexDialog.cpp.
References CONTOUR_PLOT, CUSTOM, isSuitableForLogValues(), MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_advanced, m_axisNameEdit, m_logSelector, m_logValues, m_plotOptions, m_showErrorBars, SURFACE_PLOT, WORKSPACE_INDEX, and WORKSPACE_NAME.
Referenced by initOptionsBoxes().
plotAllRequested()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::plotAllRequested ()
Called by dialog when plot all requested.
Called when dialog requests to plot all.
Definition at line 325 of file MantidWSIndexDialog.cpp.
References m_usingSprectraNumChoice, m_usingWsIndexChoice, m_wsIndexChoice, m_wsIndexIntervals, and validatePlotOptions().
Referenced by MantidQt::MantidWidgets::MantidWSIndexDialog::plotAll().
plotRequested()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::plotRequested ()
Called by dialog when plot requested.
Called when dialog requests a plot.
Returns
True to accept, false to raise error
Definition at line 285 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::addIntervals(), MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_spectraField, m_spectraNumChoice, m_usingSprectraNumChoice, m_usingWsIndexChoice, m_wsField, m_wsIndexChoice, MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::setError(), and validatePlotOptions().
Referenced by MantidQt::MantidWidgets::MantidWSIndexDialog::plot().
populateLogComboBox()
void MantidQt::MantidWidgets::MantidWSIndexWidget::populateLogComboBox () private
Populate the log combo box.
Populate the log combo box with all log names that have single numeric value per workspace (and occur in every workspace)
Definition at line 602 of file MantidWSIndexDialog.cpp.
References CUSTOM, getWorkspace(), m_logSelector, m_wsNames, Mantid::Kernel::Math::TimeAveragedMean, value, and WORKSPACE_NAME.
Referenced by initLogs().
showPlotOptionsError()
void MantidQt::MantidWidgets::MantidWSIndexWidget::showPlotOptionsError (const QString & message) private
Provide warning if there are plot errors.
Displays a message box with the supplied error string.
Parameters
message :: [input] Error message to display
Definition at line 141 of file MantidWSIndexDialog.cpp.
usingSpectraNumbers()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::usingSpectraNumbers () const private
Whether or not there are any common spectra IDs between workspaces.
Whether widget is using spectra IDs or workspace indices.
Returns
True if using spectra IDs
Definition at line 758 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::getList(), m_spectra, and m_spectraNumIntervals.
Referenced by initSpectraBox().
validatePlotOptions()
bool MantidQt::MantidWidgets::MantidWSIndexWidget::validatePlotOptions ()
Validate plot options when either plot or plot all is requested.
Validate plot options when a plot is requested set appropriate error if not valid.
Definition at line 336 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::IntervalList::clear(), CONTOUR_PLOT, CUSTOM, MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit(), m_advanced, m_logSelector, m_logValues, m_plotOptions, m_spectraNumChoice, m_usingSprectraNumChoice, m_usingWsIndexChoice, m_wsIndexChoice, m_wsNames, MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::setError(), SURFACE_PLOT, MantidQt::MantidWidgets::IntervalList::totalIntervalLength(), and value.
Referenced by plotAllRequested(), and plotRequested().
Member Data Documentation
CONTOUR_PLOT
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::CONTOUR_PLOT = "Contour Plot" static
Definition at line 261 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), isContourPlotSelected(), isSuitableForLogValues(), onPlotOptionChanged(), and validatePlotOptions().
CUSTOM
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::CUSTOM = "Custom" static
The string "Custom".
Definition at line 256 of file MantidWSIndexDialog.h.
Referenced by getCustomLogValues(), getSelections(), onLogSelected(), onPlotOptionChanged(), populateLogComboBox(), and validatePlotOptions().
m_advanced
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_advanced private
Is the plotting advanced?
Definition at line 358 of file MantidWSIndexDialog.h.
Referenced by getSelections(), init(), initOptionsBoxes(), onPlotOptionChanged(), and validatePlotOptions().
m_axisLabel
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_axisLabel private
Definition at line 362 of file MantidWSIndexDialog.h.
Referenced by initLogs().
m_axisNameEdit
QLineEditWithErrorMark* MantidQt::MantidWidgets::MantidWSIndexWidget::m_axisNameEdit private
Definition at line 368 of file MantidWSIndexDialog.h.
Referenced by getAxisName(), initLogs(), onLogSelected(), and onPlotOptionChanged().
m_customLogLabel
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_customLogLabel private
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initLogs().
m_logBox
QVBoxLayout * MantidQt::MantidWidgets::MantidWSIndexWidget::m_logBox private
Definition at line 365 of file MantidWSIndexDialog.h.
Referenced by initLogs().
m_logLabel
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_logLabel private
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initLogs().
m_logOptionsGroup
QGroupBox* MantidQt::MantidWidgets::MantidWSIndexWidget::m_logOptionsGroup private
Definition at line 364 of file MantidWSIndexDialog.h.
Referenced by initLogs().
m_logSelector
QComboBox * MantidQt::MantidWidgets::MantidWSIndexWidget::m_logSelector private
Definition at line 366 of file MantidWSIndexDialog.h.
Referenced by getCustomLogValues(), getLogName(), initLogs(), onPlotOptionChanged(), populateLogComboBox(), and validatePlotOptions().
m_logValues
QLineEditWithErrorMark * MantidQt::MantidWidgets::MantidWSIndexWidget::m_logValues private
Definition at line 363 of file MantidWSIndexDialog.h.
Referenced by getCustomLogValues(), initLogs(), onLogSelected(), onPlotOptionChanged(), and validatePlotOptions().
m_optionsBox
QVBoxLayout * MantidQt::MantidWidgets::MantidWSIndexWidget::m_optionsBox private
Definition at line 365 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes().
m_orMessage
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_orMessage private
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initSpectraBox().
m_outer
QVBoxLayout* MantidQt::MantidWidgets::MantidWSIndexWidget::m_outer private
Definition at line 365 of file MantidWSIndexDialog.h.
Referenced by init(), initLogs(), initOptionsBoxes(), initSpectraBox(), and initWorkspaceBox().
m_plotOptionLabel
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_plotOptionLabel private
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes().
m_plotOptions
QComboBox* MantidQt::MantidWidgets::MantidWSIndexWidget::m_plotOptions private
Definition at line 366 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), is1DPlotSelected(), isContourPlotSelected(), isSurfacePlotSelected(), isTiledPlotSelected(), isWaterfallPlotSelected(), onPlotOptionChanged(), and validatePlotOptions().
m_showErrorBars
QCheckBox* MantidQt::MantidWidgets::MantidWSIndexWidget::m_showErrorBars private
Definition at line 367 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), isErrorBarsSelected(), and onPlotOptionChanged().
m_spectra
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectra private
Do we allow the user to ask for a range of spectra IDs or not?
Definition at line 349 of file MantidWSIndexDialog.h.
Referenced by checkForSpectraAxes(), MantidWSIndexWidget(), and usingSpectraNumbers().
m_spectraBox
QVBoxLayout * MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectraBox private
Definition at line 365 of file MantidWSIndexDialog.h.
Referenced by initSpectraBox().
m_spectraField
QLineEditWithErrorMark * MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectraField private
Definition at line 363 of file MantidWSIndexDialog.h.
Referenced by editedWsField(), initSpectraBox(), and plotRequested().
m_spectraMessage
QLabel * MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectraMessage private
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initSpectraBox().
m_spectraNumChoice
IntervalList MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectraNumChoice private
Definition at line 375 of file MantidWSIndexDialog.h.
Referenced by getPlots(), plotRequested(), and validatePlotOptions().
m_spectraNumIntervals
IntervalList MantidQt::MantidWidgets::MantidWSIndexWidget::m_spectraNumIntervals private
Definition at line 373 of file MantidWSIndexDialog.h.
Referenced by generateSpectraNumIntervals(), initSpectraBox(), and usingSpectraNumbers().
m_tiled
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_tiled private
Do we allow the display of the tiled option.
Definition at line 355 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes().
m_usingSprectraNumChoice
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_usingSprectraNumChoice = false private
Definition at line 378 of file MantidWSIndexDialog.h.
Referenced by plotAllRequested(), plotRequested(), and validatePlotOptions().
m_usingWsIndexChoice
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_usingWsIndexChoice = false private
Flags to indicate which one of the two interval lists above is chosen by user.
Definition at line 378 of file MantidWSIndexDialog.h.
Referenced by plotAllRequested(), plotRequested(), and validatePlotOptions().
m_waterfall
bool MantidQt::MantidWidgets::MantidWSIndexWidget::m_waterfall private
Do we allow the display of the waterfall option.
Definition at line 352 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes().
m_wsBox
QVBoxLayout * MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsBox private
Definition at line 365 of file MantidWSIndexDialog.h.
Referenced by initWorkspaceBox().
m_wsField
QLineEditWithErrorMark* MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsField private
Definition at line 363 of file MantidWSIndexDialog.h.
Referenced by editedSpectraField(), initWorkspaceBox(), and plotRequested().
m_wsIndexChoice
IntervalList MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsIndexChoice private
IntervalLists for the range of indices/numbers CHOSEN by the user.
Definition at line 375 of file MantidWSIndexDialog.h.
Referenced by getPlots(), plotAllRequested(), plotRequested(), and validatePlotOptions().
m_wsIndexIntervals
IntervalList MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsIndexIntervals private
IntervalLists for the range of indices/numbers AVAILABLE to the user.
Definition at line 373 of file MantidWSIndexDialog.h.
Referenced by generateWsIndexIntervals(), initWorkspaceBox(), and plotAllRequested().
m_wsMessage
QLabel* MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsMessage private
Pointers to the obligatory Qt objects:
Definition at line 361 of file MantidWSIndexDialog.h.
Referenced by initWorkspaceBox().
m_wsNames
QList<QString> MantidQt::MantidWidgets::MantidWSIndexWidget::m_wsNames private
A list of names of workspaces which are to be plotted.
Definition at line 371 of file MantidWSIndexDialog.h.
Referenced by checkForSpectraAxes(), generateSpectraNumIntervals(), generateWsIndexIntervals(), getPlots(), getSelections(), isSuitableForContourOrSurfacePlot(), populateLogComboBox(), and validatePlotOptions().
SIMPLE_PLOT
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::SIMPLE_PLOT = "1D Plot" static
Strings for plot types.
Definition at line 258 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), is1DPlotSelected(), and isSuitableForLogValues().
SURFACE_PLOT
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::SURFACE_PLOT = "Surface Plot" static
Definition at line 260 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), isSuitableForLogValues(), isSurfacePlotSelected(), onPlotOptionChanged(), and validatePlotOptions().
WATERFALL_PLOT
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::WATERFALL_PLOT = "Waterfall Plot" static
Definition at line 259 of file MantidWSIndexDialog.h.
Referenced by initOptionsBoxes(), isSuitableForLogValues(), and isWaterfallPlotSelected().
WORKSPACE_INDEX
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::WORKSPACE_INDEX = "Workspace index" static
Definition at line 254 of file MantidWSIndexDialog.h.
Referenced by getSelections(), and onPlotOptionChanged().
WORKSPACE_NAME
const QString MantidQt::MantidWidgets::MantidWSIndexWidget::WORKSPACE_NAME = "Workspace name" static
The string "Workspace index".
Definition at line 253 of file MantidWSIndexDialog.h.
Referenced by getSelections(), onPlotOptionChanged(), and populateLogComboBox().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidWSIndexDialog.h
qt/widgets/common/src/MantidWSIndexDialog.cpp