Mantid: Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp File Reference
AnalysisDataService.cpp File Reference
#include "MantidAPI/AnalysisDataService.h"
#include "MantidAPI/IPeaksWorkspace.h"
#include "MantidAPI/WorkspaceGroup.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/Converters/PySequenceToVector.h"
#include "MantidPythonInterface/core/Converters/ToPyList.h"
#include "MantidPythonInterface/core/DataServiceExporter.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/WeakPtr.h"
#include <boost/python/enum.hpp>
#include <boost/python/list.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/return_value_policy.hpp>
Functions
void export_AnalysisDataService ()
Function Documentation
export_AnalysisDataService()
void export_AnalysisDataService ()
Definition at line 103 of file AnalysisDataService.cpp.
References Mantid::API::AnalysisDataServiceImpl::addToGroup(), Mantid::API::AnalysisDataServiceImpl::removeFromGroup(), Mantid::API::AnalysisDataServiceImpl::uniqueHiddenName(), and Mantid::API::AnalysisDataServiceImpl::uniqueName().