Mantid: Mantid::Geometry::ComponentVisitor Class Reference
Mantid::Geometry::ComponentVisitor Class Reference abstract
ComponentVisitor : Visitor for IComponents.
#include <ComponentVisitor.h>
Public Member Functions
virtual size_t registerComponentAssembly (const ICompAssembly &assembly)=0
virtual size_t registerDetector (const IDetector &detector)=0
virtual size_t registerGenericComponent (const IComponent &component)=0
virtual size_t registerGenericObjComponent (const IObjComponent &objComponent)=0
virtual size_t registerGridBank (const ICompAssembly &bank)=0
virtual size_t registerInfiniteComponent (const Mantid::Geometry::IComponent &component)=0
virtual size_t registerInfiniteObjComponent (const IObjComponent &component)=0
virtual size_t registerObjComponentAssembly (const ObjCompAssembly &obj)=0
virtual size_t registerRectangularBank (const ICompAssembly &bank)=0
virtual size_t registerStructuredBank (const ICompAssembly &bank)=0
virtual ~ComponentVisitor ()=default
Detailed Description
ComponentVisitor : Visitor for IComponents.
Enables parsing of a full doubly linked InstrumentTree without need for dynamic casts. Public methods are called by accepting IComponent
Definition at line 25 of file ComponentVisitor.h.
Constructor & Destructor Documentation
~ComponentVisitor()
virtual Mantid::Geometry::ComponentVisitor::~ComponentVisitor () virtual default
Member Function Documentation
registerComponentAssembly()
virtual size_t Mantid::Geometry::ComponentVisitor::registerComponentAssembly (const ICompAssembly & assembly) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::CompAssembly::registerContents().
registerDetector()
virtual size_t Mantid::Geometry::ComponentVisitor::registerDetector (const IDetector & detector) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::Detector::registerContents().
registerGenericComponent()
virtual size_t Mantid::Geometry::ComponentVisitor::registerGenericComponent (const IComponent & component) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::Component::registerContents().
registerGenericObjComponent()
virtual size_t Mantid::Geometry::ComponentVisitor::registerGenericObjComponent (const IObjComponent & objComponent) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::ObjComponent::registerContents().
registerGridBank()
virtual size_t Mantid::Geometry::ComponentVisitor::registerGridBank (const ICompAssembly & bank) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::GridDetector::registerContents().
registerInfiniteComponent()
virtual size_t Mantid::Geometry::ComponentVisitor::registerInfiniteComponent (const Mantid::Geometry::IComponent & component) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
registerInfiniteObjComponent()
virtual size_t Mantid::Geometry::ComponentVisitor::registerInfiniteObjComponent (const IObjComponent & component) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::ObjComponent::registerContents().
registerObjComponentAssembly()
virtual size_t Mantid::Geometry::ComponentVisitor::registerObjComponentAssembly (const ObjCompAssembly & obj) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::ObjCompAssembly::registerContents().
registerRectangularBank()
virtual size_t Mantid::Geometry::ComponentVisitor::registerRectangularBank (const ICompAssembly & bank) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::RectangularDetector::registerContents().
registerStructuredBank()
virtual size_t Mantid::Geometry::ComponentVisitor::registerStructuredBank (const ICompAssembly & bank) pure virtual
Implemented in Mantid::Geometry::InstrumentVisitor.
Referenced by Mantid::Geometry::StructuredDetector::registerContents().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Instrument/ComponentVisitor.h