Mantid: Mantid::Kernel::ConfigObserver Class Reference
Mantid::Kernel::ConfigObserver Class Reference abstract
The ConfigObserver is used to observe changes in the configuration based on notifications sent from the ConfigService.
#include <ConfigObserver.h>
Public Member Functions
ConfigObserver ()
Begins listening to notifications from the global ConfigService.
ConfigObserver (const ConfigObserver &other)
Copying a config observer is the same as default constructing one.
void notifyValueChanged (ConfigValChangeNotification_ptr notification)
Called when a config property's value is changed.
void notifyValueChanged (const std::string &name, const std::string &newValue, const std::string &prevValue)
Called when a config property's value is changed.
ConfigObserver & operator= (const ConfigObserver &other)
Nothing to do but we must overload the = operator to prevent a default copy which would produce incorrect results.
virtual ~ConfigObserver () noexcept
Protected Member Functions
virtual void onValueChanged (const std::string &name, const std::string &newValue, const std::string &prevValue)=0
Private Attributes
Poco::NObserver< ConfigObserver, Mantid::Kernel::ConfigValChangeNotification > m_valueChangeListener
Detailed Description
The ConfigObserver is used to observe changes in the configuration based on notifications sent from the ConfigService.
Definition at line 17 of file ConfigObserver.h.
Constructor & Destructor Documentation
ConfigObserver() [1/2]
Mantid::Kernel::ConfigObserver::ConfigObserver ()
Begins listening to notifications from the global ConfigService.
Definition at line 15 of file ConfigObserver.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and m_valueChangeListener.
ConfigObserver() [2/2]
Mantid::Kernel::ConfigObserver::ConfigObserver (const ConfigObserver & other)
Copying a config observer is the same as default constructing one.
It is necessary to create a new listener object with the this pointer in order for the correct object to recieve the notification.
Parameters
other The observer to copy.
Definition at line 27 of file ConfigObserver.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_valueChangeListener, and UNUSED_ARG.
~ConfigObserver()
Mantid::Kernel::ConfigObserver::~ConfigObserver () virtual noexcept
Definition at line 48 of file ConfigObserver.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and m_valueChangeListener.
Member Function Documentation
notifyValueChanged() [1/2]
void Mantid::Kernel::ConfigObserver::notifyValueChanged (ConfigValChangeNotification_ptr notification)
Called when a config property's value is changed.
Parameters
notification The Poco notification object.
Definition at line 67 of file ConfigObserver.cpp.
References notifyValueChanged().
notifyValueChanged() [2/2]
void Mantid::Kernel::ConfigObserver::notifyValueChanged (const std::string & name, const std::string & newValue, const std::string & oldValue)
Called when a config property's value is changed.
Parameters
name The name of the property which changed.
newValue The new value of the property.
oldValue The old value of the property.
Definition at line 57 of file ConfigObserver.cpp.
References onValueChanged().
Referenced by notifyValueChanged().
onValueChanged()
virtual void Mantid::Kernel::ConfigObserver::onValueChanged (const std::string & name, const std::string & newValue, const std::string & prevValue) protected pure virtual
Implemented in Mantid::Kernel::ConfigPropertyObserver, and ConfigObserverWrapper.
Referenced by notifyValueChanged().
operator=()
ConfigObserver & Mantid::Kernel::ConfigObserver::operator= (const ConfigObserver & other)
Nothing to do but we must overload the = operator to prevent a default copy which would produce incorrect results.
We don't need to re-register with the ConfigService since it is not possible to create a ConfigObserver which is unregistered and we only ever unregister in the destructor.
Parameters
other The observer to copy.
Definition at line 43 of file ConfigObserver.cpp.
References UNUSED_ARG.
Member Data Documentation
m_valueChangeListener
Poco::NObserver<ConfigObserver, Mantid::Kernel::ConfigValChangeNotification> Mantid::Kernel::ConfigObserver::m_valueChangeListener private
Definition at line 31 of file ConfigObserver.h.
Referenced by ConfigObserver(), and ~ConfigObserver().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/ConfigObserver.h
Framework/Kernel/src/ConfigObserver.cpp