Mantid: ITableWorkspacePickleSuite Class Reference
ITableWorkspacePickleSuite Class Reference
Static Public Member Functions
static dict getstate (const ITableWorkspace &ws)
static void setstate (ITableWorkspace &ws, const dict &state)
Static Private Member Functions
static void readData (ITableWorkspace &ws, const dict &state)
Read the data from a python dict into the table workspace.
static void readMetaData (ITableWorkspace &ws, const dict &state)
Read the meta data from a python dict into the table workspace.
static dict writeMetaData (const ITableWorkspace &ws)
Write the meta data from a table workspace to a python dict.
Detailed Description
Definition at line 698 of file ITableWorkspace.cpp.
Member Function Documentation
getstate()
static dict ITableWorkspacePickleSuite::getstate (const ITableWorkspace & ws) inline static
Definition at line 700 of file ITableWorkspace.cpp.
References toDict().
readData()
static void ITableWorkspacePickleSuite::readData (ITableWorkspace & ws, const dict & state) inline static private
Read the data from a python dict into the table workspace.
Parameters
ws :: the workspace to load data into
state :: the pickled state of the table
Definition at line 762 of file ITableWorkspace.cpp.
References Mantid::API::ITableWorkspace::appendRow(), Mantid::API::ITableWorkspace::getColumn(), Mantid::API::ITableWorkspace::getColumnNames(), and name.
readMetaData()
static void ITableWorkspacePickleSuite::readMetaData (ITableWorkspace & ws, const dict & state) inline static private
Read the meta data from a python dict into the table workspace.
This will read information relating to the column names and data types to be stored in the new table
Parameters
ws :: the workspace to load data into
state :: the pickled state of the table
Definition at line 742 of file ITableWorkspace.cpp.
References Mantid::API::ITableWorkspace::addColumn(), name, and value.
setstate()
static void ITableWorkspacePickleSuite::setstate (ITableWorkspace & ws, const dict & state) inline static
Definition at line 707 of file ITableWorkspace.cpp.
writeMetaData()
static dict ITableWorkspacePickleSuite::writeMetaData (const ITableWorkspace & ws) inline static private
Write the meta data from a table workspace to a python dict.
Parameters
ws :: the workspace to load data into
Definition at line 717 of file ITableWorkspace.cpp.
References Mantid::API::ITableWorkspace::getColumn(), Mantid::API::ITableWorkspace::getColumnNames(), and name.
The documentation for this class was generated from the following file:
Framework/PythonInterface/mantid/api/src/Exports/ITableWorkspace.cpp