Mantid: MantidQt::MantidWidgets::FunctionModelSpectra Class Reference
MantidQt::MantidWidgets::FunctionModelSpectra Class Reference
#include <FunctionModelSpectra.h>
Public Member Functions
WorkspaceIndex back () const
std::vector< WorkspaceIndex >::const_iterator begin () const
FunctionModelSpectra combine (const FunctionModelSpectra &other) const
bool empty () const
std::vector< WorkspaceIndex >::const_iterator end () const
void erase (WorkspaceIndex index)
WorkspaceIndex front () const
FunctionModelSpectra (const FunctionModelSpectra &vec)
FunctionModelSpectra (const std::string &str)
FunctionModelSpectra (FunctionModelSpectra &&vec)
FunctionModelSpectra (WorkspaceIndex minimum, WorkspaceIndex maximum)
std::pair< WorkspaceIndex, WorkspaceIndex > getMinMax () const
std::string getString () const
FitDomainIndex indexOf (WorkspaceIndex i) const
bool isContinuous () const
FunctionModelSpectra & operator= (const FunctionModelSpectra &vec)
FunctionModelSpectra & operator= (FunctionModelSpectra &&vec)
bool operator== (FunctionModelSpectra const &spec) const
const WorkspaceIndex & operator[] (FitDomainIndex index) const
FitDomainIndex size () const
Private Member Functions
void checkContinuous ()
FunctionModelSpectra (const std::set< WorkspaceIndex > &indices)
Private Attributes
bool m_isContinuous
std::vector< WorkspaceIndex > m_vec
Detailed Description
Definition at line 30 of file FunctionModelSpectra.h.
Constructor & Destructor Documentation
FunctionModelSpectra() [1/5]
MantidQt::MantidWidgets::FunctionModelSpectra::FunctionModelSpectra (const std::string & str) explicit
Definition at line 28 of file FunctionModelSpectra.cpp.
References checkContinuous().
FunctionModelSpectra() [2/5]
MantidQt::MantidWidgets::FunctionModelSpectra::FunctionModelSpectra (WorkspaceIndex minimum, WorkspaceIndex maximum)
Definition at line 33 of file FunctionModelSpectra.cpp.
References m_isContinuous, m_vec, and MantidQt::MantidWidgets::IndexType< Class >::value.
FunctionModelSpectra() [3/5]
MantidQt::MantidWidgets::FunctionModelSpectra::FunctionModelSpectra (const FunctionModelSpectra & vec) default
FunctionModelSpectra() [4/5]
MantidQt::MantidWidgets::FunctionModelSpectra::FunctionModelSpectra (FunctionModelSpectra && vec)
Definition at line 44 of file FunctionModelSpectra.cpp.
FunctionModelSpectra() [5/5]
MantidQt::MantidWidgets::FunctionModelSpectra::FunctionModelSpectra (const std::set< WorkspaceIndex > & indices) explicit private
Definition at line 96 of file FunctionModelSpectra.cpp.
References checkContinuous().
Member Function Documentation
back()
WorkspaceIndex MantidQt::MantidWidgets::FunctionModelSpectra::back () const inline
Definition at line 43 of file FunctionModelSpectra.h.
begin()
std::vector< WorkspaceIndex >::const_iterator MantidQt::MantidWidgets::FunctionModelSpectra::begin () const inline
Definition at line 44 of file FunctionModelSpectra.h.
Referenced by combine(), MantidQt::MantidWidgets::FunctionModelDataset::domainNames(), and indexOf().
checkContinuous()
void MantidQt::MantidWidgets::FunctionModelSpectra::checkContinuous () private
Definition at line 101 of file FunctionModelSpectra.cpp.
References m_isContinuous, m_vec, and value.
Referenced by erase(), FunctionModelSpectra(), and FunctionModelSpectra().
combine()
FunctionModelSpectra MantidQt::MantidWidgets::FunctionModelSpectra::combine (const FunctionModelSpectra & other) const
Definition at line 90 of file FunctionModelSpectra.cpp.
References begin(), and end().
empty()
bool MantidQt::MantidWidgets::FunctionModelSpectra::empty () const
Definition at line 55 of file FunctionModelSpectra.cpp.
References m_vec.
Referenced by getMinMax(), getString(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAddDomainAccepted().
end()
std::vector< WorkspaceIndex >::const_iterator MantidQt::MantidWidgets::FunctionModelSpectra::end () const inline
Definition at line 45 of file FunctionModelSpectra.h.
Referenced by combine(), MantidQt::MantidWidgets::FunctionModelDataset::domainNames(), and indexOf().
erase()
void MantidQt::MantidWidgets::FunctionModelSpectra::erase (WorkspaceIndex index)
Definition at line 113 of file FunctionModelSpectra.cpp.
References checkContinuous(), and m_vec.
front()
WorkspaceIndex MantidQt::MantidWidgets::FunctionModelSpectra::front () const inline
Definition at line 42 of file FunctionModelSpectra.h.
getMinMax()
std::pair< WorkspaceIndex, WorkspaceIndex > MantidQt::MantidWidgets::FunctionModelSpectra::getMinMax () const
Definition at line 70 of file FunctionModelSpectra.cpp.
References empty(), and m_vec.
getString()
std::string MantidQt::MantidWidgets::FunctionModelSpectra::getString () const
Definition at line 59 of file FunctionModelSpectra.cpp.
References empty(), m_isContinuous, m_vec, std::to_string(), and Mantid::Kernel::Strings::toString().
Referenced by operator==().
indexOf()
FitDomainIndex MantidQt::MantidWidgets::FunctionModelSpectra::indexOf (WorkspaceIndex i) const
Definition at line 82 of file FunctionModelSpectra.cpp.
References begin(), end(), std::to_string(), and MantidQt::MantidWidgets::IndexType< Class >::value.
isContinuous()
bool MantidQt::MantidWidgets::FunctionModelSpectra::isContinuous () const
Definition at line 80 of file FunctionModelSpectra.cpp.
References m_isContinuous.
operator=() [1/2]
FunctionModelSpectra & MantidQt::MantidWidgets::FunctionModelSpectra::operator= (const FunctionModelSpectra & vec) default
operator=() [2/2]
FunctionModelSpectra & MantidQt::MantidWidgets::FunctionModelSpectra::operator= (FunctionModelSpectra && vec)
Definition at line 49 of file FunctionModelSpectra.cpp.
References m_isContinuous, m_vec, and vec.
operator==()
bool MantidQt::MantidWidgets::FunctionModelSpectra::operator== (FunctionModelSpectra const & spec) const
Definition at line 76 of file FunctionModelSpectra.cpp.
References getString().
operator[]()
const WorkspaceIndex & MantidQt::MantidWidgets::FunctionModelSpectra::operator[] (FitDomainIndex index) const inline
Definition at line 46 of file FunctionModelSpectra.h.
References index.
size()
FitDomainIndex MantidQt::MantidWidgets::FunctionModelSpectra::size () const
Definition at line 57 of file FunctionModelSpectra.cpp.
References m_vec.
Referenced by MantidQt::MantidWidgets::FunctionModelDataset::domainNames().
Member Data Documentation
m_isContinuous
bool MantidQt::MantidWidgets::FunctionModelSpectra::m_isContinuous private
Definition at line 57 of file FunctionModelSpectra.h.
Referenced by checkContinuous(), FunctionModelSpectra(), getString(), isContinuous(), and operator=().
m_vec
std::vector<WorkspaceIndex> MantidQt::MantidWidgets::FunctionModelSpectra::m_vec private
Definition at line 56 of file FunctionModelSpectra.h.
Referenced by checkContinuous(), empty(), erase(), FunctionModelSpectra(), getMinMax(), getString(), operator=(), and size().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelSpectra.h
qt/widgets/common/src/FunctionModelSpectra.cpp