Mantid: AlgHistoryTreeWidget Class Reference
AlgHistoryTreeWidget Class Reference
#include <AlgorithmHistoryWindow.h>
Signals
void rollAlgorithmHistory (int index)
void unrollAlgorithmHistory (const std::vector< int > &indicies)
void updateAlgorithmHistoryWindow (Mantid::API::AlgorithmHistory_const_sptr algHistory)
Public Member Functions
AlgHistoryTreeWidget (QWidget *w)
Constructor.
void populateAlgHistoryTreeWidget (const Mantid::API::WorkspaceHistory &wsHist)
Protected Member Functions
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected) override
Private Slots
void onItemChanged (QTreeWidgetItem *item, int index)
Private Member Functions
QString concatVersionwithName (const std::string &name, const int version)
void getItemIndex (QTreeWidgetItem *item, int &index)
void itemChecked (QTreeWidgetItem *item, int index)
void itemUnchecked (QTreeWidgetItem *item, int index)
void populateNestedHistory (AlgHistoryItem *parentWidget, const Mantid::API::AlgorithmHistory_sptr &history)
void treeSelectionChanged ()
void uncheckAllChildren (QTreeWidgetItem *item, int index)
Private Attributes
QString m_algName
int m_nVersion
Static Private Attributes
static const int UNROLL_COLUMN_INDEX = 1
Detailed Description
Definition at line 57 of file AlgorithmHistoryWindow.h.
Constructor & Destructor Documentation
AlgHistoryTreeWidget()
AlgHistoryTreeWidget::AlgHistoryTreeWidget (QWidget * w) inline explicit
Constructor.
Definition at line 67 of file AlgorithmHistoryWindow.h.
References onItemChanged().
Member Function Documentation
concatVersionwithName()
QString AlgHistoryTreeWidget::concatVersionwithName (const std::string & name, const int version) private
Definition at line 761 of file AlgorithmHistoryWindow.cpp.
Referenced by populateAlgHistoryTreeWidget(), and populateNestedHistory().
getItemIndex()
void AlgHistoryTreeWidget::getItemIndex (QTreeWidgetItem * item, int & index) private
Definition at line 641 of file AlgorithmHistoryWindow.cpp.
References index.
Referenced by itemChecked(), and itemUnchecked().
itemChecked()
void AlgHistoryTreeWidget::itemChecked (QTreeWidgetItem * item, int index) private
Definition at line 662 of file AlgorithmHistoryWindow.cpp.
References getItemIndex(), index, and unrollAlgorithmHistory().
Referenced by onItemChanged().
itemUnchecked()
void AlgHistoryTreeWidget::itemUnchecked (QTreeWidgetItem * item, int index) private
Definition at line 689 of file AlgorithmHistoryWindow.cpp.
References getItemIndex(), index, rollAlgorithmHistory(), and uncheckAllChildren().
Referenced by onItemChanged().
onItemChanged
void AlgHistoryTreeWidget::onItemChanged (QTreeWidgetItem * item, int index) private slot
Definition at line 631 of file AlgorithmHistoryWindow.cpp.
References index, itemChecked(), itemUnchecked(), and UNROLL_COLUMN_INDEX.
Referenced by AlgHistoryTreeWidget().
populateAlgHistoryTreeWidget()
void AlgHistoryTreeWidget::populateAlgHistoryTreeWidget (const Mantid::API::WorkspaceHistory & wsHist)
Definition at line 725 of file AlgorithmHistoryWindow.cpp.
References concatVersionwithName(), Mantid::API::WorkspaceHistory::getAlgorithmHistories(), and populateNestedHistory().
Referenced by AlgorithmHistoryWindow::AlgorithmHistoryWindow().
populateNestedHistory()
void AlgHistoryTreeWidget::populateNestedHistory (AlgHistoryItem * parentWidget, const Mantid::API::AlgorithmHistory_sptr & history) private
Definition at line 743 of file AlgorithmHistoryWindow.cpp.
References concatVersionwithName(), history, and populateNestedHistory().
Referenced by populateAlgHistoryTreeWidget(), and populateNestedHistory().
rollAlgorithmHistory
void AlgHistoryTreeWidget::rollAlgorithmHistory (int index) signal
Referenced by itemUnchecked().
selectionChanged()
void AlgHistoryTreeWidget::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) override protected
Definition at line 720 of file AlgorithmHistoryWindow.cpp.
References treeSelectionChanged().
treeSelectionChanged()
void AlgHistoryTreeWidget::treeSelectionChanged () private
Definition at line 714 of file AlgorithmHistoryWindow.cpp.
References updateAlgorithmHistoryWindow().
Referenced by selectionChanged().
uncheckAllChildren()
void AlgHistoryTreeWidget::uncheckAllChildren (QTreeWidgetItem * item, int index) private
Definition at line 705 of file AlgorithmHistoryWindow.cpp.
References index, and uncheckAllChildren().
Referenced by itemUnchecked(), and uncheckAllChildren().
unrollAlgorithmHistory
void AlgHistoryTreeWidget::unrollAlgorithmHistory (const std::vector< int > & indicies) signal
Referenced by itemChecked().
updateAlgorithmHistoryWindow
void AlgHistoryTreeWidget::updateAlgorithmHistoryWindow (Mantid::API::AlgorithmHistory_const_sptr algHistory) signal
Referenced by treeSelectionChanged().
Member Data Documentation
m_algName
QString AlgHistoryTreeWidget::m_algName private
Definition at line 88 of file AlgorithmHistoryWindow.h.
m_nVersion
int AlgHistoryTreeWidget::m_nVersion private
Definition at line 89 of file AlgorithmHistoryWindow.h.
UNROLL_COLUMN_INDEX
const int AlgHistoryTreeWidget::UNROLL_COLUMN_INDEX = 1 static private
Definition at line 87 of file AlgorithmHistoryWindow.h.
Referenced by onItemChanged().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmHistoryWindow.h
qt/widgets/common/src/AlgorithmHistoryWindow.cpp