Mantid: MantidQt::API::OptionsPropertyWidget Class Reference
MantidQt::API::OptionsPropertyWidget Class Reference
Widget for displaying a Property that has a set of allowed values.
#include <OptionsPropertyWidget.h>
Public Slots
void editingFinished ()
Performs validation of the inputs when editing is finished.
Public Slots inherited from MantidQt::API::PropertyWidget
void replaceWSButtonClicked ()
Deal with the "replace workspace" button being clicked.
void toggleUseHistory ()
Toggle whether or not to use the previously-entered value.
void updateIconVisibility (const QString &error="")
Update which icons should be shown.
void userEditedProperty ()
To be called when a user edits a property, as opposed to one being set programmatically.
void valueChangedSlot ()
Emits a signal that the value of the property was changed.
Public Member Functions
QWidget * getMainWidget () override
QString getValue () const override
OptionsPropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
void setValueImpl (const QString &value) override
Set the value into the GUI.
~OptionsPropertyWidget () override
Destructor.
Public Member Functions inherited from MantidQt::API::PropertyWidget
void addReplaceWSButton ()
Create and show the "Replace WS" button.
QGridLayout * getGridLayout ()
int getGridRow ()
virtual QWidget * getMainWidget ()=0
Mantid::Kernel::Property * getProperty ()
virtual QString getValue () const =0
Return the value of the property given the GUI state.
bool inGrid () const
PropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
void setEnabled (bool val)
Sets all widgets contained within to Enabled.
void setError (const QString &error)
Externally set an error string to display in the validator.
void setPreviousValue (const QString &previousValue)
Set this widget's previously-entered value.
void setValue (const QString &value)
Set the value of the property given into the GUI state.
void setVisible (bool val) override
Sets all widgets contained within to Visible.
~PropertyWidget () override
Destructor.
Protected Attributes
QComboBox * m_combo
Combo box with the allowed options.
QLabel * m_label
Label (name of the property)
Protected Attributes inherited from MantidQt::API::PropertyWidget
QString m_doc
Documentation string (tooltip)
QString m_enteredValue
Stored the last non-previously-entered value entered entered by the user.
QString m_error
Error message received when trying to set the value.
QGridLayout * m_gridLayout
Grid layout of the dialog to which we are adding widgets.
QMap< Info, ClickableLabel * > m_icons
Allow icon access by Info enum.
bool m_isOutputWsProp
Whether or not the property is an output workspace.
QWidget * m_parent
Parent widget to add sub-widgets to.
QString m_previousValue
Stores the previously entered value when this dialog was last open.
Mantid::Kernel::Property * m_prop
Property being looked at. This is NOT owned by the widget.
QPushButton * m_replaceWSButton
Button to "replace input workspace".
int m_row
If using the GridLayout, this is the row where the widget was inserted.
bool m_useHistory
History on/off flag.
QVector< QWidget * > m_widgets
All contained widgets.
Additional Inherited Members
Public Types inherited from MantidQt::API::PropertyWidget
enum Info { INVALID , REPLACE , RESTORE }
Signals inherited from MantidQt::API::PropertyWidget
void replaceWorkspaceName (const QString &propName)
Signal is emitted whenever someone clicks the replace WS button.
void userChangedProperty ()
void valueChanged (const QString &propName)
Signal is emitted whenever the value (as entered by the user) in the GUI changes.
Static Public Member Functions inherited from MantidQt::API::PropertyWidget
static void setFieldPlaceholderText (Mantid::Kernel::Property *prop, QLineEdit *field)
Set the placeholder text of the given field based on the default value of the given property.
Static Protected Member Functions inherited from MantidQt::API::PropertyWidget
static void setLabelFont (Mantid::Kernel::Property *prop, QWidget *label)
Set the font of the given label based on the optional/required status of the given property.
Detailed Description
Widget for displaying a Property that has a set of allowed values.
The display is then a drop-down box instead of a Text box.
Date
2012-02-17
Definition at line 24 of file OptionsPropertyWidget.h.
Constructor & Destructor Documentation
OptionsPropertyWidget()
MantidQt::API::OptionsPropertyWidget::OptionsPropertyWidget (Mantid::Kernel::Property * prop, QWidget * parent = nullptr, QGridLayout * layout = nullptr, int row = -1)
Constructor.
Definition at line 28 of file OptionsPropertyWidget.cpp.
References Mantid::Kernel::Property::allowedValues(), editingFinished(), m_combo, MantidQt::API::PropertyWidget::m_doc, MantidQt::API::PropertyWidget::m_gridLayout, m_label, MantidQt::API::PropertyWidget::m_parent, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::PropertyWidget::m_row, MantidQt::API::PropertyWidget::m_widgets, Mantid::Kernel::Property::name(), MantidQt::API::PropertyWidget::setValue(), Mantid::Kernel::Property::type(), MantidQt::API::PropertyWidget::userEditedProperty(), and Mantid::Kernel::Property::value().
~OptionsPropertyWidget()
MantidQt::API::OptionsPropertyWidget::~OptionsPropertyWidget () override default
Destructor.
Member Function Documentation
editingFinished
void MantidQt::API::OptionsPropertyWidget::editingFinished () slot
Performs validation of the inputs when editing is finished.
Definition at line 84 of file OptionsPropertyWidget.cpp.
References Mantid::Kernel::Property::getDefault(), index, m_combo, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::PropertyWidget::updateIconVisibility(), and value.
Referenced by OptionsPropertyWidget().
getMainWidget()
QWidget * MantidQt::API::OptionsPropertyWidget::getMainWidget () inline override virtual
Returns
the main widget of this combo of widgets
Implements MantidQt::API::PropertyWidget.
Definition at line 35 of file OptionsPropertyWidget.h.
getValue()
QString MantidQt::API::OptionsPropertyWidget::getValue () const override virtual
Returns
the value of the property, as typed in the GUI, as a string
Implements MantidQt::API::PropertyWidget.
Definition at line 68 of file OptionsPropertyWidget.cpp.
References m_combo.
setValueImpl()
void MantidQt::API::OptionsPropertyWidget::setValueImpl (const QString & value) override virtual
Set the value into the GUI.
Parameters
value :: string representation of the value
Implements MantidQt::API::PropertyWidget.
Definition at line 74 of file OptionsPropertyWidget.cpp.
References Mantid::Kernel::Property::getDefault(), index, m_combo, MantidQt::API::PropertyWidget::m_prop, and value.
Member Data Documentation
m_combo
QComboBox* MantidQt::API::OptionsPropertyWidget::m_combo protected
Combo box with the allowed options.
Definition at line 42 of file OptionsPropertyWidget.h.
Referenced by editingFinished(), getValue(), OptionsPropertyWidget(), and setValueImpl().
m_label
QLabel* MantidQt::API::OptionsPropertyWidget::m_label protected
Label (name of the property)
Definition at line 39 of file OptionsPropertyWidget.h.
Referenced by OptionsPropertyWidget().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/OptionsPropertyWidget.h
qt/widgets/common/src/OptionsPropertyWidget.cpp