Mantid: ICat4::ns1__rule Class Reference
ICat4::ns1__rule Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__rule ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * crudFlags
ns1__grouping * grouping
std::string * what
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1917 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__rule()
ICat4::ns1__rule::ns1__rule () inline
Definition at line 1930 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__rule::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12906 of file ICat4C.cpp.
References crudFlags, grouping, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and what.
Referenced by ICat4::soap_in_ns1__rule(), ICat4::soap_new_req_ns1__rule(), and ICat4::soap_new_set_ns1__rule().
soap_get()
void * ICat4::ns1__rule::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13057 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__rule().
soap_in()
void * ICat4::ns1__rule::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12954 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__rule().
Referenced by ICat4::soap_in_ns1__rule().
soap_out()
int ICat4::ns1__rule::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12926 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__rule().
Referenced by soap_put().
soap_put()
int ICat4::ns1__rule::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13050 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__rule.
soap_serialize()
void ICat4::ns1__rule::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12915 of file ICat4C.cpp.
References crudFlags, grouping, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__grouping(), ICat4::soap_serialize_PointerTostd__string(), and what.
Referenced by ICat4::soap_serialize_PointerTons1__sampleType().
soap_type()
int ICat4::ns1__rule::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1923 of file ICat4Stub.h.
Member Data Documentation
crudFlags
std::string* ICat4::ns1__rule::crudFlags
Definition at line 1919 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
grouping
ns1__grouping* ICat4::ns1__rule::grouping
Definition at line 1920 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
what
std::string* ICat4::ns1__rule::what
Definition at line 1921 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp