Mantid: Mantid::Kernel::OptionalBool Class Reference
Mantid::Kernel::OptionalBool Class Reference
OptionalBool : Tri-state bool.
#include <OptionalBool.h>
Public Types
enum Value : unsigned char { False , True , Unset }
Public Member Functions
Value getValue () const
bool operator!= (const OptionalBool &other) const
OptionalBool & operator= (char const *arg)
OptionalBool & operator= (const int arg)
OptionalBool & operator= (const OptionalBool &other)=default
OptionalBool & operator= (std::string const &arg)
bool operator== (const OptionalBool &other) const
OptionalBool ()
OptionalBool (bool arg)
OptionalBool (char const *arg)
OptionalBool (const int arg)
OptionalBool (const OptionalBool &other)=default
OptionalBool (std::string arg)
OptionalBool (Value arg)
Value Validate (const std::string &arg)
virtual ~OptionalBool ()=default
Static Public Member Functions
static std::map< Value, std::string > enumToStrMap ()
static std::map< std::string, Value > strToEnumMap ()
Static Public Attributes
static const std::string StrFalse = "False"
static const std::string StrTrue = "True"
static const std::string StrUnset = "Unset"
Private Attributes
Value m_arg
Friends
MANTID_KERNEL_DLL std::ostream & operator<< (std::ostream &os, OptionalBool const &object)
MANTID_KERNEL_DLL std::istream & operator>> (std::istream &istream, OptionalBool &object)
Detailed Description
OptionalBool : Tri-state bool.
Defaults to unset.
Definition at line 25 of file OptionalBool.h.
Member Enumeration Documentation
Value
enum Mantid::Kernel::OptionalBool::Value : unsigned char
Enumerator
False
True
Unset
Definition at line 27 of file OptionalBool.h.
Constructor & Destructor Documentation
OptionalBool() [1/7]
Mantid::Kernel::OptionalBool::OptionalBool ()
Definition at line 36 of file OptionalBool.cpp.
OptionalBool() [2/7]
Mantid::Kernel::OptionalBool::OptionalBool (bool arg)
Definition at line 37 of file OptionalBool.cpp.
OptionalBool() [3/7]
Mantid::Kernel::OptionalBool::OptionalBool (OptionalBool::Value arg)
Definition at line 38 of file OptionalBool.cpp.
OptionalBool() [4/7]
Mantid::Kernel::OptionalBool::OptionalBool (std::string arg)
Definition at line 39 of file OptionalBool.cpp.
OptionalBool() [5/7]
Mantid::Kernel::OptionalBool::OptionalBool (char const * arg)
Definition at line 40 of file OptionalBool.cpp.
OptionalBool() [6/7]
Mantid::Kernel::OptionalBool::OptionalBool (const int arg)
Definition at line 41 of file OptionalBool.cpp.
OptionalBool() [7/7]
Mantid::Kernel::OptionalBool::OptionalBool (const OptionalBool & other) default
~OptionalBool()
virtual Mantid::Kernel::OptionalBool::~OptionalBool () virtual default
Member Function Documentation
enumToStrMap()
std::map< OptionalBool::Value, std::string > Mantid::Kernel::OptionalBool::enumToStrMap () static
Definition at line 84 of file OptionalBool.cpp.
References strToEnumMap().
Referenced by Mantid::Kernel::determineAllowedValues().
getValue()
OptionalBool::Value Mantid::Kernel::OptionalBool::getValue () const
Definition at line 66 of file OptionalBool.cpp.
References m_arg.
Referenced by export_OptionalBool().
operator!=()
bool Mantid::Kernel::OptionalBool::operator!= (const OptionalBool & other) const
Definition at line 64 of file OptionalBool.cpp.
References m_arg.
operator=() [1/4]
OptionalBool & Mantid::Kernel::OptionalBool::operator= (char const * arg)
Definition at line 50 of file OptionalBool.cpp.
References m_arg, and Validate().
operator=() [2/4]
OptionalBool & Mantid::Kernel::OptionalBool::operator= (const int arg)
Definition at line 54 of file OptionalBool.cpp.
References False, m_arg, std::to_string(), and True.
operator=() [3/4]
OptionalBool & Mantid::Kernel::OptionalBool::operator= (const OptionalBool & other) default
operator=() [4/4]
OptionalBool & Mantid::Kernel::OptionalBool::operator= (std::string const & arg)
Definition at line 46 of file OptionalBool.cpp.
References m_arg, and Validate().
operator==()
bool Mantid::Kernel::OptionalBool::operator== (const OptionalBool & other) const
Definition at line 62 of file OptionalBool.cpp.
References m_arg.
strToEnumMap()
std::map< std::string, OptionalBool::Value > Mantid::Kernel::OptionalBool::strToEnumMap () static
Definition at line 80 of file OptionalBool.cpp.
References False, StrFalse, StrTrue, StrUnset, True, and Unset.
Referenced by enumToStrMap().
Validate()
OptionalBool::Value Mantid::Kernel::OptionalBool::Validate (const std::string & arg)
Definition at line 21 of file OptionalBool.cpp.
References False, True, and Unset.
Referenced by operator=(), and operator=().
Friends And Related Symbol Documentation
operator<<
MANTID_KERNEL_DLL std::ostream & operator<< (std::ostream & os, OptionalBool const & object) friend
Definition at line 68 of file OptionalBool.cpp.
operator>>
MANTID_KERNEL_DLL std::istream & operator>> (std::istream & istream, OptionalBool & object) friend
Definition at line 73 of file OptionalBool.cpp.
Member Data Documentation
m_arg
Value Mantid::Kernel::OptionalBool::m_arg private
Definition at line 56 of file OptionalBool.h.
Referenced by getValue(), operator!=(), operator=(), operator=(), operator=(), and operator==().
StrFalse
const std::string Mantid::Kernel::OptionalBool::StrFalse = "False" static
Definition at line 31 of file OptionalBool.h.
Referenced by export_OptionalBoolValue(), and strToEnumMap().
StrTrue
const std::string Mantid::Kernel::OptionalBool::StrTrue = "True" static
Definition at line 32 of file OptionalBool.h.
Referenced by export_OptionalBoolValue(), and strToEnumMap().
StrUnset
const std::string Mantid::Kernel::OptionalBool::StrUnset = "Unset" static
Definition at line 30 of file OptionalBool.h.
Referenced by export_OptionalBoolValue(), and strToEnumMap().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/OptionalBool.h
Framework/Kernel/src/OptionalBool.cpp