Mantid: Framework/PythonInterface/mantid/api/src/Exports/CatalogManager.cpp File Reference
CatalogManager.cpp File Reference
#include "MantidAPI/CatalogManager.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/def.hpp>
#include <boost/python/list.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <map>
Functions
void export_CatalogManager ()
boost::python::list getActiveSessionsAsList (CatalogManagerImpl &self)
Function Documentation
export_CatalogManager()
void export_CatalogManager ()
Definition at line 31 of file CatalogManager.cpp.
References getActiveSessionsAsList(), and Mantid::API::CatalogManagerImpl::numberActiveSessions().
getActiveSessionsAsList()
boost::python::list getActiveSessionsAsList (CatalogManagerImpl & self)
Definition at line 22 of file CatalogManager.cpp.
Referenced by export_CatalogManager().