Mantid: ICat4::ns1__createResponse Class Reference
ICat4::ns1__createResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__createResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
LONG64 return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 472 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__createResponse()
ICat4::ns1__createResponse::ns1__createResponse () inline
Definition at line 488 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__createResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21647 of file ICat4C.cpp.
References ICat4::soap_default_LONG64().
Referenced by ICat4::ICATPortBindingProxy::create(), ICat4::soap_in_ns1__createResponse(), ICat4::soap_new_req_ns1__createResponse(), and ICat4::soap_new_set_ns1__createResponse().
soap_get()
void * ICat4::ns1__createResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21742 of file ICat4C.cpp.
References ICat4::soap_get_ns1__createResponse().
Referenced by ICat4::ICATPortBindingProxy::create().
soap_in()
void * ICat4::ns1__createResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21676 of file ICat4C.cpp.
References ICat4::soap_in_ns1__createResponse().
Referenced by ICat4::soap_in_ns1__createResponse().
soap_out()
int ICat4::ns1__createResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21661 of file ICat4C.cpp.
References ICat4::soap_out_ns1__createResponse().
soap_put()
int ICat4::ns1__createResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21735 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__createResponse.
soap_serialize()
void ICat4::ns1__createResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21653 of file ICat4C.cpp.
References SOAP_TYPE_ICat4_LONG64.
soap_type()
int ICat4::ns1__createResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 481 of file ICat4Stub.h.
Member Data Documentation
return_
LONG64 ICat4::ns1__createResponse::return_
Definition at line 474 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp