Mantid: MantidQt::MantidWidgets::AlgorithmSelectorWidget Class Reference
MantidQt::MantidWidgets::AlgorithmSelectorWidget Class Reference
A widget consisting of a ComboBox and a TreeWidget to allow a user to select an algorithm either by category or by typing.
#include <AlgorithmSelectorWidget.h>
Public Slots
void executeSelected ()
Slot called to execute whatever is the selected algorithm.
void findAlgTextChanged (const QString &text)
Show the selection in the tree when it changes in the combo.
void treeSelectionChanged ()
Show the selection in the combo when it changes in the tree.
void update ()
Update the lists of algorithms.
Signals
void algorithmFactoryUpdateReceived ()
void algorithmSelectionChanged (const QString &, int)
void executeAlgorithm (const QString &, int)
Public Member Functions
AlgorithmSelectorWidget (QWidget *parent)
Constructor.
SelectedAlgorithm getSelectedAlgorithm ()
Return the selected algorithm.
void setSelectedAlgorithm (QString &algName)
Set which algorithm is currently selected.
bool showExecuteButton () const
Is the execute button visible.
void showExecuteButton (const bool)
Show/hide the execute button.
~AlgorithmSelectorWidget () override
Destructor.
Protected Attributes
QPushButton * m_execButton
FindAlgComboBox * m_findAlg
AlgorithmTreeWidget * m_tree
Properties
bool showExecuteButton
Private Member Functions
void handleAlgorithmFactoryUpdate (Mantid::API::AlgorithmFactoryUpdateNotification_ptr)
Callback for AlgorithmFactory update notifications.
Private Attributes
bool m_updateInProgress
Poco::NObserver< AlgorithmSelectorWidget, Mantid::API::AlgorithmFactoryUpdateNotification > m_updateObserver
Observes algorithm factory update notifications.
Detailed Description
A widget consisting of a ComboBox and a TreeWidget to allow a user to select an algorithm either by category or by typing.
Date
2012-03-06
Definition at line 57 of file AlgorithmSelectorWidget.h.
Constructor & Destructor Documentation
AlgorithmSelectorWidget()
MantidQt::MantidWidgets::AlgorithmSelectorWidget::AlgorithmSelectorWidget (QWidget * parent)
Constructor.
Definition at line 28 of file AlgorithmSelectorWidget.cpp.
References algorithmFactoryUpdateReceived(), executeAlgorithm(), executeSelected(), findAlgTextChanged(), m_execButton, m_findAlg, m_tree, m_updateObserver, treeSelectionChanged(), and update().
~AlgorithmSelectorWidget()
MantidQt::MantidWidgets::AlgorithmSelectorWidget::~AlgorithmSelectorWidget () override
Destructor.
Definition at line 73 of file AlgorithmSelectorWidget.cpp.
References m_updateObserver.
Member Function Documentation
algorithmFactoryUpdateReceived
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::algorithmFactoryUpdateReceived () signal
Referenced by AlgorithmSelectorWidget(), and handleAlgorithmFactoryUpdate().
algorithmSelectionChanged
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::algorithmSelectionChanged (const QString & , int) signal
Referenced by findAlgTextChanged(), and treeSelectionChanged().
executeAlgorithm
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::executeAlgorithm (const QString & , int) signal
Referenced by AlgorithmSelectorWidget(), and executeSelected().
executeSelected
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::executeSelected () slot
Slot called to execute whatever is the selected algorithm.
Definition at line 95 of file AlgorithmSelectorWidget.cpp.
References executeAlgorithm(), and getSelectedAlgorithm().
Referenced by AlgorithmSelectorWidget().
findAlgTextChanged
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::findAlgTextChanged (const QString & text) slot
Show the selection in the tree when it changes in the combo.
Definition at line 104 of file AlgorithmSelectorWidget.cpp.
References algorithmSelectionChanged(), getSelectedAlgorithm(), m_findAlg, and m_tree.
Referenced by AlgorithmSelectorWidget().
getSelectedAlgorithm()
SelectedAlgorithm MantidQt::MantidWidgets::AlgorithmSelectorWidget::getSelectedAlgorithm ()
Return the selected algorithm.
The tree has priority. If nothing is selected in the tree, return the ComboBox selection
Definition at line 134 of file AlgorithmSelectorWidget.cpp.
References MantidQt::MantidWidgets::AlgorithmTreeWidget::getSelectedAlgorithm(), MantidQt::MantidWidgets::FindAlgComboBox::getSelectedAlgorithm(), m_findAlg, m_tree, and MantidQt::MantidWidgets::SelectedAlgorithm::name.
Referenced by executeSelected(), findAlgTextChanged(), and treeSelectionChanged().
handleAlgorithmFactoryUpdate()
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::handleAlgorithmFactoryUpdate (Mantid::API::AlgorithmFactoryUpdateNotification_ptr) private
Callback for AlgorithmFactory update notifications.
The algorithm factory has been updated, refresh the widget.
Definition at line 161 of file AlgorithmSelectorWidget.cpp.
References algorithmFactoryUpdateReceived().
setSelectedAlgorithm()
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::setSelectedAlgorithm (QString & algName)
Set which algorithm is currently selected.
Does not fire any signals. Updates the combobox, deselects in the tree.
Parameters
algName :: name of the algorithm
Definition at line 147 of file AlgorithmSelectorWidget.cpp.
References m_findAlg, and m_tree.
showExecuteButton() [1/2]
bool MantidQt::MantidWidgets::AlgorithmSelectorWidget::showExecuteButton () const
Is the execute button visible.
Definition at line 78 of file AlgorithmSelectorWidget.cpp.
References m_execButton.
showExecuteButton() [2/2]
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::showExecuteButton (const bool val)
Show/hide the execute button.
Definition at line 81 of file AlgorithmSelectorWidget.cpp.
References m_execButton.
treeSelectionChanged
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::treeSelectionChanged () slot
Show the selection in the combo when it changes in the tree.
Definition at line 120 of file AlgorithmSelectorWidget.cpp.
References algorithmSelectionChanged(), getSelectedAlgorithm(), and m_findAlg.
Referenced by AlgorithmSelectorWidget().
update
void MantidQt::MantidWidgets::AlgorithmSelectorWidget::update () slot
Update the lists of algorithms.
Definition at line 85 of file AlgorithmSelectorWidget.cpp.
References m_findAlg, m_tree, m_updateInProgress, MantidQt::MantidWidgets::AlgorithmTreeWidget::update(), and MantidQt::MantidWidgets::FindAlgComboBox::update().
Referenced by AlgorithmSelectorWidget().
Member Data Documentation
m_execButton
QPushButton* MantidQt::MantidWidgets::AlgorithmSelectorWidget::m_execButton protected
Definition at line 83 of file AlgorithmSelectorWidget.h.
Referenced by AlgorithmSelectorWidget(), showExecuteButton(), and showExecuteButton().
m_findAlg
FindAlgComboBox* MantidQt::MantidWidgets::AlgorithmSelectorWidget::m_findAlg protected
Definition at line 82 of file AlgorithmSelectorWidget.h.
Referenced by AlgorithmSelectorWidget(), findAlgTextChanged(), getSelectedAlgorithm(), setSelectedAlgorithm(), treeSelectionChanged(), and update().
m_tree
AlgorithmTreeWidget* MantidQt::MantidWidgets::AlgorithmSelectorWidget::m_tree protected
Definition at line 81 of file AlgorithmSelectorWidget.h.
Referenced by AlgorithmSelectorWidget(), findAlgTextChanged(), getSelectedAlgorithm(), setSelectedAlgorithm(), and update().
m_updateInProgress
bool MantidQt::MantidWidgets::AlgorithmSelectorWidget::m_updateInProgress private
Definition at line 91 of file AlgorithmSelectorWidget.h.
Referenced by update().
m_updateObserver
Poco::NObserver<AlgorithmSelectorWidget, Mantid::API::AlgorithmFactoryUpdateNotification> MantidQt::MantidWidgets::AlgorithmSelectorWidget::m_updateObserver private
Observes algorithm factory update notifications.
Definition at line 89 of file AlgorithmSelectorWidget.h.
Referenced by AlgorithmSelectorWidget(), and ~AlgorithmSelectorWidget().
Property Documentation
showExecuteButton
bool MantidQt::MantidWidgets::AlgorithmSelectorWidget::showExecuteButton read write
Definition at line 59 of file AlgorithmSelectorWidget.h.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmSelectorWidget.h
qt/widgets/common/src/AlgorithmSelectorWidget.cpp