Mantid: Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func > Class Template Reference
Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func > Class Template Reference
#include <PolarizationCorrectionsHelpers.h>
Classes
struct AutoDevResult
Public Types
using ADScalar = Types::ADScalar
using DerType = Types::DerType
using InputArray = Types::InputArray
using Types = ErrorTypeHelper< N >
Public Member Functions
ErrorPropagation (Func func)
AutoDevResult evaluate (const InputArray &values, const InputArray &errors) const
template<std::same_as< API::MatrixWorkspace_sptr >... Ts>
API::MatrixWorkspace_sptr evaluateWorkspaces (const bool outputWorkspaceDistribution, Ts... args) const
template<std::same_as< API::MatrixWorkspace_sptr >... Ts>
API::MatrixWorkspace_sptr evaluateWorkspaces (Ts... args) const
Private Member Functions
API::MatrixWorkspace_sptr convertToWorkspace2D (const API::MatrixWorkspace_sptr &workspace) const
template<std::same_as< API::MatrixWorkspace_sptr >... Ts>
API::MatrixWorkspace_sptr evaluateWorkspacesImpl (std::optional< bool > outputWorkspaceDistribution, Ts... args) const
API::MatrixWorkspace_sptr runWorkspaceConversionAlg (const API::MatrixWorkspace_sptr &workspace, const std::string &algName) const
Private Attributes
Func computeFunc
Detailed Description
template<size_t N, typename Func>
class Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >
Definition at line 80 of file PolarizationCorrectionsHelpers.h.
Member Typedef Documentation
ADScalar
template<size_t N, typename Func > using Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::ADScalar = Types::ADScalar
Definition at line 84 of file PolarizationCorrectionsHelpers.h.
DerType
template<size_t N, typename Func > using Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::DerType = Types::DerType
Definition at line 83 of file PolarizationCorrectionsHelpers.h.
InputArray
template<size_t N, typename Func > using Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::InputArray = Types::InputArray
Definition at line 85 of file PolarizationCorrectionsHelpers.h.
Types
template<size_t N, typename Func > using Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::Types = ErrorTypeHelper<N>
Definition at line 82 of file PolarizationCorrectionsHelpers.h.
Constructor & Destructor Documentation
ErrorPropagation()
template<size_t N, typename Func > Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::ErrorPropagation (Func func) inline
Definition at line 86 of file PolarizationCorrectionsHelpers.h.
Member Function Documentation
convertToWorkspace2D()
template<size_t N, typename Func > API::MatrixWorkspace_sptr Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::convertToWorkspace2D (const API::MatrixWorkspace_sptr & workspace) const inline private
Definition at line 164 of file PolarizationCorrectionsHelpers.h.
References Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::runWorkspaceConversionAlg(), and workspace.
Referenced by Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspacesImpl().
evaluate()
template<size_t N, typename Func > AutoDevResult Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluate (const InputArray & values, const InputArray & errors) const inline
Definition at line 94 of file PolarizationCorrectionsHelpers.h.
References Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::computeFunc, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspacesImpl().
evaluateWorkspaces() [1/2]
template<size_t N, typename Func > template<std::same_as< API::MatrixWorkspace_sptr >... Ts> API::MatrixWorkspace_sptr Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspaces (const bool outputWorkspaceDistribution, Ts... args) const inline
Definition at line 105 of file PolarizationCorrectionsHelpers.h.
References Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspacesImpl().
evaluateWorkspaces() [2/2]
template<size_t N, typename Func > template<std::same_as< API::MatrixWorkspace_sptr >... Ts> API::MatrixWorkspace_sptr Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspaces (Ts... args) const inline
Definition at line 110 of file PolarizationCorrectionsHelpers.h.
References Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspacesImpl().
evaluateWorkspacesImpl()
template<size_t N, typename Func > template<std::same_as< API::MatrixWorkspace_sptr >... Ts> API::MatrixWorkspace_sptr Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspacesImpl (std::optional< bool > outputWorkspaceDistribution, Ts... args) const inline private
Definition at line 118 of file PolarizationCorrectionsHelpers.h.
References Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::convertToWorkspace2D(), Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluate(), PARALLEL_FOR_IF, Mantid::Kernel::threadSafe(), and Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::AutoDevResult::value.
Referenced by Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspaces(), and Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluateWorkspaces().
runWorkspaceConversionAlg()
template<size_t N, typename Func > API::MatrixWorkspace_sptr Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::runWorkspaceConversionAlg (const API::MatrixWorkspace_sptr & workspace, const std::string & algName) const inline private
Definition at line 153 of file PolarizationCorrectionsHelpers.h.
References workspace.
Referenced by Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::convertToWorkspace2D().
Member Data Documentation
computeFunc
template<size_t N, typename Func > Func Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::computeFunc private
Definition at line 115 of file PolarizationCorrectionsHelpers.h.
Referenced by Mantid::Algorithms::Arithmetic::ErrorPropagation< N, Func >::evaluate().
The documentation for this class was generated from the following file:
Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationCorrectionsHelpers.h