Mantid: Framework/PythonInterface/mantid/api/src/Exports/IEventList.cpp File Reference
IEventList.cpp File Reference
#include "MantidAPI/IEventList.h"
#include "MantidPythonInterface/core/Converters/NDArrayToVector.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/Policies/VectorToNumpy.h"
#include <boost/python/class.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/make_function.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <vector>
Typedefs
using return_clone_numpy = return_value_policy< Policies::VectorToNumpy >
return_value_policy for copied numpy array
Functions
void export_IEventList ()
Typedef Documentation
return_clone_numpy
using return_clone_numpy = return_value_policy<Policies::VectorToNumpy>
return_value_policy for copied numpy array
Definition at line 39 of file IEventList.cpp.
Function Documentation
export_IEventList()
void export_IEventList ()
Definition at line 41 of file IEventList.cpp.
References Mantid::API::IEventList::addPulsetime(), Mantid::API::IEventList::addTof(), Mantid::API::IEventList::clear(), Mantid::API::IEventList::convertTof(), Mantid::API::IEventList::divide(), Mantid::API::IEventList::getEventType(), Mantid::API::IEventList::getMemorySize(), Mantid::API::IEventList::getNumberEvents(), Mantid::API::IEventList::getPulseTimeMax(), Mantid::API::IEventList::getPulseTimeMin(), Mantid::API::IEventList::getPulseTimes(), Mantid::API::IEventList::getTofMax(), Mantid::API::IEventList::getTofMin(), Mantid::API::IEventList::getTofs(), Mantid::API::IEventList::getWeightErrors(), Mantid::API::IEventList::getWeights(), Mantid::API::IEventList::integrate(), Mantid::API::IEventList::isSortedByTof(), Mantid::API::IEventList::maskTof(), Mantid::API::IEventList::multiply(), Mantid::API::IEventList::scaleTof(), Mantid::API::IEventList::switchTo(), Mantid::API::TOF, Mantid::API::WEIGHTED, and Mantid::API::WEIGHTED_NOTIME.