Mantid: Mantid::Algorithms::ExtractQENSMembers Class Reference
Mantid::Algorithms::ExtractQENSMembers Class Reference
ExtractQENSMembers : Extracts the fit members from a QENS fit.
#include <ExtractQENSMembers.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
std::vector< std::string > addMembersToADS (const std::vector< std::string > &members, const std::vector< Mantid::API::MatrixWorkspace_sptr > &memberWorkspaces, const std::string &outputWSName)
Adds the specified member workspaces to the analysis data service.
Mantid::API::MatrixWorkspace_sptr appendSpectra (const Mantid::API::MatrixWorkspace_sptr &inputWS, const Mantid::API::MatrixWorkspace_sptr &spectraWorkspace)
Appends the spectra of a specified workspace to another specified input workspace.
void appendToMembers (const Mantid::API::MatrixWorkspace_sptr &resultWS, std::vector< Mantid::API::MatrixWorkspace_sptr > &members)
Appends the n-th spectra in the specified result workspace to the n-th specified member workspace.
std::vector< Mantid::API::MatrixWorkspace_sptr > createMembersWorkspaces (const Mantid::API::MatrixWorkspace_sptr &initialWS, const std::vector< std::string > &members)
Creates the member workspaces from an initial result workspace and the member names.
void exec () override
Mantid::API::MatrixWorkspace_sptr extractSpectrum (const Mantid::API::MatrixWorkspace_sptr &inputWS, size_t spectrum)
Extracts the specified spectrum from the specified spectrum.
std::vector< std::string > getAxisLabels (const Mantid::API::MatrixWorkspace_sptr &workspace, size_t axisIndex) const
Retrieves the axis labels from the axis with the specified index, in the specified workspace.
std::vector< Mantid::API::MatrixWorkspace_sptr > getInputWorkspaces () const
std::vector< double > getQValues (const std::vector< Mantid::API::MatrixWorkspace_sptr > &workspaces)
Extracts the Q-Values from the specified workspace.
Mantid::API::WorkspaceGroup_sptr groupWorkspaces (const std::vector< std::string > &workspaceNames)
Groups the workspaces with the specified name.
void init () override
Initialize the algorithm's properties.
std::vector< std::string > renameConvolvedMembers (const std::vector< std::string > &members, const std::vector< std::string > &newNames) const
Renames the convolved members in the specified vector of members, to the respective names in the specified new names vector.
void setNumericAxis (const std::vector< Mantid::API::MatrixWorkspace_sptr > &workspaces, const std::vector< double > &values, size_t axisIndex) const
Creates and sets a numeric axis, filled with the specified values, on each of the specified workspaces at the specified axis index.
std::map< std::string, std::string > validateInputs () override
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
Workspace_sptr assemble (const std::string &partialWSName, const std::string &outputWSName)
Assemble the partial workspaces from all MPI processes.
Workspace_sptr assemble (Workspace_sptr partialWS)
Assemble the partial workspaces from all MPI processes.
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
int getNThreads ()
Return the number of MPI processes running.
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
bool isMainThread ()
Return true if we are running on the main thread.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Protected Attributes inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
bool m_useMPI
MPI option. If false, we will use one job event if MPI is available.
Detailed Description
ExtractQENSMembers : Extracts the fit members from a QENS fit.
Definition at line 18 of file ExtractQENSMembers.h.
Member Function Documentation
addMembersToADS()
std::vector< std::string > Mantid::Algorithms::ExtractQENSMembers::addMembersToADS (const std::vector< std::string > & members, const std::vector< Mantid::API::MatrixWorkspace_sptr > & memberWorkspaces, const std::string & outputWSName) private
Adds the specified member workspaces to the analysis data service.
Parameters
members The name of the members; corresponds to each member workspace.
memberWorkspaces The member workspaces.
outputWSName The name of the output workspace; used as a prefix.
Returns
A vector containing the names of the added workspaces.
Definition at line 283 of file ExtractQENSMembers.cpp.
References count, Mantid::Kernel::SingletonHolder< T >::Instance(), name(), and std::to_string().
Referenced by exec().
appendSpectra()
MatrixWorkspace_sptr Mantid::Algorithms::ExtractQENSMembers::appendSpectra (const Mantid::API::MatrixWorkspace_sptr & inputWS, const Mantid::API::MatrixWorkspace_sptr & spectraWorkspace) private
Appends the spectra of a specified workspace to another specified input workspace.
Parameters
inputWS The input workspace to append to.
spectraWorkspace The workspace whose spectra to append.
Definition at line 198 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by appendToMembers().
appendToMembers()
void Mantid::Algorithms::ExtractQENSMembers::appendToMembers (const Mantid::API::MatrixWorkspace_sptr & resultWS, std::vector< Mantid::API::MatrixWorkspace_sptr > & members) private
Appends the n-th spectra in the specified result workspace to the n-th specified member workspace.
Parameters
resultWS The result workspace.
members A vector containing the member workspaces.
Definition at line 246 of file ExtractQENSMembers.cpp.
References appendSpectra(), and extractSpectrum().
Referenced by exec().
category()
const std::string Mantid::Algorithms::ExtractQENSMembers::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 38 of file ExtractQENSMembers.cpp.
createMembersWorkspaces()
std::vector< MatrixWorkspace_sptr > Mantid::Algorithms::ExtractQENSMembers::createMembersWorkspaces (const Mantid::API::MatrixWorkspace_sptr & initialWS, const std::vector< std::string > & members) private
Creates the member workspaces from an initial result workspace and the member names.
Parameters
initialWS The initial result workspace.
members A vector of the member names.
Returns
A vector of the created members workspaces.
Definition at line 230 of file ExtractQENSMembers.cpp.
References extractSpectrum().
Referenced by exec().
exec()
void Mantid::Algorithms::ExtractQENSMembers::exec () override private
Definition at line 77 of file ExtractQENSMembers.cpp.
References addMembersToADS(), appendToMembers(), createMembersWorkspaces(), getAxisLabels(), getInputWorkspaces(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), getQValues(), groupWorkspaces(), renameConvolvedMembers(), and setNumericAxis().
extractSpectrum()
MatrixWorkspace_sptr Mantid::Algorithms::ExtractQENSMembers::extractSpectrum (const Mantid::API::MatrixWorkspace_sptr & inputWS, size_t spectrum) private
Extracts the specified spectrum from the specified spectrum.
Parameters
inputWS The workspace whose spectrum to extract.
spectrum The spectrum to extract.
Returns
A workspace containing the extracted spectrum.
Definition at line 181 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by appendToMembers(), and createMembersWorkspaces().
getAxisLabels()
std::vector< std::string > Mantid::Algorithms::ExtractQENSMembers::getAxisLabels (const Mantid::API::MatrixWorkspace_sptr & workspace, size_t axisIndex) const private
Retrieves the axis labels from the axis with the specified index, in the specified workspace.
Parameters
workspace The workspace whose axis labels to retrieve.
axisIndex The index of the axis whose labels retrieve.
Returns
The retrieved axis labels.
Definition at line 140 of file ExtractQENSMembers.cpp.
References workspace.
Referenced by exec().
getInputWorkspaces()
std::vector< MatrixWorkspace_sptr > Mantid::Algorithms::ExtractQENSMembers::getInputWorkspaces () const private
Definition at line 99 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), and name().
Referenced by exec().
getQValues()
std::vector< double > Mantid::Algorithms::ExtractQENSMembers::getQValues (const std::vector< Mantid::API::MatrixWorkspace_sptr > & workspaces) private
Extracts the Q-Values from the specified workspace.
Parameters
workspaces The workspaces whose Q-Values to extract.
Returns
The extracted Q-Values.
Definition at line 119 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and workspace.
Referenced by exec().
groupWorkspaces()
WorkspaceGroup_sptr Mantid::Algorithms::ExtractQENSMembers::groupWorkspaces (const std::vector< std::string > & workspaceNames) private
Groups the workspaces with the specified name.
Parameters
workspaceNames A vector of the names of the workspaces to group.
Returns
The group workspace.
Definition at line 214 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by exec().
init()
void Mantid::Algorithms::ExtractQENSMembers::init () override private
Initialize the algorithm's properties.
Definition at line 46 of file ExtractQENSMembers.cpp.
References Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::Algorithms::ExtractQENSMembers::name () const override
Algorithms name for identification.
See also
Algorithm::name
Definition at line 32 of file ExtractQENSMembers.cpp.
Referenced by addMembersToADS(), and getInputWorkspaces().
renameConvolvedMembers()
std::vector< std::string > Mantid::Algorithms::ExtractQENSMembers::renameConvolvedMembers (const std::vector< std::string > & members, const std::vector< std::string > & newNames) const private
Renames the convolved members in the specified vector of members, to the respective names in the specified new names vector.
Parameters
members A vector of the members.
newNames The names to use in renaming.
Returns
A vector of the members, with the convolved members renamed.
Definition at line 159 of file ExtractQENSMembers.cpp.
References index.
Referenced by exec().
setNumericAxis()
void Mantid::Algorithms::ExtractQENSMembers::setNumericAxis (const std::vector< Mantid::API::MatrixWorkspace_sptr > & workspaces, const std::vector< double > & values, size_t axisIndex) const private
Creates and sets a numeric axis, filled with the specified values, on each of the specified workspaces at the specified axis index.
Parameters
workspaces The workspaces whose axis to set.
values The values used to create the numeric axis.
axisIndex The index of the axis to set.
Definition at line 260 of file ExtractQENSMembers.cpp.
References workspace.
Referenced by exec().
summary()
const std::string Mantid::Algorithms::ExtractQENSMembers::summary () const override
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Definition at line 41 of file ExtractQENSMembers.cpp.
validateInputs()
std::map< std::string, std::string > Mantid::Algorithms::ExtractQENSMembers::validateInputs () override private
Definition at line 66 of file ExtractQENSMembers.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty().
version()
int Mantid::Algorithms::ExtractQENSMembers::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 35 of file ExtractQENSMembers.cpp.
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/ExtractQENSMembers.h
Framework/WorkflowAlgorithms/src/ExtractQENSMembers.cpp