Mantid: Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType > Class Template Reference
Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType > Class Template Reference
MatrixVectorPair.
#include <MatrixVectorPair.h>
Public Member Functions
MatrixVectorPair< MatrixNumericType, VectorType > getInverse () const
Returns the inverse MatrixVectorPair.
const Kernel::Matrix< MatrixNumericType > & getMatrix () const
Returns a const reference to the internally stored matrix.
const VectorType & getVector () const
Returns a const reference to the stored vector.
MatrixVectorPair ()
Default constructor, unit matrix and 0-vector.
MatrixVectorPair (const Kernel::Matrix< MatrixNumericType > &matrix, const VectorType &vector)
Constructor from matrix and vector.
bool operator!= (const MatrixVectorPair< MatrixNumericType, VectorType > &other) const
Inequality operator.
MatrixVectorPair< MatrixNumericType, VectorType > operator* (const MatrixVectorPair< MatrixNumericType, VectorType > &other) const
Operator to combine with another MatrixVectorPair.
template<typename T >
T operator* (const T &operand) const
Operator to transform a vector or point.
bool operator== (const MatrixVectorPair< MatrixNumericType, VectorType > &other) const
Comparison operator, compares the matrix & vector stored internally.
virtual ~MatrixVectorPair ()=default
Private Attributes
Kernel::Matrix< MatrixNumericType > m_matrix
VectorType m_vector
Detailed Description
template<typename MatrixNumericType, typename VectorType>
class Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >
MatrixVectorPair.
This class represents matrix/vector pairs (W, w) that are for example used to describe symmetry operations. On vector- or point-like objects they perform the following operation:
P' = (W * P) + w
The operation on other matrix/vector pairs is defined like this:
(P, p)' = ((W * P), (W * p) + w)
A very important use is in SymmetryOperation, which encapsulated a MatrixVectorPair<int, V3R> object to represent symmetry operations that are used to define point- and space groups.
@author Michael Wedel, ESS
@date 02/11/2015
Definition at line 34 of file MatrixVectorPair.h.
Constructor & Destructor Documentation
MatrixVectorPair() [1/2]
template<typename MatrixNumericType , typename VectorType > Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::MatrixVectorPair () inline
Default constructor, unit matrix and 0-vector.
Definition at line 37 of file MatrixVectorPair.h.
MatrixVectorPair() [2/2]
template<typename MatrixNumericType , typename VectorType > Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::MatrixVectorPair (const Kernel::Matrix< MatrixNumericType > & matrix, const VectorType & vector) inline
Constructor from matrix and vector.
Definition at line 40 of file MatrixVectorPair.h.
~MatrixVectorPair()
template<typename MatrixNumericType , typename VectorType > virtual Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::~MatrixVectorPair () virtual default
Member Function Documentation
getInverse()
template<typename MatrixNumericType , typename VectorType > MatrixVectorPair< MatrixNumericType, VectorType > Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getInverse () const inline
Returns the inverse MatrixVectorPair.
Definition at line 62 of file MatrixVectorPair.h.
References Mantid::Kernel::Matrix< T >::Invert(), Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix, and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector.
getMatrix()
template<typename MatrixNumericType , typename VectorType > const Kernel::Matrix< MatrixNumericType > & Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getMatrix () const inline
Returns a const reference to the internally stored matrix.
Definition at line 46 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix.
Referenced by Mantid::Geometry::SymmetryOperationSymbolParser::getNormalizedIdentifier(), Mantid::Geometry::SymmetryOperation::operator*(), Mantid::Geometry::SymmetryOperationSymbolParser::parseIdentifier(), and Mantid::Geometry::GroupTransformation::transformOperation().
getVector()
template<typename MatrixNumericType , typename VectorType > const VectorType & Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getVector () const inline
Returns a const reference to the stored vector.
Definition at line 49 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector.
Referenced by Mantid::Geometry::SymmetryOperationSymbolParser::getNormalizedIdentifier(), Mantid::Geometry::SymmetryOperation::operator*(), and Mantid::Geometry::GroupTransformation::transformOperation().
operator!=()
template<typename MatrixNumericType , typename VectorType > bool Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator!= (const MatrixVectorPair< MatrixNumericType, VectorType > & other) const inline
Inequality operator.
Definition at line 75 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator==().
operator*() [1/2]
template<typename MatrixNumericType , typename VectorType > MatrixVectorPair< MatrixNumericType, VectorType > Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator* (const MatrixVectorPair< MatrixNumericType, VectorType > & other) const inline
Operator to combine with another MatrixVectorPair.
Definition at line 56 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix, and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector.
operator*() [2/2]
template<typename MatrixNumericType , typename VectorType > template<typename T > T Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator* (const T & operand) const inline
Operator to transform a vector or point.
Definition at line 52 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix, and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector.
operator==()
template<typename MatrixNumericType , typename VectorType > bool Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator== (const MatrixVectorPair< MatrixNumericType, VectorType > & other) const inline
Comparison operator, compares the matrix & vector stored internally.
Definition at line 70 of file MatrixVectorPair.h.
References Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix, and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector.
Referenced by Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator!=().
Member Data Documentation
m_matrix
template<typename MatrixNumericType , typename VectorType > Kernel::Matrix<MatrixNumericType> Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_matrix private
Definition at line 78 of file MatrixVectorPair.h.
Referenced by Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getInverse(), Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getMatrix(), Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator*(), and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator==().
m_vector
template<typename MatrixNumericType , typename VectorType > VectorType Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::m_vector private
Definition at line 79 of file MatrixVectorPair.h.
Referenced by Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getInverse(), Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::getVector(), Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator*(), and Mantid::Geometry::MatrixVectorPair< MatrixNumericType, VectorType >::operator==().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/MatrixVectorPair.h