Mantid: Mantid::DataHandling::ISISRunLogs Class Reference
Mantid::DataHandling::ISISRunLogs Class Reference
Defines a class to aid in creating ISIS specific run logs for periods, status etc.
#include <ISISRunLogs.h>
Public Member Functions
void addPeriodLog (const int period, API::Run &exptRun)
Add 'period i' log.
void addPeriodLogs (const int period, API::Run &exptRun)
Adds period related logs.
void addStatusLog (API::Run &exptRun)
Adds the status log to the this run.
ISISRunLogs (const API::Run &icpRun)
Construct this object using a run that has the required ICP event log and the number of periods.
Static Public Member Functions
static void applyLogFiltering (Mantid::API::Run &exptRun)
applies log filtering for a run
static std::vector< std::string > getLogNamesExcludedFromFiltering (const API::Run &run)
gets the list of log names that should not be filtered
Private Attributes
std::unique_ptr< Kernel::LogParser > m_logParser
A LogParser object.
Detailed Description
Defines a class to aid in creating ISIS specific run logs for periods, status etc.
This adds:
status log: "running"
current period log: "period x"
all periods: "periods"
Definition at line 28 of file ISISRunLogs.h.
Constructor & Destructor Documentation
ISISRunLogs()
Mantid::DataHandling::ISISRunLogs::ISISRunLogs (const API::Run & icpRun)
Construct this object using a run that has the required ICP event log and the number of periods.
Construct using a run that has the required ICP event log Throws if no icp event log exists.
Parameters
icpRun :: A run containing the ICP event log to parse
Definition at line 28 of file ISISRunLogs.cpp.
References Mantid::API::LogManager::getLogData(), and m_logParser.
Member Function Documentation
addPeriodLog()
void Mantid::DataHandling::ISISRunLogs::addPeriodLog (const int period, API::Run & exptRun)
Add 'period i' log.
Add the period log to a run.
Parameters
period :: A period number.
exptRun :: The run to add the log to.
Definition at line 122 of file ISISRunLogs.cpp.
References Mantid::API::LogManager::addLogData(), and m_logParser.
Referenced by Mantid::DataHandling::LoadMuonNexus1::addPeriodLog().
addPeriodLogs()
void Mantid::DataHandling::ISISRunLogs::addPeriodLogs (const int period, API::Run & exptRun)
Adds period related logs.
Adds period related logs, and applies log filtering.
Parameters
period :: The period that we are adding to
exptRun :: The run for this period
Definition at line 54 of file ISISRunLogs.cpp.
References Mantid::API::LogManager::addLogData(), Mantid::API::LogManager::addProperty(), applyLogFiltering(), and m_logParser.
Referenced by Mantid::DataHandling::LoadMuonNexus1::addPeriodLog(), Mantid::DataHandling::LoadISISNexus2::exec(), and Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData().
addStatusLog()
void Mantid::DataHandling::ISISRunLogs::addStatusLog (API::Run & exptRun)
Adds the status log to the this run.
Parameters
exptRun :: The run that
Definition at line 47 of file ISISRunLogs.cpp.
References Mantid::API::LogManager::addLogData(), and m_logParser.
Referenced by Mantid::DataHandling::LoadMuonNexus1::runLoadLog(), and Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData().
applyLogFiltering()
void Mantid::DataHandling::ISISRunLogs::applyLogFiltering (Mantid::API::Run & exptRun) static
applies log filtering for a run
Applies log filtering buy run staus and period if available.
Parameters
exptRun :: The run for this period
Definition at line 72 of file ISISRunLogs.cpp.
References Mantid::Kernel::LogParser::currentPeriodLogName(), Mantid::API::LogManager::filterByLog(), Mantid::API::g_log, getLogNamesExcludedFromFiltering(), Mantid::API::LogManager::getPropertyAsIntegerValue(), Mantid::API::LogManager::getTimeSeriesProperty(), Mantid::Kernel::LogParser::periodsLogName(), Mantid::Kernel::LogParser::statusLogName(), and Mantid::Kernel::Logger::warning().
Referenced by addPeriodLogs(), and Mantid::DataHandling::LoadNexusProcessed::applyLogFiltering().
getLogNamesExcludedFromFiltering()
std::vector< std::string > Mantid::DataHandling::ISISRunLogs::getLogNamesExcludedFromFiltering (const API::Run & run) static
gets the list of log names that should not be filtered
Definition at line 126 of file ISISRunLogs.cpp.
References Mantid::API::LogManager::getProperties(), Mantid::API::LogManager::hasProperty(), Mantid::Kernel::LogParser::periodsLogName(), and Mantid::Kernel::LogParser::statusLogName().
Referenced by applyLogFiltering().
Member Data Documentation
m_logParser
std::unique_ptr<Kernel::LogParser> Mantid::DataHandling::ISISRunLogs::m_logParser private
A LogParser object.
Definition at line 48 of file ISISRunLogs.h.
Referenced by addPeriodLog(), addPeriodLogs(), addStatusLog(), and ISISRunLogs().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/ISISRunLogs.h
Framework/DataHandling/src/ISISRunLogs.cpp