Mantid: Mantid::Geometry::MDGeometryXMLDefinitions Class Reference
Mantid::Geometry::MDGeometryXMLDefinitions Class Reference
This type contains definitions that will be found in the xml schema for the rebinning instructions, but must be used in code as part of the peristance/fetching routines.
#include <MDGeometryXMLDefinitions.h>
Static Public Member Functions
static const std::string functionElementName ()
static const std::string functionNodeName ()
static const std::string functionOperatorInfo ()
static const std::string geometryNodeName ()
static const std::string geometryOperatorInfo ()
static const std::string RebinnedWSName ()
static const std::string signalName ()
static const std::string workspaceDimensionElementName ()
static const std::string workspaceGeometryElementName ()
static const std::string workspaceInstructionXMLTagEnd ()
static const std::string workspaceInstructionXMLTagStart ()
static const std::string workspaceLocationElementName ()
static const std::string workspaceLocationXMLTagEnd ()
static const std::string workspaceLocationXMLTagStart ()
static const std::string workspaceNameElementName ()
XML schema tag definitions for finding xml.
static const std::string workspaceNameXMLTagEnd ()
static const std::string workspaceNameXMLTagStart ()
static const std::string workspaceRefDimensionElementName ()
static const std::string workspaceTDimensionElementName ()
static const std::string workspaceXDimensionElementName ()
static const std::string workspaceYDimensionElementName ()
static const std::string workspaceZDimensionElementName ()
Detailed Description
This type contains definitions that will be found in the xml schema for the rebinning instructions, but must be used in code as part of the peristance/fetching routines.
This file provides a single location for definitions to aid future maintenance.
Author
Owen Arnold, Tessella plc
Date
16/12/2010
Definition at line 24 of file MDGeometryXMLDefinitions.h.
Member Function Documentation
functionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::functionElementName () inline static
Definition at line 35 of file MDGeometryXMLDefinitions.h.
functionNodeName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::functionNodeName () inline static
Definition at line 46 of file MDGeometryXMLDefinitions.h.
functionOperatorInfo()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::functionOperatorInfo () inline static
Definition at line 48 of file MDGeometryXMLDefinitions.h.
geometryNodeName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::geometryNodeName () inline static
Definition at line 45 of file MDGeometryXMLDefinitions.h.
geometryOperatorInfo()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::geometryOperatorInfo () inline static
Definition at line 47 of file MDGeometryXMLDefinitions.h.
RebinnedWSName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::RebinnedWSName () inline static
Definition at line 49 of file MDGeometryXMLDefinitions.h.
signalName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::signalName () inline static
Definition at line 44 of file MDGeometryXMLDefinitions.h.
workspaceDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceDimensionElementName () inline static
Definition at line 38 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
workspaceGeometryElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceGeometryElementName () inline static
Definition at line 37 of file MDGeometryXMLDefinitions.h.
workspaceInstructionXMLTagEnd()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceInstructionXMLTagEnd () inline static
Definition at line 32 of file MDGeometryXMLDefinitions.h.
workspaceInstructionXMLTagStart()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceInstructionXMLTagStart () inline static
Definition at line 31 of file MDGeometryXMLDefinitions.h.
workspaceLocationElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceLocationElementName () inline static
Definition at line 36 of file MDGeometryXMLDefinitions.h.
workspaceLocationXMLTagEnd()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceLocationXMLTagEnd () inline static
Definition at line 30 of file MDGeometryXMLDefinitions.h.
workspaceLocationXMLTagStart()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceLocationXMLTagStart () inline static
Definition at line 29 of file MDGeometryXMLDefinitions.h.
workspaceNameElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceNameElementName () inline static
XML schema tag definitions for finding xml.
Definition at line 34 of file MDGeometryXMLDefinitions.h.
workspaceNameXMLTagEnd()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceNameXMLTagEnd () inline static
Definition at line 28 of file MDGeometryXMLDefinitions.h.
workspaceNameXMLTagStart()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceNameXMLTagStart () inline static
Definition at line 27 of file MDGeometryXMLDefinitions.h.
workspaceRefDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceRefDimensionElementName () inline static
Definition at line 43 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
workspaceTDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceTDimensionElementName () inline static
Definition at line 42 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
workspaceXDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceXDimensionElementName () inline static
Definition at line 39 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
workspaceYDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceYDimensionElementName () inline static
Definition at line 40 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
workspaceZDimensionElementName()
static const std::string Mantid::Geometry::MDGeometryXMLDefinitions::workspaceZDimensionElementName () inline static
Definition at line 41 of file MDGeometryXMLDefinitions.h.
Referenced by Mantid::Geometry::MDGeometryXMLParser::execute().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDGeometryXMLDefinitions.h