Mantid: Mantid::Algorithms::GenerateEventsFilter Class Reference
Mantid::Algorithms::GenerateEventsFilter Class Reference final
GenerateEventsFilter : Generate an events-filter, i.e., a SplittersWorkspace according to user's request.
#include <GenerateEventsFilter.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
GenerateEventsFilter ()
Constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso algorithms related to this algorithm.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void addNewTimeFilterSplitter (Types::Core::DateAndTime starttime, Types::Core::DateAndTime stoptime, int wsindex, const std::string &info)
Add a splitter.
int determineChangingDirection (int startindex)
Determine the chaning direction of log value.
void exec () override
Implement abstract Algorithm methods.
Types::Core::DateAndTime findRunEnd ()
Find the end of the run.
void generateSplittersInMatrixWorkspace ()
Generate a matrix workspace containing splitters.
void generateSplittersInMatrixWorkspaceParallel ()
Generate a matrix workspace from the parallel version.
void generateSplittersInSplitterWS ()
Generate a SplittersWorkspace for filtering by log values.
bool identifyLogEntry (const int &index, const Types::Core::DateAndTime &currT, const bool &lastgood, const double &minvalue, const double &maxvalue, const Types::Core::DateAndTime &startT, const Types::Core::DateAndTime &stopT, const bool &filterIncrease, const bool &filterDecrease)
Identify the a sample log entry is within intended value and time region.
void init () override
Implement abstract Algorithm methods.
void makeFilterBySingleValue (double min, double max, double TimeTolerance, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime, int wsindex)
Fill a SplittingIntervalVec that will filter the events by matching SINGLE log values >= min and < max.
void makeMultipleFiltersByValues (std::map< size_t, int > indexwsindexmap, const std::vector< double > &logvalueranges, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime)
Make multiple-log-value filters in serial.
void makeMultipleFiltersByValuesParallel (const std::map< size_t, int > &indexwsindexmap, const std::vector< double > &logvalueranges, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime)
Make multiple-log-value filters in serial in parallel.
void makeMultipleFiltersByValuesPartialLog (int istart, int iend, std::vector< Types::Core::DateAndTime > &vecSplitTime, std::vector< int > &vecSplitGroup, std::map< size_t, int > indexwsindexmap, const std::vector< double > &logvalueranges, const Types::Core::time_duration &tol, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime)
Generate event splitters for partial sample log (serial)
Types::Core::DateAndTime makeSplitterInVector (std::vector< Types::Core::DateAndTime > &vecSplitTime, std::vector< int > &vecGroupIndex, Types::Core::DateAndTime start, Types::Core::DateAndTime stop, int group, int64_t tol_ns, Types::Core::DateAndTime lasttime)
Create a splitter and add to the vector of time splitters.
void processInOutWorkspaces ()
Process properties.
void processInputTime ()
Process the input for time.
void processIntegerValueFilter (int minvalue, int maxvalue, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime runend)
Generate event filters for integer sample log.
void processMultipleValueFilters (double minvalue, double valueinterval, double maxvalue, bool filterincrease, bool filterdecrease)
Generate filters from multiple values.
void processSingleValueFilter (double minvalue, double maxvalue, bool filterincrease, bool filterdecrease)
Generate filters by single log value.
size_t searchValue (const std::vector< double > &sorteddata, double value)
Search a value in a sorted vector.
void setFilterByLogValue (const std::string &logname)
Generate filters by log values.
void setFilterByTimeOnly ()
Set splitters by time value / interval only.
Private Attributes
API::MatrixWorkspace_const_sptr m_dataWS
Kernel::TimeSeriesProperty< double > * m_dblLog
API::ITableWorkspace_sptr m_filterInfoWS
API::MatrixWorkspace_sptr m_filterWS
Matrix workspace containing splitters.
bool m_forFastLog
Flag to output matrix workspace for fast log.
Kernel::TimeSeriesProperty< int > * m_intLog
bool m_isReverseLogarithmic = false
Flag if is reverse logarithmic time binning.
bool m_logAtCentre
double m_logTimeTolerance
Types::Core::DateAndTime m_runEndTime
Run end time.
Kernel::SplittingIntervalVec m_splitters
SplitterType.
DataObjects::SplittersWorkspace_sptr m_splitWS
SplitterWorkspace.
Types::Core::DateAndTime m_startTime
Types::Core::DateAndTime m_stopTime
double m_timeUnitConvertFactorToNS
bool m_useParallel
Processing algorithm type.
std::vector< std::vector< int > > m_vecGroupIndexSet
std::vector< int > m_vecSplitterGroup
std::vector< Types::Core::DateAndTime > m_vecSplitterTime
Vector as date and time.
std::vector< std::vector< Types::Core::DateAndTime > > m_vecSplitterTimeSet
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
GenerateEventsFilter : Generate an events-filter, i.e., a SplittersWorkspace according to user's request.
Request can be a combination of log value and time, i.e.,
(1) T_min (2) T_max (3) delta Time (4) Min log value (5) Max log value (6) delta log value (7) identify log value increment (bool) (8) number of sections per interval (applied to log value only!)
This algorithm can generate filters including (1) deltaT per interval from T_min to T_max with : Log value is not given (2) delta log value per interval from T_min to T_max and from min log value to max log value
Note: (1) Time can be (a) relative time in ns (b) relative time in second (float) (c) percentage time (2) if option "identify log value increment"
Date
2012-04-09
Definition at line 46 of file GenerateEventsFilter.h.
Constructor & Destructor Documentation
GenerateEventsFilter()
Mantid::Algorithms::GenerateEventsFilter::GenerateEventsFilter () explicit
Constructor.
Definition at line 38 of file GenerateEventsFilter.cpp.
Member Function Documentation
addNewTimeFilterSplitter()
void Mantid::Algorithms::GenerateEventsFilter::addNewTimeFilterSplitter (Types::Core::DateAndTime starttime, Types::Core::DateAndTime stoptime, int wsindex, const std::string & info) private
Add a splitter.
Add a new splitter to vector of splitters.
It is used by FilterByTime only.
Definition at line 1610 of file GenerateEventsFilter.cpp.
References m_filterInfoWS, m_forFastLog, m_isReverseLogarithmic, m_splitWS, m_vecSplitterGroup, and m_vecSplitterTime.
Referenced by makeFilterBySingleValue(), and setFilterByTimeOnly().
category()
const std::string Mantid::Algorithms::GenerateEventsFilter::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Implements Mantid::API::IAlgorithm.
Definition at line 64 of file GenerateEventsFilter.h.
determineChangingDirection()
int Mantid::Algorithms::GenerateEventsFilter::determineChangingDirection (int startindex) private
Determine the chaning direction of log value.
Determine starting value changing direction.
Definition at line 1570 of file GenerateEventsFilter.cpp.
References index, m_dblLog, Mantid::Kernel::TimeSeriesProperty< TYPE >::nthValue(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::size().
Referenced by makeMultipleFiltersByValuesPartialLog().
exec()
void Mantid::Algorithms::GenerateEventsFilter::exec () override private virtual
Implement abstract Algorithm methods.
Main execute body.
Implements Mantid::API::Algorithm.
Definition at line 154 of file GenerateEventsFilter.cpp.
References generateSplittersInMatrixWorkspace(), generateSplittersInMatrixWorkspaceParallel(), generateSplittersInSplitterWS(), Mantid::API::Algorithm::getProperty(), m_filterInfoWS, m_filterWS, m_forFastLog, m_splitWS, m_useParallel, processInOutWorkspaces(), processInputTime(), Mantid::API::Algorithm::progress(), setFilterByLogValue(), setFilterByTimeOnly(), and Mantid::Kernel::IPropertyManager::setProperty().
findRunEnd()
DateAndTime Mantid::Algorithms::GenerateEventsFilter::findRunEnd () private
Find the end of the run.
In order to consider the events in the last pulse,.
if proton charge does exist, then run end time will be extended by 1 pulse time
otherwise, extended by 0.1 second (10 Hz) Exception: unable to determine run end time
Definition at line 1783 of file GenerateEventsFilter.cpp.
References m_dataWS, Mantid::Kernel::TimeSeriesProperty< TYPE >::nthTime(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::size().
Referenced by processInputTime().
generateSplittersInMatrixWorkspace()
void Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspace () private
Generate a matrix workspace containing splitters.
Create a matrix workspace for filter from vector of splitter time and group.
Definition at line 1701 of file GenerateEventsFilter.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_filterWS, m_vecSplitterGroup, and m_vecSplitterTime.
Referenced by exec().
generateSplittersInMatrixWorkspaceParallel()
void Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspaceParallel () private
Generate a matrix workspace from the parallel version.
Generate matrix workspace for splitters from vector of splitter time and group in the parallel-version.
Definition at line 1730 of file GenerateEventsFilter.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, index, m_filterWS, m_vecGroupIndexSet, and m_vecSplitterTimeSet.
Referenced by exec().
generateSplittersInSplitterWS()
void Mantid::Algorithms::GenerateEventsFilter::generateSplittersInSplitterWS () private
Generate a SplittersWorkspace for filtering by log values.
Convert splitters vector to splitters and add to SplittersWorskpace.
Definition at line 1763 of file GenerateEventsFilter.cpp.
References m_splitWS, m_vecSplitterGroup, and m_vecSplitterTime.
Referenced by exec().
identifyLogEntry()
bool Mantid::Algorithms::GenerateEventsFilter::identifyLogEntry (const int & index, const Types::Core::DateAndTime & currT, const bool & lastgood, const double & minvalue, const double & maxvalue, const Types::Core::DateAndTime & startT, const Types::Core::DateAndTime & stopT, const bool & filterIncrease, const bool & filterDecrease) private
Identify the a sample log entry is within intended value and time region.
Identify a log entry whether it can be included in the splitter for filtering by single log value.
Direction: direction of changing value will be determined by the current log entry and next entry because the boundary should be set at the first value with new direction (as well as last value with the old direction)
Definition at line 902 of file GenerateEventsFilter.cpp.
References index, m_dblLog, Mantid::Kernel::TimeSeriesProperty< TYPE >::nthValue(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::size().
Referenced by makeFilterBySingleValue().
init()
void Mantid::Algorithms::GenerateEventsFilter::init () override private virtual
Implement abstract Algorithm methods.
Declare input.
Implements Mantid::API::Algorithm.
Definition at line 46 of file GenerateEventsFilter.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::Kernel::IS_NOT_EQUAL_TO, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertySettings().
makeFilterBySingleValue()
void Mantid::Algorithms::GenerateEventsFilter::makeFilterBySingleValue (double min, double max, double TimeTolerance, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime, int wsindex) private
Fill a SplittingIntervalVec that will filter the events by matching SINGLE log values >= min and < max.
Creates SplittingInterval's where times match the log values, and going to index==0.
(removed) split :: Splitter that will be filled.
Parameters
min :: Min value.
max :: Max value.
TimeTolerance :: Offset added to times in seconds.
centre :: Whether the log value time is considered centred or at the beginning.
filterIncrease :: As log value increase, and within (min, max), include this range in the filter.
filterDecrease :: As log value increase, and within (min, max), include this range in the filter.
startTime :: Start time.
stopTime :: Stop time.
wsindex :: Workspace index.
Definition at line 813 of file GenerateEventsFilter.cpp.
References addNewTimeFilterSplitter(), Mantid::API::Algorithm::g_log, identifyLogEntry(), m_dblLog, m_vecSplitterGroup, m_vecSplitterTime, name(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthTime(), Mantid::API::Algorithm::progress(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), and Mantid::Kernel::Logger::warning().
Referenced by processSingleValueFilter().
makeMultipleFiltersByValues()
void Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues (std::map< size_t, int > indexwsindexmap, const std::vector< double > & logvalueranges, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime) private
Make multiple-log-value filters in serial.
Fill a SplittingIntervalVec that will filter the events by matching SINGLE log values >= min and < max.
Creates SplittingInterval's where times match the log values, and going to index==0.
Parameters
indexwsindexmap :: Index.
logvalueranges :: A vector of double. Each 2i and 2i+1 pair is one individual log value range.
centre :: Whether the log value time is considered centred or at the beginning.
filterIncrease :: As log value increase, and within (min, max), include this range in the filter.
filterDecrease :: As log value increase, and within (min, max), include this range in the filter.
startTime :: Start time.
stopTime :: Stop time.
Definition at line 953 of file GenerateEventsFilter.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), m_dblLog, m_vecGroupIndexSet, m_vecSplitterGroup, m_vecSplitterTime, m_vecSplitterTimeSet, makeMultipleFiltersByValuesPartialLog(), Mantid::Kernel::Property::name(), Mantid::Kernel::Logger::notice(), Mantid::API::Algorithm::progress(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), and Mantid::Kernel::Logger::warning().
Referenced by processMultipleValueFilters().
makeMultipleFiltersByValuesParallel()
void Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel (const std::map< size_t, int > & indexwsindexmap, const std::vector< double > & logvalueranges, bool centre, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime) private
Make multiple-log-value filters in serial in parallel.
Fill a SplittingIntervalVec that will filter the events by matching SINGLE log values >= min and < max.
Creates SplittingInterval's where times match the log values, and going to index==0.
Parameters
indexwsindexmap :: Index.
logvalueranges :: A vector of double. Each 2i and 2i+1 pair is one individual log value range.
centre :: Whether the log value time is considered centred or at the beginning.
filterIncrease :: As log value increase, and within (min, max), include this range in the filter.
filterDecrease :: As log value increase, and within (min, max), include this range in the filter.
startTime :: Start time.
stopTime :: Stop time.
Definition at line 1007 of file GenerateEventsFilter.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), m_dblLog, m_vecGroupIndexSet, m_vecSplitterTimeSet, makeMultipleFiltersByValuesPartialLog(), Mantid::Kernel::Property::name(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_GET_MAX_THREADS, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, Mantid::API::Algorithm::progress(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), and Mantid::Kernel::Logger::warning().
Referenced by processMultipleValueFilters().
makeMultipleFiltersByValuesPartialLog()
void Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog (int istart, int iend, std::vector< Types::Core::DateAndTime > & vecSplitTime, std::vector< int > & vecSplitGroup, std::map< size_t, int > indexwsindexmap, const std::vector< double > & logvalueranges, const Types::Core::time_duration & tol, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime startTime, Types::Core::DateAndTime stopTime) private
Generate event splitters for partial sample log (serial)
Make filters by multiple log values of partial log.
Definition at line 1154 of file GenerateEventsFilter.cpp.
References Mantid::Kernel::Logger::debug(), determineChangingDirection(), Mantid::API::Algorithm::g_log, index, Mantid::Kernel::Logger::information(), Mantid::Kernel::Logger::is(), m_dblLog, makeSplitterInVector(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthTime(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthValue(), searchValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), and Mantid::Kernel::Logger::warning().
Referenced by makeMultipleFiltersByValues(), and makeMultipleFiltersByValuesParallel().
makeSplitterInVector()
DateAndTime Mantid::Algorithms::GenerateEventsFilter::makeSplitterInVector (std::vector< Types::Core::DateAndTime > & vecSplitTime, std::vector< int > & vecGroupIndex, Types::Core::DateAndTime start, Types::Core::DateAndTime stop, int group, int64_t tol_ns, Types::Core::DateAndTime lasttime) private
Create a splitter and add to the vector of time splitters.
Create a splitter and add to the vector of time splitters This method will be called intensively.
Definition at line 1658 of file GenerateEventsFilter.cpp.
References group.
Referenced by makeMultipleFiltersByValuesPartialLog(), and processIntegerValueFilter().
name()
const std::string Mantid::Algorithms::GenerateEventsFilter::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 51 of file GenerateEventsFilter.h.
Referenced by makeFilterBySingleValue().
processInOutWorkspaces()
void Mantid::Algorithms::GenerateEventsFilter::processInOutWorkspaces () private
Process properties.
Process user properties.
Definition at line 192 of file GenerateEventsFilter.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), m_dataWS, m_filterInfoWS, m_forFastLog, m_splitWS, m_useParallel, and Mantid::Kernel::Logger::warning().
Referenced by exec().
processInputTime()
void Mantid::Algorithms::GenerateEventsFilter::processInputTime () private
Process the input for time.
A smart but complicated default rule (1) Input time can be in multiple format: absolute time (ISO), relative time (double)
Definition at line 236 of file GenerateEventsFilter.cpp.
References findRunEnd(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_dataWS, m_runEndTime, m_startTime, m_stopTime, and m_timeUnitConvertFactorToNS.
Referenced by exec().
processIntegerValueFilter()
void Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter (int minvalue, int maxvalue, bool filterIncrease, bool filterDecrease, Types::Core::DateAndTime runend) private
Generate event filters for integer sample log.
Generate filters for an integer log.
Parameters
minvalue :: minimum allowed log value
maxvalue :: maximum allowed log value
filterIncrease :: include log value increasing period;
filterDecrease :: include log value decreasing period
runend :: end of run date and time
Definition at line 1383 of file GenerateEventsFilter.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::Kernel::delta, Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), m_filterInfoWS, m_intLog, m_logTimeTolerance, m_timeUnitConvertFactorToNS, m_vecSplitterGroup, m_vecSplitterTime, makeSplitterInVector(), Mantid::Kernel::Property::name(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), Mantid::Kernel::TimeSeriesProperty< TYPE >::timesAsVector(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::valuesAsVector().
Referenced by setFilterByLogValue().
processMultipleValueFilters()
void Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters (double minvalue, double valueinterval, double maxvalue, bool filterincrease, bool filterdecrease) private
Generate filters from multiple values.
Parameters
minvalue :: minimum value of the allowed log value;
valueinterval :: step of the log value for a series of filter
maxvalue :: maximum value of the allowed log value;
filterincrease :: if true, log value in the increasing curve should be included;
filterdecrease :: if true, log value in the decreasing curve should be included;
Definition at line 702 of file GenerateEventsFilter.cpp.
References Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), index, Mantid::Kernel::Logger::information(), m_dblLog, m_filterInfoWS, m_startTime, m_stopTime, m_useParallel, makeMultipleFiltersByValues(), makeMultipleFiltersByValuesParallel(), Mantid::Kernel::TimeSeriesProperty< TYPE >::maxValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::minValue(), Mantid::Kernel::Property::name(), Mantid::API::TableRow::size(), and Mantid::Kernel::Logger::warning().
Referenced by setFilterByLogValue().
processSingleValueFilter()
void Mantid::Algorithms::GenerateEventsFilter::processSingleValueFilter (double minvalue, double maxvalue, bool filterincrease, bool filterdecrease) private
Generate filters by single log value.
Parameters
minvalue :: minimum value of the allowed log value;
maxvalue :: maximum value of the allowed log value;
filterincrease :: if true, log value in the increasing curve should be included;
filterdecrease :: if true, log value in the decreasing curve should be included;
Definition at line 660 of file GenerateEventsFilter.cpp.
References Mantid::API::Algorithm::getProperty(), m_dblLog, m_filterInfoWS, m_startTime, m_stopTime, m_timeUnitConvertFactorToNS, makeFilterBySingleValue(), and Mantid::Kernel::Property::name().
Referenced by setFilterByLogValue().
searchValue()
size_t Mantid::Algorithms::GenerateEventsFilter::searchValue (const std::vector< double > & sorteddata, double value) private
Search a value in a sorted vector.
Do a binary search in the following list Warning: if the vector is not sorted, the error will happen.
This algorithm won't guarantee for it
Parameters
sorteddata :: Sorted data.
value :: Value to look up.
return: if value is out of range, then return datarange.size() + 1
Definition at line 1538 of file GenerateEventsFilter.cpp.
References index, and value.
Referenced by makeMultipleFiltersByValuesPartialLog().
seeAlso()
const std::vector< std::string > Mantid::Algorithms::GenerateEventsFilter::seeAlso () const inline override virtual
Function to return all of the seeAlso algorithms related to this algorithm.
Implements Mantid::API::IAlgorithm.
Definition at line 60 of file GenerateEventsFilter.h.
setFilterByLogValue()
void Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue (const std::string & logname) private
Generate filters by log values.
Parameters
logname :: name of the log to filter with
Definition at line 531 of file GenerateEventsFilter.cpp.
References Mantid::Kernel::TimeSeriesProperty< TYPE >::addValue(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::TimeSeriesProperty< TYPE >::eliminateDuplicates(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), Mantid::Kernel::TimeSeriesProperty< TYPE >::lastTime(), m_dataWS, m_dblLog, m_intLog, m_logAtCentre, m_logTimeTolerance, m_runEndTime, Mantid::Kernel::TimeSeriesProperty< TYPE >::maxValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::minValue(), processIntegerValueFilter(), processMultipleValueFilters(), and processSingleValueFilter().
Referenced by exec().
setFilterByTimeOnly()
void Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly () private
Set splitters by time value / interval only.
Definition at line 331 of file GenerateEventsFilter.cpp.
References addNewTimeFilterSplitter(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_dataWS, m_isReverseLogarithmic, m_startTime, m_stopTime, m_timeUnitConvertFactorToNS, Mantid::API::Algorithm::progress(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
summary()
const std::string Mantid::Algorithms::GenerateEventsFilter::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 53 of file GenerateEventsFilter.h.
version()
int Mantid::Algorithms::GenerateEventsFilter::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 59 of file GenerateEventsFilter.h.
Member Data Documentation
m_dataWS
API::MatrixWorkspace_const_sptr Mantid::Algorithms::GenerateEventsFilter::m_dataWS private
Definition at line 144 of file GenerateEventsFilter.h.
Referenced by findRunEnd(), processInOutWorkspaces(), processInputTime(), setFilterByLogValue(), and setFilterByTimeOnly().
m_dblLog
Kernel::TimeSeriesProperty<double>* Mantid::Algorithms::GenerateEventsFilter::m_dblLog private
Definition at line 161 of file GenerateEventsFilter.h.
Referenced by determineChangingDirection(), identifyLogEntry(), makeFilterBySingleValue(), makeMultipleFiltersByValues(), makeMultipleFiltersByValuesParallel(), makeMultipleFiltersByValuesPartialLog(), processMultipleValueFilters(), processSingleValueFilter(), and setFilterByLogValue().
m_filterInfoWS
API::ITableWorkspace_sptr Mantid::Algorithms::GenerateEventsFilter::m_filterInfoWS private
Definition at line 151 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), exec(), processInOutWorkspaces(), processIntegerValueFilter(), processMultipleValueFilters(), and processSingleValueFilter().
m_filterWS
API::MatrixWorkspace_sptr Mantid::Algorithms::GenerateEventsFilter::m_filterWS private
Matrix workspace containing splitters.
Definition at line 149 of file GenerateEventsFilter.h.
Referenced by exec(), generateSplittersInMatrixWorkspace(), and generateSplittersInMatrixWorkspaceParallel().
m_forFastLog
bool Mantid::Algorithms::GenerateEventsFilter::m_forFastLog private
Flag to output matrix workspace for fast log.
Definition at line 168 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), exec(), and processInOutWorkspaces().
m_intLog
Kernel::TimeSeriesProperty<int>* Mantid::Algorithms::GenerateEventsFilter::m_intLog private
Definition at line 162 of file GenerateEventsFilter.h.
Referenced by processIntegerValueFilter(), and setFilterByLogValue().
m_isReverseLogarithmic
bool Mantid::Algorithms::GenerateEventsFilter::m_isReverseLogarithmic = false private
Flag if is reverse logarithmic time binning.
Definition at line 180 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), and setFilterByTimeOnly().
m_logAtCentre
bool Mantid::Algorithms::GenerateEventsFilter::m_logAtCentre private
Definition at line 164 of file GenerateEventsFilter.h.
Referenced by setFilterByLogValue().
m_logTimeTolerance
double Mantid::Algorithms::GenerateEventsFilter::m_logTimeTolerance private
Definition at line 165 of file GenerateEventsFilter.h.
Referenced by processIntegerValueFilter(), and setFilterByLogValue().
m_runEndTime
Types::Core::DateAndTime Mantid::Algorithms::GenerateEventsFilter::m_runEndTime private
Run end time.
Definition at line 157 of file GenerateEventsFilter.h.
Referenced by processInputTime(), and setFilterByLogValue().
m_splitters
Kernel::SplittingIntervalVec Mantid::Algorithms::GenerateEventsFilter::m_splitters private
SplitterType.
Definition at line 171 of file GenerateEventsFilter.h.
m_splitWS
DataObjects::SplittersWorkspace_sptr Mantid::Algorithms::GenerateEventsFilter::m_splitWS private
SplitterWorkspace.
Definition at line 147 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), exec(), generateSplittersInSplitterWS(), and processInOutWorkspaces().
m_startTime
Types::Core::DateAndTime Mantid::Algorithms::GenerateEventsFilter::m_startTime private
Definition at line 153 of file GenerateEventsFilter.h.
Referenced by processInputTime(), processMultipleValueFilters(), processSingleValueFilter(), and setFilterByTimeOnly().
m_stopTime
Types::Core::DateAndTime Mantid::Algorithms::GenerateEventsFilter::m_stopTime private
Definition at line 154 of file GenerateEventsFilter.h.
Referenced by processInputTime(), processMultipleValueFilters(), processSingleValueFilter(), and setFilterByTimeOnly().
m_timeUnitConvertFactorToNS
double Mantid::Algorithms::GenerateEventsFilter::m_timeUnitConvertFactorToNS private
Definition at line 159 of file GenerateEventsFilter.h.
Referenced by processInputTime(), processIntegerValueFilter(), processSingleValueFilter(), and setFilterByTimeOnly().
m_useParallel
bool Mantid::Algorithms::GenerateEventsFilter::m_useParallel private
Processing algorithm type.
Definition at line 177 of file GenerateEventsFilter.h.
Referenced by exec(), processInOutWorkspaces(), and processMultipleValueFilters().
m_vecGroupIndexSet
std::vector<std::vector<int> > Mantid::Algorithms::GenerateEventsFilter::m_vecGroupIndexSet private
Definition at line 183 of file GenerateEventsFilter.h.
Referenced by generateSplittersInMatrixWorkspaceParallel(), makeMultipleFiltersByValues(), and makeMultipleFiltersByValuesParallel().
m_vecSplitterGroup
std::vector<int> Mantid::Algorithms::GenerateEventsFilter::m_vecSplitterGroup private
Definition at line 174 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), generateSplittersInMatrixWorkspace(), generateSplittersInSplitterWS(), makeFilterBySingleValue(), makeMultipleFiltersByValues(), and processIntegerValueFilter().
m_vecSplitterTime
std::vector<Types::Core::DateAndTime> Mantid::Algorithms::GenerateEventsFilter::m_vecSplitterTime private
Vector as date and time.
Definition at line 173 of file GenerateEventsFilter.h.
Referenced by addNewTimeFilterSplitter(), generateSplittersInMatrixWorkspace(), generateSplittersInSplitterWS(), makeFilterBySingleValue(), makeMultipleFiltersByValues(), and processIntegerValueFilter().
m_vecSplitterTimeSet
std::vector<std::vector<Types::Core::DateAndTime> > Mantid::Algorithms::GenerateEventsFilter::m_vecSplitterTimeSet private
Definition at line 182 of file GenerateEventsFilter.h.
Referenced by generateSplittersInMatrixWorkspaceParallel(), makeMultipleFiltersByValues(), and makeMultipleFiltersByValuesParallel().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/GenerateEventsFilter.h
Framework/Algorithms/src/GenerateEventsFilter.cpp