Mantid: ICat4::ns1__dummy Class Reference
ICat4::ns1__dummy Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__dummy ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
class ns1__datafile * arg0
class ns1__datafileFormat * arg1
class ns1__instrument * arg10
class ns1__investigation * arg11
class ns1__investigationType * arg12
class ns1__investigationUser * arg13
class ns1__keyword * arg14
class ns1__parameterType * arg15
class ns1__publication * arg16
class ns1__relatedDatafile * arg17
class ns1__sample * arg18
class ns1__sampleParameter * arg19
class ns1__datafileParameter * arg2
class ns1__shift * arg20
class ns1__study * arg21
class ns1__studyInvestigation * arg22
enum ns1__studyStatus * arg23
class ns1__application * arg24
class ns1__job * arg25
class ns1__dataCollection * arg26
class ns1__dataCollectionParameter * arg27
class ns1__dataCollectionDataset * arg28
class ns1__dataCollectionDatafile * arg29
class ns1__dataset * arg3
class ns1__grouping * arg30
class ns1__userGroup * arg31
class ns1__log * arg32
class ns1__publicStep * arg33
class ns1__datasetParameter * arg4
class ns1__datasetType * arg5
class ns1__facility * arg6
class ns1__facilityCycle * arg7
class ns1__instrumentScientist * arg8
class ns1__user * arg9
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1003 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__dummy()
ICat4::ns1__dummy::ns1__dummy () inline
Definition at line 1047 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__dummy::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17838 of file ICat4C.cpp.
References arg0, arg1, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg2, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg3, arg30, arg31, arg32, arg33, arg4, arg5, arg6, arg7, arg8, arg9, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::soap_in_ns1__dummy(), ICat4::soap_new_req_ns1__dummy(), and ICat4::soap_new_set_ns1__dummy().
soap_get()
void * ICat4::ns1__dummy::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18263 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__dummy().
soap_in()
void * ICat4::ns1__dummy::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17998 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__dummy().
Referenced by ICat4::soap_in_ns1__dummy().
soap_out()
int ICat4::ns1__dummy::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17918 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__dummy().
Referenced by soap_put().
soap_put()
int ICat4::ns1__dummy::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18256 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__dummy.
soap_serialize()
void ICat4::ns1__dummy::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17877 of file ICat4C.cpp.
References arg0, arg1, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, arg2, arg20, arg21, arg22, arg23, arg24, arg25, arg26, arg27, arg28, arg29, arg3, arg30, arg31, arg32, arg33, arg4, arg5, arg6, arg7, arg8, arg9, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTons1__application(), ICat4::soap_serialize_PointerTons1__dataCollection(), ICat4::soap_serialize_PointerTons1__dataCollectionDatafile(), ICat4::soap_serialize_PointerTons1__dataCollectionDataset(), ICat4::soap_serialize_PointerTons1__dataCollectionParameter(), ICat4::soap_serialize_PointerTons1__datafile(), ICat4::soap_serialize_PointerTons1__datafileFormat(), ICat4::soap_serialize_PointerTons1__datafileParameter(), ICat4::soap_serialize_PointerTons1__dataset(), ICat4::soap_serialize_PointerTons1__datasetParameter(), ICat4::soap_serialize_PointerTons1__datasetType(), ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTons1__facilityCycle(), ICat4::soap_serialize_PointerTons1__grouping(), ICat4::soap_serialize_PointerTons1__instrument(), ICat4::soap_serialize_PointerTons1__instrumentScientist(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTons1__investigationType(), ICat4::soap_serialize_PointerTons1__investigationUser(), ICat4::soap_serialize_PointerTons1__job(), ICat4::soap_serialize_PointerTons1__keyword(), ICat4::soap_serialize_PointerTons1__log(), ICat4::soap_serialize_PointerTons1__parameterType(), ICat4::soap_serialize_PointerTons1__publication(), ICat4::soap_serialize_PointerTons1__publicStep(), ICat4::soap_serialize_PointerTons1__relatedDatafile(), ICat4::soap_serialize_PointerTons1__sample(), ICat4::soap_serialize_PointerTons1__sampleParameter(), ICat4::soap_serialize_PointerTons1__shift(), ICat4::soap_serialize_PointerTons1__study(), ICat4::soap_serialize_PointerTons1__studyInvestigation(), ICat4::soap_serialize_PointerTons1__studyStatus(), ICat4::soap_serialize_PointerTons1__user(), and ICat4::soap_serialize_PointerTons1__userGroup().
Referenced by ICat4::soap_serialize_PointerTons1__refreshResponse().
soap_type()
int ICat4::ns1__dummy::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1040 of file ICat4Stub.h.
Member Data Documentation
arg0
class ns1__datafile* ICat4::ns1__dummy::arg0
Definition at line 1005 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg1
class ns1__datafileFormat* ICat4::ns1__dummy::arg1
Definition at line 1006 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg10
class ns1__instrument* ICat4::ns1__dummy::arg10
Definition at line 1015 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg11
class ns1__investigation* ICat4::ns1__dummy::arg11
Definition at line 1016 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg12
class ns1__investigationType* ICat4::ns1__dummy::arg12
Definition at line 1017 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg13
class ns1__investigationUser* ICat4::ns1__dummy::arg13
Definition at line 1018 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg14
class ns1__keyword* ICat4::ns1__dummy::arg14
Definition at line 1019 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg15
class ns1__parameterType* ICat4::ns1__dummy::arg15
Definition at line 1020 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg16
class ns1__publication* ICat4::ns1__dummy::arg16
Definition at line 1021 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg17
class ns1__relatedDatafile* ICat4::ns1__dummy::arg17
Definition at line 1022 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg18
class ns1__sample* ICat4::ns1__dummy::arg18
Definition at line 1023 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg19
class ns1__sampleParameter* ICat4::ns1__dummy::arg19
Definition at line 1024 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg2
class ns1__datafileParameter* ICat4::ns1__dummy::arg2
Definition at line 1007 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg20
class ns1__shift* ICat4::ns1__dummy::arg20
Definition at line 1025 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg21
class ns1__study* ICat4::ns1__dummy::arg21
Definition at line 1026 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg22
class ns1__studyInvestigation* ICat4::ns1__dummy::arg22
Definition at line 1027 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg23
enum ns1__studyStatus* ICat4::ns1__dummy::arg23
Definition at line 1028 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg24
class ns1__application* ICat4::ns1__dummy::arg24
Definition at line 1029 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg25
class ns1__job* ICat4::ns1__dummy::arg25
Definition at line 1030 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg26
class ns1__dataCollection* ICat4::ns1__dummy::arg26
Definition at line 1031 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg27
class ns1__dataCollectionParameter* ICat4::ns1__dummy::arg27
Definition at line 1032 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg28
class ns1__dataCollectionDataset* ICat4::ns1__dummy::arg28
Definition at line 1033 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg29
class ns1__dataCollectionDatafile* ICat4::ns1__dummy::arg29
Definition at line 1034 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg3
class ns1__dataset* ICat4::ns1__dummy::arg3
Definition at line 1008 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg30
class ns1__grouping* ICat4::ns1__dummy::arg30
Definition at line 1035 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg31
class ns1__userGroup* ICat4::ns1__dummy::arg31
Definition at line 1036 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg32
class ns1__log* ICat4::ns1__dummy::arg32
Definition at line 1037 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg33
class ns1__publicStep* ICat4::ns1__dummy::arg33
Definition at line 1038 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg4
class ns1__datasetParameter* ICat4::ns1__dummy::arg4
Definition at line 1009 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg5
class ns1__datasetType* ICat4::ns1__dummy::arg5
Definition at line 1010 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg6
class ns1__facility* ICat4::ns1__dummy::arg6
Definition at line 1011 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg7
class ns1__facilityCycle* ICat4::ns1__dummy::arg7
Definition at line 1012 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg8
class ns1__instrumentScientist* ICat4::ns1__dummy::arg8
Definition at line 1013 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
arg9
class ns1__user* ICat4::ns1__dummy::arg9
Definition at line 1014 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp