Mantid: Mantid::DataHandling::LoadILLIndirect2 Class Reference
Mantid::DataHandling::LoadILLIndirect2 Class Reference
Loads an ILL IN16B nexus file into a Mantid workspace.
#include <LoadILLIndirect2.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
int confidence (Nexus::NexusDescriptorLazy &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadILLIndirect2 ()
Constructor.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void exec () override
Execute the algorithm.
std::string getDataAddress (const Nexus::NXEntry &entry)
std::string getInstrumentFileName ()
Attaches proper suffixes of the relevant IDF dependent on first tube angle and mode.
void init () override
Initialize the algorithm's properties.
void initWorkSpace ()
Creates the workspace and initialises member variables with the corresponding values.
void loadDataDetails (const Nexus::NXEntry &entry)
Load Data details (number of tubes, channels, etc)
void loadDataIntoWorkspace (const Nexus::NXEntry &entry)
Load data found in nexus file in general, indirect mode.
void loadDiffractionData (Nexus::NXEntry &entry)
LoadILLIndirect2::loadDiffractionData Load IN16B diffraction data from the Nexus file when requested.
void loadNexusEntriesIntoProperties (const std::string &nexusfilename)
Loads the sample logs.
void moveComponent (const std::string &, double)
Moves the component to the given 2theta.
void moveSingleDetectors (const Nexus::NXEntry &entry)
IN16B has a few single detectors that are place around the sample.
void rotateTubes ()
The detector has two positions.
void setInstrumentName (const Nexus::NXEntry &firstEntry, const std::string &instrumentNameAddress)
Set member variable with the instrument name.
Private Attributes
std::set< int32_t > m_activeSDIndices
bool m_bats
size_t m_firstTubeAngleRounded
std::string m_instrumentName
Name of the instrument.
std::string m_loadOption
API::MatrixWorkspace_sptr m_localWorkspace
size_t m_numberOfChannels
size_t m_numberOfMonitors
size_t m_numberOfPixelsPerTube
size_t m_numberOfSimpleDetectors
size_t m_numberOfTubes
std::vector< std::string > m_supportedInstruments
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Loads an ILL IN16B nexus file into a Mantid workspace.
Definition at line 20 of file LoadILLIndirect2.h.
Constructor & Destructor Documentation
LoadILLIndirect2()
Mantid::DataHandling::LoadILLIndirect2::LoadILLIndirect2 ()
Constructor.
Definition at line 43 of file LoadILLIndirect2.cpp.
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadILLIndirect2::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 52 of file LoadILLIndirect2.cpp.
confidence()
int Mantid::DataHandling::LoadILLIndirect2::confidence (Nexus::NexusDescriptorLazy & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >.
Definition at line 62 of file LoadILLIndirect2.cpp.
References Mantid::Nexus::NexusDescriptorLazy::isEntry().
exec()
void Mantid::DataHandling::LoadILLIndirect2::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 97 of file LoadILLIndirect2.cpp.
References Mantid::DataHandling::LoadHelper::findInstrumentNexusAddress(), getInstrumentFileName(), Mantid::API::Algorithm::getPropertyValue(), initWorkSpace(), loadDataDetails(), loadDataIntoWorkspace(), loadDiffractionData(), Mantid::DataHandling::LoadHelper::loadEmptyInstrument(), loadNexusEntriesIntoProperties(), m_instrumentName, m_loadOption, m_localWorkspace, moveSingleDetectors(), Mantid::Nexus::NXRoot::openFirstEntry(), Mantid::API::Algorithm::progress(), rotateTubes(), setInstrumentName(), and Mantid::Kernel::IPropertyManager::setProperty().
getDataAddress()
std::string Mantid::DataHandling::LoadILLIndirect2::getDataAddress (const Nexus::NXEntry & entry) private
Definition at line 161 of file LoadILLIndirect2.cpp.
References Mantid::Nexus::NXClass::containsGroup(), m_loadOption, and Mantid::Nexus::NXClass::openNXGroup().
Referenced by loadDataDetails(), and loadDiffractionData().
getInstrumentFileName()
std::string Mantid::DataHandling::LoadILLIndirect2::getInstrumentFileName () private
Attaches proper suffixes of the relevant IDF dependent on first tube angle and mode.
Returns
: the file name of the corresponding IDF
Definition at line 355 of file LoadILLIndirect2.cpp.
References m_bats, m_firstTubeAngleRounded, m_instrumentName, and m_loadOption.
Referenced by exec().
init()
void Mantid::DataHandling::LoadILLIndirect2::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 82 of file LoadILLIndirect2.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
initWorkSpace()
void Mantid::DataHandling::LoadILLIndirect2::initWorkSpace () private
Creates the workspace and initialises member variables with the corresponding values.
Definition at line 238 of file LoadILLIndirect2.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_localWorkspace, m_numberOfChannels, m_numberOfMonitors, m_numberOfPixelsPerTube, m_numberOfSimpleDetectors, and m_numberOfTubes.
Referenced by exec().
loadDataDetails()
void Mantid::DataHandling::LoadILLIndirect2::loadDataDetails (const Nexus::NXEntry & entry) private
Load Data details (number of tubes, channels, etc)
Parameters
entry First entry of nexus file
Definition at line 182 of file LoadILLIndirect2.cpp.
References Mantid::API::Algorithm::g_log, getDataAddress(), Mantid::DataHandling::LoadHelper::getIntDataset(), Mantid::Kernel::Logger::information(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_activeSDIndices, m_bats, m_firstTubeAngleRounded, m_loadOption, m_numberOfChannels, m_numberOfPixelsPerTube, m_numberOfSimpleDetectors, m_numberOfTubes, Mantid::Nexus::NXClass::openNXFloat(), and Mantid::Nexus::NXClass::openNXInt().
Referenced by exec().
loadDataIntoWorkspace()
void Mantid::DataHandling::LoadILLIndirect2::loadDataIntoWorkspace (const Nexus::NXEntry & entry) private
Load data found in nexus file in general, indirect mode.
Parameters
entry :: The Nexus entry
Definition at line 255 of file LoadILLIndirect2.cpp.
References Mantid::DataHandling::LoadHelper::fillStaticWorkspace(), Mantid::DataHandling::LoadHelper::getIntDataset(), index, m_activeSDIndices, m_localWorkspace, m_numberOfChannels, m_numberOfMonitors, m_numberOfPixelsPerTube, and m_numberOfTubes.
Referenced by exec().
loadDiffractionData()
void Mantid::DataHandling::LoadILLIndirect2::loadDiffractionData (Nexus::NXEntry & entry) private
LoadILLIndirect2::loadDiffractionData Load IN16B diffraction data from the Nexus file when requested.
Parameters
entry
Definition at line 288 of file LoadILLIndirect2.cpp.
References Mantid::Nexus::NXClass::containsDataSet(), getDataAddress(), Mantid::DataHandling::LoadHelper::getIntDataset(), index, m_localWorkspace, m_numberOfChannels, m_numberOfMonitors, m_numberOfPixelsPerTube, m_numberOfTubes, Mantid::Nexus::NXClass::openNXGroup(), PARALLEL_FOR_IF, and Mantid::Kernel::threadSafe().
Referenced by exec().
loadNexusEntriesIntoProperties()
void Mantid::DataHandling::LoadILLIndirect2::loadNexusEntriesIntoProperties (const std::string & nexusfilename) private
Loads the sample logs.
Parameters
nexusfilename
Definition at line 337 of file LoadILLIndirect2.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), Mantid::API::LogManager::addProperty(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_localWorkspace, and READ.
Referenced by exec().
moveComponent()
void Mantid::DataHandling::LoadILLIndirect2::moveComponent (const std::string & componentName, double twoTheta) private
Moves the component to the given 2theta.
Parameters
componentName
twoTheta
Definition at line 373 of file LoadILLIndirect2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::Kernel::V3D::getSpherical(), m_localWorkspace, Mantid::Kernel::V3D::spherical(), and Mantid::Kernel::twoTheta.
Referenced by moveSingleDetectors().
moveSingleDetectors()
void Mantid::DataHandling::LoadILLIndirect2::moveSingleDetectors (const Nexus::NXEntry & entry) private
IN16B has a few single detectors that are place around the sample.
They are moved according to some values in the nexus file.
Parameters
entry : the nexus entry
Definition at line 392 of file LoadILLIndirect2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, index, Mantid::Nexus::NXDataSetTyped< T >::load(), m_activeSDIndices, moveComponent(), Mantid::Nexus::NXClass::openNXFloat(), and std::to_string().
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadILLIndirect2::name () const override virtual
Algorithm's name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 49 of file LoadILLIndirect2.cpp.
rotateTubes()
void Mantid::DataHandling::LoadILLIndirect2::rotateTubes () private
The detector has two positions.
By IDF the first tube is at 25.1 Degree as opening angle from Z- (Z+ is the beam direction). But it could be also 33.1, in which case all the tubes should be rotated around the sample.
Definition at line 410 of file LoadILLIndirect2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, m_firstTubeAngleRounded, m_localWorkspace, and Mantid::Kernel::Logger::warning().
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadILLIndirect2::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 28 of file LoadILLIndirect2.h.
setInstrumentName()
void Mantid::DataHandling::LoadILLIndirect2::setInstrumentName (const Nexus::NXEntry & firstEntry, const std::string & instrumentNameAddress) private
Set member variable with the instrument name.
Parameters
firstEntry : nexus entry
instrumentNameAddress : nexus address to instrument name
Definition at line 150 of file LoadILLIndirect2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::DataHandling::LoadHelper::getStringFromNexusAddress(), and m_instrumentName.
Referenced by exec().
summary()
const std::string Mantid::DataHandling::LoadILLIndirect2::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 32 of file LoadILLIndirect2.h.
version()
int Mantid::DataHandling::LoadILLIndirect2::version () const inline override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 27 of file LoadILLIndirect2.h.
Member Data Documentation
m_activeSDIndices
std::set<int32_t> Mantid::DataHandling::LoadILLIndirect2::m_activeSDIndices private
Definition at line 61 of file LoadILLIndirect2.h.
Referenced by loadDataDetails(), loadDataIntoWorkspace(), and moveSingleDetectors().
m_bats
bool Mantid::DataHandling::LoadILLIndirect2::m_bats private
Definition at line 63 of file LoadILLIndirect2.h.
Referenced by getInstrumentFileName(), and loadDataDetails().
m_firstTubeAngleRounded
size_t Mantid::DataHandling::LoadILLIndirect2::m_firstTubeAngleRounded private
Definition at line 64 of file LoadILLIndirect2.h.
Referenced by getInstrumentFileName(), loadDataDetails(), and rotateTubes().
m_instrumentName
std::string Mantid::DataHandling::LoadILLIndirect2::m_instrumentName private
Name of the instrument.
Definition at line 53 of file LoadILLIndirect2.h.
Referenced by exec(), getInstrumentFileName(), and setInstrumentName().
m_loadOption
std::string Mantid::DataHandling::LoadILLIndirect2::m_loadOption private
Definition at line 67 of file LoadILLIndirect2.h.
Referenced by exec(), getDataAddress(), getInstrumentFileName(), and loadDataDetails().
m_localWorkspace
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLIndirect2::m_localWorkspace private
Definition at line 51 of file LoadILLIndirect2.h.
Referenced by exec(), initWorkSpace(), loadDataIntoWorkspace(), loadDiffractionData(), loadNexusEntriesIntoProperties(), moveComponent(), and rotateTubes().
m_numberOfChannels
size_t Mantid::DataHandling::LoadILLIndirect2::m_numberOfChannels private
Definition at line 58 of file LoadILLIndirect2.h.
Referenced by initWorkSpace(), loadDataDetails(), loadDataIntoWorkspace(), and loadDiffractionData().
m_numberOfMonitors
size_t Mantid::DataHandling::LoadILLIndirect2::m_numberOfMonitors private
Definition at line 60 of file LoadILLIndirect2.h.
Referenced by initWorkSpace(), loadDataIntoWorkspace(), and loadDiffractionData().
m_numberOfPixelsPerTube
size_t Mantid::DataHandling::LoadILLIndirect2::m_numberOfPixelsPerTube private
Definition at line 57 of file LoadILLIndirect2.h.
Referenced by initWorkSpace(), loadDataDetails(), loadDataIntoWorkspace(), and loadDiffractionData().
m_numberOfSimpleDetectors
size_t Mantid::DataHandling::LoadILLIndirect2::m_numberOfSimpleDetectors private
Definition at line 59 of file LoadILLIndirect2.h.
Referenced by initWorkSpace(), and loadDataDetails().
m_numberOfTubes
size_t Mantid::DataHandling::LoadILLIndirect2::m_numberOfTubes private
Definition at line 56 of file LoadILLIndirect2.h.
Referenced by initWorkSpace(), loadDataDetails(), loadDataIntoWorkspace(), and loadDiffractionData().
m_supportedInstruments
std::vector<std::string> Mantid::DataHandling::LoadILLIndirect2::m_supportedInstruments private
Definition at line 66 of file LoadILLIndirect2.h.
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
Framework/DataHandling/src/LoadILLIndirect2.cpp