Mantid: MantidQt::CustomDialogs::MDPropertiesWidget Class Reference
MantidQt::CustomDialogs::MDPropertiesWidget Class Reference
Widgets to set properties for a IMDWorkspace: MaxSize.
#include <FitDialog.h>
Public Member Functions
void init () override
Initialize the child widgets with stored and allowed values.
MDPropertiesWidget (InputWorkspaceWidget *parent)
Constructor.
void setProperties () override
Set all workspace properties.
Public Member Functions inherited from MantidQt::CustomDialogs::DynamicPropertiesWidget
DynamicPropertiesWidget (InputWorkspaceWidget *parent)
Constructor.
virtual void init ()=0
Initialize the child widgets with stored and allowed values.
virtual void setProperties ()=0
Set all workspace properties.
Protected Attributes
QSpinBox * m_maxSize
Protected Attributes inherited from MantidQt::CustomDialogs::DynamicPropertiesWidget
InputWorkspaceWidget * m_wsWidget
Parent InputWorkspaceWidget.
Detailed Description
Widgets to set properties for a IMDWorkspace: MaxSize.
Definition at line 193 of file FitDialog.h.
Constructor & Destructor Documentation
MDPropertiesWidget()
MantidQt::CustomDialogs::MDPropertiesWidget::MDPropertiesWidget (InputWorkspaceWidget * parent)
Constructor.
Parameters
parent :: Parent InputWorkspaceWidget tab.
Definition at line 265 of file FitDialog.cpp.
References MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainType(), and m_maxSize.
Member Function Documentation
init()
void MantidQt::CustomDialogs::MDPropertiesWidget::init () inline override virtual
Initialize the child widgets with stored and allowed values.
Implements MantidQt::CustomDialogs::DynamicPropertiesWidget.
Definition at line 197 of file FitDialog.h.
setProperties()
void MantidQt::CustomDialogs::MDPropertiesWidget::setProperties () override virtual
Set all workspace properties.
Implements MantidQt::CustomDialogs::DynamicPropertiesWidget.
Definition at line 281 of file FitDialog.cpp.
References MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainIndex(), MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainType(), m_maxSize, MantidQt::CustomDialogs::DynamicPropertiesWidget::m_wsWidget, MantidQt::CustomDialogs::InputWorkspaceWidget::setPropertyValue(), and value.
Member Data Documentation
m_maxSize
QSpinBox* MantidQt::CustomDialogs::MDPropertiesWidget::m_maxSize protected
Definition at line 202 of file FitDialog.h.
Referenced by MDPropertiesWidget(), and setProperties().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/FitDialog.h
qt/widgets/plugins/algorithm_dialogs/src/FitDialog.cpp