Mantid: Mantid::DataObjects::EventWorkspaceMRU Class Reference
Mantid::DataObjects::EventWorkspaceMRU Class Reference
This is a container for the MRU (most-recently-used) list of generated histograms.
#include <EventWorkspaceMRU.h>
Public Types
using EType = Kernel::cow_ptr< HistogramData::HistogramE >
using EWithMarker = TypeWithMarker< EType >
using mru_listE = Kernel::MRUList< EWithMarker >
using mru_listY = Kernel::MRUList< YWithMarker >
using YType = Kernel::cow_ptr< HistogramData::HistogramY >
using YWithMarker = TypeWithMarker< YType >
Public Member Functions
void clear ()
Clear all the data in the MRU buffers.
void deleteIndex (const EventList *index)
Delete any entries in the MRU at the given index.
void ensureEnoughBuffersE (size_t thread_num) const
This function makes sure that there are enough data buffers (MRU's) for E for the number of threads requested.
void ensureEnoughBuffersY (size_t thread_num) const
This function makes sure that there are enough data buffers (MRU's) for Y for the number of threads requested.
EType findE (size_t thread_num, const EventList *index)
Find a Y histogram in the MRU.
YType findY (size_t thread_num, const EventList *index)
Find a Y histogram in the MRU.
void insertE (size_t thread_num, EType data, const EventList *index)
Insert a new histogram into the MRU.
void insertY (size_t thread_num, YType data, const EventList *index)
Insert a new histogram into the MRU.
size_t MRUSize () const
Return how many entries in the Y MRU list are used.
~EventWorkspaceMRU ()
Protected Attributes
std::vector< std::unique_ptr< mru_listE > > m_bufferedDataE
The most-recently-used list of dataE histograms.
std::vector< std::unique_ptr< mru_listY > > m_bufferedDataY
The most-recently-used list of dataY histograms.
Poco::RWLock m_changeMruListsMutexE
Mutex when adding entries in the MRU list.
Poco::RWLock m_changeMruListsMutexY
Detailed Description
This is a container for the MRU (most-recently-used) list of generated histograms.
Definition at line 61 of file EventWorkspaceMRU.h.
Member Typedef Documentation
EType
using Mantid::DataObjects::EventWorkspaceMRU::EType = Kernel::cow_ptr<HistogramData::HistogramE>
Definition at line 64 of file EventWorkspaceMRU.h.
EWithMarker
using Mantid::DataObjects::EventWorkspaceMRU::EWithMarker = TypeWithMarker<EType>
Definition at line 66 of file EventWorkspaceMRU.h.
mru_listE
using Mantid::DataObjects::EventWorkspaceMRU::mru_listE = Kernel::MRUList<EWithMarker>
Definition at line 69 of file EventWorkspaceMRU.h.
mru_listY
using Mantid::DataObjects::EventWorkspaceMRU::mru_listY = Kernel::MRUList<YWithMarker>
Definition at line 68 of file EventWorkspaceMRU.h.
YType
using Mantid::DataObjects::EventWorkspaceMRU::YType = Kernel::cow_ptr<HistogramData::HistogramY>
Definition at line 63 of file EventWorkspaceMRU.h.
YWithMarker
using Mantid::DataObjects::EventWorkspaceMRU::YWithMarker = TypeWithMarker<YType>
Definition at line 65 of file EventWorkspaceMRU.h.
Constructor & Destructor Documentation
~EventWorkspaceMRU()
Mantid::DataObjects::EventWorkspaceMRU::~EventWorkspaceMRU ()
Definition at line 13 of file EventWorkspaceMRU.cpp.
References m_bufferedDataE, m_bufferedDataY, m_changeMruListsMutexE, and m_changeMruListsMutexY.
Member Function Documentation
clear()
void Mantid::DataObjects::EventWorkspaceMRU::clear ()
Clear all the data in the MRU buffers.
Definition at line 62 of file EventWorkspaceMRU.cpp.
References m_bufferedDataE, m_bufferedDataY, m_changeMruListsMutexE, and m_changeMruListsMutexY.
deleteIndex()
void Mantid::DataObjects::EventWorkspaceMRU::deleteIndex (const EventList * index)
Delete any entries in the MRU at the given index.
Parameters
index :: index to delete.
Definition at line 142 of file EventWorkspaceMRU.cpp.
References index, m_bufferedDataE, m_bufferedDataY, m_changeMruListsMutexE, and m_changeMruListsMutexY.
Referenced by Mantid::DataObjects::EventList::clear(), Mantid::DataObjects::EventList::dataX(), Mantid::DataObjects::EventList::mutableHistogramRef(), Mantid::DataObjects::EventList::setX(), and Mantid::DataObjects::EventList::~EventList().
ensureEnoughBuffersE()
void Mantid::DataObjects::EventWorkspaceMRU::ensureEnoughBuffersE (size_t thread_num) const
This function makes sure that there are enough data buffers (MRU's) for E for the number of threads requested.
Parameters
thread_num :: thread number that wants a MRU buffer
Definition at line 36 of file EventWorkspaceMRU.cpp.
References m_bufferedDataE, and m_changeMruListsMutexE.
Referenced by Mantid::DataObjects::EventList::sharedE(), and Mantid::DataObjects::EventList::sharedY().
ensureEnoughBuffersY()
void Mantid::DataObjects::EventWorkspaceMRU::ensureEnoughBuffersY (size_t thread_num) const
This function makes sure that there are enough data buffers (MRU's) for Y for the number of threads requested.
Parameters
thread_num :: thread number that wants a MRU buffer
Definition at line 50 of file EventWorkspaceMRU.cpp.
References m_bufferedDataY, and m_changeMruListsMutexY.
Referenced by Mantid::DataObjects::EventList::sharedY().
findE()
Kernel::cow_ptr< HistogramData::HistogramE > Mantid::DataObjects::EventWorkspaceMRU::findE (size_t thread_num, const EventList * index)
Find a Y histogram in the MRU.
Parameters
thread_num :: number of the thread in which this is run
index :: index of the data to return
Returns
pointer to the TypeWithMarker that has the data; NULL if not found.
Definition at line 102 of file EventWorkspaceMRU.cpp.
References index, m_bufferedDataE, and m_changeMruListsMutexE.
Referenced by Mantid::DataObjects::EventList::sharedE().
findY()
Kernel::cow_ptr< HistogramData::HistogramY > Mantid::DataObjects::EventWorkspaceMRU::findY (size_t thread_num, const EventList * index)
Find a Y histogram in the MRU.
Parameters
thread_num :: number of the thread in which this is run
index :: index of the data to return
Returns
pointer to the TypeWithMarker that has the data; NULL if not found.
Definition at line 88 of file EventWorkspaceMRU.cpp.
References index, m_bufferedDataY, and m_changeMruListsMutexY.
Referenced by Mantid::DataObjects::EventList::sharedY().
insertE()
void Mantid::DataObjects::EventWorkspaceMRU::insertE (size_t thread_num, EType data, const EventList * index)
Insert a new histogram into the MRU.
Parameters
thread_num :: thread being accessed
data :: the new data
index :: index of the data to insert
Definition at line 130 of file EventWorkspaceMRU.cpp.
References index, m_bufferedDataE, and m_changeMruListsMutexE.
Referenced by Mantid::DataObjects::EventList::sharedE(), and Mantid::DataObjects::EventList::sharedY().
insertY()
void Mantid::DataObjects::EventWorkspaceMRU::insertY (size_t thread_num, YType data, const EventList * index)
Insert a new histogram into the MRU.
Parameters
thread_num :: thread being accessed
data :: the new data
index :: index of the data to insert
Definition at line 116 of file EventWorkspaceMRU.cpp.
References index, m_bufferedDataY, and m_changeMruListsMutexY.
Referenced by Mantid::DataObjects::EventList::sharedY().
MRUSize()
size_t Mantid::DataObjects::EventWorkspaceMRU::MRUSize () const
Return how many entries in the Y MRU list are used.
Only used in tests. It only returns the 0-th MRU list size.
Returns
:: number of entries in the MRU list.
Definition at line 163 of file EventWorkspaceMRU.cpp.
References m_bufferedDataY.
Member Data Documentation
m_bufferedDataE
std::vector<std::unique_ptr<mru_listE> > Mantid::DataObjects::EventWorkspaceMRU::m_bufferedDataE mutable protected
The most-recently-used list of dataE histograms.
Definition at line 95 of file EventWorkspaceMRU.h.
Referenced by clear(), deleteIndex(), ensureEnoughBuffersE(), findE(), insertE(), and ~EventWorkspaceMRU().
m_bufferedDataY
std::vector<std::unique_ptr<mru_listY> > Mantid::DataObjects::EventWorkspaceMRU::m_bufferedDataY mutable protected
The most-recently-used list of dataY histograms.
Definition at line 92 of file EventWorkspaceMRU.h.
Referenced by clear(), deleteIndex(), ensureEnoughBuffersY(), findY(), insertY(), MRUSize(), and ~EventWorkspaceMRU().
m_changeMruListsMutexE
Poco::RWLock Mantid::DataObjects::EventWorkspaceMRU::m_changeMruListsMutexE mutable protected
Mutex when adding entries in the MRU list.
Definition at line 98 of file EventWorkspaceMRU.h.
Referenced by clear(), deleteIndex(), ensureEnoughBuffersE(), findE(), insertE(), and ~EventWorkspaceMRU().
m_changeMruListsMutexY
Poco::RWLock Mantid::DataObjects::EventWorkspaceMRU::m_changeMruListsMutexY mutable protected
Definition at line 99 of file EventWorkspaceMRU.h.
Referenced by clear(), deleteIndex(), ensureEnoughBuffersY(), findY(), insertY(), and ~EventWorkspaceMRU().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/EventWorkspaceMRU.h
Framework/DataObjects/src/EventWorkspaceMRU.cpp