Mantid: Mantid::API::SpectrumInfoIterator< T > Class Template Reference
Mantid::API::SpectrumInfoIterator< T > Class Template Reference
SpectrumInfoIterator.
#include <SpectrumInfoIterator.h>
Public Member Functions
SpectrumInfoIterator (T &spectrumInfo, const size_t index)
Private Member Functions
void advance (int64_t delta)
void decrement ()
SpectrumInfoItem< T > & dereference () const
uint64_t distance_to (const SpectrumInfoIterator< T > &other) const
bool equal (const SpectrumInfoIterator< T > &other) const
size_t getIndex () const
void increment ()
void setIndex (const size_t index)
Private Attributes
SpectrumInfoItem< T > m_item
Friends
class boost::iterator_core_access
Detailed Description
template<typename T>
class Mantid::API::SpectrumInfoIterator< T >
SpectrumInfoIterator.
SpectrumInfoIterator allows users of the SpectrumInfo object access to data via an iterator. The iterator works as a slice view in that the index is incremented and all items accessible at that index are made available via the iterator.
Author
Bhuvan Bezawada, STFC
Date
2018
Definition at line 29 of file SpectrumInfoIterator.h.
Constructor & Destructor Documentation
SpectrumInfoIterator()
template<typename T > Mantid::API::SpectrumInfoIterator< T >::SpectrumInfoIterator (T & spectrumInfo, const size_t index) inline
Definition at line 33 of file SpectrumInfoIterator.h.
Member Function Documentation
advance()
template<typename T > void Mantid::API::SpectrumInfoIterator< T >::advance (int64_t delta) inline private
Definition at line 40 of file SpectrumInfoIterator.h.
References Mantid::Kernel::delta, and Mantid::API::SpectrumInfoIterator< T >::m_item.
decrement()
template<typename T > void Mantid::API::SpectrumInfoIterator< T >::decrement () inline private
Definition at line 55 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::m_item.
dereference()
template<typename T > SpectrumInfoItem< T > & Mantid::API::SpectrumInfoIterator< T >::dereference () const inline private
Definition at line 71 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::m_item.
distance_to()
template<typename T > uint64_t Mantid::API::SpectrumInfoIterator< T >::distance_to (const SpectrumInfoIterator< T > & other) const inline private
Definition at line 65 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::getIndex().
equal()
template<typename T > bool Mantid::API::SpectrumInfoIterator< T >::equal (const SpectrumInfoIterator< T > & other) const inline private
Definition at line 69 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::getIndex().
getIndex()
template<typename T > size_t Mantid::API::SpectrumInfoIterator< T >::getIndex () const inline private
Definition at line 61 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::m_item.
Referenced by Mantid::API::SpectrumInfoIterator< T >::distance_to(), and Mantid::API::SpectrumInfoIterator< T >::equal().
increment()
template<typename T > void Mantid::API::SpectrumInfoIterator< T >::increment () inline private
Definition at line 49 of file SpectrumInfoIterator.h.
References Mantid::API::SpectrumInfoIterator< T >::m_item.
setIndex()
template<typename T > void Mantid::API::SpectrumInfoIterator< T >::setIndex (const size_t index) inline private
Definition at line 63 of file SpectrumInfoIterator.h.
References index, and Mantid::API::SpectrumInfoIterator< T >::m_item.
Friends And Related Symbol Documentation
boost::iterator_core_access
template<typename T > friend class boost::iterator_core_access friend
Definition at line 37 of file SpectrumInfoIterator.h.
Member Data Documentation
m_item
template<typename T > SpectrumInfoItem<T> Mantid::API::SpectrumInfoIterator< T >::m_item mutable private
Definition at line 73 of file SpectrumInfoIterator.h.
Referenced by Mantid::API::SpectrumInfoIterator< T >::advance(), Mantid::API::SpectrumInfoIterator< T >::decrement(), Mantid::API::SpectrumInfoIterator< T >::dereference(), Mantid::API::SpectrumInfoIterator< T >::getIndex(), Mantid::API::SpectrumInfoIterator< T >::increment(), and Mantid::API::SpectrumInfoIterator< T >::setIndex().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/SpectrumInfoIterator.h