Mantid: Mantid::MDAlgorithms::MDNorm Class Reference
Mantid::MDAlgorithms::MDNorm Class Reference final
MDNormalization : Bin single crystal diffraction or direct geometry inelastic data and calculate the corresponding statistical weight.
#include <MDNorm.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
MDNorm ()
Constructor.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Member Functions
DataObjects::MDHistoWorkspace_sptr binBackgroundWS (const std::vector< Geometry::SymmetryOperation > &symmetryOps)
Bin(MD) input Background workspace.
DataObjects::MDHistoWorkspace_sptr binInputWS (const std::vector< Geometry::SymmetryOperation > &symmetryOps)
Bin(MD) input MDE workspace.
Mantid::Kernel::DblMatrix buildSymmetryMatrix (const Geometry::SymmetryOperation &so)
build symmetry matrix
void cacheDimensionXValues ()
Stores the X values from each H,K,L, and optionally DeltaE dimension as member variables.
void calcDiffractionIntersectionIntegral (std::vector< std::array< double, 4 > > &intersections, std::vector< double > &xValues, std::vector< double > &yValues, const API::MatrixWorkspace &integrFlux, const size_t &wsIdx)
Calculate the diffraction MDE's intersection integral of a certain detector/spectru.
void calcIntegralsForIntersections (const std::vector< double > &xValues, const API::MatrixWorkspace &integrFlux, size_t sp, std::vector< double > &yValues)
Linearly interpolate between the points in integrFlux at xValues and save the results in yValues.
void calcSingleDetectorNorm (const std::vector< std::array< double, 4 > > &intersections, const double &solid, std::vector< double > &yValues, const size_t &vmdDims, std::vector< coord_t > &pos, std::vector< coord_t > &posNew, std::vector< std::atomic< signal_t > > &signalArray, const double &solidBkgd, std::vector< std::atomic< signal_t > > &bkgdSignalArray)
Calculate the normalization among intersections on a single detector in 1 specific SpectrumInfo/ExperimentInfo.
void calculateIntersections (std::vector< std::array< double, 4 > > &intersections, const double theta, const double phi, const Kernel::DblMatrix &transform, double lowvalue, double highvalue)
Calculate the points of intersection for the given detector with cuboid surrounding the detector position in HKL.
void calculateNormalization (const std::vector< coord_t > &otherValues, const Geometry::SymmetryOperation &so, uint16_t expInfoIndex, size_t soIndex)
Computed the normalization for the input workspace.
Mantid::Kernel::DblMatrix calQTransform (const Mantid::API::ExperimentInfo &currentExpInfo, const Geometry::SymmetryOperation &so)
Calculate QTransform = (R * UB * SymmetryOperation * m_W)^-1.
void createBackgroundNormalizationWS (const DataObjects::MDHistoWorkspace &dataWS)
void createNormalizationWS (const DataObjects::MDHistoWorkspace &dataWS)
Create & cached the normalization workspace.
void determineBasisVector (const size_t &qindex, const std::string &value, const Kernel::DblMatrix &Qtransform, std::vector< double > &projection, std::stringstream &basisVector, std::vector< size_t > &qDimensionIndices)
MDNorm::determineBasisVector.
API::IMDWorkspace_sptr divideMD (const API::IMDHistoWorkspace_sptr &lhs, const API::IMDHistoWorkspace_sptr &rhs, const std::string &outputwsname, const double &startProgress, const double &endProgress)
void exec () override
Execute the algorithm.
std::map< std::string, std::string > getBinParameters ()
Calculate binning parameters.
std::vector< coord_t > getValuesFromOtherDimensions (bool &skipNormalization, uint16_t expInfoIndex=0) const
Retrieve logged values from non-HKL dimensions.
void init () override
Initialize the algorithm's properties.
std::string QDimensionName (std::vector< double > projection)
Get the dimension name when using reciprocal lattice units.
std::string QDimensionNameQSample (int i)
Get the dimension name when not using reciprocal lattice units.
void setQUnit (const std::vector< size_t > &qDimensionIndices, const Mantid::DataObjects::MDHistoWorkspace_sptr &outputMDHWS)
Set the output Frame to HKL.
void validateBinningForTemporaryDataWorkspace (const std::map< std::string, std::string > &, const Mantid::API::IMDHistoWorkspace_sptr &)
Validates the TemporaryDataWorkspace has the same binning as the input binning parameters.
std::map< std::string, std::string > validateInputs () override final
Validate the input workspace.
Private Attributes
std::string convention
ki-kf for Inelastic convention; kf-ki for Crystallography convention
bool m_accumulate
Flag to accumulate normalization.
API::IMDEventWorkspace_sptr m_backgroundWS
Input background workspace.
Kernel::V3D m_beamDir
Beam direction.
DataObjects::MDHistoWorkspace_sptr m_bkgdNormWS
bool m_dEIntegrated
Flag to indicate that the energy dimension is integrated.
bool m_diffraction
Flag indicating if the input workspace is from diffraction.
double m_Ei
Cached value of incident energy dor direct geometry.
size_t m_eIdx
std::vector< double > m_eX
size_t m_hIdx
index of h,k,l, dE dimensions in the output workspaces
std::vector< double > m_hX
cached X values along dimensions h,k,l. dE
API::IMDEventWorkspace_sptr m_inputWS
Input workspace.
bool m_isRLU
flag for reciprocal lattice units
size_t m_kIdx
std::vector< double > m_kX
size_t m_lIdx
std::vector< double > m_lX
DataObjects::MDHistoWorkspace_sptr m_normWS
Normalization workspace.
size_t m_numExptInfos
number of experimentInfo objects
size_t m_numSymmOps
number of symmetry operations
std::vector< double > m_Q0Basis {1., 0., 0.}
The projection vectors.
std::vector< double > m_Q1Basis {0., 1., 0.}
std::vector< double > m_Q2Basis {0., 0., 1.}
Kernel::V3D m_samplePos
Sample position.
Mantid::Kernel::Matrix< coord_t > m_transformation
matrix for transforming from intersections to positions in the normalization workspace
Mantid::Kernel::DblMatrix m_UB
UB matrix.
Mantid::Kernel::DblMatrix m_W
W matrix.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
MDNormalization : Bin single crystal diffraction or direct geometry inelastic data and calculate the corresponding statistical weight.
Definition at line 21 of file MDNorm.h.
Constructor & Destructor Documentation
MDNorm()
Mantid::MDAlgorithms::MDNorm::MDNorm ()
Constructor.
Definition at line 63 of file MDNorm.cpp.
Member Function Documentation
binBackgroundWS()
DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNorm::binBackgroundWS (const std::vector< Geometry::SymmetryOperation > & symmetryOps) private
Bin(MD) input Background workspace.
Bin(MD) input background MDEventWorkspace.
Parameters
symmetryOps
Returns
Definition at line 1070 of file MDNorm.cpp.
References buildSymmetryMatrix(), Mantid::API::Algorithm::createChildAlgorithm(), determineBasisVector(), getBinParameters(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), m_backgroundWS, m_inputWS, m_isRLU, m_numSymmOps, m_UB, m_W, Mantid::API::NoNormalization, setQUnit(), validateBinningForTemporaryDataWorkspace(), and value.
Referenced by exec().
binInputWS()
DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNorm::binInputWS (const std::vector< Geometry::SymmetryOperation > & symmetryOps) private
Bin(MD) input MDE workspace.
Runs the BinMD algorithm on the input to provide the output workspace All slicing algorithm properties are passed along.
Returns
MDHistoWorkspace as a result of the binning
Definition at line 1170 of file MDNorm.cpp.
References buildSymmetryMatrix(), Mantid::API::Algorithm::createChildAlgorithm(), determineBasisVector(), getBinParameters(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), m_inputWS, m_isRLU, m_UB, m_W, Mantid::API::NoNormalization, setQUnit(), validateBinningForTemporaryDataWorkspace(), and value.
Referenced by exec().
buildSymmetryMatrix()
DblMatrix Mantid::MDAlgorithms::MDNorm::buildSymmetryMatrix (const Geometry::SymmetryOperation & so) inline private
build symmetry matrix
Calculate symmetry operation matrix from Symmetry operation.
Parameters
so :: symmetry operation
Returns
:: matrix
Definition at line 974 of file MDNorm.cpp.
References Mantid::Kernel::Matrix< T >::setColumn(), and Mantid::Geometry::SymmetryOperation::transformHKL().
Referenced by binBackgroundWS(), and binInputWS().
cacheDimensionXValues()
void Mantid::MDAlgorithms::MDNorm::cacheDimensionXValues () private
Stores the X values from each H,K,L, and optionally DeltaE dimension as member variables.
Definition at line 1294 of file MDNorm.cpp.
References m_dEIntegrated, m_diffraction, m_Ei, m_eIdx, m_eX, m_hIdx, m_hX, m_kIdx, m_kX, m_lIdx, m_lX, and m_normWS.
Referenced by exec().
calcDiffractionIntersectionIntegral()
void Mantid::MDAlgorithms::MDNorm::calcDiffractionIntersectionIntegral (std::vector< std::array< double, 4 > > & intersections, std::vector< double > & xValues, std::vector< double > & yValues, const API::MatrixWorkspace & integrFlux, const size_t & wsIdx) inline private
Calculate the diffraction MDE's intersection integral of a certain detector/spectru.
Parameters
intersections vector of intersections
xValues empty vector for X values
yValues empty vector of Y values (output)
integrFlux integral flux workspace
wsIdx workspace index
Definition at line 1357 of file MDNorm.cpp.
References calcIntegralsForIntersections(), and Mantid::Geometry::x.
Referenced by calculateNormalization().
calcIntegralsForIntersections()
void Mantid::MDAlgorithms::MDNorm::calcIntegralsForIntersections (const std::vector< double > & xValues, const API::MatrixWorkspace & integrFlux, size_t sp, std::vector< double > & yValues) private
Linearly interpolate between the points in integrFlux at xValues and save the results in yValues.
Parameters
xValues :: X-values at which to interpolate
integrFlux :: A workspace with the spectra to interpolate
sp :: A workspace index for a spectrum in integrFlux to interpolate.
yValues :: A vector to save the results.
Definition at line 1749 of file MDNorm.cpp.
References Mantid::API::MatrixWorkspace::x(), and Mantid::API::MatrixWorkspace::y().
Referenced by calcDiffractionIntersectionIntegral().
calcSingleDetectorNorm()
void Mantid::MDAlgorithms::MDNorm::calcSingleDetectorNorm (const std::vector< std::array< double, 4 > > & intersections, const double & solid, std::vector< double > & yValues, const size_t & vmdDims, std::vector< coord_t > & pos, std::vector< coord_t > & posNew, std::vector< std::atomic< signal_t > > & signalArray, const double & solidBkgd, std::vector< std::atomic< signal_t > > & bkgdSignalArray) inline private
Calculate the normalization among intersections on a single detector in 1 specific SpectrumInfo/ExperimentInfo.
Parameters
intersections intersections
solid proton charge
yValues diffraction intersection integral and common to sample and background
vmdDims MD dimensions
pos position from intersecton for memory efficiency
posNew transformed positions
signalArray (output) normalization
solidBkgd background proton charge
bkgdSignalArray (output) background normalization
Definition at line 1389 of file MDNorm.cpp.
References Mantid::Kernel::AtomicOp(), Mantid::Kernel::delta, m_backgroundWS, m_diffraction, m_Ei, m_normWS, m_transformation, Mantid::Kernel::Matrix< T >::multiplyPoint(), and rhs.
Referenced by calculateNormalization().
calculateIntersections()
void Mantid::MDAlgorithms::MDNorm::calculateIntersections (std::vector< std::array< double, 4 > > & intersections, const double theta, const double phi, const Kernel::DblMatrix & transform, double lowvalue, double highvalue) private
Calculate the points of intersection for the given detector with cuboid surrounding the detector position in HKL.
Parameters
intersections A list of intersections in HKL space
theta Polar angle withd detector
phi Azimuthal angle with detector
transform Matrix to convert frm Q_lab to HKL (2Pi*R *UB*W*SO)^{-1}
lowvalue The lowest momentum or energy transfer for the trajectory
highvalue The highest momentum or energy transfer for the trajectory
Definition at line 1616 of file MDNorm.cpp.
References convention, fabs, m_dEIntegrated, m_diffraction, m_Ei, m_eX, m_hX, m_kX, m_lX, Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by calculateNormalization().
calculateNormalization()
void Mantid::MDAlgorithms::MDNorm::calculateNormalization (const std::vector< coord_t > & otherValues, const Geometry::SymmetryOperation & so, uint16_t expInfoIndex, size_t soIndex) private
Computed the normalization for the input workspace.
Results are stored in m_normWS
Parameters
otherValues - values for dimensions other than Q or DeltaE
so - symmetry operation
expInfoIndex - current experiment info index
soIndex - the index of symmetry operation (for progress purposes only)
Definition at line 1468 of file MDNorm.cpp.
References calcDiffractionIntersectionIntegral(), calcSingleDetectorNorm(), calculateIntersections(), calQTransform(), Mantid::API::Algorithm::getProperty(), index, m_accumulate, m_backgroundWS, m_beamDir, m_bkgdNormWS, m_diffraction, m_inputWS, m_normWS, m_numExptInfos, m_numSymmOps, m_samplePos, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, and Mantid::Kernel::threadSafe().
Referenced by exec().
calQTransform()
Mantid::Kernel::DblMatrix Mantid::MDAlgorithms::MDNorm::calQTransform (const Mantid::API::ExperimentInfo & currentExpInfo, const Geometry::SymmetryOperation & so) inline private
Calculate QTransform = (R * UB * SymmetryOperation * m_W)^-1.
Parameters
currentExpInfo
so
Returns
Definition at line 1330 of file MDNorm.cpp.
References Mantid::API::Run::getGoniometerMatrix(), Mantid::Kernel::Matrix< T >::Invert(), m_UB, m_W, Mantid::API::ExperimentInfo::run(), Mantid::Kernel::Matrix< T >::setColumn(), and Mantid::Geometry::SymmetryOperation::transformHKL().
Referenced by calculateNormalization().
category()
const std::string Mantid::MDAlgorithms::MDNorm::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 75 of file MDNorm.cpp.
createBackgroundNormalizationWS()
void Mantid::MDAlgorithms::MDNorm::createBackgroundNormalizationWS (const DataObjects::MDHistoWorkspace & dataWS) private
Definition at line 791 of file MDNorm.cpp.
References Mantid::DataObjects::MDHistoWorkspace::clone(), Mantid::API::Algorithm::getProperty(), m_backgroundWS, m_bkgdNormWS, and tmp.
Referenced by exec().
createNormalizationWS()
void Mantid::MDAlgorithms::MDNorm::createNormalizationWS (const DataObjects::MDHistoWorkspace & dataWS) private
Create & cached the normalization workspace.
Parameters
dataWS The binned workspace that will be used for the data
Definition at line 778 of file MDNorm.cpp.
References Mantid::DataObjects::MDHistoWorkspace::clone(), Mantid::API::Algorithm::getProperty(), m_accumulate, m_normWS, and tmp.
Referenced by exec().
determineBasisVector()
void Mantid::MDAlgorithms::MDNorm::determineBasisVector (const size_t & qindex, const std::string & value, const Kernel::DblMatrix & Qtransform, std::vector< double > & projection, std::stringstream & basisVector, std::vector< size_t > & qDimensionIndices) inline private
MDNorm::determineBasisVector.
Parameters
qindex
value
Qtransform
projection
basisVector
qDimensionIndices :: output, Q dimension index mapped to input qindex
Definition at line 999 of file MDNorm.cpp.
References m_dEIntegrated, m_eIdx, m_hIdx, m_isRLU, m_kIdx, m_lIdx, m_Q0Basis, m_Q1Basis, m_Q2Basis, QDimensionName(), QDimensionNameQSample(), and value.
Referenced by binBackgroundWS(), and binInputWS().
divideMD()
API::IMDWorkspace_sptr Mantid::MDAlgorithms::MDNorm::divideMD (const API::IMDHistoWorkspace_sptr & lhs, const API::IMDHistoWorkspace_sptr & rhs, const std::string & outputwsname, const double & startProgress, const double & endProgress) inline private
Definition at line 570 of file MDNorm.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), divideMD(), and rhs.
Referenced by divideMD(), and exec().
exec()
void Mantid::MDAlgorithms::MDNorm::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 447 of file MDNorm.cpp.
References binBackgroundWS(), binInputWS(), cacheDimensionXValues(), calculateNormalization(), convention, createBackgroundNormalizationWS(), Mantid::API::Algorithm::createChildAlgorithm(), createNormalizationWS(), Mantid::Kernel::Logger::debug(), divideMD(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), getValuesFromOtherDimensions(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_accumulate, m_backgroundWS, m_beamDir, m_bkgdNormWS, m_diffraction, m_Ei, m_inputWS, m_isRLU, m_normWS, m_numExptInfos, m_numSymmOps, m_samplePos, Mantid::Kernel::normalize(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::Kernel::Property::value(), and Mantid::Kernel::Logger::warning().
getBinParameters()
std::map< std::string, std::string > Mantid::MDAlgorithms::MDNorm::getBinParameters () private
Calculate binning parameters.
Returns
map of parameters to be passed to BinMD (non axis-aligned)
Definition at line 634 of file MDNorm.cpp.
References Mantid::Geometry::UnitCell::a(), Mantid::Geometry::UnitCell::b(), Mantid::Geometry::UnitCell::c(), Mantid::API::Algorithm::getProperty(), Mantid::PhysicalConstants::h, m_diffraction, m_inputWS, m_isRLU, m_Q0Basis, m_Q1Basis, m_Q2Basis, m_transformation, m_UB, m_W, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::NeutronMass, Mantid::Geometry::OrientedLattice::setUB(), Mantid::Kernel::Strings::toString(), Mantid::Kernel::Matrix< T >::Transpose(), and Mantid::Kernel::Property::value().
Referenced by binBackgroundWS(), and binInputWS().
getValuesFromOtherDimensions()
std::vector< coord_t > Mantid::MDAlgorithms::MDNorm::getValuesFromOtherDimensions (bool & skipNormalization, uint16_t expInfoIndex = 0) const private
Retrieve logged values from non-HKL dimensions.
Parameters
skipNormalization [InOut] Updated to false if any values are outside range measured by input workspace
expInfoIndex current experiment info index
Returns
A vector of values from other dimensions to be include in normalized MD position calculation
Definition at line 1253 of file MDNorm.cpp.
References m_inputWS, m_normWS, m_transformation, Mantid::Kernel::Matrix< T >::numRows(), Mantid::Kernel::Math::TimeAveragedMean, and value.
Referenced by exec().
init()
void Mantid::MDAlgorithms::MDNorm::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 86 of file MDNorm.cpp.
References Mantid::API::CommonBinsValidator::clone(), Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, Mantid::Kernel::IPropertyManager::setPropertyGroup(), Mantid::Kernel::IPropertyManager::setPropertySettings(), and Mantid::Kernel::Strings::toString().
name()
const std::string Mantid::MDAlgorithms::MDNorm::name () const override virtual
Algorithms name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 69 of file MDNorm.cpp.
Referenced by QDimensionName().
QDimensionName()
std::string Mantid::MDAlgorithms::MDNorm::QDimensionName (std::vector< double > projection) private
Get the dimension name when using reciprocal lattice units.
Parameters
projection - a vector with 3 elements, containing a description of the projection ("1,-1,0" for "[H,-H,0]")
Returns
string containing the name
Definition at line 605 of file MDNorm.cpp.
References name().
Referenced by determineBasisVector(), and validateBinningForTemporaryDataWorkspace().
QDimensionNameQSample()
std::string Mantid::MDAlgorithms::MDNorm::QDimensionNameQSample (int i) private
Get the dimension name when not using reciprocal lattice units.
Parameters
i - axis number to return axis name for. Can be 0, 1, or 2.
Returns
string containing the name
Definition at line 589 of file MDNorm.cpp.
Referenced by determineBasisVector(), and validateBinningForTemporaryDataWorkspace().
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::MDNorm::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 28 of file MDNorm.h.
setQUnit()
void Mantid::MDAlgorithms::MDNorm::setQUnit (const std::vector< size_t > & qDimensionIndices, const Mantid::DataObjects::MDHistoWorkspace_sptr & outputMDHWS) inline private
Set the output Frame to HKL.
Parameters
qDimensionIndices
outputMDHWS :: MDHistoWorkspace to set unit to
Definition at line 1049 of file MDNorm.cpp.
References Mantid::Kernel::Matrix< T >::getVector(), Mantid::Geometry::HKL::HKLName, m_W, Mantid::Geometry::makeMDFrameFactoryChain(), and Mantid::Kernel::Units::Symbol::RLU.
Referenced by binBackgroundWS(), and binInputWS().
summary()
const std::string Mantid::MDAlgorithms::MDNorm::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 78 of file MDNorm.cpp.
validateBinningForTemporaryDataWorkspace()
void Mantid::MDAlgorithms::MDNorm::validateBinningForTemporaryDataWorkspace (const std::map< std::string, std::string > & parameters, const Mantid::API::IMDHistoWorkspace_sptr & tempDataWS) private
Validates the TemporaryDataWorkspace has the same binning as the input binning parameters.
Parameters
parameters :: map of binning parameters
tempDataWS :: the workspace weare using to aggregate from
Returns
:: bool - true means the binning is correct to aggreagete using tempDataWS
Definition at line 815 of file MDNorm.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, m_isRLU, m_Q0Basis, m_Q1Basis, m_Q2Basis, QDimensionName(), QDimensionNameQSample(), Mantid::Kernel::VectorHelper::splitStringIntoVector< double >(), Mantid::Kernel::VectorHelper::splitStringIntoVector< size_t >(), value, and Mantid::Kernel::Logger::warning().
Referenced by binBackgroundWS(), and binInputWS().
validateInputs()
std::map< std::string, std::string > Mantid::MDAlgorithms::MDNorm::validateInputs (void) final override private virtual
Validate the input workspace.
See also
Algorithm::validateInputs
Reimplemented from Mantid::API::Algorithm.
Definition at line 213 of file MDNorm.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), fabs, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Geometry::QLab::QLabName, Mantid::Geometry::QSample::QSampleName, Mantid::Kernel::Matrix< T >::setColumn(), and Mantid::Kernel::Strings::toString().
version()
int Mantid::MDAlgorithms::MDNorm::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 72 of file MDNorm.cpp.
Member Data Documentation
convention
std::string Mantid::MDAlgorithms::MDNorm::convention private
ki-kf for Inelastic convention; kf-ki for Crystallography convention
Definition at line 127 of file MDNorm.h.
Referenced by calculateIntersections(), and exec().
m_accumulate
bool Mantid::MDAlgorithms::MDNorm::m_accumulate private
Flag to accumulate normalization.
Definition at line 119 of file MDNorm.h.
Referenced by calculateNormalization(), createNormalizationWS(), and exec().
m_backgroundWS
API::IMDEventWorkspace_sptr Mantid::MDAlgorithms::MDNorm::m_backgroundWS private
Input background workspace.
Definition at line 93 of file MDNorm.h.
Referenced by binBackgroundWS(), calcSingleDetectorNorm(), calculateNormalization(), createBackgroundNormalizationWS(), and exec().
m_beamDir
Kernel::V3D Mantid::MDAlgorithms::MDNorm::m_beamDir private
Beam direction.
Definition at line 125 of file MDNorm.h.
Referenced by calculateNormalization(), and exec().
m_bkgdNormWS
DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNorm::m_bkgdNormWS private
Definition at line 89 of file MDNorm.h.
Referenced by calculateNormalization(), createBackgroundNormalizationWS(), and exec().
m_dEIntegrated
bool Mantid::MDAlgorithms::MDNorm::m_dEIntegrated private
Flag to indicate that the energy dimension is integrated.
Definition at line 121 of file MDNorm.h.
Referenced by cacheDimensionXValues(), calculateIntersections(), and determineBasisVector().
m_diffraction
bool Mantid::MDAlgorithms::MDNorm::m_diffraction private
Flag indicating if the input workspace is from diffraction.
Definition at line 117 of file MDNorm.h.
Referenced by cacheDimensionXValues(), calcSingleDetectorNorm(), calculateIntersections(), calculateNormalization(), exec(), and getBinParameters().
m_Ei
double Mantid::MDAlgorithms::MDNorm::m_Ei private
Cached value of incident energy dor direct geometry.
Definition at line 115 of file MDNorm.h.
Referenced by cacheDimensionXValues(), calcSingleDetectorNorm(), calculateIntersections(), and exec().
m_eIdx
size_t Mantid::MDAlgorithms::MDNorm::m_eIdx private
Definition at line 109 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and determineBasisVector().
m_eX
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_eX private
Definition at line 107 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_hIdx
size_t Mantid::MDAlgorithms::MDNorm::m_hIdx private
index of h,k,l, dE dimensions in the output workspaces
Definition at line 109 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and determineBasisVector().
m_hX
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_hX private
cached X values along dimensions h,k,l. dE
Definition at line 107 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_inputWS
API::IMDEventWorkspace_sptr Mantid::MDAlgorithms::MDNorm::m_inputWS private
Input workspace.
Definition at line 91 of file MDNorm.h.
Referenced by binBackgroundWS(), binInputWS(), calculateNormalization(), exec(), getBinParameters(), and getValuesFromOtherDimensions().
m_isRLU
bool Mantid::MDAlgorithms::MDNorm::m_isRLU private
flag for reciprocal lattice units
Definition at line 96 of file MDNorm.h.
Referenced by binBackgroundWS(), binInputWS(), determineBasisVector(), exec(), getBinParameters(), and validateBinningForTemporaryDataWorkspace().
m_kIdx
size_t Mantid::MDAlgorithms::MDNorm::m_kIdx private
Definition at line 109 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and determineBasisVector().
m_kX
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_kX private
Definition at line 107 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_lIdx
size_t Mantid::MDAlgorithms::MDNorm::m_lIdx private
Definition at line 109 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and determineBasisVector().
m_lX
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_lX private
Definition at line 107 of file MDNorm.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_normWS
DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNorm::m_normWS private
Normalization workspace.
Definition at line 88 of file MDNorm.h.
Referenced by cacheDimensionXValues(), calcSingleDetectorNorm(), calculateNormalization(), createNormalizationWS(), exec(), and getValuesFromOtherDimensions().
m_numExptInfos
size_t Mantid::MDAlgorithms::MDNorm::m_numExptInfos private
number of experimentInfo objects
Definition at line 111 of file MDNorm.h.
Referenced by calculateNormalization(), and exec().
m_numSymmOps
size_t Mantid::MDAlgorithms::MDNorm::m_numSymmOps private
number of symmetry operations
Definition at line 113 of file MDNorm.h.
Referenced by binBackgroundWS(), calculateNormalization(), and exec().
m_Q0Basis
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_Q0Basis {1., 0., 0.} private
The projection vectors.
Definition at line 98 of file MDNorm.h.
Referenced by determineBasisVector(), getBinParameters(), and validateBinningForTemporaryDataWorkspace().
m_Q1Basis
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_Q1Basis {0., 1., 0.} private
Definition at line 98 of file MDNorm.h.
Referenced by determineBasisVector(), getBinParameters(), and validateBinningForTemporaryDataWorkspace().
m_Q2Basis
std::vector<double> Mantid::MDAlgorithms::MDNorm::m_Q2Basis {0., 0., 1.} private
Definition at line 98 of file MDNorm.h.
Referenced by determineBasisVector(), getBinParameters(), and validateBinningForTemporaryDataWorkspace().
m_samplePos
Kernel::V3D Mantid::MDAlgorithms::MDNorm::m_samplePos private
Sample position.
Definition at line 123 of file MDNorm.h.
Referenced by calculateNormalization(), and exec().
m_transformation
Mantid::Kernel::Matrix<coord_t> Mantid::MDAlgorithms::MDNorm::m_transformation private
matrix for transforming from intersections to positions in the normalization workspace
Definition at line 105 of file MDNorm.h.
Referenced by calcSingleDetectorNorm(), getBinParameters(), and getValuesFromOtherDimensions().
m_UB
Mantid::Kernel::DblMatrix Mantid::MDAlgorithms::MDNorm::m_UB private
UB matrix.
Definition at line 100 of file MDNorm.h.
Referenced by binBackgroundWS(), binInputWS(), calQTransform(), and getBinParameters().
m_W
Mantid::Kernel::DblMatrix Mantid::MDAlgorithms::MDNorm::m_W private
W matrix.
Definition at line 102 of file MDNorm.h.
Referenced by binBackgroundWS(), binInputWS(), calQTransform(), getBinParameters(), and setQUnit().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/MDNorm.h
Framework/MDAlgorithms/src/MDNorm.cpp