Mantid: Mantid::Geometry::HKLFilterWavelength Class Reference
Mantid::Geometry::HKLFilterWavelength Class Reference final
HKLFilterWavelength.
#include <HKLFilterWavelength.h>
Public Member Functions
std::string getDescription () const noexcept override
Returns a description for the filter.
HKLFilterWavelength (Kernel::DblMatrix ub, double lambdaMin, double lambdaMax)
Constructor, takes an orientation matrix and lambda min/max.
bool isAllowed (const Kernel::V3D &hkl) const noexcept override
Returns true if lambda of the reflection is within the limits.
Public Member Functions inherited from Mantid::Geometry::HKLFilter
std::function< bool(const Kernel::V3D &)> fn () const noexcept
Returns a function object that wraps HKLFilter::isAllowed.
virtual std::string getDescription () const =0
virtual bool isAllowed (const Kernel::V3D &hkl) const =0
virtual ~HKLFilter ()=default
Protected Member Functions
void checkProperLambdaRangeValues () const
Throws std::range_error exceptions if limits are <= 0 or max >= min.
Protected Attributes
double m_lambdaMax
double m_lambdaMin
Kernel::DblMatrix m_ub
Detailed Description
HKLFilterWavelength.
This implementation of HKLFilter filters reflections by a wavelength- range. The wavelength is calculated from the Q-vector, so the filter requires an orientation matrix.
@author Michael Wedel, ESS
@date 23/10/2015
Definition at line 25 of file HKLFilterWavelength.h.
Constructor & Destructor Documentation
HKLFilterWavelength()
Mantid::Geometry::HKLFilterWavelength::HKLFilterWavelength (Kernel::DblMatrix ub, double lambdaMin, double lambdaMax)
Constructor, takes an orientation matrix and lambda min/max.
Definition at line 17 of file HKLFilterWavelength.cpp.
References checkProperLambdaRangeValues().
Member Function Documentation
checkProperLambdaRangeValues()
void Mantid::Geometry::HKLFilterWavelength::checkProperLambdaRangeValues () const protected
Throws std::range_error exceptions if limits are <= 0 or max >= min.
Definition at line 39 of file HKLFilterWavelength.cpp.
References m_lambdaMax, and m_lambdaMin.
Referenced by HKLFilterWavelength().
getDescription()
std::string Mantid::Geometry::HKLFilterWavelength::getDescription () const override virtual noexcept
Returns a description for the filter.
Implements Mantid::Geometry::HKLFilter.
Definition at line 23 of file HKLFilterWavelength.cpp.
References m_lambdaMax, and m_lambdaMin.
isAllowed()
bool Mantid::Geometry::HKLFilterWavelength::isAllowed (const Kernel::V3D & hkl) const override virtual noexcept
Returns true if lambda of the reflection is within the limits.
Implements Mantid::Geometry::HKLFilter.
Definition at line 31 of file HKLFilterWavelength.cpp.
References lambda, Mantid::Kernel::V3D::norm2(), and Mantid::Kernel::V3D::Z().
Referenced by Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::PredictSatellitePeaks::predictOffsets(), and Mantid::Crystal::PredictSatellitePeaks::predictOffsetsWithCrossTerms().
Member Data Documentation
m_lambdaMax
double Mantid::Geometry::HKLFilterWavelength::m_lambdaMax protected
Definition at line 37 of file HKLFilterWavelength.h.
Referenced by checkProperLambdaRangeValues(), and getDescription().
m_lambdaMin
double Mantid::Geometry::HKLFilterWavelength::m_lambdaMin protected
Definition at line 36 of file HKLFilterWavelength.h.
Referenced by checkProperLambdaRangeValues(), and getDescription().
m_ub
Kernel::DblMatrix Mantid::Geometry::HKLFilterWavelength::m_ub protected
Definition at line 35 of file HKLFilterWavelength.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/HKLFilterWavelength.h
Framework/Geometry/src/Crystal/HKLFilterWavelength.cpp