Mantid: ICat4::ns1__luceneGetPopulatingResponse Class Reference
ICat4::ns1__luceneGetPopulatingResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__luceneGetPopulatingResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< std::string > return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 754 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__luceneGetPopulatingResponse()
ICat4::ns1__luceneGetPopulatingResponse::ns1__luceneGetPopulatingResponse () inline
Definition at line 770 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__luceneGetPopulatingResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19665 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfstd__string().
Referenced by ICat4::ICATPortBindingProxy::luceneGetPopulating(), ICat4::soap_in_ns1__luceneGetPopulatingResponse(), ICat4::soap_new_req_ns1__luceneGetPopulatingResponse(), and ICat4::soap_new_set_ns1__luceneGetPopulatingResponse().
soap_get()
void * ICat4::ns1__luceneGetPopulatingResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19758 of file ICat4C.cpp.
References ICat4::soap_get_ns1__luceneGetPopulatingResponse().
Referenced by ICat4::ICATPortBindingProxy::luceneGetPopulating().
soap_in()
void * ICat4::ns1__luceneGetPopulatingResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19696 of file ICat4C.cpp.
References ICat4::soap_in_ns1__luceneGetPopulatingResponse().
Referenced by ICat4::soap_in_ns1__luceneGetPopulatingResponse().
soap_out()
int ICat4::ns1__luceneGetPopulatingResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19679 of file ICat4C.cpp.
References ICat4::soap_out_ns1__luceneGetPopulatingResponse().
soap_put()
int ICat4::ns1__luceneGetPopulatingResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19751 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__luceneGetPopulatingResponse.
soap_serialize()
void ICat4::ns1__luceneGetPopulatingResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19671 of file ICat4C.cpp.
References ICat4::soap_serialize_std__vectorTemplateOfstd__string().
soap_type()
int ICat4::ns1__luceneGetPopulatingResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 763 of file ICat4Stub.h.
Member Data Documentation
return_
std::vector<std::string> ICat4::ns1__luceneGetPopulatingResponse::return_
Definition at line 756 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp