Mantid: Mantid::Kernel::Units Namespace Reference
Mantid::Kernel::Units Namespace Reference
The namespace for concrete units classes.
Classes
class AtomicDistance
Atomic Distance in Angstroms.
class Degrees
Degrees that has degrees as unit and "Scattering angle" as title.
class DeltaE
Energy transfer in milli-electronvolts.
class DeltaE_inFrequency
Energy transfer in units of frequency (MHz)
class DeltaE_inWavenumber
Energy transfer in units of wavenumber (cm^-1)
class dSpacing
d-Spacing in Angstrom
class dSpacingPerpendicular
d-SpacingPerpendicular in Angstrom
class Empty
Empty unit.
class Energy
Energy in milli-electronvolts.
class Energy_inWavenumber
Absolute energy in units of wavenumber (cm^-1)
class Label
Label unit.
class Momentum
Momentum in Angstrom^-1.
class MomentumTransfer
Momentum Transfer in Angstrom^-1.
class Phi
Phi that has degrees as unit and "Phi" as title.
class QSquared
Momentum transfer squared in Angstrom^-2.
class SpinEchoLength
SpinEchoLength in nm.
class SpinEchoTime
SpinEchoTime in ns.
class Symbol
A simple class containing common symbol types.
class Temperature
Temperature in kelvin.
class Time
Time In Second.
class TOF
Time of flight in microseconds.
class Wavelength
Wavelength in Angstrom.
Functions
MANTID_KERNEL_DLL double calculateDIFCCorrection (const double l1, const double l2, const double twotheta, const double offset, const double binWidth)
Calculate DIFC in case of logarithmic binning, used in CalculateDIFC with Signed mode.
MANTID_KERNEL_DLL double timeConversionValue (const std::string &input_unit, const std::string &output_unit)
template<typename T >
void timeConversionVector (std::vector< T > &vec, const std::string &input_unit, const std::string &output_unit)
MANTID_KERNEL_DLL double tofToDSpacingFactor (const double l1, const double l2, const double twoTheta, const double offset)
Calculate and return conversion factor from tof to d-spacing.
Variables
const double H_OVER_NEUTRON_MASS = (PhysicalConstants::h * 1e10) / (2.0 * PhysicalConstants::NeutronMass * 1e6)
const double NEUTRON_MASS_OVER_H = (PhysicalConstants::NeutronMass * 1e6) / (PhysicalConstants::h * 1e10)
Detailed Description
The namespace for concrete units classes.
Function Documentation
calculateDIFCCorrection()
double Mantid::Kernel::Units::calculateDIFCCorrection (const double l1, const double l2, const double twotheta, const double offset, const double binWidth) private
Calculate DIFC in case of logarithmic binning, used in CalculateDIFC with Signed mode.
Parameters
l1
l2
twotheta scattering angle
offset
binWidth the bin width used in logarithmic binning (DX) Will calculate the value of DIFC following DIFC = (mn/h) * (L1+L2) * 2sin(theta) * (1 + |DX|)^{-offset}
Definition at line 565 of file Unit.cpp.
References fabs, Mantid::Kernel::l2, and NEUTRON_MASS_OVER_H.
Referenced by Mantid::Geometry::Conversion::calculateDIFCCorrection().
timeConversionValue()
double Mantid::Kernel::Units::timeConversionValue (const std::string & input_unit, const std::string & output_unit) private
Definition at line 1430 of file Unit.cpp.
Referenced by Mantid::DataHandling::firstLastPulseTimes(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getCalibrations(), and timeConversionVector().
timeConversionVector()
template<typename T > void Mantid::Kernel::Units::timeConversionVector (std::vector< T > & vec, const std::string & input_unit, const std::string & output_unit) private
Definition at line 661 of file Unit.h.
References timeConversionValue(), vec, and Mantid::Geometry::x.
Referenced by Mantid::DataHandling::LoadBankFromDiskTask::loadTof(), and Mantid::DataHandling::LoadNexusMonitors2::readEventMonitorEntry().
tofToDSpacingFactor()
double Mantid::Kernel::Units::tofToDSpacingFactor (const double l1, const double l2, const double twoTheta, const double offset) private
Calculate and return conversion factor from tof to d-spacing.
Parameters
l1
l2
twoTheta scattering angle
offset
Returns
Definition at line 589 of file Unit.cpp.
References H_OVER_NEUTRON_MASS, Mantid::Kernel::l2, and Mantid::Kernel::twoTheta.
Referenced by Mantid::API::SpectrumInfo::difcUncalibrated(), Mantid::Geometry::DetectorInfo::difcUncalibrated(), Mantid::Kernel::Units::dSpacing::init(), Mantid::Kernel::Units::MomentumTransfer::init(), and Mantid::Geometry::Conversion::tofToDSpacingFactor().
Variable Documentation
H_OVER_NEUTRON_MASS
const double Mantid::Kernel::Units::H_OVER_NEUTRON_MASS = (PhysicalConstants::h * 1e10) / (2.0 * PhysicalConstants::NeutronMass * 1e6)
Definition at line 579 of file Unit.cpp.
Referenced by tofToDSpacingFactor().
NEUTRON_MASS_OVER_H
const double Mantid::Kernel::Units::NEUTRON_MASS_OVER_H = (PhysicalConstants::NeutronMass * 1e6) / (PhysicalConstants::h * 1e10)
Definition at line 553 of file Unit.cpp.
Referenced by calculateDIFCCorrection().