Mantid: Mantid::PythonInterface::Registry Namespace Reference
Mantid::PythonInterface::Registry Namespace Reference
Classes
class MappingTypeHandler
Defines a handler class for converting a Python mapping type object to a C++ PropertyManager type.
struct PropertyValueHandler
This class provides a base-class objects that are able to take a python object and set it on an algorithm property.
class PropertyWithValueFactory
Defines a static factory class that creates PropertyWithValue instances from python objects.
struct RegisterWorkspacePtrToPython
Encapsulates the registration required for an interface type T that sits on top of a Kernel::DataItem object.
struct SequenceTypeHandler
A specialisation of PropertyValueHander to handle coercing a Python value into a C++ sequence/array property.
struct TypedPropertyValueHandler
This class provides a templated class object that is able to take a python object and perform operations with a given C type.
struct TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >
class TypeRegistry
The values that are held within a given C++ property type all have a fixed type, required by static typing.
Functions
std::shared_ptr< Kernel::PropertyManager > createPropertyManager (const boost::python::dict &mapping)
Create a C++ PropertyMananager from a Python dictionary.
Function Documentation
createPropertyManager()
std::shared_ptr< Kernel::PropertyManager > Mantid::PythonInterface::Registry::createPropertyManager (const boost::python::dict & mapping)
Create a C++ PropertyMananager from a Python dictionary.
Parameters
mapping A Python dictionary instance
Returns
A new C++ PropertyManager instance
Definition at line 28 of file PropertyManagerFactory.cpp.
References Mantid::PythonInterface::Registry::PropertyWithValueFactory::create(), Mantid::Kernel::createPropertyManager(), and Mantid::Kernel::Direction::Input.
Referenced by createPropertyManagerPropertyWithDict().