Mantid: Mantid::Kernel::PropertyWithValue< TYPE > Class Template Reference
Mantid::Kernel::PropertyWithValue< TYPE > Class Template Reference
The concrete, templated class for properties.
#include <PropertyWithValue.h>
Public Member Functions
std::vector< std::string > allowedValues () const override
Returns the set of valid values for this property, if such a set exists.
PropertyWithValue< TYPE > * clone () const override
'Virtual copy constructor'
std::string getDefault () const override
Get the value the property was initialised with -its default value.
IValidator_sptr getValidator () const
Returns the validator as a constant variable so it cannot be changed.
bool isDefault () const override
Indicates if the property's value is the same as it was when it was set N.B.
bool isMultipleSelectionAllowed () override
Returns the set of valid values for this property, if such a set exists.
std::string isValid () const override
Check the value chosen for the property is OK, unless overidden it just calls the validator's isValid() N.B.
virtual operator const TYPE & () const
Allows you to get the value of the property simply by typing its name.
bool operator!= (const PropertyWithValue< TYPE > &rhs) const
Deep comparison (not equal).
virtual const TYPE & operator() () const
Allows you to get the value of the property via an expression like myProperty()
PropertyWithValue & operator+= (Property const *right) override
Add the value of another property.
PropertyWithValue & operator= (const PropertyWithValue &right)
Copy assignment operator assigns only the value and the validator not the name, default (initial) value, etc.
virtual PropertyWithValue & operator= (const TYPE &value)
Assignment operator.
bool operator== (const PropertyWithValue< TYPE > &rhs) const
Deep comparison.
PropertyWithValue ()=delete
PropertyWithValue (const PropertyWithValue< TYPE > &right)
Copy constructor Note the default value of the copied object is the initial value of original.
PropertyWithValue (const std::string &name, const TYPE &defaultValue, const std::string &defaultValueStr, IValidator_sptr validator, const unsigned int direction)
Constructor.
PropertyWithValue (std::string name, TYPE defaultValue, const unsigned int direction)
Constructor.
PropertyWithValue (std::string name, TYPE defaultValue, IValidator_sptr validator=IValidator_sptr(new NullValidator), const unsigned int direction=Direction::Input)
Constructor.
virtual void replaceValidator (IValidator_sptr newValidator)
Replace the current validator with the given one.
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
MANTID_KERNEL_DLL void saveProperty (Nexus::File *file)
void saveProperty (Nexus::File *file) override
std::string setDataItem (const std::shared_ptr< DataItem > &data) override
Set a property value via a DataItem.
std::string setValue (const std::string &value) override
Set the value of the property from a string representation.
std::string setValueFromJson (const Json::Value &value) override
Set the value of the property from a Json representation.
int size () const override
Get the size of the property.
std::string value () const override
Get the value of the property as a string.
Json::Value valueAsJson () const override
Attempt to construct a Json::Value object from the plain value.
std::string valueAsPrettyStr (const size_t maxLength=0, const bool collapseLists=true) const override
Get the value of the property as a string.
Public Member Functions inherited from Mantid::Kernel::Property
bool autoTrim () const
Returns if the property is set to automatically trim string unput values of whitespace.
void clearSettings ()
Clears the vector of PropertySettings for this property.
virtual const PropertyHistory createHistory () const
Create a PropertyHistory object representing the current state of the Property.
void createTemporaryValue ()
Create a temporary value for this property.
unsigned int direction () const
returns the direction of the property
bool disableReplaceWSButton () const
Returns if the property is set to disable the creation of the "Replace Workspace" button.
const std::string & documentation () const
Get the property's documentation string.
const std::string & getGroup ()
virtual size_t getMemorySize () const
std::vector< std::unique_ptr< IPropertySettings const > > const & getSettings () const
bool hasTemporaryValue () const
Property is using a temporary value for this property.
bool isDynamicDefault () const
Returns a flag indicating that the property's value has been set programmatically, for example, if the property has a default value which depends on the value of an upstream property.
virtual bool isValueSerializable () const
Whether the string returned by value() can be used for serialization.
virtual Property & merge (Property *)
Just returns the property (*this) unless overridden.
const std::string & name () const
Get the property's name.
bool remember () const
Whether to save input values.
void setAutoTrim (const bool &setting)
Sets if the property is set to automatically trim string unput values of whitespace.
void setDisableReplaceWSButton (const bool &disable)
Sets the property to disable the creation of the "Replace Workspace" button.
void setDocumentation (const std::string &documentation)
Sets the user level description of the property.
void setGroup (const std::string &group)
Set the group this property belongs to.
void setIsDynamicDefault (const bool &flag)
Set or clear the flag indicating whether or not the property's value has been set programmatically.
void setName (const std::string &name)
Set the property's name.
void setRemember (bool)
Set wheter to remeber this property input.
void setSettings (std::unique_ptr< IPropertySettings const > settings)
Set the PropertySettings object.
virtual void setUnits (const std::string &unit)
Sets the units of the property, as a string.
const std::string type () const
Returns the type of the property as a string.
const std::type_info * type_info () const
Get the property type_info.
virtual const std::string & units () const
Returns the units of the property, if any, as a string.
virtual ~Property ()
Virtual destructor.
Protected Attributes
TYPE m_initialValue
the property's default value which is also its initial value
TYPE m_value
The value of the property.
Protected Attributes inherited from Mantid::Kernel::Property
std::string m_name
The name of the property.
Private Member Functions
const TYPE getValueForAlias (const TYPE &alias) const
Return value for a given alias.
template<typename U >
std::string setTypedValue (const U &value, const std::false_type &)
Helper function for setValue(DataItem_sptr).
template<typename U >
std::string setTypedValue (const U &value, const std::true_type &)
Helper function for setValue(DataItem_sptr).
std::string setValueFromProperty (const Property &right) override
Set the value of the property via a reference to another property.
Private Attributes
IValidator_sptr m_validator
Visitor validator class.
Static Private Attributes
static Logger g_logger
Static reference to the logger class.
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Property
Property (const Property &right)
Copy constructor.
Property (std::string name, const std::type_info &type, const unsigned int &direction=Direction::Input)
Constructor.
Detailed Description
template<typename TYPE>
class Mantid::Kernel::PropertyWithValue< TYPE >
The concrete, templated class for properties.
The supported types at present are int, double, bool & std::string.
With reference to the Gaudi structure, this class can be seen as the equivalent of both the Gaudi class of the same name and its sub-classses.
Author
Russell Taylor, Tessella Support Services plc
Based on the Gaudi class of the same name (see http://proj-gaudi.web.cern.ch/proj-gaudi/)
Date
14/11/2007
Definition at line 32 of file PropertyWithValue.h.
Constructor & Destructor Documentation
PropertyWithValue() [1/5]
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue (std::string name, TYPE defaultValue, IValidator_sptr validator = IValidator_sptr(new NullValidator), const unsigned int direction = Direction::Input)
Constructor.
Parameters
name :: The name to assign to the property
defaultValue :: Is stored initial default value of the property
validator :: The validator to use for this property
direction :: Whether this is a Direction::Input, Direction::Output or Direction::InOut (Input & Output) property
Definition at line 44 of file PropertyWithValue.hxx.
PropertyWithValue() [2/5]
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue (std::string name, TYPE defaultValue, const unsigned int direction)
Constructor.
Parameters
name :: The name to assign to the property
defaultValue :: Is stored initial default value of the property
direction :: Whether this is a Direction::Input, Direction::Output or Direction::InOut (Input & Output) property
Definition at line 56 of file PropertyWithValue.hxx.
PropertyWithValue() [3/5]
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue (const std::string & name, const TYPE & defaultValue, const std::string & defaultValueStr, IValidator_sptr validator, const unsigned int direction)
Constructor.
Parameters
name :: The name to assign to the property.
defaultValue :: A vector of numerical type, empty to comply with other definitions.
defaultValueStr :: The numerical values you wish to assign to the property
validator :: The validator to use for this property
direction :: Whether this is a Direction::Input, Direction::Output or Direction::InOut (Input & Output) property
Definition at line 75 of file PropertyWithValue.hxx.
PropertyWithValue() [4/5]
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue (const PropertyWithValue< TYPE > & right)
Copy constructor Note the default value of the copied object is the initial value of original.
Definition at line 88 of file PropertyWithValue.hxx.
PropertyWithValue() [5/5]
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue () delete
References Mantid::API::operator+=().
Member Function Documentation
allowedValues()
template<typename TYPE > std::vector< std::string > Mantid::Kernel::PropertyWithValue< TYPE >::allowedValues () const override virtual
Returns the set of valid values for this property, if such a set exists.
If not, it returns an empty vector.
Returns
Returns the set of valid values for this property, or it returns an empty vector.
Reimplemented from Mantid::Kernel::Property.
Definition at line 318 of file PropertyWithValue.hxx.
References Mantid::Kernel::determineAllowedValues(), m_validator, and m_value.
Referenced by MantidQt::API::FileFinderWidget::getFileExtensionsFromAlgorithm().
clone()
template<typename TYPE > PropertyWithValue< TYPE > * Mantid::Kernel::PropertyWithValue< TYPE >::clone () const override virtual
'Virtual copy constructor'
Implements Mantid::Kernel::Property.
Definition at line 94 of file PropertyWithValue.hxx.
getDefault()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::getDefault () const override virtual
Get the value the property was initialised with -its default value.
Returns
The default value
Implements Mantid::Kernel::Property.
Definition at line 159 of file PropertyWithValue.hxx.
References Mantid::Kernel::toString().
getValidator()
template<typename TYPE > IValidator_sptr Mantid::Kernel::PropertyWithValue< TYPE >::getValidator () const
Returns the validator as a constant variable so it cannot be changed.
Template Parameters
TYPE :: The type of the property value
Returns
IValidator_sptr :: the validator
Definition at line 412 of file PropertyWithValue.hxx.
References m_validator.
getValueForAlias()
template<typename TYPE > const TYPE Mantid::Kernel::PropertyWithValue< TYPE >::getValueForAlias (const TYPE & alias) const private
Return value for a given alias.
Parameters
alias :: An alias for a value. If a value cannot be found throw an invalid_argument exception.
Returns
:: A value.
Definition at line 400 of file PropertyWithValue.hxx.
References m_validator, Mantid::Kernel::toString(), and Mantid::Kernel::toValue().
isDefault()
template<typename TYPE > bool Mantid::Kernel::PropertyWithValue< TYPE >::isDefault () const override virtual
Indicates if the property's value is the same as it was when it was set N.B.
Uses an unsafe comparison in the case of doubles, consider overriding if the value is a pointer or floating point type
Returns
true if the value is the same as the initial value or false otherwise
Implements Mantid::Kernel::Property.
Definition at line 311 of file PropertyWithValue.hxx.
References m_value.
isMultipleSelectionAllowed()
template<typename TYPE > bool Mantid::Kernel::PropertyWithValue< TYPE >::isMultipleSelectionAllowed () override virtual
Returns the set of valid values for this property, if such a set exists.
If not, it returns an empty vector.
Returns
Returns the set of valid values for this property, or it returns an empty vector.
Reimplemented from Mantid::Kernel::Property.
Definition at line 327 of file PropertyWithValue.hxx.
References m_validator.
isValid()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::isValid () const override virtual
Check the value chosen for the property is OK, unless overidden it just calls the validator's isValid() N.B.
Problems found in validator are written to the log if you this function to do checking outside a validator may want to do more logging
Returns
"" if the value is valid or a discription of the problem
Reimplemented from Mantid::Kernel::Property.
Definition at line 303 of file PropertyWithValue.hxx.
References Mantid::Kernel::PropertyWithValue< TYPE >::isValid(), m_validator, and m_value.
Referenced by Mantid::API::FileProperty::isValid(), Mantid::Kernel::PropertyWithValue< TYPE >::isValid(), and Mantid::Algorithms::ExtractMaskToTable::parseStringToVector().
operator const TYPE &()
template<typename TYPE > Mantid::Kernel::PropertyWithValue< TYPE >::operator const TYPE & () const virtual
Allows you to get the value of the property simply by typing its name.
Means you can use an expression like: int i = myProperty;
Returns
the value
Definition at line 294 of file PropertyWithValue.hxx.
References m_value.
operator!=()
template<typename TYPE > bool Mantid::Kernel::PropertyWithValue< TYPE >::operator!= (const PropertyWithValue< TYPE > & rhs) const
Deep comparison (not equal).
Parameters
rhs The other property to compare to.
Returns
true if the are not equal.
Definition at line 148 of file PropertyWithValue.hxx.
References rhs.
operator()()
template<typename TYPE > const TYPE & Mantid::Kernel::PropertyWithValue< TYPE >::operator() () const virtual
Allows you to get the value of the property via an expression like myProperty()
Returns
the value of the property
Definition at line 288 of file PropertyWithValue.hxx.
References m_value.
operator+=()
template<typename TYPE > PropertyWithValue< TYPE > & Mantid::Kernel::PropertyWithValue< TYPE >::operator+= (Property const * right) override virtual
Add the value of another property.
Parameters
right the property to add
Returns
the sum
Implements Mantid::Kernel::Property.
Definition at line 238 of file PropertyWithValue.hxx.
References Mantid::Kernel::addingOperator(), m_value, name, rhs, and right.
operator=() [1/2]
template<typename TYPE > PropertyWithValue< TYPE > & Mantid::Kernel::PropertyWithValue< TYPE >::operator= (const PropertyWithValue< TYPE > & right)
Copy assignment operator assigns only the value and the validator not the name, default (initial) value, etc.
Definition at line 225 of file PropertyWithValue.hxx.
References m_validator, m_value, Mantid::Kernel::PropertyWithValue< TYPE >::m_value, and right.
operator=() [2/2]
template<typename TYPE > PropertyWithValue< TYPE > & Mantid::Kernel::PropertyWithValue< TYPE >::operator= (const TYPE & value) virtual
Assignment operator.
Allows assignment of a new value to the property by writing, e.g., myProperty = 3;
Parameters
value :: The new value to assign to the property
Returns
the reference to itself
Reimplemented in Mantid::API::FunctionProperty, and Mantid::PythonInterface::PythonObjectProperty.
Definition at line 261 of file PropertyWithValue.hxx.
References m_value, name, Mantid::Kernel::toString(), Mantid::Kernel::toValue(), and value.
operator==()
template<typename TYPE > bool Mantid::Kernel::PropertyWithValue< TYPE >::operator== (const PropertyWithValue< TYPE > & rhs) const
Deep comparison.
Parameters
rhs The other property to compare to.
Returns
true if the are equal.
Definition at line 137 of file PropertyWithValue.hxx.
References m_value, name, Mantid::Kernel::Property::name(), and rhs.
replaceValidator()
template<typename TYPE > void Mantid::Kernel::PropertyWithValue< TYPE >::replaceValidator (IValidator_sptr newValidator) virtual
Replace the current validator with the given one.
Parameters
newValidator :: A replacement validator
Definition at line 335 of file PropertyWithValue.hxx.
References m_validator.
saveProperty() [1/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< float >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [2/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< double >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [3/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< int32_t >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [4/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< uint32_t >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [5/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< int64_t >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [6/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< uint64_t >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [7/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< std::string >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [8/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< std::vector< double > >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [9/10]
MANTID_KERNEL_DLL void Mantid::Kernel::PropertyWithValue< std::vector< int32_t > >::saveProperty (Nexus::File * file) virtual
Reimplemented from Mantid::Kernel::Property.
saveProperty() [10/10]
template<typename TYPE > void Mantid::Kernel::PropertyWithValue< TYPE >::saveProperty (Nexus::File * file) override virtual
Reimplemented from Mantid::Kernel::Property.
Definition at line 98 of file PropertyWithValue.hxx.
References name.
setDataItem()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setDataItem (const std::shared_ptr< DataItem > & data) override virtual
Set a property value via a DataItem.
Parameters
data :: A shared pointer to a data item
Returns
"" if the assignment was successful or a user level description of the problem
Implements Mantid::Kernel::Property.
Definition at line 215 of file PropertyWithValue.hxx.
setTypedValue() [1/2]
template<typename TYPE > template<typename U > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setTypedValue (const U & value, const std::false_type &) private
Helper function for setValue(DataItem_sptr).
Uses boost type traits to ensure it is only used if U is NOT a type that is convertible to std::shared_ptr<DataItem>
Parameters
value :: A object of type convertible to std::shared_ptr<DataItem>
Definition at line 390 of file PropertyWithValue.hxx.
References name, UNUSED_ARG, and value.
setTypedValue() [2/2]
template<typename TYPE > template<typename U > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setTypedValue (const U & value, const std::true_type &) private
Helper function for setValue(DataItem_sptr).
Uses boost type traits to ensure it is only used if U is a type that is convertible to std::shared_ptr<DataItem>
Parameters
value :: A object of type convertible to std::shared_ptr<DataItem>
Definition at line 365 of file PropertyWithValue.hxx.
References name, and value.
setValue()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setValue (const std::string & value) override virtual
Set the value of the property from a string representation.
Note that "1" & "0" must be used for bool properties rather than true/false.
Parameters
value :: The value to assign to the property
Returns
Returns "" if the assignment was successful or a user level description of the problem
Implements Mantid::Kernel::Property.
Definition at line 168 of file PropertyWithValue.hxx.
References error, m_value, name, Mantid::Kernel::toValue(), and value.
Referenced by Mantid::API::FileProperty::setLoadProperty(), Mantid::API::FileProperty::setSaveProperty(), Mantid::API::FileProperty::setValue(), and Mantid::Algorithms::ChangeTimeZero::shiftTimeOfLogForStringProperty().
setValueFromJson()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setValueFromJson (const Json::Value & value) override virtual
Set the value of the property from a Json representation.
Parameters
value :: The value to assign to the property
Returns
Returns "" if the assignment was successful or a user level description of the problem
Implements Mantid::Kernel::Property.
Definition at line 196 of file PropertyWithValue.hxx.
References value.
setValueFromProperty()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::setValueFromProperty (const Property & right) override private virtual
Set the value of the property via a reference to another property.
If the value is unacceptable the value is not changed but a string is returned. The value is only accepted if the other property has the same type as this
Parameters
right :: A reference to a property.
Implements Mantid::Kernel::Property.
Definition at line 346 of file PropertyWithValue.hxx.
References m_value, and right.
size()
template<typename TYPE > int Mantid::Kernel::PropertyWithValue< TYPE >::size () const override virtual
Get the size of the property.
Reimplemented from Mantid::Kernel::Property.
Definition at line 154 of file PropertyWithValue.hxx.
References Mantid::Kernel::findSize(), and m_value.
Referenced by Mantid::Algorithms::MaskBinsFromTable::convertToSpectraList(), and Mantid::Algorithms::ExtractMaskToTable::parseStringToVector().
value()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::value () const override virtual
Get the value of the property as a string.
Returns
The property's value
Implements Mantid::Kernel::Property.
Definition at line 109 of file PropertyWithValue.hxx.
References m_value, and Mantid::Kernel::toString().
Referenced by Mantid::Algorithms::ChangeTimeZero::shiftTimeOfLogForStringProperty().
valueAsJson()
template<typename TYPE > Json::Value Mantid::Kernel::PropertyWithValue< TYPE >::valueAsJson () const override virtual
Attempt to construct a Json::Value object from the plain value.
Returns
A new Json::Value object
Implements Mantid::Kernel::Property.
Definition at line 130 of file PropertyWithValue.hxx.
References Mantid::Kernel::encodeAsJson().
valueAsPrettyStr()
template<typename TYPE > std::string Mantid::Kernel::PropertyWithValue< TYPE >::valueAsPrettyStr (const size_t maxLength = 0, const bool collapseLists = true) const override virtual
Get the value of the property as a string.
Returns
The property's value
Reimplemented from Mantid::Kernel::Property.
Definition at line 115 of file PropertyWithValue.hxx.
References m_value, Mantid::Kernel::Strings::shorten(), Mantid::Kernel::toPrettyString(), and value.
Member Data Documentation
g_logger
template<typename TYPE > Logger Mantid::Kernel::PropertyWithValue< TYPE >::g_logger static private
Static reference to the logger class.
Definition at line 86 of file PropertyWithValue.h.
m_initialValue
template<typename TYPE > TYPE Mantid::Kernel::PropertyWithValue< TYPE >::m_initialValue protected
the property's default value which is also its initial value
Definition at line 71 of file PropertyWithValue.h.
m_validator
template<typename TYPE > IValidator_sptr Mantid::Kernel::PropertyWithValue< TYPE >::m_validator private
Visitor validator class.
Definition at line 83 of file PropertyWithValue.h.
m_value
template<typename TYPE > TYPE Mantid::Kernel::PropertyWithValue< TYPE >::m_value protected
The value of the property.
Definition at line 68 of file PropertyWithValue.h.
Referenced by Mantid::API::IndexProperty::getFilteredIndexInfo(), Mantid::API::IndexProperty::getIndices(), Mantid::API::IndexProperty::isDefault(), and Mantid::Kernel::PropertyWithValue< TYPE >::operator=().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/PropertyWithValue.h
Framework/Kernel/inc/MantidKernel/PropertyWithValue.hxx