Mantid: Mantid::DataObjects::BasePeak Class Reference
Mantid::DataObjects::BasePeak Class Reference
Structure describing a single-crystal peak.
#include <BasePeak.h>
Public Member Functions
BasePeak ()
Default constructor.
BasePeak (BasePeak &&) noexcept=default
BasePeak (const BasePeak &other)
Copy constructor.
BasePeak (const Geometry::IPeak &ipeak)
Constructor making a LeanPeak from IPeak interface.
BasePeak (const Mantid::Kernel::Matrix< double > &goniometer)
Constructor including goniometer.
double getAbsorptionWeightedPathLength () const override
Gets the absorption weighted path length.
double getBinCount () const override
Return the # of counts in the bin at its peak.
Mantid::Kernel::Matrix< double > getGoniometerMatrix () const override
Get the goniometer rotation matrix at which this peak was measured.
double getH () const override
Get the H index of the peak.
Mantid::Kernel::V3D getHKL () const override
Return the HKL vector.
double getIntensity () const override
Return the integrated peak intensity.
double getIntensityOverSigma () const override
Return the peak intensity divided by the error in the intensity.
Mantid::Kernel::V3D getIntHKL () const override
Return the int HKL vector.
Mantid::Kernel::V3D getIntMNP () const override
Return the int MNP vector.
Mantid::Kernel::Matrix< double > getInverseGoniometerMatrix () const
Get the goniometer rotation matrix at which this peak was measured.
double getK () const override
Get the K index of the peak.
double getL () const override
Get the L index of the peak.
double getMonitorCount () const override
Return the monitor count stored in this peak.
int getPeakNumber () const override
Returns the unique peak number Returns -1 if it could not find it.
const Mantid::Geometry::PeakShape & getPeakShape () const override
Get the peak shape.
int getRunNumber () const override
Return the run number this peak was measured at.
Mantid::Kernel::V3D getSamplePos () const override
Return the sample position vector.
double getSigmaIntensity () const override
Return the error on the integrated peak intensity.
virtual double getValueByColName (std::string colName) const
Helper function for displaying/sorting peaks.
bool isIndexed () const override
Return True if the peak has been indexed.
BasePeak & operator= (BasePeak &&) noexcept=default
BasePeak & operator= (const BasePeak &other)
Assignment.
void setAbsorptionWeightedPathLength (double pathLength) override
Set the absorption weighted path length.
void setBinCount (double m_binCount) override
Set the # of counts in the bin at its peak.
void setGoniometerMatrix (const Mantid::Kernel::Matrix< double > &goniometerMatrix) override
Set the goniometer rotation matrix at which this peak was measured.
void setH (double m_H) override
Set the H index of this peak.
void setHKL (const Mantid::Kernel::V3D &HKL) override
Set all HKL.
void setHKL (double H, double K, double L) override
Set all three H,K,L indices of the peak.
void setIntensity (double m_intensity) override
Set the integrated peak intensity.
void setIntHKL (const Kernel::V3D &HKL) override
Set int HKL.
void setIntMNP (const Mantid::Kernel::V3D &MNP) override
Sets the modulated peak structure number.
void setK (double m_K) override
Set the K index of this peak.
void setL (double m_L) override
Set the L index of this peak.
void setMonitorCount (double m_monitorCount) override
Set the monitor count for this peak.
void setPeakNumber (int m_peakNumber) override
Sets the unique peak number.
void setPeakShape (Mantid::Geometry::PeakShape *shape) override
Set the PeakShape.
void setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape) override
Set the PeakShape.
void setRunNumber (int m_runNumber) override
Set the run number that measured this peak.
void setSamplePos (const Mantid::Kernel::V3D &XYZ) override
Set sample position.
void setSamplePos (double samX, double samY, double samZ) override
Set sample position.
void setSigmaIntensity (double m_sigmaIntensity) override
Set the error on the integrated peak intensity.
Public Member Functions inherited from Mantid::Geometry::IPeak
virtual double getAzimuthal () const =0
virtual int getCol () const =0
virtual Mantid::Kernel::V3D getDetectorDirectionSampleFrame () const =0
virtual int getDetectorID () const =0
virtual double getDSpacing () const =0
virtual double getEnergyTransfer () const =0
virtual double getFinalEnergy () const =0
virtual double getInitialEnergy () const =0
virtual double getL1 () const =0
virtual double getL2 () const =0
virtual Mantid::Kernel::V3D getQLabFrame () const =0
virtual Mantid::Kernel::V3D getQSampleFrame () const =0
virtual std::shared_ptr< const Geometry::ReferenceFrame > getReferenceFrame () const =0
virtual int getRow () const =0
virtual double getScattering () const =0
virtual Mantid::Kernel::V3D getSourceDirectionSampleFrame () const =0
virtual double getTOF () const =0
virtual double getWavelength () const =0
virtual void setFinalEnergy (double m_FinalEnergy)=0
virtual void setInitialEnergy (double m_InitialEnergy)=0
virtual void setQLabFrame (const Mantid::Kernel::V3D &QLabFrame, std::optional< double > detectorDistance)=0
virtual void setQSampleFrame (const Mantid::Kernel::V3D &QSampleFrame, std::optional< double > detectorDistance)=0
virtual void setWavelength (double wavelength)=0
virtual ~IPeak ()=default
Protected Member Functions
double calculateWavelengthFromQLab (const Mantid::Kernel::V3D &qLab)
Protected Attributes
std::string m_convention
Mantid::Kernel::V3D m_samplePos
Cached sample position.
Private Attributes
double m_absorptionWeightedPathLength
absorption weighted path length (aka t bar)
double m_binCount
Count in the bin at the peak.
Mantid::Kernel::Matrix< double > m_GoniometerMatrix
Orientation matrix of the goniometer angles.
double m_H
H of the peak.
double m_intensity
Integrated peak intensity.
Mantid::Kernel::V3D m_intHKL
Mantid::Kernel::V3D m_intMNP
Mantid::Kernel::Matrix< double > m_InverseGoniometerMatrix
Inverse of the goniometer rotation matrix; used to go from Q in lab frame to Q in sample frame.
double m_K
K of the peak.
double m_L
L of the peak.
double m_monitorCount
Integrated monitor count over TOF range for this run.
int m_peakNumber
Mantid::Geometry::PeakShape_const_sptr m_peakShape
Peak shape.
int m_runNumber
Originating run number for this peak.
double m_sigmaIntensity
Error (sigma) on peak intensity.
Static Private Attributes
static Mantid::Kernel::Logger g_log
Static logger.
Detailed Description
Structure describing a single-crystal peak.
This is a partial implementation of IPeak and should contain everything that is common to Peak and LeanPeak.
Definition at line 33 of file BasePeak.h.
Constructor & Destructor Documentation
BasePeak() [1/5]
Mantid::DataObjects::BasePeak::BasePeak ()
Default constructor.
Definition at line 30 of file BasePeak.cpp.
BasePeak() [2/5]
Mantid::DataObjects::BasePeak::BasePeak (const Mantid::Kernel::Matrix< double > & goniometer)
Constructor including goniometer.
Parameters
goniometer :: a 3x3 rotation matrix
Definition at line 41 of file BasePeak.cpp.
References fabs, Mantid::Kernel::Matrix< T >::Invert(), and m_InverseGoniometerMatrix.
BasePeak() [3/5]
Mantid::DataObjects::BasePeak::BasePeak (const BasePeak & other)
Copy constructor.
Definition at line 50 of file BasePeak.cpp.
BasePeak() [4/5]
Mantid::DataObjects::BasePeak::BasePeak (BasePeak &&) default noexcept
BasePeak() [5/5]
Mantid::DataObjects::BasePeak::BasePeak (const Geometry::IPeak & ipeak) explicit
Constructor making a LeanPeak from IPeak interface.
Parameters
ipeak :: const reference to an IPeak object
Definition at line 63 of file BasePeak.cpp.
References fabs, Mantid::Kernel::Matrix< T >::Invert(), and m_InverseGoniometerMatrix.
Member Function Documentation
calculateWavelengthFromQLab()
double Mantid::DataObjects::BasePeak::calculateWavelengthFromQLab (const Mantid::Kernel::V3D & qLab) protected
Definition at line 349 of file BasePeak.cpp.
References Mantid::Geometry::IPeak::getReferenceFrame(), m_convention, Mantid::Kernel::V3D::norm(), and Mantid::Kernel::V3D::scalar_prod().
Referenced by Mantid::DataObjects::LeanElasticPeak::setQSampleFrame().
getAbsorptionWeightedPathLength()
double Mantid::DataObjects::BasePeak::getAbsorptionWeightedPathLength () const override virtual
Gets the absorption weighted path length.
Implements Mantid::Geometry::IPeak.
Definition at line 347 of file BasePeak.cpp.
References m_absorptionWeightedPathLength.
Referenced by Mantid::Crystal::SaveHKL::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getBinCount()
double Mantid::DataObjects::BasePeak::getBinCount () const override virtual
Return the # of counts in the bin at its peak.
Implements Mantid::Geometry::IPeak.
Definition at line 181 of file BasePeak.cpp.
References m_binCount.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SCDCalibratePanels::findL2(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getGoniometerMatrix()
Mantid::Kernel::Matrix< double > Mantid::DataObjects::BasePeak::getGoniometerMatrix () const override virtual
Get the goniometer rotation matrix at which this peak was measured.
Implements Mantid::Geometry::IPeak.
Definition at line 209 of file BasePeak.cpp.
References m_GoniometerMatrix.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Crystal::SCDPanelErrors::eval(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::exec(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::DataObjects::LeanElasticPeak::getQLabFrame(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), Mantid::DataObjects::PeaksWorkspace::saveNexus(), and Mantid::DataObjects::Peak::setQSampleFrame().
getH()
double Mantid::DataObjects::BasePeak::getH () const override virtual
Get the H index of the peak.
Implements Mantid::Geometry::IPeak.
Definition at line 93 of file BasePeak.cpp.
References m_H.
Referenced by Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SCDPanelErrors::eval(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getHKL()
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::getHKL () const override virtual
Return the HKL vector.
Implements Mantid::Geometry::IPeak.
Definition at line 102 of file BasePeak.cpp.
References m_H, m_K, and m_L.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Crystal::SaveHKL::exec(), and Mantid::Crystal::SCDCalibratePanels::exec().
getIntensity()
double Mantid::DataObjects::BasePeak::getIntensity () const override virtual
Return the integrated peak intensity.
Implements Mantid::Geometry::IPeak.
Definition at line 184 of file BasePeak.cpp.
References m_intensity.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::findL2(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getIntensityOverSigma()
double Mantid::DataObjects::BasePeak::getIntensityOverSigma () const override virtual
Return the peak intensity divided by the error in the intensity.
Implements Mantid::Geometry::IPeak.
Definition at line 190 of file BasePeak.cpp.
References m_intensity, and m_sigmaIntensity.
Referenced by getValueByColName().
getIntHKL()
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::getIntHKL () const override virtual
Return the int HKL vector.
Implements Mantid::Geometry::IPeak.
Definition at line 112 of file BasePeak.cpp.
References m_intHKL.
Referenced by Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SaveHKL::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getIntMNP()
V3D Mantid::DataObjects::BasePeak::getIntMNP () const override virtual
Return the int MNP vector.
Implements Mantid::Geometry::IPeak.
Definition at line 115 of file BasePeak.cpp.
References m_intMNP.
Referenced by Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getInverseGoniometerMatrix()
Mantid::Kernel::Matrix< double > Mantid::DataObjects::BasePeak::getInverseGoniometerMatrix () const
Get the goniometer rotation matrix at which this peak was measured.
Definition at line 213 of file BasePeak.cpp.
References m_InverseGoniometerMatrix.
Referenced by Mantid::DataObjects::Peak::getDetectorDirectionSampleFrame(), Mantid::DataObjects::Peak::getQSampleFrame(), Mantid::DataObjects::LeanElasticPeak::getSourceDirectionSampleFrame(), Mantid::DataObjects::Peak::getSourceDirectionSampleFrame(), and Mantid::DataObjects::LeanElasticPeak::setQLabFrame().
getK()
double Mantid::DataObjects::BasePeak::getK () const override virtual
Get the K index of the peak.
Implements Mantid::Geometry::IPeak.
Definition at line 96 of file BasePeak.cpp.
References m_K.
Referenced by Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SCDPanelErrors::eval(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getL()
double Mantid::DataObjects::BasePeak::getL () const override virtual
Get the L index of the peak.
Implements Mantid::Geometry::IPeak.
Definition at line 99 of file BasePeak.cpp.
References m_L.
Referenced by Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SCDPanelErrors::eval(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getMonitorCount()
double Mantid::DataObjects::BasePeak::getMonitorCount () const override virtual
Return the monitor count stored in this peak.
Implements Mantid::Geometry::IPeak.
Definition at line 85 of file BasePeak.cpp.
References m_monitorCount.
Referenced by Mantid::Crystal::SaveHKL::exec().
getPeakNumber()
int Mantid::DataObjects::BasePeak::getPeakNumber () const override virtual
Returns the unique peak number Returns -1 if it could not find it.
Implements Mantid::Geometry::IPeak.
Definition at line 233 of file BasePeak.cpp.
References m_peakNumber.
Referenced by Mantid::Crystal::SaveHKL::exec(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getPeakShape()
const PeakShape & Mantid::DataObjects::BasePeak::getPeakShape () const override virtual
Get the peak shape.
Returns
: const ref to current peak shape.
Implements Mantid::Geometry::IPeak.
Definition at line 297 of file BasePeak.cpp.
References m_peakShape.
Referenced by Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getRunNumber()
int Mantid::DataObjects::BasePeak::getRunNumber () const override virtual
Return the run number this peak was measured at.
Implements Mantid::Geometry::IPeak.
Definition at line 77 of file BasePeak.cpp.
References m_runNumber.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createOutputs(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::ShowPeakHKLOffsets::exec(), Mantid::Crystal::StatisticsOfPeaksWorkspace::exec(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getPeakInformation(), getValueByColName(), Mantid::Crystal::CentroidPeaks::integrate(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getSamplePos()
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::getSamplePos () const override virtual
Return the sample position vector.
Implements Mantid::Geometry::IPeak.
Definition at line 155 of file BasePeak.cpp.
References m_samplePos.
Referenced by Mantid::Crystal::PeakHKLErrors::function1D(), and Mantid::Crystal::PeakHKLErrors::functionDeriv1D().
getSigmaIntensity()
double Mantid::DataObjects::BasePeak::getSigmaIntensity () const override virtual
Return the error on the integrated peak intensity.
Implements Mantid::Geometry::IPeak.
Definition at line 187 of file BasePeak.cpp.
References m_sigmaIntensity.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::findL2(), getValueByColName(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
getValueByColName()
double Mantid::DataObjects::BasePeak::getValueByColName (std::string name) const virtual
Helper function for displaying/sorting peaks.
Parameters
name :: name of the column in the table workspace. The matching is case-insensitive.
Returns
a double representing that value (if that's possible)
Exceptions
std::runtime_error if you asked for a column that can't convert to double.
Reimplemented in Mantid::DataObjects::Peak.
Definition at line 249 of file BasePeak.cpp.
References getAbsorptionWeightedPathLength(), getBinCount(), Mantid::Geometry::IPeak::getDSpacing(), getH(), Mantid::Geometry::IPeak::getInitialEnergy(), getIntensity(), getIntensityOverSigma(), getIntHKL(), getIntMNP(), getK(), getL(), getPeakNumber(), Mantid::Geometry::IPeak::getQLabFrame(), Mantid::Geometry::IPeak::getQSampleFrame(), getRunNumber(), getSigmaIntensity(), Mantid::Geometry::IPeak::getTOF(), Mantid::Geometry::IPeak::getWavelength(), name, and Mantid::Kernel::V3D::norm2().
Referenced by Mantid::DataObjects::Peak::getValueByColName(), and Mantid::DataObjects::PeakComparator::operator()().
isIndexed()
bool Mantid::DataObjects::BasePeak::isIndexed () const override virtual
Return True if the peak has been indexed.
Implements Mantid::Geometry::IPeak.
Definition at line 105 of file BasePeak.cpp.
References m_H, m_K, and m_L.
operator=() [1/2]
BasePeak & Mantid::DataObjects::BasePeak::operator= (BasePeak &&) default noexcept
Referenced by Mantid::DataObjects::LeanElasticPeak::operator=(), and Mantid::DataObjects::Peak::operator=().
operator=() [2/2]
BasePeak & Mantid::DataObjects::BasePeak::operator= (const BasePeak & other)
Assignment.
Assignement operator overload.
Parameters
other : Other peak object to assign from
Returns
this
Definition at line 316 of file BasePeak.cpp.
References m_absorptionWeightedPathLength, m_binCount, m_convention, m_GoniometerMatrix, m_H, m_intensity, m_intHKL, m_intMNP, m_InverseGoniometerMatrix, m_K, m_L, m_monitorCount, m_peakNumber, m_peakShape, m_runNumber, and m_sigmaIntensity.
setAbsorptionWeightedPathLength()
void Mantid::DataObjects::BasePeak::setAbsorptionWeightedPathLength (double pathLength) override virtual
Set the absorption weighted path length.
Parameters
pathLength : Desired path length
Implements Mantid::Geometry::IPeak.
Definition at line 342 of file BasePeak.cpp.
References m_absorptionWeightedPathLength.
setBinCount()
void Mantid::DataObjects::BasePeak::setBinCount (double m_binCount) override virtual
Set the # of counts in the bin at its peak.
Parameters
m_binCount :: counts
Implements Mantid::Geometry::IPeak.
Definition at line 201 of file BasePeak.cpp.
References m_binCount.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
setGoniometerMatrix()
void Mantid::DataObjects::BasePeak::setGoniometerMatrix (const Mantid::Kernel::Matrix< double > & goniometerMatrix) override virtual
Set the goniometer rotation matrix at which this peak was measured.
Parameters
goniometerMatrix :: 3x3 matrix that represents the rotation matrix of the goniometer
Exceptions
std::invalid_argument if matrix is not 3x3
Implements Mantid::Geometry::IPeak.
Definition at line 219 of file BasePeak.cpp.
References fabs, Mantid::Kernel::Matrix< T >::Invert(), m_GoniometerMatrix, m_InverseGoniometerMatrix, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
Referenced by Mantid::Crystal::LoadIsawPeaks::appendFile(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createPeakworkspace(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), and Mantid::DataObjects::LeanElasticPeak::setQSampleFrame().
setH()
void Mantid::DataObjects::BasePeak::setH (double m_H) override virtual
Set the H index of this peak.
Parameters
m_H :: index to set
Implements Mantid::Geometry::IPeak.
Definition at line 120 of file BasePeak.cpp.
References m_H.
setHKL() [1/2]
void Mantid::DataObjects::BasePeak::setHKL (const Mantid::Kernel::V3D & HKL) override virtual
Set all HKL.
Parameters
HKL :: vector with x,y,z -> h,k,l
Implements Mantid::Geometry::IPeak.
Definition at line 141 of file BasePeak.cpp.
References setHKL(), and Mantid::Kernel::V3D::X().
setHKL() [2/2]
void Mantid::DataObjects::BasePeak::setHKL (double H, double K, double L) override virtual
Set all three H,K,L indices of the peak.
Implements Mantid::Geometry::IPeak.
Definition at line 131 of file BasePeak.cpp.
References m_H, m_K, and m_L.
Referenced by Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::CountReflections::getPeaksWorkspace(), Mantid::DataObjects::Peak::Peak(), Mantid::DataObjects::Peak::Peak(), Mantid::Crystal::LoadIsawPeaks::readPeak(), and setHKL().
setIntensity()
void Mantid::DataObjects::BasePeak::setIntensity (double m_intensity) override virtual
Set the integrated peak intensity.
Parameters
m_intensity :: intensity value
Implements Mantid::Geometry::IPeak.
Definition at line 197 of file BasePeak.cpp.
References m_intensity.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createOutputs(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createPeakworkspace(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::PeakIntegration::fitneighbours(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
setIntHKL()
void Mantid::DataObjects::BasePeak::setIntHKL (const Kernel::V3D & HKL) override virtual
Set int HKL.
Parameters
HKL :: vector with integer x,y,z -> h,k,l
Implements Mantid::Geometry::IPeak.
Definition at line 147 of file BasePeak.cpp.
References m_intHKL.
Referenced by Mantid::Crystal::LoadHKL::exec(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
setIntMNP()
void Mantid::DataObjects::BasePeak::setIntMNP (const Mantid::Kernel::V3D & MNP) override virtual
Sets the modulated peak structure number.
Parameters
MNP :: modulated peak structure value
Implements Mantid::Geometry::IPeak.
Definition at line 152 of file BasePeak.cpp.
References m_intMNP.
Referenced by Mantid::Crystal::LoadHKL::exec(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
setK()
void Mantid::DataObjects::BasePeak::setK (double m_K) override virtual
Set the K index of this peak.
Parameters
m_K :: index to set
Implements Mantid::Geometry::IPeak.
Definition at line 124 of file BasePeak.cpp.
References m_K.
setL()
void Mantid::DataObjects::BasePeak::setL (double m_L) override virtual
Set the L index of this peak.
Parameters
m_L :: index to set
Implements Mantid::Geometry::IPeak.
Definition at line 128 of file BasePeak.cpp.
References m_L.
setMonitorCount()
void Mantid::DataObjects::BasePeak::setMonitorCount (double m_monitorCount) override virtual
Set the monitor count for this peak.
Parameters
m_monitorCount :: the monitor count
Implements Mantid::Geometry::IPeak.
Definition at line 89 of file BasePeak.cpp.
References m_monitorCount.
Referenced by Mantid::Crystal::LoadIsawPeaks::appendFile().
setPeakNumber()
void Mantid::DataObjects::BasePeak::setPeakNumber (int m_peakNumber) override virtual
Sets the unique peak number.
Parameters
m_peakNumber :: unique peak number value
Implements Mantid::Geometry::IPeak.
Definition at line 238 of file BasePeak.cpp.
References m_peakNumber.
Referenced by Mantid::Crystal::LoadHKL::exec(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
setPeakShape() [1/2]
void Mantid::DataObjects::BasePeak::setPeakShape (Mantid::Geometry::PeakShape * shape) override virtual
Set the PeakShape.
Set the peak shape.
Parameters
shape : Desired shape
Implements Mantid::Geometry::IPeak.
Definition at line 303 of file BasePeak.cpp.
References m_peakShape.
setPeakShape() [2/2]
void Mantid::DataObjects::BasePeak::setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape) override virtual
Set the PeakShape.
Set the peak shape.
Parameters
shape : Desired shape
Implements Mantid::Geometry::IPeak.
Definition at line 309 of file BasePeak.cpp.
References m_peakShape.
setRunNumber()
void Mantid::DataObjects::BasePeak::setRunNumber (int m_runNumber) override virtual
Set the run number that measured this peak.
Parameters
m_runNumber :: the run number
Implements Mantid::Geometry::IPeak.
Definition at line 81 of file BasePeak.cpp.
References m_runNumber.
Referenced by Mantid::Crystal::LoadIsawPeaks::appendFile(), Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createPeakworkspace(), Mantid::Crystal::LoadHKL::exec(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), and Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry().
setSamplePos() [1/2]
void Mantid::DataObjects::BasePeak::setSamplePos (const Mantid::Kernel::V3D & XYZ) override virtual
Set sample position.
Parameters
XYZ :: vector x,y,z-> m_samplePos(x), m_samplePos(y), m_samplePos(z)
Implements Mantid::Geometry::IPeak.
Definition at line 172 of file BasePeak.cpp.
References m_samplePos.
setSamplePos() [2/2]
void Mantid::DataObjects::BasePeak::setSamplePos (double samX, double samY, double samZ) override virtual
Set sample position.
@ doubles x,y,z-> m_samplePos(x), m_samplePos(y), m_samplePos(z)
Implements Mantid::Geometry::IPeak.
Definition at line 161 of file BasePeak.cpp.
References m_samplePos.
Referenced by Mantid::Crystal::PeakHKLErrors::function1D(), and Mantid::Crystal::PeakHKLErrors::functionDeriv1D().
setSigmaIntensity()
void Mantid::DataObjects::BasePeak::setSigmaIntensity (double m_sigmaIntensity) override virtual
Set the error on the integrated peak intensity.
Parameters
m_sigmaIntensity :: intensity error value
Implements Mantid::Geometry::IPeak.
Definition at line 205 of file BasePeak.cpp.
References m_sigmaIntensity.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::PeakIntegration::fitneighbours(), and Mantid::Crystal::LoadIsawPeaks::readPeak().
Member Data Documentation
g_log
Mantid::Kernel::Logger Mantid::DataObjects::BasePeak::g_log static private
Static logger.
Definition at line 167 of file BasePeak.h.
m_absorptionWeightedPathLength
double Mantid::DataObjects::BasePeak::m_absorptionWeightedPathLength private
absorption weighted path length (aka t bar)
Definition at line 144 of file BasePeak.h.
Referenced by getAbsorptionWeightedPathLength(), operator=(), and setAbsorptionWeightedPathLength().
m_binCount
double Mantid::DataObjects::BasePeak::m_binCount private
Count in the bin at the peak.
Definition at line 141 of file BasePeak.h.
Referenced by getBinCount(), operator=(), and setBinCount().
m_convention
std::string Mantid::DataObjects::BasePeak::m_convention protected
Definition at line 119 of file BasePeak.h.
Referenced by calculateWavelengthFromQLab(), Mantid::DataObjects::LeanElasticPeak::getAzimuthal(), Mantid::DataObjects::LeanElasticPeak::getDetectorDirectionSampleFrame(), Mantid::DataObjects::Peak::getQLabFrame(), operator=(), and Mantid::DataObjects::Peak::setQLabFrame().
m_GoniometerMatrix
Mantid::Kernel::Matrix<double> Mantid::DataObjects::BasePeak::m_GoniometerMatrix private
Orientation matrix of the goniometer angles.
Definition at line 147 of file BasePeak.h.
Referenced by getGoniometerMatrix(), operator=(), and setGoniometerMatrix().
m_H
double Mantid::DataObjects::BasePeak::m_H private
H of the peak.
Definition at line 126 of file BasePeak.h.
Referenced by getH(), getHKL(), isIndexed(), operator=(), setH(), and setHKL().
m_intensity
double Mantid::DataObjects::BasePeak::m_intensity private
Integrated peak intensity.
Definition at line 135 of file BasePeak.h.
Referenced by getIntensity(), getIntensityOverSigma(), operator=(), and setIntensity().
m_intHKL
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::m_intHKL private
Definition at line 160 of file BasePeak.h.
Referenced by getIntHKL(), operator=(), and setIntHKL().
m_intMNP
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::m_intMNP private
Definition at line 161 of file BasePeak.h.
Referenced by getIntMNP(), operator=(), and setIntMNP().
m_InverseGoniometerMatrix
Mantid::Kernel::Matrix<double> Mantid::DataObjects::BasePeak::m_InverseGoniometerMatrix private
Inverse of the goniometer rotation matrix; used to go from Q in lab frame to Q in sample frame.
Definition at line 151 of file BasePeak.h.
Referenced by BasePeak(), BasePeak(), getInverseGoniometerMatrix(), operator=(), and setGoniometerMatrix().
m_K
double Mantid::DataObjects::BasePeak::m_K private
K of the peak.
Definition at line 129 of file BasePeak.h.
Referenced by getHKL(), getK(), isIndexed(), operator=(), setHKL(), and setK().
m_L
double Mantid::DataObjects::BasePeak::m_L private
L of the peak.
Definition at line 132 of file BasePeak.h.
Referenced by getHKL(), getL(), isIndexed(), operator=(), setHKL(), and setL().
m_monitorCount
double Mantid::DataObjects::BasePeak::m_monitorCount private
Integrated monitor count over TOF range for this run.
Definition at line 157 of file BasePeak.h.
Referenced by getMonitorCount(), operator=(), and setMonitorCount().
m_peakNumber
int Mantid::DataObjects::BasePeak::m_peakNumber private
Definition at line 159 of file BasePeak.h.
Referenced by getPeakNumber(), operator=(), and setPeakNumber().
m_peakShape
Mantid::Geometry::PeakShape_const_sptr Mantid::DataObjects::BasePeak::m_peakShape private
Peak shape.
Definition at line 164 of file BasePeak.h.
Referenced by getPeakShape(), operator=(), setPeakShape(), and setPeakShape().
m_runNumber
int Mantid::DataObjects::BasePeak::m_runNumber private
Originating run number for this peak.
Definition at line 154 of file BasePeak.h.
Referenced by getRunNumber(), operator=(), and setRunNumber().
m_samplePos
Mantid::Kernel::V3D Mantid::DataObjects::BasePeak::m_samplePos protected
Cached sample position.
Definition at line 122 of file BasePeak.h.
Referenced by Mantid::DataObjects::Peak::findDetector(), Mantid::DataObjects::Peak::getAzimuthal(), Mantid::DataObjects::Peak::getDetectorDirectionSampleFrame(), Mantid::DataObjects::Peak::getDSpacing(), Mantid::DataObjects::Peak::getL1(), Mantid::DataObjects::Peak::getL2(), Mantid::DataObjects::Peak::getQLabFrame(), getSamplePos(), Mantid::DataObjects::Peak::getScattering(), Mantid::DataObjects::Peak::getSourceDirectionSampleFrame(), Mantid::DataObjects::Peak::getVirtualDetectorPosition(), Mantid::DataObjects::Peak::operator=(), Mantid::DataObjects::Peak::setInstrument(), Mantid::DataObjects::Peak::setQLabFrame(), setSamplePos(), and setSamplePos().
m_sigmaIntensity
double Mantid::DataObjects::BasePeak::m_sigmaIntensity private
Error (sigma) on peak intensity.
Definition at line 138 of file BasePeak.h.
Referenced by getIntensityOverSigma(), getSigmaIntensity(), operator=(), and setSigmaIntensity().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/BasePeak.h
Framework/DataObjects/src/BasePeak.cpp