Mantid: Mantid::Kernel::DeltaEMode Struct Reference
Mantid::Kernel::DeltaEMode Struct Reference
Defines the possible energy transfer modes:
#include <DeltaEMode.h>
Public Types
enum Type { Elastic = 0 , Direct = 1 , Indirect = 2 , Undefined }
Define the available energy transfer modes It is important to assign enums proper numbers, until direct correspondence between enums and their emodes used by the external units conversion algorithms within the Mantid, so the agreement should be the stame
Static Public Member Functions
static std::string asString (const Type mode)
Return a string representation of the given mode.
static const std::vector< std::string > availableTypes ()
Returns the string list of available modes.
static Type fromString (const std::string &modeStr)
Returns the emode from the given string.
Detailed Description
Defines the possible energy transfer modes:
Elastic
Direct
Indirect and functions to convert to/from strings. It also returns a list of the available modes
Definition at line 23 of file DeltaEMode.h.
Member Enumeration Documentation
Type
enum Mantid::Kernel::DeltaEMode::Type
Define the available energy transfer modes It is important to assign enums proper numbers, until direct correspondence between enums and their emodes used by the external units conversion algorithms within the Mantid, so the agreement should be the stame
Enumerator
Elastic
Direct
Indirect
Undefined
this mode should not be displayed among modes availible to select but may have string representation
Definition at line 29 of file DeltaEMode.h.
Member Function Documentation
asString()
std::string Mantid::Kernel::DeltaEMode::asString (const Type mode) static
Return a string representation of the given mode.
Parameters
mode An enumeration of an energy transfer mode
Returns
The string representation
Definition at line 52 of file DeltaEMode.cpp.
Referenced by Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), export_DeltaEMode(), Mantid::MDAlgorithms::MDWSDescription::getEModeStr(), and Mantid::Algorithms::SparseWorkspace::SparseWorkspace().
availableTypes()
const std::vector< std::string > Mantid::Kernel::DeltaEMode::availableTypes () static
Returns the string list of available modes.
Returns
Definition at line 35 of file DeltaEMode.cpp.
References Undefined.
Referenced by Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3::calculateExtentsFromData(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::exec(), export_DeltaEMode(), Mantid::MDAlgorithms::MDTransfModQ::getEmodes(), Mantid::Algorithms::RemoveBackground::init(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::init(), and Mantid::MDAlgorithms::ConvertToMDParent::init().
fromString()
DeltaEMode::Type Mantid::Kernel::DeltaEMode::fromString (const std::string & modeStr) static
Returns the emode from the given string.
Throws if the mode is not known
Parameters
modeStr A string containing an energy transfer mode
Returns
The corresponding enumeration
Definition at line 69 of file DeltaEMode.cpp.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMatrixWS(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::RemoveBackground::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::exec(), export_DeltaEMode(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::API::ExperimentInfo::getEMode(), Mantid::MDAlgorithms::ConvertToMDParent::preprocessDetectorsPositions(), and Mantid::MDAlgorithms::ConvertToMDParent::runPreprocessDetectorsToMDChildUpdatingMasks().
The documentation for this struct was generated from the following files:
Framework/Kernel/inc/MantidKernel/DeltaEMode.h
Framework/Kernel/src/DeltaEMode.cpp