Mantid: Mantid::MDAlgorithms::MDAlgorithmsTestHelper Namespace Reference
Mantid::MDAlgorithms::MDAlgorithmsTestHelper Namespace Reference
Functions
DataObjects::MDEventWorkspace3Lean::sptr makeFileBackedMDEW (const std::string &wsName, bool fileBacked, long numEvents, Kernel::SpecialCoordinateSystem coord)
Make a (optionally) file backed MDEventWorkspace with nEvents fake data points the points are randomly distributed within the box (nEvents>0) or homogeneously and regularly spread through the box (nEvents<0)
DataObjects::MDEventWorkspace3Lean::sptr makeFileBackedMDEWwithMDFrame (const std::string &wsName, bool fileBacked, const Mantid::Geometry::MDFrame &frame, long numEvents, Kernel::SpecialCoordinateSystem coord)
Make a (optionally) file backed MDEventWorkspace with nEvents fake data points the points are randomly distributed within the box (nEvents>0) or homogeneously and regularly spread through the box (nEvents<0)
Function Documentation
makeFileBackedMDEW()
DataObjects::MDEventWorkspace3Lean::sptr Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEW (const std::string & wsName, bool fileBacked, long numEvents, Kernel::SpecialCoordinateSystem coord)
Make a (optionally) file backed MDEventWorkspace with nEvents fake data points the points are randomly distributed within the box (nEvents>0) or homogeneously and regularly spread through the box (nEvents<0)
Parameters
wsName :: name of the workspace in ADS
fileBacked :: true for file-backed
numEvents :: number of events in the target workspace distributed randomly if numEvents>0 or regularly & homogeneously if numEvents<0
coord :: Required coordinate system
Returns
MDEW sptr
Definition at line 36 of file MDAlgorithmsTestHelper.cpp.
References Mantid::DataHandling::numEvents(), and std::to_string().
makeFileBackedMDEWwithMDFrame()
DataObjects::MDEventWorkspace3Lean::sptr Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEWwithMDFrame (const std::string & wsName, bool fileBacked, const Mantid::Geometry::MDFrame & frame, long numEvents, Kernel::SpecialCoordinateSystem coord)
Make a (optionally) file backed MDEventWorkspace with nEvents fake data points the points are randomly distributed within the box (nEvents>0) or homogeneously and regularly spread through the box (nEvents<0)
Parameters
wsName :: name of the workspace in ADS
fileBacked :: true for file-backed
frame,: the required frame
numEvents :: number of events in the target workspace distributed randomly if numEvents>0 or regularly & homogeneously if numEvents<0
coord :: Required coordinate system
Returns
MDEW sptr
Definition at line 71 of file MDAlgorithmsTestHelper.cpp.
References Mantid::DataHandling::numEvents(), and std::to_string().