Mantid: Mantid::Kernel::Units::QSquared Class Reference
Mantid::Kernel::Units::QSquared Class Reference
Momentum transfer squared in Angstrom^-2.
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
QSquared ()
Constructor.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"QSquared"
Public Member Functions inherited from Mantid::Kernel::Units::MomentumTransfer
void init () override
Finalize the initialization.
MomentumTransfer ()
Constructor.
Public Member Functions inherited from Mantid::Kernel::Unit
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit. TOF is in microseconds.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight. TOF is in microseconds.
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual ~Unit ()=default
Virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Units::MomentumTransfer
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
Protected Attributes inherited from Mantid::Kernel::Units::MomentumTransfer
double difc
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Momentum transfer squared in Angstrom^-2.
Definition at line 427 of file Unit.h.
Constructor & Destructor Documentation
QSquared()
Mantid::Kernel::Units::QSquared::QSquared ()
Constructor.
Definition at line 909 of file Unit.cpp.
References Mantid::Kernel::Unit::addConversion().
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::QSquared::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 430 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::QSquared::clone () const override virtual
Returns
a cloned instance of the other
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 926 of file Unit.cpp.
References QSquared().
conversionTOFMax()
double Mantid::Kernel::Units::QSquared::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 919 of file Unit.cpp.
References Mantid::Kernel::Units::MomentumTransfer::difc.
conversionTOFMin()
double Mantid::Kernel::Units::QSquared::conversionTOFMin () const override virtual
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 918 of file Unit.cpp.
References Mantid::Kernel::Units::MomentumTransfer::difc.
label()
const UnitLabel Mantid::Kernel::Units::QSquared::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 907 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::InverseAngstromSq.
singleFromTOF()
double Mantid::Kernel::Units::QSquared::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 916 of file Unit.cpp.
References Mantid::Kernel::Units::MomentumTransfer::singleFromTOF().
singleToTOF()
double Mantid::Kernel::Units::QSquared::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
Definition at line 915 of file Unit.cpp.
References Mantid::Kernel::Units::MomentumTransfer::singleToTOF(), and Mantid::Geometry::x.
unitID()
const std::string Mantid::Kernel::Units::QSquared::unitID () const override virtual
"QSquared"
Reimplemented from Mantid::Kernel::Units::MomentumTransfer.
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp