Mantid: pqHelpWindow Class Reference
pqHelpWindow Class Reference
pqHelpWindow provides an assistant-like window for showing help provided by a QHelpEngine.
#include <pqHelpWindow.h>
Public Slots
bool isExistingPage (const QUrl &url)
Check if the url is an existing page.
virtual void printPage ()
Prints the current open page.
virtual void showHomePage ()
virtual void showHomePage (const QString &namespace_name)
Tries to locate a file name index.html in the given namespace and then shows that page.
virtual void showLinkedPage (const QUrl &url)
Show a page linked to by another page in the help window.
virtual void showPage (const QString &url, bool linkClicked=false)
Requests showing of a particular page.
virtual void showPage (const QUrl &url, bool linkClicked=false)
Signals
void helpWarnings (const QString &)
fired to relay warning messages from the help system.
Public Member Functions
pqHelpWindow (QHelpEngine *engine, QWidget *parent=nullptr, const Qt::WindowFlags &flags=Qt::WindowFlags())
Protected Slots
void linkHovered (const QString &link, const QString &title="", const QString &textContent="")
void search ()
void updateNavButtons ()
Protected Attributes
QToolButton * m_backward
QWebEngineView * m_browser
QToolButton * m_forward
QHelpEngine * m_helpEngine
Private Types
using Superclass = QMainWindow
Private Member Functions
void errorMissingPage (const QUrl &url)
Set the contents of the browser to show an error message.
pqHelpWindow & operator= (const pqHelpWindow &)=delete
pqHelpWindow (const pqHelpWindow &)=delete
Friends
class pqNetworkAccessManager
Detailed Description
pqHelpWindow provides an assistant-like window for showing help provided by a QHelpEngine.
Definition at line 73 of file pqHelpWindow.h.
Member Typedef Documentation
Superclass
using pqHelpWindow::Superclass = QMainWindow private
Definition at line 75 of file pqHelpWindow.h.
Constructor & Destructor Documentation
pqHelpWindow() [1/2]
pqHelpWindow::pqHelpWindow (QHelpEngine * engine, QWidget * parent = nullptr, const Qt::WindowFlags & flags = Qt::WindowFlags())
Definition at line 234 of file pqHelpWindow.cxx.
References helpWarnings(), linkHovered(), m_backward, m_browser, m_forward, m_helpEngine, pqNetworkAccessManager, printPage(), search(), showHomePage(), showLinkedPage(), showPage(), and updateNavButtons().
pqHelpWindow() [2/2]
pqHelpWindow::pqHelpWindow (const pqHelpWindow &) private delete
Member Function Documentation
errorMissingPage()
void pqHelpWindow::errorMissingPage (const QUrl & url) private
Set the contents of the browser to show an error message.
Parameters
url The url that could not be found.
Definition at line 333 of file pqHelpWindow.cxx.
References m_browser.
Referenced by showHomePage(), and showPage().
helpWarnings
void pqHelpWindow::helpWarnings (const QString &) signal
fired to relay warning messages from the help system.
Referenced by pqHelpWindow().
isExistingPage
bool pqHelpWindow::isExistingPage (const QUrl & url) slot
Check if the url is an existing page.
Definition at line 419 of file pqHelpWindow.cxx.
References m_helpEngine.
Referenced by showPage().
linkHovered
void pqHelpWindow::linkHovered (const QString & link, const QString & title = "", const QString & textContent = "") protected slot
Definition at line 397 of file pqHelpWindow.cxx.
Referenced by pqHelpWindow().
operator=()
pqHelpWindow & pqHelpWindow::operator= (const pqHelpWindow &) private delete
printPage
void pqHelpWindow::printPage () virtual slot
Prints the current open page.
Definition at line 371 of file pqHelpWindow.cxx.
References m_browser.
Referenced by pqHelpWindow().
search
void pqHelpWindow::search () protected slot
Definition at line 391 of file pqHelpWindow.cxx.
References m_helpEngine, and search().
Referenced by pqHelpWindow(), and search().
showHomePage [1/2]
void pqHelpWindow::showHomePage () virtual slot
Definition at line 403 of file pqHelpWindow.cxx.
References showPage().
showHomePage [2/2]
void pqHelpWindow::showHomePage (const QString & namespace_name) virtual slot
Tries to locate a file name index.html in the given namespace and then shows that page.
Definition at line 406 of file pqHelpWindow.cxx.
References errorMissingPage(), m_helpEngine, and showPage().
Referenced by pqHelpWindow().
showLinkedPage
void pqHelpWindow::showLinkedPage (const QUrl & url) virtual slot
Show a page linked to by another page in the help window.
Definition at line 368 of file pqHelpWindow.cxx.
References showPage().
Referenced by pqHelpWindow().
showPage [1/2]
void pqHelpWindow::showPage (const QString & url, bool linkClicked = false) virtual slot
Requests showing of a particular page.
The url must begin with "qthelp:" scheme when referring to pages from the help files.
Definition at line 345 of file pqHelpWindow.cxx.
References showPage().
Referenced by pqHelpWindow(), showHomePage(), showLinkedPage(), and showPage().
showPage [2/2]
void pqHelpWindow::showPage (const QUrl & url, bool linkClicked = false) virtual slot
Definition at line 350 of file pqHelpWindow.cxx.
References errorMissingPage(), isExistingPage(), m_backward, m_browser, and m_forward.
updateNavButtons
void pqHelpWindow::updateNavButtons () protected slot
Definition at line 385 of file pqHelpWindow.cxx.
References m_backward, m_browser, and m_forward.
Referenced by pqHelpWindow().
Friends And Related Function Documentation
pqNetworkAccessManager
friend class pqNetworkAccessManager friend
Definition at line 122 of file pqHelpWindow.h.
Referenced by pqHelpWindow().
Member Data Documentation
m_backward
QToolButton* pqHelpWindow::m_backward protected
Definition at line 112 of file pqHelpWindow.h.
Referenced by pqHelpWindow(), showPage(), and updateNavButtons().
m_browser
QWebEngineView* pqHelpWindow::m_browser protected
Definition at line 110 of file pqHelpWindow.h.
Referenced by errorMissingPage(), pqHelpWindow(), printPage(), showPage(), and updateNavButtons().
m_forward
QToolButton* pqHelpWindow::m_forward protected
Definition at line 111 of file pqHelpWindow.h.
Referenced by pqHelpWindow(), showPage(), and updateNavButtons().
m_helpEngine
QHelpEngine* pqHelpWindow::m_helpEngine protected
Definition at line 109 of file pqHelpWindow.h.
Referenced by isExistingPage(), pqHelpWindow(), search(), and showHomePage().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/pqHelpWindow.h
qt/widgets/common/src/pqHelpWindow.cxx