Mantid: Mantid::API::IEventWorkspace Class Reference
Mantid::API::IEventWorkspace Class Reference abstract
This class provides an interface to an EventWorkspace.
#include <IEventWorkspace.h>
Public Member Functions
virtual void clearMRU () const =0
IEventWorkspace_uptr clone () const
Returns a clone of the workspace.
IEventWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
void generateHistogram (const std::size_t index, const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const override=0
Generate the histogram or rebin the existing histogram.
virtual EventType getEventType () const =0
virtual std::size_t getNumberEvents () const =0
virtual Mantid::Types::Core::DateAndTime getPulseTimeMax () const =0
virtual Mantid::Types::Core::DateAndTime getPulseTimeMin () const =0
const IEventList & getSpectrum (const size_t index) const override=0
Return the underlying ISpectrum ptr (const version) at the given workspace index.
IEventList & getSpectrum (const size_t index) override=0
Return the underlying ISpectrum ptr at the given workspace index.
virtual Mantid::Types::Core::DateAndTime getTimeAtSampleMax (double tofOffset=0) const =0
virtual Mantid::Types::Core::DateAndTime getTimeAtSampleMin (double tofOffset=0) const =0
virtual double getTofMax () const =0
virtual double getTofMin () const =0
const std::string id () const override
Return the workspace typeID.
IEventWorkspace ()
IEventWorkspace & operator= (const IEventWorkspace &)=delete
virtual void resetAllXToSingleBin ()=0
virtual void setAllX (const HistogramData::BinEdges &x)=0
Public Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace_uptr clone () const
Returns a clone of the workspace.
MatrixWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const Indexing::IndexInfo & indexInfo () const
Returns a const reference to the IndexInfo object of the workspace.
void initialize (const Indexing::IndexInfo &indexInfo, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const std::size_t &XLength, const std::size_t &YLength)
Initialize the workspace.
MatrixWorkspace & operator= (const MatrixWorkspace &other)=delete
void setIndexInfo (const Indexing::IndexInfo &indexInfo)
Sets the IndexInfo object of the workspace.
const std::string toString () const override
Serializes the object to a string.
const std::string toString () const override
String description of state.
~MatrixWorkspace () override
Delete.
std::shared_ptr< const Geometry::IDetector > getDetector (const size_t workspaceIndex) const
Get the effective detector for the given spectrum.
double detectorTwoTheta (const Geometry::IDetector &det) const
Returns the 2Theta scattering angle for a detector.
double detectorSignedTwoTheta (const Geometry::IDetector &det) const
Returns the signed 2Theta scattering angle for a detector.
virtual void updateSpectraUsing (const SpectrumDetectorMapping &map)
void rebuildSpectraMapping (const bool includeMonitors=true, const specnum_t specNumOffset=1)
Build the default spectra mapping, most likely wanted after an instrument update.
spec2index_map getSpectrumToWorkspaceIndexMap () const
Return a map where: KEY is the Spectrum # VALUE is the Workspace Index.
detid2index_map getDetectorIDToWorkspaceIndexMap (bool throwIfMultipleDets=false, bool ignoreIfNoValidDets=false) const
Return a map where: KEY is the DetectorID (pixel ID) VALUE is the Workspace Index.
virtual std::vector< size_t > getDetectorIDToWorkspaceIndexVector (detid_t &offset, bool throwIfMultipleDets=false) const
Return a vector where: The index into the vector = DetectorID (pixel ID) + offset The value at that index = the corresponding Workspace Index.
virtual std::vector< size_t > getSpectrumToWorkspaceIndexVector (specnum_t &offset) const
Return a vector where: The index into the vector = spectrum number + offset The value at that index = the corresponding Workspace Index.
std::vector< size_t > getIndicesFromSpectra (const std::vector< specnum_t > &spectraList) const
Converts a list of spectrum numbers to the corresponding workspace indices.
size_t getIndexFromSpectrumNumber (const specnum_t specNo) const
Given a spectrum number, find the corresponding workspace index.
std::vector< size_t > getIndicesFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding workspace indices.
std::vector< specnum_t > getSpectraFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding spectrum numbers.
bool hasGroupedDetectors () const
Does the workspace has any grouped detectors?
virtual bool isRaggedWorkspace () const =0
Returns true if the workspace is ragged (has differently sized spectra).
size_t getMemorySize () const override
Get the footprint in memory in bytes.
virtual size_t getMemorySizeForXAxes () const
Returns the memory used (in bytes) by the X axes, handling ragged bins.
virtual std::size_t size () const =0
Returns the number of single indexable items in the workspace.
virtual std::size_t blocksize () const =0
Returns the size of each block of data returned by the dataY accessors.
virtual std::size_t getNumberBins (const std::size_t &index) const =0
Returns the number of bins for a given histogram index.
virtual std::size_t getMaxNumberBins () const =0
Returns the maximum number of bins in a workspace (works on ragged data).
virtual std::size_t getNumberHistograms () const =0
Returns the number of histograms in the workspace.
void setTitle (const std::string &) override
Sets MatrixWorkspace title.
const std::string getTitle () const override
Gets MatrixWorkspace title (same as Run object run_title property)
void setPlotType (const std::string &)
Sets MatrixWorkspace plot_type.
std::string getPlotType () const
Gets MatrixWorkspace plot_type.
void setMarkerStyle (const std::string &markerType)
Set the marker style for plotting.
std::string getMarkerStyle () const
Get the marker style for plotting.
void setMarkerSize (const float markerSize)
Set the size of the marker for plotting.
float getMarkerSize () const
Get the size of the marker for plotting.
virtual Types::Core::DateAndTime getFirstPulseTime () const
Return the time of the first pulse received, by accessing the run's sample logs to find the proton_charge.
Types::Core::DateAndTime getLastPulseTime () const
Return the time of the last pulse received, by accessing the run's sample logs to find the proton_charge.
std::size_t yIndexOfX (const double xValue, const std::size_t &index=0, const double tolerance=0.0) const
Returns the y index which corresponds to the X Value provided.
HistogramData::Histogram histogram (const size_t index) const
Returns the Histogram at the given workspace index.
template<typename... T>
void setHistogram (const size_t index, T &&...data) &
void convertToCounts (const size_t index)
void convertToFrequencies (const size_t index)
HistogramData::BinEdges binEdges (const size_t index) const
HistogramData::Points points (const size_t index) const
HistogramData::PointStandardDeviations pointStandardDeviations (const size_t index) const
template<typename... T>
void setBinEdges (const size_t index, T &&...data) &
template<typename... T>
void setPoints (const size_t index, T &&...data) &
template<typename... T>
void setPointVariances (const size_t index, T &&...data) &
template<typename... T>
void setPointStandardDeviations (const size_t index, T &&...data) &
HistogramData::Counts counts (const size_t index) const
HistogramData::CountVariances countVariances (const size_t index) const
HistogramData::CountStandardDeviations countStandardDeviations (const size_t index) const
HistogramData::Frequencies frequencies (const size_t index) const
HistogramData::FrequencyVariances frequencyVariances (const size_t index) const
HistogramData::FrequencyStandardDeviations frequencyStandardDeviations (const size_t index) const
template<typename... T>
void setCounts (const size_t index, T &&...data) &
template<typename... T>
void setCountVariances (const size_t index, T &&...data) &
template<typename... T>
void setCountStandardDeviations (const size_t index, T &&...data) &
template<typename... T>
void setFrequencies (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyVariances (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyStandardDeviations (const size_t index, T &&...data) &
const HistogramData::HistogramX & x (const size_t index) const
const HistogramData::HistogramY & y (const size_t index) const
const HistogramData::HistogramE & e (const size_t index) const
const HistogramData::HistogramDx & dx (const size_t index) const
HistogramData::HistogramX & mutableX (const size_t index) &
HistogramData::HistogramDx & mutableDx (const size_t index) &
HistogramData::HistogramY & mutableY (const size_t index) &
HistogramData::HistogramE & mutableE (const size_t index) &
Kernel::cow_ptr< HistogramData::HistogramX > sharedX (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramY > sharedY (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramE > sharedE (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramDx > sharedDx (const size_t index) const
void setSharedX (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &x) &
void setSharedDx (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramDx > &dx) &
void setSharedY (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramY > &y) &
void setSharedE (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramE > &e) &
void resizeHistogram (const size_t index, size_t n) &
size_t histogramSize (const size_t index) const
const MantidVec & readX (std::size_t const index) const
Deprecated, use x() instead.
const MantidVec & readY (std::size_t const index) const
Deprecated, use y() instead.
const MantidVec & readE (std::size_t const index) const
Deprecated, use e() instead.
const MantidVec & readDx (size_t const index) const
Deprecated, use dx() instead.
virtual MantidVec & dataX (const std::size_t index)
Deprecated, use mutableX() instead. Returns the x data.
virtual MantidVec & dataY (const std::size_t index)
Deprecated, use mutableY() instead. Returns the y data.
virtual MantidVec & dataE (const std::size_t index)
Deprecated, use mutableE() instead. Returns the error data.
virtual MantidVec & dataDx (const std::size_t index)
Deprecated, use mutableDx() instead. Returns the x error data.
virtual const MantidVec & dataX (const std::size_t index) const
Deprecated, use x() instead. Returns the x data const.
virtual const MantidVec & dataY (const std::size_t index) const
Deprecated, use y() instead. Returns the y data const.
virtual const MantidVec & dataE (const std::size_t index) const
Deprecated, use e() instead. Returns the error const.
virtual const MantidVec & dataDx (const std::size_t index) const
Deprecated, use dx() instead. Returns the error const.
virtual double getXMin () const
virtual double getXMax () const
virtual void getXMinMax (double &xmin, double &xmax) const
virtual Kernel::cow_ptr< HistogramData::HistogramX > refX (const std::size_t index) const
Deprecated, use sharedX() instead. Returns a pointer to the x data.
virtual void setX (const std::size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual void setX (const std::size_t index, const std::shared_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual bool hasDx (const std::size_t index) const
Probes if DX (X Error) values were set on a particular spectrum.
virtual void getIntegratedSpectra (std::vector< double > &out, const double minX, const double maxX, const bool entireRange) const
Return a vector with the integrated counts for all spectra withing the given range.
std::vector< double > getIntegratedCountsForWorkspaceIndices (const std::vector< size_t > &workspaceIndices, const double minX, const double maxX, const bool entireRange) const
std::pair< size_t, double > getXIndex (size_t i, double x, bool isLeft=true, size_t start=0) const
Return an index in the X vector for an x-value close to a given value.
int axes () const
virtual Axis * getAxis (const std::size_t &axisIndex) const
Get a non owning pointer to a workspace axis.
void replaceAxis (const std::size_t &axisIndex, std::unique_ptr< Axis > newAxis)
Replaces one of the workspace's axes with the new one provided.
size_t numberOfAxis () const
Will return the number of Axis currently stored in the workspace it is not always safe to assume it is just 2.
virtual bool isCommonLogBins () const
Returns true if the workspace contains common X bins with log spacing.
virtual bool isHistogramData () const
Returns true if the workspace contains data in histogram form (as opposed to point-like)
virtual bool isCommonBins () const
Returns true if the workspace contains common X bins.
virtual bool isIntegerBins () const
Returns true if the workspace has common, integer X bins.
const std::string & YUnit () const
void setYUnit (const std::string &newUnit)
Sets a new unit for the data (Y axis) in the workspace.
std::string YUnitLabel (bool useLatex=false, bool plotAsDistribution=false) const
Returns a caption for the units of the data in the workspace.
void setYUnitLabel (const std::string &newLabel)
Sets a new caption for the data (Y axis) in the workspace.
bool isDistribution () const
Are the Y-values dimensioned?
void setDistribution (bool newValue)
Set the flag for whether the Y-values are dimensioned.
void maskBin (const size_t &workspaceIndex, const size_t &binIndex, const double &weight=1.0)
Called by the algorithm MaskBins to mask a single bin for the first time, algorithms that later propagate the the mask from an input to the output should call flagMasked() instead.
void flagMasked (const size_t &index, const size_t &binIndex, const double &weight=1.0)
Writes the masking weight to m_masks (doesn't alter y-values).
bool hasMaskedBins (const size_t &workspaceIndex) const
Does this spectrum contain any masked bins.
bool hasAnyMaskedBins () const
Does this workspace contain any masked bins.
const MaskList & maskedBins (const size_t &workspaceIndex) const
Returns the list of masked bins for a spectrum.
std::vector< size_t > maskedBinsIndices (const size_t &workspaceIndex) const
void setMaskedBins (const size_t workspaceIndex, const MaskList &maskedBins)
Set the list of masked bins for given workspaceIndex.
void setUnmaskedBins (const size_t workspaceIndex)
Removes the mask from an index.
virtual void setMonitorWorkspace (const std::shared_ptr< MatrixWorkspace > &monitorWS)
Sets the internal monitor workspace to the provided workspace.
std::shared_ptr< MatrixWorkspace > monitorWorkspace () const
Returns a pointer to the internal monitor workspace.
void loadInstrumentNexus (Nexus::File *file)
size_t getNumDims () const override
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const override
Get a dimension.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const override
Get a dimension.
uint64_t getNPoints () const override
Gets the number of points available on the workspace.
uint64_t getNEvents () const override
Get the number of points available on the workspace.
LinePlot getLinePlot (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const override
Generate a line plot through the matrix workspace.
signal_t getSignalAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
signal_t getSignalWithMaskAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
std::vector< std::unique_ptr< IMDIterator > > createIterators (size_t suggestedNumCores=1, Mantid::Geometry::MDImplicitFunction *function=nullptr) const override
Create iterators.
void setMDMasking (std::unique_ptr< Mantid::Geometry::MDImplicitFunction > maskingRegion) override
Apply masking.
void clearMDMasking () override
Clear exsting masking.
Mantid::Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const override
virtual bool hasOrientedLattice () const override
virtual std::pair< int64_t, int64_t > findY (double value, const std::pair< int64_t, int64_t > &idx={0, 0}) const
Find first index in Y equal to value.
std::pair< size_t, size_t > getImageStartEndXIndices (size_t i, double startX, double endX) const
Get start and end x indices for images.
MantidImage_sptr getImageY (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Ys.
MantidImage_sptr getImageE (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Es.
virtual void setImageY (const MantidImage &image, size_t start=0, bool parallelExecution=true)
Copy the data (Y's) from an image to this workspace.
virtual void setImageE (const MantidImage &image, size_t start=0, bool parallelExecution=true)
Copy the data from an image to this workspace's errors.
void invalidateCachedSpectrumNumbers ()
void invalidateCommonBinsFlag ()
Invalidates the commons bins flag.
Public Member Functions inherited from Mantid::API::IMDWorkspace
std::string changeQConvention ()
virtual void clearFileBacked (bool)
if a workspace was filebacked, this should clear file-based status, delete file-based information and close related files.
std::unique_ptr< IMDWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< IMDWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
std::unique_ptr< IMDIterator > createIterator (Mantid::Geometry::MDImplicitFunction *function=nullptr) const
Creates a single iterator and returns it.
virtual MDNormalization displayNormalization () const
virtual MDNormalization displayNormalizationHisto () const
const std::string & getConvention () const
signal_t getSignalAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates.
signal_t getSignalWithMaskAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates or 0 if masked.
IMDWorkspace ()
Default constructor.
virtual bool isMDHistoWorkspace () const
virtual ITableWorkspace_sptr makeBoxTable (size_t, size_t)
this is the method to build table workspace from any workspace.
IMDWorkspace & operator= (const IMDWorkspace &other)=delete
void setConvention (std::string convention)
Sets the convention of the workspace.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::MDGeometry
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (Nexus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instument group if found there.
void loadSampleAndLogInfoNexus (Nexus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (Nexus::File *file, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (Nexus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (Nexus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Protected Member Functions
IEventList & getSpectrumWithoutInvalidation (const size_t index) override=0
IEventWorkspace (const IEventWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace (const MatrixWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
MatrixWorkspace ()
Default constructor.
virtual void init (const std::size_t &NVectors, const std::size_t &XLength, const std::size_t &YLength)=0
Initialises the workspace.
virtual void init (const HistogramData::Histogram &histogram)=0
void updateCachedDetectorGrouping (const size_t index) const override
Update detector grouping for spectrum with given index.
std::string getDimensionIdFromAxis (const int &axisIndex) const
Getter for the dimension id based on the axis.
Protected Member Functions inherited from Mantid::API::IMDWorkspace
IMDWorkspace (const IMDWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void makeSinglePointWithNaN (std::vector< coord_t > &x, std::vector< signal_t > &y, std::vector< signal_t > &e) const
Make a single point with NaN as the signal and error This can be returned when there would otherwise be nothing to plot.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::MDGeometry
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
Private Member Functions
IEventWorkspace * doClone () const override=0
Virtual clone method. Not implemented to force implementation in children.
IEventWorkspace * doCloneEmpty () const override=0
Virtual cloneEmpty method.
Additional Inherited Members
Public Types inherited from Mantid::API::MatrixWorkspace
using MaskList = std::map< size_t, double >
Masked bins for each spectrum are stored as a set of pairs containing <bin index, weight>
Static Public Attributes inherited from Mantid::API::MatrixWorkspace
static const std::string xDimensionId = "xDimension"
Dimension id for x-dimension.
static const std::string yDimensionId = "yDimension"
Dimensin id for y-dimension.
Protected Attributes inherited from Mantid::API::MatrixWorkspace
std::vector< std::unique_ptr< Axis > > m_axes
A vector of pointers to the axes for this workspace.
Protected Attributes inherited from Mantid::API::MDGeometry
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Detailed Description
This class provides an interface to an EventWorkspace.
Author
Martyn Gigg, Tessella plc
Date
13/08/2010
Definition at line 22 of file IEventWorkspace.h.
Constructor & Destructor Documentation
IEventWorkspace() [1/2]
Mantid::API::IEventWorkspace::IEventWorkspace () inline
Definition at line 24 of file IEventWorkspace.h.
IEventWorkspace() [2/2]
Mantid::API::IEventWorkspace::IEventWorkspace (const IEventWorkspace &) protected default
Protected copy constructor. May be used by childs for cloning.
Member Function Documentation
clearMRU()
virtual void Mantid::API::IEventWorkspace::clearMRU () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
clone()
IEventWorkspace_uptr Mantid::API::IEventWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 27 of file IEventWorkspace.h.
cloneEmpty()
IEventWorkspace_uptr Mantid::API::IEventWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 29 of file IEventWorkspace.h.
doClone()
IEventWorkspace * Mantid::API::IEventWorkspace::doClone () const override private pure virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
doCloneEmpty()
IEventWorkspace * Mantid::API::IEventWorkspace::doCloneEmpty () const override private pure virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
generateHistogram()
void Mantid::API::IEventWorkspace::generateHistogram (const std::size_t index, const MantidVec & X, MantidVec & Y, MantidVec & E, bool skipError = false) const override pure virtual
Generate the histogram or rebin the existing histogram.
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
getEventType()
virtual EventType Mantid::API::IEventWorkspace::getEventType () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
getNumberEvents()
virtual std::size_t Mantid::API::IEventWorkspace::getNumberEvents () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
getPulseTimeMax()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventWorkspace::getPulseTimeMax () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
getPulseTimeMin()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventWorkspace::getPulseTimeMin () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
getSpectrum() [1/2]
const IEventList & Mantid::API::IEventWorkspace::getSpectrum (const size_t index) const override pure virtual
Return the underlying ISpectrum ptr (const version) at the given workspace index.
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
getSpectrum() [2/2]
IEventList & Mantid::API::IEventWorkspace::getSpectrum (const size_t index) override pure virtual
Return the underlying ISpectrum ptr at the given workspace index.
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
getSpectrumWithoutInvalidation()
IEventList & Mantid::API::IEventWorkspace::getSpectrumWithoutInvalidation (const size_t index) override protected pure virtual
Implements Mantid::API::MatrixWorkspace.
Implemented in Mantid::DataObjects::EventWorkspace.
getTimeAtSampleMax()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventWorkspace::getTimeAtSampleMax (double tofOffset = 0) const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
getTimeAtSampleMin()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventWorkspace::getTimeAtSampleMin (double tofOffset = 0) const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
getTofMax()
virtual double Mantid::API::IEventWorkspace::getTofMax () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
getTofMin()
virtual double Mantid::API::IEventWorkspace::getTofMin () const pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
Referenced by export_IEventWorkspace().
id()
const std::string Mantid::API::IEventWorkspace::id () const inline override virtual
Return the workspace typeID.
Implements Mantid::Kernel::DataItem.
Reimplemented in Mantid::DataObjects::EventWorkspace.
Definition at line 35 of file IEventWorkspace.h.
operator=()
IEventWorkspace & Mantid::API::IEventWorkspace::operator= (const IEventWorkspace &) delete
resetAllXToSingleBin()
virtual void Mantid::API::IEventWorkspace::resetAllXToSingleBin () pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
setAllX()
virtual void Mantid::API::IEventWorkspace::setAllX (const HistogramData::BinEdges & x) pure virtual
Implemented in Mantid::DataObjects::EventWorkspace.
toString()
const std::string Mantid::API::IEventWorkspace::toString () const override protected virtual
Serializes the object to a string.
Implements Mantid::Kernel::DataItem.
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IEventWorkspace.h