Mantid: Mantid::Geometry::IMDDimension Class Reference
Mantid::Geometry::IMDDimension Class Reference abstract
The class describes one dimension of multidimensional dataset representing an orthogonal dimension and linear axis.
#include <IMDDimension.h>
Public Member Functions
virtual coord_t getBinWidth () const
virtual const std::string & getDimensionId () const =0
short name which identify the dimension among other dimension.
virtual bool getIsIntegrated () const
virtual coord_t getMaximum () const =0
virtual const Geometry::MDFrame & getMDFrame () const =0
virtual const Kernel::MDUnit & getMDUnits () const =0
virtual coord_t getMinimum () const =0
virtual std::string getName () const =0
virtual size_t getNBins () const =0
virtual size_t getNBoundaries () const =0
virtual const Kernel::UnitLabel getUnits () const =0
virtual coord_t getX (size_t ind) const =0
bool operator!= (const IMDDimension &) const
bool operator== (const IMDDimension &) const
virtual void setRange (size_t nBins, coord_t min, coord_t max)=0
Change the extents and number of bins.
virtual std::string toXMLString () const =0
virtual ~IMDDimension ()=default
Destructor.
Detailed Description
The class describes one dimension of multidimensional dataset representing an orthogonal dimension and linear axis.
Abstract type for a multi dimensional dimension. Gives a read-only layer to
the concrete implementation.
@author Owen Arnold, RAL ISIS
@date 12/11/2010
Definition at line 39 of file IMDDimension.h.
Constructor & Destructor Documentation
~IMDDimension()
virtual Mantid::Geometry::IMDDimension::~IMDDimension () virtual default
Destructor.
Member Function Documentation
getBinWidth()
virtual coord_t Mantid::Geometry::IMDDimension::getBinWidth () const inline virtual
Returns
the width of each bin
Reimplemented in Mantid::API::MWDimension, and Mantid::Geometry::MDHistoDimension.
Definition at line 88 of file IMDDimension.h.
Referenced by export_IMDDimension().
getDimensionId()
virtual const std::string & Mantid::Geometry::IMDDimension::getDimensionId () const pure virtual
short name which identify the dimension among other dimension.
A dimension can be usually find by its ID and various various method exist to manipulate set of dimensions by their names.
Returns
Dimension ID string.
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), export_IMDDimension(), and Mantid::Geometry::StrictDimensionPolicy::operator()().
getIsIntegrated()
virtual bool Mantid::Geometry::IMDDimension::getIsIntegrated () const inline virtual
Returns
true if the dimension is integrated (e.g. has only one single bin)
Reimplemented in Mantid::API::MWDimension, and Mantid::API::MWXDimension.
Definition at line 91 of file IMDDimension.h.
Referenced by Mantid::Geometry::StrictDimensionPolicy::operator()(), and Mantid::Geometry::MDHistoDimension::toXMLString().
getMaximum()
virtual coord_t Mantid::Geometry::IMDDimension::getMaximum () const pure virtual
Returns
the maximum extent of this dimension
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), and export_IMDDimension().
getMDFrame()
virtual const Geometry::MDFrame & Mantid::Geometry::IMDDimension::getMDFrame () const pure virtual
Returns
the MDFrame
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
getMDUnits()
virtual const Kernel::MDUnit & Mantid::Geometry::IMDDimension::getMDUnits () const pure virtual
Returns
the mdunits of the dimension
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
getMinimum()
virtual coord_t Mantid::Geometry::IMDDimension::getMinimum () const pure virtual
Returns
the minimum extent of this dimension
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), and export_IMDDimension().
getName()
virtual std::string Mantid::Geometry::IMDDimension::getName () const pure virtual
Returns
the name of the dimension as can be displayed along the axis
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), export_IMDDimension(), getName(), and MantidQt::API::PlotAxis::titleFromDimension().
getNBins()
virtual size_t Mantid::Geometry::IMDDimension::getNBins () const pure virtual
Returns
number of bins dimension have (an integrated has one). A axis directed along dimension would have getNBins+1 axis points.
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), and export_IMDDimension().
getNBoundaries()
virtual size_t Mantid::Geometry::IMDDimension::getNBoundaries () const pure virtual
Returns
number of bin boundaries (axis points)
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by export_IMDDimension().
getUnits()
virtual const Kernel::UnitLabel Mantid::Geometry::IMDDimension::getUnits () const pure virtual
Returns
the units of the dimension as a string
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by Mantid::MDAlgorithms::MDWSDescription::buildFromMDWS(), and MantidQt::API::PlotAxis::titleFromDimension().
getX()
virtual coord_t Mantid::Geometry::IMDDimension::getX (size_t ind) const pure virtual
Returns
coordinate of the axis at the given index
Parameters
ind :: index into the axis
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
Referenced by export_IMDDimension().
operator!=()
bool Mantid::Geometry::IMDDimension::operator!= (const IMDDimension &) const inline
Definition at line 94 of file IMDDimension.h.
operator==()
bool Mantid::Geometry::IMDDimension::operator== (const IMDDimension &) const inline
Definition at line 93 of file IMDDimension.h.
setRange()
virtual void Mantid::Geometry::IMDDimension::setRange (size_t nBins, coord_t min, coord_t max) pure virtual
Change the extents and number of bins.
Exceptions
std::invalid_argument If min is greater than max
Implemented in Mantid::Geometry::MDHistoDimension, Mantid::API::MWDimension, and Mantid::API::MWXDimension.
toXMLString()
virtual std::string Mantid::Geometry::IMDDimension::toXMLString () const pure virtual
Returns
an XML string representation of the dimension.
Implemented in Mantid::API::MWDimension, Mantid::API::MWXDimension, and Mantid::Geometry::MDHistoDimension.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/MDGeometry/IMDDimension.h