Mantid: Mantid::Geometry::MatrixVectorPairBuilder Class Reference
Mantid::Geometry::MatrixVectorPairBuilder Class Reference
#include <MatrixVectorPairParser.h>
Public Member Functions
void addCurrentStateToResult ()
Adds currently stored state to the parse result.
void advanceRow ()
Advance to the next row of the matrix/vector pair.
template<typename T >
MatrixVectorPair< T, V3R > getMatrixVectorPair () const
Construct and return the actual matrix/vector pair, the rational matrix components are castd to T.
MatrixVectorPairBuilder ()
void reset ()
Completely reset the builder, including stored preliminary results.
void resetAccumulatedResults ()
Reset all accumulated results.
void resetState ()
Reset the current state, i.e. the state representing the current row.
void setCurrentDirection (const std::string &vector)
Set the direction vector to one of the stored values that correspond to x, y or z.
void setCurrentFactor (const ParsedRationalNumber &rationalNumberComponents)
Set the current factor, which is a rational number.
void setCurrentSignNegative ()
Make the current sign negative.
void setCurrentSignPositive ()
Make the current sign positive.
Private Attributes
V3R m_currentDirection
RationalNumber m_currentFactor
size_t m_currentRow
int m_currentSign
std::map< std::string, V3R > m_directions
std::vector< V3R > m_matrixRows
V3R m_vector
Detailed Description
Definition at line 24 of file MatrixVectorPairParser.h.
Constructor & Destructor Documentation
MatrixVectorPairBuilder()
Mantid::Geometry::MatrixVectorPairBuilder::MatrixVectorPairBuilder () inline
Definition at line 26 of file MatrixVectorPairParser.h.
References m_directions, and reset().
Member Function Documentation
addCurrentStateToResult()
void Mantid::Geometry::MatrixVectorPairBuilder::addCurrentStateToResult () inline
Adds currently stored state to the parse result.
This function takes the current factor, sign and direction that were assigned using the respective functions and adds to the stored intermediate result.
If the current direction is (0,0,0) then the currently processed component is only a rational number that should go into the vector component of the row that's currently being assembled. Otherwise the direction vector should be multiplied by the rational number and added to the matrix row.
After that, the current state is reset so that the next part of the current component can be processed.
Definition at line 97 of file MatrixVectorPairParser.h.
References m_currentDirection, m_currentFactor, m_currentRow, m_currentSign, m_matrixRows, m_vector, and resetState().
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
advanceRow()
void Mantid::Geometry::MatrixVectorPairBuilder::advanceRow () inline
Advance to the next row of the matrix/vector pair.
Definition at line 114 of file MatrixVectorPairParser.h.
References m_currentRow, and resetState().
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
getMatrixVectorPair()
template<typename T > MatrixVectorPair< T, V3R > Mantid::Geometry::MatrixVectorPairBuilder::getMatrixVectorPair () const inline
Construct and return the actual matrix/vector pair, the rational matrix components are castd to T.
Definition at line 38 of file MatrixVectorPairParser.h.
References m_currentRow, m_matrixRows, m_vector, Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by Mantid::Geometry::parseMatrixVectorPair().
reset()
void Mantid::Geometry::MatrixVectorPairBuilder::reset () inline
Completely reset the builder, including stored preliminary results.
Definition at line 120 of file MatrixVectorPairParser.h.
References resetAccumulatedResults(), and resetState().
Referenced by MatrixVectorPairBuilder().
resetAccumulatedResults()
void Mantid::Geometry::MatrixVectorPairBuilder::resetAccumulatedResults () inline
Reset all accumulated results.
Definition at line 133 of file MatrixVectorPairParser.h.
References m_currentRow, m_matrixRows, and m_vector.
Referenced by reset().
resetState()
void Mantid::Geometry::MatrixVectorPairBuilder::resetState () inline
Reset the current state, i.e. the state representing the current row.
Definition at line 126 of file MatrixVectorPairParser.h.
References m_currentDirection, m_currentFactor, and m_currentSign.
Referenced by addCurrentStateToResult(), advanceRow(), and reset().
setCurrentDirection()
void Mantid::Geometry::MatrixVectorPairBuilder::setCurrentDirection (const std::string & vector) inline
Set the direction vector to one of the stored values that correspond to x, y or z.
Definition at line 73 of file MatrixVectorPairParser.h.
References m_currentDirection, and m_directions.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
setCurrentFactor()
void Mantid::Geometry::MatrixVectorPairBuilder::setCurrentFactor (const ParsedRationalNumber & rationalNumberComponents) inline
Set the current factor, which is a rational number.
Depending on whether a direction definition follows, it's processed differently later on.
Definition at line 56 of file MatrixVectorPairParser.h.
References m_currentFactor.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
setCurrentSignNegative()
void Mantid::Geometry::MatrixVectorPairBuilder::setCurrentSignNegative () inline
Make the current sign negative.
Definition at line 76 of file MatrixVectorPairParser.h.
References m_currentSign.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
setCurrentSignPositive()
void Mantid::Geometry::MatrixVectorPairBuilder::setCurrentSignPositive () inline
Make the current sign positive.
Definition at line 79 of file MatrixVectorPairParser.h.
References m_currentSign.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
Member Data Documentation
m_currentDirection
V3R Mantid::Geometry::MatrixVectorPairBuilder::m_currentDirection private
Definition at line 146 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), resetState(), and setCurrentDirection().
m_currentFactor
RationalNumber Mantid::Geometry::MatrixVectorPairBuilder::m_currentFactor private
Definition at line 145 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), resetState(), and setCurrentFactor().
m_currentRow
size_t Mantid::Geometry::MatrixVectorPairBuilder::m_currentRow private
Definition at line 149 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), advanceRow(), getMatrixVectorPair(), and resetAccumulatedResults().
m_currentSign
int Mantid::Geometry::MatrixVectorPairBuilder::m_currentSign private
Definition at line 147 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), resetState(), setCurrentSignNegative(), and setCurrentSignPositive().
m_directions
std::map<std::string, V3R> Mantid::Geometry::MatrixVectorPairBuilder::m_directions private
Definition at line 140 of file MatrixVectorPairParser.h.
Referenced by MatrixVectorPairBuilder(), and setCurrentDirection().
m_matrixRows
std::vector<V3R> Mantid::Geometry::MatrixVectorPairBuilder::m_matrixRows private
Definition at line 142 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), getMatrixVectorPair(), and resetAccumulatedResults().
m_vector
V3R Mantid::Geometry::MatrixVectorPairBuilder::m_vector private
Definition at line 143 of file MatrixVectorPairParser.h.
Referenced by addCurrentStateToResult(), getMatrixVectorPair(), and resetAccumulatedResults().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/MatrixVectorPairParser.h