Mantid: ICat4::ns1__entityInfo Class Reference
ICat4::ns1__entityInfo Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__entityInfo ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * classComment
std::vector< class ns1__constraint * > constraints
std::vector< class ns1__entityField * > fields
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1111 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__entityInfo()
ICat4::ns1__entityInfo::ns1__entityInfo () inline
Definition at line 1124 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__entityInfo::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8039 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__constraint(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__entityField().
Referenced by ICat4::soap_in_ns1__entityInfo(), ICat4::soap_new_req_ns1__entityInfo(), and ICat4::soap_new_set_ns1__entityInfo().
soap_get()
void * ICat4::ns1__entityInfo::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8147 of file ICat4C.cpp.
References ICat4::soap_get_ns1__entityInfo().
soap_in()
void * ICat4::ns1__entityInfo::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8077 of file ICat4C.cpp.
References ICat4::soap_in_ns1__entityInfo().
Referenced by ICat4::soap_in_ns1__entityInfo().
soap_out()
int ICat4::ns1__entityInfo::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8057 of file ICat4C.cpp.
References ICat4::soap_out_ns1__entityInfo().
soap_put()
int ICat4::ns1__entityInfo::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8140 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__entityInfo.
soap_serialize()
void ICat4::ns1__entityInfo::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 8047 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__constraint(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__entityField().
soap_type()
int ICat4::ns1__entityInfo::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1117 of file ICat4Stub.h.
Member Data Documentation
classComment
std::string* ICat4::ns1__entityInfo::classComment
Definition at line 1113 of file ICat4Stub.h.
constraints
std::vector<class ns1__constraint *> ICat4::ns1__entityInfo::constraints
Definition at line 1114 of file ICat4Stub.h.
fields
std::vector<class ns1__entityField *> ICat4::ns1__entityInfo::fields
Definition at line 1115 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp