Mantid: Mantid::DataObjects::MDFramesToSpecialCoordinateSystem Class Reference
Mantid::DataObjects::MDFramesToSpecialCoordinateSystem Class Reference
MDFrameFromMDWorkspace: Each dimension of the MDWorkspace contains an MDFrame.
#include <MDFramesToSpecialCoordinateSystem.h>
Public Member Functions
std::optional< Mantid::Kernel::SpecialCoordinateSystem > operator() (const Mantid::API::IMDWorkspace *workspace) const
Get the Special Coordinate System based on the MDFrame information.
Private Member Functions
void checkQCompatibility (Mantid::Kernel::SpecialCoordinateSystem specialCoordinateSystem, std::optional< Mantid::Kernel::SpecialCoordinateSystem > qFrameType) const
Make sure that the QFrame types are the same.
bool isUnknownFrame (const Mantid::Geometry::IMDDimension_const_sptr &dimension) const
Detailed Description
MDFrameFromMDWorkspace: Each dimension of the MDWorkspace contains an MDFrame.
The acutal frame which is common to all dimensions is extracted.
Definition at line 20 of file MDFramesToSpecialCoordinateSystem.h.
Member Function Documentation
checkQCompatibility()
void Mantid::DataObjects::MDFramesToSpecialCoordinateSystem::checkQCompatibility (Mantid::Kernel::SpecialCoordinateSystem specialCoordinateSystem, std::optional< Mantid::Kernel::SpecialCoordinateSystem > qFrameType) const private
Make sure that the QFrame types are the same.
Parameters
specialCoordinateSystem the q frame type to test.
qFrameType the current q frame type
Definition at line 76 of file MDFramesToSpecialCoordinateSystem.cpp.
Referenced by operator()().
isUnknownFrame()
bool Mantid::DataObjects::MDFramesToSpecialCoordinateSystem::isUnknownFrame (const Mantid::Geometry::IMDDimension_const_sptr & dimension) const private
Definition at line 92 of file MDFramesToSpecialCoordinateSystem.cpp.
Referenced by operator()().
operator()()
std::optional< Mantid::Kernel::SpecialCoordinateSystem > Mantid::DataObjects::MDFramesToSpecialCoordinateSystem::operator() (const Mantid::API::IMDWorkspace * workspace) const
Get the Special Coordinate System based on the MDFrame information.
Parameters
workspace the workspace which is being queried
Returns
either a special coordinate or an empty optional
Definition at line 20 of file MDFramesToSpecialCoordinateSystem.cpp.
References checkQCompatibility(), isUnknownFrame(), Mantid::Kernel::None, and workspace.
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/MDFramesToSpecialCoordinateSystem.h
Framework/DataObjects/src/MDFramesToSpecialCoordinateSystem.cpp