Mantid: Mantid::Kernel::Timer Class Reference
Mantid::Kernel::Timer Class Reference
A simple class that provides a wall-clock (not processor time) timer.
#include <Timer.h>
Public Member Functions
float elapsed (bool reset=true)
Returns the wall-clock time elapsed in seconds since the Timer object's creation, or the last call to elapsed.
float elapsed_no_reset () const
Returns the wall-clock time elapsed in seconds since the Timer object's creation, or the last call to elapsed.
void reset ()
Explicitly reset the timer.
std::string str () const
Convert the elapsed time (without reseting) to a string.
Timer ()
Constructor.
virtual ~Timer ()=default
Private Attributes
time_point_ns m_start
The starting time.
Detailed Description
A simple class that provides a wall-clock (not processor time) timer.
Author
Russell Taylor, Tessella plc
Date
29/04/2010
Definition at line 27 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Mantid::Kernel::Timer::Timer ()
Constructor.
Instantiating the object starts the timer.
Definition at line 20 of file Timer.cpp.
~Timer()
virtual Mantid::Kernel::Timer::~Timer () virtual default
Member Function Documentation
elapsed()
float Mantid::Kernel::Timer::elapsed (bool reset = true)
Returns the wall-clock time elapsed in seconds since the Timer object's creation, or the last call to elapsed.
Parameters
reset :: set to true to reset the clock (default)
Returns
time in seconds
Definition at line 28 of file Timer.cpp.
References elapsed_no_reset(), and reset().
Referenced by Mantid::Kernel::CPUTimer::CPUfraction(), Mantid::API::Algorithm::doCallProcessGroups(), Mantid::Kernel::CPUTimer::elapsedWallClock(), Mantid::API::Algorithm::executeInternal(), Mantid::MDAlgorithms::LoadSQW2::readPixelDataIntoWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::setupBoxController().
elapsed_no_reset()
float Mantid::Kernel::Timer::elapsed_no_reset () const
Returns the wall-clock time elapsed in seconds since the Timer object's creation, or the last call to elapsed.
Returns
time in seconds
Definition at line 40 of file Timer.cpp.
References m_start.
Referenced by elapsed(), MantidQt::MantidWidgets::NotificationService::showMessage(), Mantid::Kernel::CPUTimer::str(), str(), and MantidQt::MantidWidgets::AlgorithmProgressPresenter::updateProgressBarSlot().
reset()
void Mantid::Kernel::Timer::reset ()
Explicitly reset the timer.
Definition at line 48 of file Timer.cpp.
References m_start.
Referenced by elapsed(), Mantid::Kernel::CPUTimer::reset(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::ProcessBankData::run(), MantidQt::MantidWidgets::NotificationService::showMessage(), and MantidQt::MantidWidgets::AlgorithmProgressPresenter::updateProgressBarSlot().
str()
std::string Mantid::Kernel::Timer::str () const
Convert the elapsed time (without reseting) to a string.
Definition at line 51 of file Timer.cpp.
References elapsed_no_reset().
Member Data Documentation
m_start
time_point_ns Mantid::Kernel::Timer::m_start private
The starting time.
Definition at line 38 of file Timer.h.
Referenced by elapsed_no_reset(), and reset().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Timer.h
Framework/Kernel/src/Timer.cpp