Mantid: Mantid::Algorithms::RealFFT::PropertyNames Namespace Reference
Mantid::Algorithms::RealFFT::PropertyNames Namespace Reference
Functions
std::string const IGNORE_X_BINS ("IgnoreXBins")
std::string const INPUT_WKSP ("InputWorkspace")
std::string const OUTPUT_WKSP ("OutputWorkspace")
std::string const TRANSFORM ("Transform")
std::string const WKSP_INDEX ("WorkspaceIndex")
Function Documentation
IGNORE_X_BINS()
std::string const Mantid::Algorithms::RealFFT::PropertyNames::IGNORE_X_BINS ("IgnoreXBins") inline private
Referenced by Mantid::Algorithms::RealFFT::RealFFT::actuallyValidateInputs(), and Mantid::Algorithms::RealFFT::RealFFT::init().
INPUT_WKSP()
std::string const Mantid::Algorithms::RealFFT::PropertyNames::INPUT_WKSP ("InputWorkspace") inline private
Referenced by Mantid::Algorithms::RealFFT::RealFFT::actuallyValidateInputs(), Mantid::Algorithms::RealFFT::RealFFT::exec(), Mantid::Algorithms::RealFFT::RealFFT::init(), and Mantid::Algorithms::RealFFT::RealFFT::validateInputs().
OUTPUT_WKSP()
std::string const Mantid::Algorithms::RealFFT::PropertyNames::OUTPUT_WKSP ("OutputWorkspace") inline private
Referenced by Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Algorithms::RealFFT::RealFFT::init().
TRANSFORM()
std::string const Mantid::Algorithms::RealFFT::PropertyNames::TRANSFORM ("Transform") inline private
Referenced by Mantid::Algorithms::RealFFT::RealFFT::actuallyValidateInputs(), Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Algorithms::RealFFT::RealFFT::init().
WKSP_INDEX()
std::string const Mantid::Algorithms::RealFFT::PropertyNames::WKSP_INDEX ("WorkspaceIndex") inline private
Referenced by Mantid::Algorithms::RealFFT::RealFFT::actuallyValidateInputs(), Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Algorithms::RealFFT::RealFFT::init().