Mantid: Framework/PythonInterface/mantid/api/src/Exports/FileFinder.cpp File Reference
FileFinder.cpp File Reference
#include "MantidAPI/FileFinder.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/ReleaseGlobalInterpreterLock.h"
#include <boost/python/class.hpp>
#include <boost/python/list.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/reference_existing_object.hpp>
Functions
void export_FileFinder ()
std::vector< std::string > runFinderProxy (const FileFinderImpl &self, const std::string &hintstr, list exts_list, const bool useExtsOnly)
Runs FileFinder.findRuns after releasing the python GIL.
Function Documentation
export_FileFinder()
void export_FileFinder ()
Definition at line 56 of file FileFinder.cpp.
References Mantid::API::FileFinderImpl::getCaseSensitive(), Mantid::API::FileFinderImpl::getFullPath(), runFinderProxy(), and Mantid::API::FileFinderImpl::setCaseSensitive().
runFinderProxy()
std::vector< std::string > runFinderProxy (const FileFinderImpl & self, const std::string & hintstr, list exts_list, const bool useExtsOnly)
Runs FileFinder.findRuns after releasing the python GIL.
Parameters
self :: A reference to the calling object
hintstr :: A string containing the run number and possibly instrument to search for
exts_list :: A python list containing strings of file extensions to search
useExtsOnly :: bool. If true, use exts_list only. If false, use combination of exts_list and facility_exts.
Definition at line 41 of file FileFinder.cpp.
Referenced by export_FileFinder().