Mantid: Mantid::DataHandling::LoadILLSANS Class Reference
Mantid::DataHandling::LoadILLSANS Class Reference
LoadILLSANS; supports D11, D22 and D33 (TOF/monochromatic)
#include <LoadILLSANS.h>
Classes
struct DetectorPosition
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
int confidence (Kernel::NexusDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadILLSANS ()
Constructor.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::NexusDescriptor >
virtual int confidence (Kernel::NexusDescriptor &descriptor) const=0
Returns a confidence value that this algorithm can load a file.
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Types
enum MultichannelType { TOF , KINETIC , SCAN }
Private Member Functions
void adjustTOF ()
Adjusts pixel by pixel the wavelength axis Used only for D33 in TOF mode.
void createEmptyWorkspace (const size_t, const size_t, const MultichannelType type=MultichannelType::TOF)
Create a workspace without any data in it.
void exec () override
Execute the algorithm.
Kernel::V3D getComponentPosition (const std::string &componentName)
Get position of a component.
void getDataDimensions (const NeXus::NXInt &data, int &numberOfChannels, int &numberOfTubes, int &numberOfPixelsPerTube)
LoadILLSANS::getDataDimensions Retrieves physical dimensions of the data from the dataset dimensions.
DetectorPosition getDetectorPositionD33 (const NeXus::NXEntry &, const std::string &)
Get detector panel distances from the nexus file.
std::string getInstrumentFilePath (const std::string &) const
Makes up the full path of the relevant IDF dependent on resolution mode.
std::vector< double > getOmegaBinning (const NeXus::NXEntry &entry, const std::string &path) const
LoadILLSANS::getOmegaBinning Get the binning for an omega scan for D16B files.
std::vector< double > getVariableTimeBinning (const NeXus::NXEntry &, const std::string &, const NeXus::NXInt &, const NeXus::NXFloat &) const
Returns the wavelength axis computed in VTOF mode.
void init () override
Initialize the algorithm's properties.
void initWorkSpace (NeXus::NXEntry &, const std::string &)
Loads data for D11, D16 and D22.
void initWorkSpaceD11B (NeXus::NXEntry &, const std::string &)
LoadILLSANS::initWorkSpaceD11B Load D11B data.
void initWorkSpaceD16 (NeXus::NXEntry &, const std::string &)
void initWorkSpaceD22B (NeXus::NXEntry &, const std::string &)
LoadILLSANS::initWorkSpaceD22B Load D22B data.
void initWorkSpaceD33 (NeXus::NXEntry &, const std::string &)
Loads data for D33.
size_t loadDataFromD16ScanMonitors (const NeXus::NXEntry &firstEntry, size_t firstIndex, const std::vector< double > &binning)
Load data from D16B's monitor.
size_t loadDataFromMonitors (NeXus::NXEntry &firstEntry, size_t firstIndex=0, const MultichannelType type=MultichannelType::TOF)
Loads data from all the monitors.
size_t loadDataFromTubes (NeXus::NXInt &, const std::vector< double > &, size_t, const MultichannelType type=MultichannelType::TOF)
Loads data from tubes.
void loadMetaData (const NeXus::NXEntry &, const std::string &)
Loads some metadata present in the nexus file.
void moveDetectorDistance (double distance, const std::string &componentName)
Move detectors in Z axis (X,Y are kept constant)
void moveDetectorHorizontal (double, const std::string &)
Move detectors in X.
void moveDetectorsD33 (const DetectorPosition &)
Move the detector banks for D33.
void moveDetectorVertical (double, const std::string &)
Move detectors in Y.
void moveSource ()
Moves the source to the middle of the two master choppers Used only for D33 in TOF mode.
void placeD16 (double, double, const std::string &)
LoadILLSANS::placeD16 : place the D16 detector.
void rotateInstrument (double, const std::string &)
Rotates instrument detector around y-axis in place.
void runLoadInstrument ()
Loads the instrument from the IDF.
void setFinalProperties (const std::string &filename)
Sets full sample logs.
void setInstrumentName (const NeXus::NXEntry &, const std::string &)
Set member variable with the instrument name.
void setNumberOfMonitors ()
LoadILLSANS::setNumberOfMonitors Set the number of monitor attribute depending on the instrument loaded.
Private Attributes
std::vector< double > m_defaultBinning
the default x-axis binning
std::string m_instrumentName
Name of the instrument.
bool m_isD16Omega
Data comes from a D16 omega scan flag.
bool m_isTOF
TOF or monochromatic flag.
API::MatrixWorkspace_sptr m_localWorkspace
to-be output workspace
size_t m_numberOfMonitors
Number of monitors in this instrument.
std::string m_resMode
Resolution mode for D11 and D22.
double m_sourcePos
Source Z (for D33 TOF)
std::vector< std::string > m_supportedInstruments
List of supported instruments.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::ParallelAlgorithm
Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const override
Get correct execution mode based on input storage modes for an MPI run.
~ParallelAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadILLSANS; supports D11, D22 and D33 (TOF/monochromatic)
Definition at line 20 of file LoadILLSANS.h.
Member Enumeration Documentation
MultichannelType
enum Mantid::DataHandling::LoadILLSANS::MultichannelType private
Enumerator
TOF
KINETIC
SCAN
Definition at line 32 of file LoadILLSANS.h.
Constructor & Destructor Documentation
LoadILLSANS()
Mantid::DataHandling::LoadILLSANS::LoadILLSANS ()
Constructor.
Definition at line 43 of file LoadILLSANS.cpp.
Member Function Documentation
adjustTOF()
void Mantid::DataHandling::LoadILLSANS::adjustTOF () private
Adjusts pixel by pixel the wavelength axis Used only for D33 in TOF mode.
Definition at line 1032 of file LoadILLSANS.cpp.
References index, Mantid::Kernel::l2, lambda, m_localWorkspace, m_numberOfMonitors, m_sourcePos, PARALLEL_FOR_IF, Mantid::Kernel::threadSafe(), Mantid::Geometry::x, and Mantid::Geometry::z.
Referenced by exec().
category()
const std::string Mantid::DataHandling::LoadILLSANS::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 55 of file LoadILLSANS.cpp.
confidence()
int Mantid::DataHandling::LoadILLSANS::confidence (Kernel::NexusDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::NexusDescriptor >.
Definition at line 70 of file LoadILLSANS.cpp.
References Mantid::Kernel::NexusDescriptor::pathExists().
createEmptyWorkspace()
void Mantid::DataHandling::LoadILLSANS::createEmptyWorkspace (const size_t numberOfHistograms, const size_t numberOfChannels, const MultichannelType type = MultichannelType::TOF) private
Create a workspace without any data in it.
Parameters
numberOfHistograms : number of spectra
numberOfChannels : number of TOF channels
type : type of the multichannel workspace (TOF (default) or Kinetic)
Definition at line 756 of file LoadILLSANS.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), KINETIC, m_isD16Omega, m_localWorkspace, SCAN, and TOF.
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), and initWorkSpaceD33().
exec()
void Mantid::DataHandling::LoadILLSANS::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 101 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), adjustTOF(), Mantid::DataHandling::LoadHelper::findInstrumentNexusPath(), getComponentPosition(), getDetectorPositionD33(), Mantid::DataHandling::LoadHelper::getDoubleFromNexusPath(), Mantid::NeXus::NXClass::getFloat(), Mantid::API::Algorithm::getPropertyValue(), initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), initWorkSpaceD33(), m_instrumentName, m_isD16Omega, m_isTOF, m_localWorkspace, moveDetectorDistance(), moveDetectorHorizontal(), moveDetectorsD33(), moveSource(), Mantid::NeXus::NXRoot::openFirstEntry(), placeD16(), Mantid::API::Algorithm::progress(), rotateInstrument(), runLoadInstrument(), setFinalProperties(), setInstrumentName(), setNumberOfMonitors(), Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::Kernel::V3D::Z().
getComponentPosition()
V3D Mantid::DataHandling::LoadILLSANS::getComponentPosition (const std::string & componentName) private
Get position of a component.
Parameters
componentName : the name of the component
Returns
: V3D of the component position
Definition at line 937 of file LoadILLSANS.cpp.
References m_localWorkspace.
Referenced by exec(), moveDetectorDistance(), moveDetectorHorizontal(), and moveDetectorVertical().
getDataDimensions()
void Mantid::DataHandling::LoadILLSANS::getDataDimensions (const NeXus::NXInt & data, int & numberOfChannels, int & numberOfTubes, int & numberOfPixelsPerTube) private
LoadILLSANS::getDataDimensions Retrieves physical dimensions of the data from the dataset dimensions.
Parameters
data the data set to take the dimensions from
numberOfChannels
numberOfTubes
numberOfPixelsPerTube
Definition at line 258 of file LoadILLSANS.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSet::dim2(), Mantid::API::g_log, and m_isD16Omega.
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), and loadDataFromTubes().
getDetectorPositionD33()
LoadILLSANS::DetectorPosition Mantid::DataHandling::LoadILLSANS::getDetectorPositionD33 (const NeXus::NXEntry & firstEntry, const std::string & instrumentNamePath) private
Get detector panel distances from the nexus file.
Parameters
firstEntry : already opened first entry in nexus
instrumentNamePath : the path inside nexus where the instrument name is written
Returns
a structure with the positions
Definition at line 228 of file LoadILLSANS.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleBottomTop, Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleRear, Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleRightLeft, Mantid::API::g_log, Mantid::DataHandling::LoadHelper::getDoubleFromNexusPath(), Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftDown, Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftLeft, Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftRight, and Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftUp.
Referenced by exec().
getInstrumentFilePath()
std::string Mantid::DataHandling::LoadILLSANS::getInstrumentFilePath (const std::string & instName) const private
Makes up the full path of the relevant IDF dependent on resolution mode.
Parameters
instName : the name of the instrument (including the resolution mode suffix)
Returns
: the full path to the corresponding IDF
Definition at line 785 of file LoadILLSANS.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by runLoadInstrument().
getOmegaBinning()
std::vector< double > Mantid::DataHandling::LoadILLSANS::getOmegaBinning (const NeXus::NXEntry & entry, const std::string & path) const private
LoadILLSANS::getOmegaBinning Get the binning for an omega scan for D16B files.
Parameters
entry opened root nexus entry
path path of the scanned variables entry
Returns
the omega binning vector
Definition at line 1083 of file LoadILLSANS.cpp.
References Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::NeXus::NXData::openDoubleData(), and Mantid::NeXus::NXEntry::openNXData().
Referenced by initWorkSpace().
getVariableTimeBinning()
std::vector< double > Mantid::DataHandling::LoadILLSANS::getVariableTimeBinning (const NeXus::NXEntry & entry, const std::string & path, const NeXus::NXInt & sum, const NeXus::NXFloat & times) const private
Returns the wavelength axis computed in VTOF mode.
Parameters
entry : opened root nexus entry
path : path of the detector distance entry
sum : loaded channel width sums
times : loaded channel width times
Returns
binning : wavelength bin boundaries
Definition at line 1106 of file LoadILLSANS.cpp.
References Mantid::Kernel::VectorHelper::convertToBinBoundary(), Mantid::NeXus::NXDataSet::dim0(), Mantid::PhysicalConstants::h, lambda, Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::PhysicalConstants::NeutronMass, and Mantid::NeXus::NXClass::openNXFloat().
Referenced by initWorkSpaceD33().
init()
void Mantid::DataHandling::LoadILLSANS::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 86 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
initWorkSpace()
void Mantid::DataHandling::LoadILLSANS::initWorkSpace (NeXus::NXEntry & firstEntry, const std::string & instrumentPath) private
Loads data for D11, D16 and D22.
Parameters
firstEntry : already opened first entry in nexus
instrumentPath : the path inside nexus where the instrument name is written
Definition at line 279 of file LoadILLSANS.cpp.
References Mantid::NeXus::NXClass::containsGroup(), createEmptyWorkspace(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSet::dim2(), Mantid::API::g_log, getDataDimensions(), getOmegaBinning(), Mantid::NeXus::NXDataSetTyped< T >::load(), loadDataFromD16ScanMonitors(), loadDataFromMonitors(), loadDataFromTubes(), loadMetaData(), m_defaultBinning, m_instrumentName, m_isD16Omega, m_numberOfMonitors, m_resMode, Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), SCAN, setNumberOfMonitors(), and TOF.
Referenced by exec().
initWorkSpaceD11B()
void Mantid::DataHandling::LoadILLSANS::initWorkSpaceD11B (NeXus::NXEntry & firstEntry, const std::string & instrumentPath) private
LoadILLSANS::initWorkSpaceD11B Load D11B data.
Parameters
firstEntry : already opened first entry in nexus
instrumentPath : the path inside nexus where the instrument name is written
Definition at line 340 of file LoadILLSANS.cpp.
References createEmptyWorkspace(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::API::g_log, getDataDimensions(), KINETIC, Mantid::NeXus::NXDataSetTyped< T >::load(), loadDataFromMonitors(), loadDataFromTubes(), loadMetaData(), m_defaultBinning, m_localWorkspace, m_numberOfMonitors, Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXFloat(), and TOF.
Referenced by exec().
initWorkSpaceD16()
void Mantid::DataHandling::LoadILLSANS::initWorkSpaceD16 (NeXus::NXEntry & , const std::string &) private
initWorkSpaceD22B()
void Mantid::DataHandling::LoadILLSANS::initWorkSpaceD22B (NeXus::NXEntry & firstEntry, const std::string & instrumentPath) private
LoadILLSANS::initWorkSpaceD22B Load D22B data.
Parameters
firstEntry : already opened first entry in nexus
instrumentPath : the path inside nexus where the instrument name is written
Definition at line 402 of file LoadILLSANS.cpp.
References createEmptyWorkspace(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::API::g_log, getDataDimensions(), KINETIC, Mantid::NeXus::NXDataSetTyped< T >::load(), loadDataFromMonitors(), loadDataFromTubes(), loadMetaData(), m_defaultBinning, m_localWorkspace, m_numberOfMonitors, Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXFloat(), runLoadInstrument(), and TOF.
Referenced by exec().
initWorkSpaceD33()
void Mantid::DataHandling::LoadILLSANS::initWorkSpaceD33 (NeXus::NXEntry & firstEntry, const std::string & instrumentPath) private
Loads data for D33.
Parameters
firstEntry : already opened first entry in nexus
instrumentPath : the path inside nexus where the instrument name is written
Definition at line 463 of file LoadILLSANS.cpp.
References createEmptyWorkspace(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSet::dim2(), Mantid::API::g_log, Mantid::NeXus::NXClass::getFloat(), Mantid::DataHandling::LoadHelper::getTimeBinningFromNexusPath(), getVariableTimeBinning(), Mantid::NeXus::NXDataSetTyped< T >::load(), loadDataFromMonitors(), loadDataFromTubes(), loadMetaData(), m_defaultBinning, m_instrumentName, m_isTOF, m_numberOfMonitors, m_sourcePos, Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXFloat(), Mantid::NeXus::NXClass::openNXInt(), and std::to_string().
Referenced by exec().
loadDataFromD16ScanMonitors()
size_t Mantid::DataHandling::LoadILLSANS::loadDataFromD16ScanMonitors (const NeXus::NXEntry & firstEntry, size_t firstIndex, const std::vector< double > & binning) private
Load data from D16B's monitor.
These data are not stored in the usual NXmonitor field, but rather in the scanned variables, so it uses a completely different logic.
Parameters
firstEntry already opened first entry in nexus
firstIndex the workspace index to load the first monitor to
binning the binning to assign the monitor values
Returns
the new workspace index on which to load next
Definition at line 622 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_instrumentName, m_localWorkspace, Mantid::NeXus::NXData::openDoubleData(), and Mantid::NeXus::NXEntry::openNXData().
Referenced by initWorkSpace().
loadDataFromMonitors()
size_t Mantid::DataHandling::LoadILLSANS::loadDataFromMonitors (NeXus::NXEntry & firstEntry, size_t firstIndex = 0, const MultichannelType type = MultichannelType::TOF) private
Loads data from all the monitors.
Parameters
firstEntry : already opened first entry in nexus
firstIndex : the workspace index to load the first monitor to
type : used to discrimante between TOF and Kinetic
Returns
the next ws index after all the monitors
Definition at line 572 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSet::dim2(), Mantid::API::g_log, Mantid::NeXus::NXClass::groups(), KINETIC, Mantid::NeXus::NXDataSetTyped< T >::load(), m_defaultBinning, m_isTOF, m_localWorkspace, Mantid::NeXus::NXData::openIntData(), and Mantid::NeXus::NXEntry::openNXData().
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), and initWorkSpaceD33().
loadDataFromTubes()
size_t Mantid::DataHandling::LoadILLSANS::loadDataFromTubes (NeXus::NXInt & data, const std::vector< double > & timeBinning, size_t firstIndex = 0, const MultichannelType type = MultichannelType::TOF) private
Loads data from tubes.
Parameters
data : a reference to already loaded nexus data block
timeBinning : the x-axis binning
firstIndex : the workspace index to start loading to
type : used to discrimante between TOF and Kinetic
Returns
the next ws index after all the tubes in the given detector bank
Definition at line 689 of file LoadILLSANS.cpp.
References getDataDimensions(), index, KINETIC, m_instrumentName, m_isD16Omega, m_localWorkspace, PARALLEL_FOR_IF, and Mantid::Kernel::threadSafe().
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), and initWorkSpaceD33().
loadMetaData()
void Mantid::DataHandling::LoadILLSANS::loadMetaData (const NeXus::NXEntry & entry, const std::string & instrumentNamePath) private
Loads some metadata present in the nexus file.
Parameters
entry : opened nexus entry
instrumentNamePath : the nexus entry of the instrument
Definition at line 948 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::DataHandling::LoadHelper::calculateEnergy(), Mantid::DataHandling::LoadHelper::dateTimeInIsoFormat(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::NeXus::NXClass::getFloat(), Mantid::API::Algorithm::getPointerToProperty(), Mantid::API::Algorithm::getProperty(), Mantid::NeXus::NXClass::getString(), Mantid::Kernel::Logger::information(), Mantid::Kernel::Property::isDefault(), m_defaultBinning, m_instrumentName, and m_localWorkspace.
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), and initWorkSpaceD33().
moveDetectorDistance()
void Mantid::DataHandling::LoadILLSANS::moveDetectorDistance (double distance, const std::string & componentName) private
Move detectors in Z axis (X,Y are kept constant)
Parameters
distance : the distance to move along Z axis [meters]
componentName : name of the component to move
Definition at line 837 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, getComponentPosition(), m_localWorkspace, Mantid::Kernel::V3D::X(), and Mantid::Kernel::V3D::Y().
Referenced by exec(), and moveDetectorsD33().
moveDetectorHorizontal()
void Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal (double shift, const std::string & componentName) private
Move detectors in X.
Parameters
shift : the distance to move [metres]
componentName : the name of the component
Definition at line 901 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, getComponentPosition(), m_localWorkspace, Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by exec(), and moveDetectorsD33().
moveDetectorsD33()
void Mantid::DataHandling::LoadILLSANS::moveDetectorsD33 (const DetectorPosition & detPos) private
Move the detector banks for D33.
Parameters
detPos : structure holding the positions
Definition at line 814 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleBottomTop, Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleRear, Mantid::DataHandling::LoadILLSANS::DetectorPosition::distanceSampleRightLeft, m_localWorkspace, moveDetectorDistance(), moveDetectorHorizontal(), moveDetectorVertical(), Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftDown, Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftLeft, Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftRight, and Mantid::DataHandling::LoadILLSANS::DetectorPosition::shiftUp.
Referenced by exec().
moveDetectorVertical()
void Mantid::DataHandling::LoadILLSANS::moveDetectorVertical (double shift, const std::string & componentName) private
Move detectors in Y.
Parameters
shift : the distance to move [metres]
componentName : the name of the component
Definition at line 919 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, getComponentPosition(), m_localWorkspace, Mantid::Kernel::V3D::X(), and Mantid::Kernel::V3D::Z().
Referenced by moveDetectorsD33().
moveSource()
void Mantid::DataHandling::LoadILLSANS::moveSource () private
Moves the source to the middle of the two master choppers Used only for D33 in TOF mode.
Definition at line 1065 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), m_localWorkspace, and m_sourcePos.
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadILLSANS::name () const override virtual
Algorithm's name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 49 of file LoadILLSANS.cpp.
placeD16()
void Mantid::DataHandling::LoadILLSANS::placeD16 (double angle, double distance, const std::string & componentName) private
LoadILLSANS::placeD16 : place the D16 detector.
Parameters
angle : the angle between its center and the transmitted beam
distance : the distance between its center and the sample
componentName : "detector"
Definition at line 877 of file LoadILLSANS.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, m_localWorkspace, and rotateInstrument().
Referenced by exec().
rotateInstrument()
void Mantid::DataHandling::LoadILLSANS::rotateInstrument (double angle, const std::string & componentName) private
Rotates instrument detector around y-axis in place.
Parameters
angle : the angle to rotate [degree]
componentName : "detector"
Definition at line 858 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, and m_localWorkspace.
Referenced by exec(), and placeD16().
runLoadInstrument()
void Mantid::DataHandling::LoadILLSANS::runLoadInstrument () private
Loads the instrument from the IDF.
Definition at line 796 of file LoadILLSANS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), getInstrumentFilePath(), m_instrumentName, m_localWorkspace, and m_resMode.
Referenced by exec(), and initWorkSpaceD22B().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadILLSANS::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 26 of file LoadILLSANS.h.
setFinalProperties()
void Mantid::DataHandling::LoadILLSANS::setFinalProperties (const std::string & filename) private
Sets full sample logs.
Parameters
filename : name of the file
Definition at line 1018 of file LoadILLSANS.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), and m_localWorkspace.
Referenced by exec().
setInstrumentName()
void Mantid::DataHandling::LoadILLSANS::setInstrumentName (const NeXus::NXEntry & firstEntry, const std::string & instrumentNamePath) private
Set member variable with the instrument name.
Parameters
firstEntry already opened first entry in nexus
instrumentNamePath : the path inside nexus where the instrument name is written
Definition at line 203 of file LoadILLSANS.cpp.
References Mantid::NeXus::NXClass::containsGroup(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::DataHandling::LoadHelper::getStringFromNexusPath(), m_instrumentName, and m_supportedInstruments.
Referenced by exec().
setNumberOfMonitors()
void Mantid::DataHandling::LoadILLSANS::setNumberOfMonitors () private
LoadILLSANS::setNumberOfMonitors Set the number of monitor attribute depending on the instrument loaded.
Definition at line 248 of file LoadILLSANS.cpp.
References m_instrumentName, and m_numberOfMonitors.
Referenced by exec(), and initWorkSpace().
summary()
const std::string Mantid::DataHandling::LoadILLSANS::summary () const override virtual
Algorithm's summary.
See also
Algorithm::summery
Implements Mantid::API::Algorithm.
Definition at line 58 of file LoadILLSANS.cpp.
version()
int Mantid::DataHandling::LoadILLSANS::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 52 of file LoadILLSANS.cpp.
Member Data Documentation
m_defaultBinning
std::vector<double> Mantid::DataHandling::LoadILLSANS::m_defaultBinning private
the default x-axis binning
Definition at line 89 of file LoadILLSANS.h.
Referenced by initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), initWorkSpaceD33(), loadDataFromMonitors(), and loadMetaData().
m_instrumentName
std::string Mantid::DataHandling::LoadILLSANS::m_instrumentName private
Name of the instrument.
Definition at line 86 of file LoadILLSANS.h.
Referenced by exec(), initWorkSpace(), initWorkSpaceD33(), loadDataFromD16ScanMonitors(), loadDataFromTubes(), loadMetaData(), runLoadInstrument(), setInstrumentName(), and setNumberOfMonitors().
m_isD16Omega
bool Mantid::DataHandling::LoadILLSANS::m_isD16Omega private
Data comes from a D16 omega scan flag.
Definition at line 93 of file LoadILLSANS.h.
Referenced by createEmptyWorkspace(), exec(), getDataDimensions(), initWorkSpace(), and loadDataFromTubes().
m_isTOF
bool Mantid::DataHandling::LoadILLSANS::m_isTOF private
TOF or monochromatic flag.
Definition at line 91 of file LoadILLSANS.h.
Referenced by exec(), initWorkSpaceD33(), and loadDataFromMonitors().
m_localWorkspace
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLSANS::m_localWorkspace private
to-be output workspace
Definition at line 88 of file LoadILLSANS.h.
Referenced by adjustTOF(), createEmptyWorkspace(), exec(), getComponentPosition(), initWorkSpaceD11B(), initWorkSpaceD22B(), loadDataFromD16ScanMonitors(), loadDataFromMonitors(), loadDataFromTubes(), loadMetaData(), moveDetectorDistance(), moveDetectorHorizontal(), moveDetectorsD33(), moveDetectorVertical(), moveSource(), placeD16(), rotateInstrument(), runLoadInstrument(), and setFinalProperties().
m_numberOfMonitors
size_t Mantid::DataHandling::LoadILLSANS::m_numberOfMonitors private
Number of monitors in this instrument.
Definition at line 94 of file LoadILLSANS.h.
Referenced by adjustTOF(), initWorkSpace(), initWorkSpaceD11B(), initWorkSpaceD22B(), initWorkSpaceD33(), and setNumberOfMonitors().
m_resMode
std::string Mantid::DataHandling::LoadILLSANS::m_resMode private
Resolution mode for D11 and D22.
Definition at line 90 of file LoadILLSANS.h.
Referenced by initWorkSpace(), and runLoadInstrument().
m_sourcePos
double Mantid::DataHandling::LoadILLSANS::m_sourcePos private
Source Z (for D33 TOF)
Definition at line 92 of file LoadILLSANS.h.
Referenced by adjustTOF(), initWorkSpaceD33(), and moveSource().
m_supportedInstruments
std::vector<std::string> Mantid::DataHandling::LoadILLSANS::m_supportedInstruments private
List of supported instruments.
Definition at line 87 of file LoadILLSANS.h.
Referenced by setInstrumentName().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
Framework/DataHandling/src/LoadILLSANS.cpp