Mantid: Mantid::Geometry::SymmetryElementWithAxisGenerator Class Reference
Mantid::Geometry::SymmetryElementWithAxisGenerator Class Reference abstract
SymmetryElementWithAxisGenerator does not create any elements directly, it serves as a base for SymmetryElementRotationGenerator and SymmetryAxisMirrorGenerator, which have in common that the axis of the symmetry element as well as any potential translations must be determined.
#include <SymmetryElementFactory.h>
Protected Member Functions
V3R determineAxis (const Kernel::IntMatrix &matrix) const
Returns the symmetry axis for the given matrix.
virtual std::string determineSymbol (const SymmetryOperation &operation) const =0
V3R determineTranslation (const SymmetryOperation &operation) const
Returns the reduced vector of the operation.
Additional Inherited Members
Public Member Functions inherited from Mantid::Geometry::AbstractSymmetryElementGenerator
virtual bool canProcess (const SymmetryOperation &operation) const =0
Should return true if the generator can produce a valid SymmetryElement from the provided SymmetryOperation.
virtual SymmetryElement_sptr generateElement (const SymmetryOperation &operation) const =0
Must generate a valid SymmetryElement from the given operation.
virtual ~AbstractSymmetryElementGenerator ()=default
Detailed Description
SymmetryElementWithAxisGenerator does not create any elements directly, it serves as a base for SymmetryElementRotationGenerator and SymmetryAxisMirrorGenerator, which have in common that the axis of the symmetry element as well as any potential translations must be determined.
These are implemented according to the algorithms found in the International Tables for Crystallography A, section 11.2.
Subclasses must implement the method to determine the Hermann-Mauguin symbol, as that algorithm is different for example for rotation-axes and mirror-planes.
Definition at line 100 of file SymmetryElementFactory.h.
Member Function Documentation
determineAxis()
V3R Mantid::Geometry::SymmetryElementWithAxisGenerator::determineAxis (const Kernel::IntMatrix & matrix) const protected
Returns the symmetry axis for the given matrix.
According to ITA, 11.2 the axis of a symmetry operation can be determined by solving the Eigenvalue problem \(Wu = u\) for rotations or \(Wu = -u\) for rotoinversions. This is implemented using the general real non-symmetric eigen-problem solver provided by the GSL.
Parameters
matrix :: Matrix of a SymmetryOperation
Returns
Axis of symmetry element.
Definition at line 113 of file SymmetryElementFactory.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), fabs, Mantid::Geometry::getGSLIdentityMatrix(), Mantid::Geometry::getGSLMatrix(), Mantid::Kernel::Matrix< T >::numCols(), Mantid::Kernel::Matrix< T >::numRows(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by Mantid::Geometry::SymmetryElementRotationGenerator::generateElement(), and Mantid::Geometry::SymmetryElementMirrorGenerator::generateElement().
determineSymbol()
virtual std::string Mantid::Geometry::SymmetryElementWithAxisGenerator::determineSymbol (const SymmetryOperation & operation) const protected pure virtual
Implemented in Mantid::Geometry::SymmetryElementRotationGenerator, and Mantid::Geometry::SymmetryElementMirrorGenerator.
determineTranslation()
V3R Mantid::Geometry::SymmetryElementWithAxisGenerator::determineTranslation (const SymmetryOperation & operation) const protected
Returns the reduced vector of the operation.
Definition at line 57 of file SymmetryElementFactory.cpp.
References Mantid::Geometry::SymmetryOperation::reducedVector().
Referenced by Mantid::Geometry::SymmetryElementRotationGenerator::determineSymbol(), Mantid::Geometry::SymmetryElementMirrorGenerator::determineSymbol(), Mantid::Geometry::SymmetryElementRotationGenerator::generateElement(), and Mantid::Geometry::SymmetryElementMirrorGenerator::generateElement().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/SymmetryElementFactory.h
Framework/Geometry/src/Crystal/SymmetryElementFactory.cpp