Mantid: Mantid::Kernel::ProxyInfo Class Reference
Mantid::Kernel::ProxyInfo Class Reference
ProxyInfo : Container for carrying around network proxy information.
#include <ProxyInfo.h>
Public Member Functions
bool emptyProxy () const
std::string host () const
Host url.
bool isHttpProxy () const
Is this a http proxy.
int port () const
Port Number.
ProxyInfo ()
Constructor.
ProxyInfo (const std::string &host, const int port, const bool isHttpProxy)
Proxy information constructor.
virtual ~ProxyInfo ()=default
Private Attributes
std::string m_host
bool m_isEmptyProxy
bool m_isHttpProxy
int m_port
Detailed Description
ProxyInfo : Container for carrying around network proxy information.
Definition at line 17 of file ProxyInfo.h.
Constructor & Destructor Documentation
~ProxyInfo()
virtual Mantid::Kernel::ProxyInfo::~ProxyInfo () virtual default
ProxyInfo() [1/2]
Mantid::Kernel::ProxyInfo::ProxyInfo ()
Constructor.
Definition at line 15 of file ProxyInfo.cpp.
ProxyInfo() [2/2]
Mantid::Kernel::ProxyInfo::ProxyInfo (const std::string & host, const int port, const bool isHttpProxy)
Proxy information constructor.
Parameters
host : host url
port : port number
isHttpProxy : is this a http proxy
Definition at line 23 of file ProxyInfo.cpp.
References host(), m_isEmptyProxy, and port().
Member Function Documentation
emptyProxy()
bool Mantid::Kernel::ProxyInfo::emptyProxy () const
Returns
True if an empty proxy.
Definition at line 62 of file ProxyInfo.cpp.
References m_isEmptyProxy.
host()
std::string Mantid::Kernel::ProxyInfo::host () const
Host url.
Returns
host url or throws if an unset proxy.
Definition at line 34 of file ProxyInfo.cpp.
References m_host, and m_isEmptyProxy.
Referenced by ProxyInfo().
isHttpProxy()
bool Mantid::Kernel::ProxyInfo::isHttpProxy () const
Is this a http proxy.
Returns
True if a http proxy or throws if an unset proxy.
Definition at line 56 of file ProxyInfo.cpp.
References m_isHttpProxy.
port()
int Mantid::Kernel::ProxyInfo::port () const
Port Number.
Returns
Port number or throws if an unset proxy.
Definition at line 45 of file ProxyInfo.cpp.
References m_isEmptyProxy, and m_port.
Referenced by ProxyInfo().
Member Data Documentation
m_host
std::string Mantid::Kernel::ProxyInfo::m_host private
Definition at line 19 of file ProxyInfo.h.
Referenced by host().
m_isEmptyProxy
bool Mantid::Kernel::ProxyInfo::m_isEmptyProxy private
Definition at line 22 of file ProxyInfo.h.
Referenced by emptyProxy(), host(), port(), and ProxyInfo().
m_isHttpProxy
bool Mantid::Kernel::ProxyInfo::m_isHttpProxy private
Definition at line 21 of file ProxyInfo.h.
Referenced by isHttpProxy().
m_port
int Mantid::Kernel::ProxyInfo::m_port private
Definition at line 20 of file ProxyInfo.h.
Referenced by port().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/ProxyInfo.h
Framework/Kernel/src/ProxyInfo.cpp