Mantid: Mantid::Kernel::MantidVersion Class Reference
Mantid::Kernel::MantidVersion Class Reference
Class containing static methods to return the Mantid version number and date.
#include <MantidVersion.h>
Classes
struct VersionInfo
Static Public Member Functions
static std::string doi ()
The DOI for this release of Mantid.
static const std::string & paperCitation ()
The citation for the Mantid paper.
static std::string releaseDate ()
The date of the last commit.
static Types::Core::DateAndTime releaseDateAndTime ()
The DateAndTime of the last commit.
static std::string releaseNotes ()
The url to the most applicable release notes.
static const std::string & revision ()
The abbreviated SHA-1 of the last commit.
static const std::string & revisionFull ()
The full SHA-1 of the last commit.
static const std::string & version ()
The full version number.
static std::string versionForReleaseNotes (const VersionInfo &)
The version of mantid for the release notes url.
static const VersionInfo versionInfo ()
A data structure containing the full version info.
static const std::string & versionShort ()
The version number of the last full version.
Private Member Functions
MantidVersion ()
Private, unimplemented constructor. Not a class that can be instantiated.
Detailed Description
Class containing static methods to return the Mantid version number and date.
Definition at line 21 of file MantidVersion.h.
Constructor & Destructor Documentation
MantidVersion()
Mantid::Kernel::MantidVersion::MantidVersion () private
Private, unimplemented constructor. Not a class that can be instantiated.
Member Function Documentation
doi()
std::string Mantid::Kernel::MantidVersion::doi () static
The DOI for this release of Mantid.
Definition at line 170 of file MantidVersion.cpp.
References doi().
Referenced by doi(), export_MantidVersion(), and Mantid::welcomeMessage().
paperCitation()
const std::string & Mantid::Kernel::MantidVersion::paperCitation () static
The citation for the Mantid paper.
Definition at line 194 of file MantidVersion.cpp.
Referenced by export_MantidVersion(), and Mantid::welcomeMessage().
releaseDate()
std::string Mantid::Kernel::MantidVersion::releaseDate () static
The date of the last commit.
Definition at line 164 of file MantidVersion.cpp.
References releaseDateAndTime().
Referenced by Mantid::DataHandling::CheckMantidVersion::exec(), and export_MantidVersion().
releaseDateAndTime()
Types::Core::DateAndTime Mantid::Kernel::MantidVersion::releaseDateAndTime () static
The DateAndTime of the last commit.
Definition at line 160 of file MantidVersion.cpp.
Referenced by export_MantidVersion(), Mantid::DataHandling::CheckMantidVersion::getVersionsFromGitHub(), and releaseDate().
releaseNotes()
std::string Mantid::Kernel::MantidVersion::releaseNotes () static
The url to the most applicable release notes.
Definition at line 145 of file MantidVersion.cpp.
References versionForReleaseNotes(), and versionInfo().
Referenced by export_MantidVersion(), and Mantid::API::NotebookWriter::headerComment().
revision()
const std::string & Mantid::Kernel::MantidVersion::revision () static
The abbreviated SHA-1 of the last commit.
Definition at line 156 of file MantidVersion.cpp.
Referenced by Mantid::Kernel::ConfigServiceImpl::ConfigServiceImpl(), and export_MantidVersion().
revisionFull()
const std::string & Mantid::Kernel::MantidVersion::revisionFull () static
The full SHA-1 of the last commit.
Definition at line 158 of file MantidVersion.cpp.
Referenced by Mantid::Algorithms::GeneratePythonScript::exec(), export_MantidVersion(), Mantid::Kernel::ErrorReporter::generateErrorMessage(), and Mantid::Kernel::UsageServiceImpl::generateStartupMessage().
version()
const std::string & Mantid::Kernel::MantidVersion::version () static
The full version number.
See buildconfig/CMake/VersionNumber.cmake for more information on the meaning of the version number elements.
Definition at line 117 of file MantidVersion.cpp.
Referenced by Mantid::DataHandling::NXcanSAS::addProcess(), Mantid::Kernel::ConfigServiceImpl::ConfigServiceImpl(), Mantid::Kernel::InternetHelper::createRequest(), Mantid::DataHandling::SaveCanSAS1D::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::DataHandling::SaveNXSPE::exec(), export_MantidVersion(), Mantid::Kernel::EnvironmentHistory::frameworkVersion(), Mantid::Kernel::ErrorReporter::generateErrorMessage(), Mantid::Kernel::UsageServiceImpl::generateStartupMessage(), Mantid::DataHandling::CheckMantidVersion::getCurrentVersion(), Mantid::API::NotebookWriter::headerComment(), Mantid::DataHandling::SaveNXTomo::setupFile(), versionForReleaseNotes(), Mantid::welcomeMessage(), and Mantid::DataHandling::SavePDFGui::writeMetaData().
versionForReleaseNotes()
std::string Mantid::Kernel::MantidVersion::versionForReleaseNotes (const VersionInfo & version) static
The version of mantid for the release notes url.
Definition at line 125 of file MantidVersion.cpp.
References version().
Referenced by releaseNotes().
versionInfo()
const MantidVersion::VersionInfo Mantid::Kernel::MantidVersion::versionInfo () static
A data structure containing the full version info.
Definition at line 121 of file MantidVersion.cpp.
Referenced by export_MantidVersion(), and releaseNotes().
versionShort()
const std::string & Mantid::Kernel::MantidVersion::versionShort () static
The version number of the last full version.
Definition at line 119 of file MantidVersion.cpp.
Referenced by Mantid::Kernel::UsageServiceImpl::generateFeatureHeader().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MantidVersion.h
Framework/Kernel/src/MantidVersion.cpp