Mantid: ICat4::ns1__facility Class Reference
ICat4::ns1__facility Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__facility ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< ns1__application * > applications
std::vector< ns1__datafileFormat * > datafileFormats
std::vector< ns1__datasetType * > datasetTypes
int * daysUntilRelease
std::string * description
std::vector< ns1__facilityCycle * > facilityCycles
std::string * fullName
std::vector< ns1__instrument * > instruments
std::vector< ns1__investigation * > investigations
std::vector< ns1__investigationType * > investigationTypes
std::string * name
std::vector< ns1__parameterType * > parameterTypes
std::vector< class ns1__sampleType * > sampleTypes
std::string * url
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1607 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__facility()
ICat4::ns1__facility::ns1__facility () inline
Definition at line 1631 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__facility::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15919 of file ICat4C.cpp.
References applications, datafileFormats, datasetTypes, daysUntilRelease, description, facilityCycles, fullName, instruments, investigations, investigationTypes, name, parameterTypes, sampleTypes, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__application(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datafileFormat(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datasetType(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__facilityCycle(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__instrument(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigation(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationType(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__parameterType(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__sampleType(), and url.
Referenced by ICat4::soap_in_ns1__facility(), ICat4::soap_new_req_ns1__facility(), and ICat4::soap_new_set_ns1__facility().
soap_get()
void * ICat4::ns1__facility::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16172 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__facility().
soap_in()
void * ICat4::ns1__facility::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16020 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__facility().
Referenced by ICat4::soap_in_ns1__facility().
soap_out()
int ICat4::ns1__facility::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15961 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__facility().
Referenced by soap_put().
soap_put()
int ICat4::ns1__facility::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16165 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__facility.
soap_serialize()
void ICat4::ns1__facility::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15939 of file ICat4C.cpp.
References applications, datafileFormats, datasetTypes, daysUntilRelease, description, facilityCycles, fullName, instruments, investigations, investigationTypes, name, parameterTypes, sampleTypes, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerToint(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__application(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datafileFormat(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datasetType(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__facilityCycle(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__instrument(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigation(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationType(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__parameterType(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__sampleType(), and url.
Referenced by ICat4::soap_serialize_PointerTons1__datasetType().
soap_type()
int ICat4::ns1__facility::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1624 of file ICat4Stub.h.
Member Data Documentation
applications
std::vector<ns1__application *> ICat4::ns1__facility::applications
Definition at line 1609 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
datafileFormats
std::vector<ns1__datafileFormat *> ICat4::ns1__facility::datafileFormats
Definition at line 1610 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
datasetTypes
std::vector<ns1__datasetType *> ICat4::ns1__facility::datasetTypes
Definition at line 1611 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
daysUntilRelease
int* ICat4::ns1__facility::daysUntilRelease
Definition at line 1612 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
description
std::string* ICat4::ns1__facility::description
Definition at line 1613 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
facilityCycles
std::vector<ns1__facilityCycle *> ICat4::ns1__facility::facilityCycles
Definition at line 1614 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
fullName
std::string* ICat4::ns1__facility::fullName
Definition at line 1615 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
instruments
std::vector<ns1__instrument *> ICat4::ns1__facility::instruments
Definition at line 1616 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigations
std::vector<ns1__investigation *> ICat4::ns1__facility::investigations
Definition at line 1618 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigationTypes
std::vector<ns1__investigationType *> ICat4::ns1__facility::investigationTypes
Definition at line 1617 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__facility::name
Definition at line 1619 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
parameterTypes
std::vector<ns1__parameterType *> ICat4::ns1__facility::parameterTypes
Definition at line 1620 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
sampleTypes
std::vector<class ns1__sampleType *> ICat4::ns1__facility::sampleTypes
Definition at line 1621 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
url
std::string* ICat4::ns1__facility::url
Definition at line 1622 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp