Mantid: Mantid::Kernel::uniform_int_distribution< _IntType > Class Template Reference
Mantid::Kernel::uniform_int_distribution< _IntType > Class Template Reference
#include <uniform_int_distribution.h>
Classes
class param_type
Public Types
using result_type = _IntType
Public Member Functions
result_type a () const
result_type b () const
result_type max () const
result_type min () const
template<class _URNG >
result_type operator() (_URNG &__g)
template<class _URNG >
result_type operator() (_URNG &__g, const param_type &__p)
param_type param () const
void param (const param_type &__p)
void reset ()
uniform_int_distribution (const param_type &__p)
uniform_int_distribution (result_type __a=0, result_type __b=std::numeric_limits< result_type >::max())
Private Attributes
param_type __p_
Friends
bool operator!= (const uniform_int_distribution &__x, const uniform_int_distribution &__y)
bool operator== (const uniform_int_distribution &__x, const uniform_int_distribution &__y)
Detailed Description
template<class _IntType = int>
class Mantid::Kernel::uniform_int_distribution< _IntType >
Definition at line 211 of file uniform_int_distribution.h.
Member Typedef Documentation
result_type
template<class _IntType = int> using Mantid::Kernel::uniform_int_distribution< _IntType >::result_type = _IntType
Definition at line 214 of file uniform_int_distribution.h.
Constructor & Destructor Documentation
uniform_int_distribution() [1/2]
template<class _IntType = int> Mantid::Kernel::uniform_int_distribution< _IntType >::uniform_int_distribution (result_type __a = 0, result_type __b = std::numeric_limits<result_type>::max()) inline explicit
Definition at line 240 of file uniform_int_distribution.h.
uniform_int_distribution() [2/2]
template<class _IntType = int> Mantid::Kernel::uniform_int_distribution< _IntType >::uniform_int_distribution (const param_type & __p) inline explicit
Definition at line 242 of file uniform_int_distribution.h.
Member Function Documentation
a()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::a () const inline
Definition at line 250 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::__p_, and Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::a().
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::min().
b()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::b () const inline
Definition at line 251 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::__p_, and Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::b().
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::max().
max()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::max () const inline
Definition at line 257 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::b().
min()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::min () const inline
Definition at line 256 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::a().
operator()() [1/2]
template<class _IntType = int> template<class _URNG > result_type Mantid::Kernel::uniform_int_distribution< _IntType >::operator() (_URNG & __g) inline
Definition at line 246 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::__p_.
operator()() [2/2]
template<class _IntType > template<class _URNG > uniform_int_distribution< _IntType >::result_type Mantid::Kernel::uniform_int_distribution< _IntType >::operator() (_URNG & __g, const param_type & __p)
Definition at line 270 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::a(), and Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::b().
param() [1/2]
template<class _IntType = int> param_type Mantid::Kernel::uniform_int_distribution< _IntType >::param () const inline
Definition at line 253 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::__p_.
param() [2/2]
template<class _IntType = int> void Mantid::Kernel::uniform_int_distribution< _IntType >::param (const param_type & __p) inline
Definition at line 254 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::__p_.
reset()
template<class _IntType = int> void Mantid::Kernel::uniform_int_distribution< _IntType >::reset () inline
Definition at line 243 of file uniform_int_distribution.h.
Friends And Related Symbol Documentation
operator!=
template<class _IntType = int> bool operator!= (const uniform_int_distribution< _IntType > & __x, const uniform_int_distribution< _IntType > & __y) friend
Definition at line 262 of file uniform_int_distribution.h.
operator==
template<class _IntType = int> bool operator== (const uniform_int_distribution< _IntType > & __x, const uniform_int_distribution< _IntType > & __y) friend
Definition at line 259 of file uniform_int_distribution.h.
Member Data Documentation
__p_
template<class _IntType = int> param_type Mantid::Kernel::uniform_int_distribution< _IntType >::__p_ private
Definition at line 236 of file uniform_int_distribution.h.
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::a(), Mantid::Kernel::uniform_int_distribution< _IntType >::b(), Mantid::Kernel::uniform_int_distribution< _IntType >::operator()(), Mantid::Kernel::uniform_int_distribution< _IntType >::param(), and Mantid::Kernel::uniform_int_distribution< _IntType >::param().
The documentation for this class was generated from the following file:
Framework/Kernel/inc/MantidKernel/uniform_int_distribution.h