Mantid: Mantid::CurveFitting::SpecialFunctionSupport Namespace Reference
Mantid::CurveFitting::SpecialFunctionSupport Namespace Reference
Functions
std::complex< double > MANTID_CURVEFITTING_DLL exponentialIntegral (const std::complex< double > &z)
Compute exp(z)*E1(z) where z is complex and E1(z) is the Exponential Integral.
Function Documentation
exponentialIntegral()
complex< double > Mantid::CurveFitting::SpecialFunctionSupport::exponentialIntegral (const complex< double > & z)
Compute exp(z)*E1(z) where z is complex and E1(z) is the Exponential Integral.
Implement Exponential Integral function, E1(z), based on formulaes in Abramowitz and Stegun (A&S) In fact this implementation returns exp(z)*E1(z) where z is a complex number.
Parameters
z :: input
Returns
exp(z)*E1(z)
Definition at line 22 of file SpecialFunctionHelper.cpp.
References Mantid::Geometry::z.
Referenced by Mantid::CurveFitting::Functions::Bk2BkExpConvPV::calOmega(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::constFunction(), and Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionLocal().