Mantid: ICat4::ns1__isAccessAllowedResponse Class Reference
ICat4::ns1__isAccessAllowedResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__isAccessAllowedResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
bool return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1305 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__isAccessAllowedResponse()
ICat4::ns1__isAccessAllowedResponse::ns1__isAccessAllowedResponse () inline
Definition at line 1321 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__isAccessAllowedResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6560 of file ICat4C.cpp.
References ICat4::soap_default_bool().
Referenced by ICat4::ICATPortBindingProxy::isAccessAllowed(), ICat4::soap_in_ns1__isAccessAllowedResponse(), ICat4::soap_new_req_ns1__isAccessAllowedResponse(), and ICat4::soap_new_set_ns1__isAccessAllowedResponse().
soap_get()
void * ICat4::ns1__isAccessAllowedResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6657 of file ICat4C.cpp.
References ICat4::soap_get_ns1__isAccessAllowedResponse().
Referenced by ICat4::ICATPortBindingProxy::isAccessAllowed().
soap_in()
void * ICat4::ns1__isAccessAllowedResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6589 of file ICat4C.cpp.
References ICat4::soap_in_ns1__isAccessAllowedResponse().
Referenced by ICat4::soap_in_ns1__isAccessAllowedResponse().
soap_out()
int ICat4::ns1__isAccessAllowedResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6573 of file ICat4C.cpp.
References ICat4::soap_out_ns1__isAccessAllowedResponse().
soap_put()
int ICat4::ns1__isAccessAllowedResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6650 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__isAccessAllowedResponse.
soap_serialize()
void ICat4::ns1__isAccessAllowedResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6566 of file ICat4C.cpp.
soap_type()
int ICat4::ns1__isAccessAllowedResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1314 of file ICat4Stub.h.
Member Data Documentation
return_
bool ICat4::ns1__isAccessAllowedResponse::return_
Definition at line 1307 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::isAccessAllowed().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp