Mantid: MantidQt::MantidWidgets::ImageInfoPresenter Class Reference
MantidQt::MantidWidgets::ImageInfoPresenter Class Reference
A table widget containing information about the pixel the mouse is over in an image.
#include <ImageInfoPresenter.h>
Public Member Functions
void cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues)
void fillTableCells (const ImageInfoModel::ImageInfo &info)
Fill the view table cells using the model.
ImageInfoPresenter (IImageInfoWidget *view)
Constructor.
const ImageInfoModel & model ()
void setShowSignal (const bool showSignal)
void setWorkspace (const Mantid::API::Workspace_sptr &ws)
Set a new workspace for the view to display.
Private Attributes
std::unique_ptr< ImageInfoModel > m_model
bool m_showSignal
IImageInfoWidget * m_view
Detailed Description
A table widget containing information about the pixel the mouse is over in an image.
Definition at line 21 of file ImageInfoPresenter.h.
Constructor & Destructor Documentation
ImageInfoPresenter()
MantidQt::MantidWidgets::ImageInfoPresenter::ImageInfoPresenter (IImageInfoWidget * view)
Constructor.
Parameters
view A pointer to a view object that displays the information
Definition at line 22 of file ImageInfoPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IImageInfoWidget::setRowCount().
Member Function Documentation
cursorAt()
void MantidQt::MantidWidgets::ImageInfoPresenter::cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues)
Parameters
x X position on an image of the workspace
y Y position on an image of the workspace
signal The signal value at the given position
extraValues A map of extra column names and values to display
Definition at line 32 of file ImageInfoPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IImageInfoWidget::showInfo(), Mantid::Geometry::x, and Mantid::Geometry::y.
fillTableCells()
void MantidQt::MantidWidgets::ImageInfoPresenter::fillTableCells (const ImageInfoModel::ImageInfo & info)
Fill the view table cells using the model.
Parameters
info A reference to a collection of header/value pairs
Definition at line 54 of file ImageInfoPresenter.cpp.
References MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::empty(), MantidQt::MantidWidgets::IImageInfoWidget::hideColumn(), m_showSignal, m_view, name, MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::name(), MantidQt::MantidWidgets::IImageInfoWidget::setColumnCount(), MantidQt::MantidWidgets::IImageInfoWidget::setItem(), MantidQt::MantidWidgets::IImageInfoWidget::showColumn(), MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::size(), value, and MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::value().
model()
const ImageInfoModel & MantidQt::MantidWidgets::ImageInfoPresenter::model () inline
Definition at line 26 of file ImageInfoPresenter.h.
setShowSignal()
void MantidQt::MantidWidgets::ImageInfoPresenter::setShowSignal (const bool showSignal) inline
Definition at line 31 of file ImageInfoPresenter.h.
setWorkspace()
void MantidQt::MantidWidgets::ImageInfoPresenter::setWorkspace (const Mantid::API::Workspace_sptr & workspace)
Set a new workspace for the view to display.
Parameters
workspace A pointer to a new workspace
Definition at line 42 of file ImageInfoPresenter.cpp.
References m_model, and workspace.
Member Data Documentation
m_model
std::unique_ptr<ImageInfoModel> MantidQt::MantidWidgets::ImageInfoPresenter::m_model private
Definition at line 34 of file ImageInfoPresenter.h.
Referenced by cursorAt(), and setWorkspace().
m_showSignal
bool MantidQt::MantidWidgets::ImageInfoPresenter::m_showSignal private
Definition at line 36 of file ImageInfoPresenter.h.
Referenced by fillTableCells().
m_view
IImageInfoWidget* MantidQt::MantidWidgets::ImageInfoPresenter::m_view private
Definition at line 35 of file ImageInfoPresenter.h.
Referenced by cursorAt(), fillTableCells(), and ImageInfoPresenter().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoPresenter.h
qt/widgets/common/src/ImageInfoPresenter.cpp