Mantid: Mantid::Geometry::CenteringGroupCreatorImpl Class Reference
Mantid::Geometry::CenteringGroupCreatorImpl Class Reference
Helper class to keep this out of the interface of CenteringGroup.
#include <CenteringGroup.h>
Public Member Functions
CenteringGroup::CenteringType getCenteringType (const std::string &centeringSymbol) const
Returns centering type enum value if centering symbol exists, throws std::invalid_argument exception otherwise.
std::vector< SymmetryOperation > getSymmetryOperations (CenteringGroup::CenteringType centeringType) const
Returns a vector of symmetry operations for the given centering type or throws std::invalid_argument if an invalid value is supplied.
Protected Member Functions
CenteringGroupCreatorImpl ()
std::vector< SymmetryOperation > getACentered () const
Returns symmetry operations for A-centering.
std::vector< SymmetryOperation > getBCentered () const
Returns symmetry operations for B-centering.
std::vector< SymmetryOperation > getBodyCentered () const
Returns symmetry operations for I-centering.
std::vector< SymmetryOperation > getCCentered () const
Returns symmetry operations for C-centering.
std::vector< SymmetryOperation > getFCentered () const
Returns symmetry operations for F-centering.
std::vector< SymmetryOperation > getPrimitive () const
Returns symmetry operations for P-centering.
std::vector< SymmetryOperation > getRobvCentered () const
Returns symmetry operations for R-centering, obverse setting.
std::vector< SymmetryOperation > getRrevCentered () const
Returns symmetry operations for R-centering, reverse setting.
Protected Attributes
std::map< std::string, CenteringGroup::CenteringType > m_centeringSymbolMap
Friends
struct Mantid::Kernel::CreateUsingNew< CenteringGroupCreatorImpl >
Detailed Description
Helper class to keep this out of the interface of CenteringGroup.
Definition at line 57 of file CenteringGroup.h.
Constructor & Destructor Documentation
CenteringGroupCreatorImpl()
Mantid::Geometry::CenteringGroupCreatorImpl::CenteringGroupCreatorImpl () protected
Definition at line 106 of file CenteringGroup.cpp.
References Mantid::Geometry::CenteringGroup::A, Mantid::Geometry::CenteringGroup::B, Mantid::Geometry::CenteringGroup::C, Mantid::Geometry::CenteringGroup::F, Mantid::Geometry::CenteringGroup::I, Mantid::Geometry::CenteringGroup::P, Mantid::Geometry::CenteringGroup::Robv, and Mantid::Geometry::CenteringGroup::Rrev.
Member Function Documentation
getACentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getACentered () const protected
Returns symmetry operations for A-centering.
Definition at line 77 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getBCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getBCentered () const protected
Returns symmetry operations for B-centering.
Definition at line 82 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getBodyCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getBodyCentered () const protected
Returns symmetry operations for I-centering.
Definition at line 72 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getCCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getCCentered () const protected
Returns symmetry operations for C-centering.
Definition at line 87 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getCenteringType()
CenteringGroup::CenteringType Mantid::Geometry::CenteringGroupCreatorImpl::getCenteringType (const std::string & centeringSymbol) const
Returns centering type enum value if centering symbol exists, throws std::invalid_argument exception otherwise.
Definition at line 30 of file CenteringGroup.cpp.
References m_centeringSymbolMap.
getFCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getFCentered () const protected
Returns symmetry operations for F-centering.
Definition at line 92 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getPrimitive()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getPrimitive () const protected
Returns symmetry operations for P-centering.
Definition at line 67 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getRobvCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getRobvCentered () const protected
Returns symmetry operations for R-centering, obverse setting.
Definition at line 97 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getRrevCentered()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getRrevCentered () const protected
Returns symmetry operations for R-centering, reverse setting.
Definition at line 102 of file CenteringGroup.cpp.
Referenced by getSymmetryOperations().
getSymmetryOperations()
std::vector< SymmetryOperation > Mantid::Geometry::CenteringGroupCreatorImpl::getSymmetryOperations (CenteringGroup::CenteringType centeringType) const
Returns a vector of symmetry operations for the given centering type or throws std::invalid_argument if an invalid value is supplied.
Definition at line 43 of file CenteringGroup.cpp.
References Mantid::Geometry::CenteringGroup::A, Mantid::Geometry::CenteringGroup::B, Mantid::Geometry::CenteringGroup::C, Mantid::Geometry::CenteringGroup::F, getACentered(), getBCentered(), getBodyCentered(), getCCentered(), getFCentered(), getPrimitive(), getRobvCentered(), getRrevCentered(), Mantid::Geometry::CenteringGroup::I, Mantid::Geometry::CenteringGroup::P, Mantid::Geometry::CenteringGroup::Robv, and Mantid::Geometry::CenteringGroup::Rrev.
Friends And Related Symbol Documentation
Mantid::Kernel::CreateUsingNew< CenteringGroupCreatorImpl >
friend struct Mantid::Kernel::CreateUsingNew< CenteringGroupCreatorImpl > friend
Definition at line 74 of file CenteringGroup.h.
Member Data Documentation
m_centeringSymbolMap
std::map<std::string, CenteringGroup::CenteringType> Mantid::Geometry::CenteringGroupCreatorImpl::m_centeringSymbolMap protected
Definition at line 74 of file CenteringGroup.h.
Referenced by getCenteringType().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/CenteringGroup.h
Framework/Geometry/src/Crystal/CenteringGroup.cpp