Mantid: Mantid::MDAlgorithms::AccumulateMD Class Reference
Mantid::MDAlgorithms::AccumulateMD Class Reference
AccumulateMD : Algorithm for appending new data to a MDHistoWorkspace.
#include <AccumulateMD.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
Mantid::API::IMDEventWorkspace_sptr createMDWorkspace (const std::vector< std::string > &data_sources, const std::vector< double > &psi, const std::vector< double > &gl, const std::vector< double > &gs, const std::vector< double > &efix, const std::string &filename, const bool filebackend)
Use the CreateMD algorithm to create an MD workspace.
void exec () override
void init () override
std::map< std::string, std::string > validateInputs () override
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
AccumulateMD : Algorithm for appending new data to a MDHistoWorkspace.
Definition at line 63 of file AccumulateMD.h.
Member Function Documentation
category()
const std::string Mantid::MDAlgorithms::AccumulateMD::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 198 of file AccumulateMD.cpp.
createMDWorkspace()
IMDEventWorkspace_sptr Mantid::MDAlgorithms::AccumulateMD::createMDWorkspace (const std::vector< std::string > & data_sources, const std::vector< double > & psi, const std::vector< double > & gl, const std::vector< double > & gs, const std::vector< double > & efix, const std::string & filename, const bool filebackend) private
Use the CreateMD algorithm to create an MD workspace.
Definition at line 378 of file AccumulateMD.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue().
Referenced by exec().
exec()
void Mantid::MDAlgorithms::AccumulateMD::exec () override private
Definition at line 273 of file AccumulateMD.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), createMDWorkspace(), Mantid::MDAlgorithms::filterToExistingSources(), Mantid::MDAlgorithms::filterToNew(), Mantid::API::g_log, Mantid::MDAlgorithms::getHistoricalDataSources(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), name(), Mantid::Kernel::Logger::notice(), Mantid::MDAlgorithms::padParameterVector(), and Mantid::Kernel::Logger::warning().
init()
void Mantid::MDAlgorithms::AccumulateMD::init () override private
Definition at line 206 of file AccumulateMD.cpp.
References Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::API::FileProperty::OptionalSave, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::MDAlgorithms::AccumulateMD::name () const override
Algorithms name for identification.
See also
Algorithm::name
Definition at line 192 of file AccumulateMD.cpp.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::AccumulateMD::seeAlso () const inline override
Definition at line 67 of file AccumulateMD.h.
summary()
const std::string Mantid::MDAlgorithms::AccumulateMD::summary () const override
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Definition at line 201 of file AccumulateMD.cpp.
validateInputs()
std::map< std::string, std::string > Mantid::MDAlgorithms::AccumulateMD::validateInputs () override private
Definition at line 409 of file AccumulateMD.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty().
version()
int Mantid::MDAlgorithms::AccumulateMD::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 195 of file AccumulateMD.cpp.
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/AccumulateMD.h
Framework/MDAlgorithms/src/AccumulateMD.cpp