Mantid: Mantid::DataObjects::FindBin Struct Reference
Mantid::DataObjects::FindBin Struct Reference
Public Member Functions
FindBin (double step, double xmin)
std::optional< size_t > operator() (const Mantid::MantidVec &X, const double tof, const bool findExact)
Public Attributes
double divisor
std::optional< size_t >(* findBin)(const Mantid::MantidVec &, const double, const double, const double, const bool)
double offset
Detailed Description
Definition at line 142 of file EventList.cpp.
Constructor & Destructor Documentation
FindBin()
Mantid::DataObjects::FindBin::FindBin (double step, double xmin) inline
Definition at line 146 of file EventList.cpp.
References divisor, findBin, Mantid::DataObjects::EventList::findLinearBin(), Mantid::DataObjects::EventList::findLogBin(), and offset.
Member Function Documentation
operator()()
std::optional< size_t > Mantid::DataObjects::FindBin::operator() (const Mantid::MantidVec & X, const double tof, const bool findExact) inline
Definition at line 158 of file EventList.cpp.
References divisor, findBin, offset, and Mantid::Geometry::X.
Member Data Documentation
divisor
double Mantid::DataObjects::FindBin::divisor
Definition at line 143 of file EventList.cpp.
Referenced by FindBin(), and operator()().
findBin
std::optional< size_t >(* Mantid::DataObjects::FindBin::findBin) (const Mantid::MantidVec &, const double, const double, const double, const bool)
Definition at line 144 of file EventList.cpp.
Referenced by FindBin(), and operator()().
offset
double Mantid::DataObjects::FindBin::offset
Definition at line 144 of file EventList.cpp.
Referenced by FindBin(), and operator()().
The documentation for this struct was generated from the following file:
Framework/DataObjects/src/EventList.cpp