Mantid: Mantid::Kernel::Exception::NotFoundError Class Reference
Mantid::Kernel::Exception::NotFoundError Class Reference final
Exception for when an item is not found in a collection.
#include <Exception.h>
Public Member Functions
NotFoundError (const NotFoundError &A)
Copy constructor.
NotFoundError (const std::string &, const int &)
Constructor.
NotFoundError (const std::string &, const int64_t &)
NotFoundError (const std::string &, const std::size_t &)
NotFoundError (const std::string &, std::string)
Constructor.
NotFoundError & operator= (const NotFoundError &A)
Assignment operator.
const char * what () const noexcept override
Writes out the range and limits.
Private Attributes
const std::string objectName
The name of the search object.
std::string outMessage
The message returned by what()
Detailed Description
Exception for when an item is not found in a collection.
Definition at line 145 of file Exception.h.
Constructor & Destructor Documentation
NotFoundError() [1/5]
Mantid::Kernel::Exception::NotFoundError::NotFoundError (const std::string & Desc, std::string ObjectName)
Constructor.
Parameters
Desc :: Function description
ObjectName :: The name of the search object
Definition at line 66 of file Exception.cpp.
References objectName, and outMessage.
NotFoundError() [2/5]
Mantid::Kernel::Exception::NotFoundError::NotFoundError (const std::string & Desc, const int & ObjectNum)
Constructor.
Parameters
Desc :: Function description
ObjectNum :: The integer search object
Definition at line 75 of file Exception.cpp.
References outMessage.
NotFoundError() [3/5]
Mantid::Kernel::Exception::NotFoundError::NotFoundError (const std::string & Desc, const int64_t & ObjectNum)
Definition at line 83 of file Exception.cpp.
References outMessage.
NotFoundError() [4/5]
Mantid::Kernel::Exception::NotFoundError::NotFoundError (const std::string & Desc, const std::size_t & ObjectNum)
Definition at line 91 of file Exception.cpp.
References outMessage.
NotFoundError() [5/5]
Mantid::Kernel::Exception::NotFoundError::NotFoundError (const NotFoundError & A)
Copy constructor.
Definition at line 100 of file Exception.cpp.
Member Function Documentation
operator=()
NotFoundError & Mantid::Kernel::Exception::NotFoundError::operator= (const NotFoundError & A)
Assignment operator.
what()
const char * Mantid::Kernel::Exception::NotFoundError::what () const override noexcept
Writes out the range and limits.
Returns
a char array of foramtted error information
Definition at line 105 of file Exception.cpp.
References outMessage.
Referenced by Mantid::DataObjects::TableWorkspace::addColumn(), Mantid::Algorithms::NormaliseToMonitor::checkProperties(), Mantid::API::FrameworkManagerImpl::deleteWorkspace(), MantidQt::API::BatchAlgorithmRunner::executeAlgo(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterSimultaneousFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterTFSimultaneousFit(), Mantid::API::FileFinderImpl::getInstrument(), and Mantid::Algorithms::RenameWorkspace::processGroups().
Member Data Documentation
objectName
const std::string Mantid::Kernel::Exception::NotFoundError::objectName private
The name of the search object.
Definition at line 148 of file Exception.h.
Referenced by NotFoundError().
outMessage
std::string Mantid::Kernel::Exception::NotFoundError::outMessage private
The message returned by what()
Definition at line 150 of file Exception.h.
Referenced by NotFoundError(), NotFoundError(), NotFoundError(), NotFoundError(), and what().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Exception.h
Framework/Kernel/src/Exception.cpp