Mantid: Mantid::ICat::CatalogSearchParam Class Reference
Mantid::ICat::CatalogSearchParam Class Reference
This class is used in Catalog Search service to set/get all the inputs to search for.
#include <CatalogSearchParam.h>
Public Member Functions
CatalogSearchParam ()
constructor
const std::string & getDatafileName () const
Get the datafile name.
const time_t & getEndDate () const
Get the investigation end date.
const std::string & getInstrument () const
Get the instrument name.
const std::string & getInvestigationId () const
Get the investigation id.
const std::string & getInvestigationName () const
Get the name of the investigation to search for.
const std::string & getInvestigationType () const
Get the investigation type.
const std::string & getInvestigatorSurName () const
Get the investigators name.
const std::string & getKeywords () const
Get the keywords to search investigations for.
bool getMyData () const
Get the "my data only" flag.
const double & getRunEnd () const
Get the end run.
const double & getRunStart () const
Get the start run from user input.
const std::string & getSampleName () const
Get the sample name.
const time_t & getStartDate () const
Get the investigation start date.
time_t getTimevalue (const std::string &inputDate)
Saves the start/end date times to time_t value.
void setDatafileName (const std::string &datafileName)
Set the datafile name to search for.
void setEndDate (const time_t &endDate)
Set the end date to search for.
void setInstrument (const std::string &instrName)
Set the instrument to search for.
void setInvestigationId (const std::string &)
Set the investigation id to search for.
void setInvestigationName (const std::string &instName)
Set the investigation name to search for.
void setInvestigationType (const std::string &invstType)
Set the investigation type to search for.
void setInvestigatorSurName (const std::string &investigatorName)
Set the investigators name to search for.
void setKeywords (const std::string &keywords)
Set the keywords to search for.
void setMyData (bool flag)
Set the "my data only" flag to search only user's data if true.
void setRunEnd (const double &endRun)
Set the end run to search for.
void setRunStart (const double &startRun)
Set the start run to search for.
void setSampleName (const std::string &sampleName)
Set the sample name to search for.
void setStartDate (const time_t &startDate)
Set the start date to search for.
Private Attributes
std::string m_datafileName
Datafile name.
time_t m_endDate
end date
double m_endRun
end run number
std::string m_instrName
instrument name
std::string m_investigationId
investigation id
std::string m_investigationName
investigation anme
std::string m_investigationType
investigation type
std::string m_investigatorSurname
investigator surname
std::string m_keywords
search keywords
bool m_myData
My data checkbox.
std::string m_sampleName
sample name
time_t m_startDate
start date
double m_startRun
start run number
Detailed Description
This class is used in Catalog Search service to set/get all the inputs to search for.
Definition at line 20 of file CatalogSearchParam.h.
Constructor & Destructor Documentation
CatalogSearchParam()
Mantid::ICat::CatalogSearchParam::CatalogSearchParam ()
constructor
Definition at line 13 of file CatalogSearchParam.cpp.
Member Function Documentation
getDatafileName()
const std::string & Mantid::ICat::CatalogSearchParam::getDatafileName () const
Get the datafile name.
Gets the input from the datafile name field.
Returns
Datafile name
Definition at line 141 of file CatalogSearchParam.cpp.
References m_datafileName.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getEndDate()
const time_t & Mantid::ICat::CatalogSearchParam::getEndDate () const
Get the investigation end date.
Gets the input from the end date name field.
Returns
End date for investigations search
Definition at line 123 of file CatalogSearchParam.cpp.
References m_endDate.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getInstrument()
const std::string & Mantid::ICat::CatalogSearchParam::getInstrument () const
Get the instrument name.
Gets the input from the instrument name field.
Returns
Instrument name
Definition at line 111 of file CatalogSearchParam.cpp.
References m_instrName.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getInvestigationId()
const std::string & Mantid::ICat::CatalogSearchParam::getInvestigationId () const
Get the investigation id.
Gets the input from the investigation id field.
Returns
Investigation id of the investigation.
Definition at line 171 of file CatalogSearchParam.cpp.
References m_investigationId.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getInvestigationName()
const std::string & Mantid::ICat::CatalogSearchParam::getInvestigationName () const
Get the name of the investigation to search for.
Gets the input from the investigation name field.
Returns
Investigation name
Definition at line 135 of file CatalogSearchParam.cpp.
References m_investigationName.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getInvestigationType()
const std::string & Mantid::ICat::CatalogSearchParam::getInvestigationType () const
Get the investigation type.
Gets the input from the investigation type field.
Returns
Type of the investigation
Definition at line 159 of file CatalogSearchParam.cpp.
References m_investigationType.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getInvestigatorSurName()
const std::string & Mantid::ICat::CatalogSearchParam::getInvestigatorSurName () const
Get the investigators name.
Gets the input from the investigator name field.
Returns
Surname of the investigator
Definition at line 153 of file CatalogSearchParam.cpp.
References m_investigatorSurname.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getKeywords()
const std::string & Mantid::ICat::CatalogSearchParam::getKeywords () const
Get the keywords to search investigations for.
Gets the input from the keywords name field.
Returns
Investigation include
Definition at line 129 of file CatalogSearchParam.cpp.
References m_keywords.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getMyData()
bool Mantid::ICat::CatalogSearchParam::getMyData () const
Get the "my data only" flag.
Is "My data only" selected?
Returns
true if my data checkbox is selected.
Definition at line 165 of file CatalogSearchParam.cpp.
References m_myData.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getRunEnd()
const double & Mantid::ICat::CatalogSearchParam::getRunEnd () const
Get the end run.
Gets the input from the investigation name field.
Returns
Run end number
Definition at line 105 of file CatalogSearchParam.cpp.
References m_endRun.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getRunStart()
const double & Mantid::ICat::CatalogSearchParam::getRunStart () const
Get the start run from user input.
This method returns the start run number.
Returns
Run start number
Definition at line 99 of file CatalogSearchParam.cpp.
References m_startRun.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getSampleName()
const std::string & Mantid::ICat::CatalogSearchParam::getSampleName () const
Get the sample name.
Gets the input from the sample name field.
Returns
Samplename
Definition at line 147 of file CatalogSearchParam.cpp.
References m_sampleName.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getStartDate()
const time_t & Mantid::ICat::CatalogSearchParam::getStartDate () const
Get the investigation start date.
Gets the input from the start date name field.
Returns
Start date
Definition at line 117 of file CatalogSearchParam.cpp.
References m_startDate.
Referenced by Mantid::ICat::ICat4Catalog::buildSearchQuery().
getTimevalue()
time_t Mantid::ICat::CatalogSearchParam::getTimevalue (const std::string & inputDate)
Saves the start/end date times to time_t value.
Creates a time_t value from an input date ("23/06/2003").
Parameters
inputDate :: string containing the date.
Returns
time_t value of date
Definition at line 178 of file CatalogSearchParam.cpp.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setDatafileName()
void Mantid::ICat::CatalogSearchParam::setDatafileName (const std::string & datafileName)
Set the datafile name to search for.
This method sets data file name used for searching.
Parameters
datafileName :: data file name to search for
Definition at line 61 of file CatalogSearchParam.cpp.
References m_datafileName.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setEndDate()
void Mantid::ICat::CatalogSearchParam::setEndDate (const time_t & endDate)
Set the end date to search for.
This method sets the end date.
Parameters
endDate :: end date for search
Definition at line 43 of file CatalogSearchParam.cpp.
References m_endDate.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setInstrument()
void Mantid::ICat::CatalogSearchParam::setInstrument (const std::string & instrName)
Set the instrument to search for.
This method sets instrument name.
Parameters
instrName :: name of the instrument
Definition at line 31 of file CatalogSearchParam.cpp.
References m_instrName.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setInvestigationId()
void Mantid::ICat::CatalogSearchParam::setInvestigationId (const std::string & investigationId)
Set the investigation id to search for.
Sets the investigation id to search for.
Parameters
investigationId :: investigation id to search for.
Definition at line 93 of file CatalogSearchParam.cpp.
References m_investigationId.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setInvestigationName()
void Mantid::ICat::CatalogSearchParam::setInvestigationName (const std::string & instName)
Set the investigation name to search for.
This method sets investigationName used for searching.
Parameters
instName :: name of the investigation
Definition at line 55 of file CatalogSearchParam.cpp.
References m_investigationName.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setInvestigationType()
void Mantid::ICat::CatalogSearchParam::setInvestigationType (const std::string & invstType)
Set the investigation type to search for.
This method sets Investigation Type.
Parameters
invstType :: type of investigation
Definition at line 81 of file CatalogSearchParam.cpp.
References m_investigationType.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setInvestigatorSurName()
void Mantid::ICat::CatalogSearchParam::setInvestigatorSurName (const std::string & investigatorName)
Set the investigators name to search for.
This method sets Investigator name.
Parameters
investigatorName :: name of the investigator
Definition at line 73 of file CatalogSearchParam.cpp.
References m_investigatorSurname.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setKeywords()
void Mantid::ICat::CatalogSearchParam::setKeywords (const std::string & keywords)
Set the keywords to search for.
This method sets the keywords to search for.
Parameters
keywords :: keywords used for search
Definition at line 49 of file CatalogSearchParam.cpp.
References m_keywords.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setMyData()
void Mantid::ICat::CatalogSearchParam::setMyData (bool flag)
Set the "my data only" flag to search only user's data if true.
Sets the "My data only" checkbox.
Parameters
flag :: Flag to search in "My data" only.
Definition at line 87 of file CatalogSearchParam.cpp.
References m_myData.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setRunEnd()
void Mantid::ICat::CatalogSearchParam::setRunEnd (const double & endRun)
Set the end run to search for.
This method sets end date.
Parameters
endRun :: end run number
Definition at line 25 of file CatalogSearchParam.cpp.
References m_endRun.
Referenced by Mantid::ICat::CatalogSearch::setRunRanges().
setRunStart()
void Mantid::ICat::CatalogSearchParam::setRunStart (const double & startRun)
Set the start run to search for.
This method sets start date.
Parameters
startRun :: start run number
Definition at line 19 of file CatalogSearchParam.cpp.
References m_startRun.
Referenced by Mantid::ICat::CatalogSearch::setRunRanges().
setSampleName()
void Mantid::ICat::CatalogSearchParam::setSampleName (const std::string & sampleName)
Set the sample name to search for.
This method sets sample used for searching.
Parameters
sampleName :: name of the sample
Definition at line 67 of file CatalogSearchParam.cpp.
References m_sampleName.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
setStartDate()
void Mantid::ICat::CatalogSearchParam::setStartDate (const time_t & startDate)
Set the start date to search for.
This method sets the start date.
Parameters
startDate :: start date for search
Definition at line 37 of file CatalogSearchParam.cpp.
References m_startDate.
Referenced by Mantid::ICat::CatalogSearch::getInputProperties().
Member Data Documentation
m_datafileName
std::string Mantid::ICat::CatalogSearchParam::m_datafileName private
Datafile name.
Definition at line 97 of file CatalogSearchParam.h.
Referenced by getDatafileName(), and setDatafileName().
m_endDate
time_t Mantid::ICat::CatalogSearchParam::m_endDate private
end date
Definition at line 93 of file CatalogSearchParam.h.
Referenced by getEndDate(), and setEndDate().
m_endRun
double Mantid::ICat::CatalogSearchParam::m_endRun private
end run number
Definition at line 85 of file CatalogSearchParam.h.
Referenced by getRunEnd(), and setRunEnd().
m_instrName
std::string Mantid::ICat::CatalogSearchParam::m_instrName private
instrument name
Definition at line 87 of file CatalogSearchParam.h.
Referenced by getInstrument(), and setInstrument().
m_investigationId
std::string Mantid::ICat::CatalogSearchParam::m_investigationId private
investigation id
Definition at line 107 of file CatalogSearchParam.h.
Referenced by getInvestigationId(), and setInvestigationId().
m_investigationName
std::string Mantid::ICat::CatalogSearchParam::m_investigationName private
investigation anme
Definition at line 95 of file CatalogSearchParam.h.
Referenced by getInvestigationName(), and setInvestigationName().
m_investigationType
std::string Mantid::ICat::CatalogSearchParam::m_investigationType private
investigation type
Definition at line 103 of file CatalogSearchParam.h.
Referenced by getInvestigationType(), and setInvestigationType().
m_investigatorSurname
std::string Mantid::ICat::CatalogSearchParam::m_investigatorSurname private
investigator surname
Definition at line 101 of file CatalogSearchParam.h.
Referenced by getInvestigatorSurName(), and setInvestigatorSurName().
m_keywords
std::string Mantid::ICat::CatalogSearchParam::m_keywords private
search keywords
Definition at line 89 of file CatalogSearchParam.h.
Referenced by getKeywords(), and setKeywords().
m_myData
bool Mantid::ICat::CatalogSearchParam::m_myData private
My data checkbox.
Definition at line 105 of file CatalogSearchParam.h.
Referenced by getMyData(), and setMyData().
m_sampleName
std::string Mantid::ICat::CatalogSearchParam::m_sampleName private
sample name
Definition at line 99 of file CatalogSearchParam.h.
Referenced by getSampleName(), and setSampleName().
m_startDate
time_t Mantid::ICat::CatalogSearchParam::m_startDate private
start date
Definition at line 91 of file CatalogSearchParam.h.
Referenced by getStartDate(), and setStartDate().
m_startRun
double Mantid::ICat::CatalogSearchParam::m_startRun private
start run number
Definition at line 83 of file CatalogSearchParam.h.
Referenced by getRunStart(), and setRunStart().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/CatalogSearchParam.h
Framework/ICat/src/CatalogSearchParam.cpp