Mantid: MantidQt::MantidWidgets::DiagResults Class Reference
MantidQt::MantidWidgets::DiagResults Class Reference
#include <DiagResults.h>
Signals
void died ()
is emitted just before the window dies to let the window that created this know the pointer it has is invalid
Signals inherited from MantidQt::API::MantidDialog
void runAsPythonScript (const QString &code, bool)
Public Member Functions
DiagResults (QWidget *parent)
Constructor.
void updateResults (const QString &testSummary)
Update the results on the dialog.
Public Member Functions inherited from MantidQt::API::MantidDialog
MantidDialog (QWidget *parent=nullptr, const Qt::WindowFlags &flags=Qt::WindowCloseButtonHint|Qt::WindowType::WindowTitleHint)
DefaultConstructor.
~MantidDialog () override
Destructor.
Private Member Functions
int addRow (const QString &firstColumn, const QString &secondColumn)
insert a row at the bottom of the grid
void closeEvent (QCloseEvent *event) override
enables the run button on the parent window so the user can do more analysis
void updateRow (int row, const QString &text)
Displays a summary of the results of tests in to text labels.
Private Attributes
QGridLayout * m_Grid
the layout that widgets are added to
Additional Inherited Members
Static Public Member Functions inherited from MantidQt::API::MantidDialog
static bool handle (QObject *receiver, const std::exception &e)
Handles the exception caught in an event handler.
Protected Member Functions inherited from MantidQt::API::MantidDialog
virtual void handleException (const std::exception &e)
Override this method to handle an exception in a derived class.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Detailed Description
Definition at line 18 of file DiagResults.h.
Constructor & Destructor Documentation
DiagResults()
DiagResults::DiagResults (QWidget * parent)
Constructor.
Definition at line 48 of file DiagResults.cpp.
References addRow(), and m_Grid.
Member Function Documentation
addRow()
int DiagResults::addRow (const QString & firstColumn, const QString & secondColumn) private
insert a row at the bottom of the grid
Definition at line 111 of file DiagResults.cpp.
References m_Grid.
Referenced by DiagResults().
closeEvent()
void DiagResults::closeEvent (QCloseEvent * event) override private
enables the run button on the parent window so the user can do more analysis
Definition at line 131 of file DiagResults.cpp.
References died().
died
void MantidQt::MantidWidgets::DiagResults::died () signal
is emitted just before the window dies to let the window that created this know the pointer it has is invalid
Referenced by closeEvent().
updateResults()
void DiagResults::updateResults (const QString & testSummary)
Update the results on the dialog.
Parameters
testSummary :: A string containing the test results
Definition at line 72 of file DiagResults.cpp.
References updateRow().
updateRow()
void DiagResults::updateRow (int row, const QString & text) private
Displays a summary of the results of tests in to text labels.
Parameters
row :: the row where the data will be displayed
text :: the text that should be displayed in the first column
Definition at line 123 of file DiagResults.cpp.
References m_Grid.
Referenced by updateResults().
Member Data Documentation
m_Grid
QGridLayout* MantidQt::MantidWidgets::DiagResults::m_Grid private
the layout that widgets are added to
Definition at line 37 of file DiagResults.h.
Referenced by addRow(), DiagResults(), and updateRow().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/DiagResults.h
qt/widgets/common/src/DiagResults.cpp