Mantid: Mantid::DataHandling::LoadNexusProcessed Class Reference
Mantid::DataHandling::LoadNexusProcessed Class Reference
Loads a workspace from a NeXus Processed entry in a NeXus file.
#include <LoadNexusProcessed.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
int confidence (Kernel::NexusDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadNexusProcessed ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
~LoadNexusProcessed () override
Destructor.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::NexusDescriptor >
virtual int confidence (Kernel::NexusDescriptor &descriptor) const=0
Returns a confidence value that this algorithm can load a file.
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Protected Member Functions
void readInstrumentGroup (Mantid::NeXus::NXEntry &mtd_entry, API::MatrixWorkspace &local_workspace)
Read the spectra.
Protected Member Functions inherited from Mantid::API::ParallelAlgorithm
Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const override
Get correct execution mode based on input storage modes for an MPI run.
~ParallelAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Private Member Functions
bool addSampleProperty (Mantid::NeXus::NXMainClass &sample_entry, const std::string &entryName, API::Sample &sampleDetails)
Add a property to the sample object.
void applyLogFiltering (const Mantid::API::Workspace_sptr &local_workspace)
applies log filtering of the loaded logs if required
std::string buildWorkspaceName (const std::string &name, const std::string &baseName, size_t wsIndex)
Create the workspace name if it's part of a group workspace.
std::size_t calculateWorkspaceSize (const std::size_t numberofspectra, bool gen_filtered_list=false)
calculates the workspace size
void checkOptionalProperties (const std::size_t numberofspectra)
Validates the optional 'spectra to read' properties, if they have been set.
void correctForWorkspaceNameClash (std::string &wsName)
Add an index to the name if it already exists in the workspace.
Mantid::API::Workspace_sptr doAccelleratedMultiPeriodLoading (Mantid::NeXus::NXRoot &root, const std::string &entryName, Mantid::API::MatrixWorkspace_sptr &tempMatrixWorkspace, const size_t nWorkspaceEntries, const size_t p)
Accellerated multiperiod loading.
void exec () override
Overwrites Algorithm method.
std::vector< std::string > extractWorkspaceNames (Mantid::NeXus::NXRoot &root, size_t nWorkspaceEntries)
Extract the workspace name.
void getWordsInString (const std::string &words3, std::string &w1, std::string &w2, std::string &w3)
Splits a string of exactly three words into the separate words.
void getWordsInString (const std::string &words4, std::string &w1, std::string &w2, std::string &w3, std::string &w4)
Splits a string of exactly four words into the separate words.
void init () override
Overwrites Algorithm method.
void loadBlock (Mantid::NeXus::NXDataSetTyped< double > &data, Mantid::NeXus::NXDataSetTyped< double > &errors, Mantid::NeXus::NXDataSetTyped< double > &farea, bool hasFArea, Mantid::NeXus::NXDouble &xErrors, bool hasXErrors, int blocksize, int nchannels, int &hist, const API::MatrixWorkspace_sptr &local_workspace)
Load a block of data into the workspace where it is assumed that the x bins have already been cached.
void loadBlock (Mantid::NeXus::NXDataSetTyped< double > &data, Mantid::NeXus::NXDataSetTyped< double > &errors, Mantid::NeXus::NXDataSetTyped< double > &farea, bool hasFArea, Mantid::NeXus::NXDouble &xErrors, bool hasXErrors, int blocksize, int nchannels, int &hist, int &wsIndex, const API::MatrixWorkspace_sptr &local_workspace)
Load a block of data into the workspace where it is assumed that the x bins have already been cached.
void loadBlock (Mantid::NeXus::NXDataSetTyped< double > &data, Mantid::NeXus::NXDataSetTyped< double > &errors, Mantid::NeXus::NXDataSetTyped< double > &farea, bool hasFArea, Mantid::NeXus::NXDouble &xErrors, bool hasXErrors, Mantid::NeXus::NXDouble &xbins, int blocksize, int nchannels, int &hist, int &wsIndex, const API::MatrixWorkspace_sptr &local_workspace)
Load a block of data into the workspace.
API::Workspace_sptr loadEntry (Mantid::NeXus::NXRoot &root, const std::string &entry_name, const double &progressStart, const double &progressRange)
Load a single entry.
API::MatrixWorkspace_sptr loadEventEntry (Mantid::NeXus::NXData &wksp_cls, Mantid::NeXus::NXDouble &xbins, const double &progressStart, const double &progressRange)
Load an event_workspace field.
API::Workspace_sptr loadLeanElasticPeaksEntry (Mantid::NeXus::NXEntry &entry)
Load LeanElasticPeakWorkspace.
virtual bool loadNexusGeometry (Mantid::API::Workspace &, const int, Kernel::Logger &, const std::string &)
Load nexus geometry and apply to workspace.
API::MatrixWorkspace_sptr loadNonEventEntry (Mantid::NeXus::NXData &wksp_cls, Mantid::NeXus::NXDouble &xbins, const double &progressStart, const double &progressRange, const Mantid::NeXus::NXEntry &mtd_entry, const int xlength, std::string &workspaceType)
Load a Workspace2D.
void loadNonSpectraAxis (const API::MatrixWorkspace_sptr &local_workspace, Mantid::NeXus::NXData &data)
Load the data from a non-spectra axis (Numeric/Text) into the workspace.
template<typename ColumnType , typename NexusType >
void loadNumericColumn (const Mantid::NeXus::NXData &tableData, const std::string &dataSetName, const API::ITableWorkspace_sptr &tableWs, const std::string &columnType)
Load a numeric column to the TableWorkspace.
API::Workspace_sptr loadPeaksEntry (Mantid::NeXus::NXEntry &entry)
Load peaks.
API::Workspace_sptr loadTableEntry (const Mantid::NeXus::NXEntry &entry)
Load a table.
void loadV3DColumn (Mantid::NeXus::NXDouble &data, const API::ITableWorkspace_sptr &tableWs)
Loads a V3D column to the TableWorkspace.
template<typename Type >
void loadVectorColumn (const Mantid::NeXus::NXData &tableData, const std::string &dataSetName, const API::ITableWorkspace_sptr &tableWs, const std::string &columnType)
Loads a vector column to the TableWorkspace.
std::string loadWorkspaceName (Mantid::NeXus::NXRoot &root, const std::string &entry_name)
Load the workspace name attribute if it exists.
void readBinMasking (const Mantid::NeXus::NXData &wksp_cls, const API::MatrixWorkspace_sptr &local_workspace)
Read the bin masking information.
void readSampleGroup (Mantid::NeXus::NXEntry &mtd_entry, API::MatrixWorkspace_sptr local_workspace)
Read the data from the sample group.
virtual void readSpectraToDetectorMapping (Mantid::NeXus::NXEntry &mtd_entry, Mantid::API::MatrixWorkspace &ws)
std::map< std::string, std::string > validateInputs () override
Validates the input Min < Max and Max < Maximum_Int.
Private Attributes
MantidVec m_axis1vals
Numeric values for the second axis, if applicable.
std::vector< int > m_filtered_spec_idxs
list of spectra filtered by min/max/list, currently used only when loading data into event_workspace
bool m_interval
Flag set if interval of spectra to write is set.
bool m_list
Flag set if list of spectra to save is specifed.
std::unique_ptr<::NeXus::File > m_nexusFile
bool m_shared_bins
Does the current workspace have uniform binning.
std::vector< int > m_spec_list
The value of the spectrum_list property.
int m_spec_max
The value of the spectrum_max property.
int m_spec_min
The value of the spectrum_min property.
HistogramData::BinEdges m_xbins
The cached x binning if we have bins.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Loads a workspace from a NeXus Processed entry in a NeXus file.
LoadNexusProcessed is an algorithm and as such inherits from the Algorithm class, via DataHandlingCommand, and overrides the init() & exec() methods.
Required Properties:
Filename - The name of the input NeXus file (must exist)
InputWorkspace - The name of the workspace to put the data
Definition at line 43 of file LoadNexusProcessed.h.
Constructor & Destructor Documentation
LoadNexusProcessed()
Mantid::DataHandling::LoadNexusProcessed::LoadNexusProcessed ()
Default constructor.
Definition at line 179 of file LoadNexusProcessed.cpp.
~LoadNexusProcessed()
Mantid::DataHandling::LoadNexusProcessed::~LoadNexusProcessed () override default
Destructor.
Destructor defined here so that NeXus::File can be forward declared in header.
Member Function Documentation
addSampleProperty()
bool Mantid::DataHandling::LoadNexusProcessed::addSampleProperty (Mantid::NeXus::NXMainClass & sample_entry, const std::string & entryName, API::Sample & sampleDetails) private
Add a property to the sample object.
References Mantid::API::getWordsInString().
applyLogFiltering()
void Mantid::DataHandling::LoadNexusProcessed::applyLogFiltering (const Mantid::API::Workspace_sptr & local_workspace) private
applies log filtering of the loaded logs if required
Applies log filtering to workspaces that require it.
Parameters
local_workspace :: the workspace containing logs to be filtered
Definition at line 2418 of file LoadNexusProcessed.cpp.
References Mantid::DataHandling::ISISRunLogs::applyLogFiltering(), Mantid::API::LogManager::hasProperty(), Mantid::Kernel::LogParser::periodsLogName(), and Mantid::Kernel::LogParser::statusLogName().
Referenced by exec().
buildWorkspaceName()
std::string Mantid::DataHandling::LoadNexusProcessed::buildWorkspaceName (const std::string & name, const std::string & baseName, size_t wsIndex) private
Create the workspace name if it's part of a group workspace.
Decides what to call a child of a group workspace.
This function builds the workspace name based on either a workspace name which was stored in the file or the base name.
Parameters
name :: The name loaded from the file (possibly the empty string if none was loaded)
baseName :: The name group workspace
wsIndex :: The current index of this workspace
Returns
The name of the workspace
Definition at line 524 of file LoadNexusProcessed.cpp.
References correctForWorkspaceNameClash(), index, name(), and std::to_string().
Referenced by exec().
calculateWorkspaceSize()
size_t Mantid::DataHandling::LoadNexusProcessed::calculateWorkspaceSize (const std::size_t numberofspectra, bool gen_filtered_list = false) private
calculates the workspace size
Calculate the size of a workspace.
Parameters
numberofspectra :: count of spectra found in the file being loaded
gen_filtered_list :: process SpectrumList and SpectrumMin/Max and save resulting explicit list of spectra indices into a vector data member, presently used only when loading into event_workspace
Returns
the size of a workspace
Definition at line 2359 of file LoadNexusProcessed.cpp.
References m_filtered_spec_idxs, m_interval, m_list, m_spec_list, m_spec_max, and m_spec_min.
Referenced by loadEventEntry(), and loadNonEventEntry().
category()
const std::string Mantid::DataHandling::LoadNexusProcessed::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 64 of file LoadNexusProcessed.h.
checkOptionalProperties()
void Mantid::DataHandling::LoadNexusProcessed::checkOptionalProperties (const std::size_t numberofspectra) private
Validates the optional 'spectra to read' properties, if they have been set.
Parameters
numberofspectra :: number of spectrum
Definition at line 2305 of file LoadNexusProcessed.cpp.
References Mantid::EMPTY_INT(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), m_interval, m_list, m_spec_list, m_spec_max, and m_spec_min.
Referenced by loadEventEntry(), and loadNonEventEntry().
confidence()
int Mantid::DataHandling::LoadNexusProcessed::confidence (Kernel::NexusDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::NexusDescriptor >.
Reimplemented in Mantid::DataHandling::LoadNexusProcessed2.
Definition at line 193 of file LoadNexusProcessed.cpp.
References Mantid::Kernel::NexusDescriptor::pathExists().
Referenced by Mantid::DataHandling::LoadNexusProcessed2::confidence().
correctForWorkspaceNameClash()
void Mantid::DataHandling::LoadNexusProcessed::correctForWorkspaceNameClash (std::string & wsName) private
Add an index to the name if it already exists in the workspace.
Append an index to the name if it already exists in the AnalysisDataService.
Parameters
wsName :: Name to call the workspace
Definition at line 554 of file LoadNexusProcessed.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and std::to_string().
Referenced by buildWorkspaceName().
doAccelleratedMultiPeriodLoading()
Workspace_sptr Mantid::DataHandling::LoadNexusProcessed::doAccelleratedMultiPeriodLoading (Mantid::NeXus::NXRoot & root, const std::string & entryName, Mantid::API::MatrixWorkspace_sptr & tempMatrixWorkspace, const size_t nWorkspaceEntries, const size_t p) private
Accellerated multiperiod loading.
Loading specifically for mulitperiod group workspaces.
Parameters
root : NXRoot ref
entryName : Entry name to load.
tempMatrixWorkspace : Template workspace to base the next multiperiod entry off.
nWorkspaceEntries : N entries in the file
p : index + 1 being processed.
Returns
Next multiperiod group workspace
Definition at line 251 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXClass::close(), Mantid::NeXus::NXDataSet::dim1(), Mantid::API::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXClass::isValid(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_nexusFile, m_spec_max, m_spec_min, Mantid::NeXus::NXDataSet::openLocal(), Mantid::NeXus::NXClass::openLocal(), Mantid::API::Algorithm::progress(), and Mantid::Geometry::Y.
Referenced by exec().
exec()
void Mantid::DataHandling::LoadNexusProcessed::exec () override private virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Exceptions
runtime_error Thrown if algorithm cannot execute
Implements Mantid::API::Algorithm.
Definition at line 373 of file LoadNexusProcessed.cpp.
References applyLogFiltering(), buildWorkspaceName(), Mantid::NeXus::NXClass::close(), Mantid::API::Algorithm::declareProperty(), doAccelleratedMultiPeriodLoading(), Mantid::Kernel::Logger::error(), extractWorkspaceNames(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::NeXus::NXClass::groups(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Kernel::Property::isDefault(), loadEntry(), loadNexusGeometry(), m_axis1vals, Mantid::NeXus::NXObject::m_fileID, m_list, m_nexusFile, Mantid::Kernel::Direction::Output, Mantid::API::Algorithm::progress(), Mantid::Kernel::IPropertyManager::setProperty(), and std::to_string().
extractWorkspaceNames()
std::vector< std::string > Mantid::DataHandling::LoadNexusProcessed::extractWorkspaceNames (Mantid::NeXus::NXRoot & root, size_t nWorkspaceEntries) private
Extract the workspace name.
Extract the workspace names from the file (if any are stored)
Parameters
root :: the root for the NeXus document
nWorkspaceEntries :: the number of workspace entries
Definition at line 578 of file LoadNexusProcessed.cpp.
References loadWorkspaceName(), and std::to_string().
Referenced by exec().
getWordsInString() [1/2]
void Mantid::DataHandling::LoadNexusProcessed::getWordsInString (const std::string & words3, std::string & w1, std::string & w2, std::string & w3) private
Splits a string of exactly three words into the separate words.
If the first string contains exactly three words separated by spaces these words will be copied into each of the following strings that were passed.
Parameters
[in] words3 a string with 3 words separated by spaces
[out] w1 the first word in the input string
[out] w2 the second word in the input string
[out] w3 the third word in the input string
Exceptions
out_of_range if there aren't exaltly three strings in the word
Definition at line 1994 of file LoadNexusProcessed.cpp.
References Mantid::Kernel::StringTokenizer::count(), Mantid::API::g_log, Mantid::Kernel::StringTokenizer::TOK_TRIM, and Mantid::Kernel::Logger::warning().
getWordsInString() [2/2]
void Mantid::DataHandling::LoadNexusProcessed::getWordsInString (const std::string & words4, std::string & w1, std::string & w2, std::string & w3, std::string & w4) private
Splits a string of exactly four words into the separate words.
If the first string contains exactly four words separated by spaces these words will be copied into each of the following strings that were passed.
Parameters
[in] words4 a string with 4 words separated by spaces
[out] w1 the first word in the input string
[out] w2 the second word in the input string
[out] w3 the third word in the input string
[out] w4 the fourth word in the input string
Exceptions
out_of_range if there aren't exaltly four strings in the word
Definition at line 2018 of file LoadNexusProcessed.cpp.
References Mantid::Kernel::StringTokenizer::count(), Mantid::API::g_log, Mantid::Kernel::StringTokenizer::TOK_TRIM, and Mantid::Kernel::Logger::warning().
init()
void Mantid::DataHandling::LoadNexusProcessed::init () override private virtual
Overwrites Algorithm method.
Initialisation method.
Implements Mantid::API::Algorithm.
Definition at line 207 of file LoadNexusProcessed.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
loadBlock() [1/3]
void Mantid::DataHandling::LoadNexusProcessed::loadBlock (Mantid::NeXus::NXDataSetTyped< double > & data, Mantid::NeXus::NXDataSetTyped< double > & errors, Mantid::NeXus::NXDataSetTyped< double > & farea, bool hasFArea, Mantid::NeXus::NXDouble & xErrors, bool hasXErrors, int blocksize, int nchannels, int & hist, const API::MatrixWorkspace_sptr & local_workspace) private
Load a block of data into the workspace where it is assumed that the x bins have already been cached.
Perform a call to nxgetslab, via the NexusClasses wrapped methods for a given blocksize.
This assumes that the xbins have alread been cached
Parameters
data :: The NXDataSet object of y values
errors :: The NXDataSet object of error values
farea :: The NXDataSet object of fraction area values
hasFArea :: Flag to signal a RebinnedOutput workspace is in use
xErrors :: The NXDataSet object of xError values
hasXErrors :: Flag to signal the File contains x errors
blocksize :: The blocksize to use
nchannels :: The number of channels for the block
hist :: The workspace index to start reading into
local_workspace :: A pointer to the workspace
Definition at line 2077 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_xbins, and Mantid::Geometry::Y.
Referenced by loadNonEventEntry().
loadBlock() [2/3]
void Mantid::DataHandling::LoadNexusProcessed::loadBlock (Mantid::NeXus::NXDataSetTyped< double > & data, Mantid::NeXus::NXDataSetTyped< double > & errors, Mantid::NeXus::NXDataSetTyped< double > & farea, bool hasFArea, Mantid::NeXus::NXDouble & xErrors, bool hasXErrors, int blocksize, int nchannels, int & hist, int & wsIndex, const API::MatrixWorkspace_sptr & local_workspace) private
Load a block of data into the workspace where it is assumed that the x bins have already been cached.
Perform a call to nxgetslab, via the NexusClasses wrapped methods for a given blocksize.
This assumes that the xbins have alread been cached
Parameters
data :: The NXDataSet object of y values
errors :: The NXDataSet object of error values
farea :: The NXDataSet object of fraction area values
hasFArea :: Flag to signal a RebinnedOutput workspace is in use
xErrors :: The NXDataSet object of xError values
hasXErrors :: Flag to signal the File contains x errors
blocksize :: The blocksize to use
nchannels :: The number of channels for the block
hist :: The workspace index to start reading into
wsIndex :: The workspace index to save data into
local_workspace :: A pointer to the workspace
Definition at line 2155 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_xbins, and Mantid::Geometry::Y.
loadBlock() [3/3]
void Mantid::DataHandling::LoadNexusProcessed::loadBlock (Mantid::NeXus::NXDataSetTyped< double > & data, Mantid::NeXus::NXDataSetTyped< double > & errors, Mantid::NeXus::NXDataSetTyped< double > & farea, bool hasFArea, Mantid::NeXus::NXDouble & xErrors, bool hasXErrors, Mantid::NeXus::NXDouble & xbins, int blocksize, int nchannels, int & hist, int & wsIndex, const API::MatrixWorkspace_sptr & local_workspace) private
Load a block of data into the workspace.
Perform a call to nxgetslab, via the NexusClasses wrapped methods for a given blocksize.
The xbins are read along with each call to the data/error loading
Parameters
data :: The NXDataSet object of y values
errors :: The NXDataSet object of error values
farea :: The NXDataSet object of fraction area values
hasFArea :: Flag to signal a RebinnedOutput workspace is in use
xErrors :: The NXDataSet object of xError values
hasXErrors :: Flag to signal the File contains x errors
xbins :: The xbin NXDataSet
blocksize :: The blocksize to use
nchannels :: The number of channels for the block
hist :: The workspace index to start reading into
wsIndex :: The workspace index to save data into
local_workspace :: A pointer to the workspace
Definition at line 2233 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXDataSet::dim1(), Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::Geometry::X, and Mantid::Geometry::Y.
loadEntry()
API::Workspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadEntry (Mantid::NeXus::NXRoot & root, const std::string & entry_name, const double & progressStart, const double & progressRange) private
Load a single entry.
Load a single entry into a workspace (event_workspace or workspace2d)
Parameters
root :: The opened root node
entry_name :: The entry name
progressStart :: The percentage value to start the progress reporting for this entry
progressRange :: The percentage range that the progress reporting should cover
Returns
A 2D workspace containing the loaded data
Definition at line 1669 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXClass::containsGroup(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::NeXus::NXClass::getString(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXDataSetTyped< T >::load(), loadEventEntry(), loadLeanElasticPeaksEntry(), loadNonEventEntry(), loadNonSpectraAxis(), loadPeaksEntry(), loadTableEntry(), m_axis1vals, m_nexusFile, m_shared_bins, m_xbins, Mantid::NeXus::NXRoot::openEntry(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXObject::path(), Mantid::API::Algorithm::progress(), Mantid::NeXus::NXDataSet::rank(), readSpectraToDetectorMapping(), Mantid::NeXus::NXDataSetTyped< T >::size(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
loadEventEntry()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadEventEntry (Mantid::NeXus::NXData & wksp_cls, Mantid::NeXus::NXDouble & xbins, const double & progressStart, const double & progressRange) private
Load an event_workspace field.
Parameters
wksp_cls Nexus data for "event_workspace"
xbins bins on the "X" axis
progressStart algorithm progress (from 0)
progressRange progress made after loading an entry
Returns
event_workspace object with data
Definition at line 625 of file LoadNexusProcessed.cpp.
References Mantid::DataObjects::EventList::addEventQuickly(), Mantid::NeXus::NXObject::attributes, calculateWorkspaceSize(), checkOptionalProperties(), Mantid::API::ISpectrum::clearDetectorIDs(), Mantid::DataObjects::create(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXClass::isValid(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_filtered_spec_idxs, m_shared_bins, m_xbins, Mantid::NeXus::NXClass::openNXDataSet(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXClass::openNXFloat(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_START_INTERRUPT_REGION, Mantid::API::Algorithm::progress(), Mantid::NeXus::NXDataSet::rank(), Mantid::DataObjects::EventList::reserve(), Mantid::API::ISpectrum::setHistogram(), Mantid::DataObjects::EventList::switchTo(), Mantid::API::TOF, Mantid::NeXus::NXDataSetTyped< T >::vecBuffer(), Mantid::API::WEIGHTED, Mantid::API::WEIGHTED_NOTIME, and Mantid::Geometry::x.
Referenced by loadEntry().
loadLeanElasticPeaksEntry()
API::Workspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry (Mantid::NeXus::NXEntry & entry) private
Load LeanElasticPeakWorkspace.
Parameters
entry
Returns
API::Workspace_sptr
Definition at line 928 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXDataSet::dim0(), Mantid::API::g_log, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_nexusFile, Mantid::Kernel::Logger::notice(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXClass::openNXInt(), Mantid::NeXus::NXObject::path(), Mantid::DataObjects::BasePeak::setGoniometerMatrix(), Mantid::DataObjects::BasePeak::setRunNumber(), Mantid::NeXus::NXInfo::stat, std::to_string(), Mantid::NeXus::NXInfo::type, and value.
Referenced by loadEntry().
loadNexusGeometry()
virtual bool Mantid::DataHandling::LoadNexusProcessed::loadNexusGeometry (Mantid::API::Workspace & , const int , Kernel::Logger & , const std::string &) inline private virtual
Load nexus geometry and apply to workspace.
Reimplemented in Mantid::DataHandling::LoadNexusProcessed2.
Definition at line 96 of file LoadNexusProcessed.h.
Referenced by exec().
loadNonEventEntry()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry (Mantid::NeXus::NXData & wksp_cls, Mantid::NeXus::NXDouble & xbins, const double & progressStart, const double & progressRange, const Mantid::NeXus::NXEntry & mtd_entry, const int xlength, std::string & workspaceType) private
Load a Workspace2D.
Parameters
wksp_cls Nexus data for "Workspace2D" (or "offsets_workspace")
xbins bins on the "X" axis
progressStart algorithm progress (from 0)
progressRange progress made after loading an entry
mtd_entry Nexus entry for "mantid_workspace_..."
xlength bins in the "X" axis (xbins)
workspaceType Takes values like "Workspace2D", "RebinnedOutput", etc.
Returns
workspace object containing loaded data
Definition at line 1435 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, calculateWorkspaceSize(), checkOptionalProperties(), Mantid::NeXus::NXClass::containsGroup(), Mantid::DataObjects::create(), Mantid::Kernel::Logger::debug(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSet::dim1(), Mantid::API::g_log, Mantid::API::Algorithm::getPropertyValue(), Mantid::NeXus::NXClass::getString(), Mantid::NeXus::NXClass::groups(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXClass::isValid(), loadBlock(), m_interval, m_list, m_shared_bins, m_spec_list, m_spec_max, m_spec_min, Mantid::NeXus::NXData::openDoubleData(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXClass::openNXGroup(), Mantid::API::Algorithm::progress(), readBinMasking(), and Mantid::Kernel::Logger::warning().
Referenced by loadEntry().
loadNonSpectraAxis()
void Mantid::DataHandling::LoadNexusProcessed::loadNonSpectraAxis (const API::MatrixWorkspace_sptr & local_workspace, Mantid::NeXus::NXData & data) private
Load the data from a non-spectra axis (Numeric/Text) into the workspace.
Loads the information contained in non-Spectra (ie, Text or Numeric) axis in the Nexus file into the workspace.
Parameters
local_workspace :: pointer to workspace object
data :: reference to the NeXuS data for the axis
Definition at line 1924 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXDataSet::dim0(), Mantid::API::Axis::isNumeric(), Mantid::API::Axis::isText(), Mantid::API::Axis::length(), Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::NeXus::NXClass::openNXChar(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::API::TextAxis::setLabel(), Mantid::API::Axis::setValue(), and Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY.
Referenced by loadEntry().
loadNumericColumn()
template<typename ColumnType , typename NexusType > void Mantid::DataHandling::LoadNexusProcessed::loadNumericColumn (const Mantid::NeXus::NXData & tableData, const std::string & dataSetName, const API::ITableWorkspace_sptr & tableWs, const std::string & columnType) private
Load a numeric column to the TableWorkspace.
Parameters
tableData :: Table data to load from
dataSetName :: Name of the data set to use to get column data
tableWs :: Workspace to add column to
columnType :: Name of the column type to create
Definition at line 756 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSetTyped< T >::load(), and Mantid::NeXus::NXClass::openNXDataSet().
loadPeaksEntry()
API::Workspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry (Mantid::NeXus::NXEntry & entry) private
Load peaks.
Definition at line 1160 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXInfo::dims, Mantid::API::g_log, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_nexusFile, Mantid::NeXus::NXClass::openNXChar(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXClass::openNXInt(), Mantid::NeXus::NXObject::path(), Mantid::DataObjects::BasePeak::setGoniometerMatrix(), Mantid::DataObjects::Peak::setInstrument(), Mantid::DataObjects::BasePeak::setRunNumber(), Mantid::NeXus::NXInfo::stat, std::to_string(), Mantid::NeXus::NXInfo::type, and value.
Referenced by loadEntry().
loadTableEntry()
API::Workspace_sptr Mantid::DataHandling::LoadNexusProcessed::loadTableEntry (const Mantid::NeXus::NXEntry & entry) private
Load a table.
Definition at line 782 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXInfo::dims, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::NeXus::NXDataSetTyped< T >::load(), loadV3DColumn(), Mantid::NeXus::NXClass::openNXChar(), Mantid::NeXus::NXEntry::openNXData(), Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXInfo::rank, Mantid::NeXus::NXInfo::stat, std::to_string(), Mantid::NeXus::NXInfo::type, and workspace.
Referenced by loadEntry().
loadV3DColumn()
void Mantid::DataHandling::LoadNexusProcessed::loadV3DColumn (Mantid::NeXus::NXDouble & data, const API::ITableWorkspace_sptr & tableWs) private
Loads a V3D column to the TableWorkspace.
Parameters
data :: Table data to load from
tableWs :: Workspace to add column to
Definition at line 903 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXDataSet::dim0(), and Mantid::NeXus::NXDataSetTyped< T >::load().
Referenced by loadTableEntry().
loadVectorColumn()
template<typename Type > void Mantid::DataHandling::LoadNexusProcessed::loadVectorColumn (const Mantid::NeXus::NXData & tableData, const std::string & dataSetName, const API::ITableWorkspace_sptr & tableWs, const std::string & columnType) private
Loads a vector column to the TableWorkspace.
Parameters
tableData :: Table data to load from
dataSetName :: Name of the data set to use to get column data
tableWs :: Workspace to add column to
columnType :: Name of the column type to create
Definition at line 861 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXObject::attributes, Mantid::NeXus::NXInfo::dims, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::NeXus::NXDataSetTyped< T >::load(), and Mantid::NeXus::NXClass::openNXDataSet().
loadWorkspaceName()
std::string Mantid::DataHandling::LoadNexusProcessed::loadWorkspaceName (Mantid::NeXus::NXRoot & root, const std::string & entry_name) private
Load the workspace name attribute if it exists.
Load the workspace name, if the attribute exists.
Parameters
root :: Root of NeXus file
entry_name :: Entry in NeXus file to look at
Returns
The workspace name. If none found an empty string is returned.
Definition at line 603 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXClass::close(), Mantid::NeXus::NXClass::getString(), and Mantid::NeXus::NXRoot::openEntry().
Referenced by extractWorkspaceNames().
name()
const std::string Mantid::DataHandling::LoadNexusProcessed::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadNexusProcessed2.
Definition at line 51 of file LoadNexusProcessed.h.
Referenced by buildWorkspaceName().
readBinMasking()
void Mantid::DataHandling::LoadNexusProcessed::readBinMasking (const Mantid::NeXus::NXData & wksp_cls, const API::MatrixWorkspace_sptr & local_workspace) private
Read the bin masking information.
Read the bin masking information from the mantid_workspace_i/workspace group.
Parameters
wksp_cls :: The data group
local_workspace :: The workspace to read into
Definition at line 2039 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::NeXus::NXDataSetTyped< T >::load(), n, Mantid::NeXus::NXClass::openNXDouble(), Mantid::NeXus::NXClass::openNXInt(), Mantid::NeXus::NXClass::openNXSize(), and Mantid::NeXus::NXInfo::stat.
Referenced by loadNonEventEntry().
readInstrumentGroup()
void Mantid::DataHandling::LoadNexusProcessed::readInstrumentGroup (Mantid::NeXus::NXEntry & mtd_entry, API::MatrixWorkspace & local_workspace) protected
Read the spectra.
Read the instrument group.
Parameters
mtd_entry :: The node for the current workspace
local_workspace :: The workspace to attach the instrument
Definition at line 1853 of file LoadNexusProcessed.cpp.
References Mantid::API::g_log, Mantid::API::MatrixWorkspace::getAxis(), Mantid::API::MatrixWorkspace::getSpectrum(), index, Mantid::API::Axis::isSpectra(), m_axis1vals, m_list, m_spec_list, m_spec_max, m_spec_min, and Mantid::API::ISpectrum::setSpectrumNo().
Referenced by readSpectraToDetectorMapping(), and Mantid::DataHandling::LoadNexusProcessed2::readSpectraToDetectorMapping().
readSampleGroup()
void Mantid::DataHandling::LoadNexusProcessed::readSampleGroup (Mantid::NeXus::NXEntry & mtd_entry, API::MatrixWorkspace_sptr local_workspace) private
Read the data from the sample group.
readSpectraToDetectorMapping()
void Mantid::DataHandling::LoadNexusProcessed::readSpectraToDetectorMapping (Mantid::NeXus::NXEntry & mtd_entry, Mantid::API::MatrixWorkspace & ws) private virtual
Reimplemented in Mantid::DataHandling::LoadNexusProcessed2.
Definition at line 200 of file LoadNexusProcessed.cpp.
References readInstrumentGroup().
Referenced by loadEntry().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadNexusProcessed::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 62 of file LoadNexusProcessed.h.
summary()
const std::string Mantid::DataHandling::LoadNexusProcessed::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 53 of file LoadNexusProcessed.h.
validateInputs()
std::map< std::string, std::string > Mantid::DataHandling::LoadNexusProcessed::validateInputs (void) override private virtual
Validates the input Min < Max and Max < Maximum_Int.
Validates SpectrumMin and SpectrumMax conditions.
Returns
Returns a map indicating invalid input combinations
Reimplemented from Mantid::API::Algorithm.
Definition at line 1898 of file LoadNexusProcessed.cpp.
References Mantid::API::Algorithm::getProperty().
version()
int Mantid::DataHandling::LoadNexusProcessed::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadNexusProcessed2.
Definition at line 61 of file LoadNexusProcessed.h.
Member Data Documentation
m_axis1vals
MantidVec Mantid::DataHandling::LoadNexusProcessed::m_axis1vals private
Numeric values for the second axis, if applicable.
Definition at line 185 of file LoadNexusProcessed.h.
Referenced by exec(), loadEntry(), and readInstrumentGroup().
m_filtered_spec_idxs
std::vector<int> Mantid::DataHandling::LoadNexusProcessed::m_filtered_spec_idxs private
list of spectra filtered by min/max/list, currently used only when loading data into event_workspace
Definition at line 201 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), and loadEventEntry().
m_interval
bool Mantid::DataHandling::LoadNexusProcessed::m_interval private
Flag set if interval of spectra to write is set.
Definition at line 190 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), and loadNonEventEntry().
m_list
bool Mantid::DataHandling::LoadNexusProcessed::m_list private
Flag set if list of spectra to save is specifed.
Definition at line 188 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), exec(), loadNonEventEntry(), and readInstrumentGroup().
m_nexusFile
std::unique_ptr<::NeXus::File> Mantid::DataHandling::LoadNexusProcessed::m_nexusFile private
Definition at line 204 of file LoadNexusProcessed.h.
Referenced by doAccelleratedMultiPeriodLoading(), exec(), loadEntry(), loadLeanElasticPeaksEntry(), and loadPeaksEntry().
m_shared_bins
bool Mantid::DataHandling::LoadNexusProcessed::m_shared_bins private
Does the current workspace have uniform binning.
Definition at line 181 of file LoadNexusProcessed.h.
Referenced by loadEntry(), loadEventEntry(), and loadNonEventEntry().
m_spec_list
std::vector<int> Mantid::DataHandling::LoadNexusProcessed::m_spec_list private
The value of the spectrum_list property.
Definition at line 198 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), loadNonEventEntry(), and readInstrumentGroup().
m_spec_max
int Mantid::DataHandling::LoadNexusProcessed::m_spec_max private
The value of the spectrum_max property.
Definition at line 195 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), doAccelleratedMultiPeriodLoading(), loadNonEventEntry(), and readInstrumentGroup().
m_spec_min
int Mantid::DataHandling::LoadNexusProcessed::m_spec_min private
The value of the spectrum_min property.
Definition at line 193 of file LoadNexusProcessed.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), doAccelleratedMultiPeriodLoading(), loadNonEventEntry(), and readInstrumentGroup().
m_xbins
HistogramData::BinEdges Mantid::DataHandling::LoadNexusProcessed::m_xbins private
The cached x binning if we have bins.
Definition at line 183 of file LoadNexusProcessed.h.
Referenced by loadBlock(), loadEntry(), and loadEventEntry().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
Framework/DataHandling/src/LoadNexusProcessed.cpp