Mantid: MantidQt::MantidWidgets::FitScriptGeneratorModel Class Reference
MantidQt::MantidWidgets::FitScriptGeneratorModel Class Reference
This class stores the domain and fit data to be fitted to.
#include <FitScriptGeneratorModel.h>
Public Member Functions
void addFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function) override
void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) override
FitScriptGeneratorModel ()
FitScriptGeneratorModel (FitScriptGeneratorModel const &model)=delete
std::string generatePythonFitScript (std::tuple< std::string, std::string, std::string, std::string, std::string, bool > const &fitOptions, std::string const &filepath="") override
std::string getAdjustedFunctionIndex (std::string const &parameter) const override
std::string getDomainName (FitDomainIndex domainIndex) const override
std::string getEquivalentFunctionIndexForDomain (FitDomainIndex domainIndex, std::string const &functionIndex) const override
std::string getEquivalentFunctionIndexForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex) const override
std::string getEquivalentParameterTieForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &fullTie) const override
FittingMode getFittingMode () const noexcept override
std::string getFullParameter (FitDomainIndex domainIndex, std::string const &parameter) const override
std::string getFullTie (FitDomainIndex domainIndex, std::string const &tie) const override
Mantid::API::IFunction_sptr getFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const override
std::vector< GlobalParameter > getGlobalParameters () const noexcept override
std::vector< GlobalTie > getGlobalTies () const noexcept override
std::string getParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter) const override
std::string getParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter) const override
double getParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter) const override
bool hasParameter (FitDomainIndex domainIndex, std::string const &fullParameter) const override
bool hasWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const override
bool isParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter) const override
bool isSimultaneousMode () const override
std::tuple< bool, std::string > isValid () const override
std::size_t numberOfDomains () const noexcept override
FitScriptGeneratorModel & operator= (FitScriptGeneratorModel const &model)=delete
void removeDomain (FitDomainIndex domainIndex) override
void removeFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function) override
void removeParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter) override
void renameWorkspace (std::string const &workspaceName, std::string const &newName) override
void setFittingMode (FittingMode fittingMode) override
void setFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function) override
void setGlobalParameters (std::vector< std::string > const &parameters) override
void setOutputBaseName (std::string const &outputBaseName) override
void setParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &constraint) override
void setParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter, bool fix) override
void setParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &tie) override
void setParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter, double value) override
void subscribePresenter (IFitScriptGeneratorPresenter *presenter) override
void updateAttributeValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullAttribute, Mantid::API::IFunction::Attribute const &newValue) override
bool updateEndX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double endX) override
void updateParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex, std::string const &constraint) override
void updateParameterTie (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &tie) override
void updateParameterValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, double newValue) override
bool updateStartX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX) override
~FitScriptGeneratorModel ()
Public Member Functions inherited from MantidQt::MantidWidgets::IFitScriptGeneratorModel
virtual void addFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX)=0
virtual std::string generatePythonFitScript (std::tuple< std::string, std::string, std::string, std::string, std::string, bool > const &fitOptions, std::string const &filepath="")=0
virtual std::string getAdjustedFunctionIndex (std::string const &parameter) const =0
virtual std::string getDomainName (FitDomainIndex domainIndex) const =0
virtual std::string getEquivalentFunctionIndexForDomain (FitDomainIndex domainIndex, std::string const &functionIndex) const =0
virtual std::string getEquivalentFunctionIndexForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex) const =0
virtual std::string getEquivalentParameterTieForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &fullTie) const =0
virtual FittingMode getFittingMode () const =0
virtual std::string getFullParameter (FitDomainIndex domainIndex, std::string const &parameter) const =0
virtual std::string getFullTie (FitDomainIndex domainIndex, std::string const &tie) const =0
virtual Mantid::API::IFunction_sptr getFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const =0
virtual std::vector< GlobalParameter > getGlobalParameters () const =0
virtual std::vector< GlobalTie > getGlobalTies () const =0
virtual std::string getParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual std::string getParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual double getParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool hasParameter (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool hasWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const =0
virtual bool isParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool isSimultaneousMode () const =0
virtual std::tuple< bool, std::string > isValid () const =0
virtual std::size_t numberOfDomains () const =0
virtual void removeDomain (FitDomainIndex domainIndex)=0
virtual void removeFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void removeParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter)=0
virtual void renameWorkspace (std::string const &workspaceName, std::string const &newName)=0
virtual void setFittingMode (FittingMode fittingMode)=0
virtual void setFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void setGlobalParameters (std::vector< std::string > const &parameters)=0
virtual void setOutputBaseName (std::string const &outputBaseName)=0
virtual void setParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &constraint)=0
virtual void setParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter, bool fix)=0
virtual void setParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &tie)=0
virtual void setParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter, double value)=0
virtual void subscribePresenter (IFitScriptGeneratorPresenter *presenter)=0
virtual void updateAttributeValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullAttribute, Mantid::API::IFunction::Attribute const &newValue)=0
virtual bool updateEndX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double endX)=0
virtual void updateParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex, std::string const &constraint)=0
virtual void updateParameterTie (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &tie)=0
virtual void updateParameterValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, double newValue)=0
virtual bool updateStartX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX)=0
virtual ~IFitScriptGeneratorModel ()=default
Private Member Functions
void addGlobalParameterTies (Mantid::API::MultiDomainFunction_sptr &function) const
void addGlobalTies (Mantid::API::MultiDomainFunction_sptr &function) const
bool checkFunctionExistsInAllDomains () const
bool checkFunctionIsSameForAllDomains () const
void checkGlobalParameterhasNoTies (std::string const &globalParameter) const
void checkGlobalTies ()
void checkParameterIsInAllDomains (std::string const &globalParameter) const
void checkParameterIsNotGlobal (std::string const &fullParameter) const
void clearGlobalTie (std::string const &fullParameter)
std::string constructGlobalParameterTie (GlobalParameter const &globalParameter) const
FitDomainIndex findDomainIndex (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const
std::vector< GlobalTie >::const_iterator findGlobalTie (std::string const &fullParameter) const
std::vector< std::unique_ptr< FitDomain > >::const_iterator findWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const
std::string generatePermissibleWarnings () const
std::vector< double > getEndXs () const
std::string getEquivalentParameterTieForDomain (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &fullTie) const
std::string getFittingType () const
Mantid::API::IFunction_sptr getFunction () const
std::vector< std::string > getInputWorkspaces () const
Mantid::API::IFunction_sptr getMultiDomainFunction () const
template<typename Getter >
auto getParameterProperty (Getter &&func, FitDomainIndex domainIndex, std::string const &fullParameter) const
std::vector< double > getStartXs () const
std::vector< std::size_t > getWorkspaceIndices () const
bool hasGlobalTie (std::string const &fullParameter) const
bool isParameterValueWithinConstraints (FitDomainIndex domainIndex, std::string const &fullParameter, double value) const
template<typename T , typename Function >
std::vector< T > transformDomains (Function const &func) const
void tryToAdjustParameterInGlobalTieIfInvalidated (GlobalTie &globalTie)
void tryToAdjustTieInGlobalTieIfInvalidated (GlobalTie &globalTie)
void updateGlobalParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &fullTie)
void updateLocalParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &fullTie)
void updateParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &fullTie)
void updateParameterValueInGlobalTie (GlobalTie const &globalTie, double newValue)
void updateParameterValuesWithGlobalTieTo (std::string const &fullParameter, double newValue)
void updateParameterValuesWithLocalTieTo (FitDomainIndex domainIndex, std::string const &parameter, double newValue)
bool validGlobalTie (std::string const &fullParameter, std::string const &fullTie) const
bool validParameter (FitDomainIndex domainIndex, std::string const &fullParameter) const
bool validParameter (std::string const &fullParameter) const
bool validTie (std::string const &fullTie) const
Private Attributes
std::vector< std::unique_ptr< FitDomain > > m_fitDomains
FittingMode m_fittingMode
std::vector< GlobalParameter > m_globalParameters
std::vector< GlobalTie > m_globalTies
std::string m_outputBaseName
IFitScriptGeneratorPresenter * m_presenter
Detailed Description
This class stores the domain and fit data to be fitted to.
This data is used to generate a python script for complex Mantid fitting.
Definition at line 34 of file FitScriptGeneratorModel.h.
Constructor & Destructor Documentation
FitScriptGeneratorModel() [1/2]
MantidQt::MantidWidgets::FitScriptGeneratorModel::FitScriptGeneratorModel ()
Definition at line 91 of file FitScriptGeneratorModel.cpp.
FitScriptGeneratorModel() [2/2]
MantidQt::MantidWidgets::FitScriptGeneratorModel::FitScriptGeneratorModel (FitScriptGeneratorModel const & model) delete
~FitScriptGeneratorModel()
MantidQt::MantidWidgets::FitScriptGeneratorModel::~FitScriptGeneratorModel ()
Definition at line 95 of file FitScriptGeneratorModel.cpp.
References m_fitDomains, m_globalParameters, and m_globalTies.
Member Function Documentation
addFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::addFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 172 of file FitScriptGeneratorModel.cpp.
References checkGlobalTies(), findDomainIndex(), and m_fitDomains.
addGlobalParameterTies()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::addGlobalParameterTies (Mantid::API::MultiDomainFunction_sptr & function) const private
Definition at line 738 of file FitScriptGeneratorModel.cpp.
References constructGlobalParameterTie(), and m_globalParameters.
Referenced by getMultiDomainFunction().
addGlobalTies()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::addGlobalTies (Mantid::API::MultiDomainFunction_sptr & function) const private
Definition at line 750 of file FitScriptGeneratorModel.cpp.
References m_globalTies.
Referenced by getMultiDomainFunction().
addWorkspaceDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::addWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 114 of file FitScriptGeneratorModel.cpp.
References hasWorkspaceDomain(), m_fitDomains, std::to_string(), and MantidQt::MantidWidgets::IndexType< Class >::value.
checkFunctionExistsInAllDomains()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::checkFunctionExistsInAllDomains () const private
Definition at line 605 of file FitScriptGeneratorModel.cpp.
References m_fitDomains.
Referenced by isValid().
checkFunctionIsSameForAllDomains()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::checkFunctionIsSameForAllDomains () const private
Definition at line 610 of file FitScriptGeneratorModel.cpp.
References m_fitDomains, and numberOfDomains().
Referenced by generatePermissibleWarnings().
checkGlobalParameterhasNoTies()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::checkGlobalParameterhasNoTies (std::string const & globalParameter) const private
Definition at line 579 of file FitScriptGeneratorModel.cpp.
References hasGlobalTie(), m_fitDomains, and m_globalTies.
Referenced by setGlobalParameters().
checkGlobalTies()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::checkGlobalTies () private
Definition at line 420 of file FitScriptGeneratorModel.cpp.
References m_globalTies, m_presenter, MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalTies(), tryToAdjustParameterInGlobalTieIfInvalidated(), tryToAdjustTieInGlobalTieIfInvalidated(), validGlobalTie(), and validParameter().
Referenced by addFunction(), removeDomain(), removeFunction(), and setFunction().
checkParameterIsInAllDomains()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::checkParameterIsInAllDomains (std::string const & globalParameter) const private
Definition at line 570 of file FitScriptGeneratorModel.cpp.
References hasParameter(), and m_fitDomains.
Referenced by setGlobalParameters().
checkParameterIsNotGlobal()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::checkParameterIsNotGlobal (std::string const & fullParameter) const private
Definition at line 594 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), and m_globalParameters.
Referenced by updateParameterTie().
clearGlobalTie()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::clearGlobalTie (std::string const & fullParameter) private
Definition at line 412 of file FitScriptGeneratorModel.cpp.
References findGlobalTie(), m_globalTies, m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalTies().
Referenced by updateGlobalParameterTie(), updateLocalParameterTie(), and updateParameterValueInGlobalTie().
constructGlobalParameterTie()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::constructGlobalParameterTie (GlobalParameter const & globalParameter) const private
Definition at line 743 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::GlobalParameter::m_parameter, numberOfDomains(), and std::to_string().
Referenced by addGlobalParameterTies().
findDomainIndex()
FitDomainIndex MantidQt::MantidWidgets::FitScriptGeneratorModel::findDomainIndex (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const private
Definition at line 135 of file FitScriptGeneratorModel.cpp.
References findWorkspaceDomain(), m_fitDomains, std::to_string(), and MantidQt::MantidWidgets::IndexType< Class >::value.
Referenced by addFunction(), getEquivalentFunctionIndexForDomain(), getEquivalentParameterTieForDomain(), getFunction(), removeFunction(), removeParameterConstraint(), setFunction(), updateAttributeValue(), updateEndX(), updateParameterConstraint(), updateParameterTie(), updateParameterValue(), and updateStartX().
findGlobalTie()
std::vector< GlobalTie >::const_iterator MantidQt::MantidWidgets::FitScriptGeneratorModel::findGlobalTie (std::string const & fullParameter) const private
Definition at line 466 of file FitScriptGeneratorModel.cpp.
References m_globalTies.
Referenced by clearGlobalTie(), and hasGlobalTie().
findWorkspaceDomain()
std::vector< std::unique_ptr< FitDomain > >::const_iterator MantidQt::MantidWidgets::FitScriptGeneratorModel::findWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const private
Definition at line 146 of file FitScriptGeneratorModel.cpp.
References m_fitDomains.
Referenced by findDomainIndex(), and hasWorkspaceDomain().
generatePermissibleWarnings()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::generatePermissibleWarnings () const private
Definition at line 639 of file FitScriptGeneratorModel.cpp.
References checkFunctionIsSameForAllDomains(), m_fittingMode, and MantidQt::MantidWidgets::SEQUENTIAL.
Referenced by isValid().
generatePythonFitScript()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::generatePythonFitScript (std::tuple< std::string, std::string, std::string, std::string, std::string, bool > const & fitOptions, std::string const & filepath = "") override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 648 of file FitScriptGeneratorModel.cpp.
References getEndXs(), getFittingType(), getFunction(), getInputWorkspaces(), getStartXs(), getWorkspaceIndices(), and Mantid::Kernel::SingletonHolder< T >::Instance().
getAdjustedFunctionIndex()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getAdjustedFunctionIndex (std::string const & parameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 233 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::isNumber(), m_fittingMode, and MantidQt::MantidWidgets::SEQUENTIAL.
Referenced by checkParameterIsNotGlobal(), getParameterProperty(), isParameterValueWithinConstraints(), removeParameterConstraint(), setParameterConstraint(), setParameterFixed(), setParameterValue(), updateAttributeValue(), updateGlobalParameterTie(), updateLocalParameterTie(), updateParameterConstraint(), updateParameterValue(), updateParameterValueInGlobalTie(), and validParameter().
getDomainName()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getDomainName (FitDomainIndex domainIndex) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 499 of file FitScriptGeneratorModel.cpp.
References m_fitDomains, numberOfDomains(), and MantidQt::MantidWidgets::IndexType< Class >::value.
getEndXs()
std::vector< double > MantidQt::MantidWidgets::FitScriptGeneratorModel::getEndXs () const private
Definition at line 690 of file FitScriptGeneratorModel.cpp.
Referenced by generatePythonFitScript().
getEquivalentFunctionIndexForDomain() [1/2]
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentFunctionIndexForDomain (FitDomainIndex domainIndex, std::string const & functionIndex) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 199 of file FitScriptGeneratorModel.cpp.
References m_fittingMode, numberOfDomains(), MantidQt::MantidWidgets::SIMULTANEOUS, and MantidQt::MantidWidgets::IndexType< Class >::value.
getEquivalentFunctionIndexForDomain() [2/2]
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentFunctionIndexForDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & functionIndex) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 192 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), and getEquivalentFunctionIndexForDomain().
Referenced by getEquivalentFunctionIndexForDomain().
getEquivalentParameterTieForDomain() [1/2]
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentParameterTieForDomain (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & fullTie) const private
Definition at line 223 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::getFunctionIndexAt(), and MantidQt::MantidWidgets::IndexType< Class >::value.
getEquivalentParameterTieForDomain() [2/2]
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentParameterTieForDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, std::string const & fullTie) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 209 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), getEquivalentParameterTieForDomain(), MantidQt::MantidWidgets::isNumber(), m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, and validTie().
Referenced by getEquivalentParameterTieForDomain().
getFittingMode()
FittingMode MantidQt::MantidWidgets::FitScriptGeneratorModel::getFittingMode () const inline override virtual noexcept
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 100 of file FitScriptGeneratorModel.h.
getFittingType()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getFittingType () const private
Definition at line 703 of file FitScriptGeneratorModel.cpp.
References m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, and MantidQt::MantidWidgets::SIMULTANEOUS.
Referenced by generatePythonFitScript().
getFullParameter()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getFullParameter (FitDomainIndex domainIndex, std::string const & parameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 242 of file FitScriptGeneratorModel.cpp.
References m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, std::to_string(), and MantidQt::MantidWidgets::IndexType< Class >::value.
Referenced by getFullTie().
getFullTie()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getFullTie (FitDomainIndex domainIndex, std::string const & tie) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 248 of file FitScriptGeneratorModel.cpp.
References getFullParameter(), and MantidQt::MantidWidgets::isNumber().
Referenced by setParameterTie().
getFunction() [1/2]
IFunction_sptr MantidQt::MantidWidgets::FitScriptGeneratorModel::getFunction () const private
Definition at line 714 of file FitScriptGeneratorModel.cpp.
References getMultiDomainFunction(), m_fitDomains, m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, and MantidQt::MantidWidgets::SIMULTANEOUS.
Referenced by generatePythonFitScript().
getFunction() [2/2]
IFunction_sptr MantidQt::MantidWidgets::FitScriptGeneratorModel::getFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 186 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), and m_fitDomains.
getGlobalParameters()
std::vector< GlobalParameter > MantidQt::MantidWidgets::FitScriptGeneratorModel::getGlobalParameters () const inline override virtual noexcept
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 93 of file FitScriptGeneratorModel.h.
getGlobalTies()
std::vector< GlobalTie > MantidQt::MantidWidgets::FitScriptGeneratorModel::getGlobalTies () const inline override virtual noexcept
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 89 of file FitScriptGeneratorModel.h.
getInputWorkspaces()
std::vector< std::string > MantidQt::MantidWidgets::FitScriptGeneratorModel::getInputWorkspaces () const private
Definition at line 675 of file FitScriptGeneratorModel.cpp.
Referenced by generatePythonFitScript().
getMultiDomainFunction()
IFunction_sptr MantidQt::MantidWidgets::FitScriptGeneratorModel::getMultiDomainFunction () const private
Definition at line 725 of file FitScriptGeneratorModel.cpp.
References addGlobalParameterTies(), addGlobalTies(), m_fitDomains, and numberOfDomains().
Referenced by getFunction().
getParameterConstraint()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getParameterConstraint (FitDomainIndex domainIndex, std::string const & fullParameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 565 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::FitDomain::getParameterConstraint(), and getParameterProperty().
getParameterProperty()
template<typename Getter > auto MantidQt::MantidWidgets::FitScriptGeneratorModel::getParameterProperty (Getter && func, FitDomainIndex domainIndex, std::string const & fullParameter) const private
Definition at line 201 of file FitScriptGeneratorModel.h.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), and MantidQt::MantidWidgets::IndexType< Class >::value.
Referenced by getParameterConstraint(), getParameterTie(), getParameterValue(), hasParameter(), and isParameterFixed().
getParameterTie()
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::getParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 560 of file FitScriptGeneratorModel.cpp.
References getParameterProperty(), and MantidQt::MantidWidgets::FitDomain::getParameterTie().
getParameterValue()
double MantidQt::MantidWidgets::FitScriptGeneratorModel::getParameterValue (FitDomainIndex domainIndex, std::string const & fullParameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 552 of file FitScriptGeneratorModel.cpp.
References getParameterProperty(), and MantidQt::MantidWidgets::FitDomain::getParameterValue().
Referenced by updateGlobalParameterTie(), and validGlobalTie().
getStartXs()
std::vector< double > MantidQt::MantidWidgets::FitScriptGeneratorModel::getStartXs () const private
Definition at line 685 of file FitScriptGeneratorModel.cpp.
Referenced by generatePythonFitScript().
getWorkspaceIndices()
std::vector< std::size_t > MantidQt::MantidWidgets::FitScriptGeneratorModel::getWorkspaceIndices () const private
Definition at line 680 of file FitScriptGeneratorModel.cpp.
Referenced by generatePythonFitScript().
hasGlobalTie()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::hasGlobalTie (std::string const & fullParameter) const private
Definition at line 462 of file FitScriptGeneratorModel.cpp.
References findGlobalTie(), and m_globalTies.
Referenced by checkGlobalParameterhasNoTies(), and updateParameterValue().
hasParameter()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::hasParameter (FitDomainIndex domainIndex, std::string const & fullParameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 506 of file FitScriptGeneratorModel.cpp.
References getParameterProperty(), and MantidQt::MantidWidgets::FitDomain::hasParameter().
Referenced by checkParameterIsInAllDomains().
hasWorkspaceDomain()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::hasWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 123 of file FitScriptGeneratorModel.cpp.
References findWorkspaceDomain(), and m_fitDomains.
Referenced by addWorkspaceDomain().
isParameterFixed()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::isParameterFixed (FitDomainIndex domainIndex, std::string const & fullParameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 556 of file FitScriptGeneratorModel.cpp.
References getParameterProperty(), and MantidQt::MantidWidgets::FitDomain::isParameterFixed().
isParameterValueWithinConstraints()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::isParameterValueWithinConstraints (FitDomainIndex domainIndex, std::string const & fullParameter, double value) const private
Definition at line 403 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), value, and MantidQt::MantidWidgets::IndexType< Class >::value.
Referenced by validGlobalTie().
isSimultaneousMode()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::isSimultaneousMode () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 497 of file FitScriptGeneratorModel.cpp.
References m_fittingMode, and MantidQt::MantidWidgets::SIMULTANEOUS.
isValid()
std::tuple< bool, std::string > MantidQt::MantidWidgets::FitScriptGeneratorModel::isValid () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 622 of file FitScriptGeneratorModel.cpp.
References checkFunctionExistsInAllDomains(), generatePermissibleWarnings(), m_outputBaseName, and numberOfDomains().
numberOfDomains()
std::size_t MantidQt::MantidWidgets::FitScriptGeneratorModel::numberOfDomains () const inline override virtual noexcept
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 120 of file FitScriptGeneratorModel.h.
Referenced by checkFunctionIsSameForAllDomains(), constructGlobalParameterTie(), getDomainName(), getEquivalentFunctionIndexForDomain(), getMultiDomainFunction(), getParameterProperty(), isParameterValueWithinConstraints(), isValid(), setParameterConstraint(), setParameterFixed(), setParameterTie(), setParameterValue(), transformDomains(), and validParameter().
operator=()
FitScriptGeneratorModel & MantidQt::MantidWidgets::FitScriptGeneratorModel::operator= (FitScriptGeneratorModel const & model) delete
References Mantid::API::renameWorkspace().
removeDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::removeDomain (FitDomainIndex domainIndex) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 103 of file FitScriptGeneratorModel.cpp.
References checkGlobalTies(), m_fitDomains, and MantidQt::MantidWidgets::IndexType< Class >::value.
removeFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::removeFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 165 of file FitScriptGeneratorModel.cpp.
References checkGlobalTies(), findDomainIndex(), and m_fitDomains.
removeParameterConstraint()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::removeParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 352 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), getAdjustedFunctionIndex(), and m_fitDomains.
renameWorkspace()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::renameWorkspace (std::string const & workspaceName, std::string const & newName) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 128 of file FitScriptGeneratorModel.cpp.
References m_fitDomains.
setFittingMode()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setFittingMode (FittingMode fittingMode) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 486 of file FitScriptGeneratorModel.cpp.
References m_fittingMode, m_globalParameters, m_globalTies, m_presenter, MantidQt::MantidWidgets::SEQUENTIAL_AND_SIMULTANEOUS, MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalParameters(), and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalTies().
setFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 179 of file FitScriptGeneratorModel.cpp.
References checkGlobalTies(), findDomainIndex(), and m_fitDomains.
setGlobalParameters()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setGlobalParameters (std::vector< std::string > const & parameters) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 471 of file FitScriptGeneratorModel.cpp.
References checkGlobalParameterhasNoTies(), checkParameterIsInAllDomains(), and m_globalParameters.
setOutputBaseName()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setOutputBaseName (std::string const & outputBaseName) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 482 of file FitScriptGeneratorModel.cpp.
References m_outputBaseName.
setParameterConstraint()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setParameterConstraint (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & constraint) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 538 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), and MantidQt::MantidWidgets::IndexType< Class >::value.
setParameterFixed()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setParameterFixed (FitDomainIndex domainIndex, std::string const & fullParameter, bool fix) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 519 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), and MantidQt::MantidWidgets::IndexType< Class >::value.
setParameterTie()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & tie) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 528 of file FitScriptGeneratorModel.cpp.
References getFullTie(), numberOfDomains(), updateParameterTie(), validTie(), and MantidQt::MantidWidgets::IndexType< Class >::value.
setParameterValue()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::setParameterValue (FitDomainIndex domainIndex, std::string const & fullParameter, double value) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 510 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), value, and MantidQt::MantidWidgets::IndexType< Class >::value.
subscribePresenter()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::subscribePresenter (IFitScriptGeneratorPresenter * presenter) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 101 of file FitScriptGeneratorModel.cpp.
References m_presenter.
Referenced by MockFitScriptGeneratorPresenter::MockFitScriptGeneratorPresenter().
transformDomains()
template<typename T , typename Function > std::vector< T > MantidQt::MantidWidgets::FitScriptGeneratorModel::transformDomains (Function const & func) const private
Definition at line 696 of file FitScriptGeneratorModel.cpp.
References m_fitDomains, and numberOfDomains().
tryToAdjustParameterInGlobalTieIfInvalidated()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustParameterInGlobalTieIfInvalidated (GlobalTie & globalTie) private
Definition at line 436 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::GlobalTie::m_parameter, MantidQt::MantidWidgets::GlobalTie::toCompositeParameter(), MantidQt::MantidWidgets::GlobalTie::toNonCompositeParameter(), and validParameter().
Referenced by checkGlobalTies().
tryToAdjustTieInGlobalTieIfInvalidated()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustTieInGlobalTieIfInvalidated (GlobalTie & globalTie) private
Definition at line 449 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::GlobalTie::m_parameter, MantidQt::MantidWidgets::GlobalTie::m_tie, MantidQt::MantidWidgets::GlobalTie::toCompositeParameter(), MantidQt::MantidWidgets::GlobalTie::toNonCompositeParameter(), and validGlobalTie().
Referenced by checkGlobalTies().
updateAttributeValue()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateAttributeValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullAttribute, Mantid::API::IFunction::Attribute const & newValue) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 293 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), getAdjustedFunctionIndex(), and m_fitDomains.
updateEndX()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::updateEndX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double endX) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 160 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), and m_fitDomains.
updateGlobalParameterTie()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateGlobalParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & fullTie) private
Definition at line 333 of file FitScriptGeneratorModel.cpp.
References clearGlobalTie(), Mantid::API::g_log, getAdjustedFunctionIndex(), getParameterValue(), m_fitDomains, m_globalTies, validGlobalTie(), validParameter(), MantidQt::MantidWidgets::IndexType< Class >::value, and Mantid::Kernel::Logger::warning().
Referenced by updateParameterTie().
updateLocalParameterTie()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateLocalParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & fullTie) private
Definition at line 320 of file FitScriptGeneratorModel.cpp.
References clearGlobalTie(), Mantid::API::g_log, getAdjustedFunctionIndex(), m_fitDomains, m_fittingMode, validParameter(), MantidQt::MantidWidgets::IndexType< Class >::value, and Mantid::Kernel::Logger::warning().
Referenced by updateParameterTie().
updateParameterConstraint()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & functionIndex, std::string const & constraint) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 358 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), getAdjustedFunctionIndex(), and m_fitDomains.
updateParameterTie() [1/2]
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & fullTie) private
Definition at line 310 of file FitScriptGeneratorModel.cpp.
References checkParameterIsNotGlobal(), m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, updateGlobalParameterTie(), updateLocalParameterTie(), and MantidQt::MantidWidgets::IndexType< Class >::value.
updateParameterTie() [2/2]
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterTie (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, std::string const & tie) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 300 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), Mantid::API::g_log, updateParameterTie(), validTie(), and Mantid::Kernel::Logger::warning().
Referenced by setParameterTie(), and updateParameterTie().
updateParameterValue()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, double newValue) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 254 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), getAdjustedFunctionIndex(), hasGlobalTie(), m_fitDomains, m_fittingMode, MantidQt::MantidWidgets::SIMULTANEOUS, updateParameterValuesWithGlobalTieTo(), and updateParameterValuesWithLocalTieTo().
updateParameterValueInGlobalTie()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValueInGlobalTie (GlobalTie const & globalTie, double newValue) private
Definition at line 284 of file FitScriptGeneratorModel.cpp.
References clearGlobalTie(), getAdjustedFunctionIndex(), MantidQt::MantidWidgets::getFunctionIndexAt(), m_fitDomains, MantidQt::MantidWidgets::GlobalTie::m_parameter, MantidQt::MantidWidgets::GlobalTie::m_tie, and validGlobalTie().
Referenced by updateParameterValuesWithGlobalTieTo().
updateParameterValuesWithGlobalTieTo()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValuesWithGlobalTieTo (std::string const & fullParameter, double newValue) private
Definition at line 275 of file FitScriptGeneratorModel.cpp.
References m_globalTies, and updateParameterValueInGlobalTie().
Referenced by updateParameterValue().
updateParameterValuesWithLocalTieTo()
void MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValuesWithLocalTieTo (FitDomainIndex domainIndex, std::string const & parameter, double newValue) private
Definition at line 268 of file FitScriptGeneratorModel.cpp.
References m_fitDomains, and MantidQt::MantidWidgets::IndexType< Class >::value.
Referenced by updateParameterValue().
updateStartX()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::updateStartX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorModel.
Definition at line 154 of file FitScriptGeneratorModel.cpp.
References findDomainIndex(), and m_fitDomains.
validGlobalTie()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::validGlobalTie (std::string const & fullParameter, std::string const & fullTie) const private
Definition at line 394 of file FitScriptGeneratorModel.cpp.
References getParameterValue(), MantidQt::MantidWidgets::isNumber(), isParameterValueWithinConstraints(), and validParameter().
Referenced by checkGlobalTies(), tryToAdjustTieInGlobalTieIfInvalidated(), updateGlobalParameterTie(), and updateParameterValueInGlobalTie().
validParameter() [1/2]
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::validParameter (FitDomainIndex domainIndex, std::string const & fullParameter) const private
Definition at line 371 of file FitScriptGeneratorModel.cpp.
References getAdjustedFunctionIndex(), m_fitDomains, numberOfDomains(), and MantidQt::MantidWidgets::IndexType< Class >::value.
validParameter() [2/2]
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::validParameter (std::string const & fullParameter) const private
Definition at line 367 of file FitScriptGeneratorModel.cpp.
References validParameter().
Referenced by checkGlobalTies(), tryToAdjustParameterInGlobalTieIfInvalidated(), updateGlobalParameterTie(), updateLocalParameterTie(), validGlobalTie(), and validParameter().
validTie()
bool MantidQt::MantidWidgets::FitScriptGeneratorModel::validTie (std::string const & fullTie) const private
Definition at line 379 of file FitScriptGeneratorModel.cpp.
References MantidQt::MantidWidgets::isNumber(), m_fittingMode, MantidQt::MantidWidgets::SEQUENTIAL, MantidQt::MantidWidgets::SIMULTANEOUS, and MantidQt::MantidWidgets::splitStringBy().
Referenced by getEquivalentParameterTieForDomain(), setParameterTie(), and updateParameterTie().
Member Data Documentation
m_fitDomains
std::vector<std::unique_ptr<FitDomain> > MantidQt::MantidWidgets::FitScriptGeneratorModel::m_fitDomains private
Definition at line 192 of file FitScriptGeneratorModel.h.
Referenced by addFunction(), addWorkspaceDomain(), checkFunctionExistsInAllDomains(), checkFunctionIsSameForAllDomains(), checkGlobalParameterhasNoTies(), checkParameterIsInAllDomains(), findDomainIndex(), findWorkspaceDomain(), getDomainName(), getFunction(), getMultiDomainFunction(), getParameterProperty(), hasWorkspaceDomain(), isParameterValueWithinConstraints(), removeDomain(), removeFunction(), removeParameterConstraint(), renameWorkspace(), setFunction(), setParameterConstraint(), setParameterFixed(), setParameterValue(), transformDomains(), updateAttributeValue(), updateEndX(), updateGlobalParameterTie(), updateLocalParameterTie(), updateParameterConstraint(), updateParameterValue(), updateParameterValueInGlobalTie(), updateParameterValuesWithLocalTieTo(), updateStartX(), validParameter(), and ~FitScriptGeneratorModel().
m_fittingMode
FittingMode MantidQt::MantidWidgets::FitScriptGeneratorModel::m_fittingMode private
Definition at line 197 of file FitScriptGeneratorModel.h.
Referenced by generatePermissibleWarnings(), getAdjustedFunctionIndex(), getEquivalentFunctionIndexForDomain(), getEquivalentParameterTieForDomain(), getFittingType(), getFullParameter(), getFunction(), isSimultaneousMode(), setFittingMode(), updateLocalParameterTie(), updateParameterTie(), updateParameterValue(), and validTie().
m_globalParameters
std::vector<GlobalParameter> MantidQt::MantidWidgets::FitScriptGeneratorModel::m_globalParameters private
Definition at line 194 of file FitScriptGeneratorModel.h.
Referenced by addGlobalParameterTies(), checkParameterIsNotGlobal(), setFittingMode(), setGlobalParameters(), and ~FitScriptGeneratorModel().
m_globalTies
std::vector<GlobalTie> MantidQt::MantidWidgets::FitScriptGeneratorModel::m_globalTies private
Definition at line 196 of file FitScriptGeneratorModel.h.
Referenced by addGlobalTies(), checkGlobalParameterhasNoTies(), checkGlobalTies(), clearGlobalTie(), findGlobalTie(), hasGlobalTie(), setFittingMode(), updateGlobalParameterTie(), updateParameterValuesWithGlobalTieTo(), and ~FitScriptGeneratorModel().
m_outputBaseName
std::string MantidQt::MantidWidgets::FitScriptGeneratorModel::m_outputBaseName private
Definition at line 191 of file FitScriptGeneratorModel.h.
Referenced by isValid(), and setOutputBaseName().
m_presenter
IFitScriptGeneratorPresenter* MantidQt::MantidWidgets::FitScriptGeneratorModel::m_presenter private
Definition at line 190 of file FitScriptGeneratorModel.h.
Referenced by checkGlobalTies(), clearGlobalTie(), setFittingMode(), and subscribePresenter().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorModel.h
qt/widgets/common/src/FitScriptGeneratorModel.cpp