Mantid: Mantid::Crystal::IntegratePeakTimeSlices Class Reference
Mantid::Crystal::IntegratePeakTimeSlices Class Reference
#include <IntegratePeakTimeSlices.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
IntegratePeakTimeSlices ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
~IntegratePeakTimeSlices () override
Destructor.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Public Member Functions inherited from Mantid::API::DeprecatedAlgorithm
DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
void deprecatedDate (const std::string &)
The date the algorithm was deprecated on.
std::string deprecationMsg (const IAlgorithm *)
This merely prints the deprecation error for people to see.
void useAlgorithm (const std::string &, const int version=-1)
The algorithm to use instead of this one.
virtual ~DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
Private Member Functions
std::string CalculateFunctionProperty_Fit ()
Calculates the string for the Function Property of the Fit Algorithm.
double CalculateIsawIntegrateError (const double background, const double backError, const double ChiSqOverDOF, const double TotVariance, const int ncells)
Calculates the error in integration closest to the latest ISAW calculations.
double CalculatePositionSpan (DataObjects::Peak const &peak, const double dQ)
Calculates the span in rows and columns needed to include all data within dQ of the specified peak.
int CalculateTimeChannelSpan (Geometry::IPeak const &peak, const double dQ, const Mantid::HistogramData::HistogramX &X, const int specNum, int &Centerchan)
Calculates the span of channels needed to encompass all data around the peak with Q values within dQ of this peak's Q value.
void exec () override
Executes this algorithm.
int findNameInVector (std::string const &oneName, std::vector< std::string > const &nameList)
Utility to find a name in a vector of strings.
void FindPlane (Kernel::V3D &center, Kernel::V3D &xvec, Kernel::V3D &yvec, double &ROW, double &COL, int &NROWS, int &NCOLS, double &pixWidthx, double &pixHeighty, DataObjects::Peak const &peak) const
For NonFlat banks, this determines the data of a small planar region approximating the instrument close to the peak.
int findTimeChannel (const Mantid::HistogramData::HistogramX &X, const double time)
Finds the time channel with the given time in.
void Fit (const API::MatrixWorkspace_sptr &Data, double &chisqOverDOF, bool &done, std::vector< std::string > &names, std::vector< double > &params, std::vector< double > &errs, double lastRow, double lastCol, double neighborRadius)
Sets up data for the Fit Algorithm call and invokes it.
bool getNeighborPixIDs (const std::shared_ptr< Geometry::IComponent > &comp, const Kernel::V3D &Center, double &Radius, int *&ArryofID)
Finds all neighbors within a given Radius of the Center on the given component.
void init () override
Virtual method - must be overridden by concrete algorithm.
void InitializeColumnNamesInTableWorkspace (DataObjects::TableWorkspace_sptr &TabWS)
Initializes the column names in the output table workspace.
bool isGoodFit (std::vector< double > const &params, std::vector< double > const &errs, std::vector< std::string > const &names, double chisqOverDOF)
Determines if the list of parameters and errors represent a "good" fit.
void PreFit (const API::MatrixWorkspace_sptr &Data, double &chisqOverDOF, bool &done, std::vector< std::string > &names, std::vector< double > &params, std::vector< double > &errs, double lastRow, double lastCol, double neighborRadius)
Tests several starting points in the Marquardt algorithm then calls Fit.
void SetUpData (API::MatrixWorkspace_sptr &Data, API::MatrixWorkspace_const_sptr const &inpWkSpace, const std::shared_ptr< Geometry::IComponent > &comp, const int chanMin, const int chanMax, double CentX, double CentY, Kernel::V3D &CentNghbr, double &neighborRadius, double Radius, std::string &spec_idList)
Initial phase at converting Detector data to workspace data that will be sent to the Fit Function, BivariateNormal.
void SetUpData1 (API::MatrixWorkspace_sptr &Data, API::MatrixWorkspace_const_sptr const &inpWkSpace, const int chanMin, const int chanMax, double Radius, const Kernel::V3D &CentPos, std::string &spec_idList)
Prepares the data for futher analysis adding meta data and marking data on the edges of detectors.
bool updateNeighbors (const std::shared_ptr< Geometry::IComponent > &comp, const Kernel::V3D &CentPos, const Kernel::V3D &oldCenter, double NewRadius, double &neighborRadius)
Checks and updates if needed the list of m_NeighborIDs.
int UpdateOutputWS (DataObjects::TableWorkspace_sptr &TabWS, const int dir, const double chan, std::vector< double > const &params, std::vector< double > const &errs, std::vector< std::string > const &names, const double Chisq, const double time, std::string spec_idList)
Updates the information in the output OutputWorkspace.
void updatePeakInformation (std::vector< double > const &params, std::vector< double > const &errs, std::vector< std::string > const &names, double &TotVariance, double &TotIntensity, double const TotSliceIntensity, double const TotSliceVariance, double const chisqdivDOF, const int ncells)
Updates m_AttributeValues with this peak information from this time slice.
void updateStats (const double intensity, const double variance, const double row, const double col, std::vector< double > &StatBase)
Updates the cumulative statistics for the data being considered.
Private Attributes
std::string m_AttributeNames [20]
std::shared_ptr< DataModeHandler > m_AttributeValues
double m_cellHeight
for Describing the Plane at the Peak
double m_cellWidth
Peak.
Kernel::V3D m_center
for Describing the Plane at the Peak
double m_COL
for Describing the Column(or 0) describing the center of the
bool m_EdgePeak
int m_NCOLS
int * m_NeighborIDs
int m_NROWS
std::string m_ParameterNames [7]
std::array< double, 7 > m_ParameterValues
double m_R0
for Weak Peaks, these can be set using info from close
double m_ROW
for Describing the Row(or 0) describing the center of the Peak
Mantid::detid2index_map m_wi_to_detid_map
Kernel::V3D m_xvec
for Describing the Plane at the Peak
Kernel::V3D m_yvec
for Describing the Plane at the Peak
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Definition at line 207 of file IntegratePeakTimeSlices.h.
Constructor & Destructor Documentation
IntegratePeakTimeSlices()
Mantid::Crystal::IntegratePeakTimeSlices::IntegratePeakTimeSlices ()
Default constructor.
Definition at line 96 of file IntegratePeakTimeSlices.cpp.
References Mantid::API::DeprecatedAlgorithm::deprecatedDate(), m_AttributeNames, m_EdgePeak, m_NeighborIDs, m_ParameterNames, and m_ParameterValues.
~IntegratePeakTimeSlices()
Mantid::Crystal::IntegratePeakTimeSlices::~IntegratePeakTimeSlices () override
Destructor.
Definition at line 141 of file IntegratePeakTimeSlices.cpp.
References m_NeighborIDs.
Member Function Documentation
CalculateFunctionProperty_Fit()
std::string Mantid::Crystal::IntegratePeakTimeSlices::CalculateFunctionProperty_Fit () private
Calculates the string for the Function Property of the Fit Algorithm.
Returns
the string for the Function Property of the Fit Algorithm
Definition at line 1606 of file IntegratePeakTimeSlices.cpp.
References m_AttributeValues, m_ParameterNames, m_ParameterValues, and NParameters.
Referenced by Fit().
CalculateIsawIntegrateError()
double Mantid::Crystal::IntegratePeakTimeSlices::CalculateIsawIntegrateError (const double background, const double backError, const double ChiSqOverDOF, const double TotVariance, const int ncells) private
Calculates the error in integration closest to the latest ISAW calculations.
Parameters
background The background
backError The error in this background value
ChiSqOverDOF The fitting error
TotVariance The Total square of the intensity errors in all the cells considered
ncells The number of cells
Returns
The error in the integrated intensity
Definition at line 2197 of file IntegratePeakTimeSlices.cpp.
References Mantid::Crystal::SQRT().
CalculatePositionSpan()
double Mantid::Crystal::IntegratePeakTimeSlices::CalculatePositionSpan (DataObjects::Peak const & peak, const double dQ) private
Calculates the span in rows and columns needed to include all data within dQ of the specified peak.
Parameters
peak The peak of interest
dQ The offset from the peak's Q value for the data of interest
NOTE: differentials of Q =mv*sin(scatAng/2)/2 were used to calculate this Also s=r*theta was used to transfer d ScatAng to distance on a bank.
Definition at line 701 of file IntegratePeakTimeSlices.cpp.
References fabs, Mantid::DataObjects::Peak::getDetPos(), Mantid::DataObjects::Peak::getInstrument(), Mantid::DataObjects::Peak::getQLabFrame(), Mantid::Kernel::V3D::norm(), and Mantid::Kernel::V3D::Z().
Referenced by exec().
CalculateTimeChannelSpan()
int Mantid::Crystal::IntegratePeakTimeSlices::CalculateTimeChannelSpan (Geometry::IPeak const & peak, const double dQ, const Mantid::HistogramData::HistogramX & X, const int specNum, int & Centerchan) private
Calculates the span of channels needed to encompass all data around the peak with Q values within dQ of this peak's Q value.
Parameters
peak The peak of interest
dQ The offset of peak's Q value whose data is considered part of the peak
X The list of time channel values.
specNum The spectral number for the pixel(Not Currently Used)
Centerchan The center time channel number(from X)
Returns
The number of time channels around Centerchan to use
Definition at line 743 of file IntegratePeakTimeSlices.cpp.
References findTimeChannel(), Mantid::Geometry::IPeak::getQLabFrame(), Mantid::Geometry::IPeak::getTOF(), Mantid::Kernel::V3D::norm(), UNUSED_ARG, and Mantid::Geometry::X.
Referenced by exec().
category()
const std::string Mantid::Crystal::IntegratePeakTimeSlices::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 229 of file IntegratePeakTimeSlices.h.
exec()
void Mantid::Crystal::IntegratePeakTimeSlices::exec () override private virtual
Executes this algorithm.
Integrates one peak -First attempts to find row/col extents, time extents to fully get most of the peak -Integrate each time slice. -Report Results
Implements Mantid::API::Algorithm.
Definition at line 177 of file IntegratePeakTimeSlices.cpp.
References CalculatePositionSpan(), CalculateTimeChannelSpan(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), findNameInVector(), FindPlane(), Mantid::API::Algorithm::g_log, Mantid::DataObjects::Peak::getBankName(), Mantid::DataObjects::Peak::getDetector(), Mantid::DataObjects::Peak::getDetectorID(), Mantid::DataObjects::Peak::getDetPos(), Mantid::DataObjects::Peak::getInstrument(), getNeighborPixIDs(), Mantid::API::Algorithm::getProperty(), IIntensities, InitializeColumnNamesInTableWorkspace(), Mantid::Kernel::SingletonHolder< T >::Instance(), isGoodFit(), Mantid::Geometry::BoundingBox::isPointInside(), ISS1, ISSIx, ISSIxx, ISSIy, ITINTENS, IVariance, m_AttributeValues, m_cellHeight, m_cellWidth, m_center, m_COL, m_NCOLS, m_NeighborIDs, m_NROWS, m_ParameterValues, m_R0, m_ROW, m_wi_to_detid_map, m_xvec, m_yvec, Mantid::Kernel::ProgressBase::report(), Mantid::Kernel::IPropertyManager::setProperty(), SetUpData(), SetUpData1(), Mantid::Crystal::SQRT(), updateNeighbors(), UpdateOutputWS(), updatePeakInformation(), and Mantid::Geometry::X.
findNameInVector()
int Mantid::Crystal::IntegratePeakTimeSlices::findNameInVector (std::string const & oneName, std::vector< std::string > const & nameList) private
Utility to find a name in a vector of strings.
Parameters
oneName The name to search for
nameList The list of names
Returns
the position in the vector of oneName or -1.
Definition at line 1636 of file IntegratePeakTimeSlices.cpp.
Referenced by exec(), isGoodFit(), PreFit(), and UpdateOutputWS().
FindPlane()
void Mantid::Crystal::IntegratePeakTimeSlices::FindPlane (Kernel::V3D & center, Kernel::V3D & xvec, Kernel::V3D & yvec, double & ROW, double & COL, int & NROWS, int & NCOLS, double & pixWidthx, double & pixHeighty, DataObjects::Peak const & peak) const private
For NonFlat banks, this determines the data of a small planar region approximating the instrument close to the peak.
Parameters
center The position of the center of this plane
xvec The direction the column values increase
yvec The direction the row values increase
ROW The row for this peak(0 if undefined)
COL The col for this peak(0 if undefined)
NROWS The number? of rows for this bANK
NCOLS The number of columns for this bank
pixWidthx The width of a pixel
pixHeighty The height of a pixel
peak
Definition at line 781 of file IntegratePeakTimeSlices.cpp.
References Mantid::DataObjects::Peak::getBankName(), Mantid::DataObjects::Peak::getCol(), Mantid::DataObjects::Peak::getDetector(), Mantid::DataObjects::Peak::getInstrument(), Mantid::Kernel::Quat::getRotation(), Mantid::DataObjects::Peak::getRow(), Mantid::Kernel::Quat::inverse(), Mantid::Kernel::V3D::normalize(), Mantid::Kernel::Quat::rotate(), Mantid::Kernel::V3D::setX(), Mantid::Kernel::V3D::setY(), Mantid::Kernel::V3D::setZ(), Mantid::Kernel::V3D::X(), Mantid::Geometry::BoundingBox::xMax(), Mantid::Geometry::BoundingBox::xMin(), Mantid::Kernel::V3D::Y(), Mantid::Geometry::BoundingBox::yMax(), Mantid::Geometry::BoundingBox::yMin(), and Mantid::Kernel::V3D::Z().
Referenced by exec().
findTimeChannel()
int Mantid::Crystal::IntegratePeakTimeSlices::findTimeChannel (const Mantid::HistogramData::HistogramX & X, const double time) private
Finds the time channel with the given time in.
Parameters
X The vector of time values from a MatrixWorkspace
time The desired time
Returns
the time channel
Definition at line 1555 of file IntegratePeakTimeSlices.cpp.
References Mantid::Geometry::X.
Referenced by CalculateTimeChannelSpan().
Fit()
void Mantid::Crystal::IntegratePeakTimeSlices::Fit (const API::MatrixWorkspace_sptr & Data, double & chisqOverDOF, bool & done, std::vector< std::string > & names, std::vector< double > & params, std::vector< double > & errs, double lastRow, double lastCol, double neighborRadius) private
Sets up data for the Fit Algorithm call and invokes it.
Parameters
Data The workspace with experimental results
chisqOverDOF the chi squared over degrees of freedom result from the Fit Algorithm
done Usually true except if there is not enough data or Fit Algorithm was not called
names The parameter names
params The parameter values from the Fit Algorithm
errs The parameter errorfrom the Fit Algorithm
lastRow The previous row(for log info only)
lastCol The previous col(for log info only)
neighborRadius The neighborhood radius(for log info only)
Definition at line 1833 of file IntegratePeakTimeSlices.cpp.
References CalculateFunctionProperty_Fit(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), error, Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), IBACK, IIntensities, ISS1, IVXX, IVXY, IVYY, IXMEAN, IYMEAN, m_AttributeValues, m_NeighborIDs, m_ParameterNames, and Mantid::Crystal::SQRT().
getNeighborPixIDs()
bool Mantid::Crystal::IntegratePeakTimeSlices::getNeighborPixIDs (const std::shared_ptr< Geometry::IComponent > & comp, const Kernel::V3D & Center, double & Radius, int *& ArryofID) private
Finds all neighbors within a given Radius of the Center on the given component.
Parameters
comp -The component of interest
Center- the center of the neighbors
Radius - The radius from the center of neighbors to be included
ArryofID -The detector ID's of the neighbors. The id of the pixel at the center may be included.
Definition at line 595 of file IntegratePeakTimeSlices.cpp.
References getNeighborPixIDs(), Mantid::Kernel::V3D::X(), Mantid::Geometry::BoundingBox::xMax(), Mantid::Geometry::BoundingBox::xMin(), Mantid::Kernel::V3D::Y(), Mantid::Geometry::BoundingBox::yMax(), Mantid::Geometry::BoundingBox::yMin(), Mantid::Kernel::V3D::Z(), Mantid::Geometry::BoundingBox::zMax(), and Mantid::Geometry::BoundingBox::zMin().
Referenced by exec(), getNeighborPixIDs(), SetUpData(), and updateNeighbors().
init()
void Mantid::Crystal::IntegratePeakTimeSlices::init () override private virtual
Virtual method - must be overridden by concrete algorithm.
Implements Mantid::API::Algorithm.
Definition at line 143 of file IntegratePeakTimeSlices.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, and Mantid::Kernel::Direction::Output.
InitializeColumnNamesInTableWorkspace()
void Mantid::Crystal::IntegratePeakTimeSlices::InitializeColumnNamesInTableWorkspace (DataObjects::TableWorkspace_sptr & TabWS) private
Initializes the column names in the output table workspace.
Parameters
TabWS The TableWorkspace
Definition at line 2215 of file IntegratePeakTimeSlices.cpp.
Referenced by exec().
isGoodFit()
bool Mantid::Crystal::IntegratePeakTimeSlices::isGoodFit (std::vector< double > const & params, std::vector< double > const & errs, std::vector< std::string > const & names, double chisqOverDOF) private
Determines if the list of parameters and errors represent a "good" fit.
Parameters
params The list of parameter values
errs The list of the errors in the parameter values
names The names of the parameters
chisqOverDOF The fitting error
Returns
true if the fit is good,otherwise false
Definition at line 2012 of file IntegratePeakTimeSlices.cpp.
References Mantid::Kernel::Logger::debug(), findNameInVector(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), IBACK, IIntensities, INCol, INRows, ISS1, ITINTENS, IVXX, IVXY, IVYY, IXMEAN, IYMEAN, m_AttributeValues, m_EdgePeak, m_NCOLS, m_NROWS, obj, and Mantid::Geometry::x.
Referenced by exec().
name()
const std::string Mantid::Crystal::IntegratePeakTimeSlices::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 216 of file IntegratePeakTimeSlices.h.
PreFit()
void Mantid::Crystal::IntegratePeakTimeSlices::PreFit (const API::MatrixWorkspace_sptr & Data, double & chisqOverDOF, bool & done, std::vector< std::string > & names, std::vector< double > & params, std::vector< double > & errs, double lastRow, double lastCol, double neighborRadius) private
Tests several starting points in the Marquardt algorithm then calls Fit.
Not used.
Did 3 Fit Algorithm calls and returned the one with the smallest chiSqOverDOF. Did not work well
Parameters
Data The workspace with experimental results
chisqOverDOF the chi squared over degrees of freedom result from the Fit Algorithm
done Usually true except if there is not enough data or Fit Algorithm was not called
names The parameter names
params The parameter values from the Fit Algorithm
errs The parameter errorfrom the Fit Algorithm
lastRow The previous row(for log info only)
lastCol The previous col(for log info only)
neighborRadius The neighborhood radius(for log info only)
Definition at line 1953 of file IntegratePeakTimeSlices.cpp.
References Mantid::Kernel::Logger::debug(), findNameInVector(), Mantid::API::Algorithm::g_log, IBACK, m_AttributeValues, m_ParameterNames, and m_ParameterValues.
seeAlso()
const std::vector< std::string > Mantid::Crystal::IntegratePeakTimeSlices::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 226 of file IntegratePeakTimeSlices.h.
SetUpData()
void Mantid::Crystal::IntegratePeakTimeSlices::SetUpData (API::MatrixWorkspace_sptr & Data, API::MatrixWorkspace_const_sptr const & inpWkSpace, const std::shared_ptr< Geometry::IComponent > & comp, const int chanMin, const int chanMax, double CentX, double CentY, Kernel::V3D & CentNghbr, double & neighborRadius, double Radius, std::string & spec_idList) private
Initial phase at converting Detector data to workspace data that will be sent to the Fit Function, BivariateNormal.
Parameters
Data -workspace that will be sent to the Fit Function, BivariateNormal
inpWkSpace -The MatrixWorkspace with all the experimental data
comp -The parent of all the pixels that are neighbors of the peak being considered
chanMin -The minimum channel to use
chanMax -The maximum channel to be collapsed to one channel
CentX -The current peak row
CentY -The current peak column
CentNghbr -The center of the current and next(if changed) neighbor pixels
neighborRadius -The radius of the current neighbor pixels
Radius -The current starting Radius to use for neighbors.
spec_idList -The list of spectral id's that are neighbors
Definition at line 1326 of file IntegratePeakTimeSlices.cpp.
References getNeighborPixIDs(), Mantid::API::Algorithm::getProperty(), ISSIxx, IXMEAN, IYMEAN, m_AttributeValues, m_cellHeight, m_cellWidth, m_center, m_COL, m_NCOLS, m_NeighborIDs, m_NROWS, m_ParameterValues, m_R0, m_ROW, m_xvec, m_yvec, SetUpData1(), and Mantid::Geometry::X.
Referenced by exec().
SetUpData1()
void Mantid::Crystal::IntegratePeakTimeSlices::SetUpData1 (API::MatrixWorkspace_sptr & Data, API::MatrixWorkspace_const_sptr const & inpWkSpace, const int chanMin, const int chanMax, double Radius, const Kernel::V3D & CentPos, std::string & spec_idList) private
Prepares the data for futher analysis adding meta data and marking data on the edges of detectors.
Parameters
Data Output workspace
inpWkSpace Input workspace
chanMin Minimum channel
chanMax Maximum channel. Will be collapsed to one channel
Radius The radius of detectors
CentPos Center on plane
spec_idList List of spectra id's
Definition at line 1401 of file IntegratePeakTimeSlices.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), IBACK, INBoundary, INCol, INRows, IStartCol, IStartRow, ITINTENS, ITotBoundary, IVarBoundary, IVXX, IVXY, IVYY, IXMEAN, IYMEAN, m_AttributeValues, m_cellHeight, m_cellWidth, m_COL, m_EdgePeak, m_NCOLS, m_NeighborIDs, m_NROWS, m_ParameterValues, m_ROW, m_wi_to_detid_map, m_xvec, m_yvec, NAttributes, Mantid::Kernel::V3D::scalar_prod(), sigma, std::to_string(), UNUSED_ARG, and updateStats().
Referenced by exec(), and SetUpData().
summary()
const std::string Mantid::Crystal::IntegratePeakTimeSlices::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 219 of file IntegratePeakTimeSlices.h.
updateNeighbors()
bool Mantid::Crystal::IntegratePeakTimeSlices::updateNeighbors (const std::shared_ptr< Geometry::IComponent > & comp, const Kernel::V3D & CentPos, const Kernel::V3D & oldCenter, double NewRadius, double & neighborRadius) private
Checks and updates if needed the list of m_NeighborIDs.
Parameters
comp Component with the neighboring pixels
CentPos new Center
oldCenter old Center
NewRadius new Radius
neighborRadius old the new neighborhood radius
Definition at line 667 of file IntegratePeakTimeSlices.cpp.
References getNeighborPixIDs(), m_cellHeight, m_cellWidth, and m_NeighborIDs.
Referenced by exec().
UpdateOutputWS()
int Mantid::Crystal::IntegratePeakTimeSlices::UpdateOutputWS (DataObjects::TableWorkspace_sptr & TabWS, const int dir, const double chan, std::vector< double > const & params, std::vector< double > const & errs, std::vector< std::string > const & names, const double Chisq, const double time, std::string spec_idList) private
Updates the information in the output OutputWorkspace.
Parameters
TabWS The OutputWorkspace
dir The direction the time slices are going(>0 means increasing otherwise decreasing)
chan The number of channels away from the center channel this data corresponds to
params The parameter values
errs The error in these parameter values
names The names of the parameters
Chisq The fitting error
time The time for this channel
spec_idList The list of spectral id's used to integrate this time channel
Returns
The last row updated
Definition at line 2260 of file IntegratePeakTimeSlices.cpp.
References findNameInVector(), IIntensities, INBoundary, INCol, INRows, ISS1, IStartCol, IStartRow, ITotBoundary, IVariance, m_AttributeValues, and Mantid::Crystal::SQRT().
Referenced by exec().
updatePeakInformation()
void Mantid::Crystal::IntegratePeakTimeSlices::updatePeakInformation (std::vector< double > const & params, std::vector< double > const & errs, std::vector< std::string > const & names, double & TotVariance, double & TotIntensity, double const TotSliceIntensity, double const TotSliceVariance, double const chisqdivDOF, const int ncells) private
Updates m_AttributeValues with this peak information from this time slice.
Parameters
params The parameter values
errs The error in these parameter values
names The names of the parameters
TotVariance The total of the squares of the intensity errors from the data
TotIntensity The total of the intensities so far
TotSliceIntensity The total intensity for this slice
TotSliceVariance The total square of intensity errors for this time slice
chisqdivDOF The fitting error
ncells The number of cells
Definition at line 2352 of file IntegratePeakTimeSlices.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_AttributeValues, and UNUSED_ARG.
Referenced by exec().
updateStats()
void Mantid::Crystal::IntegratePeakTimeSlices::updateStats (const double intensity, const double variance, const double row, const double col, std::vector< double > & StatBase) private
Updates the cumulative statistics for the data being considered.
Parameters
intensity -The experimental intensity at the given pixel
variance -The square of the errors in the above intensity
row -The row of the given pixel
col -The column of the given pixel
StatBase -The data accumulator
Definition at line 865 of file IntegratePeakTimeSlices.cpp.
References IIntensities, ISS1, ISSIx, ISSIxx, ISSIxy, ISSIy, ISSIyy, ISSx, ISSxx, ISSxy, ISSy, ISSyy, and IVariance.
Referenced by SetUpData1().
version()
int Mantid::Crystal::IntegratePeakTimeSlices::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 225 of file IntegratePeakTimeSlices.h.
Member Data Documentation
m_AttributeNames
std::string Mantid::Crystal::IntegratePeakTimeSlices::m_AttributeNames[20] private
Definition at line 237 of file IntegratePeakTimeSlices.h.
Referenced by IntegratePeakTimeSlices().
m_AttributeValues
std::shared_ptr<DataModeHandler> Mantid::Crystal::IntegratePeakTimeSlices::m_AttributeValues private
Definition at line 241 of file IntegratePeakTimeSlices.h.
Referenced by CalculateFunctionProperty_Fit(), exec(), Fit(), isGoodFit(), PreFit(), SetUpData(), SetUpData1(), UpdateOutputWS(), and updatePeakInformation().
m_cellHeight
double Mantid::Crystal::IntegratePeakTimeSlices::m_cellHeight private
for Describing the Plane at the Peak
Definition at line 256 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), SetUpData1(), and updateNeighbors().
m_cellWidth
double Mantid::Crystal::IntegratePeakTimeSlices::m_cellWidth private
Peak.
for Describing the Plane at the Peak
Definition at line 255 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), SetUpData1(), and updateNeighbors().
m_center
Kernel::V3D Mantid::Crystal::IntegratePeakTimeSlices::m_center private
for Describing the Plane at the Peak
Definition at line 249 of file IntegratePeakTimeSlices.h.
Referenced by exec(), and SetUpData().
m_COL
double Mantid::Crystal::IntegratePeakTimeSlices::m_COL private
for Describing the Column(or 0) describing the center of the
Definition at line 253 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), and SetUpData1().
m_EdgePeak
bool Mantid::Crystal::IntegratePeakTimeSlices::m_EdgePeak private
Definition at line 235 of file IntegratePeakTimeSlices.h.
Referenced by IntegratePeakTimeSlices(), isGoodFit(), and SetUpData1().
m_NCOLS
int Mantid::Crystal::IntegratePeakTimeSlices::m_NCOLS private
Definition at line 258 of file IntegratePeakTimeSlices.h.
Referenced by exec(), isGoodFit(), SetUpData(), and SetUpData1().
m_NeighborIDs
int* Mantid::Crystal::IntegratePeakTimeSlices::m_NeighborIDs private
Definition at line 246 of file IntegratePeakTimeSlices.h.
Referenced by exec(), Fit(), IntegratePeakTimeSlices(), SetUpData(), SetUpData1(), updateNeighbors(), and ~IntegratePeakTimeSlices().
m_NROWS
int Mantid::Crystal::IntegratePeakTimeSlices::m_NROWS private
Definition at line 257 of file IntegratePeakTimeSlices.h.
Referenced by exec(), isGoodFit(), SetUpData(), and SetUpData1().
m_ParameterNames
std::string Mantid::Crystal::IntegratePeakTimeSlices::m_ParameterNames[7] private
Definition at line 239 of file IntegratePeakTimeSlices.h.
Referenced by CalculateFunctionProperty_Fit(), Fit(), IntegratePeakTimeSlices(), and PreFit().
m_ParameterValues
std::array<double, 7> Mantid::Crystal::IntegratePeakTimeSlices::m_ParameterValues private
Definition at line 242 of file IntegratePeakTimeSlices.h.
Referenced by CalculateFunctionProperty_Fit(), exec(), IntegratePeakTimeSlices(), PreFit(), SetUpData(), and SetUpData1().
m_R0
double Mantid::Crystal::IntegratePeakTimeSlices::m_R0 private
for Weak Peaks, these can be set using info from close
Definition at line 247 of file IntegratePeakTimeSlices.h.
Referenced by exec(), and SetUpData().
m_ROW
double Mantid::Crystal::IntegratePeakTimeSlices::m_ROW private
for Describing the Row(or 0) describing the center of the Peak
Definition at line 252 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), and SetUpData1().
m_wi_to_detid_map
Mantid::detid2index_map Mantid::Crystal::IntegratePeakTimeSlices::m_wi_to_detid_map private
Definition at line 244 of file IntegratePeakTimeSlices.h.
Referenced by exec(), and SetUpData1().
m_xvec
Kernel::V3D Mantid::Crystal::IntegratePeakTimeSlices::m_xvec private
for Describing the Plane at the Peak
Definition at line 250 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), and SetUpData1().
m_yvec
Kernel::V3D Mantid::Crystal::IntegratePeakTimeSlices::m_yvec private
for Describing the Plane at the Peak
Definition at line 251 of file IntegratePeakTimeSlices.h.
Referenced by exec(), SetUpData(), and SetUpData1().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/IntegratePeakTimeSlices.h
Framework/Crystal/src/IntegratePeakTimeSlices.cpp