Mantid: Mantid::Kernel::Smoothing::detail::GeometricAverager< T > Struct Template Reference
Mantid::Kernel::Smoothing::detail::GeometricAverager< T > Struct Template Reference
Represents taking the geometric mean.
Public Member Functions
void accumulate (T const &x) override
Include values in the average.
GeometricAverager ()
T getAverage () const override
Retrieve the average of all included values.
void separate (T const &x) override
Remove values from the average.
T term (T const &x) const override
A function returning a "term" in the average.
Public Member Functions inherited from Mantid::Kernel::Smoothing::detail::Averager< T >
Averager ()
A small ABC to represent taking an average over a few values.
Additional Inherited Members
Protected Attributes inherited from Mantid::Kernel::Smoothing::detail::Averager< T >
unsigned int m_npts
T m_total
Detailed Description
template<typename T>
struct Mantid::Kernel::Smoothing::detail::GeometricAverager< T >
Represents taking the geometric mean.
Definition at line 74 of file Smoothing.cpp.
Constructor & Destructor Documentation
GeometricAverager()
template<typename T > Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::GeometricAverager () inline
Definition at line 75 of file Smoothing.cpp.
References Mantid::Kernel::Smoothing::detail::Averager< T >::m_total.
Member Function Documentation
accumulate()
template<typename T > void Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::accumulate (T const & x) inline override virtual
Include values in the average.
Parameters
x the value to be included in the averaged
Reimplemented from Mantid::Kernel::Smoothing::detail::Averager< T >.
Definition at line 76 of file Smoothing.cpp.
References Mantid::Kernel::Smoothing::detail::Averager< T >::m_npts, Mantid::Kernel::Smoothing::detail::Averager< T >::m_total, Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::term(), and Mantid::Geometry::x.
getAverage()
template<typename T > T Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::getAverage () const inline override virtual
Retrieve the average of all included values.
Returns
the average of all included terms
Implements Mantid::Kernel::Smoothing::detail::Averager< T >.
Definition at line 89 of file Smoothing.cpp.
separate()
template<typename T > void Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::separate (T const & x) inline override virtual
Remove values from the average.
Parameters
x the value to be removed from the averaged
Reimplemented from Mantid::Kernel::Smoothing::detail::Averager< T >.
Definition at line 82 of file Smoothing.cpp.
References Mantid::Kernel::Smoothing::detail::Averager< T >::m_npts, Mantid::Kernel::Smoothing::detail::Averager< T >::m_total, Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::term(), and Mantid::Geometry::x.
term()
template<typename T > T Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::term (T const & x) const inline override virtual
A function returning a "term" in the average.
Parameters
x the input value, from which the term is computed
Returns
the term, calculated from x
Implements Mantid::Kernel::Smoothing::detail::Averager< T >.
Definition at line 88 of file Smoothing.cpp.
References Mantid::Geometry::x.
Referenced by Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::accumulate(), and Mantid::Kernel::Smoothing::detail::GeometricAverager< T >::separate().
The documentation for this struct was generated from the following file:
Framework/Kernel/src/Smoothing.cpp