Mantid: Mantid::API::IMDNode Class Reference
Mantid::API::IMDNode Class Reference abstract
#include <IMDNode.h>
Public Member Functions
virtual void buildAndAddEvent (const signal_t Signal, const signal_t errorSq, const std::vector< coord_t > &point, uint16_t expInfoIndex, uint16_t goniometerIndex, uint32_t detectorId)=0
Add a single event defined by its components.
virtual size_t buildAndAddEvents (const std::vector< signal_t > &sigErrSq, const std::vector< coord_t > &Coord, const std::vector< uint16_t > &expInfoIndex, const std::vector< uint16_t > &goniometerIndex, const std::vector< uint32_t > &detectorId)=0
Add several events from the vector of event parameters.
virtual void buildAndAddEventUnsafe (const signal_t Signal, const signal_t errorSq, const std::vector< coord_t > &point, uint16_t expInfoIndex, uint16_t goniometerIndex, uint32_t detectorId)=0
Add a single event, with no mutex locking.
virtual void calculateCentroid (coord_t *) const =0
Calculate the centroid of this box and all sub-boxes.
virtual void calculateCentroid (coord_t *, const int) const =0
Calculate the centroid of this box and all sub-boxes.
virtual void calcVolume ()=0
virtual void centroidSphere (Mantid::API::CoordTransform &radiusTransform, const coord_t radiusSquared, coord_t *centroid, signal_t &signal) const =0
Find the centroid of all events contained within by doing a weighted average of their coordinates.
virtual void clear ()=0
Clear all contained data including precalculated averages.
virtual void clearDataFromMemory ()=0
drop event data from memory but keep averages
virtual void clearFileBacked (bool loadFileData)=0
if node was fileBacked, the method clears file-backed information
virtual const IMDNode * getBoxAtCoord (const coord_t *)=0
virtual Mantid::API::BoxController * getBoxController () const =0
get box controller
virtual Mantid::API::BoxController * getBoxController ()=0
virtual void getBoxes (std::vector< IMDNode * > &boxes, size_t maxDepth, bool leafOnly)=0
Fill a vector with all the boxes who are the childred of this one up to a certain depth.
virtual void getBoxes (std::vector< IMDNode * > &boxes, size_t maxDepth, bool leafOnly, Mantid::Geometry::MDImplicitFunction *function)=0
Fill a vector with all the boxes who are the childred of this one up to a certain depth and selected by the function.
virtual void getBoxes (std::vector< IMDNode * > &outBoxes, const std::function< bool(IMDNode *)> &cond)=0
Fill a vector with all the boxes who are satisfying the condition.
virtual void getCenter (coord_t *const) const =0
virtual coord_t * getCentroid () const =0
Get the centroid of this box and all sub-boxes.
virtual IMDNode * getChild (size_t index)=0
Return the indexth child MDBoxBase.
virtual unsigned int getCoordType () const =0
virtual size_t getDataInMemorySize () const =0
get size of the data located in memory, it is equivalent to getNPoints above for memory based workspace but may be different for file based one ;
virtual uint32_t getDepth () const =0
virtual signal_t getError () const =0
virtual signal_t getErrorSquared () const =0
virtual void getEventsData (std::vector< coord_t > &coordTable, size_t &nColumns) const =0
The method to convert events in a box into a table of coodrinates/signal/errors casted into coord_t type Used to save events from plain binary file.
virtual std::string getEventType () const =0
virtual Mantid::Geometry::MDDimensionExtents< coord_t > & getExtents (size_t dim)=0
virtual size_t getID () const =0
virtual coord_t getInverseVolume () const =0
virtual Kernel::ISaveable * getISaveable () const =0
Return the pointer to the sconst tructure responsible for saving the box on disk if the workspace occupies too much memory.
virtual Kernel::ISaveable * getISaveable ()=0
Return the pointer to the structure responsible for saving the box on disk if the workspace occupies too much memory.
virtual bool getIsMasked () const =0
Getter for the masking.
virtual uint64_t getNPoints () const =0
Get total number of points both in memory and on file if present;.
virtual size_t getNumChildren () const =0
Get the # of children MDBoxBase'es (non-recursive)
virtual size_t getNumDims () const =0
Get number of dimensions, the box with this interface has.
virtual size_t getNumMDBoxes () const =0
Get the total # of unsplit MDBoxes contained.
virtual const IMDNode * getParent () const =0
Return a pointer to the parent box (const)
virtual IMDNode * getParent ()=0
Return a pointer to the parent box.
virtual signal_t getSignal () const =0
virtual signal_t getSignalByNEvents () const
virtual signal_t getSignalNormalized () const =0
virtual uint64_t getTotalDataSize () const =0
virtual std::vector< Mantid::Kernel::VMD > getVertexes () const =0
virtual std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices) const =0
virtual std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices, const size_t outDimensions, const bool *maskDim) const =0
virtual void integrateCylinder (Mantid::API::CoordTransform &radiusTransform, const coord_t radius, const coord_t length, signal_t &signal, signal_t &errorSquared, std::vector< signal_t > &signal_fit) const =0
Cylinder (peak) integration The CoordTransform object could be used for more cylinder reduces the dimensions to two values.
virtual void integrateSphere (Mantid::API::CoordTransform &radiusTransform, const coord_t radiusSquared, signal_t &signal, signal_t &errorSquared, const coord_t innerRadiusSquared=0.0, const bool useOnePercentBackgroundCorrection=true) const =0
Sphere (peak) integration The CoordTransform object could be used for more complex shapes, e.g.
virtual bool isBox () const =0
virtual bool isLeaf () const =0
Is this node a leaf: getNumChildren() == 0.
virtual void loadAndAddFrom (API::IBoxControllerIO *const, uint64_t, size_t)=0
Load the additional box data of specified size from the disk location provided using the class, respoinsible for the file IO and append them to the box.
virtual void loadAndAddFrom (API::IBoxControllerIO *const, uint64_t, size_t, std::vector< coord_t > &)=0
Load the additional box data of specified size from the disk location provided using the class, respoinsible for the file IO and append them to the box.
virtual void mask ()=0
Setter for masking the box.
virtual void refreshCache (Kernel::ThreadScheduler *=nullptr)=0
Recalculate signal etc.
virtual void reserveMemoryForLoad (uint64_t)=0
virtual void saveAt (API::IBoxControllerIO *const, uint64_t) const =0
Save the box at specific disk position using the class, respoinsible for the file IO.
virtual void setChildren (const std::vector< IMDNode * > &boxes, const size_t indexStart, const size_t indexEnd)=0
Sets the children from a vector of children.
virtual void setErrorSquared (const signal_t)=0
virtual void setEventsData (const std::vector< coord_t > &coordTable)=0
The method to convert the table of data into vector of events Used to load events from plain binary file.
virtual void setFileBacked ()=0
initiate the structure responsible for swapping the box on HDD if out of memory with default parameters (it does not know its place on HDD and was not saved).
virtual void setFileBacked (const uint64_t, const size_t, const bool)=0
initiate the structure responsible for swapping the box on HDD if out of memory.
virtual void setID (const size_t &newID)=0
sets the special id, which specify the position of this node in the chain linearly ordered nodes
virtual void setInverseVolume (const coord_t)=0
virtual void setParent (IMDNode *parent)=0
Return a pointer to the parent box.
virtual void setSignal (const signal_t)=0
virtual void splitAllIfNeeded (Mantid::Kernel::ThreadScheduler *=nullptr)=0
Split sub-boxes, if this is possible and neede for this box.
virtual void transformDimensions (std::vector< double > &scaling, std::vector< double > &offset)=0
virtual void unmask ()=0
Setter for unmasking the box.
virtual ~IMDNode ()=default
This is an interface to MDBox or MDGridBox of an MDWorkspace.
Static Public Member Functions
static bool CompareFilePosition (const IMDNode *const a, const IMDNode *const b)
Helper method for sorting MDBoxBasees by file position.
static void sortObjByID (std::vector< IMDNode * > &boxes)
Static method for sorting a list of MDBoxBase pointers by their file position, ascending.
Detailed Description
Definition at line 34 of file IMDNode.h.
Constructor & Destructor Documentation
~IMDNode()
virtual Mantid::API::IMDNode::~IMDNode () virtual default
This is an interface to MDBox or MDGridBox of an MDWorkspace.
Date
01/03/2013
Member Function Documentation
buildAndAddEvent()
virtual void Mantid::API::IMDNode::buildAndAddEvent (const signal_t Signal, const signal_t errorSq, const std::vector< coord_t > & point, uint16_t expInfoIndex, uint16_t goniometerIndex, uint32_t detectorId) pure virtual
Add a single event defined by its components.
buildAndAddEvents()
virtual size_t Mantid::API::IMDNode::buildAndAddEvents (const std::vector< signal_t > & sigErrSq, const std::vector< coord_t > & Coord, const std::vector< uint16_t > & expInfoIndex, const std::vector< uint16_t > & goniometerIndex, const std::vector< uint32_t > & detectorId) pure virtual
Add several events from the vector of event parameters.
buildAndAddEventUnsafe()
virtual void Mantid::API::IMDNode::buildAndAddEventUnsafe (const signal_t Signal, const signal_t errorSq, const std::vector< coord_t > & point, uint16_t expInfoIndex, uint16_t goniometerIndex, uint32_t detectorId) pure virtual
Add a single event, with no mutex locking.
calculateCentroid() [1/2]
virtual void Mantid::API::IMDNode::calculateCentroid (coord_t *) const pure virtual
Calculate the centroid of this box and all sub-boxes.
Referenced by Mantid::MDAlgorithms::FindPeaksMD::findPeaks().
calculateCentroid() [2/2]
virtual void Mantid::API::IMDNode::calculateCentroid (coord_t * , const int) const pure virtual
Calculate the centroid of this box and all sub-boxes.
calcVolume()
virtual void Mantid::API::IMDNode::calcVolume () pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
centroidSphere()
virtual void Mantid::API::IMDNode::centroidSphere (Mantid::API::CoordTransform & radiusTransform, const coord_t radiusSquared, coord_t * centroid, signal_t & signal) const pure virtual
Find the centroid of all events contained within by doing a weighted average of their coordinates.
Parameters
radiusTransform :: nd-to-1 coordinate transformation that converts from these dimensions to the distance (squared) from the center of the sphere.
radiusSquared :: radius^2 below which to integrate
[out] centroid :: array of size [nd]; its centroid will be added
[out] signal :: set to the integrated signal
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDGridBox::centroidSphere().
clear()
virtual void Mantid::API::IMDNode::clear () pure virtual
Clear all contained data including precalculated averages.
Referenced by Mantid::MDAlgorithms::MergeMDFiles::loadEventsFromSubBoxes(), and Mantid::DataObjects::MDEventWorkspace< MDE, nd >::setMDMasking().
clearDataFromMemory()
virtual void Mantid::API::IMDNode::clearDataFromMemory () pure virtual
drop event data from memory but keep averages
clearFileBacked()
virtual void Mantid::API::IMDNode::clearFileBacked (bool loadFileData) pure virtual
if node was fileBacked, the method clears file-backed information
Parameters
loadFileData – if true, the data on HDD and not yet in memory are loaded into memory before deleting fileBacked information, if false, all on HDD contents are discarded, which can break the data integrity (used by destructor)
Referenced by Mantid::DataObjects::MDEventWorkspace< MDE, nd >::setMDMasking().
CompareFilePosition()
static bool Mantid::API::IMDNode::CompareFilePosition (const IMDNode *const a, const IMDNode *const b) inline static
Helper method for sorting MDBoxBasees by file position.
MDGridBoxes return 0 for file position and so aren't sorted.
Parameters
a :: an MDBoxBase pointer
b :: an MDBoxBase pointer
Returns
Definition at line 279 of file IMDNode.h.
References getID().
Referenced by sortObjByID().
getBoxAtCoord()
virtual const IMDNode * Mantid::API::IMDNode::getBoxAtCoord (const coord_t *) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getBoxController() [1/2]
virtual Mantid::API::BoxController * Mantid::API::IMDNode::getBoxController () const pure virtual
get box controller
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxSaveable::flushData(), Mantid::DataObjects::MDBoxSaveable::load(), and Mantid::DataObjects::MDBoxSaveable::save().
getBoxController() [2/2]
virtual Mantid::API::BoxController * Mantid::API::IMDNode::getBoxController () pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getBoxes() [1/3]
virtual void Mantid::API::IMDNode::getBoxes (std::vector< IMDNode * > & boxes, size_t maxDepth, bool leafOnly) pure virtual
Fill a vector with all the boxes who are the childred of this one up to a certain depth.
Referenced by Mantid::MDAlgorithms::QTransform::applyCorrection(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::applyDetailedBalance(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::applyPolarizationAngleCorrection(), Mantid::MDAlgorithms::SpectralMomentMD::applyScaling(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::correctForTransmission(), Mantid::MDAlgorithms::MergeMD::doPlus(), Mantid::MDAlgorithms::DivideMD::execEventScalar(), Mantid::MDAlgorithms::MultiplyMD::execEventScalar(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::executeTemplatedMDE(), and Mantid::DataObjects::MDGridBox::getBoxes().
getBoxes() [2/3]
virtual void Mantid::API::IMDNode::getBoxes (std::vector< IMDNode * > & boxes, size_t maxDepth, bool leafOnly, Mantid::Geometry::MDImplicitFunction * function) pure virtual
Fill a vector with all the boxes who are the childred of this one up to a certain depth and selected by the function.
getBoxes() [3/3]
virtual void Mantid::API::IMDNode::getBoxes (std::vector< IMDNode * > & outBoxes, const std::function< bool(IMDNode *)> & cond) pure virtual
Fill a vector with all the boxes who are satisfying the condition.
getCenter()
virtual void Mantid::API::IMDNode::getCenter (coord_t * const) const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDGridBox::centroidSphere(), and Mantid::DataObjects::MDGridBox::integrateCylinder().
getCentroid()
virtual coord_t * Mantid::API::IMDNode::getCentroid () const pure virtual
Get the centroid of this box and all sub-boxes.
Referenced by Mantid::MDAlgorithms::FindPeaksMD::findPeaks().
getChild()
virtual IMDNode * Mantid::API::IMDNode::getChild (size_t index) pure virtual
Return the indexth child MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes().
getCoordType()
virtual unsigned int Mantid::API::IMDNode::getCoordType () const pure virtual
Returns
the length of the coordinates (in bytes), the events in the box contain.
Implemented in Mantid::DataObjects::MDBoxBase.
getDataInMemorySize()
virtual size_t Mantid::API::IMDNode::getDataInMemorySize () const pure virtual
get size of the data located in memory, it is equivalent to getNPoints above for memory based workspace but may be different for file based one ;
getDepth()
virtual uint32_t Mantid::API::IMDNode::getDepth () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes().
getError()
virtual signal_t Mantid::API::IMDNode::getError () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getErrorSquared()
virtual signal_t Mantid::API::IMDNode::getErrorSquared () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), and Mantid::DataObjects::MDGridBox::integrateCylinder().
getEventsData()
virtual void Mantid::API::IMDNode::getEventsData (std::vector< coord_t > & coordTable, size_t & nColumns) const pure virtual
The method to convert events in a box into a table of coodrinates/signal/errors casted into coord_t type Used to save events from plain binary file.
Parameters
coordTable – vector of events parameters
nColumns – number of parameters for each event
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDGridBox::integrateCylinder().
getEventType()
virtual std::string Mantid::API::IMDNode::getEventType () const pure virtual
Returns
the type of the event this box contains
Implemented in Mantid::DataObjects::MDBoxBase.
getExtents()
virtual Mantid::Geometry::MDDimensionExtents< coord_t > & Mantid::API::IMDNode::getExtents (size_t dim) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), and Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getMinimumExtents().
getID()
virtual size_t Mantid::API::IMDNode::getID () const pure virtual
Returns
The special ID which specify location of this node in the chain of ordered boxes (e.g. on a file)
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), CompareFilePosition(), and Mantid::MDAlgorithms::MergeMDFiles::loadEventsFromSubBoxes().
getInverseVolume()
virtual coord_t Mantid::API::IMDNode::getInverseVolume () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getNormalizedSignal(), and Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
getISaveable() [1/2]
virtual Kernel::ISaveable * Mantid::API::IMDNode::getISaveable () const pure virtual
Return the pointer to the sconst tructure responsible for saving the box on disk if the workspace occupies too much memory.
getISaveable() [2/2]
virtual Kernel::ISaveable * Mantid::API::IMDNode::getISaveable () pure virtual
Return the pointer to the structure responsible for saving the box on disk if the workspace occupies too much memory.
Referenced by Mantid::DataObjects::MDEventWorkspace< MDE, nd >::makeBoxTable().
getIsMasked()
virtual bool Mantid::API::IMDNode::getIsMasked () const pure virtual
Getter for the masking.
Referenced by Mantid::DataObjects::MDGridBox::getIsMasked().
getNPoints()
virtual uint64_t Mantid::API::IMDNode::getNPoints () const pure virtual
Get total number of points both in memory and on file if present;.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::MDAlgorithms::CompareMDWorkspaces::compareMDEventWorkspaces(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getMinimumExtents(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getNormalizedSignal(), and getSignalByNEvents().
getNumChildren()
virtual size_t Mantid::API::IMDNode::getNumChildren () const pure virtual
Get the # of children MDBoxBase'es (non-recursive)
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), and Mantid::DataObjects::MDEventWorkspace< MDE, nd >::makeBoxTable().
getNumDims()
virtual size_t Mantid::API::IMDNode::getNumDims () const pure virtual
Get number of dimensions, the box with this interface has.
getNumMDBoxes()
virtual size_t Mantid::API::IMDNode::getNumMDBoxes () const pure virtual
Get the total # of unsplit MDBoxes contained.
getParent() [1/2]
virtual const IMDNode * Mantid::API::IMDNode::getParent () const pure virtual
Return a pointer to the parent box (const)
Implemented in Mantid::DataObjects::MDBoxBase.
getParent() [2/2]
virtual IMDNode * Mantid::API::IMDNode::getParent () pure virtual
Return a pointer to the parent box.
Implemented in Mantid::DataObjects::MDBoxBase.
getSignal()
virtual signal_t Mantid::API::IMDNode::getSignal () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getNormalizedSignal(), getSignalByNEvents(), and Mantid::DataObjects::MDGridBox::integrateCylinder().
getSignalByNEvents()
virtual signal_t Mantid::API::IMDNode::getSignalByNEvents () const inline virtual
Definition at line 266 of file IMDNode.h.
References getNPoints(), and getSignal().
Referenced by Mantid::MDAlgorithms::FindPeaksMD::findPeaks().
getSignalNormalized()
virtual signal_t Mantid::API::IMDNode::getSignalNormalized () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getTotalDataSize()
virtual uint64_t Mantid::API::IMDNode::getTotalDataSize () const pure virtual
Returns
the amount of memory that the object takes up in the MRU.
getVertexes()
virtual std::vector< Mantid::Kernel::VMD > Mantid::API::IMDNode::getVertexes () const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getVertexesArray() [1/2]
virtual std::unique_ptr< coord_t[]> Mantid::API::IMDNode::getVertexesArray (size_t & numVertices) const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
getVertexesArray() [2/2]
virtual std::unique_ptr< coord_t[]> Mantid::API::IMDNode::getVertexesArray (size_t & numVertices, const size_t outDimensions, const bool * maskDim) const pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
integrateCylinder()
virtual void Mantid::API::IMDNode::integrateCylinder (Mantid::API::CoordTransform & radiusTransform, const coord_t radius, const coord_t length, signal_t & signal, signal_t & errorSquared, std::vector< signal_t > & signal_fit) const pure virtual
Cylinder (peak) integration The CoordTransform object could be used for more cylinder reduces the dimensions to two values.
Parameters
radiusTransform :: nd-to-1 coordinate transformation that converts from these dimensions to the distance (squared) from the center of the sphere.
radius :: radius of cylinder below which to integrate
length :: length of cylinder below which to integrate
signal [out] :: set to the integrated signal
errorSquared [out] :: set to the integrated squared error.
signal_fit [out] :: array of values for the fit.
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDGridBox::integrateCylinder().
integrateSphere()
virtual void Mantid::API::IMDNode::integrateSphere (Mantid::API::CoordTransform & radiusTransform, const coord_t radiusSquared, signal_t & signal, signal_t & errorSquared, const coord_t innerRadiusSquared = 0.0, const bool useOnePercentBackgroundCorrection = true) const pure virtual
Sphere (peak) integration The CoordTransform object could be used for more complex shapes, e.g.
"lentil" integration, as long as it reduces the dimensions to a single value.
Parameters
radiusTransform :: nd-to-1 coordinate transformation that converts from these dimensions to the distance (squared) from the center of the sphere.
radiusSquared :: radius^2 below which to integrate
signal [out] :: set to the integrated signal
errorSquared [out] :: set to the integrated squared error.
innerRadiusSquared :: radius^2 of inner background
useOnePercentBackgroundCorrection :: if one percent correction should be applied to background.
Implemented in Mantid::DataObjects::MDBoxBase.
isBox()
virtual bool Mantid::API::IMDNode::isBox () const pure virtual
isLeaf()
virtual bool Mantid::API::IMDNode::isLeaf () const pure virtual
Is this node a leaf: getNumChildren() == 0.
Implemented in Mantid::DataObjects::MDBoxBase.
loadAndAddFrom() [1/2]
virtual void Mantid::API::IMDNode::loadAndAddFrom (API::IBoxControllerIO * const , uint64_t , size_t) pure virtual
Load the additional box data of specified size from the disk location provided using the class, respoinsible for the file IO and append them to the box.
loadAndAddFrom() [2/2]
virtual void Mantid::API::IMDNode::loadAndAddFrom (API::IBoxControllerIO * const , uint64_t , size_t , std::vector< coord_t > &) pure virtual
Load the additional box data of specified size from the disk location provided using the class, respoinsible for the file IO and append them to the box.
Allow for passing temporary memory
Referenced by Mantid::DataObjects::MDBoxSaveable::load(), and Mantid::MDAlgorithms::MergeMDFiles::loadEventsFromSubBoxes().
mask()
virtual void Mantid::API::IMDNode::mask () pure virtual
Setter for masking the box.
Referenced by Mantid::DataObjects::MDGridBox::mask(), and Mantid::DataObjects::MDEventWorkspace< MDE, nd >::setMDMasking().
refreshCache()
virtual void Mantid::API::IMDNode::refreshCache (Kernel::ThreadScheduler * = nullptr) pure virtual
Recalculate signal etc.
reserveMemoryForLoad()
virtual void Mantid::API::IMDNode::reserveMemoryForLoad (uint64_t) pure virtual
Referenced by Mantid::MDAlgorithms::MergeMDFiles::loadEventsFromSubBoxes().
saveAt()
virtual void Mantid::API::IMDNode::saveAt (API::IBoxControllerIO * const , uint64_t) const pure virtual
Save the box at specific disk position using the class, respoinsible for the file IO.
Referenced by Mantid::DataObjects::MDBoxSaveable::save().
setChildren()
virtual void Mantid::API::IMDNode::setChildren (const std::vector< IMDNode * > & boxes, const size_t indexStart, const size_t indexEnd) pure virtual
Sets the children from a vector of children.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
setErrorSquared()
virtual void Mantid::API::IMDNode::setErrorSquared (const signal_t) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
setEventsData()
virtual void Mantid::API::IMDNode::setEventsData (const std::vector< coord_t > & coordTable) pure virtual
The method to convert the table of data into vector of events Used to load events from plain binary file.
Parameters
coordTable – vector of events data, which would be packed into events
Implemented in Mantid::DataObjects::MDBoxBase.
setFileBacked() [1/2]
virtual void Mantid::API::IMDNode::setFileBacked () pure virtual
initiate the structure responsible for swapping the box on HDD if out of memory with default parameters (it does not know its place on HDD and was not saved).
setFileBacked() [2/2]
virtual void Mantid::API::IMDNode::setFileBacked (const uint64_t , const size_t , const bool) pure virtual
initiate the structure responsible for swapping the box on HDD if out of memory.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
setID()
virtual void Mantid::API::IMDNode::setID (const size_t & newID) pure virtual
sets the special id, which specify the position of this node in the chain linearly ordered nodes
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
setInverseVolume()
virtual void Mantid::API::IMDNode::setInverseVolume (const coord_t) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
setParent()
virtual void Mantid::API::IMDNode::setParent (IMDNode * parent) pure virtual
Return a pointer to the parent box.
Implemented in Mantid::DataObjects::MDBoxBase.
setSignal()
virtual void Mantid::API::IMDNode::setSignal (const signal_t) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
Referenced by Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree().
sortObjByID()
static void Mantid::API::IMDNode::sortObjByID (std::vector< IMDNode * > & boxes) inline static
Static method for sorting a list of MDBoxBase pointers by their file position, ascending.
This should optimize the speed of loading a bit by reducing the amount of disk seeking.
Parameters
boxes :: ref to a vector of boxes. It will be sorted in-place.
Definition at line 292 of file IMDNode.h.
References CompareFilePosition().
Referenced by Mantid::MDAlgorithms::BinMD::binByIterating(), Mantid::MDAlgorithms::TransformMD::doTransform(), Mantid::DataObjects::MDBoxFlatTree::initFlatStructure(), and Mantid::MDAlgorithms::SliceMD::slice().
splitAllIfNeeded()
virtual void Mantid::API::IMDNode::splitAllIfNeeded (Mantid::Kernel::ThreadScheduler * = nullptr) pure virtual
Split sub-boxes, if this is possible and neede for this box.
transformDimensions()
virtual void Mantid::API::IMDNode::transformDimensions (std::vector< double > & scaling, std::vector< double > & offset) pure virtual
Implemented in Mantid::DataObjects::MDBoxBase.
unmask()
virtual void Mantid::API::IMDNode::unmask () pure virtual
Setter for unmasking the box.
Referenced by Mantid::DataObjects::MDEventWorkspace< MDE, nd >::clearMDMasking(), and Mantid::DataObjects::MDGridBox::unmask().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IMDNode.h