Mantid: Framework/PythonInterface/mantid/api/src/Exports/Workspace.cpp File Reference
Workspace.cpp File Reference
#include "MantidAPI/Workspace.h"
#include "MantidAPI/WorkspaceHistory.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/api/RegisterWorkspacePtrToPython.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/overloads.hpp>
Functions
void export_Workspace ()
std::string getName (const Workspace &self)
DEPRECATED.
Function Documentation
export_Workspace()
void export_Workspace ()
Definition at line 49 of file Workspace.cpp.
References Mantid::API::Workspace::getComment(), Mantid::API::Workspace::getHistory(), Mantid::API::Workspace::getMemorySize(), getName(), Mantid::API::Workspace::getTitle(), Mantid::API::Workspace::isDirty(), Mantid::API::Workspace::isGroup(), Mantid::API::Workspace::setComment(), and Mantid::API::Workspace::setTitle().
getName()
std::string getName (const Workspace & self)
DEPRECATED.
Use DataItem.name()
Parameters
self Reference to the calling object
Returns
name of the workspace.
Definition at line 44 of file Workspace.cpp.
Referenced by export_Workspace().