Mantid: Mantid::API::TimeAtSampleStrategyIndirect Class Reference
Mantid::API::TimeAtSampleStrategyIndirect Class Reference
TimeAtSampleStrategyIndirect : Determine Time At Sample for an indirect instrument setup.
#include <TimeAtSampleStrategyIndirect.h>
Public Member Functions
Correction calculate (const size_t &workspace_index) const override
TimeAtSampleStrategyIndirect (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Public Member Functions inherited from Mantid::API::TimeAtSampleStrategy
virtual ~TimeAtSampleStrategy ()=default
Private Member Functions
double getEfixed (const size_t &workspace_index) const
This will throw an exception if efixed is not found or negative.
Private Attributes
const Kernel::V3D m_beamDir
const double m_L1s
const Geometry::ParameterMap & m_paramMap
const API::SpectrumInfo & m_spectrumInfo
Detailed Description
TimeAtSampleStrategyIndirect : Determine Time At Sample for an indirect instrument setup.
Definition at line 24 of file TimeAtSampleStrategyIndirect.h.
Constructor & Destructor Documentation
TimeAtSampleStrategyIndirect()
Mantid::API::TimeAtSampleStrategyIndirect::TimeAtSampleStrategyIndirect (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Definition at line 30 of file TimeAtSampleStrategyIndirect.cpp.
Member Function Documentation
calculate()
Correction Mantid::API::TimeAtSampleStrategyIndirect::calculate (const size_t & workspace_index) const override virtual
Implements Mantid::API::TimeAtSampleStrategy.
Definition at line 65 of file TimeAtSampleStrategyIndirect.cpp.
References getEfixed(), Mantid::API::SpectrumInfo::isMonitor(), Mantid::API::SpectrumInfo::l2(), Mantid::Kernel::l2, m_beamDir, m_L1s, m_spectrumInfo, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::NeutronMass, Mantid::API::SpectrumInfo::position(), Mantid::Kernel::V3D::scalar_prod(), and Mantid::API::SpectrumInfo::sourcePosition().
getEfixed()
double Mantid::API::TimeAtSampleStrategyIndirect::getEfixed (const size_t & workspace_index) const private
This will throw an exception if efixed is not found or negative.
Definition at line 38 of file TimeAtSampleStrategyIndirect.cpp.
References Mantid::API::SpectrumInfo::detector(), Mantid::Kernel::efixed, Mantid::Geometry::IDetector::getID(), Mantid::Geometry::ParameterMap::getRecursive(), m_paramMap, and m_spectrumInfo.
Referenced by calculate().
Member Data Documentation
m_beamDir
const Kernel::V3D Mantid::API::TimeAtSampleStrategyIndirect::m_beamDir private
Definition at line 33 of file TimeAtSampleStrategyIndirect.h.
Referenced by calculate().
m_L1s
const double Mantid::API::TimeAtSampleStrategyIndirect::m_L1s private
Definition at line 32 of file TimeAtSampleStrategyIndirect.h.
Referenced by calculate().
m_paramMap
const Geometry::ParameterMap& Mantid::API::TimeAtSampleStrategyIndirect::m_paramMap private
Definition at line 34 of file TimeAtSampleStrategyIndirect.h.
Referenced by getEfixed().
m_spectrumInfo
const API::SpectrumInfo& Mantid::API::TimeAtSampleStrategyIndirect::m_spectrumInfo private
Definition at line 31 of file TimeAtSampleStrategyIndirect.h.
Referenced by calculate(), and getEfixed().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/TimeAtSampleStrategyIndirect.h
Framework/API/src/TimeAtSampleStrategyIndirect.cpp