Mantid: ICat4::ns1__permissibleStringValue Class Reference
ICat4::ns1__permissibleStringValue Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__permissibleStringValue ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__parameterType * type
std::string * value
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2042 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__permissibleStringValue()
ICat4::ns1__permissibleStringValue::ns1__permissibleStringValue () inline
Definition at line 2054 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__permissibleStringValue::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10554 of file ICat4C.cpp.
Referenced by ICat4::soap_in_ns1__permissibleStringValue(), ICat4::soap_new_req_ns1__permissibleStringValue(), and ICat4::soap_new_set_ns1__permissibleStringValue().
soap_get()
void * ICat4::ns1__permissibleStringValue::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10702 of file ICat4C.cpp.
References ICat4::soap_get_ns1__permissibleStringValue().
soap_in()
void * ICat4::ns1__permissibleStringValue::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10599 of file ICat4C.cpp.
References ICat4::soap_in_ns1__permissibleStringValue().
Referenced by ICat4::soap_in_ns1__permissibleStringValue().
soap_out()
int ICat4::ns1__permissibleStringValue::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10572 of file ICat4C.cpp.
References ICat4::soap_out_ns1__permissibleStringValue().
soap_put()
int ICat4::ns1__permissibleStringValue::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10695 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__permissibleStringValue.
soap_serialize()
void ICat4::ns1__permissibleStringValue::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10562 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__parameterType(), and ICat4::soap_serialize_PointerTostd__string().
soap_type()
int ICat4::ns1__permissibleStringValue::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2047 of file ICat4Stub.h.
Member Data Documentation
type
ns1__parameterType* ICat4::ns1__permissibleStringValue::type
Definition at line 2044 of file ICat4Stub.h.
value
std::string* ICat4::ns1__permissibleStringValue::value
Definition at line 2045 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp