Mantid: Mantid::Algorithms::IMCInteractionVolume Class Reference
Mantid::Algorithms::IMCInteractionVolume Class Reference abstract
Defines a base class for objects describing a volume where interactions of Tracks and Objects can take place.
#include <IMCInteractionVolume.h>
Public Member Functions
virtual TrackPair calculateBeforeAfterTrack (Kernel::PseudoRandomNumberGenerator &rng, const Kernel::V3D &startPos, const Kernel::V3D &endPos, MCInteractionStatistics &stats) const =0
virtual const Geometry::BoundingBox getFullBoundingBox () const =0
virtual void setActiveRegion (const Geometry::BoundingBox &region)=0
virtual ~IMCInteractionVolume ()=default
Detailed Description
Defines a base class for objects describing a volume where interactions of Tracks and Objects can take place.
Definition at line 36 of file IMCInteractionVolume.h.
Constructor & Destructor Documentation
~IMCInteractionVolume()
virtual Mantid::Algorithms::IMCInteractionVolume::~IMCInteractionVolume () virtual default
Member Function Documentation
calculateBeforeAfterTrack()
virtual TrackPair Mantid::Algorithms::IMCInteractionVolume::calculateBeforeAfterTrack (Kernel::PseudoRandomNumberGenerator & rng, const Kernel::V3D & startPos, const Kernel::V3D & endPos, MCInteractionStatistics & stats) const pure virtual
Implemented in Mantid::Algorithms::MCInteractionVolume.
Referenced by Mantid::Algorithms::MCAbsorptionStrategy::calculate().
getFullBoundingBox()
virtual const Geometry::BoundingBox Mantid::Algorithms::IMCInteractionVolume::getFullBoundingBox () const pure virtual
Implemented in Mantid::Algorithms::MCInteractionVolume.
Referenced by Mantid::Algorithms::MCAbsorptionStrategy::calculate(), and Mantid::Algorithms::MCAbsorptionStrategy::setActiveRegion().
setActiveRegion()
virtual void Mantid::Algorithms::IMCInteractionVolume::setActiveRegion (const Geometry::BoundingBox & region) pure virtual
Implemented in Mantid::Algorithms::MCInteractionVolume.
Referenced by Mantid::Algorithms::MCAbsorptionStrategy::setActiveRegion().
The documentation for this class was generated from the following file:
Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IMCInteractionVolume.h