Mantid: Mantid::PythonInterface::Registry::MappingTypeHandler Class Reference
Mantid::PythonInterface::Registry::MappingTypeHandler Class Reference final
Defines a handler class for converting a Python mapping type object to a C++ PropertyManager type.
#include <MappingTypeHandler.h>
Private Member Functions
std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::api::object &defaultValue, const boost::python::api::object &validator, const unsigned int direction) const override
Always throws a runtime_error.
void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::api::object &mapping) const override
Sets the named property in the PropertyManager by extracting a new PropertyManager from the Python object.
Additional Inherited Members
Public Member Functions inherited from Mantid::PythonInterface::Registry::PropertyValueHandler
virtual std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::object &value, const boost::python::object &validator, const unsigned int direction) const =0
Overload to create a Property type from the given value with no validation.
virtual void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::object &value) const =0
Overload to set the named property's value on the property manager.
virtual ~PropertyValueHandler ()=default
Virtual Destructor.
Detailed Description
Defines a handler class for converting a Python mapping type object to a C++ PropertyManager type.
Definition at line 19 of file MappingTypeHandler.h.
Member Function Documentation
create()
std::unique_ptr< Kernel::Property > Mantid::PythonInterface::Registry::MappingTypeHandler::create (const std::string & name, const boost::python::api::object & defaultValue, const boost::python::api::object & validator, const unsigned int direction) const override private
Always throws a runtime_error.
Use the PropertyManagerProperty directly
Parameters
name The name of the property
defaultValue A default value for the property.
validator A python object pointing to a validator instance, which can be None.
direction The direction of the property
Returns
A pointer to a newly constructed property instance
Definition at line 54 of file MappingTypeHandler.cpp.
References Mantid::Kernel::createPropertyManager(), and name.
set()
void Mantid::PythonInterface::Registry::MappingTypeHandler::set (Kernel::IPropertyManager * alg, const std::string & name, const boost::python::api::object & mapping) const override private
Sets the named property in the PropertyManager by extracting a new PropertyManager from the Python object.
Parameters
alg A pointer to the PropertyManager containing the named property
name The name of the property to update
mapping The new value of the property
Definition at line 34 of file MappingTypeHandler.cpp.
References Mantid::Kernel::createPropertyManager(), name, and Mantid::Kernel::IPropertyManager::setProperty().
The documentation for this class was generated from the following files:
Framework/PythonInterface/mantid/kernel/inc/MantidPythonInterface/kernel/Registry/MappingTypeHandler.h
Framework/PythonInterface/mantid/kernel/src/Registry/MappingTypeHandler.cpp