Mantid: Mantid::DataHandling::SaveISISNexus Class Reference
Mantid::DataHandling::SaveISISNexus Class Reference final
The SaveISISNexus algorithm will convert a RAW file to a NeXus file.
#include <SaveISISNexus.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
SaveISISNexus ()
Default constructor.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Member Functions
void close ()
close an open dataset.
void closegroup ()
close an open group.
void dae ()
Write instrument/dae.
void detector_1 ()
Write instrument/detector_1.
void exec () override
Overwrites Algorithm method.
int * getMonitorData (int period, int imon)
Get a pointer to the saved monitor data.
void init () override
Overwrites Algorithm method.
void instrument ()
Write instrument.
void logNotes ()
Write notes from LOG_STRUCT.
void make_detector_1_link ()
Create a link to some of detector_1's data.
void moderator ()
Write instrument/moderator.
void monitor_i (int i)
Write single monitor.
void putAttr (const char *name, char *value, int size)
void putAttr (const char *name, const std::string &value)
void putAttr (const char *name, int value, int size=1)
void run_cycle ()
Write run cycle.
void runlog ()
Write runlog.
void sample ()
Write sample.
void saveChar (const char *name, void *data, int size)
Save char data.
void saveCharOpen (const char *name, void *data, int size)
Save char data and leave the dataset open.
void saveFloat (const char *name, void *data, int size)
Save float data.
void saveFloatOpen (const char *name, void *data, int size)
Save float data ald leave the dataset open.
void saveInt (const char *name, void *data, int size=1)
Save int data.
void saveIntOpen (const char *name, void *data, int size=1)
Save int data and leave the dataset open.
void saveString (const char *name, const std::string &str)
Save a string in a dataset.
void saveStringOpen (const char *name, const std::string &str)
Save a string in a dataset.
int saveStringVectorOpen (const char *name, const std::vector< std::string > &str_vec, int max_str_size=-1)
Save a vector of string in a dataset.
void selog ()
Write selog.
void source ()
Write instrument/source.
void toISO8601 (std::string &str)
void user ()
Write user.
void write_isis_vms_compat ()
Write vms_compat.
void write_logOpen (const char *name, void *times, void *data, int type, int size, const std::string &units)
write NXlog
void write_monitors ()
Write monitors.
void write_rpb ()
void write_runlog (const char *name, void *times, void *data, int type, int size, const std::string &units)
write one run log
void write_spb ()
void write_vpb ()
Private Attributes
NXlink counts_link
NXhandle handle
std::string inputFilename
The name and path of the input file.
std::vector< std::string > log_notes
std::unique_ptr< ISISRAW2 > m_isisRaw
std::map< int, int > monitor_index
<spectrum_index,monitor_index>.
std::vector< int > monitorData
int ndet
number of detectors
int nmon
number of monitors
int nper
number of periods
int nsp
number of spectra
int ntc
number of time channels
NXlink period_index_link
FILE * rawFile
NXlink spectrum_index_link
std::string start_time_str
NXlink time_of_flight_link
NXlink time_of_flight_raw_link
Friends
template<typename T >
class getWithoutMonitors
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
The SaveISISNexus algorithm will convert a RAW file to a NeXus file.
Required Properties:
InputFilename - The name of and path to the input RAW file
OutputFilename - The name of and path to the input NeXus file
Author
Roman Tolchenov, Tessella plc
Date
03/03/2011
Definition at line 32 of file SaveISISNexus.h.
Constructor & Destructor Documentation
SaveISISNexus()
Mantid::DataHandling::SaveISISNexus::SaveISISNexus ()
Default constructor.
Empty default constructor.
Definition at line 43 of file SaveISISNexus.cpp.
Member Function Documentation
category()
const std::string Mantid::DataHandling::SaveISISNexus::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 48 of file SaveISISNexus.h.
close()
void Mantid::DataHandling::SaveISISNexus::close () inline private
close an open dataset.
Definition at line 88 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), exec(), instrument(), logNotes(), runlog(), saveChar(), saveFloat(), saveInt(), selog(), and write_logOpen().
closegroup()
void Mantid::DataHandling::SaveISISNexus::closegroup () inline private
close an open group.
Definition at line 89 of file SaveISISNexus.h.
Referenced by write_runlog().
dae()
void Mantid::DataHandling::SaveISISNexus::dae () private
Write instrument/dae.
Definition at line 639 of file SaveISISNexus.cpp.
References close(), handle, m_isisRaw, nper, ntc, period_index_link, putAttr(), saveFloatOpen(), saveIntOpen(), saveString(), time_of_flight_link, and time_of_flight_raw_link.
Referenced by instrument().
detector_1()
void Mantid::DataHandling::SaveISISNexus::detector_1 () private
Write instrument/detector_1.
Definition at line 470 of file SaveISISNexus.cpp.
References close(), counts_link, handle, index, m_isisRaw, monitor_index, monitorData, ndet, nmon, nper, nsp, ntc, period_index_link, putAttr(), rawFile, saveFloat(), saveFloatOpen(), saveIntOpen(), spectrum_index_link, time_of_flight_link, and time_of_flight_raw_link.
Referenced by instrument().
exec()
void Mantid::DataHandling::SaveISISNexus::exec () override private virtual
Overwrites Algorithm method.
Execute the algorithm.
Currently just calls SaveISISNexusProcessed but could call write other formats if support added
Exceptions
runtime_error Thrown if algorithm cannot execute
Implements Mantid::API::Algorithm.
Definition at line 98 of file SaveISISNexus.cpp.
References close(), Mantid::API::Algorithm::getPropertyValue(), handle, inputFilename, instrument(), logNotes(), m_isisRaw, make_detector_1_link(), ndet, nmon, nper, nsp, ntc, putAttr(), rawFile, run_cycle(), runlog(), sample(), saveChar(), saveCharOpen(), saveFloatOpen(), saveInt(), saveString(), saveStringOpen(), selog(), start_time_str, std::to_string(), toISO8601(), user(), write_isis_vms_compat(), and write_monitors().
getMonitorData()
int * Mantid::DataHandling::SaveISISNexus::getMonitorData (int period, int imon) private
Get a pointer to the saved monitor data.
Parameters
period Period, starts with 0
imon Monitor index (not its spectrum number)
Definition at line 593 of file SaveISISNexus.cpp.
References m_isisRaw, and monitorData.
Referenced by monitor_i().
init()
void Mantid::DataHandling::SaveISISNexus::init () override private virtual
Overwrites Algorithm method.
Initialisation method.
Implements Mantid::API::Algorithm.
Definition at line 51 of file SaveISISNexus.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, and Mantid::API::FileProperty::Save.
instrument()
void Mantid::DataHandling::SaveISISNexus::instrument () private
Write instrument.
Definition at line 457 of file SaveISISNexus.cpp.
References close(), dae(), detector_1(), handle, m_isisRaw, moderator(), putAttr(), saveCharOpen(), and source().
Referenced by exec().
logNotes()
void Mantid::DataHandling::SaveISISNexus::logNotes () private
Write notes from LOG_STRUCT.
Definition at line 1016 of file SaveISISNexus.cpp.
References close(), log_notes, and saveStringVectorOpen().
Referenced by exec().
make_detector_1_link()
void Mantid::DataHandling::SaveISISNexus::make_detector_1_link () private
Create a link to some of detector_1's data.
Create group "detector_1" at NXentry level and link to some of the data in instrument/detector_1.
Definition at line 576 of file SaveISISNexus.cpp.
References counts_link, handle, period_index_link, spectrum_index_link, and time_of_flight_link.
Referenced by exec().
moderator()
void Mantid::DataHandling::SaveISISNexus::moderator () private
Write instrument/moderator.
Write instrument/moderator group.
Definition at line 547 of file SaveISISNexus.cpp.
References handle, m_isisRaw, putAttr(), and saveFloatOpen().
Referenced by instrument().
monitor_i()
void Mantid::DataHandling::SaveISISNexus::monitor_i (int i) private
Write single monitor.
Write monitor_i gorup.
Parameters
i Index of a monitor
Definition at line 608 of file SaveISISNexus.cpp.
References getMonitorData(), handle, m_isisRaw, nper, ntc, period_index_link, putAttr(), saveInt(), and time_of_flight_link.
Referenced by write_monitors().
name()
const std::string Mantid::DataHandling::SaveISISNexus::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 37 of file SaveISISNexus.h.
Referenced by putAttr(), saveChar(), saveCharOpen(), saveFloat(), saveFloatOpen(), saveInt(), saveIntOpen(), saveString(), saveStringOpen(), saveStringVectorOpen(), write_logOpen(), and write_runlog().
putAttr() [1/3]
void Mantid::DataHandling::SaveISISNexus::putAttr (const char * name, char * value, int size) private
Definition at line 370 of file SaveISISNexus.cpp.
References handle, name(), and value.
putAttr() [2/3]
void Mantid::DataHandling::SaveISISNexus::putAttr (const char * name, const std::string & value) private
Definition at line 364 of file SaveISISNexus.cpp.
References handle, name(), and value.
Referenced by dae(), detector_1(), exec(), instrument(), moderator(), monitor_i(), runlog(), selog(), and write_logOpen().
putAttr() [3/3]
void Mantid::DataHandling::SaveISISNexus::putAttr (const char * name, int value, int size = 1) private
Definition at line 372 of file SaveISISNexus.cpp.
References handle, name(), and value.
run_cycle()
void Mantid::DataHandling::SaveISISNexus::run_cycle () private
Write run cycle.
Definition at line 1021 of file SaveISISNexus.cpp.
References saveString().
Referenced by exec().
runlog()
void Mantid::DataHandling::SaveISISNexus::runlog () private
Write runlog.
Create and write run logs form <RawFilename>_ICPstatus.txt log file.
Definition at line 712 of file SaveISISNexus.cpp.
References close(), Mantid::API::Algorithm::g_log, handle, inputFilename, Mantid::API::Algorithm::progress(), putAttr(), saveFloatOpen(), saveStringVectorOpen(), start_time_str, Mantid::Kernel::Logger::warning(), and write_runlog().
Referenced by exec().
sample()
void Mantid::DataHandling::SaveISISNexus::sample () private
Write sample.
Definition at line 684 of file SaveISISNexus.cpp.
References handle, m_isisRaw, saveChar(), saveFloat(), saveString(), and tmp.
Referenced by exec().
saveChar()
void Mantid::DataHandling::SaveISISNexus::saveChar (const char * name, void * data, int size) private
Save char data.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(char)
Definition at line 238 of file SaveISISNexus.cpp.
References close(), name(), and saveCharOpen().
Referenced by exec(), sample(), saveString(), user(), and write_isis_vms_compat().
saveCharOpen()
void Mantid::DataHandling::SaveISISNexus::saveCharOpen (const char * name, void * data, int size) private
Save char data and leave the dataset open.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(char)
Definition at line 276 of file SaveISISNexus.cpp.
References handle, and name().
Referenced by exec(), instrument(), saveChar(), and saveStringOpen().
saveFloat()
void Mantid::DataHandling::SaveISISNexus::saveFloat (const char * name, void * data, int size) private
Save float data.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(float)
Definition at line 249 of file SaveISISNexus.cpp.
References close(), name(), and saveFloatOpen().
Referenced by detector_1(), sample(), write_isis_vms_compat(), write_rpb(), write_spb(), and write_vpb().
saveFloatOpen()
void Mantid::DataHandling::SaveISISNexus::saveFloatOpen (const char * name, void * data, int size) private
Save float data ald leave the dataset open.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(float)
Definition at line 292 of file SaveISISNexus.cpp.
References handle, and name().
Referenced by dae(), detector_1(), exec(), moderator(), runlog(), saveFloat(), selog(), and write_logOpen().
saveInt()
void Mantid::DataHandling::SaveISISNexus::saveInt (const char * name, void * data, int size = 1) private
Save int data.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(int)
Definition at line 227 of file SaveISISNexus.cpp.
References close(), name(), and saveIntOpen().
Referenced by exec(), monitor_i(), write_isis_vms_compat(), write_rpb(), write_spb(), and write_vpb().
saveIntOpen()
void Mantid::DataHandling::SaveISISNexus::saveIntOpen (const char * name, void * data, int size = 1) private
Save int data and leave the dataset open.
Parameters
name Name of the data set
data Pointer to the data source
size size of the data in sizeof(int)
Definition at line 260 of file SaveISISNexus.cpp.
References handle, and name().
Referenced by dae(), detector_1(), saveInt(), and write_logOpen().
saveString()
void Mantid::DataHandling::SaveISISNexus::saveString (const char * name, const std::string & str) private
Save a string in a dataset.
Parameters
name :: Name of the data set
str :: The vector to save
Definition at line 345 of file SaveISISNexus.cpp.
References name(), and saveChar().
Referenced by dae(), exec(), run_cycle(), sample(), selog(), source(), and write_isis_vms_compat().
saveStringOpen()
void Mantid::DataHandling::SaveISISNexus::saveStringOpen (const char * name, const std::string & str) private
Save a string in a dataset.
Parameters
name :: Name of the data set
str :: The vector to save
Definition at line 357 of file SaveISISNexus.cpp.
References name(), and saveCharOpen().
Referenced by exec(), and saveStringVectorOpen().
saveStringVectorOpen()
int Mantid::DataHandling::SaveISISNexus::saveStringVectorOpen (const char * name, const std::vector< std::string > & str_vec, int max_str_size = -1) private
Save a vector of string in a dataset.
Parameters
name :: Name of the data set
str_vec :: The vector to save
max_str_size :: The maximum string size
Returns
The line size
Definition at line 309 of file SaveISISNexus.cpp.
References handle, n, name(), and saveStringOpen().
Referenced by logNotes(), runlog(), selog(), and write_isis_vms_compat().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::SaveISISNexus::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 46 of file SaveISISNexus.h.
selog()
void Mantid::DataHandling::SaveISISNexus::selog () private
Write selog.
Definition at line 894 of file SaveISISNexus.cpp.
References close(), Mantid::API::Algorithm::g_log, handle, inputFilename, Mantid::API::Algorithm::progress(), putAttr(), Mantid::Kernel::ProgressBase::report(), saveFloatOpen(), saveString(), saveStringVectorOpen(), start_time_str, tmp, and Mantid::Kernel::Logger::warning().
Referenced by exec().
source()
void Mantid::DataHandling::SaveISISNexus::source () private
Write instrument/source.
Write instrument/source group.
Definition at line 561 of file SaveISISNexus.cpp.
References handle, and saveString().
Referenced by instrument().
summary()
const std::string Mantid::DataHandling::SaveISISNexus::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 39 of file SaveISISNexus.h.
toISO8601()
void Mantid::DataHandling::SaveISISNexus::toISO8601 (std::string & str) private
Definition at line 374 of file SaveISISNexus.cpp.
Referenced by exec().
user()
void Mantid::DataHandling::SaveISISNexus::user () private
Write user.
Definition at line 674 of file SaveISISNexus.cpp.
References handle, m_isisRaw, and saveChar().
Referenced by exec().
version()
int Mantid::DataHandling::SaveISISNexus::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 45 of file SaveISISNexus.h.
write_isis_vms_compat()
void Mantid::DataHandling::SaveISISNexus::write_isis_vms_compat () private
Write vms_compat.
Write isis_vms_compat.
Definition at line 385 of file SaveISISNexus.cpp.
References handle, log_notes, m_isisRaw, n, ndet, nmon, saveChar(), saveFloat(), saveInt(), saveString(), saveStringVectorOpen(), write_rpb(), write_spb(), and write_vpb().
Referenced by exec().
write_logOpen()
void Mantid::DataHandling::SaveISISNexus::write_logOpen (const char * name, void * times, void * data, int type, int size, const std::string & units) private
write NXlog
Writes a NXlog and leaves it open.
Parameters
name The log name
times The pointer to the time array
data The pointer to the data
type The type of the data
size The size of the data
units The units of the data
Definition at line 875 of file SaveISISNexus.cpp.
References close(), handle, name(), putAttr(), saveFloatOpen(), saveIntOpen(), and start_time_str.
Referenced by write_runlog().
write_monitors()
void Mantid::DataHandling::SaveISISNexus::write_monitors () private
Write monitors.
Definition at line 597 of file SaveISISNexus.cpp.
References m_isisRaw, monitor_i(), and nmon.
Referenced by exec().
write_rpb()
void Mantid::DataHandling::SaveISISNexus::write_rpb () private
Definition at line 1023 of file SaveISISNexus.cpp.
References handle, m_isisRaw, saveFloat(), and saveInt().
Referenced by write_isis_vms_compat().
write_runlog()
void Mantid::DataHandling::SaveISISNexus::write_runlog (const char * name, void * times, void * data, int type, int size, const std::string & units) private
write one run log
Write one run log.
Parameters
name The log name
times The pointer to the time array
data The pointer to the data
type The type of the data
size The size of the data
units The units of the data
Definition at line 860 of file SaveISISNexus.cpp.
References closegroup(), name(), and write_logOpen().
Referenced by runlog().
write_spb()
void Mantid::DataHandling::SaveISISNexus::write_spb () private
Definition at line 1034 of file SaveISISNexus.cpp.
References handle, m_isisRaw, saveFloat(), and saveInt().
Referenced by write_isis_vms_compat().
write_vpb()
void Mantid::DataHandling::SaveISISNexus::write_vpb () private
Definition at line 1046 of file SaveISISNexus.cpp.
References m_isisRaw, saveFloat(), and saveInt().
Referenced by write_isis_vms_compat().
Friends And Related Function Documentation
getWithoutMonitors
template<typename T > friend class getWithoutMonitors friend
Definition at line 95 of file SaveISISNexus.h.
Member Data Documentation
counts_link
NXlink Mantid::DataHandling::SaveISISNexus::counts_link private
Definition at line 72 of file SaveISISNexus.h.
Referenced by detector_1(), and make_detector_1_link().
handle
NXhandle Mantid::DataHandling::SaveISISNexus::handle private
Definition at line 58 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), exec(), instrument(), make_detector_1_link(), moderator(), monitor_i(), putAttr(), runlog(), sample(), saveCharOpen(), saveFloatOpen(), saveIntOpen(), saveStringVectorOpen(), selog(), source(), user(), write_isis_vms_compat(), write_logOpen(), write_rpb(), and write_spb().
inputFilename
std::string Mantid::DataHandling::SaveISISNexus::inputFilename private
The name and path of the input file.
Definition at line 136 of file SaveISISNexus.h.
Referenced by exec(), runlog(), and selog().
log_notes
std::vector<std::string> Mantid::DataHandling::SaveISISNexus::log_notes private
Definition at line 70 of file SaveISISNexus.h.
Referenced by logNotes(), and write_isis_vms_compat().
m_isisRaw
std::unique_ptr<ISISRAW2> Mantid::DataHandling::SaveISISNexus::m_isisRaw private
Definition at line 57 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), exec(), getMonitorData(), instrument(), moderator(), monitor_i(), sample(), user(), write_isis_vms_compat(), write_monitors(), write_rpb(), write_spb(), and write_vpb().
monitor_index
std::map<int, int> Mantid::DataHandling::SaveISISNexus::monitor_index private
<spectrum_index,monitor_index>.
spectrum index is an index in any detector related array, not spectrum number
Definition at line 63 of file SaveISISNexus.h.
Referenced by detector_1(), and Mantid::DataHandling::getWithoutMonitors< T >::operator()().
monitorData
std::vector<int> Mantid::DataHandling::SaveISISNexus::monitorData private
Definition at line 60 of file SaveISISNexus.h.
Referenced by detector_1(), and getMonitorData().
ndet
int Mantid::DataHandling::SaveISISNexus::ndet private
number of detectors
Definition at line 68 of file SaveISISNexus.h.
Referenced by detector_1(), exec(), and write_isis_vms_compat().
nmon
int Mantid::DataHandling::SaveISISNexus::nmon private
number of monitors
Definition at line 67 of file SaveISISNexus.h.
Referenced by detector_1(), exec(), write_isis_vms_compat(), and write_monitors().
nper
int Mantid::DataHandling::SaveISISNexus::nper private
number of periods
Definition at line 64 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), exec(), and monitor_i().
nsp
int Mantid::DataHandling::SaveISISNexus::nsp private
number of spectra
Definition at line 65 of file SaveISISNexus.h.
Referenced by detector_1(), and exec().
ntc
int Mantid::DataHandling::SaveISISNexus::ntc private
number of time channels
Definition at line 66 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), exec(), and monitor_i().
period_index_link
NXlink Mantid::DataHandling::SaveISISNexus::period_index_link private
Definition at line 73 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), make_detector_1_link(), and monitor_i().
rawFile
FILE* Mantid::DataHandling::SaveISISNexus::rawFile private
Definition at line 59 of file SaveISISNexus.h.
Referenced by detector_1(), and exec().
spectrum_index_link
NXlink Mantid::DataHandling::SaveISISNexus::spectrum_index_link private
Definition at line 74 of file SaveISISNexus.h.
Referenced by detector_1(), and make_detector_1_link().
start_time_str
std::string Mantid::DataHandling::SaveISISNexus::start_time_str private
Definition at line 69 of file SaveISISNexus.h.
Referenced by exec(), runlog(), selog(), and write_logOpen().
time_of_flight_link
NXlink Mantid::DataHandling::SaveISISNexus::time_of_flight_link private
Definition at line 75 of file SaveISISNexus.h.
Referenced by dae(), detector_1(), make_detector_1_link(), and monitor_i().
time_of_flight_raw_link
NXlink Mantid::DataHandling::SaveISISNexus::time_of_flight_raw_link private
Definition at line 76 of file SaveISISNexus.h.
Referenced by dae(), and detector_1().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/SaveISISNexus.h
Framework/DataHandling/src/SaveISISNexus.cpp