Mantid: Mantid::Geometry::Surface Class Reference
Mantid::Geometry::Surface Class Reference abstract
Holds a basic quadratic surface.
#include <Surface.h>
Public Member Functions
virtual void acceptVisitor (BaseVisit &A) const
Accept visitor for line calculation.
virtual std::string className () const
Effective typeid.
std::unique_ptr< Surface > clone () const
virtual void displace (const Kernel::V3D &)=0
translates the surface
virtual double distance (const Kernel::V3D &) const =0
returns the minimum distance to the surface
virtual void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin)=0
bounding box for the surface
int getName () const
Get Name.
virtual bool onSurface (const Kernel::V3D &R) const =0
is point valid on surface
Surface & operator= (const Surface &)=delete
virtual void print () const
Simple print out function for surface header.
virtual void rotate (const Kernel::Matrix< double > &)=0
rotates the surface
void setName (int const N)
Set Name.
virtual int setSurface (const std::string &R)=0
Sets the surface based on a string input in MCNPX format.
virtual int side (const Kernel::V3D &) const
Surface side : throw AbsObjMethod.
Surface ()
Constructor.
virtual Kernel::V3D surfaceNormal (const Kernel::V3D &) const =0
returns the normal to the closest point on the surface
virtual void write (std::ostream &) const
The writes the data to the output stream.
void writeHeader (std::ostream &) const
Writes out the start of an MCNPX surface description .
virtual ~Surface ()=default
Static Public Attributes
static const int Nprecision = 10
Precision of the output.
Protected Member Functions
Surface (const Surface &)=default
Private Member Functions
virtual Surface * doClone () const =0
Abstract clone function.
Private Attributes
int Name
Surface number (MCNPX identifier)
Detailed Description
Holds a basic quadratic surface.
Author
S. Ansell
Date
April 2004
Version
1.0
Holds a basic surface with equation form
\[ Ax^2+By^2+Cz^2+Dxy+Exz+Fyz+Gx+Hy+Jz+K=0 \]
Definition at line 33 of file Surface.h.
Constructor & Destructor Documentation
Surface() [1/2]
Mantid::Geometry::Surface::Surface (const Surface &) protected default
Surface() [2/2]
Mantid::Geometry::Surface::Surface ()
Constructor.
Definition at line 50 of file Surface.cpp.
~Surface()
virtual Mantid::Geometry::Surface::~Surface () virtual default
Member Function Documentation
acceptVisitor()
virtual void Mantid::Geometry::Surface::acceptVisitor (BaseVisit & A) const inline virtual
Accept visitor for line calculation.
Reimplemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
Definition at line 53 of file Surface.h.
References Mantid::Geometry::BaseVisit::Accept().
className()
virtual std::string Mantid::Geometry::Surface::className () const inline virtual
Effective typeid.
Reimplemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
Definition at line 50 of file Surface.h.
clone()
std::unique_ptr< Surface > Mantid::Geometry::Surface::clone () const inline
Definition at line 44 of file Surface.h.
displace()
virtual void Mantid::Geometry::Surface::displace (const Kernel::V3D &) pure virtual
translates the surface
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
distance()
virtual double Mantid::Geometry::Surface::distance (const Kernel::V3D &) const pure virtual
returns the minimum distance to the surface
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
doClone()
virtual Surface * Mantid::Geometry::Surface::doClone () const private pure virtual
Abstract clone function.
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::General, Mantid::Geometry::Plane, Mantid::Geometry::Sphere, Mantid::Geometry::Torus, and Mantid::Geometry::Quadratic.
getBoundingBox()
virtual void Mantid::Geometry::Surface::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) pure virtual
bounding box for the surface
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::General, Mantid::Geometry::Plane, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
getName()
int Mantid::Geometry::Surface::getName () const inline
Get Name.
Definition at line 56 of file Surface.h.
Referenced by Mantid::Geometry::CSGObject::getSurfaceIndex().
onSurface()
virtual bool Mantid::Geometry::Surface::onSurface (const Kernel::V3D & R) const pure virtual
is point valid on surface
Implemented in Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, Mantid::Geometry::Cone, and Mantid::Geometry::Torus.
operator=()
Surface & Mantid::Geometry::Surface::operator= (const Surface &) delete
print()
void Mantid::Geometry::Surface::print () const virtual
Simple print out function for surface header.
Reimplemented in Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, and Mantid::Geometry::Quadratic.
Definition at line 63 of file Surface.cpp.
References Name.
Referenced by Mantid::Geometry::Quadratic::print().
rotate()
virtual void Mantid::Geometry::Surface::rotate (const Kernel::Matrix< double > &) pure virtual
rotates the surface
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
setName()
void Mantid::Geometry::Surface::setName (int const N) inline
Set Name.
Definition at line 55 of file Surface.h.
setSurface()
virtual int Mantid::Geometry::Surface::setSurface (const std::string & R) pure virtual
Sets the surface based on a string input in MCNPX format.
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::General, Mantid::Geometry::Plane, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
side()
int Mantid::Geometry::Surface::side (const Kernel::V3D &) const virtual
Surface side : throw AbsObjMethod.
Reimplemented in Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, Mantid::Geometry::Cone, and Mantid::Geometry::Torus.
Definition at line 57 of file Surface.cpp.
surfaceNormal()
virtual Kernel::V3D Mantid::Geometry::Surface::surfaceNormal (const Kernel::V3D &) const pure virtual
returns the normal to the closest point on the surface
Implemented in Mantid::Geometry::Quadratic, and Mantid::Geometry::Torus.
write()
void Mantid::Geometry::Surface::write (std::ostream & out) const virtual
The writes the data to the output stream.
Parameters
out :: The output stream
Reimplemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::Plane, Mantid::Geometry::Quadratic, Mantid::Geometry::Sphere, and Mantid::Geometry::Torus.
Definition at line 81 of file Surface.cpp.
Referenced by Mantid::Geometry::Torus::write().
writeHeader()
void Mantid::Geometry::Surface::writeHeader (std::ostream & OX) const
Writes out the start of an MCNPX surface description .
Does not check the length etc
Parameters
OX :: Output stream
Definition at line 71 of file Surface.cpp.
Referenced by Mantid::Geometry::Cone::write(), Mantid::Geometry::Plane::write(), Mantid::Geometry::Sphere::write(), and Mantid::Geometry::Torus::write().
Member Data Documentation
Name
int Mantid::Geometry::Surface::Name private
Surface number (MCNPX identifier)
Definition at line 35 of file Surface.h.
Referenced by print().
Nprecision
const int Mantid::Geometry::Surface::Nprecision = 10 static
Precision of the output.
Definition at line 41 of file Surface.h.
Referenced by Mantid::Geometry::Cone::write(), Mantid::Geometry::Cylinder::write(), Mantid::Geometry::Plane::write(), Mantid::Geometry::Quadratic::write(), Mantid::Geometry::Sphere::write(), and Mantid::Geometry::Torus::write().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Surfaces/Surface.h
Framework/Geometry/src/Surfaces/Surface.cpp