Mantid: Mantid::Geometry::PointGroupGenerator Class Reference
Mantid::Geometry::PointGroupGenerator Class Reference
#include <PointGroupFactory.h>
Public Member Functions
const std::string & getDescription () const
const std::string & getGeneratorString () const
const std::string & getHMSymbol () const
PointGroup_sptr getPrototype ()
PointGroupGenerator (std::string hmSymbol, std::string generatorInformation, std::string description)
Private Member Functions
PointGroup_sptr generatePrototype ()
bool hasValidPrototype () const
Private Attributes
std::string m_description
std::string m_generatorString
std::string m_hmSymbol
PointGroup_sptr m_prototype
Detailed Description
Definition at line 20 of file PointGroupFactory.h.
Constructor & Destructor Documentation
PointGroupGenerator()
Mantid::Geometry::PointGroupGenerator::PointGroupGenerator (std::string hmSymbol, std::string generatorInformation, std::string description)
Definition at line 153 of file PointGroupFactory.cpp.
Member Function Documentation
generatePrototype()
PointGroup_sptr Mantid::Geometry::PointGroupGenerator::generatePrototype () private
Definition at line 166 of file PointGroupFactory.cpp.
References m_description, m_generatorString, and m_hmSymbol.
Referenced by getPrototype().
getDescription()
const std::string & Mantid::Geometry::PointGroupGenerator::getDescription () const inline
Definition at line 26 of file PointGroupFactory.h.
getGeneratorString()
const std::string & Mantid::Geometry::PointGroupGenerator::getGeneratorString () const inline
Definition at line 25 of file PointGroupFactory.h.
getHMSymbol()
const std::string & Mantid::Geometry::PointGroupGenerator::getHMSymbol () const inline
Definition at line 24 of file PointGroupFactory.h.
getPrototype()
PointGroup_sptr Mantid::Geometry::PointGroupGenerator::getPrototype ()
Definition at line 158 of file PointGroupFactory.cpp.
References generatePrototype(), hasValidPrototype(), and m_prototype.
hasValidPrototype()
bool Mantid::Geometry::PointGroupGenerator::hasValidPrototype () const inline private
Definition at line 31 of file PointGroupFactory.h.
Referenced by getPrototype().
Member Data Documentation
m_description
std::string Mantid::Geometry::PointGroupGenerator::m_description private
Definition at line 37 of file PointGroupFactory.h.
Referenced by generatePrototype().
m_generatorString
std::string Mantid::Geometry::PointGroupGenerator::m_generatorString private
Definition at line 36 of file PointGroupFactory.h.
Referenced by generatePrototype().
m_hmSymbol
std::string Mantid::Geometry::PointGroupGenerator::m_hmSymbol private
Definition at line 35 of file PointGroupFactory.h.
Referenced by generatePrototype().
m_prototype
PointGroup_sptr Mantid::Geometry::PointGroupGenerator::m_prototype private
Definition at line 39 of file PointGroupFactory.h.
Referenced by getPrototype().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/PointGroupFactory.h
Framework/Geometry/src/Crystal/PointGroupFactory.cpp