Mantid: Mantid::PythonInterface::Converters Namespace Reference
Mantid::PythonInterface::Converters Namespace Reference
Namespaces
namespace Impl
Classes
struct CArrayToNDArray
Converter that takes a c array and its size then converts/wraps it into a numpy array.
struct Clone
Clone is a policy (in the C++ sense)for converting to an ND Array.
struct MapToPyDictionary
struct MatrixToNDArray
Converter that takes a Mantid Matrix and converts it into a numpy array.
struct NDArrayToVector
Converter taking an input numpy array and converting it to a std::vector.
struct NDArrayTypeIndex
Defines a mapping between C++ type given by the template parameter and numpy type enum NPY_TYPES.
struct PyObjectToMatrix
Takes a Python object and if it supports indexing and is two dimensional it attempts to convert it to a Kernel::Matrix object.
struct PyObjectToV3D
Takes a Python object and if it supports indexing and is of length 3 then it will attempt to convert a Kernel::V3D object from it.
struct PyObjectToVMD
Takes a Python object and if it supports indexing and is of length 3 then it will attempt to convert a Kernel::VMD object from it.
struct PySequenceToVector
Converts a Python sequence type to a C++ std::vector, where the element type is defined by the template type.
struct ToPyList
Converter that takes a std::vector and converts it into a python list.
struct VectorToNDArray
Converter that takes a std::vector and converts it into a flat numpy array.
struct WrapReadOnly
WrapReadOnly is a policy for VectorToNDArray to wrap the vector in a read-only numpy array that looks at the original data.
struct WrapReadWrite
WrapReadWrite is a policy for VectorToNDArray to wrap the vector in a read-write numpy array that looks at the original data.
Enumerations
enum NumpyWrapMode { ReadOnly , ReadWrite }
Enum defining wrapping type for conversion to numpy.
enum OwnershipMode { Cpp , Python }
Enum defining transfer of ownership when converting to numpy array.
Functions
MANTID_PYTHONINTERFACE_CORE_DLL PyArray_Descr * descr_ns ()
template<template< class > class Container, typename HeldType >
std::string dtype (const Container< HeldType > &)
MANTID_PYTHONINTERFACE_CORE_DLL std::shared_ptr< Types::Core::DateAndTime > to_dateandtime (const boost::python::api::object &value)
std::shared_ptr< Types::Core::DateAndTime > to_dateandtime (const PyObject *datetime)
PyObject * to_datetime64 (const DateAndTime &dateandtime)
MANTID_PYTHONINTERFACE_CORE_DLL PyObject * to_datetime64 (const Types::Core::DateAndTime &dateandtime)
Convert to numpy's datetime64. This is panda's name for the function.
npy_datetime to_npy_datetime (const DateAndTime &dateandtime)
MANTID_PYTHONINTERFACE_CORE_DLL npy_datetime to_npy_datetime (const Types::Core::DateAndTime &dateandtime)
Total nanoseconds since the unix epoch.
Enumeration Type Documentation
NumpyWrapMode
enum Mantid::PythonInterface::Converters::NumpyWrapMode
Enum defining wrapping type for conversion to numpy.
Enumerator
ReadOnly
ReadWrite
Definition at line 17 of file WrapWithNDArray.h.
OwnershipMode
enum Mantid::PythonInterface::Converters::OwnershipMode
Enum defining transfer of ownership when converting to numpy array.
Enumerator
Cpp
Python
Definition at line 19 of file WrapWithNDArray.h.
Function Documentation
descr_ns()
PyArray_Descr * Mantid::PythonInterface::Converters::descr_ns ()
Definition at line 46 of file DateAndTime.cpp.
Referenced by Mantid::PythonInterface::Converters::Impl::clone1D(), and to_datetime64().
dtype()
template<template< class > class Container, typename HeldType > std::string Mantid::PythonInterface::Converters::dtype (const Container< HeldType > &)
Definition at line 27 of file ContainerDtype.h.
Referenced by dtype().
to_dateandtime() [1/2]
std::shared_ptr< Types::Core::DateAndTime > Mantid::PythonInterface::Converters::to_dateandtime (const boost::python::api::object & value)
Definition at line 81 of file DateAndTime.cpp.
References to_dateandtime(), and value.
Referenced by export_DateAndTime(), and to_dateandtime().
to_dateandtime() [2/2]
std::shared_ptr< Types::Core::DateAndTime > Mantid::PythonInterface::Converters::to_dateandtime (const PyObject * datetime)
Definition at line 49 of file DateAndTime.cpp.
References GNU_DIAG_OFF, GNU_DIAG_ON, and value.
to_datetime64() [1/2]
PyObject * Mantid::PythonInterface::Converters::to_datetime64 (const DateAndTime & dateandtime)
Definition at line 32 of file DateAndTime.cpp.
References descr_ns(), and to_npy_datetime().
to_datetime64() [2/2]
MANTID_PYTHONINTERFACE_CORE_DLL PyObject * Mantid::PythonInterface::Converters::to_datetime64 (const Types::Core::DateAndTime & dateandtime)
Convert to numpy's datetime64. This is panda's name for the function.
Referenced by export_DateAndTime().
to_npy_datetime() [1/2]
npy_datetime Mantid::PythonInterface::Converters::to_npy_datetime (const DateAndTime & dateandtime)
Definition at line 28 of file DateAndTime.cpp.
to_npy_datetime() [2/2]
MANTID_PYTHONINTERFACE_CORE_DLL npy_datetime Mantid::PythonInterface::Converters::to_npy_datetime (const Types::Core::DateAndTime & dateandtime)
Total nanoseconds since the unix epoch.
Referenced by Mantid::PythonInterface::Converters::Impl::clone1D(), and to_datetime64().