Mantid: Mantid::CurveFitting::Functions::RemovePeaks Class Reference
Mantid::CurveFitting::Functions::RemovePeaks Class Reference
#include <ProcessBackground.h>
Public Member Functions
DataObjects::Workspace2D_sptr removePeaks (const API::MatrixWorkspace_const_sptr &dataws, int wsindex, double numfwhm)
Remove peaks from a input workspace.
void setup (const DataObjects::TableWorkspace_sptr &peaktablews)
Set up: parse peak workspace to vectors.
Private Member Functions
size_t excludePeaks (std::vector< double > v_inX, std::vector< bool > &v_useX, const std::vector< double > &v_centre, const std::vector< double > &v_fwhm, double num_fwhm)
Exclude peak regions.
void parsePeakTableWorkspace (const DataObjects::TableWorkspace_sptr &peaktablews, std::vector< double > &vec_peakcentre, std::vector< double > &vec_peakfwhm)
Parse peak centre and FWHM from a table workspace.
Private Attributes
std::vector< double > m_vecPeakCentre
std::vector< double > m_vecPeakFWHM
Detailed Description
Definition at line 23 of file ProcessBackground.h.
Member Function Documentation
excludePeaks()
size_t Mantid::CurveFitting::Functions::RemovePeaks::excludePeaks (std::vector< double > v_inX, std::vector< bool > & v_useX, const std::vector< double > & v_centre, const std::vector< double > & v_fwhm, double num_fwhm) private
Exclude peak regions.
Exclude peaks from.
Definition at line 898 of file ProcessBackground.cpp.
Referenced by removePeaks().
parsePeakTableWorkspace()
void Mantid::CurveFitting::Functions::RemovePeaks::parsePeakTableWorkspace (const DataObjects::TableWorkspace_sptr & peaktablews, std::vector< double > & vec_peakcentre, std::vector< double > & vec_peakfwhm) private
Parse peak centre and FWHM from a table workspace.
Parse table workspace.
Definition at line 864 of file ProcessBackground.cpp.
Referenced by setup().
removePeaks()
Workspace2D_sptr Mantid::CurveFitting::Functions::RemovePeaks::removePeaks (const API::MatrixWorkspace_const_sptr & dataws, int wsindex, double numfwhm)
Remove peaks from a input workspace.
Definition at line 811 of file ProcessBackground.cpp.
References Mantid::DataObjects::create(), excludePeaks(), index, Mantid::Kernel::SingletonHolder< T >::Instance(), m_vecPeakCentre, and m_vecPeakFWHM.
Referenced by Mantid::CurveFitting::Functions::ProcessBackground::removePeaks().
setup()
void Mantid::CurveFitting::Functions::RemovePeaks::setup (const DataObjects::TableWorkspace_sptr & peaktablews)
Set up: parse peak workspace to vectors.
Definition at line 797 of file ProcessBackground.cpp.
References m_vecPeakCentre, m_vecPeakFWHM, and parsePeakTableWorkspace().
Referenced by Mantid::CurveFitting::Functions::ProcessBackground::removePeaks().
Member Data Documentation
m_vecPeakCentre
std::vector<double> Mantid::CurveFitting::Functions::RemovePeaks::m_vecPeakCentre private
Definition at line 38 of file ProcessBackground.h.
Referenced by removePeaks(), and setup().
m_vecPeakFWHM
std::vector<double> Mantid::CurveFitting::Functions::RemovePeaks::m_vecPeakFWHM private
Definition at line 39 of file ProcessBackground.h.
Referenced by removePeaks(), and setup().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/ProcessBackground.h
Framework/CurveFitting/src/Functions/ProcessBackground.cpp