Mantid: AlgEnvHistoryGrpBox Class Reference
AlgEnvHistoryGrpBox Class Reference
#include <AlgorithmHistoryWindow.h>
Public Member Functions
AlgEnvHistoryGrpBox (const QString &, QWidget *w)
AlgEnvHistoryGrpBox (QWidget *w)
void fillEnvHistoryGroupBox (const Mantid::Kernel::EnvironmentHistory &envHist)
QLineEdit * getfrmworkVersionEdit () const
QLineEdit * getosNameEdit () const
QLineEdit * getosVersionEdit () const
~AlgEnvHistoryGrpBox () override
Private Attributes
QLineEdit * m_frmwkVersnEdit
QLabel * m_frmworkVersionLabel
QLineEdit * m_osNameEdit
QLabel * m_osNameLabel
QLineEdit * m_osVersionEdit
QLabel * m_osVersionLabel
Detailed Description
Definition at line 112 of file AlgorithmHistoryWindow.h.
Constructor & Destructor Documentation
AlgEnvHistoryGrpBox() [1/2]
AlgEnvHistoryGrpBox::AlgEnvHistoryGrpBox (QWidget * w) explicit
Definition at line 131 of file AlgorithmHistoryWindow.cpp.
AlgEnvHistoryGrpBox() [2/2]
AlgEnvHistoryGrpBox::AlgEnvHistoryGrpBox (const QString & title, QWidget * w)
Definition at line 135 of file AlgorithmHistoryWindow.cpp.
References m_frmwkVersnEdit, m_frmworkVersionLabel, m_osNameEdit, m_osNameLabel, m_osVersionEdit, and m_osVersionLabel.
~AlgEnvHistoryGrpBox()
AlgEnvHistoryGrpBox::~AlgEnvHistoryGrpBox () override
Definition at line 173 of file AlgorithmHistoryWindow.cpp.
References m_frmwkVersnEdit, m_frmworkVersionLabel, m_osNameEdit, m_osNameLabel, m_osVersionEdit, and m_osVersionLabel.
Member Function Documentation
fillEnvHistoryGroupBox()
void AlgEnvHistoryGrpBox::fillEnvHistoryGroupBox (const Mantid::Kernel::EnvironmentHistory & envHist)
Definition at line 431 of file AlgorithmHistoryWindow.cpp.
References Mantid::Kernel::EnvironmentHistory::frameworkVersion(), getfrmworkVersionEdit(), getosNameEdit(), getosVersionEdit(), Mantid::Kernel::EnvironmentHistory::osName(), and Mantid::Kernel::EnvironmentHistory::osVersion().
Referenced by AlgorithmHistoryWindow::createEnvHistGrpBox().
getfrmworkVersionEdit()
QLineEdit * AlgEnvHistoryGrpBox::getfrmworkVersionEdit () const inline
Definition at line 121 of file AlgorithmHistoryWindow.h.
References m_frmwkVersnEdit.
Referenced by fillEnvHistoryGroupBox().
getosNameEdit()
QLineEdit * AlgEnvHistoryGrpBox::getosNameEdit () const inline
Definition at line 119 of file AlgorithmHistoryWindow.h.
References m_osNameEdit.
Referenced by fillEnvHistoryGroupBox().
getosVersionEdit()
QLineEdit * AlgEnvHistoryGrpBox::getosVersionEdit () const inline
Definition at line 120 of file AlgorithmHistoryWindow.h.
References m_osVersionEdit.
Referenced by fillEnvHistoryGroupBox().
Member Data Documentation
m_frmwkVersnEdit
QLineEdit* AlgEnvHistoryGrpBox::m_frmwkVersnEdit private
Definition at line 130 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), getfrmworkVersionEdit(), and ~AlgEnvHistoryGrpBox().
m_frmworkVersionLabel
QLabel* AlgEnvHistoryGrpBox::m_frmworkVersionLabel private
Definition at line 129 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), and ~AlgEnvHistoryGrpBox().
m_osNameEdit
QLineEdit* AlgEnvHistoryGrpBox::m_osNameEdit private
Definition at line 126 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), getosNameEdit(), and ~AlgEnvHistoryGrpBox().
m_osNameLabel
QLabel* AlgEnvHistoryGrpBox::m_osNameLabel private
Definition at line 125 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), and ~AlgEnvHistoryGrpBox().
m_osVersionEdit
QLineEdit* AlgEnvHistoryGrpBox::m_osVersionEdit private
Definition at line 128 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), getosVersionEdit(), and ~AlgEnvHistoryGrpBox().
m_osVersionLabel
QLabel* AlgEnvHistoryGrpBox::m_osVersionLabel private
Definition at line 127 of file AlgorithmHistoryWindow.h.
Referenced by AlgEnvHistoryGrpBox(), and ~AlgEnvHistoryGrpBox().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmHistoryWindow.h
qt/widgets/common/src/AlgorithmHistoryWindow.cpp