Mantid: ICat4::ns1__dataset Class Reference
ICat4::ns1__dataset Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__dataset ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
bool complete
std::vector< ns1__dataCollectionDataset * > dataCollectionDatasets
std::vector< ns1__datafile * > datafiles
std::string * description
std::string * doi
time_t * endDate
ns1__investigation * investigation
std::string * location
std::string * name
std::vector< ns1__datasetParameter * > parameters
ns1__sample * sample
time_t * startDate
ns1__datasetType * type
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1539 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__dataset()
ICat4::ns1__dataset::ns1__dataset () inline
Definition at line 1563 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__dataset::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16583 of file ICat4C.cpp.
References ICat4::soap_default_bool(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataCollectionDataset(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datafile(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__datasetParameter().
Referenced by ICat4::soap_in_ns1__dataset(), ICat4::soap_new_req_ns1__dataset(), and ICat4::soap_new_set_ns1__dataset().
soap_get()
void * ICat4::ns1__dataset::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16838 of file ICat4C.cpp.
References ICat4::soap_get_ns1__dataset().
soap_in()
void * ICat4::ns1__dataset::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16674 of file ICat4C.cpp.
References ICat4::soap_in_ns1__dataset().
Referenced by ICat4::soap_in_ns1__dataset().
soap_out()
int ICat4::ns1__dataset::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16624 of file ICat4C.cpp.
References ICat4::soap_out_ns1__dataset().
soap_put()
int ICat4::ns1__dataset::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16831 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__dataset.
soap_serialize()
void ICat4::ns1__dataset::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16603 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__datasetType(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTons1__sample(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataCollectionDataset(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datafile(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datasetParameter().
soap_type()
int ICat4::ns1__dataset::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1556 of file ICat4Stub.h.
Member Data Documentation
complete
bool ICat4::ns1__dataset::complete
Definition at line 1541 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
dataCollectionDatasets
std::vector<ns1__dataCollectionDataset *> ICat4::ns1__dataset::dataCollectionDatasets
Definition at line 1542 of file ICat4Stub.h.
datafiles
std::vector<ns1__datafile *> ICat4::ns1__dataset::datafiles
Definition at line 1544 of file ICat4Stub.h.
description
std::string* ICat4::ns1__dataset::description
Definition at line 1545 of file ICat4Stub.h.
doi
std::string* ICat4::ns1__dataset::doi
Definition at line 1546 of file ICat4Stub.h.
endDate
time_t* ICat4::ns1__dataset::endDate
Definition at line 1547 of file ICat4Stub.h.
investigation
ns1__investigation* ICat4::ns1__dataset::investigation
Definition at line 1548 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
location
std::string* ICat4::ns1__dataset::location
Definition at line 1549 of file ICat4Stub.h.
name
std::string* ICat4::ns1__dataset::name
Definition at line 1550 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
parameters
std::vector<ns1__datasetParameter *> ICat4::ns1__dataset::parameters
Definition at line 1551 of file ICat4Stub.h.
sample
ns1__sample* ICat4::ns1__dataset::sample
Definition at line 1552 of file ICat4Stub.h.
startDate
time_t* ICat4::ns1__dataset::startDate
Definition at line 1553 of file ICat4Stub.h.
type
ns1__datasetType* ICat4::ns1__dataset::type
Definition at line 1554 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp