Mantid: Mantid::DataHandling::ANSTO::ProgressTracker Class Reference
Mantid::DataHandling::ANSTO::ProgressTracker Class Reference
helper class to keep track of progress
#include <LoadANSTOHelper.h>
Public Member Functions
void complete ()
ProgressTracker (API::Progress &progBar, const char *msg, int64_t target, size_t count)
void setTarget (int64_t target)
void update (int64_t position)
~ProgressTracker ()
Private Attributes
size_t m_count
const std::string m_msg
int64_t m_next
API::Progress & m_progBar
int64_t m_step
Detailed Description
helper class to keep track of progress
Definition at line 42 of file LoadANSTOHelper.h.
Constructor & Destructor Documentation
ProgressTracker()
Mantid::DataHandling::ANSTO::ProgressTracker::ProgressTracker (API::Progress & progBar, const char * msg, int64_t target, size_t count)
Definition at line 39 of file LoadANSTOHelper.cpp.
References Mantid::API::Progress::doReport(), m_msg, and m_progBar.
~ProgressTracker()
Mantid::DataHandling::ANSTO::ProgressTracker::~ProgressTracker ()
Definition at line 44 of file LoadANSTOHelper.cpp.
References complete().
Member Function Documentation
complete()
void Mantid::DataHandling::ANSTO::ProgressTracker::complete ()
Definition at line 64 of file LoadANSTOHelper.cpp.
References m_count, m_msg, m_progBar, and Mantid::Kernel::ProgressBase::reportIncrement().
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::DataHandling::LoadEMU< FD >::prepareEventStorage(), Mantid::DataHandling::LoadPLN::prepareEventStorage(), and ~ProgressTracker().
setTarget()
void Mantid::DataHandling::ANSTO::ProgressTracker::setTarget (int64_t target)
Definition at line 71 of file LoadANSTOHelper.cpp.
References m_count, m_next, and m_step.
Referenced by Mantid::DataHandling::ANSTO::Anxs::ReadEventData().
update()
void Mantid::DataHandling::ANSTO::ProgressTracker::update (int64_t position)
Definition at line 45 of file LoadANSTOHelper.cpp.
References m_count, m_msg, m_next, m_progBar, m_step, position, and Mantid::Kernel::ProgressBase::report().
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::DataHandling::LoadBBY::loadEvents(), Mantid::DataHandling::LoadEMU< FD >::prepareEventStorage(), Mantid::DataHandling::LoadPLN::prepareEventStorage(), and Mantid::DataHandling::ANSTO::Anxs::ReadEventData().
Member Data Documentation
m_count
size_t Mantid::DataHandling::ANSTO::ProgressTracker::m_count private
Definition at line 46 of file LoadANSTOHelper.h.
Referenced by complete(), setTarget(), and update().
m_msg
const std::string Mantid::DataHandling::ANSTO::ProgressTracker::m_msg private
Definition at line 45 of file LoadANSTOHelper.h.
Referenced by complete(), ProgressTracker(), and update().
m_next
int64_t Mantid::DataHandling::ANSTO::ProgressTracker::m_next private
Definition at line 48 of file LoadANSTOHelper.h.
Referenced by setTarget(), and update().
m_progBar
API::Progress& Mantid::DataHandling::ANSTO::ProgressTracker::m_progBar private
Definition at line 50 of file LoadANSTOHelper.h.
Referenced by complete(), ProgressTracker(), and update().
m_step
int64_t Mantid::DataHandling::ANSTO::ProgressTracker::m_step private
Definition at line 47 of file LoadANSTOHelper.h.
Referenced by setTarget(), and update().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadANSTOHelper.h
Framework/DataHandling/src/LoadANSTOHelper.cpp