Mantid: Mantid::DataHandling::CompressEventAccumulator Class Reference
Mantid::DataHandling::CompressEventAccumulator Class Reference abstract
CompressEventAccumulator : TODO: DESCRIPTION.
#include <CompressEventAccumulator.h>
Public Member Functions
virtual void addEvent (const float tof)=0
CompressEventAccumulator (std::shared_ptr< std::vector< double > > histogram_bin_edges, const double divisor, CompressBinningMode bin_mode)
virtual void createWeightedEvents (std::vector< Mantid::DataObjects::WeightedEventNoTime > *raw_events) const =0
virtual DataObjects::EventSortType getSortType () const =0
std::size_t numberHistBins () const
virtual double totalWeight () const =0
virtual ~CompressEventAccumulator ()=default
Protected Member Functions
std::optional< size_t > findBin (const float tof) const
template<typename INT_TYPE >
double getBinCenter (const INT_TYPE bin) const
Protected Attributes
const std::shared_ptr< std::vector< double > > m_histogram_edges
shared pointer for the histogram bin boundaries
bool m_initialized
track whether this has allocated the "big" memory objects
Private Attributes
double m_divisor
keep track if the m_tof is already sorted
std::optional< size_t >(* m_findBin)(const MantidVec &, const double, const double, const double, const bool)
function pointer on how to find the bin boundaries
double m_offset
Detailed Description
CompressEventAccumulator : TODO: DESCRIPTION.
Definition at line 21 of file CompressEventAccumulator.h.
Constructor & Destructor Documentation
CompressEventAccumulator()
Mantid::DataHandling::CompressEventAccumulator::CompressEventAccumulator (std::shared_ptr< std::vector< double > > histogram_bin_edges, const double divisor, CompressBinningMode bin_mode)
Definition at line 18 of file CompressEventAccumulator.cpp.
References Mantid::DataObjects::EventList::findLinearBin(), Mantid::DataObjects::EventList::findLogBin(), Mantid::DataHandling::LINEAR, Mantid::DataHandling::LOGARITHMIC, m_divisor, m_findBin, m_histogram_edges, and m_offset.
~CompressEventAccumulator()
virtual Mantid::DataHandling::CompressEventAccumulator::~CompressEventAccumulator () virtual default
Member Function Documentation
addEvent()
virtual void Mantid::DataHandling::CompressEventAccumulator::addEvent (const float tof) pure virtual
createWeightedEvents()
virtual void Mantid::DataHandling::CompressEventAccumulator::createWeightedEvents (std::vector< Mantid::DataObjects::WeightedEventNoTime > * raw_events) const pure virtual
findBin()
std::optional< size_t > Mantid::DataHandling::CompressEventAccumulator::findBin (const float tof) const protected
Definition at line 46 of file CompressEventAccumulator.cpp.
References m_divisor, m_findBin, m_histogram_edges, and m_offset.
getBinCenter()
template<typename INT_TYPE > double Mantid::DataHandling::CompressEventAccumulator::getBinCenter (const INT_TYPE bin) const protected
Definition at line 40 of file CompressEventAccumulator.cpp.
References m_histogram_edges.
getSortType()
virtual DataObjects::EventSortType Mantid::DataHandling::CompressEventAccumulator::getSortType () const pure virtual
numberHistBins()
std::size_t Mantid::DataHandling::CompressEventAccumulator::numberHistBins () const
Definition at line 38 of file CompressEventAccumulator.cpp.
References m_histogram_edges.
totalWeight()
virtual double Mantid::DataHandling::CompressEventAccumulator::totalWeight () const pure virtual
Member Data Documentation
m_divisor
double Mantid::DataHandling::CompressEventAccumulator::m_divisor private
keep track if the m_tof is already sorted
Definition at line 45 of file CompressEventAccumulator.h.
Referenced by CompressEventAccumulator(), and findBin().
m_findBin
std::optional< size_t >(* Mantid::DataHandling::CompressEventAccumulator::m_findBin) (const MantidVec &, const double, const double, const double, const bool) private
function pointer on how to find the bin boundaries
Definition at line 46 of file CompressEventAccumulator.h.
Referenced by CompressEventAccumulator(), and findBin().
m_histogram_edges
const std::shared_ptr<std::vector<double> > Mantid::DataHandling::CompressEventAccumulator::m_histogram_edges protected
shared pointer for the histogram bin boundaries
Definition at line 39 of file CompressEventAccumulator.h.
Referenced by CompressEventAccumulator(), findBin(), getBinCenter(), and numberHistBins().
m_initialized
bool Mantid::DataHandling::CompressEventAccumulator::m_initialized protected
track whether this has allocated the "big" memory objects
Definition at line 52 of file CompressEventAccumulator.h.
m_offset
double Mantid::DataHandling::CompressEventAccumulator::m_offset private
Definition at line 46 of file CompressEventAccumulator.h.
Referenced by CompressEventAccumulator(), and findBin().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/CompressEventAccumulator.h
Framework/DataHandling/src/CompressEventAccumulator.cpp