Mantid: Mantid::DataHandling::LoadMuonStrategy Class Reference
Mantid::DataHandling::LoadMuonStrategy Class Reference abstract
#include <LoadMuonStrategy.h>
Public Member Functions
virtual void applyTimeZeroCorrection ()=0
virtual API::Workspace_sptr getTimeZeroTable ()=0
virtual API::Workspace_sptr loadDeadTimeTable () const =0
virtual API::Workspace_sptr loadDetectorGrouping () const =0
virtual void loadGoodFrames ()=0
virtual void loadMuonLogData ()=0
LoadMuonStrategy (Kernel::Logger &g_log, std::string filename, LoadMuonNexusV2NexusHelper &nexusLoader)
virtual ~LoadMuonStrategy ()=default
Protected Member Functions
DataObjects::TableWorkspace_sptr createDeadTimeTable (const std::vector< detid_t > &detectorsLoaded, const std::vector< double > &deadTimes) const
Creates the deadtime table for the loaded detectors .
DataObjects::TableWorkspace_sptr createDetectorGroupingTable (const std::vector< detid_t > &specToLoad, const std::vector< detid_t > &grouping) const
Creates Detector Grouping Table .
std::vector< detid_t > getLoadedDetectorsFromWorkspace (const DataObjects::Workspace2D &localWorkspace) const
Determines the detectors loaded in the input workspace.
API::Workspace_sptr loadDefaultDetectorGrouping (const DataObjects::Workspace2D &localWorkspace) const
Loads default detector grouping, if this isn't present return dummy grouping.
Protected Attributes
const std::string m_filename
Kernel::Logger & m_logger
LoadMuonNexusV2NexusHelper & m_nexusLoader
Detailed Description
Definition at line 22 of file LoadMuonStrategy.h.
Constructor & Destructor Documentation
LoadMuonStrategy()
Mantid::DataHandling::LoadMuonStrategy::LoadMuonStrategy (Kernel::Logger & g_log, std::string filename, LoadMuonNexusV2NexusHelper & nexusLoader)
Definition at line 41 of file LoadMuonStrategy.cpp.
~LoadMuonStrategy()
virtual Mantid::DataHandling::LoadMuonStrategy::~LoadMuonStrategy () virtual default
Member Function Documentation
applyTimeZeroCorrection()
virtual void Mantid::DataHandling::LoadMuonStrategy::applyTimeZeroCorrection () pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
createDeadTimeTable()
DataObjects::TableWorkspace_sptr Mantid::DataHandling::LoadMuonStrategy::createDeadTimeTable (const std::vector< detid_t > & detectorsLoaded, const std::vector< double > & deadTimes) const protected
Creates the deadtime table for the loaded detectors .
Parameters
detectorsLoaded :: Vector containing the list of detectorsLoaded
deadTimes :: Vector containing corresponding deadtime
Returns
Deadtime table created using the input data
Definition at line 122 of file LoadMuonStrategy.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDeadTimeTable(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDeadTimeTable().
createDetectorGroupingTable()
DataObjects::TableWorkspace_sptr Mantid::DataHandling::LoadMuonStrategy::createDetectorGroupingTable (const std::vector< detid_t > & detectorsLoaded, const std::vector< detid_t > & grouping) const protected
Creates Detector Grouping Table .
Parameters
detectorsLoaded :: Vector containing the list of detectorsLoaded
grouping :: Vector containing corresponding grouping
Returns
Detector Grouping Table create using the data
Definition at line 96 of file LoadMuonStrategy.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping().
getLoadedDetectorsFromWorkspace()
std::vector< detid_t > Mantid::DataHandling::LoadMuonStrategy::getLoadedDetectorsFromWorkspace (const DataObjects::Workspace2D & localWorkspace) const protected
Determines the detectors loaded in the input workspace.
Returns
:: Vector containing loaded detectors
Definition at line 77 of file LoadMuonStrategy.cpp.
References Mantid::API::ISpectrum::getDetectorIDs(), Mantid::DataObjects::Workspace2D::getNumberHistograms(), and Mantid::DataObjects::Workspace2D::getSpectrum().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getLoadedDetectors(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getLoadedDetectors().
getTimeZeroTable()
virtual API::Workspace_sptr Mantid::DataHandling::LoadMuonStrategy::getTimeZeroTable () pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
loadDeadTimeTable()
virtual API::Workspace_sptr Mantid::DataHandling::LoadMuonStrategy::loadDeadTimeTable () const pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
loadDefaultDetectorGrouping()
API::Workspace_sptr Mantid::DataHandling::LoadMuonStrategy::loadDefaultDetectorGrouping (const DataObjects::Workspace2D & localWorkspace) const protected
Loads default detector grouping, if this isn't present return dummy grouping.
Returns
:: Grouping table
Definition at line 50 of file LoadMuonStrategy.cpp.
References Mantid::API::GroupingLoader::getDummyGrouping(), Mantid::API::GroupingLoader::getGroupingFromIDF(), Mantid::API::ExperimentInfo::getInstrument(), Mantid::API::LogManager::getLogData(), Mantid::DataObjects::Workspace2D::getNumberHistograms(), Mantid::API::ExperimentInfo::run(), std::to_string(), and Mantid::Kernel::Property::value().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping().
loadDetectorGrouping()
virtual API::Workspace_sptr Mantid::DataHandling::LoadMuonStrategy::loadDetectorGrouping () const pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
loadGoodFrames()
virtual void Mantid::DataHandling::LoadMuonStrategy::loadGoodFrames () pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
loadMuonLogData()
virtual void Mantid::DataHandling::LoadMuonStrategy::loadMuonLogData () pure virtual
Implemented in Mantid::DataHandling::MultiPeriodLoadMuonStrategy, and Mantid::DataHandling::SinglePeriodLoadMuonStrategy.
Member Data Documentation
m_filename
const std::string Mantid::DataHandling::LoadMuonStrategy::m_filename protected
Definition at line 55 of file LoadMuonStrategy.h.
m_logger
Kernel::Logger& Mantid::DataHandling::LoadMuonStrategy::m_logger protected
Definition at line 53 of file LoadMuonStrategy.h.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping().
m_nexusLoader
LoadMuonNexusV2NexusHelper& Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader protected
Definition at line 57 of file LoadMuonStrategy.h.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::applyTimeZeroCorrection(), Mantid::DataHandling::SinglePeriodLoadMuonStrategy::applyTimeZeroCorrection(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getTimeZeroTable(), Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getTimeZeroTable(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDeadTimeTable(), Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDeadTimeTable(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping(), Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadGoodFrames(), Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadGoodFrames(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadMuonLogData(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadMuonLogData().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadMuonStrategy.h
Framework/DataHandling/src/LoadMuonStrategy.cpp