Mantid: ICat4::ns1__parameterType Class Reference
ICat4::ns1__parameterType Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__parameterType ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
bool applicableToDataCollection
bool applicableToDatafile
bool applicableToDataset
bool applicableToInvestigation
bool applicableToSample
std::vector< ns1__dataCollectionParameter * > dataCollectionParameters
std::vector< ns1__datafileParameter * > datafileParameters
std::vector< ns1__datasetParameter * > datasetParameters
std::string * description
bool enforced
ns1__facility * facility
std::vector< ns1__investigationParameter * > investigationParameters
double * maximumNumericValue
double * minimumNumericValue
std::string * name
std::vector< class ns1__permissibleStringValue * > permissibleStringValues
std::vector< ns1__sampleParameter * > sampleParameters
std::string * units
std::string * unitsFullName
enum ns1__parameterValueType * valueType
bool verified
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1977 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__parameterType()
ICat4::ns1__parameterType::ns1__parameterType () inline
Definition at line 2011 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__parameterType::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12090 of file ICat4C.cpp.
References ICat4::soap_default_bool(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataCollectionParameter(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datafileParameter(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datasetParameter(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationParameter(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__permissibleStringValue(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__sampleParameter().
Referenced by ICat4::soap_in_ns1__parameterType(), ICat4::soap_new_req_ns1__parameterType(), and ICat4::soap_new_set_ns1__parameterType().
soap_get()
void * ICat4::ns1__parameterType::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12435 of file ICat4C.cpp.
References ICat4::soap_get_ns1__parameterType().
soap_in()
void * ICat4::ns1__parameterType::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12219 of file ICat4C.cpp.
References ICat4::soap_in_ns1__parameterType().
Referenced by ICat4::soap_in_ns1__parameterType().
soap_out()
int ICat4::ns1__parameterType::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12148 of file ICat4C.cpp.
References ICat4::soap_out_ns1__parameterType().
soap_put()
int ICat4::ns1__parameterType::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12428 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__parameterType.
soap_serialize()
void ICat4::ns1__parameterType::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 12121 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTodouble(), ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTons1__parameterValueType(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataCollectionParameter(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datafileParameter(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datasetParameter(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationParameter(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__permissibleStringValue(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__sampleParameter().
soap_type()
int ICat4::ns1__parameterType::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2004 of file ICat4Stub.h.
Member Data Documentation
applicableToDataCollection
bool ICat4::ns1__parameterType::applicableToDataCollection
Definition at line 1979 of file ICat4Stub.h.
applicableToDatafile
bool ICat4::ns1__parameterType::applicableToDatafile
Definition at line 1980 of file ICat4Stub.h.
applicableToDataset
bool ICat4::ns1__parameterType::applicableToDataset
Definition at line 1981 of file ICat4Stub.h.
applicableToInvestigation
bool ICat4::ns1__parameterType::applicableToInvestigation
Definition at line 1982 of file ICat4Stub.h.
applicableToSample
bool ICat4::ns1__parameterType::applicableToSample
Definition at line 1983 of file ICat4Stub.h.
dataCollectionParameters
std::vector<ns1__dataCollectionParameter *> ICat4::ns1__parameterType::dataCollectionParameters
Definition at line 1984 of file ICat4Stub.h.
datafileParameters
std::vector<ns1__datafileParameter *> ICat4::ns1__parameterType::datafileParameters
Definition at line 1986 of file ICat4Stub.h.
datasetParameters
std::vector<ns1__datasetParameter *> ICat4::ns1__parameterType::datasetParameters
Definition at line 1987 of file ICat4Stub.h.
description
std::string* ICat4::ns1__parameterType::description
Definition at line 1988 of file ICat4Stub.h.
enforced
bool ICat4::ns1__parameterType::enforced
Definition at line 1989 of file ICat4Stub.h.
facility
ns1__facility* ICat4::ns1__parameterType::facility
Definition at line 1990 of file ICat4Stub.h.
investigationParameters
std::vector<ns1__investigationParameter *> ICat4::ns1__parameterType::investigationParameters
Definition at line 1991 of file ICat4Stub.h.
maximumNumericValue
double* ICat4::ns1__parameterType::maximumNumericValue
Definition at line 1993 of file ICat4Stub.h.
minimumNumericValue
double* ICat4::ns1__parameterType::minimumNumericValue
Definition at line 1994 of file ICat4Stub.h.
name
std::string* ICat4::ns1__parameterType::name
Definition at line 1995 of file ICat4Stub.h.
permissibleStringValues
std::vector<class ns1__permissibleStringValue *> ICat4::ns1__parameterType::permissibleStringValues
Definition at line 1996 of file ICat4Stub.h.
sampleParameters
std::vector<ns1__sampleParameter *> ICat4::ns1__parameterType::sampleParameters
Definition at line 1998 of file ICat4Stub.h.
units
std::string* ICat4::ns1__parameterType::units
Definition at line 1999 of file ICat4Stub.h.
unitsFullName
std::string* ICat4::ns1__parameterType::unitsFullName
Definition at line 2000 of file ICat4Stub.h.
valueType
enum ns1__parameterValueType* ICat4::ns1__parameterType::valueType
Definition at line 2001 of file ICat4Stub.h.
verified
bool ICat4::ns1__parameterType::verified
Definition at line 2002 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp