Mantid: MantidQt::MantidWidgets::FitOptionsBrowser Class Reference
MantidQt::MantidWidgets::FitOptionsBrowser Class Reference
Class FitOptionsBrowser implements QtPropertyBrowser to display and set properties of Fit algorithm (excluding Function and Workspace)
#include <FitOptionsBrowser.h>
Signals
void changedToSequentialFitting ()
void changedToSimultaneousFitting ()
void doublePropertyChanged (const QString &propertyName)
Public Member Functions
bool addPropertyToBlacklist (const QString &)
Adds the property with the given name to a blacklist of properties to hide.
void copyPropertiesToAlgorithm (Mantid::API::IAlgorithm &fit) const
Copy values of the properties to an algorithm.
FitOptionsBrowser (QWidget *parent=nullptr, FittingMode fitType=FittingMode::SIMULTANEOUS)
Constructor.
FittingMode getCurrentFittingType () const
Get the current fitting type, ie which algorithm to use: Simultaneous for Fit and Sequential for PlotPeakByLogValue.
QString getParameterToPlot () const
Get name of a function parameter to plot against LogValue after sequential fitting.
QString getProperty (const QString &name) const
Get a string representation of a Fit's property value.
void loadSettings (const QSettings &settings)
Load property values from settings.
void lockCurrentFittingType (FittingMode fitType)
Lock the browser in a particular fitting type state.
void saveSettings (QSettings &settings) const
Save the last property values in settings.
void setCurrentFittingType (FittingMode fitType)
Set the current fitting type, ie which algorithm to use: Simultaneous for Fit and Sequential for PlotPeakByLogValue.
void setLogNames (const QStringList &logNames)
Define log names to use with the LogValue property.
void setParameterNamesForPlotting (const QStringList &parNames)
Define names of function parameters that can be plotted against the LogValue.
void setProperty (const QString &name, const QString &value)
Set a new value to a Fit's property.
void unlockCurrentFittingType ()
Make the fitting type changeable again.
~FitOptionsBrowser ()
Protected Member Functions
QtProperty * addDoubleProperty (const QString &propertyName)
Declares a property of type double, inserting it in the QMap attributes.
void displayProperty (const QString &propertyName, bool show=true)
Show or hide in the browser a supported property.
void displaySequentialFitProperties ()
Show sequential fit (PlotPeakByLogValue) properties and hide the others.
Private Types
using GetterType = QString(FitOptionsBrowser::*)(QtProperty *) const
using SetterType = void(FitOptionsBrowser::*)(QtProperty *, const QString &)
Private Slots
void doubleChanged (QtProperty *property)
pass the signal emitted by m_doubleManager
void enumChanged (QtProperty *)
Update the browser when an enum property changes.
Private Member Functions
void addProperty (const QString &name, QtProperty *prop, QString(FitOptionsBrowser::*getter)(QtProperty *) const, void(FitOptionsBrowser::*setter)(QtProperty *, const QString &))
void createBrowser ()
Create the Qt property browser and set up property managers.
void createCommonProperties ()
void createProperties ()
Create browser's QtProperties.
QtProperty * createPropertyProperty (Mantid::Kernel::Property *prop)
Create a QtProperty for an Algorithm Property and attach it to the correct manager.
void createSequentialFitProperties ()
void createSimultaneousFitProperties ()
void displayNormalFitProperties ()
Show normal Fit properties and hide the others.
QString getBoolProperty (QtProperty *) const
Get the value of a bool algorithm property.
QString getDoubleProperty (QtProperty *) const
Get the value of a double algorithm property.
QString getIntProperty (QtProperty *) const
Get the value of an integer algorithm property.
QString getMinimizer (QtProperty *) const
Get the value of the Minimizer property.
QString getStringEnumProperty (QtProperty *) const
Get the value of a string algorithm property with predefined set of values.
QString getStringProperty (QtProperty *) const
Get the value of a string algorithm property.
void initFittingTypeProp ()
Initialize the fitting type property.
void removeProperty (const QString &name)
Remove a property previously added with addProperty (If property doesn't exist, does nothing).
void setBoolProperty (QtProperty *, const QString &)
Set a new value of a bool algorithm property.
void setDoubleProperty (QtProperty *, const QString &)
Set a new value of a double algorithm property.
void setIntProperty (QtProperty *, const QString &)
Set a new value of an integer algorithm property.
void setMinimizer (QtProperty *, const QString &)
Set new value to the Minimizer property.
void setPropertyEnumValues (QtProperty *prop, const QStringList &values)
Set values for an enum property.
void setStringEnumProperty (QtProperty *, const QString &)
Set a new value of a string algorithm property with predefined set of values.
void setStringProperty (QtProperty *, const QString &)
Set a new value of a string algorithm property.
void switchFitType ()
Switch the current fit type according to the value in the FitType property.
void updateMinimizer ()
Update the browser when minimizer changes.
Private Attributes
QList< QtProperty * > m_blacklist
QtBoolPropertyManager * m_boolManager
Manager for bool properties.
QtTreePropertyBrowser * m_browser
Qt property browser which displays properties.
QtProperty * m_costFunction
CostFunction property.
int m_decimals
Precision of doubles in m_doubleManager.
QtDoublePropertyManager * m_doubleManager
Manager for double properties.
QtEnumPropertyManager * m_enumManager
Manager for the string list properties.
QtProperty * m_evaluationType
EvaluationType property.
FittingMode m_fittingType
The Fitting Type.
QtProperty * m_fittingTypeProp
FitType property.
QMap< QtProperty const *, GetterType > m_getters
Store for the properties getter methods.
QtGroupPropertyManager * m_groupManager
Manager for groups of properties.
QtProperty * m_ignoreInvalidData
IgnoreInvalidData property.
QtIntPropertyManager * m_intManager
Manager for int properties.
QtProperty * m_logValue
LogValue property.
QtProperty * m_maxIterations
MaxIterations property.
QtProperty * m_minimizer
Minimizer property.
QtProperty * m_minimizerGroup
Minimizer group property.
QtProperty * m_output
Output property.
QtProperty * m_outputWorkspace
OutputWorkspace property.
QtProperty * m_peakRadius
Peak radius property.
QtProperty * m_plotParameter
Property for a name of a parameter to plot against LogValue.
QtProperty * m_plotPeakByLogValueFitType
PlotPeakByLogValue FitType property.
QMap< QString, QtProperty * > m_propertyNameMap
Maps algorithm property name to the QtProperty.
QList< QtProperty * > m_sequentialProperties
Store special properties of the sequential Fit.
QMap< QtProperty const *, SetterType > m_setters
Store for the properties setter methods.
QList< QtProperty * > m_simultaneousProperties
Store special properties of the normal Fit.
QtStringPropertyManager * m_stringManager
Manager for string properties.
Detailed Description
Class FitOptionsBrowser implements QtPropertyBrowser to display and set properties of Fit algorithm (excluding Function and Workspace)
Definition at line 43 of file FitOptionsBrowser.h.
Member Typedef Documentation
GetterType
using MantidQt::MantidWidgets::FitOptionsBrowser::GetterType = QString (FitOptionsBrowser::*)(QtProperty *) const private
Definition at line 166 of file FitOptionsBrowser.h.
SetterType
using MantidQt::MantidWidgets::FitOptionsBrowser::SetterType = void (FitOptionsBrowser::*)(QtProperty *, const QString &) private
Definition at line 165 of file FitOptionsBrowser.h.
Constructor & Destructor Documentation
FitOptionsBrowser()
MantidQt::MantidWidgets::FitOptionsBrowser::FitOptionsBrowser (QWidget * parent = nullptr, FittingMode fitType = FittingMode::SIMULTANEOUS)
Constructor.
Parameters
parent :: The parent widget.
fitType :: The type of the underlying fitting algorithm.
Definition at line 51 of file FitOptionsBrowser.cpp.
References createBrowser(), createProperties(), and m_browser.
~FitOptionsBrowser()
MantidQt::MantidWidgets::FitOptionsBrowser::~FitOptionsBrowser ()
Definition at line 62 of file FitOptionsBrowser.cpp.
References m_boolManager, m_browser, m_doubleManager, m_enumManager, m_intManager, and m_stringManager.
Member Function Documentation
addDoubleProperty()
QtProperty * MantidQt::MantidWidgets::FitOptionsBrowser::addDoubleProperty (const QString & propertyName) protected
Declares a property of type double, inserting it in the QMap attributes.
Note: It does not add it to the browser. Use displayProperty() for this.
Exceptions
std::runtime_error if property already declared
Returns
a raw pointer to the created property.
Definition at line 754 of file FitOptionsBrowser.cpp.
References addProperty(), getDoubleProperty(), m_decimals, m_doubleManager, m_propertyNameMap, and setDoubleProperty().
Referenced by createPropertyProperty().
addProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::addProperty (const QString & name, QtProperty * prop, QString(FitOptionsBrowser::*)(QtProperty *) const getter, void(FitOptionsBrowser::*)(QtProperty *, const QString &) setter) private
Definition at line 302 of file FitOptionsBrowser.cpp.
References m_getters, m_propertyNameMap, m_setters, and name.
Referenced by addDoubleProperty(), createCommonProperties(), createSequentialFitProperties(), and createSimultaneousFitProperties().
addPropertyToBlacklist()
bool MantidQt::MantidWidgets::FitOptionsBrowser::addPropertyToBlacklist (const QString & name)
Adds the property with the given name to a blacklist of properties to hide.
Definition at line 790 of file FitOptionsBrowser.cpp.
References m_browser, m_propertyNameMap, m_sequentialProperties, m_simultaneousProperties, and name.
changedToSequentialFitting
void MantidQt::MantidWidgets::FitOptionsBrowser::changedToSequentialFitting () signal
Referenced by displaySequentialFitProperties().
changedToSimultaneousFitting
void MantidQt::MantidWidgets::FitOptionsBrowser::changedToSimultaneousFitting () signal
Referenced by displayNormalFitProperties().
copyPropertiesToAlgorithm()
void MantidQt::MantidWidgets::FitOptionsBrowser::copyPropertiesToAlgorithm (Mantid::API::IAlgorithm & fit) const
Copy values of the properties to an algorithm.
Parameters
fit :: An instance of the Fit algorithm.
Definition at line 458 of file FitOptionsBrowser.cpp.
References Mantid::Kernel::IPropertyManager::existsProperty(), m_getters, m_propertyNameMap, and Mantid::Kernel::IPropertyManager::setPropertyValue().
createBrowser()
void MantidQt::MantidWidgets::FitOptionsBrowser::createBrowser () private
Create the Qt property browser and set up property managers.
Definition at line 73 of file FitOptionsBrowser.cpp.
References doubleChanged(), enumChanged(), m_boolManager, m_browser, m_doubleManager, m_enumManager, m_groupManager, m_intManager, and m_stringManager.
Referenced by FitOptionsBrowser().
createCommonProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::createCommonProperties () private
Definition at line 139 of file FitOptionsBrowser.cpp.
References addProperty(), getBoolProperty(), getIntProperty(), getMinimizer(), getStringEnumProperty(), m_boolManager, m_browser, m_costFunction, m_enumManager, m_evaluationType, m_groupManager, m_ignoreInvalidData, m_intManager, m_maxIterations, m_minimizer, m_minimizerGroup, m_peakRadius, setBoolProperty(), setIntProperty(), setMinimizer(), and setStringEnumProperty().
Referenced by createProperties().
createProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::createProperties () private
Create browser's QtProperties.
Definition at line 127 of file FitOptionsBrowser.cpp.
References createCommonProperties(), createSequentialFitProperties(), createSimultaneousFitProperties(), initFittingTypeProp(), m_fittingType, MantidQt::MantidWidgets::SEQUENTIAL, MantidQt::MantidWidgets::SEQUENTIAL_AND_SIMULTANEOUS, MantidQt::MantidWidgets::SIMULTANEOUS, and switchFitType().
Referenced by FitOptionsBrowser().
createPropertyProperty()
QtProperty * MantidQt::MantidWidgets::FitOptionsBrowser::createPropertyProperty (Mantid::Kernel::Property * property) private
Create a QtProperty for an Algorithm Property and attach it to the correct manager.
Parameters
property :: An algorithm property.
Definition at line 405 of file FitOptionsBrowser.cpp.
References addDoubleProperty(), Mantid::Kernel::Property::documentation(), m_boolManager, m_doubleManager, m_intManager, m_stringManager, Mantid::Kernel::Property::name(), and Mantid::Kernel::Property::value().
Referenced by updateMinimizer().
createSequentialFitProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::createSequentialFitProperties () private
Definition at line 232 of file FitOptionsBrowser.cpp.
References addProperty(), getBoolProperty(), getStringEnumProperty(), getStringProperty(), m_boolManager, m_enumManager, m_logValue, m_outputWorkspace, m_plotParameter, m_plotPeakByLogValueFitType, m_sequentialProperties, m_stringManager, setBoolProperty(), setStringEnumProperty(), and setStringProperty().
Referenced by createProperties().
createSimultaneousFitProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::createSimultaneousFitProperties () private
Definition at line 222 of file FitOptionsBrowser.cpp.
References addProperty(), getStringProperty(), m_browser, m_output, m_simultaneousProperties, m_stringManager, and setStringProperty().
Referenced by createProperties().
displayNormalFitProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::displayNormalFitProperties () private
Show normal Fit properties and hide the others.
Definition at line 390 of file FitOptionsBrowser.cpp.
References changedToSimultaneousFitting(), m_browser, m_sequentialProperties, and m_simultaneousProperties.
Referenced by switchFitType().
displayProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::displayProperty (const QString & propertyName, bool show = true) protected
Show or hide in the browser a supported property.
Parameters
propertyName name of the existing property
show toggles the visibility of the property on/off
Precondition
if property is to be shown, property should not have been previously added to the browser
if property is to be hidden, property should not have been previously removed from the browser
Definition at line 775 of file FitOptionsBrowser.cpp.
References m_browser, and m_propertyNameMap.
displaySequentialFitProperties()
void MantidQt::MantidWidgets::FitOptionsBrowser::displaySequentialFitProperties () protected
Show sequential fit (PlotPeakByLogValue) properties and hide the others.
Definition at line 804 of file FitOptionsBrowser.cpp.
References changedToSequentialFitting(), m_browser, m_sequentialProperties, and m_simultaneousProperties.
Referenced by switchFitType().
doubleChanged
void MantidQt::MantidWidgets::FitOptionsBrowser::doubleChanged (QtProperty * property) private slot
pass the signal emitted by m_doubleManager
Definition at line 343 of file FitOptionsBrowser.cpp.
References doublePropertyChanged().
Referenced by createBrowser().
doublePropertyChanged
void MantidQt::MantidWidgets::FitOptionsBrowser::doublePropertyChanged (const QString & propertyName) signal
Referenced by doubleChanged().
enumChanged
void MantidQt::MantidWidgets::FitOptionsBrowser::enumChanged (QtProperty * prop) private slot
Update the browser when an enum property changes.
Parameters
prop :: Property that changed its value.
Definition at line 332 of file FitOptionsBrowser.cpp.
References m_fittingTypeProp, m_minimizer, switchFitType(), and updateMinimizer().
Referenced by createBrowser().
getBoolProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getBoolProperty (QtProperty * prop) const private
Get the value of a bool algorithm property.
Parameters
prop :: The corresponding QtProperty.
Definition at line 582 of file FitOptionsBrowser.cpp.
References m_boolManager.
Referenced by createCommonProperties(), and createSequentialFitProperties().
getCurrentFittingType()
FittingMode MantidQt::MantidWidgets::FitOptionsBrowser::getCurrentFittingType () const
Get the current fitting type, ie which algorithm to use: Simultaneous for Fit and Sequential for PlotPeakByLogValue.
Definition at line 666 of file FitOptionsBrowser.cpp.
References m_enumManager, m_fittingTypeProp, and value.
Referenced by switchFitType().
getDoubleProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getDoubleProperty (QtProperty * prop) const private
Get the value of a double algorithm property.
Parameters
prop :: The corresponding QtProperty.
Returns
the stored value
Definition at line 565 of file FitOptionsBrowser.cpp.
References m_doubleManager.
Referenced by addDoubleProperty().
getIntProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getIntProperty (QtProperty * prop) const private
Get the value of an integer algorithm property.
Parameters
prop :: The corresponding QtProperty.
Definition at line 549 of file FitOptionsBrowser.cpp.
References m_intManager.
Referenced by createCommonProperties().
getMinimizer()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getMinimizer (QtProperty *) const private
Get the value of the Minimizer property.
Definition at line 499 of file FitOptionsBrowser.cpp.
References m_boolManager, m_doubleManager, m_enumManager, m_intManager, m_minimizer, m_minimizerGroup, m_stringManager, and value.
Referenced by createCommonProperties().
getParameterToPlot()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getParameterToPlot () const
Get name of a function parameter to plot against LogValue after sequential fitting.
Definition at line 736 of file FitOptionsBrowser.cpp.
References m_enumManager, and m_plotParameter.
getProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getProperty (const QString & name) const
Get a string representation of a Fit's property value.
Parameters
name :: The name of a Fit's property.
Definition at line 473 of file FitOptionsBrowser.cpp.
References m_getters, m_propertyNameMap, and name.
getStringEnumProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getStringEnumProperty (QtProperty * prop) const private
Get the value of a string algorithm property with predefined set of values.
Parameters
prop :: The corresponding QtProperty.
Definition at line 600 of file FitOptionsBrowser.cpp.
References m_enumManager.
Referenced by createCommonProperties(), and createSequentialFitProperties().
getStringProperty()
QString MantidQt::MantidWidgets::FitOptionsBrowser::getStringProperty (QtProperty * prop) const private
Get the value of a string algorithm property.
Parameters
prop :: The corresponding QtProperty.
Definition at line 622 of file FitOptionsBrowser.cpp.
References m_stringManager.
Referenced by createSequentialFitProperties(), and createSimultaneousFitProperties().
initFittingTypeProp()
void MantidQt::MantidWidgets::FitOptionsBrowser::initFittingTypeProp () private
Initialize the fitting type property.
Show in the browser only if user can switch fit type.
Definition at line 111 of file FitOptionsBrowser.cpp.
References lockCurrentFittingType(), m_browser, m_enumManager, m_fittingType, m_fittingTypeProp, MantidQt::MantidWidgets::SEQUENTIAL, MantidQt::MantidWidgets::SEQUENTIAL_AND_SIMULTANEOUS, and MantidQt::MantidWidgets::SIMULTANEOUS.
Referenced by createProperties().
loadSettings()
void MantidQt::MantidWidgets::FitOptionsBrowser::loadSettings (const QSettings & settings)
Load property values from settings.
Parameters
settings :: A QSettings instance provided by the user of this class.
Definition at line 651 of file FitOptionsBrowser.cpp.
References m_propertyNameMap, m_setters, Mantid::Kernel::toString(), and value.
lockCurrentFittingType()
void MantidQt::MantidWidgets::FitOptionsBrowser::lockCurrentFittingType (FittingMode fitType)
Lock the browser in a particular fitting type state.
Disable the switch option.
Parameters
fitType :: Fitting type to lock the browser in.
Definition at line 688 of file FitOptionsBrowser.cpp.
References m_fittingTypeProp, and setCurrentFittingType().
Referenced by initFittingTypeProp().
removeProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::removeProperty (const QString & name) private
Remove a property previously added with addProperty (If property doesn't exist, does nothing).
Parameters
name :: [input] Name of property to remove
Definition at line 315 of file FitOptionsBrowser.cpp.
References m_getters, m_propertyNameMap, m_setters, and name.
Referenced by updateMinimizer().
saveSettings()
void MantidQt::MantidWidgets::FitOptionsBrowser::saveSettings (QSettings & settings) const
Save the last property values in settings.
Parameters
settings :: A QSettings instance provided by the user of this class.
Definition at line 639 of file FitOptionsBrowser.cpp.
References m_getters, and m_propertyNameMap.
setBoolProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setBoolProperty (QtProperty * prop, const QString & value) private
Set a new value of a bool algorithm property.
Parameters
prop :: The corresponding QtProperty.
value :: The new value.
Definition at line 591 of file FitOptionsBrowser.cpp.
References m_boolManager, and value.
Referenced by createCommonProperties(), and createSequentialFitProperties().
setCurrentFittingType()
void MantidQt::MantidWidgets::FitOptionsBrowser::setCurrentFittingType (FittingMode fitType)
Set the current fitting type, ie which algorithm to use: Simultaneous for Fit and Sequential for PlotPeakByLogValue.
Definition at line 675 of file FitOptionsBrowser.cpp.
References m_enumManager, m_fittingTypeProp, and MantidQt::MantidWidgets::SIMULTANEOUS.
Referenced by lockCurrentFittingType().
setDoubleProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setDoubleProperty (QtProperty * prop, const QString & value) private
Set a new value of a double algorithm property.
Parameters
prop :: The corresponding QtProperty.
value :: The new value.
Definition at line 574 of file FitOptionsBrowser.cpp.
References m_doubleManager, and value.
Referenced by addDoubleProperty().
setIntProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setIntProperty (QtProperty * prop, const QString & value) private
Set a new value of an integer algorithm property.
Parameters
prop :: The corresponding QtProperty.
value :: The new value.
Definition at line 556 of file FitOptionsBrowser.cpp.
References m_intManager, and value.
Referenced by createCommonProperties().
setLogNames()
void MantidQt::MantidWidgets::FitOptionsBrowser::setLogNames (const QStringList & logNames)
Define log names to use with the LogValue property.
Parameters
logNames :: The log names
Definition at line 723 of file FitOptionsBrowser.cpp.
References m_logValue, and setPropertyEnumValues().
setMinimizer()
void MantidQt::MantidWidgets::FitOptionsBrowser::setMinimizer (QtProperty * , const QString & value) private
Set new value to the Minimizer property.
Parameters
value :: The new value.
Definition at line 536 of file FitOptionsBrowser.cpp.
References m_enumManager, m_minimizer, and value.
Referenced by createCommonProperties().
setParameterNamesForPlotting()
void MantidQt::MantidWidgets::FitOptionsBrowser::setParameterNamesForPlotting (const QStringList & parNames)
Define names of function parameters that can be plotted against the LogValue.
Definition at line 728 of file FitOptionsBrowser.cpp.
References m_plotParameter, and setPropertyEnumValues().
setProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setProperty (const QString & name, const QString & value)
Set a new value to a Fit's property.
Parameters
name :: The name of a Fit's property.
value :: The new value as a string.
Definition at line 487 of file FitOptionsBrowser.cpp.
References m_propertyNameMap, m_setters, name, and value.
setPropertyEnumValues()
void MantidQt::MantidWidgets::FitOptionsBrowser::setPropertyEnumValues (QtProperty * prop, const QStringList & values) private
Set values for an enum property.
Parameters
prop :: A property to set the values to.
values :: New enum values.
Definition at line 703 of file FitOptionsBrowser.cpp.
References m_enumManager.
Referenced by setLogNames(), and setParameterNamesForPlotting().
setStringEnumProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setStringEnumProperty (QtProperty * prop, const QString & value) private
Set a new value of a string algorithm property with predefined set of values.
Parameters
prop :: The corresponding QtProperty.
value :: The new value.
Definition at line 612 of file FitOptionsBrowser.cpp.
References m_enumManager, and value.
Referenced by createCommonProperties(), and createSequentialFitProperties().
setStringProperty()
void MantidQt::MantidWidgets::FitOptionsBrowser::setStringProperty (QtProperty * prop, const QString & value) private
Set a new value of a string algorithm property.
Parameters
prop :: The corresponding QtProperty.
value :: The new value.
Definition at line 629 of file FitOptionsBrowser.cpp.
References m_stringManager, and value.
Referenced by createSequentialFitProperties(), and createSimultaneousFitProperties().
switchFitType()
void MantidQt::MantidWidgets::FitOptionsBrowser::switchFitType () private
Switch the current fit type according to the value in the FitType property.
Definition at line 378 of file FitOptionsBrowser.cpp.
References displayNormalFitProperties(), displaySequentialFitProperties(), getCurrentFittingType(), and MantidQt::MantidWidgets::SIMULTANEOUS.
Referenced by createProperties(), and enumChanged().
unlockCurrentFittingType()
void MantidQt::MantidWidgets::FitOptionsBrowser::unlockCurrentFittingType ()
Make the fitting type changeable again.
Definition at line 696 of file FitOptionsBrowser.cpp.
References m_fittingTypeProp.
updateMinimizer()
void MantidQt::MantidWidgets::FitOptionsBrowser::updateMinimizer () private
Update the browser when minimizer changes.
Definition at line 348 of file FitOptionsBrowser.cpp.
References createPropertyProperty(), m_enumManager, m_minimizer, m_minimizerGroup, and removeProperty().
Referenced by enumChanged().
Member Data Documentation
m_blacklist
QList<QtProperty *> MantidQt::MantidWidgets::FitOptionsBrowser::m_blacklist private
Definition at line 178 of file FitOptionsBrowser.h.
m_boolManager
QtBoolPropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_boolManager private
Manager for bool properties.
Definition at line 113 of file FitOptionsBrowser.h.
Referenced by createBrowser(), createCommonProperties(), createPropertyProperty(), createSequentialFitProperties(), getBoolProperty(), getMinimizer(), setBoolProperty(), and ~FitOptionsBrowser().
m_browser
QtTreePropertyBrowser* MantidQt::MantidWidgets::FitOptionsBrowser::m_browser private
Qt property browser which displays properties.
Definition at line 160 of file FitOptionsBrowser.h.
Referenced by addPropertyToBlacklist(), createBrowser(), createCommonProperties(), createSimultaneousFitProperties(), displayNormalFitProperties(), displayProperty(), displaySequentialFitProperties(), FitOptionsBrowser(), initFittingTypeProp(), and ~FitOptionsBrowser().
m_costFunction
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_costFunction private
CostFunction property.
Definition at line 132 of file FitOptionsBrowser.h.
Referenced by createCommonProperties().
m_decimals
int MantidQt::MantidWidgets::FitOptionsBrowser::m_decimals private
Precision of doubles in m_doubleManager.
Definition at line 163 of file FitOptionsBrowser.h.
Referenced by addDoubleProperty().
m_doubleManager
QtDoublePropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_doubleManager private
Manager for double properties.
Definition at line 117 of file FitOptionsBrowser.h.
Referenced by addDoubleProperty(), createBrowser(), createPropertyProperty(), getDoubleProperty(), getMinimizer(), setDoubleProperty(), and ~FitOptionsBrowser().
m_enumManager
QtEnumPropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_enumManager private
Manager for the string list properties.
Definition at line 121 of file FitOptionsBrowser.h.
Referenced by createBrowser(), createCommonProperties(), createSequentialFitProperties(), getCurrentFittingType(), getMinimizer(), getParameterToPlot(), getStringEnumProperty(), initFittingTypeProp(), setCurrentFittingType(), setMinimizer(), setPropertyEnumValues(), setStringEnumProperty(), updateMinimizer(), and ~FitOptionsBrowser().
m_evaluationType
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_evaluationType private
EvaluationType property.
Definition at line 136 of file FitOptionsBrowser.h.
Referenced by createCommonProperties().
m_fittingType
FittingMode MantidQt::MantidWidgets::FitOptionsBrowser::m_fittingType private
The Fitting Type.
Definition at line 175 of file FitOptionsBrowser.h.
Referenced by createProperties(), and initFittingTypeProp().
m_fittingTypeProp
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_fittingTypeProp private
FitType property.
Definition at line 126 of file FitOptionsBrowser.h.
Referenced by enumChanged(), getCurrentFittingType(), initFittingTypeProp(), lockCurrentFittingType(), setCurrentFittingType(), and unlockCurrentFittingType().
m_getters
QMap<QtProperty const *, GetterType> MantidQt::MantidWidgets::FitOptionsBrowser::m_getters private
Store for the properties getter methods.
Definition at line 172 of file FitOptionsBrowser.h.
Referenced by addProperty(), copyPropertiesToAlgorithm(), getProperty(), removeProperty(), and saveSettings().
m_groupManager
QtGroupPropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_groupManager private
Manager for groups of properties.
Definition at line 123 of file FitOptionsBrowser.h.
Referenced by createBrowser(), and createCommonProperties().
m_ignoreInvalidData
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_ignoreInvalidData private
IgnoreInvalidData property.
Definition at line 144 of file FitOptionsBrowser.h.
Referenced by createCommonProperties().
m_intManager
QtIntPropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_intManager private
Manager for int properties.
Definition at line 115 of file FitOptionsBrowser.h.
Referenced by createBrowser(), createCommonProperties(), createPropertyProperty(), getIntProperty(), getMinimizer(), setIntProperty(), and ~FitOptionsBrowser().
m_logValue
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_logValue private
LogValue property.
Definition at line 154 of file FitOptionsBrowser.h.
Referenced by createSequentialFitProperties(), and setLogNames().
m_maxIterations
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_maxIterations private
MaxIterations property.
Definition at line 134 of file FitOptionsBrowser.h.
Referenced by createCommonProperties().
m_minimizer
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_minimizer private
Minimizer property.
Definition at line 130 of file FitOptionsBrowser.h.
Referenced by createCommonProperties(), enumChanged(), getMinimizer(), setMinimizer(), and updateMinimizer().
m_minimizerGroup
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_minimizerGroup private
Minimizer group property.
Definition at line 128 of file FitOptionsBrowser.h.
Referenced by createCommonProperties(), getMinimizer(), and updateMinimizer().
m_output
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_output private
Output property.
Definition at line 142 of file FitOptionsBrowser.h.
Referenced by createSimultaneousFitProperties().
m_outputWorkspace
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_outputWorkspace private
OutputWorkspace property.
Definition at line 152 of file FitOptionsBrowser.h.
Referenced by createSequentialFitProperties().
m_peakRadius
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_peakRadius private
Peak radius property.
Definition at line 138 of file FitOptionsBrowser.h.
Referenced by createCommonProperties().
m_plotParameter
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_plotParameter private
Property for a name of a parameter to plot against LogValue.
Definition at line 157 of file FitOptionsBrowser.h.
Referenced by createSequentialFitProperties(), getParameterToPlot(), and setParameterNamesForPlotting().
m_plotPeakByLogValueFitType
QtProperty* MantidQt::MantidWidgets::FitOptionsBrowser::m_plotPeakByLogValueFitType private
PlotPeakByLogValue FitType property.
Definition at line 150 of file FitOptionsBrowser.h.
Referenced by createSequentialFitProperties().
m_propertyNameMap
QMap<QString, QtProperty *> MantidQt::MantidWidgets::FitOptionsBrowser::m_propertyNameMap private
Maps algorithm property name to the QtProperty.
Definition at line 168 of file FitOptionsBrowser.h.
Referenced by addDoubleProperty(), addProperty(), addPropertyToBlacklist(), copyPropertiesToAlgorithm(), displayProperty(), getProperty(), loadSettings(), removeProperty(), saveSettings(), and setProperty().
m_sequentialProperties
QList<QtProperty *> MantidQt::MantidWidgets::FitOptionsBrowser::m_sequentialProperties private
Store special properties of the sequential Fit.
Definition at line 148 of file FitOptionsBrowser.h.
Referenced by addPropertyToBlacklist(), createSequentialFitProperties(), displayNormalFitProperties(), and displaySequentialFitProperties().
m_setters
QMap<QtProperty const *, SetterType> MantidQt::MantidWidgets::FitOptionsBrowser::m_setters private
Store for the properties setter methods.
Definition at line 170 of file FitOptionsBrowser.h.
Referenced by addProperty(), loadSettings(), removeProperty(), and setProperty().
m_simultaneousProperties
QList<QtProperty *> MantidQt::MantidWidgets::FitOptionsBrowser::m_simultaneousProperties private
Store special properties of the normal Fit.
Definition at line 177 of file FitOptionsBrowser.h.
Referenced by addPropertyToBlacklist(), createSimultaneousFitProperties(), displayNormalFitProperties(), and displaySequentialFitProperties().
m_stringManager
QtStringPropertyManager* MantidQt::MantidWidgets::FitOptionsBrowser::m_stringManager private
Manager for string properties.
Definition at line 119 of file FitOptionsBrowser.h.
Referenced by createBrowser(), createPropertyProperty(), createSequentialFitProperties(), createSimultaneousFitProperties(), getMinimizer(), getStringProperty(), setStringProperty(), and ~FitOptionsBrowser().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitOptionsBrowser.h
qt/widgets/common/src/FitOptionsBrowser.cpp