Mantid: Mantid::Geometry::SymmetryElementRotationGenerator Class Reference
Mantid::Geometry::SymmetryElementRotationGenerator Class Reference
SymmetryElementRotationGenerator inherits from SymmetryElementWithAxisGenerator, using its methods for determination of rotation axis and translations in case of screw axes.
#include <SymmetryElementFactory.h>
Public Member Functions
bool canProcess (const SymmetryOperation &operation) const override
Checks the trace and determinat of the matrix to determine if the matrix belongs to a rotation.
SymmetryElement_sptr generateElement (const SymmetryOperation &operation) const override
Generates an instance of SymmetryElementRotation with the corresponding symbol, axis, translation vector and rotation sense.
Public Member Functions inherited from Mantid::Geometry::AbstractSymmetryElementGenerator
virtual bool canProcess (const SymmetryOperation &operation) const =0
Should return true if the generator can produce a valid SymmetryElement from the provided SymmetryOperation.
virtual SymmetryElement_sptr generateElement (const SymmetryOperation &operation) const =0
Must generate a valid SymmetryElement from the given operation.
virtual ~AbstractSymmetryElementGenerator ()=default
Protected Member Functions
SymmetryElementRotation::RotationSense determineRotationSense (const SymmetryOperation &operation, const V3R &rotationAxis) const
Determines the rotation sense according to the description in ITA 11.2.
std::string determineSymbol (const SymmetryOperation &operation) const override
Determines the Hermann-Mauguin symbol of the rotation-, rotoinversion- or screw-axis.
Protected Member Functions inherited from Mantid::Geometry::SymmetryElementWithAxisGenerator
V3R determineAxis (const Kernel::IntMatrix &matrix) const
Returns the symmetry axis for the given matrix.
virtual std::string determineSymbol (const SymmetryOperation &operation) const =0
V3R determineTranslation (const SymmetryOperation &operation) const
Returns the reduced vector of the operation.
Detailed Description
SymmetryElementRotationGenerator inherits from SymmetryElementWithAxisGenerator, using its methods for determination of rotation axis and translations in case of screw axes.
Furthermore it determines the rotation sense and of course the Hermann-Mauguin symbol.
Definition at line 116 of file SymmetryElementFactory.h.
Member Function Documentation
canProcess()
bool Mantid::Geometry::SymmetryElementRotationGenerator::canProcess (const SymmetryOperation & operation) const override virtual
Checks the trace and determinat of the matrix to determine if the matrix belongs to a rotation.
Implements Mantid::Geometry::AbstractSymmetryElementGenerator.
Definition at line 188 of file SymmetryElementFactory.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), Mantid::Geometry::SymmetryOperation::matrix(), and Mantid::Kernel::Matrix< T >::Trace().
determineRotationSense()
SymmetryElementRotation::RotationSense Mantid::Geometry::SymmetryElementRotationGenerator::determineRotationSense (const SymmetryOperation & operation, const V3R & rotationAxis) const protected
Determines the rotation sense according to the description in ITA 11.2.
Definition at line 198 of file SymmetryElementFactory.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), Mantid::Geometry::SymmetryOperation::matrix(), Mantid::Geometry::SymmetryElementRotation::Negative, Mantid::Geometry::SymmetryElementRotation::Positive, and Mantid::Kernel::Matrix< T >::setColumn().
Referenced by generateElement().
determineSymbol()
std::string Mantid::Geometry::SymmetryElementRotationGenerator::determineSymbol (const SymmetryOperation & operation) const override protected virtual
Determines the Hermann-Mauguin symbol of the rotation-, rotoinversion- or screw-axis.
Implements Mantid::Geometry::SymmetryElementWithAxisGenerator.
Definition at line 221 of file SymmetryElementFactory.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), Mantid::Geometry::SymmetryElementWithAxisGenerator::determineTranslation(), Mantid::Geometry::SymmetryOperation::matrix(), Mantid::Geometry::SymmetryOperation::order(), std::to_string(), and Mantid::Kernel::Matrix< T >::Trace().
Referenced by generateElement().
generateElement()
SymmetryElement_sptr Mantid::Geometry::SymmetryElementRotationGenerator::generateElement (const SymmetryOperation & operation) const override virtual
Generates an instance of SymmetryElementRotation with the corresponding symbol, axis, translation vector and rotation sense.
Implements Mantid::Geometry::AbstractSymmetryElementGenerator.
Definition at line 175 of file SymmetryElementFactory.cpp.
References Mantid::Geometry::SymmetryElementWithAxisGenerator::determineAxis(), determineRotationSense(), determineSymbol(), Mantid::Geometry::SymmetryElementWithAxisGenerator::determineTranslation(), and Mantid::Geometry::SymmetryOperation::matrix().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/SymmetryElementFactory.h
Framework/Geometry/src/Crystal/SymmetryElementFactory.cpp