Mantid: Mantid::DataObjects::PeakColumn< T > Class Template Reference
Mantid::DataObjects::PeakColumn< T > Class Template Reference
PeakColumn : a Column sub-class used to display peak information as a TableWorkspace.
#include <PeakColumn.h>
Public Member Functions
PeakColumn * clone () const override
Clone.
const std::vector< T > & data () const
Reference to the data.
bool equals (const Column &, double, bool) const override
void fromDouble (size_t i, double value) override
Assign from double.
const std::type_info & get_pointer_type_info () const override
Returns typeid for the pointer type to the data element in the column.
const std::type_info & get_type_info () const override
Returns typeid for the data in the column.
bool getReadOnly () const override
bool isBool () const override
Specialized type check.
bool isNumber () const override
Are elements of the column interpretable as a number?
PeakColumn (std::vector< T > &peaks, const std::string &name)
Construct a column with a reference to the peaks list, a name & type.
void print (size_t index, std::ostream &s) const override
Prints.
void read (const size_t index, std::istringstream &in) override
Sets item from a stream.
void read (size_t index, const std::string &text) override
Read in some text and convert to a number in the PeaksWorkspace.
size_t size () const override
Number of individual elements in the column.
long int sizeOfData () const override
Must return overall memory size taken by the column.
double toDouble (size_t i) const override
Cast to double.
Public Member Functions inherited from Mantid::API::Column
template<class T >
T & cell (size_t index)
Templated method for returning a value. No type checks are done.
template<class T >
const T & cell (size_t index) const
Templated method for returning a value (const version).
Column ()
virtual bool equalsRelErr (const Column &, double, bool const =false) const
int getLinkedYCol () const
int getPlotType () const
get plot type
template<class T >
bool isType () const
Type check.
template<>
bool isType () const
const std::string & name () const
Name (caption) of the column.
template<class T = double>
std::vector< T > numeric_fill (size_t maxSize=std::numeric_limits< size_t >::max()) const
Fills a std vector with values from the column if the types are compatible.
virtual double operator[] (size_t i) const
return value casted to double (should be pure virtual)
void setLinkedYCol (const int yCol)
void setName (const std::string &str)
Renames the column.
void setPlotType (int t)
Set plot type where.
void setReadOnly (bool isReadOnly)
Sets column read-only flag.
virtual void sortIndex (bool ascending, size_t start, size_t end, std::vector< size_t > &indexVec, std::vector< std::pair< size_t, size_t > > &equalRanges) const
Sort all or part of a vector of indices according to values in corresponding cells of this column.
virtual void sortValues (const std::vector< size_t > &indexVec)
Re-arrange values in this column according to indices in indexVec.
const std::string & type () const
Type of the column data.
virtual ~Column ()=default
Virtual destructor.
Protected Member Functions
void insert (size_t index) override
Inserts an item.
void remove (size_t index) override
Removes an item.
void resize (size_t count) override
Sets the new column size.
const void * void_pointer (size_t index) const override
Pointer to a data element.
void * void_pointer (size_t index) override
Pointer to a data element.
Protected Member Functions inherited from Mantid::API::Column
bool possibleToCompare (const Column &otherColumn) const
Private Types
using CacheValueType = boost::variant< double, int, std::string, Kernel::V3D >
Type of the row cache value.
Private Member Functions
void setPeakHKLOrRunNumber (const size_t index, const double val)
Sets the correct value in the referenced peak.
Private Attributes
int m_hklPrec
Precision of hkl in table workspace.
std::list< CacheValueType > m_oldRows
std::vector< T > & m_peaks
Reference to the peaks object saved in the PeaksWorkspace.
Additional Inherited Members
Protected Attributes inherited from Mantid::API::Column
bool m_isReadOnly
Column read-only flag.
int m_linkedYCol = -1
For error columns - the index of the related data column.
std::string m_name
name
int m_plotType
plot type where None = 0 (means it has specifically been set to 'no plot type') NotSet = -1000 (this is the default and means plot style has not been set) X = 1, Y = 2, Z = 3, xErr = 4, yErr = 5, Label = 6
std::string m_type
type
Detailed Description
template<class T>
class Mantid::DataObjects::PeakColumn< T >
PeakColumn : a Column sub-class used to display peak information as a TableWorkspace.
The column holds a reference to a vector of Peak objects. Values in the column are taken directly from those Peak objects.
Author
Janik Zikovsky
Date
2011-04-25 18:06:32.952258
Definition at line 28 of file PeakColumn.h.
Member Typedef Documentation
CacheValueType
template<class T > using Mantid::DataObjects::PeakColumn< T >::CacheValueType = boost::variant<double, int, std::string, Kernel::V3D> private
Type of the row cache value.
Definition at line 96 of file PeakColumn.h.
Constructor & Destructor Documentation
PeakColumn()
template<class T > Mantid::DataObjects::PeakColumn< T >::PeakColumn (std::vector< T > & peaks, const std::string & name)
Construct a column with a reference to the peaks list, a name & type.
Constructor.
Parameters
peaks :: vector of peaks
name :: name for the column
Definition at line 87 of file PeakColumn.cpp.
References Mantid::API::g_log, Mantid::Kernel::Logger::information(), Mantid::DataObjects::PeakColumn< T >::m_hklPrec, Mantid::API::Column::m_name, Mantid::API::Column::m_type, and Mantid::API::Column::name().
Member Function Documentation
clone()
template<class T > PeakColumn< T > * Mantid::DataObjects::PeakColumn< T >::clone () const override virtual
Clone.
Implements Mantid::API::Column.
Definition at line 333 of file PeakColumn.cpp.
data()
template<class T > const std::vector< T > & Mantid::DataObjects::PeakColumn< T >::data () const inline
Reference to the data.
Definition at line 71 of file PeakColumn.h.
equals()
template<class T > bool Mantid::DataObjects::PeakColumn< T >::equals (const Column & , double , bool) const inline override virtual
Reimplemented from Mantid::API::Column.
Definition at line 73 of file PeakColumn.h.
fromDouble()
template<class T > void Mantid::DataObjects::PeakColumn< T >::fromDouble (size_t i, double value) override virtual
Assign from double.
Implements Mantid::API::Column.
Definition at line 343 of file PeakColumn.cpp.
get_pointer_type_info()
template<class T > const std::type_info & Mantid::DataObjects::PeakColumn< T >::get_pointer_type_info () const override virtual
Returns typeid for the pointer type to the data element in the column.
Implements Mantid::API::Column.
Definition at line 120 of file PeakColumn.cpp.
get_type_info()
template<class T > const std::type_info & Mantid::DataObjects::PeakColumn< T >::get_type_info () const override virtual
Returns typeid for the data in the column.
Implements Mantid::API::Column.
Definition at line 100 of file PeakColumn.cpp.
getReadOnly()
template<class T > bool Mantid::DataObjects::PeakColumn< T >::getReadOnly () const override virtual
Returns
true if the column is read-only
Reimplemented from Mantid::API::Column.
Definition at line 217 of file PeakColumn.cpp.
insert()
template<class T > void Mantid::DataObjects::PeakColumn< T >::insert (size_t index) override protected virtual
Inserts an item.
Inserts an item into the column.
Not implemented as this is controlled by the PeaksWorkspace
Parameters
index :: The new index position (unused)
Exceptions
Exception::NotImplementedError
Implements Mantid::API::Column.
Definition at line 251 of file PeakColumn.cpp.
References index, and UNUSED_ARG.
isBool()
template<class T > bool Mantid::DataObjects::PeakColumn< T >::isBool () const override virtual
Specialized type check.
Implements Mantid::API::Column.
Definition at line 223 of file PeakColumn.cpp.
isNumber()
template<class T > bool Mantid::DataObjects::PeakColumn< T >::isNumber () const override virtual
Are elements of the column interpretable as a number?
Implements Mantid::API::Column.
Definition at line 225 of file PeakColumn.cpp.
print()
template<class T > void Mantid::DataObjects::PeakColumn< T >::print (size_t index, std::ostream & s) const override virtual
Prints.
Prints out the column string at the given row index.
Parameters
s :: stream to output
index :: row index
Implements Mantid::API::Column.
Definition at line 140 of file PeakColumn.cpp.
References index.
read() [1/2]
template<class T > void Mantid::DataObjects::PeakColumn< T >::read (const size_t index, std::istringstream & in) override virtual
Sets item from a stream.
Read in from stream and convert to a number in the PeaksWorkspace.
Parameters
index :: index of the peak to modify
in :: input stream
Reimplemented from Mantid::API::Column.
Definition at line 200 of file PeakColumn.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::g_log, and index.
read() [2/2]
template<class T > void Mantid::DataObjects::PeakColumn< T >::read (size_t index, const std::string & text) override virtual
Read in some text and convert to a number in the PeaksWorkspace.
Parameters
text :: string to read
index :: index of the peak to modify
Reimplemented from Mantid::API::Column.
Definition at line 179 of file PeakColumn.cpp.
References Mantid::Kernel::Strings::convert(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, and index.
remove()
template<class T > void Mantid::DataObjects::PeakColumn< T >::remove (size_t index) override protected virtual
Removes an item.
Removes an item from the column.
Not implemented as this is controlled by the PeaksWorkspace
Parameters
index :: The index position removed(unused)
Exceptions
Exception::NotImplementedError
Implements Mantid::API::Column.
Definition at line 264 of file PeakColumn.cpp.
References index, and UNUSED_ARG.
resize()
template<class T > void Mantid::DataObjects::PeakColumn< T >::resize (size_t count) override protected virtual
Sets the new column size.
Sets a new size for the column.
Not implemented as this is controlled by the PeaksWorkspace
Parameters
count :: Count of new column size (unused)
Exceptions
Exception::NotImplementedError
Implements Mantid::API::Column.
Definition at line 238 of file PeakColumn.cpp.
References count, and UNUSED_ARG.
setPeakHKLOrRunNumber()
template<class T > void Mantid::DataObjects::PeakColumn< T >::setPeakHKLOrRunNumber (const size_t index, const double val) private
Sets the correct value in the referenced peak.
Definition at line 348 of file PeakColumn.cpp.
References index.
size()
template<class T > size_t Mantid::DataObjects::PeakColumn< T >::size () const inline override virtual
Number of individual elements in the column.
Implements Mantid::API::Column.
Definition at line 35 of file PeakColumn.h.
sizeOfData()
template<class T > long int Mantid::DataObjects::PeakColumn< T >::sizeOfData () const override virtual
Must return overall memory size taken by the column.
Returns
overall memory size taken by the column.
Implements Mantid::API::Column.
Definition at line 228 of file PeakColumn.cpp.
toDouble()
template<class T > double Mantid::DataObjects::PeakColumn< T >::toDouble (size_t i) const override virtual
Cast to double.
Implements Mantid::API::Column.
Definition at line 338 of file PeakColumn.cpp.
void_pointer() [1/2]
template<class T > const void * Mantid::DataObjects::PeakColumn< T >::void_pointer (size_t index) const override protected virtual
Pointer to a data element.
Pointer to a data element in the PeaksWorkspace (const version)
Parameters
index :: A row index pointing to the PeaksWorkspace
Returns
A pointer to the data element at that index from this column
Implements Mantid::API::Column.
Definition at line 286 of file PeakColumn.cpp.
References Mantid::DataObjects::Peak::getValueByColName(), index, and value.
void_pointer() [2/2]
template<class T > void * Mantid::DataObjects::PeakColumn< T >::void_pointer (size_t index) override protected virtual
Pointer to a data element.
Pointer to a data element in the PeaksWorkspace (non-const version)
Parameters
index :: A row index pointing to the PeaksWorkspace
Returns
A pointer to the data element at that index from this column
Implements Mantid::API::Column.
Definition at line 276 of file PeakColumn.cpp.
References index.
Member Data Documentation
m_hklPrec
template<class T > int Mantid::DataObjects::PeakColumn< T >::m_hklPrec private
Precision of hkl in table workspace.
Definition at line 93 of file PeakColumn.h.
Referenced by Mantid::DataObjects::PeakColumn< T >::PeakColumn().
m_oldRows
template<class T > std::list<CacheValueType> Mantid::DataObjects::PeakColumn< T >::m_oldRows mutable private
Definition at line 98 of file PeakColumn.h.
m_peaks
template<class T > std::vector<T>& Mantid::DataObjects::PeakColumn< T >::m_peaks private
Reference to the peaks object saved in the PeaksWorkspace.
Definition at line 91 of file PeakColumn.h.
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/PeakColumn.h
Framework/DataObjects/src/PeakColumn.cpp