Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/UnitConversion.cpp File Reference
UnitConversion.cpp File Reference
#include "MantidKernel/UnitConversion.h"
#include <boost/python/class.hpp>
#include <boost/python/suite/indexing/map_indexing_suite.hpp>
Functions
double deprecatedSignature (const std::string &src, const std::string &dest, const double srcValue, const double l1, const double l2, const double theta, const DeltaEMode::Type emode, const double efixed)
void export_UnitConversion ()
Function Documentation
deprecatedSignature()
double deprecatedSignature (const std::string & src, const std::string & dest, const double srcValue, const double l1, const double l2, const double theta, const DeltaEMode::Type emode, const double efixed)
Definition at line 15 of file UnitConversion.cpp.
References Mantid::Kernel::UnitConversion::run().
Referenced by export_UnitConversion().
export_UnitConversion()
void export_UnitConversion ()
Definition at line 22 of file UnitConversion.cpp.
References deprecatedSignature(), and Mantid::Kernel::UnitConversion::run().