Mantid: Mantid::Nexus::NexusAddress Class Reference
Mantid::Nexus::NexusAddress Class Reference
This simple class encapsulates some methods for working with paths inside a Nexus file.
#include <NexusAddress.h>
Public Member Functions
char const * c_str () const
NexusAddress fromRoot () const
bool hasChild (std::string const &p) const
bool isAbsolute () const
bool isRoot () const
NexusAddress ()
NexusAddress (char const *const p)
NexusAddress (NexusAddress const &nd)=default
NexusAddress (std::filesystem::path const &p)
NexusAddress (std::string const &p)
operator std::string () const
bool operator!= (char const *const s) const
bool operator!= (NexusAddress const &p) const
bool operator!= (std::string const &s) const
std::string operator+ (char const s[]) const
std::string operator+ (std::string const &s) const
NexusAddress operator/ (char const *const s) const
NexusAddress operator/ (NexusAddress const &p) const
NexusAddress operator/ (std::string const &s) const
NexusAddress & operator/= (char const *const s)
NexusAddress & operator/= (NexusAddress const &p)
NexusAddress & operator/= (std::string const &s)
NexusAddress & operator= (NexusAddress const &nd)=default
NexusAddress & operator= (std::string const &s)
bool operator== (char const *const s) const
bool operator== (NexusAddress const &p) const
bool operator== (std::string const &s) const
NexusAddress parent_path () const
std::vector< std::string > parts () const
NexusAddress stem () const
std::string const & string () const
~NexusAddress ()=default
Static Public Member Functions
static NexusAddress root ()
Private Attributes
std::filesystem::path m_path
standard filesystem path
std::string m_resolved_path
Detailed Description
This simple class encapsulates some methods for working with paths inside a Nexus file.
The base is std::filesystem::path, but the root will always resolve to "/" regardless of OS. New paths are always cast to lexically normal during creation.
Definition at line 22 of file NexusAddress.h.
Constructor & Destructor Documentation
NexusAddress() [1/5]
Mantid::Nexus::NexusAddress::NexusAddress (std::filesystem::path const & p)
Definition at line 37 of file NexusAddress.cpp.
NexusAddress() [2/5]
Mantid::Nexus::NexusAddress::NexusAddress (std::string const & p)
Definition at line 40 of file NexusAddress.cpp.
NexusAddress() [3/5]
Mantid::Nexus::NexusAddress::NexusAddress (char const *const p)
Definition at line 42 of file NexusAddress.cpp.
NexusAddress() [4/5]
Mantid::Nexus::NexusAddress::NexusAddress ()
Definition at line 44 of file NexusAddress.cpp.
Referenced by fromRoot(), operator/(), operator/(), operator/(), operator/=(), operator/=(), parent_path(), root(), and stem().
NexusAddress() [5/5]
Mantid::Nexus::NexusAddress::NexusAddress (NexusAddress const & nd) default
~NexusAddress()
Mantid::Nexus::NexusAddress::~NexusAddress () default
References Mantid::API::operator/=().
Member Function Documentation
c_str()
char const * Mantid::Nexus::NexusAddress::c_str () const inline
Definition at line 97 of file NexusAddress.h.
fromRoot()
NexusAddress Mantid::Nexus::NexusAddress::fromRoot () const
Definition at line 88 of file NexusAddress.cpp.
References m_path, and NexusAddress().
hasChild()
bool Mantid::Nexus::NexusAddress::hasChild (std::string const & p) const
Definition at line 108 of file NexusAddress.cpp.
References isRoot(), and m_resolved_path.
isAbsolute()
bool Mantid::Nexus::NexusAddress::isAbsolute () const
Definition at line 82 of file NexusAddress.cpp.
References m_path.
isRoot()
bool Mantid::Nexus::NexusAddress::isRoot () const
Definition at line 84 of file NexusAddress.cpp.
References m_path.
Referenced by hasChild().
operator std::string()
Mantid::Nexus::NexusAddress::operator std::string () const inline
Definition at line 93 of file NexusAddress.h.
operator!=() [1/3]
bool Mantid::Nexus::NexusAddress::operator!= (char const *const s) const
Definition at line 62 of file NexusAddress.cpp.
References m_resolved_path.
operator!=() [2/3]
bool Mantid::Nexus::NexusAddress::operator!= (NexusAddress const & p) const
Definition at line 58 of file NexusAddress.cpp.
References m_path.
operator!=() [3/3]
bool Mantid::Nexus::NexusAddress::operator!= (std::string const & s) const
Definition at line 60 of file NexusAddress.cpp.
References m_resolved_path.
operator+() [1/2]
std::string Mantid::Nexus::NexusAddress::operator+ (char const s[]) const
Definition at line 96 of file NexusAddress.cpp.
References m_resolved_path.
operator+() [2/2]
std::string Mantid::Nexus::NexusAddress::operator+ (std::string const & s) const
Definition at line 94 of file NexusAddress.cpp.
References m_resolved_path.
operator/() [1/3]
NexusAddress Mantid::Nexus::NexusAddress::operator/ (char const *const s) const
Definition at line 66 of file NexusAddress.cpp.
References NexusAddress().
operator/() [2/3]
NexusAddress Mantid::Nexus::NexusAddress::operator/ (NexusAddress const & p) const
Definition at line 68 of file NexusAddress.cpp.
References m_path, and NexusAddress().
operator/() [3/3]
NexusAddress Mantid::Nexus::NexusAddress::operator/ (std::string const & s) const
Definition at line 64 of file NexusAddress.cpp.
References NexusAddress().
operator/=() [1/3]
NexusAddress & Mantid::Nexus::NexusAddress::operator/= (char const *const s)
Definition at line 74 of file NexusAddress.cpp.
References NexusAddress().
operator/=() [2/3]
NexusAddress & Mantid::Nexus::NexusAddress::operator/= (NexusAddress const & p)
Definition at line 76 of file NexusAddress.cpp.
References m_path, and m_resolved_path.
operator/=() [3/3]
NexusAddress & Mantid::Nexus::NexusAddress::operator/= (std::string const & s)
Definition at line 72 of file NexusAddress.cpp.
References NexusAddress().
operator=() [1/2]
NexusAddress & Mantid::Nexus::NexusAddress::operator= (NexusAddress const & nd) default
operator=() [2/2]
NexusAddress & Mantid::Nexus::NexusAddress::operator= (std::string const & s)
Definition at line 46 of file NexusAddress.cpp.
References m_path, and m_resolved_path.
operator==() [1/3]
bool Mantid::Nexus::NexusAddress::operator== (char const *const s) const
Definition at line 56 of file NexusAddress.cpp.
References m_resolved_path.
operator==() [2/3]
bool Mantid::Nexus::NexusAddress::operator== (NexusAddress const & p) const
Definition at line 52 of file NexusAddress.cpp.
References m_path.
operator==() [3/3]
bool Mantid::Nexus::NexusAddress::operator== (std::string const & s) const
Definition at line 54 of file NexusAddress.cpp.
References m_resolved_path.
parent_path()
NexusAddress Mantid::Nexus::NexusAddress::parent_path () const
Definition at line 86 of file NexusAddress.cpp.
References m_path, and NexusAddress().
Referenced by Mantid::DataHandling::LoadMcStas::exec(), and Mantid::Nexus::NXDataSet::open().
parts()
std::vector< std::string > Mantid::Nexus::NexusAddress::parts () const
Definition at line 98 of file NexusAddress.cpp.
References m_path.
root()
NexusAddress Mantid::Nexus::NexusAddress::root () static
Definition at line 92 of file NexusAddress.cpp.
References NexusAddress().
Referenced by Mantid::Nexus::NXDataSet::open().
stem()
NexusAddress Mantid::Nexus::NexusAddress::stem () const
Definition at line 90 of file NexusAddress.cpp.
References m_path, and NexusAddress().
Referenced by Mantid::DataHandling::LoadMcStas::exec(), Mantid::Nexus::NXObject::name(), and Mantid::DataHandling::LoadMcStas::readEventData().
string()
std::string const & Mantid::Nexus::NexusAddress::string () const inline
Definition at line 95 of file NexusAddress.h.
Referenced by operator!=(), operator+(), operator+(), operator<<(), and operator==().
Member Data Documentation
m_path
std::filesystem::path Mantid::Nexus::NexusAddress::m_path private
standard filesystem path
Definition at line 101 of file NexusAddress.h.
Referenced by fromRoot(), isAbsolute(), isRoot(), operator!=(), operator/(), operator/=(), operator=(), operator==(), parent_path(), parts(), and stem().
m_resolved_path
std::string Mantid::Nexus::NexusAddress::m_resolved_path private
Definition at line 103 of file NexusAddress.h.
Referenced by hasChild(), operator!=(), operator!=(), operator+(), operator+(), operator/=(), operator=(), operator==(), and operator==().
The documentation for this class was generated from the following files:
Framework/Nexus/inc/MantidNexus/NexusAddress.h
Framework/Nexus/src/NexusAddress.cpp