Mantid: Mantid::API::ISpectrum Class Reference
Mantid::API::ISpectrum Class Reference abstract
A "spectrum" is an object that holds the data for a particular spectrum, in particular:
#include <ISpectrum.h>
Public Member Functions
void addDetectorID (const detid_t detID)
Add a detector ID to the set of detector IDs.
void addDetectorIDs (const std::set< detid_t > &detIDs)
Add a set of detector IDs to the set of detector IDs.
void addDetectorIDs (const std::vector< detid_t > &detIDs)
Add a vector of detector IDs to the set of detector IDs.
HistogramData::BinEdges binEdges () const
virtual void clearData ()=0
void clearDetectorIDs ()
Clear the detector IDs set.
void convertToCounts ()
void convertToFrequencies ()
virtual void copyDataFrom (const ISpectrum &source)=0
Copy data from another ISpectrum with double-dynamic dispatch.
virtual void copyDataInto (DataObjects::EventList &) const
Override in child classes for polymorphic copying of data.
virtual void copyDataInto (DataObjects::Histogram1D &) const
Override in child classes for polymorphic copying of data.
virtual void copyDataInto (SpectrumTester &) const
Override in child classes for polymorphic copying of data.
void copyInfoFrom (const ISpectrum &other)
Copy spectrum number and detector IDs, but not X vector, from another ISpectrum.
virtual HistogramData::Counts counts () const
virtual HistogramData::CountStandardDeviations countStandardDeviations () const
virtual HistogramData::CountVariances countVariances () const
virtual const MantidVec & dataDx () const =0
virtual MantidVec & dataDx ()=0
virtual const MantidVec & dataE () const =0
virtual MantidVec & dataE ()=0
virtual const MantidVec & dataX () const =0
virtual MantidVec & dataX ()=0
virtual const MantidVec & dataY () const =0
virtual MantidVec & dataY ()=0
const HistogramData::HistogramDx & dx () const
virtual const HistogramData::HistogramE & e () const
virtual HistogramData::Frequencies frequencies () const
virtual HistogramData::FrequencyStandardDeviations frequencyStandardDeviations () const
virtual HistogramData::FrequencyVariances frequencyVariances () const
const std::set< detid_t > & getDetectorIDs () const
Get a const reference to the detector IDs set.
virtual size_t getMemorySize () const =0
specnum_t getSpectrumNo () const
virtual std::pair< double, double > getXDataRange () const
Return the min/max X values for this spectrum.
bool hasDetectorID (const detid_t detID) const
Return true if the given detector ID is in the list for this ISpectrum.
bool hasDx () const
Gets the value of the use flag.
virtual HistogramData::Histogram histogram () const
Returns the Histogram associated with this spectrum.
ISpectrum ()=default
ISpectrum (const specnum_t specNo)
Constructor with spectrum number.
HistogramData::HistogramDx & mutableDx () &
HistogramData::HistogramE & mutableE () &
HistogramData::HistogramX & mutableX () &
HistogramData::HistogramY & mutableY () &
HistogramData::Points points () const
HistogramData::PointStandardDeviations pointStandardDeviations () const
virtual Kernel::cow_ptr< HistogramData::HistogramX > ptrX () const =0
virtual const MantidVec & readDx () const =0
virtual const MantidVec & readE () const
Deprecated, use e() instead. Returns the y error data const.
virtual const MantidVec & readX () const =0
virtual const MantidVec & readY () const
Deprecated, use y() instead. Returns the y data const.
void resetHasDx ()
Resets the hasDx flag.
void resize (size_t n)
template<typename... T>
void setBinEdges (T &&...data) &
template<typename... T>
void setCounts (T &&...data) &
template<typename... T>
void setCountStandardDeviations (T &&...data) &
template<typename... T>
void setCountVariances (T &&...data) &
void setDetectorID (const detid_t detID)
Clear the list of detector IDs, then add one.
void setDetectorIDs (const std::set< detid_t > &detIDs)
Set the detector IDs to be the set given.
void setDetectorIDs (std::set< detid_t > &&detIDs)
Set the detector IDs to be the set given (move version).
template<typename... T>
void setFrequencies (T &&...data) &
template<typename... T>
void setFrequencyStandardDeviations (T &&...data) &
template<typename... T>
void setFrequencyVariances (T &&...data) &
template<typename... T>
void setHistogram (T &&...data)
Sets the Histogram associated with this spectrum.
void setMatrixWorkspace (MatrixWorkspace *matrixWorkspace, const size_t index)
Sets the MatrixWorkspace pointer (pointer to the owning workspace).
template<typename... T>
void setPoints (T &&...data) &
template<typename... T>
void setPointStandardDeviations (T &&...data) &
template<typename... T>
void setPointVariances (T &&...data) &
void setSharedDx (const Kernel::cow_ptr< HistogramData::HistogramDx > &dx) &
void setSharedE (const Kernel::cow_ptr< HistogramData::HistogramE > &e) &
void setSharedX (const Kernel::cow_ptr< HistogramData::HistogramX > &x) &
void setSharedY (const Kernel::cow_ptr< HistogramData::HistogramY > &y) &
void setSpectrumNo (specnum_t num)
Sets the spectrum number of this spectrum.
virtual void setX (const Kernel::cow_ptr< HistogramData::HistogramX > &X)=0
void setYMode (HistogramData::Histogram::YMode ymode)
Kernel::cow_ptr< HistogramData::HistogramDx > sharedDx () const
virtual Kernel::cow_ptr< HistogramData::HistogramE > sharedE () const
Kernel::cow_ptr< HistogramData::HistogramX > sharedX () const
virtual Kernel::cow_ptr< HistogramData::HistogramY > sharedY () const
size_t size () const
const HistogramData::HistogramX & x () const
virtual const HistogramData::HistogramY & y () const
HistogramData::Histogram::YMode yMode () const
virtual ~ISpectrum ()=default
Protected Member Functions
virtual void checkAndSanitizeHistogram (HistogramData::Histogram &)
virtual void checkIsYAndEWritable () const
virtual void checkWorksWithPoints () const
ISpectrum (const ISpectrum &other)
Copy constructor.
ISpectrum (ISpectrum &&other)
Move constructor.
ISpectrum & operator= (const ISpectrum &other)
Copy assignment.
ISpectrum & operator= (ISpectrum &&other)
Move assignment.
Private Member Functions
virtual const HistogramData::Histogram & histogramRef () const =0
void invalidateCachedSpectrumNumbers () const
Invalidates cached spectrum numbers in the owning workspace.
void invalidateSpectrumDefinition () const
Invalidates spectrum definitions in the owning workspace.
virtual HistogramData::Histogram & mutableHistogramRef ()=0
Private Attributes
std::set< detid_t > detectorIDs
Set of the detector IDs associated with this spectrum.
size_t m_index {0}
MatrixWorkspace * m_matrixWorkspace {nullptr}
specnum_t m_specNo {0}
The spectrum number of this spectrum.
Detailed Description
A "spectrum" is an object that holds the data for a particular spectrum, in particular:
The X/Y/E arrays
The spectrum number
A list of detector ids associated with it.
This is an interface that can be used for both Workspace2D's Spectrum objects, and EventWorkspace's EventList objects
Author
Janik Zikovsky
Date
2011-07-01
Definition at line 38 of file ISpectrum.h.
Constructor & Destructor Documentation
ISpectrum() [1/4]
Mantid::API::ISpectrum::ISpectrum () default
ISpectrum() [2/4]
Mantid::API::ISpectrum::ISpectrum (const specnum_t specNo)
Constructor with spectrum number.
Parameters
specNo :: spectrum # of the spectrum
Definition at line 17 of file ISpectrum.cpp.
~ISpectrum()
virtual Mantid::API::ISpectrum::~ISpectrum () virtual default
ISpectrum() [3/4]
Mantid::API::ISpectrum::ISpectrum (const ISpectrum & other) protected
Copy constructor.
Definition at line 144 of file ISpectrum.cpp.
ISpectrum() [4/4]
Mantid::API::ISpectrum::ISpectrum (ISpectrum && other) protected
Move constructor.
Definition at line 150 of file ISpectrum.cpp.
Member Function Documentation
addDetectorID()
void Mantid::API::ISpectrum::addDetectorID (const detid_t detID)
Add a detector ID to the set of detector IDs.
Parameters
detID :: detector ID to insert in set.
Definition at line 51 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
Referenced by WorkspaceCreationHelper::createRandomEventWorkspace(), and export_ISpectrum().
addDetectorIDs() [1/2]
void Mantid::API::ISpectrum::addDetectorIDs (const std::set< detid_t > & detIDs)
Add a set of detector IDs to the set of detector IDs.
Parameters
detIDs :: set of detector IDs to insert in set.
Definition at line 62 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
Referenced by Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), and Mantid::DataObjects::EventList::operator+=().
addDetectorIDs() [2/2]
void Mantid::API::ISpectrum::addDetectorIDs (const std::vector< detid_t > & detIDs)
Add a vector of detector IDs to the set of detector IDs.
Parameters
detIDs :: vector of detector IDs to insert in set.
Definition at line 73 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
binEdges()
HistogramData::BinEdges Mantid::API::ISpectrum::binEdges () const inline
Definition at line 115 of file ISpectrum.h.
checkAndSanitizeHistogram()
virtual void Mantid::API::ISpectrum::checkAndSanitizeHistogram (HistogramData::Histogram &) inline protected virtual
Reimplemented in Mantid::DataObjects::EventList, and Mantid::DataObjects::Histogram1D.
Definition at line 210 of file ISpectrum.h.
checkIsYAndEWritable()
virtual void Mantid::API::ISpectrum::checkIsYAndEWritable () const inline protected virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 212 of file ISpectrum.h.
checkWorksWithPoints()
virtual void Mantid::API::ISpectrum::checkWorksWithPoints () const inline protected virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 211 of file ISpectrum.h.
clearData()
virtual void Mantid::API::ISpectrum::clearData () pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by Mantid::Algorithms::CalculateEfficiency::maskComponent(), and Mantid::Algorithms::BinaryOperation::propagateSpectraMask().
clearDetectorIDs()
void Mantid::API::ISpectrum::clearDetectorIDs ()
Clear the detector IDs set.
Definition at line 117 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
Referenced by Mantid::DataObjects::EventList::clear(), Mantid::Algorithms::SumSpectra::execEvent(), export_ISpectrum(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::DataHandling::LoadNexusProcessed::loadEventEntry(), Mantid::Algorithms::ExportTimeSeriesLog::setupEventWorkspace(), and Mantid::Algorithms::SmoothNeighbours::setupNewInstrument().
convertToCounts()
void Mantid::API::ISpectrum::convertToCounts () inline
Definition at line 106 of file ISpectrum.h.
convertToFrequencies()
void Mantid::API::ISpectrum::convertToFrequencies () inline
Definition at line 110 of file ISpectrum.h.
copyDataFrom()
virtual void Mantid::API::ISpectrum::copyDataFrom (const ISpectrum & source) pure virtual
Copy data from another ISpectrum with double-dynamic dispatch.
Implemented in SpectrumTester, Mantid::DataObjects::EventList, and Mantid::DataObjects::Histogram1D.
copyDataInto() [1/3]
void Mantid::API::ISpectrum::copyDataInto (DataObjects::EventList &) const virtual
Override in child classes for polymorphic copying of data.
Reimplemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, SpectrumTester, and Mantid::DataObjects::EventList.
Definition at line 201 of file ISpectrum.cpp.
Referenced by Mantid::DataObjects::EventList::copyDataFrom(), and Mantid::DataObjects::Histogram1D::copyDataFrom().
copyDataInto() [2/3]
void Mantid::API::ISpectrum::copyDataInto (DataObjects::Histogram1D &) const virtual
Override in child classes for polymorphic copying of data.
Reimplemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, SpectrumTester, Mantid::DataObjects::EventList, and Mantid::DataObjects::Histogram1D.
Definition at line 205 of file ISpectrum.cpp.
copyDataInto() [3/3]
void Mantid::API::ISpectrum::copyDataInto (SpectrumTester &) const virtual
Override in child classes for polymorphic copying of data.
Reimplemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, SpectrumTester, and SpectrumTester.
Definition at line 210 of file ISpectrum.cpp.
copyInfoFrom()
void Mantid::API::ISpectrum::copyInfoFrom (const ISpectrum & other)
Copy spectrum number and detector IDs, but not X vector, from another ISpectrum.
Parameters
other :: take the values from other, put them in this
Definition at line 24 of file ISpectrum.cpp.
References detectorIDs, invalidateCachedSpectrumNumbers(), invalidateSpectrumDefinition(), and m_specNo.
Referenced by Mantid::DataObjects::EventList::createFromHistogram(), and Mantid::API::WorkspaceFactoryImpl::initializeFromParent().
counts()
virtual HistogramData::Counts Mantid::API::ISpectrum::counts () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 136 of file ISpectrum.h.
countStandardDeviations()
virtual HistogramData::CountStandardDeviations Mantid::API::ISpectrum::countStandardDeviations () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 138 of file ISpectrum.h.
countVariances()
virtual HistogramData::CountVariances Mantid::API::ISpectrum::countVariances () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 137 of file ISpectrum.h.
dataDx() [1/2]
virtual const MantidVec & Mantid::API::ISpectrum::dataDx () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
dataDx() [2/2]
virtual MantidVec & Mantid::API::ISpectrum::dataDx () pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
dataE() [1/2]
virtual const MantidVec & Mantid::API::ISpectrum::dataE () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
dataE() [2/2]
virtual MantidVec & Mantid::API::ISpectrum::dataE () pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), and readE().
dataX() [1/2]
virtual const MantidVec & Mantid::API::ISpectrum::dataX () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
dataX() [2/2]
virtual MantidVec & Mantid::API::ISpectrum::dataX () pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by Mantid::Algorithms::Integration::integrateSpectrum().
dataY() [1/2]
virtual const MantidVec & Mantid::API::ISpectrum::dataY () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
dataY() [2/2]
virtual MantidVec & Mantid::API::ISpectrum::dataY () pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by VariableBinThrowingTester::blocksize(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), and readY().
dx()
const HistogramData::HistogramDx & Mantid::API::ISpectrum::dx () const inline
Definition at line 174 of file ISpectrum.h.
e()
virtual const HistogramData::HistogramE & Mantid::API::ISpectrum::e () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 173 of file ISpectrum.h.
Referenced by Mantid::Algorithms::PolarizationCorrectionWildes::analyzerlessCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::directBeamCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::fullCorrections(), Mantid::Algorithms::Integration::integrateSpectrum(), and Mantid::Algorithms::PolarizationCorrectionWildes::twoInputsSolve01And10().
frequencies()
virtual HistogramData::Frequencies Mantid::API::ISpectrum::frequencies () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 141 of file ISpectrum.h.
frequencyStandardDeviations()
virtual HistogramData::FrequencyStandardDeviations Mantid::API::ISpectrum::frequencyStandardDeviations () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 143 of file ISpectrum.h.
frequencyVariances()
virtual HistogramData::FrequencyVariances Mantid::API::ISpectrum::frequencyVariances () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 142 of file ISpectrum.h.
getDetectorIDs()
const std::set< detid_t > & Mantid::API::ISpectrum::getDetectorIDs () const
Get a const reference to the detector IDs set.
Definition at line 113 of file ISpectrum.cpp.
References detectorIDs.
Referenced by Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), export_ISpectrum(), Mantid::DataObjects::EventList::filterByPulseTime(), Mantid::DataObjects::EventList::filterByPulseTime(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::API::MatrixWorkspace::getDetector(), Mantid::DataObjects::SpecialWorkspace2D::getDetectorIDs(), Mantid::API::MatrixWorkspace::getDetectorIDToWorkspaceIndexMap(), Mantid::API::MatrixWorkspace::getDetectorIDToWorkspaceIndexVector(), Mantid::API::MatrixWorkspace::getIndicesFromDetectorIDs(), Mantid::DataHandling::LoadMuonStrategy::getLoadedDetectorsFromWorkspace(), Mantid::API::MatrixWorkspace::hasGroupedDetectors(), Mantid::DataObjects::SpecialWorkspace2D::isCompatible(), Mantid::DataObjects::EventList::operator+=(), Mantid::Algorithms::FilterEvents::setupCustomizedTOFCorrection(), and Mantid::Algorithms::SparseWorkspace::SparseWorkspace().
getMemorySize()
virtual size_t Mantid::API::ISpectrum::getMemorySize () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, SpectrumTester, and Mantid::API::IEventList.
getSpectrumNo()
specnum_t Mantid::API::ISpectrum::getSpectrumNo () const
Returns
the spectrum number of this spectrum
Definition at line 123 of file ISpectrum.cpp.
References m_specNo.
Referenced by Mantid::Algorithms::ConjoinWorkspaces::checkForOverlap(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), export_ISpectrum(), Mantid::Algorithms::ConjoinWorkspaces::fixSpectrumNumbers(), Mantid::API::MatrixWorkspace::getIndexFromSpectrumNumber(), Mantid::API::MatrixWorkspace::getIndicesFromSpectra(), Mantid::API::SpectraAxis::getMax(), Mantid::API::SpectraAxis::getMin(), Mantid::Algorithms::WorkspaceJoiners::getMinMax(), Mantid::API::MatrixWorkspace::getSpectraFromDetectorIDs(), Mantid::API::SpectraAxis::getSpectraIndexMap(), Mantid::API::MatrixWorkspace::indexInfo(), Mantid::API::SpectraAxis::operator()(), Mantid::API::SpectraAxis::spectraNo(), and Mantid::API::WorkspaceNearestNeighbourInfo::WorkspaceNearestNeighbourInfo().
getXDataRange()
std::pair< double, double > Mantid::API::ISpectrum::getXDataRange () const virtual
Return the min/max X values for this spectrum.
Returns
A pair where the first is the minimum X value and the second the maximum
Definition at line 36 of file ISpectrum.cpp.
References readX().
hasDetectorID()
bool Mantid::API::ISpectrum::hasDetectorID (const detid_t detID) const
Return true if the given detector ID is in the list for this ISpectrum.
Definition at line 109 of file ISpectrum.cpp.
References detectorIDs.
Referenced by export_ISpectrum(), and Mantid::API::MatrixWorkspace::getSpectraFromDetectorIDs().
hasDx()
bool Mantid::API::ISpectrum::hasDx () const
Gets the value of the use flag.
Returns
true if DX has been set, else false
Definition at line 136 of file ISpectrum.cpp.
References histogramRef(), and sharedDx().
Referenced by export_ISpectrum().
histogram()
virtual HistogramData::Histogram Mantid::API::ISpectrum::histogram () const inline virtual
Returns the Histogram associated with this spectrum.
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 94 of file ISpectrum.h.
Referenced by Mantid::DataObjects::Histogram1D::checkAndSanitizeHistogram(), and Mantid::API::MatrixWorkspace::isHistogramDataByIndex().
histogramRef()
virtual const HistogramData::Histogram & Mantid::API::ISpectrum::histogramRef () const private pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by hasDx().
invalidateCachedSpectrumNumbers()
void Mantid::API::ISpectrum::invalidateCachedSpectrumNumbers () const private
Invalidates cached spectrum numbers in the owning workspace.
Definition at line 189 of file ISpectrum.cpp.
References Mantid::API::MatrixWorkspace::invalidateCachedSpectrumNumbers(), and m_matrixWorkspace.
Referenced by copyInfoFrom(), operator=(), operator=(), and setSpectrumNo().
invalidateSpectrumDefinition()
void Mantid::API::ISpectrum::invalidateSpectrumDefinition () const private
Invalidates spectrum definitions in the owning workspace.
Definition at line 195 of file ISpectrum.cpp.
References Mantid::API::ExperimentInfo::invalidateSpectrumDefinition(), m_index, and m_matrixWorkspace.
Referenced by addDetectorID(), addDetectorIDs(), addDetectorIDs(), clearDetectorIDs(), copyInfoFrom(), operator=(), operator=(), setDetectorID(), setDetectorIDs(), and setDetectorIDs().
mutableDx()
HistogramData::HistogramDx & Mantid::API::ISpectrum::mutableDx () & inline
Definition at line 176 of file ISpectrum.h.
mutableE()
HistogramData::HistogramE & Mantid::API::ISpectrum::mutableE () & inline
Definition at line 181 of file ISpectrum.h.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::assignToOutput(), and Mantid::Algorithms::Integration::integrateSpectrum().
mutableHistogramRef()
virtual HistogramData::Histogram & Mantid::API::ISpectrum::mutableHistogramRef () private pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by resetHasDx().
mutableX()
HistogramData::HistogramX & Mantid::API::ISpectrum::mutableX () & inline
Definition at line 175 of file ISpectrum.h.
Referenced by Mantid::DataObjects::EventList::convertTof(), Mantid::Algorithms::ModeratorTzero::execEvent(), and Mantid::Algorithms::Integration::integrateSpectrum().
mutableY()
HistogramData::HistogramY & Mantid::API::ISpectrum::mutableY () & inline
Definition at line 177 of file ISpectrum.h.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::assignToOutput(), and Mantid::Algorithms::Integration::integrateSpectrum().
operator=() [1/2]
ISpectrum & Mantid::API::ISpectrum::operator= (const ISpectrum & other) protected
Copy assignment.
Definition at line 156 of file ISpectrum.cpp.
References detectorIDs, invalidateCachedSpectrumNumbers(), invalidateSpectrumDefinition(), and m_specNo.
Referenced by Mantid::DataObjects::Histogram1D::operator=().
operator=() [2/2]
ISpectrum & Mantid::API::ISpectrum::operator= (ISpectrum && other) protected
Move assignment.
Definition at line 167 of file ISpectrum.cpp.
References detectorIDs, invalidateCachedSpectrumNumbers(), invalidateSpectrumDefinition(), and m_specNo.
points()
HistogramData::Points Mantid::API::ISpectrum::points () const inline
Definition at line 116 of file ISpectrum.h.
pointStandardDeviations()
HistogramData::PointStandardDeviations Mantid::API::ISpectrum::pointStandardDeviations () const inline
Definition at line 117 of file ISpectrum.h.
ptrX()
virtual Kernel::cow_ptr< HistogramData::HistogramX > Mantid::API::ISpectrum::ptrX () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by Mantid::DataObjects::EventList::createFromHistogram().
readDx()
virtual const MantidVec & Mantid::API::ISpectrum::readDx () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
readE()
const MantidVec & Mantid::API::ISpectrum::readE () const virtual
Deprecated, use e() instead. Returns the y error data const.
Definition at line 45 of file ISpectrum.cpp.
References dataE().
Referenced by Mantid::DataObjects::EventList::createFromHistogram(), and Mantid::DataObjects::EventWorkspace::dataE().
readX()
virtual const MantidVec & Mantid::API::ISpectrum::readX () const pure virtual
Implemented in Mantid::DataObjects::EventList, Mantid::DataObjects::Histogram1D, and SpectrumTester.
Referenced by Mantid::DataObjects::EventList::createFromHistogram(), and getXDataRange().
readY()
const MantidVec & Mantid::API::ISpectrum::readY () const virtual
Deprecated, use y() instead. Returns the y data const.
Definition at line 42 of file ISpectrum.cpp.
References dataY().
Referenced by Mantid::DataObjects::EventList::createFromHistogram(), Mantid::DataObjects::EventWorkspace::dataY(), and SpectrumTester::getMemorySize().
resetHasDx()
void Mantid::API::ISpectrum::resetHasDx ()
Resets the hasDx flag.
Definition at line 141 of file ISpectrum.cpp.
References mutableHistogramRef().
resize()
void Mantid::API::ISpectrum::resize (size_t n) inline
Definition at line 200 of file ISpectrum.h.
References n.
setBinEdges()
template<typename... T> void Mantid::API::ISpectrum::setBinEdges (T &&... data) & inline
Definition at line 120 of file ISpectrum.h.
setCounts()
template<typename... T> void Mantid::API::ISpectrum::setCounts (T &&... data) & inline
Definition at line 146 of file ISpectrum.h.
Referenced by Mantid::DataObjects::Histogram1D::Histogram1D(), Mantid::DataObjects::Workspace2D::init(), SpectrumTester::SpectrumTester(), and SpectrumTester::SpectrumTester().
setCountStandardDeviations()
template<typename... T> void Mantid::API::ISpectrum::setCountStandardDeviations (T &&... data) & inline
Definition at line 155 of file ISpectrum.h.
Referenced by Mantid::DataObjects::Workspace2D::init().
setCountVariances()
template<typename... T> void Mantid::API::ISpectrum::setCountVariances (T &&... data) & inline
Definition at line 151 of file ISpectrum.h.
setDetectorID()
void Mantid::API::ISpectrum::setDetectorID (const detid_t detID)
Clear the list of detector IDs, then add one.
Parameters
detID :: detector ID to insert in set.
Definition at line 84 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
Referenced by Mantid::SingleCrystalDiffractionTestHelper::WorkspaceBuilder::createEventWorkspace(), WorkspaceCreationHelper::createEventWorkspaceWithStartTime(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadBBY2::execLoader(), export_ISpectrum(), Mantid::DataHandling::LoadSwans::loadDataIntoTheWorkspace(), Mantid::DataHandling::LoadEMU< FD >::prepareEventStorage(), Mantid::DataHandling::LoadPLN::prepareEventStorage(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), and Mantid::Algorithms::SparseWorkspace::SparseWorkspace().
setDetectorIDs() [1/2]
void Mantid::API::ISpectrum::setDetectorIDs (const std::set< detid_t > & detIDs)
Set the detector IDs to be the set given.
Will clear any previous IDs (unlike addDetectorIDs).
Parameters
detIDs The new list of detector ID numbers
Definition at line 94 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
Referenced by Mantid::DataObjects::EventList::filterByPulseTime(), and Mantid::DataObjects::EventList::filterByPulseTime().
setDetectorIDs() [2/2]
void Mantid::API::ISpectrum::setDetectorIDs (std::set< detid_t > && detIDs)
Set the detector IDs to be the set given (move version).
Will clear any previous IDs (unlike addDetectorIDs).
Parameters
detIDs The new list of detector ID numbers
Definition at line 103 of file ISpectrum.cpp.
References detectorIDs, and invalidateSpectrumDefinition().
setFrequencies()
template<typename... T> void Mantid::API::ISpectrum::setFrequencies (T &&... data) & inline
Definition at line 159 of file ISpectrum.h.
setFrequencyStandardDeviations()
template<typename... T> void Mantid::API::ISpectrum::setFrequencyStandardDeviations (T &&... data) & inline
Definition at line 167 of file ISpectrum.h.
setFrequencyVariances()
template<typename... T> void Mantid::API::ISpectrum::setFrequencyVariances (T &&... data) & inline
Definition at line 163 of file ISpectrum.h.
setHistogram()
template<typename... T> void Mantid::API::ISpectrum::setHistogram (T &&... data) inline
Sets the Histogram associated with this spectrum.
Definition at line 96 of file ISpectrum.h.
Referenced by Mantid::DataObjects::EventList::copyDataInto(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::WorkspaceJoiners::execWS2D(), Mantid::DataObjects::EventList::filterByPulseTime(), Mantid::DataObjects::EventList::filterByPulseTime(), Mantid::DataObjects::EventWorkspace::init(), Mantid::DataObjects::Workspace2D::init(), Mantid::DataObjects::EventWorkspace::init(), and Mantid::DataHandling::LoadNexusProcessed::loadEventEntry().
setMatrixWorkspace()
void Mantid::API::ISpectrum::setMatrixWorkspace (MatrixWorkspace * matrixWorkspace, const size_t index)
Sets the MatrixWorkspace pointer (pointer to the owning workspace).
This method should not need to be called explicitly, it is called when getting a mutable reference to an ISpectrum stored in a MatrixWorkspace. The pointer set by this method is used to push updates of the detector IDs into the Beamline::SpectrumInfo that is stored in the ExperimentInfo.
Definition at line 183 of file ISpectrum.cpp.
References index, m_index, and m_matrixWorkspace.
Referenced by Mantid::DataObjects::EventWorkspace::getSpectrumWithoutInvalidation(), Mantid::DataObjects::Workspace2D::getSpectrumWithoutInvalidation(), Mantid::DataObjects::WorkspaceSingleValue::getSpectrumWithoutInvalidation(), and AxeslessWorkspaceTester::getSpectrumWithoutInvalidation().
setPoints()
template<typename... T> void Mantid::API::ISpectrum::setPoints (T &&... data) & inline
Definition at line 123 of file ISpectrum.h.
setPointStandardDeviations()
template<typename... T> void Mantid::API::ISpectrum::setPointStandardDeviations (T &&... data) & inline
Definition at line 133 of file ISpectrum.h.
setPointVariances()
template<typename... T> void Mantid::API::ISpectrum::setPointVariances (T &&... data) & inline
Definition at line 128 of file ISpectrum.h.
setSharedDx()
void Mantid::API::ISpectrum::setSharedDx (const Kernel::cow_ptr< HistogramData::HistogramDx > & dx) & inline
Definition at line 190 of file ISpectrum.h.
setSharedE()
void Mantid::API::ISpectrum::setSharedE (const Kernel::cow_ptr< HistogramData::HistogramE > & e) & inline
Definition at line 195 of file ISpectrum.h.
setSharedX()
void Mantid::API::ISpectrum::setSharedX (const Kernel::cow_ptr< HistogramData::HistogramX > & x) & inline
Definition at line 189 of file ISpectrum.h.
References Mantid::Geometry::x.
Referenced by Mantid::Algorithms::BinaryOperation::do2D().
setSharedY()
void Mantid::API::ISpectrum::setSharedY (const Kernel::cow_ptr< HistogramData::HistogramY > & y) & inline
Definition at line 191 of file ISpectrum.h.
References Mantid::Geometry::y.
setSpectrumNo()
void Mantid::API::ISpectrum::setSpectrumNo (specnum_t num)
Sets the spectrum number of this spectrum.
Parameters
num :: the spectrum number of this spectrum
Definition at line 127 of file ISpectrum.cpp.
References invalidateCachedSpectrumNumbers(), and m_specNo.
Referenced by WorkspaceCreationHelper::createEventWorkspaceWithStartTime(), Mantid::DataHandling::LoadBBY::exec(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Algorithms::SumSpectra::execEvent(), Mantid::DataHandling::LoadBBY2::execLoader(), export_ISpectrum(), Mantid::Algorithms::ConjoinWorkspaces::fixSpectrumNumbers(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::DataHandling::LoadSwans::loadDataIntoTheWorkspace(), Mantid::DataHandling::LoadEMU< FD >::prepareEventStorage(), Mantid::DataHandling::LoadPLN::prepareEventStorage(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::LoadNexusProcessed::readInstrumentGroup(), and Mantid::DataHandling::EventWorkspaceCollection::setSpectrumNumbersFromUniqueSpectra().
setX()
virtual void Mantid::API::ISpectrum::setX (const Kernel::cow_ptr< HistogramData::HistogramX > & X) pure virtual
Implemented in Mantid::DataObjects::EventList, and Mantid::DataObjects::Histogram1D.
setYMode()
void Mantid::API::ISpectrum::setYMode (HistogramData::Histogram::YMode ymode) inline
Definition at line 105 of file ISpectrum.h.
Referenced by Mantid::API::MatrixWorkspace::setDistribution().
sharedDx()
Kernel::cow_ptr< HistogramData::HistogramDx > Mantid::API::ISpectrum::sharedDx () const inline
Definition at line 188 of file ISpectrum.h.
Referenced by hasDx().
sharedE()
virtual Kernel::cow_ptr< HistogramData::HistogramE > Mantid::API::ISpectrum::sharedE () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 187 of file ISpectrum.h.
sharedX()
Kernel::cow_ptr< HistogramData::HistogramX > Mantid::API::ISpectrum::sharedX () const inline
Definition at line 185 of file ISpectrum.h.
sharedY()
virtual Kernel::cow_ptr< HistogramData::HistogramY > Mantid::API::ISpectrum::sharedY () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 186 of file ISpectrum.h.
size()
size_t Mantid::API::ISpectrum::size () const inline
Definition at line 201 of file ISpectrum.h.
x()
const HistogramData::HistogramX & Mantid::API::ISpectrum::x () const inline
Definition at line 171 of file ISpectrum.h.
Referenced by Mantid::Algorithms::PolarizationCorrectionWildes::checkConsistentX(), and Mantid::Algorithms::Integration::integrateSpectrum().
y()
virtual const HistogramData::HistogramY & Mantid::API::ISpectrum::y () const inline virtual
Reimplemented in Mantid::DataObjects::EventList.
Definition at line 172 of file ISpectrum.h.
Referenced by Mantid::Algorithms::PolarizationCorrectionWildes::analyzerlessCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::directBeamCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::fullCorrections(), Mantid::Algorithms::Integration::integrateSpectrum(), Mantid::Algorithms::PolarizationCorrectionWildes::threeInputsSolve01(), Mantid::Algorithms::PolarizationCorrectionWildes::threeInputsSolve10(), and Mantid::Algorithms::PolarizationCorrectionWildes::twoInputsSolve01And10().
yMode()
HistogramData::Histogram::YMode Mantid::API::ISpectrum::yMode () const inline
Definition at line 104 of file ISpectrum.h.
Referenced by Mantid::Algorithms::Integration::integrateSpectrum(), and Mantid::API::MatrixWorkspace::isDistribution().
Member Data Documentation
detectorIDs
std::set<detid_t> Mantid::API::ISpectrum::detectorIDs private
Set of the detector IDs associated with this spectrum.
Definition at line 235 of file ISpectrum.h.
Referenced by addDetectorID(), addDetectorIDs(), addDetectorIDs(), clearDetectorIDs(), copyInfoFrom(), getDetectorIDs(), hasDetectorID(), operator=(), operator=(), setDetectorID(), setDetectorIDs(), and setDetectorIDs().
m_index
size_t Mantid::API::ISpectrum::m_index {0} private
Definition at line 229 of file ISpectrum.h.
Referenced by invalidateSpectrumDefinition(), and setMatrixWorkspace().
m_matrixWorkspace
MatrixWorkspace* Mantid::API::ISpectrum::m_matrixWorkspace {nullptr} private
Definition at line 227 of file ISpectrum.h.
Referenced by invalidateCachedSpectrumNumbers(), invalidateSpectrumDefinition(), and setMatrixWorkspace().
m_specNo
specnum_t Mantid::API::ISpectrum::m_specNo {0} private
The spectrum number of this spectrum.
Definition at line 232 of file ISpectrum.h.
Referenced by copyInfoFrom(), getSpectrumNo(), operator=(), operator=(), and setSpectrumNo().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/ISpectrum.h
Framework/API/src/ISpectrum.cpp