Mantid: Mantid::FrameworkTestHelpers Namespace Reference
Mantid::FrameworkTestHelpers Namespace Reference
Namespaces
namespace JSONTestInstrumentBuilder
Classes
class FunctionChangesNParams
class MockONCatAPI
class MockTokenStore
class MultiDomainFunctionTest_Function
Typedefs
using MockResponseCallCounts = std::map< std::string, unsigned int >
using MockResponseCallMapping = std::pair< const std::basic_string< char >, unsigned int >
using MockResponseMap = std::map< std::string, std::pair< InternetHelper::HTTPStatus, std::string > >
Functions
void applyPolarizationEfficiencies (const WorkspaceGroup_sptr &ws)
void applyPolarizationEfficiencies (std::string const &name)
MatrixWorkspace_sptr createHistoWS (size_t nBins, double startX, double endX, std::vector< double > const &values, std::string const &unitX="TOF")
MatrixWorkspace_sptr createREFL_WS (size_t nBins, double startX, double endX, std::vector< double > const &values, std::string const &paramsType="", std::string const &instrumentSuffix="")
MatrixWorkspace_sptr createWorkspaceSingle (const double startX, const int nBins, const double deltaX, const std::vector< double > &yValues)
MatrixWorkspace_sptr createWorkspaceSingle (const double startX=1, const int nBins=3, const double deltaX=1)
std::string getFullJSONInstrumentSimpleCylindrical ()
std::string getFullJSONInstrumentSimpleOFF ()
std::string getFullJSONInstrumentSimpleWithChopper ()
std::string getFullJSONInstrumentSimpleWithMonitor ()
std::string getFullJSONInstrumentSimpleWithMonitorNoShape ()
std::string getFullJSONInstrumentSimpleWithSource ()
std::string getFullJSONInstrumentSimpleWithZPixelOffset ()
std::string getJSONGeometryEmptyCylindricalGeometry ()
std::string getJSONGeometryEmptyOffGeometry ()
std::string getJSONGeometryInvalidCylindricalGeometry ()
std::string getJSONGeometryInvalidOffGeometry ()
std::string getJSONGeometryMissingBeamDirectionOffset ()
std::string getJSONGeometryMissingChopperInformation ()
std::string getJSONGeometryMissingMonitorInformation ()
std::string getJSONGeometryMissingOrientation ()
std::string getJSONGeometryMissingTransformations ()
std::string getJSONGeometryNoDetectorIDs ()
std::string getJSONGeometryNoDetectors ()
std::string getJSONGeometryNoInstrument ()
std::string getJSONGeometryNoPixelShape ()
std::string getJSONGeometryNoSample ()
std::string getJSONGeometryNoXPixelOffset ()
std::string getJSONGeometryNoYPixelOffset ()
std::vector< MatrixWorkspace_sptr > groupToVector (const WorkspaceGroup_sptr &group)
std::shared_ptr< MockONCatAPI > make_mock_oncat_api (const MockResponseMap &responseMap)
IOAuthTokenStore_uptr make_mock_token_store ()
IOAuthTokenStore_uptr make_mock_token_store_already_logged_in ()
std::unique_ptr< ONCat > make_oncat_with_mock_api (const std::shared_ptr< MockONCatAPI > &mockAPI)
std::shared_ptr< Mantid::API::JointDomain > makeMultiDomainDomain3 ()
std::shared_ptr< Mantid::API::MultiDomainFunction > makeMultiDomainFunction3 ()
Mantid::API::MatrixWorkspace_sptr makeMultiDomainWorkspace1 ()
Mantid::API::MatrixWorkspace_sptr makeMultiDomainWorkspace2 ()
Mantid::API::MatrixWorkspace_sptr makeMultiDomainWorkspace3 ()
void prepareInputGroup (std::string const &name, std::string const &paramsType="", size_t size=4, double const startX=5000.0, double const endX=100000.0, size_t const nBins=10)
std::vector< MatrixWorkspace_sptr > retrieveOutWS (std::string const &name)
Variables
const double A0 = 0.5
const double A1 = -4
const double A2 = 4
const double B0 = 5
const double B1 = -20
const double B2 = 16
const double dX = 0.2
const size_t nbins = 10
Typedef Documentation
MockResponseCallCounts
using Mantid::FrameworkTestHelpers::MockResponseCallCounts = typedef std::map<std::string, unsigned int>
Definition at line 27 of file ONCatHelper.h.
MockResponseCallMapping
using Mantid::FrameworkTestHelpers::MockResponseCallMapping = typedef std::pair<const std::basic_string<char>, unsigned int>
Definition at line 28 of file ONCatHelper.h.
MockResponseMap
using Mantid::FrameworkTestHelpers::MockResponseMap = typedef std::map<std::string, std::pair<InternetHelper::HTTPStatus, std::string> >
Definition at line 26 of file ONCatHelper.h.
Function Documentation
applyPolarizationEfficiencies() [1/2]
void Mantid::FrameworkTestHelpers::applyPolarizationEfficiencies (const WorkspaceGroup_sptr & ws)
Definition at line 120 of file ReflectometryHelper.cpp.
References createHistoWS(), and groupToVector().
applyPolarizationEfficiencies() [2/2]
void Mantid::FrameworkTestHelpers::applyPolarizationEfficiencies (std::string const & name)
Definition at line 163 of file ReflectometryHelper.cpp.
References applyPolarizationEfficiencies(), group, and name.
Referenced by applyPolarizationEfficiencies().
createHistoWS()
MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::createHistoWS (size_t nBins, double startX, double endX, std::vector< double > const & values, std::string const & unitX = "TOF")
Definition at line 33 of file ReflectometryHelper.cpp.
References dX, and workspace.
Referenced by applyPolarizationEfficiencies(), and createREFL_WS().
createREFL_WS()
MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::createREFL_WS (size_t nBins, double startX, double endX, std::vector< double > const & values, std::string const & paramsType = "", std::string const & instrumentSuffix = "")
Definition at line 56 of file ReflectometryHelper.cpp.
References createHistoWS(), and workspace.
Referenced by prepareInputGroup().
createWorkspaceSingle() [1/2]
MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::createWorkspaceSingle (const double startX, const int nBins, const double deltaX, const std::vector< double > & yValues)
Definition at line 168 of file ReflectometryHelper.cpp.
References WorkspaceCreationHelper::create2DWorkspaceWithReflectometryInstrumentMultiDetector().
createWorkspaceSingle() [2/2]
MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::createWorkspaceSingle (const double startX = 1, const int nBins = 3, const double deltaX = 1)
Definition at line 184 of file ReflectometryHelper.cpp.
References WorkspaceCreationHelper::create2DWorkspaceWithReflectometryInstrumentMultiDetector().
getFullJSONInstrumentSimpleCylindrical()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical ()
Definition at line 681 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleOFF()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF ()
Definition at line 619 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleWithChopper()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper ()
Definition at line 708 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopper(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperRadius(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlitEdges(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlitHeight(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlits(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperTopDeadCenter(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleWithMonitor()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor ()
Definition at line 784 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitor(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorDetectorID(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorEventStreamInfo(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorWaveformStreamInfo(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleWithMonitorNoShape()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape ()
Definition at line 745 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitor(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorDetectorID(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorEventStreamInfo(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorWaveformStreamInfo(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleWithSource()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource ()
Definition at line 647 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSource(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getFullJSONInstrumentSimpleWithZPixelOffset()
std::string Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset ()
Definition at line 827 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addZPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryEmptyCylindricalGeometry()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry ()
Definition at line 455 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryEmptyOffGeometry()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry ()
Definition at line 421 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryInvalidCylindricalGeometry()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry ()
Definition at line 470 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryInvalidOffGeometry()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry ()
Definition at line 436 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryMissingBeamDirectionOffset()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset ()
Definition at line 512 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryMissingChopperInformation()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation ()
Definition at line 591 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopper(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryMissingMonitorInformation()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation ()
Definition at line 563 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitor(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryMissingOrientation()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation ()
Definition at line 537 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryMissingTransformations()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations ()
Definition at line 489 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoDetectorIDs()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs ()
Definition at line 369 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoDetectors()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors ()
Definition at line 359 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoInstrument()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoInstrument ()
Definition at line 350 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoPixelShape()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape ()
Definition at line 407 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoSample()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoSample ()
Definition at line 343 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoXPixelOffset()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset ()
Definition at line 380 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
getJSONGeometryNoYPixelOffset()
std::string Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset ()
Definition at line 393 of file JSONGeometryParserTestHelper.cpp.
References Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset(), Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString(), and Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot().
groupToVector()
std::vector< MatrixWorkspace_sptr > Mantid::FrameworkTestHelpers::groupToVector (const WorkspaceGroup_sptr & group)
Definition at line 107 of file ReflectometryHelper.cpp.
References group.
Referenced by applyPolarizationEfficiencies(), and retrieveOutWS().
make_mock_oncat_api()
std::shared_ptr< MockONCatAPI > Mantid::FrameworkTestHelpers::make_mock_oncat_api (const MockResponseMap & responseMap)
make_mock_token_store()
IOAuthTokenStore_uptr Mantid::FrameworkTestHelpers::make_mock_token_store ()
Definition at line 84 of file ONCatHelper.cpp.
make_mock_token_store_already_logged_in()
IOAuthTokenStore_uptr Mantid::FrameworkTestHelpers::make_mock_token_store_already_logged_in ()
Definition at line 86 of file ONCatHelper.cpp.
make_oncat_with_mock_api()
DOXYGEN_BUG std::unique_ptr< ONCat > Mantid::FrameworkTestHelpers::make_oncat_with_mock_api (const std::shared_ptr< MockONCatAPI > & mockAPI)
Definition at line 72 of file ONCatHelper.cpp.
makeMultiDomainDomain3()
std::shared_ptr< Mantid::API::JointDomain > Mantid::FrameworkTestHelpers::makeMultiDomainDomain3 ()
Definition at line 87 of file MultiDomainFunctionHelper.cpp.
makeMultiDomainFunction3()
std::shared_ptr< Mantid::API::MultiDomainFunction > Mantid::FrameworkTestHelpers::makeMultiDomainFunction3 ()
Definition at line 65 of file MultiDomainFunctionHelper.cpp.
makeMultiDomainWorkspace1()
Mantid::API::MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::makeMultiDomainWorkspace1 ()
Definition at line 101 of file MultiDomainFunctionHelper.cpp.
References A0, A1, A2, B0, B1, B2, dX, nbins, Mantid::Geometry::x, and Mantid::Geometry::y.
makeMultiDomainWorkspace2()
Mantid::API::MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::makeMultiDomainWorkspace2 ()
Definition at line 117 of file MultiDomainFunctionHelper.cpp.
References A0, A1, B0, B1, dX, nbins, Mantid::Geometry::x, and Mantid::Geometry::y.
makeMultiDomainWorkspace3()
Mantid::API::MatrixWorkspace_sptr Mantid::FrameworkTestHelpers::makeMultiDomainWorkspace3 ()
Definition at line 133 of file MultiDomainFunctionHelper.cpp.
References A0, A2, B0, B2, dX, nbins, Mantid::Geometry::x, and Mantid::Geometry::y.
prepareInputGroup()
void Mantid::FrameworkTestHelpers::prepareInputGroup (std::string const & name, std::string const & paramsType = "", size_t size = 4, double const startX = 5000.0, double const endX = 100000.0, size_t const nBins = 10)
Definition at line 79 of file ReflectometryHelper.cpp.
References createREFL_WS(), name, and std::to_string().
retrieveOutWS()
std::vector< MatrixWorkspace_sptr > Mantid::FrameworkTestHelpers::retrieveOutWS (std::string const & name)
Definition at line 115 of file ReflectometryHelper.cpp.
References group, groupToVector(), and name.
Variable Documentation
A0
const double Mantid::FrameworkTestHelpers::A0 = 0.5
Definition at line 96 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), makeMultiDomainWorkspace2(), and makeMultiDomainWorkspace3().
A1
const double Mantid::FrameworkTestHelpers::A1 = -4
Definition at line 96 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), and makeMultiDomainWorkspace2().
A2
const double Mantid::FrameworkTestHelpers::A2 = 4
Definition at line 96 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), and makeMultiDomainWorkspace3().
B0
const double Mantid::FrameworkTestHelpers::B0 = 5
Definition at line 97 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), makeMultiDomainWorkspace2(), and makeMultiDomainWorkspace3().
B1
const double Mantid::FrameworkTestHelpers::B1 = -20
Definition at line 97 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), and makeMultiDomainWorkspace2().
B2
const double Mantid::FrameworkTestHelpers::B2 = 16
Definition at line 97 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), and makeMultiDomainWorkspace3().
dX
const double Mantid::FrameworkTestHelpers::dX = 0.2
Definition at line 99 of file MultiDomainFunctionHelper.cpp.
Referenced by createHistoWS(), makeMultiDomainWorkspace1(), makeMultiDomainWorkspace2(), and makeMultiDomainWorkspace3().
nbins
const size_t Mantid::FrameworkTestHelpers::nbins = 10
Definition at line 98 of file MultiDomainFunctionHelper.cpp.
Referenced by makeMultiDomainWorkspace1(), makeMultiDomainWorkspace2(), and makeMultiDomainWorkspace3().