Mantid: Mantid::Kernel::EnumeratedString< E, names, stringComparator > Class Template Reference
Mantid::Kernel::EnumeratedString< E, names, stringComparator > Class Template Reference
#include <EnumeratedString.h>
Public Member Functions
const char * c_str () const
EnumeratedString ()
EnumeratedString (const E e)
EnumeratedString (const EnumeratedString &es)
EnumeratedString (const std::string &s)
operator E () const
operator std::string () const
bool operator!= (const char *s) const
bool operator!= (const E e) const
bool operator!= (const EnumeratedString &es) const
template<typename OtherEnumType , const std::vector< std::string > * OtherEnumStrings>
bool operator!= (const EnumeratedString< OtherEnumType, OtherEnumStrings > &other) const
bool operator!= (const std::string &s) const
EnumeratedString & operator= (const EnumeratedString &other)=default
EnumeratedString & operator= (const std::string &s)
EnumeratedString & operator= (E e)
bool operator== (const char *s) const
bool operator== (const E e) const
bool operator== (const EnumeratedString &es) const
template<typename OtherEnumType , const std::vector< std::string > * OtherEnumStrings>
bool operator== (const EnumeratedString< OtherEnumType, OtherEnumStrings > &) const
bool operator== (const std::string &s) const
Static Public Member Functions
static size_t size ()
Private Member Functions
void ensureCompatibleSize ()
E findEFromString (const std::string &s)
Private Attributes
std::string name
E value
Detailed Description
template<class E, const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings>
class Mantid::Kernel::EnumeratedString< E, names, stringComparator >
Definition at line 33 of file EnumeratedString.h.
Constructor & Destructor Documentation
EnumeratedString() [1/4]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString () inline
Template Parameters
class E an enum, the final value must be enum_count (i.e. enum class Fruit {apple, orange, enum_count})
a pointer to a static vector of string names for each enum The enum and string array must have same order.
an optional pointer to a statically defined string comparator.
Definition at line 46 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::ensureCompatibleSize().
EnumeratedString() [2/4]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString (const E e) inline
Definition at line 48 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::ensureCompatibleSize(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=().
EnumeratedString() [3/4]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString (const std::string & s) inline
Definition at line 53 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::ensureCompatibleSize(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=().
EnumeratedString() [4/4]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString (const EnumeratedString< E, names, stringComparator > & es) inline
Definition at line 58 of file EnumeratedString.h.
Member Function Documentation
c_str()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> const char * Mantid::Kernel::EnumeratedString< E, names, stringComparator >::c_str () const inline
Definition at line 116 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
ensureCompatibleSize()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> void Mantid::Kernel::EnumeratedString< E, names, stringComparator >::ensureCompatibleSize () inline private
Definition at line 132 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
Referenced by Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString().
findEFromString()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> E Mantid::Kernel::EnumeratedString< E, names, stringComparator >::findEFromString (const std::string & s) inline private
Definition at line 124 of file EnumeratedString.h.
Referenced by Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=().
operator E()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator E () const inline
Definition at line 61 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator std::string()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator std::string () const inline
Definition at line 62 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
operator!=() [1/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!= (const char * s) const inline
Definition at line 101 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
operator!=() [2/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!= (const E e) const inline
Definition at line 95 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator!=() [3/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!= (const EnumeratedString< E, names, stringComparator > & es) const inline
Definition at line 104 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator!=() [4/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> template<typename OtherEnumType , const std::vector< std::string > * OtherEnumStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!= (const EnumeratedString< OtherEnumType, OtherEnumStrings > & other) const inline
Definition at line 112 of file EnumeratedString.h.
operator!=() [5/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!= (const std::string & s) const inline
Definition at line 98 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
operator=() [1/3]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> EnumeratedString & Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator= (const EnumeratedString< E, names, stringComparator > & other) default
Referenced by Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::EnumeratedString().
operator=() [2/3]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> EnumeratedString & Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator= (const std::string & s) inline
Definition at line 77 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::findEFromString(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name, and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator=() [3/3]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> EnumeratedString & Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator= (E e) inline
Definition at line 66 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name, and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator==() [1/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator== (const char * s) const inline
Definition at line 100 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
operator==() [2/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator== (const E e) const inline
Definition at line 94 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator==() [3/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator== (const EnumeratedString< E, names, stringComparator > & es) const inline
Definition at line 103 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value.
operator==() [4/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> template<typename OtherEnumType , const std::vector< std::string > * OtherEnumStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator== (const EnumeratedString< OtherEnumType, OtherEnumStrings > &) const inline
Definition at line 107 of file EnumeratedString.h.
operator==() [5/5]
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> bool Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator== (const std::string & s) const inline
Definition at line 97 of file EnumeratedString.h.
References Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name.
size()
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> static size_t Mantid::Kernel::EnumeratedString< E, names, stringComparator >::size () inline static
Definition at line 117 of file EnumeratedString.h.
Member Data Documentation
name
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> std::string Mantid::Kernel::EnumeratedString< E, names, stringComparator >::name private
Definition at line 121 of file EnumeratedString.h.
Referenced by Mantid::Kernel::EnumeratedString< E, names, stringComparator >::c_str(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::ensureCompatibleSize(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator std::string(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator==(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator==().
value
template<class E , const std::vector< std::string > * names, std::function< bool(const std::string &, const std::string &)> * stringComparator = &compareStrings> E Mantid::Kernel::EnumeratedString< E, names, stringComparator >::value private
Definition at line 120 of file EnumeratedString.h.
Referenced by Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator E(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator!=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator=(), Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator==(), and Mantid::Kernel::EnumeratedString< E, names, stringComparator >::operator==().
The documentation for this class was generated from the following file:
Framework/Kernel/inc/MantidKernel/EnumeratedString.h