Mantid: Mantid::Algorithms::PolarizationCorrectionWildes Class Reference
Mantid::Algorithms::PolarizationCorrectionWildes Class Reference final
PolarizationCorrectionWildes : This algorithm corrects for non-ideal component efficiencies in polarized neutron analysis.
#include <PolarizationCorrectionWildes.h>
Classes
struct EfficiencyMap
A convenience set of efficiency factors.
struct WorkspaceMap
A convenience set of workspaces corresponding flipper configurations.
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
Algorithm's related algorithms.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void addSpinStateLogToWs (const API::MatrixWorkspace_sptr &ws, const std::string &spinState, const bool hasAnalyser)
Adds a sample log to the workspace that gives the spin state of the data using Reflectometry ORSO notation.
void addSpinStateOutput (std::vector< std::string > &names, const std::string &spinStateOrder, const std::string &baseName, const API::MatrixWorkspace_sptr &ws, const std::string &spinState, const bool addSpinStateLog, const bool hasAnalyser)
Add an output name in the correct position in the vector and to the ADS.
WorkspaceMap analyzerlessCorrections (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Correct for non-ideal instrument effects.
void checkConsistentNumberHistograms (const WorkspaceMap &inputs)
Check that all workspaces in inputs have the same number of histograms.
void checkConsistentX (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Check that all workspaces and efficicencies have the same X data.
WorkspaceMap directBeamCorrections (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Correct a direct beam measurement for non-ideal instrument effects.
EfficiencyMap efficiencyFactors ()
Make a convenience access object to the efficiency factors.
void exec () override
Execute the algorithm.
WorkspaceMap fullCorrections (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Correct for non-ideal instrument effects.
API::WorkspaceGroup_sptr groupOutput (const WorkspaceMap &outputs, const bool hasAnalyser)
Make a workspace group out of the given set of workspaces.
void init () override
Initialize the algorithm's properties.
WorkspaceMap mapInputsToDirections (const std::vector< std::string > &flippers)
Make a set of workspaces to correct from input properties.
WorkspaceMap threeInputCorrections (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Correct for non-ideal instrument effects.
void threeInputsSolve01 (WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Solve in-place the 01 flipper configuration from the assumption that for the corrected intensities, R01 = R10.
void threeInputsSolve10 (WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Solve in-place the 10 flipper configuration from the assumption that for the corrected intensities R01 = R10.
WorkspaceMap twoInputCorrections (const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Correct for non-ideal instrument effects.
void twoInputsSolve01And10 (WorkspaceMap &fullInputs, const WorkspaceMap &inputs, const EfficiencyMap &efficiencies)
Solve in-place the 01 and 10 flipper configurations from the assumption that for the corrected intensities R01 = R10 = 0.
std::map< std::string, std::string > validateInputs () override
Validate the algorithm's input properties.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
PolarizationCorrectionWildes : This algorithm corrects for non-ideal component efficiencies in polarized neutron analysis.
It is based on [A. R. Wildes (2006) Neutron News, 17:2, 17-25, DOI: 10.1080/10448630600668738]
Definition at line 26 of file PolarizationCorrectionWildes.h.
Member Function Documentation
addSpinStateLogToWs()
void Mantid::Algorithms::PolarizationCorrectionWildes::addSpinStateLogToWs (const API::MatrixWorkspace_sptr & ws, const std::string & spinState, const bool hasAnalyser) private
Adds a sample log to the workspace that gives the spin state of the data using Reflectometry ORSO notation.
Parameters
ws The workspace to add the sample log to.
spinState The spin state the workspace represents.
hasAnalyser Whether the flipper configuration included an analyser.
Definition at line 605 of file PolarizationCorrectionWildes.cpp.
References Mantid::Algorithms::SpinStatesORSO::addORSOLogForSpinState(), Mantid::Algorithms::SpinStateConfigurationsWildes::MINUS, Mantid::Algorithms::SpinStateConfigurationsWildes::MINUS_MINUS, Mantid::Algorithms::SpinStateConfigurationsWildes::PLUS, and Mantid::Algorithms::SpinStateConfigurationsWildes::PLUS_PLUS.
Referenced by addSpinStateOutput().
addSpinStateOutput()
void Mantid::Algorithms::PolarizationCorrectionWildes::addSpinStateOutput (std::vector< std::string > & names, const std::string & spinStateOrder, const std::string & baseName, const API::MatrixWorkspace_sptr & ws, const std::string & spinState, const bool addSpinStateLog, const bool hasAnalyser) private
Add an output name in the correct position in the vector and to the ADS.
Optionally adds a spin state log to the output workspace.
Parameters
names A list of the names of the workspaces the algorithm has generated.
spinStateOrder The order the output should be in.
baseName The base name for the output workspaces ("BASENAME_SPINSTATE" e.g "OUTNAME_+-")
ws The workspace to add to the vector and ADS.
spinState The spin state the workspace represents.
addSpinStateLog Whether to add a sample log to the output workspace giving the spin state using the Reflectometry ORSO notation.
hasAnalyser Whether the flipper configuration included an analyser.
Definition at line 575 of file PolarizationCorrectionWildes.cpp.
References addSpinStateLogToWs(), index, Mantid::Kernel::SpinStateHelpers::indexOfWorkspaceForSpinState(), and Mantid::Kernel::SpinStateHelpers::splitSpinStateString().
Referenced by groupOutput().
analyzerlessCorrections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::analyzerlessCorrections (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Correct for non-ideal instrument effects.
Deals with the case when the data was taken without the analyzer: only the polarizer flipper is used.
Parameters
inputs a set of workspaces to correct
efficiencies a set of efficiency factors
Returns
a set of corrected workspaces
Definition at line 698 of file PolarizationCorrectionWildes.cpp.
References Mantid::API::ISpectrum::e(), Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::FlipperConfigurations::OFF, Mantid::Algorithms::FlipperConfigurations::ON, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by exec().
category()
const std::string Mantid::Algorithms::PolarizationCorrectionWildes::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Implements Mantid::API::IAlgorithm.
Definition at line 300 of file PolarizationCorrectionWildes.cpp.
checkConsistentNumberHistograms()
void Mantid::Algorithms::PolarizationCorrectionWildes::checkConsistentNumberHistograms (const WorkspaceMap & inputs) private
Check that all workspaces in inputs have the same number of histograms.
Parameters
inputs a set of workspaces to check
Definition at line 444 of file PolarizationCorrectionWildes.cpp.
References Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, and Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS.
Referenced by exec().
checkConsistentX()
void Mantid::Algorithms::PolarizationCorrectionWildes::checkConsistentX (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Check that all workspaces and efficicencies have the same X data.
Parameters
inputs a set of workspaces to check
efficiencies efficiencies to check
Definition at line 477 of file PolarizationCorrectionWildes.cpp.
References Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::API::ISpectrum::x(), and Mantid::Geometry::x.
Referenced by exec().
directBeamCorrections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::directBeamCorrections (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Correct a direct beam measurement for non-ideal instrument effects.
Only the non-analyzer, polarizer flipper off case is considered here.
Parameters
inputs a set of workspaces to correct
efficiencies a set of efficiency factors
Returns
set of corrected workspaces
Definition at line 654 of file PolarizationCorrectionWildes.cpp.
References Mantid::API::ISpectrum::e(), Mantid::Algorithms::FlipperConfigurations::OFF, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by exec().
efficiencyFactors()
PolarizationCorrectionWildes::EfficiencyMap Mantid::Algorithms::PolarizationCorrectionWildes::efficiencyFactors () private
Make a convenience access object to the efficiency factors.
Returns
an EfficiencyMap object
Definition at line 626 of file PolarizationCorrectionWildes.cpp.
References Prop::EFFICIENCIES, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::API::Algorithm::getProperty(), Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, and Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2.
Referenced by exec().
exec()
void Mantid::Algorithms::PolarizationCorrectionWildes::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 354 of file PolarizationCorrectionWildes.cpp.
References analyzerlessCorrections(), checkConsistentNumberHistograms(), checkConsistentX(), directBeamCorrections(), efficiencyFactors(), fullCorrections(), Mantid::API::Algorithm::getProperty(), groupOutput(), mapInputsToDirections(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::Kernel::SpinStateHelpers::splitSpinStateString(), threeInputCorrections(), and twoInputCorrections().
fullCorrections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::fullCorrections (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Correct for non-ideal instrument effects.
Perform full polarization corrections. All flipper configurations (00, 01, 10 and 11) are needed for this.
Parameters
inputs a set of workspaces to correct
efficiencies a set of efficiency factors
Returns
a set of corrected workspaces
Definition at line 813 of file PolarizationCorrectionWildes.cpp.
References Mantid::API::ISpectrum::e(), Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by exec(), threeInputCorrections(), and twoInputCorrections().
groupOutput()
API::WorkspaceGroup_sptr Mantid::Algorithms::PolarizationCorrectionWildes::groupOutput (const WorkspaceMap & outputs, const bool hasAnalyser) private
Make a workspace group out of the given set of workspaces.
The workspaces will be published in the ADS, their names appended by appropriate suffices.
Parameters
outputs a set of workspaces to group
hasAnalyser whether the flipper configuration included an analyser.
Returns
a group workspace
Definition at line 526 of file PolarizationCorrectionWildes.cpp.
References Prop::ADD_SPIN_STATE_LOG, addSpinStateOutput(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), group, Mantid::Algorithms::SpinStateConfigurationsWildes::MINUS_MINUS, Mantid::Algorithms::SpinStateConfigurationsWildes::MINUS_PLUS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::SpinStateConfigurationsWildes::PLUS_MINUS, Mantid::Algorithms::SpinStateConfigurationsWildes::PLUS_PLUS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, and Mantid::Kernel::SpinStateHelpers::splitSpinStateString().
Referenced by exec().
init()
void Mantid::Algorithms::PolarizationCorrectionWildes::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 324 of file PolarizationCorrectionWildes.cpp.
References Prop::ADD_SPIN_STATE_LOG, Mantid::API::Algorithm::declareProperty(), Prop::EFFICIENCIES, Mantid::Kernel::Direction::Input, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, and Mantid::Kernel::Direction::Output.
mapInputsToDirections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::mapInputsToDirections (const std::vector< std::string > & flippers) private
Make a set of workspaces to correct from input properties.
Parameters
flippers a vector of flipper configurations
Returns
a set of workspaces to correct
Definition at line 884 of file PolarizationCorrectionWildes.cpp.
References Mantid::API::Algorithm::getProperty(), Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, and Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS.
Referenced by exec().
name()
const std::string Mantid::Algorithms::PolarizationCorrectionWildes::name () const override virtual
Algorithms name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 294 of file PolarizationCorrectionWildes.cpp.
seeAlso()
const std::vector< std::string > Mantid::Algorithms::PolarizationCorrectionWildes::seeAlso () const override virtual
Algorithm's related algorithms.
See also
Algorithm::seeAlso
Implements Mantid::API::IAlgorithm.
Definition at line 309 of file PolarizationCorrectionWildes.cpp.
summary()
const std::string Mantid::Algorithms::PolarizationCorrectionWildes::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 303 of file PolarizationCorrectionWildes.cpp.
threeInputCorrections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::threeInputCorrections (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Correct for non-ideal instrument effects.
Needs the 00 and 11 flipper configurations as well as either 01 or 10. The missing intensity (01 or 10) is solved from the assumption that the corrected R01 = R10.
Parameters
inputs a set of workspaces to correct
efficiencies a set of efficiency factors
Returns
a set of corrected workspaces
Definition at line 790 of file PolarizationCorrectionWildes.cpp.
References fullCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::OFF_ON, Mantid::Algorithms::FlipperConfigurations::ON_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, threeInputsSolve01(), and threeInputsSolve10().
Referenced by exec().
threeInputsSolve01()
void Mantid::Algorithms::PolarizationCorrectionWildes::threeInputsSolve01 (WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Solve in-place the 01 flipper configuration from the assumption that for the corrected intensities, R01 = R10.
Parameters
inputs a set of input workspaces
efficiencies a set of efficiency factors
Definition at line 914 of file PolarizationCorrectionWildes.cpp.
References Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by threeInputCorrections().
threeInputsSolve10()
void Mantid::Algorithms::PolarizationCorrectionWildes::threeInputsSolve10 (WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Solve in-place the 10 flipper configuration from the assumption that for the corrected intensities R01 = R10.
Parameters
inputs a set of input workspaces
efficiencies a set of efficiency factors
Definition at line 955 of file PolarizationCorrectionWildes.cpp.
References Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by threeInputCorrections().
twoInputCorrections()
PolarizationCorrectionWildes::WorkspaceMap Mantid::Algorithms::PolarizationCorrectionWildes::twoInputCorrections (const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Correct for non-ideal instrument effects.
Only 00 and 11 flipper configurations need to be provided; the missing 01 and 10 data is solved from the assumption that in the corrected data, R01 = R10 = 0.
Parameters
inputs a set of workspaces to correct
efficiencies a set of efficiency factors
Returns
a set of corrected workspaces
Definition at line 769 of file PolarizationCorrectionWildes.cpp.
References fullCorrections(), Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::FlipperConfigurations::OFF_OFF, Mantid::Algorithms::FlipperConfigurations::ON_ON, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, and twoInputsSolve01And10().
Referenced by exec().
twoInputsSolve01And10()
void Mantid::Algorithms::PolarizationCorrectionWildes::twoInputsSolve01And10 (WorkspaceMap & fullInputs, const WorkspaceMap & inputs, const EfficiencyMap & efficiencies) private
Solve in-place the 01 and 10 flipper configurations from the assumption that for the corrected intensities R01 = R10 = 0.
Parameters
fullInputs a set of output workspaces
inputs a set of input workspaces
efficiencies a set of efficiency factors
Definition at line 997 of file PolarizationCorrectionWildes.cpp.
References Mantid::Geometry::d, Mantid::API::ISpectrum::e(), Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::F2, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::mpWS, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P1, Mantid::Algorithms::PolarizationCorrectionWildes::EfficiencyMap::P2, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::pmWS, Mantid::Algorithms::PolarizationCorrectionWildes::WorkspaceMap::ppWS, Mantid::Kernel::threadSafe(), and Mantid::API::ISpectrum::y().
Referenced by twoInputCorrections().
validateInputs()
std::map< std::string, std::string > Mantid::Algorithms::PolarizationCorrectionWildes::validateInputs (void) override private virtual
Validate the algorithm's input properties.
Returns
a map from property names to discovered issues
Implements Mantid::API::IAlgorithm.
Definition at line 388 of file PolarizationCorrectionWildes.cpp.
References Prop::EFFICIENCIES, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::SpinStateHelpers::splitSpinStateString(), and std::to_string().
version()
int Mantid::Algorithms::PolarizationCorrectionWildes::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 297 of file PolarizationCorrectionWildes.cpp.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrectionWildes.h
Framework/Algorithms/src/PolarizationCorrectionWildes.cpp