Mantid: Mantid::DataObjects::PeakShapeBase Class Reference
Mantid::DataObjects::PeakShapeBase Class Reference
PeakShapeBase : Base class for concrete PeakShapes containing common code.
#include <PeakShapeBase.h>
Public Member Functions
std::string algorithmName () const override
Get the name of the algorithm used to make this shape.
int algorithmVersion () const override
Get the version of the algorithm used to make this shape.
Kernel::SpecialCoordinateSystem frame () const override
Get the coordinate frame.
PeakShapeBase (Kernel::SpecialCoordinateSystem frame, std::string algorithmName=std::string(), int algorithmVersion=-1)
Constructor.
Public Member Functions inherited from Mantid::Geometry::PeakShape
virtual PeakShape * clone () const =0
Deep copy this.
virtual std::optional< double > radius (RadiusType type) const =0
Radius.
virtual std::string shapeName () const =0
Shape name.
virtual std::string toJSON () const =0
Serialize.
virtual ~PeakShape ()=default
Destructor.
Protected Member Functions
void buildCommon (Json::Value &root) const
Build common parts of outgoing JSON serialization.
PeakShapeBase & operator= (const PeakShapeBase &)=default
Assignment operator.
bool operator== (const PeakShapeBase &other) const
Equals operator.
PeakShapeBase (const PeakShapeBase &)=default
Copy constructor.
Protected Attributes
std::string m_algorithmName
Generating algorithm name.
int m_algorithmVersion
Generating algorithm version.
Mantid::Kernel::SpecialCoordinateSystem m_frame
Special coordinate system.
Additional Inherited Members
Public Types inherited from Mantid::Geometry::PeakShape
enum RadiusType { Radius = 0 , OuterRadius = 1 , InnerRadius = 2 }
For selecting different radius types.
Detailed Description
PeakShapeBase : Base class for concrete PeakShapes containing common code.
Definition at line 26 of file PeakShapeBase.h.
Constructor & Destructor Documentation
PeakShapeBase() [1/2]
Mantid::DataObjects::PeakShapeBase::PeakShapeBase (Kernel::SpecialCoordinateSystem frame, std::string algorithmName = std::string(), int algorithmVersion = -1)
Constructor.
Definition at line 15 of file PeakShapeBase.cpp.
PeakShapeBase() [2/2]
Mantid::DataObjects::PeakShapeBase::PeakShapeBase (const PeakShapeBase &) protected default
Copy constructor.
Member Function Documentation
algorithmName()
std::string Mantid::DataObjects::PeakShapeBase::algorithmName () const override virtual
Get the name of the algorithm used to make this shape.
Get the algorithm name.
Returns
Algorithm name
Implements Mantid::Geometry::PeakShape.
Definition at line 44 of file PeakShapeBase.cpp.
References m_algorithmName.
Referenced by buildCommon().
algorithmVersion()
int Mantid::DataObjects::PeakShapeBase::algorithmVersion () const override virtual
Get the version of the algorithm used to make this shape.
Get the algorithmVersion.
Returns
Algorithm version
Implements Mantid::Geometry::PeakShape.
Definition at line 50 of file PeakShapeBase.cpp.
References m_algorithmVersion.
Referenced by buildCommon().
buildCommon()
void Mantid::DataObjects::PeakShapeBase::buildCommon (Json::Value & root) const protected
Build common parts of outgoing JSON serialization.
PeakShapeBase::buildCommon.
Serialize to JSON object and return the JSON value for further modification
Parameters
root : Ref to root value to write to
Definition at line 29 of file PeakShapeBase.cpp.
References algorithmName(), algorithmVersion(), frame(), and Mantid::Geometry::PeakShape::shapeName().
Referenced by Mantid::DataObjects::PeakShapeDetectorBin::toJSON(), Mantid::DataObjects::PeakShapeEllipsoid::toJSON(), and Mantid::DataObjects::PeakShapeSpherical::toJSON().
frame()
Kernel::SpecialCoordinateSystem Mantid::DataObjects::PeakShapeBase::frame () const override virtual
Get the coordinate frame.
PeakShapeBase::frame.
Returns
The coordinate frame used
Implements Mantid::Geometry::PeakShape.
Definition at line 22 of file PeakShapeBase.cpp.
References m_frame.
Referenced by buildCommon(), and operator==().
operator=()
PeakShapeBase & Mantid::DataObjects::PeakShapeBase::operator= (const PeakShapeBase &) protected default
Assignment operator.
operator==()
bool Mantid::DataObjects::PeakShapeBase::operator== (const PeakShapeBase & other) const protected
Equals operator.
Definition at line 52 of file PeakShapeBase.cpp.
References frame().
Referenced by Mantid::DataObjects::PeakShapeDetectorBin::operator==(), Mantid::DataObjects::PeakShapeEllipsoid::operator==(), and Mantid::DataObjects::PeakShapeSpherical::operator==().
Member Data Documentation
m_algorithmName
std::string Mantid::DataObjects::PeakShapeBase::m_algorithmName protected
Generating algorithm name.
Definition at line 50 of file PeakShapeBase.h.
Referenced by algorithmName().
m_algorithmVersion
int Mantid::DataObjects::PeakShapeBase::m_algorithmVersion protected
Generating algorithm version.
Definition at line 53 of file PeakShapeBase.h.
Referenced by algorithmVersion().
m_frame
Mantid::Kernel::SpecialCoordinateSystem Mantid::DataObjects::PeakShapeBase::m_frame protected
Special coordinate system.
Definition at line 47 of file PeakShapeBase.h.
Referenced by frame().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/PeakShapeBase.h
Framework/DataObjects/src/PeakShapeBase.cpp