Mantid: Mantid::Kernel::Units::MomentumTransfer Class Reference
Mantid::Kernel::Units::MomentumTransfer Class Reference
Momentum Transfer in Angstrom^-1.
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
MomentumTransfer ()
Constructor.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"MomentumTransfer"
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Protected Member Functions
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes
double difc
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Momentum Transfer in Angstrom^-1.
Definition at line 437 of file Unit.h.
Constructor & Destructor Documentation
MomentumTransfer()
Mantid::Kernel::Units::MomentumTransfer::MomentumTransfer ()
Constructor.
Definition at line 839 of file Unit.cpp.
References Mantid::Kernel::Unit::addConversion().
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::MomentumTransfer::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 440 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::MomentumTransfer::clone () const override virtual
Returns
a cloned instance of the other
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 878 of file Unit.cpp.
References MomentumTransfer().
conversionTOFMax()
double Mantid::Kernel::Units::MomentumTransfer::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 876 of file Unit.cpp.
conversionTOFMin()
double Mantid::Kernel::Units::MomentumTransfer::conversionTOFMin () const override virtual
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 875 of file Unit.cpp.
References difc.
init()
void Mantid::Kernel::Units::MomentumTransfer::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Implements Mantid::Kernel::Unit.
Definition at line 855 of file Unit.cpp.
References Mantid::Kernel::difc, difc, Mantid::Kernel::Unit::l1, Mantid::Kernel::l2, Mantid::Kernel::Unit::m_params, Mantid::Kernel::Units::tofToDSpacingFactor(), and Mantid::Kernel::twoTheta.
label()
const UnitLabel Mantid::Kernel::Units::MomentumTransfer::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 837 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::InverseAngstrom.
singleFromTOF()
double Mantid::Kernel::Units::MomentumTransfer::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 873 of file Unit.cpp.
References difc.
Referenced by Mantid::Kernel::Units::QSquared::singleFromTOF().
singleToTOF()
double Mantid::Kernel::Units::MomentumTransfer::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Definition at line 871 of file Unit.cpp.
References difc, and Mantid::Geometry::x.
Referenced by Mantid::Kernel::Units::QSquared::singleToTOF().
unitID()
const std::string Mantid::Kernel::Units::MomentumTransfer::unitID () const override virtual
"MomentumTransfer"
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::QSquared.
Referenced by validateUnitParams().
validateUnitParams()
void Mantid::Kernel::Units::MomentumTransfer::validateUnitParams (const int emode, const UnitParametersMap & params) override protected virtual
Reimplemented from Mantid::Kernel::Unit.
Definition at line 845 of file Unit.cpp.
References Mantid::Kernel::difc, difc, Mantid::Kernel::l2, Mantid::Kernel::twoTheta, and unitID().
Member Data Documentation
difc
double Mantid::Kernel::Units::MomentumTransfer::difc protected
Definition at line 454 of file Unit.h.
Referenced by Mantid::Kernel::Units::QSquared::conversionTOFMax(), conversionTOFMin(), Mantid::Kernel::Units::QSquared::conversionTOFMin(), init(), singleFromTOF(), singleToTOF(), and validateUnitParams().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp