Mantid: MantidQt::MantidWidgets::SelectFunctionDialog Class Reference
MantidQt::MantidWidgets::SelectFunctionDialog Class Reference
Select a function type out of a list of available ones.
#include <SelectFunctionDialog.h>
Public Member Functions
void clearSearchBoxText () const
Clear the text in the search box.
QString getFunction () const
Return selected function.
SelectFunctionDialog (QWidget *parent, const std::vector< std::string > &restrictions)
Constructor overload with categories to restrict to.
SelectFunctionDialog (QWidget *parent=nullptr)
Default constructor.
~SelectFunctionDialog () override
Public Member Functions inherited from MantidQt::API::MantidDialog
MantidDialog (QWidget *parent=nullptr, const Qt::WindowFlags &flags=Qt::WindowCloseButtonHint|Qt::WindowType::WindowTitleHint)
DefaultConstructor.
~MantidDialog () override
Destructor.
Protected Attributes
Ui::SelectFunctionDialog * m_form
Ui elements form.
Private Slots
void acceptFunction ()
void functionDoubleClicked (QTreeWidgetItem *item)
void helpClicked () const
void rejectFunction ()
void searchBoxChanged (const QString &text)
Called when the text in the search box changes.
Private Member Functions
void addSearchBoxFunctionNames (const std::vector< std::string > &registeredFunctions)
Complete QComboBox for searching functions with available functions.
void constructFunctionTree (const std::map< std::string, std::vector< std::string > > &categoryFunctionsMap, const std::vector< std::string > &restrictions)
Construct QTreeWidget with categories and functions.
void setMinimumHeightOfFunctionTree ()
Sets the minimum height of the function tree so that all catagories are visible.
Additional Inherited Members
Signals inherited from MantidQt::API::MantidDialog
void runAsPythonScript (const QString &code, bool)
Static Public Member Functions inherited from MantidQt::API::MantidDialog
static bool handle (QObject *receiver, const std::exception &e)
Handles the exception caught in an event handler.
Protected Member Functions inherited from MantidQt::API::MantidDialog
virtual void handleException (const std::exception &e)
Override this method to handle an exception in a derived class.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Detailed Description
Select a function type out of a list of available ones.
Definition at line 29 of file SelectFunctionDialog.h.
Constructor & Destructor Documentation
SelectFunctionDialog() [1/2]
MantidQt::MantidWidgets::SelectFunctionDialog::SelectFunctionDialog (QWidget * parent = nullptr)
Default constructor.
Constructor.
Parameters
parent :: A parent widget
Definition at line 37 of file SelectFunctionDialog.cpp.
SelectFunctionDialog() [2/2]
MantidQt::MantidWidgets::SelectFunctionDialog::SelectFunctionDialog (QWidget * parent, const std::vector< std::string > & restrictions)
Constructor overload with categories to restrict to.
Constructor with categories to restrict to.
Parameters
parent :: A parent widget
restrictions :: List of categories to restrict to
Definition at line 45 of file SelectFunctionDialog.cpp.
References acceptFunction(), addSearchBoxFunctionNames(), constructFunctionTree(), functionDoubleClicked(), helpClicked(), m_form, rejectFunction(), searchBoxChanged(), and setMinimumHeightOfFunctionTree().
~SelectFunctionDialog()
MantidQt::MantidWidgets::SelectFunctionDialog::~SelectFunctionDialog () override
Definition at line 182 of file SelectFunctionDialog.cpp.
References m_form.
Member Function Documentation
acceptFunction
void MantidQt::MantidWidgets::SelectFunctionDialog::acceptFunction () private slot
Definition at line 232 of file SelectFunctionDialog.cpp.
References getFunction(), and m_form.
Referenced by functionDoubleClicked(), and SelectFunctionDialog().
addSearchBoxFunctionNames()
void MantidQt::MantidWidgets::SelectFunctionDialog::addSearchBoxFunctionNames (const std::vector< std::string > & registeredFunctions) private
Complete QComboBox for searching functions with available functions.
Complete the QComboBox with the available functions for fitting.
Parameters
registeredFunctions :: [input] Vector of avaiblable functions
Definition at line 98 of file SelectFunctionDialog.cpp.
References m_form.
Referenced by SelectFunctionDialog().
clearSearchBoxText()
void MantidQt::MantidWidgets::SelectFunctionDialog::clearSearchBoxText () const
Clear the text in the search box.
Definition at line 211 of file SelectFunctionDialog.cpp.
References m_form.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addFunctionBegin().
constructFunctionTree()
void MantidQt::MantidWidgets::SelectFunctionDialog::constructFunctionTree (const std::map< std::string, std::vector< std::string > > & categoryFunctionsMap, const std::vector< std::string > & restrictions) private
Construct QTreeWidget with categories and functions.
Construct the QTreeWidget based on the map information of categories and their respective fit functions.
Parameters
categoryFunctionsMap :: [input] Map of categories to functions
restrictions :: [input] List of categories to restrict choice to. If empty, no restriction.
Definition at line 111 of file SelectFunctionDialog.cpp.
References m_form, and name.
Referenced by SelectFunctionDialog().
functionDoubleClicked
void MantidQt::MantidWidgets::SelectFunctionDialog::functionDoubleClicked (QTreeWidgetItem * item) private slot
Definition at line 227 of file SelectFunctionDialog.cpp.
References acceptFunction().
Referenced by SelectFunctionDialog().
getFunction()
QString MantidQt::MantidWidgets::SelectFunctionDialog::getFunction () const
Return selected function.
Definition at line 200 of file SelectFunctionDialog.cpp.
References m_form.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::acceptFit(), acceptFunction(), MantidQt::MantidWidgets::FunctionTreeView::addFunctionEnd(), and helpClicked().
helpClicked
void MantidQt::MantidWidgets::SelectFunctionDialog::helpClicked () const private slot
Definition at line 248 of file SelectFunctionDialog.cpp.
References getFunction(), and MantidQt::API::HelpWindow::showFitFunction().
Referenced by SelectFunctionDialog().
rejectFunction
void MantidQt::MantidWidgets::SelectFunctionDialog::rejectFunction () private slot
Definition at line 243 of file SelectFunctionDialog.cpp.
References m_form.
Referenced by SelectFunctionDialog().
searchBoxChanged
void MantidQt::MantidWidgets::SelectFunctionDialog::searchBoxChanged (const QString & text) private slot
Called when the text in the search box changes.
Definition at line 216 of file SelectFunctionDialog.cpp.
References index, and m_form.
Referenced by SelectFunctionDialog().
setMinimumHeightOfFunctionTree()
void MantidQt::MantidWidgets::SelectFunctionDialog::setMinimumHeightOfFunctionTree () private
Sets the minimum height of the function tree so that all catagories are visible.
Sets the minimum height of the function tree to ensure that all catagories are visible when the dialog is opened.
This method ensures the correct minimum size is used for any screen resolution.
Definition at line 188 of file SelectFunctionDialog.cpp.
References m_form.
Referenced by SelectFunctionDialog().
Member Data Documentation
m_form
Ui::SelectFunctionDialog* MantidQt::MantidWidgets::SelectFunctionDialog::m_form protected
Ui elements form.
Definition at line 45 of file SelectFunctionDialog.h.
Referenced by acceptFunction(), addSearchBoxFunctionNames(), clearSearchBoxText(), constructFunctionTree(), getFunction(), rejectFunction(), searchBoxChanged(), SelectFunctionDialog(), setMinimumHeightOfFunctionTree(), and ~SelectFunctionDialog().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/SelectFunctionDialog.h
qt/widgets/common/src/SelectFunctionDialog.cpp