Mantid: Mantid::CurveFitting::Functions::PseudoVoigt Class Reference
Mantid::CurveFitting::Functions::PseudoVoigt Class Reference
PseudoVoigt.
#include <PseudoVoigt.h>
Public Member Functions
const std::string category () const override
The categories the Fit function belong to.
double centre () const override
Returns the centre of the function, which may be something as simple as the centre of the fitting range in the case of a background function or peak shape function this return value reflects the centre of the peak.
double fwhm () const override
Returns the peak FWHM.
double height () const override
calculate effective parameter: height
double intensity () const override
Returns the integral intensity of the peak.
double intensityError () const override
Error in the integrated intensity of the peak due to uncertainties in the values of the fit parameters.
std::string name () const override
Returns the function's name.
void setCentre (const double c) override
Sets the parameters such that centre == c.
void setFwhm (const double w) override
set FWHM
void setHeight (const double h) override
set non-native parameter peak height
void setIntensity (const double newIntensity) override
Sets the integral intensity of the peak.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
set by name
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter.
Public Member Functions inherited from Mantid::API::IPeakFunction
virtual void fixIntensity (bool isDefault=false)
Fix a parameter or set up a tie such that value returned by intensity() is constant during fitting.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
void function1D (double *out, const double *xValues, const size_t nData) const override
General implementation of the method for all peaks.
void functionDeriv1D (Jacobian *out, const double *xValues, const size_t nData) override
General implementation of the method for all peaks.
std::string getCentreParameterName () const
Get name of parameter that is associated to centre.
virtual std::pair< double, double > getDomainInterval (double level=DEFAULT_SEARCH_LEVEL) const
Get the interval on which the peak has all its values above a certain level.
virtual std::string getWidthParameterName () const
Get the name of the parameter that is changed when the fwhm is changed.
IPeakFunction ()
Constructor.
virtual void unfixIntensity ()
Free the intensity parameter.
Public Member Functions inherited from Mantid::API::IFunctionWithLocation
virtual void fixCentre (bool isDefault=false)
Fix a parameter or set up a tie such that value returned by centre() is constant during fitting.
virtual void unfixCentre ()
Free the centre parameter.
~IFunctionWithLocation () override=default
Virtual destructor (avoids warnings about non-trivial move assignment in virtually inheriting classes)
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual void setAttribute (const std::string &name, const Attribute &)
Set a value to attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::IFunction1D
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
Protected Member Functions
void functionDerivLocal (API::Jacobian *out, const double *xValues, const size_t nData) override
calcualte derivative analytically
void functionLocal (double *out, const double *xValues, const size_t nData) const override
calculate pseudo voigt
void init () override
Declare peak parameters in this order: mixing (eta), intensity (I), peak center (x0) and FWHM (H or gamma)
Protected Member Functions inherited from Mantid::API::IPeakFunction
virtual IntegrationResultCache integrate () const
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::IFunction1D
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Private Member Functions
bool estimate_parameter_value ()
size_t get_parameter_to_calculate_from_set ()
get the parameter (by index) to calculate according to parameter set history
void update_set_history (size_t set_index)
The purpose of this is to track which user-specified parameter is outdated and to be calculated.
Private Attributes
double m_height
std::vector< size_t > m_set_history_distances
historty of the order to be set
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Types inherited from Mantid::API::IFunction1D
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Static Protected Attributes inherited from Mantid::API::IFunction1D
static Kernel::Logger g_log
Logger instance.
Detailed Description
PseudoVoigt.
This peak function provides an implementation of the pseudo-Voigt function, which is an approximation of the Voigt function (convolution of Gaussian and Lorentzian). The function has 4 parameters, height, FWHM, center and a mixing parameter a, which is limited to the interval [0,1].
The function is defined as:
f(x) = a * G(x) + (1.0 - a) * L(x)
with G(x) being the Gaussian and L(x) being the Lorentzian peak function.
This profile function is often used for peaks which are not strictly Gaussian or Lorentzian shaped.
Author
Michael Wedel, Paul Scherrer Institut - SINQ
Date
03/03/2015
Definition at line 35 of file PseudoVoigt.h.
Member Function Documentation
category()
const std::string Mantid::CurveFitting::Functions::PseudoVoigt::category () const inline override virtual
The categories the Fit function belong to.
Categories must be listed as a semi colon separated list. For example: "General, Muon\\Custom" which adds a function to the category "General" and the sub-category "Muon\\Custom"
Reimplemented from Mantid::API::IFunction.
Definition at line 49 of file PseudoVoigt.h.
centre()
double Mantid::CurveFitting::Functions::PseudoVoigt::centre () const inline override virtual
Returns the centre of the function, which may be something as simple as the centre of the fitting range in the case of a background function or peak shape function this return value reflects the centre of the peak.
Implements Mantid::API::IFunctionWithLocation.
Definition at line 37 of file PseudoVoigt.h.
estimate_parameter_value()
bool Mantid::CurveFitting::Functions::PseudoVoigt::estimate_parameter_value () private
Definition at line 218 of file PseudoVoigt.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, get_parameter_to_calculate_from_set(), Mantid::API::ParamFunction::getParameter(), m_height, and setParameter().
Referenced by setHeight(), and setParameter().
functionDerivLocal()
void Mantid::CurveFitting::Functions::PseudoVoigt::functionDerivLocal (API::Jacobian * out, const double * xValues, const size_t nData) override protected virtual
calcualte derivative analytically
Parameters
out :: array with calculated derivatives
xValues :: input X array
nData :: data size
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 131 of file PseudoVoigt.cpp.
References Mantid::API::ParamFunction::getParameter(), and Mantid::API::Jacobian::set().
functionLocal()
void Mantid::CurveFitting::Functions::PseudoVoigt::functionLocal (double * out, const double * xValues, const size_t nData) const override protected virtual
calculate pseudo voigt
Parameters
out :: array with calculated value
xValues :: array with input X values
nData :: size of data
Implements Mantid::API::IPeakFunction.
Definition at line 100 of file PseudoVoigt.cpp.
References fabs, and Mantid::API::ParamFunction::getParameter().
fwhm()
double Mantid::CurveFitting::Functions::PseudoVoigt::fwhm () const inline override virtual
Returns the peak FWHM.
Implements Mantid::API::IPeakFunction.
Definition at line 41 of file PseudoVoigt.h.
get_parameter_to_calculate_from_set()
size_t Mantid::CurveFitting::Functions::PseudoVoigt::get_parameter_to_calculate_from_set () private
get the parameter (by index) to calculate according to parameter set history
As a parameter (height, width, intensity and mixing) being set (via setParameter) find out whethere are are enough parameters that have been specified.
PseudoVoigt::get_parameter_to_calculate_from_set
Returns
:: index of the parameter to calculate if there is
Definition at line 303 of file PseudoVoigt.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, and m_set_history_distances.
Referenced by estimate_parameter_value().
height()
double Mantid::CurveFitting::Functions::PseudoVoigt::height () const override virtual
calculate effective parameter: height
Returns
Implements Mantid::API::IFunctionWithLocation.
Definition at line 332 of file PseudoVoigt.cpp.
References Mantid::API::ParamFunction::getParameter(), and height().
Referenced by height().
init()
void Mantid::CurveFitting::Functions::PseudoVoigt::init () override protected virtual
Declare peak parameters in this order: mixing (eta), intensity (I), peak center (x0) and FWHM (H or gamma)
PseudoVoigt::init declare peak parameters
Reimplemented from Mantid::API::IFunction.
Definition at line 72 of file PseudoVoigt.cpp.
intensity()
double Mantid::CurveFitting::Functions::PseudoVoigt::intensity () const inline override virtual
Returns the integral intensity of the peak.
Returns the integrated intensity of the peak function, using the peak radius to determine integration borders.
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 38 of file PseudoVoigt.h.
intensityError()
double Mantid::CurveFitting::Functions::PseudoVoigt::intensityError () const inline override virtual
Error in the integrated intensity of the peak due to uncertainties in the values of the fit parameters.
if the peak function contains no fit-parameter uncertainties, then the integration error is set to NaN. Also, this function assumes no correlation between the fit parameters, so that their corresponding errors are summed up in quadrature.
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 39 of file PseudoVoigt.h.
name()
std::string Mantid::CurveFitting::Functions::PseudoVoigt::name () const inline override virtual
Returns the function's name.
Implements Mantid::API::IFunction.
Definition at line 48 of file PseudoVoigt.h.
Referenced by setParameter().
setCentre()
void Mantid::CurveFitting::Functions::PseudoVoigt::setCentre (const double c) inline override virtual
Sets the parameters such that centre == c.
Implements Mantid::API::IFunctionWithLocation.
Definition at line 43 of file PseudoVoigt.h.
setFwhm()
void Mantid::CurveFitting::Functions::PseudoVoigt::setFwhm (const double w) override virtual
set FWHM
Parameters
w
Implements Mantid::API::IPeakFunction.
Definition at line 373 of file PseudoVoigt.cpp.
References setParameter().
setHeight()
void Mantid::CurveFitting::Functions::PseudoVoigt::setHeight (const double h) override virtual
set non-native parameter peak height
PseudoVoigt::setHeight
Parameters
h
Implements Mantid::API::IFunctionWithLocation.
Definition at line 345 of file PseudoVoigt.cpp.
References Mantid::Kernel::Logger::debug(), estimate_parameter_value(), Mantid::API::g_log, Mantid::API::ParamFunction::getParameter(), m_height, setParameter(), and update_set_history().
setIntensity()
void Mantid::CurveFitting::Functions::PseudoVoigt::setIntensity (const double newIntensity) inline override virtual
Sets the integral intensity of the peak.
Sets the integral intensity of the peak by adjusting the height.
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 46 of file PseudoVoigt.h.
setParameter() [1/2]
void Mantid::CurveFitting::Functions::PseudoVoigt::setParameter (const std::string & name, const double & value, bool explicitlySet = true) override virtual
set by name
override because setParameter(size_t i ...) is overriden
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 177 of file PseudoVoigt.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, name(), Mantid::API::IPeakFunction::setParameter(), and value.
setParameter() [2/2]
void Mantid::CurveFitting::Functions::PseudoVoigt::setParameter (size_t i, const double & value, bool explicitlySet = true) override virtual
Set i-th parameter.
set parameter by parameter index Parameter set up scenaio:
as both intensity and height are set explicity: calculate mixing and set non-explicitly
as both intensity and height are set but intensity is not set explicitly: do nothing else
if both height and mixing are specified explicitly, then calculate peak intensity Note: both intensity and height Equation among eta, I, H and height: peak_intensity = m_height / 2. / (1 + (sqrt(M_PI * M_LN2) - 1) * eta) * (M_PI * gamma);
Parameters
i :: index (mixing (0), intensity (1), centre (2), fwhm (3)
value :: value
explicitlySet :: whether it is an explicit set. if true, then consider to calculate other parameters
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 199 of file PseudoVoigt.cpp.
References Mantid::Kernel::Logger::debug(), estimate_parameter_value(), Mantid::API::g_log, Mantid::API::IPeakFunction::setParameter(), update_set_history(), and value.
Referenced by estimate_parameter_value(), setFwhm(), and setHeight().
update_set_history()
void Mantid::CurveFitting::Functions::PseudoVoigt::update_set_history (size_t set_index) private
The purpose of this is to track which user-specified parameter is outdated and to be calculated.
PseudoVoigt::update_set_history
Parameters
set_index,: 0 mixing, 1 intensity, 2 height, 3 fwhm
Definition at line 274 of file PseudoVoigt.cpp.
References m_set_history_distances.
Referenced by setHeight(), and setParameter().
Member Data Documentation
m_height
double Mantid::CurveFitting::Functions::PseudoVoigt::m_height private
Definition at line 72 of file PseudoVoigt.h.
Referenced by estimate_parameter_value(), and setHeight().
m_set_history_distances
std::vector<size_t> Mantid::CurveFitting::Functions::PseudoVoigt::m_set_history_distances private
historty of the order to be set
Definition at line 65 of file PseudoVoigt.h.
Referenced by get_parameter_to_calculate_from_set(), and update_set_history().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/PseudoVoigt.h
Framework/CurveFitting/src/Functions/PseudoVoigt.cpp