Mantid: Mantid::API::IndexTypeProperty Class Reference
Mantid::API::IndexTypeProperty Class Reference
IndexTypeProperty : Implementation of a property which stores the type of input indices users require for accessing workspace data.
#include <IndexTypeProperty.h>
Public Member Functions
int allowedTypes () const
std::vector< std::string > allowedValues () const override
Returns the set of valid values for this property, if such a set exists.
IndexTypeProperty (const std::string &name="IndexType", int indexType=static_cast< int >(IndexType::WorkspaceIndex))
bool isMultipleSelectionAllowed () override
Is Multiple Selection Allowed.
IndexTypeProperty & operator= (API::IndexType type)
IndexType selectedType () const
Public Member Functions inherited from Mantid::Kernel::PropertyWithValue< std::string >
std::vector< std::string > allowedValues () const override
Returns the set of valid values for this property, if such a set exists.
PropertyWithValue< std::string > * clone () const override
'Virtual copy constructor'
std::string getDefault () const override
Get the default value for the property which is the value the property was initialised with.
IValidator_sptr getValidator () const
bool isDefault () const override
Overriden function that returns if property has the same value that it was initialised with, if applicable.
bool isMultipleSelectionAllowed () override
Is Multiple Selection Allowed.
std::string isValid () const override
Overridden function that checks whether the property, if not overriden returns "".
virtual operator const std::string & () const
bool operator!= (const PropertyWithValue< std::string > &rhs) const
virtual const std::string & operator() () const
PropertyWithValue & operator+= (Property const *right) override
Add to this.
PropertyWithValue & operator= (const PropertyWithValue &right)
virtual PropertyWithValue & operator= (const std::string &value)
bool operator== (const PropertyWithValue< std::string > &rhs) const
PropertyWithValue (const PropertyWithValue< std::string > &right)
PropertyWithValue (const std::string &name, std::string defaultValue, const std::string &defaultValueStr, IValidator_sptr validator, const unsigned int direction)
PropertyWithValue (std::string name, std::string defaultValue, const unsigned int direction)
PropertyWithValue (std::string name, std::string defaultValue, IValidator_sptr validator=IValidator_sptr(new NullValidator), const unsigned int direction=Direction::Input)
virtual void replaceValidator (IValidator_sptr newValidator)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
void saveProperty (::NeXus::File *file) override
std::string setDataItem (const std::shared_ptr< DataItem > &data) override
Set the value of the property via a DataItem pointer.
std::string setValue (const std::string &value) override
Set the value of the property via a string.
std::string setValueFromJson (const Json::Value &value) override
Set the value of the property via a Json object.
int size () const override
Return the size of this property.
std::string value () const override
Returns the value of the property as a string.
Json::Value valueAsJson () const override
Returns the value of the property as a Json::Value.
std::string valueAsPrettyStr (const size_t maxLength=0, const bool collapseLists=true) const override
Returns the value of the property as a pretty printed string.
Public Member Functions inherited from Mantid::Kernel::Property
virtual std::vector< std::string > allowedValues () const
Returns the set of valid values for this property, if such a set exists.
bool autoTrim () const
Returns if the property is set to automatically trim string unput values of whitespace.
void clearSettings ()
Deletes the PropertySettings object contained.
virtual Property * clone () const =0
'Virtual copy constructor'
virtual const PropertyHistory createHistory () const
Create a PropertyHistory object representing the current state of the Property.
void createTemporaryValue ()
Create a temporary value for this property.
unsigned int direction () const
returns the direction of the property
const std::string & documentation () const
Get the property's documentation string.
virtual void filterByTime (const Types::Core::DateAndTime &start, const Types::Core::DateAndTime &stop)
Filter out a property by time.
virtual std::string getDefault () const =0
Get the default value for the property which is the value the property was initialised with.
const std::string & getGroup ()
virtual size_t getMemorySize () const
IPropertySettings * getSettings ()
bool hasTemporaryValue () const
Property is using a temporary value for this property.
virtual bool isDefault () const =0
Overriden function that returns if property has the same value that it was initialised with, if applicable.
virtual bool isMultipleSelectionAllowed ()
Is Multiple Selection Allowed.
virtual std::string isValid () const
Overridden function that checks whether the property, if not overriden returns "".
virtual bool isValueSerializable () const
Whether the string returned by value() can be used for serialization.
virtual Property & merge (Property *)
Just returns the property (*this) unless overridden.
const std::string & name () const
Get the property's name.
virtual Property & operator+= (Property const *rhs)=0
Add to this.
bool remember () const
Whether to save input values.
virtual void saveProperty (::NeXus::File *)
void setAutoTrim (const bool &setting)
Sets if the property is set to automatically trim string unput values of whitespace.
virtual std::string setDataItem (const std::shared_ptr< DataItem > &)=0
Set the value of the property via a DataItem pointer.
void setDocumentation (const std::string &documentation)
Sets the user level description of the property.
void setGroup (const std::string &group)
Set the group this property belongs to.
void setRemember (bool)
Set wheter to remeber this property input.
void setSettings (std::unique_ptr< IPropertySettings > settings)
Set the PropertySettings object.
virtual void setUnits (const std::string &unit)
Sets the units of the property, as a string.
virtual std::string setValue (const std::string &)=0
Set the value of the property via a string.
virtual std::string setValueFromJson (const Json::Value &)=0
Set the value of the property via a Json object.
virtual std::string setValueFromProperty (const Property &right)=0
Set the value of the property via a reference to another property.
virtual int size () const
Return the size of this property.
virtual void splitByTime (std::vector< SplittingInterval > &splitter, std::vector< Property * > outputs, bool isProtonCharge=true) const
Split a property by time.
const std::string type () const
Returns the type of the property as a string.
const std::type_info * type_info () const
Get the property type_info.
virtual const std::string & units () const
Returns the units of the property, if any, as a string.
virtual std::string value () const =0
Returns the value of the property as a string.
virtual Json::Value valueAsJson () const =0
Returns the value of the property as a Json::Value.
virtual std::string valueAsPrettyStr (const size_t maxLength=0, const bool collapseLists=true) const
Returns the value of the property as a pretty printed string.
virtual ~Property ()
Virtual destructor.
Static Public Member Functions
static std::string generatePropertyName (const std::string &name="")
Private Attributes
std::vector< std::string > m_allowedValues
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Property
Property (const Property &right)
Copy constructor.
Property (std::string name, const std::type_info &type, const unsigned int &direction=Direction::Input)
Constructor.
Protected Attributes inherited from Mantid::Kernel::PropertyWithValue< std::string >
std::string m_initialValue
the property's default value which is also its initial value
std::string m_value
The value of the property.
Protected Attributes inherited from Mantid::Kernel::Property
std::string m_name
The name of the property.
Detailed Description
IndexTypeProperty : Implementation of a property which stores the type of input indices users require for accessing workspace data.
This works in harmony with IndexProperty and is not intended for isolated use.
Author
Lamar Moore
Date
05-05-2017
Definition at line 24 of file IndexTypeProperty.h.
Constructor & Destructor Documentation
IndexTypeProperty()
Mantid::API::IndexTypeProperty::IndexTypeProperty (const std::string & name = "IndexType", int indexType = static_cast<int>(IndexType::WorkspaceIndex))
Definition at line 10 of file IndexTypeProperty.cpp.
References m_allowedValues, Mantid::Kernel::PropertyWithValue< std::string >::m_value, Mantid::API::SpectrumNum, and Mantid::API::WorkspaceIndex.
Member Function Documentation
allowedTypes()
int Mantid::API::IndexTypeProperty::allowedTypes () const
Definition at line 35 of file IndexTypeProperty.cpp.
References m_allowedValues, Mantid::API::SpectrumNum, and Mantid::API::WorkspaceIndex.
allowedValues()
std::vector< std::string > Mantid::API::IndexTypeProperty::allowedValues () const override virtual
Returns the set of valid values for this property, if such a set exists.
If not, it returns an empty set.
Returns
the set of valid values for this property or an empty set
Reimplemented from Mantid::Kernel::Property.
Definition at line 51 of file IndexTypeProperty.cpp.
References m_allowedValues.
generatePropertyName()
std::string Mantid::API::IndexTypeProperty::generatePropertyName (const std::string & name = "") static
Definition at line 71 of file IndexTypeProperty.cpp.
References Mantid::Kernel::Property::name().
isMultipleSelectionAllowed()
bool Mantid::API::IndexTypeProperty::isMultipleSelectionAllowed () override virtual
Is Multiple Selection Allowed.
Returns
true if multiple selection is allowed
Reimplemented from Mantid::Kernel::Property.
Definition at line 53 of file IndexTypeProperty.cpp.
operator=()
IndexTypeProperty & Mantid::API::IndexTypeProperty::operator= (API::IndexType type)
Definition at line 55 of file IndexTypeProperty.cpp.
References Mantid::API::SpectrumNum, Mantid::Kernel::Property::type(), and Mantid::API::WorkspaceIndex.
selectedType()
IndexType Mantid::API::IndexTypeProperty::selectedType () const
Definition at line 23 of file IndexTypeProperty.cpp.
References Mantid::API::SpectrumNum, Mantid::Kernel::PropertyWithValue< std::string >::value(), and Mantid::API::WorkspaceIndex.
Referenced by Mantid::API::IndexProperty::getFilteredIndexInfo(), and Mantid::API::IndexProperty::getIndices().
Member Data Documentation
m_allowedValues
std::vector<std::string> Mantid::API::IndexTypeProperty::m_allowedValues private
Definition at line 43 of file IndexTypeProperty.h.
Referenced by allowedTypes(), allowedValues(), and IndexTypeProperty().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IndexTypeProperty.h
Framework/API/src/IndexTypeProperty.cpp