Mantid: Mantid::API::MDGeometryNotificationHelper Class Reference
Mantid::API::MDGeometryNotificationHelper Class Reference
Public Member Functions
void deleteNotificationReceived (Mantid::API::WorkspacePreDeleteNotification_ptr notice)
MDGeometryNotificationHelper (MDGeometry &parent)
void watchForWorkspaceDeletions ()
~MDGeometryNotificationHelper ()
Private Attributes
Poco::NObserver< MDGeometryNotificationHelper, WorkspacePreDeleteNotification > m_delete_observer
Poco delete notification observer object.
bool m_observingDelete {false}
Set to True when the m_delete_observer is observing workspace deletions.
MDGeometry & m_parent
Detailed Description
Definition at line 25 of file MDGeometry.cpp.
Constructor & Destructor Documentation
MDGeometryNotificationHelper()
Mantid::API::MDGeometryNotificationHelper::MDGeometryNotificationHelper (MDGeometry & parent) inline explicit
Definition at line 27 of file MDGeometry.cpp.
~MDGeometryNotificationHelper()
Mantid::API::MDGeometryNotificationHelper::~MDGeometryNotificationHelper () inline
Definition at line 30 of file MDGeometry.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_delete_observer, and m_observingDelete.
Member Function Documentation
deleteNotificationReceived()
void Mantid::API::MDGeometryNotificationHelper::deleteNotificationReceived (Mantid::API::WorkspacePreDeleteNotification_ptr notice) inline
Definition at line 44 of file MDGeometry.cpp.
References Mantid::API::MDGeometry::deleteNotificationReceived(), and m_parent.
watchForWorkspaceDeletions()
void Mantid::API::MDGeometryNotificationHelper::watchForWorkspaceDeletions () inline
Definition at line 37 of file MDGeometry.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_delete_observer, and m_observingDelete.
Member Data Documentation
m_delete_observer
Poco::NObserver<MDGeometryNotificationHelper, WorkspacePreDeleteNotification> Mantid::API::MDGeometryNotificationHelper::m_delete_observer private
Poco delete notification observer object.
Definition at line 52 of file MDGeometry.cpp.
Referenced by watchForWorkspaceDeletions(), and ~MDGeometryNotificationHelper().
m_observingDelete
bool Mantid::API::MDGeometryNotificationHelper::m_observingDelete {false} private
Set to True when the m_delete_observer is observing workspace deletions.
Definition at line 55 of file MDGeometry.cpp.
Referenced by watchForWorkspaceDeletions(), and ~MDGeometryNotificationHelper().
m_parent
MDGeometry& Mantid::API::MDGeometryNotificationHelper::m_parent private
Definition at line 49 of file MDGeometry.cpp.
Referenced by deleteNotificationReceived().
The documentation for this class was generated from the following file:
Framework/API/src/MDGeometry.cpp