Mantid: ICat4::ICATPortBindingProxy Class Reference
ICat4::ICATPortBindingProxy Class Reference
#include <ICat4ICATPortBindingProxy.h>
Public Member Functions
virtual int create (const char *endpoint, const char *soap_action, ns1__create *ns1__create_, ns1__createResponse *ns1__createResponse_)
virtual int create (ns1__create *ns1__create_, ns1__createResponse *ns1__createResponse_)
Web service operation 'create' (returns error code or SOAP_OK)
virtual int createMany (const char *endpoint, const char *soap_action, ns1__createMany *ns1__createMany_, ns1__createManyResponse *ns1__createManyResponse_)
virtual int createMany (ns1__createMany *ns1__createMany_, ns1__createManyResponse *ns1__createManyResponse_)
Web service operation 'createMany' (returns error code or SOAP_OK)
virtual int delete_ (const char *endpoint, const char *soap_action, ns1__delete *ns1__delete_, ns1__deleteResponse *ns1__deleteResponse_)
virtual int delete_ (ns1__delete *ns1__delete_, ns1__deleteResponse *ns1__deleteResponse_)
Web service operation 'delete' (returns error code or SOAP_OK)
virtual int deleteMany (const char *endpoint, const char *soap_action, ns1__deleteMany *ns1__deleteMany_, ns1__deleteManyResponse *ns1__deleteManyResponse_)
virtual int deleteMany (ns1__deleteMany *ns1__deleteMany_, ns1__deleteManyResponse *ns1__deleteManyResponse_)
Web service operation 'deleteMany' (returns error code or SOAP_OK)
virtual void destroy ()
Delete all deserialized data (with soap_destroy and soap_end)
virtual int dummy (const char *endpoint, const char *soap_action, ns1__dummy *ns1__dummy_, ns1__dummyResponse *ns1__dummyResponse_)
virtual int dummy (ns1__dummy *ns1__dummy_, ns1__dummyResponse *ns1__dummyResponse_)
Web service operation 'dummy' (returns error code or SOAP_OK)
virtual int get (const char *endpoint, const char *soap_action, ns1__get *ns1__get_, ns1__getResponse *ns1__getResponse_)
virtual int get (ns1__get *ns1__get_, ns1__getResponse *ns1__getResponse_)
Web service operation 'get' (returns error code or SOAP_OK)
virtual int getApiVersion (const char *endpoint, const char *soap_action, ns1__getApiVersion *ns1__getApiVersion_, ns1__getApiVersionResponse *ns1__getApiVersionResponse_)
virtual int getApiVersion (ns1__getApiVersion *ns1__getApiVersion_, ns1__getApiVersionResponse *ns1__getApiVersionResponse_)
Web service operation 'getApiVersion' (returns error code or SOAP_OK)
virtual int getEntityInfo (const char *endpoint, const char *soap_action, ns1__getEntityInfo *ns1__getEntityInfo_, ns1__getEntityInfoResponse *ns1__getEntityInfoResponse_)
virtual int getEntityInfo (ns1__getEntityInfo *ns1__getEntityInfo_, ns1__getEntityInfoResponse *ns1__getEntityInfoResponse_)
Web service operation 'getEntityInfo' (returns error code or SOAP_OK)
virtual int getEntityNames (const char *endpoint, const char *soap_action, ns1__getEntityNames *ns1__getEntityNames_, ns1__getEntityNamesResponse *ns1__getEntityNamesResponse_)
virtual int getEntityNames (ns1__getEntityNames *ns1__getEntityNames_, ns1__getEntityNamesResponse *ns1__getEntityNamesResponse_)
Web service operation 'getEntityNames' (returns error code or SOAP_OK)
virtual int getProperties (const char *endpoint, const char *soap_action, ns1__getProperties *ns1__getProperties_, ns1__getPropertiesResponse *ns1__getPropertiesResponse_)
virtual int getProperties (ns1__getProperties *ns1__getProperties_, ns1__getPropertiesResponse *ns1__getPropertiesResponse_)
Web service operation 'getProperties' (returns error code or SOAP_OK)
virtual int getRemainingMinutes (const char *endpoint, const char *soap_action, ns1__getRemainingMinutes *ns1__getRemainingMinutes_, ns1__getRemainingMinutesResponse *ns1__getRemainingMinutesResponse_)
virtual int getRemainingMinutes (ns1__getRemainingMinutes *ns1__getRemainingMinutes_, ns1__getRemainingMinutesResponse *ns1__getRemainingMinutesResponse_)
Web service operation 'getRemainingMinutes' (returns error code or SOAP_OK)
virtual int getUserName (const char *endpoint, const char *soap_action, ns1__getUserName *ns1__getUserName_, ns1__getUserNameResponse *ns1__getUserNameResponse_)
virtual int getUserName (ns1__getUserName *ns1__getUserName_, ns1__getUserNameResponse *ns1__getUserNameResponse_)
Web service operation 'getUserName' (returns error code or SOAP_OK)
ICATPortBindingProxy ()
Constructor.
ICATPortBindingProxy (const char *url)
Constructor with endpoint URL.
ICATPortBindingProxy (const char *url, soap_mode iomode)
Constructor with URL and input+output mode control.
ICATPortBindingProxy (const struct soap &)
Construct from another engine state.
ICATPortBindingProxy (soap_mode imode, soap_mode omode)
Constructor with engine input and output mode control.
ICATPortBindingProxy (soap_mode iomode)
Constructor with engine input+output mode control.
virtual void ICATPortBindingProxy_init (soap_mode imode, soap_mode omode)
Initializer used by constructors.
virtual int isAccessAllowed (const char *endpoint, const char *soap_action, ns1__isAccessAllowed *ns1__isAccessAllowed_, ns1__isAccessAllowedResponse *ns1__isAccessAllowedResponse_)
virtual int isAccessAllowed (ns1__isAccessAllowed *ns1__isAccessAllowed_, ns1__isAccessAllowedResponse *ns1__isAccessAllowedResponse_)
Web service operation 'isAccessAllowed' (returns error code or SOAP_OK)
virtual int login (const char *endpoint, const char *soap_action, ns1__login *ns1__login_, ns1__loginResponse *ns1__loginResponse_)
virtual int login (ns1__login *ns1__login_, ns1__loginResponse *ns1__loginResponse_)
Web service operation 'login' (returns error code or SOAP_OK)
virtual int logout (const char *endpoint, const char *soap_action, ns1__logout *ns1__logout_, ns1__logoutResponse *ns1__logoutResponse_)
virtual int logout (ns1__logout *ns1__logout_, ns1__logoutResponse *ns1__logoutResponse_)
Web service operation 'logout' (returns error code or SOAP_OK)
virtual int luceneClear (const char *endpoint, const char *soap_action, ns1__luceneClear *ns1__luceneClear_, ns1__luceneClearResponse *ns1__luceneClearResponse_)
virtual int luceneClear (ns1__luceneClear *ns1__luceneClear_, ns1__luceneClearResponse *ns1__luceneClearResponse_)
Web service operation 'luceneClear' (returns error code or SOAP_OK)
virtual int luceneCommit (const char *endpoint, const char *soap_action, ns1__luceneCommit *ns1__luceneCommit_, ns1__luceneCommitResponse *ns1__luceneCommitResponse_)
virtual int luceneCommit (ns1__luceneCommit *ns1__luceneCommit_, ns1__luceneCommitResponse *ns1__luceneCommitResponse_)
Web service operation 'luceneCommit' (returns error code or SOAP_OK)
virtual int luceneGetPopulating (const char *endpoint, const char *soap_action, ns1__luceneGetPopulating *ns1__luceneGetPopulating_, ns1__luceneGetPopulatingResponse *ns1__luceneGetPopulatingResponse_)
virtual int luceneGetPopulating (ns1__luceneGetPopulating *ns1__luceneGetPopulating_, ns1__luceneGetPopulatingResponse *ns1__luceneGetPopulatingResponse_)
Web service operation 'luceneGetPopulating' (returns error code or SOAP_OK)
virtual int lucenePopulate (const char *endpoint, const char *soap_action, ns1__lucenePopulate *ns1__lucenePopulate_, ns1__lucenePopulateResponse *ns1__lucenePopulateResponse_)
virtual int lucenePopulate (ns1__lucenePopulate *ns1__lucenePopulate_, ns1__lucenePopulateResponse *ns1__lucenePopulateResponse_)
Web service operation 'lucenePopulate' (returns error code or SOAP_OK)
virtual int luceneSearch (const char *endpoint, const char *soap_action, ns1__luceneSearch *ns1__luceneSearch_, ns1__luceneSearchResponse *ns1__luceneSearchResponse_)
virtual int luceneSearch (ns1__luceneSearch *ns1__luceneSearch_, ns1__luceneSearchResponse *ns1__luceneSearchResponse_)
Web service operation 'luceneSearch' (returns error code or SOAP_OK)
virtual int refresh (const char *endpoint, const char *soap_action, ns1__refresh *ns1__refresh_, ns1__refreshResponse *ns1__refreshResponse_)
virtual int refresh (ns1__refresh *ns1__refresh_, ns1__refreshResponse *ns1__refreshResponse_)
Web service operation 'refresh' (returns error code or SOAP_OK)
virtual void reset ()
Delete all deserialized data and reset to default.
virtual int search (const char *endpoint, const char *soap_action, ns1__search *ns1__search_, ns1__searchResponse *ns1__searchResponse_)
virtual int search (ns1__search *ns1__search_, ns1__searchResponse *ns1__searchResponse_)
Web service operation 'search' (returns error code or SOAP_OK)
virtual int searchText (const char *endpoint, const char *soap_action, ns1__searchText *ns1__searchText_, ns1__searchTextResponse *ns1__searchTextResponse_)
virtual int searchText (ns1__searchText *ns1__searchText_, ns1__searchTextResponse *ns1__searchTextResponse_)
Web service operation 'searchText' (returns error code or SOAP_OK)
virtual int soap_close_socket ()
Close connection (normally automatic, except for send_X ops)
virtual const SOAP_ENV__Fault * soap_fault ()
Get SOAP Fault structure (NULL when absent)
virtual const char * soap_fault_detail ()
Get SOAP Fault detail as string (NULL when absent)
virtual const char * soap_fault_string ()
Get SOAP Fault string (NULL when absent)
virtual int soap_force_close_socket ()
Force close connection (can kill a thread blocked on IO)
virtual const SOAP_ENV__Header * soap_header ()
Get SOAP Header structure (NULL when absent)
virtual void soap_noheader ()
Disables and removes SOAP Header from message.
virtual void soap_print_fault (FILE *)
Print fault.
virtual char * soap_sprint_fault (char *buf, size_t len)
Put fault into buffer.
virtual void soap_stream_fault (std::ostream &)
Print fault to stream.
virtual int update (const char *endpoint, const char *soap_action, ns1__update *ns1__update_, ns1__updateResponse *ns1__updateResponse_)
virtual int update (ns1__update *ns1__update_, ns1__updateResponse *ns1__updateResponse_)
Web service operation 'update' (returns error code or SOAP_OK)
Public Attributes
const char * soap_endpoint
Endpoint URL of service 'ICATPortBindingProxy' (change as needed)
Detailed Description
Definition at line 16 of file ICat4ICATPortBindingProxy.h.
Constructor & Destructor Documentation
ICATPortBindingProxy() [1/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy ()
Constructor.
Definition at line 15 of file ICat4ICATPortBindingProxy.cpp.
References ICATPortBindingProxy_init().
ICATPortBindingProxy() [2/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy (const struct soap & _soap)
Construct from another engine state.
Definition at line 17 of file ICat4ICATPortBindingProxy.cpp.
ICATPortBindingProxy() [3/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy (const char * url)
Constructor with endpoint URL.
Definition at line 19 of file ICat4ICATPortBindingProxy.cpp.
References ICATPortBindingProxy_init(), and soap_endpoint.
ICATPortBindingProxy() [4/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy (soap_mode iomode)
Constructor with engine input+output mode control.
Definition at line 24 of file ICat4ICATPortBindingProxy.cpp.
References ICATPortBindingProxy_init().
ICATPortBindingProxy() [5/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy (const char * url, soap_mode iomode)
Constructor with URL and input+output mode control.
Definition at line 26 of file ICat4ICATPortBindingProxy.cpp.
References ICATPortBindingProxy_init(), and soap_endpoint.
ICATPortBindingProxy() [6/6]
ICat4::ICATPortBindingProxy::ICATPortBindingProxy (soap_mode imode, soap_mode omode)
Constructor with engine input and output mode control.
Definition at line 31 of file ICat4ICATPortBindingProxy.cpp.
References ICATPortBindingProxy_init().
Member Function Documentation
create() [1/2]
int ICat4::ICATPortBindingProxy::create (const char * endpoint, const char * soap_action, ns1__create * ns1__create_, ns1__createResponse * ns1__createResponse_) virtual
Definition at line 349 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__create::ns1__create_, ICat4::ns1__createResponse::soap_default(), soap_endpoint, ICat4::ns1__createResponse::soap_get(), ICat4::soap_put___ns1__create(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__create(), and ICat4::soap_serializeheader().
create() [2/2]
virtual int ICat4::ICATPortBindingProxy::create (ns1__create * ns1__create_, ns1__createResponse * ns1__createResponse_) inline virtual
Web service operation 'create' (returns error code or SOAP_OK)
Definition at line 108 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset().
createMany() [1/2]
int ICat4::ICATPortBindingProxy::createMany (const char * endpoint, const char * soap_action, ns1__createMany * ns1__createMany_, ns1__createManyResponse * ns1__createManyResponse_) virtual
Definition at line 1037 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__createMany::ns1__createMany_, ICat4::ns1__createManyResponse::soap_default(), soap_endpoint, ICat4::ns1__createManyResponse::soap_get(), ICat4::soap_put___ns1__createMany(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__createMany(), and ICat4::soap_serializeheader().
createMany() [2/2]
virtual int ICat4::ICATPortBindingProxy::createMany (ns1__createMany * ns1__createMany_, ns1__createManyResponse * ns1__createManyResponse_) inline virtual
Web service operation 'createMany' (returns error code or SOAP_OK)
Definition at line 226 of file ICat4ICATPortBindingProxy.h.
delete_() [1/2]
int ICat4::ICATPortBindingProxy::delete_ (const char * endpoint, const char * soap_action, ns1__delete * ns1__delete_, ns1__deleteResponse * ns1__deleteResponse_) virtual
Definition at line 259 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__delete::ns1__delete_, ICat4::__ns1__deleteResponse::ns1__deleteResponse_, ICat4::ns1__deleteResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__deleteResponse(), ICat4::soap_put___ns1__delete(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__delete(), and ICat4::soap_serializeheader().
delete_() [2/2]
virtual int ICat4::ICATPortBindingProxy::delete_ (ns1__delete * ns1__delete_, ns1__deleteResponse * ns1__deleteResponse_) inline virtual
Web service operation 'delete' (returns error code or SOAP_OK)
Definition at line 94 of file ICat4ICATPortBindingProxy.h.
deleteMany() [1/2]
int ICat4::ICATPortBindingProxy::deleteMany (const char * endpoint, const char * soap_action, ns1__deleteMany * ns1__deleteMany_, ns1__deleteManyResponse * ns1__deleteManyResponse_) virtual
Definition at line 1080 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__deleteMany::ns1__deleteMany_, ICat4::__ns1__deleteManyResponse::ns1__deleteManyResponse_, ICat4::ns1__deleteManyResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__deleteManyResponse(), ICat4::soap_put___ns1__deleteMany(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__deleteMany(), and ICat4::soap_serializeheader().
deleteMany() [2/2]
virtual int ICat4::ICATPortBindingProxy::deleteMany (ns1__deleteMany * ns1__deleteMany_, ns1__deleteManyResponse * ns1__deleteManyResponse_) inline virtual
Web service operation 'deleteMany' (returns error code or SOAP_OK)
Definition at line 233 of file ICat4ICATPortBindingProxy.h.
destroy()
void ICat4::ICATPortBindingProxy::destroy () virtual
Delete all deserialized data (with soap_destroy and soap_end)
Definition at line 49 of file ICat4ICATPortBindingProxy.cpp.
Referenced by reset().
dummy() [1/2]
int ICat4::ICATPortBindingProxy::dummy (const char * endpoint, const char * soap_action, ns1__dummy * ns1__dummy_, ns1__dummyResponse * ns1__dummyResponse_) virtual
Definition at line 574 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__dummy::ns1__dummy_, ICat4::__ns1__dummyResponse::ns1__dummyResponse_, ICat4::ns1__dummyResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__dummyResponse(), ICat4::soap_put___ns1__dummy(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__dummy(), and ICat4::soap_serializeheader().
dummy() [2/2]
virtual int ICat4::ICATPortBindingProxy::dummy (ns1__dummy * ns1__dummy_, ns1__dummyResponse * ns1__dummyResponse_) inline virtual
Web service operation 'dummy' (returns error code or SOAP_OK)
Definition at line 145 of file ICat4ICATPortBindingProxy.h.
get() [1/2]
int ICat4::ICATPortBindingProxy::get (const char * endpoint, const char * soap_action, ns1__get * ns1__get_, ns1__getResponse * ns1__getResponse_) virtual
Definition at line 172 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__get::ns1__get_, ICat4::ns1__getResponse::soap_default(), soap_endpoint, ICat4::ns1__getResponse::soap_get(), ICat4::soap_put___ns1__get(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__get(), and ICat4::soap_serializeheader().
get() [2/2]
virtual int ICat4::ICATPortBindingProxy::get (ns1__get * ns1__get_, ns1__getResponse * ns1__getResponse_) inline virtual
Web service operation 'get' (returns error code or SOAP_OK)
Definition at line 79 of file ICat4ICATPortBindingProxy.h.
getApiVersion() [1/2]
int ICat4::ICATPortBindingProxy::getApiVersion (const char * endpoint, const char * soap_action, ns1__getApiVersion * ns1__getApiVersion_, ns1__getApiVersionResponse * ns1__getApiVersionResponse_) virtual
Definition at line 439 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getApiVersion::ns1__getApiVersion_, ICat4::ns1__getApiVersionResponse::soap_default(), soap_endpoint, ICat4::ns1__getApiVersionResponse::soap_get(), ICat4::soap_put___ns1__getApiVersion(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getApiVersion(), and ICat4::soap_serializeheader().
getApiVersion() [2/2]
virtual int ICat4::ICATPortBindingProxy::getApiVersion (ns1__getApiVersion * ns1__getApiVersion_, ns1__getApiVersionResponse * ns1__getApiVersionResponse_) inline virtual
Web service operation 'getApiVersion' (returns error code or SOAP_OK)
Definition at line 122 of file ICat4ICATPortBindingProxy.h.
getEntityInfo() [1/2]
int ICat4::ICATPortBindingProxy::getEntityInfo (const char * endpoint, const char * soap_action, ns1__getEntityInfo * ns1__getEntityInfo_, ns1__getEntityInfoResponse * ns1__getEntityInfoResponse_) virtual
Definition at line 1127 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getEntityInfo::ns1__getEntityInfo_, ICat4::ns1__getEntityInfoResponse::soap_default(), soap_endpoint, ICat4::ns1__getEntityInfoResponse::soap_get(), ICat4::soap_put___ns1__getEntityInfo(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getEntityInfo(), and ICat4::soap_serializeheader().
getEntityInfo() [2/2]
virtual int ICat4::ICATPortBindingProxy::getEntityInfo (ns1__getEntityInfo * ns1__getEntityInfo_, ns1__getEntityInfoResponse * ns1__getEntityInfoResponse_) inline virtual
Web service operation 'getEntityInfo' (returns error code or SOAP_OK)
Definition at line 240 of file ICat4ICATPortBindingProxy.h.
getEntityNames() [1/2]
int ICat4::ICATPortBindingProxy::getEntityNames (const char * endpoint, const char * soap_action, ns1__getEntityNames * ns1__getEntityNames_, ns1__getEntityNamesResponse * ns1__getEntityNamesResponse_) virtual
Definition at line 483 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getEntityNames::ns1__getEntityNames_, ICat4::ns1__getEntityNamesResponse::soap_default(), soap_endpoint, ICat4::ns1__getEntityNamesResponse::soap_get(), ICat4::soap_put___ns1__getEntityNames(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getEntityNames(), and ICat4::soap_serializeheader().
getEntityNames() [2/2]
virtual int ICat4::ICATPortBindingProxy::getEntityNames (ns1__getEntityNames * ns1__getEntityNames_, ns1__getEntityNamesResponse * ns1__getEntityNamesResponse_) inline virtual
Web service operation 'getEntityNames' (returns error code or SOAP_OK)
Definition at line 130 of file ICat4ICATPortBindingProxy.h.
getProperties() [1/2]
int ICat4::ICATPortBindingProxy::getProperties (const char * endpoint, const char * soap_action, ns1__getProperties * ns1__getProperties_, ns1__getPropertiesResponse * ns1__getPropertiesResponse_) virtual
Definition at line 215 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getProperties::ns1__getProperties_, ICat4::ns1__getPropertiesResponse::soap_default(), soap_endpoint, ICat4::ns1__getPropertiesResponse::soap_get(), ICat4::soap_put___ns1__getProperties(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getProperties(), and ICat4::soap_serializeheader().
getProperties() [2/2]
virtual int ICat4::ICATPortBindingProxy::getProperties (ns1__getProperties * ns1__getProperties_, ns1__getPropertiesResponse * ns1__getPropertiesResponse_) inline virtual
Web service operation 'getProperties' (returns error code or SOAP_OK)
Definition at line 86 of file ICat4ICATPortBindingProxy.h.
getRemainingMinutes() [1/2]
int ICat4::ICATPortBindingProxy::getRemainingMinutes (const char * endpoint, const char * soap_action, ns1__getRemainingMinutes * ns1__getRemainingMinutes_, ns1__getRemainingMinutesResponse * ns1__getRemainingMinutesResponse_) virtual
Definition at line 668 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getRemainingMinutes::ns1__getRemainingMinutes_, ICat4::ns1__getRemainingMinutesResponse::soap_default(), soap_endpoint, ICat4::ns1__getRemainingMinutesResponse::soap_get(), ICat4::soap_put___ns1__getRemainingMinutes(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getRemainingMinutes(), and ICat4::soap_serializeheader().
getRemainingMinutes() [2/2]
virtual int ICat4::ICATPortBindingProxy::getRemainingMinutes (ns1__getRemainingMinutes * ns1__getRemainingMinutes_, ns1__getRemainingMinutesResponse * ns1__getRemainingMinutesResponse_) inline virtual
Web service operation 'getRemainingMinutes' (returns error code or SOAP_OK)
Definition at line 160 of file ICat4ICATPortBindingProxy.h.
getUserName() [1/2]
int ICat4::ICATPortBindingProxy::getUserName (const char * endpoint, const char * soap_action, ns1__getUserName * ns1__getUserName_, ns1__getUserNameResponse * ns1__getUserNameResponse_) virtual
Definition at line 128 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__getUserName::ns1__getUserName_, ICat4::ns1__getUserNameResponse::soap_default(), soap_endpoint, ICat4::ns1__getUserNameResponse::soap_get(), ICat4::soap_put___ns1__getUserName(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__getUserName(), and ICat4::soap_serializeheader().
getUserName() [2/2]
virtual int ICat4::ICATPortBindingProxy::getUserName (ns1__getUserName * ns1__getUserName_, ns1__getUserNameResponse * ns1__getUserNameResponse_) inline virtual
Web service operation 'getUserName' (returns error code or SOAP_OK)
Definition at line 72 of file ICat4ICATPortBindingProxy.h.
ICATPortBindingProxy_init()
void ICat4::ICATPortBindingProxy::ICATPortBindingProxy_init (soap_mode imode, soap_mode omode) virtual
Initializer used by constructors.
Definition at line 35 of file ICat4ICATPortBindingProxy.cpp.
References soap_endpoint.
Referenced by ICATPortBindingProxy(), and reset().
isAccessAllowed() [1/2]
int ICat4::ICATPortBindingProxy::isAccessAllowed (const char * endpoint, const char * soap_action, ns1__isAccessAllowed * ns1__isAccessAllowed_, ns1__isAccessAllowedResponse * ns1__isAccessAllowedResponse_) virtual
Definition at line 758 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__isAccessAllowed::ns1__isAccessAllowed_, ICat4::ns1__isAccessAllowedResponse::soap_default(), soap_endpoint, ICat4::ns1__isAccessAllowedResponse::soap_get(), ICat4::soap_put___ns1__isAccessAllowed(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__isAccessAllowed(), and ICat4::soap_serializeheader().
isAccessAllowed() [2/2]
virtual int ICat4::ICATPortBindingProxy::isAccessAllowed (ns1__isAccessAllowed * ns1__isAccessAllowed_, ns1__isAccessAllowedResponse * ns1__isAccessAllowedResponse_) inline virtual
Web service operation 'isAccessAllowed' (returns error code or SOAP_OK)
Definition at line 176 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::isAccessAllowed().
login() [1/2]
int ICat4::ICATPortBindingProxy::login (const char * endpoint, const char * soap_action, ns1__login * ns1__login_, ns1__loginResponse * ns1__loginResponse_) virtual
Definition at line 85 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__login::ns1__login_, ICat4::ns1__loginResponse::soap_default(), soap_endpoint, ICat4::ns1__loginResponse::soap_get(), ICat4::soap_put___ns1__login(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__login(), and ICat4::soap_serializeheader().
login() [2/2]
virtual int ICat4::ICATPortBindingProxy::login (ns1__login * ns1__login_, ns1__loginResponse * ns1__loginResponse_) inline virtual
Web service operation 'login' (returns error code or SOAP_OK)
Definition at line 65 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::login().
logout() [1/2]
int ICat4::ICATPortBindingProxy::logout (const char * endpoint, const char * soap_action, ns1__logout * ns1__logout_, ns1__logoutResponse * ns1__logoutResponse_) virtual
Definition at line 621 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__logout::ns1__logout_, ICat4::__ns1__logoutResponse::ns1__logoutResponse_, ICat4::ns1__logoutResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__logoutResponse(), ICat4::soap_put___ns1__logout(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__logout(), and ICat4::soap_serializeheader().
logout() [2/2]
virtual int ICat4::ICATPortBindingProxy::logout (ns1__logout * ns1__logout_, ns1__logoutResponse * ns1__logoutResponse_) inline virtual
Web service operation 'logout' (returns error code or SOAP_OK)
Definition at line 152 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::logout().
luceneClear() [1/2]
int ICat4::ICATPortBindingProxy::luceneClear (const char * endpoint, const char * soap_action, ns1__luceneClear * ns1__luceneClear_, ns1__luceneClearResponse * ns1__luceneClearResponse_) virtual
Definition at line 850 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__luceneClear::ns1__luceneClear_, ICat4::__ns1__luceneClearResponse::ns1__luceneClearResponse_, ICat4::ns1__luceneClearResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__luceneClearResponse(), ICat4::soap_put___ns1__luceneClear(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__luceneClear(), and ICat4::soap_serializeheader().
luceneClear() [2/2]
virtual int ICat4::ICATPortBindingProxy::luceneClear (ns1__luceneClear * ns1__luceneClear_, ns1__luceneClearResponse * ns1__luceneClearResponse_) inline virtual
Web service operation 'luceneClear' (returns error code or SOAP_OK)
Definition at line 193 of file ICat4ICATPortBindingProxy.h.
luceneCommit() [1/2]
int ICat4::ICATPortBindingProxy::luceneCommit (const char * endpoint, const char * soap_action, ns1__luceneCommit * ns1__luceneCommit_, ns1__luceneCommitResponse * ns1__luceneCommitResponse_) virtual
Definition at line 898 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__luceneCommit::ns1__luceneCommit_, ICat4::__ns1__luceneCommitResponse::ns1__luceneCommitResponse_, ICat4::ns1__luceneCommitResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__luceneCommitResponse(), ICat4::soap_put___ns1__luceneCommit(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__luceneCommit(), and ICat4::soap_serializeheader().
luceneCommit() [2/2]
virtual int ICat4::ICATPortBindingProxy::luceneCommit (ns1__luceneCommit * ns1__luceneCommit_, ns1__luceneCommitResponse * ns1__luceneCommitResponse_) inline virtual
Web service operation 'luceneCommit' (returns error code or SOAP_OK)
Definition at line 200 of file ICat4ICATPortBindingProxy.h.
luceneGetPopulating() [1/2]
int ICat4::ICATPortBindingProxy::luceneGetPopulating (const char * endpoint, const char * soap_action, ns1__luceneGetPopulating * ns1__luceneGetPopulating_, ns1__luceneGetPopulatingResponse * ns1__luceneGetPopulatingResponse_) virtual
Definition at line 990 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__luceneGetPopulating::ns1__luceneGetPopulating_, ICat4::ns1__luceneGetPopulatingResponse::soap_default(), soap_endpoint, ICat4::ns1__luceneGetPopulatingResponse::soap_get(), ICat4::soap_put___ns1__luceneGetPopulating(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__luceneGetPopulating(), and ICat4::soap_serializeheader().
luceneGetPopulating() [2/2]
virtual int ICat4::ICATPortBindingProxy::luceneGetPopulating (ns1__luceneGetPopulating * ns1__luceneGetPopulating_, ns1__luceneGetPopulatingResponse * ns1__luceneGetPopulatingResponse_) inline virtual
Web service operation 'luceneGetPopulating' (returns error code or SOAP_OK)
Definition at line 217 of file ICat4ICATPortBindingProxy.h.
lucenePopulate() [1/2]
int ICat4::ICATPortBindingProxy::lucenePopulate (const char * endpoint, const char * soap_action, ns1__lucenePopulate * ns1__lucenePopulate_, ns1__lucenePopulateResponse * ns1__lucenePopulateResponse_) virtual
Definition at line 802 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__lucenePopulate::ns1__lucenePopulate_, ICat4::__ns1__lucenePopulateResponse::ns1__lucenePopulateResponse_, ICat4::ns1__lucenePopulateResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__lucenePopulateResponse(), ICat4::soap_put___ns1__lucenePopulate(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__lucenePopulate(), and ICat4::soap_serializeheader().
lucenePopulate() [2/2]
virtual int ICat4::ICATPortBindingProxy::lucenePopulate (ns1__lucenePopulate * ns1__lucenePopulate_, ns1__lucenePopulateResponse * ns1__lucenePopulateResponse_) inline virtual
Web service operation 'lucenePopulate' (returns error code or SOAP_OK)
Definition at line 185 of file ICat4ICATPortBindingProxy.h.
luceneSearch() [1/2]
int ICat4::ICATPortBindingProxy::luceneSearch (const char * endpoint, const char * soap_action, ns1__luceneSearch * ns1__luceneSearch_, ns1__luceneSearchResponse * ns1__luceneSearchResponse_) virtual
Definition at line 946 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__luceneSearch::ns1__luceneSearch_, ICat4::ns1__luceneSearchResponse::soap_default(), soap_endpoint, ICat4::ns1__luceneSearchResponse::soap_get(), ICat4::soap_put___ns1__luceneSearch(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__luceneSearch(), and ICat4::soap_serializeheader().
luceneSearch() [2/2]
virtual int ICat4::ICATPortBindingProxy::luceneSearch (ns1__luceneSearch * ns1__luceneSearch_, ns1__luceneSearchResponse * ns1__luceneSearchResponse_) inline virtual
Web service operation 'luceneSearch' (returns error code or SOAP_OK)
Definition at line 208 of file ICat4ICATPortBindingProxy.h.
refresh() [1/2]
int ICat4::ICATPortBindingProxy::refresh (const char * endpoint, const char * soap_action, ns1__refresh * ns1__refresh_, ns1__refreshResponse * ns1__refreshResponse_) virtual
Definition at line 527 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__refresh::ns1__refresh_, ICat4::__ns1__refreshResponse::ns1__refreshResponse_, ICat4::ns1__refreshResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__refreshResponse(), ICat4::soap_put___ns1__refresh(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__refresh(), and ICat4::soap_serializeheader().
refresh() [2/2]
virtual int ICat4::ICATPortBindingProxy::refresh (ns1__refresh * ns1__refresh_, ns1__refreshResponse * ns1__refreshResponse_) inline virtual
Web service operation 'refresh' (returns error code or SOAP_OK)
Definition at line 138 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::keepAlive().
reset()
void ICat4::ICATPortBindingProxy::reset () virtual
Delete all deserialized data and reset to default.
Definition at line 54 of file ICat4ICATPortBindingProxy.cpp.
References destroy(), and ICATPortBindingProxy_init().
search() [1/2]
int ICat4::ICATPortBindingProxy::search (const char * endpoint, const char * soap_action, ns1__search * ns1__search_, ns1__searchResponse * ns1__searchResponse_) virtual
Definition at line 306 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__search::ns1__search_, ICat4::ns1__searchResponse::soap_default(), soap_endpoint, ICat4::ns1__searchResponse::soap_get(), ICat4::soap_put___ns1__search(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__search(), and ICat4::soap_serializeheader().
search() [2/2]
virtual int ICat4::ICATPortBindingProxy::search (ns1__search * ns1__search_, ns1__searchResponse * ns1__searchResponse_) inline virtual
Web service operation 'search' (returns error code or SOAP_OK)
Definition at line 101 of file ICat4ICATPortBindingProxy.h.
Referenced by Mantid::ICat::ICat4Catalog::performSearch().
searchText() [1/2]
int ICat4::ICATPortBindingProxy::searchText (const char * endpoint, const char * soap_action, ns1__searchText * ns1__searchText_, ns1__searchTextResponse * ns1__searchTextResponse_) virtual
Definition at line 715 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__searchText::ns1__searchText_, ICat4::ns1__searchTextResponse::soap_default(), soap_endpoint, ICat4::ns1__searchTextResponse::soap_get(), ICat4::soap_put___ns1__searchText(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__searchText(), and ICat4::soap_serializeheader().
searchText() [2/2]
virtual int ICat4::ICATPortBindingProxy::searchText (ns1__searchText * ns1__searchText_, ns1__searchTextResponse * ns1__searchTextResponse_) inline virtual
Web service operation 'searchText' (returns error code or SOAP_OK)
Definition at line 169 of file ICat4ICATPortBindingProxy.h.
soap_close_socket()
int ICat4::ICATPortBindingProxy::soap_close_socket () virtual
Close connection (normally automatic, except for send_X ops)
Definition at line 71 of file ICat4ICATPortBindingProxy.cpp.
soap_fault()
const SOAP_ENV__Fault * ICat4::ICATPortBindingProxy::soap_fault () virtual
Get SOAP Fault structure (NULL when absent)
Definition at line 65 of file ICat4ICATPortBindingProxy.cpp.
soap_fault_detail()
const char * ICat4::ICATPortBindingProxy::soap_fault_detail () virtual
Get SOAP Fault detail as string (NULL when absent)
Definition at line 69 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::soap_faultdetail().
soap_fault_string()
const char * ICat4::ICATPortBindingProxy::soap_fault_string () virtual
Get SOAP Fault string (NULL when absent)
Definition at line 67 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::soap_faultstring().
soap_force_close_socket()
int ICat4::ICATPortBindingProxy::soap_force_close_socket () virtual
Force close connection (can kill a thread blocked on IO)
Definition at line 73 of file ICat4ICATPortBindingProxy.cpp.
soap_header()
const SOAP_ENV__Header * ICat4::ICATPortBindingProxy::soap_header () virtual
Get SOAP Header structure (NULL when absent)
Definition at line 63 of file ICat4ICATPortBindingProxy.cpp.
soap_noheader()
void ICat4::ICATPortBindingProxy::soap_noheader () virtual
Disables and removes SOAP Header from message.
Definition at line 61 of file ICat4ICATPortBindingProxy.cpp.
soap_print_fault()
void ICat4::ICATPortBindingProxy::soap_print_fault (FILE * fd) virtual
Print fault.
Definition at line 75 of file ICat4ICATPortBindingProxy.cpp.
References soap_print_fault().
Referenced by soap_print_fault().
soap_sprint_fault()
char * ICat4::ICATPortBindingProxy::soap_sprint_fault (char * buf, size_t len) virtual
Put fault into buffer.
Definition at line 82 of file ICat4ICATPortBindingProxy.cpp.
Referenced by Mantid::ICat::ICat4Catalog::throwErrorMessage().
soap_stream_fault()
void ICat4::ICATPortBindingProxy::soap_stream_fault (std::ostream & os) virtual
Print fault to stream.
Definition at line 79 of file ICat4ICATPortBindingProxy.cpp.
References soap_stream_fault().
Referenced by soap_stream_fault().
update() [1/2]
int ICat4::ICATPortBindingProxy::update (const char * endpoint, const char * soap_action, ns1__update * ns1__update_, ns1__updateResponse * ns1__updateResponse_) virtual
Definition at line 392 of file ICat4ICATPortBindingProxy.cpp.
References ICat4::__ns1__update::ns1__update_, ICat4::__ns1__updateResponse::ns1__updateResponse_, ICat4::ns1__updateResponse::soap_default(), soap_endpoint, ICat4::soap_get___ns1__updateResponse(), ICat4::soap_put___ns1__update(), ICat4::soap_putheader(), ICat4::soap_serialize___ns1__update(), and ICat4::soap_serializeheader().
update() [2/2]
virtual int ICat4::ICATPortBindingProxy::update (ns1__update * ns1__update_, ns1__updateResponse * ns1__updateResponse_) inline virtual
Web service operation 'update' (returns error code or SOAP_OK)
Definition at line 115 of file ICat4ICATPortBindingProxy.h.
Member Data Documentation
soap_endpoint
const char* ICat4::ICATPortBindingProxy::soap_endpoint
Endpoint URL of service 'ICATPortBindingProxy' (change as needed)
Definition at line 19 of file ICat4ICATPortBindingProxy.h.
Referenced by create(), createMany(), delete_(), deleteMany(), dummy(), get(), getApiVersion(), getEntityInfo(), getEntityNames(), getProperties(), getRemainingMinutes(), getUserName(), ICATPortBindingProxy(), ICATPortBindingProxy_init(), isAccessAllowed(), login(), logout(), luceneClear(), luceneCommit(), luceneGetPopulating(), lucenePopulate(), luceneSearch(), refresh(), search(), searchText(), Mantid::ICat::ICat4Catalog::setICATProxySettings(), and update().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4ICATPortBindingProxy.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4ICATPortBindingProxy.cpp