Mantid: Framework/PythonInterface/mantid/api/src/Exports/Axis.cpp File Reference
Axis.cpp File Reference
#include "MantidAPI/Axis.h"
#include "MantidAPI/BinEdgeAxis.h"
#include "MantidAPI/MatrixWorkspace.h"
#include "MantidAPI/NumericAxis.h"
#include "MantidAPI/SpectraAxis.h"
#include "MantidAPI/TextAxis.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/ssize_t.hpp>
#include <numpy/arrayobject.h>
Macros
#define NO_IMPORT_ARRAY
#define PY_ARRAY_UNIQUE_SYMBOL API_ARRAY_API
Functions
Axis * createBinEdgeAxis (int length)
Creates a BinEdgeAxis.
Axis * createNumericAxis (int length)
Creates a NumericAxis.
Axis * createSpectraAxis (const MatrixWorkspace *const ws)
Creates a SpectraAxis referencing a given workspace.
Axis * createTextAxis (int length)
Creates a TextAxis.
void export_Axis ()
void export_BinEdgeAxis ()
void export_NumericAxis ()
void export_SpectraAxis ()
void export_TextAxis ()
Macro Definition Documentation
NO_IMPORT_ARRAY
#define NO_IMPORT_ARRAY
Definition at line 25 of file Axis.cpp.
PY_ARRAY_UNIQUE_SYMBOL
#define PY_ARRAY_UNIQUE_SYMBOL API_ARRAY_API
Definition at line 24 of file Axis.cpp.
Function Documentation
createBinEdgeAxis()
Axis * createBinEdgeAxis (int length)
Creates a BinEdgeAxis.
Parameters
length The length of the new axis
Returns
pointer to the axis object
Definition at line 168 of file Axis.cpp.
Referenced by export_BinEdgeAxis().
createNumericAxis()
Axis * createNumericAxis (int length)
Creates a NumericAxis.
Parameters
length The length of the new axis
Returns
pointer to the axis object
Definition at line 148 of file Axis.cpp.
Referenced by export_NumericAxis().
createSpectraAxis()
Axis * createSpectraAxis (const MatrixWorkspace *const ws)
Creates a SpectraAxis referencing a given workspace.
Parameters
ws A pointer to the parent workspace
Returns
pointer to the axis object
Definition at line 129 of file Axis.cpp.
Referenced by export_SpectraAxis().
createTextAxis()
Axis * createTextAxis (int length)
Creates a TextAxis.
Parameters
length The length of the new axis
Returns
pointer to the axis object
Definition at line 188 of file Axis.cpp.
Referenced by export_TextAxis().
export_Axis()
void export_Axis ()
Definition at line 87 of file Axis.cpp.
References Mantid::API::Axis::getMax(), Mantid::API::Axis::getMin(), Mantid::API::Axis::getValue(), Mantid::API::Axis::indexOfValue(), Mantid::API::Axis::isNumeric(), Mantid::API::Axis::isSpectra(), Mantid::API::Axis::isText(), Mantid::API::Axis::label(), Mantid::API::Axis::length(), Mantid::API::Axis::setUnit(), Mantid::API::Axis::setValue(), Mantid::API::Axis::title(), and Mantid::API::Axis::unit().
export_BinEdgeAxis()
void export_BinEdgeAxis ()
Exported so that Boost.Python can give back a BinEdgeAxis class when an Axis* is returned
Definition at line 170 of file Axis.cpp.
References createBinEdgeAxis().
export_NumericAxis()
void export_NumericAxis ()
Exported so that Boost.Python can give back a NumericAxis class when an Axis* is returned
Definition at line 150 of file Axis.cpp.
References createNumericAxis().
export_SpectraAxis()
void export_SpectraAxis ()
Exported so that Boost.Python can give back a SpectraAxis class when an Axis* is returned
Definition at line 131 of file Axis.cpp.
References createSpectraAxis().
export_TextAxis()
void export_TextAxis ()
Definition at line 190 of file Axis.cpp.
References createTextAxis(), Mantid::API::TextAxis::label(), and Mantid::API::TextAxis::setLabel().