Mantid: MantidQt::MantidWidgets::Batch::ExtractSubtrees Class Reference
MantidQt::MantidWidgets::Batch::ExtractSubtrees Class Reference
#include <ExtractSubtrees.h>
Public Types
using RandomAccessConstRowIterator = std::vector< Row >::const_iterator
using RandomAccessRowIterator = std::vector< Row >::iterator
Public Member Functions
boost::optional< std::vector< Subtree > > operator() (std::vector< Row > region) const
Private Member Functions
RandomAccessConstRowIterator findEndOfSubtree (RandomAccessConstRowIterator subtreeBegin, RandomAccessConstRowIterator regionEnd, int subtreeRootDepth) const
Subtree makeSubtreeFromRows (RowLocation subtreeRootLocation, RandomAccessConstRowIterator subtreeBegin, RandomAccessConstRowIterator subtreeEnd) const
std::vector< Subtree > makeSubtreesFromRows (std::vector< Row > const &rows, int subtreeRootDepth) const
Detailed Description
Definition at line 24 of file ExtractSubtrees.h.
Member Typedef Documentation
RandomAccessConstRowIterator
using MantidQt::MantidWidgets::Batch::ExtractSubtrees::RandomAccessConstRowIterator = std::vector<Row>::const_iterator
Definition at line 27 of file ExtractSubtrees.h.
RandomAccessRowIterator
using MantidQt::MantidWidgets::Batch::ExtractSubtrees::RandomAccessRowIterator = std::vector<Row>::iterator
Definition at line 26 of file ExtractSubtrees.h.
Member Function Documentation
findEndOfSubtree()
auto MantidQt::MantidWidgets::Batch::ExtractSubtrees::findEndOfSubtree (RandomAccessConstRowIterator subtreeBegin, RandomAccessConstRowIterator regionEnd, int subtreeRootDepth) const private
Definition at line 14 of file ExtractSubtrees.cpp.
References MantidQt::MantidWidgets::Batch::Row::location().
Referenced by makeSubtreesFromRows().
makeSubtreeFromRows()
Subtree MantidQt::MantidWidgets::Batch::ExtractSubtrees::makeSubtreeFromRows (RowLocation subtreeRootLocation, RandomAccessConstRowIterator subtreeBegin, RandomAccessConstRowIterator subtreeEnd) const private
Definition at line 22 of file ExtractSubtrees.cpp.
References MantidQt::MantidWidgets::Batch::Row::cells(), MantidQt::MantidWidgets::Batch::Row::location(), and MantidQt::MantidWidgets::Batch::RowLocation::relativeTo().
Referenced by makeSubtreesFromRows().
makeSubtreesFromRows()
std::vector< Subtree > MantidQt::MantidWidgets::Batch::ExtractSubtrees::makeSubtreesFromRows (std::vector< Row > const & rows, int subtreeRootDepth) const private
Definition at line 32 of file ExtractSubtrees.cpp.
References findEndOfSubtree(), and makeSubtreeFromRows().
operator()()
auto MantidQt::MantidWidgets::Batch::ExtractSubtrees::operator() (std::vector< Row > region) const
Definition at line 47 of file ExtractSubtrees.cpp.
References MantidQt::MantidWidgets::Batch::allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected(), MantidQt::MantidWidgets::Batch::RowLocation::depth(), and MantidQt::MantidWidgets::Batch::rowToRowLocation().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/ExtractSubtrees.h
qt/widgets/common/src/Batch/ExtractSubtrees.cpp