Mantid: Mantid::DataObjects::CalculateReflectometryQxQz Class Reference
Mantid::DataObjects::CalculateReflectometryQxQz Class Reference
Converts from inputs of wavelength, incident theta and final theta to Qx and Qz for reflectometry experiments.
#include <CalculateReflectometryQxQz.h>
Public Member Functions
double calculateDim0 (double wavelength) const override
Executes the calculation to determine Qx.
double calculateDim1 (double wavelength) const override
Executes the calculation to determine Qz.
CalculateReflectometryQxQz (int version)
Constructor.
Mantid::Geometry::Quadrilateral createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) override
void setThetaFinal (double thetaFinal) override
Setter for the final theta value require for the calculation.
void setTwoTheta (double twoTheta) override
Set the final theta value from the detector twoTheta value.
void updateThetaIncident (double thetaIncident) override
Setter for the incident theta value require for the calculation.
Public Member Functions inherited from Mantid::DataObjects::CalculateReflectometry
CalculateReflectometry (int version)
void setThetaIncident (double thetaIncident)
Setter for the incident theta value require for the calculation.
virtual ~CalculateReflectometry ()=default
Private Attributes
double m_cos_theta_i
double m_dirQx
double m_dirQz
double m_sin_theta_i
Additional Inherited Members
Protected Attributes inherited from Mantid::DataObjects::CalculateReflectometry
double m_theta_i {0.0}
int m_version
const double to_radians_factor = M_PI / 180.0
Detailed Description
Converts from inputs of wavelength, incident theta and final theta to Qx and Qz for reflectometry experiments.
Definition at line 18 of file CalculateReflectometryQxQz.h.
Constructor & Destructor Documentation
CalculateReflectometryQxQz()
Mantid::DataObjects::CalculateReflectometryQxQz::CalculateReflectometryQxQz (int version) inline
Constructor.
Definition at line 29 of file CalculateReflectometryQxQz.h.
Member Function Documentation
calculateDim0()
double Mantid::DataObjects::CalculateReflectometryQxQz::calculateDim0 (double wavelength) const inline override virtual
Executes the calculation to determine Qx.
Parameters
wavelength : wavelenght in Anstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 69 of file CalculateReflectometryQxQz.h.
References m_dirQx.
Referenced by createQuad().
calculateDim1()
double Mantid::DataObjects::CalculateReflectometryQxQz::calculateDim1 (double wavelength) const inline override virtual
Executes the calculation to determine Qz.
Parameters
wavelength : wavelenght in Anstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 78 of file CalculateReflectometryQxQz.h.
References m_dirQz.
Referenced by createQuad().
createQuad()
Mantid::Geometry::Quadrilateral Mantid::DataObjects::CalculateReflectometryQxQz::createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) inline override virtual
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 83 of file CalculateReflectometryQxQz.h.
References Mantid::Geometry::Quadrilateral::at(), calculateDim0(), calculateDim1(), setTwoTheta(), Mantid::Geometry::Quadrilateral::shiftVertexesClockwise(), Mantid::Kernel::V2D::X(), and Mantid::Kernel::V2D::Y().
setThetaFinal()
void Mantid::DataObjects::CalculateReflectometryQxQz::setThetaFinal (double thetaFinal) inline override virtual
Setter for the final theta value require for the calculation.
Internally pre-calculates and caches to cos theta for speed.
Parameters
thetaFinal final theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 47 of file CalculateReflectometryQxQz.h.
References m_cos_theta_i, m_dirQx, m_dirQz, m_sin_theta_i, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Referenced by setTwoTheta().
setTwoTheta()
void Mantid::DataObjects::CalculateReflectometryQxQz::setTwoTheta (double twoTheta) inline override virtual
Set the final theta value from the detector twoTheta value.
Parameters
twoTheta detector twoTheta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 58 of file CalculateReflectometryQxQz.h.
References Mantid::DataObjects::CalculateReflectometry::m_theta_i, Mantid::DataObjects::CalculateReflectometry::m_version, setThetaFinal(), and Mantid::Kernel::twoTheta.
Referenced by createQuad().
updateThetaIncident()
void Mantid::DataObjects::CalculateReflectometryQxQz::updateThetaIncident (double thetaIncident) inline override virtual
Setter for the incident theta value require for the calculation.
Internally pre-calculates and caches to cos theta for speed.
Parameters
thetaIncident incident theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 37 of file CalculateReflectometryQxQz.h.
References m_cos_theta_i, m_sin_theta_i, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Member Data Documentation
m_cos_theta_i
double Mantid::DataObjects::CalculateReflectometryQxQz::m_cos_theta_i private
Definition at line 20 of file CalculateReflectometryQxQz.h.
Referenced by setThetaFinal(), and updateThetaIncident().
m_dirQx
double Mantid::DataObjects::CalculateReflectometryQxQz::m_dirQx private
Definition at line 22 of file CalculateReflectometryQxQz.h.
Referenced by calculateDim0(), and setThetaFinal().
m_dirQz
double Mantid::DataObjects::CalculateReflectometryQxQz::m_dirQz private
Definition at line 23 of file CalculateReflectometryQxQz.h.
Referenced by calculateDim1(), and setThetaFinal().
m_sin_theta_i
double Mantid::DataObjects::CalculateReflectometryQxQz::m_sin_theta_i private
Definition at line 21 of file CalculateReflectometryQxQz.h.
Referenced by setThetaFinal(), and updateThetaIncident().
The documentation for this class was generated from the following file:
Framework/DataObjects/inc/MantidDataObjects/CalculateReflectometryQxQz.h