Mantid: Mantid::API::IFunction::Attribute Class Reference
Mantid::API::IFunction::Attribute Class Reference
Attribute is a non-fitting parameter.
#include <IFunction.h>
Public Member Functions
template<typename... Ts>
void apply (AttributeLambdaVisitor< Ts... > &v)
Apply a lambda visitor.
template<typename T >
T apply (AttributeVisitor< T > &v)
Apply an attribute visitor.
template<typename T >
T apply (ConstAttributeVisitor< T > &v) const
Apply a const attribute visitor.
bool asBool () const
Returns bool value if attribute is a bool, throws exception otherwise.
double asDouble () const
Returns double value if attribute is a double, throws exception otherwise.
int asInt () const
Returns int value if attribute is a int, throws exception otherwise.
std::string asQuotedString () const
Returns a string value that is guarenteed to be quoted for use in places where the string is used as the displayed value.
std::string asString () const
Returns string value if attribute is a string, throws exception otherwise.
std::string asUnquotedString () const
Returns a string value that is guarenteed to be unquoted.
std::vector< double > asVector () const
Returns vector<double> if attribute is vector<double>, throws exception otherwise.
Attribute ()
Create empty string attribute.
Attribute (const bool &b)
Create bool attribute.
Attribute (const char *c)
Create string attribute.
Attribute (const double &d)
Create double attribute.
Attribute (const int &i)
Create int attribute.
Attribute (const std::string &str, bool quoteValue=false)
Create string attribute.
Attribute (const std::vector< double > &v)
Create vector attribute.
void evaluateValidator () const
Evaluates the validator associated with this attribute. Returns error as a string.
template<typename T >
void evaluateValidator (T &inputData) const
Evaluates the validator associated with this attribute with regards to input value. Returns error as a string.
void fromString (const std::string &str)
Set value from a string.
Kernel::IValidator_sptr getValidator ()
Return a clone of the attribute validator;.
bool isEmpty () const
Check if a string attribute is empty.
void setBool (const bool &)
Sets new value if attribute is a bool.
void setDouble (const double &)
Sets new value if attribute is a double.
void setInt (const int &)
Sets new value if attribute is a int.
void setString (const std::string &str)
Sets new value if attribute is a string.
void setValidator (const Kernel::IValidator_sptr &validator) const
Set validator to enforce limits on attribute value.
template<typename T >
void setValue (const T &v)
void setVector (const std::vector< double > &)
Sets new value if attribute is a vector.
std::string type () const
Returns type of the attribute.
std::string value () const
Returns the attribute value as a string.
Private Attributes
boost::variant< std::string, int, double, bool, std::vector< double > > m_data
The data holder as boost variant.
bool m_quoteValue = false
Flag indicating if the string value should be returned quoted.
Kernel::IValidator_sptr m_validator
Associated Validator.
Detailed Description
Attribute is a non-fitting parameter.
It can be one of the types: std::string, int, or double Examples: file name, polinomial order
Definition at line 285 of file IFunction.h.
Constructor & Destructor Documentation
Attribute() [1/7]
Mantid::API::IFunction::Attribute::Attribute () inline explicit
Create empty string attribute.
Definition at line 288 of file IFunction.h.
Attribute() [2/7]
Mantid::API::IFunction::Attribute::Attribute (const std::string & str, bool quoteValue = false) inline explicit
Create string attribute.
Definition at line 290 of file IFunction.h.
Attribute() [3/7]
Mantid::API::IFunction::Attribute::Attribute (const int & i) inline explicit
Create int attribute.
Definition at line 292 of file IFunction.h.
Attribute() [4/7]
Mantid::API::IFunction::Attribute::Attribute (const double & d) inline explicit
Create double attribute.
Definition at line 294 of file IFunction.h.
References Mantid::Geometry::d.
Attribute() [5/7]
Mantid::API::IFunction::Attribute::Attribute (const bool & b) inline explicit
Create bool attribute.
Definition at line 296 of file IFunction.h.
Attribute() [6/7]
Mantid::API::IFunction::Attribute::Attribute (const char * c) inline explicit
Create string attribute.
Definition at line 298 of file IFunction.h.
Attribute() [7/7]
Mantid::API::IFunction::Attribute::Attribute (const std::vector< double > & v) inline explicit
Create vector attribute.
Definition at line 300 of file IFunction.h.
Member Function Documentation
apply() [1/3]
template<typename... Ts> void Mantid::API::IFunction::Attribute::apply (AttributeLambdaVisitor< Ts... > & v) inline
Apply a lambda visitor.
Definition at line 307 of file IFunction.h.
References m_data.
apply() [2/3]
template<typename T > T Mantid::API::IFunction::Attribute::apply (AttributeVisitor< T > & v) inline
Apply an attribute visitor.
Definition at line 303 of file IFunction.h.
References m_data.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addAttributeProperty(), MantidQt::MantidWidgets::PropertyHandler::initAttributes(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::FunctionTreeView::setAttributeToFunction(), and type().
apply() [3/3]
template<typename T > T Mantid::API::IFunction::Attribute::apply (ConstAttributeVisitor< T > & v) const inline
Apply a const attribute visitor.
Definition at line 305 of file IFunction.h.
References m_data.
asBool()
bool Mantid::API::IFunction::Attribute::asBool () const
Returns bool value if attribute is a bool, throws exception otherwise.
Return the attribute as a bool if it is a bool.
Definition at line 827 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldMagnetisationBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldMomentBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityBase::function1D(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::CurveFitting::Functions::BSpline::resetKnots(), Mantid::CurveFitting::Functions::BSpline::setAttribute(), Mantid::CurveFitting::Functions::Convolution::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
asDouble()
double Mantid::API::IFunction::Attribute::asDouble () const
Returns double value if attribute is a double, throws exception otherwise.
Return the attribute as a double if it is a double.
Definition at line 814 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldFunction::calcExcitations(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), Mantid::CurveFitting::Functions::BSpline::derivative1D(), Mantid::CurveFitting::Functions::BSpline::function1D(), Mantid::CurveFitting::Functions::ChudleyElliotSQE::function1D(), Mantid::CurveFitting::Functions::CriticalPeakRelaxationRate::function1D(), Mantid::CurveFitting::Functions::CrystalFieldHeatCapacityBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldMagnetisationBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldMomentBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityBase::function1D(), Mantid::CurveFitting::Functions::FickDiffusionSQE::function1D(), Mantid::CurveFitting::Functions::HallRossSQE::function1D(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::function1D(), Mantid::CurveFitting::Functions::InelasticDiffSphere::function1D(), Mantid::CurveFitting::Functions::InelasticIsoRotDiff::function1D(), Mantid::CurveFitting::Functions::Meier::function1D(), Mantid::CurveFitting::Functions::TeixeiraWaterSQE::function1D(), Mantid::CurveFitting::Functions::CrystalFieldPeaks::functionGeneral(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::CurveFitting::Functions::ElasticDiffRotDiscreteCircle::HeightPrefactor(), Mantid::CurveFitting::Functions::ElasticDiffSphere::HeightPrefactor(), Mantid::CurveFitting::Functions::ElasticIsoRotDiff::HeightPrefactor(), Mantid::CurveFitting::Functions::BSpline::resetKnots(), Mantid::CurveFitting::Functions::Chebyshev::setAttribute(), Mantid::CurveFitting::Functions::CubicSpline::setAttribute(), Mantid::CurveFitting::Functions::DynamicKuboToyabe::setAttribute(), Mantid::CurveFitting::Functions::FullprofPolynomial::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), Mantid::CurveFitting::Functions::CubicSpline::setupInput(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
asInt()
int Mantid::API::IFunction::Attribute::asInt () const
Returns int value if attribute is a int, throws exception otherwise.
Return the attribute as an int if it is a int.
Definition at line 801 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::BSpline::derivative1D(), Mantid::CurveFitting::Functions::CubicSpline::derivative1D(), Mantid::CurveFitting::Functions::CubicSpline::function1D(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::function1D(), Mantid::CurveFitting::Functions::InelasticDiffSphere::function1D(), Mantid::CurveFitting::Functions::InelasticIsoRotDiff::function1D(), Mantid::FrameworkTestHelpers::MultiDomainFunctionTest_Function::function1D(), Mantid::FrameworkTestHelpers::MultiDomainFunctionTest_Function::functionDeriv1D(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::CurveFitting::Functions::ElasticDiffRotDiscreteCircle::HeightPrefactor(), Mantid::CurveFitting::Functions::Chebyshev::setAttribute(), Mantid::CurveFitting::Functions::CubicSpline::setAttribute(), Mantid::CurveFitting::Functions::FullprofPolynomial::setAttribute(), Mantid::CurveFitting::Functions::Polynomial::setAttribute(), Mantid::CurveFitting::Functions::ReflectivityMulf::setAttribute(), Mantid::CurveFitting::Functions::FunctionQDepends::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::ConvolutionFunctionModel::setPrefix(), Mantid::CurveFitting::Functions::TabulatedFunction::setupData(), and Mantid::CurveFitting::Functions::CubicSpline::setXAttribute().
asQuotedString()
std::string Mantid::API::IFunction::Attribute::asQuotedString () const
Returns a string value that is guarenteed to be quoted for use in places where the string is used as the displayed value.
Return the attribute as a quoted string if it is a string.
Definition at line 751 of file IFunction.cpp.
References m_data.
asString()
std::string Mantid::API::IFunction::Attribute::asString () const
Returns string value if attribute is a string, throws exception otherwise.
Return the attribute as a string if it is a string.
Definition at line 735 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::calculateEigenSystem(), Mantid::CurveFitting::Functions::CrystalFieldMagnetisationBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldMomentBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityBase::function1D(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::MDAlgorithms::UserFunctionMD::setAttribute(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldControl::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), Mantid::API::MultiDomainFunction::setLocalAttribute(), MantidQt::MantidWidgets::ConvolutionFunctionModel::setPrefix(), Mantid::CurveFitting::Functions::TabulatedFunction::setupData(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
asUnquotedString()
std::string Mantid::API::IFunction::Attribute::asUnquotedString () const
Returns a string value that is guarenteed to be unquoted.
Return the attribute as an unquoted string if it is a string.
Definition at line 777 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldControl::setAttribute().
asVector()
std::vector< double > Mantid::API::IFunction::Attribute::asVector () const
Returns vector<double> if attribute is vector<double>, throws exception otherwise.
Return the attribute as a bool if it is a vector.
Definition at line 840 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldControl::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldControl::cacheAttributes(), Mantid::CurveFitting::Functions::CrystalFieldMagnetisationBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldMomentBase::function1D(), Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityBase::function1D(), Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), Mantid::CurveFitting::Functions::BSpline::resetKnots(), Mantid::CurveFitting::Functions::BSpline::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldControl::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteSingleSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
evaluateValidator() [1/2]
void Mantid::API::IFunction::Attribute::evaluateValidator () const
Evaluates the validator associated with this attribute. Returns error as a string.
Evaluates the validator associated with this attribute.
Definition at line 1059 of file IFunction.cpp.
References m_data.
Referenced by Mantid::API::IFunction::declareAttribute().
evaluateValidator() [2/2]
template<typename T > void Mantid::API::IFunction::Attribute::evaluateValidator (T & inputData) const inline
Evaluates the validator associated with this attribute with regards to input value. Returns error as a string.
Definition at line 314 of file IFunction.h.
References m_validator.
fromString()
void Mantid::API::IFunction::Attribute::fromString (const std::string & str)
Set value from a string.
Throws exception if the string has wrong format
Parameters
str :: String representation of the new value
Definition at line 1046 of file IFunction.cpp.
References m_validator, and tmp.
Referenced by Mantid::API::FunctionFactoryImpl::createSimple(), and MantidQt::MantidWidgets::PropertyHandler::setAttribute().
getValidator()
Kernel::IValidator_sptr Mantid::API::IFunction::Attribute::getValidator () inline
Return a clone of the attribute validator;.
Definition at line 320 of file IFunction.h.
References m_validator.
Referenced by MantidQt::MantidWidgets::PropertyHandler::initAttributes(), Mantid::CurveFitting::Functions::BSpline::resetValidators(), and MantidQt::MantidWidgets::PropertyHandler::setAttribute().
isEmpty()
bool Mantid::API::IFunction::Attribute::isEmpty () const
Check if a string attribute is empty.
Definition at line 933 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::hasBackground().
setBool()
void Mantid::API::IFunction::Attribute::setBool (const bool & b)
Sets new value if attribute is a bool.
Sets new value if attribute is an bool.
If the type is wrong throws an exception
Parameters
b :: The new value
Definition at line 902 of file IFunction.cpp.
References m_data.
setDouble()
void Mantid::API::IFunction::Attribute::setDouble (const double & d)
Sets new value if attribute is a double.
If the type is wrong throws an exception
Parameters
d :: The new value
Definition at line 870 of file IFunction.cpp.
References Mantid::Geometry::d, and m_data.
setInt()
void Mantid::API::IFunction::Attribute::setInt (const int & i)
Sets new value if attribute is a int.
Sets new value if attribute is an int.
If the type is wrong throws an exception
Parameters
i :: The new value
Definition at line 886 of file IFunction.cpp.
References m_data.
setString()
void Mantid::API::IFunction::Attribute::setString (const std::string & str)
Sets new value if attribute is a string.
If the type is wrong throws an exception
Parameters
str :: The new value
Definition at line 854 of file IFunction.cpp.
References m_data.
Referenced by Mantid::API::IFunction::setAttributeValue().
setValidator()
void Mantid::API::IFunction::Attribute::setValidator (const Kernel::IValidator_sptr & validator) const
Set validator to enforce limits on attribute value.
Parameters
validator :: shared ptr to validator object
Definition at line 1054 of file IFunction.cpp.
References m_validator.
Referenced by Mantid::API::IFunction::declareAttribute().
setValue()
template<typename T > void Mantid::API::IFunction::Attribute::setValue (const T & v) inline
Definition at line 357 of file IFunction.h.
References m_data.
setVector()
void Mantid::API::IFunction::Attribute::setVector (const std::vector< double > & v)
Sets new value if attribute is a vector.
If the type is wrong throws an exception
Parameters
v :: The new value
Definition at line 919 of file IFunction.cpp.
References m_data.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute().
type()
std::string Mantid::API::IFunction::Attribute::type () const
Returns type of the attribute.
Definition at line 683 of file IFunction.cpp.
References apply(), and tmp.
Referenced by Mantid::PythonInterface::IFunctionAdapter::getAttributeValue(), and MantidQt::MantidWidgets::PropertyHandler::setAttribute().
value()
std::string Mantid::API::IFunction::Attribute::value () const
Returns the attribute value as a string.
Definition at line 727 of file IFunction.cpp.
References tmp.
Referenced by Mantid::API::IFunction::writeToString(), Mantid::API::CompositeFunction::writeToString(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
Member Data Documentation
m_data
boost::variant<std::string, int, double, bool, std::vector<double> > Mantid::API::IFunction::Attribute::m_data mutable private
The data holder as boost variant.
Definition at line 367 of file IFunction.h.
m_quoteValue
bool Mantid::API::IFunction::Attribute::m_quoteValue = false private
Flag indicating if the string value should be returned quoted.
Definition at line 369 of file IFunction.h.
m_validator
Kernel::IValidator_sptr Mantid::API::IFunction::Attribute::m_validator mutable private
Associated Validator.
Definition at line 371 of file IFunction.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IFunction.h
Framework/API/src/IFunction.cpp