Mantid: MantidQt::MantidWidgets::FindAlgComboBox Class Reference
MantidQt::MantidWidgets::FindAlgComboBox Class Reference
ComboBox for finding algorithms.
#include <AlgorithmSelectorWidget.h>
Public Slots
void update ()
Update the list of algos in the combo box.
Signals
void enterPressed ()
Public Member Functions
SelectedAlgorithm getSelectedAlgorithm ()
Return the selected algorithm.
~FindAlgComboBox () override=default
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
Called when the combo box for finding algorithms has a key press event
Private Types
using AlgNamesType = std::vector< Mantid::API::AlgorithmDescriptor >
Private Member Functions
void addAliases (AlgNamesType &algNamesList)
Adds alias entries to the list of algorithms.
QString stripAlias (const QString &text) const
if a string is for an alias convert it to the algorithm name
Detailed Description
ComboBox for finding algorithms.
Definition at line 123 of file AlgorithmSelectorWidget.h.
Member Typedef Documentation
AlgNamesType
using MantidQt::MantidWidgets::FindAlgComboBox::AlgNamesType = std::vector<Mantid::API::AlgorithmDescriptor> private
Definition at line 139 of file AlgorithmSelectorWidget.h.
Constructor & Destructor Documentation
~FindAlgComboBox()
MantidQt::MantidWidgets::FindAlgComboBox::~FindAlgComboBox () override default
Member Function Documentation
addAliases()
void MantidQt::MantidWidgets::FindAlgComboBox::addAliases (AlgNamesType & algNamesList) private
Adds alias entries to the list of algorithms.
Definition at line 348 of file AlgorithmSelectorWidget.cpp.
References Mantid::API::AlgorithmDescriptor::name.
Referenced by update().
enterPressed
void MantidQt::MantidWidgets::FindAlgComboBox::enterPressed () signal
Referenced by keyPressEvent().
getSelectedAlgorithm()
SelectedAlgorithm MantidQt::MantidWidgets::FindAlgComboBox::getSelectedAlgorithm ()
Return the selected algorithm.
Definition at line 377 of file AlgorithmSelectorWidget.cpp.
References stripAlias().
Referenced by MantidQt::MantidWidgets::AlgorithmSelectorWidget::getSelectedAlgorithm().
keyPressEvent()
void MantidQt::MantidWidgets::FindAlgComboBox::keyPressEvent (QKeyEvent * e) override protected
Called when the combo box for finding algorithms has a key press event
Definition at line 319 of file AlgorithmSelectorWidget.cpp.
References enterPressed().
stripAlias()
QString MantidQt::MantidWidgets::FindAlgComboBox::stripAlias (const QString & text) const private
if a string is for an alias convert it to the algorithm name
Definition at line 364 of file AlgorithmSelectorWidget.cpp.
Referenced by getSelectedAlgorithm().
update
void MantidQt::MantidWidgets::FindAlgComboBox::update () slot
Update the list of algos in the combo box.
Definition at line 329 of file AlgorithmSelectorWidget.cpp.
References addAliases(), addItem(), and Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by MantidQt::MantidWidgets::AlgorithmSelectorWidget::update().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmSelectorWidget.h
qt/widgets/common/src/AlgorithmSelectorWidget.cpp