Mantid: Mantid::Geometry::PolygonEdge Class Reference
Mantid::Geometry::PolygonEdge Class Reference
PolygonEdge Defines a directed edge between two points on a polygon.
#include <PolygonEdge.h>
Public Types
enum Orientation {
Collinear , Parallel , Skew , SkewCross ,
SkewNoCross
}
Defines the orientation with respect to another edge.
Public Member Functions
const Kernel::V2D & direction () const
Return the direction.
const Kernel::V2D & end () const
Access the end point.
Kernel::V2D point (const double fraction) const
Create a point a given fraction along this edge.
PolygonEdge (const Kernel::V2D &start, const Kernel::V2D &end)
Constructor with starting and ending points.
const Kernel::V2D & start () const
Access the start point.
Private Member Functions
PolygonEdge ()
Default constructor.
Private Attributes
const Kernel::V2D m_dir
Direction vector.
const Kernel::V2D m_end
Destination point.
const Kernel::V2D m_start
Origin point.
Detailed Description
PolygonEdge Defines a directed edge between two points on a polygon.
Author
Martyn Gigg
Date
2011-07-08
Definition at line 23 of file PolygonEdge.h.
Member Enumeration Documentation
Orientation
enum Mantid::Geometry::PolygonEdge::Orientation
Defines the orientation with respect to another edge.
Enumerator
Collinear
Edges lie on the same line.
Parallel
Edges point in the same direction.
Skew
Edges are at an angle to each other.
SkewCross
Edges are at an angle and intersect.
SkewNoCross
Edges are at an angle and do not intersect.
Definition at line 26 of file PolygonEdge.h.
Constructor & Destructor Documentation
PolygonEdge() [1/2]
Mantid::Geometry::PolygonEdge::PolygonEdge (const Kernel::V2D & start, const Kernel::V2D & end)
Constructor with starting and ending points.
Contructor taking two points, start and end.
Definition at line 28 of file PolygonEdge.cpp.
PolygonEdge() [2/2]
Mantid::Geometry::PolygonEdge::PolygonEdge () private
Default constructor.
Member Function Documentation
direction()
const Kernel::V2D & Mantid::Geometry::PolygonEdge::direction () const inline
Return the direction.
Definition at line 41 of file PolygonEdge.h.
Referenced by Mantid::Geometry::classify(), Mantid::Geometry::crossingPoint(), Mantid::Geometry::edgeAimsAt(), and Mantid::Geometry::orientation().
end()
const Kernel::V2D & Mantid::Geometry::PolygonEdge::end () const inline
Access the end point.
Definition at line 39 of file PolygonEdge.h.
Referenced by Mantid::Geometry::classify(), Mantid::Geometry::crossingPoint(), Mantid::Geometry::intersection(), and Mantid::Geometry::orientation().
point()
Kernel::V2D Mantid::Geometry::PolygonEdge::point (const double fraction) const
Create a point a given fraction along this edge.
Parameters
fraction :: The fraction of the current edge
Returns
A point on the edge
Definition at line 36 of file PolygonEdge.cpp.
References m_dir, and start().
Referenced by Mantid::Geometry::crossingPoint().
start()
const Kernel::V2D & Mantid::Geometry::PolygonEdge::start () const inline
Access the start point.
Definition at line 37 of file PolygonEdge.h.
Referenced by Mantid::Geometry::classify(), Mantid::Geometry::crossingPoint(), Mantid::Geometry::intersection(), Mantid::Geometry::orientation(), and point().
Member Data Documentation
m_dir
const Kernel::V2D Mantid::Geometry::PolygonEdge::m_dir private
Direction vector.
Definition at line 54 of file PolygonEdge.h.
Referenced by point().
m_end
const Kernel::V2D Mantid::Geometry::PolygonEdge::m_end private
Destination point.
Definition at line 52 of file PolygonEdge.h.
m_start
const Kernel::V2D Mantid::Geometry::PolygonEdge::m_start private
Origin point.
Definition at line 50 of file PolygonEdge.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Math/PolygonEdge.h
Framework/Geometry/src/Math/PolygonEdge.cpp