Mantid: Mantid::API::ImplicitFunctionParser Class Reference
Mantid::API::ImplicitFunctionParser Class Reference abstract
XML Parser for function types.
#include <ImplicitFunctionParser.h>
Public Types
using SuccessorType = boost::interprocess::unique_ptr< ImplicitFunctionParser, DeleterPolicy< ImplicitFunctionParser > >
Successor type. Unique pointer with stack scoped deletion semantics.
Public Member Functions
virtual ImplicitFunctionBuilder * createFunctionBuilder (Poco::XML::Element *functionElement)=0
ImplicitFunctionParser (ImplicitFunctionParameterParser *parameterParser)
virtual void setParameterParser (ImplicitFunctionParameterParser *parser)=0
virtual void setSuccessorParser (ImplicitFunctionParser *parser)=0
virtual ~ImplicitFunctionParser ()=default
Protected Member Functions
void checkSuccessorExists ()
ImplicitFunctionParameter * parseParameter (Poco::XML::Element *pRoot)
Protected Attributes
ImplicitFunctionParameterParser::SuccessorType m_paramParserRoot
SuccessorType m_successor
Detailed Description
XML Parser for function types.
See chain of reponsibility pattern.
Author
Owen Arnold, Tessella plc
Date
01/10/2010
Definition at line 50 of file ImplicitFunctionParser.h.
Member Typedef Documentation
SuccessorType
using Mantid::API::ImplicitFunctionParser::SuccessorType = boost::interprocess::unique_ptr<ImplicitFunctionParser, DeleterPolicy<ImplicitFunctionParser> >
Successor type. Unique pointer with stack scoped deletion semantics.
Definition at line 53 of file ImplicitFunctionParser.h.
Constructor & Destructor Documentation
ImplicitFunctionParser()
Mantid::API::ImplicitFunctionParser::ImplicitFunctionParser (ImplicitFunctionParameterParser * parameterParser) inline
Definition at line 73 of file ImplicitFunctionParser.h.
~ImplicitFunctionParser()
virtual Mantid::API::ImplicitFunctionParser::~ImplicitFunctionParser () virtual default
Member Function Documentation
checkSuccessorExists()
void Mantid::API::ImplicitFunctionParser::checkSuccessorExists () inline protected
Definition at line 64 of file ImplicitFunctionParser.h.
createFunctionBuilder()
virtual ImplicitFunctionBuilder * Mantid::API::ImplicitFunctionParser::createFunctionBuilder (Poco::XML::Element * functionElement) pure virtual
Referenced by Mantid::API::ImplicitFunctionFactoryImpl::createUnwrapped().
parseParameter()
ImplicitFunctionParameter * Mantid::API::ImplicitFunctionParser::parseParameter (Poco::XML::Element * pRoot) inline protected
Definition at line 60 of file ImplicitFunctionParser.h.
setParameterParser()
virtual void Mantid::API::ImplicitFunctionParser::setParameterParser (ImplicitFunctionParameterParser * parser) pure virtual
Referenced by Mantid::API::ImplicitFunctionParserFactoryImpl::createImplicitFunctionParserFromXML().
setSuccessorParser()
virtual void Mantid::API::ImplicitFunctionParser::setSuccessorParser (ImplicitFunctionParser * parser) pure virtual
Referenced by Mantid::API::ImplicitFunctionParserFactoryImpl::createImplicitFunctionParserFromXML().
Member Data Documentation
m_paramParserRoot
ImplicitFunctionParameterParser::SuccessorType Mantid::API::ImplicitFunctionParser::m_paramParserRoot protected
Definition at line 56 of file ImplicitFunctionParser.h.
m_successor
SuccessorType Mantid::API::ImplicitFunctionParser::m_successor protected
Definition at line 58 of file ImplicitFunctionParser.h.
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/ImplicitFunctionParser.h