Mantid: Mantid::DataHandling::SpiceXMLNode Class Reference
Mantid::DataHandling::SpiceXMLNode Class Reference
#include <LoadSpiceXML2DDet.h>
Public Member Functions
const std::string getDescription () const
Get node's description.
const std::string getName () const
Get name of XML node.
const std::string getUnit () const
Get unit of XML node.
const std::string getValue () const
Get node's value in string.
bool hasUnit () const
Check whether XML has unit set.
bool hasValue () const
Check whether XML node has value set.
bool isDouble () const
Is this node of double type?
bool isInteger () const
Is this node of integer type?
bool isString () const
Is this node of string type?
void setParameters (const std::string &nodetype, const std::string &nodeunit, const std::string &nodedescription)
Set XML node parameters.
void setValue (const std::string &strvalue)
Set node value in string format.
SpiceXMLNode (std::string nodename)
Constructor for SpiceXMLNode.
Public Attributes
std::string m_description
std::string m_name
char m_typechar
std::string m_typefullname
std::string m_unit
std::string m_value
Detailed Description
Definition at line 17 of file LoadSpiceXML2DDet.h.
Constructor & Destructor Documentation
SpiceXMLNode()
Mantid::DataHandling::SpiceXMLNode::SpiceXMLNode (std::string nodename)
Constructor for SpiceXMLNode.
SpiceXMLNode::SpiceXMLNode
Parameters
nodename
Definition at line 52 of file LoadSpiceXML2DDet.cpp.
Member Function Documentation
getDescription()
const std::string Mantid::DataHandling::SpiceXMLNode::getDescription () const
Get node's description.
SpiceXMLNode::getDescription
Returns
Definition at line 131 of file LoadSpiceXML2DDet.cpp.
References m_description.
getName()
const std::string Mantid::DataHandling::SpiceXMLNode::getName () const
Get name of XML node.
SpiceXMLNode::getName
Returns
Definition at line 119 of file LoadSpiceXML2DDet.cpp.
References m_name.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry().
getUnit()
const std::string Mantid::DataHandling::SpiceXMLNode::getUnit () const
Get unit of XML node.
SpiceXMLNode::getUnit
Returns
Definition at line 125 of file LoadSpiceXML2DDet.cpp.
References m_unit.
getValue()
const std::string Mantid::DataHandling::SpiceXMLNode::getValue () const
Get node's value in string.
SpiceXMLNode::getValue
Returns
Definition at line 137 of file LoadSpiceXML2DDet.cpp.
References m_value.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry().
hasUnit()
bool Mantid::DataHandling::SpiceXMLNode::hasUnit () const
Check whether XML has unit set.
Definition at line 89 of file LoadSpiceXML2DDet.cpp.
References m_unit.
hasValue()
bool Mantid::DataHandling::SpiceXMLNode::hasValue () const
Check whether XML node has value set.
SpiceXMLNode::hasValue
Returns
Definition at line 95 of file LoadSpiceXML2DDet.cpp.
References m_value.
isDouble()
bool Mantid::DataHandling::SpiceXMLNode::isDouble () const
Is this node of double type?
SpiceXMLNode::isDouble
Returns
Definition at line 113 of file LoadSpiceXML2DDet.cpp.
References Mantid::DataHandling::FLOAT32, and m_typechar.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry().
isInteger()
bool Mantid::DataHandling::SpiceXMLNode::isInteger () const
Is this node of integer type?
SpiceXMLNode::isInteger
Returns
Definition at line 107 of file LoadSpiceXML2DDet.cpp.
References Mantid::DataHandling::INT32, and m_typechar.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry().
isString()
bool Mantid::DataHandling::SpiceXMLNode::isString () const
Is this node of string type?
SpiceXMLNode::isString
Returns
Definition at line 101 of file LoadSpiceXML2DDet.cpp.
References m_typechar, and Mantid::DataHandling::STRING.
setParameters()
void Mantid::DataHandling::SpiceXMLNode::setParameters (const std::string & nodetype, const std::string & nodeunit, const std::string & nodedescription)
Set XML node parameters.
SpiceXMLNode::setValues
Parameters
nodetype
nodeunit
nodedescription
Definition at line 66 of file LoadSpiceXML2DDet.cpp.
References Mantid::DataHandling::FLOAT32, Mantid::DataHandling::INT32, m_description, m_typechar, m_typefullname, and m_unit.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseSpice().
setValue()
void Mantid::DataHandling::SpiceXMLNode::setValue (const std::string & strvalue)
Set node value in string format.
SpiceXMLNode::setValue
Parameters
strvalue
Definition at line 58 of file LoadSpiceXML2DDet.cpp.
References m_value.
Referenced by Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseSpice().
Member Data Documentation
m_description
std::string Mantid::DataHandling::SpiceXMLNode::m_description
Definition at line 40 of file LoadSpiceXML2DDet.h.
Referenced by getDescription(), and setParameters().
m_name
std::string Mantid::DataHandling::SpiceXMLNode::m_name
Definition at line 35 of file LoadSpiceXML2DDet.h.
Referenced by getName().
m_typechar
char Mantid::DataHandling::SpiceXMLNode::m_typechar
Definition at line 38 of file LoadSpiceXML2DDet.h.
Referenced by isDouble(), isInteger(), isString(), and setParameters().
m_typefullname
std::string Mantid::DataHandling::SpiceXMLNode::m_typefullname
Definition at line 39 of file LoadSpiceXML2DDet.h.
Referenced by setParameters().
m_unit
std::string Mantid::DataHandling::SpiceXMLNode::m_unit
Definition at line 37 of file LoadSpiceXML2DDet.h.
Referenced by getUnit(), hasUnit(), and setParameters().
m_value
std::string Mantid::DataHandling::SpiceXMLNode::m_value
Definition at line 36 of file LoadSpiceXML2DDet.h.
Referenced by getValue(), hasValue(), and setValue().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadSpiceXML2DDet.h
Framework/DataHandling/src/LoadSpiceXML2DDet.cpp