Mantid: Mantid::Geometry::AlgorithmicSpaceGroupGenerator Class Reference
Mantid::Geometry::AlgorithmicSpaceGroupGenerator Class Reference
Concrete space group generator that uses space group generators as given in ITA.
#include <SpaceGroupFactory.h>
Public Member Functions
AlgorithmicSpaceGroupGenerator (size_t number, const std::string &hmSymbol, const std::string &generatorInformation)
Constructor of AlgorithmicSpaceGroupGenerator which throws an std::runtime_error exception when the generatorInformation string cannot be interpreted as symmetry operations.
Public Member Functions inherited from Mantid::Geometry::AbstractSpaceGroupGenerator
AbstractSpaceGroupGenerator (size_t number, std::string hmSymbol, std::string generatorInformation)
Constructor for AbstractSpaceGroupGenerator.
const std::string & getGeneratorString () const
const std::string & getHMSymbol () const
size_t getNumber () const
SpaceGroup_const_sptr getPrototype ()
Returns the internally stored prototype, generates one if necessary.
virtual ~AbstractSpaceGroupGenerator ()=default
Protected Member Functions
Group_const_sptr generateGroup () const override
Uses an algorithm based on Shmueli, U.
std::string getCenteringSymbol () const
Returns the centering symbol, which is extracted from the Hermann-Mauguin-symbol.
Detailed Description
Concrete space group generator that uses space group generators as given in ITA.
Definition at line 68 of file SpaceGroupFactory.h.
Constructor & Destructor Documentation
AlgorithmicSpaceGroupGenerator()
Mantid::Geometry::AlgorithmicSpaceGroupGenerator::AlgorithmicSpaceGroupGenerator (size_t number, const std::string & hmSymbol, const std::string & generatorInformation)
Constructor of AlgorithmicSpaceGroupGenerator which throws an std::runtime_error exception when the generatorInformation string cannot be interpreted as symmetry operations.
Definition at line 116 of file SpaceGroupFactory.cpp.
References Mantid::Geometry::isValidGeneratorString().
Member Function Documentation
generateGroup()
Group_const_sptr Mantid::Geometry::AlgorithmicSpaceGroupGenerator::generateGroup () const override protected virtual
Uses an algorithm based on Shmueli, U.
Acta Crystallogr. A 40, 559–567 (1984) to generate the group.
Implements Mantid::Geometry::AbstractSpaceGroupGenerator.
Definition at line 126 of file SpaceGroupFactory.cpp.
References getCenteringSymbol(), and Mantid::Geometry::AbstractSpaceGroupGenerator::getGeneratorString().
getCenteringSymbol()
std::string Mantid::Geometry::AlgorithmicSpaceGroupGenerator::getCenteringSymbol () const protected
Returns the centering symbol, which is extracted from the Hermann-Mauguin-symbol.
Definition at line 135 of file SpaceGroupFactory.cpp.
References Mantid::Geometry::AbstractSpaceGroupGenerator::getHMSymbol().
Referenced by generateGroup().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/SpaceGroupFactory.h
Framework/Geometry/src/Crystal/SpaceGroupFactory.cpp