Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/DateAndTime.cpp File Reference
DateAndTime.cpp File Reference
#include "MantidKernel/DateAndTime.h"
#include "MantidPythonInterface/core/Converters/DateAndTime.h"
#include <boost/python/class.hpp>
#include <boost/python/make_constructor.hpp>
#include <boost/python/operators.hpp>
#include <cstddef>
#include <memory>
#include <numpy/arrayobject.h>
#include <numpy/arrayscalars.h>
Functions
void export_DateAndTime ()
void export_time_duration ()
std::string ISO8601StringPlusSpace (const DateAndTime &self)
Circumvent a bug in IPython 1.1, which chokes on nanosecond precision datetimes.
int64_t time_duration_total_nanoseconds (time_duration &self)
int64_t total_nanoseconds (const DateAndTime &self)
Function Documentation
export_DateAndTime()
void export_DateAndTime ()
Definition at line 38 of file DateAndTime.cpp.
References ISO8601StringPlusSpace(), Mantid::PythonInterface::Converters::to_dateandtime(), Mantid::PythonInterface::Converters::to_datetime64(), and total_nanoseconds().
export_time_duration()
void export_time_duration ()
Definition at line 79 of file DateAndTime.cpp.
References time_duration_total_nanoseconds().
ISO8601StringPlusSpace()
std::string ISO8601StringPlusSpace (const DateAndTime & self)
Circumvent a bug in IPython 1.1, which chokes on nanosecond precision datetimes.
Adding a space to the string returned by the C++ method avoids it being given the special treatment that leads to the problem.
Definition at line 28 of file DateAndTime.cpp.
Referenced by export_DateAndTime().
time_duration_total_nanoseconds()
int64_t time_duration_total_nanoseconds (time_duration & self)
Definition at line 74 of file DateAndTime.cpp.
Referenced by export_time_duration().
total_nanoseconds()
int64_t total_nanoseconds (const DateAndTime & self)
Definition at line 33 of file DateAndTime.cpp.
Referenced by Mantid::Algorithms::AverageLogData::exec(), and export_DateAndTime().