Mantid: MantidQt::MantidWidgets::PythonHelpWindow Class Reference
MantidQt::MantidWidgets::PythonHelpWindow Class Reference
#include <PythonHelpWindow.h>
Public Member Functions
PythonHelpWindow ()
void showAlgorithm (const QString &name, const int version=-1) override
void showAlgorithm (const std::string &name=std::string(), const int version=-1) override
void showConcept (const QString &name) override
void showConcept (const std::string &name) override
void showCustomInterface (const QString &name, const QString &area=QString(), const QString &section=QString()) override
void showCustomInterface (const std::string &name=std::string(), const std::string &area=std::string(), const std::string &section=std::string()) override
void showFitFunction (const QString &name) override
void showFitFunction (const std::string &name=std::string()) override
void showPage (const QString &url) override
void showPage (const QUrl &url) override
void showPage (const std::string &url=std::string()) override
void shutdown () override
Perform any clean up on main window shutdown.
Public Member Functions inherited from MantidQt::API::MantidHelpInterface
MantidHelpInterface ()
Default constructor.
~MantidHelpInterface () override
Default destructor.
Additional Inherited Members
Public Slots inherited from MantidQt::API::MantidHelpInterface
Detailed Description
Definition at line 19 of file PythonHelpWindow.h.
Constructor & Destructor Documentation
PythonHelpWindow()
MantidQt::MantidWidgets::PythonHelpWindow::PythonHelpWindow ()
Definition at line 19 of file PythonHelpWindow.cpp.
Member Function Documentation
showAlgorithm() [1/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showAlgorithm (const QString & name, const int version = -1) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 49 of file PythonHelpWindow.cpp.
References n, name, and showAlgorithm().
showAlgorithm() [2/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showAlgorithm (const std::string & name = std::string(), const int version = -1) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 38 of file PythonHelpWindow.cpp.
References name, and showPage().
Referenced by showAlgorithm().
showConcept() [1/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showConcept (const QString & name) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 59 of file PythonHelpWindow.cpp.
References n, name, and showConcept().
showConcept() [2/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showConcept (const std::string & name) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 54 of file PythonHelpWindow.cpp.
References name, and showPage().
Referenced by showConcept().
showCustomInterface() [1/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showCustomInterface (const QString & name, const QString & area = QString(), const QString & section = QString()) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 84 of file PythonHelpWindow.cpp.
References n, name, and showCustomInterface().
showCustomInterface() [2/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showCustomInterface (const std::string & name = std::string(), const std::string & area = std::string(), const std::string & section = std::string()) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 75 of file PythonHelpWindow.cpp.
References name, and showPage().
Referenced by showCustomInterface().
showFitFunction() [1/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showFitFunction (const QString & name) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 70 of file PythonHelpWindow.cpp.
References n, name, and showFitFunction().
showFitFunction() [2/2]
void MantidQt::MantidWidgets::PythonHelpWindow::showFitFunction (const std::string & name = std::string()) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 64 of file PythonHelpWindow.cpp.
References name, and showPage().
Referenced by showFitFunction().
showPage() [1/3]
void MantidQt::MantidWidgets::PythonHelpWindow::showPage (const QString & url) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 26 of file PythonHelpWindow.cpp.
References MantidQt::MantidWidgets::PythonHelpBridge::showHelpPage().
showPage() [2/3]
void MantidQt::MantidWidgets::PythonHelpWindow::showPage (const QUrl & url) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 32 of file PythonHelpWindow.cpp.
References MantidQt::MantidWidgets::PythonHelpBridge::showHelpPage().
showPage() [3/3]
void MantidQt::MantidWidgets::PythonHelpWindow::showPage (const std::string & url = std::string()) override virtual
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 21 of file PythonHelpWindow.cpp.
References MantidQt::MantidWidgets::PythonHelpBridge::showHelpPage().
Referenced by showAlgorithm(), showConcept(), showCustomInterface(), and showFitFunction().
shutdown()
void MantidQt::MantidWidgets::PythonHelpWindow::shutdown () override virtual
Perform any clean up on main window shutdown.
Reimplemented from MantidQt::API::MantidHelpInterface.
Definition at line 91 of file PythonHelpWindow.cpp.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/PythonHelpWindow.h
qt/widgets/common/src/PythonHelpWindow.cpp