Mantid: Mantid::CurveFitting::FitMW Class Reference
Mantid::CurveFitting::FitMW Class Reference
Creates FunctionDomain1D form a spectrum in a MatrixWorkspace.
#include <FitMW.h>
Public Member Functions
void createDomain (std::shared_ptr< API::FunctionDomain > &domain, std::shared_ptr< API::FunctionValues > &values, size_t i0=0) override
Create a domain from the input workspace.
std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName) override
Create an output workspace.
void declareDatasetProperties (const std::string &suffix="", bool addProp=true) override
Declare properties that specify the dataset within the workspace to fit to.
FitMW (DomainType domainType=Simple)
Constructor.
FitMW (Kernel::IPropertyManager *fit, const std::string &workspacePropertyName, DomainType domainType=Simple)
Constructor.
void setMaxSize (size_t maxSize)
Set max size for Sequantial and Parallel domains.
void setNormalise (bool on)
Set the normalisation flag.
Public Member Functions inherited from Mantid::CurveFitting::IMWDomainCreator
std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName) override
Create an output workspace.
void declareDatasetProperties (const std::string &suffix="", bool addProp=true) override
Declare properties that specify the dataset within the workspace to fit to.
size_t getDomainSize () const override
Return the size of the domain to be created.
IMWDomainCreator (Kernel::IPropertyManager *fit, const std::string &workspacePropertyName, DomainType domainType=Simple)
Constructor.
void initFunction (API::IFunction_sptr function) override
Initialize the function.
void setRange (double startX, double endX)
Set the startX and endX.
void setWorkspace (std::shared_ptr< API::MatrixWorkspace > ws)
Set the workspace.
void setWorkspaceIndex (size_t wi)
Set the workspace index.
Public Member Functions inherited from Mantid::API::IDomainCreator
virtual void createDomain (std::shared_ptr< API::FunctionDomain > &domain, std::shared_ptr< API::FunctionValues > &values, size_t i0=0)=0
Create a domain and values from the input workspace.
virtual std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName="OutputWorkspace")
Create an output workspace filled with data simulated with the fitting function.
virtual void declareDatasetProperties (const std::string &suffix="", bool addProp=true)
Declare properties that specify the dataset within the workspace to fit to.
virtual size_t getDomainSize () const =0
Return the size of the domain to be created.
IDomainCreator (Kernel::IPropertyManager *manager, std::vector< std::string > workspacePropertyNames, DomainType domainType=Simple)
Constrcutor.
void ignoreInvalidData (bool yes)
Set to ignore invalid data.
virtual void initFunction (API::IFunction_sptr function)
Initialize the function.
virtual void initialize (Kernel::IPropertyManager *, const std::string &, DomainType)
Initialize.
void separateCompositeMembersInOutput (const bool value, const bool conv=false)
Toggle output of either just composite or composite + members.
virtual ~IDomainCreator ()=default
Virtual destructor.
Protected Member Functions
void setParameters () const override
Set all parameters.
Protected Member Functions inherited from Mantid::CurveFitting::IMWDomainCreator
void addFunctionValuesToWS (const API::IFunction_sptr &function, std::shared_ptr< API::MatrixWorkspace > &ws, const size_t wsIndex, const std::shared_ptr< API::FunctionDomain > &domain, const std::shared_ptr< API::FunctionValues > &resultValues) const
Add the calculated function values to the workspace.
void appendCompositeFunctionMembers (std::list< API::IFunction_sptr > &functionList, const API::IFunction_sptr &function) const
void appendConvolvedCompositeFunctionMembers (std::list< API::IFunction_sptr > &functionList, const API::IFunction_sptr &function) const
If the fit function is Convolution and flag m_convolutionCompositeMembers is set and Convolution's second function (the model) is composite then use members of the model for the output.
std::shared_ptr< API::MatrixWorkspace > createEmptyResultWS (const size_t nhistograms, const size_t nyvalues)
Creates the blank output workspace of the correct size.
std::pair< size_t, size_t > getXInterval () const
Calculate size and starting iterator in the X array.
void setInitialValues (API::IFunction &function)
Set initial values for parameters with default values.
virtual void setParameters () const
Set all parameters.
Protected Member Functions inherited from Mantid::API::IDomainCreator
void declareProperty (Kernel::Property *prop, const std::string &doc)
Declare a property to the algorithm.
Private Attributes
std::vector< double > m_exclude
Ranges that must be excluded from fit.
std::string m_excludePropertyName
Store the Exclude property name.
size_t m_maxSize
Max size for seq domain.
std::string m_maxSizePropertyName
Store maxSize property name.
bool m_normalise
Option to normalise the data.
std::string m_normalisePropertyName
Store Normalise property name.
Additional Inherited Members
Public Types inherited from Mantid::API::IDomainCreator
enum DomainType { Simple = 0 , Sequential , Parallel }
Type of domain to create.
Protected Attributes inherited from Mantid::CurveFitting::IMWDomainCreator
std::weak_ptr< API::FunctionDomain1D > m_domain
Store the created domain and values.
double m_endX
endX
std::string m_endXPropertyName
Store endX property name.
std::shared_ptr< API::MatrixWorkspace > m_matrixWorkspace
The input MareixWorkspace.
size_t m_startIndex
double m_startX
startX
std::string m_startXPropertyName
Store startX property name.
std::weak_ptr< API::FunctionValues > m_values
size_t m_workspaceIndex
The workspace index.
std::string m_workspaceIndexPropertyName
Store workspace index property name.
std::string m_workspacePropertyName
Store workspace property name.
Protected Attributes inherited from Mantid::API::IDomainCreator
bool m_convolutionCompositeMembers
Perform convolution of output composite components.
DomainType m_domainType
Domain type.
bool m_ignoreInvalidData
Flag to ignore nans, infinities and zero errors.
Kernel::IPropertyManager * m_manager
Pointer to a property manager.
bool m_outputCompositeMembers
Output separate composite function values.
std::vector< std::string > m_workspacePropertyNames
Property names for workspaces to get the data from.
Detailed Description
Creates FunctionDomain1D form a spectrum in a MatrixWorkspace.
Declares WorkspaceIndex, StartX, and EndX input properties. Declares OutputWorkspace output property.
Author
Roman Tolchenov, Tessella plc
Date
06/12/2011
Definition at line 38 of file FitMW.h.
Constructor & Destructor Documentation
FitMW() [1/2]
Mantid::CurveFitting::FitMW::FitMW (Kernel::IPropertyManager * fit, const std::string & workspacePropertyName, FitMW::DomainType domainType = Simple)
Constructor.
Parameters
fit :: Property manager with properties defining the domain to be created
workspacePropertyName :: Name of the workspace property.
domainType :: Type of the domain: Simple, Sequential, or Parallel.
Definition at line 123 of file FitMW.cpp.
FitMW() [2/2]
Mantid::CurveFitting::FitMW::FitMW (FitMW::DomainType domainType = Simple)
Constructor.
Methods setWorkspace, setWorkspaceIndex and setRange must be called set up the creator.
Parameters
domainType :: Type of the domain: Simple, Sequential, or Parallel.
Definition at line 132 of file FitMW.cpp.
Member Function Documentation
createDomain()
void Mantid::CurveFitting::FitMW::createDomain (std::shared_ptr< API::FunctionDomain > & domain, std::shared_ptr< API::FunctionValues > & values, size_t i0 = 0) override virtual
Create a domain from the input workspace.
Implements Mantid::API::IDomainCreator.
Definition at line 194 of file FitMW.cpp.
References Mantid::CurveFitting::SeqDomain::addCreator(), Mantid::CurveFitting::SeqDomain::create(), error, Mantid::CurveFitting::IMWDomainCreator::getXInterval(), Mantid::CurveFitting::ExcludeRangeFinder::isExcluded(), Mantid::Geometry::m, Mantid::CurveFitting::IMWDomainCreator::m_domain, Mantid::API::IDomainCreator::m_domainType, m_exclude, Mantid::API::IDomainCreator::m_ignoreInvalidData, Mantid::CurveFitting::IMWDomainCreator::m_matrixWorkspace, m_maxSize, m_normalise, Mantid::CurveFitting::IMWDomainCreator::m_startIndex, Mantid::CurveFitting::IMWDomainCreator::m_values, Mantid::CurveFitting::IMWDomainCreator::m_workspaceIndex, n, setParameters(), Mantid::CurveFitting::IMWDomainCreator::setWorkspace(), Mantid::API::IDomainCreator::Simple, Mantid::Geometry::X, Mantid::Geometry::x, Mantid::Geometry::Y, and Mantid::Geometry::y.
createOutputWorkspace()
std::shared_ptr< API::Workspace > Mantid::CurveFitting::FitMW::createOutputWorkspace (const std::string & baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string & outputWorkspacePropertyName) override virtual
Create an output workspace.
Create an output workspace with the calculated values.
Parameters
baseName :: Specifies the name of the output workspace
function :: A Pointer to the fitting function
domain :: The domain containing x-values for the function
values :: A API::FunctionValues instance containing the fitting data
outputWorkspacePropertyName :: The property name
Reimplemented from Mantid::API::IDomainCreator.
Definition at line 315 of file FitMW.cpp.
References Mantid::CurveFitting::IMWDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::IMWDomainCreator::m_matrixWorkspace, m_normalise, Mantid::Geometry::X, and Mantid::Geometry::Y.
declareDatasetProperties()
void Mantid::CurveFitting::FitMW::declareDatasetProperties (const std::string & suffix = "", bool addProp = true) override virtual
Declare properties that specify the dataset within the workspace to fit to.
Parameters
suffix :: names the dataset
addProp :: allows for the declaration of certain properties of the dataset
Reimplemented from Mantid::API::IDomainCreator.
Definition at line 166 of file FitMW.cpp.
References Mantid::CurveFitting::IMWDomainCreator::declareDatasetProperties(), Mantid::API::IDomainCreator::declareProperty(), Mantid::Kernel::IPropertyManager::existsProperty(), Mantid::API::IDomainCreator::m_domainType, m_excludePropertyName, Mantid::API::IDomainCreator::m_manager, m_maxSizePropertyName, m_normalisePropertyName, and Mantid::API::IDomainCreator::Simple.
setMaxSize()
void Mantid::CurveFitting::FitMW::setMaxSize (size_t maxSize) inline
Set max size for Sequantial and Parallel domains.
Parameters
maxSize :: Maximum size of each simple domain
Definition at line 57 of file FitMW.h.
setNormalise()
void Mantid::CurveFitting::FitMW::setNormalise (bool on) inline
Set the normalisation flag.
Parameters
on :: If true and the spectrum is a histogram the fitting data will be normalised by the bin width.
Definition at line 62 of file FitMW.h.
setParameters()
void Mantid::CurveFitting::FitMW::setParameters () const override protected virtual
Set all parameters.
Exceptions
std::runtime_error if the Exclude property has an odd number of entries.
Reimplemented from Mantid::CurveFitting::IMWDomainCreator.
Definition at line 140 of file FitMW.cpp.
References Mantid::Kernel::IPropertyManager::getProperty(), Mantid::API::IDomainCreator::m_domainType, m_exclude, m_excludePropertyName, Mantid::API::IDomainCreator::m_manager, m_maxSize, m_maxSizePropertyName, m_normalise, m_normalisePropertyName, Mantid::CurveFitting::IMWDomainCreator::setParameters(), and Mantid::API::IDomainCreator::Simple.
Referenced by createDomain().
Member Data Documentation
m_exclude
std::vector<double> Mantid::CurveFitting::FitMW::m_exclude mutable private
Ranges that must be excluded from fit.
Definition at line 81 of file FitMW.h.
Referenced by createDomain(), and setParameters().
m_excludePropertyName
std::string Mantid::CurveFitting::FitMW::m_excludePropertyName private
Store the Exclude property name.
Definition at line 74 of file FitMW.h.
Referenced by declareDatasetProperties(), and setParameters().
m_maxSize
size_t Mantid::CurveFitting::FitMW::m_maxSize mutable private
Max size for seq domain.
Definition at line 77 of file FitMW.h.
Referenced by createDomain(), and setParameters().
m_maxSizePropertyName
std::string Mantid::CurveFitting::FitMW::m_maxSizePropertyName private
Store maxSize property name.
Definition at line 70 of file FitMW.h.
Referenced by declareDatasetProperties(), and setParameters().
m_normalise
bool Mantid::CurveFitting::FitMW::m_normalise mutable private
Option to normalise the data.
Definition at line 79 of file FitMW.h.
Referenced by createDomain(), createOutputWorkspace(), and setParameters().
m_normalisePropertyName
std::string Mantid::CurveFitting::FitMW::m_normalisePropertyName private
Store Normalise property name.
Definition at line 72 of file FitMW.h.
Referenced by declareDatasetProperties(), and setParameters().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/FitMW.h
Framework/CurveFitting/src/FitMW.cpp