Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/Logger.cpp File Reference
Logger.cpp File Reference
#include "MantidKernel/Logger.h"
#include "MantidPythonInterface/core/ReleaseGlobalInterpreterLock.h"
#include <boost/python/class.hpp>
#include <boost/python/make_constructor.hpp>
#include <boost/python/reference_existing_object.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <memory>
Typedefs
using LoggerFlushFunction = void(Logger::*)()
using LoggerMsgFunction = void(Logger::*)(const std::string &)
Functions
void export_Logger ()
Typedef Documentation
LoggerFlushFunction
using LoggerFlushFunction = void (Logger::*)()
Definition at line 19 of file Logger.cpp.
LoggerMsgFunction
using LoggerMsgFunction = void (Logger::*)(const std::string &)
Definition at line 18 of file Logger.cpp.
Function Documentation
export_Logger()
void export_Logger ()
Definition at line 67 of file Logger.cpp.
References Mantid::Kernel::Logger::accumulate(), error, Mantid::Kernel::Logger::flush(), Mantid::Kernel::Logger::flushDebug(), Mantid::Kernel::Logger::flushError(), Mantid::Kernel::Logger::flushFatal(), Mantid::Kernel::Logger::flushInformation(), Mantid::Kernel::Logger::flushNotice(), Mantid::Kernel::Logger::flushWarning(), and Mantid::Kernel::Logger::purge().