Mantid: Mantid::Crystal::SCDCalibratePanels2 Class Reference
Mantid::Crystal::SCDCalibratePanels2 Class Reference
SCDCalibratePanels2 : Using input peakworkspace with indexation results to calibrate each individual panels.
#include <SCDCalibratePanels2.h>
Public Member Functions
const std::string category () const override
Algorithm's category, overriding a virtual method.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Extra help info.
const std::string summary () const override
Summary of algorithm's purpose.
int version () const override
Algorithm's version, overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Member Functions
void adjustComponent (double dx, double dy, double dz, double drx, double dry, double drz, double scalex, double scaley, const std::string &cmptName, Mantid::API::IPeaksWorkspace_sptr &pws)
Helper functions for adjusting components.
std::vector< double > captureTOF (const Mantid::API::IPeaksWorkspace_sptr &pws)
Cache TOF equivalent to those measured from experiment.
void exec () override
Overwrites Algorithm method.
Mantid::API::ITableWorkspace_sptr generateCalibrationTable (std::shared_ptr< Geometry::Instrument > &instrument, const Geometry::ParameterMap &pmap)
Generate a Table workspace to store the calibration results.
void getBankNames (const Mantid::API::IPeaksWorkspace_sptr &pws)
Private function for getting names of banks to be calibrated.
Mantid::API::MatrixWorkspace_sptr getIdealQSampleAsHistogram1D (const Mantid::API::IPeaksWorkspace_sptr &pws)
Helper function that calculates the ideal qSample based on integer HKL.
std::pair< double, double > getRectangularDetectorScaleFactors (std::shared_ptr< Geometry::Instrument > &instrument, const std::string &bankname, const Geometry::ParameterMap &pmap)
Retrieve "scalex" and "scaley" from a workspace's parameter map if the component is rectangular detector.
void init () override
Overwrites Algorithm method. Does nothing at present.
void optimizeBanks (Mantid::API::IPeaksWorkspace_sptr pws, const Mantid::API::IPeaksWorkspace_sptr &pws_original, const bool &docalibsize, const double &sizesearchradius, const bool &fixdetxyratio)
Private function for calibrating banks.
void optimizeL1 (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Private function for calibrating L1.
void optimizeSamplePos (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Private function for fine tunning sample position.
void optimizeT0 (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Private function for calibrating T0.
void parseLatticeConstant (const Mantid::API::IPeaksWorkspace_sptr &pws)
Private function dedicated for parsing lattice constant.
void profileBanks (Mantid::API::IPeaksWorkspace_sptr &pws, const Mantid::API::IPeaksWorkspace_sptr &pws_original)
Profiling obj func along six degree of freedom, which can be very slow.
void profileL1 (Mantid::API::IPeaksWorkspace_sptr &pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Profile related functions.
void profileL1T0 (Mantid::API::IPeaksWorkspace_sptr &pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Profile obj func along L1 and T0 axis.
void profileT0 (Mantid::API::IPeaksWorkspace_sptr &pws, Mantid::API::IPeaksWorkspace_sptr pws_original)
Profile obj func along T0 axis.
Mantid::API::IPeaksWorkspace_sptr removeUnindexedPeaks (const Mantid::API::IPeaksWorkspace_sptr &pws)
Remove unindexed peaks from workspace.
void saveCalibrationTable (const std::string &FileName, Mantid::API::ITableWorkspace_sptr &tws)
Save the calibration table to a CSV file.
void saveIsawDetCal (const std::string &filename, boost::container::flat_set< std::string > &AllBankName, std::shared_ptr< Geometry::Instrument > &instrument, double T0)
Save to ISAW type det calibration output for backward compatiblity.
void saveXmlFile (const std::string &FileName, const boost::container::flat_set< std::string > &AllBankNames, std::shared_ptr< Geometry::Instrument > &instrument, const Geometry::ParameterMap &pmap)
Save to xml file for Mantid to load by manual crafting.
Mantid::API::IPeaksWorkspace_sptr selectPeaksByBankName (const Mantid::API::IPeaksWorkspace_sptr &pws, const std::string &bankname, const std::string &outputwsn)
Helper function for selecting peaks based on given bank name.
void updateUBMatrix (const Mantid::API::IPeaksWorkspace_sptr &pws)
Update the UB matrix.
std::map< std::string, std::string > validateInputs () override
Private validator for inputs.
Private Attributes
const std::vector< std::string > calibrationTableColumnNames
const std::vector< std::string > calibrationTableColumnTypes
bool LOGCHILDALG {true}
double m_a
unique vars for a given instance of calibration
double m_alpha
double m_b
boost::container::flat_set< std::string > m_BankNames
double m_beta
double m_c
double m_gamma
double m_T0 = 0.0
int maxFitIterations {500}
std::string mCalibBankName {""}
Mantid::API::ITableWorkspace_sptr mCaliTable
const int MINIMUM_PEAKS_PER_BANK {6}
const double PI {3.1415926535897932384626433832795028841971693993751058209}
Static Private Attributes
static constexpr double Tolerance = std::numeric_limits<double>::epsilon()
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
SCDCalibratePanels2 : Using input peakworkspace with indexation results to calibrate each individual panels.
The target calibration properties include:
T0: micro seconds time for proton to travel from reactor to target to generate neutron
L1: meters distance between target and sample
L2: meters (also known as z_shift) distance between sample and the center of each panel
Rot: degrees Euler angles (xyz)
Spirit successor of ISAW and its reincarnation: SCDCalibratePanels
Definition at line 36 of file SCDCalibratePanels2.h.
Member Function Documentation
adjustComponent()
void Mantid::Crystal::SCDCalibratePanels2::adjustComponent (double dx, double dy, double dz, double drx, double dry, double drz, double scalex, double scaley, const std::string & cmptName, Mantid::API::IPeaksWorkspace_sptr & pws) private
Helper functions for adjusting components.
Definition at line 1050 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, LOGCHILDALG, and Mantid::Kernel::Logger::notice().
Referenced by optimizeBanks(), optimizeL1(), and optimizeSamplePos().
captureTOF()
std::vector< double > Mantid::Crystal::SCDCalibratePanels2::captureTOF (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Cache TOF equivalent to those measured from experiment.
Capture TOFs that are equivalent to thoes measured from experiment.
This step should be carried out after the indexation (if required)
Parameters
pws
Definition at line 925 of file SCDCalibratePanels2.cpp.
Referenced by optimizeBanks(), optimizeL1(), optimizeSamplePos(), optimizeT0(), profileBanks(), profileL1(), profileL1T0(), and profileT0().
category()
const std::string Mantid::Crystal::SCDCalibratePanels2::category () const inline override virtual
Algorithm's category, overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 52 of file SCDCalibratePanels2.h.
exec()
void Mantid::Crystal::SCDCalibratePanels2::exec () override private virtual
Overwrites Algorithm method.
execute calibration
Implements Mantid::API::Algorithm.
Definition at line 275 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::g_log, generateCalibrationTable(), getBankNames(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), LOGCHILDALG, m_BankNames, m_T0, maxFitIterations, mCalibBankName, Mantid::Kernel::Logger::notice(), optimizeBanks(), optimizeL1(), optimizeSamplePos(), optimizeT0(), parseLatticeConstant(), profileBanks(), profileL1(), profileL1T0(), profileT0(), removeUnindexedPeaks(), saveCalibrationTable(), saveIsawDetCal(), saveXmlFile(), Mantid::Kernel::IPropertyManager::setProperty(), updateUBMatrix(), and Mantid::Kernel::Logger::warning().
generateCalibrationTable()
ITableWorkspace_sptr Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable (std::shared_ptr< Geometry::Instrument > & instrument, const Geometry::ParameterMap & pmap) private
Generate a Table workspace to store the calibration results.
Definition at line 1116 of file SCDCalibratePanels2.cpp.
References calibrationTableColumnNames, calibrationTableColumnTypes, Mantid::API::Algorithm::g_log, Mantid::Kernel::Quat::getAngleAxis(), getRectangularDetectorScaleFactors(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_BankNames, Mantid::Kernel::Logger::notice(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by exec().
getBankNames()
void Mantid::Crystal::SCDCalibratePanels2::getBankNames (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Private function for getting names of banks to be calibrated.
Gather names for bank for calibration.
Parameters
pws
Definition at line 940 of file SCDCalibratePanels2.cpp.
References m_BankNames.
Referenced by exec().
getIdealQSampleAsHistogram1D()
MatrixWorkspace_sptr Mantid::Crystal::SCDCalibratePanels2::getIdealQSampleAsHistogram1D (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Helper function that calculates the ideal qSample based on integer HKL.
Return a 1D histogram consists of ideal qSample calculated from integer HKL directly.
Parameters
pws
Returns
MatrixWorkspace_sptr
Definition at line 982 of file SCDCalibratePanels2.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), and PI.
Referenced by optimizeBanks(), optimizeL1(), optimizeSamplePos(), optimizeT0(), and profileBanks().
getRectangularDetectorScaleFactors()
std::pair< double, double > Mantid::Crystal::SCDCalibratePanels2::getRectangularDetectorScaleFactors (std::shared_ptr< Geometry::Instrument > & instrument, const std::string & bankname, const Geometry::ParameterMap & pmap) private
Retrieve "scalex" and "scaley" from a workspace's parameter map if the component is rectangular detector.
The default cases for the return value includes
the bank is not a rectagular detector OR
the component does not have "scalex" and "scaley" in parameter map
Parameters
instrument :: Instrument geometry
bankname :: bank name (component name)
pmap :: parameter map from the same workspace where instrument is belonged to
Returns
:: pair as scalex and scaley. Default is (1., 1.)
Definition at line 1773 of file SCDCalibratePanels2.cpp.
Referenced by generateCalibrationTable(), optimizeBanks(), and saveXmlFile().
init()
void Mantid::Crystal::SCDCalibratePanels2::init () override private virtual
Overwrites Algorithm method. Does nothing at present.
Initialization.
Implements Mantid::API::Algorithm.
Definition at line 57 of file SCDCalibratePanels2.cpp.
References Mantid::EMPTY_DBL(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_DEFAULT, Mantid::Kernel::IS_EQUAL_TO, Mantid::API::FileProperty::OptionalSave, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::Crystal::SCDCalibratePanels2::name () const inline override virtual
Algorithm's name for identification.
Implements Mantid::API::Algorithm.
Definition at line 39 of file SCDCalibratePanels2.h.
optimizeBanks()
void Mantid::Crystal::SCDCalibratePanels2::optimizeBanks (Mantid::API::IPeaksWorkspace_sptr pws, const Mantid::API::IPeaksWorkspace_sptr & pws_original, const bool & docalibsize, const double & sizesearchradius, const bool & fixdetxyratio) private
Private function for calibrating banks.
Calibrate the position and rotation of each Bank, one at a time.
Parameters
pws
pws_original
docalibsize :: flag to calibrate rectangular detector size
sizesearchradius :: searching radius for detector size calibration
fixdetxyratio,: flag to tie the rectangular detector
Definition at line 525 of file SCDCalibratePanels2.cpp.
References adjustComponent(), captureTOF(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, getIdealQSampleAsHistogram1D(), Mantid::API::Algorithm::getProperty(), getRectangularDetectorScaleFactors(), Mantid::Kernel::Logger::information(), m_BankNames, m_T0, maxFitIterations, mCalibBankName, MINIMUM_PEAKS_PER_BANK, Mantid::Kernel::Logger::notice(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, selectPeaksByBankName(), Mantid::Kernel::threadSafe(), and Tolerance.
Referenced by exec().
optimizeL1()
void Mantid::Crystal::SCDCalibratePanels2::optimizeL1 (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Private function for calibrating L1.
----------------------------------------— /// Core functions for Calibration&Optimizatoin /// ----------------------------------------— ///
Parameters
pws
pws_original
Definition at line 429 of file SCDCalibratePanels2.cpp.
References adjustComponent(), captureTOF(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, getIdealQSampleAsHistogram1D(), Mantid::API::Algorithm::getProperty(), m_T0, and Mantid::Kernel::Logger::notice().
Referenced by exec().
optimizeSamplePos()
void Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Private function for fine tunning sample position.
fine tuning sample position to better match QSample
Parameters
pws
pws_original
Definition at line 790 of file SCDCalibratePanels2.cpp.
References adjustComponent(), captureTOF(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, getIdealQSampleAsHistogram1D(), Mantid::API::Algorithm::getProperty(), m_T0, and Mantid::Kernel::Logger::notice().
Referenced by exec().
optimizeT0()
void Mantid::Crystal::SCDCalibratePanels2::optimizeT0 (Mantid::API::IPeaksWorkspace_sptr pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Private function for calibrating T0.
adjusting the deltaT0 to match the qSample_calculated and qSameple_measured
Note
this function currently only returns dT0=0, and the reason is still unkown.
Parameters
pws
pws_original
Definition at line 728 of file SCDCalibratePanels2.cpp.
References captureTOF(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, getIdealQSampleAsHistogram1D(), Mantid::API::Algorithm::getProperty(), m_T0, and Mantid::Kernel::Logger::notice().
Referenced by exec().
parseLatticeConstant()
void Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Private function dedicated for parsing lattice constant.
-------------— /// helper functions /// -------------— ///
get lattice constants from either inputs or the input peak workspace
Definition at line 850 of file SCDCalibratePanels2.cpp.
References Mantid::Geometry::UnitCell::a(), Mantid::Geometry::UnitCell::alpha(), Mantid::Geometry::UnitCell::b(), Mantid::Geometry::UnitCell::beta(), Mantid::Geometry::UnitCell::c(), Mantid::EMPTY_DBL(), Mantid::Geometry::UnitCell::gamma(), Mantid::API::Algorithm::getProperty(), m_a, m_alpha, m_b, m_beta, m_c, and m_gamma.
Referenced by exec().
profileBanks()
void Mantid::Crystal::SCDCalibratePanels2::profileBanks (Mantid::API::IPeaksWorkspace_sptr & pws, const Mantid::API::IPeaksWorkspace_sptr & pws_original) private
Profiling obj func along six degree of freedom, which can be very slow.
Parameters
pws
pws_original
Definition at line 1480 of file SCDCalibratePanels2.cpp.
References captureTOF(), Mantid::API::Algorithm::g_log, getIdealQSampleAsHistogram1D(), Mantid::API::Algorithm::getProperty(), m_BankNames, MINIMUM_PEAKS_PER_BANK, Mantid::Kernel::Logger::notice(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, PI, selectPeaksByBankName(), and Mantid::Kernel::threadSafe().
Referenced by exec().
profileL1()
void Mantid::Crystal::SCDCalibratePanels2::profileL1 (Mantid::API::IPeaksWorkspace_sptr & pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Profile related functions.
Profile obj func along L1 axis.
Parameters
pws
pws_original
Definition at line 1398 of file SCDCalibratePanels2.cpp.
References captureTOF(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::notice(), and PI.
Referenced by exec().
profileL1T0()
void Mantid::Crystal::SCDCalibratePanels2::profileL1T0 (Mantid::API::IPeaksWorkspace_sptr & pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Profile obj func along L1 and T0 axis.
Parameters
pws
pws_original
Definition at line 1687 of file SCDCalibratePanels2.cpp.
References captureTOF(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::notice(), and PI.
Referenced by exec().
profileT0()
void Mantid::Crystal::SCDCalibratePanels2::profileT0 (Mantid::API::IPeaksWorkspace_sptr & pws, Mantid::API::IPeaksWorkspace_sptr pws_original) private
Profile obj func along T0 axis.
Parameters
pws
pws_original
Definition at line 1609 of file SCDCalibratePanels2.cpp.
References captureTOF(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::notice(), and PI.
Referenced by exec().
removeUnindexedPeaks()
IPeaksWorkspace_sptr Mantid::Crystal::SCDCalibratePanels2::removeUnindexedPeaks (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Remove unindexed peaks from workspace.
Parameters
pws
Returns
IPeaksWorkspace_sptr
Definition at line 905 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), and LOGCHILDALG.
Referenced by exec().
saveCalibrationTable()
void Mantid::Crystal::SCDCalibratePanels2::saveCalibrationTable (const std::string & FileName, Mantid::API::ITableWorkspace_sptr & tws) private
Save the calibration table to a CSV file.
Save the CORELLI calibration table into a CSV file.
Parameters
FileName
tws
Definition at line 1381 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm().
Referenced by exec().
saveIsawDetCal()
void Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal (const std::string & filename, boost::container::flat_set< std::string > & AllBankName, std::shared_ptr< Geometry::Instrument > & instrument, double T0) private
Save to ISAW type det calibration output for backward compatiblity.
Really this is the operator SaveIsawDetCal but only the results of the given banks are saved.
L1 and T0 are also saved.
Parameters
filename -The name of the DetCal file to save the results to
AllBankName -the set of the NewInstrument names of the banks(panels)
instrument -The instrument with the correct panel geometries and initial path length
T0 -The time offset from the DetCal file
Definition at line 1344 of file SCDCalibratePanels2.cpp.
References Mantid::DataObjects::create(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Kernel::Logger::notice(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
saveXmlFile()
void Mantid::Crystal::SCDCalibratePanels2::saveXmlFile (const std::string & FileName, const boost::container::flat_set< std::string > & AllBankNames, std::shared_ptr< Geometry::Instrument > & instrument, const Geometry::ParameterMap & pmap) private
Save to xml file for Mantid to load by manual crafting.
Saves the new instrument to an xml file that can be used with the LoadParameterFile Algorithm.
If the filename is empty, nothing gets done.
Parameters
FileName The filename to save this information to
AllBankNames The names of the banks in each group whose values are to be saved to the file
instrument The instrument with the new values for the banks in Groups
pmap :: parameter map from workspace
Definition at line 1182 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Quat::getEulerAngles(), getRectangularDetectorScaleFactors(), m_T0, Mantid::Kernel::Logger::notice(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::Crystal::SCDCalibratePanels2::seeAlso () const inline override virtual
Extra help info.
Reimplemented from Mantid::API::Algorithm.
Definition at line 55 of file SCDCalibratePanels2.h.
selectPeaksByBankName()
IPeaksWorkspace_sptr Mantid::Crystal::SCDCalibratePanels2::selectPeaksByBankName (const Mantid::API::IPeaksWorkspace_sptr & pws, const std::string & bankname, const std::string & outputwsn) private
Helper function for selecting peaks based on given bank name.
Select peaks with give bankname.
Parameters
pws
bankname
outputwsn
Returns
DataObjects::PeaksWorkspace_sptr
Definition at line 960 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), and LOGCHILDALG.
Referenced by optimizeBanks(), and profileBanks().
summary()
const std::string Mantid::Crystal::SCDCalibratePanels2::summary () const inline override virtual
Summary of algorithm's purpose.
Implements Mantid::API::Algorithm.
Definition at line 42 of file SCDCalibratePanels2.h.
updateUBMatrix()
void Mantid::Crystal::SCDCalibratePanels2::updateUBMatrix (const Mantid::API::IPeaksWorkspace_sptr & pws) private
Update the UB matrix.
update UB matrix embeded in the peakworkspace using lattice constants and redo the peak indexation afterwards
Parameters
pws
Definition at line 878 of file SCDCalibratePanels2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), LOGCHILDALG, m_a, m_alpha, m_b, m_beta, m_c, and m_gamma.
Referenced by exec().
validateInputs()
std::map< std::string, std::string > Mantid::Crystal::SCDCalibratePanels2::validateInputs (void) override private virtual
Private validator for inputs.
validate inputs
Returns
std::map<std::string, std::string>
Reimplemented from Mantid::API::Algorithm.
Definition at line 245 of file SCDCalibratePanels2.cpp.
References calibrationTableColumnNames, calibrationTableColumnTypes, Mantid::EMPTY_DBL(), and Mantid::API::Algorithm::getProperty().
version()
int Mantid::Crystal::SCDCalibratePanels2::version () const inline override virtual
Algorithm's version, overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 49 of file SCDCalibratePanels2.h.
Member Data Documentation
calibrationTableColumnNames
const std::vector<std::string> Mantid::Crystal::SCDCalibratePanels2::calibrationTableColumnNames private
Initial value:
{
      "ComponentName",    "Xposition",        "Yposition",     "Zposition", "XdirectionCosine",
      "YdirectionCosine", "ZdirectionCosine", "RotationAngle", "ScaleX",    "ScaleY"}
Definition at line 144 of file SCDCalibratePanels2.h.
Referenced by generateCalibrationTable(), and validateInputs().
calibrationTableColumnTypes
const std::vector<std::string> Mantid::Crystal::SCDCalibratePanels2::calibrationTableColumnTypes private
Initial value:
{"str",    "double", "double", "double", "double",
                                                             "double", "double", "double", "double", "double"}
Definition at line 147 of file SCDCalibratePanels2.h.
Referenced by generateCalibrationTable(), and validateInputs().
LOGCHILDALG
bool Mantid::Crystal::SCDCalibratePanels2::LOGCHILDALG {true} private
Definition at line 136 of file SCDCalibratePanels2.h.
Referenced by adjustComponent(), exec(), removeUnindexedPeaks(), selectPeaksByBankName(), and updateUBMatrix().
m_a
double Mantid::Crystal::SCDCalibratePanels2::m_a private
unique vars for a given instance of calibration
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_alpha
double Mantid::Crystal::SCDCalibratePanels2::m_alpha private
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_b
double Mantid::Crystal::SCDCalibratePanels2::m_b private
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_BankNames
boost::container::flat_set<std::string> Mantid::Crystal::SCDCalibratePanels2::m_BankNames private
Definition at line 150 of file SCDCalibratePanels2.h.
Referenced by exec(), generateCalibrationTable(), getBankNames(), optimizeBanks(), and profileBanks().
m_beta
double Mantid::Crystal::SCDCalibratePanels2::m_beta private
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_c
double Mantid::Crystal::SCDCalibratePanels2::m_c private
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_gamma
double Mantid::Crystal::SCDCalibratePanels2::m_gamma private
Definition at line 134 of file SCDCalibratePanels2.h.
Referenced by parseLatticeConstant(), and updateUBMatrix().
m_T0
double Mantid::Crystal::SCDCalibratePanels2::m_T0 = 0.0 private
Definition at line 135 of file SCDCalibratePanels2.h.
Referenced by exec(), optimizeBanks(), optimizeL1(), optimizeSamplePos(), optimizeT0(), and saveXmlFile().
maxFitIterations
int Mantid::Crystal::SCDCalibratePanels2::maxFitIterations {500} private
Definition at line 137 of file SCDCalibratePanels2.h.
Referenced by exec(), and optimizeBanks().
mCalibBankName
std::string Mantid::Crystal::SCDCalibratePanels2::mCalibBankName {""} private
Definition at line 139 of file SCDCalibratePanels2.h.
Referenced by exec(), and optimizeBanks().
mCaliTable
Mantid::API::ITableWorkspace_sptr Mantid::Crystal::SCDCalibratePanels2::mCaliTable private
Definition at line 151 of file SCDCalibratePanels2.h.
MINIMUM_PEAKS_PER_BANK
const int Mantid::Crystal::SCDCalibratePanels2::MINIMUM_PEAKS_PER_BANK {6} private
Definition at line 138 of file SCDCalibratePanels2.h.
Referenced by optimizeBanks(), and profileBanks().
PI
const double Mantid::Crystal::SCDCalibratePanels2::PI {3.1415926535897932384626433832795028841971693993751058209} private
Definition at line 140 of file SCDCalibratePanels2.h.
Referenced by getIdealQSampleAsHistogram1D(), profileBanks(), profileL1(), profileL1T0(), and profileT0().
Tolerance
constexpr double Mantid::Crystal::SCDCalibratePanels2::Tolerance = std::numeric_limits<double>::epsilon() static constexpr private
Definition at line 141 of file SCDCalibratePanels2.h.
Referenced by optimizeBanks().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/SCDCalibratePanels2.h
Framework/Crystal/src/SCDCalibratePanels2.cpp