Mantid: Mantid::DataHandling::PLN::EventCounter Class Reference
Mantid::DataHandling::PLN::EventCounter Class Reference
Public Member Functions
EventCounter (const std::vector< bool > &roi, const std::vector< size_t > &mapIndex, const double framePeriod, const double gatePeriod, const TimeLimits &timeBoundary, std::vector< size_t > &eventCounts, const double L1, const double V0, const std::vector< double > &vecL2, size_t maxEvents)
double tofCorrection ()
Public Member Functions inherited from Mantid::DataHandling::PLN::EventProcessor
void addEvent (size_t x, size_t p, double tof, double)
size_t availableEvents () const
double duration () const
EventProcessor (const std::vector< bool > &roi, const std::vector< size_t > &mapIndex, const double framePeriod, const double gatePeriod, const TimeLimits &timeBoundary, size_t maxEvents)
int64_t frameStart () const
void newFrame ()
size_t numFrames () const
size_t processedEvents () const
bool validFrame () const
Protected Member Functions
void addEventImpl (size_t id, size_t, size_t, double tobs) override
Protected Attributes
std::vector< size_t > & m_eventCounts
SimpleHist m_histogram
double m_L1
const std::vector< double > & m_L2
double m_V0
Protected Attributes inherited from Mantid::DataHandling::PLN::EventProcessor
size_t m_droppedEvents
const double m_framePeriod
size_t m_frames
size_t m_framesValid
const double m_gatePeriod
const std::vector< size_t > & m_mapIndex
size_t m_maxEvents
size_t m_processedEvents
const std::vector< bool > & m_roi
const TimeLimits m_timeBoundary
Detailed Description
Definition at line 344 of file LoadPLN.cpp.
Constructor & Destructor Documentation
EventCounter()
Mantid::DataHandling::PLN::EventCounter::EventCounter (const std::vector< bool > & roi, const std::vector< size_t > & mapIndex, const double framePeriod, const double gatePeriod, const TimeLimits & timeBoundary, std::vector< size_t > & eventCounts, const double L1, const double V0, const std::vector< double > & vecL2, size_t maxEvents) inline
Definition at line 362 of file LoadPLN.cpp.
Member Function Documentation
addEventImpl()
void Mantid::DataHandling::PLN::EventCounter::addEventImpl (size_t id, size_t , size_t , double tobs) inline override protected virtual
Implements Mantid::DataHandling::PLN::EventProcessor.
Definition at line 353 of file LoadPLN.cpp.
References Mantid::DataHandling::PLN::SimpleHist::add(), m_eventCounts, m_histogram, m_L1, m_L2, and m_V0.
tofCorrection()
double Mantid::DataHandling::PLN::EventCounter::tofCorrection () inline
Definition at line 369 of file LoadPLN.cpp.
References count, Mantid::DataHandling::PLN::SimpleHist::histogram(), m_histogram, Mantid::DataHandling::PLN::SimpleHist::peak(), and Mantid::DataHandling::PLN::SimpleHist::xval().
Referenced by Mantid::DataHandling::LoadPLN::exec().
Member Data Documentation
m_eventCounts
std::vector<size_t>& Mantid::DataHandling::PLN::EventCounter::m_eventCounts protected
Definition at line 347 of file LoadPLN.cpp.
Referenced by addEventImpl().
m_histogram
SimpleHist Mantid::DataHandling::PLN::EventCounter::m_histogram protected
Definition at line 351 of file LoadPLN.cpp.
Referenced by addEventImpl(), and tofCorrection().
m_L1
double Mantid::DataHandling::PLN::EventCounter::m_L1 protected
Definition at line 348 of file LoadPLN.cpp.
Referenced by addEventImpl().
m_L2
const std::vector<double>& Mantid::DataHandling::PLN::EventCounter::m_L2 protected
Definition at line 350 of file LoadPLN.cpp.
Referenced by addEventImpl().
m_V0
double Mantid::DataHandling::PLN::EventCounter::m_V0 protected
Definition at line 349 of file LoadPLN.cpp.
Referenced by addEventImpl().
The documentation for this class was generated from the following file:
Framework/DataHandling/src/LoadPLN.cpp