Mantid: Framework/PythonInterface/mantid/api/src/Exports/WorkspaceValidators.cpp File Reference
WorkspaceValidators.cpp File Reference
#include "MantidAPI/CommonBinsValidator.h"
#include "MantidAPI/HistogramValidator.h"
#include "MantidAPI/IMDWorkspace.h"
#include "MantidAPI/MDFrameValidator.h"
#include "MantidAPI/NumericAxisValidator.h"
#include "MantidAPI/PolSANSWorkspaceValidator.h"
#include "MantidAPI/RawCountValidator.h"
#include "MantidAPI/SpectraAxisValidator.h"
#include "MantidAPI/WorkspaceGroup.h"
#include "MantidAPI/WorkspaceUnitValidator.h"
#include "MantidPythonInterface/core/TypedValidatorExporter.h"
#include <boost/python/class.hpp>
#include <boost/python/list.hpp>
#include <boost/python/make_constructor.hpp>
Macros
#define EXPORT_WKSP_VALIDATOR_ARG(ValidatorType, ArgType, ArgName, DocString)
Export a validator derived from a MatrixWorkspaceValidator that has a single-arg constructor.
#define EXPORT_WKSP_VALIDATOR_DEFAULT_ARG(ValidatorType, ArgType, ArgName, DefaultValue, DocString)
Export a validator derived from a MatrixWorkspaceValidator that has a single-arg constructor with a default argument.
#define EXPORT_WKSP_VALIDATOR_NO_ARG(ValidatorType, DocString) class_<ValidatorType, bases<MatrixWorkspaceValidator>, boost::noncopyable>(#ValidatorType, init<>(DocString));
Export a validator derived from a MatrixWorkspaceValidator that has a no-arg constructor.
Functions
void export_MatrixWorkspaceValidator ()
This is the base TypedValidator for most of the WorkspaceValidators.
void export_WorkspaceValidators ()
std::shared_ptr< Mantid::API::PolSANSWorkspaceValidator > polSANSValidatorConstructor (bool expectHistogramData=true, bool allowMultiPeriodData=false, list allowedNumberOfPeriods=list())
Macro Definition Documentation
EXPORT_WKSP_VALIDATOR_ARG
#define EXPORT_WKSP_VALIDATOR_ARG (ValidatorType, ArgType, ArgName, DocString)
Value:
  class_<ValidatorType, bases<MatrixWorkspaceValidator>, boost::noncopyable>(#ValidatorType,                           \
                                                                             init<ArgType>(arg(ArgName), DocString));
Export a validator derived from a MatrixWorkspaceValidator that has a single-arg constructor.
Definition at line 66 of file WorkspaceValidators.cpp.
EXPORT_WKSP_VALIDATOR_DEFAULT_ARG
#define EXPORT_WKSP_VALIDATOR_DEFAULT_ARG (ValidatorType, ArgType, ArgName, DefaultValue, DocString)
Value:
  class_<ValidatorType, bases<MatrixWorkspaceValidator>, boost::noncopyable>(                                          \
      #ValidatorType, init<ArgType>(arg(ArgName) = DefaultValue, DocString));
Export a validator derived from a MatrixWorkspaceValidator that has a single-arg constructor with a default argument.
Definition at line 72 of file WorkspaceValidators.cpp.
EXPORT_WKSP_VALIDATOR_NO_ARG
#define EXPORT_WKSP_VALIDATOR_NO_ARG (ValidatorType, DocString) class_<ValidatorType, bases<MatrixWorkspaceValidator>, boost::noncopyable>(#ValidatorType, init<>(DocString));
Export a validator derived from a MatrixWorkspaceValidator that has a no-arg constructor.
Definition at line 62 of file WorkspaceValidators.cpp.
Function Documentation
export_MatrixWorkspaceValidator()
void export_MatrixWorkspaceValidator ()
This is the base TypedValidator for most of the WorkspaceValidators.
Definition at line 47 of file WorkspaceValidators.cpp.
References Mantid::PythonInterface::TypedValidatorExporter< Type >::define().
export_WorkspaceValidators()
void export_WorkspaceValidators ()
Definition at line 76 of file WorkspaceValidators.cpp.
References EXPORT_WKSP_VALIDATOR_ARG, EXPORT_WKSP_VALIDATOR_DEFAULT_ARG, EXPORT_WKSP_VALIDATOR_NO_ARG, and polSANSValidatorConstructor().
polSANSValidatorConstructor()
std::shared_ptr< Mantid::API::PolSANSWorkspaceValidator > polSANSValidatorConstructor (bool expectHistogramData = true, bool allowMultiPeriodData = false, list allowedNumberOfPeriods = list())
Definition at line 29 of file WorkspaceValidators.cpp.
Referenced by export_WorkspaceValidators().