Mantid: Mantid::Crystal::PeakHKLErrors Class Reference
Mantid::Crystal::PeakHKLErrors Class Reference
#include <PeakHKLErrors.h>
Public Member Functions
const std::string category () const override
The categories the Fit function belong to.
void function1D (double *out, const double *xValues, const size_t nData) const override
Calculates the h,k, and l offsets from an integer for (some of)the peaks, given the parameter values.
void functionDeriv1D (Mantid::API::Jacobian *out, const double *xValues, const size_t nData) override
Derivatives of function with respect to active parameters.
IFunction::Attribute getAttribute (const std::string &attName) const override
Return a value of attribute attName.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names.
std::shared_ptr< Geometry::Instrument > getNewInstrument (const DataObjects::PeaksWorkspace_sptr &peaksWs) const
Creates a new parameterized instrument for which the parameter values can be changed.
void getRun2MatMap (DataObjects::PeaksWorkspace_sptr &Peaks, const std::string &OptRuns, std::map< int, Mantid::Kernel::Matrix< double > > &Res) const
Updates the map from run number to GoniometerMatrix.
bool hasAttribute (const std::string &attName) const override
Check if attribute attName exists.
void init () override
Function initialization. Declare function parameters in this method.
std::string name () const override
Returns the function's name.
size_t nAttributes () const override
Returns the number of attributes associated with the function.
PeakHKLErrors ()
void setAttribute (const std::string &attName, const IFunction::Attribute &value) override
Set a value to attribute attName.
virtual int version () const
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::IFunction1D
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
Static Public Member Functions
static void cLone (std::shared_ptr< Geometry::ParameterMap > &pmap, const std::shared_ptr< const Geometry::IComponent > &component, std::shared_ptr< const Geometry::ParameterMap > &pmapSv)
"Clones" a parameter map duplicating all Parameters with double,V3D,int and string parameter values that apply to the given component and all(most) of the components children.
static DataObjects::Peak createNewPeak (const DataObjects::Peak &peak_old, const Geometry::Instrument_sptr &instrNew, double T0, double L0)
Creates a new peak, matching the old peak except for a different instrument.
static Kernel::Matrix< double > DerivRotationMatrixAboutRegAxis (double theta, char axis)
Returns the derivative of the matrix corresponding to a rotation of theta(degrees) around axis with respect to the angle or rotation in degrees.
static Kernel::Matrix< double > RotationMatrixAboutRegAxis (double theta, char axis)
Returns the matrix corresponding to a rotation of theta(degrees) around axis.
Private Member Functions
void setUpOptRuns ()
Declares parameters for the chi,phi and omega angles for the run numbers where these will be optimized.
Private Attributes
bool hasParameterMap = false
int initMode
std::shared_ptr< Geometry::Instrument > instChange
std::string OptRuns
std::string PeakWorkspaceName
std::shared_ptr< const Geometry::ParameterMap > pmapSv
Kernel::V3D sampPos
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Types inherited from Mantid::API::IFunction1D
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::IFunction1D
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Static Protected Attributes inherited from Mantid::API::IFunction1D
static Kernel::Logger g_log
Logger instance.
Detailed Description
Author
Ruth Mikkelson, SNS,ORNL
Date
01/26/2013
Definition at line 33 of file PeakHKLErrors.h.
Constructor & Destructor Documentation
PeakHKLErrors()
Mantid::Crystal::PeakHKLErrors::PeakHKLErrors ()
Definition at line 44 of file PeakHKLErrors.cpp.
Member Function Documentation
category()
const std::string Mantid::Crystal::PeakHKLErrors::category () const inline override virtual
The categories the Fit function belong to.
Categories must be listed as a semi colon separated list. For example: "General, Muon\\Custom" which adds a function to the category "General" and the sub-category "Muon\\Custom"
Reimplemented from Mantid::API::IFunction.
Definition at line 41 of file PeakHKLErrors.h.
cLone()
void Mantid::Crystal::PeakHKLErrors::cLone (std::shared_ptr< Geometry::ParameterMap > & pmap, const std::shared_ptr< const Geometry::IComponent > & component, std::shared_ptr< const Geometry::ParameterMap > & pmapSv) static
"Clones" a parameter map duplicating all Parameters with double,V3D,int and string parameter values that apply to the given component and all(most) of the components children.
If the component is an instrument, this parameter map can be used to create a separate parameterized instrument close to the original instrument.
NOTE: For speed purposes, if a component(or subcomponent) has too many children(180 or more),the parameters corresponding to these children(and subchildren) will not be added to the parameter map
Parameters
pmap The new parameter map to which the new Parameters are to be added
component The component along with most of its children and subchildren for which Parameters that correspond to these will be considered.
pmapSv The old parameter map from which copies of the parameters corresponding to the given component or subchild are added to pmap
Definition at line 111 of file PeakHKLErrors.cpp.
References cLone(), and pmapSv.
Referenced by cLone(), and getNewInstrument().
createNewPeak()
Peak Mantid::Crystal::PeakHKLErrors::createNewPeak (const DataObjects::Peak & peak_old, const Geometry::Instrument_sptr & instrNew, double T0, double L0) static
Creates a new peak, matching the old peak except for a different instrument.
The Time of flightis the same except offset by T0. L0 should be the L0 for the new instrument. It is added as a parameter in case the instrument will have the initial flight path adjusted later. NOTE: the wavelength is changed.
Parameters
peak_old - The old peak
instrNew -The new instrument
T0 :
L0 :
Returns
The new peak with the new instrument(adjusted with the parameters) and time adjusted.
!!peak.setDetectorID(ID);
Definition at line 600 of file PeakHKLErrors.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::IFunction1D::g_log, Mantid::DataObjects::BasePeak::getBinCount(), Mantid::DataObjects::Peak::getDetectorID(), Mantid::DataObjects::BasePeak::getGoniometerMatrix(), Mantid::DataObjects::BasePeak::getHKL(), Mantid::DataObjects::Peak::getInitialEnergy(), Mantid::DataObjects::Peak::getInstrument(), Mantid::DataObjects::BasePeak::getIntensity(), Mantid::DataObjects::Peak::getL2(), Mantid::DataObjects::BasePeak::getRunNumber(), Mantid::DataObjects::Peak::getScattering(), Mantid::DataObjects::BasePeak::getSigmaIntensity(), Mantid::DataObjects::Peak::getTOF(), Mantid::DataObjects::Peak::getWavelength(), Mantid::Kernel::Unit::initialize(), Mantid::DataObjects::BasePeak::setBinCount(), Mantid::DataObjects::BasePeak::setIntensity(), Mantid::DataObjects::BasePeak::setRunNumber(), Mantid::DataObjects::BasePeak::setSigmaIntensity(), Mantid::DataObjects::Peak::setWavelength(), and Mantid::Kernel::Units::Wavelength::singleFromTOF().
Referenced by function1D(), and functionDeriv1D().
DerivRotationMatrixAboutRegAxis()
Matrix< double > Mantid::Crystal::PeakHKLErrors::DerivRotationMatrixAboutRegAxis (double theta, char axis) static
Returns the derivative of the matrix corresponding to a rotation of theta(degrees) around axis with respect to the angle or rotation in degrees.
Parameters
theta the angle of rotation in degrees
axis either x,y,z, or X,Y, or Z.
Returns
The derivative of the matrix that corresponds to this action with respect to degree rotation.
Definition at line 297 of file PeakHKLErrors.cpp.
References Mantid::Kernel::Matrix< T >::zeroMatrix().
Referenced by functionDeriv1D().
function1D()
void Mantid::Crystal::PeakHKLErrors::function1D (double * out, const double * xValues, const size_t nData) const override virtual
Calculates the h,k, and l offsets from an integer for (some of)the peaks, given the parameter values.
Parameters
out For each peak there are 3 consecutive elements in this array. The first is for the h offset from an integer, the second is the k offset and the 3rd is the l offset
xValues xValues give the index in the PeaksWorkspace for the peak. For each peak considered there are three consecutive entries all with the same index
nData The size of the xValues and out arrays
Implements Mantid::API::IFunction1D.
Definition at line 331 of file PeakHKLErrors.cpp.
References Mantid::API::IConstraint::check(), createNewPeak(), Mantid::Kernel::Logger::debug(), Mantid::API::IFunction1D::g_log, Mantid::API::IFunction::getConstraint(), Mantid::DataObjects::BasePeak::getGoniometerMatrix(), Mantid::DataObjects::Peak::getL1(), getNewInstrument(), Mantid::API::ParamFunction::getParameter(), Mantid::DataObjects::Peak::getQSampleFrame(), getRun2MatMap(), Mantid::DataObjects::BasePeak::getRunNumber(), Mantid::DataObjects::BasePeak::getSamplePos(), Mantid::Kernel::Matrix< T >::Invert(), Mantid::API::ParamFunction::nParams(), OptRuns, Mantid::API::ParamFunction::parameterName(), PeakWorkspaceName, RotationMatrixAboutRegAxis(), Mantid::DataObjects::BasePeak::setGoniometerMatrix(), Mantid::DataObjects::BasePeak::setSamplePos(), and std::to_string().
functionDeriv1D()
void Mantid::Crystal::PeakHKLErrors::functionDeriv1D (Mantid::API::Jacobian * jacobian, const double * xValues, const size_t nData) override virtual
Derivatives of function with respect to active parameters.
Reimplemented from Mantid::API::IFunction1D.
Definition at line 404 of file PeakHKLErrors.cpp.
References createNewPeak(), Mantid::Kernel::Logger::debug(), DerivRotationMatrixAboutRegAxis(), Mantid::API::IFunction1D::g_log, Mantid::DataObjects::Peak::getDetPos(), Mantid::Geometry::Goniometer::getEulerAngles(), Mantid::DataObjects::BasePeak::getGoniometerMatrix(), Mantid::Geometry::IPeak::getL1(), Mantid::DataObjects::Peak::getL1(), Mantid::Geometry::IPeak::getL2(), getNewInstrument(), Mantid::API::ParamFunction::getParameter(), Mantid::DataObjects::Peak::getQLabFrame(), getRun2MatMap(), Mantid::DataObjects::BasePeak::getRunNumber(), Mantid::DataObjects::BasePeak::getSamplePos(), Mantid::Geometry::IPeak::getTOF(), Mantid::DataObjects::Peak::getTOF(), Mantid::Geometry::IPeak::getWavelength(), Mantid::Kernel::Matrix< T >::Invert(), Mantid::Kernel::V3D::norm(), Mantid::API::ParamFunction::nParams(), OptRuns, Mantid::API::ParamFunction::parameterIndex(), PeakWorkspaceName, RotationMatrixAboutRegAxis(), Mantid::API::Jacobian::set(), Mantid::DataObjects::BasePeak::setGoniometerMatrix(), Mantid::DataObjects::BasePeak::setSamplePos(), std::to_string(), and Mantid::Geometry::x.
getAttribute()
IFunction::Attribute Mantid::Crystal::PeakHKLErrors::getAttribute (const std::string & name) const inline override virtual
Return a value of attribute attName.
Parameters
name :: Returns the named attribute
Reimplemented from Mantid::API::IFunction.
Definition at line 85 of file PeakHKLErrors.h.
getAttributeNames()
std::vector< std::string > Mantid::Crystal::PeakHKLErrors::getAttributeNames () const inline override virtual
Returns a list of attribute names.
Reimplemented from Mantid::API::IFunction.
Definition at line 83 of file PeakHKLErrors.h.
getNewInstrument()
std::shared_ptr< Geometry::Instrument > Mantid::Crystal::PeakHKLErrors::getNewInstrument (const DataObjects::PeaksWorkspace_sptr & peaksWs) const
Creates a new parameterized instrument for which the parameter values can be changed.
Parameters
peaksWs - a PeaksWorkspace used to get the original instrument. The instrument from the 0th peak is the one that is used.
NOTE: All the peaks in the PeaksWorkspace must use the same instrument.
Definition at line 174 of file PeakHKLErrors.cpp.
References cLone(), Mantid::Kernel::Logger::error(), Mantid::API::IFunction1D::g_log, Mantid::API::ParamFunction::getParameter(), hasParameterMap, instChange, pmapSv, sampPos, Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by function1D(), and functionDeriv1D().
getRun2MatMap()
void Mantid::Crystal::PeakHKLErrors::getRun2MatMap (DataObjects::PeaksWorkspace_sptr & Peaks, const std::string & OptRuns, std::map< int, Mantid::Kernel::Matrix< double > > & Res) const
Updates the map from run number to GoniometerMatrix.
Parameters
Peaks The PeaksWorkspace whose peaks contain the run numbers along with the corresponding GoniometerMatrix
OptRuns A '/' separated "list" of run numbers to include in the map. This string must also start and end with a '/'
Res The resultant map.
Definition at line 231 of file PeakHKLErrors.cpp.
References Mantid::API::ParamFunction::getParameter(), Mantid::Geometry::Goniometer::getR(), Mantid::Geometry::IPeak::getRunNumber(), Mantid::Geometry::Goniometer::makeUniversalGoniometer(), OptRuns, Mantid::Geometry::Goniometer::setRotationAngle(), and std::to_string().
Referenced by function1D(), and functionDeriv1D().
hasAttribute()
bool Mantid::Crystal::PeakHKLErrors::hasAttribute (const std::string & name) const inline override virtual
Check if attribute attName exists.
Check if attribute named exists.
Reimplemented from Mantid::API::IFunction.
Definition at line 125 of file PeakHKLErrors.h.
init()
void Mantid::Crystal::PeakHKLErrors::init () override virtual
Function initialization. Declare function parameters in this method.
Initialize the function. Calls declareAttributes & declareParameters.
Reimplemented from Mantid::API::IFunction.
Definition at line 46 of file PeakHKLErrors.cpp.
References Mantid::API::ParamFunction::declareParameter(), initMode, OptRuns, and setUpOptRuns().
name()
std::string Mantid::Crystal::PeakHKLErrors::name () const inline override virtual
Returns the function's name.
Implements Mantid::API::IFunction.
Definition at line 37 of file PeakHKLErrors.h.
nAttributes()
size_t Mantid::Crystal::PeakHKLErrors::nAttributes () const inline override virtual
Returns the number of attributes associated with the function.
Reimplemented from Mantid::API::IFunction.
Definition at line 75 of file PeakHKLErrors.h.
RotationMatrixAboutRegAxis()
Matrix< double > Mantid::Crystal::PeakHKLErrors::RotationMatrixAboutRegAxis (double theta, char axis) static
Returns the matrix corresponding to a rotation of theta(degrees) around axis.
Parameters
theta the angle of rotation in degrees
axis either x,y,z, or X,Y, or Z.
Returns
The matrix that corresponds to this action.
Replace by Quats?
Definition at line 264 of file PeakHKLErrors.cpp.
References Mantid::Kernel::Matrix< T >::zeroMatrix().
Referenced by Mantid::Crystal::OptimizeCrystalPlacement::exec(), function1D(), and functionDeriv1D().
setAttribute()
void Mantid::Crystal::PeakHKLErrors::setAttribute (const std::string & name, const IFunction::Attribute & value) inline override virtual
Set a value to attribute attName.
Set a value to a named attribute.
Can be overridden in the inheriting class, the default just stores the value
Parameters
name :: The name of the attribute
value :: The value of the attribute
Reimplemented from Mantid::API::IFunction.
Definition at line 95 of file PeakHKLErrors.h.
References value.
setUpOptRuns()
void Mantid::Crystal::PeakHKLErrors::setUpOptRuns () private
Declares parameters for the chi,phi and omega angles for the run numbers where these will be optimized.
Definition at line 64 of file PeakHKLErrors.cpp.
References Mantid::API::ParamFunction::declareParameter(), and OptRuns.
Referenced by init().
version()
virtual int Mantid::Crystal::PeakHKLErrors::version () const inline virtual
Definition at line 39 of file PeakHKLErrors.h.
Member Data Documentation
hasParameterMap
bool Mantid::Crystal::PeakHKLErrors::hasParameterMap = false mutable private
Definition at line 146 of file PeakHKLErrors.h.
Referenced by getNewInstrument().
initMode
int Mantid::Crystal::PeakHKLErrors::initMode private
Definition at line 140 of file PeakHKLErrors.h.
Referenced by init().
instChange
std::shared_ptr<Geometry::Instrument> Mantid::Crystal::PeakHKLErrors::instChange mutable private
Definition at line 145 of file PeakHKLErrors.h.
Referenced by getNewInstrument().
OptRuns
std::string Mantid::Crystal::PeakHKLErrors::OptRuns private
Definition at line 136 of file PeakHKLErrors.h.
Referenced by function1D(), functionDeriv1D(), getRun2MatMap(), init(), and setUpOptRuns().
PeakWorkspaceName
std::string Mantid::Crystal::PeakHKLErrors::PeakWorkspaceName private
Definition at line 138 of file PeakHKLErrors.h.
Referenced by function1D(), and functionDeriv1D().
pmapSv
std::shared_ptr<const Geometry::ParameterMap> Mantid::Crystal::PeakHKLErrors::pmapSv mutable private
Definition at line 148 of file PeakHKLErrors.h.
Referenced by cLone(), and getNewInstrument().
sampPos
Kernel::V3D Mantid::Crystal::PeakHKLErrors::sampPos mutable private
Definition at line 147 of file PeakHKLErrors.h.
Referenced by getNewInstrument().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/PeakHKLErrors.h
Framework/Crystal/src/PeakHKLErrors.cpp