Mantid: Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy > Class Template Reference
Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy > Class Template Reference
#include <MDGeometryXMLBuilder.h>
Public Member Functions
void addManyOrdinaryDimensions (const VecIMDDimension_sptr &manyDims) const
Add many ordinary dimensions.
bool addOrdinaryDimension (IMDDimension_const_sptr dimensionToAdd) const
Add a dimension that is neither considered x, y, z or t.
bool addTDimension (const IMDDimension_const_sptr &dimension) const
Add t dimension.
bool addXDimension (const IMDDimension_const_sptr &dimension) const
Add x dimension.
bool addYDimension (const IMDDimension_const_sptr &dimension) const
Add y dimension.
bool addZDimension (const IMDDimension_const_sptr &dimension) const
Add z dimension.
const std::string & create () const
Create the xml.
bool hasIntegratedTDimension () const
Determine whether an integrated t dimension has been provided.
bool hasTDimension () const
Determine whether a valid t dimension has been provided.
bool hasXDimension () const
Determine if a valid x dimension has been provided.
bool hasYDimension () const
Determine whether a valid y dimension has been provided.
bool hasZDimension () const
Determine whether a valid z dimension has been provided.
MDGeometryBuilderXML ()
Constructor.
MDGeometryBuilderXML (const MDGeometryBuilderXML &)
Copy constructor.
MDGeometryBuilderXML & operator= (const MDGeometryBuilderXML &)
Assignment Operator.
~MDGeometryBuilderXML ()
Destructor.
Private Types
using DimensionContainerType = std::vector< IMDDimension_const_sptr >
Private Member Functions
void applyPolicyChecking (const IMDDimension &dimensionToAdd) const
Instantiate and apply the checking policy.
Private Attributes
bool m_changed
Flag indicating that some change in the inputs has occured.
std::string m_lastResult
Variable suports lazy calculation.
IMDDimension_const_sptr m_spTDimension
IMDDimension_const_sptr m_spXDimension
IMDDimension_const_sptr m_spYDimension
IMDDimension_const_sptr m_spZDimension
DimensionContainerType m_vecDimensions
Detailed Description
template<typename CheckDimensionPolicy>
class Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >
Definition at line 30 of file MDGeometryXMLBuilder.h.
Member Typedef Documentation
DimensionContainerType
template<typename CheckDimensionPolicy > using Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::DimensionContainerType = std::vector<IMDDimension_const_sptr> private
Definition at line 82 of file MDGeometryXMLBuilder.h.
Constructor & Destructor Documentation
MDGeometryBuilderXML() [1/2]
template<typename CheckDimensionPolicy > Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::MDGeometryBuilderXML ()
Constructor.
Definition at line 266 of file MDGeometryXMLBuilder.cpp.
~MDGeometryBuilderXML()
template<typename CheckDimensionPolicy > Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::~MDGeometryBuilderXML () default
Destructor.
References Mantid::DataObjects::create().
MDGeometryBuilderXML() [2/2]
template<typename CheckDimensionPolicy > Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::MDGeometryBuilderXML (const MDGeometryBuilderXML< CheckDimensionPolicy > & other)
Copy constructor.
Definition at line 58 of file MDGeometryXMLBuilder.cpp.
Member Function Documentation
addManyOrdinaryDimensions()
template<typename CheckDimensionPolicy > void Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addManyOrdinaryDimensions (const VecIMDDimension_sptr & manyDims) const
Add many ordinary dimensions.
Parameters
manyDims :: Collection of dimensions to add as ordinary dimensions.
Definition at line 51 of file MDGeometryXMLBuilder.cpp.
addOrdinaryDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addOrdinaryDimension (IMDDimension_const_sptr dimensionToAdd) const
Add a dimension that is neither considered x, y, z or t.
Add an ordinary dimension.
Parameters
dimensionToAdd :: The dimension to add to the geometry.
Returns
true if addition does not cause an overwrite successful.
Definition at line 30 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
addTDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addTDimension (const IMDDimension_const_sptr & dimension) const
Add t dimension.
Add an t dimension.
Parameters
dimension :: The dimension to add to the geometry.
Returns
true if addition was successful.
Definition at line 151 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
addXDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addXDimension (const IMDDimension_const_sptr & dimension) const
Add x dimension.
Add an x dimension.
Parameters
dimension :: The dimension to add to the geometry.
Returns
true if addition was successful.
Definition at line 95 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
addYDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addYDimension (const IMDDimension_const_sptr & dimension) const
Add y dimension.
Add an y dimension.
Parameters
dimension :: The dimension to add to the geometry.
Returns
true if addition was successful.
Definition at line 114 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
addZDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addZDimension (const IMDDimension_const_sptr & dimension) const
Add z dimension.
Add an z dimension.
Parameters
dimension :: The dimension to add to the geometry.
Returns
true if addition was successful.
Definition at line 133 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
applyPolicyChecking()
template<typename CheckDimensionPolicy > void Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::applyPolicyChecking (const IMDDimension & dimensionToAdd) const private
Instantiate and apply the checking policy.
Check that the addition of dimensions conforms to the defined policy.
Parameters
dimensionToAdd :: The dimension to add to the geometry.
Definition at line 84 of file MDGeometryXMLBuilder.cpp.
create()
template<typename CheckDimensionPolicy > const std::string & Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::create () const
Create the xml.
Builder creational method.
Processes added dimensions. creates xml string.
Returns
xmlstring.
Definition at line 168 of file MDGeometryXMLBuilder.cpp.
Referenced by Mantid::API::MDGeometry::getGeometryXML().
hasIntegratedTDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::hasIntegratedTDimension () const
Determine whether an integrated t dimension has been provided.
Definition at line 258 of file MDGeometryXMLBuilder.cpp.
hasTDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::hasTDimension () const
Determine whether a valid t dimension has been provided.
Definition at line 253 of file MDGeometryXMLBuilder.cpp.
hasXDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::hasXDimension () const
Determine if a valid x dimension has been provided.
Definition at line 241 of file MDGeometryXMLBuilder.cpp.
hasYDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::hasYDimension () const
Determine whether a valid y dimension has been provided.
Definition at line 245 of file MDGeometryXMLBuilder.cpp.
hasZDimension()
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::hasZDimension () const
Determine whether a valid z dimension has been provided.
Definition at line 249 of file MDGeometryXMLBuilder.cpp.
operator=()
template<typename CheckDimensionPolicy > MDGeometryBuilderXML< CheckDimensionPolicy > & Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::operator= (const MDGeometryBuilderXML< CheckDimensionPolicy > & other)
Assignment Operator.
Definition at line 66 of file MDGeometryXMLBuilder.cpp.
Member Data Documentation
m_changed
template<typename CheckDimensionPolicy > bool Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_changed mutable private
Flag indicating that some change in the inputs has occured.
Triggers full recreation.
Definition at line 99 of file MDGeometryXMLBuilder.h.
m_lastResult
template<typename CheckDimensionPolicy > std::string Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_lastResult mutable private
Variable suports lazy calculation.
Definition at line 102 of file MDGeometryXMLBuilder.h.
m_spTDimension
template<typename CheckDimensionPolicy > IMDDimension_const_sptr Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_spTDimension mutable private
Definition at line 92 of file MDGeometryXMLBuilder.h.
m_spXDimension
template<typename CheckDimensionPolicy > IMDDimension_const_sptr Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_spXDimension mutable private
Definition at line 86 of file MDGeometryXMLBuilder.h.
m_spYDimension
template<typename CheckDimensionPolicy > IMDDimension_const_sptr Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_spYDimension mutable private
Definition at line 88 of file MDGeometryXMLBuilder.h.
m_spZDimension
template<typename CheckDimensionPolicy > IMDDimension_const_sptr Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_spZDimension mutable private
Definition at line 90 of file MDGeometryXMLBuilder.h.
m_vecDimensions
template<typename CheckDimensionPolicy > DimensionContainerType Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::m_vecDimensions mutable private
Definition at line 84 of file MDGeometryXMLBuilder.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDGeometryXMLBuilder.h
Framework/Geometry/src/MDGeometry/MDGeometryXMLBuilder.cpp