Mantid: Mantid::API::PolSANSWorkspaceValidator Class Reference
Mantid::API::PolSANSWorkspaceValidator Class Reference
PolSANSWorkspaceValidator : Validator for SANS polarized transmission runs.
#include <PolSANSWorkspaceValidator.h>
Public Member Functions
Kernel::IValidator_sptr clone () const override
Clone the current state.
std::string getType () const
Gets the type of the validator.
PolSANSWorkspaceValidator (bool expectHistogramData=true, bool allowMultiPeriodData=false, const std::unordered_set< int > &allowedNumberOfPeriods={4})
Private Member Functions
std::string checkValidity (const WorkspaceGroup_sptr &workspace) const override
Check for validity.
std::string validateGroupItem (API::MatrixWorkspace_sptr const &workspace) const
Private Attributes
const std::unordered_set< int > m_allowedNumberOfPeriods
const bool m_allowMultiPeriodData
const bool m_expectHistogramData
Detailed Description
PolSANSWorkspaceValidator : Validator for SANS polarized transmission runs.
Definition at line 20 of file PolSANSWorkspaceValidator.h.
Constructor & Destructor Documentation
PolSANSWorkspaceValidator()
Mantid::API::PolSANSWorkspaceValidator::PolSANSWorkspaceValidator (bool expectHistogramData = true, bool allowMultiPeriodData = false, const std::unordered_set< int > & allowedNumberOfPeriods = {4}) explicit
Definition at line 16 of file PolSANSWorkspaceValidator.cpp.
Member Function Documentation
checkValidity()
std::string Mantid::API::PolSANSWorkspaceValidator::checkValidity (const WorkspaceGroup_sptr & workspace) const override private
Check for validity.
Definition at line 55 of file PolSANSWorkspaceValidator.cpp.
References m_allowedNumberOfPeriods, validateGroupItem(), and workspace.
clone()
Kernel::IValidator_sptr Mantid::API::PolSANSWorkspaceValidator::clone () const override
Clone the current state.
Definition at line 21 of file PolSANSWorkspaceValidator.cpp.
getType()
std::string Mantid::API::PolSANSWorkspaceValidator::getType () const inline
Gets the type of the validator.
Definition at line 25 of file PolSANSWorkspaceValidator.h.
validateGroupItem()
std::string Mantid::API::PolSANSWorkspaceValidator::validateGroupItem (API::MatrixWorkspace_sptr const & workspace) const private
Definition at line 25 of file PolSANSWorkspaceValidator.cpp.
References Mantid::Kernel::Strings::join(), m_allowMultiPeriodData, m_expectHistogramData, and workspace.
Referenced by checkValidity().
Member Data Documentation
m_allowedNumberOfPeriods
const std::unordered_set<int> Mantid::API::PolSANSWorkspaceValidator::m_allowedNumberOfPeriods private
Definition at line 36 of file PolSANSWorkspaceValidator.h.
Referenced by checkValidity().
m_allowMultiPeriodData
const bool Mantid::API::PolSANSWorkspaceValidator::m_allowMultiPeriodData private
Definition at line 35 of file PolSANSWorkspaceValidator.h.
Referenced by validateGroupItem().
m_expectHistogramData
const bool Mantid::API::PolSANSWorkspaceValidator::m_expectHistogramData private
Definition at line 34 of file PolSANSWorkspaceValidator.h.
Referenced by validateGroupItem().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/PolSANSWorkspaceValidator.h
Framework/API/src/PolSANSWorkspaceValidator.cpp