Mantid: MantidQt::MantidWidgets::SlitCalculator Class Reference
MantidQt::MantidWidgets::SlitCalculator Class Reference
SlitCalculator : A calculator for Reflectometry instrument slits.
#include <SlitCalculator.h>
Public Member Functions
void processInstrumentHasBeenChanged () override
void setCurrentInstrumentName (const std::string &instrumentName) override
void show () override
SlitCalculator (QWidget *parent)
~SlitCalculator () override
Public Member Functions inherited from MantidQt::MantidWidgets::ISlitCalculator
virtual ~ISlitCalculator ()=default
Protected Attributes
Ui::SlitCalculator ui
Private Slots
void on_recalculate_triggered ()
Private Member Functions
const std::string & getCurrentInstrumentName ()
Mantid::Geometry::Instrument_const_sptr getInstrument ()
void setInstrument (const std::string &instrumentName)
void setupSlitCalculatorWithInstrumentValues (const Mantid::Geometry::Instrument_const_sptr &)
Private Attributes
std::string currentInstrumentName
Mantid::Geometry::Instrument_const_sptr instrument
Detailed Description
SlitCalculator : A calculator for Reflectometry instrument slits.
Definition at line 23 of file SlitCalculator.h.
Constructor & Destructor Documentation
SlitCalculator()
MantidQt::MantidWidgets::SlitCalculator::SlitCalculator (QWidget * parent)
Definition at line 18 of file SlitCalculator.cpp.
References currentInstrumentName, on_recalculate_triggered(), setInstrument(), and ui.
~SlitCalculator()
MantidQt::MantidWidgets::SlitCalculator::~SlitCalculator () override default
Member Function Documentation
getCurrentInstrumentName()
const std::string & MantidQt::MantidWidgets::SlitCalculator::getCurrentInstrumentName () private
Definition at line 88 of file SlitCalculator.cpp.
References currentInstrumentName.
getInstrument()
Mantid::Geometry::Instrument_const_sptr MantidQt::MantidWidgets::SlitCalculator::getInstrument () private
Definition at line 84 of file SlitCalculator.cpp.
References instrument.
Referenced by on_recalculate_triggered().
on_recalculate_triggered
void MantidQt::MantidWidgets::SlitCalculator::on_recalculate_triggered () private slot
Definition at line 89 of file SlitCalculator.cpp.
References currentInstrumentName, getInstrument(), setInstrument(), and ui.
Referenced by processInstrumentHasBeenChanged(), and SlitCalculator().
processInstrumentHasBeenChanged()
void MantidQt::MantidWidgets::SlitCalculator::processInstrumentHasBeenChanged () override virtual
Implements MantidQt::MantidWidgets::ISlitCalculator.
Definition at line 29 of file SlitCalculator.cpp.
References on_recalculate_triggered().
setCurrentInstrumentName()
void MantidQt::MantidWidgets::SlitCalculator::setCurrentInstrumentName (const std::string & instrumentName) override virtual
Implements MantidQt::MantidWidgets::ISlitCalculator.
Definition at line 85 of file SlitCalculator.cpp.
References currentInstrumentName.
setInstrument()
void MantidQt::MantidWidgets::SlitCalculator::setInstrument (const std::string & instrumentName) private
Definition at line 35 of file SlitCalculator.cpp.
References Mantid::API::InstrumentFileFinder::getInstrumentFilename(), Mantid::Geometry::InstrumentDefinitionParser::getMangledName(), instrument, Mantid::Kernel::Strings::loadFile(), Mantid::Geometry::InstrumentDefinitionParser::parseXML(), and setupSlitCalculatorWithInstrumentValues().
Referenced by on_recalculate_triggered(), and SlitCalculator().
setupSlitCalculatorWithInstrumentValues()
void MantidQt::MantidWidgets::SlitCalculator::setupSlitCalculatorWithInstrumentValues (const Mantid::Geometry::Instrument_const_sptr & instrument) private
Definition at line 60 of file SlitCalculator.cpp.
References instrument, and ui.
Referenced by setInstrument().
show()
void MantidQt::MantidWidgets::SlitCalculator::show () override virtual
Implements MantidQt::MantidWidgets::ISlitCalculator.
Definition at line 58 of file SlitCalculator.cpp.
Member Data Documentation
currentInstrumentName
std::string MantidQt::MantidWidgets::SlitCalculator::currentInstrumentName private
Definition at line 37 of file SlitCalculator.h.
Referenced by getCurrentInstrumentName(), on_recalculate_triggered(), setCurrentInstrumentName(), and SlitCalculator().
instrument
Mantid::Geometry::Instrument_const_sptr MantidQt::MantidWidgets::SlitCalculator::instrument private
Definition at line 36 of file SlitCalculator.h.
Referenced by getInstrument(), setInstrument(), and setupSlitCalculatorWithInstrumentValues().
ui
Ui::SlitCalculator MantidQt::MantidWidgets::SlitCalculator::ui protected
Definition at line 33 of file SlitCalculator.h.
Referenced by on_recalculate_triggered(), setupSlitCalculatorWithInstrumentValues(), and SlitCalculator().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/SlitCalculator.h
qt/widgets/common/src/SlitCalculator.cpp