Mantid: Mantid::DataObjects::PeakShapeDetectorBin Class Reference
Mantid::DataObjects::PeakShapeDetectorBin Class Reference
PeakShapeDetectorBin : PeakShape representing detector ids and integration limits of a peak.
#include <PeakShapeDetectorBin.h>
Public Member Functions
Mantid::Geometry::PeakShape * clone () const override
Clone PeakShapeDetectorBin.
const std::vector< std::tuple< int32_t, double, double > > & getDetectorBinList () const
bool operator== (const PeakShapeDetectorBin &other) const
Equals operator.
PeakShapeDetectorBin (const std::vector< std::tuple< int32_t, double, double > > &detectorBinList, Kernel::SpecialCoordinateSystem frame, std::string algorithmName=std::string(), int algorithmVersion=-1)
Create PeakShapeDetectorBin.
std::optional< double > radius (RadiusType) const override
PeakBase interface.
std::string shapeName () const override
Get the peak shape.
std::string toJSON () const override
PeakShape interface.
Public Member Functions inherited from Mantid::DataObjects::PeakShapeBase
std::string algorithmName () const override
Get the name of the algorithm used to make this shape.
int algorithmVersion () const override
Get the version of the algorithm used to make this shape.
Kernel::SpecialCoordinateSystem frame () const override
Get the coordinate frame.
PeakShapeBase (Kernel::SpecialCoordinateSystem frame, std::string algorithmName=std::string(), int algorithmVersion=-1)
Constructor.
Public Member Functions inherited from Mantid::Geometry::PeakShape
virtual ~PeakShape ()=default
Destructor.
Static Public Member Functions
static const std::string detectorBinShapeName ()
Private Attributes
std::vector< std::tuple< int32_t, double, double > > m_detectorBinList
Additional Inherited Members
Public Types inherited from Mantid::Geometry::PeakShape
enum RadiusType { Radius = 0 , OuterRadius = 1 , InnerRadius = 2 }
For selecting different radius types.
Protected Member Functions inherited from Mantid::DataObjects::PeakShapeBase
void buildCommon (Json::Value &root) const
Build common parts of outgoing JSON serialization.
PeakShapeBase & operator= (const PeakShapeBase &)=default
Assignment operator.
bool operator== (const PeakShapeBase &other) const
Equals operator.
PeakShapeBase (const PeakShapeBase &)=default
Copy constructor.
Protected Attributes inherited from Mantid::DataObjects::PeakShapeBase
std::string m_algorithmName
Generating algorithm name.
int m_algorithmVersion
Generating algorithm version.
Mantid::Kernel::SpecialCoordinateSystem m_frame
Special coordinate system.
Detailed Description
PeakShapeDetectorBin : PeakShape representing detector ids and integration limits of a peak.
Definition at line 17 of file PeakShapeDetectorBin.h.
Constructor & Destructor Documentation
PeakShapeDetectorBin()
Mantid::DataObjects::PeakShapeDetectorBin::PeakShapeDetectorBin (const std::vector< std::tuple< int32_t, double, double > > & detectorBinList, Kernel::SpecialCoordinateSystem frame, std::string algorithmName = std::string(), int algorithmVersion = -1)
Create PeakShapeDetectorBin.
Parameters
detectorBinList The list containing each detector Ids associated with its start and end points in TOF or dSpacing domains
frame SpecialCoordinateSystem frame, default is None
algorithmName Name of the algorithm using this shape
algorithmVersion Version of the above algorithm
Definition at line 24 of file PeakShapeDetectorBin.cpp.
Member Function Documentation
clone()
Mantid::Geometry::PeakShape * Mantid::DataObjects::PeakShapeDetectorBin::clone () const override virtual
Clone PeakShapeDetectorBin.
Implements Mantid::Geometry::PeakShape.
Definition at line 54 of file PeakShapeDetectorBin.cpp.
detectorBinShapeName()
const std::string Mantid::DataObjects::PeakShapeDetectorBin::detectorBinShapeName () static
Definition at line 58 of file PeakShapeDetectorBin.cpp.
Referenced by Mantid::DataObjects::PeakShapeDetectorBinFactory::create(), and shapeName().
getDetectorBinList()
const std::vector< std::tuple< int32_t, double, double > > & Mantid::DataObjects::PeakShapeDetectorBin::getDetectorBinList () const inline
Definition at line 37 of file PeakShapeDetectorBin.h.
operator==()
bool Mantid::DataObjects::PeakShapeDetectorBin::operator== (const PeakShapeDetectorBin & other) const
Equals operator.
Definition at line 34 of file PeakShapeDetectorBin.cpp.
References m_detectorBinList, and Mantid::DataObjects::PeakShapeBase::operator==().
radius()
std::optional< double > Mantid::DataObjects::PeakShapeDetectorBin::radius (RadiusType) const inline override virtual
PeakBase interface.
Implements Mantid::Geometry::PeakShape.
Definition at line 33 of file PeakShapeDetectorBin.h.
shapeName()
std::string Mantid::DataObjects::PeakShapeDetectorBin::shapeName () const override virtual
Get the peak shape.
Implements Mantid::Geometry::PeakShape.
Definition at line 56 of file PeakShapeDetectorBin.cpp.
References detectorBinShapeName().
toJSON()
std::string Mantid::DataObjects::PeakShapeDetectorBin::toJSON () const override virtual
PeakShape interface.
Implements Mantid::Geometry::PeakShape.
Definition at line 38 of file PeakShapeDetectorBin.cpp.
References Mantid::DataObjects::PeakShapeBase::buildCommon(), and m_detectorBinList.
Member Data Documentation
m_detectorBinList
std::vector<std::tuple<int32_t, double, double> > Mantid::DataObjects::PeakShapeDetectorBin::m_detectorBinList private
Definition at line 40 of file PeakShapeDetectorBin.h.
Referenced by operator==(), and toJSON().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/PeakShapeDetectorBin.h
Framework/DataObjects/src/PeakShapeDetectorBin.cpp