Mantid: Mantid::Algorithms::TimeAtSampleStrategyElastic Class Reference
Mantid::Algorithms::TimeAtSampleStrategyElastic Class Reference
TimeAtSampleStrategyElastic : Time at sample stragegy for elastic scattering.
#include <TimeAtSampleStrategyElastic.h>
Public Member Functions
Correction calculate (const size_t &workspace_index) const override
Calculate correction.
TimeAtSampleStrategyElastic (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Public Member Functions inherited from Mantid::Algorithms::TimeAtSampleStrategy
virtual Correction calculate (const size_t &workspace_index) const =0
virtual ~TimeAtSampleStrategy ()=default
Private Attributes
const Kernel::V3D m_beamDir
const API::SpectrumInfo & m_spectrumInfo
std::shared_ptr< const Mantid::API::MatrixWorkspace > m_ws
Detailed Description
TimeAtSampleStrategyElastic : Time at sample stragegy for elastic scattering.
Definition at line 23 of file TimeAtSampleStrategyElastic.h.
Constructor & Destructor Documentation
TimeAtSampleStrategyElastic()
Mantid::Algorithms::TimeAtSampleStrategyElastic::TimeAtSampleStrategyElastic (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Definition at line 24 of file TimeAtSampleStrategyElastic.cpp.
Member Function Documentation
calculate()
Correction Mantid::Algorithms::TimeAtSampleStrategyElastic::calculate (const size_t & workspace_index) const override virtual
Calculate correction.
Parameters
workspace_index
Returns
Correction
Implements Mantid::Algorithms::TimeAtSampleStrategy.
Definition at line 33 of file TimeAtSampleStrategyElastic.cpp.
References Mantid::API::SpectrumInfo::isMonitor(), Mantid::API::SpectrumInfo::l1(), Mantid::API::SpectrumInfo::l2(), m_beamDir, m_spectrumInfo, Mantid::API::SpectrumInfo::position(), Mantid::Kernel::V3D::scalar_prod(), and Mantid::API::SpectrumInfo::sourcePosition().
Referenced by Mantid::Algorithms::RebinByTimeAtSample::doHistogramming().
Member Data Documentation
m_beamDir
const Kernel::V3D Mantid::Algorithms::TimeAtSampleStrategyElastic::m_beamDir private
Definition at line 31 of file TimeAtSampleStrategyElastic.h.
Referenced by calculate().
m_spectrumInfo
const API::SpectrumInfo& Mantid::Algorithms::TimeAtSampleStrategyElastic::m_spectrumInfo private
Definition at line 30 of file TimeAtSampleStrategyElastic.h.
Referenced by calculate().
m_ws
std::shared_ptr<const Mantid::API::MatrixWorkspace> Mantid::Algorithms::TimeAtSampleStrategyElastic::m_ws private
Definition at line 29 of file TimeAtSampleStrategyElastic.h.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/TimeAtSampleStrategyElastic.h
Framework/Algorithms/src/TimeAtSampleStrategyElastic.cpp