Mantid: Mantid::API::FileBackedExperimentInfo Class Reference
Mantid::API::FileBackedExperimentInfo Class Reference
Implements a lazy-loading mechanism for the experimental information stored in a NeXus file.
#include <FileBackedExperimentInfo.h>
Public Member Functions
ExperimentInfo * cloneExperimentInfo () const override
This clones the FileBackedExperimentInfo and will not cause a load of the information.
FileBackedExperimentInfo (std::string filename, std::string nxpath)
Create an object based on a NeXus file and path.
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, ::NeXus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (const std::string &nxFilename, ::NeXus::File *file, std::string &parameterStr, const Mantid::Kernel::NexusHDF5Descriptor &fileInfo, const std::string &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, ::NeXus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, ::NeXus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (::NeXus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instument group if found there.
void loadSampleAndLogInfoNexus (::NeXus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (::NeXus::File *file, const Mantid::Kernel::NexusHDF5Descriptor &fileInfo, const std::string &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (::NeXus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (::NeXus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Private Member Functions
void populateFromFile () const
Populate this object with the data from the file.
void populateIfNotLoaded () const override
Check if the object has been populated and load the information if it has not.
Private Attributes
std::string m_filename
bool m_loaded
std::string m_nxpath
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
virtual void updateCachedDetectorGrouping (const size_t index) const
Update detector grouping for spectrum with given index.
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Detailed Description
Implements a lazy-loading mechanism for the experimental information stored in a NeXus file.
Definition at line 19 of file FileBackedExperimentInfo.h.
Constructor & Destructor Documentation
FileBackedExperimentInfo()
Mantid::API::FileBackedExperimentInfo::FileBackedExperimentInfo (std::string filename, std::string nxpath)
Create an object based on a NeXus file and path.
Parameters
filename The full path to the file
nxpath Path to the location of the experiment information
Definition at line 30 of file FileBackedExperimentInfo.cpp.
Member Function Documentation
cloneExperimentInfo()
ExperimentInfo * Mantid::API::FileBackedExperimentInfo::cloneExperimentInfo () const override virtual
This clones the FileBackedExperimentInfo and will not cause a load of the information.
Returns
A clone of the object.
Reimplemented from Mantid::API::ExperimentInfo.
Definition at line 38 of file FileBackedExperimentInfo.cpp.
populateFromFile()
void Mantid::API::FileBackedExperimentInfo::populateFromFile () const private
Populate this object with the data from the file.
Definition at line 53 of file FileBackedExperimentInfo.cpp.
References Mantid::API::ExperimentInfo::loadExperimentInfoNexus(), m_filename, m_loaded, m_nxpath, and Mantid::API::ExperimentInfo::readParameterMap().
Referenced by populateIfNotLoaded().
populateIfNotLoaded()
void Mantid::API::FileBackedExperimentInfo::populateIfNotLoaded () const override private virtual
Check if the object has been populated and load the information if it has not.
Reimplemented from Mantid::API::ExperimentInfo.
Definition at line 44 of file FileBackedExperimentInfo.cpp.
References m_loaded, and populateFromFile().
Member Data Documentation
m_filename
std::string Mantid::API::FileBackedExperimentInfo::m_filename private
Definition at line 29 of file FileBackedExperimentInfo.h.
Referenced by populateFromFile().
m_loaded
bool Mantid::API::FileBackedExperimentInfo::m_loaded mutable private
Definition at line 28 of file FileBackedExperimentInfo.h.
Referenced by populateFromFile(), and populateIfNotLoaded().
m_nxpath
std::string Mantid::API::FileBackedExperimentInfo::m_nxpath private
Definition at line 30 of file FileBackedExperimentInfo.h.
Referenced by populateFromFile().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/FileBackedExperimentInfo.h
Framework/API/src/FileBackedExperimentInfo.cpp