Mantid: Mantid::CurveFitting::EigenJacobian Class Reference
Mantid::CurveFitting::EigenJacobian Class Reference
Two implementations of Jacobian.
#include <EigenJacobian.h>
Public Member Functions
void addNumberToColumn (const double &value, const size_t &iActiveP) override
overwrite base method
EigenJacobian (const API::IFunction &fun, const size_t ny)
Constructor.
double get (size_t iY, size_t iP) override
overwrite base method
map_type & getJ ()
Get the map to the jacobian.
EigenMatrix & matrix ()
void set (size_t iY, size_t iP, double value) override
overwrite base method
void zero () override
overwrite base method
Public Member Functions inherited from Mantid::API::Jacobian
virtual ~Jacobian ()=default
Virtual destructor.
Private Attributes
std::vector< int > m_index
Maps declared indeces to active. For fixed (tied) parameters holds -1.
EigenMatrix m_J
The internal jacobian matrix.
Detailed Description
Two implementations of Jacobian.
Author
Anders Markvardsen, ISIS, RAL
Date
14/05/2010
Definition at line 23 of file EigenJacobian.h.
Constructor & Destructor Documentation
EigenJacobian()
Mantid::CurveFitting::EigenJacobian::EigenJacobian (const API::IFunction & fun, const size_t ny) inline
Constructor.
Parameters
fun :: Function which derivatives to be stored in this Jacobian.
ny :: Size of the fitting data.
Definition at line 33 of file EigenJacobian.h.
References Mantid::API::IFunction::isActive(), m_index, m_J, Mantid::API::IFunction::nParams(), and Mantid::CurveFitting::EigenMatrix::resize().
Member Function Documentation
addNumberToColumn()
void Mantid::CurveFitting::EigenJacobian::addNumberToColumn (const double & value, const size_t & iActiveP) inline override
overwrite base method
Parameters
value :: the value
iActiveP :: the index of the parameter
Exceptions
runtime_error Thrown if column of Jacobian to add number to does not exist
Definition at line 55 of file EigenJacobian.h.
References m_J, Mantid::CurveFitting::EigenMatrix::mutator(), Mantid::CurveFitting::EigenMatrix::size1(), Mantid::CurveFitting::EigenMatrix::size2(), and value.
get()
double Mantid::CurveFitting::EigenJacobian::get (size_t iY, size_t iP) inline override virtual
overwrite base method
Implements Mantid::API::Jacobian.
Definition at line 74 of file EigenJacobian.h.
References Mantid::CurveFitting::EigenMatrix::get(), m_index, and m_J.
Referenced by Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::getCovarianceMatrix().
getJ()
map_type & Mantid::CurveFitting::EigenJacobian::getJ () inline
Get the map to the jacobian.
Definition at line 48 of file EigenJacobian.h.
References m_J, and Mantid::CurveFitting::EigenMatrix::mutator().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncFitting::calActiveCovarianceMatrix().
matrix()
EigenMatrix & Mantid::CurveFitting::EigenJacobian::matrix () inline
Definition at line 45 of file EigenJacobian.h.
References m_J.
set()
void Mantid::CurveFitting::EigenJacobian::set (size_t iY, size_t iP, double value) inline override virtual
overwrite base method
Implements Mantid::API::Jacobian.
Definition at line 68 of file EigenJacobian.h.
References m_index, m_J, Mantid::CurveFitting::EigenMatrix::set(), and value.
zero()
void Mantid::CurveFitting::EigenJacobian::zero () inline override virtual
overwrite base method
Implements Mantid::API::Jacobian.
Definition at line 81 of file EigenJacobian.h.
References m_J, and Mantid::CurveFitting::EigenMatrix::zero().
Member Data Documentation
m_index
std::vector<int> Mantid::CurveFitting::EigenJacobian::m_index private
Maps declared indeces to active. For fixed (tied) parameters holds -1.
Definition at line 27 of file EigenJacobian.h.
Referenced by EigenJacobian(), get(), and set().
m_J
EigenMatrix Mantid::CurveFitting::EigenJacobian::m_J private
The internal jacobian matrix.
Definition at line 25 of file EigenJacobian.h.
Referenced by addNumberToColumn(), EigenJacobian(), get(), getJ(), matrix(), set(), and zero().
The documentation for this class was generated from the following file:
Framework/CurveFitting/inc/MantidCurveFitting/EigenJacobian.h