Mantid: Mantid::Algorithms::RectangularBeamProfile Class Reference
Mantid::Algorithms::RectangularBeamProfile Class Reference final
Defines a flat, rectangular beam profile that has a width, height and center point.
#include <RectangularBeamProfile.h>
Public Member Functions
Geometry::BoundingBox defineActiveRegion (const Geometry::BoundingBox &) const override
Compute a region that defines how the beam illuminates the given sample/can.
IBeamProfile::Ray generatePoint (Kernel::PseudoRandomNumberGenerator &rng) const override
Generate a random point within the beam profile using the supplied random number source.
IBeamProfile::Ray generatePoint (Kernel::PseudoRandomNumberGenerator &rng, const Geometry::BoundingBox &bounds) const override
Generate a random point on the profile that is within the given bounding area.
Kernel::V3D maxPoint () const
Returns the max point of the profile.
Kernel::V3D minPoint () const
Returns the min point of the profile.
RectangularBeamProfile (const Geometry::ReferenceFrame &frame, const Kernel::V3D &center, double width, double height)
Construct a beam profile.
Public Member Functions inherited from Mantid::Algorithms::IBeamProfile
Geometry::IObject_sptr getIntersectionWithSample (const Geometry::IObject &sample) const
Get the intersection of the beam with the sample.
IBeamProfile ()=default
IBeamProfile (const Kernel::V3D center)
Construct a new IBeamProfile::IBeamProfile object.
virtual ~IBeamProfile ()=default
Private Attributes
Kernel::V3D m_beamDir
const unsigned short m_beamIdx
const double m_height
const unsigned short m_horIdx
Kernel::V3D m_min
const unsigned short m_upIdx
const double m_width
Additional Inherited Members
Protected Attributes inherited from Mantid::Algorithms::IBeamProfile
Kernel::V3D m_beamCenter
Detailed Description
Defines a flat, rectangular beam profile that has a width, height and center point.
The profile is assumed infinitely thin.
Definition at line 25 of file RectangularBeamProfile.h.
Constructor & Destructor Documentation
RectangularBeamProfile()
Mantid::Algorithms::RectangularBeamProfile::RectangularBeamProfile (const Geometry::ReferenceFrame & frame, const Kernel::V3D & center, double width, double height)
Construct a beam profile.
Parameters
frame Defines the direction of the beam, up and horizontal
center V3D defining the central point of the rectangle
width Width of beam
height Height of beam
Definition at line 26 of file RectangularBeamProfile.cpp.
References height, m_beamDir, m_beamIdx, m_horIdx, m_min, and m_upIdx.
Member Function Documentation
defineActiveRegion()
Geometry::BoundingBox Mantid::Algorithms::RectangularBeamProfile::defineActiveRegion (const Geometry::BoundingBox & sampleBox) const override virtual
Compute a region that defines how the beam illuminates the given sample/can.
Parameters
sampleBox A reference to the bounding box of the sample
Returns
A BoundingBox defining the active region
Implements Mantid::Algorithms::IBeamProfile.
Definition at line 81 of file RectangularBeamProfile.cpp.
References m_beamIdx, m_height, m_horIdx, m_min, m_upIdx, m_width, Mantid::Geometry::BoundingBox::maxPoint(), Mantid::Geometry::BoundingBox::minPoint(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
generatePoint() [1/2]
IBeamProfile::Ray Mantid::Algorithms::RectangularBeamProfile::generatePoint (Kernel::PseudoRandomNumberGenerator & rng) const override virtual
Generate a random point within the beam profile using the supplied random number source.
Parameters
rng A reference to a random number generator
Returns
An IBeamProfile::Ray describing the start and direction
Implements Mantid::Algorithms::IBeamProfile.
Definition at line 42 of file RectangularBeamProfile.cpp.
References m_beamDir, m_beamIdx, m_height, m_horIdx, m_min, m_upIdx, m_width, and Mantid::Kernel::PseudoRandomNumberGenerator::nextValue().
Referenced by generatePoint().
generatePoint() [2/2]
IBeamProfile::Ray Mantid::Algorithms::RectangularBeamProfile::generatePoint (Kernel::PseudoRandomNumberGenerator & rng, const Geometry::BoundingBox & bounds) const override virtual
Generate a random point on the profile that is within the given bounding area.
If the point is outside the area then it is pulled to the boundary of the bounding area.
Parameters
rng A reference to a random number generator
bounds A reference to the bounding area that defines the maximum allowed region for the generated point.
Returns
An IBeamProfile::Ray describing the start and direction
Implements Mantid::Algorithms::IBeamProfile.
Definition at line 59 of file RectangularBeamProfile.cpp.
References generatePoint(), m_horIdx, m_upIdx, Mantid::Geometry::BoundingBox::maxPoint(), and Mantid::Geometry::BoundingBox::minPoint().
maxPoint()
Kernel::V3D Mantid::Algorithms::RectangularBeamProfile::maxPoint () const inline
Returns the max point of the profile.
Definition at line 36 of file RectangularBeamProfile.h.
minPoint()
Kernel::V3D Mantid::Algorithms::RectangularBeamProfile::minPoint () const inline
Returns the min point of the profile.
Definition at line 34 of file RectangularBeamProfile.h.
References m_min.
Member Data Documentation
m_beamDir
Kernel::V3D Mantid::Algorithms::RectangularBeamProfile::m_beamDir private
Definition at line 50 of file RectangularBeamProfile.h.
Referenced by generatePoint(), and RectangularBeamProfile().
m_beamIdx
const unsigned short Mantid::Algorithms::RectangularBeamProfile::m_beamIdx private
Definition at line 45 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), generatePoint(), and RectangularBeamProfile().
m_height
const double Mantid::Algorithms::RectangularBeamProfile::m_height private
Definition at line 48 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), and generatePoint().
m_horIdx
const unsigned short Mantid::Algorithms::RectangularBeamProfile::m_horIdx private
Definition at line 46 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), generatePoint(), generatePoint(), and RectangularBeamProfile().
m_min
Kernel::V3D Mantid::Algorithms::RectangularBeamProfile::m_min private
Definition at line 49 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), generatePoint(), and RectangularBeamProfile().
m_upIdx
const unsigned short Mantid::Algorithms::RectangularBeamProfile::m_upIdx private
Definition at line 44 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), generatePoint(), generatePoint(), and RectangularBeamProfile().
m_width
const double Mantid::Algorithms::RectangularBeamProfile::m_width private
Definition at line 47 of file RectangularBeamProfile.h.
Referenced by defineActiveRegion(), and generatePoint().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h
Framework/Algorithms/src/SampleCorrections/RectangularBeamProfile.cpp