Mantid: Mantid::API::FunctionHandler Class Reference
Mantid::API::FunctionHandler Class Reference abstract
Classes inherited from FunctionHandler will handle the function.
#include <IFunction.h>
Public Member Functions
IFunction_sptr function () const
Return the handled function.
FunctionHandler (const FunctionHandler &)=delete
Delete copy constructor and copy assignment operator.
FunctionHandler (IFunction_sptr fun)
Constructor.
virtual void init ()=0
abstract init method. It is called after setting handler to the function
FunctionHandler & operator= (const FunctionHandler &)=delete
virtual ~FunctionHandler ()=default
Virtual destructor.
Protected Attributes
IFunction_sptr m_fun
pointer to the handled function
Detailed Description
Classes inherited from FunctionHandler will handle the function.
The intended purpose is to help with displaying nested composite functions in a tree view. This way a display handler shows only single function and there is no need to duplicate the function tree structure.
Definition at line 743 of file IFunction.h.
Constructor & Destructor Documentation
FunctionHandler() [1/2]
Mantid::API::FunctionHandler::FunctionHandler (IFunction_sptr fun) inline
Constructor.
Definition at line 746 of file IFunction.h.
FunctionHandler() [2/2]
Mantid::API::FunctionHandler::FunctionHandler (const FunctionHandler &) delete
Delete copy constructor and copy assignment operator.
~FunctionHandler()
virtual Mantid::API::FunctionHandler::~FunctionHandler () virtual default
Virtual destructor.
Member Function Documentation
function()
IFunction_sptr Mantid::API::FunctionHandler::function () const inline
Return the handled function.
Definition at line 755 of file IFunction.h.
References m_fun.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), MantidQt::MantidWidgets::FitPropertyBrowser::addTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), MantidQt::MantidWidgets::PropertyHandler::calcBase(), MantidQt::MantidWidgets::PropertyHandler::changeType(), MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie(), MantidQt::MantidWidgets::PropertyHandler::findFunction(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), MantidQt::MantidWidgets::PropertyHandler::functionName(), MantidQt::MantidWidgets::PropertyHandler::functionPrefix(), MantidQt::MantidWidgets::PropertyHandler::initAttributes(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), MantidQt::MantidWidgets::PropertyHandler::removeFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::setCentre(), MantidQt::MantidWidgets::FitPropertyBrowser::setFwhm(), MantidQt::MantidWidgets::FitPropertyBrowser::setHeight(), MantidQt::MantidWidgets::PropertyHandler::updateAttribute(), MantidQt::MantidWidgets::PropertyHandler::updateError(), MantidQt::MantidWidgets::PropertyHandler::updateParameter(), and MantidQt::MantidWidgets::PropertyHandler::updateStructureTooltip().
init()
virtual void Mantid::API::FunctionHandler::init () pure virtual
abstract init method. It is called after setting handler to the function
Implemented in MantidQt::MantidWidgets::PropertyHandler.
operator=()
FunctionHandler & Mantid::API::FunctionHandler::operator= (const FunctionHandler &) delete
Member Data Documentation
m_fun
IFunction_sptr Mantid::API::FunctionHandler::m_fun protected
pointer to the handled function
Definition at line 758 of file IFunction.h.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addConstraint(), MantidQt::MantidWidgets::PropertyHandler::fit(), MantidQt::MantidWidgets::PropertyHandler::fix(), function(), MantidQt::MantidWidgets::PropertyHandler::init(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), MantidQt::MantidWidgets::PropertyHandler::removeConstraint(), MantidQt::MantidWidgets::PropertyHandler::removeTie(), MantidQt::MantidWidgets::PropertyHandler::renameChildren(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), and MantidQt::MantidWidgets::PropertyHandler::setParameter().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IFunction.h