Mantid: Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares Class Reference
Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares Class Reference
Cost function for least squares.
#include <CostFuncLeastSquares.h>
Public Member Functions
CostFuncLeastSquares ()
Constructor.
std::string name () const override
Get name of minimizer.
std::string shortName () const override
Get short name of minimizer - useful for say labels in guis.
Public Member Functions inherited from Mantid::CurveFitting::CostFunctions::CostFuncFitting
void applyTies ()
Apply ties in the fitting function.
virtual void calCovarianceMatrix (EigenMatrix &covar, double epsrel=1e-8)
Calculates covariance matrix.
virtual void calFittingErrors (const EigenMatrix &covar, double chi2)
Calculate fitting errors.
CostFuncFitting ()
Constructor.
virtual void deriv (std::vector< double > &der) const override
Calculate the derivatives of the cost function.
void drop ()
Discard saved parameters, derivatives and hessian.
const EigenVector & getDeriv () const
Return cached or calculate the drivatives.
API::FunctionDomain_sptr getDomain () const
Get the domain the fitting function is applied to.
virtual API::IFunction_sptr getFittingFunction () const
Get fitting function.
const EigenMatrix & getHessian () const
Return cached or calculate the Hessian.
double getParameter (size_t i) const override
Get i-th parameter.
void getParameters (EigenVector &params) const
Get all parameters into a GSLVector.
API::FunctionValues_sptr getValues () const
Get FunctionValues where function values are stored.
size_t nParams () const override
Number of parameters.
std::string parameterName (size_t i) const
Get name of i-th parameter.
void pop ()
Restore saved parameters, derivatives and hessian.
void push ()
Save current parameters, derivatives and hessian.
void reset () const
Reset the fitting function (neccessary if parameters get fixed/unfixed)
virtual void setFittingFunction (API::IFunction_sptr function, API::FunctionDomain_sptr domain, API::FunctionValues_sptr values)
Set fitting function.
void setIgnoreInvalidData (bool ignoreInvalidData)
Set to ignore invalid data.
void setParameter (size_t i, const double &value) override
Set i-th parameter.
void setParameters (const EigenVector &params)
Set all parameters.
virtual double val () const override
Calculate value of cost function.
virtual double valAndDeriv (std::vector< double > &der) const override
Calculate the value and the derivatives of the cost function.
virtual double valDerivHessian (bool evalDeriv=true, bool evalHessian=true) const
Calculate the value, the first and the second derivatives of the cost function.
Public Member Functions inherited from Mantid::API::ICostFunction
virtual ~ICostFunction ()=default
Virtual destructor.
Protected Member Functions
void addVal (API::FunctionDomain_sptr domain, API::FunctionValues_sptr values) const override
Add a contribution to the cost function value from the fitting function evaluated on a particular domain.
void addValDerivHessian (API::IFunction_sptr function, API::FunctionDomain_sptr domain, API::FunctionValues_sptr values, bool evalDeriv=true, bool evalHessian=true) const override
Update the cost function, derivatives and hessian by adding values calculated on a domain.
void calActiveCovarianceMatrix (EigenMatrix &covar, double epsrel=1e-8) override
Calculates covariance matrix for fitting function's active parameters.
virtual std::vector< double > getFitWeights (API::FunctionValues_sptr values) const
Get mapped weights from FunctionValues.
virtual void updateValidateFitWeights () override
Validates current fit weights and raise errors when necessary.
Protected Member Functions inherited from Mantid::CurveFitting::CostFunctions::CostFuncFitting
void calTransformationMatrixNumerically (EigenMatrix &tm)
Calculate the transformation matrix T by numeric differentiation.
void checkValidity () const
Throw a runtime_error if function is invalid.
bool isValid () const
Is the function set and valid?
void setDirty ()
Set all dirty flags.
void validateNegativeFitWeights ()
Functionality to validate negative fit weights.
Protected Attributes
double m_factor
Protected Attributes inherited from Mantid::CurveFitting::CostFunctions::CostFuncFitting
EigenVector m_der
bool m_dirtyDeriv
dirty derivatives flag
bool m_dirtyHessian
dirty hessian flag
bool m_dirtyVal
dirty value flag
API::FunctionDomain_sptr m_domain
Shared pointer to the function domain.
API::IFunction_sptr m_function
Shared pointer to the fitting function.
EigenMatrix m_hessian
bool m_ignoreInvalidData
bool m_includePenalty
Flag to include constraint in cost function value.
std::vector< size_t > m_indexMap
maps the cost function's parameters to the ones of the fitting function.
size_t m_numberFunParams
Number of all parameters in the fitting function.
bool m_pushed
EigenVector m_pushedParams
double m_pushedValue
double m_value
API::FunctionValues_sptr m_values
Shared poinetr to the function values.
Detailed Description
Cost function for least squares.
Author
Anders Markvardsen, ISIS, RAL
Date
11/05/2010
Definition at line 24 of file CostFuncLeastSquares.h.
Constructor & Destructor Documentation
CostFuncLeastSquares()
Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::CostFuncLeastSquares ()
Constructor.
Definition at line 32 of file CostFuncLeastSquares.cpp.
Member Function Documentation
addVal()
void Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addVal (API::FunctionDomain_sptr domain, API::FunctionValues_sptr values) const override protected virtual
Add a contribution to the cost function value from the fitting function evaluated on a particular domain.
Parameters
domain :: A domain
values :: Values
Implements Mantid::CurveFitting::CostFunctions::CostFuncFitting.
Definition at line 39 of file CostFuncLeastSquares.cpp.
References getFitWeights(), m_factor, Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_function, Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_value, PARALLEL_ATOMIC, and Mantid::CurveFitting::CostFunctions::CostFuncFitting::val().
Referenced by Mantid::CurveFitting::SeqDomain::rwpVal().
addValDerivHessian()
void Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian (API::IFunction_sptr function, API::FunctionDomain_sptr domain, API::FunctionValues_sptr values, bool evalDeriv = true, bool evalHessian = true) const override protected virtual
Update the cost function, derivatives and hessian by adding values calculated on a domain.
Parameters
function :: Function to use to calculate the value and the derivatives
domain :: The domain.
values :: The fit function values
evalDeriv :: Flag to evaluate the derivatives
evalHessian :: Flag to evaluate the Hessian
Implements Mantid::CurveFitting::CostFunctions::CostFuncFitting.
Definition at line 65 of file CostFuncLeastSquares.cpp.
References Mantid::Geometry::d, Mantid::CurveFitting::EigenVector::get(), Mantid::CurveFitting::EigenMatrix::get(), Mantid::API::Jacobian::get(), getFitWeights(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_der, Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_hessian, Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_value, PARALLEL_ATOMIC, PARALLEL_CRITICAL, Mantid::CurveFitting::EigenVector::set(), Mantid::CurveFitting::EigenMatrix::set(), Mantid::CurveFitting::EigenVector::size(), Mantid::CurveFitting::EigenMatrix::size1(), Mantid::CurveFitting::EigenMatrix::size2(), UNUSED_ARG, and Mantid::Geometry::y.
Referenced by Mantid::CurveFitting::SeqDomain::rwpValDerivHessian().
calActiveCovarianceMatrix()
void Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix (EigenMatrix & covar, double epsrel = 1e-8) override protected virtual
Calculates covariance matrix for fitting function's active parameters.
Parameters
covar :: Output cavariance matrix.
epsrel :: Tolerance.
Reimplemented from Mantid::CurveFitting::CostFunctions::CostFuncFitting.
Reimplemented in Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares.
Definition at line 158 of file CostFuncLeastSquares.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::CurveFitting::EigenMatrix::get(), Mantid::CurveFitting::EigenMatrix::invert(), Mantid::Kernel::Logger::is(), Mantid::CurveFitting::EigenMatrix::isEmpty(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::m_hessian, Mantid::CurveFitting::EigenMatrix::size1(), Mantid::CurveFitting::EigenMatrix::size2(), UNUSED_ARG, and Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix().
getFitWeights()
std::vector< double > Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::getFitWeights (API::FunctionValues_sptr values) const protected virtual
Get mapped weights from FunctionValues.
Reimplemented in Mantid::CurveFitting::CostFunctions::CostFuncRwp, and Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares.
Definition at line 144 of file CostFuncLeastSquares.cpp.
Referenced by addVal(), and addValDerivHessian().
name()
std::string Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::name () const inline override virtual
Get name of minimizer.
Implements Mantid::API::ICostFunction.
Reimplemented in Mantid::CurveFitting::CostFunctions::CostFuncRwp, and Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares.
Definition at line 30 of file CostFuncLeastSquares.h.
shortName()
std::string Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::shortName () const inline override virtual
Get short name of minimizer - useful for say labels in guis.
Reimplemented from Mantid::API::ICostFunction.
Reimplemented in Mantid::CurveFitting::CostFunctions::CostFuncRwp, and Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares.
Definition at line 33 of file CostFuncLeastSquares.h.
updateValidateFitWeights()
void Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::updateValidateFitWeights () override protected virtual
Validates current fit weights and raise errors when necessary.
Reimplemented from Mantid::CurveFitting::CostFunctions::CostFuncFitting.
Reimplemented in Mantid::CurveFitting::CostFunctions::CostFuncRwp, and Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares.
Definition at line 199 of file CostFuncLeastSquares.cpp.
References Mantid::CurveFitting::CostFunctions::CostFuncFitting::validateNegativeFitWeights().
Member Data Documentation
m_factor
double Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::m_factor protected
Definition at line 48 of file CostFuncLeastSquares.h.
Referenced by addVal().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/CostFunctions/CostFuncLeastSquares.h
Framework/CurveFitting/src/CostFunctions/CostFuncLeastSquares.cpp