Mantid: Mantid::WorkflowAlgorithms::ComputeSensitivity Class Reference
Mantid::WorkflowAlgorithms::ComputeSensitivity Class Reference
Workflow algorithm to compute a patched sensitivity correction for EQSANS.
#include <ComputeSensitivity.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
void exec () override
Execution code.
void init () override
Initialisation code.
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
Workflow algorithm to compute a patched sensitivity correction for EQSANS.
Definition at line 19 of file ComputeSensitivity.h.
Member Function Documentation
category()
const std::string Mantid::WorkflowAlgorithms::ComputeSensitivity::category () const inline override
Algorithm's category for identification.
Definition at line 28 of file ComputeSensitivity.h.
exec()
void Mantid::WorkflowAlgorithms::ComputeSensitivity::exec () override private
Execution code.
Definition at line 40 of file ComputeSensitivity.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::API::GenericDataProcessorAlgorithm< Base >::getProcessProperties(), and Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue().
init()
void Mantid::WorkflowAlgorithms::ComputeSensitivity::init () override private
Initialisation code.
Definition at line 28 of file ComputeSensitivity.cpp.
References Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::Load, Mantid::API::PropertyMode::Optional, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::WorkflowAlgorithms::ComputeSensitivity::name () const inline override
Algorithm's name.
Definition at line 22 of file ComputeSensitivity.h.
summary()
const std::string Mantid::WorkflowAlgorithms::ComputeSensitivity::summary () const inline override
Summary of algorithms purpose.
Definition at line 24 of file ComputeSensitivity.h.
version()
int Mantid::WorkflowAlgorithms::ComputeSensitivity::version () const inline override
Algorithm's version.
Definition at line 26 of file ComputeSensitivity.h.
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/ComputeSensitivity.h
Framework/WorkflowAlgorithms/src/ComputeSensitivity.cpp