Mantid: Mantid::Geometry::RenderingHelpers Namespace Reference
Mantid::Geometry::RenderingHelpers Namespace Reference
Functions
MANTID_GEOMETRY_DLL void renderBitmap (const RectangularDetector &rectDet)
Renders a Bitmap (used for rendering RectangularDetector)
MANTID_GEOMETRY_DLL void renderIObjComponent (const IObjComponent &objComp)
Render IObjComponent.
MANTID_GEOMETRY_DLL void renderShape (const detail::ShapeInfo &shapeInfo)
Renders a sphere, cuboid, hexahedron, cone or cylinder.
MANTID_GEOMETRY_DLL void renderStructured (const StructuredDetector &structDet)
Renders structured geometry (used for rendering StructuredDetector)
MANTID_GEOMETRY_DLL void renderTriangulated (detail::GeometryTriangulator &triangulator)
Render Traingulated Surface.
Function Documentation
renderBitmap()
MANTID_GEOMETRY_DLL void Mantid::Geometry::RenderingHelpers::renderBitmap (const RectangularDetector & rectDet)
Renders a Bitmap (used for rendering RectangularDetector)
renderIObjComponent()
void Mantid::Geometry::RenderingHelpers::renderIObjComponent (const IObjComponent & objComp)
Render IObjComponent.
Definition at line 314 of file RenderingHelpersOpenGL.cpp.
Referenced by Mantid::Geometry::GeometryHandler::render().
renderShape()
void Mantid::Geometry::RenderingHelpers::renderShape (const detail::ShapeInfo & shapeInfo)
Renders a sphere, cuboid, hexahedron, cone or cylinder.
Definition at line 327 of file RenderingHelpersOpenGL.cpp.
References Mantid::Geometry::detail::ShapeInfo::CONE, Mantid::Geometry::detail::ShapeInfo::CUBOID, Mantid::Geometry::detail::ShapeInfo::CYLINDER, Mantid::Geometry::detail::ShapeInfo::HEXAHEDRON, Mantid::Geometry::detail::ShapeInfo::shape(), and Mantid::Geometry::detail::ShapeInfo::SPHERE.
Referenced by Mantid::Geometry::GeometryHandler::render().
renderStructured()
MANTID_GEOMETRY_DLL void Mantid::Geometry::RenderingHelpers::renderStructured (const StructuredDetector & structDet)
Renders structured geometry (used for rendering StructuredDetector)
renderTriangulated()
void Mantid::Geometry::RenderingHelpers::renderTriangulated (detail::GeometryTriangulator & triangulator)
Render Traingulated Surface.
Definition at line 316 of file RenderingHelpersOpenGL.cpp.
Referenced by Mantid::Geometry::GeometryHandler::render().