Mantid: MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber Class Reference
MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber Class Reference abstract
#include <IJobTreeView.h>
Public Member Functions
virtual void notifyAppendAndEditAtChildRowRequested ()=0
virtual void notifyAppendAndEditAtRowBelowRequested ()=0
virtual void notifyCellTextChanged (RowLocation const &itemIndex, int column, std::string const &oldValue, std::string const &newValue)=0
virtual void notifyCopyRowsRequested ()=0
virtual void notifyCutRowsRequested ()=0
virtual void notifyEditAtRowAboveRequested ()=0
virtual void notifyFilterReset ()=0
virtual void notifyPasteRowsRequested ()=0
virtual void notifyRemoveRowsRequested (std::vector< RowLocation > const &locationsOfRowsToRemove)=0
virtual void notifyRowInserted (RowLocation const &newRowLocation)=0
virtual void notifySelectionChanged ()=0
virtual ~JobTreeViewSubscriber ()=default
Detailed Description
Definition at line 22 of file IJobTreeView.h.
Constructor & Destructor Documentation
~JobTreeViewSubscriber()
virtual MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::~JobTreeViewSubscriber () virtual default
Member Function Documentation
notifyAppendAndEditAtChildRowRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyAppendAndEditAtChildRowRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtChildRowRequested().
notifyAppendAndEditAtRowBelowRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyAppendAndEditAtRowBelowRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtRowBelowRequested().
notifyCellTextChanged()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCellTextChanged (RowLocation const & itemIndex, int column, std::string const & oldValue, std::string const & newValue) pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::commitData().
notifyCopyRowsRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCopyRowsRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::copySelectedRequested().
notifyCutRowsRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCutRowsRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::cutSelectedRequested().
notifyEditAtRowAboveRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyEditAtRowAboveRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::editAtRowAboveRequested().
notifyFilterReset()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyFilterReset () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::resetFilter().
notifyPasteRowsRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyPasteRowsRequested () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::pasteSelectedRequested().
notifyRemoveRowsRequested()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRemoveRowsRequested (std::vector< RowLocation > const & locationsOfRowsToRemove) pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::removeSelectedRequested().
notifyRowInserted()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRowInserted (RowLocation const & newRowLocation) pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtChildRow(), MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtRowBelow(), and MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult().
notifySelectionChanged()
virtual void MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifySelectionChanged () pure virtual
Implemented in MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::selectionChanged().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/IJobTreeView.h