Mantid: Mantid::Kernel::Exception::InternetError Class Reference
Mantid::Kernel::Exception::InternetError Class Reference final
Exception thrown when error occurs accessing an internet resource.
#include <Exception.h>
Public Member Functions
const int & errorCode () const
Writes out the range and limits.
InternetError (const std::string &message, const int &errorCode=0)
Constructor.
const char * what () const noexcept override
Overloaded reporting method.
Private Attributes
int m_errorCode
The message reported by what()
std::string outMessage
The message returned by what()
Detailed Description
Exception thrown when error occurs accessing an internet resource.
Author
Nick Draper, Tessella
Date
13/11/2013
Definition at line 321 of file Exception.h.
Constructor & Destructor Documentation
InternetError()
Mantid::Kernel::Exception::InternetError::InternetError (const std::string & message, const int & errorCode = 0)
Constructor.
Parameters
message :: The error message
errorCode :: The HTTP error code if available
Definition at line 296 of file Exception.cpp.
References errorCode(), m_errorCode, and outMessage.
Member Function Documentation
errorCode()
const int & Mantid::Kernel::Exception::InternetError::errorCode () const
Writes out the range and limits.
Returns
the error string
Definition at line 317 of file Exception.cpp.
References m_errorCode.
Referenced by Mantid::DataHandling::CheckMantidVersion::exec(), InternetError(), Mantid::DataHandling::DownloadInstrument::processRepository(), Mantid::Kernel::ErrorReporter::sendErrorReport(), Mantid::Kernel::ErrorReporter::sendReport(), and Mantid::Kernel::UsageServiceImpl::sendReport().
what()
const char * Mantid::Kernel::Exception::InternetError::what () const override noexcept
Overloaded reporting method.
Writes out the range and limits.
Returns
the error string
Definition at line 311 of file Exception.cpp.
References outMessage.
Referenced by Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::Kernel::ErrorReporter::sendErrorReport(), Mantid::Kernel::ErrorReporter::sendReport(), Mantid::Kernel::UsageServiceImpl::sendReport(), and Mantid::DataHandling::ISISDataArchive::sendRequest().
Member Data Documentation
m_errorCode
int Mantid::Kernel::Exception::InternetError::m_errorCode private
The message reported by what()
Definition at line 325 of file Exception.h.
Referenced by errorCode(), and InternetError().
outMessage
std::string Mantid::Kernel::Exception::InternetError::outMessage private
The message returned by what()
Definition at line 324 of file Exception.h.
Referenced by InternetError(), and what().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Exception.h
Framework/Kernel/src/Exception.cpp