Mantid: Mantid::DataHandling::H5Util Namespace Reference
Mantid::DataHandling::H5Util Namespace Reference
Functions
Group createGroupCanSAS (Group &group, const std::string &name, const std::string &nxtype, const std::string &cstype)
MANTID_DATAHANDLING_DLL H5::Group createGroupCanSAS (H5::Group &group, const std::string &name, const std::string &nxtype, const std::string &cstype)
MANTID_DATAHANDLING_DLL H5::Group createGroupCanSAS (H5::H5File &file, const std::string &name, const std::string &nxtype, const std::string &cstype)
Group createGroupCanSAS (H5File &file, const std::string &name, const std::string &nxtype, const std::string &cstype)
Group createGroupNXS (Group &group, const std::string &name, const std::string &nxtype)
MANTID_DATAHANDLING_DLL H5::Group createGroupNXS (H5::Group &group, const std::string &name, const std::string &nxtype)
MANTID_DATAHANDLING_DLL H5::Group createGroupNXS (H5::H5File &file, const std::string &name, const std::string &nxtype)
Group createGroupNXS (H5File &file, const std::string &name, const std::string &nxtype)
MANTID_DATAHANDLING_DLL H5::DataSpace getDataSpace (const size_t length)
H5Util : TODO: DESCRIPTION.
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< double > &data)
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< float > &data)
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< int32_t > &data)
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< int64_t > &data)
template<typename NumT >
H5::DataSpace getDataSpace (const std::vector< NumT > &data)
Create a 1D data-space that will hold the supplied vector.
template<typename NumT >
DataSpace getDataSpace (const std::vector< NumT > &data)
Create a 1D data-space that will hold the supplied vector.
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< uint32_t > &data)
template MANTID_DATAHANDLING_DLL DataSpace getDataSpace (const std::vector< uint64_t > &data)
template<typename NumT >
H5::DataType getType ()
Convert a primitive type to the appropriate H5::DataType.
template<typename NumT >
DataType getType ()
Convert a primitive type to the appropriate H5::DataType.
template<>
MANTID_DATAHANDLING_DLL DataType getType< double > ()
template<>
MANTID_DATAHANDLING_DLL DataType getType< float > ()
template<>
MANTID_DATAHANDLING_DLL DataType getType< int32_t > ()
template<>
MANTID_DATAHANDLING_DLL DataType getType< int64_t > ()
template<>
MANTID_DATAHANDLING_DLL DataType getType< uint32_t > ()
template<>
MANTID_DATAHANDLING_DLL DataType getType< uint64_t > ()
template<typename NumT >
std::vector< NumT > readArray1DCoerce (DataSet &dataset)
template<typename NumT >
std::vector< NumT > readArray1DCoerce (H5::DataSet &dataset)
template<typename NumT >
std::vector< NumT > readArray1DCoerce (H5::Group &group, const std::string &name)
template MANTID_DATAHANDLING_DLL std::vector< float > readArray1DCoerce (H5::Group &group, const std::string &name)
template MANTID_DATAHANDLING_DLL std::vector< double > readArray1DCoerce< double > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::vector< float > readArray1DCoerce< float > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::vector< int32_t > readArray1DCoerce< int32_t > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::vector< int64_t > readArray1DCoerce< int64_t > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::vector< uint32_t > readArray1DCoerce< uint32_t > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::vector< uint64_t > readArray1DCoerce< uint64_t > (DataSet &dataset)
template MANTID_DATAHANDLING_DLL std::string readAttributeAsString (H5::DataSet &location, const std::string &attributeName)
template MANTID_DATAHANDLING_DLL std::string readAttributeAsString (H5::Group &location, const std::string &attributeName)
template<typename LocationType >
std::string readAttributeAsString (LocationType &dataset, const std::string &attributeName)
template MANTID_DATAHANDLING_DLL std::vector< float > readNumArrayAttributeCoerce (H5::DataSet &location, const std::string &attributeName)
template MANTID_DATAHANDLING_DLL std::vector< float > readNumArrayAttributeCoerce (H5::Group &location, const std::string &attributeName)
template<typename NumT , typename LocationType >
std::vector< NumT > readNumArrayAttributeCoerce (LocationType &location, const std::string &attributeName)
template MANTID_DATAHANDLING_DLL float readNumAttributeCoerce (H5::DataSet &location, const std::string &attributeName)
template MANTID_DATAHANDLING_DLL float readNumAttributeCoerce (H5::Group &location, const std::string &attributeName)
template<typename NumT , typename LocationType >
NumT readNumAttributeCoerce (LocationType &location, const std::string &attributeName)
MANTID_DATAHANDLING_DLL std::string readString (H5::DataSet &dataset)
MANTID_DATAHANDLING_DLL std::string readString (H5::Group &group, const std::string &name)
MANTID_DATAHANDLING_DLL std::string readString (H5::H5File &file, const std::string &path)
std::vector< std::string > readStringVector (Group &group, const std::string &name)
Returns 1D vector of variable length strings.
MANTID_DATAHANDLING_DLL std::vector< std::string > readStringVector (H5::Group &, const std::string &)
MANTID_DATAHANDLING_DLL H5::DSetCreatPropList setCompressionAttributes (const std::size_t length, const int deflateLevel=6)
Sets up the chunking and compression rate.
void write (Group &group, const std::string &name, const std::string &value)
MANTID_DATAHANDLING_DLL void write (H5::Group &group, const std::string &name, const std::string &value)
template<typename NumT >
void writeArray1D (Group &group, const std::string &name, const std::vector< NumT > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< double > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< float > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< int32_t > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< int64_t > &values)
template<typename NumT >
void writeArray1D (H5::Group &group, const std::string &name, const std::vector< NumT > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< uint32_t > &values)
template MANTID_DATAHANDLING_DLL void writeArray1D (H5::Group &group, const std::string &name, const std::vector< uint64_t > &values)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const double &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const float &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const int32_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const int64_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< double > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< float > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< int32_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< int64_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< uint32_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const std::vector< uint64_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const uint32_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::DataSet &location, const std::string &name, const uint64_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const double &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const float &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const int32_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const int64_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< double > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< float > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< int32_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< int64_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< uint32_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const std::vector< uint64_t > &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const uint32_t &value)
template MANTID_DATAHANDLING_DLL void writeNumAttribute (H5::Group &location, const std::string &name, const uint64_t &value)
template<typename NumT , typename LocationType >
void writeNumAttribute (LocationType &location, const std::string &name, const NumT &value)
template<typename NumT , typename LocationType >
void writeNumAttribute (LocationType &location, const std::string &name, const std::vector< NumT > &value)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const double &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const float &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const int32_t &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const int64_t &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const std::string &value, const std::map< std::string, std::string > &attributes)
template<typename T >
void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const T &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const uint32_t &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeScalarDataSetWithStrAttributes (H5::Group &group, const std::string &name, const uint64_t &value, const std::map< std::string, std::string > &attributes)
template MANTID_DATAHANDLING_DLL void writeStrAttribute (H5::DataSet &location, const std::string &name, const std::string &value)
template MANTID_DATAHANDLING_DLL void writeStrAttribute (H5::Group &location, const std::string &name, const std::string &value)
template<typename LocationType >
void writeStrAttribute (LocationType &location, const std::string &name, const std::string &value)
Function Documentation
createGroupCanSAS() [1/4]
Group Mantid::DataHandling::H5Util::createGroupCanSAS (Group & group, const std::string & name, const std::string & nxtype, const std::string & cstype)
Definition at line 101 of file H5Util.cpp.
References createGroupNXS(), and writeStrAttribute().
createGroupCanSAS() [2/4]
MANTID_DATAHANDLING_DLL H5::Group Mantid::DataHandling::H5Util::createGroupCanSAS (H5::Group & group, const std::string & name, const std::string & nxtype, const std::string & cstype)
createGroupCanSAS() [3/4]
MANTID_DATAHANDLING_DLL H5::Group Mantid::DataHandling::H5Util::createGroupCanSAS (H5::H5File & file, const std::string & name, const std::string & nxtype, const std::string & cstype)
createGroupCanSAS() [4/4]
Group Mantid::DataHandling::H5Util::createGroupCanSAS (H5File & file, const std::string & name, const std::string & nxtype, const std::string & cstype)
Definition at line 95 of file H5Util.cpp.
References createGroupNXS(), and writeStrAttribute().
createGroupNXS() [1/4]
Group Mantid::DataHandling::H5Util::createGroupNXS (Group & group, const std::string & name, const std::string & nxtype)
Definition at line 89 of file H5Util.cpp.
References writeStrAttribute().
createGroupNXS() [2/4]
MANTID_DATAHANDLING_DLL H5::Group Mantid::DataHandling::H5Util::createGroupNXS (H5::Group & group, const std::string & name, const std::string & nxtype)
createGroupNXS() [3/4]
MANTID_DATAHANDLING_DLL H5::Group Mantid::DataHandling::H5Util::createGroupNXS (H5::H5File & file, const std::string & name, const std::string & nxtype)
Referenced by createGroupCanSAS(), and Mantid::DataHandling::SaveDiffCal::exec().
createGroupNXS() [4/4]
Group Mantid::DataHandling::H5Util::createGroupNXS (H5File & file, const std::string & name, const std::string & nxtype)
Definition at line 83 of file H5Util.cpp.
References writeStrAttribute().
getDataSpace() [1/9]
DataSpace Mantid::DataHandling::H5Util::getDataSpace (const size_t length)
H5Util : TODO: DESCRIPTION.
Create a 1D data-space to hold data of length.
Definition at line 46 of file H5Util.cpp.
Referenced by getDataSpace(), writeArray1D(), and writeNumAttribute().
getDataSpace() [2/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< double > & data)
getDataSpace() [3/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< float > & data)
getDataSpace() [4/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< int32_t > & data)
getDataSpace() [5/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< int64_t > & data)
getDataSpace() [6/9]
template<typename NumT > H5::DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< NumT > & data)
Create a 1D data-space that will hold the supplied vector.
Definition at line 51 of file H5Util.cpp.
References getDataSpace().
getDataSpace() [7/9]
template<typename NumT > DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< NumT > & data)
Create a 1D data-space that will hold the supplied vector.
Definition at line 51 of file H5Util.cpp.
References getDataSpace().
getDataSpace() [8/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< uint32_t > & data)
getDataSpace() [9/9]
template MANTID_DATAHANDLING_DLL DataSpace Mantid::DataHandling::H5Util::getDataSpace (const std::vector< uint64_t > & data)
getType() [1/2]
template<typename NumT > H5::DataType Mantid::DataHandling::H5Util::getType ()
Convert a primitive type to the appropriate H5::DataType.
Definition at line 32 of file H5Util.cpp.
getType() [2/2]
template<typename NumT > DataType Mantid::DataHandling::H5Util::getType ()
Convert a primitive type to the appropriate H5::DataType.
Definition at line 32 of file H5Util.cpp.
getType< double >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< double > ()
Definition at line 36 of file H5Util.cpp.
getType< float >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< float > ()
Definition at line 34 of file H5Util.cpp.
getType< int32_t >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< int32_t > ()
Definition at line 38 of file H5Util.cpp.
getType< int64_t >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< int64_t > ()
Definition at line 42 of file H5Util.cpp.
getType< uint32_t >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< uint32_t > ()
Definition at line 40 of file H5Util.cpp.
getType< uint64_t >()
template<> MANTID_DATAHANDLING_DLL DataType Mantid::DataHandling::H5Util::getType< uint64_t > ()
Definition at line 44 of file H5Util.cpp.
readArray1DCoerce() [1/4]
template<typename NumT > std::vector< NumT > Mantid::DataHandling::H5Util::readArray1DCoerce (DataSet & dataset)
Definition at line 361 of file H5Util.cpp.
readArray1DCoerce() [2/4]
template<typename NumT > std::vector< NumT > Mantid::DataHandling::H5Util::readArray1DCoerce (H5::DataSet & dataset)
readArray1DCoerce() [3/4]
template<typename NumT > template MANTID_DATAHANDLING_DLL std::vector< uint64_t > Mantid::DataHandling::H5Util::readArray1DCoerce (H5::Group & group, const std::string & name)
Definition at line 241 of file H5Util.cpp.
References Mantid::API::g_log, Mantid::Kernel::Logger::information(), and UNUSED_ARG.
readArray1DCoerce() [4/4]
template MANTID_DATAHANDLING_DLL std::vector< float > Mantid::DataHandling::H5Util::readArray1DCoerce (H5::Group & group, const std::string & name)
readArray1DCoerce< double >()
template MANTID_DATAHANDLING_DLL std::vector< double > Mantid::DataHandling::H5Util::readArray1DCoerce< double > (DataSet & dataset)
Referenced by Mantid::DataHandling::LoadDiffCal::exec().
readArray1DCoerce< float >()
template MANTID_DATAHANDLING_DLL std::vector< float > Mantid::DataHandling::H5Util::readArray1DCoerce< float > (DataSet & dataset)
readArray1DCoerce< int32_t >()
template MANTID_DATAHANDLING_DLL std::vector< int32_t > Mantid::DataHandling::H5Util::readArray1DCoerce< int32_t > (DataSet & dataset)
Referenced by Mantid::DataHandling::LoadDiffCal::exec().
readArray1DCoerce< int64_t >()
template MANTID_DATAHANDLING_DLL std::vector< int64_t > Mantid::DataHandling::H5Util::readArray1DCoerce< int64_t > (DataSet & dataset)
readArray1DCoerce< uint32_t >()
template MANTID_DATAHANDLING_DLL std::vector< uint32_t > Mantid::DataHandling::H5Util::readArray1DCoerce< uint32_t > (DataSet & dataset)
readArray1DCoerce< uint64_t >()
template MANTID_DATAHANDLING_DLL std::vector< uint64_t > Mantid::DataHandling::H5Util::readArray1DCoerce< uint64_t > (DataSet & dataset)
readAttributeAsString() [1/3]
template MANTID_DATAHANDLING_DLL std::string Mantid::DataHandling::H5Util::readAttributeAsString (H5::DataSet & location, const std::string & attributeName)
readAttributeAsString() [2/3]
template MANTID_DATAHANDLING_DLL std::string Mantid::DataHandling::H5Util::readAttributeAsString (H5::Group & location, const std::string & attributeName)
readAttributeAsString() [3/3]
template<typename LocationType > std::string Mantid::DataHandling::H5Util::readAttributeAsString (LocationType & dataset, const std::string & attributeName)
Definition at line 234 of file H5Util.cpp.
References value.
readNumArrayAttributeCoerce() [1/3]
template MANTID_DATAHANDLING_DLL std::vector< uint64_t > Mantid::DataHandling::H5Util::readNumArrayAttributeCoerce (H5::DataSet & location, const std::string & attributeName)
readNumArrayAttributeCoerce() [2/3]
template MANTID_DATAHANDLING_DLL std::vector< uint64_t > Mantid::DataHandling::H5Util::readNumArrayAttributeCoerce (H5::Group & location, const std::string & attributeName)
readNumArrayAttributeCoerce() [3/3]
template<typename NumT , typename LocationType > std::vector< NumT > Mantid::DataHandling::H5Util::readNumArrayAttributeCoerce (LocationType & location, const std::string & attributeName)
Definition at line 332 of file H5Util.cpp.
References value.
readNumAttributeCoerce() [1/3]
template MANTID_DATAHANDLING_DLL uint64_t Mantid::DataHandling::H5Util::readNumAttributeCoerce (H5::DataSet & location, const std::string & attributeName)
readNumAttributeCoerce() [2/3]
template MANTID_DATAHANDLING_DLL uint64_t Mantid::DataHandling::H5Util::readNumAttributeCoerce (H5::Group & location, const std::string & attributeName)
readNumAttributeCoerce() [3/3]
template<typename NumT , typename LocationType > NumT Mantid::DataHandling::H5Util::readNumAttributeCoerce (LocationType & location, const std::string & attributeName)
Definition at line 304 of file H5Util.cpp.
References value.
readString() [1/3]
std::string Mantid::DataHandling::H5Util::readString (H5::DataSet & dataset)
Definition at line 197 of file H5Util.cpp.
References value.
readString() [2/3]
std::string Mantid::DataHandling::H5Util::readString (H5::Group & group, const std::string & name)
Definition at line 187 of file H5Util.cpp.
References readString(), and UNUSED_ARG.
readString() [3/3]
std::string Mantid::DataHandling::H5Util::readString (H5::H5File & file, const std::string & path)
Definition at line 174 of file H5Util.cpp.
References readString(), and UNUSED_ARG.
Referenced by Mantid::DataHandling::LoadDiffCal::getInstrument(), and readString().
readStringVector() [1/2]
std::vector< std::string > Mantid::DataHandling::H5Util::readStringVector (Group & group, const std::string & name)
Returns 1D vector of variable length strings.
Parameters
group :: H5::Group already opened
name :: name of the dataset in the group (rank must be 1)
Returns
:: vector of strings
Definition at line 209 of file H5Util.cpp.
readStringVector() [2/2]
MANTID_DATAHANDLING_DLL std::vector< std::string > Mantid::DataHandling::H5Util::readStringVector (H5::Group & , const std::string &)
Referenced by Mantid::DataHandling::LoadILLDiffraction::loadScanVars().
setCompressionAttributes()
DSetCreatPropList Mantid::DataHandling::H5Util::setCompressionAttributes (const std::size_t length, const int deflateLevel = 6)
Sets up the chunking and compression rate.
Parameters
length
deflateLevel
Returns
The configured property list
Definition at line 107 of file H5Util.cpp.
Referenced by writeArray1D().
write() [1/2]
void Mantid::DataHandling::H5Util::write (Group & group, const std::string & name, const std::string & value)
Definition at line 149 of file H5Util.cpp.
References value.
write() [2/2]
MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::write (H5::Group & group, const std::string & name, const std::string & value)
Referenced by Mantid::DataHandling::SaveDiffCal::exec().
writeArray1D() [1/8]
template<typename NumT > void Mantid::DataHandling::H5Util::writeArray1D (Group & group, const std::string & name, const std::vector< NumT > & values)
Definition at line 160 of file H5Util.cpp.
References getDataSpace(), and setCompressionAttributes().
writeArray1D() [2/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< double > & values)
writeArray1D() [3/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< float > & values)
writeArray1D() [4/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< int32_t > & values)
writeArray1D() [5/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< int64_t > & values)
writeArray1D() [6/8]
template<typename NumT > void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< NumT > & values)
Referenced by Mantid::DataHandling::SaveDiffCal::writeDoubleFieldFromTable(), Mantid::DataHandling::SaveDiffCal::writeIntFieldFromSVWS(), and Mantid::DataHandling::SaveDiffCal::writeIntFieldFromTable().
writeArray1D() [7/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< uint32_t > & values)
writeArray1D() [8/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeArray1D (H5::Group & group, const std::string & name, const std::vector< uint64_t > & values)
writeNumAttribute() [1/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const double & value)
writeNumAttribute() [2/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const float & value)
writeNumAttribute() [3/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const int32_t & value)
writeNumAttribute() [4/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const int64_t & value)
writeNumAttribute() [5/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< double > & value)
writeNumAttribute() [6/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< float > & value)
writeNumAttribute() [7/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< int32_t > & value)
writeNumAttribute() [8/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< int64_t > & value)
writeNumAttribute() [9/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< uint32_t > & value)
writeNumAttribute() [10/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const std::vector< uint64_t > & value)
writeNumAttribute() [11/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const uint32_t & value)
writeNumAttribute() [12/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::DataSet & location, const std::string & name, const uint64_t & value)
writeNumAttribute() [13/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const double & value)
writeNumAttribute() [14/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const float & value)
writeNumAttribute() [15/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const int32_t & value)
writeNumAttribute() [16/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const int64_t & value)
writeNumAttribute() [17/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< double > & value)
writeNumAttribute() [18/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< float > & value)
writeNumAttribute() [19/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< int32_t > & value)
writeNumAttribute() [20/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< int64_t > & value)
writeNumAttribute() [21/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< uint32_t > & value)
writeNumAttribute() [22/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const std::vector< uint64_t > & value)
writeNumAttribute() [23/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const uint32_t & value)
writeNumAttribute() [24/26]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeNumAttribute (H5::Group & location, const std::string & name, const uint64_t & value)
writeNumAttribute() [25/26]
template<typename NumT , typename LocationType > void Mantid::DataHandling::H5Util::writeNumAttribute (LocationType & location, const std::string & name, const NumT & value)
Definition at line 124 of file H5Util.cpp.
References value.
writeNumAttribute() [26/26]
template<typename NumT , typename LocationType > void Mantid::DataHandling::H5Util::writeNumAttribute (LocationType & location, const std::string & name, const std::vector< NumT > & value)
Definition at line 138 of file H5Util.cpp.
References getDataSpace(), and value.
writeScalarDataSetWithStrAttributes() [1/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const double & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [2/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const float & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [3/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const int32_t & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [4/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const int64_t & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [5/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const std::string & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [6/8]
template<typename T > void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const T & value, const std::map< std::string, std::string > & attributes)
Definition at line 152 of file H5Util.cpp.
References value, and writeStrAttribute().
writeScalarDataSetWithStrAttributes() [7/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const uint32_t & value, const std::map< std::string, std::string > & attributes)
writeScalarDataSetWithStrAttributes() [8/8]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeScalarDataSetWithStrAttributes (H5::Group & group, const std::string & name, const uint64_t & value, const std::map< std::string, std::string > & attributes)
writeStrAttribute() [1/3]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeStrAttribute (H5::DataSet & location, const std::string & name, const std::string & value)
writeStrAttribute() [2/3]
template MANTID_DATAHANDLING_DLL void Mantid::DataHandling::H5Util::writeStrAttribute (H5::Group & location, const std::string & name, const std::string & value)
writeStrAttribute() [3/3]
template<typename LocationType > void Mantid::DataHandling::H5Util::writeStrAttribute (LocationType & location, const std::string & name, const std::string & value)
Definition at line 116 of file H5Util.cpp.
References value.
Referenced by createGroupCanSAS(), createGroupNXS(), Mantid::DataHandling::SaveDiffCal::exec(), and writeScalarDataSetWithStrAttributes().