Mantid: Mantid::DataHandling::Mantid3MFFileIO Class Reference
Mantid::DataHandling::Mantid3MFFileIO Class Reference
Class to load and save .3mf files .3mf format is a 3D manufacturing format for storing mesh descriptions of multi-component objects + metadata about the overall model (eg scale) and the individual components.
#include <Mantid3MFFileIO.h>
Public Member Functions
void LoadFile (std::string filename)
Load 3MF format file.
Mantid3MFFileIO ()
void readMeshObjects (std::vector< MeshObject_sptr > &meshObjects, MeshObject_sptr &sample)
Read a set of mesh objects from the in memory lib3mf model object.
void saveFile (std::string filename)
void writeMeshObjects (std::vector< const Geometry::MeshObject * > meshObjects, MeshObject_const_sptr &sample, DataHandling::ScaleUnits scale)
Public Member Functions inherited from Mantid::DataHandling::MeshFileIO
Kernel::V3D createScaledV3D (double xVal, double yVal, double zVal)
scales a 3D point according the units defined in the MeshFileIO class
ScaleUnits getScaleType ()
std::shared_ptr< Geometry::MeshObject > rotate (std::shared_ptr< Geometry::MeshObject > environmentMesh, double xRotation, double yRotation, double zRotation)
Rotates the environment by a generated matrix.
std::shared_ptr< Geometry::MeshObject > translate (std::shared_ptr< Geometry::MeshObject > environmentMesh, const std::vector< double > &translationVector)
translates the environment by a provided matrix
Private Member Functions
void AddBaseMaterial (std::string materialName, int materialColor, int &resourceID, Lib3MF_uint32 &materialPropertyID)
int generateRandomColor ()
MeshObject_sptr loadMeshObject (Lib3MF::PMeshObject meshObject, sLib3MFTransform buildTransform)
Load a single mesh object into a Mantid Geometry::MeshObject.
void readComponents (std::vector< MeshObject_sptr > &meshObjects, MeshObject_sptr &sample, uint32_t objectResourceID, sLib3MFTransform transform)
void readMeshObject (std::vector< MeshObject_sptr > &meshObjects, MeshObject_sptr &sample, uint32_t objectResourceID, sLib3MFTransform transform)
Attempt to read a single mesh from a specified lib3mf resource id.
void setMaterialOnObject (std::string objectName, std::string materialName, int materialColor)
void writeMeshObject (const Geometry::MeshObject &meshObject, std::string name)
Private Attributes
std::string m_filename
Lib3MF::PModel model
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataHandling::MeshFileIO
MeshFileIO (ScaleUnits scaleType)
MeshFileIO (ScaleUnits scaleType, std::vector< uint32_t > triangles, std::vector< Kernel::V3D > vertices)
float removeScale (double value)
double scaleValue (double val)
void setScaleType (const ScaleUnits scaleType)
Protected Attributes inherited from Mantid::DataHandling::MeshFileIO
ScaleUnits m_scaleType
std::vector< uint32_t > m_triangle
std::vector< Kernel::V3D > m_vertices
Detailed Description
Class to load and save .3mf files .3mf format is a 3D manufacturing format for storing mesh descriptions of multi-component objects + metadata about the overall model (eg scale) and the individual components.
The class currently uses the Lib3MF library to parse the files
Definition at line 35 of file Mantid3MFFileIO.h.
Constructor & Destructor Documentation
Mantid3MFFileIO()
Mantid::DataHandling::Mantid3MFFileIO::Mantid3MFFileIO () inline
Definition at line 37 of file Mantid3MFFileIO.h.
References Mantid::DataHandling::undefined.
Member Function Documentation
AddBaseMaterial()
void Mantid::DataHandling::Mantid3MFFileIO::AddBaseMaterial (std::string materialName, int materialColor, int & resourceID, Lib3MF_uint32 & materialPropertyID) private
Definition at line 360 of file Mantid3MFFileIO.cpp.
References model.
Referenced by setMaterialOnObject(), and writeMeshObject().
generateRandomColor()
int Mantid::DataHandling::Mantid3MFFileIO::generateRandomColor () private
Definition at line 308 of file Mantid3MFFileIO.cpp.
Referenced by writeMeshObject().
LoadFile()
void Mantid::DataHandling::Mantid3MFFileIO::LoadFile (std::string filename)
Load 3MF format file.
Parameters
filename The name of the 3MF file
Definition at line 34 of file Mantid3MFFileIO.cpp.
References Mantid::DataHandling::centimetres, Mantid::API::g_log, m_filename, Mantid::DataHandling::metres, Mantid::DataHandling::millimetres, model, Mantid::DataHandling::MeshFileIO::setScaleType(), and Mantid::Kernel::Logger::warning().
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFrom3MF(), and Mantid::DataHandling::SampleEnvironmentSpecParser::loadFullSpecification().
loadMeshObject()
MeshObject_sptr Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject (Lib3MF::PMeshObject meshObject, sLib3MFTransform buildTransform) private
Load a single mesh object into a Mantid Geometry::MeshObject.
Parameters
meshObject A Lib3mf pointer to the mesh object
buildTransform The rotation/translation to be applied to the object
Returns
A pointer to the Geometry::MeshObject
Definition at line 80 of file Mantid3MFFileIO.cpp.
References Mantid::DataHandling::MeshFileIO::createScaledV3D(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, m_filename, Mantid::DataHandling::MeshFileIO::m_triangle, Mantid::DataHandling::MeshFileIO::m_vertices, model, Mantid::Kernel::MaterialXMLParser::parse(), Mantid::DataHandling::MeshFileIO::scaleValue(), Mantid::Kernel::Matrix< T >::setRow(), std::to_string(), and Mantid::Kernel::Logger::warning().
Referenced by readMeshObject().
readComponents()
void Mantid::DataHandling::Mantid3MFFileIO::readComponents (std::vector< MeshObject_sptr > & meshObjects, MeshObject_sptr & sample, uint32_t objectResourceID, sLib3MFTransform transform) private
Definition at line 225 of file Mantid3MFFileIO.cpp.
References model, and readMeshObject().
Referenced by readMeshObject().
readMeshObject()
void Mantid::DataHandling::Mantid3MFFileIO::readMeshObject (std::vector< MeshObject_sptr > & meshObjects, MeshObject_sptr & sample, uint32_t objectResourceID, sLib3MFTransform transform) private
Attempt to read a single mesh from a specified lib3mf resource id.
If the resource id points at a component instead then read them
Parameters
meshObjects A vector to store the meshes for env components
sample A parameter to store a mesh for the sample
objectResourceID Integer identifier of the object to read in
transform Rotation/translation matrix for the object
Definition at line 202 of file Mantid3MFFileIO.cpp.
References loadMeshObject(), model, and readComponents().
Referenced by readComponents(), and readMeshObjects().
readMeshObjects()
void Mantid::DataHandling::Mantid3MFFileIO::readMeshObjects (std::vector< MeshObject_sptr > & meshObjects, MeshObject_sptr & sample)
Read a set of mesh objects from the in memory lib3mf model object.
Parameters
meshObjects A vector to store the meshes for env components
sample A parameter to store a mesh for the sample
Definition at line 184 of file Mantid3MFFileIO.cpp.
References model, and readMeshObject().
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFrom3MF(), and Mantid::DataHandling::SampleEnvironmentSpecParser::loadFullSpecification().
saveFile()
void Mantid::DataHandling::Mantid3MFFileIO::saveFile (std::string filename)
Definition at line 458 of file Mantid3MFFileIO.cpp.
References model.
Referenced by Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec().
setMaterialOnObject()
void Mantid::DataHandling::Mantid3MFFileIO::setMaterialOnObject (std::string objectName, std::string materialName, int materialColor) private
Definition at line 408 of file Mantid3MFFileIO.cpp.
References AddBaseMaterial(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, and model.
writeMeshObject()
void Mantid::DataHandling::Mantid3MFFileIO::writeMeshObject (const Geometry::MeshObject & meshObject, std::string name) private
Definition at line 240 of file Mantid3MFFileIO.cpp.
References AddBaseMaterial(), Mantid::Kernel::V3D::cross_prod(), Mantid::Kernel::Logger::debug(), Mantid::Geometry::Track::front(), Mantid::API::g_log, generateRandomColor(), Mantid::Geometry::MeshObject::getTriangles(), Mantid::Geometry::MeshObject::getV3Ds(), Mantid::Geometry::MeshObject::id(), Mantid::Geometry::MeshObject::interceptSurface(), Mantid::Geometry::MeshObject::material(), model, Mantid::Kernel::Material::name(), Mantid::Kernel::normalize(), and Mantid::Geometry::MeshObject::numberOfTriangles().
Referenced by writeMeshObjects().
writeMeshObjects()
void Mantid::DataHandling::Mantid3MFFileIO::writeMeshObjects (std::vector< const Geometry::MeshObject * > meshObjects, MeshObject_const_sptr & sample, DataHandling::ScaleUnits scale)
Definition at line 325 of file Mantid3MFFileIO.cpp.
References Mantid::DataHandling::centimetres, Mantid::DataHandling::metres, Mantid::DataHandling::millimetres, model, and writeMeshObject().
Referenced by Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec().
Member Data Documentation
m_filename
std::string Mantid::DataHandling::Mantid3MFFileIO::m_filename private
Definition at line 49 of file Mantid3MFFileIO.h.
Referenced by LoadFile(), and loadMeshObject().
model
Lib3MF::PModel Mantid::DataHandling::Mantid3MFFileIO::model private
Definition at line 48 of file Mantid3MFFileIO.h.
Referenced by AddBaseMaterial(), LoadFile(), loadMeshObject(), readComponents(), readMeshObject(), readMeshObjects(), saveFile(), setMaterialOnObject(), writeMeshObject(), and writeMeshObjects().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/Mantid3MFFileIO.h
Framework/DataHandling/src/Mantid3MFFileIO.cpp