Mantid: MantidQt::MantidWidgets::Batch::Row Class Reference
MantidQt::MantidWidgets::Batch::Row Class Reference
#include <Row.h>
Public Member Functions
std::vector< Cell > & cells ()
std::vector< Cell > const & cells () const
RowLocation const & location () const
Row (RowLocation location, std::vector< Cell > cells)
Private Attributes
std::vector< Cell > m_cells
RowLocation m_location
Detailed Description
Definition at line 23 of file Row.h.
Constructor & Destructor Documentation
Row()
MantidQt::MantidWidgets::Batch::Row::Row (RowLocation location, std::vector< Cell > cells)
Definition at line 12 of file Row.cpp.
Member Function Documentation
cells() [1/2]
std::vector< Cell > & MantidQt::MantidWidgets::Batch::Row::cells ()
Definition at line 17 of file Row.cpp.
References m_cells.
cells() [2/2]
std::vector< Cell > const & MantidQt::MantidWidgets::Batch::Row::cells () const
Definition at line 16 of file Row.cpp.
References m_cells.
Referenced by MantidQt::MantidWidgets::Batch::ExtractSubtrees::makeSubtreeFromRows(), MantidQt::MantidWidgets::Batch::operator<<(), and MantidQt::MantidWidgets::Batch::operator==().
location()
RowLocation const & MantidQt::MantidWidgets::Batch::Row::location () const
Definition at line 14 of file Row.cpp.
References m_location.
Referenced by MantidQt::MantidWidgets::Batch::ExtractSubtrees::findEndOfSubtree(), MantidQt::MantidWidgets::Batch::ExtractSubtrees::makeSubtreeFromRows(), MantidQt::MantidWidgets::Batch::operator<(), MantidQt::MantidWidgets::Batch::operator<<(), MantidQt::MantidWidgets::Batch::operator==(), and MantidQt::MantidWidgets::Batch::rowToRowLocation().
Member Data Documentation
m_cells
std::vector<Cell> MantidQt::MantidWidgets::Batch::Row::m_cells private
Definition at line 34 of file Row.h.
Referenced by cells(), and cells().
m_location
RowLocation MantidQt::MantidWidgets::Batch::Row::m_location private
Definition at line 33 of file Row.h.
Referenced by location().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/Row.h
qt/widgets/common/src/Batch/Row.cpp