Mantid: Mantid::Geometry::GridDetector Class Reference
Mantid::Geometry::GridDetector Class Reference
GridDetector is a type of CompAssembly, an assembly of components.
#include <GridDetector.h>
Public Member Functions
GridDetector * clone () const override
Make a clone of the present component.
void draw () const override
Draws the objcomponent.
void drawObject () const override
Draws the Object.
std::shared_ptr< Detector > getAtXYZ (const int x, const int y, const int z) const
Return a pointer to the component in the assembly at the (X,Y) pixel position.
void getBoundingBox (BoundingBox &assemblyBox) const override
Get the bounding box for this component and store it in the given argument.
void getBoundingBox (BoundingBox &assemblyBox) const override
Retrieve the cached bounding box.
std::shared_ptr< const IComponent > getComponentByName (const std::string &cname, int nlevels=0) const override
Returns a pointer to the first component of assembly encountered with the given name.
detid_t getDetectorIDAtXYZ (const int x, const int y, const int z) const
Return the detector ID corresponding to the component in the assembly at the (X,Y) pixel position.
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
Kernel::V3D getRelativePosAtXYZ (int x, int y, int z) const
Returns the position of the center of the pixel at x,y, relative to the center of the GridDetector, in the plain X,Y coordinates of the pixels (i.e.
std::tuple< int, int, int > getXYZForDetectorID (const detid_t detectorID) const
Given a detector ID, return the X,Y,Z coords into the grid detector.
GridDetector (const GridDetector *base, const ParameterMap *map)
Parametrized constructor.
GridDetector (const std::string &name, IComponent *reference=nullptr)
Constructor with a name and parent reference.
bool idfillbyfirst_y () const
Returns the idfillbyfirst_y.
std::string idFillOrder () const
Returns the id fill order.
int idstart () const
Returns the idstart.
int idstep () const
Returns the idstep.
int idstepbyrow () const
Returns the idstepbyrow.
void initDraw () const override
Initializes the ObjComponent for rendering, this function should be called before rendering.
void initialize (std::shared_ptr< IObject > shape, int xpixels, double xstart, double xstep, int ypixels, double ystart, double ystep, int zpixels, double zstart, double zstep, int idstart, const std::string &idFillOrder, int idstepbyrow, int idstep=1)
Create all the detector pixels of this grid detector.
int interceptSurface (Track &track) const override
Checks whether the track given will pass through this Component.
bool isOnSide (const Kernel::V3D &point) const override
Does the point given lie on the surface of this object component?
bool isValid (const Kernel::V3D &point) const override
Does the point given lie within this object component?
const Kernel::Material material () const override
Returns the material of the detector.
detid_t maxDetectorID ()
maximum detector id
detid_t minDetectorID ()
minimum detector id
virtual size_t registerContents (class ComponentVisitor &componentVisitor) const override
const std::shared_ptr< const IObject > shape () const override
Returns the shape of the Object.
double solidAngle (const Kernel::V3D &observer) const override
Finds the approximate solid angle covered by the component when viewed from the point given.
void testIntersectionWithChildren (Track &testRay, std::deque< IComponent_const_sptr > &searchQueue) const override
Test the intersection of the ray with the children of the component assembly, for InstrumentRayTracer.
std::string type () const override
String description of the type of component.
int xpixels () const
Returns the number of pixels in the X direction.
double xsize () const
Size in X of the detector.
double xstart () const
Returns the start position in the X direction.
double xstep () const
Returns the step size in the X direction.
int ypixels () const
Returns the number of pixels in the Y direction.
double ysize () const
Size in Y of the detector.
double ystart () const
Returns the start position in the Y direction.
double ystep () const
Returns the step size in the Y direction.
int zpixels () const
Returns the number of pixels in the Z direction.
double zsize () const
Size in Z of the detector.
double zstart () const
Returns the start position in the Z direction.
double zstep () const
Returns the step size in the Z direction.
Public Member Functions inherited from Mantid::Geometry::CompAssembly
int add (IComponent *) override
Add a component to the assembly.
void addChildren (IComponent *comp)
Add a copy (clone) of a component.
int addCopy (IComponent *) override
AddCopy method.
int addCopy (IComponent *, const std::string &) override
Add a copy (clone) of a component and rename it.
IComponent * clone () const override
Make a clone of the present component.
CompAssembly ()
Empty constructor.
CompAssembly (const CompAssembly &)
Copy constructor.
CompAssembly (const IComponent *base, const ParameterMap *map)
Constructor for parametrized version.
CompAssembly (const std::string &, IComponent *reference=nullptr)
Constructor with a name and parent reference.
void getBoundingBox (BoundingBox &assemblyBox) const override
Get the bounding box for this component and store it in the given argument.
std::shared_ptr< IComponent > getChild (const int i) const override
Get a pointer to the ith component within the assembly. Easier to use than.
void getChildren (std::vector< IComponent_const_sptr > &outVector, bool recursive) const override
Returns a vector of all children contained.
std::shared_ptr< const IComponent > getComponentByName (const std::string &cname, int nlevels=0) const override
Returns a pointer to the first component of assembly encountered with the given name.
Kernel::V3D getPos () const override
Gets the absolute position of the Parametrized CompAssembly This attempts to read the cached position value from the parameter map, and creates it if it is not available.
Kernel::Quat getRotation () const override
Gets the absolute position of the Parametrized CompAssembly This attempts to read the cached position value from the parameter map, and creates it if it is not available.
int nelements () const override
Return the number of elements in the assembly.
CompAssembly & operator= (const CompAssembly &other)
std::shared_ptr< IComponent > operator[] (int i) const override
Get a pointer to the ith component in the assembly.
void printChildren (std::ostream &) const override
Print information about all children.
void printTree (std::ostream &) const override
Print information about all the elements in the tree to a stream Loops through all components in the tree and call printSelf(os).
virtual size_t registerContents (class ComponentVisitor &componentVisitor) const override
int remove (IComponent *)
Remove a component from the assembly.
void testIntersectionWithChildren (Track &testRay, std::deque< IComponent_const_sptr > &searchQueue) const override
Test the intersection of the ray with the children of the component assembly, for InstrumentRayTracer
std::string type () const override
String description of the type of component.
~CompAssembly () override
Destructor.
Public Member Functions inherited from Mantid::Geometry::ICompAssembly
virtual int add (IComponent *)=0
Add a component to the assembly.
virtual int addCopy (IComponent *)=0
Add a copy (clone) of a component.
virtual int addCopy (IComponent *, const std::string &)=0
Add a copy (clone) of a component and rename it.
IComponent * clone () const override=0
Make a clone of the present component.
virtual std::shared_ptr< IComponent > getChild (const int i) const =0
Get a pointer to the ith component within the assembly.
virtual void getChildren (std::vector< IComponent_const_sptr > &outVector, bool recursive) const =0
Get all children.
virtual std::shared_ptr< const IComponent > getComponentByName (const std::string &cname, int nlevels=0) const =0
Returns a pointer to the first component of assembly encountered with the given name.
ICompAssembly ()
virtual int nelements () const =0
Return the number of elements in the assembly.
virtual std::shared_ptr< IComponent > operator[] (int i) const =0
Overloaded index operator.
virtual void printChildren (std::ostream &) const =0
Print information about all children.
virtual void printTree (std::ostream &) const =0
Print information about all the elements in the tree to a stream Loops through all components in the tree and call printSelf(os).
virtual void testIntersectionWithChildren (Track &testRay, std::deque< IComponent_const_sptr > &searchQueue) const =0
Test the intersection of the ray with the children of the component assembly.
std::string type () const override
String description of the type of component.
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual IComponent * clone () const =0
Return a clone to the current object.
virtual std::vector< std::shared_ptr< const IComponent > > getAncestors () const =0
Return an array of all ancestors, the nearest first.
virtual const IComponent * getBareParent () const =0
Returns the bare pointer to the IComponent parent.
virtual IComponent const * getBaseComponent () const =0
Returns const pointer to base component if this component is parametrized.
virtual void getBoundingBox (BoundingBox &boundingBox) const =0
Get the bounding box for this component and store it in the given argument.
virtual ComponentID getComponentID () const =0
Returns the ComponentID - a unique identifier of the component.
virtual double getDistance (const IComponent &) const =0
Get the distance to another IComponent.
virtual std::string getFullName () const =0
Get the IComponent full path name.
virtual std::string getName () const =0
Get the IComponent name.
virtual std::shared_ptr< const IComponent > getParent () const =0
Return a pointer to the current parent.
virtual Kernel::V3D getPos () const =0
Get the position of the IComponent. Tree structure is traverse through the.
virtual Kernel::V3D getRelativePos () const =0
Get the position relative to the parent IComponent (absolute if no parent)
virtual Kernel::Quat getRelativeRot () const =0
Get the relative Orientation.
virtual Kernel::Quat getRotation () const =0
Get the absolute orientation of the IComponent.
virtual Kernel::V3D getScaleFactor () const
Gets the scaling factor of the object for the Object Component.
virtual void rotate (const Kernel::Quat &)=0
Rotate the IComponent. This is relative to parent.
virtual void rotate (double, const Kernel::V3D &)=0
Rotate the IComponent by an angle in degrees with respect to an axis.
virtual void setName (const std::string &)=0
Set the IComponent name.
virtual void setParent (IComponent *)=0
Assign a parent IComponent. Previous parent link is lost.
virtual void setPos (const Kernel::V3D &)=0
Set the position of the component The position is with respect to the parent component.
virtual void setPos (double, double, double)=0
Set the IComponent position, x, y, z respective to parent (if present)
virtual void setRot (const Kernel::Quat &)=0
Set the orientation Kernel::Quaternion relative to parent (if present)
virtual void translate (const Kernel::V3D &)=0
Copy the Rotation from another IComponent.
virtual void translate (double, double, double)=0
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string type () const
Returns a string representation of the IComponent type.
virtual ~IComponent ()=default
Destructor.
Public Member Functions inherited from Mantid::Geometry::Component
IComponent * clone () const override
Clone method Make a copy of the Component.
Component ()
Create Empty Component at Origin, with no orientation and null parent.
Component (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
Component (std::string name, const Kernel::V3D &position, const Kernel::Quat &rotation, IComponent *parent=nullptr)
Create a named component with positioning vector, orientation and parent.
Component (std::string name, const Kernel::V3D &position, IComponent *parent=nullptr)
Create a named component with positioning vector, and parent component.
Component (std::string name, IComponent *parent=nullptr)
Create a named component with a parent component (optional)
std::vector< std::shared_ptr< const IComponent > > getAncestors () const override
Return an array of all ancestors.
IComponent const * getBaseComponent () const override
Returns const pointer to base component if this component is parametrized.
void getBoundingBox (BoundingBox &boundingBox) const override
Get the bounding box for this component and store it in the given argument.
ComponentID getComponentID () const override
Returns the ComponentID - a unique identifier of the component.
double getDistance (const IComponent &) const override
Get the distance to another IComponent.
std::string getFullName () const override
Get the full pathname.
std::string getName () const override
Get the IComponent name.
std::shared_ptr< const IComponent > getParent () const override
Return a pointer to the current parent. as shared pointer.
Kernel::V3D getPos () const override
Get the position of the IComponent. Tree structure is traverse through the.
Kernel::V3D getRelativePos () const override
Get the position relative to the parent IComponent (absolute if no parent)
Kernel::Quat getRelativeRot () const override
Get the relative Orientation.
Kernel::Quat getRotation () const override
Get the absolute orientation of the IComponent.
bool isParentNamed (const std::string &expectedName, int maxDepth=-1) const
Return true if one of the parents of this component is named something.
void rotate (const Kernel::Quat &) override
Rotate the IComponent. This is relative to parent.
void rotate (double, const Kernel::V3D &) override
Rotate the IComponent by an angle in degrees with respect to an axis.
void setName (const std::string &) override
Set the IComponent name.
void setParent (IComponent *) override
Assign a parent IComponent. Previous parent link is lost.
void setPos (const Kernel::V3D &) override
Set the position of the Component The position is with respect to the parent Component.
void setPos (double, double, double) override
Set the IComponent position, x, y, z respective to parent (if present)
void setRot (const Kernel::Quat &) override
Set the orientation Kernel::Quaternion relative to parent (if present)
void translate (const Kernel::V3D &) override
Translate the IComponent (vector form). This is relative to parent if.
void translate (double, double, double) override
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string typeName () const
std::set< std::string > getParameterNames (bool recursive=true) const override
Return the parameter names.
std::map< std::string, ComponentID > getParameterNamesByComponent () const override
return the parameter names and the component they are from
bool hasParameter (const std::string &name, bool recursive=true) const override
Returns a boolean indicating if the component has the named parameter.
std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a double.
std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an int.
std::string getParameterType (const std::string &pname, bool recursive=true) const override
Get a parameter's type – this is HACK until Python can export property regardless of the property type.
std::string getDescription () const
Get this component parameter's description – no recursive search within children.
std::string getParamDescription (const std::string &pname, bool recursive=true) const
Get description of a parameter attached to this component
std::string getParamShortDescription (const std::string &pname, bool recursive=true) const
Get a component's parameter short description.
std::string getShortDescription () const
Get a components's short description.
void setDescription (const std::string &descr)
Set components description.
std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a bool.
std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::V3D.
std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::Quaternion.
std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a string.
std::string getParameterAsString (const std::string &pname, bool recursive=true) const override
get a string representation of a parameter
bool getParameterVisible (const std::string &p_name, bool recursive) const override
Get a visibility attribute of a parameter from the parameter map.
void printSelf (std::ostream &) const override
Prints a text representation of itself.
const IComponent * base () const
Returns the address of the base component.
Kernel::V3D getScaleFactor () const override
Returns the ScaleFactor.
const IComponent * getBareParent () const override
Returns the bare pointer to the IComponent parent.
virtual void readXMLAttributes (const Poco::XML::Attributes &attr)
Reads the XML attributes from Poco XML parser.
virtual void writeXML (Poco::XML::XMLWriter &writer) const
virtual void appendXML (std::ostream &xmlStream) const
Append to an open XML string.
bool isParametrized () const override
Return true if the Component is, in fact, parametrized (that is - it has a valid parameter map)
bool hasComponentInfo () const
size_t index () const
Helper for legacy access mode. Returns the index of the component.
Public Member Functions inherited from Mantid::Geometry::IObjComponent
IComponent * clone () const override=0
Virtual Copy Constructor.
virtual void draw () const =0
Draws the objcomponent.
virtual void drawObject () const =0
Draws the Object.
virtual int getPointInObject (Kernel::V3D &point) const =0
Try to find a point that lies within (or on) the object.
GeometryHandler * Handle () const
Gets the GeometryHandler.
virtual void initDraw () const =0
Initializes the ObjComponent for rendering, this function should be called before rendering.
virtual int interceptSurface (Track &track) const =0
Checks whether the track given will pass through this Component.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
virtual bool isOnSide (const Kernel::V3D &point) const =0
Does the point given lie on the surface of this object component?
virtual bool isValid (const Kernel::V3D &point) const =0
Does the point given lie within this object component?
virtual const Kernel::Material material () const =0
Returns the material of the Object.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
virtual const std::shared_ptr< const IObject > shape () const =0
Returns the shape of the Object.
virtual double solidAngle (const Kernel::V3D &observer) const =0
Finds the approximate solid angle covered by the component when viewed from the point given.
std::string type () const override
type string
~IObjComponent () override
Static Public Member Functions
static bool compareName (const std::string &proposedMatch)
Matches name to Structured Detector.
Protected Member Functions
void createLayer (const std::string &name, CompAssembly *parent, int iz, int &minDetID, int &maxDetID)
void init ()
initialize members to bare defaults
Protected Member Functions inherited from Mantid::Geometry::ICompAssembly
ICompAssembly (const ICompAssembly &)=default
Protected copy constructor.
Protected Member Functions inherited from Mantid::Geometry::Component
template<class TYPE >
std::vector< TYPE > getParameter (const std::string &p_name, bool recursive) const
Get a parameter from the parameter map.
void swap (const Component *base, const ParameterMap *pmap)
Swap the current references to the un-parameterized component and parameter map for new ones.
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Private Member Functions
void initializeValues (std::shared_ptr< IObject > shape, int xpixels, double xstart, double xstep, int ypixels, double ystart, double ystep, int zpixels, double zstart, double zstep, int idstart, const std::string &idFillOrder, int idstepbyrow, int idstep)
GridDetector & operator= (const ICompAssembly &)
Private copy assignment operator.
void validateInput () const
Private Attributes
const GridDetector * m_gridBase
Pointer to the base GridDetector, for parametrized instruments.
bool m_idfillbyfirst_y
IDs are filled in Y fastest.
std::string m_idFillOrder
The order in which to fill IDs.
int m_idstart
IDs start here.
int m_idstep
Step size in ID in each col.
int m_idstepbyrow
Step size in ID in each row.
detid_t m_maxDetId
maximum detector id
detid_t m_minDetId
minimum detector id
std::shared_ptr< IObject > m_shape
Pointer to the shape of the pixels in this detector array.
int m_xpixels
The number of pixels in the X (horizontal) direction.
double m_xsize
Size in X of the detector.
double m_xstart
X position of the 0-th pixel.
double m_xstep
Step size in the X direction of detector.
int m_ypixels
The number of pixels in the Y (vertical) direction.
double m_ysize
Size in Y of the detector.
double m_ystart
Y position of the 0-th pixel.
double m_ystep
Step size in the Y direction of detector.
int m_zpixels
The number of pixels in the Z (usually beam) direction.
double m_zsize
Size in Z of the detector.
double m_zstart
Z position of the 0-th pixel.
double m_zstep
Step size in the Z direction of the detector.
Friends
class GridDetectorPixel
Additional Inherited Members
Protected Types inherited from Mantid::Geometry::CompAssembly
using comp_it = std::vector< IComponent * >::iterator
Iterator type.
using const_comp_it = std::vector< IComponent * >::const_iterator
Const iterator type.
Protected Attributes inherited from Mantid::Geometry::CompAssembly
BoundingBox * m_cachedBoundingBox
A cached bounding box.
std::vector< IComponent * > m_children
the group of child components
Protected Attributes inherited from Mantid::Geometry::Component
const IComponent * m_parent
Parent component in the tree.
const Component * m_base
The base component - this is the unmodified component (without the parameters).
const ParameterMap * m_map
A pointer to const ParameterMap containing the parameters.
std::string m_name
Name of the component.
Kernel::V3D m_pos
Position w.
Kernel::Quat m_rot
Orientation.
Detailed Description
GridDetector is a type of CompAssembly, an assembly of components.
It is designed to be an easy way to specify a 3D grid (XYZ) array of Detector pixels. Ragged grids are not allowed, pixels are uniform in each dimension.
Assembly of Detector objects in a 3D grid shape
Author
Lamar Moore, ISIS
Date
2018-Jul-24
Definition at line 34 of file GridDetector.h.
Constructor & Destructor Documentation
GridDetector() [1/2]
Mantid::Geometry::GridDetector::GridDetector (const std::string & n, IComponent * reference = nullptr)
Constructor with a name and parent reference.
Valued constructor.
Parameters
n :: name of the assembly
reference :: the parent Component
If the reference is an object of class Component,
normal parenting apply. If the reference object is an assembly itself, then in addition to parenting this is registered as a children of reference.
Definition at line 52 of file GridDetector.cpp.
References Mantid::Geometry::IObjComponent::GeometryHandler, init(), Mantid::Geometry::IObjComponent::setGeometryHandler(), and Mantid::Geometry::IComponent::setName().
GridDetector() [2/2]
Mantid::Geometry::GridDetector::GridDetector (const GridDetector * base, const ParameterMap * map)
Parametrized constructor.
Constructor for a parametrized GridDetector.
Parameters
base the base (un-parametrized) GridDetector
map pointer to the ParameterMap
Definition at line 37 of file GridDetector.cpp.
References Mantid::Geometry::IObjComponent::GeometryHandler, init(), and Mantid::Geometry::IObjComponent::setGeometryHandler().
Member Function Documentation
clone()
GridDetector * Mantid::Geometry::GridDetector::clone () const override virtual
Make a clone of the present component.
Clone method Make a copy of the component assembly.
Returns
new(*this)
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 80 of file GridDetector.cpp.
compareName()
bool Mantid::Geometry::GridDetector::compareName (const std::string & proposedMatch) static
Matches name to Structured Detector.
Definition at line 59 of file GridDetector.cpp.
Referenced by Mantid::Geometry::InstrumentDefinitionParser::appendLeaf().
createLayer()
void Mantid::Geometry::GridDetector::createLayer (const std::string & name, CompAssembly * parent, int iz, int & minDetID, int & maxDetID) protected
Definition at line 437 of file GridDetector.cpp.
References Mantid::Geometry::CompAssembly::CompAssembly(), getDetectorIDAtXYZ(), GridDetectorPixel, m_shape, m_xpixels, m_xstart, m_xstep, m_ypixels, m_ystart, m_ystep, m_zpixels, m_zstart, m_zstep, Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by initialize().
draw()
void Mantid::Geometry::GridDetector::draw () const override virtual
Draws the objcomponent.
Draws the objcomponent, If the handler is not set then this function does nothing.
Implements Mantid::Geometry::IObjComponent.
Definition at line 790 of file GridDetector.cpp.
References Mantid::Geometry::IObjComponent::Handle(), and Mantid::Geometry::GeometryHandler::render().
Referenced by drawObject().
drawObject()
void Mantid::Geometry::GridDetector::drawObject () const override virtual
Draws the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 799 of file GridDetector.cpp.
References draw().
getAtXYZ()
std::shared_ptr< Detector > Mantid::Geometry::GridDetector::getAtXYZ (const int x, const int y, const int z) const
Return a pointer to the component in the assembly at the (X,Y) pixel position.
Parameters
x :: index from 0..m_xpixels-1
y :: index from 0..m_ypixels-1
z :: index from 0..m_zpixels-1
Returns
a pointer to the component in the assembly at the (x,y,z) pixel position
Exceptions
runtime_error if the x/y/z pixel width is not set, or x/y/z are out of range
Definition at line 94 of file GridDetector.cpp.
References Mantid::Geometry::CompAssembly::getChild(), Mantid::Geometry::x, xpixels(), Mantid::Geometry::y, ypixels(), Mantid::Geometry::z, and zpixels().
Referenced by Mantid::Geometry::RectangularDetector::getAtXY(), getBoundingBox(), and testIntersectionWithChildren().
getBoundingBox() [1/2]
void Mantid::Geometry::CompAssembly::getBoundingBox (BoundingBox & assemblyBox) const override virtual
Get the bounding box for this component and store it in the given argument.
Get the bounding box for this assembly.
It is simply the sum of the bounding boxes of its children
Parameters
assemblyBox :: [Out] The resulting bounding box is stored here.
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 80 of file CompAssembly.cpp.
getBoundingBox() [2/2]
void Mantid::Geometry::GridDetector::getBoundingBox (BoundingBox & assemblyBox) const override virtual
Retrieve the cached bounding box.
Get the bounding box and store it in the given object.
This is cached after the first call.
Parameters
assemblyBox :: A BoundingBox object that will be overwritten
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 757 of file GridDetector.cpp.
References Mantid::Geometry::ComponentInfo::boundingBox(), Mantid::Geometry::ParameterMap::componentInfo(), getAtXYZ(), Mantid::Geometry::BoundingBox::grow(), Mantid::Geometry::Component::hasComponentInfo(), Mantid::Geometry::Component::index(), Mantid::Geometry::Component::m_map, xpixels(), ypixels(), and zpixels().
getComponentByName()
std::shared_ptr< const IComponent > Mantid::Geometry::GridDetector::getComponentByName (const std::string & cname, int nlevels = 0) const override virtual
Returns a pointer to the first component of assembly encountered with the given name.
Find a component by name.
Parameters
cname :: The name of the component. If there are multiple matches, the first one found is returned. If the name contains '/', it will search for the component whose name occurs before the '/' then within that component's assembly, search the component whose name occurs after the '/' and so on with any subsequent '/'. For example to find 'tube020' in 'panel07', one could use the cname 'panel07/tube020', given that tube020 is unique within panel07.
nlevels :: Optional argument to limit number of levels searched. If cname has a '/', then nlevels will apply to each step delimited by the '/'s, rather than the whole search. In particular, nlevels=1, would force cname to be a full path name.
Returns
A shared pointer to the component
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 622 of file GridDetector.cpp.
References Mantid::Geometry::CompAssembly::getComponentByName(), and Mantid::Geometry::IComponent::getName().
getDetectorIDAtXYZ()
detid_t Mantid::Geometry::GridDetector::getDetectorIDAtXYZ (const int x, const int y, const int z) const
Return the detector ID corresponding to the component in the assembly at the (X,Y) pixel position.
No bounds check is made!
Parameters
x :: index from 0..m_xpixels-1
y :: index from 0..m_ypixels-1
z :: index from 0..m_zpixels-1
Returns
detector ID int
Exceptions
runtime_error if the x/y/z pixel width is not set, or X/Y are out of range
Definition at line 156 of file GridDetector.cpp.
References Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), m_gridBase, m_idFillOrder, Mantid::Geometry::Component::m_map, Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by createLayer(), and Mantid::Geometry::RectangularDetector::getDetectorIDAtXY().
getPointInObject()
int Mantid::Geometry::GridDetector::getPointInObject (Kernel::V3D & point) const override virtual
Try to find a point that lies within (or on) the object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 747 of file GridDetector.cpp.
getRelativePosAtXYZ()
V3D Mantid::Geometry::GridDetector::getRelativePosAtXYZ (int x, int y, int z) const
Returns the position of the center of the pixel at x,y, relative to the center of the GridDetector, in the plain X,Y coordinates of the pixels (i.e.
unrotated).
Parameters
x :: x pixel integer
y :: y pixel integer
z :: z pixel integer
Returns
a V3D vector of the relative position
Definition at line 421 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), getRelativePosAtXYZ(), m_gridBase, Mantid::Geometry::Component::m_map, m_xstart, m_xstep, m_ystart, m_ystep, m_zstart, m_zstep, Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by Mantid::Geometry::RectangularDetector::getRelativePosAtXY(), and getRelativePosAtXYZ().
getXYZForDetectorID()
std::tuple< int, int, int > Mantid::Geometry::GridDetector::getXYZForDetectorID (const detid_t detectorID) const
Given a detector ID, return the X,Y,Z coords into the grid detector.
Parameters
detectorID :: detectorID
Returns
tuple of (x,y,z)
Definition at line 211 of file GridDetector.cpp.
References Mantid::Geometry::getXYZFillFirstX(), Mantid::Geometry::getXYZFillFirstY(), Mantid::Geometry::getXYZFillFirstZ(), m_gridBase, m_idFillOrder, m_idstart, m_idstep, m_idstepbyrow, and Mantid::Geometry::Component::m_map.
Referenced by Mantid::Geometry::RectangularDetector::getXYForDetectorID().
idfillbyfirst_y()
bool Mantid::Geometry::GridDetector::idfillbyfirst_y () const
Returns the idfillbyfirst_y.
Definition at line 378 of file GridDetector.cpp.
References m_gridBase, m_idfillbyfirst_y, and Mantid::Geometry::Component::m_map.
Referenced by Mantid::Geometry::RectangularDetector::initialize().
idFillOrder()
std::string Mantid::Geometry::GridDetector::idFillOrder () const
Returns the id fill order.
Definition at line 386 of file GridDetector.cpp.
References m_gridBase, m_idFillOrder, and Mantid::Geometry::Component::m_map.
Referenced by export_GridDetector(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::getXYZFillFirstX(), Mantid::Geometry::getXYZFillFirstY(), Mantid::Geometry::getXYZFillFirstZ(), initialize(), and initializeValues().
idstart()
int Mantid::Geometry::GridDetector::idstart () const
Returns the idstart.
Definition at line 369 of file GridDetector.cpp.
References m_gridBase, m_idstart, and Mantid::Geometry::Component::m_map.
Referenced by export_GridDetector(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
idstep()
int Mantid::Geometry::GridDetector::idstep () const
Returns the idstep.
Definition at line 404 of file GridDetector.cpp.
References m_gridBase, m_idstep, and Mantid::Geometry::Component::m_map.
Referenced by export_GridDetector(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
idstepbyrow()
int Mantid::Geometry::GridDetector::idstepbyrow () const
Returns the idstepbyrow.
Definition at line 395 of file GridDetector.cpp.
References m_gridBase, m_idstepbyrow, and Mantid::Geometry::Component::m_map.
Referenced by export_GridDetector(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::getXYZFillFirstX(), Mantid::Geometry::getXYZFillFirstY(), Mantid::Geometry::getXYZFillFirstZ(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
init()
void Mantid::Geometry::GridDetector::init () protected
initialize members to bare defaults
Definition at line 64 of file GridDetector.cpp.
References m_idfillbyfirst_y, m_idstart, m_idstep, m_idstepbyrow, m_maxDetId, m_minDetId, m_xpixels, m_xsize, m_xstart, m_xstep, m_ypixels, m_ysize, m_ystart, m_ystep, m_zpixels, m_zsize, m_zstart, and m_zstep.
Referenced by GridDetector(), and Mantid::Geometry::RectangularDetector::RectangularDetector().
initDraw()
void Mantid::Geometry::GridDetector::initDraw () const override virtual
Initializes the ObjComponent for rendering, this function should be called before rendering.
Implements Mantid::Geometry::IObjComponent.
Definition at line 805 of file GridDetector.cpp.
References Mantid::Geometry::IObjComponent::Handle(), and Mantid::Geometry::GeometryHandler::initialize().
initialize()
void Mantid::Geometry::GridDetector::initialize (std::shared_ptr< IObject > shape, int xpixels, double xstart, double xstep, int ypixels, double ystart, double ystep, int zpixels, double zstart, double zstep, int idstart, const std::string & idFillOrder, int idstepbyrow, int idstep = 1)
Create all the detector pixels of this grid detector.
Initialize a GridDetector by creating all of the pixels contained within it.
You should have set the name, position and rotation and facing of this object BEFORE calling this.
Parameters
shape :: a geometry Object containing the shape of each (individual) pixel in the assembly. All pixels must have the same shape.
xpixels :: number of pixels in X
xstart :: x-position of the 0-th pixel (in length units, normally meters)
xstep :: step size between pixels in the horizontal direction (in length units, normally meters)
ypixels :: number of pixels in Y
ystart :: y-position of the 0-th pixel (in length units, normally meters)
ystep :: step size between pixels in the vertical direction (in length units, normally meters)
zpixels :: number of pixels in Z
zstart :: z-position of the 0-th pixel (in length units, normally meters)
zstep :: step size between pixels in the beam direction (in length units, normally meters)
idstart :: detector ID of the first pixel
idFillOrder :: string of size 3 which contains axis order e.g "xyz"
idstepbyrow :: amount to increase the ID number on each row. e.g, if you fill by Y first, and set idstepbyrow = 100, and have 50 Y pixels, you would get: (0,0)=0; (0,1)=1; ... (0,49)=49; (1,0)=100; (1,1)=101; etc.
idstep :: amount to increase each individual ID number with a row. e.g, if you fill by Y first, and idstep=100 and idstart=1 then (0,0)=1; (0,1)=101; and so on
Definition at line 572 of file GridDetector.cpp.
References Mantid::Geometry::CompAssembly::CompAssembly(), createLayer(), Mantid::Geometry::IComponent::getName(), idFillOrder(), idstart(), idstep(), idstepbyrow(), initializeValues(), Mantid::Geometry::Component::m_map, m_maxDetId, m_minDetId, m_zpixels, shape(), xpixels(), xstart(), xstep(), ypixels(), ystart(), ystep(), zpixels(), zstart(), and zstep().
Referenced by Mantid::Geometry::RectangularDetector::initialize().
initializeValues()
void Mantid::Geometry::GridDetector::initializeValues (std::shared_ptr< IObject > shape, int xpixels, double xstart, double xstep, int ypixels, double ystart, double ystep, int zpixels, double zstart, double zstep, int idstart, const std::string & idFillOrder, int idstepbyrow, int idstep) private
IDs start here
IDs are filled in Y fastest
IDs are filled by Y fastest
Step size in ID in each row
Step size in ID in each col
Definition at line 506 of file GridDetector.cpp.
References idFillOrder(), idstart(), idstep(), idstepbyrow(), m_idfillbyfirst_y, m_idFillOrder, m_idstart, m_idstep, m_idstepbyrow, m_shape, m_xpixels, m_xsize, m_xstart, m_xstep, m_ypixels, m_ysize, m_ystart, m_ystep, m_zpixels, m_zsize, m_zstart, m_zstep, shape(), validateInput(), xpixels(), xstart(), xstep(), ypixels(), ystart(), ystep(), zpixels(), zstart(), and zstep().
Referenced by initialize().
interceptSurface()
int Mantid::Geometry::GridDetector::interceptSurface (Track & track) const override virtual
Checks whether the track given will pass through this Component.
Implements Mantid::Geometry::IObjComponent.
Definition at line 734 of file GridDetector.cpp.
isOnSide()
bool Mantid::Geometry::GridDetector::isOnSide (const Kernel::V3D & point) const override virtual
Does the point given lie on the surface of this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 728 of file GridDetector.cpp.
isValid()
bool Mantid::Geometry::GridDetector::isValid (const Kernel::V3D & point) const override virtual
Does the point given lie within this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 722 of file GridDetector.cpp.
material()
const Kernel::Material Mantid::Geometry::GridDetector::material () const override virtual
Returns the material of the detector.
Implements Mantid::Geometry::IObjComponent.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 833 of file GridDetector.cpp.
maxDetectorID()
detid_t Mantid::Geometry::GridDetector::maxDetectorID ()
maximum detector id
Returns the maximum detector id.
Returns
maximum detector id
Definition at line 614 of file GridDetector.cpp.
References m_gridBase, Mantid::Geometry::Component::m_map, and m_maxDetId.
Referenced by export_GridDetector().
minDetectorID()
detid_t Mantid::Geometry::GridDetector::minDetectorID ()
minimum detector id
Returns the minimum detector id.
Returns
minimum detector id
Definition at line 604 of file GridDetector.cpp.
References m_gridBase, Mantid::Geometry::Component::m_map, and m_minDetId.
Referenced by export_GridDetector().
operator=()
GridDetector & Mantid::Geometry::GridDetector::operator= (const ICompAssembly &) private
Private copy assignment operator.
registerContents()
size_t Mantid::Geometry::GridDetector::registerContents (class ComponentVisitor & componentVisitor) const override virtual
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 835 of file GridDetector.cpp.
References Mantid::Geometry::ComponentVisitor::registerGridBank().
shape()
const std::shared_ptr< const IObject > Mantid::Geometry::GridDetector::shape () const override virtual
Returns the shape of the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 813 of file GridDetector.cpp.
References Mantid::Geometry::ShapeFactory::createShape(), m_xpixels, m_ypixels, and m_zpixels.
Referenced by Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
solidAngle()
double Mantid::Geometry::GridDetector::solidAngle (const Kernel::V3D & observer) const override virtual
Finds the approximate solid angle covered by the component when viewed from the point given.
Implements Mantid::Geometry::IObjComponent.
Definition at line 741 of file GridDetector.cpp.
testIntersectionWithChildren()
void Mantid::Geometry::GridDetector::testIntersectionWithChildren (Track & testRay, std::deque< IComponent_const_sptr > & searchQueue) const override virtual
Test the intersection of the ray with the children of the component assembly, for InstrumentRayTracer.
Uses the knowledge of the GridDetector shape to significantly speed up tracking.
Parameters
testRay :: Track under test. The results are stored here.
searchQueue :: If a child is a sub-assembly then it is appended for later searching. Unused.
Base point (x,y,z) = position of pixel 0,0
Vertical (y-axis) basis vector of the detector
Horizontal (x-axis) basis vector of the detector
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 651 of file GridDetector.cpp.
References Mantid::Geometry::Track::addLink(), Mantid::Geometry::Track::direction(), getAtXYZ(), Mantid::Kernel::Matrix< T >::Invert(), Mantid::Kernel::Matrix< T >::setColumn(), Mantid::Geometry::Track::startPoint(), xpixels(), and ypixels().
type()
std::string Mantid::Geometry::GridDetector::type () const inline override virtual
String description of the type of component.
Reimplemented from Mantid::Geometry::CompAssembly.
Reimplemented in Mantid::Geometry::RectangularDetector.
Definition at line 39 of file GridDetector.h.
validateInput()
void Mantid::Geometry::GridDetector::validateInput () const private
Definition at line 494 of file GridDetector.cpp.
References Mantid::Geometry::checkValidOrderString(), m_idFillOrder, m_xpixels, and m_ypixels.
Referenced by initializeValues().
xpixels()
int Mantid::Geometry::GridDetector::xpixels () const
Returns the number of pixels in the X direction.
Returns
number of X pixels
Definition at line 232 of file GridDetector.cpp.
References m_gridBase, Mantid::Geometry::Component::m_map, and m_xpixels.
Referenced by export_GridDetector(), getAtXYZ(), getBoundingBox(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::RectangularDetector::getTextureSize(), Mantid::Geometry::getXYZFillFirstY(), Mantid::Geometry::getXYZFillFirstZ(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), initializeValues(), testIntersectionWithChildren(), and Mantid::Geometry::RectangularDetector::testIntersectionWithChildren().
xsize()
double Mantid::Geometry::GridDetector::xsize () const
Size in X of the detector.
Returns the size in the X direction.
Definition at line 333 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_xsize.
Referenced by export_GridDetector(), and Mantid::Geometry::RectangularDetector::getTextureSize().
xstart()
double Mantid::Geometry::GridDetector::xstart () const
Returns the start position in the X direction.
Definition at line 297 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_xstart.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
xstep()
double Mantid::Geometry::GridDetector::xstep () const
Returns the step size in the X direction.
Definition at line 261 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_xstep.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
ypixels()
int Mantid::Geometry::GridDetector::ypixels () const
Returns the number of pixels in the Y direction.
Returns
number of y pixels
Definition at line 242 of file GridDetector.cpp.
References m_gridBase, Mantid::Geometry::Component::m_map, and m_ypixels.
Referenced by export_GridDetector(), getAtXYZ(), getBoundingBox(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstZ(), Mantid::Geometry::RectangularDetector::getTextureSize(), Mantid::Geometry::getXYZFillFirstX(), Mantid::Geometry::getXYZFillFirstZ(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), initializeValues(), testIntersectionWithChildren(), and Mantid::Geometry::RectangularDetector::testIntersectionWithChildren().
ysize()
double Mantid::Geometry::GridDetector::ysize () const
Size in Y of the detector.
Returns the size in the Y direction.
Definition at line 345 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_ysize.
Referenced by export_GridDetector().
ystart()
double Mantid::Geometry::GridDetector::ystart () const
Returns the start position in the Y direction.
Definition at line 309 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_ystart.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
ystep()
double Mantid::Geometry::GridDetector::ystep () const
Returns the step size in the Y direction.
Definition at line 273 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_ystep.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), Mantid::Geometry::RectangularDetector::initialize(), initialize(), and initializeValues().
zpixels()
int Mantid::Geometry::GridDetector::zpixels () const
Returns the number of pixels in the Z direction.
Returns
number of z pixels
Definition at line 252 of file GridDetector.cpp.
References m_gridBase, Mantid::Geometry::Component::m_map, and m_zpixels.
Referenced by export_GridDetector(), getAtXYZ(), getBoundingBox(), Mantid::Geometry::getFillFirstX(), Mantid::Geometry::getFillFirstY(), Mantid::Geometry::getXYZFillFirstX(), Mantid::Geometry::getXYZFillFirstY(), initialize(), and initializeValues().
zsize()
double Mantid::Geometry::GridDetector::zsize () const
Size in Z of the detector.
Returns the size in the Z direction.
Definition at line 357 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_zsize.
Referenced by export_GridDetector().
zstart()
double Mantid::Geometry::GridDetector::zstart () const
Returns the start position in the Z direction.
Definition at line 321 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_zstart.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), initialize(), and initializeValues().
zstep()
double Mantid::Geometry::GridDetector::zstep () const
Returns the step size in the Z direction.
Definition at line 285 of file GridDetector.cpp.
References Mantid::Geometry::ParameterMap::contains(), Mantid::Geometry::ParameterMap::get(), m_gridBase, Mantid::Geometry::Component::m_map, and m_zstep.
Referenced by export_GridDetector(), Mantid::Geometry::GridDetectorPixel::getRelativePos(), initialize(), and initializeValues().
Friends And Related Function Documentation
GridDetectorPixel
friend class GridDetectorPixel friend
Definition at line 35 of file GridDetector.h.
Referenced by createLayer().
Member Data Documentation
m_gridBase
const GridDetector* Mantid::Geometry::GridDetector::m_gridBase private
Pointer to the base GridDetector, for parametrized instruments.
Definition at line 153 of file GridDetector.h.
Referenced by getDetectorIDAtXYZ(), getRelativePosAtXYZ(), getXYZForDetectorID(), idfillbyfirst_y(), idFillOrder(), idstart(), idstep(), idstepbyrow(), maxDetectorID(), minDetectorID(), xpixels(), xsize(), xstart(), xstep(), ypixels(), ysize(), ystart(), ystep(), zpixels(), zsize(), zstart(), and zstep().
m_idfillbyfirst_y
bool Mantid::Geometry::GridDetector::m_idfillbyfirst_y private
IDs are filled in Y fastest.
Definition at line 195 of file GridDetector.h.
Referenced by idfillbyfirst_y(), init(), and initializeValues().
m_idFillOrder
std::string Mantid::Geometry::GridDetector::m_idFillOrder private
The order in which to fill IDs.
Definition at line 197 of file GridDetector.h.
Referenced by getDetectorIDAtXYZ(), getXYZForDetectorID(), idFillOrder(), initializeValues(), and validateInput().
m_idstart
int Mantid::Geometry::GridDetector::m_idstart private
IDs start here.
Definition at line 193 of file GridDetector.h.
Referenced by getXYZForDetectorID(), idstart(), init(), and initializeValues().
m_idstep
int Mantid::Geometry::GridDetector::m_idstep private
Step size in ID in each col.
Definition at line 201 of file GridDetector.h.
Referenced by getXYZForDetectorID(), idstep(), init(), and initializeValues().
m_idstepbyrow
int Mantid::Geometry::GridDetector::m_idstepbyrow private
Step size in ID in each row.
Definition at line 199 of file GridDetector.h.
Referenced by getXYZForDetectorID(), idstepbyrow(), init(), and initializeValues().
m_maxDetId
detid_t Mantid::Geometry::GridDetector::m_maxDetId private
maximum detector id
Definition at line 190 of file GridDetector.h.
Referenced by init(), initialize(), and maxDetectorID().
m_minDetId
detid_t Mantid::Geometry::GridDetector::m_minDetId private
minimum detector id
Definition at line 188 of file GridDetector.h.
Referenced by init(), initialize(), and minDetectorID().
m_shape
std::shared_ptr<IObject> Mantid::Geometry::GridDetector::m_shape private
Pointer to the shape of the pixels in this detector array.
Definition at line 186 of file GridDetector.h.
Referenced by createLayer(), and initializeValues().
m_xpixels
int Mantid::Geometry::GridDetector::m_xpixels private
The number of pixels in the X (horizontal) direction.
Definition at line 158 of file GridDetector.h.
Referenced by createLayer(), init(), initializeValues(), shape(), validateInput(), and xpixels().
m_xsize
double Mantid::Geometry::GridDetector::m_xsize private
Size in X of the detector.
Definition at line 165 of file GridDetector.h.
Referenced by init(), initializeValues(), and xsize().
m_xstart
double Mantid::Geometry::GridDetector::m_xstart private
X position of the 0-th pixel.
Definition at line 172 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and xstart().
m_xstep
double Mantid::Geometry::GridDetector::m_xstep private
Step size in the X direction of detector.
Definition at line 179 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and xstep().
m_ypixels
int Mantid::Geometry::GridDetector::m_ypixels private
The number of pixels in the Y (vertical) direction.
Definition at line 160 of file GridDetector.h.
Referenced by createLayer(), init(), initializeValues(), shape(), validateInput(), and ypixels().
m_ysize
double Mantid::Geometry::GridDetector::m_ysize private
Size in Y of the detector.
Definition at line 167 of file GridDetector.h.
Referenced by init(), initializeValues(), and ysize().
m_ystart
double Mantid::Geometry::GridDetector::m_ystart private
Y position of the 0-th pixel.
Definition at line 174 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and ystart().
m_ystep
double Mantid::Geometry::GridDetector::m_ystep private
Step size in the Y direction of detector.
Definition at line 181 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and ystep().
m_zpixels
int Mantid::Geometry::GridDetector::m_zpixels private
The number of pixels in the Z (usually beam) direction.
Definition at line 162 of file GridDetector.h.
Referenced by createLayer(), init(), initialize(), initializeValues(), shape(), and zpixels().
m_zsize
double Mantid::Geometry::GridDetector::m_zsize private
Size in Z of the detector.
Definition at line 169 of file GridDetector.h.
Referenced by init(), initializeValues(), and zsize().
m_zstart
double Mantid::Geometry::GridDetector::m_zstart private
Z position of the 0-th pixel.
Definition at line 176 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and zstart().
m_zstep
double Mantid::Geometry::GridDetector::m_zstep private
Step size in the Z direction of the detector.
Definition at line 183 of file GridDetector.h.
Referenced by createLayer(), getRelativePosAtXYZ(), init(), initializeValues(), and zstep().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/GridDetector.h
Framework/Geometry/src/Instrument/GridDetector.cpp