Mantid: MantidQt::MantidWidgets::Batch::CellDelegate Class Reference
MantidQt::MantidWidgets::Batch::CellDelegate Class Reference
#include <CellDelegate.h>
Public Member Functions
CellDelegate (QObject *parent, QTreeView const &view, FilteredTreeModel const &filterModel, QStandardItemModel const &mainModel)
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Private Attributes
FilteredTreeModel const & m_filteredModel
QStandardItemModel const & m_mainModel
QTreeView const & m_view
Detailed Description
Definition at line 20 of file CellDelegate.h.
Constructor & Destructor Documentation
CellDelegate()
MantidQt::MantidWidgets::Batch::CellDelegate::CellDelegate (QObject * parent, QTreeView const & view, FilteredTreeModel const & filterModel, QStandardItemModel const & mainModel) explicit
Definition at line 15 of file CellDelegate.cpp.
Member Function Documentation
paint()
void MantidQt::MantidWidgets::Batch::CellDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 19 of file CellDelegate.cpp.
References MantidQt::MantidWidgets::Batch::fromMainModel(), MantidQt::MantidWidgets::Batch::getBorderColor(), MantidQt::MantidWidgets::Batch::getBorderThickness(), index, m_filteredModel, m_mainModel, m_view, and MantidQt::MantidWidgets::Batch::modelItemFromIndex().
Member Data Documentation
m_filteredModel
FilteredTreeModel const& MantidQt::MantidWidgets::Batch::CellDelegate::m_filteredModel private
Definition at line 28 of file CellDelegate.h.
Referenced by paint().
m_mainModel
QStandardItemModel const& MantidQt::MantidWidgets::Batch::CellDelegate::m_mainModel private
Definition at line 29 of file CellDelegate.h.
Referenced by paint().
m_view
QTreeView const& MantidQt::MantidWidgets::Batch::CellDelegate::m_view private
Definition at line 27 of file CellDelegate.h.
Referenced by paint().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/CellDelegate.h
qt/widgets/common/src/Batch/CellDelegate.cpp