Mantid: Mantid::NeXus::NXRoot Class Reference
Mantid::NeXus::NXRoot Class Reference
Implements NXroot Nexus class.
#include <NexusClasses.h>
Public Member Functions
bool isStandard () const
True if complies with our understanding of the www.nexusformat.org definition.
std::string NX_class () const override
Return the NX class for a class (HDF group) or "SDS" for a data set;.
NXRoot (std::string fname)
Constructor.
NXRoot (std::string fname, const std::string &entry)
Constructor.
NXEntry openEntry (const std::string &name)
Opens an entry – a topmost Nexus class.
NXEntry openFirstEntry ()
Open the first NXentry in the file.
~NXRoot () override
Destructor.
Public Member Functions inherited from Mantid::NeXus::NXClass
void close ()
Close this class.
bool containsDataSet (const std::string &query) const
Returns whether an individual dataset is present.
bool containsGroup (const std::string &query) const
Returns whether an individual group (or group) is present.
std::vector< NXInfo > & datasets () const
Returns a list of all datasets in this NXClass.
NXInfo getDataSetInfo (const std::string &name) const
Returns NXInfo for a dataset.
double getDouble (const std::string &name) const
Returns a double.
float getFloat (const std::string &name) const
Returns a float.
int getInt (const std::string &name) const
Returns a int.
NXClassInfo getNextEntry ()
Returns the class information about the next entry (class or dataset) in this class.
std::string getString (const std::string &name) const
Returns a string.
std::vector< NXClassInfo > & groups () const
Returns a list of all classes (or groups) in this NXClass.
bool isValid (const std::string &path) const
Check if a path exists relative to the current class path.
std::string NX_class () const override
The NX class identifier.
NXClass (const NXClass &parent, const std::string &name)
Constructor.
void open ()
Opens this NXClass using NXopengrouppath. Can be slow (or is slow)
bool openLocal (const std::string &nxclass="")
Opens this NXClass using NXopengroup.
NXChar openNXChar (const std::string &name) const
Creates and opens a char dataset.
template<class NX >
NX openNXClass (const std::string &name) const
Templated method for creating derived NX classes.
template<class T >
NXDataSetTyped< T > openNXDataSet (const std::string &name) const
Templated method for creating datasets.
NXDouble openNXDouble (const std::string &name) const
Creates and opens a double dataset.
NXFloat openNXFloat (const std::string &name) const
Creates and opens a float dataset.
NXClass openNXGroup (const std::string &name) const
Creates and opens an arbitrary (non-standard) class (group).
NXInt openNXInt (const std::string &name) const
Creates and opens an integer dataset.
NXSize openNXSize (const std::string &name) const
Creates and opens a size_t dataset.
void reset ()
Creates a new object in the NeXus file at path path.
Public Member Functions inherited from Mantid::NeXus::NXObject
std::string name () const
Returns the name of the object.
virtual std::string NX_class () const =0
Return the NX class name for a class (HDF group) or "SDS" for a data set;.
NXObject (const NXhandle fileID, const NXClass *parent, const std::string &name)
NXObject constructor.
std::string path () const
Returns the absolute path to the object.
virtual ~NXObject ()=default
Private Attributes
const std::string m_filename
The file name.
Additional Inherited Members
Public Attributes inherited from Mantid::NeXus::NXObject
NXAttributes attributes
Attributes.
NXhandle m_fileID
Nexus file id.
Protected Member Functions inherited from Mantid::NeXus::NXClass
void clear ()
Deletes content of m_groups and m_datasets.
void readAllInfo ()
Fills in m_groups and m_datasets.
Protected Attributes inherited from Mantid::NeXus::NXClass
std::shared_ptr< std::vector< NXInfo > > m_datasets
Holds info about the datasets in this NXClass.
std::shared_ptr< std::vector< NXClassInfo > > m_groups
Holds info about the child NXClasses.
Protected Attributes inherited from Mantid::NeXus::NXObject
bool m_open
Set to true if the object has been open.
std::string m_path
Keeps the absolute path to the object.
Detailed Description
Implements NXroot Nexus class.
Definition at line 922 of file NexusClasses.h.
Constructor & Destructor Documentation
NXRoot() [1/2]
Mantid::NeXus::NXRoot::NXRoot (std::string fname)
Constructor.
On creation opens the Nexus file for reading only.
Parameters
fname :: The file name to open
Definition at line 379 of file NexusClasses.cpp.
References Mantid::NeXus::NXObject::m_fileID, m_filename, and Mantid::NeXus::NXClass::readAllInfo().
NXRoot() [2/2]
Mantid::NeXus::NXRoot::NXRoot (std::string fname, const std::string & entry)
Constructor.
Creates a new Nexus file. The first root entry will be also created.
Parameters
fname :: The file name to create
entry :: The name of the first entry in the new file
Definition at line 394 of file NexusClasses.cpp.
References Mantid::NeXus::NXObject::m_fileID, and m_filename.
~NXRoot()
Mantid::NeXus::NXRoot::~NXRoot () override
Destructor.
Definition at line 403 of file NexusClasses.cpp.
References Mantid::NeXus::NXObject::m_fileID.
Member Function Documentation
isStandard()
bool Mantid::NeXus::NXRoot::isStandard () const
True if complies with our understanding of the www.nexusformat.org definition.
Definition at line 405 of file NexusClasses.cpp.
NX_class()
std::string Mantid::NeXus::NXRoot::NX_class () const inline override virtual
Return the NX class for a class (HDF group) or "SDS" for a data set;.
Reimplemented from Mantid::NeXus::NXClass.
Definition at line 931 of file NexusClasses.h.
openEntry()
NXEntry Mantid::NeXus::NXRoot::openEntry (const std::string & name) inline
Opens an entry – a topmost Nexus class.
Parameters
name :: The name of the entry
Returns
the entry
Definition at line 939 of file NexusClasses.h.
Referenced by Mantid::DataHandling::LoadMuonNexus2::doExec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMuonNexus1::exec(), Mantid::DataHandling::LoadNexus::exec(), Mantid::DataHandling::LoadMuonNexusV2::execLoader(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadData(), Mantid::DataHandling::LoadMuonNexus1::loadDeadTimes(), Mantid::DataHandling::LoadMuonNexus1::loadDetectorGrouping(), Mantid::DataHandling::LoadMuonNexus2::loadDetectorMapping(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadMuonNexus1::loadRunDetails(), Mantid::DataHandling::LoadMuonNexus2::loadRunDetails(), Mantid::DataHandling::LoadNexusProcessed::loadWorkspaceName(), openFirstEntry(), and Mantid::DataHandling::whichNexusType().
openFirstEntry()
NXEntry Mantid::NeXus::NXRoot::openFirstEntry ()
Open the first NXentry in the file.
Definition at line 410 of file NexusClasses.cpp.
References Mantid::NeXus::NXClass::groups(), and openEntry().
Referenced by Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadILLIndirect2::exec(), Mantid::DataHandling::LoadILLReflectometry::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::LoadILLTOF2::exec(), Mantid::DataHandling::LoadLLB::exec(), Mantid::DataHandling::LoadMLZ::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadQKK::exec(), Mantid::DataHandling::LoadSINQFocus::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadEMU< FD >::loadEnvironParameters(), Mantid::DataHandling::LoadPLN::loadEnvironParameters(), Mantid::DataHandling::LoadEMU< FD >::loadParameters(), and Mantid::DataHandling::LoadPLN::loadParameters().
Member Data Documentation
m_filename
const std::string Mantid::NeXus::NXRoot::m_filename private
The file name.
Definition at line 943 of file NexusClasses.h.
Referenced by NXRoot().
The documentation for this class was generated from the following files:
Framework/Nexus/inc/MantidNexus/NexusClasses.h
Framework/Nexus/src/NexusClasses.cpp