Mantid: Mantid::DataHandling::LoadISISNexusHelper Namespace Reference
Mantid::DataHandling::LoadISISNexusHelper Namespace Reference
Functions
std::tuple< Nexus::NXInt, Nexus::NXInt > findDetectorIDsAndSpectrumNumber (const Nexus::NXEntry &entry, const bool hasVMSBlock)
find detector ids and spectrum numbers
int64_t findNumberOfSpectra (const Nexus::NXEntry &entry, const bool hasVMSBlock)
find the number of spectra in the nexus file
void loadRunDetails (API::Run &run, const NXEntry &entry, const bool hasVMSBlock)
Load data about the run.
void loadSampleGeometry (Sample &sample, const NXEntry &entry, const bool hasVMSBlock)
Load geometrical data about the sample from the nexus entry into a workspace.
std::shared_ptr< HistogramData::HistogramX > loadTimeData (const NXEntry &entry)
Load the time data from nexus entry.
Function Documentation
findDetectorIDsAndSpectrumNumber()
std::tuple< NXInt, NXInt > Mantid::DataHandling::LoadISISNexusHelper::findDetectorIDsAndSpectrumNumber (const NXEntry & entry, const bool hasVMSBlock)
find detector ids and spectrum numbers
Find total number of spectra in the nexus file.
Parameters
entry :: The Nexus entry
hasVMSBlock :: Whether the current nexus entry has a vms_compat block
Returns
Returns a pair containing the Detector IDs corresponding Spectrum numbers
Definition at line 52 of file LoadISISNexusHelper.cpp.
References Mantid::Nexus::NXDataSetTyped< T >::load(), Mantid::Nexus::NXClass::openNXGroup(), and Mantid::Nexus::NXClass::openNXInt().
Referenced by Mantid::DataHandling::LoadISISNexus2::exec().
findNumberOfSpectra()
int64_t Mantid::DataHandling::LoadISISNexusHelper::findNumberOfSpectra (const NXEntry & entry, const bool hasVMSBlock)
find the number of spectra in the nexus file
Find total number of spectra in the nexus file.
Parameters
entry :: The Nexus entry
hasVMSBlock :: Whether the current nexus entry has a vms_compat block
Returns
Total number of spectra
Definition at line 27 of file LoadISISNexusHelper.cpp.
References Mantid::Nexus::NXDataSet::dim0(), Mantid::Nexus::NXDataSetTyped< T >::load(), Mantid::Nexus::NXClass::openNXGroup(), and Mantid::Nexus::NXClass::openNXInt().
Referenced by Mantid::DataHandling::LoadISISNexus2::exec().
loadRunDetails()
void Mantid::DataHandling::LoadISISNexusHelper::loadRunDetails (API::Run & run, const NXEntry & entry, const bool hasVMSBlock)
Load data about the run.
Parameters
run :: The run where the information will be stored
entry :: The Nexus entry
hasVMSBlock :: Whether the current nexus entry has a vms_compat
Definition at line 125 of file LoadISISNexusHelper.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::Nexus::NXDataSet::attributes, Mantid::Nexus::NXClass::close(), Mantid::Nexus::NXClass::getFloat(), Mantid::Nexus::NXClass::getInt(), Mantid::Nexus::NXClass::getString(), Mantid::Nexus::NXDataSetTyped< T >::load(), Mantid::Nexus::NXClass::openNXChar(), Mantid::Nexus::NXClass::openNXFloat(), Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), Mantid::API::Run::setProtonCharge(), and std::to_string().
Referenced by Mantid::DataHandling::LoadISISNexus2::loadRunDetails().
loadSampleGeometry()
void Mantid::DataHandling::LoadISISNexusHelper::loadSampleGeometry (Sample & sample, const NXEntry & entry, const bool hasVMSBlock)
Load geometrical data about the sample from the nexus entry into a workspace.
Parameters
sample :: The sample which the geometrical data will be saved into
entry :: The Nexus entry
hasVMSBlock :: Whether the current nexus entry has a vms_compat block
Definition at line 81 of file LoadISISNexusHelper.cpp.
References Mantid::Nexus::NXClass::getFloat(), Mantid::Nexus::NXClass::getString(), height, Mantid::Nexus::NXDataSetTyped< T >::load(), Mantid::Nexus::NXClass::openNXFloat(), Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), Mantid::API::Sample::setGeometryFlag(), Mantid::API::Sample::setHeight(), Mantid::API::Sample::setThickness(), and Mantid::API::Sample::setWidth().
Referenced by Mantid::DataHandling::LoadISISNexus2::loadSampleData().
loadTimeData()
std::shared_ptr< HistogramData::HistogramX > Mantid::DataHandling::LoadISISNexusHelper::loadTimeData (const NXEntry & entry)
Load the time data from nexus entry.
Parameters
entry :: The Nexus entry
Returns
Returns a shared pointer to a HistogramX instance storing the time bins.
Definition at line 204 of file LoadISISNexusHelper.cpp.
References Mantid::Nexus::NXDataSet::dim0(), Mantid::Nexus::NXClass::openNXFloat(), and Mantid::Nexus::NXClass::openNXGroup().
Referenced by Mantid::DataHandling::LoadISISNexus2::exec().