Mantid: Mantid::Kernel::ROI Namespace Reference
Mantid::Kernel::ROI Namespace Reference
Functions
template MANTID_KERNEL_DLL std::vector< std::size_t > calculate_intersection (const std::vector< std::size_t > &left, const std::vector< std::size_t > &right)
template<typename TYPE >
std::vector< TYPE > calculate_intersection (const std::vector< TYPE > &left, const std::vector< TYPE > &right)
This calculates the intersection of two sorted vectors that represent regions of interest (ROI).
template MANTID_KERNEL_DLL std::vector< Types::Core::DateAndTime > calculate_intersection (const std::vector< Types::Core::DateAndTime > &left, const std::vector< Types::Core::DateAndTime > &right)
Function Documentation
calculate_intersection() [1/3]
template MANTID_KERNEL_DLL std::vector< std::size_t > Mantid::Kernel::ROI::calculate_intersection (const std::vector< std::size_t > & left, const std::vector< std::size_t > & right)
calculate_intersection() [2/3]
template<typename TYPE > std::vector< TYPE > Mantid::Kernel::ROI::calculate_intersection (const std::vector< TYPE > & left, const std::vector< TYPE > & right) private
This calculates the intersection of two sorted vectors that represent regions of interest (ROI).
The ROI are pairs of [[include, exclude), [include,exclude), ...] where an empty vector is interpreted to mean "use all".
Definition at line 449 of file TimeROI.cpp.
References left, and right.
Referenced by Mantid::DataHandling::ProcessBankCompressed::collectEvents(), Mantid::DataHandling::PulseIndexer::PulseIndexer(), Mantid::DataHandling::ProcessBankData::run(), and Mantid::Kernel::TimeROI::update_intersection().
calculate_intersection() [3/3]
template MANTID_KERNEL_DLL std::vector< Types::Core::DateAndTime > Mantid::Kernel::ROI::calculate_intersection (const std::vector< Types::Core::DateAndTime > & left, const std::vector< Types::Core::DateAndTime > & right)