Mantid: Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder Namespace Reference
Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder Namespace Reference
Functions
Json::Value & addCylindricalShape (Json::Value &nxDetector, const std::string &name="pixel_shape")
void addCylindricalShapeCylinders (Json::Value &shape, const std::vector< int > &arrayShape={3}, const std::vector< int > &indices={0, 1, 2})
void addCylindricalShapeVertices (Json::Value &shape, const std::vector< int > &arrayShape={3, 3}, const std::vector< double > &vertices={-0.001, 0, 0, 0.001, 0.00405, 0, 0.001, 0, 0})
void addDetectorNumbers (Json::Value &nxDetector, const std::vector< int > &arrayShape, const std::vector< int32_t > &values)
void addDetectorNumbers (Json::Value &nxDetector, const std::vector< int32_t > &arrayShape, const std::vector< int32_t > &values)
Json::Value & addNXChopper (Json::Value &instrument, const std::string &name)
void addNXChopperName (Json::Value &chopper, const std::string &chopperName)
void addNXChopperRadius (Json::Value &chopper, const double radius=350)
void addNXChopperSlitEdges (Json::Value &chopper, const std::vector< double > &edges={0.0, 23.0})
void addNXChopperSlitHeight (Json::Value &chopper, const double slitHeight=150)
void addNXChopperSlits (Json::Value &chopper, const int32_t value)
void addNXChopperTopDeadCenter (Json::Value &chopper, const std::string &topic, const std::string &source, const std::string &writerModule)
Json::Value & addNXDetector (Json::Value &instrument, const std::string &name)
Json::Value & addNXEntry (Json::Value &root, const std::string &name)
Json::Value & addNXInstrument (Json::Value &entry, const std::string &name)
void addNXInstrumentName (Json::Value &instrument, const std::string &name)
Json::Value & addNXMonitor (Json::Value &entry, const std::string &name)
void addNXMonitorDetectorID (Json::Value &monitor, const int32_t detectorID)
void addNXMonitorEventStreamInfo (Json::Value &monitor, const std::string &topic, const std::string &source, const std::string &writerModule)
void addNXMonitorName (Json::Value &monitor, const std::string &name)
void addNXMonitorWaveformStreamInfo (Json::Value &monitor, const std::string &topic, const std::string &source, const std::string &writerModule)
Json::Value & addNXSample (Json::Value &entry, const std::string &name)
Json::Value & addNXSource (Json::Value &instrument, const std::string &name)
Json::Value & addNXTransformation (Json::Value &nxDetector, const std::string &name)
void addNXTransformationBeamDirectionOffset (Json::Value &nxTransformation, const std::vector< int > &arrayShape={1}, const std::vector< double > &values={0.049}, const std::vector< double > &vec={0, 0, -1})
void addNXTransformationDependency (Json::Value &nxDetector, const std::string &dependencyPath)
void addNXTransformationLocation (Json::Value &nxTransformation, const std::vector< int > &arrayShape={1}, const std::vector< double > &values={0.971}, const std::vector< double > &vec={1, 0, 0})
void addNXTransformationOrientation (Json::Value &nxTransformation, const std::vector< int > &arrayShape={1}, const std::vector< double > &values={90}, const std::vector< double > &vec={0, 1, 0})
Json::Value & addOffShape (Json::Value &nxDetector, const std::string &name="pixel_shape")
void addOffShapeFaces (Json::Value &shape, const std::vector< int > &arrayShape={1}, const std::vector< int > &faces={0})
void addOffShapeVertices (Json::Value &shape, const std::vector< int > &arrayShape={4, 3}, const std::vector< double > &vertices={-0.001, -0.001, 0, 0.001, -0.001, 0, 0.001, 0.001, 0, -0.001, 0.001, 0})
void addOffShapeWindingOrder (Json::Value &shape, const std::vector< int > &arrayShape={4}, const std::vector< int > &windingOrder={0, 1, 2, 3})
void addXPixelOffset (Json::Value &nxDetector, const std::vector< int > &arrayShape, const std::vector< double > &values)
void addXPixelOffset (Json::Value &nxDetector, const std::vector< int32_t > &arrayShape, const std::vector< double > &values)
void addYPixelOffset (Json::Value &nxDetector, const std::vector< int > &arrayShape, const std::vector< double > &values)
void addYPixelOffset (Json::Value &nxDetector, const std::vector< int32_t > &arrayShape, const std::vector< double > &values)
void addZPixelOffset (Json::Value &nxDetector, const std::vector< int > &arrayShape, const std::vector< double > &values)
void addZPixelOffset (Json::Value &nxDetector, const std::vector< int32_t > &arrayShape, const std::vector< double > &values)
const std::string convertToString (const Json::Value &value)
void initialiseRoot (const Json::Value &root, const std::string &name)
Function Documentation
addCylindricalShape()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShape (Json::Value & nxDetector, const std::string & name = "pixel_shape")
Definition at line 325 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), and Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry().
addCylindricalShapeCylinders()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeCylinders (Json::Value & shape, const std::vector< int > & arrayShape = {3}, const std::vector< int > & indices = {0, 1, 2})
Definition at line 329 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), and Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry().
addCylindricalShapeVertices()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addCylindricalShapeVertices (Json::Value & shape, const std::vector< int > & arrayShape = {3, 3}, const std::vector< double > & vertices = {-0.001, 0, 0, 0.001, 0.00405, 0, 0.001, 0, 0})
Definition at line 334 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), and Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry().
addDetectorNumbers() [1/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers (Json::Value & nxDetector, const std::vector< int > & arrayShape, const std::vector< int32_t > & values)
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addDetectorNumbers() [2/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addDetectorNumbers (Json::Value & nxDetector, const std::vector< int32_t > & arrayShape, const std::vector< int32_t > & values)
Definition at line 288 of file JSONGeometryParserTestHelper.cpp.
addNXChopper()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopper (Json::Value & instrument, const std::string & name)
Definition at line 217 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation().
addNXChopperName()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperName (Json::Value & chopper, const std::string & chopperName)
Definition at line 221 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXChopperRadius()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperRadius (Json::Value & chopper, const double radius = 350)
Definition at line 227 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXChopperSlitEdges()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlitEdges (Json::Value & chopper, const std::vector< double > & edges = {0.0, 23.0})
Definition at line 234 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXChopperSlitHeight()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlitHeight (Json::Value & chopper, const double slitHeight = 150)
Definition at line 238 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXChopperSlits()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperSlits (Json::Value & chopper, const int32_t value)
Definition at line 245 of file JSONGeometryParserTestHelper.cpp.
References value.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXChopperTopDeadCenter()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXChopperTopDeadCenter (Json::Value & chopper, const std::string & topic, const std::string & source, const std::string & writerModule)
Definition at line 251 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper().
addNXDetector()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXDetector (Json::Value & instrument, const std::string & name)
Definition at line 256 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addNXEntry()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXEntry (Json::Value & root, const std::string & name)
Definition at line 176 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors(), Mantid::FrameworkTestHelpers::getJSONGeometryNoInstrument(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoSample(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addNXInstrument()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrument (Json::Value & entry, const std::string & name)
Definition at line 182 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addNXInstrumentName()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXInstrumentName (Json::Value & instrument, const std::string & name)
Definition at line 184 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), and Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset().
addNXMonitor()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitor (Json::Value & entry, const std::string & name)
Definition at line 194 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation().
addNXMonitorDetectorID()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorDetectorID (Json::Value & monitor, const int32_t detectorID)
Definition at line 201 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), and Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape().
addNXMonitorEventStreamInfo()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorEventStreamInfo (Json::Value & monitor, const std::string & topic, const std::string & source, const std::string & writerModule)
Definition at line 207 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), and Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape().
addNXMonitorName()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorName (Json::Value & monitor, const std::string & name)
Definition at line 195 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), and Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape().
addNXMonitorWaveformStreamInfo()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXMonitorWaveformStreamInfo (Json::Value & monitor, const std::string & topic, const std::string & source, const std::string & writerModule)
Definition at line 212 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), and Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape().
addNXSample()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSample (Json::Value & entry, const std::string & name)
Definition at line 180 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors(), Mantid::FrameworkTestHelpers::getJSONGeometryNoInstrument(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addNXSource()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXSource (Json::Value & instrument, const std::string & name)
Definition at line 190 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource().
addNXTransformation()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformation (Json::Value & nxDetector, const std::string & name)
Definition at line 266 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation().
addNXTransformationBeamDirectionOffset()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationBeamDirectionOffset (Json::Value & nxTransformation, const std::vector< int > & arrayShape = {1}, const std::vector< double > & values = {0.049}, const std::vector< double > & vec = {0, 0, -1})
Definition at line 270 of file JSONGeometryParserTestHelper.cpp.
References vec.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation().
addNXTransformationDependency()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationDependency (Json::Value & nxDetector, const std::string & dependencyPath)
Definition at line 260 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations().
addNXTransformationLocation()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationLocation (Json::Value & nxTransformation, const std::vector< int > & arrayShape = {1}, const std::vector< double > & values = {0.971}, const std::vector< double > & vec = {1, 0, 0})
Definition at line 276 of file JSONGeometryParserTestHelper.cpp.
References vec.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation().
addNXTransformationOrientation()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addNXTransformationOrientation (Json::Value & nxTransformation, const std::vector< int > & arrayShape = {1}, const std::vector< double > & values = {90}, const std::vector< double > & vec = {0, 1, 0})
Definition at line 283 of file JSONGeometryParserTestHelper.cpp.
References vec.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation().
addOffShape()
Json::Value & Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShape (Json::Value & nxDetector, const std::string & name = "pixel_shape")
Definition at line 308 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations().
addOffShapeFaces()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeFaces (Json::Value & shape, const std::vector< int > & arrayShape = {1}, const std::vector< int > & faces = {0})
Definition at line 312 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations().
addOffShapeVertices()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeVertices (Json::Value & shape, const std::vector< int > & arrayShape = {4, 3}, const std::vector< double > & vertices = {-0.001, -0.001, 0, 0.001, -0.001, 0, 0.001, 0.001, 0, -0.001, 0.001, 0})
Definition at line 316 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations().
addOffShapeWindingOrder()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addOffShapeWindingOrder (Json::Value & shape, const std::vector< int > & arrayShape = {4}, const std::vector< int > & windingOrder = {0, 1, 2, 3})
Definition at line 320 of file JSONGeometryParserTestHelper.cpp.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), and Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations().
addXPixelOffset() [1/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset (Json::Value & nxDetector, const std::vector< int > & arrayShape, const std::vector< double > & values)
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
addXPixelOffset() [2/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addXPixelOffset (Json::Value & nxDetector, const std::vector< int32_t > & arrayShape, const std::vector< double > & values)
Definition at line 293 of file JSONGeometryParserTestHelper.cpp.
addYPixelOffset() [1/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset (Json::Value & nxDetector, const std::vector< int > & arrayShape, const std::vector< double > & values)
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape().
addYPixelOffset() [2/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addYPixelOffset (Json::Value & nxDetector, const std::vector< int32_t > & arrayShape, const std::vector< double > & values)
Definition at line 298 of file JSONGeometryParserTestHelper.cpp.
addZPixelOffset() [1/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addZPixelOffset (Json::Value & nxDetector, const std::vector< int > & arrayShape, const std::vector< double > & values)
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset().
addZPixelOffset() [2/2]
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::addZPixelOffset (Json::Value & nxDetector, const std::vector< int32_t > & arrayShape, const std::vector< double > & values)
Definition at line 303 of file JSONGeometryParserTestHelper.cpp.
convertToString()
const std::string Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::convertToString (const Json::Value & value)
Definition at line 339 of file JSONGeometryParserTestHelper.cpp.
References value.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors(), Mantid::FrameworkTestHelpers::getJSONGeometryNoInstrument(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoSample(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().
initialiseRoot()
void Mantid::FrameworkTestHelpers::JSONTestInstrumentBuilder::initialiseRoot (const Json::Value & root, const std::string & name)
Definition at line 174 of file JSONGeometryParserTestHelper.cpp.
References name.
Referenced by Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleCylindrical(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleOFF(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithChopper(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitor(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithMonitorNoShape(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithSource(), Mantid::FrameworkTestHelpers::getFullJSONInstrumentSimpleWithZPixelOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryEmptyOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidCylindricalGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryInvalidOffGeometry(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingBeamDirectionOffset(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingChopperInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingMonitorInformation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingOrientation(), Mantid::FrameworkTestHelpers::getJSONGeometryMissingTransformations(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectorIDs(), Mantid::FrameworkTestHelpers::getJSONGeometryNoDetectors(), Mantid::FrameworkTestHelpers::getJSONGeometryNoInstrument(), Mantid::FrameworkTestHelpers::getJSONGeometryNoPixelShape(), Mantid::FrameworkTestHelpers::getJSONGeometryNoSample(), Mantid::FrameworkTestHelpers::getJSONGeometryNoXPixelOffset(), and Mantid::FrameworkTestHelpers::getJSONGeometryNoYPixelOffset().