Mantid: MantidQt::MantidWidgets::ImageInfoWidget Class Reference
MantidQt::MantidWidgets::ImageInfoWidget Class Reference
A table widget containing information about the pixel the mouse is over in an image.
#include <ImageInfoWidget.h>
Public Member Functions
void cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues) override
ImageInfoWidget (QWidget *parent=nullptr)
Constructor.
void setWorkspace (const Mantid::API::Workspace_sptr &ws) override
Set the workspace to probe for information.
void showInfo (const ImageInfoModel::ImageInfo &info) override
Display the information provided within the table cells.
Public Member Functions inherited from MantidQt::MantidWidgets::IImageInfoWidget
virtual void cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues)=0
IImageInfoWidget (QWidget *parent=nullptr)
virtual void setWorkspace (const Mantid::API::Workspace_sptr &ws)=0
virtual void showInfo (const ImageInfoModel::ImageInfo &info)=0
Private Attributes
std::unique_ptr< ImageInfoPresenter > m_presenter
Detailed Description
A table widget containing information about the pixel the mouse is over in an image.
Definition at line 22 of file ImageInfoWidget.h.
Constructor & Destructor Documentation
ImageInfoWidget()
MantidQt::MantidWidgets::ImageInfoWidget::ImageInfoWidget (QWidget * parent = nullptr)
Constructor.
Parameters
parent A QWidget to act as the parent widget
Definition at line 21 of file ImageInfoWidget.cpp.
Member Function Documentation
cursorAt()
void MantidQt::MantidWidgets::ImageInfoWidget::cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues) override virtual
Parameters
x X position if the cursor
y Y position if the cursor
signal Signal value at cursor position
extraValues A map of extra column names and values to display
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 35 of file ImageInfoWidget.cpp.
References m_presenter, Mantid::Geometry::x, and Mantid::Geometry::y.
setWorkspace()
void MantidQt::MantidWidgets::ImageInfoWidget::setWorkspace (const Mantid::API::Workspace_sptr & ws) override virtual
Set the workspace to probe for information.
Parameters
ws A pointer to a Workspace object
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 66 of file ImageInfoWidget.cpp.
References m_presenter.
showInfo()
void MantidQt::MantidWidgets::ImageInfoWidget::showInfo (const ImageInfoModel::ImageInfo & info) override virtual
Display the information provided within the table cells.
Parameters
info A reference to a collection of header/value pairs
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 44 of file ImageInfoWidget.cpp.
References MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::empty(), MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::name(), MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::size(), value, and MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::value().
Member Data Documentation
m_presenter
std::unique_ptr<ImageInfoPresenter> MantidQt::MantidWidgets::ImageInfoWidget::m_presenter private
Definition at line 36 of file ImageInfoWidget.h.
Referenced by cursorAt(), and setWorkspace().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoWidget.h
qt/widgets/common/src/ImageInfoWidget.cpp