Mantid: MantidQt::MantidWidgets::ImageInfoModel Class Reference
MantidQt::MantidWidgets::ImageInfoModel Class Reference abstract
#include <ImageInfoModel.h>
Classes
class ImageInfo
Public Member Functions
virtual ImageInfoModel::ImageInfo info (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues) const =0
Creates information about the point at the given coordinates in the workspace.
virtual ~ImageInfoModel ()=default
Static Public Member Functions
static const QString defaultFormat (const double x)
static const QString defaultFormat (const int x)
Static Public Attributes
static constexpr auto DecimalFormat = 'f'
Default float format.
static constexpr auto FourDigitPrecision = 4
Default float precision.
static const QString MissingValue = QString("-")
MissingValue identifier.
static constexpr auto UnsetValue = std::numeric_limits<double>::max()
Value to indicate that a MissingValue should be shown.
Detailed Description
Definition at line 22 of file ImageInfoModel.h.
Constructor & Destructor Documentation
~ImageInfoModel()
virtual MantidQt::MantidWidgets::ImageInfoModel::~ImageInfoModel () virtual default
Member Function Documentation
defaultFormat() [1/2]
static const QString MantidQt::MantidWidgets::ImageInfoModel::defaultFormat (const double x) inline static
Definition at line 47 of file ImageInfoModel.h.
References Mantid::Geometry::x.
Referenced by MantidQt::MantidWidgets::ImageInfoModelMatrixWS::info(), MantidQt::MantidWidgets::ImageInfoModelMD::info(), and MantidQt::MantidWidgets::ImageInfoModelMatrixWS::setUnitsInfo().
defaultFormat() [2/2]
static const QString MantidQt::MantidWidgets::ImageInfoModel::defaultFormat (const int x) inline static
Definition at line 53 of file ImageInfoModel.h.
References Mantid::Geometry::x.
info()
virtual ImageInfoModel::ImageInfo MantidQt::MantidWidgets::ImageInfoModel::info (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues) const pure virtual
Creates information about the point at the given coordinates in the workspace.
Parameters
x x data coordinate
y y data coordinate
signal the signal value at x, y
extraValues extra values to be displayed in the image info table
Returns
An ImageInfo object
Implemented in MantidQt::MantidWidgets::ImageInfoModelMatrixWS, and MantidQt::MantidWidgets::ImageInfoModelMD.
Member Data Documentation
DecimalFormat
constexpr auto MantidQt::MantidWidgets::ImageInfoModel::DecimalFormat = 'f' static constexpr
Default float format.
Definition at line 41 of file ImageInfoModel.h.
FourDigitPrecision
constexpr auto MantidQt::MantidWidgets::ImageInfoModel::FourDigitPrecision = 4 static constexpr
Default float precision.
Definition at line 39 of file ImageInfoModel.h.
MissingValue
const QString MantidQt::MantidWidgets::ImageInfoModel::MissingValue = QString("-") inline static
MissingValue identifier.
Definition at line 45 of file ImageInfoModel.h.
Referenced by MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::ImageInfo(), and MantidQt::MantidWidgets::ImageInfoModelMD::info().
UnsetValue
constexpr auto MantidQt::MantidWidgets::ImageInfoModel::UnsetValue = std::numeric_limits<double>::max() static constexpr
Value to indicate that a MissingValue should be shown.
Definition at line 43 of file ImageInfoModel.h.
Referenced by MantidQt::MantidWidgets::ImageInfoModelMatrixWS::info(), and MantidQt::MantidWidgets::ImageInfoModelMD::info().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoModel.h