Mantid: MantidQt::MantidWidgets::SetAttribute Class Reference
MantidQt::MantidWidgets::SetAttribute Class Reference
Visitor setting new attribute value.
Public Member Functions
SetAttribute (FitPropertyBrowser *browser, QtProperty *prop, Mantid::Kernel::IValidator_sptr validator=Mantid::Kernel::IValidator_sptr())
Public Member Functions inherited from Mantid::API::IFunction::AttributeVisitor< T >
T operator() (bool &b) const
implements static_visitor's operator() for bool
T operator() (double &d) const
implements static_visitor's operator() for double
T operator() (int &i) const
implements static_visitor's operator() for int
T operator() (std::string &str) const
implements static_visitor's operator() for std::string
T operator() (std::vector< double > &v) const
implements static_visitor's operator() for vector
virtual ~AttributeVisitor ()=default
Virtual destructor.
Protected Member Functions
void apply (bool &b) const override
Create bool property.
void apply (double &d) const override
Create double property.
void apply (int &i) const override
Create int property.
void apply (std::string &str) const override
Create string property.
void apply (std::vector< double > &v) const override
Create vector property.
Protected Member Functions inherited from Mantid::API::IFunction::AttributeVisitor< T >
virtual T apply (bool &) const =0
Implement this method to access attribute as bool.
virtual T apply (double &) const =0
Implement this method to access attribute as double.
virtual T apply (int &) const =0
Implement this method to access attribute as int.
virtual T apply (std::string &) const =0
Implement this method to access attribute as string.
virtual T apply (std::vector< double > &) const =0
Implement this method to access attribute as vector.
template<typename T1 >
void evaluateValidator (T1 &inputData) const
Evaluates the validator associated with attribute this visitor is to visit.
Private Attributes
FitPropertyBrowser * m_browser
QtProperty * m_prop
Additional Inherited Members
Protected Attributes inherited from Mantid::API::IFunction::AttributeVisitor< T >
Mantid::Kernel::IValidator_sptr m_validator = Mantid::Kernel::IValidator_sptr()
Validator against which to evaluate attribute value to set.
Detailed Description
Visitor setting new attribute value.
Depending on the attribute type the appropriate apply method is used.
Definition at line 665 of file PropertyHandler.cpp.
Constructor & Destructor Documentation
SetAttribute()
MantidQt::MantidWidgets::SetAttribute::SetAttribute (FitPropertyBrowser * browser, QtProperty * prop, Mantid::Kernel::IValidator_sptr validator = Mantid::Kernel::IValidator_sptr()) inline
Definition at line 667 of file PropertyHandler.cpp.
References Mantid::API::IFunction::AttributeVisitor< T >::m_validator.
Member Function Documentation
apply() [1/5]
void MantidQt::MantidWidgets::SetAttribute::apply (bool & b) const inline override protected virtual
Create bool property.
Implements Mantid::API::IFunction::AttributeVisitor< T >.
Definition at line 696 of file PropertyHandler.cpp.
References Mantid::API::IFunction::AttributeVisitor< T >::evaluateValidator(), MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, m_browser, and m_prop.
apply() [2/5]
void MantidQt::MantidWidgets::SetAttribute::apply (double & d) const inline override protected virtual
Create double property.
Implements Mantid::API::IFunction::AttributeVisitor< T >.
Definition at line 682 of file PropertyHandler.cpp.
References Mantid::Geometry::d, Mantid::API::IFunction::AttributeVisitor< T >::evaluateValidator(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager, and m_prop.
apply() [3/5]
void MantidQt::MantidWidgets::SetAttribute::apply (int & i) const inline override protected virtual
Create int property.
Implements Mantid::API::IFunction::AttributeVisitor< T >.
Definition at line 689 of file PropertyHandler.cpp.
References Mantid::API::IFunction::AttributeVisitor< T >::evaluateValidator(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_intManager, and m_prop.
apply() [4/5]
void MantidQt::MantidWidgets::SetAttribute::apply (std::string & str) const inline override protected virtual
Create string property.
Implements Mantid::API::IFunction::AttributeVisitor< T >.
Definition at line 675 of file PropertyHandler.cpp.
References Mantid::API::IFunction::AttributeVisitor< T >::evaluateValidator(), MantidQt::MantidWidgets::FitPropertyBrowser::getStringPropertyValue(), m_browser, and m_prop.
apply() [5/5]
void MantidQt::MantidWidgets::SetAttribute::apply (std::vector< double > & v) const inline override protected virtual
Create vector property.
Implements Mantid::API::IFunction::AttributeVisitor< T >.
Definition at line 703 of file PropertyHandler.cpp.
References Mantid::API::IFunction::AttributeVisitor< T >::evaluateValidator(), m_browser, m_prop, Mantid::API::IFunction::AttributeVisitor< T >::m_validator, MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorDoubleManager, and MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorSizeManager.
Member Data Documentation
m_browser
FitPropertyBrowser* MantidQt::MantidWidgets::SetAttribute::m_browser private
Definition at line 738 of file PropertyHandler.cpp.
Referenced by apply().
m_prop
QtProperty* MantidQt::MantidWidgets::SetAttribute::m_prop private
Definition at line 739 of file PropertyHandler.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
qt/widgets/common/src/PropertyHandler.cpp