Mantid: Mantid::PythonInterface::TypedValidatorExporter< Type > Struct Template Reference
Mantid::PythonInterface::TypedValidatorExporter< Type > Struct Template Reference
Declares a simple static struct to export a TypedValidator to Python.
#include <TypedValidatorExporter.h>
Static Public Member Functions
static void define (const char *pythonClassName)
Detailed Description
template<typename Type>
struct Mantid::PythonInterface::TypedValidatorExporter< Type >
Declares a simple static struct to export a TypedValidator to Python.
Template Parameters
HeldType The type held within the validator
Definition at line 18 of file TypedValidatorExporter.h.
Member Function Documentation
define()
template<typename Type > static void Mantid::PythonInterface::TypedValidatorExporter< Type >::define (const char * pythonClassName) inline static
Definition at line 19 of file TypedValidatorExporter.h.
Referenced by export_InstrumentValidator(), export_MatrixWorkspaceValidator(), and export_OrientedLatticeValidator().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/TypedValidatorExporter.h