Mantid: ICat4::ns1__create Class Reference
ICat4::ns1__create Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__create ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__entityBaseBean * bean
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 453 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__create()
ICat4::ns1__create::ns1__create () inline
Definition at line 465 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__create::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21794 of file ICat4C.cpp.
References bean, sessionId, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::soap_in_ns1__create(), ICat4::soap_new_req_ns1__create(), and ICat4::soap_new_set_ns1__create().
soap_get()
void * ICat4::ns1__create::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21894 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__create().
soap_in()
void * ICat4::ns1__create::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21826 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__create().
Referenced by ICat4::soap_in_ns1__create().
soap_out()
int ICat4::ns1__create::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21810 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__create().
Referenced by soap_put().
soap_put()
int ICat4::ns1__create::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21887 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__create.
soap_serialize()
void ICat4::ns1__create::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21801 of file ICat4C.cpp.
References bean, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTons1__entityBaseBean(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__searchResponse().
soap_type()
int ICat4::ns1__create::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 458 of file ICat4Stub.h.
Member Data Documentation
bean
ns1__entityBaseBean* ICat4::ns1__create::bean
Definition at line 456 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset(), soap_default(), and soap_serialize().
sessionId
std::string* ICat4::ns1__create::sessionId
Definition at line 455 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::createMantidDataset(), soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp