Mantid: Mantid::API::Algorithm Class Reference
Mantid::API::Algorithm Class Reference abstract
Base class from which all concrete algorithm classes should be derived.
#include <Algorithm.h>
Classes
class AlgorithmNotification
Base class for algorithm notifications.
class CancelException
CancelException is thrown to cancel execution of the algorithm.
class ErrorNotification
ErrorNotification is sent when an exception is caught during execution of the algorithm.
class FinishedNotification
FinishedNotification is sent after the algorithm finishes its execution.
class ProgressNotification
An algorithm can report its progress by sending ProgressNotification.
class StartedNotification
StartedNotification is sent when the algorithm begins execution.
Public Member Functions
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
IAlgorithm methods
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Asynchronous Execution
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Serialization functions
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
virtual void init ()=0
Virtual method - must be overridden by concrete algorithm.
virtual void exec ()=0
Virtual method - must be overridden by concrete algorithm.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
Algorithm Information
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
const std::string name () const override=0
function to return a name of the algorithm, must be overridden in all algorithms
int version () const override=0
function to return a version of the algorithm, must be overridden in all algorithms
const std::string summary () const override=0
function returns a summary message that will be displayed in the default GUI, and in the help.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Progress Reporting functions
class Progress
class WorkspaceHistory
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
std::unique_ptr< Poco::ActiveMethod< bool, Poco::Void, Algorithm, Poco::ActiveStarter< Algorithm > > > m_executeAsync
Poco::ActiveMethod used to implement asynchronous execution.
std::unique_ptr< Poco::NotificationCenter > m_notificationCenter
Sends notifications to observers.
std::unique_ptr< Poco::NObserver< Algorithm, ProgressNotification > > m_progressObserver
Child algorithm progress observer.
std::atomic< ExecutionState > m_executionState
the current execution state
std::atomic< ResultState > m_resultState
the current result State
bool m_isChildAlgorithm
Algorithm is a child algorithm.
bool m_recordHistoryForChild
Flag to indicate whether history should be recorded.
bool m_alwaysStoreInADS
Always store in the ADS, even for child algos.
bool m_runningAsync
Algorithm is running asynchronously.
bool m_rethrow
Algorithm should rethrow exceptions while executing.
bool m_isAlgStartupLoggingEnabled
double m_startChildProgress
Whether to log alg startup and closedown messages from the base class (default = true)
double m_endChildProgress
Keeps value for algorithm's progress at Child Algorithm's finish.
AlgorithmID m_algorithmID
Algorithm ID for managed algorithms.
std::vector< std::weak_ptr< IAlgorithm > > m_ChildAlgorithms
A list of weak pointers to any child algorithms created.
WorkspaceVector m_readLockedWorkspaces
Vector of all the workspaces that have been read-locked.
WorkspaceVector m_writeLockedWorkspaces
Vector of all the workspaces that have been write-locked.
std::vector< IWorkspaceProperty * > m_outputWorkspaceProps
All the WorkspaceProperties that are Output or InOut. Set in execute()
std::vector< IWorkspaceProperty * > m_pureOutputWorkspaceProps
All the WorkspaceProperties that are Output (not inOut). Set in execute()
std::vector< std::shared_ptr< WorkspaceGroup > > m_groupWorkspaces
Pointer to the WorkspaceGroup (if any) for each input workspace property.
int m_singleGroup
If only one input is a group, this is its index. -1 if they are all groups.
bool m_groupsHaveSimilarNames
All the groups have similar names (group_1, group_2 etc.)
std::vector< Workspace_sptr > m_inputWorkspaceHistories
Store a pointer to the input workspace histories so they can be copied to the outputs to avoid anything being overwritten.
std::vector< std::string > m_reservedList
Reserved property names.
Mantid::Types::Core::DateAndTime m_gcTime
The earliest this class should be considered for garbage collection.
Mantid::Kernel::PropertyManagerOwner m_properties
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
template<typename T1 , typename T2 , typename WsType >
void doSetInputProperties (const std::string &name, const T1 &wksp, IndexType type, const T2 &list)
void lockWorkspaces ()
Go through the workspace properties of this algorithm and lock the workspaces for reading or writing.
void unlockWorkspaces ()
Unlock any previously locked workspaces.
void clearWorkspaceCaches ()
Clear any internal workspace handles so that workspaces will be deleted promptly after a managed algorithm finishes.
void linkHistoryWithLastChild ()
Link the name of the output workspaces on this parent algorithm.
void logAlgorithmInfo () const
Sends out algorithm parameter information to the logger.
bool executeInternal ()
Invoced internally in execute()
bool executeAsyncImpl (const Poco::Void &i)
Callback when an algorithm is executed asynchronously.
bool doCallProcessGroups (Mantid::Types::Core::DateAndTime &start_time)
Calls process groups with the required timing checks and algorithm execution finalization steps.
void reportCompleted (const double &duration, const bool groupProcessing=false)
Report that the algorithm has completed.
void registerFeatureUsage () const
Registers the usage of the algorithm with the UsageService.
bool isCompoundProperty (const std::string &name) const
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Detailed Description
Base class from which all concrete algorithm classes should be derived.
In order for a concrete algorithm class to do anything useful the methods init() & exec() should be overridden.
Further text from Gaudi file....... The base class provides utility methods for accessing standard services (event data service etc.); for declaring properties which may be configured by the job options service; and for creating Child Algorithms. The only base class functionality which may be used in the constructor of a concrete algorithm is the declaration of member variables as properties. All other functionality, i.e. the use of services and the creation of Child Algorithms, may be used only in initialise() and afterwards (see the Gaudi user guide).
Author
Russell Taylor, Tessella Support Services plc
Based on the Gaudi class of the same name (see http://proj-gaudi.web.cern.ch/proj-gaudi/)
Date
12/09/2007
Definition at line 76 of file Algorithm.h.
Member Typedef Documentation
WorkspaceVector
using Mantid::API::Algorithm::WorkspaceVector = std::vector<std::shared_ptr<Workspace> >
Definition at line 282 of file Algorithm.h.
Constructor & Destructor Documentation
Algorithm() [1/2]
Mantid::API::Algorithm::Algorithm ()
Constructor.
Definition at line 111 of file Algorithm.cpp.
Algorithm() [2/2]
Mantid::API::Algorithm::Algorithm (const Algorithm &) delete
~Algorithm()
Mantid::API::Algorithm::~Algorithm () override default
Virtual destructor.
Member Function Documentation
addObserver()
void Mantid::API::Algorithm::addObserver (const Poco::AbstractObserver & observer) const override virtual
Add an observer for a notification.
Add an observer to a notification.
Parameters
observer :: Reference to the observer to add
Implements Mantid::API::IAlgorithm.
Definition at line 220 of file Algorithm.cpp.
References notificationCenter().
addTimer()
void Mantid::API::Algorithm::addTimer (const std::string & name, const Kernel::time_point_ns & begin, const Kernel::time_point_ns & end)
Definition at line 29 of file AlgorithmExecuteProfile.cpp.
References name().
Referenced by Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::Algorithms::Bin2DPowderDiffraction::exec(), Mantid::Algorithms::FilterEvents::exec(), Mantid::DataHandling::CompressEvents::exec(), Mantid::Algorithms::MaskBins::execEvent(), Mantid::Algorithms::FilterEvents::filterEvents(), and Mantid::Algorithms::RemovePromptPulse::getTofRange().
afterPropertySet()
void Mantid::API::Algorithm::afterPropertySet (const std::string & name) override virtual
Override this method to perform a custom action right after a property was set.
The argument is the property name. Default - do nothing.
The argument is the property name. Default - do nothing.
Parameters
name :: A property name.
Reimplemented from Mantid::Kernel::IPropertyManager.
Reimplemented in Mantid::CurveFitting::IFittingAlgorithm.
Definition at line 2023 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::afterPropertySet(), m_properties, and name().
Referenced by setPropertyOrdinal(), setPropertyValue(), and setPropertyValueFromJson().
alias()
const std::string Mantid::API::Algorithm::alias () const inline override virtual
function to return any aliases to the algorithm; A default implementation is provided
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::Load, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::UpdateInstrumentFromFile, and Mantid::MDAlgorithms::TransposeMD.
Definition at line 170 of file Algorithm.h.
aliasDeprecated()
const std::string Mantid::API::Algorithm::aliasDeprecated () const inline override virtual
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
Implements Mantid::API::IAlgorithm.
Definition at line 175 of file Algorithm.h.
asJson()
Json::Value Mantid::API::Algorithm::asJson (bool withDefaultValues = false) const override virtual
Return the property manager serialized as a json object.
Parameters
withDefaultValues :: If true then the value of default parameters will be included
Returns
A jsonValue of the manager
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1992 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::asJson(), and m_properties.
asString()
std::string Mantid::API::Algorithm::asString (bool withDefaultValues = false) const override virtual
Return the property manager serialized as a string.
The format is propName=value,propName=value,propName=value
Parameters
withDefaultValues :: If true then the value of default parameters will be included
Returns
A stringized version of the manager
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1985 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::asString(), and m_properties.
cacheInputWorkspaceHistories()
void Mantid::API::Algorithm::cacheInputWorkspaceHistories () protected
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
Definition at line 371 of file Algorithm.cpp.
References getProperties(), group, Mantid::Kernel::Direction::InOut, Mantid::Kernel::Direction::Input, m_inputWorkspaceHistories, and trackingHistory().
Referenced by executeInternal().
cacheWorkspaceProperties()
void Mantid::API::Algorithm::cacheWorkspaceProperties () protected
Go through the properties and cache the input/output workspace properties for later use.
Definition at line 339 of file Algorithm.cpp.
References getProperties(), Mantid::Kernel::Direction::InOut, Mantid::Kernel::Direction::Input, m_inputWorkspaceProps, m_outputWorkspaceProps, m_pureOutputWorkspaceProps, and Mantid::Kernel::Direction::Output.
Referenced by executeInternal().
cancel()
void Mantid::API::Algorithm::cancel () override virtual
Raises the cancel flag.
Cancel an algorithm.
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::DataHandling::Load.
Definition at line 1662 of file Algorithm.cpp.
References m_cancel, and m_ChildAlgorithms.
Referenced by Mantid::ICat::CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(), and Mantid::ICat::CatalogPublish::publish().
categories()
const std::vector< std::string > Mantid::API::Algorithm::categories () const override virtual
Function to return all of the categories that contain this algorithm.
Implements Mantid::API::IAlgorithm.
Definition at line 246 of file Algorithm.cpp.
References Mantid::Kernel::StringTokenizer::asVector(), category(), categorySeparator(), Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY, and Mantid::Kernel::StringTokenizer::TOK_TRIM.
category()
const std::string Mantid::API::Algorithm::category () const inline override virtual
function to return a category of the algorithm.
A default implementation is provided
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::CurveFitting::IFittingAlgorithm, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficienciesBase, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDParent, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, and Mantid::DataHandling::SetSample.
Definition at line 160 of file Algorithm.h.
Referenced by categories().
categorySeparator()
const std::string Mantid::API::Algorithm::categorySeparator () const inline override virtual
Function to return the separator token for the category string.
A default implementation ';' is provided
Implements Mantid::API::IAlgorithm.
Definition at line 165 of file Algorithm.h.
Referenced by categories().
checkGroups()
bool Mantid::API::Algorithm::checkGroups () virtual
Check the input workspace properties for groups.
If there are more than one input workspace properties, then:
All inputs should be groups of the same size
In this case, algorithms are processed in order
OR, only one input should be a group, the others being size of 1
If the property itself is a WorkspaceProperty<WorkspaceGroup> then this returns false
Returns true if processGroups() should be called. It also sets up some other members.
Override if it is needed to customize the group checking.
Exceptions
std::invalid_argument if the groups sizes are incompatible.
std::invalid_argument if a member is not found
This method (or an override) must NOT THROW any exception if there are no input workspace groups
Reimplemented in Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Stitch1DMany, Mantid::API::MultiPeriodGroupAlgorithm, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::ICat::CatalogPublish, and Mantid::PythonInterface::RunPythonScript.
Definition at line 1172 of file Algorithm.cpp.
References Mantid::API::WorkspaceGroup::areNamesSimilar(), Mantid::API::WorkspaceProperty< TYPE >::getWorkspace(), m_groupsHaveSimilarNames, m_groupSize, m_groupWorkspaces, m_inputWorkspaceProps, m_singleGroup, and m_unrolledInputWorkspaces.
Referenced by Mantid::Algorithms::DeleteWorkspace::checkGroups(), Mantid::API::MultiPeriodGroupAlgorithm::checkGroups(), and executeInternal().
clear()
void Mantid::API::Algorithm::clear () override virtual
Clears all properties under management.
Implements Mantid::Kernel::IPropertyManager.
Definition at line 2015 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::clear(), and m_properties.
Referenced by Mantid::Algorithms::DetectorEfficiencyCor::DetectorEfficiencyCor(), Mantid::Algorithms::BinaryOperation::do2D(), Mantid::Algorithms::He3TubeEfficiency::He3TubeEfficiency(), and Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::~VesuvioCalculateGammaBackground().
clearWorkspaceCaches()
void Mantid::API::Algorithm::clearWorkspaceCaches () private
Clear any internal workspace handles so that workspaces will be deleted promptly after a managed algorithm finishes.
Definition at line 507 of file Algorithm.cpp.
References m_groupWorkspaces, m_inputWorkspaceHistories, m_inputWorkspaceProps, m_outputWorkspaceProps, m_pureOutputWorkspaceProps, and m_unrolledInputWorkspaces.
Referenced by executeInternal().
copyNonWorkspaceProperties()
void Mantid::API::Algorithm::copyNonWorkspaceProperties (IAlgorithm * alg, int periodNum)
Copy all the non-workspace properties from this to alg.
Parameters
alg :: other IAlgorithm
periodNum :: number of the "period" = the entry in the group + 1
Definition at line 1541 of file Algorithm.cpp.
References getProperties(), Mantid::API::IAlgorithm::name(), and setOtherProperties().
Referenced by processGroups(), and Mantid::API::MultiPeriodGroupWorker::processGroups().
copyPropertiesFrom()
virtual void Mantid::API::Algorithm::copyPropertiesFrom (const Algorithm & alg) inline virtual
Make m_properties point to the same PropertyManager as alg.m_properties.
Definition at line 320 of file Algorithm.h.
References m_properties.
Referenced by Mantid::DataHandling::LoadMuonNexusV2::runLoadISISNexus().
createChildAlgorithm()
Algorithm_sptr Mantid::API::Algorithm::createChildAlgorithm (const std::string & name, const double startProgress = -1., const double endProgress = -1., const bool enableLogging = true, const int & version = -1) virtual
Create a Child Algorithm.
A call to this method creates a child algorithm object. Using this mechanism instead of creating daughter algorithms directly via the new operator is prefered since then the framework can take care of all of the necessary book-keeping.
Parameters
name :: The concrete algorithm class of the Child Algorithm
startProgress :: The percentage progress value of the overall algorithm where this child algorithm starts
endProgress :: The percentage progress value of the overall algorithm where this child algorithm ends
enableLogging :: Set to false to disable logging from the child algorithm
version :: The version of the child algorithm to create. By default gives the latest version.
Returns
shared pointer to the newly created algorithm object
Reimplemented in Mantid::API::NexusFileLoader.
Definition at line 860 of file Algorithm.cpp.
References name(), setupAsChildAlgorithm(), and version().
Referenced by Mantid::Algorithms::PolarizationCorrectionFredrikze::add(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::addAdditionalLogs(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::addWorkspaceToDiscus2DData(), Mantid::Crystal::SCDCalibratePanels2::adjustComponent(), Mantid::DataHandling::CreateSimulationWorkspace::adjustInstrument(), Mantid::Algorithms::ConvertUnits::alignBins(), Mantid::Algorithms::DirectILLTubeBackground::applyDiagnostics(), Mantid::Algorithms::DetectorDiagnostic::applyMask(), Mantid::DataHandling::LoadIsawDetCal::applyScalings(), Mantid::DataHandling::LoadILLSANS::applySensitivityMap(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::MDAlgorithms::MDNorm::binBackgroundWS(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::binEvent(), Mantid::MDAlgorithms::MDNormDirectSC::binInputWS(), Mantid::MDAlgorithms::MDNormSCD::binInputWS(), Mantid::MDAlgorithms::MDNorm::binInputWS(), Mantid::Algorithms::GetAllEi::buildWorkspaceToFit(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcDepolarizedProportion(), Mantid::Algorithms::FitOneSinglePeak::calChiSquareSD(), Mantid::Algorithms::CalculateEfficiency2::calculateEfficiency(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3::calculateExtentsFromData(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateFunctionStatistic(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcWavelengthDependentTransmission(), Mantid::WorkflowAlgorithms::StepScan::cloneInputWorkspace(), Mantid::Algorithms::Stitch::cloneWorkspaces(), Mantid::Algorithms::Stitch1D::conjoinXAxis(), Mantid::DataHandling::LoadILLDiffraction::convertAxisAndTranspose(), Mantid::CurveFitting::Algorithms::SplineInterpolation::convertBinnedData(), Mantid::CurveFitting::Algorithms::SplineSmoothing::convertBinnedData(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::convertInputToY(), Mantid::DataHandling::LoadILLPolarizedDiffraction::convertSpectrumAxis(), Mantid::DataHandling::LoadILLReflectometry::convertTofToWavelength(), Mantid::CurveFitting::Algorithms::SplineSmoothing::convertToHistogram(), Mantid::Algorithms::PolarizationEfficiencyCor::convertToHistogram(), Mantid::Algorithms::CalculateIqt::convertToPointData(), Mantid::Algorithms::DetectorDiagnostic::convertToRate(), Mantid::Algorithms::DiffractionFocussing::convertUnitsToDSpacing(), Mantid::DataHandling::LoadDaveGrp::convertWorkspaceToHistogram(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::convertWsBothAxesToPoints(), Mantid::Algorithms::WienerSmooth::copyInput(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::copyLogs(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::copyLogs(), Mantid::Algorithms::RemoveSpectra::copySpectraFromInputToOutput(), Mantid::Algorithms::PDCalibration::createCalTableFromExisting(), Mantid::Algorithms::PDCalibration::createCalTableNew(), Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::DataHandling::LoadISISPolarizationEfficiencies::createEfficiencies(), WorkspaceCreationHelper::createEventWorkspace3(), Mantid::DataHandling::CreateSimulationWorkspace::createInstrument(), Mantid::Algorithms::ChangeTimeZero::createOutputWS(), Mantid::DataHandling::LoadPSIMuonBin::createSampleLogAlgorithm(), Mantid::Algorithms::RemoveBins::crop(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::cropHisto(), Mantid::Algorithms::DirectILLTubeBackground::cropToComponent(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), Mantid::Algorithms::CalculateIqt::cropWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::cropWorkspace(), Mantid::Algorithms::CalculateIqt::divide(), Mantid::MDAlgorithms::MDNorm::divideMD(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::Algorithms::DetectorDiagnostic::doDetVanTest(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakBackground(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doFitFunction(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitGaussianPeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitNPeaksSimple(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::DataHandling::LoadFITS::doLoadFiles(), Mantid::Algorithms::CompareWorkspaces::doMDComparison(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Crystal::StatisticsOfPeaksWorkspace::doSortHKL(), Mantid::Algorithms::Stitch1DMany::doStitch1D(), Mantid::Algorithms::Stitch1DMany::doStitch1DMany(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::Algorithms::ApplyDetailedBalance::exec(), Mantid::Algorithms::ApplyFloodWorkspace::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering2::exec(), Mantid::Algorithms::CalculatePolynomialBackground::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::ChangeLogTime::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CorelliCalibrationApply::exec(), Mantid::Algorithms::CreateBootstrapWorkspaces::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::CropWorkspace::exec(), Mantid::Algorithms::CropWorkspaceRagged::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DeleteWorkspaces::exec(), Mantid::Algorithms::DetectorDiagnostic::exec(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::ExtractFFTSpectrum::exec(), Mantid::Algorithms::ExtractSingleSpectrum::exec(), Mantid::Algorithms::ExtractUnmaskedSpectra::exec(), Mantid::Algorithms::FFTSmooth::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FindCenterOfMassPosition2::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::IdentifyNoisyDetectors::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::IntegrateEPP::exec(), Mantid::Algorithms::InvertMask::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::Max::exec(), Mantid::Algorithms::Min::exec(), Mantid::Algorithms::MultipleScatteringCorrection::exec(), Mantid::Algorithms::NormaliseByDetector::exec(), Mantid::Algorithms::NormaliseToUnity::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin2D::exec(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::RemoveMaskedSpectra::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::RenameWorkspaces::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::ResetNegatives::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::ShiftLogTime::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::Algorithms::SofQWPolygon::exec(), Mantid::Algorithms::SphericalAbsorption::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Algorithms::SumNeighbours::exec(), Mantid::Algorithms::XrayAbsorptionCorrection::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::ExtractPolarizationEfficiencies::exec(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadCalFile::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadIsawDetCal::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::RotateSource::exec(), Mantid::DataHandling::SaveGSASInstrumentFile::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SaveNXSPE::exec(), Mantid::DataHandling::SavePAR::exec(), Mantid::DataHandling::SavePHX::exec(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::BinaryOperationMD::exec(), Mantid::MDAlgorithms::ChangeQConvention::exec(), Mantid::MDAlgorithms::CompactMD::exec(), Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MergeMDFiles::exec(), Mantid::MDAlgorithms::SaveMD2::exec(), Mantid::MDAlgorithms::SetMDUsingMask::exec(), Mantid::MDAlgorithms::ThresholdMD::exec(), Mantid::MDAlgorithms::TransformMD::exec(), Mantid::MDAlgorithms::UnaryOperationMD::exec(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::HFIRSANSNormalise::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::WorkflowAlgorithms::StepScan::exec(), Mantid::Algorithms::FFTDerivative::execComplexFFT(), Mantid::CurveFitting::Algorithms::DoublePulseFit::execConcrete(), Mantid::Algorithms::PolarizationEfficiencyCor::execFredrikze(), Mantid::WorkflowAlgorithms::DgsRemap::execGrouping(), Mantid::WorkflowAlgorithms::DgsRemap::execMasking(), Mantid::Algorithms::PolarizationCorrectionFredrikze::execPA(), Mantid::Algorithms::PolarizationEfficiencyCor::execWildes(), Mantid::Algorithms::CalculateIqt::extractFFTSpectrum(), Mantid::Algorithms::NormaliseToMonitor::extractMonitorSpectra(), Mantid::Algorithms::GetEi::extractSpec(), Mantid::Algorithms::CalculateTransmission::extractSpectra(), Mantid::DataHandling::LoadPSIMuonBin::extractSpectra(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::extractSpectrum(), Mantid::Algorithms::GetEi2::extractSpectrum(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::finaliseMinimizerOutput(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::finaliseOutputWorkspaces(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::finaliseOutputWorkspacesWithAppend(), Mantid::MDAlgorithms::LoadSQW2::finalize(), Mantid::Crystal::SCDCalibratePanels::findL1(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::Algorithms::FindPeaks::findPeakBackground(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Algorithms::DirectILLTubeBackground::fitComponentBackground(), Mantid::Algorithms::CalculateTransmission::fitData(), Mantid::Algorithms::HeliumAnalyserEfficiency::fitDecayTime(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitFunction(), Mantid::Algorithms::FitPeaks::fitFunctionMD(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionMD(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionSD(), Mantid::Algorithms::FindEPP::fitGaussian(), Mantid::Algorithms::HeliumAnalyserEfficiency::fitHe3Polarization(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::Crystal::PeakIntegration::fitneighbours(), Mantid::Algorithms::CalculateTransmission::fitPolynomial(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::Algorithms::FitPeaks::fitSpectrumPeaks(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::fitToData(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::DataHandling::ApplyDiffCal::getCalibrationWS(), Mantid::Algorithms::PolarizationCorrectionFredrikze::getEfficiencyWorkspace(), Mantid::Algorithms::DiffractionFocussing2::getGroupingWorkspace(), Mantid::Algorithms::CreateFloodWorkspace::getInputWorkspace(), Mantid::Algorithms::Integration::getInputWorkspace(), Mantid::Algorithms::CreateGroupingWorkspace::getInstrument(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::DataHandling::LoadDiffCal::getInstrument(), Mantid::Crystal::LoadIsawSpectrum::getInstrument3Ways(), Mantid::DataHandling::LoadCalFile::getInstrument3Ways(), Mantid::Algorithms::TOFSANSResolutionByPixel::getModeratorWorkspace(), Mantid::Algorithms::MedianDetectorTest::getSolidAngles(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::getTimeDifference(), Mantid::Algorithms::HeliumAnalyserEfficiency::getTimeDifferences(), Mantid::Algorithms::PolarizationCorrectionWildes::groupOutput(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::Algorithms::FindPeaksConvolve::groupOutputWorkspaces(), Mantid::Algorithms::GetEiMonDet3::groupSpectra(), Mantid::Algorithms::BinaryOperation::handleSpecialDivideMinus(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initTargetWSDescr(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initTargetWSDescr(), Mantid::MDAlgorithms::SaveIsawQvector::initTargetWSDescr(), Mantid::Algorithms::CreateFloodWorkspace::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Algorithms::DetectorDiagnostic::integrateSpectra(), Mantid::Algorithms::FindDeadDetectors::integrateWorkspace(), Mantid::Algorithms::SumRowColumn::integrateWorkspace(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::integrateWS(), Mantid::Algorithms::CalculateIqt::integration(), Mantid::Algorithms::Stitch1D::integration(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::intensity(), Mantid::Algorithms::PolarizationEfficiencyCor::interpolate(), Mantid::DataHandling::JoinISISPolarizationEfficiencies::interpolateHistogramWorkspace(), Mantid::DataHandling::LoadMask::intializeMaskWorkspace(), Mantid::Algorithms::CalculateFlatBackground::LinearFit(), Mantid::Algorithms::PDCalibration::load(), Mantid::WorkflowAlgorithms::SANSBeamFinder::loadBeamFinderFile(), Mantid::DataHandling::ApplyDiffCal::loadCalFile(), Mantid::DataHandling::Load::loadFileToWs(), Mantid::DataHandling::SaveGSASInstrumentFile::loadFullprofResolutionFile(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::DataHandling::LoadPLN::loadInstrument(), Mantid::DataHandling::LoadSwans::loadInstrument(), Mantid::DataHandling::LoadNGEM::loadInstrument(), Mantid::DataHandling::LoadSpiceXML2DDet::loadInstrument(), Mantid::DataHandling::LoadISISNexus2::loadLogs(), Mantid::DataHandling::LoadIDFFromNexus::loadParameterFile(), Mantid::DataHandling::LoadMLZ::loadRunDetails(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::loadRunToMatrixWS(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::loadSpiceData(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadTwoThetaDetectors(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::WorkflowAlgorithms::SANSBeamFinder::maskEdges(), Mantid::Algorithms::CalculateEfficiency::maskEdges(), Mantid::Algorithms::Stitch::merge(), Mantid::Algorithms::CalculateEfficiency2::mergeGroup(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::movedetector(), Mantid::DataHandling::LoadILLSANS::moveDetectorDistance(), Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal(), Mantid::DataHandling::LoadILLSANS::moveDetectorVertical(), Mantid::DataHandling::LoadILLSANS::moveSource(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter(), Mantid::Algorithms::PolarizationCorrectionFredrikze::multiply(), Mantid::Algorithms::NormaliseToMonitor::normaliseByIntegratedCount(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::normalize(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::Crystal::SCDCalibratePanels2::optimizeL1(), Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos(), Mantid::Crystal::SCDCalibratePanels2::optimizeT0(), Mantid::Algorithms::FindPeaksConvolve::outputIntermediateWorkspace(), Mantid::Algorithms::GetEiMonDet3::peakPosition(), Mantid::CurveFitting::Algorithms::SplineSmoothing::performAdditionalFitting(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::DataHandling::LoadILLSANS::placeD16(), Mantid::DataHandling::Load::plusWs(), Mantid::Algorithms::HeliumAnalyserEfficiency::prepareOutputTable(), processGroups(), Mantid::API::MultiPeriodGroupWorker::processGroups(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::Algorithms::NormaliseByDetector::processHistograms(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::processIndirectFitParameters(), Mantid::DataHandling::LoadPSIMuonBin::processLine(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromEventWS(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromHistoWS(), Mantid::Algorithms::Integration::rangeFilterEventWorkspace(), Mantid::Crystal::LoadIsawPeaks::readHeader(), Mantid::Algorithms::PDCalibration::rebin(), Mantid::Algorithms::GetEi2::rebin(), Mantid::Algorithms::UnwrapMonitor::rebin(), Mantid::Algorithms::CalculateIqt::rebin(), Mantid::Algorithms::CalculateTransmission::rebin(), Mantid::Algorithms::Stitch1D::rebin(), Mantid::Algorithms::MergeRuns::rebinInput(), Mantid::Algorithms::DiffractionFocussing::RebinWorkspace(), Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::Algorithms::AddTimeSeriesLog::removeExisting(), Mantid::Crystal::SCDCalibratePanels2::removeUnindexedPeaks(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::renameWorkspaces(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::renameWorkspaces(), Mantid::Algorithms::SumSpectra::replaceSpecialValues(), Mantid::Algorithms::CalculateIqt::replaceSpecialValues(), Mantid::DataHandling::LoadILLSANS::rotateInstrument(), Mantid::DataHandling::LoadILLIndirect2::rotateTubes(), Mantid::Algorithms::AnnularRingAbsorption::runCreateSampleShape(), Mantid::WorkflowAlgorithms::StepScan::runFilterByXValue(), Mantid::DataHandling::MaskDetectorsInShape::runFindDetectorsInShape(), Mantid::Algorithms::HRPDSlabCanAbsorption::runFlatPlateAbsorption(), Mantid::DataHandling::LoadDiffCal::runLoadCalFile(), Mantid::DataHandling::LoadEmptyInstrument::runLoadIDFFromNexus(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), Mantid::DataHandling::LoadHFIRSANS::runLoadInstrument(), Mantid::DataHandling::LoadMLZ::runLoadInstrument(), Mantid::DataHandling::LoadSINQFocus::runLoadInstrument(), Mantid::DataHandling::LoadEventPreNexus2::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadEmptyInstrument::runLoadInstrument(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadInstrument(), Mantid::DataHandling::LoadCanSAS1D::runLoadInstrument(), Mantid::DataHandling::LoadSpice2D::runLoadInstrument(), Mantid::DataHandling::LoadPreNexusMonitors::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadInstrument(), Mantid::DataHandling::LoadISISNexus2::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrumentFromRaw(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadNexusMonitors2::runLoadLogs(), Mantid::DataHandling::LoadRawHelper::runLoadMappingTable(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadNexus::runLoadNexusProcessed(), Mantid::DataHandling::LoadInstrument::runLoadParameterFile(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::Algorithms::UnwrapSNS::runMaskDetectors(), Mantid::WorkflowAlgorithms::StepScan::runMaskDetectors(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::runMaskDetectors(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::runMaskDetectors(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::runMaskDetectors(), Mantid::MDAlgorithms::IntegratePeaksMD2::runMaskDetectors(), Mantid::Algorithms::AnnularRingAbsorption::runMonteCarloAbsorptionCorrection(), Mantid::MDAlgorithms::ConvertToMDParent::runPreprocessDetectorsToMDChildUpdatingMasks(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::Algorithms::AnnularRingAbsorption::runSetSampleMaterial(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::DataHandling::GenerateGroupingPowder::saveAsNexus(), Mantid::DataHandling::GenerateGroupingPowder2::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder2::saveAsXML(), Mantid::Crystal::SCDCalibratePanels2::saveCalibrationTable(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveNexus(), Mantid::Algorithms::FlipperEfficiency::saveToFile(), Mantid::Algorithms::PolarizerEfficiency::saveToFile(), Mantid::Algorithms::Stitch::scale(), Mantid::Algorithms::Stitch::scaleManual(), Mantid::Crystal::SCDCalibratePanels2::selectPeaksByBankName(), Mantid::DataHandling::LoadILLSALSA::setInstrument(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::DataHandling::LoadPLN::setupDetectorMasks(), Mantid::MDAlgorithms::LoadSQW2::setupFileBackend(), Mantid::MDAlgorithms::ConvertToMD::setupFileBackend(), Mantid::Algorithms::TOFSANSResolutionByPixel::setupOutputWorkspace(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::setupTransferMatrix(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::Algorithms::ChangeTimeZero::shiftTimeOfNeutrons(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::Algorithms::WienerSmooth::smoothSingleSpectrum(), Mantid::Algorithms::PDCalibration::sortTableWorkspace(), Mantid::Algorithms::CombineDiffCal::sortTableWorkspace(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::sumSpectra(), Mantid::Algorithms::CreateFloodWorkspace::transpose(), Mantid::MDAlgorithms::TransformMD::transposeMD(), Mantid::MDAlgorithms::ReplicateMD::transposeMD(), Mantid::DataHandling::LoadILLPolarizedDiffraction::transposeMonochromatic(), Mantid::Crystal::SCDCalibratePanels2::updateUBMatrix(), Mantid::Algorithms::DepolarizedAnalyserTransmission::validateInputs(), and Mantid::Algorithms::Stitch1D::weightedMean().
declareOrReplaceProperty()
void Mantid::API::Algorithm::declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string & doc = "") override virtual
Add or replace property in the list of managed properties.
Parameters
p :: The property object to add
doc :: A description of the property that may be displayed to users
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1811 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::declareOrReplaceProperty(), and m_properties.
Referenced by Mantid::DataHandling::Load::setOutputProperties().
declareProperty() [1/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const std::string & doc, IValidator_sptr validator = std::make_shared<NullValidator>(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The (optional) documentation string
validator :: Pointer to the (optional) validator. Ownership will be taken over.
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 166 of file IPropertyManager.h.
declareProperty() [2/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const unsigned int direction) inline
Add a property of string type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 183 of file IPropertyManager.h.
declareProperty() [3/8]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = std::string(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator. Ownership will be taken over.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 137 of file IPropertyManager.h.
declareProperty() [4/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const std::string & doc, const unsigned int direction = Direction::Input) inline
Add a property to the list of managed properties with no validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The documentation string
direction :: The (optional) direction of the property, in (default), out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 98 of file IPropertyManager.h.
declareProperty() [5/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const unsigned int direction) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 113 of file IPropertyManager.h.
declareProperty() [6/8]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = "", const unsigned int direction = Direction::Input) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 81 of file IPropertyManager.h.
declareProperty() [7/8]
void Mantid::API::Algorithm::declareProperty (std::unique_ptr< Kernel::Property > p, const std::string & doc = "") override virtual
Add a property to the list of managed properties.
Parameters
p :: The property object to add
doc :: A description of the property that may be displayed to users
Exceptions
Exception::ExistsError if a property with the given name already exists
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1803 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::declareProperty(), and m_properties.
Referenced by Mantid::CurveFitting::Functions::UserFunction1D::AddVariable(), Mantid::DataHandling::LoadCanSAS1D::appendDataToOutput(), Mantid::CurveFitting::Algorithms::Fit::copyMinimizerOutput(), Mantid::Algorithms::SofQW::createCommonInputProperties(), Mantid::DataHandling::LoadNGEM::createCountWorkspace(), Mantid::DataHandling::LoadRawHelper::createMonitorWorkspace(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::CurveFitting::Algorithms::DoublePulseFit::declareAdditionalProperties(), Mantid::CurveFitting::Functions::UserFunction1D::declareAdditionalProperties(), Mantid::CurveFitting::IFittingAlgorithm::declareCostFunctionProperty(), Mantid::Algorithms::HeliumAnalyserEfficiency::declareFitProperties(), Mantid::Algorithms::HeliumAnalyserEfficiency::declareInputProperties(), Mantid::DataHandling::Load::declareLoaderProperties(), Mantid::Algorithms::HeliumAnalyserEfficiency::declareOutputProperties(), Mantid::Algorithms::SpectrumAlgorithm::declareWorkspaceIndexSetProperties(), declareWorkspaceInputProperties(), Mantid::Algorithms::AnyShapeAbsorption::defineProperties(), Mantid::Algorithms::CylinderAbsorption::defineProperties(), Mantid::Algorithms::ExponentialCorrection::defineProperties(), Mantid::Algorithms::FlatPlateAbsorption::defineProperties(), Mantid::Algorithms::Logarithm::defineProperties(), Mantid::Algorithms::OneMinusExponentialCor::defineProperties(), Mantid::Algorithms::PolynomialCorrection::defineProperties(), Mantid::Algorithms::Power::defineProperties(), Mantid::Algorithms::PowerLawCorrection::defineProperties(), Mantid::Algorithms::ReplaceSpecialValues::defineProperties(), Mantid::DataHandling::LoadSpice2D::detectorDistance(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::RenameWorkspaces::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::DataHandling::LoadCalFile::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::execConcrete(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::Crystal::LoadIsawSpectrum::getInstrument3WaysInit(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::Algorithms::AbsorptionCorrection::init(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::init(), Mantid::Algorithms::AddLogInterpolated::init(), Mantid::Algorithms::AddLogSmoothed::init(), Mantid::Algorithms::AddPeak::init(), Mantid::Algorithms::AddSampleLog::init(), Mantid::Algorithms::AddTimeSeriesLog::init(), Mantid::Algorithms::AnnularRingAbsorption::init(), Mantid::Algorithms::AppendSpectra::init(), Mantid::Algorithms::ApplyCalibration::init(), Mantid::Algorithms::ApplyFloodWorkspace::init(), Mantid::Algorithms::ApplyInstrumentToPeaks::init(), Mantid::Algorithms::ApplyTransmissionCorrection::init(), Mantid::Algorithms::AverageLogData::init(), Mantid::Algorithms::Bin2DPowderDiffraction::init(), Mantid::Algorithms::BinaryOperateMasks::init(), Mantid::Algorithms::BinaryOperation::init(), Mantid::Algorithms::CalculateCountRate::init(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::CalculateDynamicRange::init(), Mantid::Algorithms::CalculateEfficiency::init(), Mantid::Algorithms::CalculateEfficiency2::init(), Mantid::Algorithms::CalculateFlatBackground::init(), Mantid::Algorithms::CalculateIqt::init(), Mantid::Algorithms::CalculatePlaczek::init(), Mantid::Algorithms::CalculatePolynomialBackground::init(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::init(), Mantid::Algorithms::ChangeLogTime::init(), Mantid::Algorithms::ChangePulsetime::init(), Mantid::Algorithms::ChangePulsetime2::init(), Mantid::Algorithms::ChangeTimeZero::init(), Mantid::Algorithms::ClearInstrumentParameters::init(), Mantid::Algorithms::ClearMaskFlag::init(), Mantid::Algorithms::CloneWorkspace::init(), Mantid::Algorithms::CombineDiffCal::init(), Mantid::Algorithms::CombineTableWorkspaces::init(), Mantid::Algorithms::Comment::init(), Mantid::Algorithms::CompareWorkspaces::init(), Mantid::Algorithms::ConjoinXRuns::init(), Mantid::Algorithms::ConvertAxesToRealSpace::init(), Mantid::Algorithms::ConvertAxisByFormula::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::ConvertFromDistribution::init(), Mantid::Algorithms::ConvertSpectrumAxis::init(), Mantid::Algorithms::ConvertSpectrumAxis2::init(), Mantid::Algorithms::ConvertTableToMatrixWorkspace::init(), Mantid::Algorithms::ConvertToConstantL2::init(), Mantid::Algorithms::ConvertToDistribution::init(), Mantid::Algorithms::ConvertToMatrixWorkspace::init(), Mantid::Algorithms::ConvertUnits::init(), Mantid::Algorithms::CopyDataRange::init(), Mantid::Algorithms::CopyDetectorMapping::init(), Mantid::Algorithms::CopyInstrumentParameters::init(), Mantid::Algorithms::CopyLogs::init(), Mantid::Algorithms::CopySample::init(), Mantid::Algorithms::CorrectKiKf::init(), Mantid::Algorithms::CorrectToFile::init(), Mantid::Algorithms::CreateBootstrapWorkspaces::init(), Mantid::Algorithms::CreateCalFileByNames::init(), Mantid::Algorithms::CreateDummyCalFile::init(), Mantid::Algorithms::CreateEPP::init(), Mantid::Algorithms::CreateFlatEventWorkspace::init(), Mantid::Algorithms::CreateFloodWorkspace::init(), Mantid::Algorithms::CreateGroupingWorkspace::init(), Mantid::Algorithms::CreateLogPropertyTable::init(), Mantid::Algorithms::CreateMonteCarloWorkspace::init(), Mantid::Algorithms::CreatePeaksWorkspace::init(), Mantid::Algorithms::CreatePSDBleedMask::init(), Mantid::Algorithms::CreateSampleWorkspace::init(), Mantid::Algorithms::CreateUserDefinedBackground::init(), Mantid::Algorithms::CropWorkspace::init(), Mantid::Algorithms::CrossCorrelate::init(), Mantid::Algorithms::DeadTimeCorrection::init(), Mantid::Algorithms::DeleteLog::init(), Mantid::Algorithms::DetectorDiagnostic::init(), Mantid::Algorithms::DetectorEfficiencyCor::init(), Mantid::Algorithms::DetectorEfficiencyCorUser::init(), Mantid::Algorithms::DetectorEfficiencyVariation::init(), Mantid::Algorithms::DetermineSpinStateOrder::init(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::init(), Mantid::Algorithms::DiffractionFocussing::init(), Mantid::Algorithms::DirectILLTubeBackground::init(), Mantid::Algorithms::EditInstrumentGeometry::init(), Mantid::Algorithms::ElasticWindow::init(), Mantid::Algorithms::EQSANSCorrectFrame::init(), Mantid::Algorithms::EQSANSTofStructure::init(), Mantid::Algorithms::EstimateDivergence::init(), Mantid::Algorithms::EstimateResolutionDiffraction::init(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::init(), Mantid::Algorithms::ExtractFFTSpectrum::init(), Mantid::Algorithms::ExtractMask::init(), Mantid::Algorithms::ExtractSingleSpectrum::init(), Mantid::Algorithms::ExtractSpectra::init(), Mantid::Algorithms::ExtractSpectra2::init(), Mantid::Algorithms::ExtractUnmaskedSpectra::init(), Mantid::Algorithms::FFT::init(), Mantid::Algorithms::FFTDerivative::init(), Mantid::Algorithms::FFTSmooth::init(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::init(), Mantid::Algorithms::FilterBadPulses::init(), Mantid::Algorithms::FilterByLogValue::init(), Mantid::Algorithms::FilterByTime::init(), Mantid::Algorithms::FilterByXValue::init(), Mantid::Algorithms::FilterEvents::init(), Mantid::Algorithms::FindCenterOfMassPosition::init(), Mantid::Algorithms::FindCenterOfMassPosition2::init(), Mantid::Algorithms::FindDeadDetectors::init(), Mantid::Algorithms::FindDetectorsOutsideLimits::init(), Mantid::Algorithms::FindEPP::init(), Mantid::Algorithms::FindPeaks::init(), Mantid::Algorithms::FindPeaksConvolve::init(), Mantid::Algorithms::FitPeak::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::GeneralisedSecondDifference::init(), Mantid::Algorithms::GenerateEventsFilter::init(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::init(), Mantid::Algorithms::GeneratePeaks::init(), Mantid::Algorithms::GeneratePythonFitScript::init(), Mantid::Algorithms::GeneratePythonScript::init(), Mantid::Algorithms::GetAllEi::init(), Mantid::Algorithms::GetDetectorOffsets::init(), Mantid::Algorithms::GetEi::init(), Mantid::Algorithms::GetEi2::init(), Mantid::Algorithms::GetEiMonDet3::init(), Mantid::Algorithms::GetTimeSeriesLogInformation::init(), Mantid::Algorithms::GroupToXResolution::init(), Mantid::Algorithms::GroupWorkspaces::init(), Mantid::Algorithms::He3TubeEfficiency::init(), Mantid::Algorithms::HRPDSlabCanAbsorption::init(), Mantid::Algorithms::HyspecScharpfCorrection::init(), Mantid::Algorithms::IntegrateByComponent::init(), Mantid::Algorithms::IntegrateEPP::init(), Mantid::Algorithms::Integration::init(), Mantid::Algorithms::InterpolatingRebin::init(), Mantid::Algorithms::IQTransform::init(), Mantid::Algorithms::LineProfile::init(), Mantid::Algorithms::LorentzCorrection::init(), Mantid::Algorithms::MagFormFactorCorrection::init(), Mantid::Algorithms::MaskBins::init(), Mantid::Algorithms::MaskBinsFromTable::init(), Mantid::Algorithms::MaskBinsFromWorkspace::init(), Mantid::Algorithms::MaskDetectorsIf::init(), Mantid::Algorithms::MaskInstrument::init(), Mantid::Algorithms::MaskNonOverlappingBins::init(), Mantid::Algorithms::Max::init(), Mantid::Algorithms::MaxEnt::init(), Mantid::Algorithms::MaxMin::init(), Mantid::Algorithms::MedianDetectorTest::init(), Mantid::Algorithms::MergeRuns::init(), Mantid::Algorithms::Min::init(), Mantid::Algorithms::ModeratorTzero::init(), Mantid::Algorithms::ModeratorTzeroLinear::init(), Mantid::Algorithms::MostLikelyMean::init(), Mantid::Algorithms::MultipleScatteringCorrection::init(), Mantid::Algorithms::MultiplyRange::init(), Mantid::Algorithms::NormaliseByCurrent::init(), Mantid::Algorithms::NormaliseByDetector::init(), Mantid::Algorithms::NormaliseToMonitor::init(), Mantid::Algorithms::NormaliseToUnity::init(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::init(), Mantid::Algorithms::ParallaxCorrection::init(), Mantid::Algorithms::Pause::init(), Mantid::Algorithms::PDCalibration::init(), Mantid::Algorithms::PDDetermineCharacterizations::init(), Mantid::Algorithms::PDFFourierTransform::init(), Mantid::Algorithms::PDFFourierTransform2::init(), Mantid::Algorithms::PointByPointVCorrection::init(), Mantid::Algorithms::PolarizationCorrectionFredrikze::init(), Mantid::Algorithms::DepolarizedAnalyserTransmission::init(), Mantid::Algorithms::FlipperEfficiency::init(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::init(), Mantid::Algorithms::PolarizationEfficienciesWildes::init(), Mantid::Algorithms::PolarizerEfficiency::init(), Mantid::Algorithms::PolarizationCorrectionWildes::init(), Mantid::Algorithms::PolarizationEfficiencyCor::init(), Mantid::Algorithms::Q1D2::init(), Mantid::Algorithms::Q1DWeighted::init(), Mantid::Algorithms::Qxy::init(), Mantid::Algorithms::RadiusSum::init(), Mantid::Algorithms::ReadGroupsFromFile::init(), Mantid::Algorithms::RealFFT::RealFFT::init(), Mantid::Algorithms::Rebin::init(), Mantid::Algorithms::Rebin2D::init(), Mantid::Algorithms::RebinByTimeBase::init(), Mantid::Algorithms::RebinRagged::init(), Mantid::Algorithms::Rebunch::init(), Mantid::Algorithms::Regroup::init(), Mantid::Algorithms::RemoveBackground::init(), Mantid::Algorithms::RemoveBins::init(), Mantid::Algorithms::RemoveInstrumentGeometry::init(), Mantid::Algorithms::RemoveLowResTOF::init(), Mantid::Algorithms::RemoveMaskedSpectra::init(), Mantid::Algorithms::RemovePromptPulse::init(), Mantid::Algorithms::RemoveWorkspaceHistory::init(), Mantid::Algorithms::RenameWorkspace::init(), Mantid::Algorithms::RenameWorkspaces::init(), Mantid::Algorithms::ResampleX::init(), Mantid::Algorithms::ResetNegatives::init(), Mantid::Algorithms::ResizeRectangularDetector::init(), Mantid::Algorithms::RingProfile::init(), Mantid::Algorithms::MayersSampleCorrection::init(), Mantid::Algorithms::SassenaFFT::init(), Mantid::Algorithms::Scale::init(), Mantid::Algorithms::ScaleX::init(), Mantid::Algorithms::Segfault::init(), Mantid::Algorithms::SetInstrumentParameter::init(), Mantid::Algorithms::SetUncertainties::init(), Mantid::Algorithms::ShiftLogTime::init(), Mantid::Algorithms::SmoothData::init(), Mantid::Algorithms::SmoothNeighbours::init(), Mantid::Algorithms::SolidAngle::init(), Mantid::Algorithms::SortEvents::init(), Mantid::Algorithms::SortXAxis::init(), Mantid::Algorithms::SphericalAbsorption::init(), Mantid::Algorithms::Stitch::init(), Mantid::Algorithms::Stitch1D::init(), Mantid::Algorithms::StripPeaks::init(), Mantid::Algorithms::StripVanadiumPeaks::init(), Mantid::Algorithms::SumEventsByLogValue::init(), Mantid::Algorithms::SumNeighbours::init(), Mantid::Algorithms::SumOverlappingTubes::init(), Mantid::Algorithms::SumRowColumn::init(), Mantid::Algorithms::SumSpectra::init(), Mantid::Algorithms::TOFSANSResolution::init(), Mantid::Algorithms::TOFSANSResolutionByPixel::init(), Mantid::Algorithms::Transpose::init(), Mantid::Algorithms::UnaryOperation::init(), Mantid::Algorithms::UnGroupWorkspace::init(), Mantid::Algorithms::UnwrapMonitor::init(), Mantid::Algorithms::UnwrapMonitorsInTOF::init(), Mantid::Algorithms::UnwrapSNS::init(), Mantid::Algorithms::VesuvioL1ThetaResolution::init(), Mantid::Algorithms::WeightedMeanOfWorkspace::init(), Mantid::Algorithms::WienerSmooth::init(), Mantid::Algorithms::XDataConverter::init(), Mantid::Crystal::AddPeakHKL::init(), Mantid::Crystal::AnvredCorrection::init(), Mantid::Crystal::CalculatePeaksHKL::init(), Mantid::Crystal::CalculateUMatrix::init(), Mantid::Crystal::CentroidPeaks::init(), Mantid::Crystal::ClearUB::init(), Mantid::Crystal::CombinePeaksWorkspaces::init(), Mantid::Crystal::CountReflections::init(), Mantid::Crystal::DiffPeaksWorkspaces::init(), Mantid::Crystal::FilterPeaks::init(), Mantid::Crystal::FindClusterFaces::init(), Mantid::Crystal::FindGoniometerAngles::init(), Mantid::Crystal::FindSXPeaks::init(), Mantid::Crystal::FindUBUsingFFT::init(), Mantid::Crystal::FindUBUsingIndexedPeaks::init(), Mantid::Crystal::FindUBUsingLatticeParameters::init(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::init(), Mantid::Crystal::HasUB::init(), Mantid::Crystal::IndexPeaks::init(), Mantid::Crystal::IndexSXPeaks::init(), Mantid::Crystal::IntegratePeaksHybrid::init(), Mantid::Crystal::IntegratePeaksUsingClusters::init(), Mantid::Crystal::IntegratePeakTimeSlices::init(), Mantid::Crystal::LoadIsawPeaks::init(), Mantid::Crystal::LoadIsawUB::init(), Mantid::Crystal::MaskPeaksWorkspace::init(), Mantid::Crystal::NormaliseVanadium::init(), Mantid::Crystal::OptimizeCrystalPlacement::init(), Mantid::Crystal::OptimizeLatticeForCellType::init(), Mantid::Crystal::PeakIntegration::init(), Mantid::Crystal::PeakIntensityVsRadius::init(), Mantid::Crystal::PeaksInRegion::init(), Mantid::Crystal::PeaksOnSurface::init(), Mantid::Crystal::PredictPeaks::init(), Mantid::Crystal::PredictSatellitePeaks::init(), Mantid::Crystal::SaveIsawUB::init(), Mantid::Crystal::SCDCalibratePanels::init(), Mantid::Crystal::SelectCellOfType::init(), Mantid::Crystal::SelectCellWithForm::init(), Mantid::Crystal::SetGoniometer::init(), Mantid::Crystal::SetSpecialCoordinates::init(), Mantid::Crystal::SetUB::init(), Mantid::Crystal::ShowPossibleCells::init(), Mantid::Crystal::SortHKL::init(), Mantid::Crystal::SortPeaksWorkspace::init(), Mantid::Crystal::StatisticsOfPeaksWorkspace::init(), Mantid::Crystal::TransformHKL::init(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::init(), Mantid::CurveFitting::Algorithms::ConvolveWorkspaces::init(), Mantid::CurveFitting::CrystalFieldEnergies::init(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::init(), Mantid::CurveFitting::Algorithms::Fit1D::init(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::init(), Mantid::CurveFitting::Algorithms::LeBailFit::init(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::init(), Mantid::CurveFitting::Algorithms::PawleyFit::init(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::init(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::init(), Mantid::CurveFitting::Algorithms::SplineBackground::init(), Mantid::CurveFitting::Algorithms::SplineInterpolation::init(), Mantid::CurveFitting::Algorithms::SplineSmoothing::init(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::init(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::init(), Mantid::CurveFitting::Functions::ProcessBackground::init(), Mantid::CurveFitting::IFittingAlgorithm::init(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), Mantid::DataHandling::ApplyDiffCal::init(), Mantid::DataHandling::CheckMantidVersion::init(), Mantid::DataHandling::CompressEvents::init(), Mantid::DataHandling::CreateChunkingFromInstrument::init(), Mantid::DataHandling::CreatePolarizationEfficiencies::init(), Mantid::DataHandling::CreateSampleShape::init(), Mantid::DataHandling::CreateSimulationWorkspace::init(), Mantid::DataHandling::DeleteTableRows::init(), Mantid::DataHandling::DetermineChunking::init(), Mantid::DataHandling::DownloadFile::init(), Mantid::DataHandling::DownloadInstrument::init(), Mantid::DataHandling::ExtractMonitorWorkspace::init(), Mantid::DataHandling::ExtractPolarizationEfficiencies::init(), Mantid::DataHandling::FindDetectorsInShape::init(), Mantid::DataHandling::FindDetectorsPar::init(), Mantid::DataHandling::GenerateGroupingPowder::init(), Mantid::DataHandling::GroupDetectors::init(), Mantid::DataHandling::GroupDetectors2::init(), Mantid::DataHandling::ISISJournalGetExperimentRuns::init(), Mantid::DataHandling::JoinISISPolarizationEfficiencies::init(), Mantid::DataHandling::Load::init(), Mantid::DataHandling::LoadAscii::init(), Mantid::DataHandling::LoadAscii2::init(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadBBY2::init(), Mantid::DataHandling::LoadCalFile::init(), Mantid::DataHandling::LoadCanSAS1D::init(), Mantid::DataHandling::LoadCSNSNexus::init(), Mantid::DataHandling::LoadDaveGrp::init(), Mantid::DataHandling::LoadDetectorInfo::init(), Mantid::DataHandling::LoadDiffCal::init(), Mantid::DataHandling::LoadDNSEvent::init(), Mantid::DataHandling::LoadEmptyInstrument::init(), Mantid::DataHandling::LoadErrorEventsNexus::init(), Mantid::DataHandling::LoadEventAsWorkspace2D::init(), Mantid::DataHandling::LoadEventNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::LoadFITS::init(), Mantid::DataHandling::LoadFullprofResolution::init(), Mantid::DataHandling::LoadGSS::init(), Mantid::DataHandling::LoadHFIRSANS::init(), Mantid::DataHandling::LoadIDFFromNexus::init(), Mantid::DataHandling::LoadILLDiffraction::init(), Mantid::DataHandling::LoadILLIndirect2::init(), Mantid::DataHandling::LoadILLLagrange::init(), Mantid::DataHandling::LoadILLPolarizationFactors::init(), Mantid::DataHandling::LoadILLPolarizedDiffraction::init(), Mantid::DataHandling::LoadILLReflectometry::init(), Mantid::DataHandling::LoadILLSALSA::init(), Mantid::DataHandling::LoadILLSANS::init(), Mantid::DataHandling::LoadILLTOF2::init(), Mantid::DataHandling::LoadILLTOF3::init(), Mantid::DataHandling::LoadInstrument::init(), Mantid::DataHandling::LoadInstrumentFromRaw::init(), Mantid::DataHandling::LoadIsawDetCal::init(), Mantid::DataHandling::LoadISISNexus2::init(), Mantid::DataHandling::LoadISISPolarizationEfficiencies::init(), Mantid::DataHandling::LoadLog::init(), Mantid::DataHandling::LoadMappingTable::init(), Mantid::DataHandling::LoadMcStas::init(), Mantid::DataHandling::LoadMcStasNexus::init(), Mantid::DataHandling::LoadMLZ::init(), Mantid::DataHandling::LoadMuonNexusV2::init(), Mantid::DataHandling::LoadNexus::init(), Mantid::DataHandling::LoadNexusLogs::init(), Mantid::DataHandling::LoadNexusMonitors2::init(), Mantid::DataHandling::LoadNexusProcessed::init(), Mantid::DataHandling::LoadNGEM::init(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::init(), Mantid::DataHandling::LoadNXSPE::init(), Mantid::DataHandling::LoadParameterFile::init(), Mantid::DataHandling::LoadPDFgetNFile::init(), Mantid::DataHandling::LoadPLN::init(), Mantid::DataHandling::LoadPreNexus::init(), Mantid::DataHandling::LoadPreNexusMonitors::init(), Mantid::DataHandling::LoadPSIMuonBin::init(), Mantid::DataHandling::LoadQKK::init(), Mantid::DataHandling::LoadRaw3::init(), Mantid::DataHandling::LoadRawBin0::init(), Mantid::DataHandling::LoadRawHelper::init(), Mantid::DataHandling::LoadRKH::init(), Mantid::DataHandling::LoadSampleEnvironment::init(), Mantid::DataHandling::LoadSampleShape::init(), Mantid::DataHandling::LoadSassena::init(), Mantid::DataHandling::LoadSESANS::init(), Mantid::DataHandling::LoadSINQFocus::init(), Mantid::DataHandling::LoadSPE::init(), Mantid::DataHandling::LoadSpec::init(), Mantid::DataHandling::LoadSpice2D::init(), Mantid::DataHandling::LoadSpiceAscii::init(), Mantid::DataHandling::LoadSpiceXML2DDet::init(), Mantid::DataHandling::LoadSwans::init(), Mantid::DataHandling::LoadTBL::init(), Mantid::DataHandling::LoadTOFRawNexus::init(), Mantid::DataHandling::MaskDetectors::init(), Mantid::DataHandling::MaskDetectorsInShape::init(), Mantid::DataHandling::MaskSpectra::init(), Mantid::DataHandling::MoveInstrumentComponent::init(), Mantid::DataHandling::PatchBBY::init(), Mantid::DataHandling::PDLoadCharacterizations::init(), Mantid::DataHandling::RawFileInfo::init(), Mantid::DataHandling::RemoveLogs::init(), Mantid::DataHandling::RotateInstrumentComponent::init(), Mantid::DataHandling::RotateSampleShape::init(), Mantid::DataHandling::RotateSource::init(), Mantid::DataHandling::SaveAscii::init(), Mantid::DataHandling::SaveAscii2::init(), Mantid::DataHandling::SaveBankScatteringAngles::init(), Mantid::DataHandling::SaveCSV::init(), Mantid::DataHandling::SaveDaveGrp::init(), Mantid::DataHandling::SaveDiffCal::init(), Mantid::DataHandling::SaveFullprofResolution::init(), Mantid::DataHandling::SaveGDA::init(), Mantid::DataHandling::SaveGSASInstrumentFile::init(), Mantid::DataHandling::SaveGSS::init(), Mantid::DataHandling::SaveNexus::init(), Mantid::DataHandling::SaveNexusGeometry::init(), Mantid::DataHandling::SaveNexusProcessed::init(), Mantid::DataHandling::SaveNISTDAT::init(), Mantid::DataHandling::SaveNXSPE::init(), Mantid::DataHandling::SaveNXTomo::init(), Mantid::DataHandling::SavePAR::init(), Mantid::DataHandling::SaveParameterFile::init(), Mantid::DataHandling::SavePDFGui::init(), Mantid::DataHandling::SavePHX::init(), Mantid::DataHandling::SaveRKH::init(), Mantid::DataHandling::SaveRMCProfile::init(), Mantid::DataHandling::SaveSampleEnvironmentAndShape::init(), Mantid::DataHandling::SaveSESANS::init(), Mantid::DataHandling::SaveSPE::init(), Mantid::DataHandling::SaveTBL::init(), Mantid::DataHandling::SaveVTK::init(), Mantid::DataHandling::ScaleInstrumentComponent::init(), Mantid::DataHandling::SetSampleMaterial::init(), Mantid::DataHandling::SetScalingPSD::init(), Mantid::DataHandling::SNSAppendGeometryToNexus::init(), Mantid::DataHandling::SortTableWorkspace::init(), Mantid::DataHandling::UpdateInstrumentFromFile::init(), Mantid::ICat::CatalogLogin::init(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::init(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::init(), Mantid::MDAlgorithms::BinaryOperationMD::init(), Mantid::MDAlgorithms::BinMD::init(), Mantid::MDAlgorithms::CalculateCoverageDGS::init(), Mantid::MDAlgorithms::CentroidPeaksMD2::init(), Mantid::MDAlgorithms::CompactMD::init(), Mantid::MDAlgorithms::CompareMDWorkspaces::init(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::init(), Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE::init(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::init(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::init(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::init(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::init(), Mantid::MDAlgorithms::ConvertToMDParent::init(), Mantid::MDAlgorithms::CreateMDHistoWorkspace::init(), Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD::init(), Mantid::MDAlgorithms::EvaluateMDFunction::init(), Mantid::MDAlgorithms::FindPeaksMD::init(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::init(), Mantid::MDAlgorithms::ImportMDEventWorkspace::init(), Mantid::MDAlgorithms::ImportMDHistoWorkspace::init(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::init(), Mantid::MDAlgorithms::IntegrateFlux::init(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::init(), Mantid::MDAlgorithms::IntegratePeaksCWSD::init(), Mantid::MDAlgorithms::IntegratePeaksMD::init(), Mantid::MDAlgorithms::IntegratePeaksMD2::init(), Mantid::MDAlgorithms::LoadDNSSCD::init(), Mantid::MDAlgorithms::LoadMD::init(), Mantid::MDAlgorithms::LoadSQW::init(), Mantid::MDAlgorithms::LoadSQW2::init(), Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD::init(), Mantid::MDAlgorithms::MaskMD::init(), Mantid::MDAlgorithms::MDNorm::init(), Mantid::MDAlgorithms::MDNormDirectSC::init(), Mantid::MDAlgorithms::MDNormSCD::init(), Mantid::MDAlgorithms::MergeMD::init(), Mantid::MDAlgorithms::MergeMDFiles::init(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::init(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::init(), Mantid::MDAlgorithms::QTransform::init(), Mantid::MDAlgorithms::QueryMDWorkspace::init(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::init(), Mantid::MDAlgorithms::ReplicateMD::init(), Mantid::MDAlgorithms::SaveIsawQvector::init(), Mantid::MDAlgorithms::SaveZODS::init(), Mantid::MDAlgorithms::SetMDFrame::init(), Mantid::MDAlgorithms::SetMDUsingMask::init(), Mantid::MDAlgorithms::SmoothMD::init(), Mantid::MDAlgorithms::SpectralMomentMD::init(), Mantid::MDAlgorithms::ThresholdMD::init(), Mantid::MDAlgorithms::TransformMD::init(), Mantid::MDAlgorithms::TransposeMD::init(), Mantid::MDAlgorithms::UnaryOperationMD::init(), Mantid::PythonInterface::RunPythonScript::init(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::init(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::init(), Mantid::WorkflowAlgorithms::DgsDiagnose::init(), Mantid::WorkflowAlgorithms::DgsPreprocessData::init(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::init(), Mantid::WorkflowAlgorithms::DgsRemap::init(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::init(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::init(), Mantid::WorkflowAlgorithms::EQSANSLoad::init(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::init(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::init(), Mantid::WorkflowAlgorithms::EQSANSQ2D::init(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::init(), Mantid::WorkflowAlgorithms::HFIRLoad::init(), Mantid::Algorithms::ProcessIndirectFitParameters::init(), Mantid::WorkflowAlgorithms::SANSBeamFinder::init(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::init(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::init(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::init(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::init(), Mantid::WorkflowAlgorithms::StepScan::init(), Mantid::Algorithms::ClearCache::init(), Mantid::Algorithms::CropToComponent::init(), Mantid::DataHandling::SaveFITS::init(), Mantid::DataHandling::SetBeam::init(), Mantid::DataHandling::SetSample::init(), Mantid::Crystal::PeaksIntersection::initBaseProperties(), Mantid::API::BoxControllerSettingsAlgorithm::initBoxControllerProps(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::initConcrete(), Mantid::CurveFitting::Algorithms::CalculateCostFunction::initConcrete(), Mantid::CurveFitting::Algorithms::DoublePulseFit::initConcrete(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::initConcrete(), Mantid::CurveFitting::Algorithms::EvaluateFunction::initConcrete(), Mantid::CurveFitting::Algorithms::Fit::initConcrete(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::initConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::initConcrete(), Mantid::MDAlgorithms::EqualToMD::initExtraProperties(), Mantid::MDAlgorithms::LogarithmMD::initExtraProperties(), Mantid::MDAlgorithms::PowerMD::initExtraProperties(), Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase::initGenericImportProps(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initInstance(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initInstance(), Mantid::DataHandling::CreatePolarizationEfficienciesBase::initOutputWorkspace(), Mantid::DataHandling::SaveNXcanSASBase::initPolarizedProperties(), Mantid::MDAlgorithms::SlicingAlgorithm::initSlicingProps(), Mantid::DataHandling::SaveNXcanSASBase::initStandardProperties(), Mantid::DataHandling::Load::loadMultipleFiles(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::loadTransmission(), Mantid::Algorithms::Qhelper::outputParts(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::DataHandling::LoadCanSAS1D2::processTransmission(), Mantid::DataHandling::LoadMuonNexusV2::runLoadISISNexus(), Mantid::DataHandling::LoadEventNexus::runLoadMonitors(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::CurveFitting::IFittingAlgorithm::setFunction(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::DataHandling::LoadNexus::setOutputWorkspace(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), and Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace().
declareProperty() [8/8]
virtual void Mantid::Kernel::IPropertyManager::declareProperty (std::unique_ptr< Property > p, const std::string & doc = "") virtual
Function to declare properties (i.e. store them)
Implements Mantid::Kernel::IPropertyManager.
declareWorkspaceInputProperties()
template<typename T , const int AllowedIndexTypes, typename... WSPropArgs, typename > void Mantid::API::Algorithm::declareWorkspaceInputProperties (const std::string & propertyName, const std::string & doc, WSPropArgs &&... wsPropArgs) protected
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
This method is only enabled if T is convertible to MatrixWorkspace. The AllowedIndexTypes combination of allowed index types. Default IndexType::WorkspaceIndex
Parameters
propertyName Name of property which will be reserved
wsPropArgs a parameter pack of arguments forwarded to WorkspaceProperty. Can contain PropertyMode, LockMode, and validators.
doc Property documentation string.
Definition at line 42 of file Algorithm.hxx.
References declareProperty(), Mantid::API::IndexProperty::generatePropertyName(), Mantid::API::IndexTypeProperty::generatePropertyName(), Mantid::Kernel::Direction::Input, and m_reservedList.
doCallProcessGroups()
bool Mantid::API::Algorithm::doCallProcessGroups (Mantid::Types::Core::DateAndTime & startTime) private
Calls process groups with the required timing checks and algorithm execution finalization steps.
Parameters
startTime to record the algorithm execution start
Returns
whether processGroups succeeds.
Definition at line 1265 of file Algorithm.cpp.
References Mantid::Kernel::Timer::elapsed(), Mantid::API::Failed, fillHistory(), findWorkspaces(), g_execCount, interruption_point(), isExecuted(), m_alwaysStoreInADS, m_history, m_runningAsync, m_usingBaseProcessGroups, notificationCenter(), Mantid::Kernel::Direction::Output, processGroups(), reportCompleted(), setResultState(), store(), Mantid::API::Success, and trackingHistory().
Referenced by executeInternal().
doSetInputProperties()
template<typename T1 , typename T2 , typename WsType > void Mantid::API::Algorithm::doSetInputProperties (const std::string & name, const T1 & wksp, IndexType type, const T2 & list) private
Definition at line 71 of file Algorithm.hxx.
References Mantid::API::IndexProperty::generatePropertyName(), Mantid::API::IndexTypeProperty::generatePropertyName(), getPointerToProperty(), isCompoundProperty(), and name().
enableHistoryRecordingForChild()
void Mantid::API::Algorithm::enableHistoryRecordingForChild (const bool on) override virtual
Change the state of the history recording flag.
Only applicable for child algorithms.
Parameters
on :: The new state of the flag
Implements Mantid::API::IAlgorithm.
Definition at line 176 of file Algorithm.cpp.
References m_recordHistoryForChild.
Referenced by export_leaf_classes(), Mantid::Algorithms::Comment::init(), and trackAlgorithmHistory().
exec()
virtual void Mantid::API::Algorithm::exec () protected pure virtual
Virtual method - must be overridden by concrete algorithm.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::BinaryOperation, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByTimeBase, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnaryOperation, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XDataConverter, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::IFittingAlgorithm, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficienciesBase, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GenerateGroupingPowder2, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QTransform, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::API::NexusFileLoader, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, and Mantid::DataHandling::SetSample.
Referenced by Mantid::DataHandling::LoadEMUTar::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), and executeInternal().
execute()
bool Mantid::API::Algorithm::execute () final override virtual
The actions to be performed by the algorithm on a dataset.
This method is invoked for top level algorithms by the application manager. This method invokes exec() method. For Child Algorithms either the execute() method or exec() method must be EXPLICITLY invoked by the parent algorithm.
Exceptions
runtime_error Thrown if algorithm or Child Algorithm cannot be executed
Returns
true if executed successfully.
Implements Mantid::API::IAlgorithm.
Definition at line 24 of file AlgorithmExecuteProfile.cpp.
References executeInternal(), and name().
Referenced by Mantid::DataHandling::LoadILLSANS::applySensitivityMap(), Mantid::MDAlgorithms::LoadGaussCube::exec(), executeAsChildAlg(), executeAsyncImpl(), processGroups(), and SANSInstrumentCreationHelper::runLoadInstrument().
executeAsChildAlg()
void Mantid::API::Algorithm::executeAsChildAlg () override virtual
Execute as a Child Algorithm.
This runs execute() but catches errors so as to log the name of the failed Child Algorithm, if it fails.
Implements Mantid::API::IAlgorithm.
Definition at line 787 of file Algorithm.cpp.
References execute(), and name().
Referenced by Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec().
executeAsync()
Poco::ActiveResult< bool > Mantid::API::Algorithm::executeAsync () override virtual
Asynchronous execution.
Implements Mantid::API::IAlgorithm.
Definition at line 1613 of file Algorithm.cpp.
References executeAsyncImpl(), and m_executeAsync.
executeAsyncImpl()
bool Mantid::API::Algorithm::executeAsyncImpl (const Poco::Void & i) private
Callback when an algorithm is executed asynchronously.
Parameters
i :: Unused argument
Returns
true if executed successfully.
Definition at line 1623 of file Algorithm.cpp.
References execute(), and m_runningAsync.
Referenced by executeAsync().
executeInternal()
bool Mantid::API::Algorithm::executeInternal () private
Invoced internally in execute()
Definition at line 520 of file Algorithm.cpp.
References cacheInputWorkspaceHistories(), cacheWorkspaceProperties(), calledByAlias, checkGroups(), clearWorkspaceCaches(), Mantid::Kernel::Logger::debug(), doCallProcessGroups(), Mantid::Kernel::Timer::elapsed(), error, Mantid::Kernel::Logger::error(), exec(), existsProperty(), Mantid::API::Failed, fillHistory(), g_execCount, getAlgorithmID(), getLogger(), getProperties(), interruption_point(), isExecuted(), isInitialized(), linkHistoryWithLastChild(), lockWorkspaces(), logAlgorithmInfo(), m_alwaysStoreInADS, m_gcTime, m_history, m_isChildAlgorithm, m_rethrow, m_runningAsync, name(), notificationCenter(), registerFeatureUsage(), reportCompleted(), Mantid::API::Running, setExecutionState(), setResultState(), store(), Mantid::API::Success, std::to_string(), trackingHistory(), unlockWorkspaces(), validateInputs(), validateProperties(), and Mantid::Kernel::Logger::warning().
Referenced by execute().
executionState()
ExecutionState Mantid::API::Algorithm::executionState () const override virtual
Gets the current execution state.
Implements Mantid::API::IAlgorithm.
Definition at line 129 of file Algorithm.cpp.
References m_executionState.
Referenced by isExecuted(), isReadyForGarbageCollection(), and isRunning().
existsProperty()
bool Mantid::API::Algorithm::existsProperty (const std::string & name) const override virtual
Checks whether the named property is already in the list of managed property.
Parameters
name :: The name of the property (case insensitive)
Returns
True if the property is already stored
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1898 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::existsProperty(), m_properties, and name().
Referenced by Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), executeInternal(), Mantid::Algorithms::SpectrumAlgorithm::getWorkspaceIndexSet(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::CurveFitting::Algorithms::Fit::initializeMinimizer(), Mantid::DataHandling::Load::loadFileToWs(), Mantid::DataHandling::LoadEventNexus::loadInstrument(), Mantid::DataHandling::Load::loadSingleFile(), Mantid::CurveFitting::Functions::UserFunction1D::prepare(), Mantid::CurveFitting::IFittingAlgorithm::setFunction(), Mantid::DataHandling::LoadNexus::setOutputWorkspace(), Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace(), and Mantid::Algorithms::Rebin::validateInputs().
fillHistory() [1/2]
void Mantid::API::Algorithm::fillHistory () protected virtual
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
Fills History, Algorithm History and Algorithm Parameters.
Reimplemented in Mantid::Algorithms::ConjoinXRuns, and Mantid::Algorithms::MergeRuns.
Definition at line 1012 of file Algorithm.cpp.
References fillHistory(), findWorkspaces(), isChild(), and Mantid::Kernel::Direction::Output.
Referenced by doCallProcessGroups(), Mantid::Algorithms::UnGroupWorkspace::exec(), executeInternal(), and fillHistory().
fillHistory() [2/2]
void Mantid::API::Algorithm::fillHistory (const std::vector< Workspace_sptr > & outputWorkspaces) protected
Copy workspace history from input workspaces to provided vector of output workspaces.
If this algorithm is not a child then copy history between the inputs and outputs and add a record for this algorithm.
If the algorithm is a child attach the child history to the parent if requested.
Parameters
outputWorkspaces :: A reference to a vector for the output workspaces. Used in the non-child case.
Definition at line 1333 of file Algorithm.cpp.
References Mantid::API::Workspace::getHistory(), isChild(), m_history, m_inputWorkspaceHistories, m_parentHistory, and m_recordHistoryForChild.
findWorkspaces()
void Mantid::API::Algorithm::findWorkspaces (WorkspaceVector & workspaces, unsigned int direction, bool checkADS = false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
Parameters
workspaces A reference to a vector for the workspaces
direction The direction of the property required for the search
checkADS If true, check the ADS for workspace references if the check on the workspace property value is empty. Most useful for finding group workspaces that are never stored on the property
Definition at line 1091 of file Algorithm.cpp.
References getProperties(), Mantid::API::IWorkspaceProperty::getWorkspace(), Mantid::Kernel::Direction::InOut, and workspace.
Referenced by doCallProcessGroups(), fillHistory(), and Mantid::API::MultiPeriodGroupWorker::findMultiPeriodGroups().
fromHistory()
IAlgorithm_sptr Mantid::API::Algorithm::fromHistory (const AlgorithmHistory & history) static
Construct an object from a history entry.
This creates the algorithm and sets all of its properties using the history.
Parameters
history :: AlgorithmHistory object
Returns
a shared pointer to the created algorithm.
Definition at line 947 of file Algorithm.cpp.
References fromString(), and history.
Referenced by Mantid::API::AlgorithmHistory::createAlgorithm(), Mantid::API::WorkspaceHistory::getAlgorithm(), and Mantid::API::AlgorithmHistory::getChildAlgorithm().
fromJson()
IAlgorithm_sptr Mantid::API::Algorithm::fromJson (const Json::Value & serialized) static
De-serialize an object from a Json.
De-serializes the algorithm from a Json object.
Parameters
serialized A reference to Json::Value that contains a serialized algorithm object
Returns
A new algorithm object
Exceptions
std::runtime_error if the algorithm cannot be created
Definition at line 1001 of file Algorithm.cpp.
Referenced by fromString(), and Mantid::API::AlgorithmProperty::setValueFromJson().
fromString()
IAlgorithm_sptr Mantid::API::Algorithm::fromString (const std::string & input) static
De-serialize an object from a string.
De-serializes the algorithm from a string.
Parameters
input :: An input string in the format. The format is AlgorithmName.version(prop1=value1,prop2=value2,...). If .version is not found the highest found is used.
Returns
A pointer to a managed algorithm object
Exceptions
std::runtime_error if the algorithm cannot be created
Definition at line 985 of file Algorithm.cpp.
References fromJson().
Referenced by Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), export_leaf_classes(), fromHistory(), Mantid::WorkflowAlgorithms::SANSBeamFinder::loadBeamFinderFile(), and Mantid::API::AlgorithmProperty::setValue().
getAlgorithmID()
AlgorithmID Mantid::API::Algorithm::getAlgorithmID () const inline override virtual
Algorithm ID.
Unmanaged algorithms return 0 (or NULL?) values. Managed ones have non-zero.
Implements Mantid::API::IAlgorithm.
Definition at line 204 of file Algorithm.h.
Referenced by executeInternal().
getAlgStartupLogging()
bool Mantid::API::Algorithm::getAlgStartupLogging () const override virtual
get the state of Logging of start and end messages
return the state of logging of start and end messages
Returns
: true to logging is enabled
Implements Mantid::API::IAlgorithm.
Definition at line 1761 of file Algorithm.cpp.
References m_isAlgStartupLoggingEnabled.
getAlwaysStoreInADS()
bool Mantid::API::Algorithm::getAlwaysStoreInADS () const override virtual
Returns true if we always store in the AnalysisDataService.
Returns
true if output is saved to the AnalysisDataService.
Implements Mantid::API::IAlgorithm.
Definition at line 197 of file Algorithm.cpp.
References m_alwaysStoreInADS.
Referenced by Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), and Mantid::API::AlgorithmHistory::fillAlgorithmHistory().
getCancel()
bool Mantid::API::Algorithm::getCancel () const
Returns the cancellation state.
Definition at line 1675 of file Algorithm.cpp.
References m_cancel.
Referenced by Mantid::API::Progress::hasCancellationBeenRequested(), Mantid::DataHandling::LoadDNSEvent::populate_EventWorkspace(), Mantid::DataHandling::LoadNGEM::reportProgressAndCheckCancel(), Mantid::DataHandling::LoadBankFromDiskTask::run(), and Mantid::DataHandling::ProcessBankData::run().
getDeclaredPropertyNames()
std::vector< std::string > Mantid::API::Algorithm::getDeclaredPropertyNames () const override virtual noexcept
Return the list of declared property names.
Returns
A vector holding strings of property names
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1946 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getDeclaredPropertyNames(), and m_properties.
getLogger()
Kernel::Logger & Mantid::API::Algorithm::getLogger () const
Returns a reference to the logger.
Definition at line 1678 of file Algorithm.cpp.
References g_log.
Referenced by Mantid::DataHandling::ProcessBankCompressed::addToEventLists(), Mantid::DataHandling::ProcessBankCompressed::collectEvents(), Mantid::DataHandling::LoadRawHelper::createMonitorWorkspace(), Mantid::Algorithms::FilterByTime::exec(), Mantid::DataHandling::LoadNexusLogs::execLoader(), executeInternal(), initialize(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventId(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventIndex(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventWeights(), Mantid::DataHandling::LoadBankFromDiskTask::loadPulseTimes(), Mantid::DataHandling::LoadBankFromDiskTask::loadTof(), logAlgorithmInfo(), Mantid::DataHandling::LoadBankFromDiskTask::prepareEventId(), reportCompleted(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::LoadEmptyInstrument::runLoadIDFFromNexus(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadInstrument(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), and Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs().
getLoggingOffset()
int Mantid::API::Algorithm::getLoggingOffset () const override virtual
returns the logging priority offset
Implements Mantid::API::IAlgorithm.
Definition at line 1692 of file Algorithm.cpp.
References g_log, and Mantid::Kernel::Logger::getLevelOffset().
getPointerToProperty()
Property * Mantid::API::Algorithm::getPointerToProperty (const std::string & name) const override virtual
Get a property by name.
Parameters
name :: The name of the property (case insensitive)
Returns
A pointer to the named property
Exceptions
Exception::NotFoundError if the named property is unknown
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1923 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getPointerToProperty(), m_properties, and name().
Referenced by Mantid::CurveFitting::IFittingAlgorithm::afterPropertySet(), Mantid::API::checkForMandatoryInstrumentDefault(), Mantid::API::checkForOptionalInstrumentDefault(), Mantid::Algorithms::ExponentialCorrection::defineProperties(), doSetInputProperties(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::ExtractSpectra2::exec(), Mantid::Algorithms::NormaliseToMonitor::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::MergeMDFiles::exec(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::exec(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::execConcrete(), getWorkspaceAndIndices(), Mantid::DataHandling::SaveAscii::init(), Mantid::DataHandling::SaveAscii2::init(), Mantid::DataHandling::SaveCSV::init(), Mantid::MDAlgorithms::ConvertToMDParent::init(), Mantid::CurveFitting::Algorithms::DoublePulseFit::initConcrete(), Mantid::CurveFitting::Algorithms::Fit::initConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::initConcrete(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadILLSANS::loadMetaData(), Mantid::Algorithms::Bin2DPowderDiffraction::validateInputs(), Mantid::Algorithms::DiffractionFocussing2::validateInputs(), Mantid::Crystal::ConvertPeaksWorkspace::validateInputs(), Mantid::Crystal::FindSXPeaks::validateInputs(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::validateInputs(), and Mantid::Algorithms::MergeLogs::validateTSP().
getPointerToPropertyOrdinal()
Property * Mantid::API::Algorithm::getPointerToPropertyOrdinal (const int & index) const override virtual
Get a property by an index.
Parameters
index :: The name of the property (case insensitive)
Returns
A pointer to the named property
Exceptions
std::runtime_error if the property index is too high
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1932 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getPointerToPropertyOrdinal(), index, and m_properties.
getProperties()
const std::vector< Property * > & Mantid::API::Algorithm::getProperties () const override virtual
Get the list of managed properties.
The properties will be stored in the order that they were declared.
Returns
A vector holding pointers to the list of properties
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1940 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getProperties(), and m_properties.
Referenced by Mantid::CurveFitting::IFittingAlgorithm::addWorkspaces(), Mantid::MDAlgorithms::MDNormDirectSC::binInputWS(), Mantid::MDAlgorithms::MDNormSCD::binInputWS(), cacheInputWorkspaceHistories(), cacheWorkspaceProperties(), copyNonWorkspaceProperties(), Mantid::DataHandling::Load::declareLoaderProperties(), Mantid::MDAlgorithms::UnaryOperationMD::exec(), executeInternal(), findWorkspaces(), Mantid::CurveFitting::Algorithms::Fit1D::init(), Mantid::DataHandling::Load::init(), linkHistoryWithLastChild(), Mantid::DataHandling::Load::loadFileToWs(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::API::AlgorithmHistory::setProperties(), and store().
getProperty()
IPropertyManager::TypedValue Mantid::API::Algorithm::getProperty (const std::string & name) const override virtual
Get the value of a property.
Allows you to assign directly to a variable of the property's type (if a supported type).
*** This method does NOT work for assigning to an existing std::string. In this case you have to use getPropertyValue() instead. Note that you can, though, construct a local string variable by writing, e.g. std::string s = getProperty("myProperty"). ***
Parameters
name :: The name of the property
Returns
The value of the property. Will be cast to the desired type (if a supported type).
Exceptions
std::runtime_error If an attempt is made to assign a property to a different type
Exception::NotFoundError If the property requested does not exist
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1966 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getProperty(), m_properties, and name().
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::actuallyValidateInputs(), Mantid::Algorithms::RealFFT::RealFFT::actuallyValidateInputs(), Mantid::Algorithms::SumEventsByLogValue::addMonitorCounts(), Mantid::Algorithms::PaddingAndApodization::addPadding(), Mantid::DataHandling::SaveNXcanSASBase::addPolarizedData(), Mantid::DataHandling::SaveNXcanSASBase::addPolarizedMetadata(), Mantid::CurveFitting::Functions::ProcessBackground::addRegion(), Mantid::DataHandling::SaveNXcanSASBase::addStandardMetadata(), Mantid::CurveFitting::IFittingAlgorithm::addWorkspace(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::appendSampleLogs(), Mantid::Algorithms::DirectILLTubeBackground::applyDiagnostics(), Mantid::Algorithms::FFT::areBinWidthsUneven(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::MDAlgorithms::MDNorm::binBackgroundWS(), Mantid::MDAlgorithms::BinMD::binByIterating(), Mantid::MDAlgorithms::MDNorm::binInputWS(), Mantid::Algorithms::Q1DWeighted::bootstrap(), Mantid::PythonInterface::RunPythonScript::buildLocals(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), Mantid::Algorithms::GetAllEi::buildWorkspaceToFit(), Mantid::Algorithms::RadiusSum::cacheInputPropertyValues(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::cacheInputs(), Mantid::DataHandling::LoadDetectorInfo::cacheInputs(), Mantid::MDAlgorithms::MDNormDirectSC::cacheInputs(), Mantid::MDAlgorithms::MDNormSCD::cacheInputs(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcDepolarizedProportion(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3::calculateExtentsFromData(), Mantid::MDAlgorithms::MDNorm::calculateNormalization(), Mantid::MDAlgorithms::MDNormDirectSC::calculateNormalization(), Mantid::MDAlgorithms::MDNormSCD::calculateNormalization(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::calculateOutputs(), Mantid::Algorithms::PolarizationEfficienciesWildes::calculatePolarizerAndAnalyserEfficiencies(), Mantid::Algorithms::PolarizerEfficiency::calculatePolarizerEfficiency(), Mantid::Crystal::PredictPeaks::calculateQAndAddToOutput(), Mantid::DataHandling::SaveSESANS::calculateSpinEchoLength(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcWavelengthDependentTransmission(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::Algorithms::CompareWorkspaces::checkAxes(), Mantid::Algorithms::CompareWorkspaces::checkData(), Mantid::Algorithms::DeleteWorkspace::checkGroups(), Mantid::DataHandling::SaveNXcanSAS::checkGroups(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::checkInputMDDimension(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::checkInputMDDimension(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::checkInputMDDimensions(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::checkInputWorkspace(), Mantid::Algorithms::CompareWorkspaces::checkInstrument(), Mantid::DataHandling::SaveVTK::checkOptionalProperties(), Mantid::DataHandling::LoadISISNexus2::checkOptionalProperties(), Mantid::DataHandling::LoadNexusProcessed::checkOptionalProperties(), Mantid::Algorithms::ExtractSpectra::checkProperties(), Mantid::Algorithms::NormaliseToMonitor::checkProperties(), Mantid::Algorithms::CalculateFlatBackground::checkRange(), Mantid::Algorithms::MergeRuns::checkRebinning(), Mantid::CurveFitting::Algorithms::SplineSmoothing::checkSmoothingAccuracy(), Mantid::Algorithms::MaskNonOverlappingBins::checkXSorting(), Mantid::Algorithms::CreateFloodWorkspace::collectExcludedSpectra(), Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::Algorithms::DirectILLTubeBackground::components(), Mantid::Algorithms::GetEiMonDet3::computeTOF(), Mantid::Algorithms::ConjoinWorkspaces::conjoinEvents(), Mantid::Algorithms::ConjoinWorkspaces::conjoinHistograms(), Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::Algorithms::PDFFourierTransform2::convertFromSQMinus1(), Mantid::Algorithms::PDFFourierTransform2::convertToSQMinus1(), Mantid::Algorithms::HeliumAnalyserEfficiency::convertToTheoreticalEfficiencies(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::Algorithms::He3TubeEfficiency::correctForEfficiency(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::correctForTransmission(), Mantid::MDAlgorithms::MDNorm::createBackgroundNormalizationWS(), Mantid::DataHandling::CreateSimulationWorkspace::createBinBoundaries(), Mantid::Algorithms::PDCalibration::createCalTableFromExisting(), Mantid::DataHandling::LoadNGEM::createCountWorkspace(), Mantid::DataHandling::CreateSimulationWorkspace::createDetectorMapping(), Mantid::DataHandling::CreatePolarizationEfficiencies::createEfficiencies(), Mantid::DataHandling::JoinISISPolarizationEfficiencies::createEfficiencies(), Mantid::Algorithms::ConvertSpectrumAxis2::createElasticQMap(), Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase::createEmptyOutputWorkspace(), Mantid::Algorithms::GetDetectorOffsets::createFunction(), Mantid::Algorithms::FitPeak::createFunctions(), Mantid::MDAlgorithms::SlicingAlgorithm::createGeneralTransform(), Mantid::DataHandling::SaveDetectorsGrouping::createGroupDetectorIDMap(), Mantid::DataHandling::GenerateGroupingPowder::createGroups(), Mantid::DataHandling::CreateSimulationWorkspace::createInstrument(), Mantid::DataHandling::Load::createLoader(), Mantid::Algorithms::MaskDetectorsIf::createNewCalFile(), Mantid::MDAlgorithms::ConvertToMD::createNewMDWorkspace(), Mantid::MDAlgorithms::MDNorm::createNormalizationWS(), Mantid::MDAlgorithms::MDNormDirectSC::createNormalizationWS(), Mantid::MDAlgorithms::MDNormSCD::createNormalizationWS(), Mantid::Algorithms::AddTimeSeriesLog::createOrUpdate(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::CurveFitting::Algorithms::LeBailFit::createOutputDataWorkspace(), Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace(), Mantid::DataHandling::CreateSimulationWorkspace::createOutputWorkspace(), Mantid::Algorithms::Rebin2D::createOutputWorkspace(), Mantid::DataHandling::LoadNexusMonitors2::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::Algorithms::ScaleX::createOutputWS(), Mantid::Algorithms::ChangeTimeZero::createOutputWS(), Mantid::MDAlgorithms::FindPeaksMD::createPeak(), Mantid::DataHandling::SaveNXcanSASBase::createPolarizedComponentMap(), Mantid::Algorithms::AnnularRingAbsorption::createSampleShapeXML(), Mantid::DataHandling::SaveCanSAS1D::createSASDetectorElement(), Mantid::DataHandling::SaveCanSAS1D::createSASInstrument(), Mantid::DataHandling::SaveCanSAS1D::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D::createSASSampleElement(), Mantid::DataHandling::LoadEventNexus::createSpectraMapping(), Mantid::DataHandling::SaveAscii2::createSpectrumFilename(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::createTableWorkspace(), Mantid::MDAlgorithms::SlicingAlgorithm::createTransform(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), Mantid::CurveFitting::Algorithms::DoublePulseFit::declareAdditionalProperties(), Mantid::DataHandling::LoadILLReflectometry::detectorRotation(), Mantid::Algorithms::SumSpectra::determineIndices(), Mantid::Algorithms::PDFFourierTransform::determineQmaxIndex(), Mantid::Algorithms::PDFFourierTransform::determineQminIndex(), Mantid::Algorithms::DiffractionFocussing2::determineRebinParametersFromParameters(), Mantid::Algorithms::PDFFourierTransform::determineRho0(), Mantid::Algorithms::PDFFourierTransform2::determineRho0(), Mantid::Algorithms::CompareWorkspaces::doComparison(), Mantid::MDAlgorithms::CompareMDWorkspaces::doComparison(), Mantid::Algorithms::MedianDetectorTest::doDetectorTests(), Mantid::Algorithms::DetectorDiagnostic::doDetVanTest(), Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::MDAlgorithms::LoadMD::doLoad(), Mantid::Algorithms::CompareWorkspaces::doMDComparison(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::doParameterSpaceRandomWalk(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::MDAlgorithms::SaveMD::doSaveEvents(), Mantid::MDAlgorithms::SaveMD2::doSaveHisto(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doSimulatedAnnealing(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Crystal::StatisticsOfPeaksWorkspace::doSortHKL(), Mantid::Algorithms::CompareWorkspaces::doTableComparison(), Mantid::MDAlgorithms::ConvertToMD::doWeNeedNewTargetWorkspace(), Mantid::Algorithms::PolarizationCorrectionWildes::efficiencyFactors(), Mantid::Algorithms::He3TubeEfficiency::eventHelper(), Mantid::Algorithms::AbsorptionCorrection::exec(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), Mantid::Algorithms::AddLogDerivative::exec(), Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::AddPeak::exec(), Mantid::Algorithms::AddSampleLog::exec(), Mantid::Algorithms::AddTimeSeriesLog::exec(), Mantid::Algorithms::AnnularRingAbsorption::exec(), Mantid::Algorithms::AppendSpectra::exec(), Mantid::Algorithms::ApplyCalibration::exec(), Mantid::Algorithms::ApplyDetailedBalance::exec(), Mantid::Algorithms::ApplyFloodWorkspace::exec(), Mantid::Algorithms::ApplyInstrumentToPeaks::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::Bin2DPowderDiffraction::exec(), Mantid::Algorithms::BinaryOperateMasks::exec(), Mantid::Algorithms::BinaryOperation::exec(), Mantid::Algorithms::CalculateCountRate::exec(), Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::CalculateDynamicRange::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateEfficiency2::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CalculateIqt::exec(), Mantid::Algorithms::CalculatePlaczek::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering2::exec(), Mantid::Algorithms::CalculatePolynomialBackground::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::CalculateZscore::exec(), Mantid::Algorithms::ChangeBinOffset::exec(), Mantid::Algorithms::ChangeLogTime::exec(), Mantid::Algorithms::ChangePulsetime::exec(), Mantid::Algorithms::ChangePulsetime2::exec(), Mantid::Algorithms::ChangeTimeZero::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::ClearInstrumentParameters::exec(), Mantid::Algorithms::ClearMaskFlag::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::CombineDiffCal::exec(), Mantid::Algorithms::CombineTableWorkspaces::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::ConjoinWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::ConvertFromDistribution::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::ConvertSpectrumAxis2::exec(), Mantid::Algorithms::ConvertTableToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertToDistribution::exec(), Mantid::Algorithms::ConvertToEventWorkspace::exec(), Mantid::Algorithms::ConvertToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CopyDataRange::exec(), Mantid::Algorithms::CopyDetectorMapping::exec(), Mantid::Algorithms::CopyInstrumentParameters::exec(), Mantid::Algorithms::CopyLogs::exec(), Mantid::Algorithms::CopySample::exec(), Mantid::Algorithms::CorelliCalibrationApply::exec(), Mantid::Algorithms::CorelliCalibrationDatabase::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CorrectToFile::exec(), Mantid::Algorithms::CreateBootstrapWorkspaces::exec(), Mantid::Algorithms::CreateCalFileByNames::exec(), Mantid::Algorithms::CreateDetectorTable::exec(), Mantid::Algorithms::CreateDummyCalFile::exec(), Mantid::Algorithms::CreateEPP::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogPropertyTable::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreateMonteCarloWorkspace::exec(), Mantid::Algorithms::CreatePeaksWorkspace::exec(), Mantid::Algorithms::CreatePSDBleedMask::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateSingleValuedWorkspace::exec(), Mantid::Algorithms::CreateUserDefinedBackground::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::CropWorkspace::exec(), Mantid::Algorithms::CropWorkspaceRagged::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DeleteLog::exec(), Mantid::Algorithms::DeleteWorkspace::exec(), Mantid::Algorithms::DeleteWorkspaces::exec(), Mantid::Algorithms::DetectorDiagnostic::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::DirectILLTubeBackground::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::Divide::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::EQSANSCorrectFrame::exec(), Mantid::Algorithms::EQSANSTofStructure::exec(), Mantid::Algorithms::EstimateDivergence::exec(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::exec(), Mantid::Algorithms::ExportTimeSeriesLog::exec(), Mantid::Algorithms::ExtractFFTSpectrum::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::ExtractSingleSpectrum::exec(), Mantid::Algorithms::ExtractSpectra::exec(), Mantid::Algorithms::ExtractUnmaskedSpectra::exec(), Mantid::Algorithms::FFT::exec(), Mantid::Algorithms::FFTSmooth::exec(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FilterByLogValue::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::FilterByXValue::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FindCenterOfMassPosition2::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::FindEPP::exec(), Mantid::Algorithms::FixGSASInstrumentFile::exec(), Mantid::Algorithms::GeneralisedSecondDifference::exec(), Mantid::Algorithms::GenerateEventsFilter::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GenerateIPythonNotebook::exec(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::Algorithms::GetAllEi::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::GetEi::exec(), Mantid::Algorithms::GetEi2::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::GetQsInQENSData::exec(), Mantid::Algorithms::GetTimeSeriesLogInformation::exec(), Mantid::Algorithms::GroupToXResolution::exec(), Mantid::Algorithms::GroupWorkspaces::exec(), Mantid::Algorithms::He3TubeEfficiency::exec(), Mantid::Algorithms::HyspecScharpfCorrection::exec(), Mantid::Algorithms::IdentifyNoisyDetectors::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::IntegrateEPP::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::InterpolatingRebin::exec(), Mantid::Algorithms::InvertMask::exec(), Mantid::Algorithms::IQTransform::exec(), Mantid::Algorithms::LineProfile::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::MagFormFactorCorrection::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskBinsFromTable::exec(), Mantid::Algorithms::MaskBinsFromWorkspace::exec(), Mantid::Algorithms::MaskBinsIf::exec(), Mantid::Algorithms::MaskInstrument::exec(), Mantid::Algorithms::MaskNonOverlappingBins::exec(), Mantid::Algorithms::Max::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::MedianDetectorTest::exec(), Mantid::Algorithms::MergeLogs::exec(), Mantid::Algorithms::MergeRuns::exec(), Mantid::Algorithms::Min::exec(), Mantid::Algorithms::ModeratorTzero::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::MonitorEfficiencyCorUser::exec(), Mantid::Algorithms::MonteCarloAbsorption::exec(), Mantid::Algorithms::MostLikelyMean::exec(), Mantid::Algorithms::MultipleScatteringCorrection::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::NormaliseByCurrent::exec(), Mantid::Algorithms::NormaliseByDetector::exec(), Mantid::Algorithms::NormaliseToMonitor::exec(), Mantid::Algorithms::NormaliseToUnity::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::PaddingAndApodization::exec(), Mantid::Algorithms::ParallaxCorrection::exec(), Mantid::Algorithms::Pause::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDDetermineCharacterizations::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::PointByPointVCorrection::exec(), Mantid::Algorithms::PolarizationCorrectionFredrikze::exec(), Mantid::Algorithms::FlipperEfficiency::exec(), Mantid::Algorithms::HeliumAnalyserEfficiency::exec(), Mantid::Algorithms::PolarizationCorrectionWildes::exec(), Mantid::Algorithms::PolarizationEfficiencyCor::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::Q1DWeighted::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Algorithms::RadiusSum::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::ReadGroupsFromFile::exec(), Mantid::Algorithms::RealFFT::RealFFT::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin2D::exec(), Mantid::Algorithms::RebinByTimeBase::exec(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::RebinToWorkspace::exec(), Mantid::Algorithms::Rebunch::exec(), Mantid::Algorithms::Regroup::exec(), Mantid::Algorithms::RemoveBackground::exec(), Mantid::Algorithms::RemoveBins::exec(), Mantid::Algorithms::RemoveInstrumentGeometry::exec(), Mantid::Algorithms::RemoveLowResTOF::exec(), Mantid::Algorithms::RemoveMaskedSpectra::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::RemoveWorkspaceHistory::exec(), Mantid::Algorithms::RenameWorkspace::exec(), Mantid::Algorithms::RenameWorkspaces::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::ResetNegatives::exec(), Mantid::Algorithms::ResizeRectangularDetector::exec(), Mantid::Algorithms::RingProfile::exec(), Mantid::Algorithms::MayersSampleCorrection::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::Scale::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Algorithms::Segfault::exec(), Mantid::Algorithms::SetInstrumentParameter::exec(), Mantid::Algorithms::SetUncertainties::exec(), Mantid::Algorithms::ShiftLogTime::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SmoothNeighbours::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::Algorithms::SofQWPolygon::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::SortEvents::exec(), Mantid::Algorithms::SortXAxis::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::SphericalAbsorption::exec(), Mantid::Algorithms::Stitch::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Algorithms::StripPeaks::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumEventsByLogValue::exec(), Mantid::Algorithms::SumNeighbours::exec(), Mantid::Algorithms::SumOverlappingTubes::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Algorithms::Transpose::exec(), Mantid::Algorithms::UnaryOperation::exec(), Mantid::Algorithms::UnGroupWorkspace::exec(), Mantid::Algorithms::UnwrapMonitor::exec(), Mantid::Algorithms::UnwrapMonitorsInTOF::exec(), Mantid::Algorithms::UnwrapSNS::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::Algorithms::WeightedMeanOfWorkspace::exec(), Mantid::Algorithms::WienerSmooth::exec(), Mantid::Algorithms::WorkflowAlgorithmRunner::exec(), Mantid::Algorithms::XDataConverter::exec(), Mantid::Algorithms::XrayAbsorptionCorrection::exec(), Mantid::Crystal::AddPeakHKL::exec(), Mantid::Crystal::AnvredCorrection::exec(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::CalculateUMatrix::exec(), Mantid::Crystal::CentroidPeaks::exec(), Mantid::Crystal::ClearUB::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::ConvertPeaksWorkspace::exec(), Mantid::Crystal::CountReflections::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::Crystal::FilterPeaks::exec(), Mantid::Crystal::FindClusterFaces::exec(), Mantid::Crystal::FindGoniometerAngles::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::Crystal::FindUBUsingFFT::exec(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::HasUB::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::LoadIsawUB::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::NormaliseVanadium::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::Crystal::PeaksInRegion::exec(), Mantid::Crystal::PeaksOnSurface::exec(), Mantid::Crystal::PredictFractionalPeaks::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::PredictSatellitePeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SelectCellOfType::exec(), Mantid::Crystal::SelectCellWithForm::exec(), Mantid::Crystal::SetCrystalLocation::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::Crystal::SetSpecialCoordinates::exec(), Mantid::Crystal::SetUB::exec(), Mantid::Crystal::ShowPeakHKLOffsets::exec(), Mantid::Crystal::ShowPossibleCells::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::Crystal::SortPeaksWorkspace::exec(), Mantid::Crystal::StatisticsOfPeaksWorkspace::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::CurveFitting::Algorithms::ConvolveWorkspaces::exec(), Mantid::CurveFitting::CrystalFieldEnergies::exec(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::exec(), Mantid::CurveFitting::Algorithms::SplineBackground::exec(), Mantid::CurveFitting::Algorithms::SplineInterpolation::exec(), Mantid::CurveFitting::Algorithms::SplineSmoothing::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::CurveFitting::IFittingAlgorithm::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::ApplyDiffCal::exec(), Mantid::DataHandling::CompressEvents::exec(), Mantid::DataHandling::CreateChunkingFromInstrument::exec(), Mantid::DataHandling::CreateSampleShape::exec(), Mantid::DataHandling::DefineGaugeVolume::exec(), Mantid::DataHandling::DeleteTableRows::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadFile::exec(), Mantid::DataHandling::ExtractMonitorWorkspace::exec(), Mantid::DataHandling::ExtractPolarizationEfficiencies::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::GroupDetectors2::exec(), Mantid::DataHandling::Load::exec(), Mantid::DataHandling::LoadAscii::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadCalFile::exec(), Mantid::DataHandling::LoadCanSAS1D2::exec(), Mantid::DataHandling::LoadCSNSNexus::exec(), Mantid::DataHandling::LoadDaveGrp::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadDNSEvent::exec(), Mantid::DataHandling::LoadEmptyInstrument::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadFITS::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadGSS::exec(), Mantid::DataHandling::LoadIDFFromNexus::exec(), Mantid::DataHandling::LoadILLDiffraction::exec(), Mantid::DataHandling::LoadILLPolarizationFactors::exec(), Mantid::DataHandling::LoadILLSALSA::exec(), Mantid::DataHandling::LoadILLTOF2::exec(), Mantid::DataHandling::LoadILLTOF3::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadIsawDetCal::exec(), Mantid::DataHandling::LoadLog::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadMask::exec(), Mantid::DataHandling::LoadNGEM::exec(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadParameterFile::exec(), Mantid::DataHandling::LoadPDFgetNFile::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::LoadPSIMuonBin::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::DataHandling::LoadSampleShape::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSpec::exec(), Mantid::DataHandling::LoadSpiceAscii::exec(), Mantid::DataHandling::LoadTBL::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::MaskDetectors::exec(), Mantid::DataHandling::MaskDetectorsInShape::exec(), Mantid::DataHandling::MaskSpectra::exec(), Mantid::DataHandling::ModifyDetectorDotDatFile::exec(), Mantid::DataHandling::MoveInstrumentComponent::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::RemoveLogs::exec(), Mantid::DataHandling::RenameLog::exec(), Mantid::DataHandling::RotateInstrumentComponent::exec(), Mantid::DataHandling::RotateSampleShape::exec(), Mantid::DataHandling::RotateSource::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::DataHandling::SaveBankScatteringAngles::exec(), Mantid::DataHandling::SaveCalFile::exec(), Mantid::DataHandling::SaveCanSAS1D::exec(), Mantid::DataHandling::SaveCanSAS1D2::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveDaveGrp::exec(), Mantid::DataHandling::SaveDetectorsGrouping::exec(), Mantid::DataHandling::SaveDiffCal::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveGDA::exec(), Mantid::DataHandling::SaveGSS::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SaveNexus::exec(), Mantid::DataHandling::SaveNexusESS::exec(), Mantid::DataHandling::SaveNexusGeometry::exec(), Mantid::DataHandling::SaveNexusProcessed::exec(), Mantid::DataHandling::SaveNISTDAT::exec(), Mantid::DataHandling::SaveNXcanSAS::exec(), Mantid::DataHandling::SaveNXSPE::exec(), Mantid::DataHandling::SaveNXTomo::exec(), Mantid::DataHandling::SaveOpenGenieAscii::exec(), Mantid::DataHandling::SavePAR::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::SavePDFGui::exec(), Mantid::DataHandling::SavePHX::exec(), Mantid::DataHandling::SavePolarizedNXcanSAS::exec(), Mantid::DataHandling::SaveReflectometryAscii::exec(), Mantid::DataHandling::SaveRKH::exec(), Mantid::DataHandling::SaveRMCProfile::exec(), Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec(), Mantid::DataHandling::SaveSESANS::exec(), Mantid::DataHandling::SaveSPE::exec(), Mantid::DataHandling::SaveTBL::exec(), Mantid::DataHandling::SaveVTK::exec(), Mantid::DataHandling::ScaleInstrumentComponent::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::DataHandling::SetScalingPSD::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::DataHandling::SortTableWorkspace::exec(), Mantid::DataHandling::UpdateInstrumentFromFile::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::ICat::CatalogGetDataFiles::exec(), Mantid::ICat::CatalogGetDataSets::exec(), Mantid::ICat::CatalogKeepAlive::exec(), Mantid::ICat::CatalogLogin::exec(), Mantid::ICat::CatalogPublish::exec(), Mantid::ICat::CatalogSearch::exec(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::exec(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::BinaryOperationMD::exec(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::CentroidPeaksMD2::exec(), Mantid::MDAlgorithms::ChangeQConvention::exec(), Mantid::MDAlgorithms::CloneMDWorkspace::exec(), Mantid::MDAlgorithms::CompactMD::exec(), Mantid::MDAlgorithms::CompareMDWorkspaces::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE::exec(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::exec(), Mantid::MDAlgorithms::CreateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD::exec(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::exec(), Mantid::MDAlgorithms::EvaluateMDFunction::exec(), Mantid::MDAlgorithms::FakeMDEventData::exec(), Mantid::MDAlgorithms::FindPeaksMD::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::exec(), Mantid::MDAlgorithms::ImportMDEventWorkspace::exec(), Mantid::MDAlgorithms::ImportMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::MDAlgorithms::IntegrateFlux::exec(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegratePeaksMD::exec(), Mantid::MDAlgorithms::IntegratePeaksMD2::exec(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::MDAlgorithms::MergeMDFiles::exec(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::exec(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::exec(), Mantid::MDAlgorithms::QTransform::exec(), Mantid::MDAlgorithms::QueryMDWorkspace::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::MDAlgorithms::SaveIsawQvector::exec(), Mantid::MDAlgorithms::SaveMD::exec(), Mantid::MDAlgorithms::SaveMD2::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), Mantid::MDAlgorithms::SetMDFrame::exec(), Mantid::MDAlgorithms::SetMDUsingMask::exec(), Mantid::MDAlgorithms::SliceMD::exec(), Mantid::MDAlgorithms::SmoothMD::exec(), Mantid::MDAlgorithms::SpectralMomentMD::exec(), Mantid::MDAlgorithms::ThresholdMD::exec(), Mantid::MDAlgorithms::TransformMD::exec(), Mantid::MDAlgorithms::TransposeMD::exec(), Mantid::MDAlgorithms::UnaryOperationMD::exec(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::DgsRemap::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::HFIRSANSNormalise::exec(), Mantid::Algorithms::ProcessIndirectFitParameters::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::WorkflowAlgorithms::StepScan::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::Algorithms::CropToComponent::exec(), Mantid::DataHandling::SaveFITS::exec(), Mantid::DataHandling::SetBeam::exec(), Mantid::DataHandling::SetSample::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::Crystal::PredictSatellitePeaks::exec_peaks(), Mantid::Algorithms::FFTDerivative::execComplexFFT(), Mantid::CurveFitting::Algorithms::DoublePulseFit::execConcrete(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::execConcrete(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::execConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::execConcrete(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Algorithms::ExtractSpectra::execEvent(), Mantid::Algorithms::He3TubeEfficiency::execEvent(), Mantid::Algorithms::MaskBins::execEvent(), Mantid::Algorithms::ModeratorTzeroLinear::execEvent(), Mantid::Algorithms::ScaleX::execEvent(), Mantid::Algorithms::UnaryOperation::execEvent(), Mantid::Algorithms::UnwrapSNS::execEvent(), Mantid::DataHandling::GroupDetectors2::execEvent(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::DataHandling::SaveNexusProcessed::execEvent(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::WorkflowAlgorithms::DgsRemap::execGrouping(), Mantid::MDAlgorithms::LogarithmMD::execHisto(), Mantid::MDAlgorithms::PowerMD::execHisto(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::MDAlgorithms::EqualToMD::execHistoHisto(), Mantid::MDAlgorithms::EqualToMD::execHistoScalar(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::DataHandling::LoadMuonNexusV2::execLoader(), Mantid::DataHandling::LoadNexusLogs::execLoader(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::MDAlgorithms::LoadMD::execLoader(), Mantid::WorkflowAlgorithms::DgsRemap::execMasking(), Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::DataHandling::MaskDetectors::execPeaks(), Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer(), Mantid::Crystal::PeaksIntersection::executePeaksIntersection(), Mantid::Algorithms::ConvertUnits::executeUnitConversion(), Mantid::Algorithms::GetTimeSeriesLogInformation::exportErrorLog(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::extractMembersAlgorithm(), Mantid::Algorithms::GetEi::extractSpec(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspaceRaw(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingGenerator(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingPeaksWorkspace(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::Algorithms::GetAllEi::findMonitorPeak(), Mantid::API::MultiPeriodGroupWorker::findMultiPeriodGroups(), Mantid::Algorithms::SmoothNeighbours::findNeighboursRectangular(), Mantid::Algorithms::SmoothNeighbours::findNeighboursUbiquitous(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::Algorithms::FindPeaks::findPeaksUsingMariscotti(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::CreateMDWorkspace::finish(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), Mantid::Algorithms::CalculateTransmission::fit(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Algorithms::DirectILLTubeBackground::fitComponentBackground(), Mantid::Algorithms::HeliumAnalyserEfficiency::fitDecayTime(), Mantid::Algorithms::HeliumAnalyserEfficiency::fitHe3Polarization(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::Crystal::PeakIntegration::fitneighbours(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::fitToData(), Mantid::Algorithms::AppendSpectra::fixSpectrumNumbers(), Mantid::Algorithms::ConjoinWorkspaces::fixSpectrumNumbers(), Mantid::DataHandling::GroupDetectors2::formGroups(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::Algorithms::IQTransform::general(), Mantid::DataHandling::SaveGSS::generateBankData(), Mantid::Algorithms::GeneratePythonFitScript::generateFitScript(), Mantid::Algorithms::FitPeaks::generateFittedParametersValueWorkspaces(), Mantid::Algorithms::GeneratePythonFitScript::generateFunctionString(), Mantid::DataHandling::SaveGSS::generateGSASBuffer(), Mantid::DataHandling::SaveGSS::generateInstrumentHeader(), Mantid::DataHandling::SaveGSS::generateOutFileNames(), Mantid::Algorithms::GeneratePythonFitScript::generateSimultaneousFitCode(), Mantid::Algorithms::GeneratePythonFitScript::generateVariableSetupCode(), Mantid::Algorithms::FitPeak::genOutputTableWS(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getAdditionalLogStrings(), Mantid::Crystal::FindSXPeaks::getBackgroundStrategy(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::getBanks(), Mantid::MDAlgorithms::MDNorm::getBinParameters(), Mantid::DataHandling::ApplyDiffCal::getCalibrationWS(), Mantid::Crystal::FindSXPeaks::getCompareStrategy(), Mantid::CurveFitting::Algorithms::PawleyFit::getCompositeFunction(), Mantid::CurveFitting::IFittingAlgorithm::getCostFunctionInitialized(), Mantid::MDAlgorithms::ReplicateMD::getDataWorkspace(), Mantid::Algorithms::TOFSANSResolution::getEffectiveXPixelSize(), Mantid::Algorithms::TOFSANSResolution::getEffectiveYPixelSize(), Mantid::Algorithms::PolarizationEfficiencyCor::getEfficiencies(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient2(), Mantid::Algorithms::PolarizationCorrectionFredrikze::getEfficiencyWorkspace(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::Algorithms::ConvertSpectrumAxis2::getEfixed(), Mantid::Algorithms::Stitch1D::getEndOverlap(), Mantid::Algorithms::ProcessIndirectFitParameters::getEndRow(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::getExclude(), Mantid::DataHandling::LoadIsawDetCal::getFilenames(), Mantid::DataHandling::PDLoadCharacterizations::getFilenames(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient2(), Mantid::Algorithms::DiffractionFocussing2::getGroupingWorkspace(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::Algorithms::SumOverlappingTubes::getHeightAxis(), Mantid::Algorithms::SumOverlappingTubes::getInputParameters(), Mantid::ICat::CatalogSearch::getInputProperties(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::Algorithms::CreateFloodWorkspace::getInputWorkspace(), Mantid::Algorithms::Integration::getInputWorkspace(), Mantid::Algorithms::CreateGroupingWorkspace::getInstrument(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::DataHandling::LoadDiffCal::getInstrument(), Mantid::Crystal::LoadIsawSpectrum::getInstrument3Ways(), Mantid::DataHandling::LoadCalFile::getInstrument3Ways(), Mantid::Algorithms::NormaliseToMonitor::getInWSMonitorSpectrum(), Mantid::Algorithms::FindPeaksConvolve::getKernelBinCount(), Mantid::Algorithms::PDDetermineCharacterizations::getLogValue(), Mantid::Algorithms::AddSampleLog::getMetaData(), Mantid::Algorithms::TOFSANSResolutionByPixel::getModeratorWorkspace(), Mantid::Crystal::PredictFractionalPeaks::getModulationInfo(), Mantid::Algorithms::NormaliseToMonitor::getMonitorWorkspace(), Mantid::Crystal::PredictSatellitePeaks::getOffsetVector(), Mantid::Crystal::SortHKL::getOutputPeaksWorkspace(), Mantid::Algorithms::CalculatePlaczek::getPackingFraction(), Mantid::Algorithms::CalculatePlaczekSelfScattering::getPackingFraction(), Mantid::Algorithms::He3TubeEfficiency::getParameter(), Mantid::Crystal::FindSXPeaks::getPeakFindingStrategy(), Mantid::Crystal::CountReflections::getPeaksWorkspace(), Mantid::Algorithms::FFT::getPhaseShift(), Mantid::Algorithms::GetAllEi::getPLogForProperty(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), Mantid::DataHandling::MaskDetectors::getRanges(), Mantid::Algorithms::Stitch1D::getRebinParams(), Mantid::Crystal::FindSXPeaks::getReducePeakListStrategy(), Mantid::Algorithms::CalculatePlaczek::getSampleTemperature(), Mantid::Algorithms::SumOverlappingTubes::getScatteringAngleBinning(), Mantid::MDAlgorithms::ReplicateMD::getShapeWorkspace(), Mantid::Algorithms::Stitch1D::getStartOverlap(), Mantid::Algorithms::ProcessIndirectFitParameters::getStartRow(), Mantid::Crystal::SortHKL::getStatisticsTable(), Mantid::Algorithms::Q1DWeighted::getTableShapes(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::getTemperature(), Mantid::Algorithms::ChangeTimeZero::getTimeShift(), Mantid::Algorithms::RemoveLowResTOF::getTminData(), Mantid::Algorithms::RemovePromptPulse::getTofRange(), Mantid::Algorithms::UnwrapSNS::getTofRangeData(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::getUBMatrix(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getUniqueParameterNames(), Mantid::Algorithms::EstimateResolutionDiffraction::getWavelength(), getWorkspaceAndIndices(), Mantid::Algorithms::PolarizationEfficiencyCor::getWorkspaceGroup(), Mantid::Algorithms::SpectrumAlgorithm::getWorkspaceIndexSet(), Mantid::Algorithms::PolarizationEfficiencyCor::getWorkspaceNameList(), Mantid::CurveFitting::Algorithms::DoublePulseFit::getWorkspaces(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getWorkspaces(), Mantid::DataHandling::SaveNexusProcessed::getWSIndexList(), Mantid::Algorithms::ConjoinXRuns::getXAxis(), Mantid::Algorithms::ExtractSpectra::getXMaxIndex(), Mantid::Algorithms::ExtractSpectra::getXMinIndex(), Mantid::Algorithms::PolarizationCorrectionWildes::groupOutput(), Mantid::DataHandling::MaskDetectors::handleMaskByMaskWorkspace(), Mantid::Algorithms::BinaryOperation::handleSpecialDivideMinus(), Mantid::DataHandling::SaveReflectometryAscii::header(), Mantid::DataHandling::SaveReflectometryAscii::includeQResolution(), Mantid::Algorithms::SofQCommon::initCachedValues(), Mantid::CurveFitting::Algorithms::Fit::initializeMinimizer(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::Algorithms::ConvertToConstantL2::initWorkspaces(), Mantid::Algorithms::RadiusSum::inputValidationSanityCheck(), Mantid::Crystal::SortHKL::insertStatisticsIntoTable(), Mantid::DataHandling::LoadCalFile::instrumentIsSpecified(), Mantid::Crystal::CentroidPeaks::integrate(), Mantid::Algorithms::CreateFloodWorkspace::integrate(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Crystal::CentroidPeaks::integrateEvent(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::integratePeak(), Mantid::Algorithms::FindDeadDetectors::integrateWorkspace(), Mantid::Algorithms::SumRowColumn::integrateWorkspace(), Mantid::Algorithms::MaskNonOverlappingBins::isCommonBins(), Mantid::Crystal::IntegratePeakTimeSlices::isGoodFit(), Mantid::Algorithms::ConjoinXRuns::joinSpectrum(), Mantid::Algorithms::PDCalibration::load(), Mantid::Algorithms::PDCalibration::loadAndBin(), Mantid::WorkflowAlgorithms::SANSBeamFinder::loadBeamFinderFile(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::loadCollimatorInfo(), Mantid::DataHandling::LoadILLLagrange::loadData(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadData(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadCanSAS1D2::loadEntry(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFrom3MF(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataHandling::LoadSassena::loadFQT(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::MDAlgorithms::LoadMD::loadHisto(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::Algorithms::VesuvioL1ThetaResolution::loadInstrument(), Mantid::DataHandling::LoadEventNexus::loadInstrument(), Mantid::DataHandling::LoadISISNexus2::loadLogs(), Mantid::DataHandling::LoadILLSANS::loadMetaData(), Mantid::DataHandling::Load::loadMultipleFiles(), Mantid::DataHandling::LoadILLReflectometry::loadNexusEntriesIntoProperties(), Mantid::DataHandling::LoadNexusLogs::loadNXLog(), Mantid::DataHandling::LoadPLN::loadParameters(), Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::DataHandling::LoadLog::LoadSNSText(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::loadSpiceData(), Mantid::Crystal::PredictPeaks::logNumberOfPeaksFound(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make1DWorkspace(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make2DWorkspace(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::Algorithms::HeliumAnalyserEfficiency::makeFit(), Mantid::DataHandling::LoadDiffCal::makeGroupingWorkspace(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::makeIntegrationParameters(), Mantid::DataHandling::LoadDiffCal::makeMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::DataHandling::LoadFITS::makeWorkspace(), Mantid::Algorithms::PolarizationCorrectionWildes::mapInputsToDirections(), Mantid::Algorithms::PolarizationEfficienciesWildes::mapSpinStateWorkspaces(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::Algorithms::MedianDetectorTest::maskOutliers(), Mantid::Algorithms::GetEiMonDet3::minimumTOF(), Mantid::Algorithms::GetEiMonDet3::monitorPeakPosition(), Mantid::Algorithms::FFTDerivative::multiplyTransform(), Mantid::Algorithms::NormaliseToMonitor::normaliseByIntegratedCount(), Mantid::DataHandling::LoadEventPreNexus2::openEventFile(), Mantid::DataHandling::SaveGSS::openFileStream(), Mantid::DataHandling::SaveOpenGenieAscii::openFileStream(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::Crystal::SCDCalibratePanels2::optimizeL1(), Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos(), Mantid::Crystal::SCDCalibratePanels2::optimizeT0(), Mantid::Algorithms::MaskDetectorsIf::outputToWorkspace(), Mantid::Algorithms::PDDetermineCharacterizations::overrideRunNumProperty(), Mantid::DataHandling::UpdateInstrumentFromFile::parseAsciiHeader(), Mantid::Algorithms::MultipleScatteringCorrection::parseInputs(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::DataHandling::SaveGDA::parseParamsFile(), Mantid::Algorithms::SumOverlappingTubes::performBinning(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::Algorithms::Q1D2::pixelWeight(), Mantid::CurveFitting::Functions::UserFunction1D::prepare(), Mantid::DataHandling::SaveCanSAS1D::prepareFileToWriteEntry(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::Algorithms::FindPeaks::processAlgorithmProperties(), Mantid::Algorithms::EstimateResolutionDiffraction::processAlgProperties(), Mantid::Algorithms::GeneratePeaks::processAlgProperties(), Mantid::DataHandling::SaveNXTomo::processAll(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::MDAlgorithms::SlicingAlgorithm::processGeneralTransformProperties(), Mantid::Algorithms::CalculateEfficiency2::processGroups(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::DataHandling::SaveNexusESS::processGroups(), Mantid::DataHandling::SaveNXcanSAS::processGroups(), Mantid::API::MultiPeriodGroupWorker::processGroups(), Mantid::DataHandling::LoadAscii2::processHeader(), Mantid::DataHandling::LoadAscii::processHeader(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::processIndirectFitParameters(), Mantid::Algorithms::GenerateEventsFilter::processInOutWorkspaces(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputBackground(), Mantid::Algorithms::FitPeaks::processInputFitRanges(), Mantid::Algorithms::FitPeaks::processInputFunctions(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::Algorithms::FitPeaks::processInputPeakTolerance(), Mantid::Algorithms::FindPeakBackground::processInputProperties(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::processInputProperties(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputProperties(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::processInputProperties(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::DataHandling::LoadSpiceXML2DDet::processInputs(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::GenerateEventsFilter::processInputTime(), Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter(), Mantid::DataHandling::LoadEventPreNexus2::processInvestigationInputs(), Mantid::DataHandling::LoadRawHelper::ProcessLoadMonitorOptions(), Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters(), Mantid::Algorithms::MaskNonOverlappingBins::processNonRagged(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::DataHandling::SaveFullprofResolution::processProperties(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::Algorithms::MaskNonOverlappingBins::processRagged(), Mantid::DataHandling::DownloadInstrument::processRepository(), Mantid::Algorithms::GenerateEventsFilter::processSingleValueFilter(), Mantid::Algorithms::GetTimeSeriesLogInformation::processTimeRange(), Mantid::DataHandling::SaveGSS::processUserSpecifiedHeaders(), Mantid::DataHandling::GroupDetectors2::processXMLFile(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::Crystal::SCDCalibratePanels2::profileBanks(), Mantid::Crystal::SCDCalibratePanels2::profileL1(), Mantid::Crystal::SCDCalibratePanels2::profileL1T0(), Mantid::Crystal::SCDCalibratePanels2::profileT0(), Mantid::DataHandling::LoadRKH::read1D(), Mantid::Algorithms::Bin2DPowderDiffraction::ReadBinsFromFile(), Mantid::WorkflowAlgorithms::EQSANSLoad::readConfigFile(), Mantid::DataHandling::LoadAscii::readData(), Mantid::MDAlgorithms::LoadSQW2::readDataSection(), Mantid::DataHandling::LoadMcStas::readEventData(), Mantid::DataHandling::LoadMcStas::readHistogramData(), Mantid::DataHandling::LoadPSIMuonBin::readInTemperatureFile(), Mantid::Crystal::LoadIsawUB::readModulatedUB(), Mantid::CurveFitting::Algorithms::Fit::readProperties(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::readTableInfo(), Mantid::Algorithms::RebinToWorkspace::rebin(), Mantid::Algorithms::CalculateIqt::rebinParamsAsString(), Mantid::Algorithms::CompareWorkspaces::recordMismatch(), Mantid::Crystal::FindSXPeaks::reducePeakList(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::refineInstrumentParametersMC(), Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::Crystal::CentroidPeaks::removeEdgePeaks(), Mantid::CurveFitting::Functions::ProcessBackground::removePeaks(), Mantid::Algorithms::ConvertUnits::removeUnphysicalBins(), Mantid::Algorithms::SumSpectra::replaceSpecialValues(), Mantid::Algorithms::AbsorptionCorrection::retrieveBaseProperties(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::retrieveBaseProperties(), Mantid::Algorithms::SphericalAbsorption::retrieveBaseProperties(), Mantid::Crystal::AnvredCorrection::retrieveBaseProperties(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::retrieveInputs(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::retrieveInputs(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::retrieveInputs(), Mantid::Algorithms::DetectorEfficiencyCor::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveProperties(), Mantid::Algorithms::MaskDetectorsIf::retrieveProperties(), Mantid::Algorithms::MedianDetectorTest::retrieveProperties(), Mantid::Crystal::MaskPeaksWorkspace::retrieveProperties(), Mantid::Crystal::PeakIntegration::retrieveProperties(), Mantid::Algorithms::AnyShapeAbsorption::retrieveProperties(), Mantid::Algorithms::CylinderAbsorption::retrieveProperties(), Mantid::Algorithms::ExponentialCorrection::retrieveProperties(), Mantid::Algorithms::FlatPlateAbsorption::retrieveProperties(), Mantid::Algorithms::Logarithm::retrieveProperties(), Mantid::Algorithms::OneMinusExponentialCor::retrieveProperties(), Mantid::Algorithms::PolynomialCorrection::retrieveProperties(), Mantid::Algorithms::Power::retrieveProperties(), Mantid::Algorithms::PowerLawCorrection::retrieveProperties(), Mantid::Algorithms::ReplaceSpecialValues::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyVariation::retrieveProperties(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::retrieveWorkspaceForWavelength(), Mantid::WorkflowAlgorithms::StepScan::runFilterByXValue(), Mantid::CurveFitting::Algorithms::DoublePulseFit::runFitAlgorith(), Mantid::Algorithms::HRPDSlabCanAbsorption::runFlatPlateAbsorption(), Mantid::DataHandling::LoadDiffCal::runLoadCalFile(), Mantid::DataHandling::LoadMuonNexusV2::runLoadISISNexus(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadNexusMonitors2::runLoadLogs(), Mantid::DataHandling::LoadEventNexus::runLoadMonitors(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::Algorithms::UnwrapSNS::runMaskDetectors(), Mantid::Algorithms::AnnularRingAbsorption::runMonteCarloAbsorptionCorrection(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::Algorithms::AnnularRingAbsorption::runSetSampleMaterial(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::DataHandling::GenerateGroupingPowder::saveAsNexus(), Mantid::DataHandling::GenerateGroupingPowder::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder2::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder::saveAsXML(), Mantid::DataHandling::GenerateGroupingPowder2::saveAsXML(), Mantid::DataHandling::GenerateGroupingPowder::saveGroups(), Mantid::DataHandling::GenerateGroupingPowder2::saveGroups(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Algorithms::Stitch::scale(), Mantid::Algorithms::CreateFloodWorkspace::scaleToCentralPixel(), Mantid::CurveFitting::Functions::ProcessBackground::selectBkgdPoints(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenFunction(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::CurveFitting::Algorithms::SplineSmoothing::selectSmoothingPoints(), Mantid::DataHandling::SaveReflectometryAscii::separator(), Mantid::API::BoxControllerSettingsAlgorithm::setBoxController(), Mantid::DataHandling::LoadHFIRSANS::setDetectorDistance(), Mantid::DataHandling::LoadAscii2::setDistribution(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly(), Mantid::Algorithms::GetAllEi::setFilterLog(), Mantid::CurveFitting::IFittingAlgorithm::setFunction(), Mantid::DataHandling::LoadSpice2D::setInputPropertiesAsMemberProperties(), Mantid::Algorithms::NormaliseToMonitor::setIntegrationProps(), Mantid::DataHandling::LoadRaw3::setOptionalProperties(), Mantid::DataHandling::LoadRawBin0::setOptionalProperties(), Mantid::Algorithms::CalculateCountRate::setOutLogParameters(), Mantid::CurveFitting::Algorithms::DoublePulseFit::setOutputProperties(), Mantid::Algorithms::PolarizationEfficienciesWildes::setOutputs(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::Algorithms::Divide::setOutputUnits(), Mantid::DataHandling::Load::setPropertyValue(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), Mantid::DataHandling::CreateSimulationWorkspace::setStartDate(), Mantid::CurveFitting::IFittingAlgorithm::setStepSizeMethod(), Mantid::Crystal::PredictPeaks::setStructureFactorCalculatorFromSample(), Mantid::Algorithms::CreateDetectorTable::setTableToOutput(), Mantid::DataHandling::LoadEventNexus::setTimeFilters(), Mantid::Algorithms::AddSampleLog::setTimeSeriesData(), Mantid::DataHandling::LoadEventNexus::setTopEntryName(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::MDAlgorithms::LoadSQW2::setupBoxController(), Mantid::Algorithms::FilterEvents::setupCustomizedTOFCorrection(), Mantid::Crystal::IntegratePeakTimeSlices::SetUpData(), Mantid::Crystal::IntegratePeakTimeSlices::SetUpData1(), Mantid::Algorithms::FilterEvents::setupDirectTOFCorrection(), Mantid::Algorithms::Qxy::setUpOutputWorkspace(), Mantid::Algorithms::ConvertUnits::setupOutputWorkspace(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogs(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::DataHandling::LoadDaveGrp::setupWorkspace(), Mantid::DataHandling::LoadHFIRSANS::setWavelength(), Mantid::Algorithms::SmoothNeighbours::setWeightingStrategy(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::Algorithms::FindPeaksConvolve::storeClassProperties(), Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace(), Mantid::API::BoxControllerSettingsAlgorithm::takeDefaultsFromInstrument(), Mantid::Algorithms::UnwrapMonitor::unwrapX(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromAscii(), Mantid::Crystal::SCDCalibratePanels2::updateUBMatrix(), Mantid::Algorithms::MaxEnt::validateBinEdges(), Mantid::DataHandling::LoadNGEM::validateEventsPerFrame(), Mantid::Algorithms::AbsorptionCorrection::validateInputs(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::validateInputs(), Mantid::Algorithms::AddLogInterpolated::validateInputs(), Mantid::Algorithms::AddLogSmoothed::validateInputs(), Mantid::Algorithms::ApplyTransmissionCorrection::validateInputs(), Mantid::Algorithms::CalculateDIFC::validateInputs(), Mantid::Algorithms::CalculateDynamicRange::validateInputs(), Mantid::Algorithms::CalculateEfficiency2::validateInputs(), Mantid::Algorithms::CalculateIqt::validateInputs(), Mantid::Algorithms::CalculatePlaczek::validateInputs(), Mantid::Algorithms::CalculatePlaczekSelfScattering::validateInputs(), Mantid::Algorithms::ChangeTimeZero::validateInputs(), Mantid::Algorithms::CombineDiffCal::validateInputs(), Mantid::Algorithms::CombineTableWorkspaces::validateInputs(), Mantid::Algorithms::ConjoinXRuns::validateInputs(), Mantid::Algorithms::ConvertDiffCal::validateInputs(), Mantid::Algorithms::ConvertToDistribution::validateInputs(), Mantid::Algorithms::CopyDataRange::validateInputs(), Mantid::Algorithms::CopyDetectorMapping::validateInputs(), Mantid::Algorithms::CopySample::validateInputs(), Mantid::Algorithms::CorelliCalibrationApply::validateInputs(), Mantid::Algorithms::CorelliCalibrationDatabase::validateInputs(), Mantid::Algorithms::CorelliCrossCorrelate::validateInputs(), Mantid::Algorithms::CreateDetectorTable::validateInputs(), Mantid::Algorithms::CreateUserDefinedBackground::validateInputs(), Mantid::Algorithms::CreateWorkspace::validateInputs(), Mantid::Algorithms::CropToComponent::validateInputs(), Mantid::Algorithms::CropWorkspaceRagged::validateInputs(), Mantid::Algorithms::CrossCorrelate::validateInputs(), Mantid::Algorithms::CylinderAbsorption::validateInputs(), Mantid::Algorithms::DetermineSpinStateOrder::validateInputs(), Mantid::Algorithms::DiffractionFocussing2::validateInputs(), Mantid::Algorithms::DirectILLTubeBackground::validateInputs(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::validateInputs(), Mantid::Algorithms::EditInstrumentGeometry::validateInputs(), Mantid::Algorithms::EstimateResolutionDiffraction::validateInputs(), Mantid::Algorithms::ExtractSpectra::validateInputs(), Mantid::Algorithms::FFT::validateInputs(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::validateInputs(), Mantid::Algorithms::FilterByLogValue::validateInputs(), Mantid::Algorithms::FilterByXValue::validateInputs(), Mantid::Algorithms::FilterEvents::validateInputs(), Mantid::Algorithms::FitPeaks::validateInputs(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::validateInputs(), Mantid::Algorithms::GeneratePythonFitScript::validateInputs(), Mantid::Algorithms::GetAllEi::validateInputs(), Mantid::Algorithms::GetDetectorOffsets::validateInputs(), Mantid::Algorithms::GetQsInQENSData::validateInputs(), Mantid::Algorithms::GroupToXResolution::validateInputs(), Mantid::Algorithms::GroupWorkspaces::validateInputs(), Mantid::Algorithms::IntegrateEPP::validateInputs(), Mantid::Algorithms::Integration::validateInputs(), Mantid::Algorithms::InterpolatingRebin::validateInputs(), Mantid::Algorithms::LineProfile::validateInputs(), Mantid::Algorithms::LorentzCorrection::validateInputs(), Mantid::Algorithms::MaskNonOverlappingBins::validateInputs(), Mantid::Algorithms::MaxEnt::validateInputs(), Mantid::Algorithms::MergeLogs::validateInputs(), Mantid::Algorithms::MonteCarloAbsorption::validateInputs(), Mantid::Algorithms::MultipleScatteringCorrection::validateInputs(), Mantid::Algorithms::NormaliseToMonitor::validateInputs(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::validateInputs(), Mantid::Algorithms::ParallaxCorrection::validateInputs(), Mantid::Algorithms::PDCalibration::validateInputs(), Mantid::Algorithms::PDDetermineCharacterizations::validateInputs(), Mantid::Algorithms::PDFFourierTransform::validateInputs(), Mantid::Algorithms::PDFFourierTransform2::validateInputs(), Mantid::Algorithms::DepolarizedAnalyserTransmission::validateInputs(), Mantid::Algorithms::HeliumAnalyserEfficiency::validateInputs(), Mantid::Algorithms::PolarizationEfficienciesWildes::validateInputs(), Mantid::Algorithms::PolarizerEfficiency::validateInputs(), Mantid::Algorithms::PolarizationCorrectionWildes::validateInputs(), Mantid::Algorithms::RealFFT::RealFFT::validateInputs(), Mantid::Algorithms::Rebin::validateInputs(), Mantid::Algorithms::RebinRagged::validateInputs(), Mantid::Algorithms::RemoveBins::validateInputs(), Mantid::Algorithms::RemoveSpectra::validateInputs(), Mantid::Algorithms::RenameWorkspace::validateInputs(), Mantid::Algorithms::RenameWorkspaces::validateInputs(), Mantid::Algorithms::ResampleX::validateInputs(), Mantid::Algorithms::Scale::validateInputs(), Mantid::Algorithms::SofQWNormalisedPolygon::validateInputs(), Mantid::Algorithms::Stitch::validateInputs(), Mantid::Algorithms::Stitch1D::validateInputs(), Mantid::Algorithms::Stitch1DMany::validateInputs(), Mantid::Algorithms::SumEventsByLogValue::validateInputs(), Mantid::Algorithms::SumSpectra::validateInputs(), Mantid::Algorithms::UnwrapMonitorsInTOF::validateInputs(), Mantid::Algorithms::XrayAbsorptionCorrection::validateInputs(), Mantid::Crystal::AnvredCorrection::validateInputs(), Mantid::Crystal::ConvertPeaksWorkspace::validateInputs(), Mantid::Crystal::FindSXPeaks::validateInputs(), Mantid::Crystal::IndexPeaks::validateInputs(), Mantid::Crystal::PeakIntensityVsRadius::validateInputs(), Mantid::Crystal::PredictFractionalPeaks::validateInputs(), Mantid::Crystal::SCDCalibratePanels2::validateInputs(), Mantid::Crystal::SetGoniometer::validateInputs(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::validateInputs(), Mantid::CurveFitting::Algorithms::SplineInterpolation::validateInputs(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs(), Mantid::DataHandling::ApplyDiffCal::validateInputs(), Mantid::DataHandling::GenerateGroupingPowder::validateInputs(), Mantid::DataHandling::LoadEventAsWorkspace2D::validateInputs(), Mantid::DataHandling::LoadEventNexus::validateInputs(), Mantid::DataHandling::LoadILLPolarizationFactors::validateInputs(), Mantid::DataHandling::LoadIsawDetCal::validateInputs(), Mantid::DataHandling::LoadMask::validateInputs(), Mantid::DataHandling::LoadNexusProcessed::validateInputs(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SaveBankScatteringAngles::validateInputs(), Mantid::DataHandling::SaveDiffCal::validateInputs(), Mantid::DataHandling::SaveFITS::validateInputs(), Mantid::DataHandling::SaveGDA::validateInputs(), Mantid::DataHandling::SaveGSS::validateInputs(), Mantid::DataHandling::SavePDFGui::validateInputs(), Mantid::DataHandling::SavePolarizedNXcanSAS::validateInputs(), Mantid::DataHandling::SaveReflectometryAscii::validateInputs(), Mantid::DataHandling::SaveRMCProfile::validateInputs(), Mantid::DataHandling::SaveSESANS::validateInputs(), Mantid::DataHandling::ScaleInstrumentComponent::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::validateInputs(), Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE::validateInputs(), Mantid::MDAlgorithms::ConvertToMD::validateInputs(), Mantid::MDAlgorithms::CreateMDWorkspace::validateInputs(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::validateInputs(), Mantid::MDAlgorithms::FindPeaksMD::validateInputs(), Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase::validateInputs(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::validateInputs(), Mantid::MDAlgorithms::IntegratePeaksMD2::validateInputs(), Mantid::MDAlgorithms::MaskMD::validateInputs(), Mantid::MDAlgorithms::QTransform::validateInputs(), Mantid::MDAlgorithms::ReplicateMD::validateInputs(), Mantid::MDAlgorithms::SetMDFrame::validateInputs(), Mantid::MDAlgorithms::SmoothMD::validateInputs(), Mantid::MDAlgorithms::SpectralMomentMD::validateInputs(), Mantid::DataHandling::SetBeam::validateInputs(), Mantid::DataHandling::SetSample::validateInputs(), Mantid::MDAlgorithms::MDNorm::validateInputs(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::validateInputs(), Mantid::Algorithms::CreateEPP::validateInputs(), Mantid::DataHandling::LoadNGEM::validateMinMaxToF(), Mantid::Algorithms::FindPeaksConvolve::validatePeakExtentInput(), Mantid::DataHandling::SaveNXcanSASBase::validatePolarizedInputWorkspace(), Mantid::DataHandling::SaveNXcanSASBase::validatePolarizedMetadata(), Mantid::DataHandling::SaveNXcanSASBase::validateStandardInputs(), Mantid::Algorithms::MergeLogs::validateTSP(), Mantid::DataHandling::SaveOpenGenieAscii::writeDataToFile(), Mantid::DataHandling::SaveFITS::writeFITSHeaderBlock(), Mantid::DataHandling::SaveFITS::writeFITSImageMatrix(), Mantid::DataHandling::SaveRMCProfile::writeMetaData(), and Mantid::DataHandling::LoadAscii2::writeToWorkspace().
getPropertyValue()
std::string Mantid::API::Algorithm::getPropertyValue (const std::string & name) const override virtual
Get the value of a property as a string.
Parameters
name :: The name of the property (case insensitive)
Returns
The value of the named property
Exceptions
Exception::NotFoundError if the named property is unknown
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1916 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getPropertyValue(), m_properties, and name().
Referenced by Mantid::DataHandling::SaveNXcanSASBase::addStandardMetadata(), Mantid::Algorithms::AddSampleLog::addTimeSeriesProperty(), Mantid::DataHandling::LoadILLSANS::applySensitivityMap(), Mantid::MDAlgorithms::MDNorm::binBackgroundWS(), Mantid::MDAlgorithms::MDNorm::binInputWS(), Mantid::PythonInterface::RunPythonScript::buildLocals(), Mantid::MDAlgorithms::LoadSQW2::cacheInputs(), Mantid::Algorithms::FlipperEfficiency::calculateEfficiency(), Mantid::Algorithms::CalculateEfficiency2::calculateEfficiency(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3::calculateExtentsFromData(), Mantid::Algorithms::PolarizerEfficiency::calculatePolarizerEfficiency(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcWavelengthDependentTransmission(), Mantid::DataHandling::LoadCanSAS1D::check(), Mantid::DataHandling::SaveReflectometryAscii::checkGroups(), Mantid::DataHandling::LoadILLReflectometry::convertTofToWavelength(), Mantid::MDAlgorithms::SlicingAlgorithm::createAlignedTransform(), Mantid::DataHandling::LoadISISPolarizationEfficiencies::createEfficiencies(), Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase::createEmptyOutputWorkspace(), Mantid::Algorithms::FitPeak::createFunctions(), Mantid::DataHandling::Load::createLoader(), Mantid::DataHandling::LoadRawHelper::createMonitorWorkspace(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::createOutputWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D::createSASSourceElement(), Mantid::DataHandling::LoadILLReflectometry::detectorRotation(), Mantid::DataHandling::LoadPSIMuonBin::detectTempFile(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::MDAlgorithms::SaveMD::doSaveEvents(), Mantid::MDAlgorithms::SaveMD::doSaveHisto(), Mantid::MDAlgorithms::SaveMD2::doSaveHisto(), Mantid::Crystal::StatisticsOfPeaksWorkspace::doSortHKL(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::Algorithms::AddLogDerivative::exec(), Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::AddSampleLog::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::ChangeLogTime::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::ClearMaskFlag::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::ConjoinWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CorrectToFile::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogPropertyTable::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::EstimateResolutionDiffraction::exec(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), Mantid::Algorithms::FilterByLogValue::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FixGSASInstrumentFile::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GenerateIPythonNotebook::exec(), Mantid::Algorithms::GeneratePythonFitScript::exec(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::MaskBinsIf::exec(), Mantid::Algorithms::MonteCarloAbsorption::exec(), Mantid::Algorithms::NormaliseToMonitor::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDDetermineCharacterizations::exec(), Mantid::Algorithms::DepolarizedAnalyserTransmission::exec(), Mantid::Algorithms::FlipperEfficiency::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::RemoveLowResTOF::exec(), Mantid::Algorithms::RenameWorkspace::exec(), Mantid::Algorithms::RenameWorkspaces::exec(), Mantid::Algorithms::ResizeRectangularDetector::exec(), Mantid::Algorithms::RingProfile::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::Scale::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Algorithms::SetInstrumentParameter::exec(), Mantid::Algorithms::ShiftLogTime::exec(), Mantid::Algorithms::SortEvents::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::Stitch::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::LoadIsawPeaks::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::SplineSmoothing::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::CompressEvents::exec(), Mantid::DataHandling::CreateChunkingFromInstrument::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::ISISJournalGetExperimentRuns::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadCalFile::exec(), Mantid::DataHandling::LoadCanSAS1D::exec(), Mantid::DataHandling::LoadCSNSNexus::exec(), Mantid::DataHandling::LoadDetectorInfo::exec(), Mantid::DataHandling::LoadDiffCal::exec(), Mantid::DataHandling::LoadDNSEvent::exec(), Mantid::DataHandling::LoadEmptyInstrument::exec(), Mantid::DataHandling::LoadEMUTar::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadFITS::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadGSS::exec(), Mantid::DataHandling::LoadIDFFromNexus::exec(), Mantid::DataHandling::LoadILLDiffraction::exec(), Mantid::DataHandling::LoadILLIndirect2::exec(), Mantid::DataHandling::LoadILLPolarizedDiffraction::exec(), Mantid::DataHandling::LoadILLReflectometry::exec(), Mantid::DataHandling::LoadILLSALSA::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::LoadILLTOF2::exec(), Mantid::DataHandling::LoadILLTOF3::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadLog::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadMcStasNexus::exec(), Mantid::DataHandling::LoadMLZ::exec(), Mantid::DataHandling::LoadNexus::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::exec(), Mantid::DataHandling::LoadParameterFile::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::LoadPreNexusMonitors::exec(), Mantid::DataHandling::LoadPSIMuonBin::exec(), Mantid::DataHandling::LoadQKK::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRKH::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSampleShape::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSESANS::exec(), Mantid::DataHandling::LoadSINQFocus::exec(), Mantid::DataHandling::LoadSPE::exec(), Mantid::DataHandling::LoadSpiceAscii::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::ModifyDetectorDotDatFile::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::DataHandling::SaveCalFile::exec(), Mantid::DataHandling::SaveCanSAS1D::exec(), Mantid::DataHandling::SaveCanSAS1D2::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SaveNexus::exec(), Mantid::DataHandling::SaveNexusGeometry::exec(), Mantid::DataHandling::SaveNISTDAT::exec(), Mantid::DataHandling::SaveNXSPE::exec(), Mantid::DataHandling::SavePolarizedNXcanSAS::exec(), Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec(), Mantid::DataHandling::SaveSESANS::exec(), Mantid::DataHandling::SetScalingPSD::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::DataHandling::UpdateInstrumentFromFile::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::ICat::CatalogGetDataFiles::exec(), Mantid::ICat::CatalogGetDataSets::exec(), Mantid::ICat::CatalogKeepAlive::exec(), Mantid::ICat::CatalogListInstruments::exec(), Mantid::ICat::CatalogListInvestigationTypes::exec(), Mantid::ICat::CatalogLogout::exec(), Mantid::ICat::CatalogMyDataSearch::exec(), Mantid::ICat::CatalogPublish::exec(), Mantid::ICat::CatalogSearch::exec(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::exec(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::LoadGaussCube::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::exec(), Mantid::MDAlgorithms::QueryMDWorkspace::exec(), Mantid::MDAlgorithms::SaveIsawQvector::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), Mantid::MDAlgorithms::SpectralMomentMD::exec(), Mantid::MDAlgorithms::TransformMD::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::API::NexusFileLoader::exec(), Mantid::DataHandling::SaveFITS::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::execConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::execConcrete(), Mantid::Algorithms::ScaleX::execEvent(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::Algorithms::PolarizationEfficiencyCor::execFredrikze(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::DataHandling::LoadMcStas::execLoader(), Mantid::DataHandling::LoadMuonNexusV2::execLoader(), Mantid::DataHandling::LoadNexusLogs::execLoader(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::MDAlgorithms::LoadMD::execLoader(), Mantid::Crystal::PeaksIntersection::executePeaksIntersection(), Mantid::Algorithms::PolarizationEfficiencyCor::execWildes(), Mantid::DataHandling::LoadPSIMuonBin::extractSpectra(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingGenerator(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::Algorithms::Q1DWeighted::finalize(), Mantid::Algorithms::DirectILLTubeBackground::fitComponentBackground(), Mantid::DataHandling::SaveGSS::generateBankData(), Mantid::Algorithms::FitPeaks::generateCalculatedPeaksWS(), Mantid::Algorithms::FitPeaks::generateFittedParametersValueWorkspaces(), Mantid::DataHandling::SaveGSS::generateGSASBuffer(), Mantid::DataHandling::SaveGSS::generateInstrumentHeader(), Mantid::Algorithms::CreateFloodWorkspace::getBackgroundFunction(), Mantid::MDAlgorithms::QueryMDWorkspace::getBoxData(), Mantid::DataHandling::ApplyDiffCal::getCalibrationWS(), Mantid::Crystal::SortHKL::getCentering(), Mantid::CurveFitting::IFittingAlgorithm::getCostFunctionInitialized(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::getExclude(), Mantid::Algorithms::SumOverlappingTubes::getInputParameters(), Mantid::ICat::CatalogSearch::getInputProperties(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::Algorithms::CreateGroupingWorkspace::getInstrument(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::Crystal::LoadIsawSpectrum::getInstrument3Ways(), Mantid::DataHandling::LoadCalFile::getInstrument3Ways(), Mantid::Algorithms::AddSampleLog::getMetaData(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::getMinimizerString(), Mantid::Crystal::IntegratePeaksUsingClusters::getNormalization(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getOutputBaseName(), Mantid::Algorithms::GetEi::getPeakEstimates(), Mantid::Crystal::CountReflections::getPeaksWorkspace(), Mantid::Crystal::SortHKL::getPointgroup(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::getTimeDifference(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::getUBMatrix(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getWorkspaceIndices(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::getWorkspaceNames(), Mantid::Algorithms::PolarizationCorrectionWildes::groupOutput(), Mantid::MDAlgorithms::LoadSQW2::initFileReader(), Mantid::CurveFitting::Algorithms::Fit::initializeMinimizer(), Mantid::DataHandling::LoadILLPolarizedDiffraction::initStaticWorkspace(), Mantid::DataHandling::LoadCalFile::instrumentIsSpecified(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::DataHandling::LoadILLLagrange::loadData(), Mantid::DataHandling::LoadSwans::loadData(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadCanSAS1D2::loadEntry(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataHandling::Load::loadFileToWs(), Mantid::DataHandling::LoadSassena::loadFQ(), Mantid::DataHandling::LoadSassena::loadFQT(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::Algorithms::VesuvioL1ThetaResolution::loadInstrument(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadILLLagrange::loadMetaData(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::DataHandling::LoadILLReflectometry::loadNexusEntriesIntoProperties(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), Mantid::DataHandling::LoadISISNexus2::loadPeriodData(), Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::DataHandling::Load::loadSingleFile(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadTwoThetaDetectors(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make1DWorkspace(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make2DWorkspace(), Mantid::DataHandling::LoadPSIMuonBin::makeDeadTimeTable(), Mantid::DataHandling::LoadFITS::mapHeaderKeys(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::DataHandling::LoadILLPolarizedDiffraction::moveTwoTheta(), Mantid::Algorithms::Qhelper::outputParts(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::Algorithms::PolarizationEfficienciesWildes::populateSpinStateWorkspaces(), Mantid::DataHandling::LoadILLPolarizedDiffraction::prepareAxes(), Mantid::DataHandling::RotateSampleShape::prepareGoniometerAxes(), Mantid::Algorithms::HeliumAnalyserEfficiency::prepareOutputs(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::Algorithms::FindPeaks::processAlgorithmProperties(), Mantid::Algorithms::GeneratePeaks::processAlgProperties(), Mantid::DataHandling::SaveNXTomo::processAll(), Mantid::DataHandling::SaveNXcanSAS::processAllWorkspaces(), Mantid::MDAlgorithms::SlicingAlgorithm::processGeneralTransformProperties(), Mantid::Algorithms::CalculateEfficiency2::processGroups(), Mantid::Algorithms::ConjoinWorkspaces::processGroups(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::DataHandling::SaveNXTomo::processGroups(), Mantid::DataHandling::SaveReflectometryAscii::processGroups(), Mantid::Algorithms::GenerateEventsFilter::processInOutWorkspaces(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputBackground(), Mantid::Algorithms::FitPeaks::processInputFitRanges(), Mantid::Algorithms::FitPeaks::processInputFunctions(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::Algorithms::FindPeakBackground::processInputProperties(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputProperties(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::DataHandling::LoadSpiceXML2DDet::processInputs(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::DataHandling::SaveFullprofResolution::processProperties(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::DataHandling::LoadCanSAS1D2::processTransmission(), Mantid::ICat::CatalogPublish::publishWorkspaceHistory(), Mantid::DataHandling::LoadAscii::readData(), Mantid::DataHandling::LoadMcStas::readEventData(), Mantid::Crystal::LoadIsawPeaks::readHeader(), Mantid::DataHandling::LoadPSIMuonBin::readInTemperatureFile(), Mantid::CurveFitting::Algorithms::Fit::readProperties(), Mantid::Algorithms::PDCalibration::rebin(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::Algorithms::PolarizationEfficienciesWildes::resetPropertyValue(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::retrieveInputs(), Mantid::CurveFitting::Algorithms::DoublePulseFit::runFitAlgorith(), Mantid::DataHandling::LoadDiffCal::runLoadCalFile(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadNexus::runLoadNexusProcessed(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::Algorithms::AnnularRingAbsorption::runSetSampleMaterial(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::DataHandling::GenerateGroupingPowder::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder2::saveAsPAR(), Mantid::ICat::CatalogDownloadDataFiles::saveFiletoDisk(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::saveMDToFile(), Mantid::PythonInterface::RunPythonScript::scriptCode(), Mantid::CurveFitting::Functions::ProcessBackground::selectBkgdPoints(), Mantid::DataHandling::LoadPSIMuonBin::setDetectorGroupingTable(), Mantid::CurveFitting::IFittingAlgorithm::setDomainType(), Mantid::DataHandling::LoadHFIRSANS::setInputFileAsHandler(), Mantid::DataHandling::LoadSpice2D::setInputPropertiesAsMemberProperties(), Mantid::DataHandling::Load::setPropertyValue(), Mantid::Algorithms::CreateDetectorTable::setTableToOutput(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::Algorithms::ConvertUnits::setupMemberVariables(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::Algorithms::ConjoinWorkspaces::setYUnitAndLabel(), Mantid::Algorithms::ConvertUnits::storeEModeOnWorkspace(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::transferFileDataIntoWorkspace(), Mantid::Algorithms::AddLogInterpolated::validateInputs(), Mantid::Algorithms::AddLogSmoothed::validateInputs(), Mantid::Algorithms::CalculateEfficiency2::validateInputs(), Mantid::Algorithms::ConjoinXRuns::validateInputs(), Mantid::Algorithms::CreateGroupingWorkspace::validateInputs(), Mantid::Algorithms::DetermineSpinStateOrder::validateInputs(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::validateInputs(), Mantid::Algorithms::FilterByLogValue::validateInputs(), Mantid::Algorithms::FilterEvents::validateInputs(), Mantid::Algorithms::FitPeaks::validateInputs(), Mantid::Algorithms::GeneratePythonFitScript::validateInputs(), Mantid::Algorithms::LorentzCorrection::validateInputs(), Mantid::Algorithms::MaskBinsIf::validateInputs(), Mantid::Algorithms::MonteCarloAbsorption::validateInputs(), Mantid::Algorithms::DepolarizedAnalyserTransmission::validateInputs(), Mantid::Algorithms::FlipperEfficiency::validateInputs(), Mantid::Algorithms::PolarizerEfficiency::validateInputs(), Mantid::Algorithms::PolarizationCorrectionWildes::validateInputs(), Mantid::Algorithms::Rebin::validateInputs(), Mantid::Algorithms::RenameWorkspace::validateInputs(), Mantid::Algorithms::RenameWorkspaces::validateInputs(), Mantid::Algorithms::Scale::validateInputs(), Mantid::Algorithms::SetInstrumentParameter::validateInputs(), Mantid::Algorithms::Stitch::validateInputs(), Mantid::Algorithms::SumEventsByLogValue::validateInputs(), Mantid::Algorithms::SumSpectra::validateInputs(), Mantid::CurveFitting::Algorithms::Fit::validateInputs(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::validateInputs(), Mantid::DataHandling::CreateChunkingFromInstrument::validateInputs(), Mantid::DataHandling::GroupDetectors2::validateInputs(), Mantid::DataHandling::LoadILLPolarizedDiffraction::validateInputs(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SaveNXSPE::validateInputs(), Mantid::DataHandling::SaveReflectometryAscii::validateInputs(), Mantid::DataHandling::SaveSESANS::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::validateInputs(), Mantid::MDAlgorithms::MaskMD::validateInputs(), Mantid::PythonInterface::RunPythonScript::validateInputs(), Mantid::DataHandling::SaveRKH::writeHeader(), Mantid::DataHandling::SaveSESANS::writeHeaders(), and Mantid::DataHandling::SaveGSS::writeRALFHeader().
getWorkspaceAndIndices()
template<typename T , typename > std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > Mantid::API::Algorithm::getWorkspaceAndIndices (const std::string & name) const
Mechanism for retriving the index property.
This method can only be used if T is convertible to a MatrixWorkspace.
Parameters
name Property name
Returns
Tuple containing Workspace shared pointer and SpectrumIndexSet
Definition at line 127 of file Algorithm.hxx.
References Mantid::API::IndexProperty::generatePropertyName(), getPointerToProperty(), getProperty(), isCompoundProperty(), and name().
handleChildProgressNotification()
void Mantid::API::Algorithm::handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > & pNf) protected
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
Handles and rescales child algorithm progress notifications.
Parameters
pNf :: The progress notification from the child algorithm.
Definition at line 1641 of file Algorithm.cpp.
References m_endChildProgress, m_startChildProgress, and progress().
Referenced by progressObserver().
helpURL()
const std::string Mantid::API::Algorithm::helpURL () const inline override virtual
function to return URL for algorithm documentation; A default implementation is provided.
Override if the algorithm is not part of the Mantid distribution.
Implements Mantid::API::IAlgorithm.
Definition at line 180 of file Algorithm.h.
init()
virtual void Mantid::API::Algorithm::init () protected pure virtual
Virtual method - must be overridden by concrete algorithm.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::BinaryOperation, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByTimeBase, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnaryOperation, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XDataConverter, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::IFittingAlgorithm, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GenerateGroupingPowder2, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace2, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::ConvertToMDParent, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QTransform, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, and Mantid::DataHandling::SetSample.
Referenced by Mantid::DataHandling::LoadEMUTar::init(), Mantid::DataHandling::LoadEMUHdf::init(), and initialize().
initialize()
void Mantid::API::Algorithm::initialize () override virtual
Initialization method invoked by the framework.
This method is responsible for any bookkeeping of initialization required by the framework itself. It will in turn invoke the init() method of the derived algorithm, and of any Child Algorithms which it creates.
Exceptions
runtime_error Thrown if algorithm or Child Algorithm cannot be initialised
Implements Mantid::API::IAlgorithm.
Definition at line 292 of file Algorithm.cpp.
References Mantid::Kernel::Logger::fatal(), g_log, getLogger(), init(), Mantid::API::Initialized, isInitialized(), name(), setExecutionState(), setLoggingOffset(), and Mantid::Kernel::Logger::setName().
Referenced by Mantid::DataHandling::LoadILLSANS::applySensitivityMap(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::MDAlgorithms::LoadGaussCube::exec(), and SANSInstrumentCreationHelper::runLoadInstrument().
interruption_point()
void Mantid::API::Algorithm::interruption_point () protected
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Definition at line 1698 of file Algorithm.cpp.
References IF_NOT_PARALLEL, and m_cancel.
Referenced by Mantid::Algorithms::DetectorDiagnostic::advanceProgress(), Mantid::Algorithms::GetEi::advanceProgress(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::Algorithms::SumEventsByLogValue::createTableOutput(), doCallProcessGroups(), Mantid::Algorithms::DetectorEfficiencyVariation::doDetectorTests(), Mantid::API::Progress::doReport(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::Algorithms::DetectorEfficiencyCor::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::He3TubeEfficiency::exec(), Mantid::Algorithms::IntegrateEPP::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::Pause::exec(), Mantid::Algorithms::Rebunch::exec(), Mantid::Algorithms::Regroup::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::GroupDetectors2::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::ICat::CatalogKeepAlive::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::Algorithms::He3TubeEfficiency::execEvent(), Mantid::DataHandling::GroupDetectors2::execEvent(), executeInternal(), Mantid::Algorithms::GetEi::extractSpec(), Mantid::DataHandling::GroupDetectors2::fileReadProg(), Mantid::DataHandling::GroupDetectors2::formGroups(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::DataHandling::LoadRaw3::includeMonitors(), Mantid::DataHandling::LoadRawHelper::loadSpectra(), Mantid::DataHandling::GroupDetectors2::moveOthers(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Algorithms::ConvertUnits::reverse(), and Mantid::DataHandling::LoadRaw3::separateMonitors().
isChild()
bool Mantid::API::Algorithm::isChild () const override virtual
To query whether algorithm is a child.
Returns
true - the algorithm is a child algorithm. False - this is a full managed algorithm.
Implements Mantid::API::IAlgorithm.
Definition at line 160 of file Algorithm.cpp.
References m_isChildAlgorithm.
Referenced by Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::Algorithms::Stitch1DMany::doStitch1D(), fillHistory(), Mantid::Algorithms::ConjoinXRuns::fillHistory(), fillHistory(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), lockWorkspaces(), logAlgorithmInfo(), Mantid::CurveFitting::Algorithms::Fit::readProperties(), registerFeatureUsage(), reportCompleted(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), setChild(), Mantid::Algorithms::PolarizationEfficienciesWildes::setOutputs(), trackingHistory(), and unlockWorkspaces().
isCompoundProperty()
bool Mantid::API::Algorithm::isCompoundProperty (const std::string & name) const private
Definition at line 1763 of file Algorithm.cpp.
References m_reservedList, and name().
Referenced by doSetInputProperties(), and getWorkspaceAndIndices().
isDefault()
bool Mantid::API::Algorithm::isDefault (const std::string & name) const
Parameters
name
Returns
True if the property is its default value.
Definition at line 1974 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::getPointerToProperty(), Mantid::Kernel::Property::isDefault(), m_properties, and name().
Referenced by Mantid::CurveFitting::IFittingAlgorithm::afterPropertySet(), Mantid::Algorithms::DirectILLTubeBackground::applyDiagnostics(), Mantid::Algorithms::Q1DWeighted::bootstrap(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::calculateOutputs(), Mantid::Algorithms::PolarizationEfficiencyCor::checkFredrikzeProperties(), Mantid::Algorithms::PolarizationEfficiencyCor::checkWildesProperties(), Mantid::Algorithms::PolarizationEfficiencyCor::checkWorkspaces(), Mantid::Algorithms::DirectILLTubeBackground::components(), Mantid::Algorithms::PDFFourierTransform2::convertFromSQMinus1(), Mantid::Algorithms::PDFFourierTransform2::convertToSQMinus1(), Mantid::DataHandling::GenerateGroupingPowder::createGroups(), Mantid::DataHandling::LoadEventNexus::createSpectraMapping(), Mantid::DataHandling::LoadILLReflectometry::detectorRotation(), Mantid::Algorithms::PDCalibration::detIdsForTable(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::ExtractSpectra::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskDetectorsIf::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::FlipperEfficiency::exec(), Mantid::Algorithms::PolarizationEfficienciesWildes::exec(), Mantid::Algorithms::Stitch::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Crystal::FilterPeaks::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::CurveFitting::Algorithms::SplineInterpolation::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::Algorithms::ExtractSpectra::execEvent(), Mantid::Algorithms::PolarizationEfficiencyCor::execFredrikze(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::Algorithms::PolarizationEfficiencyCor::execWildes(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::Algorithms::PolarizationEfficiencyCor::getEfficiencies(), Mantid::Algorithms::Stitch::getReferenceIndex(), Mantid::Algorithms::CalculatePlaczek::getSampleTemperature(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::getTimeDifference(), Mantid::Algorithms::PolarizationEfficiencyCor::getWorkspaceGroup(), Mantid::Algorithms::PolarizationEfficiencyCor::getWorkspaceNameList(), Mantid::Algorithms::CreateFloodWorkspace::integrate(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::Algorithms::HeliumAnalyserEfficiency::makeFit(), Mantid::DataHandling::LoadDiffCal::makeGroupingWorkspace(), Mantid::Algorithms::PDDetermineCharacterizations::overrideRunNumProperty(), Mantid::Algorithms::MultipleScatteringCorrection::parseInputs(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::Algorithms::EstimateResolutionDiffraction::processAlgProperties(), Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::retrieveBaseProperties(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::retrieveWorkspaceForWavelength(), Mantid::DataHandling::LoadDiffCal::runLoadCalFile(), Mantid::DataHandling::GenerateGroupingPowder::saveGroups(), Mantid::DataHandling::GenerateGroupingPowder2::saveGroups(), Mantid::Algorithms::CreateFloodWorkspace::scaleToCentralPixel(), Mantid::Algorithms::Stitch::scaleWithMedianRatios(), Mantid::Algorithms::CreateFloodWorkspace::shouldRemoveBackground(), Mantid::Algorithms::CalculateDIFC::validateInputs(), Mantid::Algorithms::CalculatePlaczek::validateInputs(), Mantid::Algorithms::ConvertDiffCal::validateInputs(), Mantid::Algorithms::CreateGroupingWorkspace::validateInputs(), Mantid::Algorithms::CrossCorrelate::validateInputs(), Mantid::Algorithms::DetermineSpinStateOrder::validateInputs(), Mantid::Algorithms::DiffractionFocussing2::validateInputs(), Mantid::Algorithms::DirectILLTubeBackground::validateInputs(), Mantid::Algorithms::EstimateResolutionDiffraction::validateInputs(), Mantid::Algorithms::ExtractSpectra::validateInputs(), Mantid::Algorithms::FilterByTime::validateInputs(), Mantid::Algorithms::FitPeaks::validateInputs(), Mantid::Algorithms::MaskDetectorsIf::validateInputs(), Mantid::Algorithms::DepolarizedAnalyserTransmission::validateInputs(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::validateInputs(), Mantid::Algorithms::PolarizationEfficienciesWildes::validateInputs(), Mantid::Algorithms::Rebin::validateInputs(), Mantid::Algorithms::Stitch::validateInputs(), Mantid::Algorithms::Stitch1DMany::validateInputs(), Mantid::Crystal::ConvertPeaksWorkspace::validateInputs(), Mantid::Crystal::SetGoniometer::validateInputs(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs(), Mantid::DataHandling::GenerateGroupingPowder::validateInputs(), Mantid::DataHandling::LoadEventNexus::validateInputs(), Mantid::DataHandling::LoadNGEM::validateMinMaxToF(), and Mantid::Algorithms::MergeLogs::validateTSP().
isEmpty()
template<typename NumT > static bool Mantid::API::Algorithm::isEmpty (const NumT toCheck) static protected
checks that the value was not set by users, uses the value in empty double/int.
Referenced by Mantid::Algorithms::CalculateEfficiency2::averageAndNormalizePixels(), Mantid::Algorithms::RemoveLowResTOF::calcTofMin(), Mantid::Algorithms::ExtractSpectra::checkProperties(), Mantid::CurveFitting::Algorithms::LeBailFit::createLeBailFunction(), Mantid::Algorithms::SumSpectra::determineIndices(), Mantid::Algorithms::PDFFourierTransform2::determineMaxIndex(), Mantid::Algorithms::PDFFourierTransform2::determineMinIndex(), Mantid::Algorithms::PDFFourierTransform::determineQmaxIndex(), Mantid::Algorithms::PDFFourierTransform::determineQminIndex(), Mantid::Algorithms::PDFFourierTransform::determineRho0(), Mantid::Algorithms::PDFFourierTransform2::determineRho0(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::AbsorptionCorrection::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::FilterByXValue::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::RemoveBins::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::DataHandling::CompressEvents::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::SaveNXSPE::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::WorkflowAlgorithms::StepScan::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::DataHandling::SetSampleMaterial::fixNeutron(), Mantid::Algorithms::RemovePromptPulse::getFrequency(), Mantid::Algorithms::CalculatePlaczekSelfScattering::getPackingFraction(), Mantid::Algorithms::RemovePromptPulse::getTofRange(), Mantid::Crystal::MaskPeaksWorkspace::getTofRange(), Mantid::Algorithms::EstimateResolutionDiffraction::getWavelength(), Mantid::Algorithms::SpectrumAlgorithm::getWorkspaceIndexSet(), Mantid::Algorithms::ExtractSpectra::getXMaxIndex(), Mantid::Algorithms::ExtractSpectra::getXMinIndex(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::DataHandling::LoadEventPreNexus2::openEventFile(), Mantid::Algorithms::FindPeaks::processAlgorithmProperties(), Mantid::Algorithms::FitPeaks::processInputPeakTolerance(), Mantid::Algorithms::FindPeakBackground::processInputProperties(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter(), Mantid::DataHandling::LoadEventPreNexus2::processInvestigationInputs(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::Crystal::FindSXPeaks::reducePeakList(), Mantid::Algorithms::AbsorptionCorrection::retrieveBaseProperties(), Mantid::Crystal::MaskPeaksWorkspace::retrieveProperties(), Mantid::Algorithms::CylinderAbsorption::retrieveProperties(), Mantid::DataHandling::LoadHFIRSANS::setDetectorDistance(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::Algorithms::NormaliseToMonitor::setIntegrationProps(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::Algorithms::FilterEvents::setupDirectTOFCorrection(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::DataHandling::LoadHFIRSANS::setWavelength(), Mantid::DataHandling::LoadSpice2D::setWavelength(), Mantid::Algorithms::CalculateEfficiency2::sumUnmaskedAndDeadPixels(), Mantid::Algorithms::ApplyTransmissionCorrection::validateInputs(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::validateInputs(), Mantid::Algorithms::ExtractSpectra::validateInputs(), Mantid::Algorithms::FilterByLogValue::validateInputs(), Mantid::Algorithms::FilterByXValue::validateInputs(), Mantid::Algorithms::FilterEvents::validateInputs(), Mantid::Algorithms::Integration::validateInputs(), Mantid::Algorithms::NormaliseToMonitor::validateInputs(), Mantid::Algorithms::PDFFourierTransform::validateInputs(), Mantid::Algorithms::PDFFourierTransform2::validateInputs(), Mantid::Algorithms::RemoveBins::validateInputs(), and Mantid::Crystal::FindSXPeaks::validateInputs().
isExecuted()
bool Mantid::API::Algorithm::isExecuted () const override virtual
Has the Algorithm already been executed successfully.
Implements Mantid::API::IAlgorithm.
Definition at line 151 of file Algorithm.cpp.
References executionState(), Mantid::API::Finished, resultState(), and Mantid::API::Success.
Referenced by doCallProcessGroups(), and executeInternal().
isInitialized()
bool Mantid::API::Algorithm::isInitialized () const override virtual
Has the Algorithm already been initialized.
Implements Mantid::API::IAlgorithm.
Definition at line 148 of file Algorithm.cpp.
References m_executionState, and Mantid::API::Uninitialized.
Referenced by executeInternal(), Mantid::API::MultiPeriodGroupWorker::findMultiPeriodGroups(), and initialize().
isLogging()
bool Mantid::API::Algorithm::isLogging () const override virtual
returns the status of logging, True = enabled
Implements Mantid::API::IAlgorithm.
Definition at line 1682 of file Algorithm.cpp.
References g_log, and Mantid::Kernel::Logger::getEnabled().
Referenced by Mantid::DataHandling::SaveMask::exec(), processGroups(), and Mantid::API::MultiPeriodGroupWorker::processGroups().
isReadyForGarbageCollection()
bool Mantid::API::Algorithm::isReadyForGarbageCollection () const override virtual
True if the algorithm is ready for garbage collection.
Implements Mantid::API::IAlgorithm.
Definition at line 208 of file Algorithm.cpp.
References executionState(), Mantid::API::Finished, and m_gcTime.
isRecordingHistoryForChild()
bool Mantid::API::Algorithm::isRecordingHistoryForChild () inline
Definition at line 225 of file Algorithm.h.
Referenced by Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::Algorithms::ConjoinXRuns::fillHistory(), and Mantid::DataHandling::SaveNexus::runSaveNexusProcessed().
isRunning()
bool Mantid::API::Algorithm::isRunning () const override virtual
True if the algorithm is running.
Implements Mantid::API::IAlgorithm.
Definition at line 205 of file Algorithm.cpp.
References executionState(), and Mantid::API::Running.
isWorkspaceProperty()
bool Mantid::API::Algorithm::isWorkspaceProperty (const Kernel::Property *const prop) const protected
checks the property is a workspace property
To query the property is a workspace property.
Parameters
prop :: pointer to input properties
Returns
true if this is a workspace property
Definition at line 1577 of file Algorithm.cpp.
linkHistoryWithLastChild()
void Mantid::API::Algorithm::linkHistoryWithLastChild () private
Link the name of the output workspaces on this parent algorithm.
with the last child algorithm executed to ensure they match in the history.
This solves the case where child algorithms use a temporary name and this name needs to match the output name of the parent algorithm so the history can be re-run.
Definition at line 1028 of file Algorithm.cpp.
References getProperties(), Mantid::API::IWorkspaceProperty::getWorkspace(), Mantid::Kernel::Direction::InOut, m_history, m_recordHistoryForChild, Mantid::Kernel::Direction::Output, and workspace.
Referenced by executeInternal().
lockWorkspaces()
void Mantid::API::Algorithm::lockWorkspaces () private
Go through the workspace properties of this algorithm and lock the workspaces for reading or writing.
Definition at line 433 of file Algorithm.cpp.
References Mantid::Kernel::Logger::debug(), g_log, isChild(), m_inputWorkspaceProps, m_outputWorkspaceProps, m_readLockedWorkspaces, and m_writeLockedWorkspaces.
Referenced by executeInternal().
logAlgorithmInfo()
void Mantid::API::Algorithm::logAlgorithmInfo () const private
Sends out algorithm parameter information to the logger.
Definition at line 1126 of file Algorithm.cpp.
References getLogger(), isChild(), m_isAlgStartupLoggingEnabled, name(), and Mantid::API::AlgorithmHistory::printSelf().
Referenced by executeInternal().
name()
const std::string Mantid::API::Algorithm::name () const override pure virtual
function to return a name of the algorithm, must be overridden in all algorithms
Implements Mantid::API::IAlgorithm.
Implemented in Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CuboidGaugeVolumeAbsorption, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSResolution, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, and Mantid::MDAlgorithms::ConvertToMDParent.
Referenced by addTimer(), Mantid::CurveFitting::IFittingAlgorithm::addWorkspace(), afterPropertySet(), createChildAlgorithm(), Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::MDAlgorithms::SlicingAlgorithm::createTransform(), Mantid::Algorithms::BinaryOperation::do2D(), doSetInputProperties(), Mantid::Algorithms::BinaryOperation::doSingleColumn(), Mantid::Algorithms::BinaryOperation::doSingleSpectrum(), Mantid::Algorithms::BinaryOperation::doSingleValue(), Mantid::Algorithms::BinaryOperation::exec(), Mantid::Algorithms::RebinByTimeBase::exec(), execute(), executeAsChildAlg(), executeInternal(), existsProperty(), Mantid::API::AlgorithmHistory::fillAlgorithmHistory(), Mantid::CurveFitting::IFittingAlgorithm::getCostFunctionNames(), getPointerToProperty(), getProperty(), getPropertyValue(), getWorkspaceAndIndices(), Mantid::Algorithms::BinaryOperation::handleSpecialDivideMinus(), initialize(), isCompoundProperty(), isDefault(), logAlgorithmInfo(), Mantid::MDAlgorithms::SlicingAlgorithm::makeAlignedDimensionFromString(), Mantid::MDAlgorithms::SlicingAlgorithm::makeBasisVectorFromString(), processGroups(), Mantid::API::MultiPeriodGroupWorker::processGroups(), registerFeatureUsage(), removeProperty(), reportCompleted(), setPropertyValue(), setPropertyValueFromJson(), setWorkspaceInputProperties(), setWorkspaceInputProperties(), and toJson().
notificationCenter()
Poco::NotificationCenter & Mantid::API::Algorithm::notificationCenter () const protected
Return a reference to the algorithm's notification dispatcher.
Returns
A reference to the Poco::NotificationCenter object that dispatches notifications
Definition at line 1632 of file Algorithm.cpp.
References m_notificationCenter.
Referenced by addObserver(), doCallProcessGroups(), executeInternal(), progress(), and removeObserver().
operator=()
Algorithm & Mantid::API::Algorithm::operator= (const Algorithm &) delete
processGroups()
bool Mantid::API::Algorithm::processGroups () virtual
Process WorkspaceGroup inputs.
This should be called after checkGroups(), which sets up required members. It goes through each member of the group(s), creates and sets an algorithm for each and executes them one by one.
If there are several group input workspaces, then the member of each group is executed pair-wise.
Returns
true - if all the workspace members are executed.
Reimplemented in Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::SassenaFFT, Mantid::API::MultiPeriodGroupAlgorithm, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXTomo, and Mantid::DataHandling::SaveReflectometryAscii.
Definition at line 1383 of file Algorithm.cpp.
References copyNonWorkspaceProperties(), createChildAlgorithm(), execute(), isLogging(), m_groupsHaveSimilarNames, m_groupSize, m_inputWorkspaceProps, m_pureOutputWorkspaceProps, m_singleGroup, m_unrolledInputWorkspaces, m_usingBaseProcessGroups, name(), Mantid::Kernel::IPropertyManager::setProperty(), setPropertyValue(), Mantid::Kernel::Strings::toString(), and version().
Referenced by doCallProcessGroups(), Mantid::Algorithms::ConjoinWorkspaces::processGroups(), and Mantid::API::MultiPeriodGroupAlgorithm::processGroups().
progress()
void Mantid::API::Algorithm::progress (double p, const std::string & msg = "", double estimatedTime = 0.0, int progressPrecision = 0) protected
Sends ProgressNotification.
Parameters
p :: Reported progress, must be between 0 (just started) and 1 (finished)
msg :: Optional message string
estimatedTime :: Optional estimated time to completion
progressPrecision :: optional, int number of digits after the decimal point to show.
Definition at line 240 of file Algorithm.cpp.
References notificationCenter().
Referenced by Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::addMDEvents(), Mantid::Algorithms::GetEi::advanceProgress(), Mantid::Algorithms::Q1DWeighted::calculate(), Mantid::Algorithms::CalculateEfficiency2::calculateEfficiency(), Mantid::DataHandling::LoadNGEM::createCountWorkspace(), Mantid::Algorithms::ConvertSpectrumAxis2::createElasticQMap(), Mantid::Algorithms::MaskDetectorsIf::createNewCalFile(), Mantid::Algorithms::ConvertSpectrumAxis2::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::Algorithms::CreateSampleWorkspace::createTestInstrumentRectangular(), Mantid::Algorithms::ConvertSpectrumAxis2::createThetaMap(), Mantid::DataHandling::LoadNexusProcessed::doAccelleratedMultiPeriodLoading(), Mantid::Algorithms::DetectorEfficiencyVariation::doDetectorTests(), Mantid::Algorithms::MedianDetectorTest::doDetectorTests(), Mantid::DataHandling::LoadFITS::doLoadFiles(), Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain(), Mantid::MDAlgorithms::MinusMD::doMinus(), Mantid::API::Progress::doReport(), Mantid::MDAlgorithms::SaveMD::doSaveEvents(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::Algorithms::AddLogDerivative::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::CalculateEfficiency2::exec(), Mantid::Algorithms::CalculatePolynomialBackground::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::CalculateZscore::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::CombineTableWorkspaces::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::ConvertSpectrumAxis2::exec(), Mantid::Algorithms::CreateBootstrapWorkspaces::exec(), Mantid::Algorithms::CreateCalFileByNames::exec(), Mantid::Algorithms::CreateDummyCalFile::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::CreateFloodWorkspace::exec(), Mantid::Algorithms::CreateMonteCarloWorkspace::exec(), Mantid::Algorithms::CreatePeaksWorkspace::exec(), Mantid::Algorithms::CreatePSDBleedMask::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DetectorEfficiencyCor::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::DirectILLTubeBackground::exec(), Mantid::Algorithms::EQSANSCorrectFrame::exec(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), Mantid::Algorithms::FilterEvents::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FindCenterOfMassPosition2::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::GeneralisedSecondDifference::exec(), Mantid::Algorithms::GenerateEventsFilter::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::HRPDSlabCanAbsorption::exec(), Mantid::Algorithms::IdentifyNoisyDetectors::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskBinsIf::exec(), Mantid::Algorithms::MaskDetectorsIf::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::NormaliseToUnity::exec(), Mantid::Algorithms::ParallaxCorrection::exec(), Mantid::Algorithms::Pause::exec(), Mantid::Algorithms::PolarizationEfficienciesWildes::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::ReadGroupsFromFile::exec(), Mantid::Algorithms::Rebunch::exec(), Mantid::Algorithms::Regroup::exec(), Mantid::Algorithms::Scale::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SphericalAbsorption::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumNeighbours::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Algorithms::Transpose::exec(), Mantid::Algorithms::UnaryOperation::exec(), Mantid::Algorithms::WienerSmooth::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::Crystal::FindClusterFaces::exec(), Mantid::Crystal::FindGoniometerAngles::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::CreateChunkingFromInstrument::exec(), Mantid::DataHandling::CreateSampleShape::exec(), Mantid::DataHandling::DefineGaugeVolume::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::GroupDetectors2::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadDiffCal::exec(), Mantid::DataHandling::LoadILLDiffraction::exec(), Mantid::DataHandling::LoadILLIndirect2::exec(), Mantid::DataHandling::LoadILLLagrange::exec(), Mantid::DataHandling::LoadILLPolarizedDiffraction::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadNGEM::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSPE::exec(), Mantid::DataHandling::LoadSpec::exec(), Mantid::DataHandling::MaskDetectors::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveDaveGrp::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveNISTDAT::exec(), Mantid::DataHandling::SaveNXSPE::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::ICat::CatalogLogin::exec(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::MDAlgorithms::QueryMDWorkspace::exec(), Mantid::MDAlgorithms::ReplicateMD::exec(), Mantid::MDAlgorithms::TransposeMD::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::Algorithms::FFTDerivative::execComplexFFT(), Mantid::CurveFitting::Algorithms::Fit::execConcrete(), Mantid::Algorithms::MaskBins::execEvent(), Mantid::DataHandling::GroupDetectors2::execEvent(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::execEvent(), Mantid::Algorithms::EQSANSTofStructure::execEvent(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), Mantid::Algorithms::GetEi::extractSpec(), Mantid::DataHandling::GroupDetectors2::fileReadProg(), Mantid::Algorithms::CreateMonteCarloWorkspace::fillHistogramWithRandomData(), Mantid::Algorithms::FilterEvents::filterEvents(), Mantid::MDAlgorithms::MergeMDFiles::finalizeOutput(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::Algorithms::SmoothNeighbours::findNeighboursUbiquitous(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::Algorithms::CalculateTransmission::fit(), Mantid::DataHandling::GroupDetectors2::formGroups(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::MDAlgorithms::SmoothMD::gaussianSmooth(), Mantid::DataHandling::ApplyDiffCal::getCalibrationWS(), Mantid::DataHandling::LoadDaveGrp::getData(), Mantid::Algorithms::DiffractionFocussing2::getGroupingWorkspace(), Mantid::Algorithms::IdentifyNoisyDetectors::getStdDev(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), handleChildProgressNotification(), Mantid::MDAlgorithms::SmoothMD::hatSmooth(), Mantid::Algorithms::FitOneSinglePeak::highBkgdFit(), Mantid::DataHandling::LoadRaw3::includeMonitors(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::MDAlgorithms::MergeMDFiles::loadBoxData(), Mantid::DataHandling::LoadILLReflectometry::loadData(), Mantid::DataHandling::LoadMLZ::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadSINQFocus::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadNexusProcessed::loadEventEntry(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadRawHelper::loadSpectra(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::Algorithms::AddLogDerivative::makeDerivative(), Mantid::Algorithms::GenerateEventsFilter::makeFilterBySingleValue(), Mantid::DataHandling::LoadDiffCal::makeGroupingWorkspace(), Mantid::DataHandling::LoadDiffCal::makeMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::DataHandling::GroupDetectors2::moveOthers(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::DataHandling::LoadDNSEvent::populate_EventWorkspace(), Mantid::DataHandling::SaveNXTomo::processAll(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Algorithms::CalculateEfficiency2::processGroups(), Mantid::Algorithms::MaskNonOverlappingBins::processNonRagged(), Mantid::Algorithms::MaskNonOverlappingBins::processRagged(), Mantid::DataHandling::LoadNGEM::readDataAsEvents(), Mantid::DataHandling::LoadNGEM::readDataAsHistograms(), Mantid::Algorithms::ReadGroupsFromFile::readGroupingFile(), Mantid::Algorithms::ReadGroupsFromFile::readXMLGroupingFile(), Mantid::Crystal::FindSXPeaks::reducePeakList(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::DataHandling::LoadNGEM::reportProgressAndCheckCancel(), Mantid::DataHandling::MaskDetectorsInShape::runFindDetectorsInShape(), Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadRawHelper::runLoadMappingTable(), Mantid::DataHandling::MaskDetectorsInShape::runMaskDetectors(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::Algorithms::Stitch::scaleManual(), Mantid::Algorithms::Stitch::scaleWithMedianRatios(), Mantid::DataHandling::LoadRaw3::separateMonitors(), Mantid::DataHandling::UpdateInstrumentFromFile::setDetectorPositions(), Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly(), Mantid::Algorithms::FitOneSinglePeak::simpleFit(), Mantid::Algorithms::CalculateEfficiency::sumUnmaskedDetectors(), Mantid::DataHandling::SaveAscii2::write1DHistoCut(), Mantid::DataHandling::SaveSPE::writeHists(), and Mantid::DataHandling::SaveAscii2::writeTableWorkspace().
progressObserver()
const Poco::AbstractObserver & Mantid::API::Algorithm::progressObserver () const protected
Return a reference to the algorithm's object that is reporting progress.
Returns
A Poco:NObserver object that is responsible for reporting progress
Definition at line 1650 of file Algorithm.cpp.
References handleChildProgressNotification(), and m_progressObserver.
Referenced by Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), setupAsChildAlgorithm(), and Mantid::DataHandling::Load::setUpLoader().
propertyCount()
size_t Mantid::API::Algorithm::propertyCount () const override virtual
Count the number of properties under management.
Returns
The number of properties being managed
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1909 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::propertyCount().
Referenced by Mantid::DataHandling::Load::init().
registerFeatureUsage()
void Mantid::API::Algorithm::registerFeatureUsage () const private
Registers the usage of the algorithm with the UsageService.
Definition at line 1745 of file Algorithm.cpp.
References isChild(), name(), and version().
Referenced by executeInternal().
removeObserver()
void Mantid::API::Algorithm::removeObserver (const Poco::AbstractObserver & observer) const override virtual
Remove an observer.
Parameters
observer :: Reference to the observer to remove
Implements Mantid::API::IAlgorithm.
Definition at line 227 of file Algorithm.cpp.
References notificationCenter().
removeProperty()
void Mantid::API::Algorithm::removeProperty (const std::string & name, const bool delproperty = true) override virtual
Removes the property from management.
Removes the property from properties map.
Parameters
name :: Name of the property to be removed.
delproperty :: if true, delete the named property
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1999 of file Algorithm.cpp.
References m_properties, name(), and Mantid::Kernel::PropertyManagerOwner::removeProperty().
Referenced by Mantid::DataHandling::Load::declareLoaderProperties(), Mantid::DataHandling::GenerateGroupingPowder2::init(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::init(), and Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initInstance().
reportCompleted()
void Mantid::API::Algorithm::reportCompleted (const double & duration, const bool groupProcessing = false) private
Report that the algorithm has completed.
Parameters
duration : Algorithm duration
groupProcessing : We have been processing via processGroups if true.
Definition at line 1715 of file Algorithm.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Finished, getLogger(), isChild(), m_alwaysStoreInADS, m_isAlgStartupLoggingEnabled, m_isChildAlgorithm, name(), Mantid::Kernel::Logger::notice(), and setExecutionState().
Referenced by doCallProcessGroups(), and executeInternal().
resetProperties()
void Mantid::API::Algorithm::resetProperties () override virtual
Reset property values back to initial values (blank or default values)
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1817 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::resetProperties().
resultState()
ResultState Mantid::API::Algorithm::resultState () const override virtual
Gets the current result State.
Implements Mantid::API::IAlgorithm.
Definition at line 135 of file Algorithm.cpp.
References m_resultState.
Referenced by isExecuted().
seeAlso()
const std::vector< std::string > Mantid::API::Algorithm::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, and Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection.
Definition at line 168 of file Algorithm.h.
setAlgStartupLogging()
void Mantid::API::Algorithm::setAlgStartupLogging (const bool enabled) override virtual
disable Logging of start and end messages
Enable or disable Logging of start and end messages.
Parameters
enabled : true to enable logging, false to disable
Implements Mantid::API::IAlgorithm.
Definition at line 1756 of file Algorithm.cpp.
References m_isAlgStartupLoggingEnabled.
setAlwaysStoreInADS()
void Mantid::API::Algorithm::setAlwaysStoreInADS (const bool doStore) override virtual
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
Parameters
doStore :: always store in ADS
Implements Mantid::API::IAlgorithm.
Definition at line 183 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::existsProperty(), Mantid::Kernel::PropertyManagerOwner::getPointerToProperty(), m_alwaysStoreInADS, m_properties, Mantid::API::PropertyMode::Optional, and Mantid::API::setPropertyModeForWorkspaceProperty().
Referenced by setChild().
setChild()
void Mantid::API::Algorithm::setChild (const bool isChild) override virtual
To set whether algorithm is a child.
Parameters
isChild :: True - the algorithm is a child algorithm. False - this is a full managed algorithm.
Implements Mantid::API::IAlgorithm.
Definition at line 166 of file Algorithm.cpp.
References isChild(), m_isChildAlgorithm, and setAlwaysStoreInADS().
Referenced by Mantid::Algorithms::FindPeaks::callFitPeak().
setChildEndProgress()
void Mantid::API::Algorithm::setChildEndProgress (const double endProgress) const inline override virtual
setting the child end progress
Implements Mantid::API::IAlgorithm.
Definition at line 256 of file Algorithm.h.
Referenced by Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), and Mantid::DataHandling::Load::setUpLoader().
setChildStartProgress()
void Mantid::API::Algorithm::setChildStartProgress (const double startProgress) const inline override virtual
setting the child start progress
Implements Mantid::API::IAlgorithm.
Definition at line 254 of file Algorithm.h.
Referenced by Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), and Mantid::DataHandling::Load::setUpLoader().
setExecutionState()
void Mantid::API::Algorithm::setExecutionState (const ExecutionState state) protected
Sets the current execution state.
Definition at line 132 of file Algorithm.cpp.
References m_executionState.
Referenced by executeInternal(), initialize(), reportCompleted(), and setResultState().
setLogging()
void Mantid::API::Algorithm::setLogging (const bool value) override virtual
Logging can be disabled by passing a value of false.
Implements Mantid::API::IAlgorithm.
Definition at line 1680 of file Algorithm.cpp.
References g_log, Mantid::Kernel::Logger::setEnabled(), and value.
setLoggingOffset()
void Mantid::API::Algorithm::setLoggingOffset (const int value) override virtual
gets the logging priority offset
Implements Mantid::API::IAlgorithm.
Definition at line 1689 of file Algorithm.cpp.
References g_log, Mantid::Kernel::Logger::setLevelOffset(), and value.
Referenced by initialize().
setOtherProperties()
void Mantid::API::Algorithm::setOtherProperties (IAlgorithm * alg, const std::string & propertyName, const std::string & propertyValue, int periodNum) protected virtual
Virtual method to set the non workspace properties for this algorithm.
To be overridden by specific algorithms when needed.
Parameters
alg :: pointer to the algorithm
propertyName :: name of the property
propertyValue :: value of the property
periodNum :: period number
Reimplemented in Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveNexus, and Mantid::DataHandling::SaveNexusProcessed.
Definition at line 1565 of file Algorithm.cpp.
References Mantid::Kernel::IPropertyManager::setPropertyValue().
Referenced by copyNonWorkspaceProperties(), Mantid::DataHandling::SaveCanSAS1D::setOtherProperties(), Mantid::DataHandling::SaveGSS::setOtherProperties(), Mantid::DataHandling::SaveFocusedXYE::setOtherProperties(), Mantid::DataHandling::SaveNexus::setOtherProperties(), and Mantid::DataHandling::SaveNexusProcessed::setOtherProperties().
setProperties() [1/2]
void Mantid::API::Algorithm::setProperties (const ::Json::Value & jsonValue, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>(), bool createMissing = false) override virtual
Sets all the declared properties from a json object.
Parameters
jsonValue :: A json name value pair collection
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1841 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::setProperties().
setProperties() [2/2]
void Mantid::API::Algorithm::setProperties (const std::string & propertiesJson, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>(), bool createMissing = false) override virtual
Set the ordered list of properties by one string of values, separated by semicolons.
The string should be a json formatted collection of name value pairs
Parameters
propertiesJson :: The string of property values
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Exceptions
invalid_argument if error in parameters
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1830 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::setProperties().
setPropertiesWithString()
void Mantid::API::Algorithm::setPropertiesWithString (const std::string & propertiesString, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set<std::string>()) override virtual
Sets all the declared properties from a string.
Parameters
propertiesString :: A list of name = value pairs separated by a semicolon
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1852 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::setPropertiesWithString().
setPropertyOrdinal()
void Mantid::API::Algorithm::setPropertyOrdinal (const int & index, const std::string & value) override virtual
Set the value of a property by an index N.B.
bool properties must be set using 1/0 rather than true/false
Parameters
index :: The index of the property to assign
value :: The value to assign to the property
Exceptions
std::runtime_error if the property index is too high
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1888 of file Algorithm.cpp.
References afterPropertySet(), Mantid::Kernel::PropertyManagerOwner::getPointerToPropertyOrdinal(), index, m_properties, Mantid::Kernel::Property::name(), Mantid::Kernel::PropertyManagerOwner::setPropertyOrdinal(), and value.
setPropertyValue()
void Mantid::API::Algorithm::setPropertyValue (const std::string & name, const std::string & value) override virtual
Set the value of a property by string N.B.
bool properties must be set using 1/0 rather than true/false
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError if the named property is unknown
std::invalid_argument If the value is not valid for the property given
Implements Mantid::Kernel::IPropertyManager.
Reimplemented in Mantid::DataHandling::Load.
Definition at line 1865 of file Algorithm.cpp.
References afterPropertySet(), m_properties, name(), Mantid::Kernel::PropertyManagerOwner::setPropertyValue(), and value.
Referenced by Mantid::DataHandling::LoadILLSANS::applySensitivityMap(), Mantid::Algorithms::DirectILLTubeBackground::components(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::CurveFitting::Algorithms::DoublePulseFit::declareAdditionalProperties(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::GenerateIPythonNotebook::exec(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::UpdateInstrumentFromFile::exec(), Mantid::MDAlgorithms::LoadGaussCube::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::execConcrete(), Mantid::Algorithms::Q1DWeighted::finalize(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), Mantid::Algorithms::Qhelper::outputParts(), processGroups(), Mantid::Algorithms::PolarizationEfficienciesWildes::resetPropertyValue(), SANSInstrumentCreationHelper::runLoadInstrument(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::DataHandling::Load::setPropertyValue(), Mantid::Algorithms::CreateDetectorTable::setTableToOutput(), Mantid::CurveFitting::Functions::ProcessBackground::setupDummyOutputWSes(), and Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace().
setPropertyValueFromJson()
void Mantid::API::Algorithm::setPropertyValueFromJson (const std::string & name, const Json::Value & value) override virtual
Set the value of a property by Json::Value object.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError if the named property is unknown
std::invalid_argument If the value is not valid for the property given
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1877 of file Algorithm.cpp.
References afterPropertySet(), m_properties, name(), Mantid::Kernel::PropertyManagerOwner::setPropertyValueFromJson(), and value.
setResultState()
void Mantid::API::Algorithm::setResultState (const ResultState state) protected
Sets the result execution state.
Sets the result execution state if set to Success or Failed will also set the execution state to finished.
Definition at line 139 of file Algorithm.cpp.
References Mantid::API::Finished, m_resultState, Mantid::API::NotFinished, and setExecutionState().
Referenced by doCallProcessGroups(), and executeInternal().
setRethrows()
void Mantid::API::Algorithm::setRethrows (const bool rethrow) override virtual
Set whether the algorithm will rethrow exceptions.
Parameters
rethrow :: true if you want to rethrow exception.
Implements Mantid::API::IAlgorithm.
Definition at line 202 of file Algorithm.cpp.
References m_rethrow.
setupAsChildAlgorithm()
void Mantid::API::Algorithm::setupAsChildAlgorithm (const Algorithm_sptr & alg, const double startProgress = -1., const double endProgress = -1., const bool enableLogging = true)
Setup algorithm as child algorithm.
Used internally by createChildAlgorithm. Arguments are as documented there. Can also be used manually for algorithms created otherwise. This allows running algorithms that are not declared into the factory as child algorithms.
Definition at line 873 of file Algorithm.cpp.
References m_ChildAlgorithms, m_endChildProgress, m_startChildProgress, Mantid::Kernel::Direction::Output, PARALLEL_CRITICAL, and progressObserver().
Referenced by createChildAlgorithm(), and Mantid::Algorithms::ExtractSpectra::exec().
setWorkspaceInputProperties() [1/2]
template<typename T1 , typename T2 , typename , typename > void Mantid::API::Algorithm::setWorkspaceInputProperties (const std::string & name, const std::shared_ptr< T1 > & wksp, IndexType type, const T2 & list)
Mechanism for setting the index property with a workspace shared pointer.
This method can only be used if T1 is convertible to a MatrixWorkspace and T2 is either std::string or std::vector<int>
Parameters
name Property name
wksp Workspace as a pointer
type Index type IndexType::WorkspaceIndex or IndexType::SpectrumNum
list List of indices to be used.
Definition at line 99 of file Algorithm.hxx.
References name().
setWorkspaceInputProperties() [2/2]
template<typename T1 , typename T2 , typename , typename > void Mantid::API::Algorithm::setWorkspaceInputProperties (const std::string & name, const std::string & wsName, IndexType type, const T2 & list)
Mechanism for setting the index property with a workspace shared pointer.
This method can only be used if T1 is convertible to a MatrixWorkspace and T2 is either std::string or std::vector<int64_t>
Parameters
name Property name
wsName Workspace name as string
type Index type IndexType::WorkspaceIndex or IndexType::SpectrumNum
list List of indices to be used.
Definition at line 114 of file Algorithm.hxx.
References name().
store()
void Mantid::API::Algorithm::store () protected
Stores any output workspaces into the AnalysisDataService.
Exceptions
std::runtime_error If unable to successfully store an output workspace
Definition at line 805 of file Algorithm.cpp.
References getProperties(), group, and Mantid::API::IWorkspaceProperty::store().
Referenced by doCallProcessGroups(), and executeInternal().
summary()
const std::string Mantid::API::Algorithm::summary () const override pure virtual
function returns a summary message that will be displayed in the default GUI, and in the help.
Implements Mantid::API::IAlgorithm.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CuboidGaugeVolumeAbsorption, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSResolution, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnaryOperation, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::WorkspaceJoiners, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, and Mantid::DataHandling::SetSample.
takeProperty()
std::unique_ptr< Kernel::Property > Mantid::API::Algorithm::takeProperty (const size_t index) override virtual
Removes the property from management and returns a pointer to it.
Removes a property from the properties map by index and return a pointer to it.
Parameters
index :: index of the property to be removed
Returns
:: pointer to the removed property if found, NULL otherwise
Implements Mantid::Kernel::IPropertyManager.
Definition at line 2008 of file Algorithm.cpp.
References index, m_properties, and Mantid::Kernel::PropertyManagerOwner::takeProperty().
toJson()
Json::Value Mantid::API::Algorithm::toJson () const override virtual
Serialize an object to a json object.
Serialize this object to a json object)
Returns
This object serialized as a json object
Implements Mantid::API::IAlgorithm.
Definition at line 929 of file Algorithm.cpp.
References Mantid::Kernel::PropertyManagerOwner::asJson(), m_properties, name(), and version().
Referenced by toString().
toString()
std::string Mantid::API::Algorithm::toString () const override virtual
Serialize an object to a string.
Serialize this object to a string.
The format is a json formatted string.
Returns
This object serialized as a string
Implements Mantid::API::IAlgorithm.
Definition at line 923 of file Algorithm.cpp.
References toJson().
Referenced by Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), and Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec().
trackAlgorithmHistory()
void Mantid::API::Algorithm::trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
Indicates that this algrithms history should be tracked regardless of if it is a child.
Parameters
parentHist :: the parent algorithm history object the history in.
Definition at line 1073 of file Algorithm.cpp.
References enableHistoryRecordingForChild(), and m_parentHistory.
trackingHistory()
bool Mantid::API::Algorithm::trackingHistory () protected
get whether we are tracking the history for this algorithm,
Check if we are tracking history for this algorithm.
Returns
if we are tracking the history of this algorithm
Definition at line 1081 of file Algorithm.cpp.
References isChild(), and m_recordHistoryForChild.
Referenced by cacheInputWorkspaceHistories(), doCallProcessGroups(), Mantid::DataHandling::SaveNexusProcessed::doExec(), executeInternal(), and Mantid::DataHandling::SaveNexus::runSaveNexusProcessed().
unlockWorkspaces()
void Mantid::API::Algorithm::unlockWorkspaces () private
Unlock any previously locked workspaces.
Definition at line 480 of file Algorithm.cpp.
References Mantid::Kernel::Logger::debug(), g_log, isChild(), m_readLockedWorkspaces, and m_writeLockedWorkspaces.
Referenced by executeInternal().
validateInputs()
std::map< std::string, std::string > Mantid::API::Algorithm::validateInputs (void) override virtual
Perform validation of ALL the input properties of the algorithm.
This is to be overridden by specific algorithms. It will be called in dialogs after parsing all inputs and setting the properties, but BEFORE executing.
Returns
a map where: Key = string name of the property; Value = string describing the problem with the property.
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::Crystal::AnvredCorrection, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::IndexPeaks, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SetGoniometer, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::QTransform, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::PythonInterface::RunPythonScript, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::MDAlgorithms::MDNorm, and Mantid::MDAlgorithms::RecalculateTrajectoriesExtents.
Definition at line 332 of file Algorithm.cpp.
Referenced by executeInternal().
validateProperties()
bool Mantid::API::Algorithm::validateProperties () const override virtual
Validates all the properties in the collection.
Returns
True if all properties have a valid value
Implements Mantid::Kernel::IPropertyManager.
Definition at line 1903 of file Algorithm.cpp.
References m_properties, and Mantid::Kernel::PropertyManagerOwner::validateProperties().
Referenced by executeInternal().
version()
int Mantid::API::Algorithm::version () const override pure virtual
function to return a version of the algorithm, must be overridden in all algorithms
Implements Mantid::API::IAlgorithm.
Implemented in Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XDataConverter, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GenerateGroupingPowder2, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNexusProcessed2, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace2, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, and Mantid::MDAlgorithms::ConvertToMDParent.
Referenced by createChildAlgorithm(), Mantid::API::NexusFileLoader::createChildAlgorithm(), Mantid::API::AlgorithmHistory::fillAlgorithmHistory(), processGroups(), Mantid::API::MultiPeriodGroupWorker::processGroups(), registerFeatureUsage(), and toJson().
workspaceMethodInputProperty()
const std::string Mantid::API::Algorithm::workspaceMethodInputProperty () const override virtual
Returns
The name of the property that the calling object will be passed to.
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::DataHandling::MaskDetectors.
Definition at line 281 of file Algorithm.cpp.
workspaceMethodName()
const std::string Mantid::API::Algorithm::workspaceMethodName () const override virtual
Returns
A string giving the method name that should be attached to a workspace
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::DataHandling::MaskDetectors.
Definition at line 264 of file Algorithm.cpp.
workspaceMethodOn()
const std::vector< std::string > Mantid::API::Algorithm::workspaceMethodOn () const override virtual
Returns
A list of workspace class names that should have the workspaceMethodName attached
Implements Mantid::API::IAlgorithm.
Definition at line 271 of file Algorithm.cpp.
References Mantid::Kernel::StringTokenizer::asVector(), Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY, Mantid::Kernel::StringTokenizer::TOK_TRIM, and workspaceMethodOnTypes().
workspaceMethodOnTypes()
virtual const std::string Mantid::API::Algorithm::workspaceMethodOnTypes () const inline protected virtual
Returns a semi-colon separated list of workspace types to attach this algorithm.
Reimplemented in Mantid::Algorithms::Rebin.
Definition at line 364 of file Algorithm.h.
Referenced by workspaceMethodOn().
Friends And Related Symbol Documentation
Progress
friend class Progress friend
Definition at line 375 of file Algorithm.h.
WorkspaceHistory
friend class WorkspaceHistory friend
Definition at line 408 of file Algorithm.h.
Member Data Documentation
calledByAlias
bool Mantid::API::Algorithm::calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Definition at line 172 of file Algorithm.h.
Referenced by executeInternal().
g_execCount
size_t Mantid::API::Algorithm::g_execCount = 0 static protected
Counter to keep track of algorithm execution order.
Initialize static algorithm counter.
Definition at line 410 of file Algorithm.h.
Referenced by doCallProcessGroups(), Mantid::DataHandling::SaveNexusProcessed::doExec(), executeInternal(), Mantid::API::WorkspaceHistory::parseAlgorithmHistory(), and Mantid::DataHandling::SaveNexus::runSaveNexusProcessed().
g_log
Kernel::Logger& Mantid::API::Algorithm::g_log protected
Definition at line 422 of file Algorithm.h.
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::acceptOrDeny(), Mantid::DataHandling::LoadILLTOF2::addAllNexusFieldsAsProperties(), Mantid::DataHandling::LoadILLTOF3::addAllNexusFieldsAsProperties(), Mantid::Algorithms::FindPeaks::addInfoRow(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::addMDEvents(), Mantid::Algorithms::FindPeaks::addNonFitRecord(), Mantid::CurveFitting::Algorithms::LeBailFit::addParameterToMCMinimize(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::addParameterToMCMinimize(), Mantid::MDAlgorithms::FindPeaksMD::addPeak(), Mantid::CurveFitting::Functions::ProcessBackground::addRegion(), Mantid::DataHandling::LoadHFIRSANS::addRunProperty(), Mantid::DataHandling::LoadHFIRSANS::addRunTimeSeriesProperty(), Mantid::Algorithms::AddSampleLog::addSingleValueProperty(), Mantid::Algorithms::AddSampleLog::addTimeSeriesProperty(), Mantid::Algorithms::GroupWorkspaces::addToGroup(), Mantid::Algorithms::ExtractMaskToTable::addToTableWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::addToWorkspaceLog(), Mantid::Crystal::SCDCalibratePanels2::adjustComponent(), Mantid::DataHandling::CreateSimulationWorkspace::adjustInstrument(), Mantid::Crystal::LoadIsawPeaks::appendFile(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::appendSampleLogs(), Mantid::DataHandling::MaskDetectors::appendToDetectorListFromComponentList(), Mantid::DataHandling::MaskDetectors::appendToIndexListFromMaskWS(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::applyCorrection(), Mantid::CurveFitting::Algorithms::LeBailFit::applyParameterValues(), Mantid::DataHandling::SaveGSS::areAllDetectorsValid(), Mantid::DataHandling::LoadPSIMuonBin::assignOutputWorkspaceParticulars(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::Algorithms::CalculateEfficiency2::averageAndNormalizePixels(), Mantid::DataHandling::LoadMask::bankToDetectors(), Mantid::DataHandling::LoadSpiceXML2DDet::binaryParseIntegers(), Mantid::MDAlgorithms::BinMD::binByIterating(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::CurveFitting::Algorithms::LeBailFit::bookKeepBestMCResult(), Mantid::Algorithms::Q1DWeighted::bootstrap(), Mantid::DataHandling::SaveGSASInstrumentFile::buildGSASTabulatedProfile(), Mantid::Algorithms::CalculateCountRate::buildVisWSNormalization(), Mantid::Algorithms::RadiusSum::cacheInputPropertyValues(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::cacheInstrumentGeometry(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::calcAveragePosition(), Mantid::Algorithms::EstimateResolutionDiffraction::calcCentreVelocity(), Mantid::MDAlgorithms::IntegratePeaksMD2::calcCovar(), Mantid::DataHandling::FindDetectorsPar::calcDetPar(), Mantid::Algorithms::FitOneSinglePeak::calChiSquareSD(), Mantid::Algorithms::RemoveLowResTOF::calcTofMin(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackground(), Mantid::CurveFitting::Algorithms::SplineBackground::calculateBinWeight(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::CurveFitting::Algorithms::LeBailFit::calculateDiffractionPattern(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Algorithms::ExportTimeSeriesLog::calculateFirstDerivative(), Mantid::Algorithms::MonitorEfficiencyCorUser::calculateFormulaValue(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::calculateFunctionError(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateFunctionStatistic(), Mantid::Algorithms::MultipleScatteringCorrection::calculateLS1s(), Mantid::Algorithms::DetectorDiagnostic::calculateMedian(), Mantid::Algorithms::GetEi2::calculatePeakWidthAtHalfHeight(), Mantid::Algorithms::PolarizationEfficienciesWildes::calculatePolarizerAndAnalyserEfficiencies(), Mantid::DataHandling::LoadILLDiffraction::calculateRelativeRotations(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSampleAndContainer(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSingleComponent(), Mantid::Algorithms::ModeratorTzeroLinear::calculateTfLi(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateThermalNeutronSpecial(), Mantid::Algorithms::ExportTimeSeriesLog::calculateTimeSeriesRangeByTime(), Mantid::DataHandling::LoadRawHelper::calculateWorkspacesizes(), Mantid::Algorithms::GetTimeSeriesLogInformation::calDistributions(), Mantid::DataHandling::SaveGSASInstrumentFile::calL2FromDtt1(), Mantid::Algorithms::FindPeaks::callFitPeak(), Mantid::DataHandling::LoadNexusMonitors2::canOpenAsNeXus(), Mantid::Algorithms::PointByPointVCorrection::check_masks(), Mantid::Algorithms::PointByPointVCorrection::check_validity(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::Algorithms::CompareWorkspaces::checkAxes(), Mantid::Algorithms::BinaryOperation::checkCompatibility(), Mantid::Algorithms::CompareWorkspaces::checkData(), Mantid::DataHandling::SaveReflectometryAscii::checkFile(), Mantid::DataHandling::SaveReflectometryAscii::checkGroups(), Mantid::Algorithms::Q1DWeighted::checkIfSuperposedWedges(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::checkInputMDDimension(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::checkInputMDDimension(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::checkInputMDDimensions(), Mantid::Algorithms::RingProfile::checkInputsForNumericWorkspace(), Mantid::Algorithms::RingProfile::checkInputsForSpectraWorkspace(), Mantid::Algorithms::CompareWorkspaces::checkInstrument(), Mantid::Algorithms::GetTimeSeriesLogInformation::checkLogBasicInforamtion(), Mantid::Algorithms::GetTimeSeriesLogInformation::checkLogValueChanging(), Mantid::DataHandling::LoadSESANS::checkMandatoryHeaders(), Mantid::Algorithms::CompareWorkspaces::checkMasking(), Mantid::DataHandling::LoadRawHelper::checkOptionalProperties(), Mantid::DataHandling::SaveVTK::checkOptionalProperties(), Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), Mantid::Algorithms::CopyInstrumentParameters::checkProperties(), Mantid::Algorithms::NormaliseToMonitor::checkProperties(), Mantid::Algorithms::CalculateFlatBackground::checkRange(), Mantid::Algorithms::CompareWorkspaces::checkRunProperties(), Mantid::DataHandling::LoadPDFgetNFile::checkSameSize(), Mantid::Algorithms::CompareWorkspaces::checkSample(), Mantid::Crystal::ClearUB::clearSingleExperimentInfo(), Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::Algorithms::CompareWorkspaces::compareEventsListInDetails(), Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::MDAlgorithms::CompareMDWorkspaces::compareMDEventWorkspaces(), Mantid::DataHandling::LoadMask::componentToDetectors(), Mantid::Algorithms::CreateMonteCarloWorkspace::computeNormalizedCDF(), Mantid::Algorithms::FindPeaks::computePhi(), Mantid::Algorithms::GetEiMonDet3::computeTOF(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructGaugeVolume(), Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructSample(), Mantid::DataHandling::LoadSESANS::consumeData(), Mantid::CurveFitting::Algorithms::SplineInterpolation::convertBinnedData(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::convertFromQSampleToHKL(), Mantid::Algorithms::PDFFourierTransform2::convertFromSQMinus1(), Mantid::Algorithms::FitPeaks::convertParametersNameToIndex(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertSpiceMatrixToMomentumMDEvents(), Mantid::DataHandling::SaveDetectorsGrouping::convertToDetectorsRanges(), Mantid::DataHandling::SaveGSASInstrumentFile::convertToGSAS(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::convertToMatrixWorkspace(), Mantid::Algorithms::DetectorDiagnostic::convertToRate(), Mantid::Algorithms::MaskBinsFromTable::convertToSpectraList(), Mantid::Algorithms::PDFFourierTransform2::convertToSQMinus1(), Mantid::Algorithms::DiffractionFocussing::convertUnitsToDSpacing(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::DataHandling::LoadTOFRawNexus::countPixels(), Mantid::MDAlgorithms::SlicingAlgorithm::createAlignedTransform(), Mantid::CurveFitting::Functions::ProcessBackground::createBackgroundFunction(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::createDataMDWorkspace(), Mantid::Algorithms::GeneratePeaks::createDataWorkspace(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::createExperimentMDWorkspace(), Mantid::Algorithms::FindPeaks::createFunctions(), Mantid::Algorithms::FitPeak::createFunctions(), Mantid::MDAlgorithms::SlicingAlgorithm::createGeneralTransform(), Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadGSS::createInstrumentGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::createMatrixWorkspace(), Mantid::Algorithms::MaskDetectorsIf::createNewCalFile(), Mantid::CurveFitting::Algorithms::LeBailFit::createOutputDataWorkspace(), Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace(), Mantid::Algorithms::GeneratePeaks::createOutputWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::MDAlgorithms::FindPeaksMD::createPeak(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createPeakworkspace(), Mantid::DataHandling::LoadSpiceAscii::createRunInfoWS(), Mantid::Algorithms::AnnularRingAbsorption::createSampleShapeXML(), Mantid::DataHandling::SaveCanSAS1D::createSASDetectorElement(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D::createSASRunElement(), Mantid::Algorithms::SumEventsByLogValue::createTableOutput(), Mantid::Algorithms::ConvertSpectrumAxis2::createThetaMap(), Mantid::Algorithms::PDCalibration::createTOFPeakCenterFitWindowWorkspaces(), Mantid::MDAlgorithms::SlicingAlgorithm::createTransform(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::createVirtualInstrument(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::cropWorkspace(), Mantid::Algorithms::ClearCache::deleteFiles(), Mantid::DataHandling::LoadSpice2D::detectorDistance(), Mantid::DataHandling::LoadILLReflectometry::detectorRotation(), Mantid::DataHandling::LoadSpice2D::detectorTranslation(), Mantid::DataHandling::SaveOpenGenieAscii::determineEnginXBankId(), Mantid::Algorithms::PDFFourierTransform2::determineMaxIndex(), Mantid::Algorithms::PDFFourierTransform2::determineMinIndex(), Mantid::Algorithms::PDFFourierTransform::determineQmaxIndex(), Mantid::Algorithms::PDFFourierTransform::determineQminIndex(), Mantid::Algorithms::CalculateCountRate::disableNormalization(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::ICat::CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(), Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::MDAlgorithms::MergeMDFiles::doExecByCloning(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakBackground(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSequential(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doFitFunction(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitGaussianPeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitMultiplePeaks(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitNPeaksSimple(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitPeak(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::DataHandling::LoadFITS::doLoadFiles(), Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::doParameterSpaceRandomWalk(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doSimulatedAnnealing(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::CompareWorkspaces::doTableComparison(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::Algorithms::FindPeakBackground::estimateBackground(), Mantid::Algorithms::EstimateResolutionDiffraction::estimateDetectorResolution(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::estimatePeakHeightsLeBail(), Mantid::Algorithms::FindPeaks::estimatePeakParameters(), Mantid::Algorithms::CreateSampleWorkspace::evalFunction(), Mantid::Algorithms::FilterEvents::examineEventWS(), Mantid::Algorithms::AbsorptionCorrection::exec(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), Mantid::Algorithms::AddLogDerivative::exec(), Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::Bin2DPowderDiffraction::exec(), Mantid::Algorithms::BinaryOperation::exec(), Mantid::Algorithms::CalculateDynamicRange::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::ConvertToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CopyInstrumentParameters::exec(), Mantid::Algorithms::CopySample::exec(), Mantid::Algorithms::CorelliCalibrationApply::exec(), Mantid::Algorithms::CorelliCalibrationDatabase::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CorrectToFile::exec(), Mantid::Algorithms::CreateCalFileByNames::exec(), Mantid::Algorithms::CreateDummyCalFile::exec(), Mantid::Algorithms::CreateEPP::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreateMonteCarloWorkspace::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DeleteLog::exec(), Mantid::Algorithms::DeleteWorkspaces::exec(), Mantid::Algorithms::DetectorDiagnostic::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::EQSANSCorrectFrame::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FilterByLogValue::exec(), Mantid::Algorithms::FilterEvents::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindPeaks::exec(), Mantid::Algorithms::FitPeak::exec(), Mantid::Algorithms::FixGSASInstrumentFile::exec(), Mantid::Algorithms::GeneralisedSecondDifference::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GenerateIPythonNotebook::exec(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::Algorithms::GetAllEi::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::GetEi::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::GetQsInQENSData::exec(), Mantid::Algorithms::GetTimeSeriesLogInformation::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::InvertMask::exec(), Mantid::Algorithms::IQTransform::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskDetectorsIf::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::ModeratorTzero::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::NormaliseByCurrent::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::ParallaxCorrection::exec(), Mantid::Algorithms::Pause::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDDetermineCharacterizations::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::PolarizationCorrectionFredrikze::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin2D::exec(), Mantid::Algorithms::RebinToWorkspace::exec(), Mantid::Algorithms::RemoveBackground::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::ResetNegatives::exec(), Mantid::Algorithms::RingProfile::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Algorithms::Segfault::exec(), Mantid::Algorithms::SetInstrumentParameter::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Algorithms::StripPeaks::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Algorithms::UnwrapMonitor::exec(), Mantid::Algorithms::UnwrapSNS::exec(), Mantid::Algorithms::UpdateScriptRepository::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::Crystal::AnvredCorrection::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::ConvertPeaksWorkspace::exec(), Mantid::Crystal::CountReflections::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::Crystal::FindClusterFaces::exec(), Mantid::Crystal::FindGoniometerAngles::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::Crystal::FindUBUsingFFT::exec(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::IndexPeaks::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::PredictSatellitePeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SelectCellOfType::exec(), Mantid::Crystal::SelectCellWithForm::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::Crystal::SetUB::exec(), Mantid::Crystal::ShowPeakHKLOffsets::exec(), Mantid::Crystal::ShowPossibleCells::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::exec(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), Mantid::CurveFitting::Algorithms::LeBailFit::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::exec(), Mantid::CurveFitting::Algorithms::SplineInterpolation::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::ApplyDiffCal::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DefineGaugeVolume::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadFile::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::LoadAscii::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadCSNSNexus::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadEmptyInstrument::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadIDFFromNexus::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadMask::exec(), Mantid::DataHandling::LoadMcStasNexus::exec(), Mantid::DataHandling::LoadNexus::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadParameterFile::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadPreNexusMonitors::exec(), Mantid::DataHandling::LoadRKH::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSESANS::exec(), Mantid::DataHandling::LoadSPE::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::MaskDetectors::exec(), Mantid::DataHandling::MaskDetectorsInShape::exec(), Mantid::DataHandling::MoveInstrumentComponent::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::RotateInstrumentComponent::exec(), Mantid::DataHandling::RotateSampleShape::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::DataHandling::SaveBankScatteringAngles::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveDaveGrp::exec(), Mantid::DataHandling::SaveDetectorsGrouping::exec(), Mantid::DataHandling::SaveDiffCal::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveFullprofResolution::exec(), Mantid::DataHandling::SaveGSASInstrumentFile::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SaveNexusGeometry::exec(), Mantid::DataHandling::SaveNISTDAT::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::SavePHX::exec(), Mantid::DataHandling::SaveRKH::exec(), Mantid::DataHandling::SaveSESANS::exec(), Mantid::DataHandling::SaveVTK::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::ICat::CatalogLogin::exec(), Mantid::ICat::CatalogPublish::exec(), Mantid::MDAlgorithms::BinaryOperationMD::exec(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::ChangeQConvention::exec(), Mantid::MDAlgorithms::CompareMDWorkspaces::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::ImportMDEventWorkspace::exec(), Mantid::MDAlgorithms::ImportMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MDNormDirectSC::exec(), Mantid::MDAlgorithms::MDNormSCD::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), Mantid::MDAlgorithms::SpectralMomentMD::exec(), Mantid::MDAlgorithms::ThresholdMD::exec(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::DataHandling::SaveFITS::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::Crystal::PredictSatellitePeaks::exec_peaks(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::execConcrete(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Algorithms::He3TubeEfficiency::execEvent(), Mantid::Algorithms::HyspecScharpfCorrection::execEvent(), Mantid::Algorithms::ModeratorTzeroLinear::execEvent(), Mantid::Algorithms::ScaleX::execEvent(), Mantid::Algorithms::UnaryOperation::execEvent(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::Algorithms::EQSANSTofStructure::execEvent(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::execFitParametersMC(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::execFitParametersNonMC(), Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::DataHandling::MaskDetectors::execPeaks(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), Mantid::Algorithms::SmoothNeighbours::execWorkspace2D(), Mantid::CurveFitting::Algorithms::LeBailFit::exportBraggPeakParameterToTable(), Mantid::Algorithms::GetTimeSeriesLogInformation::exportErrorLog(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exportEvents(), Mantid::Algorithms::ExportTimeSeriesLog::exportLog(), Mantid::Algorithms::NormaliseByCurrent::extractCharge(), Mantid::Algorithms::ExtractMaskToTable::extractMaskFromMatrixWorkspace(), Mantid::MDAlgorithms::SlicingAlgorithm::extractMDFrameForNonAxisAligned(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::extractSpectrum(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::extractValidSampleObject(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::fileCheck(), Mantid::DataHandling::MaskDetectors::fillIndexListFromSpectra(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspaceRaw(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingGenerator(), Mantid::DataHandling::LoadILLTOF2::fillStaticWorkspace(), Mantid::DataHandling::LoadILLTOF3::fillStaticWorkspace(), Mantid::Algorithms::FilterEvents::filterEvents(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), Mantid::MDAlgorithms::MergeMDFiles::finalizeOutput(), Mantid::Algorithms::FindPeakBackground::findBackground(), Mantid::Algorithms::GetAllEi::findBinRanges(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::Algorithms::GetEi::findHalfLoc(), Mantid::CurveFitting::Algorithms::SplineInterpolation::findInterpolationRange(), Mantid::Crystal::SCDCalibratePanels::findL1(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::Algorithms::GetAllEi::findMonitorPeak(), Mantid::Algorithms::SmoothNeighbours::findNeighboursRectangular(), Mantid::Algorithms::SmoothNeighbours::findNeighboursUbiquitous(), Mantid::Algorithms::FindPeaks::findPeakBackground(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::Algorithms::FindPeaks::findPeaksGivenStartingPoints(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::Algorithms::FindPeaks::findPeaksUsingMariscotti(), Mantid::DataHandling::LoadISISNexus2::findSpectraDetRangeInFile(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), Mantid::Algorithms::CalculateTransmission::fit(), Mantid::Algorithms::FitPeaks::fitBackground(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Algorithms::CalculateTransmission::fitData(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitFunction(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::fitFunction(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionMD(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionSD(), Mantid::Algorithms::FitPeaks::fitFunctionSD(), Mantid::Algorithms::FindEPP::fitGaussian(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitOverlappedPeaks(), Mantid::Algorithms::FindPeaks::fitPeakGivenFWHM(), Mantid::Algorithms::FindPeaks::fitPeakInWindow(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksRobust(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksWithGoodStartingValues(), Mantid::Algorithms::CalculateTransmission::fitPolynomial(), Mantid::Algorithms::FindPeaks::fitSinglePeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::Algorithms::FitPeaks::fitSpectrumPeaks(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::fitToData(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::Algorithms::IQTransform::general(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::DataHandling::LoadEventPreNexus2::generateEventDistribtionWorkspace(), Mantid::DataHandling::LoadDetectorsGroupingFile::generateNoInstrumentGroupWorkspace(), Mantid::DataHandling::SaveGSS::generateOutFileNames(), Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspace(), Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspaceParallel(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genOutputFittedPatternWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeakParametersWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeaksFromTable(), Mantid::DataHandling::LoadFullprofResolution::genTableWorkspace(), Mantid::DataHandling::LoadGSASInstrumentFile::genTableWorkspace(), Mantid::DataHandling::FindDetectorsPar::get_ASCII_header(), Mantid::DataHandling::FindDetectorsPar::get_my_line(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::getBanks(), Mantid::DataHandling::LoadSpice2D::getData(), Mantid::DataHandling::LoadILLSANS::getDataDimensions(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::DataHandling::LoadILLSANS::getDetectorPositionD33(), Mantid::DataHandling::SetScalingPSD::getDetPositionsFromRaw(), Mantid::Algorithms::GetEi2::getDistanceFromSource(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient2(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::Algorithms::ConvertSpectrumAxis2::getEfixed(), Mantid::Algorithms::CorrectKiKf::getEfixedFromParameterMap(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::getEi(), Mantid::Algorithms::Stitch1D::getEndOverlap(), Mantid::DataHandling::PDLoadCharacterizations::getFilenames(), Mantid::DataHandling::DownloadInstrument::getFileShas(), Mantid::DataHandling::DetermineChunking::getFileType(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient2(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::getGaugeVolumeObject(), Mantid::MDAlgorithms::SlicingAlgorithm::getGeneralImplicitFunction(), Mantid::Algorithms::GetEi::getGeometry(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::DataHandling::LoadSpiceXML2DDet::getHB3AWavelength(), Mantid::Algorithms::SumOverlappingTubes::getHeightAxis(), Mantid::Algorithms::FindPeaks::getIndex(), Mantid::Algorithms::PDDetermineCharacterizations::getInformationFromTable(), Mantid::Algorithms::SumOverlappingTubes::getInputParameters(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::DataHandling::LoadDiffCal::getInstrument(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentDoubleParameter(), Mantid::DataHandling::SNSAppendGeometryToNexus::getInstrumentName(), Mantid::Algorithms::ConvertToConstantL2::getInstrumentProperty(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentStringParameter(), getLogger(), getLoggingOffset(), Mantid::Algorithms::PDDetermineCharacterizations::getLogValue(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getMeasureTime(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getMonitorCounts(), Mantid::DataHandling::LoadRawHelper::getmonitorSpectrumList(), Mantid::Algorithms::GetEi::getMonitorWsIndexs(), Mantid::DataHandling::Load::getOutputWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::getParameter(), Mantid::Algorithms::GetEi::getPeakEstimates(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getPeakInformation(), Mantid::Crystal::SortHKL::getPointgroup(), Mantid::DataHandling::SaveGSASInstrumentFile::getProfileParameterValue(), Mantid::Algorithms::Qxy::getQminFromWs(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getSampleLogValues(), Mantid::Algorithms::SumOverlappingTubes::getScatteringAngleBinning(), Mantid::DataHandling::LoadHFIRSANS::getSourceToSampleDistance(), Mantid::Algorithms::GeneratePeaks::getSpectraSet(), Mantid::Algorithms::Stitch1D::getStartOverlap(), Mantid::Algorithms::Q1DWeighted::getTableShapes(), Mantid::DataHandling::LoadRawHelper::getTimeChannels(), Mantid::Algorithms::RemoveLowResTOF::getTminData(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset(), Mantid::Algorithms::EQSANSTofStructure::getTofOffset(), Mantid::Algorithms::UnwrapSNS::getTofRangeData(), Mantid::Algorithms::MonitorEfficiencyCorUser::getValFromInstrumentDef(), Mantid::DataHandling::SaveGSASInstrumentFile::getValueFromMap(), Mantid::Algorithms::Q1DWeighted::getViewportParams(), Mantid::DataHandling::SaveNexusProcessed::getWSIndexList(), Mantid::DataHandling::LoadILLReflectometry::getXValues(), Mantid::Algorithms::CreateCalFileByNames::groupingFileDoesExist(), Mantid::Algorithms::CreateDummyCalFile::groupingFileDoesExist(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::Algorithms::UnwrapMonitor::handleFrameOverlapped(), Mantid::DataHandling::MaskDetectors::handleMaskByMaskWorkspace(), Mantid::DataHandling::MaskDetectors::handleMaskByMatrixWorkspace(), Mantid::DataHandling::LoadFITS::headerSanityCheck(), Mantid::Algorithms::FitOneSinglePeak::highBkgdFit(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::importInstrumentParameterFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::importMonteCarloParametersFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::importParametersFromTable(), Mantid::Algorithms::GeneratePeaks::importPeaksFromTable(), Mantid::Algorithms::GeneratePeaks::init(), initialize(), Mantid::DataHandling::LoadMask::initializeXMLParser(), Mantid::DataHandling::LoadMLZ::initInstrumentSpecific(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::DataHandling::LoadILLReflectometry::initNames(), Mantid::DataHandling::LoadILLTOF2::initWorkspace(), Mantid::DataHandling::LoadSINQFocus::initWorkSpace(), Mantid::DataHandling::LoadILLTOF3::initWorkspace(), Mantid::DataHandling::LoadMLZ::initWorkspace(), Mantid::DataHandling::LoadILLReflectometry::initWorkspace(), Mantid::DataHandling::LoadILLSANS::initWorkSpace(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD11B(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD22B(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD33(), Mantid::Algorithms::ConvertToConstantL2::initWorkspaces(), Mantid::Algorithms::RadiusSum::inputValidationSanityCheck(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Algorithms::DetectorDiagnostic::integrateSpectra(), Mantid::Algorithms::FindDeadDetectors::integrateWorkspace(), Mantid::Algorithms::SumRowColumn::integrateWorkspace(), Mantid::Algorithms::CreateMonteCarloWorkspace::integrateYData(), Mantid::Algorithms::Stitch1D::integration(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::intensity(), Mantid::DataHandling::LoadMask::intializeMaskWorkspace(), Mantid::Crystal::IntegratePeakTimeSlices::isGoodFit(), Mantid::DataHandling::LoadFITS::isInstrOtherThanIMAT(), isLogging(), Mantid::Algorithms::CalculateFlatBackground::LinearFit(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::linearInterpolation(), Mantid::DataHandling::FindDetectorsPar::load_plain(), Mantid::DataHandling::LoadTOFRawNexus::loadBank(), Mantid::MDAlgorithms::MergeMDFiles::loadBoxData(), Mantid::DataHandling::LoadSwans::loadData(), Mantid::DataHandling::LoadILLIndirect2::loadDataDetails(), Mantid::DataHandling::LoadILLSANS::loadDataFromMonitors(), Mantid::DataHandling::LoadMLZ::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadSINQFocus::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::LoadBBY::loadEvents(), Mantid::DataHandling::LoadFullprofResolution::loadFile(), Mantid::DataHandling::LoadGSASInstrumentFile::loadFile(), Mantid::DataHandling::LoadSassena::loadFQ(), Mantid::DataHandling::LoadSassena::loadFQT(), Mantid::DataHandling::SaveGSASInstrumentFile::loadFullprofResolutionFile(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::DataHandling::LoadFITS::loadHeader(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::Algorithms::VesuvioL1ThetaResolution::loadInstrument(), Mantid::DataHandling::LoadSwans::loadInstrument(), Mantid::DataHandling::LoadSpiceXML2DDet::loadInstrument(), Mantid::DataHandling::LoadILLTOF2::loadInstrumentDetails(), Mantid::DataHandling::LoadILLTOF3::loadInstrumentDetails(), Mantid::DataHandling::LoadMLZ::loadInstrumentDetails(), Mantid::DataHandling::LoadBBY::loadInstrumentParameters(), Mantid::DataHandling::LoadISISNexus2::loadLogs(), Mantid::DataHandling::LoadILLDiffraction::loadMetaData(), Mantid::DataHandling::LoadILLLagrange::loadMetaData(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadMetaData(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::DataHandling::LoadILLSANS::loadMetaData(), Mantid::DataHandling::LoadILLIndirect2::loadNexusEntriesIntoProperties(), Mantid::Algorithms::CorelliCalibrationDatabase::loadNonCalibratedComponentDatabase(), Mantid::DataHandling::LoadIDFFromNexus::loadParameterFile(), Mantid::DataHandling::LoadIDFFromNexus::LoadParameters(), Mantid::DataHandling::FindDetectorsPar::loadParFile(), Mantid::DataHandling::LoadISISNexus2::loadPeriodData(), Mantid::DataHandling::LoadEventPreNexus2::loadPixelMap(), Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::DataHandling::LoadMLZ::loadRunDetails(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::loadRunToMatrixWS(), Mantid::DataHandling::LoadISISNexus2::loadSampleData(), Mantid::DataHandling::Load::loadSingleFile(), Mantid::DataHandling::LoadNGEM::loadSingleFile(), Mantid::DataHandling::LoadLog::LoadSNSText(), Mantid::DataHandling::LoadLog::loadThreeColumnLogFile(), Mantid::DataHandling::LoadILLTOF2::loadTimeDetails(), Mantid::DataHandling::LoadILLTOF3::loadTimeDetails(), Mantid::DataHandling::LoadMLZ::loadTimeDetails(), lockWorkspaces(), Mantid::Algorithms::He3TubeEfficiency::logErrors(), Mantid::Algorithms::DetectorEfficiencyCor::logErrors(), Mantid::Algorithms::CreateLogTimeCorrection::logGeometryInformation(), Mantid::Algorithms::CalculateTransmission::logIfNotMonitor(), Mantid::Crystal::FindUBUsingIndexedPeaks::logLattice(), Mantid::DataHandling::SaveSPE::logMissingMasked(), Mantid::Algorithms::FitPeaks::logNoOffset(), Mantid::Crystal::PredictPeaks::logNumberOfPeaksFound(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make1DWorkspace(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeFilterBySingleValue(), Mantid::DataHandling::LoadDiffCal::makeGroupingWorkspace(), Mantid::Algorithms::DetectorDiagnostic::makeMap(), Mantid::Algorithms::IntegrateByComponent::makeMap(), Mantid::DataHandling::LoadDiffCal::makeMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog(), Mantid::Crystal::ConvertPeaksWorkspace::makePeaksWorkspace(), Mantid::DataHandling::LoadFITS::mapHeaderKeys(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::Algorithms::CalculateEfficiency::maskComponent(), Mantid::DataHandling::LoadMLZ::maskDetectors(), Mantid::WorkflowAlgorithms::SANSBeamFinder::maskEdges(), Mantid::Algorithms::CalculateEfficiency::maskEdges(), Mantid::DataHandling::LoadILLIndirect2::moveComponent(), Mantid::DataHandling::LoadHFIRSANS::moveDetector(), Mantid::DataHandling::LoadILLSANS::moveDetectorDistance(), Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal(), Mantid::DataHandling::LoadILLSANS::moveDetectorVertical(), Mantid::DataHandling::GroupDetectors2::moveOthers(), Mantid::DataHandling::SetScalingPSD::movePos(), Mantid::DataHandling::LoadILLIndirect2::moveSingleDetectors(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter(), Mantid::DataHandling::LoadILLDiffraction::moveTwoThetaZero(), Mantid::Algorithms::NormaliseToMonitor::normaliseBinByBin(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::Algorithms::RadiusSum::normalizeOutputByRadius(), Mantid::Algorithms::Bin2DPowderDiffraction::normalizeToBinArea(), Mantid::Algorithms::RadiusSum::numBinsIsReasonable(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::observePeakRange(), Mantid::DataHandling::LoadEventPreNexus2::openEventFile(), Mantid::DataHandling::SaveOpenGenieAscii::openFileStream(), Mantid::DataHandling::SaveCanSAS1D::openForAppending(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::Crystal::SCDCalibratePanels2::optimizeL1(), Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos(), Mantid::Crystal::SCDCalibratePanels2::optimizeT0(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::outputAxisProfiles(), Mantid::Algorithms::FindPeaksConvolve::outputResults(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::pairBraggSatellitePeaks(), Mantid::DataHandling::LoadDNSEvent::parse_andAddEvent(), Mantid::DataHandling::LoadDNSEvent::parse_File(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBackgroundTableWorkspace(), Mantid::DataHandling::LoadGSASInstrumentFile::parseBank(), Mantid::DataHandling::LoadFullprofResolution::parseBankLine(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBraggPeaksParametersTable(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseBraggPeakTable(), Mantid::DataHandling::LoadPDFgetNFile::parseColumnNameLine(), Mantid::DataHandling::LoadPDFgetNFile::parseDataFile(), Mantid::DataHandling::LoadPDFgetNFile::parseDataLine(), Mantid::DataHandling::LoadSpice2D::parseDetectorDimensions(), Mantid::DataHandling::LoadHFIRSANS::parseDetectorDimensions(), Mantid::DataHandling::LoadFullprofResolution::parseDoubleValue(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseFitParameterWorkspace(), Mantid::Algorithms::MultipleScatteringCorrection::parseInputs(), Mantid::CurveFitting::Algorithms::LeBailFit::parseInstrumentParametersTable(), Mantid::Algorithms::ExtractMaskToTable::parseMaskTable(), Mantid::DataHandling::SaveGDA::parseParamsFile(), Mantid::DataHandling::SaveGSASInstrumentFile::parseProfileTableWorkspace(), Mantid::DataHandling::LoadFullprofResolution::parseResolutionStrings(), Mantid::DataHandling::LoadPreNexus::parseRuninfo(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::parseSampleLogs(), Mantid::DataHandling::LoadSpiceAscii::parseSPICEAscii(), Mantid::Algorithms::ExtractMaskToTable::parseStringToVector(), Mantid::DataHandling::SaveFullprofResolution::parseTableWorkspace(), Mantid::DataHandling::LoadMask::parseXML(), Mantid::Algorithms::GetAllEi::peakGuess(), Mantid::Algorithms::FindPeaksConvolve::performConvolution(), Mantid::Algorithms::ParallaxCorrection::performCorrection(), Mantid::DataHandling::LoadILLSANS::placeD16(), Mantid::DataHandling::LoadSwans::placeDetectorInSpace(), Mantid::DataHandling::LoadDNSEvent::populate_EventWorkspace(), Mantid::Algorithms::CreateDetectorTable::populateTable(), Mantid::Crystal::IntegratePeakTimeSlices::PreFit(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors(), Mantid::Algorithms::GetAllEi::printDebugModeInfo(), Mantid::DataHandling::SaveDetectorsGrouping::printToXML(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::Algorithms::FindPeaks::processAlgorithmProperties(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::processDetectorsPositions(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::Algorithms::SassenaFFT::processGroups(), Mantid::DataHandling::SaveNexusESS::processGroups(), Mantid::DataHandling::SaveNexusProcessed::processGroups(), Mantid::DataHandling::LoadAscii2::processHeader(), Mantid::DataHandling::LoadAscii::processHeader(), Mantid::DataHandling::LoadEventPreNexus2::processImbedLogs(), Mantid::Algorithms::GenerateEventsFilter::processInOutWorkspaces(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputBackground(), Mantid::Algorithms::FitPeaks::processInputFunctions(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::Algorithms::FitPeaks::processInputPeakTolerance(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::processInputProperties(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputProperties(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::DataHandling::LoadSpiceXML2DDet::processInputs(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::GenerateEventsFilter::processInputTime(), Mantid::Algorithms::RadiusSum::processInstrumentRadiusSum(), Mantid::Algorithms::RingProfile::processInstrumentRingProfile(), Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter(), Mantid::Algorithms::MaskBinsFromTable::processMaskBinWorkspace(), Mantid::DataHandling::LoadMask::processMaskOnDetectors(), Mantid::DataHandling::LoadMask::processMaskOnWorkspaceIndex(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters(), Mantid::Algorithms::RadiusSum::processNumericImageRadiusSum(), Mantid::Algorithms::FitPeaks::processOutputs(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::DataHandling::SaveFullprofResolution::processProperties(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::DataHandling::SetScalingPSD::processScalingFile(), Mantid::Algorithms::FitPeaks::processSinglePeakFitResult(), Mantid::Algorithms::GeneratePeaks::processTableColumnNames(), Mantid::Algorithms::GetTimeSeriesLogInformation::processTimeRange(), Mantid::DataHandling::GroupDetectors2::processXMLFile(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear(), Mantid::Crystal::SCDCalibratePanels2::profileBanks(), Mantid::Crystal::SCDCalibratePanels2::profileL1(), Mantid::Crystal::SCDCalibratePanels2::profileL1T0(), Mantid::Crystal::SCDCalibratePanels2::profileT0(), Mantid::CurveFitting::Algorithms::LeBailFit::proposeNewBackgroundValues(), Mantid::CurveFitting::Algorithms::LeBailFit::proposeNewValues(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::proposeNewValues(), Mantid::ICat::CatalogPublish::publish(), Mantid::Algorithms::Integration::rangeFilterEventWorkspace(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::rasterizeGaugeVolumeAndCalculateMeanElementPosition(), Mantid::DataHandling::LoadRKH::read1D(), Mantid::DataHandling::LoadRKH::read2D(), Mantid::MDAlgorithms::LoadDNSSCD::read_data(), Mantid::Algorithms::Bin2DPowderDiffraction::ReadBinsFromFile(), Mantid::DataHandling::PDLoadCharacterizations::readCharInfo(), Mantid::WorkflowAlgorithms::EQSANSLoad::readConfigFile(), Mantid::DataHandling::LoadHFIRSANS::readData(), Mantid::DataHandling::LoadAscii::readData(), Mantid::DataHandling::LoadNexusMonitors2::readEventMonitorEntry(), Mantid::MDAlgorithms::LoadSQW::readEvents(), Mantid::MDAlgorithms::FindPeaksMD::readExperimentInfo(), Mantid::DataHandling::PDLoadCharacterizations::readExpIni(), Mantid::Algorithms::ReadGroupsFromFile::readGroupingFile(), Mantid::Algorithms::DiffractionFocussing::readGroupingFile(), Mantid::Crystal::LoadIsawPeaks::readHeader(), Mantid::DataHandling::GroupDetectors2::readInt(), Mantid::DataHandling::LoadPSIMuonBin::readInTemperatureFile(), Mantid::DataHandling::LoadDetectorInfo::readLibisisNxs(), Mantid::MDAlgorithms::LoadSQW2::readMainHeader(), Mantid::DataHandling::LoadIDFFromNexus::readParameterCorrectionFile(), Mantid::MDAlgorithms::LoadSQW2::readPixelDataIntoWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::readPulseidFile(), Mantid::MDAlgorithms::LoadSQW2::readSingleSPEHeader(), Mantid::DataHandling::GroupDetectors2::readSpectraIndexes(), Mantid::MDAlgorithms::LoadSQW2::readSQWDimensions(), Mantid::DataHandling::LoadAscii2::readTable(), Mantid::DataHandling::LoadRawHelper::readTitle(), Mantid::DataHandling::PDLoadCharacterizations::readVersion0(), Mantid::DataHandling::PDLoadCharacterizations::readVersion1(), Mantid::Algorithms::PDCalibration::rebin(), Mantid::Algorithms::UnwrapMonitor::rebin(), Mantid::Algorithms::Regroup::rebin(), Mantid::Algorithms::Stitch1D::rebin(), Mantid::Algorithms::DiffractionFocussing::RebinWorkspace(), Mantid::Crystal::FindSXPeaks::reducePeakList(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::reducePowderData(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::refineInstrumentParametersMC(), Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::DataHandling::DownloadInstrument::removeOrphanedFiles(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::Algorithms::ConvertUnits::removeUnphysicalBins(), Mantid::DataHandling::LoadSPE::reportFormatError(), Mantid::DataHandling::LoadILLDiffraction::resolveInstrument(), Mantid::Crystal::AnvredCorrection::retrieveBaseProperties(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveFormula(), Mantid::Algorithms::DetectorEfficiencyCor::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveProperties(), Mantid::DataHandling::LoadHFIRSANS::rotateDetector(), Mantid::DataHandling::LoadSpice2D::rotateDetector(), Mantid::DataHandling::LoadILLSANS::rotateInstrument(), Mantid::DataHandling::LoadILLIndirect2::rotateTubes(), Mantid::Algorithms::AnnularRingAbsorption::runCreateSampleShape(), Mantid::DataHandling::MaskDetectorsInShape::runFindDetectorsInShape(), Mantid::DataHandling::LoadHFIRSANS::runLoadInstrument(), Mantid::DataHandling::LoadMLZ::runLoadInstrument(), Mantid::DataHandling::LoadSINQFocus::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadCanSAS1D::runLoadInstrument(), Mantid::DataHandling::LoadSpice2D::runLoadInstrument(), Mantid::DataHandling::LoadPreNexusMonitors::runLoadInstrument(), Mantid::DataHandling::LoadISISNexus2::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrumentFromRaw(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadNexusMonitors2::runLoadLogs(), Mantid::DataHandling::LoadRawHelper::runLoadMappingTable(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadNexus::runLoadNexusProcessed(), Mantid::DataHandling::LoadInstrument::runLoadParameterFile(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::CurveFitting::Algorithms::Fit::runMinimizer(), Mantid::Algorithms::AnnularRingAbsorption::runMonteCarloAbsorptionCorrection(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::Algorithms::AnnularRingAbsorption::runSetSampleMaterial(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::DataHandling::SaveAscii2::sampleLogValueUnit(), Mantid::DataHandling::GenerateGroupingPowder::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder::saveAsXML(), Mantid::DataHandling::SaveCalFile::saveCalFile(), Mantid::Algorithms::CreateCalFileByNames::saveGroupingFile(), Mantid::Algorithms::CreateDummyCalFile::saveGroupingFile(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveIsawDetCal(), Mantid::DataHandling::SaveNexusESS::saveNexusGeometry(), Mantid::DataHandling::SaveNexusProcessed::saveSpectraDetectorMapNexus(), Mantid::Crystal::SCDCalibratePanels::saveXmlFile(), Mantid::Crystal::SCDCalibratePanels2::saveXmlFile(), Mantid::Algorithms::CreateFloodWorkspace::scaleToCentralPixel(), Mantid::Algorithms::Stitch1D::scaleWorkspace(), Mantid::DataHandling::LoadFullprofResolution::scanBanks(), Mantid::PythonInterface::RunPythonScript::scriptCode(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::DataHandling::LoadHFIRSANS::setBeamDiameter(), Mantid::DataHandling::LoadHFIRSANS::setBeamTrapRunProperty(), Mantid::DataHandling::LoadSpice2D::setBeamTrapRunProperty(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByComponents(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByDetectors(), Mantid::DataHandling::LoadDetectorsGroupingFile::setBySpectrumNos(), Mantid::DataHandling::LoadHFIRSANS::setDetectorDistance(), Mantid::DataHandling::UpdateInstrumentFromFile::setDetectorPositions(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly(), Mantid::Algorithms::GetAllEi::setFilterLog(), Mantid::DataHandling::LoadILLSANS::setFinalProperties(), Mantid::Algorithms::FitOneSinglePeak::setFitPeakCriteria(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterFitSetups(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterValues(), Mantid::DataHandling::LoadSpice2D::setInputPropertiesAsMemberProperties(), Mantid::DataHandling::LoadILLSANS::setInstrumentName(), Mantid::DataHandling::LoadILLIndirect2::setInstrumentName(), Mantid::Algorithms::NormaliseToMonitor::setIntegrationProps(), setLogging(), setLoggingOffset(), Mantid::DataHandling::LoadSpice2D::setMetadataAsRunProperties(), Mantid::Algorithms::CalculateCountRate::setOutLogParameters(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::DataHandling::LoadEventPreNexus2::setProtonCharge(), Mantid::DataHandling::LoadHFIRSANS::setSansSpiceXmlFormatVersion(), Mantid::DataHandling::LoadSpice2D::setSansSpiceXmlFormatVersion(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), Mantid::DataHandling::DetermineChunking::setTopEntryName(), Mantid::DataHandling::LoadPDFgetNFile::setUnit(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::MDAlgorithms::LoadSQW2::setupBoxController(), Mantid::CurveFitting::Algorithms::LeBailFit::setupBuiltInRandomWalkStrategy(), Mantid::Algorithms::FilterEvents::setupCustomizedTOFCorrection(), Mantid::Crystal::IntegratePeakTimeSlices::SetUpData1(), Mantid::Algorithms::FilterEvents::setupDirectTOFCorrection(), Mantid::DataHandling::SaveGSASInstrumentFile::setupInstrumentConstants(), Mantid::Algorithms::RadiusSum::setUpOutputWorkspace(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setupRandomWalkStrategy(), Mantid::CurveFitting::Algorithms::LeBailFit::setupRandomWalkStrategyFromTable(), Mantid::DataHandling::LoadSpiceAscii::setupRunStartTime(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogFromSpiceTable(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::setupSampleLogs(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogs(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::setupTransferMatrix(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::DataHandling::LoadHFIRSANS::setWavelength(), Mantid::DataHandling::LoadSpice2D::setWavelength(), Mantid::Algorithms::SmoothNeighbours::setWeightingStrategy(), Mantid::Algorithms::FitOneSinglePeak::simpleFit(), Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration(), Mantid::MDAlgorithms::LoadSQW2::skipDetectorSection(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::Algorithms::WienerSmooth::smoothSingleSpectrum(), Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData(), Mantid::DataHandling::CheckMantidVersion::splitVersionString(), Mantid::Algorithms::SmoothNeighbours::spreadPixels(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::start_point(), Mantid::DataHandling::LoadHFIRSANS::storeMetaDataIntoWS(), Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace(), Mantid::Algorithms::IQTransform::subtractBackgroundWS(), Mantid::Algorithms::CalculateEfficiency2::sumUnmaskedAndDeadPixels(), Mantid::Algorithms::CalculateEfficiency::sumUnmaskedDetectors(), Mantid::DataHandling::LoadSESANS::throwFormatError(), Mantid::DataHandling::SaveFullprofResolution::toProf10IrfString(), Mantid::DataHandling::SaveFullprofResolution::toProf9IrfString(), Mantid::Algorithms::RemoveBins::transformRangeUnit(), Mantid::DataHandling::SetSample::tryCreateXMLFromArgsOnly(), Mantid::Algorithms::NormaliseByDetector::tryParseFunctionParameter(), unlockWorkspaces(), Mantid::DataHandling::LoadEventPreNexus2::unmaskVetoEventIndex(), Mantid::Algorithms::UnwrapMonitor::unwrapX(), Mantid::Algorithms::CorelliCalibrationDatabase::updateComponentDatabaseFiles(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromAscii(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromNeXus(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromRaw(), Mantid::Crystal::IntegratePeakTimeSlices::updatePeakInformation(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::updateWeightAndPosition(), Mantid::MDAlgorithms::MDNorm::validateBinningForTemporaryDataWorkspace(), Mantid::Algorithms::GetAllEi::validateInputs(), Mantid::Algorithms::Rebin::validateInputs(), Mantid::Algorithms::RemoveBins::validateInputs(), Mantid::Crystal::IndexPeaks::validateInputs(), Mantid::DataHandling::LoadSpiceAscii::validateLogNamesType(), Mantid::DataHandling::LoadISISNexus2::validateMultiPeriodLogs(), Mantid::Algorithms::DiffractionFocussing2::validateSpectrumInGroup(), Mantid::Algorithms::SmoothData::validateSpectrumInGroup(), Mantid::DataHandling::LoadNGEM::verifyFileSize(), Mantid::MDAlgorithms::LoadSQW2::warnIfMemoryInsufficient(), Mantid::DataHandling::SaveRKH::write1D(), Mantid::DataHandling::SaveGSS::writeBufferToFile(), Mantid::Crystal::SetSpecialCoordinates::writeCoordinatesToMDEventWorkspace(), Mantid::Crystal::SetSpecialCoordinates::writeCoordinatesToMDHistoWorkspace(), Mantid::Algorithms::CreateLogTimeCorrection::writeCorrectionToFile(), Mantid::Algorithms::FitPeaks::writeFitResult(), Mantid::DataHandling::SaveGSASInstrumentFile::writePRMSingleBank(), Mantid::DataHandling::SaveGSS::writeSLOGdata(), Mantid::DataHandling::SaveAscii2::writeSpectrum(), Mantid::DataHandling::SaveAscii2::writeTableWorkspace(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseDetectorNode(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseSpice().
m_algorithmID
AlgorithmID Mantid::API::Algorithm::m_algorithmID private
Algorithm ID for managed algorithms.
Definition at line 494 of file Algorithm.h.
m_alwaysStoreInADS
bool Mantid::API::Algorithm::m_alwaysStoreInADS private
Always store in the ADS, even for child algos.
Definition at line 484 of file Algorithm.h.
Referenced by doCallProcessGroups(), executeInternal(), getAlwaysStoreInADS(), reportCompleted(), and setAlwaysStoreInADS().
m_cancel
std::atomic<bool> Mantid::API::Algorithm::m_cancel protected
Set to true to stop execution.
Definition at line 404 of file Algorithm.h.
Referenced by Mantid::MDAlgorithms::BinMD::binByIterating(), cancel(), getCancel(), and interruption_point().
m_ChildAlgorithms
std::vector<std::weak_ptr<IAlgorithm> > Mantid::API::Algorithm::m_ChildAlgorithms private
A list of weak pointers to any child algorithms created.
Definition at line 495 of file Algorithm.h.
Referenced by cancel(), and setupAsChildAlgorithm().
m_endChildProgress
double Mantid::API::Algorithm::m_endChildProgress mutable private
Keeps value for algorithm's progress at Child Algorithm's finish.
Definition at line 492 of file Algorithm.h.
Referenced by handleChildProgressNotification(), and setupAsChildAlgorithm().
m_executeAsync
std::unique_ptr<Poco::ActiveMethod<bool, Poco::Void, Algorithm, Poco::ActiveStarter<Algorithm> > > Mantid::API::Algorithm::m_executeAsync private
Poco::ActiveMethod used to implement asynchronous execution.
Definition at line 470 of file Algorithm.h.
Referenced by executeAsync().
m_executionState
std::atomic<ExecutionState> Mantid::API::Algorithm::m_executionState private
the current execution state
Definition at line 479 of file Algorithm.h.
Referenced by executionState(), isInitialized(), and setExecutionState().
m_gcTime
Mantid::Types::Core::DateAndTime Mantid::API::Algorithm::m_gcTime private
The earliest this class should be considered for garbage collection.
Definition at line 525 of file Algorithm.h.
Referenced by executeInternal(), and isReadyForGarbageCollection().
m_groupsHaveSimilarNames
bool Mantid::API::Algorithm::m_groupsHaveSimilarNames private
All the groups have similar names (group_1, group_2 etc.)
Definition at line 516 of file Algorithm.h.
Referenced by checkGroups(), and processGroups().
m_groupSize
size_t Mantid::API::Algorithm::m_groupSize protected
Size of the group(s) being processed.
Definition at line 431 of file Algorithm.h.
Referenced by checkGroups(), and processGroups().
m_groupWorkspaces
std::vector<std::shared_ptr<WorkspaceGroup> > Mantid::API::Algorithm::m_groupWorkspaces private
Pointer to the WorkspaceGroup (if any) for each input workspace property.
Definition at line 512 of file Algorithm.h.
Referenced by checkGroups(), and clearWorkspaceCaches().
m_history
std::shared_ptr<AlgorithmHistory> Mantid::API::Algorithm::m_history protected
Pointer to the history for the algorithm being executed.
Definition at line 418 of file Algorithm.h.
Referenced by doCallProcessGroups(), Mantid::DataHandling::SaveNexusProcessed::doExec(), executeInternal(), Mantid::Algorithms::ConjoinXRuns::fillHistory(), fillHistory(), linkHistoryWithLastChild(), and Mantid::DataHandling::SaveNexus::runSaveNexusProcessed().
m_inputWorkspaceHistories
std::vector<Workspace_sptr> Mantid::API::Algorithm::m_inputWorkspaceHistories private
Store a pointer to the input workspace histories so they can be copied to the outputs to avoid anything being overwritten.
Definition at line 519 of file Algorithm.h.
Referenced by cacheInputWorkspaceHistories(), clearWorkspaceCaches(), and fillHistory().
m_inputWorkspaceProps
std::vector<IWorkspaceProperty *> Mantid::API::Algorithm::m_inputWorkspaceProps protected
All the WorkspaceProperties that are Input or InOut. Set in execute()
Definition at line 416 of file Algorithm.h.
Referenced by cacheWorkspaceProperties(), checkGroups(), clearWorkspaceCaches(), lockWorkspaces(), and processGroups().
m_isAlgStartupLoggingEnabled
bool Mantid::API::Algorithm::m_isAlgStartupLoggingEnabled private
Definition at line 487 of file Algorithm.h.
Referenced by getAlgStartupLogging(), logAlgorithmInfo(), reportCompleted(), and setAlgStartupLogging().
m_isChildAlgorithm
bool Mantid::API::Algorithm::m_isChildAlgorithm private
Algorithm is a child algorithm.
Definition at line 481 of file Algorithm.h.
Referenced by executeInternal(), isChild(), reportCompleted(), and setChild().
m_log
Kernel::Logger Mantid::API::Algorithm::m_log protected
Logger for this algorithm.
Definition at line 421 of file Algorithm.h.
Referenced by Mantid::DataHandling::LoadNexusMonitors2::createOutputWorkspace(), Mantid::Algorithms::GetEiMonDet3::exec(), and Mantid::DataHandling::LoadInstrument::exec().
m_notificationCenter
std::unique_ptr<Poco::NotificationCenter> Mantid::API::Algorithm::m_notificationCenter mutable private
Sends notifications to observers.
Observers can subscribe to notificationCenter using Poco::NotificationCenter::addObserver(...);
Definition at line 475 of file Algorithm.h.
Referenced by notificationCenter().
m_outputWorkspaceProps
std::vector<IWorkspaceProperty *> Mantid::API::Algorithm::m_outputWorkspaceProps private
All the WorkspaceProperties that are Output or InOut. Set in execute()
Definition at line 507 of file Algorithm.h.
Referenced by cacheWorkspaceProperties(), clearWorkspaceCaches(), and lockWorkspaces().
m_parallelException
std::atomic<bool> Mantid::API::Algorithm::m_parallelException protected
Set if an exception is thrown, and not caught, within a parallel region.
Definition at line 406 of file Algorithm.h.
m_parentHistory
std::shared_ptr<AlgorithmHistory> Mantid::API::Algorithm::m_parentHistory protected
Pointer to the parent history object (if set)
Definition at line 425 of file Algorithm.h.
Referenced by Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::Algorithms::ConjoinXRuns::fillHistory(), fillHistory(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), and trackAlgorithmHistory().
m_progressObserver
std::unique_ptr<Poco::NObserver<Algorithm, ProgressNotification> > Mantid::API::Algorithm::m_progressObserver mutable private
Child algorithm progress observer.
Definition at line 477 of file Algorithm.h.
Referenced by progressObserver().
m_properties
Mantid::Kernel::PropertyManagerOwner Mantid::API::Algorithm::m_properties private
Definition at line 527 of file Algorithm.h.
Referenced by afterPropertySet(), asJson(), asString(), clear(), copyPropertiesFrom(), declareOrReplaceProperty(), declareProperty(), existsProperty(), getDeclaredPropertyNames(), getPointerToProperty(), getPointerToPropertyOrdinal(), getProperties(), getProperty(), getPropertyValue(), isDefault(), propertyCount(), removeProperty(), resetProperties(), setAlwaysStoreInADS(), setProperties(), setProperties(), setPropertiesWithString(), setPropertyOrdinal(), setPropertyValue(), setPropertyValueFromJson(), takeProperty(), toJson(), and validateProperties().
m_pureOutputWorkspaceProps
std::vector<IWorkspaceProperty *> Mantid::API::Algorithm::m_pureOutputWorkspaceProps private
All the WorkspaceProperties that are Output (not inOut). Set in execute()
Definition at line 509 of file Algorithm.h.
Referenced by cacheWorkspaceProperties(), clearWorkspaceCaches(), and processGroups().
m_readLockedWorkspaces
WorkspaceVector Mantid::API::Algorithm::m_readLockedWorkspaces private
Vector of all the workspaces that have been read-locked.
Definition at line 502 of file Algorithm.h.
Referenced by lockWorkspaces(), and unlockWorkspaces().
m_recordHistoryForChild
bool Mantid::API::Algorithm::m_recordHistoryForChild private
Flag to indicate whether history should be recorded.
Applicable to child algs only
Definition at line 482 of file Algorithm.h.
Referenced by enableHistoryRecordingForChild(), fillHistory(), linkHistoryWithLastChild(), and trackingHistory().
m_reservedList
std::vector<std::string> Mantid::API::Algorithm::m_reservedList private
Reserved property names.
Definition at line 522 of file Algorithm.h.
Referenced by declareWorkspaceInputProperties(), and isCompoundProperty().
m_resultState
std::atomic<ResultState> Mantid::API::Algorithm::m_resultState private
the current result State
Definition at line 480 of file Algorithm.h.
Referenced by resultState(), and setResultState().
m_rethrow
bool Mantid::API::Algorithm::m_rethrow private
Algorithm should rethrow exceptions while executing.
Definition at line 486 of file Algorithm.h.
Referenced by executeInternal(), and setRethrows().
m_runningAsync
bool Mantid::API::Algorithm::m_runningAsync private
Algorithm is running asynchronously.
Definition at line 485 of file Algorithm.h.
Referenced by doCallProcessGroups(), executeAsyncImpl(), and executeInternal().
m_singleGroup
int Mantid::API::Algorithm::m_singleGroup private
If only one input is a group, this is its index. -1 if they are all groups.
Definition at line 514 of file Algorithm.h.
Referenced by checkGroups(), and processGroups().
m_startChildProgress
double Mantid::API::Algorithm::m_startChildProgress mutable private
Whether to log alg startup and closedown messages from the base class (default = true)
Keeps value for algorithm's progress at start of an Child Algorithm
Definition at line 490 of file Algorithm.h.
Referenced by handleChildProgressNotification(), and setupAsChildAlgorithm().
m_unrolledInputWorkspaces
std::vector<WorkspaceVector> Mantid::API::Algorithm::m_unrolledInputWorkspaces protected
One vector of workspaces for each input workspace property.
A group is unrolled to its constituent members
Definition at line 429 of file Algorithm.h.
Referenced by checkGroups(), clearWorkspaceCaches(), processGroups(), Mantid::DataHandling::SaveNexusESS::processGroups(), and Mantid::DataHandling::SaveNexusProcessed::processGroups().
m_usingBaseProcessGroups
bool Mantid::API::Algorithm::m_usingBaseProcessGroups = false protected
distinguish between base processGroups() and overriden/algorithm specific versions
Definition at line 434 of file Algorithm.h.
Referenced by doCallProcessGroups(), processGroups(), and Mantid::API::MultiPeriodGroupAlgorithm::processGroups().
m_writeLockedWorkspaces
WorkspaceVector Mantid::API::Algorithm::m_writeLockedWorkspaces private
Vector of all the workspaces that have been write-locked.
Definition at line 504 of file Algorithm.h.
Referenced by lockWorkspaces(), and unlockWorkspaces().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/Algorithm.h
Framework/API/inc/MantidAPI/Algorithm.hxx
Framework/API/src/Algorithm.cpp
Framework/API/src/AlgorithmExecuteProfile.cpp