Mantid: Mantid::API::Jacobian Class Reference
Mantid::API::Jacobian Class Reference abstract
Represents the Jacobian in IFitFunction::functionDeriv.
#include <Jacobian.h>
Public Member Functions
virtual double get (size_t iY, size_t iP)=0
Get the value to a Jacobian matrix element.
virtual void set (size_t iY, size_t iP, double value)=0
Set a value to a Jacobian matrix element.
virtual void zero ()=0
Zero all matrix elements.
virtual ~Jacobian ()=default
Virtual destructor.
Detailed Description
Represents the Jacobian in IFitFunction::functionDeriv.
Author
Roman Tolchenov, Tessella plc
Date
15/11/2011
Definition at line 22 of file Jacobian.h.
Constructor & Destructor Documentation
~Jacobian()
virtual Mantid::API::Jacobian::~Jacobian () virtual default
Virtual destructor.
Member Function Documentation
get()
virtual double Mantid::API::Jacobian::get (size_t iY, size_t iP) pure virtual
Get the value to a Jacobian matrix element.
Parameters
iY :: The index of a data point.
iP :: The index of a declared parameter.
Implemented in Mantid::API::PartialJacobian, Mantid::API::TempJacobian, Mantid::CurveFitting::EigenJacobian, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::EigenMatrix >, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::FortranMatrix >, Mantid::CurveFitting::JacobianImpl1< T >, Mantid::CurveFitting::Jacobian, and Mantid::CurveFitting::Algorithms::JacobianImpl.
Referenced by Mantid::CurveFitting::IMWDomainCreator::addFunctionValuesToWS(), Mantid::CurveFitting::TableWorkspaceDomainCreator::addFunctionValuesToWS(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateDerivative(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateHessian(), export_Jacobian(), Mantid::CurveFitting::Functions::BivariateNormal::functionDeriv1D(), and Mantid::API::PartialJacobian::get().
set()
virtual void Mantid::API::Jacobian::set (size_t iY, size_t iP, double value) pure virtual
Set a value to a Jacobian matrix element.
Parameters
iY :: The index of a data point.
iP :: The index of a declared parameter.
value :: The derivative value.
Implemented in Mantid::API::PartialJacobian, Mantid::API::TempJacobian, Mantid::CurveFitting::EigenJacobian, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::EigenMatrix >, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::FortranMatrix >, Mantid::CurveFitting::JacobianImpl1< T >, Mantid::CurveFitting::Jacobian, and Mantid::CurveFitting::Algorithms::JacobianImpl.
Referenced by Mantid::API::IFunction1D::calcNumericalDerivative1D(), Mantid::CurveFitting::Functions::Voigt::calculateFunctionAndDerivative(), Mantid::API::IFunction::calNumericalDeriv(), export_Jacobian(), Mantid::CurveFitting::Functions::UserFunction1D::functionDeriv(), Mantid::CurveFitting::Functions::LogNormal::functionDeriv1D(), Mantid::CurveFitting::Functions::Quadratic::functionDeriv1D(), Mantid::CurveFitting::Functions::StretchExp::functionDeriv1D(), Mantid::CurveFitting::Functions::ActivationK::functionDeriv1D(), Mantid::CurveFitting::Functions::ActivationmeV::functionDeriv1D(), Mantid::CurveFitting::Functions::BivariateNormal::functionDeriv1D(), Mantid::CurveFitting::Functions::Chebyshev::functionDeriv1D(), Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong::functionDeriv1D(), Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot::functionDeriv1D(), Mantid::CurveFitting::Functions::ExpDecay::functionDeriv1D(), Mantid::CurveFitting::Functions::ExpDecayMuon::functionDeriv1D(), Mantid::CurveFitting::Functions::ExpDecayOsc::functionDeriv1D(), Mantid::CurveFitting::Functions::FlatBackground::functionDeriv1D(), Mantid::CurveFitting::Functions::FullprofPolynomial::functionDeriv1D(), Mantid::CurveFitting::Functions::GausDecay::functionDeriv1D(), Mantid::CurveFitting::Functions::GausOsc::functionDeriv1D(), Mantid::CurveFitting::Functions::LinearBackground::functionDeriv1D(), Mantid::CurveFitting::Functions::MagneticOrderParameter::functionDeriv1D(), Mantid::CurveFitting::Functions::MuoniumDecouplingCurve::functionDeriv1D(), Mantid::CurveFitting::Functions::Polynomial::functionDeriv1D(), Mantid::CurveFitting::Functions::PowerLaw::functionDeriv1D(), Mantid::CurveFitting::Functions::ProductLinearExp::functionDeriv1D(), Mantid::CurveFitting::Functions::ProductQuadraticExp::functionDeriv1D(), Mantid::CurveFitting::Functions::SmoothTransition::functionDeriv1D(), Mantid::CurveFitting::Functions::TabulatedFunction::functionDeriv1D(), Mantid::CurveFitting::Functions::ThermalNeutronDtoTOFFunction::functionDeriv1D(), Mantid::API::IPeakFunction::functionDeriv1D(), Mantid::CurveFitting::Functions::ChudleyElliotSQE::functionDeriv1D(), Mantid::CurveFitting::Functions::FickDiffusionSQE::functionDeriv1D(), Mantid::CurveFitting::Functions::HallRossSQE::functionDeriv1D(), Mantid::CurveFitting::Functions::TeixeiraWaterSQE::functionDeriv1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::FrameworkTestHelpers::FunctionChangesNParams::functionDeriv1D(), Mantid::FrameworkTestHelpers::MultiDomainFunctionTest_Function::functionDeriv1D(), Mantid::CurveFitting::Functions::AsymmetricPearsonVII::functionDerivLocal(), Mantid::CurveFitting::Functions::Gaussian::functionDerivLocal(), Mantid::CurveFitting::Functions::Lorentzian::functionDerivLocal(), Mantid::CurveFitting::Functions::PseudoVoigt::functionDerivLocal(), Mantid::CurveFitting::Functions::FlatBackground::histogramDerivative1D(), Mantid::CurveFitting::Functions::Gaussian::histogramDerivative1D(), Mantid::CurveFitting::Functions::LinearBackground::histogramDerivative1D(), Mantid::CurveFitting::Functions::Lorentzian::histogramDerivative1D(), and Mantid::API::PartialJacobian::set().
zero()
virtual void Mantid::API::Jacobian::zero () pure virtual
Zero all matrix elements.
Implemented in Mantid::API::PartialJacobian, Mantid::API::TempJacobian, Mantid::CurveFitting::EigenJacobian, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::EigenMatrix >, Mantid::CurveFitting::JacobianImpl1< Mantid::CurveFitting::FortranMatrix >, Mantid::CurveFitting::JacobianImpl1< T >, Mantid::CurveFitting::Jacobian, and Mantid::CurveFitting::Algorithms::JacobianImpl.
References value.
Referenced by Mantid::API::MultiDomainFunction::functionDeriv().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/Jacobian.h