Mantid: MantidQt::MantidWidgets::InstrumentSelector Class Reference
MantidQt::MantidWidgets::InstrumentSelector Class Reference
This class defines a widget for selecting an instrument known to Mantid.
#include <InstrumentSelector.h>
Public Slots
void fillWithInstrumentsFromFacility (const QString &name=QString())
Update list for a new facility.
Signals
void configValueChanged (const QString &, const QString &, const QString &)
void instrumentListUpdated ()
Signals that the list of instruments has been updated.
void instrumentSelectionChanged (const QString &)
Indicate that the instrument selection has changed.
Public Member Functions
bool getAutoUpdate ()
Returns true of auto reloading on facility change is enabled.
QString getFacility ()
Get the name of the facility instrumetns are currently loaded from.
const QStringList & getTechniques () const
Return the list of techniques.
InstrumentSelector (QWidget *parent=nullptr, bool init=true)
Default Constructor.
void setAutoUpdate (bool autoUpdate)
Enable or disable reloading on facility change.
void setFacility (const QString &facilityName)
Load instruments from a given facility.
void setTechniques (const QStringList &techniques)
Set the list of techniques.
void updateInstrumentOnSelection (const bool storeChanges)
Sets whether to update the default instrument on selection change.
~InstrumentSelector () override
Destructor.
Properties
QString facility
QStringList techniques
bool updateOnFacilityChange
Private Slots
void updateInstrument (const QString &name)
Handle an instrument seelction.
Private Member Functions
void filterByTechniquesAtFacility (const QStringList &techniques, const Mantid::Kernel::FacilityInfo &facility)
Filter the list to only show those supporting the given technique.
void handleConfigChange (Mantid::Kernel::ConfigValChangeNotification_ptr pNf)
Private Attributes
Poco::NObserver< InstrumentSelector, Mantid::Kernel::ConfigValChangeNotification > m_changeObserver
Poco Observer for Config Service Notifications.
const Mantid::Kernel::FacilityInfo * m_currentFacility
The current facility.
bool m_init
Should the object be initialized.
QString m_selectedInstrument
The last selected instrument.
bool m_storeChanges
Should the default instrument be changed when the selection changes.
QStringList m_techniques
A list of technqiues.
bool m_updateOnFacilityChange
If the instrument list should be reloaded when the facility changes.
Detailed Description
This class defines a widget for selecting an instrument known to Mantid.
Author
Martyn Gigg, Tessella Support Services plc
Date
10/08/2010
Definition at line 30 of file InstrumentSelector.h.
Constructor & Destructor Documentation
InstrumentSelector()
MantidQt::MantidWidgets::InstrumentSelector::InstrumentSelector (QWidget * parent = nullptr, bool init = true)
Default Constructor.
Default constructor.
Parameters
parent :: A widget to act as this widget's parent (default = NULL)
init :: If true then the widget will be populated with the instrument list (default = true)
Definition at line 29 of file InstrumentSelector.cpp.
References Mantid::Kernel::ConfigServiceImpl::addObserver(), fillWithInstrumentsFromFacility(), m_changeObserver, and updateInstrument().
~InstrumentSelector()
MantidQt::MantidWidgets::InstrumentSelector::~InstrumentSelector () override
Destructor.
Destructor for InstrumentSelector De-subscribes this object from the Poco NotificationCentre.
Definition at line 49 of file InstrumentSelector.cpp.
References m_changeObserver, and m_init.
Member Function Documentation
configValueChanged
void MantidQt::MantidWidgets::InstrumentSelector::configValueChanged (const QString & , const QString & , const QString &) signal
fillWithInstrumentsFromFacility
void MantidQt::MantidWidgets::InstrumentSelector::fillWithInstrumentsFromFacility (const QString & name = QString()) slot
Update list for a new facility.
Populate list with instruments from the named facility.
Note the current list is cleared.
Parameters
name :: The name of the facility whose instruments should be placed in the list. An empty string uses the default facility defined in Mantid.
Definition at line 126 of file InstrumentSelector.cpp.
References addItem(), filterByTechniquesAtFacility(), Mantid::Kernel::ConfigServiceImpl::getFacility(), Mantid::Kernel::ConfigServiceImpl::getFacilityNames(), index, Mantid::Kernel::FacilityInfo::instrument(), instrumentListUpdated(), Mantid::Kernel::FacilityInfo::instruments(), m_currentFacility, m_techniques, name, Mantid::Kernel::InstrumentInfo::shortName(), and updateInstrument().
Referenced by handleConfigChange(), InstrumentSelector(), and setFacility().
filterByTechniquesAtFacility()
void MantidQt::MantidWidgets::InstrumentSelector::filterByTechniquesAtFacility (const QStringList & techniques, const Mantid::Kernel::FacilityInfo & facility) private
Filter the list to only show those supporting the given technique.
Parameters
techniques :: A string list containing the names of a techniques to filter the instrument list by
facility :: A FacilityInfo object
Definition at line 216 of file InstrumentSelector.cpp.
References count, facility, instrumentListUpdated(), name, removeItem(), and techniques.
Referenced by fillWithInstrumentsFromFacility(), and setTechniques().
getAutoUpdate()
bool MantidQt::MantidWidgets::InstrumentSelector::getAutoUpdate ()
Returns true of auto reloading on facility change is enabled.
Returns if the list of instruments will be refeshed when the facility changes.
Returns
If facility auto update is enabled
Definition at line 67 of file InstrumentSelector.cpp.
References m_updateOnFacilityChange.
getFacility()
QString MantidQt::MantidWidgets::InstrumentSelector::getFacility ()
Get the name of the facility instrumetns are currently loaded from.
Returns the name of the facility from which instruments are listed.
Returns
Facility name
Definition at line 91 of file InstrumentSelector.cpp.
References m_currentFacility, and Mantid::Kernel::FacilityInfo::name().
getTechniques()
const QStringList & MantidQt::MantidWidgets::InstrumentSelector::getTechniques () const
Return the list of techniques.
Return the list of techniques that are supported by the instruments in the widget.
Returns
A list of supported techniques
Definition at line 60 of file InstrumentSelector.cpp.
References m_techniques.
handleConfigChange()
void MantidQt::MantidWidgets::InstrumentSelector::handleConfigChange (Mantid::Kernel::ConfigValChangeNotification_ptr pNf) private
Definition at line 99 of file InstrumentSelector.cpp.
References fillWithInstrumentsFromFacility(), m_currentFacility, m_updateOnFacilityChange, and Mantid::Kernel::FacilityInfo::name().
instrumentListUpdated
void MantidQt::MantidWidgets::InstrumentSelector::instrumentListUpdated () signal
Signals that the list of instruments has been updated.
Referenced by fillWithInstrumentsFromFacility(), and filterByTechniquesAtFacility().
instrumentSelectionChanged
void MantidQt::MantidWidgets::InstrumentSelector::instrumentSelectionChanged (const QString &) signal
Indicate that the instrument selection has changed.
The parameter will contain the new name
Referenced by updateInstrument().
setAutoUpdate()
void MantidQt::MantidWidgets::InstrumentSelector::setAutoUpdate (bool autoUpdate)
Enable or disable reloading on facility change.
Sets if the list of instruments should be updated folowing a facility change.
Parameters
autoUpdate If instruments are to be updated
Definition at line 73 of file InstrumentSelector.cpp.
References m_updateOnFacilityChange.
setFacility()
void MantidQt::MantidWidgets::InstrumentSelector::setFacility (const QString & facilityName)
Load instruments from a given facility.
Sets the facility instruments should be loaded from and refeshes the list.
Parameters
facilityName Name of facilty
Definition at line 97 of file InstrumentSelector.cpp.
References fillWithInstrumentsFromFacility().
setTechniques()
void MantidQt::MantidWidgets::InstrumentSelector::setTechniques (const QStringList & techniques)
Set the list of techniques.
Parameters
techniques :: Only those instruments that support these techniques will be shown
Definition at line 80 of file InstrumentSelector.cpp.
References count, filterByTechniquesAtFacility(), m_currentFacility, m_techniques, and techniques.
updateInstrument
void MantidQt::MantidWidgets::InstrumentSelector::updateInstrument (const QString & name) private slot
Handle an instrument seelction.
Handle an instrument being selected from the drop down.
Set the named instrument as the default for Mantid if desired and emit the signal if the new instrument is different to that which was previously selected.
Parameters
name :: A string containing the new instrument to set as the default
Definition at line 192 of file InstrumentSelector.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, instrumentSelectionChanged(), m_selectedInstrument, m_storeChanges, and name.
Referenced by fillWithInstrumentsFromFacility(), and InstrumentSelector().
updateInstrumentOnSelection()
void MantidQt::MantidWidgets::InstrumentSelector::updateInstrumentOnSelection (const bool storeChanges)
Sets whether to update the default instrument on selection change.
Parameters
storeChanges :: True = store change on selection change
Definition at line 180 of file InstrumentSelector.cpp.
References m_storeChanges.
Member Data Documentation
m_changeObserver
Poco::NObserver<InstrumentSelector, Mantid::Kernel::ConfigValChangeNotification> MantidQt::MantidWidgets::InstrumentSelector::m_changeObserver private
Poco Observer for Config Service Notifications.
Definition at line 80 of file InstrumentSelector.h.
Referenced by InstrumentSelector(), and ~InstrumentSelector().
m_currentFacility
const Mantid::Kernel::FacilityInfo* MantidQt::MantidWidgets::InstrumentSelector::m_currentFacility private
The current facility.
Definition at line 85 of file InstrumentSelector.h.
Referenced by fillWithInstrumentsFromFacility(), getFacility(), handleConfigChange(), and setTechniques().
m_init
bool MantidQt::MantidWidgets::InstrumentSelector::m_init private
Should the object be initialized.
Definition at line 87 of file InstrumentSelector.h.
Referenced by ~InstrumentSelector().
m_selectedInstrument
QString MantidQt::MantidWidgets::InstrumentSelector::m_selectedInstrument private
The last selected instrument.
Definition at line 93 of file InstrumentSelector.h.
Referenced by updateInstrument().
m_storeChanges
bool MantidQt::MantidWidgets::InstrumentSelector::m_storeChanges private
Should the default instrument be changed when the selection changes.
Definition at line 89 of file InstrumentSelector.h.
Referenced by updateInstrument(), and updateInstrumentOnSelection().
m_techniques
QStringList MantidQt::MantidWidgets::InstrumentSelector::m_techniques private
A list of technqiues.
Only those instruments supporting these techniques are shown.
Definition at line 83 of file InstrumentSelector.h.
Referenced by fillWithInstrumentsFromFacility(), getTechniques(), and setTechniques().
m_updateOnFacilityChange
bool MantidQt::MantidWidgets::InstrumentSelector::m_updateOnFacilityChange private
If the instrument list should be reloaded when the facility changes.
Definition at line 91 of file InstrumentSelector.h.
Referenced by getAutoUpdate(), handleConfigChange(), and setAutoUpdate().
Property Documentation
facility
QString MantidQt::MantidWidgets::InstrumentSelector::facility read write
Definition at line 35 of file InstrumentSelector.h.
Referenced by filterByTechniquesAtFacility().
techniques
QStringList MantidQt::MantidWidgets::InstrumentSelector::techniques read write
Definition at line 33 of file InstrumentSelector.h.
Referenced by filterByTechniquesAtFacility(), and setTechniques().
updateOnFacilityChange
bool MantidQt::MantidWidgets::InstrumentSelector::updateOnFacilityChange read write
Definition at line 34 of file InstrumentSelector.h.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InstrumentSelector.h
qt/widgets/common/src/InstrumentSelector.cpp