Mantid: ICat4::ns1__isAccessAllowed Class Reference
ICat4::ns1__isAccessAllowed Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__isAccessAllowed ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
enum ns1__accessType * accessType
ns1__entityBaseBean * bean
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1285 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__isAccessAllowed()
ICat4::ns1__isAccessAllowed::ns1__isAccessAllowed () inline
Definition at line 1298 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__isAccessAllowed::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6708 of file ICat4C.cpp.
References accessType, bean, sessionId, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::soap_in_ns1__isAccessAllowed(), ICat4::soap_new_req_ns1__isAccessAllowed(), and ICat4::soap_new_set_ns1__isAccessAllowed().
soap_get()
void * ICat4::ns1__isAccessAllowed::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6821 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__isAccessAllowed().
soap_in()
void * ICat4::ns1__isAccessAllowed::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6745 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__isAccessAllowed().
Referenced by ICat4::soap_in_ns1__isAccessAllowed().
soap_out()
int ICat4::ns1__isAccessAllowed::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6726 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__isAccessAllowed().
Referenced by soap_put().
soap_put()
int ICat4::ns1__isAccessAllowed::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6814 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__isAccessAllowed.
soap_serialize()
void ICat4::ns1__isAccessAllowed::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6716 of file ICat4C.cpp.
References accessType, bean, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTons1__accessType(), ICat4::soap_serialize_PointerTons1__entityBaseBean(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__searchTextResponse().
soap_type()
int ICat4::ns1__isAccessAllowed::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1291 of file ICat4Stub.h.
Member Data Documentation
accessType
enum ns1__accessType* ICat4::ns1__isAccessAllowed::accessType
Definition at line 1289 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::isAccessAllowed(), soap_default(), and soap_serialize().
bean
ns1__entityBaseBean* ICat4::ns1__isAccessAllowed::bean
Definition at line 1288 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::isAccessAllowed(), soap_default(), and soap_serialize().
sessionId
std::string* ICat4::ns1__isAccessAllowed::sessionId
Definition at line 1287 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::isAccessAllowed(), soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp