Mantid: MantidQt::API::HelpWindow Class Reference
MantidQt::API::HelpWindow Class Reference
#include <HelpWindow.h>
Static Public Member Functions
static void showAlgorithm (const QString &name, const int version=-1)
static void showAlgorithm (const std::string &name=std::string(), const int version=-1)
static void showConcept (const QString &name)
static void showConcept (const std::string &name=std::string())
static void showCustomInterface (const QString &name, const QString &area=QString(), const QString &section=QString())
static void showCustomInterface (const std::string &name=std::string(), const std::string &area=std::string(), const std::string &section=std::string())
static void showFitFunction (const std::string &name=std::string())
static void showPage (const QString &url)
static void showPage (const QUrl &url)
static void showPage (const std::string &url=std::string())
Detailed Description
Definition at line 19 of file HelpWindow.h.
Member Function Documentation
showAlgorithm() [1/2]
void MantidQt::API::HelpWindow::showAlgorithm (const QString & name, const int version = -1) static
Definition at line 54 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::debug(), name, MantidQt::API::MantidDesktopServices::openUrl(), and MantidQt::API::MantidHelpInterface::showAlgorithm().
showAlgorithm() [2/2]
void MantidQt::API::HelpWindow::showAlgorithm (const std::string & name = std::string(), const int version = -1) static
Definition at line 50 of file HelpWindow.cpp.
References name, and showAlgorithm().
Referenced by MantidQt::API::AlgorithmDialog::helpClicked(), MantidQt::MantidWidgets::SequentialFitDialog::helpClicked(), MantidQt::CustomDialogs::LoadDialog::helpClicked(), and showAlgorithm().
showConcept() [1/2]
void MantidQt::API::HelpWindow::showConcept (const QString & name) static
Definition at line 70 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::error(), name, and MantidQt::API::MantidHelpInterface::showConcept().
showConcept() [2/2]
void MantidQt::API::HelpWindow::showConcept (const std::string & name = std::string()) static
Definition at line 68 of file HelpWindow.cpp.
References name, and showConcept().
Referenced by showConcept().
showCustomInterface() [1/2]
void MantidQt::API::HelpWindow::showCustomInterface (const QString & name, const QString & area = QString(), const QString & section = QString()) static
Definition at line 94 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::debug(), name, MantidQt::API::MantidDesktopServices::openUrl(), and MantidQt::API::MantidHelpInterface::showCustomInterface().
Referenced by MantidQt::API::ManageUserDirectories::helpClicked(), MantidQt::MantidWidgets::FitScriptGeneratorView::onHelpClicked(), and showCustomInterface().
showCustomInterface() [2/2]
void MantidQt::API::HelpWindow::showCustomInterface (const std::string & name = std::string(), const std::string & area = std::string(), const std::string & section = std::string()) static
Definition at line 90 of file HelpWindow.cpp.
References name, and showCustomInterface().
showFitFunction()
void MantidQt::API::HelpWindow::showFitFunction (const std::string & name = std::string()) static
Definition at line 80 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::error(), name, and MantidQt::API::MantidHelpInterface::showFitFunction().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::functionHelp(), and MantidQt::MantidWidgets::SelectFunctionDialog::helpClicked().
showPage() [1/3]
void MantidQt::API::HelpWindow::showPage (const QString & url) static
Definition at line 30 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::error(), and MantidQt::API::MantidHelpInterface::showPage().
showPage() [2/3]
void MantidQt::API::HelpWindow::showPage (const QUrl & url) static
Definition at line 40 of file HelpWindow.cpp.
References MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::Logger::error(), and MantidQt::API::MantidHelpInterface::showPage().
showPage() [3/3]
void MantidQt::API::HelpWindow::showPage (const std::string & url = std::string()) static
Definition at line 28 of file HelpWindow.cpp.
References showPage().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::browserHelp(), MantidQt::API::ScriptRepositoryView::helpClicked(), MantidQt::MantidWidgets::UserFunctionDialog::helpClicked(), and showPage().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/HelpWindow.h
qt/widgets/common/src/HelpWindow.cpp