Mantid: Mantid::Geometry::ObjComponent Class Reference
Mantid::Geometry::ObjComponent Class Reference
Object Component class, this class brings together the physical attributes of the component to the positioning and geometry tree.
#include <ObjComponent.h>
Public Member Functions
void boundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) const
IComponent * clone () const override
Virtual Copy Constructor.
void draw () const override
Draws the objcomponent, If the handler is not set then this function does nothing.
void drawObject () const override
Draws the Object.
void getBoundingBox (BoundingBox &absoluteBB) const override
get bounding box, which may or may not be axis aligned;
virtual double getDepth () const
get Depth (Z-dimension) value for component
virtual double getHeight () const
get Height (Y-dimension) value for component
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
virtual double getWidth () const
get Width (X-dimension) value for component
void initDraw () const override
Initializes the ObjComponent for rendering, this function should be called before rendering.
int interceptSurface (Track &track) const override
Checks whether the track given will pass through this Component.
bool isOnSide (const Kernel::V3D &point) const override
Does the point given lie on the surface of this object component?
bool isValid (const Kernel::V3D &point) const override
Does the point given lie within this object component?
const Kernel::Material material () const override
Return the material this component is made from.
ObjComponent (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
ObjComponent (const std::string &name, IComponent *parent=nullptr)
Constructor.
ObjComponent (const std::string &name, std::shared_ptr< const IObject > shape, IComponent *parent=nullptr)
Constructor.
virtual size_t registerContents (class ComponentVisitor &componentVisitor) const override
Register the contents of this ObjComponent.
void setShape (std::shared_ptr< const IObject > newShape)
Set a new shape on the component void setShape(std::shared_ptr<const IObject> newShape);.
const std::shared_ptr< const IObject > shape () const override
Return the shape of the component.
double solidAngle (const Geometry::SolidAngleParams &params) const override
Finds the approximate solid angle covered by the component when viewed from the point given.
std::string type () const override
type string
Public Member Functions inherited from Mantid::Geometry::IObjComponent
GeometryHandler * Handle () const
Gets the GeometryHandler.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
~IObjComponent () override
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual ~IComponent ()=default
Destructor.
Public Member Functions inherited from Mantid::Geometry::Component
Component ()
Create Empty Component at Origin, with no orientation and null parent.
Component (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
Component (std::string name, const Kernel::V3D &position, const Kernel::Quat &rotation, IComponent *parent=nullptr)
Create a named component with positioning vector, orientation and parent.
Component (std::string name, const Kernel::V3D &position, IComponent *parent=nullptr)
Create a named component with positioning vector, and parent component.
Component (std::string name, IComponent *parent=nullptr)
Create a named component with a parent component (optional)
std::vector< std::shared_ptr< const IComponent > > getAncestors () const override
Return an array of all ancestors.
IComponent const * getBaseComponent () const override
Returns const pointer to base component if this component is parametrized.
ComponentID getComponentID () const override
Returns the ComponentID - a unique identifier of the component.
double getDistance (const IComponent &) const override
Get the distance to another IComponent.
std::string getFullName () const override
Get the full pathname.
std::string getName () const override
Get the IComponent name.
std::shared_ptr< const IComponent > getParent () const override
Return a pointer to the current parent. as shared pointer.
Kernel::V3D getPos () const override
Get the position of the IComponent. Tree structure is traverse through the.
Kernel::V3D getRelativePos () const override
Get the position relative to the parent IComponent (absolute if no parent)
Kernel::Quat getRelativeRot () const override
Get the relative Orientation.
Kernel::Quat getRotation () const override
Get the absolute orientation of the IComponent.
std::optional< Kernel::V2D > getSideBySideViewPos () const override
Return the position of the component required on the instrument side by side view.
bool isParentNamed (const std::string &expectedName, int maxDepth=-1) const
Return true if one of the parents of this component is named something.
void rotate (const Kernel::Quat &) override
Rotate the IComponent. This is relative to parent.
void rotate (double, const Kernel::V3D &) override
Rotate the IComponent by an angle in degrees with respect to an axis.
void setName (const std::string &) override
Set the IComponent name.
void setParent (IComponent *) override
Assign a parent IComponent. Previous parent link is lost.
void setPos (const Kernel::V3D &) override
Set the position of the Component The position is with respect to the parent Component.
void setPos (double, double, double) override
Set the IComponent position, x, y, z respective to parent (if present)
void setRot (const Kernel::Quat &) override
Set the orientation Kernel::Quaternion relative to parent (if present)
void setSideBySideViewPos (const Kernel::V2D &) override
Set the IComponent position in the side by side instrument view.
void translate (const Kernel::V3D &) override
Translate the IComponent (vector form). This is relative to parent if.
void translate (double, double, double) override
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string typeName () const
std::set< std::string > getParameterNames (bool recursive=true) const override
Return the parameter names.
std::map< std::string, ComponentID > getParameterNamesByComponent () const override
return the parameter names and the component they are from
bool hasParameter (const std::string &name, bool recursive=true) const override
Returns a boolean indicating if the component has the named parameter.
std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a double.
std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an int.
std::string getParameterType (const std::string &pname, bool recursive=true) const override
Get a parameter's type – this is HACK until Python can export property regardless of the property type.
std::string getDescription () const
Get this component parameter's description – no recursive search within children.
std::string getParamDescription (const std::string &pname, bool recursive=true) const
Get description of a parameter attached to this component
std::string getParamShortDescription (const std::string &pname, bool recursive=true) const
Get a component's parameter short description.
std::string getShortDescription () const
Get a components's short description.
void setDescription (const std::string &descr)
Set components description.
std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a bool.
std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::V3D.
std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::Quaternion.
std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a string.
std::string getParameterAsString (const std::string &pname, bool recursive=true) const override
get a string representation of a parameter
bool getParameterVisible (const std::string &p_name, bool recursive) const override
Get a visibility attribute of a parameter from the parameter map.
double getFittingParameter (const std::string &pname, double xvalue) const
Get fitting parameter.
void printSelf (std::ostream &) const override
Prints a text representation of itself.
const IComponent * base () const
Returns the address of the base component.
Kernel::V3D getScaleFactor () const override
Returns the ScaleFactor.
const IComponent * getBareParent () const override
Returns the bare pointer to the IComponent parent.
virtual void readXMLAttributes (const Poco::XML::Attributes &attr)
Reads the XML attributes from Poco XML parser.
virtual void writeXML (Poco::XML::XMLWriter &writer) const
virtual void appendXML (std::ostream &xmlStream) const
Append to an open XML string.
bool isParametrized () const override
Return true if the Component is, in fact, parametrized (that is - it has a valid parameter map)
bool hasComponentInfo () const
size_t index () const
Helper for legacy access mode. Returns the index of the component.
Protected Member Functions
const Kernel::V3D factorOutComponentPosition (const Kernel::V3D &point) const
Find the point that's in the same place relative to the constituent geometrical Object if the position and rotation introduced by the Component is ignored.
const Kernel::V3D takeOutRotation (Kernel::V3D point) const
Rotates a point by the reverse of the component's rotation.
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Protected Member Functions inherited from Mantid::Geometry::Component
template<class TYPE >
std::vector< TYPE > getParameter (const std::string &p_name, bool recursive) const
Get a parameter from the parameter map.
void swap (const Component *base, const ParameterMap *pmap)
Swap the current references to the un-parameterized component and parameter map for new ones.
Protected Attributes
std::shared_ptr< const IObject > m_shape
The physical geometry representation.
Protected Attributes inherited from Mantid::Geometry::Component
const IComponent * m_parent
Parent component in the tree.
const Component * m_base
The base component - this is the unmodified component (without the parameters).
const ParameterMap * m_map
A pointer to const ParameterMap containing the parameters.
std::string m_name
Name of the component.
Kernel::V3D m_pos
Position w.
Kernel::Quat m_rot
Orientation.
std::optional< Kernel::V2D > m_sidebysideviewpos
Position of component in instrument viewer side by side view.
Private Member Functions
void getRelativeBoundingBox (BoundingBox &RelativeBB) const
common part of the two Bounding box functions above;
Detailed Description
Object Component class, this class brings together the physical attributes of the component to the positioning and geometry tree.
Author
Laurent C Chapon, ISIS, RAL
Date
26/09/2007
Author
Russell Taylor, Tessella Support Services plc
Date
26/06/2008
Definition at line 33 of file ObjComponent.h.
Constructor & Destructor Documentation
ObjComponent() [1/3]
Mantid::Geometry::ObjComponent::ObjComponent (const IComponent * base, const ParameterMap * map)
Constructor for parametrized component.
Constructor for a parametrized ObjComponent.
Parameters
base the base (un-parametrized) IComponent
map pointer to the ParameterMap
Definition at line 28 of file ObjComponent.cpp.
ObjComponent() [2/3]
Mantid::Geometry::ObjComponent::ObjComponent (const std::string & name, IComponent * parent = nullptr) explicit
Constructor.
Parameters
name :: The name of the component
parent :: The Parent geometry object of this component
Definition at line 34 of file ObjComponent.cpp.
ObjComponent() [3/3]
Mantid::Geometry::ObjComponent::ObjComponent (const std::string & name, std::shared_ptr< const IObject > shape, IComponent * parent = nullptr) explicit
Constructor.
Parameters
name :: The name of the component
shape :: A pointer to the object describing the shape of this component
parent :: The Parent geometry object of this component
Definition at line 43 of file ObjComponent.cpp.
Member Function Documentation
boundingBox()
void Mantid::Geometry::ObjComponent::boundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) const
Todo:
This should go in favour of just the class related one.
clone()
IComponent * Mantid::Geometry::ObjComponent::clone () const inline override virtual
Virtual Copy Constructor.
Returns
A pointer to a copy of the input ObjComponent
Implements Mantid::Geometry::IObjComponent.
Definition at line 48 of file ObjComponent.h.
draw()
void Mantid::Geometry::ObjComponent::draw () const override virtual
Draws the objcomponent, If the handler is not set then this function does nothing.
Implements Mantid::Geometry::IObjComponent.
Definition at line 309 of file ObjComponent.cpp.
References Mantid::Geometry::IObjComponent::Handle(), and Mantid::Geometry::GeometryHandler::render().
drawObject()
void Mantid::Geometry::ObjComponent::drawObject () const override virtual
Draws the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 319 of file ObjComponent.cpp.
References shape().
factorOutComponentPosition()
const V3D Mantid::Geometry::ObjComponent::factorOutComponentPosition (const Kernel::V3D & point) const protected
Find the point that's in the same place relative to the constituent geometrical Object if the position and rotation introduced by the Component is ignored.
Definition at line 284 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getPos(), and takeOutRotation().
Referenced by interceptSurface(), isOnSide(), isValid(), and solidAngle().
getBoundingBox()
void Mantid::Geometry::ObjComponent::getBoundingBox (BoundingBox & absoluteBB) const override virtual
get bounding box, which may or may not be axis aligned;
Given an input estimate of the axis aligned (AA) bounding box (BB), return an improved set of values.
The AA BB is determined in the frame of the object and the initial estimate will be transformed there. The returned BB will be the frame of the ObjComponent and may not be optimal.
Parameters
absoluteBB :: [InOut] The bounding box for this object component will be stored here. if BB alignment is different from axis alignment, the system of coordinates to alighn is taken fron the absoluteBB
Implements Mantid::Geometry::IComponent.
Definition at line 178 of file ObjComponent.cpp.
References Mantid::Geometry::ComponentInfo::boundingBox(), Mantid::Geometry::ParameterMap::componentInfo(), Mantid::Geometry::BoundingBox::getCoordSystem(), Mantid::Geometry::Component::getPos(), Mantid::Geometry::Component::getRotation(), Mantid::Geometry::Component::getScaleFactor(), Mantid::Geometry::Component::hasComponentInfo(), Mantid::Geometry::Component::index(), Mantid::Geometry::BoundingBox::isAxisAligned(), Mantid::Geometry::BoundingBox::isNull(), Mantid::Geometry::Component::m_map, Mantid::Geometry::BoundingBox::nullify(), Mantid::Geometry::BoundingBox::realign(), shape(), Mantid::Kernel::V3D::X(), Mantid::Geometry::BoundingBox::xMax(), Mantid::Geometry::BoundingBox::xMin(), Mantid::Kernel::V3D::Y(), Mantid::Geometry::BoundingBox::yMax(), Mantid::Geometry::BoundingBox::yMin(), Mantid::Kernel::V3D::Z(), Mantid::Geometry::BoundingBox::zMax(), and Mantid::Geometry::BoundingBox::zMin().
getDepth()
double Mantid::Geometry::ObjComponent::getDepth () const virtual
get Depth (Z-dimension) value for component
Gets the Depth of the object by querying the underlying BoundingBox.
Returns
depth of object
Definition at line 252 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getScaleFactor(), shape(), Mantid::Kernel::V3D::Z(), Mantid::Geometry::BoundingBox::zMax(), and Mantid::Geometry::BoundingBox::zMin().
getHeight()
double Mantid::Geometry::ObjComponent::getHeight () const virtual
get Height (Y-dimension) value for component
Gets the Height of the object by querying the underlying BoundingBox.
Returns
height of object
Definition at line 234 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getScaleFactor(), shape(), Mantid::Kernel::V3D::Y(), Mantid::Geometry::BoundingBox::yMax(), and Mantid::Geometry::BoundingBox::yMin().
getPointInObject()
int Mantid::Geometry::ObjComponent::getPointInObject (Kernel::V3D & point) const override virtual
Try to find a point that lies within (or on) the object.
Parameters
point :: On exit, set to the point value (if found)
Returns
1 if point found, 0 otherwise
Implements Mantid::Geometry::IObjComponent.
Definition at line 262 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getPos(), Mantid::Geometry::Component::getRotation(), Mantid::Geometry::Component::getScaleFactor(), Mantid::Kernel::Quat::rotate(), and shape().
getRelativeBoundingBox()
void Mantid::Geometry::ObjComponent::getRelativeBoundingBox (BoundingBox & RelativeBB) const private
common part of the two Bounding box functions above;
getWidth()
double Mantid::Geometry::ObjComponent::getWidth () const virtual
get Width (X-dimension) value for component
Gets the Width of the object by querying the underlying BoundingBox.
Returns
width of object
Definition at line 243 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getScaleFactor(), shape(), Mantid::Kernel::V3D::X(), Mantid::Geometry::BoundingBox::xMax(), and Mantid::Geometry::BoundingBox::xMin().
initDraw()
void Mantid::Geometry::ObjComponent::initDraw () const override virtual
Initializes the ObjComponent for rendering, this function should be called before rendering.
Implements Mantid::Geometry::IObjComponent.
Definition at line 328 of file ObjComponent.cpp.
References Mantid::Geometry::IObjComponent::Handle(), Mantid::Geometry::GeometryHandler::initialize(), and shape().
interceptSurface()
int Mantid::Geometry::ObjComponent::interceptSurface (Track & track) const override virtual
Checks whether the track given will pass through this Component.
Parameters
track :: The Track Iobject to test (N.B. Will be modified if hits are found)
Returns
The number of track segments added (i.e. 1 if the track enters and exits the Iobject once each)
Exceptions
NullPointerException if the underlying geometrical IObject has not been set
Implements Mantid::Geometry::IObjComponent.
Definition at line 104 of file ObjComponent.cpp.
References Mantid::Geometry::Track::addLink(), Mantid::Geometry::Track::cbegin(), Mantid::Geometry::Track::cend(), Mantid::Geometry::Track::direction(), Mantid::Kernel::V3D::distance(), factorOutComponentPosition(), Mantid::Geometry::Component::getPos(), Mantid::Geometry::Component::getRotation(), Mantid::Geometry::Component::getScaleFactor(), Mantid::Kernel::Quat::rotate(), shape(), Mantid::Geometry::Track::startPoint(), and takeOutRotation().
isOnSide()
bool Mantid::Geometry::ObjComponent::isOnSide (const Kernel::V3D & point) const override virtual
Does the point given lie on the surface of this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 86 of file ObjComponent.cpp.
References factorOutComponentPosition(), Mantid::Geometry::Component::getPos(), Mantid::Geometry::Component::getScaleFactor(), and shape().
isValid()
bool Mantid::Geometry::ObjComponent::isValid (const Kernel::V3D & point) const override virtual
Does the point given lie within this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 75 of file ObjComponent.cpp.
References factorOutComponentPosition(), Mantid::Geometry::Component::getPos(), Mantid::Geometry::Component::getScaleFactor(), and shape().
material()
const Kernel::Material Mantid::Geometry::ObjComponent::material () const override virtual
Return the material this component is made from.
Return the material of the component.
Currently unaffected by parametrization
Implements Mantid::Geometry::IObjComponent.
Definition at line 72 of file ObjComponent.cpp.
References m_shape.
registerContents()
size_t Mantid::Geometry::ObjComponent::registerContents (class ComponentVisitor & componentVisitor) const override virtual
Register the contents of this ObjComponent.
Implements Mantid::Geometry::IComponent.
Reimplemented in Mantid::Geometry::Detector, and Mantid::Geometry::ObjCompAssembly.
Definition at line 340 of file ObjComponent.cpp.
References Mantid::Geometry::ComponentVisitor::registerGenericObjComponent(), Mantid::Geometry::ComponentVisitor::registerInfiniteObjComponent(), and shape().
setShape()
void Mantid::Geometry::ObjComponent::setShape (std::shared_ptr< const IObject > newShape)
Set a new shape on the component void setShape(std::shared_ptr<const IObject> newShape);.
Set a new shape on the component.
Definition at line 60 of file ObjComponent.cpp.
References Mantid::Geometry::Component::m_map, and m_shape.
Referenced by ComponentCreationHelper::createEmptyInstrument(), ComponentCreationHelper::createInstrumentWithPSDTubes(), ComponentCreationHelper::createInstrumentWithSourceRotation(), Mantid::Geometry::ComponentHelper::createMinimalInstrument(), ComponentCreationHelper::createMinimalInstrument(), Mantid::Geometry::InstrumentDefinitionParser::createNeutronicInstrument(), ComponentCreationHelper::createSimpleInstrumentWithRotation(), Mantid::Geometry::ComponentHelper::createVirtualInstrument(), Mantid::DataHandling::LoadNXSPE::exec(), and ComponentCreationHelper::makeBank().
shape()
const IObject_const_sptr Mantid::Geometry::ObjComponent::shape () const override virtual
Return the shape of the component.
Implements Mantid::Geometry::IObjComponent.
Definition at line 48 of file ObjComponent.cpp.
References Mantid::Geometry::Component::base(), Mantid::Geometry::Component::m_base, Mantid::Geometry::Component::m_map, and m_shape.
Referenced by drawObject(), getBoundingBox(), getDepth(), getHeight(), getPointInObject(), getWidth(), initDraw(), interceptSurface(), isOnSide(), isValid(), registerContents(), and solidAngle().
solidAngle()
double Mantid::Geometry::ObjComponent::solidAngle (const Geometry::SolidAngleParams & params) const override virtual
Finds the approximate solid angle covered by the component when viewed from the point given.
Parameters
params :: The position from which the component is being viewed, and number of cylinder slices
Returns
The solid angle in steradians
Exceptions
NullPointerException if the underlying geometrical Object has not been set
Implements Mantid::Geometry::IObjComponent.
Definition at line 142 of file ObjComponent.cpp.
References Mantid::Geometry::ParameterMap::componentInfo(), Mantid::Geometry::SolidAngleParams::copyWithNewObserver(), factorOutComponentPosition(), Mantid::Geometry::Component::getScaleFactor(), Mantid::Geometry::Component::hasComponentInfo(), Mantid::Geometry::Component::index(), Mantid::Geometry::Component::m_map, Mantid::Geometry::SolidAngleParams::observer(), shape(), and Mantid::Geometry::ComponentInfo::solidAngle().
takeOutRotation()
const V3D Mantid::Geometry::ObjComponent::takeOutRotation (Kernel::V3D point) const protected
Rotates a point by the reverse of the component's rotation.
Definition at line 290 of file ObjComponent.cpp.
References Mantid::Geometry::Component::getRotation(), Mantid::Kernel::Quat::inverse(), and Mantid::Kernel::Quat::rotate().
Referenced by factorOutComponentPosition(), and interceptSurface().
type()
std::string Mantid::Geometry::ObjComponent::type () const inline override virtual
type string
Reimplemented from Mantid::Geometry::IObjComponent.
Definition at line 36 of file ObjComponent.h.
Member Data Documentation
m_shape
std::shared_ptr<const IObject> Mantid::Geometry::ObjComponent::m_shape protected
The physical geometry representation.
Definition at line 86 of file ObjComponent.h.
Referenced by material(), Mantid::Geometry::ObjCompAssembly::setOutline(), setShape(), and shape().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/ObjComponent.h
Framework/Geometry/src/Instrument/ObjComponent.cpp