Mantid: Mantid::Kernel::Units::Wavelength Class Reference
Mantid::Kernel::Units::Wavelength Class Reference
Wavelength in Angstrom.
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
double conversionTOFMin () const override
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"Wavelength"
Wavelength ()
Constructor.
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Protected Member Functions
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes
bool do_sfpFrom
Apply the sfpFrom value.
double efixed
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
double sfpFrom
Extra correction factor in from conversion.
double sfpTo
Extra correction factor in to conversion.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Wavelength in Angstrom.
Definition at line 302 of file Unit.h.
Constructor & Destructor Documentation
Wavelength()
Mantid::Kernel::Units::Wavelength::Wavelength ()
Constructor.
Definition at line 307 of file Unit.cpp.
References Mantid::PhysicalConstants::h, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::meVtoWavenumber, and Mantid::PhysicalConstants::NeutronMass.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::Wavelength::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 305 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::Wavelength::clone () const override virtual
Returns
a cloned instance of the other
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 420 of file Unit.cpp.
References Wavelength().
conversionTOFMax()
double Mantid::Kernel::Units::Wavelength::conversionTOFMax () const override virtual
Returns
Maximal time of flight, which can be reversively converted into wavelength
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 410 of file Unit.cpp.
References factorTo, and sfpTo.
conversionTOFMin()
double Mantid::Kernel::Units::Wavelength::conversionTOFMin () const override virtual
Returns
Minimal time of flight, which can be reversively converted into wavelength
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 402 of file Unit.cpp.
References Mantid::Kernel::Unit::emode, and sfpTo.
Referenced by Mantid::Kernel::Units::SpinEchoLength::conversionTOFMin().
init()
void Mantid::Kernel::Units::Wavelength::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 332 of file Unit.cpp.
References do_sfpFrom, Mantid::Kernel::efixed, efixed, Mantid::Kernel::Unit::emode, factorFrom, factorTo, Mantid::PhysicalConstants::h, Mantid::Kernel::Unit::l1, Mantid::Kernel::l2, Mantid::Kernel::Unit::m_params, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::NeutronMass, sfpFrom, and sfpTo.
Referenced by Mantid::Kernel::Units::SpinEchoLength::init(), and Mantid::Kernel::Units::SpinEchoTime::init().
label()
const UnitLabel Mantid::Kernel::Units::Wavelength::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 317 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::Angstrom.
singleFromTOF()
double Mantid::Kernel::Units::Wavelength::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 393 of file Unit.cpp.
References do_sfpFrom, factorFrom, sfpFrom, and Mantid::Geometry::x.
Referenced by Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::Kernel::Units::SpinEchoLength::singleFromTOF(), and Mantid::Kernel::Units::SpinEchoTime::singleFromTOF().
singleToTOF()
double Mantid::Kernel::Units::Wavelength::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Definition at line 386 of file Unit.cpp.
References Mantid::Kernel::Unit::emode, factorTo, sfpTo, and Mantid::Geometry::x.
Referenced by Mantid::Kernel::Units::SpinEchoLength::singleToTOF(), and Mantid::Kernel::Units::SpinEchoTime::singleToTOF().
unitID()
const std::string Mantid::Kernel::Units::Wavelength::unitID () const override virtual
"Wavelength"
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::SpinEchoLength, and Mantid::Kernel::Units::SpinEchoTime.
Referenced by validateUnitParams().
validateUnitParams()
void Mantid::Kernel::Units::Wavelength::validateUnitParams (const int emode, const UnitParametersMap & params) override protected virtual
Reimplemented from Mantid::Kernel::Unit.
Definition at line 319 of file Unit.cpp.
References Mantid::Kernel::efixed, Mantid::Kernel::l2, and unitID().
Member Data Documentation
do_sfpFrom
bool Mantid::Kernel::Units::Wavelength::do_sfpFrom protected
Apply the sfpFrom value.
Definition at line 326 of file Unit.h.
Referenced by init(), and singleFromTOF().
efixed
double Mantid::Kernel::Units::Wavelength::efixed protected
Definition at line 321 of file Unit.h.
Referenced by init().
factorFrom
double Mantid::Kernel::Units::Wavelength::factorFrom protected
Constant factor for from conversion.
Definition at line 325 of file Unit.h.
Referenced by init(), and singleFromTOF().
factorTo
double Mantid::Kernel::Units::Wavelength::factorTo protected
Constant factor for to conversion.
Definition at line 323 of file Unit.h.
Referenced by conversionTOFMax(), init(), and singleToTOF().
sfpFrom
double Mantid::Kernel::Units::Wavelength::sfpFrom protected
Extra correction factor in from conversion.
Definition at line 324 of file Unit.h.
Referenced by init(), and singleFromTOF().
sfpTo
double Mantid::Kernel::Units::Wavelength::sfpTo protected
Extra correction factor in to conversion.
Definition at line 322 of file Unit.h.
Referenced by conversionTOFMax(), conversionTOFMin(), init(), and singleToTOF().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp