Mantid: Mantid::API::MWDimension Class Reference
Mantid::API::MWDimension Class Reference
Public Member Functions
coord_t getBinWidth () const override
Return the bin width taking into account if the stored values are actually bin centres or not.
const std::string & getDimensionId () const override
short name which identify the dimension among other dimension.
bool getIsIntegrated () const override
if the dimension is integrated (e.g. have single bin)
coord_t getMaximum () const override
const Geometry::MDFrame & getMDFrame () const override
const Kernel::MDUnit & getMDUnits () const override
coord_t getMinimum () const override
std::string getName () const override
the name of the dimennlsion as can be displayed along the axis
size_t getNBins () const override
number of bins dimension have (an integrated has one).
size_t getNBoundaries () const override
number of bin boundaries (axis points)
const Kernel::UnitLabel getUnits () const override
coord_t getX (size_t ind) const override
Get coordinate for index;.
MWDimension (const Axis *axis, std::string dimensionId)
void setRange (size_t, coord_t, coord_t) override
Change the extents and number of bins.
std::string toXMLString () const override
Public Member Functions inherited from Mantid::Geometry::IMDDimension
bool operator!= (const IMDDimension &) const
bool operator== (const IMDDimension &) const
virtual ~IMDDimension ()=default
Destructor.
Private Attributes
const Axis & m_axis
const std::string m_dimensionId
const Geometry::MDFrame_const_uptr m_frame
const bool m_haveEdges
Detailed Description
Definition at line 1494 of file MatrixWorkspace.cpp.
Constructor & Destructor Documentation
MWDimension()
Mantid::API::MWDimension::MWDimension (const Axis * axis, std::string dimensionId) inline
Definition at line 1496 of file MatrixWorkspace.cpp.
Member Function Documentation
getBinWidth()
coord_t Mantid::API::MWDimension::getBinWidth () const inline override virtual
Return the bin width taking into account if the stored values are actually bin centres or not.
Returns
A single value for the uniform bin width
Reimplemented from Mantid::Geometry::IMDDimension.
Definition at line 1552 of file MatrixWorkspace.cpp.
References getMaximum(), getMinimum(), getNBins(), and m_haveEdges.
getDimensionId()
const std::string & Mantid::API::MWDimension::getDimensionId () const inline override virtual
short name which identify the dimension among other dimension.
A dimension can be usually find by its ID and various various method exist to manipulate set of dimensions by their names.
Implements Mantid::Geometry::IMDDimension.
Definition at line 1516 of file MatrixWorkspace.cpp.
References m_dimensionId.
getIsIntegrated()
bool Mantid::API::MWDimension::getIsIntegrated () const inline override virtual
if the dimension is integrated (e.g. have single bin)
Reimplemented from Mantid::Geometry::IMDDimension.
Definition at line 1519 of file MatrixWorkspace.cpp.
References Mantid::API::Axis::length(), and m_axis.
getMaximum()
coord_t Mantid::API::MWDimension::getMaximum () const inline override virtual
Returns
the maximum extent of this dimension
Implements Mantid::Geometry::IMDDimension.
Definition at line 1525 of file MatrixWorkspace.cpp.
References Mantid::API::Axis::getMax(), and m_axis.
Referenced by getBinWidth().
getMDFrame()
const Geometry::MDFrame & Mantid::API::MWDimension::getMDFrame () const inline override virtual
Returns
the MDFrame
Implements Mantid::Geometry::IMDDimension.
Definition at line 1561 of file MatrixWorkspace.cpp.
References m_frame.
getMDUnits()
const Kernel::MDUnit & Mantid::API::MWDimension::getMDUnits () const inline override virtual
Returns
the mdunits of the dimension
Implements Mantid::Geometry::IMDDimension.
Definition at line 1560 of file MatrixWorkspace.cpp.
References m_frame.
getMinimum()
coord_t Mantid::API::MWDimension::getMinimum () const inline override virtual
Returns
the minimum extent of this dimension
Implements Mantid::Geometry::IMDDimension.
Definition at line 1522 of file MatrixWorkspace.cpp.
References Mantid::API::Axis::getMin(), and m_axis.
Referenced by getBinWidth().
getName()
std::string Mantid::API::MWDimension::getName () const inline override virtual
the name of the dimennlsion as can be displayed along the axis
Implements Mantid::Geometry::IMDDimension.
Definition at line 1502 of file MatrixWorkspace.cpp.
References m_axis, Mantid::API::Axis::title(), and Mantid::API::Axis::unit().
getNBins()
size_t Mantid::API::MWDimension::getNBins () const inline override virtual
number of bins dimension have (an integrated has one).
A axis directed along dimension would have getNBins+1 axis points.
Implements Mantid::Geometry::IMDDimension.
Definition at line 1529 of file MatrixWorkspace.cpp.
References Mantid::API::Axis::length(), m_axis, and m_haveEdges.
Referenced by getBinWidth().
getNBoundaries()
size_t Mantid::API::MWDimension::getNBoundaries () const inline override virtual
number of bin boundaries (axis points)
Implements Mantid::Geometry::IMDDimension.
Definition at line 1537 of file MatrixWorkspace.cpp.
References Mantid::API::Axis::length(), and m_axis.
getUnits()
const Kernel::UnitLabel Mantid::API::MWDimension::getUnits () const inline override virtual
Returns
the units of the dimension as a string
Implements Mantid::Geometry::IMDDimension.
Definition at line 1511 of file MatrixWorkspace.cpp.
References m_axis, and Mantid::API::Axis::unit().
getX()
coord_t Mantid::API::MWDimension::getX (size_t ind) const inline override virtual
Get coordinate for index;.
Implements Mantid::Geometry::IMDDimension.
Definition at line 1545 of file MatrixWorkspace.cpp.
References m_axis.
setRange()
void Mantid::API::MWDimension::setRange (size_t , coord_t , coord_t) inline override virtual
Change the extents and number of bins.
Implements Mantid::Geometry::IMDDimension.
Definition at line 1540 of file MatrixWorkspace.cpp.
toXMLString()
std::string Mantid::API::MWDimension::toXMLString () const inline override virtual
Returns
an XML string representation of the dimension.
Implements Mantid::Geometry::IMDDimension.
Definition at line 1558 of file MatrixWorkspace.cpp.
Member Data Documentation
m_axis
const Axis& Mantid::API::MWDimension::m_axis private
Definition at line 1564 of file MatrixWorkspace.cpp.
Referenced by getIsIntegrated(), getMaximum(), getMinimum(), getName(), getNBins(), getNBoundaries(), getUnits(), and getX().
m_dimensionId
const std::string Mantid::API::MWDimension::m_dimensionId private
Definition at line 1565 of file MatrixWorkspace.cpp.
Referenced by getDimensionId().
m_frame
const Geometry::MDFrame_const_uptr Mantid::API::MWDimension::m_frame private
Definition at line 1567 of file MatrixWorkspace.cpp.
Referenced by getMDFrame(), and getMDUnits().
m_haveEdges
const bool Mantid::API::MWDimension::m_haveEdges private
Definition at line 1566 of file MatrixWorkspace.cpp.
Referenced by getBinWidth(), and getNBins().
The documentation for this class was generated from the following file:
Framework/API/src/MatrixWorkspace.cpp