Mantid: ICat4::ns1__loginResponse Class Reference
ICat4::ns1__loginResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__loginResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 980 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__loginResponse()
ICat4::ns1__loginResponse::ns1__loginResponse () inline
Definition at line 996 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__loginResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18314 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::ICATPortBindingProxy::login(), ICat4::soap_in_ns1__loginResponse(), ICat4::soap_new_req_ns1__loginResponse(), and ICat4::soap_new_set_ns1__loginResponse().
soap_get()
void * ICat4::ns1__loginResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18405 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__loginResponse().
Referenced by ICat4::ICATPortBindingProxy::login().
soap_in()
void * ICat4::ns1__loginResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18343 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__loginResponse().
Referenced by ICat4::soap_in_ns1__loginResponse().
soap_out()
int ICat4::ns1__loginResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18328 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__loginResponse().
Referenced by soap_put().
soap_put()
int ICat4::ns1__loginResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18398 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__loginResponse.
soap_serialize()
void ICat4::ns1__loginResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18320 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__login().
soap_type()
int ICat4::ns1__loginResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 989 of file ICat4Stub.h.
Member Data Documentation
return_
std::string* ICat4::ns1__loginResponse::return_
Definition at line 982 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::login(), soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp