Mantid: MantidQt::CustomDialogs::InputWorkspaceWidget Class Reference
MantidQt::CustomDialogs::InputWorkspaceWidget Class Reference
Widget for inputting workspace information.
#include <FitDialog.h>
Public Member Functions
QStringList getAllowedPropertyValues (const QString &propName) const
Get allowed values for a property.
int getDomainIndex () const
Return the domain index.
int getDomainType () const
Get the domain type: Simple, Sequential, or Parallel.
QString getStoredPropertyValue (const QString &propName) const
Return property value stored in history.
QString getWorkspaceName () const
Get workspace name.
InputWorkspaceWidget (FitDialog *parent, int domainIndex=0)
Constructor.
void setProperties ()
Set all workspace properties.
void setPropertyValue (const QString &propName, const QString &propValue)
Set a property.
void setWorkspaceName (const QString &wsName)
Set workspace name.
Protected Slots
void setDynamicProperties ()
Set the dynamic properties.
Protected Member Functions
bool isMatrixWorkspace () const
Is the workspace MW?
bool isMDWorkspace () const
Is the workspace MD?
bool isWorkspaceSupported () const
is current workspace supported by Fit?
bool isWSNameSet () const
Is ws name set?
Protected Attributes
int m_domainIndex
In multidomain fitting it is index of domain created from this workspace In single domain case == 0.
DynamicPropertiesWidget * m_dynamicProperties
Dynamic propeties widget.
FitDialog * m_fitDialog
Parent FitDialog.
QVBoxLayout * m_layout
The main layout.
QComboBox * m_workspaceName
Workspace name widget.
QString m_wsPropName
Name of the property for the input workspace.
Detailed Description
Widget for inputting workspace information.
Definition at line 102 of file FitDialog.h.
Constructor & Destructor Documentation
InputWorkspaceWidget()
MantidQt::CustomDialogs::InputWorkspaceWidget::InputWorkspaceWidget (FitDialog * parent, int domainIndex = 0)
Constructor.
Parameters
parent :: Parent dialog.
domainIndex Number that allows to identify the InputWorkspace formed with the followin rule InputWorkspace_[domainIndex]
Definition at line 47 of file FitDialog.cpp.
Member Function Documentation
getAllowedPropertyValues()
QStringList MantidQt::CustomDialogs::InputWorkspaceWidget::getAllowedPropertyValues (const QString & propName) const inline
Get allowed values for a property.
Definition at line 110 of file FitDialog.h.
References MantidQt::CustomDialogs::FitDialog::getAllowedPropertyValues(), and m_fitDialog.
getDomainIndex()
int MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainIndex () const inline
Return the domain index.
Definition at line 118 of file FitDialog.h.
References m_domainIndex.
Referenced by MantidQt::CustomDialogs::MWPropertiesWidget::setProperties(), and MantidQt::CustomDialogs::MDPropertiesWidget::setProperties().
getDomainType()
int MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainType () const inline
Get the domain type: Simple, Sequential, or Parallel.
Definition at line 124 of file FitDialog.h.
References MantidQt::CustomDialogs::FitDialog::getDomainType(), and m_fitDialog.
Referenced by MantidQt::CustomDialogs::MDPropertiesWidget::MDPropertiesWidget(), MantidQt::CustomDialogs::MWPropertiesWidget::MWPropertiesWidget(), MantidQt::CustomDialogs::MWPropertiesWidget::setProperties(), and MantidQt::CustomDialogs::MDPropertiesWidget::setProperties().
getStoredPropertyValue()
QString MantidQt::CustomDialogs::InputWorkspaceWidget::getStoredPropertyValue (const QString & propName) const inline
Return property value stored in history.
Definition at line 108 of file FitDialog.h.
References MantidQt::API::AlgorithmDialog::getPreviousValue(), and m_fitDialog.
getWorkspaceName()
QString MantidQt::CustomDialogs::InputWorkspaceWidget::getWorkspaceName () const
Get workspace name.
Definition at line 138 of file FitDialog.cpp.
References m_workspaceName.
Referenced by MantidQt::CustomDialogs::FitDialog::createInputWorkspaceWidgets(), MantidQt::CustomDialogs::MWPropertiesWidget::MWPropertiesWidget(), and setProperties().
isMatrixWorkspace()
bool MantidQt::CustomDialogs::InputWorkspaceWidget::isMatrixWorkspace () const protected
Is the workspace MW?
Definition at line 74 of file FitDialog.cpp.
References m_workspaceName.
Referenced by isWorkspaceSupported(), and setDynamicProperties().
isMDWorkspace()
bool MantidQt::CustomDialogs::InputWorkspaceWidget::isMDWorkspace () const protected
Is the workspace MD?
Definition at line 89 of file FitDialog.cpp.
References m_workspaceName.
Referenced by isWorkspaceSupported(), and setDynamicProperties().
isWorkspaceSupported()
bool MantidQt::CustomDialogs::InputWorkspaceWidget::isWorkspaceSupported () const protected
is current workspace supported by Fit?
Is current workspace supported by Fit?
Definition at line 104 of file FitDialog.cpp.
References isMatrixWorkspace(), and isMDWorkspace().
Referenced by setProperties().
isWSNameSet()
bool MantidQt::CustomDialogs::InputWorkspaceWidget::isWSNameSet () const protected
Is ws name set?
Definition at line 66 of file FitDialog.cpp.
References m_workspaceName.
Referenced by setDynamicProperties().
setDynamicProperties
void MantidQt::CustomDialogs::InputWorkspaceWidget::setDynamicProperties () protected slot
Set the dynamic properties.
Definition at line 109 of file FitDialog.cpp.
References isMatrixWorkspace(), MantidQt::CustomDialogs::FitDialog::isMD(), isMDWorkspace(), isWSNameSet(), m_dynamicProperties, m_fitDialog, and m_layout.
setProperties()
void MantidQt::CustomDialogs::InputWorkspaceWidget::setProperties ()
Set all workspace properties.
Definition at line 163 of file FitDialog.cpp.
References getWorkspaceName(), isWorkspaceSupported(), m_dynamicProperties, m_wsPropName, MantidQt::CustomDialogs::DynamicPropertiesWidget::setProperties(), and setPropertyValue().
Referenced by MantidQt::CustomDialogs::FitDialog::parseInput().
setPropertyValue()
void MantidQt::CustomDialogs::InputWorkspaceWidget::setPropertyValue (const QString & propName, const QString & propValue)
Set a property.
Parameters
propName :: Property name
propValue :: Property value
Definition at line 153 of file FitDialog.cpp.
References MantidQt::API::AlgorithmDialog::getAlgorithm(), m_fitDialog, and MantidQt::API::AlgorithmDialog::storePropertyValue().
Referenced by setProperties(), MantidQt::CustomDialogs::MWPropertiesWidget::setProperties(), and MantidQt::CustomDialogs::MDPropertiesWidget::setProperties().
setWorkspaceName()
void MantidQt::CustomDialogs::InputWorkspaceWidget::setWorkspaceName (const QString & wsName)
Set workspace name.
Definition at line 141 of file FitDialog.cpp.
References m_workspaceName.
Referenced by MantidQt::CustomDialogs::FitDialog::setWorkspaceName().
Member Data Documentation
m_domainIndex
int MantidQt::CustomDialogs::InputWorkspaceWidget::m_domainIndex protected
In multidomain fitting it is index of domain created from this workspace In single domain case == 0.
Definition at line 143 of file FitDialog.h.
Referenced by getDomainIndex().
m_dynamicProperties
DynamicPropertiesWidget* MantidQt::CustomDialogs::InputWorkspaceWidget::m_dynamicProperties protected
Dynamic propeties widget.
Definition at line 149 of file FitDialog.h.
Referenced by setDynamicProperties(), and setProperties().
m_fitDialog
FitDialog* MantidQt::CustomDialogs::InputWorkspaceWidget::m_fitDialog protected
Parent FitDialog.
Definition at line 140 of file FitDialog.h.
Referenced by getAllowedPropertyValues(), getDomainType(), getStoredPropertyValue(), setDynamicProperties(), and setPropertyValue().
m_layout
QVBoxLayout* MantidQt::CustomDialogs::InputWorkspaceWidget::m_layout protected
The main layout.
Definition at line 152 of file FitDialog.h.
Referenced by setDynamicProperties().
m_workspaceName
QComboBox* MantidQt::CustomDialogs::InputWorkspaceWidget::m_workspaceName protected
Workspace name widget.
Definition at line 147 of file FitDialog.h.
Referenced by getWorkspaceName(), isMatrixWorkspace(), isMDWorkspace(), isWSNameSet(), and setWorkspaceName().
m_wsPropName
QString MantidQt::CustomDialogs::InputWorkspaceWidget::m_wsPropName protected
Name of the property for the input workspace.
Definition at line 145 of file FitDialog.h.
Referenced by setProperties().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/FitDialog.h
qt/widgets/plugins/algorithm_dialogs/src/FitDialog.cpp