Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames Namespace Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames Namespace Reference
Functions
const std::string DETID ("event_id")
const std::string INDEX_ID ("event_index")
const std::string TIME_OF_FLIGHT ("event_time_offset")
Function Documentation
DETID()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::DETID ("event_id")
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().
INDEX_ID()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::INDEX_ID ("event_index")
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::NexusLoader::loadEventIndex().
TIME_OF_FLIGHT()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::TIME_OF_FLIGHT ("event_time_offset")
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().