Mantid: Mantid::Geometry::ICompAssembly Class Reference
Mantid::Geometry::ICompAssembly Class Reference abstract
Class for Assembly of geometric components.
#include <ICompAssembly.h>
Public Member Functions
virtual int add (IComponent *)=0
Add a component to the assembly.
virtual int addCopy (IComponent *)=0
Add a copy (clone) of a component.
virtual int addCopy (IComponent *, const std::string &)=0
Add a copy (clone) of a component and rename it.
IComponent * clone () const override=0
Make a clone of the present component.
virtual std::shared_ptr< IComponent > getChild (const int i) const =0
Get a pointer to the ith component within the assembly.
virtual void getChildren (std::vector< IComponent_const_sptr > &outVector, bool recursive) const =0
Get all children.
virtual std::shared_ptr< const IComponent > getComponentByName (const std::string &cname, int nlevels=0) const =0
Returns a pointer to the first component of assembly encountered with the given name.
ICompAssembly ()
virtual int nelements () const =0
Return the number of elements in the assembly.
virtual std::shared_ptr< IComponent > operator[] (int i) const =0
Overloaded index operator.
virtual void printChildren (std::ostream &) const =0
Print information about all children.
virtual void printTree (std::ostream &) const =0
Print information about all the elements in the tree to a stream Loops through all components in the tree and call printSelf(os).
virtual void testIntersectionWithChildren (Track &testRay, std::deque< IComponent_const_sptr > &searchQueue) const =0
Test the intersection of the ray with the children of the component assembly.
std::string type () const override
String description of the type of component.
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual IComponent * clone () const =0
Return a clone to the current object.
virtual std::vector< std::shared_ptr< const IComponent > > getAncestors () const =0
Return an array of all ancestors, the nearest first.
virtual const IComponent * getBareParent () const =0
Returns the bare pointer to the IComponent parent.
virtual IComponent const * getBaseComponent () const =0
Returns const pointer to base component if this component is parametrized.
virtual void getBoundingBox (BoundingBox &boundingBox) const =0
Get the bounding box for this component and store it in the given argument.
virtual ComponentID getComponentID () const =0
Returns the ComponentID - a unique identifier of the component.
virtual double getDistance (const IComponent &) const =0
Get the distance to another IComponent.
virtual std::string getFullName () const =0
Get the IComponent full path name.
virtual std::string getName () const =0
Get the IComponent name.
virtual std::shared_ptr< const IComponent > getParent () const =0
Return a pointer to the current parent.
virtual Kernel::V3D getPos () const =0
Get the position of the IComponent. Tree structure is traverse through the.
virtual Kernel::V3D getRelativePos () const =0
Get the position relative to the parent IComponent (absolute if no parent)
virtual Kernel::Quat getRelativeRot () const =0
Get the relative Orientation.
virtual Kernel::Quat getRotation () const =0
Get the absolute orientation of the IComponent.
virtual Kernel::V3D getScaleFactor () const
Gets the scaling factor of the object for the Object Component.
virtual void rotate (const Kernel::Quat &)=0
Rotate the IComponent. This is relative to parent.
virtual void rotate (double, const Kernel::V3D &)=0
Rotate the IComponent by an angle in degrees with respect to an axis.
virtual void setName (const std::string &)=0
Set the IComponent name.
virtual void setParent (IComponent *)=0
Assign a parent IComponent. Previous parent link is lost.
virtual void setPos (const Kernel::V3D &)=0
Set the position of the component The position is with respect to the parent component.
virtual void setPos (double, double, double)=0
Set the IComponent position, x, y, z respective to parent (if present)
virtual void setRot (const Kernel::Quat &)=0
Set the orientation Kernel::Quaternion relative to parent (if present)
virtual void translate (const Kernel::V3D &)=0
Copy the Rotation from another IComponent.
virtual void translate (double, double, double)=0
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string type () const
Returns a string representation of the IComponent type.
virtual ~IComponent ()=default
Destructor.
virtual std::set< std::string > getParameterNames (bool recursive=true) const =0
Return the names of the parameters for this component.
virtual std::map< std::string, ComponentID > getParameterNamesByComponent () const =0
return the parameter names and the component they are from
virtual bool hasParameter (const std::string &name, bool recursive=true) const =0
Returns a boolean indicating if the component has the named parameter.
virtual std::string getParameterType (const std::string &pname, bool recursive=true) const =0
virtual std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a double.
virtual std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a Kernel::V3D.
virtual std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a Kernel::Quaternion.
virtual std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a string.
virtual std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as an integer.
virtual std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a boolean.
virtual std::string getParameterAsString (const std::string &pname, bool recursive=true) const =0
get a string representation of a parameter
virtual bool getParameterVisible (const std::string &pname, bool recursive=true) const =0
get visibility attribute of a parameter
virtual void printSelf (std::ostream &) const =0
Prints a text representation of itself.
virtual bool isParametrized () const =0
Returns true if the Component is parametrized (has a parameter map)
virtual size_t registerContents (class ComponentVisitor &component) const =0
Protected Member Functions
ICompAssembly (const ICompAssembly &)=default
Protected copy constructor.
Private Member Functions
ICompAssembly & operator= (const ICompAssembly &)=delete
Detailed Description
Class for Assembly of geometric components.
Version
A
Author
Laurent C Chapon, ISIS RAL
Date
01/11/2007
CompAssembly allows Components to be positioned in a hierarchical structure in the form of a tree. CompAssembly inherits from component.
Definition at line 30 of file ICompAssembly.h.
Constructor & Destructor Documentation
ICompAssembly() [1/2]
Mantid::Geometry::ICompAssembly::ICompAssembly () inline
Definition at line 34 of file ICompAssembly.h.
ICompAssembly() [2/2]
Mantid::Geometry::ICompAssembly::ICompAssembly (const ICompAssembly &) protected default
Protected copy constructor.
Member Function Documentation
add()
virtual int Mantid::Geometry::ICompAssembly::add (IComponent *) pure virtual
Add a component to the assembly.
Implemented in Mantid::Geometry::CompAssembly, Mantid::Geometry::ObjCompAssembly, and Mantid::Geometry::Instrument.
Referenced by Mantid::Geometry::InstrumentDefinitionParser::appendLeaf(), Mantid::Geometry::CompAssembly::CompAssembly(), Mantid::Geometry::InstrumentDefinitionParser::createDetectorOrMonitor(), Mantid::Geometry::InstrumentDefinitionParser::getAbsolutPositionInCompCoorSys(), and Mantid::Geometry::ObjCompAssembly::ObjCompAssembly().
addCopy() [1/2]
virtual int Mantid::Geometry::ICompAssembly::addCopy (IComponent *) pure virtual
Add a copy (clone) of a component.
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
addCopy() [2/2]
virtual int Mantid::Geometry::ICompAssembly::addCopy (IComponent * , const std::string &) pure virtual
Add a copy (clone) of a component and rename it.
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
clone()
IComponent * Mantid::Geometry::ICompAssembly::clone () const override pure virtual
Make a clone of the present component.
Implements Mantid::Geometry::IComponent.
Implemented in Mantid::Geometry::Instrument, Mantid::Geometry::CompAssembly, Mantid::Geometry::GridDetector, Mantid::Geometry::ObjCompAssembly, Mantid::Geometry::RectangularDetector, and Mantid::Geometry::StructuredDetector.
getChild()
virtual std::shared_ptr< IComponent > Mantid::Geometry::ICompAssembly::getChild (const int i) const pure virtual
Get a pointer to the ith component within the assembly.
Easier to use than [] when you have a pointer
Implemented in Mantid::Geometry::Instrument, Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
getChildren()
virtual void Mantid::Geometry::ICompAssembly::getChildren (std::vector< IComponent_const_sptr > & outVector, bool recursive) const pure virtual
Get all children.
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
Referenced by Mantid::Geometry::Instrument::getDetectorsInBank(), and Mantid::Geometry::InstrumentVisitor::registerComponentAssembly().
getComponentByName()
virtual std::shared_ptr< const IComponent > Mantid::Geometry::ICompAssembly::getComponentByName (const std::string & cname, int nlevels = 0) const pure virtual
Returns a pointer to the first component of assembly encountered with the given name.
Implemented in Mantid::Geometry::CompAssembly, Mantid::Geometry::GridDetector, Mantid::Geometry::ObjCompAssembly, and Mantid::Geometry::StructuredDetector.
nelements()
virtual int Mantid::Geometry::ICompAssembly::nelements () const pure virtual
Return the number of elements in the assembly.
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
Referenced by export_ICompAssembly().
operator=()
ICompAssembly & Mantid::Geometry::ICompAssembly::operator= (const ICompAssembly &) private delete
operator[]()
virtual std::shared_ptr< IComponent > Mantid::Geometry::ICompAssembly::operator[] (int i) const pure virtual
Overloaded index operator.
Get a pointer to the ith component in the assembly
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
printChildren()
virtual void Mantid::Geometry::ICompAssembly::printChildren (std::ostream &) const pure virtual
Print information about all children.
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
printTree()
virtual void Mantid::Geometry::ICompAssembly::printTree (std::ostream &) const pure virtual
Print information about all the elements in the tree to a stream Loops through all components in the tree and call printSelf(os).
Implemented in Mantid::Geometry::CompAssembly, and Mantid::Geometry::ObjCompAssembly.
testIntersectionWithChildren()
virtual void Mantid::Geometry::ICompAssembly::testIntersectionWithChildren (Track & testRay, std::deque< IComponent_const_sptr > & searchQueue) const pure virtual
Test the intersection of the ray with the children of the component assembly.
Implemented in Mantid::Geometry::ObjCompAssembly, Mantid::Geometry::CompAssembly, Mantid::Geometry::GridDetector, and Mantid::Geometry::RectangularDetector.
type()
std::string Mantid::Geometry::ICompAssembly::type () const inline override virtual
String description of the type of component.
Reimplemented from Mantid::Geometry::IComponent.
Reimplemented in Mantid::Geometry::Instrument, Mantid::Geometry::CompAssembly, Mantid::Geometry::GridDetector, Mantid::Geometry::ObjCompAssembly, Mantid::Geometry::RectangularDetector, and Mantid::Geometry::StructuredDetector.
Definition at line 36 of file ICompAssembly.h.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/ICompAssembly.h