Mantid: Mantid::MDAlgorithms::CellCoords Struct Reference
Mantid::MDAlgorithms::CellCoords Struct Reference
Partition QLab space into a cubic lattice.
#include <IntegrateQLabEvents.h>
Public Member Functions
CellCoords (const V3D &q, const double cellSize)
int64_t getHash ()
cast coordinates to scalar, to be used as key in an unordered map
bool isOrigin ()
Check if all cell coords are zero.
std::vector< int64_t > nearbyCellHashes ()
Hashes for the 26 first neighbor coordinates plus the coordinates themselves.
Public Attributes
int64_t a
int64_t b
int64_t c
Detailed Description
Partition QLab space into a cubic lattice.
Definition at line 33 of file IntegrateQLabEvents.h.
Constructor & Destructor Documentation
CellCoords()
Mantid::MDAlgorithms::CellCoords::CellCoords (const V3D & q, const double cellSize) inline
Definition at line 38 of file IntegrateQLabEvents.h.
Member Function Documentation
getHash()
int64_t Mantid::MDAlgorithms::CellCoords::getHash () inline
cast coordinates to scalar, to be used as key in an unordered map
Definition at line 46 of file IntegrateQLabEvents.h.
References a, b, and c.
Referenced by Mantid::MDAlgorithms::IntegrateQLabEvents::addEvent(), Mantid::MDAlgorithms::IntegrateQLabEvents::ellipseIntegrateEvents(), and Mantid::MDAlgorithms::IntegrateQLabEvents::IntegrateQLabEvents().
isOrigin()
bool Mantid::MDAlgorithms::CellCoords::isOrigin () inline
Check if all cell coords are zero.
Definition at line 43 of file IntegrateQLabEvents.h.
References a, b, and c.
Referenced by Mantid::MDAlgorithms::IntegrateQLabEvents::addEvent(), and Mantid::MDAlgorithms::IntegrateQLabEvents::IntegrateQLabEvents().
nearbyCellHashes()
std::vector< int64_t > Mantid::MDAlgorithms::CellCoords::nearbyCellHashes () inline
Hashes for the 26 first neighbor coordinates plus the coordinates themselves.
Definition at line 50 of file IntegrateQLabEvents.h.
References a, b, and c.
Referenced by Mantid::MDAlgorithms::IntegrateQLabEvents::populateCellsWithPeaks().
Member Data Documentation
a
int64_t Mantid::MDAlgorithms::CellCoords::a
Definition at line 34 of file IntegrateQLabEvents.h.
Referenced by getHash(), isOrigin(), and nearbyCellHashes().
b
int64_t Mantid::MDAlgorithms::CellCoords::b
Definition at line 35 of file IntegrateQLabEvents.h.
Referenced by getHash(), isOrigin(), and nearbyCellHashes().
c
int64_t Mantid::MDAlgorithms::CellCoords::c
Definition at line 36 of file IntegrateQLabEvents.h.
Referenced by getHash(), isOrigin(), and nearbyCellHashes().
The documentation for this struct was generated from the following file:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegrateQLabEvents.h