Mantid: Framework/Nexus/src/NexusAddress.cpp File Reference
NexusAddress.cpp File Reference
#include "MantidNexus/NexusAddress.h"
Namespaces
namespace Mantid
Helper class which provides the Collimation Length for SANS instruments.
namespace Mantid::Nexus
Header for a base Nexus::Exception.
Functions
bool operator!= (std::string const &s, Mantid::Nexus::NexusAddress const &p)
std::string operator+ (char const s[], Mantid::Nexus::NexusAddress const &p)
std::string operator+ (std::string const &s, Mantid::Nexus::NexusAddress const &p)
std::ostream & operator<< (std::ostream &os, Mantid::Nexus::NexusAddress const &p)
bool operator== (std::string const &s, Mantid::Nexus::NexusAddress const &p)
Function Documentation
operator!=()
bool operator!= (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 108 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator+() [1/2]
std::string operator+ (char const s[], Mantid::Nexus::NexusAddress const & p)
Definition at line 112 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator+() [2/2]
std::string operator+ (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 110 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator<<()
std::ostream & operator<< (std::ostream & os, Mantid::Nexus::NexusAddress const & p)
Definition at line 114 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator==()
bool operator== (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 106 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().