Mantid: Mantid::Crystal::CompositeCluster Class Reference
Mantid::Crystal::CompositeCluster Class Reference
CompositeCluster : Cluster made by by merging other IClusters.
#include <CompositeCluster.h>
Public Member Functions
void add (std::shared_ptr< ICluster > &toOwn)
Own.
void addIndex (const size_t &index) override
Track a linear IMDHistoWorkspace index that belongs to the cluster.
CompositeCluster ()=default
CompositeCluster (const CompositeCluster &)=delete
bool containsLabel (const size_t &label) const override
Is a given label part of this cluster.
size_t getLabel () const override
Get the cluster label.
size_t getOriginalLabel () const override
Original label.
size_t getRepresentitiveIndex () const override
Get a representative index of the cluster.
ICluster::ClusterIntegratedValues integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const override
integrate the cluster
CompositeCluster & operator= (const CompositeCluster &)=delete
void setRootCluster (ICluster const *root) override
Set the root cluster.
size_t size () const override
Number of indexes tracked.
void toUniformMinimum (std::vector< DisjointElement > &disjointSet) override
Resolve the proper label for this cluster.
void writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const override
Apply labels to the workspace.
Public Member Functions inherited from Mantid::Crystal::ICluster
virtual ~ICluster ()=default
Virtual destructor.
Private Member Functions
void findMinimum () const
Helper method to find the minimum label.
Private Attributes
std::optional< size_t > m_label
Label used by cluster.
std::vector< std::shared_ptr< ICluster > > m_ownedClusters
Attached clusters.
Additional Inherited Members
Public Types inherited from Mantid::Crystal::ICluster
using ClusterIntegratedValues = boost::tuple< double, double >
Detailed Description
CompositeCluster : Cluster made by by merging other IClusters.
Definition at line 19 of file CompositeCluster.h.
Constructor & Destructor Documentation
CompositeCluster() [1/2]
Mantid::Crystal::CompositeCluster::CompositeCluster () default
CompositeCluster() [2/2]
Mantid::Crystal::CompositeCluster::CompositeCluster (const CompositeCluster &) delete
Member Function Documentation
add()
void Mantid::Crystal::CompositeCluster::add (std::shared_ptr< ICluster > & toOwn)
Own.
Add other IClusters to own.
Parameters
toOwn : Item to own
Definition at line 157 of file CompositeCluster.cpp.
References m_ownedClusters.
addIndex()
void Mantid::Crystal::CompositeCluster::addIndex (const size_t & index) override virtual
Track a linear IMDHistoWorkspace index that belongs to the cluster.
Add an index. This method does not apply to composite clusters.
Implements Mantid::Crystal::ICluster.
Definition at line 90 of file CompositeCluster.cpp.
containsLabel()
bool Mantid::Crystal::CompositeCluster::containsLabel (const size_t & label) const override virtual
Is a given label part of this cluster.
Does this cluster contain the label of the argument.
Parameters
label : Label id to find
Returns
True only if that label is contained.
Implements Mantid::Crystal::ICluster.
Definition at line 169 of file CompositeCluster.cpp.
References m_ownedClusters.
findMinimum()
void Mantid::Crystal::CompositeCluster::findMinimum () const private
Helper method to find the minimum label.
Find the minimum label in the composite.
Definition at line 97 of file CompositeCluster.cpp.
References Mantid::Crystal::ICluster::getLabel(), m_label, and m_ownedClusters.
Referenced by getLabel().
getLabel()
size_t Mantid::Crystal::CompositeCluster::getLabel () const override virtual
Get the cluster label.
Get the label.
Returns
Current label.
Implements Mantid::Crystal::ICluster.
Definition at line 64 of file CompositeCluster.cpp.
References findMinimum(), and m_label.
Referenced by getOriginalLabel().
getOriginalLabel()
size_t Mantid::Crystal::CompositeCluster::getOriginalLabel () const override virtual
Original label.
Get the original label.
Doesn't make sense for composites, so wired through to getLabel()
Returns
getLabel()
Implements Mantid::Crystal::ICluster.
Definition at line 78 of file CompositeCluster.cpp.
References getLabel().
getRepresentitiveIndex()
size_t Mantid::Crystal::CompositeCluster::getRepresentitiveIndex () const override virtual
Get a representative index of the cluster.
Get any representative index from this cluster.
Returns
: Representative index.
Implements Mantid::Crystal::ICluster.
Definition at line 139 of file CompositeCluster.cpp.
References m_ownedClusters.
integrate()
ICluster::ClusterIntegratedValues Mantid::Crystal::CompositeCluster::integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const override virtual
integrate the cluster
Integrate the composite cluster.
Parameters
ws : Workspace to integrate
Returns
Integrated signal and error sq values.
Implements Mantid::Crystal::ICluster.
Definition at line 37 of file CompositeCluster.cpp.
References m_ownedClusters.
operator=()
CompositeCluster & Mantid::Crystal::CompositeCluster::operator= (const CompositeCluster &) delete
setRootCluster()
void Mantid::Crystal::CompositeCluster::setRootCluster (ICluster const * root) override virtual
Set the root cluster.
Parameters
root : Root cluster to use
Implements Mantid::Crystal::ICluster.
Definition at line 147 of file CompositeCluster.cpp.
References m_ownedClusters.
size()
size_t Mantid::Crystal::CompositeCluster::size () const override virtual
Number of indexes tracked.
Get the size of the composite.
This is the total size of all owned clusters.
Returns
total size.
Implements Mantid::Crystal::ICluster.
Definition at line 84 of file CompositeCluster.cpp.
References m_ownedClusters.
toUniformMinimum()
void Mantid::Crystal::CompositeCluster::toUniformMinimum (std::vector< DisjointElement > & disjointSet) override virtual
Resolve the proper label for this cluster.
Convert the disjointSet to a uniform minimum value.
Parameters
disjointSet : DisjointSets to adapt.
Implements Mantid::Crystal::ICluster.
Definition at line 115 of file CompositeCluster.cpp.
References Mantid::Crystal::ICluster::getLabel(), m_label, m_ownedClusters, and Mantid::Crystal::ICluster::setRootCluster().
writeTo()
void Mantid::Crystal::CompositeCluster::writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const override virtual
Apply labels to the workspace.
Write to an output histo workspace.
Parameters
ws
Implements Mantid::Crystal::ICluster.
Definition at line 54 of file CompositeCluster.cpp.
References m_ownedClusters.
Member Data Documentation
m_label
std::optional<size_t> Mantid::Crystal::CompositeCluster::m_label mutable private
Label used by cluster.
Definition at line 64 of file CompositeCluster.h.
Referenced by findMinimum(), getLabel(), and toUniformMinimum().
m_ownedClusters
std::vector<std::shared_ptr<ICluster> > Mantid::Crystal::CompositeCluster::m_ownedClusters private
Attached clusters.
Definition at line 66 of file CompositeCluster.h.
Referenced by add(), containsLabel(), findMinimum(), getRepresentitiveIndex(), integrate(), setRootCluster(), size(), toUniformMinimum(), and writeTo().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/CompositeCluster.h
Framework/Crystal/src/CompositeCluster.cpp