Mantid: boost::algorithm Namespace Reference
boost::algorithm Namespace Reference
Namespaces
namespace detail
Functions
template<class InputIterator1 , class InputIterator2 >
bool equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, InputIterator2 last2)
template<class InputIterator1 , class InputIterator2 , class BinaryPredicate >
bool equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, InputIterator2 last2, BinaryPredicate pred)
Function Documentation
equal() [1/2]
template<class InputIterator1 , class InputIterator2 > boost::algorithm::equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, InputIterator2 last2)
Returns
true if all elements in the two ranges are equal
Parameters
first1 The start of the first range.
last1 One past the end of the first range.
first2 The start of the second range.
last2 One past the end of the second range.
Definition at line 81 of file equal.hpp.
References boost::algorithm::detail::equal().
equal() [2/2]
template<class InputIterator1 , class InputIterator2 , class BinaryPredicate > boost::algorithm::equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, InputIterator2 last2, BinaryPredicate pred)
Returns
true if all elements in the two ranges are equal
Parameters
first1 The start of the first range.
last1 One past the end of the first range.
first2 The start of the second range.
last2 One past the end of the second range.
pred A predicate for comparing the elements of the ranges
Definition at line 63 of file equal.hpp.
References boost::algorithm::detail::equal().
Referenced by MantidQt::MantidWidgets::Batch::RowLocation::isChildOf(), MantidQt::MantidWidgets::Batch::RowLocation::isDescendantOf(), MantidQt::MantidWidgets::Batch::RowLocation::isSiblingOf(), and MantidQt::MantidWidgets::Batch::pathsSameUntilDepth().