Mantid: MantidQt::CustomDialogs::ShapeDetails Class Reference
MantidQt::CustomDialogs::ShapeDetails Class Reference abstract
The base class for the details widgets.
#include <SampleShapeHelpers.h>
Public Types
enum Unit { millimetre = 0 , centimetre = 1 , metre = 2 }
Public Member Functions
bool getComplementFlag () const
Get complement flag.
const QString & getShapeID () const
void setComplementFlag (bool flag)
Set the complement flag.
ShapeDetails (QWidget *parent=nullptr)
Constructor.
virtual QString writeXML () const =0
Write out the XML definition for this shape.
~ShapeDetails () override=default
Constructor.
Static Public Member Functions
static QString convertToMetres (const QString &value, Unit start_unit)
Convert a string value from the given unit to metres (static)
static QComboBox * createLengthUnitsCombo ()
Create a new length units box.
Protected Attributes
QString m_idvalue
ID string of this object.
Private Attributes
bool m_isComplement
Take the complement of the shape.
Detailed Description
The base class for the details widgets.
Definition at line 120 of file SampleShapeHelpers.h.
Member Enumeration Documentation
Unit
enum MantidQt::CustomDialogs::ShapeDetails::Unit
Enumerator
millimetre
centimetre
metre
Definition at line 137 of file SampleShapeHelpers.h.
Constructor & Destructor Documentation
ShapeDetails()
MantidQt::CustomDialogs::ShapeDetails::ShapeDetails (QWidget * parent = nullptr) inline
Constructor.
Definition at line 125 of file SampleShapeHelpers.h.
~ShapeDetails()
MantidQt::CustomDialogs::ShapeDetails::~ShapeDetails () override default
Constructor.
Member Function Documentation
convertToMetres()
QString ShapeDetails::convertToMetres (const QString & value, Unit start_unit) static
Convert a string value from the given unit to metres (static)
Parameters
value :: The value to change
start_unit :: Initial unit
Returns
A new string value in metres
Definition at line 187 of file SampleShapeHelpers.cpp.
References centimetre, millimetre, and value.
Referenced by MantidQt::CustomDialogs::PointGroupBox::write3DElement(), MantidQt::CustomDialogs::SphereDetails::writeXML(), MantidQt::CustomDialogs::CylinderDetails::writeXML(), MantidQt::CustomDialogs::InfiniteCylinderDetails::writeXML(), MantidQt::CustomDialogs::SliceOfCylinderRingDetails::writeXML(), and MantidQt::CustomDialogs::ConeDetails::writeXML().
createLengthUnitsCombo()
QComboBox * ShapeDetails::createLengthUnitsCombo () static
Create a new length units box.
Create a QComboBox filled with length units (static)
Definition at line 173 of file SampleShapeHelpers.cpp.
Referenced by MantidQt::CustomDialogs::ConeDetails::ConeDetails(), MantidQt::CustomDialogs::CylinderDetails::CylinderDetails(), MantidQt::CustomDialogs::InfiniteCylinderDetails::InfiniteCylinderDetails(), MantidQt::CustomDialogs::PointGroupBox::PointGroupBox(), MantidQt::CustomDialogs::SliceOfCylinderRingDetails::SliceOfCylinderRingDetails(), and MantidQt::CustomDialogs::SphereDetails::SphereDetails().
getComplementFlag()
bool ShapeDetails::getComplementFlag () const
Get complement flag.
Get the complement flag.
Returns
The value of the complement flag
Definition at line 212 of file SampleShapeHelpers.cpp.
References m_isComplement.
getShapeID()
const QString & MantidQt::CustomDialogs::ShapeDetails::getShapeID () const inline
Definition at line 132 of file SampleShapeHelpers.h.
References m_idvalue.
setComplementFlag()
void ShapeDetails::setComplementFlag (bool flag)
Set the complement flag.
Parameters
flag :: The value of the flag
Definition at line 206 of file SampleShapeHelpers.cpp.
References m_isComplement.
writeXML()
virtual QString MantidQt::CustomDialogs::ShapeDetails::writeXML () const pure virtual
Write out the XML definition for this shape.
Implemented in MantidQt::CustomDialogs::SphereDetails, MantidQt::CustomDialogs::CylinderDetails, MantidQt::CustomDialogs::InfiniteCylinderDetails, MantidQt::CustomDialogs::SliceOfCylinderRingDetails, MantidQt::CustomDialogs::ConeDetails, MantidQt::CustomDialogs::InfiniteConeDetails, MantidQt::CustomDialogs::InfinitePlaneDetails, MantidQt::CustomDialogs::CuboidDetails, and MantidQt::CustomDialogs::HexahedronDetails.
Member Data Documentation
m_idvalue
QString MantidQt::CustomDialogs::ShapeDetails::m_idvalue protected
ID string of this object.
Definition at line 148 of file SampleShapeHelpers.h.
Referenced by MantidQt::CustomDialogs::ConeDetails::ConeDetails(), MantidQt::CustomDialogs::CuboidDetails::CuboidDetails(), MantidQt::CustomDialogs::CylinderDetails::CylinderDetails(), getShapeID(), MantidQt::CustomDialogs::HexahedronDetails::HexahedronDetails(), MantidQt::CustomDialogs::InfiniteConeDetails::InfiniteConeDetails(), MantidQt::CustomDialogs::InfiniteCylinderDetails::InfiniteCylinderDetails(), MantidQt::CustomDialogs::InfinitePlaneDetails::InfinitePlaneDetails(), MantidQt::CustomDialogs::SliceOfCylinderRingDetails::SliceOfCylinderRingDetails(), MantidQt::CustomDialogs::SphereDetails::SphereDetails(), MantidQt::CustomDialogs::SphereDetails::writeXML(), MantidQt::CustomDialogs::CylinderDetails::writeXML(), MantidQt::CustomDialogs::InfiniteCylinderDetails::writeXML(), MantidQt::CustomDialogs::SliceOfCylinderRingDetails::writeXML(), MantidQt::CustomDialogs::ConeDetails::writeXML(), MantidQt::CustomDialogs::InfiniteConeDetails::writeXML(), MantidQt::CustomDialogs::InfinitePlaneDetails::writeXML(), MantidQt::CustomDialogs::CuboidDetails::writeXML(), and MantidQt::CustomDialogs::HexahedronDetails::writeXML().
m_isComplement
bool MantidQt::CustomDialogs::ShapeDetails::m_isComplement private
Take the complement of the shape.
Definition at line 152 of file SampleShapeHelpers.h.
Referenced by getComplementFlag(), and setComplementFlag().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/SampleShapeHelpers.h
qt/widgets/plugins/algorithm_dialogs/src/SampleShapeHelpers.cpp