Mantid: MantidQt::MantidWidgets::FitScriptGeneratorView Class Reference
MantidQt::MantidWidgets::FitScriptGeneratorView Class Reference
#include <FitScriptGeneratorView.h>
Public Slots
void closeEvent (QCloseEvent *event) override
Public Member Functions
QPushButton * addWorkspaceButton () const override
AddWorkspaceDialog * addWorkspaceDialog () const override
void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) override
std::vector< FitDomainIndex > allRows () const override
bool applyFunctionChangesToAll () const override
Mantid::API::IFunction::Attribute attributeValue (std::string const &attribute) const override
void clearFunction () override
void clearHandle () override
If the ADS is cleared, then this function will trigger, works by overloading this class and overriding this function.
FitDomainIndex currentRow () const override
void deleteHandle (std::string const &wsName, Workspace_sptr const &ws) override
If a workspace is deleted from the ADS, then this function will trigger, works by overloading this class and overriding this function.
void displayWarning (std::string const &message) override
double endX (FitDomainIndex index) const override
std::string filepath () const override
std::tuple< std::string, std::string, std::string, std::string, std::string, bool > fitOptions () const override
FitScriptGeneratorView (QWidget *parent=nullptr, FittingMode fittingMode=FittingMode::SEQUENTIAL, QMap< QString, QString > const &fitOptions=QMap< QString, QString >())
QPushButton * generateScriptToClipboardButton () const override
QPushButton * generateScriptToFileButton () const override
std::vector< WorkspaceIndex > getDialogWorkspaceIndices () const override
std::vector< Mantid::API::MatrixWorkspace_const_sptr > getDialogWorkspaces () override
std::tuple< std::string, std::vector< double >, std::vector< bool >, std::vector< std::string >, std::vector< std::string > > getEditLocalParameterResults () const override
bool hasLoadedData () const override
void openAddWorkspaceDialog () override
void openEditLocalParameterDialog (std::string const &parameter, std::vector< std::string > const &workspaceNames, std::vector< std::string > const &domainNames, std::vector< double > const &values, std::vector< bool > const &fixes, std::vector< std::string > const &ties, std::vector< std::string > const &constraints) override
double parameterValue (std::string const &parameter) const override
QPushButton * removeButton () const override
void removeDomain (FitDomainIndex domainIndex) override
void renameHandle (std::string const &wsName, std::string const &newName) override
If a workspace is renamed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
void renameWorkspace (std::string const &workspaceName, std::string const &newName) override
void resetSelection () override
void saveTextToClipboard (std::string const &text) const override
std::vector< FitDomainIndex > selectedRows () const override
void setFunction (Mantid::API::IFunction_sptr const &function) const override
void setGlobalParameters (std::vector< GlobalParameter > const &globalParameter) override
void setGlobalTies (std::vector< GlobalTie > const &globalTies) override
void setSimultaneousMode (bool simultaneousMode) override
void setSuccessText (std::string const &text) override
double startX (FitDomainIndex index) const override
void subscribePresenter (IFitScriptGeneratorPresenter *presenter) override
FitScriptGeneratorDataTable * tableWidget () const override
Testing accessors.
WorkspaceIndex workspaceIndex (FitDomainIndex index) const override
std::string workspaceName (FitDomainIndex index) const override
~FitScriptGeneratorView () override
Public Member Functions inherited from MantidQt::MantidWidgets::IFitScriptGeneratorView
virtual QPushButton * addWorkspaceButton () const =0
virtual AddWorkspaceDialog * addWorkspaceDialog () const =0
virtual void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX)=0
virtual std::vector< FitDomainIndex > allRows () const =0
virtual bool applyFunctionChangesToAll () const =0
virtual Mantid::API::IFunction::Attribute attributeValue (std::string const &attribute) const =0
virtual void clearFunction ()=0
virtual FitDomainIndex currentRow () const =0
virtual void displayWarning (std::string const &message)=0
virtual double endX (FitDomainIndex index) const =0
virtual std::string filepath () const =0
virtual std::tuple< std::string, std::string, std::string, std::string, std::string, bool > fitOptions () const =0
virtual QPushButton * generateScriptToClipboardButton () const =0
virtual QPushButton * generateScriptToFileButton () const =0
virtual std::vector< WorkspaceIndex > getDialogWorkspaceIndices () const =0
virtual std::vector< Mantid::API::MatrixWorkspace_const_sptr > getDialogWorkspaces ()=0
virtual std::tuple< std::string, std::vector< double >, std::vector< bool >, std::vector< std::string >, std::vector< std::string > > getEditLocalParameterResults () const =0
virtual bool hasLoadedData () const =0
IFitScriptGeneratorView (QWidget *parent=nullptr)
virtual void openAddWorkspaceDialog ()=0
virtual void openEditLocalParameterDialog (std::string const &parameter, std::vector< std::string > const &workspaceNames, std::vector< std::string > const &domainNames, std::vector< double > const &values, std::vector< bool > const &fixes, std::vector< std::string > const &ties, std::vector< std::string > const &constraints)=0
virtual double parameterValue (std::string const &parameter) const =0
virtual QPushButton * removeButton () const =0
virtual void removeDomain (FitDomainIndex domainIndex)=0
virtual void renameWorkspace (std::string const &workspaceName, std::string const &newName)=0
virtual void resetSelection ()=0
virtual void saveTextToClipboard (std::string const &text) const =0
virtual std::vector< FitDomainIndex > selectedRows () const =0
virtual void setFunction (Mantid::API::IFunction_sptr const &function) const =0
virtual void setGlobalParameters (std::vector< GlobalParameter > const &globalParameter)=0
virtual void setGlobalTies (std::vector< GlobalTie > const &globalTies)=0
virtual void setSimultaneousMode (bool simultaneousMode)=0
virtual void setSuccessText (std::string const &text)=0
virtual double startX (FitDomainIndex index) const =0
virtual void subscribePresenter (IFitScriptGeneratorPresenter *presenter)=0
virtual FitScriptGeneratorDataTable * tableWidget () const =0
Testing accessors.
virtual WorkspaceIndex workspaceIndex (FitDomainIndex index) const =0
virtual std::string workspaceName (FitDomainIndex index) const =0
virtual ~IFitScriptGeneratorView ()=default
Public Member Functions inherited from MantidQt::API::MantidWidget
virtual QVariant getUserInput () const
Returns a QVariant containing what the widget classes as user input so that input can be returned through a common interface.
virtual void setUserInput (const QVariant &value)
Sets a value on a mantid widget through a common interface.
Public Member Functions inherited from Mantid::API::AnalysisDataServiceObserver
virtual void addHandle (const std::string &wsName, const Workspace_sptr &ws)
If a workspace is added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
AnalysisDataServiceObserver ()
virtual void anyChangeHandle ()
If anyChange to the ADS occurs then this function will trigger, works by overloading this class and overriding this function.
virtual void clearHandle ()
If the ADS is cleared, then this function will trigger, works by overloading this class and overriding this function.
virtual void deleteHandle (const std::string &wsName, const Workspace_sptr &ws)
If a workspace is deleted from the ADS, then this function will trigger, works by overloading this class and overriding this function.
virtual void groupHandle (const std::string &wsName, const Workspace_sptr &ws)
If a group is created/added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
virtual void groupUpdateHandle (const std::string &wsName, const Workspace_sptr &ws)
If a group has a workspace added/removed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
void observeAdd (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is added to it.
void observeAll (bool turnOn=true)
Function will turn on/off all observers for the ADS.
void observeClear (bool turnOn=true)
Function will add/remove the observer to the ADS for when the ADS is cleared.
void observeDelete (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is deleted.
void observeGroup (bool turnOn=true)
Function will add/remove the observer to the ADS for when a group is added/created in the ADS.
void observeGroupUpdate (bool turnOn=true)
Function will add/remove the observer to the ADS for if a workspace is added to a group or removed.
void observeRename (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is renamed.
void observeReplace (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is replaced.
void observeUnGroup (bool turnOn=true)
Function will add/remove the observer to the ADS for when a group is removed/delete from the ADS.
virtual void renameHandle (const std::string &wsName, const std::string &newName)
If a workspace is renamed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
virtual void replaceHandle (const std::string &wsName, const Workspace_sptr &ws)
If a workspace is replaced in the ADS, then this function will trigger, works by overloading this class and overriding this function.
virtual void unGroupHandle (const std::string &wsName, const Workspace_sptr &ws)
If a group is removed from the ADS, then this function will trigger, works by overloading this class and overriding this function.
virtual ~AnalysisDataServiceObserver ()
Private Slots
void addWorkspaceDialogAccepted (bool close)
void closeAddWorkspaceDialog ()
void notifyADSClearEvent ()
void notifyADSDeleteEvent (std::string const &workspaceName)
void notifyADSRenameEvent (std::string const &workspaceName, std::string const &newName)
void onAddDomainClicked ()
void onAttributeChanged (QString const &attribute)
void onCellChanged (int row, int column)
void onCopyFunctionToClipboard ()
void onEditLocalParameterClicked (QString const &parameter)
void onEditLocalParameterFinished (int result)
void onFittingModeChanged (FittingMode fittingMode)
void onFunctionAdded (QString const &function)
void onFunctionHelpRequested ()
void onFunctionRemoved (QString const &function)
void onFunctionReplaced (QString const &function)
void onGenerateScriptToClipboardClicked ()
void onGenerateScriptToFileClicked ()
void onGlobalParametersChanged (QStringList const &globalParameters)
void onHelpClicked ()
void onItemSelected ()
void onOutputBaseNameChanged (std::string const &outputBaseName)
void onParameterChanged (QString const &parameter)
void onParameterConstraintChanged (QString const &functionIndex, QString const &constraint)
void onParameterConstraintRemoved (QString const &parameter)
void onParameterTieChanged (QString const &parameter, QString const &tie)
void onRemoveDomainClicked ()
Private Member Functions
void connectUiSignals ()
void setFitBrowserOptions (QMap< QString, QString > const &fitOptions)
void setFittingMode (FittingMode fittingMode)
Private Attributes
std::unique_ptr< AddWorkspaceDialog > m_addWorkspaceDialog
std::unique_ptr< FitScriptGeneratorDataTable > m_dataTable
EditLocalParameterDialog * m_editLocalParameterDialog
std::unique_ptr< FitScriptOptionsBrowser > m_fitOptionsBrowser
std::unique_ptr< FunctionTreeView > m_functionTreeView
IFitScriptGeneratorPresenter * m_presenter
Ui::FitScriptGenerator m_ui
Additional Inherited Members
Public Types inherited from MantidQt::MantidWidgets::IFitScriptGeneratorView
enum class Event {
ADSDeleteEvent , ADSClearEvent , ADSRenameEvent , RemoveDomainClicked ,
AddDomainClicked , AddDomainAccepted , StartXChanged , EndXChanged ,
SelectionChanged , FunctionRemoved , FunctionAdded , FunctionReplaced ,
ParameterChanged , AttributeChanged , ParameterTieChanged , ParameterConstraintRemoved ,
ParameterConstraintChanged , GlobalParametersChanged , EditLocalParameterClicked , EditLocalParameterFinished ,
OutputBaseNameChanged , FittingModeChanged , GenerateScriptToFileClicked , GenerateScriptToClipboardClicked
}
Signals inherited from MantidQt::API::MantidWidget
void runAsPythonScript (const QString &code, bool)
Protected Member Functions inherited from MantidQt::API::MantidWidget
MantidWidget (QWidget *parent=nullptr)
Default constructor.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Detailed Description
Definition at line 42 of file FitScriptGeneratorView.h.
Constructor & Destructor Documentation
FitScriptGeneratorView()
MantidQt::MantidWidgets::FitScriptGeneratorView::FitScriptGeneratorView (QWidget * parent = nullptr, FittingMode fittingMode = FittingMode::SEQUENTIAL, QMap< QString, QString > const & fitOptions = QMap<QString, QString>())
Definition at line 94 of file FitScriptGeneratorView.cpp.
References connectUiSignals(), fitOptions(), m_dataTable, m_fitOptionsBrowser, m_functionTreeView, m_ui, Mantid::API::AnalysisDataServiceObserver::observeClear(), Mantid::API::AnalysisDataServiceObserver::observeDelete(), Mantid::API::AnalysisDataServiceObserver::observeRename(), setFitBrowserOptions(), and setFittingMode().
~FitScriptGeneratorView()
MantidQt::MantidWidgets::FitScriptGeneratorView::~FitScriptGeneratorView () override
Definition at line 115 of file FitScriptGeneratorView.cpp.
References closeAddWorkspaceDialog(), m_addWorkspaceDialog, m_dataTable, m_fitOptionsBrowser, m_functionTreeView, Mantid::API::AnalysisDataServiceObserver::observeClear(), Mantid::API::AnalysisDataServiceObserver::observeDelete(), and Mantid::API::AnalysisDataServiceObserver::observeRename().
Member Function Documentation
addWorkspaceButton()
QPushButton * MantidQt::MantidWidgets::FitScriptGeneratorView::addWorkspaceButton () const inline override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 113 of file FitScriptGeneratorView.h.
addWorkspaceDialog()
AddWorkspaceDialog * MantidQt::MantidWidgets::FitScriptGeneratorView::addWorkspaceDialog () const inline override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 114 of file FitScriptGeneratorView.h.
addWorkspaceDialogAccepted
void MantidQt::MantidWidgets::FitScriptGeneratorView::addWorkspaceDialogAccepted (bool close) private slot
Definition at line 373 of file FitScriptGeneratorView.cpp.
References closeAddWorkspaceDialog(), m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by closeAddWorkspaceDialog(), and openAddWorkspaceDialog().
addWorkspaceDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorView::addWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 354 of file FitScriptGeneratorView.cpp.
References endX(), m_dataTable, startX(), workspaceIndex(), and workspaceName().
allRows()
std::vector< FitDomainIndex > MantidQt::MantidWidgets::FitScriptGeneratorView::allRows () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 332 of file FitScriptGeneratorView.cpp.
References m_dataTable.
applyFunctionChangesToAll()
bool MantidQt::MantidWidgets::FitScriptGeneratorView::applyFunctionChangesToAll () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 440 of file FitScriptGeneratorView.cpp.
References m_ui.
attributeValue()
IFunction::Attribute MantidQt::MantidWidgets::FitScriptGeneratorView::attributeValue (std::string const & attribute) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 344 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
clearFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorView::clearFunction () override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 444 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
clearHandle()
void MantidQt::MantidWidgets::FitScriptGeneratorView::clearHandle () override virtual
If the ADS is cleared, then this function will trigger, works by overloading this class and overriding this function.
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 197 of file FitScriptGeneratorView.cpp.
References notifyADSClearEvent().
closeAddWorkspaceDialog
void MantidQt::MantidWidgets::FitScriptGeneratorView::closeAddWorkspaceDialog () private slot
Definition at line 366 of file FitScriptGeneratorView.cpp.
References addWorkspaceDialogAccepted(), closeAddWorkspaceDialog(), and m_addWorkspaceDialog.
Referenced by addWorkspaceDialogAccepted(), closeAddWorkspaceDialog(), closeEvent(), openAddWorkspaceDialog(), and ~FitScriptGeneratorView().
closeEvent
void MantidQt::MantidWidgets::FitScriptGeneratorView::closeEvent (QCloseEvent * event) override slot
Definition at line 484 of file FitScriptGeneratorView.cpp.
References closeAddWorkspaceDialog(), and m_addWorkspaceDialog.
connectUiSignals()
void MantidQt::MantidWidgets::FitScriptGeneratorView::connectUiSignals () private
Disconnected because it causes a crash when selecting a table row while editing a parameters value. This is because selecting a different row will change the current function in the FunctionTreeView. The closeEditor slot is then called after this, but the memory location of the old function is now a nullptr so there is a read access violation.
Definition at line 128 of file FitScriptGeneratorView.cpp.
References m_dataTable, m_fitOptionsBrowser, m_functionTreeView, m_ui, onAddDomainClicked(), onAttributeChanged(), onCellChanged(), onCopyFunctionToClipboard(), onEditLocalParameterClicked(), onFittingModeChanged(), onFunctionAdded(), onFunctionHelpRequested(), onFunctionRemoved(), onFunctionReplaced(), onGenerateScriptToClipboardClicked(), onGenerateScriptToFileClicked(), onGlobalParametersChanged(), onHelpClicked(), onItemSelected(), onOutputBaseNameChanged(), onParameterChanged(), onParameterConstraintChanged(), onParameterConstraintRemoved(), onParameterTieChanged(), and onRemoveDomainClicked().
Referenced by FitScriptGeneratorView().
currentRow()
FitDomainIndex MantidQt::MantidWidgets::FitScriptGeneratorView::currentRow () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 336 of file FitScriptGeneratorView.cpp.
References m_dataTable.
deleteHandle()
void MantidQt::MantidWidgets::FitScriptGeneratorView::deleteHandle (std::string const & wsName, Workspace_sptr const & ws) override virtual
If a workspace is deleted from the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
ws Workspace_sptr; the Workspace that is deleted
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 189 of file FitScriptGeneratorView.cpp.
References notifyADSDeleteEvent().
displayWarning()
void MantidQt::MantidWidgets::FitScriptGeneratorView::displayWarning (std::string const & message) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 480 of file FitScriptGeneratorView.cpp.
Referenced by getDialogWorkspaces().
endX()
double MantidQt::MantidWidgets::FitScriptGeneratorView::endX (FitDomainIndex index) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 330 of file FitScriptGeneratorView.cpp.
References index, and m_dataTable.
Referenced by addWorkspaceDomain().
filepath()
std::string MantidQt::MantidWidgets::FitScriptGeneratorView::filepath () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 427 of file FitScriptGeneratorView.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
fitOptions()
std::tuple< std::string, std::string, std::string, std::string, std::string, bool > MantidQt::MantidWidgets::FitScriptGeneratorView::fitOptions () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 421 of file FitScriptGeneratorView.cpp.
References m_fitOptionsBrowser.
Referenced by FitScriptGeneratorView(), and setFitBrowserOptions().
generateScriptToClipboardButton()
QPushButton * MantidQt::MantidWidgets::FitScriptGeneratorView::generateScriptToClipboardButton () const inline override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 116 of file FitScriptGeneratorView.h.
generateScriptToFileButton()
QPushButton * MantidQt::MantidWidgets::FitScriptGeneratorView::generateScriptToFileButton () const inline override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 115 of file FitScriptGeneratorView.h.
getDialogWorkspaceIndices()
std::vector< WorkspaceIndex > MantidQt::MantidWidgets::FitScriptGeneratorView::getDialogWorkspaceIndices () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 390 of file FitScriptGeneratorView.cpp.
References m_addWorkspaceDialog.
getDialogWorkspaces()
std::vector< MatrixWorkspace_const_sptr > MantidQt::MantidWidgets::FitScriptGeneratorView::getDialogWorkspaces () override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 379 of file FitScriptGeneratorView.cpp.
References displayWarning(), and m_addWorkspaceDialog.
getEditLocalParameterResults()
std::tuple< std::string, std::vector< double >, std::vector< bool >, std::vector< std::string >, std::vector< std::string > > MantidQt::MantidWidgets::FitScriptGeneratorView::getEditLocalParameterResults () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 412 of file FitScriptGeneratorView.cpp.
References MantidQt::MantidWidgets::EditLocalParameterDialog::getConstraints(), MantidQt::MantidWidgets::EditLocalParameterDialog::getFixes(), MantidQt::MantidWidgets::EditLocalParameterDialog::getParameterName(), MantidQt::MantidWidgets::EditLocalParameterDialog::getTies(), MantidQt::MantidWidgets::EditLocalParameterDialog::getValues(), and m_editLocalParameterDialog.
hasLoadedData()
bool MantidQt::MantidWidgets::FitScriptGeneratorView::hasLoadedData () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 338 of file FitScriptGeneratorView.cpp.
References m_dataTable.
notifyADSClearEvent
void MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSClearEvent () private slot
Definition at line 218 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by clearHandle().
notifyADSDeleteEvent
void MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSDeleteEvent (std::string const & workspaceName) private slot
Definition at line 214 of file FitScriptGeneratorView.cpp.
References m_presenter, MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter(), and workspaceName().
Referenced by deleteHandle().
notifyADSRenameEvent
void MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSRenameEvent (std::string const & workspaceName, std::string const & newName) private slot
Definition at line 220 of file FitScriptGeneratorView.cpp.
References m_presenter, MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter(), and workspaceName().
Referenced by renameHandle().
onAddDomainClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onAddDomainClicked () private slot
Definition at line 226 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onAttributeChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onAttributeChanged (QString const & attribute) private slot
Definition at line 258 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onCellChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onCellChanged (int row, int column) private slot
Definition at line 228 of file FitScriptGeneratorView.cpp.
References m_dataTable, m_presenter, MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter(), and UNUSED_ARG.
Referenced by connectUiSignals().
onCopyFunctionToClipboard
void MantidQt::MantidWidgets::FitScriptGeneratorView::onCopyFunctionToClipboard () private slot
Definition at line 279 of file FitScriptGeneratorView.cpp.
References m_functionTreeView, and saveTextToClipboard().
Referenced by connectUiSignals().
onEditLocalParameterClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onEditLocalParameterClicked (QString const & parameter) private slot
Definition at line 297 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onEditLocalParameterFinished
void MantidQt::MantidWidgets::FitScriptGeneratorView::onEditLocalParameterFinished (int result) private slot
Definition at line 301 of file FitScriptGeneratorView.cpp.
References m_editLocalParameterDialog, m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by openEditLocalParameterDialog().
onFittingModeChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onFittingModeChanged (FittingMode fittingMode) private slot
Definition at line 293 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onFunctionAdded
void MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionAdded (QString const & function) private slot
Definition at line 246 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onFunctionHelpRequested
void MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionHelpRequested () private slot
Definition at line 284 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
Referenced by connectUiSignals().
onFunctionRemoved
void MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionRemoved (QString const & function) private slot
Definition at line 242 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onFunctionReplaced
void MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionReplaced (QString const & function) private slot
Definition at line 250 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onGenerateScriptToClipboardClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onGenerateScriptToClipboardClicked () private slot
Definition at line 312 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onGenerateScriptToFileClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onGenerateScriptToFileClicked () private slot
Definition at line 308 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onGlobalParametersChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onGlobalParametersChanged (QStringList const & globalParameters) private slot
Definition at line 275 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onHelpClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onHelpClicked () private slot
Definition at line 316 of file FitScriptGeneratorView.cpp.
References MantidQt::API::HelpWindow::showCustomInterface().
Referenced by connectUiSignals().
onItemSelected
void MantidQt::MantidWidgets::FitScriptGeneratorView::onItemSelected () private slot
Definition at line 240 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onOutputBaseNameChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onOutputBaseNameChanged (std::string const & outputBaseName) private slot
Definition at line 289 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onParameterChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterChanged (QString const & parameter) private slot
Definition at line 254 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onParameterConstraintChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterConstraintChanged (QString const & functionIndex, QString const & constraint) private slot
Definition at line 270 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onParameterConstraintRemoved
void MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterConstraintRemoved (QString const & parameter) private slot
Definition at line 266 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onParameterTieChanged
void MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterTieChanged (QString const & parameter, QString const & tie) private slot
Definition at line 262 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
onRemoveDomainClicked
void MantidQt::MantidWidgets::FitScriptGeneratorView::onRemoveDomainClicked () private slot
Definition at line 224 of file FitScriptGeneratorView.cpp.
References m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by connectUiSignals().
openAddWorkspaceDialog()
void MantidQt::MantidWidgets::FitScriptGeneratorView::openAddWorkspaceDialog () override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 359 of file FitScriptGeneratorView.cpp.
References addWorkspaceDialogAccepted(), closeAddWorkspaceDialog(), and m_addWorkspaceDialog.
openEditLocalParameterDialog()
void MantidQt::MantidWidgets::FitScriptGeneratorView::openEditLocalParameterDialog (std::string const & parameter, std::vector< std::string > const & workspaceNames, std::vector< std::string > const & domainNames, std::vector< double > const & values, std::vector< bool > const & fixes, std::vector< std::string > const & ties, std::vector< std::string > const & constraints) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 397 of file FitScriptGeneratorView.cpp.
References m_editLocalParameterDialog, and onEditLocalParameterFinished().
parameterValue()
double MantidQt::MantidWidgets::FitScriptGeneratorView::parameterValue (std::string const & parameter) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 340 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
removeButton()
QPushButton * MantidQt::MantidWidgets::FitScriptGeneratorView::removeButton () const inline override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 112 of file FitScriptGeneratorView.h.
removeDomain()
void MantidQt::MantidWidgets::FitScriptGeneratorView::removeDomain (FitDomainIndex domainIndex) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 352 of file FitScriptGeneratorView.cpp.
References m_dataTable.
renameHandle()
void MantidQt::MantidWidgets::FitScriptGeneratorView::renameHandle (std::string const & wsName, std::string const & newName) override virtual
If a workspace is renamed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
newName std::string; the new name of the workspace
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 205 of file FitScriptGeneratorView.cpp.
References notifyADSRenameEvent().
renameWorkspace()
void MantidQt::MantidWidgets::FitScriptGeneratorView::renameWorkspace (std::string const & workspaceName, std::string const & newName) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 348 of file FitScriptGeneratorView.cpp.
References m_dataTable, and workspaceName().
resetSelection()
void MantidQt::MantidWidgets::FitScriptGeneratorView::resetSelection () override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 438 of file FitScriptGeneratorView.cpp.
References m_dataTable.
saveTextToClipboard()
void MantidQt::MantidWidgets::FitScriptGeneratorView::saveTextToClipboard (std::string const & text) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 475 of file FitScriptGeneratorView.cpp.
Referenced by onCopyFunctionToClipboard().
selectedRows()
std::vector< FitDomainIndex > MantidQt::MantidWidgets::FitScriptGeneratorView::selectedRows () const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 334 of file FitScriptGeneratorView.cpp.
References m_dataTable.
setFitBrowserOptions()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setFitBrowserOptions (QMap< QString, QString > const & fitOptions) private
Definition at line 175 of file FitScriptGeneratorView.cpp.
References fitOptions(), and m_fitOptionsBrowser.
Referenced by FitScriptGeneratorView().
setFittingMode()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setFittingMode (FittingMode fittingMode) private
Definition at line 180 of file FitScriptGeneratorView.cpp.
References m_fitOptionsBrowser.
Referenced by FitScriptGeneratorView().
setFunction()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setFunction (Mantid::API::IFunction_sptr const & function) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 456 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
setGlobalParameters()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setGlobalParameters (std::vector< GlobalParameter > const & globalParameter) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 467 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
setGlobalTies()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setGlobalTies (std::vector< GlobalTie > const & globalTies) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 463 of file FitScriptGeneratorView.cpp.
References m_functionTreeView.
setSimultaneousMode()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setSimultaneousMode (bool simultaneousMode) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 446 of file FitScriptGeneratorView.cpp.
References m_dataTable, and m_functionTreeView.
setSuccessText()
void MantidQt::MantidWidgets::FitScriptGeneratorView::setSuccessText (std::string const & text) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 471 of file FitScriptGeneratorView.cpp.
References m_ui.
startX()
double MantidQt::MantidWidgets::FitScriptGeneratorView::startX (FitDomainIndex index) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 328 of file FitScriptGeneratorView.cpp.
References index, and m_dataTable.
Referenced by addWorkspaceDomain().
subscribePresenter()
void MantidQt::MantidWidgets::FitScriptGeneratorView::subscribePresenter (IFitScriptGeneratorPresenter * presenter) override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 184 of file FitScriptGeneratorView.cpp.
References m_fitOptionsBrowser, m_presenter, and MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter().
Referenced by MockFitScriptGeneratorPresenter::MockFitScriptGeneratorPresenter().
tableWidget()
FitScriptGeneratorDataTable * MantidQt::MantidWidgets::FitScriptGeneratorView::tableWidget () const inline override virtual
Testing accessors.
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 111 of file FitScriptGeneratorView.h.
workspaceIndex()
WorkspaceIndex MantidQt::MantidWidgets::FitScriptGeneratorView::workspaceIndex (FitDomainIndex index) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 324 of file FitScriptGeneratorView.cpp.
References index, and m_dataTable.
Referenced by addWorkspaceDomain().
workspaceName()
std::string MantidQt::MantidWidgets::FitScriptGeneratorView::workspaceName (FitDomainIndex index) const override virtual
Implements MantidQt::MantidWidgets::IFitScriptGeneratorView.
Definition at line 320 of file FitScriptGeneratorView.cpp.
References index, and m_dataTable.
Referenced by addWorkspaceDomain(), notifyADSDeleteEvent(), notifyADSRenameEvent(), and renameWorkspace().
Member Data Documentation
m_addWorkspaceDialog
std::unique_ptr<AddWorkspaceDialog> MantidQt::MantidWidgets::FitScriptGeneratorView::m_addWorkspaceDialog private
Definition at line 159 of file FitScriptGeneratorView.h.
Referenced by closeAddWorkspaceDialog(), closeEvent(), getDialogWorkspaceIndices(), getDialogWorkspaces(), openAddWorkspaceDialog(), and ~FitScriptGeneratorView().
m_dataTable
std::unique_ptr<FitScriptGeneratorDataTable> MantidQt::MantidWidgets::FitScriptGeneratorView::m_dataTable private
Definition at line 160 of file FitScriptGeneratorView.h.
Referenced by addWorkspaceDomain(), allRows(), connectUiSignals(), currentRow(), endX(), FitScriptGeneratorView(), hasLoadedData(), onCellChanged(), removeDomain(), renameWorkspace(), resetSelection(), selectedRows(), setSimultaneousMode(), startX(), workspaceIndex(), workspaceName(), and ~FitScriptGeneratorView().
m_editLocalParameterDialog
EditLocalParameterDialog* MantidQt::MantidWidgets::FitScriptGeneratorView::m_editLocalParameterDialog private
Definition at line 163 of file FitScriptGeneratorView.h.
Referenced by getEditLocalParameterResults(), onEditLocalParameterFinished(), and openEditLocalParameterDialog().
m_fitOptionsBrowser
std::unique_ptr<FitScriptOptionsBrowser> MantidQt::MantidWidgets::FitScriptGeneratorView::m_fitOptionsBrowser private
Definition at line 162 of file FitScriptGeneratorView.h.
Referenced by connectUiSignals(), fitOptions(), FitScriptGeneratorView(), setFitBrowserOptions(), setFittingMode(), subscribePresenter(), and ~FitScriptGeneratorView().
m_functionTreeView
std::unique_ptr<FunctionTreeView> MantidQt::MantidWidgets::FitScriptGeneratorView::m_functionTreeView private
Definition at line 161 of file FitScriptGeneratorView.h.
Referenced by attributeValue(), clearFunction(), connectUiSignals(), FitScriptGeneratorView(), onCopyFunctionToClipboard(), onFunctionHelpRequested(), parameterValue(), setFunction(), setGlobalParameters(), setGlobalTies(), setSimultaneousMode(), and ~FitScriptGeneratorView().
m_presenter
IFitScriptGeneratorPresenter* MantidQt::MantidWidgets::FitScriptGeneratorView::m_presenter private
Definition at line 158 of file FitScriptGeneratorView.h.
Referenced by addWorkspaceDialogAccepted(), notifyADSClearEvent(), notifyADSDeleteEvent(), notifyADSRenameEvent(), onAddDomainClicked(), onAttributeChanged(), onCellChanged(), onEditLocalParameterClicked(), onEditLocalParameterFinished(), onFittingModeChanged(), onFunctionAdded(), onFunctionRemoved(), onFunctionReplaced(), onGenerateScriptToClipboardClicked(), onGenerateScriptToFileClicked(), onGlobalParametersChanged(), onItemSelected(), onOutputBaseNameChanged(), onParameterChanged(), onParameterConstraintChanged(), onParameterConstraintRemoved(), onParameterTieChanged(), onRemoveDomainClicked(), and subscribePresenter().
m_ui
Ui::FitScriptGenerator MantidQt::MantidWidgets::FitScriptGeneratorView::m_ui private
Definition at line 164 of file FitScriptGeneratorView.h.
Referenced by applyFunctionChangesToAll(), connectUiSignals(), FitScriptGeneratorView(), and setSuccessText().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorView.h
qt/widgets/common/src/FitScriptGeneratorView.cpp