Mantid: Framework/PythonInterface/mantid/api/src/Exports/SpectrumInfo.cpp File Reference
SpectrumInfo.cpp File Reference
#include "MantidAPI/SpectrumInfo.h"
#include "MantidAPI/SpectrumInfoItem.h"
#include "MantidAPI/SpectrumInfoIterator.h"
#include "MantidPythonInterface/api/SpectrumInfoPythonIterator.h"
#include "MantidTypes/SpectrumDefinition.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/list.hpp>
#include <boost/python/return_value_policy.hpp>
#include <boost/python/tuple.hpp>
Functions
void export_SpectrumInfo ()
PyObject * geographicalAngles (const SpectrumInfo &spectrumInfo, const size_t index)
SpectrumInfoPythonIterator make_pyiterator (SpectrumInfo &spectrumInfo)
Function Documentation
export_SpectrumInfo()
void export_SpectrumInfo ()
Definition at line 38 of file SpectrumInfo.cpp.
References Mantid::API::SpectrumInfo::azimuthal(), Mantid::API::SpectrumInfo::detectorCount(), Mantid::API::SpectrumInfo::difcUncalibrated(), Mantid::API::SpectrumInfo::diffractometerConstants(), geographicalAngles(), Mantid::API::SpectrumInfo::hasDetectors(), Mantid::API::SpectrumInfo::hasUniqueDetector(), Mantid::API::SpectrumInfo::isMasked(), Mantid::API::SpectrumInfo::isMonitor(), Mantid::API::SpectrumInfo::l1(), Mantid::API::SpectrumInfo::l2(), make_pyiterator(), Mantid::API::SpectrumInfo::position(), Mantid::API::SpectrumInfo::samplePosition(), Mantid::API::SpectrumInfo::setMasked(), Mantid::API::SpectrumInfo::signedTwoTheta(), Mantid::API::SpectrumInfo::size(), Mantid::API::SpectrumInfo::sourcePosition(), Mantid::API::SpectrumInfo::spectrumDefinition(), and Mantid::API::SpectrumInfo::twoTheta().
geographicalAngles()
PyObject * geographicalAngles (const SpectrumInfo & spectrumInfo, const size_t index)
Definition at line 32 of file SpectrumInfo.cpp.
References Mantid::API::SpectrumInfo::geographicalAngles(), and index.
Referenced by export_SpectrumInfo().
make_pyiterator()
SpectrumInfoPythonIterator make_pyiterator (SpectrumInfo & spectrumInfo)
Definition at line 28 of file SpectrumInfo.cpp.
Referenced by export_ComponentInfo(), export_DetectorInfo(), and export_SpectrumInfo().