Mantid: ICat4::xsd__string Class Reference
ICat4::xsd__string Class Reference
#include <ICat4Stub.h>
Public Member Functions
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
xsd__string ()
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 221 of file ICat4Stub.h.
Constructor & Destructor Documentation
xsd__string()
ICat4::xsd__string::xsd__string () inline
Definition at line 233 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::xsd__string::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23722 of file ICat4C.cpp.
References ICat4::soap_default_std__string().
Referenced by ICat4::soap_in_xsd__string(), ICat4::soap_new_req_xsd__string(), and ICat4::soap_new_set_xsd__string().
soap_get()
void * ICat4::xsd__string::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23779 of file ICat4C.cpp.
References ICat4::soap_get_xsd__string().
soap_in()
void * ICat4::xsd__string::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23746 of file ICat4C.cpp.
References ICat4::soap_in_xsd__string().
Referenced by ICat4::soap_in_xsd__string().
soap_out()
int ICat4::xsd__string::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23737 of file ICat4C.cpp.
References ICat4::soap_out_xsd__string().
soap_put()
int ICat4::xsd__string::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23772 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_xsd__string.
soap_serialize()
void ICat4::xsd__string::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23728 of file ICat4C.cpp.
References ICat4::soap_serialize_std__string(), and SOAP_TYPE_ICat4_std__string.
soap_type()
int ICat4::xsd__string::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 226 of file ICat4Stub.h.
Member Data Documentation
__item
std::string ICat4::xsd__string::__item
Definition at line 223 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp