Mantid: ICat4::ns1__sample Class Reference
ICat4::ns1__sample Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__sample ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< ns1__dataset * > datasets
ns1__investigation * investigation
std::string * name
std::vector< ns1__sampleParameter * > parameters
ns1__sampleType * type
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2061 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__sample()
ICat4::ns1__sample::ns1__sample () inline
Definition at line 2076 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__sample::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10090 of file ICat4C.cpp.
References datasets, investigation, name, parameters, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataset(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__sampleParameter(), and type.
Referenced by ICat4::soap_in_ns1__sample(), ICat4::soap_new_req_ns1__sample(), and ICat4::soap_new_set_ns1__sample().
soap_get()
void * ICat4::ns1__sample::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10260 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_get_ns1__sample(), and type.
soap_in()
void * ICat4::ns1__sample::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10147 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_in_ns1__sample(), and type.
Referenced by ICat4::soap_in_ns1__sample().
soap_out()
int ICat4::ns1__sample::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10114 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_out_ns1__sample(), and type.
Referenced by soap_put().
soap_put()
int ICat4::ns1__sample::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10253 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), SOAP_TYPE_ICat4_ns1__sample, and type.
soap_serialize()
void ICat4::ns1__sample::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10101 of file ICat4C.cpp.
References datasets, investigation, name, parameters, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTons1__sampleType(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataset(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__sampleParameter(), and type.
Referenced by ICat4::soap_serialize_PointerTons1__relatedDatafile().
soap_type()
int ICat4::ns1__sample::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2069 of file ICat4Stub.h.
Member Data Documentation
datasets
std::vector<ns1__dataset *> ICat4::ns1__sample::datasets
Definition at line 2063 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigation
ns1__investigation* ICat4::ns1__sample::investigation
Definition at line 2064 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__sample::name
Definition at line 2065 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
parameters
std::vector<ns1__sampleParameter *> ICat4::ns1__sample::parameters
Definition at line 2066 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
type
ns1__sampleType* ICat4::ns1__sample::type
Definition at line 2067 of file ICat4Stub.h.
Referenced by soap_default(), soap_get(), soap_in(), ICat4::soap_in_ns1__sample(), soap_out(), soap_put(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp