Mantid: Mantid::CurveFitting::Algorithms Namespace Reference
Mantid::CurveFitting::Algorithms Namespace Reference
Classes
class CalculateChiSquared
Calculate chi squared for a function and a data set in a workspace.
class CalculateCostFunction
Calculate cost function for a function and a data set in a workspace.
class ChiSlice
Helper class to calculate the chi squared along a direction in the parameter space.
class ConvertToYSpace
Takes a workspace with X axis in TOF and converts it to Y-space where the transformation is defined by equation (7) in http://link.aip.org/link/doi/10.1063/1.3561493?ver=pdfcov.
class ConvolutionFit
ConvolutionFit : Performs a QENS convolution fit.
class ConvolveWorkspaces
Convolution of two workspaces.
struct DetectorParams
Simple data structure to store nominal detector values It avoids some functions taking a huge number of arguments.
class DoublePulseFit
A function to fit muon data from a double pulse source.
class EstimateFitParameters
Estimate parameters of a fitting function using a Monte Carlo algorithm.
class EstimatePeakErrors
class EvaluateFunction
Evaluate a function (1D or MD) on a domain of an input workspace and save the result in the output workspace.
class Fit
A generic fitting algorithm.
class Fit1D
Deprecation notice: instead of using this algorithm please use the Fit algorithm instead.
struct FitData
Structure to contain least squares data and used by GSL.
class FitPowderDiffPeaks
FitPowderDiffPeaks : Fit peaks in powder diffraction pattern.
struct InputSpectraToFit
class IqtFit
class JacobianImpl
The implementation of Jacobian.
class LeBailFit
class LeBailFunction
LeBailFunction : LeBailFunction is to calculate peak intensities in a composite function including neutron peak and background functions.
class NormaliseByPeakArea
struct Parameter
LeBailFit : Algorithm to do Le Bail Fit.
class PawleyFit
This algorithm uses the Pawley-method to refine lattice parameters using a powder diffractogram and a list of unique Miller indices.
class PlotPeakByLogValue
Takes a workspace group and fits the same spectrum in all workspaces with the same function.
class ProfileChiSquared1D
Profiles chi2 about its minimum to find parameter errors.
class QENSFitSequential
QENSFitSequential - Performs a sequential QENS fit.
class QENSFitSimultaneous
QENSFitSimultaneous - Algorithm for performing a simultaneous QENS fit.
class RefinePowderInstrumentParameters
RefinePowderInstrumentParameters : Algorithm to refine instrument geometry parameters only.
class RefinePowderInstrumentParameters3
RefinePowderInstrumentParameters3 :
class SplineBackground
SplineBackground.
class SplineInterpolation
Takes two workspaces as input.
class SplineSmoothing
Takes a 2D workspace and produces an output workspace containing a smoothed version of the data by selecting a number of points to define a spline for each histogram in the workspace.
class V3DFromHKLColumnExtractor
Small helper class to extract HKLs as V3D from table columns.
class VesuvioCalculateGammaBackground
class VesuvioCalculateMS
Calculates the multiple scattering & total scattering contributions for a flat-plate or cylindrical sample.
Typedefs
using ConvolutionFitSequential = ConvolutionFit< QENSFitSequential >
using ConvolutionFitSimultaneous = ConvolutionFit< QENSFitSimultaneous >
using IqtFitSequential = IqtFit< QENSFitSequential >
using IqtFitSimultaneous = IqtFit< QENSFitSimultaneous >
using LeBailFunction_sptr = std::shared_ptr< LeBailFunction >
Enumerations
enum SpecialIndex { NOT_SET = -1 , WHOLE_RANGE = -2 }
Functions
void addGroupWorkspace (std::vector< InputSpectraToFit > &nameList, double start, double end, int wi, int spec, int period, const std::shared_ptr< API::WorkspaceGroup > &wsg)
void addMatrixworkspace (std::vector< InputSpectraToFit > &nameList, double start, double end, std::string &name, int wi, int spec, int period, const boost::optional< API::Workspace_sptr > &workspaceOptional, const std::shared_ptr< API::MatrixWorkspace > &wsMatrix)
double calculateFunctionChiSquare (const std::vector< double > &modelY, const std::vector< double > &dataY, const std::vector< double > &dataE)
Calculate Chi^2.
void convertToDict (std::vector< std::string > strvec, std::map< std::string, size_t > &lookupdict)
Convert a vector to a lookup map (dictionary)
void copyParametersValues (std::map< std::string, Parameter > source, std::map< std::string, Parameter > &target)
Copy parameters values from source to target.
void duplicateParameters (std::map< std::string, Parameter > source, std::map< std::string, Parameter > &target)
Copy parameters from source to target.
void estimateBackgroundCoarse (const DataObjects::Workspace2D_sptr &dataws, const Functions::BackgroundFunction_sptr &background, size_t wsindexraw, size_t wsindexbkgd, size_t wsindexpeak)
Estimate background for a pattern in a coarse mode.
MANTID_CURVEFITTING_DLL Mantid::API::IFunction_sptr extractInnerFunction (std::shared_ptr< const API::MultiDomainFunction > const &function)
MANTID_CURVEFITTING_DLL Mantid::API::IFunction_sptr extractInnerFunction (std::shared_ptr< const Mantid::CurveFitting::Functions::Convolution > const &function)
size_t findMaxValue (const API::MatrixWorkspace_sptr &dataws, size_t wsindex, double leftbound, double rightbound)
Find maximum value.
size_t findMaxValue (const std::vector< double > &Y)
Find maximum value.
MANTID_CURVEFITTING_DLL Mantid::API::IFunction_sptr getDoublePulseFunction (std::shared_ptr< const API::IFunction > const &function, double offset, double firstPulseWeight, double secondPulseWeight)
MANTID_CURVEFITTING_DLL Mantid::API::IFunction_sptr getDoublePulseMultiDomainFunction (std::shared_ptr< const API::MultiDomainFunction > const &function, double offset, double firstPulseWeight, double secondPulseWeight)
std::string getFunctionInfo (const API::IFunction_sptr &function)
Get function parameter name, value and etc information in string.
int getStringIndex (std::map< std::string, size_t > lookupdict, const std::string &key)
Get the index from lookup dictionary (map)
MANTID_CURVEFITTING_DLL boost::optional< API::Workspace_sptr > getWorkspace (const std::string &name, int period)
MANTID_CURVEFITTING_DLL std::vector< int > getWorkspaceIndicesFromAxes (API::MatrixWorkspace &ws, int workspaceIndex, int spectrumNumber, double start, double end)
Get a workspace.
static double gsl_costFunction (const gsl_vector *x, void *params)
Calculating the cost function assuming it has the least-squared format.
static int gsl_df (const gsl_vector *x, void *params, gsl_matrix *J)
Fit1D GSL derivative function wrapper.
static int gsl_f (const gsl_vector *x, void *params, gsl_vector *f)
Fit1D GSL function wrapper.
static int gsl_fdf (const gsl_vector *x, void *params, gsl_vector *f, gsl_matrix *J)
Fit1D derivatives and function GSL wrapper.
template<class Type >
Type lexCast (std::string input, const std::string &errorMessage)
double linearInterpolateX (double x0, double xf, double y0, double yf, double y)
Formular for linear iterpolation: X = [(xf-x0)*Y - (xf*y0-x0*yf)]/(yf-y0)
double linearInterpolateY (double x0, double xf, double y0, double yf, double x)
Formula for linear interpolation: Y = ((xf*y0-x0*yf) + x*(yf-y0))/(xf-x0)
MANTID_CURVEFITTING_DLL std::vector< InputSpectraToFit > makeNames (const std::string &inputList, int default_wi, int default_spec)
Create a list of input workspace names.
bool observePeakParameters (const DataObjects::Workspace2D_sptr &dataws, size_t wsindex, double &centre, double &height, double &fwhm, std::string &errmsg)
Estimate peak parameters;.
void parseValueRange (const std::string &index, double &start, double &end, int &wi, int &spec)
void restoreFunctionParameterValue (map< string, pair< double, double > > parvaluemap, const IFunction_sptr &function, map< string, Parameter > &parammap)
Restore function parameter values saved in a (string,double) map to a function object and a (string, Parameter) map.
void restoreFunctionParameterValue (std::map< std::string, std::pair< double, double > > parvaluemap, const API::IFunction_sptr &function, std::map< std::string, Parameter > &parammap)
Restore function parameter values to a map.
void setMultiDataProperties (const Mantid::API::IAlgorithm &fittingAlgorithm, Mantid::API::IAlgorithm &fit, const Mantid::API::MatrixWorkspace_sptr &workspace, const std::string &suffix)
void setMultiDataProperties (const Mantid::API::IAlgorithm &fittingAlgorithm, Mantid::API::IAlgorithm &fit, const std::vector< Mantid::API::MatrixWorkspace_sptr > &workspaces)
void storeFunctionParameterValue (const API::IFunction_sptr &function, std::map< std::string, std::pair< double, double > > &parvaluemap)
Store function parameter values to a map.
void storeFunctionParameterValue (const IFunction_sptr &function, map< string, pair< double, double > > &parvaluemap)
Store function parameter values to a map.
void writeRfactorsToFile (std::vector< double > vecX, std::vector< Kernel::Rfactor > vecR, const std::string &filename)
Write a set of (XY) data to a column file.
Variables
const Rfactor badR (DBL_MAX, DBL_MAX)
Kernel::Logger g_log ("LeBailFunction")
double PEAK_POS_GUESS = -0.1
Starting value of peak position in y-space for fit.
double PEAK_WIDTH_GUESS = 4.0
Starting value of width in y-space for fit.
double SUMMEDY_BIN_WIDTH = 0.5
Bin width for rebinning workspace converted from TOF.
Typedef Documentation
ConvolutionFitSequential
using Mantid::CurveFitting::Algorithms::ConvolutionFitSequential = typedef ConvolutionFit<QENSFitSequential>
Definition at line 327 of file ConvolutionFit.cpp.
ConvolutionFitSimultaneous
using Mantid::CurveFitting::Algorithms::ConvolutionFitSimultaneous = typedef ConvolutionFit<QENSFitSimultaneous>
Definition at line 328 of file ConvolutionFit.cpp.
IqtFitSequential
using Mantid::CurveFitting::Algorithms::IqtFitSequential = typedef IqtFit<QENSFitSequential>
Definition at line 86 of file IqtFit.cpp.
IqtFitSimultaneous
using Mantid::CurveFitting::Algorithms::IqtFitSimultaneous = typedef IqtFit<QENSFitSimultaneous>
Definition at line 87 of file IqtFit.cpp.
LeBailFunction_sptr
using Mantid::CurveFitting::Algorithms::LeBailFunction_sptr = typedef std::shared_ptr<LeBailFunction>
Definition at line 191 of file LeBailFunction.h.
Enumeration Type Documentation
SpecialIndex
enum Mantid::CurveFitting::Algorithms::SpecialIndex
Enumerator
NOT_SET
WHOLE_RANGE
Definition at line 44 of file PlotPeakByLogValueHelper.h.
Function Documentation
addGroupWorkspace()
void Mantid::CurveFitting::Algorithms::addGroupWorkspace (std::vector< InputSpectraToFit > & nameList, double start, double end, int wi, int spec, int period, const std::shared_ptr< API::WorkspaceGroup > & wsg)
Definition at line 136 of file PlotPeakByLogValueHelper.cpp.
References addGroupWorkspace(), getWorkspaceIndicesFromAxes(), Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
Referenced by addGroupWorkspace(), and makeNames().
addMatrixworkspace()
void Mantid::CurveFitting::Algorithms::addMatrixworkspace (std::vector< InputSpectraToFit > & nameList, double start, double end, std::string & name, int wi, int spec, int period, const boost::optional< API::Workspace_sptr > & workspaceOptional, const std::shared_ptr< API::MatrixWorkspace > & wsMatrix)
Definition at line 124 of file PlotPeakByLogValueHelper.cpp.
References addMatrixworkspace(), and getWorkspaceIndicesFromAxes().
Referenced by addMatrixworkspace(), and makeNames().
calculateFunctionChiSquare()
double Mantid::CurveFitting::Algorithms::calculateFunctionChiSquare (const std::vector< double > & modelY, const std::vector< double > & dataY, const std::vector< double > & dataE)
Calculate Chi^2.
Definition at line 763 of file RefinePowderInstrumentParameters3.cpp.
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::calculateFunction(), and restoreFunctionParameterValue().
convertToDict()
void Mantid::CurveFitting::Algorithms::convertToDict (std::vector< std::string > strvec, std::map< std::string, size_t > & lookupdict)
Convert a vector to a lookup map (dictionary)
Definition at line 1242 of file RefinePowderInstrumentParameters3.cpp.
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::parseTableWorkspace().
copyParametersValues()
void Mantid::CurveFitting::Algorithms::copyParametersValues (std::map< std::string, Parameter > source, std::map< std::string, Parameter > & target)
Copy parameters values from source to target.
Copy parameters from source to target, i.e., clear the target and make it exacly same as source;.
Definition at line 1218 of file RefinePowderInstrumentParameters3.cpp.
References Mantid::CurveFitting::Algorithms::Parameter::curvalue.
Referenced by restoreFunctionParameterValue().
duplicateParameters()
void Mantid::CurveFitting::Algorithms::duplicateParameters (std::map< std::string, Parameter > source, std::map< std::string, Parameter > & target)
Copy parameters from source to target.
Copy parameters from source to target, i.e., clear the target and make it exacly same as source;.
Definition at line 1200 of file RefinePowderInstrumentParameters3.cpp.
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::bookKeepMCResult(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doSimulatedAnnealing(), and restoreFunctionParameterValue().
estimateBackgroundCoarse()
void Mantid::CurveFitting::Algorithms::estimateBackgroundCoarse (const DataObjects::Workspace2D_sptr & dataws, const BackgroundFunction_sptr & background, size_t wsindexraw, size_t wsindexbkgd, size_t wsindexpeak)
Estimate background for a pattern in a coarse mode.
Estimate background for a pattern in a coarse mode Assumption: the peak must be in the data range completely Algorithm: use two end data points for a linear background Output: dataws spectrum 3 (workspace index 2)
Parameters
dataws data workspace to estimate background for
background background function
wsindexraw workspace index of spectrum holding raw data
wsindexbkgd workspace index of spectrum holding background data
wsindexpeak workspace index of spectrum holding pure peak data (with background removed)
Definition at line 2909 of file FitPowderDiffPeaks.cpp.
References Mantid::API::FunctionValues::toVector(), Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitOverlappedPeaks(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident(), and Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust().
extractInnerFunction() [1/2]
Mantid::API::IFunction_sptr Mantid::CurveFitting::Algorithms::extractInnerFunction (std::shared_ptr< const API::MultiDomainFunction > const & function)
Definition at line 100 of file DoublePulseFit.cpp.
References extractInnerFunction().
extractInnerFunction() [2/2]
Mantid::API::IFunction_sptr Mantid::CurveFitting::Algorithms::extractInnerFunction (std::shared_ptr< const Mantid::CurveFitting::Functions::Convolution > const & function)
Definition at line 95 of file DoublePulseFit.cpp.
Referenced by Mantid::CurveFitting::Algorithms::DoublePulseFit::createOutput(), and extractInnerFunction().
findMaxValue() [1/2]
size_t Mantid::CurveFitting::Algorithms::findMaxValue (const MatrixWorkspace_sptr & dataws, size_t wsindex, double leftbound, double rightbound)
Find maximum value.
Parameters
dataws :: a workspace to check
wsindex :: the spectrum to check
leftbound :: lower constraint for check
rightbound :: upper constraint for check
Returns
the index of the maximum value
Definition at line 3089 of file FitPowderDiffPeaks.cpp.
References Mantid::Geometry::X, and Mantid::Geometry::Y.
findMaxValue() [2/2]
size_t Mantid::CurveFitting::Algorithms::findMaxValue (const std::vector< double > & Y)
Find maximum value.
Parameters
Y :: vector to get maximum value from
Returns
index of the maximum value
Definition at line 3075 of file FitPowderDiffPeaks.cpp.
References Mantid::Geometry::Y.
Referenced by Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident(), observePeakParameters(), and Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::observePeakRange().
getDoublePulseFunction()
Mantid::API::IFunction_sptr Mantid::CurveFitting::Algorithms::getDoublePulseFunction (std::shared_ptr< const API::IFunction > const & function, double offset, double firstPulseWeight, double secondPulseWeight)
Definition at line 56 of file DoublePulseFit.cpp.
Referenced by Mantid::CurveFitting::Algorithms::DoublePulseFit::execConcrete(), and getDoublePulseMultiDomainFunction().
getDoublePulseMultiDomainFunction()
Mantid::API::IFunction_sptr Mantid::CurveFitting::Algorithms::getDoublePulseMultiDomainFunction (std::shared_ptr< const API::MultiDomainFunction > const & function, double offset, double firstPulseWeight, double secondPulseWeight)
Definition at line 82 of file DoublePulseFit.cpp.
References getDoublePulseFunction().
Referenced by Mantid::CurveFitting::Algorithms::DoublePulseFit::execConcrete().
getFunctionInfo()
string Mantid::CurveFitting::Algorithms::getFunctionInfo (const IFunction_sptr & function)
Get function parameter name, value and etc information in string.
Get function parameter values information and returned as a string.
Parameters
function function to have information written out
Definition at line 2886 of file FitPowderDiffPeaks.cpp.
Referenced by Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakBackground(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), and Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak().
getStringIndex()
int Mantid::CurveFitting::Algorithms::getStringIndex (std::map< std::string, size_t > lookupdict, const std::string & key)
Get the index from lookup dictionary (map)
Definition at line 1252 of file RefinePowderInstrumentParameters3.cpp.
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::parseTableWorkspace().
getWorkspace()
boost::optional< API::Workspace_sptr > Mantid::CurveFitting::Algorithms::getWorkspace (const std::string & name, int period)
Definition at line 202 of file PlotPeakByLogValueHelper.cpp.
References Mantid::API::g_log, getWorkspace(), Mantid::Kernel::SingletonHolder< T >::Instance(), std::to_string(), and Mantid::Kernel::Logger::warning().
Referenced by getWorkspace(), and makeNames().
getWorkspaceIndicesFromAxes()
std::vector< int > Mantid::CurveFitting::Algorithms::getWorkspaceIndicesFromAxes (API::MatrixWorkspace & ws, int workspaceIndex, int spectrumNumber, double start, double end)
Get a workspace.
Get a workspace identified by an InputSpectraToFit structure.
Parameters
ws :: Workspace to fit required to work out indices
workspaceIndex :: workspace index to use
spectrumNumber :: spectrum number to use
start :: Start of range for value based spectrum range
end :: End of range for value based spectrum range
Returns
Vector of workspace indices to fit
Definition at line 161 of file PlotPeakByLogValueHelper.cpp.
References Mantid::API::MatrixWorkspace::getAxis(), getWorkspaceIndicesFromAxes(), Mantid::API::Axis::isSpectra(), Mantid::API::Axis::length(), and Mantid::API::Axis::spectraNo().
Referenced by addGroupWorkspace(), addMatrixworkspace(), and getWorkspaceIndicesFromAxes().
gsl_costFunction()
static double Mantid::CurveFitting::Algorithms::gsl_costFunction (const gsl_vector * x, void * params) static
Calculating the cost function assuming it has the least-squared format.
Initially implemented to use the gsl simplex routine within the least-squared scheme.
Parameters
x :: Input function arguments
params :: Input data
Returns
Value of least squared cost function
Definition at line 181 of file Fit1D.cpp.
References Mantid::CurveFitting::Algorithms::FitData::forSimplexLSwrap, and Mantid::Geometry::x.
gsl_df()
static int Mantid::CurveFitting::Algorithms::gsl_df (const gsl_vector * x, void * params, gsl_matrix * J) static
Fit1D GSL derivative function wrapper.
Parameters
x :: Input function arguments
params :: Input data
J :: Output derivatives
Returns
A GSL status information
Definition at line 139 of file Fit1D.cpp.
References Mantid::CurveFitting::gsl_df(), Mantid::CurveFitting::Algorithms::FitData::parameters, and Mantid::Geometry::x.
gsl_f()
static int Mantid::CurveFitting::Algorithms::gsl_f (const gsl_vector * x, void * params, gsl_vector * f) static
Fit1D GSL function wrapper.
Parameters
x :: Input function arguments
params :: Input data
f :: Output function values = (y_cal-y_data)/sigma for each data point
Returns
A GSL status information
Definition at line 116 of file Fit1D.cpp.
References Mantid::CurveFitting::gsl_f(), Mantid::CurveFitting::Algorithms::FitData::parameters, and Mantid::Geometry::x.
gsl_fdf()
static int Mantid::CurveFitting::Algorithms::gsl_fdf (const gsl_vector * x, void * params, gsl_vector * f, gsl_matrix * J) static
Fit1D derivatives and function GSL wrapper.
Parameters
x :: Input function arguments
params :: Input data
f :: Output function values = (y_cal-y_cal)/sigma for each data point
J :: Output derivatives
Returns
A GSL status information
Definition at line 168 of file Fit1D.cpp.
References Mantid::CurveFitting::gsl_df(), Mantid::CurveFitting::gsl_f(), Mantid::CurveFitting::gsl_fdf(), and Mantid::Geometry::x.
lexCast()
template<class Type > Type Mantid::CurveFitting::Algorithms::lexCast (std::string input, const std::string & errorMessage)
Definition at line 26 of file PlotPeakByLogValueHelper.cpp.
References lexCast().
Referenced by lexCast().
linearInterpolateX()
double Mantid::CurveFitting::Algorithms::linearInterpolateX (double x0, double xf, double y0, double yf, double y) inline
Formular for linear iterpolation: X = [(xf-x0)*Y - (xf*y0-x0*yf)]/(yf-y0)
Definition at line 348 of file FitPowderDiffPeaks.h.
References linearInterpolateX(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by linearInterpolateX(), and observePeakParameters().
linearInterpolateY()
double Mantid::CurveFitting::Algorithms::linearInterpolateY (double x0, double xf, double y0, double yf, double x) inline
Formula for linear interpolation: Y = ((xf*y0-x0*yf) + x*(yf-y0))/(xf-x0)
Definition at line 355 of file FitPowderDiffPeaks.h.
References linearInterpolateY(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by linearInterpolateY().
makeNames()
std::vector< InputSpectraToFit > Mantid::CurveFitting::Algorithms::makeNames (const std::string & inputList, int default_wi, int default_spec)
Create a list of input workspace names.
Definition at line 77 of file PlotPeakByLogValueHelper.cpp.
References addGroupWorkspace(), addMatrixworkspace(), Mantid::Kernel::StringTokenizer::count(), getWorkspace(), index, makeNames(), parseValueRange(), Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY, and Mantid::Kernel::StringTokenizer::TOK_TRIM.
Referenced by Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), makeNames(), and Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::validateInputs().
observePeakParameters()
bool Mantid::CurveFitting::Algorithms::observePeakParameters (const Workspace2D_sptr & dataws, size_t wsindex, double & centre, double & height, double & fwhm, string & errmsg)
Estimate peak parameters;.
Estimate peak parameters; Prerequisit: (1) Background removed (2) Peak is inside Algorithm: From the top.
Get the maximum value. Calculate the half maximum value. Find the range of X
Parameters
dataws data workspace containing peak data
wsindex :: index of a histogram
centre :: (output) peak centre
height :: (output) peak height
fwhm :: (output) peak FWHM
errmsg :: (output) error message
Definition at line 2980 of file FitPowderDiffPeaks.cpp.
References findMaxValue(), height, index, linearInterpolateX(), Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust().
parseValueRange()
void Mantid::CurveFitting::Algorithms::parseValueRange (const std::string & index, double & start, double & end, int & wi, int & spec)
Definition at line 34 of file PlotPeakByLogValueHelper.cpp.
References Mantid::Kernel::StringTokenizer::count(), index, NOT_SET, parseValueRange(), Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY, Mantid::Kernel::StringTokenizer::TOK_TRIM, and WHOLE_RANGE.
Referenced by makeNames(), and parseValueRange().
restoreFunctionParameterValue() [1/2]
void Mantid::CurveFitting::Algorithms::restoreFunctionParameterValue (map< string, pair< double, double > > parvaluemap, const IFunction_sptr & function, map< string, Parameter > & parammap)
Restore function parameter values saved in a (string,double) map to a function object and a (string, Parameter) map.
Definition at line 1289 of file RefinePowderInstrumentParameters3.cpp.
restoreFunctionParameterValue() [2/2]
void Mantid::CurveFitting::Algorithms::restoreFunctionParameterValue (std::map< std::string, std::pair< double, double > > parvaluemap, const API::IFunction_sptr & function, std::map< std::string, Parameter > & parammap)
Restore function parameter values to a map.
References calculateFunctionChiSquare(), copyParametersValues(), duplicateParameters(), and restoreFunctionParameterValue().
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::fitFunction(), and restoreFunctionParameterValue().
setMultiDataProperties() [1/2]
void Mantid::CurveFitting::Algorithms::setMultiDataProperties (const Mantid::API::IAlgorithm & fittingAlgorithm, Mantid::API::IAlgorithm & fit, const Mantid::API::MatrixWorkspace_sptr & workspace, const std::string & suffix)
Definition at line 32 of file DoublePulseFit.cpp.
References Mantid::Kernel::IPropertyManager::getProperty(), Mantid::Kernel::IPropertyManager::setProperty(), and workspace.
Referenced by Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::CurveFitting::Algorithms::DoublePulseFit::runFitAlgorith(), and setMultiDataProperties().
setMultiDataProperties() [2/2]
void Mantid::CurveFitting::Algorithms::setMultiDataProperties (const Mantid::API::IAlgorithm & fittingAlgorithm, Mantid::API::IAlgorithm & fit, const std::vector< Mantid::API::MatrixWorkspace_sptr > & workspaces)
Definition at line 48 of file DoublePulseFit.cpp.
References setMultiDataProperties(), and std::to_string().
storeFunctionParameterValue() [1/2]
void Mantid::CurveFitting::Algorithms::storeFunctionParameterValue (const API::IFunction_sptr & function, std::map< std::string, std::pair< double, double > > & parvaluemap)
Store function parameter values to a map.
References storeFunctionParameterValue().
Referenced by Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::fitFunction(), and storeFunctionParameterValue().
storeFunctionParameterValue() [2/2]
void Mantid::CurveFitting::Algorithms::storeFunctionParameterValue (const IFunction_sptr & function, map< string, pair< double, double > > & parvaluemap)
Store function parameter values to a map.
Definition at line 1272 of file RefinePowderInstrumentParameters3.cpp.
writeRfactorsToFile()
void Mantid::CurveFitting::Algorithms::writeRfactorsToFile (std::vector< double > vecX, std::vector< Kernel::Rfactor > vecR, const std::string & filename)
Write a set of (XY) data to a column file.
Definition at line 2225 of file LeBailFit.cpp.
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain().
Variable Documentation
badR
const Rfactor Mantid::CurveFitting::Algorithms::badR(DBL_MAX, DBL_MAX) (DBL_MAX , DBL_MAX)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::calculateDiffractionPattern().
g_log
Kernel::Logger Mantid::CurveFitting::Algorithms::g_log("LeBailFunction") ("LeBailFunction")
PEAK_POS_GUESS
double Mantid::CurveFitting::Algorithms::PEAK_POS_GUESS = -0.1
Starting value of peak position in y-space for fit.
Definition at line 28 of file NormaliseByPeakArea.cpp.
Referenced by Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak().
PEAK_WIDTH_GUESS
double Mantid::CurveFitting::Algorithms::PEAK_WIDTH_GUESS = 4.0
Starting value of width in y-space for fit.
Definition at line 30 of file NormaliseByPeakArea.cpp.
Referenced by Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak().
SUMMEDY_BIN_WIDTH
double Mantid::CurveFitting::Algorithms::SUMMEDY_BIN_WIDTH = 0.5
Bin width for rebinning workspace converted from TOF.
Definition at line 32 of file NormaliseByPeakArea.cpp.
Referenced by Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::convertInputToY().