Mantid: MantidQt::MantidWidgets::IImageInfoWidget Class Reference
MantidQt::MantidWidgets::IImageInfoWidget Class Reference abstract
#include <IImageInfoWidget.h>
Public Member Functions
virtual void cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues)=0
virtual void hideColumn (const int index)=0
virtual void setColumnCount (const int count)=0
virtual void setItem (const int rowIndex, const int columnIndex, QTableWidgetItem *item)=0
virtual void setRowCount (const int count)=0
virtual void setWorkspace (const Mantid::API::Workspace_sptr &ws)=0
virtual void showColumn (const int index)=0
virtual void showInfo (const ImageInfoModel::ImageInfo &info)=0
virtual ~IImageInfoWidget ()=default
Detailed Description
Definition at line 17 of file IImageInfoWidget.h.
Constructor & Destructor Documentation
~IImageInfoWidget()
virtual MantidQt::MantidWidgets::IImageInfoWidget::~IImageInfoWidget () virtual default
Member Function Documentation
cursorAt()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
hideColumn()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::hideColumn (const int index) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::fillTableCells().
setColumnCount()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::setColumnCount (const int count) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::fillTableCells().
setItem()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::setItem (const int rowIndex, const int columnIndex, QTableWidgetItem * item) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::fillTableCells().
setRowCount()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::setRowCount (const int count) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::ImageInfoPresenter().
setWorkspace()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::setWorkspace (const Mantid::API::Workspace_sptr & ws) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
showColumn()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::showColumn (const int index) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::fillTableCells().
showInfo()
virtual void MantidQt::MantidWidgets::IImageInfoWidget::showInfo (const ImageInfoModel::ImageInfo & info) pure virtual
Implemented in MantidQt::MantidWidgets::ImageInfoWidget, and MantidQt::MantidWidgets::ImageInfoWidgetMini.
Referenced by MantidQt::MantidWidgets::ImageInfoPresenter::cursorAt().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IImageInfoWidget.h