Mantid: Mantid::DataHandling::LoadRawBin0 Class Reference
Mantid::DataHandling::LoadRawBin0 Class Reference
Loads bin zero for all spectra from ISIS RAW file and stores it in a 2D workspace (Workspace2D class).
#include <LoadRawBin0.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
LoadRawBin0 ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::DataHandling::LoadRawHelper
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadRawHelper ()
Default constructor.
void loadRunParameters (const API::MatrixWorkspace_sptr &localWorkspace, ISISRAW *const =nullptr) const
Read in run parameters Public so that LoadRaw2 can use it.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
FILE * openRawFile (const std::string &fileName)
Opens Raw File.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
~LoadRawHelper () override
Destructor.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void exec () override
Overwrites Algorithm method.
void init () override
Overwrites Algorithm method.
void setOptionalProperties ()
This sets the optional property to the LoadRawHelper class.
Private Attributes
std::shared_ptr< ISISRAW2 > isisRaw
ISISRAW class instance which does raw file reading.
std::vector< std::string > m_cache_options
Allowed values for the cache property.
std::string m_filename
The name and path of the input file.
int64_t m_lengthIn
Read in the time bin boundaries.
int64_t m_noTimeRegimes
number of time regime
specnum_t m_numberOfSpectra
The number of spectra in the raw file.
std::shared_ptr< Kernel::Property > m_perioids
TimeSeriesProperty<int> containing data periods.
double m_prog
The current value of the progress counter.
std::map< int64_t, int64_t > m_specTimeRegimes
A map for storing the time regime for each spectrum.
std::vector< std::shared_ptr< HistogramData::HistogramX > > m_timeChannelsVec
time channel vector
specnum_t m_total_specs
total number of specs
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::DataHandling::LoadRawHelper
static API::WorkspaceGroup_sptr createGroupWorkspace ()
creates shared pointer to group workspace
static void createMonitorWorkspace (DataObjects::Workspace2D_sptr &monws_sptr, const DataObjects::Workspace2D_sptr &normalws_sptr, API::WorkspaceGroup_sptr &mongrp_sptr, const int64_t mwsSpecs, const int64_t nwsSpecs, const int64_t numberOfPeriods, const int64_t lengthIn, const std::string &title, API::Algorithm *const pAlg)
creates monitor workspace
static DataObjects::Workspace2D_sptr createWorkspace (const DataObjects::Workspace2D_sptr &ws_sptr, int64_t nVectors=-1, int64_t xLengthIn=-1, int64_t yLengthIn=-1)
creates shared pointer to workspace from parent workspace
static DataObjects::Workspace2D_sptr createWorkspace (int64_t nVectors, int64_t xlengthIn, int64_t ylengthIn, const std::string &title)
overloaded method to create shared pointer to workspace
static Types::Core::DateAndTime extractEndTime (ISISRAW &isisRaw)
Extract the end time from a raw file.
static Types::Core::DateAndTime extractStartTime (ISISRAW &isisRaw)
Extract the start time from a raw file.
static bool isExcludeMonitors (const std::string &monitorOption)
returns true if the Exclude Monitor option(property) selected
static bool isIncludeMonitors (const std::string &monitorOption)
returns true if the Include Monitor Option selected
static bool isSeparateMonitors (const std::string &monitorOption)
returns true if the Separate Monitor Option selected
static void ProcessLoadMonitorOptions (bool &bincludeMonitors, bool &bseparateMonitors, bool &bexcludeMonitors, const API::Algorithm *pAlgo)
The method to interpret LoadMonitors property options and convert then into boolean values.
static std::list< std::string > searchForLogFiles (const std::filesystem::path &pathToRawFile)
Search for the log files in the workspace, and output their names as a list.
static void setWorkspaceProperty (const DataObjects::Workspace2D_sptr &ws_sptr, const API::WorkspaceGroup_sptr &grpws_sptr, const int64_t period, bool bmonitors, API::Algorithm *const pAlg)
overloaded method to set the workspace property
static void setWorkspaceProperty (const std::string &propertyName, const std::string &title, const API::WorkspaceGroup_sptr &grpws_sptr, const DataObjects::Workspace2D_sptr &ws_sptr, int64_t numberOfPeriods, bool bMonitor, API::Algorithm *const pAlg)
sets the workspace property
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::DataHandling::LoadRawHelper
specnum_t calculateWorkspaceSize ()
calculate workspace size
void calculateWorkspacesizes (const std::vector< specnum_t > &monitorSpecList, specnum_t &normalwsSpecs, specnum_t &monitorwsSpecs)
calculate workspace sizes if separate or exclude monitors are selected
void checkOptionalProperties ()
Validates the optional 'spectra to read' properties, if they have been set.
void createPeriodLogs (int64_t period, const DataObjects::Workspace2D_sptr &local_workspace)
Create the period specific logs.
std::vector< specnum_t > getmonitorSpectrumList (const API::SpectrumDetectorMapping &mapping)
gets the monitor spectrum list from the workspace
int getNumberofTimeRegimes ()
number of time regimes
float getProtonCharge () const
get proton charge from raw file
std::vector< std::shared_ptr< HistogramData::HistogramX > > getTimeChannels (const int64_t &regimes, const int64_t &lengthIn)
Constructs the time channel (X) vector(s)
void init () override
Overwrites Algorithm method.
void ioRaw (FILE *file, bool from_file)
calls isisRaw ioraw
ISISRAW2 & isisRaw () const
return an reference to the ISISRAW2 reader
void loadSpectra (FILE *file, const int &period, const int &total_specs, const DataObjects::Workspace2D_sptr &ws_sptr, const std::vector< std::shared_ptr< HistogramData::HistogramX > > &)
load the spectra
bool readData (FILE *file, int hist)
reads data
bool readData (FILE *file, int64_t hist)
void readTitle (FILE *file, std::string &title)
Reads title from the isisraw class.
void readworkspaceParameters (specnum_t &numberOfSpectra, int &numberOfPeriods, int64_t &lengthIn, int64_t &noTimeRegimes)
reads workspace parameters like number of histograms,size of vectors etc
void reset ()
resets the isisraw shared pointer
void runLoadInstrument (const std::string &fileName, const DataObjects::Workspace2D_sptr &, double, double)
loadinstrument Child Algorithm
void runLoadInstrumentFromRaw (const std::string &fileName, const DataObjects::Workspace2D_sptr &)
loadinstrumentfromraw algorithm
void runLoadLog (const std::string &fileName, const DataObjects::Workspace2D_sptr &, double, double)
load log algorithm
void runLoadMappingTable (const std::string &fileName, const DataObjects::Workspace2D_sptr &)
loadinstrumentfromraw Child Algorithm
void setOptionalProperties (const int &spec_min, const int &spec_max, const std::vector< int > &spec_list)
sets optional properties like spec_min,spec_max etc
void setProtonCharge (API::Run &run)
set proton charge
void setRunNumber (API::Run &run)
Stores the run number in the sample's logs.
void setWorkspaceData (const DataObjects::Workspace2D_sptr &newWorkspace, const std::vector< std::shared_ptr< HistogramData::HistogramX > > &timeChannelsVec, int64_t wsIndex, specnum_t nspecNum, int64_t noTimeRegimes, int64_t lengthIn, int64_t binStart)
This method sets the raw file data to workspace vectors.
void skipData (FILE *file, int hist)
skips histrogram data from raw file.
void skipData (FILE *file, int64_t hist)
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::DataHandling::LoadRawHelper
bool m_interval
Have the spectrum_min/max properties been set?
bool m_list
Has the spectrum_list property been set?
int m_numberOfPeriods
The number of periods in the raw file.
std::vector< specnum_t > m_spec_list
The value of the spectrum_list property.
specnum_t m_spec_max
The value of the spectrum_max property.
specnum_t m_spec_min
The value of the spectrum_min property.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Loads bin zero for all spectra from ISIS RAW file and stores it in a 2D workspace (Workspace2D class).
LoadRawBin0 is an algorithm and as such inherits from the Algorithm class and overrides the init() & exec() methods.
Required Properties:
Filename - The name of and path to the input RAW file
OutputWorkspace - The name of the workspace in which to store the imported data (a multiperiod file will store higher periods in workspaces called OutputWorkspace_PeriodNo)
Optional Properties: (note that these options are not available if reading a
multiperiod file)
spectrum_min - The spectrum to start loading from
spectrum_max - The spectrum to load to
spectrum_list - An ArrayProperty of spectra to load
Author
Sofia Antony,ISIS,RAL
Date
12/04/2010
Definition at line 53 of file LoadRawBin0.h.
Constructor & Destructor Documentation
LoadRawBin0()
Mantid::DataHandling::LoadRawBin0::LoadRawBin0 ()
Default constructor.
Constructor.
Definition at line 31 of file LoadRawBin0.cpp.
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadRawBin0::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 69 of file LoadRawBin0.h.
exec()
void Mantid::DataHandling::LoadRawBin0::exec () override private virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Exceptions
Exception::FileError If the RAW file cannot be found/opened
std::invalid_argument If the optional properties are set to invalid values
Implements Mantid::API::Algorithm.
Definition at line 54 of file LoadRawBin0.cpp.
References Mantid::DataHandling::LoadRawHelper::calculateWorkspaceSize(), Mantid::DataHandling::LoadRawHelper::checkOptionalProperties(), Mantid::DataHandling::LoadRawHelper::createGroupWorkspace(), Mantid::DataHandling::LoadRawHelper::createPeriodLogs(), Mantid::DataHandling::LoadRawHelper::createWorkspace(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::Algorithm::interruption_point(), Mantid::Kernel::FileDescriptor::isAscii(), isisRaw, m_filename, m_lengthIn, Mantid::DataHandling::LoadRawHelper::m_list, m_noTimeRegimes, Mantid::DataHandling::LoadRawHelper::m_numberOfPeriods, m_numberOfSpectra, m_prog, Mantid::DataHandling::LoadRawHelper::m_spec_list, Mantid::DataHandling::LoadRawHelper::m_spec_max, Mantid::DataHandling::LoadRawHelper::m_spec_min, m_timeChannelsVec, m_total_specs, Mantid::DataHandling::LoadRawHelper::openRawFile(), Mantid::API::Algorithm::progress(), Mantid::DataHandling::LoadRawHelper::readData(), Mantid::DataHandling::LoadRawHelper::readTitle(), Mantid::DataHandling::LoadRawHelper::readworkspaceParameters(), Mantid::API::LogManager::removeLogData(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), setOptionalProperties(), Mantid::DataHandling::LoadRawHelper::setProtonCharge(), Mantid::DataHandling::LoadRawHelper::setWorkspaceData(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), and Mantid::DataHandling::LoadRawHelper::skipData().
init()
void Mantid::DataHandling::LoadRawBin0::init () override private virtual
Overwrites Algorithm method.
Initialisation method.
Implements Mantid::API::Algorithm.
Definition at line 36 of file LoadRawBin0.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), and Mantid::DataHandling::LoadRawHelper::init().
name()
const std::string Mantid::DataHandling::LoadRawBin0::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 58 of file LoadRawBin0.h.
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadRawBin0::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 67 of file LoadRawBin0.h.
setOptionalProperties()
void Mantid::DataHandling::LoadRawBin0::setOptionalProperties () private
This sets the optional property to the LoadRawHelper class.
Definition at line 167 of file LoadRawBin0.cpp.
References Mantid::API::Algorithm::getProperty(), Mantid::DataHandling::LoadRawHelper::m_spec_list, Mantid::DataHandling::LoadRawHelper::m_spec_max, and Mantid::DataHandling::LoadRawHelper::m_spec_min.
Referenced by exec().
summary()
const std::string Mantid::DataHandling::LoadRawBin0::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 60 of file LoadRawBin0.h.
version()
int Mantid::DataHandling::LoadRawBin0::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 66 of file LoadRawBin0.h.
Member Data Documentation
isisRaw
std::shared_ptr<ISISRAW2> Mantid::DataHandling::LoadRawBin0::isisRaw private
ISISRAW class instance which does raw file reading.
Shared pointer to prevent memory leak when an exception is thrown.
Definition at line 82 of file LoadRawBin0.h.
Referenced by exec().
m_cache_options
std::vector<std::string> Mantid::DataHandling::LoadRawBin0::m_cache_options private
Allowed values for the cache property.
Definition at line 92 of file LoadRawBin0.h.
m_filename
std::string Mantid::DataHandling::LoadRawBin0::m_filename private
The name and path of the input file.
Definition at line 84 of file LoadRawBin0.h.
Referenced by exec().
m_lengthIn
int64_t Mantid::DataHandling::LoadRawBin0::m_lengthIn private
Read in the time bin boundaries.
Definition at line 99 of file LoadRawBin0.h.
Referenced by exec().
m_noTimeRegimes
int64_t Mantid::DataHandling::LoadRawBin0::m_noTimeRegimes private
number of time regime
Definition at line 89 of file LoadRawBin0.h.
Referenced by exec().
m_numberOfSpectra
specnum_t Mantid::DataHandling::LoadRawBin0::m_numberOfSpectra private
The number of spectra in the raw file.
Definition at line 87 of file LoadRawBin0.h.
Referenced by exec().
m_perioids
std::shared_ptr<Kernel::Property> Mantid::DataHandling::LoadRawBin0::m_perioids private
TimeSeriesProperty<int> containing data periods.
Definition at line 101 of file LoadRawBin0.h.
m_prog
double Mantid::DataHandling::LoadRawBin0::m_prog private
The current value of the progress counter.
Definition at line 96 of file LoadRawBin0.h.
Referenced by exec().
m_specTimeRegimes
std::map<int64_t, int64_t> Mantid::DataHandling::LoadRawBin0::m_specTimeRegimes private
A map for storing the time regime for each spectrum.
Definition at line 94 of file LoadRawBin0.h.
m_timeChannelsVec
std::vector<std::shared_ptr<HistogramData::HistogramX> > Mantid::DataHandling::LoadRawBin0::m_timeChannelsVec private
time channel vector
Definition at line 106 of file LoadRawBin0.h.
Referenced by exec().
m_total_specs
specnum_t Mantid::DataHandling::LoadRawBin0::m_total_specs private
total number of specs
Definition at line 104 of file LoadRawBin0.h.
Referenced by exec().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadRawBin0.h
Framework/DataHandling/src/LoadRawBin0.cpp