Mantid: Mantid::API::IWorkspaceProperty Class Reference
Mantid::API::IWorkspaceProperty Class Reference abstract
An interface that is implemented by WorkspaceProperty.
#include <IWorkspaceProperty.h>
Public Member Functions
virtual void clear ()=0
Clear the stored pointer.
virtual Workspace_sptr getWorkspace () const =0
Get a pointer to the workspace.
virtual bool isLocking () const =0
Will the workspace be locked when starting an algorithm?
virtual bool isOptional () const =0
Is the input workspace property optional (can be blank)?
virtual void setIsMasterRank (bool isMasterRank)=0
Sets a flag indicating whether this is the master rank in MPI builds.
virtual bool store ()=0
Store a workspace into the AnalysisDataService.
virtual ~IWorkspaceProperty ()=default
Virtual destructor.
Detailed Description
An interface that is implemented by WorkspaceProperty.
Used for non templated workspace operations.
Author
Nick Draper, Tessella Support Services plc
Russell Taylor, Tessella Support Services plc
Date
11/12/2007
Definition at line 23 of file IWorkspaceProperty.h.
Constructor & Destructor Documentation
~IWorkspaceProperty()
virtual Mantid::API::IWorkspaceProperty::~IWorkspaceProperty () virtual default
Virtual destructor.
Member Function Documentation
clear()
virtual void Mantid::API::IWorkspaceProperty::clear () pure virtual
Clear the stored pointer.
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
getWorkspace()
virtual Workspace_sptr Mantid::API::IWorkspaceProperty::getWorkspace () const pure virtual
Get a pointer to the workspace.
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
Referenced by Mantid::API::Algorithm::findWorkspaces(), Mantid::API::IndexProperty::getIndexInfoFromWorkspace(), and Mantid::API::IndexProperty::isValid().
isLocking()
virtual bool Mantid::API::IWorkspaceProperty::isLocking () const pure virtual
Will the workspace be locked when starting an algorithm?
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
isOptional()
virtual bool Mantid::API::IWorkspaceProperty::isOptional () const pure virtual
Is the input workspace property optional (can be blank)?
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
setIsMasterRank()
virtual void Mantid::API::IWorkspaceProperty::setIsMasterRank (bool isMasterRank) pure virtual
Sets a flag indicating whether this is the master rank in MPI builds.
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
store()
virtual bool Mantid::API::IWorkspaceProperty::store () pure virtual
Store a workspace into the AnalysisDataService.
Implemented in Mantid::API::WorkspaceProperty< TYPE >.
Referenced by Mantid::API::Algorithm::store().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IWorkspaceProperty.h