Mantid: Mantid::Geometry::BoolValue Class Reference
Mantid::Geometry::BoolValue Class Reference
Rule Status class.
#include <Rules.h>
Public Member Functions
BoolValue ()
Constructor.
std::string className () const override
Returns class name as string.
std::unique_ptr< BoolValue > clone () const
Clone constructor.
std::string display () const override
std::string displayAddress () const override
Returns the memory address as a string.
Rule * findKey (const int) override
Abstract key find.
int findLeaf (const Rule *) const override
Abstract find.
void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) override
gets the bounding box for the BoolValue Rule
bool isValid (const Kernel::V3D &) const override
Determines if a point is valid.
bool isValid (const std::map< int, int > &) const override
isValue :: Based on a surface status map
Rule * leaf (const int=0) const override
No leaves.
void setLeaf (std::unique_ptr< Rule >, const int=0) override
Replaces a leaf with a rule.
void setLeaves (std::unique_ptr< Rule >, std::unique_ptr< Rule >) override
Replaces a leaf with a rule.
void setStatus (int val)
< write val into status, if in valid range
int simplify () override
Bool value is always in simplest form.
int type () const override
Null rule.
Public Member Functions inherited from Mantid::Geometry::Rule
int checkParents () const
Debug test for parents.
std::unique_ptr< Rule > clone () const
int commonType () const
Gets a common type.
int Eliminate ()
elimination not written
int getKeyList (std::vector< int > &) const
Generate the key list given an insertion type object.
Rule * getParent () const
Returns the parent object.
virtual int isComplementary () const
Always returns false (0)
void makeParents ()
This is initialisation code that populates all the parents in the rule tree.
Rule ()
Standard Constructor.
Rule (Rule *)
Constructor copies.
void setParent (Rule *)
Sets the parent object (not check for A==this)
int substituteSurf (const int SurfN, const int newSurfN, const std::shared_ptr< Surface > &SPtr)
Substitues a surface item if within a rule.
virtual ~Rule ()=default
Protected Member Functions
BoolValue (const BoolValue &)=default
BoolValue & operator= (const BoolValue &)
Assignment operator.
Protected Member Functions inherited from Mantid::Geometry::Rule
Rule & operator= (const Rule &)
Assignment operator= does not set parent as Rules are cloned.
Rule (const Rule &)
Constructor copies.
Private Member Functions
BoolValue * doClone () const override
Clone constructor.
Private Attributes
int status
Three values 0 False : 1 True : -1 doesn't matter.
Additional Inherited Members
Static Public Member Functions inherited from Mantid::Geometry::Rule
static int makeCNF (std::unique_ptr< Rule > &)
Make Rule into a CNF format.
static int makeCNFcopy (std::unique_ptr< Rule > &)
Make Rule into a CNF format (slow)
static int makeFullDNF (std::unique_ptr< Rule > &)
Make Rule into a full DNF format.
static int removeComplementary (std::unique_ptr< Rule > &)
NOT WORKING.
static int removeItem (std::unique_ptr< Rule > &TRule, const int SurfN)
Given an item as a surface name, remove the surface from the Rule tree.
Detailed Description
Rule Status class.
Author
S.Ansell
Version
1.0
Date
April 2005
Class to handle a rule with a truth value but can be true/false/unknown.
Definition at line 363 of file Rules.h.
Constructor & Destructor Documentation
BoolValue() [1/2]
Mantid::Geometry::BoolValue::BoolValue (const BoolValue &) protected default
BoolValue() [2/2]
Mantid::Geometry::BoolValue::BoolValue ()
Constructor.
Definition at line 1181 of file RuleItems.cpp.
Referenced by doClone().
Member Function Documentation
className()
std::string Mantid::Geometry::BoolValue::className () const inline override virtual
Returns class name as string.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 375 of file Rules.h.
clone()
std::unique_ptr< BoolValue > Mantid::Geometry::BoolValue::clone () const
Clone constructor.
Returns
new(*this)
Definition at line 1211 of file RuleItems.cpp.
References doClone().
display()
std::string Mantid::Geometry::BoolValue::display () const override virtual
Returns
string of
"true" "false" or "unknown"
Implements Mantid::Geometry::Rule.
Definition at line 1283 of file RuleItems.cpp.
References status.
displayAddress()
std::string Mantid::Geometry::BoolValue::displayAddress () const override virtual
Returns the memory address as a string.
Returns
string of Address
Implements Mantid::Geometry::Rule.
Definition at line 1299 of file RuleItems.cpp.
doClone()
BoolValue * Mantid::Geometry::BoolValue::doClone () const override private virtual
Clone constructor.
Returns
new(*this)
Implements Mantid::Geometry::Rule.
Definition at line 1202 of file RuleItems.cpp.
References BoolValue().
Referenced by clone().
findKey()
Rule * Mantid::Geometry::BoolValue::findKey (const int) inline override virtual
Abstract key find.
Implements Mantid::Geometry::Rule.
Definition at line 381 of file Rules.h.
findLeaf()
int Mantid::Geometry::BoolValue::findLeaf (const Rule *) const override virtual
Abstract find.
Implements Mantid::Geometry::Rule.
Definition at line 1250 of file RuleItems.cpp.
getBoundingBox()
void Mantid::Geometry::BoolValue::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) override virtual
gets the bounding box for the BoolValue Rule
Parameters
xmax :: Maximum value for the bounding box in x direction
ymax :: Maximum value for the bounding box in y direction
zmax :: Maximum value for the bounding box in z direction
xmin :: Minimum value for the bounding box in x direction
ymin :: Minimum value for the bounding box in y direction
zmin :: Minimum value for the bounding box in z direction
Implements Mantid::Geometry::Rule.
Definition at line 1320 of file RuleItems.cpp.
isValid() [1/2]
bool Mantid::Geometry::BoolValue::isValid (const Kernel::V3D & pt) const override virtual
Determines if a point is valid.
Parameters
pt :: Point to test
Returns
status
Implements Mantid::Geometry::Rule.
Definition at line 1252 of file RuleItems.cpp.
isValid() [2/2]
bool Mantid::Geometry::BoolValue::isValid (const std::map< int, int > & map) const override virtual
isValue :: Based on a surface status map
Determines if a point is valid.
Parameters
map :: map of surface number and true values
Returns
:: status
Implements Mantid::Geometry::Rule.
Definition at line 1263 of file RuleItems.cpp.
leaf()
Rule * Mantid::Geometry::BoolValue::leaf (const int = 0) const inline override virtual
No leaves.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 377 of file Rules.h.
operator=()
BoolValue & Mantid::Geometry::BoolValue::operator= (const BoolValue & A) protected
Assignment operator.
Parameters
A :: BoolValue to copy
Returns
*this
Definition at line 1188 of file RuleItems.cpp.
References Mantid::Geometry::Rule::operator=(), and status.
setLeaf()
void Mantid::Geometry::BoolValue::setLeaf (std::unique_ptr< Rule > aR, const int = 0) override virtual
Replaces a leaf with a rule.
This REQUIRES that aR is of type SurfPoint
Parameters
aR :: new rule
secont argument ignored (Null side point)
Implements Mantid::Geometry::Rule.
Definition at line 1220 of file RuleItems.cpp.
setLeaves()
void Mantid::Geometry::BoolValue::setLeaves (std::unique_ptr< Rule > aR, std::unique_ptr< Rule > oR) override virtual
Replaces a leaf with a rule.
This REQUIRES that aR is of type SurfPoint
Parameters
aR :: new rule
oR :: Null other rule
Implements Mantid::Geometry::Rule.
Definition at line 1235 of file RuleItems.cpp.
setStatus()
void Mantid::Geometry::BoolValue::setStatus (int val) inline
< write val into status, if in valid range
Definition at line 386 of file Rules.h.
simplify()
int Mantid::Geometry::BoolValue::simplify () override virtual
Bool value is always in simplest form.
Returns
0
Implements Mantid::Geometry::Rule.
Definition at line 1274 of file RuleItems.cpp.
type()
int Mantid::Geometry::BoolValue::type () const inline override virtual
Null rule.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 383 of file Rules.h.
Member Data Documentation
status
int Mantid::Geometry::BoolValue::status private
Three values 0 False : 1 True : -1 doesn't matter.
Definition at line 365 of file Rules.h.
Referenced by display(), and operator=().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Objects/Rules.h
Framework/Geometry/src/Objects/RuleItems.cpp