Mantid: Mantid::Kernel::Units::Energy_inWavenumber Class Reference
Mantid::Kernel::Units::Energy_inWavenumber Class Reference
Absolute energy in units of wavenumber (cm^-1)
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
Energy_inWavenumber ()
Constructor.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"Energy_inWavenumber"
Public Member Functions inherited from Mantid::Kernel::Unit
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit. TOF is in microseconds.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight. TOF is in microseconds.
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual ~Unit ()=default
Virtual destructor.
Protected Member Functions
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
Protected Attributes
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Absolute energy in units of wavenumber (cm^-1)
Definition at line 321 of file Unit.h.
Constructor & Destructor Documentation
Energy_inWavenumber()
Mantid::Kernel::Units::Energy_inWavenumber::Energy_inWavenumber ()
Constructor.
Definition at line 496 of file Unit.cpp.
References Mantid::Kernel::Unit::addConversion(), Mantid::PhysicalConstants::h, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::meVtoWavenumber, and Mantid::PhysicalConstants::NeutronMass.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::Energy_inWavenumber::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Implements Mantid::Kernel::Unit.
Definition at line 324 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::Energy_inWavenumber::clone () const override virtual
Returns
a cloned instance of the other
Implements Mantid::Kernel::Unit.
Definition at line 550 of file Unit.cpp.
References Energy_inWavenumber().
conversionTOFMax()
double Mantid::Kernel::Units::Energy_inWavenumber::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Definition at line 541 of file Unit.cpp.
References factorTo.
conversionTOFMin()
double Mantid::Kernel::Units::Energy_inWavenumber::conversionTOFMin () const override virtual
Returns
Minimal time which can be reversibly converted into energy in wavenumner units
Implements Mantid::Kernel::Unit.
Definition at line 540 of file Unit.cpp.
References factorTo.
init()
void Mantid::Kernel::Units::Energy_inWavenumber::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Implements Mantid::Kernel::Unit.
Definition at line 515 of file Unit.cpp.
References factorFrom, factorTo, Mantid::Kernel::Unit::l1, Mantid::Kernel::l2, Mantid::Kernel::Unit::m_params, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::meVtoWavenumber, and Mantid::PhysicalConstants::NeutronMass.
label()
const UnitLabel Mantid::Kernel::Units::Energy_inWavenumber::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Implements Mantid::Kernel::Unit.
Definition at line 493 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::InverseCM.
singleFromTOF()
double Mantid::Kernel::Units::Energy_inWavenumber::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Implements Mantid::Kernel::Unit.
Definition at line 543 of file Unit.cpp.
References factorFrom.
singleToTOF()
double Mantid::Kernel::Units::Energy_inWavenumber::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Implements Mantid::Kernel::Unit.
Definition at line 532 of file Unit.cpp.
References factorTo, and Mantid::Geometry::x.
unitID()
const std::string Mantid::Kernel::Units::Energy_inWavenumber::unitID () const override virtual
"Energy_inWavenumber"
Implements Mantid::Kernel::Unit.
Referenced by validateUnitParams().
validateUnitParams()
void Mantid::Kernel::Units::Energy_inWavenumber::validateUnitParams (const int emode, const UnitParametersMap & params) override protected virtual
Reimplemented from Mantid::Kernel::Unit.
Definition at line 507 of file Unit.cpp.
References Mantid::Kernel::l2, and unitID().
Member Data Documentation
factorFrom
double Mantid::Kernel::Units::Energy_inWavenumber::factorFrom protected
Constant factor for from conversion.
Definition at line 340 of file Unit.h.
Referenced by init(), and singleFromTOF().
factorTo
double Mantid::Kernel::Units::Energy_inWavenumber::factorTo protected
Constant factor for to conversion.
Definition at line 339 of file Unit.h.
Referenced by conversionTOFMax(), conversionTOFMin(), init(), and singleToTOF().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp