Mantid: MantidQt::MantidWidgets::InputController Class Reference
MantidQt::MantidWidgets::InputController Class Reference
The base class for the mouse and keyboard controllers to work with ProjectionSurfaces.
#include <InputController.h>
Signals
void disabled ()
void enabled ()
void touchPointAt (int, int)
Public Member Functions
bool canShowContextMenu () const
Returns true if a surface using this controller can show a context menu on right-click.
virtual void enterEvent (QEvent *)
virtual void freezeRotation (bool)
InputController (QObject *parent, bool contextAllowed=true)
virtual void keyPressEvent (QKeyEvent *)
virtual void leaveEvent (QEvent *)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *)
virtual void mouseReleaseEvent (QMouseEvent *)
virtual void onDisabled ()
To be called when this controller looses control.
virtual void onEnabled ()
To be called when this controller takes control of the input.
virtual void onPaint (QPainter &)
To be called after the owner widget has drawn its content.
virtual void wheelEvent (QWheelEvent *)
~InputController () override=default
Private Attributes
bool m_canShowContextMenu
Detailed Description
The base class for the mouse and keyboard controllers to work with ProjectionSurfaces.
Surfaces can be in different interaction modes and the same mode on different surfaces can involve different inputs.
A projection surface keeps a list of controllers: one per interaction mode. The current controller emits signals which are connected to the relevant slots on the surface.
Definition at line 37 of file InputController.h.
Constructor & Destructor Documentation
InputController()
MantidQt::MantidWidgets::InputController::InputController (QObject * parent, bool contextAllowed = true) explicit
Definition at line 21 of file InputController.cpp.
~InputController()
MantidQt::MantidWidgets::InputController::~InputController () override default
Member Function Documentation
canShowContextMenu()
bool MantidQt::MantidWidgets::InputController::canShowContextMenu () const inline
Returns true if a surface using this controller can show a context menu on right-click.
Definition at line 63 of file InputController.h.
disabled
void MantidQt::MantidWidgets::InputController::disabled () signal
Referenced by MantidQt::MantidWidgets::InputControllerDrawShape::onDisabled().
enabled
void MantidQt::MantidWidgets::InputController::enabled () signal
enterEvent()
virtual void MantidQt::MantidWidgets::InputController::enterEvent (QEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 48 of file InputController.h.
freezeRotation()
virtual void MantidQt::MantidWidgets::InputController::freezeRotation (bool) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputController3DMove.
Definition at line 59 of file InputController.h.
keyPressEvent()
virtual void MantidQt::MantidWidgets::InputController::keyPressEvent (QKeyEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputControllerDrawShape.
Definition at line 47 of file InputController.h.
leaveEvent()
virtual void MantidQt::MantidWidgets::InputController::leaveEvent (QEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputControllerDrawShape, and MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 49 of file InputController.h.
mouseMoveEvent()
virtual void MantidQt::MantidWidgets::InputController::mouseMoveEvent (QMouseEvent * event) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputController3DMove, MantidQt::MantidWidgets::InputControllerPick, MantidQt::MantidWidgets::InputControllerDrawShape, MantidQt::MantidWidgets::InputControllerMoveUnwrapped, and MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 44 of file InputController.h.
Referenced by MantidQt::MantidWidgets::InputController3DMove::mouseMoveEvent(), and MantidQt::MantidWidgets::InputControllerMoveUnwrapped::mouseMoveEvent().
mousePressEvent()
virtual void MantidQt::MantidWidgets::InputController::mousePressEvent (QMouseEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputController3DMove, MantidQt::MantidWidgets::InputControllerPick, MantidQt::MantidWidgets::InputControllerDrawShape, MantidQt::MantidWidgets::InputControllerMoveUnwrapped, and MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 43 of file InputController.h.
mouseReleaseEvent()
virtual void MantidQt::MantidWidgets::InputController::mouseReleaseEvent (QMouseEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputController3DMove, MantidQt::MantidWidgets::InputControllerPick, MantidQt::MantidWidgets::InputControllerDrawShape, MantidQt::MantidWidgets::InputControllerMoveUnwrapped, and MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 45 of file InputController.h.
onDisabled()
virtual void MantidQt::MantidWidgets::InputController::onDisabled () inline virtual
To be called when this controller looses control.
By default emits disabled() signal.
Definition at line 57 of file InputController.h.
onEnabled()
virtual void MantidQt::MantidWidgets::InputController::onEnabled () inline virtual
To be called when this controller takes control of the input.
By default emits enabled() signal.
Definition at line 54 of file InputController.h.
onPaint()
virtual void MantidQt::MantidWidgets::InputController::onPaint (QPainter &) inline virtual
To be called after the owner widget has drawn its content.
Reimplemented in MantidQt::MantidWidgets::InputControllerSelection.
Definition at line 51 of file InputController.h.
touchPointAt
void MantidQt::MantidWidgets::InputController::touchPointAt (int , int) signal
wheelEvent()
virtual void MantidQt::MantidWidgets::InputController::wheelEvent (QWheelEvent *) inline virtual
Reimplemented in MantidQt::MantidWidgets::InputController3DMove, and MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 46 of file InputController.h.
Member Data Documentation
m_canShowContextMenu
bool MantidQt::MantidWidgets::InputController::m_canShowContextMenu private
Definition at line 71 of file InputController.h.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InputController.h
qt/widgets/common/src/InputController.cpp