Mantid: Mantid::Geometry::IObject Class Reference
Mantid::Geometry::IObject Class Reference abstract
IObject : Interface for geometry objects.
#include <IObject.h>
Public Member Functions
virtual IObject * clone () const =0
virtual IObject * cloneWithMaterial (const Kernel::Material &material) const =0
virtual double distance (const Geometry::Track &) const =0
virtual void draw () const =0
virtual boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const BoundingBox &activeRegion, const size_t) const =0
virtual boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const size_t) const =0
virtual const BoundingBox & getBoundingBox () const =0
Return cached value of axis-aligned bounding box.
virtual void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) const =0
Calculate (or return cached value of) Axis Aligned Bounding box (DEPRECATED)
virtual std::shared_ptr< GeometryHandler > getGeometryHandler () const =0
virtual int getName () const =0
virtual void GetObjectGeom (detail::ShapeInfo::GeometryShape &type, std::vector< Kernel::V3D > &vectors, double &innerRadius, double &radius, double &height) const =0
virtual int getPointInObject (Kernel::V3D &point) const =0
virtual bool hasValidShape () const =0
virtual const std::string & id () const =0
virtual void initDraw () const =0
virtual int interceptSurface (Geometry::Track &) const =0
virtual bool isFiniteGeometry () const
virtual bool isOnSide (const Kernel::V3D &) const =0
virtual bool isValid (const Kernel::V3D &) const =0
virtual const Kernel::Material & material () const =0
virtual void setFiniteGeometryFlag (bool)
virtual void setID (const std::string &id)=0
virtual void setMaterial (const Kernel::Material &material)=0
virtual detail::ShapeInfo::GeometryShape shape () const =0
virtual const detail::ShapeInfo & shapeInfo () const =0
virtual double solidAngle (const Kernel::V3D &observer) const =0
virtual double solidAngle (const Kernel::V3D &observer, const Kernel::V3D &scaleFactor) const =0
virtual double volume () const =0
virtual ~IObject ()=default
Detailed Description
IObject : Interface for geometry objects.
Interface for Geometry Objects
Definition at line 41 of file IObject.h.
Constructor & Destructor Documentation
~IObject()
virtual Mantid::Geometry::IObject::~IObject () virtual default
Member Function Documentation
clone()
virtual IObject * Mantid::Geometry::IObject::clone () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::cacheLS1(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::initialiseCachedDistances(), and Mantid::Algorithms::AnyShapeAbsorption::initialiseCachedDistances().
cloneWithMaterial()
virtual IObject * Mantid::Geometry::IObject::cloneWithMaterial (const Kernel::Material & material) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Geometry::Container::cloneWithMaterial(), and Mantid::Algorithms::CopySample::copyParameters().
distance()
virtual double Mantid::Geometry::IObject::distance (const Geometry::Track &) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::MeshObject2D, Mantid::Geometry::CSGObject, and Mantid::Geometry::MeshObject.
draw()
virtual void Mantid::Geometry::IObject::draw () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
generatePointInObject() [1/2]
virtual boost::optional< Kernel::V3D > Mantid::Geometry::IObject::generatePointInObject (Kernel::PseudoRandomNumberGenerator & rng, const BoundingBox & activeRegion, const size_t) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
generatePointInObject() [2/2]
virtual boost::optional< Kernel::V3D > Mantid::Geometry::IObject::generatePointInObject (Kernel::PseudoRandomNumberGenerator & rng, const size_t) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::MCInteractionVolume::generatePointInObjectByIndex().
getBoundingBox() [1/2]
virtual const BoundingBox & Mantid::Geometry::IObject::getBoundingBox () const pure virtual
Return cached value of axis-aligned bounding box.
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::cacheInputs(), and Mantid::Algorithms::BeamProfileFactory::createBeamProfile().
getBoundingBox() [2/2]
virtual void Mantid::Geometry::IObject::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) const pure virtual
Calculate (or return cached value of) Axis Aligned Bounding box (DEPRECATED)
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
getGeometryHandler()
virtual std::shared_ptr< GeometryHandler > Mantid::Geometry::IObject::getGeometryHandler () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
getName()
virtual int Mantid::Geometry::IObject::getName () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
GetObjectGeom()
virtual void Mantid::Geometry::IObject::GetObjectGeom (detail::ShapeInfo::GeometryShape & type, std::vector< Kernel::V3D > & vectors, double & innerRadius, double & radius, double & height) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
getPointInObject()
virtual int Mantid::Geometry::IObject::getPointInObject (Kernel::V3D & point) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
hasValidShape()
virtual bool Mantid::Geometry::IObject::hasValidShape () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructSample(), Mantid::Algorithms::BeamProfileFactory::createBeamProfile(), Mantid::Algorithms::CylinderAbsorption::getShapeFromSample(), Mantid::Geometry::ComponentInfo::hasValidShape(), and Mantid::Algorithms::MCInteractionVolume::MCInteractionVolume().
id()
virtual const std::string & Mantid::Geometry::IObject::id () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
initDraw()
virtual void Mantid::Geometry::IObject::initDraw () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
interceptSurface()
virtual int Mantid::Geometry::IObject::interceptSurface (Geometry::Track &) const pure virtual
Implemented in Mantid::Geometry::MeshObject, Mantid::Geometry::Container, Mantid::Geometry::CSGObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::Algorithms::XrayAbsorptionCorrection::calculateMuonPos(), Mantid::Algorithms::DetectorEfficiencyCor::distToSurface(), Mantid::Algorithms::He3TubeEfficiency::distToSurface(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), Mantid::Algorithms::XrayAbsorptionCorrection::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateDetectorPos(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateScatter(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::initialiseCachedDistances(), and Mantid::Algorithms::FlatPlateAbsorption::initialiseCachedDistances().
isFiniteGeometry()
virtual bool Mantid::Geometry::IObject::isFiniteGeometry () const inline virtual
Reimplemented in Mantid::Geometry::CSGObject.
Definition at line 46 of file IObject.h.
isOnSide()
virtual bool Mantid::Geometry::IObject::isOnSide (const Kernel::V3D &) const pure virtual
Implemented in Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, Mantid::Geometry::MeshObject2D, and Mantid::Geometry::Container.
isValid()
virtual bool Mantid::Geometry::IObject::isValid (const Kernel::V3D &) const pure virtual
Implemented in Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, Mantid::Geometry::Container, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::FlatPlateAbsorption::initialiseCachedDistances().
material()
virtual const Kernel::Material & Mantid::Geometry::IObject::material () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Algorithms::MultipleScatteringCorrection::calculateSingleComponent(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors().
setFiniteGeometryFlag()
virtual void Mantid::Geometry::IObject::setFiniteGeometryFlag (bool) inline virtual
Reimplemented in Mantid::Geometry::CSGObject.
Definition at line 47 of file IObject.h.
setID()
virtual void Mantid::Geometry::IObject::setID (const std::string & id) pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
setMaterial()
virtual void Mantid::Geometry::IObject::setMaterial (const Kernel::Material & material) pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
shape()
virtual detail::ShapeInfo::GeometryShape Mantid::Geometry::IObject::shape () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Geometry::Rasterize::calculate(), Mantid::Geometry::Rasterize::calculateCylinder(), Mantid::Geometry::Rasterize::calculateHollowCylinder(), Mantid::Algorithms::CylinderAbsorption::getShapeFromSample(), and Mantid::Algorithms::CylinderAbsorption::initialiseCachedDistances().
shapeInfo()
virtual const detail::ShapeInfo & Mantid::Geometry::IObject::shapeInfo () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Geometry::Rasterize::calculate(), Mantid::Geometry::Rasterize::calculateCylinder(), and Mantid::Geometry::Rasterize::calculateHollowCylinder().
solidAngle() [1/2]
virtual double Mantid::Geometry::IObject::solidAngle (const Kernel::V3D & observer) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
Referenced by Mantid::Geometry::ComponentInfo::solidAngle().
solidAngle() [2/2]
virtual double Mantid::Geometry::IObject::solidAngle (const Kernel::V3D & observer, const Kernel::V3D & scaleFactor) const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
volume()
virtual double Mantid::Geometry::IObject::volume () const pure virtual
Implemented in Mantid::Geometry::Container, Mantid::Geometry::CSGObject, Mantid::Geometry::MeshObject, and Mantid::Geometry::MeshObject2D.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Objects/IObject.h