Mantid: Mantid::Kernel::LiveListenerInfo Class Reference
Mantid::Kernel::LiveListenerInfo Class Reference
A class that holds information about a LiveListener connection.
#include <LiveListenerInfo.h>
Public Member Functions
const std::string & address () const
Returns the address string of this LiveListener connection.
const std::string & listener () const
Returns the classname of the specific LiveListener to use.
LiveListenerInfo (InstrumentInfo const *inst, const Poco::XML::Element *elem)
Construct from Facility Info XML.
LiveListenerInfo (std::string listener="", std::string address="", std::string name="")
Construct manually.
const std::string & name () const
Return the name of this LiveListener connection.
bool operator== (const LiveListenerInfo &rhs) const
Required for Python bindings.
Private Attributes
std::string m_address
Listener address.
std::string m_listener
Listener classname.
std::string m_name
Listener name.
Detailed Description
A class that holds information about a LiveListener connection.
Definition at line 37 of file LiveListenerInfo.h.
Constructor & Destructor Documentation
LiveListenerInfo() [1/2]
Mantid::Kernel::LiveListenerInfo::LiveListenerInfo (InstrumentInfo const * inst, const Poco::XML::Element * elem)
Construct from Facility Info XML.
Parameters
inst Pointer to InstrumentInfo that this LiveListenerInfo belongs to
elem The Poco::XML::Element to read the data from
Definition at line 32 of file LiveListenerInfo.cpp.
References Mantid::Kernel::Logger::error(), Mantid::Kernel::DateAndTimeHelpers::g_log, m_address, m_listener, m_name, and Mantid::Kernel::InstrumentInfo::name().
LiveListenerInfo() [2/2]
Mantid::Kernel::LiveListenerInfo::LiveListenerInfo (std::string listener = "", std::string address = "", std::string name = "")
Construct manually.
Parameters
listener Class name of specific listener to use
address Address which listener should use to connect
name Name designator for this listener connection info
Definition at line 52 of file LiveListenerInfo.cpp.
Member Function Documentation
address()
const std::string & Mantid::Kernel::LiveListenerInfo::address () const
Returns the address string of this LiveListener connection.
Definition at line 61 of file LiveListenerInfo.cpp.
References m_address.
Referenced by Mantid::API::LiveListenerFactoryImpl::create(), export_LiveListenerInfo(), Mantid::Kernel::InstrumentInfo::liveDataAddress(), Mantid::Kernel::operator<<(), and operator==().
listener()
const std::string & Mantid::Kernel::LiveListenerInfo::listener () const
Returns the classname of the specific LiveListener to use.
Definition at line 63 of file LiveListenerInfo.cpp.
References m_listener.
Referenced by Mantid::API::LiveListenerFactoryImpl::create(), export_LiveListenerInfo(), Mantid::Kernel::InstrumentInfo::liveListener(), and Mantid::Kernel::operator<<().
name()
const std::string & Mantid::Kernel::LiveListenerInfo::name () const
Return the name of this LiveListener connection.
Definition at line 59 of file LiveListenerInfo.cpp.
References m_name.
Referenced by export_LiveListenerInfo(), and Mantid::Kernel::operator<<().
operator==()
bool Mantid::Kernel::LiveListenerInfo::operator== (const LiveListenerInfo & rhs) const
Required for Python bindings.
Definition at line 55 of file LiveListenerInfo.cpp.
References address(), and rhs.
Member Data Documentation
m_address
std::string Mantid::Kernel::LiveListenerInfo::m_address private
Listener address.
Definition at line 56 of file LiveListenerInfo.h.
Referenced by address(), and LiveListenerInfo().
m_listener
std::string Mantid::Kernel::LiveListenerInfo::m_listener private
Listener classname.
Definition at line 57 of file LiveListenerInfo.h.
Referenced by listener(), and LiveListenerInfo().
m_name
std::string Mantid::Kernel::LiveListenerInfo::m_name private
Listener name.
Definition at line 55 of file LiveListenerInfo.h.
Referenced by LiveListenerInfo(), and name().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/LiveListenerInfo.h
Framework/Kernel/src/LiveListenerInfo.cpp