Mantid: Mantid::Algorithms::IBeamProfile Class Reference
Mantid::Algorithms::IBeamProfile Class Reference abstract
Base class for all classes defining a beam profile.
#include <IBeamProfile.h>
Classes
struct Ray
Public Member Functions
virtual Geometry::BoundingBox defineActiveRegion (const Geometry::BoundingBox &) const =0
virtual Ray generatePoint (Kernel::PseudoRandomNumberGenerator &rng) const =0
virtual Ray generatePoint (Kernel::PseudoRandomNumberGenerator &rng, const Geometry::BoundingBox &) const =0
Geometry::IObject_sptr getIntersectionWithSample (const Geometry::IObject &sample) const
Get the intersection of the beam with the sample.
IBeamProfile ()=default
IBeamProfile (const Kernel::V3D center)
Construct a new IBeamProfile::IBeamProfile object.
virtual ~IBeamProfile ()=default
Protected Attributes
Kernel::V3D m_beamCenter
Detailed Description
Base class for all classes defining a beam profile.
Definition at line 27 of file IBeamProfile.h.
Constructor & Destructor Documentation
IBeamProfile() [1/2]
Mantid::Algorithms::IBeamProfile::IBeamProfile (const Kernel::V3D center)
Construct a new IBeamProfile::IBeamProfile object.
Parameters
center Center of the beam
Definition at line 69 of file IBeamProfile.cpp.
IBeamProfile() [2/2]
Mantid::Algorithms::IBeamProfile::IBeamProfile () default
~IBeamProfile()
virtual Mantid::Algorithms::IBeamProfile::~IBeamProfile () virtual default
Member Function Documentation
defineActiveRegion()
virtual Geometry::BoundingBox Mantid::Algorithms::IBeamProfile::defineActiveRegion (const Geometry::BoundingBox &) const pure virtual
Implemented in Mantid::Algorithms::RectangularBeamProfile, and Mantid::Algorithms::CircularBeamProfile.
Referenced by getIntersectionWithSample(), and Mantid::Algorithms::MCAbsorptionStrategy::setActiveRegion().
generatePoint() [1/2]
virtual Ray Mantid::Algorithms::IBeamProfile::generatePoint (Kernel::PseudoRandomNumberGenerator & rng) const pure virtual
Implemented in Mantid::Algorithms::CircularBeamProfile, and Mantid::Algorithms::RectangularBeamProfile.
Referenced by Mantid::Algorithms::MCAbsorptionStrategy::calculate().
generatePoint() [2/2]
virtual Ray Mantid::Algorithms::IBeamProfile::generatePoint (Kernel::PseudoRandomNumberGenerator & rng, const Geometry::BoundingBox &) const pure virtual
Implemented in Mantid::Algorithms::CircularBeamProfile, and Mantid::Algorithms::RectangularBeamProfile.
getIntersectionWithSample()
Geometry::IObject_sptr Mantid::Algorithms::IBeamProfile::getIntersectionWithSample (const Geometry::IObject & sample) const
Get the intersection of the beam with the sample.
Parameters
sample Sample object to be intersected with
Returns
Geometry::IObject_sptr
Definition at line 77 of file IBeamProfile.cpp.
References Mantid::Geometry::BoundingBox::centrePoint(), Mantid::Geometry::IObject::clone(), Mantid::Geometry::ShapeFactory::createShape(), defineActiveRegion(), Mantid::Geometry::IObject::getBoundingBox(), Mantid::Geometry::BoundingBox::maxPoint(), Mantid::Geometry::BoundingBox::minPoint(), Mantid::Geometry::BoundingBox::xMax(), Mantid::Geometry::BoundingBox::xMin(), Mantid::Geometry::BoundingBox::yMax(), Mantid::Geometry::BoundingBox::yMin(), Mantid::Geometry::BoundingBox::zMax(), and Mantid::Geometry::BoundingBox::zMin().
Member Data Documentation
m_beamCenter
Kernel::V3D Mantid::Algorithms::IBeamProfile::m_beamCenter protected
Definition at line 43 of file IBeamProfile.h.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IBeamProfile.h
Framework/Algorithms/src/SampleCorrections/IBeamProfile.cpp