Mantid: Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy > Struct Template Reference
Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy > Struct Template Reference
A struct to help export std::vector types.
#include <StlExportDefinitions.h>
Public Types
using w_t = std::vector< ElementType >
A typedef of a vector of template ElementTypes.
Static Public Member Functions
static std::string to_string (const w_t &values)
static void wrap (std::string const &python_name)
a python wrapper
Detailed Description
template<typename ElementType, bool NoIndexingProxy = false>
struct Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >
A struct to help export std::vector types.
Definition at line 69 of file StlExportDefinitions.h.
Member Typedef Documentation
w_t
template<typename ElementType , bool NoIndexingProxy = false> using Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >::w_t = std::vector<ElementType>
A typedef of a vector of template ElementTypes.
Definition at line 71 of file StlExportDefinitions.h.
Member Function Documentation
to_string()
template<typename ElementType , bool NoIndexingProxy = false> static std::string Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >::to_string (const w_t & values) inline static
Definition at line 73 of file StlExportDefinitions.h.
Referenced by Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >::wrap().
wrap()
template<typename ElementType , bool NoIndexingProxy = false> static void Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >::wrap (std::string const & python_name) inline static
a python wrapper
Definition at line 83 of file StlExportDefinitions.h.
References Mantid::PythonInterface::std_vector_exporter< ElementType, NoIndexingProxy >::to_string().
Referenced by export_Property(), export_SymmetryOperation(), and exportStlContainers().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/StlExportDefinitions.h