Mantid: Mantid::DataHandling::XmlHandler Class Reference
Mantid::DataHandling::XmlHandler Class Reference
#include <XmlHandler.h>
Public Member Functions
std::map< std::string, std::string > get_attributes_from_tag (const std::string &)
std::map< std::string, std::string > get_metadata (const std::vector< std::string > &tags_to_ignore)
Build dictionary {string : string } of all tags in the dictionary Composed tags: / replaced by _.
std::vector< std::string > get_subnodes (const std::string &)
Returns list of sub-nodes for a xpath node For: xpath = //Data/ Returns: Detector , DetectorWing.
std::string get_text_from_tag (const std::string &)
XmlHandler ()=default
XmlHandler (const std::string &)
Private Attributes
Poco::AutoPtr< Poco::XML::Document > pDoc
Detailed Description
Definition at line 21 of file XmlHandler.h.
Constructor & Destructor Documentation
XmlHandler() [1/2]
Mantid::DataHandling::XmlHandler::XmlHandler () default
XmlHandler() [2/2]
Mantid::DataHandling::XmlHandler::XmlHandler (const std::string & filename)
Definition at line 25 of file XmlHandler.cpp.
References pDoc.
Member Function Documentation
get_attributes_from_tag()
std::map< std::string, std::string > Mantid::DataHandling::XmlHandler::get_attributes_from_tag (const std::string & xpath)
Definition at line 67 of file XmlHandler.cpp.
References pDoc.
Referenced by Mantid::DataHandling::LoadSpice2D::getData(), Mantid::DataHandling::LoadHFIRSANS::readData(), Mantid::DataHandling::LoadHFIRSANS::setTimes(), and Mantid::DataHandling::LoadSpice2D::setTimes().
get_metadata()
std::map< std::string, std::string > Mantid::DataHandling::XmlHandler::get_metadata (const std::vector< std::string > & tags_to_ignore)
Build dictionary {string : string } of all tags in the dictionary Composed tags: / replaced by _.
Definition at line 37 of file XmlHandler.cpp.
References pDoc, and value.
Referenced by Mantid::DataHandling::LoadSpice2D::exec(), and Mantid::DataHandling::LoadHFIRSANS::setInputFileAsHandler().
get_subnodes()
std::vector< std::string > Mantid::DataHandling::XmlHandler::get_subnodes (const std::string & xpath)
Returns list of sub-nodes for a xpath node For: xpath = //Data/ Returns: Detector , DetectorWing.
Definition at line 87 of file XmlHandler.cpp.
References pDoc.
Referenced by Mantid::DataHandling::LoadSpice2D::getData(), and Mantid::DataHandling::LoadHFIRSANS::readData().
get_text_from_tag()
std::string Mantid::DataHandling::XmlHandler::get_text_from_tag (const std::string & xpath)
Definition at line 57 of file XmlHandler.cpp.
References pDoc, and value.
Referenced by Mantid::DataHandling::LoadSpice2D::getData(), and Mantid::DataHandling::LoadHFIRSANS::readData().
Member Data Documentation
pDoc
Poco::AutoPtr<Poco::XML::Document> Mantid::DataHandling::XmlHandler::pDoc private
Definition at line 32 of file XmlHandler.h.
Referenced by get_attributes_from_tag(), get_metadata(), get_subnodes(), get_text_from_tag(), and XmlHandler().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/XmlHandler.h
Framework/DataHandling/src/XmlHandler.cpp