Mantid: Mantid::API::IEventList Class Reference
Mantid::API::IEventList Class Reference abstract
IEventList : Interface to Mantid::DataObjects::EventList class, used to expose to PythonAPI.
#include <IEventList.h>
Public Member Functions
virtual void addPulsetime (const double seconds)=0
Add a value to the pulse time values.
virtual void addPulsetimes (const std::vector< double > &seconds)=0
Add a separate value to each of the pulse time values.
virtual void addTof (const double offset)=0
Add a value to the TOF values.
virtual void clear (const bool removeDetIDs)=0
Clear the event list.
virtual void convertTof (const double factor, const double offset=0.)=0
Convert the TOF values.
virtual void convertTof (std::function< double(double)> func, const int sorting=0)=0
Convert the TOF values.
virtual void divide (const double value, const double error=0.0)=0
Divide event list by a constant with error.
virtual void divide (const MantidVec &X, const MantidVec &Y, const MantidVec &E)=0
Divide event list by a histogram.
virtual void generateHistogram (const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const =0
Get copy of counts and errors, rebinned using on the given X values.
virtual void generateHistogramPulseTime (const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const =0
Get copy of counts and errors rebinned using the given X values w.r.t pulse time.
virtual void generateHistogramTimeAtSample (const MantidVec &X, MantidVec &Y, MantidVec &E, const double &tofFactor, const double &tofOffset, bool skipError=false) const =0
Get copy of counts and errors rebinning using the given X values w.r.t absolute time at the sample.
virtual Mantid::API::EventType getEventType () const =0
Return the current event type for the list.
size_t getMemorySize () const override=0
Get memory size of event list.
virtual std::size_t getNumberEvents () const =0
Get the number of events from the list.
virtual Mantid::Types::Core::DateAndTime getPulseTimeMax () const =0
Get the maximum pulse time from the list.
virtual Mantid::Types::Core::DateAndTime getPulseTimeMin () const =0
Get the minimum pulse time from the list.
virtual std::vector< Mantid::Types::Core::DateAndTime > getPulseTimes () const =0
Return the list of pulse time values.
virtual Mantid::Types::Core::DateAndTime getTimeAtSampleMax (const double &tofFactor, const double &tofOffset) const =0
Get the maximum time at sample.
virtual Mantid::Types::Core::DateAndTime getTimeAtSampleMin (const double &tofFactor, const double &tofOffset) const =0
Get the minimum time at sample.
virtual double getTofMax () const =0
Get the maximum TOF from the list.
virtual double getTofMin () const =0
Get the minimum TOF from the list.
virtual std::vector< double > getTofs () const =0
Return the list of TOF values.
virtual void getTofs (std::vector< double > &tofs) const =0
Return the list of TOF values.
virtual std::vector< double > getWeightErrors () const =0
Return the list of event weight error values.
virtual void getWeightErrors (std::vector< double > &weightErrors) const =0
Return the list of event weight error values.
virtual std::vector< double > getWeights () const =0
Return the list of event weight values.
virtual void getWeights (std::vector< double > &weights) const =0
Return the list of event weight values.
IEventList ()
Empty constructor.
IEventList (specnum_t specNo)
Constructor.
virtual double integrate (const double minX, const double maxX, const bool entireRange) const =0
Integrate the event list.
virtual bool isSortedByTof () const =0
IS the list sorted by TOF?
virtual void maskCondition (const std::vector< bool > &mask)=0
Mask the events by the condition vector.
virtual void maskTof (const double tofMin, const double tofMax)=0
Mask a given TOF range.
virtual void multiply (const double value, const double error=0.0)=0
Multiply event list by a constant with error.
virtual void multiply (const MantidVec &X, const MantidVec &Y, const MantidVec &E)=0
Multiply event list by a histogram.
virtual void reserve (size_t num)=0
Reserve a fixed size for the list.
virtual void scaleTof (const double factor)=0
Scale the TOF values by a constant.
virtual void setTofs (const MantidVec &tofs)=0
Set the TOFs from the given list.
virtual void switchTo (Mantid::API::EventType newType)=0
Switch to a new event type within the list.
Public Member Functions inherited from Mantid::API::ISpectrum
void addDetectorID (const detid_t detID)
Add a detector ID to the set of detector IDs.
void addDetectorIDs (const std::set< detid_t > &detIDs)
Add a set of detector IDs to the set of detector IDs.
void addDetectorIDs (const std::vector< detid_t > &detIDs)
Add a vector of detector IDs to the set of detector IDs.
HistogramData::BinEdges binEdges () const
virtual void clearData ()=0
void clearDetectorIDs ()
Clear the detector IDs set.
void convertToCounts ()
void convertToFrequencies ()
virtual void copyDataFrom (const ISpectrum &source)=0
Copy data from another ISpectrum with double-dynamic dispatch.
virtual void copyDataInto (DataObjects::EventList &) const
Override in child classes for polymorphic copying of data.
virtual void copyDataInto (DataObjects::Histogram1D &) const
Override in child classes for polymorphic copying of data.
virtual void copyDataInto (SpectrumTester &) const
Override in child classes for polymorphic copying of data.
void copyInfoFrom (const ISpectrum &other)
Copy spectrum number and detector IDs, but not X vector, from another ISpectrum.
virtual HistogramData::Counts counts () const
virtual HistogramData::CountStandardDeviations countStandardDeviations () const
virtual HistogramData::CountVariances countVariances () const
virtual const MantidVec & dataDx () const =0
virtual MantidVec & dataDx ()=0
virtual const MantidVec & dataE () const =0
virtual MantidVec & dataE ()=0
virtual const MantidVec & dataX () const =0
virtual MantidVec & dataX ()=0
virtual const MantidVec & dataY () const =0
virtual MantidVec & dataY ()=0
const HistogramData::HistogramDx & dx () const
virtual const HistogramData::HistogramE & e () const
virtual HistogramData::Frequencies frequencies () const
virtual HistogramData::FrequencyStandardDeviations frequencyStandardDeviations () const
virtual HistogramData::FrequencyVariances frequencyVariances () const
const std::set< detid_t > & getDetectorIDs () const
Get a const reference to the detector IDs set.
virtual size_t getMemorySize () const =0
specnum_t getSpectrumNo () const
virtual std::pair< double, double > getXDataRange () const
Return the min/max X values for this spectrum.
bool hasDetectorID (const detid_t detID) const
Return true if the given detector ID is in the list for this ISpectrum.
bool hasDx () const
Gets the value of the use flag.
virtual HistogramData::Histogram histogram () const
Returns the Histogram associated with this spectrum.
ISpectrum ()=default
ISpectrum (const specnum_t specNo)
Constructor with spectrum number.
HistogramData::HistogramDx & mutableDx () &
HistogramData::HistogramE & mutableE () &
HistogramData::HistogramX & mutableX () &
HistogramData::HistogramY & mutableY () &
HistogramData::Points points () const
HistogramData::PointStandardDeviations pointStandardDeviations () const
virtual Kernel::cow_ptr< HistogramData::HistogramX > ptrX () const =0
virtual const MantidVec & readDx () const =0
virtual const MantidVec & readE () const
Deprecated, use e() instead. Returns the y error data const.
virtual const MantidVec & readX () const =0
virtual const MantidVec & readY () const
Deprecated, use y() instead. Returns the y data const.
void resetHasDx ()
Resets the hasDx flag.
template<typename... T>
void setBinEdges (T &&...data) &
template<typename... T>
void setCounts (T &&...data) &
template<typename... T>
void setCountStandardDeviations (T &&...data) &
template<typename... T>
void setCountVariances (T &&...data) &
void setDetectorID (const detid_t detID)
Clear the list of detector IDs, then add one.
void setDetectorIDs (const std::set< detid_t > &detIDs)
Set the detector IDs to be the set given.
void setDetectorIDs (std::set< detid_t > &&detIDs)
Set the detector IDs to be the set given (move version).
template<typename... T>
void setFrequencies (T &&...data) &
template<typename... T>
void setFrequencyStandardDeviations (T &&...data) &
template<typename... T>
void setFrequencyVariances (T &&...data) &
template<typename... T>
void setHistogram (T &&...data)
Sets the Histogram associated with this spectrum.
void setMatrixWorkspace (MatrixWorkspace *matrixWorkspace, const size_t index)
Sets the MatrixWorkspace pointer (pointer to the owning workspace).
template<typename... T>
void setPoints (T &&...data) &
template<typename... T>
void setPointStandardDeviations (T &&...data) &
template<typename... T>
void setPointVariances (T &&...data) &
void setSharedDx (const Kernel::cow_ptr< HistogramData::HistogramDx > &dx) &
void setSharedE (const Kernel::cow_ptr< HistogramData::HistogramE > &e) &
void setSharedX (const Kernel::cow_ptr< HistogramData::HistogramX > &x) &
void setSharedY (const Kernel::cow_ptr< HistogramData::HistogramY > &y) &
void setSpectrumNo (specnum_t num)
Sets the the spectrum number of this spectrum.
virtual void setX (const Kernel::cow_ptr< HistogramData::HistogramX > &X)=0
void setYMode (HistogramData::Histogram::YMode ymode)
Kernel::cow_ptr< HistogramData::HistogramDx > sharedDx () const
virtual Kernel::cow_ptr< HistogramData::HistogramE > sharedE () const
Kernel::cow_ptr< HistogramData::HistogramX > sharedX () const
virtual Kernel::cow_ptr< HistogramData::HistogramY > sharedY () const
const HistogramData::HistogramX & x () const
virtual const HistogramData::HistogramY & y () const
HistogramData::Histogram::YMode yMode () const
virtual ~ISpectrum ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::ISpectrum
virtual void checkAndSanitizeHistogram (HistogramData::Histogram &)
virtual void checkIsYAndEWritable () const
virtual void checkWorksWithPoints () const
ISpectrum (const ISpectrum &other)
Copy constructor.
ISpectrum (ISpectrum &&other)
Move constructor.
ISpectrum & operator= (const ISpectrum &other)
Copy assignment.
ISpectrum & operator= (ISpectrum &&other)
Move assignment.
Detailed Description
IEventList : Interface to Mantid::DataObjects::EventList class, used to expose to PythonAPI.
Author
Janik Zikovsky
Date
2011-04-12 11:48:38.252379
Definition at line 26 of file IEventList.h.
Constructor & Destructor Documentation
IEventList() [1/2]
Mantid::API::IEventList::IEventList () inline
Empty constructor.
Definition at line 29 of file IEventList.h.
IEventList() [2/2]
Mantid::API::IEventList::IEventList (specnum_t specNo) inline
Constructor.
Definition at line 32 of file IEventList.h.
Member Function Documentation
addPulsetime()
virtual void Mantid::API::IEventList::addPulsetime (const double seconds) pure virtual
Add a value to the pulse time values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
addPulsetimes()
virtual void Mantid::API::IEventList::addPulsetimes (const std::vector< double > & seconds) pure virtual
Add a separate value to each of the pulse time values.
Implemented in Mantid::DataObjects::EventList.
addTof()
virtual void Mantid::API::IEventList::addTof (const double offset) pure virtual
Add a value to the TOF values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
clear()
virtual void Mantid::API::IEventList::clear (const bool removeDetIDs) pure virtual
Clear the event list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
convertTof() [1/2]
virtual void Mantid::API::IEventList::convertTof (const double factor, const double offset = 0.) pure virtual
Convert the TOF values.
Implemented in Mantid::DataObjects::EventList.
convertTof() [2/2]
virtual void Mantid::API::IEventList::convertTof (std::function< double(double)> func, const int sorting = 0) pure virtual
Convert the TOF values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
divide() [1/2]
virtual void Mantid::API::IEventList::divide (const double value, const double error = 0.0) pure virtual
Divide event list by a constant with error.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
divide() [2/2]
virtual void Mantid::API::IEventList::divide (const MantidVec & X, const MantidVec & Y, const MantidVec & E) pure virtual
Divide event list by a histogram.
Implemented in Mantid::DataObjects::EventList.
generateHistogram()
virtual void Mantid::API::IEventList::generateHistogram (const MantidVec & X, MantidVec & Y, MantidVec & E, bool skipError = false) const pure virtual
Get copy of counts and errors, rebinned using on the given X values.
Implemented in Mantid::DataObjects::EventList.
generateHistogramPulseTime()
virtual void Mantid::API::IEventList::generateHistogramPulseTime (const MantidVec & X, MantidVec & Y, MantidVec & E, bool skipError = false) const pure virtual
Get copy of counts and errors rebinned using the given X values w.r.t pulse time.
Implemented in Mantid::DataObjects::EventList.
generateHistogramTimeAtSample()
virtual void Mantid::API::IEventList::generateHistogramTimeAtSample (const MantidVec & X, MantidVec & Y, MantidVec & E, const double & tofFactor, const double & tofOffset, bool skipError = false) const pure virtual
Get copy of counts and errors rebinning using the given X values w.r.t absolute time at the sample.
Implemented in Mantid::DataObjects::EventList.
getEventType()
virtual Mantid::API::EventType Mantid::API::IEventList::getEventType () const pure virtual
Return the current event type for the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getMemorySize()
size_t Mantid::API::IEventList::getMemorySize () const override pure virtual
Get memory size of event list.
Implements Mantid::API::ISpectrum.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getNumberEvents()
virtual std::size_t Mantid::API::IEventList::getNumberEvents () const pure virtual
Get the number of events from the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getPulseTimeMax()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventList::getPulseTimeMax () const pure virtual
Get the maximum pulse time from the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getPulseTimeMin()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventList::getPulseTimeMin () const pure virtual
Get the minimum pulse time from the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getPulseTimes()
virtual std::vector< Mantid::Types::Core::DateAndTime > Mantid::API::IEventList::getPulseTimes () const pure virtual
Return the list of pulse time values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList(), and Mantid::Algorithms::SumEventsByLogValue::filterEventList().
getTimeAtSampleMax()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventList::getTimeAtSampleMax (const double & tofFactor, const double & tofOffset) const pure virtual
Get the maximum time at sample.
Implemented in Mantid::DataObjects::EventList.
getTimeAtSampleMin()
virtual Mantid::Types::Core::DateAndTime Mantid::API::IEventList::getTimeAtSampleMin (const double & tofFactor, const double & tofOffset) const pure virtual
Get the minimum time at sample.
Implemented in Mantid::DataObjects::EventList.
getTofMax()
virtual double Mantid::API::IEventList::getTofMax () const pure virtual
Get the maximum TOF from the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getTofMin()
virtual double Mantid::API::IEventList::getTofMin () const pure virtual
Get the minimum TOF from the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getTofs() [1/2]
virtual std::vector< double > Mantid::API::IEventList::getTofs () const pure virtual
Return the list of TOF values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getTofs() [2/2]
virtual void Mantid::API::IEventList::getTofs (std::vector< double > & tofs) const pure virtual
Return the list of TOF values.
Implemented in Mantid::DataObjects::EventList.
getWeightErrors() [1/2]
virtual std::vector< double > Mantid::API::IEventList::getWeightErrors () const pure virtual
Return the list of event weight error values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getWeightErrors() [2/2]
virtual void Mantid::API::IEventList::getWeightErrors (std::vector< double > & weightErrors) const pure virtual
Return the list of event weight error values.
Implemented in Mantid::DataObjects::EventList.
getWeights() [1/2]
virtual std::vector< double > Mantid::API::IEventList::getWeights () const pure virtual
Return the list of event weight values.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
getWeights() [2/2]
virtual void Mantid::API::IEventList::getWeights (std::vector< double > & weights) const pure virtual
Return the list of event weight values.
Implemented in Mantid::DataObjects::EventList.
integrate()
virtual double Mantid::API::IEventList::integrate (const double minX, const double maxX, const bool entireRange) const pure virtual
Integrate the event list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
isSortedByTof()
virtual bool Mantid::API::IEventList::isSortedByTof () const pure virtual
IS the list sorted by TOF?
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
maskCondition()
virtual void Mantid::API::IEventList::maskCondition (const std::vector< bool > & mask) pure virtual
Mask the events by the condition vector.
Implemented in Mantid::DataObjects::EventList.
maskTof()
virtual void Mantid::API::IEventList::maskTof (const double tofMin, const double tofMax) pure virtual
Mask a given TOF range.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
multiply() [1/2]
virtual void Mantid::API::IEventList::multiply (const double value, const double error = 0.0) pure virtual
Multiply event list by a constant with error.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
multiply() [2/2]
virtual void Mantid::API::IEventList::multiply (const MantidVec & X, const MantidVec & Y, const MantidVec & E) pure virtual
Multiply event list by a histogram.
Implemented in Mantid::DataObjects::EventList.
reserve()
virtual void Mantid::API::IEventList::reserve (size_t num) pure virtual
Reserve a fixed size for the list.
Implemented in Mantid::DataObjects::EventList.
scaleTof()
virtual void Mantid::API::IEventList::scaleTof (const double factor) pure virtual
Scale the TOF values by a constant.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
setTofs()
virtual void Mantid::API::IEventList::setTofs (const MantidVec & tofs) pure virtual
Set the TOFs from the given list.
Implemented in Mantid::DataObjects::EventList.
switchTo()
virtual void Mantid::API::IEventList::switchTo (Mantid::API::EventType newType) pure virtual
Switch to a new event type within the list.
Implemented in Mantid::DataObjects::EventList.
Referenced by export_IEventList().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IEventList.h