Mantid: Mantid::Crystal::PeakClusterProjection Class Reference
Mantid::Crystal::PeakClusterProjection Class Reference
PeakClusterProjection : Maps peaks onto IMDHistoWorkspaces and returns the signal value at the peak center.
#include <PeakClusterProjection.h>
Public Member Functions
PeakClusterProjection & operator= (const PeakClusterProjection &)=delete
Mantid::Kernel::V3D peakCenter (const Mantid::Geometry::IPeak &peak) const
Get the peak center.
PeakClusterProjection (const PeakClusterProjection &)=delete
PeakClusterProjection (std::shared_ptr< Mantid::API::IMDEventWorkspace > &mdWS)
Constructor.
PeakClusterProjection (std::shared_ptr< Mantid::API::IMDHistoWorkspace > &mdWS)
Constructor.
PeakClusterProjection (std::shared_ptr< Mantid::API::IMDWorkspace > &mdWS)
Constructor.
Mantid::signal_t signalAtPeakCenter (const Mantid::Geometry::IPeak &peak, Mantid::API::MDNormalization normalization=Mantid::API::NoNormalization) const
Get the signal value at the peak center.
virtual ~PeakClusterProjection ()=default
Destructor.
Private Attributes
std::shared_ptr< Mantid::API::IMDWorkspace > m_mdWS
Image.
std::shared_ptr< Mantid::Geometry::PeakTransform > m_peakTransform
Peak Transform.
Detailed Description
PeakClusterProjection : Maps peaks onto IMDHistoWorkspaces and returns the signal value at the peak center.
Definition at line 28 of file PeakClusterProjection.h.
Constructor & Destructor Documentation
PeakClusterProjection() [1/4]
Mantid::Crystal::PeakClusterProjection::PeakClusterProjection (std::shared_ptr< Mantid::API::IMDWorkspace > & mdWS)
Constructor.
Parameters
mdWS Input image workspace to base the projection on and to take the coordinate system from.
Definition at line 70 of file PeakClusterProjection.cpp.
References m_peakTransform.
PeakClusterProjection() [2/4]
Mantid::Crystal::PeakClusterProjection::PeakClusterProjection (std::shared_ptr< Mantid::API::IMDHistoWorkspace > & mdWS)
Constructor.
Parameters
mdWS Input image workspace to base the projection on and to take the coordinate system from.
Definition at line 83 of file PeakClusterProjection.cpp.
References m_peakTransform.
PeakClusterProjection() [3/4]
Mantid::Crystal::PeakClusterProjection::PeakClusterProjection (std::shared_ptr< Mantid::API::IMDEventWorkspace > & mdWS)
Constructor.
Parameters
mdWS Input mdevent workspace to base the projection on and to take the coordinate system from.
Definition at line 97 of file PeakClusterProjection.cpp.
References m_peakTransform.
PeakClusterProjection() [4/4]
Mantid::Crystal::PeakClusterProjection::PeakClusterProjection (const PeakClusterProjection &) delete
~PeakClusterProjection()
virtual Mantid::Crystal::PeakClusterProjection::~PeakClusterProjection () virtual default
Destructor.
Member Function Documentation
operator=()
PeakClusterProjection & Mantid::Crystal::PeakClusterProjection::operator= (const PeakClusterProjection &) delete
peakCenter()
Mantid::Kernel::V3D Mantid::Crystal::PeakClusterProjection::peakCenter (const Mantid::Geometry::IPeak & peak) const
Get the peak center.
Returns
Get the peak center in the current coordinate system.
Definition at line 109 of file PeakClusterProjection.cpp.
References m_peakTransform.
Referenced by Mantid::Crystal::IntegratePeaksHybrid::exec().
signalAtPeakCenter()
Mantid::signal_t Mantid::Crystal::PeakClusterProjection::signalAtPeakCenter (const Mantid::Geometry::IPeak & peak, Mantid::API::MDNormalization normalization = Mantid::API::NoNormalization) const
Get the signal value at the peak center.
Parameters
peak
normalization : Optional normalization. Off by default.
Returns
signal value at peak center. NAN if the peak is not centered on the image.
Definition at line 120 of file PeakClusterProjection.cpp.
References m_mdWS, and m_peakTransform.
Referenced by Mantid::Crystal::IntegratePeaksHybrid::exec(), and Mantid::Crystal::IntegratePeaksUsingClusters::exec().
Member Data Documentation
m_mdWS
std::shared_ptr<Mantid::API::IMDWorkspace> Mantid::Crystal::PeakClusterProjection::m_mdWS private
Image.
Definition at line 48 of file PeakClusterProjection.h.
Referenced by signalAtPeakCenter().
m_peakTransform
std::shared_ptr<Mantid::Geometry::PeakTransform> Mantid::Crystal::PeakClusterProjection::m_peakTransform private
Peak Transform.
Definition at line 51 of file PeakClusterProjection.h.
Referenced by peakCenter(), PeakClusterProjection(), and signalAtPeakCenter().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/PeakClusterProjection.h
Framework/Crystal/src/PeakClusterProjection.cpp