Mantid: MantidQt::MantidWidgets::MultifitSetupDialog Class Reference
MantidQt::MantidWidgets::MultifitSetupDialog Class Reference
This is a dialog for doing setting up the MultiBG function.
#include <MultifitSetupDialog.h>
Public Member Functions
QStringList getParameterTies () const
Returns a list of parameter ties.
MultifitSetupDialog (FitPropertyBrowser *fitBrowser)
Default constructor.
Private Slots
void accept () override
Setup the function and close dialog.
void cellChanged (int, int)
Private Attributes
FitPropertyBrowser * m_fitBrowser
Pointer to the calling fit browser.
QStringList m_ties
A list with parameter ties.
Ui::MultifitSetupDialog ui
The form generated with Qt Designer.
Detailed Description
This is a dialog for doing setting up the MultiBG function.
Author
Roman Tolchenov, Tessella plc
Date
7/09/2011
Definition at line 22 of file MultifitSetupDialog.h.
Constructor & Destructor Documentation
MultifitSetupDialog()
MantidQt::MantidWidgets::MultifitSetupDialog::MultifitSetupDialog (FitPropertyBrowser * fitBrowser)
Default constructor.
Constructor.
Parameters
fitBrowser
Definition at line 26 of file MultifitSetupDialog.cpp.
References cellChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), m_fitBrowser, and ui.
Member Function Documentation
accept
void MantidQt::MantidWidgets::MultifitSetupDialog::accept () override private slot
Setup the function and close dialog.
Definition at line 47 of file MultifitSetupDialog.cpp.
References m_ties, and ui.
cellChanged
void MantidQt::MantidWidgets::MultifitSetupDialog::cellChanged (int row, int col) private slot
Definition at line 59 of file MultifitSetupDialog.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), m_fitBrowser, and ui.
Referenced by MultifitSetupDialog().
getParameterTies()
QStringList MantidQt::MantidWidgets::MultifitSetupDialog::getParameterTies () const inline
Returns a list of parameter ties.
Empty string means no ties and parameter is local
Definition at line 31 of file MultifitSetupDialog.h.
References m_ties.
Member Data Documentation
m_fitBrowser
FitPropertyBrowser* MantidQt::MantidWidgets::MultifitSetupDialog::m_fitBrowser private
Pointer to the calling fit browser.
Definition at line 44 of file MultifitSetupDialog.h.
Referenced by cellChanged(), and MultifitSetupDialog().
m_ties
QStringList MantidQt::MantidWidgets::MultifitSetupDialog::m_ties private
A list with parameter ties.
Definition at line 47 of file MultifitSetupDialog.h.
Referenced by accept(), and getParameterTies().
ui
Ui::MultifitSetupDialog MantidQt::MantidWidgets::MultifitSetupDialog::ui private
The form generated with Qt Designer.
Definition at line 41 of file MultifitSetupDialog.h.
Referenced by accept(), cellChanged(), and MultifitSetupDialog().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MultifitSetupDialog.h
qt/widgets/common/src/MultifitSetupDialog.cpp