Mantid: ICat4::ns1__delete Class Reference
ICat4::ns1__delete Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__delete ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__entityBaseBean * bean
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1250 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__delete()
ICat4::ns1__delete::ns1__delete () inline
Definition at line 1262 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__delete::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6979 of file ICat4C.cpp.
Referenced by ICat4::soap_in_ns1__delete(), ICat4::soap_new_req_ns1__delete(), and ICat4::soap_new_set_ns1__delete().
soap_get()
void * ICat4::ns1__delete::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7079 of file ICat4C.cpp.
References ICat4::soap_get_ns1__delete().
soap_in()
void * ICat4::ns1__delete::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7011 of file ICat4C.cpp.
References ICat4::soap_in_ns1__delete().
Referenced by ICat4::soap_in_ns1__delete().
soap_out()
int ICat4::ns1__delete::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6995 of file ICat4C.cpp.
References ICat4::soap_out_ns1__delete().
soap_put()
int ICat4::ns1__delete::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7072 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__delete.
soap_serialize()
void ICat4::ns1__delete::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6986 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__entityBaseBean(), and ICat4::soap_serialize_PointerTostd__string().
soap_type()
int ICat4::ns1__delete::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1255 of file ICat4Stub.h.
Member Data Documentation
bean
ns1__entityBaseBean* ICat4::ns1__delete::bean
Definition at line 1253 of file ICat4Stub.h.
sessionId
std::string* ICat4::ns1__delete::sessionId
Definition at line 1252 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp