Mantid: Mantid::WorkflowAlgorithms::EQSANSInstrument Namespace Reference
Mantid::WorkflowAlgorithms::EQSANSInstrument Namespace Reference
Functions
void getCoordinateFromPixel (const double &pixel_x, const double &pixel_y, const API::MatrixWorkspace_sptr &dataWS, double &x, double &y)
void getDefaultBeamCenter (const API::MatrixWorkspace_sptr &dataWS, double &pixel_x, double &pixel_y)
int getDetectorFromPixel (const int &pixel_x, const int &pixel_y, const API::MatrixWorkspace_sptr &dataWS)
void getPixelFromCoordinate (const double &x, const double &y, const API::MatrixWorkspace_sptr &dataWS, double &pixel_x, double &pixel_y)
double readInstrumentParameter (const std::string &parameter, const API::MatrixWorkspace_sptr &dataWS)
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Variables
const double default_slit_positions [3][8]
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Function Documentation
getCoordinateFromPixel()
void Mantid::WorkflowAlgorithms::EQSANSInstrument::getCoordinateFromPixel (const double & pixel_x, const double & pixel_y, const API::MatrixWorkspace_sptr & dataWS, double & x, double & y)
Definition at line 45 of file EQSANSInstrument.cpp.
References readInstrumentParameter(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter().
getDefaultBeamCenter()
void Mantid::WorkflowAlgorithms::EQSANSInstrument::getDefaultBeamCenter (const API::MatrixWorkspace_sptr & dataWS, double & pixel_x, double & pixel_y)
Definition at line 76 of file EQSANSInstrument.cpp.
References getPixelFromCoordinate().
Referenced by Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter().
getDetectorFromPixel()
int Mantid::WorkflowAlgorithms::EQSANSInstrument::getDetectorFromPixel (const int & pixel_x, const int & pixel_y, const API::MatrixWorkspace_sptr & dataWS)
Definition at line 36 of file EQSANSInstrument.cpp.
References readInstrumentParameter().
Referenced by Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter().
getPixelFromCoordinate()
void Mantid::WorkflowAlgorithms::EQSANSInstrument::getPixelFromCoordinate (const double & x, const double & y, const API::MatrixWorkspace_sptr & dataWS, double & pixel_x, double & pixel_y)
Definition at line 62 of file EQSANSInstrument.cpp.
References readInstrumentParameter(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), and getDefaultBeamCenter().
readInstrumentParameter()
double Mantid::WorkflowAlgorithms::EQSANSInstrument::readInstrumentParameter (const std::string & parameter, const API::MatrixWorkspace_sptr & dataWS)
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 26 of file EQSANSInstrument.cpp.
Referenced by getCoordinateFromPixel(), getDetectorFromPixel(), and getPixelFromCoordinate().
Variable Documentation
default_slit_positions
const double Mantid::WorkflowAlgorithms::EQSANSInstrument::default_slit_positions[3][8]
Initial value:
= {{5.0, 10.0, 10.0, 15.0, 20.0, 20.0, 25.0, 40.0},
                                             {0.0, 10.0, 10.0, 15.0, 15.0, 20.0, 20.0, 40.0},
                                             {0.0, 10.0, 10.0, 15.0, 15.0, 20.0, 20.0, 40.0}}
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 21 of file EQSANSInstrument.h.