Mantid: Mantid::Kernel::LabelUnit Class Reference
Mantid::Kernel::LabelUnit Class Reference
#include <MDUnit.h>
Public Member Functions
bool canConvertTo (const MDUnit &other) const override
LabelUnit * clone () const override
UnitLabel getUnitLabel () const override
bool isQUnit () const override
LabelUnit (UnitLabel unitLabel)
Public Member Functions inherited from Mantid::Kernel::MDUnit
bool operator== (const MDUnit &other) const
virtual ~MDUnit ()=default
Private Attributes
UnitLabel m_unitLabel
Detailed Description
Definition at line 58 of file MDUnit.h.
Constructor & Destructor Documentation
LabelUnit()
Mantid::Kernel::LabelUnit::LabelUnit (UnitLabel unitLabel)
Definition at line 80 of file MDUnit.cpp.
Member Function Documentation
canConvertTo()
bool Mantid::Kernel::LabelUnit::canConvertTo (const MDUnit & other) const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 84 of file MDUnit.cpp.
References Mantid::Kernel::MDUnit::getUnitLabel(), and getUnitLabel().
clone()
LabelUnit * Mantid::Kernel::LabelUnit::clone () const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 92 of file MDUnit.cpp.
References m_unitLabel.
getUnitLabel()
UnitLabel Mantid::Kernel::LabelUnit::getUnitLabel () const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 82 of file MDUnit.cpp.
References m_unitLabel.
Referenced by canConvertTo().
isQUnit()
bool Mantid::Kernel::LabelUnit::isQUnit () const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 86 of file MDUnit.cpp.
References Mantid::Kernel::UnitLabel::ascii(), and m_unitLabel.
Member Data Documentation
m_unitLabel
UnitLabel Mantid::Kernel::LabelUnit::m_unitLabel private
Definition at line 60 of file MDUnit.h.
Referenced by clone(), getUnitLabel(), and isQUnit().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MDUnit.h
Framework/Kernel/src/MDUnit.cpp