Mantid: MantidQt::MantidWidgets::IFitScriptGeneratorPresenter Class Reference
MantidQt::MantidWidgets::IFitScriptGeneratorPresenter Class Reference abstract
#include <IFitScriptGeneratorPresenter.h>
Public Member Functions
virtual void handleAddDomainAccepted (std::vector< Mantid::API::MatrixWorkspace_const_sptr > const &workspaces, FunctionModelSpectra const &workspaceIndices)=0
virtual void notifyPresenter (ViewEvent const &event, FittingMode fittingMode)=0
virtual void notifyPresenter (ViewEvent const &event, std::string const &arg1="", std::string const &arg2="")=0
virtual void notifyPresenter (ViewEvent const &event, std::vector< std::string > const &vec)=0
virtual void openFitScriptGenerator ()=0
virtual void setGlobalParameters (std::vector< MantidQt::MantidWidgets::GlobalParameter > const &globalParameters)=0
virtual void setGlobalTies (std::vector< MantidQt::MantidWidgets::GlobalTie > const &globalTies)=0
virtual ~IFitScriptGeneratorPresenter ()=default
Detailed Description
Definition at line 24 of file IFitScriptGeneratorPresenter.h.
Constructor & Destructor Documentation
~IFitScriptGeneratorPresenter()
virtual MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::~IFitScriptGeneratorPresenter () virtual default
Member Function Documentation
handleAddDomainAccepted()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::handleAddDomainAccepted (std::vector< Mantid::API::MatrixWorkspace_const_sptr > const & workspaces, FunctionModelSpectra const & workspaceIndices) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorView::addWorkspaceDialogAccepted().
notifyPresenter() [1/3]
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, FittingMode fittingMode) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
notifyPresenter() [2/3]
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, std::string const & arg1 = "", std::string const & arg2 = "") pure virtual
Implemented in MockFitScriptGeneratorPresenter, and MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSClearEvent(), MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSDeleteEvent(), MantidQt::MantidWidgets::FitScriptGeneratorView::notifyADSRenameEvent(), MantidQt::MantidWidgets::FitScriptGeneratorView::onAddDomainClicked(), MantidQt::MantidWidgets::FitScriptGeneratorView::onAttributeChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onCellChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onEditLocalParameterClicked(), MantidQt::MantidWidgets::FitScriptGeneratorView::onEditLocalParameterFinished(), MantidQt::MantidWidgets::FitScriptGeneratorView::onFittingModeChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionAdded(), MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionRemoved(), MantidQt::MantidWidgets::FitScriptGeneratorView::onFunctionReplaced(), MantidQt::MantidWidgets::FitScriptGeneratorView::onGenerateScriptToClipboardClicked(), MantidQt::MantidWidgets::FitScriptGeneratorView::onGenerateScriptToFileClicked(), MantidQt::MantidWidgets::FitScriptGeneratorView::onGlobalParametersChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onItemSelected(), MantidQt::MantidWidgets::FitScriptGeneratorView::onOutputBaseNameChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterConstraintChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterConstraintRemoved(), MantidQt::MantidWidgets::FitScriptGeneratorView::onParameterTieChanged(), MantidQt::MantidWidgets::FitScriptGeneratorView::onRemoveDomainClicked(), and MantidQt::MantidWidgets::FitScriptGeneratorView::subscribePresenter().
notifyPresenter() [3/3]
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::notifyPresenter (ViewEvent const & event, std::vector< std::string > const & vec) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
openFitScriptGenerator()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::openFitScriptGenerator () pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
setGlobalParameters()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalParameters (std::vector< MantidQt::MantidWidgets::GlobalParameter > const & globalParameters) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::setFittingMode().
setGlobalTies()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorPresenter::setGlobalTies (std::vector< MantidQt::MantidWidgets::GlobalTie > const & globalTies) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorPresenter.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::checkGlobalTies(), MantidQt::MantidWidgets::FitScriptGeneratorModel::clearGlobalTie(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::setFittingMode().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorPresenter.h