Mantid: Mantid::DataObjects::PeakComparator Class Reference
Mantid::DataObjects::PeakComparator Class Reference
Comparator class for sorting peaks by one or more criteria.
Public Types
using ColumnAndDirection = LeanElasticPeaksWorkspace::ColumnAndDirection
using ColumnAndDirection = PeaksWorkspace::ColumnAndDirection
Public Member Functions
bool operator() (const LeanElasticPeak &a, const LeanElasticPeak &b)
Compare two peaks using the stored criteria.
bool operator() (const Peak &a, const Peak &b)
Compare two peaks using the stored criteria.
PeakComparator (std::vector< ColumnAndDirection > &criteria)
Constructor for the comparator for sorting peaks.
PeakComparator (std::vector< ColumnAndDirection > &criteria)
Constructor for the comparator for sorting peaks.
Public Attributes
std::vector< ColumnAndDirection > & criteria
Detailed Description
Comparator class for sorting peaks by one or more criteria.
Definition at line 54 of file LeanElasticPeaksWorkspace.cpp.
Member Typedef Documentation
ColumnAndDirection [1/2]
using Mantid::DataObjects::PeakComparator::ColumnAndDirection = LeanElasticPeaksWorkspace::ColumnAndDirection
Definition at line 56 of file LeanElasticPeaksWorkspace.cpp.
ColumnAndDirection [2/2]
using Mantid::DataObjects::PeakComparator::ColumnAndDirection = PeaksWorkspace::ColumnAndDirection
Definition at line 56 of file PeaksWorkspace.cpp.
Constructor & Destructor Documentation
PeakComparator() [1/2]
Mantid::DataObjects::PeakComparator::PeakComparator (std::vector< ColumnAndDirection > & criteria) inline explicit
Constructor for the comparator for sorting peaks.
Parameters
criteria : a vector with a list of pairs: column name, bool; where bool = true for ascending, false for descending sort.
Definition at line 63 of file LeanElasticPeaksWorkspace.cpp.
PeakComparator() [2/2]
Mantid::DataObjects::PeakComparator::PeakComparator (std::vector< ColumnAndDirection > & criteria) inline explicit
Constructor for the comparator for sorting peaks.
Parameters
criteria : a vector with a list of pairs: column name, bool; where bool = true for ascending, false for descending sort.
Definition at line 63 of file PeaksWorkspace.cpp.
Member Function Documentation
operator()() [1/2]
bool Mantid::DataObjects::PeakComparator::operator() (const LeanElasticPeak & a, const LeanElasticPeak & b) inline
Compare two peaks using the stored criteria.
Definition at line 66 of file LeanElasticPeaksWorkspace.cpp.
References criteria, Mantid::DataObjects::BasePeak::getValueByColName(), and name.
operator()() [2/2]
bool Mantid::DataObjects::PeakComparator::operator() (const Peak & a, const Peak & b) inline
Compare two peaks using the stored criteria.
Definition at line 66 of file PeaksWorkspace.cpp.
References criteria, Mantid::DataObjects::Peak::getBankName(), Mantid::DataObjects::Peak::getValueByColName(), and name.
Member Data Documentation
criteria
std::vector< ColumnAndDirection > & Mantid::DataObjects::PeakComparator::criteria
Definition at line 57 of file LeanElasticPeaksWorkspace.cpp.
Referenced by operator()(), and operator()().
The documentation for this class was generated from the following files:
Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
Framework/DataObjects/src/PeaksWorkspace.cpp