Mantid: SANSInstrumentCreationHelper Class Reference
SANSInstrumentCreationHelper Class Reference
#include <SANSInstrumentCreationHelper.h>
Static Public Member Functions
static Mantid::DataObjects::Workspace2D_sptr createSANSInstrumentWorkspace (const std::string &workspace)
static void runLoadInstrument (const std::string &inst_name, const Mantid::DataObjects::Workspace2D_sptr &workspace)
Run the Child Algorithm LoadInstrument (as for LoadRaw)
static void runLoadMappingTable (const Mantid::DataObjects::Workspace2D_sptr &workspace, int nxbins, int nybins)
Populate spectra mapping to detector IDs.
Static Public Attributes
static const int nBins = 30
static const int nMonitors = 2
Detailed Description
Definition at line 20 of file SANSInstrumentCreationHelper.h.
Member Function Documentation
createSANSInstrumentWorkspace()
Workspace2D_sptr SANSInstrumentCreationHelper::createSANSInstrumentWorkspace (const std::string & workspace) static
Definition at line 46 of file SANSInstrumentCreationHelper.cpp.
References WorkspaceCreationHelper::create2DWorkspace123(), Mantid::Kernel::SingletonHolder< T >::Instance(), nBins, nMonitors, runLoadInstrument(), runLoadMappingTable(), and workspace.
runLoadInstrument()
void SANSInstrumentCreationHelper::runLoadInstrument (const std::string & inst_name, const Mantid::DataObjects::Workspace2D_sptr & workspace) static
Run the Child Algorithm LoadInstrument (as for LoadRaw)
Parameters
inst_name :: The name written in the Nexus file
workspace :: The workspace to insert the instrument into
Definition at line 65 of file SANSInstrumentCreationHelper.cpp.
References Mantid::API::Algorithm::execute(), Mantid::API::Algorithm::initialize(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::API::Algorithm::setPropertyValue(), and workspace.
Referenced by createSANSInstrumentWorkspace().
runLoadMappingTable()
void SANSInstrumentCreationHelper::runLoadMappingTable (const Mantid::DataObjects::Workspace2D_sptr & workspace, int nxbins, int nybins) static
Populate spectra mapping to detector IDs.
Parameters
workspace Workspace2D object
nxbins number of bins in X
nybins number of bins in Y
Parameters
workspace Workspace2D object
nxbins number of bins in X
nybins number of bins in Y
Definition at line 92 of file SANSInstrumentCreationHelper.cpp.
References error, nMonitors, and workspace.
Referenced by createSANSInstrumentWorkspace().
Member Data Documentation
nBins
const int SANSInstrumentCreationHelper::nBins = 30 static
Definition at line 23 of file SANSInstrumentCreationHelper.h.
Referenced by createSANSInstrumentWorkspace().
nMonitors
const int SANSInstrumentCreationHelper::nMonitors = 2 static
Definition at line 25 of file SANSInstrumentCreationHelper.h.
Referenced by createSANSInstrumentWorkspace(), and runLoadMappingTable().
The documentation for this class was generated from the following files:
Framework/TestHelpers/inc/MantidFrameworkTestHelpers/SANSInstrumentCreationHelper.h
Framework/TestHelpers/src/SANSInstrumentCreationHelper.cpp