Mantid: MantidQt::MantidWidgets::IFitScriptGeneratorView Class Reference
MantidQt::MantidWidgets::IFitScriptGeneratorView Class Reference abstract
#include <IFitScriptGeneratorView.h>
Public Types
enum class Event {
ADSDeleteEvent , ADSClearEvent , ADSRenameEvent , RemoveDomainClicked ,
AddDomainClicked , StartXChanged , EndXChanged , SelectionChanged ,
FunctionRemoved , FunctionAdded , FunctionReplaced , ParameterChanged ,
AttributeChanged , ParameterTieChanged , ParameterConstraintRemoved , ParameterConstraintChanged ,
GlobalParametersChanged , EditLocalParameterClicked , EditLocalParameterFinished , OutputBaseNameChanged ,
FittingModeChanged , GenerateScriptToFileClicked , GenerateScriptToClipboardClicked
}
Public Member Functions
virtual QPushButton * addWorkspaceButton () const =0
virtual void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX)=0
virtual std::vector< FitDomainIndex > allRows () const =0
virtual bool applyFunctionChangesToAll () const =0
virtual Mantid::API::IFunction::Attribute attributeValue (std::string const &attribute) const =0
virtual void clearFunction ()=0
virtual FitDomainIndex currentRow () const =0
virtual void displayWarning (std::string const &message)=0
virtual double endX (FitDomainIndex index) const =0
virtual std::string filepath () const =0
virtual std::tuple< std::string, std::string, std::string, std::string, std::string, bool > fitOptions () const =0
virtual QPushButton * generateScriptToClipboardButton () const =0
virtual QPushButton * generateScriptToFileButton () const =0
virtual std::vector< Mantid::API::MatrixWorkspace_const_sptr > getDialogWorkspaces (MantidWidgets::IAddWorkspaceDialog *dialog)=0
virtual std::tuple< std::string, std::vector< double >, std::vector< bool >, std::vector< std::string >, std::vector< std::string > > getEditLocalParameterResults () const =0
virtual bool hasLoadedData () const =0
IFitScriptGeneratorView (QWidget *parent=nullptr)
virtual void openAddWorkspaceDialog ()=0
virtual void openEditLocalParameterDialog (std::string const &parameter, std::vector< std::string > const &workspaceNames, std::vector< std::string > const &domainNames, std::vector< double > const &values, std::vector< bool > const &fixes, std::vector< std::string > const &ties, std::vector< std::string > const &constraints)=0
virtual double parameterValue (std::string const &parameter) const =0
virtual QPushButton * removeButton () const =0
virtual void removeDomain (FitDomainIndex domainIndex)=0
virtual void renameWorkspace (std::string const &workspaceName, std::string const &newName)=0
virtual void resetSelection ()=0
virtual void saveTextToClipboard (std::string const &text) const =0
virtual std::vector< FitDomainIndex > selectedRows () const =0
virtual void setFunction (Mantid::API::IFunction_sptr const &function) const =0
virtual void setGlobalParameters (std::vector< GlobalParameter > const &globalParameter)=0
virtual void setGlobalTies (std::vector< GlobalTie > const &globalTies)=0
virtual void setSimultaneousMode (bool simultaneousMode)=0
virtual void setSuccessText (std::string const &text)=0
virtual double startX (FitDomainIndex index) const =0
virtual void subscribePresenter (IFitScriptGeneratorPresenter *presenter)=0
virtual FitScriptGeneratorDataTable * tableWidget () const =0
Testing accessors.
virtual WorkspaceIndex workspaceIndex (FitDomainIndex index) const =0
virtual std::string workspaceName (FitDomainIndex index) const =0
virtual ~IFitScriptGeneratorView ()=default
Public Member Functions inherited from MantidQt::API::MantidWidget
virtual QVariant getUserInput () const
Returns a QVariant containing what the widget classes as user input so that input can be returned through a common interface.
virtual void setUserInput (const QVariant &value)
Sets a value on a mantid widget through a common interface.
Additional Inherited Members
Signals inherited from MantidQt::API::MantidWidget
void runAsPythonScript (const QString &code, bool)
Protected Member Functions inherited from MantidQt::API::MantidWidget
MantidWidget (QWidget *parent=nullptr)
Default constructor.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Detailed Description
Definition at line 36 of file IFitScriptGeneratorView.h.
Member Enumeration Documentation
Event
enum class MantidQt::MantidWidgets::IFitScriptGeneratorView::Event strong
Enumerator
ADSDeleteEvent
ADSClearEvent
ADSRenameEvent
RemoveDomainClicked
AddDomainClicked
StartXChanged
EndXChanged
SelectionChanged
FunctionRemoved
FunctionAdded
FunctionReplaced
ParameterChanged
AttributeChanged
ParameterTieChanged
ParameterConstraintRemoved
ParameterConstraintChanged
GlobalParametersChanged
EditLocalParameterClicked
EditLocalParameterFinished
OutputBaseNameChanged
FittingModeChanged
GenerateScriptToFileClicked
GenerateScriptToClipboardClicked
Definition at line 40 of file IFitScriptGeneratorView.h.
Constructor & Destructor Documentation
IFitScriptGeneratorView()
MantidQt::MantidWidgets::IFitScriptGeneratorView::IFitScriptGeneratorView (QWidget * parent = nullptr) inline
Definition at line 66 of file IFitScriptGeneratorView.h.
~IFitScriptGeneratorView()
virtual MantidQt::MantidWidgets::IFitScriptGeneratorView::~IFitScriptGeneratorView () virtual default
Member Function Documentation
addWorkspaceButton()
virtual QPushButton * MantidQt::MantidWidgets::IFitScriptGeneratorView::addWorkspaceButton () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
addWorkspaceDomain()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::addWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace().
allRows()
virtual std::vector< FitDomainIndex > MantidQt::MantidWidgets::IFitScriptGeneratorView::allRows () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getDomainsWithLocalParameter(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getRowIndices(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSClearEvent(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSDeleteEvent(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterData().
applyFunctionChangesToAll()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorView::applyFunctionChangesToAll () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getRowIndices().
attributeValue()
virtual Mantid::API::IFunction::Attribute MantidQt::MantidWidgets::IFitScriptGeneratorView::attributeValue (std::string const & attribute) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAttributeChanged().
clearFunction()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::clearFunction () pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionStructure().
currentRow()
virtual FitDomainIndex MantidQt::MantidWidgets::IFitScriptGeneratorView::currentRow () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateXLimitForDomain().
displayWarning()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::displayWarning (std::string const & message) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::checkForWarningMessages(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateFitScript(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleGlobalParametersChanged(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateEndX(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionStructure(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateStartX().
endX()
virtual double MantidQt::MantidWidgets::IFitScriptGeneratorView::endX (FitDomainIndex index) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEndXChanged().
filepath()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorView::filepath () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToFile().
fitOptions()
virtual std::tuple< std::string, std::string, std::string, std::string, std::string, bool > MantidQt::MantidWidgets::IFitScriptGeneratorView::fitOptions () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToClipboard(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToFile().
generateScriptToClipboardButton()
virtual QPushButton * MantidQt::MantidWidgets::IFitScriptGeneratorView::generateScriptToClipboardButton () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
generateScriptToFileButton()
virtual QPushButton * MantidQt::MantidWidgets::IFitScriptGeneratorView::generateScriptToFileButton () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
getDialogWorkspaces()
virtual std::vector< Mantid::API::MatrixWorkspace_const_sptr > MantidQt::MantidWidgets::IFitScriptGeneratorView::getDialogWorkspaces (MantidWidgets::IAddWorkspaceDialog * dialog) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
getEditLocalParameterResults()
virtual std::tuple< std::string, std::vector< double >, std::vector< bool >, std::vector< std::string >, std::vector< std::string > > MantidQt::MantidWidgets::IFitScriptGeneratorView::getEditLocalParameterResults () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEditLocalParameterFinished().
hasLoadedData()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorView::hasLoadedData () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionStructure(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateXLimitForDomain().
openAddWorkspaceDialog()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::openAddWorkspaceDialog () pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleAddDomainClicked().
openEditLocalParameterDialog()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::openEditLocalParameterDialog (std::string const & parameter, std::vector< std::string > const & workspaceNames, std::vector< std::string > const & domainNames, std::vector< double > const & values, std::vector< bool > const & fixes, std::vector< std::string > const & ties, std::vector< std::string > const & constraints) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEditLocalParameterClicked().
parameterValue()
virtual double MantidQt::MantidWidgets::IFitScriptGeneratorView::parameterValue (std::string const & parameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterChanged().
removeButton()
virtual QPushButton * MantidQt::MantidWidgets::IFitScriptGeneratorView::removeButton () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
removeDomain()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::removeDomain (FitDomainIndex domainIndex) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeDomains().
renameWorkspace()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::renameWorkspace (std::string const & workspaceName, std::string const & newName) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSRenameEvent().
resetSelection()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::resetSelection () pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateEndX(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateStartX().
saveTextToClipboard()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::saveTextToClipboard (std::string const & text) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToClipboard().
selectedRows()
virtual std::vector< FitDomainIndex > MantidQt::MantidWidgets::IFitScriptGeneratorView::selectedRows () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getRowIndices(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleRemoveDomainClicked().
setFunction()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::setFunction (Mantid::API::IFunction_sptr const & function) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel().
setGlobalParameters()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::setGlobalParameters (std::vector< GlobalParameter > const & globalParameter) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setGlobalParameters().
setGlobalTies()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::setGlobalTies (std::vector< GlobalTie > const & globalTies) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setGlobalTies().
setSimultaneousMode()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::setSimultaneousMode (bool simultaneousMode) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged().
setSuccessText()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::setSuccessText (std::string const & text) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToClipboard(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToFile().
startX()
virtual double MantidQt::MantidWidgets::IFitScriptGeneratorView::startX (FitDomainIndex index) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleStartXChanged().
subscribePresenter()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorView::subscribePresenter (IFitScriptGeneratorPresenter * presenter) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::FitScriptGeneratorPresenter().
tableWidget()
virtual FitScriptGeneratorDataTable * MantidQt::MantidWidgets::IFitScriptGeneratorView::tableWidget () const pure virtual
Testing accessors.
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
workspaceIndex()
virtual WorkspaceIndex MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceIndex (FitDomainIndex index) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::invokeFunctionForDomain(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel().
workspaceName()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorView::workspaceName (FitDomainIndex index) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorView.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSDeleteEvent(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::invokeFunctionForDomain(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorView.h