Mantid: MantidQt::MantidWidgets::IProjectSaveView Class Reference
MantidQt::MantidWidgets::IProjectSaveView Class Reference abstract
IProjectSaveView is the interface for defining the functions that the project save view needs to implement.
#include <IProjectSaveView.h>
Public Member Functions
virtual std::vector< std::string > getAllPythonInterfaces ()=0
Get all active python interfaces names passed to the view.
virtual std::vector< std::string > getCheckedPythonInterfaces ()=0
Get any checked interface names on the view.
virtual std::vector< std::string > getCheckedWorkspaceNames ()=0
Get the names of all checked workspaces.
virtual QString getProjectPath ()=0
Get the project path.
virtual std::vector< std::string > getUncheckedPythonInterfaces ()=0
Get any unchecked interface names on the view.
virtual std::vector< std::string > getUncheckedWorkspaceNames ()=0
Get the names of all unchecked workspaces.
virtual std::vector< MantidQt::API::IProjectSerialisable * > getWindows ()=0
Get all window handles passed to the view.
virtual void removeFromExcludedWindowsList (const std::vector< std::string > &windows)=0
Remove items from the excluded window list.
virtual void removeFromIncludedWindowsList (const std::vector< std::string > &windows)=0
Remove items from the included window list.
virtual void setProjectPath (const QString &path)=0
Set the project path.
virtual void updateExcludedWindowsList (const std::vector< WindowInfo > &windows)=0
Update the excluded windows list with a collection of window info items.
virtual void updateIncludedWindowsList (const std::vector< WindowInfo > &windows)=0
Update the included windows list with a collection of window info items.
virtual void updateInterfacesList (const std::vector< std::string > &interfaces)=0
Update the list of interfaces.
virtual void updateWorkspacesList (const std::vector< WorkspaceInfo > &workspaces)=0
Update the workspaces list with a collection of workspace info items.
Detailed Description
IProjectSaveView is the interface for defining the functions that the project save view needs to implement.
Definition at line 28 of file IProjectSaveView.h.
Member Function Documentation
getAllPythonInterfaces()
virtual std::vector< std::string > MantidQt::MantidWidgets::IProjectSaveView::getAllPythonInterfaces () pure virtual
Get all active python interfaces names passed to the view.
getCheckedPythonInterfaces()
virtual std::vector< std::string > MantidQt::MantidWidgets::IProjectSaveView::getCheckedPythonInterfaces () pure virtual
Get any checked interface names on the view.
getCheckedWorkspaceNames()
virtual std::vector< std::string > MantidQt::MantidWidgets::IProjectSaveView::getCheckedWorkspaceNames () pure virtual
Get the names of all checked workspaces.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::includeWindowsForCheckedWorkspace().
getProjectPath()
virtual QString MantidQt::MantidWidgets::IProjectSaveView::getProjectPath () pure virtual
Get the project path.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::prepareProjectFolder().
getUncheckedPythonInterfaces()
virtual std::vector< std::string > MantidQt::MantidWidgets::IProjectSaveView::getUncheckedPythonInterfaces () pure virtual
Get any unchecked interface names on the view.
getUncheckedWorkspaceNames()
virtual std::vector< std::string > MantidQt::MantidWidgets::IProjectSaveView::getUncheckedWorkspaceNames () pure virtual
Get the names of all unchecked workspaces.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::excludeWindowsForUncheckedWorkspace().
getWindows()
virtual std::vector< MantidQt::API::IProjectSerialisable * > MantidQt::MantidWidgets::IProjectSaveView::getWindows () pure virtual
Get all window handles passed to the view.
removeFromExcludedWindowsList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::removeFromExcludedWindowsList (const std::vector< std::string > & windows) pure virtual
Remove items from the excluded window list.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::includeWindowsForCheckedWorkspace().
removeFromIncludedWindowsList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::removeFromIncludedWindowsList (const std::vector< std::string > & windows) pure virtual
Remove items from the included window list.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::excludeWindowsForUncheckedWorkspace().
setProjectPath()
virtual void MantidQt::MantidWidgets::IProjectSaveView::setProjectPath (const QString & path) pure virtual
Set the project path.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::prepareProjectFolder().
updateExcludedWindowsList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::updateExcludedWindowsList (const std::vector< WindowInfo > & windows) pure virtual
Update the excluded windows list with a collection of window info items.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::excludeWindowsForUncheckedWorkspace().
updateIncludedWindowsList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::updateIncludedWindowsList (const std::vector< WindowInfo > & windows) pure virtual
Update the included windows list with a collection of window info items.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::includeWindowsForCheckedWorkspace(), and MantidQt::MantidWidgets::ProjectSavePresenter::ProjectSavePresenter().
updateInterfacesList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::updateInterfacesList (const std::vector< std::string > & interfaces) pure virtual
Update the list of interfaces.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::ProjectSavePresenter().
updateWorkspacesList()
virtual void MantidQt::MantidWidgets::IProjectSaveView::updateWorkspacesList (const std::vector< WorkspaceInfo > & workspaces) pure virtual
Update the workspaces list with a collection of workspace info items.
Referenced by MantidQt::MantidWidgets::ProjectSavePresenter::ProjectSavePresenter().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IProjectSaveView.h