Mantid: MantidQt::MantidWidgets::ImageInfoModel::ImageInfo Class Reference
MantidQt::MantidWidgets::ImageInfoModel::ImageInfo Class Reference
#include <ImageInfoModel.h>
Public Types
using StringItems = std::vector< QString >
Public Member Functions
bool empty () const noexcept
ImageInfo (StringItems names)
Construct an ImageInfo to store name/value pairs.
const QString & name (int index) const noexcept
void setValue (int index, const QString &value) noexcept
int size () const noexcept
const QString & value (int index) const noexcept
Public Attributes
StringItems m_names
StringItems m_values
Detailed Description
Definition at line 24 of file ImageInfoModel.h.
Member Typedef Documentation
StringItems
using MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::StringItems = std::vector<QString>
Definition at line 26 of file ImageInfoModel.h.
Constructor & Destructor Documentation
ImageInfo()
MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::ImageInfo (StringItems names)
Construct an ImageInfo to store name/value pairs.
Parameters
names The names of the name/value pairs in the table
Definition at line 23 of file ImageInfoModel.cpp.
References m_names, m_values, and MantidQt::MantidWidgets::ImageInfoModel::MissingValue.
Member Function Documentation
empty()
bool MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::empty () const inline noexcept
Definition at line 29 of file ImageInfoModel.h.
Referenced by MantidQt::MantidWidgets::ImageInfoWidget::showInfo().
name()
const QString & MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::name (int index) const inline noexcept
Definition at line 31 of file ImageInfoModel.h.
References index.
Referenced by MantidQt::MantidWidgets::ImageInfoWidget::showInfo().
setValue()
void MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::setValue (int index, const QString & value) inline noexcept
Definition at line 33 of file ImageInfoModel.h.
References index, and value.
Referenced by MantidQt::MantidWidgets::ImageInfoModelMatrixWS::info(), MantidQt::MantidWidgets::ImageInfoModelMD::info(), and MantidQt::MantidWidgets::ImageInfoModelMatrixWS::setUnitsInfo().
size()
int MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::size () const inline noexcept
Definition at line 30 of file ImageInfoModel.h.
Referenced by MantidQt::MantidWidgets::ImageInfoWidget::showInfo().
value()
const QString & MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::value (int index) const inline noexcept
Definition at line 32 of file ImageInfoModel.h.
References index.
Referenced by MantidQt::MantidWidgets::ImageInfoWidget::showInfo().
Member Data Documentation
m_names
StringItems MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::m_names
Definition at line 34 of file ImageInfoModel.h.
Referenced by ImageInfo(), and MantidQt::MantidWidgets::ImageInfoModelMD::info().
m_values
StringItems MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::m_values
Definition at line 35 of file ImageInfoModel.h.
Referenced by ImageInfo(), and MantidQt::MantidWidgets::ImageInfoModelMD::info().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoModel.h
qt/widgets/common/src/ImageInfoModel.cpp