Mantid: Mantid::DataHandling::LoadISISNexus2 Class Reference
Mantid::DataHandling::LoadISISNexus2 Class Reference
Loads a file in a NeXus format and stores it in a 2D workspace.
#include <LoadISISNexus2.h>
Classes
struct SpectraBlock
Spectra block descriptor.
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
int confidence (Nexus::NexusDescriptorLazy &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadISISNexus2 ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void buildSpectraInd2SpectraNumMap (bool range_supplied, bool hasSpectraList, const DataBlockComposite &dataBlockComposite)
Build the list of spectra to load and include into spectra-detectors map.
bool checkOptionalProperties (bool bseparateMonitors, bool bexcludeMonitor)
Check the validity of the optional properties of the algorithm and identify if partial data should be loaded.
void checkOverlappingSpectraRange ()
Check if any of the spectra block ranges overlap.
void createPeriodLogs (int64_t period, DataObjects::Workspace2D_sptr &local_workspace)
Creates period log data in the workspace.
void exec () override
Overwrites Algorithm method.
bool findSpectraDetRangeInFile (const Nexus::NXEntry &entry, std::vector< specnum_t > &spectrum_index, int64_t ndets, int64_t n_vms_compat_spectra, const std::map< specnum_t, std::string > &monitors, bool excludeMonitors, bool separateMonitors)
Method takes input parameters which describe monitor loading and analyze them against spectra/monitor block information in the file.
void init () override
Overwrites Algorithm method.
bool isMultipleTimeRegimeFile (const Nexus::NXEntry &entry) const
Check if is the file is a multiple time regime file.
void loadBlock (Nexus::NXInt &data, int64_t blocksize, int64_t period, int64_t start, int64_t &hist, int64_t &spec_num, DataObjects::Workspace2D_sptr &local_workspace)
Perform a call to nxgetslab, via the NexusClasses wrapped methods for a given block-size.
void loadLogs (DataObjects::Workspace2D_sptr &ws)
Load log data from the nexus file.
void loadPeriodData (int64_t period, Mantid::Nexus::NXEntry &entry, DataObjects::Workspace2D_sptr &local_workspace, bool update_spectra2det_mapping=false)
Load a given period into the workspace.
void loadRunDetails (DataObjects::Workspace2D_sptr &local_workspace, Mantid::Nexus::NXEntry &entry)
Load in details about the run.
void loadSampleData (DataObjects::Workspace2D_sptr &, const Mantid::Nexus::NXEntry &entry)
Load in details about the sample.
size_t prepareSpectraBlocks (std::map< specnum_t, std::string > &monitors, DataBlockComposite &LoadBlock)
Prepare a vector of SpectraBlock structures to simplify loading.
void runLoadInstrument (DataObjects::Workspace2D_sptr &)
Run LoadInstrument as a ChildAlgorithm.
void validateMultiPeriodLogs (const Mantid::API::MatrixWorkspace_sptr &)
Check for a set of synthetic logs associated with multi-period log data.
Static Private Member Functions
static double dblSqrt (double in)
Personal wrapper for sqrt to allow msvs to compile.
Private Attributes
DataBlockComposite m_detBlockInfo
int64_t m_entrynumber
The number of the input entry.
std::string m_filename
The name and path of the input file.
bool m_hasVMSBlock
bool m_have_detector
Is there a detector block.
std::string m_instrument_name
The instrument name from Nexus.
bool m_load_selected_spectra
if true, a spectra list or range of spectra is supplied
DataBlockComposite m_loadBlockInfo
boost::scoped_ptr< API::ISISRunLogs > m_logCreator
A pointer to the ISISRunLogs creator.
DataBlockComposite m_monBlockInfo
std::map< specnum_t, std::string > m_monitors
Monitors, map spectrum index to monitor group name.
boost::scoped_ptr< Nexus::File > m_nexusFile
std::shared_ptr< API::Progress > m_progress
Progress reporting object.
std::string m_samplename
The sample name read from Nexus.
std::vector< specnum_t > m_spec
Spectra numbers.
API::SpectrumDetectorMapping m_spec2det_map
spectra Number to detector ID (multi)map
const specnum_t * m_spec_end
Pointer to one-past-the-end of spectrum number array (m_spec)
std::vector< SpectraBlock > m_spectraBlocks
List of disjoint data blocks to load.
std::shared_ptr< HistogramData::HistogramX > m_tof_data
Time channels.
std::map< int64_t, specnum_t > m_wsInd2specNum_map
map of workspace Index to spectra Number (spectraID)
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Loads a file in a NeXus format and stores it in a 2D workspace.
LoadISISNexus2 is an algorithm and as such inherits from the Algorithm class, via DataHandlingCommand, and overrides the init() & exec() methods.
Required Properties:
Filename - The name of and path to the input NeXus file
OutputWorkspace - The name of the workspace in which to store the imported data (a multi-period file will store higher periods in workspaces called OutputWorkspace_PeriodNo)
Optional Properties: (note that these options are not available if reading a multi-period file)
SpectrumMin - The starting spectrum number
SpectrumMax - The final spectrum number (inclusive)
SpectrumList - An ArrayProperty of spectra to load
Author
Roman Tolchenov, Tessella plc
Definition at line 59 of file LoadISISNexus2.h.
Constructor & Destructor Documentation
LoadISISNexus2()
Mantid::DataHandling::LoadISISNexus2::LoadISISNexus2 ()
Default constructor.
Empty default constructor.
Definition at line 69 of file LoadISISNexus2.cpp.
Member Function Documentation
buildSpectraInd2SpectraNumMap()
void Mantid::DataHandling::LoadISISNexus2::buildSpectraInd2SpectraNumMap (bool range_supplied, bool hasSpectraList, const DataBlockComposite & dataBlockComposite) private
Build the list of spectra to load and include into spectra-detectors map.
The map should be built if the user either specified a range or if the user provided a list of spectrum numbers.
Parameters
range_supplied if true specifies that the range of values provided below have to be processed rather then spectra list
hasSpectraList did the user specify a spectrum list
dataBlockComposite a data block composite specfiying the spectra intervals
Definition at line 603 of file LoadISISNexus2.cpp.
References Mantid::DataHandling::DataBlockComposite::getGenerator(), and m_wsInd2specNum_map.
Referenced by checkOptionalProperties(), and exec().
category()
const std::string Mantid::DataHandling::LoadISISNexus2::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 69 of file LoadISISNexus2.h.
checkOptionalProperties()
bool Mantid::DataHandling::LoadISISNexus2::checkOptionalProperties (bool bseparateMonitors, bool bexcludeMonitor) private
Check the validity of the optional properties of the algorithm and identify if partial data should be loaded.
Parameters
bseparateMonitors flag indicating if the monitors are to be loaded separately
bexcludeMonitor flag indicating if the monitors are to be excluded
Definition at line 415 of file LoadISISNexus2.cpp.
References buildSpectraInd2SpectraNumMap(), Mantid::EMPTY_INT(), Mantid::DataHandling::DataBlockComposite::getAllSpectrumNumbers(), Mantid::DataHandling::DataBlockComposite::getMaxSpectrumID(), Mantid::DataHandling::DataBlockComposite::getMinSpectrumID(), Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::DataHandling::DataBlockComposite::getNumberOfPeriods(), Mantid::API::Algorithm::getProperty(), Mantid::DataHandling::DataBlockComposite::isEmpty(), m_entrynumber, m_load_selected_spectra, m_loadBlockInfo, m_monBlockInfo, Mantid::DataHandling::populateDataBlockCompositeWithContainer(), Mantid::DataHandling::DataBlockComposite::removeSpectra(), std::to_string(), Mantid::DataHandling::DataBlockComposite::truncate(), and Mantid::Geometry::x.
Referenced by exec().
checkOverlappingSpectraRange()
void Mantid::DataHandling::LoadISISNexus2::checkOverlappingSpectraRange () private
Check if any of the spectra block ranges overlap.
Check if any spectra block ranges overlap.
Iterate over the sorted list of spectra blocks and check if the last element of the preceeding block is less than the first element of the next block.
Definition at line 676 of file LoadISISNexus2.cpp.
References m_spectraBlocks.
Referenced by prepareSpectraBlocks().
confidence()
int Mantid::DataHandling::LoadISISNexus2::confidence (Nexus::NexusDescriptorLazy & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence criteria for this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >.
Definition at line 81 of file LoadISISNexus2.cpp.
References Mantid::Nexus::NexusDescriptorLazy::isEntry().
Referenced by Mantid::DataHandling::UpdateInstrumentFromFile::exec().
createPeriodLogs()
void Mantid::DataHandling::LoadISISNexus2::createPeriodLogs (int64_t period, DataObjects::Workspace2D_sptr & local_workspace) private
Creates period log data in the workspace.
Parameters
period :: period number
local_workspace :: workspace to add period log data to.
Definition at line 773 of file LoadISISNexus2.cpp.
References m_logCreator.
Referenced by exec().
dblSqrt()
double Mantid::DataHandling::LoadISISNexus2::dblSqrt (double in) static private
Personal wrapper for sqrt to allow msvs to compile.
Definition at line 916 of file LoadISISNexus2.cpp.
exec()
void Mantid::DataHandling::LoadISISNexus2::exec () override private virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Exceptions
Exception::FileError If the Nexus file cannot be found/opened
std::invalid_argument If the optional properties are set to invalid values
Implements Mantid::API::Algorithm.
Definition at line 138 of file LoadISISNexus2.cpp.
References Mantid::API::ISISRunLogs::addPeriodLogs(), Mantid::Nexus::NXObject::address(), buildSpectraInd2SpectraNumMap(), checkOptionalProperties(), Mantid::Nexus::NXClass::containsGroup(), Mantid::DataObjects::create(), createPeriodLogs(), Mantid::API::Algorithm::declareProperty(), Mantid::Nexus::NXDataSet::dim0(), Mantid::Kernel::Logger::error(), Mantid::DataHandling::LoadISISNexusHelper::findDetectorIDsAndSpectrumNumber(), Mantid::DataHandling::LoadISISNexusHelper::findNumberOfSpectra(), findSpectraDetRangeInFile(), Mantid::API::Algorithm::g_log, Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::DataHandling::DataBlockComposite::getNumberOfPeriods(), Mantid::DataHandling::DataBlockComposite::getNumberOfSpectra(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Nexus::NXClass::getString(), Mantid::Nexus::NXClass::groups(), index, Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Nexus::NXDataSetTyped< T >::load(), loadLogs(), loadPeriodData(), loadRunDetails(), loadSampleData(), Mantid::DataHandling::LoadISISNexusHelper::loadTimeData(), m_detBlockInfo, m_entrynumber, Mantid::Nexus::NXObject::m_fileID, m_filename, m_hasVMSBlock, m_have_detector, m_instrument_name, m_load_selected_spectra, m_loadBlockInfo, m_monBlockInfo, m_monitors, m_nexusFile, m_progress, m_spec, m_spec2det_map, m_spec_end, m_spectraBlocks, m_tof_data, m_wsInd2specNum_map, Mantid::Nexus::NXRoot::openEntry(), Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), Mantid::Kernel::Direction::Output, prepareSpectraBlocks(), Mantid::DataHandling::LoadRawHelper::ProcessLoadMonitorOptions(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), runLoadInstrument(), Mantid::Kernel::IPropertyManager::setProperty(), validateMultiPeriodLogs(), Mantid::Nexus::NXDataSetTyped< T >::vecBuffer(), and Mantid::Kernel::Logger::warning().
findSpectraDetRangeInFile()
bool Mantid::DataHandling::LoadISISNexus2::findSpectraDetRangeInFile (const Nexus::NXEntry & entry, std::vector< specnum_t > & spectrum_index, int64_t ndets, int64_t n_vms_compat_spectra, const std::map< specnum_t, std::string > & monitors, bool excludeMonitors, bool separateMonitors) private
Method takes input parameters which describe monitor loading and analyze them against spectra/monitor block information in the file.
The result is the option if monitors can be loaded together with spectra or mast be treated separately and additional information on how to treat monitor spectra.
Parameters
entry :: entry to the NeXus file, opened at root folder
spectrum_index :: array of spectra indexes of the data present in the file
ndets :: size of the spectrum index array
n_vms_compat_spectra :: number of data entries containing common time bins (e.g. all spectra, or all spectra and monitors or some spectra (this is not fully supported)
monitors :: map connecting monitor spectra ID against monitor group name in the file.
excludeMonitors :: input property indicating if it is requested to exclude monitors from the target workspace
separateMonitors :: input property indicating if it is requested to load monitors separately (and exclude them from target data workspace this way)
Returns
excludeMonitors :: indicator if monitors should or must be excluded from the main data workspace if they can not be loaded with the data (contain different number of time channels)
Definition at line 942 of file LoadISISNexus2.cpp.
References Mantid::DataHandling::DataBlockComposite::addDataBlock(), Mantid::Nexus::NXDataSet::dim0(), Mantid::Nexus::NXDataSet::dim2(), Mantid::API::Algorithm::g_log, Mantid::DataHandling::DataBlockComposite::getAllSpectrumNumbers(), Mantid::DataHandling::DataBlockComposite::getMaxSpectrumID(), Mantid::DataHandling::DataBlockComposite::getMinSpectrumID(), Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::DataHandling::DataBlockComposite::getNumberOfPeriods(), Mantid::DataHandling::DataBlockComposite::getNumberOfSpectra(), isMultipleTimeRegimeFile(), m_detBlockInfo, m_loadBlockInfo, m_monBlockInfo, m_monitors, Mantid::Nexus::NXData::openIntData(), Mantid::Nexus::NXEntry::openNXData(), Mantid::Nexus::NXClass::openNXInt(), Mantid::DataHandling::populateDataBlockCompositeWithContainer(), Mantid::DataHandling::DataBlockComposite::removeSpectra(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
init()
void Mantid::DataHandling::LoadISISNexus2::init () override private virtual
Overwrites Algorithm method.
Initialization method.
Implements Mantid::API::Algorithm.
Definition at line 91 of file LoadISISNexus2.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
isMultipleTimeRegimeFile()
bool Mantid::DataHandling::LoadISISNexus2::isMultipleTimeRegimeFile (const Nexus::NXEntry & entry) const private
Check if is the file is a multiple time regime file.
Determine if a file is a multiple time regime file.
Note that for a true multi-time regime file we need at least three time regime entries, since two time regimes are handled by vms_compat.
Parameters
entry a handle to the Nexus file
Returns
if the file has multiple time regimes or not
Definition at line 1058 of file LoadISISNexus2.cpp.
References Mantid::Nexus::NXClass::containsGroup(), and Mantid::Nexus::NXClass::openNXGroup().
Referenced by findSpectraDetRangeInFile().
loadBlock()
void Mantid::DataHandling::LoadISISNexus2::loadBlock (Nexus::NXInt & data, int64_t blocksize, int64_t period, int64_t start, int64_t & hist, int64_t & spec_num, DataObjects::Workspace2D_sptr & local_workspace) private
Perform a call to nxgetslab, via the NexusClasses wrapped methods for a given block-size.
Parameters
data :: The NXDataSet object
blocksize :: The block-size to use
period :: The period number
start :: The index within the file to start reading from (zero based)
hist :: The workspace index to start reading into
spec_num :: The spectrum number that matches the hist variable
local_workspace :: The workspace to fill the data with
Definition at line 788 of file LoadISISNexus2.cpp.
References Mantid::API::SpectrumDetectorMapping::getDetectorIDsForSpectrumNo(), Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_detBlockInfo, m_load_selected_spectra, m_loadBlockInfo, m_progress, m_spec2det_map, m_tof_data, and m_wsInd2specNum_map.
Referenced by loadPeriodData().
loadLogs()
void Mantid::DataHandling::LoadISISNexus2::loadLogs (DataObjects::Workspace2D_sptr & ws) private
Load log data from the nexus file.
Load logs from Nexus file.
Logs are expected to be in /raw_data_1/runlog group of the file. Call to this method must be done within /raw_data_1 group.
Parameters
ws :: The workspace to load the logs to.
Definition at line 896 of file LoadISISNexus2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), m_logCreator, and Mantid::Kernel::Logger::warning().
Referenced by exec().
loadPeriodData()
void Mantid::DataHandling::LoadISISNexus2::loadPeriodData (int64_t period, Mantid::Nexus::NXEntry & entry, DataObjects::Workspace2D_sptr & local_workspace, bool update_spectra2det_mapping = false) private
Load a given period into the workspace.
Parameters
period :: The period number to load (starting from 1)
entry :: The opened root entry node for accessing the monitor and data nodes
local_workspace :: The workspace to place the data in
update_spectra2det_mapping :: reset spectra-detector map to the one calculated earlier. (Warning! – this map has to be calculated correctly!)
Definition at line 697 of file LoadISISNexus2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::Nexus::NXDataSet::dim0(), Mantid::API::Algorithm::g_log, Mantid::API::SpectrumDetectorMapping::getDetectorIDsForSpectrumNo(), Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Nexus::NXClass::getString(), Mantid::Nexus::NXDataSetTyped< T >::load(), loadBlock(), m_have_detector, m_monBlockInfo, m_progress, m_spec, m_spec2det_map, m_spec_end, m_spectraBlocks, m_wsInd2specNum_map, Mantid::Nexus::NXDataSet::open(), Mantid::Nexus::NXData::openIntData(), Mantid::Nexus::NXEntry::openNXData(), and Mantid::Nexus::NXClass::openNXFloat().
Referenced by exec().
loadRunDetails()
void Mantid::DataHandling::LoadISISNexus2::loadRunDetails (DataObjects::Workspace2D_sptr & local_workspace, Mantid::Nexus::NXEntry & entry) private
Load in details about the run.
Load data about the run.
Parameters
local_workspace :: The workspace to load the run information in to
entry :: The Nexus entry
Definition at line 864 of file LoadISISNexus2.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::DataHandling::DataBlockComposite::getNumberOfChannels(), Mantid::DataHandling::DataBlockComposite::getNumberOfPeriods(), Mantid::DataHandling::DataBlockComposite::getNumberOfSpectra(), Mantid::DataHandling::LoadISISNexusHelper::loadRunDetails(), m_hasVMSBlock, and m_loadBlockInfo.
Referenced by exec().
loadSampleData()
void Mantid::DataHandling::LoadISISNexus2::loadSampleData (DataObjects::Workspace2D_sptr & local_workspace, const Mantid::Nexus::NXEntry & entry) private
Load in details about the sample.
Load data about the sample.
Parameters
local_workspace :: The workspace to load the logs to.
entry :: The Nexus entry
Definition at line 881 of file LoadISISNexus2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::DataHandling::LoadISISNexusHelper::loadSampleGeometry(), and m_hasVMSBlock.
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadISISNexus2::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 64 of file LoadISISNexus2.h.
prepareSpectraBlocks()
size_t Mantid::DataHandling::LoadISISNexus2::prepareSpectraBlocks (std::map< specnum_t, std::string > & monitors, DataBlockComposite & LoadBlock) private
Prepare a vector of SpectraBlock structures to simplify loading.
Analyze the spectra ranges and prepare a list contiguous blocks.
Each monitor must be in a separate block.
Returns
:: Number of spectra to load.
Definition at line 623 of file LoadISISNexus2.cpp.
References checkOverlappingSpectraRange(), Mantid::DataHandling::DataBlockComposite::getDataBlocks(), and m_spectraBlocks.
Referenced by exec().
runLoadInstrument()
void Mantid::DataHandling::LoadISISNexus2::runLoadInstrument (DataObjects::Workspace2D_sptr & localWorkspace) private
Run LoadInstrument as a ChildAlgorithm.
Run the Child Algorithm LoadInstrument (or LoadInstrumentFromNexus)
Definition at line 814 of file LoadISISNexus2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_filename, m_instrument_name, and value.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadISISNexus2::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 67 of file LoadISISNexus2.h.
summary()
const std::string Mantid::DataHandling::LoadISISNexus2::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 71 of file LoadISISNexus2.h.
validateMultiPeriodLogs()
void Mantid::DataHandling::LoadISISNexus2::validateMultiPeriodLogs (const Mantid::API::MatrixWorkspace_sptr & ws) private
Check for a set of synthetic logs associated with multi-period log data.
Raise warnings where necessary.
Definition at line 395 of file LoadISISNexus2.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::LogManager::hasProperty(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
version()
int Mantid::DataHandling::LoadISISNexus2::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 66 of file LoadISISNexus2.h.
Member Data Documentation
m_detBlockInfo
DataBlockComposite Mantid::DataHandling::LoadISISNexus2::m_detBlockInfo private
Definition at line 133 of file LoadISISNexus2.h.
Referenced by exec(), findSpectraDetRangeInFile(), and loadBlock().
m_entrynumber
int64_t Mantid::DataHandling::LoadISISNexus2::m_entrynumber private
The number of the input entry.
Definition at line 153 of file LoadISISNexus2.h.
Referenced by checkOptionalProperties(), and exec().
m_filename
std::string Mantid::DataHandling::LoadISISNexus2::m_filename private
The name and path of the input file.
Definition at line 126 of file LoadISISNexus2.h.
Referenced by exec(), and runLoadInstrument().
m_hasVMSBlock
bool Mantid::DataHandling::LoadISISNexus2::m_hasVMSBlock private
Definition at line 145 of file LoadISISNexus2.h.
Referenced by exec(), loadRunDetails(), and loadSampleData().
m_have_detector
bool Mantid::DataHandling::LoadISISNexus2::m_have_detector private
Is there a detector block.
Definition at line 143 of file LoadISISNexus2.h.
Referenced by exec(), and loadPeriodData().
m_instrument_name
std::string Mantid::DataHandling::LoadISISNexus2::m_instrument_name private
The instrument name from Nexus.
Definition at line 128 of file LoadISISNexus2.h.
Referenced by exec(), and runLoadInstrument().
m_load_selected_spectra
bool Mantid::DataHandling::LoadISISNexus2::m_load_selected_spectra private
if true, a spectra list or range of spectra is supplied
Definition at line 147 of file LoadISISNexus2.h.
Referenced by checkOptionalProperties(), exec(), and loadBlock().
m_loadBlockInfo
DataBlockComposite Mantid::DataHandling::LoadISISNexus2::m_loadBlockInfo private
Definition at line 141 of file LoadISISNexus2.h.
Referenced by checkOptionalProperties(), exec(), findSpectraDetRangeInFile(), loadBlock(), and loadRunDetails().
m_logCreator
boost::scoped_ptr<API::ISISRunLogs> Mantid::DataHandling::LoadISISNexus2::m_logCreator private
A pointer to the ISISRunLogs creator.
Definition at line 165 of file LoadISISNexus2.h.
Referenced by createPeriodLogs(), and loadLogs().
m_monBlockInfo
DataBlockComposite Mantid::DataHandling::LoadISISNexus2::m_monBlockInfo private
Definition at line 135 of file LoadISISNexus2.h.
Referenced by checkOptionalProperties(), exec(), findSpectraDetRangeInFile(), and loadPeriodData().
m_monitors
std::map<specnum_t, std::string> Mantid::DataHandling::LoadISISNexus2::m_monitors private
Monitors, map spectrum index to monitor group name.
Definition at line 163 of file LoadISISNexus2.h.
Referenced by exec(), and findSpectraDetRangeInFile().
m_nexusFile
boost::scoped_ptr<Nexus::File> Mantid::DataHandling::LoadISISNexus2::m_nexusFile private
Definition at line 171 of file LoadISISNexus2.h.
Referenced by exec().
m_progress
std::shared_ptr<API::Progress> Mantid::DataHandling::LoadISISNexus2::m_progress private
Progress reporting object.
Definition at line 167 of file LoadISISNexus2.h.
Referenced by exec(), loadBlock(), and loadPeriodData().
m_samplename
std::string Mantid::DataHandling::LoadISISNexus2::m_samplename private
The sample name read from Nexus.
Definition at line 130 of file LoadISISNexus2.h.
m_spec
std::vector<specnum_t> Mantid::DataHandling::LoadISISNexus2::m_spec private
Spectra numbers.
Definition at line 159 of file LoadISISNexus2.h.
Referenced by exec(), and loadPeriodData().
m_spec2det_map
API::SpectrumDetectorMapping Mantid::DataHandling::LoadISISNexus2::m_spec2det_map private
spectra Number to detector ID (multi)map
Definition at line 151 of file LoadISISNexus2.h.
Referenced by exec(), loadBlock(), and loadPeriodData().
m_spec_end
const specnum_t* Mantid::DataHandling::LoadISISNexus2::m_spec_end private
Pointer to one-past-the-end of spectrum number array (m_spec)
Definition at line 161 of file LoadISISNexus2.h.
Referenced by exec(), and loadPeriodData().
m_spectraBlocks
std::vector<SpectraBlock> Mantid::DataHandling::LoadISISNexus2::m_spectraBlocks private
List of disjoint data blocks to load.
Definition at line 155 of file LoadISISNexus2.h.
Referenced by checkOverlappingSpectraRange(), exec(), loadPeriodData(), and prepareSpectraBlocks().
m_tof_data
std::shared_ptr<HistogramData::HistogramX> Mantid::DataHandling::LoadISISNexus2::m_tof_data private
Time channels.
Definition at line 157 of file LoadISISNexus2.h.
Referenced by exec(), and loadBlock().
m_wsInd2specNum_map
std::map<int64_t, specnum_t> Mantid::DataHandling::LoadISISNexus2::m_wsInd2specNum_map private
map of workspace Index to spectra Number (spectraID)
Definition at line 149 of file LoadISISNexus2.h.
Referenced by buildSpectraInd2SpectraNumMap(), exec(), loadBlock(), and loadPeriodData().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
Framework/DataHandling/src/LoadISISNexus2.cpp