Mantid: MantidQt::MantidWidgets::WorkspacePresenter Class Reference
MantidQt::MantidWidgets::WorkspacePresenter Class Reference
Presenter class for Workspace dock in MantidPlot UI.
#include <WorkspacePresenter.h>
Public Member Functions
void init ()
Initialises the view weak pointer for the Workspace Provider.
void notifyFromView (ViewNotifiable::Flag flag) override
Handle notifications from the view.
void notifyFromWorkspaceProvider (WorkspaceProviderNotifiable::Flag flag) override
Handle WorkspaceProvider (ADS) notifications.
WorkspacePresenter (IWorkspaceDockView *view)
~WorkspacePresenter () override
Public Member Functions inherited from MantidQt::MantidWidgets::WorkspaceProviderNotifiable
virtual void notifyFromWorkspaceProvider (Flag flag)=0
virtual ~WorkspaceProviderNotifiable ()=default
Public Member Functions inherited from MantidQt::MantidWidgets::ViewNotifiable
virtual void notifyFromView (Flag flag)=0
virtual ~ViewNotifiable ()=default
Private Member Functions
void clearUBMatrix ()
void clearWorkspaces ()
void convertMDHistoToMatrixWorkspace ()
void convertToMatrixWorkspace ()
void deleteWorkspaces ()
void filterWorkspaces ()
void groupWorkspaces ()
void loadLiveData ()
void loadWorkspace ()
void plotSpectrum ()
void plotSpectrumAdvanced ()
void plotSpectrumWithErrors ()
void populateAndShowWorkspaceContextMenu ()
void refreshWorkspaces ()
void renameWorkspace ()
void saveSingleWorkspace ()
void saveToProgram ()
void saveWorkspaceCollection ()
void showAlgorithmHistory ()
void showBoxDataTable ()
void showColourFillPlot ()
void showDetectorsTable ()
void showInstrumentView ()
void showListData ()
void showLogs ()
void showMDPlot ()
void showSampleMaterialWindow ()
void showSliceViewer ()
void showSpectrumViewer ()
void showTransposed ()
void showWorkspaceData ()
void sortWorkspaces ()
void ungroupWorkspaces ()
void updateView ()
Update the view by publishing the ADS contents.
void workspaceGroupUpdated ()
void workspaceLoaded ()
void workspaceRenamed ()
void workspacesCleared ()
void workspacesDeleted ()
void workspacesGrouped ()
void workspacesUngrouped ()
Private Attributes
ADSAdapter_uptr m_adapter
IWorkspaceDockView * m_view
Additional Inherited Members
Public Types inherited from MantidQt::MantidWidgets::WorkspaceProviderNotifiable
enum class Flag {
WorkspaceLoaded , WorkspaceRenamed , WorkspaceDeleted , WorkspacesCleared ,
WorkspacesGrouped , WorkspacesUngrouped , WorkspaceGroupUpdated , GenericUpdateNotification
}
Public Types inherited from MantidQt::MantidWidgets::ViewNotifiable
enum class Flag {
LoadWorkspace , LoadLiveDataWorkspace , RenameWorkspace , DeleteWorkspaces ,
ClearWorkspaces , GroupWorkspaces , UngroupWorkspaces , SortWorkspaces ,
SaveSingleWorkspace , SaveWorkspaceCollection , FilterWorkspaces , PopulateAndShowWorkspaceContextMenu ,
SaveToProgram , ShowWorkspaceData , ShowInstrumentView , PlotSpectrum ,
PlotSpectrumWithErrors , PlotSpectrumAdvanced , ShowColourFillPlot , ShowDetectorsTable ,
ShowBoxDataTable , ShowMDPlot , ShowListData , ShowSpectrumViewer ,
ShowSliceViewer , ShowLogs , ShowSampleMaterialWindow , ShowAlgorithmHistory ,
ShowTransposed , ConvertToMatrixWorkspace , ConvertMDHistoToMatrixWorkspace , ClearUBMatrix ,
RefreshWorkspaces
}
Detailed Description
Presenter class for Workspace dock in MantidPlot UI.
Author
Lamar Moore
Date
24-08-2016
Version
1.0
Definition at line 29 of file WorkspacePresenter.h.
Constructor & Destructor Documentation
WorkspacePresenter()
MantidQt::MantidWidgets::WorkspacePresenter::WorkspacePresenter (IWorkspaceDockView * view) explicit
Definition at line 18 of file WorkspacePresenter.cpp.
~WorkspacePresenter()
MantidQt::MantidWidgets::WorkspacePresenter::~WorkspacePresenter () override default
References Mantid::API::renameWorkspace().
Member Function Documentation
clearUBMatrix()
void MantidQt::MantidWidgets::WorkspacePresenter::clearUBMatrix () private
Definition at line 303 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::executeAlgorithmAsync(), MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), Mantid::Kernel::SingletonHolder< T >::Instance(), and m_view.
Referenced by notifyFromView().
clearWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::clearWorkspaces () private
Definition at line 248 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::clearWorkspacesConfirmation(), MantidQt::MantidWidgets::IWorkspaceDockView::enableClearButton(), Mantid::Kernel::SingletonHolder< T >::Instance(), and m_view.
Referenced by notifyFromView().
convertMDHistoToMatrixWorkspace()
void MantidQt::MantidWidgets::WorkspacePresenter::convertMDHistoToMatrixWorkspace () private
Definition at line 301 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::convertMDHistoToMatrixWorkspace(), and m_view.
Referenced by notifyFromView().
convertToMatrixWorkspace()
void MantidQt::MantidWidgets::WorkspacePresenter::convertToMatrixWorkspace () private
Definition at line 299 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::convertToMatrixWorkspace(), and m_view.
Referenced by notifyFromView().
deleteWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces () private
Definition at line 229 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::deleteConfirmation(), MantidQt::MantidWidgets::IWorkspaceDockView::deleteWorkspaces(), MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), MantidQt::MantidWidgets::IWorkspaceDockView::isPromptDelete(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showCriticalUserMessage().
Referenced by notifyFromView().
filterWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::filterWorkspaces () private
Definition at line 261 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::filterWorkspaces(), MantidQt::MantidWidgets::IWorkspaceDockView::getFilterText(), and m_view.
Referenced by notifyFromView().
groupWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::groupWorkspaces () private
Definition at line 167 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::askUserYesNo(), MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_adapter, m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showCriticalUserMessage().
Referenced by notifyFromView().
init()
void MantidQt::MantidWidgets::WorkspacePresenter::init ()
Initialises the view weak pointer for the Workspace Provider.
Definition at line 24 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getPresenterWeakPtr(), m_adapter, and m_view.
loadLiveData()
void MantidQt::MantidWidgets::WorkspacePresenter::loadLiveData () private
Definition at line 163 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showLiveDataDialog().
Referenced by notifyFromView().
loadWorkspace()
void MantidQt::MantidWidgets::WorkspacePresenter::loadWorkspace () private
Definition at line 161 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showLoadDialog().
Referenced by notifyFromView().
notifyFromView()
void MantidQt::MantidWidgets::WorkspacePresenter::notifyFromView (ViewNotifiable::Flag flag) override virtual
Handle notifications from the view.
Implements MantidQt::MantidWidgets::ViewNotifiable.
Definition at line 57 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::ClearUBMatrix, clearUBMatrix(), MantidQt::MantidWidgets::ViewNotifiable::ClearWorkspaces, clearWorkspaces(), MantidQt::MantidWidgets::ViewNotifiable::ConvertMDHistoToMatrixWorkspace, convertMDHistoToMatrixWorkspace(), MantidQt::MantidWidgets::ViewNotifiable::ConvertToMatrixWorkspace, convertToMatrixWorkspace(), MantidQt::MantidWidgets::ViewNotifiable::DeleteWorkspaces, deleteWorkspaces(), MantidQt::MantidWidgets::ViewNotifiable::FilterWorkspaces, filterWorkspaces(), MantidQt::MantidWidgets::ViewNotifiable::GroupWorkspaces, groupWorkspaces(), loadLiveData(), MantidQt::MantidWidgets::ViewNotifiable::LoadLiveDataWorkspace, MantidQt::MantidWidgets::ViewNotifiable::LoadWorkspace, loadWorkspace(), MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrum, plotSpectrum(), MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrumAdvanced, plotSpectrumAdvanced(), MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrumWithErrors, plotSpectrumWithErrors(), MantidQt::MantidWidgets::ViewNotifiable::PopulateAndShowWorkspaceContextMenu, populateAndShowWorkspaceContextMenu(), MantidQt::MantidWidgets::ViewNotifiable::RefreshWorkspaces, refreshWorkspaces(), MantidQt::MantidWidgets::ViewNotifiable::RenameWorkspace, renameWorkspace(), MantidQt::MantidWidgets::ViewNotifiable::SaveSingleWorkspace, saveSingleWorkspace(), MantidQt::MantidWidgets::ViewNotifiable::SaveToProgram, saveToProgram(), MantidQt::MantidWidgets::ViewNotifiable::SaveWorkspaceCollection, saveWorkspaceCollection(), MantidQt::MantidWidgets::ViewNotifiable::ShowAlgorithmHistory, showAlgorithmHistory(), MantidQt::MantidWidgets::ViewNotifiable::ShowBoxDataTable, showBoxDataTable(), MantidQt::MantidWidgets::ViewNotifiable::ShowColourFillPlot, showColourFillPlot(), MantidQt::MantidWidgets::ViewNotifiable::ShowDetectorsTable, showDetectorsTable(), MantidQt::MantidWidgets::ViewNotifiable::ShowInstrumentView, showInstrumentView(), MantidQt::MantidWidgets::ViewNotifiable::ShowListData, showListData(), MantidQt::MantidWidgets::ViewNotifiable::ShowLogs, showLogs(), MantidQt::MantidWidgets::ViewNotifiable::ShowMDPlot, showMDPlot(), MantidQt::MantidWidgets::ViewNotifiable::ShowSampleMaterialWindow, showSampleMaterialWindow(), MantidQt::MantidWidgets::ViewNotifiable::ShowSliceViewer, showSliceViewer(), MantidQt::MantidWidgets::ViewNotifiable::ShowSpectrumViewer, showSpectrumViewer(), MantidQt::MantidWidgets::ViewNotifiable::ShowTransposed, showTransposed(), MantidQt::MantidWidgets::ViewNotifiable::ShowWorkspaceData, showWorkspaceData(), MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces, sortWorkspaces(), MantidQt::MantidWidgets::ViewNotifiable::UngroupWorkspaces, and ungroupWorkspaces().
notifyFromWorkspaceProvider()
void MantidQt::MantidWidgets::WorkspacePresenter::notifyFromWorkspaceProvider (WorkspaceProviderNotifiable::Flag flag) override virtual
Handle WorkspaceProvider (ADS) notifications.
Implements MantidQt::MantidWidgets::WorkspaceProviderNotifiable.
Definition at line 27 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::WorkspaceProviderNotifiable::GenericUpdateNotification, updateView(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceDeleted, workspaceGroupUpdated(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceGroupUpdated, workspaceLoaded(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceLoaded, workspaceRenamed(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceRenamed, workspacesCleared(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesCleared, workspacesDeleted(), workspacesGrouped(), MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesGrouped, workspacesUngrouped(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesUngrouped.
plotSpectrum()
void MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrum () private
Definition at line 271 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::plotSpectrum().
Referenced by notifyFromView().
plotSpectrumAdvanced()
void MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrumAdvanced () private
Definition at line 275 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::plotSpectrum().
Referenced by notifyFromView().
plotSpectrumWithErrors()
void MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrumWithErrors () private
Definition at line 273 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::plotSpectrum().
Referenced by notifyFromView().
populateAndShowWorkspaceContextMenu()
void MantidQt::MantidWidgets::WorkspacePresenter::populateAndShowWorkspaceContextMenu () private
Definition at line 263 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::popupContextMenu().
Referenced by notifyFromView().
refreshWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::refreshWorkspaces () private
Definition at line 319 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromView().
renameWorkspace()
void MantidQt::MantidWidgets::WorkspacePresenter::renameWorkspace () private
Definition at line 165 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showRenameDialog().
Referenced by notifyFromView().
saveSingleWorkspace()
void MantidQt::MantidWidgets::WorkspacePresenter::saveSingleWorkspace () private
Definition at line 255 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getSaveFileType(), MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspace(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::saveWorkspace().
Referenced by notifyFromView().
saveToProgram()
void MantidQt::MantidWidgets::WorkspacePresenter::saveToProgram () private
Definition at line 269 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::saveToProgram().
Referenced by notifyFromView().
saveWorkspaceCollection()
void MantidQt::MantidWidgets::WorkspacePresenter::saveWorkspaceCollection () private
Definition at line 259 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::saveWorkspaces().
Referenced by notifyFromView().
showAlgorithmHistory()
void MantidQt::MantidWidgets::WorkspacePresenter::showAlgorithmHistory () private
Definition at line 295 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showAlgorithmHistory().
Referenced by notifyFromView().
showBoxDataTable()
void MantidQt::MantidWidgets::WorkspacePresenter::showBoxDataTable () private
Definition at line 281 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showBoxDataTable().
Referenced by notifyFromView().
showColourFillPlot()
void MantidQt::MantidWidgets::WorkspacePresenter::showColourFillPlot () private
Definition at line 277 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showColourFillPlot().
Referenced by notifyFromView().
showDetectorsTable()
void MantidQt::MantidWidgets::WorkspacePresenter::showDetectorsTable () private
Definition at line 279 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showDetectorsTable().
Referenced by notifyFromView().
showInstrumentView()
void MantidQt::MantidWidgets::WorkspacePresenter::showInstrumentView () private
Definition at line 267 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showInstrumentView().
Referenced by notifyFromView().
showListData()
void MantidQt::MantidWidgets::WorkspacePresenter::showListData () private
Definition at line 285 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showListData().
Referenced by notifyFromView().
showLogs()
void MantidQt::MantidWidgets::WorkspacePresenter::showLogs () private
Definition at line 291 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showLogs().
Referenced by notifyFromView().
showMDPlot()
void MantidQt::MantidWidgets::WorkspacePresenter::showMDPlot () private
Definition at line 283 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showMDPlot().
Referenced by notifyFromView().
showSampleMaterialWindow()
void MantidQt::MantidWidgets::WorkspacePresenter::showSampleMaterialWindow () private
Definition at line 293 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showSampleMaterialWindow().
Referenced by notifyFromView().
showSliceViewer()
void MantidQt::MantidWidgets::WorkspacePresenter::showSliceViewer () private
Definition at line 289 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showSliceViewer().
Referenced by notifyFromView().
showSpectrumViewer()
void MantidQt::MantidWidgets::WorkspacePresenter::showSpectrumViewer () private
Definition at line 287 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showSpectrumViewer().
Referenced by notifyFromView().
showTransposed()
void MantidQt::MantidWidgets::WorkspacePresenter::showTransposed () private
Definition at line 297 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showTransposed().
Referenced by notifyFromView().
showWorkspaceData()
void MantidQt::MantidWidgets::WorkspacePresenter::showWorkspaceData () private
Definition at line 265 of file WorkspacePresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showWorkspaceData().
Referenced by notifyFromView().
sortWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::sortWorkspaces () private
Definition at line 225 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getSortCriteria(), MantidQt::MantidWidgets::IWorkspaceDockView::getSortDirection(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::sortWorkspaces().
Referenced by notifyFromView().
ungroupWorkspaces()
void MantidQt::MantidWidgets::WorkspacePresenter::ungroupWorkspaces () private
Definition at line 198 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::showCriticalUserMessage().
Referenced by notifyFromView().
updateView()
void MantidQt::MantidWidgets::WorkspacePresenter::updateView () private
Update the view by publishing the ADS contents.
Definition at line 337 of file WorkspacePresenter.cpp.
References m_adapter, m_view, and MantidQt::MantidWidgets::IWorkspaceDockView::updateTree().
Referenced by notifyFromWorkspaceProvider(), refreshWorkspaces(), workspaceGroupUpdated(), workspaceLoaded(), workspacesDeleted(), workspacesGrouped(), and workspacesUngrouped().
workspaceGroupUpdated()
void MantidQt::MantidWidgets::WorkspacePresenter::workspaceGroupUpdated () private
Definition at line 330 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromWorkspaceProvider().
workspaceLoaded()
void MantidQt::MantidWidgets::WorkspacePresenter::workspaceLoaded () private
Definition at line 321 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromWorkspaceProvider().
workspaceRenamed()
void MantidQt::MantidWidgets::WorkspacePresenter::workspaceRenamed () private
Definition at line 323 of file WorkspacePresenter.cpp.
References m_adapter, m_view, MantidQt::MantidWidgets::IWorkspaceDockView::recordWorkspaceRename(), and MantidQt::MantidWidgets::IWorkspaceDockView::updateTree().
Referenced by notifyFromWorkspaceProvider().
workspacesCleared()
void MantidQt::MantidWidgets::WorkspacePresenter::workspacesCleared () private
Definition at line 334 of file WorkspacePresenter.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::clearView(), and m_view.
Referenced by notifyFromWorkspaceProvider().
workspacesDeleted()
void MantidQt::MantidWidgets::WorkspacePresenter::workspacesDeleted () private
Definition at line 332 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromWorkspaceProvider().
workspacesGrouped()
void MantidQt::MantidWidgets::WorkspacePresenter::workspacesGrouped () private
Definition at line 328 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromWorkspaceProvider().
workspacesUngrouped()
void MantidQt::MantidWidgets::WorkspacePresenter::workspacesUngrouped () private
Definition at line 329 of file WorkspacePresenter.cpp.
References updateView().
Referenced by notifyFromWorkspaceProvider().
Member Data Documentation
m_adapter
ADSAdapter_uptr MantidQt::MantidWidgets::WorkspacePresenter::m_adapter private
Definition at line 87 of file WorkspacePresenter.h.
Referenced by groupWorkspaces(), init(), updateView(), and workspaceRenamed().
m_view
IWorkspaceDockView* MantidQt::MantidWidgets::WorkspacePresenter::m_view private
Definition at line 86 of file WorkspacePresenter.h.
Referenced by clearUBMatrix(), clearWorkspaces(), convertMDHistoToMatrixWorkspace(), convertToMatrixWorkspace(), deleteWorkspaces(), filterWorkspaces(), groupWorkspaces(), init(), loadLiveData(), loadWorkspace(), plotSpectrum(), plotSpectrumAdvanced(), plotSpectrumWithErrors(), populateAndShowWorkspaceContextMenu(), renameWorkspace(), saveSingleWorkspace(), saveToProgram(), saveWorkspaceCollection(), showAlgorithmHistory(), showBoxDataTable(), showColourFillPlot(), showDetectorsTable(), showInstrumentView(), showListData(), showLogs(), showMDPlot(), showSampleMaterialWindow(), showSliceViewer(), showSpectrumViewer(), showTransposed(), showWorkspaceData(), sortWorkspaces(), ungroupWorkspaces(), updateView(), workspaceRenamed(), and workspacesCleared().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspacePresenter.h
qt/widgets/common/src/WorkspacePresenter/WorkspacePresenter.cpp