Mantid: Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy Class Reference
Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy Class Reference
#include <FindSXPeaksHelper.h>
Public Member Functions
FindMaxReduceStrategy (const CompareStrategy *compareStrategy)
std::vector< SXPeak > reduce (const std::vector< SXPeak > &peaks, Mantid::Kernel::ProgressBase &progress) const override
Public Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy
ReducePeakListStrategy (const CompareStrategy *compareStrategy)
void setMaxNSpectraPerPeak (int maxSpectrasForPeak)
void setMinNSpectraPerPeak (int minSpectrasForPeak)
virtual ~ReducePeakListStrategy ()=default
Private Member Functions
std::vector< SXPeak > getFinalPeaks (const std::vector< std::vector< SXPeak * > > &peakGroups) const
std::vector< std::vector< SXPeak * > > getPeakGroups (const std::vector< SXPeak > &peakList, Mantid::Kernel::ProgressBase &progress) const
Additional Inherited Members
Protected Attributes inherited from Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy
const CompareStrategy * m_compareStrategy
int m_maxNSpectraPerPeak = EMPTY_INT()
int m_minNSpectraPerPeak = EMPTY_INT()
Detailed Description
Definition at line 289 of file FindSXPeaksHelper.h.
Constructor & Destructor Documentation
FindMaxReduceStrategy()
Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::FindMaxReduceStrategy (const CompareStrategy * compareStrategy)
Definition at line 685 of file FindSXPeaksHelper.cpp.
Member Function Documentation
getFinalPeaks()
std::vector< SXPeak > Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getFinalPeaks (const std::vector< std::vector< SXPeak * > > & peakGroups) const private
Definition at line 788 of file FindSXPeaksHelper.cpp.
References Mantid::EMPTY_INT(), group, Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_maxNSpectraPerPeak, and Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_minNSpectraPerPeak.
Referenced by reduce().
getPeakGroups()
std::vector< std::vector< SXPeak * > > Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getPeakGroups (const std::vector< SXPeak > & peakList, Mantid::Kernel::ProgressBase & progress) const private
Definition at line 707 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::CompareStrategy::compare(), Mantid::Kernel::ProgressBase::doReport(), Mantid::Crystal::FindSXPeaksHelper::g_log, Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_compareStrategy, std::to_string(), and Mantid::Kernel::Logger::warning().
Referenced by reduce().
reduce()
std::vector< SXPeak > Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::reduce (const std::vector< SXPeak > & peaks, Mantid::Kernel::ProgressBase & progress) const override virtual
Implements Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy.
Definition at line 688 of file FindSXPeaksHelper.cpp.
References getFinalPeaks(), and getPeakGroups().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
Framework/Crystal/src/FindSXPeaksHelper.cpp