Mantid: Mantid::DataObjects::MDEvent< nd > Class Template Reference
Mantid::DataObjects::MDEvent< nd > Class Template Reference
Templated class holding data about a neutron detection event in N-dimensions (for example, Qx, Qy, Qz, E).
#include <MDEvent.h>
Public Types
enum { is_full_mdevent = true }
Public Types inherited from Mantid::DataObjects::MDLeanEvent< nd >
enum { is_full_mdevent = false }
using IntT = typename morton_index::IndexTypes< nd, coord_t >::IntType
Additional index type defenitions.
using MortonT = typename morton_index::IndexTypes< nd, coord_t >::MortonType
Public Member Functions
int32_t getDetectorID () const
uint16_t getExpInfoIndex () const
uint16_t getGoniometerIndex () const
MDEvent ()
Empty constructor.
MDEvent (const double signal, const double errorSquared)
Constructor with signal and error.
MDEvent (const double signal, const double errorSquared, const coord_t *centers)
Constructor with signal and error and an array of centers.
MDEvent (const double signal, const double errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId)
Constructor with signal, error, expInfoIndex and detectorId.
MDEvent (const double signal, const double errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId, const coord_t *centers)
MDEvent (const float signal, const float errorSquared)
Constructor with signal and error.
MDEvent (const float signal, const float errorSquared, const coord_t *centers)
Constructor with signal and error and an array of centers.
MDEvent (const float signal, const float errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId)
Constructor with signal, error, expInfoIndex and detectorId.
MDEvent (const float signal, const float errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId, const coord_t *centers)
Constructor with signal and error and an array of centers, and the expInfoIndex and detectorID.
void setDetectorId (int32_t id)
Sets the detectorId of this event.
void setExpInfoIndex (uint16_t index)
Sets the expInfoIndex of this event.
void setGoniometerIndex (uint16_t index)
Sets the expInfoIndex of this event.
Public Member Functions inherited from Mantid::DataObjects::MDLeanEvent< nd >
const coord_t * getCenter () const
Returns the array of coordinates.
coord_t getCenter (const size_t n) const
coord_t * getCenterNonConst ()
Returns the array of coordinates, as a pointer to a non-const array.
int32_t getDetectorID () const
float getError () const
Returns the error (not squared) of this event.
float getErrorSquared () const
Returns the error (squared) of this event.
uint16_t getExpInfoIndex () const
uint16_t getGoniometerIndex () const
size_t getNumDims () const
Returns the number of dimensions in the event.
float getSignal () const
Returns the signal (weight) of this event.
MDLeanEvent ()
Empty constructor.
MDLeanEvent (const double signal, const double errorSquared)
Constructor with signal and error.
MDLeanEvent (const double signal, const double errorSquared, const coord_t *centers)
Constructor with signal and error and an array of centers.
MDLeanEvent (const float signal, const float errorSquared)
Constructor with signal and error.
MDLeanEvent (const float signal, const float errorSquared, const coord_t *centers)
Constructor with signal and error and an array of centers.
MDLeanEvent (const MDLeanEvent &rhs)
Copy constructor.
MDLeanEvent & operator= (MDLeanEvent other)
void setCenter (const size_t n, const coord_t value)
Sets the n-th coordinate axis value.
void setCoords (const coord_t *centers)
Sets all the coordinates.
void setErrorSquared (const float newerrorSquared)
Set the squared error of the event.
void setSignal (const float newSignal)
Set the signal of the event.
Static Public Member Functions
static void dataToEvents (const std::vector< coord_t > &data, std::vector< MDEvent< nd > > &events, bool reserveMemory=true)
static void eventsToData (const std::vector< MDEvent< nd > > &events, std::vector< coord_t > &data, size_t &ncols, double &totalSignal, double &totalErrSq)
static std::string getTypeName ()
Static Public Member Functions inherited from Mantid::DataObjects::MDLeanEvent< nd >
static void dataToEvents (const std::vector< coord_t > &coord, std::vector< MDLeanEvent< nd > > &events, bool reserveMemory=true)
static void eventsToData (const std::vector< MDLeanEvent< nd > > &mdLeanEvents, std::vector< coord_t > &data, size_t &ncols, double &totalSignal, double &totalErrSq)
static std::string getTypeName ()
Protected Attributes
int32_t detectorId
Detector ID of the pixel that measured this event.
uint16_t expInfoIndex
0-based index of which run this event belongs to.
uint16_t goniometerIndex
0-based index determines the goniometer settings when this event occurred
Protected Attributes inherited from Mantid::DataObjects::MDLeanEvent< nd >
union {
coord_t center [nd]
MortonT index = 0
};
The N-dimensional coordinates of the center of the event.
float errorSquared
The square of the error carried in this event.
float signal
The signal (aka weight) from the neutron event.
Detailed Description
template<size_t nd>
class Mantid::DataObjects::MDEvent< nd >
Templated class holding data about a neutron detection event in N-dimensions (for example, Qx, Qy, Qz, E).
This is an extension to MDLeanEvent which adds:
16-bit int for the expInfoIndex (index into the vector of ExperimentInfo of the workspace)
16-bit int for the goniometer index (0-based index determines the goniometer settings when the event occurred)
32-bit int for the detector_id.
Template Parameters
nd :: the number of dimensions that each MDEvent will be tracking. an int > 0.
Author
Janik Zikovsky, SNS
Date
Dec 3, 2010
Definition at line 36 of file MDEvent.h.
Member Enumeration Documentation
anonymous enum
template<size_t nd> anonymous enum
Enumerator
is_full_mdevent
Definition at line 52 of file MDEvent.h.
Constructor & Destructor Documentation
MDEvent() [1/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent () inline
Empty constructor.
Definition at line 56 of file MDEvent.h.
MDEvent() [2/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const float signal, const float errorSquared) inline
Constructor with signal and error.
Parameters
signal :: signal
errorSquared :: square of the error on the weight
Definition at line 64 of file MDEvent.h.
MDEvent() [3/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const double signal, const double errorSquared) inline
Constructor with signal and error.
Parameters
signal :: signal
errorSquared :: square of the error on the weight
Definition at line 73 of file MDEvent.h.
MDEvent() [4/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const double signal, const double errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId) inline
Constructor with signal, error, expInfoIndex and detectorId.
Parameters
signal :: signal (aka weight)
errorSquared :: square of the error on the weight
expInfoIndex :: 0-based index of which run in the containing MDEventWorkspace
goniometerIndex :: 0-based index determines the goniometer settings when this event occurred
detectorId :: ID of the detector that measured this event.
Definition at line 87 of file MDEvent.h.
MDEvent() [5/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const float signal, const float errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId) inline
Constructor with signal, error, expInfoIndex and detectorId.
Parameters
signal :: signal (aka weight)
errorSquared :: square of the error on the weight
expInfoIndex :: 0-based index of which run in the containing MDEventWorkspace
goniometerIndex :: 0-based index determines the goniometer settings when this event occurred
detectorId :: ID of the detector that measured this event.
Definition at line 103 of file MDEvent.h.
MDEvent() [6/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const float signal, const float errorSquared, const coord_t * centers) inline
Constructor with signal and error and an array of centers.
Parameters
signal :: signal (aka weight)
errorSquared :: square of the error on the weight
centers :: pointer to a nd-sized array of values to set for all coordinates.
Definition at line 116 of file MDEvent.h.
MDEvent() [7/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const double signal, const double errorSquared, const coord_t * centers) inline
Constructor with signal and error and an array of centers.
Parameters
signal :: signal (aka weight)
errorSquared :: square of the error on the weight
centers :: pointer to a nd-sized array of values to set for all coordinates.
Definition at line 126 of file MDEvent.h.
MDEvent() [8/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const float signal, const float errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId, const coord_t * centers) inline
Constructor with signal and error and an array of centers, and the expInfoIndex and detectorID.
Parameters
signal :: signal (aka weight)
errorSquared :: square of the error on the weight
expInfoIndex :: 0-based index of which run in the containing MDEventWorkspace
goniometerIndex :: 0-based index determines the goniometer settings when this event occurred
detectorId :: ID of the detector that measured this event.
centers :: pointer to a nd-sized array of values to set for all coordinates.
Definition at line 142 of file MDEvent.h.
MDEvent() [9/9]
template<size_t nd> Mantid::DataObjects::MDEvent< nd >::MDEvent (const double signal, const double errorSquared, const uint16_t expInfoIndex, const uint16_t goniometerIndex, const int32_t detectorId, const coord_t * centers) inline
Definition at line 147 of file MDEvent.h.
Member Function Documentation
dataToEvents()
template<size_t nd> static void Mantid::DataObjects::MDEvent< nd >::dataToEvents (const std::vector< coord_t > & data, std::vector< MDEvent< nd > > & events, bool reserveMemory = true) inline static
Definition at line 244 of file MDEvent.h.
References Mantid::DataHandling::numEvents().
eventsToData()
template<size_t nd> static void Mantid::DataObjects::MDEvent< nd >::eventsToData (const std::vector< MDEvent< nd > > & events, std::vector< coord_t > & data, size_t & ncols, double & totalSignal, double & totalErrSq) inline static
Definition at line 211 of file MDEvent.h.
References Mantid::Geometry::d, index, and ncols.
getDetectorID()
template<size_t nd> int32_t Mantid::DataObjects::MDEvent< nd >::getDetectorID () const inline
Returns
the detectorId of this event.
Definition at line 191 of file MDEvent.h.
Referenced by Mantid::MDAlgorithms::copyEvent(), and Mantid::MDAlgorithms::copyEvent().
getExpInfoIndex()
template<size_t nd> uint16_t Mantid::DataObjects::MDEvent< nd >::getExpInfoIndex () const inline
Returns
the associated experiment-info index of this event in the containing MDEventWorkspace
Definition at line 175 of file MDEvent.h.
Referenced by Mantid::MDAlgorithms::copyEvent(), and Mantid::MDAlgorithms::copyEvent().
getGoniometerIndex()
template<size_t nd> uint16_t Mantid::DataObjects::MDEvent< nd >::getGoniometerIndex () const inline
Returns
the goniometer index of this event
Definition at line 183 of file MDEvent.h.
getTypeName()
template<size_t nd> static std::string Mantid::DataObjects::MDEvent< nd >::getTypeName () inline static
Returns
a string identifying the type of event this is.
Definition at line 199 of file MDEvent.h.
Referenced by Mantid::DataObjects::BoxControllerNeXusIO::BoxControllerNeXusIO().
setDetectorId()
template<size_t nd> void Mantid::DataObjects::MDEvent< nd >::setDetectorId (int32_t id) inline
Sets the detectorId of this event.
Parameters
id :: new detector ID value.
Definition at line 195 of file MDEvent.h.
Referenced by Mantid::MDAlgorithms::copyEvent(), and Mantid::MDAlgorithms::copyEvent().
setExpInfoIndex()
template<size_t nd> void Mantid::DataObjects::MDEvent< nd >::setExpInfoIndex (uint16_t index) inline
Sets the expInfoIndex of this event.
Parameters
index :: new expInfoIndex value.
Definition at line 179 of file MDEvent.h.
References index.
Referenced by Mantid::MDAlgorithms::copyEvent(), and Mantid::MDAlgorithms::copyEvent().
setGoniometerIndex()
template<size_t nd> void Mantid::DataObjects::MDEvent< nd >::setGoniometerIndex (uint16_t index) inline
Sets the expInfoIndex of this event.
Parameters
index :: new goniometerIndex value.
Definition at line 187 of file MDEvent.h.
References index.
Member Data Documentation
detectorId
template<size_t nd> int32_t Mantid::DataObjects::MDEvent< nd >::detectorId protected
Detector ID of the pixel that measured this event.
Definition at line 48 of file MDEvent.h.
expInfoIndex
template<size_t nd> uint16_t Mantid::DataObjects::MDEvent< nd >::expInfoIndex protected
0-based index of which run this event belongs to.
This refers to the particular ExperimentInfo that is stored in the MDEventWorkspace
Definition at line 42 of file MDEvent.h.
goniometerIndex
template<size_t nd> uint16_t Mantid::DataObjects::MDEvent< nd >::goniometerIndex protected
0-based index determines the goniometer settings when this event occurred
Definition at line 45 of file MDEvent.h.
The documentation for this class was generated from the following file:
Framework/DataObjects/inc/MantidDataObjects/MDEvent.h