Mantid: Mantid::DataHandling::LoadLog Class Reference
Mantid::DataHandling::LoadLog Class Reference final
Load ISIS log file(s).
#include <DataHandling/LoadLog.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
LoadLog ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Types
enum kind { empty , string , number }
type returned by classify
Private Member Functions
kind classify (const std::string &s) const
Takes as input a string and try to determine what type it is.
int countNumberColumns (std::ifstream &logFileStream, const std::string &logFileName)
Returns the number of columns in the log file.
void exec () override
Overwrites Algorithm method.
std::string extractLogName (const std::vector< std::string > &logName)
Checks if a log file name was provided (e.g.
void init () override
Overwrites Algorithm method.
bool isAscii (const std::string &filename)
Checks if the file is an ASCII file.
bool isDateTimeString (const std::string &str) const
Check if first 19 characters of a string is date-time string according to yyyy-mm-ddThh:mm:ss.
bool isOldDateTimeFormat (std::ifstream &logFileStream) const
Check whether the first 24 characters of a string are consistent with the date-time format used in older unsupported log files.
bool LoadSNSText ()
SNS text.
void loadThreeColumnLogFile (std::ifstream &logFileStream, const std::string &logFileName, API::Run &run)
Create timeseries property from .log file and adds that to sample object.
void loadTwoColumnLogFile (std::ifstream &logFileStream, std::string logFileName, API::Run &run)
Loads two column log file data into local workspace.
bool SNSTextFormatColumns (const std::string &input, std::vector< double > &out) const
Check for SNS-style text file.
std::string stringToLower (std::string strToConvert)
Convert string to lower case.
Private Attributes
std::string m_filename
The name and path of an input file.
std::shared_ptr< Kernel::Property > m_periods
TimeSeriesProperty<int> containing data periods. Created by LogParser.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Load ISIS log file(s).
Assumes that a log file originates from a PC (not VMS) environment, i.e. the log files to be loaded are assumed to have the extension .txt. Its filename is assumed to starts with the raw data file identifier followed by the character '_', and a log file is assumed to have a format of two columns, where the first column consists of data-time strings of the ISO 8601 form and the second column consists of either numbers or strings that may contain spaces.
The algoritm requires an input filename. If this filename is the name of a raw datafile the algorithm will attempt to read in all the log files associated with that log file. Otherwise it will assume the filename specified is the filename of a specific log file.
LoadLog is an algorithm and as such inherits from the Algorithm class, via DataHandlingCommand, and overrides the init() & exec() methods. LoadLog is intended to be used as a child algorithm of other Loadxxx algorithms, rather than being used directly.
Required Properties:
Filename - The filename (including its full or relative path) of either an ISIS log file or an ISIS raw file. If a raw file is specified all log files associated with that raw file are loaded into the specified workspace. The file extension must either be .raw or .s when specifying a raw file, and at least 10 characters long.
Workspace - The workspace to which the log data is appended
Author
Anders Markvardsen, ISIS, RAL
Date
26/09/2007
Definition at line 59 of file LoadLog.h.
Member Enumeration Documentation
kind
enum Mantid::DataHandling::LoadLog::kind private
type returned by classify
Enumerator
empty
string
number
Definition at line 89 of file LoadLog.h.
Constructor & Destructor Documentation
LoadLog()
Mantid::DataHandling::LoadLog::LoadLog () default
Default constructor.
Empty default constructor.
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadLog::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 72 of file LoadLog.h.
classify()
LoadLog::kind Mantid::DataHandling::LoadLog::classify (const std::string & s) const private
Takes as input a string and try to determine what type it is.
Parameters
s :: The input string to be classified
Returns
A enum kind which tells what type the string is
Definition at line 396 of file LoadLog.cpp.
References empty, lower, number, string, and upper.
Referenced by countNumberColumns(), loadThreeColumnLogFile(), and loadTwoColumnLogFile().
countNumberColumns()
int Mantid::DataHandling::LoadLog::countNumberColumns (std::ifstream & logFileStream, const std::string & logFileName) private
Returns the number of columns in the log file.
Count the number of columns in the first line of the text file.
Parameters
logFileStream :: stream to the file
logFileName :: name for the log file
Definition at line 520 of file LoadLog.cpp.
References classify(), empty, Mantid::Kernel::Strings::extractToEOL(), isDateTimeString(), m_filename, number, and string.
Referenced by exec().
exec()
void Mantid::DataHandling::LoadLog::exec () override private virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in ISIS log file(s)
Exceptions
Mantid::Kernel::Exception::FileError Thrown if file is not recognised to be a raw datafile or log file
std::runtime_error Thrown with Workspace problems
Implements Mantid::API::Algorithm.
Definition at line 106 of file LoadLog.cpp.
References countNumberColumns(), Mantid::EMPTY_INT(), extractLogName(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), isAscii(), isOldDateTimeFormat(), LoadSNSText(), loadThreeColumnLogFile(), loadTwoColumnLogFile(), and m_filename.
extractLogName()
std::string Mantid::DataHandling::LoadLog::extractLogName (const std::vector< std::string > & logName) private
Checks if a log file name was provided (e.g.
Check if log file property name has been set.
through setPropertyValue). If not it creates one based on provided path.
If not set, return the workspace + log file name (e.g. HRP37129_ICPevent). Otherwise return first log name.
Parameters
logName :: The vector containing log file names.
Returns
The name of the log file.
Definition at line 307 of file LoadLog.cpp.
References m_filename.
Referenced by exec().
init()
void Mantid::DataHandling::LoadLog::init () override private virtual
Overwrites Algorithm method.
Initialisation method.
Implements Mantid::API::Algorithm.
Definition at line 68 of file LoadLog.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::InOut, and Mantid::API::FileProperty::Load.
isAscii()
bool Mantid::DataHandling::LoadLog::isAscii (const std::string & filename) private
Checks if the file is an ASCII file.
Checks whether filename is a simple text file.
Parameters
filename :: The filename to inspect
Returns
true if the filename has the .txt extension
Definition at line 441 of file LoadLog.cpp.
Referenced by exec().
isDateTimeString()
bool Mantid::DataHandling::LoadLog::isDateTimeString (const std::string & str) const private
Check if first 19 characters of a string is date-time string according to yyyy-mm-ddThh:mm:ss.
Check if the string conforms to the ISO8601 standard.
Parameters
str :: The string to test
Returns
true if the strings format matched the expected date format
Definition at line 469 of file LoadLog.cpp.
Referenced by countNumberColumns(), loadThreeColumnLogFile(), and loadTwoColumnLogFile().
isOldDateTimeFormat()
bool Mantid::DataHandling::LoadLog::isOldDateTimeFormat (std::ifstream & logFileStream) const private
Check whether the first 24 characters of a string are consistent with the date-time format used in older unsupported log files.
Check whether the string is consistent with the old log file date-time format, for example: Fri 31-JAN-2003 11:28:15 Wed 9-FEB-2005 09:47:01.
Parameters
logFileStream :: The file to test
Returns
true if the format matches the old log file format.
Definition at line 481 of file LoadLog.cpp.
References Mantid::Kernel::Strings::extractToEOL().
Referenced by exec().
LoadSNSText()
bool Mantid::DataHandling::LoadLog::LoadSNSText () private
SNS text.
Check if the file is SNS text; load it if it is, return false otherwise.
Returns
true if the file was a SNS style; false otherwise.
Definition at line 319 of file LoadLog.cpp.
References Mantid::Kernel::Strings::extractToEOL(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_filename, and SNSTextFormatColumns().
Referenced by exec().
loadThreeColumnLogFile()
void Mantid::DataHandling::LoadLog::loadThreeColumnLogFile (std::ifstream & logFileStream, const std::string & logFileName, API::Run & run) private
Create timeseries property from .log file and adds that to sample object.
reads the .log stream and creates timeseries property and sets that to the run object
Parameters
logFileStream :: The stream of the log file (data).
logFileName :: The name of the log file to load.
run :: The run information object
Definition at line 214 of file LoadLog.cpp.
References classify(), empty, Mantid::Kernel::Strings::extractToEOL(), Mantid::API::Algorithm::g_log, isDateTimeString(), m_filename, number, string, stringToLower(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
loadTwoColumnLogFile()
void Mantid::DataHandling::LoadLog::loadTwoColumnLogFile (std::ifstream & logFileStream, std::string logFileName, API::Run & run) private
Loads two column log file data into local workspace.
Load an ISIS log file into the local workspace.
Parameters
logFileStream :: The stream of the log file (data).
logFileName :: The name of the log file to load.
run :: The run information object
Definition at line 169 of file LoadLog.cpp.
References Mantid::API::LogManager::addLogData(), classify(), Mantid::Kernel::LogParser::createLogProperty(), Mantid::Kernel::Strings::extractToEOL(), isDateTimeString(), m_filename, number, string, and stringToLower().
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadLog::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 64 of file LoadLog.h.
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadLog::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 70 of file LoadLog.h.
SNSTextFormatColumns()
bool Mantid::DataHandling::LoadLog::SNSTextFormatColumns (const std::string & input, std::vector< double > & out) const private
Check for SNS-style text file.
Read a line of a SNS-style text file.
Parameters
input :: The string to test
out :: a vector that will be filled with the double values.
Returns
false if the format is NOT SNS style or a conversion failed.
Definition at line 499 of file LoadLog.cpp.
Referenced by LoadSNSText().
stringToLower()
std::string Mantid::DataHandling::LoadLog::stringToLower (std::string strToConvert) private
Convert string to lower case.
Change each element of the string to lower case.
Parameters
strToConvert :: The input string
Returns
The string but with all characters in lower case
Definition at line 431 of file LoadLog.cpp.
Referenced by loadThreeColumnLogFile(), and loadTwoColumnLogFile().
summary()
const std::string Mantid::DataHandling::LoadLog::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 66 of file LoadLog.h.
version()
int Mantid::DataHandling::LoadLog::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 69 of file LoadLog.h.
Member Data Documentation
m_filename
std::string Mantid::DataHandling::LoadLog::m_filename private
The name and path of an input file.
This may be the filename of a raw datafile or the name of a specific log file.
Definition at line 86 of file LoadLog.h.
Referenced by countNumberColumns(), exec(), extractLogName(), LoadSNSText(), loadThreeColumnLogFile(), and loadTwoColumnLogFile().
m_periods
std::shared_ptr<Kernel::Property> Mantid::DataHandling::LoadLog::m_periods private
TimeSeriesProperty<int> containing data periods. Created by LogParser.
Definition at line 125 of file LoadLog.h.
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadLog.h
Framework/DataHandling/src/LoadLog.cpp