Mantid: Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection Class Reference
Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection Class Reference
This class computes all possible unique reflections within the specified d-limits, given a certain unit cell, lattice centering and point group.
#include <PeakStatisticsTools.h>
Public Member Functions
void addObservations (const std::vector< DataObjects::Peak > &peaks)
Assigns the supplied peaks to the proper UniqueReflection.
size_t getObservedReflectionCount () const
Number of observed reflections.
size_t getObservedUniqueReflectionCount (size_t moreThan=0) const
Number of unique reflections that have more observations than the supplied number (default is 0 - gives number of).
UniqueReflection getReflection (const Kernel::V3D &hkl) const
Returns a copy of the UniqueReflection with the supplied HKL.
const std::map< Kernel::V3D, UniqueReflection > & getReflections () const
Returns the internally stored reflection map.
size_t getUniqueReflectionCount () const
Total number of unique reflections (theoretically possible).
std::vector< Kernel::V3D > getUnobservedUniqueReflections () const
List of unobserved unique reflections in resolution range.
UniqueReflectionCollection (const Geometry::UnitCell &cell, const std::pair< double, double > &dLimits, Geometry::PointGroup_sptr pointGroup, const Geometry::ReflectionCondition_sptr &centering)
UniqueReflectionCollection::UniqueReflectionCollection.
~UniqueReflectionCollection ()=default
Protected Member Functions
UniqueReflectionCollection (const std::map< Kernel::V3D, UniqueReflection > &reflections, const Geometry::PointGroup_sptr &pointGroup)
Alternative constructor for testing purposes, no validation is performed.
Private Attributes
Geometry::PointGroup_sptr m_pointgroup
std::map< Kernel::V3D, UniqueReflection > m_reflections
Detailed Description
This class computes all possible unique reflections within the specified d-limits, given a certain unit cell, lattice centering and point group.
The cost of this computation depends directly on the size of the unit cell (larger cells result in more reflections) and to some extent also on the symmetry (higher symmetry results in more matrix operations).
After adding observations using addObservations, various reflection- counts can be obtained, for example to calculate redundancy or completeness of the observations.
Definition at line 70 of file PeakStatisticsTools.h.
Constructor & Destructor Documentation
UniqueReflectionCollection() [1/2]
Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::UniqueReflectionCollection (const Geometry::UnitCell & cell, const std::pair< double, double > & dLimits, Geometry::PointGroup_sptr pointGroup, const Geometry::ReflectionCondition_sptr & centering)
UniqueReflectionCollection::UniqueReflectionCollection.
Takes the supplied parameters to calculate theoretically possible unique reflections and stores a UniqueReflection for each of those internally.
Parameters
cell :: UnitCell of the sample.
dLimits :: Resolution limits for the generated reflections.
pointGroup :: Point group of the sample.
centering :: Lattice centering.
Definition at line 113 of file PeakStatisticsTools.cpp.
References m_pointgroup, and m_reflections.
~UniqueReflectionCollection()
Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::~UniqueReflectionCollection () default
UniqueReflectionCollection() [2/2]
Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::UniqueReflectionCollection (const std::map< Kernel::V3D, UniqueReflection > & reflections, const Geometry::PointGroup_sptr & pointGroup) inline protected
Alternative constructor for testing purposes, no validation is performed.
Definition at line 90 of file PeakStatisticsTools.h.
Member Function Documentation
addObservations()
void Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::addObservations (const std::vector< DataObjects::Peak > & peaks)
Assigns the supplied peaks to the proper UniqueReflection.
Peaks for which the reflection family can not be found are ignored.
Definition at line 133 of file PeakStatisticsTools.cpp.
References m_pointgroup, m_reflections, and Mantid::Kernel::V3D::norm2().
Referenced by Mantid::Crystal::CountReflections::exec(), and Mantid::Crystal::SortHKL::getUniqueReflections().
getObservedReflectionCount()
size_t Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getObservedReflectionCount () const
Number of observed reflections.
Definition at line 180 of file PeakStatisticsTools.cpp.
References m_reflections.
Referenced by Mantid::Crystal::CountReflections::exec(), Mantid::Crystal::PeakStatisticsTools::PeaksStatistics::PeaksStatistics(), and Mantid::Crystal::PeakStatisticsTools::PeaksStatistics::PeaksStatistics().
getObservedUniqueReflectionCount()
size_t Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getObservedUniqueReflectionCount (size_t moreThan = 0) const
Number of unique reflections that have more observations than the supplied number (default is 0 - gives number of).
Definition at line 159 of file PeakStatisticsTools.cpp.
References m_reflections.
Referenced by Mantid::Crystal::CountReflections::exec().
getReflection()
UniqueReflection Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getReflection (const Kernel::V3D & hkl) const
Returns a copy of the UniqueReflection with the supplied HKL.
Raises an exception if the reflection is not found.
Definition at line 150 of file PeakStatisticsTools.cpp.
References m_pointgroup, and m_reflections.
getReflections()
const std::map< V3D, UniqueReflection > & Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getReflections () const
Returns the internally stored reflection map.
May disappear or change if implementation changes.
Definition at line 189 of file PeakStatisticsTools.cpp.
References m_reflections.
Referenced by Mantid::Crystal::SortHKL::exec(), Mantid::Crystal::PeakStatisticsTools::PeaksStatistics::PeaksStatistics(), and Mantid::Crystal::PeakStatisticsTools::PeaksStatistics::PeaksStatistics().
getUniqueReflectionCount()
size_t Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getUniqueReflectionCount () const
Total number of unique reflections (theoretically possible).
Definition at line 155 of file PeakStatisticsTools.cpp.
References m_reflections.
Referenced by Mantid::Crystal::CountReflections::exec().
getUnobservedUniqueReflections()
std::vector< V3D > Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::getUnobservedUniqueReflections () const
List of unobserved unique reflections in resolution range.
Definition at line 166 of file PeakStatisticsTools.cpp.
References m_reflections.
Referenced by Mantid::Crystal::CountReflections::getPeaksWorkspace().
Member Data Documentation
m_pointgroup
Geometry::PointGroup_sptr Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::m_pointgroup private
Definition at line 96 of file PeakStatisticsTools.h.
Referenced by addObservations(), getReflection(), and UniqueReflectionCollection().
m_reflections
std::map<Kernel::V3D, UniqueReflection> Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::m_reflections private
Definition at line 95 of file PeakStatisticsTools.h.
Referenced by addObservations(), getObservedReflectionCount(), getObservedUniqueReflectionCount(), getReflection(), getReflections(), getUniqueReflectionCount(), getUnobservedUniqueReflections(), and UniqueReflectionCollection().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/PeakStatisticsTools.h
Framework/Crystal/src/PeakStatisticsTools.cpp