Mantid: Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy Class Reference
Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy Class Reference
#include <FindSXPeaksHelper.h>
Public Member Functions
AllPeaksStrategy (const BackgroundStrategy *backgroundStrategy, const API::SpectrumInfo &spectrumInfo, const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
PeakList dofindSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, Bound low, Bound high, const int workspaceIndex) const override
Public Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
PeakList findSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const int workspaceIndex) const
PeakFindingStrategy (const BackgroundStrategy *backgroundStrategy, const API::SpectrumInfo &spectrumInfo, const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
virtual ~PeakFindingStrategy ()=default
Private Member Functions
PeakList convertToSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const std::vector< std::unique_ptr< PeakContainer > > &peaks, const int workspaceIndex) const
std::vector< std::unique_ptr< PeakContainer > > getAllPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, Bound low, Bound high, const Mantid::Crystal::FindSXPeaksHelper::BackgroundStrategy *backgroundStrategy) const
Additional Inherited Members
Protected Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
double calculatePhi (size_t workspaceIndex) const
Calculates the average phi value if the workspace contains multiple detectors per spectrum, or returns the value of phi if it is a single detector to spectrum mapping.
double convertToTOF (const double xValue, const size_t workspaceIndex) const
virtual PeakList dofindSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, Bound low, Bound high, const int workspaceIndex) const =0
BoundsIterator getBounds (const HistogramData::HistogramX &x) const
double getXValue (const HistogramData::HistogramX &x, const size_t peakLocation) const
Protected Attributes inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
const BackgroundStrategy * m_backgroundStrategy
const double m_maxValue = EMPTY_DBL()
const double m_minValue = EMPTY_DBL()
const API::SpectrumInfo & m_spectrumInfo
const XAxisUnit m_units
Detailed Description
Definition at line 183 of file FindSXPeaksHelper.h.
Constructor & Destructor Documentation
AllPeaksStrategy()
Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy::AllPeaksStrategy (const BackgroundStrategy * backgroundStrategy, const API::SpectrumInfo & spectrumInfo, const double minValue = EMPTY_DBL(), const double maxValue = EMPTY_DBL(), const XAxisUnit units = XAxisUnit::TOF)
Definition at line 392 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::m_backgroundStrategy.
Member Function Documentation
convertToSXPeaks()
PeakList Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy::convertToSXPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, const std::vector< std::unique_ptr< PeakContainer > > & peaks, const int workspaceIndex) const private
Definition at line 478 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::calculatePhi(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::convertToTOF(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::getXValue(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::m_spectrumInfo, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by dofindSXPeaks().
dofindSXPeaks()
PeakList Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy::dofindSXPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, Bound low, Bound high, const int workspaceIndex) const override virtual
Implements Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy.
Definition at line 402 of file FindSXPeaksHelper.cpp.
References convertToSXPeaks(), getAllPeaks(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::m_backgroundStrategy, Mantid::Geometry::x, and Mantid::Geometry::y.
getAllPeaks()
std::vector< std::unique_ptr< PeakContainer > > Mantid::Crystal::FindSXPeaksHelper::AllPeaksStrategy::getAllPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, Bound low, Bound high, const Mantid::Crystal::FindSXPeaksHelper::BackgroundStrategy * backgroundStrategy) const private
Definition at line 414 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::BackgroundStrategy::isBelowBackground(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by dofindSXPeaks().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
Framework/Crystal/src/FindSXPeaksHelper.cpp