Mantid: Mantid::CurveFitting::EigenMatrix_View Class Reference
Mantid::CurveFitting::EigenMatrix_View Class Reference
#include <EigenMatrixView.h>
Public Member Functions
size_t cols () const
EigenMatrix_View ()
EigenMatrix_View (const double *base, const size_t nTotalRows, size_t nTotalCols, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
CONST constructor: array->matrix view.
EigenMatrix_View (const Eigen::MatrixXd &matrix, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
CONST constructor: matrix->matrix view.
EigenMatrix_View (const EigenMatrix_View &v)
CONST copy constructor.
EigenMatrix_View (const map_type &matrix, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
CONST constructor: map->matrix view.
EigenMatrix_View (double *base, const size_t nTotalRows, size_t nTotalCols, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
EigenMatrix_View (Eigen::MatrixXd &matrix, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
EigenMatrix_View (EigenMatrix_View &v)
copy constructor
EigenMatrix_View (map_type &matrix, size_t nElements_1=SIZE_T_NULL, size_t nElements_2=SIZE_T_NULL, const size_t startElement_1=0, const size_t startElement_2=0)
size_t innerStride () const
map_type matrix_copy () const
const map_type matrix_inspector () const
map_type & matrix_mutator ()
EigenMatrix_View & operator= (EigenMatrix_View &&V)
EigenMatrix_View & operator= (EigenMatrix_View &V)
size_t outerStride () const
size_t rows () const
Protected Member Functions
void initialiseMatrix (const size_t nTotalRows, const size_t nTotalCols, size_t &nElements_1, size_t &nElements_2)
Protected Attributes
bool m_isConst = false
map_type m_view
Detailed Description
Definition at line 21 of file EigenMatrixView.h.
Constructor & Destructor Documentation
EigenMatrix_View() [1/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View ()
Definition at line 12 of file EigenMatrixView.cpp.
EigenMatrix_View() [2/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (double * base, const size_t nTotalRows, size_t nTotalCols, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
Parameters
base array from which to take view.
nTotalRows total number of rows in the subject matrix.
nTotalCols total number of columns in the subject matrix.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 22 of file EigenMatrixView.cpp.
References initialiseMatrix(), m_view, and SIZE_T_NULL.
EigenMatrix_View() [3/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (Eigen::MatrixXd & matrix, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
Parameters
matrix Eigen::MatrixXd from which to take view.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 39 of file EigenMatrixView.cpp.
References initialiseMatrix(), m_view, and SIZE_T_NULL.
EigenMatrix_View() [4/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (map_type & matrix, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
Parameters
matrix Eigen::Map of an Eigen::MatrixXd from which to take view.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 56 of file EigenMatrixView.cpp.
References initialiseMatrix(), m_view, and SIZE_T_NULL.
EigenMatrix_View() [5/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (const double * base, const size_t nTotalRows, size_t nTotalCols, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
CONST constructor: array->matrix view.
Parameters
base array from which to take view.
nTotalRows total number of rows in the subject matrix.
nTotalCols total number of columns in the subject matrix.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 75 of file EigenMatrixView.cpp.
EigenMatrix_View() [6/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (const Eigen::MatrixXd & matrix, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
CONST constructor: matrix->matrix view.
Parameters
matrix Eigen::MatrixXd from which to take view.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 89 of file EigenMatrixView.cpp.
EigenMatrix_View() [7/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (const map_type & matrix, size_t nElements_1 = SIZE_T_NULL, size_t nElements_2 = SIZE_T_NULL, const size_t startElement_1 = 0, const size_t startElement_2 = 0)
CONST constructor: map->matrix view.
Parameters
matrix Eigen::Map of an Eigen::MatrixXd from which to take view.
nElements_1 number of elements to include in view in dimension 1 (rows).
nElements_2 number of elements to include in view in dimension 2 (cols).
startElement_1 index number of element to start view on, dimension 1 (rows).
startElement_2 index number of element to start view on, dimension 2 (cols).
Definition at line 103 of file EigenMatrixView.cpp.
EigenMatrix_View() [8/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (EigenMatrix_View & v)
copy constructor
Parameters
v :: EigenMatrix_View to copy.
Definition at line 121 of file EigenMatrixView.cpp.
EigenMatrix_View() [9/9]
Mantid::CurveFitting::EigenMatrix_View::EigenMatrix_View (const EigenMatrix_View & v)
CONST copy constructor.
Parameters
v :: EigenMatrix_View to copy.
Definition at line 113 of file EigenMatrixView.cpp.
Member Function Documentation
cols()
size_t Mantid::CurveFitting::EigenMatrix_View::cols () const inline
Definition at line 61 of file EigenMatrixView.h.
Referenced by Mantid::CurveFitting::EigenMatrix::copyRow(), Mantid::CurveFitting::EigenMatrix::get(), Mantid::CurveFitting::EigenMatrix::set(), and Mantid::CurveFitting::EigenMatrix::size2().
initialiseMatrix()
void Mantid::CurveFitting::EigenMatrix_View::initialiseMatrix (const size_t nTotalRows, const size_t nTotalCols, size_t & nElements_1, size_t & nElements_2) inline protected
Definition at line 69 of file EigenMatrixView.h.
References SIZE_T_NULL.
Referenced by EigenMatrix_View(), EigenMatrix_View(), and EigenMatrix_View().
innerStride()
size_t Mantid::CurveFitting::EigenMatrix_View::innerStride () const inline
Definition at line 63 of file EigenMatrixView.h.
Referenced by Mantid::CurveFitting::EigenMatrix::copyColumn().
matrix_copy()
map_type Mantid::CurveFitting::EigenMatrix_View::matrix_copy () const inline
Definition at line 59 of file EigenMatrixView.h.
matrix_inspector()
const map_type Mantid::CurveFitting::EigenMatrix_View::matrix_inspector () const inline
Definition at line 58 of file EigenMatrixView.h.
Referenced by Mantid::CurveFitting::EigenMatrix::get().
matrix_mutator()
map_type & Mantid::CurveFitting::EigenMatrix_View::matrix_mutator ()
Returns
a non-const reference to the member m_view, an Eigen::Map of an Eigen::MatrixXd.
Definition at line 126 of file EigenMatrixView.cpp.
References m_isConst, and m_view.
Referenced by Mantid::CurveFitting::EigenMatrix::copyColumn(), Mantid::CurveFitting::EigenMatrix::copyRow(), Mantid::CurveFitting::EigenMatrix::EigenMatrix(), Mantid::CurveFitting::EigenMatrix::EigenMatrix(), Mantid::CurveFitting::EigenMatrix::identity(), Mantid::CurveFitting::EigenMatrix::operator*=(), Mantid::CurveFitting::EigenMatrix::operator+=(), Mantid::CurveFitting::EigenMatrix::operator+=(), Mantid::CurveFitting::EigenMatrix::operator-=(), Mantid::CurveFitting::EigenMatrix::operator-=(), Mantid::CurveFitting::EigenMatrix::set(), and Mantid::CurveFitting::EigenMatrix::zero().
operator=() [1/2]
EigenMatrix_View & Mantid::CurveFitting::EigenMatrix_View::operator= (EigenMatrix_View && V)
Definition at line 141 of file EigenMatrixView.cpp.
References m_isConst, and m_view.
operator=() [2/2]
EigenMatrix_View & Mantid::CurveFitting::EigenMatrix_View::operator= (EigenMatrix_View & V)
Definition at line 134 of file EigenMatrixView.cpp.
References m_isConst, and m_view.
outerStride()
size_t Mantid::CurveFitting::EigenMatrix_View::outerStride () const inline
Definition at line 62 of file EigenMatrixView.h.
Referenced by Mantid::CurveFitting::EigenMatrix::copyRow().
rows()
size_t Mantid::CurveFitting::EigenMatrix_View::rows () const inline
Definition at line 60 of file EigenMatrixView.h.
Referenced by Mantid::CurveFitting::EigenMatrix::copyColumn(), Mantid::CurveFitting::EigenMatrix::get(), Mantid::CurveFitting::EigenMatrix::operator()(), Mantid::CurveFitting::EigenMatrix::set(), and Mantid::CurveFitting::EigenMatrix::size1().
Member Data Documentation
m_isConst
bool Mantid::CurveFitting::EigenMatrix_View::m_isConst = false protected
Definition at line 77 of file EigenMatrixView.h.
Referenced by matrix_mutator(), operator=(), and operator=().
m_view
map_type Mantid::CurveFitting::EigenMatrix_View::m_view protected
Definition at line 76 of file EigenMatrixView.h.
Referenced by EigenMatrix_View(), EigenMatrix_View(), EigenMatrix_View(), matrix_mutator(), operator=(), and operator=().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/EigenMatrixView.h
Framework/CurveFitting/src/EigenMatrixView.cpp