Mantid: Mantid::Geometry::AtomPositionsEqual Class Reference
Mantid::Geometry::AtomPositionsEqual Class Reference
Equality-functor for comparison of atom positions with specifiable precision.
#include <Group.h>
Public Member Functions
AtomPositionsEqual (double precision=1.e-4)
bool operator() (const Kernel::V3D &lhs, const Kernel::V3D &rhs) const
Private Attributes
double m_precision
Detailed Description
Equality-functor for comparison of atom positions with specifiable precision.
Definition at line 22 of file Group.h.
Constructor & Destructor Documentation
AtomPositionsEqual()
Mantid::Geometry::AtomPositionsEqual::AtomPositionsEqual (double precision = 1.e-4) inline
Definition at line 24 of file Group.h.
Member Function Documentation
operator()()
bool Mantid::Geometry::AtomPositionsEqual::operator() (const Kernel::V3D & lhs, const Kernel::V3D & rhs) const inline
Definition at line 26 of file Group.h.
References fabs, rhs, Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Member Data Documentation
m_precision
double Mantid::Geometry::AtomPositionsEqual::m_precision private
Definition at line 32 of file Group.h.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/Group.h