Mantid: MantidQt::MantidWidgets::MuonFitPropertyBrowser Class Reference
MantidQt::MantidWidgets::MuonFitPropertyBrowser Class Reference
#include <MuonFitPropertyBrowser.h>
Public Slots
void addPeriodCheckboxToMap (const QString &name)
Adds a new checkbox to the list of periods with given name It updates the display.
void combineBtnPressed ()
void executeFitMenu (const QString &item) override
void fit () override
Perform the fit algorithm.
void generateBtnPressed ()
void groupBtnPressed ()
void periodBtnPressed ()
void sequentialFit () override
Open sequential fit dialog.
void setNumPeriods (size_t numPeriods)
Sets checkboxes for periods.
void updatePeriods ()
updates the period displays
Public Slots inherited from MantidQt::MantidWidgets::FitPropertyBrowser
virtual void clear ()
Slot.
void clearBrowser ()
void executeClearCustomSetups ()
void executeCustomSetupRemove (const QString &name)
void executeDisplayMenu (const QString &)
virtual void executeFitMenu (const QString &)
void executeSetupManageMenu (const QString &)
void executeSetupMenu (const QString &)
void findPeaks ()
virtual void fit ()
Do the fit.
virtual void removePropertiesFromSettingsBrowser (const QStringList &propsToRemove)
Function to toggle the visibility of a settings group property exposed to python.
virtual void sequentialFit ()
void setPeakToolOn (bool on)
virtual void toggleSettingsBrowserVisible ()
Function to toggle the visibility of the settings browser.
virtual void toggleWsListVisible ()
void undoFit ()
Slot.
void workspaceDoubleClicked (QListWidgetItem *item)
Signals
void fitRawDataClicked (bool enabled) override
Emitted when "fit to raw data" is changed.
void functionUpdateAndFitRequested (bool sequential) override
Emitted when a fit or sequential fit is requested.
void functionUpdateRequested () override
Emitted when function should be updated.
void groupBoxClicked ()
void periodBoxClicked ()
void preFitChecksRequested (bool sequential) override
Emitted when fit is about to be run.
void reselctGroupClicked (bool enabled)
void sequentialFitRequested ()
Emitted when sequential fit is requested by user.
void TFPlot (QString wsName)
void userChangedDatasetIndex (int index) override
Emitted when dataset index to fit is changed.
void workspacesToFitChanged (int n) override
Emitted when number of workspaces to fit is changed.
Signals inherited from MantidQt::MantidWidgets::FitPropertyBrowser
void algorithmFinished (const QString &)
void algorithmStarted (const QString &)
void changedParameterOf (const QString &prefix)
void changeWindowTitle (const QString &)
void currentChanged () const
void endXChanged (double)
void errorsEnabled (bool enabled)
void executeFit (QString, QHash< QString, QString >, Mantid::API::AlgorithmObserver *)
void fitResultsChanged (const QString &status)
void fittingDone (const QString &)
signal which can optionally be caught for customization after a fit has been done
void fitUndone ()
void functionChanged ()
void functionCleared ()
void functionFactoryUpdateReceived ()
void functionLoaded (const QString &)
void functionRemoved ()
void itemDoubleClicked (QListWidgetItem *item)
void multifitFinished ()
void parameterChanged (const Mantid::API::IFunction *)
void plotCurrentGuess ()
void plotGuess ()
void removeCurrentGuess ()
void removeFitCurves ()
void removeGuess ()
void removePlotSignal (MantidQt::MantidWidgets::PropertyHandler *)
void sequentialFitDone () const
void startXChanged (double)
void updatePlotSpectrum (int index)
void workspaceClicked (const QString &wsName)
void workspaceIndexChanged (int index)
void workspaceNameChanged (const QString &)
void wsChangePPAssign (const QString &)
void xRangeChanged (double, double)
Signals inherited from MantidQt::MantidWidgets::IMuonFitFunctionModel
virtual void fitRawDataClicked (bool enabled)=0
virtual void functionUpdateAndFitRequested (bool sequential)=0
virtual void functionUpdateRequested ()=0
virtual void userChangedDatasetIndex (int index)=0
Signals inherited from MantidQt::MantidWidgets::IMuonFitDataModel
virtual void preFitChecksRequested (bool sequential)=0
Public Member Functions
void addExtraWidget (QWidget *widget)
Add an extra widget into the browser.
void addFitBrowserWidget (QWidget *widget, MantidQt::MantidWidgets::FunctionBrowser *functionBrowser)
Adds an extra widget in between the fit buttons and the browser.
void checkFitEnabled ()
void clearChosenGroups () const
Clear list of selected groups.
void clearChosenPeriods () const
Clears the list of selected groups (unchecks boxes)
void continueAfterChecks (bool sequential) override
After fit checks done, continue.
void doPlotGuess () override
Plot a guess function.
void doRemoveGuess () override
Remove a plotted guess.
void doTFAsymmFit ()
Creates an instance of Fit algorithm, sets its properties and launches it.
void finishHandle (const Mantid::API::IAlgorithm *alg) override
Called when the fit is finished.
void finishHandleNormal (const Mantid::API::IAlgorithm *alg)
void finishHandleTF (const Mantid::API::IAlgorithm *alg)
QStringList getChosenGroups () const
Returns a list of the selected groups (checked boxes)
QStringList getChosenPeriods () const
Returns a list of the selected periods (checked boxes)
Mantid::API::IFunction_sptr getFunction () const override
Get the fitting function.
std::vector< std::string > getWorkspaceNamesToFit () const override
Get names of workspaces that are set to be fitted.
bool hasGuess () const override
Whether a guess is plotted or not.
void init () override
Initialise the layout.
bool isMultiFittingMode () const override
returns true if the browser is set to multi fitting mode
MuonFitPropertyBrowser (QWidget *parent=nullptr, QObject *mantidui=nullptr)
Constructor.
std::string outputName () const override
Get output name.
void runFit () override
Run a non-sequential fit.
void runSequentialFit () override
Run a sequential fit.
void setAllGroups ()
Selects all groups.
void setAllGroupsOrPairs (const bool isItGroup)
Sets the multifit mode to all groups or all pairs depending on if a group or pair is selected in the home tab.
void setAllPairs ()
void setAllPeriods ()
Selects all periods.
void setAvailableGroups (const QStringList &groups)
Sets group names and updates checkboxes on UI By default sets all unchecked.
void setAvailablePeriods (const QStringList &periods)
Sets period names and updates checkboxes on UI By default sets all unchecked.
void setChosenGroup (const QString &group)
Selects a single group/pair.
void setChosenPeriods (const QString &period)
Ticks the selected periods.
virtual void setFitEnabled (bool yes) override
Enable/disable the Fit button;.
void setFunction (const Mantid::API::IFunction_sptr func) override
Set function externally.
void setGroupNames (const std::vector< std::string > groupNames)
void setMultiFittingMode (bool enabled) override
Set multiple fitting mode on or off.
void setNormalization (const std::string &name)
void setSimultaneousLabel (const std::string &label) override
Set label for simultaneous fit results.
void setSingleFitLabel (const std::string &name)
sets the label for a single fit and selects the relevant group/pair
void setTFAsymm (bool state)
void setWorkspaceName (const QString &wsName) override
Set the input workspace name.
void setWorkspaceNames (const QStringList &wsNames) override
Set list of workspaces to fit.
void userChangedDataset (int index) override
User changed dataset index to fit.
Public Member Functions inherited from MantidQt::MantidWidgets::FitPropertyBrowser
void addAllowedSpectra (const QString &wsName, const QList< int > &wsIndices)
void addAllowedTableWorkspace (const QString &wsName)
void addAutoBackground ()
Creates and adds the autobackground.
void addFitResultWorkspacesToTableWidget ()
Adds the fit result workspaces to the QListWidget in the browser.
QString addFunction (const QString &fnName)
A specialisation of addFunction to be used in the workbench.
PropertyHandler * addFunction (const std::string &fnName)
Create a new function.
void addHandle (const std::string &wsName, const std::shared_ptr< Mantid::API::Workspace > &ws) override
workspace was added
void allowSequentialFits (bool allow) override
Allow or disallow sequential fits (depending on whether other conditions are met)
double centre () const
Centre of the current peak.
std::shared_ptr< Mantid::API::CompositeFunction > compositeFunction () const
Get Composite Function.
bool convolveMembers () const
Get the "ConvolveMembers" option.
std::string costFunction () const
Get the cost function.
int count () const
Get count.
PropertyHandler * currentHandler () const
Get the current function.
std::string defaultBackgroundType () const
Get the default background type.
std::string defaultFunctionType () const
Get the default function type.
std::string defaultPeakType ()
Get the default peak type.
double endX () const
Get the end X.
void finishHandle (const Mantid::API::IAlgorithm *alg) override
Called when the Fit is finished.
FitPropertyBrowser (QWidget *parent=nullptr, QObject *mantidui=nullptr)
Constructor.
double fwhm () const
Width of the current peak.
QString getAutoBackgroundString () const
std::string getCentreParameterNameOf (const QString &prefix)
QString getConstraintsString () const
Creates the "Constraints" property value for the Fit algorithm.
int getDecimals () const
Number of decimal places in double properties.
QString getErrColumnName () const
Get the name of the Error column.
std::string getExcludeRange () const
Get the excluded range for the fit.
std::string getFitAlgorithmOutputStatus () const
================================================================================================= Get Fit Algorithm output statuss
std::string getFitAlgorithmParameters () const
================================================================================================= Get Fit Algorithm parameters
QMenu * getFitMenu () const
Return the Fit menu.
Mantid::API::IFunction_sptr getFittingFunction () const
Return the fitting function.
Mantid::API::IFunction_sptr getFunctionAtIndex (std::size_t const &index) const
Return a function at a specific index in the composite function.
std::string getFunctionString () const
Get the function as a string.
PropertyHandler * getHandler () const
Get handler to the root composite function.
QStringList getParameterNames () const
Get function parameter names.
QList< double > getParameterValues () const
Get function parameter values.
double getPeakCentreOf (const QString &prefix)
double getPeakFwhmOf (const QString &prefix)
PropertyHandler * getPeakHandler (const QString &prefix)
double getPeakHeightOf (const QString &prefix)
QStringList getPeakPrefixes () const
int getPeakRadius () const
Get the peak radius for peak functions.
QString getTieString () const
Creates the "Ties" property value for the Fit algorithm.
std::string getWidthParameterNameOf (const QString &prefix)
std::shared_ptr< Mantid::API::Workspace > getWorkspace () const
Get the workspace.
QListWidget * getWorkspaceList () const
Return the Fit menu.
QStringList getWorkspaceNames ()
Returns the list of workspaces that are currently been worked on by the fit property browser.
QString getXColumnName () const
Get the name of the X column.
QVector< double > getXRange ()
Get the X limits of the workspace.
QString getYColumnName () const
Get the name of the Y column.
double height () const
Height of the current peak.
bool ignoreInvalidData () const
Get the ignore invalid data option.
virtual void init ()
Initialise layout.
bool isAutoBack () const
bool isFitEnabled () const
Returns true if the function is ready for a fit.
bool isHistogramFit () const
Get "HistogramFit" option.
bool isParameterExplicitlySetOf (const QString &prefix, const std::string &param)
bool isPeak () const
Is the current function a peak?
bool isUndoEnabled () const
Tells if undo can be done.
void loadFunction (const QString &funcString)
Load function.
int maxIterations () const
Get the max number of iterations.
std::string minimizer (bool withProperties=false) const
Get the minimizer.
void normaliseData (bool on)
Set if the data must be normalised before fitting.
virtual std::string outputName () const
Get the output name.
bool plotCompositeMembers () const
Returns true if a composite's member functions should be plotted also.
bool plotDiff () const
Returns true if the difference plot should be drawn.
void postDeleteHandle (const std::string &wsName) override
workspace was removed
bool rawData () const override
Returns true if the fit should be done against binned (bunched) data.
void refitAutoBackground ()
const QStringList & registeredBackgrounds () const
Return a list of registered backgrounds.
const QStringList & registeredFunctions () const
Return a list of registered functions.
const QStringList & registeredOthers () const
Return a list of registered other functions.
const QStringList & registeredPeaks () const
Return a list of registered peaks.
virtual void removeFunction (PropertyHandler *handler)
Removes the function held by the property handler.
void removeWorkspace (const std::string &wsName)
void removeWorkspaceAndSpectra (const std::string &wsName)
void renameHandle (const std::string &oldName, const std::string &newName) override
Handler of the Rename notifications.
void saveFunction (const QString &fnName)
save function
void sendParameterChanged (const Mantid::API::IFunction *f)
void sendParameterChanged (const QString &prefix)
void sequentialFitFinished ()
void setADSObserveEnabled (bool enabled)
void setAutoBackgroundName (const QString &aName)
Remember a background function name to be used for creating auto-background.
void setCentre (double value)
Set centre of the current peak.
void setCurrentFunction (PropertyHandler *h) const
Set new current function.
void setDecimals (int d)
void setDefaultBackgroundType (const std::string &fnType)
Set the default background type.
void setDefaultFunctionType (const std::string &fnType)
Set the default function type.
void setDefaultPeakType (const std::string &fnType)
Set the default peak type.
void setEndX (double end) override
Set the end X.
virtual void setFitEnabled (bool enable)
Enable/disable the Fit buttons;.
void setFwhm (double value)
Set width of the current peak.
void setHeight (double value)
Set height of the current peak.
void setIgnoreInvalidData (bool on)
Set the ignore invalid data option.
void setOutputName (const std::string &)
Set the output name.
void setPeakCentreOf (const QString &prefix, double value)
void setPeakFwhmOf (const QString &prefix, double value)
void setPeakHeightOf (const QString &prefix, double value)
void setStartX (double start) override
Set the start X.
void setTextPlotGuess (const QString &text)
alter text of Plot Guess
void setTip (const QString &txt)
Display a tip.
void setWorkspaceIndex (int i) override
Set workspace index.
virtual void setWorkspaceName (const QString &wsName) override
Set the input workspace name.
void setXRange (double start, double end)
Set both start and end X.
int sizeOfFunctionsGroup () const
double startX () const
Get the start X.
std::shared_ptr< const Mantid::API::IFunction > theFunction () const
Get the current function.
void updateAttributes ()
Update the function attributes.
void updateParameters ()
Update the function parameters.
int workspaceIndex () const
Get workspace index.
std::string workspaceName () const
Get the input workspace name.
~FitPropertyBrowser () override
Destructor.
Public Member Functions inherited from Mantid::API::AlgorithmObserver
AlgorithmObserver ()
Default constructor.
AlgorithmObserver (const IAlgorithm_const_sptr &alg)
Constructs AlgorithmObserver and connects all its handlers to algorithm alg.
virtual void errorHandle (const IAlgorithm *alg, const std::string &what)
virtual void finishHandle (const IAlgorithm *alg)
void observeAll (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe all its notifications.
void observeError (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its error notification.
void observeFinish (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its finish notification.
void observeProgress (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its progress notification.
void observeStart (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its start notification.
void observeStarting ()
Connect to AlgorithmManager and observe its starting notifications.
virtual void progressHandle (const IAlgorithm *alg, double p, const std::string &msg, const double estimatedTime, const int progressPrecision)
virtual void startHandle (const IAlgorithm *alg)
virtual void startingHandle (IAlgorithm_sptr alg)
void stopObserving (const IAlgorithm_const_sptr &alg)
Disconnect from algorithm alg.
void stopObserving (const Mantid::API::IAlgorithm *alg)
void stopObservingManager ()
Disconnect from the algorithm manager.
virtual ~AlgorithmObserver ()
Virtual destructor.
Public Member Functions inherited from MantidQt::API::WorkspaceObserver
void observeAdd (bool on=true)
Observe additions.
void observeADSClear (bool on=true)
Observe clearances.
void observeAfterReplace (bool on=true)
Observe replacements.
void observePostDelete (bool on=true)
Observe workspace deletes.
void observePreDelete (bool on=true)
Observe workspace deletes.
void observeRename (bool on=true)
Observe renaming.
WorkspaceObserver ()
Default constructor.
virtual ~WorkspaceObserver ()
Destructor.
Public Member Functions inherited from MantidQt::MantidWidgets::IWorkspaceFitControl
virtual void allowSequentialFits (bool allow)=0
virtual bool rawData () const =0
virtual void setEndX (double end)=0
virtual void setStartX (double start)=0
virtual void setWorkspaceIndex (int i)=0
virtual void setWorkspaceName (const QString &wsName)=0
virtual ~IWorkspaceFitControl ()=default
Public Member Functions inherited from MantidQt::MantidWidgets::IMuonFitFunctionModel
virtual void doPlotGuess ()=0
virtual void doRemoveGuess ()=0
virtual Mantid::API::IFunction_sptr getFunction () const =0
virtual std::vector< std::string > getWorkspaceNamesToFit () const =0
virtual bool hasGuess () const =0
virtual bool isMultiFittingMode () const =0
virtual void runFit ()=0
virtual void runSequentialFit ()=0
virtual void setFunction (const Mantid::API::IFunction_sptr func)=0
virtual void setMultiFittingMode (bool enabled)=0
virtual ~IMuonFitFunctionModel ()=default
Public Member Functions inherited from MantidQt::MantidWidgets::IMuonFitDataModel
virtual void continueAfterChecks (bool sequential)=0
virtual void setSimultaneousLabel (const std::string &label)=0
virtual void setWorkspaceNames (const QStringList &wsNames)=0
virtual void userChangedDataset (int index)=0
virtual void workspacesToFitChanged (int n)=0
Static Public Attributes
static const std::string SIMULTANEOUS_PREFIX = {"MuonSimulFit_"}
Prefix for simultaneous fit results.
Protected Member Functions
void setNormalization ()
void showEvent (QShowEvent *e) override
Connect to the AnalysisDataService when shown.
Protected Member Functions inherited from MantidQt::MantidWidgets::FitPropertyBrowser
QtProperty * addDoubleProperty (const QString &name, QtDoublePropertyManager *manager=nullptr) const
Create a double property and set some settings.
virtual void addWorkspaceIndexToBrowser ()
Adds the workspace index property to the browser.
void createCompositeFunction (const Mantid::API::IFunction_sptr &func)
Create CompositeFunction from pointer.
void createCompositeFunction (const QString &str="")
Create CompositeFunction from string.
void createEditors (QWidget *w)
Create editors and assign them to the managers.
void doFit (int maxIterations)
Do the fitting.
bool getShouldBeNormalised ()
void hideEvent (QHideEvent *e) override
actions to do before the browser is hidden
void initBasicLayout (QWidget *w)
Initialise the layout, except for the fit button in the menu bar.
void initLayout (QWidget *w)
Initialise the layout.
void minimizerChanged ()
Called when the minimizer changes. Creates minimizes's properties.
void modifyFitMenu (QAction *fitAction, bool enabled)
virtual void populateFitMenuButton (QSignalMapper *fitMapper, QMenu *fitMenu)
Populate the fit button.
void populateWorkspaceNames ()
Get and store available workspace names.
void setWorkspace (const Mantid::API::IFunction_sptr &function) const
Sets the workspace to a function.
void setWorkspaceProperties ()
Display properties relevant to the selected workspace.
void showEvent (QShowEvent *e) override
actions to do before the browser made visible
Mantid::API::IFunction_sptr tryCreateFitFunction (const QString &str)
Catches unexpected not found exceptions.
void updateBrowserFromFitResults (const Mantid::API::IFunction_sptr &finalFunction)
Set the parameters to the fit outcome.
void updateDecimals ()
impose a number of decimal places on all defined Double properties
Protected Member Functions inherited from MantidQt::API::WorkspaceObserver
void _addHandle (Mantid::API::WorkspaceAddNotification_ptr pNf)
Poco notification handler for DataService::DeleteNotification.
void _afterReplaceHandle (Mantid::API::WorkspaceAfterReplaceNotification_ptr pNf)
Poco notification handler for DataService::AfterReplaceNotification.
void _clearADSHandle (Mantid::API::ClearADSNotification_ptr)
ADS clear notification.
void _postDeleteHandle (Mantid::API::WorkspacePostDeleteNotification_ptr pNf)
Poco notification handler for DataService::PostDeleteNotification.
void _preDeleteHandle (Mantid::API::WorkspacePreDeleteNotification_ptr pNf)
Poco notification handler for DataService::PostDeleteNotification.
void _renameHandle (Mantid::API::WorkspaceRenameNotification_ptr pNf)
Poco notification handler for DataService::RenameNotification.
virtual void addHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the add notifications.
virtual void afterReplaceHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the AfterReplace notifications.
virtual void clearADSHandle ()
Handle an ADS clear notification.
virtual void postDeleteHandle (const std::string &wsName)
Handler of the delete notifications.
virtual void preDeleteHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the delete notifications.
virtual void renameHandle (const std::string &oldName, const std::string &newName)
Handler of the Rename notifications.
Private Slots
void boolChanged (QtProperty *prop) override
Called when a bool property changed.
void doubleChanged (QtProperty *prop) override
Called when a double property changed.
void enumChanged (QtProperty *prop) override
Called when a dropdown menu is changed.
Private Member Functions
void addGroupCheckbox (const QString &name)
Add a new checkbox to the list of groups with given name The new checkbox is checked according to dropdown menu selection.
void addPeriodCheckbox (const QString &name)
Add a new checkbox to the list of periods with given name The new checkbox is unchecked by default.
void clearGroupCheckboxes ()
Clears all group names and checkboxes (ready to add new ones)
void clearPeriodCheckboxes ()
Clears all pair names and checkboxes (ready to add new ones)
void ConvertFitFunctionForMuonTFAsymmetry (bool enabled)
void finishAfterSimultaneousFit (const Mantid::API::IAlgorithm *fitAlg, const int nWorkspaces) const
After a simultaneous fit, add information to results table and group workspaces.
void finishAfterTFSimultaneousFit (const Mantid::API::IAlgorithm *alg, const std::string &baseName) const
After a TF simultaneous fit, insert extra information into parameters table (i.e.
void genCombinePeriodWindow ()
void genGroupWindow ()
void genPeriodWindow ()
std::string getUnnormName (const std::string wsName)
bool isPeriodValid (const QString &name)
Check if a period is valid.
bool isWorkspaceValid (Mantid::API::Workspace_sptr) const override
Check if the workspace can be used in the fit.
void populateFunctionNames () override
Get the registered function names.
void setChosenPeriods (const QStringList &chosenPeriods)
Ticks the selected periods.
void setFitWorkspaces (const std::string &input)
void setTFAsymmMode (bool state)
Set TF asymmetry mode on or off.
std::string TFExtension () const
void updateGroupDisplay ()
Sets the display for selected groups.
void updatePeriodDisplay ()
Sets the display for selected periods.
void updatePeriods (const int j)
updates the period displays and conserves the selection if selection is niot available default to all periods
void updateTFPlot ()
Makes sure we have the TF plot in TFAsymm mode.
Private Attributes
QString m_autoBackground
QGroupBox * m_btnGroup
QDialog * m_comboWindow
MantidQt::MantidWidgets::FunctionBrowser * m_functionBrowser
QPushButton * m_generateBtn
QMap< QString, QtProperty * > m_groupBoxes
Map of group names to checkboxes.
std::vector< std::string > m_groupsList
QtProperty * m_groupsToFit
QStringList m_groupsToFitOptions
QDialog * m_groupWindow
bool m_isMultiFittingMode
QtProperty * m_keepNorm
QSplitter * m_mainSplitter
QtBrowserItem * m_multiFitSettingsGroup
QLineEdit * m_negativeCombo
QtProperty * m_normalization
QStringList m_normalizationValue
QMap< QString, QtProperty * > m_periodBoxes
Map of group names to checkboxes.
QtProperty * m_periodsToFit
QStringList m_periodsToFitOptions
QDialog * m_periodWindow
QLineEdit * m_positiveCombo
QPushButton * m_reselectGroupBtn
QPushButton * m_reselectPeriodBtn
QtProperty * m_showGroup
QStringList m_showGroupValue
QtProperty * m_showPeriods
QStringList m_showPeriodValue
std::string m_simultaneousLabel
Label to use for simultaneous fits.
QtProperty * m_TFAsymmMode
QSplitter * m_widgetSplitter
Splitter for additional widgets and splitter between this and browser.
std::vector< std::string > m_workspacesToFit
Names of workspaces to fit.
Additional Inherited Members
Protected Slots inherited from MantidQt::MantidWidgets::FitPropertyBrowser
virtual void boolChanged (QtProperty *prop)
Called when a bool property is changed.
virtual void doubleChanged (QtProperty *prop)
Called when a double property changed.
void enactAttributeChange (QtProperty *prop, PropertyHandler *h, const bool vectorAttribute=false)
virtual void enumChanged (QtProperty *prop)
Called when the function name property changed.
virtual void intChanged (QtProperty *prop)
Called when an int property changed.
virtual void populateFunctionNames ()
Get the registered function names.
Protected Attributes inherited from MantidQt::MantidWidgets::FitPropertyBrowser
QtBoolPropertyManager * m_boolManager
QtTreePropertyBrowser * m_browser
bool m_changeSlotsEnabled
If false the change-slots (such as enumChanged(), doubleChanged()) are disabled.
QtEnumPropertyManager * m_columnManager
std::shared_ptr< Mantid::API::CompositeFunction > m_compositeFunction
A copy of the edited function.
QtProperty * m_convolveMembers
QtProperty * m_costFunction
QStringList m_costFunctions
A list of available cost functions.
QtBrowserItem * m_customSettingsGroup
Group for custom options available on muon analysis widget.
QtDoublePropertyManager * m_doubleManager
QtProperty * m_endX
QtEnumPropertyManager * m_enumManager
QtProperty * m_errColumn
QtProperty * m_evaluationType
QStringList m_evaluationTypes
A list of possible function evaluation types.
QtProperty * m_excludeRange
QtStringPropertyManager * m_filenameManager
QAction * m_fitActionEvaluate
QAction * m_fitActionFit
QAction * m_fitActionSeqFit
QAction * m_fitActionUndoFit
QtStringPropertyManager * m_formulaManager
QtBrowserItem * m_functionsGroup
Group for functions.
QtGroupPropertyManager * m_groupManager
Property managers:
bool m_guessOutputName
if true the output name will be guessed every time workspace name is changeed
QtProperty * m_ignoreInvalidData
std::vector< double > m_initialParameters
To keep a copy of the initial parameters in case for undo fit.
QtIntPropertyManager * m_intManager
QtProperty * m_maxIterations
QtProperty * m_minimizer
QList< QtProperty * > m_minimizerProperties
QStringList m_minimizers
A list of available minimizers.
QtProperty * m_output
ParameterPropertyManager * m_parameterManager
QtProperty * m_peakRadius
QtProperty * m_plotCompositeMembers
QtProperty * m_plotDiff
QtProperty * m_rawData
QStringList m_registeredBackgrounds
A list of registered backgrounds.
QStringList m_registeredFunctions
A list of registered functions.
QStringList m_registeredOther
A list of registered functions that are neither peaks nor backgrounds.
QStringList m_registeredPeaks
A list of registered peaks.
QtBrowserItem * m_settingsGroup
Group for input/output settings.
QtProperty * m_showParamErrors
QtProperty * m_startX
QtStringPropertyManager * m_stringManager
QtDoublePropertyManager * m_vectorDoubleManager
QtGroupPropertyManager * m_vectorManager
QtIntPropertyManager * m_vectorSizeManager
QtProperty * m_workspace
QtProperty * m_workspaceIndex
QStringList m_workspaceNames
A list of available workspaces.
QtProperty * m_xColumn
QtProperty * m_yColumn
Protected Attributes inherited from MantidQt::API::WorkspaceObserver
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceAddNotification > m_addObserver
Poco::NObserver for DataServise::AddNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceAfterReplaceNotification > m_afterReplaceObserver
Poco::NObserver for DataServise::AfterReplaceNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::ClearADSNotification > m_clearADSObserver
Clear notification observer.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspacePostDeleteNotification > m_postDeleteObserver
Poco::NObserver for DataServise::DeleteNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspacePreDeleteNotification > m_preDeleteObserver
Poco::NObserver for DataServise::DeleteNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceRenameNotification > m_renameObserver
Poco::NObserver for DataServise::RenameNotification.
Detailed Description
Definition at line 47 of file MuonFitPropertyBrowser.h.
Constructor & Destructor Documentation
MuonFitPropertyBrowser()
MantidQt::MantidWidgets::MuonFitPropertyBrowser::MuonFitPropertyBrowser (QWidget * parent = nullptr, QObject * mantidui = nullptr)
Constructor.
Parameters
parent :: The parent widget - must be an ApplicationWindow
mantidui :: The UI form for MantidPlot
Definition at line 90 of file MuonFitPropertyBrowser.cpp.
Member Function Documentation
addExtraWidget()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::addExtraWidget (QWidget * widget)
Add an extra widget into the browser.
Adds an extra widget in between the fit buttons and the browser.
Parameters
widget :: [input] Pointer to widget to add
Definition at line 1015 of file MuonFitPropertyBrowser.cpp.
addFitBrowserWidget()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::addFitBrowserWidget (QWidget * widget, MantidQt::MantidWidgets::FunctionBrowser * functionBrowser)
Adds an extra widget in between the fit buttons and the browser.
Parameters
widget :: [input] Pointer to widget to add
functionBrowser :: [input] pointer to the function browser
Definition at line 1241 of file MuonFitPropertyBrowser.cpp.
addGroupCheckbox()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::addGroupCheckbox (const QString & name) private
Add a new checkbox to the list of groups with given name The new checkbox is checked according to dropdown menu selection.
Parameters
name :: [input] Name of group to add
Definition at line 1328 of file MuonFitPropertyBrowser.cpp.
Referenced by init().
addPeriodCheckbox()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::addPeriodCheckbox (const QString & name) private
Add a new checkbox to the list of periods with given name The new checkbox is unchecked by default.
Parameters
name :: [input] Name of period to add
Definition at line 1604 of file MuonFitPropertyBrowser.cpp.
addPeriodCheckboxToMap
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::addPeriodCheckboxToMap (const QString & name) slot
Adds a new checkbox to the list of periods with given name It updates the display.
Parameters
name :: [input] Name of period to add
Definition at line 1547 of file MuonFitPropertyBrowser.cpp.
boolChanged
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged (QtProperty * prop) override private slot
Called when a bool property changed.
Parameters
prop :: A pointer to the property
Definition at line 523 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::boolChanged(), fitRawDataClicked(), groupBoxClicked(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_groupBoxes, m_keepNorm, m_periodBoxes, MantidQt::MantidWidgets::FitPropertyBrowser::m_rawData, m_TFAsymmMode, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspace, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames, periodBoxClicked(), MantidQt::MantidWidgets::FitPropertyBrowser::rawData(), MantidQt::MantidWidgets::readMultipleNormalization(), setTFAsymmMode(), tmp, updateGroupDisplay(), and updatePeriodDisplay().
checkFitEnabled()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::checkFitEnabled ()
Definition at line 312 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::count(), and setFitEnabled().
clearChosenGroups()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::clearChosenGroups () const
Clear list of selected groups.
Clears the list of selected groups (unchecks boxes)
Definition at line 1347 of file MuonFitPropertyBrowser.cpp.
Referenced by init().
clearChosenPeriods()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::clearChosenPeriods () const
Clears the list of selected groups (unchecks boxes)
Definition at line 1495 of file MuonFitPropertyBrowser.cpp.
clearGroupCheckboxes()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::clearGroupCheckboxes () private
Clears all group names and checkboxes (ready to add new ones)
Definition at line 1317 of file MuonFitPropertyBrowser.cpp.
clearPeriodCheckboxes()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::clearPeriodCheckboxes () private
Clears all pair names and checkboxes (ready to add new ones)
Definition at line 1481 of file MuonFitPropertyBrowser.cpp.
combineBtnPressed
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::combineBtnPressed () slot
Definition at line 1713 of file MuonFitPropertyBrowser.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::g_log, and value.
continueAfterChecks()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::continueAfterChecks (bool sequential) override virtual
After fit checks done, continue.
The pre-fit checks have been successfully completed.
Continue by emitting a signal to update the function and request the fit.
Parameters
sequential :: [input] Whether fit is sequential or not
Implements MantidQt::MantidWidgets::IMuonFitDataModel.
Definition at line 1254 of file MuonFitPropertyBrowser.cpp.
ConvertFitFunctionForMuonTFAsymmetry()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::ConvertFitFunctionForMuonTFAsymmetry (bool enabled) private
Definition at line 1108 of file MuonFitPropertyBrowser.cpp.
References index, and tmp.
doPlotGuess()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::doPlotGuess () inline override virtual
Plot a guess function.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 96 of file MuonFitPropertyBrowser.h.
doRemoveGuess()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::doRemoveGuess () inline override virtual
Remove a plotted guess.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 94 of file MuonFitPropertyBrowser.h.
doTFAsymmFit()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit ()
Creates an instance of Fit algorithm, sets its properties and launches it.
Definition at line 640 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::endX(), MantidQt::MantidWidgets::FunctionBrowser::getGlobalFunction(), getUnnormName(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::FitPropertyBrowser::m_compositeFunction, MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionUndoFit, m_functionBrowser, MantidQt::MantidWidgets::FitPropertyBrowser::m_initialParameters, m_workspacesToFit, MantidQt::MantidWidgets::FitPropertyBrowser::minimizer(), Mantid::API::AlgorithmObserver::observeFinish(), outputName(), MantidQt::MantidWidgets::FitPropertyBrowser::rawData(), setSingleFitLabel(), MantidQt::MantidWidgets::FitPropertyBrowser::startX(), tmp, and MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName().
Referenced by executeFitMenu().
doubleChanged
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged (QtProperty * prop) override private slot
Called when a double property changed.
Parameters
prop :: A pointer to the property
Definition at line 455 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addConstraint(), MantidQt::MantidWidgets::FitPropertyBrowser::endX(), MantidQt::MantidWidgets::FitPropertyBrowser::endXChanged(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), MantidQt::MantidWidgets::FitPropertyBrowser::getHandler(), MantidQt::MantidWidgets::PropertyHandler::getParameterProperty(), MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, MantidQt::MantidWidgets::FitPropertyBrowser::m_compositeFunction, MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_endX, MantidQt::MantidWidgets::FitPropertyBrowser::m_startX, MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspace(), MantidQt::MantidWidgets::FitPropertyBrowser::startX(), MantidQt::MantidWidgets::FitPropertyBrowser::startXChanged(), value, and MantidQt::MantidWidgets::FitPropertyBrowser::xRangeChanged().
enumChanged
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged (QtProperty * prop) override private slot
Called when a dropdown menu is changed.
Parameters
prop :: A pointer to the function name property
Definition at line 336 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::enumChanged(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, genGroupWindow(), genPeriodWindow(), MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_groupBoxes, m_groupsToFit, m_groupsToFitOptions, m_multiFitSettingsGroup, m_periodBoxes, m_periodsToFit, m_periodsToFitOptions, m_reselectGroupBtn, m_reselectPeriodBtn, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspace, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames, setAllGroups(), setAllPairs(), setAllPeriods(), MantidQt::MantidWidgets::FitPropertyBrowser::setOutputName(), tmp, updateGroupDisplay(), updatePeriodDisplay(), updateTFPlot(), and MantidQt::MantidWidgets::FitPropertyBrowser::workspaceNameChanged().
executeFitMenu
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::executeFitMenu (const QString & item) override slot
Definition at line 292 of file MuonFitPropertyBrowser.cpp.
References doTFAsymmFit(), MantidQt::MantidWidgets::FitPropertyBrowser::executeFitMenu(), MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, and m_TFAsymmMode.
finishAfterSimultaneousFit()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterSimultaneousFit (const Mantid::API::IAlgorithm * fitAlg, const int nWorkspaces) const private
After a simultaneous fit, add information to results table and group workspaces.
After a simultaneous fit, insert extra information into parameters table (i.e.
what runs, groups, periods "f0", "f1" etc were) and group the output workspaces
Parameters
fitAlg :: [input] Pointer to fit algorithm that just finished
nWorkspaces :: [input] Number of workspaces that were fitted
Definition at line 933 of file MuonFitPropertyBrowser.cpp.
References Mantid::API::AnalysisDataServiceImpl::addOrReplace(), Mantid::API::AnalysisDataServiceImpl::addToGroup(), Mantid::API::g_log, Mantid::Kernel::IPropertyManager::getProperty(), Mantid::Kernel::IPropertyManager::getPropertyValue(), Mantid::API::AnalysisDataServiceImpl::retrieveWS(), Mantid::Kernel::Logger::warning(), and Mantid::Kernel::Exception::NotFoundError::what().
finishAfterTFSimultaneousFit()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterTFSimultaneousFit (const Mantid::API::IAlgorithm * alg, const std::string & baseName) const private
After a TF simultaneous fit, insert extra information into parameters table (i.e.
what runs, groups, periods "f0", "f1" etc were) and group the output workspaces
Parameters
alg :: [input] Pointer to fit algorithm that just finished
baseName :: [input] The common name of the workspaces of interest
Definition at line 977 of file MuonFitPropertyBrowser.cpp.
References Mantid::API::AnalysisDataServiceImpl::addOrReplace(), Mantid::API::AnalysisDataServiceImpl::addToGroup(), Mantid::API::g_log, Mantid::Kernel::IPropertyManager::getProperty(), Mantid::API::AnalysisDataServiceImpl::retrieveWS(), Mantid::Kernel::Logger::warning(), and Mantid::Kernel::Exception::NotFoundError::what().
finishHandle()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandle (const Mantid::API::IAlgorithm * alg) override virtual
Called when the fit is finished.
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 877 of file MuonFitPropertyBrowser.cpp.
References Mantid::API::IAlgorithm::name().
finishHandleNormal()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandleNormal (const Mantid::API::IAlgorithm * alg)
Definition at line 912 of file MuonFitPropertyBrowser.cpp.
References Mantid::Kernel::IPropertyManager::getProperty().
finishHandleTF()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandleTF (const Mantid::API::IAlgorithm * alg)
Definition at line 884 of file MuonFitPropertyBrowser.cpp.
References Mantid::Kernel::IPropertyManager::getProperty(), and Mantid::Kernel::IPropertyManager::getPropertyValue().
fit
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::fit () override slot
Perform the fit algorithm.
Requests checks and updates prior to running a fit.
Definition at line 742 of file MuonFitPropertyBrowser.cpp.
fitRawDataClicked
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::fitRawDataClicked (bool enabled) override signal
Emitted when "fit to raw data" is changed.
Referenced by boolChanged().
functionUpdateAndFitRequested
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::functionUpdateAndFitRequested (bool sequential) override signal
Emitted when a fit or sequential fit is requested.
functionUpdateRequested
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::functionUpdateRequested () override signal
Emitted when function should be updated.
genCombinePeriodWindow()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::genCombinePeriodWindow () private
Definition at line 1689 of file MuonFitPropertyBrowser.cpp.
Referenced by generateBtnPressed().
generateBtnPressed
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::generateBtnPressed () slot
Definition at line 304 of file MuonFitPropertyBrowser.cpp.
References genCombinePeriodWindow().
Referenced by init().
genGroupWindow()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::genGroupWindow () private
Definition at line 1386 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged(), and groupBtnPressed().
genPeriodWindow()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::genPeriodWindow () private
Definition at line 1667 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged(), and periodBtnPressed().
getChosenGroups()
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::getChosenGroups () const
Returns a list of the selected groups (checked boxes)
Returns
:: list of selected groups
Definition at line 1335 of file MuonFitPropertyBrowser.cpp.
Referenced by updateGroupDisplay().
getChosenPeriods()
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::getChosenPeriods () const
Returns a list of the selected periods (checked boxes)
Returns
:: list of selected periods
Definition at line 1623 of file MuonFitPropertyBrowser.cpp.
Referenced by updatePeriodDisplay().
getFunction()
Mantid::API::IFunction_sptr MantidQt::MantidWidgets::MuonFitPropertyBrowser::getFunction () const inline override virtual
Get the fitting function.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 73 of file MuonFitPropertyBrowser.h.
getUnnormName()
std::string MantidQt::MantidWidgets::MuonFitPropertyBrowser::getUnnormName (const std::string wsName) private
Definition at line 621 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::rawData(), and TFExtension().
Referenced by doTFAsymmFit().
getWorkspaceNamesToFit()
std::vector< std::string > MantidQt::MantidWidgets::MuonFitPropertyBrowser::getWorkspaceNamesToFit () const inline override virtual
Get names of workspaces that are set to be fitted.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 83 of file MuonFitPropertyBrowser.h.
groupBoxClicked
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::groupBoxClicked () signal
Referenced by boolChanged().
groupBtnPressed
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::groupBtnPressed () slot
Definition at line 300 of file MuonFitPropertyBrowser.cpp.
References genGroupWindow().
Referenced by init().
hasGuess()
bool MantidQt::MantidWidgets::MuonFitPropertyBrowser::hasGuess () const override virtual
Whether a guess is plotted or not.
Returns whether or not a guess is plotted.
Returns
:: True if a plot guess is plotted, false if not.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 1260 of file MuonFitPropertyBrowser.cpp.
init()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::init () override virtual
Initialise the layout.
Initialise the muon fit property browser.
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 97 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty(), addGroupCheckbox(), clearChosenGroups(), MantidQt::MantidWidgets::FitPropertyBrowser::createEditors(), MantidQt::MantidWidgets::FitPropertyBrowser::currentItemChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::functionChanged(), generateBtnPressed(), MantidQt::MantidWidgets::FitPropertyBrowser::getAutoBackgroundString(), groupBtnPressed(), index, MantidQt::MantidWidgets::FitPropertyBrowser::initBasicLayout(), m_autoBackground, MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_browser, m_btnGroup, m_comboWindow, MantidQt::MantidWidgets::FitPropertyBrowser::m_costFunction, MantidQt::MantidWidgets::FitPropertyBrowser::m_costFunctions, MantidQt::MantidWidgets::FitPropertyBrowser::m_customSettingsGroup, MantidQt::MantidWidgets::FitPropertyBrowser::m_endX, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_evaluationType, MantidQt::MantidWidgets::FitPropertyBrowser::m_evaluationTypes, MantidQt::MantidWidgets::FitPropertyBrowser::m_functionsGroup, m_generateBtn, MantidQt::MantidWidgets::FitPropertyBrowser::m_groupManager, m_groupsToFit, m_groupsToFitOptions, m_groupWindow, MantidQt::MantidWidgets::FitPropertyBrowser::m_intManager, m_keepNorm, m_mainSplitter, MantidQt::MantidWidgets::FitPropertyBrowser::m_minimizer, MantidQt::MantidWidgets::FitPropertyBrowser::m_minimizers, m_multiFitSettingsGroup, m_normalization, MantidQt::MantidWidgets::FitPropertyBrowser::m_output, MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager, m_periodsToFit, m_periodsToFitOptions, m_periodWindow, MantidQt::MantidWidgets::FitPropertyBrowser::m_plotDiff, MantidQt::MantidWidgets::FitPropertyBrowser::m_rawData, m_reselectGroupBtn, m_reselectPeriodBtn, MantidQt::MantidWidgets::FitPropertyBrowser::m_settingsGroup, m_showGroup, m_showGroupValue, MantidQt::MantidWidgets::FitPropertyBrowser::m_showParamErrors, m_showPeriods, m_showPeriodValue, MantidQt::MantidWidgets::FitPropertyBrowser::m_startX, MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager, m_TFAsymmMode, m_widgetSplitter, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspace, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceIndex, periodBtnPressed(), MantidQt::MantidWidgets::FitPropertyBrowser::plotDiff(), setNormalization(), setTFAsymmMode(), tmp, MantidQt::MantidWidgets::FitPropertyBrowser::updateDecimals(), and MantidQt::MantidWidgets::FitPropertyBrowser::updateStructureTooltips().
isMultiFittingMode()
bool MantidQt::MantidWidgets::MuonFitPropertyBrowser::isMultiFittingMode () const override virtual
returns true if the browser is set to multi fitting mode
Returns true is the browser is set to multi fitting mode This works using the visibility state of the button group which is controlled in setMultiFittingMode.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 1107 of file MuonFitPropertyBrowser.cpp.
isPeriodValid()
bool MantidQt::MantidWidgets::MuonFitPropertyBrowser::isPeriodValid (const QString & name) private
Check if a period is valid.
Parameters
name :: [input] Name of period to add
Definition at line 1562 of file MuonFitPropertyBrowser.cpp.
References tmp, and value.
isWorkspaceValid()
bool MantidQt::MantidWidgets::MuonFitPropertyBrowser::isWorkspaceValid (Mantid::API::Workspace_sptr ws) const override private virtual
Check if the workspace can be used in the fit.
The accepted types are MatrixWorkspaces same size and that it isn't the generated raw file.
Parameters
ws :: The workspace
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 840 of file MuonFitPropertyBrowser.cpp.
outputName()
std::string MantidQt::MantidWidgets::MuonFitPropertyBrowser::outputName () const override virtual
Get output name.
Override in the case of simultaneous fits to use a special prefix.
Otherwise, use the parent class method.
Returns
:: output name for Fit algorithm
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 1047 of file MuonFitPropertyBrowser.cpp.
Referenced by doTFAsymmFit().
periodBoxClicked
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::periodBoxClicked () signal
Referenced by boolChanged().
periodBtnPressed
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::periodBtnPressed () slot
Definition at line 302 of file MuonFitPropertyBrowser.cpp.
References genPeriodWindow().
Referenced by init().
populateFunctionNames()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::populateFunctionNames () override private virtual
Get the registered function names.
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 590 of file MuonFitPropertyBrowser.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredBackgrounds, MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredFunctions, MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredOther, and MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredPeaks.
preFitChecksRequested
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::preFitChecksRequested (bool sequential) override signal
Emitted when fit is about to be run.
reselctGroupClicked
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::reselctGroupClicked (bool enabled) signal
runFit()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::runFit () override virtual
Run a non-sequential fit.
Creates an instance of Fit algorithm, sets its properties and launches it.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 747 of file MuonFitPropertyBrowser.cpp.
References observeFinish().
runSequentialFit()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::runSequentialFit () override virtual
Run a sequential fit.
Show sequential fit dialog.
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 820 of file MuonFitPropertyBrowser.cpp.
sequentialFit
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::sequentialFit () override slot
Open sequential fit dialog.
Requests checks and updates prior to running a sequential fit.
Definition at line 825 of file MuonFitPropertyBrowser.cpp.
sequentialFitRequested
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::sequentialFitRequested () signal
Emitted when sequential fit is requested by user.
setAllGroups()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAllGroups ()
Selects all groups.
Definition at line 1356 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged().
setAllGroupsOrPairs()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAllGroupsOrPairs (const bool isItGroup)
Sets the multifit mode to all groups or all pairs depending on if a group or pair is selected in the home tab.
Parameters
isItGroup :: [input] if it is a group (true)
Definition at line 1763 of file MuonFitPropertyBrowser.cpp.
References index.
setAllPairs()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAllPairs ()
Definition at line 1370 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged().
setAllPeriods()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAllPeriods ()
Selects all periods.
Definition at line 1407 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged().
setAvailableGroups()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAvailableGroups (const QStringList & groups)
Sets group names and updates checkboxes on UI By default sets all unchecked.
Parameters
groups :: [input] List of group names
Definition at line 1274 of file MuonFitPropertyBrowser.cpp.
setAvailablePeriods()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setAvailablePeriods (const QStringList & periods)
Sets period names and updates checkboxes on UI By default sets all unchecked.
Parameters
periods :: [input] List of period names
Definition at line 1459 of file MuonFitPropertyBrowser.cpp.
setChosenGroup()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setChosenGroup (const QString & group)
Selects a single group/pair.
Parameters
group :: [input] Group/pair to select
Definition at line 1305 of file MuonFitPropertyBrowser.cpp.
setChosenPeriods() [1/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setChosenPeriods (const QString & period)
Ticks the selected periods.
Parameters
period :: selected periods
Definition at line 1655 of file MuonFitPropertyBrowser.cpp.
setChosenPeriods() [2/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setChosenPeriods (const QStringList & chosenPeriods) private
Ticks the selected periods.
Parameters
chosenPeriods :: list of selected periods
Definition at line 1641 of file MuonFitPropertyBrowser.cpp.
setFitEnabled()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setFitEnabled (bool yes) override virtual
Enable/disable the Fit button;.
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 307 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionFit, and MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionSeqFit.
Referenced by checkFitEnabled().
setFitWorkspaces()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setFitWorkspaces (const std::string & input) private
Definition at line 853 of file MuonFitPropertyBrowser.cpp.
References Mantid::API::ExperimentInfo::copyExperimentInfoFrom().
setFunction()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setFunction (const Mantid::API::IFunction_sptr func) override virtual
Set function externally.
Called externally to set the function.
Parameters
func :: [input] Fit function to use
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 1026 of file MuonFitPropertyBrowser.cpp.
setGroupNames()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setGroupNames (const std::vector< std::string > groupNames)
Definition at line 1803 of file MuonFitPropertyBrowser.cpp.
setMultiFittingMode()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setMultiFittingMode (bool enabled) override virtual
Set multiple fitting mode on or off.
If turned off, all parts of the fit property browser are shown and all extra widgets (like the function browser or data selector) are hidden, so it looks just like it used to before the changes in Mantid 3.8. If turned on, the "Function" and "Data" sections of the fit property browser are hidden and the extra widgets are shown.
Parameters
enabled :: [input] Whether to turn this mode on or off
Implements MantidQt::MantidWidgets::IMuonFitFunctionModel.
Definition at line 1068 of file MuonFitPropertyBrowser.cpp.
setNormalization() [1/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization () protected
Definition at line 495 of file MuonFitPropertyBrowser.cpp.
References setNormalization(), and MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName().
Referenced by init(), and setNormalization().
setNormalization() [2/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization (const std::string & name)
Parameters
name :: the ws name to get normalization for
Returns
the normalization
Definition at line 500 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_normalization, m_normalizationValue, MantidQt::MantidWidgets::FitPropertyBrowser::rawData(), MantidQt::MantidWidgets::readMultipleNormalization(), and tmp.
setNumPeriods
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNumPeriods (size_t numPeriods) slot
Sets checkboxes for periods.
Parameters
numPeriods :: [input] Number of periods
Definition at line 1418 of file MuonFitPropertyBrowser.cpp.
setSimultaneousLabel()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setSimultaneousLabel (const std::string & label) inline override virtual
Set label for simultaneous fit results.
Implements MantidQt::MantidWidgets::IMuonFitDataModel.
Definition at line 81 of file MuonFitPropertyBrowser.h.
setSingleFitLabel()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setSingleFitLabel (const std::string & name)
sets the label for a single fit and selects the relevant group/pair
Parameters
name :: string of the ws
Definition at line 1735 of file MuonFitPropertyBrowser.cpp.
Referenced by doTFAsymmFit().
setTFAsymm()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setTFAsymm (bool state)
Definition at line 1806 of file MuonFitPropertyBrowser.cpp.
setTFAsymmMode()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setTFAsymmMode (bool enabled) private
Set TF asymmetry mode on or off.
If turned off, the fit property browser looks like Mantid 3.8. If turned on, the fit menu has an extra button and normalization is shown in the data table
Parameters
enabled :: [input] Whether to turn this mode on or off
Definition at line 1195 of file MuonFitPropertyBrowser.cpp.
Referenced by boolChanged(), and init().
setWorkspaceName()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceName (const QString & wsName) override virtual
Set the input workspace name.
Reimplemented from MantidQt::MantidWidgets::FitPropertyBrowser.
Definition at line 322 of file MuonFitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspace, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames, and MantidQt::MantidWidgets::FitPropertyBrowser::populateWorkspaceNames().
setWorkspaceNames()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceNames (const QStringList & wsNames) override virtual
Set list of workspaces to fit.
Set the list of workspaces to fit to the given list.
Parameters
wsNames :: [input] List of workspace names to fit
Implements MantidQt::MantidWidgets::IMuonFitDataModel.
Definition at line 1032 of file MuonFitPropertyBrowser.cpp.
showEvent()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::showEvent (QShowEvent * e) override protected
Connect to the AnalysisDataService when shown.
Definition at line 830 of file MuonFitPropertyBrowser.cpp.
TFExtension()
std::string MantidQt::MantidWidgets::MuonFitPropertyBrowser::TFExtension () const private
Definition at line 1215 of file MuonFitPropertyBrowser.cpp.
Referenced by getUnnormName().
TFPlot
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::TFPlot (QString wsName) signal
updateGroupDisplay()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::updateGroupDisplay () private
Sets the display for selected groups.
Definition at line 433 of file MuonFitPropertyBrowser.cpp.
References getChosenGroups(), MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_multiFitSettingsGroup, m_showGroup, and m_showGroupValue.
Referenced by boolChanged(), and enumChanged().
updatePeriodDisplay()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::updatePeriodDisplay () private
Sets the display for selected periods.
Definition at line 442 of file MuonFitPropertyBrowser.cpp.
References getChosenPeriods(), MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_multiFitSettingsGroup, m_periodsToFitOptions, m_showPeriods, m_showPeriodValue, and tmp.
Referenced by boolChanged(), and enumChanged().
updatePeriods [1/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::updatePeriods () slot
updates the period displays
Definition at line 1503 of file MuonFitPropertyBrowser.cpp.
updatePeriods() [2/2]
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::updatePeriods (const int j) private
updates the period displays and conserves the selection if selection is niot available default to all periods
Parameters
j :: [input] index of selection in combobox selected is an input for changing runs and preserving selection (list of selected periods) currently has a bug
Definition at line 1516 of file MuonFitPropertyBrowser.cpp.
updateTFPlot()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::updateTFPlot () private
Makes sure we have the TF plot in TFAsymm mode.
Definition at line 1219 of file MuonFitPropertyBrowser.cpp.
Referenced by enumChanged().
userChangedDataset()
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::userChangedDataset (int index) inline override virtual
User changed dataset index to fit.
Implements MantidQt::MantidWidgets::IMuonFitDataModel.
Definition at line 85 of file MuonFitPropertyBrowser.h.
References index.
userChangedDatasetIndex
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::userChangedDatasetIndex (int index) override signal
Emitted when dataset index to fit is changed.
workspacesToFitChanged
void MantidQt::MantidWidgets::MuonFitPropertyBrowser::workspacesToFitChanged (int n) override signal
Emitted when number of workspaces to fit is changed.
Member Data Documentation
m_autoBackground
QString MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_autoBackground private
Definition at line 233 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_btnGroup
QGroupBox* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_btnGroup private
Definition at line 223 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_comboWindow
QDialog* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_comboWindow private
Definition at line 226 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_functionBrowser
MantidQt::MantidWidgets::FunctionBrowser* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_functionBrowser private
Definition at line 227 of file MuonFitPropertyBrowser.h.
Referenced by doTFAsymmFit().
m_generateBtn
QPushButton* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_generateBtn private
Definition at line 222 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_groupBoxes
QMap<QString, QtProperty *> MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_groupBoxes private
Map of group names to checkboxes.
Definition at line 207 of file MuonFitPropertyBrowser.h.
Referenced by boolChanged(), and enumChanged().
m_groupsList
std::vector<std::string> MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_groupsList private
Definition at line 228 of file MuonFitPropertyBrowser.h.
m_groupsToFit
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_groupsToFit private
Definition at line 204 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), and init().
m_groupsToFitOptions
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_groupsToFitOptions private
Definition at line 205 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), and init().
m_groupWindow
QDialog* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_groupWindow private
Definition at line 224 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_isMultiFittingMode
bool MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_isMultiFittingMode private
Definition at line 231 of file MuonFitPropertyBrowser.h.
m_keepNorm
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_keepNorm private
Definition at line 201 of file MuonFitPropertyBrowser.h.
Referenced by boolChanged(), and init().
m_mainSplitter
QSplitter * MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_mainSplitter private
Definition at line 194 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_multiFitSettingsGroup
QtBrowserItem* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_multiFitSettingsGroup private
Definition at line 203 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), init(), updateGroupDisplay(), and updatePeriodDisplay().
m_negativeCombo
QLineEdit* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_negativeCombo private
Definition at line 218 of file MuonFitPropertyBrowser.h.
m_normalization
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_normalization private
Definition at line 199 of file MuonFitPropertyBrowser.h.
Referenced by init(), and setNormalization().
m_normalizationValue
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_normalizationValue private
Definition at line 200 of file MuonFitPropertyBrowser.h.
Referenced by setNormalization().
m_periodBoxes
QMap<QString, QtProperty *> MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_periodBoxes private
Map of group names to checkboxes.
Definition at line 214 of file MuonFitPropertyBrowser.h.
Referenced by boolChanged(), and enumChanged().
m_periodsToFit
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_periodsToFit private
Definition at line 211 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), and init().
m_periodsToFitOptions
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_periodsToFitOptions private
Definition at line 212 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), init(), and updatePeriodDisplay().
m_periodWindow
QDialog* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_periodWindow private
Definition at line 225 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_positiveCombo
QLineEdit* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_positiveCombo private
Definition at line 217 of file MuonFitPropertyBrowser.h.
m_reselectGroupBtn
QPushButton* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_reselectGroupBtn private
Definition at line 220 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), and init().
m_reselectPeriodBtn
QPushButton* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_reselectPeriodBtn private
Definition at line 221 of file MuonFitPropertyBrowser.h.
Referenced by enumChanged(), and init().
m_showGroup
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_showGroup private
Definition at line 208 of file MuonFitPropertyBrowser.h.
Referenced by init(), and updateGroupDisplay().
m_showGroupValue
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_showGroupValue private
Definition at line 209 of file MuonFitPropertyBrowser.h.
Referenced by init(), and updateGroupDisplay().
m_showPeriods
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_showPeriods private
Definition at line 215 of file MuonFitPropertyBrowser.h.
Referenced by init(), and updatePeriodDisplay().
m_showPeriodValue
QStringList MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_showPeriodValue private
Definition at line 216 of file MuonFitPropertyBrowser.h.
Referenced by init(), and updatePeriodDisplay().
m_simultaneousLabel
std::string MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_simultaneousLabel private
Label to use for simultaneous fits.
Definition at line 198 of file MuonFitPropertyBrowser.h.
m_TFAsymmMode
QtProperty* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_TFAsymmMode private
Definition at line 202 of file MuonFitPropertyBrowser.h.
Referenced by boolChanged(), executeFitMenu(), and init().
m_widgetSplitter
QSplitter* MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_widgetSplitter private
Splitter for additional widgets and splitter between this and browser.
Definition at line 194 of file MuonFitPropertyBrowser.h.
Referenced by init().
m_workspacesToFit
std::vector<std::string> MantidQt::MantidWidgets::MuonFitPropertyBrowser::m_workspacesToFit private
Names of workspaces to fit.
Definition at line 196 of file MuonFitPropertyBrowser.h.
Referenced by doTFAsymmFit().
SIMULTANEOUS_PREFIX
const std::string MantidQt::MantidWidgets::MuonFitPropertyBrowser::SIMULTANEOUS_PREFIX = {"MuonSimulFit_"} static
Prefix for simultaneous fit results.
Definition at line 79 of file MuonFitPropertyBrowser.h.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MuonFitPropertyBrowser.h
qt/widgets/common/src/MuonFitPropertyBrowser.cpp