Mantid: Framework/DataHandling/src/LoadRaw/byte_rel_comp.h File Reference
byte_rel_comp.h File Reference
Functions
int byte_rel_comp (const int *data_in, int n_in, char *data_out, int max_out, int &n_out)
int byte_rel_expn (const char *data_in, int n_in, int n_from, int *data_out, int n_out)
Function Documentation
byte_rel_comp()
int byte_rel_comp (const int * data_in, int n_in, char * data_out, int max_out, int & n_out)
Definition at line 36 of file byte_rel_comp.cpp.
References LARGE_NUMBER, and SUCCESS.
Referenced by ISISRAW::ioRAW().
byte_rel_expn()
int byte_rel_expn (const char * data_in, int n_in, int n_from, int * data_out, int n_out)
Definition at line 119 of file byte_rel_comp.cpp.
References SUCCESS.
Referenced by ISISRAW::ioRAW(), and ISISRAW2::readData().