Mantid: Mantid::API::IMDIterator Class Reference
Mantid::API::IMDIterator Class Reference abstract
This is an interface to an iterator of an IMDWorkspace.
#include <IMDIterator.h>
Public Member Functions
virtual std::vector< size_t > findNeighbourIndexes () const =0
Find neighbouring indexes vertex touching.
virtual std::vector< size_t > findNeighbourIndexesFaceTouching () const =0
Find neighbouring indexes face touching.
virtual Mantid::Kernel::VMD getCenter () const =0
Returns the position of the center of the box pointed to.
virtual size_t getDataSize () const =0
Get the size of the data (number of entries that will be iterated through)
virtual signal_t getError () const =0
Returns the total error for this box.
virtual int32_t getInnerDetectorID (size_t index) const =0
For a given event/point in this box, return the detector ID.
virtual signal_t getInnerError (size_t index) const =0
Returns the error of a given event.
virtual uint16_t getInnerExpInfoIndex (size_t index) const =0
For a given event/point in this box, return the associated experiment-info index.
virtual uint16_t getInnerGoniometerIndex (size_t index) const =0
For a given event/point in this box, return the goniometer index.
virtual coord_t getInnerPosition (size_t index, size_t dimension) const =0
Returns the position of a given event for a given dimension.
virtual signal_t getInnerSignal (size_t index) const =0
Returns the signal of a given event.
virtual bool getIsMasked () const =0
Returns true if masking is used.
virtual size_t getLinearIndex () const =0
Get the linear index.
Mantid::API::MDNormalization getNormalization () const
virtual signal_t getNormalizedError () const =0
Returns the normalized error for this box.
virtual signal_t getNormalizedSignal () const =0
Returns the normalized signal for this box.
virtual size_t getNumEvents () const =0
Returns the number of events/points contained in this box.
virtual signal_t getSignal () const =0
Returns the total signal for this box.
virtual std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices) const =0
Return a list of vertexes defining the volume pointed to.
virtual std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices, const size_t outDimensions, const bool *maskDim) const =0
Return a list of vertexes defining the volume pointed to, enable masking of dimensions.
IMDIterator ()
Default constructor.
virtual bool isWithinBounds (size_t index) const =0
Is index reachable by the iterator.
virtual void jumpTo (size_t index)=0
Jump to the index^th cell.
virtual bool next ()=0
Advance to the next cell.
virtual bool next (size_t skip)=0
Advance, skipping a certain number of cells.
void setNormalization (Mantid::API::MDNormalization normalization)
Set how the signal will be normalized when calling getNormalizedSignal()
virtual bool valid () const =0
Is the current position of the iterator valid?
virtual ~IMDIterator ()=default
Protected Attributes
Mantid::API::MDNormalization m_normalization
Normalization method for getNormalizedSignal()
Detailed Description
This is an interface to an iterator of an IMDWorkspace.
Author
Roman Tolchenov, Tessella Support Services plc
Date
15/03/2011
Definition at line 39 of file IMDIterator.h.
Constructor & Destructor Documentation
IMDIterator()
Mantid::API::IMDIterator::IMDIterator ()
Default constructor.
Definition at line 15 of file IMDIterator.cpp.
~IMDIterator()
virtual Mantid::API::IMDIterator::~IMDIterator () virtual default
Member Function Documentation
findNeighbourIndexes()
virtual std::vector< size_t > Mantid::API::IMDIterator::findNeighbourIndexes () const pure virtual
Find neighbouring indexes vertex touching.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
findNeighbourIndexesFaceTouching()
virtual std::vector< size_t > Mantid::API::IMDIterator::findNeighbourIndexesFaceTouching () const pure virtual
Find neighbouring indexes face touching.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getCenter()
virtual Mantid::Kernel::VMD Mantid::API::IMDIterator::getCenter () const pure virtual
Returns the position of the center of the box pointed to.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::MDAlgorithms::UserFunctionMD::functionMD(), and Mantid::Crystal::PeakBackground::isBackground().
getDataSize()
virtual size_t Mantid::API::IMDIterator::getDataSize () const pure virtual
Get the size of the data (number of entries that will be iterated through)
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getError()
virtual signal_t Mantid::API::IMDIterator::getError () const pure virtual
Returns the total error for this box.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerDetectorID()
virtual int32_t Mantid::API::IMDIterator::getInnerDetectorID (size_t index) const pure virtual
For a given event/point in this box, return the detector ID.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerError()
virtual signal_t Mantid::API::IMDIterator::getInnerError (size_t index) const pure virtual
Returns the error of a given event.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerExpInfoIndex()
virtual uint16_t Mantid::API::IMDIterator::getInnerExpInfoIndex (size_t index) const pure virtual
For a given event/point in this box, return the associated experiment-info index.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerGoniometerIndex()
virtual uint16_t Mantid::API::IMDIterator::getInnerGoniometerIndex (size_t index) const pure virtual
For a given event/point in this box, return the goniometer index.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerPosition()
virtual coord_t Mantid::API::IMDIterator::getInnerPosition (size_t index, size_t dimension) const pure virtual
Returns the position of a given event for a given dimension.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getInnerSignal()
virtual signal_t Mantid::API::IMDIterator::getInnerSignal (size_t index) const pure virtual
Returns the signal of a given event.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getIsMasked()
virtual bool Mantid::API::IMDIterator::getIsMasked () const pure virtual
Returns true if masking is used.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::DataObjects::SkipMaskedBins::keepGoing().
getLinearIndex()
virtual size_t Mantid::API::IMDIterator::getLinearIndex () const pure virtual
Get the linear index.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::Crystal::ConnectedComponentLabeling::calculateDisjointTree().
getNormalization()
Mantid::API::MDNormalization Mantid::API::IMDIterator::getNormalization () const
Returns
how the signal will be normalized when calling getNormalizedSignal()
Definition at line 25 of file IMDIterator.cpp.
References m_normalization.
getNormalizedError()
virtual signal_t Mantid::API::IMDIterator::getNormalizedError () const pure virtual
Returns the normalized error for this box.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getNormalizedSignal()
virtual signal_t Mantid::API::IMDIterator::getNormalizedSignal () const pure virtual
Returns the normalized signal for this box.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::Crystal::HardThresholdBackground::isBackground().
getNumEvents()
virtual size_t Mantid::API::IMDIterator::getNumEvents () const pure virtual
Returns the number of events/points contained in this box.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getSignal()
virtual signal_t Mantid::API::IMDIterator::getSignal () const pure virtual
Returns the total signal for this box.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getVertexesArray() [1/2]
virtual std::unique_ptr< coord_t[]> Mantid::API::IMDIterator::getVertexesArray (size_t & numVertices) const pure virtual
Return a list of vertexes defining the volume pointed to.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
getVertexesArray() [2/2]
virtual std::unique_ptr< coord_t[]> Mantid::API::IMDIterator::getVertexesArray (size_t & numVertices, const size_t outDimensions, const bool * maskDim) const pure virtual
Return a list of vertexes defining the volume pointed to, enable masking of dimensions.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
isWithinBounds()
virtual bool Mantid::API::IMDIterator::isWithinBounds (size_t index) const pure virtual
Is index reachable by the iterator.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
jumpTo()
virtual void Mantid::API::IMDIterator::jumpTo (size_t index) pure virtual
Jump to the index^th cell.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::Crystal::ConnectedComponentLabeling::calculateDisjointTree().
next() [1/2]
virtual bool Mantid::API::IMDIterator::next () pure virtual
Advance to the next cell.
If the current cell is the last one in the workspace do nothing and return false.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Referenced by Mantid::Crystal::ConnectedComponentLabeling::calculateDisjointTree().
next() [2/2]
virtual bool Mantid::API::IMDIterator::next (size_t skip) pure virtual
Advance, skipping a certain number of cells.
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
setNormalization()
void Mantid::API::IMDIterator::setNormalization (Mantid::API::MDNormalization normalization)
Set how the signal will be normalized when calling getNormalizedSignal()
Parameters
normalization :: method to use
Definition at line 21 of file IMDIterator.cpp.
References m_normalization.
Referenced by Mantid::Crystal::HardThresholdBackground::configureIterator().
valid()
virtual bool Mantid::API::IMDIterator::valid () const pure virtual
Is the current position of the iterator valid?
Implemented in Mantid::API::MatrixWorkspaceMDIterator, Mantid::DataObjects::MDBoxIterator, and Mantid::DataObjects::MDHistoWorkspaceIterator.
Member Data Documentation
m_normalization
Mantid::API::MDNormalization Mantid::API::IMDIterator::m_normalization protected
Normalization method for getNormalizedSignal()
Definition at line 125 of file IMDIterator.h.
Referenced by getNormalization(), Mantid::API::MatrixWorkspaceMDIterator::getNormalizedError(), Mantid::DataObjects::MDHistoWorkspaceIterator::getNormalizedError(), Mantid::API::MatrixWorkspaceMDIterator::getNormalizedSignal(), Mantid::DataObjects::MDHistoWorkspaceIterator::getNormalizedSignal(), and setNormalization().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IMDIterator.h
Framework/API/src/IMDIterator.cpp