Mantid: MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter Class Reference
MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter Class Reference
#include <QtStandardItemTreeAdapter.h>
Public Member Functions
QModelIndexForMainModel appendChildRow (QModelIndexForMainModel const &parent, std::vector< Cell > const &cells)
QModelIndexForMainModel appendEmptyChildRow (QModelIndexForMainModel const &parent)
QModelIndexForMainModel appendEmptySiblingRow (QModelIndexForMainModel const &index)
QModelIndexForMainModel appendSiblingRow (QModelIndexForMainModel const &index, std::vector< Cell > const &cells)
Cell cellFromCellIndex (QModelIndexForMainModel const &index) const
std::vector< Cell > cellsAtRow (QModelIndexForMainModel const &firstCellIndex) const
std::vector< Cell > emptyRow (int columnCount) const
template<typename Action >
void enumerateCellsInRow (QModelIndexForMainModel const &startIndex, int columns, Action const &action) const
Enumerates the first columnCount number of cells to the right of startAtCell, moving left to right.
QModelIndexForMainModel insertChildRow (QModelIndexForMainModel const &parent, int row, std::vector< Cell > const &cells)
QModelIndexForMainModel insertEmptyChildRow (QModelIndexForMainModel const &parent, int column)
QtStandardItemTreeModelAdapter (QStandardItemModel &model, Cell emptyCellStyle)
void removeRowFrom (QModelIndexForMainModel const &index)
QModelIndexForMainModel rootIndex () const
void setCellAtCellIndex (QModelIndexForMainModel const &index, Cell const &newCellProperties)
void setCellsAtRow (QModelIndexForMainModel const &rowIndex, std::vector< Cell > const &cells)
Private Member Functions
QList< QStandardItem * > rowItemsFromCells (std::vector< Cell > const &cells)
Private Attributes
Cell m_emptyCellStyle
QStandardItemModel & m_model
Detailed Description
Definition at line 23 of file QtStandardItemTreeAdapter.h.
Constructor & Destructor Documentation
QtStandardItemTreeModelAdapter()
MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::QtStandardItemTreeModelAdapter (QStandardItemModel & model, Cell emptyCellStyle)
Definition at line 17 of file QtStandardItemTreeAdapter.cpp.
Member Function Documentation
appendChildRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendChildRow (QModelIndexForMainModel const & parent, std::vector< Cell > const & cells)
Definition at line 45 of file QtStandardItemTreeAdapter.cpp.
References MantidQt::MantidWidgets::Batch::firstCellOnRowOf(), MantidQt::MantidWidgets::Batch::lastChildRowOf(), m_model, MantidQt::MantidWidgets::Batch::modelItemFromIndex(), rowItemsFromCells(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf(), appendEmptyChildRow(), and appendSiblingRow().
appendEmptyChildRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptyChildRow (QModelIndexForMainModel const & parent)
Definition at line 41 of file QtStandardItemTreeAdapter.cpp.
References appendChildRow(), emptyRow(), and m_model.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtChildRow(), MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf(), and appendEmptySiblingRow().
appendEmptySiblingRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptySiblingRow (QModelIndexForMainModel const & index)
Definition at line 30 of file QtStandardItemTreeAdapter.cpp.
References appendEmptyChildRow(), and index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult(), and MantidQt::MantidWidgets::Batch::JobTreeView::findOrMakeCellBelow().
appendSiblingRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendSiblingRow (QModelIndexForMainModel const & index, std::vector< Cell > const & cells)
Definition at line 35 of file QtStandardItemTreeAdapter.cpp.
References appendChildRow(), and index.
cellFromCellIndex()
Cell MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellFromCellIndex (QModelIndexForMainModel const & index) const
Definition at line 103 of file QtStandardItemTreeAdapter.cpp.
References MantidQt::MantidWidgets::Batch::extractCellPropertiesFromItem(), index, m_model, and MantidQt::MantidWidgets::Batch::modelItemFromIndex().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::cellAt(), and MantidQt::MantidWidgets::Batch::JobTreeView::commitData().
cellsAtRow()
std::vector< Cell > MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellsAtRow (QModelIndexForMainModel const & firstCellIndex) const
Definition at line 93 of file QtStandardItemTreeAdapter.cpp.
References enumerateCellsInRow(), and m_model.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::cellsAt().
emptyRow()
std::vector< Cell > MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::emptyRow (int columnCount) const
Definition at line 65 of file QtStandardItemTreeAdapter.cpp.
References m_emptyCellStyle.
Referenced by appendEmptyChildRow(), and insertEmptyChildRow().
enumerateCellsInRow()
template<typename Action > void MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::enumerateCellsInRow (QModelIndexForMainModel const & startIndex, int columns, Action const & action) const
Enumerates the first columnCount number of cells to the right of startAtCell, moving left to right.
Definition at line 63 of file QtStandardItemTreeAdapter.h.
References MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::row(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::sibling().
Referenced by cellsAtRow(), MantidQt::MantidWidgets::Batch::JobTreeView::closeAnyOpenEditorsOnUneditableCells(), and setCellsAtRow().
insertChildRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::insertChildRow (QModelIndexForMainModel const & parent, int row, std::vector< Cell > const & cells)
Definition at line 53 of file QtStandardItemTreeAdapter.cpp.
References m_model, MantidQt::MantidWidgets::Batch::modelItemFromIndex(), rowItemsFromCells(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf(), and insertEmptyChildRow().
insertEmptyChildRow()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::insertEmptyChildRow (QModelIndexForMainModel const & parent, int column)
Definition at line 60 of file QtStandardItemTreeAdapter.cpp.
References emptyRow(), insertChildRow(), and m_model.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf().
removeRowFrom()
void MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::removeRowFrom (QModelIndexForMainModel const & index)
Definition at line 22 of file QtStandardItemTreeAdapter.cpp.
References index, and m_model.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::removeRowAt().
rootIndex()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::rootIndex () const
Definition at line 20 of file QtStandardItemTreeAdapter.cpp.
rowItemsFromCells()
QList< QStandardItem * > MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::rowItemsFromCells (std::vector< Cell > const & cells) private
Definition at line 83 of file QtStandardItemTreeAdapter.cpp.
References MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem().
Referenced by appendChildRow(), and insertChildRow().
setCellAtCellIndex()
void MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellAtCellIndex (QModelIndexForMainModel const & index, Cell const & newCellProperties)
Definition at line 69 of file QtStandardItemTreeAdapter.cpp.
References MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), m_model, and MantidQt::MantidWidgets::Batch::modelItemFromIndex().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::setCellAt().
setCellsAtRow()
void MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellsAtRow (QModelIndexForMainModel const & rowIndex, std::vector< Cell > const & cells)
Definition at line 74 of file QtStandardItemTreeAdapter.cpp.
References enumerateCellsInRow(), and m_model.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::setCellsAt().
Member Data Documentation
m_emptyCellStyle
Cell MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::m_emptyCellStyle private
Definition at line 55 of file QtStandardItemTreeAdapter.h.
Referenced by emptyRow().
m_model
QStandardItemModel& MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::m_model private
Definition at line 54 of file QtStandardItemTreeAdapter.h.
Referenced by appendChildRow(), appendEmptyChildRow(), cellFromCellIndex(), cellsAtRow(), insertChildRow(), insertEmptyChildRow(), removeRowFrom(), setCellAtCellIndex(), and setCellsAtRow().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/QtStandardItemTreeAdapter.h
qt/widgets/common/src/Batch/QtStandardItemTreeAdapter.cpp