Mantid: Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp File Reference
MatrixWorkspace.cpp File Reference
#include "MantidAPI/MatrixWorkspace.h"
#include "MantidAPI/Axis.h"
#include "MantidAPI/Run.h"
#include "MantidAPI/WorkspaceOpOverloads.h"
#include "MantidGeometry/IDetector.h"
#include "MantidHistogramData/HistogramY.h"
#include "MantidIndexing/IndexInfo.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/api/CloneMatrixWorkspace.h"
#include "MantidPythonInterface/api/RegisterWorkspacePtrToPython.h"
#include "MantidPythonInterface/core/Converters/NDArrayToVector.h"
#include "MantidPythonInterface/core/Converters/PySequenceToVector.h"
#include "MantidPythonInterface/core/Converters/WrapWithNDArray.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include "MantidPythonInterface/core/Policies/VectorToNumpy.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/implicit.hpp>
#include <boost/python/list.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/suite/indexing/map_indexing_suite.hpp>
#include <boost/python/tuple.hpp>
#include <numpy/arrayobject.h>
Macros
#define NO_IMPORT_ARRAY
#define PY_ARRAY_UNIQUE_SYMBOL API_ARRAY_API
Functions
void export_MatrixWorkspace ()
Python exports of the Mantid::API::MatrixWorkspace class.
Macro Definition Documentation
NO_IMPORT_ARRAY
#define NO_IMPORT_ARRAY
Definition at line 36 of file MatrixWorkspace.cpp.
PY_ARRAY_UNIQUE_SYMBOL
#define PY_ARRAY_UNIQUE_SYMBOL API_ARRAY_API
Definition at line 35 of file MatrixWorkspace.cpp.
Function Documentation
export_MatrixWorkspace()
void export_MatrixWorkspace ()
Python exports of the Mantid::API::MatrixWorkspace class.
Typedef to remove const qualifier on input detector shared_ptr. See Policies/RemoveConst.h for more details
Definition at line 312 of file MatrixWorkspace.cpp.
References Mantid::API::MatrixWorkspace::axes(), Mantid::API::MatrixWorkspace::blocksize(), Mantid::PythonInterface::cloneDx(), Mantid::PythonInterface::cloneE(), Mantid::PythonInterface::cloneX(), Mantid::PythonInterface::cloneY(), Mantid::API::MatrixWorkspace::dataDx(), Mantid::API::MatrixWorkspace::dataE(), Mantid::API::MatrixWorkspace::dataX(), Mantid::API::MatrixWorkspace::dataY(), Mantid::API::MatrixWorkspace::detectorSignedTwoTheta(), Mantid::API::MatrixWorkspace::detectorTwoTheta(), Mantid::API::equals(), Mantid::API::MatrixWorkspace::getAxis(), Mantid::API::MatrixWorkspace::getDetector(), Mantid::API::MatrixWorkspace::getIndexFromSpectrumNumber(), Mantid::API::MatrixWorkspace::getMaxNumberBins(), Mantid::API::MatrixWorkspace::getNumberBins(), Mantid::API::MatrixWorkspace::getNumberHistograms(), Mantid::API::MatrixWorkspace::getSpectrum(), Mantid::API::MatrixWorkspace::hasAnyMaskedBins(), Mantid::API::MatrixWorkspace::hasDx(), Mantid::API::MatrixWorkspace::hasMaskedBins(), Mantid::API::MatrixWorkspace::isCommonBins(), Mantid::API::MatrixWorkspace::isCommonLogBins(), Mantid::API::MatrixWorkspace::isDistribution(), Mantid::API::MatrixWorkspace::isHistogramData(), Mantid::API::MatrixWorkspace::isRaggedWorkspace(), Mantid::API::ExperimentInfo::mutableRun(), Mantid::API::MatrixWorkspace::readDx(), Mantid::API::MatrixWorkspace::readE(), Mantid::API::MatrixWorkspace::readX(), Mantid::API::MatrixWorkspace::readY(), Mantid::API::MatrixWorkspace::setDistribution(), Mantid::API::MatrixWorkspace::setYUnit(), Mantid::API::MatrixWorkspace::setYUnitLabel(), Mantid::API::MatrixWorkspace::yIndexOfX(), Mantid::API::MatrixWorkspace::YUnit(), and Mantid::API::MatrixWorkspace::YUnitLabel().