Mantid: MantidQt::MantidWidgets::Batch::FilteredTreeModel Class Reference
MantidQt::MantidWidgets::Batch::FilteredTreeModel Class Reference
#include <FilteredTreeModel.h>
Public Member Functions
FilteredTreeModel (RowLocationAdapter rowLocation, QObject *parent=nullptr)
bool isReset () const
void resetPredicate ()
RowLocation rowLocationAt (QModelIndex const &index) const
void setPredicate (std::unique_ptr< RowPredicate > predicate)
Protected Member Functions
bool filterAcceptsRow (int row, const QModelIndex &parent) const override
Private Attributes
std::unique_ptr< RowPredicate > m_predicate
RowLocationAdapter m_rowLocation
Detailed Description
Definition at line 22 of file FilteredTreeModel.h.
Constructor & Destructor Documentation
FilteredTreeModel()
MantidQt::MantidWidgets::Batch::FilteredTreeModel::FilteredTreeModel (RowLocationAdapter rowLocation, QObject * parent = nullptr)
Definition at line 11 of file FilteredTreeModel.cpp.
References resetPredicate().
Member Function Documentation
filterAcceptsRow()
bool MantidQt::MantidWidgets::Batch::FilteredTreeModel::filterAcceptsRow (int row, const QModelIndex & parent) const override protected
Definition at line 32 of file FilteredTreeModel.cpp.
References filterAcceptsRow(), index, m_predicate, and rowLocationAt().
Referenced by filterAcceptsRow().
isReset()
bool MantidQt::MantidWidgets::Batch::FilteredTreeModel::isReset () const
Definition at line 21 of file FilteredTreeModel.cpp.
References m_predicate.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::hasFilter().
resetPredicate()
void MantidQt::MantidWidgets::Batch::FilteredTreeModel::resetPredicate ()
Definition at line 16 of file FilteredTreeModel.cpp.
References m_predicate.
Referenced by FilteredTreeModel(), and MantidQt::MantidWidgets::Batch::JobTreeView::resetFilter().
rowLocationAt()
RowLocation MantidQt::MantidWidgets::Batch::FilteredTreeModel::rowLocationAt (QModelIndex const & index) const
Definition at line 28 of file FilteredTreeModel.cpp.
References MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), MantidQt::MantidWidgets::Batch::fromMainModel(), index, and m_rowLocation.
Referenced by filterAcceptsRow().
setPredicate()
void MantidQt::MantidWidgets::Batch::FilteredTreeModel::setPredicate (std::unique_ptr< RowPredicate > predicate)
Definition at line 23 of file FilteredTreeModel.cpp.
References m_predicate.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::filterRowsBy().
Member Data Documentation
m_predicate
std::unique_ptr<RowPredicate> MantidQt::MantidWidgets::Batch::FilteredTreeModel::m_predicate private
Definition at line 34 of file FilteredTreeModel.h.
Referenced by filterAcceptsRow(), isReset(), resetPredicate(), and setPredicate().
m_rowLocation
RowLocationAdapter MantidQt::MantidWidgets::Batch::FilteredTreeModel::m_rowLocation private
Definition at line 35 of file FilteredTreeModel.h.
Referenced by rowLocationAt().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/FilteredTreeModel.h
qt/widgets/common/src/Batch/FilteredTreeModel.cpp