Mantid: MantidQt::MantidWidgets::Batch::JobTreeView Class Reference
MantidQt::MantidWidgets::Batch::JobTreeView Class Reference
#include <JobTreeView.h>
Public Member Functions
void appendAllUnselectedDescendants (QModelIndexList &selectedRows, QModelIndex const &index) const
void appendAndEditAtChildRow () override
void appendAndEditAtRowBelow () override
RowLocation appendChildRowOf (RowLocation const &parent) override
RowLocation appendChildRowOf (RowLocation const &parentLocation, std::vector< Cell > const &rowText) override
void appendSubtreeAt (RowLocation const &parent, Subtree const &subtree) override
void appendSubtreesAt (RowLocation const &parent, std::vector< Subtree > subtrees) override
Cell cellAt (RowLocation location, int column) const override
std::vector< Cell > cellsAt (RowLocation const &location) const override
void clearSelection () override
void collapseAll () override
int currentColumn () const override
Cell deadCell () const override
void editAtRowAbove () override
void expandAll () override
void filterRowsBy (RowPredicate *predicate) override
void filterRowsBy (std::unique_ptr< RowPredicate > predicate) override
QModelIndexList findImplicitlySelected (QModelIndexList const &selectedRows) const
bool hasFilter () const override
bool hasNoSelectedDescendants (QModelIndex const &index) const
RowLocation insertChildRowOf (RowLocation const &parent, int beforeRow) override
RowLocation insertChildRowOf (RowLocation const &parent, int beforeRow, std::vector< Cell > const &rowText) override
void insertSubtreeAt (RowLocation const &parent, int index, Subtree const &subtree) override
bool isOnlyChildOfRoot (RowLocation const &location) const override
JobTreeView (QStringList const &columnHeadings, Cell const &defaultCellStyle, QWidget *parent=nullptr)
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) override
void removeAllRows () override
void removeRowAt (RowLocation const &location) override
void removeRows (std::vector< RowLocation > rowsToRemove) override
void replaceRows (std::vector< RowLocation > replacementPoints, std::vector< Subtree > replacements) override
void replaceSubtreeAt (RowLocation const &rootToRemove, Subtree const &toInsert) override
void resetFilter () override
std::vector< RowLocation > selectedRowLocations () const override
boost::optional< std::vector< RowLocation > > selectedSubtreeRoots () const override
boost::optional< std::vector< Subtree > > selectedSubtrees () const override
void setCellAt (RowLocation location, int column, Cell const &cellText) override
void setCellsAt (RowLocation const &location, std::vector< Cell > const &rowText) override
void setHintsForColumn (int column, HintStrategy *hintStrategy) override
void setHintsForColumn (int column, std::unique_ptr< HintStrategy > hintStrategy) override
void subscribe (JobTreeViewSubscriber *subscriber) override
Public Member Functions inherited from MantidQt::MantidWidgets::Batch::IJobTreeView
virtual void appendAndEditAtChildRow ()=0
virtual void appendAndEditAtRowBelow ()=0
virtual RowLocation appendChildRowOf (RowLocation const &parent)=0
virtual RowLocation appendChildRowOf (RowLocation const &parentLocation, std::vector< Cell > const &rowText)=0
virtual void appendSubtreeAt (RowLocation const &parent, Subtree const &subtree)=0
virtual void appendSubtreesAt (RowLocation const &parent, std::vector< Subtree > subtrees)=0
virtual Cell cellAt (RowLocation location, int column) const =0
virtual std::vector< Cell > cellsAt (RowLocation const &location) const =0
virtual void clearSelection ()=0
virtual void collapseAll ()=0
virtual int currentColumn () const =0
virtual Cell deadCell () const =0
virtual void editAtRowAbove ()=0
virtual void expandAll ()=0
virtual void filterRowsBy (RowPredicate *predicate)=0
virtual void filterRowsBy (std::unique_ptr< RowPredicate > predicate)=0
virtual bool hasFilter () const =0
virtual RowLocation insertChildRowOf (RowLocation const &parent, int beforeRow)=0
virtual RowLocation insertChildRowOf (RowLocation const &parent, int beforeRow, std::vector< Cell > const &rowText)=0
virtual void insertSubtreeAt (RowLocation const &parent, int index, Subtree const &subtree)=0
virtual bool isOnlyChildOfRoot (RowLocation const &location) const =0
virtual void removeAllRows ()=0
virtual void removeRowAt (RowLocation const &location)=0
virtual void removeRows (std::vector< RowLocation > rowsToRemove)=0
virtual void replaceRows (std::vector< RowLocation > replacementPoints, std::vector< Subtree > replacements)=0
virtual void replaceSubtreeAt (RowLocation const &rootToRemove, Subtree const &toInsert)=0
virtual void resetFilter ()=0
virtual std::vector< RowLocation > selectedRowLocations () const =0
virtual boost::optional< std::vector< RowLocation > > selectedSubtreeRoots () const =0
virtual boost::optional< std::vector< Subtree > > selectedSubtrees () const =0
virtual void setCellAt (RowLocation location, int column, Cell const &cellText)=0
virtual void setCellsAt (RowLocation const &location, std::vector< Cell > const &rowText)=0
virtual void setHintsForColumn (int column, HintStrategy *hintStrategy)=0
virtual void setHintsForColumn (int column, std::unique_ptr< HintStrategy > hintStrategy)=0
virtual void subscribe (JobTreeViewSubscriber *subscriber)=0
virtual ~IJobTreeView ()=default
Protected Slots
void commitData (QWidget *) override
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected) override
Protected Member Functions
void appendAndEditAtChildRowRequested ()
void appendAndEditAtRowBelowRequested ()
void copySelectedRequested ()
void cutSelectedRequested ()
bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event) override
void editAtRowAboveRequested ()
void enableFiltering ()
void keyPressEvent (QKeyEvent *event) override
void pasteSelectedRequested ()
void removeSelectedRequested ()
void setHeaderLabels (QStringList const &columnHeadings)
Private Member Functions
QModelIndex applyNavigationResult (QtTreeCursorNavigationResult const &result)
void closeAnyOpenEditorsOnUneditableCells (QModelIndexForMainModel const &firstCellOnRow, std::vector< Cell > const &cells)
void closeEditorIfCellIsUneditable (QModelIndexForMainModel const &cellIndex, Cell const &cell)
void closeEditorIfOpenAtCell (QModelIndexForFilteredModel const &cellIndex)
void editAt (QModelIndexForFilteredModel const &index)
QModelIndexForFilteredModel expanded (QModelIndexForFilteredModel const &index)
std::pair< QModelIndexForFilteredModel, bool > findOrMakeCellBelow (QModelIndexForFilteredModel const &index)
QModelIndexForFilteredModel fromFilteredModel (QModelIndex const &filteredModelIndex) const
QModelIndexForMainModel fromMainModel (QModelIndex const &mainModelIndex) const
bool hasEditorOpen () const
bool indexesAreOnSameRow (QModelIndex const &a, QModelIndex const &b) const
bool isBeingEdited (QModelIndexForFilteredModel const &cellIndex) const
bool isEditable (const QModelIndex &index) const
bool isOnlyChild (QModelIndexForMainModel const &index) const
bool isOnlyChildOfRoot (QModelIndexForMainModel const &index) const
QModelIndexForFilteredModel mapToFilteredModel (QModelIndexForMainModel const &mainModelIndex) const
QModelIndexForMainModel mapToMainModel (QModelIndexForFilteredModel const &filteredModelIndex) const
QtTreeCursorNavigationResult moveNextUntilEditable (QModelIndex const &startingPoint)
QModelIndex movePreviousUntilEditable (QModelIndex const &startingPoint)
QtTreeCursorNavigation navigation () const
RowLocationAdapter rowLocation () const
bool rowRemovalWouldBeIneffective (QModelIndexForMainModel const &indexToRemove) const
QModelIndex siblingIfExistsElseParent (QModelIndex const &index) const
Private Attributes
QtStandardItemTreeModelAdapter m_adaptedMainModel
FilteredTreeModel m_filteredModel
bool m_hasEditorOpen
QModelIndexForMainModel m_lastEdited
QStandardItemModel m_mainModel
JobTreeViewSubscriber * m_notifyee
Static Private Attributes
static Cell const g_deadCell = Cell("", "white", 0, "transparent", 0, false)
Detailed Description
Definition at line 29 of file JobTreeView.h.
Constructor & Destructor Documentation
JobTreeView()
MantidQt::MantidWidgets::Batch::JobTreeView::JobTreeView (QStringList const & columnHeadings, Cell const & defaultCellStyle, QWidget * parent = nullptr)
Definition at line 30 of file JobTreeView.cpp.
References enableFiltering(), m_filteredModel, m_mainModel, and setHeaderLabels().
Member Function Documentation
appendAllUnselectedDescendants()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendAllUnselectedDescendants (QModelIndexList & selectedRows, QModelIndex const & index) const
Definition at line 119 of file JobTreeView.cpp.
References appendAllUnselectedDescendants(), index, and m_filteredModel.
Referenced by appendAllUnselectedDescendants(), and findImplicitlySelected().
appendAndEditAtChildRow()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtChildRow () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 421 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptyChildRow(), editAt(), expanded(), fromFilteredModel(), m_adaptedMainModel, m_notifyee, mapToFilteredModel(), mapToMainModel(), MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRowInserted(), resetFilter(), and rowLocation().
appendAndEditAtChildRowRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtChildRowRequested () protected
Definition at line 163 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyAppendAndEditAtChildRowRequested().
Referenced by keyPressEvent().
appendAndEditAtRowBelow()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtRowBelow () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 429 of file JobTreeView.cpp.
References editAt(), findOrMakeCellBelow(), fromFilteredModel(), index, m_mainModel, m_notifyee, mapToMainModel(), MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRowInserted(), and rowLocation().
appendAndEditAtRowBelowRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendAndEditAtRowBelowRequested () protected
Definition at line 165 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyAppendAndEditAtRowBelowRequested().
Referenced by keyPressEvent().
appendChildRowOf() [1/2]
RowLocation MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf (RowLocation const & parent) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 364 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptyChildRow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), m_adaptedMainModel, and rowLocation().
Referenced by removeAllRows().
appendChildRowOf() [2/2]
RowLocation MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf (RowLocation const & parentLocation, std::vector< Cell > const & rowText) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 368 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendChildRow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), g_deadCell, MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), m_adaptedMainModel, m_mainModel, MantidQt::MantidWidgets::Batch::paddedCellsToWidth(), and rowLocation().
appendSubtreeAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendSubtreeAt (RowLocation const & parent, Subtree const & subtree) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 250 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), insertSubtreeAt(), m_mainModel, and rowLocation().
Referenced by appendSubtreesAt(), and replaceRows().
appendSubtreesAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::appendSubtreesAt (RowLocation const & parent, std::vector< Subtree > subtrees) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 245 of file JobTreeView.cpp.
References appendSubtreeAt().
applyNavigationResult()
QModelIndex MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult (QtTreeCursorNavigationResult const & result) private
Definition at line 531 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptySiblingRow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), expanded(), MantidQt::MantidWidgets::Batch::firstCellOnRowOf(), fromFilteredModel(), fromMainModel(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexIfExistsAt(), m_adaptedMainModel, m_notifyee, mapToFilteredModel(), mapToMainModel(), MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRowInserted(), resetFilter(), rowLocation(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by moveCursor().
cellAt()
Cell MantidQt::MantidWidgets::Batch::JobTreeView::cellAt (RowLocation location, int column) const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 183 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellFromCellIndex(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), m_adaptedMainModel, and rowLocation().
cellsAt()
std::vector< Cell > MantidQt::MantidWidgets::Batch::JobTreeView::cellsAt (RowLocation const & location) const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 208 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellsAtRow(), m_adaptedMainModel, and rowLocation().
clearSelection()
void MantidQt::MantidWidgets::Batch::JobTreeView::clearSelection () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 382 of file JobTreeView.cpp.
Referenced by removeAllRows().
closeAnyOpenEditorsOnUneditableCells()
void MantidQt::MantidWidgets::Batch::JobTreeView::closeAnyOpenEditorsOnUneditableCells (QModelIndexForMainModel const & firstCellOnRow, std::vector< Cell > const & cells) private
Definition at line 212 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::enumerateCellsInRow(), m_adaptedMainModel, and m_mainModel.
Referenced by setCellsAt().
closeEditorIfCellIsUneditable()
void MantidQt::MantidWidgets::Batch::JobTreeView::closeEditorIfCellIsUneditable (QModelIndexForMainModel const & cellIndex, Cell const & cell) private
Definition at line 197 of file JobTreeView.cpp.
References closeEditorIfOpenAtCell(), MantidQt::MantidWidgets::Batch::Cell::isEditable(), and mapToFilteredModel().
Referenced by setCellAt().
closeEditorIfOpenAtCell()
void MantidQt::MantidWidgets::Batch::JobTreeView::closeEditorIfOpenAtCell (QModelIndexForFilteredModel const & cellIndex) private
Definition at line 192 of file JobTreeView.cpp.
References isBeingEdited(), MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::isValid(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by closeEditorIfCellIsUneditable().
collapseAll()
void MantidQt::MantidWidgets::Batch::JobTreeView::collapseAll () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 386 of file JobTreeView.cpp.
commitData
void MantidQt::MantidWidgets::Batch::JobTreeView::commitData (QWidget * editor) override protected slot
Definition at line 43 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellFromCellIndex(), MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::column(), MantidQt::MantidWidgets::Batch::Cell::contentText(), editAt(), fromFilteredModel(), m_adaptedMainModel, m_hasEditorOpen, m_lastEdited, m_notifyee, MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCellTextChanged(), and rowLocation().
copySelectedRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::copySelectedRequested () protected
Definition at line 171 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCopyRowsRequested().
Referenced by keyPressEvent().
currentColumn()
int MantidQt::MantidWidgets::Batch::JobTreeView::currentColumn () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 565 of file JobTreeView.cpp.
cutSelectedRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::cutSelectedRequested () protected
Definition at line 173 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyCutRowsRequested().
Referenced by keyPressEvent().
deadCell()
Cell MantidQt::MantidWidgets::Batch::JobTreeView::deadCell () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 87 of file JobTreeView.cpp.
References g_deadCell.
edit()
bool MantidQt::MantidWidgets::Batch::JobTreeView::edit (const QModelIndex & index, EditTrigger trigger, QEvent * event) override protected
Definition at line 81 of file JobTreeView.cpp.
References fromFilteredModel(), index, m_hasEditorOpen, m_lastEdited, and mapToMainModel().
Referenced by editAt().
editAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::editAt (QModelIndexForFilteredModel const & index) private
Definition at line 374 of file JobTreeView.cpp.
References edit(), index, and isEditable().
Referenced by appendAndEditAtChildRow(), appendAndEditAtRowBelow(), commitData(), editAtRowAbove(), and insertChildRowOf().
editAtRowAbove()
void MantidQt::MantidWidgets::Batch::JobTreeView::editAtRowAbove () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 445 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::above(), editAt(), fromFilteredModel(), and MantidQt::MantidWidgets::Batch::hasRowAbove().
editAtRowAboveRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::editAtRowAboveRequested () protected
Definition at line 167 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyEditAtRowAboveRequested().
Referenced by keyPressEvent().
enableFiltering()
void MantidQt::MantidWidgets::Batch::JobTreeView::enableFiltering () protected
Definition at line 450 of file JobTreeView.cpp.
References m_filteredModel, and m_mainModel.
Referenced by JobTreeView().
expandAll()
void MantidQt::MantidWidgets::Batch::JobTreeView::expandAll () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 384 of file JobTreeView.cpp.
Referenced by filterRowsBy().
expanded()
QModelIndexForFilteredModel MantidQt::MantidWidgets::Batch::JobTreeView::expanded (QModelIndexForFilteredModel const & index) private
Definition at line 388 of file JobTreeView.cpp.
References index, and m_filteredModel.
Referenced by appendAndEditAtChildRow(), applyNavigationResult(), and insertChildRowOf().
filterRowsBy() [1/2]
void MantidQt::MantidWidgets::Batch::JobTreeView::filterRowsBy (RowPredicate * predicate) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 69 of file JobTreeView.cpp.
References expandAll(), m_filteredModel, and MantidQt::MantidWidgets::Batch::FilteredTreeModel::setPredicate().
filterRowsBy() [2/2]
void MantidQt::MantidWidgets::Batch::JobTreeView::filterRowsBy (std::unique_ptr< RowPredicate > predicate) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 64 of file JobTreeView.cpp.
References expandAll(), m_filteredModel, and MantidQt::MantidWidgets::Batch::FilteredTreeModel::setPredicate().
findImplicitlySelected()
QModelIndexList MantidQt::MantidWidgets::Batch::JobTreeView::findImplicitlySelected (QModelIndexList const & selectedRows) const
Definition at line 136 of file JobTreeView.cpp.
References appendAllUnselectedDescendants(), and hasNoSelectedDescendants().
Referenced by selectedRowLocations().
findOrMakeCellBelow()
std::pair< QModelIndexForFilteredModel, bool > MantidQt::MantidWidgets::Batch::JobTreeView::findOrMakeCellBelow (QModelIndexForFilteredModel const & index) private
Definition at line 402 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendEmptySiblingRow(), MantidQt::MantidWidgets::Batch::below(), fromFilteredModel(), MantidQt::MantidWidgets::Batch::hasRowBelow(), index, m_adaptedMainModel, mapToFilteredModel(), mapToMainModel(), and resetFilter().
Referenced by appendAndEditAtRowBelow().
fromFilteredModel()
QModelIndexForFilteredModel MantidQt::MantidWidgets::Batch::JobTreeView::fromFilteredModel (QModelIndex const & filteredModelIndex) const private
Definition at line 502 of file JobTreeView.cpp.
References m_filteredModel.
Referenced by appendAndEditAtChildRow(), appendAndEditAtRowBelow(), applyNavigationResult(), commitData(), edit(), editAtRowAbove(), findOrMakeCellBelow(), isBeingEdited(), and rowRemovalWouldBeIneffective().
fromMainModel()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::JobTreeView::fromMainModel (QModelIndex const & mainModelIndex) const private
Definition at line 498 of file JobTreeView.cpp.
References m_mainModel.
Referenced by applyNavigationResult(), and replaceSubtreeAt().
hasEditorOpen()
bool MantidQt::MantidWidgets::Batch::JobTreeView::hasEditorOpen () const private
Definition at line 283 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::isValid(), and m_lastEdited.
Referenced by isBeingEdited(), and rowRemovalWouldBeIneffective().
hasFilter()
bool MantidQt::MantidWidgets::Batch::JobTreeView::hasFilter () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 79 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::FilteredTreeModel::isReset(), and m_filteredModel.
hasNoSelectedDescendants()
bool MantidQt::MantidWidgets::Batch::JobTreeView::hasNoSelectedDescendants (QModelIndex const & index) const
Definition at line 108 of file JobTreeView.cpp.
References hasNoSelectedDescendants(), index, and m_filteredModel.
Referenced by findImplicitlySelected(), and hasNoSelectedDescendants().
indexesAreOnSameRow()
bool MantidQt::MantidWidgets::Batch::JobTreeView::indexesAreOnSameRow (QModelIndex const & a, QModelIndex const & b) const private
References MantidQt::MantidWidgets::Batch::fromFilteredModel(), and MantidQt::MantidWidgets::Batch::fromMainModel().
insertChildRowOf() [1/2]
RowLocation MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf (RowLocation const & parent, int beforeRow) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 346 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), editAt(), expanded(), MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::insertEmptyChildRow(), m_adaptedMainModel, mapToFilteredModel(), and rowLocation().
insertChildRowOf() [2/2]
RowLocation MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf (RowLocation const & parent, int beforeRow, std::vector< Cell > const & rowText) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 352 of file JobTreeView.cpp.
References assertOrThrow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex(), editAt(), expanded(), g_deadCell, MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::insertChildRow(), m_adaptedMainModel, m_mainModel, mapToFilteredModel(), MantidQt::MantidWidgets::Batch::paddedCellsToWidth(), and rowLocation().
insertSubtreeAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::insertSubtreeAt (RowLocation const & parent, int index, Subtree const & subtree) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 240 of file JobTreeView.cpp.
References index, m_adaptedMainModel, and rowLocation().
Referenced by appendSubtreeAt(), and replaceSubtreeAt().
isBeingEdited()
bool MantidQt::MantidWidgets::Batch::JobTreeView::isBeingEdited (QModelIndexForFilteredModel const & cellIndex) const private
Definition at line 188 of file JobTreeView.cpp.
References fromFilteredModel(), and hasEditorOpen().
Referenced by closeEditorIfOpenAtCell().
isEditable()
bool MantidQt::MantidWidgets::Batch::JobTreeView::isEditable (const QModelIndex & index) const private
Definition at line 506 of file JobTreeView.cpp.
References index.
Referenced by editAt(), moveNextUntilEditable(), and movePreviousUntilEditable().
isOnlyChild()
bool MantidQt::MantidWidgets::Batch::JobTreeView::isOnlyChild (QModelIndexForMainModel const & index) const private
Definition at line 300 of file JobTreeView.cpp.
References index, and m_mainModel.
Referenced by isOnlyChildOfRoot().
isOnlyChildOfRoot() [1/2]
bool MantidQt::MantidWidgets::Batch::JobTreeView::isOnlyChildOfRoot (QModelIndexForMainModel const & index) const private
Definition at line 309 of file JobTreeView.cpp.
References index, and isOnlyChild().
isOnlyChildOfRoot() [2/2]
bool MantidQt::MantidWidgets::Batch::JobTreeView::isOnlyChildOfRoot (RowLocation const & location) const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 305 of file JobTreeView.cpp.
References index, isOnlyChildOfRoot(), and rowLocation().
Referenced by isOnlyChildOfRoot(), removeAllRows(), and removeRowAt().
keyPressEvent()
void MantidQt::MantidWidgets::Batch::JobTreeView::keyPressEvent (QKeyEvent * event) override protected
Definition at line 456 of file JobTreeView.cpp.
References appendAndEditAtChildRowRequested(), appendAndEditAtRowBelowRequested(), copySelectedRequested(), cutSelectedRequested(), editAtRowAboveRequested(), pasteSelectedRequested(), and removeSelectedRequested().
mapToFilteredModel()
QModelIndexForFilteredModel MantidQt::MantidWidgets::Batch::JobTreeView::mapToFilteredModel (QModelIndexForMainModel const & mainModelIndex) const private
Definition at line 417 of file JobTreeView.cpp.
References m_filteredModel, and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by appendAndEditAtChildRow(), applyNavigationResult(), closeEditorIfCellIsUneditable(), findOrMakeCellBelow(), insertChildRowOf(), and removeRowAt().
mapToMainModel()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::JobTreeView::mapToMainModel (QModelIndexForFilteredModel const & filteredModelIndex) const private
Definition at line 413 of file JobTreeView.cpp.
References m_filteredModel, and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by appendAndEditAtChildRow(), appendAndEditAtRowBelow(), applyNavigationResult(), edit(), findOrMakeCellBelow(), and rowRemovalWouldBeIneffective().
moveCursor()
QModelIndex MantidQt::MantidWidgets::Batch::JobTreeView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) override
Definition at line 522 of file JobTreeView.cpp.
References applyNavigationResult(), moveNextUntilEditable(), and movePreviousUntilEditable().
moveNextUntilEditable()
QtTreeCursorNavigationResult MantidQt::MantidWidgets::Batch::JobTreeView::moveNextUntilEditable (QModelIndex const & startingPoint) private
Definition at line 508 of file JobTreeView.cpp.
References isEditable(), MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::moveCursorNext(), and navigation().
Referenced by moveCursor().
movePreviousUntilEditable()
QModelIndex MantidQt::MantidWidgets::Batch::JobTreeView::movePreviousUntilEditable (QModelIndex const & startingPoint) private
Definition at line 515 of file JobTreeView.cpp.
References isEditable(), MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::moveCursorPrevious(), and navigation().
Referenced by moveCursor().
navigation()
QtTreeCursorNavigation MantidQt::MantidWidgets::Batch::JobTreeView::navigation () const private
Definition at line 397 of file JobTreeView.cpp.
References m_filteredModel.
Referenced by moveNextUntilEditable(), and movePreviousUntilEditable().
pasteSelectedRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::pasteSelectedRequested () protected
Definition at line 175 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyPasteRowsRequested().
Referenced by keyPressEvent().
removeAllRows()
void MantidQt::MantidWidgets::Batch::JobTreeView::removeAllRows () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 337 of file JobTreeView.cpp.
References appendChildRowOf(), clearSelection(), isOnlyChildOfRoot(), and removeRowAt().
Referenced by removeRowAt().
removeRowAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::removeRowAt (RowLocation const & location) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 313 of file JobTreeView.cpp.
References assertOrThrow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), isOnlyChildOfRoot(), m_adaptedMainModel, mapToFilteredModel(), removeAllRows(), MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::removeRowFrom(), resetFilter(), rowLocation(), rowRemovalWouldBeIneffective(), and siblingIfExistsElseParent().
Referenced by removeAllRows(), removeRows(), replaceRows(), and replaceSubtreeAt().
removeRows()
void MantidQt::MantidWidgets::Batch::JobTreeView::removeRows (std::vector< RowLocation > rowsToRemove) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 177 of file JobTreeView.cpp.
References removeRowAt().
removeSelectedRequested()
void MantidQt::MantidWidgets::Batch::JobTreeView::removeSelectedRequested () protected
Definition at line 169 of file JobTreeView.cpp.
References m_notifyee, MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyRemoveRowsRequested(), and selectedRowLocations().
Referenced by keyPressEvent().
replaceRows()
void MantidQt::MantidWidgets::Batch::JobTreeView::replaceRows (std::vector< RowLocation > replacementPoints, std::vector< Subtree > replacements) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 255 of file JobTreeView.cpp.
References appendSubtreeAt(), assertOrThrow(), removeRowAt(), and replaceSubtreeAt().
replaceSubtreeAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::replaceSubtreeAt (RowLocation const & rootToRemove, Subtree const & toInsert) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 226 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::below(), fromMainModel(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), insertSubtreeAt(), MantidQt::MantidWidgets::Batch::RowLocation::parent(), removeRowAt(), rowLocation(), and MantidQt::MantidWidgets::Batch::RowLocation::rowRelativeToParent().
Referenced by replaceRows().
resetFilter()
void MantidQt::MantidWidgets::Batch::JobTreeView::resetFilter () override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 74 of file JobTreeView.cpp.
References m_filteredModel, m_notifyee, MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifyFilterReset(), and MantidQt::MantidWidgets::Batch::FilteredTreeModel::resetPredicate().
Referenced by appendAndEditAtChildRow(), applyNavigationResult(), findOrMakeCellBelow(), and removeRowAt().
rowLocation()
RowLocationAdapter MantidQt::MantidWidgets::Batch::JobTreeView::rowLocation () const private
Definition at line 399 of file JobTreeView.cpp.
References m_mainModel.
Referenced by appendAndEditAtChildRow(), appendAndEditAtRowBelow(), appendChildRowOf(), appendSubtreeAt(), applyNavigationResult(), cellAt(), cellsAt(), commitData(), insertChildRowOf(), insertSubtreeAt(), isOnlyChildOfRoot(), removeRowAt(), replaceSubtreeAt(), setCellAt(), and setCellsAt().
rowRemovalWouldBeIneffective()
bool MantidQt::MantidWidgets::Batch::JobTreeView::rowRemovalWouldBeIneffective (QModelIndexForMainModel const & indexToRemove) const private
Definition at line 285 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::areOnSameRow(), fromFilteredModel(), hasEditorOpen(), mapToMainModel(), and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
Referenced by removeRowAt().
selectedRowLocations()
std::vector< RowLocation > MantidQt::MantidWidgets::Batch::JobTreeView::selectedRowLocations () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 149 of file JobTreeView.cpp.
References findImplicitlySelected(), and index.
Referenced by removeSelectedRequested(), selectedSubtreeRoots(), and selectedSubtrees().
selectedSubtreeRoots()
boost::optional< std::vector< RowLocation > > MantidQt::MantidWidgets::Batch::JobTreeView::selectedSubtreeRoots () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 103 of file JobTreeView.cpp.
References selectedRowLocations().
selectedSubtrees()
boost::optional< std::vector< Subtree > > MantidQt::MantidWidgets::Batch::JobTreeView::selectedSubtrees () const override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 89 of file JobTreeView.cpp.
References selectedRowLocations().
selectionChanged
void MantidQt::MantidWidgets::Batch::JobTreeView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) override protected slot
Definition at line 57 of file JobTreeView.cpp.
References m_notifyee, and MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber::notifySelectionChanged().
setCellAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::setCellAt (RowLocation location, int column, Cell const & cellText) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 202 of file JobTreeView.cpp.
References closeEditorIfCellIsUneditable(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), m_adaptedMainModel, rowLocation(), and MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellAtCellIndex().
setCellsAt()
void MantidQt::MantidWidgets::Batch::JobTreeView::setCellsAt (RowLocation const & location, std::vector< Cell > const & rowText) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 220 of file JobTreeView.cpp.
References closeAnyOpenEditorsOnUneditableCells(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), m_adaptedMainModel, rowLocation(), and MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellsAtRow().
setHeaderLabels()
void MantidQt::MantidWidgets::Batch::JobTreeView::setHeaderLabels (QStringList const & columnHeadings) protected
Definition at line 274 of file JobTreeView.cpp.
References m_mainModel.
Referenced by JobTreeView().
setHintsForColumn() [1/2]
void MantidQt::MantidWidgets::Batch::JobTreeView::setHintsForColumn (int column, HintStrategy * hintStrategy) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 132 of file JobTreeView.cpp.
References setHintsForColumn().
setHintsForColumn() [2/2]
void MantidQt::MantidWidgets::Batch::JobTreeView::setHintsForColumn (int column, std::unique_ptr< HintStrategy > hintStrategy) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 128 of file JobTreeView.cpp.
Referenced by setHintsForColumn().
siblingIfExistsElseParent()
QModelIndex MantidQt::MantidWidgets::Batch::JobTreeView::siblingIfExistsElseParent (QModelIndex const & index) const private
Definition at line 290 of file JobTreeView.cpp.
References MantidQt::MantidWidgets::Batch::above(), MantidQt::MantidWidgets::Batch::below(), MantidQt::MantidWidgets::Batch::hasRowAbove(), MantidQt::MantidWidgets::Batch::hasRowBelow(), and index.
Referenced by removeRowAt().
subscribe()
void MantidQt::MantidWidgets::Batch::JobTreeView::subscribe (JobTreeViewSubscriber * subscriber) override virtual
Implements MantidQt::MantidWidgets::Batch::IJobTreeView.
Definition at line 281 of file JobTreeView.cpp.
References m_notifyee.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::JobTreeViewSignalAdapter().
Member Data Documentation
g_deadCell
Cell const MantidQt::MantidWidgets::Batch::JobTreeView::g_deadCell = Cell("", "white", 0, "transparent", 0, false) static private
Definition at line 108 of file JobTreeView.h.
Referenced by appendChildRowOf(), deadCell(), and insertChildRowOf().
m_adaptedMainModel
QtStandardItemTreeModelAdapter MantidQt::MantidWidgets::Batch::JobTreeView::m_adaptedMainModel private
Definition at line 144 of file JobTreeView.h.
Referenced by appendAndEditAtChildRow(), appendChildRowOf(), applyNavigationResult(), cellAt(), cellsAt(), closeAnyOpenEditorsOnUneditableCells(), commitData(), findOrMakeCellBelow(), insertChildRowOf(), insertSubtreeAt(), removeRowAt(), setCellAt(), and setCellsAt().
m_filteredModel
FilteredTreeModel MantidQt::MantidWidgets::Batch::JobTreeView::m_filteredModel private
Definition at line 146 of file JobTreeView.h.
Referenced by appendAllUnselectedDescendants(), enableFiltering(), expanded(), filterRowsBy(), fromFilteredModel(), hasFilter(), hasNoSelectedDescendants(), JobTreeView(), mapToFilteredModel(), mapToMainModel(), navigation(), and resetFilter().
m_hasEditorOpen
bool MantidQt::MantidWidgets::Batch::JobTreeView::m_hasEditorOpen private
Definition at line 148 of file JobTreeView.h.
Referenced by commitData(), and edit().
m_lastEdited
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::JobTreeView::m_lastEdited private
Definition at line 147 of file JobTreeView.h.
Referenced by commitData(), edit(), and hasEditorOpen().
m_mainModel
QStandardItemModel MantidQt::MantidWidgets::Batch::JobTreeView::m_mainModel private
Definition at line 143 of file JobTreeView.h.
Referenced by appendAndEditAtRowBelow(), appendChildRowOf(), appendSubtreeAt(), closeAnyOpenEditorsOnUneditableCells(), enableFiltering(), fromMainModel(), insertChildRowOf(), isOnlyChild(), JobTreeView(), rowLocation(), and setHeaderLabels().
m_notifyee
JobTreeViewSubscriber* MantidQt::MantidWidgets::Batch::JobTreeView::m_notifyee private
Definition at line 142 of file JobTreeView.h.
Referenced by appendAndEditAtChildRow(), appendAndEditAtChildRowRequested(), appendAndEditAtRowBelow(), appendAndEditAtRowBelowRequested(), applyNavigationResult(), commitData(), copySelectedRequested(), cutSelectedRequested(), editAtRowAboveRequested(), pasteSelectedRequested(), removeSelectedRequested(), resetFilter(), selectionChanged(), and subscribe().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/JobTreeView.h
qt/widgets/common/src/Batch/JobTreeView.cpp