Mantid: Mantid::DataHandling Namespace Reference
Mantid::DataHandling Namespace Reference
Namespaces
namespace ANSTO
namespace AxisHelper
namespace EMU
namespace GeometryArgs
Provate namespace storing geometry args.
namespace H5Util
namespace LoadGeometry
Common methods for LoadInstrument.cpp and LoadEmptyInstrument.cpp.
namespace LoadHelper
LoadHelper : Auxiliary functions for Loading Files.
namespace LoadISISNexusHelper
namespace LoadNexusMonitorsAlg
Load Monitors from NeXus files.
namespace MuonNexus
namespace NeXusEntry
namespace NXcanSAS
namespace PLN
namespace PropertyNames
Private namespace storing property name strings.
namespace SEArgs
Private namespace storing sample environment args.
namespace ShapeArgs
Private namespace storing sample environment args.
Classes
class ApplyDiffCal
ApplyDiffCal :
class AvrgDetector
helper class-collection to keep together the parameters, which characterize average composite detector and help to calculate these parameters
class CheckMantidVersion
CheckMantidVersion : Checks if the current version of Mantid is the most recent.
class ChopperConfiguration
struct CoincidenceEvent
A detected neutron.
class CompressEvents
Compress an EventWorkspace by lumping together events with very close TOF value, while ignoring the event's pulse time.
class CreateChunkingFromInstrument
CreateChunkingFromInstrument : TODO: DESCRIPTION.
class CreatePolarizationEfficiencies
CreatePolarizationEfficiencies.
class CreatePolarizationEfficienciesBase
CreatePolarizationEfficienciesBase - the base class for algorithms that create polarization efficiency workspaces:
class CreateSampleShape
This class allows the shape of the sample to be defined by using the allowed XML expressions.
class CreateSimulationWorkspace
struct DasEvent
Structure that matches the form in the binary event list.
class DataBlock
DataBlock: The DataBlock class holds information about a contiguous block of spectrum numbers.
class DataBlockComposite
DataBlockComposite: The DataBlockComposite handles a collection of DataBlocks.
class DataBlockGenerator
DataBlockGenerator: The DataBlockGenerator class provides increasing int64_t numbers from a collection of intervals which are being input into the generator at construction.
class DefaultEventLoader
Helper class for LoadEventNexus that is specific to the current default loading code for NXevent_data entries in Nexus files, in particular LoadBankFromDiskTask and ProcessBankData.
class DefineGaugeVolume
This class allows the shape of the sample to be defined by using the allowed XML expressions.
class DeleteTableRows
Deletes a row from a TableWorkspace.
struct DetectorWord
Holds the 128 bit words from the detector.
class DetermineChunking
class DetParameters
Small helper class-holder used to precalculate the detectors parameters in spherical coordinate system.
class DownloadFile
DownloadFile : Downloads a file from a url to the file system.
class DownloadInstrument
DownloadInstrument : Downloads one or more instrument files to the local instrument cache from the instrument repository.
union EventUnion
Is able to hold all versions of the data words in the same memory location.
class EventWorkspaceCollection
EventWorkspaceCollection : Collection of EventWorspaces to give backward-forward compatibility around performing operations on groups.
class ExtractMonitorWorkspace
Looks for an internally-stored monitor workspace on the input workspace and sets it as the output workspace if found.
class ExtractPolarizationEfficiencies
Looks for a parameter in the parameter file that stores polarization efficiencies to be used with the polarization correction algorithm (PolarizationEfficienciesCor).
struct FileTypeDescriptor
Description of the ASCII data header, common for all ASCII PAR and PHX files.
class FilterEventsByLogValuePreNexus
A data loading and splitting routine for SNS pre-nexus event files.
class FindDetectorsInShape
An algorithm for finding which detectors are contained within a user defined shape within the instrument.
class FindDetectorsPar
struct FITSInfo
class GenerateGroupingPowder
GenerateGroupingPowder : Generate grouping file and par file, for powder scattering.
struct GenericEvent
Generic event to separate bits.
class getWithoutMonitors
To be used with std::generate to copy only those values from a dataset that don't relate to monitors.
class GroupDetectors
An algorithm for grouping detectors and the spectra associated with them into a single DetectorGroup and spectrum.
class GroupDetectors2
An algorithm for grouping detectors and their associated spectra into single spectra and DetectorGroups.
struct HashV3DPair
struct headerData
struct IntermediateEvent
Structure used as an intermediate for parallel processing of events.
class InvalidLogPeriods
Custom exception extending std::invalid_argument Thrown when nperiods does not match period_log Custom exception so we can re-propagate this error and handle all other errors.
class ISampleEnvironmentSpecFinder
Interface for a class responsible for finding a specification based on a name.
class ISISDataArchive
This class is for searching the ISIS data archive.
class ISISJournal
ISISJournal: Helper class to aid in fetching ISIS specific run information from journal files.
class ISISJournalGetExperimentRuns
ISISJournalGetExperimentRuns obtains a list of runs and related information for an investigation and cycle.
class ISISRunLogs
Defines a class to aid in creating ISIS specific run logs for periods, status etc.
class JoinISISPolarizationEfficiencies
JoinISISPolarizationEfficiencies : Joins reflectometry polarization efficiency correction factors to form a single matrix workspace.
class Load
Loads a workspace from a data file.
class LoadAscii
Loads a workspace from an ascii file.
class LoadAscii2
Loads a workspace from an ascii file.
class LoadAsciiStl
class LoadBankFromDiskTask
This task does the disk IO from loading the NXS file, and so will be on a disk IO mutex.
class LoadBBY
class LoadBinaryStl
class LoadCalFile
Algorithm to load a 5-column ascii .cal file into up to 3 workspaces: a GroupingWorkspace, OffsetsWorkspace and/or MaskWorkspace.
class LoadCanSAS1D
This algorithm loads 1 CanSAS1d xml file into a workspace.
class LoadCanSAS1D2
This algorithm loads 1 CanSAS1d xml file into a workspace.
class LoadCSNSNexus
LoadCSNSNexus : TODO: DESCRIPTION.
class LoadDaveGrp
Reads the DAVE grouped ASCII format into a workspace.
class LoadDetectorInfo
class LoadDetectorsGroupingFile
LoadDetectorsGroupingFile.
class LoadDiffCal
LoadDiffCal : TODO: DESCRIPTION.
class LoadDNSEvent
LoadDNSEvent.
class LoadDspacemap
Loads a Dspacemap file (POWGEN binary, VULCAN binary or ascii format) into an OffsetsWorkspace.
class LoadEmptyInstrument
Loads an instrument definition file into a workspace, with the purpose of being able to visualise an instrument without requiring to read in a ISIS raw datafile first.
class LoadEMU
class LoadEMUHdf
LoadEMUHdf : Loads an ANSTO EMU Hdf and linked event file into a workspace.
class LoadEMUTar
LoadEMUTar : Loads a merged ANSTO EMU Hdf and event file into a workspace.
class LoadEventNexus
Load Event Nexus files.
class LoadEventNexusIndexSetup
Helper for LoadEventNexus dealing with setting up indices (spectrum numbers an detector ID mapping) for workspaces.
class LoadEventPreNexus2
A data loading routine for SNS pre-nexus event files.
class LoadFITS
LoadFITS: Load one or more of FITS files into a Workspace2D.
class LoadFullprofResolution
LoadFullprofResolution : Load Fullprof resolution (.irf) file to TableWorkspace(s)
class LoadGroupMapFile
Class used to load a grouping information from .map file.
class LoadGroupXMLFile
class LoadGSASInstrumentFile
LoadGSASInstrumentFile : Load GSAS instrument file to TableWorkspace(s)
class LoadGSS
Loads a file as saved by SaveGSS.
class LoadHFIRSANS
This algorithm loads a SPICE2D file for HFIR SANS into a workspace.
class LoadIDFFromNexus
DataHandling/LoadIDFFromNexus.h.
class LoadILLDiffraction
LoadILLDiffraction : Loads ILL diffraction nexus files.
class LoadILLIndirect2
Loads an ILL IN16B nexus file into a Mantid workspace.
class LoadILLPolarizationFactors
LoadILLPolarizationFactors : Load reflectometry polarization efficiency correction factors from disk.
class LoadILLPolarizedDiffraction
LoadILLPolarizedDiffraction : Loads ILL polarized diffraction nexus files from instrument D7.
class LoadILLReflectometry
LoadILLReflectometry : Loads an ILL reflectometry Nexus data file.
class LoadILLSALSA
Loads an ILL SALSA NeXus file into a Mantid workspace.
class LoadILLSANS
LoadILLSANS; supports D11, D22 and D33 (TOF/monochromatic)
class LoadILLTOF2
Loads an ILL IN4/5/6/Panther NeXus file into a Mantid workspace.
class LoadInstrument
Loads instrument data from an XML or Nexus instrument description file and adds it to a workspace.
class LoadInstrumentFromNexus
DataHandling/LoadInstrumentFromNexus.h.
class LoadInstrumentFromRaw
DataHandling/LoadInstrumentFromRaw.h.
class LoadIsawDetCal
Find the offsets for each detector.
class LoadISISNexus2
Loads a file in a NeXus format and stores it in a 2D workspace.
class LoadISISPolarizationEfficiencies
LoadISISPolarizationEfficiencies : Load reflectometry polarization efficiency correction factors from disk.
class LoadLLB
LoadLLB : Loads an LLB MIBEMOL TOF NeXus file into a Workspace2D with the given name.
class LoadLog
Load ISIS log file(s).
class LoadMappingTable
Loads the mapping table between spectra and IDetector from a raw file.
class LoadMask
LoadMask : Load masking file to generate a SpecialWorkspace2D object (masking workspace).
class LoadMcStas
LoadMcStas : TODO: DESCRIPTION.
class LoadMcStasNexus
LoadMcStasNexus : TODO: DESCRIPTION.
class LoadMLZ
LoadMLZ : Loads MLZ nexus or hdf file into a Mantid workspace.
class LoadMuonLog
Load ISIS Muon log data from a NeXus file.
class LoadMuonNexus
It is a base class for loaders for versions 1 and 2 of the muon nexus file format.
class LoadMuonNexus1
class LoadMuonNexus2
Loads an file in NeXus Muon format version 1 and 2 and stores it in a 2D workspace (Workspace2D class).
class LoadMuonNexusV2
Loads a file in the Nexus Muon format V2 and stores it in a 2D workspace (Workspace2D class).
class LoadMuonNexusV2NexusHelper
class LoadMuonStrategy
class LoadNexus
Loads a file in NeXus format and stores it in a 2D workspace (Workspace2D class).
class LoadNexusLogs
Loads the run logs from a NeXus file.
class LoadNexusMonitors
DataHandling/LoadNexusMonitors.h.
class LoadNexusMonitors2
class LoadNexusProcessed
Loads a workspace from a NeXus Processed entry in a NeXus file.
class LoadNexusProcessed2
LoadNexusProcessed2 : Second variation of LoadNexusProcess, built to handle ESS file specifics in addition to existing behaviour for standard Mantid Processed files.
class LoadNGEM
class LoadNXcanSAS
LoadNXcanSAS : Tries to load an NXcanSAS file type into a Workspace2D.
class LoadNXSPE
LoadNXSPE : Algorithm to load an NXSPE file into a workspace2D.
class LoadOff
class LoadParameterFile
DataHandling/LoadParameterFile.h.
class LoadPDFgetNFile
LoadPDFgetNFile : TODO: DESCRIPTION.
class LoadPLN
LoadPLN : Loads an ANSTO PLN Hdf and linked event file into a workspace.
class LoadPreNexus
LoadPreNexus : Workflow algorithm to load a collection of preNeXus files.
class LoadPreNexusMonitors
class LoadPSIMuonBin
class LoadQKK
Loads a Quokka data file.
class LoadRaw3
Loads an file in ISIS RAW format and stores it in a 2D workspace (Workspace2D class).
class LoadRawBin0
Loads bin zero for all spectra from ISIS RAW file and stores it in a 2D workspace (Workspace2D class).
class LoadRawHelper
Helper class for LoadRaw algorithms.
class LoadRawSpectrum0
Loads zeroth spectrum from ISIS RAW format file and stores it in a 2D workspace (Workspace2D class).
class LoadRKH
Loads an RKH file into a Mantid 1D workspace.
class LoadSampleDetailsFromRaw
An algorithm to extract the sample details from the SPB structure within a RAW file.
class LoadSampleEnvironment
Load Environment into the sample of a workspace, either replacing the current environment, or replacing it, you may also set the material.
class LoadSampleShape
Load Shape into an instrument of a workspace.
class LoadSassena
Load Sassena Output files.
class LoadSESANS
LoadSESANS : Load a workspace in the SESANS file format.
class LoadSingleMesh
class LoadSINQFocus
Loads an PSI nexus file into a Mantid workspace.
class LoadSNSspec
Loads a workspace from an SNS spec file.
class LoadSPE
Loads an SPE format file into a Mantid workspace.
class LoadSpec
Loads a workspace from an ascii file.
class LoadSpice2D
This algorithm loads a SPICE2D file for HFIR SANS into a workspace.
class LoadSpiceAscii
LoadSpiceAscii : TODO: DESCRIPTION.
class LoadSpiceXML2DDet
LoadSpiceXML2DDet : Load 2D detector data in XML format form SPICE.
class LoadStl
class LoadStlFactory
class LoadSwans
LoadSwans : Test Loader to read data from the LDRD new SWANS detector.
class LoadTBL
Loads a table workspace from an ascii file in reflectometry tbl format.
class LoadTOFRawNexus
Loads a NeXus file that conforms to the TOFRaw instrument definition format and stores it in a 2D workspace.
class Mantid3MFFileIO
Class to load and save .3mf files .3mf format is a 3D manufacturing format for storing mesh descriptions of multi-component objects + metadata about the overall model (eg scale) and the individual components.
class MaskDetectors
An algorithm to mask a detector, or set of detectors.
class MaskDetectorsInShape
An algorithm for finding masking detectors that are contained within a user defined shape within the instrument.
class MaskSpectra
Mask specified spectra and the underlying detectors in a workspace.
class MeshFileIO
class ModifyDetectorDotDatFile
Modifies an ISIS detector dot data file, so that the detector positions are as in the given workspace.
class MoveInstrumentComponent
DataHandling/MoveInstrumentComponent.h.
class MultiPeriodLoadMuonStrategy
class NexusTester
NexusTester : debugging/performance testing algorithm for nexus file loading and saving.
class ORNLDataArchive
Please see the .cpp file for more information.
class ParallelEventLoader
Loader for event data from Nexus files with parallelism based on multiple processes (MPI or MultiProcessing) for performance.
class PatchBBY
class PDLoadCharacterizations
LoadPDCharacterizations : Load a characterization file used in Powder Diffraction Reduction.
class ProcessBankData
This task does the disk IO from loading the NXS file, and so will be on a disk IO mutex.
struct PropertyInfo
struct Pulse
Structure that matches the form in the new pulseid files.
class RawFileInfo
An algorithm to extract pertinent information about a RAW file without loading the data.
class ReadMaterial
This class contains code for interpreting a material input for SetSampleMaterial, validating the parameters before sending them on to MaterialBuilder.
class RemoveLogs
Load ISIS log file(s).
class RenameLog
RenameLog : TODO: DESCRIPTION.
class RotateInstrumentComponent
DataHandling/RotateInstrumentComponent.h.
class RotateSource
RotateSource : Moves the source by a given angle taking into account the handedness.
class SampleEnvironmentFactory
Create a single instance of a SampleEnvironment.
class SampleEnvironmentSpec
Defines the properties of a named SampleEnvironment setup.
class SampleEnvironmentSpecFileFinder
Class responsible for finding a specifications on disk.
class SampleEnvironmentSpecParser
Read an XML definition of a SampleEnvironmentSpec and produce a new SampleEnvironmentSpec object.
class SaveAscii
Saves a workspace or selected spectra in a coma-separated ascii file.
class SaveAscii2
Saves a workspace or selected spectra in a coma-separated ascii file.
class SaveBankScatteringAngles
class SaveCalFile
Algorithm to save a 5-column ascii .cal file from to 3 workspaces: a GroupingWorkspace, OffsetsWorkspace and/or MaskWorkspace.
class SaveCanSAS1D
class SaveCanSAS1D2
This algorithm saves workspace into CanSAS1d format.
class SaveCSV
Saves a 1D or 2D workspace to a CSV file.
class SaveDaveGrp
class SaveDetectorsGrouping
SaveDetectorsGrouping : TODO: DESCRIPTION.
class SaveDiffCal
SaveDiffCal : TODO: DESCRIPTION.
class SaveDiffFittingAscii
class SaveDspacemap
Saves an OffsetsWorkspace into a POWGEN-format binary dspace map file.
class SaveFITS
SaveFITS : Save images in FITS formats.
class SaveFocusedXYE
Saves a focused data set (usually output of a diffraction focusing routine but not exclusively) into a three column format containing X_i, Y_i, and E_i.
class SaveFullprofResolution
SaveFullprofResolution : TODO: DESCRIPTION.
class SaveGDA
class SaveGSASInstrumentFile
SaveGSASInstrumentFile : Convert Fullprof"s instrument resolution file (.irf) to GSAS"s instrument file (.iparm/.prm).
class SaveGSS
Saves a focused data set into a three column GSAS format containing X_i, Y_i*step, and E_i*step.
class SaveIsawDetCal
Saves an instrument with RectangularDetectors to an ISAW .DetCal file.
class SaveISISNexus
The SaveISISNexus algorithm will convert a RAW file to a NeXus file.
class SaveMask
SaveMaskingToFile : TODO: DESCRIPTION.
class SaveNexus
Saves a file in NeXus format and from a 2D workspace (Workspace2D class).
class SaveNexusESS
SaveNexusESS : Save algorithm to save a NeXus organised hdf5 file containing data and geometry from reduced experiment for use at European Spallation Source.
class SaveNexusGeometry
class SaveNexusProcessed
DataHandling/SaveNexusProcessed.h.
class SaveNISTDAT
Writer for compatibility with SansView and NIST reduced data file format.
class SaveNXcanSAS
SaveNXcanSAS : Saves a reduced workspace in the NXcanSAS format.
class SaveNXSPE
Saves a workspace into a NeXus/HDF5 NXSPE file.
class SaveNXTomo
Saves a workspace into a NeXus/HDF5 NXTomo file.
class SaveOpenGenieAscii
class SavePAR
Saves a workspace into an ASCII PAR file.
class SaveParameterFile
SaveParameterFile : Save a workspace's parameters to an instrument parameter file.
class SavePDFGui
SavePDFGui : Saves a workspace containing a pair distrebution function in a format readable by the PDFgui package.
class SavePHX
Saves a workspace into an ASCII PHX file.
class SaveReflectometryAscii
Saves a file of desired (mft, txt, dat or custom) Ascii format from a 2D workspace.
class SaveRKH
Saves a workspace in the RKH file format.
class SaveRMCProfile
SaveRMCProfile : Saves a workspace containing a spectral density in a format readable by the RMCProfile package.
class SaveSampleEnvironmentAndShape
Save the Shape of the sample and environment into a single binary .stl file.
class SaveSESANS
SaveSESANS : Save a workspace in the SESANS file format.
class SaveSPE
Saves a workspace into an ASCII SPE file.
class SaveStl
Class to contain functionality for writing out STL files for SaveShapeAndEnvironment.
class SaveTBL
Saves a table workspace to a reflectometry tbl format ascii file.
class SaveToSNSHistogramNexus
Save a Workspace2D or an EventWorkspace into a NeXus file whose format corresponds to that expected at the SNS.
class SaveVTK
Saves a 1D or 2D workspace using the vtk file format described in the "file formats" document at http://www.vtk.org/documents.php .
class SetBeam
Set properties of the beam.
class SetSample
High-level interface for setting sample metadata on a workspace.
class SetSampleMaterial
This class allows the shape of the sample to be defined by using the allowed XML expressions.
class SetScalingPSD
Read the scaling information from a file (e.g.
class SinglePeriodLoadMuonStrategy
class SNSAppendGeometryToNexus
SNSAppendGeometryToNexus : Appends geometry information to a NeXus file.
class SortTableWorkspace
SortTableWorkspace : TODO: DESCRIPTION.
class SpiceXMLNode
struct T0FrameEvent
Indicate time 0, the start of a new frame.
struct temperatureHeaderData
class UpdateInstrumentFromFile
Update detector positions initially loaded in from Instrument Defintion File (IDF) from information in the provided files.
struct V3DTrueComparator
struct VulcanCorrectionFactor
Structure of the vulcan binary file.
class XmlHandler
Typedefs
using ChopperConfiguration_sptr = std::shared_ptr< ChopperConfiguration >
using DasTofType = int
Type for the DAS time of flight (data file)
using EventWorkspaceCollection_sptr = std::shared_ptr< EventWorkspaceCollection >
using EventWorkspaceCollection_uptr = std::unique_ptr< EventWorkspaceCollection >
using ISampleEnvironmentSpecFinder_uptr = std::unique_ptr< ISampleEnvironmentSpecFinder >
using MeshObject_const_sptr = std::shared_ptr< const Geometry::MeshObject >
Typdef for a shared pointer to a const object.
using MeshObject_sptr = std::shared_ptr< Geometry::MeshObject >
Typdef for a shared pointer.
using mypair = std::pair< double, int >
using optional_size_t = NeXus::NexusFileIO::optional_size_t
using PixelType = int
DetermineChunking : Workflow algorithm to determine chunking.
using SampleEnvironmentSpec_const_uptr = std::unique_ptr< const SampleEnvironmentSpec >
unique_ptr to a const SampleEnvironmentSpec
using SampleEnvironmentSpec_uptr = std::unique_ptr< SampleEnvironmentSpec >
unique_ptr to a SampleEnvironmentSpec
using SpectrumPair = std::pair< specnum_t, specnum_t >
using tokenizer = Mantid::Kernel::StringTokenizer
using ValidationErrors = std::map< std::string, std::string >
Enumerations
enum FileType { PRENEXUS_FILE , EVENT_NEXUS_FILE , HISTO_NEXUS_FILE , RAW_FILE }
Allowed file types.
enum fileTypes {
PAR_type , PHX_type , SPE_type , BIN_file ,
NumFileTypes
}
file types currently supported by ASCII loader are: 1) an ASCII Tobyfit par file Syntax: >> par = get_ascii_file(filename,['par'])
enum class InstrumentLayout { Mantid , NexusFormat , NotRecognised }
Layout information relating to detector-spectra mappings.
enum class LoaderType { Xml = 1 , Idf = 2 , Nxs = 3 }
enum class NexusType { Muon , Processed , ISIS , TofRaw }
enum class ScaleUnits { undefined , metres , centimetres , millimetres }
enum class TimeType : unsigned char { StartTime , EndTime }
enum TYPE { TYPE_STR , TYPE_INT , TYPE_DBL }
Functions
template<typename TYPE >
void AddSinglePointTimeSeriesProperty (API::LogManager &logManager, const std::string &time, const std::string &name, const TYPE value)
template<typename T >
void adjustTimeOfFlightISISLegacy (::NeXus::File &file, T localWorkspace, const std::string &entry_name, const std::string &classType, const Kernel::NexusHDF5Descriptor *descriptor=nullptr)
ISIS specific method for dealing with wide events.
std::vector< int32_t > bankOffsets (const API::ExperimentInfo &ws, const std::string &filename, const std::string &groupName, const std::vector< std::string > &bankNames)
Return offset between global spectrum index and detector ID for given banks.
std::vector< int32_t > bankOffsetsSpectrumNumbers (const API::MatrixWorkspace &ws, const std::string &filename, const std::string &groupName, const std::vector< std::string > &bankNames)
Return offset between global spectrum index and spectrum number for given banks.
static const string BLOCK_SIZE_PARAM ("LoadingBlockSize")
static const string BLOCK_SIZE_PARAM ("LoadingBlockSize")
size_t calcVecSize (const std::vector< double > &data0, std::vector< size_t > &numptsvec, size_t &numsets, bool xascend)
static bool checkIntersection (std::vector< std::string > v1, std::vector< std::string > v2)
bool compare (const mypair &left, const mypair &right)
DataObjects::TableWorkspace_sptr createTimeZeroTable (const size_t numSpec, const std::vector< double > &timeZeros)
Creates a timezero table for the loaded detectors.
static bool endswith (const std::string &s, const std::string &subs)
static const string EVENT_PARAM ("EventFilename")
static const string EVENT_PARAM ("EventFilename")
bool exists (::NeXus::File &file, const std::string &name)
Based on the current group in the file, does the named sub-entry exist?
bool exists (const std::map< std::string, std::string > &entries, const std::string &name)
Mantid::Types::Core::DateAndTime extractDateAndTime (TimeType type, const std::string &filename)
Mantid::Types::Core::DateAndTime DLLExport extractEndTime (const std::string &filename)
Gets the start time from the nexus file.
Mantid::Types::Core::DateAndTime DLLExport extractStartTime (const std::string &filename)
Extracts the start and the end time from a Nexus file.
std::pair< DateAndTime, DateAndTime > firstLastPulseTimes (::NeXus::File &file, Kernel::Logger &logger)
template<class T >
bool from_string (T &t, const std::string &s, std::ios_base &(*f)(std::ios_base &))
static string generateMappingfileName (EventWorkspace_sptr &wksp)
Generate mapping file name.
static string generateMappingfileName (EventWorkspace_sptr &wksp)
Generate mapping file name from Event workspace's instrument.
static string generatePulseidName (string eventfile)
Generate pulse ID.
static string generatePulseidName (string eventfile)
Generate Pulse ID file name from preNexus event file's name.
vector< string > getGroupNames (const string &names)
Split a list of instrument components into a vector of strings.
std::vector< int32_t > getOffsets (const DataObjects::EventWorkspace &ws, const std::string &filename, const std::string &groupName, const std::vector< std::string > &bankNames, const bool eventIDIsSpectrumNumber)
std::vector< std::vector< Types::Event::TofEvent > * > getResultVector (DataObjects::EventWorkspace &ws)
static string getRunnumber (const string &filename)
Get run number.
static string getRunnumber (const string &filename)
Parse preNexus file name to get run number.
ScaleUnits getScaleTypeFromStr (const std::string &scaleProperty)
Mantid::Types::Core::DateAndTime handleISISNexusFile (TimeType type, const std::string &filename)
Mantid::Types::Core::DateAndTime handleMuonNexusFile (TimeType type, const std::string &filename)
Mantid::Types::Core::DateAndTime handleProcessedNexusFile (TimeType type, const std::string &filename)
Mantid::Types::Core::DateAndTime handleTofRawNexusFile (TimeType type, const std::string &filename)
template<class T >
bool loadNXDataSet (NeXus::NXEntry &entry, const std::string &path, T &value)
bool loadNXString (const NeXus::NXEntry &entry, const std::string &path, std::string &value)
std::string MANTID_DATAHANDLING_DLL makeCanSASRelaxedName (const std::string &input)
This makes out of an input a relaxed name, something conforming to "[A-Za-z_][\w_]*" For now "-" is converted to "_", "." is converted to "_", else we throw.
template<typename T >
void makeTimeOfFlightDataFuzzy (::NeXus::File &file, T localWorkspace, const std::string &binsName, size_t start_wi=0, size_t end_wi=0)
Load the time of flight data.
static const string MAP_PARAM ("MappingFilename")
static const string MAP_PARAM ("MappingFilename")
static const string MAP_PARAM ("MappingFilename")
void nexus_print_error (void *pD, char *text)
const int NUM_EXT_EVENT_NEXUS (3)
Number of event nexus extensions.
const int NUM_EXT_HISTO_NEXUS (1)
Number of histogram nexus extensions.
const int NUM_EXT_PRENEXUS (1)
Number of prenexus extensions.
const int NUM_EXT_RAW (1)
Number of raw file extensions.
std::size_t numEvents (::NeXus::File &file, bool &hasTotalCounts, bool &oldNeXusFileNames, const std::string &prefix, const NexusHDF5Descriptor &descriptor)
Get the number of events in the currently opened group.
static const string OUT_PARAM ("OutputWorkspace")
static const string OUT_PARAM ("OutputWorkspace")
static const string PARALLEL_PARAM ("UseParallelProcessing")
static const string PARALLEL_PARAM ("UseParallelProcessing")
string parentName (const IComponent_const_sptr &comp, const string &prefix)
Find the name of the parent of the component that starts with the supplied prefix.
string parentName (const IComponent_const_sptr &comp, const vector< string > &names)
Find the name of the parent of the component that is in the list of parents that are being searched for.
static const string PID_PARAM ("SpectrumList")
static const string PID_PARAM ("SpectrumList")
template<typename T >
void DLLExport populateDataBlockCompositeWithContainer (DataBlockComposite &dataBlockComposite, T &indexContainer, int64_t nArray, int numberOfPeriods, size_t numberOfChannels, std::vector< specnum_t > monitorSpectra)
Populates a DataBlockComposite with DataBlocks which are extracted from a indexable collection (array-type).
static const string PULSEID_PARAM ("PulseidFilename")
static const string PULSEID_PARAM ("PulseidFilename")
static const std::string RUNINFO_FILENAME ("RunInfoFilename")
static const string RUNINFO_PARAM ("Filename")
bool startsWith (const string &str, const string &prefix)
Returns true if str starts with prefix.
void store_value (const DataObjects::Workspace2D_sptr &ws, int specID, double value, double error, double wavelength, double dwavelength)
Convenience function to store a detector value into a given spectrum.
const Mantid::Geometry::MeshObject & toMeshObject (const Geometry::IObject &object)
Function to convert an IObject to a mesh, and throw if this can't be done.
bool UDlesserExecCount (const Mantid::NeXus::NXClassInfo &elem1, const Mantid::NeXus::NXClassInfo &elem2)
to sort the algorithmhistory vector
static const uint64_t VETOFLAG (72057594037927935)
Veto mask as 0xFF000000000.
static const uint64_t VETOFLAG (72057594037927935)
Veto flag: 0xFF00000000000.
bool vzintermediatePixelIDComp (IntermediateEvent x, IntermediateEvent y)
Comparator for sorting dasevent lists.
NexusType whichNexusType (const std::string &filename)
static const std::string WORKSPACE_OUT ("OutputWorkspace")
Variables
const double CONSTANT = (PhysicalConstants::h * 1e10) / (2.0 * PhysicalConstants::NeutronMass * 1e6)
static constexpr uint64_t CONTIN_ID_VALUE = 0x4F
static const double CURRENT_CONVERSION = 1.e-6 / 3600.
Conversion factor between picoColumbs and microAmp*hours.
static const double CURRENT_CONVERSION = 1.e-6 / 3600.
Conversion factor between picoColumbs and microAmp*hours.
static const PixelType ERROR_PID = 0x80000000
All pixel ids with matching this mask are errors.
static const PixelType ERROR_PID = 0x80000000
All pixel ids with matching this mask are errors.
static const string EVENT_EXTS []
static const string EVENT_EXTS []
static constexpr uint64_t EVENT_ID_MASK = 0x40
const std::string EVENT_NEXUS_EXT [NUM_EXT_EVENT_NEXUS] = {"_event.nxs", ".nxs", ".nxs.h5"}
Valid extensions for event nexus files.
static char const *const EXTERNAL = "EXTERNAL"
static char const *const FilenameStr = "Filename"
static char const *const FilenameStr = "Filename"
static char const *const FilterByTimeStartStr = "FilterByTimeStart"
static char const *const FilterByTimeStopStr = "FilterByTimeStop"
static char const *const FilterByTofMaxStr = "FilterByTofMax"
static char const *const FilterByTofMinStr = "FilterByTofMin"
const char FLOAT32 = 'f'
Kernel::Logger g_log ("LoadCSNSNexus")
static const size_t HISTO_BINS_X = 240
static const size_t HISTO_BINS_Y = 256
const std::string HISTO_NEXUS_EXT [NUM_EXT_HISTO_NEXUS] = {"_histo.nxs"}
Valid extensions for histogram nexus files.
static char const *const HistoryStr = "History.log"
const char INT32 = 'i'
static char const *const INTERNAL = "INTERNAL"
static char const *const MaskStr = "Mask"
const unsigned int MAX_BUFFER_BYTES_SIZE = 1500
static const uint32_t MAX_TOF_UINT32 = std::numeric_limits<uint32_t>::max()
The maximum possible tof as native type.
static const uint32_t MAX_TOF_UINT32 = std::numeric_limits<uint32_t>::max()
The maximum possible tof as native type.
static const int NUM_EXT = 6
static const int NUM_EXT = 7
static const unsigned int NUM_PER_LINE = 8
set to the number of numbers on each line (the length of lines is hard-coded in other parts of the code too)
static PropertyInfo PatchableProperties []
const unsigned int PIXEL_PER_TUBE = 1024
const std::string PRENEXUS_EXT [NUM_EXT_PRENEXUS] = {"_runinfo.xml"}
Valid extensions for prenexus files.
static const size_t Progress_LoadBinFile = 48
static const size_t Progress_ReserveMemory = 4
static const size_t Progress_Total = 2 * Progress_LoadBinFile + Progress_ReserveMemory
static const string PULSE_EXTS []
static const string PULSE_EXTS []
constexpr double rad2deg = 180.0 / M_PI
const std::string RAW_EXT [NUM_EXT_RAW] = {".raw"}
Valid extensions for ISIS raw files.
const char STRING = 's'
static const double TOF_CONVERSION = .1
Conversion factor between 100 nanoseconds and 1 microsecond.
static const double TOF_CONVERSION = .1
Conversion factor between 100 nanoseconds and 1 microsecond.
Typedef Documentation
ChopperConfiguration_sptr
using Mantid::DataHandling::ChopperConfiguration_sptr = typedef std::shared_ptr<ChopperConfiguration>
Definition at line 71 of file SaveGSASInstrumentFile.cpp.
DasTofType
typedef int Mantid::DataHandling::DasTofType
Type for the DAS time of flight (data file)
Definition at line 25 of file DetermineChunking.h.
EventWorkspaceCollection_sptr
using Mantid::DataHandling::EventWorkspaceCollection_sptr = typedef std::shared_ptr<EventWorkspaceCollection>
Definition at line 84 of file EventWorkspaceCollection.h.
EventWorkspaceCollection_uptr
using Mantid::DataHandling::EventWorkspaceCollection_uptr = typedef std::unique_ptr<EventWorkspaceCollection>
Definition at line 85 of file EventWorkspaceCollection.h.
ISampleEnvironmentSpecFinder_uptr
using Mantid::DataHandling::ISampleEnvironmentSpecFinder_uptr = typedef std::unique_ptr<ISampleEnvironmentSpecFinder>
Definition at line 27 of file SampleEnvironmentFactory.h.
MeshObject_const_sptr
using Mantid::DataHandling::MeshObject_const_sptr = typedef std::shared_ptr<const Geometry::MeshObject>
Typdef for a shared pointer to a const object.
Definition at line 23 of file Mantid3MFFileIO.h.
MeshObject_sptr
using Mantid::DataHandling::MeshObject_sptr = typedef std::shared_ptr<Geometry::MeshObject>
Typdef for a shared pointer.
Definition at line 21 of file Mantid3MFFileIO.h.
mypair
using Mantid::DataHandling::mypair = typedef std::pair<double, int>
Definition at line 90 of file LoadSassena.cpp.
optional_size_t
using Mantid::DataHandling::optional_size_t = typedef NeXus::NexusFileIO::optional_size_t
Definition at line 35 of file SaveNexusProcessed.cpp.
PixelType
typedef int Mantid::DataHandling::PixelType
DetermineChunking : Workflow algorithm to determine chunking.
This define is used to quickly turn parallel code on or off.
Date
2012-01-30 Make the code clearer by having this an explicit type
Make the code clearer by having this an explicit type
Definition at line 23 of file DetermineChunking.h.
SampleEnvironmentSpec_const_uptr
using Mantid::DataHandling::SampleEnvironmentSpec_const_uptr = typedef std::unique_ptr<const SampleEnvironmentSpec>
unique_ptr to a const SampleEnvironmentSpec
Definition at line 56 of file SampleEnvironmentSpec.h.
SampleEnvironmentSpec_uptr
using Mantid::DataHandling::SampleEnvironmentSpec_uptr = typedef std::unique_ptr<SampleEnvironmentSpec>
unique_ptr to a SampleEnvironmentSpec
Definition at line 54 of file SampleEnvironmentSpec.h.
SpectrumPair
using Mantid::DataHandling::SpectrumPair = typedef std::pair<specnum_t, specnum_t>
Definition at line 16 of file DataBlock.h.
tokenizer
using Mantid::DataHandling::tokenizer = typedef Mantid::Kernel::StringTokenizer
Definition at line 34 of file CreateChunkingFromInstrument.cpp.
ValidationErrors
using Mantid::DataHandling::ValidationErrors = typedef std::map<std::string, std::string>
Definition at line 18 of file ReadMaterial.h.
Enumeration Type Documentation
FileType
enum Mantid::DataHandling::FileType
Allowed file types.
Enumerator
PRENEXUS_FILE
PreNeXus files.
EVENT_NEXUS_FILE
Event NeXus files.
HISTO_NEXUS_FILE
Histogram NeXus files.
RAW_FILE
ISIS raw files.
Definition at line 38 of file DetermineChunking.h.
fileTypes
enum Mantid::DataHandling::fileTypes
file types currently supported by ASCII loader are: 1) an ASCII Tobyfit par file Syntax: >> par = get_ascii_file(filename,['par'])
filename name of par file
par(5,ndet) contents of array
1st column      sample-detector distance
2nd  &quot;          scattering angle (deg)
3rd  &quot;          azimuthal angle (deg)
            (west bank = 0 deg, north bank = -90 deg etc.)
            (Note the reversed sign convention cf .phx files)
4th  &quot;          width (m)
5th  &quot;          height (m)
2) load an ASCII phx file
 phx(7,ndet)         contents of array
 Recall that only the 3,4,5,6 columns in the file (rows in the
 output of this routine) contain useful information
     3rd column      scattering angle (deg)
     4th  &quot;          azimuthal angle (deg)
                 (west bank = 0 deg, north bank = 90 deg etc.)
     5th  &quot;          angular width (deg)
     6th  &quot;          angular height (deg)
Enumerator
PAR_type
PHX_type
SPE_type
BIN_file
NumFileTypes
Definition at line 49 of file FindDetectorsPar.h.
InstrumentLayout
enum class Mantid::DataHandling::InstrumentLayout strong
Layout information relating to detector-spectra mappings.
Enumerator
Mantid
NexusFormat
NotRecognised
Definition at line 27 of file LoadNexusProcessed2.h.
LoaderType
enum class Mantid::DataHandling::LoaderType strong
Enumerator
Xml
Idf
Nxs
Definition at line 41 of file LoadInstrument.cpp.
NexusType
enum class Mantid::DataHandling::NexusType strong
Enumerator
Muon
Processed
ISIS
TofRaw
Definition at line 23 of file StartAndEndTimeFromNexusFileExtractor.cpp.
ScaleUnits
enum class Mantid::DataHandling::ScaleUnits strong
Enumerator
undefined
metres
centimetres
millimetres
Definition at line 21 of file MeshFileIO.h.
TimeType
enum class Mantid::DataHandling::TimeType : unsigned char strong
Enumerator
StartTime
EndTime
Definition at line 24 of file StartAndEndTimeFromNexusFileExtractor.cpp.
TYPE
enum Mantid::DataHandling::TYPE
Enumerator
TYPE_STR
TYPE_INT
TYPE_DBL
Definition at line 20 of file PatchBBY.cpp.
Function Documentation
AddSinglePointTimeSeriesProperty()
template<typename TYPE > void Mantid::DataHandling::AddSinglePointTimeSeriesProperty (API::LogManager & logManager, const std::string & time, const std::string & name, const TYPE value)
Definition at line 66 of file LoadBBY.cpp.
References value.
Referenced by Mantid::DataHandling::LoadBBY::exec().
adjustTimeOfFlightISISLegacy()
template<typename T > void Mantid::DataHandling::adjustTimeOfFlightISISLegacy (::NeXus::File & file, T localWorkspace, const std::string & entry_name, const std::string & classType, const Kernel::NexusHDF5Descriptor * descriptor = nullptr)
ISIS specific method for dealing with wide events.
Check if time_of_flight can be found in the file and load it.
THIS ONLY APPLIES TO ISIS FILES WITH "detector_1_events" IN THE "NXentry."
Parameters
file :: The nexus file to read from.
localWorkspace :: The event workspace collection which events will be modified.
entry_name :: An NXentry tag in the file
classType :: The type of the events: either detector or monitor
descriptor :: input descriptor carrying metadata information
Definition at line 376 of file LoadEventNexus.h.
References makeTimeOfFlightDataFuzzy(), n, and std::to_string().
Referenced by Mantid::DataHandling::LoadNexusMonitors2::exec().
bankOffsets()
std::vector< int32_t > Mantid::DataHandling::bankOffsets (const API::ExperimentInfo & ws, const std::string & filename, const std::string & groupName, const std::vector< std::string > & bankNames)
Return offset between global spectrum index and detector ID for given banks.
Definition at line 18 of file ParallelEventLoader.cpp.
References bankOffsets(), Mantid::Geometry::DetectorInfo::detectorIDs(), and Mantid::API::ExperimentInfo::detectorInfo().
Referenced by bankOffsets(), and getOffsets().
bankOffsetsSpectrumNumbers()
std::vector< int32_t > Mantid::DataHandling::bankOffsetsSpectrumNumbers (const API::MatrixWorkspace & ws, const std::string & filename, const std::string & groupName, const std::vector< std::string > & bankNames)
Return offset between global spectrum index and spectrum number for given banks.
Definition at line 51 of file ParallelEventLoader.cpp.
References Mantid::API::MatrixWorkspace::indexInfo().
Referenced by getOffsets().
BLOCK_SIZE_PARAM() [1/2]
static const string Mantid::DataHandling::BLOCK_SIZE_PARAM ("LoadingBlockSize") static
BLOCK_SIZE_PARAM() [2/2]
static const string Mantid::DataHandling::BLOCK_SIZE_PARAM ("LoadingBlockSize") static
calcVecSize()
size_t Mantid::DataHandling::calcVecSize (const std::vector< double > & data0, std::vector< size_t > & numptsvec, size_t & numsets, bool xascend)
Definition at line 280 of file LoadPDFgetNFile.cpp.
Referenced by Mantid::DataHandling::LoadPDFgetNFile::generateDataWorkspace().
checkIntersection()
static bool Mantid::DataHandling::checkIntersection (std::vector< std::string > v1, std::vector< std::string > v2) static
Definition at line 47 of file LoadSpiceAscii.cpp.
Referenced by Mantid::DataHandling::LoadSpiceAscii::validateLogNamesType().
compare()
bool Mantid::DataHandling::compare (const mypair & left, const mypair & right)
Definition at line 91 of file LoadSassena.cpp.
References left, and right.
Referenced by Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::API::Sample::operator==(), and Mantid::Algorithms::CheckWorkspacesMatch::runCompareWorkspaces().
createTimeZeroTable()
DataObjects::TableWorkspace_sptr Mantid::DataHandling::createTimeZeroTable (const size_t numSpec, const std::vector< double > & timeZeros)
Creates a timezero table for the loaded detectors.
Parameters
numSpec :: Number of spectra (number of rows in table)
timeZeros :: Vector containing time zero values for each spectra
Returns
TableWorkspace of time zeros
Definition at line 26 of file LoadMuonStrategy.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::DataHandling::LoadMuonNexus1::exec(), Mantid::DataHandling::LoadPSIMuonBin::exec(), Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getTimeZeroTable(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getTimeZeroTable().
endswith()
static bool Mantid::DataHandling::endswith (const std::string & s, const std::string & subs) static
Definition at line 36 of file LoadSpiceAscii.cpp.
Referenced by Mantid::DataHandling::LoadDiffCal::exec(), and Mantid::DataHandling::LoadSpiceAscii::parseSPICEAscii().
EVENT_PARAM() [1/2]
static const string Mantid::DataHandling::EVENT_PARAM ("EventFilename") static
Referenced by Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties().
EVENT_PARAM() [2/2]
static const string Mantid::DataHandling::EVENT_PARAM ("EventFilename") static
exists() [1/2]
bool Mantid::DataHandling::exists (::NeXus::File & file, const std::string & name)
Based on the current group in the file, does the named sub-entry exist?
Parameters
file : File handle. This is not modified, but cannot be const
name : sub entry name to look for
Returns
true only if it exists
Definition at line 69 of file LoadEventNexus.cpp.
References exists().
Referenced by Mantid::Kernel::AttenuationProfile::AttenuationProfile(), Mantid::DataObjects::MDEventsTestHelper::checkAndDeleteFile(), Mantid::DataHandling::SaveReflectometryAscii::checkFile(), Mantid::Kernel::FileValidator::checkValidity(), Mantid::API::DeprecatedAlgorithm::deprecationMsg(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::SaveDiffCal::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveNXcanSAS::exec(), Mantid::MDAlgorithms::MergeMDFiles::exec(), exists(), Mantid::Kernel::FileDescriptor::FileDescriptor(), Mantid::DataHandling::ISISDataArchive::fileExists(), Mantid::WorkflowAlgorithms::EQSANSLoad::findConfigFile(), Mantid::DataHandling::SampleEnvironmentSpecParser::findFile(), Mantid::API::FileFinderImpl::findRun(), generateMappingfileName(), Mantid::DataHandling::SampleEnvironmentSpecParser::loadMeshFromSTL(), Mantid::API::InstrumentFileFinder::lookupIPF(), Mantid::Kernel::NexusDescriptor::NexusDescriptor(), Mantid::Kernel::BinaryFile< T >::open(), Mantid::NeXus::NexusFileIO::openNexusWrite(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties(), and Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs().
exists() [2/2]
bool Mantid::DataHandling::exists (const std::map< std::string, std::string > & entries, const std::string & name)
Definition at line 74 of file LoadEventNexus.cpp.
extractDateAndTime()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::extractDateAndTime (TimeType type, const std::string & filename)
Definition at line 99 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References handleISISNexusFile(), handleMuonNexusFile(), handleProcessedNexusFile(), handleTofRawNexusFile(), Mantid::Kernel::SingletonHolder< T >::Instance(), ISIS, Muon, Processed, TofRaw, and whichNexusType().
Referenced by extractEndTime(), and extractStartTime().
extractEndTime()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::extractEndTime (const std::string & filename)
Gets the start time from the nexus file.
Parameters
filename the file name
Returns
the start time
Exceptions
if the the start time cannot be extracted
Definition at line 142 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References EndTime, and extractDateAndTime().
extractStartTime()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::extractStartTime (const std::string & filename)
Extracts the start and the end time from a Nexus file.
Gets the start time from the nexus file.
Parameters
filename the file name
Returns
the start time
Exceptions
if the the start time cannot be extracted
Definition at line 132 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References extractDateAndTime(), and StartTime.
firstLastPulseTimes()
std::pair< DateAndTime, DateAndTime > Mantid::DataHandling::firstLastPulseTimes (::NeXus::File & file, Kernel::Logger & logger)
Definition at line 448 of file LoadEventNexus.cpp.
References Mantid::Kernel::Units::timeConversionValue(), and Mantid::Kernel::Logger::warning().
Referenced by Mantid::DataHandling::LoadEventNexus::loadEvents().
from_string()
template<class T > bool Mantid::DataHandling::from_string (T & t, const std::string & s, std::ios_base &(*)(std::ios_base &) f)
Definition at line 62 of file LoadSpice2D.cpp.
generateMappingfileName() [1/2]
static string Mantid::DataHandling::generateMappingfileName (EventWorkspace_sptr & wksp) static
Generate mapping file name.
Definition at line 145 of file FilterEventsByLogValuePreNexus.cpp.
References exists(), and Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::setupOutputEventWorkspace().
generateMappingfileName() [2/2]
static string Mantid::DataHandling::generateMappingfileName (EventWorkspace_sptr & wksp) static
Generate mapping file name from Event workspace's instrument.
Definition at line 145 of file LoadEventPreNexus2.cpp.
References exists(), and Mantid::Kernel::SingletonHolder< T >::Instance().
generatePulseidName() [1/2]
static string Mantid::DataHandling::generatePulseidName (string eventfile) static
Generate pulse ID.
Definition at line 124 of file FilterEventsByLogValuePreNexus.cpp.
References EVENT_EXTS, NUM_EXT, and PULSE_EXTS.
Referenced by Mantid::DataHandling::LoadEventPreNexus2::exec(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties().
generatePulseidName() [2/2]
static string Mantid::DataHandling::generatePulseidName (string eventfile) static
Generate Pulse ID file name from preNexus event file's name.
Definition at line 124 of file LoadEventPreNexus2.cpp.
References EVENT_EXTS, NUM_EXT, and PULSE_EXTS.
getGroupNames()
vector< string > Mantid::DataHandling::getGroupNames (const string & names)
Split a list of instrument components into a vector of strings.
Parameters
names Comma separated list of instrument components
Returns
The vector of instrument component names.
Definition at line 257 of file CreateChunkingFromInstrument.cpp.
References Mantid::Kernel::StringTokenizer::asVector(), and Mantid::Kernel::StringTokenizer::TOK_TRIM.
Referenced by Mantid::DataHandling::CreateChunkingFromInstrument::exec().
getOffsets()
std::vector< int32_t > Mantid::DataHandling::getOffsets (const DataObjects::EventWorkspace & ws, const std::string & filename, const std::string & groupName, const std::vector< std::string > & bankNames, const bool eventIDIsSpectrumNumber)
Definition at line 87 of file ParallelEventLoader.cpp.
References bankOffsets(), and bankOffsetsSpectrumNumbers().
Referenced by Mantid::DataHandling::ParallelEventLoader::loadMPI(), and Mantid::DataHandling::ParallelEventLoader::loadMultiProcess().
getResultVector()
std::vector< std::vector< Types::Event::TofEvent > * > Mantid::DataHandling::getResultVector (DataObjects::EventWorkspace & ws)
Definition at line 78 of file ParallelEventLoader.cpp.
References Mantid::DataObjects::getEventsFrom(), Mantid::DataObjects::EventWorkspace::getNumberHistograms(), and Mantid::DataObjects::EventWorkspace::getSpectrum().
Referenced by Mantid::DataHandling::ParallelEventLoader::loadMPI(), and Mantid::DataHandling::ParallelEventLoader::loadMultiProcess().
getRunnumber() [1/2]
static string Mantid::DataHandling::getRunnumber (const string & filename) static
Get run number.
Definition at line 108 of file FilterEventsByLogValuePreNexus.cpp.
References left, and right.
Referenced by Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::setupOutputEventWorkspace().
getRunnumber() [2/2]
static string Mantid::DataHandling::getRunnumber (const string & filename) static
Parse preNexus file name to get run number.
Definition at line 108 of file LoadEventPreNexus2.cpp.
References left, and right.
getScaleTypeFromStr()
ScaleUnits Mantid::DataHandling::getScaleTypeFromStr (const std::string & scaleProperty) inline
Definition at line 73 of file MeshFileIO.h.
References centimetres, metres, and millimetres.
Referenced by Mantid::DataHandling::LoadSampleShape::exec(), Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), and Mantid::DataHandling::SampleEnvironmentSpecParser::loadMeshFromSTL().
handleISISNexusFile()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::handleISISNexusFile (TimeType type, const std::string & filename)
Definition at line 44 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References Mantid::NeXus::NXClass::getString(), and StartTime.
Referenced by extractDateAndTime().
handleMuonNexusFile()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::handleMuonNexusFile (TimeType type, const std::string & filename)
Definition at line 26 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References Mantid::NeXus::NXClass::getString(), and StartTime.
Referenced by extractDateAndTime().
handleProcessedNexusFile()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::handleProcessedNexusFile (TimeType type, const std::string & filename)
Definition at line 35 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References Mantid::NeXus::NXClass::getString(), and StartTime.
Referenced by extractDateAndTime().
handleTofRawNexusFile()
Mantid::Types::Core::DateAndTime Mantid::DataHandling::handleTofRawNexusFile (TimeType type, const std::string & filename)
Definition at line 53 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References Mantid::NeXus::NXClass::getString(), and StartTime.
Referenced by extractDateAndTime().
loadNXDataSet()
template<class T > bool Mantid::DataHandling::loadNXDataSet (NeXus::NXEntry & entry, const std::string & path, T & value)
Definition at line 63 of file PatchBBY.cpp.
References Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::NeXus::NXClass::openNXDataSet(), and value.
Referenced by Mantid::DataHandling::PatchBBY::exec().
loadNXString()
bool Mantid::DataHandling::loadNXString (const NeXus::NXEntry & entry, const std::string & path, std::string & value)
Definition at line 74 of file PatchBBY.cpp.
References Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::NeXus::NXClass::openNXChar(), and value.
Referenced by Mantid::DataHandling::PatchBBY::exec().
makeCanSASRelaxedName()
std::string Mantid::DataHandling::makeCanSASRelaxedName (const std::string & input)
This makes out of an input a relaxed name, something conforming to "[A-Za-z_][\w_]*" For now "-" is converted to "_", "." is converted to "_", else we throw.
Definition at line 879 of file SaveNXcanSAS.cpp.
makeTimeOfFlightDataFuzzy()
template<typename T > void Mantid::DataHandling::makeTimeOfFlightDataFuzzy (::NeXus::File & file, T localWorkspace, const std::string & binsName, size_t start_wi = 0, size_t end_wi = 0)
Load the time of flight data.
file must have open the group containing "time_of_flight" data set. This will add a offset to all of the time-of-flight values or a random number to each time-of-flight. It should only ever be called on event files that have a "detector_1_events" group inside the "NXentry". It is an old ISIS requirement that is rarely used now.
Due to hardware issues with retro-fitting event mode to old electronics, ISIS event mode is really a very fine histogram with between 1 and 2 microseconds bins.
If we just took "middle of bin" as the true event time here then WISH observed strange ripples when they added spectra. The solution was to randomise the probability of an event within the bin.
This randomisation is now performed in the control program which also writes the "event_time_offset_shift" dataset (with a single value of "random") when it has been performed. If this dataset is present in an event file then no randomisation is performed in LoadEventNexus.
This code should remain for loading older ISIS event datasets.
Parameters
file :: The nexus file to read from.
localWorkspace :: The event workspace collection to write to.
binsName :: bins name
start_wi :: First workspace index to process
end_wi :: Last workspace index to process
Definition at line 287 of file LoadEventNexus.h.
References Mantid::DataObjects::EventList::empty(), Mantid::DataObjects::EventList::getTofs(), left, Mantid::Geometry::m, n, right, Mantid::DataObjects::EventList::setTofs(), and Mantid::DataObjects::EventList::sortTof().
Referenced by adjustTimeOfFlightISISLegacy().
MAP_PARAM() [1/3]
static const string Mantid::DataHandling::MAP_PARAM ("MappingFilename") static
Referenced by Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::LoadPreNexus::init(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::setupOutputEventWorkspace().
MAP_PARAM() [2/3]
static const string Mantid::DataHandling::MAP_PARAM ("MappingFilename") static
MAP_PARAM() [3/3]
static const string Mantid::DataHandling::MAP_PARAM ("MappingFilename") static
nexus_print_error()
void Mantid::DataHandling::nexus_print_error (void * pD, char * text)
Definition at line 661 of file SaveToSNSHistogramNexus.cpp.
NUM_EXT_EVENT_NEXUS()
const int Mantid::DataHandling::NUM_EXT_EVENT_NEXUS (3)
Number of event nexus extensions.
Referenced by Mantid::DataHandling::DetermineChunking::init().
NUM_EXT_HISTO_NEXUS()
const int Mantid::DataHandling::NUM_EXT_HISTO_NEXUS (1)
Number of histogram nexus extensions.
Referenced by Mantid::DataHandling::DetermineChunking::init().
NUM_EXT_PRENEXUS()
const int Mantid::DataHandling::NUM_EXT_PRENEXUS (1)
Number of prenexus extensions.
Referenced by Mantid::DataHandling::DetermineChunking::init().
NUM_EXT_RAW()
const int Mantid::DataHandling::NUM_EXT_RAW (1)
Number of raw file extensions.
Referenced by Mantid::DataHandling::DetermineChunking::init().
numEvents()
std::size_t Mantid::DataHandling::numEvents (::NeXus::File & file, bool & hasTotalCounts, bool & oldNeXusFileNames, const std::string & prefix, const NexusHDF5Descriptor & descriptor)
Get the number of events in the currently opened group.
Parameters
file The handle to the nexus file opened to the group to look at.
hasTotalCounts Whether to try looking at the total_counts field. This variable will be changed if the field is not there.
oldNeXusFileNames Whether to try using old names. This variable will be changed if it is determined that old names are being used.
prefix current entry name prefix (e.g. /entry)
descriptor input containing metadata information
Returns
The number of events.
Definition at line 491 of file LoadEventNexus.cpp.
References Mantid::Kernel::NexusHDF5Descriptor::isEntry(), and numEvents().
Referenced by Mantid::DataObjects::FakeMD::addFakeEllipsoid(), Mantid::SingleCrystalDiffractionTestHelper::WorkspaceBuilder::addPeakByHKL(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::DataHandling::LoadEMU< FD >::calibrateDopplerPhase(), Mantid::DataObjects::EventList::compressEventsParallelHelper(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::MDAlgorithms::ConvToMDEventsWS::convertEventList(), Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::convertEvents(), Mantid::DataObjects::MDEventsTestHelper::createDiffractionEventWorkspace(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), WorkspaceCreationHelper::createEventWorkspace(), Mantid::Algorithms::CreateSampleWorkspace::createEventWorkspace(), WorkspaceCreationHelper::createEventWorkspaceWithStartTime(), Mantid::DataObjects::EventList::createFromHistogram(), Mantid::DataObjects::MDLeanEvent< nd >::dataToEvents(), Mantid::DataObjects::MDEvent< nd >::dataToEvents(), Mantid::DataObjects::EventList::equals(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::MDAlgorithms::TransformMD::exec(), Mantid::Algorithms::UnwrapSNS::execEvent(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEvents(), Mantid::DataObjects::EventList::getPulseTimeMax(), Mantid::DataObjects::EventList::getPulseTimeMin(), Mantid::DataObjects::EventList::getPulseTimeMinMax(), Mantid::DataObjects::EventList::getTimeAtSampleMax(), Mantid::DataObjects::EventList::getTimeAtSampleMin(), Mantid::DataObjects::EventList::getTofMax(), Mantid::DataObjects::EventList::getTofMin(), Mantid::DataHandling::LoadBankFromDiskTask::LoadBankFromDiskTask(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataObjects::MDEventsTestHelper::makeFakeMDEventWorkspace(), Mantid::DataObjects::MDEventsTestHelper::makeFakeMDHistoWorkspace(), Mantid::DataObjects::MDEventsTestHelper::makeFakeMDHistoWorkspaceWithMDFrame(), Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEW(), Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEWwithMDFrame(), numEvents(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEvents(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::LoadNexusMonitors2::readEventMonitorEntry(), Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree(), Mantid::DataHandling::LoadBankFromDiskTask::run(), and Mantid::DataObjects::MDHistoWorkspace::setTo().
OUT_PARAM() [1/2]
static const string Mantid::DataHandling::OUT_PARAM ("OutputWorkspace") static
Referenced by Mantid::DataHandling::FilterEventsByLogValuePreNexus::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), and Mantid::DataHandling::LoadEventPreNexus2::init().
OUT_PARAM() [2/2]
static const string Mantid::DataHandling::OUT_PARAM ("OutputWorkspace") static
PARALLEL_PARAM() [1/2]
static const string Mantid::DataHandling::PARALLEL_PARAM ("UseParallelProcessing") static
PARALLEL_PARAM() [2/2]
static const string Mantid::DataHandling::PARALLEL_PARAM ("UseParallelProcessing") static
parentName() [1/2]
string Mantid::DataHandling::parentName (const IComponent_const_sptr & comp, const string & prefix)
Find the name of the parent of the component that starts with the supplied prefix.
Parameters
comp The component to find the parent of.
prefix Prefix of parent names to look for.
Returns
The correct parent name. This is an empty string if the name isn't found.
Definition at line 203 of file CreateChunkingFromInstrument.cpp.
References parentName(), and startsWith().
Referenced by Mantid::DataHandling::CreateChunkingFromInstrument::exec(), and parentName().
parentName() [2/2]
string Mantid::DataHandling::parentName (const IComponent_const_sptr & comp, const vector< string > & names)
Find the name of the parent of the component that is in the list of parents that are being searched for.
Parameters
comp The component to find the parent of.
names List of parent names to look for.
Returns
The correct parent name. This is an empty string if the name isn't found.
Definition at line 229 of file CreateChunkingFromInstrument.cpp.
References parentName().
PID_PARAM() [1/2]
static const string Mantid::DataHandling::PID_PARAM ("SpectrumList") static
Referenced by Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties().
PID_PARAM() [2/2]
static const string Mantid::DataHandling::PID_PARAM ("SpectrumList") static
populateDataBlockCompositeWithContainer()
template<typename T > void DLLExport Mantid::DataHandling::populateDataBlockCompositeWithContainer (DataBlockComposite & dataBlockComposite, T & indexContainer, int64_t nArray, int numberOfPeriods, size_t numberOfChannels, std::vector< specnum_t > monitorSpectra)
Populates a DataBlockComposite with DataBlocks which are extracted from a indexable collection (array-type).
Note that std::is_array does not work on std::shared_array which is one of the use cases. Hence this function could get abused. Monitor spectra get their own data block
Parameters
dataBlockComposite the detector block composite which will get populated
indexContainer the container of indices
nArray the number of array elements
numberOfPeriods the number of periods
numberOfChannels the number of channels
monitorSpectra a collection of monitor spectrum numbers
Definition at line 62 of file DataBlockComposite.h.
References Mantid::DataHandling::DataBlockComposite::addDataBlock(), index, Mantid::DataHandling::DataBlock::setMaxSpectrumID(), and Mantid::DataHandling::DataBlock::setMinSpectrumID().
Referenced by Mantid::DataHandling::LoadISISNexus2::checkOptionalProperties(), and Mantid::DataHandling::LoadISISNexus2::findSpectraDetRangeInFile().
PULSEID_PARAM() [1/2]
static const string Mantid::DataHandling::PULSEID_PARAM ("PulseidFilename") static
Referenced by Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties().
PULSEID_PARAM() [2/2]
static const string Mantid::DataHandling::PULSEID_PARAM ("PulseidFilename") static
RUNINFO_FILENAME()
static const std::string Mantid::DataHandling::RUNINFO_FILENAME ("RunInfoFilename") static
Referenced by Mantid::DataHandling::LoadPreNexusMonitors::exec(), and Mantid::DataHandling::LoadPreNexusMonitors::init().
RUNINFO_PARAM()
static const string Mantid::DataHandling::RUNINFO_PARAM ("Filename") static
Referenced by Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::LoadPreNexus::init(), and Mantid::DataHandling::LoadPreNexus::runLoadMonitors().
startsWith()
bool Mantid::DataHandling::startsWith (const string & str, const string & prefix)
Returns true if str starts with prefix.
Parameters
str The string to check.
prefix The prefix to look for.
Returns
true if str starts with prefix.
Definition at line 186 of file CreateChunkingFromInstrument.cpp.
Referenced by Mantid::DataHandling::LoadPDFgetNFile::confidence(), parentName(), and Mantid::DataHandling::LoadDNSEvent::parse_File().
store_value()
void Mantid::DataHandling::store_value (const DataObjects::Workspace2D_sptr & ws, int specID, double value, double error, double wavelength, double dwavelength)
Convenience function to store a detector value into a given spectrum.
Note that this type of data doesn't use TOD, so that we use a single dummy bin in X. Each detector is defined as a spectrum of length 1.
Parameters
ws workspace
specID ID of the spectrum to store the value in
value value to store [count]
error error on the value [count]
wavelength wavelength value [Angstrom]
dwavelength error on the wavelength [Angstrom]
Definition at line 78 of file LoadSpice2D.cpp.
References error, value, Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by Mantid::DataHandling::LoadSpice2D::createWorkspace().
toMeshObject()
const Geometry::MeshObject & Mantid::DataHandling::toMeshObject (const Geometry::IObject & object)
Function to convert an IObject to a mesh, and throw if this can't be done.
Parameters
object The IObject to convert.
Returns
const Geometry::MeshObject& The converted MeshObject.
Definition at line 184 of file SaveSampleEnvironmentAndShape.cpp.
Referenced by Mantid::DataHandling::SaveSampleEnvironmentAndShape::exec().
UDlesserExecCount()
bool Mantid::DataHandling::UDlesserExecCount (const NXClassInfo & elem1, const NXClassInfo & elem2)
to sort the algorithmhistory vector
Binary predicate function object to sort the AlgorithmHistory vector by execution order.
Parameters
elem1 :: first element in the vector
elem2 :: second element in the vecor
Definition at line 1960 of file LoadNexusProcessed.cpp.
References Mantid::NeXus::NXClassInfo::nxname.
VETOFLAG() [1/2]
static const uint64_t Mantid::DataHandling::VETOFLAG (72057594037927935) static
Veto mask as 0xFF000000000.
Referenced by Mantid::DataHandling::LoadEventPreNexus2::unmaskVetoEventIndex(), and Mantid::DataHandling::FilterEventsByLogValuePreNexus::unmaskVetoEventIndexes().
VETOFLAG() [2/2]
static const uint64_t Mantid::DataHandling::VETOFLAG (72057594037927935) static
Veto flag: 0xFF00000000000.
vzintermediatePixelIDComp()
bool Mantid::DataHandling::vzintermediatePixelIDComp (IntermediateEvent x, IntermediateEvent y)
Comparator for sorting dasevent lists.
Definition at line 1112 of file LoadEventPreNexus2.cpp.
References Mantid::Geometry::x, and Mantid::Geometry::y.
whichNexusType()
NexusType Mantid::DataHandling::whichNexusType (const std::string & filename)
Definition at line 62 of file StartAndEndTimeFromNexusFileExtractor.cpp.
References count, Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::NeXus::getNexusEntryTypes(), Mantid::NeXus::NXClass::groups(), ISIS, Muon, Mantid::DataHandling::LoadNexus::muonTD, Mantid::NeXus::NXRoot::openEntry(), Mantid::NeXus::NXClass::openNXChar(), Processed, Mantid::DataHandling::LoadNexus::pulsedTD, and TofRaw.
Referenced by extractDateAndTime().
WORKSPACE_OUT()
static const std::string Mantid::DataHandling::WORKSPACE_OUT ("OutputWorkspace") static
Referenced by Mantid::DataHandling::LoadPreNexusMonitors::init().
Variable Documentation
CONSTANT
const double Mantid::DataHandling::CONSTANT = (PhysicalConstants::h * 1e10) / (2.0 * PhysicalConstants::NeutronMass * 1e6)
Definition at line 130 of file LoadDspacemap.cpp.
Referenced by Mantid::DataHandling::LoadDspacemap::CalculateOffsetsFromVulcanFactors().
CONTIN_ID_VALUE
constexpr uint64_t Mantid::DataHandling::CONTIN_ID_VALUE = 0x4F static constexpr
Definition at line 17 of file LoadNGEM.h.
Referenced by Mantid::DataHandling::CoincidenceEvent::check(), Mantid::DataHandling::GenericEvent::check(), and Mantid::DataHandling::T0FrameEvent::check().
CURRENT_CONVERSION [1/2]
const double Mantid::DataHandling::CURRENT_CONVERSION = 1.e-6 / 3600. static
Conversion factor between picoColumbs and microAmp*hours.
Definition at line 91 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by Mantid::DataHandling::FilterEventsByLogValuePreNexus::readPulseidFile(), and Mantid::DataHandling::LoadEventPreNexus2::readPulseidFile().
CURRENT_CONVERSION [2/2]
const double Mantid::DataHandling::CURRENT_CONVERSION = 1.e-6 / 3600. static
Conversion factor between picoColumbs and microAmp*hours.
Definition at line 90 of file LoadEventPreNexus2.cpp.
ERROR_PID [1/2]
const PixelType Mantid::DataHandling::ERROR_PID = 0x80000000 static
All pixel ids with matching this mask are errors.
Definition at line 85 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEventsLinear(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEventsLinear(), and Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear().
ERROR_PID [2/2]
const PixelType Mantid::DataHandling::ERROR_PID = 0x80000000 static
All pixel ids with matching this mask are errors.
Definition at line 84 of file LoadEventPreNexus2.cpp.
EVENT_EXTS [1/2]
const string Mantid::DataHandling::EVENT_EXTS[] static
Initial value:
= {"_neutron_event.dat",  "_neutron0_event.dat", "_neutron1_event.dat",
                                    "_neutron2_event.dat", "_neutron3_event.dat", "_live_neutron_event.dat"}
Definition at line 95 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by generatePulseidName(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::runLoadInstrument(), and Mantid::DataHandling::LoadEventPreNexus2::runLoadInstrument().
EVENT_EXTS [2/2]
const string Mantid::DataHandling::EVENT_EXTS[] static
Initial value:
= {"_neutron_event.dat",     "_neutron0_event.dat", "_neutron1_event.dat",
                                    "_neutron2_event.dat",    "_neutron3_event.dat", "_neutron4_event.dat",
                                    "_live_neutron_event.dat"}
Definition at line 94 of file LoadEventPreNexus2.cpp.
EVENT_ID_MASK
constexpr uint64_t Mantid::DataHandling::EVENT_ID_MASK = 0x40 static constexpr
Definition at line 18 of file LoadNGEM.h.
Referenced by Mantid::DataHandling::GenericEvent::check().
EVENT_NEXUS_EXT
const std::string Mantid::DataHandling::EVENT_NEXUS_EXT[NUM_EXT_EVENT_NEXUS] = {"_event.nxs", ".nxs", ".nxs.h5"}
Valid extensions for event nexus files.
Definition at line 51 of file DetermineChunking.cpp.
Referenced by Mantid::DataHandling::DetermineChunking::getFileType(), and Mantid::DataHandling::DetermineChunking::init().
EXTERNAL
char const* const Mantid::DataHandling::EXTERNAL = "EXTERNAL" static
Definition at line 35 of file PatchBBY.cpp.
Referenced by Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::PatchBBY::init().
FilenameStr [1/2]
char const* const Mantid::DataHandling::FilenameStr = "Filename" static
Definition at line 54 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMUTar::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::PatchBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadPLN::init(), Mantid::DataHandling::PatchBBY::init(), and Mantid::DataHandling::LoadEMU< FD >::init().
FilenameStr [2/2]
char const* const Mantid::DataHandling::FilenameStr = "Filename" static
Definition at line 34 of file PatchBBY.cpp.
FilterByTimeStartStr
char const* const Mantid::DataHandling::FilterByTimeStartStr = "FilterByTimeStart" static
Definition at line 60 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadPLN::init(), and Mantid::DataHandling::LoadEMU< FD >::init().
FilterByTimeStopStr
char const* const Mantid::DataHandling::FilterByTimeStopStr = "FilterByTimeStop" static
Definition at line 61 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadPLN::init(), and Mantid::DataHandling::LoadEMU< FD >::init().
FilterByTofMaxStr
char const* const Mantid::DataHandling::FilterByTofMaxStr = "FilterByTofMax" static
Definition at line 58 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY::init().
FilterByTofMinStr
char const* const Mantid::DataHandling::FilterByTofMinStr = "FilterByTofMin" static
Definition at line 57 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY::init().
FLOAT32
const char Mantid::DataHandling::FLOAT32 = 'f'
Definition at line 45 of file LoadSpiceXML2DDet.cpp.
Referenced by Mantid::DataHandling::SpiceXMLNode::isDouble(), and Mantid::DataHandling::SpiceXMLNode::setParameters().
g_log
Kernel::Logger Mantid::DataHandling::g_log("LoadCSNSNexus") ("LoadCSNSNexus")
HISTO_BINS_X
const size_t Mantid::DataHandling::HISTO_BINS_X = 240 static
Definition at line 47 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::PLN::EventProcessor::addEvent(), Mantid::DataHandling::LoadBBY::createRoiVector(), Mantid::DataHandling::LoadEMU< FD >::createRoiVector(), Mantid::DataHandling::LoadPLN::createRoiVector(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadPLN::exec(), and Mantid::DataHandling::LoadBBY::loadEvents().
HISTO_BINS_Y
const size_t Mantid::DataHandling::HISTO_BINS_Y = 256 static
Definition at line 48 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::createRoiVector(), Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY::loadEvents().
HISTO_NEXUS_EXT
const std::string Mantid::DataHandling::HISTO_NEXUS_EXT[NUM_EXT_HISTO_NEXUS] = {"_histo.nxs"}
Valid extensions for histogram nexus files.
Definition at line 54 of file DetermineChunking.cpp.
Referenced by Mantid::DataHandling::DetermineChunking::getFileType(), and Mantid::DataHandling::DetermineChunking::init().
HistoryStr
char const* const Mantid::DataHandling::HistoryStr = "History.log" static
Definition at line 33 of file PatchBBY.cpp.
Referenced by Mantid::DataHandling::PatchBBY::exec().
INT32
const char Mantid::DataHandling::INT32 = 'i'
Definition at line 46 of file LoadSpiceXML2DDet.cpp.
Referenced by Mantid::DataHandling::SpiceXMLNode::isInteger(), and Mantid::DataHandling::SpiceXMLNode::setParameters().
INTERNAL
char const* const Mantid::DataHandling::INTERNAL = "INTERNAL" static
Definition at line 36 of file PatchBBY.cpp.
Referenced by Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::PatchBBY::init().
MaskStr
char const* const Mantid::DataHandling::MaskStr = "Mask" static
Definition at line 55 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadPLN::init(), and Mantid::DataHandling::LoadEMU< FD >::init().
MAX_BUFFER_BYTES_SIZE
const unsigned int Mantid::DataHandling::MAX_BUFFER_BYTES_SIZE = 1500
Definition at line 71 of file LoadDNSEvent.cpp.
Referenced by Mantid::DataHandling::LoadDNSEvent::split_File().
MAX_TOF_UINT32 [1/2]
const uint32_t Mantid::DataHandling::MAX_TOF_UINT32 = std::numeric_limits<uint32_t>::max() static
The maximum possible tof as native type.
Definition at line 87 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEvents(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEventsLinear(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEvents(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEventsLinear(), and Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear().
MAX_TOF_UINT32 [2/2]
const uint32_t Mantid::DataHandling::MAX_TOF_UINT32 = std::numeric_limits<uint32_t>::max() static
The maximum possible tof as native type.
Definition at line 86 of file LoadEventPreNexus2.cpp.
NUM_EXT [1/2]
const int Mantid::DataHandling::NUM_EXT = 6 static
Definition at line 99 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by generatePulseidName(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::runLoadInstrument(), and Mantid::DataHandling::LoadEventPreNexus2::runLoadInstrument().
NUM_EXT [2/2]
const int Mantid::DataHandling::NUM_EXT = 7 static
Definition at line 99 of file LoadEventPreNexus2.cpp.
NUM_PER_LINE
const unsigned int Mantid::DataHandling::NUM_PER_LINE = 8 static
set to the number of numbers on each line (the length of lines is hard-coded in other parts of the code too)
Definition at line 76 of file SaveSPE.cpp.
Referenced by Mantid::DataHandling::SaveSPE::writeBins(), Mantid::DataHandling::SaveSPE::writeHists(), Mantid::DataHandling::SaveSPE::writeSPEFile(), and Mantid::DataHandling::SaveSPE::writeValue().
PatchableProperties
PropertyInfo Mantid::DataHandling::PatchableProperties[] static
Initial value:
= {
    {"Calibration", "Bm1Counts", TYPE_INT},
    {"Calibration", "AttPos", TYPE_DBL},
    {"Velocity Selector and Choppers", "MasterChopperFreq", TYPE_DBL},
    {"Velocity Selector and Choppers", "T0ChopperFreq", TYPE_DBL},
    {"Velocity Selector and Choppers", "T0ChopperPhase", TYPE_DBL},
    {"Velocity Selector and Choppers", "FrameSource", TYPE_STR},
    {"Velocity Selector and Choppers", "Wavelength", TYPE_DBL},
    {"Geometry Setup", "L1", TYPE_DBL},
    {"Geometry Setup", "LTofDet", TYPE_DBL},
    {"Geometry Setup", "L2Det", TYPE_DBL},
    {"Geometry Setup", "L2CurtainL", TYPE_DBL},
    {"Geometry Setup", "L2CurtainR", TYPE_DBL},
    {"Geometry Setup", "L2CurtainU", TYPE_DBL},
    {"Geometry Setup", "L2CurtainD", TYPE_DBL},
    {"Geometry Setup", "CurtainL", TYPE_DBL},
    {"Geometry Setup", "CurtainR", TYPE_DBL},
    {"Geometry Setup", "CurtainU", TYPE_DBL},
    {"Geometry Setup", "CurtainD", TYPE_DBL},
}
Definition at line 37 of file PatchBBY.cpp.
Referenced by Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::PatchBBY::init().
PIXEL_PER_TUBE
const unsigned int Mantid::DataHandling::PIXEL_PER_TUBE = 1024
Definition at line 72 of file LoadDNSEvent.cpp.
Referenced by Mantid::DataHandling::LoadDNSEvent::exec().
PRENEXUS_EXT
const std::string Mantid::DataHandling::PRENEXUS_EXT[NUM_EXT_PRENEXUS] = {"_runinfo.xml"}
Valid extensions for prenexus files.
Definition at line 48 of file DetermineChunking.cpp.
Referenced by Mantid::DataHandling::DetermineChunking::getFileType(), and Mantid::DataHandling::DetermineChunking::init().
Progress_LoadBinFile
const size_t Mantid::DataHandling::Progress_LoadBinFile = 48 static
Definition at line 50 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::loadEvents(), Mantid::DataHandling::EMU::loadEvents(), and Mantid::DataHandling::PLN::loadEvents().
Progress_ReserveMemory
const size_t Mantid::DataHandling::Progress_ReserveMemory = 4 static
Definition at line 51 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), and Mantid::DataHandling::LoadPLN::exec().
Progress_Total
const size_t Mantid::DataHandling::Progress_Total = 2 * Progress_LoadBinFile + Progress_ReserveMemory static
Definition at line 52 of file LoadBBY.cpp.
Referenced by Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), and Mantid::DataHandling::LoadPLN::exec().
PULSE_EXTS [1/2]
const string Mantid::DataHandling::PULSE_EXTS[] static
Initial value:
= {"_pulseid.dat",  "_pulseid0.dat", "_pulseid1.dat",
                                    "_pulseid2.dat", "_pulseid3.dat", "_live_pulseid.dat"}
Definition at line 97 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by generatePulseidName(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::init(), and Mantid::DataHandling::LoadEventPreNexus2::init().
PULSE_EXTS [2/2]
const string Mantid::DataHandling::PULSE_EXTS[] static
Initial value:
= {"_pulseid.dat",  "_pulseid0.dat", "_pulseid1.dat",    "_pulseid2.dat",
                                    "_pulseid3.dat", "_pulseid4.dat", "_live_pulseid.dat"}
Definition at line 97 of file LoadEventPreNexus2.cpp.
rad2deg
constexpr double Mantid::DataHandling::rad2deg = 180.0 / M_PI constexpr
Definition at line 170 of file FindDetectorsPar.cpp.
Referenced by Mantid::Crystal::FindSXPeaksHelper::AbsoluteCompareStrategy::AbsoluteCompareStrategy(), Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::Kernel::Quat::getEulerAngles(), Mantid::Kernel::V3D::getSpherical(), Mantid::DataHandling::FindDetectorsPar::populate_values_from_file(), and Mantid::DataHandling::SaveAscii2::populateAngleMetaData().
RAW_EXT
const std::string Mantid::DataHandling::RAW_EXT[NUM_EXT_RAW] = {".raw"}
Valid extensions for ISIS raw files.
Definition at line 57 of file DetermineChunking.cpp.
Referenced by Mantid::DataHandling::DetermineChunking::getFileType(), and Mantid::DataHandling::DetermineChunking::init().
STRING
const char Mantid::DataHandling::STRING = 's'
Definition at line 44 of file LoadSpiceXML2DDet.cpp.
Referenced by Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::Crystal::SaveHKL::exec(), and Mantid::DataHandling::SpiceXMLNode::isString().
TOF_CONVERSION [1/2]
const double Mantid::DataHandling::TOF_CONVERSION = .1 static
Conversion factor between 100 nanoseconds and 1 microsecond.
Definition at line 89 of file FilterEventsByLogValuePreNexus.cpp.
Referenced by Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEvents(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEventsLinear(), Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEventsLinear(), and Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear().
TOF_CONVERSION [2/2]
const double Mantid::DataHandling::TOF_CONVERSION = .1 static
Conversion factor between 100 nanoseconds and 1 microsecond.
Definition at line 88 of file LoadEventPreNexus2.cpp.