Mantid: Mantid::CurveFitting::Functions::GramCharlierComptonProfile Class Reference
Mantid::CurveFitting::Functions::GramCharlierComptonProfile Class Reference
Implements a function to calculate the Compton profile of a nucleus using a Gram-Charlier approximation convoluted with an instrument resolution function that is approximated by a Voigt function.
#include <GramCharlierComptonProfile.h>
Public Member Functions
GramCharlierComptonProfile ()
Default constructor required by factory.
Public Member Functions inherited from Mantid::CurveFitting::Functions::ComptonProfile
ComptonProfile ()
Default constructor required for factory.
virtual size_t fillConstraintMatrix (Kernel::DblMatrix &cmatrix, const size_t start, const HistogramData::HistogramE &errors) const =0
Fill the appropriate columns of the given matrix with the values of the mass profile.
virtual std::vector< size_t > intensityParameterIndices () const =0
Returns the indices of the intensity parameters.
virtual void massProfile (double *result, const size_t nData) const =0
Override to calculate the value of the profile for this mass and store in the given array.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void function1D (double *out, const double *xValues, const size_t nData) const override
Calculates the value of the function for each x value and stores in the given output array.
void setUpForFit () override
Ensure the object is ready to be fitted.
void buildCaches ()
Initiate a Y-space value chache rebuild when workspace of mass are changed.
void cacheYSpaceValues (const HistogramData::Points &tseconds, const Algorithms::DetectorParams &detpar, const ResolutionParams &respar)
Pre-calculate the Y-space values with specified resolution parameters.
void disableLogging ()
Turn off logger.
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void function (const FunctionDomain &domain, FunctionValues &values) const =0
Evaluates the function for all arguments in the domain.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies ()
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::IFunction1D
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
virtual void function1D (double *out, const double *xValues, const size_t nData) const =0
Function you want to fit to.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
virtual void functionDeriv1D (Jacobian *jacobian, const double *xValues, const size_t nData)
Derivatives of function with respect to active parameters.
Private Member Functions
void addFSETerm (std::vector< double > &lhs) const
Add FSE term based on current parameter setting.
void addMassProfile (double *result, const unsigned int npoly) const
Compute the contribution to mass profile nth Hermite polynomial coefficient.
void cacheYSpaceValues (const HistogramData::Points &tseconds, const Algorithms::DetectorParams &detpar) override
Pre-calculate the Y-space values.
void convoluteVoigt (double *result, const size_t nData, const std::vector< double > &profile) const
Convolute with resolution.
void declareAttributes () override
Declare non-parameter attributes.
void declareGramCharlierParameters ()
Declare the Gram-Charlier (Hermite) coefficients.
void declareParameters () override
Declare the function parameters.
size_t fillConstraintMatrix (Kernel::DblMatrix &cmatrix, const size_t start, const HistogramData::HistogramE &errors) const override
Fill in the columns of the matrix for this mass.
std::vector< size_t > intensityParameterIndices () const override
Returns the indices of the intensity parameters.
void massProfile (double *result, const size_t nData) const override
Compute the sum for all Hermite polynomial coefficents.
std::string name () const override
A string identifier for this function.
void setAttribute (const std::string &name, const Attribute &value) override
Set an attribute value (and possibly cache its value)
void setHermiteCoefficients (const std::string &coeffs)
Parse the active hermite polynomial coefficents.
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Called by the framework when a workspace is set.
Private Attributes
std::vector< short > m_hermite
The active hermite coefficents.
std::vector< double > m_qfine
Interpolated Q values over a finer Y range.
bool m_userFixedFSE
Flag to hold whether the FSE parameter is fixed by the user.
std::vector< std::vector< double > > m_voigt
Holds the value of the Voigt function for each coarse y-space point as this is an expensive calculation.
std::vector< double > m_voigtProfile
Holds the result Voigt multiplied by the profile function for the extended Y space range.
std::vector< double > m_yfine
Y values over a finer range.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Types inherited from Mantid::API::IFunction1D
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Protected Member Functions inherited from Mantid::CurveFitting::Functions::ComptonProfile
void declareParameters () override
Declare parameters that will never participate in the fit.
const std::vector< double > & e0 () const
Access e0 values.
double mass () const
Access the mass.
const std::vector< double > & modQ () const
Access Q values cache.
void voigtApprox (std::vector< double > &voigt, const std::vector< double > &yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const
Compute Voigt function.
void voigtApproxDiff (std::vector< double > &voigtDiff, const std::vector< double > &yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const
Compute Voigt function interpolated around the given values.
const std::vector< double > & ySpace () const
Access y-values cache.
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::IFunction1D
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Protected Attributes inherited from Mantid::CurveFitting::Functions::ComptonProfile
double m_endX
Kernel::Logger m_log
Logger.
std::shared_ptr< VesuvioResolution > m_resolutionFunction
Vesuvio resolution function.
double m_startX
std::shared_ptr< API::IPeakFunction > m_voigt
Voigt function.
std::shared_ptr< const API::MatrixWorkspace > m_workspace
Current workspace.
size_t m_wsIndex
Current workspace index, required to access instrument parameters.
std::vector< double > m_yspace
std::vector< double > m_modQ
Q-values.
std::vector< double > m_e0
Incident energies.
double m_mass
Atomic mass.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Static Protected Attributes inherited from Mantid::API::IFunction1D
static Kernel::Logger g_log
Logger instance.
Detailed Description
Implements a function to calculate the Compton profile of a nucleus using a Gram-Charlier approximation convoluted with an instrument resolution function that is approximated by a Voigt function.
Definition at line 22 of file GramCharlierComptonProfile.h.
Constructor & Destructor Documentation
GramCharlierComptonProfile()
Mantid::CurveFitting::Functions::GramCharlierComptonProfile::GramCharlierComptonProfile ()
Default constructor required by factory.
Definition at line 74 of file GramCharlierComptonProfile.cpp.
Member Function Documentation
addFSETerm()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::addFSETerm (std::vector< double > & lhs) const private
Add FSE term based on current parameter setting.
Adds the FSE term to the result in the vector given.
Parameters
lhs Existing vector that the result should be added to
Definition at line 288 of file GramCharlierComptonProfile.cpp.
References Mantid::API::ParamFunction::getParameter(), m_qfine, m_userFixedFSE, m_yfine, Mantid::CurveFitting::Functions::WIDTH_PARAM, and Mantid::Geometry::y.
Referenced by fillConstraintMatrix(), and massProfile().
addMassProfile()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::addMassProfile (double * result, const unsigned int npoly) const private
Compute the contribution to mass profile nth Hermite polynomial coefficient.
Uses a Gram-Charlier series approximation for the mass and convolutes it with the Voigt instrument resolution function.
Also multiplies by the mass*e_i^0.1/q. Sums it with the given result
Parameters
result An pre-sized output array that should be filled with the results. Size is fixed at NFINE_Y
npoly An integer denoting the polynomial to calculate
Definition at line 263 of file GramCharlierComptonProfile.cpp.
References Mantid::API::ParamFunction::getParameter(), m_yfine, Mantid::CurveFitting::Functions::WIDTH_PARAM, and Mantid::Geometry::y.
Referenced by fillConstraintMatrix(), and massProfile().
cacheYSpaceValues()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::cacheYSpaceValues (const HistogramData::Points & tseconds, const Algorithms::DetectorParams & detpar) override private virtual
Pre-calculate the Y-space values.
Parameters
tseconds A vector containing the time-of-flight values in seconds
detpar Structure containing detector parameters
Reimplemented from Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 351 of file GramCharlierComptonProfile.cpp.
References Mantid::CurveFitting::Functions::ComptonProfile::cacheYSpaceValues(), Mantid::API::IFunction::isActive(), m_qfine, Mantid::CurveFitting::Functions::ComptonProfile::m_resolutionFunction, m_userFixedFSE, m_voigt, m_voigtProfile, m_yfine, Mantid::CurveFitting::Functions::ComptonProfile::modQ(), Mantid::API::ParamFunction::parameterIndex(), and Mantid::CurveFitting::Functions::ComptonProfile::ySpace().
convoluteVoigt()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::convoluteVoigt (double * result, const size_t nData, const std::vector< double > & profile) const private
Convolute with resolution.
Convolute with resolution and multiply by the final ei^0.1*mass/q prefactor.
Parameters
result Output array that holds the result of the convolution
nData The length of the array
profile The input mass profile
Definition at line 317 of file GramCharlierComptonProfile.cpp.
References Mantid::CurveFitting::Functions::ComptonProfile::e0(), m_voigt, m_voigtProfile, m_yfine, Mantid::CurveFitting::Functions::ComptonProfile::mass(), and Mantid::CurveFitting::Functions::ComptonProfile::modQ().
Referenced by fillConstraintMatrix(), and massProfile().
declareAttributes()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::declareAttributes () override private virtual
Declare non-parameter attributes.
Reimplemented from Mantid::API::IFunction.
Definition at line 90 of file GramCharlierComptonProfile.cpp.
References Mantid::API::IFunction::declareAttribute(), and Mantid::API::IFunction::declareAttributes().
declareGramCharlierParameters()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::declareGramCharlierParameters () private
Declare the Gram-Charlier (Hermite) coefficients.
Currently the first mass is assumed to be fitted with the Gram-Charlier expansion.
The input string gives whether each even Hermite polnomial is active or not
Definition at line 137 of file GramCharlierComptonProfile.cpp.
References Mantid::API::ParamFunction::declareParameter(), and m_hermite.
Referenced by setHermiteCoefficients().
declareParameters()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::declareParameters () override private virtual
Declare the function parameters.
Reimplemented from Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 82 of file GramCharlierComptonProfile.cpp.
References Mantid::API::ParamFunction::declareParameter(), Mantid::CurveFitting::Functions::ComptonProfile::declareParameters(), and Mantid::CurveFitting::Functions::WIDTH_PARAM.
fillConstraintMatrix()
size_t Mantid::CurveFitting::Functions::GramCharlierComptonProfile::fillConstraintMatrix (Kernel::DblMatrix & cmatrix, const size_t start, const HistogramData::HistogramE & errors) const override private virtual
Fill in the columns of the matrix for this mass.
Fills in a column for each active hermite polynomial, starting at the given index.
Parameters
cmatrix InOut matrix whose columns should be set to the mass profile for each active hermite polynomial
start Index of the column to start on
errors Data errors array
Returns
The number of columns filled
Implements Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 181 of file GramCharlierComptonProfile.cpp.
References addFSETerm(), addMassProfile(), convoluteVoigt(), m_hermite, m_userFixedFSE, Mantid::Kernel::Matrix< T >::setColumn(), and Mantid::CurveFitting::Functions::ComptonProfile::ySpace().
intensityParameterIndices()
std::vector< size_t > Mantid::CurveFitting::Functions::GramCharlierComptonProfile::intensityParameterIndices () const override private virtual
Returns the indices of the intensity parameters.
Implements Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 151 of file GramCharlierComptonProfile.cpp.
References Mantid::API::IFunction::isActive(), m_hermite, and Mantid::API::ParamFunction::parameterIndex().
massProfile()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::massProfile (double * result, const size_t nData) const override private virtual
Compute the sum for all Hermite polynomial coefficents.
Uses a Gram-Charlier series approximation for the mass and convolutes it with the Voigt instrument resolution function.
Also multiplies by the mass*e_i^0.1/q
Parameters
result An pre-sized output array that should be filled with the results
nData The length of the array
Implements Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 234 of file GramCharlierComptonProfile.cpp.
References addFSETerm(), addMassProfile(), convoluteVoigt(), m_hermite, and UNUSED_ARG.
name()
std::string Mantid::CurveFitting::Functions::GramCharlierComptonProfile::name () const override private virtual
A string identifier for this function.
Returns
A string containing the name of the function
Implements Mantid::API::IFunction.
Definition at line 80 of file GramCharlierComptonProfile.cpp.
Referenced by setAttribute().
setAttribute()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::setAttribute (const std::string & name, const Attribute & value) override private virtual
Set an attribute value (and possibly cache its value)
Parameters
name The name of the attribute
value The attribute's value
Reimplemented from Mantid::API::IFunction.
Definition at line 103 of file GramCharlierComptonProfile.cpp.
References name(), Mantid::API::IFunction::setAttribute(), setHermiteCoefficients(), and value.
setHermiteCoefficients()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::setHermiteCoefficients (const std::string & coeffs) private
Parse the active hermite polynomial coefficents.
Throws if the string is empty and contains something other than numbers.
Parameters
coeffs A string of space separated 1/0 values indicating which polynomial coefficients to include in the fitting
Definition at line 114 of file GramCharlierComptonProfile.cpp.
References declareGramCharlierParameters(), m_hermite, and value.
Referenced by setAttribute().
setMatrixWorkspace()
void Mantid::CurveFitting::Functions::GramCharlierComptonProfile::setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override private virtual
Called by the framework when a workspace is set.
Used to cache some values when the workspace has been set.
Parameters
workspace A pointer to the workspace
wi A workspace index
startX Starting x-vaue (unused).
endX Ending x-vaue (unused).
Reimplemented from Mantid::CurveFitting::Functions::ComptonProfile.
Definition at line 341 of file GramCharlierComptonProfile.cpp.
References Mantid::CurveFitting::Functions::ComptonProfile::setMatrixWorkspace(), and workspace.
Member Data Documentation
m_hermite
std::vector<short> Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_hermite private
The active hermite coefficents.
Definition at line 63 of file GramCharlierComptonProfile.h.
Referenced by declareGramCharlierParameters(), fillConstraintMatrix(), intensityParameterIndices(), massProfile(), and setHermiteCoefficients().
m_qfine
std::vector<double> Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_qfine private
Interpolated Q values over a finer Y range.
Definition at line 67 of file GramCharlierComptonProfile.h.
Referenced by addFSETerm(), and cacheYSpaceValues().
m_userFixedFSE
bool Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_userFixedFSE private
Flag to hold whether the FSE parameter is fixed by the user.
Definition at line 77 of file GramCharlierComptonProfile.h.
Referenced by addFSETerm(), cacheYSpaceValues(), and fillConstraintMatrix().
m_voigt
std::vector<std::vector<double> > Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_voigt private
Holds the value of the Voigt function for each coarse y-space point as this is an expensive calculation.
Definition at line 71 of file GramCharlierComptonProfile.h.
Referenced by cacheYSpaceValues(), and convoluteVoigt().
m_voigtProfile
std::vector<double> Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_voigtProfile mutable private
Holds the result Voigt multiplied by the profile function for the extended Y space range.
Definition at line 74 of file GramCharlierComptonProfile.h.
Referenced by cacheYSpaceValues(), and convoluteVoigt().
m_yfine
std::vector<double> Mantid::CurveFitting::Functions::GramCharlierComptonProfile::m_yfine private
Y values over a finer range.
Definition at line 65 of file GramCharlierComptonProfile.h.
Referenced by addFSETerm(), addMassProfile(), cacheYSpaceValues(), and convoluteVoigt().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/GramCharlierComptonProfile.h
Framework/CurveFitting/src/Functions/GramCharlierComptonProfile.cpp