Mantid: Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace Struct Reference
Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace Struct Reference
Simple struct used to access features of the ADS No destructor so ensure you tearDown the ADS.
#include <IndirectFitDataCreationHelper.h>
Public Member Functions
template<typename T >
void addOrReplace (std::string const &workspaceName, T const &workspace)
bool doesExist (std::string const &workspaceName)
Mantid::API::MatrixWorkspace_sptr retrieveWorkspace (std::string const &workspaceName)
template<typename T >
SetUpADSWithWorkspace (std::string const &inputWSName, T const &workspace)
Detailed Description
Simple struct used to access features of the ADS No destructor so ensure you tearDown the ADS.
Definition at line 60 of file IndirectFitDataCreationHelper.h.
Constructor & Destructor Documentation
SetUpADSWithWorkspace()
template<typename T > Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace::SetUpADSWithWorkspace (std::string const & inputWSName, T const & workspace) inline
Definition at line 62 of file IndirectFitDataCreationHelper.h.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
Member Function Documentation
addOrReplace()
template<typename T > void Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace::addOrReplace (std::string const & workspaceName, T const & workspace) inline
Definition at line 66 of file IndirectFitDataCreationHelper.h.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
doesExist()
bool Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace::doesExist (std::string const & workspaceName) inline
Definition at line 70 of file IndirectFitDataCreationHelper.h.
References Mantid::Kernel::SingletonHolder< T >::Instance().
retrieveWorkspace()
Mantid::API::MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::SetUpADSWithWorkspace::retrieveWorkspace (std::string const & workspaceName) inline
Definition at line 74 of file IndirectFitDataCreationHelper.h.
References Mantid::Kernel::SingletonHolder< T >::Instance().
The documentation for this struct was generated from the following file:
Framework/TestHelpers/inc/MantidFrameworkTestHelpers/IndirectFitDataCreationHelper.h