Mantid: Mantid::DataObjects::LOOP< nd > Class Template Reference
Mantid::DataObjects::LOOP< nd > Class Template Reference
MDEventFactory : collection of methods to create MDLeanEvent* instances, by specifying the number of dimensions as a parameter.
Public Member Functions
LOOP ()
Static Public Member Functions
static void EXEC ()
Detailed Description
template<size_t nd>
class Mantid::DataObjects::LOOP< nd >
MDEventFactory : collection of methods to create MDLeanEvent* instances, by specifying the number of dimensions as a parameter.
Author
Janik Zikovsky
Date
2011-02-24 15:08:43.105134
Definition at line 381 of file MDEventFactory.cpp.
Constructor & Destructor Documentation
LOOP()
template<size_t nd> Mantid::DataObjects::LOOP< nd >::LOOP () inline
Definition at line 383 of file MDEventFactory.cpp.
References Mantid::DataObjects::LOOP< nd >::EXEC().
Member Function Documentation
EXEC()
template<size_t nd> static void Mantid::DataObjects::LOOP< nd >::EXEC () inline static
Definition at line 384 of file MDEventFactory.cpp.
References Mantid::DataObjects::MDEventFactory::boxCreatorFP, Mantid::DataObjects::LOOP< nd >::EXEC(), Mantid::DataObjects::MDEventFactory::MDBoxWithFat, Mantid::DataObjects::MDEventFactory::MDBoxWithLean, Mantid::DataObjects::MDEventFactory::MDGridBoxWithFat, Mantid::DataObjects::MDEventFactory::MDGridBoxWithLean, Mantid::DataObjects::MDEventFactory::NumBoxTypes, and Mantid::DataObjects::MDEventFactory::wsCreatorFP.
Referenced by Mantid::DataObjects::LOOP< nd >::EXEC(), Mantid::MDAlgorithms::LOOP< i >::EXEC(), Mantid::DataObjects::LOOP< nd >::LOOP(), and Mantid::MDAlgorithms::MDEventWSWrapper::MDEventWSWrapper().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/MDEventFactory.h
Framework/DataObjects/src/MDEventFactory.cpp