Mantid: MantidQt::MantidWidgets::AddWorkspaceMultiDialog Class Reference
MantidQt::MantidWidgets::AddWorkspaceMultiDialog Class Reference
#include <AddWorkspaceMultiDialog.h>
Signals
void addData (MantidWidgets::IAddWorkspaceDialog *dialog)
Public Member Functions
AddWorkspaceMultiDialog (QWidget *parent)
bool isEmpty () const
void notifyAlgorithmComplete (API::IConfiguredAlgorithm_sptr &algorithm) override
void notifyAlgorithmError (API::IConfiguredAlgorithm_sptr &algorithm, std::string const &message) override
void notifyAlgorithmStarted (API::IConfiguredAlgorithm_sptr &algorithm) override
void notifyBatchCancelled () override
void notifyBatchComplete (bool error) override
StringPairVec selectedNameIndexPairs () const
void setFBSuffices (const QStringList &suffices) override
void setLoadProperty (const std::string &propname, bool enable) override
Set an extra property on the load algorithm of the workspace multi dialog before execution.
void setup ()
void setWSSuffices (const QStringList &suffices) override
std::string workspaceName () const override
Public Member Functions inherited from MantidQt::MantidWidgets::IAddWorkspaceDialog
virtual void updateSelectedSpectra ()=0
Public Member Functions inherited from MantidQt::API::JobRunnerSubscriber
virtual ~JobRunnerSubscriber ()=default
Private Slots
void emitAddData ()
void handleFilesFound ()
void selectAllSpectra ()
void unifyRange ()
void updateSelectedSpectra () override
Private Member Functions
void updateAddButtonState (bool enabled) const
Private Attributes
std::unique_ptr< MantidQt::API::QtJobRunner > m_algRunner
Algorithm Runner used to run the load algorithm.
Mantid::API::AlgorithmRuntimeProps m_loadProperties
Ui::AddWorkspaceMultiDialog m_uiForm
Detailed Description
Definition at line 22 of file AddWorkspaceMultiDialog.h.
Constructor & Destructor Documentation
AddWorkspaceMultiDialog()
MantidQt::MantidWidgets::AddWorkspaceMultiDialog::AddWorkspaceMultiDialog (QWidget * parent) explicit
Definition at line 34 of file AddWorkspaceMultiDialog.cpp.
References emitAddData(), handleFilesFound(), m_algRunner, m_uiForm, selectAllSpectra(), unifyRange(), and updateSelectedSpectra().
Member Function Documentation
addData
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::addData (MantidWidgets::IAddWorkspaceDialog * dialog) signal
Referenced by emitAddData().
emitAddData
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::emitAddData () private slot
Definition at line 82 of file AddWorkspaceMultiDialog.cpp.
References addData().
Referenced by AddWorkspaceMultiDialog().
handleFilesFound
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::handleFilesFound () private slot
Definition at line 88 of file AddWorkspaceMultiDialog.cpp.
References m_algRunner, m_uiForm, and updateAddButtonState().
Referenced by AddWorkspaceMultiDialog().
isEmpty()
bool MantidQt::MantidWidgets::AddWorkspaceMultiDialog::isEmpty () const
Definition at line 56 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
notifyAlgorithmComplete()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::notifyAlgorithmComplete (API::IConfiguredAlgorithm_sptr & algorithm) inline override virtual
Implements MantidQt::API::JobRunnerSubscriber.
Definition at line 41 of file AddWorkspaceMultiDialog.h.
References UNUSED_ARG.
notifyAlgorithmError()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::notifyAlgorithmError (API::IConfiguredAlgorithm_sptr & algorithm, std::string const & message) override virtual
Implements MantidQt::API::JobRunnerSubscriber.
Definition at line 103 of file AddWorkspaceMultiDialog.cpp.
References UNUSED_ARG, and updateAddButtonState().
notifyAlgorithmStarted()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::notifyAlgorithmStarted (API::IConfiguredAlgorithm_sptr & algorithm) inline override virtual
Implements MantidQt::API::JobRunnerSubscriber.
Definition at line 40 of file AddWorkspaceMultiDialog.h.
References UNUSED_ARG.
notifyBatchCancelled()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::notifyBatchCancelled () inline override virtual
Implements MantidQt::API::JobRunnerSubscriber.
Definition at line 39 of file AddWorkspaceMultiDialog.h.
notifyBatchComplete()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::notifyBatchComplete (bool error) override virtual
Implements MantidQt::API::JobRunnerSubscriber.
Definition at line 98 of file AddWorkspaceMultiDialog.cpp.
References error, UNUSED_ARG, and updateAddButtonState().
selectAllSpectra
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::selectAllSpectra () private slot
Definition at line 80 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
Referenced by AddWorkspaceMultiDialog().
selectedNameIndexPairs()
StringPairVec MantidQt::MantidWidgets::AddWorkspaceMultiDialog::selectedNameIndexPairs () const
Definition at line 51 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
setFBSuffices()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::setFBSuffices (const QStringList & suffices) override virtual
Implements MantidQt::MantidWidgets::IAddWorkspaceDialog.
Definition at line 64 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
setLoadProperty()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::setLoadProperty (const std::string & propName, bool enable) override virtual
Set an extra property on the load algorithm of the workspace multi dialog before execution.
Parameters
propName :: The name of the Load algorithm property to be set
enable :: The value of the Load algorithm property to be set
Implements MantidQt::MantidWidgets::IAddWorkspaceDialog.
Definition at line 76 of file AddWorkspaceMultiDialog.cpp.
References m_loadProperties, and Mantid::API::AlgorithmProperties::update().
setup()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::setup ()
Definition at line 49 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
setWSSuffices()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::setWSSuffices (const QStringList & suffices) override virtual
Implements MantidQt::MantidWidgets::IAddWorkspaceDialog.
Definition at line 60 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
unifyRange
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::unifyRange () private slot
Definition at line 86 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
Referenced by AddWorkspaceMultiDialog().
updateAddButtonState()
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::updateAddButtonState (bool enabled) const private
Definition at line 110 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
Referenced by handleFilesFound(), notifyAlgorithmError(), and notifyBatchComplete().
updateSelectedSpectra
void MantidQt::MantidWidgets::AddWorkspaceMultiDialog::updateSelectedSpectra () override private slot
Definition at line 84 of file AddWorkspaceMultiDialog.cpp.
References m_uiForm.
Referenced by AddWorkspaceMultiDialog().
workspaceName()
std::string MantidQt::MantidWidgets::AddWorkspaceMultiDialog::workspaceName () const override virtual
Implements MantidQt::MantidWidgets::IAddWorkspaceDialog.
Definition at line 45 of file AddWorkspaceMultiDialog.cpp.
Member Data Documentation
m_algRunner
std::unique_ptr<MantidQt::API::QtJobRunner> MantidQt::MantidWidgets::AddWorkspaceMultiDialog::m_algRunner private
Algorithm Runner used to run the load algorithm.
Definition at line 58 of file AddWorkspaceMultiDialog.h.
Referenced by AddWorkspaceMultiDialog(), and handleFilesFound().
m_loadProperties
Mantid::API::AlgorithmRuntimeProps MantidQt::MantidWidgets::AddWorkspaceMultiDialog::m_loadProperties private
Definition at line 59 of file AddWorkspaceMultiDialog.h.
Referenced by setLoadProperty().
m_uiForm
Ui::AddWorkspaceMultiDialog MantidQt::MantidWidgets::AddWorkspaceMultiDialog::m_uiForm private
Definition at line 56 of file AddWorkspaceMultiDialog.h.
Referenced by AddWorkspaceMultiDialog(), handleFilesFound(), isEmpty(), selectAllSpectra(), selectedNameIndexPairs(), setFBSuffices(), setup(), setWSSuffices(), unifyRange(), updateAddButtonState(), and updateSelectedSpectra().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AddWorkspaceMultiDialog.h
qt/widgets/common/src/AddWorkspaceMultiDialog.cpp