Mantid: Mantid::CurveFitting::Functions::PawleyFunction Class Reference
Mantid::CurveFitting::Functions::PawleyFunction Class Reference
The Pawley approach to obtain lattice parameters from a powder diffractogram works by placing peak profiles at d-values (which result from the lattice parameters and the Miller indices of each peak) and fitting the total profile to the recorded diffractogram.
#include <PawleyFunction.h>
Public Member Functions
void addPeak (const Kernel::V3D &hkl, double fwhm, double height) override
Adds a peak with the supplied FWHM and height.
void clearPeaks () override
Removes all peaks from the function.
void function (const API::FunctionDomain &domain, API::FunctionValues &values) const override
Calculates the function values on the supplied domain.
void functionDeriv (const API::FunctionDomain &domain, API::Jacobian &jacobian) override
Derivates are calculated numerically.
PawleyParameterFunction_sptr getPawleyParameterFunction () const
Returns the internally stored PawleyParameterFunction.
size_t getPeakCount () const override
Returns the number of peaks that are stored in the function.
API::IPeakFunction_sptr getPeakFunction (size_t i) const override
Returns the profile function stored for the i-th peak.
Kernel::V3D getPeakHKL (size_t i) const override
Return the HKL of the i-th peak.
std::string name () const override
Returns the name of the function.
PawleyFunction ()
Constructor.
void setLatticeSystem (const std::string &latticeSystem) override
Sets the crystal system on the internal parameter function and updates the exposed parameters.
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Set matrix workspace.
void setPeaks (const std::vector< Kernel::V3D > &hkls, double fwhm, double height) override
Clears peaks and adds a peak for each hkl, all with the same FWHM and height.
void setProfileFunction (const std::string &profileFunction) override
Sets the profile function and replaces already existing functions in the internally stored CompositeFunction.
void setUnitCell (const std::string &unitCellString) override
Sets the unit cell from a string with either 6 or 3 space-separated numbers.
Public Member Functions inherited from Mantid::API::IPawleyFunction
IPawleyFunction ()
Default constructor.
Public Member Functions inherited from Mantid::API::FunctionParameterDecorator
double activeParameter (size_t i) const override
Value of i-th active parameter of the decorated function.
void addConstraint (std::unique_ptr< IConstraint > ic) override
Add a constraint to decorated function.
void addTies (const std::string &ties, bool isDefault=false) override
Add ties to the decorated function.
void applyTies () override
Apply the ties in decorated function.
void clearTies () override
Remove all ties of decorated function.
IFunction_sptr clone () const override
Virtual copy constructor.
FunctionParameterDecorator ()
IFunction::Attribute getAttribute (const std::string &attName) const override
Return a value of attribute attName of decorated function-.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names of decorated function.
IConstraint * getConstraint (size_t i) const override
Get constraint of i-th parameter of decorated function.
IFunction_sptr getDecoratedFunction () const
double getError (const std::string &name) const override
Get the fitting error for a parameter of decorated function by name.
double getError (size_t i) const override
Get the fitting error for a parameter of decorated function.
double getParameter (const std::string &name) const override
Get parameter of decorated function by name.
double getParameter (size_t i) const override
Get i-th parameter of decorated function.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index of decorated function from a parameter reference.
ParameterTie * getTie (size_t i) const override
Get the tie of i-th parameter of decorated function.
bool hasAttribute (const std::string &attName) const override
Check if attribute attName exists in decorated function.
bool hasParameter (const std::string &name) const override
Check if the decorated function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter of decorated function has been set explicitly.
size_t nAttributes () const override
Returns the number of attributes associated with the decorated function.
size_t nParams () const override
Total number of parameters of decorated function.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i of decorated function.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter of decorated function name.
std::string parameterName (size_t i) const override
Returns the name of parameter i of decorated function.
void removeConstraint (const std::string &parName) override
Remove a constraint of decorated function.
void removeTie (const std::string &parName) override
Removes the tie off a parameter.
bool removeTie (size_t i) override
Removes i-th parameter's of decorated function tie.
void setActiveParameter (size_t i, double value) override
Set new value of i-th active parameter of the decorated function.
void setAttribute (const std::string &attName, const IFunction::Attribute &attValue) override
Set a value to attribute attName of decorated function.
void setDecoratedFunction (const std::string &wrappedFunctionName)
void setError (const std::string &name, double err) override
Set the fitting error for a parameter of decorated function by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter of decorated function.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter of decorated function by name.
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter of decorated function.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter of decorated function by name.
void setParameterDescription (size_t i, const std::string &description) override
Set i-th parameter description of decorated function.
void setUpForFit () override
Set parameters of decorated function to satisfy constraints.
void setWorkspace (std::shared_ptr< const Workspace > ws) override
Set the workspace.
void tie (const std::string &parName, const std::string &expr, bool isDefault=false) override
Tie a parameter of decorated function to other parameters (or a constant).
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Protected Member Functions
void beforeDecoratedFunctionSet (const API::IFunction_sptr &fn) override
Checks that the decorated function has the correct structure.
size_t calculateFunctionValues (const API::IPeakFunction_sptr &peak, const API::FunctionDomain1D &domain, API::FunctionValues &localValues) const
double getTransformedCenter (double d) const
Transform d value to workspace unit.
void init () override
Does nothing.
void setPeakPositions (const std::string &centreName, double zeroShift, const Geometry::UnitCell &cell) const
Protected Member Functions inherited from Mantid::API::FunctionParameterDecorator
void addTie (std::unique_ptr< ParameterTie >) override
Forwads addTie-call to the decorated function.
void declareParameter (const std::string &name, double initValue, const std::string &description) override
Does nothing, function does not have parameters.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setDecoratedFunctionPrivate (const IFunction_sptr &fn)
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
void throwIfNoFunctionSet () const
Throws std::runtime_error when m_wrappedFunction is not set.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Attributes
API::CompositeFunction_sptr m_compositeFunction
Kernel::Unit_sptr m_dUnit
std::vector< Kernel::V3D > m_hkls
PawleyParameterFunction_sptr m_pawleyParameterFunction
API::CompositeFunction_sptr m_peakProfileComposite
int m_peakRadius
Kernel::Unit_sptr m_wsUnit
Protected Attributes inherited from Mantid::API::FunctionParameterDecorator
IFunction_sptr m_wrappedFunction
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Detailed Description
The Pawley approach to obtain lattice parameters from a powder diffractogram works by placing peak profiles at d-values (which result from the lattice parameters and the Miller indices of each peak) and fitting the total profile to the recorded diffractogram.
Depending on the chosen crystal system, this function exposes the appropriate lattice parameters as parameters, as well as profile parameters of the individual peak functions, except the peak locations, which are a direct result of their HKLs in combination with the unit cell.
Author
Michael Wedel, Paul Scherrer Institut - SINQ
Date
11/03/2015
Definition at line 91 of file PawleyFunction.h.
Constructor & Destructor Documentation
PawleyFunction()
Mantid::CurveFitting::Functions::PawleyFunction::PawleyFunction ()
Constructor.
Definition at line 301 of file PawleyFunction.cpp.
Member Function Documentation
addPeak()
void Mantid::CurveFitting::Functions::PawleyFunction::addPeak (const Kernel::V3D & hkl, double fwhm, double height) override virtual
Adds a peak with the supplied FWHM and height.
Implements Mantid::API::IPawleyFunction.
Definition at line 474 of file PawleyFunction.cpp.
References height, m_compositeFunction, m_hkls, m_pawleyParameterFunction, and m_peakProfileComposite.
Referenced by setPeaks().
beforeDecoratedFunctionSet()
void Mantid::CurveFitting::Functions::PawleyFunction::beforeDecoratedFunctionSet (const API::IFunction_sptr & fn) override protected virtual
Checks that the decorated function has the correct structure.
Reimplemented from Mantid::API::FunctionParameterDecorator.
Definition at line 529 of file PawleyFunction.cpp.
References m_compositeFunction, m_pawleyParameterFunction, and m_peakProfileComposite.
calculateFunctionValues()
size_t Mantid::CurveFitting::Functions::PawleyFunction::calculateFunctionValues (const API::IPeakFunction_sptr & peak, const API::FunctionDomain1D & domain, API::FunctionValues & localValues) const protected
Definition at line 387 of file PawleyFunction.cpp.
References Mantid::API::FunctionDomain1D::getPointerAt(), Mantid::API::FunctionValues::getPointerToCalculated(), m_peakRadius, n, Mantid::API::FunctionValues::reset(), and Mantid::API::FunctionDomain1D::size().
Referenced by function().
clearPeaks()
void Mantid::CurveFitting::Functions::PawleyFunction::clearPeaks () override virtual
Removes all peaks from the function.
Implements Mantid::API::IPawleyFunction.
Definition at line 456 of file PawleyFunction.cpp.
References m_compositeFunction, m_hkls, and m_peakProfileComposite.
Referenced by setPeaks().
function()
void Mantid::CurveFitting::Functions::PawleyFunction::function (const API::FunctionDomain & domain, API::FunctionValues & values) const override virtual
Calculates the function values on the supplied domain.
This function is the core of PawleyFunction. It calculates the d-value for each stored HKL from the unit cell that is the result of the parameters stored in the internal PawleyParameterFunction and adds the ZeroShift parameter. The value is set as center parameter on the internally stored PeakFunctions.
Parameters
domain :: Function domain.
values :: Function values.
Implements Mantid::API::IFunction.
Definition at line 425 of file PawleyFunction.cpp.
References Mantid::API::FunctionValues::addToCalculated(), calculateFunctionValues(), m_pawleyParameterFunction, m_peakProfileComposite, setPeakPositions(), and Mantid::API::FunctionValues::zeroCalculated().
functionDeriv()
void Mantid::CurveFitting::Functions::PawleyFunction::functionDeriv (const API::FunctionDomain & domain, API::Jacobian & jacobian) inline override virtual
Derivates are calculated numerically.
Reimplemented from Mantid::API::IFunction.
Definition at line 108 of file PawleyFunction.h.
getPawleyParameterFunction()
PawleyParameterFunction_sptr Mantid::CurveFitting::Functions::PawleyFunction::getPawleyParameterFunction () const
Returns the internally stored PawleyParameterFunction.
Definition at line 516 of file PawleyFunction.cpp.
References m_pawleyParameterFunction.
getPeakCount()
size_t Mantid::CurveFitting::Functions::PawleyFunction::getPeakCount () const override virtual
Returns the number of peaks that are stored in the function.
Implements Mantid::API::IPawleyFunction.
Definition at line 496 of file PawleyFunction.cpp.
References m_hkls.
getPeakFunction()
IPeakFunction_sptr Mantid::CurveFitting::Functions::PawleyFunction::getPeakFunction (size_t i) const override virtual
Returns the profile function stored for the i-th peak.
Implements Mantid::API::IPawleyFunction.
Definition at line 498 of file PawleyFunction.cpp.
References m_hkls, and m_peakProfileComposite.
getPeakHKL()
Kernel::V3D Mantid::CurveFitting::Functions::PawleyFunction::getPeakHKL (size_t i) const override virtual
Return the HKL of the i-th peak.
Implements Mantid::API::IPawleyFunction.
Definition at line 507 of file PawleyFunction.cpp.
References m_hkls.
getTransformedCenter()
double Mantid::CurveFitting::Functions::PawleyFunction::getTransformedCenter (double d) const protected
Transform d value to workspace unit.
Definition at line 371 of file PawleyFunction.cpp.
References Mantid::Geometry::d, Mantid::Kernel::DeltaEMode::Elastic, m_dUnit, m_wsUnit, and Mantid::Kernel::UnitConversion::run().
Referenced by setPeakPositions().
init()
void Mantid::CurveFitting::Functions::PawleyFunction::init () override protected virtual
Does nothing.
Reimplemented from Mantid::API::FunctionParameterDecorator.
Definition at line 518 of file PawleyFunction.cpp.
References m_compositeFunction, m_dUnit, and Mantid::API::FunctionParameterDecorator::setDecoratedFunction().
name()
std::string Mantid::CurveFitting::Functions::PawleyFunction::name () const inline override virtual
Returns the name of the function.
Implements Mantid::API::IFunction.
Definition at line 96 of file PawleyFunction.h.
setLatticeSystem()
void Mantid::CurveFitting::Functions::PawleyFunction::setLatticeSystem (const std::string & latticeSystem) override virtual
Sets the crystal system on the internal parameter function and updates the exposed parameters.
Implements Mantid::API::IPawleyFunction.
Definition at line 331 of file PawleyFunction.cpp.
References m_compositeFunction, and m_pawleyParameterFunction.
setMatrixWorkspace()
void Mantid::CurveFitting::Functions::PawleyFunction::setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override virtual
Set matrix workspace.
Initialize the function providing it the workspace.
Parameters
workspace :: The workspace to set
wi :: The workspace index
startX :: The lower bin index
endX :: The upper bin index
Reimplemented from Mantid::API::FunctionParameterDecorator.
Definition at line 308 of file PawleyFunction.cpp.
References m_dUnit, Mantid::API::FunctionParameterDecorator::m_wrappedFunction, m_wsUnit, Mantid::API::Axis::unit(), and workspace.
setPeakPositions()
void Mantid::CurveFitting::Functions::PawleyFunction::setPeakPositions (const std::string & centreName, double zeroShift, const Geometry::UnitCell & cell) const protected
Definition at line 379 of file PawleyFunction.cpp.
References Mantid::Geometry::UnitCell::d(), getTransformedCenter(), m_hkls, and m_peakProfileComposite.
Referenced by function().
setPeaks()
void Mantid::CurveFitting::Functions::PawleyFunction::setPeaks (const std::vector< Kernel::V3D > & hkls, double fwhm, double height) override virtual
Clears peaks and adds a peak for each hkl, all with the same FWHM and height.
Implements Mantid::API::IPawleyFunction.
Definition at line 465 of file PawleyFunction.cpp.
References addPeak(), clearPeaks(), and height.
setProfileFunction()
void Mantid::CurveFitting::Functions::PawleyFunction::setProfileFunction (const std::string & profileFunction) override virtual
Sets the profile function and replaces already existing functions in the internally stored CompositeFunction.
Implements Mantid::API::IPawleyFunction.
Definition at line 338 of file PawleyFunction.cpp.
References m_compositeFunction, m_pawleyParameterFunction, and m_peakProfileComposite.
setUnitCell()
void Mantid::CurveFitting::Functions::PawleyFunction::setUnitCell (const std::string & unitCellString) override virtual
Sets the unit cell from a string with either 6 or 3 space-separated numbers.
Implements Mantid::API::IPawleyFunction.
Definition at line 366 of file PawleyFunction.cpp.
References m_pawleyParameterFunction, and Mantid::Geometry::strToUnitCell().
Member Data Documentation
m_compositeFunction
API::CompositeFunction_sptr Mantid::CurveFitting::Functions::PawleyFunction::m_compositeFunction protected
Definition at line 133 of file PawleyFunction.h.
Referenced by addPeak(), beforeDecoratedFunctionSet(), clearPeaks(), init(), setLatticeSystem(), and setProfileFunction().
m_dUnit
Kernel::Unit_sptr Mantid::CurveFitting::Functions::PawleyFunction::m_dUnit protected
Definition at line 139 of file PawleyFunction.h.
Referenced by getTransformedCenter(), init(), and setMatrixWorkspace().
m_hkls
std::vector<Kernel::V3D> Mantid::CurveFitting::Functions::PawleyFunction::m_hkls protected
Definition at line 137 of file PawleyFunction.h.
Referenced by addPeak(), clearPeaks(), getPeakCount(), getPeakFunction(), getPeakHKL(), and setPeakPositions().
m_pawleyParameterFunction
PawleyParameterFunction_sptr Mantid::CurveFitting::Functions::PawleyFunction::m_pawleyParameterFunction protected
Definition at line 134 of file PawleyFunction.h.
Referenced by addPeak(), beforeDecoratedFunctionSet(), function(), getPawleyParameterFunction(), setLatticeSystem(), setProfileFunction(), and setUnitCell().
m_peakProfileComposite
API::CompositeFunction_sptr Mantid::CurveFitting::Functions::PawleyFunction::m_peakProfileComposite protected
Definition at line 135 of file PawleyFunction.h.
Referenced by addPeak(), beforeDecoratedFunctionSet(), clearPeaks(), function(), getPeakFunction(), setPeakPositions(), and setProfileFunction().
m_peakRadius
int Mantid::CurveFitting::Functions::PawleyFunction::m_peakRadius protected
Definition at line 142 of file PawleyFunction.h.
Referenced by calculateFunctionValues().
m_wsUnit
Kernel::Unit_sptr Mantid::CurveFitting::Functions::PawleyFunction::m_wsUnit protected
Definition at line 140 of file PawleyFunction.h.
Referenced by getTransformedCenter(), and setMatrixWorkspace().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/PawleyFunction.h
Framework/CurveFitting/src/Functions/PawleyFunction.cpp