Mantid: Mantid::DataObjects::MementoTableWorkspace Class Reference
Mantid::DataObjects::MementoTableWorkspace Class Reference
Variation on the TableWorkspace with a set of pre-defined columns used to store diffs on Workspaces.
#include <MementoTableWorkspace.h>
Public Member Functions
std::unique_ptr< MementoTableWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< MementoTableWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
MementoTableWorkspace (int nRows=0)
Constructor.
MementoTableWorkspace & operator= (const MementoTableWorkspace &)=delete
Public Member Functions inherited from Mantid::DataObjects::TableWorkspace
API::Column_sptr addColumn (const std::string &type, const std::string &name) override
Creates a new column.
template<class U >
U cell_cast (size_t nRow, const std::string &col_name) const
template<class U >
U cell_cast (size_t nRow, size_t nCol) const
Casts cells through converting their values to/from double without type checking; Can produce stuped results in case if the type is in any way not related to double.
std::unique_ptr< TableWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< TableWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
size_t columnCount () const override
Number of columns in the workspace.
void find (API::Boolean value, size_t &row, size_t col) override
This method finds the row and column index of an API::Bollean value in a table workspace.
void find (const Mantid::Kernel::V3D &value, size_t &row, size_t col) override
This method finds the row and column index of an Mantid::Kernel::V3D cell value in a table workspace.
void find (const std::string &value, size_t &row, size_t col) override
This method finds the row and column index of an string cell value in a table workspace.
void find (double value, size_t &row, size_t col) override
This method finds the row and column index of an double cell value in a table workspace.
void find (float value, size_t &row, size_t col) override
This method finds the row and column index of an float value in a table workspace.
void find (size_t value, size_t &row, size_t col) override
This method finds the row and column index of an integer cell value in a table workspace.
template<class T >
T * getColDataArray (const std::string &name)
Non-throwing access to the pointer to the column data array for the column with given name.
template<class T >
T * getColDataArray (const std::string &name) const
Non-throwing const access to the pointer to the column data array for the column with given name.
API::Column_const_sptr getColumn (const std::string &name) const override
Gets the shared pointer to a column.
API::Column_sptr getColumn (const std::string &name) override
Gets the shared pointer to a column.
API::Column_const_sptr getColumn (size_t index) const override
Gets the shared pointer to a column by index - return none-modifyable column.
API::Column_sptr getColumn (size_t index) override
Gets the shared pointer to a column.
std::vector< std::string > getColumnNames () const override
Returns a vector of all column names.
template<class T >
std::vector< T > & getColVector (const std::string &name)
get access to the column vector for column with given name .
template<class T >
const std::vector< T > & getColVector (const std::string &name) const
get access to column vector for column with given name
template<class T >
std::vector< T > & getColVector (size_t index)
get access to column vector for index i.
template<class T >
const std::vector< T > & getColVector (size_t index) const
get constant access to column vector for index i.
API::LogManager_const_sptr getLogs () const override
Get constant access to shared pointer containing workspace porperties.
size_t getMemorySize () const override
Get the footprint in memory in KB.
const std::string id () const override
Return the workspace typeID.
size_t insertRow (size_t index) override
Inserts a row before row pointed to by index and fills it with default vales.
API::LogManager_sptr logs () override
Get access to shared pointer containing workspace porperties.
TableWorkspace & operator= (const TableWorkspace &other)=delete
void removeColumn (const std::string &name) override
Removes a column.
void removeRow (size_t index) override
Delets a row if it exists.
size_t rowCount () const override
Number of rows in the workspace.
void setRowCount (size_t count) final
Resizes the workspace.
void sort (std::vector< std::pair< std::string, bool > > &criteria) override
Sort this table.
TableWorkspace (size_t nrows=0)
Constructor.
Public Member Functions inherited from Mantid::API::ITableWorkspace
virtual bool addColumns (const std::string &type, const std::string &name, size_t n)
Creates n new columns of the same type.
TableRowHelper appendRow ()
Appends a row.
Boolean & Bool (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is bool.
template<class T >
T & cell (size_t row, size_t col)
Get the reference to the element in row row and column col.
ITableWorkspace_uptr clone () const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneColumns (const std::vector< std::string > &colNames) const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
virtual bool customSort () const
Does this type of TableWorkspace need a custom sorting call (e.g.
double & Double (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is double.
TableRowHelper getFirstRow ()
Creates a TableRow object for the first row (row == 0).
template<class T >
T & getRef (const std::string &name, size_t index)
Get a reference to a data element.
TableRowHelper getRow (size_t row)
Creates a TableRow object for row row.
TableColumnHelper getVector (const std::string &name)
Access the column with name name trough a ColumnVector object.
TableConstColumnHelper getVector (const std::string &name) const
Access the column with name name trough a ColumnVector object.
int & Int (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is int.
ITableWorkspace ()
Constructor.
void modified ()
If the workspace is the AnalysisDataService sends AfterReplaceNotification.
ITableWorkspace & operator= (const ITableWorkspace &)=delete
std::string & String (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is std::string.
const std::string toString () const override
Serializes the object to a string.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
virtual const std::string getTitle () const
Get the workspace title.
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
virtual void setTitle (const std::string &)
Set the title of the workspace.
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Static Public Member Functions
static bool isMementoWorkspace (const Mantid::API::ITableWorkspace &candidate)
Determines whether a given table workspace has columns in the same order, and exactly matching those for the MementoTableWorkspace schema.
Protected Member Functions
MementoTableWorkspace (const MementoTableWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::DataObjects::TableWorkspace
TableWorkspace (const TableWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::API::ITableWorkspace
void insertInColumn (Column *c, size_t index)
Insert a new element into a column.
ITableWorkspace (const ITableWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void removeFromColumn (Column *c, size_t index)
Remove an element from a column.
void resizeColumn (Column *c, size_t size)
Resize a column.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Private Member Functions
MementoTableWorkspace * doClone () const override
Virtual clone method. Not implemented to force implementation in children.
MementoTableWorkspace * doCloneEmpty () const override
Virtual cloneEmpty method.
Static Private Member Functions
static bool expectedColumn (const Mantid::API::Column_const_sptr &expected, const Mantid::API::Column_const_sptr &candidate)
Determines whether the provided column has the same name and type as expected.
Detailed Description
Variation on the TableWorkspace with a set of pre-defined columns used to store diffs on Workspaces.
Author
Owen Arnold
Date
31/08/2011
Definition at line 22 of file MementoTableWorkspace.h.
Constructor & Destructor Documentation
MementoTableWorkspace() [1/2]
Mantid::DataObjects::MementoTableWorkspace::MementoTableWorkspace (int nRows = 0)
Constructor.
Definition at line 57 of file MementoTableWorkspace.cpp.
References Mantid::DataObjects::TableWorkspace::addColumn().
MementoTableWorkspace() [2/2]
Mantid::DataObjects::MementoTableWorkspace::MementoTableWorkspace (const MementoTableWorkspace &) protected default
Protected copy constructor. May be used by childs for cloning.
Member Function Documentation
clone()
std::unique_ptr< MementoTableWorkspace > Mantid::DataObjects::MementoTableWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 29 of file MementoTableWorkspace.h.
cloneEmpty()
std::unique_ptr< MementoTableWorkspace > Mantid::DataObjects::MementoTableWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 32 of file MementoTableWorkspace.h.
doClone()
MementoTableWorkspace * Mantid::DataObjects::MementoTableWorkspace::doClone () const inline override private virtual
Virtual clone method. Not implemented to force implementation in children.
Reimplemented from Mantid::API::ITableWorkspace.
Definition at line 41 of file MementoTableWorkspace.h.
doCloneEmpty()
MementoTableWorkspace * Mantid::DataObjects::MementoTableWorkspace::doCloneEmpty () const inline override private virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::ITableWorkspace.
Definition at line 43 of file MementoTableWorkspace.h.
expectedColumn()
bool Mantid::DataObjects::MementoTableWorkspace::expectedColumn (const Mantid::API::Column_const_sptr & expected, const Mantid::API::Column_const_sptr & candidate) static private
Determines whether the provided column has the same name and type as expected.
Parameters
expected : expected column name
candidate : ref to column to check
Returns
true if all expectations are met.
Definition at line 23 of file MementoTableWorkspace.cpp.
Referenced by isMementoWorkspace().
isMementoWorkspace()
bool Mantid::DataObjects::MementoTableWorkspace::isMementoWorkspace (const Mantid::API::ITableWorkspace & candidate) static
Determines whether a given table workspace has columns in the same order, and exactly matching those for the MementoTableWorkspace schema.
Parameters
candidate : ref to workspace to treat as a candidate for being a memento table workspace.
Returns
true if it is a MementoTableWorkspace.
Definition at line 42 of file MementoTableWorkspace.cpp.
References Mantid::API::ITableWorkspace::columnCount(), Mantid::DataObjects::TableWorkspace::columnCount(), expectedColumn(), Mantid::DataObjects::TableWorkspace::getColumn(), and Mantid::API::ITableWorkspace::getColumn().
operator=()
MementoTableWorkspace & Mantid::DataObjects::MementoTableWorkspace::operator= (const MementoTableWorkspace &) delete
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/MementoTableWorkspace.h
Framework/DataObjects/src/MementoTableWorkspace.cpp