Mantid: Mantid::API::IFunctionGeneral Class Reference
Mantid::API::IFunctionGeneral Class Reference abstract
IFunctionGeneral: a very general function definition.
#include <IFunctionGeneral.h>
Public Member Functions
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
virtual void functionGeneral (const FunctionDomainGeneral &domain, FunctionValues &values) const =0
Provide a concrete function in an implementation that operates on a FunctionDomainGeneral.
virtual size_t getDefaultDomainSize () const
Get the default size of a domain.
virtual size_t getNumberDomainColumns () const =0
Get number of columns that the domain must have.
virtual size_t getNumberValuesPerArgument () const =0
Get number of values per argument in the domain.
size_t getValuesSize (const FunctionDomain &domain) const override
Get number of values for a given domain.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
virtual void setParameter (size_t, const double &value, bool explicitlySet=true)=0
Set i-th parameter.
virtual void setParameterDescription (size_t, const std::string &description)=0
Set i-th parameter description.
virtual double getParameter (size_t i) const =0
Get i-th parameter.
virtual void setParameter (const std::string &name, const double &value, bool explicitlySet=true)=0
Set parameter by name.
virtual void setParameterDescription (const std::string &name, const std::string &description)=0
Set description of parameter by name.
virtual double getParameter (const std::string &name) const =0
Get parameter by name.
virtual bool hasParameter (const std::string &name) const =0
Check if function has a parameter with this name.
virtual size_t nParams () const =0
Total number of parameters.
virtual size_t parameterIndex (const std::string &name) const =0
Returns the index of parameter name.
virtual std::string parameterName (size_t i) const =0
Returns the name of parameter i.
virtual std::string parameterDescription (size_t i) const =0
Returns the description of parameter i.
virtual bool isExplicitlySet (size_t i) const =0
Checks if a parameter has been set explicitly.
virtual double getError (size_t i) const =0
Get the fitting error for a parameter.
virtual double getError (const std::string &name) const =0
Get the fitting error for a parameter by name.
virtual void setError (size_t i, double err)=0
Set the fitting error for a parameter.
virtual void setError (const std::string &name, double err)=0
Set the fitting error for a parameter by name.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
virtual size_t getParameterIndex (const ParameterReference &ref) const =0
Return parameter index from a parameter reference.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual void setAttribute (const std::string &name, const Attribute &)
Set a value to attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setParameterStatus (size_t i, ParameterStatus status)=0
Change status of parameter.
virtual ParameterStatus getParameterStatus (size_t i) const =0
Get status of parameter.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Static Protected Attributes
static Kernel::Logger g_log
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
virtual void declareParameter (const std::string &name, double initValue=0, const std::string &description="")=0
Declare a new parameter.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
IFunctionGeneral: a very general function definition.
It gets its arguments from a FunctionDomainGeneral and they can have any type. An argument can be a collection of a number of values of different types.
The domain and the values object can have different sizes. In particular the domain can be empty.
Definition at line 26 of file IFunctionGeneral.h.
Member Function Documentation
function()
void Mantid::API::IFunctionGeneral::function (const FunctionDomain & domain, FunctionValues & values) const override virtual
Evaluates the function for all arguments in the domain.
Parameters
domain :: Provides arguments for the function.
values :: A buffer to store the function values. It must be large enogh to store domain.size() values.
Implements Mantid::API::IFunction.
Definition at line 13 of file IFunctionGeneral.cpp.
References functionGeneral(), getValuesSize(), and Mantid::API::FunctionValues::size().
functionDeriv()
void Mantid::API::IFunctionGeneral::functionDeriv (const FunctionDomain & domain, Jacobian & jacobian) override virtual
Derivatives of function with respect to active parameters.
Base class implementation calculates the derivatives numerically.
Parameters
domain :: The domain of the function
jacobian :: A Jacobian matrix. It is expected to have dimensions of domain.size() by nParams().
Reimplemented from Mantid::API::IFunction.
Definition at line 27 of file IFunctionGeneral.cpp.
References Mantid::API::IFunction::calNumericalDeriv().
functionGeneral()
virtual void Mantid::API::IFunctionGeneral::functionGeneral (const FunctionDomainGeneral & domain, FunctionValues & values) const pure virtual
Provide a concrete function in an implementation that operates on a FunctionDomainGeneral.
Implemented in Mantid::CurveFitting::Functions::CrystalFieldPeaks.
Referenced by function().
getDefaultDomainSize()
size_t Mantid::API::IFunctionGeneral::getDefaultDomainSize () const virtual
Get the default size of a domain.
If a function is given an empty domain then it must output a values object of the size: getDefaultDomainSize() * getNumberValuesPerArgument() The default size must not be infinite (max of size_t).
Reimplemented in Mantid::CurveFitting::Functions::CrystalFieldPeaks.
Definition at line 38 of file IFunctionGeneral.cpp.
Referenced by Mantid::CurveFitting::GeneralDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::GeneralDomainCreator::GeneralDomainCreator(), and getValuesSize().
getNumberDomainColumns()
virtual size_t Mantid::API::IFunctionGeneral::getNumberDomainColumns () const pure virtual
Get number of columns that the domain must have.
If consider the collection of these columns as a table then a row corresponds to a single (multi-valued) argument.
Implemented in Mantid::CurveFitting::Functions::CrystalFieldPeaks.
Referenced by Mantid::CurveFitting::GeneralDomainCreator::GeneralDomainCreator(), and getValuesSize().
getNumberValuesPerArgument()
virtual size_t Mantid::API::IFunctionGeneral::getNumberValuesPerArgument () const pure virtual
Get number of values per argument in the domain.
Implemented in Mantid::CurveFitting::Functions::CrystalFieldPeaks.
Referenced by Mantid::CurveFitting::GeneralDomainCreator::GeneralDomainCreator(), and getValuesSize().
getValuesSize()
size_t Mantid::API::IFunctionGeneral::getValuesSize (const FunctionDomain & domain) const override virtual
Get number of values for a given domain.
Parameters
domain :: A domain.
Reimplemented from Mantid::API::IFunction.
Definition at line 31 of file IFunctionGeneral.cpp.
References getDefaultDomainSize(), getNumberDomainColumns(), getNumberValuesPerArgument(), and Mantid::API::FunctionDomain::size().
Referenced by function().
Member Data Documentation
g_log
Kernel::Logger Mantid::API::IFunctionGeneral::g_log static protected
Definition at line 53 of file IFunctionGeneral.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IFunctionGeneral.h
Framework/API/src/IFunctionGeneral.cpp