Mantid: Mantid::DataHandling::CoincidenceEvent Struct Reference
Mantid::DataHandling::CoincidenceEvent Struct Reference
A detected neutron.
#include <LoadNGEM.h>
Public Member Functions
uint64_t avgX () const
uint64_t avgY () const
bool check ()
uint64_t getPixel () const
Public Attributes
uint64_t clusterTimeX: 10
uint64_t clusterTimeY: 10
uint64_t contin: 8
uint64_t firstX: 7
uint64_t firstY: 7
uint64_t id: 8
uint64_t lastX: 7
uint64_t lastY: 7
uint64_t t0id: 24
uint64_t timeDiffX: 6
uint64_t timeDiffY: 6
uint64_t timeOfFlight: 28
Static Public Attributes
static constexpr int COINCIDENCE_IDENTIFIER = 0x47
Detailed Description
A detected neutron.
Definition at line 47 of file LoadNGEM.h.
Member Function Documentation
avgX()
uint64_t Mantid::DataHandling::CoincidenceEvent::avgX () const inline
Definition at line 63 of file LoadNGEM.h.
References firstX, and lastX.
Referenced by getPixel().
avgY()
uint64_t Mantid::DataHandling::CoincidenceEvent::avgY () const inline
Definition at line 64 of file LoadNGEM.h.
References firstY, and lastY.
Referenced by getPixel().
check()
bool Mantid::DataHandling::CoincidenceEvent::check () inline
Definition at line 66 of file LoadNGEM.h.
References COINCIDENCE_IDENTIFIER, contin, and Mantid::DataHandling::CONTIN_ID_VALUE.
Referenced by Mantid::DataHandling::LoadNGEM::loadSingleFile().
getPixel()
uint64_t Mantid::DataHandling::CoincidenceEvent::getPixel () const inline
Definition at line 67 of file LoadNGEM.h.
References avgX(), and avgY().
Member Data Documentation
clusterTimeX
uint64_t Mantid::DataHandling::CoincidenceEvent::clusterTimeX
Definition at line 52 of file LoadNGEM.h.
clusterTimeY
uint64_t Mantid::DataHandling::CoincidenceEvent::clusterTimeY
Definition at line 49 of file LoadNGEM.h.
COINCIDENCE_IDENTIFIER
constexpr int Mantid::DataHandling::CoincidenceEvent::COINCIDENCE_IDENTIFIER = 0x47 static constexpr
Definition at line 65 of file LoadNGEM.h.
Referenced by check().
contin
uint64_t Mantid::DataHandling::CoincidenceEvent::contin
Definition at line 55 of file LoadNGEM.h.
Referenced by check().
firstX
uint64_t Mantid::DataHandling::CoincidenceEvent::firstX
Definition at line 59 of file LoadNGEM.h.
Referenced by avgX().
firstY
uint64_t Mantid::DataHandling::CoincidenceEvent::firstY
Definition at line 57 of file LoadNGEM.h.
Referenced by avgY().
id
uint64_t Mantid::DataHandling::CoincidenceEvent::id
Definition at line 61 of file LoadNGEM.h.
lastX
uint64_t Mantid::DataHandling::CoincidenceEvent::lastX
Definition at line 58 of file LoadNGEM.h.
Referenced by avgX().
lastY
uint64_t Mantid::DataHandling::CoincidenceEvent::lastY
Definition at line 56 of file LoadNGEM.h.
Referenced by avgY().
t0id
uint64_t Mantid::DataHandling::CoincidenceEvent::t0id
Definition at line 48 of file LoadNGEM.h.
timeDiffX
uint64_t Mantid::DataHandling::CoincidenceEvent::timeDiffX
Definition at line 54 of file LoadNGEM.h.
timeDiffY
uint64_t Mantid::DataHandling::CoincidenceEvent::timeDiffY
Definition at line 51 of file LoadNGEM.h.
timeOfFlight
uint64_t Mantid::DataHandling::CoincidenceEvent::timeOfFlight
Definition at line 60 of file LoadNGEM.h.
The documentation for this struct was generated from the following file:
Framework/DataHandling/inc/MantidDataHandling/LoadNGEM.h