Mantid: ICat4::ns1__investigationParameter Class Reference
ICat4::ns1__investigationParameter Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__investigationParameter ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__parameter
ns1__parameter ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__investigation * investigation
Public Attributes inherited from ICat4::ns1__parameter
time_t * dateTimeValue
double * error
double * numericValue
double * rangeBottom
double * rangeTop
std::string * stringValue
ns1__parameterType * type
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2283 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__investigationParameter()
ICat4::ns1__investigationParameter::ns1__investigationParameter () inline
Definition at line 2294 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__investigationParameter::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10757 of file ICat4C.cpp.
References investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and ICat4::ns1__parameter::soap_default().
Referenced by ICat4::soap_in_ns1__investigationParameter(), ICat4::soap_new_req_ns1__investigationParameter(), and ICat4::soap_new_set_ns1__investigationParameter().
soap_get()
void * ICat4::ns1__investigationParameter::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10954 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_get_ns1__investigationParameter(), and ICat4::ns1__parameter::type.
soap_in()
void * ICat4::ns1__investigationParameter::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10815 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_in_ns1__investigationParameter(), and ICat4::ns1__parameter::type.
Referenced by ICat4::soap_in_ns1__investigationParameter().
soap_out()
int ICat4::ns1__investigationParameter::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10775 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_out_ns1__investigationParameter(), and ICat4::ns1__parameter::type.
Referenced by soap_put().
soap_put()
int ICat4::ns1__investigationParameter::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10947 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), SOAP_TYPE_ICat4_ns1__investigationParameter, and ICat4::ns1__parameter::type.
soap_serialize()
void ICat4::ns1__investigationParameter::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10765 of file ICat4C.cpp.
References investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::ns1__parameter::soap_serialize(), and ICat4::soap_serialize_PointerTons1__investigation().
Referenced by ICat4::soap_serialize_PointerTons1__investigationInstrument().
soap_type()
int ICat4::ns1__investigationParameter::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2287 of file ICat4Stub.h.
Member Data Documentation
investigation
ns1__investigation* ICat4::ns1__investigationParameter::investigation
Definition at line 2285 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp