Mantid: Mantid::API::ImmutableCompositeFunction Class Reference
Mantid::API::ImmutableCompositeFunction Class Reference
Immutable composite function is a composite function which members cannot be added or removed after creation.
#include <ImmutableCompositeFunction.h>
Public Member Functions
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
std::string name () const override
Returns the function's name.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t i, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::CompositeFunction
double activeParameter (size_t i) const override
Value of i-th active parameter.
void applyTies () override
Apply the ties.
std::size_t attributeFunctionIndex (std::size_t i) const
Get the index of the function to which parameter i belongs.
std::string attributeName (size_t i) const override
Returns the name of attribute i.
void checkFunction ()
Check the function.
void clear ()
Remove all member functions.
void clearTies () override
Remove all ties.
CompositeFunction ()
Default constructor.
std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const override
Split this function (if needed) into a list of independent functions.
std::string descriptionOfActive (size_t i) const override
Returns the name of active parameter i.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Function you want to fit to.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
std::size_t functionIndex (const std::string &functionName) const
Get the first function index with a matching function name.
std::size_t functionIndex (std::size_t i) const
Get the function index.
Attribute getAttribute (const std::string &name) const override
Return a value of attribute attName.
IConstraint * getConstraint (size_t i) const override
Get constraint of i-th parameter.
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getError (size_t i, size_t j) const
Get the fitting error for i-th function's j-th parameter.
IFunction_sptr getFunction (std::size_t i) const override
Returns the pointer to i-th function.
virtual Attribute getLocalAttribute (size_t i, const std::string &attName) const
Return a value of attribute attName.
virtual std::vector< std::string > getLocalAttributeNames () const
Returns a list of attribute names.
size_t getNumberDomains () const override
Get number of domains required by this function.
double getParameter (size_t i, size_t j) const
Get parameter from i-th function, j-th local parameter index.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
ParameterTie * getTie (size_t i) const override
Get the tie of i-th parameter.
bool hasAttribute (const std::string &name) const override
Check if a function has an attribute with this name.
bool hasFunction (const std::string &functionName) const
Returns true if the composite has at least one of this function.
virtual bool hasLocalAttribute (const std::string &) const
Check if attribute attName exists.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
std::string nameOfActive (size_t i) const override
Returns the name of active parameter i.
size_t nAttributes () const override
Returns the number of attributes associated with the function.
std::size_t nFunctions () const override
Number of functions.
size_t nGlobalAttributes () const noexcept
virtual size_t nLocalAttributes () const
Returns the number of attributes associated with the function.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterLocalIndex (size_t i, bool recursive=false) const
Returns the index of parameter i as it declared in its function.
std::string parameterLocalName (size_t i, bool recursive=false) const
Returns the name of parameter i as it declared in its function.
std::string parameterName (size_t i, size_t j) const
Returns the name of i-th function's j-th parameter.
void registerFunctionUsage (bool internal) override
Registers the usage of the function with the UsageService.
void removeConstraint (const std::string &parName) override
Remove a constraint.
void removeFunction (size_t i)
Remove a function.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
bool removeTie (size_t i) override
Removes i-th parameter's tie.
void replaceFunction (size_t functionIndex, const IFunction_sptr &f)
Replace a function.
void replaceFunctionPtr (const IFunction_sptr &f_old, const IFunction_sptr &f_new)
Replace a function.
void setActiveParameter (size_t i, double value) override
Set new value of i-th active parameter.
void setAttribute (const std::string &name, const API::IFunction::Attribute &value) override
Set a value of a named attribute.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
virtual void setLocalAttribute (size_t i, const std::string &attName, const Attribute &)
Set a value to attribute attName.
void setLocalAttributeValue (size_t i, const std::string &attName, const char *value)
template<typename T >
void setLocalAttributeValue (size_t i, const std::string &attName, const T &value)
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Set matrix workspace.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
void setStepSizeMethod (const StepSizeMethod stepSizeMethod) override
Sets the function to use when calculating the step size.
void setUpForFit () override
Prepare function for a fit.
void setWorkspace (std::shared_ptr< const Workspace > ws) override
Sets the workspace for each member function.
void updateActive (const double *in)
Update parameters after a fitting iteration.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
IFunction & operator= (const IFunction &)=delete
No copying.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
Protected Member Functions
void addDefaultConstraints (const std::string &constraints)
Add default constraints.
void addDefaultTies (const std::string &ties)
Add default ties.
void addFunction (IFunction *fun)
Overload addFunction to take a bare pointer.
virtual size_t addFunction (IFunction_sptr f)
Make it protected.
void setAlias (const std::string &parName, const std::string &alias)
Define an alias for a parameter.
std::string writeToString (const std::string &parentLocalAttributesStr="") const override
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::CompositeFunction
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute, with a validator.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
void init () override
Function initialization. Declare function parameters in this method.
size_t paramOffset (size_t i) const
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
Private Attributes
std::map< std::string, size_t > m_aliases
Keep paramater aliases.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Static Public Member Functions inherited from Mantid::API::CompositeFunction
static std::pair< std::string, size_t > parseName (const std::string &varName)
Extract function index and parameter name from a variable name.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
Immutable composite function is a composite function which members cannot be added or removed after creation.
Only a derived class can add functions in its contructor (or methods). The function factory treat an ImmutableCompositeFunction as a simple function.
Definition at line 26 of file ImmutableCompositeFunction.h.
Member Function Documentation
addDefaultConstraints()
void Mantid::API::ImmutableCompositeFunction::addDefaultConstraints (const std::string & constraints) protected
Add default constraints.
Add a list of constraints from a string.
Constraints added with this method are created with isDefault flag set to true and do not appear in the string returned by asString() method.
Parameters
constraints :: A comma-separated list of constraint expressions.
Definition at line 133 of file ImmutableCompositeFunction.cpp.
References Mantid::API::IFunction::addConstraints().
addDefaultTies()
void Mantid::API::ImmutableCompositeFunction::addDefaultTies (const std::string & ties) protected
Add default ties.
Ties added with this method are created with isDefault flag set to true and do not appear in the string returned by asString() method.
Parameters
ties :: Comma-separated list of name=value pairs where name is a parameter name and value is a math expression tying the parameter to other parameters or a constant.
Definition at line 124 of file ImmutableCompositeFunction.cpp.
References Mantid::API::IFunction::addTies().
Referenced by Mantid::CurveFitting::Functions::DiffRotDiscreteCircle::init(), Mantid::CurveFitting::Functions::DiffSphere::init(), and Mantid::CurveFitting::Functions::IsoRotDiff::init().
addFunction() [1/2]
void Mantid::API::ImmutableCompositeFunction::addFunction (IFunction * fun) protected
Overload addFunction to take a bare pointer.
A convenience method to add a new function.
Parameters
fun @ A pointer to a newly created function.
Definition at line 32 of file ImmutableCompositeFunction.cpp.
References addFunction().
Referenced by addFunction(), Mantid::CurveFitting::Functions::DiffRotDiscreteCircle::init(), Mantid::CurveFitting::Functions::DiffSphere::init(), and Mantid::CurveFitting::Functions::IsoRotDiff::init().
addFunction() [2/2]
size_t Mantid::API::CompositeFunction::addFunction (IFunction_sptr f) protected virtual
Make it protected.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 167 of file CompositeFunction.cpp.
getParameter() [1/2]
double Mantid::API::ImmutableCompositeFunction::getParameter (const std::string & name) const override virtual
Get parameter by name.
Parameters
name :: An alias or a name in CompositeFunction's style: f#.name
Returns
:: The parameter value.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 68 of file ImmutableCompositeFunction.cpp.
References Mantid::API::CompositeFunction::getParameter(), m_aliases, and name().
getParameter() [2/2]
double Mantid::API::ImmutableCompositeFunction::getParameter (size_t i) const inline override virtual
Get i-th parameter.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 45 of file ImmutableCompositeFunction.h.
name()
std::string Mantid::API::ImmutableCompositeFunction::name () const inline override virtual
Returns the function's name.
Reimplemented from Mantid::API::CompositeFunction.
Reimplemented in Mantid::CurveFitting::Functions::DiffRotDiscreteCircle, Mantid::CurveFitting::Functions::DiffSphere, and Mantid::CurveFitting::Functions::IsoRotDiff.
Definition at line 31 of file ImmutableCompositeFunction.h.
Referenced by getParameter(), parameterIndex(), setParameter(), and setParameterDescription().
parameterIndex()
size_t Mantid::API::ImmutableCompositeFunction::parameterIndex (const std::string & name) const override virtual
Returns the index of parameter name.
Parameters
name :: An alias or a name in CompositeFunction's style: f#.name
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 80 of file ImmutableCompositeFunction.cpp.
References m_aliases, name(), and Mantid::API::CompositeFunction::parameterIndex().
parameterName()
std::string Mantid::API::ImmutableCompositeFunction::parameterName (size_t i) const override virtual
Returns the name of parameter i.
Returns the alias or name of parameter i.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 91 of file ImmutableCompositeFunction.cpp.
References m_aliases, and Mantid::API::CompositeFunction::parameterName().
setAlias()
void Mantid::API::ImmutableCompositeFunction::setAlias (const std::string & parName, const std::string & alias) protected
Define an alias for a parameter.
Use this method only after all member functions have been added.
Parameters
parName :: Fully qualified parameter name.
alias :: An alias for the parameter.
Definition at line 108 of file ImmutableCompositeFunction.cpp.
References m_aliases, and Mantid::API::CompositeFunction::parameterIndex().
setParameter() [1/2]
void Mantid::API::ImmutableCompositeFunction::setParameter (const std::string & name, const double & value, bool explicitlySet = true) override virtual
Set parameter by name.
Parameters
name :: An alias or a name in CompositeFunction's style: f#.name
value :: A new parameter value.
explicitlySet :: The explicitly set flag.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 40 of file ImmutableCompositeFunction.cpp.
References m_aliases, name(), Mantid::API::CompositeFunction::setParameter(), and value.
setParameter() [2/2]
void Mantid::API::ImmutableCompositeFunction::setParameter (size_t i, const double & value, bool explicitlySet = true) inline override virtual
Set i-th parameter.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 33 of file ImmutableCompositeFunction.h.
References value.
setParameterDescription() [1/2]
void Mantid::API::ImmutableCompositeFunction::setParameterDescription (const std::string & name, const std::string & description) override virtual
Set description of parameter by name.
Parameters
name :: An alias or a name in CompositeFunction's style: f#.name
description :: A parameter description.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 54 of file ImmutableCompositeFunction.cpp.
References m_aliases, name(), and Mantid::API::CompositeFunction::setParameterDescription().
setParameterDescription() [2/2]
void Mantid::API::ImmutableCompositeFunction::setParameterDescription (size_t i, const std::string & description) inline override virtual
Set i-th parameter description.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 37 of file ImmutableCompositeFunction.h.
writeToString()
std::string Mantid::API::ImmutableCompositeFunction::writeToString (const std::string & parentLocalAttributesStr = "") const override protected virtual
Writes itself into a string.
Overridden method creates an initialization string which makes it look like a siple function.
Reimplemented from Mantid::API::CompositeFunction.
Definition at line 24 of file ImmutableCompositeFunction.cpp.
References Mantid::API::IFunction::writeToString().
Member Data Documentation
m_aliases
std::map<std::string, size_t> Mantid::API::ImmutableCompositeFunction::m_aliases private
Keep paramater aliases.
Definition at line 69 of file ImmutableCompositeFunction.h.
Referenced by getParameter(), parameterIndex(), parameterName(), setAlias(), setParameter(), and setParameterDescription().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/ImmutableCompositeFunction.h
Framework/API/src/ImmutableCompositeFunction.cpp