Mantid: MantidQt::API::BoolPropertyWidget Class Reference
MantidQt::API::BoolPropertyWidget Class Reference
Set of widgets representing a PropertyWithValue<bool>.
#include <BoolPropertyWidget.h>
Public Member Functions
BoolPropertyWidget (Mantid::Kernel::PropertyWithValue< bool > *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
QWidget * getMainWidget () override
QString getValue () const override
void setValueImpl (const QString &value) override
Set the value into the GUI.
~BoolPropertyWidget () override
Destructor.
Public Member Functions inherited from MantidQt::API::PropertyWidget
void addReplaceWSButton ()
Create and show the "Replace WS" button.
QGridLayout * getGridLayout ()
int getGridRow ()
Mantid::Kernel::Property * getProperty ()
const Mantid::Kernel::Property * getProperty () const
bool inGrid () const
PropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
void setEnabled (bool val)
Sets all widgets contained within to Enabled.
void setError (const QString &error)
Externally set an error string to display in the validator.
void setPrevious_isDynamicDefault (bool flag)
Set the isDynamicDefault flag associated with the previously-entered value.
void setPreviousValue (const QString &previousValue)
Set this widget's previously-entered value.
void setValue (const QString &value)
Set the value of the property given into the GUI state.
void setVisible (bool val) override
Sets all widgets contained within to Visible.
void transferHistoryState (const PropertyWidget *other, const PropertyWidget *upstream=nullptr)
Transfer the history state from another PropertyWidget, possibly additionally depending on the history state of an upstream property.
~PropertyWidget () override
Destructor.
Protected Attributes
QCheckBox * m_checkBox
Checkbox widget.
Protected Attributes inherited from MantidQt::API::PropertyWidget
QString m_doc
Documentation string (tooltip)
bool m_entered_isDynamicDefault
Stores the isDynamicDefault flag corresponding to the last value entered by the user.
QString m_enteredValue
Stores the last value entered by the user.
QString m_error
Error message received when trying to set the value.
QGridLayout * m_gridLayout
Grid layout of the dialog to which we are adding widgets.
QMap< Info, ClickableLabel * > m_icons
Allow icon access by Info enum.
bool m_isOutputWsProp
Whether or not the property is an output workspace.
QString m_lastValue
Last modified value.
QWidget * m_parent
Parent widget to add sub-widgets to.
bool m_previous_isDynamicDefault
Stores the isDynamicDefault flag corresponding to the previously entered value.
QString m_previousValue
Stores the previously entered value when this dialog was last open.
Mantid::Kernel::Property * m_prop
Property being looked at. This is NOT owned by the widget.
QPushButton * m_replaceWSButton
Button to "replace input workspace".
int m_row
If using the GridLayout, this is the row where the widget was inserted.
bool m_useHistory
History on/off flag.
QVector< QWidget * > m_widgets
All contained widgets.
Additional Inherited Members
Public Types inherited from MantidQt::API::PropertyWidget
enum Info { INVALID , REPLACE , RESTORE }
Public Slots inherited from MantidQt::API::PropertyWidget
void replaceWSButtonClicked ()
Deal with the "replace workspace" button being clicked.
void toggleUseHistory ()
Toggle whether or not to use the previously-entered value.
void updateIconVisibility (const QString &error="")
Update which icons should be shown.
void userEditedProperty ()
To be called when a user edits a property, as opposed to one being set programmatically.
void valueChangedSlot ()
Emits a signal that the value of the property was changed.
Signals inherited from MantidQt::API::PropertyWidget
void replaceWorkspaceName (const QString &propName)
Signal is emitted whenever someone clicks the replace WS button.
void userChangedProperty ()
void valueChanged (const QString &propName)
Signal is emitted whenever the value (as entered by the user) in the GUI changes.
Static Public Member Functions inherited from MantidQt::API::PropertyWidget
static void setFieldPlaceholderText (Mantid::Kernel::Property *prop, QLineEdit *field)
Set the placeholder text of the given field based on the default value of the given property.
Static Protected Member Functions inherited from MantidQt::API::PropertyWidget
static void setLabelFont (Mantid::Kernel::Property *prop, QWidget *label)
Set the font of the given label based on the optional/required status of the given property.
Detailed Description
Set of widgets representing a PropertyWithValue<bool>.
Date
2012-02-16
Definition at line 22 of file BoolPropertyWidget.h.
Constructor & Destructor Documentation
BoolPropertyWidget()
MantidQt::API::BoolPropertyWidget::BoolPropertyWidget (Mantid::Kernel::PropertyWithValue< bool > * prop, QWidget * parent = nullptr, QGridLayout * layout = nullptr, int row = -1)
Constructor.
Definition at line 16 of file BoolPropertyWidget.cpp.
References m_checkBox, MantidQt::API::PropertyWidget::m_doc, MantidQt::API::PropertyWidget::m_gridLayout, MantidQt::API::PropertyWidget::m_parent, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::PropertyWidget::m_row, MantidQt::API::PropertyWidget::m_widgets, Mantid::Kernel::Property::name(), MantidQt::API::PropertyWidget::setValue(), MantidQt::API::PropertyWidget::userEditedProperty(), and Mantid::Kernel::Property::value().
~BoolPropertyWidget()
MantidQt::API::BoolPropertyWidget::~BoolPropertyWidget () override default
Destructor.
Member Function Documentation
getMainWidget()
QWidget * MantidQt::API::BoolPropertyWidget::getMainWidget () inline override virtual
Returns
the main widget of this combo of widgets
Implements MantidQt::API::PropertyWidget.
Definition at line 33 of file BoolPropertyWidget.h.
getValue()
QString MantidQt::API::BoolPropertyWidget::getValue () const override virtual
Returns
the value of the property, as typed in the GUI, as a string
Implements MantidQt::API::PropertyWidget.
Definition at line 39 of file BoolPropertyWidget.cpp.
References m_checkBox.
setValueImpl()
void MantidQt::API::BoolPropertyWidget::setValueImpl (const QString & value) override virtual
Set the value into the GUI.
Parameters
value :: string representation of the value
Implements MantidQt::API::PropertyWidget.
Definition at line 50 of file BoolPropertyWidget.cpp.
References Mantid::Kernel::Property::getDefault(), m_checkBox, MantidQt::API::PropertyWidget::m_prop, and value.
Member Data Documentation
m_checkBox
QCheckBox* MantidQt::API::BoolPropertyWidget::m_checkBox protected
Checkbox widget.
Definition at line 37 of file BoolPropertyWidget.h.
Referenced by BoolPropertyWidget(), getValue(), and setValueImpl().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/BoolPropertyWidget.h
qt/widgets/common/src/BoolPropertyWidget.cpp