Mantid: MantidQt::MantidWidgets::IFunctionModel Class Reference
MantidQt::MantidWidgets::IFunctionModel Class Reference abstract
#include <IFunctionModel.h>
Public Member Functions
virtual void addConstraint (std::string const &functionIndex, std::string const &constraint)=0
virtual void addFunction (std::string const &prefix, std::string const &funStr)=0
virtual void changeTie (std::string const &parameterName, std::string const &tie)=0
void clear ()
virtual int currentDomainIndex () const =0
virtual IFunction_sptr getCurrentFunction () const =0
virtual std::vector< std::string > getDatasetDomainNames () const =0
virtual std::vector< std::string > getDatasetNames () const =0
virtual IFunction_sptr getFitFunction () const =0
std::string getFitFunctionString () const
virtual IFunction_sptr getFullFunction () const =0
std::string getFunctionString () const
virtual std::vector< std::string > getGlobalParameters () const =0
virtual std::string getLocalParameterConstraint (std::string const &parameterName, int i) const =0
virtual std::vector< std::string > getLocalParameters () const =0
virtual std::string getLocalParameterTie (std::string const &parameterName, int i) const =0
virtual double getLocalParameterValue (std::string const &parameterName, int i) const =0
virtual int getNumberDomains () const =0
int getNumberLocalFunctions () const
virtual double getParameter (std::string const &parameterName) const =0
virtual std::string getParameterDescription (std::string const &parameterName) const =0
virtual double getParameterError (std::string const &parameterName) const =0
virtual std::vector< std::string > getParameterNames () const =0
virtual IFunction_sptr getSingleFunction (int index) const =0
virtual bool hasFunction () const =0
virtual bool isGlobal (std::string const &parameterName) const =0
virtual bool isLocalParameterFixed (std::string const &parameterName, int i) const =0
virtual void removeConstraint (std::string const &parameterName)=0
virtual void removeFunction (std::string const &functionIndex)=0
virtual std::string setBackgroundA0 (double value)=0
virtual void setCurrentDomainIndex (int)=0
virtual void setDatasets (const QList< FunctionModelDataset > &datasets)=0
virtual void setFunction (IFunction_sptr fun)=0
void setFunctionString (std::string const &funStr)
virtual void setGlobal (std::string const &parameterName, bool on)=0
virtual void setGlobalParameters (const std::vector< std::string > &globals)=0
virtual void setGlobalParameterValue (std::string const &parameterName, double value)=0
virtual void setLocalParameterConstraint (std::string const &parameterName, int i, std::string const &constraint)=0
virtual void setLocalParameterFixed (std::string const &parameterName, int i, bool fixed)=0
virtual void setLocalParameterTie (std::string const &parameterName, int i, std::string const &tie)=0
virtual void setLocalParameterValue (std::string const &parameterName, int i, double value)=0
virtual void setLocalParameterValue (std::string const &parameterName, int i, double value, double error)=0
virtual void setNumberDomains (int)=0
virtual void setParameter (std::string const &parameterName, double value)=0
virtual void setParameterError (std::string const &parameterName, double value)=0
virtual void setQValues (const std::vector< double > &qValues)=0
virtual void setResolution (const std::vector< std::pair< std::string, size_t > > &fitResolutions)=0
virtual void updateMultiDatasetParameters (const IFunction &fun)=0
virtual void updateMultiDatasetParameters (const ITableWorkspace &paramTable)=0
virtual void updateParameters (const IFunction &fun)=0
virtual ~IFunctionModel ()=default
Protected Member Functions
void copyParametersAndErrorsToAllLocalFunctions (const IFunction &fun)
Static Protected Member Functions
static void copyParametersAndErrors (const IFunction &funFrom, IFunction &funTo)
Detailed Description
Definition at line 25 of file IFunctionModel.h.
Constructor & Destructor Documentation
~IFunctionModel()
virtual MantidQt::MantidWidgets::IFunctionModel::~IFunctionModel () virtual default
Member Function Documentation
addConstraint()
virtual void MantidQt::MantidWidgets::IFunctionModel::addConstraint (std::string const & functionIndex, std::string const & constraint) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
addFunction()
virtual void MantidQt::MantidWidgets::IFunctionModel::addFunction (std::string const & prefix, std::string const & funStr) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
changeTie()
virtual void MantidQt::MantidWidgets::IFunctionModel::changeTie (std::string const & parameterName, std::string const & tie) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
clear()
void MantidQt::MantidWidgets::IFunctionModel::clear ()
Definition at line 37 of file IFunctionModel.cpp.
References setFunction().
Referenced by MantidQt::MantidWidgets::FunctionModel::removeFunction(), and setFunctionString().
copyParametersAndErrors()
void MantidQt::MantidWidgets::IFunctionModel::copyParametersAndErrors (const IFunction & funFrom, IFunction & funTo) static protected
Definition at line 44 of file IFunctionModel.cpp.
References Mantid::API::IFunction::getError(), Mantid::API::IFunction::getParameter(), Mantid::API::IFunction::nParams(), Mantid::API::IFunction::setError(), and Mantid::API::IFunction::setParameter().
Referenced by copyParametersAndErrorsToAllLocalFunctions(), MantidQt::MantidWidgets::FunctionModel::updateMultiDatasetParameters(), and MantidQt::MantidWidgets::FunctionModel::updateParameters().
copyParametersAndErrorsToAllLocalFunctions()
void MantidQt::MantidWidgets::IFunctionModel::copyParametersAndErrorsToAllLocalFunctions (const IFunction & fun) protected
Definition at line 53 of file IFunctionModel.cpp.
References copyParametersAndErrors(), getNumberLocalFunctions(), and getSingleFunction().
currentDomainIndex()
virtual int MantidQt::MantidWidgets::IFunctionModel::currentDomainIndex () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getCurrentFunction()
virtual IFunction_sptr MantidQt::MantidWidgets::IFunctionModel::getCurrentFunction () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
Referenced by getFunctionString().
getDatasetDomainNames()
virtual std::vector< std::string > MantidQt::MantidWidgets::IFunctionModel::getDatasetDomainNames () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getDatasetNames()
virtual std::vector< std::string > MantidQt::MantidWidgets::IFunctionModel::getDatasetNames () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getFitFunction()
virtual IFunction_sptr MantidQt::MantidWidgets::IFunctionModel::getFitFunction () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
Referenced by getFitFunctionString().
getFitFunctionString()
std::string MantidQt::MantidWidgets::IFunctionModel::getFitFunctionString () const
Definition at line 30 of file IFunctionModel.cpp.
References getFitFunction().
getFullFunction()
virtual IFunction_sptr MantidQt::MantidWidgets::IFunctionModel::getFullFunction () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getFunctionString()
std::string MantidQt::MantidWidgets::IFunctionModel::getFunctionString () const
Definition at line 23 of file IFunctionModel.cpp.
References getCurrentFunction().
Referenced by MantidQt::MantidWidgets::FunctionModel::addFunction().
getGlobalParameters()
virtual std::vector< std::string > MantidQt::MantidWidgets::IFunctionModel::getGlobalParameters () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getLocalParameterConstraint()
virtual std::string MantidQt::MantidWidgets::IFunctionModel::getLocalParameterConstraint (std::string const & parameterName, int i) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getLocalParameters()
virtual std::vector< std::string > MantidQt::MantidWidgets::IFunctionModel::getLocalParameters () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getLocalParameterTie()
virtual std::string MantidQt::MantidWidgets::IFunctionModel::getLocalParameterTie (std::string const & parameterName, int i) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getLocalParameterValue()
virtual double MantidQt::MantidWidgets::IFunctionModel::getLocalParameterValue (std::string const & parameterName, int i) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getNumberDomains()
virtual int MantidQt::MantidWidgets::IFunctionModel::getNumberDomains () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
Referenced by getNumberLocalFunctions().
getNumberLocalFunctions()
int MantidQt::MantidWidgets::IFunctionModel::getNumberLocalFunctions () const
Definition at line 39 of file IFunctionModel.cpp.
References getNumberDomains(), and n.
Referenced by copyParametersAndErrorsToAllLocalFunctions().
getParameter()
virtual double MantidQt::MantidWidgets::IFunctionModel::getParameter (std::string const & parameterName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getParameterDescription()
virtual std::string MantidQt::MantidWidgets::IFunctionModel::getParameterDescription (std::string const & parameterName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getParameterError()
virtual double MantidQt::MantidWidgets::IFunctionModel::getParameterError (std::string const & parameterName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getParameterNames()
virtual std::vector< std::string > MantidQt::MantidWidgets::IFunctionModel::getParameterNames () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
getSingleFunction()
virtual IFunction_sptr MantidQt::MantidWidgets::IFunctionModel::getSingleFunction (int index) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
Referenced by copyParametersAndErrorsToAllLocalFunctions().
hasFunction()
virtual bool MantidQt::MantidWidgets::IFunctionModel::hasFunction () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
isGlobal()
virtual bool MantidQt::MantidWidgets::IFunctionModel::isGlobal (std::string const & parameterName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
isLocalParameterFixed()
virtual bool MantidQt::MantidWidgets::IFunctionModel::isLocalParameterFixed (std::string const & parameterName, int i) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
removeConstraint()
virtual void MantidQt::MantidWidgets::IFunctionModel::removeConstraint (std::string const & parameterName) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
removeFunction()
virtual void MantidQt::MantidWidgets::IFunctionModel::removeFunction (std::string const & functionIndex) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setBackgroundA0()
virtual std::string MantidQt::MantidWidgets::IFunctionModel::setBackgroundA0 (double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setCurrentDomainIndex()
virtual void MantidQt::MantidWidgets::IFunctionModel::setCurrentDomainIndex (int) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setDatasets()
virtual void MantidQt::MantidWidgets::IFunctionModel::setDatasets (const QList< FunctionModelDataset > & datasets) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setFunction()
virtual void MantidQt::MantidWidgets::IFunctionModel::setFunction (IFunction_sptr fun) pure virtual
Implemented in MantidQt::MantidWidgets::ConvolutionFunctionModel, and MantidQt::MantidWidgets::FunctionModel.
Referenced by clear(), and setFunctionString().
setFunctionString()
void MantidQt::MantidWidgets::IFunctionModel::setFunctionString (std::string const & funStr)
Definition at line 15 of file IFunctionModel.cpp.
References clear(), and setFunction().
Referenced by MantidQt::MantidWidgets::FunctionModel::addFunction().
setGlobal()
virtual void MantidQt::MantidWidgets::IFunctionModel::setGlobal (std::string const & parameterName, bool on) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setGlobalParameters()
virtual void MantidQt::MantidWidgets::IFunctionModel::setGlobalParameters (const std::vector< std::string > & globals) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setGlobalParameterValue()
virtual void MantidQt::MantidWidgets::IFunctionModel::setGlobalParameterValue (std::string const & parameterName, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setLocalParameterConstraint()
virtual void MantidQt::MantidWidgets::IFunctionModel::setLocalParameterConstraint (std::string const & parameterName, int i, std::string const & constraint) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setLocalParameterFixed()
virtual void MantidQt::MantidWidgets::IFunctionModel::setLocalParameterFixed (std::string const & parameterName, int i, bool fixed) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setLocalParameterTie()
virtual void MantidQt::MantidWidgets::IFunctionModel::setLocalParameterTie (std::string const & parameterName, int i, std::string const & tie) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setLocalParameterValue() [1/2]
virtual void MantidQt::MantidWidgets::IFunctionModel::setLocalParameterValue (std::string const & parameterName, int i, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setLocalParameterValue() [2/2]
virtual void MantidQt::MantidWidgets::IFunctionModel::setLocalParameterValue (std::string const & parameterName, int i, double value, double error) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setNumberDomains()
virtual void MantidQt::MantidWidgets::IFunctionModel::setNumberDomains (int) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setParameter()
virtual void MantidQt::MantidWidgets::IFunctionModel::setParameter (std::string const & parameterName, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setParameterError()
virtual void MantidQt::MantidWidgets::IFunctionModel::setParameterError (std::string const & parameterName, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setQValues()
virtual void MantidQt::MantidWidgets::IFunctionModel::setQValues (const std::vector< double > & qValues) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
setResolution()
virtual void MantidQt::MantidWidgets::IFunctionModel::setResolution (const std::vector< std::pair< std::string, size_t > > & fitResolutions) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
updateMultiDatasetParameters() [1/2]
virtual void MantidQt::MantidWidgets::IFunctionModel::updateMultiDatasetParameters (const IFunction & fun) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
updateMultiDatasetParameters() [2/2]
virtual void MantidQt::MantidWidgets::IFunctionModel::updateMultiDatasetParameters (const ITableWorkspace & paramTable) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
updateParameters()
virtual void MantidQt::MantidWidgets::IFunctionModel::updateParameters (const IFunction & fun) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionModel.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/IFunctionModel.h
qt/widgets/common/src/IFunctionModel.cpp