Mantid: SmoothNeighboursDialog Class Reference
SmoothNeighboursDialog Class Reference
#include <SmoothNeighboursDialog.h>
Public Member Functions
SmoothNeighboursDialog (QWidget *parent=nullptr)
Constructor.
Public Member Functions inherited from MantidQt::API::AlgorithmDialog
AlgorithmDialog (QWidget *parent=nullptr)
DefaultConstructor.
void initializeLayout ()
Create the layout of the widget. Can only be called once.
bool isInitialized () const
Is this dialog initialized.
bool isShowKeepOpen () const
Set if the keep open option is shown.
void setShowKeepOpen (const bool showOption)
Set if the keep open option is shown.
~AlgorithmDialog () override
Destructor.
void setAlgorithm (const Mantid::API::IAlgorithm_sptr &)
The following methods were made public for testing in GenericDialogDemo.cpp.
void setPresetValues (const QHash< QString, QString > &presetValues)
Set a list of suggested values.
void isForScript (bool forScript)
Set whether this is intended for use from a script or not.
void executeOnAccept (bool on)
If true then execute the algorithm on acceptance.
void setOptionalMessage (const QString &message)
Set an optional message to be displayed at the top of the dialog.
void addEnabledAndDisableLists (const QStringList &enabled, const QStringList &disabled)
Set comma-separated-list of enabled parameter names.
void addAlgorithmObserver (Mantid::API::AlgorithmObserver *observer)
Add an AlgorithmObserver to the algorithm.
void disableExitButton ()
Disable the exit button.
Protected Member Functions
void accept () override
Overridden to enable validators.
Protected Member Functions inherited from MantidQt::API::AlgorithmDialog
virtual void parseInput ()
Parse out the values entered into the dialog boxes.
virtual void saveInput ()
Save the input history of an accepted dialog.
const QString & getOptionalMessage () const
Get the message string.
void addOptionalMessage (QVBoxLayout *mainLay)
Add the optional message to the given layout.
bool isForScript () const
Get the usage boolean value.
bool isMessageAvailable () const
Is there a message string available.
bool isWidgetEnabled (const QString &propName) const
Check is a given property should have its control enabled or not.
Mantid::API::IAlgorithm_sptr getAlgorithm () const
Get the algorithm pointer.
Mantid::Kernel::Property * getAlgorithmProperty (const QString &propName) const
Get a pointer to the named property.
bool requiresUserInput (const QString &propName) const
Return a true if the given property requires user input.
QString getInputValue (const QString &propName) const
Get an input value from the form, dealing with blank inputs etc.
QLabel * getValidatorMarker (const QString &propname)
Get a property validator label.
void storePropertyValue (const QString &name, const QString &value)
Adds a property (name,value) pair to the stored map.
void removePropertyValue (const QString &name)
Removes a property (name, value) pair from the stored map.
bool setPropertyValues (const QStringList &skipList=QStringList())
Set properties on this algorithm by pulling values from the tied widgets.
bool setPropertyValue (const QString &pName, bool validateOthers)
Sets the value of a single property, using the value previously stored using storePropertyValue()
void showValidators ()
Show the validators for all the properties.
QWidget * tie (QWidget *widget, const QString &property, QLayout *parent_layout=nullptr, bool readHistory=true)
Tie a widget to a property.
void untie (const QString &property)
Untie a widget to a property.
QString openFileDialog (const QString &propName)
Open a file dialog to select a file.
QStringList openMultipleFileDialog (const QString &propName)
Open a file dialog to select many file.
void fillAndSetComboBox (const QString &propName, QComboBox *optionsBox) const
Fill a combo box for the named algorithm's allowed values.
void fillLineEdit (const QString &propName, QLineEdit *field)
Fill in the necessary input for a text field.
QLayout * createDefaultButtonLayout (const QString &helpText=QString("?"), const QString &loadText=QString("Run"), const QString &cancelText=QString("Close"), const QString &keepOpenText=QString("Keep Open"))
Create a row layout of buttons with specified text.
QPushButton * createHelpButton (const QString &helpText=QString("?")) const
Create a help button for this algorithm.
void flagInputWS (QWidget *inputWidget)
Flag an input workspace combobox with its property name.
QString getValue (QWidget *widget)
Retrieve a text value for a property from a widget.
void parse ()
Parse out the input from the dialog.
bool requestedToKeepEnabled (const QString &propName) const
Test if the given name's widget has been explicity asked to be enabled.
QString getPreviousValue (const QString &propName) const
Get the property value from either the previous input store or from Python argument.
void setPreviousValue (QWidget *widget, const QString &property)
Set a value based on any old input that we have.
void finishHandle (const Mantid::API::IAlgorithm *alg) override
Handle completion of algorithm started while staying open.
void errorHandle (const Mantid::API::IAlgorithm *alg, const std::string &what) override
Handle completion of algorithm started while staying open.
void closeEvent (QCloseEvent *evt) override
Only allow close when close is enabled.
Private Slots
void inputWorkspaceChanged (const QString &pName)
Called when input workspace get changed.
Private Member Functions
void initLayout () override
Initialize the layout.
Private Attributes
QVBoxLayout * m_dialogLayout
Main layout for the dialog.
MantidQt::API::AlgorithmPropertiesWidget * m_propertiesWidget
Widget for all the PropertyWidgets.
Static Private Attributes
static const QString INPUT_WORKSPACE = "InputWorkspace"
Input workspace name.
static const QString NON_UNIFORM_GROUP = "NonUniform Detectors"
Non rectangular detector group name.
static const QString RECTANGULAR_GROUP = "Rectangular Detectors"
Rectangular detector group name.
Additional Inherited Members
Signals inherited from MantidQt::API::AlgorithmDialog
void algCompletedSignal ()
Emitted when alg completes and dialog is staying open.
void closeEventCalled ()
Protected Slots inherited from MantidQt::API::AlgorithmDialog
void accept () override
A default slot that can be used for an OK button.
void reject () override
A default slot that can be used for a rejected button.
virtual void helpClicked ()
Help button clicked;.
virtual void keepOpenChanged (int state)
Keep open checkbox clicked;.
virtual void algorithmCompleted ()
Keep the running algorithm has completed.
virtual void executeAlgorithmAsync ()
Executes the algorithm in a separate thread.
virtual void removeAlgorithmFromManager ()
Removes the algorithm from the manager.
void enableExitButton ()
Enable to exit button.
Protected Attributes inherited from MantidQt::API::AlgorithmDialog
Mantid::API::IAlgorithm_sptr m_algorithm
The algorithm associated with this dialog.
QString m_algName
The name of the algorithm.
QStringList m_algProperties
The properties associated with this dialog.
QHash< QString, QString > m_propertyValueMap
A map of property <name, value> pairs that have been taken from the dialog.
QHash< QString, QWidget * > m_tied_properties
A list pointers to the widget for each property.
bool m_forScript
A boolean indicating whether this is for a script or not.
QStringList m_python_arguments
A list of property names that have been passed from Python.
QStringList m_enabled
A list of property names that should have their widgets enabled.
QStringList m_disabled
A list of property names that the user has requested to be disabled (overrides those in enabled)
QString m_strMessage
The message string to be displayed at the top of the widget; if it exists.
bool m_keepOpen
Whether to keep the dialog box open after alg execution.
bool m_msgAvailable
Is the message string empty or not.
bool m_isInitialized
Whether the layout has been initialized.
bool m_autoParseOnInit
Flag if the input should be parsed automatically on initialization.
QHash< QString, QLabel * > m_validators
A list of labels to use as validation markers.
QHash< QString, QString > m_errors
A map where key = property name; value = the error for this property (i.e.
QStringList m_noValidation
A list of property names whose widgets handle their own validation.
QVector< QWidget * > m_inputws_opts
Store a list of the names of input workspace boxes.
QVector< QLineEdit * > m_outputws_fields
Store a list of output workspace text edits.
QHash< QPushButton *, int > m_wsbtn_tracker
A map to keep track of replace workspace button presses.
QCheckBox * m_keepOpenCheckBox
QPushButton * m_okButton
QPushButton * m_exitButton
std::vector< Mantid::API::AlgorithmObserver * > m_observers
A list of AlgorithmObservers to add to the algorithm prior to execution.
QTimer m_btnTimer
Enable the close button when the timer fires.
bool m_statusTracked
A flag to track whether the status of the algorithm is being tracked.
Detailed Description
Definition at line 12 of file SmoothNeighboursDialog.h.
Constructor & Destructor Documentation
SmoothNeighboursDialog()
SmoothNeighboursDialog::SmoothNeighboursDialog (QWidget * parent = nullptr)
Constructor.
Definition at line 27 of file SmoothNeighboursDialog.cpp.
Member Function Documentation
accept()
void SmoothNeighboursDialog::accept () override protected
Overridden to enable validators.
Definition at line 110 of file SmoothNeighboursDialog.cpp.
References MantidQt::API::AlgorithmDialog::accept(), MantidQt::API::AlgorithmDialog::m_errors, m_propertiesWidget, and MantidQt::API::AlgorithmPropertiesWidget::m_propWidgets.
initLayout()
void SmoothNeighboursDialog::initLayout () override private virtual
Initialize the layout.
Implements MantidQt::API::AlgorithmDialog.
Definition at line 30 of file SmoothNeighboursDialog.cpp.
References MantidQt::API::AlgorithmPropertiesWidget::addEnabledAndDisableLists(), MantidQt::API::AlgorithmDialog::addOptionalMessage(), MantidQt::API::AlgorithmDialog::createDefaultButtonLayout(), MantidQt::API::AlgorithmDialog::getAlgorithm(), MantidQt::API::AlgorithmPropertiesWidget::hideOrDisableProperties(), INPUT_WORKSPACE, inputWorkspaceChanged(), m_dialogLayout, MantidQt::API::AlgorithmDialog::m_disabled, MantidQt::API::AlgorithmDialog::m_enabled, m_propertiesWidget, MantidQt::API::AlgorithmPropertiesWidget::m_propWidgets, MantidQt::API::AlgorithmDialog::m_python_arguments, MantidQt::API::AlgorithmPropertiesWidget::setAlgorithm(), MantidQt::API::AlgorithmDialog::tie(), and MantidQt::API::PropertyWidget::valueChangedSlot().
inputWorkspaceChanged
void SmoothNeighboursDialog::inputWorkspaceChanged (const QString & pName) private slot
Called when input workspace get changed.
Definition at line 69 of file SmoothNeighboursDialog.cpp.
References MantidQt::API::AlgorithmDialog::getAlgorithm(), INPUT_WORKSPACE, MantidQt::API::AlgorithmPropertiesWidget::m_groupWidgets, m_propertiesWidget, NON_UNIFORM_GROUP, RECTANGULAR_GROUP, and UNUSED_ARG.
Referenced by initLayout().
Member Data Documentation
INPUT_WORKSPACE
const QString SmoothNeighboursDialog::INPUT_WORKSPACE = "InputWorkspace" static private
Input workspace name.
Definition at line 33 of file SmoothNeighboursDialog.h.
Referenced by initLayout(), and inputWorkspaceChanged().
m_dialogLayout
QVBoxLayout* SmoothNeighboursDialog::m_dialogLayout private
Main layout for the dialog.
Definition at line 42 of file SmoothNeighboursDialog.h.
Referenced by initLayout().
m_propertiesWidget
MantidQt::API::AlgorithmPropertiesWidget* SmoothNeighboursDialog::m_propertiesWidget private
Widget for all the PropertyWidgets.
Definition at line 39 of file SmoothNeighboursDialog.h.
Referenced by accept(), initLayout(), and inputWorkspaceChanged().
NON_UNIFORM_GROUP
const QString SmoothNeighboursDialog::NON_UNIFORM_GROUP = "NonUniform Detectors" static private
Non rectangular detector group name.
Definition at line 29 of file SmoothNeighboursDialog.h.
Referenced by inputWorkspaceChanged().
RECTANGULAR_GROUP
const QString SmoothNeighboursDialog::RECTANGULAR_GROUP = "Rectangular Detectors" static private
Rectangular detector group name.
Definition at line 31 of file SmoothNeighboursDialog.h.
Referenced by inputWorkspaceChanged().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/SmoothNeighboursDialog.h
qt/widgets/plugins/algorithm_dialogs/src/SmoothNeighboursDialog.cpp