Mantid: Mantid::API Namespace Reference
Mantid::API Namespace Reference
Namespaces
namespace AlgorithmProperties
namespace MuParserUtils
namespace OperatorOverloads
Classes
class ADSValidator
ADSValidator : a validator that requires the value of a property to be present in the ADS.
class Algorithm
Base class from which all concrete algorithm classes should be derived.
struct AlgorithmDescriptor
Structure uniquely describing an algorithm with its name, category and version.
class AlgorithmFactoryImpl
The AlgorithmFactory class is in charge of the creation of concrete instances of Algorithms.
class AlgorithmFactoryObserver
class AlgorithmHasProperty
A validator to check whether a given algorithm has a named property.
class AlgorithmHistory
This class stores information about the Command History used by algorithms on a workspace.
class AlgorithmManagerImpl
The AlgorithmManagerImpl class is responsible for controlling algorithm instances.
class AlgorithmObserver
Observes Algorithm notifications: start,progress,finish,error.
class AlgorithmProperty
Define an algorithm property that can be used to supply an algorithm object to a subsequent algorithm.
class AlgorithmRuntimeProps
class AlgorithmStartingNotification
Class for when an algorithm is starting asynchronously.
class AnalysisDataServiceImpl
The Analysis data service stores instances of the Workspace objects and anything that derives from template class DynamicFactory<Mantid::Kernel::IAlgorithm>.
class AnalysisDataServiceObserver
class ArchiveSearchFactoryImpl
Creates instances of IArchiveSearch.
struct AttributeLambdaVisitor
Attribute visitor structure supporting lambda expressions Example usage: AttributeLambdaVisitor{[](const int val) {...}, [] (const double val) {}} would create a visitor capable of "visiting" an integer and double attribute* It functions by inheriting the () operator defined in each lambda.
class Axis
Class to represent the axis of a workspace.
class BinEdgeAxis
Stores numeric values that are assumed to be bin edge values.
class Boolean
As TableColumn stores its data in a std::vector bool type cannot be used in the same way as the other types.
class BoxController
This class is used by MDBox and MDGridBox in order to intelligently determine optimal behavior.
class BoxControllerSettingsAlgorithm
An abstract algorithm sub-class for algorithms that define properties for BoxController settings.
class CatalogFactoryImpl
The factory is a singleton that hands out shared pointers to the base Catalog class.
class CatalogManagerImpl
This class is a singleton and is responsible for creating, destroying, and managing catalogs.
class CatalogSession
This class is a responsible for storing session information for a specific catalog.
class Citation
class Column
Column is the base class for columns of TableWorkspace.
class ColumnFactoryImpl
The ColumnFactory class is in charge of the creation of concrete instances of columns.
class ColumnVector
ColumnVector gives access to the column elements without alowing its resizing.
class CommonBinsValidator
A validator which provides a TENTATIVE check that a workspace contains common bins in each spectrum.
class CompositeCatalog
CompositeCatalog is responsible for storing and performing options on multiple catalogues.
class CompositeDomain
Base class for a composite domain.
class CompositeDomainMD
A composite domain for MD functions.
class CompositeFunction
A composite function is a function containing other functions.
class ConstColumnVector
ConstColumnVector gives const access to the column elements without alowing its resizing.
class ConstraintFactoryImpl
The ConstraintFactory class is in charge of the creation of concrete instances of Constraints.
class CoordTransform
Unique SingleValueParameter Declaration for InputNDimensions.
struct Correction
The Correction struct to be applied as factor * TOF + offset multiplicativeFactor: TOF correction factor to multiply TOF by additiveOffset:: TOF additive offset in unit of TOF.
class CostFunctionFactoryImpl
The CostFunctionFactory class is in charge of the creation of concrete instances of minimizers.
class DeleterPolicy
class DeprecatedAlgorithm
Class for marking algorithms as deprecated.
class DeprecatedAlias
DeprecatedAlias : Class for making algorithm with deprecated names (aliases).
class DetectorSearcher
class DomainCreatorFactoryImpl
Constructs a DomainCreator object from a string.
struct ElementTraits
Default ElementTraits SFINAE Typetraits are used to provide the correct formatting based on the element type chosen.
struct ElementTraits< bool >
ElementTraits for boolean element types.
struct ElementTraits< double >
ElementTraits for double element types.
struct ElementTraits< float >
ElementTraits for float element types.
struct ElementTraits< size_t >
ElementTraits for boolean element types.
class EnabledWhenWorkspaceIsType
Show a property as enabled when the workspace pointed to by another is of a given type.
class EqualBinSizesValidator
EqualBinSizesValidator : Checks that all bins in a workspace are equally sized to within a given tolerance.
class ExperimentInfo
This class is shared by a few Workspace types and holds information related to a particular experiment/run:
class Expression
This class represents an expression made up of names, binary operators and brackets.
class FileBackedExperimentInfo
Implements a lazy-loading mechanism for the experimental information stored in a NeXus file.
class FileFinderImpl
This class finds data files given an instrument name (optionally) and a run number.
class FileLoaderRegistryImpl
Keeps a registry of algorithm's that are file loading algorithms to allow them to be searched to find the correct one to load a particular file.
class FileProperty
A specialized class for dealing with file properties.
class FrameworkManagerImpl
The main public API via which users interact with the Mantid framework.
class FuncMinimizerFactoryImpl
The FuncMinimizerFactory class is in charge of the creation of concrete instances of minimizers.
class FunctionDomain
Base class that represents the domain of a function.
class FunctionDomain1D
Represent a domain for functions of one real argument.
class FunctionDomain1DHistogram
Implements FunctionDomain1D as a set of bins for a histogram.
class FunctionDomain1DSpectrum
Specialization of FunctionDomain1DVector for spectra of MatrixWorkspaces.
class FunctionDomain1DVector
Implements FunctionDomain1D with its own storage in form of a std::vector.
class FunctionDomain1DView
1D domain - a wrapper around an array of doubles.
class FunctionDomainGeneral
Represent a domain of a very general type.
class FunctionDomainMD
Implements a domain for MD functions (IFunctionMD).
class FunctionFactoryImpl
The FunctionFactory class is in charge of the creation of concrete instances of fitting functions.
class FunctionGenerator
FunctionGenerator is a partial implementation of IFunction that defines a function consisting of two parts: the source and the target.
class FunctionHandler
Classes inherited from FunctionHandler will handle the function.
class FunctionParameterDecorator
FunctionParameterDecorator.
class FunctionProperty
A property class for functions.
class FunctionValues
A class to store values calculated by a function.
class GenericDataProcessorAlgorithm
Data processor algorithm to be used as a parent to workflow algorithms.
class GridDomain
class GridDomain1D
class Grouping
Structure to represent grouping information.
class GroupingLoader
GroupingLoader : Loads instrument grouping from IDF file.
class HistogramValidator
A validator which checks that a workspace contains histogram data (the default) or point data as required.
class HistoryItem
class HistoryView
This class wraps an algorithm history pointer to add additional functionality when creating a HistoryView.
class HistoWorkspace
HistoWorkspace is an abstract base class for MatrixWorkspace types that are NOT event workspaces.
class IAlgorithm
IAlgorithm is the interface implemented by the Algorithm base class.
class IAlgorithmRuntimeProps
class IArchiveSearch
This class is an archive searching interface.
class IBackgroundFunction
An interface to a background function.
class IBoxControllerIO
The header describes interface to IO Operations perfomed by the box controller May be replaced by a boost filestream in a future.
class ICatalog
This class creates an interface for information catalogs to support multiple facilities.
class ICatalogInfoService
This class is responsible for interfacing with the Information Data Service (IDS) to upload and download files to and from the archives.
class IConstraint
An interface to a constraint.
class ICostFunction
An interface for specifying the cost function to be used with Fit algorithm or minimizers, for example, the default being least squares fitting.
class IDomainCreator
An base class for domain creators for use in Fit.
class IEventList
IEventList : Interface to Mantid::DataObjects::EventList class, used to expose to PythonAPI.
class IEventWorkspace
This class provides an interface to an EventWorkspace.
class IFileLoader
Defines an interface to an algorithm that loads a file so that it can take part in the automatic selection procedure provided by the FileLoaderRegistry.
class IFuncMinimizer
An interface for function minimizers.
class IFunction
This is an interface to a fitting function - a semi-abstarct class.
class IFunction1D
This is a specialization of IFunction for functions of one real argument.
class IFunction1DSpectrum
IFunction1DSpectrum :
class IFunctionGeneral
IFunctionGeneral: a very general function definition.
class IFunctionMD
This is a specialization of IFunction for functions defined on an IMDWorkspace.
class IFunctionMW
This is a specialization of IFunction for functions defined on a MatrixWorkspace.
class IFunctionWithLocation
An interface to a function with location, which here means a function for which the user may ask what is its centre and height.
class IJournal
IJournal: Interface for classes that fetch information from journal files.
class ILatticeFunction
ILatticeFunction.
class ILiveListener
ILiveListener is the interface implemented by classes which connect directly to instrument data acquisition systems (DAS) for retrieval of 'live' data into Mantid.
class IMaskWorkspace
This class provides an interface to a MaskWorkspace.
class IMDEventWorkspace
Abstract base class for multi-dimension event workspaces (MDEventWorkspace).
class IMDHistoWorkspace
Abstract interface to MDHistoWorkspace, for use in exposing to Python.
class IMDIterator
This is an interface to an iterator of an IMDWorkspace.
class IMDNode
class IMDWorkspace
Basic MD Workspace Abstract Class.
class ImmutableCompositeFunction
Immutable composite function is a composite function which members cannot be added or removed after creation.
class ImplicitFunctionBuilder
This class is the abstract type for building IImplicitFunctions.
class ImplicitFunctionFactoryImpl
class ImplicitFunctionParameter
Abstract parameter type for use with IImplicitFunctions.
class ImplicitFunctionParameterParser
class ImplicitFunctionParameterParserFactoryImpl
class ImplicitFunctionParser
XML Parser for function types.
class ImplicitFunctionParserFactoryImpl
class IncreasingAxisValidator
A validator which checks that the X axis of a workspace is increasing from left to right.
class IndexProperty
IndexProperty : Implementation of a property type which returns a SpectrumIndexSet provided an input vector of integers or a string.
class IndexTypeProperty
IndexTypeProperty : Implementation of a property which stores the type of input indices users require for accessing workspace data.
class InstrumentDataServiceImpl
InstrumentDataService Class.
class InstrumentFileFinder
class InstrumentValidator
A validator which checks that a workspace has a valid instrument.
struct IntegrationResult
PeakFunctionIntegrator :
class IPawleyFunction
IPawleyFunction.
class IPeakFunction
An interface to a peak function, which extend the interface of IFunctionWithLocation by adding methods to set and get peak width.
class IPeaksWorkspace
Interface to the class Mantid::DataObjects::PeaksWorkspace.
class IPowderDiffPeakFunction
An interface to a peak function, which extend the interface of IFunctionWithLocation by adding methods to set and get peak width.
class IPreview
IPreview : This is the abstract base class of the raw data previews.
class ISISInstrumentDataCache
class ISISRunLogs
Defines a class to aid in creating ISIS specific run logs for periods, status etc.
class ISpectrum
A "spectrum" is an object that holds the data for a particular spectrum, in particular:
class ISplittersWorkspace
ISplittersWorkspace : Workspace to contain splitters for event filtering.
class ITableWorkspace
ITableWorkspace is an implementation of Workspace in which the data are organised in columns of same size.
class ITransformScale
class IWorkspaceProperty
An interface that is implemented by WorkspaceProperty.
class Jacobian
Represents the Jacobian in IFitFunction::functionDeriv.
class JointDomain
An implementation of CompositeDomain.
class LatticeDomain
LatticeDomain.
class LinearScale
class LiveListener
Base implementation for common behaviour of all live listener classes.
class LiveListenerFactoryImpl
The factory for creating instances of ILiveListener implementations.
struct LockMode
Enumeration for locking behaviour.
class LogarithmScale
class LogManager
This class contains the information about the log entries.
class MatrixWorkspace
Base MatrixWorkspace Abstract Class.
class MatrixWorkspaceMDIterator
IMDIterator-compatible implementation of an iterator through a MatrixWorkspace.
class MatrixWorkspaceValidator
An interface for those validators that require the MatrixWorkspace interface.
class MDFrameValidator
class MDGeometry
Describes the geometry (i.e.
class MDGeometryNotificationHelper
class MultiDomainFunction
A composite function defined on a CompositeDomain.
class MultiPeriodGroupAlgorithm
MutliPeriodGroupAlgorithm : Abstract algorithm.
class MultiPeriodGroupWorker
MultiPeriodGroupWorker : Multiperiod group logic relating to determining a valid multiperiod group, and processing a multiperiod group, as well as combining and returning the output.
class MultipleExperimentInfos
Small class that allows a MDEventWorkspace or a MDHistoWorkspace to hold several ExperimentInfo classes.
class MultipleFileProperty
A property to allow a user to specify multiple files to load.
class MWDimension
class MWXDimension
An implementation of IMDDimension for MatrixWorkspace that points to the X vector of the first spectrum.
class NexusFileLoader
class NotebookBuilder
class NotebookWriter
class NullCoordTransform
NullCoordTransform : A transform that sets the outVector to have the same values as the inputVector.
class NumericAxis
Class to represent a numeric axis of a workspace.
class NumericAxisValidator
A validator which checks whether the input workspace has the Numeric data in the axis.
class OrientedLatticeValidator
class PanelsSurfaceCalculator
class ParameterReference
A reference to a parameter in a function.
class ParameterTie
Ties fitting parameters.
class ParamFunction
Implements the part of IFunction interface dealing with parameters.
class PartialJacobian
A Jacobian for individual functions.
class PeakFunctionIntegrator
class PolSANSWorkspaceValidator
PolSANSWorkspaceValidator : Validator for SANS polarized transmission runs.
class PreviewManagerImpl
PreviewManager : Manages the raw data previews.
class Progress
Helper class for reporting progress from algorithms.
class Projection
struct PropertyMode
Enumeration for a mandatory/optional property.
class RawCountValidator
A validator which checks that a workspace contains raw counts in its bins.
class RefAxis
A class to represent the axis of a 2D (or more) workspace where the value at a given point on the axis varies along the other dimension.
class ReferenceEqual
Used to find ParameterTie for a parameter i.
class RegionSelectorObserver
class Result
class Run
This class stores information regarding an experimental run as a series of log entries.
class Sample
This class stores information about the sample used in particular run.
class SampleShapeValidator
Verify that a workspace has valid sample shape.
class SampleValidator
A validator which checks that sample has the required properties.
class ScopedWorkspace
ScopedWorkspace : scoped workspace ADS entry.
class ScriptBuilder
This class build a sttring which cana be executed as a python script.
struct ScriptInfo
Information about the files inside the repository.
class ScriptRepoException
The ScriptRepository class is intended to be used mainly by the users, who will be willing to share and download scripts for their analysis.
class ScriptRepository
class ScriptRepositoryFactoryImpl
The ScriptRepositoryFactoryImpl class is in charge of the creation of concrete instance of ScriptRepository interface.
class SingleCountValidator
SingleCountValidator : This validator checks that there is only a single entry per spectrum, the counts, so no Time-of-Flight data.
class SingleValueParameter
SingleValueParameter is a templated base class implementing CRTP.
class SingleValueParameterParser
XML Parser for single value parameter types.
class SpectraAxis
Class to represent the spectra axis of a workspace.
class SpectraAxisValidator
A validator which checks whether the input workspace has the Spectra number in the axis.
class SpectrumDetectorMapping
A minimal class to hold the mapping between the spectrum number and its related detector ID numbers for a dataset.
class SpectrumInfo
API::SpectrumInfo is an intermediate step towards a SpectrumInfo that is part of Instrument-2.0.
class SpectrumInfoItem
SpectrumInfoItem.
class SpectrumInfoIterator
SpectrumInfoIterator.
class TableColumnHelper
Helper class used to create ColumnVector.
class TableConstColumnHelper
Helper class used to create ConstColumnVector.
class TableRow
TableRow represents a row in a TableWorkspace.
class TableRowHelper
Helper class used to create TableRow.
class TempJacobian
class TextAxis
Class to represent a text axis of a workspace.
class TimeAtSampleStrategy
TimeAtSampleStrategy : Strategy (technique dependent) for determining Time At Sample.
class TimeAtSampleStrategyDirect
TimeAtSampleStrategyDirect : Determine the Time at Sample corrections for a Direct Geometry instrument.
class TimeAtSampleStrategyElastic
TimeAtSampleStrategyElastic : Time at sample stragegy for elastic scattering.
class TimeAtSampleStrategyIndirect
TimeAtSampleStrategyIndirect : Determine Time At Sample for an indirect instrument setup.
class Topology
Abstract type represents topology for visualisation.
class TransformScaleFactoryImpl
Constructs a scaling transform object from a string.
class VectorParameter
VectorParameter is abstract type implementing curiously recurring template pattern to implement common code associated with vector storage.
class VectorParameterParser
XML parser for vector value (n elements) parameter types.
class Workspace
Base Workspace Abstract Class.
class WorkspaceFactoryImpl
The WorkspaceFactory class is in charge of the creation of all types of workspaces.
class WorkspaceGroup
Class to hold a set of workspaces.
class WorkspaceHasDxValidator
WorkspaceHasDxValidator : A validator which checks that all histograms in a workspace have Dx values.
struct WorkspaceHelpers
A collection of static functions for use with workspaces.
class WorkspaceHistory
This class stores information about the Workspace History used by algorithms on a workspace and the environment history.
class WorkspaceNearestNeighbourInfo
WorkspaceNearestNeighbourInfo provides easy access to nearest-neighbour information for a workspace.
class WorkspaceNearestNeighbours
This class is not intended for direct use.
class WorkspaceProperty
A property class for workspaces.
class WorkspaceUnitValidator
A validator which checks that the unit of the workspace referred to by a WorkspaceProperty is the expected one.
Typedefs
using Algorithm_sptr = std::shared_ptr< Algorithm >
Typedef for a shared pointer to an Algorithm.
using AlgorithmFactory = Mantid::Kernel::SingletonHolder< AlgorithmFactoryImpl >
using AlgorithmFactoryUpdateNotification = Mantid::Kernel::DynamicFactory< Algorithm >::UpdateNotification
Convenient typedef for an UpdateNotification.
using AlgorithmFactoryUpdateNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DynamicFactory< Algorithm >::UpdateNotification > &
using AlgorithmHistories = std::vector< AlgorithmHistory_sptr >
using AlgorithmHistory_const_sptr = std::shared_ptr< const AlgorithmHistory >
using AlgorithmHistory_sptr = std::shared_ptr< AlgorithmHistory >
using AlgorithmID = void *
As we have multiple interfaces to the same logical algorithm we need a way of uniquely identifying managed algorithms.
using AlgorithmManager = Mantid::Kernel::SingletonHolder< AlgorithmManagerImpl >
using AnalysisDataService = Mantid::Kernel::SingletonHolder< AnalysisDataServiceImpl >
using ArchiveSearchFactory = Mantid::Kernel::SingletonHolder< ArchiveSearchFactoryImpl >
using BoxController_const_sptr = std::shared_ptr< const BoxController >
Shared ptr to a const BoxController.
using BoxController_sptr = std::shared_ptr< BoxController >
Shared ptr to BoxController.
using CatalogFactory = Mantid::Kernel::SingletonHolder< CatalogFactoryImpl >
The specialisation of the SingletonHolder class that holds the CatalogFactory.
using CatalogManager = Kernel::SingletonHolder< CatalogManagerImpl >
using CatalogSession_const_sptr = std::shared_ptr< const CatalogSession >
using CatalogSession_sptr = std::shared_ptr< CatalogSession >
using ClearADSNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::ClearNotification
using ClearADSNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::ClearNotification > &
using Column_const_sptr = std::shared_ptr< const Column >
using Column_sptr = std::shared_ptr< Column >
using ColumnFactory = Mantid::Kernel::SingletonHolder< ColumnFactoryImpl >
using CompositeFunction_const_sptr = std::shared_ptr< const CompositeFunction >
shared pointer to the composite function base class (const version)
using CompositeFunction_sptr = std::shared_ptr< CompositeFunction >
shared pointer to the composite function base class
using ConstraintFactory = Mantid::Kernel::SingletonHolder< ConstraintFactoryImpl >
using CoordTransform_const_sptr = std::shared_ptr< const CoordTransform >
using CoordTransform_sptr = std::shared_ptr< CoordTransform >
using CostFunctionFactory = Mantid::Kernel::SingletonHolder< CostFunctionFactoryImpl >
using DataProcessorAlgorithm = GenericDataProcessorAlgorithm< Algorithm >
using DomainCreatorFactory = Mantid::Kernel::SingletonHolder< DomainCreatorFactoryImpl >
using ExperimentInfo_const_sptr = std::shared_ptr< const ExperimentInfo >
Shared pointer to const ExperimentInfo.
using ExperimentInfo_sptr = std::shared_ptr< ExperimentInfo >
Shared pointer to ExperimentInfo.
using FileFinder = Mantid::Kernel::SingletonHolder< FileFinderImpl >
using FileLoaderRegistry = Mantid::Kernel::SingletonHolder< FileLoaderRegistryImpl >
Type for the actual singleton instance.
using FrameworkManager = Mantid::Kernel::SingletonHolder< FrameworkManagerImpl >
using FuncMinimizerFactory = Mantid::Kernel::SingletonHolder< FuncMinimizerFactoryImpl >
using FunctionDomain1D_const_sptr = std::shared_ptr< const FunctionDomain1D >
typedef for a shared pointer to a const FunctionDomain1D
using FunctionDomain1D_sptr = std::shared_ptr< FunctionDomain1D >
typedef for a shared pointer to a FunctionDomain1D
using FunctionDomain_sptr = std::shared_ptr< FunctionDomain >
typedef for a shared pointer
using FunctionFactory = Mantid::Kernel::SingletonHolder< FunctionFactoryImpl >
using FunctionFactoryUpdateNotification = FunctionFactoryImpl::UpdateNotification
Convenient typedef for an UpdateNotification.
using FunctionFactoryUpdateNotification_ptr = const Poco::AutoPtr< FunctionFactoryUpdateNotification > &
Convenient typedef for an UpdateNotification AutoPtr.
using FunctionParameterDecorator_sptr = std::shared_ptr< FunctionParameterDecorator >
using FunctionValues_sptr = std::shared_ptr< FunctionValues >
typedef for a shared pointer
using GridDomain1D_sptr = std::shared_ptr< GridDomain1D >
typedef for a shared pointer
using GridDomain_sptr = std::shared_ptr< GridDomain >
typedef for a shared pointer
using GroupUpdatedNotification = AnalysisDataServiceImpl::GroupUpdatedNotification
using GroupUpdatedNotification_ptr = const Poco::AutoPtr< AnalysisDataServiceImpl::GroupUpdatedNotification > &
using IAlgorithm_const_sptr = std::shared_ptr< const IAlgorithm >
shared pointer to Mantid::API::IAlgorithm (const version)
using IAlgorithm_const_uptr = std::unique_ptr< const IAlgorithm >
unique pointer to Mantid::API::IAlgorithm (const version)
using IAlgorithm_sptr = std::shared_ptr< IAlgorithm >
shared pointer to Mantid::API::IAlgorithm
using IAlgorithm_uptr = std::unique_ptr< IAlgorithm >
unique pointer to Mantid::API::IAlgorithm
using IArchiveSearch_sptr = std::shared_ptr< IArchiveSearch >
Typedef for a shared pointer to an IArchiveSearch.
using IBackgroundFunction_sptr = std::shared_ptr< IBackgroundFunction >
using ICatalog_const_sptr = std::shared_ptr< const ICatalog >
using ICatalog_sptr = std::shared_ptr< ICatalog >
using ICatalogInfoService_const_sptr = std::shared_ptr< const ICatalogInfoService >
using ICatalogInfoService_sptr = std::shared_ptr< ICatalogInfoService >
using ICostFunction_sptr = std::shared_ptr< ICostFunction >
define a shared pointer to a cost function
using IDomainCreator_sptr = std::shared_ptr< IDomainCreator >
Typedef for a shared pointer to IDomainCreator.
using IEventWorkspace_const_sptr = std::shared_ptr< const IEventWorkspace >
shared pointer to Mantid::API::IEventWorkspace (const version)
using IEventWorkspace_const_uptr = std::unique_ptr< const IEventWorkspace >
unique pointer to Mantid::API::IEventWorkspace (const version)
using IEventWorkspace_sptr = std::shared_ptr< IEventWorkspace >
shared pointer to Mantid::API::IEventWorkspace
using IEventWorkspace_uptr = std::unique_ptr< IEventWorkspace >
unique pointer to Mantid::API::IEventWorkspace
using IFuncMinimizer_sptr = std::shared_ptr< IFuncMinimizer >
using IFunction1D_sptr = std::shared_ptr< IFunction1D >
using IFunction_const_sptr = std::shared_ptr< const IFunction >
shared pointer to the function base class (const version)
using IFunction_sptr = std::shared_ptr< IFunction >
shared pointer to the function base class
using ILatticeFunction_sptr = std::shared_ptr< ILatticeFunction >
using ILiveListener_sptr = std::shared_ptr< ILiveListener >
Shared pointer to an ILiveListener.
using IMaskWorkspace_const_sptr = std::shared_ptr< const IMaskWorkspace >
shared pointer to the matrix workspace base class (const version)
using IMaskWorkspace_sptr = std::shared_ptr< IMaskWorkspace >
shared pointer to the matrix workspace base class
using IMDEventWorkspace_const_sptr = std::shared_ptr< const IMDEventWorkspace >
Shared pointer to Mantid::API::IMDEventWorkspace (const version)
using IMDEventWorkspace_const_uptr = std::unique_ptr< const IMDEventWorkspace >
unique pointer to Mantid::API::IMDEventWorkspace (const version)
using IMDEventWorkspace_sptr = std::shared_ptr< IMDEventWorkspace >
Shared pointer to Mantid::API::IMDEventWorkspace.
using IMDEventWorkspace_uptr = std::unique_ptr< IMDEventWorkspace >
unique pointer to Mantid::API::IMDEventWorkspace
using IMDHistoWorkspace_const_sptr = std::shared_ptr< const IMDHistoWorkspace >
shared pointer to Mantid::API::IMDHistoWorkspace (const version)
using IMDHistoWorkspace_const_uptr = std::unique_ptr< const IMDHistoWorkspace >
unique pointer to Mantid::API::IMDHistoWorkspace (const version)
using IMDHistoWorkspace_sptr = std::shared_ptr< IMDHistoWorkspace >
shared pointer to Mantid::API::IMDHistoWorkspace
using IMDHistoWorkspace_uptr = std::unique_ptr< IMDHistoWorkspace >
unique pointer to Mantid::API::IMDHistoWorkspace
using IMDWorkspace_const_sptr = std::shared_ptr< const IMDWorkspace >
Shared pointer to the IMDWorkspace base class (const version)
using IMDWorkspace_sptr = std::shared_ptr< IMDWorkspace >
Shared pointer to the IMDWorkspace base class.
using ImplicitFunctionFactory = Mantid::Kernel::SingletonHolder< ImplicitFunctionFactoryImpl >
using ImplicitFunctionParameterParserFactory = Mantid::Kernel::SingletonHolder< ImplicitFunctionParameterParserFactoryImpl >
using ImplicitFunctionParserFactory = Mantid::Kernel::SingletonHolder< ImplicitFunctionParserFactoryImpl >
using InstrumentDataService = Mantid::Kernel::SingletonHolder< InstrumentDataServiceImpl >
using IntegrationResultCache = std::pair< double, double >
using IPawleyFunction_sptr = std::shared_ptr< IPawleyFunction >
using IPeakFunction_const_sptr = std::shared_ptr< const IPeakFunction >
using IPeakFunction_sptr = std::shared_ptr< IPeakFunction >
using IPeaksWorkspace_const_sptr = std::shared_ptr< const IPeaksWorkspace >
shared pointer to Mantid::API::IPeaksWorkspace (const version)
using IPeaksWorkspace_const_uptr = std::unique_ptr< const IPeaksWorkspace >
unique pointer to Mantid::API::IPeaksWorkspace (const version)
using IPeaksWorkspace_sptr = std::shared_ptr< IPeaksWorkspace >
shared pointer to Mantid::API::IPeaksWorkspace
using IPeaksWorkspace_uptr = std::unique_ptr< IPeaksWorkspace >
unique pointer to Mantid::API::IPeaksWorkspace
using IPowderDiffPeakFunction_sptr = std::shared_ptr< IPowderDiffPeakFunction >
using IPreview_uptr = std::unique_ptr< IPreview >
using ISplittersWorkspace_const_sptr = std::shared_ptr< const ISplittersWorkspace >
Typedef for a shared pointer to const TableWorkspace.
using ISplittersWorkspace_sptr = std::shared_ptr< ISplittersWorkspace >
Typedef for a shared pointer to TableWorkspace.
using ITableWorkspace_const_sptr = std::shared_ptr< const ITableWorkspace >
shared pointer to Mantid::API::ITableWorkspace (const version)
using ITableWorkspace_const_uptr = std::unique_ptr< const ITableWorkspace >
unique pointer to Mantid::API::ITableWorkspace (const version)
using ITableWorkspace_sptr = std::shared_ptr< ITableWorkspace >
shared pointer to Mantid::API::ITableWorkspace
using ITableWorkspace_uptr = std::unique_ptr< ITableWorkspace >
unique pointer to Mantid::API::ITableWorkspace
using ITransformScale_sptr = std::shared_ptr< ITransformScale >
typedef for a shared pointer
using LiveListenerFactory = Kernel::SingletonHolder< LiveListenerFactoryImpl >
using LogManager_const_sptr = std::shared_ptr< const LogManager >
shared pointer to the logManager base class (const version)
using LogManager_sptr = std::shared_ptr< LogManager >
shared pointer to the logManager base class
using MantidImage = std::vector< std::vector< double > >
typedef for the image type
using MantidImage_const_sptr = std::shared_ptr< const MantidImage >
shared pointer to const MantidImage
using MantidImage_sptr = std::shared_ptr< MantidImage >
shared pointer to MantidImage
using MatrixWorkspace_const_sptr = std::shared_ptr< const MatrixWorkspace >
shared pointer to the matrix workspace base class (const version)
using MatrixWorkspace_const_uptr = std::unique_ptr< const MatrixWorkspace >
unique pointer to Mantid::API::MatrixWorkspace (const version)
using MatrixWorkspace_sptr = std::shared_ptr< MatrixWorkspace >
shared pointer to the matrix workspace base class
using MatrixWorkspace_uptr = std::unique_ptr< MatrixWorkspace >
unique pointer to Mantid::API::MatrixWorkspace
using MultiDomainFunction_const_sptr = std::shared_ptr< const MultiDomainFunction >
Shared pointer to Mantid::API::MultiDomainFunction (const version)
using MultiDomainFunction_sptr = std::shared_ptr< MultiDomainFunction >
Shared pointer to Mantid::API::MultiDomainFunction.
using MultipleExperimentInfos_const_sptr = std::shared_ptr< const MultipleExperimentInfos >
using MultipleExperimentInfos_sptr = std::shared_ptr< MultipleExperimentInfos >
using PreviewManager = Mantid::Kernel::SingletonHolder< PreviewManagerImpl >
using PreviewRegister = std::map< std::string, std::map< std::string, std::map< std::string, IPreview_uptr > > >
using Projection_sptr = std::shared_ptr< Projection >
using ScriptRepository_sptr = std::shared_ptr< ScriptRepository >
shared pointer to the function base class
using ScriptRepositoryFactory = Mantid::Kernel::SingletonHolder< ScriptRepositoryFactoryImpl >
using SpectrumInfoConstIt = SpectrumInfoIterator< const SpectrumInfo >
using SpectrumInfoIt = SpectrumInfoIterator< SpectrumInfo >
using tokenizer = Mantid::Kernel::StringTokenizer
using TransformScaleFactory = Mantid::Kernel::SingletonHolder< TransformScaleFactoryImpl >
using Workspace_const_sptr = std::shared_ptr< const Workspace >
shared pointer to Mantid::API::Workspace (const version)
using Workspace_const_uptr = std::unique_ptr< const Workspace >
unique pointer to Mantid::API::Workspace (const version)
using Workspace_sptr = std::shared_ptr< Workspace >
shared pointer to Mantid::API::Workspace
using Workspace_uptr = std::unique_ptr< Workspace >
unique pointer to Mantid::API::Workspace
using WorkspaceAddNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::AddNotification
using WorkspaceAddNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::AddNotification > &
using WorkspaceAfterReplaceNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::AfterReplaceNotification
using WorkspaceAfterReplaceNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::AfterReplaceNotification > &
using WorkspaceBeforeReplaceNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::BeforeReplaceNotification
using WorkspaceBeforeReplaceNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::BeforeReplaceNotification > &
using WorkspaceFactory = Mantid::Kernel::SingletonHolder< WorkspaceFactoryImpl >
using WorkspaceGroup_const_sptr = std::shared_ptr< const WorkspaceGroup >
shared pointer to Mantid::API::WorkspaceGroup, pointer to const version
using WorkspaceGroup_const_uptr = std::unique_ptr< const WorkspaceGroup >
unique pointer to Mantid::API::WorkspaceGroup (const version)
using WorkspaceGroup_sptr = std::shared_ptr< WorkspaceGroup >
shared pointer to Mantid::API::WorkspaceGroup
using WorkspaceGroup_uptr = std::unique_ptr< WorkspaceGroup >
unique pointer to Mantid::API::WorkspaceGroup
using WorkspacePostDeleteNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::PostDeleteNotification
using WorkspacePostDeleteNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::PostDeleteNotification > &
using WorkspacePreDeleteNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::PreDeleteNotification
using WorkspacePreDeleteNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::PreDeleteNotification > &
using WorkspaceRenameNotification = Mantid::Kernel::DataService< Mantid::API::Workspace >::RenameNotification
using WorkspaceRenameNotification_ptr = const Poco::AutoPtr< Mantid::Kernel::DataService< Mantid::API::Workspace >::RenameNotification > &
using WorkspacesGroupedNotification = AnalysisDataServiceImpl::GroupWorkspacesNotification
using WorkspacesGroupedNotification_ptr = const Poco::AutoPtr< AnalysisDataServiceImpl::GroupWorkspacesNotification > &
using WorkspaceUnGroupingNotification = AnalysisDataServiceImpl::UnGroupingWorkspaceNotification
using WorkspaceUnGroupingNotification_ptr = const Poco::AutoPtr< AnalysisDataServiceImpl::UnGroupingWorkspaceNotification > &
Enumerations
enum EventType { TOF , WEIGHTED , WEIGHTED_NOTIME }
What kind of event list is being stored.
enum class ExecutionState { Uninitialized , Initialized , Running , Finished }
The current state of the algorithm object.
enum class IndexType { SpectrumNum = 1 , WorkspaceIndex = 2 }
enum MDNormalization { NoNormalization = 0 , VolumeNormalization = 1 , NumEventsNormalization = 2 }
Enum describing different ways to normalize the signal in a MDWorkspace.
enum ProjectionUnit { RLU , INV_ANG }
Represents 3 dimensional projections.
enum class ResultState { NotFinished , Failed , Success }
The validity of the results of the algorithm object.
enum SCRIPTSTATUS {
BOTH_UNCHANGED = 0 , REMOTE_ONLY = (1u << 0) , LOCAL_ONLY = (1u << 1) , REMOTE_CHANGED = (1u << 2) ,
LOCAL_CHANGED = (1u << 3) , BOTH_CHANGED = (REMOTE_CHANGED | LOCAL_CHANGED)
}
Represent the possible states for a given file:
Functions
void applyRectangularDetectorScaleToComponentInfo (Geometry::ComponentInfo &componentInfo, const Geometry::ComponentID componentId, const double scaleX, const double scaleY)
MANTID_API_DLL void applyRectangularDetectorScaleToComponentInfo (Geometry::ComponentInfo &componentInfo, Geometry::IComponent *componentId, const double scaleX, const double scaleY)
Helpers for resizing RectangularDetectors.
template<class... Ts>
AttributeLambdaVisitor (Ts...) -> AttributeLambdaVisitor< Ts... >
template<typename T >
T checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
BoostOptionalToAlgorithmProperty : Checks for default values of an algorithm property if the user has not supplied the value.
template<>
MANTID_API_DLL std::string checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
Specializations for std::string.
template<>
std::string checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
Specializations for std::string.
template<typename T >
std::optional< T > checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
Checks for the default values of an optional algorithm property associated with an instrument component.
template<>
MANTID_API_DLL std::optional< std::string > checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
template<>
std::optional< std::string > checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string &propName, const Mantid::Geometry::Instrument_const_sptr &instrument, const std::string &idf_name)
bool containsMultipleData (const std::vector< MatrixWorkspace_sptr > &workspaces)
template<class T , class... InitArgs>
std::shared_ptr< T > createWorkspace (InitArgs... args)
static MatrixWorkspace_sptr createWorkspaceSingleValue (const double &rhsValue)
Creates a temporary single value workspace the error is set to zero.
std::complex< double > MANTID_API_DLL E1 (std::complex< double > z)
Integral for Gamma.
bool MANTID_API_DLL equals (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs, double tolerance)
Performs a comparison operation on two workspaces, using the CompareWorkspaces algorithm.
void getWordsInString (const std::string &words3, std::string &w1, std::string &w2, std::string &w3)
If the first string contains exactly three words separated by spaces these words will be copied into each of the following strings that were passed.
void getWordsInString (const std::string &words4, std::string &w1, std::string &w2, std::string &w3, std::string &w4)
If the first string contains exactly four words separated by spaces these words will be copied into each of the following strings that were passed.
double MANTID_API_DLL gsl_peak_wrapper (double x, void *parameters)
MatrixWorkspace_sptr MANTID_API_DLL operator* (const double &lhsValue, const MatrixWorkspace_sptr &rhs)
Multiply a workspace and a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator* (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Multiply a workspace and a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator* (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Multiply two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator*= (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Multiplies a workspace by a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator*= (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Multiply two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator+ (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Adds a workspace to a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator+ (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Adds two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator+= (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Adds a single value to a workspace.
MatrixWorkspace_sptr MANTID_API_DLL operator+= (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Adds two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator- (const double &lhsValue, const MatrixWorkspace_sptr &rhs)
Subtracts a workspace from a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator- (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Subtracts a single value from a workspace.
MatrixWorkspace_sptr MANTID_API_DLL operator- (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Subtracts two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator-= (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Subtracts a single value from a workspace.
MatrixWorkspace_sptr MANTID_API_DLL operator-= (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Subtracts two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator/ (const double &lhsValue, const MatrixWorkspace_sptr &rhs)
Divide a single value and a workspace.
MatrixWorkspace_sptr MANTID_API_DLL operator/ (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Divide a workspace by a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator/ (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Divide two workspaces.
MatrixWorkspace_sptr MANTID_API_DLL operator/= (const MatrixWorkspace_sptr &lhs, const double &rhsValue)
Divides a workspace by a single value.
MatrixWorkspace_sptr MANTID_API_DLL operator/= (const MatrixWorkspace_sptr &lhs, const MatrixWorkspace_sptr &rhs)
Divide two workspaces.
MANTID_API_DLL std::ostream & operator<< (std::ostream &, const API::Boolean &)
Printing Boolean to an output stream.
MANTID_API_DLL std::ostream & operator<< (std::ostream &os, const AlgorithmHistory &AH)
Prints a text representation.
MANTID_API_DLL std::ostream & operator<< (std::ostream &os, const WorkspaceHistory &WH)
Prints a text representation.
std::ostream & operator<< (std::ostream &ostr, const IFunction &f)
Operator <<.
MANTID_API_DLL std::ostream & operator<< (std::ostream &s, const TableRow &row)
Output stream operator.
MANTID_API_DLL std::istream & operator>> (std::istream &istr, API::Boolean &)
Redaing a Boolean from an input stream.
void renameWorkspace (const IAlgorithm_sptr &renamer, const Workspace_sptr &workspace, const std::string &newName)
void renameWorkspacesInQENSFit (Algorithm *qensFit, IAlgorithm_sptr renameAlgorithm, const WorkspaceGroup_sptr &outputGroup, std::string const &outputBaseName, std::function< std::string(std::size_t)> const &getNameSuffix)
void renameWorkspacesWith (const WorkspaceGroup_sptr &groupWorkspace, std::function< std::string(std::size_t)> const &getName, std::function< void(Workspace_sptr, const std::string &)> const &renamer)
MANTID_API_DLL void setPropertyModeForWorkspaceProperty (Mantid::Kernel::Property *prop, const PropertyMode::Type &optional)
Variables
const std::string COMMENT_ALG = "Comment"
const std::string EMPTY_EXPRESSION_NAME = "EMPTY"
Kernel::Logger g_log ("ExperimentInfo")
static logger object
static const signal_t MDMaskValue = std::numeric_limits<double>::quiet_NaN()
Typedef Documentation
Algorithm_sptr
using Mantid::API::Algorithm_sptr = typedef std::shared_ptr<Algorithm>
Typedef for a shared pointer to an Algorithm.
Definition at line 52 of file Algorithm.h.
AlgorithmFactory
using Mantid::API::AlgorithmFactory = typedef Mantid::Kernel::SingletonHolder<AlgorithmFactoryImpl>
Definition at line 165 of file AlgorithmFactory.h.
AlgorithmFactoryUpdateNotification
using Mantid::API::AlgorithmFactoryUpdateNotification = typedef Mantid::Kernel::DynamicFactory<Algorithm>::UpdateNotification
Convenient typedef for an UpdateNotification.
Definition at line 168 of file AlgorithmFactory.h.
AlgorithmFactoryUpdateNotification_ptr
using Mantid::API::AlgorithmFactoryUpdateNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DynamicFactory<Algorithm>::UpdateNotification> &
Definition at line 169 of file AlgorithmFactory.h.
AlgorithmHistories
using Mantid::API::AlgorithmHistories = typedef std::vector<AlgorithmHistory_sptr>
Definition at line 30 of file AlgorithmHistory.h.
AlgorithmHistory_const_sptr
using Mantid::API::AlgorithmHistory_const_sptr = typedef std::shared_ptr<const AlgorithmHistory>
Definition at line 29 of file AlgorithmHistory.h.
AlgorithmHistory_sptr
using Mantid::API::AlgorithmHistory_sptr = typedef std::shared_ptr<AlgorithmHistory>
Definition at line 28 of file AlgorithmHistory.h.
AlgorithmID
using Mantid::API::AlgorithmID = typedef void *
As we have multiple interfaces to the same logical algorithm we need a way of uniquely identifying managed algorithms.
It can be AlgorithmID.
Definition at line 28 of file IAlgorithm.h.
AlgorithmManager
using Mantid::API::AlgorithmManager = typedef Mantid::Kernel::SingletonHolder<AlgorithmManagerImpl>
Definition at line 86 of file AlgorithmManager.h.
AnalysisDataService
using Mantid::API::AnalysisDataService = typedef Mantid::Kernel::SingletonHolder<AnalysisDataServiceImpl>
Definition at line 158 of file AnalysisDataService.h.
ArchiveSearchFactory
using Mantid::API::ArchiveSearchFactory = typedef Mantid::Kernel::SingletonHolder<ArchiveSearchFactoryImpl>
Definition at line 41 of file ArchiveSearchFactory.h.
BoxController_const_sptr
using Mantid::API::BoxController_const_sptr = typedef std::shared_ptr<const BoxController>
Shared ptr to a const BoxController.
Definition at line 519 of file BoxController.h.
BoxController_sptr
using Mantid::API::BoxController_sptr = typedef std::shared_ptr<BoxController>
Shared ptr to BoxController.
Definition at line 516 of file BoxController.h.
CatalogFactory
using Mantid::API::CatalogFactory = typedef Mantid::Kernel::SingletonHolder<CatalogFactoryImpl>
The specialisation of the SingletonHolder class that holds the CatalogFactory.
Definition at line 63 of file CatalogFactory.h.
CatalogManager
using Mantid::API::CatalogManager = typedef Kernel::SingletonHolder<CatalogManagerImpl>
Definition at line 53 of file CatalogManager.h.
CatalogSession_const_sptr
using Mantid::API::CatalogSession_const_sptr = typedef std::shared_ptr<const CatalogSession>
Definition at line 37 of file CatalogSession.h.
CatalogSession_sptr
using Mantid::API::CatalogSession_sptr = typedef std::shared_ptr<CatalogSession>
Definition at line 36 of file CatalogSession.h.
ClearADSNotification
using Mantid::API::ClearADSNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::ClearNotification
Definition at line 181 of file AnalysisDataService.h.
ClearADSNotification_ptr
using Mantid::API::ClearADSNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::ClearNotification> &
Definition at line 182 of file AnalysisDataService.h.
Column_const_sptr
using Mantid::API::Column_const_sptr = typedef std::shared_ptr<const Column>
Definition at line 233 of file Column.h.
Column_sptr
using Mantid::API::Column_sptr = typedef std::shared_ptr<Column>
Definition at line 232 of file Column.h.
ColumnFactory
using Mantid::API::ColumnFactory = typedef Mantid::Kernel::SingletonHolder<ColumnFactoryImpl>
Definition at line 51 of file ColumnFactory.h.
CompositeFunction_const_sptr
typedef std::shared_ptr< const CompositeFunction > Mantid::API::CompositeFunction_const_sptr
shared pointer to the composite function base class (const version)
Shared pointer to Mantid::API::CompositeFunction (const version)
Definition at line 263 of file CompositeFunction.h.
CompositeFunction_sptr
typedef std::shared_ptr< CompositeFunction > Mantid::API::CompositeFunction_sptr
shared pointer to the composite function base class
Shared pointer to Mantid::API::CompositeFunction.
Definition at line 261 of file CompositeFunction.h.
ConstraintFactory
using Mantid::API::ConstraintFactory = typedef Mantid::Kernel::SingletonHolder<ConstraintFactoryImpl>
Definition at line 57 of file ConstraintFactory.h.
CoordTransform_const_sptr
using Mantid::API::CoordTransform_const_sptr = typedef std::shared_ptr<const CoordTransform>
Definition at line 70 of file CoordTransform.h.
CoordTransform_sptr
using Mantid::API::CoordTransform_sptr = typedef std::shared_ptr<CoordTransform>
Definition at line 67 of file CoordTransform.h.
CostFunctionFactory
using Mantid::API::CostFunctionFactory = typedef Mantid::Kernel::SingletonHolder<CostFunctionFactoryImpl>
Definition at line 50 of file CostFunctionFactory.h.
DataProcessorAlgorithm
using Mantid::API::DataProcessorAlgorithm = typedef GenericDataProcessorAlgorithm<Algorithm>
Definition at line 116 of file DataProcessorAlgorithm.h.
DomainCreatorFactory
using Mantid::API::DomainCreatorFactory = typedef Mantid::Kernel::SingletonHolder<DomainCreatorFactoryImpl>
Definition at line 56 of file DomainCreatorFactory.h.
ExperimentInfo_const_sptr
using Mantid::API::ExperimentInfo_const_sptr = typedef std::shared_ptr<const ExperimentInfo>
Shared pointer to const ExperimentInfo.
Definition at line 215 of file ExperimentInfo.h.
ExperimentInfo_sptr
using Mantid::API::ExperimentInfo_sptr = typedef std::shared_ptr<ExperimentInfo>
Shared pointer to ExperimentInfo.
Definition at line 212 of file ExperimentInfo.h.
FileFinder
using Mantid::API::FileFinder = typedef Mantid::Kernel::SingletonHolder<FileFinderImpl>
Definition at line 83 of file FileFinder.h.
FileLoaderRegistry
using Mantid::API::FileLoaderRegistry = typedef Mantid::Kernel::SingletonHolder<FileLoaderRegistryImpl>
Type for the actual singleton instance.
Definition at line 139 of file FileLoaderRegistry.h.
FrameworkManager
using Mantid::API::FrameworkManager = typedef Mantid::Kernel::SingletonHolder<FrameworkManagerImpl>
Definition at line 89 of file FrameworkManager.h.
FuncMinimizerFactory
using Mantid::API::FuncMinimizerFactory = typedef Mantid::Kernel::SingletonHolder<FuncMinimizerFactoryImpl>
Definition at line 47 of file FuncMinimizerFactory.h.
FunctionDomain1D_const_sptr
using Mantid::API::FunctionDomain1D_const_sptr = typedef std::shared_ptr<const FunctionDomain1D>
typedef for a shared pointer to a const FunctionDomain1D
Definition at line 161 of file FunctionDomain1D.h.
FunctionDomain1D_sptr
using Mantid::API::FunctionDomain1D_sptr = typedef std::shared_ptr<FunctionDomain1D>
typedef for a shared pointer to a FunctionDomain1D
Definition at line 159 of file FunctionDomain1D.h.
FunctionDomain_sptr
using Mantid::API::FunctionDomain_sptr = typedef std::shared_ptr<FunctionDomain>
typedef for a shared pointer
Definition at line 43 of file FunctionDomain.h.
FunctionFactory
using Mantid::API::FunctionFactory = typedef Mantid::Kernel::SingletonHolder<FunctionFactoryImpl>
Definition at line 132 of file FunctionFactory.h.
FunctionFactoryUpdateNotification
using Mantid::API::FunctionFactoryUpdateNotification = typedef FunctionFactoryImpl::UpdateNotification
Convenient typedef for an UpdateNotification.
Definition at line 135 of file FunctionFactory.h.
FunctionFactoryUpdateNotification_ptr
using Mantid::API::FunctionFactoryUpdateNotification_ptr = typedef const Poco::AutoPtr<FunctionFactoryUpdateNotification> &
Convenient typedef for an UpdateNotification AutoPtr.
Definition at line 137 of file FunctionFactory.h.
FunctionParameterDecorator_sptr
using Mantid::API::FunctionParameterDecorator_sptr = typedef std::shared_ptr<FunctionParameterDecorator>
Definition at line 137 of file FunctionParameterDecorator.h.
FunctionValues_sptr
using Mantid::API::FunctionValues_sptr = typedef std::shared_ptr<FunctionValues>
typedef for a shared pointer
Definition at line 108 of file FunctionValues.h.
GridDomain1D_sptr
using Mantid::API::GridDomain1D_sptr = typedef std::shared_ptr<GridDomain1D>
typedef for a shared pointer
Definition at line 44 of file GridDomain1D.h.
GridDomain_sptr
using Mantid::API::GridDomain_sptr = typedef std::shared_ptr<GridDomain>
typedef for a shared pointer
Definition at line 45 of file GridDomain.h.
GroupUpdatedNotification
using Mantid::API::GroupUpdatedNotification = typedef AnalysisDataServiceImpl::GroupUpdatedNotification
Definition at line 196 of file AnalysisDataService.h.
GroupUpdatedNotification_ptr
using Mantid::API::GroupUpdatedNotification_ptr = typedef const Poco::AutoPtr<AnalysisDataServiceImpl::GroupUpdatedNotification> &
Definition at line 197 of file AnalysisDataService.h.
IAlgorithm_const_sptr
using Mantid::API::IAlgorithm_const_sptr = typedef std::shared_ptr<const IAlgorithm>
shared pointer to Mantid::API::IAlgorithm (const version)
Definition at line 22 of file IAlgorithm_fwd.h.
IAlgorithm_const_uptr
using Mantid::API::IAlgorithm_const_uptr = typedef std::unique_ptr<const IAlgorithm>
unique pointer to Mantid::API::IAlgorithm (const version)
Definition at line 26 of file IAlgorithm_fwd.h.
IAlgorithm_sptr
using Mantid::API::IAlgorithm_sptr = typedef std::shared_ptr<IAlgorithm>
shared pointer to Mantid::API::IAlgorithm
Definition at line 20 of file IAlgorithm_fwd.h.
IAlgorithm_uptr
using Mantid::API::IAlgorithm_uptr = typedef std::unique_ptr<IAlgorithm>
unique pointer to Mantid::API::IAlgorithm
Definition at line 24 of file IAlgorithm_fwd.h.
IArchiveSearch_sptr
using Mantid::API::IArchiveSearch_sptr = typedef std::shared_ptr<IArchiveSearch>
Typedef for a shared pointer to an IArchiveSearch.
Definition at line 53 of file IArchiveSearch.h.
IBackgroundFunction_sptr
using Mantid::API::IBackgroundFunction_sptr = typedef std::shared_ptr<IBackgroundFunction>
Definition at line 30 of file IBackgroundFunction.h.
ICatalog_const_sptr
using Mantid::API::ICatalog_const_sptr = typedef std::shared_ptr<const ICatalog>
Definition at line 56 of file ICatalog.h.
ICatalog_sptr
using Mantid::API::ICatalog_sptr = typedef std::shared_ptr<ICatalog>
Definition at line 55 of file ICatalog.h.
ICatalogInfoService_const_sptr
using Mantid::API::ICatalogInfoService_const_sptr = typedef std::shared_ptr<const ICatalogInfoService>
Definition at line 38 of file ICatalogInfoService.h.
ICatalogInfoService_sptr
using Mantid::API::ICatalogInfoService_sptr = typedef std::shared_ptr<ICatalogInfoService>
Definition at line 37 of file ICatalogInfoService.h.
ICostFunction_sptr
using Mantid::API::ICostFunction_sptr = typedef std::shared_ptr<ICostFunction>
define a shared pointer to a cost function
Definition at line 60 of file ICostFunction.h.
IDomainCreator_sptr
using Mantid::API::IDomainCreator_sptr = typedef std::shared_ptr<IDomainCreator>
Typedef for a shared pointer to IDomainCreator.
Definition at line 128 of file IDomainCreator.h.
IEventWorkspace_const_sptr
using Mantid::API::IEventWorkspace_const_sptr = typedef std::shared_ptr<const IEventWorkspace>
shared pointer to Mantid::API::IEventWorkspace (const version)
Definition at line 22 of file IEventWorkspace_fwd.h.
IEventWorkspace_const_uptr
using Mantid::API::IEventWorkspace_const_uptr = typedef std::unique_ptr<const IEventWorkspace>
unique pointer to Mantid::API::IEventWorkspace (const version)
Definition at line 26 of file IEventWorkspace_fwd.h.
IEventWorkspace_sptr
using Mantid::API::IEventWorkspace_sptr = typedef std::shared_ptr<IEventWorkspace>
shared pointer to Mantid::API::IEventWorkspace
Definition at line 20 of file IEventWorkspace_fwd.h.
IEventWorkspace_uptr
using Mantid::API::IEventWorkspace_uptr = typedef std::unique_ptr<IEventWorkspace>
unique pointer to Mantid::API::IEventWorkspace
Definition at line 24 of file IEventWorkspace_fwd.h.
IFuncMinimizer_sptr
using Mantid::API::IFuncMinimizer_sptr = typedef std::shared_ptr<IFuncMinimizer>
Definition at line 59 of file IFuncMinimizer.h.
IFunction1D_sptr
using Mantid::API::IFunction1D_sptr = typedef std::shared_ptr<IFunction1D>
Definition at line 80 of file IFunction1D.h.
IFunction_const_sptr
typedef std::shared_ptr< const IFunction > Mantid::API::IFunction_const_sptr
shared pointer to the function base class (const version)
Shared pointer to Mantid::API::IFunction (const version)
Definition at line 745 of file IFunction.h.
IFunction_sptr
typedef std::shared_ptr< IFunction > Mantid::API::IFunction_sptr
shared pointer to the function base class
Shared pointer to Mantid::API::IFunction.
Definition at line 743 of file IFunction.h.
ILatticeFunction_sptr
using Mantid::API::ILatticeFunction_sptr = typedef std::shared_ptr<ILatticeFunction>
Definition at line 51 of file ILatticeFunction.h.
ILiveListener_sptr
using Mantid::API::ILiveListener_sptr = typedef std::shared_ptr<ILiveListener>
Shared pointer to an ILiveListener.
Definition at line 135 of file ILiveListener.h.
IMaskWorkspace_const_sptr
using Mantid::API::IMaskWorkspace_const_sptr = typedef std::shared_ptr<const IMaskWorkspace>
shared pointer to the matrix workspace base class (const version)
Definition at line 62 of file IMaskWorkspace.h.
IMaskWorkspace_sptr
using Mantid::API::IMaskWorkspace_sptr = typedef std::shared_ptr<IMaskWorkspace>
shared pointer to the matrix workspace base class
Definition at line 60 of file IMaskWorkspace.h.
IMDEventWorkspace_const_sptr
using Mantid::API::IMDEventWorkspace_const_sptr = typedef std::shared_ptr<const IMDEventWorkspace>
Shared pointer to Mantid::API::IMDEventWorkspace (const version)
Definition at line 23 of file IMDEventWorkspace_fwd.h.
IMDEventWorkspace_const_uptr
using Mantid::API::IMDEventWorkspace_const_uptr = typedef std::unique_ptr<const IMDEventWorkspace>
unique pointer to Mantid::API::IMDEventWorkspace (const version)
Definition at line 27 of file IMDEventWorkspace_fwd.h.
IMDEventWorkspace_sptr
using Mantid::API::IMDEventWorkspace_sptr = typedef std::shared_ptr<IMDEventWorkspace>
Shared pointer to Mantid::API::IMDEventWorkspace.
Definition at line 21 of file IMDEventWorkspace_fwd.h.
IMDEventWorkspace_uptr
using Mantid::API::IMDEventWorkspace_uptr = typedef std::unique_ptr<IMDEventWorkspace>
unique pointer to Mantid::API::IMDEventWorkspace
Definition at line 25 of file IMDEventWorkspace_fwd.h.
IMDHistoWorkspace_const_sptr
using Mantid::API::IMDHistoWorkspace_const_sptr = typedef std::shared_ptr<const IMDHistoWorkspace>
shared pointer to Mantid::API::IMDHistoWorkspace (const version)
Definition at line 22 of file IMDHistoWorkspace_fwd.h.
IMDHistoWorkspace_const_uptr
using Mantid::API::IMDHistoWorkspace_const_uptr = typedef std::unique_ptr<const IMDHistoWorkspace>
unique pointer to Mantid::API::IMDHistoWorkspace (const version)
Definition at line 26 of file IMDHistoWorkspace_fwd.h.
IMDHistoWorkspace_sptr
using Mantid::API::IMDHistoWorkspace_sptr = typedef std::shared_ptr<IMDHistoWorkspace>
shared pointer to Mantid::API::IMDHistoWorkspace
Definition at line 20 of file IMDHistoWorkspace_fwd.h.
IMDHistoWorkspace_uptr
using Mantid::API::IMDHistoWorkspace_uptr = typedef std::unique_ptr<IMDHistoWorkspace>
unique pointer to Mantid::API::IMDHistoWorkspace
Definition at line 24 of file IMDHistoWorkspace_fwd.h.
IMDWorkspace_const_sptr
using Mantid::API::IMDWorkspace_const_sptr = typedef std::shared_ptr<const IMDWorkspace>
Shared pointer to the IMDWorkspace base class (const version)
Definition at line 148 of file IMDWorkspace.h.
IMDWorkspace_sptr
using Mantid::API::IMDWorkspace_sptr = typedef std::shared_ptr<IMDWorkspace>
Shared pointer to the IMDWorkspace base class.
Definition at line 146 of file IMDWorkspace.h.
ImplicitFunctionFactory
using Mantid::API::ImplicitFunctionFactory = typedef Mantid::Kernel::SingletonHolder<ImplicitFunctionFactoryImpl>
Definition at line 46 of file ImplicitFunctionFactory.h.
ImplicitFunctionParameterParserFactory
using Mantid::API::ImplicitFunctionParameterParserFactory = typedef Mantid::Kernel::SingletonHolder<ImplicitFunctionParameterParserFactoryImpl>
Definition at line 45 of file ImplicitFunctionParameterParserFactory.h.
ImplicitFunctionParserFactory
using Mantid::API::ImplicitFunctionParserFactory = typedef Mantid::Kernel::SingletonHolder<ImplicitFunctionParserFactoryImpl>
Definition at line 45 of file ImplicitFunctionParserFactory.h.
InstrumentDataService
using Mantid::API::InstrumentDataService = typedef Mantid::Kernel::SingletonHolder<InstrumentDataServiceImpl>
Definition at line 33 of file InstrumentDataService.h.
IntegrationResultCache
using Mantid::API::IntegrationResultCache = typedef std::pair<double, double>
Definition at line 44 of file IPeakFunction.h.
IPawleyFunction_sptr
using Mantid::API::IPawleyFunction_sptr = typedef std::shared_ptr<IPawleyFunction>
Definition at line 57 of file IPawleyFunction.h.
IPeakFunction_const_sptr
using Mantid::API::IPeakFunction_const_sptr = typedef std::shared_ptr<const IPeakFunction>
Definition at line 142 of file IPeakFunction.h.
IPeakFunction_sptr
using Mantid::API::IPeakFunction_sptr = typedef std::shared_ptr<IPeakFunction>
Definition at line 141 of file IPeakFunction.h.
IPeaksWorkspace_const_sptr
using Mantid::API::IPeaksWorkspace_const_sptr = typedef std::shared_ptr<const IPeaksWorkspace>
shared pointer to Mantid::API::IPeaksWorkspace (const version)
Definition at line 22 of file IPeaksWorkspace_fwd.h.
IPeaksWorkspace_const_uptr
using Mantid::API::IPeaksWorkspace_const_uptr = typedef std::unique_ptr<const IPeaksWorkspace>
unique pointer to Mantid::API::IPeaksWorkspace (const version)
Definition at line 26 of file IPeaksWorkspace_fwd.h.
IPeaksWorkspace_sptr
using Mantid::API::IPeaksWorkspace_sptr = typedef std::shared_ptr<IPeaksWorkspace>
shared pointer to Mantid::API::IPeaksWorkspace
Definition at line 20 of file IPeaksWorkspace_fwd.h.
IPeaksWorkspace_uptr
using Mantid::API::IPeaksWorkspace_uptr = typedef std::unique_ptr<IPeaksWorkspace>
unique pointer to Mantid::API::IPeaksWorkspace
Definition at line 24 of file IPeaksWorkspace_fwd.h.
IPowderDiffPeakFunction_sptr
using Mantid::API::IPowderDiffPeakFunction_sptr = typedef std::shared_ptr<IPowderDiffPeakFunction>
Definition at line 138 of file IPowderDiffPeakFunction.h.
IPreview_uptr
using Mantid::API::IPreview_uptr = typedef std::unique_ptr<IPreview>
Definition at line 37 of file IPreview.h.
ISplittersWorkspace_const_sptr
using Mantid::API::ISplittersWorkspace_const_sptr = typedef std::shared_ptr<const ISplittersWorkspace>
Typedef for a shared pointer to const TableWorkspace.
Definition at line 67 of file ISplittersWorkspace.h.
ISplittersWorkspace_sptr
using Mantid::API::ISplittersWorkspace_sptr = typedef std::shared_ptr<ISplittersWorkspace>
Typedef for a shared pointer to TableWorkspace.
Definition at line 65 of file ISplittersWorkspace.h.
ITableWorkspace_const_sptr
using Mantid::API::ITableWorkspace_const_sptr = typedef std::shared_ptr<const ITableWorkspace>
shared pointer to Mantid::API::ITableWorkspace (const version)
Definition at line 22 of file ITableWorkspace_fwd.h.
ITableWorkspace_const_uptr
using Mantid::API::ITableWorkspace_const_uptr = typedef std::unique_ptr<const ITableWorkspace>
unique pointer to Mantid::API::ITableWorkspace (const version)
Definition at line 26 of file ITableWorkspace_fwd.h.
ITableWorkspace_sptr
using Mantid::API::ITableWorkspace_sptr = typedef std::shared_ptr<ITableWorkspace>
shared pointer to Mantid::API::ITableWorkspace
Definition at line 20 of file ITableWorkspace_fwd.h.
ITableWorkspace_uptr
using Mantid::API::ITableWorkspace_uptr = typedef std::unique_ptr<ITableWorkspace>
unique pointer to Mantid::API::ITableWorkspace
Definition at line 24 of file ITableWorkspace_fwd.h.
ITransformScale_sptr
using Mantid::API::ITransformScale_sptr = typedef std::shared_ptr<ITransformScale>
typedef for a shared pointer
Definition at line 41 of file ITransformScale.h.
LiveListenerFactory
using Mantid::API::LiveListenerFactory = typedef Kernel::SingletonHolder<LiveListenerFactoryImpl>
Definition at line 65 of file LiveListenerFactory.h.
LogManager_const_sptr
using Mantid::API::LogManager_const_sptr = typedef std::shared_ptr<const LogManager>
shared pointer to the logManager base class (const version)
Definition at line 231 of file LogManager.h.
LogManager_sptr
using Mantid::API::LogManager_sptr = typedef std::shared_ptr<LogManager>
shared pointer to the logManager base class
Definition at line 229 of file LogManager.h.
MantidImage
using Mantid::API::MantidImage = typedef std::vector<std::vector<double> >
typedef for the image type
Definition at line 80 of file MatrixWorkspace.h.
MantidImage_const_sptr
using Mantid::API::MantidImage_const_sptr = typedef std::shared_ptr<const MantidImage>
shared pointer to const MantidImage
Definition at line 84 of file MatrixWorkspace.h.
MantidImage_sptr
using Mantid::API::MantidImage_sptr = typedef std::shared_ptr<MantidImage>
shared pointer to MantidImage
Definition at line 82 of file MatrixWorkspace.h.
MatrixWorkspace_const_sptr
typedef std::shared_ptr< const MatrixWorkspace > Mantid::API::MatrixWorkspace_const_sptr
shared pointer to the matrix workspace base class (const version)
shared pointer to Mantid::API::MatrixWorkspace (const version)
Definition at line 587 of file MatrixWorkspace.h.
MatrixWorkspace_const_uptr
using Mantid::API::MatrixWorkspace_const_uptr = typedef std::unique_ptr<const MatrixWorkspace>
unique pointer to Mantid::API::MatrixWorkspace (const version)
Definition at line 26 of file MatrixWorkspace_fwd.h.
MatrixWorkspace_sptr
typedef std::shared_ptr< MatrixWorkspace > Mantid::API::MatrixWorkspace_sptr
shared pointer to the matrix workspace base class
shared pointer to Mantid::API::MatrixWorkspace
Definition at line 585 of file MatrixWorkspace.h.
MatrixWorkspace_uptr
using Mantid::API::MatrixWorkspace_uptr = typedef std::unique_ptr<MatrixWorkspace>
unique pointer to Mantid::API::MatrixWorkspace
Definition at line 24 of file MatrixWorkspace_fwd.h.
MultiDomainFunction_const_sptr
using Mantid::API::MultiDomainFunction_const_sptr = typedef std::shared_ptr<const MultiDomainFunction>
Shared pointer to Mantid::API::MultiDomainFunction (const version)
Definition at line 37 of file IFunction_fwd.h.
MultiDomainFunction_sptr
using Mantid::API::MultiDomainFunction_sptr = typedef std::shared_ptr<MultiDomainFunction>
Shared pointer to Mantid::API::MultiDomainFunction.
Definition at line 35 of file IFunction_fwd.h.
MultipleExperimentInfos_const_sptr
using Mantid::API::MultipleExperimentInfos_const_sptr = typedef std::shared_ptr<const MultipleExperimentInfos>
Definition at line 52 of file MultipleExperimentInfos.h.
MultipleExperimentInfos_sptr
using Mantid::API::MultipleExperimentInfos_sptr = typedef std::shared_ptr<MultipleExperimentInfos>
Definition at line 51 of file MultipleExperimentInfos.h.
PreviewManager
using Mantid::API::PreviewManager = typedef Mantid::Kernel::SingletonHolder<PreviewManagerImpl>
Definition at line 54 of file PreviewManager.h.
PreviewRegister
using Mantid::API::PreviewRegister = typedef std::map<std::string, std::map<std::string, std::map<std::string, IPreview_uptr> >>
Definition at line 22 of file PreviewManager.h.
Projection_sptr
using Mantid::API::Projection_sptr = typedef std::shared_ptr<Projection>
Definition at line 70 of file Projection.h.
ScriptRepository_sptr
using Mantid::API::ScriptRepository_sptr = typedef std::shared_ptr<ScriptRepository>
shared pointer to the function base class
Definition at line 588 of file ScriptRepository.h.
ScriptRepositoryFactory
using Mantid::API::ScriptRepositoryFactory = typedef Mantid::Kernel::SingletonHolder<ScriptRepositoryFactoryImpl>
Definition at line 53 of file ScriptRepositoryFactory.h.
SpectrumInfoConstIt
using Mantid::API::SpectrumInfoConstIt = typedef SpectrumInfoIterator<const SpectrumInfo>
Definition at line 116 of file SpectrumInfo.h.
SpectrumInfoIt
using Mantid::API::SpectrumInfoIt = typedef SpectrumInfoIterator<SpectrumInfo>
Definition at line 115 of file SpectrumInfo.h.
tokenizer
using Mantid::API::tokenizer = typedef Mantid::Kernel::StringTokenizer
Definition at line 17 of file Expression.cpp.
TransformScaleFactory
using Mantid::API::TransformScaleFactory = typedef Mantid::Kernel::SingletonHolder<TransformScaleFactoryImpl>
Definition at line 50 of file TransformScaleFactory.h.
Workspace_const_sptr
using Mantid::API::Workspace_const_sptr = typedef std::shared_ptr<const Workspace>
shared pointer to Mantid::API::Workspace (const version)
Definition at line 22 of file Workspace_fwd.h.
Workspace_const_uptr
using Mantid::API::Workspace_const_uptr = typedef std::unique_ptr<const Workspace>
unique pointer to Mantid::API::Workspace (const version)
Definition at line 26 of file Workspace_fwd.h.
Workspace_sptr
using Mantid::API::Workspace_sptr = typedef std::shared_ptr<Workspace>
shared pointer to Mantid::API::Workspace
Definition at line 20 of file Workspace_fwd.h.
Workspace_uptr
using Mantid::API::Workspace_uptr = typedef std::unique_ptr<Workspace>
unique pointer to Mantid::API::Workspace
Definition at line 24 of file Workspace_fwd.h.
WorkspaceAddNotification
using Mantid::API::WorkspaceAddNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::AddNotification
Definition at line 160 of file AnalysisDataService.h.
WorkspaceAddNotification_ptr
using Mantid::API::WorkspaceAddNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::AddNotification> &
Definition at line 161 of file AnalysisDataService.h.
WorkspaceAfterReplaceNotification
using Mantid::API::WorkspaceAfterReplaceNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::AfterReplaceNotification
Definition at line 169 of file AnalysisDataService.h.
WorkspaceAfterReplaceNotification_ptr
using Mantid::API::WorkspaceAfterReplaceNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::AfterReplaceNotification> &
Definition at line 170 of file AnalysisDataService.h.
WorkspaceBeforeReplaceNotification
using Mantid::API::WorkspaceBeforeReplaceNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::BeforeReplaceNotification
Definition at line 164 of file AnalysisDataService.h.
WorkspaceBeforeReplaceNotification_ptr
using Mantid::API::WorkspaceBeforeReplaceNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::BeforeReplaceNotification> &
Definition at line 166 of file AnalysisDataService.h.
WorkspaceFactory
using Mantid::API::WorkspaceFactory = typedef Mantid::Kernel::SingletonHolder<WorkspaceFactoryImpl>
Definition at line 72 of file WorkspaceFactory.h.
WorkspaceGroup_const_sptr
using Mantid::API::WorkspaceGroup_const_sptr = typedef std::shared_ptr<const WorkspaceGroup>
shared pointer to Mantid::API::WorkspaceGroup, pointer to const version
Definition at line 22 of file WorkspaceGroup_fwd.h.
WorkspaceGroup_const_uptr
using Mantid::API::WorkspaceGroup_const_uptr = typedef std::unique_ptr<const WorkspaceGroup>
unique pointer to Mantid::API::WorkspaceGroup (const version)
Definition at line 26 of file WorkspaceGroup_fwd.h.
WorkspaceGroup_sptr
using Mantid::API::WorkspaceGroup_sptr = typedef std::shared_ptr<WorkspaceGroup>
shared pointer to Mantid::API::WorkspaceGroup
Definition at line 20 of file WorkspaceGroup_fwd.h.
WorkspaceGroup_uptr
using Mantid::API::WorkspaceGroup_uptr = typedef std::unique_ptr<WorkspaceGroup>
unique pointer to Mantid::API::WorkspaceGroup
Definition at line 24 of file WorkspaceGroup_fwd.h.
WorkspacePostDeleteNotification
using Mantid::API::WorkspacePostDeleteNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::PostDeleteNotification
Definition at line 177 of file AnalysisDataService.h.
WorkspacePostDeleteNotification_ptr
using Mantid::API::WorkspacePostDeleteNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::PostDeleteNotification> &
Definition at line 178 of file AnalysisDataService.h.
WorkspacePreDeleteNotification
using Mantid::API::WorkspacePreDeleteNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::PreDeleteNotification
Definition at line 173 of file AnalysisDataService.h.
WorkspacePreDeleteNotification_ptr
using Mantid::API::WorkspacePreDeleteNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::PreDeleteNotification> &
Definition at line 174 of file AnalysisDataService.h.
WorkspaceRenameNotification
using Mantid::API::WorkspaceRenameNotification = typedef Mantid::Kernel::DataService<Mantid::API::Workspace>::RenameNotification
Definition at line 185 of file AnalysisDataService.h.
WorkspaceRenameNotification_ptr
using Mantid::API::WorkspaceRenameNotification_ptr = typedef const Poco::AutoPtr<Mantid::Kernel::DataService<Mantid::API::Workspace>::RenameNotification> &
Definition at line 186 of file AnalysisDataService.h.
WorkspacesGroupedNotification
using Mantid::API::WorkspacesGroupedNotification = typedef AnalysisDataServiceImpl::GroupWorkspacesNotification
Definition at line 189 of file AnalysisDataService.h.
WorkspacesGroupedNotification_ptr
using Mantid::API::WorkspacesGroupedNotification_ptr = typedef const Poco::AutoPtr<AnalysisDataServiceImpl::GroupWorkspacesNotification> &
Definition at line 190 of file AnalysisDataService.h.
WorkspaceUnGroupingNotification
using Mantid::API::WorkspaceUnGroupingNotification = typedef AnalysisDataServiceImpl::UnGroupingWorkspaceNotification
Definition at line 192 of file AnalysisDataService.h.
WorkspaceUnGroupingNotification_ptr
using Mantid::API::WorkspaceUnGroupingNotification_ptr = typedef const Poco::AutoPtr<AnalysisDataServiceImpl::UnGroupingWorkspaceNotification> &
Definition at line 193 of file AnalysisDataService.h.
Enumeration Type Documentation
EventType
enum Mantid::API::EventType
What kind of event list is being stored.
Enumerator
TOF
WEIGHTED
WEIGHTED_NOTIME
Definition at line 18 of file IEventList.h.
ExecutionState
enum class Mantid::API::ExecutionState strong
The current state of the algorithm object.
Enumerator
Uninitialized
Initialized
Running
Finished
Definition at line 31 of file IAlgorithm.h.
IndexType
enum class Mantid::API::IndexType strong
Enumerator
SpectrumNum
WorkspaceIndex
Definition at line 15 of file IndexTypeProperty.h.
MDNormalization
enum Mantid::API::MDNormalization
Enum describing different ways to normalize the signal in a MDWorkspace.
Enumerator
NoNormalization
Don't normalize = return raw counts.
VolumeNormalization
Divide the signal by the volume of the box/bin.
NumEventsNormalization
Divide the signal by the number of events that contributed to it.
Definition at line 25 of file IMDIterator.h.
ProjectionUnit
enum Mantid::API::ProjectionUnit
Represents 3 dimensional projections.
Author
Harry Jeffery
Date
2015-02-5 The units for a given dimension
Enumerator
RLU
INV_ANG
Definition at line 27 of file Projection.h.
ResultState
enum class Mantid::API::ResultState strong
The validity of the results of the algorithm object.
Enumerator
NotFinished
Failed
Success
Definition at line 33 of file IAlgorithm.h.
SCRIPTSTATUS
enum Mantid::API::SCRIPTSTATUS
Represent the possible states for a given file:
REMOTE_ONLY: it exists only at the remote repository.
LOCAL_ONLY: it exists only at the local folder.
REMOTE_CHANGED: it has been changed remotely, may be updated.
LOCAL_CHANGED: it has been modified locally, may be published.
BOTH_CHANGED: modified locally and remotelly.
BOTH_UNCHANGED: the local file is a copy of the remotely one.
For folders, the reason are slightly different:
REMOTE_ONLY: the folder exists only remotely.
LOCAL_ONLY: the folder exists only locally.
BOTH_UNCHANGED: if no file inside the folder has the XXX_CHANGED status.
BOTH_CHANGED: if inside the folder it has one file with BOTH_CHANGED status or one REMOTE_CHANGED with another LOCAL_CHANGED.
REMOTE_CHANGED: at least one marked with REMOTE_CHANGED and others as REMOTE_CHANGED or BOTH_UNCHANGED.
LOCAL_CHANGED: analogous to REMOTE_CHANGED, but locally.
Enumerator
BOTH_UNCHANGED
REMOTE_ONLY
LOCAL_ONLY
REMOTE_CHANGED
LOCAL_CHANGED
BOTH_CHANGED
Definition at line 50 of file ScriptRepository.h.
Function Documentation
applyRectangularDetectorScaleToComponentInfo() [1/2]
void Mantid::API::applyRectangularDetectorScaleToComponentInfo (Geometry::ComponentInfo & componentInfo, const Geometry::ComponentID componentId, const double scaleX, const double scaleY)
Definition at line 14 of file ResizeRectangularDetectorHelper.cpp.
References Mantid::Kernel::Quat::conjugate(), Mantid::Geometry::ComponentInfo::detectorsInSubtree(), index, Mantid::Geometry::ComponentInfo::indexOf(), Mantid::Geometry::ComponentInfo::position(), Mantid::Geometry::ComponentInfo::rotation(), rotation, Mantid::Geometry::ComponentInfo::setPosition(), Mantid::Kernel::toQuaterniond(), Mantid::Kernel::toV3D(), and Mantid::Kernel::toVector3d().
applyRectangularDetectorScaleToComponentInfo() [2/2]
MANTID_API_DLL void Mantid::API::applyRectangularDetectorScaleToComponentInfo (Geometry::ComponentInfo & componentInfo, Geometry::IComponent * componentId, const double scaleX, const double scaleY)
Helpers for resizing RectangularDetectors.
Referenced by Mantid::Crystal::CalibrationHelpers::adjustBankPositionsAndSizes(), Mantid::Algorithms::ResizeRectangularDetector::exec(), Mantid::Crystal::SCDPanelErrors::moveDetector(), and Mantid::Crystal::SCDCalibratePanels2ObjFunc::scaleRectagularDetectorSize().
AttributeLambdaVisitor()
template<class... Ts> Mantid::API::AttributeLambdaVisitor (Ts...) -> AttributeLambdaVisitor< Ts... >
checkForMandatoryInstrumentDefault() [1/3]
template<typename T > T Mantid::API::checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
BoostOptionalToAlgorithmProperty : Checks for default values of an algorithm property if the user has not supplied the value.
If it is a mandatory property then the value will be returned, if the property is optional then a value of type std::optional<T> will be returned. Checks for the default values of a mandatory algorithm property associated with an instrument component. i.e MonitorIndex
Parameters
alg : A pointer to the algorithm to which the property belongs
propName : The name of the property in the algorithm
instrument : A pointer to the instrument
idf_name : The name of the property in the Instrument Defintion
Returns
A value of type T that is either the default value or the user supplied value.
Definition at line 38 of file BoostOptionalToAlgorithmProperty.h.
References Mantid::API::Algorithm::getPointerToProperty().
checkForMandatoryInstrumentDefault() [2/3]
template<> MANTID_API_DLL std::string Mantid::API::checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
Specializations for std::string.
Definition at line 11 of file BoostOptionalToAlgorithmProperty.cpp.
References Mantid::API::Algorithm::getPointerToProperty().
checkForMandatoryInstrumentDefault() [3/3]
template<> std::string Mantid::API::checkForMandatoryInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
Specializations for std::string.
Definition at line 11 of file BoostOptionalToAlgorithmProperty.cpp.
References Mantid::API::Algorithm::getPointerToProperty().
checkForOptionalInstrumentDefault() [1/3]
template<typename T > std::optional< T > Mantid::API::checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
Checks for the default values of an optional algorithm property associated with an instrument component.
i.e MonitorIndex
Parameters
alg : A pointer to the algorithm to which the property belongs
propName : The name of the property in the algorithm
instrument : A pointer to the instrument
idf_name : The name of the property in the Instrument Defintion
Returns
A boost optional value of type T that is either the default value, the user supplied value or an uninitialized std::optional.
Definition at line 69 of file BoostOptionalToAlgorithmProperty.h.
References Mantid::API::Algorithm::getPointerToProperty(), and value.
checkForOptionalInstrumentDefault() [2/3]
template<> MANTID_API_DLL std::optional< std::string > Mantid::API::checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
Definition at line 29 of file BoostOptionalToAlgorithmProperty.cpp.
References Mantid::API::Algorithm::getPointerToProperty().
checkForOptionalInstrumentDefault() [3/3]
template<> std::optional< std::string > Mantid::API::checkForOptionalInstrumentDefault (const Mantid::API::Algorithm *const alg, const std::string & propName, const Mantid::Geometry::Instrument_const_sptr & instrument, const std::string & idf_name)
Definition at line 29 of file BoostOptionalToAlgorithmProperty.cpp.
References Mantid::API::Algorithm::getPointerToProperty().
containsMultipleData()
bool Mantid::API::containsMultipleData (const std::vector< MatrixWorkspace_sptr > & workspaces)
Definition at line 35 of file QENSFitUtilities.cpp.
References workspace.
Referenced by Mantid::CurveFitting::Algorithms::QENSFitSequential::exec(), and Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::execConcrete().
createWorkspace()
template<class T , class... InitArgs> std::shared_ptr< T > Mantid::API::createWorkspace (InitArgs... args)
Definition at line 74 of file WorkspaceFactory.h.
Referenced by Mantid::IndirectFitDataCreationHelper::createGroupWorkspace(), Mantid::DataHandling::LoadSpice2D::createWorkspace(), Mantid::IndirectFitDataCreationHelper::createWorkspaceWithBinValues(), Mantid::IndirectFitDataCreationHelper::createWorkspaceWithIndirectInstrumentAndParameters(), Mantid::IndirectFitDataCreationHelper::createWorkspaceWithTextAxis(), Mantid::DataHandling::ExtractPolarizationEfficiencies::exec(), Mantid::DataHandling::LoadEMU< FD >::exec(), export_Projection(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::loadTransmission(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputPDF(), and Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::transferFileDataIntoWorkspace().
createWorkspaceSingleValue()
static MatrixWorkspace_sptr Mantid::API::createWorkspaceSingleValue (const double & rhsValue) static
Creates a temporary single value workspace the error is set to zero.
Parameters
rhsValue :: the value to use
Returns
The value in a workspace shared pointer
Definition at line 161 of file WorkspaceOpOverloads.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::API::GenericDataProcessorAlgorithm< Base >::divide(), UnaryOperationMDTestHelper::doTest(), Mantid::API::GenericDataProcessorAlgorithm< Base >::minus(), Mantid::API::GenericDataProcessorAlgorithm< Base >::multiply(), operator*(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-(), operator-=(), operator/(), operator/(), operator/=(), Mantid::API::GenericDataProcessorAlgorithm< Base >::plus(), and BinaryOperationMDTestHelper::setUpBinaryOperationMDTestHelper().
E1()
std::complex< double > Mantid::API::E1 (std::complex< double > z)
Integral for Gamma.
Implementation of complex integral E_1.
Definition at line 207 of file IPowderDiffPeakFunction.cpp.
References fabs, and Mantid::Geometry::z.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD2::calculateDistanceToEdge(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::calculateE1(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::calculateE1(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::calculateE1(), Mantid::MDAlgorithms::IntegratePeaksMD2::calculateE1(), Mantid::Algorithms::ModeratorTzero::CalculateT0elastic(), Mantid::Algorithms::ModeratorTzero::CalculateT0indirect(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calOmega(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calOmega(), Mantid::Algorithms::CompareWorkspaces::checkData(), Mantid::API::DetectorSearcher::createDetectorCache(), Mantid::MDAlgorithms::Integrate3DEvents::detectorQ(), Mantid::MDAlgorithms::IntegrateQLabEvents::detectorQ(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::ModeratorTzero::exec(), Mantid::Algorithms::PointByPointVCorrection::exec(), and Mantid::Algorithms::ModeratorTzero::execEvent().
equals()
bool Mantid::API::equals (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs, double tolerance)
Performs a comparison operation on two workspaces, using the CompareWorkspaces algorithm.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
tolerance :: acceptable difference for floating point numbers
Returns
bool, true if workspaces match
Definition at line 139 of file WorkspaceOpOverloads.cpp.
References rhs, and tolerance.
Referenced by export_MatrixWorkspace().
getWordsInString() [1/2]
void Mantid::API::getWordsInString (const std::string & words3, std::string & w1, std::string & w2, std::string & w3)
If the first string contains exactly three words separated by spaces these words will be copied into each of the following strings that were passed.
Parameters
[in] words3 a string with 3 words separated by spaces
[out] w1 the first word in the input string
[out] w2 the second word in the input string
[out] w3 the third word in the input string
Exceptions
out_of_range if there aren't exaltly three strings in the word
Definition at line 220 of file WorkspaceHistory.cpp.
References Mantid::Kernel::StringTokenizer::count(), and Mantid::Kernel::StringTokenizer::TOK_TRIM.
Referenced by Mantid::DataHandling::LoadNexusProcessed::addSampleProperty(), and Mantid::API::WorkspaceHistory::parseAlgorithmHistory().
getWordsInString() [2/2]
void Mantid::API::getWordsInString (const std::string & words4, std::string & w1, std::string & w2, std::string & w3, std::string & w4)
If the first string contains exactly four words separated by spaces these words will be copied into each of the following strings that were passed.
Parameters
[in] words4 a string with 4 words separated by spaces
[out] w1 the first word in the input string
[out] w2 the second word in the input string
[out] w3 the third word in the input string
[out] w4 the fourth word in the input string
Exceptions
out_of_range if there aren't exaltly four strings in the word
Definition at line 241 of file WorkspaceHistory.cpp.
References Mantid::Kernel::StringTokenizer::count(), and Mantid::Kernel::StringTokenizer::TOK_TRIM.
gsl_peak_wrapper()
double Mantid::API::gsl_peak_wrapper (double x, void * parameters)
Definition at line 189 of file PeakFunctionIntegrator.cpp.
References Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::API::PeakFunctionIntegrator::getGSLFunction().
operator*() [1/3]
MatrixWorkspace_sptr Mantid::API::operator* (const double & lhsValue, const MatrixWorkspace_sptr & rhs)
Multiply a workspace and a single value.
Allows you to write, e.g., 2*workspace.
Parameters
lhsValue :: the single value
rhs :: workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 242 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue(), and rhs.
operator*() [2/3]
MatrixWorkspace_sptr Mantid::API::operator* (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Multiply a workspace and a single value.
Parameters
lhs :: left hand side workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 231 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator*() [3/3]
MatrixWorkspace_sptr Mantid::API::operator* (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Multiply two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 222 of file WorkspaceOpOverloads.cpp.
References rhs.
Referenced by Mantid::Kernel::Matrix< T >::isOrthogonal(), Mantid::Kernel::Matrix< T >::isRotation(), Mantid::Geometry::operator*(), Mantid::Kernel::Matrix< T >::operator*=(), and Mantid::Kernel::Matrix< T >::toRotation().
operator*=() [1/2]
MatrixWorkspace_sptr Mantid::API::operator*= (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Multiplies a workspace by a single value.
Parameters
lhs :: workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 332 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator*=() [2/2]
MatrixWorkspace_sptr Mantid::API::operator*= (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Multiply two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 322 of file WorkspaceOpOverloads.cpp.
References rhs.
operator+() [1/2]
MatrixWorkspace_sptr Mantid::API::operator+ (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Adds a workspace to a single value.
Parameters
lhs :: left hand side workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 184 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator+() [2/2]
MatrixWorkspace_sptr Mantid::API::operator+ (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Adds two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 175 of file WorkspaceOpOverloads.cpp.
References rhs.
operator+=() [1/2]
MatrixWorkspace_sptr Mantid::API::operator+= (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Adds a single value to a workspace.
Parameters
lhs :: workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 292 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator+=() [2/2]
MatrixWorkspace_sptr Mantid::API::operator+= (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Adds two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 282 of file WorkspaceOpOverloads.cpp.
References rhs.
Referenced by Mantid::API::FunctionProperty::operator=(), Mantid::Kernel::PropertyWithValue< TYPE >::PropertyWithValue(), Mantid::API::Run::~Run(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::~TimeSeriesProperty().
operator-() [1/3]
MatrixWorkspace_sptr Mantid::API::operator- (const double & lhsValue, const MatrixWorkspace_sptr & rhs)
Subtracts a workspace from a single value.
Parameters
lhsValue :: the single value
rhs :: right-hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 213 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue(), and rhs.
operator-() [2/3]
MatrixWorkspace_sptr Mantid::API::operator- (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Subtracts a single value from a workspace.
Parameters
lhs :: left hand side workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 203 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator-() [3/3]
MatrixWorkspace_sptr Mantid::API::operator- (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Subtracts two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 194 of file WorkspaceOpOverloads.cpp.
References rhs.
operator-=() [1/2]
MatrixWorkspace_sptr Mantid::API::operator-= (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Subtracts a single value from a workspace.
Parameters
lhs :: workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 312 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator-=() [2/2]
MatrixWorkspace_sptr Mantid::API::operator-= (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Subtracts two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 302 of file WorkspaceOpOverloads.cpp.
References rhs.
operator/() [1/3]
MatrixWorkspace_sptr Mantid::API::operator/ (const double & lhsValue, const MatrixWorkspace_sptr & rhs)
Divide a single value and a workspace.
Allows you to write, e.g., 2/workspace.
Parameters
lhsValue :: the single value
rhs :: workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 272 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue(), and rhs.
operator/() [2/3]
MatrixWorkspace_sptr Mantid::API::operator/ (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Divide a workspace by a single value.
Parameters
lhs :: left hand side workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 261 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator/() [3/3]
MatrixWorkspace_sptr Mantid::API::operator/ (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Divide two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 252 of file WorkspaceOpOverloads.cpp.
References rhs.
operator/=() [1/2]
MatrixWorkspace_sptr Mantid::API::operator/= (const MatrixWorkspace_sptr & lhs, const double & rhsValue)
Divides a workspace by a single value.
Parameters
lhs :: workspace shared pointer
rhsValue :: the single value
Returns
The result in a workspace shared pointer
Definition at line 352 of file WorkspaceOpOverloads.cpp.
References createWorkspaceSingleValue().
operator/=() [2/2]
MatrixWorkspace_sptr Mantid::API::operator/= (const MatrixWorkspace_sptr & lhs, const MatrixWorkspace_sptr & rhs)
Divide two workspaces.
Parameters
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
Returns
The result in a workspace shared pointer
Definition at line 342 of file WorkspaceOpOverloads.cpp.
References rhs.
Referenced by Mantid::Nexus::NexusAddress::~NexusAddress().
operator<<() [1/5]
std::ostream & Mantid::API::operator<< (std::ostream & s, const API::Boolean & b)
Printing Boolean to an output stream.
Definition at line 53 of file Column.cpp.
References Mantid::API::Boolean::value.
operator<<() [2/5]
std::ostream & Mantid::API::operator<< (std::ostream & os, const AlgorithmHistory & AH)
Prints a text representation.
Parameters
os :: The ouput stream to write to
AH :: The AlgorithmHistory to output
Returns
The ouput stream
Definition at line 254 of file AlgorithmHistory.cpp.
References Mantid::API::AlgorithmHistory::printSelf().
operator<<() [3/5]
std::ostream & Mantid::API::operator<< (std::ostream & os, const WorkspaceHistory & WH)
Prints a text representation.
Parameters
os :: The ouput stream to write to
WH :: The WorkspaceHistory to output
Returns
The ouput stream
Definition at line 451 of file WorkspaceHistory.cpp.
References Mantid::API::WorkspaceHistory::printSelf().
operator<<() [4/5]
std::ostream & Mantid::API::operator<< (std::ostream & ostr, const IFunction & f)
Operator <<.
Parameters
ostr :: The output stream
f :: The IFunction
Definition at line 659 of file IFunction.cpp.
References Mantid::API::IFunction::asString().
operator<<() [5/5]
std::ostream & Mantid::API::operator<< (std::ostream & s, const TableRow & row)
Output stream operator.
Parameters
s :: Output stream
row :: The TableRow
Returns
stream representation of row
Definition at line 75 of file TableRow.cpp.
operator>>()
std::istream & Mantid::API::operator>> (std::istream & istr, API::Boolean & b)
Redaing a Boolean from an input stream.
Translate text into a Boolean.
Definition at line 61 of file Column.cpp.
renameWorkspace()
void Mantid::API::renameWorkspace (const IAlgorithm_sptr & renamer, const Workspace_sptr & workspace, const std::string & newName)
Definition at line 29 of file QENSFitUtilities.cpp.
References workspace.
Referenced by MantidQt::MantidWidgets::MantidTreeModel::MantidTreeModel(), MantidQt::MantidWidgets::FitScriptGeneratorModel::operator=(), renameWorkspacesInQENSFit(), MantidQt::MantidWidgets::FitScriptGeneratorDataTable::~FitScriptGeneratorDataTable(), and MantidQt::MantidWidgets::WorkspacePresenter::~WorkspacePresenter().
renameWorkspacesInQENSFit()
void Mantid::API::renameWorkspacesInQENSFit (Algorithm * qensFit, IAlgorithm_sptr renameAlgorithm, const WorkspaceGroup_sptr & outputGroup, std::string const & outputBaseName, std::function< std::string(std::size_t)> const & getNameSuffix)
Definition at line 41 of file QENSFitUtilities.cpp.
References getName(), name, renameWorkspace(), renameWorkspacesWith(), Mantid::Kernel::ProgressBase::report(), and workspace.
Referenced by Mantid::CurveFitting::Algorithms::QENSFitSequential::renameWorkspaces(), Mantid::CurveFitting::Algorithms::QENSFitSequential::renameWorkspaces(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::renameWorkspaces(), and Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::renameWorkspaces().
renameWorkspacesWith()
void Mantid::API::renameWorkspacesWith (const WorkspaceGroup_sptr & groupWorkspace, std::function< std::string(std::size_t)> const & getName, std::function< void(Workspace_sptr, const std::string &)> const & renamer)
Definition at line 13 of file QENSFitUtilities.cpp.
References count, getName(), name, and std::to_string().
Referenced by renameWorkspacesInQENSFit().
setPropertyModeForWorkspaceProperty()
void MANTID_API_DLL Mantid::API::setPropertyModeForWorkspaceProperty (Mantid::Kernel::Property * prop, const PropertyMode::Type & optional)
Definition at line 39 of file WorkspacePropertyUtils.cpp.
References setPropertyModeForWorkspaceProperty().
Referenced by Mantid::API::Algorithm::setAlwaysStoreInADS(), and setPropertyModeForWorkspaceProperty().
Variable Documentation
COMMENT_ALG
const std::string Mantid::API::COMMENT_ALG = "Comment"
Definition at line 37 of file ScriptBuilder.cpp.
Referenced by Mantid::API::ScriptBuilder::buildAlgorithmString(), and Mantid::API::ScriptBuilder::buildCommentString().
EMPTY_EXPRESSION_NAME
const std::string Mantid::API::EMPTY_EXPRESSION_NAME = "EMPTY"
Definition at line 22 of file Expression.cpp.
Referenced by Mantid::API::Expression::setFunct().
g_log
Kernel::Logger Mantid::API::g_log("ExperimentInfo") ("ExperimentInfo")
static logger object
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::API::BatchAlgorithmRunner::addAlgorithm(), Mantid::CurveFitting::Algorithms::LeBailFunction::addBackgroundFunction(), MantidQt::MantidWidgets::FitDomain::addFunctionToExisting(), Mantid::CurveFitting::Algorithms::LeBailFunction::addPeaks(), Mantid::DataObjects::TimeSplitter::addROI(), Mantid::API::WorkspaceGroup::addWorkspace(), Mantid::API::AlgorithmFactoryImpl::AlgorithmFactoryImpl(), Mantid::API::AlgorithmManagerImpl::AlgorithmManagerImpl(), Mantid::API::ISISRunLogs::applyLogFiltering(), Mantid::API::FrameworkManagerImpl::asynchronousStartupTasks(), Mantid::DataObjects::SpecialWorkspace2D::binaryOperation(), Mantid::API::ScriptBuilder::buildAlgorithmString(), Mantid::API::ScriptBuilder::buildPropertyString(), Mantid::API::NotebookBuilder::buildPropertyString(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::cacheWorkspaceInfo(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::API::Run::calculateAverageGoniometerMatrix(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::calculateConvChainAndBestParameters(), Mantid::CurveFitting::Functions::CubicSpline::calculateDerivative(), Mantid::Crystal::ConnectedComponentLabeling::calculateDisjointTree(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculateGroupPeakIntensities(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculatePeaksIntensities(), Mantid::CurveFitting::Functions::CubicSpline::calculateSpline(), Mantid::CurveFitting::Functions::Bk2BkExpConvPV::calHandEta(), Mantid::CurveFitting::Algorithms::LeBailFunction::calPeak(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::calWavelengthAtEachDataPoint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::check(), Mantid::API::FrameworkManagerImpl::checkIfNewerVersionIsAvailable(), Mantid::Crystal::LoadIsawPeaks::checkNumberPeaks(), Mantid::DataHandling::LoadMuonNexusV2::chooseLoaderStrategy(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::compressEventsOutputWS(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::conjoinWorkspaces(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::constFunction(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::convergenceCheck(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::convertUnits(), Mantid::API::IFunction::convertValue(), Mantid::MDAlgorithms::ConvertToMD::copyMetaData(), Mantid::API::LiveListenerFactoryImpl::create(), Mantid::API::AlgorithmFactoryImpl::create(), Mantid::API::AlgorithmManagerImpl::create(), Mantid::API::WorkspaceFactoryImpl::create(), Mantid::API::TransformScaleFactoryImpl::create(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::createConstraintMatrices(), Mantid::API::SpectrumInfo::createDetectorIdLogMessages(), Mantid::ICat::ICat4Catalog::createMantidDataset(), Mantid::MDAlgorithms::ConvertToMD::createNewMDWorkspace(), Mantid::DataObjects::PeaksWorkspace::createPeakQSample(), Mantid::DataHandling::LoadEventNexus::createSpectraMapping(), Mantid::API::AlgorithmFactoryImpl::decodeName(), MantidQt::MantidWidgets::FitPropertyBrowser::defaultPeakType(), Mantid::API::FrameworkManagerImpl::deleteWorkspace(), Mantid::API::DeprecatedAlgorithm::deprecationMsg(), Mantid::WorkflowAlgorithms::LoadEventAndCompress::determineChunk(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::diffractionFocus(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::diffractionFocusRaggedRebinInDspace(), MantidQt::MantidWidgets::FitPropertyBrowser::doFit(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::editInstrument(), Mantid::MDAlgorithms::IntegrateQLabEvents::ellipseIntegrateEvents(), MantidQt::MantidWidgets::FitPropertyBrowser::enactAttributeChange(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), Mantid::CurveFitting::Functions::PseudoVoigt::estimate_parameter_value(), Mantid::Algorithms::FFTSmooth::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::MDAlgorithms::AccumulateMD::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::exec(), Mantid::MDAlgorithms::CutMD::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::WorkflowAlgorithms::ComputeSensitivity::exec(), Mantid::WorkflowAlgorithms::DgsReduction::exec(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::DataHandling::LoadNexusLogs::execLoader(), MantidQt::API::BatchAlgorithmRunner::executeAlgo(), MantidQt::MantidWidgets::MantidTreeModel::executeAlgorithmAsync(), Mantid::Crystal::ConnectedComponentLabeling::executeAndFetchClusters(), MantidQt::API::BatchAlgorithmRunner::executeBatchAsyncImpl(), Mantid::DataHandling::LoadNexusProcessed2::extractMappingInfoNew(), Mantid::DataHandling::LoadEventNexus::filterDuringPause(), Mantid::DataHandling::LoadEventNexus::filterEventsByTime(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::filterResonances(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::finalize(), Mantid::DataHandling::SampleEnvironmentSpecFileFinder::find(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::API::FileFinderImpl::findRun(), Mantid::API::FileFinderImpl::findRuns(), Mantid::CurveFitting::Algorithms::LeBailFunction::fixPeakParameter(), Mantid::API::FrameworkManagerImpl::FrameworkManagerImpl(), Mantid::CurveFitting::Algorithms::LeBailFunction::function(), Mantid::CurveFitting::Functions::Bk2BkExpConvPV::functionLocal(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionLocal(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::fwhm(), Mantid::CurveFitting::Functions::PseudoVoigt::get_parameter_to_calculate_from_set(), Mantid::DataHandling::ORNLDataArchive::getArchivePath(), Mantid::DataHandling::ISISDataArchive::getArchivePath(), Mantid::API::FileFinderImpl::getArchivePath(), Mantid::API::FileFinderImpl::getArchiveSearch(), Mantid::API::ExperimentInfo::getAvailableWorkspaceEndDate(), Mantid::API::ExperimentInfo::getAvailableWorkspaceStartDate(), Mantid::API::MatrixWorkspace::getDetector(), Mantid::API::MatrixWorkspace::getDetectorIDToWorkspaceIndexVector(), Mantid::API::SpectrumInfo::getDetectorValues(), Mantid::ICat::ICat4Catalog::getDownloadURL(), MantidQt::MantidWidgets::WorkspaceUtils::getEMode(), Mantid::API::FileFinderImpl::getExtension(), Mantid::API::ISISInstrumentDataCache::getFileParentDirectoryPath(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::getFilterROI(), MantidQt::MantidWidgets::FunctionTreeView::getFunction(), Mantid::API::GridDomain::getGrid(), MantidQt::MantidWidgets::SequentialFitDialog::getIndex(), Mantid::API::FileFinderImpl::getInstrument(), Mantid::API::InstrumentFileFinder::getInstrumentFilename(), Mantid::ICat::ICat4Catalog::getMantidDatasetId(), Mantid::ICat::ICat4Catalog::getNumberOfSearchResults(), Mantid::API::ParamFunction::getParameter(), Mantid::API::InstrumentFileFinder::getParameterPath(), Mantid::DataHandling::ISISDataArchive::getPath(), Mantid::API::FileFinderImpl::getPath(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeak(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakMaximumValue(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakParameter(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakParameter(), Mantid::API::Run::getProtonCharge(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::getResidualVariance(), Mantid::API::InstrumentFileFinder::getResourceFilenames(), Mantid::API::MatrixWorkspace::getSpectrumToWorkspaceIndexMap(), Mantid::ICat::ICat4Catalog::getUploadURL(), Mantid::DataObjects::SpecialWorkspace2D::getValue(), Mantid::API::ExperimentInfo::getWorkspaceStartDate(), Mantid::CurveFitting::Algorithms::LeBailFunction::groupPeaks(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::info(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::init(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::init(), Mantid::CurveFitting::MultiDomainCreator::initFunction(), Mantid::CurveFitting::Constraints::BoundaryConstraint::initialize(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::initSimulatedAnnealing(), Mantid::API::Run::integrateProtonCharge(), Mantid::DataObjects::SpecialWorkspace2D::isCompatible(), Mantid::API::WorkspaceGroup::isMultiperiod(), Mantid::CurveFitting::Algorithms::LeBailFunction::isParameterValid(), MantidQt::MantidWidgets::FitDomain::isParameterValueWithinConstraints(), Mantid::API::WorkspaceProperty< TYPE >::isValidGroup(), MantidQt::MantidWidgets::FitDomain::isValidParameterConstraint(), Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate(), Mantid::CurveFitting::FuncMinimisers::DampedGaussNewtonMinimizer::iterate(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::jumpUpdate(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::loadCalFile(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::loadCalFile(), Mantid::WorkflowAlgorithms::LoadEventAndCompress::loadChunk(), Mantid::API::ExperimentInfo::loadEmbeddedInstrumentInfoNexus(), Mantid::DataHandling::LoadCanSAS1D2::loadEntry(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataObjects::MDBoxFlatTree::loadExperimentInfos(), Mantid::DataObjects::MDBoxFlatTree::loadExperimentInfos(), Mantid::DataHandling::Mantid3MFFileIO::LoadFile(), Mantid::WorkflowAlgorithms::DgsReduction::loadGroupingFile(), Mantid::WorkflowAlgorithms::DgsReduction::loadInputData(), Mantid::API::ExperimentInfo::loadInstrumentParametersNexus(), Mantid::API::ExperimentInfo::loadInstrumentXML(), Mantid::DataHandling::LoadEventNexus::loadISISVMSSpectraMapping(), Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::API::WorkspaceHistory::loadNestedHistory(), Mantid::API::WorkspaceHistory::loadNexus(), Mantid::DataHandling::LoadNexusLogs::loadNPeriods(), Mantid::DataHandling::LoadNexusLogs::loadNXLog(), Mantid::API::FrameworkManagerImpl::loadPluginsUsingKey(), Mantid::DataHandling::LoadNexusLogs::loadSELog(), Mantid::DataHandling::LoadSingleMesh::LoadSingleMesh(), Mantid::API::ISISInstrumentDataCache::makeIndexFilePath(), Mantid::API::ISISInstrumentDataCache::openCacheJsonFile(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputConvergedChains(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputCostFunctionTable(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputPDF(), Mantid::API::WorkspaceHistory::parseAlgorithmHistory(), Mantid::DataObjects::PeakColumn< T >::PeakColumn(), Mantid::ICat::ICat4Catalog::performSearch(), MantidQt::MantidWidgets::FitPropertyBrowser::populateFunctionNames(), Mantid::API::ExperimentInfo::populateInstrumentParameters(), Mantid::API::WorkspaceGroup::print(), Mantid::DataObjects::PeakColumn< T >::read(), Mantid::DataObjects::PeakColumn< T >::read(), Mantid::Nexus::H5Util::readArray1DCoerce(), Mantid::Nexus::H5Util::readArray1DCoerce(), Mantid::DataHandling::LoadMcStas::readEventData(), Mantid::DataHandling::LoadMcStas::readHistogramData(), Mantid::API::ExperimentInfo::readParameterMap(), Mantid::DataHandling::LoadNexusProcessed2::readSpectraToDetectorMapping(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::rebin(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::rebinRagged(), Mantid::DataHandling::LoadHelper::recurseAndAddNexusFieldsToWsRun(), Mantid::API::AlgorithmManagerImpl::removeById(), Mantid::DataObjects::TableWorkspace::removeColumn(), Mantid::DataObjects::SplittersWorkspace::removeSplitter(), Mantid::API::WorkspaceGroup::reorderMembersWithIndices(), Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree(), Mantid::DataHandling::LoadEventNexus::runLoadMonitors(), Mantid::DataObjects::MDBoxFlatTree::saveAffineTransformMatrix(), Mantid::DataObjects::MDBoxFlatTree::saveExperimentInfos(), Mantid::API::LogManager::saveNexus(), Mantid::API::DetectorSearcher::searchUsingNearestNeighbours(), Mantid::DataHandling::ISISDataArchive::sendRequest(), Mantid::CurveFitting::ParameterEstimator::setBackToBackExponential(), Mantid::API::LogarithmScale::setBase(), Mantid::API::IFunction::setConstraintPenaltyFactor(), Mantid::CurveFitting::Algorithms::LeBailFunction::setFitProfileParameter(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setFixedParameterValues(), Mantid::CurveFitting::Functions::PseudoVoigt::setHeight(), Mantid::API::ExperimentInfo::setInstumentFromXML(), MantidQt::MantidWidgets::FunctionModel::setLocalParameterConstraint(), MantidQt::MantidWidgets::FunctionModel::setLocalParameterTie(), Mantid::DataHandling::Mantid3MFFileIO::setMaterialOnObject(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setMatrixWorkspace(), Mantid::API::IFunction::setMatrixWorkspace(), Mantid::DataHandling::EventWorkspaceCollection::setNPeriods(), Mantid::API::FrameworkManagerImpl::setNumOMPThreads(), Mantid::CurveFitting::Functions::PseudoVoigt::setParameter(), Mantid::CurveFitting::Functions::PseudoVoigt::setParameter(), MantidQt::MantidWidgets::FitDomain::setParameterTie(), Mantid::CurveFitting::Constraints::BoundaryConstraint::setParamToSatisfyConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::setPenaltyFactor(), Mantid::API::Column::setPlotType(), Mantid::CurveFitting::Algorithms::LeBailFunction::setProfileParameterValues(), MantidQt::API::BatchAlgorithmRunner::setQueue(), Mantid::DataHandling::LoadEventNexus::setTopEntryName(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::setUnitsInfo(), Mantid::Crystal::SCDPanelErrors::setupData(), Mantid::API::CompositeFunction::setUpForFit(), Mantid::CurveFitting::Functions::CubicSpline::setupInput(), Mantid::API::MultipleFileProperty::setValue(), Mantid::API::MultipleFileProperty::setValueAsMultipleFiles(), Mantid::API::MultipleFileProperty::setValueAsSingleFile(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::shouldCompressUnfocused(), MantidQt::MantidWidgets::MantidTreeModel::showAlgorithmDialog(), Mantid::MDAlgorithms::CreateMD::single_run(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::API::FileFinderImpl::toInstrumentAndNumber(), Mantid::API::LogarithmScale::transform(), Mantid::API::AlgorithmFactoryImpl::unsubscribe(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::updateCMatrixValues(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateGlobalParameterTie(), MantidQt::MantidWidgets::InstrumentSelector::updateInstrument(), Mantid::API::FrameworkManagerImpl::updateInstrumentDefinitions(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateLocalParameterTie(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterTie(), Mantid::API::MatrixWorkspace::updateSpectraUsing(), Mantid::DataHandling::LoadEventNexus::validateInputs(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::validateInputs(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedAttribute(), Mantid::API::WorkspaceFactoryImpl::WorkspaceFactoryImpl(), and Mantid::DataHandling::Mantid3MFFileIO::writeMeshObject().
MDMaskValue
const signal_t Mantid::API::MDMaskValue = std::numeric_limits<double>::quiet_NaN() static
Definition at line 25 of file IMDWorkspace.h.
Referenced by Mantid::DataObjects::MDHistoWorkspace::getSignalWithMaskAtCoord(), and Mantid::DataObjects::MDHistoWorkspace::setMDMaskAt().