Mantid: Mantid::MDAlgorithms::LoadGaussCube Class Reference
Mantid::MDAlgorithms::LoadGaussCube Class Reference
LoadGaussCube : TODO: DESCRIPTION.
#include <LoadGaussCube.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
std::map< std::string, std::string > validateInputs () override
Validate input.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
void exec () override
Execute the algorithm.
void init () override
Initialize the algorithm's properties.
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
LoadGaussCube : TODO: DESCRIPTION.
Definition at line 17 of file LoadGaussCube.h.
Member Function Documentation
category()
const std::string Mantid::MDAlgorithms::LoadGaussCube::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 37 of file LoadGaussCube.cpp.
exec()
void Mantid::MDAlgorithms::LoadGaussCube::exec () override private
Execute the algorithm.
Definition at line 87 of file LoadGaussCube.cpp.
References error, Mantid::API::Algorithm::execute(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue(), Mantid::Kernel::Strings::getWord(), Mantid::API::Algorithm::initialize(), Mantid::MDAlgorithms::parseNames(), Mantid::Kernel::Strings::readToEndOfLine(), Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::API::Algorithm::setPropertyValue().
init()
void Mantid::MDAlgorithms::LoadGaussCube::init () override private
Initialize the algorithm's properties.
Definition at line 47 of file LoadGaussCube.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::copyProperty(), Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::MDAlgorithms::LoadGaussCube::name () const override
Algorithms name for identification.
See also
Algorithm::name
Definition at line 31 of file LoadGaussCube.cpp.
Referenced by validateInputs().
summary()
const std::string Mantid::MDAlgorithms::LoadGaussCube::summary () const override
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Definition at line 40 of file LoadGaussCube.cpp.
validateInputs()
std::map< std::string, std::string > Mantid::MDAlgorithms::LoadGaussCube::validateInputs () override
Validate input.
Definition at line 66 of file LoadGaussCube.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), name(), and Mantid::MDAlgorithms::parseNames().
version()
int Mantid::MDAlgorithms::LoadGaussCube::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 34 of file LoadGaussCube.cpp.
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadGaussCube.h
Framework/MDAlgorithms/src/LoadGaussCube.cpp