Mantid: Mantid::DataHandling::ANSTO::EventCounter Class Reference
Mantid::DataHandling::ANSTO::EventCounter Class Reference
#include <LoadANSTOHelper.h>
Public Member Functions
EventCounter (const std::vector< bool > &roi, const size_t stride, const double period, const double phase, const int64_t startTime, const double tofMinBoundary, const double tofMaxBoundary, const double timeMinBoundary, const double timeMaxBoundary, std::vector< size_t > &eventCounts)
size_t numFrames () const
double tofMax () const
double tofMin () const
Public Member Functions inherited from Mantid::DataHandling::ANSTO::EventProcessor
void addEvent (size_t x, size_t y, double tof)
EventProcessor (const std::vector< bool > &roi, size_t stride, const double period, const double phase, const int64_t startTime, const double tofMinBoundary, const double tofMaxBoundary, const double timeMinBoundary, const double timeMaxBoundary)
void newFrame ()
Protected Member Functions
void addEventImpl (size_t id, int64_t pulse, double tof) override
Protected Member Functions inherited from Mantid::DataHandling::ANSTO::EventProcessor
bool validFrame () const
Protected Attributes
std::vector< size_t > & m_eventCounts
double m_tofMax
double m_tofMin
Protected Attributes inherited from Mantid::DataHandling::ANSTO::EventProcessor
size_t m_frames
size_t m_framesValid
const double m_period
const double m_phase
const std::vector< bool > & m_roi
int64_t m_startTime
const size_t m_stride
const double m_timeMaxBoundary
const double m_timeMinBoundary
const double m_tofMaxBoundary
const double m_tofMinBoundary
Detailed Description
Definition at line 96 of file LoadANSTOHelper.h.
Constructor & Destructor Documentation
EventCounter()
Mantid::DataHandling::ANSTO::EventCounter::EventCounter (const std::vector< bool > & roi, const size_t stride, const double period, const double phase, const int64_t startTime, const double tofMinBoundary, const double tofMaxBoundary, const double timeMinBoundary, const double timeMaxBoundary, std::vector< size_t > & eventCounts)
Definition at line 136 of file LoadANSTOHelper.cpp.
Member Function Documentation
addEventImpl()
void Mantid::DataHandling::ANSTO::EventCounter::addEventImpl (size_t id, int64_t pulse, double tof) override protected virtual
Implements Mantid::DataHandling::ANSTO::EventProcessor.
Definition at line 146 of file LoadANSTOHelper.cpp.
References m_eventCounts, m_tofMax, m_tofMin, and UNUSED_ARG.
numFrames()
size_t Mantid::DataHandling::ANSTO::EventCounter::numFrames () const
Definition at line 143 of file LoadANSTOHelper.cpp.
References Mantid::DataHandling::ANSTO::EventProcessor::m_framesValid.
Referenced by Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY2::exec().
tofMax()
double Mantid::DataHandling::ANSTO::EventCounter::tofMax () const
Definition at line 145 of file LoadANSTOHelper.cpp.
References m_tofMax, and m_tofMin.
Referenced by Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY2::exec().
tofMin()
double Mantid::DataHandling::ANSTO::EventCounter::tofMin () const
Definition at line 144 of file LoadANSTOHelper.cpp.
References m_tofMax, and m_tofMin.
Referenced by Mantid::DataHandling::LoadBBY::exec(), and Mantid::DataHandling::LoadBBY2::exec().
Member Data Documentation
m_eventCounts
std::vector<size_t>& Mantid::DataHandling::ANSTO::EventCounter::m_eventCounts protected
Definition at line 99 of file LoadANSTOHelper.h.
Referenced by addEventImpl().
m_tofMax
double Mantid::DataHandling::ANSTO::EventCounter::m_tofMax protected
Definition at line 102 of file LoadANSTOHelper.h.
Referenced by addEventImpl(), tofMax(), and tofMin().
m_tofMin
double Mantid::DataHandling::ANSTO::EventCounter::m_tofMin protected
Definition at line 101 of file LoadANSTOHelper.h.
Referenced by addEventImpl(), tofMax(), and tofMin().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadANSTOHelper.h
Framework/DataHandling/src/LoadANSTOHelper.cpp