Mantid: ICat4::ns1__getApiVersionResponse Class Reference
ICat4::ns1__getApiVersionResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__getApiVersionResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 713 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__getApiVersionResponse()
ICat4::ns1__getApiVersionResponse::ns1__getApiVersionResponse () inline
Definition at line 729 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__getApiVersionResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19956 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::ICATPortBindingProxy::getApiVersion(), ICat4::soap_in_ns1__getApiVersionResponse(), ICat4::soap_new_req_ns1__getApiVersionResponse(), and ICat4::soap_new_set_ns1__getApiVersionResponse().
soap_get()
void * ICat4::ns1__getApiVersionResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20050 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__getApiVersionResponse().
Referenced by ICat4::ICATPortBindingProxy::getApiVersion().
soap_in()
void * ICat4::ns1__getApiVersionResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19985 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__getApiVersionResponse().
Referenced by ICat4::soap_in_ns1__getApiVersionResponse().
soap_out()
int ICat4::ns1__getApiVersionResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19970 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__getApiVersionResponse().
Referenced by soap_put().
soap_put()
int ICat4::ns1__getApiVersionResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20043 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__getApiVersionResponse.
soap_serialize()
void ICat4::ns1__getApiVersionResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19962 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__getApiVersion().
soap_type()
int ICat4::ns1__getApiVersionResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 722 of file ICat4Stub.h.
Member Data Documentation
return_
std::string* ICat4::ns1__getApiVersionResponse::return_
Definition at line 715 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp