Mantid: ICat4::ns1__createMany Class Reference
ICat4::ns1__createMany Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__createMany ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< class ns1__entityBaseBean * > beans
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 389 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__createMany()
ICat4::ns1__createMany::ns1__createMany () inline
Definition at line 401 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__createMany::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23052 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__entityBaseBean().
Referenced by ICat4::soap_in_ns1__createMany(), ICat4::soap_new_req_ns1__createMany(), and ICat4::soap_new_set_ns1__createMany().
soap_get()
void * ICat4::ns1__createMany::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23151 of file ICat4C.cpp.
References ICat4::soap_get_ns1__createMany().
soap_in()
void * ICat4::ns1__createMany::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23085 of file ICat4C.cpp.
References ICat4::soap_in_ns1__createMany().
Referenced by ICat4::soap_in_ns1__createMany().
soap_out()
int ICat4::ns1__createMany::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23068 of file ICat4C.cpp.
References ICat4::soap_out_ns1__createMany().
soap_put()
int ICat4::ns1__createMany::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23144 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__createMany.
soap_serialize()
void ICat4::ns1__createMany::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23059 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__entityBaseBean().
soap_type()
int ICat4::ns1__createMany::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 394 of file ICat4Stub.h.
Member Data Documentation
beans
std::vector<class ns1__entityBaseBean *> ICat4::ns1__createMany::beans
Definition at line 392 of file ICat4Stub.h.
sessionId
std::string* ICat4::ns1__createMany::sessionId
Definition at line 391 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp