Mantid: Mantid::Geometry::MDFrame Class Reference
Mantid::Geometry::MDFrame Class Reference abstract
MDFrame : The coordinate frame for a dimension, or set of dimensions in a multidimensional workspace.
#include <MDFrame.h>
Public Member Functions
virtual bool canConvertTo (const Mantid::Kernel::MDUnit &otherUnit) const =0
virtual MDFrame * clone () const =0
virtual Mantid::Kernel::SpecialCoordinateSystem equivalientSpecialCoordinateSystem () const =0
virtual const Mantid::Kernel::MDUnit & getMDUnit () const =0
virtual Mantid::Kernel::UnitLabel getUnitLabel () const =0
virtual bool isQ () const =0
virtual bool isSameType (const MDFrame &frame) const =0
virtual std::string name () const =0
virtual bool setMDUnit (const Mantid::Kernel::MDUnit &newUnit)=0
virtual ~MDFrame ()=default
Detailed Description
MDFrame : The coordinate frame for a dimension, or set of dimensions in a multidimensional workspace.
Definition at line 22 of file MDFrame.h.
Constructor & Destructor Documentation
~MDFrame()
virtual Mantid::Geometry::MDFrame::~MDFrame () virtual default
Member Function Documentation
canConvertTo()
virtual bool Mantid::Geometry::MDFrame::canConvertTo (const Mantid::Kernel::MDUnit & otherUnit) const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QSample, Mantid::Geometry::QLab, and Mantid::Geometry::UnknownFrame.
clone()
virtual MDFrame * Mantid::Geometry::MDFrame::clone () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
Referenced by Mantid::Geometry::MDHistoDimension::setMDFrame().
equivalientSpecialCoordinateSystem()
virtual Mantid::Kernel::SpecialCoordinateSystem Mantid::Geometry::MDFrame::equivalientSpecialCoordinateSystem () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
getMDUnit()
virtual const Mantid::Kernel::MDUnit & Mantid::Geometry::MDFrame::getMDUnit () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
getUnitLabel()
virtual Mantid::Kernel::UnitLabel Mantid::Geometry::MDFrame::getUnitLabel () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
Referenced by Mantid::MDAlgorithms::SetMDFrame::createMDFrame(), and export_MDFrame().
isQ()
virtual bool Mantid::Geometry::MDFrame::isQ () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
Referenced by export_MDFrame().
isSameType()
virtual bool Mantid::Geometry::MDFrame::isSameType (const MDFrame & frame) const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
name()
virtual std::string Mantid::Geometry::MDFrame::name () const pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
Referenced by export_MDFrame().
setMDUnit()
virtual bool Mantid::Geometry::MDFrame::setMDUnit (const Mantid::Kernel::MDUnit & newUnit) pure virtual
Implemented in Mantid::Geometry::GeneralFrame, Mantid::Geometry::HKL, Mantid::Geometry::QLab, Mantid::Geometry::QSample, and Mantid::Geometry::UnknownFrame.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDFrame.h