Mantid: Mantid::Kernel::EnvironmentHistory Class Reference
Mantid::Kernel::EnvironmentHistory Class Reference
This class stores information about the Environment of the computer used by the framework.
#include <EnvironmentHistory.h>
Public Member Functions
std::string frameworkVersion () const
returns the framework version
std::string osName () const
returns the os name
std::string osVersion () const
returns the os version
void printSelf (std::ostream &, const int indent=0) const
print contents of object
Detailed Description
This class stores information about the Environment of the computer used by the framework.
Author
Dickon Champion, ISIS, RAL
Date
21/01/2008
Definition at line 24 of file EnvironmentHistory.h.
Member Function Documentation
frameworkVersion()
std::string Mantid::Kernel::EnvironmentHistory::frameworkVersion () const
returns the framework version
Returns the framework version.
Returns
A string containing the Mantid version
Definition at line 21 of file EnvironmentHistory.cpp.
References Mantid::Kernel::MantidVersion::version().
Referenced by AlgEnvHistoryGrpBox::fillEnvHistoryGroupBox(), and printSelf().
osName()
std::string Mantid::Kernel::EnvironmentHistory::osName () const
returns the os name
Returns the OS name.
Returns
A string containing the OS name
Definition at line 26 of file EnvironmentHistory.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by AlgEnvHistoryGrpBox::fillEnvHistoryGroupBox(), and printSelf().
osVersion()
std::string Mantid::Kernel::EnvironmentHistory::osVersion () const
returns the os version
Returns the OS version.
Returns
A string containing the OS version
Definition at line 31 of file EnvironmentHistory.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by AlgEnvHistoryGrpBox::fillEnvHistoryGroupBox(), and printSelf().
printSelf()
void Mantid::Kernel::EnvironmentHistory::printSelf (std::ostream & os, const int indent = 0) const
print contents of object
Prints a text representation of itself.
Parameters
os :: The ouput stream to write to
indent :: an indentation value to make pretty printing of object and sub-objects
Definition at line 38 of file EnvironmentHistory.cpp.
References frameworkVersion(), osName(), and osVersion().
Referenced by Mantid::Kernel::operator<<(), and Mantid::API::WorkspaceHistory::printSelf().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/EnvironmentHistory.h
Framework/Kernel/src/EnvironmentHistory.cpp