Mantid: qt/widgets/common/src/RepoModel.cpp File Reference
RepoModel.cpp File Reference
#include "MantidQtWidgets/Common/RepoModel.h"
#include "MantidAPI/ScriptRepositoryFactory.h"
#include <utility>
#include <vector>
#include "MantidKernel/ConfigService.h"
#include "MantidKernel/Logger.h"
#include "MantidQtIcons/Icon.h"
#include <QIcon>
#include <QPixmap>
#include <QCheckBox>
#include <QDebug>
#include <QDialogButtonBox>
#include <QFormLayout>
#include <QGridLayout>
#include <QGroupBox>
#include <QLabel>
#include <QLineEdit>
#include <QSettings>
#include <QTextEdit>
#include <QTextStream>
#include <QVBoxLayout>
#include <QtConcurrentRun>
#include <stdexcept>
Functions
static QString delete_thread (Mantid::API::ScriptRepository_sptr &pt, const std::string &path, const QString &email, const QString &author, const QString &comment)
Execute the remove from ScriptRepository.
static QString download_thread (Mantid::API::ScriptRepository_sptr &pt, const std::string &path)
Executes the download from ScriptRepository.
static QString upload_thread (Mantid::API::ScriptRepository_sptr &pt, const std::string &path, const QString &email, const QString &author, const QString &comment)
Execute the upload from ScriptRepository.
Variables
const char * delete_mark = "*DELETE*"
const char * nofile_flag = "nofile"
Function Documentation
delete_thread()
static QString delete_thread (Mantid::API::ScriptRepository_sptr & pt, const std::string & path, const QString & email, const QString & author, const QString & comment) static
Execute the remove from ScriptRepository.
This function will be executed in a separate thread.
Definition at line 77 of file RepoModel.cpp.
References delete_mark, and Mantid::API::ScriptRepoException::what().
Referenced by MantidQt::API::RepoModel::setData().
download_thread()
static QString download_thread (Mantid::API::ScriptRepository_sptr & pt, const std::string & path) static
Executes the download from ScriptRepository.
This function will be executed in a separate thread
Definition at line 49 of file RepoModel.cpp.
References Mantid::API::ScriptRepoException::what().
Referenced by MantidQt::API::RepoModel::setData().
upload_thread()
static QString upload_thread (Mantid::API::ScriptRepository_sptr & pt, const std::string & path, const QString & email, const QString & author, const QString & comment) static
Execute the upload from ScriptRepository.
This function will be executed in a separate thread
Definition at line 64 of file RepoModel.cpp.
References Mantid::API::ScriptRepoException::what().
Referenced by MantidQt::API::RepoModel::setData().
Variable Documentation
delete_mark
const char* delete_mark = "*DELETE*"
Definition at line 44 of file RepoModel.cpp.
Referenced by delete_thread(), and MantidQt::API::RepoModel::uploadFinished().
nofile_flag
const char* nofile_flag = "nofile"
Definition at line 45 of file RepoModel.cpp.
Referenced by MantidQt::API::RepoModel::downloadFinished(), MantidQt::API::RepoModel::RepoModel(), and MantidQt::API::RepoModel::uploadFinished().