Mantid: Mantid::Kernel::Spline< X, Y > Class Template Reference
Mantid::Kernel::Spline< X, Y > Class Template Reference
Generic spline interpolation base class.
#include <Spline.h>
Public Member Functions
std::vector< Y > deriv (std::span< X const > newX, unsigned int order=1) const
Y deriv (X const newX, unsigned int order=1) const
std::vector< Y > operator() (std::span< X const > newX) const
Y operator() (X const newX) const
Spline (std::span< X const > x, std::span< Y const > y, gsl_interp_type const *type)
virtual ~Spline ()=default
Private Member Functions
Spline & operator= (Spline &&)=delete
Spline & operator= (Spline const &)=delete
Spline (Spline &&)=delete
Spline (Spline const &)=delete
Private Attributes
spline::accel_uptr m_acc
spline::spline_uptr m_spline
Detailed Description
template<typename X, typename Y>
class Mantid::Kernel::Spline< X, Y >
Generic spline interpolation base class.
Template Parameters
X Type for x-coordinates (must be numeric)
Y Type for y-coordinates (must be numeric)
Definition at line 21 of file Spline.h.
Constructor & Destructor Documentation
Spline() [1/3]
template<typename X , typename Y > Mantid::Kernel::Spline< X, Y >::Spline (Spline< X, Y > const &) private delete
Spline() [2/3]
template<typename X , typename Y > Mantid::Kernel::Spline< X, Y >::Spline (Spline< X, Y > &&) private delete
Spline() [3/3]
template<typename X , typename Y > Mantid::Kernel::Spline< X, Y >::Spline (std::span< X const > x, std::span< Y const > y, gsl_interp_type const * type) inline
Definition at line 33 of file Spline.h.
~Spline()
template<typename X , typename Y > virtual Mantid::Kernel::Spline< X, Y >::~Spline () virtual default
Member Function Documentation
deriv() [1/2]
template<typename X , typename Y > std::vector< Y > Mantid::Kernel::Spline< X, Y >::deriv (std::span< X const > newX, unsigned int order = 1) const inline
Definition at line 67 of file Spline.h.
References Mantid::Geometry::X, and Mantid::Geometry::x.
deriv() [2/2]
template<typename X , typename Y > Y Mantid::Kernel::Spline< X, Y >::deriv (X const newX, unsigned int order = 1) const inline
Definition at line 50 of file Spline.h.
References Mantid::Kernel::Spline< X, Y >::deriv(), Mantid::Kernel::Spline< X, Y >::m_acc, Mantid::Kernel::Spline< X, Y >::m_spline, std::to_string(), and Mantid::Geometry::Y.
Referenced by Mantid::Kernel::Spline< X, Y >::deriv().
operator()() [1/2]
template<typename X , typename Y > std::vector< Y > Mantid::Kernel::Spline< X, Y >::operator() (std::span< X const > newX) const inline
Definition at line 44 of file Spline.h.
References Mantid::Geometry::X, and Mantid::Geometry::x.
operator()() [2/2]
template<typename X , typename Y > Y Mantid::Kernel::Spline< X, Y >::operator() (X const newX) const inline
Definition at line 36 of file Spline.h.
References Mantid::Kernel::Spline< X, Y >::m_acc, Mantid::Kernel::Spline< X, Y >::m_spline, std::to_string(), Mantid::Geometry::Y, and Mantid::Geometry::y.
operator=() [1/2]
template<typename X , typename Y > Spline & Mantid::Kernel::Spline< X, Y >::operator= (Spline< X, Y > &&) private delete
operator=() [2/2]
template<typename X , typename Y > Spline & Mantid::Kernel::Spline< X, Y >::operator= (Spline< X, Y > const &) private delete
Member Data Documentation
m_acc
template<typename X , typename Y > spline::accel_uptr Mantid::Kernel::Spline< X, Y >::m_acc private
Definition at line 26 of file Spline.h.
Referenced by Mantid::Kernel::Spline< X, Y >::deriv(), and Mantid::Kernel::Spline< X, Y >::operator()().
m_spline
template<typename X , typename Y > spline::spline_uptr Mantid::Kernel::Spline< X, Y >::m_spline private
Definition at line 25 of file Spline.h.
Referenced by Mantid::Kernel::Spline< X, Y >::deriv(), and Mantid::Kernel::Spline< X, Y >::operator()().
The documentation for this class was generated from the following file:
Framework/Kernel/inc/MantidKernel/Spline.h