Mantid: Mantid::Geometry::IPeak Class Reference
Mantid::Geometry::IPeak Class Reference abstract
Structure describing a single-crystal peak.
#include <IPeak.h>
Public Member Functions
virtual double getAbsorptionWeightedPathLength () const =0
virtual double getAzimuthal () const =0
virtual double getBinCount () const =0
virtual int getCol () const =0
virtual Mantid::Kernel::V3D getDetectorDirectionSampleFrame () const =0
virtual int getDetectorID () const =0
virtual double getDSpacing () const =0
virtual double getEnergyTransfer () const =0
virtual double getFinalEnergy () const =0
virtual Mantid::Kernel::Matrix< double > getGoniometerMatrix () const =0
virtual double getH () const =0
virtual Mantid::Kernel::V3D getHKL () const =0
virtual double getInitialEnergy () const =0
virtual double getIntensity () const =0
virtual double getIntensityOverSigma () const =0
virtual Mantid::Kernel::V3D getIntHKL () const =0
virtual Mantid::Kernel::V3D getIntMNP () const =0
virtual double getK () const =0
virtual double getL () const =0
virtual double getL1 () const =0
virtual double getL2 () const =0
virtual double getMonitorCount () const =0
virtual int getPeakNumber () const =0
virtual const Mantid::Geometry::PeakShape & getPeakShape () const =0
virtual Mantid::Kernel::V3D getQLabFrame () const =0
virtual Mantid::Kernel::V3D getQSampleFrame () const =0
virtual std::shared_ptr< const Geometry::ReferenceFrame > getReferenceFrame () const =0
virtual int getRow () const =0
virtual int getRunNumber () const =0
virtual Mantid::Kernel::V3D getSamplePos () const =0
virtual double getScattering () const =0
virtual double getSigmaIntensity () const =0
virtual Mantid::Kernel::V3D getSourceDirectionSampleFrame () const =0
virtual double getTOF () const =0
virtual double getWavelength () const =0
virtual bool isIndexed () const =0
virtual void setAbsorptionWeightedPathLength (double pathLength)=0
virtual void setBinCount (double m_BinCount)=0
virtual void setFinalEnergy (double m_FinalEnergy)=0
virtual void setGoniometerMatrix (const Mantid::Kernel::Matrix< double > &m_GoniometerMatrix)=0
virtual void setH (double m_H)=0
virtual void setHKL (const Mantid::Kernel::V3D &HKL)=0
virtual void setHKL (double H, double K, double L)=0
virtual void setInitialEnergy (double m_InitialEnergy)=0
virtual void setIntensity (double m_Intensity)=0
virtual void setIntHKL (const Mantid::Kernel::V3D &HKL)=0
virtual void setIntMNP (const Mantid::Kernel::V3D &MNP)=0
virtual void setK (double m_K)=0
virtual void setL (double m_L)=0
virtual void setMonitorCount (double m_MonitorCount)=0
virtual void setPeakNumber (int m_PeakNumber)=0
virtual void setPeakShape (Mantid::Geometry::PeakShape *shape)=0
virtual void setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape)=0
virtual void setQLabFrame (const Mantid::Kernel::V3D &QLabFrame, std::optional< double > detectorDistance)=0
virtual void setQSampleFrame (const Mantid::Kernel::V3D &QSampleFrame, std::optional< double > detectorDistance)=0
virtual void setRunNumber (int m_RunNumber)=0
virtual void setSamplePos (const Mantid::Kernel::V3D &XYZ)=0
virtual void setSamplePos (double samX, double samY, double samZ)=0
virtual void setSigmaIntensity (double m_SigmaIntensity)=0
virtual void setWavelength (double wavelength)=0
virtual ~IPeak ()=default
Detailed Description
Structure describing a single-crystal peak.
Author
Janik Zikovsky
Date
2011-04-15 13:24:07.963491
Definition at line 26 of file IPeak.h.
Constructor & Destructor Documentation
~IPeak()
virtual Mantid::Geometry::IPeak::~IPeak () virtual default
Member Function Documentation
getAbsorptionWeightedPathLength()
virtual double Mantid::Geometry::IPeak::getAbsorptionWeightedPathLength () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getAzimuthal()
virtual double Mantid::Geometry::IPeak::getAzimuthal () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getBinCount()
virtual double Mantid::Geometry::IPeak::getBinCount () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getCol()
virtual int Mantid::Geometry::IPeak::getCol () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getDetectorDirectionSampleFrame()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getDetectorDirectionSampleFrame () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getDetectorID()
virtual int Mantid::Geometry::IPeak::getDetectorID () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getDSpacing()
virtual double Mantid::Geometry::IPeak::getDSpacing () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::CurveFitting::LatticeDomainCreator::createDomainFromPeaksWorkspace(), export_IPeak(), and Mantid::DataObjects::BasePeak::getValueByColName().
getEnergyTransfer()
virtual double Mantid::Geometry::IPeak::getEnergyTransfer () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getFinalEnergy()
virtual double Mantid::Geometry::IPeak::getFinalEnergy () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getGoniometerMatrix()
virtual Mantid::Kernel::Matrix< double > Mantid::Geometry::IPeak::getGoniometerMatrix () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PredictPeaks::exec(), and export_IPeak().
getH()
virtual double Mantid::Geometry::IPeak::getH () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::CalculateUMatrix::exec(), export_IPeak(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
getHKL()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getHKL () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), Mantid::CurveFitting::LatticeDomainCreator::createDomainFromPeaksWorkspace(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::TransformHKL::exec(), export_IPeak(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingPeaksWorkspace(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Crystal::PeakBackground::PeakBackground(), and Mantid::Geometry::PeakTransformHKL::transformPeak().
getInitialEnergy()
virtual double Mantid::Geometry::IPeak::getInitialEnergy () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak(), and Mantid::DataObjects::BasePeak::getValueByColName().
getIntensity()
virtual double Mantid::Geometry::IPeak::getIntensity () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::PeakIntensityVsRadius::exec(), and export_IPeak().
getIntensityOverSigma()
virtual double Mantid::Geometry::IPeak::getIntensityOverSigma () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getIntHKL()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getIntHKL () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::TransformHKL::exec(), export_IPeak(), and Mantid::Crystal::FindUBUsingIndexedPeaks::isPeakIndexed().
getIntMNP()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getIntMNP () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::SelectCellWithForm::ApplyTransform(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::TransformHKL::exec(), export_IPeak(), and Mantid::Crystal::FindUBUsingIndexedPeaks::isPeakIndexed().
getK()
virtual double Mantid::Geometry::IPeak::getK () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::CalculateUMatrix::exec(), export_IPeak(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
getL()
virtual double Mantid::Geometry::IPeak::getL () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::CalculateUMatrix::exec(), export_IPeak(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
getL1()
virtual double Mantid::Geometry::IPeak::getL1 () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak(), and Mantid::Crystal::PeakHKLErrors::functionDeriv1D().
getL2()
virtual double Mantid::Geometry::IPeak::getL2 () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), and Mantid::MDAlgorithms::CentroidPeaksMD2::integrate().
getMonitorCount()
virtual double Mantid::Geometry::IPeak::getMonitorCount () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getPeakNumber()
virtual int Mantid::Geometry::IPeak::getPeakNumber () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getPeakShape()
virtual const Mantid::Geometry::PeakShape & Mantid::Geometry::IPeak::getPeakShape () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
getQLabFrame()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getQLabFrame () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::Crystal::IntegratePeakTimeSlices::CalculateTimeChannelSpan(), Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), export_IPeak(), Mantid::DataObjects::BasePeak::getValueByColName(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Crystal::PeakBackground::PeakBackground(), and Mantid::Geometry::PeakTransformQLab::transformPeak().
getQSampleFrame()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getQSampleFrame () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::Crystal::SelectCellWithForm::ApplyTransform(), Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::CalculateUMatrix::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::TransformHKL::exec(), export_IPeak(), Mantid::DataObjects::BasePeak::getValueByColName(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Crystal::PeakBackground::PeakBackground(), and Mantid::Geometry::PeakTransformQSample::transformPeak().
getReferenceFrame()
virtual std::shared_ptr< const Geometry::ReferenceFrame > Mantid::Geometry::IPeak::getReferenceFrame () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::DataObjects::BasePeak::calculateWavelengthFromQLab(), and export_IPeak().
getRow()
virtual int Mantid::Geometry::IPeak::getRow () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getRunNumber()
virtual int Mantid::Geometry::IPeak::getRunNumber () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), export_IPeak(), Mantid::Crystal::PeakHKLErrors::getRun2MatMap(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
getSamplePos()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getSamplePos () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
getScattering()
virtual double Mantid::Geometry::IPeak::getScattering () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getSigmaIntensity()
virtual double Mantid::Geometry::IPeak::getSigmaIntensity () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::PeakIntensityVsRadius::exec(), and export_IPeak().
getSourceDirectionSampleFrame()
virtual Mantid::Kernel::V3D Mantid::Geometry::IPeak::getSourceDirectionSampleFrame () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
getTOF()
virtual double Mantid::Geometry::IPeak::getTOF () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::Crystal::IntegratePeakTimeSlices::CalculateTimeChannelSpan(), export_IPeak(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), and Mantid::DataObjects::BasePeak::getValueByColName().
getWavelength()
virtual double Mantid::Geometry::IPeak::getWavelength () const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), export_IPeak(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), and Mantid::DataObjects::BasePeak::getValueByColName().
isIndexed()
virtual bool Mantid::Geometry::IPeak::isIndexed () const pure virtual
Implemented in Mantid::DataObjects::BasePeak.
setAbsorptionWeightedPathLength()
virtual void Mantid::Geometry::IPeak::setAbsorptionWeightedPathLength (double pathLength) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setBinCount()
virtual void Mantid::Geometry::IPeak::setBinCount (double m_BinCount) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak(), and Mantid::MDAlgorithms::CentroidPeaksMD2::integrate().
setFinalEnergy()
virtual void Mantid::Geometry::IPeak::setFinalEnergy (double m_FinalEnergy) pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
setGoniometerMatrix()
virtual void Mantid::Geometry::IPeak::setGoniometerMatrix (const Mantid::Kernel::Matrix< double > & m_GoniometerMatrix) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
setH()
virtual void Mantid::Geometry::IPeak::setH (double m_H) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setHKL() [1/2]
virtual void Mantid::Geometry::IPeak::setHKL (const Mantid::Kernel::V3D & HKL) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
setHKL() [2/2]
virtual void Mantid::Geometry::IPeak::setHKL (double H, double K, double L) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::SelectCellWithForm::ApplyTransform(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::TransformHKL::exec(), export_IPeak(), and Mantid::MDAlgorithms::CentroidPeaksMD2::integrate().
setInitialEnergy()
virtual void Mantid::Geometry::IPeak::setInitialEnergy (double m_InitialEnergy) pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
setIntensity()
virtual void Mantid::Geometry::IPeak::setIntensity (double m_Intensity) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
setIntHKL()
virtual void Mantid::Geometry::IPeak::setIntHKL (const Mantid::Kernel::V3D & HKL) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::Crystal::SelectCellWithForm::ApplyTransform(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::TransformHKL::exec(), and export_IPeak().
setIntMNP()
virtual void Mantid::Geometry::IPeak::setIntMNP (const Mantid::Kernel::V3D & MNP) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setK()
virtual void Mantid::Geometry::IPeak::setK (double m_K) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setL()
virtual void Mantid::Geometry::IPeak::setL (double m_L) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setMonitorCount()
virtual void Mantid::Geometry::IPeak::setMonitorCount (double m_MonitorCount) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setPeakNumber()
virtual void Mantid::Geometry::IPeak::setPeakNumber (int m_PeakNumber) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::MDAlgorithms::FindPeaksMD::exec(), and export_IPeak().
setPeakShape() [1/2]
virtual void Mantid::Geometry::IPeak::setPeakShape (Mantid::Geometry::PeakShape * shape) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
setPeakShape() [2/2]
virtual void Mantid::Geometry::IPeak::setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
setQLabFrame()
virtual void Mantid::Geometry::IPeak::setQLabFrame (const Mantid::Kernel::V3D & QLabFrame, std::optional< double > detectorDistance) pure virtual
Implemented in Mantid::DataObjects::Peak, and Mantid::DataObjects::LeanElasticPeak.
Referenced by Mantid::MDAlgorithms::CentroidPeaksMD2::integrate().
setQSampleFrame()
virtual void Mantid::Geometry::IPeak::setQSampleFrame (const Mantid::Kernel::V3D & QSampleFrame, std::optional< double > detectorDistance) pure virtual
Implemented in Mantid::DataObjects::Peak, and Mantid::DataObjects::LeanElasticPeak.
Referenced by Mantid::MDAlgorithms::CentroidPeaksMD2::integrate().
setRunNumber()
virtual void Mantid::Geometry::IPeak::setRunNumber (int m_RunNumber) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setSamplePos() [1/2]
virtual void Mantid::Geometry::IPeak::setSamplePos (const Mantid::Kernel::V3D & XYZ) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
setSamplePos() [2/2]
virtual void Mantid::Geometry::IPeak::setSamplePos (double samX, double samY, double samZ) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak().
setSigmaIntensity()
virtual void Mantid::Geometry::IPeak::setSigmaIntensity (double m_SigmaIntensity) pure virtual
Implemented in Mantid::DataObjects::BasePeak.
Referenced by export_IPeak(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), and Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
setWavelength()
virtual void Mantid::Geometry::IPeak::setWavelength (double wavelength) pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeak, and Mantid::DataObjects::Peak.
Referenced by export_IPeak().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/IPeak.h