Mantid: std Namespace Reference
std Namespace Reference
STL namespace.
Namespaces
namespace literals
namespace wide_integer_literals
Classes
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
class jthread
STL class.
class length_error
STL class.
class list
STL class.
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class weak_ptr
STL class.
class wfstream
STL class.
class wide_integer
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Typedefs
template<class T1 , class T2 >
using __only_arithmetic = typename std::enable_if< ArithmeticConcept< T1 >() &&ArithmeticConcept< T2 >()>::type
template<class T , class T2 >
using __only_integer = typename std::enable_if< IntegralConcept< T >() &&IntegralConcept< T2 >()>::type
using int128_t = wide_int< 128 >
using int256_t = wide_int< 256 >
using int512_t = wide_int< 512 >
using uint128_t = wide_uint< 128 >
using uint256_t = wide_uint< 256 >
using uint512_t = wide_uint< 512 >
template<size_t Bits>
using wide_int = wide_integer< Bits, signed >
template<size_t Bits>
using wide_uint = wide_integer< Bits, unsigned >
Functions
template<typename T >
static constexpr bool ArithmeticConcept () noexcept
template<typename HeldType >
HeldType * get_pointer (const std::weak_ptr< HeldType > &dataItem)
Boost.Python doesn't understand weak_ptrs out of the box.
template<typename T >
static constexpr bool IntegralConcept () noexcept
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator!= (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator!= (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
constexpr int128_t operator""_cppi128 (const char *n)
constexpr int256_t operator""_cppi256 (const char *n)
constexpr int512_t operator""_cppi512 (const char *n)
constexpr uint128_t operator""_cppui128 (const char *n)
constexpr uint256_t operator""_cppui256 (const char *n)
constexpr uint512_t operator""_cppui512 (const char *n)
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>>
std::common_type_t< Integral, Integral2 > constexpr operator% (const Integral &rhs, const Integral2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator% (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>>
std::common_type_t< Integral, Integral2 > constexpr operator& (const Integral &rhs, const Integral2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator& (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
std::common_type_t< Arithmetic, Arithmetic2 > constexpr operator* (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator* (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
std::common_type_t< Arithmetic, Arithmetic2 > constexpr operator+ (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed >
constexpr wide_integer< Bits, Signed > operator+ (const wide_integer< Bits, Signed > &lhs) noexcept(is_same< Signed, unsigned >::value)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator+ (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
std::common_type_t< Arithmetic, Arithmetic2 > constexpr operator- (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed >
constexpr wide_integer< Bits, Signed > operator- (const wide_integer< Bits, Signed > &lhs) noexcept(is_same< Signed, unsigned >::value)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator- (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
std::common_type_t< Arithmetic, Arithmetic2 > constexpr operator/ (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator/ (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator< (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator< (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<size_t Bits, typename Signed , typename T2 , typename = std::enable_if<std::is_integral<T2>::value && std::is_unsigned<T2>::value>>
constexpr wide_integer< Bits, Signed > operator<< (const wide_integer< Bits, Signed > &lhs, T2 n) noexcept
template<size_t Bits, typename Signed >
std::ostream & operator<< (std::ostream &out, const wide_integer< Bits, Signed > &n)
template<size_t Bits, typename Signed >
std::wostream & operator<< (std::wostream &out, const wide_integer< Bits, Signed > &n)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator<= (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator<= (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator== (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator== (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator> (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator> (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>>
constexpr bool operator>= (const Arithmetic &rhs, const Arithmetic2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
constexpr bool operator>= (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<size_t Bits, typename Signed , typename T2 , typename = std::enable_if<std::is_integral<T2>::value && std::is_unsigned<T2>::value>>
constexpr wide_integer< Bits, Signed > operator>> (const wide_integer< Bits, Signed > &lhs, T2 n) noexcept
template<size_t Bits, typename Signed >
std::istream & operator>> (std::istream &in, wide_integer< Bits, Signed > &n)
template<size_t Bits, typename Signed >
std::wistream & operator>> (std::wistream &in, wide_integer< Bits, Signed > &n)
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>>
std::common_type_t< Integral, Integral2 > constexpr operator^ (const Integral &rhs, const Integral2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator^ (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>>
std::common_type_t< Integral, Integral2 > constexpr operator| (const Integral &rhs, const Integral2 &lhs)
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 >
std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr operator| (const wide_integer< Bits, Signed > &lhs, const wide_integer< Bits2, Signed2 > &rhs)
template<size_t Bits, typename Signed >
constexpr wide_integer< Bits, Signed > operator~ (const wide_integer< Bits, Signed > &lhs) noexcept
template<size_t Bits, typename Signed >
std::string to_string (const wide_integer< Bits, Signed > &n)
template<size_t Bits, typename Signed >
std::wstring to_wstring (const wide_integer< Bits, Signed > &n)
Detailed Description
STL namespace.
class wide_integer has been created working on proposals for c++ standard "Numbers TS" in 2017 by Igor Klevanets cerev.nosp@m.ra@y.nosp@m.andex.nosp@m..ru, cerev.nosp@m.ra@y.nosp@m.andex.nosp@m.-tea.nosp@m.m.ru and Antony Polukhin antos.nosp@m.hkka.nosp@m.@gmai.nosp@m.l.co.nosp@m.m, antos.nosp@m.hkka.nosp@m.@yand.nosp@m.ex-t.nosp@m.eam.r.nosp@m.u and has been approved by committee: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0104r0.html The original source could be found: https://github.com/cerevra/int/tree/master/v3.
This class is adopted to use 32 bit integer type as the base class (for performance) to implement uint96, uint128, uint256 types, used in indexed version of ConvertToMD for Morton index. Class is not much optimized due to it is not the bottleneck in algorithm. Minor changes have been applied to avoid compiler warnings.
Should be substituted by something from stdlib in the proper c++ standard.
Typedef Documentation
__only_arithmetic
template<class T1 , class T2 > using std::__only_arithmetic = typedef typename std::enable_if<ArithmeticConcept<T1>() && ArithmeticConcept<T2>()>::type
Definition at line 144 of file WideInt.h.
__only_integer
template<class T , class T2 > using std::__only_integer = typedef typename std::enable_if<IntegralConcept<T>() && IntegralConcept<T2>()>::type
Definition at line 148 of file WideInt.h.
Function Documentation
ArithmeticConcept()
template<typename T > static constexpr bool std::ArithmeticConcept () static constexpr noexcept
get_pointer()
template<typename HeldType > HeldType * std::get_pointer (const std::weak_ptr< HeldType > & dataItem) inline
Boost.Python doesn't understand weak_ptrs out of the box.
This acts an intermediary so that a bare pointer can be retrieved from the wrapper. The important bit here is that the weak pointer won't allow the bare pointer to be retrieved unless the object it points to still exists The name and arguments are dictated by boost
Parameters
dataItem :: A reference to the weak_ptr
Returns
A bare pointer to the HeldType
Definition at line 29 of file WeakPtr.h.
IntegralConcept()
template<typename T > static constexpr bool std::IntegralConcept () static constexpr noexcept
operator!=() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator!= (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator!=() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator!= (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator""_cppi128()
constexpr int128_t std::operator""_cppi128 (const char * n) constexpr
operator""_cppi256()
constexpr int256_t std::operator""_cppi256 (const char * n) constexpr
operator""_cppi512()
constexpr int512_t std::operator""_cppi512 (const char * n) constexpr
operator""_cppui128()
constexpr uint128_t std::operator""_cppui128 (const char * n) constexpr
operator""_cppui256()
constexpr uint256_t std::operator""_cppui256 (const char * n) constexpr
operator""_cppui512()
constexpr uint512_t std::operator""_cppui512 (const char * n) constexpr
operator%() [1/2]
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>> std::common_type_t< Integral, Integral2 > constexpr std::operator% (const Integral & rhs, const Integral2 & lhs) constexpr
operator%() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator% (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator&() [1/2]
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>> std::common_type_t< Integral, Integral2 > constexpr std::operator& (const Integral & rhs, const Integral2 & lhs) constexpr
operator&() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator& (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator*() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> std::common_type_t< Arithmetic, Arithmetic2 > constexpr std::operator* (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator*() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator* (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator+() [1/3]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> std::common_type_t< Arithmetic, Arithmetic2 > constexpr std::operator+ (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator+() [2/3]
template<size_t Bits, typename Signed > constexpr wide_integer< Bits, Signed > std::operator+ (const wide_integer< Bits, Signed > & lhs) constexpr noexcept
operator+() [3/3]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator+ (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator-() [1/3]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> std::common_type_t< Arithmetic, Arithmetic2 > constexpr std::operator- (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator-() [2/3]
template<size_t Bits, typename Signed > constexpr wide_integer< Bits, Signed > std::operator- (const wide_integer< Bits, Signed > & lhs) constexpr noexcept
operator-() [3/3]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator- (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator/() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> std::common_type_t< Arithmetic, Arithmetic2 > constexpr std::operator/ (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator/() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator/ (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator<() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator< (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator<() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator< (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator<<() [1/3]
template<size_t Bits, typename Signed , typename T2 , typename = std::enable_if<std::is_integral<T2>::value && std::is_unsigned<T2>::value>> constexpr wide_integer< Bits, Signed > std::operator<< (const wide_integer< Bits, Signed > & lhs, T2 n) constexpr noexcept
operator<<() [2/3]
template<size_t Bits, typename Signed > std::ostream & std::operator<< (std::ostream & out, const wide_integer< Bits, Signed > & n)
operator<<() [3/3]
template<size_t Bits, typename Signed > std::wostream & std::operator<< (std::wostream & out, const wide_integer< Bits, Signed > & n)
operator<=() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator<= (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator<=() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator<= (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator==() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator== (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator==() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator== (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
Referenced by Mantid::Kernel::V3D::operator!=().
operator>() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator> (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator>() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator> (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator>=() [1/2]
template<typename Arithmetic , typename Arithmetic2 , class = __only_arithmetic<Arithmetic, Arithmetic2>> constexpr bool std::operator>= (const Arithmetic & rhs, const Arithmetic2 & lhs) constexpr
operator>=() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > constexpr bool std::operator>= (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator>>() [1/3]
template<size_t Bits, typename Signed , typename T2 , typename = std::enable_if<std::is_integral<T2>::value && std::is_unsigned<T2>::value>> constexpr wide_integer< Bits, Signed > std::operator>> (const wide_integer< Bits, Signed > & lhs, T2 n) constexpr noexcept
operator>>() [2/3]
template<size_t Bits, typename Signed > std::istream & std::operator>> (std::istream & in, wide_integer< Bits, Signed > & n)
operator>>() [3/3]
template<size_t Bits, typename Signed > std::wistream & std::operator>> (std::wistream & in, wide_integer< Bits, Signed > & n)
operator^() [1/2]
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>> std::common_type_t< Integral, Integral2 > constexpr std::operator^ (const Integral & rhs, const Integral2 & lhs) constexpr
operator^() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator^ (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator|() [1/2]
template<typename Integral , typename Integral2 , class = __only_integer<Integral, Integral2>> std::common_type_t< Integral, Integral2 > constexpr std::operator| (const Integral & rhs, const Integral2 & lhs) constexpr
operator|() [2/2]
template<size_t Bits, typename Signed , size_t Bits2, typename Signed2 > std::common_type_t< wide_integer< Bits, Signed >, wide_integer< Bits2, Signed2 > > constexpr std::operator| (const wide_integer< Bits, Signed > & lhs, const wide_integer< Bits2, Signed2 > & rhs) constexpr
operator~()
template<size_t Bits, typename Signed > constexpr wide_integer< Bits, Signed > std::operator~ (const wide_integer< Bits, Signed > & lhs) constexpr noexcept
to_string()
template<size_t Bits, typename Signed > std::string std::to_string (const wide_integer< Bits, Signed > & n)
Referenced by Mantid::API::AnalysisDataServiceImpl::add(), Mantid::DataHandling::NXcanSAS::addDigit(), Mantid::CurveFitting::Algorithms::QENSFitSequential::addFitRangeLogs(), Mantid::Geometry::ShapeFactory::addGoniometerTag(), Mantid::Algorithms::ExtractQENSMembers::addMembersToADS(), Mantid::DataHandling::LegacyLoadHelper::addNumericProperty(), Mantid::API::AnalysisDataServiceImpl::addOrReplace(), MantidQt::MantidWidgets::FunctionTreeView::addParameterTieInComposite(), MantidQt::MantidWidgets::MuonPeriodInfo::addPeriodToTable(), Mantid::DataHandling::NXcanSAS::addProcess(), Mantid::DataHandling::SaveNXcanSASBase::addSasEntry(), Mantid::DataHandling::LoadPSIMuonBin::addToSampleLog(), Mantid::DataHandling::LoadPSIMuonBin::addToSampleLog(), MantidQt::MantidWidgets::FitScriptGeneratorModel::addWorkspaceDomain(), Mantid::DataHandling::adjustTimeOfFlightISISLegacy(), Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::appendEventsFromInputWS(), Mantid::DataHandling::LoadPSIMuonBin::assignOutputWorkspaceParticulars(), Mantid::API::CompositeFunction::attributeFunctionIndex(), Mantid::DataHandling::AlignAndFocusPowderSlim::BankCalibration::BankCalibration(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::binEvent(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildAttributeNames(), Mantid::CurveFitting::Functions::ComptonProfile::buildCaches(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteMultiSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildPhysprop(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildTargetFunction(), Mantid::DataHandling::LoadNexusProcessed::buildWorkspaceName(), Mantid::ICat::ICat4Catalog::bytesToString(), Mantid::MDAlgorithms::MDTransfModQ::calcGenericVariables(), Mantid::MDAlgorithms::MDTransfNoQ::calcGenericVariables(), Mantid::Algorithms::MCAbsorptionStrategy::calculate(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackground(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::calculateMS(), Mantid::Algorithms::HeliumAnalyserEfficiency::calculateTCrit(), Mantid::DataHandling::SaveOpenGenieAscii::calculateXYZDelta(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcWavelengthDependentTransmission(), Mantid::API::ITableWorkspace::cell(), Mantid::API::SpectrumInfo::checkAndGetSpectrumDefinition(), Mantid::CurveFitting::Functions::CrystalFieldControl::checkConsistent(), MantidQt::MantidWidgets::FunctionModel::checkDatasets(), Mantid::DataHandling::LoadEventNexus::checkForCorruptedPeriods(), Mantid::MDAlgorithms::MDWSDescription::checkMinMaxNdimConsistent(), Mantid::DataHandling::LoadISISNexus2::checkOptionalProperties(), Mantid::API::ParamFunction::checkParameterIndex(), Mantid::API::NumericAxisValidator::checkValidity(), Mantid::API::SpectraAxisValidator::checkValidity(), Mantid::Kernel::ArrayOrderedPairsValidator< TYPE >::checkValidity(), Mantid::Geometry::MeshObjectCommon::checkVertexLimit(), MantidQt::CustomInterfaces::UserInputValidator::checkWorkspaceNumberOfBins(), MantidQt::CustomInterfaces::UserInputValidator::checkWorkspaceNumberOfHistograms(), Mantid::MDAlgorithms::MDWSDescription::checkWSCorresponsMDWorkspace(), Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::Algorithms::WorkflowAlgorithmRunner::configureRow(), MantidQt::MantidWidgets::FitScriptGeneratorModel::constructGlobalParameterTie(), Mantid::DataHandling::LoadSESANS::consumeData(), Mantid::Geometry::InstrumentDefinitionParser::convertLocationsElement(), Mantid::Kernel::UnitConversion::convertViaTOF(), Mantid::DataHandling::SaveOpenGenieAscii::convertWorkspaceData(), Mantid::DataObjects::CoordTransformAligned::CoordTransformAligned(), Mantid::DataObjects::CoordTransformAligned::CoordTransformAligned(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::correctForWorkspaceNameClash(), Mantid::DataHandling::LoadNexusProcessed::correctForWorkspaceNameClash(), Mantid::DataHandling::CreateSimulationWorkspace::createBinBoundaries(), Mantid::Algorithms::Stitch1DMany::createChildWorkspaceName(), ComponentCreationHelper::createCylInstrumentWithDetInGivenPositions(), ComponentCreationHelper::createCylInstrumentWithVerticalOffsetsSpecified(), Mantid::API::SpectrumInfo::createDetectorIdLogMessages(), Mantid::DataHandling::JoinISISPolarizationEfficiencies::createEfficiencies(), Mantid::DataHandling::LoadISISPolarizationEfficiencies::createEfficiencies(), Mantid::MDAlgorithms::MDEventWSWrapper::createEmptyMDWS(), Mantid::API::MultiDomainFunction::createEquivalentFunctions(), Mantid::DataHandling::SaveDetectorsGrouping::createGroupDetectorIDMap(), Mantid::Algorithms::FindPeaksConvolve::createIntermediateWorkspaces(), MuonWorkspaceCreationHelper::createMultiPeriodAsymmetryData(), MuonWorkspaceCreationHelper::createMultiPeriodWorkspaceGroup(), Mantid::Algorithms::FindPeaksConvolve::createOutputTables(), Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace(), Mantid::Algorithms::ConvertSpectrumAxis2::createOutputWorkspace(), Mantid::CurveFitting::MultiDomainCreator::createOutputWorkspace(), Mantid::MDAlgorithms::LoadSQW2::createQDimension(), MantidQt::MantidWidgets::ConvolutionFunctionModel::createResolutionFunction(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::createResultsTable(), Mantid::DataHandling::SaveCanSAS1D::createSASInstrument(), Mantid::DataHandling::SaveCanSAS1D::createSASSampleElement(), Mantid::Geometry::ShapeFactory::createShape(), Mantid::Algorithms::CreateSampleWorkspace::createTestInstrumentRectangular(), Mantid::Algorithms::SampleLogsBehaviour::createTolerancesVector(), Mantid::Algorithms::createTruncatedList(), MuonWorkspaceCreationHelper::createWorkspaceGroupConsecutiveDetectorIDs(), MuonGroupingXMLHelper::createXMLwithPairsAndGroups(), Mantid::DataHandling::LoadTBL::csvParse(), Mantid::Kernel::Spline< X, Y >::deriv(), Mantid::DataHandling::LoadPSIMuonBin::detectTempFile(), Mantid::DataHandling::SaveOpenGenieAscii::determineEnginXBankId(), Mantid::Algorithms::DiffractionFocussing2::determineRebinParametersFromParameters(), Mantid::Geometry::SymmetryElementRotationGenerator::determineSymbol(), Mantid::Geometry::ParameterMap::diff(), Mantid::DataHandling::LoadFITS::doLoadFiles(), MantidQt::MantidWidgets::FitDomain::domainName(), Mantid::MDAlgorithms::SaveMD2::doSaveHisto(), Mantid::API::IFunctionMD::evaluateFunction(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CreateBootstrapWorkspaces::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GetAllEi::exec(), Mantid::Algorithms::PaddingAndApodization::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::SofQWCentre::exec(), Mantid::Algorithms::WorkflowAlgorithmRunner::exec(), Mantid::Crystal::AnvredCorrection::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::StatisticsOfPeaksWorkspace::exec(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::exec(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::ExtractPolarizationEfficiencies::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadILLPolarizationFactors::exec(), Mantid::DataHandling::LoadQKK::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::MDAlgorithms::CompactMD::exec(), Mantid::MDAlgorithms::CutMD::exec(), Mantid::MDAlgorithms::ReplicateMD::exec(), Mantid::DataHandling::SaveFITS::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::execConcrete(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::Algorithms::PolarizationCorrectionFredrikze::execPA(), Mantid::API::Algorithm::executeInternal(), Mantid::Algorithms::NormaliseByCurrent::extractCharge(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::extractMembers(), Mantid::DataHandling::LoadNexusProcessed::extractWorkspaceNames(), Mantid::Kernel::Smoothing::fftButterworthSmooth(), Mantid::Kernel::Smoothing::fftSmooth(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::finaliseOutputWorkspacesWithAppend(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), MantidQt::MantidWidgets::FitScriptGeneratorModel::findDomainIndex(), Mantid::CurveFitting::Algorithms::SplineInterpolation::findInterpolationRange(), Mantid::API::FileFinderImpl::findRuns(), Mantid::Algorithms::HeliumAnalyserEfficiency::fitHe3Polarization(), Mantid::API::IFunction::fix(), Mantid::CurveFitting::Functions::Gaussian::fixIntensity(), Mantid::CurveFitting::Functions::FullprofPolynomial::FullprofPolynomial(), Mantid::API::MultiDomainFunction::function(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::CurveFitting::Functions::UserFunction::function1D(), Mantid::API::MultiDomainFunction::functionDeriv(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::API::CompositeFunction::functionIndex(), Mantid::CurveFitting::GeneralDomainCreator::GeneralDomainCreator(), Mantid::DataHandling::SaveGSS::generateOutFileNames(), Mantid::Algorithms::MCInteractionVolume::generatePoint(), Mantid::Algorithms::GeneratePythonFitScript::generateSimultaneousFitCode(), Mantid::Algorithms::GeneratePythonFitScript::generateVariableSetupCode(), Mantid::DataHandling::LoadTBL::getCells(), Mantid::Algorithms::SANSCollimationLengthEstimator::getCollimationLengthWithGuides(), Mantid::DataHandling::NXcanSAS::getDataSpaceInfo(), Mantid::API::SpectrumInfo::getDetector(), Mantid::Algorithms::He3TubeEfficiency::getDetectorGeometry(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::getDetectorParameters(), Mantid::ICat::ICat4Catalog::getDownloadURL(), Mantid::ICat::ICat4Catalog::getFileLocation(), MantidQt::MantidWidgets::FitScriptGeneratorModel::getFullParameter(), MantidQt::MantidWidgets::FunctionTreeView::getFullParameterName(), Mantid::API::CompositeFunction::getFunction(), Mantid::MDAlgorithms::SlicingAlgorithm::getGeneralImplicitFunction(), Mantid::DataHandling::LoadCSNSNexus::getGPPDModules(), Mantid::ICat::CatalogAlgorithmHelper::getIDSError(), MantidQt::MantidWidgets::WorkspaceUtils::getIndexString(), Mantid::API::MultiDomainFunction::getLocalAttribute(), Mantid::DataObjects::EventWorkspace::getNumberBins(), Mantid::DataObjects::Workspace2D::getNumberBins(), Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getPeakGroups(), Mantid::CurveFitting::Functions::VesuvioResolution::getResolutionParameters(), Mantid::Crystal::PeakHKLErrors::getRun2MatMap(), Mantid::DataHandling::SaveOpenGenieAscii::getSampleLogs(), Mantid::API::MatrixWorkspace::getSignalAtCoord(), MantidQt::MantidWidgets::FunctionModelSpectra::getString(), Mantid::ICat::ICat4Catalog::getUploadURL(), Mantid::CurveFitting::Algorithms::getWorkspace(), Mantid::API::Grouping::Grouping(), MantidQt::MantidWidgets::FunctionModelSpectra::indexOf(), Mantid::MDAlgorithms::UserFunctionMD::initDimensions(), Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMinimizer::initialize(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::DataHandling::LoadILLReflectometry::initNames(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD33(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::integrateCumulative(), Mantid::Kernel::PropertyHistory::isEmptyDefault(), MantidQt::MantidWidgets::ConvolutionFunctionModel::iterateThroughFunction(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::iterationContinuation(), Mantid::FrameworkTestHelpers::FunctionChangesNParams::iterationFinished(), Mantid::API::SpectraAxis::label(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadBankParameters(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadData(), Mantid::DataHandling::LoadILLReflectometry::loadData(), Mantid::DataHandling::LoadILLSANS::loadDataFromD16ScanMonitors(), Mantid::DataHandling::LoadMuonStrategy::loadDefaultDetectorGrouping(), Mantid::DataHandling::LoadEventNexus::loadEntryMetadata(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFrom3MF(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::LoadDetectorInfo::loadFromRAW(), Mantid::DataHandling::LoadFITS::loadHeader(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadMetaData(), Mantid::DataHandling::Load::loadMultipleFiles(), Mantid::API::Run::loadNexusCommon(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), Mantid::DataHandling::LoadISISNexusHelper::loadRunDetails(), Mantid::DataHandling::LoadMLZ::loadRunDetails(), Mantid::DataHandling::LoadNexusProcessed::loadTableEntry(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadTwoThetaDetectors(), Mantid::Algorithms::CalculateTransmission::logIfNotMonitor(), ComponentCreationHelper::makeBank(), Mantid::Algorithms::SparseWorkspace::makeCubeShape(), Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEW(), Mantid::MDAlgorithms::MDAlgorithmsTestHelper::makeFileBackedMDEWwithMDFrame(), Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsMultiSiteMultiSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsSingleSiteMultiSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsSingleSiteSingleSpectrum(), Mantid::API::IFuncMinimizer::minimize(), Mantid::DataHandling::LoadILLIndirect2::moveSingleDetectors(), Mantid::DataHandling::LoadILLPolarizedDiffraction::moveTwoTheta(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::normalize(), Mantid::Kernel::FilteredTimeSeriesProperty< HeldType >::nthInterval(), Mantid::Kernel::Spline< X, Y >::operator()(), Mantid::Kernel::OptionalBool::operator=(), Mantid::CurveFitting::Functions::CrystalFieldFunction::parameterName(), Mantid::DataHandling::LoadFITS::parseHeader(), Mantid::DataHandling::LoadAscii2::parseLine(), MantidQt::MantidWidgets::WorkspaceUtils::parseRunNumbers(), Mantid::Algorithms::GetAllEi::peakGuess(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), Mantid::Algorithms::FindPeaksConvolve::performConvolution(), Mantid::Algorithms::FindPeaksConvolve::populateOutputWorkspaces(), Mantid::DataHandling::SaveAscii2::populateSpectrumNumberMetaData(), Mantid::Algorithms::Fitting::prepareEfficiencyFunc(), Mantid::Algorithms::Fitting::prepareExpDecayFunction(), Mantid::FrameworkTestHelpers::prepareInputGroup(), Mantid::MDAlgorithms::ConvertToMDParent::preprocessDetectorsPositions(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Geometry::CSGObject::procString(), Mantid::Algorithms::SofQCommon::qBinHintsIndirect(), Mantid::DataHandling::GroupDetectors2::readFile(), Mantid::DataHandling::LoadFITS::readInBuffer(), Mantid::DataHandling::LoadBinaryStl::readShape(), Mantid::DataHandling::GroupDetectors2::readSpectraIndexes(), Mantid::DataHandling::LoadRKH::readUnit(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::API::CompositeFunction::removeFunction(), Mantid::API::renameWorkspacesWith(), Mantid::API::CompositeFunction::replaceFunction(), Mantid::DataHandling::LoadNGEM::reportProgressAndCheckCancel(), Mantid::CurveFitting::Functions::BSpline::resetParameters(), Mantid::MDAlgorithms::MDWSDescription::resizeDimDescriptions(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::API::Run::saveNexus(), Mantid::Algorithms::CreateFloodWorkspace::scaleToCentralPixel(), Mantid::API::ScriptRepoException::ScriptRepoException(), Mantid::ICat::ICat4Catalog::search(), Mantid::API::ParameterTie::set(), Mantid::Nexus::NXAttributes::set(), Mantid::CurveFitting::Functions::Chebyshev::setAttribute(), Mantid::CurveFitting::Functions::CubicSpline::setAttribute(), Mantid::CurveFitting::Functions::FullprofPolynomial::setAttribute(), Mantid::CurveFitting::Functions::Polynomial::setAttribute(), Mantid::CurveFitting::Functions::ReflectivityMulf::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute(), MantidQt::MantidWidgets::FunctionModel::setBackgroundA0(), Mantid::DataHandling::LoadAscii2::setcolumns(), Mantid::MDAlgorithms::MDWSDescription::setDimName(), Mantid::MDAlgorithms::MDWSDescription::setDimUnit(), Mantid::CurveFitting::IFittingAlgorithm::setFunction(), Mantid::DataObjects::Workspace2D::setImageYAndE(), MantidQt::MantidWidgets::ConvolutionFunctionModel::setModel(), Mantid::CurveFitting::Algorithms::setMultiDataProperties(), MantidQt::MantidWidgets::MuonPeriodInfo::setNumberOfSequences(), Mantid::MDAlgorithms::MDWSDescription::setNumBins(), MantidQt::MantidWidgets::FitDomain::setParameterFixed(), Mantid::DataHandling::LoadRawHelper::setRunNumber(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), Mantid::Crystal::IntegratePeakTimeSlices::SetUpData1(), Mantid::CurveFitting::Functions::CubicSpline::setupInput(), Mantid::CurveFitting::Algorithms::SplineSmoothing::setupOutputWorkspace(), Mantid::Kernel::PropertyManagerProperty::setValueFromJson(), Mantid::CurveFitting::Functions::CubicSpline::setXAttribute(), Mantid::Geometry::ShapeFactory::sphereAlgebra(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::start_point(), Mantid::DataHandling::SaveOpenGenieAscii::storeWorkspaceInformation(), Mantid::Kernel::StringTokenizer::StringTokenizer(), Mantid::Crystal::FindSXPeaksHelper::SXPeak::SXPeak(), Mantid::DataHandling::LoadSESANS::throwFormatError(), Mantid::PythonInterface::Converters::NDArrayToVector< DestElementType >::throwIfSizeMismatched(), Mantid::PythonInterface::Converters::PySequenceToVector< DestElementType >::throwIfSizeMismatched(), Mantid::MDAlgorithms::LoadSQW2::throwIfUnsupportedFileType(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::API::ITableWorkspace::toString(), Mantid::API::IFunction::unfix(), Mantid::API::AnalysisDataServiceImpl::uniqueName(), MantidQt::MantidWidgets::FunctionTreeView::updateFunctionIndices(), Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteMultiSpectrum(), Mantid::Algorithms::AddLogInterpolated::validateInputs(), Mantid::Algorithms::AddLogSmoothed::validateInputs(), Mantid::Algorithms::CorelliCalibrationApply::validateInputs(), Mantid::Algorithms::CorrectTOFAxis::validateInputs(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::validateInputs(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::validateInputs(), Mantid::Algorithms::GetAllEi::validateInputs(), Mantid::Algorithms::PolarizerEfficiency::validateInputs(), Mantid::Algorithms::PolarizationCorrectionWildes::validateInputs(), Mantid::Algorithms::RealFFT::RealFFT::validateInputs(), Mantid::Algorithms::RebinRagged::validateInputs(), Mantid::Algorithms::RemoveSpectra::validateInputs(), Mantid::DataHandling::SaveGDA::validateInputs(), Mantid::DataHandling::SaveGSS::validateInputs(), Mantid::Algorithms::InterpolationOption::validateInputSize(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::validateNegativeFitWeights(), Mantid::NexusGeometry::validateStorageType(), Mantid::DataHandling::SaveFITS::writeFITSHeaderAxesSizes(), Mantid::DataHandling::SaveSESANS::writeHeaders(), Mantid::Nexus::NexusFileIO::writeNexusTableWorkspace(), Mantid::DataHandling::SaveGSS::writeSLOGdata(), and MantidQt::MantidWidgets::FitDomain::xLimits().
to_wstring()
template<size_t Bits, typename Signed > std::wstring std::to_wstring (const wide_integer< Bits, Signed > & n)