Mantid: Mantid::Geometry::MDHistoDimension Class Reference
Mantid::Geometry::MDHistoDimension Class Reference
MDHistoDimension :
#include <MDHistoDimension.h>
Public Member Functions
coord_t getBinWidth () const override
Return the width of one bin.
const std::string & getDimensionId () const override
Short name which identify the dimension among other dimension.
coord_t getMaximum () const override
Returns the maximum extent of this dimension.
const MDFrame & getMDFrame () const override
Return the md frame.
const Kernel::MDUnit & getMDUnits () const override
Returns the unit.
coord_t getMinimum () const override
Returns the minimum extent of this dimension.
std::string getName () const override
Return the name of the dimension as can be displayed along the axis.
size_t getNBins () const override
number of bins dimension have (an integrated has one).
size_t getNBoundaries () const override
number of bin boundaries (axis points)
const Kernel::UnitLabel getUnits () const override
Return the units of the dimension as a string.
coord_t getX (size_t index) const override
Get coordinate for index;.
MDHistoDimension (const IMDDimension *other)
copy constructor
MDHistoDimension (std::string name, std::string ID, const MDFrame &frame, coord_t min, coord_t max, size_t numBins)
Constructor for simple MDHistoDimension.
void setMDFrame (const MDFrame &frame)
Set the MDFrame.
void setRange (size_t nBins, coord_t min, coord_t max) override
Change the extents and number of bins.
std::string toXMLString () const override
Dimensions must be xml serializable.
Public Member Functions inherited from Mantid::Geometry::IMDDimension
virtual bool getIsIntegrated () const
bool operator!= (const IMDDimension &) const
bool operator== (const IMDDimension &) const
virtual ~IMDDimension ()=default
Destructor.
Private Attributes
coord_t m_binWidth
Calculated bin size.
std::string m_dimensionId
ID string.
Geometry::MDFrame_uptr m_frame
Multidimensional frame.
coord_t m_max
Extent of dimension.
coord_t m_min
Extent of dimension.
std::string m_name
Name.
size_t m_numBins
Number of bins.
Detailed Description
MDHistoDimension :
A very simple implementation of a IMDDimension, describing the limits and number of bins in a dimension.
Author
Janik Zikovsky
Date
2011-03-24 14:16:39.231608
Definition at line 28 of file MDHistoDimension.h.
Constructor & Destructor Documentation
MDHistoDimension() [1/2]
Mantid::Geometry::MDHistoDimension::MDHistoDimension (std::string name, std::string ID, const MDFrame & frame, coord_t min, coord_t max, size_t numBins) inline
Constructor for simple MDHistoDimension.
Parameters
name :: full name of the axis
ID :: identifier string
frame :: MDFrame
min :: minimum extent
max :: maximum extent
numBins :: number of bins (evenly spaced)
Definition at line 38 of file MDHistoDimension.h.
MDHistoDimension() [2/2]
Mantid::Geometry::MDHistoDimension::MDHistoDimension (const IMDDimension * other) inline
copy constructor
Parameters
other :: other IMDDimension
Definition at line 50 of file MDHistoDimension.h.
Member Function Documentation
getBinWidth()
coord_t Mantid::Geometry::MDHistoDimension::getBinWidth () const inline override virtual
Return the width of one bin.
Reimplemented from Mantid::Geometry::IMDDimension.
Definition at line 93 of file MDHistoDimension.h.
getDimensionId()
const std::string & Mantid::Geometry::MDHistoDimension::getDimensionId () const inline override virtual
Short name which identify the dimension among other dimension.
A dimension can be usually found by its ID and various various method exist to manipulate set of dimensions by their names.
Implements Mantid::Geometry::IMDDimension.
Definition at line 71 of file MDHistoDimension.h.
Referenced by toXMLString().
getMaximum()
coord_t Mantid::Geometry::MDHistoDimension::getMaximum () const inline override virtual
Returns the maximum extent of this dimension.
Implements Mantid::Geometry::IMDDimension.
Definition at line 74 of file MDHistoDimension.h.
References m_max.
Referenced by toXMLString().
getMDFrame()
const MDFrame & Mantid::Geometry::MDHistoDimension::getMDFrame () const inline override virtual
Return the md frame.
Implements Mantid::Geometry::IMDDimension.
Definition at line 59 of file MDHistoDimension.h.
Referenced by toXMLString().
getMDUnits()
const Kernel::MDUnit & Mantid::Geometry::MDHistoDimension::getMDUnits () const inline override virtual
Returns the unit.
Implements Mantid::Geometry::IMDDimension.
Definition at line 65 of file MDHistoDimension.h.
getMinimum()
coord_t Mantid::Geometry::MDHistoDimension::getMinimum () const inline override virtual
Returns the minimum extent of this dimension.
Implements Mantid::Geometry::IMDDimension.
Definition at line 77 of file MDHistoDimension.h.
References m_min.
Referenced by toXMLString().
getName()
std::string Mantid::Geometry::MDHistoDimension::getName () const inline override virtual
Return the name of the dimension as can be displayed along the axis.
Implements Mantid::Geometry::IMDDimension.
Definition at line 56 of file MDHistoDimension.h.
Referenced by toXMLString().
getNBins()
size_t Mantid::Geometry::MDHistoDimension::getNBins () const inline override virtual
number of bins dimension have (an integrated has one).
A axis directed along dimension would have getNBins+1 axis points.
Implements Mantid::Geometry::IMDDimension.
Definition at line 81 of file MDHistoDimension.h.
Referenced by toXMLString().
getNBoundaries()
size_t Mantid::Geometry::MDHistoDimension::getNBoundaries () const inline override virtual
number of bin boundaries (axis points)
Implements Mantid::Geometry::IMDDimension.
Definition at line 84 of file MDHistoDimension.h.
getUnits()
const Kernel::UnitLabel Mantid::Geometry::MDHistoDimension::getUnits () const inline override virtual
Return the units of the dimension as a string.
Implements Mantid::Geometry::IMDDimension.
Definition at line 62 of file MDHistoDimension.h.
Referenced by toXMLString().
getX()
coord_t Mantid::Geometry::MDHistoDimension::getX (size_t index) const inline override virtual
Get coordinate for index;.
Implements Mantid::Geometry::IMDDimension.
Definition at line 90 of file MDHistoDimension.h.
References index, and m_min.
setMDFrame()
void Mantid::Geometry::MDHistoDimension::setMDFrame (const MDFrame & frame) inline
Set the MDFrame.
This method was added in order to set the correct MDFrame information on workspaces which are loaded from legacy files. This is currently being used by SetMDFrame. Except for legacy corrections you should not have to use of this method. If you think you do, it is advisible to consolut with other Mantid team members before using it.
Parameters
frame,: a reference to a new MDFrame
Definition at line 119 of file MDHistoDimension.h.
References Mantid::Geometry::MDFrame::clone().
setRange()
void Mantid::Geometry::MDHistoDimension::setRange (size_t nBins, coord_t min, coord_t max) inline override virtual
Change the extents and number of bins.
Parameters
nBins :: number of bins
min :: extents minimum
max :: extents maximum
Implements Mantid::Geometry::IMDDimension.
Definition at line 100 of file MDHistoDimension.h.
References m_max, and m_min.
toXMLString()
std::string Mantid::Geometry::MDHistoDimension::toXMLString () const override virtual
Dimensions must be xml serializable.
Implements Mantid::Geometry::IMDDimension.
Definition at line 23 of file MDHistoDimension.cpp.
References getDimensionId(), Mantid::Geometry::IMDDimension::getIsIntegrated(), getMaximum(), getMDFrame(), getMinimum(), getName(), getNBins(), getUnits(), and name.
Member Data Documentation
m_binWidth
coord_t Mantid::Geometry::MDHistoDimension::m_binWidth private
Calculated bin size.
Definition at line 141 of file MDHistoDimension.h.
m_dimensionId
std::string Mantid::Geometry::MDHistoDimension::m_dimensionId private
ID string.
Definition at line 126 of file MDHistoDimension.h.
m_frame
Geometry::MDFrame_uptr Mantid::Geometry::MDHistoDimension::m_frame private
Multidimensional frame.
Definition at line 129 of file MDHistoDimension.h.
m_max
coord_t Mantid::Geometry::MDHistoDimension::m_max private
Extent of dimension.
Definition at line 135 of file MDHistoDimension.h.
m_min
coord_t Mantid::Geometry::MDHistoDimension::m_min private
Extent of dimension.
Definition at line 132 of file MDHistoDimension.h.
m_name
std::string Mantid::Geometry::MDHistoDimension::m_name private
Name.
Definition at line 123 of file MDHistoDimension.h.
m_numBins
size_t Mantid::Geometry::MDHistoDimension::m_numBins private
Number of bins.
Definition at line 138 of file MDHistoDimension.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDHistoDimension.h
Framework/Geometry/src/MDGeometry/MDHistoDimension.cpp