Mantid: Mantid::MDAlgorithms::MDNormSCD Class Reference
Mantid::MDAlgorithms::MDNormSCD Class Reference
MDNormSCD : Generate MD normalization for single crystal diffraction.
#include <MDNormSCD.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
MDNormSCD ()
Constructor.
const std::string name () const override
Algorithm's name for use in the GUI and help.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
SlicingAlgorithm ()
Constructor.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Member Functions
DataObjects::MDHistoWorkspace_sptr binInputWS ()
Runs the BinMD algorithm on the input to provide the output workspace All slicing algorithm properties are passed along.
void cacheDimensionXValues ()
Stores the X values from each H,K,L dimension as member variables.
void cacheInputs ()
Set up starting values for cached variables.
void calcIntegralsForIntersections (const std::vector< double > &xValues, const API::MatrixWorkspace &integrFlux, size_t sp, std::vector< double > &yValues) const
Linearly interpolate between the points in integrFlux at xValues and save the results in yValues.
void calculateIntersections (std::vector< std::array< double, 4 > > &intersections, const double theta, const double phi)
Calculate the points of intersection for the given detector with cuboid surrounding the detector position in HKL.
void calculateNormalization (const std::vector< coord_t > &otherValues, const Kernel::Matrix< coord_t > &affineTrans, uint16_t expInfoIndex)
Computed the normalization for the input workspace.
void createNormalizationWS (const DataObjects::MDHistoWorkspace &dataWS)
Create & cached the normalization workspace.
void exec () override
Execute the algorithm.
Kernel::Matrix< coord_t > findIntergratedDimensions (const std::vector< coord_t > &otherDimValues, bool &skipNormalization)
Checks the normalization workspace against the indices of the original dimensions.
std::vector< coord_t > getValuesFromOtherDimensions (bool &skipNormalization, uint16_t expInfoIndex=0) const
Retrieve logged values from non-HKL dimensions.
void init () override
Initialize the algorithm's properties.
std::string inputEnergyMode () const
Currently looks for the ConvertToMD algorithm in the history.
Private Attributes
std::string convention
ki-kf for Inelastic convention; kf-ki for Crystallography convention
bool m_accumulate {false}
internal flag to accumulate to an existing workspace
Kernel::V3D m_beamDir
Beam direction.
size_t m_hIdx
index of h,k,l dimensions in the output workspaces
bool m_hIntegrated
flag for integrated h,k,l dimensions
coord_t m_hmax
coord_t m_hmin
limits for h,k,l dimensions
std::vector< double > m_hX
cached X values along dimensions h,k,l
API::IMDEventWorkspace_sptr m_inputWS
Input workspace.
size_t m_kIdx
double m_kiMax
double m_kiMin
limits for momentum
bool m_kIntegrated
coord_t m_kmax
coord_t m_kmin
std::vector< double > m_kX
size_t m_lIdx
bool m_lIntegrated
coord_t m_lmax
coord_t m_lmin
std::vector< double > m_lX
DataObjects::MDHistoWorkspace_sptr m_normWS
Normalization workspace.
uint16_t m_numExptInfos
number of experiment infos
Mantid::Kernel::DblMatrix m_rubw
(2*PiRUBW)^-1
Kernel::V3D m_samplePos
Sample position.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
static std::string getDimensionChars ()
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
void createAlignedTransform ()
Using the parameters, create a coordinate transformation for aligned cuts.
void createGeneralTransform ()
Loads the dimensions and create the coordinate transform, using the inputs.
void createTransform ()
Read the algorithm properties and creates the appropriate transforms for slicing the MDEventWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getGeneralImplicitFunction (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getImplicitFunctionForChunk (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
void initSlicingProps ()
Initialise the properties.
void makeAlignedDimensionFromString (const std::string &str)
Generate a MDHistoDimension_sptr from a comma-sep string (for AlignedDim0, etc.) Must be called in order X,Y,Z,T.
void makeBasisVectorFromString (const std::string &str)
Generate the MDHistoDimension and basis vector for a given string from BasisVector0 etc.
void processGeneralTransformProperties ()
Reads the various Properties for the general (non-aligned) case and fills in members on the Algorithm for later use.
~SlicingAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::MDAlgorithms::SlicingAlgorithm
bool m_axisAligned
Set to true if the cut is aligned with the axes.
std::vector< Mantid::Kernel::VMD > m_bases
Basis vectors of the output dimensions, normalized to unity length.
std::vector< Mantid::Geometry::MDHistoDimension_sptr > m_binDimensions
Bin dimensions to actually use.
std::vector< double > m_binningScaling
Scaling factor to apply for each basis vector (to map to the bins).
std::vector< size_t > m_dimensionToBinFrom
Index of the dimension in the MDEW for the dimension in the output.
Mantid::Kernel::VMD m_inputMinPoint
Coordinates in the INPUT workspace corresponding to the minimum edge in all dimensions.
Mantid::API::IMDWorkspace_sptr m_intermediateWS
Intermediate original workspace.
Mantid::API::IMDWorkspace_sptr m_inWS
Input workspace.
std::vector< double > m_maxExtents
For non-aligned, the maximum coordinate extents in each OUTPUT dimension.
std::vector< double > m_minExtents
For non-aligned, the minimum coordinate extents in each OUTPUT dimension.
bool m_NormalizeBasisVectors
The NormalizeBasisVectors option.
std::vector< int > m_numBins
For non-aligned, the number of bins in each OUTPUT dimension.
Mantid::API::IMDWorkspace_sptr m_originalWS
Original (MDEventWorkspace) that inWS was based on.
size_t m_outD
Number of dimensions in the output (binned) workspace.
std::unique_ptr< API::CoordTransform > m_transform
Coordinate transformation to apply.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformFromIntermediate
Coordinate transformation to save in the output WS, from the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformFromOriginal
Coordinate transformation to save in the output workspace (original->binned)
std::vector< double > m_transformScaling
Scaling factor to apply for each basis vector to transfor to the output dimensions.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformToIntermediate
Coordinate transformation to save in the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformToOriginal
Coordinate transformation to save in the output workspace (binned->original)
Mantid::Kernel::VMD m_translation
Translation from the OUTPUT to the INPUT workspace i.e.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
MDNormSCD : Generate MD normalization for single crystal diffraction.
Definition at line 20 of file MDNormSCD.h.
Constructor & Destructor Documentation
MDNormSCD()
Mantid::MDAlgorithms::MDNormSCD::MDNormSCD ()
Constructor.
Definition at line 44 of file MDNormSCD.cpp.
Member Function Documentation
binInputWS()
MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNormSCD::binInputWS () private
Runs the BinMD algorithm on the input to provide the output workspace All slicing algorithm properties are passed along.
Returns
MDHistoWorkspace as a result of the binning
Definition at line 220 of file MDNormSCD.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), and Mantid::API::Algorithm::getProperties().
Referenced by exec().
cacheDimensionXValues()
void Mantid::MDAlgorithms::MDNormSCD::cacheDimensionXValues () private
Stores the X values from each H,K,L dimension as member variables.
Definition at line 349 of file MDNormSCD.cpp.
References m_hIdx, m_hIntegrated, m_hX, m_kIdx, m_kIntegrated, m_kX, m_lIdx, m_lIntegrated, m_lX, and m_normWS.
Referenced by exec().
cacheInputs()
void Mantid::MDAlgorithms::MDNormSCD::cacheInputs () private
Set up starting values for cached variables.
Definition at line 158 of file MDNormSCD.cpp.
References Mantid::API::Algorithm::getProperty(), inputEnergyMode(), m_beamDir, m_hmax, m_hmin, m_inputWS, m_kmax, m_kmin, m_lmax, m_lmin, m_samplePos, and Mantid::Kernel::normalize().
Referenced by exec().
calcIntegralsForIntersections()
void Mantid::MDAlgorithms::MDNormSCD::calcIntegralsForIntersections (const std::vector< double > & xValues, const API::MatrixWorkspace & integrFlux, size_t sp, std::vector< double > & yValues) const private
Linearly interpolate between the points in integrFlux at xValues and save the results in yValues.
Parameters
xValues :: X-values at which to interpolate
integrFlux :: A workspace with the spectra to interpolate
sp :: A workspace index for a spectrum in integrFlux to interpolate.
yValues :: A vector to save the results.
Definition at line 502 of file MDNormSCD.cpp.
References Mantid::API::MatrixWorkspace::x(), and Mantid::API::MatrixWorkspace::y().
Referenced by calculateNormalization().
calculateIntersections()
void Mantid::MDAlgorithms::MDNormSCD::calculateIntersections (std::vector< std::array< double, 4 > > & intersections, const double theta, const double phi) private
Calculate the points of intersection for the given detector with cuboid surrounding the detector position in HKL.
Parameters
intersections A list of intersections in HKL space
theta Polar angle withd detector
phi Azimuthal angle with detector
Definition at line 578 of file MDNormSCD.cpp.
References convention, fabs, m_hIntegrated, m_hmax, m_hmin, m_hX, m_kiMax, m_kiMin, m_kIntegrated, m_kmax, m_kmin, m_kX, m_lIntegrated, m_lmax, m_lmin, m_lX, m_rubw, Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by calculateNormalization().
calculateNormalization()
void Mantid::MDAlgorithms::MDNormSCD::calculateNormalization (const std::vector< coord_t > & otherValues, const Kernel::Matrix< coord_t > & affineTrans, uint16_t expInfoIndex) private
Computed the normalization for the input workspace.
Results are stored in m_normWS
Parameters
otherValues
affineTrans
expInfoIndex current experiment info index
Definition at line 380 of file MDNormSCD.cpp.
References Mantid::Kernel::AtomicOp(), calcIntegralsForIntersections(), calculateIntersections(), Mantid::Kernel::delta, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Matrix< T >::Invert(), m_accumulate, m_beamDir, m_inputWS, m_kiMax, m_kiMin, m_normWS, m_numExptInfos, m_rubw, m_samplePos, Mantid::Kernel::Matrix< T >::multiplyPoint(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, rhs, Mantid::Kernel::threadSafe(), and Mantid::Geometry::x.
Referenced by exec().
category()
const std::string Mantid::MDAlgorithms::MDNormSCD::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 53 of file MDNormSCD.cpp.
createNormalizationWS()
void Mantid::MDAlgorithms::MDNormSCD::createNormalizationWS (const DataObjects::MDHistoWorkspace & dataWS) private
Create & cached the normalization workspace.
Parameters
dataWS The binned workspace that will be used for the data
Definition at line 241 of file MDNormSCD.cpp.
References Mantid::DataObjects::MDHistoWorkspace::clone(), Mantid::API::Algorithm::getProperty(), m_accumulate, m_normWS, and tmp.
Referenced by exec().
exec()
void Mantid::MDAlgorithms::MDNormSCD::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 125 of file MDNormSCD.cpp.
References binInputWS(), cacheDimensionXValues(), cacheInputs(), calculateNormalization(), convention, createNormalizationWS(), findIntergratedDimensions(), Mantid::API::Algorithm::g_log, getValuesFromOtherDimensions(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_accumulate, m_normWS, m_numExptInfos, Mantid::API::NoNormalization, Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::Kernel::Logger::warning().
findIntergratedDimensions()
Kernel::Matrix< coord_t > Mantid::MDAlgorithms::MDNormSCD::findIntergratedDimensions (const std::vector< coord_t > & otherDimValues, bool & skipNormalization) private
Checks the normalization workspace against the indices of the original dimensions.
If not found, the corresponding dimension is integrated
Parameters
otherDimValues Values from non-HKL dimensions
skipNormalization [InOut] Sets the flag true if normalization values are outside of original inputs
Returns
Affine trasform matrix
Definition at line 292 of file MDNormSCD.cpp.
References m_hIdx, m_hIntegrated, m_hmax, m_hmin, m_kIdx, m_kIntegrated, m_kmax, m_kmin, m_lIdx, m_lIntegrated, m_lmax, m_lmin, m_normWS, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
Referenced by exec().
getValuesFromOtherDimensions()
std::vector< coord_t > Mantid::MDAlgorithms::MDNormSCD::getValuesFromOtherDimensions (bool & skipNormalization, uint16_t expInfoIndex = 0) const private
Retrieve logged values from non-HKL dimensions.
Parameters
skipNormalization [InOut] Updated to false if any values are outside range measured by input workspace
expInfoIndex current experiment info index
Returns
A vector of values from other dimensions to be include in normalized MD position calculation
Definition at line 261 of file MDNormSCD.cpp.
References m_inputWS, and value.
Referenced by exec().
init()
void Mantid::MDAlgorithms::MDNormSCD::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 67 of file MDNormSCD.cpp.
References Mantid::API::CommonBinsValidator::clone(), Mantid::API::Algorithm::declareProperty(), Mantid::MDAlgorithms::SlicingAlgorithm::getDimensionChars(), Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, and Mantid::Kernel::Strings::toString().
inputEnergyMode()
std::string Mantid::MDAlgorithms::MDNormSCD::inputEnergyMode () const private
Currently looks for the ConvertToMD algorithm in the history.
Returns
A string donating the energy transfer mode of the input workspace
Definition at line 190 of file MDNormSCD.cpp.
References history, and m_inputWS.
Referenced by cacheInputs().
name()
const std::string Mantid::MDAlgorithms::MDNormSCD::name () const override virtual
Algorithm's name for use in the GUI and help.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 62 of file MDNormSCD.cpp.
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::MDNormSCD::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 26 of file MDNormSCD.h.
summary()
const std::string Mantid::MDAlgorithms::MDNormSCD::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 56 of file MDNormSCD.cpp.
version()
int Mantid::MDAlgorithms::MDNormSCD::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 50 of file MDNormSCD.cpp.
Member Data Documentation
convention
std::string Mantid::MDAlgorithms::MDNormSCD::convention private
ki-kf for Inelastic convention; kf-ki for Crystallography convention
Definition at line 72 of file MDNormSCD.h.
Referenced by calculateIntersections(), and exec().
m_accumulate
bool Mantid::MDAlgorithms::MDNormSCD::m_accumulate {false} private
internal flag to accumulate to an existing workspace
Definition at line 74 of file MDNormSCD.h.
Referenced by calculateNormalization(), createNormalizationWS(), and exec().
m_beamDir
Kernel::V3D Mantid::MDAlgorithms::MDNormSCD::m_beamDir private
Beam direction.
Definition at line 70 of file MDNormSCD.h.
Referenced by cacheInputs(), and calculateNormalization().
m_hIdx
size_t Mantid::MDAlgorithms::MDNormSCD::m_hIdx private
index of h,k,l dimensions in the output workspaces
Definition at line 64 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and findIntergratedDimensions().
m_hIntegrated
bool Mantid::MDAlgorithms::MDNormSCD::m_hIntegrated private
flag for integrated h,k,l dimensions
Definition at line 58 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), calculateIntersections(), and findIntergratedDimensions().
m_hmax
coord_t Mantid::MDAlgorithms::MDNormSCD::m_hmax private
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_hmin
coord_t Mantid::MDAlgorithms::MDNormSCD::m_hmin private
limits for h,k,l dimensions
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_hX
std::vector<double> Mantid::MDAlgorithms::MDNormSCD::m_hX private
cached X values along dimensions h,k,l
Definition at line 66 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_inputWS
API::IMDEventWorkspace_sptr Mantid::MDAlgorithms::MDNormSCD::m_inputWS private
Input workspace.
Definition at line 54 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateNormalization(), getValuesFromOtherDimensions(), and inputEnergyMode().
m_kIdx
size_t Mantid::MDAlgorithms::MDNormSCD::m_kIdx private
Definition at line 64 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and findIntergratedDimensions().
m_kiMax
double Mantid::MDAlgorithms::MDNormSCD::m_kiMax private
Definition at line 62 of file MDNormSCD.h.
Referenced by calculateIntersections(), and calculateNormalization().
m_kiMin
double Mantid::MDAlgorithms::MDNormSCD::m_kiMin private
limits for momentum
Definition at line 62 of file MDNormSCD.h.
Referenced by calculateIntersections(), and calculateNormalization().
m_kIntegrated
bool Mantid::MDAlgorithms::MDNormSCD::m_kIntegrated private
Definition at line 58 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), calculateIntersections(), and findIntergratedDimensions().
m_kmax
coord_t Mantid::MDAlgorithms::MDNormSCD::m_kmax private
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_kmin
coord_t Mantid::MDAlgorithms::MDNormSCD::m_kmin private
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_kX
std::vector<double> Mantid::MDAlgorithms::MDNormSCD::m_kX private
Definition at line 66 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_lIdx
size_t Mantid::MDAlgorithms::MDNormSCD::m_lIdx private
Definition at line 64 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and findIntergratedDimensions().
m_lIntegrated
bool Mantid::MDAlgorithms::MDNormSCD::m_lIntegrated private
Definition at line 58 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), calculateIntersections(), and findIntergratedDimensions().
m_lmax
coord_t Mantid::MDAlgorithms::MDNormSCD::m_lmax private
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_lmin
coord_t Mantid::MDAlgorithms::MDNormSCD::m_lmin private
Definition at line 56 of file MDNormSCD.h.
Referenced by cacheInputs(), calculateIntersections(), and findIntergratedDimensions().
m_lX
std::vector<double> Mantid::MDAlgorithms::MDNormSCD::m_lX private
Definition at line 66 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), and calculateIntersections().
m_normWS
DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::MDNormSCD::m_normWS private
Normalization workspace.
Definition at line 52 of file MDNormSCD.h.
Referenced by cacheDimensionXValues(), calculateNormalization(), createNormalizationWS(), exec(), and findIntergratedDimensions().
m_numExptInfos
uint16_t Mantid::MDAlgorithms::MDNormSCD::m_numExptInfos private
number of experiment infos
Definition at line 76 of file MDNormSCD.h.
Referenced by calculateNormalization(), and exec().
m_rubw
Mantid::Kernel::DblMatrix Mantid::MDAlgorithms::MDNormSCD::m_rubw private
(2*PiRUBW)^-1
Definition at line 60 of file MDNormSCD.h.
Referenced by calculateIntersections(), and calculateNormalization().
m_samplePos
Kernel::V3D Mantid::MDAlgorithms::MDNormSCD::m_samplePos private
Sample position.
Definition at line 68 of file MDNormSCD.h.
Referenced by cacheInputs(), and calculateNormalization().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/MDNormSCD.h
Framework/MDAlgorithms/src/MDNormSCD.cpp