Mantid: Mantid::DataHandling::LoadGeometry Namespace Reference
Mantid::DataHandling::LoadGeometry Namespace Reference
Common methods for LoadInstrument.cpp and LoadEmptyInstrument.cpp.
Functions
bool isIDF (const std::string &filename)
Determine if the Geometry file type is IDF.
bool isNexus (const std::string &filename)
Determine if the Geometry file type is Nexus.
bool isNexus (const std::string &filename, const std::map< std::string, std::set< std::string > > &allEntries)
Determine if the Geometry file type is Nexus version that reuses the metadata container.
const std::vector< std::string > validExtensions ()
List allowed file extensions for geometry.
Detailed Description
Common methods for LoadInstrument.cpp and LoadEmptyInstrument.cpp.
Author
Neil Vaytet, ESS
Date
01/11/2018
Function Documentation
isIDF()
bool Mantid::DataHandling::LoadGeometry::isIDF (const std::string & filename)
Determine if the Geometry file type is IDF.
Definition at line 14 of file LoadGeometry.cpp.
References Mantid::Kernel::FileDescriptor::isXML().
Referenced by Mantid::DataHandling::LoadInstrument::exec().
isNexus() [1/2]
bool Mantid::DataHandling::LoadGeometry::isNexus (const std::string & filename)
Determine if the Geometry file type is Nexus.
Definition at line 23 of file LoadGeometry.cpp.
References Mantid::Kernel::NexusDescriptor::classTypeExists(), Mantid::Kernel::FileDescriptor::isAscii(), and Mantid::Kernel::NexusDescriptor::isReadable().
Referenced by Mantid::DataHandling::LoadInstrument::exec(), and Mantid::DataHandling::LoadEventNexus::runLoadInstrument().
isNexus() [2/2]
bool Mantid::DataHandling::LoadGeometry::isNexus (const std::string & filename, const std::map< std::string, std::set< std::string > > & allEntries)
Determine if the Geometry file type is Nexus version that reuses the metadata container.
Definition at line 33 of file LoadGeometry.cpp.
References Mantid::Kernel::FileDescriptor::isAscii(), and Mantid::Kernel::NexusDescriptor::isReadable().
validExtensions()
const std::vector< std::string > Mantid::DataHandling::LoadGeometry::validExtensions ()
List allowed file extensions for geometry.
Definition at line 45 of file LoadGeometry.cpp.
Referenced by Mantid::DataHandling::LoadEmptyInstrument::init(), and Mantid::DataHandling::LoadInstrument::init().