Mantid: Mantid::Kernel::Smoothing::detail Namespace Reference
Mantid::Kernel::Smoothing::detail Namespace Reference
Classes
struct ArithmeticAverager
Represents taking the arithmetic mean.
struct Averager
struct ErrorPropagationAverager
Represents propagating errors for values which had been arithmetically averaged.
struct GeometricAverager
Represents taking the geometric mean.
struct SumSquareAverager
Represents taking the root-mean-square averaege.
Functions
template<typename T >
std::vector< T > boxcarSmoothWithFunction (std::vector< T > const &input, unsigned int const numPoints, Averager< T > &averager)
Function Documentation
boxcarSmoothWithFunction()
template<typename T > std::vector< T > Mantid::Kernel::Smoothing::detail::boxcarSmoothWithFunction (std::vector< T > const & input, unsigned int const numPoints, Averager< T > & averager)
Definition at line 93 of file Smoothing.cpp.
References Mantid::Kernel::Smoothing::detail::Averager< T >::accumulate(), Mantid::Kernel::Smoothing::detail::Averager< T >::getAverage(), and Mantid::Kernel::Smoothing::detail::Averager< T >::separate().
Referenced by Mantid::Kernel::Smoothing::boxcarErrorSmooth(), Mantid::Kernel::Smoothing::boxcarRMSESmooth(), and Mantid::Kernel::Smoothing::boxcarSmooth().