Mantid: MantidQt::MantidWidgets::IWorkspaceDockView Class Reference
MantidQt::MantidWidgets::IWorkspaceDockView Class Reference abstract
#include <IWorkspaceDockView.h>
Public Types
enum class SaveFileType { Nexus , ASCII }
enum class SortCriteria { ByName , ByLastModified , ByMemorySize }
enum class SortDirection { Ascending , Descending }
Public Member Functions
virtual bool askUserYesNo (const std::string &caption, const std::string &message) const =0
virtual void clearView ()=0
virtual bool clearWorkspacesConfirmation () const =0
virtual void convertMDHistoToMatrixWorkspace ()=0
virtual void convertToMatrixWorkspace ()=0
virtual bool deleteConfirmation () const =0
virtual void deleteWorkspaces (const StringList &wsNames)=0
virtual void enableClearButton (bool enable)=0
virtual void enableDeletePrompt (bool enable)=0
virtual bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=true)=0
virtual void filterWorkspaces (const std::string &filterText)=0
virtual std::string getFilterText () const =0
virtual WorkspacePresenterWN_wptr getPresenterWeakPtr ()=0
virtual SaveFileType getSaveFileType () const =0
virtual Mantid::API::Workspace_sptr getSelectedWorkspace () const =0
virtual StringList getSelectedWorkspaceNames () const =0
virtual SortCriteria getSortCriteria () const =0
virtual SortDirection getSortDirection () const =0
virtual bool isPromptDelete () const =0
virtual void plotSpectrum (const std::string &type)=0
virtual void popupContextMenu ()=0
virtual void recordWorkspaceRename (const std::string &oldName, const std::string &newName)=0
virtual void refreshWorkspaces ()=0
virtual void saveToProgram ()=0
virtual void saveWorkspace (const std::string &wsName, const SaveFileType type)=0
virtual void saveWorkspaces (const StringList &wsNames)=0
virtual void showAlgorithmHistory ()=0
virtual void showBoxDataTable ()=0
virtual void showColourFillPlot ()=0
virtual void showCriticalUserMessage (const std::string &caption, const std::string &message) const =0
virtual void showDetectorsTable ()=0
virtual void showInstrumentView ()=0
virtual void showListData ()=0
virtual void showLiveDataDialog ()=0
virtual void showLoadDialog ()=0
virtual void showLogs ()=0
virtual void showMDPlot ()=0
virtual void showRenameDialog (const StringList &wsNames)=0
virtual void showSampleMaterialWindow ()=0
virtual void showSliceViewer ()=0
virtual void showSpectrumViewer ()=0
virtual void showTransposed ()=0
virtual void showWorkspaceData ()=0
virtual void sortWorkspaces (SortCriteria criteria, SortDirection direction)=0
virtual void updateTree (const std::map< std::string, Mantid::API::Workspace_sptr > &items)=0
virtual ~IWorkspaceDockView ()
Detailed Description
Author
Lamar Moore
Date
24-08-2016
Version
1.0
Definition at line 28 of file IWorkspaceDockView.h.
Member Enumeration Documentation
SaveFileType
enum class MantidQt::MantidWidgets::IWorkspaceDockView::SaveFileType strong
Enumerator
Nexus
ASCII
Definition at line 32 of file IWorkspaceDockView.h.
SortCriteria
enum class MantidQt::MantidWidgets::IWorkspaceDockView::SortCriteria strong
Enumerator
ByName
ByLastModified
ByMemorySize
Definition at line 31 of file IWorkspaceDockView.h.
SortDirection
enum class MantidQt::MantidWidgets::IWorkspaceDockView::SortDirection strong
Enumerator
Ascending
Descending
Definition at line 30 of file IWorkspaceDockView.h.
Constructor & Destructor Documentation
~IWorkspaceDockView()
virtual MantidQt::MantidWidgets::IWorkspaceDockView::~IWorkspaceDockView () inline virtual
Definition at line 34 of file IWorkspaceDockView.h.
Member Function Documentation
askUserYesNo()
virtual bool MantidQt::MantidWidgets::IWorkspaceDockView::askUserYesNo (const std::string & caption, const std::string & message) const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::groupWorkspaces().
clearView()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::clearView () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::workspacesCleared().
clearWorkspacesConfirmation()
virtual bool MantidQt::MantidWidgets::IWorkspaceDockView::clearWorkspacesConfirmation () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::clearWorkspaces().
convertMDHistoToMatrixWorkspace()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::convertMDHistoToMatrixWorkspace () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::convertMDHistoToMatrixWorkspace().
convertToMatrixWorkspace()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::convertToMatrixWorkspace () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::convertToMatrixWorkspace().
deleteConfirmation()
virtual bool MantidQt::MantidWidgets::IWorkspaceDockView::deleteConfirmation () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces().
deleteWorkspaces()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::deleteWorkspaces (const StringList & wsNames) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces().
enableClearButton()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::enableClearButton (bool enable) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::clearWorkspaces().
enableDeletePrompt()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::enableDeletePrompt (bool enable) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget, and MockWorkspaceDockView.
executeAlgorithmAsync()
virtual bool MantidQt::MantidWidgets::IWorkspaceDockView::executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait = true) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::clearUBMatrix().
filterWorkspaces()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::filterWorkspaces (const std::string & filterText) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::filterWorkspaces().
getFilterText()
virtual std::string MantidQt::MantidWidgets::IWorkspaceDockView::getFilterText () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::filterWorkspaces().
getPresenterWeakPtr()
virtual WorkspacePresenterWN_wptr MantidQt::MantidWidgets::IWorkspaceDockView::getPresenterWeakPtr () pure virtual
Implemented in MockWorkspaceDockView, and MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::init().
getSaveFileType()
virtual SaveFileType MantidQt::MantidWidgets::IWorkspaceDockView::getSaveFileType () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::saveSingleWorkspace().
getSelectedWorkspace()
virtual Mantid::API::Workspace_sptr MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspace () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::saveSingleWorkspace().
getSelectedWorkspaceNames()
virtual StringList MantidQt::MantidWidgets::IWorkspaceDockView::getSelectedWorkspaceNames () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::clearUBMatrix(), MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces(), MantidQt::MantidWidgets::WorkspacePresenter::groupWorkspaces(), MantidQt::MantidWidgets::WorkspacePresenter::renameWorkspace(), MantidQt::MantidWidgets::WorkspacePresenter::saveWorkspaceCollection(), and MantidQt::MantidWidgets::WorkspacePresenter::ungroupWorkspaces().
getSortCriteria()
virtual SortCriteria MantidQt::MantidWidgets::IWorkspaceDockView::getSortCriteria () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::sortWorkspaces().
getSortDirection()
virtual SortDirection MantidQt::MantidWidgets::IWorkspaceDockView::getSortDirection () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::sortWorkspaces().
isPromptDelete()
virtual bool MantidQt::MantidWidgets::IWorkspaceDockView::isPromptDelete () const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces().
plotSpectrum()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::plotSpectrum (const std::string & type) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrum(), MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrumAdvanced(), and MantidQt::MantidWidgets::WorkspacePresenter::plotSpectrumWithErrors().
popupContextMenu()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::popupContextMenu () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget, and MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::populateAndShowWorkspaceContextMenu().
recordWorkspaceRename()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::recordWorkspaceRename (const std::string & oldName, const std::string & newName) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::workspaceRenamed().
refreshWorkspaces()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::refreshWorkspaces () pure virtual
Implemented in MockWorkspaceDockView, and MantidQt::MantidWidgets::WorkspaceTreeWidget.
saveToProgram()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::saveToProgram () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::saveToProgram().
saveWorkspace()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::saveWorkspace (const std::string & wsName, const SaveFileType type) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::saveSingleWorkspace().
saveWorkspaces()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::saveWorkspaces (const StringList & wsNames) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::saveWorkspaceCollection().
showAlgorithmHistory()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showAlgorithmHistory () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showAlgorithmHistory().
showBoxDataTable()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showBoxDataTable () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showBoxDataTable().
showColourFillPlot()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showColourFillPlot () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showColourFillPlot().
showCriticalUserMessage()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showCriticalUserMessage (const std::string & caption, const std::string & message) const pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::deleteWorkspaces(), MantidQt::MantidWidgets::WorkspacePresenter::groupWorkspaces(), and MantidQt::MantidWidgets::WorkspacePresenter::ungroupWorkspaces().
showDetectorsTable()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showDetectorsTable () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showDetectorsTable().
showInstrumentView()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showInstrumentView () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showInstrumentView().
showListData()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showListData () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showListData().
showLiveDataDialog()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showLiveDataDialog () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::loadLiveData().
showLoadDialog()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showLoadDialog () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::loadWorkspace().
showLogs()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showLogs () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showLogs().
showMDPlot()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showMDPlot () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showMDPlot().
showRenameDialog()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showRenameDialog (const StringList & wsNames) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::renameWorkspace().
showSampleMaterialWindow()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showSampleMaterialWindow () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showSampleMaterialWindow().
showSliceViewer()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showSliceViewer () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showSliceViewer().
showSpectrumViewer()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showSpectrumViewer () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showSpectrumViewer().
showTransposed()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showTransposed () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showTransposed().
showWorkspaceData()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::showWorkspaceData () pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::showWorkspaceData().
sortWorkspaces()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::sortWorkspaces (SortCriteria criteria, SortDirection direction) pure virtual
Implemented in MantidQt::MantidWidgets::WorkspaceTreeWidget.
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::sortWorkspaces().
updateTree()
virtual void MantidQt::MantidWidgets::IWorkspaceDockView::updateTree (const std::map< std::string, Mantid::API::Workspace_sptr > & items) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspacePresenter::updateView(), and MantidQt::MantidWidgets::WorkspacePresenter::workspaceRenamed().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/IWorkspaceDockView.h