Mantid: Framework/PythonInterface/mantid/geometry/src/Exports/ComponentInfo.cpp File Reference
ComponentInfo.cpp File Reference
#include "MantidGeometry/Instrument/ComponentInfo.h"
#include "MantidGeometry/Objects/IObject.h"
#include "MantidKernel/Quat.h"
#include "MantidKernel/V3D.h"
#include "MantidPythonInterface/core/Converters/WrapWithNDArray.h"
#include "MantidPythonInterface/core/Policies/VectorToNumpy.h"
#include "MantidPythonInterface/geometry/ComponentInfoPythonIterator.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/reference_existing_object.hpp>
#include <boost/python/return_value_policy.hpp>
Functions
void export_ComponentInfo ()
Variables
Mantid::Kernel::V3D(ComponentInfo::* position)(const size_t) const = &ComponentInfo::position
Mantid::Kernel::Quat(ComponentInfo::* rotation)(const size_t) const = &ComponentInfo::rotation
void(ComponentInfo::* setPosition)(const size_t, const Mantid::Kernel::V3D &) = &ComponentInfo::setPosition
void(ComponentInfo::* setRotation)(const size_t, const Mantid::Kernel::Quat &) = &ComponentInfo::setRotation
Function Documentation
export_ComponentInfo()
void export_ComponentInfo ()
Definition at line 44 of file ComponentInfo.cpp.
References Mantid::Geometry::ComponentInfo::children(), Mantid::Geometry::ComponentInfo::componentsInSubtree(), Mantid::Geometry::ComponentInfo::detectorsInSubtree(), Mantid::Geometry::ComponentInfo::hasEquivalentSample(), Mantid::Geometry::ComponentInfo::hasEquivalentSource(), Mantid::Geometry::ComponentInfo::hasParent(), Mantid::Geometry::ComponentInfo::hasSample(), Mantid::Geometry::ComponentInfo::hasSource(), Mantid::Geometry::ComponentInfo::hasValidShape(), Mantid::Geometry::ComponentInfo::indexOfAny(), Mantid::Geometry::ComponentInfo::isDetector(), Mantid::Geometry::ComponentInfo::l1(), make_pyiterator(), Mantid::Geometry::ComponentInfo::name(), Mantid::Geometry::ComponentInfo::parent(), position, Mantid::Geometry::ComponentInfo::relativePosition(), Mantid::Geometry::ComponentInfo::relativeRotation(), Mantid::Geometry::ComponentInfo::root(), rotation, Mantid::Geometry::ComponentInfo::sample(), Mantid::Geometry::ComponentInfo::samplePosition(), Mantid::Geometry::ComponentInfo::scaleFactor(), setPosition, setRotation, Mantid::Geometry::ComponentInfo::setScaleFactor(), Mantid::Geometry::ComponentInfo::shape(), Mantid::Geometry::ComponentInfo::size(), Mantid::Geometry::ComponentInfo::source(), Mantid::Geometry::ComponentInfo::sourcePosition(), and Mantid::Geometry::ComponentInfo::uniqueName().
Variable Documentation
position
Mantid::Kernel::V3D(ComponentInfo::* position) (const size_t) const (const size_t) const = &ComponentInfo::position
Definition at line 35 of file ComponentInfo.cpp.
Referenced by export_ComponentInfo().
rotation
Mantid::Kernel::Quat(ComponentInfo::* rotation) (const size_t) const (const size_t) const = &ComponentInfo::rotation
Definition at line 37 of file ComponentInfo.cpp.
Referenced by Mantid::API::applyRectangularDetectorScaleToComponentInfo(), Mantid::DataObjects::ScanningWorkspaceBuilder::buildRelativeRotationsForScans(), Mantid::Geometry::ComponentInfo::componentBoundingBox(), ComponentCreationHelper::createCuboid(), Mantid::DataHandling::SetSample::createFlatPlateXML(), Mantid::DataHandling::RotateInstrumentComponent::exec(), export_ComponentInfo(), export_DetectorInfo(), Mantid::Geometry::ParameterMap::getCachedRotation(), Mantid::DataHandling::SampleEnvironmentSpecParser::loadMeshFromSTL(), Mantid::DataHandling::LoadILLPolarizedDiffraction::moveTwoTheta(), Mantid::DataHandling::LoadILLDiffraction::moveTwoThetaZero(), Mantid::DataHandling::LoadILLReflectometry::placeDetector(), Mantid::DataHandling::LoadSwans::placeDetectorInSpace(), Mantid::Geometry::ParameterMap::setCachedRotation(), and Mantid::Geometry::DetectorInfo::setRotation().
setPosition
void(ComponentInfo::* setPosition) (const size_t, const Mantid::Kernel::V3D &) (const size_t, const Mantid::Kernel::V3D &) = &ComponentInfo::setPosition
Definition at line 39 of file ComponentInfo.cpp.
Referenced by Mantid::Geometry::BraggScattererInCrystalStructure::afterPropertySet(), export_ComponentInfo(), MantidQt::MantidWidgets::InputControllerDraw::mouseMoveEvent(), and MantidQt::MantidWidgets::InputControllerDraw::mousePressEvent().
setRotation
void(ComponentInfo::* setRotation) (const size_t, const Mantid::Kernel::Quat &) (const size_t, const Mantid::Kernel::Quat &) = &ComponentInfo::setRotation
Definition at line 41 of file ComponentInfo.cpp.
Referenced by export_ComponentInfo().