Mantid: ICat4::ns1__publication Class Reference
ICat4::ns1__publication Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__publication ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * doi
std::string * fullReference
ns1__investigation * investigation
std::string * repository
std::string * repositoryId
std::string * url
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2124 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__publication()
ICat4::ns1__publication::ns1__publication () inline
Definition at line 2140 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__publication::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9437 of file ICat4C.cpp.
References doi, fullReference, investigation, repository, repositoryId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and url.
Referenced by ICat4::soap_in_ns1__publication(), ICat4::soap_new_req_ns1__publication(), and ICat4::soap_new_set_ns1__publication().
soap_get()
void * ICat4::ns1__publication::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9621 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__publication().
soap_in()
void * ICat4::ns1__publication::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9498 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__publication().
Referenced by ICat4::soap_in_ns1__publication().
soap_out()
int ICat4::ns1__publication::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9463 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__publication().
Referenced by soap_put().
soap_put()
int ICat4::ns1__publication::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9614 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__publication.
soap_serialize()
void ICat4::ns1__publication::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9449 of file ICat4C.cpp.
References doi, fullReference, investigation, repository, repositoryId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTostd__string(), and url.
Referenced by ICat4::soap_serialize_PointerTons1__parameterType().
soap_type()
int ICat4::ns1__publication::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2133 of file ICat4Stub.h.
Member Data Documentation
doi
std::string* ICat4::ns1__publication::doi
Definition at line 2126 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
fullReference
std::string* ICat4::ns1__publication::fullReference
Definition at line 2127 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigation
ns1__investigation* ICat4::ns1__publication::investigation
Definition at line 2128 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
repository
std::string* ICat4::ns1__publication::repository
Definition at line 2129 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
repositoryId
std::string* ICat4::ns1__publication::repositoryId
Definition at line 2130 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
url
std::string* ICat4::ns1__publication::url
Definition at line 2131 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp