Mantid: MantidQt::MantidWidgets::MantidWSIndexDialog Class Reference
MantidQt::MantidWidgets::MantidWSIndexDialog Class Reference
#include <MantidWSIndexDialog.h>
Public Member Functions
QMultiMap< QString, std::set< int > > getPlots () const
Returns the QMultiMap that contains all the workspaces that are to be plotted, mapped to the set of workspace indices.
MantidWSIndexWidget::UserInput getSelections ()
Returns a structure holding all of the selected options.
bool is1DPlotSelected () const
Returns whether the waterfall option has been selected.
bool isContourPlotSelected () const
Returns whether surface plot is selected.
bool isErrorBarsSelected () const
Returns whether error bars have been selected.
bool isSurfacePlotSelected () const
Returns whether surface plot is selected.
bool isTiledPlotSelected () const
Returns whether the tiled plot option has been selected.
bool isWaterfallPlotSelected () const
Returns whether the waterfall option has been selected.
MantidWSIndexDialog (QWidget *parent, const Qt::WindowFlags &flags, const QList< QString > &wsNames, const bool showWaterfallOption=false, const bool showPlotAll=true, const bool showTiledOption=false, const bool isAdvanced=false)
Constructor - has a list of the names of workspaces to be plotted.
Private Slots
void plot ()
Called when the OK button is pressed.
void plotAll ()
Called when the "Plot All" button is pressed.
Private Member Functions
void init (bool isAdvanced)
Initializes the layout of the dialog.
void initButtons ()
Initializes the layout of the buttons.
Private Attributes
QHBoxLayout * m_buttonBox
QPushButton * m_cancelButton
QPushButton * m_okButton
Qt objects.
QVBoxLayout * m_outer
bool m_plotAll
Do we allow the display of the "Plot all" button.
QPushButton * m_plotAllButton
MantidWSIndexWidget m_widget
Detailed Description
Definition at line 382 of file MantidWSIndexDialog.h.
Constructor & Destructor Documentation
MantidWSIndexDialog()
MantidQt::MantidWidgets::MantidWSIndexDialog::MantidWSIndexDialog (QWidget * parent, const Qt::WindowFlags & flags, const QList< QString > & wsNames, const bool showWaterfallOption = false, const bool showPlotAll = true, const bool showTiledOption = false, const bool isAdvanced = false)
Constructor - has a list of the names of workspaces to be plotted.
Construct an object of this type.
Parameters
parent :: The MantidUI area
flags :: Window flags that are passed to the QDialog constructor
wsNames :: the names of the workspaces to be plotted
showWaterfallOption :: If true the waterfall checkbox is created
showPlotAll :: If true the "Plot all" button is created
showTiledOption :: If true the "Tiled" option is created
isAdvanced :: true if advanced plotting dialog is created
Definition at line 775 of file MantidWSIndexDialog.cpp.
References init().
Member Function Documentation
getPlots()
QMultiMap< QString, std::set< int > > MantidQt::MantidWidgets::MantidWSIndexDialog::getPlots () const
Returns the QMultiMap that contains all the workspaces that are to be plotted, mapped to the set of workspace indices.
Returns the user-selected plots from the widget.
Returns
Plots selected by user
Definition at line 794 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::getPlots(), and m_widget.
getSelections()
MantidWSIndexWidget::UserInput MantidQt::MantidWidgets::MantidWSIndexDialog::getSelections ()
Returns a structure holding all of the selected options.
Returns the user-selected options.
Returns
Struct containing user options
Definition at line 788 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::getSelections(), and m_widget.
Referenced by MantidQt::MantidWidgets::MantidTreeWidget::chooseSpectrumFromSelected().
init()
void MantidQt::MantidWidgets::MantidWSIndexDialog::init (bool isAdvanced) private
Initializes the layout of the dialog.
Definition at line 856 of file MantidWSIndexDialog.cpp.
References initButtons(), m_outer, and m_widget.
Referenced by MantidWSIndexDialog().
initButtons()
void MantidQt::MantidWidgets::MantidWSIndexDialog::initButtons () private
Initializes the layout of the buttons.
Definition at line 869 of file MantidWSIndexDialog.cpp.
References m_buttonBox, m_cancelButton, m_okButton, m_outer, m_plotAll, m_plotAllButton, plot(), and plotAll().
Referenced by init().
is1DPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::is1DPlotSelected () const
Returns whether the waterfall option has been selected.
Whether the user selected the simple 1D plot.
Returns
True if waterfall plot selected
Definition at line 800 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::is1DPlotSelected(), and m_widget.
isContourPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::isContourPlotSelected () const
Returns whether surface plot is selected.
Whether the user selected the surface plot.
Returns
True if surface plot selected
Definition at line 824 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::isContourPlotSelected(), and m_widget.
isErrorBarsSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::isErrorBarsSelected () const
Returns whether error bars have been selected.
Whether the user selected error bars.
Returns
True if error bars selected
Definition at line 830 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::isErrorBarsSelected(), and m_widget.
isSurfacePlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::isSurfacePlotSelected () const
Returns whether surface plot is selected.
Whether the user selected the surface plot.
Returns
True if surface plot selected
Definition at line 818 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::isSurfacePlotSelected(), and m_widget.
isTiledPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::isTiledPlotSelected () const
Returns whether the tiled plot option has been selected.
Whether the user selected the "tiled" plot.
Returns
True if tiled plot selected
Definition at line 812 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::isTiledPlotSelected(), and m_widget.
isWaterfallPlotSelected()
bool MantidQt::MantidWidgets::MantidWSIndexDialog::isWaterfallPlotSelected () const
Returns whether the waterfall option has been selected.
Whether the user selected the "waterfall" plot.
Returns
True if waterfall plot selected
Definition at line 806 of file MantidWSIndexDialog.cpp.
References MantidQt::MantidWidgets::MantidWSIndexWidget::isWaterfallPlotSelected(), and m_widget.
plot
void MantidQt::MantidWidgets::MantidWSIndexDialog::plot () private slot
Called when the OK button is pressed.
Called when OK button pressed.
Definition at line 838 of file MantidWSIndexDialog.cpp.
References m_widget, and MantidQt::MantidWidgets::MantidWSIndexWidget::plotRequested().
Referenced by initButtons().
plotAll
void MantidQt::MantidWidgets::MantidWSIndexDialog::plotAll () private slot
Called when the "Plot All" button is pressed.
Called when "Plot all" button pressed.
Definition at line 847 of file MantidWSIndexDialog.cpp.
References m_widget, and MantidQt::MantidWidgets::MantidWSIndexWidget::plotAllRequested().
Referenced by initButtons().
Member Data Documentation
m_buttonBox
QHBoxLayout* MantidQt::MantidWidgets::MantidWSIndexDialog::m_buttonBox private
Definition at line 424 of file MantidWSIndexDialog.h.
Referenced by initButtons().
m_cancelButton
QPushButton * MantidQt::MantidWidgets::MantidWSIndexDialog::m_cancelButton private
Definition at line 423 of file MantidWSIndexDialog.h.
Referenced by initButtons().
m_okButton
QPushButton* MantidQt::MantidWidgets::MantidWSIndexDialog::m_okButton private
Qt objects.
Definition at line 423 of file MantidWSIndexDialog.h.
Referenced by initButtons().
m_outer
QVBoxLayout* MantidQt::MantidWidgets::MantidWSIndexDialog::m_outer private
Definition at line 425 of file MantidWSIndexDialog.h.
Referenced by init(), and initButtons().
m_plotAll
bool MantidQt::MantidWidgets::MantidWSIndexDialog::m_plotAll private
Do we allow the display of the "Plot all" button.
Definition at line 421 of file MantidWSIndexDialog.h.
Referenced by initButtons().
m_plotAllButton
QPushButton * MantidQt::MantidWidgets::MantidWSIndexDialog::m_plotAllButton private
Definition at line 423 of file MantidWSIndexDialog.h.
Referenced by initButtons().
m_widget
MantidWSIndexWidget MantidQt::MantidWidgets::MantidWSIndexDialog::m_widget private
Definition at line 415 of file MantidWSIndexDialog.h.
Referenced by getPlots(), getSelections(), init(), is1DPlotSelected(), isContourPlotSelected(), isErrorBarsSelected(), isSurfacePlotSelected(), isTiledPlotSelected(), isWaterfallPlotSelected(), plot(), and plotAll().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidWSIndexDialog.h
qt/widgets/common/src/MantidWSIndexDialog.cpp