Mantid: Mantid::Geometry::NiggliCell Class Reference
Mantid::Geometry::NiggliCell Class Reference
Class to implement UB matrix.
#include <Geometry/Crystal/NiggliCell.h>
Public Member Functions
NiggliCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true), const int angleunit=angDegrees)
Constructor.
NiggliCell (const double _a, const double _b, const double _c, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
Constructor.
NiggliCell (const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
Default constructor.
NiggliCell (const UnitCell &uc, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
UnitCell constructor.
Public Member Functions inherited from Mantid::Geometry::UnitCell
double a () const
Get lattice parameter.
double a (int nd) const
Get lattice parameter a1-a3 as function of index (0-2)
double a1 () const
Get lattice parameter.
double a2 () const
Get lattice parameter.
double a3 () const
Get lattice parameter.
double alpha () const
Get lattice parameter.
double alpha1 () const
Get lattice parameter.
double alpha2 () const
Get lattice parameter.
double alpha3 () const
Get lattice parameter.
double alphastar () const
Get reciprocal lattice parameter.
double astar () const
Get reciprocal lattice parameter.
double b () const
Get lattice parameter.
double b1 () const
Get reciprocal lattice parameter.
double b2 () const
Get reciprocal lattice parameter.
double b3 () const
Get reciprocal lattice parameter.
double beta () const
Get lattice parameter.
double beta1 () const
Get reciprocal lattice parameter.
double beta2 () const
Get reciprocal lattice parameter.
double beta3 () const
Get reciprocal lattice parameter.
double betastar () const
Get reciprocal lattice parameter.
double bstar () const
Get reciprocal lattice parameter.
double c () const
Get lattice parameter.
double cstar () const
Get reciprocal lattice parameter.
double d (const Kernel::V3D &hkl) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double d (double h, double k, double l) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double dstar (const Kernel::V3D &hkl) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double dstar (double h, double k, double l) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double errora () const
Get lattice parameter error.
double erroralpha (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorb () const
Get lattice parameter error.
double errorbeta (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorc () const
Get lattice parameter error.
double errorgamma (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorvolume () const
Get lattice parameter error.
double gamma () const
Get lattice parameter.
double gammastar () const
Get reciprocal lattice parameter.
const Kernel::DblMatrix & getB () const
Get the B-matrix.
const Kernel::DblMatrix & getBinv () const
Get the inverse of the B-matrix.
bool getCrossTerm () const
Get cross term boolean.
double getdh (int j) const
Get modulation vectors for satellites.
double getdherr (int j) const
Get error of modulation vectors for satellites.
double getdk (int j) const
Get modulation vectors for satellites.
double getdkerr (int j) const
Get error of modulation vectors for satellites.
double getdl (int j) const
Get modulation vectors for satellites.
double getdlerr (int j) const
Get error of modulation vectors for satellites.
const Kernel::DblMatrix & getG () const
Get the metric tensor.
const Kernel::DblMatrix & getGstar () const
Get the reciprocal metric tensor.
int getMaxOrder () const
Get max order.
const Kernel::DblMatrix & getModHKL () const
Get modulation vectors for satellites.
const Kernel::V3D getModVec (int j) const
Get modulation vectors for satellites.
const Kernel::V3D getVecErr (int j) const
Get errors for modulation vectors for satellites.
bool operator!= (const UnitCell &other) const
bool operator== (const UnitCell &other) const
virtual void recalculateFromGstar (const Kernel::Matrix< double > &NewGstar)
Recalculate lattice from reciprocal metric tensor (Gstar=transpose(UB)*UB)
double recAngle (double h1, double k1, double l1, double h2, double k2, double l2, const int angleunit=angDegrees) const
Calculate the angle in degrees or radians between two reciprocal vectors (h1,k1,l1) and (h2,k2,l2)
double recVolume () const
Volume of the reciprocal lattice.
void set (double _a, double _b, double _c, double _alpha, double _beta, double _gamma, const int angleunit=angDegrees)
Set lattice parameters.
void seta (double _a)
Set lattice parameter.
void setalpha (double _alpha, const int angleunit=angDegrees)
Set lattice parameter.
void setb (double _b)
Set lattice parameter.
void setbeta (double _beta, const int angleunit=angDegrees)
Set lattice parameter.
void setc (double _c)
Set lattice parameter.
void setCrossTerm (bool CT)
Set modulation vectors for satellites.
void setError (double _aerr, double _berr, double _cerr, double _alphaerr, double _betaerr, double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter errors.
void setErrora (double _aerr)
Set lattice parameter error.
void setErroralpha (double _alphaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorb (double _berr)
Set lattice parameter error.
void setErrorbeta (double _betaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorc (double _cerr)
Set lattice parameter error.
void setErrorgamma (double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorModHKL (const Kernel::DblMatrix &newErrorModHKL)
Set modulation vectors for satellites.
void setErrorModHKL (double _dh1err, double _dk1err, double _dl1err, double _dh2err, double _dk2err, double _dl2err, double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setgamma (double _gamma, const int angleunit=angDegrees)
Set lattice parameter.
void setMaxOrder (int MaxO)
Set modulation vectors for satellites.
void setModerr (int i, double _dherr, double _dkerr, double _dlerr)
Set modulation vectors for satellites.
void setModerr1 (double _dh1err, double _dk1err, double _dl1err)
Set modulation vectors for satellites.
void setModerr2 (double _dh2err, double _dk2err, double _dl2err)
Set modulation vectors for satellites.
void setModerr3 (double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setModHKL (const Kernel::DblMatrix &newModHKL)
Set modulation vectors for satellites.
void setModHKL (double _dh1, double _dk1, double _dl1, double _dh2, double _dk2, double _dl2, double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
void setModVec1 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec1 (double _dh1, double _dk1, double _dl1)
Set modulation vectors for satellites.
void setModVec2 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec2 (double _dh2, double _dk2, double _dl2)
Set modulation vectors for satellites.
void setModVec3 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec3 (double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
UnitCell ()
Default constructor.
UnitCell (const double _a, const double _b, const double _c)
Constructor.
UnitCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const int angleunit=angDegrees)
Constructor.
double volume () const
Volume of the direct unit-cell.
virtual ~UnitCell ()=default
Static Public Member Functions
static bool HasNiggliAngles (const Kernel::V3D &a_dir, const Kernel::V3D &b_dir, const Kernel::V3D &c_dir, double epsilon)
Check if a,b,c cell has angles satifying Niggli condition within epsilon.
static bool MakeNiggliUB (const Kernel::DblMatrix &UB, Kernel::DblMatrix &newUB)
Construct a newUB corresponding to a Niggli cell from the given UB.
Private Attributes
Kernel::DblMatrix U
Kernel::DblMatrix UB
Additional Inherited Members
Protected Member Functions inherited from Mantid::Geometry::UnitCell
void calculateB ()
Private function to calculate B matrix.
void calculateG ()
void calculateGstar ()
Private function to calculate Gstar matrix.
void calculateReciprocalLattice ()
Private function to calculate reciprocal lattice parameters.
virtual void recalculate ()
Private function, called at initialization or whenever lattice parameters are changed.
Protected Attributes inherited from Mantid::Geometry::UnitCell
Kernel::DblMatrix B
B matrix for a right-handed coordinate system, in Busing-Levy convention.
Kernel::DblMatrix Binv
Inverse of the B matrix.
bool CrossTerm
std::vector< double > da
Lattice parameter a,b,c,alpha,beta,gamma (in \(\mbox{ \AA } \) and radians)
std::vector< double > errorda
Error in lattice parameters (in \(\mbox{ \AA } \) and radians)
Kernel::DblMatrix errorModHKL
Kernel::DblMatrix G
Metric tensor.
Kernel::DblMatrix Gstar
Reciprocal lattice tensor.
int MaxOrder
Kernel::DblMatrix ModHKL
std::vector< double > ra
Reciprocal lattice parameters (in \(\mbox{ \AA }^{-1} \) and radians)
Detailed Description
Class to implement UB matrix.
See documentation about UB matrix in the Mantid repository.
Author
Andrei Savici, SNS, ORNL
Date
2011-04-15
Definition at line 21 of file NiggliCell.h.
Constructor & Destructor Documentation
NiggliCell() [1/4]
Mantid::Geometry::NiggliCell::NiggliCell (const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
Default constructor.
Parameters
Umatrix :: orientation matrix U. By default this will be identity matrix
Definition at line 79 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Kernel::Matrix< T >::isRotation(), U, and UB.
NiggliCell() [2/4]
Mantid::Geometry::NiggliCell::NiggliCell (const double _a, const double _b, const double _c, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
Constructor.
Parameters
_a :: lattice parameter \(a \) with \(\alpha = \beta = \gamma = 90^\circ \)
_b :: lattice parameter \(b \) with \(\alpha = \beta = \gamma = 90^\circ \)
_c :: lattice parameter \(c \) with \(\alpha = \beta = \gamma = 90^\circ \)
Umatrix :: orientation matrix U
Definition at line 96 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Kernel::Matrix< T >::isRotation(), U, and UB.
NiggliCell() [3/4]
Mantid::Geometry::NiggliCell::NiggliCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true), const int angleunit = angDegrees)
Constructor.
Parameters
_a :: lattice parameter \(a \)
_b :: lattice parameter \(b \)
_c :: lattice parameter \(c \)
_alpha :: lattice parameter \(\alpha \)
_beta :: lattice parameter \(\beta \)
_gamma :: lattice parameter \(\gamma \)
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Umatrix :: orientation matrix U
Definition at line 115 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Kernel::Matrix< T >::isRotation(), U, and UB.
NiggliCell() [4/4]
Mantid::Geometry::NiggliCell::NiggliCell (const UnitCell & uc, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
UnitCell constructor.
Parameters
uc :: UnitCell
Umatrix :: orientation matrix U. By default this will be identity matrix
Definition at line 129 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Kernel::Matrix< T >::isRotation(), U, and UB.
Member Function Documentation
HasNiggliAngles()
bool Mantid::Geometry::NiggliCell::HasNiggliAngles (const Kernel::V3D & a_dir, const Kernel::V3D & b_dir, const Kernel::V3D & c_dir, double epsilon) static
Check if a,b,c cell has angles satifying Niggli condition within epsilon.
Specifically, check if all angles are strictly less than 90 degrees, or all angles are greater than or equal to 90 degrees. The inequality requirements are relaxed by an amount specified by the paramter epsilon to accommodate some experimental and/or rounding error in the calculated angles.
Parameters
a_dir Vector in the direction of the real cell edge vector 'a'
b_dir Vector in the direction of the real cell edge vector 'b'
c_dir Vector in the direction of the real cell edge vector 'c'
epsilon Tolerance (in degrees) around 90 degrees. For example an angle theta will be considered strictly less than 90 degrees, if it is less than 90+epsilon.
Returns
true if all angles are less than 90 degrees, or if all angles are greater than or equal to 90 degrees.
Definition at line 154 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::alpha(), Mantid::Kernel::V3D::angle(), Mantid::Geometry::UnitCell::beta(), and Mantid::Geometry::UnitCell::gamma().
Referenced by MakeNiggliUB().
MakeNiggliUB()
bool Mantid::Geometry::NiggliCell::MakeNiggliUB (const Kernel::DblMatrix & UB, Kernel::DblMatrix & newUB) static
Construct a newUB corresponding to a Niggli cell from the given UB.
Try to find a UB that is equivalent to the original UB, but corresponds to a Niggli reduced cell with the smallest sum of edge lengths and with angles that are farthest from 90 degrees.
Parameters
UB The original UB
newUB Returns the newUB
Returns
True if a possibly constructive change was made and newUB has been set to a new matrix. It returns false if no constructive change was found and newUB is just set to the original UB.
Definition at line 183 of file NiggliCell.cpp.
References Mantid::Geometry::UnitCell::a(), Mantid::Geometry::UnitCell::b(), Mantid::Geometry::UnitCell::c(), Mantid::Geometry::CompareABCsum(), Mantid::Geometry::CompareDiffFrom90(), Mantid::Kernel::V3D::compareMagnitude(), Mantid::Kernel::V3D::cross_prod(), fabs, Mantid::Geometry::OrientedLattice::GetABC(), Mantid::Geometry::OrientedLattice::GetUB(), HasNiggliAngles(), Mantid::Kernel::V3D::norm(), Mantid::Kernel::V3D::scalar_prod(), and UB.
Referenced by Mantid::Geometry::IndexingUtils::Find_UB(), and Mantid::Geometry::IndexingUtils::Find_UB().
Member Data Documentation
U
Kernel::DblMatrix Mantid::Geometry::NiggliCell::U private
Definition at line 43 of file NiggliCell.h.
Referenced by NiggliCell(), NiggliCell(), NiggliCell(), and NiggliCell().
UB
Kernel::DblMatrix Mantid::Geometry::NiggliCell::UB private
Definition at line 44 of file NiggliCell.h.
Referenced by MakeNiggliUB(), NiggliCell(), NiggliCell(), NiggliCell(), and NiggliCell().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/NiggliCell.h
Framework/Geometry/src/Crystal/NiggliCell.cpp