Mantid: Mantid::MDAlgorithms::BinMD Class Reference
Mantid::MDAlgorithms::BinMD Class Reference
Take a MDEventWorkspace and bin it to a dense histogram in a MDHistoWorkspace.
#include <BinMD.h>
Public Member Functions
BinMD ()
Constructor.
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
SlicingAlgorithm ()
Constructor.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
template<typename MDE , size_t nd>
void binByIterating (typename DataObjects::MDEventWorkspace< MDE, nd >::sptr ws)
Helper method.
template<typename MDE , size_t nd>
void binMDBox (DataObjects::MDBox< MDE, nd > *box, const size_t *const chunkMin, const size_t *const chunkMax)
Method to bin a single MDBox.
void exec () override
Run the algorithm.
void init () override
Initialise the properties.
Private Attributes
signal_t * errors
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > implicitFunction
ImplicitFunction used.
std::vector< size_t > indexMultiplier
Cached values for speed up.
bool m_accumulate {false}
signal_t * numEvents
Mantid::DataObjects::MDHistoWorkspace_sptr outWS
The output MDHistoWorkspace.
std::unique_ptr< Mantid::API::Progress > prog = nullptr
Progress reporting.
signal_t * signals
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
static std::string getDimensionChars ()
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::MDAlgorithms::SlicingAlgorithm
void createAlignedTransform ()
Using the parameters, create a coordinate transformation for aligned cuts.
void createGeneralTransform ()
Loads the dimensions and create the coordinate transform, using the inputs.
void createTransform ()
Read the algorithm properties and creates the appropriate transforms for slicing the MDEventWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getGeneralImplicitFunction (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getImplicitFunctionForChunk (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
void initSlicingProps ()
Initialise the properties.
void makeAlignedDimensionFromString (const std::string &str)
Generate a MDHistoDimension_sptr from a comma-sep string (for AlignedDim0, etc.) Must be called in order X,Y,Z,T.
void makeBasisVectorFromString (const std::string &str)
Generate the MDHistoDimension and basis vector for a given string from BasisVector0 etc.
void processGeneralTransformProperties ()
Reads the various Properties for the general (non-aligned) case and fills in members on the Algorithm for later use.
~SlicingAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::MDAlgorithms::SlicingAlgorithm
bool m_axisAligned
Set to true if the cut is aligned with the axes.
std::vector< Mantid::Kernel::VMD > m_bases
Basis vectors of the output dimensions, normalized to unity length.
std::vector< Mantid::Geometry::MDHistoDimension_sptr > m_binDimensions
Bin dimensions to actually use.
std::vector< double > m_binningScaling
Scaling factor to apply for each basis vector (to map to the bins).
std::vector< size_t > m_dimensionToBinFrom
Index of the dimension in the MDEW for the dimension in the output.
Mantid::Kernel::VMD m_inputMinPoint
Coordinates in the INPUT workspace corresponding to the minimum edge in all dimensions.
Mantid::API::IMDWorkspace_sptr m_intermediateWS
Intermediate original workspace.
Mantid::API::IMDWorkspace_sptr m_inWS
Input workspace.
std::vector< double > m_maxExtents
For non-aligned, the maximum coordinate extents in each OUTPUT dimension.
std::vector< double > m_minExtents
For non-aligned, the minimum coordinate extents in each OUTPUT dimension.
bool m_NormalizeBasisVectors
The NormalizeBasisVectors option.
std::vector< int > m_numBins
For non-aligned, the number of bins in each OUTPUT dimension.
Mantid::API::IMDWorkspace_sptr m_originalWS
Original (MDEventWorkspace) that inWS was based on.
size_t m_outD
Number of dimensions in the output (binned) workspace.
std::unique_ptr< API::CoordTransform > m_transform
Coordinate transformation to apply.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformFromIntermediate
Coordinate transformation to save in the output WS, from the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformFromOriginal
Coordinate transformation to save in the output workspace (original->binned)
std::vector< double > m_transformScaling
Scaling factor to apply for each basis vector to transfor to the output dimensions.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformToIntermediate
Coordinate transformation to save in the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformToOriginal
Coordinate transformation to save in the output workspace (binned->original)
Mantid::Kernel::VMD m_translation
Translation from the OUTPUT to the INPUT workspace i.e.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Take a MDEventWorkspace and bin it to a dense histogram in a MDHistoWorkspace.
This is principally used for visualization.
The output workspace may have fewer dimensions than the input MDEventWorkspace.
Author
Janik Zikovsky
Date
2011-03-29 11:28:06.048254
Definition at line 37 of file BinMD.h.
Constructor & Destructor Documentation
BinMD()
Mantid::MDAlgorithms::BinMD::BinMD ()
Constructor.
Definition at line 38 of file BinMD.cpp.
Member Function Documentation
binByIterating()
template<typename MDE , size_t nd> void Mantid::MDAlgorithms::BinMD::binByIterating (typename DataObjects::MDEventWorkspace< MDE, nd >::sptr ws) private
Helper method.
Perform binning by iterating through every event and placing them in the output workspace.
Parameters
ws :: MDEventWorkspace of the given type.
Definition at line 219 of file BinMD.cpp.
References binMDBox(), Mantid::Geometry::d, Mantid::Kernel::Logger::debug(), errors, Mantid::API::Algorithm::g_log, Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getBox(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getBoxController(), Mantid::MDAlgorithms::SlicingAlgorithm::getImplicitFunctionForChunk(), Mantid::API::Algorithm::getProperty(), implicitFunction, indexMultiplier, m_accumulate, Mantid::MDAlgorithms::SlicingAlgorithm::m_binDimensions, Mantid::API::Algorithm::m_cancel, Mantid::MDAlgorithms::SlicingAlgorithm::m_outD, numEvents, outWS, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_GET_MAX_THREADS, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, prog, signals, and Mantid::API::IMDNode::sortObjByID().
Referenced by exec().
binMDBox()
template<typename MDE , size_t nd> void Mantid::MDAlgorithms::BinMD::binMDBox (DataObjects::MDBox< MDE, nd > * box, const size_t *const chunkMin, const size_t *const chunkMax) inline private
Method to bin a single MDBox.
Bin the contents of a MDBox.
Parameters
box :: pointer to the MDBox to bin
chunkMin :: the minimum index in each dimension to consider "valid" (inclusive)
chunkMax :: the maximum index in each dimension to consider "valid" (exclusive)
Loop through the dimensions on which we bin
Loop through the dimensions on which we bin
Definition at line 93 of file BinMD.cpp.
References errors, Mantid::DataObjects::MDBox::getConstEvents(), Mantid::DataObjects::MDBoxBase::getErrorSquared(), Mantid::DataObjects::MDBox::getNPoints(), Mantid::DataObjects::MDBoxBase::getSignal(), Mantid::DataObjects::MDBoxBase::getVertexesArray(), indexMultiplier, Mantid::MDAlgorithms::SlicingAlgorithm::m_outD, Mantid::MDAlgorithms::SlicingAlgorithm::m_transform, numEvents, Mantid::DataObjects::MDBox::releaseEvents(), signals, and Mantid::Geometry::x.
Referenced by binByIterating().
category()
const std::string Mantid::MDAlgorithms::BinMD::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 53 of file BinMD.h.
exec()
void Mantid::MDAlgorithms::BinMD::exec () override private virtual
Run the algorithm.
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 344 of file BinMD.cpp.
References binByIterating(), CALL_MDEVENT_FUNCTION, Mantid::MDAlgorithms::SlicingAlgorithm::createTransform(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), implicitFunction, m_accumulate, Mantid::MDAlgorithms::SlicingAlgorithm::m_bases, Mantid::MDAlgorithms::SlicingAlgorithm::m_binDimensions, Mantid::MDAlgorithms::SlicingAlgorithm::m_intermediateWS, Mantid::MDAlgorithms::SlicingAlgorithm::m_inWS, Mantid::MDAlgorithms::SlicingAlgorithm::m_transformFromIntermediate, Mantid::MDAlgorithms::SlicingAlgorithm::m_transformFromOriginal, Mantid::MDAlgorithms::SlicingAlgorithm::m_transformToIntermediate, Mantid::MDAlgorithms::SlicingAlgorithm::m_transformToOriginal, Mantid::MDAlgorithms::SlicingAlgorithm::m_translation, name(), outWS, prog, Mantid::Kernel::IPropertyManager::setProperty(), tmp, and Mantid::Kernel::Logger::warning().
init()
void Mantid::MDAlgorithms::BinMD::init () override private virtual
Initialise the properties.
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 45 of file BinMD.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::MDAlgorithms::SlicingAlgorithm::initSlicingProps(), Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertyGroup().
name()
const std::string Mantid::MDAlgorithms::BinMD::name () const inline override virtual
Algorithm's name for identification.
Implements Mantid::API::Algorithm.
Definition at line 42 of file BinMD.h.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::BinMD::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 51 of file BinMD.h.
summary()
const std::string Mantid::MDAlgorithms::BinMD::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 44 of file BinMD.h.
version()
int Mantid::MDAlgorithms::BinMD::version () const inline override virtual
Algorithm's version for identification.
Implements Mantid::API::Algorithm.
Definition at line 50 of file BinMD.h.
Member Data Documentation
errors
signal_t* Mantid::MDAlgorithms::BinMD::errors private
Definition at line 78 of file BinMD.h.
Referenced by binByIterating(), and binMDBox().
implicitFunction
std::unique_ptr<Mantid::Geometry::MDImplicitFunction> Mantid::MDAlgorithms::BinMD::implicitFunction private
ImplicitFunction used.
Definition at line 73 of file BinMD.h.
Referenced by binByIterating(), and exec().
indexMultiplier
std::vector<size_t> Mantid::MDAlgorithms::BinMD::indexMultiplier private
Cached values for speed up.
Definition at line 76 of file BinMD.h.
Referenced by binByIterating(), and binMDBox().
m_accumulate
bool Mantid::MDAlgorithms::BinMD::m_accumulate {false} private
Definition at line 80 of file BinMD.h.
Referenced by binByIterating(), and exec().
numEvents
signal_t* Mantid::MDAlgorithms::BinMD::numEvents private
Definition at line 79 of file BinMD.h.
Referenced by binByIterating(), and binMDBox().
outWS
Mantid::DataObjects::MDHistoWorkspace_sptr Mantid::MDAlgorithms::BinMD::outWS private
The output MDHistoWorkspace.
Definition at line 69 of file BinMD.h.
Referenced by binByIterating(), and exec().
prog
std::unique_ptr<Mantid::API::Progress> Mantid::MDAlgorithms::BinMD::prog = nullptr private
Progress reporting.
Definition at line 71 of file BinMD.h.
Referenced by binByIterating(), and exec().
signals
signal_t* Mantid::MDAlgorithms::BinMD::signals private
Definition at line 77 of file BinMD.h.
Referenced by binByIterating(), and binMDBox().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/BinMD.h
Framework/MDAlgorithms/src/BinMD.cpp