Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask Class Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask Class Reference
#include <ProcessBankTask.h>
Public Member Functions
void operator() (const tbb::blocked_range< size_t > &range) const
ProcessBankTask (std::vector< std::string > &bankEntryNames, H5::H5File &h5file, const bool is_time_filtered, API::MatrixWorkspace_sptr &wksp, const std::map< detid_t, double > &calibration, const std::map< detid_t, double > &scale_at_sample, const std::map< size_t, std::vector< detid_t > > &grouping, const std::set< detid_t > &masked, const size_t events_per_chunk, const size_t grainsize_event, std::vector< PulseROI > pulse_indices, std::shared_ptr< API::Progress > &progress)
Private Attributes
const std::vector< std::string > m_bankEntries
const std::map< detid_t, double > m_calibration
detid: 1/difc
const size_t m_events_per_chunk
number of events to read from disk at one time
const size_t m_grainsize_event
number of events to histogram in a single thread
const std::map< size_t, std::vector< detid_t > > m_grouping
detector ids for output spectrum number
H5::H5File m_h5file
NexusLoader m_loader
const std::set< detid_t > m_masked
std::shared_ptr< API::Progress > m_progress
std::map< detid_t, double > m_scale_at_sample
multiplicative 0<value<1 to move neutron TOF at sample
API::MatrixWorkspace_sptr m_wksp
Detailed Description
Definition at line 20 of file ProcessBankTask.h.
Constructor & Destructor Documentation
ProcessBankTask()
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::ProcessBankTask (std::vector< std::string > & bankEntryNames, H5::H5File & h5file, const bool is_time_filtered, API::MatrixWorkspace_sptr & wksp, const std::map< detid_t, double > & calibration, const std::map< detid_t, double > & scale_at_sample, const std::map< size_t, std::vector< detid_t > > & grouping, const std::set< detid_t > & masked, const size_t events_per_chunk, const size_t grainsize_event, std::vector< PulseROI > pulse_indices, std::shared_ptr< API::Progress > & progress)
Definition at line 28 of file ProcessBankTask.cpp.
Member Function Documentation
operator()()
void Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator() (const tbb::blocked_range< size_t > & range) const
Definition at line 40 of file ProcessBankTask.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::DETID(), Mantid::API::g_log, Mantid::DataHandling::AlignAndFocusPowderSlim::NexusLoader::getEventIndexRanges(), Mantid::DataHandling::AlignAndFocusPowderSlim::NexusLoader::loadData(), m_bankEntries, m_calibration, m_events_per_chunk, m_grainsize_event, m_grouping, m_h5file, m_loader, m_masked, m_progress, m_scale_at_sample, m_wksp, maxval, minval, Mantid::Kernel::parallel_minmax(), Mantid::Nexus::H5Util::readStringAttribute(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::TIME_OF_FLIGHT(), Mantid::Kernel::Units::timeConversionValue(), and Mantid::Geometry::y.
Member Data Documentation
m_bankEntries
const std::vector<std::string> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_bankEntries private
Definition at line 33 of file ProcessBankTask.h.
Referenced by operator()().
m_calibration
const std::map<detid_t, double> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_calibration private
detid: 1/difc
Definition at line 36 of file ProcessBankTask.h.
Referenced by operator()().
m_events_per_chunk
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_events_per_chunk private
number of events to read from disk at one time
Definition at line 41 of file ProcessBankTask.h.
Referenced by operator()().
m_grainsize_event
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_grainsize_event private
number of events to histogram in a single thread
Definition at line 43 of file ProcessBankTask.h.
Referenced by operator()().
m_grouping
const std::map<size_t, std::vector<detid_t> > Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_grouping private
detector ids for output spectrum number
Definition at line 38 of file ProcessBankTask.h.
Referenced by operator()().
m_h5file
H5::H5File Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_h5file private
Definition at line 32 of file ProcessBankTask.h.
Referenced by operator()().
m_loader
NexusLoader Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_loader mutable private
Definition at line 34 of file ProcessBankTask.h.
Referenced by operator()().
m_masked
const std::set<detid_t> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_masked private
Definition at line 39 of file ProcessBankTask.h.
Referenced by operator()().
m_progress
std::shared_ptr<API::Progress> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_progress private
Definition at line 44 of file ProcessBankTask.h.
Referenced by operator()().
m_scale_at_sample
std::map<detid_t, double> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_scale_at_sample private
multiplicative 0<value<1 to move neutron TOF at sample
Definition at line 37 of file ProcessBankTask.h.
Referenced by operator()().
m_wksp
API::MatrixWorkspace_sptr Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::m_wksp private
Definition at line 35 of file ProcessBankTask.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim/ProcessBankTask.h
Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankTask.cpp