Mantid: Mantid::Algorithms::SofQW Class Reference
Mantid::Algorithms::SofQW Class Reference
#include <SofQW.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Static Public Member Functions
static void createCommonInputProperties (API::Algorithm &alg)
Create the input properties on the given algorithm object.
template<typename Workspace >
static std::unique_ptr< Workspace > setUpOutputWorkspace (const API::MatrixWorkspace &inputWorkspace, const std::vector< double > &qbinParams, std::vector< double > &qAxis, const std::vector< double > &ebinParams, const SofQCommon &emodeProperties)
Create the output workspace.
Private Member Functions
void exec () override
Execution code.
void init () override
Initialization code.
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
Definition at line 44 of file SofQW.h.
Member Function Documentation
category()
const std::string Mantid::Algorithms::SofQW::category () const inline override
Algorithm's category for identification.
Definition at line 57 of file SofQW.h.
createCommonInputProperties()
void Mantid::Algorithms::SofQW::createCommonInputProperties (API::Algorithm & alg) static
Create the input properties on the given algorithm object.
Create the common set of input properties for the given algorithm.
Parameters
alg An algorithm object
Definition at line 69 of file SofQW.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, and Mantid::Kernel::Direction::Output.
Referenced by init(), Mantid::Algorithms::SofQWCentre::init(), Mantid::Algorithms::SofQWNormalisedPolygon::init(), and Mantid::Algorithms::SofQWPolygon::init().
exec()
void Mantid::Algorithms::SofQW::exec () override private
Execution code.
Definition at line 110 of file SofQW.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty().
init()
void Mantid::Algorithms::SofQW::init () override private
Initialization code.
Create the input properties.
Definition at line 54 of file SofQW.cpp.
References createCommonInputProperties().
name()
const std::string Mantid::Algorithms::SofQW::name () const inline override
Algorithm's name.
Definition at line 47 of file SofQW.h.
seeAlso()
const std::vector< std::string > Mantid::Algorithms::SofQW::seeAlso () const inline override
Definition at line 53 of file SofQW.h.
setUpOutputWorkspace()
template<typename Workspace > std::unique_ptr< Workspace > Mantid::Algorithms::SofQW::setUpOutputWorkspace (const API::MatrixWorkspace & inputWorkspace, const std::vector< double > & qbinParams, std::vector< double > & qAxis, const std::vector< double > & ebinParams, const SofQCommon & emodeProperties) static
Create the output workspace.
Creates the output workspace, setting the axes according to the input binning parameters.
Template Parameters
Workspace The type of the workspace to create
Parameters
[in] inputWorkspace The input workspace
[in] qbinParams The q-bin parameters from the user
[out] qAxis The 'vertical' (q) axis defined by the given parameters
[out] ebinParams The 'horizontal' (energy) axis parameters (optional)
[in] emodeProperties The initialized SofQCommon object corresponding to the input workspace and calling algorithm
Returns
A pointer to the newly-created workspace
Definition at line 87 of file SofQW.h.
References Mantid::API::MatrixWorkspace::binEdges(), Mantid::Kernel::VectorHelper::createAxisFromRebinParams(), Mantid::API::MatrixWorkspace::getXMinMax(), and Mantid::Algorithms::SofQCommon::qBinHints().
summary()
const std::string Mantid::Algorithms::SofQW::summary () const override
Summary of algorithms purpose.
Returns
A summary of the algorithm
Definition at line 37 of file SofQW.cpp.
version()
int Mantid::Algorithms::SofQW::version () const inline override
Algorithm's version.
Definition at line 52 of file SofQW.h.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/SofQW.h
Framework/Algorithms/src/SofQW.cpp