Mantid: Mantid::API::MDGeometry Class Reference
Mantid::API::MDGeometry Class Reference
Describes the geometry (i.e.
#include <MDGeometry.h>
Public Member Functions
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const
Get a dimension.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const
Get a dimension.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumDims () const
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Protected Member Functions
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Attributes
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Friends
class MDGeometryNotificationHelper
Detailed Description
Describes the geometry (i.e.
dimensions) of an IMDWorkspace. This defines the dimensions contained in the workspace. On option, it can also relate the coordinates of this workspace to another workspace, e.g. if a workspace is a slice or a view onto an original workspace.
Author
Janik Zikovsky
Date
2011-09-06
Definition at line 36 of file MDGeometry.h.
Constructor & Destructor Documentation
MDGeometry() [1/2]
Mantid::API::MDGeometry::MDGeometry ()
Constructor.
Definition at line 78 of file MDGeometry.cpp.
MDGeometry() [2/2]
Mantid::API::MDGeometry::MDGeometry (const MDGeometry & other)
Copy Constructor.
Definition at line 86 of file MDGeometry.cpp.
~MDGeometry()
Mantid::API::MDGeometry::~MDGeometry () virtual
Destructor.
Definition at line 148 of file MDGeometry.cpp.
References m_dimensions.
Member Function Documentation
addDimension() [1/2]
void Mantid::API::MDGeometry::addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > & dim)
Add a dimension.
Parameters
dim :: shared pointer to the dimension object
Definition at line 255 of file MDGeometry.cpp.
References m_dimensions.
Referenced by Mantid::MDAlgorithms::LoadMD::doLoad(), and Mantid::MDAlgorithms::SliceMD::slice().
addDimension() [2/2]
void Mantid::API::MDGeometry::addDimension (Mantid::Geometry::IMDDimension * dim)
Add a dimension.
Parameters
dim :: bare pointer to the dimension object
Definition at line 262 of file MDGeometry.cpp.
References m_dimensions.
allBasisNormalized()
bool Mantid::API::MDGeometry::allBasisNormalized () const
Returns
True ONLY if ALL the basis vectors have been normalized.
Definition at line 332 of file MDGeometry.cpp.
References m_basisVectors.
clearOriginalWorkspaces()
void Mantid::API::MDGeometry::clearOriginalWorkspaces ()
Clear original workspaces.
Clear the original workspaces.
Definition at line 143 of file MDGeometry.cpp.
References m_originalWorkspaces.
Referenced by export_MDGeometry().
clearTransforms()
void Mantid::API::MDGeometry::clearTransforms ()
Clear transforms.
Clear all transforms to and from original workspaces.
Definition at line 135 of file MDGeometry.cpp.
References m_transforms_FromOriginal, and m_transforms_ToOriginal.
deleteNotificationReceived()
void Mantid::API::MDGeometry::deleteNotificationReceived (const std::shared_ptr< const Workspace > & deleted) protected
Function called when observer objects recieves a notification.
Function called when observer objects receives a notification that a workspace has been deleted.
This checks if the "original workspace" in this object is being deleted, and removes the reference to it to allow it to be destructed properly.
Parameters
deleted :: The deleted workspace
Definition at line 432 of file MDGeometry.cpp.
References m_originalWorkspaces.
Referenced by Mantid::API::MDGeometryNotificationHelper::deleteNotificationReceived().
estimateResolution()
std::vector< coord_t > Mantid::API::MDGeometry::estimateResolution () const virtual
Returns
a vector with the size of the smallest bin in each dimension
Reimplemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Definition at line 213 of file MDGeometry.cpp.
References Mantid::Geometry::d, and getNumDims().
Referenced by export_MDGeometry().
getBasisVector() [1/2]
Mantid::Kernel::VMD & Mantid::API::MDGeometry::getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
Parameters
index :: which dimension
Returns
a vector, in the dimensions of the original workspace
Definition at line 301 of file MDGeometry.cpp.
References index, and m_basisVectors.
Referenced by export_MDGeometry().
getBasisVector() [2/2]
const Mantid::Kernel::VMD & Mantid::API::MDGeometry::getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
Parameters
index :: which dimension
Returns
a vector, in the dimensions of the original workspace
Definition at line 312 of file MDGeometry.cpp.
References index, and m_basisVectors.
getDimension()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getDimension (size_t index) const virtual
Get a dimension.
Parameters
index :: which dimension
Returns
the dimension at that index
Reimplemented in Mantid::API::MatrixWorkspace.
Definition at line 178 of file MDGeometry.cpp.
References index, and m_dimensions.
Referenced by Mantid::DataObjects::FakeMD::addFakeRegularData(), Mantid::DataObjects::FakeMD::addFakeUniformData(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), Mantid::DataObjects::MDHistoWorkspaceIterator::createPermutations(), createShapedOutput(), export_MDGeometry(), Mantid::DataObjects::MDHistoWorkspace::getBinBoundariesOnLine(), getGeometryXML(), getTDimension(), getXDimension(), getYDimension(), getZDimension(), Mantid::DataObjects::MDHistoWorkspaceIterator::init(), Mantid::DataObjects::pointInWorkspace(), and Mantid::API::IMDWorkspace::toString().
getDimensionIndexById()
size_t Mantid::API::MDGeometry::getDimensionIndexById (const std::string & id) const
Get the index of the dimension that matches the ID given.
Parameters
id :: id string of the dimension
Returns
the index (size_t)
Exceptions
runtime_error if it cannot be found.
Definition at line 243 of file MDGeometry.cpp.
References m_dimensions.
Referenced by export_MDGeometry().
getDimensionIndexByName()
size_t Mantid::API::MDGeometry::getDimensionIndexByName (const std::string & name) const
Get the index of the dimension that matches the name given.
Parameters
name :: name of the m_dimensions
Returns
the index (size_t)
Exceptions
runtime_error if it cannot be found.
Definition at line 227 of file MDGeometry.cpp.
References m_dimensions, and name.
Referenced by export_MDGeometry().
getDimensionWithId()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getDimensionWithId (std::string id) const virtual
Get a dimension.
Parameters
id :: string ID of the dimension
Returns
the dimension with the specified id string.
Reimplemented in Mantid::API::MatrixWorkspace.
Definition at line 189 of file MDGeometry.cpp.
References m_dimensions.
Referenced by export_MDGeometry().
getGeometryXML()
std::string Mantid::API::MDGeometry::getGeometryXML () const
Returns
a XML representation of the geometry of the workspace
Definition at line 539 of file MDGeometry.cpp.
References Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addOrdinaryDimension(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addTDimension(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addXDimension(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addYDimension(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::addZDimension(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::create(), getDimension(), getNumDims(), getTDimension(), getXDimension(), getYDimension(), and getZDimension().
Referenced by export_MDGeometry().
getNonIntegratedDimensions()
Mantid::Geometry::VecIMDDimension_const_sptr Mantid::API::MDGeometry::getNonIntegratedDimensions () const
Get non-collapsed dimensions.
Returns
vector of collapsed dimensions in the workspace geometry.
Definition at line 203 of file MDGeometry.cpp.
References m_dimensions.
getNumberTransformsFromOriginal()
size_t Mantid::API::MDGeometry::getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
Returns
The number of transforms.
Definition at line 575 of file MDGeometry.cpp.
References m_transforms_FromOriginal.
Referenced by export_MDGeometry().
getNumberTransformsToOriginal()
size_t Mantid::API::MDGeometry::getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
Returns
The number of transforms.
Definition at line 569 of file MDGeometry.cpp.
References m_transforms_ToOriginal.
Referenced by export_MDGeometry().
getNumDims()
size_t Mantid::API::MDGeometry::getNumDims () const virtual
Returns
the number of dimensions in this workspace
Reimplemented in Mantid::API::MatrixWorkspace, Mantid::DataObjects::MDEventWorkspace< MDE, nd >, and Mantid::DataObjects::WorkspaceSingleValue.
Definition at line 165 of file MDGeometry.cpp.
References m_dimensions.
Referenced by Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), createShapedOutput(), estimateResolution(), export_MDGeometry(), getGeometryXML(), Mantid::DataObjects::MDHistoWorkspace::getLinePoints(), getTDimension(), getXDimension(), getYDimension(), getZDimension(), MantidQt::MantidWidgets::SlicingAlgorithmDialog::hasDimensionHistoryChanged(), Mantid::DataObjects::MDHistoWorkspaceIterator::init(), Mantid::DataObjects::pointInWorkspace(), and Mantid::API::IMDWorkspace::toString().
getNumNonIntegratedDims()
size_t Mantid::API::MDGeometry::getNumNonIntegratedDims () const virtual
Returns
the number of non-integrated dimensions in this workspace
Definition at line 168 of file MDGeometry.cpp.
References m_dimensions.
getOrigin() [1/2]
Mantid::Kernel::VMD & Mantid::API::MDGeometry::getOrigin () inline
Returns
the vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace
Definition at line 91 of file MDGeometry.h.
Referenced by export_MDGeometry().
getOrigin() [2/2]
const Mantid::Kernel::VMD & Mantid::API::MDGeometry::getOrigin () const inline
Returns
the vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace
Definition at line 95 of file MDGeometry.h.
getOriginalWorkspace()
std::shared_ptr< Workspace > Mantid::API::MDGeometry::getOriginalWorkspace (size_t index = 0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Returns
the original workspace to which the basis vectors relate
Parameters
index :: index into the vector of original workspaces.
Definition at line 361 of file MDGeometry.cpp.
References index, and m_originalWorkspaces.
Referenced by export_MDGeometry(), and Mantid::API::IMDWorkspace::toString().
getTDimension()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getTDimension () const
Get the t-dimension mapping.
Definition at line 289 of file MDGeometry.cpp.
References getDimension(), and getNumDims().
Referenced by export_MDGeometry(), and getGeometryXML().
getTransformFromOriginal()
Mantid::API::CoordTransform const * Mantid::API::MDGeometry::getTransformFromOriginal (size_t index = 0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Returns
CoordTransform pointer
Parameters
index :: index into the array of original workspaces
Definition at line 476 of file MDGeometry.cpp.
References index, and m_transforms_FromOriginal.
getTransformToOriginal()
Mantid::API::CoordTransform const * Mantid::API::MDGeometry::getTransformToOriginal (size_t index = 0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Returns
CoordTransform pointer
Parameters
index :: index into the array of original workspaces
Definition at line 512 of file MDGeometry.cpp.
References index, and m_transforms_ToOriginal.
getWTransf()
const Kernel::DblMatrix & Mantid::API::MDGeometry::getWTransf () const inline
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
Definition at line 108 of file MDGeometry.h.
getXDimension()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getXDimension () const
Get the x-dimension mapping.
Definition at line 268 of file MDGeometry.cpp.
References getDimension(), and getNumDims().
Referenced by export_MDGeometry(), and getGeometryXML().
getYDimension()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getYDimension () const
Get the y-dimension mapping.
Definition at line 275 of file MDGeometry.cpp.
References getDimension(), and getNumDims().
Referenced by export_MDGeometry(), and getGeometryXML().
getZDimension()
std::shared_ptr< const Mantid::Geometry::IMDDimension > Mantid::API::MDGeometry::getZDimension () const
Get the z-dimension mapping.
Definition at line 282 of file MDGeometry.cpp.
References getDimension(), and getNumDims().
Referenced by export_MDGeometry(), and getGeometryXML().
hasOriginalWorkspace()
bool Mantid::API::MDGeometry::hasOriginalWorkspace (size_t index = 0) const
Returns
true if the geometry is defined relative to another workspace.
Parameters
index :: index into the vector of original workspaces
Definition at line 341 of file MDGeometry.cpp.
References index, and m_originalWorkspaces.
Referenced by export_MDGeometry(), and Mantid::API::IMDWorkspace::toString().
initGeometry()
void Mantid::API::MDGeometry::initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > & dimensions)
Initialize the geometry.
Parameters
dimensions :: vector of IMDDimension objects, in the order of X, Y, Z, t, etc.
Definition at line 156 of file MDGeometry.cpp.
References m_basisVectors, and m_dimensions.
Referenced by Mantid::DataObjects::MDHistoWorkspace::init(), MDHistoWorkspaceTester::MDHistoWorkspaceTester(), and operator=().
numOriginalWorkspaces()
size_t Mantid::API::MDGeometry::numOriginalWorkspaces () const
Returns
the number of original workspaces attached to this one
Definition at line 348 of file MDGeometry.cpp.
References m_originalWorkspaces.
Referenced by export_MDGeometry().
operator=()
MDGeometry & Mantid::API::MDGeometry::operator= (const MDGeometry & other)
Definition at line 88 of file MDGeometry.cpp.
References Mantid::Geometry::d, initGeometry(), m_basisVectors, m_dimensions, m_notificationHelper, m_origin, m_originalWorkspaces, m_transforms_FromOriginal, m_transforms_ToOriginal, m_Wtransf, and setOriginalWorkspace().
replaceNotificationReceived()
void Mantid::API::MDGeometry::replaceNotificationReceived (const std::shared_ptr< const Workspace > & replaced) protected
Function called when observer detects a workspace is replaced.
Function called when observer objects receives a notification that a workspace has been replaced.
This checks if the "original workspace" in this object is being replaced, and removes the reference to it to allow it to be destructed properly.
Parameters
replaced :: The replaced workspace
Definition at line 453 of file MDGeometry.cpp.
References m_originalWorkspaces.
Referenced by Mantid::API::MDGeometryNotificationHelper::replaceNotificationReceived().
setBasisVector()
void Mantid::API::MDGeometry::setBasisVector (size_t index, const Mantid::Kernel::VMD & vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
Parameters
index :: which dimension
vec :: a vector, in the dimensions of the original workspace
Definition at line 323 of file MDGeometry.cpp.
References index, m_basisVectors, and vec.
setOrigin()
void Mantid::API::MDGeometry::setOrigin (const Mantid::Kernel::VMD & orig) inline
Sets the origin of this geometry.
Parameters
orig :: the vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace
Definition at line 100 of file MDGeometry.h.
setOriginalWorkspace()
void Mantid::API::MDGeometry::setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index = 0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Parameters
ws :: original workspace shared pointer
index :: index into the vector of original workspaces.
Definition at line 378 of file MDGeometry.cpp.
References index, m_notificationHelper, and m_originalWorkspaces.
Referenced by operator=(), and transformDimensions().
setTransformFromOriginal()
void Mantid::API::MDGeometry::setTransformFromOriginal (Mantid::API::CoordTransform * transform, size_t index = 0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Parameters
transform :: CoordTransform pointer (this assumes pointer ownership)
index :: index into the array of original workspaces
Definition at line 493 of file MDGeometry.cpp.
References index, and m_transforms_FromOriginal.
Referenced by transformDimensions().
setTransformToOriginal()
void Mantid::API::MDGeometry::setTransformToOriginal (Mantid::API::CoordTransform * transform, size_t index = 0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
In the case of a chain of workspaces: A->binned to B->binned to C: Index 0 = the workspace that was binned, e.g. "A" Index 1 = the intermediate workspace, e.g. "B"
Parameters
transform :: CoordTransform pointer (this assumes pointer ownership)
index :: index into the array of original workspaces
Definition at line 530 of file MDGeometry.cpp.
References index, and m_transforms_ToOriginal.
Referenced by transformDimensions().
setWTransf()
void Mantid::API::MDGeometry::setWTransf (const Kernel::DblMatrix & WTransf) inline
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
Definition at line 104 of file MDGeometry.h.
transformDimensions()
void Mantid::API::MDGeometry::transformDimensions (std::vector< double > const & scaling, std::vector< double > const & offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
This clears any original workspace or coordinate transformation contained.
NOTE! This does not modify any other underlying data. Call the TransformMD algorithm to perform a full transform.
Parameters
scaling :: multiply each coordinate by this value.
offset :: after multiplying, add this offset.
Definition at line 399 of file MDGeometry.cpp.
References Mantid::Geometry::d, m_dimensions, setOriginalWorkspace(), setTransformFromOriginal(), and setTransformToOriginal().
Friends And Related Symbol Documentation
MDGeometryNotificationHelper
friend class MDGeometryNotificationHelper friend
Definition at line 115 of file MDGeometry.h.
Member Data Documentation
m_basisVectors
std::vector<Mantid::Kernel::VMD> Mantid::API::MDGeometry::m_basisVectors protected
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
Definition at line 157 of file MDGeometry.h.
Referenced by allBasisNormalized(), getBasisVector(), getBasisVector(), initGeometry(), operator=(), and setBasisVector().
m_dimensions
std::vector<std::shared_ptr<Geometry::IMDDimension> > Mantid::API::MDGeometry::m_dimensions protected
Vector of the dimensions used, in the order X Y Z t, etc.
Definition at line 125 of file MDGeometry.h.
Referenced by addDimension(), addDimension(), Mantid::DataObjects::MDHistoWorkspace::applyImplicitFunction(), Mantid::DataObjects::MDHistoWorkspace::cacheValues(), getDimension(), getDimensionIndexById(), getDimensionIndexByName(), getDimensionWithId(), getNonIntegratedDimensions(), getNumDims(), getNumNonIntegratedDims(), initGeometry(), Mantid::DataObjects::MDHistoWorkspace::initVertexesArray(), operator=(), transformDimensions(), and ~MDGeometry().
m_notificationHelper
std::unique_ptr<MDGeometryNotificationHelper> Mantid::API::MDGeometry::m_notificationHelper protected
Helper that deals with notifications and observing the ADS.
Definition at line 144 of file MDGeometry.h.
Referenced by operator=(), and setOriginalWorkspace().
m_origin
Mantid::Kernel::VMD Mantid::API::MDGeometry::m_origin protected
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
Definition at line 133 of file MDGeometry.h.
Referenced by operator=().
m_originalWorkspaces
std::vector<std::shared_ptr<Workspace> > Mantid::API::MDGeometry::m_originalWorkspaces protected
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
Definition at line 129 of file MDGeometry.h.
Referenced by clearOriginalWorkspaces(), deleteNotificationReceived(), getOriginalWorkspace(), hasOriginalWorkspace(), numOriginalWorkspaces(), operator=(), replaceNotificationReceived(), and setOriginalWorkspace().
m_transforms_FromOriginal
std::vector<std::shared_ptr<const Mantid::API::CoordTransform> > Mantid::API::MDGeometry::m_transforms_FromOriginal protected
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Definition at line 137 of file MDGeometry.h.
Referenced by clearTransforms(), getNumberTransformsFromOriginal(), getTransformFromOriginal(), operator=(), and setTransformFromOriginal().
m_transforms_ToOriginal
std::vector<std::shared_ptr<const Mantid::API::CoordTransform> > Mantid::API::MDGeometry::m_transforms_ToOriginal protected
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Definition at line 141 of file MDGeometry.h.
Referenced by clearTransforms(), getNumberTransformsToOriginal(), getTransformToOriginal(), operator=(), and setTransformToOriginal().
m_Wtransf
Kernel::DblMatrix Mantid::API::MDGeometry::m_Wtransf protected
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Small variation here is that in also includes either B-matrix or orthogonal B-matrix
Definition at line 152 of file MDGeometry.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/MDGeometry.h
Framework/API/src/MDGeometry.cpp