Mantid: Mantid::Geometry::Rasterize Namespace Reference
Mantid::Geometry::Rasterize Namespace Reference
Functions
MANTID_GEOMETRY_DLL Raster calculate (const Kernel::V3D &beamDirection, const IObject &integShape, const IObject &sampleShape, const double cubeSizeInMetre)
MANTID_GEOMETRY_DLL Raster calculateCylinder (const Kernel::V3D &beamDirection, const IObject &integShape, const IObject &sampleShape, const size_t numSlices, const size_t numAnnuli)
MANTID_GEOMETRY_DLL Raster calculateHollowCylinder (const Kernel::V3D &beamDirection, const IObject &integShape, const IObject &sampleShape, const size_t numSlices, const size_t numAnnuli)
Function Documentation
calculate()
Raster Mantid::Geometry::Rasterize::calculate (const Kernel::V3D & beamDirection, const IObject & integShape, const IObject & sampleShape, const double cubeSizeInMetre)
Definition at line 162 of file Rasterize.cpp.
References calculateCylinder(), calculateHollowCylinder(), Mantid::Geometry::detail::ShapeInfo::CYLINDER, Mantid::Geometry::detail::ShapeInfo::cylinderGeometry(), Mantid::Geometry::detail::ShapeInfo::HOLLOWCYLINDER, Mantid::Geometry::IObject::shape(), and Mantid::Geometry::IObject::shapeInfo().
Referenced by Mantid::Algorithms::MultipleScatteringCorrectionDistGraber::cacheLS1(), Mantid::Algorithms::AnyShapeAbsorption::initialiseCachedDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::rasterize(), and Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::rasterizeGaugeVolumeAndCalculateMeanElementPosition().
calculateCylinder()
Raster Mantid::Geometry::Rasterize::calculateCylinder (const Kernel::V3D & beamDirection, const IObject & integShape, const IObject & sampleShape, const size_t numSlices, const size_t numAnnuli)
Definition at line 188 of file Rasterize.cpp.
References Mantid::Kernel::V3D::cross_prod(), Mantid::Geometry::detail::ShapeInfo::CYLINDER, Mantid::Geometry::detail::ShapeInfo::cylinderGeometry(), Mantid::Geometry::IObject::interceptSurface(), Mantid::Geometry::IObject::isValid(), Mantid::Kernel::normalize(), position, Mantid::Geometry::Raster::reserve(), Mantid::Geometry::IObject::shape(), Mantid::Geometry::IObject::shapeInfo(), Mantid::Geometry::Track::totalDistInsideObject(), and Mantid::Geometry::z.
Referenced by calculate(), and Mantid::Algorithms::CylinderAbsorption::initialiseCachedDistances().
calculateHollowCylinder()
Raster Mantid::Geometry::Rasterize::calculateHollowCylinder (const Kernel::V3D & beamDirection, const IObject & integShape, const IObject & sampleShape, const size_t numSlices, const size_t numAnnuli)
Definition at line 265 of file Rasterize.cpp.
References Mantid::Kernel::V3D::cross_prod(), Mantid::Geometry::detail::ShapeInfo::HOLLOWCYLINDER, Mantid::Geometry::detail::ShapeInfo::hollowCylinderGeometry(), Mantid::Geometry::IObject::interceptSurface(), Mantid::Geometry::IObject::isValid(), Mantid::Kernel::V3D::normalize(), position, Mantid::Geometry::Raster::reserve(), Mantid::Geometry::IObject::shape(), Mantid::Geometry::IObject::shapeInfo(), Mantid::Geometry::Track::totalDistInsideObject(), and Mantid::Geometry::z.
Referenced by calculate().