Mantid: MantidQt::MantidWidgets::FindPeakConvolveStrategy Class Reference
MantidQt::MantidWidgets::FindPeakConvolveStrategy Class Reference
#include <FitPropertyBrowserFindPeaksExt.h>
Public Member Functions
void execute () override
void initialise (const std::string &wsName, const int workspaceIndex, const std::string &peakListName, const int FWHM, AlgorithmFinishObserver *obs) override
Public Member Functions inherited from MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >
double getPeakCentre (const size_t peakIndex) const override
double getPeakHeight (const size_t peakIndex) const override
double getPeakWidth (const size_t peakIndex) const override
size_t peakNumber () const override
Public Member Functions inherited from MantidQt::MantidWidgets::FindPeakStrategyGeneric
virtual ~FindPeakStrategyGeneric ()
Private Attributes
MantidQt::API::AlgorithmDialog * m_dlg
int m_FWHM
AlgorithmFinishObserver * m_obs
Additional Inherited Members
Protected Attributes inherited from MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >
std::unique_ptr< std::vector< double > > m_peakCentres
std::unique_ptr< std::vector< double > > m_peakHeights
std::string m_peakListName
std::unique_ptr< std::vector< double > > m_peakWidths
Detailed Description
Definition at line 60 of file FitPropertyBrowserFindPeaksExt.h.
Member Function Documentation
execute()
void MantidQt::MantidWidgets::FindPeakConvolveStrategy::execute () override virtual
Implements MantidQt::MantidWidgets::FindPeakStrategyGeneric.
Definition at line 47 of file FitPropertyBrowserFindPeaksExt.cpp.
References m_dlg, m_FWHM, m_obs, MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >::m_peakCentres, MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >::m_peakHeights, MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >::m_peakListName, and MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >::m_peakWidths.
initialise()
void MantidQt::MantidWidgets::FindPeakConvolveStrategy::initialise (const std::string & wsName, const int workspaceIndex, const std::string & peakListName, const int FWHM, AlgorithmFinishObserver * obs) override virtual
Implements MantidQt::MantidWidgets::FindPeakStrategyGeneric.
Definition at line 24 of file FitPropertyBrowserFindPeaksExt.cpp.
References MantidQt::API::AlgorithmDialog::addAlgorithmObserver(), MantidQt::API::InterfaceManager::createDialogFromName(), MantidQt::API::AlgorithmDialog::disableExitButton(), m_dlg, m_FWHM, m_obs, MantidQt::MantidWidgets::FindPeakStrategy< std::vector< double > >::m_peakListName, and MantidQt::API::AlgorithmDialog::setShowKeepOpen().
Member Data Documentation
m_dlg
MantidQt::API::AlgorithmDialog* MantidQt::MantidWidgets::FindPeakConvolveStrategy::m_dlg private
Definition at line 71 of file FitPropertyBrowserFindPeaksExt.h.
Referenced by execute(), and initialise().
m_FWHM
int MantidQt::MantidWidgets::FindPeakConvolveStrategy::m_FWHM private
Definition at line 69 of file FitPropertyBrowserFindPeaksExt.h.
Referenced by execute(), and initialise().
m_obs
AlgorithmFinishObserver* MantidQt::MantidWidgets::FindPeakConvolveStrategy::m_obs private
Definition at line 70 of file FitPropertyBrowserFindPeaksExt.h.
Referenced by execute(), and initialise().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowserFindPeaksExt.h
qt/widgets/common/src/FitPropertyBrowserFindPeaksExt.cpp