Mantid: ICat4::_ns1__login_credentials_entry Class Reference
ICat4::_ns1__login_credentials_entry Class Reference
#include <ICat4Stub.h>
Public Member Functions
_ns1__login_credentials_entry ()
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
virtual ~_ns1__login_credentials_entry ()=default
Public Attributes
std::string * key
std::string * value
Detailed Description
Definition at line 922 of file ICat4Stub.h.
Constructor & Destructor Documentation
_ns1__login_credentials_entry()
ICat4::_ns1__login_credentials_entry::_ns1__login_credentials_entry () inline
Definition at line 934 of file ICat4Stub.h.
~_ns1__login_credentials_entry()
virtual ICat4::_ns1__login_credentials_entry::~_ns1__login_credentials_entry () virtual default
Member Function Documentation
soap_default()
void ICat4::_ns1__login_credentials_entry::soap_default (struct soap * soap) virtual
Definition at line 4906 of file ICat4C.cpp.
References key, and value.
Referenced by ICat4::soap_in__ns1__login_credentials_entry(), ICat4::soap_new_req__ns1__login_credentials_entry(), and ICat4::soap_new_set__ns1__login_credentials_entry().
soap_get()
void * ICat4::_ns1__login_credentials_entry::soap_get (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 5000 of file ICat4C.cpp.
References ICat4::soap_get__ns1__login_credentials_entry().
soap_in()
void * ICat4::_ns1__login_credentials_entry::soap_in (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 4937 of file ICat4C.cpp.
References ICat4::soap_in__ns1__login_credentials_entry().
Referenced by ICat4::soap_in__ns1__login_credentials_entry().
soap_out()
int ICat4::_ns1__login_credentials_entry::soap_out (struct soap * soap, const char * tag, int id, const char * type) const virtual
Definition at line 4920 of file ICat4C.cpp.
References ICat4::soap_out__ns1__login_credentials_entry().
Referenced by soap_put().
soap_put()
int ICat4::_ns1__login_credentials_entry::soap_put (struct soap * soap, const char * tag, const char * type) const virtual
Definition at line 4993 of file ICat4C.cpp.
References soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4__ns1__login_credentials_entry.
soap_serialize()
void ICat4::_ns1__login_credentials_entry::soap_serialize (struct soap * soap) const virtual
Definition at line 4912 of file ICat4C.cpp.
References key, ICat4::soap_serialize_PointerTostd__string(), and value.
soap_type()
virtual int ICat4::_ns1__login_credentials_entry::soap_type () const inline virtual
Definition at line 927 of file ICat4Stub.h.
Member Data Documentation
key
std::string* ICat4::_ns1__login_credentials_entry::key
Definition at line 924 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::login(), soap_default(), and soap_serialize().
value
std::string* ICat4::_ns1__login_credentials_entry::value
Definition at line 925 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::login(), soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp