Mantid: Mantid::CurveFitting::Functions::IkedaCarpenterPV Class Reference
Mantid::CurveFitting::Functions::IkedaCarpenterPV Class Reference
Provide Ikeda-Carpenter-pseudo-Voigt peak shape function interface to IPeakFunction.
#include <IkedaCarpenterPV.h>
Public Member Functions
const std::string category () const override
The categories the Fit function belong to.
double centre () const override
overwrite IPeakFunction base class methods
double fwhm () const override
Returns the peak FWHM.
double height () const override
Returns the height of the function.
double intensity () const override
Returns the integral intensity of the peak.
std::string name () const override
overwrite IFunction base class methods
void setCentre (const double c) override
Sets the parameters such that centre == c.
void setFwhm (const double w) override
Sets the parameters such that FWHM = w.
void setHeight (const double h) override
Sets the parameters such that height == h.
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Set MatrixWorkspace.
Public Member Functions inherited from Mantid::API::IPeakFunction
virtual void fixIntensity (bool isDefault=false)
Fix a parameter or set up a tie such that value returned by intensity() is constant during fitting.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
void function1D (double *out, const double *xValues, const size_t nData) const override
General implementation of the method for all peaks.
void functionDeriv1D (Jacobian *out, const double *xValues, const size_t nData) override
General implementation of the method for all peaks.
virtual void functionDerivLocal (Jacobian *jacobian, const double *xValues, const size_t nData)
Derivative evaluation method. Default is to calculate numerically.
virtual void functionLocal (double *out, const double *xValues, const size_t nData) const =0
Function evaluation method to be implemented in the inherited classes.
virtual double fwhm () const =0
Returns the peak FWHM.
std::string getCentreParameterName () const
Get name of parameter that is associated to centre.
virtual std::pair< double, double > getDomainInterval (double level=DEFAULT_SEARCH_LEVEL) const
Get the interval on which the peak has all its values above a certain level.
virtual std::string getWidthParameterName () const
Get the name of the parameter that is changed when the fwhm is changed.
virtual double intensity () const
Returns the integral intensity of the peak.
virtual double intensityError () const
Error in the integrated intensity of the peak due to uncertainties in the values of the fit parameters.
IPeakFunction ()
Constructor.
virtual void setFwhm (const double w)=0
Sets the parameters such that FWHM = w.
virtual void setIntensity (const double newIntensity)
Sets the integral intensity of the peak.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Override parent so that we may bust the cache when a parameter is set.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Override parent so that we may bust the cache when a parameter is set.
virtual void unfixIntensity ()
Free the intensity parameter.
Public Member Functions inherited from Mantid::API::IFunctionWithLocation
virtual double centre () const =0
Returns the centre of the function, which may be something as simple as the centre of the fitting range in the case of a background function or peak shape function this return value reflects the centre of the peak.
virtual void fixCentre (bool isDefault=false)
Fix a parameter or set up a tie such that value returned by centre() is constant during fitting.
virtual double height () const =0
Returns the height of the function.
virtual void setCentre (const double c)=0
Sets the parameters such that centre == c.
virtual void setHeight (const double h)=0
Sets the parameters such that height == h.
virtual void unfixCentre ()
Free the centre parameter.
~IFunctionWithLocation () override=default
Virtual destructor (avoids warnings about non-trivial move assignment in virtually inheriting classes)
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void function (const FunctionDomain &domain, FunctionValues &values) const =0
Evaluates the function for all arguments in the domain.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies ()
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual void setAttribute (const std::string &name, const Attribute &)
Set a value to attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::IFunction1D
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
virtual void function1D (double *out, const double *xValues, const size_t nData) const =0
Function you want to fit to.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
virtual void functionDeriv1D (Jacobian *jacobian, const double *xValues, const size_t nData)
Derivatives of function with respect to active parameters.
Public Member Functions inherited from Mantid::API::IFunctionMW
std::shared_ptr< const API::MatrixWorkspace > getMatrixWorkspace () const
Get shared pointer to the workspace.
size_t getWorkspaceIndex () const
Get the workspace index.
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Set MatrixWorkspace.
Protected Member Functions
void functionDeriv (const API::FunctionDomain &domain, API::Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
void functionDerivLocal (API::Jacobian *out, const double *xValues, const size_t nData) override
Derivative evaluation method. Default is to calculate numerically.
void functionLocal (double *out, const double *xValues, const size_t nData) const override
Function evaluation method to be implemented in the inherited classes.
void init () override
overwrite IFunction base class method, which declare function parameters
Protected Member Functions inherited from Mantid::API::IPeakFunction
virtual IntegrationResultCache integrate () const
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::IFunction1D
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Private Member Functions
void calWavelengthAtEachDataPoint (const double *xValues, const size_t &nData) const
method for updating m_waveLength
void constFunction (double *out, const double *xValues, const int &nData) const
calculate the const function
void convertVoigtToPseudo (const double &voigtSigmaSq, const double &voigtGamma, double &H, double &eta) const
convert voigt params to pseudo voigt params
void lowerConstraint0 (const std::string &paramName)
constrain all parameters to be non-negative
Private Attributes
std::vector< double > m_waveLength
container for storing wavelength values for each data point
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Types inherited from Mantid::API::IFunction1D
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Protected Attributes inherited from Mantid::API::IFunctionMW
std::weak_ptr< const API::MatrixWorkspace > m_workspace
Keep a weak pointer to the workspace.
size_t m_workspaceIndex
An index to a spectrum.
Static Protected Attributes inherited from Mantid::API::IFunction1D
static Kernel::Logger g_log
Logger instance.
Detailed Description
Provide Ikeda-Carpenter-pseudo-Voigt peak shape function interface to IPeakFunction.
See wiki page www.mantidproject.org/IkedaCarpenterPV for documentation for this function.
Author
Anders Markvardsen, ISIS, RAL
Date
3/11/2009
Definition at line 27 of file IkedaCarpenterPV.h.
Member Function Documentation
calWavelengthAtEachDataPoint()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::calWavelengthAtEachDataPoint (const double * xValues, const size_t & nData) const private
method for updating m_waveLength
Method for updating m_waveLength.
If size of m_waveLength is equal to number of data (for a new instance of this class this vector is empty initially) then don't recalculate it.
Parameters
xValues :: x values
nData :: length of xValues
Definition at line 141 of file IkedaCarpenterPV.cpp.
References Mantid::API::IFunction::convertValue(), Mantid::API::g_log, Mantid::API::IFunctionMW::getMatrixWorkspace(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_waveLength, Mantid::API::IFunctionMW::m_workspaceIndex, and Mantid::Kernel::Logger::warning().
Referenced by constFunction(), and functionLocal().
category()
const std::string Mantid::CurveFitting::Functions::IkedaCarpenterPV::category () const inline override virtual
The categories the Fit function belong to.
Categories must be listed as a semi colon separated list. For example: "General, Muon\\Custom" which adds a function to the category "General" and the sub-category "Muon\\Custom"
Reimplemented from Mantid::API::IFunction.
Definition at line 39 of file IkedaCarpenterPV.h.
centre()
double Mantid::CurveFitting::Functions::IkedaCarpenterPV::centre () const override virtual
overwrite IPeakFunction base class methods
Implements Mantid::API::IFunctionWithLocation.
Definition at line 47 of file IkedaCarpenterPV.cpp.
Referenced by height(), and setMatrixWorkspace().
constFunction()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::constFunction (double * out, const double * xValues, const int & nData) const private
calculate the const function
Definition at line 210 of file IkedaCarpenterPV.cpp.
References calWavelengthAtEachDataPoint(), convertVoigtToPseudo(), Mantid::CurveFitting::SpecialFunctionSupport::exponentialIntegral(), Mantid::API::g_log, Mantid::API::IFunction::getParameter(), m_waveLength, Mantid::Kernel::Logger::warning(), Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by height().
convertVoigtToPseudo()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::convertVoigtToPseudo (const double & voigtSigmaSq, const double & voigtGamma, double & H, double & eta) const private
convert voigt params to pseudo voigt params
Parameters
voigtSigmaSq :: voigt param
voigtGamma :: voigt param
H :: pseudo voigt param
eta :: pseudo voigt param
Definition at line 189 of file IkedaCarpenterPV.cpp.
References tmp.
Referenced by constFunction(), and functionLocal().
functionDeriv()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionDeriv (const API::FunctionDomain & domain, API::Jacobian & jacobian) override protected virtual
Derivatives of function with respect to active parameters.
Base class implementation calculates the derivatives numerically.
Parameters
domain :: The domain of the function
jacobian :: A Jacobian matrix. It is expected to have dimensions of domain.size() by nParams().
Reimplemented from Mantid::API::IFunction.
Definition at line 369 of file IkedaCarpenterPV.cpp.
References Mantid::API::IFunction::calNumericalDeriv().
functionDerivLocal()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionDerivLocal (API::Jacobian * jacobian, const double * xValues, const size_t nData) override protected virtual
Derivative evaluation method. Default is to calculate numerically.
Computes the function derivative numerically.
Parameters
jacobian An output Jacobian to receive the calculated values
xValues An input array of X data
nData The number of X values provided
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 364 of file IkedaCarpenterPV.cpp.
functionLocal()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionLocal (double * out, const double * xValues, const size_t nData) const override protected virtual
Function evaluation method to be implemented in the inherited classes.
Implements Mantid::API::IPeakFunction.
Definition at line 287 of file IkedaCarpenterPV.cpp.
References calWavelengthAtEachDataPoint(), convertVoigtToPseudo(), Mantid::CurveFitting::SpecialFunctionSupport::exponentialIntegral(), Mantid::API::g_log, Mantid::API::IFunction::getParameter(), m_waveLength, Mantid::Kernel::Logger::warning(), Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
fwhm()
double Mantid::CurveFitting::Functions::IkedaCarpenterPV::fwhm () const override virtual
Returns the peak FWHM.
Implements Mantid::API::IPeakFunction.
Definition at line 75 of file IkedaCarpenterPV.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, and Mantid::API::IFunction::getParameter().
height()
double Mantid::CurveFitting::Functions::IkedaCarpenterPV::height () const override virtual
Returns the height of the function.
For a background function this may return an average height of the background. For a peak function this return value is the height of the peak
Implements Mantid::API::IFunctionWithLocation.
Definition at line 65 of file IkedaCarpenterPV.cpp.
References centre(), and constFunction().
Referenced by setHeight().
init()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::init () override protected virtual
overwrite IFunction base class method, which declare function parameters
Reimplemented from Mantid::API::IFunction.
Definition at line 104 of file IkedaCarpenterPV.cpp.
References Mantid::API::IFunction::declareParameter(), and lowerConstraint0().
intensity()
double Mantid::CurveFitting::Functions::IkedaCarpenterPV::intensity () const override virtual
Returns the integral intensity of the peak.
Reimplemented from Mantid::API::IPeakFunction.
Definition at line 374 of file IkedaCarpenterPV.cpp.
References Mantid::API::IPeakFunction::getDomainInterval(), Mantid::API::PeakFunctionIntegrator::integrate(), and Mantid::API::IntegrationResult::result.
lowerConstraint0()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::lowerConstraint0 (const std::string & paramName) private
constrain all parameters to be non-negative
Definition at line 126 of file IkedaCarpenterPV.cpp.
References Mantid::API::IFunction::addConstraint().
Referenced by init().
name()
std::string Mantid::CurveFitting::Functions::IkedaCarpenterPV::name () const inline override virtual
overwrite IFunction base class methods
Implements Mantid::API::IFunction.
Definition at line 38 of file IkedaCarpenterPV.h.
setCentre()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::setCentre (const double c) override virtual
Sets the parameters such that centre == c.
Implements Mantid::API::IFunctionWithLocation.
Definition at line 102 of file IkedaCarpenterPV.cpp.
References Mantid::API::IPeakFunction::setParameter().
setFwhm()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::setFwhm (const double w) override virtual
Sets the parameters such that FWHM = w.
Implements Mantid::API::IPeakFunction.
Definition at line 97 of file IkedaCarpenterPV.cpp.
References Mantid::API::IPeakFunction::setParameter().
setHeight()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::setHeight (const double h) override virtual
Sets the parameters such that height == h.
Implements Mantid::API::IFunctionWithLocation.
Definition at line 49 of file IkedaCarpenterPV.cpp.
References height(), and Mantid::API::IPeakFunction::setParameter().
setMatrixWorkspace()
void Mantid::CurveFitting::Functions::IkedaCarpenterPV::setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX) override virtual
Set MatrixWorkspace.
Initialize the function providing it the workspace.
Parameters
workspace :: The workspace to set
wi :: The workspace index
startX :: The lower bin index
endX :: The upper bin index
Reimplemented from Mantid::API::IFunctionMW.
Definition at line 383 of file IkedaCarpenterPV.cpp.
References centre(), Mantid::API::IFunction::convertValue(), Mantid::API::IFunction::getParameter(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::API::IFunction::isActive(), Mantid::API::IFunction::parameterIndex(), Mantid::API::IFunctionMW::setMatrixWorkspace(), Mantid::API::IPeakFunction::setParameter(), and workspace.
Member Data Documentation
m_waveLength
std::vector<double> Mantid::CurveFitting::Functions::IkedaCarpenterPV::m_waveLength mutable private
container for storing wavelength values for each data point
Definition at line 57 of file IkedaCarpenterPV.h.
Referenced by calWavelengthAtEachDataPoint(), constFunction(), and functionLocal().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/IkedaCarpenterPV.h
Framework/CurveFitting/src/Functions/IkedaCarpenterPV.cpp