Mantid: Mantid::DataHandling::AvrgDetector Class Reference
Mantid::DataHandling::AvrgDetector Class Reference
helper class-collection to keep together the parameters, which characterize average composite detector and help to calculate these parameters
#include <FindDetectorsPar.h>
Public Member Functions
void addDetInfo (const Geometry::IDetector &det, const Kernel::V3D &Observer)
method to cacluate the detectors parameters and add them to the detectors averages
AvrgDetector ()
void returnAvrgDetPar (DetParameters &avrgDet)
Method processes accumulated averages and return them in preexistent avrgDet class.
void setUseSpherical (bool shouldWe=true)
Static Public Member Functions
static double nearAngle (const double &baseAngle, const double &anAngle)
method calculates an angle closest to the initial one taken on a ring e.g.
Private Attributes
double m_AzimBase
double m_AzimMax
double m_AzimMin
double m_AzimutSum
double m_FlightPathSum
size_t m_nComponents
numbr of primary detectors, contributing into this detector
double m_PolarBase
double m_PolarMax
double m_PolarMin
double m_PolarSum
bool m_useSphericalSizes
Detailed Description
helper class-collection to keep together the parameters, which characterize average composite detector and help to calculate these parameters
Definition at line 223 of file FindDetectorsPar.h.
Constructor & Destructor Documentation
AvrgDetector()
Mantid::DataHandling::AvrgDetector::AvrgDetector () inline
Definition at line 235 of file FindDetectorsPar.h.
Member Function Documentation
addDetInfo()
void Mantid::DataHandling::AvrgDetector::addDetInfo (const Geometry::IDetector & det, const Kernel::V3D & Observer)
method to cacluate the detectors parameters and add them to the detectors averages
Parameters
det – reference to the Mantid Detector
Observer – sample position or the centre of the polar system of coordinates to calculate detector's parameters.
Definition at line 196 of file FindDetectorsPar.cpp.
References Mantid::Kernel::V3D::cross_prod(), Mantid::Geometry::IComponent::getBoundingBox(), Mantid::Geometry::IComponent::getPos(), Mantid::Kernel::V3D::getSpherical(), m_AzimBase, m_AzimMax, m_AzimMin, m_AzimutSum, m_FlightPathSum, m_nComponents, m_PolarBase, m_PolarMax, m_PolarMin, m_PolarSum, m_useSphericalSizes, nearAngle(), Mantid::Kernel::V3D::normalize(), Mantid::Kernel::V3D::nullVector(), Mantid::DataHandling::rad2deg, Mantid::Geometry::BoundingBox::setBoxAlignment(), Mantid::Geometry::BoundingBox::yMax(), Mantid::Geometry::BoundingBox::yMin(), Mantid::Kernel::V3D::Z(), Mantid::Geometry::BoundingBox::zMax(), and Mantid::Geometry::BoundingBox::zMin().
Referenced by Mantid::DataHandling::FindDetectorsPar::calcDetPar().
nearAngle()
double Mantid::DataHandling::AvrgDetector::nearAngle (const double & baseAngle, const double & anAngle) static
method calculates an angle closest to the initial one taken on a ring e.g.
given inital angle 179 deg and another one -179 closest one to 179 is 181
Parameters
baseAngle – the angle to be close to
anAngle – the angle which ring image may be requested
Returns
– the angle closest to the initial on a ring.
Definition at line 180 of file FindDetectorsPar.cpp.
Referenced by addDetInfo().
returnAvrgDetPar()
void Mantid::DataHandling::AvrgDetector::returnAvrgDetPar (DetParameters & avrgDet)
Method processes accumulated averages and return them in preexistent avrgDet class.
Definition at line 284 of file FindDetectorsPar.cpp.
References Mantid::DataHandling::DetParameters::azimutAngle, Mantid::DataHandling::DetParameters::azimWidth, m_AzimMax, m_AzimMin, m_AzimutSum, m_FlightPathSum, m_nComponents, m_PolarMax, m_PolarMin, m_PolarSum, Mantid::DataHandling::DetParameters::polarAngle, Mantid::DataHandling::DetParameters::polarWidth, and Mantid::DataHandling::DetParameters::secondaryFlightPath.
Referenced by Mantid::DataHandling::FindDetectorsPar::calcDetPar().
setUseSpherical()
void Mantid::DataHandling::AvrgDetector::setUseSpherical (bool shouldWe = true) inline
Definition at line 241 of file FindDetectorsPar.h.
References m_useSphericalSizes.
Referenced by Mantid::DataHandling::FindDetectorsPar::calcDetPar().
Member Data Documentation
m_AzimBase
double Mantid::DataHandling::AvrgDetector::m_AzimBase private
Definition at line 227 of file FindDetectorsPar.h.
Referenced by addDetInfo().
m_AzimMax
double Mantid::DataHandling::AvrgDetector::m_AzimMax private
Definition at line 230 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_AzimMin
double Mantid::DataHandling::AvrgDetector::m_AzimMin private
Definition at line 230 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_AzimutSum
double Mantid::DataHandling::AvrgDetector::m_AzimutSum private
Definition at line 224 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_FlightPathSum
double Mantid::DataHandling::AvrgDetector::m_FlightPathSum private
Definition at line 226 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_nComponents
size_t Mantid::DataHandling::AvrgDetector::m_nComponents private
numbr of primary detectors, contributing into this detector
Definition at line 232 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_PolarBase
double Mantid::DataHandling::AvrgDetector::m_PolarBase private
Definition at line 227 of file FindDetectorsPar.h.
Referenced by addDetInfo().
m_PolarMax
double Mantid::DataHandling::AvrgDetector::m_PolarMax private
Definition at line 230 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_PolarMin
double Mantid::DataHandling::AvrgDetector::m_PolarMin private
Definition at line 230 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_PolarSum
double Mantid::DataHandling::AvrgDetector::m_PolarSum private
Definition at line 225 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and returnAvrgDetPar().
m_useSphericalSizes
bool Mantid::DataHandling::AvrgDetector::m_useSphericalSizes private
Definition at line 229 of file FindDetectorsPar.h.
Referenced by addDetInfo(), and setUseSpherical().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/FindDetectorsPar.h
Framework/DataHandling/src/FindDetectorsPar.cpp