Mantid: Mantid::Kernel::spline Namespace Reference
Mantid::Kernel::spline Namespace Reference
Classes
struct GSLFree
Functor to free a GSL objects in a unique pointer.
Typedefs
using accel_uptr = std::unique_ptr< gsl_interp_accel, GSLFree >
using spline_uptr = std::unique_ptr< gsl_spline, GSLFree >
Functions
template<typename X , typename Y >
spline_uptr make_cubic_spline (std::span< X const > x, std::span< Y const > y)
accel_uptr make_interp_accel ()
template<typename X , typename Y >
spline_uptr make_spline (std::span< X const > x, std::span< Y const > y, gsl_interp_type const *type)
Variables
constexpr unsigned int MIN_CSPLINE_POINTS {3}
Minimum number of points needed to fit a cubic spline in GSL.
Typedef Documentation
accel_uptr
using Mantid::Kernel::spline::accel_uptr = typedef std::unique_ptr<gsl_interp_accel, GSLFree>
Definition at line 49 of file GSL_Helpers.h.
spline_uptr
using Mantid::Kernel::spline::spline_uptr = typedef std::unique_ptr<gsl_spline, GSLFree>
Definition at line 50 of file GSL_Helpers.h.
Function Documentation
make_cubic_spline()
template<typename X , typename Y > spline_uptr Mantid::Kernel::spline::make_cubic_spline (std::span< X const > x, std::span< Y const > y)
Definition at line 80 of file GSL_Helpers.h.
References make_spline(), MIN_CSPLINE_POINTS, Mantid::Kernel::Strings::strmakef(), Mantid::Geometry::x, and Mantid::Geometry::y.
make_interp_accel()
accel_uptr Mantid::Kernel::spline::make_interp_accel () inline
Definition at line 52 of file GSL_Helpers.h.
make_spline()
template<typename X , typename Y > spline_uptr Mantid::Kernel::spline::make_spline (std::span< X const > x, std::span< Y const > y, gsl_interp_type const * type)
Definition at line 61 of file GSL_Helpers.h.
References Mantid::Kernel::Strings::strmakef(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by make_cubic_spline().
Variable Documentation
MIN_CSPLINE_POINTS
constexpr unsigned int Mantid::Kernel::spline::MIN_CSPLINE_POINTS {3} constexpr
Minimum number of points needed to fit a cubic spline in GSL.
Definition at line 41 of file GSL_Helpers.h.
Referenced by make_cubic_spline(), and Mantid::Algorithms::AddLogInterpolated::validateInputs().