Mantid: Mantid::DataObjects::AffineMatrixParameter Class Reference
Mantid::DataObjects::AffineMatrixParameter Class Reference
Type to wrap an affine matrix and allow serialization via xml.
#include <AffineMatrixParameter.h>
Public Member Functions
AffineMatrixParameter (const AffineMatrixParameter &)
Copy constructor.
AffineMatrixParameter (size_t outD, size_t inD)
Constructor.
AffineMatrixParameter * clone () const override
Clone the parameter.
AffineMatrixType getAffineMatrix () const
Gets copy of internal affine matrix.
std::string getName () const override
Get the name of the parameter.
coord_t ** getRawMatrix ()
Get the matrix in its raw array form.
bool isValid () const override
Getter for the valid status.
AffineMatrixParameter & operator= (const AffineMatrixParameter &other)
Assignment operator.
void setMatrix (const AffineMatrixType &newMatrix)
Setter for the internal affine matrix.
std::string toXMLString () const override
Serialize the Affine Matrix Parameter.
~AffineMatrixParameter () override
Destructor.
Public Member Functions inherited from Mantid::API::ImplicitFunctionParameter
virtual ImplicitFunctionParameter * clone () const =0
virtual std::string getName () const =0
virtual bool isValid () const =0
virtual std::string toXMLString () const =0
virtual ~ImplicitFunctionParameter ()=default
Static Public Member Functions
static std::string parameterName ()
Gets the type parameter name.
Private Member Functions
void copyRawMatrix ()
Copy elements from affinematrix into raw array.
Private Attributes
AffineMatrixType m_affineMatrix
Affine matrix.
coord_t ** m_rawMatrix
Raw matrix used for speed (array of pointers to columns).
coord_t * m_rawMem
pointer to large memory block (matrix)
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::ImplicitFunctionParameter
std::string parameterXMLTemplate (const std::string &valueXMLtext) const
Protected Attributes inherited from Mantid::API::ImplicitFunctionParameter
bool m_isValid {false}
Detailed Description
Type to wrap an affine matrix and allow serialization via xml.
Author
Owen Arnold
Date
20/07/2011
Definition at line 24 of file AffineMatrixParameter.h.
Constructor & Destructor Documentation
AffineMatrixParameter() [1/2]
Mantid::DataObjects::AffineMatrixParameter::AffineMatrixParameter (size_t outD, size_t inD)
Constructor.
Parameters
outD the number of output dimensions
inD the nubmer of input dimensions
Definition at line 17 of file AffineMatrixParameter.cpp.
References copyRawMatrix(), Mantid::Kernel::Matrix< T >::identityMatrix(), m_affineMatrix, Mantid::API::ImplicitFunctionParameter::m_isValid, m_rawMatrix, m_rawMem, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
AffineMatrixParameter() [2/2]
Mantid::DataObjects::AffineMatrixParameter::AffineMatrixParameter (const AffineMatrixParameter & other)
Copy constructor.
Parameters
other : another affine matrix to copy from.
Definition at line 141 of file AffineMatrixParameter.cpp.
References copyRawMatrix(), m_affineMatrix, Mantid::API::ImplicitFunctionParameter::m_isValid, m_rawMatrix, m_rawMem, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
~AffineMatrixParameter()
Mantid::DataObjects::AffineMatrixParameter::~AffineMatrixParameter () override
Destructor.
Definition at line 34 of file AffineMatrixParameter.cpp.
References m_rawMatrix, and m_rawMem.
Member Function Documentation
clone()
AffineMatrixParameter * Mantid::DataObjects::AffineMatrixParameter::clone () const override virtual
Clone the parameter.
Returns
Cloned parameter.
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 105 of file AffineMatrixParameter.cpp.
References m_affineMatrix, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
copyRawMatrix()
void Mantid::DataObjects::AffineMatrixParameter::copyRawMatrix () private
Copy elements from affinematrix into raw array.
Definition at line 46 of file AffineMatrixParameter.cpp.
References m_affineMatrix, m_rawMatrix, Mantid::Kernel::Matrix< T >::numCols(), Mantid::Kernel::Matrix< T >::numRows(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by AffineMatrixParameter(), operator=(), and setMatrix().
getAffineMatrix()
AffineMatrixType Mantid::DataObjects::AffineMatrixParameter::getAffineMatrix () const
Gets copy of internal affine matrix.
Returns
A copy of the underlying affine matrix.
Definition at line 57 of file AffineMatrixParameter.cpp.
References m_affineMatrix.
getName()
std::string Mantid::DataObjects::AffineMatrixParameter::getName () const override virtual
Get the name of the parameter.
Returns
Parameter name.
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 71 of file AffineMatrixParameter.cpp.
References parameterName().
getRawMatrix()
coord_t ** Mantid::DataObjects::AffineMatrixParameter::getRawMatrix ()
Get the matrix in its raw array form.
Returns
the matrix as an array.
Definition at line 64 of file AffineMatrixParameter.cpp.
References m_rawMatrix.
isValid()
bool Mantid::DataObjects::AffineMatrixParameter::isValid () const override virtual
Getter for the valid status.
Returns
The valid status. i.e. has setMatrix been called.
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 114 of file AffineMatrixParameter.cpp.
References Mantid::API::ImplicitFunctionParameter::m_isValid.
operator=()
AffineMatrixParameter & Mantid::DataObjects::AffineMatrixParameter::operator= (const AffineMatrixParameter & other)
Assignment operator.
Parameters
other : another affine matrix to assign from.
Returns
ref to assigned object
Definition at line 122 of file AffineMatrixParameter.cpp.
References copyRawMatrix(), m_affineMatrix, and Mantid::API::ImplicitFunctionParameter::m_isValid.
parameterName()
static std::string Mantid::DataObjects::AffineMatrixParameter::parameterName () inline static
Gets the type parameter name.
Returns
parameter name.
Definition at line 44 of file AffineMatrixParameter.h.
Referenced by Mantid::DataObjects::AffineMatrixParameterParser::createParameter(), and getName().
setMatrix()
void Mantid::DataObjects::AffineMatrixParameter::setMatrix (const AffineMatrixType & newMatrix)
Setter for the internal affine matrix.
Parameters
newMatrix : new matrix to use.
Definition at line 158 of file AffineMatrixParameter.cpp.
References copyRawMatrix(), m_affineMatrix, Mantid::API::ImplicitFunctionParameter::m_isValid, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
Referenced by Mantid::DataObjects::CoordTransformAffine::toXMLString().
toXMLString()
std::string Mantid::DataObjects::AffineMatrixParameter::toXMLString () const override virtual
Serialize the Affine Matrix Parameter.
Returns
the object as serialized. Xml in a std::string.
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 78 of file AffineMatrixParameter.cpp.
References Mantid::Kernel::Matrix< T >::getVector(), m_affineMatrix, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::API::ImplicitFunctionParameter::parameterXMLTemplate().
Referenced by Mantid::DataObjects::CoordTransformAffine::toXMLString().
Member Data Documentation
m_affineMatrix
AffineMatrixType Mantid::DataObjects::AffineMatrixParameter::m_affineMatrix private
Affine matrix.
Definition at line 55 of file AffineMatrixParameter.h.
Referenced by AffineMatrixParameter(), clone(), copyRawMatrix(), getAffineMatrix(), operator=(), setMatrix(), and toXMLString().
m_rawMatrix
coord_t** Mantid::DataObjects::AffineMatrixParameter::m_rawMatrix private
Raw matrix used for speed (array of pointers to columns).
Definition at line 50 of file AffineMatrixParameter.h.
Referenced by AffineMatrixParameter(), copyRawMatrix(), getRawMatrix(), and ~AffineMatrixParameter().
m_rawMem
coord_t* Mantid::DataObjects::AffineMatrixParameter::m_rawMem private
pointer to large memory block (matrix)
Definition at line 52 of file AffineMatrixParameter.h.
Referenced by AffineMatrixParameter(), and ~AffineMatrixParameter().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/AffineMatrixParameter.h
Framework/DataObjects/src/AffineMatrixParameter.cpp