Mantid: Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp File Reference
IPeak.cpp File Reference
#include "MantidGeometry/Crystal/IPeak.h"
#include "MantidGeometry/Instrument/ReferenceFrame.h"
#include "MantidPythonInterface/core/Converters/CloneToNDArray.h"
#include "MantidPythonInterface/core/Converters/PyObjectToMatrix.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/Policies/MatrixToNumpy.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include <boost/python/class.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <optional>
Functions
void export_IPeak ()
Function Documentation
export_IPeak()
void export_IPeak ()
Definition at line 58 of file IPeak.cpp.
References Mantid::Geometry::IPeak::getAbsorptionWeightedPathLength(), Mantid::Geometry::IPeak::getAzimuthal(), Mantid::Geometry::IPeak::getBinCount(), Mantid::Geometry::IPeak::getCol(), Mantid::Geometry::IPeak::getDetectorDirectionSampleFrame(), Mantid::Geometry::IPeak::getDetectorID(), Mantid::Geometry::IPeak::getDSpacing(), Mantid::Geometry::IPeak::getEnergyTransfer(), Mantid::Geometry::IPeak::getFinalEnergy(), Mantid::Geometry::IPeak::getGoniometerMatrix(), Mantid::Geometry::IPeak::getH(), Mantid::Geometry::IPeak::getHKL(), Mantid::Geometry::IPeak::getInitialEnergy(), Mantid::Geometry::IPeak::getIntensity(), Mantid::Geometry::IPeak::getIntensityOverSigma(), Mantid::Geometry::IPeak::getIntHKL(), Mantid::Geometry::IPeak::getIntMNP(), Mantid::Geometry::IPeak::getK(), Mantid::Geometry::IPeak::getL(), Mantid::Geometry::IPeak::getL1(), Mantid::Geometry::IPeak::getL2(), Mantid::Geometry::IPeak::getMonitorCount(), Mantid::Geometry::IPeak::getPeakNumber(), Mantid::Geometry::IPeak::getQLabFrame(), Mantid::Geometry::IPeak::getQSampleFrame(), Mantid::Geometry::IPeak::getReferenceFrame(), Mantid::Geometry::IPeak::getRow(), Mantid::Geometry::IPeak::getRunNumber(), Mantid::Geometry::IPeak::getSamplePos(), Mantid::Geometry::IPeak::getScattering(), Mantid::Geometry::IPeak::getSigmaIntensity(), Mantid::Geometry::IPeak::getSourceDirectionSampleFrame(), Mantid::Geometry::IPeak::getTOF(), Mantid::Geometry::IPeak::getWavelength(), Mantid::Geometry::IPeak::setAbsorptionWeightedPathLength(), Mantid::Geometry::IPeak::setBinCount(), Mantid::Geometry::IPeak::setFinalEnergy(), Mantid::Geometry::IPeak::setH(), Mantid::Geometry::IPeak::setHKL(), Mantid::Geometry::IPeak::setInitialEnergy(), Mantid::Geometry::IPeak::setIntensity(), Mantid::Geometry::IPeak::setIntHKL(), Mantid::Geometry::IPeak::setIntMNP(), Mantid::Geometry::IPeak::setK(), Mantid::Geometry::IPeak::setL(), Mantid::Geometry::IPeak::setMonitorCount(), Mantid::Geometry::IPeak::setPeakNumber(), Mantid::Geometry::IPeak::setRunNumber(), Mantid::Geometry::IPeak::setSamplePos(), Mantid::Geometry::IPeak::setSigmaIntensity(), and Mantid::Geometry::IPeak::setWavelength().