Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/MaterialBuilder.cpp File Reference
MaterialBuilder.cpp File Reference
#include "MantidKernel/MaterialBuilder.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/implicit.hpp>
#include <boost/python/make_function.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/return_arg.hpp>
#include <boost/python/return_value_policy.hpp>
Functions
void export_MaterialBuilder ()
Function Documentation
export_MaterialBuilder()
void export_MaterialBuilder ()
Definition at line 20 of file MaterialBuilder.cpp.
References Mantid::Kernel::MaterialBuilder::Atoms, Mantid::Kernel::MaterialBuilder::build(), Mantid::Kernel::MaterialBuilder::FormulaUnits, Mantid::Kernel::MaterialBuilder::setAbsorptionXSection(), Mantid::Kernel::MaterialBuilder::setAtomicNumber(), Mantid::Kernel::MaterialBuilder::setCoherentXSection(), Mantid::Kernel::MaterialBuilder::setFormula(), Mantid::Kernel::MaterialBuilder::setIncoherentXSection(), Mantid::Kernel::MaterialBuilder::setMassDensity(), Mantid::Kernel::MaterialBuilder::setMassNumber(), Mantid::Kernel::MaterialBuilder::setName(), Mantid::Kernel::MaterialBuilder::setNumberDensity(), Mantid::Kernel::MaterialBuilder::setNumberDensityUnit(), Mantid::Kernel::MaterialBuilder::setPackingFraction(), Mantid::Kernel::MaterialBuilder::setTotalScatterXSection(), Mantid::Kernel::MaterialBuilder::setUnitCellVolume(), and Mantid::Kernel::MaterialBuilder::setZParameter().