Mantid: Mantid::API::DeprecatedAlgorithm Class Reference
Mantid::API::DeprecatedAlgorithm Class Reference
Class for marking algorithms as deprecated.
#include <DeprecatedAlgorithm.h>
Public Member Functions
DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
void deprecatedDate (const std::string &)
The date the algorithm was deprecated on.
std::string deprecationMsg (const IAlgorithm *)
This merely prints the deprecation error for people to see.
void useAlgorithm (const std::string &, const int version=-1)
The algorithm to use instead of this one.
virtual ~DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
Private Attributes
std::string m_deprecatedDate
The date that the algorithm was first deprecated.
std::string m_replacementAlgorithm
The algorithm to use instead of this one.
int m_replacementVersion
Replacement version, -1 indicates latest.
Detailed Description
Class for marking algorithms as deprecated.
Author
Peter Peterson, NScD Oak Ridge National Laboratory
Date
25/02/2011
Definition at line 23 of file DeprecatedAlgorithm.h.
Constructor & Destructor Documentation
DeprecatedAlgorithm()
Mantid::API::DeprecatedAlgorithm::DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
Definition at line 20 of file DeprecatedAlgorithm.cpp.
~DeprecatedAlgorithm()
Mantid::API::DeprecatedAlgorithm::~DeprecatedAlgorithm () virtual default
Does nothing other than make the compiler happy.
Member Function Documentation
deprecatedDate()
void Mantid::API::DeprecatedAlgorithm::deprecatedDate (const std::string & date)
The date the algorithm was deprecated on.
Definition at line 42 of file DeprecatedAlgorithm.cpp.
References m_deprecatedDate.
Referenced by Mantid::MDAlgorithms::IntegratePeaksCWSD::IntegratePeaksCWSD(), Mantid::MDAlgorithms::IntegratePeaksMD::IntegratePeaksMD(), Mantid::Crystal::IntegratePeakTimeSlices::IntegratePeakTimeSlices(), Mantid::DataHandling::LoadEventPreNexus2::LoadEventPreNexus2(), Mantid::DataHandling::LoadPreNexus::LoadPreNexus(), Mantid::DataHandling::LoadPreNexusMonitors::LoadPreNexusMonitors(), Mantid::Algorithms::SofQWCentre::SofQWCentre(), Mantid::Algorithms::SofQWPolygon::SofQWPolygon(), and Mantid::Algorithms::UnwrapSNS::UnwrapSNS().
deprecationMsg()
std::string Mantid::API::DeprecatedAlgorithm::deprecationMsg (const IAlgorithm * algo)
This merely prints the deprecation error for people to see.
Definition at line 56 of file DeprecatedAlgorithm.cpp.
References Mantid::DataHandling::exists(), Mantid::API::g_log, m_deprecatedDate, m_replacementAlgorithm, m_replacementVersion, Mantid::API::IAlgorithm::name(), and Mantid::Kernel::Logger::warning().
useAlgorithm()
void Mantid::API::DeprecatedAlgorithm::useAlgorithm (const std::string & replacement, const int version = -1)
The algorithm to use instead of this one.
Parameters
replacement Name of the algorithm that replaces the deprecated one
version An optional version number for the replacement (default=-1)
Definition at line 28 of file DeprecatedAlgorithm.cpp.
References m_replacementAlgorithm, and m_replacementVersion.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD::IntegratePeaksMD(), Mantid::DataHandling::LoadAscii::LoadAscii(), Mantid::Algorithms::SofQWCentre::SofQWCentre(), and Mantid::Algorithms::SofQWPolygon::SofQWPolygon().
Member Data Documentation
m_deprecatedDate
std::string Mantid::API::DeprecatedAlgorithm::m_deprecatedDate private
The date that the algorithm was first deprecated.
Definition at line 39 of file DeprecatedAlgorithm.h.
Referenced by deprecatedDate(), and deprecationMsg().
m_replacementAlgorithm
std::string Mantid::API::DeprecatedAlgorithm::m_replacementAlgorithm private
The algorithm to use instead of this one.
Definition at line 35 of file DeprecatedAlgorithm.h.
Referenced by deprecationMsg(), and useAlgorithm().
m_replacementVersion
int Mantid::API::DeprecatedAlgorithm::m_replacementVersion private
Replacement version, -1 indicates latest.
Definition at line 37 of file DeprecatedAlgorithm.h.
Referenced by deprecationMsg(), and useAlgorithm().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/DeprecatedAlgorithm.h
Framework/API/src/DeprecatedAlgorithm.cpp