Mantid: ICat4::ns1__user Class Reference
ICat4::ns1__user Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__user ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * fullName
std::vector< ns1__instrumentScientist * > instrumentScientists
std::vector< ns1__investigationUser * > investigationUsers
std::string * name
std::vector< ns1__study * > studies
std::vector< ns1__userGroup * > userGroups
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1792 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__user()
ICat4::ns1__user::ns1__user () inline
Definition at line 1809 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__user::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14142 of file ICat4C.cpp.
References fullName, instrumentScientists, investigationUsers, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__instrumentScientist(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationUser(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__study(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__userGroup(), studies, and userGroups.
Referenced by ICat4::soap_in_ns1__user(), ICat4::soap_new_req_ns1__user(), and ICat4::soap_new_set_ns1__user().
soap_get()
void * ICat4::ns1__user::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14316 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__user().
soap_in()
void * ICat4::ns1__user::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14204 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__user().
Referenced by ICat4::soap_in_ns1__user().
soap_out()
int ICat4::ns1__user::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14168 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__user().
Referenced by soap_put().
soap_put()
int ICat4::ns1__user::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14309 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__user.
soap_serialize()
void ICat4::ns1__user::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14154 of file ICat4C.cpp.
References fullName, instrumentScientists, investigationUsers, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__instrumentScientist(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationUser(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__study(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__userGroup(), studies, and userGroups.
Referenced by ICat4::soap_serialize_PointerTons1__instrumentScientist().
soap_type()
int ICat4::ns1__user::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1802 of file ICat4Stub.h.
Member Data Documentation
fullName
std::string* ICat4::ns1__user::fullName
Definition at line 1794 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
instrumentScientists
std::vector<ns1__instrumentScientist *> ICat4::ns1__user::instrumentScientists
Definition at line 1795 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigationUsers
std::vector<ns1__investigationUser *> ICat4::ns1__user::investigationUsers
Definition at line 1797 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__user::name
Definition at line 1798 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
studies
std::vector<ns1__study *> ICat4::ns1__user::studies
Definition at line 1799 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
userGroups
std::vector<ns1__userGroup *> ICat4::ns1__user::userGroups
Definition at line 1800 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp