Mantid: MantidQt::MantidWidgets::PythonHelpBridge Class Reference
MantidQt::MantidWidgets::PythonHelpBridge Class Reference
#include <PythonHelpBridge.h>
Public Member Functions
PythonHelpBridge ()
void showHelpPage (const std::string &relative_url)
Detailed Description
Definition at line 15 of file PythonHelpBridge.h.
Constructor & Destructor Documentation
PythonHelpBridge()
MantidQt::MantidWidgets::PythonHelpBridge::PythonHelpBridge ()
Definition at line 30 of file PythonHelpBridge.cpp.
Member Function Documentation
showHelpPage()
void MantidQt::MantidWidgets::PythonHelpBridge::showHelpPage (const std::string & relative_url)
Definition at line 32 of file PythonHelpBridge.cpp.
Referenced by MantidQt::MantidWidgets::PythonHelpWindow::showPage(), MantidQt::MantidWidgets::PythonHelpWindow::showPage(), and MantidQt::MantidWidgets::PythonHelpWindow::showPage().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/PythonHelpBridge.h
qt/widgets/common/src/PythonHelpBridge.cpp