Mantid: MantidQt::MantidWidgets::WorkspaceTreeWidget Class Reference
MantidQt::MantidWidgets::WorkspaceTreeWidget Class Reference
#include <WorkspaceTreeWidget.h>
Public Slots
void chooseByLastModified ()
void chooseByMemorySize ()
void chooseByName ()
void clickedWorkspace (QTreeWidgetItem *, int)
void keyPressEvent (QKeyEvent *) override
void onClickClearWorkspaces ()
Handles clear button trigger.
void onClickDeleteWorkspaces ()
Handles delete button/menu item triggers.
void onClickSaveToProgram (const QString &name)
void populateChildData (QTreeWidgetItem *item)
When an item is expanded, populate the child data for this item.
void renameWorkspace ()
void saveWorkspaceCollection ()
void sortAscending ()
void sortDescending ()
Signals
void signalClearView ()
void signalUpdateTree (const TopLevelItems &)
Public Member Functions
bool askUserYesNo (const std::string &caption, const std::string &message) const override
void clearView () override
bool clearWorkspacesConfirmation () const override
Gets confirmation from user that they meant to press clear workspaces button.
void convertMDHistoToMatrixWorkspace () override
void convertToMatrixWorkspace () override
bool deleteConfirmation () const override
void deleteWorkspaces (const MantidQt::MantidWidgets::StringList &wsNames) override
void dropEvent (QDropEvent *de) override
Accept a drag drop event and process the data appropriately.
void enableClearButton (bool enable) override
Enables and disables the Clear Workspaces Button.
void enableDeletePrompt (bool enable) override
bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=true) override
Allows asynchronous execution of algorithms.
void filterWorkspaces (const std::string &filterText) override
std::string getFilterText () const override
MantidQt::MantidWidgets::WorkspacePresenterWN_wptr getPresenterWeakPtr () override
SaveFileType getSaveFileType () const override
Mantid::API::Workspace_sptr getSelectedWorkspace () const override
Returns a pointer to the selected workspace (the first if multiple workspaces selected)
MantidQt::MantidWidgets::StringList getSelectedWorkspaceNames () const override
Returns the names of the selected workspaces in the dock.
QStringList getSelectedWorkspaceNamesAsQList () const
SortCriteria getSortCriteria () const override
SortDirection getSortDirection () const override
bool isPromptDelete () const override
void plotSpectrum (const std::string &type) override
Plots one or more spectra from each selected workspace.
void popupContextMenu () override
void recordWorkspaceRename (const std::string &oldName, const std::string &newName) override
Save the old and the new name in m_renameMap.
void refreshWorkspaces () override
void saveToProgram () override
Saves a workspace based on the program the user chooses to save to.
void saveWorkspace (const std::string &wsName, SaveFileType type) override
void saveWorkspaces (const MantidQt::MantidWidgets::StringList &wsNames) override
void showAlgorithmHistory () override
void showBoxDataTable () override
void showColourFillPlot () override
Draw a color fill plot of the workspaces that are currently selected.
void showCriticalUserMessage (const std::string &caption, const std::string &message) const override
void showDetectorsTable () override
void showInstrumentView () override
void showListData () override
void showLiveDataDialog () override
void showLoadDialog () override
void showLogs () override
void showMDPlot () override
void showRenameDialog (const MantidQt::MantidWidgets::StringList &wsNames) override
void showSampleMaterialWindow () override
void showSliceViewer () override
void showSpectrumViewer () override
void showTransposed () override
void showWorkspaceData () override
void sortWorkspaces (SortCriteria criteria, SortDirection direction) override
WorkspaceTreeWidget (MantidQt::MantidWidgets::MantidDisplayBase *mdb, bool viewOnly=false, QWidget *parent=nullptr)
~WorkspaceTreeWidget ()
Public Member Functions inherited from MantidQt::MantidWidgets::IWorkspaceDockView
virtual bool askUserYesNo (const std::string &caption, const std::string &message) const =0
virtual void clearView ()=0
virtual bool clearWorkspacesConfirmation () const =0
virtual void convertMDHistoToMatrixWorkspace ()=0
virtual void convertToMatrixWorkspace ()=0
virtual bool deleteConfirmation () const =0
virtual void deleteWorkspaces (const StringList &wsNames)=0
virtual void enableClearButton (bool enable)=0
virtual void enableDeletePrompt (bool enable)=0
virtual bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=true)=0
virtual void filterWorkspaces (const std::string &filterText)=0
virtual std::string getFilterText () const =0
virtual WorkspacePresenterWN_wptr getPresenterWeakPtr ()=0
virtual SaveFileType getSaveFileType () const =0
virtual Mantid::API::Workspace_sptr getSelectedWorkspace () const =0
virtual StringList getSelectedWorkspaceNames () const =0
virtual SortCriteria getSortCriteria () const =0
virtual SortDirection getSortDirection () const =0
virtual bool isPromptDelete () const =0
virtual void plotSpectrum (const std::string &type)=0
virtual void popupContextMenu ()=0
virtual void recordWorkspaceRename (const std::string &oldName, const std::string &newName)=0
virtual void refreshWorkspaces ()=0
virtual void saveToProgram ()=0
virtual void saveWorkspace (const std::string &wsName, const SaveFileType type)=0
virtual void saveWorkspaces (const StringList &wsNames)=0
virtual void showAlgorithmHistory ()=0
virtual void showBoxDataTable ()=0
virtual void showColourFillPlot ()=0
virtual void showCriticalUserMessage (const std::string &caption, const std::string &message) const =0
virtual void showDetectorsTable ()=0
virtual void showInstrumentView ()=0
virtual void showListData ()=0
virtual void showLiveDataDialog ()=0
virtual void showLoadDialog ()=0
virtual void showLogs ()=0
virtual void showMDPlot ()=0
virtual void showRenameDialog (const StringList &wsNames)=0
virtual void showSampleMaterialWindow ()=0
virtual void showSliceViewer ()=0
virtual void showSpectrumViewer ()=0
virtual void showTransposed ()=0
virtual void showWorkspaceData ()=0
virtual void sortWorkspaces (SortCriteria criteria, SortDirection direction)=0
virtual void updateTree (const std::map< std::string, Mantid::API::Workspace_sptr > &items)=0
virtual ~IWorkspaceDockView ()
Protected Slots
void popupMenu (const QPoint &pos)
Handles display of the workspace context menu.
void workspaceSelected ()
Protected Attributes
QAction * m_delete
QMenu * m_loadMenu
QPoint m_menuPosition
QAction * m_program
QSignalMapper * m_programMapper
QAction * m_rename
QAction * m_saveNexus
QMenu * m_saveToProgram
MantidTreeWidget * m_tree
QString selectedWsName
Private Slots
void filterWorkspaceTree (const QString &text)
Filter workspaces based on the string provided.
void handleClearView ()
void handleShowSaveAlgorithm ()
void handleUpdateTree (const TopLevelItems &)
Handle asynchronous tree update.
void incrementUpdateCount ()
void onClickClearUB ()
Handler for the clear the UB matrix event.
void onClickConvertMDHistoToMatrixWorkspace ()
Convert selected MDHistoWorkspace to a MatrixWorkspace.
void onClickConvertToMatrixWorkspace ()
Convert selected TableWorkspace to a MatrixWorkspace.
void onClickDrawColorFillPlot ()
void onClickGroupButton ()
Handles group button clicks.
void onClickLiveData ()
handles Live Data menu trigger
void onClickLoad ()
Handles Load File menu trigger.
void onClickPlotAdvanced ()
void onClickPlotSpectra ()
void onClickPlotSpectraErr ()
void onClickSaveNexusWorkspace ()
void onClickShowAlgHistory ()
void onClickShowBoxData ()
void onClickShowData ()
void onClickShowDetectorTable ()
void onClickShowFileLog ()
void onClickShowInstrument ()
void onClickShowListData ()
void onClickShowMDPlot ()
void onClickShowSampleMaterial ()
void onClickShowSliceViewer ()
void onClickShowSpectrumViewer ()
void onClickShowTransposed ()
void onLoadAccept ()
void onTreeSelectionChanged ()
Private Member Functions
void addClearMenuItems (QMenu *menu, const QString &wsName)
Add menu for clearing workspace items.
void addMatrixWorkspaceMenuItems (QMenu *menu, const Mantid::API::MatrixWorkspace_const_sptr &matrixWS) const
Add the actions that are appropriate for a MatrixWorkspace.
void addMDEventWorkspaceMenuItems (QMenu *menu, const Mantid::API::IMDEventWorkspace_const_sptr &mdeventWS) const
Add the actions that are appropriate for a MDEventWorkspace.
void addMDHistoWorkspaceMenuItems (QMenu *menu, const Mantid::API::IMDWorkspace_const_sptr &WS) const
void addPeaksWorkspaceMenuItems (QMenu *menu, const Mantid::API::IPeaksWorkspace_const_sptr &WS) const
Add the actions that are appropriate for a PeaksWorkspace.
void addSaveMenuOption (const QString &algorithmString, QString menuEntryName="")
Adds an algorithm to the save menu.
void addTableWorkspaceMenuItems (QMenu *menu) const
Add the actions that are appropriate for a MatrixWorkspace.
MantidTreeWidgetItem * addTreeEntry (const std::pair< std::string, Mantid::API::Workspace_sptr > &item, QTreeWidgetItem *parent=nullptr)
Adds a node for the given named item, including a single child ID item to make each node have a expandable button and allowing plotting to work from non-expanded items.
void addWorkspaceGroupMenuItems (QMenu *menu) const
Add the actions that are appropriate for a WorkspaceGroup.
void createSortMenuActions ()
Create actions for sorting.
void createWorkspaceMenuActions ()
Create the action items associated with the dock.
void excludeItemFromSort (MantidTreeWidgetItem *item)
bool hasUBMatrix (const std::string &wsName)
void hideButtonToolbar ()
bool isTreeUpdating () const
void populateTopLevel (const TopLevelItems &topLevelItems, const QStringList &expanded)
Clears the tree and re-populates it with the given top level items.
void setItemIcon (QTreeWidgetItem *item, const std::string &wsID)
Set tree item's icon based on the ID of the workspace.
void setTreeUpdating (const bool state)
Flips the flag indicating whether a tree update is in progress.
void setupConnections ()
void setupLoadButtonMenu ()
void setupWidgetLayout ()
bool shouldBeSelected (const QString &name) const
Check if a workspace should be selected after dock update.
void updateTree (const TopLevelItems &items) override
Update the workspace tree to match the current state of the ADS.
MantidQt::MantidWidgets::MantidItemSortScheme whichCriteria (SortCriteria criteria)
Private Attributes
QAction * m_ascendingSortAction
QAction * m_byLastModifiedChoice
QAction * m_byNameChoice
QPushButton * m_clearButton
QAction * m_clearUB
QAction * m_colorFill
QAction * m_convertMDHistoToMatrixWorkspace
QAction * m_convertToMatrixWorkspace
QPushButton * m_deleteButton
QAction * m_descendingSortAction
std::string m_filteredText
QPushButton * m_groupButton
QPushButton * m_loadButton
MantidDisplayBase *const m_mantidDisplayModel
QMutex m_mutex
A mutex to lock m_renameMap and m_selectedNames for reading/writing.
QAction * m_plotAdvanced
QAction * m_plotSpec
QAction * m_plotSpecErr
MantidQt::MantidWidgets::WorkspacePresenterVN_sptr m_presenter
QString m_programName
bool m_promptDelete
QHash< QString, QString > m_renameMap
Keep a map of renamed workspaces between updates.
QPushButton * m_saveButton
SaveFileType m_saveFileType
QFileDialog * m_saveFolderDialog
QMenu * m_saveMenu
QStringList m_selectedNames
Temporarily keeps names of selected workspaces during tree update in order to restore selection after update.
QAction * m_showBoxData
QAction * m_showData
QAction * m_showDetectors
QAction * m_showHist
QAction * m_showInst
QAction * m_showListData
QAction * m_showLogs
QAction * m_showMDPlot
QAction * m_showSampleMaterial
QAction * m_showSliceViewer
QAction * m_showSpectrumViewer
QAction * m_showTransposed
QPushButton * m_sortButton
QActionGroup * m_sortChoiceGroup
SortCriteria m_sortCriteria
SortDirection m_sortDirection
QMenu * m_sortMenu
bool m_treeUpdating
QAtomicInt m_updateCount
bool m_viewOnly
QLineEdit * m_workspaceFilter
Additional Inherited Members
Public Types inherited from MantidQt::MantidWidgets::IWorkspaceDockView
enum class SaveFileType { Nexus , ASCII }
enum class SortCriteria { ByName , ByLastModified , ByMemorySize }
enum class SortDirection { Ascending , Descending }
Detailed Description
Author
Lamar Moore
Date
24-08-2016
Version
1.1
Definition at line 60 of file WorkspaceTreeWidget.h.
Constructor & Destructor Documentation
WorkspaceTreeWidget()
MantidQt::MantidWidgets::WorkspaceTreeWidget::WorkspaceTreeWidget (MantidQt::MantidWidgets::MantidDisplayBase * mdb, bool viewOnly = false, QWidget * parent = nullptr)
Definition at line 56 of file WorkspaceTreeWidget.cpp.
References createSortMenuActions(), createWorkspaceMenuActions(), hideButtonToolbar(), m_presenter, m_saveFolderDialog, m_saveMenu, m_tree, m_viewOnly, setupConnections(), setupLoadButtonMenu(), and setupWidgetLayout().
~WorkspaceTreeWidget()
MantidQt::MantidWidgets::WorkspaceTreeWidget::~WorkspaceTreeWidget () default
Member Function Documentation
addClearMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addClearMenuItems (QMenu * menu, const QString & wsName) private
Add menu for clearing workspace items.
Parameters
menu : Parent menu.
wsName : Name of the selected workspace.
Definition at line 986 of file WorkspaceTreeWidget.cpp.
References hasUBMatrix(), and m_clearUB.
Referenced by popupContextMenu().
addMatrixWorkspaceMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addMatrixWorkspaceMenuItems (QMenu * menu, const Mantid::API::MatrixWorkspace_const_sptr & matrixWS) const private
Add the actions that are appropriate for a MatrixWorkspace.
Parameters
menu :: The menu to store the items
matrixWS :: The workspace related to the menu
Definition at line 866 of file WorkspaceTreeWidget.cpp.
References m_colorFill, m_plotAdvanced, m_plotSpec, m_plotSpecErr, m_saveNexus, m_showData, m_showDetectors, m_showHist, m_showInst, m_showLogs, m_showSampleMaterial, m_showSliceViewer, and m_showSpectrumViewer.
Referenced by popupContextMenu().
addMDEventWorkspaceMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addMDEventWorkspaceMenuItems (QMenu * menu, const Mantid::API::IMDEventWorkspace_const_sptr & WS) const private
Add the actions that are appropriate for a MDEventWorkspace.
Parameters
menu :: The menu to store the items
WS :: The workspace related to the menu
Definition at line 916 of file WorkspaceTreeWidget.cpp.
References m_showHist, m_showListData, m_showLogs, and m_showSliceViewer.
Referenced by popupContextMenu().
addMDHistoWorkspaceMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addMDHistoWorkspaceMenuItems (QMenu * menu, const Mantid::API::IMDWorkspace_const_sptr & WS) const private
Definition at line 927 of file WorkspaceTreeWidget.cpp.
References m_convertMDHistoToMatrixWorkspace, m_showHist, m_showListData, m_showLogs, m_showMDPlot, and m_showSliceViewer.
Referenced by popupContextMenu().
addPeaksWorkspaceMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addPeaksWorkspaceMenuItems (QMenu * menu, const Mantid::API::IPeaksWorkspace_const_sptr & WS) const private
Add the actions that are appropriate for a PeaksWorkspace.
Parameters
menu :: The menu to store the items
WS :: The workspace related to the menu
Definition at line 942 of file WorkspaceTreeWidget.cpp.
References m_showData, m_showDetectors, and m_showHist.
Referenced by popupContextMenu().
addSaveMenuOption()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addSaveMenuOption (const QString & algorithmString, QString menuEntryName = "") private
Adds an algorithm to the save menu.
Parameters
algorithmString Algorithm string in format ALGO_NAME.VERSION or ALGO_NAME
menuEntryName Text to be shown in menu
Definition at line 1012 of file WorkspaceTreeWidget.cpp.
References handleShowSaveAlgorithm(), and m_saveMenu.
Referenced by workspaceSelected().
addTableWorkspaceMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addTableWorkspaceMenuItems (QMenu * menu) const private
Add the actions that are appropriate for a MatrixWorkspace.
Parameters
menu :: The menu to store the items
Definition at line 973 of file WorkspaceTreeWidget.cpp.
References m_convertToMatrixWorkspace, m_saveNexus, m_showData, m_showHist, and m_showTransposed.
Referenced by popupContextMenu().
addTreeEntry()
MantidTreeWidgetItem * MantidQt::MantidWidgets::WorkspaceTreeWidget::addTreeEntry (const std::pair< std::string, Mantid::API::Workspace_sptr > & item, QTreeWidgetItem * parent = nullptr) private
Adds a node for the given named item, including a single child ID item to make each node have a expandable button and allowing plotting to work from non-expanded items.
Parameters
item A name/workspace pair to add.
parent If not null then add the new items as a child of the given item
Definition at line 780 of file WorkspaceTreeWidget.cpp.
References m_tree, and setItemIcon().
Referenced by populateChildData(), and populateTopLevel().
addWorkspaceGroupMenuItems()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::addWorkspaceGroupMenuItems (QMenu * menu) const private
Add the actions that are appropriate for a WorkspaceGroup.
Parameters
menu :: The menu to store the items
Definition at line 955 of file WorkspaceTreeWidget.cpp.
References m_colorFill, m_plotAdvanced, m_plotSpec, m_plotSpecErr, and m_saveNexus.
Referenced by popupContextMenu().
askUserYesNo()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::askUserYesNo (const std::string & caption, const std::string & message) const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 224 of file WorkspaceTreeWidget.cpp.
Referenced by clearWorkspacesConfirmation(), and deleteConfirmation().
chooseByLastModified
void MantidQt::MantidWidgets::WorkspaceTreeWidget::chooseByLastModified () slot
Definition at line 324 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ByLastModified, m_presenter, m_sortCriteria, and MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces.
Referenced by createSortMenuActions().
chooseByMemorySize
void MantidQt::MantidWidgets::WorkspaceTreeWidget::chooseByMemorySize () slot
Definition at line 329 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ByMemorySize, m_presenter, m_sortCriteria, and MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces.
Referenced by createSortMenuActions().
chooseByName
void MantidQt::MantidWidgets::WorkspaceTreeWidget::chooseByName () slot
Definition at line 319 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ByName, m_presenter, m_sortCriteria, and MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces.
Referenced by createSortMenuActions().
clearView()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::clearView () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 307 of file WorkspaceTreeWidget.cpp.
References signalClearView().
clearWorkspacesConfirmation()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::clearWorkspacesConfirmation () const override virtual
Gets confirmation from user that they meant to press clear workspaces button.
Returns
True if yes is pressed, false if no is pressed
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1046 of file WorkspaceTreeWidget.cpp.
References askUserYesNo().
clickedWorkspace
void MantidQt::MantidWidgets::WorkspaceTreeWidget::clickedWorkspace (QTreeWidgetItem * item, int) slot
Definition at line 1061 of file WorkspaceTreeWidget.cpp.
Referenced by setupConnections().
convertMDHistoToMatrixWorkspace()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::convertMDHistoToMatrixWorkspace () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1557 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmDialog().
convertToMatrixWorkspace()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::convertToMatrixWorkspace () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1553 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmDialog().
createSortMenuActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::createSortMenuActions () private
Create actions for sorting.
Definition at line 635 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ByName, chooseByLastModified(), chooseByMemorySize(), chooseByName(), m_ascendingSortAction, m_byLastModifiedChoice, m_byNameChoice, m_descendingSortAction, m_sortButton, m_sortChoiceGroup, m_sortCriteria, m_sortMenu, sortAscending(), and sortDescending().
Referenced by WorkspaceTreeWidget().
createWorkspaceMenuActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::createWorkspaceMenuActions () private
Create the action items associated with the dock.
Definition at line 556 of file WorkspaceTreeWidget.cpp.
References MantidQt::API::getQPixmap(), m_clearUB, m_colorFill, m_convertMDHistoToMatrixWorkspace, m_convertToMatrixWorkspace, m_delete, m_plotAdvanced, m_plotSpec, m_plotSpecErr, m_rename, m_saveNexus, m_showBoxData, m_showData, m_showDetectors, m_showHist, m_showInst, m_showListData, m_showLogs, m_showMDPlot, m_showSampleMaterial, m_showSliceViewer, m_showSpectrumViewer, m_showTransposed, onClickClearUB(), onClickConvertMDHistoToMatrixWorkspace(), onClickConvertToMatrixWorkspace(), onClickDeleteWorkspaces(), onClickDrawColorFillPlot(), onClickPlotAdvanced(), onClickPlotSpectra(), onClickPlotSpectraErr(), onClickSaveNexusWorkspace(), onClickShowAlgHistory(), onClickShowBoxData(), onClickShowData(), onClickShowDetectorTable(), onClickShowFileLog(), onClickShowInstrument(), onClickShowListData(), onClickShowMDPlot(), onClickShowSampleMaterial(), onClickShowSliceViewer(), onClickShowSpectrumViewer(), onClickShowTransposed(), and renameWorkspace().
Referenced by WorkspaceTreeWidget().
deleteConfirmation()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::deleteConfirmation () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 295 of file WorkspaceTreeWidget.cpp.
References askUserYesNo().
deleteWorkspaces()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::deleteWorkspaces (const MantidQt::MantidWidgets::StringList & wsNames) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 300 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::deleteWorkspaces(), and m_mantidDisplayModel.
dropEvent()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::dropEvent (QDropEvent * de) override
Accept a drag drop event and process the data appropriately.
Parameters
de :: The drag drop event
Definition at line 101 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidTreeWidget::dropEvent(), and m_tree.
enableClearButton()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::enableClearButton (bool enable) override virtual
Enables and disables the Clear Workspaces Button.
Parameters
enable : true for enable and false for disable
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1054 of file WorkspaceTreeWidget.cpp.
References m_clearButton.
Referenced by handleUpdateTree().
enableDeletePrompt()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::enableDeletePrompt (bool enable) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 291 of file WorkspaceTreeWidget.cpp.
References m_promptDelete.
excludeItemFromSort()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::excludeItemFromSort (MantidTreeWidgetItem * item) private
Definition at line 334 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidTreeWidgetItem::setSortPos().
Referenced by populateChildData().
executeAlgorithmAsync()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait = true) override virtual
Allows asynchronous execution of algorithms.
This method is made available in the view for access by the presenter in order to obviate the dependency on Qt in the Unit tests.
Parameters
alg : algorithm to be executed
wait : determines whether or not a non-gui blocking wait should occur.
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1573 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::executeAlgorithmAsync(), and m_mantidDisplayModel.
Referenced by saveToProgram().
filterWorkspaces()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::filterWorkspaces (const std::string & filterText) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 439 of file WorkspaceTreeWidget.cpp.
References m_tree, n, and workspace.
filterWorkspaceTree
void MantidQt::MantidWidgets::WorkspaceTreeWidget::filterWorkspaceTree (const QString & text) private slot
Filter workspaces based on the string provided.
Parameters
text : the string to filter on.
Definition at line 1032 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::FilterWorkspaces, m_filteredText, and m_presenter.
Referenced by populateTopLevel(), and setupConnections().
getFilterText()
std::string MantidQt::MantidWidgets::WorkspaceTreeWidget::getFilterText () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 437 of file WorkspaceTreeWidget.cpp.
References m_workspaceFilter.
getPresenterWeakPtr()
WorkspacePresenterWN_wptr MantidQt::MantidWidgets::WorkspaceTreeWidget::getPresenterWeakPtr () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 187 of file WorkspaceTreeWidget.cpp.
References m_presenter.
getSaveFileType()
WorkspaceTreeWidget::SaveFileType MantidQt::MantidWidgets::WorkspaceTreeWidget::getSaveFileType () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 388 of file WorkspaceTreeWidget.cpp.
References m_saveFileType.
getSelectedWorkspace()
Mantid::API::Workspace_sptr MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspace () const override virtual
Returns a pointer to the selected workspace (the first if multiple workspaces selected)
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 217 of file WorkspaceTreeWidget.cpp.
References m_tree.
getSelectedWorkspaceNames()
StringList MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNames () const override virtual
Returns the names of the selected workspaces in the dock.
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 194 of file WorkspaceTreeWidget.cpp.
References m_tree.
Referenced by showDetectorsTable(), and workspaceSelected().
getSelectedWorkspaceNamesAsQList()
QStringList MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList () const
Definition at line 204 of file WorkspaceTreeWidget.cpp.
References m_tree.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverPlotMDHistoWorkspaceClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverPlotMDHistoWorkspaceWithErrorsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverplotSpectrumClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverplotSpectrumWithErrorsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotAdvancedClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotBinClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotColorfillClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotContourClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotMDHistoWorkspaceClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotMDHistoWorkspaceWithErrorsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSpectrumClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSpectrumWithErrorsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSurfaceClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotWireframeClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleLogsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleMaterialClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleShapeClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowAlgorithmHistoryClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowDataClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowDetectorsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowInstrumentClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSliceViewerClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotBinsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotBinsWithErrsClicked(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotClicked(), and MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotWithErrsClicked().
getSortCriteria()
WorkspaceTreeWidget::SortCriteria MantidQt::MantidWidgets::WorkspaceTreeWidget::getSortCriteria () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 344 of file WorkspaceTreeWidget.cpp.
References m_sortCriteria.
getSortDirection()
WorkspaceTreeWidget::SortDirection MantidQt::MantidWidgets::WorkspaceTreeWidget::getSortDirection () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 342 of file WorkspaceTreeWidget.cpp.
References m_sortDirection.
handleClearView
void MantidQt::MantidWidgets::WorkspaceTreeWidget::handleClearView () private slot
Definition at line 1144 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, m_tree, and MantidQt::MantidWidgets::MantidDisplayBase::updateProject().
Referenced by setupConnections().
handleShowSaveAlgorithm
void MantidQt::MantidWidgets::WorkspaceTreeWidget::handleShowSaveAlgorithm () private slot
Definition at line 373 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ASCII, m_presenter, m_saveFileType, MantidQt::MantidWidgets::IWorkspaceDockView::Nexus, and MantidQt::MantidWidgets::ViewNotifiable::SaveSingleWorkspace.
Referenced by addSaveMenuOption().
handleUpdateTree
void MantidQt::MantidWidgets::WorkspaceTreeWidget::handleUpdateTree (const TopLevelItems & items) private slot
Handle asynchronous tree update.
Definition at line 1116 of file WorkspaceTreeWidget.cpp.
References enableClearButton(), m_mantidDisplayModel, m_tree, m_updateCount, n, populateTopLevel(), setTreeUpdating(), MantidQt::MantidWidgets::MantidTreeWidget::sort(), and MantidQt::MantidWidgets::MantidDisplayBase::updateProject().
Referenced by setupConnections().
hasUBMatrix()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::hasUBMatrix (const std::string & wsName) private
Definition at line 995 of file WorkspaceTreeWidget.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by addClearMenuItems().
hideButtonToolbar()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::hideButtonToolbar () private
Definition at line 1577 of file WorkspaceTreeWidget.cpp.
References m_clearButton, m_deleteButton, m_groupButton, m_loadButton, m_saveButton, and m_sortButton.
Referenced by WorkspaceTreeWidget().
incrementUpdateCount
void MantidQt::MantidWidgets::WorkspaceTreeWidget::incrementUpdateCount () private slot
Definition at line 185 of file WorkspaceTreeWidget.cpp.
References m_updateCount.
Referenced by updateTree().
isPromptDelete()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::isPromptDelete () const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 293 of file WorkspaceTreeWidget.cpp.
References m_promptDelete.
isTreeUpdating()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::isTreeUpdating () const inline private
Definition at line 126 of file WorkspaceTreeWidget.h.
Referenced by sortWorkspaces().
keyPressEvent
void MantidQt::MantidWidgets::WorkspaceTreeWidget::keyPressEvent (QKeyEvent * e) override slot
Definition at line 1469 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::DeleteWorkspaces, and m_presenter.
onClickClearUB
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickClearUB () private slot
Handler for the clear the UB matrix event.
Definition at line 1564 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::ClearUBMatrix, and m_presenter.
Referenced by createWorkspaceMenuActions().
onClickClearWorkspaces
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickClearWorkspaces () slot
Handles clear button trigger.
Definition at line 1057 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::ClearWorkspaces, and m_presenter.
Referenced by setupConnections().
onClickConvertMDHistoToMatrixWorkspace
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickConvertMDHistoToMatrixWorkspace () private slot
Convert selected MDHistoWorkspace to a MatrixWorkspace.
Definition at line 1549 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::ConvertMDHistoToMatrixWorkspace, and m_presenter.
Referenced by createWorkspaceMenuActions().
onClickConvertToMatrixWorkspace
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickConvertToMatrixWorkspace () private slot
Convert selected TableWorkspace to a MatrixWorkspace.
Definition at line 1542 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::ConvertToMatrixWorkspace, and m_presenter.
Referenced by createWorkspaceMenuActions().
onClickDeleteWorkspaces
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickDeleteWorkspaces () slot
Handles delete button/menu item triggers.
Definition at line 1038 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::DeleteWorkspaces, and m_presenter.
Referenced by createWorkspaceMenuActions(), and setupConnections().
onClickDrawColorFillPlot
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickDrawColorFillPlot () private slot
Definition at line 1434 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowColourFillPlot.
Referenced by createWorkspaceMenuActions().
onClickGroupButton
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickGroupButton () private slot
Handles group button clicks.
Definition at line 1095 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::GroupWorkspaces, m_groupButton, m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::UngroupWorkspaces.
Referenced by setupConnections().
onClickLiveData
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickLiveData () private slot
handles Live Data menu trigger
Definition at line 1110 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::LoadLiveDataWorkspace, and m_presenter.
Referenced by setupLoadButtonMenu().
onClickLoad
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickLoad () private slot
Handles Load File menu trigger.
Definition at line 1107 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ViewNotifiable::LoadWorkspace, and m_presenter.
Referenced by setupLoadButtonMenu().
onClickPlotAdvanced
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickPlotAdvanced () private slot
Definition at line 1394 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrumAdvanced.
Referenced by createWorkspaceMenuActions().
onClickPlotSpectra
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickPlotSpectra () private slot
Definition at line 1388 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrum.
Referenced by createWorkspaceMenuActions().
onClickPlotSpectraErr
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickPlotSpectraErr () private slot
Definition at line 1390 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::PlotSpectrumWithErrors.
Referenced by createWorkspaceMenuActions().
onClickSaveNexusWorkspace
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickSaveNexusWorkspace () private slot
Definition at line 1535 of file WorkspaceTreeWidget.cpp.
References m_presenter, m_saveFileType, MantidQt::MantidWidgets::IWorkspaceDockView::Nexus, and MantidQt::MantidWidgets::ViewNotifiable::SaveSingleWorkspace.
Referenced by createWorkspaceMenuActions().
onClickSaveToProgram
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickSaveToProgram (const QString & name) slot
Definition at line 1267 of file WorkspaceTreeWidget.cpp.
References m_presenter, m_programName, and MantidQt::MantidWidgets::ViewNotifiable::SaveToProgram.
Referenced by popupContextMenu().
onClickShowAlgHistory
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowAlgHistory () private slot
Definition at line 1525 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowAlgorithmHistory.
Referenced by createWorkspaceMenuActions().
onClickShowBoxData
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowBoxData () private slot
Definition at line 1491 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowBoxDataTable.
Referenced by createWorkspaceMenuActions().
onClickShowData
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowData () private slot
Definition at line 1257 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowWorkspaceData.
Referenced by createWorkspaceMenuActions().
onClickShowDetectorTable
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowDetectorTable () private slot
Definition at line 1478 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowDetectorsTable.
Referenced by createWorkspaceMenuActions().
onClickShowFileLog
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowFileLog () private slot
Definition at line 1515 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowLogs.
Referenced by createWorkspaceMenuActions().
onClickShowInstrument
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowInstrument () private slot
Definition at line 1261 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowInstrumentView.
Referenced by createWorkspaceMenuActions().
onClickShowListData
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowListData () private slot
Definition at line 1499 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowListData.
Referenced by createWorkspaceMenuActions().
onClickShowMDPlot
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowMDPlot () private slot
Definition at line 1495 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowMDPlot.
Referenced by createWorkspaceMenuActions().
onClickShowSampleMaterial
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowSampleMaterial () private slot
Definition at line 1519 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowSampleMaterialWindow.
Referenced by createWorkspaceMenuActions().
onClickShowSliceViewer
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowSliceViewer () private slot
Definition at line 1509 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowSliceViewer.
Referenced by createWorkspaceMenuActions().
onClickShowSpectrumViewer
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowSpectrumViewer () private slot
Definition at line 1503 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowSpectrumViewer.
Referenced by createWorkspaceMenuActions().
onClickShowTransposed
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onClickShowTransposed () private slot
Definition at line 1531 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::ShowTransposed.
Referenced by createWorkspaceMenuActions().
onLoadAccept
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onLoadAccept () private slot
Definition at line 233 of file WorkspaceTreeWidget.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::updateRecentFilesList().
onTreeSelectionChanged
void MantidQt::MantidWidgets::WorkspaceTreeWidget::onTreeSelectionChanged () private slot
Definition at line 820 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::disableSaveNexus(), MantidQt::MantidWidgets::MantidDisplayBase::enableSaveNexus(), m_deleteButton, m_groupButton, m_mantidDisplayModel, m_saveButton, and m_tree.
Referenced by setupConnections().
plotSpectrum()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::plotSpectrum (const std::string & type) override virtual
Plots one or more spectra from each selected workspace.
Parameters
type "Simple", "Errors" show error bars, "Advanced" advanced plotting.
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1401 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidTreeWidget::chooseSpectrumFromSelected(), MantidQt::DistributionDefault, m_mantidDisplayModel, m_tree, MantidQt::MantidWidgets::MantidDisplayBase::plot1D(), MantidQt::MantidWidgets::MantidDisplayBase::plotContour(), MantidQt::MantidWidgets::MantidDisplayBase::plotSubplots(), and MantidQt::MantidWidgets::MantidDisplayBase::plotSurface().
populateChildData
void MantidQt::MantidWidgets::WorkspaceTreeWidget::populateChildData (QTreeWidgetItem * item) slot
When an item is expanded, populate the child data for this item.
Parameters
item :: The tree item being expanded
Definition at line 689 of file WorkspaceTreeWidget.cpp.
References addTreeEntry(), excludeItemFromSort(), m_tree, shouldBeSelected(), and workspace.
Referenced by setupConnections().
populateTopLevel()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::populateTopLevel (const TopLevelItems & topLevelItems, const QStringList & expanded) private
Clears the tree and re-populates it with the given top level items.
Parameters
topLevelItems The map of names to workspaces
expanded Names of items who should expanded after being populated
Definition at line 745 of file WorkspaceTreeWidget.cpp.
References addTreeEntry(), filterWorkspaceTree(), m_mutex, m_renameMap, m_selectedNames, m_tree, m_workspaceFilter, and shouldBeSelected().
Referenced by handleUpdateTree().
popupContextMenu()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::popupContextMenu () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Reimplemented in MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple.
Definition at line 1159 of file WorkspaceTreeWidget.cpp.
References addClearMenuItems(), addMatrixWorkspaceMenuItems(), addMDEventWorkspaceMenuItems(), addMDHistoWorkspaceMenuItems(), addPeaksWorkspaceMenuItems(), addTableWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_delete, m_loadMenu, m_menuPosition, m_program, m_programMapper, m_rename, m_saveToProgram, m_tree, onClickSaveToProgram(), and selectedWsName.
popupMenu
void MantidQt::MantidWidgets::WorkspaceTreeWidget::popupMenu (const QPoint & pos) protected slot
Handles display of the workspace context menu.
Definition at line 1152 of file WorkspaceTreeWidget.cpp.
References m_menuPosition, m_presenter, m_viewOnly, and MantidQt::MantidWidgets::ViewNotifiable::PopulateAndShowWorkspaceContextMenu.
Referenced by setupConnections().
recordWorkspaceRename()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::recordWorkspaceRename (const std::string & oldName, const std::string & newName) override virtual
Save the old and the new name in m_renameMap.
This is needed to restore selection of the renamed workspace (if it was selected before renaming).
Parameters
oldName :: Old name of a renamed workspace.
newName :: New name of a renamed workspace.
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 272 of file WorkspaceTreeWidget.cpp.
References m_mutex, and m_renameMap.
refreshWorkspaces()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::refreshWorkspaces () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 289 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::RefreshWorkspaces.
renameWorkspace
void MantidQt::MantidWidgets::WorkspaceTreeWidget::renameWorkspace () slot
Definition at line 254 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::RenameWorkspace.
Referenced by createWorkspaceMenuActions().
saveToProgram()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::saveToProgram () override virtual
Saves a workspace based on the program the user chooses to save to.
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1275 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::createAlgorithm(), executeAlgorithmAsync(), Mantid::API::FileProperty::getDefaultExt(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_mantidDisplayModel, m_programName, and selectedWsName.
saveWorkspace()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::saveWorkspace (const std::string & wsName, SaveFileType type) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 390 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::ASCII, m_mantidDisplayModel, MantidQt::MantidWidgets::IWorkspaceDockView::Nexus, and MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmDialog().
saveWorkspaceCollection
void MantidQt::MantidWidgets::WorkspaceTreeWidget::saveWorkspaceCollection () slot
Definition at line 369 of file WorkspaceTreeWidget.cpp.
References m_presenter, and MantidQt::MantidWidgets::ViewNotifiable::SaveWorkspaceCollection.
Referenced by workspaceSelected().
saveWorkspaces()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::saveWorkspaces (const MantidQt::MantidWidgets::StringList & wsNames) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 410 of file WorkspaceTreeWidget.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_saveFolderDialog, and m_tree.
setItemIcon()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::setItemIcon (QTreeWidgetItem * item, const std::string & wsID) private
Set tree item's icon based on the ID of the workspace.
Parameters
item :: A workspace tree item.
wsID :: An icon type code.
Definition at line 545 of file WorkspaceTreeWidget.cpp.
Referenced by addTreeEntry().
setTreeUpdating()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::setTreeUpdating (const bool state) private
Flips the flag indicating whether a tree update is in progress.
Actions such as sorting are disabled while an update is in progress.
Parameters
state The required state for the flag
Definition at line 183 of file WorkspaceTreeWidget.cpp.
References m_treeUpdating.
Referenced by handleUpdateTree().
setupConnections()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::setupConnections () private
Definition at line 159 of file WorkspaceTreeWidget.cpp.
References clickedWorkspace(), filterWorkspaceTree(), handleClearView(), handleUpdateTree(), m_clearButton, m_deleteButton, m_groupButton, m_tree, m_workspaceFilter, onClickClearWorkspaces(), onClickDeleteWorkspaces(), onClickGroupButton(), onTreeSelectionChanged(), populateChildData(), popupMenu(), signalClearView(), signalUpdateTree(), and workspaceSelected().
Referenced by WorkspaceTreeWidget().
setupLoadButtonMenu()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::setupLoadButtonMenu () private
Definition at line 146 of file WorkspaceTreeWidget.cpp.
References m_loadButton, m_loadMenu, onClickLiveData(), and onClickLoad().
Referenced by WorkspaceTreeWidget().
setupWidgetLayout()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::setupWidgetLayout () private
Definition at line 103 of file WorkspaceTreeWidget.cpp.
References m_clearButton, m_deleteButton, m_groupButton, m_loadButton, m_mantidDisplayModel, m_saveButton, m_sortButton, m_tree, and m_workspaceFilter.
Referenced by WorkspaceTreeWidget().
shouldBeSelected()
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::shouldBeSelected (const QString & name) const private
Check if a workspace should be selected after dock update.
Parameters
name :: Name of a workspace to check.
Definition at line 805 of file WorkspaceTreeWidget.cpp.
References m_mutex, m_renameMap, and m_selectedNames.
Referenced by populateChildData(), and populateTopLevel().
showAlgorithmHistory()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showAlgorithmHistory () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1529 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmHistory().
showBoxDataTable()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showBoxDataTable () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1493 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::importBoxDataTable(), and m_mantidDisplayModel.
showColourFillPlot()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showColourFillPlot () override virtual
Draw a color fill plot of the workspaces that are currently selected.
NOTE: The drawing of 2D plots is currently intimately linked with MantidMatrix meaning that one of these must be generated first!
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1443 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::drawColorFillPlots(), m_mantidDisplayModel, and m_tree.
showCriticalUserMessage()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showCriticalUserMessage (const std::string & caption, const std::string & message) const override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 229 of file WorkspaceTreeWidget.cpp.
showDetectorsTable()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showDetectorsTable () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1482 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::createDetectorTable(), getSelectedWorkspaceNames(), and m_mantidDisplayModel.
showInstrumentView()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showInstrumentView () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1265 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showMantidInstrumentSelected().
showListData()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showListData () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1501 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showListData().
showLiveDataDialog()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showLiveDataDialog () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 249 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel.
showLoadDialog()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showLoadDialog () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 244 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel.
showLogs()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showLogs () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1517 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showLogFileWindow().
showMDPlot()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showMDPlot () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1497 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showMDPlot().
showRenameDialog()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showRenameDialog (const MantidQt::MantidWidgets::StringList & wsNames) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 256 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::renameWorkspace().
showSampleMaterialWindow()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showSampleMaterialWindow () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1523 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showSampleMaterialWindow().
showSliceViewer()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showSliceViewer () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1513 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showSliceViewer().
showSpectrumViewer()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showSpectrumViewer () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1507 of file WorkspaceTreeWidget.cpp.
References m_mantidDisplayModel, and MantidQt::MantidWidgets::MantidDisplayBase::showSpectrumViewer().
showTransposed()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showTransposed () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1533 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::importTransposed(), and m_mantidDisplayModel.
showWorkspaceData()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::showWorkspaceData () override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 1259 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::MantidDisplayBase::importWorkspace(), and m_mantidDisplayModel.
signalClearView
void MantidQt::MantidWidgets::WorkspaceTreeWidget::signalClearView () signal
Referenced by clearView(), and setupConnections().
signalUpdateTree
void MantidQt::MantidWidgets::WorkspaceTreeWidget::signalUpdateTree (const TopLevelItems &) signal
Referenced by setupConnections(), and updateTree().
sortAscending
void MantidQt::MantidWidgets::WorkspaceTreeWidget::sortAscending () slot
Definition at line 309 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::Ascending, m_presenter, m_sortDirection, and MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces.
Referenced by createSortMenuActions().
sortDescending
void MantidQt::MantidWidgets::WorkspaceTreeWidget::sortDescending () slot
Definition at line 314 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::Descending, m_presenter, m_sortDirection, and MantidQt::MantidWidgets::ViewNotifiable::SortWorkspaces.
Referenced by createSortMenuActions().
sortWorkspaces()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::sortWorkspaces (SortCriteria criteria, SortDirection direction) override virtual
Implements MantidQt::MantidWidgets::IWorkspaceDockView.
Definition at line 346 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::IWorkspaceDockView::Ascending, isTreeUpdating(), m_tree, MantidQt::MantidWidgets::MantidTreeWidget::setSortOrder(), MantidQt::MantidWidgets::MantidTreeWidget::setSortScheme(), MantidQt::MantidWidgets::MantidTreeWidget::sort(), and whichCriteria().
updateTree()
void MantidQt::MantidWidgets::WorkspaceTreeWidget::updateTree (const TopLevelItems & items) override private
Update the workspace tree to match the current state of the ADS.
It is important that the workspace tree is modified only by this method.
Parameters
items Items which are currently in the ADS.
Definition at line 735 of file WorkspaceTreeWidget.cpp.
References incrementUpdateCount(), and signalUpdateTree().
whichCriteria()
MantidQt::MantidWidgets::MantidItemSortScheme MantidQt::MantidWidgets::WorkspaceTreeWidget::whichCriteria (SortCriteria criteria) private
Definition at line 354 of file WorkspaceTreeWidget.cpp.
References MantidQt::MantidWidgets::ByLastModified, MantidQt::MantidWidgets::IWorkspaceDockView::ByLastModified, MantidQt::MantidWidgets::ByMemorySize, MantidQt::MantidWidgets::IWorkspaceDockView::ByMemorySize, MantidQt::MantidWidgets::ByName, and MantidQt::MantidWidgets::IWorkspaceDockView::ByName.
Referenced by sortWorkspaces().
workspaceSelected
void MantidQt::MantidWidgets::WorkspaceTreeWidget::workspaceSelected () protected slot
Definition at line 1063 of file WorkspaceTreeWidget.cpp.
References addSaveMenuOption(), MantidQt::MantidWidgets::MantidDisplayBase::enableSaveNexus(), getSelectedWorkspaceNames(), m_mantidDisplayModel, m_saveButton, m_saveMenu, and saveWorkspaceCollection().
Referenced by setupConnections().
Member Data Documentation
m_ascendingSortAction
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_ascendingSortAction private
Definition at line 233 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_byLastModifiedChoice
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_byLastModifiedChoice private
Definition at line 234 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_byNameChoice
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_byNameChoice private
Definition at line 233 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_clearButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_clearButton private
Definition at line 221 of file WorkspaceTreeWidget.h.
Referenced by enableClearButton(), hideButtonToolbar(), setupConnections(), and setupWidgetLayout().
m_clearUB
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_clearUB private
Definition at line 235 of file WorkspaceTreeWidget.h.
Referenced by addClearMenuItems(), and createWorkspaceMenuActions().
m_colorFill
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_colorFill private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), and createWorkspaceMenuActions().
m_convertMDHistoToMatrixWorkspace
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_convertMDHistoToMatrixWorkspace private
Definition at line 234 of file WorkspaceTreeWidget.h.
Referenced by addMDHistoWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_convertToMatrixWorkspace
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_convertToMatrixWorkspace private
Definition at line 234 of file WorkspaceTreeWidget.h.
Referenced by addTableWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_delete
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_delete protected
Definition at line 211 of file WorkspaceTreeWidget.h.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addGeneralWorkspaceActions(), createWorkspaceMenuActions(), and popupContextMenu().
m_deleteButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_deleteButton private
Definition at line 220 of file WorkspaceTreeWidget.h.
Referenced by hideButtonToolbar(), onTreeSelectionChanged(), setupConnections(), and setupWidgetLayout().
m_descendingSortAction
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_descendingSortAction private
Definition at line 233 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_filteredText
std::string MantidQt::MantidWidgets::WorkspaceTreeWidget::m_filteredText private
Definition at line 217 of file WorkspaceTreeWidget.h.
Referenced by filterWorkspaceTree().
m_groupButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_groupButton private
Definition at line 222 of file WorkspaceTreeWidget.h.
Referenced by hideButtonToolbar(), onClickGroupButton(), onTreeSelectionChanged(), setupConnections(), and setupWidgetLayout().
m_loadButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_loadButton private
Definition at line 218 of file WorkspaceTreeWidget.h.
Referenced by hideButtonToolbar(), setupLoadButtonMenu(), and setupWidgetLayout().
m_loadMenu
QMenu* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_loadMenu protected
Definition at line 209 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::popupContextMenu(), and setupLoadButtonMenu().
m_mantidDisplayModel
MantidDisplayBase* const MantidQt::MantidWidgets::WorkspaceTreeWidget::m_mantidDisplayModel private
Definition at line 215 of file WorkspaceTreeWidget.h.
Referenced by convertMDHistoToMatrixWorkspace(), convertToMatrixWorkspace(), deleteWorkspaces(), executeAlgorithmAsync(), handleClearView(), handleUpdateTree(), onLoadAccept(), onTreeSelectionChanged(), plotSpectrum(), saveToProgram(), saveWorkspace(), setupWidgetLayout(), showAlgorithmHistory(), showBoxDataTable(), showColourFillPlot(), showDetectorsTable(), showInstrumentView(), showListData(), showLiveDataDialog(), showLoadDialog(), showLogs(), showMDPlot(), showRenameDialog(), showSampleMaterialWindow(), showSliceViewer(), showSpectrumViewer(), showTransposed(), showWorkspaceData(), and workspaceSelected().
m_menuPosition
QPoint MantidQt::MantidWidgets::WorkspaceTreeWidget::m_menuPosition protected
Definition at line 207 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::popupContextMenu(), and popupMenu().
m_mutex
QMutex MantidQt::MantidWidgets::WorkspaceTreeWidget::m_mutex mutable private
A mutex to lock m_renameMap and m_selectedNames for reading/writing.
Definition at line 249 of file WorkspaceTreeWidget.h.
Referenced by populateTopLevel(), recordWorkspaceRename(), and shouldBeSelected().
m_plotAdvanced
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_plotAdvanced private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), and createWorkspaceMenuActions().
m_plotSpec
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_plotSpec private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), and createWorkspaceMenuActions().
m_plotSpecErr
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_plotSpecErr private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), and createWorkspaceMenuActions().
m_presenter
MantidQt::MantidWidgets::WorkspacePresenterVN_sptr MantidQt::MantidWidgets::WorkspaceTreeWidget::m_presenter private
Definition at line 203 of file WorkspaceTreeWidget.h.
Referenced by chooseByLastModified(), chooseByMemorySize(), chooseByName(), filterWorkspaceTree(), getPresenterWeakPtr(), handleShowSaveAlgorithm(), keyPressEvent(), onClickClearUB(), onClickClearWorkspaces(), onClickConvertMDHistoToMatrixWorkspace(), onClickConvertToMatrixWorkspace(), onClickDeleteWorkspaces(), onClickDrawColorFillPlot(), onClickGroupButton(), onClickLiveData(), onClickLoad(), onClickPlotAdvanced(), onClickPlotSpectra(), onClickPlotSpectraErr(), onClickSaveNexusWorkspace(), onClickSaveToProgram(), onClickShowAlgHistory(), onClickShowBoxData(), onClickShowData(), onClickShowDetectorTable(), onClickShowFileLog(), onClickShowInstrument(), onClickShowListData(), onClickShowMDPlot(), onClickShowSampleMaterial(), onClickShowSliceViewer(), onClickShowSpectrumViewer(), onClickShowTransposed(), popupMenu(), refreshWorkspaces(), renameWorkspace(), saveWorkspaceCollection(), sortAscending(), sortDescending(), and WorkspaceTreeWidget().
m_program
QAction* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_program protected
Definition at line 211 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu().
m_programMapper
QSignalMapper* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_programMapper protected
Definition at line 210 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu().
m_programName
QString MantidQt::MantidWidgets::WorkspaceTreeWidget::m_programName private
Definition at line 214 of file WorkspaceTreeWidget.h.
Referenced by onClickSaveToProgram(), and saveToProgram().
m_promptDelete
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::m_promptDelete private
Definition at line 239 of file WorkspaceTreeWidget.h.
Referenced by enableDeletePrompt(), and isPromptDelete().
m_rename
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_rename protected
Definition at line 211 of file WorkspaceTreeWidget.h.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addGeneralWorkspaceActions(), createWorkspaceMenuActions(), and popupContextMenu().
m_renameMap
QHash<QString, QString> MantidQt::MantidWidgets::WorkspaceTreeWidget::m_renameMap private
Keep a map of renamed workspaces between updates.
Definition at line 247 of file WorkspaceTreeWidget.h.
Referenced by populateTopLevel(), recordWorkspaceRename(), and shouldBeSelected().
m_saveButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveButton private
Definition at line 219 of file WorkspaceTreeWidget.h.
Referenced by hideButtonToolbar(), onTreeSelectionChanged(), setupWidgetLayout(), and workspaceSelected().
m_saveFileType
SaveFileType MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveFileType private
Definition at line 240 of file WorkspaceTreeWidget.h.
Referenced by getSaveFileType(), handleShowSaveAlgorithm(), and onClickSaveNexusWorkspace().
m_saveFolderDialog
QFileDialog* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveFolderDialog private
Definition at line 226 of file WorkspaceTreeWidget.h.
Referenced by saveWorkspaces(), and WorkspaceTreeWidget().
m_saveMenu
QMenu * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveMenu private
Definition at line 229 of file WorkspaceTreeWidget.h.
Referenced by addSaveMenuOption(), workspaceSelected(), and WorkspaceTreeWidget().
m_saveNexus
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveNexus protected
Definition at line 211 of file WorkspaceTreeWidget.h.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addGeneralWorkspaceActions(), addMatrixWorkspaceMenuItems(), addTableWorkspaceMenuItems(), addWorkspaceGroupMenuItems(), and createWorkspaceMenuActions().
m_saveToProgram
QMenu * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveToProgram protected
Definition at line 209 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu().
m_selectedNames
QStringList MantidQt::MantidWidgets::WorkspaceTreeWidget::m_selectedNames private
Temporarily keeps names of selected workspaces during tree update in order to restore selection after update.
Definition at line 245 of file WorkspaceTreeWidget.h.
Referenced by populateTopLevel(), and shouldBeSelected().
m_showBoxData
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showBoxData private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by createWorkspaceMenuActions().
m_showData
QAction* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showData private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addPeaksWorkspaceMenuItems(), addTableWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showDetectors
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showDetectors private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addPeaksWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showHist
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showHist private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addMDEventWorkspaceMenuItems(), addMDHistoWorkspaceMenuItems(), addPeaksWorkspaceMenuItems(), addTableWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showInst
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showInst private
Definition at line 231 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showListData
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showListData private
Definition at line 233 of file WorkspaceTreeWidget.h.
Referenced by addMDEventWorkspaceMenuItems(), addMDHistoWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showLogs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showLogs private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addMDEventWorkspaceMenuItems(), addMDHistoWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showMDPlot
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showMDPlot private
Definition at line 233 of file WorkspaceTreeWidget.h.
Referenced by addMDHistoWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showSampleMaterial
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showSampleMaterial private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showSliceViewer
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showSliceViewer private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), addMDEventWorkspaceMenuItems(), addMDHistoWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showSpectrumViewer
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showSpectrumViewer private
Definition at line 232 of file WorkspaceTreeWidget.h.
Referenced by addMatrixWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_showTransposed
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidget::m_showTransposed private
Definition at line 234 of file WorkspaceTreeWidget.h.
Referenced by addTableWorkspaceMenuItems(), and createWorkspaceMenuActions().
m_sortButton
QPushButton* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_sortButton private
Definition at line 223 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions(), hideButtonToolbar(), and setupWidgetLayout().
m_sortChoiceGroup
QActionGroup* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_sortChoiceGroup private
Definition at line 225 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_sortCriteria
SortCriteria MantidQt::MantidWidgets::WorkspaceTreeWidget::m_sortCriteria private
Definition at line 241 of file WorkspaceTreeWidget.h.
Referenced by chooseByLastModified(), chooseByMemorySize(), chooseByName(), createSortMenuActions(), and getSortCriteria().
m_sortDirection
SortDirection MantidQt::MantidWidgets::WorkspaceTreeWidget::m_sortDirection private
Definition at line 242 of file WorkspaceTreeWidget.h.
Referenced by getSortDirection(), sortAscending(), and sortDescending().
m_sortMenu
QMenu* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_sortMenu private
Definition at line 229 of file WorkspaceTreeWidget.h.
Referenced by createSortMenuActions().
m_tree
MantidTreeWidget* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_tree protected
Definition at line 206 of file WorkspaceTreeWidget.h.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addMatrixWorkspaceActions(), addTreeEntry(), dropEvent(), filterWorkspaces(), getSelectedWorkspace(), getSelectedWorkspaceNames(), getSelectedWorkspaceNamesAsQList(), handleClearView(), handleUpdateTree(), onTreeSelectionChanged(), plotSpectrum(), populateChildData(), populateTopLevel(), popupContextMenu(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::popupContextMenu(), saveWorkspaces(), setupConnections(), setupWidgetLayout(), showColourFillPlot(), sortWorkspaces(), WorkspaceTreeWidget(), and MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::WorkspaceTreeWidgetSimple().
m_treeUpdating
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::m_treeUpdating private
Definition at line 238 of file WorkspaceTreeWidget.h.
Referenced by setTreeUpdating().
m_updateCount
QAtomicInt MantidQt::MantidWidgets::WorkspaceTreeWidget::m_updateCount private
Definition at line 237 of file WorkspaceTreeWidget.h.
Referenced by handleUpdateTree(), and incrementUpdateCount().
m_viewOnly
bool MantidQt::MantidWidgets::WorkspaceTreeWidget::m_viewOnly private
Definition at line 227 of file WorkspaceTreeWidget.h.
Referenced by popupMenu(), and WorkspaceTreeWidget().
m_workspaceFilter
QLineEdit* MantidQt::MantidWidgets::WorkspaceTreeWidget::m_workspaceFilter private
Definition at line 224 of file WorkspaceTreeWidget.h.
Referenced by getFilterText(), populateTopLevel(), setupConnections(), and setupWidgetLayout().
selectedWsName
QString MantidQt::MantidWidgets::WorkspaceTreeWidget::selectedWsName protected
Definition at line 208 of file WorkspaceTreeWidget.h.
Referenced by popupContextMenu(), MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::popupContextMenu(), and saveToProgram().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidget.h
qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp