Mantid: Mantid::Crystal::PredictPeaks Class Reference
Mantid::Crystal::PredictPeaks Class Reference final
Using a known crystal lattice and UB matrix, predict where single crystal peaks should be found in detector/TOF space.
#include <PredictPeaks.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name for identification.
PredictPeaks ()
Constructor.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void calculateQAndAddToOutput (const Kernel::V3D &hkl, const Kernel::DblMatrix &orientedUB, const Kernel::DblMatrix &goniometerMatrix)
Calculates Q from HKL and adds a peak to the output workspace.
void calculateQAndAddToOutputLeanElastic (const Kernel::V3D &hkl, const Kernel::DblMatrix &UB)
Calculates Q from HKL and adds a peak to the output workspace.
void checkBeamDirection () const
Checks that the beam direction is +Z, throws exception otherwise.
void exec () override
Run the algorithm.
void fillPossibleHKLsUsingGenerator (const Geometry::OrientedLattice &orientedLattice, std::vector< Kernel::V3D > &possibleHKLs) const
Fills possibleHKLs with all HKLs that are allowed within d- and lambda-limits.
void fillPossibleHKLsUsingPeaksWorkspace (const API::IPeaksWorkspace_sptr &peaksWorkspace, std::vector< Kernel::V3D > &possibleHKLs) const
Fills possibleHKLs with all HKLs from the supplied PeaksWorkspace.
std::tuple< Kernel::V3D, double > getPeakParametersFromQ (const Kernel::V3D &q) const
Get the predicted detector direction from Q.
void init () override
Initialise the properties.
void logNumberOfPeaksFound (size_t allowedPeakCount) const
Log the number of peaks found to fall on and off detectors.
void setInstrumentFromInputWorkspace (const API::ExperimentInfo_sptr &inWS)
Tries to set the internally stored instrument from an ExperimentInfo-object.
void setReferenceFrameAndBeamDirection ()
Cache the reference frame and beam direction from the instrument.
void setRunNumberFromInputWorkspace (const API::ExperimentInfo_sptr &inWS)
Sets the run number from the supplied ExperimentInfo or throws an exception.
void setStructureFactorCalculatorFromSample (const API::Sample &sample)
Assigns a StructureFactorCalculator if available in sample.
Private Attributes
std::unique_ptr< API::DetectorSearcher > m_detectorCacheSearch
Detector search cache for fast look-up of detectors.
int m_edge
Number of edge pixels with no peaks.
Geometry::Instrument_const_sptr m_inst
Instrument reference.
bool m_leanElasticPeak = false
Mantid::API::IPeaksWorkspace_sptr m_pw
Output peaks workspace.
double m_qConventionFactor
Kernel::V3D m_refBeamDir
Direction of the beam for this instrument.
std::vector< Mantid::Geometry::ReflectionCondition_sptr > m_refConds
Reflection conditions possible.
std::shared_ptr< const Geometry::ReferenceFrame > m_refFrame
Reference frame for the instrument.
int m_runNumber
Run number of input workspace.
Geometry::StructureFactorCalculator_sptr m_sfCalculator
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Using a known crystal lattice and UB matrix, predict where single crystal peaks should be found in detector/TOF space.
Creates a PeaksWorkspace containing the peaks at the expected positions.
Author
Janik Zikovsky
Date
2011-04-29 16:30:52.986094
Definition at line 32 of file PredictPeaks.h.
Constructor & Destructor Documentation
PredictPeaks()
Mantid::Crystal::PredictPeaks::PredictPeaks ()
Constructor.
Definition at line 46 of file PredictPeaks.cpp.
Member Function Documentation
calculateQAndAddToOutput()
void Mantid::Crystal::PredictPeaks::calculateQAndAddToOutput (const Kernel::V3D & hkl, const Kernel::DblMatrix & orientedUB, const Kernel::DblMatrix & goniometerMatrix) private
Calculates Q from HKL and adds a peak to the output workspace.
This method takes HKL and uses the oriented UB matrix (UB multiplied by the goniometer matrix) to calculate Q. It then creates a Peak-object using that Q-vector and the internally stored instrument. If the corresponding diffracted beam intersects with a detector, the peak is added to the output- workspace.
Parameters
hkl
orientedUB
goniometerMatrix
Definition at line 566 of file PredictPeaks.cpp.
References Mantid::Geometry::Track::back(), Mantid::Geometry::edgePixel(), getPeakParametersFromQ(), Mantid::API::Algorithm::getProperty(), m_detectorCacheSearch, m_edge, m_inst, m_pw, m_qConventionFactor, m_runNumber, and m_sfCalculator.
Referenced by exec().
calculateQAndAddToOutputLeanElastic()
void Mantid::Crystal::PredictPeaks::calculateQAndAddToOutputLeanElastic (const Kernel::V3D & hkl, const Kernel::DblMatrix & UB) private
Calculates Q from HKL and adds a peak to the output workspace.
This method takes HKL and uses the UB multiplied to calculate Q sample. It then creates a LeanElasticPeak-object using that Q-vector.
Parameters
hkl
UB
Definition at line 643 of file PredictPeaks.cpp.
References m_pw, m_qConventionFactor, m_runNumber, and m_sfCalculator.
Referenced by exec().
category()
const std::string Mantid::Crystal::PredictPeaks::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 49 of file PredictPeaks.h.
checkBeamDirection()
void Mantid::Crystal::PredictPeaks::checkBeamDirection () const private
Checks that the beam direction is +Z, throws exception otherwise.
Definition at line 449 of file PredictPeaks.cpp.
References fabs, m_inst, Mantid::Kernel::V3D::X(), and Mantid::Kernel::V3D::Y().
Referenced by exec().
exec()
void Mantid::Crystal::PredictPeaks::exec () override private virtual
Run the algorithm.
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 168 of file PredictPeaks.cpp.
References Mantid::Geometry::Goniometer::calcFromQSampleAndWavelength(), calculateQAndAddToOutput(), calculateQAndAddToOutputLeanElastic(), checkBeamDirection(), Mantid::Kernel::Logger::error(), fillPossibleHKLsUsingGenerator(), fillPossibleHKLsUsingPeaksWorkspace(), Mantid::API::Algorithm::g_log, Mantid::Geometry::Goniometer::getEulerAngles(), Mantid::Geometry::IPeak::getGoniometerMatrix(), Mantid::API::Sample::getOrientedLattice(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Geometry::Goniometer::getR(), Mantid::Geometry::OrientedLattice::getUB(), Mantid::Kernel::Logger::information(), Mantid::Geometry::HKLFilterWavelength::isAllowed(), lambda, logNumberOfPeaksFound(), m_detectorCacheSearch, m_edge, m_inst, m_leanElasticPeak, m_pw, m_qConventionFactor, Mantid::Kernel::V3D::norm2(), Mantid::Kernel::ProgressBase::report(), setInstrumentFromInputWorkspace(), Mantid::Kernel::ProgressBase::setNotifyStep(), setReferenceFrameAndBeamDirection(), setRunNumberFromInputWorkspace(), setStructureFactorCalculatorFromSample(), Mantid::Kernel::Logger::warning(), Mantid::Kernel::withinAbsoluteDifference(), and Mantid::Kernel::V3D::Z().
fillPossibleHKLsUsingGenerator()
void Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingGenerator (const Geometry::OrientedLattice & orientedLattice, std::vector< Kernel::V3D > & possibleHKLs) const private
Fills possibleHKLs with all HKLs that are allowed within d- and lambda-limits.
Definition at line 466 of file PredictPeaks.cpp.
References Mantid::Geometry::HKLGenerator::begin(), Mantid::Geometry::HKLGenerator::end(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), m_refConds, and Mantid::Geometry::HKLGenerator::size().
Referenced by exec().
fillPossibleHKLsUsingPeaksWorkspace()
void Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingPeaksWorkspace (const API::IPeaksWorkspace_sptr & peaksWorkspace, std::vector< Kernel::V3D > & possibleHKLs) const private
Fills possibleHKLs with all HKLs from the supplied PeaksWorkspace.
Definition at line 502 of file PredictPeaks.cpp.
References Mantid::Geometry::IPeak::getHKL(), Mantid::API::Algorithm::getProperty(), Mantid::Crystal::qConventionFactor(), and Mantid::Kernel::V3D::round().
Referenced by exec().
getPeakParametersFromQ()
std::tuple< V3D, double > Mantid::Crystal::PredictPeaks::getPeakParametersFromQ (const Kernel::V3D & q) const private
Get the predicted detector direction from Q.
Get the detector direction and wavelength of a peak from it's QLab vector.
Parameters
q :: the q lab vector for this peak
Returns
a tuple containing the detector direction and the wavelength
Definition at line 668 of file PredictPeaks.cpp.
References m_qConventionFactor, m_refBeamDir, m_refFrame, Mantid::Kernel::V3D::norm(), Mantid::Kernel::V3D::normalize(), and Mantid::Kernel::V3D::scalar_prod().
Referenced by calculateQAndAddToOutput().
init()
void Mantid::Crystal::PredictPeaks::init () override private virtual
Initialise the properties.
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 52 of file PredictPeaks.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_DEFAULT, Mantid::Kernel::IS_NOT_DEFAULT, m_refConds, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertySettings().
logNumberOfPeaksFound()
void Mantid::Crystal::PredictPeaks::logNumberOfPeaksFound (size_t allowedPeakCount) const private
Log the number of peaks found to fall on and off detectors.
Parameters
allowedPeakCount :: number of candidate peaks found
Definition at line 403 of file PredictPeaks.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), m_pw, and Mantid::Kernel::Logger::notice().
Referenced by exec().
name()
const std::string Mantid::Crystal::PredictPeaks::name () const inline override virtual
Algorithm's name for identification.
Implements Mantid::API::Algorithm.
Definition at line 37 of file PredictPeaks.h.
seeAlso()
const std::vector< std::string > Mantid::Crystal::PredictPeaks::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 47 of file PredictPeaks.h.
setInstrumentFromInputWorkspace()
void Mantid::Crystal::PredictPeaks::setInstrumentFromInputWorkspace (const API::ExperimentInfo_sptr & inWS) private
Tries to set the internally stored instrument from an ExperimentInfo-object.
Definition at line 430 of file PredictPeaks.cpp.
References m_inst.
Referenced by exec().
setReferenceFrameAndBeamDirection()
void Mantid::Crystal::PredictPeaks::setReferenceFrameAndBeamDirection () private
Cache the reference frame and beam direction from the instrument.
Cache the reference frame and beam direction using the instrument.
Definition at line 683 of file PredictPeaks.cpp.
References m_inst, m_refBeamDir, and m_refFrame.
Referenced by exec().
setRunNumberFromInputWorkspace()
void Mantid::Crystal::PredictPeaks::setRunNumberFromInputWorkspace (const API::ExperimentInfo_sptr & inWS) private
Sets the run number from the supplied ExperimentInfo or throws an exception.
Definition at line 440 of file PredictPeaks.cpp.
References m_runNumber.
Referenced by exec().
setStructureFactorCalculatorFromSample()
void Mantid::Crystal::PredictPeaks::setStructureFactorCalculatorFromSample (const API::Sample & sample) private
Assigns a StructureFactorCalculator if available in sample.
This method constructs a StructureFactorCalculator using the CrystalStructure stored in sample if available. For consistency it sets the OrientedLattice in the sample as the unit cell of the crystal structure.
Additionally, the property CalculateStructureFactors is taken into account. If it's disabled, the calculator will not be assigned, disabling structure factor calculation.
Parameters
sample :: Sample, potentially with crystal structure
Definition at line 542 of file PredictPeaks.cpp.
References Mantid::API::Sample::getCrystalStructure(), Mantid::API::Sample::getOrientedLattice(), Mantid::API::Algorithm::getProperty(), Mantid::API::Sample::hasCrystalStructure(), m_sfCalculator, and Mantid::Geometry::CrystalStructure::setCell().
Referenced by exec().
summary()
const std::string Mantid::Crystal::PredictPeaks::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 39 of file PredictPeaks.h.
version()
int Mantid::Crystal::PredictPeaks::version () const inline override virtual
Algorithm's version for identification.
Implements Mantid::API::Algorithm.
Definition at line 46 of file PredictPeaks.h.
Member Data Documentation
m_detectorCacheSearch
std::unique_ptr<API::DetectorSearcher> Mantid::Crystal::PredictPeaks::m_detectorCacheSearch private
Detector search cache for fast look-up of detectors.
Definition at line 87 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), and exec().
m_edge
int Mantid::Crystal::PredictPeaks::m_edge private
Number of edge pixels with no peaks.
Definition at line 82 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), and exec().
m_inst
Geometry::Instrument_const_sptr Mantid::Crystal::PredictPeaks::m_inst private
Instrument reference.
Definition at line 91 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), checkBeamDirection(), exec(), setInstrumentFromInputWorkspace(), and setReferenceFrameAndBeamDirection().
m_leanElasticPeak
bool Mantid::Crystal::PredictPeaks::m_leanElasticPeak = false private
Definition at line 99 of file PredictPeaks.h.
Referenced by exec().
m_pw
Mantid::API::IPeaksWorkspace_sptr Mantid::Crystal::PredictPeaks::m_pw private
Output peaks workspace.
Definition at line 97 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), calculateQAndAddToOutputLeanElastic(), exec(), and logNumberOfPeaksFound().
m_qConventionFactor
double Mantid::Crystal::PredictPeaks::m_qConventionFactor private
Definition at line 101 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), calculateQAndAddToOutputLeanElastic(), exec(), and getPeakParametersFromQ().
m_refBeamDir
Kernel::V3D Mantid::Crystal::PredictPeaks::m_refBeamDir private
Direction of the beam for this instrument.
Definition at line 95 of file PredictPeaks.h.
Referenced by getPeakParametersFromQ(), and setReferenceFrameAndBeamDirection().
m_refConds
std::vector<Mantid::Geometry::ReflectionCondition_sptr> Mantid::Crystal::PredictPeaks::m_refConds private
Reflection conditions possible.
Definition at line 85 of file PredictPeaks.h.
Referenced by fillPossibleHKLsUsingGenerator(), and init().
m_refFrame
std::shared_ptr<const Geometry::ReferenceFrame> Mantid::Crystal::PredictPeaks::m_refFrame private
Reference frame for the instrument.
Definition at line 93 of file PredictPeaks.h.
Referenced by getPeakParametersFromQ(), and setReferenceFrameAndBeamDirection().
m_runNumber
int Mantid::Crystal::PredictPeaks::m_runNumber private
Run number of input workspace.
Definition at line 89 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), calculateQAndAddToOutputLeanElastic(), and setRunNumberFromInputWorkspace().
m_sfCalculator
Geometry::StructureFactorCalculator_sptr Mantid::Crystal::PredictPeaks::m_sfCalculator private
Definition at line 98 of file PredictPeaks.h.
Referenced by calculateQAndAddToOutput(), calculateQAndAddToOutputLeanElastic(), and setStructureFactorCalculatorFromSample().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/PredictPeaks.h
Framework/Crystal/src/PredictPeaks.cpp