Mantid: Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type > Struct Template Reference
Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type > Struct Template Reference
#include <RegisterWorkspacePtrToPython.h>
Public Types
using HeldType = std::shared_ptr< T >
Type required by TypeRegistry framework.
using PointeeType = T
Convenience typedef.
using PropertyValueType = std::shared_ptr< T >
Convenience typedef.
Public Member Functions
std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator, const unsigned int direction) const override
Create a PropertyWithValue from the given python object value.
void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::object &value) const override
Set function to handle Python -> C++ calls and get the correct type.
Public Member Functions inherited from Mantid::PythonInterface::Registry::PropertyValueHandler
virtual std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::object &value, const boost::python::object &validator, const unsigned int direction) const =0
Overload to create a Property type from the given value with no validation.
virtual void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::object &value) const =0
Overload to set the named property's value on the property manager.
virtual ~PropertyValueHandler ()=default
Virtual Destructor.
Detailed Description
template<typename T>
struct Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >
Definition at line 20 of file RegisterWorkspacePtrToPython.h.
Member Typedef Documentation
HeldType
template<typename T > using Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::HeldType = std::shared_ptr<T>
Type required by TypeRegistry framework.
Definition at line 24 of file RegisterWorkspacePtrToPython.h.
PointeeType
template<typename T > using Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::PointeeType = T
Convenience typedef.
Definition at line 27 of file RegisterWorkspacePtrToPython.h.
PropertyValueType
template<typename T > using Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::PropertyValueType = std::shared_ptr<T>
Convenience typedef.
Definition at line 29 of file RegisterWorkspacePtrToPython.h.
Member Function Documentation
create()
template<typename T > std::unique_ptr< Kernel::Property > Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::create (const std::string & name, const boost::python::object & defaultValue, const boost::python::object & validator, const unsigned int direction) const inline override virtual
Create a PropertyWithValue from the given python object value.
Parameters
name :: The name of the property
defaultValue :: The defaultValue of the property. The object attempts to extract a value of type ValueType from the python object
validator :: A python object pointing to a validator instance, which can be None.
direction :: The direction of the property
Returns
A pointer to a newly constructed property instance
Implements Mantid::PythonInterface::Registry::PropertyValueHandler.
Definition at line 55 of file RegisterWorkspacePtrToPython.h.
References Mantid::Kernel::IValidator::clone(), and Mantid::PythonInterface::isNone().
set()
template<typename T > void Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::set (Kernel::IPropertyManager * alg, const std::string & name, const boost::python::object & value) const inline override virtual
Set function to handle Python -> C++ calls and get the correct type.
Parameters
alg :: A pointer to an IPropertyManager
name :: The name of the property
value :: A boost python object that stores the value
Implements Mantid::PythonInterface::Registry::PropertyValueHandler.
Definition at line 37 of file RegisterWorkspacePtrToPython.h.
References Mantid::Kernel::IPropertyManager::setProperty(), and value.
The documentation for this struct was generated from the following file:
Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/RegisterWorkspacePtrToPython.h