Mantid: Mantid::DataHandling::ANSTO::Anxs Namespace Reference
Mantid::DataHandling::ANSTO::Anxs Namespace Reference
Enumerations
enum class ScanLog { Start , End , Mean }
Functions
int64_t epochRelDateTimeBase (int64_t epochInNanoSeconds)
template<typename T >
bool extractTimedDataSet (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t &eventTime, T &eventValue, std::string &units)
template<typename T >
uint64_t extractTimedDataSet (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > &times, std::vector< T > &events, std::string &units)
template bool extractTimedDataSet< double > (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t &eventTime, double &eventValue, std::string &units)
template uint64_t extractTimedDataSet< double > (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > &times, std::vector< double > &events, std::string &units)
template bool extractTimedDataSet< float > (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t &eventTime, float &eventValue, std::string &units)
template uint64_t extractTimedDataSet< float > (const Nexus::NXEntry &entry, const std::string &path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > &times, std::vector< float > &events, std::string &units)
std::string extractWorkspaceTitle (const std::string &nxsFile)
std::pair< uint64_t, uint64_t > getHMScanLimits (const Nexus::NXEntry &entry, int datasetIx)
std::pair< uint64_t, uint64_t > getTimeScanLimits (const Nexus::NXEntry &entry, int datasetIx)
bool isTimedDataSet (const Nexus::NXEntry &entry, const std::string &path)
template<typename T >
bool loadNXDataSet (const Nexus::NXEntry &entry, const std::string &path, T &value, int index)
template bool loadNXDataSet< double > (const Nexus::NXEntry &entry, const std::string &path, double &value, int index)
template bool loadNXDataSet< float > (const Nexus::NXEntry &entry, const std::string &path, float &value, int index)
template bool loadNXDataSet< int > (const Nexus::NXEntry &entry, const std::string &path, int &value, int index)
template bool loadNXDataSet< int64_t > (const Nexus::NXEntry &entry, const std::string &path, int64_t &value, int index)
template bool loadNXDataSet< uint64_t > (const Nexus::NXEntry &entry, const std::string &path, uint64_t &value, int index)
bool loadNXString (const Nexus::NXEntry &entry, const std::string &path, std::string &value)
void ReadEventData (ProgressTracker &prog, const Nexus::NXEntry &entry, EventProcessor *handler, uint64_t start_nsec, uint64_t end_nsec, const std::string &neutron_path, int tube_resolution=1024)
Enumeration Type Documentation
ScanLog
enum class Mantid::DataHandling::ANSTO::Anxs::ScanLog strong
Enumerator
Start
End
Mean
Definition at line 255 of file LoadANSTOHelper.h.
Function Documentation
epochRelDateTimeBase()
int64_t Mantid::DataHandling::ANSTO::Anxs::epochRelDateTimeBase (int64_t epochInNanoSeconds)
Definition at line 503 of file LoadANSTOHelper.cpp.
Referenced by Mantid::DataHandling::LoadBBY2::createInstrument().
extractTimedDataSet() [1/2]
template<typename T > bool Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t & eventTime, T & eventValue, std::string & units)
Definition at line 633 of file LoadANSTOHelper.cpp.
References End, Mean, n, and Start.
extractTimedDataSet() [2/2]
template<typename T > uint64_t Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > & times, std::vector< T > & events, std::string & units)
Definition at line 606 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::openNXDataSet().
Referenced by Mantid::DataHandling::LoadBBY2::createInstrument(), and Mantid::DataHandling::LoadBBY2::loadInstrumentParameters().
extractTimedDataSet< double >() [1/2]
template bool Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet< double > (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t & eventTime, double & eventValue, std::string & units)
extractTimedDataSet< double >() [2/2]
template uint64_t Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet< double > (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > & times, std::vector< double > & events, std::string & units)
extractTimedDataSet< float >() [1/2]
template bool Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet< float > (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, ScanLog valueOption, uint64_t & eventTime, float & eventValue, std::string & units)
extractTimedDataSet< float >() [2/2]
template uint64_t Mantid::DataHandling::ANSTO::Anxs::extractTimedDataSet< float > (const Nexus::NXEntry & entry, const std::string & path, uint64_t startTime, uint64_t endTime, std::vector< uint64_t > & times, std::vector< float > & events, std::string & units)
extractWorkspaceTitle()
std::string Mantid::DataHandling::ANSTO::Anxs::extractWorkspaceTitle (const std::string & nxsFile)
Definition at line 508 of file LoadANSTOHelper.cpp.
Referenced by Mantid::DataHandling::LoadBBY2::execLoader().
getHMScanLimits()
std::pair< uint64_t, uint64_t > Mantid::DataHandling::ANSTO::Anxs::getHMScanLimits (const Nexus::NXEntry & entry, int datasetIx)
Definition at line 579 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::openNXDataSet().
Referenced by Mantid::DataHandling::LoadBBY2::execLoader().
getTimeScanLimits()
std::pair< uint64_t, uint64_t > Mantid::DataHandling::ANSTO::Anxs::getTimeScanLimits (const Nexus::NXEntry & entry, int datasetIx)
Definition at line 559 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::openNXDataSet().
Referenced by Mantid::DataHandling::LoadBBY2::execLoader().
isTimedDataSet()
bool Mantid::DataHandling::ANSTO::Anxs::isTimedDataSet (const Nexus::NXEntry & entry, const std::string & path)
Definition at line 547 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::datasets(), and Mantid::Nexus::NXClass::openNXGroup().
loadNXDataSet()
template<typename T > bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet (const Nexus::NXEntry & entry, const std::string & path, T & value, int index)
Definition at line 517 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXDataSet::dim0(), index, Mantid::Nexus::NXDataSetTyped< T >::load(), Mantid::Nexus::NXClass::openNXDataSet(), and value.
Referenced by Mantid::DataHandling::LoadBBY2::createInstrument(), and Mantid::DataHandling::LoadBBY2::loadInstrumentParameters().
loadNXDataSet< double >()
template bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet< double > (const Nexus::NXEntry & entry, const std::string & path, double & value, int index)
loadNXDataSet< float >()
template bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet< float > (const Nexus::NXEntry & entry, const std::string & path, float & value, int index)
loadNXDataSet< int >()
template bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet< int > (const Nexus::NXEntry & entry, const std::string & path, int & value, int index)
loadNXDataSet< int64_t >()
template bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet< int64_t > (const Nexus::NXEntry & entry, const std::string & path, int64_t & value, int index)
loadNXDataSet< uint64_t >()
template bool Mantid::DataHandling::ANSTO::Anxs::loadNXDataSet< uint64_t > (const Nexus::NXEntry & entry, const std::string & path, uint64_t & value, int index)
loadNXString()
bool Mantid::DataHandling::ANSTO::Anxs::loadNXString (const Nexus::NXEntry & entry, const std::string & path, std::string & value)
Definition at line 535 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::openNXChar(), and value.
Referenced by Mantid::DataHandling::LoadBBY2::createInstrument(), and Mantid::DataHandling::LoadBBY2::loadInstrumentParameters().
ReadEventData()
void Mantid::DataHandling::ANSTO::Anxs::ReadEventData (ProgressTracker & prog, const Nexus::NXEntry & entry, EventProcessor * handler, uint64_t start_nsec, uint64_t end_nsec, const std::string & neutron_path, int tube_resolution = 1024)
Definition at line 663 of file LoadANSTOHelper.cpp.
References Mantid::DataHandling::ANSTO::EventProcessor::addEvent(), Mantid::DataHandling::ANSTO::EventProcessor::newFrame(), Mantid::Nexus::NXClass::openNXDataSet(), Mantid::DataHandling::ANSTO::ProgressTracker::setTarget(), Mantid::DataHandling::ANSTO::ProgressTracker::update(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::DataHandling::loadEvents().