Mantid: Mantid::Algorithms::SolidAngleHelpers::Rectangle Struct Reference
Mantid::Algorithms::SolidAngleHelpers::Rectangle Struct Reference
Public Member Functions
double solidAngle (size_t index) const override
SolidAngleCalculator (const ComponentInfo &componentInfo, const DetectorInfo &detectorInfo, const std::string &method, const double pixelArea)
Public Member Functions inherited from Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator
virtual double solidAngle (size_t index) const =0
SolidAngleCalculator (const ComponentInfo &componentInfo, const DetectorInfo &detectorInfo, const std::string &method, const double pixelArea)
virtual ~SolidAngleCalculator ()=default
Additional Inherited Members
Protected Attributes inherited from Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator
std::unique_ptr< const AlphaAngleCalculator > m_alphaAngleCalculator
const V3D m_beamLine
const ComponentInfo & m_componentInfo
const DetectorInfo & m_detectorInfo
const double m_pixelArea
const V3D m_samplePos
Detailed Description
Definition at line 110 of file SolidAngle.cpp.
Member Function Documentation
solidAngle()
double Mantid::Algorithms::SolidAngleHelpers::Rectangle::solidAngle (size_t index) const inline override virtual
Implements Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator.
Definition at line 112 of file SolidAngle.cpp.
References Mantid::Kernel::V3D::cosAngle(), index, Mantid::Geometry::DetectorInfo::l2(), Mantid::Kernel::l2, Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::m_beamLine, Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::m_componentInfo, Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::m_detectorInfo, Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::m_pixelArea, Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::m_samplePos, Mantid::Geometry::DetectorInfo::position(), and Mantid::Geometry::ComponentInfo::scaleFactor().
SolidAngleCalculator()
Mantid::Algorithms::SolidAngleHelpers::SolidAngleCalculator::SolidAngleCalculator (const ComponentInfo & componentInfo, const DetectorInfo & detectorInfo, const std::string & method, const double pixelArea) inline
Definition at line 83 of file SolidAngle.cpp.
The documentation for this struct was generated from the following file:
Framework/Algorithms/src/SolidAngle.cpp