Mantid: Mantid::Kernel::PropertyManagerProperty Class Reference
Mantid::Kernel::PropertyManagerProperty Class Reference final
#include <PropertyManagerProperty.h>
Public Types
using BaseClass = PropertyWithValue< PropertyManager_sptr >
using ValueType = PropertyManager_sptr
Public Member Functions
PropertyManagerProperty * clone () const override
'Virtual copy constructor'
std::string getDefault () const override
PropertyManagerProperty & operator= (const PropertyManagerProperty &)=default
PropertyManagerProperty (const PropertyManagerProperty &)=default
PropertyManagerProperty (const std::string &name, const ValueType &defaultValue, unsigned int direction=Direction::Input)
Constructor taking an initial value.
PropertyManagerProperty (const std::string &name, unsigned int direction=Direction::Input)
Constructor with a default empty pointer.
std::string setValue (const std::string &strValue) override
Overwrite the current value.
std::string setValueFromJson (const Json::Value &value) override
Sets the value of the property from a Json object.
std::string value () const override
Json::Value valueAsJson () const override
Create a Json::Value objectValue from the PropertyManager.
Public Member Functions inherited from Mantid::Kernel::PropertyWithValue< PropertyManager_sptr >
std::vector< std::string > allowedValues () const override
Returns the set of valid values for this property, if such a set exists.
PropertyWithValue< PropertyManager_sptr > * clone () const override
'Virtual copy constructor'
std::string getDefault () const override
Get the default value for the property which is the value the property was initialised with.
IValidator_sptr getValidator () const
bool isDefault () const override
Overriden function that returns if property has the same value that it was initialised with, if applicable.
bool isMultipleSelectionAllowed () override
Is Multiple Selection Allowed.
std::string isValid () const override
Overridden function that checks whether the property, if not overriden returns "".
virtual operator const PropertyManager_sptr & () const
bool operator!= (const PropertyWithValue< PropertyManager_sptr > &rhs) const
virtual const PropertyManager_sptr & operator() () const
PropertyWithValue & operator+= (Property const *right) override
Add to this.
virtual PropertyWithValue & operator= (const PropertyManager_sptr &value)
PropertyWithValue & operator= (const PropertyWithValue &right)
bool operator== (const PropertyWithValue< PropertyManager_sptr > &rhs) const
PropertyWithValue (const PropertyWithValue< PropertyManager_sptr > &right)
PropertyWithValue (const std::string &name, PropertyManager_sptr defaultValue, const std::string &defaultValueStr, IValidator_sptr validator, const unsigned int direction)
PropertyWithValue (std::string name, PropertyManager_sptr defaultValue, const unsigned int direction)
PropertyWithValue (std::string name, PropertyManager_sptr defaultValue, IValidator_sptr validator=IValidator_sptr(new NullValidator), const unsigned int direction=Direction::Input)
virtual void replaceValidator (IValidator_sptr newValidator)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
MANTID_KERNEL_DLL void saveProperty (::NeXus::File *file)
void saveProperty (::NeXus::File *file) override
std::string setDataItem (const std::shared_ptr< DataItem > &data) override
Set the value of the property via a DataItem pointer.
std::string setValue (const std::string &value) override
Set the value of the property via a string.
std::string setValueFromJson (const Json::Value &value) override
Set the value of the property via a Json object.
int size () const override
Return the size of this property.
std::string value () const override
Returns the value of the property as a string.
Json::Value valueAsJson () const override
Returns the value of the property as a Json::Value.
std::string valueAsPrettyStr (const size_t maxLength=0, const bool collapseLists=true) const override
Returns the value of the property as a pretty printed string.
Public Member Functions inherited from Mantid::Kernel::Property
virtual std::vector< std::string > allowedValues () const
Returns the set of valid values for this property, if such a set exists.
bool autoTrim () const
Returns if the property is set to automatically trim string unput values of whitespace.
void clearSettings ()
Deletes the PropertySettings object contained.
virtual Property * clone () const =0
'Virtual copy constructor'
virtual const PropertyHistory createHistory () const
Create a PropertyHistory object representing the current state of the Property.
void createTemporaryValue ()
Create a temporary value for this property.
unsigned int direction () const
returns the direction of the property
const std::string & documentation () const
Get the property's documentation string.
virtual void filterByTime (const Types::Core::DateAndTime &start, const Types::Core::DateAndTime &stop)
Filter out a property by time.
virtual std::string getDefault () const =0
Get the default value for the property which is the value the property was initialised with.
const std::string & getGroup ()
virtual size_t getMemorySize () const
IPropertySettings * getSettings ()
bool hasTemporaryValue () const
Property is using a temporary value for this property.
virtual bool isDefault () const =0
Overriden function that returns if property has the same value that it was initialised with, if applicable.
virtual bool isMultipleSelectionAllowed ()
Is Multiple Selection Allowed.
virtual std::string isValid () const
Overridden function that checks whether the property, if not overriden returns "".
virtual bool isValueSerializable () const
Whether the string returned by value() can be used for serialization.
virtual Property & merge (Property *)
Just returns the property (*this) unless overridden.
const std::string & name () const
Get the property's name.
virtual Property & operator+= (Property const *rhs)=0
Add to this.
bool remember () const
Whether to save input values.
virtual void saveProperty (::NeXus::File *)
void setAutoTrim (const bool &setting)
Sets if the property is set to automatically trim string unput values of whitespace.
virtual std::string setDataItem (const std::shared_ptr< DataItem > &)=0
Set the value of the property via a DataItem pointer.
void setDocumentation (const std::string &documentation)
Sets the user level description of the property.
void setGroup (const std::string &group)
Set the group this property belongs to.
void setRemember (bool)
Set wheter to remeber this property input.
void setSettings (std::unique_ptr< IPropertySettings > settings)
Set the PropertySettings object.
virtual void setUnits (const std::string &unit)
Sets the units of the property, as a string.
virtual std::string setValue (const std::string &)=0
Set the value of the property via a string.
virtual std::string setValueFromJson (const Json::Value &)=0
Set the value of the property via a Json object.
virtual std::string setValueFromProperty (const Property &right)=0
Set the value of the property via a reference to another property.
virtual int size () const
Return the size of this property.
virtual void splitByTime (std::vector< SplittingInterval > &splitter, std::vector< Property * > outputs, bool isProtonCharge=true) const
Split a property by time.
const std::string type () const
Returns the type of the property as a string.
const std::type_info * type_info () const
Get the property type_info.
virtual const std::string & units () const
Returns the units of the property, if any, as a string.
virtual std::string value () const =0
Returns the value of the property as a string.
virtual Json::Value valueAsJson () const =0
Returns the value of the property as a Json::Value.
virtual std::string valueAsPrettyStr (const size_t maxLength=0, const bool collapseLists=true) const
Returns the value of the property as a pretty printed string.
virtual ~Property ()
Virtual destructor.
Private Attributes
std::string m_dataServiceKey
std::string m_defaultAsStr
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Property
Property (const Property &right)
Copy constructor.
Property (std::string name, const std::type_info &type, const unsigned int &direction=Direction::Input)
Constructor.
Protected Attributes inherited from Mantid::Kernel::PropertyWithValue< PropertyManager_sptr >
PropertyManager_sptr m_initialValue
the property's default value which is also its initial value
PropertyManager_sptr m_value
The value of the property.
Protected Attributes inherited from Mantid::Kernel::Property
std::string m_name
The name of the property.
Detailed Description
Definition at line 15 of file PropertyManagerProperty.h.
Member Typedef Documentation
BaseClass
using Mantid::Kernel::PropertyManagerProperty::BaseClass = PropertyWithValue<PropertyManager_sptr>
Definition at line 18 of file PropertyManagerProperty.h.
ValueType
using Mantid::Kernel::PropertyManagerProperty::ValueType = PropertyManager_sptr
Definition at line 19 of file PropertyManagerProperty.h.
Constructor & Destructor Documentation
PropertyManagerProperty() [1/3]
Mantid::Kernel::PropertyManagerProperty::PropertyManagerProperty (const std::string & name, unsigned int direction = Direction::Input)
Constructor with a default empty pointer.
Parameters
name The name of the property
direction Direction of the property
Definition at line 26 of file PropertyManagerProperty.cpp.
PropertyManagerProperty() [2/3]
Mantid::Kernel::PropertyManagerProperty::PropertyManagerProperty (const std::string & name, const ValueType & defaultValue, unsigned int direction = Direction::Input)
Constructor taking an initial value.
Parameters
name The name of the property
defaultValue A default value for the property
direction Direction of the property
Definition at line 35 of file PropertyManagerProperty.cpp.
References m_defaultAsStr, and Mantid::Kernel::Property::name().
PropertyManagerProperty() [3/3]
Mantid::Kernel::PropertyManagerProperty::PropertyManagerProperty (const PropertyManagerProperty &) default
Member Function Documentation
clone()
PropertyManagerProperty * Mantid::Kernel::PropertyManagerProperty::clone () const inline override virtual
'Virtual copy constructor'
Implements Mantid::Kernel::Property.
Definition at line 29 of file PropertyManagerProperty.h.
getDefault()
std::string Mantid::Kernel::PropertyManagerProperty::getDefault () const override virtual
Returns
The string representation of the default value
Implements Mantid::Kernel::Property.
Definition at line 65 of file PropertyManagerProperty.cpp.
References m_defaultAsStr.
operator=()
PropertyManagerProperty & Mantid::Kernel::PropertyManagerProperty::operator= (const PropertyManagerProperty &) default
setValue()
std::string Mantid::Kernel::PropertyManagerProperty::setValue (const std::string & strValue) override virtual
Overwrite the current value.
The string is expected to contain either:
the key to a PropertyManager stored in the PropertyManagerDataService
or json-serialized data, where the properties must already exist on the containing PropertyManager
Parameters
strValue A string assumed to contain serialized Json
Returns
If an error occurred then this contains an error message, otherwise an empty string
Implements Mantid::Kernel::Property.
Definition at line 76 of file PropertyManagerProperty.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_dataServiceKey, and value().
setValueFromJson()
std::string Mantid::Kernel::PropertyManagerProperty::setValueFromJson (const Json::Value & value) override virtual
Sets the value of the property from a Json object.
Parameters
value A Json objectValue
Returns
An empty string indicating success otherwise a help message indicating what error has occurred
Implements Mantid::Kernel::Property.
Definition at line 117 of file PropertyManagerProperty.cpp.
References Mantid::Kernel::createPropertyManager(), std::to_string(), and value().
value()
std::string Mantid::Kernel::PropertyManagerProperty::value () const override virtual
Returns
The value of the property represented as a string
Implements Mantid::Kernel::Property.
Definition at line 48 of file PropertyManagerProperty.cpp.
References m_dataServiceKey.
Referenced by setValue(), and setValueFromJson().
valueAsJson()
Json::Value Mantid::Kernel::PropertyManagerProperty::valueAsJson () const override virtual
Create a Json::Value objectValue from the PropertyManager.
Implements Mantid::Kernel::Property.
Definition at line 59 of file PropertyManagerProperty.cpp.
Member Data Documentation
m_dataServiceKey
std::string Mantid::Kernel::PropertyManagerProperty::m_dataServiceKey private
Definition at line 38 of file PropertyManagerProperty.h.
Referenced by setValue(), and value().
m_defaultAsStr
std::string Mantid::Kernel::PropertyManagerProperty::m_defaultAsStr private
Definition at line 39 of file PropertyManagerProperty.h.
Referenced by getDefault(), and PropertyManagerProperty().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/PropertyManagerProperty.h
Framework/Kernel/src/PropertyManagerProperty.cpp