Mantid: Mantid::API::IAlgorithm Class Reference
Mantid::API::IAlgorithm Class Reference abstract
IAlgorithm is the interface implemented by the Algorithm base class.
#include <IAlgorithm.h>
Public Member Functions
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
virtual const std::string workspaceMethodName () const =0
virtual const std::vector< std::string > workspaceMethodOn () const =0
Returns a set of class names that will have the method attached.
virtual const std::string workspaceMethodInputProperty () const =0
Returns the name of the input workspace property used by the calling object.
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Detailed Description
IAlgorithm is the interface implemented by the Algorithm base class.
Concrete algorithms, derived from the Algorithm base class are controlled via this interface.
Author
Russell Taylor, Tessella Support Services plc
Based on the Gaudi class of the same name (see http://proj-gaudi.web.cern.ch/proj-gaudi/)
Date
11/09/2007
Definition at line 45 of file IAlgorithm.h.
Member Function Documentation
addObserver()
virtual void Mantid::API::IAlgorithm::addObserver (const Poco::AbstractObserver & observer) const pure virtual
Add an observer for a notification.
Implemented in Mantid::API::Algorithm.
alias()
virtual const std::string Mantid::API::IAlgorithm::alias () const pure virtual
function to return any aliases of the algorithm.
Implemented in Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::Minus, Mantid::Algorithms::Rebin, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::ResampleX, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::API::Algorithm, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::Load, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::UpdateInstrumentFromFile, and Mantid::MDAlgorithms::TransposeMD.
Referenced by Mantid::API::DeprecatedAlias::deprecationMessage(), and export_ialgorithm().
aliasDeprecated()
virtual const std::string Mantid::API::IAlgorithm::aliasDeprecated () const pure virtual
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
cancel()
virtual void Mantid::API::IAlgorithm::cancel () pure virtual
Raises the cancel flag.
interuption_point() method if called inside exec() checks this flag and if true terminates the algorithm.
Implemented in Mantid::API::Algorithm, and Mantid::DataHandling::Load.
Referenced by export_ialgorithm().
categories()
virtual const std::vector< std::string > Mantid::API::IAlgorithm::categories () const pure virtual
Function to return all of the categories that contain this algorithm.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
category()
virtual const std::string Mantid::API::IAlgorithm::category () const pure virtual
function to return a category of the algorithm.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::BinaryOperation, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnaryOperation, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::WorkspaceJoiners, Mantid::Algorithms::XDataConverter, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::API::Algorithm, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::CurveFitting::IFittingAlgorithm, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficienciesBase, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDParent, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, and Mantid::DataHandling::SetSample.
Referenced by export_ialgorithm().
categorySeparator()
virtual const std::string Mantid::API::IAlgorithm::categorySeparator () const pure virtual
Function to return the separator token for the category string.
Implemented in Mantid::API::Algorithm.
enableHistoryRecordingForChild()
virtual void Mantid::API::IAlgorithm::enableHistoryRecordingForChild (const bool on) pure virtual
If true history will be recorded for a child.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
execute()
virtual bool Mantid::API::IAlgorithm::execute () pure virtual
System execution.
This method invokes the exec() method of a concrete algorithm.
Implemented in Mantid::API::Algorithm.
executeAsChildAlg()
virtual void Mantid::API::IAlgorithm::executeAsChildAlg () pure virtual
Execute as a Child Algorithm, with try/catch.
Implemented in Mantid::API::Algorithm.
Referenced by Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit().
executeAsync()
virtual Poco::ActiveResult< bool > Mantid::API::IAlgorithm::executeAsync () pure virtual
Asynchronous execution of the algorithm.
Implemented in Mantid::API::Algorithm.
executionState()
virtual ExecutionState Mantid::API::IAlgorithm::executionState () const pure virtual
Gets the current execution state.
Implemented in Mantid::API::Algorithm.
getAlgorithmID()
virtual AlgorithmID Mantid::API::IAlgorithm::getAlgorithmID () const pure virtual
Algorithm ID.
Unmanaged algorithms return 0 (or NULL?) values. Managed ones have non-zero.
Implemented in Mantid::API::Algorithm.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::progressHandle(), MantidQt::MantidWidgets::AlgorithmProgressModel::removeFrom(), and MantidQt::MantidWidgets::AlgorithmProgressModel::startHandle().
getAlgStartupLogging()
virtual bool Mantid::API::IAlgorithm::getAlgStartupLogging () const pure virtual
get the state of Logging of start and end messages
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
getAlwaysStoreInADS()
virtual bool Mantid::API::IAlgorithm::getAlwaysStoreInADS () const pure virtual
To query whether the output is stored in the analysis data service.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
getLoggingOffset()
virtual int Mantid::API::IAlgorithm::getLoggingOffset () const pure virtual
returns the logging priority offset
Implemented in Mantid::API::Algorithm.
helpURL()
virtual const std::string Mantid::API::IAlgorithm::helpURL () const pure virtual
function to return an optional URL for documentation.
Override if the algorithm is not part of the Mantid distribution
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
initialize()
virtual void Mantid::API::IAlgorithm::initialize () pure virtual
Initialization method invoked by the framework.
This method is responsible for any bookkeeping of initialization required by the framework itself. It will in turn invoke the init() method of the derived algorithm, and of any Child Algorithms which it creates.
Implemented in Mantid::API::Algorithm.
isChild()
virtual bool Mantid::API::IAlgorithm::isChild () const pure virtual
To query whether algorithm is a child. Default to false.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
isExecuted()
virtual bool Mantid::API::IAlgorithm::isExecuted () const pure virtual
Check whether the algorithm has been executed sucessfully.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
isInitialized()
virtual bool Mantid::API::IAlgorithm::isInitialized () const pure virtual
Check whether the algorithm is initialized properly.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
isLogging()
virtual bool Mantid::API::IAlgorithm::isLogging () const pure virtual
returns the status of logging, True = enabled
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
isReadyForGarbageCollection()
virtual bool Mantid::API::IAlgorithm::isReadyForGarbageCollection () const pure virtual
True if the algorithm is ready for garbage collection.
Implemented in Mantid::API::Algorithm.
isRunning()
virtual bool Mantid::API::IAlgorithm::isRunning () const pure virtual
True if the algorithm is running.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
name()
virtual const std::string Mantid::API::IAlgorithm::name () const pure virtual
function to return a name of the algorithm, must be overridden in all algorithms
Implemented in Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CuboidGaugeVolumeAbsorption, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSResolution, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::API::Algorithm, and Mantid::MDAlgorithms::ConvertToMDParent.
Referenced by Mantid::API::Algorithm::copyNonWorkspaceProperties(), Mantid::API::DeprecatedAlias::deprecationMessage(), Mantid::API::DeprecatedAlgorithm::deprecationMsg(), export_ialgorithm(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandle().
removeObserver()
virtual void Mantid::API::IAlgorithm::removeObserver (const Poco::AbstractObserver & observer) const pure virtual
Remove an observer.
Implemented in Mantid::API::Algorithm.
Referenced by Mantid::API::AlgorithmObserver::stopObserving().
resultState()
virtual ResultState Mantid::API::IAlgorithm::resultState () const pure virtual
Gets the currnet result State.
Implemented in Mantid::API::Algorithm.
seeAlso()
virtual const std::vector< std::string > Mantid::API::IAlgorithm::seeAlso () const pure virtual
Function to return all of the seeAlso algorithms related to this algorithm.
Implemented in Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearCache, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropToComponent, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSResolution, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::API::Algorithm, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, and Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection.
Referenced by export_ialgorithm().
setAlgStartupLogging()
virtual void Mantid::API::IAlgorithm::setAlgStartupLogging (const bool enabled) pure virtual
disable Logging of start and end messages
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
setAlwaysStoreInADS()
virtual void Mantid::API::IAlgorithm::setAlwaysStoreInADS (const bool doStore) pure virtual
Set whether we always store the output in the analysis data service.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
setChild()
virtual void Mantid::API::IAlgorithm::setChild (const bool isChild) pure virtual
To set whether algorithm is a child.
Parameters
isChild :: True - the algorithm is a child algorithm. False - this is a full managed algorithm.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
setChildEndProgress()
virtual void Mantid::API::IAlgorithm::setChildEndProgress (const double endProgress) const pure virtual
setting the child end progress
Implemented in Mantid::API::Algorithm.
setChildStartProgress()
virtual void Mantid::API::IAlgorithm::setChildStartProgress (const double startProgress) const pure virtual
setting the child start progress
Implemented in Mantid::API::Algorithm.
setLogging()
virtual void Mantid::API::IAlgorithm::setLogging (const bool value) pure virtual
Logging can be disabled by passing a value of false.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
setLoggingOffset()
virtual void Mantid::API::IAlgorithm::setLoggingOffset (const int value) pure virtual
gets the logging priority offset
Implemented in Mantid::API::Algorithm.
setRethrows()
virtual void Mantid::API::IAlgorithm::setRethrows (const bool rethrow) pure virtual
To query whether an algorithm should rethrow exceptions when executing.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
summary()
virtual const std::string Mantid::API::IAlgorithm::summary () const pure virtual
function returns a summary message that will be displayed in the default GUI, and in the help.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToHistogram, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertToPointData, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreatePSDBleedMask, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CuboidGaugeVolumeAbsorption, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSResolution, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnaryOperation, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::WorkspaceJoiners, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::CurveFitting::Functions::UserFunction1D, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, and Mantid::API::Algorithm.
Referenced by export_ialgorithm().
toJson()
virtual ::Json::Value Mantid::API::IAlgorithm::toJson () const pure virtual
Serialize an algorithm as Json.
Implemented in Mantid::API::Algorithm.
toString()
virtual std::string Mantid::API::IAlgorithm::toString () const pure virtual
Serialize an algorithm.
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
validateInputs()
virtual std::map< std::string, std::string > Mantid::API::IAlgorithm::validateInputs () pure virtual
Method checking errors on ALL the inputs, before execution.
For use mostly in dialogs.
Implemented in Mantid::Algorithms::AbsorptionCorrection, Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropToComponent, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::LineProfile, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ResampleX, Mantid::Algorithms::Scale, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::API::Algorithm, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::IndexPeaks, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SetGoniometer, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::ImportMDHistoWorkspaceBase, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::QTransform, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::PythonInterface::RunPythonScript, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, and Mantid::Algorithms::CreateEPP.
version()
virtual int Mantid::API::IAlgorithm::version () const pure virtual
function to return a version of the algorithm, must be overridden in all algorithms
Implemented in Mantid::Algorithms::AddAbsorptionWeightedPathLengths, Mantid::Algorithms::AddLogDerivative, Mantid::Algorithms::AddLogInterpolated, Mantid::Algorithms::AddLogSmoothed, Mantid::Algorithms::AddPeak, Mantid::Algorithms::AddSampleLog, Mantid::Algorithms::AddTimeSeriesLog, Mantid::Algorithms::AnnularRingAbsorption, Mantid::Algorithms::AnyShapeAbsorption, Mantid::Algorithms::AppendSpectra, Mantid::Algorithms::ApplyCalibration, Mantid::Algorithms::ApplyDetailedBalance, Mantid::Algorithms::ApplyFloodWorkspace, Mantid::Algorithms::ApplyInstrumentToPeaks, Mantid::Algorithms::ApplyTransmissionCorrection, Mantid::Algorithms::AverageLogData, Mantid::Algorithms::Bin2DPowderDiffraction, Mantid::Algorithms::BinaryOperateMasks, Mantid::Algorithms::CalculateCountRate, Mantid::Algorithms::CalculateDIFC, Mantid::Algorithms::CalculateDynamicRange, Mantid::Algorithms::CalculateEfficiency, Mantid::Algorithms::CalculateEfficiency2, Mantid::Algorithms::CalculateFlatBackground, Mantid::Algorithms::CalculateIqt, Mantid::Algorithms::CalculatePlaczek, Mantid::Algorithms::CalculatePlaczekSelfScattering, Mantid::Algorithms::CalculatePlaczekSelfScattering2, Mantid::Algorithms::CalculatePolynomialBackground, Mantid::Algorithms::CalculateTransmission, Mantid::Algorithms::CalculateTransmissionBeamSpreader, Mantid::Algorithms::CalculateZscore, Mantid::Algorithms::ChangeBinOffset, Mantid::Algorithms::ChangeLogTime, Mantid::Algorithms::ChangePulsetime, Mantid::Algorithms::ChangePulsetime2, Mantid::Algorithms::ChangeTimeZero, Mantid::Algorithms::ChopData, Mantid::Algorithms::ClearInstrumentParameters, Mantid::Algorithms::ClearMaskFlag, Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::CombineDiffCal, Mantid::Algorithms::CombineTableWorkspaces, Mantid::Algorithms::Comment, Mantid::Algorithms::CompareWorkspaces, Mantid::Algorithms::ConjoinWorkspaces, Mantid::Algorithms::ConjoinXRuns, Mantid::Algorithms::ConvertAxesToRealSpace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertDiffCal, Mantid::Algorithms::ConvertFromDistribution, Mantid::Algorithms::ConvertSpectrumAxis, Mantid::Algorithms::ConvertSpectrumAxis2, Mantid::Algorithms::ConvertTableToMatrixWorkspace, Mantid::Algorithms::ConvertToConstantL2, Mantid::Algorithms::ConvertToDistribution, Mantid::Algorithms::ConvertToEventWorkspace, Mantid::Algorithms::ConvertToMatrixWorkspace, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::CopyDataRange, Mantid::Algorithms::CopyDetectorMapping, Mantid::Algorithms::CopyInstrumentParameters, Mantid::Algorithms::CopyLogs, Mantid::Algorithms::CopySample, Mantid::Algorithms::CorelliCalibrationApply, Mantid::Algorithms::CorelliCalibrationDatabase, Mantid::Algorithms::CorelliCrossCorrelate, Mantid::Algorithms::CorrectKiKf, Mantid::Algorithms::CorrectTOFAxis, Mantid::Algorithms::CorrectToFile, Mantid::Algorithms::CreateBootstrapWorkspaces, Mantid::Algorithms::CreateCalFileByNames, Mantid::Algorithms::CreateDetectorTable, Mantid::Algorithms::CreateDummyCalFile, Mantid::Algorithms::CreateEPP, Mantid::Algorithms::CreateFlatEventWorkspace, Mantid::Algorithms::CreateFloodWorkspace, Mantid::Algorithms::CreateGroupingWorkspace, Mantid::Algorithms::CreateLogPropertyTable, Mantid::Algorithms::CreateLogTimeCorrection, Mantid::Algorithms::CreateMonteCarloWorkspace, Mantid::Algorithms::CreatePeaksWorkspace, Mantid::Algorithms::CreateSampleWorkspace, Mantid::Algorithms::CreateSingleValuedWorkspace, Mantid::Algorithms::CreateUserDefinedBackground, Mantid::Algorithms::CreateWorkspace, Mantid::Algorithms::CropWorkspace, Mantid::Algorithms::CropWorkspaceRagged, Mantid::Algorithms::CrossCorrelate, Mantid::Algorithms::CylinderAbsorption, Mantid::Algorithms::DeadTimeCorrection, Mantid::Algorithms::DeleteLog, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::DeleteWorkspaces, Mantid::Algorithms::DetectorDiagnostic, Mantid::Algorithms::DetectorEfficiencyCor, Mantid::Algorithms::DetectorEfficiencyCorUser, Mantid::Algorithms::DetectorEfficiencyVariation, Mantid::Algorithms::DetermineSpinStateOrder, Mantid::Algorithms::DiffractionEventCalibrateDetectors, Mantid::Algorithms::DiffractionFocussing, Mantid::Algorithms::DiffractionFocussing2, Mantid::Algorithms::DirectILLTubeBackground, Mantid::Algorithms::DiscusMultipleScatteringCorrection, Mantid::Algorithms::Divide, Mantid::Algorithms::EditInstrumentGeometry, Mantid::Algorithms::ElasticWindow, Mantid::Algorithms::EQSANSCorrectFrame, Mantid::Algorithms::EQSANSTofStructure, Mantid::Algorithms::EstimateDivergence, Mantid::Algorithms::EstimateResolutionDiffraction, Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass, Mantid::Algorithms::Exponential, Mantid::Algorithms::ExponentialCorrection, Mantid::Algorithms::ExportTimeSeriesLog, Mantid::Algorithms::ExtractFFTSpectrum, Mantid::Algorithms::ExtractMask, Mantid::Algorithms::ExtractMaskToTable, Mantid::Algorithms::ExtractSingleSpectrum, Mantid::Algorithms::ExtractSpectra, Mantid::Algorithms::ExtractSpectra2, Mantid::Algorithms::ExtractUnmaskedSpectra, Mantid::Algorithms::FFT, Mantid::Algorithms::FFTDerivative, Mantid::Algorithms::FFTSmooth, Mantid::Algorithms::FFTSmooth::FFTSmooth2, Mantid::Algorithms::FilterBadPulses, Mantid::Algorithms::FilterByLogValue, Mantid::Algorithms::FilterByTime, Mantid::Algorithms::FilterByXValue, Mantid::Algorithms::FilterEvents, Mantid::Algorithms::FindCenterOfMassPosition, Mantid::Algorithms::FindCenterOfMassPosition2, Mantid::Algorithms::FindDeadDetectors, Mantid::Algorithms::FindDetectorsOutsideLimits, Mantid::Algorithms::FindEPP, Mantid::Algorithms::FindPeakBackground, Mantid::Algorithms::FindPeaks, Mantid::Algorithms::FindPeaksConvolve, Mantid::Algorithms::FitOneSinglePeak, Mantid::Algorithms::FitPeak, Mantid::Algorithms::FitPeaks, Mantid::Algorithms::FixGSASInstrumentFile, Mantid::Algorithms::FlatPlateAbsorption, Mantid::Algorithms::GeneralisedSecondDifference, Mantid::Algorithms::GenerateEventsFilter, Mantid::Algorithms::GenerateGoniometerIndependentBackground, Mantid::Algorithms::GenerateIPythonNotebook, Mantid::Algorithms::GeneratePeaks, Mantid::Algorithms::GeneratePythonFitScript, Mantid::Algorithms::GeneratePythonScript, Mantid::Algorithms::GetAllEi, Mantid::Algorithms::GetDetectorOffsets, Mantid::Algorithms::GetEi, Mantid::Algorithms::GetEi2, Mantid::Algorithms::GetEiMonDet3, Mantid::Algorithms::GetQsInQENSData, Mantid::Algorithms::GetTimeSeriesLogInformation, Mantid::Algorithms::GroupToXResolution, Mantid::Algorithms::GroupWorkspaces, Mantid::Algorithms::He3TubeEfficiency, Mantid::Algorithms::HRPDSlabCanAbsorption, Mantid::Algorithms::HyspecScharpfCorrection, Mantid::Algorithms::IdentifyNoisyDetectors, Mantid::Algorithms::IntegrateByComponent, Mantid::Algorithms::IntegrateEPP, Mantid::Algorithms::Integration, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::InvertMask, Mantid::Algorithms::IQTransform, Mantid::Algorithms::LineProfile, Mantid::Algorithms::Logarithm, Mantid::Algorithms::LorentzCorrection, Mantid::Algorithms::MagFormFactorCorrection, Mantid::Algorithms::MaskBins, Mantid::Algorithms::MaskBinsFromTable, Mantid::Algorithms::MaskBinsFromWorkspace, Mantid::Algorithms::MaskBinsIf, Mantid::Algorithms::MaskDetectorsIf, Mantid::Algorithms::MaskInstrument, Mantid::Algorithms::MaskNonOverlappingBins, Mantid::Algorithms::Max, Mantid::Algorithms::MaxEnt, Mantid::Algorithms::MaxMin, Mantid::Algorithms::MedianDetectorTest, Mantid::Algorithms::MergeLogs, Mantid::Algorithms::MergeRuns, Mantid::Algorithms::Min, Mantid::Algorithms::Minus, Mantid::Algorithms::ModeratorTzero, Mantid::Algorithms::ModeratorTzeroLinear, Mantid::Algorithms::MonitorEfficiencyCorUser, Mantid::Algorithms::MonteCarloAbsorption, Mantid::Algorithms::MostLikelyMean, Mantid::Algorithms::MultipleScatteringCorrection, Mantid::Algorithms::MultipleScatteringCylinderAbsorption, Mantid::Algorithms::Multiply, Mantid::Algorithms::MultiplyRange, Mantid::Algorithms::NormaliseByCurrent, Mantid::Algorithms::NormaliseByDetector, Mantid::Algorithms::NormaliseToMonitor, Mantid::Algorithms::NormaliseToUnity, Mantid::Algorithms::OneMinusExponentialCor, Mantid::Algorithms::PaalmanPingsAbsorptionCorrection, Mantid::Algorithms::PaddingAndApodization, Mantid::Algorithms::ParallaxCorrection, Mantid::Algorithms::Pause, Mantid::Algorithms::PDCalibration, Mantid::Algorithms::PDDetermineCharacterizations, Mantid::Algorithms::PDFFourierTransform, Mantid::Algorithms::PDFFourierTransform2, Mantid::Algorithms::Plus, Mantid::Algorithms::PointByPointVCorrection, Mantid::Algorithms::PoissonErrors, Mantid::Algorithms::PolarizationCorrectionFredrikze, Mantid::Algorithms::DepolarizedAnalyserTransmission, Mantid::Algorithms::FlipperEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiency, Mantid::Algorithms::HeliumAnalyserEfficiencyTime, Mantid::Algorithms::PolarizationEfficienciesWildes, Mantid::Algorithms::PolarizerEfficiency, Mantid::Algorithms::PolarizationCorrectionWildes, Mantid::Algorithms::PolarizationEfficiencyCor, Mantid::Algorithms::PolynomialCorrection, Mantid::Algorithms::Power, Mantid::Algorithms::PowerLawCorrection, Mantid::Algorithms::Q1D2, Mantid::Algorithms::Q1DWeighted, Mantid::Algorithms::Qxy, Mantid::Algorithms::RadiusSum, Mantid::Algorithms::RayTracerTester, Mantid::Algorithms::ReadGroupsFromFile, Mantid::Algorithms::RealFFT::RealFFT, Mantid::Algorithms::Rebin, Mantid::Algorithms::Rebin2D, Mantid::Algorithms::RebinByPulseTimes, Mantid::Algorithms::RebinByTimeAtSample, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RebinToWorkspace, Mantid::Algorithms::Rebunch, Mantid::Algorithms::Regroup, Mantid::Algorithms::RemoveBackground, Mantid::Algorithms::RemoveBins, Mantid::Algorithms::RemoveInstrumentGeometry, Mantid::Algorithms::RemoveLowResTOF, Mantid::Algorithms::RemoveMaskedSpectra, Mantid::Algorithms::RemovePromptPulse, Mantid::Algorithms::RemoveSpectra, Mantid::Algorithms::RemoveWorkspaceHistory, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::RenameWorkspaces, Mantid::Algorithms::ReplaceSpecialValues, Mantid::Algorithms::ResampleX, Mantid::Algorithms::ResetNegatives, Mantid::Algorithms::ResizeRectangularDetector, Mantid::Algorithms::RingProfile, Mantid::Algorithms::MayersSampleCorrection, Mantid::Algorithms::SassenaFFT, Mantid::Algorithms::Scale, Mantid::Algorithms::ScaleX, Mantid::Algorithms::Segfault, Mantid::Algorithms::SetInstrumentParameter, Mantid::Algorithms::SetUncertainties, Mantid::Algorithms::ShiftLogTime, Mantid::Algorithms::SignalOverError, Mantid::Algorithms::SmoothData, Mantid::Algorithms::SmoothNeighbours, Mantid::Algorithms::SofQWCentre, Mantid::Algorithms::SofQWNormalisedPolygon, Mantid::Algorithms::SofQWPolygon, Mantid::Algorithms::SolidAngle, Mantid::Algorithms::SortEvents, Mantid::Algorithms::SortXAxis, Mantid::Algorithms::SpatialGrouping, Mantid::Algorithms::SphericalAbsorption, Mantid::Algorithms::Stitch, Mantid::Algorithms::Stitch1D, Mantid::Algorithms::Stitch1DMany, Mantid::Algorithms::StripPeaks, Mantid::Algorithms::StripVanadiumPeaks, Mantid::Algorithms::SumEventsByLogValue, Mantid::Algorithms::SumNeighbours, Mantid::Algorithms::SumOverlappingTubes, Mantid::Algorithms::SumRowColumn, Mantid::Algorithms::SumSpectra, Mantid::Algorithms::TOFSANSResolution, Mantid::Algorithms::TOFSANSResolutionByPixel, Mantid::Algorithms::Transpose, Mantid::Algorithms::UnGroupWorkspace, Mantid::Algorithms::UnwrapMonitor, Mantid::Algorithms::UnwrapMonitorsInTOF, Mantid::Algorithms::UnwrapSNS, Mantid::Algorithms::UpdateScriptRepository, Mantid::Algorithms::VesuvioL1ThetaResolution, Mantid::Algorithms::WeightedMean, Mantid::Algorithms::WeightedMeanOfWorkspace, Mantid::Algorithms::WienerSmooth, Mantid::Algorithms::WorkflowAlgorithmRunner, Mantid::Algorithms::XDataConverter, Mantid::Algorithms::XrayAbsorptionCorrection, Mantid::Crystal::AddPeakHKL, Mantid::Crystal::AnvredCorrection, Mantid::Crystal::CalculatePeaksHKL, Mantid::Crystal::CalculateUMatrix, Mantid::Crystal::CentroidPeaks, Mantid::Crystal::ClearUB, Mantid::Crystal::CombinePeaksWorkspaces, Mantid::Crystal::ConvertPeaksWorkspace, Mantid::Crystal::CountReflections, Mantid::Crystal::DiffPeaksWorkspaces, Mantid::Crystal::FilterPeaks, Mantid::Crystal::FindClusterFaces, Mantid::Crystal::FindGoniometerAngles, Mantid::Crystal::FindSXPeaks, Mantid::Crystal::FindUBUsingFFT, Mantid::Crystal::FindUBUsingIndexedPeaks, Mantid::Crystal::FindUBUsingLatticeParameters, Mantid::Crystal::GoniometerAnglesFromPhiRotation, Mantid::Crystal::HasUB, Mantid::Crystal::IndexPeaks, Mantid::Crystal::IndexSXPeaks, Mantid::Crystal::IntegratePeaksHybrid, Mantid::Crystal::IntegratePeaksUsingClusters, Mantid::Crystal::IntegratePeakTimeSlices, Mantid::Crystal::LoadHKL, Mantid::Crystal::LoadIsawPeaks, Mantid::Crystal::LoadIsawSpectrum, Mantid::Crystal::LoadIsawUB, Mantid::Crystal::MaskPeaksWorkspace, Mantid::Crystal::NormaliseVanadium, Mantid::Crystal::OptimizeCrystalPlacement, Mantid::Crystal::OptimizeLatticeForCellType, Mantid::Crystal::PeakIntegration, Mantid::Crystal::PeakIntensityVsRadius, Mantid::Crystal::PeaksInRegion, Mantid::Crystal::PeaksOnSurface, Mantid::Crystal::PredictFractionalPeaks, Mantid::Crystal::PredictPeaks, Mantid::Crystal::PredictSatellitePeaks, Mantid::Crystal::SaveHKL, Mantid::Crystal::SaveIsawPeaks, Mantid::Crystal::SaveIsawUB, Mantid::Crystal::SaveLauenorm, Mantid::Crystal::SCDCalibratePanels, Mantid::Crystal::SCDCalibratePanels2, Mantid::Crystal::SelectCellOfType, Mantid::Crystal::SelectCellWithForm, Mantid::Crystal::SetCrystalLocation, Mantid::Crystal::SetGoniometer, Mantid::Crystal::SetSpecialCoordinates, Mantid::Crystal::SetUB, Mantid::Crystal::ShowPeakHKLOffsets, Mantid::Crystal::ShowPossibleCells, Mantid::Crystal::SortHKL, Mantid::Crystal::SortPeaksWorkspace, Mantid::Crystal::StatisticsOfPeaksWorkspace, Mantid::Crystal::TransformHKL, Mantid::CurveFitting::Algorithms::CalculateChiSquared, Mantid::CurveFitting::Algorithms::CalculateCostFunction, Mantid::CurveFitting::Algorithms::ConvertToYSpace, Mantid::CurveFitting::Algorithms::ConvolveWorkspaces, Mantid::CurveFitting::CrystalFieldEnergies, Mantid::CurveFitting::Algorithms::DoublePulseFit, Mantid::CurveFitting::Algorithms::EstimateFitParameters, Mantid::CurveFitting::Algorithms::EstimatePeakErrors, Mantid::CurveFitting::Algorithms::EvaluateFunction, Mantid::CurveFitting::Algorithms::Fit, Mantid::CurveFitting::Algorithms::Fit1D, Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks, Mantid::CurveFitting::Algorithms::LeBailFit, Mantid::CurveFitting::Algorithms::NormaliseByPeakArea, Mantid::CurveFitting::Algorithms::PawleyFit, Mantid::CurveFitting::Algorithms::PlotPeakByLogValue, Mantid::CurveFitting::Algorithms::ProfileChiSquared1D, Mantid::CurveFitting::Algorithms::QENSFitSimultaneous, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters, Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3, Mantid::CurveFitting::Algorithms::SplineBackground, Mantid::CurveFitting::Algorithms::SplineInterpolation, Mantid::CurveFitting::Algorithms::SplineSmoothing, Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground, Mantid::CurveFitting::Algorithms::VesuvioCalculateMS, Mantid::CurveFitting::Functions::ProcessBackground, Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim, Mantid::DataHandling::ApplyDiffCal, Mantid::DataHandling::CheckMantidVersion, Mantid::DataHandling::CompressEvents, Mantid::DataHandling::CreateChunkingFromInstrument, Mantid::DataHandling::CreatePolarizationEfficiencies, Mantid::DataHandling::CreateSampleShape, Mantid::DataHandling::CreateSimulationWorkspace, Mantid::DataHandling::DefineGaugeVolume, Mantid::DataHandling::DeleteTableRows, Mantid::DataHandling::DetermineChunking, Mantid::DataHandling::DownloadFile, Mantid::DataHandling::DownloadInstrument, Mantid::DataHandling::ExtractMonitorWorkspace, Mantid::DataHandling::ExtractPolarizationEfficiencies, Mantid::DataHandling::FindDetectorsInShape, Mantid::DataHandling::FindDetectorsPar, Mantid::DataHandling::GenerateGroupingPowder, Mantid::DataHandling::GenerateGroupingPowder2, Mantid::DataHandling::GroupDetectors, Mantid::DataHandling::GroupDetectors2, Mantid::DataHandling::ISISJournalGetExperimentRuns, Mantid::DataHandling::JoinISISPolarizationEfficiencies, Mantid::DataHandling::Load, Mantid::DataHandling::LoadAscii, Mantid::DataHandling::LoadAscii2, Mantid::DataHandling::LoadBBY, Mantid::DataHandling::LoadBBY2, Mantid::DataHandling::LoadCalFile, Mantid::DataHandling::LoadCanSAS1D, Mantid::DataHandling::LoadCanSAS1D2, Mantid::DataHandling::LoadCSNSNexus, Mantid::DataHandling::LoadDaveGrp, Mantid::DataHandling::LoadDetectorInfo, Mantid::DataHandling::LoadDetectorsGroupingFile, Mantid::DataHandling::LoadDiffCal, Mantid::DataHandling::LoadDNSEvent, Mantid::DataHandling::LoadEmptyInstrument, Mantid::DataHandling::LoadEMUTar, Mantid::DataHandling::LoadEMUHdf, Mantid::DataHandling::LoadErrorEventsNexus, Mantid::DataHandling::LoadEventAsWorkspace2D, Mantid::DataHandling::LoadEventNexus, Mantid::DataHandling::LoadEventPreNexus2, Mantid::DataHandling::LoadFITS, Mantid::DataHandling::LoadFullprofResolution, Mantid::DataHandling::LoadGSASInstrumentFile, Mantid::DataHandling::LoadGSS, Mantid::DataHandling::LoadHFIRSANS, Mantid::DataHandling::LoadIDFFromNexus, Mantid::DataHandling::LoadILLDiffraction, Mantid::DataHandling::LoadILLIndirect2, Mantid::DataHandling::LoadILLLagrange, Mantid::DataHandling::LoadILLPolarizationFactors, Mantid::DataHandling::LoadILLPolarizedDiffraction, Mantid::DataHandling::LoadILLReflectometry, Mantid::DataHandling::LoadILLSALSA, Mantid::DataHandling::LoadILLSANS, Mantid::DataHandling::LoadILLTOF2, Mantid::DataHandling::LoadILLTOF3, Mantid::DataHandling::LoadInstrument, Mantid::DataHandling::LoadInstrumentFromRaw, Mantid::DataHandling::LoadIsawDetCal, Mantid::DataHandling::LoadISISNexus2, Mantid::DataHandling::LoadISISPolarizationEfficiencies, Mantid::DataHandling::LoadLog, Mantid::DataHandling::LoadMappingTable, Mantid::DataHandling::LoadMask, Mantid::DataHandling::LoadMcStas, Mantid::DataHandling::LoadMcStasNexus, Mantid::DataHandling::LoadMLZ, Mantid::DataHandling::LoadMuonNexusV2, Mantid::DataHandling::LoadNexus, Mantid::DataHandling::LoadNexusLogs, Mantid::DataHandling::LoadNexusMonitors2, Mantid::DataHandling::LoadNexusProcessed, Mantid::DataHandling::LoadNexusProcessed2, Mantid::DataHandling::LoadNGEM, Mantid::DataHandling::NXcanSAS::LoadNXcanSAS, Mantid::DataHandling::LoadNXSPE, Mantid::DataHandling::LoadParameterFile, Mantid::DataHandling::LoadPDFgetNFile, Mantid::DataHandling::LoadPLN, Mantid::DataHandling::LoadPreNexus, Mantid::DataHandling::LoadPreNexusMonitors, Mantid::DataHandling::LoadPSIMuonBin, Mantid::DataHandling::LoadQKK, Mantid::DataHandling::LoadRaw3, Mantid::DataHandling::LoadRawBin0, Mantid::DataHandling::LoadRawHelper, Mantid::DataHandling::LoadRawSpectrum0, Mantid::DataHandling::LoadRKH, Mantid::DataHandling::LoadSampleDetailsFromRaw, Mantid::DataHandling::LoadSampleEnvironment, Mantid::DataHandling::LoadSampleShape, Mantid::DataHandling::LoadSassena, Mantid::DataHandling::LoadSESANS, Mantid::DataHandling::LoadSINQFocus, Mantid::DataHandling::LoadSPE, Mantid::DataHandling::LoadSpec, Mantid::DataHandling::LoadSpice2D, Mantid::DataHandling::LoadSpiceAscii, Mantid::DataHandling::LoadSpiceXML2DDet, Mantid::DataHandling::LoadSwans, Mantid::DataHandling::LoadTBL, Mantid::DataHandling::LoadTOFRawNexus, Mantid::DataHandling::MaskDetectors, Mantid::DataHandling::MaskDetectorsInShape, Mantid::DataHandling::MaskSpectra, Mantid::DataHandling::ModifyDetectorDotDatFile, Mantid::DataHandling::MoveInstrumentComponent, Mantid::DataHandling::PatchBBY, Mantid::DataHandling::PDLoadCharacterizations, Mantid::DataHandling::RawFileInfo, Mantid::DataHandling::RemoveLogs, Mantid::DataHandling::RenameLog, Mantid::DataHandling::RotateInstrumentComponent, Mantid::DataHandling::RotateSampleShape, Mantid::DataHandling::RotateSource, Mantid::DataHandling::SaveAscii, Mantid::DataHandling::SaveAscii2, Mantid::DataHandling::SaveBankScatteringAngles, Mantid::DataHandling::SaveCalFile, Mantid::DataHandling::SaveCanSAS1D, Mantid::DataHandling::SaveCanSAS1D2, Mantid::DataHandling::SaveCSV, Mantid::DataHandling::SaveDaveGrp, Mantid::DataHandling::SaveDetectorsGrouping, Mantid::DataHandling::SaveDiffCal, Mantid::DataHandling::SaveFocusedXYE, Mantid::DataHandling::SaveFullprofResolution, Mantid::DataHandling::SaveGDA, Mantid::DataHandling::SaveGSASInstrumentFile, Mantid::DataHandling::SaveGSS, Mantid::DataHandling::SaveIsawDetCal, Mantid::DataHandling::SaveMask, Mantid::DataHandling::SaveNexus, Mantid::DataHandling::SaveNexusESS, Mantid::DataHandling::SaveNexusGeometry, Mantid::DataHandling::SaveNexusProcessed, Mantid::DataHandling::SaveNISTDAT, Mantid::DataHandling::SaveNXcanSAS, Mantid::DataHandling::SaveNXSPE, Mantid::DataHandling::SaveNXTomo, Mantid::DataHandling::SaveOpenGenieAscii, Mantid::DataHandling::SavePAR, Mantid::DataHandling::SaveParameterFile, Mantid::DataHandling::SavePDFGui, Mantid::DataHandling::SavePHX, Mantid::DataHandling::SavePolarizedNXcanSAS, Mantid::DataHandling::SaveReflectometryAscii, Mantid::DataHandling::SaveRKH, Mantid::DataHandling::SaveRMCProfile, Mantid::DataHandling::SaveSampleEnvironmentAndShape, Mantid::DataHandling::SaveSESANS, Mantid::DataHandling::SaveSPE, Mantid::DataHandling::SaveTBL, Mantid::DataHandling::SaveVTK, Mantid::DataHandling::ScaleInstrumentComponent, Mantid::DataHandling::SetSampleMaterial, Mantid::DataHandling::SetScalingPSD, Mantid::DataHandling::SNSAppendGeometryToNexus, Mantid::DataHandling::SortTableWorkspace, Mantid::DataHandling::UpdateInstrumentFromFile, Mantid::ICat::CatalogDownloadDataFiles, Mantid::ICat::CatalogGetDataFiles, Mantid::ICat::CatalogGetDataSets, Mantid::ICat::CatalogKeepAlive, Mantid::ICat::CatalogListInstruments, Mantid::ICat::CatalogListInvestigationTypes, Mantid::ICat::CatalogLogin, Mantid::ICat::CatalogLogout, Mantid::ICat::CatalogMyDataSearch, Mantid::ICat::CatalogPublish, Mantid::ICat::CatalogSearch, Mantid::MDAlgorithms::AndMD, Mantid::MDAlgorithms::ApplyDetailedBalanceMD, Mantid::MDAlgorithms::BinaryOperationMD, Mantid::MDAlgorithms::BinMD, Mantid::MDAlgorithms::BooleanBinaryOperationMD, Mantid::MDAlgorithms::CalculateCoverageDGS, Mantid::MDAlgorithms::CentroidPeaksMD2, Mantid::MDAlgorithms::ChangeQConvention, Mantid::MDAlgorithms::CloneMDWorkspace, Mantid::MDAlgorithms::CompactMD, Mantid::MDAlgorithms::CompareMDWorkspaces, Mantid::MDAlgorithms::ConvertCWPDMDToSpectra, Mantid::MDAlgorithms::ConvertCWSDExpToMomentum, Mantid::MDAlgorithms::ConvertCWSDMDtoHKL, Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE, Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace, Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace, Mantid::MDAlgorithms::ConvertToDetectorFaceMD, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace2, Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace3, Mantid::MDAlgorithms::ConvertToMD, Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal, Mantid::MDAlgorithms::ConvertToMDMinMaxLocal, Mantid::MDAlgorithms::CreateMDHistoWorkspace, Mantid::MDAlgorithms::CreateMDWorkspace, Mantid::MDAlgorithms::DebyeWallerFactorCorrectionMD, Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD, Mantid::MDAlgorithms::DivideMD, Mantid::MDAlgorithms::EqualToMD, Mantid::MDAlgorithms::EvaluateMDFunction, Mantid::MDAlgorithms::ExponentialMD, Mantid::MDAlgorithms::FakeMDEventData, Mantid::MDAlgorithms::FindPeaksMD, Mantid::MDAlgorithms::FlippingRatioCorrectionMD, Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD, Mantid::MDAlgorithms::GreaterThanMD, Mantid::MDAlgorithms::ImportMDEventWorkspace, Mantid::MDAlgorithms::ImportMDHistoWorkspace, Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep, Mantid::MDAlgorithms::IntegrateEllipsoidsV1, Mantid::MDAlgorithms::IntegrateEllipsoidsV2, Mantid::MDAlgorithms::IntegrateFlux, Mantid::MDAlgorithms::IntegrateMDHistoWorkspace, Mantid::MDAlgorithms::IntegratePeaksCWSD, Mantid::MDAlgorithms::IntegratePeaksMD, Mantid::MDAlgorithms::IntegratePeaksMD2, Mantid::MDAlgorithms::IntegratePeaksMDHKL, Mantid::MDAlgorithms::LessThanMD, Mantid::MDAlgorithms::LoadDNSSCD, Mantid::MDAlgorithms::LoadMD, Mantid::MDAlgorithms::LoadSQW, Mantid::MDAlgorithms::LoadSQW2, Mantid::MDAlgorithms::LogarithmMD, Mantid::MDAlgorithms::MagneticFormFactorCorrectionMD, Mantid::MDAlgorithms::MaskMD, Mantid::MDAlgorithms::MDNorm, Mantid::MDAlgorithms::MDNormDirectSC, Mantid::MDAlgorithms::MDNormSCD, Mantid::MDAlgorithms::MergeMD, Mantid::MDAlgorithms::MergeMDFiles, Mantid::MDAlgorithms::MinusMD, Mantid::MDAlgorithms::MultiplyMD, Mantid::MDAlgorithms::NotMD, Mantid::MDAlgorithms::OrMD, Mantid::MDAlgorithms::PlusMD, Mantid::MDAlgorithms::PolarizationAngleCorrectionMD, Mantid::MDAlgorithms::PowerMD, Mantid::MDAlgorithms::PreprocessDetectorsToMD, Mantid::MDAlgorithms::QueryMDWorkspace, Mantid::MDAlgorithms::RecalculateTrajectoriesExtents, Mantid::MDAlgorithms::ReplicateMD, Mantid::MDAlgorithms::SaveIsawQvector, Mantid::MDAlgorithms::SaveMD, Mantid::MDAlgorithms::SaveMD2, Mantid::MDAlgorithms::SaveZODS, Mantid::MDAlgorithms::SetMDFrame, Mantid::MDAlgorithms::SetMDUsingMask, Mantid::MDAlgorithms::SliceMD, Mantid::MDAlgorithms::SmoothMD, Mantid::MDAlgorithms::SpectralMomentMD, Mantid::MDAlgorithms::ThresholdMD, Mantid::MDAlgorithms::TransformMD, Mantid::MDAlgorithms::TransposeMD, Mantid::MDAlgorithms::UnaryOperationMD, Mantid::MDAlgorithms::WeightedMeanMD, Mantid::MDAlgorithms::XorMD, Mantid::PythonInterface::RunPythonScript, WorkspaceCreationHelper::StubAlgorithm, Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction, Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer, Mantid::WorkflowAlgorithms::DgsDiagnose, Mantid::WorkflowAlgorithms::DgsPreprocessData, Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium, Mantid::WorkflowAlgorithms::DgsRemap, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2, Mantid::WorkflowAlgorithms::EQSANSLoad, Mantid::WorkflowAlgorithms::EQSANSMonitorTOF, Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity, Mantid::WorkflowAlgorithms::EQSANSQ2D, Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction, Mantid::WorkflowAlgorithms::HFIRLoad, Mantid::WorkflowAlgorithms::HFIRSANSNormalise, Mantid::Algorithms::ProcessIndirectFitParameters, Mantid::WorkflowAlgorithms::SANSBeamFinder, Mantid::WorkflowAlgorithms::SANSSensitivityCorrection, Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection, Mantid::WorkflowAlgorithms::SetupEQSANSReduction, Mantid::WorkflowAlgorithms::SetupHFIRReduction, Mantid::WorkflowAlgorithms::StepScan, Mantid::Algorithms::ClearCache, Mantid::Algorithms::CropToComponent, Mantid::DataHandling::SaveFITS, Mantid::DataHandling::SetBeam, Mantid::DataHandling::SetSample, Mantid::API::Algorithm, and Mantid::MDAlgorithms::ConvertToMDParent.
Referenced by export_ialgorithm().
workspaceMethodInputProperty()
virtual const std::string Mantid::API::IAlgorithm::workspaceMethodInputProperty () const pure virtual
Returns the name of the input workspace property used by the calling object.
Implemented in Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::Rebin, Mantid::Algorithms::RenameWorkspace, Mantid::API::Algorithm, and Mantid::DataHandling::MaskDetectors.
Referenced by export_ialgorithm().
workspaceMethodName()
virtual const std::string Mantid::API::IAlgorithm::workspaceMethodName () const pure virtual
Returns a name that will be used when attached as a workspace method. Empty string indicates do not attach
Implemented in Mantid::Algorithms::CloneWorkspace, Mantid::Algorithms::ConvertAxisByFormula, Mantid::Algorithms::ConvertUnits, Mantid::Algorithms::DeleteWorkspace, Mantid::Algorithms::InterpolatingRebin, Mantid::Algorithms::Rebin, Mantid::Algorithms::RebinRagged, Mantid::Algorithms::RenameWorkspace, Mantid::Algorithms::ResampleX, Mantid::API::Algorithm, and Mantid::DataHandling::MaskDetectors.
Referenced by export_ialgorithm().
workspaceMethodOn()
virtual const std::vector< std::string > Mantid::API::IAlgorithm::workspaceMethodOn () const pure virtual
Returns a set of class names that will have the method attached.
Empty list indicates all types
Implemented in Mantid::API::Algorithm.
Referenced by export_ialgorithm().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IAlgorithm.h