Mantid: Mantid::Geometry::MeshObject2D Class Reference
Mantid::Geometry::MeshObject2D Class Reference
MeshObject2D :
#include <MeshObject2D.h>
Classes
struct PlaneParameters
Public Member Functions
MeshObject2D * clone () const override
MeshObject2D * cloneWithMaterial (const Kernel::Material &material) const override
double distance (const Geometry::Track &ut) const override
Compute the distance to the first point of intersection with the mesh.
double distanceToPlane (const Kernel::V3D &point) const
void draw () const override
boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const BoundingBox &activeRegion, const size_t) const override
boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const size_t) const override
const BoundingBox & getBoundingBox () const override
Returns an axis-aligned bounding box that will fit the shape.
void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) const override
Calculate (or return cached value of) Axis Aligned Bounding box (DEPRECATED)
std::shared_ptr< GeometryHandler > getGeometryHandler () const override
int getName () const override
void GetObjectGeom (detail::ShapeInfo::GeometryShape &type, std::vector< Kernel::V3D > &vectors, double &innerRadius, double &radius, double &height) const override
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
std::vector< uint32_t > getTriangles () const
std::vector< double > getVertices () const
bool hasValidShape () const override
const std::string & id () const override
void initDraw () const override
int interceptSurface (Geometry::Track &ut) const override
Given a track, fill the track with valid section.
bool isOnSide (const Kernel::V3D &) const override
Determine if point is on the side of the object.
bool isValid (const Kernel::V3D &point) const override
Check if a point is inside.
const Kernel::Material & material () const override
MeshObject2D (std::vector< uint32_t > &&faces, std::vector< Kernel::V3D > &&vertices, const Kernel::Material &&material)
Constructor.
MeshObject2D (std::vector< uint32_t > faces, std::vector< Kernel::V3D > vertices, const Kernel::Material &material)
Constructor.
size_t numberOfTriangles () const
size_t numberOfVertices () const
bool operator== (const MeshObject2D &other) const
void setID (const std::string &id) override
virtual void setMaterial (const Kernel::Material &material) override
detail::ShapeInfo::GeometryShape shape () const override
const detail::ShapeInfo & shapeInfo () const override
double solidAngle (const Kernel::V3D &observer) const override
Solid angle only considers triangle facing sample.
double solidAngle (const Kernel::V3D &observer, const Kernel::V3D &scaleFactor) const override
double volume () const override
Public Member Functions inherited from Mantid::Geometry::IObject
virtual IObject * clone () const =0
virtual IObject * cloneWithMaterial (const Kernel::Material &material) const =0
virtual double distance (const Geometry::Track &) const =0
virtual void draw () const =0
virtual boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const BoundingBox &activeRegion, const size_t) const =0
virtual boost::optional< Kernel::V3D > generatePointInObject (Kernel::PseudoRandomNumberGenerator &rng, const size_t) const =0
virtual const BoundingBox & getBoundingBox () const =0
Return cached value of axis-aligned bounding box.
virtual void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) const =0
Calculate (or return cached value of) Axis Aligned Bounding box (DEPRECATED)
virtual std::shared_ptr< GeometryHandler > getGeometryHandler () const =0
virtual int getName () const =0
virtual void GetObjectGeom (detail::ShapeInfo::GeometryShape &type, std::vector< Kernel::V3D > &vectors, double &innerRadius, double &radius, double &height) const =0
virtual int getPointInObject (Kernel::V3D &point) const =0
virtual bool hasValidShape () const =0
virtual const std::string & id () const =0
virtual void initDraw () const =0
virtual int interceptSurface (Geometry::Track &) const =0
virtual bool isFiniteGeometry () const
virtual bool isOnSide (const Kernel::V3D &) const =0
virtual bool isValid (const Kernel::V3D &) const =0
virtual const Kernel::Material & material () const =0
virtual void setFiniteGeometryFlag (bool)
virtual void setID (const std::string &id)=0
virtual void setMaterial (const Kernel::Material &material)=0
virtual detail::ShapeInfo::GeometryShape shape () const =0
virtual const detail::ShapeInfo & shapeInfo () const =0
virtual double solidAngle (const Kernel::V3D &observer) const =0
virtual double solidAngle (const Kernel::V3D &observer, const Kernel::V3D &scaleFactor) const =0
virtual double volume () const =0
virtual ~IObject ()=default
Static Public Member Functions
static bool pointsCoplanar (const std::vector< Kernel::V3D > &vertices)
Estalish if points are coplanar.
Static Public Attributes
static const std::string Id = "MeshObject2D"
Id as static.
static const double MinThickness = 0.001
Private Member Functions
void initialize ()
Common initialization.
Private Attributes
BoundingBox m_boundingBox
Bounding box.
std::shared_ptr< GeometryHandler > m_handler
Geometry Handle for rendering.
std::string m_id
optional string identifier
Kernel::Material m_material
Material composition.
struct Mantid::Geometry::MeshObject2D::PlaneParameters m_planeParameters
std::vector< uint32_t > m_triangles
Triangles are specified by indices into a list of vertices.
std::vector< Kernel::V3D > m_vertices
Vertices.
Detailed Description
MeshObject2D :
Defines an IObject implemented as a 2D mesh composed of triangles. Avoids assumptions made in MeshObject to do with closed surfaces, non-zero volumes and assoicated additional runtime costs. The number of vertices is limited to 2^16 based on index type.
Definition at line 30 of file MeshObject2D.h.
Constructor & Destructor Documentation
MeshObject2D() [1/2]
Mantid::Geometry::MeshObject2D::MeshObject2D (std::vector< uint32_t > faces, std::vector< Kernel::V3D > vertices, const Kernel::Material & material)
Constructor.
Definition at line 147 of file MeshObject2D.cpp.
References initialize().
MeshObject2D() [2/2]
Mantid::Geometry::MeshObject2D::MeshObject2D (std::vector< uint32_t > && faces, std::vector< Kernel::V3D > && vertices, const Kernel::Material && material)
Constructor.
Move constructor.
Definition at line 156 of file MeshObject2D.cpp.
References initialize().
Member Function Documentation
clone()
MeshObject2D * Mantid::Geometry::MeshObject2D::clone () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 281 of file MeshObject2D.cpp.
References m_material, m_triangles, and m_vertices.
cloneWithMaterial()
MeshObject2D * Mantid::Geometry::MeshObject2D::cloneWithMaterial (const Kernel::Material & material) const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 285 of file MeshObject2D.cpp.
References m_triangles, and m_vertices.
distance()
double Mantid::Geometry::MeshObject2D::distance (const Geometry::Track & ut) const override virtual
Compute the distance to the first point of intersection with the mesh.
Parameters
ut Track defining start/direction
Returns
The distance to the object
Exceptions
std::runtime_error if no intersection was found
Implements Mantid::Geometry::IObject.
Definition at line 257 of file MeshObject2D.cpp.
References Mantid::Geometry::Track::direction(), Mantid::Geometry::intersection(), m_planeParameters, m_vertices, Mantid::Geometry::MeshObject2D::PlaneParameters::normal, Mantid::Geometry::MeshObject2D::PlaneParameters::p0, Mantid::Geometry::MeshObjectCommon::rayIntersectsTriangle(), Mantid::Kernel::V3D::scalar_prod(), and Mantid::Geometry::Track::startPoint().
distanceToPlane()
double Mantid::Geometry::MeshObject2D::distanceToPlane (const Kernel::V3D & point) const
Definition at line 187 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObject2D::PlaneParameters::a, Mantid::Geometry::MeshObject2D::PlaneParameters::b, Mantid::Geometry::MeshObject2D::PlaneParameters::c, Mantid::Geometry::MeshObject2D::PlaneParameters::k, m_planeParameters, Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by isValid().
draw()
void Mantid::Geometry::MeshObject2D::draw () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 413 of file MeshObject2D.cpp.
References m_handler.
generatePointInObject() [1/2]
boost::optional< Kernel::V3D > Mantid::Geometry::MeshObject2D::generatePointInObject (Kernel::PseudoRandomNumberGenerator & rng, const BoundingBox & activeRegion, const size_t) const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 370 of file MeshObject2D.cpp.
generatePointInObject() [2/2]
boost::optional< Kernel::V3D > Mantid::Geometry::MeshObject2D::generatePointInObject (Kernel::PseudoRandomNumberGenerator & rng, const size_t) const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 362 of file MeshObject2D.cpp.
getBoundingBox() [1/2]
const BoundingBox & Mantid::Geometry::MeshObject2D::getBoundingBox () const override virtual
Returns an axis-aligned bounding box that will fit the shape.
This is not threadsafe
Returns
A reference to a bounding box for this shape.
Implements Mantid::Geometry::IObject.
Definition at line 346 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObjectCommon::getBoundingBox(), m_boundingBox, and m_vertices.
getBoundingBox() [2/2]
void Mantid::Geometry::MeshObject2D::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) const override virtual
Calculate (or return cached value of) Axis Aligned Bounding box (DEPRECATED)
Implements Mantid::Geometry::IObject.
Definition at line 350 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObjectCommon::getBoundingBox(), m_boundingBox, and m_vertices.
getGeometryHandler()
std::shared_ptr< GeometryHandler > Mantid::Geometry::MeshObject2D::getGeometryHandler () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 389 of file MeshObject2D.cpp.
References m_handler.
getName()
int Mantid::Geometry::MeshObject2D::getName () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 289 of file MeshObject2D.cpp.
GetObjectGeom()
void Mantid::Geometry::MeshObject2D::GetObjectGeom (detail::ShapeInfo::GeometryShape & type, std::vector< Kernel::V3D > & vectors, double & innerRadius, double & radius, double & height) const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 408 of file MeshObject2D.cpp.
getPointInObject()
int Mantid::Geometry::MeshObject2D::getPointInObject (Kernel::V3D & point) const override virtual
Try to find a point that lies within (or on) the object.
Parameters
[out] point :: on exit set to the point value, if found
Returns
1 if point found, 0 otherwise
Implements Mantid::Geometry::IObject.
Definition at line 360 of file MeshObject2D.cpp.
References isValid().
getTriangles()
std::vector< uint32_t > Mantid::Geometry::MeshObject2D::getTriangles () const
Definition at line 397 of file MeshObject2D.cpp.
References m_triangles.
getVertices()
std::vector< double > Mantid::Geometry::MeshObject2D::getVertices () const
Definition at line 395 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObjectCommon::getVertices(), and m_vertices.
hasValidShape()
bool Mantid::Geometry::MeshObject2D::hasValidShape () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 182 of file MeshObject2D.cpp.
References m_triangles, and m_vertices.
id()
const std::string & Mantid::Geometry::MeshObject2D::id () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 387 of file MeshObject2D.cpp.
References Id.
initDraw()
void Mantid::Geometry::MeshObject2D::initDraw () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 420 of file MeshObject2D.cpp.
References m_handler.
initialize()
void Mantid::Geometry::MeshObject2D::initialize () private
Common initialization.
Definition at line 165 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObject2D::PlaneParameters::a, Mantid::Geometry::MeshObject2D::PlaneParameters::abs_normal, Mantid::Geometry::MeshObject2D::PlaneParameters::b, Mantid::Geometry::MeshObject2D::PlaneParameters::c, Mantid::Geometry::MeshObjectCommon::checkVertexLimit(), Mantid::Geometry::MeshObject2D::PlaneParameters::k, m_handler, m_planeParameters, m_vertices, Mantid::Kernel::V3D::norm(), Mantid::Geometry::MeshObject2D::PlaneParameters::normal, Mantid::Geometry::MeshObject2D::PlaneParameters::p0, Mantid::Geometry::CoplanarChecks::validatePointsCoplanar(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by MeshObject2D().
interceptSurface()
int Mantid::Geometry::MeshObject2D::interceptSurface (Geometry::Track & ut) const override virtual
Given a track, fill the track with valid section.
Parameters
ut :: Initial track
Returns
Number of segments added
Implements Mantid::Geometry::IObject.
Definition at line 225 of file MeshObject2D.cpp.
References Mantid::Geometry::Track::addPoint(), Mantid::Geometry::Track::buildLink(), Mantid::Geometry::Track::count(), Mantid::Geometry::Track::direction(), Mantid::Geometry::intersection(), m_planeParameters, m_vertices, Mantid::Geometry::MeshObject2D::PlaneParameters::normal, Mantid::Geometry::MeshObject2D::PlaneParameters::p0, Mantid::Geometry::MeshObjectCommon::rayIntersectsTriangle(), Mantid::Kernel::V3D::scalar_prod(), and Mantid::Geometry::Track::startPoint().
isOnSide()
bool Mantid::Geometry::MeshObject2D::isOnSide (const Kernel::V3D & point) const override virtual
Determine if point is on the side of the object.
Parameters
point : Point to test
Returns
: True if the point is on the side
Implements Mantid::Geometry::IObject.
Definition at line 218 of file MeshObject2D.cpp.
References isValid().
isValid()
bool Mantid::Geometry::MeshObject2D::isValid (const Kernel::V3D & point) const override virtual
Check if a point is inside.
Check that the point is on the plane AND that it is inside or on.
MeshObject2D::isOnSide one of the triangles that defines the plane. Both must be true.
Parameters
point : Point to test
Returns
: True only if the point is valid
Implements Mantid::Geometry::IObject.
Definition at line 199 of file MeshObject2D.cpp.
References distanceToPlane(), Mantid::Geometry::MeshObjectCommon::isOnTriangle(), m_triangles, m_vertices, and tolerance.
Referenced by getPointInObject(), and isOnSide().
material()
const Kernel::Material & Mantid::Geometry::MeshObject2D::material () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 380 of file MeshObject2D.cpp.
References m_material.
Referenced by setMaterial().
numberOfTriangles()
size_t Mantid::Geometry::MeshObject2D::numberOfTriangles () const
Definition at line 393 of file MeshObject2D.cpp.
References m_triangles.
numberOfVertices()
size_t Mantid::Geometry::MeshObject2D::numberOfVertices () const
Definition at line 391 of file MeshObject2D.cpp.
References m_vertices.
operator==()
bool Mantid::Geometry::MeshObject2D::operator== (const MeshObject2D & other) const
Definition at line 328 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObject2D::PlaneParameters::a, Mantid::Geometry::MeshObject2D::PlaneParameters::b, Mantid::Geometry::MeshObject2D::PlaneParameters::c, Mantid::Geometry::MeshObject2D::PlaneParameters::k, m_material, m_planeParameters, m_triangles, m_vertices, Mantid::Kernel::Material::name(), and Mantid::Geometry::MeshObject2D::PlaneParameters::p0.
pointsCoplanar()
bool Mantid::Geometry::MeshObject2D::pointsCoplanar (const std::vector< Kernel::V3D > & vertices) static
Estalish if points are coplanar.
Parameters
vertices : All vertices to consider
Returns
: Return True only if all coplanar
Definition at line 130 of file MeshObject2D.cpp.
References Mantid::Geometry::CoplanarChecks::allCoplanar(), Mantid::Kernel::V3D::norm2(), Mantid::Geometry::CoplanarChecks::sufficientPoints(), and Mantid::Geometry::CoplanarChecks::surfaceNormal().
setID()
void Mantid::Geometry::MeshObject2D::setID (const std::string & id) inline override virtual
Implements Mantid::Geometry::IObject.
Definition at line 73 of file MeshObject2D.h.
setMaterial()
void Mantid::Geometry::MeshObject2D::setMaterial (const Kernel::Material & material) override virtual
Parameters
material :: material that is being set for the object
Implements Mantid::Geometry::IObject.
Definition at line 385 of file MeshObject2D.cpp.
References m_material, and material().
shape()
detail::ShapeInfo::GeometryShape Mantid::Geometry::MeshObject2D::shape () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 399 of file MeshObject2D.cpp.
References Mantid::Geometry::detail::ShapeInfo::NOSHAPE.
shapeInfo()
const detail::ShapeInfo & Mantid::Geometry::MeshObject2D::shapeInfo () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 404 of file MeshObject2D.cpp.
solidAngle() [1/2]
double Mantid::Geometry::MeshObject2D::solidAngle (const Kernel::V3D & observer) const override virtual
Solid angle only considers triangle facing sample.
Back faces do NOT contribute.
This is tantamount to defining an object that is opaque to neutrons. Note that it is still possible to define a facing surface which is obscured by another. In that case there would still be a solid angle contribution as there is no way of detecting the shadowing.
Parameters
observer
Returns
Implements Mantid::Geometry::IObject.
Definition at line 307 of file MeshObject2D.cpp.
References Mantid::Geometry::MeshObjectCommon::getTriangleSolidAngle(), m_triangles, and m_vertices.
Referenced by solidAngle().
solidAngle() [2/2]
double Mantid::Geometry::MeshObject2D::solidAngle (const Kernel::V3D & observer, const Kernel::V3D & scaleFactor) const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 319 of file MeshObject2D.cpp.
References m_material, m_triangles, m_vertices, and solidAngle().
volume()
double Mantid::Geometry::MeshObject2D::volume () const override virtual
Implements Mantid::Geometry::IObject.
Definition at line 335 of file MeshObject2D.cpp.
Member Data Documentation
Id
const std::string Mantid::Geometry::MeshObject2D::Id = "MeshObject2D" static
Id as static.
Definition at line 76 of file MeshObject2D.h.
Referenced by id().
m_boundingBox
BoundingBox Mantid::Geometry::MeshObject2D::m_boundingBox mutable private
Bounding box.
Definition at line 104 of file MeshObject2D.h.
Referenced by getBoundingBox().
m_handler
std::shared_ptr<GeometryHandler> Mantid::Geometry::MeshObject2D::m_handler private
Geometry Handle for rendering.
Definition at line 106 of file MeshObject2D.h.
Referenced by draw(), getGeometryHandler(), initDraw(), and initialize().
m_id
std::string Mantid::Geometry::MeshObject2D::m_id private
optional string identifier
Definition at line 100 of file MeshObject2D.h.
m_material
Kernel::Material Mantid::Geometry::MeshObject2D::m_material private
Material composition.
Definition at line 102 of file MeshObject2D.h.
Referenced by clone(), material(), operator==(), setMaterial(), and solidAngle().
m_planeParameters
struct Mantid::Geometry::MeshObject2D::PlaneParameters Mantid::Geometry::MeshObject2D::m_planeParameters private
Referenced by distance(), distanceToPlane(), initialize(), interceptSurface(), and operator==().
m_triangles
std::vector<uint32_t> Mantid::Geometry::MeshObject2D::m_triangles private
Triangles are specified by indices into a list of vertices.
Offset is always 3.
Definition at line 96 of file MeshObject2D.h.
Referenced by clone(), cloneWithMaterial(), getTriangles(), hasValidShape(), isValid(), numberOfTriangles(), operator==(), and solidAngle().
m_vertices
std::vector<Kernel::V3D> Mantid::Geometry::MeshObject2D::m_vertices private
Vertices.
Definition at line 98 of file MeshObject2D.h.
Referenced by clone(), cloneWithMaterial(), distance(), getBoundingBox(), getVertices(), hasValidShape(), initialize(), interceptSurface(), isValid(), numberOfVertices(), operator==(), and solidAngle().
MinThickness
const double Mantid::Geometry::MeshObject2D::MinThickness = 0.001 static
Definition at line 54 of file MeshObject2D.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Objects/MeshObject2D.h
Framework/Geometry/src/Objects/MeshObject2D.cpp