Mantid: Mantid::Geometry::InfoIteratorBase< T, InfoItem > Class Template Reference
Mantid::Geometry::InfoIteratorBase< T, InfoItem > Class Template Reference
InfoIterator.
#include <InfoIteratorBase.h>
Public Member Functions
InfoIteratorBase (T &info, const size_t index, const size_t totalSize)
Constructor for base iterator.
Private Member Functions
void advance (int64_t delta)
void decrement ()
InfoItem< T > dereference () const
uint64_t distance_to (const InfoIteratorBase< T, InfoItem > &other) const
bool equal (const InfoIteratorBase< T, InfoItem > &other) const
size_t getIndex () const
void increment ()
void setIndex (const size_t index)
Private Attributes
InfoItem< T > m_item
size_t m_totalSize
Friends
class boost::iterator_core_access
Detailed Description
template<typename T, template< typename > class InfoItem>
class Mantid::Geometry::InfoIteratorBase< T, InfoItem >
InfoIterator.
Base to allow users of the Info objects (DetectorInfo etc) access to data via a random access iterator.
Note that the reference type (InfoItem<T>) causes the iterator to be treated as std::input_iterator for the purposes of many std algorithms such as std::advance. See https://en.cppreference.com/w/cpp/iterator/advance for example
Definition at line 25 of file InfoIteratorBase.h.
Constructor & Destructor Documentation
InfoIteratorBase()
template<typename T , template< typename > class InfoItem> Mantid::Geometry::InfoIteratorBase< T, InfoItem >::InfoIteratorBase (T & info, const size_t index, const size_t totalSize) inline
Constructor for base iterator.
Parameters
info : Info object (T) to provide iterator ontop of.
index : start point of iterator
totalSize : Represents maximum length of info. i.e. total number of items that can be iterated over.
Definition at line 36 of file InfoIteratorBase.h.
References index.
Member Function Documentation
advance()
template<typename T , template< typename > class InfoItem> void Mantid::Geometry::InfoIteratorBase< T, InfoItem >::advance (int64_t delta) inline private
Definition at line 45 of file InfoIteratorBase.h.
References Mantid::Kernel::delta, Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item, and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_totalSize.
decrement()
template<typename T , template< typename > class InfoItem> void Mantid::Geometry::InfoIteratorBase< T, InfoItem >::decrement () inline private
Definition at line 58 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item.
dereference()
template<typename T , template< typename > class InfoItem> InfoItem< T > Mantid::Geometry::InfoIteratorBase< T, InfoItem >::dereference () const inline private
Definition at line 68 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item.
distance_to()
template<typename T , template< typename > class InfoItem> uint64_t Mantid::Geometry::InfoIteratorBase< T, InfoItem >::distance_to (const InfoIteratorBase< T, InfoItem > & other) const inline private
Definition at line 70 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::getIndex().
equal()
template<typename T , template< typename > class InfoItem> bool Mantid::Geometry::InfoIteratorBase< T, InfoItem >::equal (const InfoIteratorBase< T, InfoItem > & other) const inline private
Definition at line 50 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::getIndex().
getIndex()
template<typename T , template< typename > class InfoItem> size_t Mantid::Geometry::InfoIteratorBase< T, InfoItem >::getIndex () const inline private
Definition at line 64 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item.
Referenced by Mantid::Geometry::InfoIteratorBase< T, InfoItem >::distance_to(), and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::equal().
increment()
template<typename T , template< typename > class InfoItem> void Mantid::Geometry::InfoIteratorBase< T, InfoItem >::increment () inline private
Definition at line 52 of file InfoIteratorBase.h.
References Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item, and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_totalSize.
setIndex()
template<typename T , template< typename > class InfoItem> void Mantid::Geometry::InfoIteratorBase< T, InfoItem >::setIndex (const size_t index) inline private
Definition at line 66 of file InfoIteratorBase.h.
References index, and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item.
Friends And Related Symbol Documentation
boost::iterator_core_access
template<typename T , template< typename > class InfoItem> friend class boost::iterator_core_access friend
Definition at line 43 of file InfoIteratorBase.h.
Member Data Documentation
m_item
template<typename T , template< typename > class InfoItem> InfoItem<T> Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_item private
Definition at line 74 of file InfoIteratorBase.h.
Referenced by Mantid::Geometry::InfoIteratorBase< T, InfoItem >::advance(), Mantid::Geometry::InfoIteratorBase< T, InfoItem >::decrement(), Mantid::Geometry::InfoIteratorBase< T, InfoItem >::dereference(), Mantid::Geometry::InfoIteratorBase< T, InfoItem >::getIndex(), Mantid::Geometry::InfoIteratorBase< T, InfoItem >::increment(), and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::setIndex().
m_totalSize
template<typename T , template< typename > class InfoItem> size_t Mantid::Geometry::InfoIteratorBase< T, InfoItem >::m_totalSize private
Definition at line 75 of file InfoIteratorBase.h.
Referenced by Mantid::Geometry::InfoIteratorBase< T, InfoItem >::advance(), and Mantid::Geometry::InfoIteratorBase< T, InfoItem >::increment().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Instrument/InfoIteratorBase.h