Mantid: Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer Class Reference
Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer Class Reference
Implementing Levenberg-Marquardt algorithm.
#include <LevenbergMarquardtMDMinimizer.h>
Public Member Functions
double costFunctionVal () override
Return current value of the cost function.
void initialize (API::ICostFunction_sptr function, size_t maxIterations=0) override
Initialize minimizer, i.e. pass a function to minimize.
bool iterate (size_t iteration) override
Do one iteration.
LevenbergMarquardtMDMinimizer ()
Constructor.
std::string name () const override
Name of the minimizer.
Public Member Functions inherited from Mantid::API::IFuncMinimizer
virtual void finalize ()
Finalize minimization, eg store additional outputs.
virtual std::string getError () const
Get the error string.
virtual bool minimize (size_t maxIterations=1000)
Perform iteration with minimizer and return true if successful.
Public Member Functions inherited from Mantid::Kernel::PropertyManager
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
void clear () override final
Clears the whole property map.
PropertyManager * cloneInTimeROI (const Kernel::TimeROI &timeROI)
Create a partial copy of this object such that every time series property is cloned according to the input TimeROI.
void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add or replace a property in the list of managed properties.
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
void declareProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
void filterByProperty (Mantid::Kernel::LogFilter *logFilter, const std::vector< std::string > &excludedFromFiltering=std::vector< std::string >()) override
Filter the managed properties by the given boolean property mask.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
const std::vector< Property * > & getProperties () const override
Get the list of managed properties.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
bool operator!= (const PropertyManager &other) const
PropertyManager & operator+= (const PropertyManager &rhs)
Addition operator.
PropertyManager & operator= (const PropertyManager &)
Assignment operator - performs a deep copy.
bool operator== (const PropertyManager &other) const
size_t propertyCount () const override
Count the number of properties under management.
PropertyManager ()
Default constructor.
PropertyManager (const PropertyManager &)
copy constructor
void removeDataOutsideTimeROI (const Kernel::TimeROI &timeROI)
For time series properties, remove time values outside of TimeROI regions, each defined as [roi_begin,roi_end].
void removeProperty (const std::string &name, const bool delproperty=true) override
removes the property from properties map
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by a json value collection.
void setProperties (const ::Json::Value &jsonValue, IPropertyManager *targetPropertyManager, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)
Set the ordered list of properties by a json value collection.
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const std::string &propertiesJson, IPropertyManager *targetPropertyManager, const std::unordered_set< std::string > &ignoreProperties, bool createMissing=false)
Set the ordered list of properties by one string of values, separated by semicolons.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value.
std::unique_ptr< Property > takeProperty (const size_t index) override
removes the property from the properties map and returns a pointer to it
bool validateProperties () const override
Validates all the properties in the collection.
virtual ~PropertyManager () override
Virtual destructor.
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Attributes
std::shared_ptr< CostFunctions::CostFuncFitting > m_costFunction
Pointer to the cost function.
std::vector< double > m_D
double m_F
To keep function value.
double m_mu
The damping mu parameter in the Levenberg-Marquardt method.
double m_nu
The nu parameter in the Levenberg-Marquardt method.
double m_rho
The rho parameter in the Levenberg-Marquardt method.
double m_tau
The tau parameter in the Levenberg-Marquardt method.
Additional Inherited Members
Static Public Member Functions inherited from Mantid::Kernel::PropertyManager
static std::string getInvalidValuesFilterLogName (const std::string &logName)
Gets the correct log name for the matching invalid values log for a given log name.
static std::string getLogNameFromInvalidValuesFilter (const std::string &logName)
static bool isAnInvalidValuesFilterLog (const std::string &logName)
Determine if the log's name has a substring indicating it should not be filtered.
Static Public Attributes inherited from Mantid::Kernel::PropertyManager
static const std::string INVALID_VALUES_SUFFIX = "_invalid_values"
Protected Member Functions inherited from Mantid::Kernel::PropertyManager
Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
Property * getPointerToPropertyOrNull (const std::string &name) const
Get a property by name.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Protected Attributes inherited from Mantid::API::IFuncMinimizer
std::string m_errorString
Error string.
Detailed Description
Implementing Levenberg-Marquardt algorithm.
Uses the normal system calculate the corrections to the parameters. Expects a cost function that can evaluate the value, the derivatives and the hessian matrix.
Author
Roman Tolchenov, Tessella plc
Definition at line 30 of file LevenbergMarquardtMDMinimizer.h.
Constructor & Destructor Documentation
LevenbergMarquardtMDMinimizer()
Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::LevenbergMarquardtMDMinimizer ()
Constructor.
Definition at line 33 of file LevenbergMarquardtMDMinimizer.cpp.
Member Function Documentation
costFunctionVal()
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::costFunctionVal () override virtual
Return current value of the cost function.
Implements Mantid::API::IFuncMinimizer.
Definition at line 280 of file LevenbergMarquardtMDMinimizer.cpp.
References m_costFunction.
initialize()
void Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::initialize (API::ICostFunction_sptr function, size_t maxIterations = 0) override virtual
Initialize minimizer, i.e. pass a function to minimize.
Implements Mantid::API::IFuncMinimizer.
Definition at line 43 of file LevenbergMarquardtMDMinimizer.cpp.
References m_costFunction, m_mu, m_nu, and m_rho.
iterate()
bool Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate (size_t iteration) override virtual
Do one iteration.
Implements Mantid::API::IFuncMinimizer.
Definition at line 55 of file LevenbergMarquardtMDMinimizer.cpp.
References Mantid::Geometry::d, Mantid::CurveFitting::EigenVector::dot(), error, fabs, Mantid::API::g_log, Mantid::CurveFitting::EigenVector::get(), Mantid::Kernel::PropertyManager::getProperty(), m_costFunction, m_D, Mantid::API::IFuncMinimizer::m_errorString, m_F, m_mu, m_nu, m_rho, m_tau, n, Mantid::CurveFitting::EigenVector::norm(), Mantid::CurveFitting::EigenVector::set(), tmp, and Mantid::Kernel::Logger::warning().
name()
std::string Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::name () const inline override virtual
Name of the minimizer.
Implements Mantid::API::IFuncMinimizer.
Definition at line 35 of file LevenbergMarquardtMDMinimizer.h.
Member Data Documentation
m_costFunction
std::shared_ptr<CostFunctions::CostFuncFitting> Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_costFunction private
Pointer to the cost function.
Definition at line 46 of file LevenbergMarquardtMDMinimizer.h.
Referenced by costFunctionVal(), initialize(), and iterate().
m_D
std::vector<double> Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_D private
Definition at line 57 of file LevenbergMarquardtMDMinimizer.h.
Referenced by iterate().
m_F
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_F private
To keep function value.
Definition at line 56 of file LevenbergMarquardtMDMinimizer.h.
Referenced by iterate().
m_mu
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_mu private
The damping mu parameter in the Levenberg-Marquardt method.
Definition at line 50 of file LevenbergMarquardtMDMinimizer.h.
Referenced by initialize(), and iterate().
m_nu
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_nu private
The nu parameter in the Levenberg-Marquardt method.
Definition at line 52 of file LevenbergMarquardtMDMinimizer.h.
Referenced by initialize(), and iterate().
m_rho
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_rho private
The rho parameter in the Levenberg-Marquardt method.
Definition at line 54 of file LevenbergMarquardtMDMinimizer.h.
Referenced by initialize(), and iterate().
m_tau
double Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::m_tau private
The tau parameter in the Levenberg-Marquardt method.
Definition at line 48 of file LevenbergMarquardtMDMinimizer.h.
Referenced by iterate().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/FuncMinimizers/LevenbergMarquardtMDMinimizer.h
Framework/CurveFitting/src/FuncMinimizers/LevenbergMarquardtMDMinimizer.cpp