Mantid: Mantid::Geometry::Quadratic Class Reference
Mantid::Geometry::Quadratic Class Reference abstract
Holds a basic quadratic surface.
#include <Quadratic.h>
Public Member Functions
void acceptVisitor (BaseVisit &A) const override
Accept visitor for line calculation.
std::string className () const override
Effective typeid.
std::unique_ptr< Quadratic > clone () const
const std::vector< double > & copyBaseEqn () const
access BaseEquation vector
void displace (const Kernel::V3D &) override
Apply a general displacement to the surface.
double distance (const Kernel::V3D &) const override
distance between point and surface (approx)
double eqnValue (const Kernel::V3D &) const
Helper function to calcuate the value of the equation at a fixed point.
bool onSurface (const Kernel::V3D &) const override
is point valid on surface
void print () const override
Print out the genreal equation for debugging.
Quadratic ()
Constructor.
void rotate (const Kernel::Matrix< double > &) override
Rotate the surface by matrix MX.
virtual void setBaseEqn ()=0
Abstract set baseEqn.
int side (const Kernel::V3D &) const override
Determine if the the Point is true to the surface or on the other side.
Kernel::V3D surfaceNormal (const Kernel::V3D &) const override
Normal at surface.
void write (std::ostream &) const override
Writes out an MCNPX surface description Note : Swap since base equation is swapped in gq output (mcnp 4c manual pg.
Public Member Functions inherited from Mantid::Geometry::Surface
virtual void acceptVisitor (BaseVisit &A) const
Accept visitor for line calculation.
virtual std::string className () const
Effective typeid.
std::unique_ptr< Surface > clone () const
virtual void displace (const Kernel::V3D &)=0
translates the surface
virtual double distance (const Kernel::V3D &) const =0
returns the minimum distance to the surface
virtual void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin)=0
bounding box for the surface
int getName () const
Get Name.
virtual bool onSurface (const Kernel::V3D &R) const =0
is point valid on surface
Surface & operator= (const Surface &)=delete
virtual void print () const
Simple print out function for surface header.
virtual void rotate (const Kernel::Matrix< double > &)=0
rotates the surface
void setName (int const N)
Set Name.
virtual int setSurface (const std::string &R)=0
Sets the surface based on a string input in MCNPX format.
virtual int side (const Kernel::V3D &) const
Surface side : throw AbsObjMethod.
Surface ()
Constructor.
virtual Kernel::V3D surfaceNormal (const Kernel::V3D &) const =0
returns the normal to the closest point on the surface
virtual void write (std::ostream &) const
The writes the data to the output stream.
void writeHeader (std::ostream &) const
Writes out the start of an MCNPX surface description .
virtual ~Surface ()=default
Static Public Attributes
static const int Nprecision = 10
Precision of the output.
Static Public Attributes inherited from Mantid::Geometry::Surface
static const int Nprecision = 10
Precision of the output.
Protected Member Functions
Quadratic & operator= (const Quadratic &)=delete
Quadratic (const Quadratic &)=default
Protected Member Functions inherited from Mantid::Geometry::Surface
Surface (const Surface &)=default
Protected Attributes
std::vector< double > BaseEqn
Base equation (as a 10 point vector)
Private Member Functions
Quadratic * doClone () const override=0
Abstract clone function.
void matrixForm (Kernel::Matrix< double > &, Kernel::V3D &, double &) const
Converts the baseEqn into the matrix form such that.
Detailed Description
Holds a basic quadratic surface.
Author
S. Ansell
Date
April 2004
Version
1.0
Holds a basic surface with equation form
\[ Ax^2+By^2+Cz^2+Dxy+Exz+Fyz+Gx+Hy+Jz+K=0 \]
Definition at line 29 of file Quadratic.h.
Constructor & Destructor Documentation
Quadratic() [1/2]
Mantid::Geometry::Quadratic::Quadratic (const Quadratic &) protected default
Quadratic() [2/2]
Mantid::Geometry::Quadratic::Quadratic ()
Constructor.
Definition at line 38 of file Quadratic.cpp.
Member Function Documentation
acceptVisitor()
void Mantid::Geometry::Quadratic::acceptVisitor (BaseVisit & A) const inline override virtual
Accept visitor for line calculation.
Reimplemented from Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 46 of file Quadratic.h.
References Mantid::Geometry::BaseVisit::Accept().
className()
std::string Mantid::Geometry::Quadratic::className () const inline override virtual
Effective typeid.
Reimplemented from Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 49 of file Quadratic.h.
clone()
std::unique_ptr< Quadratic > Mantid::Geometry::Quadratic::clone () const
Definition at line 331 of file Quadratic.cpp.
References doClone().
copyBaseEqn()
const std::vector< double > & Mantid::Geometry::Quadratic::copyBaseEqn () const inline
access BaseEquation vector
Definition at line 51 of file Quadratic.h.
displace()
void Mantid::Geometry::Quadratic::displace (const Kernel::V3D & Pt) override virtual
Apply a general displacement to the surface.
Parameters
Pt :: Point to add to surface coordinate
Implements Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 244 of file Quadratic.cpp.
References BaseEqn.
Referenced by Mantid::Geometry::Cylinder::displace(), Mantid::Geometry::Plane::displace(), and Mantid::Geometry::Sphere::displace().
distance()
double Mantid::Geometry::Quadratic::distance (const Kernel::V3D & Pt) const override virtual
distance between point and surface (approx)
Proper calcuation of a point to a general surface.
Parameters
Pt :: Point to calculate distance from surace
Returns
distance from point to surface (signed)
Implements Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 123 of file Quadratic.cpp.
References Mantid::Kernel::Matrix< T >::Diagonalise(), Mantid::Kernel::V3D::distance(), Mantid::mathLevel::PolyBase::realRoots(), Mantid::Kernel::Tolerance, and Mantid::Kernel::Matrix< T >::Tprime().
doClone()
Quadratic * Mantid::Geometry::Quadratic::doClone () const override private pure virtual
Abstract clone function.
Implements Mantid::Geometry::Surface.
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::General, Mantid::Geometry::Plane, and Mantid::Geometry::Sphere.
Referenced by clone().
eqnValue()
double Mantid::Geometry::Quadratic::eqnValue (const Kernel::V3D & Pt) const
Helper function to calcuate the value of the equation at a fixed point.
Parameters
Pt :: Point to determine the equation surface value at
Returns
value Eqn(Pt) : -ve inside +ve outside
Definition at line 45 of file Quadratic.cpp.
matrixForm()
void Mantid::Geometry::Quadratic::matrixForm (Kernel::Matrix< double > & A, Kernel::V3D & B, double & C) const private
Converts the baseEqn into the matrix form such that.
\[ x^T A x + B^T x + C =0 \]
Parameters
A :: Matrix to place equation into
B :: Vector point
C :: Constant value
Definition at line 101 of file Quadratic.cpp.
onSurface()
bool Mantid::Geometry::Quadratic::onSurface (const Kernel::V3D & Pt) const override virtual
is point valid on surface
Test to see if a point is on the surface.
Parameters
Pt :: Point to test
Returns
0 : if not on surface; 1 if on surace
Implements Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 233 of file Quadratic.cpp.
References Mantid::Kernel::Tolerance.
Referenced by Mantid::Geometry::Cylinder::onSurface().
operator=()
Quadratic & Mantid::Geometry::Quadratic::operator= (const Quadratic &) protected delete
print()
void Mantid::Geometry::Quadratic::print () const override virtual
Print out the genreal equation for debugging.
Reimplemented from Mantid::Geometry::Surface.
Definition at line 298 of file Quadratic.cpp.
References BaseEqn, and Mantid::Geometry::Surface::print().
Referenced by Mantid::Geometry::Cylinder::print(), and Mantid::Geometry::Plane::print().
rotate()
void Mantid::Geometry::Quadratic::rotate (const Kernel::Matrix< double > & MX) override virtual
Rotate the surface by matrix MX.
Parameters
MX :: Matrix for rotation (not inverted like MCNPX)
Implements Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 258 of file Quadratic.cpp.
References BaseEqn, Mantid::Geometry::d, and Mantid::Kernel::Matrix< T >::Invert().
Referenced by Mantid::Geometry::Cylinder::rotate(), Mantid::Geometry::Plane::rotate(), and Mantid::Geometry::Sphere::rotate().
setBaseEqn()
virtual void Mantid::Geometry::Quadratic::setBaseEqn () pure virtual
Abstract set baseEqn.
Implemented in Mantid::Geometry::Cone, Mantid::Geometry::Cylinder, Mantid::Geometry::General, Mantid::Geometry::Plane, and Mantid::Geometry::Sphere.
side()
int Mantid::Geometry::Quadratic::side (const Kernel::V3D & Pt) const override virtual
Determine if the the Point is true to the surface or on the other side.
Parameters
Pt :: Point to check
Return values
1 : if the point is "true" to the surface
-1 : if the point is "false" to the surface
0 :: The point is on the surface
Reimplemented from Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 68 of file Quadratic.cpp.
References fabs, and Mantid::Kernel::Tolerance.
Referenced by Mantid::Geometry::Cylinder::side().
surfaceNormal()
Kernel::V3D Mantid::Geometry::Quadratic::surfaceNormal (const Kernel::V3D & Pt) const override virtual
Normal at surface.
Given a point on the surface Calculate the normal at the point Some rather disturbing behaviour happens if the point is a significant distance from the surface.
Parameters
Pt :: Point to calcution
Returns
normal unit vector
Implements Mantid::Geometry::Surface.
Definition at line 84 of file Quadratic.cpp.
References Mantid::Kernel::V3D::normalize().
write()
void Mantid::Geometry::Quadratic::write (std::ostream & OX) const override virtual
Writes out an MCNPX surface description Note : Swap since base equation is swapped in gq output (mcnp 4c manual pg.
3-14)
Parameters
OX :: Output stream (required for multiple std::endl)
Reimplemented from Mantid::Geometry::Surface.
Reimplemented in Mantid::Geometry::Sphere.
Definition at line 310 of file Quadratic.cpp.
References Mantid::Geometry::Surface::Nprecision, and Mantid::Kernel::Strings::writeMCNPX().
Referenced by Mantid::Geometry::Cone::write(), and Mantid::Geometry::Cylinder::write().
Member Data Documentation
BaseEqn
std::vector<double> Mantid::Geometry::Quadratic::BaseEqn protected
Base equation (as a 10 point vector)
Definition at line 35 of file Quadratic.h.
Referenced by displace(), print(), rotate(), Mantid::Geometry::Cone::setBaseEqn(), Mantid::Geometry::Cylinder::setBaseEqn(), Mantid::Geometry::Plane::setBaseEqn(), Mantid::Geometry::Sphere::setBaseEqn(), and Mantid::Geometry::General::setSurface().
Nprecision
const int Mantid::Geometry::Quadratic::Nprecision = 10 static
Precision of the output.
Definition at line 40 of file Quadratic.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Surfaces/Quadratic.h
Framework/Geometry/src/Surfaces/Quadratic.cpp