Mantid: Mantid::API::TempJacobian Class Reference
Mantid::API::TempJacobian Class Reference
#include <IPeakFunction.h>
Public Member Functions
double get (size_t iY, size_t iP) override
Get the value to a Jacobian matrix element.
size_t maxParam (size_t iY)
void set (size_t iY, size_t iP, double value) override
Set a value to a Jacobian matrix element.
TempJacobian (size_t y, size_t p)
void zero () override
Zero all matrix elements.
Public Member Functions inherited from Mantid::API::Jacobian
virtual ~Jacobian ()=default
Virtual destructor.
Protected Attributes
std::vector< double > m_J
size_t m_p
size_t m_y
Detailed Description
Definition at line 18 of file IPeakFunction.h.
Constructor & Destructor Documentation
TempJacobian()
Mantid::API::TempJacobian::TempJacobian (size_t y, size_t p) inline
Definition at line 20 of file IPeakFunction.h.
Member Function Documentation
get()
double Mantid::API::TempJacobian::get (size_t iY, size_t iP) inline override virtual
Get the value to a Jacobian matrix element.
Parameters
iY :: The index of a data point.
iP :: The index of a declared parameter.
Implements Mantid::API::Jacobian.
Definition at line 22 of file IPeakFunction.h.
References m_J, and m_p.
Referenced by maxParam().
maxParam()
size_t Mantid::API::TempJacobian::maxParam (size_t iY) inline
Definition at line 23 of file IPeakFunction.h.
References get(), and m_p.
Referenced by Mantid::API::IPeakFunction::getCentreParameterName().
set()
void Mantid::API::TempJacobian::set (size_t iY, size_t iP, double value) inline override virtual
Set a value to a Jacobian matrix element.
Parameters
iY :: The index of a data point.
iP :: The index of a declared parameter.
value :: The derivative value.
Implements Mantid::API::Jacobian.
Definition at line 21 of file IPeakFunction.h.
References m_J, m_p, and value.
zero()
void Mantid::API::TempJacobian::zero () inline override virtual
Zero all matrix elements.
Implements Mantid::API::Jacobian.
Definition at line 36 of file IPeakFunction.h.
References m_J.
Member Data Documentation
m_J
std::vector<double> Mantid::API::TempJacobian::m_J protected
Definition at line 41 of file IPeakFunction.h.
Referenced by get(), set(), and zero().
m_p
size_t Mantid::API::TempJacobian::m_p protected
Definition at line 40 of file IPeakFunction.h.
Referenced by get(), maxParam(), and set().
m_y
size_t Mantid::API::TempJacobian::m_y protected
Definition at line 39 of file IPeakFunction.h.
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IPeakFunction.h