Mantid: ICat4::ns1__shift Class Reference
ICat4::ns1__shift Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__shift ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * comment
time_t * endDate
ns1__investigation * investigation
time_t * startDate
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2147 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__shift()
ICat4::ns1__shift::ns1__shift () inline
Definition at line 2161 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__shift::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9223 of file ICat4C.cpp.
References comment, endDate, investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and startDate.
Referenced by ICat4::soap_in_ns1__shift(), ICat4::soap_new_req_ns1__shift(), and ICat4::soap_new_set_ns1__shift().
soap_get()
void * ICat4::ns1__shift::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9386 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__shift().
soap_in()
void * ICat4::ns1__shift::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9275 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__shift().
Referenced by ICat4::soap_in_ns1__shift().
soap_out()
int ICat4::ns1__shift::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9245 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__shift().
Referenced by soap_put().
soap_put()
int ICat4::ns1__shift::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9379 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__shift.
soap_serialize()
void ICat4::ns1__shift::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9233 of file ICat4C.cpp.
References comment, endDate, investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), and startDate.
Referenced by ICat4::soap_serialize_PointerTons1__sampleParameter().
soap_type()
int ICat4::ns1__shift::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2154 of file ICat4Stub.h.
Member Data Documentation
comment
std::string* ICat4::ns1__shift::comment
Definition at line 2149 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
endDate
time_t* ICat4::ns1__shift::endDate
Definition at line 2150 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
investigation
ns1__investigation* ICat4::ns1__shift::investigation
Definition at line 2151 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
startDate
time_t* ICat4::ns1__shift::startDate
Definition at line 2152 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp