Mantid: Mantid::PythonInterface::PropertyWithValueExporter< HeldType, ValueReturnPolicy > Struct Template Reference
Mantid::PythonInterface::PropertyWithValueExporter< HeldType, ValueReturnPolicy > Struct Template Reference
A helper struct to export PropertyWithValue<> types to Python.
#include <PropertyWithValueExporter.h>
Static Public Member Functions
static void define (const char *pythonClassName)
Detailed Description
template<typename HeldType, typename ValueReturnPolicy = boost::python::return_by_value>
struct Mantid::PythonInterface::PropertyWithValueExporter< HeldType, ValueReturnPolicy >
A helper struct to export PropertyWithValue<> types to Python.
Definition at line 53 of file PropertyWithValueExporter.h.
Member Function Documentation
define()
template<typename HeldType , typename ValueReturnPolicy = boost::python::return_by_value> static void Mantid::PythonInterface::PropertyWithValueExporter< HeldType, ValueReturnPolicy >::define (const char * pythonClassName) inline static
Definition at line 54 of file PropertyWithValueExporter.h.
References Mantid::Kernel::Direction::Input.
Referenced by Mantid::PythonInterface::WorkspacePropertyExporter< WorkspaceType >::define(), export_AlgorithmProperty(), export_BasicPropertyWithValueTypes(), export_FunctionProperty(), export_MultipleFileProperty(), export_PropertyManagerProperty(), export_PropertyWithValueOptionalBool(), and export_PythonObjectProperty().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/PropertyWithValueExporter.h