Mantid: Mantid::Geometry::SymmetryElementTranslationGenerator Class Reference
Mantid::Geometry::SymmetryElementTranslationGenerator Class Reference
This implementation of AbstractSymmetryElementGenerator produces only translation elements.
#include <SymmetryElementFactory.h>
Public Member Functions
bool canProcess (const SymmetryOperation &operation) const override
Checks that the order of the matrix is 1 and the operation has a translation.
SymmetryElement_sptr generateElement (const SymmetryOperation &operation) const override
Generates an instance of SymmetryElementTranslation with the vector of the operation as translation vector.
Public Member Functions inherited from Mantid::Geometry::AbstractSymmetryElementGenerator
virtual ~AbstractSymmetryElementGenerator ()=default
Detailed Description
This implementation of AbstractSymmetryElementGenerator produces only translation elements.
Definition at line 66 of file SymmetryElementFactory.h.
Member Function Documentation
canProcess()
bool Mantid::Geometry::SymmetryElementTranslationGenerator::canProcess (const SymmetryOperation & operation) const override virtual
Checks that the order of the matrix is 1 and the operation has a translation.
Implements Mantid::Geometry::AbstractSymmetryElementGenerator.
Definition at line 37 of file SymmetryElementFactory.cpp.
References Mantid::Geometry::SymmetryOperation::hasTranslation(), and Mantid::Geometry::SymmetryOperation::order().
generateElement()
SymmetryElement_sptr Mantid::Geometry::SymmetryElementTranslationGenerator::generateElement (const SymmetryOperation & operation) const override virtual
Generates an instance of SymmetryElementTranslation with the vector of the operation as translation vector.
Implements Mantid::Geometry::AbstractSymmetryElementGenerator.
Definition at line 31 of file SymmetryElementFactory.cpp.
References Mantid::Geometry::SymmetryOperation::vector().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/SymmetryElementFactory.h
Framework/Geometry/src/Crystal/SymmetryElementFactory.cpp