Mantid: MantidQt::MantidWidgets::Batch Namespace Reference
MantidQt::MantidWidgets::Batch Namespace Reference
Classes
class BuildSubtreeItems
class Cell
class CellDelegate
class ExtractSubtrees
class FilteredTreeModel
class FindSubtreeRoots
class IJobTreeView
class JobTreeView
class JobTreeViewSignalAdapter
class JobTreeViewSubscriber
class LambdaRowPredicate
class MockJobTreeView
class QModelIndexForFilteredModel
class QModelIndexForMainModel
class QtStandardItemTreeModelAdapter
class QtTreeCursorNavigation
class Row
class RowLocation
class RowLocationAdapter
class RowPredicate
class StrictQModelIndex
Typedefs
using QtTreeCursorNavigationResult = std::pair< bool, QModelIndex >
using RowPath = std::vector< int >
using Subtree = std::vector< Row >
Enumerations
enum CellUserRoles { BorderColor = Qt::UserRole + 1 , BorderThickness , IconFilePath }
Functions
QModelIndex above (QModelIndex const &index)
template<typename RowLocationConstIterator >
bool allNodesDescendedFromParentOfFirstRoot (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
template<typename RowLocationConstIterator >
bool allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected (int subtreeRootDepth, RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
void applyCellPropertiesToItem (Cell const &cell, QStandardItem &item)
bool areOnSameRow (QModelIndex const &a, QModelIndex const &b)
QModelIndex below (QModelIndex const &index)
Cell extractCellPropertiesFromItem (QStandardItem const &item)
QModelIndex firstCellOnRowOf (QModelIndex const &index)
QModelIndexForFilteredModel fromFilteredModel (QModelIndex const &filteredModelIndex, QAbstractItemModel const &model)
QModelIndexForMainModel fromMainModel (QModelIndex const &mainModelIndex, QAbstractItemModel const &model)
std::string getBackgroundColor (QStandardItem const &item)
QColor getBorderColor (QStandardItem const &item)
int getBorderThickness (QStandardItem const &item)
std::string getForegroundColor (QStandardItem const &item)
std::string getIconFilePath (QStandardItem const &item)
bool hasCellOnTheLeft (QModelIndex const &index)
bool hasCellOnTheRight (QModelIndex const &index)
bool hasRowAbove (QModelIndex const &index)
bool hasRowBelow (QModelIndex const &index)
template<typename RowLocationConstIterator >
bool hasSubtreeRootDeeperThanFirstRoot (int firstSubtreeRootDepth, RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
template<typename RowLocationConstIterator >
bool hasSubtreeRootShallowerThanFirstRoot (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
QModelIndex lastChildRowOf (QModelIndex const &index, QAbstractItemModel const &model)
QModelIndex leftOf (QModelIndex const &index)
template<typename Predicate >
std::unique_ptr< RowPredicate > makeFilterFromLambda (Predicate predicate)
template<typename RowLocationConstIterator >
bool maximumIncreaseInDepthIsOne (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
EXPORT_OPT_MANTIDQT_COMMON QStandardItem * modelItemFromIndex (QStandardItemModel &model, QModelIndexForMainModel const &index)
EXPORT_OPT_MANTIDQT_COMMON QStandardItem const * modelItemFromIndex (QStandardItemModel const &model, QModelIndexForMainModel const &index)
EXPORT_OPT_MANTIDQT_COMMON bool operator!= (Cell const &lhs, Cell const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator!= (Row const &lhs, Row const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator< (Row const &lhs, Row const &rhs)
EXPORT_OPT_MANTIDQT_COMMON std::ostream & operator<< (std::ostream &os, Cell const &cell)
EXPORT_OPT_MANTIDQT_COMMON std::ostream & operator<< (std::ostream &os, Row const &location)
EXPORT_OPT_MANTIDQT_COMMON std::ostream & operator<< (std::ostream &os, RowLocation const &location)
EXPORT_OPT_MANTIDQT_COMMON bool operator<= (Row const &lhs, Row const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator== (Cell const &lhs, Cell const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator== (Row const &lhs, Row const &rhs)
template<typename Derived >
bool operator== (StrictQModelIndex< Derived > const &lhs, StrictQModelIndex< Derived > const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator> (Row const &lhs, Row const &rhs)
EXPORT_OPT_MANTIDQT_COMMON bool operator>= (Row const &lhs, Row const &rhs)
EXPORT_OPT_MANTIDQT_COMMON std::vector< Cell > paddedCellsToWidth (std::vector< Cell > const &cells, Cell const &paddingCell, int paddedWidth)
EXPORT_OPT_MANTIDQT_COMMON bool pathsSameUntilDepth (int depth, RowLocation const &locationA, RowLocation const &locationB)
QModelIndex rightOf (QModelIndex const &index)
RowLocation rowToRowLocation (Row const &row)
void setBackgroundColor (QStandardItem &item, std::string const &backgroundColor)
void setBorderColor (QStandardItem &item, std::string const &borderColor, int alpha)
void setBorderThickness (QStandardItem &item, int borderThickness)
void setForegroundColor (QStandardItem &item, std::string const &foregroundColor)
void setIcon (QStandardItem &item, std::string const &iconFilePath)
void setIconFilePath (QStandardItem &item, QString const &iconFilePath)
Typedef Documentation
QtTreeCursorNavigationResult
using MantidQt::MantidWidgets::Batch::QtTreeCursorNavigationResult = typedef std::pair<bool, QModelIndex>
Definition at line 18 of file QtTreeCursorNavigation.h.
RowPath
using MantidQt::MantidWidgets::Batch::RowPath = typedef std::vector<int>
Definition at line 20 of file RowLocation.h.
Subtree
using MantidQt::MantidWidgets::Batch::Subtree = typedef std::vector<Row>
Definition at line 20 of file Subtree.h.
Enumeration Type Documentation
CellUserRoles
enum MantidQt::MantidWidgets::Batch::CellUserRoles
Enumerator
BorderColor
BorderThickness
IconFilePath
Definition at line 20 of file CellStandardItem.h.
Function Documentation
above()
QModelIndex MantidQt::MantidWidgets::Batch::above (QModelIndex const & index)
Definition at line 13 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::editAtRowAbove(), and MantidQt::MantidWidgets::Batch::JobTreeView::siblingIfExistsElseParent().
allNodesDescendedFromParentOfFirstRoot()
template<typename RowLocationConstIterator > bool MantidQt::MantidWidgets::Batch::allNodesDescendedFromParentOfFirstRoot (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
Definition at line 33 of file Subtree.h.
References MantidQt::MantidWidgets::Batch::RowLocation::isDescendantOf().
Referenced by allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected().
allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected()
template<typename RowLocationConstIterator > bool MantidQt::MantidWidgets::Batch::allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected (int subtreeRootDepth, RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
Definition at line 60 of file Subtree.h.
References allNodesDescendedFromParentOfFirstRoot(), hasSubtreeRootDeeperThanFirstRoot(), and maximumIncreaseInDepthIsOne().
Referenced by MantidQt::MantidWidgets::Batch::ExtractSubtrees::operator()(), and MantidQt::MantidWidgets::Batch::FindSubtreeRoots::operator()().
applyCellPropertiesToItem()
void MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem (Cell const & cell, QStandardItem & item)
Definition at line 10 of file CellStandardItem.cpp.
References MantidQt::MantidWidgets::Batch::Cell::backgroundColor(), MantidQt::MantidWidgets::Batch::Cell::borderColor(), MantidQt::MantidWidgets::Batch::Cell::borderOpacity(), MantidQt::MantidWidgets::Batch::Cell::borderThickness(), MantidQt::MantidWidgets::Batch::Cell::contentText(), MantidQt::MantidWidgets::Batch::Cell::foregroundColor(), MantidQt::MantidWidgets::Batch::Cell::iconFilePath(), MantidQt::MantidWidgets::Batch::Cell::isEditable(), setBackgroundColor(), setBorderColor(), setBorderThickness(), setForegroundColor(), setIcon(), and MantidQt::MantidWidgets::Batch::Cell::toolTip().
Referenced by MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::rowItemsFromCells(), and MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellAtCellIndex().
areOnSameRow()
bool MantidQt::MantidWidgets::Batch::areOnSameRow (QModelIndex const & a, QModelIndex const & b)
Definition at line 29 of file QtBasicNavigation.cpp.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::rowRemovalWouldBeIneffective().
below()
QModelIndex MantidQt::MantidWidgets::Batch::below (QModelIndex const & index)
Definition at line 11 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::findOrMakeCellBelow(), MantidQt::MantidWidgets::Batch::JobTreeView::replaceSubtreeAt(), and MantidQt::MantidWidgets::Batch::JobTreeView::siblingIfExistsElseParent().
extractCellPropertiesFromItem()
Cell MantidQt::MantidWidgets::Batch::extractCellPropertiesFromItem (QStandardItem const & item)
Definition at line 21 of file CellStandardItem.cpp.
References getBackgroundColor(), getBorderColor(), getBorderThickness(), getForegroundColor(), and getIconFilePath().
Referenced by MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellFromCellIndex().
firstCellOnRowOf()
QModelIndex MantidQt::MantidWidgets::Batch::firstCellOnRowOf (QModelIndex const & index)
Definition at line 27 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendChildRow(), and MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult().
fromFilteredModel()
QModelIndexForFilteredModel MantidQt::MantidWidgets::Batch::fromFilteredModel (QModelIndex const & filteredModelIndex, QAbstractItemModel const & model) inline
Definition at line 65 of file StrictQModelIndices.h.
References assertOrThrow().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::indexesAreOnSameRow().
fromMainModel()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::fromMainModel (QModelIndex const & mainModelIndex, QAbstractItemModel const & model) inline
Definition at line 76 of file StrictQModelIndices.h.
References assertOrThrow().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::indexesAreOnSameRow(), MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexIfExistsAt(), MantidQt::MantidWidgets::Batch::CellDelegate::paint(), and MantidQt::MantidWidgets::Batch::FilteredTreeModel::rowLocationAt().
getBackgroundColor()
std::string MantidQt::MantidWidgets::Batch::getBackgroundColor (QStandardItem const & item)
Definition at line 71 of file CellStandardItem.cpp.
Referenced by extractCellPropertiesFromItem().
getBorderColor()
QColor MantidQt::MantidWidgets::Batch::getBorderColor (QStandardItem const & item)
Definition at line 84 of file CellStandardItem.cpp.
References BorderColor.
Referenced by extractCellPropertiesFromItem(), and MantidQt::MantidWidgets::Batch::CellDelegate::paint().
getBorderThickness()
int MantidQt::MantidWidgets::Batch::getBorderThickness (QStandardItem const & item)
Definition at line 41 of file CellStandardItem.cpp.
References BorderThickness.
Referenced by extractCellPropertiesFromItem(), and MantidQt::MantidWidgets::Batch::CellDelegate::paint().
getForegroundColor()
std::string MantidQt::MantidWidgets::Batch::getForegroundColor (QStandardItem const & item)
Definition at line 80 of file CellStandardItem.cpp.
Referenced by extractCellPropertiesFromItem().
getIconFilePath()
std::string MantidQt::MantidWidgets::Batch::getIconFilePath (QStandardItem const & item)
Definition at line 43 of file CellStandardItem.cpp.
References IconFilePath.
Referenced by extractCellPropertiesFromItem().
hasCellOnTheLeft()
bool MantidQt::MantidWidgets::Batch::hasCellOnTheLeft (QModelIndex const & index)
Definition at line 19 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotFirstCellInThisRow().
hasCellOnTheRight()
bool MantidQt::MantidWidgets::Batch::hasCellOnTheRight (QModelIndex const & index)
Definition at line 21 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotLastCellOnThisRow().
hasRowAbove()
bool MantidQt::MantidWidgets::Batch::hasRowAbove (QModelIndex const & index)
Definition at line 23 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::editAtRowAbove(), MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotFirstRowInThisNode(), and MantidQt::MantidWidgets::Batch::JobTreeView::siblingIfExistsElseParent().
hasRowBelow()
bool MantidQt::MantidWidgets::Batch::hasRowBelow (QModelIndex const & index)
Definition at line 25 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::findOrMakeCellBelow(), MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotLastRowInThisNode(), and MantidQt::MantidWidgets::Batch::JobTreeView::siblingIfExistsElseParent().
hasSubtreeRootDeeperThanFirstRoot()
template<typename RowLocationConstIterator > bool MantidQt::MantidWidgets::Batch::hasSubtreeRootDeeperThanFirstRoot (int firstSubtreeRootDepth, RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
Definition at line 50 of file Subtree.h.
References MantidQt::MantidWidgets::Batch::RowLocation::depth(), and pathsSameUntilDepth().
Referenced by allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected().
hasSubtreeRootShallowerThanFirstRoot()
template<typename RowLocationConstIterator > bool MantidQt::MantidWidgets::Batch::hasSubtreeRootShallowerThanFirstRoot (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
Definition at line 23 of file Subtree.h.
References MantidQt::MantidWidgets::Batch::RowLocation::depth(), and rhs.
lastChildRowOf()
QModelIndex MantidQt::MantidWidgets::Batch::lastChildRowOf (QModelIndex const & index, QAbstractItemModel const & model)
Definition at line 56 of file QtTreeCursorNavigation.cpp.
Referenced by MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendChildRow(), and MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::lastRowInThisNode().
leftOf()
QModelIndex MantidQt::MantidWidgets::Batch::leftOf (QModelIndex const & index)
Definition at line 15 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::previousCellInThisRow().
makeFilterFromLambda()
template<typename Predicate > std::unique_ptr< RowPredicate > MantidQt::MantidWidgets::Batch::makeFilterFromLambda (Predicate predicate)
Definition at line 39 of file RowPredicate.h.
maximumIncreaseInDepthIsOne()
template<typename RowLocationConstIterator > bool MantidQt::MantidWidgets::Batch::maximumIncreaseInDepthIsOne (RowLocationConstIterator sortedRegionBegin, RowLocationConstIterator sortedRegionEnd)
Definition at line 42 of file Subtree.h.
References MantidQt::MantidWidgets::Batch::RowLocation::depth().
Referenced by allSubtreeRootsShareAParentAndAllSubtreeNodesAreConnected().
modelItemFromIndex() [1/2]
QStandardItem * MantidQt::MantidWidgets::Batch::modelItemFromIndex (QStandardItemModel & model, QModelIndexForMainModel const & index)
Definition at line 117 of file QtStandardItemTreeAdapter.cpp.
References assertOrThrow(), and index.
Referenced by MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::appendChildRow(), MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::cellFromCellIndex(), MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::insertChildRow(), MantidQt::MantidWidgets::Batch::CellDelegate::paint(), and MantidQt::MantidWidgets::Batch::QtStandardItemTreeModelAdapter::setCellAtCellIndex().
modelItemFromIndex() [2/2]
QStandardItem const * MantidQt::MantidWidgets::Batch::modelItemFromIndex (QStandardItemModel const & model, QModelIndexForMainModel const & index)
Definition at line 108 of file QtStandardItemTreeAdapter.cpp.
References assertOrThrow(), and index.
operator!=() [1/2]
bool MantidQt::MantidWidgets::Batch::operator!= (Cell const & lhs, Cell const & rhs)
Definition at line 93 of file Cell.cpp.
References rhs.
operator!=() [2/2]
bool MantidQt::MantidWidgets::Batch::operator!= (Row const & lhs, Row const & rhs)
Definition at line 30 of file Row.cpp.
References rhs.
operator<()
bool MantidQt::MantidWidgets::Batch::operator< (Row const & lhs, Row const & rhs)
Definition at line 32 of file Row.cpp.
References MantidQt::MantidWidgets::Batch::Row::location(), and rhs.
operator<<() [1/3]
std::ostream & MantidQt::MantidWidgets::Batch::operator<< (std::ostream & os, Cell const & cell)
Definition at line 83 of file Cell.cpp.
References MantidQt::MantidWidgets::Batch::Cell::contentText().
operator<<() [2/3]
std::ostream & MantidQt::MantidWidgets::Batch::operator<< (std::ostream & os, Row const & location)
Definition at line 19 of file Row.cpp.
References MantidQt::MantidWidgets::Batch::Row::cells(), and MantidQt::MantidWidgets::Batch::Row::location().
operator<<() [3/3]
std::ostream & MantidQt::MantidWidgets::Batch::operator<< (std::ostream & os, RowLocation const & location)
Definition at line 53 of file RowLocation.cpp.
References MantidQt::MantidWidgets::Batch::RowLocation::path().
operator<=()
bool MantidQt::MantidWidgets::Batch::operator<= (Row const & lhs, Row const & rhs)
Definition at line 34 of file Row.cpp.
References rhs.
operator==() [1/3]
bool MantidQt::MantidWidgets::Batch::operator== (Cell const & lhs, Cell const & rhs)
Definition at line 88 of file Cell.cpp.
References MantidQt::MantidWidgets::Batch::Cell::borderColor(), MantidQt::MantidWidgets::Batch::Cell::borderThickness(), MantidQt::MantidWidgets::Batch::Cell::contentText(), MantidQt::MantidWidgets::Batch::Cell::isEditable(), and rhs.
operator==() [2/3]
bool MantidQt::MantidWidgets::Batch::operator== (Row const & lhs, Row const & rhs)
Definition at line 26 of file Row.cpp.
References MantidQt::MantidWidgets::Batch::Row::cells(), MantidQt::MantidWidgets::Batch::Row::location(), and rhs.
operator==() [3/3]
template<typename Derived > bool MantidQt::MantidWidgets::Batch::operator== (StrictQModelIndex< Derived > const & lhs, StrictQModelIndex< Derived > const & rhs)
Definition at line 43 of file StrictQModelIndices.h.
References rhs, and MantidQt::MantidWidgets::Batch::StrictQModelIndex< Derived >::untyped().
operator>()
bool MantidQt::MantidWidgets::Batch::operator> (Row const & lhs, Row const & rhs)
Definition at line 38 of file Row.cpp.
References rhs.
operator>=()
bool MantidQt::MantidWidgets::Batch::operator>= (Row const & lhs, Row const & rhs)
Definition at line 36 of file Row.cpp.
References rhs.
paddedCellsToWidth()
std::vector< Cell > MantidQt::MantidWidgets::Batch::paddedCellsToWidth (std::vector< Cell > const & cells, Cell const & paddingCell, int paddedWidth)
Definition at line 95 of file Cell.cpp.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf(), and MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf().
pathsSameUntilDepth()
bool MantidQt::MantidWidgets::Batch::pathsSameUntilDepth (int depth, RowLocation const & locationA, RowLocation const & locationB)
Definition at line 114 of file RowLocation.cpp.
References assertOrThrow(), MantidQt::MantidWidgets::Batch::RowLocation::depth(), boost::algorithm::equal(), and MantidQt::MantidWidgets::Batch::RowLocation::path().
Referenced by hasSubtreeRootDeeperThanFirstRoot().
rightOf()
QModelIndex MantidQt::MantidWidgets::Batch::rightOf (QModelIndex const & index)
Definition at line 17 of file QtBasicNavigation.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::nextCellOnThisRow().
rowToRowLocation()
RowLocation MantidQt::MantidWidgets::Batch::rowToRowLocation (Row const & row)
Definition at line 45 of file ExtractSubtrees.cpp.
References MantidQt::MantidWidgets::Batch::Row::location().
Referenced by MantidQt::MantidWidgets::Batch::ExtractSubtrees::operator()().
setBackgroundColor()
void MantidQt::MantidWidgets::Batch::setBackgroundColor (QStandardItem & item, std::string const & backgroundColor)
Definition at line 66 of file CellStandardItem.cpp.
Referenced by applyCellPropertiesToItem().
setBorderColor()
void MantidQt::MantidWidgets::Batch::setBorderColor (QStandardItem & item, std::string const & borderColor, int alpha)
Definition at line 60 of file CellStandardItem.cpp.
References BorderColor.
Referenced by applyCellPropertiesToItem().
setBorderThickness()
void MantidQt::MantidWidgets::Batch::setBorderThickness (QStandardItem & item, int borderThickness)
Definition at line 37 of file CellStandardItem.cpp.
References BorderThickness.
Referenced by applyCellPropertiesToItem().
setForegroundColor()
void MantidQt::MantidWidgets::Batch::setForegroundColor (QStandardItem & item, std::string const & foregroundColor)
Definition at line 75 of file CellStandardItem.cpp.
Referenced by applyCellPropertiesToItem().
setIcon()
void MantidQt::MantidWidgets::Batch::setIcon (QStandardItem & item, std::string const & iconFilePath)
Definition at line 51 of file CellStandardItem.cpp.
References setIconFilePath().
Referenced by applyCellPropertiesToItem().
setIconFilePath()
void MantidQt::MantidWidgets::Batch::setIconFilePath (QStandardItem & item, QString const & iconFilePath)
Definition at line 47 of file CellStandardItem.cpp.
References IconFilePath.
Referenced by setIcon().