Mantid: Mantid::MDAlgorithms::DisplayNormalizationSetter Class Reference
Mantid::MDAlgorithms::DisplayNormalizationSetter Class Reference
DisplayNormalizationSetter: Sets the displaynormalization on a workspace based on several parameters such as workspace-type, energy-transfer-mode and if we are dealing with Q3D.
#include <DisplayNormalizationSetter.h>
Public Member Functions
void operator() (const Mantid::API::IMDWorkspace_sptr &mdWorkspace, const Mantid::API::MatrixWorkspace_sptr &underlyingWorkspace, bool isQ=false, const Mantid::Kernel::DeltaEMode::Type &mode=Mantid::Kernel::DeltaEMode::Elastic)
Sets the display normalization.
Private Member Functions
void applyNormalizationMDEvent (const Mantid::API::IMDWorkspace_sptr &mdWorkspace, Mantid::API::MDNormalization displayNormalization, Mantid::API::MDNormalization displayNormalizationHisto)
Apply the normalization to an MDEvent Workspace.
void setNormalizationMDEvent (const Mantid::API::IMDWorkspace_sptr &mdWorkspace, const Mantid::API::MatrixWorkspace_sptr &underlyingWorkspace, bool isQ=false, const Mantid::Kernel::DeltaEMode::Type &mode=Mantid::Kernel::DeltaEMode::Elastic)
Sets the display normalization for MDEventWorkspaces.
Detailed Description
DisplayNormalizationSetter: Sets the displaynormalization on a workspace based on several parameters such as workspace-type, energy-transfer-mode and if we are dealing with Q3D.
Definition at line 20 of file DisplayNormalizationSetter.h.
Member Function Documentation
applyNormalizationMDEvent()
void Mantid::MDAlgorithms::DisplayNormalizationSetter::applyNormalizationMDEvent (const Mantid::API::IMDWorkspace_sptr & mdWorkspace, Mantid::API::MDNormalization displayNormalization, Mantid::API::MDNormalization displayNormalizationHisto) private
Apply the normalization to an MDEvent Workspace.
Parameters
mdWorkspace the workspace which gets its normalization tags set
displayNormalization the display normalization for the MDEvent workspace
displayNormalizationHisto the display normalization for derived MDHisto workspaces
Definition at line 79 of file DisplayNormalizationSetter.cpp.
Referenced by setNormalizationMDEvent().
operator()()
void Mantid::MDAlgorithms::DisplayNormalizationSetter::operator() (const Mantid::API::IMDWorkspace_sptr & mdWorkspace, const Mantid::API::MatrixWorkspace_sptr & underlyingWorkspace, bool isQ = false, const Mantid::Kernel::DeltaEMode::Type & mode = Mantid::Kernel::DeltaEMode::Elastic)
Sets the display normalization.
Parameters
mdWorkspace the MDWorkspace which needs its normalizations flags set
underlyingWorkspace the underlying workspace, ie EventWorkspace or Workspace2D
isQ if the transform is Q or not
mode the energy transfer mode
Definition at line 24 of file DisplayNormalizationSetter.cpp.
References setNormalizationMDEvent().
setNormalizationMDEvent()
void Mantid::MDAlgorithms::DisplayNormalizationSetter::setNormalizationMDEvent (const Mantid::API::IMDWorkspace_sptr & mdWorkspace, const Mantid::API::MatrixWorkspace_sptr & underlyingWorkspace, bool isQ = false, const Mantid::Kernel::DeltaEMode::Type & mode = Mantid::Kernel::DeltaEMode::Elastic) private
Sets the display normalization for MDEventWorkspaces.
Parameters
mdWorkspace the MDWorkspace which needs its normalizations flags set
underlyingWorkspace the underlying workspace, ie EventWorkspace or Workspace2D
isQ if the transform is Q or not
mode the energy transfer mode
Definition at line 43 of file DisplayNormalizationSetter.cpp.
References applyNormalizationMDEvent(), Mantid::Kernel::DeltaEMode::Elastic, Mantid::API::NoNormalization, Mantid::API::NumEventsNormalization, and Mantid::API::VolumeNormalization.
Referenced by operator()().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/DisplayNormalizationSetter.h
Framework/MDAlgorithms/src/DisplayNormalizationSetter.cpp