Mantid: Mantid::NeXus::NexusFileIO Class Reference
Mantid::NeXus::NexusFileIO Class Reference
Utility method for saving NeXus format of Mantid Workspace This class interfaces to the C Nexus API.
#include <NeXus/NexusFileIO.h>
Public Types
using optional_size_t = boost::optional< size_t >
Public Member Functions
void closeGroup ()
Close the group.
void closeNexusFile ()
close the nexus file
int getSpectra (MantidVec &values, MantidVec &errors, const int &spectra) const
read values and errors for spectra
int getWorkspaceSize (int &numberOfSpectra, int &numberOfChannels, int &numberOfXpoints, bool &uniformBounds, std::string &axesUnits, std::string &yUnits) const
find size of open entry data section
int getXValues (MantidVec &xValues, const int &spectra) const
read X values for one (or the generic if uniform) spectra
NexusFileIO ()
Default constructor.
NexusFileIO (API::Progress *prog)
Contructor with Progress supplied.
void NXwritedata (const char *name, int datatype, int rank, int *dims_array, void *data, bool compress=false) const
Write out an array to the open file.
void openNexusWrite (const std::string &fileName, optional_size_t entryNumber=optional_size_t(), const bool append_to_file=true)
open the nexus file for writing
void resetProgress (Mantid::API::Progress *prog)
Reset the pointer to the progress object.
int writeEventList (const DataObjects::EventList &el, const std::string &group_name) const
Write out an event list into an already-opened group.
template<class T >
void writeEventListData (std::vector< T > events, bool writeTOF, bool writePulsetime, bool writeWeight, bool writeError) const
Write out the event list data, no matter what the underlying event type is.
bool writeNexusBinMasking (const API::MatrixWorkspace_const_sptr &ws) const
write bin masking information
int writeNexusProcessedData2D (const API::MatrixWorkspace_const_sptr &localworkspace, const bool &uniformSpectra, const std::vector< int > &indices, const char *group_name, bool write2Ddata) const
write the workspace data
int writeNexusProcessedDataEvent (const DataObjects::EventWorkspace_const_sptr &ws)
Write out all of the event lists in the given workspace.
int writeNexusProcessedDataEventCombined (const DataObjects::EventWorkspace_const_sptr &ws, std::vector< int64_t > &indices, double *tofs, float *weights, float *errorSquareds, int64_t *pulsetimes, bool compress) const
Write out a combined chunk of event data.
int writeNexusProcessedHeader (const std::string &title, const std::string &wsName="") const
write the header ifon for the Mantid workspace format
int writeNexusSampleLogs (const Mantid::API::Run &runProperties) const
Write a lgos section.
int writeNexusTableWorkspace (const API::ITableWorkspace_const_sptr &itableworkspace, const char *group_name) const
write table workspace
template<>
bool writeNxValue (const std::string &name, const std::string &value, const int nxType, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
Write a single valued entry to the Nexus file (specialization for a string)
template<>
bool writeSingleValueNXLog (const std::string &name, const std::string &value, const int nxType, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
Write a single valued NXLog entry to the Nexus file (specialization for a string)
~NexusFileIO ()
Destructor.
Public Attributes
NXhandle fileID
Nexus file handle.
Private Member Functions
bool checkAttributeName (const std::string &target) const
check if given attribute name is in currently opened entry
bool checkEntryAtLevel (const std::string &item) const
check if the gievn item exists in the current level
bool checkEntryAtLevelByAttribute (const std::string &attribute, std::string &entry) const
Look for entry with given attribute (eg "signal")
int findMantidWSEntries () const
search for exisiting MantidWorkpace_n entries in opened file
bool isTimeSeries (Kernel::Property *prop) const
Returns true if the given property is a time series property.
template<class T >
std::string logValueType () const
Return the log value type as string.
template<>
std::string logValueType () const
template<>
std::string logValueType () const
template<>
std::string logValueType () const
std::time_t to_time_t (const boost::posix_time::ptime &t)
convert posix time to time_t
template<class T >
void writeNexusTimeLog (const Kernel::TimeSeriesProperty< T > *timeSeries) const
Writes a numeric log to the Nexus file.
template<typename VecType , typename ElemType >
void writeNexusVectorColumn (const API::Column_const_sptr &col, const std::string &columnName, int nexusType, const std::string &interpret_as) const
Writes given vector column to the currently open Nexus file.
template<class T >
void writeNumericTimeLog (const Kernel::TimeSeriesProperty< T > *timeSeries) const
Writes a numeric log to the Nexus file.
void writeNumericTimeLog_String (const Kernel::TimeSeriesProperty< std::string > *s_timeSeries) const
Write NXlog data for given string TimeSeriesProperty.
void writeNxFloatArray (const std::string &name, const std::vector< double > &values, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
write a float array along with any defined attributes
bool writeNxNote (const std::string &noteName, const std::string &author, const std::string &date, const std::string &description, const std::string &pairValues) const
write an NXnote with standard fields (but NX_CHAR rather than NX_BINARY data)
bool writeNxStringArray (const std::string &name, const std::vector< std::string > &values, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
write a char array along with any defined attributes
template<class TYPE >
bool writeNxValue (const std::string &name, const TYPE &value, const int nxType, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
Write a simple value plus possible attributes.
bool writeSingleValueLog (Kernel::Property *prop) const
Write a single value log entry.
template<class TYPE >
bool writeSingleValueNXLog (const std::string &name, const TYPE &value, const int nxType, const std::vector< std::string > &attributes, const std::vector< std::string > &avalues) const
Write a single valued NXLog entry to the Nexus file.
template<typename ColumnT , typename NexusT >
void writeTableColumn (int type, const std::string &interpret_as, const API::Column &col, const std::string &columnName) const
Save a numeric columns of a TableWorkspace to currently open nexus file.
bool writeTimeSeriesLog (Kernel::Property *prop) const
Write a time series log entry.
Private Attributes
std::shared_ptr< ::NeXus::File > m_filehandle
C++ API file handle.
std::string m_filename
nexus file name
int m_nexuscompression
Nexus compression method.
API::Progress * m_progress
Allow an externally supplied progress object to be used.
Detailed Description
Utility method for saving NeXus format of Mantid Workspace This class interfaces to the C Nexus API.
This is written for use by Save and Load NexusProcessed classes, though it could be extended to other Nexus formats. It might be replaced in future by methods using the new Nexus C++ API.
Definition at line 38 of file NexusFileIO.h.
Member Typedef Documentation
optional_size_t
using Mantid::NeXus::NexusFileIO::optional_size_t = boost::optional<size_t>
Definition at line 42 of file NexusFileIO.h.
Constructor & Destructor Documentation
NexusFileIO() [1/2]
Mantid::NeXus::NexusFileIO::NexusFileIO ()
Default constructor.
Empty default constructor.
Definition at line 45 of file NexusFileIO.cpp.
NexusFileIO() [2/2]
Mantid::NeXus::NexusFileIO::NexusFileIO (API::Progress * prog)
Contructor with Progress supplied.
Constructor that supplies a progress object.
Definition at line 49 of file NexusFileIO.cpp.
~NexusFileIO()
Mantid::NeXus::NexusFileIO::~NexusFileIO ()
Destructor.
Definition at line 1229 of file NexusFileIO.cpp.
Member Function Documentation
checkAttributeName()
bool Mantid::NeXus::NexusFileIO::checkAttributeName (const std::string & target) const private
check if given attribute name is in currently opened entry
Definition at line 963 of file NexusFileIO.cpp.
References m_filehandle.
Referenced by checkEntryAtLevelByAttribute(), and getWorkspaceSize().
checkEntryAtLevel()
bool Mantid::NeXus::NexusFileIO::checkEntryAtLevel (const std::string & item) const private
check if the gievn item exists in the current level
Definition at line 1057 of file NexusFileIO.cpp.
References m_filehandle.
checkEntryAtLevelByAttribute()
bool Mantid::NeXus::NexusFileIO::checkEntryAtLevelByAttribute (const std::string & attribute, std::string & entry) const private
Look for entry with given attribute (eg "signal")
Definition at line 1063 of file NexusFileIO.cpp.
References checkAttributeName(), and m_filehandle.
Referenced by getSpectra(), and getWorkspaceSize().
closeGroup()
void Mantid::NeXus::NexusFileIO::closeGroup ()
Close the group.
Definition at line 158 of file NexusFileIO.cpp.
References m_filehandle.
closeNexusFile()
void Mantid::NeXus::NexusFileIO::closeNexusFile ()
close the nexus file
Definition at line 161 of file NexusFileIO.cpp.
References m_filehandle.
findMantidWSEntries()
int Mantid::NeXus::NexusFileIO::findMantidWSEntries () const private
search for exisiting MantidWorkpace_n entries in opened file
Definition at line 1042 of file NexusFileIO.cpp.
References count, and m_filehandle.
Referenced by openNexusWrite().
getSpectra()
int Mantid::NeXus::NexusFileIO::getSpectra (MantidVec & values, MantidVec & errors, const int & spectra) const
read values and errors for spectra
Definition at line 999 of file NexusFileIO.cpp.
References checkEntryAtLevelByAttribute(), and fileID.
getWorkspaceSize()
int Mantid::NeXus::NexusFileIO::getWorkspaceSize (int & numberOfSpectra, int & numberOfChannels, int & numberOfXpoints, bool & uniformBounds, std::string & axesUnits, std::string & yUnits) const
find size of open entry data section
Read the size of the data section in a mantid_workspace_entry and also get the names of axes.
Definition at line 896 of file NexusFileIO.cpp.
References checkAttributeName(), checkEntryAtLevelByAttribute(), and fileID.
getXValues()
int Mantid::NeXus::NexusFileIO::getXValues (MantidVec & xValues, const int & spectra) const
read X values for one (or the generic if uniform) spectra
Definition at line 972 of file NexusFileIO.cpp.
References fileID.
isTimeSeries()
bool Mantid::NeXus::NexusFileIO::isTimeSeries (Kernel::Property * prop) const private
Returns true if the given property is a time series property.
logValueType() [1/4]
template<class T > std::string Mantid::NeXus::NexusFileIO::logValueType () const inline private
Return the log value type as string.
Definition at line 173 of file NexusFileIO.h.
logValueType() [2/4]
template<> std::string Mantid::NeXus::NexusFileIO::logValueType () const private
Definition at line 1144 of file NexusFileIO.cpp.
logValueType() [3/4]
template<> std::string Mantid::NeXus::NexusFileIO::logValueType () const private
Definition at line 1146 of file NexusFileIO.cpp.
logValueType() [4/4]
template<> std::string Mantid::NeXus::NexusFileIO::logValueType () const private
Definition at line 1148 of file NexusFileIO.cpp.
NXwritedata()
void Mantid::NeXus::NexusFileIO::NXwritedata (const char * name, int datatype, int rank, int * dims_array, void * data, bool compress = false) const
Write out an array to the open file.
Definition at line 754 of file NexusFileIO.cpp.
References fileID, and m_nexuscompression.
Referenced by writeEventList(), writeEventListData(), writeNexusProcessedDataEventCombined(), writeNexusVectorColumn(), and writeTableColumn().
openNexusWrite()
void Mantid::NeXus::NexusFileIO::openNexusWrite (const std::string & fileName, NexusFileIO::optional_size_t entryNumber = optional_size_t(), const bool append_to_file = true)
open the nexus file for writing
Definition at line 80 of file NexusFileIO.cpp.
References count, Mantid::Kernel::Logger::error(), Mantid::DataHandling::exists(), fileID, findMantidWSEntries(), Mantid::API::g_log, m_filehandle, m_filename, and m_nexuscompression.
resetProgress()
void Mantid::NeXus::NexusFileIO::resetProgress (Mantid::API::Progress * prog)
Reset the pointer to the progress object.
Definition at line 52 of file NexusFileIO.cpp.
References m_progress.
to_time_t()
std::time_t Mantid::NeXus::NexusFileIO::to_time_t (const boost::posix_time::ptime & t) inline private
convert posix time to time_t
Take the input Posix time, subtract the unix epoch, and return the seconds as a std::time_t value.
Parameters
t :: time of interest as ptime
Returns
:: time_t value of t
Parameters
t convert posix time to time_t
Definition at line 147 of file NexusFileIO.h.
writeEventList()
int Mantid::NeXus::NexusFileIO::writeEventList (const DataObjects::EventList & el, const std::string & group_name) const
Write out an event list into an already-opened group.
Parameters
el :: reference to the EventList to write.
group_name :: group_name to create.
Definition at line 830 of file NexusFileIO.cpp.
References fileID, Mantid::API::ISpectrum::getDetectorIDs(), Mantid::DataObjects::EventList::getEvents(), Mantid::DataObjects::EventList::getEventType(), Mantid::DataObjects::EventList::getNumberEvents(), Mantid::DataObjects::EventList::getSortType(), Mantid::DataObjects::EventList::getWeightedEvents(), Mantid::DataObjects::EventList::getWeightedEventsNoTime(), NXwritedata(), Mantid::DataObjects::PULSETIME_SORT, Mantid::API::TOF, Mantid::DataObjects::TOF_SORT, Mantid::DataObjects::UNSORTED, Mantid::API::WEIGHTED, Mantid::API::WEIGHTED_NOTIME, and writeEventListData().
Referenced by writeNexusProcessedDataEvent().
writeEventListData()
template<class T > void Mantid::NeXus::NexusFileIO::writeEventListData (std::vector< T > events, bool writeTOF, bool writePulsetime, bool writeWeight, bool writeError) const
Write out the event list data, no matter what the underlying event type is.
Parameters
events :: vector of TofEvent or WeightedEvent, etc.
writeTOF :: if true, write the TOF values
writePulsetime :: if true, write the pulse time values
writeWeight :: if true, write the event weights
writeError :: if true, write the errors
Definition at line 778 of file NexusFileIO.cpp.
References NXwritedata().
Referenced by writeEventList().
writeNexusBinMasking()
bool Mantid::NeXus::NexusFileIO::writeNexusBinMasking (const API::MatrixWorkspace_const_sptr & ws) const
write bin masking information
Write bin masking information.
Parameters
ws :: The workspace
Returns
true for OK, false for error
Definition at line 1087 of file NexusFileIO.cpp.
References fileID.
Referenced by writeNexusProcessedData2D().
writeNexusProcessedData2D()
int Mantid::NeXus::NexusFileIO::writeNexusProcessedData2D (const API::MatrixWorkspace_const_sptr & localworkspace, const bool & uniformSpectra, const std::vector< int > & indices, const char * group_name, bool write2Ddata) const
write the workspace data
Write out a MatrixWorkspace's data as a 2D matrix.
Use writeNexusProcessedDataEvent if writing an EventWorkspace.
Definition at line 280 of file NexusFileIO.cpp.
References fileID, Mantid::API::Axis::isSpectra(), Mantid::API::Axis::isText(), Mantid::API::Axis::label(), Mantid::API::Axis::length(), m_nexuscompression, m_progress, Mantid::Kernel::ProgressBase::reportIncrement(), Mantid::API::Axis::unit(), and writeNexusBinMasking().
Referenced by Mantid::DataHandling::SaveNexusProcessed::execEvent().
writeNexusProcessedDataEvent()
int Mantid::NeXus::NexusFileIO::writeNexusProcessedDataEvent (const DataObjects::EventWorkspace_const_sptr & ws)
Write out all of the event lists in the given workspace.
Parameters
ws :: an EventWorkspace
Definition at line 734 of file NexusFileIO.cpp.
References fileID, and writeEventList().
writeNexusProcessedDataEventCombined()
int Mantid::NeXus::NexusFileIO::writeNexusProcessedDataEventCombined (const DataObjects::EventWorkspace_const_sptr & ws, std::vector< int64_t > & indices, double * tofs, float * weights, float * errorSquareds, int64_t * pulsetimes, bool compress) const
Write out a combined chunk of event data.
Parameters
ws :: an EventWorkspace
indices :: array of event list indexes
tofs :: array of TOFs
weights :: array of event weights
errorSquareds :: array of event squared errors
pulsetimes :: array of pulsetimes
compress :: if true, compress the entry
Definition at line 694 of file NexusFileIO.cpp.
References fileID, m_nexuscompression, and NXwritedata().
Referenced by Mantid::DataHandling::SaveNexusProcessed::execEvent().
writeNexusProcessedHeader()
int Mantid::NeXus::NexusFileIO::writeNexusProcessedHeader (const std::string & title, const std::string & wsName = "") const
write the header ifon for the Mantid workspace format
Write Nexus mantid workspace header fields for the NXentry/IXmantid/NXprocessed field.
The URLs are not correct as they do not exist presently, but follow the format for other Nexus specs.
Parameters
title :: title field.
wsName :: workspace name.
Returns
zero on success, a non-zero value on failure.
Definition at line 176 of file NexusFileIO.cpp.
writeNexusSampleLogs()
int Mantid::NeXus::NexusFileIO::writeNexusSampleLogs (const Mantid::API::Run & runProperties) const
Write a lgos section.
writeNexusTableWorkspace()
int Mantid::NeXus::NexusFileIO::writeNexusTableWorkspace (const API::ITableWorkspace_const_sptr & itableworkspace, const char * group_name) const
write table workspace
Write out a table Workspace's.
Definition at line 590 of file NexusFileIO.cpp.
References fileID, and std::to_string().
writeNexusTimeLog()
template<class T > void Mantid::NeXus::NexusFileIO::writeNexusTimeLog (const Kernel::TimeSeriesProperty< T > * timeSeries) const private
Writes a numeric log to the Nexus file.
Template Parameters
T A numeric type (double, int, bool)
Parameters
timeSeries :: A pointer to the log property
writeNexusVectorColumn()
template<typename VecType , typename ElemType > void Mantid::NeXus::NexusFileIO::writeNexusVectorColumn (const API::Column_const_sptr & col, const std::string & columnName, int nexusType, const std::string & interpret_as) const private
Writes given vector column to the currently open Nexus file.
Parameters
col :: Column to write
columnName :: Name of NXdata to write to
nexusType :: Nexus type to use to store data
interpret_as :: Name of the type to use for "interpret_as" attribute
Definition at line 530 of file NexusFileIO.cpp.
References fileID, NXwritedata(), and Mantid::API::ConstColumnVector< T >::size().
writeNumericTimeLog()
template<class T > void Mantid::NeXus::NexusFileIO::writeNumericTimeLog (const Kernel::TimeSeriesProperty< T > * timeSeries) const private
Writes a numeric log to the Nexus file.
Template Parameters
T A numeric type (double, int, bool)
Parameters
timeSeries :: A pointer to the log property
Definition at line 324 of file NexusFileIO.h.
References fileID, Mantid::Kernel::Property::name(), Mantid::Kernel::TimeSeriesProperty< TYPE >::valueAsMap(), and writeNxFloatArray().
writeNumericTimeLog_String()
void Mantid::NeXus::NexusFileIO::writeNumericTimeLog_String (const Kernel::TimeSeriesProperty< std::string > * s_timeSeries) const private
Write NXlog data for given string TimeSeriesProperty.
writeNxFloatArray()
void Mantid::NeXus::NexusFileIO::writeNxFloatArray (const std::string & name, const std::vector< double > & values, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const private
write a float array along with any defined attributes
Definition at line 210 of file NexusFileIO.cpp.
References m_filehandle.
Referenced by writeNumericTimeLog().
writeNxNote()
bool Mantid::NeXus::NexusFileIO::writeNxNote (const std::string & noteName, const std::string & author, const std::string & date, const std::string & description, const std::string & pairValues) const private
write an NXnote with standard fields (but NX_CHAR rather than NX_BINARY data)
Definition at line 253 of file NexusFileIO.cpp.
References m_filehandle.
writeNxStringArray()
bool Mantid::NeXus::NexusFileIO::writeNxStringArray (const std::string & name, const std::vector< std::string > & values, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const private
write a char array along with any defined attributes
Definition at line 224 of file NexusFileIO.cpp.
References fileID, and rhs.
writeNxValue() [1/2]
template<> bool Mantid::NeXus::NexusFileIO::writeNxValue (const std::string & name, const std::string & value, const int nxType, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const inline
Write a single valued entry to the Nexus file (specialization for a string)
Parameters
name :: The name of the entry
value :: The value of the entry
nxType :: The nxType of the entry
attributes :: A list of attributes 1:1 mapped to their values in the avalues argument
avalues :: A list of attribute values in the same order as the attributes argument
Returns
A boolean indicating success or failure
Definition at line 227 of file NexusFileIO.h.
References fileID, and value.
writeNxValue() [2/2]
template<class TYPE > bool Mantid::NeXus::NexusFileIO::writeNxValue (const std::string & name, const TYPE & value, const int nxType, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const private
Write a simple value plus possible attributes.
Write a single valued entry to the Nexus file.
Parameters
name :: The name of the entry
value :: The value of the entry
nxType :: The nxType of the entry
attributes :: A list of attributes 1:1 mapped to their values in the avalues argument
avalues :: A list of attribute values in the same order as the attributes argument
Returns
A boolean indicating success or failure
Definition at line 198 of file NexusFileIO.h.
References fileID, and value.
writeSingleValueLog()
bool Mantid::NeXus::NexusFileIO::writeSingleValueLog (Kernel::Property * prop) const private
Write a single value log entry.
writeSingleValueNXLog() [1/2]
template<> bool Mantid::NeXus::NexusFileIO::writeSingleValueNXLog (const std::string & name, const std::string & value, const int nxType, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const inline
Write a single valued NXLog entry to the Nexus file (specialization for a string)
Parameters
name :: The name of the entry
value :: The value of the entry
nxType :: The nxType of the entry
attributes :: A list of attributes 1:1 mapped to their values in the avalues argument
avalues :: A list of attribute values in the same order as the attributes argument
Returns
A boolean indicating success or failure
Definition at line 294 of file NexusFileIO.h.
References fileID, and value.
writeSingleValueNXLog() [2/2]
template<class TYPE > bool Mantid::NeXus::NexusFileIO::writeSingleValueNXLog (const std::string & name, const TYPE & value, const int nxType, const std::vector< std::string > & attributes, const std::vector< std::string > & avalues) const private
Write a single valued NXLog entry to the Nexus file.
Parameters
name :: The name of the entry
value :: The value of the entry
nxType :: The nxType of the entry
attributes :: A list of attributes 1:1 mapped to their values in the avalues argument
avalues :: A list of attribute values in the same order as the attributes argument
Returns
A boolean indicating success or failure
Definition at line 260 of file NexusFileIO.h.
References fileID, and value.
writeTableColumn()
template<typename ColumnT , typename NexusT > void Mantid::NeXus::NexusFileIO::writeTableColumn (int type, const std::string & interpret_as, const API::Column & col, const std::string & columnName) const private
Save a numeric columns of a TableWorkspace to currently open nexus file.
Parameters
type :: Nexus code for the element data type.
interpret_as :: Value of the interpret_as attribute.
col :: Reference to the column being svaed.
columnName :: Name of the nexus data set in which the column values are saved.
Definition at line 493 of file NexusFileIO.cpp.
References Mantid::API::Column::cell(), fileID, NXwritedata(), and Mantid::API::Column::size().
writeTimeSeriesLog()
bool Mantid::NeXus::NexusFileIO::writeTimeSeriesLog (Kernel::Property * prop) const private
Write a time series log entry.
Member Data Documentation
fileID
NXhandle Mantid::NeXus::NexusFileIO::fileID
Nexus file handle.
Definition at line 99 of file NexusFileIO.h.
Referenced by getSpectra(), getWorkspaceSize(), getXValues(), NXwritedata(), openNexusWrite(), writeEventList(), writeNexusBinMasking(), writeNexusProcessedData2D(), writeNexusProcessedDataEvent(), writeNexusProcessedDataEventCombined(), writeNexusTableWorkspace(), writeNexusVectorColumn(), writeNumericTimeLog(), writeNxStringArray(), writeNxValue(), writeSingleValueNXLog(), and writeTableColumn().
m_filehandle
std::shared_ptr< ::NeXus::File> Mantid::NeXus::NexusFileIO::m_filehandle private
C++ API file handle.
Definition at line 104 of file NexusFileIO.h.
Referenced by checkAttributeName(), checkEntryAtLevel(), checkEntryAtLevelByAttribute(), closeGroup(), closeNexusFile(), findMantidWSEntries(), openNexusWrite(), writeNxFloatArray(), and writeNxNote().
m_filename
std::string Mantid::NeXus::NexusFileIO::m_filename private
nexus file name
Definition at line 164 of file NexusFileIO.h.
Referenced by openNexusWrite().
m_nexuscompression
int Mantid::NeXus::NexusFileIO::m_nexuscompression private
Nexus compression method.
Definition at line 107 of file NexusFileIO.h.
Referenced by NXwritedata(), openNexusWrite(), writeNexusProcessedData2D(), and writeNexusProcessedDataEventCombined().
m_progress
API::Progress* Mantid::NeXus::NexusFileIO::m_progress private
Allow an externally supplied progress object to be used.
Definition at line 109 of file NexusFileIO.h.
Referenced by resetProgress(), and writeNexusProcessedData2D().
The documentation for this class was generated from the following files:
Framework/Nexus/inc/MantidNexus/NexusFileIO.h
Framework/Nexus/src/NexusFileIO.cpp