Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/Material.cpp File Reference
Material.cpp File Reference
#include "MantidKernel/Material.h"
#include "MantidKernel/Atom.h"
#include "MantidKernel/NeutronAtom.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/list.hpp>
#include <boost/python/make_function.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/tuple.hpp>
#include <numeric>
Functions
void export_Material ()
Function Documentation
export_Material()
void export_Material ()
Definition at line 63 of file Material.cpp.
References Mantid::Kernel::Material::absorbXSection(), Mantid::Kernel::Material::cohScatterLength(), Mantid::Kernel::Material::cohScatterLengthImg(), Mantid::Kernel::Material::cohScatterLengthReal(), Mantid::Kernel::Material::cohScatterLengthSqrd(), Mantid::Kernel::Material::cohScatterXSection(), Mantid::Kernel::Material::incohScatterLength(), Mantid::Kernel::Material::incohScatterLengthImg(), Mantid::Kernel::Material::incohScatterLengthReal(), Mantid::Kernel::Material::incohScatterLengthSqrd(), Mantid::Kernel::Material::incohScatterXSection(), Mantid::Kernel::Material::name(), Mantid::Kernel::Material::numberDensity(), Mantid::Kernel::Material::numberDensityEffective(), Mantid::Kernel::Material::packingFraction(), Mantid::Kernel::Material::pressure(), Mantid::PhysicalConstants::NeutronAtom::ReferenceLambda, Mantid::Kernel::Material::temperature(), Mantid::Kernel::Material::totalAtoms(), Mantid::Kernel::Material::totalScatterLength(), Mantid::Kernel::Material::totalScatterLengthSqrd(), and Mantid::Kernel::Material::totalScatterXSection().