Mantid: MantidQt::MantidWidgets::IAlgorithmProgressWidget Class Reference
MantidQt::MantidWidgets::IAlgorithmProgressWidget Class Reference abstract
#include <IAlgorithmProgressWidget.h>
Public Member Functions
virtual void algorithmEnded ()=0
virtual void algorithmStarted ()=0
IAlgorithmProgressWidget ()=default
virtual void showDetailsDialog ()=0
virtual void updateProgress (const double progress, const QString &message, const double estimatedTime, const int progressPrecision)=0
virtual ~IAlgorithmProgressWidget ()=default
Detailed Description
Definition at line 12 of file IAlgorithmProgressWidget.h.
Constructor & Destructor Documentation
IAlgorithmProgressWidget()
MantidQt::MantidWidgets::IAlgorithmProgressWidget::IAlgorithmProgressWidget () default
~IAlgorithmProgressWidget()
virtual MantidQt::MantidWidgets::IAlgorithmProgressWidget::~IAlgorithmProgressWidget () virtual default
Member Function Documentation
algorithmEnded()
virtual void MantidQt::MantidWidgets::IAlgorithmProgressWidget::algorithmEnded () pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressWidget.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressPresenter::algorithmEndedSlot().
algorithmStarted()
virtual void MantidQt::MantidWidgets::IAlgorithmProgressWidget::algorithmStarted () pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressWidget.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressPresenter::algorithmStartedSlot().
showDetailsDialog()
virtual void MantidQt::MantidWidgets::IAlgorithmProgressWidget::showDetailsDialog () pure virtual
updateProgress()
virtual void MantidQt::MantidWidgets::IAlgorithmProgressWidget::updateProgress (const double progress, const QString & message, const double estimatedTime, const int progressPrecision) pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressWidget.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressPresenter::updateProgressBarSlot().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/IAlgorithmProgressWidget.h