Mantid: MantidQt::MantidWidgets::InputControllerPick Class Reference
MantidQt::MantidWidgets::InputControllerPick Class Reference
Controller for picking detectors.
#include <InputController.h>
Signals
void finishSelection ()
void pickPointAt (int, int)
void setSelection (const QRect &)
void touchPointAt (int, int)
Signals inherited from MantidQt::MantidWidgets::InputController
void disabled ()
void enabled ()
void touchPointAt (int, int)
Public Member Functions
InputControllerPick (QObject *parent)
Constructor.
void mouseMoveEvent (QMouseEvent *) override
Process the mouse move event.
void mousePressEvent (QMouseEvent *) override
Process the mouse press event.
void mouseReleaseEvent (QMouseEvent *) override
Process the mouse release event.
Public Member Functions inherited from MantidQt::MantidWidgets::InputController
bool canShowContextMenu () const
Returns true if a surface using this controller can show a context menu on right-click.
virtual void enterEvent (QEvent *)
virtual void freezeRotation (bool)
InputController (QObject *parent, bool contextAllowed=true)
virtual void keyPressEvent (QKeyEvent *)
virtual void leaveEvent (QEvent *)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *)
virtual void mouseReleaseEvent (QMouseEvent *)
virtual void onDisabled ()
To be called when this controller looses control.
virtual void onEnabled ()
To be called when this controller takes control of the input.
virtual void onPaint (QPainter &)
To be called after the owner widget has drawn its content.
virtual void wheelEvent (QWheelEvent *)
~InputController () override=default
Private Attributes
bool m_isButtonPressed
QRect m_rect
Detailed Description
Controller for picking detectors.
Definition at line 116 of file InputController.h.
Constructor & Destructor Documentation
InputControllerPick()
MantidQt::MantidWidgets::InputControllerPick::InputControllerPick (QObject * parent)
Constructor.
Parameters
parent :: The parent object.
Definition at line 91 of file InputController.cpp.
Member Function Documentation
finishSelection
void MantidQt::MantidWidgets::InputControllerPick::finishSelection () signal
Referenced by mouseReleaseEvent().
mouseMoveEvent()
void MantidQt::MantidWidgets::InputControllerPick::mouseMoveEvent (QMouseEvent * event) override virtual
Process the mouse move event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 107 of file InputController.cpp.
References m_isButtonPressed, m_rect, setSelection(), and touchPointAt().
mousePressEvent()
void MantidQt::MantidWidgets::InputControllerPick::mousePressEvent (QMouseEvent * event) override virtual
Process the mouse press event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 96 of file InputController.cpp.
References m_isButtonPressed, m_rect, and pickPointAt().
mouseReleaseEvent()
void MantidQt::MantidWidgets::InputControllerPick::mouseReleaseEvent (QMouseEvent *) override virtual
Process the mouse release event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 119 of file InputController.cpp.
References finishSelection(), and m_isButtonPressed.
pickPointAt
void MantidQt::MantidWidgets::InputControllerPick::pickPointAt (int , int) signal
Referenced by mousePressEvent().
setSelection
void MantidQt::MantidWidgets::InputControllerPick::setSelection (const QRect &) signal
Referenced by mouseMoveEvent().
touchPointAt
void MantidQt::MantidWidgets::InputControllerPick::touchPointAt (int , int) signal
Referenced by mouseMoveEvent().
Member Data Documentation
m_isButtonPressed
bool MantidQt::MantidWidgets::InputControllerPick::m_isButtonPressed private
Definition at line 132 of file InputController.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_rect
QRect MantidQt::MantidWidgets::InputControllerPick::m_rect private
Definition at line 133 of file InputController.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InputController.h
qt/widgets/common/src/InputController.cpp