Mantid: Mantid::Crystal::HardThresholdBackground Class Reference
Mantid::Crystal::HardThresholdBackground Class Reference
HardThresholdBackground : Implementation of BackgroundStrategy using a fixed background signal value as the threshold.
#include <HardThresholdBackground.h>
Public Member Functions
HardThresholdBackground * clone () const override
Virtual constructor.
void configureIterator (Mantid::API::IMDIterator *const iterator) const override
Overriden configureIterator.
HardThresholdBackground (const double thresholdSignal, const Mantid::API::MDNormalization normalization)
Contructor.
bool isBackground (Mantid::API::IMDIterator *iterator) const override
Overriden isBackground.
Public Member Functions inherited from Mantid::Crystal::BackgroundStrategy
virtual BackgroundStrategy * clone () const =0
virtual void configureIterator (Mantid::API::IMDIterator *const iterator) const =0
virtual bool isBackground (Mantid::API::IMDIterator *const iterator) const =0
virtual ~BackgroundStrategy ()=default
Private Attributes
Mantid::API::MDNormalization m_normalization
Normalization.
double m_thresholdSignal
Cutoff.
Detailed Description
HardThresholdBackground : Implementation of BackgroundStrategy using a fixed background signal value as the threshold.
Definition at line 19 of file HardThresholdBackground.h.
Constructor & Destructor Documentation
HardThresholdBackground()
Mantid::Crystal::HardThresholdBackground::HardThresholdBackground (const double thresholdSignal, const Mantid::API::MDNormalization normalization)
Contructor.
Constructor.
Definition at line 15 of file HardThresholdBackground.cpp.
Member Function Documentation
clone()
HardThresholdBackground * Mantid::Crystal::HardThresholdBackground::clone () const override virtual
Virtual constructor.
Implements Mantid::Crystal::BackgroundStrategy.
Reimplemented in Mantid::Crystal::PeakBackground.
Definition at line 19 of file HardThresholdBackground.cpp.
configureIterator()
void Mantid::Crystal::HardThresholdBackground::configureIterator (Mantid::API::IMDIterator *const iterator) const override virtual
Overriden configureIterator.
Implements Mantid::Crystal::BackgroundStrategy.
Reimplemented in Mantid::Crystal::PeakBackground.
Definition at line 21 of file HardThresholdBackground.cpp.
References m_normalization, and Mantid::API::IMDIterator::setNormalization().
isBackground()
bool Mantid::Crystal::HardThresholdBackground::isBackground (Mantid::API::IMDIterator * iterator) const override virtual
Overriden isBackground.
Implements Mantid::Crystal::BackgroundStrategy.
Reimplemented in Mantid::Crystal::PeakBackground.
Definition at line 25 of file HardThresholdBackground.cpp.
References Mantid::API::IMDIterator::getNormalizedSignal(), and m_thresholdSignal.
Referenced by Mantid::Crystal::PeakBackground::isBackground().
Member Data Documentation
m_normalization
Mantid::API::MDNormalization Mantid::Crystal::HardThresholdBackground::m_normalization private
Normalization.
Definition at line 37 of file HardThresholdBackground.h.
Referenced by configureIterator().
m_thresholdSignal
double Mantid::Crystal::HardThresholdBackground::m_thresholdSignal private
Cutoff.
Definition at line 35 of file HardThresholdBackground.h.
Referenced by isBackground().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/HardThresholdBackground.h
Framework/Crystal/src/HardThresholdBackground.cpp