Mantid: ICat4::xsd__long Class Reference
ICat4::xsd__long Class Reference
#include <ICat4Stub.h>
Public Member Functions
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
xsd__long ()
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
LONG64 __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 198 of file ICat4Stub.h.
Constructor & Destructor Documentation
xsd__long()
ICat4::xsd__long::xsd__long () inline
Definition at line 210 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::xsd__long::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23830 of file ICat4C.cpp.
References ICat4::soap_default_LONG64().
Referenced by ICat4::soap_in_xsd__long(), ICat4::soap_new_req_xsd__long(), and ICat4::soap_new_set_xsd__long().
soap_get()
void * ICat4::xsd__long::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23885 of file ICat4C.cpp.
References ICat4::soap_get_xsd__long().
soap_in()
void * ICat4::xsd__long::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23853 of file ICat4C.cpp.
References ICat4::soap_in_xsd__long().
Referenced by ICat4::soap_in_xsd__long().
soap_out()
int ICat4::xsd__long::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23844 of file ICat4C.cpp.
References ICat4::soap_out_xsd__long().
soap_put()
int ICat4::xsd__long::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23878 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_xsd__long.
soap_serialize()
void ICat4::xsd__long::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 23836 of file ICat4C.cpp.
References SOAP_TYPE_ICat4_LONG64.
soap_type()
int ICat4::xsd__long::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 203 of file ICat4Stub.h.
Member Data Documentation
__item
LONG64 ICat4::xsd__long::__item
Definition at line 200 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp