Mantid: Mantid::API::ILatticeFunction Class Reference
Mantid::API::ILatticeFunction Class Reference abstract
ILatticeFunction.
#include <ILatticeFunction.h>
Public Member Functions
void function (const FunctionDomain &domain, FunctionValues &values) const override
Implementation of IFunction::function.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Implementation of IFunction::functionDeriv.
virtual void functionDerivLattice (const LatticeDomain &latticeDomain, Jacobian &jacobian)
Default implementation, throws NotImplementedError.
virtual void functionLattice (const LatticeDomain &latticeDomain, FunctionValues &values) const =0
Function that should calculate d-values for the HKLs provided in the domain.
virtual Geometry::UnitCell getUnitCell () const =0
Returns a unit cell object created from the function parameters.
ILatticeFunction ()
virtual void setLatticeSystem (const std::string &crystalSystem)=0
A string that names the crystal system.
virtual void setUnitCell (const Geometry::UnitCell &unitCell)=0
Overload to set unit cell directly from UnitCell object.
virtual void setUnitCell (const std::string &unitCellString)=0
Set the function parameters according to the supplied unit cell.
Public Member Functions inherited from Mantid::API::FunctionParameterDecorator
double activeParameter (size_t i) const override
Value of i-th active parameter of the decorated function.
void addConstraint (std::unique_ptr< IConstraint > ic) override
Add a constraint to decorated function.
void addTies (const std::string &ties, bool isDefault=false) override
Add ties to the decorated function.
void applyTies () override
Apply the ties in decorated function.
void clearTies () override
Remove all ties of decorated function.
IFunction_sptr clone () const override
Virtual copy constructor.
FunctionParameterDecorator ()
IFunction::Attribute getAttribute (const std::string &attName) const override
Return a value of attribute attName of decorated function-.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names of decorated function.
IConstraint * getConstraint (size_t i) const override
Get constraint of i-th parameter of decorated function.
IFunction_sptr getDecoratedFunction () const
double getError (const std::string &name) const override
Get the fitting error for a parameter of decorated function by name.
double getError (size_t i) const override
Get the fitting error for a parameter of decorated function.
double getParameter (const std::string &name) const override
Get parameter of decorated function by name.
double getParameter (size_t i) const override
Get i-th parameter of decorated function.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index of decorated function from a parameter reference.
ParameterTie * getTie (size_t i) const override
Get the tie of i-th parameter of decorated function.
bool hasAttribute (const std::string &attName) const override
Check if attribute attName exists in decorated function.
bool hasParameter (const std::string &name) const override
Check if the decorated function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter of decorated function has been set explicitly.
size_t nAttributes () const override
Returns the number of attributes associated with the decorated function.
size_t nParams () const override
Total number of parameters of decorated function.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i of decorated function.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter of decorated function name.
std::string parameterName (size_t i) const override
Returns the name of parameter i of decorated function.
void removeConstraint (const std::string &parName) override
Remove a constraint of decorated function.
void removeTie (const std::string &parName) override
Removes the tie off a parameter.
bool removeTie (size_t i) override
Removes i-th parameter's of decorated function tie.
void setActiveParameter (size_t i, double value) override
Set new value of i-th active parameter of the decorated function.
void setAttribute (const std::string &attName, const IFunction::Attribute &attValue) override
Set a value to attribute attName of decorated function.
void setDecoratedFunction (const std::string &wrappedFunctionName)
void setError (const std::string &name, double err) override
Set the fitting error for a parameter of decorated function by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter of decorated function.
void setMatrixWorkspace (std::shared_ptr< const MatrixWorkspace > workspace, size_t wi, double startX, double endX) override
Set matrix workspace.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter of decorated function by name.
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter of decorated function.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter of decorated function by name.
void setParameterDescription (size_t i, const std::string &description) override
Set i-th parameter description of decorated function.
void setUpForFit () override
Set parameters of decorated function to satisfy constraints.
void setWorkspace (std::shared_ptr< const Workspace > ws) override
Set the workspace.
void tie (const std::string &parName, const std::string &expr, bool isDefault=false) override
Tie a parameter of decorated function to other parameters (or a constant).
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Member Functions inherited from Mantid::API::FunctionParameterDecorator
void addTie (std::unique_ptr< ParameterTie >) override
Forwads addTie-call to the decorated function.
virtual void beforeDecoratedFunctionSet (const IFunction_sptr &fn)
Function that is called before the decorated function is set.
void declareParameter (const std::string &name, double initValue, const std::string &description) override
Does nothing, function does not have parameters.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void init () override
Does nothing.
void setDecoratedFunctionPrivate (const IFunction_sptr &fn)
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
void throwIfNoFunctionSet () const
Throws std::runtime_error when m_wrappedFunction is not set.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Attributes inherited from Mantid::API::FunctionParameterDecorator
IFunction_sptr m_wrappedFunction
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
ILatticeFunction.
This abstract class defines the interface for a function that calculates values based on HKL-values and a lattice. Currently the only implementation is CurveFitting::LatticeFunction.
Author
Michael Wedel, Paul Scherrer Institut - SINQ
Date
15/04/2015
Definition at line 26 of file ILatticeFunction.h.
Constructor & Destructor Documentation
ILatticeFunction()
Mantid::API::ILatticeFunction::ILatticeFunction ()
Definition at line 13 of file ILatticeFunction.cpp.
Member Function Documentation
function()
void Mantid::API::ILatticeFunction::function (const FunctionDomain & domain, FunctionValues & values) const override virtual
Implementation of IFunction::function.
The implementation tries to cast the supplied domain to LatticeDomain, and calls functionLattice, which needs to be implemented in subclasses.
Parameters
domain :: A FunctionDomain of type LatticeDomain
values :: Function values.
Implements Mantid::API::IFunction.
Definition at line 24 of file ILatticeFunction.cpp.
References functionLattice().
functionDeriv()
void Mantid::API::ILatticeFunction::functionDeriv (const FunctionDomain & domain, Jacobian & jacobian) override virtual
Implementation of IFunction::functionDeriv.
Just like the function-method, the domain is checked for correct type. If functionDerivLattice has not been implemented, numerical derivatives are calculated.
Parameters
domain :: A FunctionDomain of type LatticeDomain
jacobian :: Jacobian matrix
Reimplemented from Mantid::API::IFunction.
Definition at line 44 of file ILatticeFunction.cpp.
References Mantid::API::IFunction::calNumericalDeriv(), and functionDerivLattice().
functionDerivLattice()
void Mantid::API::ILatticeFunction::functionDerivLattice (const LatticeDomain & latticeDomain, Jacobian & jacobian) virtual
Default implementation, throws NotImplementedError.
Definition at line 57 of file ILatticeFunction.cpp.
References UNUSED_ARG.
Referenced by functionDeriv().
functionLattice()
virtual void Mantid::API::ILatticeFunction::functionLattice (const LatticeDomain & latticeDomain, FunctionValues & values) const pure virtual
Function that should calculate d-values for the HKLs provided in the domain.
Implemented in Mantid::CurveFitting::LatticeFunction.
Referenced by function().
getUnitCell()
virtual Geometry::UnitCell Mantid::API::ILatticeFunction::getUnitCell () const pure virtual
Returns a unit cell object created from the function parameters.
Implemented in Mantid::CurveFitting::LatticeFunction.
setLatticeSystem()
virtual void Mantid::API::ILatticeFunction::setLatticeSystem (const std::string & crystalSystem) pure virtual
A string that names the crystal system.
Implemented in Mantid::CurveFitting::LatticeFunction.
setUnitCell() [1/2]
virtual void Mantid::API::ILatticeFunction::setUnitCell (const Geometry::UnitCell & unitCell) pure virtual
Overload to set unit cell directly from UnitCell object.
Implemented in Mantid::CurveFitting::LatticeFunction.
setUnitCell() [2/2]
virtual void Mantid::API::ILatticeFunction::setUnitCell (const std::string & unitCellString) pure virtual
Set the function parameters according to the supplied unit cell.
Implemented in Mantid::CurveFitting::LatticeFunction.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/ILatticeFunction.h
Framework/API/src/ILatticeFunction.cpp