Mantid: Mantid::API::Projection Class Reference
Mantid::API::Projection Class Reference
#include <Projection.h>
Public Member Functions
Kernel::V3D getAxis (size_t nd)
Retrieves the axis vector for the given dimension.
double getOffset (size_t nd)
Retrieves the offset for the given dimension.
ProjectionUnit getUnit (size_t nd)
Retrives the unit of the given dimension.
Projection ()
Default constructor builds identity projection.
Projection (const ITableWorkspace &ws)
Construct from an ITableWorkspace.
Projection (const Kernel::V3D &u, const Kernel::V3D &v)
Three dimensional value constructor, w is the cross product of u and v.
Projection (const Kernel::V3D &u, const Kernel::V3D &v, const Kernel::V3D &w)
Three dimensional value constructor.
void setAxis (size_t nd, const Kernel::V3D &axis)
Set the axis vector for a given dimension.
void setOffset (size_t nd, double offset)
Set the offset for a given dimension.
void setUnit (size_t nd, ProjectionUnit unit)
Set the unit for a given dimension.
Kernel::V3D & U ()
Kernel::V3D & V ()
Kernel::V3D & W ()
virtual ~Projection ()=default
Destructor.
Protected Attributes
Kernel::V3D m_dimensions [3]
The dimensions.
double m_offsets [3]
The offsets for each dimension.
ProjectionUnit m_units [3]
The units for each dimension.
Detailed Description
Definition at line 32 of file Projection.h.
Constructor & Destructor Documentation
Projection() [1/4]
Mantid::API::Projection::Projection ()
Default constructor builds identity projection.
Definition at line 14 of file Projection.cpp.
References m_dimensions, m_offsets, m_units, and Mantid::API::RLU.
Projection() [2/4]
Mantid::API::Projection::Projection (const Kernel::V3D & u, const Kernel::V3D & v)
Three dimensional value constructor, w is the cross product of u and v.
Definition at line 26 of file Projection.cpp.
References Mantid::Kernel::V3D::cross_prod(), m_dimensions, m_offsets, m_units, and Mantid::API::RLU.
Projection() [3/4]
Mantid::API::Projection::Projection (const Kernel::V3D & u, const Kernel::V3D & v, const Kernel::V3D & w)
Three dimensional value constructor.
Definition at line 36 of file Projection.cpp.
References Mantid::Kernel::V3D::cross_prod(), fabs, m_dimensions, m_offsets, m_units, Mantid::API::RLU, and Mantid::Kernel::V3D::scalar_prod().
Projection() [4/4]
Mantid::API::Projection::Projection (const ITableWorkspace & ws)
Construct from an ITableWorkspace.
Definition at line 49 of file Projection.cpp.
References Mantid::API::ITableWorkspace::columnCount(), Mantid::API::ITableWorkspace::getColumn(), index, Mantid::API::INV_ANG, m_dimensions, m_offsets, m_units, Mantid::API::RLU, Mantid::API::ITableWorkspace::rowCount(), and value.
~Projection()
virtual Mantid::API::Projection::~Projection () virtual default
Destructor.
Member Function Documentation
getAxis()
V3D Mantid::API::Projection::getAxis (size_t nd)
Retrieves the axis vector for the given dimension.
Definition at line 104 of file Projection.cpp.
References m_dimensions.
Referenced by export_Projection().
getOffset()
double Mantid::API::Projection::getOffset (size_t nd)
Retrieves the offset for the given dimension.
Definition at line 97 of file Projection.cpp.
References m_offsets.
Referenced by export_Projection().
getUnit()
ProjectionUnit Mantid::API::Projection::getUnit (size_t nd)
Retrives the unit of the given dimension.
Definition at line 111 of file Projection.cpp.
References m_units.
Referenced by Mantid::MDAlgorithms::CutMD::exec().
setAxis()
void Mantid::API::Projection::setAxis (size_t nd, const Kernel::V3D & axis)
Set the axis vector for a given dimension.
Definition at line 125 of file Projection.cpp.
References m_dimensions.
Referenced by export_Projection().
setOffset()
void Mantid::API::Projection::setOffset (size_t nd, double offset)
Set the offset for a given dimension.
Definition at line 118 of file Projection.cpp.
References m_offsets.
Referenced by export_Projection().
setUnit()
void Mantid::API::Projection::setUnit (size_t nd, ProjectionUnit unit)
Set the unit for a given dimension.
Definition at line 132 of file Projection.cpp.
References m_units.
U()
Kernel::V3D & Mantid::API::Projection::U () inline
Definition at line 57 of file Projection.h.
Referenced by Mantid::MDAlgorithms::CutMD::exec(), and export_Projection().
V()
Kernel::V3D & Mantid::API::Projection::V () inline
Definition at line 58 of file Projection.h.
Referenced by Mantid::MDAlgorithms::CutMD::exec(), and export_Projection().
W()
Kernel::V3D & Mantid::API::Projection::W () inline
Definition at line 59 of file Projection.h.
Referenced by Mantid::MDAlgorithms::CutMD::exec(), and export_Projection().
Member Data Documentation
m_dimensions
Kernel::V3D Mantid::API::Projection::m_dimensions[3] protected
The dimensions.
Definition at line 63 of file Projection.h.
Referenced by getAxis(), Projection(), and setAxis().
m_offsets
double Mantid::API::Projection::m_offsets[3] protected
The offsets for each dimension.
Definition at line 65 of file Projection.h.
Referenced by getOffset(), Projection(), and setOffset().
m_units
ProjectionUnit Mantid::API::Projection::m_units[3] protected
The units for each dimension.
Definition at line 67 of file Projection.h.
Referenced by getUnit(), Projection(), and setUnit().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/Projection.h
Framework/API/src/Projection.cpp