Mantid: Mantid::Crystal Namespace Reference
Mantid::Crystal Namespace Reference
Namespaces
namespace CalibrationHelpers
CalibrationHelpers : This contains helper methods to move source, sample and detector positions/rotations for an instrument according to some calibration information.
namespace ConnectedComponentMappingTypes
Namespace containing useful typedefs.
namespace FindSXPeaksHelper
namespace PeakStatisticsTools
namespace Prop
Classes
class AddPeakHKL
AddPeakHKL : Algorithm to add a peaks to a PeaksWorkspace in the HKL frame.
class AnvredCorrection
Calculates anvred correction factors for attenuation due to absorption and scattering in a spherical sample.
class BackgroundStrategy
BackgroundStrategy : Abstract class used for identifying elements of a IMDWorkspace that are not considered background.
class CalculatePeaksHKL
CalculatePeaksHKL : Calculate the HKL value for each peak without any rounding or optimization of the UB Matrix.
class CalculateUMatrix
CalculateUMatrix : Algorithm to calculate the U matrix, given lattice parameters and a list of peaks.
class CentroidPeaks
Find the centroid of single-crystal peaks in a 2D Workspace, in order to refine their positions.
class ClearUB
ClearUB : Clear the UB matrix from a workspace by removing the oriented lattice.
class Cluster
Cluster : Image cluster used by connected component labeling.
class ClusterRegister
ClusterRegister : A fly-weight ICluster regeister.
class CombinePeaksWorkspaces
An algorithm that combines the sets of peaks in two peaks workspaces.
class CompositeCluster
CompositeCluster : Cluster made by by merging other IClusters.
class ConnectedComponentLabeling
ConnectedComponentLabelling : Implements connected component labeling on MDHistoWorkspaces.
class ConvertPeaksWorkspace
ConvertPeaksWorkspace : Bi-directional conversion between a regular PeaksWorkspace (with instrument) and a LeanElasticPeaksWorkspace (no instrument)
class CountReflections
CountReflections.
class DataModeHandler
Integrates each time slice using the BivariateNormal formula, adding the results to the peak object.
class DiffPeaksWorkspaces
An algorithm that subtracts from a workspace (the LHSWorkspace) any peaks that match entries in a second workspace (the RHSWorkspace).
class DisjointElement
DisjointElement : Cluster item used in a disjoint-set data structure.
class FilterPeaks
FilterPeaks : Filter a peaks workspace based on a set number of queries to provide a new, filtered peaks workspace.
class FindClusterFaces
FindClusterFaces : Algorithm to find faces of clusters in an MDHistoWorkspace (image)
class FindSXPeaks
Search detector space for single crystal peaks.
class FindUBUsingFFT
FindUBUsingFFT : Algorithm to calculate a UB matrix using fast Fourier transforms given a list of peaks and bounds on the lattice parameters.
class FindUBUsingIndexedPeaks
FindUBUsingIndexedPeaks : Algorithm to calculate a UB matrix, given a list of peaks that have already been indexed by some means.
class FindUBUsingLatticeParameters
FindUBUsingLatticeParameters : Algorithm to calculate a UB matrix, given lattice parameters and a list of peaks.
class FindUBUsingMinMaxD
FindUBUsingMinMaxD : Algorithm to calculate a UB matrix, given bounds on the lattice parameters and a list of peaks.
class GoniometerAnglesFromPhiRotation
class HardThresholdBackground
HardThresholdBackground : Implementation of BackgroundStrategy using a fixed background signal value as the threshold.
class HasUB
HasUB : Determine if a workspace has a UB matrix on any of it's samples.
class ICluster
ICluster : Abstract cluster.
class ImplClusterRegister
struct index
Peak indexing algorithm, which works by assigning multiple possible HKL values to each peak and then culling these options by comparison with neighbouring peaks.
class IndexPeaks
Implements an algorithm for indexing main and satellites peaks in single crystal peaks.
class IndexSXPeaks
class IntegratePeaksHybrid
IntegratePeaksHybrid : Integrate single crystal peaks algorithm.
class IntegratePeaksUsingClusters
IntegratePeaksUsingClusters : Uses clustering to integrate peaks.
class IntegratePeakTimeSlices
class LoadHKL
LoadHKL : Load an ISAW-style .hkl file into a PeaksWorkspace.
class LoadIsawPeaks
Load an ISAW-style .peaks or .integrate file into a PeaksWorkspace.
class LoadIsawSpectrum
Load incident spectrum and detector efficiency correction file.
class LoadIsawUB
Algorithm to load an ISAW-style ASCII UB matrix and lattice parameters file, and place its information into a workspace.
class MaskPeaksWorkspace
Find the offsets for each detector.
struct ModulationProperties
Tie together the names of the properties for the modulation vectors.
class NormaliseVanadium
Calculates anvred correction factors for attenuation due to absorption and scattering in a spherical sample.
class OptimizeCrystalPlacement
OptimizeCrystalPlacement.
class OptimizeLatticeForCellType
Find the offsets for each detector.
class OrEnabledWhenProperties
class PeakBackground
PeakBackground : Extension of HardThresholdBackground to consider regions of the image as background if they are outside the peaks radius limits (no mater what their theshold is).
class PeakCandidate
class PeakClusterProjection
PeakClusterProjection : Maps peaks onto IMDHistoWorkspaces and returns the signal value at the peak center.
class PeakHKLErrors
class PeakIntegration
Find the offsets for each detector.
class PeakIntensityVsRadius
Calculate the integrated intensity of peaks vs integration radius.
class PeaksInRegion
PeaksInRegion : Find peaks that are either inside a box region, or that have a radius of sufficent size, that they intersect the box.
class PeaksIntersection
PeaksIntersection : Abstract base algorithm class for algorithms that identify peaks interacting with one or more surfaces i.e.
class PeaksOnSurface
PeaksOnSurface : Check peak workspace interaction with a single surface.
class PredictFractionalPeaks
Using a set of offset vectors, either provided as separate lists or as a set of vectors, predict whether.
class PredictPeaks
Using a known crystal lattice and UB matrix, predict where single crystal peaks should be found in detector/TOF space.
class PredictSatellitePeaks
PredictSatellitePeaks : Algorithm to create a PeaksWorkspace with peaks corresponding to fractional h,k,and l values.
class SaveHKL
Save a PeaksWorkspace to a Gsas-style ASCII .hkl file.
class SaveIsawPeaks
Save a PeaksWorkspace to a ISAW-style ASCII .peaks file.
class SaveIsawUB
Algorithm to save a UB matrix and lattice parameters to an ISAW-style ASCII file.
class SaveLauenorm
Save a PeaksWorkspace to a lauenorm format http://www.ccp4.ac.uk/cvs/viewvc.cgi/laue/doc/lauenorm.ptx?diff_format=s&revision=1.1.1.1&view=markup.
class SCDCalibratePanels
SCDCalibratePanels calibrates instrument parameters for Rectangular Detectors.
class SCDCalibratePanels2
SCDCalibratePanels2 : Using input peakworkspace with indexation results to calibrate each individual panels.
class SCDCalibratePanels2ObjFunc
SCDCalibratePanels2ObjFunc : TODO: DESCRIPTION.
class SCDPanelErrors
class SelectCellOfType
ShowPossibleCells : Algorithm to display a list of possible conventional cells corresponding to the UB saved in the sample associated with the specified PeaksWorkspace, provided the saved UB is for a Niggli reduced cell.
class SelectCellWithForm
ShowPossibleCells : Algorithm to display a list of possible conventional cells corresponding to the UB saved in the sample associated with the specified PeaksWorkspace, provided the saved UB is for a Niggli reduced cell.
class SetCrystalLocation
SetCrystalLocation.
class SetGoniometer
Define the goniometer used in an experiment by giving the axes and directions of rotations.
class SetSpecialCoordinates
SetSpecialCoordinates :
class SetUB
SetUB : Algorithm to set the UB matrix, given lattice parameters and u and v vectors as defined in: http://horace.isis.rl.ac.uk/Getting_started.
class ShowPeakHKLOffsets
class ShowPossibleCells
ShowPossibleCells : Algorithm to display a list of possible conventional cells corresponding to the UB saved in the sample associated with the specified PeaksWorkspace, provided the saved UB is for a Niggli reduced cell.
class SortHKL
Save a PeaksWorkspace to a Gsas-style ASCII .hkl file.
class SortPeaksWorkspace
SortPeaksWorkspace : Sort a PeaksWorkspace by a range of properties.
class StatisticsOfPeaksWorkspace
Statistics of a PeaksWorkspace.
class TransformHKL
TransformHKL : Algorithm to adjust the UB saved in the sample associated with the specified PeaksWorkspace, so the HKL values are reordered or otherwise transformed.
Typedefs
using MNPOffset = std::tuple< double, double, double, Kernel::V3D >
Tie together a modulated peak number with its offset.
using peakvector = std::vector< FindSXPeaksHelper::SXPeak >
using VecV3D = std::vector< Mantid::Kernel::V3D >
using VecVecV3D = std::vector< VecV3D >
Functions
std::vector< Kernel::V3D > addModulationVectors (const std::vector< double > &modVector1, const std::vector< double > &modVector2, const std::vector< double > &modVector3)
Create a list of valid modulation vectors from the input.
std::vector< MNPOffset > generateOffsetVectors (const std::vector< double > &hOffsets, const std::vector< double > &kOffsets, const std::vector< double > &lOffsets)
Calculate a list of HKL offsets from the given lists of offsets.
std::vector< MNPOffset > generateOffsetVectors (const std::vector< Kernel::V3D > &modVectors, const int maxOrder, const bool crossTerms)
Calculate a list of HKL offsets from the given modulation vectors.
bool MANTID_CRYSTAL_DLL lineIntersectsSphere (const Mantid::Kernel::V3D &line, const Mantid::Kernel::V3D &lineStart, const Mantid::Kernel::V3D &peakCenter, const double peakRadius)
Non-member helper function.
V3D makeV3DFromVector (const VecDouble &vec)
double qConventionFactor ()
convenience overload to pull the convention from the config service
double qConventionFactor (const std::string &convention)
return -1 if convention is "Crystallography" and 1 otherwise.
double SQRT (double v)
void unionElements (DisjointElement *a, DisjointElement *b)
Convenience non-member function.
std::vector< Kernel::V3D > validModulationVectors (const std::vector< double > &modVector1, const std::vector< double > &modVector2, const std::vector< double > &modVector3)
Create a list of valid modulation vectors from the input.
void writeXmlParameter (ofstream &ostream, const string &name, const double value)
Variables
const double MAX_WAVELENGTH = 50.0
const int MIN_INDEXED_PEAKS = 3
const size_t NUM_AXES = 6
How many axes (max) to define.
const int NUM_WAVELENGTHS = static_cast<int>(std::ceil(MAX_WAVELENGTH * STEPS_PER_ANGSTROM))
const double pc [8][19]
const double radtodeg = 180.0 / M_PI
const double radtodeg_half = 180.0 / M_PI / 2.
const double STEPS_PER_ANGSTROM = 100
Typedef Documentation
MNPOffset
using Mantid::Crystal::MNPOffset = typedef std::tuple<double, double, double, Kernel::V3D>
Tie together a modulated peak number with its offset.
Definition at line 23 of file PeakAlgorithmHelpers.h.
peakvector
using Mantid::Crystal::peakvector = typedef std::vector<FindSXPeaksHelper::SXPeak>
Definition at line 23 of file FindSXPeaks.h.
VecV3D
using Mantid::Crystal::VecV3D = typedef std::vector<Mantid::Kernel::V3D>
Definition at line 16 of file PeaksIntersection.h.
VecVecV3D
using Mantid::Crystal::VecVecV3D = typedef std::vector<VecV3D>
Definition at line 17 of file PeaksIntersection.h.
Function Documentation
addModulationVectors()
std::vector< Kernel::V3D > Mantid::Crystal::addModulationVectors (const std::vector< double > & modVector1, const std::vector< double > & modVector2, const std::vector< double > & modVector3)
Create a list of valid modulation vectors from the input.
Direct add modulation a list to return.
Parameters
modVector1 List of 3 doubles specifying an offset
modVector2 List of 3 doubles specifying an offset
modVector3 List of 3 doubles specifying an offset
Returns
A list of valid modulation vectors
Definition at line 107 of file PeakAlgorithmHelpers.cpp.
References modVectors.
generateOffsetVectors() [1/2]
std::vector< MNPOffset > Mantid::Crystal::generateOffsetVectors (const std::vector< double > & hOffsets, const std::vector< double > & kOffsets, const std::vector< double > & lOffsets)
Calculate a list of HKL offsets from the given lists of offsets.
The final offset vector is computed as (hoffsets[i],koffsets[j],loffsets[k]) for each combination of i,j,k.
All offsets are considered order 1
Parameters
hOffsets A list of offsets in the h direction
kOffsets A list of offsets in the k direction
lOffsets A list of offsets in the l direction
Returns
A list of (1, 1, 1, V3D) were m,n,p specifies the modulation structure number and V3D specifies the offset to be tested
Definition at line 200 of file PeakAlgorithmHelpers.cpp.
generateOffsetVectors() [2/2]
std::vector< MNPOffset > Mantid::Crystal::generateOffsetVectors (const std::vector< Kernel::V3D > & modVectors, const int maxOrder, const bool crossTerms)
Calculate a list of HKL offsets from the given modulation vectors.
Parameters
maxOrder Integer specifying the multiples of the modulation vector.
modVectors A list of modulation vectors form the user
crossTerms If true then compute products of the modulation vectors
Returns
A list of (m, n, p, V3D) were m,n,p specifies the modulation structure number and V3D specifies the offset to be tested
Definition at line 128 of file PeakAlgorithmHelpers.cpp.
References crossTerms, Mantid::Geometry::m, maxOrder, modVectors, and n.
Referenced by Mantid::Crystal::ModulationProperties::create(), and Mantid::Crystal::PredictFractionalPeaks::getModulationInfo().
lineIntersectsSphere()
bool Mantid::Crystal::lineIntersectsSphere (const Mantid::Kernel::V3D & line, const Mantid::Kernel::V3D & lineStart, const Mantid::Kernel::V3D & peakCenter, const double peakRadius)
Non-member helper function.
Definition at line 88 of file PeaksOnSurface.cpp.
References lineStart, Mantid::Kernel::V3D::norm(), Mantid::Kernel::normalize(), and Mantid::Kernel::V3D::scalar_prod().
Referenced by Mantid::Crystal::PeaksOnSurface::pointInsideAllExtents().
makeV3DFromVector()
V3D Mantid::Crystal::makeV3DFromVector (const VecDouble & vec)
Definition at line 177 of file PeaksOnSurface.cpp.
Referenced by Mantid::Crystal::PeaksOnSurface::exec().
qConventionFactor() [1/2]
double Mantid::Crystal::qConventionFactor ()
convenience overload to pull the convention from the config service
Returns
qConventionFactor for Q.convention setting in ConfigService
Definition at line 36 of file PeakAlgorithmHelpers.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and qConventionFactor().
Referenced by Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingPeaksWorkspace(), and qConventionFactor().
qConventionFactor() [2/2]
double Mantid::Crystal::qConventionFactor (const std::string & convention)
return -1 if convention is "Crystallography" and 1 otherwise.
Returns
-1 if Q.convention==Crystallography, else return 1.0
Definition at line 26 of file PeakAlgorithmHelpers.cpp.
SQRT()
double Mantid::Crystal::SQRT (double v)
Definition at line 134 of file IntegratePeakTimeSlices.cpp.
Referenced by Mantid::Crystal::IntegratePeakTimeSlices::CalculateIsawIntegrateError(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), and Mantid::Crystal::IntegratePeakTimeSlices::UpdateOutputWS().
unionElements()
void Mantid::Crystal::unionElements (DisjointElement * a, DisjointElement * b)
Convenience non-member function.
Parameters
a : Pointer to first disjoint element to join
b : Pointer to second disjoint element to join
Definition at line 154 of file DisjointElement.cpp.
References Mantid::Crystal::DisjointElement::unionWith().
validModulationVectors()
std::vector< Kernel::V3D > Mantid::Crystal::validModulationVectors (const std::vector< double > & modVector1, const std::vector< double > & modVector2, const std::vector< double > & modVector3)
Create a list of valid modulation vectors from the input.
Check each input is a valid modulation and add it to a list to return.
Parameters
modVector1 List of 3 doubles specifying an offset
modVector2 List of 3 doubles specifying an offset
modVector3 List of 3 doubles specifying an offset
Returns
A list of valid modulation vectors
Definition at line 86 of file PeakAlgorithmHelpers.cpp.
References modVectors.
Referenced by Mantid::Crystal::ModulationProperties::create(), and Mantid::Crystal::PredictFractionalPeaks::validateInputs().
writeXmlParameter()
void Mantid::Crystal::writeXmlParameter (ofstream & ostream, const string & name, const double value)
Definition at line 503 of file SCDCalibratePanels.cpp.
References value.
Referenced by Mantid::Crystal::SCDCalibratePanels::saveXmlFile().
Variable Documentation
MAX_WAVELENGTH
const double Mantid::Crystal::MAX_WAVELENGTH = 50.0
Definition at line 48 of file AnvredCorrection.h.
MIN_INDEXED_PEAKS
const int Mantid::Crystal::MIN_INDEXED_PEAKS = 3
Definition at line 25 of file FindUBUsingIndexedPeaks.cpp.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec().
NUM_AXES
const size_t Mantid::Crystal::NUM_AXES = 6
How many axes (max) to define.
Definition at line 31 of file SetGoniometer.cpp.
Referenced by Mantid::Crystal::SetGoniometer::exec(), and Mantid::Crystal::SetGoniometer::init().
NUM_WAVELENGTHS
const int Mantid::Crystal::NUM_WAVELENGTHS = static_cast<int>(std::ceil(MAX_WAVELENGTH * STEPS_PER_ANGSTROM))
Definition at line 52 of file AnvredCorrection.h.
Referenced by Mantid::Crystal::AnvredCorrection::BuildLamdaWeights().
pc
const double Mantid::Crystal::pc[8][19]
Initial value:
= {{-6.4910e-07, -6.8938e-07, -7.8149e-07, 8.1682e-08, 1.8008e-06, 3.3916e-06, 4.5095e-06,
                           4.7970e-06, 4.4934e-06, 3.6700e-06, 2.5881e-06, 1.5007e-06, 3.7669e-07, -7.9487e-07,
                           -1.7935e-06, -2.5563e-06, -3.1113e-06, -3.3993e-06, -3.5091e-06},
                          {1.0839e-05, 1.1582e-05, 1.1004e-05, -2.2848e-05, -8.1974e-05, -1.3268e-04, -1.6486e-04,
                           -1.6839e-04, -1.5242e-04, -1.1949e-04, -7.8682e-05, -3.7973e-05, 2.9117e-06, 4.4823e-05,
                           8.0464e-05, 1.0769e-04, 1.2753e-04, 1.3800e-04, 1.4190e-04},
                          {8.7140e-05, 9.0870e-05, 1.6706e-04, 6.9008e-04, 1.4781e-03, 2.0818e-03, 2.3973e-03,
                           2.3209e-03, 1.9935e-03, 1.4508e-03, 8.1903e-04, 1.9608e-04, -4.1128e-04, -1.0205e-03,
                           -1.5374e-03, -1.9329e-03, -2.2212e-03, -2.3760e-03, -2.4324e-03},
                          {-2.9549e-03, -3.1360e-03, -4.2431e-03, -8.1103e-03, -1.2989e-02, -1.6012e-02, -1.6815e-02,
                           -1.4962e-02, -1.1563e-02, -6.8581e-03, -1.7302e-03, 3.2400e-03, 7.9409e-03, 1.2528e-02,
                           1.6414e-02, 1.9394e-02, 2.1568e-02, 2.2758e-02, 2.3182e-02},
                          {1.7934e-02, 1.9304e-02, 2.4706e-02, 3.6759e-02, 4.8351e-02, 5.1049e-02, 4.5368e-02,
                           3.0864e-02, 1.2086e-02, -1.0254e-02, -3.2992e-02, -5.4495e-02, -7.4205e-02, -9.2818e-02,
                           -1.0855e-01, -1.2068e-01, -1.2954e-01, -1.3451e-01, -1.3623e-01},
                          {6.2799e-02, 6.3892e-02, 6.4943e-02, 6.4881e-02, 7.2169e-02, 9.5669e-02, 1.3082e-01,
                           1.7694e-01, 2.2559e-01, 2.7655e-01, 3.2483e-01, 3.6888e-01, 4.0783e-01, 4.4330e-01,
                           4.7317e-01, 4.9631e-01, 5.1334e-01, 5.2318e-01, 5.2651e-01},
                          {-1.4949e+00, -1.4952e+00, -1.4925e+00, -1.4889e+00, -1.4867e+00, -1.4897e+00, -1.4948e+00,
                           -1.5025e+00, -1.5084e+00, -1.5142e+00, -1.5176e+00, -1.5191e+00, -1.5187e+00, -1.5180e+00,
                           -1.5169e+00, -1.5153e+00, -1.5138e+00, -1.5125e+00, -1.5120e+00},
                          {0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
                           0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
                           0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00}}
Definition at line 23 of file AnvredCorrection.h.
Referenced by Mantid::Crystal::AnvredCorrection::calc_Astar(), and Mantid::Crystal::LoadHKL::exec().
radtodeg
const double Mantid::Crystal::radtodeg = 180.0 / M_PI
Definition at line 54 of file AnvredCorrection.h.
Referenced by Mantid::Crystal::AnvredCorrection::absor_sphere(), Mantid::Crystal::SaveHKL::absorbSphere(), Mantid::Crystal::AnvredCorrection::calc_Astar(), and Mantid::Crystal::LoadHKL::exec().
radtodeg_half
const double Mantid::Crystal::radtodeg_half = 180.0 / M_PI / 2.
Definition at line 18 of file NormaliseVanadium.h.
STEPS_PER_ANGSTROM
const double Mantid::Crystal::STEPS_PER_ANGSTROM = 100
Definition at line 50 of file AnvredCorrection.h.
Referenced by Mantid::Crystal::AnvredCorrection::BuildLamdaWeights(), and Mantid::Crystal::AnvredCorrection::getEventWeight().