Mantid: Mantid::CurveFitting::Functions::CrystalFieldSpectrum Class Reference
Mantid::CurveFitting::Functions::CrystalFieldSpectrum Class Reference
Calculates crystal field spectrum.
#include <CrystalFieldSpectrum.h>
Public Member Functions
void buildTargetFunction () const override
Uses m_crystalField to calculate peak centres and intensities then populates m_spectrum with peaks of type given in PeakShape attribute.
const std::string category () const override
The categories the Fit function belong to.
CrystalFieldSpectrum ()
Constructor.
void init () override
overwrite IFunction base class method, which declare function parameters
std::string name () const override
Returns the function's name.
Public Member Functions inherited from Mantid::API::FunctionGenerator
FunctionGenerator (const IFunction_sptr &source)
Constructor.
size_t nAttributes () const override
Returns the number of attributes associated with the function.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names.
Attribute getAttribute (const std::string &name) const override
Return a value of attribute attName.
void setAttribute (const std::string &name, const Attribute &) override
Set a value to attribute attName.
bool hasAttribute (const std::string &name) const override
Check if attribute attName exists.
std::string attributeName (size_t i) const override
Return the name of the ith attribute.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluate the function.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
double getParameter (size_t i) const override
Get i-th parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
double getParameter (const std::string &name) const override
Get parameter by name.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
size_t nParams () const override
Total number of parameters.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
void setUpForFit () override
Set up the function for a fit.
ParameterTie * getTie (size_t i) const override
Get the tie for i-th parameter.
IConstraint * getConstraint (size_t i) const override
Get the i-th constraint.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void function (const FunctionDomain &domain, FunctionValues &values) const =0
Evaluates the function for all arguments in the domain.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies ()
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Protected Member Functions
void updateTargetFunction () const override
Update m_spectrum function.
std::string writeToString (const std::string &parentLocalAttributesStr="") const override
Custom string conversion method.
Protected Member Functions inherited from Mantid::API::FunctionGenerator
void setSource (IFunction_sptr source) const
Set the source function.
virtual bool isSourceName (const std::string &aName) const
Test if a name (parameter's or attribute's) belongs to m_source.
void checkTargetFunction () const
Update target function if necessary.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
Private Attributes
size_t m_nPeaks
Number of fitted peaks in the spectrum.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Attributes inherited from Mantid::API::FunctionGenerator
IFunction_sptr m_source
Function that calculates parameters of the target function.
IFunction_sptr m_target
Function that actually calculates the output.
size_t m_nOwnParams
Cached number of parameters in m_source.
bool m_dirty
Flag indicating that updateTargetFunction() is required.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
Calculates crystal field spectrum.
Definition at line 18 of file CrystalFieldSpectrum.h.
Constructor & Destructor Documentation
CrystalFieldSpectrum()
Mantid::CurveFitting::Functions::CrystalFieldSpectrum::CrystalFieldSpectrum ()
Constructor.
Definition at line 35 of file CrystalFieldSpectrum.cpp.
Member Function Documentation
buildTargetFunction()
void Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction () const override virtual
Uses m_crystalField to calculate peak centres and intensities then populates m_spectrum with peaks of type given in PeakShape attribute.
Implements Mantid::API::FunctionGenerator.
Definition at line 56 of file CrystalFieldSpectrum.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asInt(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asVector(), Mantid::CurveFitting::Functions::CrystalFieldUtils::buildSpectrumFunction(), Mantid::API::FunctionGenerator::getAttribute(), Mantid::API::FunctionGenerator::m_dirty, m_nPeaks, Mantid::API::FunctionGenerator::m_source, Mantid::API::FunctionGenerator::m_target, Mantid::API::FunctionValues::size(), and Mantid::API::IFunction::storeReadOnlyAttribute().
Referenced by init(), and updateTargetFunction().
category()
const std::string Mantid::CurveFitting::Functions::CrystalFieldSpectrum::category () const inline override virtual
The categories the Fit function belong to.
Categories must be listed as a semi colon separated list. For example: "General, Muon\\Custom" which adds a function to the category "General" and the sub-category "Muon\\Custom"
Reimplemented from Mantid::API::IFunction.
Definition at line 24 of file CrystalFieldSpectrum.h.
init()
void Mantid::CurveFitting::Functions::CrystalFieldSpectrum::init () override virtual
overwrite IFunction base class method, which declare function parameters
Reimplemented from Mantid::API::FunctionGenerator.
Definition at line 46 of file CrystalFieldSpectrum.cpp.
References buildTargetFunction(), Mantid::Kernel::Logger::error(), and Mantid::API::g_log.
name()
std::string Mantid::CurveFitting::Functions::CrystalFieldSpectrum::name () const inline override virtual
Returns the function's name.
Implements Mantid::API::IFunction.
Definition at line 23 of file CrystalFieldSpectrum.h.
Referenced by writeToString().
updateTargetFunction()
void Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction () const override protected virtual
Update m_spectrum function.
Implements Mantid::API::FunctionGenerator.
Definition at line 89 of file CrystalFieldSpectrum.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asVector(), buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldUtils::calculateNPeaks(), Mantid::API::FunctionGenerator::getAttribute(), Mantid::API::FunctionGenerator::m_dirty, m_nPeaks, Mantid::API::FunctionGenerator::m_source, Mantid::API::FunctionGenerator::m_target, Mantid::API::IFunction::storeReadOnlyAttribute(), and Mantid::CurveFitting::Functions::CrystalFieldUtils::updateSpectrumFunction().
writeToString()
std::string Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString (const std::string & parentLocalAttributesStr = "") const override protected virtual
Custom string conversion method.
Reimplemented from Mantid::API::IFunction.
Definition at line 113 of file CrystalFieldSpectrum.cpp.
References Mantid::API::FunctionGenerator::getAttribute(), Mantid::API::IFunction::getAttributeNames(), Mantid::API::FunctionGenerator::getAttributeNames(), Mantid::API::FunctionGenerator::getParameter(), Mantid::API::IFunction::isActive(), Mantid::API::IFunction::isFixed(), Mantid::Kernel::Strings::join(), Mantid::API::FunctionGenerator::m_nOwnParams, m_nPeaks, name(), Mantid::API::FunctionGenerator::parameterName(), Mantid::API::IFunction::tie(), Mantid::API::IFunction::Attribute::value(), Mantid::API::IFunction::writeConstraints(), and Mantid::API::IFunction::writeTies().
Member Data Documentation
m_nPeaks
size_t Mantid::CurveFitting::Functions::CrystalFieldSpectrum::m_nPeaks mutable private
Number of fitted peaks in the spectrum.
Definition at line 33 of file CrystalFieldSpectrum.h.
Referenced by buildTargetFunction(), updateTargetFunction(), and writeToString().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldSpectrum.h
Framework/CurveFitting/src/Functions/CrystalFieldSpectrum.cpp