Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask Class Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask Class Reference
#include <ProcessBankSplitFullTimeTask.h>
Public Member Functions
void operator() (const tbb::blocked_range< size_t > &range) const
ProcessBankSplitFullTimeTask (std::vector< std::string > &bankEntryNames, H5::H5File &h5file, const bool is_time_filtered, std::vector< int > &workspaceIndices, std::vector< API::MatrixWorkspace_sptr > &wksps, const std::map< detid_t, double > &calibration, const std::map< detid_t, double > &scale_at_sample, const std::map< size_t, std::vector< detid_t > > &grouping, const std::set< detid_t > &masked, const size_t events_per_chunk, const size_t grainsize_event, const std::vector< PulseROI > &pulse_indices, const std::map< Mantid::Types::Core::DateAndTime, int > &splitterMap, std::shared_ptr< API::Progress > &progress)
ProcessBankSplitFullTimeTask (std::vector< std::string > &bankEntryNames, H5::H5File &h5file, std::shared_ptr< NexusLoader > loader, std::vector< int > &workspaceIndices, std::vector< API::MatrixWorkspace_sptr > &wksps, const std::map< detid_t, double > &calibration, const std::map< detid_t, double > &scale_at_sample, const std::map< size_t, std::vector< detid_t > > &grouping, const std::set< detid_t > &masked, const size_t events_per_chunk, const size_t grainsize_event, const std::map< Mantid::Types::Core::DateAndTime, int > &splitterMap, std::shared_ptr< API::Progress > &progress)
Private Attributes
const std::vector< std::string > m_bankEntries
const std::map< detid_t, double > m_calibration
const size_t m_events_per_chunk
number of events to read from disk at one time
const size_t m_grainsize_event
number of events to histogram in a single thread
const std::map< size_t, std::vector< detid_t > > m_grouping
detector ids for output spectrum number
H5::H5File m_h5file
std::shared_ptr< NexusLoader > m_loader
const std::set< detid_t > m_masked
std::shared_ptr< API::Progress > m_progress
std::map< detid_t, double > m_scale_at_sample
multiplicative 0<value<1 to move neutron TOF at sample
const std::map< Mantid::Types::Core::DateAndTime, int > m_splitterMap
std::vector< API::MatrixWorkspace_sptr > m_wksps
std::vector< int > m_workspaceIndices
Detailed Description
Definition at line 26 of file ProcessBankSplitFullTimeTask.h.
Constructor & Destructor Documentation
ProcessBankSplitFullTimeTask() [1/2]
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::ProcessBankSplitFullTimeTask (std::vector< std::string > & bankEntryNames, H5::H5File & h5file, const bool is_time_filtered, std::vector< int > & workspaceIndices, std::vector< API::MatrixWorkspace_sptr > & wksps, const std::map< detid_t, double > & calibration, const std::map< detid_t, double > & scale_at_sample, const std::map< size_t, std::vector< detid_t > > & grouping, const std::set< detid_t > & masked, const size_t events_per_chunk, const size_t grainsize_event, const std::vector< PulseROI > & pulse_indices, const std::map< Mantid::Types::Core::DateAndTime, int > & splitterMap, std::shared_ptr< API::Progress > & progress)
Definition at line 32 of file ProcessBankSplitFullTimeTask.cpp.
ProcessBankSplitFullTimeTask() [2/2]
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::ProcessBankSplitFullTimeTask (std::vector< std::string > & bankEntryNames, H5::H5File & h5file, std::shared_ptr< NexusLoader > loader, std::vector< int > & workspaceIndices, std::vector< API::MatrixWorkspace_sptr > & wksps, const std::map< detid_t, double > & calibration, const std::map< detid_t, double > & scale_at_sample, const std::map< size_t, std::vector< detid_t > > & grouping, const std::set< detid_t > & masked, const size_t events_per_chunk, const size_t grainsize_event, const std::map< Mantid::Types::Core::DateAndTime, int > & splitterMap, std::shared_ptr< API::Progress > & progress)
Definition at line 45 of file ProcessBankSplitFullTimeTask.cpp.
Member Function Documentation
operator()()
void Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator() (const tbb::blocked_range< size_t > & range) const
Definition at line 57 of file ProcessBankSplitFullTimeTask.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::DETID(), Mantid::API::g_log, m_bankEntries, m_calibration, m_events_per_chunk, m_grainsize_event, m_h5file, m_loader, m_masked, m_progress, m_scale_at_sample, m_wksps, m_workspaceIndices, maxval, minval, Mantid::Kernel::parallel_minmax(), Mantid::Nexus::H5Util::readStringAttribute(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::TIME_OF_FLIGHT(), and Mantid::Kernel::Units::timeConversionValue().
Member Data Documentation
m_bankEntries
const std::vector<std::string> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_bankEntries private
Definition at line 51 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_calibration
const std::map<detid_t, double> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_calibration private
Definition at line 55 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_events_per_chunk
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_events_per_chunk private
number of events to read from disk at one time
Definition at line 60 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_grainsize_event
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_grainsize_event private
number of events to histogram in a single thread
Definition at line 63 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_grouping
const std::map<size_t, std::vector<detid_t> > Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_grouping private
detector ids for output spectrum number
Definition at line 57 of file ProcessBankSplitFullTimeTask.h.
m_h5file
H5::H5File Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_h5file private
Definition at line 50 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_loader
std::shared_ptr<NexusLoader> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_loader private
Definition at line 52 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_masked
const std::set<detid_t> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_masked private
Definition at line 58 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_progress
std::shared_ptr<API::Progress> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_progress private
Definition at line 64 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_scale_at_sample
std::map<detid_t, double> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_scale_at_sample private
multiplicative 0<value<1 to move neutron TOF at sample
Definition at line 56 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_splitterMap
const std::map<Mantid::Types::Core::DateAndTime, int> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_splitterMap private
Definition at line 61 of file ProcessBankSplitFullTimeTask.h.
m_wksps
std::vector<API::MatrixWorkspace_sptr> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_wksps private
Definition at line 54 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
m_workspaceIndices
std::vector<int> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::m_workspaceIndices private
Definition at line 53 of file ProcessBankSplitFullTimeTask.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim/ProcessBankSplitFullTimeTask.h
Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankSplitFullTimeTask.cpp