Mantid: Mantid::DataHandling::LoadILLDiffraction Class Reference
Mantid::DataHandling::LoadILLDiffraction Class Reference
LoadILLDiffraction : Loads ILL diffraction nexus files.
#include <LoadILLDiffraction.h>
Classes
struct ScannedVariables
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
int confidence (Nexus::NexusDescriptorLazy &descriptor) const override
Returns confidence.
LoadILLDiffraction ()
Constructor.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Types
enum ScanType : size_t { NoScan = 0 , DetectorScan = 1 , OtherScan = 2 }
Private Member Functions
void calculateRelativeRotations (std::vector< double > &instrumentAngles, const Kernel::V3D &firstTubePosition)
Convert from absolute rotation angle, around the sample, of tube 1, to a relative rotation angle around the sample.
void computeThetaOffset ()
Computes the 2theta offset of the decoder for D20.
void convertAxisAndTranspose ()
the 2theta offset for D20 to account for dead pixels
void exec () override
Executes the algorithm.
void fillDataScanMetaData (const Nexus::NXDouble &)
Creates time series sample logs for the scanned variables.
void fillMovingInstrumentScan (const Nexus::NXInt &, const Nexus::NXDouble &)
Fills the counts for the instrument with moving detectors.
void fillStaticInstrumentScan (const Nexus::NXInt &, const Nexus::NXDouble &, const double &)
Fills the loaded data to the workspace when the detector is not moving during the run, but can be moved before.
std::vector< Types::Core::DateAndTime > getAbsoluteTimes (const Nexus::NXDouble &) const
Returns the vector of absolute times for each scan point.
std::vector< double > getAxis (const Nexus::NXDouble &) const
Returns the x-axis.
std::vector< double > getDurations (const Nexus::NXDouble &) const
Returns the durations in seconds for each scan point.
std::string getInstrumentFilePath (const std::string &) const
Makes up the full path of the relevant IDF dependent on resolution mode.
std::vector< double > getMonitor (const Nexus::NXDouble &) const
Returns the monitor spectrum.
Kernel::V3D getReferenceComponentPosition (const API::MatrixWorkspace_sptr &instrumentWorkspace)
Get the position of the component in the workspace which corresponds to the angle stored in the scanned variables of the NeXus files.
std::vector< double > getScannedVaribleByPropertyName (const Nexus::NXDouble &scan, const std::string &propertyName) const
Gets a scanned variable based on its property type in the scanned_variables block.
void init () override
Initialize the algorithm's properties.
void initMovingWorkspace (const Nexus::NXDouble &scan)
Use the ScanningWorkspaceBuilder to create a time indexed workspace.
void initStaticWorkspace ()
Initializes the output workspace based on the resolved instrument, scan points, and scan type.
void loadDataScan ()
Loads the scanned detector data.
void loadMetaData ()
Dumps the metadata from the whole file to SampleLogs.
void loadScanVars ()
Loads the scanned_variables/variables_names block.
void moveTwoThetaZero (double)
Rotates the detector to the 2theta0 read from the file.
void resolveInstrument ()
Resolves the instrument based on instrument name and resolution mode.
void resolveScanType ()
Resolves the scan type.
void setSampleLogs ()
Adds some sample logs needed later by reduction.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
Private Attributes
std::string m_filename
file name to load
std::string m_instName
instrument name to load the IDF
std::set< std::string > m_instNames
supported instruments
double m_maxHeight {0.}
maximum absolute height of the D2B tubes
size_t m_numberDetectorsActual
number of cells actually active
size_t m_numberDetectorsRead
number of cells read from file
size_t m_numberScanPoints
number of scan points
double m_offsetTheta {0.}
API::MatrixWorkspace_sptr m_outWorkspace
output workspace
double m_pixelHeight {0.}
height of the pixel in D2B
size_t m_resolutionMode
resolution mode; 1:low, 2:nominal, 3:high
ScanType m_scanType
NoScan, DetectorScan or OtherScan.
std::vector< ScannedVariables > m_scanVar
holds the scan info
size_t m_sizeDim1
size of dim1, number of tubes (D2B) or the whole detector (D20)
size_t m_sizeDim2
size of dim2, number of pixels (1 for D20!)
Types::Core::DateAndTime m_startTime
start time of acquisition
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadILLDiffraction : Loads ILL diffraction nexus files.
Date
15/05/17
Definition at line 25 of file LoadILLDiffraction.h.
Member Enumeration Documentation
ScanType
enum Mantid::DataHandling::LoadILLDiffraction::ScanType : size_t private
Enumerator
NoScan
DetectorScan
OtherScan
Definition at line 36 of file LoadILLDiffraction.h.
Constructor & Destructor Documentation
LoadILLDiffraction()
Mantid::DataHandling::LoadILLDiffraction::LoadILLDiffraction ()
Constructor.
Definition at line 93 of file LoadILLDiffraction.cpp.
Member Function Documentation
calculateRelativeRotations()
void Mantid::DataHandling::LoadILLDiffraction::calculateRelativeRotations (std::vector< double > & tubeRotations, const Kernel::V3D & firstTubePosition) private
Convert from absolute rotation angle, around the sample, of tube 1, to a relative rotation angle around the sample.
Parameters
tubeRotations Input is the absolute rotations around the sample of tube 1, output is the relative rotations required from the IDF for all detectors
firstTubePosition A V3D object containing the position of the first tube
Definition at line 403 of file LoadILLDiffraction.cpp.
References Mantid::Kernel::V3D::angle(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_instName, and m_offsetTheta.
Referenced by initMovingWorkspace().
category()
const std::string Mantid::DataHandling::LoadILLDiffraction::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 85 of file LoadILLDiffraction.cpp.
computeThetaOffset()
void Mantid::DataHandling::LoadILLDiffraction::computeThetaOffset () private
Computes the 2theta offset of the decoder for D20.
Definition at line 788 of file LoadILLDiffraction.cpp.
References m_offsetTheta, and m_resolutionMode.
Referenced by loadDataScan().
confidence()
int Mantid::DataHandling::LoadILLDiffraction::confidence (Nexus::NexusDescriptorLazy & descriptor) const override virtual
Returns confidence.
See also
IFileLoader::confidence
Implements Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >.
Definition at line 65 of file LoadILLDiffraction.cpp.
convertAxisAndTranspose()
void Mantid::DataHandling::LoadILLDiffraction::convertAxisAndTranspose () private
the 2theta offset for D20 to account for dead pixels
Converts the spectrum axis to 2theta and transposes the workspace.
Definition at line 796 of file LoadILLDiffraction.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), and m_outWorkspace.
Referenced by exec().
exec()
void Mantid::DataHandling::LoadILLDiffraction::exec () override private virtual
Executes the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 118 of file LoadILLDiffraction.cpp.
References convertAxisAndTranspose(), DetectorScan, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), loadDataScan(), loadMetaData(), loadScanVars(), m_filename, m_instName, m_outWorkspace, m_scanType, m_scanVar, Mantid::API::Algorithm::progress(), Mantid::Kernel::IPropertyManager::setProperty(), and setSampleLogs().
fillDataScanMetaData()
void Mantid::DataHandling::LoadILLDiffraction::fillDataScanMetaData (const Nexus::NXDouble & scan) private
Creates time series sample logs for the scanned variables.
Parameters
scan : scan data
Definition at line 531 of file LoadILLDiffraction.cpp.
References getAbsoluteTimes(), m_numberScanPoints, m_outWorkspace, m_scanVar, and name().
Referenced by loadDataScan().
fillMovingInstrumentScan()
void Mantid::DataHandling::LoadILLDiffraction::fillMovingInstrumentScan (const Nexus::NXInt & data, const Nexus::NXDouble & scan) private
Fills the counts for the instrument with moving detectors.
Parameters
data : detector data
scan : scan data
Definition at line 436 of file LoadILLDiffraction.cpp.
References Mantid::Nexus::NXDataSet::dim1(), Mantid::Nexus::NXDataSet::dim2(), Mantid::DataHandling::LoadHelper::fillMovingWorkspace(), getMonitor(), index, m_numberDetectorsActual, m_numberScanPoints, and m_outWorkspace.
Referenced by loadDataScan().
fillStaticInstrumentScan()
void Mantid::DataHandling::LoadILLDiffraction::fillStaticInstrumentScan (const Nexus::NXInt & data, const Nexus::NXDouble & scan, const double & twoTheta0) private
Fills the loaded data to the workspace when the detector is not moving during the run, but can be moved before.
Parameters
data : detector data
scan : scan data
twoTheta0 : starting two theta
Definition at line 472 of file LoadILLDiffraction.cpp.
References Mantid::Nexus::NXDataSet::dim1(), Mantid::Nexus::NXDataSet::dim2(), Mantid::DataHandling::LoadHelper::fillStaticWorkspace(), getAxis(), getMonitor(), Mantid::DataHandling::LoadHelper::loadEmptyInstrument(), m_instName, m_numberDetectorsActual, m_outWorkspace, and moveTwoThetaZero().
Referenced by loadDataScan().
getAbsoluteTimes()
std::vector< DateAndTime > Mantid::DataHandling::LoadILLDiffraction::getAbsoluteTimes (const Nexus::NXDouble & scan) const private
Returns the vector of absolute times for each scan point.
Parameters
scan : scan data
Returns
vector of absolute times
Definition at line 640 of file LoadILLDiffraction.cpp.
References getDurations(), m_numberScanPoints, and m_startTime.
Referenced by fillDataScanMetaData().
getAxis()
std::vector< double > Mantid::DataHandling::LoadILLDiffraction::getAxis (const Nexus::NXDouble & scan) const private
Returns the x-axis.
Parameters
scan : scan data
Returns
the x-axis
Definition at line 605 of file LoadILLDiffraction.cpp.
References m_numberScanPoints, m_scanType, m_scanVar, and OtherScan.
Referenced by fillStaticInstrumentScan().
getDurations()
std::vector< double > Mantid::DataHandling::LoadILLDiffraction::getDurations (const Nexus::NXDouble & scan) const private
Returns the durations in seconds for each scan point.
Parameters
scan : scan data
Returns
vector of durations
Definition at line 624 of file LoadILLDiffraction.cpp.
References m_numberScanPoints, and m_scanVar.
Referenced by getAbsoluteTimes().
getInstrumentFilePath()
std::string Mantid::DataHandling::LoadILLDiffraction::getInstrumentFilePath (const std::string & instName) const private
Makes up the full path of the relevant IDF dependent on resolution mode.
Parameters
instName : the name of the instrument (including the resolution mode suffix)
Returns
: the full path to the corresponding IDF
Definition at line 735 of file LoadILLDiffraction.cpp.
Referenced by initMovingWorkspace().
getMonitor()
std::vector< double > Mantid::DataHandling::LoadILLDiffraction::getMonitor (const Nexus::NXDouble & scan) const private
Returns the monitor spectrum.
Parameters
scan : scan data
Returns
monitor spectrum
Exceptions
std::runtime_error If there are no entries named Monitor1 or Monitor_1, or monitor1 in the NeXus file
Definition at line 588 of file LoadILLDiffraction.cpp.
References m_numberScanPoints, m_scanVar, and name().
Referenced by fillMovingInstrumentScan(), and fillStaticInstrumentScan().
getReferenceComponentPosition()
V3D Mantid::DataHandling::LoadILLDiffraction::getReferenceComponentPosition (const API::MatrixWorkspace_sptr & instrumentWorkspace) private
Get the position of the component in the workspace which corresponds to the angle stored in the scanned variables of the NeXus files.
For 1D detectors this should be the first detector (ID 1), while for 2D detectors (D2B only) it should be the position of the first tube.
Parameters
instrumentWorkspace The empty workspace containing the instrument
Returns
A V3D object containing the position of the relevant component
Definition at line 383 of file LoadILLDiffraction.cpp.
References m_instName.
Referenced by initMovingWorkspace().
getScannedVaribleByPropertyName()
std::vector< double > Mantid::DataHandling::LoadILLDiffraction::getScannedVaribleByPropertyName (const Nexus::NXDouble & scan, const std::string & propertyName) const private
Gets a scanned variable based on its property type in the scanned_variables block.
Parameters
scan : scan data
propertyName The name of the property
Returns
A vector of doubles containing the scanned variable
Exceptions
runtime_error If a scanned variable property name is missing from the NeXus file
Definition at line 561 of file LoadILLDiffraction.cpp.
References m_numberScanPoints, and m_scanVar.
Referenced by initMovingWorkspace().
init()
void Mantid::DataHandling::LoadILLDiffraction::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 97 of file LoadILLDiffraction.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
initMovingWorkspace()
void Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace (const Nexus::NXDouble & scan) private
Use the ScanningWorkspaceBuilder to create a time indexed workspace.
Parameters
scan : scan data
Definition at line 268 of file LoadILLDiffraction.cpp.
References calculateRelativeRotations(), Mantid::Kernel::Logger::debug(), fabs, Mantid::API::Algorithm::g_log, getInstrumentFilePath(), Mantid::API::Algorithm::getProperty(), getReferenceComponentPosition(), getScannedVaribleByPropertyName(), Mantid::Kernel::V3D::getSpherical(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::DataHandling::LoadHelper::loadEmptyInstrument(), m_instName, m_maxHeight, m_numberScanPoints, m_outWorkspace, m_pixelHeight, m_startTime, Mantid::Kernel::V3D::spherical(), std::to_string(), Mantid::Geometry::y, Mantid::Geometry::BoundingBox::yMax(), and Mantid::Geometry::BoundingBox::yMin().
Referenced by loadDataScan().
initStaticWorkspace()
void Mantid::DataHandling::LoadILLDiffraction::initStaticWorkspace () private
Initializes the output workspace based on the resolved instrument, scan points, and scan type.
Definition at line 247 of file LoadILLDiffraction.cpp.
References DetectorScan, Mantid::Kernel::SingletonHolder< T >::Instance(), m_numberDetectorsActual, m_numberScanPoints, m_outWorkspace, m_scanType, m_startTime, nSpectra, and OtherScan.
Referenced by loadDataScan().
loadDataScan()
void Mantid::DataHandling::LoadILLDiffraction::loadDataScan () private
Loads the scanned detector data.
Definition at line 146 of file LoadILLDiffraction.cpp.
References Mantid::Nexus::NXClass::close(), computeThetaOffset(), Mantid::DataHandling::LoadHelper::dateTimeInIsoFormat(), Mantid::Kernel::Logger::debug(), DetectorScan, fillDataScanMetaData(), fillMovingInstrumentScan(), fillStaticInstrumentScan(), Mantid::API::Algorithm::g_log, Mantid::DataHandling::LoadHelper::getDoubleDataset(), Mantid::API::Algorithm::getPointerToProperty(), Mantid::API::Algorithm::getProperty(), Mantid::Nexus::NXClass::getString(), initMovingWorkspace(), initStaticWorkspace(), Mantid::API::Algorithm::isDefault(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_filename, m_instName, m_numberDetectorsRead, m_numberScanPoints, m_scanType, m_scanVar, m_sizeDim1, m_sizeDim2, m_startTime, Mantid::Kernel::Logger::notice(), Mantid::Nexus::NXRoot::openFirstEntry(), Mantid::Nexus::NXClass::openNXDataSet(), Mantid::Nexus::NXClass::openNXFloat(), Mantid::Nexus::NXClass::openNXInt(), resolveInstrument(), and resolveScanType().
Referenced by exec().
loadMetaData()
void Mantid::DataHandling::LoadILLDiffraction::loadMetaData () private
Dumps the metadata from the whole file to SampleLogs.
Definition at line 221 of file LoadILLDiffraction.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_filename, m_outWorkspace, and READ.
Referenced by exec().
loadScanVars()
void Mantid::DataHandling::LoadILLDiffraction::loadScanVars () private
Loads the scanned_variables/variables_names block.
Definition at line 504 of file LoadILLDiffraction.cpp.
References Mantid::Nexus::H5Util::defaultFileAcc(), m_filename, m_scanVar, and Mantid::Nexus::H5Util::readStringVector().
Referenced by exec().
moveTwoThetaZero()
void Mantid::DataHandling::LoadILLDiffraction::moveTwoThetaZero (double twoTheta0Read) private
Rotates the detector to the 2theta0 read from the file.
Parameters
twoTheta0Read : 2theta0 read from the file
Definition at line 715 of file LoadILLDiffraction.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_instName, m_offsetTheta, m_outWorkspace, and rotation.
Referenced by fillStaticInstrumentScan().
name()
const std::string Mantid::DataHandling::LoadILLDiffraction::name () const override virtual
Algorithms name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 79 of file LoadILLDiffraction.cpp.
Referenced by fillDataScanMetaData(), and getMonitor().
resolveInstrument()
void Mantid::DataHandling::LoadILLDiffraction::resolveInstrument () private
Resolves the instrument based on instrument name and resolution mode.
Exceptions
runtime_error,if the instrument is not supported
Definition at line 681 of file LoadILLDiffraction.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_instName, m_instNames, m_numberDetectorsActual, m_numberDetectorsRead, and m_resolutionMode.
Referenced by loadDataScan().
resolveScanType()
void Mantid::DataHandling::LoadILLDiffraction::resolveScanType () private
Resolves the scan type.
Definition at line 657 of file LoadILLDiffraction.cpp.
References DetectorScan, m_instName, m_numberScanPoints, m_scanType, m_scanVar, NoScan, and OtherScan.
Referenced by loadDataScan().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadILLDiffraction::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 29 of file LoadILLDiffraction.h.
setSampleLogs()
void Mantid::DataHandling::LoadILLDiffraction::setSampleLogs () private
Adds some sample logs needed later by reduction.
Exceptions
runtime_error If wavelength or Monochromator.ei metadata is missing from the file
Definition at line 746 of file LoadILLDiffraction.cpp.
References Mantid::API::LogManager::addLogData(), DetectorScan, Mantid::API::LogManager::getLogAsSingleValue(), Mantid::API::LogManager::getPropertyValueAsType(), Mantid::API::LogManager::hasProperty(), lambda, m_maxHeight, m_numberDetectorsActual, m_numberScanPoints, m_outWorkspace, m_pixelHeight, m_resolutionMode, m_scanType, NoScan, and OtherScan.
Referenced by exec().
summary()
const std::string Mantid::DataHandling::LoadILLDiffraction::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 88 of file LoadILLDiffraction.cpp.
validateInputs()
std::map< std::string, std::string > Mantid::DataHandling::LoadILLDiffraction::validateInputs (void) override private virtual
Perform validation of ALL the input properties of the algorithm.
This is to be overridden by specific algorithms. It will be called in dialogs after parsing all inputs and setting the properties, but BEFORE executing.
Returns
a map where: Key = string name of the property; Value = string describing the problem with the property.
Reimplemented from Mantid::API::Algorithm.
Definition at line 110 of file LoadILLDiffraction.cpp.
version()
int Mantid::DataHandling::LoadILLDiffraction::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 82 of file LoadILLDiffraction.cpp.
Member Data Documentation
m_filename
std::string Mantid::DataHandling::LoadILLDiffraction::m_filename private
file name to load
Definition at line 97 of file LoadILLDiffraction.h.
Referenced by exec(), loadDataScan(), loadMetaData(), and loadScanVars().
m_instName
std::string Mantid::DataHandling::LoadILLDiffraction::m_instName private
instrument name to load the IDF
Definition at line 95 of file LoadILLDiffraction.h.
Referenced by calculateRelativeRotations(), exec(), fillStaticInstrumentScan(), getReferenceComponentPosition(), initMovingWorkspace(), loadDataScan(), moveTwoThetaZero(), resolveInstrument(), and resolveScanType().
m_instNames
std::set<std::string> Mantid::DataHandling::LoadILLDiffraction::m_instNames private
supported instruments
Definition at line 96 of file LoadILLDiffraction.h.
Referenced by resolveInstrument().
m_maxHeight
double Mantid::DataHandling::LoadILLDiffraction::m_maxHeight {0.} private
maximum absolute height of the D2B tubes
Definition at line 101 of file LoadILLDiffraction.h.
Referenced by initMovingWorkspace(), and setSampleLogs().
m_numberDetectorsActual
size_t Mantid::DataHandling::LoadILLDiffraction::m_numberDetectorsActual private
number of cells actually active
Definition at line 91 of file LoadILLDiffraction.h.
Referenced by fillMovingInstrumentScan(), fillStaticInstrumentScan(), initStaticWorkspace(), resolveInstrument(), and setSampleLogs().
m_numberDetectorsRead
size_t Mantid::DataHandling::LoadILLDiffraction::m_numberDetectorsRead private
number of cells read from file
Definition at line 90 of file LoadILLDiffraction.h.
Referenced by loadDataScan(), and resolveInstrument().
m_numberScanPoints
size_t Mantid::DataHandling::LoadILLDiffraction::m_numberScanPoints private
number of scan points
Definition at line 92 of file LoadILLDiffraction.h.
Referenced by fillDataScanMetaData(), fillMovingInstrumentScan(), getAbsoluteTimes(), getAxis(), getDurations(), getMonitor(), getScannedVaribleByPropertyName(), initMovingWorkspace(), initStaticWorkspace(), loadDataScan(), resolveScanType(), and setSampleLogs().
m_offsetTheta
double Mantid::DataHandling::LoadILLDiffraction::m_offsetTheta {0.} private
Definition at line 86 of file LoadILLDiffraction.h.
Referenced by calculateRelativeRotations(), computeThetaOffset(), and moveTwoThetaZero().
m_outWorkspace
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLDiffraction::m_outWorkspace private
output workspace
Definition at line 104 of file LoadILLDiffraction.h.
Referenced by convertAxisAndTranspose(), exec(), fillDataScanMetaData(), fillMovingInstrumentScan(), fillStaticInstrumentScan(), initMovingWorkspace(), initStaticWorkspace(), loadMetaData(), moveTwoThetaZero(), and setSampleLogs().
m_pixelHeight
double Mantid::DataHandling::LoadILLDiffraction::m_pixelHeight {0.} private
height of the pixel in D2B
Definition at line 100 of file LoadILLDiffraction.h.
Referenced by initMovingWorkspace(), and setSampleLogs().
m_resolutionMode
size_t Mantid::DataHandling::LoadILLDiffraction::m_resolutionMode private
resolution mode; 1:low, 2:nominal, 3:high
Definition at line 93 of file LoadILLDiffraction.h.
Referenced by computeThetaOffset(), resolveInstrument(), and setSampleLogs().
m_scanType
ScanType Mantid::DataHandling::LoadILLDiffraction::m_scanType private
NoScan, DetectorScan or OtherScan.
Definition at line 99 of file LoadILLDiffraction.h.
Referenced by exec(), getAxis(), initStaticWorkspace(), loadDataScan(), resolveScanType(), and setSampleLogs().
m_scanVar
std::vector<ScannedVariables> Mantid::DataHandling::LoadILLDiffraction::m_scanVar private
holds the scan info
Definition at line 103 of file LoadILLDiffraction.h.
Referenced by exec(), fillDataScanMetaData(), getAxis(), getDurations(), getMonitor(), getScannedVaribleByPropertyName(), loadDataScan(), loadScanVars(), and resolveScanType().
m_sizeDim1
size_t Mantid::DataHandling::LoadILLDiffraction::m_sizeDim1 private
size of dim1, number of tubes (D2B) or the whole detector (D20)
Definition at line 87 of file LoadILLDiffraction.h.
Referenced by loadDataScan().
m_sizeDim2
size_t Mantid::DataHandling::LoadILLDiffraction::m_sizeDim2 private
size of dim2, number of pixels (1 for D20!)
Definition at line 89 of file LoadILLDiffraction.h.
Referenced by loadDataScan().
m_startTime
Types::Core::DateAndTime Mantid::DataHandling::LoadILLDiffraction::m_startTime private
start time of acquisition
Definition at line 98 of file LoadILLDiffraction.h.
Referenced by getAbsoluteTimes(), initMovingWorkspace(), initStaticWorkspace(), and loadDataScan().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
Framework/DataHandling/src/LoadILLDiffraction.cpp