Mantid: Mantid::CurveFitting::HistogramDomainCreator Class Reference
Mantid::CurveFitting::HistogramDomainCreator Class Reference
HistogramDomainCreator:
#include <HistogramDomainCreator.h>
Public Member Functions
void createDomain (std::shared_ptr< API::FunctionDomain > &domain, std::shared_ptr< API::FunctionValues > &values, size_t i0=0) override
Creates a domain corresponding to the assigned MatrixWorkspace.
std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName) override
Create an output workspace with the calculated values.
HistogramDomainCreator (Kernel::IPropertyManager &manager, const std::string &workspacePropertyName)
Constructor.
Public Member Functions inherited from Mantid::CurveFitting::IMWDomainCreator
std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName) override
Create an output workspace.
void declareDatasetProperties (const std::string &suffix="", bool addProp=true) override
Declare properties that specify the dataset within the workspace to fit to.
size_t getDomainSize () const override
Return the size of the domain to be created.
IMWDomainCreator (Kernel::IPropertyManager *fit, const std::string &workspacePropertyName, DomainType domainType=Simple)
Constructor.
void initFunction (API::IFunction_sptr function) override
Initialize the function.
void setRange (double startX, double endX)
Set the startX and endX.
void setWorkspace (std::shared_ptr< API::MatrixWorkspace > ws)
Set the workspace.
void setWorkspaceIndex (size_t wi)
Set the workspace index.
Public Member Functions inherited from Mantid::API::IDomainCreator
IDomainCreator (Kernel::IPropertyManager *manager, std::vector< std::string > workspacePropertyNames, DomainType domainType=Simple)
Constrcutor.
void ignoreInvalidData (bool yes)
Set to ignore invalid data.
virtual void initialize (Kernel::IPropertyManager *, const std::string &, DomainType)
Initialize.
void separateCompositeMembersInOutput (const bool value, const bool conv=false)
Toggle output of either just composite or composite + members.
virtual ~IDomainCreator ()=default
Virtual destructor.
Additional Inherited Members
Public Types inherited from Mantid::API::IDomainCreator
enum DomainType { Simple = 0 , Sequential , Parallel }
Type of domain to create.
Protected Member Functions inherited from Mantid::CurveFitting::IMWDomainCreator
void addFunctionValuesToWS (const API::IFunction_sptr &function, std::shared_ptr< API::MatrixWorkspace > &ws, const size_t wsIndex, const std::shared_ptr< API::FunctionDomain > &domain, const std::shared_ptr< API::FunctionValues > &resultValues) const
Add the calculated function values to the workspace.
void appendCompositeFunctionMembers (std::list< API::IFunction_sptr > &functionList, const API::IFunction_sptr &function) const
void appendConvolvedCompositeFunctionMembers (std::list< API::IFunction_sptr > &functionList, const API::IFunction_sptr &function) const
If the fit function is Convolution and flag m_convolutionCompositeMembers is set and Convolution's second function (the model) is composite then use members of the model for the output.
std::shared_ptr< API::MatrixWorkspace > createEmptyResultWS (const size_t nhistograms, const size_t nyvalues)
Creates the blank output workspace of the correct size.
std::pair< size_t, size_t > getXInterval () const
Calculate size and starting iterator in the X array.
void setInitialValues (API::IFunction &function)
Set initial values for parameters with default values.
virtual void setParameters () const
Set all parameters.
Protected Member Functions inherited from Mantid::API::IDomainCreator
void declareProperty (Kernel::Property *prop, const std::string &doc)
Declare a property to the algorithm.
Protected Attributes inherited from Mantid::CurveFitting::IMWDomainCreator
std::weak_ptr< API::FunctionDomain1D > m_domain
Store the created domain and values.
double m_endX
endX
std::string m_endXPropertyName
Store endX property name.
std::shared_ptr< API::MatrixWorkspace > m_matrixWorkspace
The input MareixWorkspace.
size_t m_startIndex
double m_startX
startX
std::string m_startXPropertyName
Store startX property name.
std::weak_ptr< API::FunctionValues > m_values
size_t m_workspaceIndex
The workspace index.
std::string m_workspaceIndexPropertyName
Store workspace index property name.
std::string m_workspacePropertyName
Store workspace property name.
Protected Attributes inherited from Mantid::API::IDomainCreator
bool m_convolutionCompositeMembers
Perform convolution of output composite components.
DomainType m_domainType
Domain type.
bool m_ignoreInvalidData
Flag to ignore nans, infinities and zero errors.
Kernel::IPropertyManager * m_manager
Pointer to a property manager.
bool m_outputCompositeMembers
Output separate composite function values.
std::vector< std::string > m_workspacePropertyNames
Property names for workspaces to get the data from.
Detailed Description
HistogramDomainCreator:
HistogramDomainCreator creates a FunctionDomain1DHistogram which is used with IFunction1D.
This file is part of Mantid.
Mantid is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
Mantid is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 45 of file HistogramDomainCreator.h.
Constructor & Destructor Documentation
HistogramDomainCreator()
Mantid::CurveFitting::HistogramDomainCreator::HistogramDomainCreator (Kernel::IPropertyManager & manager, const std::string & workspacePropertyName)
Constructor.
Parameters
manager :: Pointer to IPropertyManager (Algorithm) instance.
workspacePropertyName :: Name of the output property for a created workspace in case a PropertyManager is used.
Definition at line 23 of file HistogramDomainCreator.cpp.
Member Function Documentation
createDomain()
void Mantid::CurveFitting::HistogramDomainCreator::createDomain (std::shared_ptr< API::FunctionDomain > & domain, std::shared_ptr< API::FunctionValues > & values, size_t i0 = 0) override virtual
Creates a domain corresponding to the assigned MatrixWorkspace.
Parameters
domain :: Pointer to outgoing FunctionDomain instance.
values :: Pointer to outgoing FunctionValues object.
i0 :: Size offset for values object if it already contains data.
Implements Mantid::API::IDomainCreator.
Definition at line 34 of file HistogramDomainCreator.cpp.
References error, Mantid::CurveFitting::IMWDomainCreator::getXInterval(), Mantid::CurveFitting::IMWDomainCreator::m_domain, Mantid::API::IDomainCreator::m_domainType, Mantid::API::IDomainCreator::m_ignoreInvalidData, Mantid::CurveFitting::IMWDomainCreator::m_matrixWorkspace, Mantid::CurveFitting::IMWDomainCreator::m_startIndex, Mantid::CurveFitting::IMWDomainCreator::m_values, Mantid::CurveFitting::IMWDomainCreator::m_workspaceIndex, Mantid::CurveFitting::IMWDomainCreator::setParameters(), Mantid::API::IDomainCreator::Simple, Mantid::Geometry::X, Mantid::Geometry::Y, and Mantid::Geometry::y.
createOutputWorkspace()
std::shared_ptr< API::Workspace > Mantid::CurveFitting::HistogramDomainCreator::createOutputWorkspace (const std::string & baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string & outputWorkspacePropertyName) override virtual
Create an output workspace with the calculated values.
Parameters
baseName :: Specifies the name of the output workspace
function :: A Pointer to the fitting function
domain :: The domain containing x-values for the function
values :: A API::FunctionValues instance containing the fitting data
outputWorkspacePropertyName :: The property name
Reimplemented from Mantid::API::IDomainCreator.
Definition at line 108 of file HistogramDomainCreator.cpp.
References Mantid::CurveFitting::IMWDomainCreator::createOutputWorkspace(), left, Mantid::API::FunctionDomain1DHistogram::leftBoundary(), Mantid::CurveFitting::IMWDomainCreator::m_matrixWorkspace, right, and Mantid::Geometry::y.
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/HistogramDomainCreator.h
Framework/CurveFitting/src/HistogramDomainCreator.cpp