Mantid: MantidQt::MantidWidgets::InputControllerMoveUnwrapped Class Reference
MantidQt::MantidWidgets::InputControllerMoveUnwrapped Class Reference
Controller for moving the instrument on an unwrapped surface.
#include <InputController.h>
Signals
void resetZoom ()
void setSelectionRect (const QRect &)
void unzoom ()
void zoom ()
Signals inherited from MantidQt::MantidWidgets::InputController
void disabled ()
void enabled ()
void touchPointAt (int, int)
Public Member Functions
InputControllerMoveUnwrapped (QObject *parent)
Constructor.
void mouseMoveEvent (QMouseEvent *) override
Process the mouse move event.
void mousePressEvent (QMouseEvent *) override
Process the mouse press event.
void mouseReleaseEvent (QMouseEvent *) override
Process the mouse button release event.
Public Member Functions inherited from MantidQt::MantidWidgets::InputController
bool canShowContextMenu () const
Returns true if a surface using this controller can show a context menu on right-click.
virtual void enterEvent (QEvent *)
virtual void freezeRotation (bool)
InputController (QObject *parent, bool contextAllowed=true)
virtual void keyPressEvent (QKeyEvent *)
virtual void leaveEvent (QEvent *)
virtual void onDisabled ()
To be called when this controller looses control.
virtual void onEnabled ()
To be called when this controller takes control of the input.
virtual void onPaint (QPainter &)
To be called after the owner widget has drawn its content.
virtual void wheelEvent (QWheelEvent *)
~InputController () override=default
Private Attributes
bool m_isButtonPressed
QRect m_rect
Detailed Description
Controller for moving the instrument on an unwrapped surface.
Definition at line 195 of file InputController.h.
Constructor & Destructor Documentation
InputControllerMoveUnwrapped()
MantidQt::MantidWidgets::InputControllerMoveUnwrapped::InputControllerMoveUnwrapped (QObject * parent)
Constructor.
Definition at line 231 of file InputController.cpp.
Member Function Documentation
mouseMoveEvent()
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::mouseMoveEvent (QMouseEvent * event) override virtual
Process the mouse move event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 247 of file InputController.cpp.
References m_isButtonPressed, m_rect, MantidQt::MantidWidgets::InputController::mouseMoveEvent(), and setSelectionRect().
mousePressEvent()
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::mousePressEvent (QMouseEvent * event) override virtual
Process the mouse press event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 237 of file InputController.cpp.
References m_isButtonPressed, and m_rect.
mouseReleaseEvent()
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::mouseReleaseEvent (QMouseEvent * event) override virtual
Process the mouse button release event.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 258 of file InputController.cpp.
References m_isButtonPressed, m_rect, resetZoom(), unzoom(), and zoom().
resetZoom
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::resetZoom () signal
Referenced by mouseReleaseEvent().
setSelectionRect
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::setSelectionRect (const QRect &) signal
Referenced by mouseMoveEvent().
unzoom
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::unzoom () signal
Referenced by mouseReleaseEvent().
zoom
void MantidQt::MantidWidgets::InputControllerMoveUnwrapped::zoom () signal
Referenced by mouseReleaseEvent().
Member Data Documentation
m_isButtonPressed
bool MantidQt::MantidWidgets::InputControllerMoveUnwrapped::m_isButtonPressed private
Definition at line 211 of file InputController.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_rect
QRect MantidQt::MantidWidgets::InputControllerMoveUnwrapped::m_rect private
Definition at line 212 of file InputController.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InputController.h
qt/widgets/common/src/InputController.cpp