Mantid: Mantid::API::IPreview Class Reference
Mantid::API::IPreview Class Reference abstract
IPreview : This is the abstract base class of the raw data previews.
#include <IPreview.h>
Public Types
enum class PreviewType { IVIEW = 0 , PLOT1D = 1 , PLOT2D = 2 , SVIEW = 3 }
Public Member Functions
virtual std::string facility () const =0
virtual std::string name () const =0
virtual std::string technique () const =0
virtual PreviewType type () const =0
Workspace_sptr view (Workspace_sptr ws) const
virtual ~IPreview ()=default
Private Member Functions
virtual Workspace_sptr preview (Workspace_sptr ws) const
Detailed Description
IPreview : This is the abstract base class of the raw data previews.
Preview is a stateless, named basic operation (view) that is commonly used for a given facility and technique for visualizing the raw data in a meaningful way. Preview also has a type, which tells the client which kind of visualization is relevant for the returned workspace (instrument view, slice view, 1d or color fill plot).
Definition at line 24 of file IPreview.h.
Member Enumeration Documentation
PreviewType
enum class Mantid::API::IPreview::PreviewType strong
Enumerator
IVIEW
PLOT1D
PLOT2D
SVIEW
Definition at line 26 of file IPreview.h.
Constructor & Destructor Documentation
~IPreview()
virtual Mantid::API::IPreview::~IPreview () virtual default
Member Function Documentation
facility()
virtual std::string Mantid::API::IPreview::facility () const pure virtual
Referenced by export_IPreview().
name()
virtual std::string Mantid::API::IPreview::name () const pure virtual
Referenced by export_IPreview().
preview()
virtual Workspace_sptr Mantid::API::IPreview::preview (Workspace_sptr ws) const inline private virtual
Definition at line 35 of file IPreview.h.
technique()
virtual std::string Mantid::API::IPreview::technique () const pure virtual
Referenced by export_IPreview().
type()
virtual PreviewType Mantid::API::IPreview::type () const pure virtual
Referenced by export_IPreview().
view()
Workspace_sptr Mantid::API::IPreview::view (Workspace_sptr ws) const inline
Definition at line 32 of file IPreview.h.
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IPreview.h