Mantid: ICat4::ns1__luceneGetPopulating Class Reference
ICat4::ns1__luceneGetPopulating Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__luceneGetPopulating ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 736 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__luceneGetPopulating()
ICat4::ns1__luceneGetPopulating::ns1__luceneGetPopulating () inline
Definition at line 747 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__luceneGetPopulating::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19809 of file ICat4C.cpp.
Referenced by ICat4::soap_in_ns1__luceneGetPopulating(), ICat4::soap_new_req_ns1__luceneGetPopulating(), and ICat4::soap_new_set_ns1__luceneGetPopulating().
soap_get()
void * ICat4::ns1__luceneGetPopulating::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19902 of file ICat4C.cpp.
References ICat4::soap_get_ns1__luceneGetPopulating().
soap_in()
void * ICat4::ns1__luceneGetPopulating::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19838 of file ICat4C.cpp.
References ICat4::soap_in_ns1__luceneGetPopulating().
Referenced by ICat4::soap_in_ns1__luceneGetPopulating().
soap_out()
int ICat4::ns1__luceneGetPopulating::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19823 of file ICat4C.cpp.
References ICat4::soap_out_ns1__luceneGetPopulating().
soap_put()
int ICat4::ns1__luceneGetPopulating::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19895 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__luceneGetPopulating.
soap_serialize()
void ICat4::ns1__luceneGetPopulating::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19815 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTostd__string().
soap_type()
int ICat4::ns1__luceneGetPopulating::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 740 of file ICat4Stub.h.
Member Data Documentation
sessionId
std::string* ICat4::ns1__luceneGetPopulating::sessionId
Definition at line 738 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp