Mantid: MantidQt::MantidWidgets::MantidTreeModel Class Reference
MantidQt::MantidWidgets::MantidTreeModel Class Reference
#include <MantidTreeModel.h>
Public Slots
Table * createDetectorTable (const QString &wsName, const std::vector< int > &indices, bool include_data=false) override
MantidQt::MantidWidgets::MantidWSIndexDialog * createWorkspaceIndexDialog (int flags, const QStringList &wsNames, bool showWaterfall, bool showPlotAll, bool showTiledOpt, bool isAdvanced=false) override
void disableSaveNexus () override
void drawColorFillPlots (const QStringList &wsNames, GraphOptions::CurveType curveType=GraphOptions::ColorMap) override
void enableSaveNexus (const QString &wsName) override
void executeAlgorithm (Mantid::API::IAlgorithm_sptr alg) override
void importBoxDataTable () override
MantidMatrix * importMatrixWorkspace (const Mantid::API::MatrixWorkspace_sptr workspace, int lower=-1, int upper=-1, bool showDlg=true) override
void importTransposed () override
void importWorkspace () override
void importWorkspace (const QString &wsName, bool showDlg=true, bool makeVisible=true) override
MultiLayer * plot1D (const QMultiMap< QString, std::set< int > > &toPlot, bool spectrumPlot, MantidQt::DistributionFlag distr=MantidQt::DistributionDefault, bool errs=false, MultiLayer *plotWindow=nullptr, bool clearWindow=false, bool waterfallPlot=false, const QString &log="", const std::set< double > &customLogValues=std::set< double >()) override
void plotContour (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames) override
void plotSurface (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames) override
void renameWorkspace (QStringList=QStringList()) override
void showAlgorithmDialog (const QString &algName, int version=-1) override
void showAlgorithmDialog (const QString &algName, QHash< QString, QString > paramList, Mantid::API::AlgorithmObserver *obs=nullptr, int version=-1) override
void showAlgorithmHistory () override
void showCritical (const QString &) override
void showListData () override
void showLogFileWindow () override
void showMantidInstrumentSelected () override
void showMDPlot () override
void showSampleMaterialWindow () override
void showSliceViewer () override
void showSpectrumViewer () override
void updateProject () override
Public Member Functions
Mantid::API::IAlgorithm_sptr createAlgorithm (const QString &algName, int version=-1) override
MantidQt::API::AlgorithmDialog * createAlgorithmDialog (const Mantid::API::IAlgorithm_sptr &alg)
This creates an algorithm dialog (the default property entry thingie).
void deleteWorkspaces (const QStringList &wsNames=QStringList()) override
bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=false) override
QWidget * getParent () override
Mantid::API::Workspace_const_sptr getWorkspace (const QString &workspaceName) override
MantidTreeModel ()
DefaultConstructor.
MultiLayer * plotSubplots (const QMultiMap< QString, std::set< int > > &toPlot, MantidQt::DistributionFlag distr=MantidQt::DistributionDefault, bool errs=false, MultiLayer *plotWindow=nullptr) override
void updateRecentFilesList (const QString &fname) override
Public Member Functions inherited from MantidQt::MantidWidgets::MantidDisplayBase
virtual Table * createDetectorTable (const QString &wsName, const std::vector< int > &indices, bool include_data=false)=0
virtual MantidWSIndexDialog * createWorkspaceIndexDialog (int flags, const QStringList &wsNames, bool showWaterfall, bool showPlotAll, bool showTiledOpt, bool isAdvanced=false)=0
virtual void disableSaveNexus ()=0
virtual void drawColorFillPlots (const QStringList &wsNames, GraphOptions::CurveType curveType=GraphOptions::ColorMap)=0
virtual void enableSaveNexus (const QString &wsName)=0
virtual void executeAlgorithm (Mantid::API::IAlgorithm_sptr alg)=0
virtual void importBoxDataTable ()=0
virtual MantidMatrix * importMatrixWorkspace (const Mantid::API::MatrixWorkspace_sptr workspace, int lower=-1, int upper=-1, bool showDlg=true)=0
virtual void importTransposed ()=0
virtual void importWorkspace ()=0
virtual void importWorkspace (const QString &wsName, bool showDlg=true, bool makeVisible=true)=0
virtual MultiLayer * plot1D (const QMultiMap< QString, std::set< int > > &toPlot, bool spectrumPlot, MantidQt::DistributionFlag distr=MantidQt::DistributionDefault, bool errs=false, MultiLayer *plotWindow=nullptr, bool clearWindow=false, bool waterfallPlot=false, const QString &log="", const std::set< double > &customLogValues=std::set< double >())=0
virtual void plotContour (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames)=0
virtual void plotSurface (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames)=0
virtual void renameWorkspace (QStringList=QStringList())=0
virtual void showAlgorithmDialog (const QString &algName, int version=-1)=0
virtual void showAlgorithmDialog (const QString &algName, QHash< QString, QString > paramList, Mantid::API::AlgorithmObserver *obs=nullptr, int version=-1)=0
virtual void showAlgorithmHistory ()=0
virtual void showCritical (const QString &)
virtual void showListData ()=0
virtual void showLogFileWindow ()=0
virtual void showMantidInstrumentSelected ()=0
virtual void showMDPlot ()=0
virtual void showSampleMaterialWindow ()=0
virtual void showSliceViewer ()=0
virtual void showSpectrumViewer ()=0
virtual void updateProject ()=0
virtual ~MantidDisplayBase ()=default
Private Member Functions
MantidTreeModel (const MantidTreeModel &)
MantidTreeModel & operator= (const MantidTreeModel &)
Detailed Description
Author
Elliot Oram
Date
18-12-2017
Version
1.0
Definition at line 35 of file MantidTreeModel.h.
Constructor & Destructor Documentation
MantidTreeModel() [1/2]
MantidTreeModel::MantidTreeModel () default
DefaultConstructor.
References Mantid::API::renameWorkspace().
MantidTreeModel() [2/2]
MantidQt::MantidWidgets::MantidTreeModel::MantidTreeModel (const MantidTreeModel &) private
Member Function Documentation
createAlgorithm()
Mantid::API::IAlgorithm_sptr MantidTreeModel::createAlgorithm (const QString & algName, int version = -1) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 61 of file MantidTreeModel.cpp.
Referenced by deleteWorkspaces(), showAlgorithmDialog(), and showAlgorithmDialog().
createAlgorithmDialog()
MantidQt::API::AlgorithmDialog * MantidTreeModel::createAlgorithmDialog (const Mantid::API::IAlgorithm_sptr & alg)
This creates an algorithm dialog (the default property entry thingie).
Helper function not required by interface
Definition at line 117 of file MantidTreeModel.cpp.
References MantidQt::API::InterfaceManager::createDialog().
Referenced by showAlgorithmDialog().
createDetectorTable
Table * MantidTreeModel::createDetectorTable (const QString & wsName, const std::vector< int > & indices, bool include_data = false) override slot
Definition at line 220 of file MantidTreeModel.cpp.
createWorkspaceIndexDialog
MantidQt::MantidWidgets::MantidWSIndexDialog * MantidTreeModel::createWorkspaceIndexDialog (int flags, const QStringList & wsNames, bool showWaterfall, bool showPlotAll, bool showTiledOpt, bool isAdvanced = false) override slot
Definition at line 279 of file MantidTreeModel.cpp.
deleteWorkspaces()
void MantidTreeModel::deleteWorkspaces (const QStringList & wsNames = QStringList()) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 28 of file MantidTreeModel.cpp.
References createAlgorithm(), and executeAlgorithmAsync().
disableSaveNexus
void MantidTreeModel::disableSaveNexus () override slot
Definition at line 188 of file MantidTreeModel.cpp.
drawColorFillPlots
void MantidTreeModel::drawColorFillPlots (const QStringList & wsNames, GraphOptions::CurveType curveType = GraphOptions::ColorMap) override slot
Definition at line 243 of file MantidTreeModel.cpp.
enableSaveNexus
void MantidTreeModel::enableSaveNexus (const QString & wsName) override slot
Definition at line 187 of file MantidTreeModel.cpp.
executeAlgorithm
void MantidTreeModel::executeAlgorithm (Mantid::API::IAlgorithm_sptr alg) override slot
Definition at line 143 of file MantidTreeModel.cpp.
References executeAlgorithmAsync().
executeAlgorithmAsync()
bool MantidTreeModel::executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait = false) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 145 of file MantidTreeModel.cpp.
References Mantid::Kernel::Logger::error(), and Mantid::API::g_log.
Referenced by deleteWorkspaces(), and executeAlgorithm().
getParent()
QWidget * MantidTreeModel::getParent () override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 194 of file MantidTreeModel.cpp.
getWorkspace()
Workspace_const_sptr MantidTreeModel::getWorkspace (const QString & workspaceName) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 169 of file MantidTreeModel.cpp.
importBoxDataTable
void MantidTreeModel::importBoxDataTable () override slot
Definition at line 198 of file MantidTreeModel.cpp.
importMatrixWorkspace
MantidMatrix * MantidTreeModel::importMatrixWorkspace (const Mantid::API::MatrixWorkspace_sptr workspace, int lower = -1, int upper = -1, bool showDlg = true) override slot
Definition at line 205 of file MantidTreeModel.cpp.
References lower, upper, and workspace.
importTransposed
void MantidTreeModel::importTransposed () override slot
Definition at line 200 of file MantidTreeModel.cpp.
importWorkspace [1/2]
void MantidTreeModel::importWorkspace () override slot
Definition at line 203 of file MantidTreeModel.cpp.
importWorkspace [2/2]
void MantidTreeModel::importWorkspace (const QString & wsName, bool showDlg = true, bool makeVisible = true) override slot
Definition at line 214 of file MantidTreeModel.cpp.
operator=()
MantidTreeModel & MantidQt::MantidWidgets::MantidTreeModel::operator= (const MantidTreeModel &) private
plot1D
MultiLayer * MantidTreeModel::plot1D (const QMultiMap< QString, std::set< int > > & toPlot, bool spectrumPlot, MantidQt::DistributionFlag distr = MantidQt::DistributionDefault, bool errs = false, MultiLayer * plotWindow = nullptr, bool clearWindow = false, bool waterfallPlot = false, const QString & log = "", const std::set< double > & customLogValues = std::set<double>()) override slot
Definition at line 227 of file MantidTreeModel.cpp.
plotContour
void MantidTreeModel::plotContour (bool accepted, int plotIndex, const QString & axisName, const QString & logName, const std::set< double > & customLogValues, const QList< QString > & workspaceNames) override slot
Definition at line 268 of file MantidTreeModel.cpp.
plotSubplots()
MultiLayer * MantidTreeModel::plotSubplots (const QMultiMap< QString, std::set< int > > & toPlot, MantidQt::DistributionFlag distr = MantidQt::DistributionDefault, bool errs = false, MultiLayer * plotWindow = nullptr) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 248 of file MantidTreeModel.cpp.
plotSurface
void MantidTreeModel::plotSurface (bool accepted, int plotIndex, const QString & axisName, const QString & logName, const std::set< double > & customLogValues, const QList< QString > & workspaceNames) override slot
Definition at line 258 of file MantidTreeModel.cpp.
renameWorkspace
void MantidTreeModel::renameWorkspace (QStringList wsName = QStringList()) override slot
Definition at line 45 of file MantidTreeModel.cpp.
References showAlgorithmDialog().
showAlgorithmDialog [1/2]
void MantidTreeModel::showAlgorithmDialog (const QString & algName, int version = -1) override slot
Definition at line 75 of file MantidTreeModel.cpp.
References createAlgorithm(), and MantidQt::API::InterfaceManager::createDialog().
Referenced by renameWorkspace().
showAlgorithmDialog [2/2]
void MantidTreeModel::showAlgorithmDialog (const QString & algName, QHash< QString, QString > paramList, Mantid::API::AlgorithmObserver * obs = nullptr, int version = -1) override slot
Definition at line 87 of file MantidTreeModel.cpp.
References MantidQt::API::AlgorithmDialog::addAlgorithmObserver(), createAlgorithm(), createAlgorithmDialog(), Mantid::Kernel::Logger::error(), and Mantid::API::g_log.
showAlgorithmHistory
void MantidTreeModel::showAlgorithmHistory () override slot
Definition at line 192 of file MantidTreeModel.cpp.
showCritical
void MantidTreeModel::showCritical (const QString & msg) override slot
Definition at line 196 of file MantidTreeModel.cpp.
showListData
void MantidTreeModel::showListData () override slot
Definition at line 199 of file MantidTreeModel.cpp.
showLogFileWindow
void MantidTreeModel::showLogFileWindow () override slot
Definition at line 201 of file MantidTreeModel.cpp.
showMantidInstrumentSelected
void MantidTreeModel::showMantidInstrumentSelected () override slot
Definition at line 197 of file MantidTreeModel.cpp.
showMDPlot
void MantidTreeModel::showMDPlot () override slot
Definition at line 193 of file MantidTreeModel.cpp.
showSampleMaterialWindow
void MantidTreeModel::showSampleMaterialWindow () override slot
Definition at line 202 of file MantidTreeModel.cpp.
showSliceViewer
void MantidTreeModel::showSliceViewer () override slot
Definition at line 191 of file MantidTreeModel.cpp.
showSpectrumViewer
void MantidTreeModel::showSpectrumViewer () override slot
Definition at line 190 of file MantidTreeModel.cpp.
updateProject
void MantidTreeModel::updateProject () override slot
Definition at line 195 of file MantidTreeModel.cpp.
updateRecentFilesList()
void MantidTreeModel::updateRecentFilesList (const QString & fname) override virtual
Implements MantidQt::MantidWidgets::MantidDisplayBase.
Definition at line 184 of file MantidTreeModel.cpp.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidTreeModel.h
qt/widgets/common/src/MantidTreeModel.cpp