Mantid: ICat4::ns1__deleteResponse Class Reference
ICat4::ns1__deleteResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__deleteResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Additional Inherited Members
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1269 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__deleteResponse()
ICat4::ns1__deleteResponse::ns1__deleteResponse () inline
Definition at line 1278 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__deleteResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6873 of file ICat4C.cpp.
Referenced by ICat4::ICATPortBindingProxy::delete_(), ICat4::soap_in_ns1__deleteResponse(), ICat4::soap_new_req_ns1__deleteResponse(), and ICat4::soap_new_set_ns1__deleteResponse().
soap_get()
void * ICat4::ns1__deleteResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6927 of file ICat4C.cpp.
References ICat4::soap_get_ns1__deleteResponse().
soap_in()
void * ICat4::ns1__deleteResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6894 of file ICat4C.cpp.
References ICat4::soap_in_ns1__deleteResponse().
Referenced by ICat4::soap_in_ns1__deleteResponse().
soap_out()
int ICat4::ns1__deleteResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6885 of file ICat4C.cpp.
References ICat4::soap_out_ns1__deleteResponse().
soap_put()
int ICat4::ns1__deleteResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6920 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__deleteResponse.
soap_serialize()
void ICat4::ns1__deleteResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 6878 of file ICat4C.cpp.
soap_type()
int ICat4::ns1__deleteResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1271 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp