Mantid: Mantid::DataHandling::LoadOff Class Reference
Mantid::DataHandling::LoadOff Class Reference
#include <LoadOff.h>
Public Member Functions
LoadOff (const std::string &filename, ScaleUnits scaleType)
std::unique_ptr< Geometry::MeshObject > readShape () override
Public Member Functions inherited from Mantid::DataHandling::LoadSingleMesh
LoadSingleMesh (std::string filename, std::ios_base::openmode mode, ScaleUnits scaleType)
virtual ~LoadSingleMesh ()
Public Member Functions inherited from Mantid::DataHandling::MeshFileIO
Kernel::V3D createScaledV3D (double xVal, double yVal, double zVal)
scales a 3D point according the units defined in the MeshFileIO class
ScaleUnits getScaleType ()
std::shared_ptr< Geometry::MeshObject > rotate (std::shared_ptr< Geometry::MeshObject > environmentMesh, double xRotation, double yRotation, double zRotation)
Rotates the environment by a generated matrix.
std::shared_ptr< Geometry::MeshObject > translate (std::shared_ptr< Geometry::MeshObject > environmentMesh, const std::vector< double > &translationVector)
translates the environment by a provided matrix
Private Member Functions
bool getOFFline (std::string &line)
std::unique_ptr< Geometry::MeshObject > readOFFMeshObject ()
void readOFFTriangles ()
void readOFFVertices ()
Private Attributes
uint32_t m_nTriangles
uint32_t m_nVertices
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataHandling::MeshFileIO
MeshFileIO (ScaleUnits scaleType)
MeshFileIO (ScaleUnits scaleType, std::vector< uint32_t > triangles, std::vector< Kernel::V3D > vertices)
float removeScale (double value)
double scaleValue (double val)
void setScaleType (const ScaleUnits scaleType)
Protected Attributes inherited from Mantid::DataHandling::LoadSingleMesh
std::ifstream m_file
const std::string m_filename
Protected Attributes inherited from Mantid::DataHandling::MeshFileIO
ScaleUnits m_scaleType
std::vector< uint32_t > m_triangle
std::vector< Kernel::V3D > m_vertices
Detailed Description
Definition at line 23 of file LoadOff.h.
Constructor & Destructor Documentation
LoadOff()
Mantid::DataHandling::LoadOff::LoadOff (const std::string & filename, ScaleUnits scaleType)
Definition at line 17 of file LoadOff.cpp.
Member Function Documentation
getOFFline()
bool Mantid::DataHandling::LoadOff::getOFFline (std::string & line) private
Definition at line 20 of file LoadOff.cpp.
References Mantid::DataHandling::LoadSingleMesh::m_file.
Referenced by readOFFMeshObject(), readOFFTriangles(), readOFFVertices(), and readShape().
readOFFMeshObject()
std::unique_ptr< Geometry::MeshObject > Mantid::DataHandling::LoadOff::readOFFMeshObject () private
Definition at line 85 of file LoadOff.cpp.
References getOFFline(), m_nTriangles, m_nVertices, Mantid::DataHandling::MeshFileIO::m_triangle, Mantid::DataHandling::MeshFileIO::m_vertices, readOFFTriangles(), and readOFFVertices().
Referenced by readShape().
readOFFTriangles()
void Mantid::DataHandling::LoadOff::readOFFTriangles () private
Definition at line 56 of file LoadOff.cpp.
References getOFFline(), m_nTriangles, and Mantid::DataHandling::MeshFileIO::m_triangle.
Referenced by readOFFMeshObject().
readOFFVertices()
void Mantid::DataHandling::LoadOff::readOFFVertices () private
Definition at line 36 of file LoadOff.cpp.
References Mantid::DataHandling::MeshFileIO::createScaledV3D(), getOFFline(), m_nVertices, and Mantid::DataHandling::MeshFileIO::m_vertices.
Referenced by readOFFMeshObject().
readShape()
std::unique_ptr< Geometry::MeshObject > Mantid::DataHandling::LoadOff::readShape () override virtual
Implements Mantid::DataHandling::LoadSingleMesh.
Definition at line 117 of file LoadOff.cpp.
References getOFFline(), and readOFFMeshObject().
Member Data Documentation
m_nTriangles
uint32_t Mantid::DataHandling::LoadOff::m_nTriangles private
Definition at line 35 of file LoadOff.h.
Referenced by readOFFMeshObject(), and readOFFTriangles().
m_nVertices
uint32_t Mantid::DataHandling::LoadOff::m_nVertices private
Definition at line 34 of file LoadOff.h.
Referenced by readOFFMeshObject(), and readOFFVertices().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadOff.h
Framework/DataHandling/src/LoadOff.cpp