Mantid: Mantid::Algorithms::TimeAtSampleStrategyIndirect Class Reference
Mantid::Algorithms::TimeAtSampleStrategyIndirect Class Reference
TimeAtSampleStrategyIndirect : Determine Time At Sample for an indirect instrument setup.
#include <TimeAtSampleStrategyIndirect.h>
Public Member Functions
Correction calculate (const size_t &workspace_index) const override
TimeAtSampleStrategyIndirect (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Public Member Functions inherited from Mantid::Algorithms::TimeAtSampleStrategy
virtual Correction calculate (const size_t &workspace_index) const =0
virtual ~TimeAtSampleStrategy ()=default
Private Attributes
const API::SpectrumInfo & m_spectrumInfo
std::shared_ptr< const Mantid::API::MatrixWorkspace > m_ws
Workspace to operate on.
Detailed Description
TimeAtSampleStrategyIndirect : Determine Time At Sample for an indirect instrument setup.
Definition at line 24 of file TimeAtSampleStrategyIndirect.h.
Constructor & Destructor Documentation
TimeAtSampleStrategyIndirect()
Mantid::Algorithms::TimeAtSampleStrategyIndirect::TimeAtSampleStrategyIndirect (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Definition at line 31 of file TimeAtSampleStrategyIndirect.cpp.
Member Function Documentation
calculate()
Correction Mantid::Algorithms::TimeAtSampleStrategyIndirect::calculate (const size_t & workspace_index) const override virtual
Implements Mantid::Algorithms::TimeAtSampleStrategy.
Definition at line 34 of file TimeAtSampleStrategyIndirect.cpp.
References Mantid::API::SpectrumInfo::detector(), Mantid::Geometry::IDetector::getID(), Mantid::API::SpectrumInfo::isMonitor(), Mantid::API::SpectrumInfo::l1(), Mantid::API::SpectrumInfo::l2(), Mantid::Kernel::l2, m_spectrumInfo, m_ws, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::NeutronMass, Mantid::API::SpectrumInfo::position(), and Mantid::API::SpectrumInfo::sourcePosition().
Member Data Documentation
m_spectrumInfo
const API::SpectrumInfo& Mantid::Algorithms::TimeAtSampleStrategyIndirect::m_spectrumInfo private
Definition at line 32 of file TimeAtSampleStrategyIndirect.h.
Referenced by calculate().
m_ws
std::shared_ptr<const Mantid::API::MatrixWorkspace> Mantid::Algorithms::TimeAtSampleStrategyIndirect::m_ws private
Workspace to operate on.
Definition at line 31 of file TimeAtSampleStrategyIndirect.h.
Referenced by calculate().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/TimeAtSampleStrategyIndirect.h
Framework/Algorithms/src/TimeAtSampleStrategyIndirect.cpp