Mantid: Mantid::Algorithms::FilterEvents Class Reference
Mantid::Algorithms::FilterEvents Class Reference final
FilterEvents : Filter Events in EventWorkspace to multiple EventsWorkspace by Splitters.
#include <FilterEvents.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
FilterEvents ()
Constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso algorithms related to this algorithm.
const std::string summary () const override
Summary of algorithms purpose.
std::map< std::string, std::string > validateInputs () override
Method checking errors on ALL the inputs, before execution.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Types
enum EVENTFILTERSKIP { EventFilterSkipNoDet , EventFilterSkipNoDetTOFCorr }
enum TOFCorrectionOp { MultiplyOp , ShiftOp }
enum TOFCorrectionType {
NoneCorrect , CustomizedCorrect , DirectCorrect , ElasticCorrect ,
IndirectCorrect
}
Private Member Functions
double calculate_duration (std::unique_ptr< Kernel::TimeSeriesProperty< int > > &splitter_tsp)
calculate split-workspace's duration according to splitter time series property
void convertSplittersWorkspaceToVectors ()
Convert SplittersWorkspace to vector of time and vector of target (itarget)
void copyNoneSplitLogs (std::vector< Kernel::TimeSeriesProperty< int > * > &int_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< double > * > &dbl_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< bool > * > &bool_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< std::string > * > &string_tsp_vector)
Clone the sample logs that will not be split, including single-value and add all the TimeSeriesProperty sample logs to vectors by their type.
std::shared_ptr< DataObjects::EventWorkspace > createEventWorkspaceNoLog ()
create event workspace
void createOutputWorkspacesMatrixCase ()
create output workspaces in the case of using MatrixWorkspace for splitters
void createOutputWorkspacesSplitters ()
create output workspaces if the splitters are given in SplittersWorkspace
void createOutputWorkspacesTableSplitterCase ()
create output workspaces in the case of using TableWorlspace for splitters
void examineAndSortEventWS ()
Examine workspace.
void exec () override
Execution body.
void filterEventsBySplitters (double progressamount)
Filter events by splitters in format of Splitter.
void filterEventsByVectorSplitters (double progressamount)
Filter events by splitters in format of vector.
void generateSplitterTSP (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > &split_tsp_vec)
Generate a vector of integer time series property for each splitter corresponding to each target (in integer) in each splitter-time-series-property, 1 stands for include and 0 stands for time for neutrons to be discarded.
void generateSplitterTSPalpha (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > &split_tsp_vec)
Generate the splitter's time series property (log) the splitters workspace.
std::vector< std::string > getTimeSeriesLogNames ()
get the names of all the time series properties in the input workspace's Run object
void groupOutputWorkspace ()
group output workspaces
void init () override
Declare Inputs.
void mapSplitterTSPtoWorkspaces (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > &split_tsp_vec)
Add time series property 'Splitter' to each child workspace.
void processAlgorithmProperties ()
Process user input properties.
void processMatrixSplitterWorkspace ()
process splitters given by a MatrixWorkspace
void processSplittersWorkspace ()
process splitters given by a SplittersWorkspace
void processTableSplittersWorkspace ()
process the input splitters given by a TableWorkspace The method will transfer the start/stop time to "m_vecSplitterTime" and map the splitting target (in string) to "m_vecSplitterGroup".
void setupCustomizedTOFCorrection ()
Set up detector calibration parameters from customized values.
void setupDetectorTOFCalibration ()
Set up detector calibration parameters.
TimeAtSampleStrategy * setupDirectTOFCorrection () const
Set up detector calibration parmaeters for direct inelastic scattering instrument.
TimeAtSampleStrategy * setupElasticTOFCorrection () const
Set up detector calibration parameters for elastic scattering instrument.
TimeAtSampleStrategy * setupIndirectTOFCorrection () const
Set up detector calibration parameters for indirect inelastic scattering instrument.
void splitTimeSeriesLogs (const std::vector< Kernel::TimeSeriesProperty< int > * > &int_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< double > * > &dbl_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< bool > * > &bool_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< std::string > * > &string_tsp_vector)
Split ALL the TimeSeriesProperty sample logs to all the output workspace.
template<typename TYPE >
void splitTimeSeriesProperty (Kernel::TimeSeriesProperty< TYPE > *tsp, std::vector< Types::Core::DateAndTime > &split_datetime_vec, const int max_target_index)
split one single time-series property (template)
Private Attributes
int m_dbWSIndex
DataObjects::TableWorkspace_sptr m_detCorrectWorkspace
std::vector< double > m_detTofFactors
std::vector< double > m_detTofOffsets
DataObjects::EventWorkspace_sptr m_eventWS
bool m_filterByPulseTime
Types::Core::DateAndTime m_filterStartTime
bool m_hasInfoWS
DataObjects::TableWorkspace_sptr m_informationWS
bool m_isSplittersRelativeTime
API::MatrixWorkspace_const_sptr m_matrixSplitterWS
int m_maxTargetIndex
std::map< int, DataObjects::EventWorkspace_sptr > m_outputWorkspacesMap
std::string m_outputWSNameBase
Base of output workspace's name.
double m_progress
Types::Core::DateAndTime m_runStartTime
EVENTFILTERSKIP m_specSkipType
Spectrum skip type.
bool m_splitSampleLogs
Flag to split sample logs.
Kernel::TimeSplitterType m_splitters
DataObjects::SplittersWorkspace_sptr m_splittersWorkspace
DataObjects::TableWorkspace_sptr m_splitterTableWorkspace
std::map< std::string, int > m_targetIndexMap
TableWorkspace splitters: from target map to vector workspace group-index These 2 maps are complimentary to each other.
std::set< int > m_targetWorkspaceIndexSet
TOFCorrectionType m_tofCorrType
TOF detector/sample correction type.
bool m_toGroupWS
Flag to group workspace.
bool m_useArbTableSplitters
bool m_useDBSpectrum
Debug.
bool m_useSplittersWorkspace
Flag to use matrix splitters or table splitters.
std::vector< bool > m_vecSkip
Vector for skip information.
std::vector< int > m_vecSplitterGroup
Vector for splitting group.
std::vector< int64_t > m_vecSplitterTime
Vector for splitting time FIXME - shall we convert this to DateAndTime???.
std::map< uint32_t, int > m_wsGroupdYMap
std::map< int, std::string > m_wsGroupIndexTargetMap
std::vector< std::string > m_wsNames
std::map< int, uint32_t > m_yIndexMap
MatrixWorkspace splitters:
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
FilterEvents : Filter Events in EventWorkspace to multiple EventsWorkspace by Splitters.
Date
2012-04-04
Definition at line 29 of file FilterEvents.h.
Member Enumeration Documentation
EVENTFILTERSKIP
enum Mantid::Algorithms::FilterEvents::EVENTFILTERSKIP private
Enumerator
EventFilterSkipNoDet
EventFilterSkipNoDetTOFCorr
Definition at line 33 of file FilterEvents.h.
TOFCorrectionOp
enum Mantid::Algorithms::FilterEvents::TOFCorrectionOp private
Enumerator
MultiplyOp
ShiftOp
Definition at line 32 of file FilterEvents.h.
TOFCorrectionType
enum Mantid::Algorithms::FilterEvents::TOFCorrectionType private
Enumerator
NoneCorrect
CustomizedCorrect
DirectCorrect
ElasticCorrect
IndirectCorrect
Definition at line 31 of file FilterEvents.h.
Constructor & Destructor Documentation
FilterEvents()
Mantid::Algorithms::FilterEvents::FilterEvents ()
Constructor.
Definition at line 61 of file FilterEvents.cpp.
Member Function Documentation
calculate_duration()
double Mantid::Algorithms::FilterEvents::calculate_duration (std::unique_ptr< Kernel::TimeSeriesProperty< int > > & splitter_tsp) private
calculate split-workspace's duration according to splitter time series property
Calculate split-workspace's duration according to splitter time series property.
calculate the duration from TSP "splitter"
Parameters
splitter_tsp :: TimeSeriesProperty for splitter
Returns
Definition at line 1910 of file FilterEvents.cpp.
Referenced by mapSplitterTSPtoWorkspaces().
category()
const std::string Mantid::Algorithms::FilterEvents::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Implements Mantid::API::IAlgorithm.
Definition at line 53 of file FilterEvents.h.
convertSplittersWorkspaceToVectors()
void Mantid::Algorithms::FilterEvents::convertSplittersWorkspaceToVectors () private
Convert SplittersWorkspace to vector of time and vector of target (itarget)
Convert SplittersWorkspace to vector of time and vector of target (itarget) NOTE: This is designed to use a single vector/vector splitters for all types of inputs It is not used before vast experiment on speed comparison!
FilterEvents::convertSplittersWorkspaceToVectors
Definition at line 809 of file FilterEvents.cpp.
References Mantid::Kernel::SplittingInterval::index(), m_maxTargetIndex, m_splitters, m_useSplittersWorkspace, m_vecSplitterGroup, m_vecSplitterTime, Mantid::Kernel::SplittingInterval::start(), Mantid::Kernel::SplittingInterval::stop(), and TOLERANCE().
Referenced by splitTimeSeriesLogs().
copyNoneSplitLogs()
void Mantid::Algorithms::FilterEvents::copyNoneSplitLogs (std::vector< Kernel::TimeSeriesProperty< int > * > & int_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< double > * > & dbl_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< bool > * > & bool_tsp_name_vector, std::vector< Kernel::TimeSeriesProperty< std::string > * > & string_tsp_vector) private
Clone the sample logs that will not be split, including single-value and add all the TimeSeriesProperty sample logs to vectors by their type.
FilterEvents::copyNoneSplitLogs
Parameters
int_tsp_name_vector :: output
dbl_tsp_name_vector :: output
bool_tsp_name_vector :: output
string_tsp_vector :: output
Definition at line 536 of file FilterEvents.cpp.
References Mantid::Kernel::Strings::convert(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), m_eventWS, m_outputWorkspacesMap, and Mantid::Kernel::Logger::warning().
Referenced by exec().
createEventWorkspaceNoLog()
std::shared_ptr< DataObjects::EventWorkspace > Mantid::Algorithms::FilterEvents::createEventWorkspaceNoLog () private
create event workspace
createOutputWorkspacesMatrixCase()
void Mantid::Algorithms::FilterEvents::createOutputWorkspacesMatrixCase () private
create output workspaces in the case of using MatrixWorkspace for splitters
Create output EventWorkspaces in the case that the splitters are given by MatrixWorkspace Here is the list of class variables that will be updated:
m_outputWorkspacesMap: use (integer) group index to find output EventWorkspace
m_wsNames: vector of output workspaces
FilterEvents::createOutputWorkspacesMatrixCase
Definition at line 1204 of file FilterEvents.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::existsProperty(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_eventWS, m_matrixSplitterWS, m_outputWorkspacesMap, m_outputWSNameBase, m_progress, m_targetWorkspaceIndexSet, m_toGroupWS, m_vecSplitterTime, m_wsGroupdYMap, m_wsNames, Mantid::Kernel::Direction::Output, Mantid::API::Algorithm::progress(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by exec().
createOutputWorkspacesSplitters()
void Mantid::Algorithms::FilterEvents::createOutputWorkspacesSplitters () private
create output workspaces if the splitters are given in SplittersWorkspace
Create a list of EventWorkspace for output in the case that splitters are given by SplittersWorkspace.
Definition at line 1047 of file FilterEvents.cpp.
References Mantid::API::Algorithm::addTimer(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::declareProperty(), Mantid::API::Algorithm::existsProperty(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::API::TableRow::Int(), left, m_eventWS, m_hasInfoWS, m_informationWS, m_outputWorkspacesMap, m_outputWSNameBase, m_progress, m_runStartTime, m_splitters, m_targetWorkspaceIndexSet, m_toGroupWS, m_wsNames, name(), Mantid::Kernel::Direction::Output, Mantid::API::Algorithm::progress(), Mantid::Kernel::Strings::removeSpace(), right, Mantid::Kernel::IPropertyManager::setProperty(), Mantid::API::Algorithm::splitByTime(), and Mantid::API::TableRow::String().
Referenced by exec().
createOutputWorkspacesTableSplitterCase()
void Mantid::Algorithms::FilterEvents::createOutputWorkspacesTableSplitterCase () private
create output workspaces in the case of using TableWorlspace for splitters
Create output EventWorkspaces in the case that the splitters are given by TableWorkspace Here is the list of class variables that will be updated:
m_outputWorkspacesMap: use (integer) group index to find output EventWorkspace
m_wsNames: vector of output workspaces
FilterEvents::createOutputWorkspacesMatrixCase
Definition at line 1299 of file FilterEvents.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::existsProperty(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_eventWS, m_outputWorkspacesMap, m_outputWSNameBase, m_progress, m_runStartTime, m_targetWorkspaceIndexSet, m_toGroupWS, m_useArbTableSplitters, m_vecSplitterGroup, m_vecSplitterTime, m_wsGroupIndexTargetMap, m_wsNames, Mantid::Kernel::Direction::Output, Mantid::API::Algorithm::progress(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by exec().
examineAndSortEventWS()
void Mantid::Algorithms::FilterEvents::examineAndSortEventWS () private
Examine workspace.
Examine whether any spectrum does not have detector Warning message will be written out.
FilterEvents::examineEventWS
Definition at line 313 of file FilterEvents.cpp.
References EventFilterSkipNoDetTOFCorr, Mantid::API::Algorithm::g_log, Mantid::DataObjects::EventList::getNumberEvents(), m_eventWS, m_filterByPulseTime, m_specSkipType, m_tofCorrType, m_vecSkip, NoneCorrect, Mantid::Kernel::Logger::notice(), Mantid::DataObjects::PULSETIME_SORT, Mantid::DataObjects::PULSETIMETOF_SORT, and Mantid::Kernel::Logger::warning().
Referenced by exec().
exec()
void Mantid::Algorithms::FilterEvents::exec () override private virtual
Execution body.
Implements Mantid::API::Algorithm.
Definition at line 224 of file FilterEvents.cpp.
References copyNoneSplitLogs(), createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), examineAndSortEventWS(), filterEventsBySplitters(), filterEventsByVectorSplitters(), Mantid::API::Algorithm::g_log, generateSplitterTSP(), generateSplitterTSPalpha(), groupOutputWorkspace(), m_eventWS, m_outputWorkspacesMap, m_progress, m_toGroupWS, m_useArbTableSplitters, m_useSplittersWorkspace, mapSplitterTSPtoWorkspaces(), processAlgorithmProperties(), processMatrixSplitterWorkspace(), processSplittersWorkspace(), processTableSplittersWorkspace(), Mantid::API::Algorithm::progress(), Mantid::Kernel::IPropertyManager::setProperty(), setupDetectorTOFCalibration(), splitTimeSeriesLogs(), and Mantid::Kernel::Logger::warning().
filterEventsBySplitters()
void Mantid::Algorithms::FilterEvents::filterEventsBySplitters (double progressamount) private
Filter events by splitters in format of Splitter.
Main filtering method Structure: per spectrum --> per workspace.
Definition at line 1609 of file FilterEvents.cpp.
References Mantid::API::Algorithm::addTimer(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, index, m_detTofFactors, m_detTofOffsets, m_eventWS, m_filterByPulseTime, m_outputWorkspacesMap, m_splitters, m_tofCorrType, m_vecSkip, NoneCorrect, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_START_INTERRUPT_REGION, Mantid::API::Algorithm::progress(), Mantid::DataObjects::EventList::splitByFullTime(), and Mantid::DataObjects::EventList::splitByPulseTime().
Referenced by exec().
filterEventsByVectorSplitters()
void Mantid::Algorithms::FilterEvents::filterEventsByVectorSplitters (double progressamount) private
Filter events by splitters in format of vector.
Split events by splitters represented by vector.
Definition at line 1659 of file FilterEvents.cpp.
References Mantid::API::Algorithm::g_log, index, m_dbWSIndex, m_detTofFactors, m_detTofOffsets, m_eventWS, m_filterByPulseTime, m_outputWorkspacesMap, m_targetWorkspaceIndexSet, m_tofCorrType, m_useDBSpectrum, m_vecSkip, m_vecSplitterGroup, m_vecSplitterTime, NoneCorrect, Mantid::Kernel::Logger::notice(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_START_INTERRUPT_REGION, Mantid::API::Algorithm::progress(), Mantid::DataObjects::EventList::splitByFullTimeMatrixSplitter(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
generateSplitterTSP()
void Mantid::Algorithms::FilterEvents::generateSplitterTSP (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > & split_tsp_vec) private
Generate a vector of integer time series property for each splitter corresponding to each target (in integer) in each splitter-time-series-property, 1 stands for include and 0 stands for time for neutrons to be discarded.
If there is no UN-DEFINED
FilterEvents::generateSplitterTSP
Parameters
split_tsp_vec
Definition at line 1758 of file FilterEvents.cpp.
References Mantid::Kernel::TimeSeriesProperty< TYPE >::addValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::clear(), error, Mantid::Kernel::TimeSeriesProperty< TYPE >::firstValue(), m_maxTargetIndex, m_runStartTime, m_vecSplitterGroup, m_vecSplitterTime, and Mantid::Kernel::TimeSeriesProperty< TYPE >::size().
Referenced by exec().
generateSplitterTSPalpha()
void Mantid::Algorithms::FilterEvents::generateSplitterTSPalpha (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > & split_tsp_vec) private
Generate the splitter's time series property (log) the splitters workspace.
FilterEvents::generateSplitterTSPalpha
Parameters
split_tsp_vec
Definition at line 1823 of file FilterEvents.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_maxTargetIndex, m_runStartTime, and m_splitters.
Referenced by exec().
getTimeSeriesLogNames()
std::vector< std::string > Mantid::Algorithms::FilterEvents::getTimeSeriesLogNames () private
get the names of all the time series properties in the input workspace's Run object
Get all filterable logs' names (double and integer)
Returns
Vector of names of logs
Definition at line 1934 of file FilterEvents.cpp.
References m_eventWS, and Mantid::Kernel::Property::name().
groupOutputWorkspace()
void Mantid::Algorithms::FilterEvents::groupOutputWorkspace () private
group output workspaces
FilterEvents::groupOutputWorkspace
Definition at line 487 of file FilterEvents.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::existsProperty(), Mantid::API::Algorithm::g_log, Mantid::Kernel::SingletonHolder< T >::Instance(), m_outputWSNameBase, m_progress, m_toGroupWS, m_wsNames, Mantid::Kernel::Direction::Output, Mantid::API::Algorithm::progress(), Mantid::Kernel::DataService< T >::retrieve(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by exec().
init()
void Mantid::Algorithms::FilterEvents::init () override private virtual
Declare Inputs.
Implements Mantid::API::Algorithm.
Definition at line 72 of file FilterEvents.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertySettings().
mapSplitterTSPtoWorkspaces()
void Mantid::Algorithms::FilterEvents::mapSplitterTSPtoWorkspaces (std::vector< std::unique_ptr< Kernel::TimeSeriesProperty< int > > > & split_tsp_vec) private
Add time series property 'Splitter' to each child workspace.
add the splitter TimeSeriesProperty logs to each workspace
FilterEvents::mapSplitterTSPtoWorkspaces
Parameters
split_tsp_vec
Definition at line 1865 of file FilterEvents.cpp.
References calculate_duration(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_outputWorkspacesMap, and Mantid::Kernel::Logger::warning().
Referenced by exec().
name()
const std::string Mantid::Algorithms::FilterEvents::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 39 of file FilterEvents.h.
Referenced by createOutputWorkspacesSplitters().
processAlgorithmProperties()
void Mantid::Algorithms::FilterEvents::processAlgorithmProperties () private
Process user input properties.
Process input properties.
Definition at line 368 of file FilterEvents.cpp.
References CustomizedCorrect, DirectCorrect, ElasticCorrect, Mantid::Kernel::Logger::error(), EventFilterSkipNoDet, EventFilterSkipNoDetTOFCorr, Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), IndirectCorrect, Mantid::API::Algorithm::isEmpty(), m_dbWSIndex, m_eventWS, m_filterByPulseTime, m_filterStartTime, m_hasInfoWS, m_informationWS, m_isSplittersRelativeTime, m_matrixSplitterWS, m_outputWSNameBase, m_runStartTime, m_specSkipType, m_splitSampleLogs, m_splittersWorkspace, m_splitterTableWorkspace, m_tofCorrType, m_toGroupWS, m_useArbTableSplitters, m_useDBSpectrum, m_useSplittersWorkspace, and NoneCorrect.
Referenced by exec().
processMatrixSplitterWorkspace()
void Mantid::Algorithms::FilterEvents::processMatrixSplitterWorkspace () private
process splitters given by a MatrixWorkspace
FilterEvents::processMatrixSplitterWorkspace Purpose: Convert the splitters in MatrixWorkspace to m_vecSplitterTime and m_vecSplitterGroup Requirements: m_matrixSplitterWS has valid value vecX's size must be one larger than and that of vecY of m_matrixSplitterWS Guarantees.
Splitters stored in m_matrixSpliterWS are transformed to "m_vecSplitterTime" and "m_vecSplitterGroup", whose sizes differ by 1.
Y values are mapped to integer group index stored in "m_vecSplitterGroup". The mapping is recorded in "m_yIndexMap" and "m_wsGroupdYMap" "m_maxTargetIndex" is used to register the maximum group index Negative Y is defined as "undefined" Note: there is NO undefined split region here, while any NEGATIVE Y value is defined as "undefined splitter"
Definition at line 878 of file FilterEvents.cpp.
References m_filterStartTime, m_isSplittersRelativeTime, m_matrixSplitterWS, m_maxTargetIndex, m_targetWorkspaceIndexSet, m_vecSplitterGroup, m_vecSplitterTime, m_wsGroupdYMap, m_yIndexMap, UNDEFINED_SPLITTING_TARGET(), Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by exec().
processSplittersWorkspace()
void Mantid::Algorithms::FilterEvents::processSplittersWorkspace () private
process splitters given by a SplittersWorkspace
Purpose: Convert SplitterWorkspace object to TimeSplitterType (sorted vector) and create a map for all workspace group number Requirements: Gaurantees:
Update of m_maxTargetIndex: it can be zero in SplittersWorkspace case
FilterEvents::processSplittersWorkspace
Definition at line 761 of file FilterEvents.cpp.
References Mantid::API::Algorithm::g_log, m_hasInfoWS, m_informationWS, m_maxTargetIndex, m_progress, m_splitters, m_splittersWorkspace, m_targetWorkspaceIndexSet, Mantid::API::Algorithm::progress(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
processTableSplittersWorkspace()
void Mantid::Algorithms::FilterEvents::processTableSplittersWorkspace () private
process the input splitters given by a TableWorkspace The method will transfer the start/stop time to "m_vecSplitterTime" and map the splitting target (in string) to "m_vecSplitterGroup".
The mapping will be recorded in "m_targetIndexMap" and "m_wsGroupIndexTargetMap". Also, "m_maxTargetIndex" is set up to record the highest target group/index, i.e., max value of m_vecSplitterGroup
Definition at line 959 of file FilterEvents.cpp.
References m_isSplittersRelativeTime, m_maxTargetIndex, m_runStartTime, m_splitterTableWorkspace, m_targetIndexMap, m_targetWorkspaceIndexSet, m_vecSplitterGroup, m_vecSplitterTime, m_wsGroupIndexTargetMap, TOLERANCE(), and UNDEFINED_SPLITTING_TARGET().
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::Algorithms::FilterEvents::seeAlso () const inline override virtual
Function to return all of the seeAlso algorithms related to this algorithm.
Implements Mantid::API::IAlgorithm.
Definition at line 48 of file FilterEvents.h.
setupCustomizedTOFCorrection()
void Mantid::Algorithms::FilterEvents::setupCustomizedTOFCorrection () private
Set up detector calibration parameters from customized values.
Set up corrections with customized TOF correction input The first column must be either DetectorID or Spectrum (from 0... as workspace index) The second column must be Correction or CorrectFactor, a number between 0 and 1, i.e, [0, 1] The third column is optional as shift in unit of second.
Definition at line 1472 of file FilterEvents.cpp.
References Mantid::API::Algorithm::g_log, Mantid::API::ISpectrum::getDetectorIDs(), Mantid::API::Algorithm::getProperty(), m_detCorrectWorkspace, m_detTofFactors, m_detTofOffsets, m_eventWS, and Mantid::Kernel::Logger::warning().
Referenced by setupDetectorTOFCalibration().
setupDetectorTOFCalibration()
void Mantid::Algorithms::FilterEvents::setupDetectorTOFCalibration () private
Set up detector calibration parameters.
Set up neutron event's TOF correction.
It can be (1) parsed from TOF-correction table workspace to vectors, (2) created according to detector's position in instrument; (3) or no correction,i.e., correction value is equal to 1. Offset should be as F*TOF + B
Definition at line 1398 of file FilterEvents.cpp.
References CustomizedCorrect, DirectCorrect, ElasticCorrect, Mantid::Algorithms::Correction::factor, IndirectCorrect, m_detTofFactors, m_detTofOffsets, m_eventWS, m_tofCorrType, m_vecSkip, Mantid::Algorithms::Correction::offset, Mantid::Kernel::IPropertyManager::setProperty(), setupCustomizedTOFCorrection(), setupDirectTOFCorrection(), setupElasticTOFCorrection(), and setupIndirectTOFCorrection().
Referenced by exec().
setupDirectTOFCorrection()
TimeAtSampleStrategy * Mantid::Algorithms::FilterEvents::setupDirectTOFCorrection () const private
Set up detector calibration parmaeters for direct inelastic scattering instrument.
Definition at line 1443 of file FilterEvents.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::isEmpty(), and m_eventWS.
Referenced by setupDetectorTOFCalibration().
setupElasticTOFCorrection()
TimeAtSampleStrategy * Mantid::Algorithms::FilterEvents::setupElasticTOFCorrection () const private
Set up detector calibration parameters for elastic scattering instrument.
Definition at line 1438 of file FilterEvents.cpp.
References m_eventWS.
Referenced by setupDetectorTOFCalibration().
setupIndirectTOFCorrection()
TimeAtSampleStrategy * Mantid::Algorithms::FilterEvents::setupIndirectTOFCorrection () const private
Set up detector calibration parameters for indirect inelastic scattering instrument.
Definition at line 1461 of file FilterEvents.cpp.
References m_eventWS.
Referenced by setupDetectorTOFCalibration().
splitTimeSeriesLogs()
void Mantid::Algorithms::FilterEvents::splitTimeSeriesLogs (const std::vector< Kernel::TimeSeriesProperty< int > * > & int_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< double > * > & dbl_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< bool > * > & bool_tsp_vector, const std::vector< Kernel::TimeSeriesProperty< std::string > * > & string_tsp_vector) private
Split ALL the TimeSeriesProperty sample logs to all the output workspace.
FilterEvents::splitTimeSeriesLogs
Parameters
int_tsp_vector :: vector of itneger tps
dbl_tsp_vector :: vector of double tsp
bool_tsp_vector :: vector of boolean tsp
string_tsp_vector :: vector of string tsp
Definition at line 626 of file FilterEvents.cpp.
References convertSplittersWorkspaceToVectors(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_outputWorkspacesMap, m_targetWorkspaceIndexSet, m_useSplittersWorkspace, m_vecSplitterTime, and splitTimeSeriesProperty().
Referenced by exec().
splitTimeSeriesProperty()
template<typename TYPE > void Mantid::Algorithms::FilterEvents::splitTimeSeriesProperty (Kernel::TimeSeriesProperty< TYPE > * tsp, std::vector< Types::Core::DateAndTime > & split_datetime_vec, const int max_target_index) private
split one single time-series property (template)
FilterEvents::splitTimeSeriesProperty
Parameters
tsp :: a time series property instance
split_datetime_vec :: splitter
max_target_index :: maximum number of separated time series
Definition at line 705 of file FilterEvents.cpp.
References Mantid::Kernel::TimeSeriesProperty< TYPE >::firstTime(), Mantid::Kernel::TimeSeriesProperty< TYPE >::firstValue(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_outputWorkspacesMap, m_vecSplitterGroup, Mantid::Kernel::Property::name(), Mantid::Kernel::TimeSeriesProperty< TYPE >::size(), Mantid::Kernel::TimeSeriesProperty< TYPE >::splitByTimeVector(), Mantid::Kernel::Property::units(), and Mantid::Geometry::x.
Referenced by splitTimeSeriesLogs().
summary()
const std::string Mantid::Algorithms::FilterEvents::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 41 of file FilterEvents.h.
validateInputs()
std::map< std::string, std::string > Mantid::Algorithms::FilterEvents::validateInputs () override virtual
Method checking errors on ALL the inputs, before execution.
For use mostly in dialogs.
Implements Mantid::API::IAlgorithm.
Definition at line 168 of file FilterEvents.cpp.
References Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), and Mantid::API::Algorithm::isEmpty().
version()
int Mantid::Algorithms::FilterEvents::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 47 of file FilterEvents.h.
Member Data Documentation
m_dbWSIndex
int Mantid::Algorithms::FilterEvents::m_dbWSIndex private
Definition at line 196 of file FilterEvents.h.
Referenced by filterEventsByVectorSplitters(), and processAlgorithmProperties().
m_detCorrectWorkspace
DataObjects::TableWorkspace_sptr Mantid::Algorithms::FilterEvents::m_detCorrectWorkspace private
Definition at line 148 of file FilterEvents.h.
Referenced by setupCustomizedTOFCorrection().
m_detTofFactors
std::vector<double> Mantid::Algorithms::FilterEvents::m_detTofFactors private
Definition at line 161 of file FilterEvents.h.
Referenced by filterEventsBySplitters(), filterEventsByVectorSplitters(), setupCustomizedTOFCorrection(), and setupDetectorTOFCalibration().
m_detTofOffsets
std::vector<double> Mantid::Algorithms::FilterEvents::m_detTofOffsets private
Definition at line 160 of file FilterEvents.h.
Referenced by filterEventsBySplitters(), filterEventsByVectorSplitters(), setupCustomizedTOFCorrection(), and setupDetectorTOFCalibration().
m_eventWS
DataObjects::EventWorkspace_sptr Mantid::Algorithms::FilterEvents::m_eventWS private
Definition at line 144 of file FilterEvents.h.
Referenced by copyNoneSplitLogs(), createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), examineAndSortEventWS(), exec(), filterEventsBySplitters(), filterEventsByVectorSplitters(), getTimeSeriesLogNames(), processAlgorithmProperties(), setupCustomizedTOFCorrection(), setupDetectorTOFCalibration(), setupDirectTOFCorrection(), setupElasticTOFCorrection(), and setupIndirectTOFCorrection().
m_filterByPulseTime
bool Mantid::Algorithms::FilterEvents::m_filterByPulseTime private
Definition at line 163 of file FilterEvents.h.
Referenced by examineAndSortEventWS(), filterEventsBySplitters(), filterEventsByVectorSplitters(), and processAlgorithmProperties().
m_filterStartTime
Types::Core::DateAndTime Mantid::Algorithms::FilterEvents::m_filterStartTime private
Definition at line 209 of file FilterEvents.h.
Referenced by processAlgorithmProperties(), and processMatrixSplitterWorkspace().
m_hasInfoWS
bool Mantid::Algorithms::FilterEvents::m_hasInfoWS private
Definition at line 166 of file FilterEvents.h.
Referenced by createOutputWorkspacesSplitters(), processAlgorithmProperties(), and processSplittersWorkspace().
m_informationWS
DataObjects::TableWorkspace_sptr Mantid::Algorithms::FilterEvents::m_informationWS private
Definition at line 165 of file FilterEvents.h.
Referenced by createOutputWorkspacesSplitters(), processAlgorithmProperties(), and processSplittersWorkspace().
m_isSplittersRelativeTime
bool Mantid::Algorithms::FilterEvents::m_isSplittersRelativeTime private
Definition at line 207 of file FilterEvents.h.
Referenced by processAlgorithmProperties(), processMatrixSplitterWorkspace(), and processTableSplittersWorkspace().
m_matrixSplitterWS
API::MatrixWorkspace_const_sptr Mantid::Algorithms::FilterEvents::m_matrixSplitterWS private
Definition at line 147 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), processAlgorithmProperties(), and processMatrixSplitterWorkspace().
m_maxTargetIndex
int Mantid::Algorithms::FilterEvents::m_maxTargetIndex private
Definition at line 155 of file FilterEvents.h.
Referenced by convertSplittersWorkspaceToVectors(), generateSplitterTSP(), generateSplitterTSPalpha(), processMatrixSplitterWorkspace(), processSplittersWorkspace(), and processTableSplittersWorkspace().
m_outputWorkspacesMap
std::map<int, DataObjects::EventWorkspace_sptr> Mantid::Algorithms::FilterEvents::m_outputWorkspacesMap private
Definition at line 157 of file FilterEvents.h.
Referenced by copyNoneSplitLogs(), createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), exec(), filterEventsBySplitters(), filterEventsByVectorSplitters(), mapSplitterTSPtoWorkspaces(), splitTimeSeriesLogs(), and splitTimeSeriesProperty().
m_outputWSNameBase
std::string Mantid::Algorithms::FilterEvents::m_outputWSNameBase private
Base of output workspace's name.
Definition at line 171 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), groupOutputWorkspace(), and processAlgorithmProperties().
m_progress
double Mantid::Algorithms::FilterEvents::m_progress private
Definition at line 168 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), exec(), groupOutputWorkspace(), and processSplittersWorkspace().
m_runStartTime
Types::Core::DateAndTime Mantid::Algorithms::FilterEvents::m_runStartTime private
Definition at line 211 of file FilterEvents.h.
Referenced by createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), generateSplitterTSP(), generateSplitterTSPalpha(), processAlgorithmProperties(), and processTableSplittersWorkspace().
m_specSkipType
EVENTFILTERSKIP Mantid::Algorithms::FilterEvents::m_specSkipType private
Spectrum skip type.
Definition at line 202 of file FilterEvents.h.
Referenced by examineAndSortEventWS(), and processAlgorithmProperties().
m_splitSampleLogs
bool Mantid::Algorithms::FilterEvents::m_splitSampleLogs private
Flag to split sample logs.
Definition at line 192 of file FilterEvents.h.
Referenced by processAlgorithmProperties().
m_splitters
Kernel::TimeSplitterType Mantid::Algorithms::FilterEvents::m_splitters private
Definition at line 156 of file FilterEvents.h.
Referenced by convertSplittersWorkspaceToVectors(), createOutputWorkspacesSplitters(), filterEventsBySplitters(), generateSplitterTSPalpha(), and processSplittersWorkspace().
m_splittersWorkspace
DataObjects::SplittersWorkspace_sptr Mantid::Algorithms::FilterEvents::m_splittersWorkspace private
Definition at line 145 of file FilterEvents.h.
Referenced by processAlgorithmProperties(), and processSplittersWorkspace().
m_splitterTableWorkspace
DataObjects::TableWorkspace_sptr Mantid::Algorithms::FilterEvents::m_splitterTableWorkspace private
Definition at line 146 of file FilterEvents.h.
Referenced by processAlgorithmProperties(), and processTableSplittersWorkspace().
m_targetIndexMap
std::map<std::string, int> Mantid::Algorithms::FilterEvents::m_targetIndexMap private
TableWorkspace splitters: from target map to vector workspace group-index These 2 maps are complimentary to each other.
Definition at line 175 of file FilterEvents.h.
Referenced by processTableSplittersWorkspace().
m_targetWorkspaceIndexSet
std::set<int> Mantid::Algorithms::FilterEvents::m_targetWorkspaceIndexSet private
Definition at line 154 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), filterEventsByVectorSplitters(), processMatrixSplitterWorkspace(), processSplittersWorkspace(), processTableSplittersWorkspace(), and splitTimeSeriesLogs().
m_tofCorrType
TOFCorrectionType Mantid::Algorithms::FilterEvents::m_tofCorrType private
TOF detector/sample correction type.
Definition at line 199 of file FilterEvents.h.
Referenced by examineAndSortEventWS(), filterEventsBySplitters(), filterEventsByVectorSplitters(), processAlgorithmProperties(), and setupDetectorTOFCalibration().
m_toGroupWS
bool Mantid::Algorithms::FilterEvents::m_toGroupWS private
Flag to group workspace.
Definition at line 183 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), exec(), groupOutputWorkspace(), and processAlgorithmProperties().
m_useArbTableSplitters
bool Mantid::Algorithms::FilterEvents::m_useArbTableSplitters private
Definition at line 152 of file FilterEvents.h.
Referenced by createOutputWorkspacesTableSplitterCase(), exec(), and processAlgorithmProperties().
m_useDBSpectrum
bool Mantid::Algorithms::FilterEvents::m_useDBSpectrum private
Debug.
Definition at line 195 of file FilterEvents.h.
Referenced by filterEventsByVectorSplitters(), and processAlgorithmProperties().
m_useSplittersWorkspace
bool Mantid::Algorithms::FilterEvents::m_useSplittersWorkspace private
Flag to use matrix splitters or table splitters.
Definition at line 151 of file FilterEvents.h.
Referenced by convertSplittersWorkspaceToVectors(), exec(), processAlgorithmProperties(), and splitTimeSeriesLogs().
m_vecSkip
std::vector<bool> Mantid::Algorithms::FilterEvents::m_vecSkip private
Vector for skip information.
Definition at line 204 of file FilterEvents.h.
Referenced by examineAndSortEventWS(), filterEventsBySplitters(), filterEventsByVectorSplitters(), and setupDetectorTOFCalibration().
m_vecSplitterGroup
std::vector<int> Mantid::Algorithms::FilterEvents::m_vecSplitterGroup private
Vector for splitting group.
Definition at line 189 of file FilterEvents.h.
Referenced by convertSplittersWorkspaceToVectors(), createOutputWorkspacesTableSplitterCase(), filterEventsByVectorSplitters(), generateSplitterTSP(), processMatrixSplitterWorkspace(), processTableSplittersWorkspace(), and splitTimeSeriesProperty().
m_vecSplitterTime
std::vector<int64_t> Mantid::Algorithms::FilterEvents::m_vecSplitterTime private
Vector for splitting time FIXME - shall we convert this to DateAndTime???.
Need to do speed test!
Definition at line 187 of file FilterEvents.h.
Referenced by convertSplittersWorkspaceToVectors(), createOutputWorkspacesMatrixCase(), createOutputWorkspacesTableSplitterCase(), filterEventsByVectorSplitters(), generateSplitterTSP(), processMatrixSplitterWorkspace(), processTableSplittersWorkspace(), and splitTimeSeriesLogs().
m_wsGroupdYMap
std::map<uint32_t, int> Mantid::Algorithms::FilterEvents::m_wsGroupdYMap private
Definition at line 180 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), and processMatrixSplitterWorkspace().
m_wsGroupIndexTargetMap
std::map<int, std::string> Mantid::Algorithms::FilterEvents::m_wsGroupIndexTargetMap private
Definition at line 176 of file FilterEvents.h.
Referenced by createOutputWorkspacesTableSplitterCase(), and processTableSplittersWorkspace().
m_wsNames
std::vector<std::string> Mantid::Algorithms::FilterEvents::m_wsNames private
Definition at line 158 of file FilterEvents.h.
Referenced by createOutputWorkspacesMatrixCase(), createOutputWorkspacesSplitters(), createOutputWorkspacesTableSplitterCase(), and groupOutputWorkspace().
m_yIndexMap
std::map<int, uint32_t> Mantid::Algorithms::FilterEvents::m_yIndexMap private
MatrixWorkspace splitters:
Definition at line 179 of file FilterEvents.h.
Referenced by processMatrixSplitterWorkspace().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/FilterEvents.h
Framework/Algorithms/src/FilterEvents.cpp