Mantid: Mantid::API::IMDEventWorkspace Class Reference
Mantid::API::IMDEventWorkspace Class Reference abstract
Abstract base class for multi-dimension event workspaces (MDEventWorkspace).
#include <IMDEventWorkspace.h>
Public Member Functions
IMDEventWorkspace_uptr clone () const
Returns a clone of the workspace.
IMDEventWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
Mantid::API::MDNormalization displayNormalization () const override=0
Mantid::API::MDNormalization displayNormalizationHisto () const override=0
bool fileNeedsUpdating () const
virtual Mantid::API::BoxController_const_sptr getBoxController () const =0
virtual Mantid::API::BoxController_sptr getBoxController ()=0
virtual std::vector< std::string > getBoxControllerStats () const =0
Returns some information about the box controller, to be displayed in the GUI, for example.
virtual void getBoxes (std::vector< API::IMDNode * > &boxes, size_t maxDepth, bool leafOnly)=0
virtual std::string getEventTypeName () const =0
Return the type of event contained, as a string. MDEvent or MDLeanEvent.
virtual std::vector< Mantid::Geometry::MDDimensionExtents< coord_t > > getMinimumExtents (size_t depth=2) const =0
Get the minimum extents that hold the data.
virtual bool hasOrientedLattice () const override
IMDEventWorkspace ()
Empty constructor.
virtual void initialize ()=0
Perform initialization after dimensions (and others) have been set.
virtual bool isFileBacked () const =0
IMDEventWorkspace & operator= (const IMDEventWorkspace &)=delete
virtual void refreshCache ()=0
Refresh the cache (integrated signal of each box)
virtual void setBox (API::IMDNode *box)=0
virtual void setCoordinateSystem (const Mantid::Kernel::SpecialCoordinateSystem coordinateSystem)=0
virtual void setDisplayNormalization (Mantid::API::MDNormalization preferredNormalization)=0
Preferred visual normalization method.
virtual void setDisplayNormalizationHisto (Mantid::API::MDNormalization preferredNormalizationHisto)=0
Preferred visual normalizaiton method for any histo workspaces created from this.
virtual void setFileBacked ()=0
set filebacked on the contained box
void setFileNeedsUpdating (bool value)
Sets the marker set to true when a file-backed workspace needs its back-end file updated (by calling SaveMD(UpdateFileBackEnd=1))
virtual void setMinRecursionDepth (size_t depth)=0
Recurse down to a minimum depth.
virtual size_t sizeofEvent () const =0
Return the size(in bytes) for the event, which this workspace contains.
virtual void splitAllIfNeeded (Kernel::ThreadScheduler *ts)=0
Split all boxes that exceed the split threshold.
virtual void splitBox ()=0
Split the top-level MDBox into a MDGridBox.
bool threadSafe () const override
Is the workspace thread-safe.
Public Member Functions inherited from Mantid::API::IMDWorkspace
std::string changeQConvention ()
virtual void clearFileBacked (bool)
if a workspace was filebacked, this should clear file-based status, delete file-based information and close related files.
virtual void clearMDMasking ()=0
Clear existing masks.
std::unique_ptr< IMDWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< IMDWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
std::unique_ptr< IMDIterator > createIterator (Mantid::Geometry::MDImplicitFunction *function=nullptr) const
Creates a single iterator and returns it.
virtual std::vector< std::unique_ptr< IMDIterator > > createIterators (size_t suggestedNumCores=1, Mantid::Geometry::MDImplicitFunction *function=nullptr) const =0
Creates a new iterator pointing to the first cell in the workspace.
const std::string & getConvention () const
virtual LinePlot getLinePlot (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const
Method to generate a line plot through a MD-workspace.
virtual uint64_t getNEvents () const =0
virtual uint64_t getNPoints () const =0
Get the number of points associated with the workspace.
virtual signal_t getSignalAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const =0
Returns the (normalized) signal at a given coordinates.
signal_t getSignalAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates.
virtual signal_t getSignalWithMaskAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const =0
Returns the (normalized) signal at a given coordinates or 0 if the value.
signal_t getSignalWithMaskAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates or 0 if masked.
virtual Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const =0
IMDWorkspace ()
Default constructor.
virtual bool isMDHistoWorkspace () const
virtual ITableWorkspace_sptr makeBoxTable (size_t, size_t)
this is the method to build table workspace from any workspace.
IMDWorkspace & operator= (const IMDWorkspace &other)=delete
void setConvention (std::string convention)
Sets the convention of the workspace.
virtual void setMDMasking (std::unique_ptr< Mantid::Geometry::MDImplicitFunction > maskingRegion)=0
Setter for the masking region.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
virtual size_t getMemorySize () const =0
Get the footprint in memory in bytes.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
virtual const std::string getTitle () const
Get the workspace title.
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
virtual void setTitle (const std::string &)
Set the title of the workspace.
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
virtual const std::string id () const =0
A string ID for the class.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::MDGeometry
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const
Get a dimension.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const
Get a dimension.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumDims () const
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Public Member Functions inherited from Mantid::API::MultipleExperimentInfos
uint16_t addExperimentInfo (const ExperimentInfo_sptr &ei)
Add a new ExperimentInfo to this MDEventWorkspace.
void copyExperimentInfos (const MultipleExperimentInfos &other)
Copy the experiment infos from another.
ExperimentInfo_sptr getExperimentInfo (const uint16_t expInfoIndex)
Get the ExperimentInfo for the given Experiment-Info Index.
ExperimentInfo_const_sptr getExperimentInfo (const uint16_t expInfoIndex) const
Get the ExperimentInfo for the given Experiment-Info Index.
uint16_t getNumExperimentInfo () const
bool hasOrientedLattice () const
MultipleExperimentInfos ()=default
MultipleExperimentInfos (const MultipleExperimentInfos &other)
Copy constructor.
MultipleExperimentInfos & operator= (const MultipleExperimentInfos &other)
void setExperimentInfo (const uint16_t expInfoIndex, ExperimentInfo_sptr ei)
Replace the ExperimentInfo entry at a given place.
virtual ~MultipleExperimentInfos ()=default
Protected Member Functions
IMDEventWorkspace (const IMDEventWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::IMDWorkspace
IMDWorkspace (const IMDWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void makeSinglePointWithNaN (std::vector< coord_t > &x, std::vector< signal_t > &y, std::vector< signal_t > &e) const
Make a single point with NaN as the signal and error This can be returned when there would otherwise be nothing to plot.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::MDGeometry
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Member Functions inherited from Mantid::API::MultipleExperimentInfos
const std::string toString () const
Returns a string description of the object.
Protected Attributes
bool m_fileNeedsUpdating
Marker set to true when a file-backed workspace needs its back-end file updated (by calling SaveMD(UpdateFileBackEnd=1))
Protected Attributes inherited from Mantid::API::MDGeometry
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Private Member Functions
IMDEventWorkspace * doClone () const override=0
Virtual clone method. Not implemented to force implementation in children.
IMDEventWorkspace * doCloneEmpty () const override=0
Virtual cloneEmpty method.
Detailed Description
Abstract base class for multi-dimension event workspaces (MDEventWorkspace).
This class will handle as much of the common operations as possible; but since MDEventWorkspace is a templated class, that makes some aspects impossible.
Author
Janik Zikovsky, SNS
Date
Dec 3, 2010
Definition at line 36 of file IMDEventWorkspace.h.
Constructor & Destructor Documentation
IMDEventWorkspace() [1/2]
Mantid::API::IMDEventWorkspace::IMDEventWorkspace ()
Empty constructor.
Definition at line 20 of file IMDEventWorkspace.cpp.
IMDEventWorkspace() [2/2]
Mantid::API::IMDEventWorkspace::IMDEventWorkspace (const IMDEventWorkspace &) protected default
Protected copy constructor. May be used by childs for cloning.
References Mantid::Kernel::toString().
Member Function Documentation
clone()
IMDEventWorkspace_uptr Mantid::API::IMDEventWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 41 of file IMDEventWorkspace.h.
cloneEmpty()
IMDEventWorkspace_uptr Mantid::API::IMDEventWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 44 of file IMDEventWorkspace.h.
displayNormalization()
Mantid::API::MDNormalization Mantid::API::IMDEventWorkspace::displayNormalization () const override pure virtual
Returns
normalization preferred for visualization. Set to none for the generic case, but overriden elsewhere.
Reimplemented from Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
displayNormalizationHisto()
Mantid::API::MDNormalization Mantid::API::IMDEventWorkspace::displayNormalizationHisto () const override pure virtual
Returns
normalization preferred for visualization of histo workspaces. Set to none for the generic case, but overriden elsewhere.
Reimplemented from Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
doClone()
IMDEventWorkspace * Mantid::API::IMDEventWorkspace::doClone () const override private pure virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
doCloneEmpty()
IMDEventWorkspace * Mantid::API::IMDEventWorkspace::doCloneEmpty () const override private pure virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
fileNeedsUpdating()
bool Mantid::API::IMDEventWorkspace::fileNeedsUpdating () const
Returns
the marker set to true when a file-backed workspace needs its back-end file updated (by calling SaveMD(UpdateFileBackEnd=1))
Definition at line 26 of file IMDEventWorkspace.cpp.
References m_fileNeedsUpdating.
Referenced by Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), and Mantid::MDAlgorithms::SaveMD::doSaveEvents().
getBoxController() [1/2]
virtual Mantid::API::BoxController_const_sptr Mantid::API::IMDEventWorkspace::getBoxController () const pure virtual
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
getBoxController() [2/2]
virtual Mantid::API::BoxController_sptr Mantid::API::IMDEventWorkspace::getBoxController () pure virtual
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Referenced by export_IMDEventWorkspace().
getBoxControllerStats()
virtual std::vector< std::string > Mantid::API::IMDEventWorkspace::getBoxControllerStats () const pure virtual
Returns some information about the box controller, to be displayed in the GUI, for example.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Referenced by toString().
getBoxes()
virtual void Mantid::API::IMDEventWorkspace::getBoxes (std::vector< API::IMDNode * > & boxes, size_t maxDepth, bool leafOnly) pure virtual
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
getEventTypeName()
virtual std::string Mantid::API::IMDEventWorkspace::getEventTypeName () const pure virtual
Return the type of event contained, as a string. MDEvent or MDLeanEvent.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
getMinimumExtents()
virtual std::vector< Mantid::Geometry::MDDimensionExtents< coord_t > > Mantid::API::IMDEventWorkspace::getMinimumExtents (size_t depth = 2) const pure virtual
Get the minimum extents that hold the data.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
hasOrientedLattice()
virtual bool Mantid::API::IMDEventWorkspace::hasOrientedLattice () const inline override virtual
Implements Mantid::API::IMDWorkspace.
Definition at line 103 of file IMDEventWorkspace.h.
initialize()
virtual void Mantid::API::IMDEventWorkspace::initialize () pure virtual
Perform initialization after dimensions (and others) have been set.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
isFileBacked()
virtual bool Mantid::API::IMDEventWorkspace::isFileBacked () const pure virtual
Returns
true if the workspace is file-backed
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Referenced by threadSafe().
operator=()
IMDEventWorkspace & Mantid::API::IMDEventWorkspace::operator= (const IMDEventWorkspace &) delete
refreshCache()
virtual void Mantid::API::IMDEventWorkspace::refreshCache () pure virtual
Refresh the cache (integrated signal of each box)
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
setBox()
virtual void Mantid::API::IMDEventWorkspace::setBox (API::IMDNode * box) pure virtual
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
setCoordinateSystem()
virtual void Mantid::API::IMDEventWorkspace::setCoordinateSystem (const Mantid::Kernel::SpecialCoordinateSystem coordinateSystem) pure virtual
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
setDisplayNormalization()
virtual void Mantid::API::IMDEventWorkspace::setDisplayNormalization (Mantid::API::MDNormalization preferredNormalization) pure virtual
Preferred visual normalization method.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Referenced by export_IMDEventWorkspace().
setDisplayNormalizationHisto()
virtual void Mantid::API::IMDEventWorkspace::setDisplayNormalizationHisto (Mantid::API::MDNormalization preferredNormalizationHisto) pure virtual
Preferred visual normalizaiton method for any histo workspaces created from this.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
Referenced by export_IMDEventWorkspace().
setFileBacked()
virtual void Mantid::API::IMDEventWorkspace::setFileBacked () pure virtual
set filebacked on the contained box
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
setFileNeedsUpdating()
void Mantid::API::IMDEventWorkspace::setFileNeedsUpdating (bool value)
Sets the marker set to true when a file-backed workspace needs its back-end file updated (by calling SaveMD(UpdateFileBackEnd=1))
Parameters
value :: marker value
Definition at line 33 of file IMDEventWorkspace.cpp.
References m_fileNeedsUpdating, and value.
Referenced by Mantid::MDAlgorithms::MinusMD::doMinus(), Mantid::MDAlgorithms::MergeMD::doPlus(), Mantid::MDAlgorithms::SaveMD::doSaveEvents(), Mantid::MDAlgorithms::DivideMD::execEventScalar(), Mantid::MDAlgorithms::MultiplyMD::execEventScalar(), and Mantid::MDAlgorithms::FlippingRatioCorrectionMD::executeTemplatedMDE().
setMinRecursionDepth()
virtual void Mantid::API::IMDEventWorkspace::setMinRecursionDepth (size_t depth) pure virtual
Recurse down to a minimum depth.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
sizeofEvent()
virtual size_t Mantid::API::IMDEventWorkspace::sizeofEvent () const pure virtual
Return the size(in bytes) for the event, which this workspace contains.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
splitAllIfNeeded()
virtual void Mantid::API::IMDEventWorkspace::splitAllIfNeeded (Kernel::ThreadScheduler * ts) pure virtual
Split all boxes that exceed the split threshold.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
References Mantid::Kernel::threadSafe().
splitBox()
virtual void Mantid::API::IMDEventWorkspace::splitBox () pure virtual
Split the top-level MDBox into a MDGridBox.
Implemented in Mantid::DataObjects::MDEventWorkspace< MDE, nd >.
threadSafe()
bool Mantid::API::IMDEventWorkspace::threadSafe () const override virtual
Is the workspace thread-safe.
For MDEventWorkspaces, this means operations on separate boxes in separate threads. Don't try to write to the same box on different threads.
Returns
false if the workspace is file-backed.
Implements Mantid::Kernel::DataItem.
Definition at line 42 of file IMDEventWorkspace.cpp.
References isFileBacked().
toString()
const std::string Mantid::API::IMDEventWorkspace::toString () const override protected virtual
Serializes the object to a string.
Implements Mantid::Kernel::DataItem.
Definition at line 44 of file IMDEventWorkspace.cpp.
References getBoxControllerStats(), Mantid::API::IMDWorkspace::getNPoints(), Mantid::API::MultipleExperimentInfos::toString(), and Mantid::API::IMDWorkspace::toString().
Member Data Documentation
m_fileNeedsUpdating
bool Mantid::API::IMDEventWorkspace::m_fileNeedsUpdating protected
Marker set to true when a file-backed workspace needs its back-end file updated (by calling SaveMD(UpdateFileBackEnd=1))
Definition at line 114 of file IMDEventWorkspace.h.
Referenced by fileNeedsUpdating(), and setFileNeedsUpdating().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IMDEventWorkspace.h
Framework/API/src/IMDEventWorkspace.cpp