Mantid: Mantid::Algorithms::BinaryOperation Class Reference
Mantid::Algorithms::BinaryOperation Class Reference abstract
BinaryOperation supports the implementation of a binary operation on two input workspaces.
#include <BinaryOperation.h>
Public Types
using BinaryOperationTable = std::vector< int64_t >
BinaryOperationTable: a list of ints.
using BinaryOperationTable_sptr = std::shared_ptr< BinaryOperationTable >
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string name () const override=0
function to return a name of the algorithm, must be overridden in all algorithms
int version () const override=0
function to return a version of the algorithm, must be overridden in all algorithms
const std::string summary () const override=0
function returns a summary message that will be displayed in the default GUI, and in the help.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Static Public Member Functions
static BinaryOperationTable_sptr buildBinaryOperationTable (const API::MatrixWorkspace_const_sptr &lhs, const API::MatrixWorkspace_const_sptr &rhs)
Build up an BinaryOperationTable for performing a binary operation e.g.
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Protected Member Functions
virtual bool checkCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs) const
Checks the compatibility of the two workspaces.
virtual bool checkEventCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs)
Checks the compatibility of event-based processing of the two workspaces.
virtual void checkRequirements ()
Check what operation will be needed in order to apply the operation to these two types of workspaces.
virtual std::string checkSizeCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs) const
Checks the overall size compatibility of two workspaces.
void exec () override
Executes the algorithm.
virtual void execEvent (DataObjects::EventWorkspace_const_sptr lhs, DataObjects::EventWorkspace_const_sptr rhs)
Execution method for event workspaces, to be overridden as needed.
OperandType getOperandType (const API::MatrixWorkspace_const_sptr &ws)
Get the type of operand from a workspace.
bool handleSpecialDivideMinus ()
Special handling for 1-WS and 1/WS.
void init () override
Initialisation method.
virtual std::string inputPropName1 () const
The name of the first input workspace property.
virtual std::string inputPropName2 () const
The name of the second input workspace property.
virtual void operateOnRun (const API::Run &lhs, const API::Run &rhs, API::Run &ans) const
Only overridden by operations that affect the properties of the run (e.g.
virtual std::string outputPropName () const
The name of the output workspace property.
virtual void performBinaryOperation (const HistogramData::Histogram &lhs, const double rhsY, const double rhsE, HistogramData::HistogramY &YOut, HistogramData::HistogramE &EOut)=0
Carries out the binary operation when the right hand operand is a single number.
virtual void performBinaryOperation (const HistogramData::Histogram &lhs, const HistogramData::Histogram &rhs, HistogramData::HistogramY &YOut, HistogramData::HistogramE &EOut)=0
Carries out the binary operation on a single spectrum, with another spectrum as the right-hand operand.
virtual void performEventBinaryOperation (DataObjects::EventList &lhs, const DataObjects::EventList &rhs)
Carries out the binary operation IN-PLACE on a single EventList, with another EventList as the right-hand operand.
virtual void performEventBinaryOperation (DataObjects::EventList &lhs, const double &rhsY, const double &rhsE)
Carries out the binary operation IN-PLACE on a single EventList, with a single (double) value as the right-hand operand.
virtual void performEventBinaryOperation (DataObjects::EventList &lhs, const MantidVec &rhsX, const MantidVec &rhsY, const MantidVec &rhsE)
Carries out the binary operation IN-PLACE on a single EventList, with another (histogrammed) spectrum as the right-hand operand.
virtual bool propagateSpectraMask (const API::SpectrumInfo &lhsSpectrumInfo, const API::SpectrumInfo &rhsSpectrumInfo, const int64_t index, API::MatrixWorkspace &out, API::SpectrumInfo &outSpectrumInfo)
Checks if the spectra at the given index of either input workspace is masked.
virtual void setOutputUnits (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs, API::MatrixWorkspace_sptr out)
Should be overridden by operations that need to manipulate the units of the output workspace.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Protected Attributes
bool m_AllowDifferentNumberSpectra {false}
The property value.
bool m_ClearRHSWorkspace {false}
Flag to clear RHS workspace in binary operation.
bool m_do2D_even_for_SingleColumn_on_rhs {false}
Special case for plus/minus: if there is only one bin on the RHS, use the 2D method (appending event lists) so that the single bin is not treated as a scalar.
DataObjects::EventWorkspace_const_sptr m_elhs
Left-hand side EventWorkspace.
DataObjects::EventWorkspace_sptr m_eout
Output EventWorkspace.
DataObjects::EventWorkspace_const_sptr m_erhs
Right-hand side EventWorkspace.
bool m_flipSides {false}
flipSides set to true if the rhs and lhs operands should be flipped - for commutative binary operations, normally.
bool m_keepEventWorkspace {false}
Variable set to true if the operation allows the output to stay as an EventWorkspace.
API::MatrixWorkspace_const_sptr m_lhs
Left-hand side workspace.
size_t m_lhsBlocksize
Cache for LHS workspace's blocksize.
bool m_lhsRagged {false}
Cache for if LHS workspace's is ragged.
bool m_matchXSize {false}
matchXSize set to true if the X sizes of histograms must match.
API::MatrixWorkspace_sptr m_out
Output workspace.
API::MatrixWorkspace_const_sptr m_rhs
Right-hand side workspace.
size_t m_rhsBlocksize
Cache for RHS workspace's blocksize.
bool m_rhsRagged {false}
Cache for if RHS workspace's is ragged.
bool m_useHistogramForRhsEventWorkspace {false}
Are we going to use the histogram representation of the RHS event list when performing the operation? e.g.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Private Member Functions
void do2D (bool mismatchedSpectra)
Called when the two workspaces are the same size.
void doSingleColumn ()
Called when the m_rhs operand is a 2D workspace of single values.
void doSingleSpectrum ()
Called when the m_rhs operand is a single spectrum.
void doSingleValue ()
Called when the rhs operand is a single value.
void propagateBinMasks (const API::MatrixWorkspace_const_sptr &rhs, const API::MatrixWorkspace_sptr &out)
Copies any bin masking from the smaller/rhs input workspace to the output.
Private Attributes
std::unique_ptr< API::Progress > m_progress = nullptr
Progress reporting.
Additional Inherited Members
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
BinaryOperation supports the implementation of a binary operation on two input workspaces.
It inherits from the Algorithm class, and overrides the init() & exec() methods.
Required Properties:
InputWorkspace1 - The name of the workspace forming the left hand operand
InputWorkspace2 - The name of the workspace forming the right hand operand
OutputWorkspace - The name of the workspace in which to store the result
Author
Nick Draper
Date
14/12/2007
Definition at line 42 of file BinaryOperation.h.
Member Typedef Documentation
BinaryOperationTable
using Mantid::Algorithms::BinaryOperation::BinaryOperationTable = std::vector<int64_t>
BinaryOperationTable: a list of ints.
Index into vector: workspace index in the lhs; Value at that index: workspace index of the rhs to apply to the WI in the lhs. -1 if not found.
Definition at line 52 of file BinaryOperation.h.
BinaryOperationTable_sptr
using Mantid::Algorithms::BinaryOperation::BinaryOperationTable_sptr = std::shared_ptr<BinaryOperationTable>
Definition at line 53 of file BinaryOperation.h.
Member Function Documentation
buildBinaryOperationTable()
BinaryOperation::BinaryOperationTable_sptr Mantid::Algorithms::BinaryOperation::buildBinaryOperationTable (const API::MatrixWorkspace_const_sptr & lhs, const API::MatrixWorkspace_const_sptr & rhs) static
Build up an BinaryOperationTable for performing a binary operation e.g.
lhs = (lhs + rhs) where the spectra in rhs are to go into lhs. This function looks to match the detector IDs in rhs to those in the lhs.
Parameters
lhs :: matrix workspace in which the operation is being done.
rhs :: matrix workspace on the right hand side of the operand
Returns
map from detector ID to workspace index for the RHS workspace. NULL if there is not a 1:1 mapping from detector ID to workspace index (e.g more than one detector per pixel).
Definition at line 891 of file BinaryOperation.cpp.
References PARALLEL_FOR_NO_WSP_CHECK, and rhs.
Referenced by do2D(), and Mantid::Algorithms::ApplyFloodWorkspace::exec().
category()
const std::string Mantid::Algorithms::BinaryOperation::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Implements Mantid::API::IAlgorithm.
Reimplemented in Mantid::Algorithms::PoissonErrors.
Definition at line 45 of file BinaryOperation.h.
checkCompatibility()
bool Mantid::Algorithms::BinaryOperation::checkCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs) const protected virtual
Checks the compatibility of the two workspaces.
Return true if the two workspaces are compatible for this operation Virtual: will be overridden as needed.
Parameters
lhs :: left-hand workspace to check
rhs :: right-hand workspace to check
Returns
flag for the compatibility to the two workspaces
Reimplemented in Mantid::Algorithms::Minus, Mantid::Algorithms::Plus, and Mantid::Algorithms::WeightedMean.
Definition at line 307 of file BinaryOperation.cpp.
References checkSizeCompatibility(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, m_lhsBlocksize, m_rhsBlocksize, and rhs.
Referenced by Mantid::Algorithms::Minus::checkCompatibility(), Mantid::Algorithms::Plus::checkCompatibility(), Mantid::Algorithms::WeightedMean::checkCompatibility(), and exec().
checkEventCompatibility()
bool Mantid::Algorithms::BinaryOperation::checkEventCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs) protected virtual
Checks the compatibility of event-based processing of the two workspaces.
Return true if the two workspaces can be treated as event workspaces for the binary operation.
If so, execEvent() will be called. (e.g. Plus algorithm will concatenate event lists)
Parameters
lhs :: left-hand event workspace to check
rhs :: right-hand event workspace to check
Returns
false by default; will be overridden by specific algorithms
Definition at line 344 of file BinaryOperation.cpp.
References rhs, and UNUSED_ARG.
checkRequirements()
void Mantid::Algorithms::BinaryOperation::checkRequirements () protected virtual
Check what operation will be needed in order to apply the operation to these two types of workspaces.
This function must be overridden and checked against all 9 possible combinations.
Must set: m_matchXSize, m_flipSides, m_keepEventWorkspace
Reimplemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, and Mantid::Algorithms::Plus.
Definition at line 863 of file BinaryOperation.cpp.
References m_flipSides, m_keepEventWorkspace, m_matchXSize, and m_useHistogramForRhsEventWorkspace.
Referenced by Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), and exec().
checkSizeCompatibility()
std::string Mantid::Algorithms::BinaryOperation::checkSizeCompatibility (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs) const protected virtual
Checks the overall size compatibility of two workspaces.
Performs a simple check to see if the sizes of two workspaces are compatible for a binary operation In order to be size compatible then the larger workspace must divide be the size of the smaller workspace leaving no remainder.
Parameters
lhs :: the first workspace to compare
rhs :: the second workspace to compare
Return values
"" The two workspaces are size compatible
<reason why not compatible> The two workspaces are NOT size compatible
Reimplemented in Mantid::Algorithms::CommutativeBinaryOperation, Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, Mantid::Algorithms::Plus, Mantid::Algorithms::PoissonErrors, and Mantid::Algorithms::WeightedMean.
Definition at line 361 of file BinaryOperation.cpp.
References m_lhsBlocksize, m_lhsRagged, m_matchXSize, m_rhsBlocksize, m_rhsRagged, Mantid::API::WorkspaceHelpers::matchingBins(), and rhs.
Referenced by checkCompatibility(), Mantid::Algorithms::CommutativeBinaryOperation::checkSizeCompatibility(), Mantid::Algorithms::Minus::checkSizeCompatibility(), and Mantid::Algorithms::Plus::checkSizeCompatibility().
do2D()
void Mantid::Algorithms::BinaryOperation::do2D (bool mismatchedSpectra) private
Called when the two workspaces are the same size.
Loops over the workspaces extracting the appropriate spectra and calling the abstract binary operation function.
Parameters
mismatchedSpectra :: allow the # of spectra to not be the same. Will use the detector IDs to find the corresponding spectrum on RHS
Definition at line 636 of file BinaryOperation.cpp.
References buildBinaryOperationTable(), Mantid::API::Algorithm::clear(), m_ClearRHSWorkspace, m_eout, m_erhs, m_lhs, m_out, m_progress, m_rhs, m_useHistogramForRhsEventWorkspace, Mantid::API::Algorithm::name(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, performBinaryOperation(), performEventBinaryOperation(), propagateBinMasks(), propagateSpectraMask(), Mantid::API::ISpectrum::setSharedX(), and Mantid::Kernel::threadSafe().
Referenced by exec().
doSingleColumn()
void Mantid::Algorithms::BinaryOperation::doSingleColumn () private
Called when the m_rhs operand is a 2D workspace of single values.
Loops over the workspaces calling the abstract binary operation function with a single number as the m_rhs operand.
Definition at line 496 of file BinaryOperation.cpp.
References m_eout, m_lhs, m_out, m_progress, m_rhs, Mantid::API::Algorithm::name(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, performBinaryOperation(), performEventBinaryOperation(), propagateSpectraMask(), and Mantid::Kernel::threadSafe().
Referenced by exec().
doSingleSpectrum()
void Mantid::Algorithms::BinaryOperation::doSingleSpectrum () private
Called when the m_rhs operand is a single spectrum.
Loops over the lhs workspace calling the abstract binary operation function.
Definition at line 549 of file BinaryOperation.cpp.
References m_eout, m_erhs, m_lhs, m_out, m_progress, m_rhs, Mantid::API::Algorithm::name(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, performBinaryOperation(), performEventBinaryOperation(), propagateBinMasks(), rhs, and Mantid::Kernel::threadSafe().
Referenced by exec().
doSingleValue()
void Mantid::Algorithms::BinaryOperation::doSingleValue () private
Called when the rhs operand is a single value.
Loops over the lhs workspace calling the abstract binary operation function with a single number as the rhs operand.
Definition at line 449 of file BinaryOperation.cpp.
References m_eout, m_lhs, m_out, m_progress, m_rhs, Mantid::API::Algorithm::name(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, performBinaryOperation(), performEventBinaryOperation(), and Mantid::Kernel::threadSafe().
Referenced by exec().
exec()
void Mantid::Algorithms::BinaryOperation::exec () override protected virtual
Executes the algorithm.
Will call execEvent() if appropriate.
Exceptions
runtime_error Thrown if algorithm cannot execute
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::Algorithms::Divide.
Definition at line 131 of file BinaryOperation.cpp.
References checkCompatibility(), checkRequirements(), do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), handleSpecialDivideMinus(), inputPropName1(), inputPropName2(), m_AllowDifferentNumberSpectra, m_ClearRHSWorkspace, m_do2D_even_for_SingleColumn_on_rhs, m_elhs, m_eout, m_erhs, m_flipSides, m_keepEventWorkspace, m_lhs, m_lhsBlocksize, m_lhsRagged, m_out, m_progress, m_rhs, m_rhsBlocksize, m_rhsRagged, Mantid::API::Algorithm::name(), operateOnRun(), outputPropName(), setOutputUnits(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by Mantid::Algorithms::Divide::exec().
execEvent()
void Mantid::Algorithms::BinaryOperation::execEvent (DataObjects::EventWorkspace_const_sptr lhs, DataObjects::EventWorkspace_const_sptr rhs) protected virtual
Execution method for event workspaces, to be overridden as needed.
Execute a binary operation on events.
Should be overridden.
Parameters
lhs :: left-hand event workspace
rhs :: right-hand event workspace
Definition at line 292 of file BinaryOperation.cpp.
References rhs, and UNUSED_ARG.
getOperandType()
OperandType Mantid::Algorithms::BinaryOperation::getOperandType (const API::MatrixWorkspace_const_sptr & ws) protected
Get the type of operand from a workspace.
Parameters
ws :: workspace to check
Returns
OperandType describing what type of workspace it will be operated as.
Definition at line 840 of file BinaryOperation.cpp.
References Mantid::Algorithms::eEventList, Mantid::Algorithms::eHistogram, and Mantid::Algorithms::eNumber.
handleSpecialDivideMinus()
bool Mantid::Algorithms::BinaryOperation::handleSpecialDivideMinus () protected
Special handling for 1-WS and 1/WS.
Returns
true if the operation was handled; exec() should then return
Definition at line 68 of file BinaryOperation.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getProperty(), inputPropName1(), inputPropName2(), m_lhs, m_rhs, Mantid::API::Algorithm::name(), outputPropName(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by exec().
init()
void Mantid::Algorithms::BinaryOperation::init () override protected virtual
Initialisation method.
Defines input and output workspaces
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::Algorithms::Divide.
Definition at line 38 of file BinaryOperation.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, inputPropName1(), inputPropName2(), Mantid::Kernel::Direction::Output, and outputPropName().
Referenced by Mantid::Algorithms::Divide::init().
inputPropName1()
virtual std::string Mantid::Algorithms::BinaryOperation::inputPropName1 () const inline protected virtual
The name of the first input workspace property.
Reimplemented in Mantid::Algorithms::PoissonErrors, and Mantid::Algorithms::WeightedMean.
Definition at line 69 of file BinaryOperation.h.
Referenced by exec(), handleSpecialDivideMinus(), and init().
inputPropName2()
virtual std::string Mantid::Algorithms::BinaryOperation::inputPropName2 () const inline protected virtual
The name of the second input workspace property.
Reimplemented in Mantid::Algorithms::PoissonErrors, and Mantid::Algorithms::WeightedMean.
Definition at line 71 of file BinaryOperation.h.
Referenced by exec(), handleSpecialDivideMinus(), and init().
operateOnRun()
virtual void Mantid::Algorithms::BinaryOperation::operateOnRun (const API::Run & lhs, const API::Run & rhs, API::Run & ans) const inline protected virtual
Only overridden by operations that affect the properties of the run (e.g.
Plus where the proton currents (charges) are added). Otherwise it does nothing.
Parameters
lhs :: One of the workspaces to operate on
rhs :: The other workspace
ans :: The output workspace
Reimplemented in Mantid::Algorithms::Plus.
Definition at line 156 of file BinaryOperation.h.
References rhs.
Referenced by exec().
outputPropName()
virtual std::string Mantid::Algorithms::BinaryOperation::outputPropName () const inline protected virtual
The name of the output workspace property.
Reimplemented in Mantid::Algorithms::PoissonErrors.
Definition at line 73 of file BinaryOperation.h.
Referenced by exec(), handleSpecialDivideMinus(), and init().
performBinaryOperation() [1/2]
virtual void Mantid::Algorithms::BinaryOperation::performBinaryOperation (const HistogramData::Histogram & lhs, const double rhsY, const double rhsE, HistogramData::HistogramY & YOut, HistogramData::HistogramE & EOut) protected pure virtual
Carries out the binary operation when the right hand operand is a single number.
Parameters
lhs :: Lhs histogram data
rhsY :: The rhs data value
rhsE :: The lhs data value
YOut :: Data values resulting from the operation
EOut :: Error values resulting from the operation
Implemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, Mantid::Algorithms::Plus, Mantid::Algorithms::PoissonErrors, and Mantid::Algorithms::WeightedMean.
performBinaryOperation() [2/2]
virtual void Mantid::Algorithms::BinaryOperation::performBinaryOperation (const HistogramData::Histogram & lhs, const HistogramData::Histogram & rhs, HistogramData::HistogramY & YOut, HistogramData::HistogramE & EOut) protected pure virtual
Carries out the binary operation on a single spectrum, with another spectrum as the right-hand operand.
Parameters
lhs :: Lhs histogram data
rhs :: Rhs histogram data
YOut :: Data values resulting from the operation
EOut :: Drror values resulting from the operation
Implemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, Mantid::Algorithms::Plus, Mantid::Algorithms::PoissonErrors, and Mantid::Algorithms::WeightedMean.
Referenced by do2D(), doSingleColumn(), doSingleSpectrum(), and doSingleValue().
performEventBinaryOperation() [1/3]
void Mantid::Algorithms::BinaryOperation::performEventBinaryOperation (DataObjects::EventList & lhs, const DataObjects::EventList & rhs) protected virtual
Carries out the binary operation IN-PLACE on a single EventList, with another EventList as the right-hand operand.
The event lists simply get appended.
Parameters
lhs :: Reference to the EventList that will be modified in place.
rhs :: Const reference to the EventList on the right hand side.
Reimplemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, and Mantid::Algorithms::Plus.
Definition at line 796 of file BinaryOperation.cpp.
References rhs, and UNUSED_ARG.
Referenced by do2D(), doSingleColumn(), doSingleSpectrum(), and doSingleValue().
performEventBinaryOperation() [2/3]
void Mantid::Algorithms::BinaryOperation::performEventBinaryOperation (DataObjects::EventList & lhs, const double & rhsY, const double & rhsE) protected virtual
Carries out the binary operation IN-PLACE on a single EventList, with a single (double) value as the right-hand operand.
Parameters
lhs :: Reference to the EventList that will be modified in place.
rhsY :: The rhs data value
rhsE :: The rhs error value
Reimplemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, and Mantid::Algorithms::Plus.
Definition at line 828 of file BinaryOperation.cpp.
References UNUSED_ARG.
performEventBinaryOperation() [3/3]
void Mantid::Algorithms::BinaryOperation::performEventBinaryOperation (DataObjects::EventList & lhs, const MantidVec & rhsX, const MantidVec & rhsY, const MantidVec & rhsE) protected virtual
Carries out the binary operation IN-PLACE on a single EventList, with another (histogrammed) spectrum as the right-hand operand.
Parameters
lhs :: Reference to the EventList that will be modified in place.
rhsX :: Rhs X bin boundaries
rhsY :: Rhs data values
rhsE :: Rhs error values
Reimplemented in Mantid::Algorithms::Divide, Mantid::Algorithms::Minus, Mantid::Algorithms::Multiply, and Mantid::Algorithms::Plus.
Definition at line 811 of file BinaryOperation.cpp.
References UNUSED_ARG.
propagateBinMasks()
void Mantid::Algorithms::BinaryOperation::propagateBinMasks (const API::MatrixWorkspace_const_sptr & rhs, const API::MatrixWorkspace_sptr & out) private
Copies any bin masking from the smaller/rhs input workspace to the output.
Masks on the other input workspace are copied automatically by the workspace factory.
Parameters
rhs :: The workspace which is the right hand operand
out :: The result workspace
Definition at line 768 of file BinaryOperation.cpp.
References rhs.
Referenced by do2D(), and doSingleSpectrum().
propagateSpectraMask()
bool Mantid::Algorithms::BinaryOperation::propagateSpectraMask (const API::SpectrumInfo & lhsSpectrumInfo, const API::SpectrumInfo & rhsSpectrumInfo, const int64_t index, API::MatrixWorkspace & out, API::SpectrumInfo & outSpectrumInfo) protected virtual
Checks if the spectra at the given index of either input workspace is masked.
If so then the output spectra has zeroed data and is also masked.
Parameters
lhsSpectrumInfo :: The LHS spectrum info object
rhsSpectrumInfo :: The RHS spectrum info object
index :: The workspace index to check
out :: A pointer to the output workspace
outSpectrumInfo :: The spectrum info object of out
Returns
True if further processing is not required on the spectra, false if the binary operation should be performed.
Definition at line 431 of file BinaryOperation.cpp.
References Mantid::API::ISpectrum::clearData(), Mantid::API::MatrixWorkspace::getSpectrum(), Mantid::API::SpectrumInfo::hasDetectors(), index, Mantid::API::SpectrumInfo::isMasked(), PARALLEL_CRITICAL, and Mantid::API::SpectrumInfo::setMasked().
Referenced by do2D(), and doSingleColumn().
setOutputUnits()
virtual void Mantid::Algorithms::BinaryOperation::setOutputUnits (const API::MatrixWorkspace_const_sptr lhs, const API::MatrixWorkspace_const_sptr rhs, API::MatrixWorkspace_sptr out) inline protected virtual
Should be overridden by operations that need to manipulate the units of the output workspace.
Does nothing by default.
Parameters
lhs :: The first input workspace
rhs :: The second input workspace
out :: The output workspace
Reimplemented in Mantid::Algorithms::Divide, and Mantid::Algorithms::Multiply.
Definition at line 141 of file BinaryOperation.h.
References rhs.
Referenced by exec().
Member Data Documentation
m_AllowDifferentNumberSpectra
bool Mantid::Algorithms::BinaryOperation::m_AllowDifferentNumberSpectra {false} protected
The property value.
Definition at line 183 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Minus::checkCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), and exec().
m_ClearRHSWorkspace
bool Mantid::Algorithms::BinaryOperation::m_ClearRHSWorkspace {false} protected
Flag to clear RHS workspace in binary operation.
Definition at line 185 of file BinaryOperation.h.
Referenced by do2D(), and exec().
m_do2D_even_for_SingleColumn_on_rhs
bool Mantid::Algorithms::BinaryOperation::m_do2D_even_for_SingleColumn_on_rhs {false} protected
Special case for plus/minus: if there is only one bin on the RHS, use the 2D method (appending event lists) so that the single bin is not treated as a scalar.
Definition at line 220 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), and exec().
m_elhs
DataObjects::EventWorkspace_const_sptr Mantid::Algorithms::BinaryOperation::m_elhs protected
Left-hand side EventWorkspace.
Definition at line 170 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Divide::checkRequirements(), Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), Mantid::Algorithms::Minus::checkSizeCompatibility(), Mantid::Algorithms::Plus::checkSizeCompatibility(), and exec().
m_eout
DataObjects::EventWorkspace_sptr Mantid::Algorithms::BinaryOperation::m_eout protected
Output EventWorkspace.
Definition at line 180 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Plus::checkRequirements(), do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), and exec().
m_erhs
DataObjects::EventWorkspace_const_sptr Mantid::Algorithms::BinaryOperation::m_erhs protected
Right-hand side EventWorkspace.
Definition at line 175 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), Mantid::Algorithms::Minus::checkSizeCompatibility(), Mantid::Algorithms::Plus::checkSizeCompatibility(), do2D(), doSingleSpectrum(), and exec().
m_flipSides
bool Mantid::Algorithms::BinaryOperation::m_flipSides {false} protected
flipSides set to true if the rhs and lhs operands should be flipped - for commutative binary operations, normally.
Definition at line 202 of file BinaryOperation.h.
Referenced by checkRequirements(), Mantid::Algorithms::Divide::checkRequirements(), Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), and exec().
m_keepEventWorkspace
bool Mantid::Algorithms::BinaryOperation::m_keepEventWorkspace {false} protected
Variable set to true if the operation allows the output to stay as an EventWorkspace.
If this returns false, any EventWorkspace will be converted to Workspace2D. This is ignored if the lhs operand is not an EventWorkspace.
Definition at line 208 of file BinaryOperation.h.
Referenced by checkRequirements(), Mantid::Algorithms::Divide::checkRequirements(), Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), and exec().
m_lhs
API::MatrixWorkspace_const_sptr Mantid::Algorithms::BinaryOperation::m_lhs protected
Left-hand side workspace.
Definition at line 168 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), exec(), and handleSpecialDivideMinus().
m_lhsBlocksize
size_t Mantid::Algorithms::BinaryOperation::m_lhsBlocksize protected
Cache for LHS workspace's blocksize.
Definition at line 187 of file BinaryOperation.h.
Referenced by checkCompatibility(), Mantid::Algorithms::Multiply::checkRequirements(), checkSizeCompatibility(), and exec().
m_lhsRagged
bool Mantid::Algorithms::BinaryOperation::m_lhsRagged {false} protected
Cache for if LHS workspace's is ragged.
Definition at line 192 of file BinaryOperation.h.
Referenced by checkSizeCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), and exec().
m_matchXSize
bool Mantid::Algorithms::BinaryOperation::m_matchXSize {false} protected
matchXSize set to true if the X sizes of histograms must match.
Definition at line 198 of file BinaryOperation.h.
Referenced by checkRequirements(), Mantid::Algorithms::Divide::checkRequirements(), Mantid::Algorithms::Minus::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), checkSizeCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), and Mantid::Algorithms::Multiply::checkSizeCompatibility().
m_out
API::MatrixWorkspace_sptr Mantid::Algorithms::BinaryOperation::m_out protected
Output workspace.
Definition at line 178 of file BinaryOperation.h.
Referenced by do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), and exec().
m_progress
std::unique_ptr<API::Progress> Mantid::Algorithms::BinaryOperation::m_progress = nullptr private
Progress reporting.
Definition at line 230 of file BinaryOperation.h.
Referenced by do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), and exec().
m_rhs
API::MatrixWorkspace_const_sptr Mantid::Algorithms::BinaryOperation::m_rhs protected
Right-hand side workspace.
Definition at line 173 of file BinaryOperation.h.
Referenced by Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), do2D(), doSingleColumn(), doSingleSpectrum(), doSingleValue(), exec(), and handleSpecialDivideMinus().
m_rhsBlocksize
size_t Mantid::Algorithms::BinaryOperation::m_rhsBlocksize protected
Cache for RHS workspace's blocksize.
Definition at line 189 of file BinaryOperation.h.
Referenced by checkCompatibility(), Mantid::Algorithms::Multiply::checkRequirements(), checkSizeCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), exec(), and Mantid::Algorithms::Divide::setOutputUnits().
m_rhsRagged
bool Mantid::Algorithms::BinaryOperation::m_rhsRagged {false} protected
Cache for if RHS workspace's is ragged.
Definition at line 194 of file BinaryOperation.h.
Referenced by checkSizeCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), and exec().
m_useHistogramForRhsEventWorkspace
bool Mantid::Algorithms::BinaryOperation::m_useHistogramForRhsEventWorkspace {false} protected
Are we going to use the histogram representation of the RHS event list when performing the operation? e.g.
divide and multiply? Plus and Minus will set this to false (default).
Definition at line 214 of file BinaryOperation.h.
Referenced by checkRequirements(), Mantid::Algorithms::Divide::checkRequirements(), Mantid::Algorithms::Multiply::checkRequirements(), Mantid::Algorithms::Plus::checkRequirements(), and do2D().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/BinaryOperation.h
Framework/Algorithms/src/BinaryOperation.cpp