Mantid: MantidQt::MantidWidgets::AlgorithmProgressPresenterBase Class Reference
MantidQt::MantidWidgets::AlgorithmProgressPresenterBase Class Reference abstract
#include <AlgorithmProgressPresenterBase.h>
Signals
void algorithmEndedSignal (Mantid::API::AlgorithmID)
void algorithmStartedSignal (Mantid::API::AlgorithmID)
void updateProgressBarSignal (Mantid::API::AlgorithmID, double progress, QString message, double estimatedTime, int progressPrecision)
Public Member Functions
void algorithmEnded (Mantid::API::AlgorithmID)
Signals to the presenters that an algorithm has ended.
virtual void algorithmEndedSlot (Mantid::API::AlgorithmID)=0
AlgorithmProgressPresenterBase (QObject *parent)
void algorithmStarted (Mantid::API::AlgorithmID)
Signals to the presenters that an algorithm has started.
virtual void algorithmStartedSlot (Mantid::API::AlgorithmID)=0
void setProgressBar (QProgressBar *, const double, const QString &, const double, const int)
Sets the parameter progress bar to show the progress and message.
void updateProgressBar (Mantid::API::AlgorithmID, double, const std::string &, const double estimatedTime, const int progressPrecision)
Signals to the presenters that there has been progress in one of the algorithms.
virtual void updateProgressBarSlot (Mantid::API::AlgorithmID, const double, const QString, const double, const int)=0
Detailed Description
Definition at line 33 of file AlgorithmProgressPresenterBase.h.
Constructor & Destructor Documentation
AlgorithmProgressPresenterBase()
MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::AlgorithmProgressPresenterBase (QObject * parent)
Definition at line 12 of file AlgorithmProgressPresenterBase.cpp.
References algorithmEndedSignal(), algorithmEndedSlot(), algorithmStartedSignal(), algorithmStartedSlot(), updateProgressBarSignal(), and updateProgressBarSlot().
Member Function Documentation
algorithmEnded()
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmEnded (Mantid::API::AlgorithmID alg)
Signals to the presenters that an algorithm has ended.
This function is called whenever an algorithm ended.
It emits a signal triggering the slot inside the GUI thread. It is safe to call this function from any thread
Parameters
alg The ID of the algorithm that has started executing
Definition at line 35 of file AlgorithmProgressPresenterBase.cpp.
References algorithmEndedSignal().
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::removeFrom().
algorithmEndedSignal
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmEndedSignal (Mantid::API::AlgorithmID) signal
Referenced by algorithmEnded(), and AlgorithmProgressPresenterBase().
algorithmEndedSlot()
virtual void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmEndedSlot (Mantid::API::AlgorithmID) pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressDialogPresenter, and MantidQt::MantidWidgets::AlgorithmProgressPresenter.
Referenced by AlgorithmProgressPresenterBase().
algorithmStarted()
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmStarted (Mantid::API::AlgorithmID alg)
Signals to the presenters that an algorithm has started.
This function is called whenever an algorithm started.
It emits an algorithm started signal, which is allows the GUIs to be updated, by triggering the slot in the GUI thread. It is safe to call this function from any thread
Parameters
alg The ID of the algorithm that has started executing
Definition at line 28 of file AlgorithmProgressPresenterBase.cpp.
References algorithmStartedSignal().
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::startHandle().
algorithmStartedSignal
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmStartedSignal (Mantid::API::AlgorithmID) signal
Referenced by AlgorithmProgressPresenterBase(), and algorithmStarted().
algorithmStartedSlot()
virtual void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::algorithmStartedSlot (Mantid::API::AlgorithmID) pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressDialogPresenter, and MantidQt::MantidWidgets::AlgorithmProgressPresenter.
Referenced by AlgorithmProgressPresenterBase().
setProgressBar()
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::setProgressBar (QProgressBar * progressBar, const double progress, const QString & message, const double estimatedTime, const int progressPrecision)
Sets the parameter progress bar to show the progress and message.
Updates the parameter progress bar to display the progress.
If there is a message, the progress bar format is changed to display it as well.
Parameters
progressBar The progress bar that will be updated
progress The progress that an algorithm has reported
message The message that an algorithm has sent. The object will already have been copied into the GUI thread, so it is safe to receive it by
estimatedTime :: estimated time to completion in seconds
progressPrecision :: number of digits after the decimal
Definition at line 44 of file AlgorithmProgressPresenterBase.cpp.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressDialogPresenter::updateProgressBarSlot().
updateProgressBar()
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::updateProgressBar (Mantid::API::AlgorithmID alg, double progress, const std::string & msg, const double estimatedTime, const int progressPrecision)
Signals to the presenters that there has been progress in one of the algorithms.
This function is called whenever an algorithm reports progress.
It emits a signal triggering the slot inside the GUI thread. It is safe to call this function from any thread
Parameters
alg The ID of the algorithm that has started executing
progress The progress that the algorithm has reported
msg The message that the algorithm has sent
estimatedTime :: estimated time to completion in seconds
progressPrecision :: number of digits after the decimal
Definition at line 82 of file AlgorithmProgressPresenterBase.cpp.
References updateProgressBarSignal().
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::progressHandle().
updateProgressBarSignal
void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::updateProgressBarSignal (Mantid::API::AlgorithmID , double progress, QString message, double estimatedTime, int progressPrecision) signal
Referenced by AlgorithmProgressPresenterBase(), and updateProgressBar().
updateProgressBarSlot()
virtual void MantidQt::MantidWidgets::AlgorithmProgressPresenterBase::updateProgressBarSlot (Mantid::API::AlgorithmID , const double , const QString, const double , const int) pure virtual
Implemented in MantidQt::MantidWidgets::AlgorithmProgressDialogPresenter, and MantidQt::MantidWidgets::AlgorithmProgressPresenter.
Referenced by AlgorithmProgressPresenterBase().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressPresenterBase.h
qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressPresenterBase.cpp