Mantid: MantidQt::API::FileDialogHandler Namespace Reference
MantidQt::API::FileDialogHandler Namespace Reference
Contains modifications to Qt functions where problems have been found on certain operating systems.
Functions
DLLExport QString addExtension (const QString &filename, const QString &selectedFilter)
For file dialogs.
DLLExport QString formatExtension (const std::string &extension)
Format extension into expected form (*.ext)
DLLExport QString getCaption (const std::string &dialogName, const Mantid::Kernel::Property *prop)
DLLExport QString getFilter (const Mantid::Kernel::Property *baseProp)
DLLExport QString getFilter (const std::vector< std::string > &exts)
For file dialogs.
DLLExport QString getSaveFileName (QWidget *parent, const Mantid::Kernel::Property *baseProp, const QFileDialog::Options &options)
Contains modifications to Qt functions where problems have been found on certain operating systems.
Detailed Description
Contains modifications to Qt functions where problems have been found on certain operating systems.
Function Documentation
addExtension()
QString MantidQt::API::FileDialogHandler::addExtension (const QString & filename, const QString & selectedFilter)
For file dialogs.
This will add the selected extension if an extension doesn't already exist.
Definition at line 54 of file FileDialogHandler.cpp.
Referenced by getSaveFileName().
formatExtension()
QString MantidQt::API::FileDialogHandler::formatExtension (const std::string & extension)
Format extension into expected form (*.ext)
Parameters
extension :: extension to be formatted
Returns
a QString of the expected form
Definition at line 127 of file FileDialogHandler.cpp.
Referenced by getFilter().
getCaption()
QString MantidQt::API::FileDialogHandler::getCaption (const std::string & dialogName, const Mantid::Kernel::Property * prop)
Definition at line 146 of file FileDialogHandler.cpp.
References name, and Mantid::Kernel::Property::name().
Referenced by getSaveFileName(), and MantidQt::API::FilePropertyWidget::openFileDialog().
getFilter() [1/2]
QString MantidQt::API::FileDialogHandler::getFilter (const Mantid::Kernel::Property * baseProp)
Definition at line 71 of file FileDialogHandler.cpp.
References getFilter().
Referenced by getFilter(), getSaveFileName(), MantidQt::API::FilePropertyWidget::openFileDialog(), and MantidQt::API::FilePropertyWidget::openMultipleFileDialog().
getFilter() [2/2]
QString MantidQt::API::FileDialogHandler::getFilter (const std::vector< std::string > & exts)
For file dialogs.
Have each filter on a separate line with Data Files as the first and All Files as the last
Parameters
exts :: vector of extensions
Returns
a string that filters files by extenstions
Definition at line 96 of file FileDialogHandler.cpp.
References formatExtension().
getSaveFileName()
QString MantidQt::API::FileDialogHandler::getSaveFileName (QWidget * parent = nullptr, const Mantid::Kernel::Property * baseProp = nullptr, const QFileDialog::Options & options = QFileDialog::Options())
Contains modifications to Qt functions where problems have been found on certain operating systems.
Parameters
parent :: the dialog will be shown centered over this parent widget
baseProp :: The property that the dialog parameters will be extracted from.
options :: The options argument holds various options about how to run the dialog
Definition at line 40 of file FileDialogHandler.cpp.
References addExtension(), getCaption(), and getFilter().
Referenced by MantidQt::API::FilePropertyWidget::openFileDialog().