Mantid: MantidQt::MantidWidgets::ProgressableView Class Reference
MantidQt::MantidWidgets::ProgressableView Class Reference abstract
ProgressableView : Abstract view useful for indicating progress.
#include <ProgressableView.h>
Public Types
enum class Style { PERCENTAGE , ENDLESS }
The style of the progress bar: either a standard percentage progress bar or an endless busy indicator.
Public Member Functions
virtual void clearProgress ()=0
bool isPercentageIndicator () const
ProgressableView ()
void setAsEndlessIndicator ()
void setAsPercentageIndicator ()
virtual void setProgress (int progress)=0
virtual void setProgressRange (int min, int max)
virtual ~ProgressableView ()=default
Protected Attributes
int m_max
int m_min
Style m_style
Detailed Description
ProgressableView : Abstract view useful for indicating progress.
Definition at line 16 of file ProgressableView.h.
Member Enumeration Documentation
Style
enum class MantidQt::MantidWidgets::ProgressableView::Style strong
The style of the progress bar: either a standard percentage progress bar or an endless busy indicator.
Enumerator
PERCENTAGE
ENDLESS
Definition at line 20 of file ProgressableView.h.
Constructor & Destructor Documentation
ProgressableView()
MantidQt::MantidWidgets::ProgressableView::ProgressableView () inline
Definition at line 22 of file ProgressableView.h.
~ProgressableView()
virtual MantidQt::MantidWidgets::ProgressableView::~ProgressableView () virtual default
Member Function Documentation
clearProgress()
virtual void MantidQt::MantidWidgets::ProgressableView::clearProgress () pure virtual
Referenced by ProgressPresenter::clear(), and ProgressPresenter::ProgressPresenter().
isPercentageIndicator()
bool MantidQt::MantidWidgets::ProgressableView::isPercentageIndicator () const
Definition at line 11 of file ProgressableView.cpp.
References m_style, and PERCENTAGE.
Referenced by ProgressPresenter::doReport().
setAsEndlessIndicator()
void MantidQt::MantidWidgets::ProgressableView::setAsEndlessIndicator ()
Definition at line 27 of file ProgressableView.cpp.
References ENDLESS, m_style, and setProgressRange().
Referenced by ProgressPresenter::setAsEndlessIndicator().
setAsPercentageIndicator()
void MantidQt::MantidWidgets::ProgressableView::setAsPercentageIndicator ()
Definition at line 22 of file ProgressableView.cpp.
References m_max, m_min, m_style, PERCENTAGE, and setProgressRange().
Referenced by ProgressPresenter::setAsPercentageIndicator().
setProgress()
virtual void MantidQt::MantidWidgets::ProgressableView::setProgress (int progress) pure virtual
Referenced by ProgressPresenter::doReport().
setProgressRange()
void MantidQt::MantidWidgets::ProgressableView::setProgressRange (int min, int max) virtual
Definition at line 13 of file ProgressableView.cpp.
References m_max, and m_min.
Referenced by ProgressPresenter::ProgressPresenter(), setAsEndlessIndicator(), and setAsPercentageIndicator().
Member Data Documentation
m_max
int MantidQt::MantidWidgets::ProgressableView::m_max protected
Definition at line 36 of file ProgressableView.h.
Referenced by setAsPercentageIndicator(), and setProgressRange().
m_min
int MantidQt::MantidWidgets::ProgressableView::m_min protected
Definition at line 35 of file ProgressableView.h.
Referenced by setAsPercentageIndicator(), and setProgressRange().
m_style
Style MantidQt::MantidWidgets::ProgressableView::m_style protected
Definition at line 34 of file ProgressableView.h.
Referenced by isPercentageIndicator(), setAsEndlessIndicator(), and setAsPercentageIndicator().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ProgressableView.h
qt/widgets/common/src/ProgressableView.cpp