Mantid: Mantid::DataHandling::SampleEnvironmentFactory Class Reference
Mantid::DataHandling::SampleEnvironmentFactory Class Reference
Create a single instance of a SampleEnvironment.
#include <SampleEnvironmentFactory.h>
Public Member Functions
size_t cacheSize () const
void clearCache ()
Clear the cache of SampleEnvironmentSpec objects.
Geometry::SampleEnvironment_uptr create (const std::string &facility, const std::string &instrument, const std::string &specName, const std::string &canName)
Create a new SampleEnvironment instance from the given specification and can.
SampleEnvironmentSpec_uptr parseSpec (const std::string &filename, const std::string &filepath) const
Calls SampleEnvironmentSpecFileFinder::parseSpec.
SampleEnvironmentFactory ()=default
SampleEnvironmentFactory (ISampleEnvironmentSpecFinder_uptr specFinder)
Constructor accepting a pointer to a finder object.
Private Attributes
ISampleEnvironmentSpecFinder_uptr m_finder
Detailed Description
Create a single instance of a SampleEnvironment.
It requires the name of a sample environment specification and a can name.
The specifications are cached in a static lookup. The class is implemented using the monostate pattern
Definition at line 36 of file SampleEnvironmentFactory.h.
Constructor & Destructor Documentation
SampleEnvironmentFactory() [1/2]
Mantid::DataHandling::SampleEnvironmentFactory::SampleEnvironmentFactory () default
References Mantid::DataObjects::create().
SampleEnvironmentFactory() [2/2]
Mantid::DataHandling::SampleEnvironmentFactory::SampleEnvironmentFactory (ISampleEnvironmentSpecFinder_uptr specFinder)
Constructor accepting a pointer to a finder object.
Parameters
specFinder A reference to an object used to retrieve find a given specification.
Definition at line 58 of file SampleEnvironmentFactory.cpp.
Member Function Documentation
cacheSize()
size_t Mantid::DataHandling::SampleEnvironmentFactory::cacheSize () const
Returns
the number of cache entries
Definition at line 93 of file SampleEnvironmentFactory.cpp.
clearCache()
void Mantid::DataHandling::SampleEnvironmentFactory::clearCache ()
Clear the cache of SampleEnvironmentSpec objects.
Definition at line 98 of file SampleEnvironmentFactory.cpp.
create()
Geometry::SampleEnvironment_uptr Mantid::DataHandling::SampleEnvironmentFactory::create (const std::string & facility, const std::string & instrument, const std::string & specName, const std::string & canName)
Create a new SampleEnvironment instance from the given specification and can.
SampleEnvironmentSpec
Parameters
facility Name of facility
instrument Full name of the instrument
specName The name of a specification
canName The name of a can within the spec
Returns
A new instance of the given environment
Definition at line 70 of file SampleEnvironmentFactory.cpp.
References Mantid::DataHandling::SampleEnvironmentSpec::buildEnvironment(), and m_finder.
Referenced by Mantid::DataHandling::SetSample::setSampleEnvironmentFromFile().
parseSpec()
SampleEnvironmentSpec_uptr Mantid::DataHandling::SampleEnvironmentFactory::parseSpec (const std::string & filename, const std::string & filepath) const
Calls SampleEnvironmentSpecFileFinder::parseSpec.
Parameters
filename The name of the specification
filepath Assumed to be an absolute path to an existing specification
Returns
A parse specification
Definition at line 106 of file SampleEnvironmentFactory.cpp.
References m_finder.
Referenced by Mantid::DataHandling::SetSample::setSampleEnvironmentFromFile().
Member Data Documentation
m_finder
ISampleEnvironmentSpecFinder_uptr Mantid::DataHandling::SampleEnvironmentFactory::m_finder private
Definition at line 49 of file SampleEnvironmentFactory.h.
Referenced by create(), and parseSpec().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/SampleEnvironmentFactory.h
Framework/DataHandling/src/SampleEnvironmentFactory.cpp