Mantid: Mantid::API::CommonBinsValidator Class Reference
Mantid::API::CommonBinsValidator Class Reference
A validator which provides a TENTATIVE check that a workspace contains common bins in each spectrum.
#include <CommonBinsValidator.h>
Public Member Functions
Kernel::IValidator_sptr clone () const override
Clone the current state.
std::string getType () const
Gets the type of the validator.
Private Member Functions
std::string checkValidity (const MatrixWorkspace_sptr &value) const override
Check for validity.
Detailed Description
A validator which provides a TENTATIVE check that a workspace contains common bins in each spectrum.
For efficiency reasons, it only checks that the first and last spectra have common bins, so it is important to carry out a full check within the algorithm itself.
Definition at line 21 of file CommonBinsValidator.h.
Member Function Documentation
checkValidity()
std::string Mantid::API::CommonBinsValidator::checkValidity (const MatrixWorkspace_sptr & value) const override private
Check for validity.
Checks that the bin boundaries of each histogram in the workspace are the same.
Parameters
value :: The workspace to test
Returns
A message for users saying that bins are different, otherwise ""
Definition at line 20 of file CommonBinsValidator.cpp.
References value.
clone()
Kernel::IValidator_sptr Mantid::API::CommonBinsValidator::clone () const override
Clone the current state.
Definition at line 13 of file CommonBinsValidator.cpp.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMDHKL::init(), Mantid::MDAlgorithms::MDNorm::init(), and Mantid::MDAlgorithms::MDNormSCD::init().
getType()
std::string Mantid::API::CommonBinsValidator::getType () const inline
Gets the type of the validator.
Definition at line 24 of file CommonBinsValidator.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/CommonBinsValidator.h
Framework/API/src/CommonBinsValidator.cpp