Mantid: MantidQt::MantidWidgets::GlobalTie Struct Reference
MantidQt::MantidWidgets::GlobalTie Struct Reference
This struct stores the data associated with a global tie.
#include <FittingGlobals.h>
Public Member Functions
std::string asString () const
GlobalTie (std::string parameter, std::string tie)
std::string toCompositeParameter (std ::string const &fullParameter) const
std::string toNonCompositeParameter (std ::string const &fullParameter) const
Public Attributes
std::string m_parameter
std::string m_tie
Detailed Description
This struct stores the data associated with a global tie.
A global tie is where a parameter of a specific domain is tied to the value of a parameter in a different domain.
Definition at line 37 of file FittingGlobals.h.
Constructor & Destructor Documentation
GlobalTie()
MantidQt::MantidWidgets::GlobalTie::GlobalTie (std::string parameter, std::string tie)
Definition at line 15 of file FittingGlobals.cpp.
Member Function Documentation
asString()
std::string MantidQt::MantidWidgets::GlobalTie::asString () const
Definition at line 37 of file FittingGlobals.cpp.
References m_parameter, and m_tie.
toCompositeParameter()
std::string MantidQt::MantidWidgets::GlobalTie::toCompositeParameter (std ::string const & fullParameter) const
Definition at line 18 of file FittingGlobals.cpp.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustParameterInGlobalTieIfInvalidated(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustTieInGlobalTieIfInvalidated().
toNonCompositeParameter()
std::string MantidQt::MantidWidgets::GlobalTie::toNonCompositeParameter (std ::string const & fullParameter) const
Definition at line 26 of file FittingGlobals.cpp.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustParameterInGlobalTieIfInvalidated(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustTieInGlobalTieIfInvalidated().
Member Data Documentation
m_parameter
std::string MantidQt::MantidWidgets::GlobalTie::m_parameter
Definition at line 46 of file FittingGlobals.h.
Referenced by asString(), MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustParameterInGlobalTieIfInvalidated(), MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustTieInGlobalTieIfInvalidated(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValueInGlobalTie().
m_tie
std::string MantidQt::MantidWidgets::GlobalTie::m_tie
Definition at line 47 of file FittingGlobals.h.
Referenced by asString(), MantidQt::MantidWidgets::FitScriptGeneratorModel::tryToAdjustTieInGlobalTieIfInvalidated(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValueInGlobalTie().
The documentation for this struct was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FittingGlobals.h
qt/widgets/common/src/FittingGlobals.cpp