Mantid: Mantid::API::AlgorithmObserver Class Reference
Mantid::API::AlgorithmObserver Class Reference
Observes Algorithm notifications: start,progress,finish,error.
#include <AlgorithmObserver.h>
Public Member Functions
AlgorithmObserver ()
Default constructor.
AlgorithmObserver (const IAlgorithm_const_sptr &alg)
Constructs AlgorithmObserver and connects all its handlers to algorithm alg.
virtual void errorHandle (const IAlgorithm *alg, const std::string &what)
virtual void finishHandle (const IAlgorithm *alg)
void observeAll (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe all its notifications.
void observeError (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its error notification.
void observeFinish (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its finish notification.
void observeProgress (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its progress notification.
void observeStart (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its start notification.
void observeStarting ()
Connect to AlgorithmManager and observe its starting notifications.
virtual void progressHandle (const IAlgorithm *alg, double p, const std::string &msg, const double estimatedTime, const int progressPrecision)
virtual void startHandle (const IAlgorithm *alg)
virtual void startingHandle (IAlgorithm_sptr alg)
void stopObserving (const IAlgorithm_const_sptr &alg)
Disconnect from algorithm alg.
void stopObserving (const Mantid::API::IAlgorithm *alg)
void stopObservingManager ()
Disconnect from the algorithm manager.
virtual ~AlgorithmObserver ()
Virtual destructor.
Private Member Functions
void _errorHandle (const Poco::AutoPtr< Algorithm::ErrorNotification > &pNf)
Poco notification handler for Algorithm::ErrorNotification.
void _finishHandle (const Poco::AutoPtr< Algorithm::FinishedNotification > &pNf)
Poco notification handler for Algorithm::FinishedNotification.
void _progressHandle (const Poco::AutoPtr< Algorithm::ProgressNotification > &pNf)
Poco notification handler for Algorithm::ProgressNotification.
void _startHandle (const Poco::AutoPtr< Algorithm::StartedNotification > &pNf)
Poco notification handler for Algorithm::StartedNotification.
void _startingHandle (const Poco::AutoPtr< AlgorithmStartingNotification > &pNf)
Poco notification handler for API::AlgorithmStartingNotification.
Private Attributes
Poco::NObserver< AlgorithmObserver, Algorithm::ErrorNotification > m_errorObserver
Poco::NObserver for Algorithm::ErrorNotification.
Poco::NObserver< AlgorithmObserver, Algorithm::FinishedNotification > m_finishObserver
Poco::NObserver for Algorithm::FinishedNotification.
Poco::NObserver< AlgorithmObserver, Algorithm::ProgressNotification > m_progressObserver
Poco::NObserver for Algorithm::ProgressNotification.
Poco::NObserver< AlgorithmObserver, AlgorithmStartingNotification > m_startingObserver
Poco::NObserver for API::AlgorithmStartingNotification.
Poco::NObserver< AlgorithmObserver, Algorithm::StartedNotification > m_startObserver
Poco::NObserver for Algorithm::StartedNotification.
Detailed Description
Observes Algorithm notifications: start,progress,finish,error.
Hides Poco::Notification API from the user.
Definition at line 23 of file AlgorithmObserver.h.
Constructor & Destructor Documentation
AlgorithmObserver() [1/2]
Mantid::API::AlgorithmObserver::AlgorithmObserver ()
Default constructor.
Notification handlers are not connected to any algorithm
Definition at line 19 of file AlgorithmObserver.cpp.
AlgorithmObserver() [2/2]
Mantid::API::AlgorithmObserver::AlgorithmObserver (const IAlgorithm_const_sptr & alg)
Constructs AlgorithmObserver and connects all its handlers to algorithm alg.
Parameters
alg :: Algorithm to be observed
Definition at line 30 of file AlgorithmObserver.cpp.
References observeAll().
~AlgorithmObserver()
Mantid::API::AlgorithmObserver::~AlgorithmObserver () virtual default
Virtual destructor.
Member Function Documentation
_errorHandle()
void Mantid::API::AlgorithmObserver::_errorHandle (const Poco::AutoPtr< Algorithm::ErrorNotification > & pNf) private
Poco notification handler for Algorithm::ErrorNotification.
Parameters
pNf :: An pointer to the notification.
Definition at line 171 of file AlgorithmObserver.cpp.
References errorHandle().
_finishHandle()
void Mantid::API::AlgorithmObserver::_finishHandle (const Poco::AutoPtr< Algorithm::FinishedNotification > & pNf) private
Poco notification handler for Algorithm::FinishedNotification.
Parameters
pNf :: An pointer to the notification.
Definition at line 164 of file AlgorithmObserver.cpp.
References finishHandle().
_progressHandle()
void Mantid::API::AlgorithmObserver::_progressHandle (const Poco::AutoPtr< Algorithm::ProgressNotification > & pNf) private
Poco notification handler for Algorithm::ProgressNotification.
Parameters
pNf :: An pointer to the notification.
Definition at line 150 of file AlgorithmObserver.cpp.
References progressHandle().
_startHandle()
void Mantid::API::AlgorithmObserver::_startHandle (const Poco::AutoPtr< Algorithm::StartedNotification > & pNf) private
Poco notification handler for Algorithm::StartedNotification.
Parameters
pNf :: An pointer to the notification.
Definition at line 157 of file AlgorithmObserver.cpp.
References startHandle().
_startingHandle()
void Mantid::API::AlgorithmObserver::_startingHandle (const Poco::AutoPtr< AlgorithmStartingNotification > & pNf) private
Poco notification handler for API::AlgorithmStartingNotification.
Parameters
pNf :: An pointer to the notification.
Definition at line 178 of file AlgorithmObserver.cpp.
References startingHandle().
errorHandle()
virtual void Mantid::API::AlgorithmObserver::errorHandle (const IAlgorithm * alg, const std::string & what) virtual
Reimplemented in Mantid::PythonInterface::AlgorithmObserverAdapter, MantidQt::API::AlgorithmDialog, and MantidQt::MantidWidgets::AlgorithmProgressModel.
Referenced by _errorHandle().
finishHandle()
virtual void Mantid::API::AlgorithmObserver::finishHandle (const IAlgorithm * alg) virtual
Reimplemented in Mantid::PythonInterface::AlgorithmObserverAdapter, MantidQt::API::AlgorithmDialog, MantidQt::MantidWidgets::AlgorithmProgressModel, MantidQt::MantidWidgets::FitPropertyBrowser, MantidQt::MantidWidgets::MuonFitPropertyBrowser, and MantidQt::MantidWidgets::SequentialFitDialog.
Referenced by _finishHandle().
observeAll()
void Mantid::API::AlgorithmObserver::observeAll (const IAlgorithm_const_sptr & alg)
Connect to algorithm alg and observe all its notifications.
Parameters
alg :: Algorithm to be observed
Definition at line 45 of file AlgorithmObserver.cpp.
References m_errorObserver, m_finishObserver, m_progressObserver, and m_startObserver.
Referenced by AlgorithmObserver().
observeError()
void Mantid::API::AlgorithmObserver::observeError (const IAlgorithm_const_sptr & alg)
Connect to algorithm alg and observe its error notification.
Parameters
alg :: Algorithm to be observed
Definition at line 76 of file AlgorithmObserver.cpp.
References m_errorObserver.
Referenced by MantidQt::API::AlgorithmDialog::executeAlgorithmAsync(), observeError(), and MantidQt::MantidWidgets::AlgorithmProgressModel::startingHandle().
observeFinish()
void Mantid::API::AlgorithmObserver::observeFinish (const IAlgorithm_const_sptr & alg)
Connect to algorithm alg and observe its finish notification.
Parameters
alg :: Algorithm to be observed
Definition at line 71 of file AlgorithmObserver.cpp.
References m_finishObserver.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::MantidWidgets::FitPropertyBrowser::doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), MantidQt::API::AlgorithmDialog::executeAlgorithmAsync(), observeFinish(), and MantidQt::MantidWidgets::AlgorithmProgressModel::startingHandle().
observeProgress()
void Mantid::API::AlgorithmObserver::observeProgress (const IAlgorithm_const_sptr & alg)
Connect to algorithm alg and observe its progress notification.
Parameters
alg :: Algorithm to be observed
Definition at line 55 of file AlgorithmObserver.cpp.
References m_progressObserver.
Referenced by observeProgress(), and MantidQt::MantidWidgets::AlgorithmProgressModel::startingHandle().
observeStart()
void Mantid::API::AlgorithmObserver::observeStart (const IAlgorithm_const_sptr & alg)
Connect to algorithm alg and observe its start notification.
Parameters
alg :: Algorithm to be observed
Definition at line 66 of file AlgorithmObserver.cpp.
References m_startObserver.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::startingHandle().
observeStarting()
void Mantid::API::AlgorithmObserver::observeStarting ()
Connect to AlgorithmManager and observe its starting notifications.
Definition at line 59 of file AlgorithmObserver.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and m_startingObserver.
Referenced by MantidQt::MantidWidgets::AlgorithmProgressModel::AlgorithmProgressModel(), Mantid::Algorithms::RecordPythonScript::exec(), and export_algorithm_observer().
progressHandle()
virtual void Mantid::API::AlgorithmObserver::progressHandle (const IAlgorithm * alg, double p, const std::string & msg, const double estimatedTime, const int progressPrecision) virtual
Reimplemented in Mantid::PythonInterface::AlgorithmObserverAdapter, and MantidQt::MantidWidgets::AlgorithmProgressModel.
Referenced by _progressHandle().
startHandle()
virtual void Mantid::API::AlgorithmObserver::startHandle (const IAlgorithm * alg) virtual
Reimplemented in MantidQt::MantidWidgets::AlgorithmProgressModel.
Referenced by _startHandle().
startingHandle()
virtual void Mantid::API::AlgorithmObserver::startingHandle (IAlgorithm_sptr alg) virtual
Reimplemented in Mantid::Algorithms::RecordPythonScript, Mantid::PythonInterface::AlgorithmObserverAdapter, and MantidQt::MantidWidgets::AlgorithmProgressModel.
Referenced by _startingHandle().
stopObserving() [1/2]
void Mantid::API::AlgorithmObserver::stopObserving (const IAlgorithm_const_sptr & alg)
Disconnect from algorithm alg.
Should be called in the destructor of inherited classes.
Parameters
alg :: Algorithm to be disconnected
Definition at line 82 of file AlgorithmObserver.cpp.
References stopObserving().
Referenced by MantidQt::API::AlgorithmDialog::executeAlgorithmAsync(), MantidQt::MantidWidgets::AlgorithmProgressModel::removeFrom(), stopObserving(), stopObserving(), and MantidQt::API::AlgorithmDialog::~AlgorithmDialog().
stopObserving() [2/2]
void Mantid::API::AlgorithmObserver::stopObserving (const Mantid::API::IAlgorithm * alg)
Definition at line 84 of file AlgorithmObserver.cpp.
References m_errorObserver, m_finishObserver, m_progressObserver, m_startObserver, and Mantid::API::IAlgorithm::removeObserver().
stopObservingManager()
void Mantid::API::AlgorithmObserver::stopObservingManager ()
Disconnect from the algorithm manager.
Definition at line 94 of file AlgorithmObserver.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and m_startingObserver.
Referenced by Mantid::Algorithms::RecordPythonScript::exec(), and MantidQt::MantidWidgets::AlgorithmProgressModel::~AlgorithmProgressModel().
Member Data Documentation
m_errorObserver
Poco::NObserver<AlgorithmObserver, Algorithm::ErrorNotification> Mantid::API::AlgorithmObserver::m_errorObserver private
Poco::NObserver for Algorithm::ErrorNotification.
Definition at line 62 of file AlgorithmObserver.h.
Referenced by observeAll(), observeError(), and stopObserving().
m_finishObserver
Poco::NObserver<AlgorithmObserver, Algorithm::FinishedNotification> Mantid::API::AlgorithmObserver::m_finishObserver private
Poco::NObserver for Algorithm::FinishedNotification.
Definition at line 58 of file AlgorithmObserver.h.
Referenced by observeAll(), observeFinish(), and stopObserving().
m_progressObserver
Poco::NObserver<AlgorithmObserver, Algorithm::ProgressNotification> Mantid::API::AlgorithmObserver::m_progressObserver private
Poco::NObserver for Algorithm::ProgressNotification.
Definition at line 50 of file AlgorithmObserver.h.
Referenced by observeAll(), observeProgress(), and stopObserving().
m_startingObserver
Poco::NObserver<AlgorithmObserver, AlgorithmStartingNotification> Mantid::API::AlgorithmObserver::m_startingObserver private
Poco::NObserver for API::AlgorithmStartingNotification.
Definition at line 66 of file AlgorithmObserver.h.
Referenced by observeStarting(), and stopObservingManager().
m_startObserver
Poco::NObserver<AlgorithmObserver, Algorithm::StartedNotification> Mantid::API::AlgorithmObserver::m_startObserver private
Poco::NObserver for Algorithm::StartedNotification.
Definition at line 54 of file AlgorithmObserver.h.
Referenced by observeAll(), observeStart(), and stopObserving().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/AlgorithmObserver.h
Framework/API/src/AlgorithmObserver.cpp