Mantid: ICat4::ns1__luceneSearch Class Reference
ICat4::ns1__luceneSearch Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__luceneSearch ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * entityName
int maxCount
std::string * query
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 536 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__luceneSearch()
ICat4::ns1__luceneSearch::ns1__luceneSearch () inline
Definition at line 550 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__luceneSearch::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21181 of file ICat4C.cpp.
References entityName, maxCount, query, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_int().
Referenced by ICat4::soap_in_ns1__luceneSearch(), ICat4::soap_new_req_ns1__luceneSearch(), and ICat4::soap_new_set_ns1__luceneSearch().
soap_get()
void * ICat4::ns1__luceneSearch::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21306 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__luceneSearch().
soap_in()
void * ICat4::ns1__luceneSearch::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21222 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__luceneSearch().
Referenced by ICat4::soap_in_ns1__luceneSearch().
soap_out()
int ICat4::ns1__luceneSearch::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21201 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__luceneSearch().
Referenced by soap_put().
soap_put()
int ICat4::ns1__luceneSearch::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21299 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__luceneSearch.
soap_serialize()
void ICat4::ns1__luceneSearch::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21190 of file ICat4C.cpp.
References entityName, maxCount, query, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTostd__string(), and SOAP_TYPE_ICat4_int.
Referenced by ICat4::soap_serialize_PointerTons1__luceneCommitResponse().
soap_type()
int ICat4::ns1__luceneSearch::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 543 of file ICat4Stub.h.
Member Data Documentation
entityName
std::string* ICat4::ns1__luceneSearch::entityName
Definition at line 541 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
maxCount
int ICat4::ns1__luceneSearch::maxCount
Definition at line 540 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
query
std::string* ICat4::ns1__luceneSearch::query
Definition at line 539 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
sessionId
std::string* ICat4::ns1__luceneSearch::sessionId
Definition at line 538 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp