Mantid: Mantid::DataHandling::ANSTO Namespace Reference
Mantid::DataHandling::ANSTO Namespace Reference
Namespaces
namespace Anxs
namespace Tar
Classes
class EventAssigner
class EventAssignerFixedWavelength
class EventCounter
struct EventFileHeader_Base
struct EventFileHeader_Packed
class EventProcessor
class FastReadOnlyFile
class ProgressTracker
helper class to keep track of progress
Typedefs
using EventVector_pt = std::vector< Types::Event::TofEvent > *
pointer to the vector of events
Enumerations
enum event_decode_state {
DECODE_START , DECODE_OOB_BYTE_1 , DECODE_OOB_BYTE_2 , DECODE_VAL_BITFIELDS ,
DECODE_DT
}
Functions
std::vector< std::string > filterDatasets (const Nexus::NXEntry &entry, const std::string &groupAddress, const std::string &regexFilter)
extract datasets from a group that match a regex filter
template<class IReader , class IEventHandler , class IProgress >
void ReadEventFile (IReader &loader, IEventHandler &handler, IProgress &progress, int32_t def_clock_scale, bool use_tx_chopper)
Variables
constexpr int32_t EVENTFILEHEADER_BASE_FORMAT_NUMBER = 0x00010002
constexpr int32_t EVENTFILEHEADER_BASE_MAGIC_NUMBER = 0x0DAE0DAE
constexpr int32_t NVAL = 5
Typedef Documentation
EventVector_pt
using Mantid::DataHandling::ANSTO::EventVector_pt = typedef std::vector<Types::Event::TofEvent> *
pointer to the vector of events
Definition at line 39 of file LoadANSTOHelper.h.
Enumeration Type Documentation
event_decode_state
enum Mantid::DataHandling::ANSTO::event_decode_state
Enumerator
DECODE_START
DECODE_OOB_BYTE_1
DECODE_OOB_BYTE_2
DECODE_VAL_BITFIELDS
DECODE_DT
Definition at line 56 of file LoadANSTOEventFile.h.
Function Documentation
filterDatasets()
std::vector< std::string > Mantid::DataHandling::ANSTO::filterDatasets (const Nexus::NXEntry & entry, const std::string & groupAddress, const std::string & regexFilter)
extract datasets from a group that match a regex filter
Definition at line 24 of file LoadANSTOHelper.cpp.
References Mantid::Nexus::NXClass::datasets(), group, and Mantid::Nexus::NXClass::openNXGroup().
Referenced by Mantid::DataHandling::LoadEMU< FD >::loadEnvironParameters(), and Mantid::DataHandling::LoadPLN::loadEnvironParameters().
ReadEventFile()
template<class IReader , class IEventHandler , class IProgress > void Mantid::DataHandling::ANSTO::ReadEventFile (IReader & loader, IEventHandler & handler, IProgress & progress, int32_t def_clock_scale, bool use_tx_chopper)
Definition at line 89 of file LoadANSTOEventFile.h.
References Mantid::DataHandling::ANSTO::EventFileHeader_Base::clock_scale, DECODE_DT, DECODE_OOB_BYTE_1, DECODE_OOB_BYTE_2, DECODE_START, DECODE_VAL_BITFIELDS, EVENTFILEHEADER_BASE_FORMAT_NUMBER, EVENTFILEHEADER_BASE_MAGIC_NUMBER, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_nbits_v, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_nbits_w, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_nbits_wa, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_nbits_x, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_nbits_y, Mantid::DataHandling::ANSTO::EventFileHeader_Packed::evt_stg_xy_signed, Mantid::DataHandling::ANSTO::EventFileHeader_Base::format_number, Mantid::DataHandling::ANSTO::EventFileHeader_Base::magic_number, NVAL, Mantid::DataHandling::ANSTO::EventFileHeader_Base::oob_enabled, Mantid::DataHandling::ANSTO::EventFileHeader_Base::pack_format, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::DataHandling::EMU::loadEvents(), and Mantid::DataHandling::PLN::loadEvents().
Variable Documentation
EVENTFILEHEADER_BASE_FORMAT_NUMBER
constexpr int32_t Mantid::DataHandling::ANSTO::EVENTFILEHEADER_BASE_FORMAT_NUMBER = 0x00010002 constexpr
Definition at line 21 of file LoadANSTOEventFile.h.
Referenced by ReadEventFile().
EVENTFILEHEADER_BASE_MAGIC_NUMBER
constexpr int32_t Mantid::DataHandling::ANSTO::EVENTFILEHEADER_BASE_MAGIC_NUMBER = 0x0DAE0DAE constexpr
Definition at line 20 of file LoadANSTOEventFile.h.
Referenced by ReadEventFile().
NVAL
constexpr int32_t Mantid::DataHandling::ANSTO::NVAL = 5 constexpr
Definition at line 24 of file LoadANSTOEventFile.h.
Referenced by ReadEventFile().