Mantid: Mantid::Algorithms::SampleLogsBehaviour Class Reference
Mantid::Algorithms::SampleLogsBehaviour Class Reference
SampleLogsBehaviour : This class holds information relating to the behaviour of the sample log merging.
#include <SampleLogsBehaviour.h>
Classes
struct ParameterName
struct SampleLogBehaviour
struct SampleLogNames
Public Types
enum class MergeLogType {
Sum , TimeSeries , List , Warn ,
Fail
}
Public Member Functions
void mergeSampleLogs (const API::MatrixWorkspace_sptr &addeeWS, const API::MatrixWorkspace_sptr &outWS)
Create and update sample logs according to instrument parameters.
void readdSampleLogToWorkspace (const API::MatrixWorkspace_sptr &addeeWS)
When doing a time series merge we need to remove, then add back the sample log in the addee workspace to supress a warning about it not being a TimeSeriesProperty.
void removeSampleLogsFromWorkspace (const API::MatrixWorkspace_sptr &addeeWS)
When doing a time series merge we need to remove, then add back the sample log in the addee workspace to supress a warning about it not being a TimeSeriesProperty.
void resetSampleLogs (const API::MatrixWorkspace_sptr &ws)
Resets the sample logs in the workspace to the values in the map.
SampleLogsBehaviour (const API::MatrixWorkspace_sptr &ws, Kernel::Logger &logger, const SampleLogNames &logEntries={}, ParameterName parName={})
Create and initialise an object that is responsbile for keeping track of the merge types, and performing the merge or warning/error for sample logs when calling MergeRuns.
void setUpdatedSampleLogs (const API::MatrixWorkspace_sptr &outWS)
Set the values in the map to be the same as those in the output workspace.
Public Attributes
struct Mantid::Algorithms::SampleLogsBehaviour::ParameterName parameterNames
Static Public Attributes
static const std::string FAIL_DOC
static const std::string FAIL_PROP = "SampleLogsFail"
static const std::string FAIL_TOL_DOC
static const std::string FAIL_TOL_PROP = "SampleLogsFailTolerances"
static const std::string LIST_DOC
static const std::string LIST_PROP = "SampleLogsList"
static const std::string SUM_DOC
static const std::string SUM_PROP = "SampleLogsSum"
static const std::string TIME_SERIES_DOC
static const std::string TIME_SERIES_PROP = "SampleLogsTimeSeries"
static const std::string WARN_DOC
static const std::string WARN_PROP = "SampleLogsWarn"
static const std::string WARN_TOL_DOC
static const std::string WARN_TOL_PROP = "SampleLogsWarnTolerances"
Private Types
using SampleLogsKey = std::pair< std::string, MergeLogType >
using SampleLogsMap = std::map< SampleLogsKey, SampleLogBehaviour >
Private Member Functions
std::shared_ptr< Kernel::Property > addPropertyForList (const std::string &item, const std::string &value, API::MatrixWorkspace &ws)
Adds a property to the workspace provided for a List merge type.
std::shared_ptr< Kernel::Property > addPropertyForTimeSeries (const std::string &item, const double value, API::MatrixWorkspace &ws)
Adds a property to the workspace provided for a TimeSeries merge type.
void checkErrorProperty (const API::MatrixWorkspace &addeeWS, const Kernel::Property *addeeWSProperty, const SampleLogBehaviour &behaviour, const double addeeWSNumber, const double outWSNumber, const std::string &name)
Performs the check to see if an error should be generated because logs are different.
void checkWarnProperty (const API::MatrixWorkspace &addeeWS, const Kernel::Property *addeeWSProperty, const SampleLogBehaviour &behaviour, const double addeeWSNumber, const double outWSNumber, const std::string &name)
Performs the check to see if a warning should be generated because logs are different.
void createSampleLogsMapsFromInstrumentParams (SampleLogsMap &instrumentMap, API::MatrixWorkspace &ws)
Extracts all of the settings from the instrument parameters, and adds them to a map of sample log behaviours.
std::vector< double > createTolerancesVector (const size_t numberNames, const std::vector< std::string > &tolerances)
Creates a vector of tolerances with the same size as the number of sample logs for the merge type.
bool isWithinTolerance (const SampleLogBehaviour &behaviour, const double addeeWSNumber, const double outWSNumber)
Check if a sample log value in the addee workspace is numeric and within tolerances.
bool setNumericValue (const std::string &item, const API::MatrixWorkspace &ws, double &value)
Tries to set the numeric value of a property.
void setSampleMap (SampleLogsMap &map, const MergeLogType &, const std::string &params, API::MatrixWorkspace &ws, const std::string &paramsTolerances="", bool skipIfInPrimaryMap=false)
This method updates the map with the sample log behaviour, and adds the new property to the workspace if required.
bool stringPropertiesMatch (const SampleLogBehaviour &behaviour, const Kernel::Property *addeeWSProperty)
Check if a sample log value in the addee workspace matches one in the first workspace.
void updateListProperty (const API::MatrixWorkspace &addeeWS, API::MatrixWorkspace &outWS, const std::string &name)
Perform the update for a list property, appending a new value to the existing string.
void updateSumProperty (double addeeWSNumber, double outWSNumber, API::MatrixWorkspace &outWS, const std::string &name)
Perform the update for a sum property, adding a new value to the existing one.
void updateTimeSeriesProperty (const API::MatrixWorkspace &addeeWS, const API::MatrixWorkspace &outWS, const std::string &name)
Perform the update for a time series property, adding a new value to the existing time series property.
Private Attributes
std::vector< std::shared_ptr< Kernel::Property > > m_addeeLogMap
Kernel::Logger & m_logger
SampleLogsMap m_logMap
Detailed Description
SampleLogsBehaviour : This class holds information relating to the behaviour of the sample log merging.
It holds a map of all the sample log parameters to merge, how to merge them, and the associated tolerances. Algorithms which already define paramter names for the instrument parameter file are ConjoinXRuns and MergeRuns. Please use different names for new algorithms.
Definition at line 24 of file SampleLogsBehaviour.h.
Member Typedef Documentation
SampleLogsKey
using Mantid::Algorithms::SampleLogsBehaviour::SampleLogsKey = std::pair<std::string, MergeLogType> private
Definition at line 85 of file SampleLogsBehaviour.h.
SampleLogsMap
using Mantid::Algorithms::SampleLogsBehaviour::SampleLogsMap = std::map<SampleLogsKey, SampleLogBehaviour> private
Definition at line 86 of file SampleLogsBehaviour.h.
Member Enumeration Documentation
MergeLogType
enum class Mantid::Algorithms::SampleLogsBehaviour::MergeLogType strong
Enumerator
Sum
TimeSeries
List
Warn
Fail
Definition at line 26 of file SampleLogsBehaviour.h.
Constructor & Destructor Documentation
SampleLogsBehaviour()
Mantid::Algorithms::SampleLogsBehaviour::SampleLogsBehaviour (const API::MatrixWorkspace_sptr & ws, Kernel::Logger & logger, const SampleLogNames & logEntries = {}, ParameterName parName = {})
Create and initialise an object that is responsbile for keeping track of the merge types, and performing the merge or warning/error for sample logs when calling MergeRuns.
Parameters
ws the base workspace that the other workspaces are merged into
logger the logger from the parent algorithm
logEntries the sample log names to merge given by the user which override names given by IPF parameters
parName the parameter names which specify the sample log sames to merge given be the IPF
Definition at line 81 of file SampleLogsBehaviour.cpp.
References createSampleLogsMapsFromInstrumentParams(), Fail, List, m_logMap, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsFail, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsFailTolerances, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsList, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsSum, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsTimeSeries, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsWarn, Mantid::Algorithms::SampleLogsBehaviour::SampleLogNames::sampleLogsWarnTolerances, setSampleMap(), Sum, TimeSeries, and Warn.
Member Function Documentation
addPropertyForList()
std::shared_ptr< Property > Mantid::Algorithms::SampleLogsBehaviour::addPropertyForList (const std::string & item, const std::string & value, API::MatrixWorkspace & ws) private
Adds a property to the workspace provided for a List merge type.
Parameters
item the name of the sample log to merge as a list
value the string value of the sample log in the first workspace
ws the first workspace in the merge
Returns
a shared pointer to the added property
Definition at line 328 of file SampleLogsBehaviour.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::Kernel::Property::clone(), Mantid::API::ExperimentInfo::getLog(), Mantid::API::ExperimentInfo::mutableRun(), Mantid::Kernel::Property::setUnits(), Mantid::Kernel::Property::units(), and value.
Referenced by setSampleMap().
addPropertyForTimeSeries()
std::shared_ptr< Property > Mantid::Algorithms::SampleLogsBehaviour::addPropertyForTimeSeries (const std::string & item, const double value, API::MatrixWorkspace & ws) private
Adds a property to the workspace provided for a TimeSeries merge type.
Parameters
item the name of the sample log to merge as a time series
value the numeric value of the sample log in the first workspace
ws the first workspace in the merge
Returns
a shared pointer to the added property
Definition at line 297 of file SampleLogsBehaviour.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::Kernel::Property::clone(), Mantid::API::ExperimentInfo::getLog(), Mantid::API::LogManager::getTimeSeriesProperty(), Mantid::API::ExperimentInfo::mutableRun(), Mantid::API::ExperimentInfo::run(), Mantid::Kernel::Property::setUnits(), Mantid::API::LogManager::startTime(), Mantid::Kernel::Property::units(), and value.
Referenced by setSampleMap().
checkErrorProperty()
void Mantid::Algorithms::SampleLogsBehaviour::checkErrorProperty (const API::MatrixWorkspace & addeeWS, const Kernel::Property * addeeWSProperty, const SampleLogBehaviour & behaviour, const double addeeWSNumericValue, const double outWSNumericValue, const std::string & name) private
Performs the check to see if an error should be generated because logs are different.
Performs a numeric comparison if a tolerance is set and the log is a number, else performs a string comparison.
Parameters
addeeWS the workspace being merged
addeeWSProperty the property value of the workspace being merged
behaviour the merge behaviour struct, containing information about the merge
addeeWSNumericValue a double for the addeeWS value (0 if it is not numeric)
outWSNumericValue a double for the outWS value (0 if it is not numeric)
name the name of the sample log to check
Definition at line 511 of file SampleLogsBehaviour.cpp.
References Mantid::API::Workspace::getName(), isWithinTolerance(), name, Mantid::Algorithms::SampleLogsBehaviour::SampleLogBehaviour::property, stringPropertiesMatch(), and Mantid::Kernel::Property::value().
Referenced by mergeSampleLogs().
checkWarnProperty()
void Mantid::Algorithms::SampleLogsBehaviour::checkWarnProperty (const API::MatrixWorkspace & addeeWS, const Kernel::Property * addeeWSProperty, const SampleLogBehaviour & behaviour, const double addeeWSNumericValue, const double outWSNumericValue, const std::string & name) private
Performs the check to see if a warning should be generated because logs are different.
Performs a numeric comparison if a tolerance is set and the log is a number, else performs a string comparison.
Parameters
addeeWS the workspace being merged
addeeWSProperty the property value of the workspace being merged
behaviour the merge behaviour struct, containing information about the merge
addeeWSNumericValue a double for the addeeWS value (0 if it is not numeric)
outWSNumericValue a double for the outWS value (0 if it is not numeric)
name the name of the sample log to check
Definition at line 485 of file SampleLogsBehaviour.cpp.
References Mantid::API::Workspace::getName(), isWithinTolerance(), m_logger, name, Mantid::Algorithms::SampleLogsBehaviour::SampleLogBehaviour::property, stringPropertiesMatch(), Mantid::Kernel::Property::value(), and Mantid::Kernel::Logger::warning().
Referenced by mergeSampleLogs().
createSampleLogsMapsFromInstrumentParams()
void Mantid::Algorithms::SampleLogsBehaviour::createSampleLogsMapsFromInstrumentParams (SampleLogsMap & map, API::MatrixWorkspace & ws) private
Extracts all of the settings from the instrument parameters, and adds them to a map of sample log behaviours.
Parameters
map the map to add the merge behaviours to
ws the workspace with the instrument and initial map
Definition at line 105 of file SampleLogsBehaviour.cpp.
References Fail, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::FAIL_MERGE, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::FAIL_MERGE_TOLERANCES, Mantid::API::ExperimentInfo::getInstrument(), List, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::LIST_MERGE, parameterNames, setSampleMap(), Sum, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::SUM_MERGE, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::TIME_SERIES_MERGE, TimeSeries, Warn, Mantid::Algorithms::SampleLogsBehaviour::ParameterName::WARN_MERGE, and Mantid::Algorithms::SampleLogsBehaviour::ParameterName::WARN_MERGE_TOLERANCES.
Referenced by SampleLogsBehaviour().
createTolerancesVector()
std::vector< double > Mantid::Algorithms::SampleLogsBehaviour::createTolerancesVector (const size_t numberNames, const std::vector< std::string > & tolerances) private
Creates a vector of tolerances with the same size as the number of sample logs for the merge type.
If the number of names and tolerances is the same the vector is filled with the tolerances for each name. If no tolerances were specified all tolerances are set to -1, and if one tolerance is given all tolerances are set to that value.
Parameters
numberNames the number of sample log names
tolerances a vector containing strings with the tolerances
Returns
a vector of doubles of size numberNames
Definition at line 238 of file SampleLogsBehaviour.cpp.
References std::to_string(), and value.
Referenced by setSampleMap().
isWithinTolerance()
bool Mantid::Algorithms::SampleLogsBehaviour::isWithinTolerance (const SampleLogBehaviour & behaviour, const double addeeWSNumericValue, const double outWSNumericValue) private
Check if a sample log value in the addee workspace is numeric and within tolerances.
Parameters
behaviour the SampleLogBehaviour item to check
addeeWSNumericValue the value in the workspace being added
outWSNumericValue the value in the first workspace
Returns
true if the sample log is numeric and within any tolerance set, or if strings match, false otherwise
Definition at line 532 of file SampleLogsBehaviour.cpp.
References Mantid::Algorithms::SampleLogsBehaviour::SampleLogBehaviour::isNumeric, Mantid::Algorithms::SampleLogsBehaviour::SampleLogBehaviour::tolerance, and Mantid::Kernel::withinAbsoluteDifference().
Referenced by checkErrorProperty(), and checkWarnProperty().
mergeSampleLogs()
void Mantid::Algorithms::SampleLogsBehaviour::mergeSampleLogs (const API::MatrixWorkspace_sptr & addeeWS, const API::MatrixWorkspace_sptr & outWS)
Create and update sample logs according to instrument parameters.
Updates the sample logs according to the requested behaviour.
Parameters
addeeWS the workspace being merged
outWS the workspace the others are merged into
Definition at line 371 of file SampleLogsBehaviour.cpp.
References checkErrorProperty(), checkWarnProperty(), Fail, List, m_logMap, Sum, TimeSeries, Mantid::Kernel::Property::units(), updateListProperty(), updateSumProperty(), updateTimeSeriesProperty(), and Warn.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), and Mantid::Algorithms::MergeRuns::execHistogram().
readdSampleLogToWorkspace()
void Mantid::Algorithms::SampleLogsBehaviour::readdSampleLogToWorkspace (const API::MatrixWorkspace_sptr & addeeWS)
When doing a time series merge we need to remove, then add back the sample log in the addee workspace to supress a warning about it not being a TimeSeriesProperty.
Here we add back the original property, as the original workspace should remain unchanged.
Parameters
addeeWS the workspace being merged
Definition at line 593 of file SampleLogsBehaviour.cpp.
References m_addeeLogMap.
Referenced by Mantid::Algorithms::MergeRuns::execHistogram().
removeSampleLogsFromWorkspace()
void Mantid::Algorithms::SampleLogsBehaviour::removeSampleLogsFromWorkspace (const API::MatrixWorkspace_sptr & addeeWS)
When doing a time series merge we need to remove, then add back the sample log in the addee workspace to supress a warning about it not being a TimeSeriesProperty.
Here we remove the original property.
Parameters
addeeWS the workspace being merged
Definition at line 578 of file SampleLogsBehaviour.cpp.
References m_addeeLogMap.
Referenced by Mantid::Algorithms::MergeRuns::execHistogram().
resetSampleLogs()
void Mantid::Algorithms::SampleLogsBehaviour::resetSampleLogs (const API::MatrixWorkspace_sptr & ws)
Resets the sample logs in the workspace to the values in the map.
Parameters
ws the merged workspace to reset the sample logs for
Definition at line 606 of file SampleLogsBehaviour.cpp.
References List, m_logMap, Sum, and TimeSeries.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), and Mantid::Algorithms::MergeRuns::execHistogram().
setNumericValue()
bool Mantid::Algorithms::SampleLogsBehaviour::setNumericValue (const std::string & item, const API::MatrixWorkspace & ws, double & value) private
Tries to set the numeric value of a property.
Parameters
item the name of the sample log
ws the first workspace in the merge
value the value of the sample log (if it could be set)
Returns
true if the sample log could be converted to a double, false otherwise
Definition at line 352 of file SampleLogsBehaviour.cpp.
References Mantid::API::ExperimentInfo::getLogAsSingleValue(), and value.
Referenced by setSampleMap().
setSampleMap()
void Mantid::Algorithms::SampleLogsBehaviour::setSampleMap (SampleLogsMap & map, const MergeLogType & mergeType, const std::string & params, API::MatrixWorkspace & ws, const std::string & paramsTolerances = "", bool skipIfInPrimaryMap = false) private
This method updates the map with the sample log behaviour, and adds the new property to the workspace if required.
if skipIfInPrimaryMap is true sample logs in the primary map are ignored. Throws std::invalid_argument if a sample log is not found.
Parameters
map the map to add the merge behaviours to
mergeType an enum for the type of merge to perform
params a string containing a comma separated list of the sample logs to merge for this behaviour
ws the base workspace that the other workspaces are merged into
paramsTolerances a string containing a comma spearated list of the tolerances for this merge behaviour (optional)
skipIfInPrimaryMap whether to skip if in the member variable map (optional, default false)
Definition at line 141 of file SampleLogsBehaviour.cpp.
References addPropertyForList(), addPropertyForTimeSeries(), Mantid::Kernel::StringTokenizer::asVector(), Mantid::Kernel::StringTokenizer::begin(), Mantid::Kernel::Property::clone(), createTolerancesVector(), Mantid::Kernel::StringTokenizer::end(), Mantid::Kernel::Logger::error(), Mantid::API::ExperimentInfo::getLog(), List, m_logger, m_logMap, setNumericValue(), Sum, TimeSeries, Mantid::Kernel::StringTokenizer::TOK_IGNORE_EMPTY, Mantid::Kernel::StringTokenizer::TOK_TRIM, tolerance, and value.
Referenced by createSampleLogsMapsFromInstrumentParams(), and SampleLogsBehaviour().
setUpdatedSampleLogs()
void Mantid::Algorithms::SampleLogsBehaviour::setUpdatedSampleLogs (const API::MatrixWorkspace_sptr & outWS)
Set the values in the map to be the same as those in the output workspace.
Parameters
outWS the merged workspace
Definition at line 558 of file SampleLogsBehaviour.cpp.
References Mantid::Kernel::Property::clone(), Fail, m_logMap, and Warn.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), and Mantid::Algorithms::MergeRuns::execHistogram().
stringPropertiesMatch()
bool Mantid::Algorithms::SampleLogsBehaviour::stringPropertiesMatch (const SampleLogBehaviour & behaviour, const Kernel::Property * addeeWSProperty) private
Check if a sample log value in the addee workspace matches one in the first workspace.
Parameters
behaviour the SampleLogBehaviour item to check
addeeWSProperty a pointer to the property in the workspace being added
Returns
true if the sample logs match, false otherwise
Definition at line 549 of file SampleLogsBehaviour.cpp.
References Mantid::Algorithms::SampleLogsBehaviour::SampleLogBehaviour::property, and Mantid::Kernel::Property::value().
Referenced by checkErrorProperty(), and checkWarnProperty().
updateListProperty()
void Mantid::Algorithms::SampleLogsBehaviour::updateListProperty (const API::MatrixWorkspace & addeeWS, API::MatrixWorkspace & outWS, const std::string & name) private
Perform the update for a list property, appending a new value to the existing string.
If the list log entry is in the addeeWS the list log entry is merged instead.
Parameters
addeeWS the workspace being merged
outWS the workspace the others are merged into
name the name of the property
Definition at line 463 of file SampleLogsBehaviour.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::API::ExperimentInfo::getLog(), Mantid::API::LogManager::getProperty(), Mantid::API::ExperimentInfo::mutableRun(), name, Mantid::API::ExperimentInfo::run(), and Mantid::Kernel::Property::value().
Referenced by mergeSampleLogs().
updateSumProperty()
void Mantid::Algorithms::SampleLogsBehaviour::updateSumProperty (double addeeWSNumericValue, double outWSNumericValue, API::MatrixWorkspace & outWS, const std::string & name) private
Perform the update for a sum property, adding a new value to the existing one.
Skipped if the time series log entry is in the addeeWS.
Parameters
addeeWSNumericValue the sample log value from the workspace being merged
outWSNumericValue the sample log value for the merged workspace
outWS the workspace the others are merged into
name the name of the property
Definition at line 424 of file SampleLogsBehaviour.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::API::ExperimentInfo::mutableRun(), and name.
Referenced by mergeSampleLogs().
updateTimeSeriesProperty()
void Mantid::Algorithms::SampleLogsBehaviour::updateTimeSeriesProperty (const API::MatrixWorkspace & addeeWS, const API::MatrixWorkspace & outWS, const std::string & name) private
Perform the update for a time series property, adding a new value to the existing time series property.
Parameters
addeeWS the workspace being merged
outWS the workspace the others are merged into
name the name of the property
Definition at line 437 of file SampleLogsBehaviour.cpp.
References Mantid::Kernel::Property::clone(), Mantid::API::LogManager::getLogAsSingleValue(), Mantid::API::LogManager::getProperty(), Mantid::API::LogManager::getTimeSeriesProperty(), m_addeeLogMap, name, Mantid::API::ExperimentInfo::run(), Mantid::API::LogManager::startTime(), and value.
Referenced by mergeSampleLogs().
Member Data Documentation
FAIL_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::FAIL_DOC static
Initial value:
= "The sample logs to fail if different "
                                                  "when merging. If there is a "
                                                  "difference the run is skipped."
Definition at line 49 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
FAIL_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::FAIL_PROP = "SampleLogsFail" static
Definition at line 48 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
FAIL_TOL_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::FAIL_TOL_DOC static
Initial value:
= "The tolerances for failing if sample logs are different. "
                                                      "Can either be empty for a comparison of the strings, a "
                                                      "single value for all fail sample logs, or a comma "
                                                      "separated list of values (must be the same length as "
                                                      "SampleLogsFail)."
Definition at line 51 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
FAIL_TOL_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::FAIL_TOL_PROP = "SampleLogsFailTolerances" static
Definition at line 50 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
LIST_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::LIST_DOC static
Initial value:
= "A comma separated list of the sample logs to merge into a "
                                                  "list."
Definition at line 43 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
LIST_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::LIST_PROP = "SampleLogsList" static
Definition at line 42 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
m_addeeLogMap
std::vector<std::shared_ptr<Kernel::Property> > Mantid::Algorithms::SampleLogsBehaviour::m_addeeLogMap private
Definition at line 88 of file SampleLogsBehaviour.h.
Referenced by readdSampleLogToWorkspace(), removeSampleLogsFromWorkspace(), and updateTimeSeriesProperty().
m_logger
Kernel::Logger& Mantid::Algorithms::SampleLogsBehaviour::m_logger private
Definition at line 83 of file SampleLogsBehaviour.h.
Referenced by checkWarnProperty(), and setSampleMap().
m_logMap
SampleLogsMap Mantid::Algorithms::SampleLogsBehaviour::m_logMap private
Definition at line 87 of file SampleLogsBehaviour.h.
Referenced by mergeSampleLogs(), resetSampleLogs(), SampleLogsBehaviour(), setSampleMap(), and setUpdatedSampleLogs().
parameterNames
struct Mantid::Algorithms::SampleLogsBehaviour::ParameterName Mantid::Algorithms::SampleLogsBehaviour::parameterNames
Referenced by createSampleLogsMapsFromInstrumentParams().
SUM_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::SUM_DOC static
Initial value:
= "A comma separated list of the sample "
                                                 "logs to sum into a single entry.  "
                                                 "Sample logs must be numeric."
Definition at line 53 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
SUM_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::SUM_PROP = "SampleLogsSum" static
Definition at line 52 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
TIME_SERIES_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::TIME_SERIES_DOC static
Initial value:
= "A comma separated list of the sample logs to merge into a "
                                                         "time series. The initial times are taken as the start times "
                                                         "for the run. Sample logs must be numeric."
Definition at line 41 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
TIME_SERIES_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::TIME_SERIES_PROP = "SampleLogsTimeSeries" static
Definition at line 40 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
WARN_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::WARN_DOC static
Initial value:
= "A comma separated list of the sample "
                                                  "logs to generate a warning if "
                                                  "different when merging."
Definition at line 45 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
WARN_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::WARN_PROP = "SampleLogsWarn" static
Definition at line 44 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
WARN_TOL_DOC
const std::string Mantid::Algorithms::SampleLogsBehaviour::WARN_TOL_DOC static
Initial value:
= "The tolerances for warning if sample logs are different. "
                                                      "Can either be empty for a comparison of the strings, a "
                                                      "single value for all warn sample logs, or a comma "
                                                      "separated list of values (must be the same length as "
                                                      "SampleLogsWarn)."
Definition at line 47 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
WARN_TOL_PROP
const std::string Mantid::Algorithms::SampleLogsBehaviour::WARN_TOL_PROP = "SampleLogsWarnTolerances" static
Definition at line 46 of file SampleLogsBehaviour.h.
Referenced by Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::ConjoinXRuns::init(), and Mantid::Algorithms::MergeRuns::init().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/RunCombinationHelpers/SampleLogsBehaviour.h
Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp