Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/PropertyManagerProperty.cpp File Reference
PropertyManagerProperty.cpp File Reference
#include "MantidKernel/PropertyManagerProperty.h"
#include "MantidKernel/PropertyManager.h"
#include "MantidPythonInterface/core/PropertyWithValueExporter.h"
#include "MantidPythonInterface/kernel/Registry/MappingTypeHandler.h"
#include "MantidPythonInterface/kernel/Registry/PropertyManagerFactory.h"
#include "MantidPythonInterface/kernel/Registry/TypeRegistry.h"
#include <boost/python/class.hpp>
#include <boost/python/dict.hpp>
#include <boost/python/default_call_policies.hpp>
#include <boost/python/make_constructor.hpp>
Functions
PropertyManagerProperty * createPropertyManagerPropertyWithDict (const std::string &name, const boost::python::dict &value, const unsigned int &direction)
void export_PropertyManagerProperty ()
Function Documentation
createPropertyManagerPropertyWithDict()
PropertyManagerProperty * createPropertyManagerPropertyWithDict (const std::string & name, const boost::python::dict & value, const unsigned int & direction)
Definition at line 28 of file PropertyManagerProperty.cpp.
References Mantid::PythonInterface::Registry::createPropertyManager(), name, and value.
Referenced by export_PropertyManagerProperty().
export_PropertyManagerProperty()
void export_PropertyManagerProperty ()
Definition at line 34 of file PropertyManagerProperty.cpp.
References createPropertyManagerPropertyWithDict(), Mantid::PythonInterface::PropertyWithValueExporter< HeldType, ValueReturnPolicy >::define(), and Mantid::Kernel::Direction::Input.