Mantid: Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataServiceObserver.cpp File Reference
AnalysisDataServiceObserver.cpp File Reference
#include "MantidAPI/AnalysisDataServiceObserver.h"
#include "MantidPythonInterface/api/AnalysisDataServiceObserverAdapter.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/ReleaseGlobalInterpreterLock.h"
#include <boost/mpl/vector.hpp>
#include <boost/python/bases.hpp>
#include <boost/python/class.hpp>
#include <boost/python/make_function.hpp>
#include <functional>
Typedefs
using ObserverMethod = void(AnalysisDataServiceObserver::*)(bool)
using ObserverMethodSignature = boost::mpl::vector< void, AnalysisDataServiceObserver &, bool >
Functions
void export_AnalysisDataServiceObserver ()
Typedef Documentation
ObserverMethod
using ObserverMethod = void (AnalysisDataServiceObserver::*)(bool)
Definition at line 22 of file AnalysisDataServiceObserver.cpp.
ObserverMethodSignature
using ObserverMethodSignature = boost::mpl::vector<void, AnalysisDataServiceObserver &, bool>
Definition at line 23 of file AnalysisDataServiceObserver.cpp.
Function Documentation
export_AnalysisDataServiceObserver()
void export_AnalysisDataServiceObserver ()
Definition at line 44 of file AnalysisDataServiceObserver.cpp.
References Mantid::API::AnalysisDataServiceObserver::observeAdd(), Mantid::API::AnalysisDataServiceObserver::observeAll(), Mantid::API::AnalysisDataServiceObserver::observeClear(), Mantid::API::AnalysisDataServiceObserver::observeDelete(), Mantid::API::AnalysisDataServiceObserver::observeGroup(), Mantid::API::AnalysisDataServiceObserver::observeGroupUpdate(), Mantid::API::AnalysisDataServiceObserver::observeRename(), Mantid::API::AnalysisDataServiceObserver::observeReplace(), and Mantid::API::AnalysisDataServiceObserver::observeUnGroup().