Mantid: Mantid::MDAlgorithms::SlicingAlgorithm Class Reference
Mantid::MDAlgorithms::SlicingAlgorithm Class Reference
Abstract Algorithm class that will be used by: BinMD and SliceMD and shares code for getting a slice from one workspace to another.
#include <SlicingAlgorithm.h>
Public Member Functions
SlicingAlgorithm ()
Constructor.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string name () const override=0
function to return a name of the algorithm, must be overridden in all algorithms
int version () const override=0
function to return a version of the algorithm, must be overridden in all algorithms
const std::string summary () const override=0
function returns a summary message that will be displayed in the default GUI, and in the help.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Static Public Member Functions
static std::string getDimensionChars ()
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Protected Member Functions
void createAlignedTransform ()
Using the parameters, create a coordinate transformation for aligned cuts.
void createGeneralTransform ()
Loads the dimensions and create the coordinate transform, using the inputs.
void createTransform ()
Read the algorithm properties and creates the appropriate transforms for slicing the MDEventWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getGeneralImplicitFunction (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > getImplicitFunctionForChunk (const size_t *const chunkMin, const size_t *const chunkMax)
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
void initSlicingProps ()
Initialise the properties.
void makeAlignedDimensionFromString (const std::string &str)
Generate a MDHistoDimension_sptr from a comma-sep string (for AlignedDim0, etc.) Must be called in order X,Y,Z,T.
void makeBasisVectorFromString (const std::string &str)
Generate the MDHistoDimension and basis vector for a given string from BasisVector0 etc.
void processGeneralTransformProperties ()
Reads the various Properties for the general (non-aligned) case and fills in members on the Algorithm for later use.
~SlicingAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
virtual void init ()=0
Virtual method - must be overridden by concrete algorithm.
virtual void exec ()=0
Virtual method - must be overridden by concrete algorithm.
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Protected Attributes
bool m_axisAligned
Set to true if the cut is aligned with the axes.
std::vector< Mantid::Kernel::VMD > m_bases
Basis vectors of the output dimensions, normalized to unity length.
std::vector< Mantid::Geometry::MDHistoDimension_sptr > m_binDimensions
Bin dimensions to actually use.
std::vector< double > m_binningScaling
Scaling factor to apply for each basis vector (to map to the bins).
std::vector< size_t > m_dimensionToBinFrom
Index of the dimension in the MDEW for the dimension in the output.
Mantid::Kernel::VMD m_inputMinPoint
Coordinates in the INPUT workspace corresponding to the minimum edge in all dimensions.
Mantid::API::IMDWorkspace_sptr m_intermediateWS
Intermediate original workspace.
Mantid::API::IMDWorkspace_sptr m_inWS
Input workspace.
std::vector< double > m_maxExtents
For non-aligned, the maximum coordinate extents in each OUTPUT dimension.
std::vector< double > m_minExtents
For non-aligned, the minimum coordinate extents in each OUTPUT dimension.
bool m_NormalizeBasisVectors
The NormalizeBasisVectors option.
std::vector< int > m_numBins
For non-aligned, the number of bins in each OUTPUT dimension.
Mantid::API::IMDWorkspace_sptr m_originalWS
Original (MDEventWorkspace) that inWS was based on.
size_t m_outD
Number of dimensions in the output (binned) workspace.
std::unique_ptr< API::CoordTransform > m_transform
Coordinate transformation to apply.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformFromIntermediate
Coordinate transformation to save in the output WS, from the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformFromOriginal
Coordinate transformation to save in the output workspace (original->binned)
std::vector< double > m_transformScaling
Scaling factor to apply for each basis vector to transfor to the output dimensions.
std::unique_ptr< DataObjects::CoordTransformAffine > m_transformToIntermediate
Coordinate transformation to save in the intermediate WS.
std::unique_ptr< API::CoordTransform > m_transformToOriginal
Coordinate transformation to save in the output workspace (binned->original)
Mantid::Kernel::VMD m_translation
Translation from the OUTPUT to the INPUT workspace i.e.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Private Member Functions
Mantid::Geometry::MDFrame_uptr createMDFrameForNonAxisAligned (const std::string &units, const Mantid::Kernel::VMD &basisVector) const
Create an MDFrame for the Non-Axis-Aligned case.
Mantid::Geometry::MDFrame_uptr extractMDFrameForNonAxisAligned (std::vector< size_t > indicesWithProjection, const std::string &units) const
Extract the MDFrame.
std::vector< size_t > getIndicesWithProjection (const Mantid::Kernel::VMD &basisVector, const std::vector< Mantid::Kernel::VMD > &oldBasis) const
Get indices which have a projection contribution.
std::vector< Mantid::Kernel::VMD > getOldBasis (size_t dimension) const
bool isProjectingOnFrame (const Mantid::Kernel::VMD &oldVector, const Mantid::Kernel::VMD &basisVector) const
Check if the two vectors are orthogonal or not.
void setTargetUnits (Mantid::Geometry::MDFrame_uptr &frame, const std::string &units) const
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Abstract Algorithm class that will be used by: BinMD and SliceMD and shares code for getting a slice from one workspace to another.
Author
Janik Zikovsky
Date
2011-09-27
Definition at line 33 of file SlicingAlgorithm.h.
Constructor & Destructor Documentation
SlicingAlgorithm()
Mantid::MDAlgorithms::SlicingAlgorithm::SlicingAlgorithm ()
Constructor.
Definition at line 33 of file SlicingAlgorithm.cpp.
~SlicingAlgorithm()
Mantid::MDAlgorithms::SlicingAlgorithm::~SlicingAlgorithm () protected default
Member Function Documentation
createAlignedTransform()
void Mantid::MDAlgorithms::SlicingAlgorithm::createAlignedTransform () protected
Using the parameters, create a coordinate transformation for aligned cuts.
Definition at line 491 of file SlicingAlgorithm.cpp.
References Mantid::Geometry::d, Mantid::API::Algorithm::g_log, getDimensionChars(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Matrix< T >::Invert(), m_bases, m_binDimensions, m_dimensionToBinFrom, m_inWS, m_outD, m_transform, m_transformFromOriginal, m_transformToOriginal, m_translation, makeAlignedDimensionFromString(), Mantid::Kernel::Strings::strip(), tmp, and Mantid::Kernel::Logger::warning().
Referenced by createTransform().
createGeneralTransform()
void Mantid::MDAlgorithms::SlicingAlgorithm::createGeneralTransform () protected
Loads the dimensions and create the coordinate transform, using the inputs.
This is for the general (i.e. non-aligned) case
Definition at line 338 of file SlicingAlgorithm.cpp.
References Mantid::API::CoordTransform::applyVMD(), Mantid::Geometry::d, Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_bases, m_binDimensions, m_binningScaling, m_inputMinPoint, m_inWS, m_originalWS, m_outD, m_transform, m_transformFromOriginal, m_transformScaling, m_transformToOriginal, m_translation, Mantid::Kernel::VMDBase< VMD_t >::makeVectorsOrthogonal(), processGeneralTransformProperties(), and Mantid::DataObjects::CoordTransformAffine::setMatrix().
Referenced by createTransform().
createMDFrameForNonAxisAligned()
Mantid::Geometry::MDFrame_uptr Mantid::MDAlgorithms::SlicingAlgorithm::createMDFrameForNonAxisAligned (const std::string & units, const Mantid::Kernel::VMD & basisVector) const private
Create an MDFrame for the Non-Axis-Aligned case.
Make sure that MDFrames onto which the basis vector projects are not mixed, e.g. no mixing of HKL and GenerFrame
Parameters
units the units
basisVector the basis vector
Returns
the unique pointer
Definition at line 838 of file SlicingAlgorithm.cpp.
References extractMDFrameForNonAxisAligned(), getIndicesWithProjection(), getOldBasis(), and m_inWS.
Referenced by makeBasisVectorFromString().
createTransform()
void Mantid::MDAlgorithms::SlicingAlgorithm::createTransform () protected
Read the algorithm properties and creates the appropriate transforms for slicing the MDEventWorkspace.
NOTE: The m_inWS member must be set first. If the workspace is based on another, e.g. result from BinMD, m_inWS will be modified to be the original workspace and the transformations will be altered to match.
The m_transform, m_transformFromOriginal and m_transformToOriginal transforms will be set.
Definition at line 583 of file SlicingAlgorithm.cpp.
References createAlignedTransform(), createGeneralTransform(), Mantid::API::Algorithm::g_log, Mantid::API::LogManager::getProperty(), Mantid::API::Algorithm::getProperty(), Mantid::API::LogManager::hasProperty(), Mantid::Kernel::Matrix< T >::Invert(), m_axisAligned, m_intermediateWS, m_inWS, m_originalWS, m_transform, m_transformFromIntermediate, m_transformToIntermediate, m_transformToOriginal, Mantid::API::CoordTransform::makeAffineMatrix(), Mantid::API::Algorithm::name(), Mantid::Kernel::Logger::notice(), and Mantid::Kernel::Property::value().
Referenced by Mantid::MDAlgorithms::BinMD::exec(), and Mantid::MDAlgorithms::SliceMD::exec().
extractMDFrameForNonAxisAligned()
Mantid::Geometry::MDFrame_uptr Mantid::MDAlgorithms::SlicingAlgorithm::extractMDFrameForNonAxisAligned (std::vector< size_t > indicesWithProjection, const std::string & units) const private
Extract the MDFrame.
Make sure that all MDFrames are compatible – if not throw
Parameters
indicesWithProjection list of indices of dimensions which have a projection
units the units
Definition at line 896 of file SlicingAlgorithm.cpp.
References Mantid::API::Algorithm::g_log, index, m_inWS, setTargetUnits(), and Mantid::Kernel::Logger::warning().
Referenced by createMDFrameForNonAxisAligned().
getDimensionChars()
static std::string Mantid::MDAlgorithms::SlicingAlgorithm::getDimensionChars () inline static
Returns
a string with the character that identifies each dimension in order (01234)
Definition at line 39 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), Mantid::MDAlgorithms::MDNormDirectSC::init(), Mantid::MDAlgorithms::MDNormSCD::init(), initSlicingProps(), and processGeneralTransformProperties().
getGeneralImplicitFunction()
std::unique_ptr< MDImplicitFunction > Mantid::MDAlgorithms::SlicingAlgorithm::getGeneralImplicitFunction (const size_t *const chunkMin, const size_t *const chunkMax) protected
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
This needs to be in the space of the INPUT MDEventWorkspace.
In the most general case, this function assumes ORTHOGONAL BASIS VECTORS! However, in the case of N dimensions with N or N-1 bases then non-orthogonal basis vectors are allowed.
Parameters
chunkMin :: the minimum index in each dimension to consider "valid" (inclusive). NULL to use the entire range.
chunkMax :: the maximum index in each dimension to consider "valid" (exclusive) NULL to use the entire range.
Returns
MDImplicitFunction created
Definition at line 698 of file SlicingAlgorithm.cpp.
References Mantid::Geometry::d, Mantid::API::Algorithm::g_log, Mantid::Kernel::VMDBase< VMD_t >::getNormalVector(), m_bases, m_binDimensions, m_inWS, m_translation, Mantid::Kernel::VMDBase< TYPE >::size(), std::to_string(), Mantid::Kernel::Logger::warning(), and Mantid::Geometry::x.
Referenced by getImplicitFunctionForChunk().
getImplicitFunctionForChunk()
std::unique_ptr< MDImplicitFunction > Mantid::MDAlgorithms::SlicingAlgorithm::getImplicitFunctionForChunk (const size_t *const chunkMin, const size_t *const chunkMax) protected
Create an implicit function for picking boxes, based on the indexes in the output MDHistoWorkspace.
This needs to be in the space of the INPUT MDEventWorkspace
Parameters
chunkMin :: the minimum index in each dimension to consider "valid" (inclusive). NULL to use the entire range.
chunkMax :: the maximum index in each dimension to consider "valid" (exclusive) NULL to use the entire range.
Returns
MDImplicitFunction created
Definition at line 804 of file SlicingAlgorithm.cpp.
References Mantid::Geometry::d, getGeneralImplicitFunction(), m_axisAligned, m_binDimensions, m_dimensionToBinFrom, m_inWS, and m_outD.
Referenced by Mantid::MDAlgorithms::BinMD::binByIterating(), and Mantid::MDAlgorithms::SliceMD::slice().
getIndicesWithProjection()
std::vector< size_t > Mantid::MDAlgorithms::SlicingAlgorithm::getIndicesWithProjection (const Mantid::Kernel::VMD & basisVector, const std::vector< Mantid::Kernel::VMD > & oldBasis) const private
Get indices which have a projection contribution.
Parameters
basisVector the vector under investigation
oldBasis the old basis vectors
Returns
the indices of vectors onto which the basisVector projects
Definition at line 877 of file SlicingAlgorithm.cpp.
References index, and isProjectingOnFrame().
Referenced by createMDFrameForNonAxisAligned().
getOldBasis()
std::vector< Mantid::Kernel::VMD > Mantid::MDAlgorithms::SlicingAlgorithm::getOldBasis (size_t dimension) const private
Definition at line 850 of file SlicingAlgorithm.cpp.
Referenced by createMDFrameForNonAxisAligned().
initSlicingProps()
void Mantid::MDAlgorithms::SlicingAlgorithm::initSlicingProps () protected
Initialise the properties.
Initialize the algorithm's properties.
Definition at line 40 of file SlicingAlgorithm.cpp.
References Mantid::API::Algorithm::declareProperty(), getDimensionChars(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::Kernel::IPropertyManager::setPropertyGroup(), Mantid::Kernel::IPropertyManager::setPropertySettings(), and Mantid::Kernel::Strings::toString().
Referenced by Mantid::MDAlgorithms::BinMD::init().
isProjectingOnFrame()
bool Mantid::MDAlgorithms::SlicingAlgorithm::isProjectingOnFrame (const Mantid::Kernel::VMD & oldVector, const Mantid::Kernel::VMD & basisVector) const private
Check if the two vectors are orthogonal or not.
Parameters
oldVector the old vector
basisVector the vector under investigation
Returns
true if there is a projection else false
Definition at line 866 of file SlicingAlgorithm.cpp.
References Mantid::Kernel::VMDBase< TYPE >::scalar_prod().
Referenced by getIndicesWithProjection().
makeAlignedDimensionFromString()
void Mantid::MDAlgorithms::SlicingAlgorithm::makeAlignedDimensionFromString (const std::string & str) protected
Generate a MDHistoDimension_sptr from a comma-sep string (for AlignedDim0, etc.) Must be called in order X,Y,Z,T.
Parameters
str :: name,minimum,maximum,number_of_bins
Definition at line 415 of file SlicingAlgorithm.cpp.
References Mantid::Kernel::Strings::convert(), m_binDimensions, m_dimensionToBinFrom, m_inWS, n, Mantid::API::Algorithm::name(), and Mantid::Kernel::Strings::strip().
Referenced by createAlignedTransform().
makeBasisVectorFromString()
void Mantid::MDAlgorithms::SlicingAlgorithm::makeBasisVectorFromString (const std::string & str) protected
Generate the MDHistoDimension and basis vector for a given string from BasisVector0 etc.
If the workspace being binned has an original workspace, then the vector is transformed to THOSE coordinates.
"Format: 'name, units, x,y,z,..'.\n" Adds values to m_bases, m_binDimensions, m_binningScaling and m_transformScaling
Parameters
str :: name,number_of_bins
Definition at line 135 of file SlicingAlgorithm.cpp.
References Mantid::API::CoordTransform::applyVMD(), Mantid::Kernel::Strings::convert(), createMDFrameForNonAxisAligned(), Mantid::Geometry::d, m_bases, m_binDimensions, m_binningScaling, m_inWS, m_maxExtents, m_minExtents, m_NormalizeBasisVectors, m_numBins, m_originalWS, m_transformScaling, n, Mantid::API::Algorithm::name(), Mantid::Kernel::VMDBase< TYPE >::norm(), Mantid::Kernel::VMDBase< TYPE >::normalize(), Mantid::Kernel::Strings::strip(), and Mantid::Kernel::Strings::toString().
Referenced by processGeneralTransformProperties().
processGeneralTransformProperties()
void Mantid::MDAlgorithms::SlicingAlgorithm::processGeneralTransformProperties () protected
Reads the various Properties for the general (non-aligned) case and fills in members on the Algorithm for later use.
Exceptions
if some of the inputs are invalid
Definition at line 261 of file SlicingAlgorithm.cpp.
References Mantid::Geometry::d, getDimensionChars(), Mantid::Kernel::VMDBase< TYPE >::getNumDims(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), m_binDimensions, m_binningScaling, m_inWS, m_maxExtents, m_minExtents, m_NormalizeBasisVectors, m_numBins, m_outD, m_transformScaling, m_translation, makeBasisVectorFromString(), Mantid::Kernel::Strings::strip(), and Mantid::Kernel::Strings::toString().
Referenced by createGeneralTransform().
setTargetUnits()
void Mantid::MDAlgorithms::SlicingAlgorithm::setTargetUnits (Mantid::Geometry::MDFrame_uptr & frame, const std::string & units) const private
Definition at line 924 of file SlicingAlgorithm.cpp.
Referenced by extractMDFrameForNonAxisAligned().
Member Data Documentation
m_axisAligned
bool Mantid::MDAlgorithms::SlicingAlgorithm::m_axisAligned protected
Set to true if the cut is aligned with the axes.
Definition at line 97 of file SlicingAlgorithm.h.
Referenced by createTransform(), and getImplicitFunctionForChunk().
m_bases
std::vector<Mantid::Kernel::VMD> Mantid::MDAlgorithms::SlicingAlgorithm::m_bases protected
Basis vectors of the output dimensions, normalized to unity length.
Definition at line 103 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), createGeneralTransform(), Mantid::MDAlgorithms::BinMD::exec(), getGeneralImplicitFunction(), and makeBasisVectorFromString().
m_binDimensions
std::vector<Mantid::Geometry::MDHistoDimension_sptr> Mantid::MDAlgorithms::SlicingAlgorithm::m_binDimensions protected
Bin dimensions to actually use.
These are NEW dimensions created, or copied (not pointing to) the original workspace.
Definition at line 69 of file SlicingAlgorithm.h.
Referenced by Mantid::MDAlgorithms::BinMD::binByIterating(), createAlignedTransform(), createGeneralTransform(), Mantid::MDAlgorithms::BinMD::exec(), getGeneralImplicitFunction(), getImplicitFunctionForChunk(), makeAlignedDimensionFromString(), makeBasisVectorFromString(), processGeneralTransformProperties(), and Mantid::MDAlgorithms::SliceMD::slice().
m_binningScaling
std::vector<double> Mantid::MDAlgorithms::SlicingAlgorithm::m_binningScaling protected
Scaling factor to apply for each basis vector (to map to the bins).
i.e.. MULTIPLY the distance in the INPUT workspace by this = an index into the bin
Definition at line 108 of file SlicingAlgorithm.h.
Referenced by createGeneralTransform(), makeBasisVectorFromString(), and processGeneralTransformProperties().
m_dimensionToBinFrom
std::vector<size_t> Mantid::MDAlgorithms::SlicingAlgorithm::m_dimensionToBinFrom protected
Index of the dimension in the MDEW for the dimension in the output.
Only for axis-aligned slices
Definition at line 73 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), getImplicitFunctionForChunk(), and makeAlignedDimensionFromString().
m_inputMinPoint
Mantid::Kernel::VMD Mantid::MDAlgorithms::SlicingAlgorithm::m_inputMinPoint protected
Coordinates in the INPUT workspace corresponding to the minimum edge in all dimensions.
Definition at line 122 of file SlicingAlgorithm.h.
Referenced by createGeneralTransform().
m_intermediateWS
Mantid::API::IMDWorkspace_sptr Mantid::MDAlgorithms::SlicingAlgorithm::m_intermediateWS protected
Intermediate original workspace.
Output -> intermediate (MDHisto) -> original (MDEvent)
Definition at line 89 of file SlicingAlgorithm.h.
Referenced by createTransform(), and Mantid::MDAlgorithms::BinMD::exec().
m_inWS
Mantid::API::IMDWorkspace_sptr Mantid::MDAlgorithms::SlicingAlgorithm::m_inWS protected
Input workspace.
Definition at line 61 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), createGeneralTransform(), createMDFrameForNonAxisAligned(), createTransform(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::SliceMD::exec(), extractMDFrameForNonAxisAligned(), getGeneralImplicitFunction(), getImplicitFunctionForChunk(), makeAlignedDimensionFromString(), makeBasisVectorFromString(), and processGeneralTransformProperties().
m_maxExtents
std::vector<double> Mantid::MDAlgorithms::SlicingAlgorithm::m_maxExtents protected
For non-aligned, the maximum coordinate extents in each OUTPUT dimension.
Definition at line 128 of file SlicingAlgorithm.h.
Referenced by makeBasisVectorFromString(), and processGeneralTransformProperties().
m_minExtents
std::vector<double> Mantid::MDAlgorithms::SlicingAlgorithm::m_minExtents protected
For non-aligned, the minimum coordinate extents in each OUTPUT dimension.
Definition at line 125 of file SlicingAlgorithm.h.
Referenced by makeBasisVectorFromString(), and processGeneralTransformProperties().
m_NormalizeBasisVectors
bool Mantid::MDAlgorithms::SlicingAlgorithm::m_NormalizeBasisVectors protected
The NormalizeBasisVectors option.
Definition at line 134 of file SlicingAlgorithm.h.
Referenced by makeBasisVectorFromString(), and processGeneralTransformProperties().
m_numBins
std::vector<int> Mantid::MDAlgorithms::SlicingAlgorithm::m_numBins protected
For non-aligned, the number of bins in each OUTPUT dimension.
Definition at line 131 of file SlicingAlgorithm.h.
Referenced by makeBasisVectorFromString(), and processGeneralTransformProperties().
m_originalWS
Mantid::API::IMDWorkspace_sptr Mantid::MDAlgorithms::SlicingAlgorithm::m_originalWS protected
Original (MDEventWorkspace) that inWS was based on.
Used during basis vector constructor
Definition at line 65 of file SlicingAlgorithm.h.
Referenced by createGeneralTransform(), createTransform(), and makeBasisVectorFromString().
m_outD
size_t Mantid::MDAlgorithms::SlicingAlgorithm::m_outD protected
Number of dimensions in the output (binned) workspace.
Definition at line 100 of file SlicingAlgorithm.h.
Referenced by Mantid::MDAlgorithms::BinMD::binByIterating(), Mantid::MDAlgorithms::BinMD::binMDBox(), createAlignedTransform(), createGeneralTransform(), Mantid::MDAlgorithms::SliceMD::doExec(), getImplicitFunctionForChunk(), and processGeneralTransformProperties().
m_transform
std::unique_ptr<API::CoordTransform> Mantid::MDAlgorithms::SlicingAlgorithm::m_transform protected
Coordinate transformation to apply.
This transformation contains the scaling that makes the output coordinate = bin indexes in the output MDHistoWorkspace.
Definition at line 78 of file SlicingAlgorithm.h.
Referenced by Mantid::MDAlgorithms::BinMD::binMDBox(), createAlignedTransform(), createGeneralTransform(), and createTransform().
m_transformFromIntermediate
std::unique_ptr<DataObjects::CoordTransformAffine> Mantid::MDAlgorithms::SlicingAlgorithm::m_transformFromIntermediate protected
Coordinate transformation to save in the output WS, from the intermediate WS.
Definition at line 92 of file SlicingAlgorithm.h.
Referenced by createTransform(), and Mantid::MDAlgorithms::BinMD::exec().
m_transformFromOriginal
std::unique_ptr<API::CoordTransform> Mantid::MDAlgorithms::SlicingAlgorithm::m_transformFromOriginal protected
Coordinate transformation to save in the output workspace (original->binned)
Definition at line 82 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), createGeneralTransform(), Mantid::MDAlgorithms::BinMD::exec(), and Mantid::MDAlgorithms::SliceMD::slice().
m_transformScaling
std::vector<double> Mantid::MDAlgorithms::SlicingAlgorithm::m_transformScaling protected
Scaling factor to apply for each basis vector to transfor to the output dimensions.
i.e.. MULTIPLY the distance in the INPUT workspace by this = a distance in the OUTPUT dimension
Definition at line 114 of file SlicingAlgorithm.h.
Referenced by createGeneralTransform(), makeBasisVectorFromString(), and processGeneralTransformProperties().
m_transformToIntermediate
std::unique_ptr<DataObjects::CoordTransformAffine> Mantid::MDAlgorithms::SlicingAlgorithm::m_transformToIntermediate protected
Coordinate transformation to save in the intermediate WS.
Definition at line 94 of file SlicingAlgorithm.h.
Referenced by createTransform(), and Mantid::MDAlgorithms::BinMD::exec().
m_transformToOriginal
std::unique_ptr<API::CoordTransform> Mantid::MDAlgorithms::SlicingAlgorithm::m_transformToOriginal protected
Coordinate transformation to save in the output workspace (binned->original)
Definition at line 85 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), createGeneralTransform(), createTransform(), and Mantid::MDAlgorithms::BinMD::exec().
m_translation
Mantid::Kernel::VMD Mantid::MDAlgorithms::SlicingAlgorithm::m_translation protected
Translation from the OUTPUT to the INPUT workspace i.e.
this position in the input workspace = 0,0,0 in the output.
Definition at line 118 of file SlicingAlgorithm.h.
Referenced by createAlignedTransform(), createGeneralTransform(), Mantid::MDAlgorithms::BinMD::exec(), getGeneralImplicitFunction(), and processGeneralTransformProperties().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/SlicingAlgorithm.h
Framework/MDAlgorithms/src/SlicingAlgorithm.cpp