Mantid: Mantid::API::TimeAtSampleStrategyElastic Class Reference
Mantid::API::TimeAtSampleStrategyElastic Class Reference
TimeAtSampleStrategyElastic : Time at sample stragegy for elastic scattering.
#include <TimeAtSampleStrategyElastic.h>
Public Member Functions
Correction calculate (const size_t &workspace_index) const override
Calculate correction.
TimeAtSampleStrategyElastic (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Public Member Functions inherited from Mantid::API::TimeAtSampleStrategy
virtual ~TimeAtSampleStrategy ()=default
Private Attributes
const Kernel::V3D m_beamDir
const double m_L1s
const API::SpectrumInfo & m_spectrumInfo
Detailed Description
TimeAtSampleStrategyElastic : Time at sample stragegy for elastic scattering.
Definition at line 21 of file TimeAtSampleStrategyElastic.h.
Constructor & Destructor Documentation
TimeAtSampleStrategyElastic()
Mantid::API::TimeAtSampleStrategyElastic::TimeAtSampleStrategyElastic (std::shared_ptr< const Mantid::API::MatrixWorkspace > ws)
Constructor.
Definition at line 27 of file TimeAtSampleStrategyElastic.cpp.
Member Function Documentation
calculate()
Correction Mantid::API::TimeAtSampleStrategyElastic::calculate (const size_t & workspace_index) const override virtual
Calculate correction.
Parameters
workspace_index
Returns
Correction
Implements Mantid::API::TimeAtSampleStrategy.
Definition at line 36 of file TimeAtSampleStrategyElastic.cpp.
References Mantid::API::SpectrumInfo::isMonitor(), Mantid::API::SpectrumInfo::l2(), m_beamDir, m_L1s, m_spectrumInfo, Mantid::API::SpectrumInfo::position(), Mantid::Kernel::V3D::scalar_prod(), and Mantid::API::SpectrumInfo::sourcePosition().
Referenced by Mantid::Algorithms::RebinByTimeAtSample::doHistogramming().
Member Data Documentation
m_beamDir
const Kernel::V3D Mantid::API::TimeAtSampleStrategyElastic::m_beamDir private
Definition at line 29 of file TimeAtSampleStrategyElastic.h.
Referenced by calculate().
m_L1s
const double Mantid::API::TimeAtSampleStrategyElastic::m_L1s private
Definition at line 28 of file TimeAtSampleStrategyElastic.h.
Referenced by calculate().
m_spectrumInfo
const API::SpectrumInfo& Mantid::API::TimeAtSampleStrategyElastic::m_spectrumInfo private
Definition at line 27 of file TimeAtSampleStrategyElastic.h.
Referenced by calculate().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/TimeAtSampleStrategyElastic.h
Framework/API/src/TimeAtSampleStrategyElastic.cpp