Mantid: Mantid::Nexus::UniqueID< D > Class Template Reference
Mantid::Nexus::UniqueID< D > Class Template Reference
A wrapper class for managing HDF5 object handles (hid_t).
#include <UniqueID.h>
Public Member Functions
hid_t get () const
bool isValid () const
operator hid_t () const
bool operator< (int const id) const
bool operator<= (int const id) const
UniqueID< D > & operator= (hid_t const id)
Assign a HDF5 object ID to be managed.
UniqueID< D > & operator= (UniqueID< D > &&uid)
Pass the HDF5 object ID from an existing UniqueID to another UniqueID.
bool operator== (int const id) const
hid_t release ()
Release hold on the managed ID; it will not be closed by this UniqueID.
void reset (hid_t const id=INVALID_ID)
UniqueID ()
UniqueID (hid_t const id)
UniqueID (UniqueID< D > &&uid) noexcept
~UniqueID ()
Static Public Attributes
static hid_t constexpr INVALID_ID {-1}
Private Member Functions
void close ()
UniqueID & operator= (UniqueID< D > const &)=delete
UniqueID (UniqueID< D > const &uid)=delete
Private Attributes
hid_t m_id
Detailed Description
template<herr_t(*)(hid_t) D>
class Mantid::Nexus::UniqueID< D >
A wrapper class for managing HDF5 object handles (hid_t).
The UniqueID class is designed to manage the lifecycle of HDF5 object handles (hid_t), ensuring that the handle is properly closed when the UniqueID object is destroyed. This helps prevent resource leaks and ensures proper cleanup of HDF5 resources.
Definition at line 23 of file UniqueID.h.
Constructor & Destructor Documentation
UniqueID() [1/4]
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::UniqueID (UniqueID< D > const & uid) private delete
UniqueID() [2/4]
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::UniqueID (UniqueID< D > && uid) inline noexcept
Definition at line 31 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::INVALID_ID.
UniqueID() [3/4]
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::UniqueID () inline
Definition at line 42 of file UniqueID.h.
UniqueID() [4/4]
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::UniqueID (hid_t const id) inline
Definition at line 43 of file UniqueID.h.
~UniqueID()
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::~UniqueID () inline
Definition at line 44 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::close().
Member Function Documentation
close()
template<herr_t(*)(hid_t) deleter> void Mantid::Nexus::UniqueID< deleter >::close () private
Definition at line 58 of file UniqueID.h.
Referenced by Mantid::Nexus::UniqueID< D >::~UniqueID().
get()
template<herr_t(*)(hid_t) D> hid_t Mantid::Nexus::UniqueID< D >::get () const inline
Definition at line 38 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::m_id.
isValid()
template<herr_t(*)(hid_t) D> bool Mantid::Nexus::UniqueID< D >::isValid () const
Definition at line 49 of file UniqueID.h.
References H5Iis_valid().
operator hid_t()
template<herr_t(*)(hid_t) D> Mantid::Nexus::UniqueID< D >::operator hid_t () const inline
Definition at line 37 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::m_id.
operator<()
template<herr_t(*)(hid_t) D> bool Mantid::Nexus::UniqueID< D >::operator< (int const id) const inline
Definition at line 36 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::m_id.
operator<=()
template<herr_t(*)(hid_t) D> bool Mantid::Nexus::UniqueID< D >::operator<= (int const id) const inline
Definition at line 35 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::m_id.
operator=() [1/3]
template<herr_t(*)(hid_t) D> UniqueID< D > & Mantid::Nexus::UniqueID< D >::operator= (hid_t const id)
Assign a HDF5 object ID to be managed.
Parameters
id : the ID to be managed
Definition at line 82 of file UniqueID.h.
operator=() [2/3]
template<herr_t(*)(hid_t) D> UniqueID< D > & Mantid::Nexus::UniqueID< D >::operator= (UniqueID< D > && uid)
Pass the HDF5 object ID from an existing UniqueID to another UniqueID.
Parameters
uid : the UniqueID previously managing the ID; it will lose ownership of the ID.
Definition at line 89 of file UniqueID.h.
operator=() [3/3]
template<herr_t(*)(hid_t) D> UniqueID & Mantid::Nexus::UniqueID< D >::operator= (UniqueID< D > const &) private delete
operator==()
template<herr_t(*)(hid_t) D> bool Mantid::Nexus::UniqueID< D >::operator== (int const id) const inline
Definition at line 34 of file UniqueID.h.
References Mantid::Nexus::UniqueID< D >::m_id.
release()
template<herr_t(*)(hid_t) D> hid_t Mantid::Nexus::UniqueID< D >::release ()
Release hold on the managed ID; it will not be closed by this UniqueID.
Returns
the managed ID
Definition at line 67 of file UniqueID.h.
References tmp.
reset()
template<herr_t(*)(hid_t) D> void Mantid::Nexus::UniqueID< D >::reset (hid_t const id = INVALID_ID)
Definition at line 73 of file UniqueID.h.
Referenced by Mantid::Nexus::H5Util::copyGroup(), and Mantid::Nexus::H5Util::isHdf5().
Member Data Documentation
INVALID_ID
template<herr_t(*)(hid_t) D> hid_t constexpr Mantid::Nexus::UniqueID< D >::INVALID_ID {-1} static constexpr
Definition at line 46 of file UniqueID.h.
Referenced by Mantid::Nexus::UniqueID< D >::UniqueID().
m_id
template<herr_t(*)(hid_t) D> hid_t Mantid::Nexus::UniqueID< D >::m_id private
Definition at line 25 of file UniqueID.h.
Referenced by Mantid::Nexus::UniqueID< D >::get(), Mantid::Nexus::UniqueID< D >::operator hid_t(), Mantid::Nexus::UniqueID< D >::operator<(), Mantid::Nexus::UniqueID< D >::operator<=(), and Mantid::Nexus::UniqueID< D >::operator==().
The documentation for this class was generated from the following file:
Framework/Nexus/inc/MantidNexus/UniqueID.h