Mantid: Mantid::DataHandling::LoadILLReflectometry Class Reference
Mantid::DataHandling::LoadILLReflectometry Class Reference
LoadILLReflectometry : Loads an ILL reflectometry Nexus data file.
#include <LoadILLReflectometry.h>
Public Member Functions
const std::string category () const override
Algorithm's category for search and find.
int confidence (Kernel::NexusDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
double doubleFromRun (const std::string &entryName) const
LoadILLReflectometry::doubleFromRun Returns a sample log a single double.
LoadILLReflectometry ()=default
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::NexusDescriptor >
virtual int confidence (Kernel::NexusDescriptor &descriptor) const=0
Returns a confidence value that this algorithm can load a file.
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Types
enum class Supported { D17 , FIGARO }
ID tags for supported instruments.
Private Member Functions
void addSampleLogs ()
double collimationAngle () const
Return the incident neutron deflection angle.
void convertTofToWavelength ()
Call child algorithm ConvertUnits for conversion from TOF to wavelength Note that DAN calibration is done in preprocess, since it needs information also from the direct beam so converting to wavelength in the loader will not be accurate.
double detectorRotation ()
Compute the detector rotation angle around origin.
void exec () override
Execute the algorithm.
std::vector< double > getXValues ()
Determine x values (unit time-of-flight)
void init () override
Initialize the algorithm's properties.
void initNames (const NeXus::NXEntry &entry)
Init names of sample logs based on instrument specific NeXus file entries.
void initPixelWidth ()
Initialize m_pixelWidth from the IDF as the step of rectangular detector.
void initWorkspace (const std::vector< std::vector< int > > &monitorsData)
Creates the workspace and initialises member variables with the corresponding values.
void loadData (const NeXus::NXEntry &entry, const std::vector< std::vector< int > > &monitorsData, const std::vector< double > &xVals)
Load data from nexus file.
void loadDataDetails (const NeXus::NXEntry &entry)
Load Data details (number of tubes, channels, etc)
void loadInstrument ()
Run the Child Algorithm LoadInstrument.
std::vector< std::vector< int > > loadMonitors (const NeXus::NXEntry &entry)
Load monitor data.
void loadNexusEntriesIntoProperties ()
Use the LoadHelper utility to load most of the nexus entries into workspace sample log properties.
std::vector< int > loadSingleMonitor (const NeXus::NXEntry &entry, const std::string &monitor_data)
Load single monitor.
double offsetAngle (const double peakCentre, const double detectorCentre, const double detectorDistance) const
Calculate the offset angle between detector center and peak.
double peakOffsetAngle ()
void placeDetector ()
Update detector position according to data file.
void placeSlits ()
Update the slit positions.
void placeSource ()
Update source position.
double reflectometryPeak ()
Gaussian fit to determine peak position if no user position given.
void sampleAngle (const NeXus::NXEntry &entry)
Sets the sample angle (i.e.
double sampleDetectorDistance () const
Return the sample to detector distance for the current instrument.
void sampleHorizontalOffset ()
Return the horizontal offset along the z axis.
double sourceSampleDistance () const
Return the source to sample distance for the current instrument.
Private Attributes
size_t m_acqMode {1}
double m_channelWidth {0.0}
std::string m_chopper1Name
std::string m_chopper2Name
double m_detectorDistance {0.0}
Supported m_instrument {Supported::D17}
API::MatrixWorkspace_sptr m_localWorkspace
size_t m_numberOfChannels {0}
(1: TOF (default), 0: monochromatic)
size_t m_numberOfHistograms {0}
std::string m_offsetFrom
double m_pixelWidth {0.0}
double m_sampleAngle {0.0}
std::string m_sampleAngleName
double m_sampleZOffset {0.0}
double m_sourceDistance {0.0}
Mantid::Types::Core::DateAndTime m_startTime
double m_tofDelay {0.0}
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::ParallelAlgorithm
Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const override
Get correct execution mode based on input storage modes for an MPI run.
~ParallelAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadILLReflectometry : Loads an ILL reflectometry Nexus data file.
Definition at line 21 of file LoadILLReflectometry.h.
Member Enumeration Documentation
Supported
enum class Mantid::DataHandling::LoadILLReflectometry::Supported strong private
ID tags for supported instruments.
Enumerator
D17
FIGARO
Definition at line 42 of file LoadILLReflectometry.h.
Constructor & Destructor Documentation
LoadILLReflectometry()
Mantid::DataHandling::LoadILLReflectometry::LoadILLReflectometry () default
Member Function Documentation
addSampleLogs()
void Mantid::DataHandling::LoadILLReflectometry::addSampleLogs () private
category()
const std::string Mantid::DataHandling::LoadILLReflectometry::category () const inline override virtual
Algorithm's category for search and find.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 32 of file LoadILLReflectometry.h.
collimationAngle()
double Mantid::DataHandling::LoadILLReflectometry::collimationAngle () const private
Return the incident neutron deflection angle.
Definition at line 771 of file LoadILLReflectometry.cpp.
References doubleFromRun(), FIGARO, m_instrument, and m_sampleAngleName.
confidence()
int Mantid::DataHandling::LoadILLReflectometry::confidence (Kernel::NexusDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::NexusDescriptor >.
Definition at line 158 of file LoadILLReflectometry.cpp.
convertTofToWavelength()
void Mantid::DataHandling::LoadILLReflectometry::convertTofToWavelength () private
Call child algorithm ConvertUnits for conversion from TOF to wavelength Note that DAN calibration is done in preprocess, since it needs information also from the direct beam so converting to wavelength in the loader will not be accurate.
Definition at line 282 of file LoadILLReflectometry.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getPropertyValue(), m_acqMode, and m_localWorkspace.
Referenced by exec().
detectorRotation()
double Mantid::DataHandling::LoadILLReflectometry::detectorRotation () private
Compute the detector rotation angle around origin.
Returns
a rotation angle
Definition at line 645 of file LoadILLReflectometry.cpp.
References Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::Algorithm::isDefault(), m_detectorDistance, m_localWorkspace, m_sampleAngle, offsetAngle(), reflectometryPeak(), and Mantid::Kernel::Logger::warning().
Referenced by placeDetector().
doubleFromRun()
double Mantid::DataHandling::LoadILLReflectometry::doubleFromRun (const std::string & entryName) const
LoadILLReflectometry::doubleFromRun Returns a sample log a single double.
Parameters
entryName : the name of the log
Returns
the value as double
Exceptions
runtime_error : if the log does not exist
Definition at line 348 of file LoadILLReflectometry.cpp.
References m_localWorkspace.
Referenced by collimationAngle(), getXValues(), placeSlits(), sampleDetectorDistance(), sampleHorizontalOffset(), and sourceSampleDistance().
exec()
void Mantid::DataHandling::LoadILLReflectometry::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 201 of file LoadILLReflectometry.cpp.
References Mantid::NeXus::NXClass::close(), convertTofToWavelength(), Mantid::API::Algorithm::getPropertyValue(), getXValues(), initNames(), initPixelWidth(), initWorkspace(), loadData(), loadDataDetails(), loadInstrument(), loadMonitors(), loadNexusEntriesIntoProperties(), m_localWorkspace, Mantid::NeXus::NXRoot::openFirstEntry(), placeDetector(), placeSlits(), placeSource(), sampleAngle(), sampleHorizontalOffset(), and Mantid::Kernel::IPropertyManager::setProperty().
getXValues()
std::vector< double > Mantid::DataHandling::LoadILLReflectometry::getXValues () private
Determine x values (unit time-of-flight)
Returns
:: vector holding the x values
Definition at line 390 of file LoadILLReflectometry.cpp.
References D17, Mantid::Kernel::Logger::debug(), doubleFromRun(), Mantid::Kernel::Logger::error(), FIGARO, Mantid::API::g_log, m_acqMode, m_channelWidth, m_chopper1Name, m_chopper2Name, m_instrument, m_localWorkspace, m_numberOfChannels, m_offsetFrom, m_tofDelay, and Mantid::Kernel::Logger::warning().
Referenced by exec().
init()
void Mantid::DataHandling::LoadILLReflectometry::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 173 of file LoadILLReflectometry.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
initNames()
void Mantid::DataHandling::LoadILLReflectometry::initNames (const NeXus::NXEntry & entry) private
Init names of sample logs based on instrument specific NeXus file entries.
Parameters
entry :: the NeXus file entry
Definition at line 239 of file LoadILLReflectometry.cpp.
References D17, Mantid::Kernel::Logger::debug(), FIGARO, Mantid::DataHandling::LoadHelper::findInstrumentNexusPath(), Mantid::API::g_log, Mantid::NeXus::NXClass::getString(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_acqMode, m_chopper1Name, m_chopper2Name, m_instrument, m_offsetFrom, m_sampleAngleName, Mantid::NeXus::NXClass::openNXInt(), and std::to_string().
Referenced by exec().
initPixelWidth()
void Mantid::DataHandling::LoadILLReflectometry::initPixelWidth () private
Initialize m_pixelWidth from the IDF as the step of rectangular detector.
Definition at line 692 of file LoadILLReflectometry.cpp.
References D17, m_instrument, m_localWorkspace, and m_pixelWidth.
Referenced by exec().
initWorkspace()
void Mantid::DataHandling::LoadILLReflectometry::initWorkspace (const std::vector< std::vector< int > > & monitorsData) private
Creates the workspace and initialises member variables with the corresponding values.
Parameters
monitorsData :: Monitors data already loaded
Definition at line 299 of file LoadILLReflectometry.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::Kernel::SingletonHolder< T >::Instance(), m_acqMode, m_localWorkspace, m_numberOfChannels, m_numberOfHistograms, and m_startTime.
Referenced by exec().
loadData()
void Mantid::DataHandling::LoadILLReflectometry::loadData (const NeXus::NXEntry & entry, const std::vector< std::vector< int > > & monitorsData, const std::vector< double > & xVals) private
Load data from nexus file.
Parameters
entry :: The Nexus file entry
monitorsData :: Monitors data already loaded
xVals :: X values
Definition at line 504 of file LoadILLReflectometry.cpp.
References Mantid::NeXus::NXDataSetTyped< T >::load(), m_localWorkspace, m_numberOfChannels, m_numberOfHistograms, Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), PARALLEL_FOR_IF, Mantid::API::Algorithm::progress(), and Mantid::Kernel::threadSafe().
Referenced by exec().
loadDataDetails()
void Mantid::DataHandling::LoadILLReflectometry::loadDataDetails (const NeXus::NXEntry & entry) private
Load Data details (number of tubes, channels, etc)
Parameters
entry First entry of nexus file
Definition at line 323 of file LoadILLReflectometry.cpp.
References Mantid::DataHandling::LoadHelper::dateTimeInIsoFormat(), Mantid::NeXus::NXClass::getString(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_acqMode, m_channelWidth, m_numberOfChannels, m_numberOfHistograms, m_startTime, m_tofDelay, Mantid::NeXus::NXClass::openNXFloat(), and Mantid::NeXus::NXClass::openNXInt().
Referenced by exec().
loadInstrument()
void Mantid::DataHandling::LoadILLReflectometry::loadInstrument () private
Run the Child Algorithm LoadInstrument.
Definition at line 224 of file LoadILLReflectometry.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), D17, m_instrument, and m_localWorkspace.
Referenced by exec().
loadMonitors()
std::vector< std::vector< int > > Mantid::DataHandling::LoadILLReflectometry::loadMonitors (const NeXus::NXEntry & entry) private
Load monitor data.
Parameters
entry :: The Nexus entry
Returns
:: A std::vector of vectors of monitors containing monitor values
Definition at line 377 of file LoadILLReflectometry.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, and loadSingleMonitor().
Referenced by exec().
loadNexusEntriesIntoProperties()
void Mantid::DataHandling::LoadILLReflectometry::loadNexusEntriesIntoProperties () private
Use the LoadHelper utility to load most of the nexus entries into workspace sample log properties.
Definition at line 536 of file LoadILLReflectometry.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), FIGARO, Mantid::API::Algorithm::getPropertyValue(), m_instrument, and m_localWorkspace.
Referenced by exec().
loadSingleMonitor()
std::vector< int > Mantid::DataHandling::LoadILLReflectometry::loadSingleMonitor (const NeXus::NXEntry & entry, const std::string & monitor_data) private
Load single monitor.
Parameters
entry :: The Nexus entry
monitor_data :: A std::string containing the Nexus path to the monitor data
Returns
monitor :: A std::vector containing monitor values
Definition at line 364 of file LoadILLReflectometry.cpp.
References Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::NeXus::NXData::openIntData(), Mantid::NeXus::NXEntry::openNXData(), and Mantid::NeXus::NXDataSetTyped< T >::size().
Referenced by loadMonitors().
name()
const std::string Mantid::DataHandling::LoadILLReflectometry::name () const inline override virtual
Algorithm's name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 27 of file LoadILLReflectometry.h.
offsetAngle()
double Mantid::DataHandling::LoadILLReflectometry::offsetAngle (const double peakCentre, const double detectorCentre, const double detectorDistance) const private
Calculate the offset angle between detector center and peak.
Parameters
peakCentre peak centre in pixels.
detectorCentre detector centre in pixels.
detectorDistance detector-sample distance in meters.
Returns
the offset angle.
Definition at line 781 of file LoadILLReflectometry.cpp.
References FIGARO, m_instrument, and m_pixelWidth.
Referenced by detectorRotation().
peakOffsetAngle()
double Mantid::DataHandling::LoadILLReflectometry::peakOffsetAngle () private
placeDetector()
void Mantid::DataHandling::LoadILLReflectometry::placeDetector () private
Update detector position according to data file.
Definition at line 707 of file LoadILLReflectometry.cpp.
References D17, detectorRotation(), m_detectorDistance, m_instrument, m_localWorkspace, Mantid::DataHandling::LoadHelper::moveComponent(), Mantid::DataHandling::LoadHelper::rotateComponent(), rotation, and sampleDetectorDistance().
Referenced by exec().
placeSlits()
void Mantid::DataHandling::LoadILLReflectometry::placeSlits () private
Update the slit positions.
Definition at line 721 of file LoadILLReflectometry.cpp.
References doubleFromRun(), FIGARO, m_instrument, m_localWorkspace, m_sampleAngleName, m_sampleZOffset, and Mantid::DataHandling::LoadHelper::moveComponent().
Referenced by exec().
placeSource()
void Mantid::DataHandling::LoadILLReflectometry::placeSource () private
Update source position.
Definition at line 763 of file LoadILLReflectometry.cpp.
References m_localWorkspace, m_sourceDistance, Mantid::DataHandling::LoadHelper::moveComponent(), and sourceSampleDistance().
Referenced by exec().
reflectometryPeak()
double Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak () private
Gaussian fit to determine peak position if no user position given.
Returns
:: detector position of the peak: Gaussian fit and position of the maximum (serves as start value for the optimization)
Definition at line 559 of file LoadILLReflectometry.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), height, Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::API::Algorithm::isDefault(), m_detectorDistance, m_localWorkspace, m_sourceDistance, Mantid::Kernel::Logger::warning(), and Mantid::Geometry::x.
Referenced by detectorRotation().
sampleAngle()
void Mantid::DataHandling::LoadILLReflectometry::sampleAngle (const NeXus::NXEntry & entry) private
Sets the sample angle (i.e.
bragg angle) [degrees] Used when measurement type is reflected beam (otherwise must be zero) Note that DAN calibration needs information also from the corresponding direct beam, hence it cannot be done in the loader, but it is done in preprocessing algorithm. However loader should still support loading reflected beams standalone, hence sample angle is the only option if BraggAngle is not manually specified.
Definition at line 671 of file LoadILLReflectometry.cpp.
References D17, Mantid::NeXus::NXClass::isValid(), Mantid::NeXus::NXDataSetTyped< T >::load(), m_instrument, m_sampleAngle, and Mantid::NeXus::NXClass::openNXFloat().
Referenced by exec().
sampleDetectorDistance()
double Mantid::DataHandling::LoadILLReflectometry::sampleDetectorDistance () const private
Return the sample to detector distance for the current instrument.
Returns
the distance in meters
Definition at line 793 of file LoadILLReflectometry.cpp.
References D17, doubleFromRun(), and m_instrument.
Referenced by placeDetector().
sampleHorizontalOffset()
void Mantid::DataHandling::LoadILLReflectometry::sampleHorizontalOffset () private
Return the horizontal offset along the z axis.
Definition at line 804 of file LoadILLReflectometry.cpp.
References doubleFromRun(), FIGARO, m_instrument, m_localWorkspace, and m_sampleZOffset.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadILLReflectometry::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 30 of file LoadILLReflectometry.h.
sourceSampleDistance()
double Mantid::DataHandling::LoadILLReflectometry::sourceSampleDistance () const private
Return the source to sample distance for the current instrument.
Returns
the source to sample distance in meters
Definition at line 826 of file LoadILLReflectometry.cpp.
References D17, doubleFromRun(), m_instrument, m_localWorkspace, m_sampleAngleName, and m_sampleZOffset.
Referenced by placeSource().
summary()
const std::string Mantid::DataHandling::LoadILLReflectometry::summary () const inline override virtual
Algorithm's summary.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 34 of file LoadILLReflectometry.h.
version()
int Mantid::DataHandling::LoadILLReflectometry::version () const inline override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 29 of file LoadILLReflectometry.h.
Member Data Documentation
m_acqMode
size_t Mantid::DataHandling::LoadILLReflectometry::m_acqMode {1} private
Definition at line 71 of file LoadILLReflectometry.h.
Referenced by convertTofToWavelength(), getXValues(), initNames(), initWorkspace(), and loadDataDetails().
m_channelWidth
double Mantid::DataHandling::LoadILLReflectometry::m_channelWidth {0.0} private
Definition at line 79 of file LoadILLReflectometry.h.
Referenced by getXValues(), and loadDataDetails().
m_chopper1Name
std::string Mantid::DataHandling::LoadILLReflectometry::m_chopper1Name private
Definition at line 76 of file LoadILLReflectometry.h.
Referenced by getXValues(), and initNames().
m_chopper2Name
std::string Mantid::DataHandling::LoadILLReflectometry::m_chopper2Name private
Definition at line 77 of file LoadILLReflectometry.h.
Referenced by getXValues(), and initNames().
m_detectorDistance
double Mantid::DataHandling::LoadILLReflectometry::m_detectorDistance {0.0} private
Definition at line 80 of file LoadILLReflectometry.h.
Referenced by detectorRotation(), placeDetector(), and reflectometryPeak().
m_instrument
Supported Mantid::DataHandling::LoadILLReflectometry::m_instrument {Supported::D17} private
Definition at line 70 of file LoadILLReflectometry.h.
Referenced by collimationAngle(), getXValues(), initNames(), initPixelWidth(), loadInstrument(), loadNexusEntriesIntoProperties(), offsetAngle(), placeDetector(), placeSlits(), sampleAngle(), sampleDetectorDistance(), sampleHorizontalOffset(), and sourceSampleDistance().
m_localWorkspace
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLReflectometry::m_localWorkspace private
Definition at line 86 of file LoadILLReflectometry.h.
Referenced by convertTofToWavelength(), detectorRotation(), doubleFromRun(), exec(), getXValues(), initPixelWidth(), initWorkspace(), loadData(), loadInstrument(), loadNexusEntriesIntoProperties(), placeDetector(), placeSlits(), placeSource(), reflectometryPeak(), sampleHorizontalOffset(), and sourceSampleDistance().
m_numberOfChannels
size_t Mantid::DataHandling::LoadILLReflectometry::m_numberOfChannels {0} private
(1: TOF (default), 0: monochromatic)
Definition at line 72 of file LoadILLReflectometry.h.
Referenced by getXValues(), initWorkspace(), loadData(), and loadDataDetails().
m_numberOfHistograms
size_t Mantid::DataHandling::LoadILLReflectometry::m_numberOfHistograms {0} private
Definition at line 73 of file LoadILLReflectometry.h.
Referenced by initWorkspace(), loadData(), and loadDataDetails().
m_offsetFrom
std::string Mantid::DataHandling::LoadILLReflectometry::m_offsetFrom private
Definition at line 75 of file LoadILLReflectometry.h.
Referenced by getXValues(), and initNames().
m_pixelWidth
double Mantid::DataHandling::LoadILLReflectometry::m_pixelWidth {0.0} private
Definition at line 81 of file LoadILLReflectometry.h.
Referenced by initPixelWidth(), and offsetAngle().
m_sampleAngle
double Mantid::DataHandling::LoadILLReflectometry::m_sampleAngle {0.0} private
Definition at line 84 of file LoadILLReflectometry.h.
Referenced by detectorRotation(), and sampleAngle().
m_sampleAngleName
std::string Mantid::DataHandling::LoadILLReflectometry::m_sampleAngleName private
Definition at line 74 of file LoadILLReflectometry.h.
Referenced by collimationAngle(), initNames(), placeSlits(), and sourceSampleDistance().
m_sampleZOffset
double Mantid::DataHandling::LoadILLReflectometry::m_sampleZOffset {0.0} private
Definition at line 82 of file LoadILLReflectometry.h.
Referenced by placeSlits(), sampleHorizontalOffset(), and sourceSampleDistance().
m_sourceDistance
double Mantid::DataHandling::LoadILLReflectometry::m_sourceDistance {0.0} private
Definition at line 83 of file LoadILLReflectometry.h.
Referenced by placeSource(), and reflectometryPeak().
m_startTime
Mantid::Types::Core::DateAndTime Mantid::DataHandling::LoadILLReflectometry::m_startTime private
Definition at line 85 of file LoadILLReflectometry.h.
Referenced by initWorkspace(), and loadDataDetails().
m_tofDelay
double Mantid::DataHandling::LoadILLReflectometry::m_tofDelay {0.0} private
Definition at line 78 of file LoadILLReflectometry.h.
Referenced by getXValues(), and loadDataDetails().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadILLReflectometry.h
Framework/DataHandling/src/LoadILLReflectometry.cpp