Mantid: Mantid::Kernel::uniform_int_distribution< _IntType >::param_type Class Reference
Mantid::Kernel::uniform_int_distribution< _IntType >::param_type Class Reference
#include <uniform_int_distribution.h>
Public Types
using distribution_type = uniform_int_distribution
Public Member Functions
result_type a () const
result_type b () const
param_type (result_type __a=0, result_type __b=std::numeric_limits< result_type >::max())
Private Attributes
result_type __a_
result_type __b_
Friends
bool operator!= (const param_type &__x, const param_type &__y)
bool operator== (const param_type &__x, const param_type &__y)
Detailed Description
template<class _IntType = int>
class Mantid::Kernel::uniform_int_distribution< _IntType >::param_type
Definition at line 212 of file uniform_int_distribution.h.
Member Typedef Documentation
distribution_type
template<class _IntType = int> using Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::distribution_type = uniform_int_distribution
Definition at line 217 of file uniform_int_distribution.h.
Constructor & Destructor Documentation
param_type()
template<class _IntType = int> Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::param_type (result_type __a = 0, result_type __b = std::numeric_limits<result_type>::max()) inline explicit
Definition at line 219 of file uniform_int_distribution.h.
Member Function Documentation
a()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::a () const inline
Definition at line 222 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::__a_.
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::a(), and Mantid::Kernel::uniform_int_distribution< _IntType >::operator()().
b()
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::b () const inline
Definition at line 223 of file uniform_int_distribution.h.
References Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::__b_.
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::b(), and Mantid::Kernel::uniform_int_distribution< _IntType >::operator()().
Friends And Related Function Documentation
operator!=
template<class _IntType = int> bool operator!= (const param_type & __x, const param_type & __y) friend
Definition at line 228 of file uniform_int_distribution.h.
operator==
template<class _IntType = int> bool operator== (const param_type & __x, const param_type & __y) friend
Definition at line 225 of file uniform_int_distribution.h.
Member Data Documentation
__a_
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::__a_ private
Definition at line 213 of file uniform_int_distribution.h.
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::a().
__b_
template<class _IntType = int> result_type Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::__b_ private
Definition at line 214 of file uniform_int_distribution.h.
Referenced by Mantid::Kernel::uniform_int_distribution< _IntType >::param_type::b().
The documentation for this class was generated from the following file:
Framework/Kernel/inc/MantidKernel/uniform_int_distribution.h