Mantid: ICat4::ns1__studyInvestigation Class Reference
ICat4::ns1__studyInvestigation Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__studyInvestigation ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__investigation * investigation
ns1__study * study
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1859 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__studyInvestigation()
ICat4::ns1__studyInvestigation::ns1__studyInvestigation () inline
Definition at line 1871 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__studyInvestigation::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13500 of file ICat4C.cpp.
References investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and study.
Referenced by ICat4::soap_in_ns1__studyInvestigation(), ICat4::soap_new_req_ns1__studyInvestigation(), and ICat4::soap_new_set_ns1__studyInvestigation().
soap_get()
void * ICat4::ns1__studyInvestigation::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13646 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__studyInvestigation().
soap_in()
void * ICat4::ns1__studyInvestigation::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13545 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__studyInvestigation().
Referenced by ICat4::soap_in_ns1__studyInvestigation().
soap_out()
int ICat4::ns1__studyInvestigation::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13518 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__studyInvestigation().
Referenced by soap_put().
soap_put()
int ICat4::ns1__studyInvestigation::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13639 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__studyInvestigation.
soap_serialize()
void ICat4::ns1__studyInvestigation::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13508 of file ICat4C.cpp.
References investigation, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__investigation(), ICat4::soap_serialize_PointerTons1__study(), and study.
Referenced by ICat4::soap_serialize_PointerTons1__study().
soap_type()
int ICat4::ns1__studyInvestigation::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1864 of file ICat4Stub.h.
Member Data Documentation
investigation
ns1__investigation* ICat4::ns1__studyInvestigation::investigation
Definition at line 1861 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
study
ns1__study* ICat4::ns1__studyInvestigation::study
Definition at line 1862 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp