Mantid: MantidQt::API::MantidHelpInterface Class Reference
MantidQt::API::MantidHelpInterface Class Reference
#include <MantidHelpInterface.h>
Public Slots
virtual void shutdown ()
Perform any clean up on main window shutdown.
Public Member Functions
MantidHelpInterface ()
Default constructor.
virtual void showAlgorithm (const QString &name, const int version=-1)
virtual void showAlgorithm (const std::string &name=std::string(), const int version=-1)
virtual void showConcept (const QString &name)
virtual void showConcept (const std::string &name)
virtual void showCustomInterface (const QString &name, const QString &area=QString(), const QString &section=QString())
virtual void showCustomInterface (const std::string &name, const std::string &area=std::string(), const std::string &section=std::string())
virtual void showFitFunction (const QString &name)
virtual void showFitFunction (const std::string &name=std::string())
virtual void showPage (const QString &url)
virtual void showPage (const QUrl &url)
virtual void showPage (const std::string &url=std::string())
virtual void showWikiPage (const QString &page)
virtual void showWikiPage (const std::string &page=std::string())
~MantidHelpInterface () override
Default destructor.
Detailed Description
Definition at line 22 of file MantidHelpInterface.h.
Constructor & Destructor Documentation
MantidHelpInterface()
MantidHelpInterface::MantidHelpInterface () default
Default constructor.
~MantidHelpInterface()
MantidHelpInterface::~MantidHelpInterface () override default
Default destructor.
Member Function Documentation
showAlgorithm() [1/2]
void MantidHelpInterface::showAlgorithm (const QString & name, const int version = -1) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 37 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showAlgorithm() [2/2]
void MantidHelpInterface::showAlgorithm (const std::string & name = std::string(), const int version = -1) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 32 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
Referenced by MantidQt::API::HelpWindow::showAlgorithm().
showConcept() [1/2]
void MantidHelpInterface::showConcept (const QString & name) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 30 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showConcept() [2/2]
void MantidHelpInterface::showConcept (const std::string & name) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 28 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
Referenced by MantidQt::API::HelpWindow::showConcept().
showCustomInterface() [1/2]
void MantidHelpInterface::showCustomInterface (const QString & name, const QString & area = QString(), const QString & section = QString()) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 53 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showCustomInterface() [2/2]
void MantidHelpInterface::showCustomInterface (const std::string & name, const std::string & area = std::string(), const std::string & section = std::string()) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 46 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
Referenced by MantidQt::API::HelpWindow::showCustomInterface().
showFitFunction() [1/2]
void MantidHelpInterface::showFitFunction (const QString & name) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 44 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showFitFunction() [2/2]
void MantidHelpInterface::showFitFunction (const std::string & name = std::string()) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 42 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
Referenced by MantidQt::API::HelpWindow::showFitFunction().
showPage() [1/3]
void MantidHelpInterface::showPage (const QString & url) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 20 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showPage() [2/3]
void MantidHelpInterface::showPage (const QUrl & url) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 22 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showPage() [3/3]
void MantidHelpInterface::showPage (const std::string & url = std::string()) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 18 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
Referenced by MantidQt::API::HelpWindow::showPage().
showWikiPage() [1/2]
void MantidHelpInterface::showWikiPage (const QString & page) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 26 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
showWikiPage() [2/2]
void MantidHelpInterface::showWikiPage (const std::string & page = std::string()) virtual
Reimplemented in MantidQt::MantidWidgets::MantidHelpWindow.
Definition at line 24 of file MantidHelpInterface.cpp.
References UNUSED_ARG.
shutdown
void MantidHelpInterface::shutdown () virtual slot
Perform any clean up on main window shutdown.
Definition at line 59 of file MantidHelpInterface.cpp.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidHelpInterface.h
qt/widgets/common/src/MantidHelpInterface.cpp