Mantid: Framework/PythonInterface/mantid/api/src/Exports/MDGeometry.cpp File Reference
MDGeometry.cpp File Reference
#include "MantidAPI/MDGeometry.h"
#include "MantidAPI/Workspace.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include "MantidPythonInterface/core/Policies/VectorToNumpy.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/list.hpp>
#include <boost/python/return_value_policy.hpp>
Functions
void export_MDGeometry ()
Function Documentation
export_MDGeometry()
void export_MDGeometry ()
Definition at line 41 of file MDGeometry.cpp.
References Mantid::API::MDGeometry::clearOriginalWorkspaces(), Mantid::API::MDGeometry::estimateResolution(), Mantid::API::MDGeometry::getBasisVector(), Mantid::API::MDGeometry::getDimension(), Mantid::API::MDGeometry::getDimensionIndexById(), Mantid::API::MDGeometry::getDimensionIndexByName(), Mantid::API::MDGeometry::getDimensionWithId(), Mantid::API::MDGeometry::getGeometryXML(), Mantid::API::MDGeometry::getNumberTransformsFromOriginal(), Mantid::API::MDGeometry::getNumberTransformsToOriginal(), Mantid::API::MDGeometry::getNumDims(), Mantid::API::MDGeometry::getOrigin(), Mantid::API::MDGeometry::getOriginalWorkspace(), Mantid::API::MDGeometry::getTDimension(), Mantid::API::MDGeometry::getXDimension(), Mantid::API::MDGeometry::getYDimension(), Mantid::API::MDGeometry::getZDimension(), Mantid::API::MDGeometry::hasOriginalWorkspace(), and Mantid::API::MDGeometry::numOriginalWorkspaces().