Mantid: Framework/PythonInterface/mantid/api/src/Exports/AlgorithmObserver.cpp File Reference
AlgorithmObserver.cpp File Reference
#include "MantidPythonInterface/api/Algorithms/AlgorithmObserverAdapter.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/register_ptr_to_python.hpp>
Functions
void export_algorithm_observer ()
void observeError (AlgorithmObserver &self, const boost::python::object &alg)
void observeFinish (AlgorithmObserver &self, const boost::python::object &alg)
void observeProgress (AlgorithmObserver &self, const boost::python::object &alg)
void stopObserving (AlgorithmObserver &self, const boost::python::object &alg)
Function Documentation
export_algorithm_observer()
void export_algorithm_observer ()
Definition at line 39 of file AlgorithmObserver.cpp.
References observeError(), observeFinish(), observeProgress(), Mantid::API::AlgorithmObserver::observeStarting(), and stopObserving().
observeError()
void observeError (AlgorithmObserver & self, const boost::python::object & alg)
Definition at line 22 of file AlgorithmObserver.cpp.
References Mantid::API::AlgorithmObserver::observeError().
Referenced by export_algorithm_observer().
observeFinish()
void observeFinish (AlgorithmObserver & self, const boost::python::object & alg)
Definition at line 17 of file AlgorithmObserver.cpp.
References Mantid::API::AlgorithmObserver::observeFinish().
Referenced by export_algorithm_observer(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::runFit().
observeProgress()
void observeProgress (AlgorithmObserver & self, const boost::python::object & alg)
Definition at line 27 of file AlgorithmObserver.cpp.
References Mantid::API::AlgorithmObserver::observeProgress().
Referenced by export_algorithm_observer().
stopObserving()
void stopObserving (AlgorithmObserver & self, const boost::python::object & alg)
Definition at line 32 of file AlgorithmObserver.cpp.
References Mantid::API::AlgorithmObserver::stopObserving().
Referenced by export_algorithm_observer().