Mantid: Mantid::Kernel::Units::SpinEchoLength Class Reference
Mantid::Kernel::Units::SpinEchoLength Class Reference
SpinEchoLength in nm.
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
SpinEchoLength ()
Constructor.
const std::string unitID () const override
"SpinEchoLength"
Public Member Functions inherited from Mantid::Kernel::Units::Wavelength
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
double conversionTOFMin () const override
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"Wavelength"
Wavelength ()
Constructor.
Public Member Functions inherited from Mantid::Kernel::Unit
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit. TOF is in microseconds.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight. TOF is in microseconds.
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > const &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual ~Unit ()=default
Virtual destructor.
Private Attributes
double efixed
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Units::Wavelength
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
Protected Attributes inherited from Mantid::Kernel::Units::Wavelength
bool do_sfpFrom
Apply the sfpFrom value.
double efixed
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
double sfpFrom
Extra correction factor in from conversion.
double sfpTo
Extra correction factor in to conversion.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
SpinEchoLength in nm.
Definition at line 528 of file Unit.h.
Constructor & Destructor Documentation
SpinEchoLength()
Mantid::Kernel::Units::SpinEchoLength::SpinEchoLength ()
Constructor.
Definition at line 1238 of file Unit.cpp.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::SpinEchoLength::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Implements Mantid::Kernel::Unit.
Definition at line 531 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::SpinEchoLength::clone () const override virtual
Returns
a cloned instance of the other
Implements Mantid::Kernel::Unit.
Definition at line 1276 of file Unit.cpp.
References SpinEchoLength().
conversionTOFMax()
double Mantid::Kernel::Units::SpinEchoLength::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Definition at line 1261 of file Unit.cpp.
References efixed.
conversionTOFMin()
double Mantid::Kernel::Units::SpinEchoLength::conversionTOFMin () const override virtual
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Definition at line 1257 of file Unit.cpp.
References Mantid::Kernel::Units::Wavelength::conversionTOFMin(), and efixed.
init()
void Mantid::Kernel::Units::SpinEchoLength::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Implements Mantid::Kernel::Unit.
Definition at line 1240 of file Unit.cpp.
References Mantid::Kernel::efixed, efixed, Mantid::Kernel::Unit::emode, Mantid::Kernel::Units::Wavelength::init(), and Mantid::Kernel::Unit::m_params.
label()
const UnitLabel Mantid::Kernel::Units::SpinEchoLength::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Implements Mantid::Kernel::Unit.
Definition at line 1236 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::Nanometre.
singleFromTOF()
double Mantid::Kernel::Units::SpinEchoLength::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Implements Mantid::Kernel::Unit.
Definition at line 1270 of file Unit.cpp.
References efixed, Mantid::Kernel::Units::Wavelength::singleFromTOF(), and Mantid::Geometry::x.
singleToTOF()
double Mantid::Kernel::Units::SpinEchoLength::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Implements Mantid::Kernel::Unit.
Definition at line 1251 of file Unit.cpp.
References efixed, Mantid::Kernel::Units::Wavelength::singleToTOF(), and Mantid::Geometry::x.
unitID()
const std::string Mantid::Kernel::Units::SpinEchoLength::unitID () const override virtual
"SpinEchoLength"
Implements Mantid::Kernel::Unit.
Member Data Documentation
efixed
double Mantid::Kernel::Units::SpinEchoLength::efixed private
Definition at line 545 of file Unit.h.
Referenced by conversionTOFMax(), conversionTOFMin(), init(), singleFromTOF(), and singleToTOF().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp