Mantid: MantidQt::MantidWidgets::Batch::BuildSubtreeItems Class Reference
MantidQt::MantidWidgets::Batch::BuildSubtreeItems Class Reference
#include <BuildSubtreeItems.h>
Public Types
using SubtreeConstIterator = typename Subtree::const_iterator
Public Member Functions
SubtreeConstIterator buildRecursively (int index, RowLocation const &parent, SubtreeConstIterator current, SubtreeConstIterator end)
BuildSubtreeItems (QtStandardItemTreeModelAdapter &adaptedModel, RowLocationAdapter const &rowLocationAdapter)
QModelIndexForMainModel modelIndexAt (RowLocation const &parent) const
void operator() (RowLocation const &parentOfSubtreeRoot, int index, Subtree const &subtree)
Private Attributes
QtStandardItemTreeModelAdapter & m_adaptedMainModel
RowLocationAdapter m_rowLocations
Detailed Description
Definition at line 23 of file BuildSubtreeItems.h.
Member Typedef Documentation
SubtreeConstIterator
using MantidQt::MantidWidgets::Batch::BuildSubtreeItems::SubtreeConstIterator = typename Subtree::const_iterator
Definition at line 25 of file BuildSubtreeItems.h.
Constructor & Destructor Documentation
BuildSubtreeItems()
MantidQt::MantidWidgets::Batch::BuildSubtreeItems::BuildSubtreeItems (QtStandardItemTreeModelAdapter & adaptedModel, RowLocationAdapter const & rowLocationAdapter)
Definition at line 11 of file BuildSubtreeItems.cpp.
Member Function Documentation
buildRecursively()
auto MantidQt::MantidWidgets::Batch::BuildSubtreeItems::buildRecursively (int index, RowLocation const & parent, SubtreeConstIterator current, SubtreeConstIterator end)
Definition at line 15 of file BuildSubtreeItems.cpp.
Referenced by operator()().
modelIndexAt()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::BuildSubtreeItems::modelIndexAt (RowLocation const & parent) const
Definition at line 48 of file BuildSubtreeItems.cpp.
References MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt(), and m_rowLocations.
operator()()
void MantidQt::MantidWidgets::Batch::BuildSubtreeItems::operator() (RowLocation const & parentOfSubtreeRoot, int index, Subtree const & subtree)
Definition at line 41 of file BuildSubtreeItems.cpp.
References buildRecursively().
Member Data Documentation
m_adaptedMainModel
QtStandardItemTreeModelAdapter& MantidQt::MantidWidgets::Batch::BuildSubtreeItems::m_adaptedMainModel private
Definition at line 35 of file BuildSubtreeItems.h.
m_rowLocations
RowLocationAdapter MantidQt::MantidWidgets::Batch::BuildSubtreeItems::m_rowLocations private
Definition at line 36 of file BuildSubtreeItems.h.
Referenced by modelIndexAt().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/BuildSubtreeItems.h
qt/widgets/common/src/Batch/BuildSubtreeItems.cpp