Mantid: MantidQt::API::ManageUserDirectories Class Reference
MantidQt::API::ManageUserDirectories Class Reference
Access and update the user directory settings within the Mantid config service.
#include <ManageUserDirectories.h>
Public Member Functions
QPushButton * cancelButton () const
Testing accessors.
void enableSaveToFile (bool enabled)
Control if the config service changes are persisted to the user file.
ManageUserDirectories (QWidget *parent=nullptr)
Constructor.
Static Public Member Functions
static ManageUserDirectories * openManageUserDirectories ()
Show the default dialog or raise the existing one if it exists.
Private Types
using BaseClass = QDialog
Private Slots
void addDirectory ()
Handle the add directory button to take the text from a text box based on the signal sender to the correct list.
void browseToDirectory ()
Browse to find a new directory.
void cancelClicked ()
Close the dialog without saving the configuration.
void confirmClicked ()
Persist the properties to the config store and close the dialog.
void helpClicked ()
Show the help for ManageUserDirectories.
void moveDown ()
Lower an item down in the list based on the sender of the signal.
void moveToTop ()
Raise an item to the top in the list based on the sender of the signal.
void moveUp ()
Raise an item up in the list based on the sender of the signal.
void remDir ()
Remove a directory from the list based on the sender.
void selectSaveDir ()
Find an existing directory to be used for the save directory path.
Private Member Functions
virtual void initLayout ()
Create the UI layout, fill the widgets and connect the relevant signals.
QListWidget * listWidget (QObject *object)
Return the QListWidget related to the given sender.
void loadProperties ()
Load config properties into the form widgets.
void moveItem (bool toTop, int offset)
Move an item in the list based on the sender of the signal and a specified direction.
void saveProperties ()
Save the current contents of the widgets back to the main config.
Private Attributes
bool m_saveToFile
Ui::ManageUserDirectories m_uiForm
Detailed Description
Access and update the user directory settings within the Mantid config service.
Definition at line 22 of file ManageUserDirectories.h.
Member Typedef Documentation
BaseClass
using MantidQt::API::ManageUserDirectories::BaseClass = QDialog private
Definition at line 23 of file ManageUserDirectories.h.
Constructor & Destructor Documentation
ManageUserDirectories()
ManageUserDirectories::ManageUserDirectories (QWidget * parent = nullptr)
Constructor.
Parameters
parent A parent QWidget for the dialog
Definition at line 65 of file ManageUserDirectories.cpp.
References initLayout(), and m_uiForm.
Member Function Documentation
addDirectory
void ManageUserDirectories::addDirectory () private slot
Handle the add directory button to take the text from a text box based on the signal sender to the correct list.
Definition at line 234 of file ManageUserDirectories.cpp.
References listWidget(), and m_uiForm.
Referenced by initLayout().
browseToDirectory
void ManageUserDirectories::browseToDirectory () private slot
Browse to find a new directory.
The start directory is the last directory accessed by the application. The directory is added to the list based on the object sender
Definition at line 252 of file ManageUserDirectories.cpp.
References listWidget().
Referenced by initLayout().
cancelButton()
QPushButton * MantidQt::API::ManageUserDirectories::cancelButton () const inline
Testing accessors.
Definition at line 36 of file ManageUserDirectories.h.
cancelClicked
void ManageUserDirectories::cancelClicked () private slot
Close the dialog without saving the configuration.
Definition at line 222 of file ManageUserDirectories.cpp.
Referenced by initLayout().
confirmClicked
void ManageUserDirectories::confirmClicked () private slot
Persist the properties to the config store and close the dialog.
Definition at line 225 of file ManageUserDirectories.cpp.
References saveProperties().
Referenced by initLayout().
enableSaveToFile()
void ManageUserDirectories::enableSaveToFile (bool enabled)
Control if the config service changes are persisted to the user file.
Parameters
enabled If true the config is persisted to the user file after updating the service otherwise only the in-memory store is affected.
Definition at line 77 of file ManageUserDirectories.cpp.
References m_saveToFile.
helpClicked
void ManageUserDirectories::helpClicked () private slot
Show the help for ManageUserDirectories.
Definition at line 219 of file ManageUserDirectories.cpp.
References MantidQt::API::HelpWindow::showCustomInterface().
Referenced by initLayout().
initLayout()
void ManageUserDirectories::initLayout () private virtual
Create the UI layout, fill the widgets and connect the relevant signals.
Definition at line 82 of file ManageUserDirectories.cpp.
References addDirectory(), browseToDirectory(), cancelClicked(), confirmClicked(), helpClicked(), loadProperties(), m_uiForm, moveDown(), moveToTop(), moveUp(), remDir(), and selectSaveDir().
Referenced by ManageUserDirectories().
listWidget()
QListWidget * ManageUserDirectories::listWidget (QObject * sender) private
Return the QListWidget related to the given sender.
Parameters
sender A pointer to the QObject that caused this slot to be called
Returns
QListWidget if sender is a known button else nullptr
Definition at line 205 of file ManageUserDirectories.cpp.
References m_uiForm.
Referenced by addDirectory(), browseToDirectory(), moveItem(), and remDir().
loadProperties()
void ManageUserDirectories::loadProperties () private
Load config properties into the form widgets.
Definition at line 112 of file ManageUserDirectories.cpp.
References m_uiForm.
Referenced by initLayout().
moveDown
void ManageUserDirectories::moveDown () private slot
Lower an item down in the list based on the sender of the signal.
Definition at line 301 of file ManageUserDirectories.cpp.
References moveItem().
Referenced by initLayout().
moveItem()
void ManageUserDirectories::moveItem (bool toTop, int offset) private
Move an item in the list based on the sender of the signal and a specified direction.
Definition at line 274 of file ManageUserDirectories.cpp.
References count, index, and listWidget().
Referenced by moveDown(), moveToTop(), and moveUp().
moveToTop
void ManageUserDirectories::moveToTop () private slot
Raise an item to the top in the list based on the sender of the signal.
Definition at line 295 of file ManageUserDirectories.cpp.
References moveItem().
Referenced by initLayout().
moveUp
void ManageUserDirectories::moveUp () private slot
Raise an item up in the list based on the sender of the signal.
Definition at line 298 of file ManageUserDirectories.cpp.
References moveItem().
Referenced by initLayout().
openManageUserDirectories()
ManageUserDirectories * ManageUserDirectories::openManageUserDirectories () static
Show the default dialog or raise the existing one if it exists.
It wraps the Mantid::Kernel::ConfigService by default.
Definition at line 51 of file ManageUserDirectories.cpp.
remDir
void ManageUserDirectories::remDir () private slot
Remove a directory from the list based on the sender.
Definition at line 266 of file ManageUserDirectories.cpp.
References listWidget().
Referenced by initLayout().
saveProperties()
void ManageUserDirectories::saveProperties () private
Save the current contents of the widgets back to the main config.
Definition at line 151 of file ManageUserDirectories.cpp.
References m_saveToFile, and m_uiForm.
Referenced by confirmClicked().
selectSaveDir
void ManageUserDirectories::selectSaveDir () private slot
Find an existing directory to be used for the save directory path.
Definition at line 304 of file ManageUserDirectories.cpp.
References m_uiForm.
Referenced by initLayout().
Member Data Documentation
m_saveToFile
bool MantidQt::API::ManageUserDirectories::m_saveToFile private
Definition at line 59 of file ManageUserDirectories.h.
Referenced by enableSaveToFile(), and saveProperties().
m_uiForm
Ui::ManageUserDirectories MantidQt::API::ManageUserDirectories::m_uiForm private
Definition at line 58 of file ManageUserDirectories.h.
Referenced by addDirectory(), initLayout(), listWidget(), loadProperties(), ManageUserDirectories(), saveProperties(), and selectSaveDir().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ManageUserDirectories.h
qt/widgets/common/src/ManageUserDirectories.cpp