Mantid: Framework/PythonInterface/mantid/api/src/Exports/WorkspaceGroup.cpp File Reference
WorkspaceGroup.cpp File Reference
#include "MantidAPI/WorkspaceGroup.h"
#include "MantidAPI/AnalysisDataService.h"
#include "MantidAPI/WorkspaceGroup_fwd.h"
#include "MantidPythonInterface/api/RegisterWorkspacePtrToPython.h"
#include "MantidPythonInterface/core/DataServiceExporter.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/ReleaseGlobalInterpreterLock.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_non_const_reference.hpp>
#include <boost/python/iterator.hpp>
#include <boost/python/make_constructor.hpp>
#include <boost/python/return_value_policy.hpp>
Functions
void addItem (WorkspaceGroup &self, const std::string &name)
void addWorkspace (WorkspaceGroup &self, const boost::python::object &pyobj)
void export_WorkspaceGroup ()
PyObject * getItem (WorkspaceGroup &self, const int &index)
std::vector< Workspace_sptr >::iterator group_begin (WorkspaceGroup &self)
Returns an iterator pointing to the first element in the group.
std::vector< Workspace_sptr >::iterator group_end (WorkspaceGroup &self)
Returns an iterator pointing to the past-the-end element in the group.
Workspace_sptr makeWorkspaceGroup ()
Constructor function for WorkspaceGroup.
void removeItem (WorkspaceGroup &self, const std::string &name)
Function Documentation
addItem()
void addItem (WorkspaceGroup & self, const std::string & name)
Definition at line 65 of file WorkspaceGroup.cpp.
References Mantid::API::WorkspaceGroup::add().
Referenced by export_WorkspaceGroup(), MantidQt::MantidWidgets::InstrumentSelector::fillWithInstrumentsFromFacility(), MantidQt::MantidWidgets::WorkspaceSelector::handleAddEvent(), MantidQt::MantidWidgets::WorkspaceSelector::handleClearEvent(), MantidQt::MantidWidgets::WorkspaceSelector::handleRenameEvent(), MantidQt::MantidWidgets::WorkspaceSelector::handleReplaceEvent(), MantidQt::MantidWidgets::WorkspaceSelector::refresh(), and MantidQt::MantidWidgets::FindAlgComboBox::update().
addWorkspace()
void addWorkspace (WorkspaceGroup & self, const boost::python::object & pyobj)
Definition at line 70 of file WorkspaceGroup.cpp.
References Mantid::API::WorkspaceGroup::addWorkspace().
Referenced by export_WorkspaceGroup().
export_WorkspaceGroup()
void export_WorkspaceGroup ()
Definition at line 89 of file WorkspaceGroup.cpp.
References addItem(), addWorkspace(), Mantid::API::WorkspaceGroup::contains(), getItem(), Mantid::API::WorkspaceGroup::getNames(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), group_begin(), group_end(), Mantid::API::WorkspaceGroup::isMultiperiod(), makeWorkspaceGroup(), removeItem(), Mantid::API::WorkspaceGroup::size(), and Mantid::API::WorkspaceGroup::sortByName().
getItem()
PyObject * getItem (WorkspaceGroup & self, const int & index)
Definition at line 80 of file WorkspaceGroup.cpp.
References Mantid::API::WorkspaceGroup::getItem(), index, Mantid::API::WorkspaceGroup::size(), and Mantid::API::WorkspaceGroup::throwIndexOutOfRangeError().
Referenced by export_VMD(), export_WorkspaceGroup(), and item_struct< T >::getItem().
group_begin()
std::vector< Workspace_sptr >::iterator group_begin (WorkspaceGroup & self)
Returns an iterator pointing to the first element in the group.
Parameters
self :: handle to the workspace group.
Returns
A non-const iterator pointing at start of workspace group, for use in python.
Definition at line 48 of file WorkspaceGroup.cpp.
Referenced by export_WorkspaceGroup().
group_end()
std::vector< Workspace_sptr >::iterator group_end (WorkspaceGroup & self)
Returns an iterator pointing to the past-the-end element in the group.
Parameters
self :: handle to the workspace group.
Returns
A non-const iterator pointing at end of workspace group, for use in python.
Definition at line 57 of file WorkspaceGroup.cpp.
References Mantid::API::WorkspaceGroup::end().
Referenced by export_WorkspaceGroup().
makeWorkspaceGroup()
Workspace_sptr makeWorkspaceGroup ()
Constructor function for WorkspaceGroup.
Definition at line 60 of file WorkspaceGroup.cpp.
Referenced by export_WorkspaceGroup().
removeItem()
void removeItem (WorkspaceGroup & self, const std::string & name)
Definition at line 75 of file WorkspaceGroup.cpp.
References Mantid::API::WorkspaceGroup::remove().
Referenced by export_WorkspaceGroup(), MantidQt::MantidWidgets::InstrumentSelector::filterByTechniquesAtFacility(), MantidQt::MantidWidgets::WorkspaceSelector::handleRemEvent(), MantidQt::MantidWidgets::WorkspaceSelector::handleRenameEvent(), and MantidQt::MantidWidgets::WorkspaceSelector::handleReplaceEvent().