Mantid: MuonGroupingXMLHelper Namespace Reference
MuonGroupingXMLHelper Namespace Reference
Functions
ScopedFileHelper::ScopedFile createGroupingXMLSingleGroup (const std::string &groupName, const std::string &group)
Simplest possible grouping file, with only a single group.
ScopedFileHelper::ScopedFile createGroupingXMLSinglePair (const std::string &pairName, const std::string &groupName)
Create an XML with two simple groups and a pair made from them.
ScopedFileHelper::ScopedFile createXMLwithPairsAndGroups (const int &nGroups=1, const int &nDetectorsPerGroup=1)
Create an XML file with grouping/pairing information.
DLLExport std::string groupingToXML (const Mantid::API::Grouping &grouping)
Create an XML file (as a string) containing muon grouping information.
Function Documentation
createGroupingXMLSingleGroup()
ScopedFileHelper::ScopedFile MuonGroupingXMLHelper::createGroupingXMLSingleGroup (const std::string & groupName, const std::string & group)
Simplest possible grouping file, with only a single group.
Parameters
groupName :: Name of the group.
group :: Detector grouping string (e.g. "1-4,5,6-10").
Returns
ScopedFile object.
Definition at line 32 of file MuonGroupingXMLHelper.cpp.
References group.
createGroupingXMLSinglePair()
ScopedFileHelper::ScopedFile MuonGroupingXMLHelper::createGroupingXMLSinglePair (const std::string & pairName, const std::string & groupName)
Create an XML with two simple groups and a pair made from them.
Grouping file with two groups (group1 and group2), combined into one pair.
groupName applies only to the pairing so that we can test a failure case.
Parameters
pairName :: Name of the pair.
groupName :: Override the name of the second group of the pair, used to test a possible failure case.
Returns
ScopedFile object.
Definition at line 52 of file MuonGroupingXMLHelper.cpp.
createXMLwithPairsAndGroups()
ScopedFileHelper::ScopedFile MuonGroupingXMLHelper::createXMLwithPairsAndGroups (const int & nGroups = 1, const int & nDetectorsPerGroup = 1)
Create an XML file with grouping/pairing information.
With nGroups = 3 and nDetectorPerGroup = 5 the grouping would be {"1-5","6-10","11-15"}.
With nGroups = 3 and nDetectorPerGroup = 5 the grouping would be {"1-5","6-10","11-15"}.
Parameters
nGroups :: The number of groups to produce
nDetectorsPerGroup :: The number of detector IDs per group
Returns
ScopedFile.
Definition at line 88 of file MuonGroupingXMLHelper.cpp.
References group, groupingToXML(), Mantid::API::Grouping::groupNames, Mantid::API::Grouping::groups, Mantid::API::Grouping::pairAlphas, Mantid::API::Grouping::pairNames, Mantid::API::Grouping::pairs, and std::to_string().
groupingToXML()
std::string MuonGroupingXMLHelper::groupingToXML (const Mantid::API::Grouping & grouping)
Create an XML file (as a string) containing muon grouping information.
Parameters
grouping :: Struct with grouping information
Definition at line 124 of file MuonGroupingXMLHelper.cpp.
References Mantid::API::Grouping::defaultName, Mantid::API::Grouping::description, Mantid::API::Grouping::groupNames, Mantid::API::Grouping::groups, Mantid::API::Grouping::pairAlphas, Mantid::API::Grouping::pairNames, and Mantid::API::Grouping::pairs.
Referenced by createXMLwithPairsAndGroups().