Mantid: Mantid::Kernel::Units::DeltaE_inWavenumber Class Reference
Mantid::Kernel::Units::DeltaE_inWavenumber Class Reference
Energy transfer in units of wavenumber (cm^-1)
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
DeltaE_inWavenumber ()
Constructor.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
const std::string unitID () const override
"DeltaE_inWavenumber"
Public Member Functions inherited from Mantid::Kernel::Units::DeltaE
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
DeltaE ()
Constructor.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"DeltaE"
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Units::DeltaE
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes inherited from Mantid::Kernel::Units::DeltaE
double efixed
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
double t_other
Energy mode dependent factor in to conversion.
double t_otherFrom
Energy mode dependent factor in from conversion.
double unitScaling
Apply unit scaling to energy value.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Energy transfer in units of wavenumber (cm^-1)
Definition at line 506 of file Unit.h.
Constructor & Destructor Documentation
DeltaE_inWavenumber()
Mantid::Kernel::Units::DeltaE_inWavenumber::DeltaE_inWavenumber ()
Constructor.
Definition at line 1060 of file Unit.cpp.
References Mantid::Kernel::Unit::addConversion(), and Mantid::PhysicalConstants::meVtoWavenumber.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::DeltaE_inWavenumber::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 509 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::DeltaE_inWavenumber::clone () const override virtual
Returns
a cloned instance of the other
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 1058 of file Unit.cpp.
References DeltaE_inWavenumber().
conversionTOFMax()
double Mantid::Kernel::Units::DeltaE_inWavenumber::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 1066 of file Unit.cpp.
References Mantid::Kernel::Units::DeltaE::conversionTOFMax().
conversionTOFMin()
double Mantid::Kernel::Units::DeltaE_inWavenumber::conversionTOFMin () const override virtual
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 1064 of file Unit.cpp.
References Mantid::Kernel::Units::DeltaE::conversionTOFMin().
init()
void Mantid::Kernel::Units::DeltaE_inWavenumber::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 1052 of file Unit.cpp.
References Mantid::Kernel::Units::DeltaE::init(), Mantid::PhysicalConstants::meVtoWavenumber, and Mantid::Kernel::Units::DeltaE::unitScaling.
label()
const UnitLabel Mantid::Kernel::Units::DeltaE_inWavenumber::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Reimplemented from Mantid::Kernel::Units::DeltaE.
Definition at line 1050 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::InverseCM.
unitID()
const std::string Mantid::Kernel::Units::DeltaE_inWavenumber::unitID () const override virtual
"DeltaE_inWavenumber"
Reimplemented from Mantid::Kernel::Units::DeltaE.
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp