Mantid: Mantid::WorkflowAlgorithms Namespace Reference
Mantid::WorkflowAlgorithms Namespace Reference
Namespaces
namespace EQSANSInstrument
namespace HFIRInstrument
namespace PropertyNames
Classes
class AlignAndFocusPowder
This is a parent algorithm that uses several different child algorithms to perform it's task.
class ComputeSensitivity
Workflow algorithm to compute a patched sensitivity correction for EQSANS.
class DgsAbsoluteUnitsReduction
DgsAbsoluteUnitsReduction : This is the algorithm responsible for processing and creating the absolute units normalisation data.
class DgsConvertToEnergyTransfer
DgsConvertToEnergyTransfer : This is the algorithm responsible for the conversion from TOF to energy transfer.
class DgsDiagnose
DgsDiagnose : This algorithm constructs all of the necessary workspaces for performing detector diagnostics and then runs the diagnostic algorithm.
class DgsPreprocessData
DgsPreprocessData : This algorithm is responsible for normalising the data to current (proton charge) or monitor.
class DgsProcessDetectorVanadium
DgsProcessDetectorVanadium : This is the algorithm responsible for processing the detector vanadium into the form needed for the normalisation of sample data in the convert to energy transfer process.
class DgsReduction
DgsReduction : This is the top-level workflow algorithm for controlling direct geometry spectrometer reduction.
class DgsRemap
DgsRemap : This algorithm takes a workspace and masks and groups that workspace if appropriate information is passed.
class EQSANSDarkCurrentSubtraction
Subtract dark current for EQSANS.
class EQSANSDarkCurrentSubtraction2
Subtract dark current for EQSANS.
class EQSANSLoad
Subtract dark current for EQSANS.
class EQSANSMonitorTOF
class EQSANSPatchSensitivity
Calculate the detector sensitivity and patch the pixels that are masked in a second workspace.
class EQSANSQ2D
Workflow algorithm to process a reduced EQSANS workspace and produce I(Qx,Qy).
class HFIRDarkCurrentSubtraction
Subtract dark current for HFIR SANS.
class HFIRLoad
Subtract dark current for HFIR SANS.
class HFIRSANSNormalise
class IMuonAsymmetryCalculator
IMuonAsymmetryCalculator : Abstract base class for muon asymmetry calculations.
class LoadEventAndCompress
LoadEventAndCompress : TODO: DESCRIPTION.
class MuonGroupAsymmetryCalculator
MuonGroupAsymmetryCalculator : Calculates asymmetry between given group (specified via GroupIndex) and Muon exponential decay.
class MuonGroupCalculator
MuonGroupCalculator : Base class for Muon group counts/asymmetry calculators.
class MuonGroupCountsCalculator
MuonGroupCountsCalculator : Calculates pure counts of the group specified via group index.
class MuonPairAsymmetryCalculator
MuonPairAsymmetryCalculator : Calculates asymmetry for a given pair of groups, given the alpha value.
class MuonProcess
MuonProcess : Processes and analyses Muon workspace.
struct RegLowVectorPair
class SANSBeamFinder
Beam Finder for SANS instruments.
class SANSBeamFluxCorrection
Performs beam flux correction on TOF SANS data.
class SANSSensitivityCorrection
Sensitivity correction for SANS.
class SANSSolidAngleCorrection
Performs a solid angle correction on a 2D SANS data set to correct for the absence of curvature of the detector.
class SetupEQSANSReduction
Set up the reduction options for EQSANS reduction.
class SetupHFIRReduction
Set up the reduction options for HFIR reduction.
class SofTwoThetaTOF
SofTwoThetaTOF : Convert a S(spectrum number, TOF) workspace to S(twoTheta, TOF) workspace.
class StepScan
This workflow algorithm is for generation of a rocking curve from an alignment scan performed on an ADARA-enabled instrument at the SNS.
Functions
double getRunProperty (const MatrixWorkspace_sptr &inputWS, const std::string &pname)
Returns the value of a run property from a given workspace.
double getRunPropertyDbl (const MatrixWorkspace_sptr &inputWS, const std::string &pname)
Returns the value of a run property from a given workspace.
double getStoredNorm ()
template<typename NumT >
RegLowVectorPair< NumT > splitVectors (const std::vector< NumT > &orig, const size_t numVal, const std::string &label)
Variables
const double CHOPPER_ANGLE [4] = {129.605, 179.989, 230.010, 230.007}
const double CHOPPER_LOCATION [4] = {5700., 7800., 9497., 9507.}
const double CHOPPER_PHASE_OFFSET [2][4] = {{9507., 9471., 9829.7, 9584.3}, {19024., 18820., 19714., 19360.}}
const double PULSEWIDTH = 20.0
Determine the wavelength from the TOF in the beam monitor histogram.
Function Documentation
getRunProperty()
double Mantid::WorkflowAlgorithms::getRunProperty (const MatrixWorkspace_sptr & inputWS, const std::string & pname)
Returns the value of a run property from a given workspace.
Parameters
inputWS :: input workspace
pname :: name of the property to retrieve
Definition at line 37 of file EQSANSQ2D.cpp.
Referenced by Mantid::WorkflowAlgorithms::EQSANSQ2D::exec().
getRunPropertyDbl()
double Mantid::WorkflowAlgorithms::getRunPropertyDbl (const MatrixWorkspace_sptr & inputWS, const std::string & pname)
Returns the value of a run property from a given workspace.
Parameters
inputWS :: input workspace
pname :: name of the property to retrieve
Definition at line 109 of file EQSANSLoad.cpp.
getStoredNorm()
double Mantid::WorkflowAlgorithms::getStoredNorm ()
Definition at line 166 of file MuonGroupAsymmetryCalculator.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by Mantid::WorkflowAlgorithms::MuonGroupAsymmetryCalculator::estimateAsymmetry().
splitVectors()
template<typename NumT > RegLowVectorPair< NumT > Mantid::WorkflowAlgorithms::splitVectors (const std::vector< NumT > & orig, const size_t numVal, const std::string & label)
Definition at line 291 of file AlignAndFocusPowder.cpp.
References Mantid::WorkflowAlgorithms::RegLowVectorPair< NumT >::low, and Mantid::WorkflowAlgorithms::RegLowVectorPair< NumT >::reg.
Referenced by Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec().
Variable Documentation
CHOPPER_ANGLE
const double Mantid::WorkflowAlgorithms::CHOPPER_ANGLE[4] = {129.605, 179.989, 230.010, 230.007}
Definition at line 29 of file EQSANSMonitorTOF.h.
Referenced by Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset().
CHOPPER_LOCATION
const double Mantid::WorkflowAlgorithms::CHOPPER_LOCATION[4] = {5700., 7800., 9497., 9507.}
Definition at line 31 of file EQSANSMonitorTOF.h.
Referenced by Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset().
CHOPPER_PHASE_OFFSET
const double Mantid::WorkflowAlgorithms::CHOPPER_PHASE_OFFSET[2][4] = {{9507., 9471., 9829.7, 9584.3}, {19024., 18820., 19714., 19360.}}
Definition at line 27 of file EQSANSMonitorTOF.h.
Referenced by Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset().
PULSEWIDTH
const double Mantid::WorkflowAlgorithms::PULSEWIDTH = 20.0
Determine the wavelength from the TOF in the beam monitor histogram.
The algorithm has to modify TOF values to correct for the fact that T_0 is not properly recorded by the DAS.
Definition at line 25 of file EQSANSMonitorTOF.h.
Referenced by Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset().