Mantid: ICat4::ns1__luceneSearchResponse Class Reference
ICat4::ns1__luceneSearchResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__luceneSearchResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< std::string > return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 557 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__luceneSearchResponse()
ICat4::ns1__luceneSearchResponse::ns1__luceneSearchResponse () inline
Definition at line 573 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__luceneSearchResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21036 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_std__vectorTemplateOfstd__string().
Referenced by ICat4::ICATPortBindingProxy::luceneSearch(), ICat4::soap_in_ns1__luceneSearchResponse(), ICat4::soap_new_req_ns1__luceneSearchResponse(), and ICat4::soap_new_set_ns1__luceneSearchResponse().
soap_get()
void * ICat4::ns1__luceneSearchResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21127 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__luceneSearchResponse().
Referenced by ICat4::ICATPortBindingProxy::luceneSearch().
soap_in()
void * ICat4::ns1__luceneSearchResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21065 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__luceneSearchResponse().
Referenced by ICat4::soap_in_ns1__luceneSearchResponse().
soap_out()
int ICat4::ns1__luceneSearchResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21050 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__luceneSearchResponse().
Referenced by soap_put().
soap_put()
int ICat4::ns1__luceneSearchResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21120 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__luceneSearchResponse.
soap_serialize()
void ICat4::ns1__luceneSearchResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 21042 of file ICat4C.cpp.
References return_, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), and ICat4::soap_serialize_std__vectorTemplateOfstd__string().
Referenced by ICat4::soap_serialize_PointerTons1__luceneSearch().
soap_type()
int ICat4::ns1__luceneSearchResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 566 of file ICat4Stub.h.
Member Data Documentation
return_
std::vector<std::string> ICat4::ns1__luceneSearchResponse::return_
Definition at line 559 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp