Mantid: Mantid::Geometry::MDGeometryXMLParser Class Reference
Mantid::Geometry::MDGeometryXMLParser Class Reference
Handles the extraction of dimensions from a xml xml string to determine how mappings have been formed.
#include <MDGeometryXMLParser.h>
Public Member Functions
virtual void execute ()
Peforms the processing associated with these transformations.
Mantid::Geometry::VecIMDDimension_sptr getAllDimensions () const
Getter for all dimensions parsed.
Mantid::Geometry::VecIMDDimension_sptr getIntegratedDimensions () const
Getter for all those dimensions which are integrated.
Mantid::Geometry::VecIMDDimension_sptr getNonIntegratedDimensions () const
Getter for all those dimensions which are not integrated.
Mantid::Geometry::VecIMDDimension_sptr getNonMappedDimensions () const
Getter for all those dimensions which are not mapped.
Mantid::Geometry::IMDDimension_sptr getTDimension () const
Getter for t dimension.
Mantid::Geometry::IMDDimension_sptr getXDimension () const
Getter for x dimension.
Mantid::Geometry::IMDDimension_sptr getYDimension () const
Getter for y dimension.
Mantid::Geometry::IMDDimension_sptr getZDimension () const
Getter for z dimension.
bool hasTDimension () const
Determine wheter t dimension is present.
bool hasXDimension () const
Determine wheter x dimension is present.
bool hasYDimension () const
Determine wheter y dimension is present.
bool hasZDimension () const
Determine wheter z dimension is present.
bool isTDimension (const Mantid::Geometry::IMDDimension_sptr &) const
Determines whether query dimension is the t dimension.
bool isXDimension (const Mantid::Geometry::IMDDimension_sptr &) const
Determines whether query dimension is the x dimension.
bool isYDimension (const Mantid::Geometry::IMDDimension_sptr &) const
Determines whether query dimension is the y dimension.
bool isZDimension (const Mantid::Geometry::IMDDimension_sptr &) const
Determines whether query dimension is the z dimension.
MDGeometryXMLParser (const MDGeometryXMLParser &)
Copy constructor.
MDGeometryXMLParser (std::string xmlToProcess)
Constructor.
MDGeometryXMLParser & operator= (const MDGeometryXMLParser &)
Assignement operator.
void SetRootNodeCheck (std::string elementName)
Setter for the root element.
virtual ~MDGeometryXMLParser ()=default
Protected Member Functions
MDGeometryXMLParser ()
Constructor.
Protected Attributes
std::string m_xmlToProcess
Private Member Functions
void validate () const
Validate the current object.
Private Attributes
bool m_executed
std::string m_rootNodeName
Mantid::Geometry::IMDDimension_sptr m_tDimension
Mantid::Geometry::VecIMDDimension_sptr m_vecAllDims
Mantid::Geometry::VecIMDDimension_sptr m_vecNonMappedDims
Mantid::Geometry::IMDDimension_sptr m_xDimension
Mantid::Geometry::IMDDimension_sptr m_yDimension
Mantid::Geometry::IMDDimension_sptr m_zDimension
Detailed Description
Handles the extraction of dimensions from a xml xml string to determine how mappings have been formed.
Author
Owen Arnold, Tessella Support Services plc
Date
17/05/2011
Definition at line 24 of file MDGeometryXMLParser.h.
Constructor & Destructor Documentation
MDGeometryXMLParser() [1/3]
Mantid::Geometry::MDGeometryXMLParser::MDGeometryXMLParser () protected
Constructor.
Definition at line 151 of file MDGeometryXMLParser.cpp.
MDGeometryXMLParser() [2/3]
Mantid::Geometry::MDGeometryXMLParser::MDGeometryXMLParser (std::string xmlToProcess) explicit
Constructor.
Parameters
xmlToProcess : vtkDataSet to process
Definition at line 145 of file MDGeometryXMLParser.cpp.
~MDGeometryXMLParser()
virtual Mantid::Geometry::MDGeometryXMLParser::~MDGeometryXMLParser () virtual default
MDGeometryXMLParser() [3/3]
Mantid::Geometry::MDGeometryXMLParser::MDGeometryXMLParser (const MDGeometryXMLParser & other)
Copy constructor.
Parameters
other : existing MDGeometryXMLParser to assign from.
Definition at line 294 of file MDGeometryXMLParser.cpp.
Member Function Documentation
execute()
void Mantid::Geometry::MDGeometryXMLParser::execute () virtual
Peforms the processing associated with these transformations.
Definition at line 48 of file MDGeometryXMLParser.cpp.
References Mantid::Geometry::createDimension(), m_executed, m_rootNodeName, m_tDimension, m_vecAllDims, m_vecNonMappedDims, m_xDimension, m_xmlToProcess, m_yDimension, m_zDimension, Mantid::Geometry::MDGeometryXMLDefinitions::workspaceDimensionElementName(), Mantid::Geometry::MDGeometryXMLDefinitions::workspaceRefDimensionElementName(), Mantid::Geometry::MDGeometryXMLDefinitions::workspaceTDimensionElementName(), Mantid::Geometry::MDGeometryXMLDefinitions::workspaceXDimensionElementName(), Mantid::Geometry::MDGeometryXMLDefinitions::workspaceYDimensionElementName(), and Mantid::Geometry::MDGeometryXMLDefinitions::workspaceZDimensionElementName().
getAllDimensions()
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getAllDimensions () const
Getter for all dimensions parsed.
Returns
collection of all dimensions parsed.
Definition at line 224 of file MDGeometryXMLParser.cpp.
References m_vecAllDims, and validate().
getIntegratedDimensions()
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getIntegratedDimensions () const
Getter for all those dimensions which are integrated.
Returns
collection of non integrated dimensions parsed.
Definition at line 213 of file MDGeometryXMLParser.cpp.
References m_vecAllDims, and validate().
getNonIntegratedDimensions()
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getNonIntegratedDimensions () const
Getter for all those dimensions which are not integrated.
Returns
collection of non integrated dimensions parsed.
Definition at line 202 of file MDGeometryXMLParser.cpp.
References m_vecAllDims, and validate().
getNonMappedDimensions()
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getNonMappedDimensions () const
Getter for all those dimensions which are not mapped.
Returns
collection of non-mapped dimensions parsed.
Definition at line 193 of file MDGeometryXMLParser.cpp.
References m_vecNonMappedDims, and validate().
getTDimension()
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getTDimension () const
Getter for t dimension.
Returns
t dimension.
Definition at line 184 of file MDGeometryXMLParser.cpp.
References m_tDimension, and validate().
getXDimension()
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getXDimension () const
Getter for x dimension.
Returns
x dimension.
Definition at line 157 of file MDGeometryXMLParser.cpp.
References m_xDimension, and validate().
getYDimension()
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getYDimension () const
Getter for y dimension.
Returns
y dimension.
Definition at line 166 of file MDGeometryXMLParser.cpp.
References m_yDimension, and validate().
getZDimension()
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::getZDimension () const
Getter for z dimension.
Returns
z dimension.
Definition at line 175 of file MDGeometryXMLParser.cpp.
References m_zDimension, and validate().
hasTDimension()
bool Mantid::Geometry::MDGeometryXMLParser::hasTDimension () const
Determine wheter t dimension is present.
Returns
true if available.
Definition at line 260 of file MDGeometryXMLParser.cpp.
References m_tDimension, and validate().
Referenced by isTDimension().
hasXDimension()
bool Mantid::Geometry::MDGeometryXMLParser::hasXDimension () const
Determine wheter x dimension is present.
Returns
true if available.
Definition at line 233 of file MDGeometryXMLParser.cpp.
References m_xDimension, and validate().
Referenced by isXDimension().
hasYDimension()
bool Mantid::Geometry::MDGeometryXMLParser::hasYDimension () const
Determine wheter y dimension is present.
Returns
true if available.
Definition at line 242 of file MDGeometryXMLParser.cpp.
References m_yDimension, and validate().
Referenced by isYDimension().
hasZDimension()
bool Mantid::Geometry::MDGeometryXMLParser::hasZDimension () const
Determine wheter z dimension is present.
Returns
true if available.
Definition at line 251 of file MDGeometryXMLParser.cpp.
References m_zDimension, and validate().
Referenced by isZDimension().
isTDimension()
bool Mantid::Geometry::MDGeometryXMLParser::isTDimension (const Mantid::Geometry::IMDDimension_sptr & candidate) const
Determines whether query dimension is the t dimension.
Parameters
candidate : query dimension.
Returns
true if matches.
Definition at line 352 of file MDGeometryXMLParser.cpp.
References hasTDimension(), m_tDimension, and validate().
isXDimension()
bool Mantid::Geometry::MDGeometryXMLParser::isXDimension (const Mantid::Geometry::IMDDimension_sptr & candidate) const
Determines whether query dimension is the x dimension.
Parameters
candidate : query dimension.
Returns
true if matches.
Definition at line 304 of file MDGeometryXMLParser.cpp.
References hasXDimension(), m_xDimension, and validate().
isYDimension()
bool Mantid::Geometry::MDGeometryXMLParser::isYDimension (const Mantid::Geometry::IMDDimension_sptr & candidate) const
Determines whether query dimension is the y dimension.
Parameters
candidate : query dimension.
Returns
true if matches.
Definition at line 320 of file MDGeometryXMLParser.cpp.
References hasYDimension(), m_yDimension, and validate().
isZDimension()
bool Mantid::Geometry::MDGeometryXMLParser::isZDimension (const Mantid::Geometry::IMDDimension_sptr & candidate) const
Determines whether query dimension is the z dimension.
Parameters
candidate : query dimension.
Returns
true if matches.
Definition at line 336 of file MDGeometryXMLParser.cpp.
References hasZDimension(), m_zDimension, and validate().
operator=()
MDGeometryXMLParser & Mantid::Geometry::MDGeometryXMLParser::operator= (const MDGeometryXMLParser & other)
Assignement operator.
Parameters
other : existing MDGeometryXMLParser to assign from.
Definition at line 276 of file MDGeometryXMLParser.cpp.
References m_executed, m_rootNodeName, m_tDimension, m_vecAllDims, m_vecNonMappedDims, m_xDimension, m_yDimension, and m_zDimension.
SetRootNodeCheck()
void Mantid::Geometry::MDGeometryXMLParser::SetRootNodeCheck (std::string elementName)
Setter for the root element.
Parameters
elementName : name of the element containing xml dimensions. Usually "Dimensions" unless xml snippet passed in directly, in which case do not set.
Definition at line 270 of file MDGeometryXMLParser.cpp.
References m_rootNodeName.
validate()
void Mantid::Geometry::MDGeometryXMLParser::validate () const private
Validate the current object.
Take action if not set up properly.
Definition at line 38 of file MDGeometryXMLParser.cpp.
References m_executed.
Referenced by getAllDimensions(), getIntegratedDimensions(), getNonIntegratedDimensions(), getNonMappedDimensions(), getTDimension(), getXDimension(), getYDimension(), getZDimension(), hasTDimension(), hasXDimension(), hasYDimension(), hasZDimension(), isTDimension(), isXDimension(), isYDimension(), and isZDimension().
Member Data Documentation
m_executed
bool Mantid::Geometry::MDGeometryXMLParser::m_executed private
Definition at line 27 of file MDGeometryXMLParser.h.
Referenced by execute(), operator=(), and validate().
m_rootNodeName
std::string Mantid::Geometry::MDGeometryXMLParser::m_rootNodeName private
Definition at line 29 of file MDGeometryXMLParser.h.
Referenced by execute(), operator=(), and SetRootNodeCheck().
m_tDimension
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_tDimension private
Definition at line 41 of file MDGeometryXMLParser.h.
Referenced by execute(), getTDimension(), hasTDimension(), isTDimension(), and operator=().
m_vecAllDims
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_vecAllDims private
Definition at line 33 of file MDGeometryXMLParser.h.
Referenced by execute(), getAllDimensions(), getIntegratedDimensions(), getNonIntegratedDimensions(), and operator=().
m_vecNonMappedDims
Mantid::Geometry::VecIMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_vecNonMappedDims private
Definition at line 31 of file MDGeometryXMLParser.h.
Referenced by execute(), getNonMappedDimensions(), and operator=().
m_xDimension
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_xDimension private
Definition at line 35 of file MDGeometryXMLParser.h.
Referenced by execute(), getXDimension(), hasXDimension(), isXDimension(), and operator=().
m_xmlToProcess
std::string Mantid::Geometry::MDGeometryXMLParser::m_xmlToProcess protected
Definition at line 46 of file MDGeometryXMLParser.h.
Referenced by execute().
m_yDimension
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_yDimension private
Definition at line 37 of file MDGeometryXMLParser.h.
Referenced by execute(), getYDimension(), hasYDimension(), isYDimension(), and operator=().
m_zDimension
Mantid::Geometry::IMDDimension_sptr Mantid::Geometry::MDGeometryXMLParser::m_zDimension private
Definition at line 39 of file MDGeometryXMLParser.h.
Referenced by execute(), getZDimension(), hasZDimension(), isZDimension(), and operator=().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDGeometryXMLParser.h
Framework/Geometry/src/MDGeometry/MDGeometryXMLParser.cpp