Mantid: Mantid::Geometry::ComponentParser Class Reference
Mantid::Geometry::ComponentParser Class Reference
This class implements the Poco SAX ContentHandler class for reading component XML.
#include <ComponentParser.h>
Public Member Functions
void characters (const Poco::XML::XMLChar[], int, int) override
void endDocument () override
Not used.
void endElement (const Poco::XML::XMLString &, const Poco::XML::XMLString &localName, const Poco::XML::XMLString &) override
Signals end of element.
void endPrefixMapping (const Poco::XML::XMLString &) override
Not used.
Component * getComponent ()
void ignorableWhitespace (const Poco::XML::XMLChar[], int, int) override
Not used.
void processingInstruction (const Poco::XML::XMLString &, const Poco::XML::XMLString &) override
Not used.
void setDocumentLocator (const Poco::XML::Locator *) override
Not used.
size_t size () const
void skippedEntity (const Poco::XML::XMLString &) override
Not used.
void startDocument () override
Signals start of XML document.
void startElement (const Poco::XML::XMLString &, const Poco::XML::XMLString &localName, const Poco::XML::XMLString &, const Poco::XML::Attributes &attr) override
Signals start of element.
void startPrefixMapping (const Poco::XML::XMLString &, const Poco::XML::XMLString &) override
Not used.
Private Attributes
std::vector< Component * > m_current
The components currently being built up.
std::string m_innerText
Detailed Description
This class implements the Poco SAX ContentHandler class for reading component XML.
Author
Janik Zikovsky
Date
2011-09-07
Definition at line 24 of file ComponentParser.h.
Member Function Documentation
characters()
void Mantid::Geometry::ComponentParser::characters (const Poco::XML::XMLChar ch[], int start, int length) override
Definition at line 21 of file ComponentParser.cpp.
References m_innerText.
endDocument()
void Mantid::Geometry::ComponentParser::endDocument () inline override
Not used.
Definition at line 44 of file ComponentParser.h.
endElement()
void Mantid::Geometry::ComponentParser::endElement (const Poco::XML::XMLString & , const Poco::XML::XMLString & localName, const Poco::XML::XMLString &) override
Signals end of element.
Definition at line 58 of file ComponentParser.cpp.
References Mantid::Kernel::Quat::fromString(), Mantid::Kernel::V3D::fromString(), m_current, m_innerText, Mantid::Geometry::Component::setPos(), and Mantid::Geometry::Component::setRot().
endPrefixMapping()
void Mantid::Geometry::ComponentParser::endPrefixMapping (const Poco::XML::XMLString &) inline override
Not used.
Definition at line 48 of file ComponentParser.h.
getComponent()
Component * Mantid::Geometry::ComponentParser::getComponent ()
Returns
the top-level component created
Definition at line 14 of file ComponentParser.cpp.
References m_current.
ignorableWhitespace()
void Mantid::Geometry::ComponentParser::ignorableWhitespace (const Poco::XML::XMLChar [], int , int) inline override
Not used.
Definition at line 45 of file ComponentParser.h.
processingInstruction()
void Mantid::Geometry::ComponentParser::processingInstruction (const Poco::XML::XMLString & , const Poco::XML::XMLString &) inline override
Not used.
Definition at line 46 of file ComponentParser.h.
setDocumentLocator()
void Mantid::Geometry::ComponentParser::setDocumentLocator (const Poco::XML::Locator *) inline override
Not used.
Definition at line 43 of file ComponentParser.h.
size()
size_t Mantid::Geometry::ComponentParser::size () const inline
Definition at line 37 of file ComponentParser.h.
skippedEntity()
void Mantid::Geometry::ComponentParser::skippedEntity (const Poco::XML::XMLString &) inline override
Not used.
Definition at line 49 of file ComponentParser.h.
startDocument()
void Mantid::Geometry::ComponentParser::startDocument () inline override
Signals start of XML document.
Not used
Definition at line 42 of file ComponentParser.h.
startElement()
void Mantid::Geometry::ComponentParser::startElement (const Poco::XML::XMLString & , const Poco::XML::XMLString & localName, const Poco::XML::XMLString & , const Poco::XML::Attributes & attr) override
Signals start of element.
Definition at line 27 of file ComponentParser.cpp.
References m_current, and Mantid::Geometry::Component::readXMLAttributes().
startPrefixMapping()
void Mantid::Geometry::ComponentParser::startPrefixMapping (const Poco::XML::XMLString & , const Poco::XML::XMLString &) inline override
Not used.
Definition at line 47 of file ComponentParser.h.
Member Data Documentation
m_current
std::vector<Component *> Mantid::Geometry::ComponentParser::m_current private
The components currently being built up.
The one at the back of the vector is the latest one.
Definition at line 54 of file ComponentParser.h.
Referenced by endElement(), getComponent(), and startElement().
m_innerText
std::string Mantid::Geometry::ComponentParser::m_innerText private
Definition at line 56 of file ComponentParser.h.
Referenced by characters(), and endElement().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/ComponentParser.h
Framework/Geometry/src/ComponentParser.cpp