Mantid: MantidQt::MantidWidgets::IFitScriptGeneratorModel Class Reference
MantidQt::MantidWidgets::IFitScriptGeneratorModel Class Reference abstract
#include <IFitScriptGeneratorModel.h>
Public Member Functions
virtual void addFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void addWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX)=0
virtual std::string generatePythonFitScript (std::tuple< std::string, std::string, std::string, std::string, std::string, bool > const &fitOptions, std::string const &filepath="")=0
virtual std::string getAdjustedFunctionIndex (std::string const &parameter) const =0
virtual std::string getDomainName (FitDomainIndex domainIndex) const =0
virtual std::string getEquivalentFunctionIndexForDomain (FitDomainIndex domainIndex, std::string const &functionIndex) const =0
virtual std::string getEquivalentFunctionIndexForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex) const =0
virtual std::string getEquivalentParameterTieForDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &fullTie) const =0
virtual FittingMode getFittingMode () const =0
virtual std::string getFullParameter (FitDomainIndex domainIndex, std::string const &parameter) const =0
virtual std::string getFullTie (FitDomainIndex domainIndex, std::string const &tie) const =0
virtual Mantid::API::IFunction_sptr getFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const =0
virtual std::vector< GlobalParameter > getGlobalParameters () const =0
virtual std::vector< GlobalTie > getGlobalTies () const =0
virtual std::string getParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual std::string getParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual double getParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool hasParameter (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool hasWorkspaceDomain (std::string const &workspaceName, WorkspaceIndex workspaceIndex) const =0
virtual bool isParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter) const =0
virtual bool isSimultaneousMode () const =0
virtual std::tuple< bool, std::string > isValid () const =0
virtual std::size_t numberOfDomains () const =0
virtual void removeDomain (FitDomainIndex domainIndex)=0
virtual void removeFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void removeParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter)=0
virtual void renameWorkspace (std::string const &workspaceName, std::string const &newName)=0
virtual void setFittingMode (FittingMode fittingMode)=0
virtual void setFunction (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &function)=0
virtual void setGlobalParameters (std::vector< std::string > const &parameters)=0
virtual void setOutputBaseName (std::string const &outputBaseName)=0
virtual void setParameterConstraint (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &constraint)=0
virtual void setParameterFixed (FitDomainIndex domainIndex, std::string const &fullParameter, bool fix)=0
virtual void setParameterTie (FitDomainIndex domainIndex, std::string const &fullParameter, std::string const &tie)=0
virtual void setParameterValue (FitDomainIndex domainIndex, std::string const &fullParameter, double value)=0
virtual void subscribePresenter (IFitScriptGeneratorPresenter *presenter)=0
virtual void updateAttributeValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullAttribute, Mantid::API::IFunction::Attribute const &newValue)=0
virtual bool updateEndX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double endX)=0
virtual void updateParameterConstraint (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &functionIndex, std::string const &constraint)=0
virtual void updateParameterTie (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, std::string const &tie)=0
virtual void updateParameterValue (std::string const &workspaceName, WorkspaceIndex workspaceIndex, std::string const &fullParameter, double newValue)=0
virtual bool updateStartX (std::string const &workspaceName, WorkspaceIndex workspaceIndex, double startX)=0
virtual ~IFitScriptGeneratorModel ()=default
Detailed Description
Definition at line 23 of file IFitScriptGeneratorModel.h.
Constructor & Destructor Documentation
~IFitScriptGeneratorModel()
virtual MantidQt::MantidWidgets::IFitScriptGeneratorModel::~IFitScriptGeneratorModel () virtual default
Member Function Documentation
addFunction()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::addFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addFunction().
addWorkspaceDomain()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::addWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX, double endX) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::addWorkspace().
generatePythonFitScript()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::generatePythonFitScript (std::tuple< std::string, std::string, std::string, std::string, std::string, bool > const & fitOptions, std::string const & filepath = "") pure virtual
Implemented in MockFitScriptGeneratorModel, and MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToClipboard(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateScriptToFile().
getAdjustedFunctionIndex()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getAdjustedFunctionIndex (std::string const & parameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleEditLocalParameterClicked().
getDomainName()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getDomainName (FitDomainIndex domainIndex) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain().
getEquivalentFunctionIndexForDomain() [1/2]
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentFunctionIndexForDomain (FitDomainIndex domainIndex, std::string const & functionIndex) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
getEquivalentFunctionIndexForDomain() [2/2]
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentFunctionIndexForDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & functionIndex) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::convertFunctionIndexOfParameterTie(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterConstraint(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterValue().
getEquivalentParameterTieForDomain()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getEquivalentParameterTieForDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, std::string const & fullTie) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::convertFunctionIndexOfParameterTie().
getFittingMode()
virtual FittingMode MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFittingMode () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
getFullParameter()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFullParameter (FitDomainIndex domainIndex, std::string const & parameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getDomainsWithLocalParameter(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
getFullTie()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFullTie (FitDomainIndex domainIndex, std::string const & tie) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
getFunction()
virtual Mantid::API::IFunction_sptr MantidQt::MantidWidgets::IFitScriptGeneratorModel::getFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel().
getGlobalParameters()
virtual std::vector< GlobalParameter > MantidQt::MantidWidgets::IFitScriptGeneratorModel::getGlobalParameters () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateFunctionInViewFromModel().
getGlobalTies()
virtual std::vector< GlobalTie > MantidQt::MantidWidgets::IFitScriptGeneratorModel::getGlobalTies () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleParameterTieChanged().
getParameterConstraint()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterConstraint (FitDomainIndex domainIndex, std::string const & fullParameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain().
getParameterTie()
virtual std::string MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain().
getParameterValue()
virtual double MantidQt::MantidWidgets::IFitScriptGeneratorModel::getParameterValue (FitDomainIndex domainIndex, std::string const & fullParameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain().
hasParameter()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::hasParameter (FitDomainIndex domainIndex, std::string const & fullParameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::getDomainsWithLocalParameter(), MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain(), and MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
hasWorkspaceDomain()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::hasWorkspaceDomain (std::string const & workspaceName, WorkspaceIndex workspaceIndex) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
isParameterFixed()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::isParameterFixed (FitDomainIndex domainIndex, std::string const & fullParameter) const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::insertLocalParameterDataForDomain().
isSimultaneousMode()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::isSimultaneousMode () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleSelectionChanged().
isValid()
virtual std::tuple< bool, std::string > MantidQt::MantidWidgets::IFitScriptGeneratorModel::isValid () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::generateFitScript().
numberOfDomains()
virtual std::size_t MantidQt::MantidWidgets::IFitScriptGeneratorModel::numberOfDomains () const pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
removeDomain()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeDomain (FitDomainIndex domainIndex) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeDomains().
removeFunction()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeFunction().
removeParameterConstraint()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::removeParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::removeParameterConstraint().
renameWorkspace()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::renameWorkspace (std::string const & workspaceName, std::string const & newName) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleADSRenameEvent().
setFittingMode()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setFittingMode (FittingMode fittingMode) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleFittingModeChanged().
setFunction()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setFunction (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & function) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setFunction().
setGlobalParameters()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setGlobalParameters (std::vector< std::string > const & parameters) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleGlobalParametersChanged().
setOutputBaseName()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setOutputBaseName (std::string const & outputBaseName) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::handleOutputBaseNameChanged().
setParameterConstraint()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterConstraint (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & constraint) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
setParameterFixed()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterFixed (FitDomainIndex domainIndex, std::string const & fullParameter, bool fix) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
setParameterTie()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterTie (FitDomainIndex domainIndex, std::string const & fullParameter, std::string const & tie) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
setParameterValue()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::setParameterValue (FitDomainIndex domainIndex, std::string const & fullParameter, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::setLocalParameterDataForDomain().
subscribePresenter()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::subscribePresenter (IFitScriptGeneratorPresenter * presenter) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::FitScriptGeneratorPresenter().
updateAttributeValue()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateAttributeValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullAttribute, Mantid::API::IFunction::Attribute const & newValue) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateAttributeValue().
updateEndX()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateEndX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double endX) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateEndX().
updateParameterConstraint()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterConstraint (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & functionIndex, std::string const & constraint) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterConstraint().
updateParameterTie()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterTie (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, std::string const & tie) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterTie().
updateParameterValue()
virtual void MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateParameterValue (std::string const & workspaceName, WorkspaceIndex workspaceIndex, std::string const & fullParameter, double newValue) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateParameterValue().
updateStartX()
virtual bool MantidQt::MantidWidgets::IFitScriptGeneratorModel::updateStartX (std::string const & workspaceName, WorkspaceIndex workspaceIndex, double startX) pure virtual
Implemented in MantidQt::MantidWidgets::FitScriptGeneratorModel.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorPresenter::updateStartX().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorModel.h