Mantid: Mantid::CurveFitting::MultiDomainCreator Class Reference
Mantid::CurveFitting::MultiDomainCreator Class Reference
Creates a composite domain.
#include <MultiDomainCreator.h>
Public Member Functions
void createDomain (std::shared_ptr< API::FunctionDomain > &domain, std::shared_ptr< API::FunctionValues > &ivalues, size_t i0=0) override
Create a domain from the input workspace.
std::shared_ptr< API::Workspace > createOutputWorkspace (const std::string &baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string &outputWorkspacePropertyName) override
Create the output workspace.
size_t getDomainSize () const override
Return the size of the domain to be created.
size_t getNCreators () const
Get number of creators.
bool hasCreator (size_t i) const
Check if i-th creator has been set with setCreator.
void initFunction (API::IFunction_sptr function) override
Initialize the function.
MultiDomainCreator (Kernel::IPropertyManager *fit, const std::vector< std::string > &workspacePropertyNames)
A friend that can create instances of this class.
void setCreator (size_t i, API::IDomainCreator *creator)
Set ith creator.
Public Member Functions inherited from Mantid::API::IDomainCreator
virtual void declareDatasetProperties (const std::string &suffix="", bool addProp=true)
Declare properties that specify the dataset within the workspace to fit to.
IDomainCreator (Kernel::IPropertyManager *manager, std::vector< std::string > workspacePropertyNames, DomainType domainType=Simple)
Constrcutor.
void ignoreInvalidData (bool yes)
Set to ignore invalid data.
virtual void initialize (Kernel::IPropertyManager *, const std::string &, DomainType)
Initialize.
void separateCompositeMembersInOutput (const bool value, const bool conv=false)
Toggle output of either just composite or composite + members.
virtual ~IDomainCreator ()=default
Virtual destructor.
Protected Attributes
std::vector< std::shared_ptr< API::IDomainCreator > > m_creators
Vector of creators.
Protected Attributes inherited from Mantid::API::IDomainCreator
bool m_convolutionCompositeMembers
Perform convolution of output composite components.
DomainType m_domainType
Domain type.
bool m_ignoreInvalidData
Flag to ignore nans, infinities and zero errors.
Kernel::IPropertyManager * m_manager
Pointer to a property manager.
bool m_outputCompositeMembers
Output separate composite function values.
std::vector< std::string > m_workspacePropertyNames
Property names for workspaces to get the data from.
Additional Inherited Members
Public Types inherited from Mantid::API::IDomainCreator
enum DomainType { Simple = 0 , Sequential , Parallel }
Type of domain to create.
Protected Member Functions inherited from Mantid::API::IDomainCreator
void declareProperty (Kernel::Property *prop, const std::string &doc)
Declare a property to the algorithm.
Detailed Description
Creates a composite domain.
Author
Roman Tolchenov, Tessella plc
Date
06/12/2011
Definition at line 24 of file MultiDomainCreator.h.
Constructor & Destructor Documentation
MultiDomainCreator()
Mantid::CurveFitting::MultiDomainCreator::MultiDomainCreator (Kernel::IPropertyManager * fit, const std::vector< std::string > & workspacePropertyNames) inline
A friend that can create instances of this class.
Constructor
Definition at line 29 of file MultiDomainCreator.h.
Member Function Documentation
createDomain()
void Mantid::CurveFitting::MultiDomainCreator::createDomain (std::shared_ptr< API::FunctionDomain > & domain, std::shared_ptr< API::FunctionValues > & ivalues, size_t i0 = 0) override virtual
Create a domain from the input workspace.
Implements Mantid::API::IDomainCreator.
Definition at line 39 of file MultiDomainCreator.cpp.
References Mantid::API::IDomainCreator::m_convolutionCompositeMembers, m_creators, Mantid::API::IDomainCreator::m_ignoreInvalidData, Mantid::API::IDomainCreator::m_outputCompositeMembers, and Mantid::API::IDomainCreator::m_workspacePropertyNames.
createOutputWorkspace()
std::shared_ptr< API::Workspace > Mantid::CurveFitting::MultiDomainCreator::createOutputWorkspace (const std::string & baseName, API::IFunction_sptr function, std::shared_ptr< API::FunctionDomain > domain, std::shared_ptr< API::FunctionValues > values, const std::string & outputWorkspacePropertyName) override virtual
Create the output workspace.
Create the output workspace group.
Parameters
baseName :: The base name for the output workspace. Suffix "Workspace" will be added to it.
function :: A function to calculate the values. Must be of the MultiDomainFunction type.
domain :: Domain created earlier with this creator (unused)
values :: Values created earlier with this creator (unused)
outputWorkspacePropertyName :: Name for the property to hold the output workspace. If empty the property won't be created.
Returns
A shared pointer to the created workspace.
Reimplemented from Mantid::API::IDomainCreator.
Definition at line 105 of file MultiDomainCreator.cpp.
References Mantid::API::IDomainCreator::declareProperty(), m_creators, Mantid::API::IDomainCreator::m_manager, Mantid::Kernel::Direction::Output, Mantid::Kernel::IPropertyManager::setProperty(), Mantid::Kernel::IPropertyManager::setPropertyValue(), std::to_string(), and UNUSED_ARG.
getDomainSize()
size_t Mantid::CurveFitting::MultiDomainCreator::getDomainSize () const inline override virtual
Return the size of the domain to be created.
Implements Mantid::API::IDomainCreator.
Definition at line 42 of file MultiDomainCreator.h.
getNCreators()
size_t Mantid::CurveFitting::MultiDomainCreator::getNCreators () const inline
Get number of creators.
Definition at line 47 of file MultiDomainCreator.h.
hasCreator()
bool Mantid::CurveFitting::MultiDomainCreator::hasCreator (size_t i) const
Check if i-th creator has been set with setCreator.
Parameters
i :: Index of a creator, 0 < i < getNCreators()
Definition at line 36 of file MultiDomainCreator.cpp.
References m_creators.
initFunction()
void Mantid::CurveFitting::MultiDomainCreator::initFunction (API::IFunction_sptr function) override virtual
Initialize the function.
Initialize the function with the workspace(s).
Parameters
function :: A function to initialize.
Reimplemented from Mantid::API::IDomainCreator.
Definition at line 67 of file MultiDomainCreator.cpp.
References Mantid::API::g_log, index, Mantid::API::IDomainCreator::initFunction(), m_creators, and Mantid::Kernel::Logger::warning().
setCreator()
void Mantid::CurveFitting::MultiDomainCreator::setCreator (size_t i, API::IDomainCreator * creator)
Set ith creator.
Definition at line 28 of file MultiDomainCreator.cpp.
References m_creators.
Member Data Documentation
m_creators
std::vector<std::shared_ptr<API::IDomainCreator> > Mantid::CurveFitting::MultiDomainCreator::m_creators protected
Vector of creators.
Definition at line 53 of file MultiDomainCreator.h.
Referenced by createDomain(), createOutputWorkspace(), hasCreator(), initFunction(), and setCreator().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/MultiDomainCreator.h
Framework/CurveFitting/src/MultiDomainCreator.cpp