Mantid: Mantid::DataHandling::FilterEventsByLogValuePreNexus Class Reference
Mantid::DataHandling::FilterEventsByLogValuePreNexus Class Reference
A data loading and splitting routine for SNS pre-nexus event files.
#include <FilterEventsByLogValuePreNexus.h>
Public Member Functions
const std::string alias () const override
Algorithm's aliases.
const std::string category () const override
Algorithm's category for identification.
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
FilterEventsByLogValuePreNexus ()
Constructor.
const std::string name () const override
Algorithm's name.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
~FilterEventsByLogValuePreNexus () override
Virtual destructor.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual int confidence (Kernel::FileDescriptor &descriptor) const=0
Returns a confidence value that this algorithm can load a file.
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Public Member Functions inherited from Mantid::API::DeprecatedAlgorithm
DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
void deprecatedDate (const std::string &)
The date the algorithm was deprecated on.
std::string deprecationMsg (const IAlgorithm *)
This merely prints the deprecation error for people to see.
void useAlgorithm (const std::string &, const int version=-1)
The algorithm to use instead of this one.
virtual ~DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
Private Member Functions
void addToWorkspaceLog (const std::string &logtitle, size_t mindex)
Add absolute time series to log.
void debugOutput (bool doit, size_t mindex)
void doStatToEventLog (size_t mindex)
Perform statistics to event (wrong pixel ID) logs.
void exec () override
Execution code.
void filterEvents ()
Process the event file properly.
void filterEventsLinear (DataObjects::EventWorkspace_sptr &workspace, std::vector< Types::Event::TofEvent > **arrayOfVectors, DasEvent *event_buffer, size_t current_event_buffer_size, size_t fileOffset)
Linear-version of the procedure to process the event file properly.
int findRunFrequency ()
Use pulse index/ event index to find out the frequency of instrument running.
void init () override
Initialisation code.
void loadPixelMap (const std::string &filename)
Load a pixel mapping file.
void openEventFile (const std::string &filename)
Open an event file.
size_t padOutEmptyPixels (const DataObjects::EventWorkspace_sptr &eventws)
Pad out empty pixel.
void processEventLogs ()
Process imbed logs (marked by bad pixel IDs) (1) Add special event log to workspace log (2) (Optionally) do statistic to each pixel (3) (Optionally) write out information.
void processProperties ()
Process properties.
void procEvents (DataObjects::EventWorkspace_sptr &workspace)
Process the event file properly.
void procEventsLinear (DataObjects::EventWorkspace_sptr &workspace, std::vector< Types::Event::TofEvent > **arrayOfVectors, DasEvent *event_buffer, size_t current_event_buffer_size, size_t fileOffset)
Linear-version of the procedure to process the event file properly.
void readPulseidFile (const std::string &filename, const bool throwError)
Read a pulse ID file.
void runLoadInstrument (const std::string &eventfilename, const API::MatrixWorkspace_sptr &localWorkspace)
Load the instrument geometry File.
void setProtonCharge (DataObjects::EventWorkspace_sptr &workspace)
Add a sample environment log for the proton chage (charge of the pulse in picoCoulombs) and set the scalar value (total proton charge, microAmps*hours, on the sample)
DataObjects::EventWorkspace_sptr setupOutputEventWorkspace ()
Create, initialize and set up output EventWrokspace.
void setupPixelSpectrumMap (const DataObjects::EventWorkspace_sptr &eventws)
Set up spectrum/detector ID map inside a workspace.
void unmaskVetoEventIndexes ()
Correct wrong event indexes with pulse.
Private Attributes
bool m_corretctTOF
int64_t m_dbPixelID
Mantid::detid_t m_detid_max
The maximum detector ID possible.
std::unique_ptr< Mantid::Kernel::BinaryFile< DasEvent > > m_eventFile
Handles loading from the event file.
std::string m_eventFileName
Event file.
bool m_examEventLog
Flag for examine event (log)
std::size_t m_firstEvent
The first event to load (count from zero)
int m_freqHz
Accelerator operation frequency.
std::string m_functionMode
Function mode.
int64_t m_istep
bool m_loadOnlySomeSpectra
For loading only some spectra.
DataObjects::EventWorkspace_sptr m_localWorkspace
DataObjects::EventWorkspace_sptr m_localWorkspaceBA
Output EventWorkspace for filtered event B->A.
double m_longestTof
Longest TOF limit.
std::size_t m_maxNumEvents
Number of events to load.
std::size_t m_numBadEvents
The number of bad events.
std::size_t m_numErrorEvents
The number of error events encountered.
std::size_t m_numEvents
The number of events in the file.
int m_numevents2write
Number of events to write out.
std::size_t m_numGoodEvents
The number of good events loaded.
std::size_t m_numIgnoredEvents
the number of events that were ignored (not loaded) because, e.g.
uint32_t m_numPixel
the number of pixels
std::size_t m_numPulses
the number of pulses
std::size_t m_numWrongdetidEvents
The number of events with wrong.
bool m_parallelProcessing
Flag to allow for parallel loading.
int m_pixelid2exam
Pixel ID to exam.
std::vector< PixelType > m_pixelmap
Map between the DAS pixel IDs and our pixel IDs, used while loading.
std::vector< std::size_t > m_pixelToWkspindex
The value of the vector is the workspace index.
std::unique_ptr< Mantid::API::Progress > m_progress = nullptr
std::vector< double > m_protonCharge
The proton charge on a pulse by pulse basis.
double m_protonChargeTot
The total proton charge for the run.
std::string m_pulseIDFileName
Pulse ID file.
bool m_pulseTimesIncreasing
Whether or not the pulse times are sorted in increasing order.
double m_shortestTof
Shortest TOF limit.
std::vector< int64_t > m_spectraList
the list of Spectra
bool m_throwError
Throw error with bad pulse ID.
bool m_useDBOutput
bool m_usingMappingFile
Set to true if a valid Mapping file was provided.
std::vector< uint64_t > m_vecEventIndex
The index of the first event in each pulse.
std::vector< int > m_vecLogPixelID
Log pixel IDs for filtering.
std::vector< std::string > m_vecLogPixelTag
Log pixel Tags for filtering.
std::vector< detid_t > mSEids
sample environment event
std::map< size_t, detid_t > mSEmap
std::vector< std::vector< int64_t > > mSEpulseids
std::vector< std::vector< double > > mSEtofs
std::vector< Types::Core::DateAndTime > pulsetimes
The times for each pulse.
std::map< int64_t, bool > spectraLoadMap
Handle to the loaded spectra map.
std::vector< std::vector< Types::Core::DateAndTime > > wrongdetid_pulsetimes
std::vector< std::vector< double > > wrongdetid_tofs
std::map< PixelType, size_t > wrongdetidmap
std::set< PixelType > wrongdetids
detector IDs. Part of error events.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::ParallelAlgorithm
Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const override
Get correct execution mode based on input storage modes for an MPI run.
~ParallelAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
A data loading and splitting routine for SNS pre-nexus event files.
Definition at line 78 of file FilterEventsByLogValuePreNexus.h.
Constructor & Destructor Documentation
FilterEventsByLogValuePreNexus()
Mantid::DataHandling::FilterEventsByLogValuePreNexus::FilterEventsByLogValuePreNexus ()
Constructor.
Definition at line 207 of file FilterEventsByLogValuePreNexus.cpp.
~FilterEventsByLogValuePreNexus()
Mantid::DataHandling::FilterEventsByLogValuePreNexus::~FilterEventsByLogValuePreNexus () override default
Virtual destructor.
Destructor.
Member Function Documentation
addToWorkspaceLog()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::addToWorkspaceLog (const std::string & logtitle, size_t mindex) private
Add absolute time series to log.
Parameters
logtitle :: title of the log to be inserted to workspace
mindex :: index of the the series in the wrong detectors map
Definition at line 633 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::g_log, Mantid::Kernel::Logger::information(), m_localWorkspace, value, wrongdetid_pulsetimes, and wrongdetid_tofs.
Referenced by processEventLogs().
alias()
const std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::alias () const inline override virtual
Algorithm's aliases.
Reimplemented from Mantid::API::Algorithm.
Definition at line 92 of file FilterEventsByLogValuePreNexus.h.
category()
const std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 90 of file FilterEventsByLogValuePreNexus.h.
confidence()
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 226 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::FileDescriptor::data(), Mantid::Kernel::FileDescriptor::extension(), and Mantid::Kernel::FileDescriptor::isAscii().
debugOutput()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::debugOutput (bool doit, size_t mindex) private
doStatToEventLog()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::doStatToEventLog (size_t mindex) private
Perform statistics to event (wrong pixel ID) logs.
Parameters
mindex :: index of the the series in the list
Definition at line 661 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::Logger::warning(), wrongdetid_pulsetimes, and wrongdetid_tofs.
Referenced by processEventLogs().
exec()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::exec () override private virtual
Execution code.
Execute the algorithm.
check all the inputs
create an EventWorkspace object
process events
set out output
Implements Mantid::API::Algorithm.
Definition at line 338 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::Algorithm::declareProperty(), filterEvents(), findRunFrequency(), Mantid::API::g_log, m_eventFileName, m_freqHz, m_functionMode, m_istep, m_localWorkspace, m_localWorkspaceBA, m_numPulses, m_progress, m_pulseIDFileName, m_pulseTimesIncreasing, m_throwError, openEventFile(), Mantid::DataHandling::OUT_PARAM(), Mantid::Kernel::Direction::Output, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_START_INTERRUPT_REGION, processEventLogs(), processProperties(), procEvents(), Mantid::DataObjects::PULSETIME_SORT, readPulseidFile(), setupOutputEventWorkspace(), unmaskVetoEventIndexes(), and Mantid::Kernel::Logger::warning().
filterEvents()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEvents () private
Process the event file properly.
Pointer to the vector of events
Bare array of arrays of pointers to the EventVectors
How many threads will we use?
Definition at line 1373 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::DataObjects::EventList::clear(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::DEFAULT_BLOCK_SIZE, filterEventsLinear(), Mantid::API::g_log, Mantid::DataObjects::EventList::getEvents(), Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_detid_max, m_eventFile, m_firstEvent, m_localWorkspace, m_localWorkspaceBA, m_longestTof, m_maxNumEvents, m_numErrorEvents, m_numGoodEvents, m_parallelProcessing, m_pixelToWkspindex, m_progress, m_shortestTof, Mantid::DataHandling::MAX_TOF_UINT32, Mantid::Kernel::Logger::notice(), Mantid::DataHandling::numEvents(), padOutEmptyPixels(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_GET_MAX_THREADS, PARALLEL_START_INTERRUPT_REGION, PARALLEL_THREAD_NUMBER, PRAGMA_OMP, Mantid::DataObjects::EventList::reserve(), setProtonCharge(), setupPixelSpectrumMap(), Mantid::DataHandling::TOF_CONVERSION, Mantid::Kernel::Logger::warning(), wrongdetid_pulsetimes, wrongdetidmap, and wrongdetids.
Referenced by exec().
filterEventsLinear()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::filterEventsLinear (DataObjects::EventWorkspace_sptr & workspace, std::vector< Types::Event::TofEvent > ** arrayOfVectors, DasEvent * event_buffer, size_t current_event_buffer_size, size_t fileOffset) private
Linear-version of the procedure to process the event file properly.
Parameters
workspace :: EventWorkspace to write to.
arrayOfVectors :: For speed up: this is an array, of size m_detid_max+1, where the index is a pixel ID, and the value is a pointer to the vector<tofEvent> in the given EventList.
event_buffer :: The buffer containing the DAS events
current_event_buffer_size :: The length of the given DAS buffer
fileOffset :: Value for an offset into the binary file
Definition at line 1614 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::Logger::error(), Mantid::DataHandling::ERROR_PID, Mantid::API::g_log, Mantid::Kernel::l2, m_corretctTOF, m_dbPixelID, m_detid_max, m_examEventLog, m_istep, m_loadOnlySomeSpectra, m_localWorkspace, m_longestTof, m_maxNumEvents, m_numBadEvents, m_numErrorEvents, m_numevents2write, m_numGoodEvents, m_numIgnoredEvents, m_numPixel, m_numPulses, m_pixelid2exam, m_pixelmap, m_shortestTof, m_useDBOutput, m_usingMappingFile, m_vecEventIndex, m_vecLogPixelID, Mantid::DataHandling::MAX_TOF_UINT32, Mantid::Kernel::Logger::notice(), PARALLEL_CRITICAL, Mantid::DataHandling::DasEvent::pid, pulsetimes, spectraLoadMap, Mantid::DataHandling::DasEvent::tof, Mantid::DataHandling::TOF_CONVERSION, and Mantid::Kernel::Logger::warning().
Referenced by filterEvents().
findRunFrequency()
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::findRunFrequency () private
Use pulse index/ event index to find out the frequency of instrument running.
Definition at line 2037 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, m_maxNumEvents, m_vecEventIndex, and Mantid::Kernel::Logger::notice().
Referenced by exec().
init()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::init () override private virtual
Initialisation code.
Initialize the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 252 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), Mantid::DataHandling::EVENT_EXTS, Mantid::DataHandling::EVENT_PARAM(), Mantid::Kernel::IS_NOT_DEFAULT, Mantid::API::FileProperty::Load, Mantid::DataHandling::MAP_PARAM(), Mantid::DataHandling::NUM_EXT, Mantid::API::PropertyMode::Optional, Mantid::API::FileProperty::OptionalLoad, Mantid::DataHandling::OUT_PARAM(), Mantid::Kernel::Direction::Output, Mantid::DataHandling::PID_PARAM(), Mantid::DataHandling::PULSE_EXTS, Mantid::DataHandling::PULSEID_PARAM(), and Mantid::Kernel::IPropertyManager::setPropertySettings().
loadPixelMap()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::loadPixelMap (const std::string & filename) private
Load a pixel mapping file.
Parameters
filename :: Path to file.
Definition at line 2105 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::g_log, Mantid::Kernel::BinaryFile< T >::getNumElements(), Mantid::Kernel::Logger::information(), Mantid::Kernel::BinaryFile< T >::loadAllIntoVector(), m_numPixel, m_pixelmap, m_usingMappingFile, and Mantid::Kernel::Logger::warning().
Referenced by setupOutputEventWorkspace().
name()
const std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::name () const inline override virtual
Algorithm's name.
Implements Mantid::API::Algorithm.
Definition at line 86 of file FilterEventsByLogValuePreNexus.h.
openEventFile()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::openEventFile (const std::string & filename) private
Open an event file.
Parameters
filename :: file to open.
Definition at line 2147 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), m_eventFile, m_firstEvent, m_maxNumEvents, and m_numEvents.
Referenced by exec().
padOutEmptyPixels()
size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::padOutEmptyPixels (const DataObjects::EventWorkspace_sptr & eventws) private
Pad out empty pixel.
Set up instrument related parameters such as detector map and etc for 'eventws' and create a pixel-spectrum map We want to pad out empty pixels: monitor.
Definition at line 1978 of file FilterEventsByLogValuePreNexus.cpp.
References m_detid_max, m_loadOnlySomeSpectra, m_pixelToWkspindex, m_progress, and spectraLoadMap.
Referenced by filterEvents().
processEventLogs()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::processEventLogs () private
Process imbed logs (marked by bad pixel IDs) (1) Add special event log to workspace log (2) (Optionally) do statistic to each pixel (3) (Optionally) write out information.
Definition at line 576 of file FilterEventsByLogValuePreNexus.cpp.
References addToWorkspaceLog(), doStatToEventLog(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::Kernel::IPropertyManager::setProperty(), wrongdetid_pulsetimes, wrongdetidmap, and wrongdetids.
Referenced by exec().
processProperties()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::processProperties () private
Process properties.
Process input properties.
Definition at line 409 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::DataHandling::EVENT_PARAM(), Mantid::DataHandling::exists(), Mantid::API::g_log, Mantid::DataHandling::generatePulseidName(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), m_corretctTOF, m_dbPixelID, m_eventFileName, m_examEventLog, m_freqHz, m_functionMode, m_loadOnlySomeSpectra, m_numevents2write, m_pixelid2exam, m_pulseIDFileName, m_spectraList, m_throwError, m_useDBOutput, m_vecLogPixelID, m_vecLogPixelTag, Mantid::DataHandling::PID_PARAM(), Mantid::DataHandling::PULSEID_PARAM(), spectraLoadMap, and Mantid::Kernel::Logger::warning().
Referenced by exec().
procEvents()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEvents (DataObjects::EventWorkspace_sptr & workspace) private
Process the event file properly.
Parameters
workspace :: EventWorkspace to write to.
Pointer to the vector of events
Bare array of arrays of pointers to the EventVectors
How many threads will we use?
Definition at line 758 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::ISpectrum::addDetectorID(), Mantid::DataObjects::EventList::clear(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::DEFAULT_BLOCK_SIZE, Mantid::API::g_log, Mantid::DataObjects::EventList::getEvents(), Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), m_detid_max, m_eventFile, m_firstEvent, m_functionMode, m_loadOnlySomeSpectra, m_longestTof, m_maxNumEvents, m_numBadEvents, m_numErrorEvents, m_numGoodEvents, m_numIgnoredEvents, m_numWrongdetidEvents, m_parallelProcessing, m_pixelToWkspindex, m_progress, m_shortestTof, m_spectraList, Mantid::DataHandling::MAX_TOF_UINT32, Mantid::Kernel::Logger::notice(), Mantid::DataHandling::numEvents(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_GET_MAX_THREADS, PARALLEL_START_INTERRUPT_REGION, PARALLEL_THREAD_NUMBER, PRAGMA_OMP, procEventsLinear(), Mantid::DataObjects::EventList::reserve(), setProtonCharge(), Mantid::API::ISpectrum::setSpectrumNo(), spectraLoadMap, workspace, wrongdetid_pulsetimes, wrongdetidmap, and wrongdetids.
Referenced by exec().
procEventsLinear()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::procEventsLinear (DataObjects::EventWorkspace_sptr & workspace, std::vector< Types::Event::TofEvent > ** arrayOfVectors, DasEvent * event_buffer, size_t current_event_buffer_size, size_t fileOffset) private
Linear-version of the procedure to process the event file properly.
Parameters
workspace :: EventWorkspace to write to.
arrayOfVectors :: For speed up: this is an array, of size m_detid_max+1, where the index is a pixel ID, and the value is a pointer to the vector<tofEvent> in the given EventList.
event_buffer :: The buffer containing the DAS events
current_event_buffer_size :: The length of the given DAS buffer
fileOffset :: Value for an offset into the binary file
Definition at line 1044 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::DataHandling::ERROR_PID, Mantid::API::g_log, m_detid_max, m_examEventLog, m_istep, m_loadOnlySomeSpectra, m_longestTof, m_maxNumEvents, m_numBadEvents, m_numErrorEvents, m_numevents2write, m_numGoodEvents, m_numIgnoredEvents, m_numPixel, m_numPulses, m_numWrongdetidEvents, m_pixelid2exam, m_pixelmap, m_shortestTof, m_usingMappingFile, m_vecEventIndex, Mantid::DataHandling::MAX_TOF_UINT32, Mantid::Kernel::Logger::notice(), PARALLEL_CRITICAL, Mantid::DataHandling::DasEvent::pid, pulsetimes, spectraLoadMap, Mantid::DataHandling::DasEvent::tof, Mantid::DataHandling::TOF_CONVERSION, Mantid::Kernel::Logger::warning(), wrongdetid_pulsetimes, wrongdetid_tofs, wrongdetidmap, and wrongdetids.
Referenced by procEvents().
readPulseidFile()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::readPulseidFile (const std::string & filename, const bool throwError) private
Read a pulse ID file.
Parameters
filename :: file to load.
throwError :: Flag to trigger error throwing instead of just logging
Definition at line 2177 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::DataHandling::CURRENT_CONVERSION, Mantid::API::g_log, Mantid::Kernel::BinaryFile< T >::getNumElements(), Mantid::Kernel::Logger::information(), Mantid::Kernel::BinaryFile< T >::loadAll(), m_numPulses, m_protonCharge, m_protonChargeTot, m_pulseTimesIncreasing, m_vecEventIndex, pulsetimes, and Mantid::Kernel::Logger::warning().
Referenced by exec().
runLoadInstrument()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::runLoadInstrument (const std::string & eventfilename, const API::MatrixWorkspace_sptr & localWorkspace) private
Load the instrument geometry File.
Parameters
eventfilename :: Used to pick the instrument.
localWorkspace :: MatrixWorkspace in which to put the instrument geometry
Definition at line 719 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::DataHandling::EVENT_EXTS, and Mantid::DataHandling::NUM_EXT.
Referenced by setupOutputEventWorkspace().
setProtonCharge()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::setProtonCharge (DataObjects::EventWorkspace_sptr & workspace) private
Add a sample environment log for the proton chage (charge of the pulse in picoCoulombs) and set the scalar value (total proton charge, microAmps*hours, on the sample)
Parameters
workspace :: Event workspace to set the proton charge on
Definition at line 2080 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::LogManager::addLogData(), Mantid::Kernel::TimeSeriesProperty< TYPE >::addValues(), Mantid::API::g_log, Mantid::API::Run::getProtonCharge(), Mantid::Kernel::Logger::information(), Mantid::API::Run::integrateProtonCharge(), m_protonCharge, pulsetimes, Mantid::Kernel::Property::setUnits(), and workspace.
Referenced by filterEvents(), and procEvents().
setupOutputEventWorkspace()
DataObjects::EventWorkspace_sptr Mantid::DataHandling::FilterEventsByLogValuePreNexus::setupOutputEventWorkspace () private
Create, initialize and set up output EventWrokspace.
Create, initialize and set up output EventWorkspace.
Definition at line 509 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::g_log, Mantid::DataHandling::generateMappingfileName(), Mantid::API::Algorithm::getPropertyValue(), Mantid::DataHandling::getRunnumber(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), loadPixelMap(), m_eventFileName, m_numPulses, m_progress, m_spectraList, Mantid::DataHandling::MAP_PARAM(), Mantid::Kernel::Logger::notice(), pulsetimes, runLoadInstrument(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
setupPixelSpectrumMap()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::setupPixelSpectrumMap (const DataObjects::EventWorkspace_sptr & eventws) private
Set up spectrum/detector ID map inside a workspace.
Set up instrument related parameters such as detector map and etc for 'eventws' create a pixel-spectrum map.
Definition at line 2013 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::API::ISpectrum::addDetectorID(), m_loadOnlySomeSpectra, m_pixelToWkspindex, Mantid::API::ISpectrum::setSpectrumNo(), and spectraLoadMap.
Referenced by filterEvents().
summary()
const std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 94 of file FilterEventsByLogValuePreNexus.h.
unmaskVetoEventIndexes()
void Mantid::DataHandling::FilterEventsByLogValuePreNexus::unmaskVetoEventIndexes () private
Correct wrong event indexes with pulse.
Correct wrong event indexes.
Definition at line 1291 of file FilterEventsByLogValuePreNexus.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, m_numEvents, m_vecEventIndex, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, and Mantid::DataHandling::VETOFLAG().
Referenced by exec().
version()
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::version () const inline override virtual
Algorithm's version.
Implements Mantid::API::Algorithm.
Definition at line 88 of file FilterEventsByLogValuePreNexus.h.
Member Data Documentation
m_corretctTOF
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_corretctTOF private
Definition at line 265 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), and processProperties().
m_dbPixelID
int64_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_dbPixelID private
Definition at line 262 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), and processProperties().
m_detid_max
Mantid::detid_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_detid_max private
The maximum detector ID possible.
Definition at line 179 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), padOutEmptyPixels(), procEvents(), and procEventsLinear().
m_eventFile
std::unique_ptr<Mantid::Kernel::BinaryFile<DasEvent> > Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_eventFile private
Handles loading from the event file.
Definition at line 182 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), openEventFile(), and procEvents().
m_eventFileName
std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_eventFileName private
Event file.
Definition at line 230 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), processProperties(), and setupOutputEventWorkspace().
m_examEventLog
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_examEventLog private
Flag for examine event (log)
Definition at line 241 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), processProperties(), and procEventsLinear().
m_firstEvent
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_firstEvent private
The first event to load (count from zero)
Definition at line 201 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), openEventFile(), and procEvents().
m_freqHz
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_freqHz private
Accelerator operation frequency.
Definition at line 258 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), and processProperties().
m_functionMode
std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_functionMode private
Function mode.
Definition at line 238 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), processProperties(), and procEvents().
m_istep
int64_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_istep private
Definition at line 260 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), filterEventsLinear(), and procEventsLinear().
m_loadOnlySomeSpectra
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_loadOnlySomeSpectra private
For loading only some spectra.
Definition at line 208 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), padOutEmptyPixels(), processProperties(), procEvents(), procEventsLinear(), and setupPixelSpectrumMap().
m_localWorkspace
DataObjects::EventWorkspace_sptr Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_localWorkspace private
Definition at line 161 of file FilterEventsByLogValuePreNexus.h.
Referenced by addToWorkspaceLog(), exec(), filterEvents(), and filterEventsLinear().
m_localWorkspaceBA
DataObjects::EventWorkspace_sptr Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_localWorkspaceBA private
Output EventWorkspace for filtered event B->A.
Definition at line 255 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), and filterEvents().
m_longestTof
double Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_longestTof private
Longest TOF limit.
Definition at line 213 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), procEvents(), and procEventsLinear().
m_maxNumEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_maxNumEvents private
Number of events to load.
Definition at line 202 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), findRunFrequency(), openEventFile(), procEvents(), and procEventsLinear().
m_numBadEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numBadEvents private
The number of bad events.
Part of error events
Definition at line 189 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), procEvents(), and procEventsLinear().
m_numErrorEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numErrorEvents private
The number of error events encountered.
Definition at line 188 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), procEvents(), and procEventsLinear().
m_numEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numEvents private
The number of events in the file.
Definition at line 183 of file FilterEventsByLogValuePreNexus.h.
Referenced by openEventFile(), and unmaskVetoEventIndexes().
m_numevents2write
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numevents2write private
Number of events to write out.
Definition at line 247 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), processProperties(), and procEventsLinear().
m_numGoodEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numGoodEvents private
The number of good events loaded.
Definition at line 187 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), procEvents(), and procEventsLinear().
m_numIgnoredEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numIgnoredEvents private
the number of events that were ignored (not loaded) because, e.g.
of only loading some spectra.
Definition at line 200 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), procEvents(), and procEventsLinear().
m_numPixel
uint32_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numPixel private
the number of pixels
Definition at line 185 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), loadPixelMap(), and procEventsLinear().
m_numPulses
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numPulses private
the number of pulses
Definition at line 184 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), filterEventsLinear(), procEventsLinear(), readPulseidFile(), and setupOutputEventWorkspace().
m_numWrongdetidEvents
std::size_t Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_numWrongdetidEvents private
The number of events with wrong.
Definition at line 191 of file FilterEventsByLogValuePreNexus.h.
Referenced by procEvents(), and procEventsLinear().
m_parallelProcessing
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_parallelProcessing private
Flag to allow for parallel loading.
Definition at line 218 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), and procEvents().
m_pixelid2exam
int Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_pixelid2exam private
Pixel ID to exam.
Definition at line 244 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), processProperties(), and procEventsLinear().
m_pixelmap
std::vector<PixelType> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_pixelmap private
Map between the DAS pixel IDs and our pixel IDs, used while loading.
Definition at line 176 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), loadPixelMap(), and procEventsLinear().
m_pixelToWkspindex
std::vector<std::size_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_pixelToWkspindex private
The value of the vector is the workspace index.
The index into it is the pixel ID from DAS
Definition at line 174 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), padOutEmptyPixels(), procEvents(), and setupPixelSpectrumMap().
m_progress
std::unique_ptr<Mantid::API::Progress> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_progress = nullptr private
Definition at line 159 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), filterEvents(), padOutEmptyPixels(), procEvents(), and setupOutputEventWorkspace().
m_protonCharge
std::vector<double> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_protonCharge private
The proton charge on a pulse by pulse basis.
Definition at line 169 of file FilterEventsByLogValuePreNexus.h.
Referenced by readPulseidFile(), and setProtonCharge().
m_protonChargeTot
double Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_protonChargeTot private
The total proton charge for the run.
Definition at line 171 of file FilterEventsByLogValuePreNexus.h.
Referenced by readPulseidFile().
m_pulseIDFileName
std::string Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_pulseIDFileName private
Pulse ID file.
Definition at line 233 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), and processProperties().
m_pulseTimesIncreasing
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_pulseTimesIncreasing private
Whether or not the pulse times are sorted in increasing order.
Definition at line 221 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), and readPulseidFile().
m_shortestTof
double Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_shortestTof private
Shortest TOF limit.
Definition at line 215 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), filterEventsLinear(), procEvents(), and procEventsLinear().
m_spectraList
std::vector<int64_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_spectraList private
the list of Spectra
Definition at line 162 of file FilterEventsByLogValuePreNexus.h.
Referenced by processProperties(), procEvents(), and setupOutputEventWorkspace().
m_throwError
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_throwError private
Throw error with bad pulse ID.
Definition at line 235 of file FilterEventsByLogValuePreNexus.h.
Referenced by exec(), and processProperties().
m_useDBOutput
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_useDBOutput private
Definition at line 263 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), and processProperties().
m_usingMappingFile
bool Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_usingMappingFile private
Set to true if a valid Mapping file was provided.
Definition at line 205 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), loadPixelMap(), and procEventsLinear().
m_vecEventIndex
std::vector<uint64_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_vecEventIndex private
The index of the first event in each pulse.
Definition at line 167 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), findRunFrequency(), procEventsLinear(), readPulseidFile(), and unmaskVetoEventIndexes().
m_vecLogPixelID
std::vector<int> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_vecLogPixelID private
Log pixel IDs for filtering.
Definition at line 250 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), and processProperties().
m_vecLogPixelTag
std::vector<std::string> Mantid::DataHandling::FilterEventsByLogValuePreNexus::m_vecLogPixelTag private
Log pixel Tags for filtering.
Definition at line 252 of file FilterEventsByLogValuePreNexus.h.
Referenced by processProperties().
mSEids
std::vector<detid_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::mSEids private
sample environment event
Definition at line 224 of file FilterEventsByLogValuePreNexus.h.
mSEmap
std::map<size_t, detid_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::mSEmap private
Definition at line 225 of file FilterEventsByLogValuePreNexus.h.
mSEpulseids
std::vector<std::vector<int64_t> > Mantid::DataHandling::FilterEventsByLogValuePreNexus::mSEpulseids private
Definition at line 226 of file FilterEventsByLogValuePreNexus.h.
mSEtofs
std::vector<std::vector<double> > Mantid::DataHandling::FilterEventsByLogValuePreNexus::mSEtofs private
Definition at line 227 of file FilterEventsByLogValuePreNexus.h.
pulsetimes
std::vector<Types::Core::DateAndTime> Mantid::DataHandling::FilterEventsByLogValuePreNexus::pulsetimes private
The times for each pulse.
Definition at line 165 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), procEventsLinear(), readPulseidFile(), setProtonCharge(), and setupOutputEventWorkspace().
spectraLoadMap
std::map<int64_t, bool> Mantid::DataHandling::FilterEventsByLogValuePreNexus::spectraLoadMap private
Handle to the loaded spectra map.
Definition at line 210 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEventsLinear(), padOutEmptyPixels(), processProperties(), procEvents(), procEventsLinear(), and setupPixelSpectrumMap().
wrongdetid_pulsetimes
std::vector<std::vector<Types::Core::DateAndTime> > Mantid::DataHandling::FilterEventsByLogValuePreNexus::wrongdetid_pulsetimes private
Definition at line 195 of file FilterEventsByLogValuePreNexus.h.
Referenced by addToWorkspaceLog(), doStatToEventLog(), filterEvents(), processEventLogs(), procEvents(), and procEventsLinear().
wrongdetid_tofs
std::vector<std::vector<double> > Mantid::DataHandling::FilterEventsByLogValuePreNexus::wrongdetid_tofs private
Definition at line 196 of file FilterEventsByLogValuePreNexus.h.
Referenced by addToWorkspaceLog(), doStatToEventLog(), and procEventsLinear().
wrongdetidmap
std::map<PixelType, size_t> Mantid::DataHandling::FilterEventsByLogValuePreNexus::wrongdetidmap private
Definition at line 194 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), processEventLogs(), procEvents(), and procEventsLinear().
wrongdetids
std::set<PixelType> Mantid::DataHandling::FilterEventsByLogValuePreNexus::wrongdetids private
detector IDs. Part of error events.
set of all wrong detector IDs
Definition at line 193 of file FilterEventsByLogValuePreNexus.h.
Referenced by filterEvents(), processEventLogs(), procEvents(), and procEventsLinear().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/FilterEventsByLogValuePreNexus.h
Framework/DataHandling/src/FilterEventsByLogValuePreNexus.cpp