Mantid: Mantid::API::IFunction1D Class Reference
Mantid::API::IFunction1D Class Reference abstract
This is a specialization of IFunction for functions of one real argument.
#include <IFunction1D.h>
Public Member Functions
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
virtual void function1D (double *out, const double *xValues, const size_t nData) const =0
Function you want to fit to.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
virtual void functionDeriv1D (Jacobian *jacobian, const double *xValues, const size_t nData)
Derivatives of function with respect to active parameters.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
virtual void setParameter (size_t, const double &value, bool explicitlySet=true)=0
Set i-th parameter.
virtual void setParameterDescription (size_t, const std::string &description)=0
Set i-th parameter description.
virtual double getParameter (size_t i) const =0
Get i-th parameter.
virtual void setParameter (const std::string &name, const double &value, bool explicitlySet=true)=0
Set parameter by name.
virtual void setParameterDescription (const std::string &name, const std::string &description)=0
Set description of parameter by name.
virtual double getParameter (const std::string &name) const =0
Get parameter by name.
virtual bool hasParameter (const std::string &name) const =0
Check if function has a parameter with this name.
virtual size_t nParams () const =0
Total number of parameters.
virtual size_t parameterIndex (const std::string &name) const =0
Returns the index of parameter name.
virtual std::string parameterName (size_t i) const =0
Returns the name of parameter i.
virtual std::string parameterDescription (size_t i) const =0
Returns the description of parameter i.
virtual bool isExplicitlySet (size_t i) const =0
Checks if a parameter has been set explicitly.
virtual double getError (size_t i) const =0
Get the fitting error for a parameter.
virtual double getError (const std::string &name) const =0
Get the fitting error for a parameter by name.
virtual void setError (size_t i, double err)=0
Set the fitting error for a parameter.
virtual void setError (const std::string &name, double err)=0
Set the fitting error for a parameter by name.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
virtual size_t getParameterIndex (const ParameterReference &ref) const =0
Return parameter index from a parameter reference.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual void setAttribute (const std::string &name, const Attribute &)
Set a value to attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setParameterStatus (size_t i, ParameterStatus status)=0
Change status of parameter.
virtual ParameterStatus getParameterStatus (size_t i) const =0
Get status of parameter.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Protected Types
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Protected Member Functions
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
virtual void declareParameter (const std::string &name, double initValue=0, const std::string &description="")=0
Declare a new parameter.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Static Protected Attributes
static Kernel::Logger g_log
Logger instance.
Friends
class CurveFitting::Algorithms::Fit
Making a friend.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
This is a specialization of IFunction for functions of one real argument.
It uses FunctionDomain1D as a domain. Implement function1D(...) method in a concrete function. Implement functionDeriv1D to use analytical derivatives.
Author
Roman Tolchenov, Tessella Support Services plc
Date
16/10/2009
Definition at line 43 of file IFunction1D.h.
Member Typedef Documentation
Function1DMethod
template<typename FunctionType > using Mantid::API::IFunction1D::Function1DMethod = void (FunctionType::*)(double *, const double *, const size_t) const protected
Definition at line 63 of file IFunction1D.h.
Member Function Documentation
calcNumericalDerivative1D()
template<typename EvaluationMethod > void Mantid::API::IFunction1D::calcNumericalDerivative1D (Jacobian * jacobian, EvaluationMethod func1D, const double * xValues, const size_t nData) protected
Calculate a numerical derivative for the 1D data.
Definition at line 16 of file IFunction1D.hxx.
References Mantid::API::IFunction::activeParameter(), Mantid::API::IFunction::applyTies(), Mantid::API::IFunction::calculateStepSize(), Mantid::API::IFunction::isActive(), Mantid::API::IFunction::nParams(), Mantid::API::Jacobian::set(), and Mantid::API::IFunction::setActiveParameter().
Referenced by functionDeriv1D(), and Mantid::API::IPeakFunction::functionDerivLocal().
derivative()
void Mantid::API::IFunction1D::derivative (const FunctionDomain & domain, FunctionValues & values, const size_t order = 1) const virtual
Definition at line 65 of file IFunction1D.cpp.
References derivative1D(), and Mantid::API::FunctionValues::getPointerToCalculated().
Referenced by Mantid::CurveFitting::Functions::ChudleyElliotSQE::functionDeriv1D(), Mantid::CurveFitting::Functions::FickDiffusionSQE::functionDeriv1D(), Mantid::CurveFitting::Functions::HallRossSQE::functionDeriv1D(), and Mantid::CurveFitting::Functions::TeixeiraWaterSQE::functionDeriv1D().
derivative1D()
void Mantid::API::IFunction1D::derivative1D (double * out, const double * xValues, const size_t nData, const size_t order) const virtual
Function to calculate the derivatives of the data set.
Reimplemented in Mantid::CurveFitting::Functions::BSpline, and Mantid::CurveFitting::Functions::CubicSpline.
Definition at line 74 of file IFunction1D.cpp.
References UNUSED_ARG.
Referenced by derivative().
function()
void Mantid::API::IFunction1D::function (const FunctionDomain & domain, FunctionValues & values) const override virtual
Evaluates the function for all arguments in the domain.
Parameters
domain :: Provides arguments for the function.
values :: A buffer to store the function values. It must be large enogh to store domain.size() values.
Implements Mantid::API::IFunction.
Reimplemented in Mantid::API::IPeakFunction, Mantid::API::IPowderDiffPeakFunction, Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt, and Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt.
Definition at line 38 of file IFunction1D.cpp.
References Mantid::API::FunctionValues::getPointerToCalculated(), and histogram1D().
Referenced by Mantid::API::IPeakFunction::function().
function1D()
virtual void Mantid::API::IFunction1D::function1D (double * out, const double * xValues, const size_t nData) const pure virtual
Function you want to fit to.
Implemented in Mantid::CurveFitting::Functions::GramCharlier, Mantid::CurveFitting::Functions::LogNormal, Mantid::CurveFitting::Functions::Quadratic, Mantid::CurveFitting::Functions::StretchExp, Mantid::API::IPeakFunction, Mantid::Crystal::PeakHKLErrors, Mantid::Crystal::SCDPanelErrors, Mantid::CurveFitting::Functions::Abragam, Mantid::CurveFitting::Functions::ActivationK, Mantid::CurveFitting::Functions::ActivationmeV, Mantid::CurveFitting::Functions::BackToBackExponential, Mantid::CurveFitting::Functions::BivariateNormal, Mantid::CurveFitting::Functions::BSpline, Mantid::CurveFitting::Functions::Chebyshev, Mantid::CurveFitting::Functions::ChudleyElliotSQE, Mantid::CurveFitting::Functions::ComptonPeakProfile, Mantid::CurveFitting::Functions::ComptonProfile, Mantid::CurveFitting::Functions::ConvTempCorrection, Mantid::CurveFitting::Functions::CriticalPeakRelaxationRate, Mantid::CurveFitting::Functions::CrystalFieldHeatCapacityBase, Mantid::CurveFitting::Functions::CrystalFieldHeatCapacity, Mantid::CurveFitting::Functions::CrystalFieldMagnetisationBase, Mantid::CurveFitting::Functions::CrystalFieldMagnetisation, Mantid::CurveFitting::Functions::CrystalFieldMomentBase, Mantid::CurveFitting::Functions::CrystalFieldMoment, Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityBase, Mantid::CurveFitting::Functions::CrystalFieldSusceptibility, Mantid::CurveFitting::Functions::CubicSpline, Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong, Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot, Mantid::CurveFitting::Functions::DeltaFunction, Mantid::CurveFitting::Functions::DynamicKuboToyabe, Mantid::CurveFitting::Functions::EndErfc, Mantid::CurveFitting::Functions::ExpDecay, Mantid::CurveFitting::Functions::ExpDecayMuon, Mantid::CurveFitting::Functions::ExpDecayOsc, Mantid::CurveFitting::Functions::FickDiffusionSQE, Mantid::CurveFitting::Functions::FlatBackground, Mantid::CurveFitting::Functions::FullprofPolynomial, Mantid::CurveFitting::Functions::GausDecay, Mantid::CurveFitting::Functions::GausOsc, Mantid::CurveFitting::Functions::HallRossSQE, Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle, Mantid::CurveFitting::Functions::InelasticDiffSphere, Mantid::CurveFitting::Functions::InelasticIsoRotDiff, Mantid::CurveFitting::Functions::Keren, Mantid::CurveFitting::Functions::LinearBackground, Mantid::CurveFitting::Functions::LogNormal, Mantid::CurveFitting::Functions::MagneticOrderParameter, Mantid::CurveFitting::Functions::Meier, Mantid::CurveFitting::Functions::MuonFInteraction, Mantid::CurveFitting::Functions::MuoniumDecouplingCurve, Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt, Mantid::CurveFitting::Functions::PeakParameterFunction, Mantid::CurveFitting::Functions::Polynomial, Mantid::CurveFitting::Functions::PowerLaw, Mantid::CurveFitting::Functions::ProductLinearExp, Mantid::CurveFitting::Functions::ProductQuadraticExp, Mantid::CurveFitting::Functions::Quadratic, Mantid::CurveFitting::Functions::ReflectivityMulf, Mantid::CurveFitting::Functions::Resolution, Mantid::CurveFitting::Functions::SmoothTransition, Mantid::CurveFitting::Functions::StaticKuboToyabe, Mantid::CurveFitting::Functions::StaticKuboToyabeTimesExpDecay, Mantid::CurveFitting::Functions::StaticKuboToyabeTimesGausDecay, Mantid::CurveFitting::Functions::StaticKuboToyabeTimesStretchExp, Mantid::CurveFitting::Functions::StretchExp, Mantid::CurveFitting::Functions::StretchExpMuon, Mantid::CurveFitting::Functions::TabulatedFunction, Mantid::CurveFitting::Functions::TeixeiraWaterSQE, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpAlpha, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpBeta, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpSigma, Mantid::CurveFitting::Functions::ThermalNeutronDtoTOFFunction, Mantid::CurveFitting::Functions::UserFunction, Mantid::CurveFitting::Functions::VesuvioResolution, Mantid::PythonInterface::IFunction1DAdapter, Mantid::PythonInterface::IPeakFunctionAdapter, Mantid::FrameworkTestHelpers::FunctionChangesNParams, Mantid::FrameworkTestHelpers::MultiDomainFunctionTest_Function, and Mantid::Crystal::SCDCalibratePanels2ObjFunc.
Referenced by functionDeriv1D().
functionDeriv()
void Mantid::API::IFunction1D::functionDeriv (const FunctionDomain & domain, Jacobian & jacobian) override virtual
Derivatives of function with respect to active parameters.
Base class implementation calculates the derivatives numerically.
Parameters
domain :: The domain of the function
jacobian :: A Jacobian matrix. It is expected to have dimensions of domain.size() by nParams().
Reimplemented from Mantid::API::IFunction.
Reimplemented in Mantid::CurveFitting::Functions::Abragam, Mantid::CurveFitting::Functions::Bk2BkExpConvPV, Mantid::CurveFitting::Functions::DynamicKuboToyabe, Mantid::CurveFitting::Functions::IkedaCarpenterPV, Mantid::CurveFitting::Functions::PeakParameterFunction, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpAlpha, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpBeta, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt, Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpSigma, and Mantid::CurveFitting::Functions::UserFunction.
Definition at line 52 of file IFunction1D.cpp.
References functionDeriv1D(), and histogramDerivative1D().
functionDeriv1D()
void Mantid::API::IFunction1D::functionDeriv1D (Jacobian * jacobian, const double * xValues, const size_t nData) virtual
Derivatives of function with respect to active parameters.
Reimplemented in Mantid::CurveFitting::Functions::BackToBackExponential, Mantid::CurveFitting::Functions::LogNormal, Mantid::CurveFitting::Functions::Quadratic, Mantid::CurveFitting::Functions::StretchExp, Mantid::Crystal::SCDPanelErrors, Mantid::CurveFitting::Functions::ActivationK, Mantid::CurveFitting::Functions::ActivationmeV, Mantid::CurveFitting::Functions::BivariateNormal, Mantid::CurveFitting::Functions::Chebyshev, Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong, Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot, Mantid::CurveFitting::Functions::DeltaFunction, Mantid::CurveFitting::Functions::DynamicKuboToyabe, Mantid::CurveFitting::Functions::ExpDecay, Mantid::CurveFitting::Functions::ExpDecayMuon, Mantid::CurveFitting::Functions::ExpDecayOsc, Mantid::CurveFitting::Functions::FlatBackground, Mantid::CurveFitting::Functions::FullprofPolynomial, Mantid::CurveFitting::Functions::GausDecay, Mantid::CurveFitting::Functions::GausOsc, Mantid::CurveFitting::Functions::LinearBackground, Mantid::CurveFitting::Functions::LogNormal, Mantid::CurveFitting::Functions::MagneticOrderParameter, Mantid::CurveFitting::Functions::MuoniumDecouplingCurve, Mantid::CurveFitting::Functions::Polynomial, Mantid::CurveFitting::Functions::PowerLaw, Mantid::CurveFitting::Functions::ProductLinearExp, Mantid::CurveFitting::Functions::ProductQuadraticExp, Mantid::CurveFitting::Functions::Quadratic, Mantid::CurveFitting::Functions::Resolution, Mantid::CurveFitting::Functions::SmoothTransition, Mantid::CurveFitting::Functions::StretchExp, Mantid::CurveFitting::Functions::TabulatedFunction, Mantid::CurveFitting::Functions::ThermalNeutronDtoTOFFunction, Mantid::PythonInterface::IFunction1DAdapter, Mantid::PythonInterface::IPeakFunctionAdapter, Mantid::API::IPeakFunction, Mantid::CurveFitting::Functions::ChudleyElliotSQE, Mantid::CurveFitting::Functions::FickDiffusionSQE, Mantid::CurveFitting::Functions::HallRossSQE, Mantid::CurveFitting::Functions::TeixeiraWaterSQE, Mantid::Crystal::PeakHKLErrors, Mantid::FrameworkTestHelpers::FunctionChangesNParams, and Mantid::FrameworkTestHelpers::MultiDomainFunctionTest_Function.
Definition at line 82 of file IFunction1D.cpp.
References calcNumericalDerivative1D(), and function1D().
Referenced by functionDeriv(), and Mantid::PythonInterface::IFunction1DAdapter::functionDeriv1D().
histogram1D()
void Mantid::API::IFunction1D::histogram1D (double * out, double left, const double * right, const size_t nBins) const protected virtual
Calculate histogram data for the given bin boundaries.
Parameters
out :: Output bin values (size == nBins) - integrals of the function inside each bin.
left :: The left-most bin boundary.
right :: A pointer to an array of successive right bin boundaries (size = nBins).
nBins :: Number of bins.
Reimplemented in Mantid::CurveFitting::Functions::FlatBackground, Mantid::CurveFitting::Functions::Gaussian, Mantid::CurveFitting::Functions::LinearBackground, and Mantid::CurveFitting::Functions::Lorentzian.
Definition at line 96 of file IFunction1D.cpp.
References left, right, and UNUSED_ARG.
Referenced by function().
histogramDerivative1D()
void Mantid::API::IFunction1D::histogramDerivative1D (Jacobian * jacobian, double left, const double * right, const size_t nBins) const protected virtual
Derivatives of the histogram1D with respect to active parameters.
Derivatives of the histogram.
Parameters
jacobian :: The output Jacobian.
left :: The left-most bin boundary.
right :: A pointer to an array of successive right bin boundaries (size = nBins).
nBins :: Number of bins.
Reimplemented in Mantid::CurveFitting::Functions::FlatBackground, Mantid::CurveFitting::Functions::Gaussian, Mantid::CurveFitting::Functions::LinearBackground, and Mantid::CurveFitting::Functions::Lorentzian.
Definition at line 110 of file IFunction1D.cpp.
References left, right, and UNUSED_ARG.
Referenced by functionDeriv().
Friends And Related Symbol Documentation
CurveFitting::Algorithms::Fit
friend class CurveFitting::Algorithms::Fit friend
Making a friend.
Definition at line 77 of file IFunction1D.h.
Member Data Documentation
g_log
Kernel::Logger Mantid::API::IFunction1D::g_log static protected
Logger instance.
init logger
Definition at line 74 of file IFunction1D.h.
Referenced by Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calHandEta(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calHandEta(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calOmega(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calOmega(), Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::CurveFitting::Functions::FunctionQDepends::extractQValues(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::function(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::function(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::CurveFitting::Functions::BivariateNormal::function1D(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::function1D(), Mantid::CurveFitting::Functions::InelasticDiffSphere::function1D(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::function1D(), Mantid::CurveFitting::Functions::BivariateNormal::functionDeriv1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::Crystal::PeakHKLErrors::getNewInstrument(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::getPeakParameter(), Mantid::CurveFitting::Functions::TabulatedFunction::setupData(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::setWorkspace(), and Mantid::CurveFitting::Functions::InelasticDiffSphere::setWorkspace().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IFunction1D.h
Framework/API/inc/MantidAPI/IFunction1D.hxx
Framework/API/src/IFunction1D.cpp