Mantid: ICat4::ns1__study Class Reference
ICat4::ns1__study Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__study ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * description
std::string * name
time_t * startDate
enum ns1__studyStatus * status
std::vector< ns1__studyInvestigation * > studyInvestigations
ns1__user * user
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1836 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__study()
ICat4::ns1__study::ns1__study () inline
Definition at line 1852 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__study::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13700 of file ICat4C.cpp.
References description, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__studyInvestigation(), startDate, status, studyInvestigations, and user.
Referenced by ICat4::soap_in_ns1__study(), ICat4::soap_new_req_ns1__study(), and ICat4::soap_new_set_ns1__study().
soap_get()
void * ICat4::ns1__study::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13881 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__study().
soap_in()
void * ICat4::ns1__study::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13761 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__study().
Referenced by ICat4::soap_in_ns1__study().
soap_out()
int ICat4::ns1__study::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13726 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__study().
Referenced by soap_put().
soap_put()
int ICat4::ns1__study::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13874 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__study.
soap_serialize()
void ICat4::ns1__study::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 13712 of file ICat4C.cpp.
References description, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__studyStatus(), ICat4::soap_serialize_PointerTons1__user(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__studyInvestigation(), startDate, status, studyInvestigations, and user.
Referenced by ICat4::soap_serialize_PointerTons1__shift().
soap_type()
int ICat4::ns1__study::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1845 of file ICat4Stub.h.
Member Data Documentation
description
std::string* ICat4::ns1__study::description
Definition at line 1838 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__study::name
Definition at line 1839 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
startDate
time_t* ICat4::ns1__study::startDate
Definition at line 1840 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
status
enum ns1__studyStatus* ICat4::ns1__study::status
Definition at line 1841 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
studyInvestigations
std::vector<ns1__studyInvestigation *> ICat4::ns1__study::studyInvestigations
Definition at line 1842 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
user
ns1__user* ICat4::ns1__study::user
Definition at line 1843 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp