Mantid: Mantid::DataHandling::LoadGroupXMLFile Class Reference
Mantid::DataHandling::LoadGroupXMLFile Class Reference
#include <LoadDetectorsGroupingFile.h>
Public Member Functions
const std::string & getDate () const
const std::string & getDescription () const
const std::map< int, std::vector< std::string > > & getGroupComponentsMap () const
Data structures to store XML to Group/Detector conversion map.
const std::map< int, std::vector< detid_t > > & getGroupDetectorsMap () const
const std::map< int, std::string > & getGroupNamesMap () const
const std::map< int, std::vector< int > > & getGroupSpectraMap () const
const std::string & getInstrumentName ()
bool isGivenDate () const
bool isGivenDescription () const
bool isGivenInstrumentName () const
LoadGroupXMLFile ()
void loadXMLFile (const std::string &xmlfilename)
void setDefaultStartingGroupID (int startgroupid)
Private Member Functions
void initializeXMLParser (const std::string &filename)
Initialize XML parser.
void parseXML ()
Parse XML.
Static Private Member Functions
static std::string getAttributeValueByName (Poco::XML::Node *pNode, const std::string &attributename, bool &found)
Get attribute value from an XML node.
Private Attributes
std::string m_date
Date in ISO 8601 for which this grouping is relevant.
std::string m_description
Grouping description. Empty if not specified.
std::map< int, std::vector< std::string > > m_groupComponentsMap
Data structures to store XML to Group/Detector conversion map.
std::map< int, std::vector< detid_t > > m_groupDetectorsMap
std::map< int, std::string > m_groupNamesMap
Map of group names.
std::map< int, std::vector< int > > m_groupSpectraMap
std::string m_instrumentName
Instrument name.
Poco::AutoPtr< Poco::XML::Document > m_pDoc
XML document loaded.
int m_startGroupID
bool m_userGiveDate
Whether date is given by user.
bool m_userGiveDescription
Whether description is given by user.
bool m_userGiveInstrument
User-define instrument name.
Detailed Description
Definition at line 97 of file LoadDetectorsGroupingFile.h.
Constructor & Destructor Documentation
LoadGroupXMLFile()
Mantid::DataHandling::LoadGroupXMLFile::LoadGroupXMLFile ()
Definition at line 364 of file LoadDetectorsGroupingFile.cpp.
Member Function Documentation
getAttributeValueByName()
std::string Mantid::DataHandling::LoadGroupXMLFile::getAttributeValueByName (Poco::XML::Node * pNode, const std::string & attributename, bool & found) static private
Get attribute value from an XML node.
Definition at line 553 of file LoadDetectorsGroupingFile.cpp.
References value.
Referenced by parseXML().
getDate()
const std::string & Mantid::DataHandling::LoadGroupXMLFile::getDate () const inline
Definition at line 107 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
getDescription()
const std::string & Mantid::DataHandling::LoadGroupXMLFile::getDescription () const inline
Definition at line 110 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
getGroupComponentsMap()
const std::map< int, std::vector< std::string > > & Mantid::DataHandling::LoadGroupXMLFile::getGroupComponentsMap () const inline
Data structures to store XML to Group/Detector conversion map.
Definition at line 114 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
getGroupDetectorsMap()
const std::map< int, std::vector< detid_t > > & Mantid::DataHandling::LoadGroupXMLFile::getGroupDetectorsMap () const inline
Definition at line 115 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), and Mantid::DataHandling::GroupDetectors2::processXMLFile().
getGroupNamesMap()
const std::map< int, std::string > & Mantid::DataHandling::LoadGroupXMLFile::getGroupNamesMap () const inline
Definition at line 118 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
getGroupSpectraMap()
const std::map< int, std::vector< int > > & Mantid::DataHandling::LoadGroupXMLFile::getGroupSpectraMap () const inline
Definition at line 116 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), and Mantid::DataHandling::GroupDetectors2::processXMLFile().
getInstrumentName()
const std::string & Mantid::DataHandling::LoadGroupXMLFile::getInstrumentName () inline
Definition at line 104 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
initializeXMLParser()
void Mantid::DataHandling::LoadGroupXMLFile::initializeXMLParser (const std::string & filename) private
Initialize XML parser.
Definition at line 378 of file LoadDetectorsGroupingFile.cpp.
References Mantid::Kernel::Strings::loadFile(), and m_pDoc.
Referenced by loadXMLFile().
isGivenDate()
bool Mantid::DataHandling::LoadGroupXMLFile::isGivenDate () const inline
Definition at line 108 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
isGivenDescription()
bool Mantid::DataHandling::LoadGroupXMLFile::isGivenDescription () const inline
Definition at line 111 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
isGivenInstrumentName()
bool Mantid::DataHandling::LoadGroupXMLFile::isGivenInstrumentName () const inline
Definition at line 105 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec().
loadXMLFile()
void Mantid::DataHandling::LoadGroupXMLFile::loadXMLFile (const std::string & xmlfilename)
Definition at line 369 of file LoadDetectorsGroupingFile.cpp.
References initializeXMLParser(), and parseXML().
Referenced by Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), and Mantid::DataHandling::GroupDetectors2::processXMLFile().
parseXML()
void Mantid::DataHandling::LoadGroupXMLFile::parseXML () private
Parse XML.
Definition at line 398 of file LoadDetectorsGroupingFile.cpp.
References getAttributeValueByName(), m_date, m_description, m_groupComponentsMap, m_groupDetectorsMap, m_groupNamesMap, m_groupSpectraMap, m_instrumentName, m_pDoc, m_startGroupID, m_userGiveDate, m_userGiveDescription, m_userGiveInstrument, name, Mantid::Kernel::Strings::parseRange(), and value.
Referenced by loadXMLFile().
setDefaultStartingGroupID()
void Mantid::DataHandling::LoadGroupXMLFile::setDefaultStartingGroupID (int startgroupid) inline
Definition at line 102 of file LoadDetectorsGroupingFile.h.
Referenced by Mantid::DataHandling::GroupDetectors2::processXMLFile().
Member Data Documentation
m_date
std::string Mantid::DataHandling::LoadGroupXMLFile::m_date private
Date in ISO 8601 for which this grouping is relevant.
Definition at line 127 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_description
std::string Mantid::DataHandling::LoadGroupXMLFile::m_description private
Grouping description. Empty if not specified.
Definition at line 132 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_groupComponentsMap
std::map<int, std::vector<std::string> > Mantid::DataHandling::LoadGroupXMLFile::m_groupComponentsMap private
Data structures to store XML to Group/Detector conversion map.
Definition at line 139 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_groupDetectorsMap
std::map<int, std::vector<detid_t> > Mantid::DataHandling::LoadGroupXMLFile::m_groupDetectorsMap private
Definition at line 140 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_groupNamesMap
std::map<int, std::string> Mantid::DataHandling::LoadGroupXMLFile::m_groupNamesMap private
Map of group names.
Definition at line 145 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_groupSpectraMap
std::map<int, std::vector<int> > Mantid::DataHandling::LoadGroupXMLFile::m_groupSpectraMap private
Definition at line 141 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_instrumentName
std::string Mantid::DataHandling::LoadGroupXMLFile::m_instrumentName private
Instrument name.
Definition at line 122 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_pDoc
Poco::AutoPtr<Poco::XML::Document> Mantid::DataHandling::LoadGroupXMLFile::m_pDoc private
XML document loaded.
Definition at line 137 of file LoadDetectorsGroupingFile.h.
Referenced by initializeXMLParser(), and parseXML().
m_startGroupID
int Mantid::DataHandling::LoadGroupXMLFile::m_startGroupID private
Definition at line 142 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_userGiveDate
bool Mantid::DataHandling::LoadGroupXMLFile::m_userGiveDate private
Whether date is given by user.
Definition at line 129 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_userGiveDescription
bool Mantid::DataHandling::LoadGroupXMLFile::m_userGiveDescription private
Whether description is given by user.
Definition at line 134 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
m_userGiveInstrument
bool Mantid::DataHandling::LoadGroupXMLFile::m_userGiveInstrument private
User-define instrument name.
Definition at line 124 of file LoadDetectorsGroupingFile.h.
Referenced by parseXML().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadDetectorsGroupingFile.h
Framework/DataHandling/src/LoadDetectorsGroupingFile.cpp