Mantid: ICat4::ns1__update Class Reference
ICat4::ns1__update Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__update ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__entityBaseBean * bean
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 777 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__update()
ICat4::ns1__update::ns1__update () inline
Definition at line 789 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__update::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19514 of file ICat4C.cpp.
References bean, sessionId, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::soap_in_ns1__update(), ICat4::soap_new_req_ns1__update(), and ICat4::soap_new_set_ns1__update().
soap_get()
void * ICat4::ns1__update::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19614 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__update().
soap_in()
void * ICat4::ns1__update::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19546 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__update().
Referenced by ICat4::soap_in_ns1__update().
soap_out()
int ICat4::ns1__update::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19530 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__update().
Referenced by soap_put().
soap_put()
int ICat4::ns1__update::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19607 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__update.
soap_serialize()
void ICat4::ns1__update::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 19521 of file ICat4C.cpp.
References bean, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTons1__entityBaseBean(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__createResponse().
soap_type()
int ICat4::ns1__update::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 782 of file ICat4Stub.h.
Member Data Documentation
bean
ns1__entityBaseBean* ICat4::ns1__update::bean
Definition at line 780 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
sessionId
std::string* ICat4::ns1__update::sessionId
Definition at line 779 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp