Mantid: Mantid::PythonInterface::std_function_from_python< R, Args > Struct Template Reference
Mantid::PythonInterface::std_function_from_python< R, Args > Struct Template Reference
#include <StdFunctionExporter.h>
Public Member Functions
std_function_from_python ()
Static Public Member Functions
static void construct (PyObject *obj_ptr, boost::python::converter::rvalue_from_python_stage1_data *data)
static void * convertible (PyObject *obj_ptr)
Detailed Description
template<typename R, typename... Args>
struct Mantid::PythonInterface::std_function_from_python< R, Args >
Definition at line 30 of file StdFunctionExporter.h.
Constructor & Destructor Documentation
std_function_from_python()
template<typename R , typename... Args> Mantid::PythonInterface::std_function_from_python< R, Args >::std_function_from_python () inline
Definition at line 31 of file StdFunctionExporter.h.
References Mantid::PythonInterface::std_function_from_python< R, Args >::construct(), and Mantid::PythonInterface::std_function_from_python< R, Args >::convertible().
Member Function Documentation
construct()
template<typename R , typename... Args> static void Mantid::PythonInterface::std_function_from_python< R, Args >::construct (PyObject * obj_ptr, boost::python::converter::rvalue_from_python_stage1_data * data) inline static
Definition at line 38 of file StdFunctionExporter.h.
Referenced by Mantid::PythonInterface::std_function_from_python< R, Args >::std_function_from_python().
convertible()
template<typename R , typename... Args> static void * Mantid::PythonInterface::std_function_from_python< R, Args >::convertible (PyObject * obj_ptr) inline static
Definition at line 36 of file StdFunctionExporter.h.
Referenced by Mantid::PythonInterface::std_function_from_python< R, Args >::std_function_from_python().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/StdFunctionExporter.h