Mantid: Mantid::DataHandling::LoadILLPolarizedDiffraction Class Reference
Mantid::DataHandling::LoadILLPolarizedDiffraction Class Reference
LoadILLPolarizedDiffraction : Loads ILL polarized diffraction nexus files from instrument D7.
#include <LoadILLPolarizedDiffraction.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
int confidence (Nexus::NexusDescriptorLazy &) const override
Returns confidence.
LoadILLPolarizedDiffraction ()
Constructor.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
API::MatrixWorkspace_sptr convertSpectrumAxis (API::MatrixWorkspace_sptr)
Converts the spectrum axis to scattering angle.
void exec () override
Executes the algorithm.
void init () override
Initialize the algorithm's properties.
API::MatrixWorkspace_sptr initStaticWorkspace (const Nexus::NXEntry &)
Initializes the output workspace based on the resolved instrument.
std::vector< double > loadBankParameters (const API::MatrixWorkspace_sptr &, const int)
Loads offsets and slopes for each detector bank from the workspace entry.
void loadData ()
Loads the polarized detector data, sets up workspaces and labels according to the measurement type and data dimensions.
void loadMetaData ()
Dumps the metadata from the file for each entry separately.
std::vector< double > loadTwoThetaDetectors (const API::MatrixWorkspace_sptr &, const Nexus::NXEntry &, const int)
Loads 2theta for each detector pixel from either the nexus file or the Instrument Parameter File.
void moveTwoTheta (const Nexus::NXEntry &, const API::MatrixWorkspace_sptr &)
Rotates each pixel to its corresponding 2theta read from the file.
std::vector< double > prepareAxes (const Nexus::NXEntry &)
Prepares values for bin edges depending of measurement type.
API::WorkspaceGroup_sptr sortPolarisations ()
Ensures that the order of flipper state values is 'ON' and then 'OFF' for each polarisation orientation, and that polarisations are in the following order: Z, X, Y, X-Y, X+Y.
API::MatrixWorkspace_sptr transposeMonochromatic (const API::MatrixWorkspace_sptr &)
Transposes given 2D workspace with monochromatic data.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
Private Attributes
size_t m_acquisitionMode
std::string m_fileName
file name to load
std::string m_instName
instrument name to load the IDF
size_t m_numberOfChannels
std::vector< API::MatrixWorkspace_sptr > m_outputWorkspaceGroup
vector with output workspaces
double m_wavelength
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadILLPolarizedDiffraction : Loads ILL polarized diffraction nexus files from instrument D7.
Date
15/05/20
Definition at line 26 of file LoadILLPolarizedDiffraction.h.
Constructor & Destructor Documentation
LoadILLPolarizedDiffraction()
Mantid::DataHandling::LoadILLPolarizedDiffraction::LoadILLPolarizedDiffraction ()
Constructor.
Definition at line 81 of file LoadILLPolarizedDiffraction.cpp.
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadILLPolarizedDiffraction::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Reimplemented from Mantid::API::Algorithm.
Definition at line 71 of file LoadILLPolarizedDiffraction.cpp.
confidence()
int Mantid::DataHandling::LoadILLPolarizedDiffraction::confidence (Nexus::NexusDescriptorLazy & descriptor) const override virtual
Returns confidence.
See also
IFileLoader::confidence
Implements Mantid::API::IFileLoader< Nexus::NexusDescriptorLazy >.
Definition at line 54 of file LoadILLPolarizedDiffraction.cpp.
convertSpectrumAxis()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLPolarizedDiffraction::convertSpectrumAxis (API::MatrixWorkspace_sptr workspace) private
Converts the spectrum axis to scattering angle.
Parameters
workspace : workspace to change the
Definition at line 419 of file LoadILLPolarizedDiffraction.cpp.
References convertSpectrumAxis(), Mantid::API::Algorithm::createChildAlgorithm(), and workspace.
Referenced by convertSpectrumAxis(), and loadData().
exec()
void Mantid::DataHandling::LoadILLPolarizedDiffraction::exec () override private virtual
Executes the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 122 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::getPropertyValue(), loadData(), loadMetaData(), m_fileName, m_wavelength, Mantid::API::Algorithm::progress(), Mantid::Kernel::IPropertyManager::setProperty(), and sortPolarisations().
init()
void Mantid::DataHandling::LoadILLPolarizedDiffraction::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 86 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::API::FileProperty::Load, Mantid::API::FileProperty::OptionalLoad, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertySettings().
initStaticWorkspace()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLPolarizedDiffraction::initStaticWorkspace (const Nexus::NXEntry & entry) private
Initializes the output workspace based on the resolved instrument.
If there are multiple entries in the file and the current entry is not the first one, the returned workspace is a clone of the workspace from the first entry
Parameters
entry : entry linked with the returned workspace
Returns
: workspace with the correct data dimensions
Definition at line 236 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::Units::Symbol::EmptyLabel, Mantid::API::Algorithm::getPropertyValue(), Mantid::Nexus::NXClass::getString(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_acquisitionMode, m_numberOfChannels, nSpectra, Mantid::Nexus::NXClass::openNXFloat(), Mantid::Nexus::NXClass::openNXInt(), and workspace.
Referenced by loadData().
loadBankParameters()
std::vector< double > Mantid::DataHandling::LoadILLPolarizedDiffraction::loadBankParameters (const API::MatrixWorkspace_sptr & workspace, const int bankId) private
Loads offsets and slopes for each detector bank from the workspace entry.
Parameters
workspace : workspace with loaded instrument
bankId : bank ID of the relevant bank
Returns
: vector of the bank slope and offset
Definition at line 320 of file LoadILLPolarizedDiffraction.cpp.
References std::to_string(), and workspace.
Referenced by moveTwoTheta().
loadData()
void Mantid::DataHandling::LoadILLPolarizedDiffraction::loadData () private
Loads the polarized detector data, sets up workspaces and labels according to the measurement type and data dimensions.
Definition at line 145 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::Nexus::NXClass::close(), convertSpectrumAxis(), Mantid::DataHandling::LoadHelper::dateTimeInIsoFormat(), Mantid::DataHandling::LoadHelper::fillStaticWorkspace(), Mantid::DataHandling::LoadHelper::getIntDataset(), Mantid::API::Algorithm::getProperty(), Mantid::Nexus::NXClass::getString(), Mantid::Nexus::NXClass::groups(), initStaticWorkspace(), Mantid::DataHandling::LoadHelper::loadEmptyInstrument(), m_acquisitionMode, m_fileName, m_instName, m_outputWorkspaceGroup, moveTwoTheta(), Mantid::Nexus::NXRoot::openEntry(), prepareAxes(), Mantid::DataHandling::LoadHelper::replaceZeroErrors(), std::to_string(), transposeMonochromatic(), and workspace.
Referenced by exec().
loadMetaData()
void Mantid::DataHandling::LoadILLPolarizedDiffraction::loadMetaData () private
Dumps the metadata from the file for each entry separately.
Definition at line 209 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::DataHandling::LoadHelper::addNexusFieldsToWsRun(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_fileName, m_outputWorkspaceGroup, m_wavelength, READ, std::to_string(), and workspace.
Referenced by exec().
loadTwoThetaDetectors()
std::vector< double > Mantid::DataHandling::LoadILLPolarizedDiffraction::loadTwoThetaDetectors (const API::MatrixWorkspace_sptr & workspace, const Nexus::NXEntry & entry, const int bankId) private
Loads 2theta for each detector pixel from either the nexus file or the Instrument Parameter File.
Parameters
workspace : workspace with loaded instrument
entry : entry from which the pixel 2theta positions will be read
bankId : bank ID for which 2theta positions will be read
Returns
: vector of pixel 2theta positions in the chosen bank
Definition at line 284 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_wavelength, Mantid::Nexus::NXClass::openNXFloat(), std::to_string(), Mantid::Kernel::twoTheta, and workspace.
Referenced by moveTwoTheta().
moveTwoTheta()
void Mantid::DataHandling::LoadILLPolarizedDiffraction::moveTwoTheta (const Nexus::NXEntry & entry, const API::MatrixWorkspace_sptr & workspace) private
Rotates each pixel to its corresponding 2theta read from the file.
Parameters
entry : entry from which the 2theta positions will be read
workspace : workspace containing the instrument being moved
Definition at line 340 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::V3D::getSpherical(), Mantid::Nexus::NXDataSetTyped< T >::load(), loadBankParameters(), loadTwoThetaDetectors(), Mantid::Nexus::NXClass::openNXFloat(), position, rotation, std::to_string(), and workspace.
Referenced by loadData().
name()
const std::string Mantid::DataHandling::LoadILLPolarizedDiffraction::name () const override virtual
Algorithms name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 65 of file LoadILLPolarizedDiffraction.cpp.
prepareAxes()
std::vector< double > Mantid::DataHandling::LoadILLPolarizedDiffraction::prepareAxes (const Nexus::NXEntry & entry) private
Prepares values for bin edges depending of measurement type.
Parameters
entry : entry from which the number of channels and measurement type will be read
Returns
: returns vector with bin edges
Definition at line 383 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::getPropertyValue(), Mantid::Nexus::NXDataSetTyped< T >::load(), m_acquisitionMode, m_numberOfChannels, m_wavelength, and Mantid::Nexus::NXClass::openNXFloat().
Referenced by loadData().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadILLPolarizedDiffraction::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 30 of file LoadILLPolarizedDiffraction.h.
sortPolarisations()
API::WorkspaceGroup_sptr Mantid::DataHandling::LoadILLPolarizedDiffraction::sortPolarisations () private
Ensures that the order of flipper state values is 'ON' and then 'OFF' for each polarisation orientation, and that polarisations are in the following order: Z, X, Y, X-Y, X+Y.
Definition at line 458 of file LoadILLPolarizedDiffraction.cpp.
References m_outputWorkspaceGroup.
Referenced by exec().
summary()
const std::string Mantid::DataHandling::LoadILLPolarizedDiffraction::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 74 of file LoadILLPolarizedDiffraction.cpp.
transposeMonochromatic()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadILLPolarizedDiffraction::transposeMonochromatic (const API::MatrixWorkspace_sptr & workspace) private
Transposes given 2D workspace with monochromatic data.
Parameters
workspace : workspace to be transposed
Definition at line 445 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), and workspace.
Referenced by loadData().
validateInputs()
std::map< std::string, std::string > Mantid::DataHandling::LoadILLPolarizedDiffraction::validateInputs (void) override private virtual
Perform validation of ALL the input properties of the algorithm.
This is to be overridden by specific algorithms. It will be called in dialogs after parsing all inputs and setting the properties, but BEFORE executing.
Returns
a map where: Key = string name of the property; Value = string describing the problem with the property.
Reimplemented from Mantid::API::Algorithm.
Definition at line 110 of file LoadILLPolarizedDiffraction.cpp.
References Mantid::API::Algorithm::getPropertyValue().
version()
int Mantid::DataHandling::LoadILLPolarizedDiffraction::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 68 of file LoadILLPolarizedDiffraction.cpp.
Member Data Documentation
m_acquisitionMode
size_t Mantid::DataHandling::LoadILLPolarizedDiffraction::m_acquisitionMode private
Definition at line 55 of file LoadILLPolarizedDiffraction.h.
Referenced by initStaticWorkspace(), loadData(), and prepareAxes().
m_fileName
std::string Mantid::DataHandling::LoadILLPolarizedDiffraction::m_fileName private
file name to load
Definition at line 59 of file LoadILLPolarizedDiffraction.h.
Referenced by exec(), loadData(), and loadMetaData().
m_instName
std::string Mantid::DataHandling::LoadILLPolarizedDiffraction::m_instName private
instrument name to load the IDF
Definition at line 58 of file LoadILLPolarizedDiffraction.h.
Referenced by loadData().
m_numberOfChannels
size_t Mantid::DataHandling::LoadILLPolarizedDiffraction::m_numberOfChannels private
Definition at line 54 of file LoadILLPolarizedDiffraction.h.
Referenced by initStaticWorkspace(), and prepareAxes().
m_outputWorkspaceGroup
std::vector<API::MatrixWorkspace_sptr> Mantid::DataHandling::LoadILLPolarizedDiffraction::m_outputWorkspaceGroup private
vector with output workspaces
Definition at line 63 of file LoadILLPolarizedDiffraction.h.
Referenced by loadData(), loadMetaData(), and sortPolarisations().
m_wavelength
double Mantid::DataHandling::LoadILLPolarizedDiffraction::m_wavelength private
Definition at line 61 of file LoadILLPolarizedDiffraction.h.
Referenced by exec(), loadMetaData(), loadTwoThetaDetectors(), and prepareAxes().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadILLPolarizedDiffraction.h
Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp