Mantid: ICat4::ns1__datafile Class Reference
ICat4::ns1__datafile Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__datafile ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * checksum
std::vector< ns1__dataCollectionDatafile * > dataCollectionDatafiles
time_t * datafileCreateTime
ns1__datafileFormat * datafileFormat
time_t * datafileModTime
ns1__dataset * dataset
std::string * description
std::vector< ns1__relatedDatafile * > destDatafiles
std::string * doi
LONG64 * fileSize
std::string * location
std::string * name
std::vector< ns1__datafileParameter * > parameters
std::vector< ns1__relatedDatafile * > sourceDatafiles
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1445 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__datafile()
ICat4::ns1__datafile::ns1__datafile () inline
Definition at line 1470 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__datafile::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17524 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataCollectionDatafile(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__datafileParameter(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__relatedDatafile().
Referenced by ICat4::soap_in_ns1__datafile(), ICat4::soap_new_req_ns1__datafile(), and ICat4::soap_new_set_ns1__datafile().
soap_get()
void * ICat4::ns1__datafile::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17787 of file ICat4C.cpp.
References ICat4::soap_get_ns1__datafile().
soap_in()
void * ICat4::ns1__datafile::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17622 of file ICat4C.cpp.
References ICat4::soap_in_ns1__datafile().
Referenced by ICat4::soap_in_ns1__datafile().
soap_out()
int ICat4::ns1__datafile::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17568 of file ICat4C.cpp.
References ICat4::soap_out_ns1__datafile().
soap_put()
int ICat4::ns1__datafile::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17780 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__datafile.
soap_serialize()
void ICat4::ns1__datafile::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 17545 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerToLONG64(), ICat4::soap_serialize_PointerTons1__datafileFormat(), ICat4::soap_serialize_PointerTons1__dataset(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataCollectionDatafile(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datafileParameter(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__relatedDatafile().
soap_type()
int ICat4::ns1__datafile::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1463 of file ICat4Stub.h.
Member Data Documentation
checksum
std::string* ICat4::ns1__datafile::checksum
Definition at line 1447 of file ICat4Stub.h.
dataCollectionDatafiles
std::vector<ns1__dataCollectionDatafile *> ICat4::ns1__datafile::dataCollectionDatafiles
Definition at line 1448 of file ICat4Stub.h.
datafileCreateTime
time_t* ICat4::ns1__datafile::datafileCreateTime
Definition at line 1450 of file ICat4Stub.h.
datafileFormat
ns1__datafileFormat* ICat4::ns1__datafile::datafileFormat
Definition at line 1451 of file ICat4Stub.h.
datafileModTime
time_t* ICat4::ns1__datafile::datafileModTime
Definition at line 1452 of file ICat4Stub.h.
dataset
ns1__dataset* ICat4::ns1__datafile::dataset
Definition at line 1453 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::getPublishInvestigations().
description
std::string* ICat4::ns1__datafile::description
Definition at line 1454 of file ICat4Stub.h.
destDatafiles
std::vector<ns1__relatedDatafile *> ICat4::ns1__datafile::destDatafiles
Definition at line 1455 of file ICat4Stub.h.
doi
std::string* ICat4::ns1__datafile::doi
Definition at line 1456 of file ICat4Stub.h.
fileSize
LONG64* ICat4::ns1__datafile::fileSize
Definition at line 1457 of file ICat4Stub.h.
location
std::string* ICat4::ns1__datafile::location
Definition at line 1458 of file ICat4Stub.h.
name
std::string* ICat4::ns1__datafile::name
Definition at line 1459 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::getPublishInvestigations().
parameters
std::vector<ns1__datafileParameter *> ICat4::ns1__datafile::parameters
Definition at line 1460 of file ICat4Stub.h.
sourceDatafiles
std::vector<ns1__relatedDatafile *> ICat4::ns1__datafile::sourceDatafiles
Definition at line 1461 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp