Mantid: MantidQt::API::JobRunnerSubscriber Class Reference
MantidQt::API::JobRunnerSubscriber Class Reference abstract
JobRunnerSubscriber is an interface to a class that subscribes to notifications from an IJobRunner.
#include <IJobRunner.h>
Public Member Functions
virtual void notifyAlgorithmComplete (API::IConfiguredAlgorithm_sptr &algorithm)=0
virtual void notifyAlgorithmError (API::IConfiguredAlgorithm_sptr &algorithm, std::string const &message)=0
virtual void notifyAlgorithmStarted (API::IConfiguredAlgorithm_sptr &algorithm)=0
virtual void notifyBatchCancelled ()=0
virtual void notifyBatchComplete (bool error)=0
virtual ~JobRunnerSubscriber ()=default
Detailed Description
JobRunnerSubscriber is an interface to a class that subscribes to notifications from an IJobRunner.
Definition at line 24 of file IJobRunner.h.
Constructor & Destructor Documentation
~JobRunnerSubscriber()
virtual MantidQt::API::JobRunnerSubscriber::~JobRunnerSubscriber () virtual default
Member Function Documentation
notifyAlgorithmComplete()
virtual void MantidQt::API::JobRunnerSubscriber::notifyAlgorithmComplete (API::IConfiguredAlgorithm_sptr & algorithm) pure virtual
Implemented in MantidQt::MantidWidgets::AddWorkspaceMultiDialog, and MantidQt::API::AlgorithmRunner.
Referenced by MantidQt::API::QtJobRunner::onAlgorithmComplete().
notifyAlgorithmError()
virtual void MantidQt::API::JobRunnerSubscriber::notifyAlgorithmError (API::IConfiguredAlgorithm_sptr & algorithm, std::string const & message) pure virtual
Implemented in MantidQt::MantidWidgets::AddWorkspaceMultiDialog, and MantidQt::API::AlgorithmRunner.
Referenced by MantidQt::API::QtJobRunner::onAlgorithmError().
notifyAlgorithmStarted()
virtual void MantidQt::API::JobRunnerSubscriber::notifyAlgorithmStarted (API::IConfiguredAlgorithm_sptr & algorithm) pure virtual
Implemented in MantidQt::MantidWidgets::AddWorkspaceMultiDialog, and MantidQt::API::AlgorithmRunner.
Referenced by MantidQt::API::QtJobRunner::onAlgorithmStarted().
notifyBatchCancelled()
virtual void MantidQt::API::JobRunnerSubscriber::notifyBatchCancelled () pure virtual
Implemented in MantidQt::MantidWidgets::AddWorkspaceMultiDialog, and MantidQt::API::AlgorithmRunner.
Referenced by MantidQt::API::QtJobRunner::onBatchCancelled().
notifyBatchComplete()
virtual void MantidQt::API::JobRunnerSubscriber::notifyBatchComplete (bool error) pure virtual
Implemented in MantidQt::MantidWidgets::AddWorkspaceMultiDialog, and MantidQt::API::AlgorithmRunner.
Referenced by MantidQt::API::QtJobRunner::onBatchComplete().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IJobRunner.h