Mantid: Mantid::WorkflowAlgorithms::MuonGroupCountsCalculator Class Reference
Mantid::WorkflowAlgorithms::MuonGroupCountsCalculator Class Reference
MuonGroupCountsCalculator : Calculates pure counts of the group specified via group index.
#include <MuonGroupCountsCalculator.h>
Public Member Functions
Mantid::API::MatrixWorkspace_sptr calculate () const override
Performs group counts calculation.
MuonGroupCountsCalculator (const Mantid::API::WorkspaceGroup_sptr &inputWS, const std::vector< int > &summedPeriods, const std::vector< int > &subtractedPeriods, const int groupIndex)
Constructor.
Public Member Functions inherited from Mantid::WorkflowAlgorithms::MuonGroupCalculator
MuonGroupCalculator (const Mantid::API::WorkspaceGroup_sptr &inputWS, const std::vector< int > &summedPeriods, const std::vector< int > &subtractedPeriods, const int groupIndex)
Constructor.
void setStartEnd (const double start, const double end)
void setWSName (const std::string &wsName)
Public Member Functions inherited from Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator
IMuonAsymmetryCalculator (API::WorkspaceGroup_sptr inputWS, std::vector< int > summedPeriods, std::vector< int > subtractedPeriods)
Constructor.
virtual ~IMuonAsymmetryCalculator ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator
API::MatrixWorkspace_sptr extractSpectrum (const API::Workspace_sptr &inputWS, const int index) const
Extracts a single spectrum from a workspace.
API::MatrixWorkspace_sptr subtractWorkspaces (const API::MatrixWorkspace_sptr &lhs, const API::MatrixWorkspace_sptr &rhs) const
Subtracts one workspace from another (lhs - rhs)
API::MatrixWorkspace_sptr sumPeriods (const std::vector< int > &periodsToSum) const
Sums the specified periods in the input workspace group.
Protected Attributes inherited from Mantid::WorkflowAlgorithms::MuonGroupCalculator
double m_endX
const int m_groupIndex
Workspace index of the group to analyse.
double m_startX
std::string m_wsName
Protected Attributes inherited from Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator
const API::WorkspaceGroup_sptr m_inputWS
Input workspace.
const std::vector< int > m_subtractedPeriods
List of subtracted periods.
const std::vector< int > m_summedPeriods
List of summed periods.
Detailed Description
MuonGroupCountsCalculator : Calculates pure counts of the group specified via group index.
Definition at line 17 of file MuonGroupCountsCalculator.h.
Constructor & Destructor Documentation
MuonGroupCountsCalculator()
Mantid::WorkflowAlgorithms::MuonGroupCountsCalculator::MuonGroupCountsCalculator (const Mantid::API::WorkspaceGroup_sptr & inputWS, const std::vector< int > & summedPeriods, const std::vector< int > & subtractedPeriods, const int groupIndex)
Constructor.
Parameters
inputWS :: [input] Input workspace group
summedPeriods :: [input] Vector of period indexes to be summed
subtractedPeriods :: [input] Vector of period indexes to be subtracted from summed periods
groupIndex :: [input] Workspace index of the group to analyse
Definition at line 22 of file MuonGroupCountsCalculator.cpp.
Member Function Documentation
calculate()
MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::MuonGroupCountsCalculator::calculate () const override virtual
Performs group counts calculation.
Calculates raw counts according to period arithmetic.
Returns
Workspace containing result of calculation
Implements Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator.
Definition at line 31 of file MuonGroupCountsCalculator.cpp.
References Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::extractSpectrum(), Mantid::WorkflowAlgorithms::MuonGroupCalculator::m_groupIndex, Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::m_inputWS, Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::m_subtractedPeriods, Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::m_summedPeriods, Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::subtractWorkspaces(), and Mantid::WorkflowAlgorithms::IMuonAsymmetryCalculator::sumPeriods().
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/MuonGroupCountsCalculator.h
Framework/WorkflowAlgorithms/src/MuonGroupCountsCalculator.cpp