Mantid: Mantid::DataObjects::detail Namespace Reference
Mantid::DataObjects::detail Namespace Reference
Factory methods for creating MatrixWorkspaces.
Classes
struct IsIndexInfo
struct IsIndexInfo< Indexing::IndexInfo >
Functions
template<class T >
std::unique_ptr< T > createConcreteHelper ()
template<>
MANTID_DATAOBJECTS_DLL std::unique_ptr< API::MatrixWorkspace > createConcreteHelper ()
template<>
MANTID_DATAOBJECTS_DLL std::unique_ptr< API::HistoWorkspace > createConcreteHelper ()
template<>
std::unique_ptr< API::MatrixWorkspace > createConcreteHelper ()
template<>
std::unique_ptr< API::HistoWorkspace > createConcreteHelper ()
template<class T >
std::unique_ptr< T > createHelper ()
template<>
MANTID_DATAOBJECTS_DLL std::unique_ptr< API::HistoWorkspace > createHelper ()
template<>
MANTID_DATAOBJECTS_DLL std::unique_ptr< EventWorkspace > createHelper ()
template<>
MANTID_DATAOBJECTS_DLL std::unique_ptr< API::MatrixWorkspace > createHelper ()
template<>
std::unique_ptr< EventWorkspace > createHelper ()
template<>
std::unique_ptr< API::HistoWorkspace > createHelper ()
template<>
std::unique_ptr< API::MatrixWorkspace > createHelper ()
template<class UseIndexInfo >
void doInitializeFromParent (const API::MatrixWorkspace &parent, API::MatrixWorkspace &workspace, const bool differentSize)
template<>
void doInitializeFromParent< std::true_type > (const API::MatrixWorkspace &parent, API::MatrixWorkspace &child, const bool differentSize)
Same as WorkspaceFactory::initializeFromParent, with modifications for changed IndexInfo.
template<class HistArg >
void fixDistributionFlag (API::MatrixWorkspace &, const HistArg &)
template<>
MANTID_DATAOBJECTS_DLL void fixDistributionFlag (API::MatrixWorkspace &workspace, const HistogramData::Histogram &histArg)
template<>
void fixDistributionFlag (API::MatrixWorkspace &workspace, const HistogramData::Histogram &histArg)
template<class UseIndexInfo >
void initializeFromParent (const API::MatrixWorkspace &parent, API::MatrixWorkspace &ws)
Initialize a MatrixWorkspace from its parent including instrument, unit, number of spectra and Run.
template void MANTID_DATAOBJECTS_DLL initializeFromParent< std::false_type > (const API::MatrixWorkspace &, API::MatrixWorkspace &)
template void MANTID_DATAOBJECTS_DLL initializeFromParent< std::true_type > (const API::MatrixWorkspace &, API::MatrixWorkspace &)
MANTID_DATAOBJECTS_DLL HistogramData::Histogram stripData (HistogramData::Histogram histogram)
Detailed Description
Factory methods for creating MatrixWorkspaces.
A template parameter T specifies the type of (or a base type of) the created workspace:
The type of the output workspace is identical to T for the variants without parent.
The type of the output workspace is the dynamic type of the parent if T is a base of the parents dynamic type.
The type of the output workspace is T if the dynamic type of the parent is a base of T.
If T is not a base of the parents dynamic type, a conversion is attempted. Currently this is the case only for EventWorkspace:
If the dynamic type of the parent is EventWorkspace but T is not, either a Workspace2D or T is created, whichever is more derived. For example, a typical use-case is to drop events and create a Workspace2D from an EventWorkspace. This can be achieved as follows:
auto ws = create<HistoWorkspace>(parent);
This is equivalent to the old way of using WorkspaceFactory::create(parent). In this case, Workspace2D is more derived than HistoWorkspace, so a Workspace2D is created.
If the dynamic type of the parent is derived from HistoWorkspace, and EventWorkspace can be created from it.
Other arguments can include:
The instrument.
The desired number of spectra (NumSpectra) to be created in the output workspace.
A reference to an IndexInfo object, defining the number of spectra and spectrum number and detector IDs.
A reference to a Histogram object (or alternatively BinEdges or Points), defining the size of the histograms as well as whether the workspace stores point data or histogram data. This is a replacement for an independent specification of the X and Y lengths. This is also used to initialize the workspace with X data and (optionally) Y and E data.
Available variants are:
create<T>(NumSpectra, Histogram)
create<T>(IndexInfo,  Histogram)
create<T>(Instrument, NumSpectra, Histogram)
create<T>(Instrument, IndexInfo,  Histogram)
create<T>(ParentWS)
create<T>(ParentWS, Histogram)
create<T>(ParentWS, NumSpectra, Histogram)
create<T>(ParentWS, IndexInfo, Histogram)
If neither NumSpectra nor IndexInfo is given, or if the new size is identical to the size of the parent, the created workspace has the same number of spectra as the parent workspace and spectrum number as well as detector ID information is copied from the parent.
If only ParentWS is given, the created workspace has X identical to the parent workspace and Y and E are initialized to 0.
If a Histogram with 'NULL' Y and E is given, Y and E are initialized to 0.
In all cases a (smart) pointer to T is returned.
Author
Simon Heybrock
Date
2016
Function Documentation
createConcreteHelper() [1/5]
template<class T > std::unique_ptr< T > Mantid::DataObjects::detail::createConcreteHelper ()
Definition at line 97 of file WorkspaceCreation.h.
createConcreteHelper() [2/5]
template<> MANTID_DATAOBJECTS_DLL std::unique_ptr< API::MatrixWorkspace > Mantid::DataObjects::detail::createConcreteHelper ()
Definition at line 26 of file WorkspaceCreation.cpp.
createConcreteHelper() [3/5]
template<> MANTID_DATAOBJECTS_DLL std::unique_ptr< API::HistoWorkspace > Mantid::DataObjects::detail::createConcreteHelper ()
Definition at line 26 of file WorkspaceCreation.cpp.
createConcreteHelper() [4/5]
template<> std::unique_ptr< API::MatrixWorkspace > Mantid::DataObjects::detail::createConcreteHelper ()
Definition at line 26 of file WorkspaceCreation.cpp.
createConcreteHelper() [5/5]
template<> std::unique_ptr< API::HistoWorkspace > Mantid::DataObjects::detail::createConcreteHelper ()
Definition at line 29 of file WorkspaceCreation.cpp.
createHelper() [1/7]
template<class T > std::unique_ptr< T > Mantid::DataObjects::detail::createHelper ()
Definition at line 95 of file WorkspaceCreation.h.
createHelper() [2/7]
template<> MANTID_DATAOBJECTS_DLL std::unique_ptr< API::HistoWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 20 of file WorkspaceCreation.cpp.
createHelper() [3/7]
template<> MANTID_DATAOBJECTS_DLL std::unique_ptr< EventWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 20 of file WorkspaceCreation.cpp.
createHelper() [4/7]
template<> MANTID_DATAOBJECTS_DLL std::unique_ptr< API::MatrixWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 20 of file WorkspaceCreation.cpp.
createHelper() [5/7]
template<> std::unique_ptr< EventWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 20 of file WorkspaceCreation.cpp.
createHelper() [6/7]
template<> std::unique_ptr< API::HistoWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 22 of file WorkspaceCreation.cpp.
createHelper() [7/7]
template<> std::unique_ptr< API::MatrixWorkspace > Mantid::DataObjects::detail::createHelper ()
Definition at line 24 of file WorkspaceCreation.cpp.
doInitializeFromParent()
template<class UseIndexInfo > void Mantid::DataObjects::detail::doInitializeFromParent (const API::MatrixWorkspace & parent, API::MatrixWorkspace & workspace, const bool differentSize)
Definition at line 34 of file WorkspaceCreation.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
doInitializeFromParent< std::true_type >()
template<> void Mantid::DataObjects::detail::doInitializeFromParent< std::true_type > (const API::MatrixWorkspace & parent, API::MatrixWorkspace & child, const bool differentSize)
Same as WorkspaceFactory::initializeFromParent, with modifications for changed IndexInfo.
IndexInfo used for initialization this implies that the following data from the parent is not applicable (since no automatic mapping possible):
Bin masking
Spectrum numbers and detector ID grouping
Y axis
Definition at line 49 of file WorkspaceCreation.cpp.
References Mantid::API::MatrixWorkspace::indexInfo(), Mantid::Kernel::SingletonHolder< T >::Instance(), and Mantid::API::MatrixWorkspace::setIndexInfo().
fixDistributionFlag() [1/3]
template<class HistArg > void Mantid::DataObjects::detail::fixDistributionFlag (API::MatrixWorkspace & , const HistArg &)
Definition at line 111 of file WorkspaceCreation.h.
Referenced by Mantid::DataObjects::create().
fixDistributionFlag() [2/3]
template<> MANTID_DATAOBJECTS_DLL void Mantid::DataObjects::detail::fixDistributionFlag (API::MatrixWorkspace & workspace, const HistogramData::Histogram & histArg)
Definition at line 81 of file WorkspaceCreation.cpp.
References workspace.
fixDistributionFlag() [3/3]
template<> void Mantid::DataObjects::detail::fixDistributionFlag (API::MatrixWorkspace & workspace, const HistogramData::Histogram & histArg)
Definition at line 81 of file WorkspaceCreation.cpp.
References workspace.
initializeFromParent()
template<class UseIndexInfo > void Mantid::DataObjects::detail::initializeFromParent (const API::MatrixWorkspace & parent, API::MatrixWorkspace & ws)
Initialize a MatrixWorkspace from its parent including instrument, unit, number of spectra and Run.
initializeFromParent
Parameters
parent
ws
Definition at line 71 of file WorkspaceCreation.cpp.
References Mantid::Kernel::DataItem::id(), Mantid::API::MatrixWorkspace::mutableX(), Mantid::API::MatrixWorkspace::x(), and Mantid::API::MatrixWorkspace::y().
initializeFromParent< std::false_type >()
template void MANTID_DATAOBJECTS_DLL Mantid::DataObjects::detail::initializeFromParent< std::false_type > (const API::MatrixWorkspace & , API::MatrixWorkspace &)
initializeFromParent< std::true_type >()
template void MANTID_DATAOBJECTS_DLL Mantid::DataObjects::detail::initializeFromParent< std::true_type > (const API::MatrixWorkspace & , API::MatrixWorkspace &)
stripData()
HistogramData::Histogram Mantid::DataObjects::detail::stripData (HistogramData::Histogram histogram)
Definition at line 14 of file WorkspaceCreation.cpp.
Referenced by Mantid::DataObjects::create().