Mantid: Mantid::DataHandling::LoadSESANS Class Reference
Mantid::DataHandling::LoadSESANS Class Reference
LoadSESANS : Load a workspace in the SESANS file format.
#include <LoadSESANS.h>
Public Member Functions
const std::string category () const override
Get algorithm's category.
int confidence (Kernel::FileDescriptor &descriptor) const override
Get the confidence that this algorithm can load a file.
const std::string name () const override
Get algorithm's name.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Get summary of algorithm.
int version () const override
Get algorithm's version number.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void checkMandatoryHeaders (const AttributeMap &attributes)
Make sure that all mandatory headers are supplied in the file.
ColumnMap consumeData (std::ifstream &infile, std::string &line, int &lineNum)
Read numerical data from the file into a map of the form [column name] -> [column data].
AttributeMap consumeHeaders (std::ifstream &infile, std::string &line, int &lineNum)
Read headers from the input file into the attribute map, until BEGIN_DATA is found.
void exec () override
Execute the algorithm.
void init () override
Initialise the algorithm.
API::MatrixWorkspace_sptr makeWorkspace (ColumnMap columns)
Create a new workspace with the columns read from the file.
std::pair< std::string, std::string > splitHeader (const std::string &line, const int &lineNum)
Split a header into a key-value pair delimited by whitespace, where the first token is the key and the remainder the value.
void throwFormatError (const std::string &line, const std::string &message, const int &lineNum)
Helper function to throw an error relating to the format of the file.
Private Attributes
const std::string m_beginData = "BEGIN_DATA"
const std::string m_depolarisation = "Depolarisation"
const std::string m_depolarisationError = "Depolarisation_error"
const std::vector< std::string > m_fileExtensions {".ses", ".SES", ".sesans", ".SESANS"}
const std::vector< std::string > m_mandatoryAttributes
const std::vector< std::string > m_mandatoryColumnHeaders
const std::string m_spinEchoLength = "SpinEchoLength"
const std::string m_wavelength = "Wavelength"
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadSESANS : Load a workspace in the SESANS file format.
Required properties:
<UL>
<LI> Filename - The path to the file</LI>
<LI> OutputWorkspace - The name of the output workspace</LI>
</UL>
@author Joseph Ramsay, ISIS
@date 20/07/2017
Definition at line 33 of file LoadSESANS.h.
Member Function Documentation
category()
const std::string Mantid::DataHandling::LoadSESANS::category () const override virtual
Get algorithm's category.
Reimplemented from Mantid::API::Algorithm.
Definition at line 77 of file LoadSESANS.cpp.
checkMandatoryHeaders()
void Mantid::DataHandling::LoadSESANS::checkMandatoryHeaders (const AttributeMap & attributes) private
Make sure that all mandatory headers are supplied in the file.
Exceptions
runtime_error If any other the mandatory headers are missing
Definition at line 313 of file LoadSESANS.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and m_mandatoryAttributes.
Referenced by exec().
confidence()
int Mantid::DataHandling::LoadSESANS::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Get the confidence that this algorithm can load a file.
Parameters
descriptor A descriptor for the file
Returns
The confidence level (0 to 100) where 0 indicates this algorithm will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 84 of file LoadSESANS.cpp.
References Mantid::Kernel::FileDescriptor::data(), Mantid::Kernel::FileDescriptor::extension(), Mantid::Kernel::FileDescriptor::isAscii(), m_beginData, and m_fileExtensions.
consumeData()
ColumnMap Mantid::DataHandling::LoadSESANS::consumeData (std::ifstream & infile, std::string & line, int & lineNum) private
Read numerical data from the file into a map of the form [column name] -> [column data].
Any lines which are badly formed are ignored, and a warning passed to the user
Parameters
infile Reference to the input file
line Reference to the line of the file currently being processed
lineNum The number of the line being processed
Returns
A mapping from column header to vector of strings representing the numbers in that column
Exceptions
runtime_error If the 4 mandatory columns are not supplied in the file
Definition at line 224 of file LoadSESANS.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_mandatoryColumnHeaders, throwFormatError(), std::to_string(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
consumeHeaders()
AttributeMap Mantid::DataHandling::LoadSESANS::consumeHeaders (std::ifstream & infile, std::string & line, int & lineNum) private
Read headers from the input file into the attribute map, until BEGIN_DATA is found.
Parameters
infile Reference to the input file
line Reference to the line currently being processed
lineNum Number of the line currently being processed
Returns
Map of attributes read
Exceptions
runtime_error If incorrectly formatted headers are found (empty lines are permitted)
Definition at line 197 of file LoadSESANS.cpp.
References m_beginData, and splitHeader().
Referenced by exec().
exec()
void Mantid::DataHandling::LoadSESANS::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 144 of file LoadSESANS.cpp.
References checkMandatoryHeaders(), consumeData(), consumeHeaders(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), m_beginData, makeWorkspace(), Mantid::Kernel::IPropertyManager::setProperty(), and throwFormatError().
init()
void Mantid::DataHandling::LoadSESANS::init () override private virtual
Initialise the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 134 of file LoadSESANS.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, m_fileExtensions, and Mantid::Kernel::Direction::Output.
makeWorkspace()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadSESANS::makeWorkspace (ColumnMap columns) private
Create a new workspace with the columns read from the file.
Parameters
columns Data columns from input file
Returns
A workspace with the corresponding data
Definition at line 327 of file LoadSESANS.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), m_depolarisation, m_depolarisationError, and m_spinEchoLength.
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadSESANS::name () const override virtual
Get algorithm's name.
Implements Mantid::API::Algorithm.
Definition at line 68 of file LoadSESANS.cpp.
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadSESANS::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 38 of file LoadSESANS.h.
splitHeader()
std::pair< std::string, std::string > Mantid::DataHandling::LoadSESANS::splitHeader (const std::string & untrimmedLine, const int & lineNum) private
Split a header into a key-value pair delimited by whitespace, where the first token is the key and the remainder the value.
Parameters
untrimmedLine A string containing the line to split, possibly with whitespace at each end
lineNum The number of the line in the file, used for error messaging
Returns
A key-value pair
Exceptions
runtime_error If the line contains less than two tokens
Definition at line 274 of file LoadSESANS.cpp.
References throwFormatError().
Referenced by consumeHeaders().
summary()
const std::string Mantid::DataHandling::LoadSESANS::summary () const override virtual
Get summary of algorithm.
Implements Mantid::API::Algorithm.
Definition at line 71 of file LoadSESANS.cpp.
throwFormatError()
void Mantid::DataHandling::LoadSESANS::throwFormatError (const std::string & line, const std::string & message, const int & lineNum) private
Helper function to throw an error relating to the format of the file.
Parameters
line The line where a format error was found
message A message detailing the reason for the error
lineNum The number of the line
Exceptions
runtime_error Under all circumstances
Definition at line 304 of file LoadSESANS.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and std::to_string().
Referenced by consumeData(), exec(), and splitHeader().
version()
int Mantid::DataHandling::LoadSESANS::version () const override virtual
Get algorithm's version number.
Implements Mantid::API::Algorithm.
Definition at line 74 of file LoadSESANS.cpp.
Member Data Documentation
m_beginData
const std::string Mantid::DataHandling::LoadSESANS::m_beginData = "BEGIN_DATA" private
Definition at line 48 of file LoadSESANS.h.
Referenced by confidence(), consumeHeaders(), and exec().
m_depolarisation
const std::string Mantid::DataHandling::LoadSESANS::m_depolarisation = "Depolarisation" private
Definition at line 46 of file LoadSESANS.h.
Referenced by makeWorkspace().
m_depolarisationError
const std::string Mantid::DataHandling::LoadSESANS::m_depolarisationError = "Depolarisation_error" private
Definition at line 47 of file LoadSESANS.h.
Referenced by makeWorkspace().
m_fileExtensions
const std::vector<std::string> Mantid::DataHandling::LoadSESANS::m_fileExtensions {".ses", ".SES", ".sesans", ".SESANS"} private
Definition at line 56 of file LoadSESANS.h.
Referenced by confidence(), and init().
m_mandatoryAttributes
const std::vector<std::string> Mantid::DataHandling::LoadSESANS::m_mandatoryAttributes private
Initial value:
{
      "FileFormatVersion",   "DataFileTitle",       "Sample",         "Thickness",       "Thickness_unit",
      "Theta_zmax",          "Theta_zmax_unit",     "Theta_ymax",     "Theta_ymax_unit", "Orientation",
      "SpinEchoLength_unit", "Depolarisation_unit", "Wavelength_unit"}
Definition at line 50 of file LoadSESANS.h.
Referenced by checkMandatoryHeaders().
m_mandatoryColumnHeaders
const std::vector<std::string> Mantid::DataHandling::LoadSESANS::m_mandatoryColumnHeaders private
Initial value:
{m_spinEchoLength, m_wavelength, m_depolarisation,
                                                          m_depolarisationError}
Definition at line 54 of file LoadSESANS.h.
Referenced by consumeData().
m_spinEchoLength
const std::string Mantid::DataHandling::LoadSESANS::m_spinEchoLength = "SpinEchoLength" private
Definition at line 44 of file LoadSESANS.h.
Referenced by makeWorkspace().
m_wavelength
const std::string Mantid::DataHandling::LoadSESANS::m_wavelength = "Wavelength" private
Definition at line 45 of file LoadSESANS.h.
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadSESANS.h
Framework/DataHandling/src/LoadSESANS.cpp