Mantid: MantidQt::MantidWidgets::CreateAttributeProperty Class Reference
MantidQt::MantidWidgets::CreateAttributeProperty Class Reference
Attribute visitor to create a QtProperty.
Public Member Functions
CreateAttributeProperty (FitPropertyBrowser *browser, PropertyHandler *handler, QString name, Mantid::Kernel::IValidator_sptr validator=nullptr)
Public Member Functions inherited from Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >
QtProperty * operator() (const bool &b) const
implements static_visitor's operator() for bool
QtProperty * operator() (const double &d) const
implements static_visitor's operator() for double
QtProperty * operator() (const int &i) const
implements static_visitor's operator() for int
QtProperty * operator() (const std::string &str) const
implements static_visitor's operator() for std::string
QtProperty * operator() (const std::vector< double > &v) const
implements static_visitor's operator() for vector
virtual ~ConstAttributeVisitor ()=default
Virtual destructor.
Protected Member Functions
QtProperty * apply (const bool &b) const override
Create bool property.
QtProperty * apply (const double &d) const override
Create double property.
QtProperty * apply (const int &i) const override
Create int property.
QtProperty * apply (const std::string &str) const override
Create string property.
QtProperty * apply (const std::vector< double > &b) const override
Create vector property.
Protected Member Functions inherited from Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >
virtual QtProperty * apply (const bool &i) const=0
Implement this mathod to access attribute as bool.
virtual QtProperty * apply (const double &d) const=0
Implement this mathod to access attribute as double.
virtual QtProperty * apply (const int &i) const=0
Implement this mathod to access attribute as int.
virtual QtProperty * apply (const std::string &str) const=0
Implement this mathod to access attribute as string.
virtual QtProperty * apply (const std::vector< double > &) const=0
Implement this mathod to access attribute as vector.
void evaluateValidator (T1 &inputData) const
Evaluates the validator associated with attribute this visitor is to visit.
Private Attributes
FitPropertyBrowser * m_browser
PropertyHandler * m_handler
QString m_name
Additional Inherited Members
Protected Attributes inherited from Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >
Mantid::Kernel::IValidator_sptr m_validator
Validator against which to evaluate attribute value to set.
Detailed Description
Attribute visitor to create a QtProperty.
Depending on the attribute type the appropriate apply method is used.
Definition at line 134 of file PropertyHandler.cpp.
Constructor & Destructor Documentation
CreateAttributeProperty()
MantidQt::MantidWidgets::CreateAttributeProperty::CreateAttributeProperty (FitPropertyBrowser * browser, PropertyHandler * handler, QString name, Mantid::Kernel::IValidator_sptr validator = nullptr) inline
Definition at line 136 of file PropertyHandler.cpp.
References Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >::m_validator.
Member Function Documentation
apply() [1/5]
QtProperty * MantidQt::MantidWidgets::CreateAttributeProperty::apply (const bool & b) const inline override protected virtual
Create bool property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >.
Definition at line 170 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager, m_browser, and m_name.
apply() [2/5]
QtProperty * MantidQt::MantidWidgets::CreateAttributeProperty::apply (const double & d) const inline override protected virtual
Create double property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >.
Definition at line 158 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty(), Mantid::Geometry::d, m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager, and m_name.
apply() [3/5]
QtProperty * MantidQt::MantidWidgets::CreateAttributeProperty::apply (const int & i) const inline override protected virtual
Create int property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >.
Definition at line 164 of file PropertyHandler.cpp.
References m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_intManager, and m_name.
apply() [4/5]
QtProperty * MantidQt::MantidWidgets::CreateAttributeProperty::apply (const std::string & str) const inline override protected virtual
Create string property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >.
Definition at line 144 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addStringListProperty(), MantidQt::MantidWidgets::FitPropertyBrowser::addStringProperty(), m_browser, m_name, Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >::m_validator, and MantidQt::MantidWidgets::FitPropertyBrowser::setStringPropertyValue().
apply() [5/5]
QtProperty * MantidQt::MantidWidgets::CreateAttributeProperty::apply (const std::vector< double > & b) const inline override protected virtual
Create vector property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< QtProperty * >.
Definition at line 176 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty(), m_browser, m_handler, m_name, MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorDoubleManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorManager, MantidQt::MantidWidgets::PropertyHandler::m_vectorMembers, MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorSizeManager, and MantidQt::MantidWidgets::PropertyHandler::m_vectorSizes.
Member Data Documentation
m_browser
FitPropertyBrowser* MantidQt::MantidWidgets::CreateAttributeProperty::m_browser private
Definition at line 199 of file PropertyHandler.cpp.
Referenced by apply().
m_handler
PropertyHandler* MantidQt::MantidWidgets::CreateAttributeProperty::m_handler private
Definition at line 200 of file PropertyHandler.cpp.
Referenced by apply().
m_name
QString MantidQt::MantidWidgets::CreateAttributeProperty::m_name private
Definition at line 201 of file PropertyHandler.cpp.
Referenced by apply().
The documentation for this class was generated from the following file:
qt/widgets/common/src/PropertyHandler.cpp