Mantid: Mantid::Algorithms::SANSCollimationLengthEstimator Class Reference
Mantid::Algorithms::SANSCollimationLengthEstimator Class Reference
#include <SANSCollimationLengthEstimator.h>
Public Member Functions
double provideCollimationLength (const Mantid::API::MatrixWorkspace_sptr &workspace)
Provide the collimation length which is associated with the instrument.
Private Member Functions
double getCollimationLengthWithGuides (const Mantid::API::MatrixWorkspace_sptr &inOutWS, const double L1, const double collimationLengthCorrection) const
This extraction strategy gets applied when guides are used to calculate the collimation length.
double getGuideValue (const Mantid::Kernel::Property *prop) const
Extracts the value of the guide.
Detailed Description
Definition at line 16 of file SANSCollimationLengthEstimator.h.
Member Function Documentation
getCollimationLengthWithGuides()
double Mantid::Algorithms::SANSCollimationLengthEstimator::getCollimationLengthWithGuides (const Mantid::API::MatrixWorkspace_sptr & inOutWS, const double L1, const double collimationLengthCorrection) const private
This extraction strategy gets applied when guides are used to calculate the collimation length.
The instrument parameter file contains the information about the number of guides to use. The guide data itself is fetched from the sample logs.
Parameters
inOutWS a matrix workspace
L1 the distance between sample and source
collimationLengthCorrection The correction to get the collimation length
Definition at line 99 of file SANSCollimationLengthEstimator.cpp.
References getGuideValue(), and std::to_string().
Referenced by provideCollimationLength().
getGuideValue()
double Mantid::Algorithms::SANSCollimationLengthEstimator::getGuideValue (const Mantid::Kernel::Property * prop) const private
Extracts the value of the guide.
Parameters
prop a property
Returns
the guide value
Definition at line 171 of file SANSCollimationLengthEstimator.cpp.
References Mantid::Algorithms::g_log, and Mantid::Kernel::Logger::warning().
Referenced by getCollimationLengthWithGuides().
provideCollimationLength()
double Mantid::Algorithms::SANSCollimationLengthEstimator::provideCollimationLength (const Mantid::API::MatrixWorkspace_sptr & workspace)
Provide the collimation length which is associated with the instrument.
Parameters
workspace the input workspace
Returns
the collimation length
Definition at line 46 of file SANSCollimationLengthEstimator.cpp.
References Mantid::Kernel::Logger::error(), Mantid::Algorithms::g_log, getCollimationLengthWithGuides(), Mantid::Kernel::V3D::norm(), Mantid::Kernel::Logger::notice(), and workspace.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/SANSCollimationLengthEstimator.h
Framework/Algorithms/src/SANSCollimationLengthEstimator.cpp