Mantid: Mantid::DataHandling::LoadFITS Class Reference
Mantid::DataHandling::LoadFITS Class Reference
LoadFITS: Load one or more of FITS files into a Workspace2D.
#include <LoadFITS.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadFITS ()
Constructor.
bool loadMutipleAsOne () override
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
void addAxesInfoAndLogs (const DataObjects::Workspace2D_sptr &ws, bool loadAsRectImg, const FITSInfo &fileInfo, int binSize, double cmpp)
Add information to the workspace being loaded: labels, units, logs related to the image size, etc.
void doFilterNoise (double thresh, API::MantidImage &imageY, API::MantidImage &imageE)
filter noise pixel by pixel
void doLoadFiles (const std::vector< std::string > &paths, const std::string &outWSName, bool loadAsRectImg, int binSize, double noiseThresh)
Loads files into workspace(s)
void doRebin (size_t rebin, const API::MantidImage &imageY, const API::MantidImage &imageE, API::MantidImage &rebinnedY, API::MantidImage &rebinnedE)
rebin the matrix/image
void exec () override
Execution code.
size_t fetchNumber (const std::string &name)
Returns the trailing number from a string minus leading 0's (so 25 from workspace_000025)
void headerSanityCheck (const FITSInfo &hdr, const FITSInfo &hdrFirst)
Once loaded, check against standard and limitations of this algorithm.
void init () override
Initialisation code.
bool isInstrOtherThanIMAT (const FITSInfo &hdr)
identifies fits coming from 'other' cameras by specific headers
void loadHeader (const std::string &filePath, FITSInfo &header)
Load the FITS header(s) from one fits file into a struct.
DataObjects::Workspace2D_sptr makeWorkspace (const FITSInfo &fileInfo, size_t &newFileNumber, std::vector< char > &buffer, API::MantidImage &imageY, API::MantidImage &imageE, const DataObjects::Workspace2D_sptr &parent, bool loadAsRectImg=false, int binSize=1, double noiseThresh=false)
Initialises a workspace with IDF and fills it with data.
void mapHeaderKeys ()
Maps the header keys to specified values.
std::string padZeros (const size_t number, const size_t totalDigitCount)
Adds 0's to the front of a number to create a string of size totalDigitCount including number.
void parseHeader (FITSInfo &headerInfo)
Parses the header values for the FITS file.
void readDataToImgs (const FITSInfo &fileInfo, API::MantidImage &imageY, API::MantidImage &imageE, std::vector< char > &buffer)
Reads the data (FITS matrix) from a single FITS file into image objects (Y and E).
void readDataToWorkspace (const FITSInfo &fileInfo, double cmpp, const DataObjects::Workspace2D_sptr &ws, std::vector< char > &buffer)
Reads the data (FITS matrix) from a single FITS file into a workspace (directly into the spectra, using one spectrum per image row).
void readInBuffer (const FITSInfo &fileInfo, std::vector< char > &buffer, size_t len)
Reads the data (FITS matrix) from a single FITS file into a buffer.
void setupDefaultKeywordNames ()
Sets several keyword names with default (and standard) values.
Private Attributes
std::vector< std::string > m_headerAxisNameKeys
std::string m_headerBitDepthKey
std::string m_headerImageKeyKey
std::string m_headerNAxisNameKey
std::string m_headerOffsetKey
std::string m_headerRotationKey
std::string m_headerScaleKey
std::string m_imageType
std::string m_mapFile
size_t m_pixelCount
std::string m_sampleRotation
Static Private Attributes
static const std::string g_AXIS_NAMES_NAME = "AxisNames"
static const int g_BASE_HEADER_SIZE = 2880
size of a FITS header block (room for 36 entries, of 80 characters each), in bytes.
static const std::string g_BIT_DEPTH_NAME = "BitDepthName"
static const std::string g_COMMENT_KEYNAME = "COMMENT"
static const std::string g_defaultImgType = "SAMPLE"
static const size_t g_DIGIT_SIZE_APPEND = 6
static const std::string g_END_KEYNAME = "END"
static const std::string g_HEADER_MAP_NAME = "HeaderMapFile"
static const std::string g_IMAGE_KEY_NAME = "ImageKeyName"
static const size_t g_maxBitDepth = 64
static const size_t g_maxBytesPP = g_maxBitDepth / 8
static const std::string g_ROTATION_NAME = "RotationName"
static const std::string g_XTENSION_KEYNAME = "XTENSION"
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
LoadFITS: Load one or more of FITS files into a Workspace2D.
The FITS format, normally used for images, is described for example here: http://www.fileformat.info/format/fits/egff.htm
At the moment this algorithm only supports 2 data axis and the following data types: unsigned 8, 16, 32 bits per pixel.
Definition at line 36 of file LoadFITS.h.
Constructor & Destructor Documentation
LoadFITS()
Mantid::DataHandling::LoadFITS::LoadFITS ()
Constructor.
Just initialize everything to prevent issues.
Definition at line 80 of file LoadFITS.cpp.
References setupDefaultKeywordNames().
Member Function Documentation
addAxesInfoAndLogs()
void Mantid::DataHandling::LoadFITS::addAxesInfoAndLogs (const DataObjects::Workspace2D_sptr & ws, bool loadAsRectImg, const FITSInfo & fileInfo, int binSize, double cmpp) private
Add information to the workspace being loaded: labels, units, logs related to the image size, etc.
Parameters
ws workspace to manipulate
loadAsRectImg if true, the workspace has one spectrum per row and one bin per column
fileInfo information for the current file
binSize size to rebin (1 == no re-bin == default)
cmpp centimeters per pixel (already taking into account possible rebinning)
Definition at line 675 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::axisPixelLengths, Mantid::DataObjects::create(), Mantid::DataHandling::FITSInfo::headerKeys, height, Mantid::DataHandling::FITSInfo::imageKey, and m_sampleRotation.
Referenced by makeWorkspace().
category()
const std::string Mantid::DataHandling::LoadFITS::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 51 of file LoadFITS.h.
confidence()
int Mantid::DataHandling::LoadFITS::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 92 of file LoadFITS.cpp.
References Mantid::Kernel::FileDescriptor::extension().
doFilterNoise()
void Mantid::DataHandling::LoadFITS::doFilterNoise (double thresh, API::MantidImage & imageY, API::MantidImage & imageE) private
filter noise pixel by pixel
Apply a simple noise filter by averaging threshold-filtered neighbor pixels (with 4-neighbohood / 4-connectivity).
The filtering is done in place for both imageY and imageE.
Parameters
thresh Threshold to apply on pixels
imageY raw data (Y values)
imageE raw data (E/error values)
Definition at line 895 of file LoadFITS.cpp.
Referenced by makeWorkspace().
doLoadFiles()
void Mantid::DataHandling::LoadFITS::doLoadFiles (const std::vector< std::string > & paths, const std::string & outWSName, bool loadAsRectImg, int binSize, double noiseThresh) private
Loads files into workspace(s)
Create FITS file information for each file selected.
Loads headers and data from the files and creates and fills the output workspace(s).
Parameters
paths File names as given in the algorithm input property
outWSName name of the output (group) workspace to create
loadAsRectImg Load files with 1 spectrum per row and 1 bin per column, so a color fill plot displays the image
binSize size to rebin (1 == no re-bin == default)
noiseThresh threshold for noise filtering
Exceptions
std::runtime_error when load fails (for example a memory allocation issue, wrong rebin requested, etc.)
Definition at line 369 of file LoadFITS.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), fetchNumber(), Mantid::API::Algorithm::g_log, Mantid::API::WorkspaceGroup::getNames(), headerSanityCheck(), Mantid::Kernel::Logger::information(), isInstrOtherThanIMAT(), loadHeader(), m_pixelCount, makeWorkspace(), Mantid::API::Algorithm::progress(), Mantid::Kernel::IPropertyManager::setProperty(), and std::to_string().
Referenced by exec().
doRebin()
void Mantid::DataHandling::LoadFITS::doRebin (size_t rebin, const API::MantidImage & imageY, const API::MantidImage & imageE, API::MantidImage & rebinnedY, API::MantidImage & rebinnedE) private
rebin the matrix/image
Group pixels in blocks of rebin X rebin.
Parameters
rebin bin size (n to make blocks of n*n pixels)
imageY raw data (Y values)
imageE raw data (E/error values)
rebinnedY raw data after rebin (Y values)
rebinnedE raw data after rebin (E/error values)
Definition at line 949 of file LoadFITS.cpp.
Referenced by makeWorkspace().
exec()
void Mantid::DataHandling::LoadFITS::exec () override private virtual
Execution code.
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 150 of file LoadFITS.cpp.
References doLoadFiles(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), and mapHeaderKeys().
fetchNumber()
size_t Mantid::DataHandling::LoadFITS::fetchNumber (const std::string & name) private
Returns the trailing number from a string minus leading 0's (so 25 from workspace_000025)
Returns the trailing number from a string minus leading 0's (so 25 from workspace_00025).
Parameters
name string with a numerical suffix
Returns
A numerical representation of the string minus leading characters and leading 0's
Definition at line 1083 of file LoadFITS.cpp.
References name().
Referenced by doLoadFiles().
headerSanityCheck()
void Mantid::DataHandling::LoadFITS::headerSanityCheck (const FITSInfo & hdr, const FITSInfo & hdrFirst) private
Once loaded, check against standard and limitations of this algorithm.
Checks that a FITS header (once loaded) is valid/supported: standard (no extension to FITS), and has two axis with the expected dimensions.
Parameters
hdr FITS header struct loaded from a file - to check
hdrFirst FITS header struct loaded from a (first) reference file - to compare against
Exceptions
std::exception if there's any issue or unsupported entry in the header
Definition at line 310 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::axisPixelLengths, Mantid::Kernel::Logger::error(), Mantid::DataHandling::FITSInfo::extension, Mantid::DataHandling::FITSInfo::filePath, Mantid::API::Algorithm::g_log, and Mantid::DataHandling::FITSInfo::numberOfAxis.
Referenced by doLoadFiles().
init()
void Mantid::DataHandling::LoadFITS::init () override private virtual
Initialisation code.
Initialise the algorithm.
Declare properties which can be set before execution (input) or read from after the execution (output).
Implements Mantid::API::Algorithm.
Definition at line 102 of file LoadFITS.cpp.
References Mantid::API::Algorithm::declareProperty(), g_HEADER_MAP_NAME, Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::OptionalDirectory, and Mantid::Kernel::Direction::Output.
isInstrOtherThanIMAT()
bool Mantid::DataHandling::LoadFITS::isInstrOtherThanIMAT (const FITSInfo & hdr) private
identifies fits coming from 'other' cameras by specific headers
Looks for headers used by specific instruments/cameras, or finds if the instrument does not appear to be IMAT, which is the only one for which we have a camera-instrument definition and because of that is the only one loaded for the moment.
Parameters
hdr FITS header information
Returns
whether this file seems to come from 'another' camera such as Starlight Xpress, etc.
Definition at line 983 of file LoadFITS.cpp.
References Mantid::API::Algorithm::g_log, Mantid::DataHandling::FITSInfo::headerKeys, and Mantid::Kernel::Logger::information().
Referenced by doLoadFiles().
loadHeader()
void Mantid::DataHandling::LoadFITS::loadHeader (const std::string & filePath, FITSInfo & header) private
Load the FITS header(s) from one fits file into a struct.
Definition at line 166 of file LoadFITS.cpp.
References Mantid::Kernel::Logger::debug(), g_defaultImgType, Mantid::API::Algorithm::g_log, g_XTENSION_KEYNAME, m_headerAxisNameKeys, m_headerBitDepthKey, m_headerImageKeyKey, m_headerNAxisNameKey, m_headerOffsetKey, m_headerScaleKey, parseHeader(), std::to_string(), and Mantid::Kernel::Logger::warning().
Referenced by doLoadFiles().
loadMutipleAsOne()
bool Mantid::DataHandling::LoadFITS::loadMutipleAsOne () inline override virtual
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Reimplemented from Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 58 of file LoadFITS.h.
makeWorkspace()
Workspace2D_sptr Mantid::DataHandling::LoadFITS::makeWorkspace (const FITSInfo & fileInfo, size_t & newFileNumber, std::vector< char > & buffer, API::MantidImage & imageY, API::MantidImage & imageE, const DataObjects::Workspace2D_sptr & parent, bool loadAsRectImg = false, int binSize = 1, double noiseThresh = false) private
Initialises a workspace with IDF and fills it with data.
Creates and initialises a workspace with instrument definition and fills it with data.
Parameters
fileInfo information for the current file
newFileNumber sequence number for the new file when added into ws group
buffer pre-allocated buffer to contain data values
imageY Object to set the Y data values in
imageE Object to set the E data values in
parent A workspace which can be used to copy initialisation information from (size/instrument def etc)
loadAsRectImg if true, the new workspace will have one spectrum per row and one bin per column, instead of the (default) as many spectra as pixels.
binSize size to rebin (1 == no re-bin == default)
noiseThresh threshold for noise filtering
Returns
A newly created Workspace2D, as a shared pointer
Definition at line 597 of file LoadFITS.cpp.
References addAxesInfoAndLogs(), Mantid::DataHandling::FITSInfo::axisPixelLengths, Mantid::DataObjects::create(), doFilterNoise(), doRebin(), Mantid::DataHandling::FITSInfo::filePath, g_DIGIT_SIZE_APPEND, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_pixelCount, padZeros(), readDataToImgs(), and readDataToWorkspace().
Referenced by doLoadFiles().
mapHeaderKeys()
void Mantid::DataHandling::LoadFITS::mapHeaderKeys () private
Maps the header keys to specified values.
Definition at line 1031 of file LoadFITS.cpp.
References Mantid::Kernel::Logger::error(), g_AXIS_NAMES_NAME, g_BIT_DEPTH_NAME, g_HEADER_MAP_NAME, g_IMAGE_KEY_NAME, Mantid::API::Algorithm::g_log, g_ROTATION_NAME, Mantid::API::Algorithm::getPropertyValue(), m_headerAxisNameKeys, m_headerBitDepthKey, m_headerImageKeyKey, and m_headerRotationKey.
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadFITS::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 41 of file LoadFITS.h.
Referenced by fetchNumber().
padZeros()
std::string Mantid::DataHandling::LoadFITS::padZeros (const size_t number, const size_t totalDigitCount) private
Adds 0's to the front of a number to create a string of size totalDigitCount including number.
Parameters
number input number to add padding to
totalDigitCount width of the resulting string with 0s followed by number
Returns
A string with the 0-padded number
Definition at line 1105 of file LoadFITS.cpp.
Referenced by makeWorkspace().
parseHeader()
void Mantid::DataHandling::LoadFITS::parseHeader (FITSInfo & headerInfo) private
Parses the header values for the FITS file.
Read a single files header and populate an object with the information.
Parameters
headerInfo A FITSInfo file object to parse header information into. This object must have its field filePath set to the input file
A typical simple FITS header looks like this:
SIMPLE  =                    T / file does conform to FITS standard
BITPIX  =                   16 / number of bits per data pixel
NAXIS   =                    2 / number of data axes
NAXIS1  =                  512 / length of data axis 1
NAXIS2  =                  512 / length of data axis 2
EXTEND  =                    T / FITS dataset may contain extensions
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H
TOF     =   0.0595897599999995 / Ttime of flight from the external trigger
TIMEBIN =           4.096E-005 / Time width of this image
N_COUNTS=               182976 / Total counts in this image
N_TRIGS =                 4426 / Number of triggers acquired
END
Exceptions
various std::runtime_error etc. on read failure
Definition at line 498 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::filePath, g_BASE_HEADER_SIZE, g_COMMENT_KEYNAME, g_END_KEYNAME, Mantid::DataHandling::FITSInfo::headerItems, Mantid::DataHandling::FITSInfo::headerKeys, Mantid::DataHandling::FITSInfo::headerSizeMultiplier, std::to_string(), and value.
Referenced by loadHeader().
readDataToImgs()
void Mantid::DataHandling::LoadFITS::readDataToImgs (const FITSInfo & fileInfo, API::MantidImage & imageY, API::MantidImage & imageE, std::vector< char > & buffer) private
Reads the data (FITS matrix) from a single FITS file into image objects (Y and E).
E is filled with the sqrt() of Y.
Parameters
fileInfo information on the FITS file to load, including its path
imageY Object to set the Y data values in
imageE Object to set the E data values in
buffer pre-allocated buffer to contain data values
Exceptions
std::runtime_error if there are file input issues
Definition at line 810 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::axisPixelLengths, Mantid::DataHandling::FITSInfo::bitsPerPixel, Mantid::DataHandling::FITSInfo::isFloat, m_pixelCount, Mantid::DataHandling::FITSInfo::offset, readInBuffer(), Mantid::DataHandling::FITSInfo::scale, and tmp.
Referenced by makeWorkspace().
readDataToWorkspace()
void Mantid::DataHandling::LoadFITS::readDataToWorkspace (const FITSInfo & fileInfo, double cmpp, const DataObjects::Workspace2D_sptr & ws, std::vector< char > & buffer) private
Reads the data (FITS matrix) from a single FITS file into a workspace (directly into the spectra, using one spectrum per image row).
Parameters
fileInfo information on the FITS file to load, including its path
cmpp centimeters per pixel, to scale/normalize values
ws workspace with the required dimensions
buffer pre-allocated buffer to read from file
Exceptions
std::runtime_error if there are file input issues
Definition at line 751 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::axisPixelLengths, Mantid::DataHandling::FITSInfo::bitsPerPixel, g_maxBytesPP, Mantid::DataHandling::FITSInfo::isFloat, m_pixelCount, ncols, nrows, Mantid::DataHandling::FITSInfo::offset, PARALLEL_FOR_NO_WSP_CHECK, readInBuffer(), and Mantid::DataHandling::FITSInfo::scale.
Referenced by makeWorkspace().
readInBuffer()
void Mantid::DataHandling::LoadFITS::readInBuffer (const FITSInfo & fileInfo, std::vector< char > & buffer, size_t len) private
Reads the data (FITS matrix) from a single FITS file into a buffer.
This simply reads the raw block of data, without doing any re-scaling or adjustment.
Parameters
fileInfo information on the FITS file to load, including its path
buffer pre-allocated buffer where to read data
len amount of chars/bytes/octets to read
Exceptions
std::runtime_error if there are file input issues
Definition at line 872 of file LoadFITS.cpp.
References Mantid::DataHandling::FITSInfo::filePath, g_BASE_HEADER_SIZE, Mantid::DataHandling::FITSInfo::headerSizeMultiplier, and std::to_string().
Referenced by readDataToImgs(), and readDataToWorkspace().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadFITS::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 48 of file LoadFITS.h.
setupDefaultKeywordNames()
void Mantid::DataHandling::LoadFITS::setupDefaultKeywordNames () private
Sets several keyword names with default (and standard) values.
You don't want to change these unless you want to break compatibility with the FITS standard.
Definition at line 1008 of file LoadFITS.cpp.
References m_headerAxisNameKeys, m_headerBitDepthKey, m_headerImageKeyKey, m_headerNAxisNameKey, m_headerOffsetKey, m_headerRotationKey, m_headerScaleKey, m_imageType, m_mapFile, and m_sampleRotation.
Referenced by LoadFITS().
summary()
const std::string Mantid::DataHandling::LoadFITS::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 44 of file LoadFITS.h.
version()
int Mantid::DataHandling::LoadFITS::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 47 of file LoadFITS.h.
Member Data Documentation
g_AXIS_NAMES_NAME
const std::string Mantid::DataHandling::LoadFITS::g_AXIS_NAMES_NAME = "AxisNames" static private
Definition at line 155 of file LoadFITS.h.
Referenced by mapHeaderKeys().
g_BASE_HEADER_SIZE
const int Mantid::DataHandling::LoadFITS::g_BASE_HEADER_SIZE = 2880 static private
size of a FITS header block (room for 36 entries, of 80 characters each), in bytes.
A FITS header always comes in multiples of this block.
Definition at line 145 of file LoadFITS.h.
Referenced by parseHeader(), and readInBuffer().
g_BIT_DEPTH_NAME
const std::string Mantid::DataHandling::LoadFITS::g_BIT_DEPTH_NAME = "BitDepthName" static private
Definition at line 154 of file LoadFITS.h.
Referenced by mapHeaderKeys().
g_COMMENT_KEYNAME
const std::string Mantid::DataHandling::LoadFITS::g_COMMENT_KEYNAME = "COMMENT" static private
Definition at line 152 of file LoadFITS.h.
Referenced by parseHeader().
g_defaultImgType
const std::string Mantid::DataHandling::LoadFITS::g_defaultImgType = "SAMPLE" static private
Definition at line 131 of file LoadFITS.h.
Referenced by loadHeader().
g_DIGIT_SIZE_APPEND
const size_t Mantid::DataHandling::LoadFITS::g_DIGIT_SIZE_APPEND = 6 static private
Definition at line 141 of file LoadFITS.h.
Referenced by makeWorkspace().
g_END_KEYNAME
const std::string Mantid::DataHandling::LoadFITS::g_END_KEYNAME = "END" static private
Definition at line 151 of file LoadFITS.h.
Referenced by parseHeader().
g_HEADER_MAP_NAME
const std::string Mantid::DataHandling::LoadFITS::g_HEADER_MAP_NAME = "HeaderMapFile" static private
Definition at line 158 of file LoadFITS.h.
Referenced by init(), and mapHeaderKeys().
g_IMAGE_KEY_NAME
const std::string Mantid::DataHandling::LoadFITS::g_IMAGE_KEY_NAME = "ImageKeyName" static private
Definition at line 157 of file LoadFITS.h.
Referenced by mapHeaderKeys().
g_maxBitDepth
const size_t Mantid::DataHandling::LoadFITS::g_maxBitDepth = 64 static private
Definition at line 162 of file LoadFITS.h.
g_maxBytesPP
const size_t Mantid::DataHandling::LoadFITS::g_maxBytesPP = g_maxBitDepth / 8 static private
Definition at line 164 of file LoadFITS.h.
Referenced by readDataToWorkspace().
g_ROTATION_NAME
const std::string Mantid::DataHandling::LoadFITS::g_ROTATION_NAME = "RotationName" static private
Definition at line 156 of file LoadFITS.h.
Referenced by mapHeaderKeys().
g_XTENSION_KEYNAME
const std::string Mantid::DataHandling::LoadFITS::g_XTENSION_KEYNAME = "XTENSION" static private
Definition at line 153 of file LoadFITS.h.
Referenced by loadHeader().
m_headerAxisNameKeys
std::vector<std::string> Mantid::DataHandling::LoadFITS::m_headerAxisNameKeys private
Definition at line 128 of file LoadFITS.h.
Referenced by loadHeader(), mapHeaderKeys(), and setupDefaultKeywordNames().
m_headerBitDepthKey
std::string Mantid::DataHandling::LoadFITS::m_headerBitDepthKey private
Definition at line 124 of file LoadFITS.h.
Referenced by loadHeader(), mapHeaderKeys(), and setupDefaultKeywordNames().
m_headerImageKeyKey
std::string Mantid::DataHandling::LoadFITS::m_headerImageKeyKey private
Definition at line 126 of file LoadFITS.h.
Referenced by loadHeader(), mapHeaderKeys(), and setupDefaultKeywordNames().
m_headerNAxisNameKey
std::string Mantid::DataHandling::LoadFITS::m_headerNAxisNameKey private
Definition at line 127 of file LoadFITS.h.
Referenced by loadHeader(), and setupDefaultKeywordNames().
m_headerOffsetKey
std::string Mantid::DataHandling::LoadFITS::m_headerOffsetKey private
Definition at line 123 of file LoadFITS.h.
Referenced by loadHeader(), and setupDefaultKeywordNames().
m_headerRotationKey
std::string Mantid::DataHandling::LoadFITS::m_headerRotationKey private
Definition at line 125 of file LoadFITS.h.
Referenced by mapHeaderKeys(), and setupDefaultKeywordNames().
m_headerScaleKey
std::string Mantid::DataHandling::LoadFITS::m_headerScaleKey private
Definition at line 122 of file LoadFITS.h.
Referenced by loadHeader(), and setupDefaultKeywordNames().
m_imageType
std::string Mantid::DataHandling::LoadFITS::m_imageType private
Definition at line 135 of file LoadFITS.h.
Referenced by setupDefaultKeywordNames().
m_mapFile
std::string Mantid::DataHandling::LoadFITS::m_mapFile private
Definition at line 129 of file LoadFITS.h.
Referenced by setupDefaultKeywordNames().
m_pixelCount
size_t Mantid::DataHandling::LoadFITS::m_pixelCount private
Definition at line 137 of file LoadFITS.h.
Referenced by doLoadFiles(), makeWorkspace(), readDataToImgs(), and readDataToWorkspace().
m_sampleRotation
std::string Mantid::DataHandling::LoadFITS::m_sampleRotation private
Definition at line 134 of file LoadFITS.h.
Referenced by addAxesInfoAndLogs(), and setupDefaultKeywordNames().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadFITS.h
Framework/DataHandling/src/LoadFITS.cpp