Mantid: Mantid::Crystal::ICluster Class Reference
Mantid::Crystal::ICluster Class Reference abstract
ICluster : Abstract cluster.
#include <ICluster.h>
Public Types
using ClusterIntegratedValues = boost::tuple< double, double >
Public Member Functions
virtual void addIndex (const size_t &index)=0
Track a linear IMDHistoWorkspace index that belongs to the cluster.
virtual bool containsLabel (const size_t &label) const =0
Is the label contained in the cluster.
virtual size_t getLabel () const =0
Get the cluster label.
virtual size_t getOriginalLabel () const =0
Get the originally set label.
virtual size_t getRepresentitiveIndex () const =0
Get a represetiative index of the cluster.
virtual ClusterIntegratedValues integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const =0
integrate the cluster
virtual void setRootCluster (ICluster const *root)=0
Set the root cluster.
virtual size_t size () const =0
Number of indexes tracked.
virtual void toUniformMinimum (std::vector< DisjointElement > &disjointSet)=0
Resolve the proper label for this cluster.
virtual void writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const =0
Apply labels to the workspace.
virtual ~ICluster ()=default
Virtual destructor.
Detailed Description
ICluster : Abstract cluster.
Identifies neighbour elements in an image that are connected.
Definition at line 24 of file ICluster.h.
Member Typedef Documentation
ClusterIntegratedValues
using Mantid::Crystal::ICluster::ClusterIntegratedValues = boost::tuple<double, double>
Definition at line 26 of file ICluster.h.
Constructor & Destructor Documentation
~ICluster()
virtual Mantid::Crystal::ICluster::~ICluster () virtual default
Virtual destructor.
Member Function Documentation
addIndex()
virtual void Mantid::Crystal::ICluster::addIndex (const size_t & index) pure virtual
Track a linear IMDHistoWorkspace index that belongs to the cluster.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
containsLabel()
virtual bool Mantid::Crystal::ICluster::containsLabel (const size_t & label) const pure virtual
Is the label contained in the cluster.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
getLabel()
virtual size_t Mantid::Crystal::ICluster::getLabel () const pure virtual
Get the cluster label.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
Referenced by Mantid::Crystal::CompositeCluster::findMinimum(), Mantid::Crystal::Cluster::getLabel(), and Mantid::Crystal::CompositeCluster::toUniformMinimum().
getOriginalLabel()
virtual size_t Mantid::Crystal::ICluster::getOriginalLabel () const pure virtual
Get the originally set label.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
getRepresentitiveIndex()
virtual size_t Mantid::Crystal::ICluster::getRepresentitiveIndex () const pure virtual
Get a represetiative index of the cluster.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
Referenced by Mantid::Crystal::Cluster::toUniformMinimum().
integrate()
virtual ClusterIntegratedValues Mantid::Crystal::ICluster::integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const pure virtual
integrate the cluster
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
Referenced by Mantid::Crystal::IntegratePeaksHybrid::exec(), and Mantid::Crystal::IntegratePeaksUsingClusters::exec().
setRootCluster()
virtual void Mantid::Crystal::ICluster::setRootCluster (ICluster const * root) pure virtual
Set the root cluster.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
Referenced by Mantid::Crystal::CompositeCluster::toUniformMinimum().
size()
virtual size_t Mantid::Crystal::ICluster::size () const pure virtual
Number of indexes tracked.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
toUniformMinimum()
virtual void Mantid::Crystal::ICluster::toUniformMinimum (std::vector< DisjointElement > & disjointSet) pure virtual
Resolve the proper label for this cluster.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
writeTo()
virtual void Mantid::Crystal::ICluster::writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const pure virtual
Apply labels to the workspace.
Implemented in Mantid::Crystal::Cluster, and Mantid::Crystal::CompositeCluster.
The documentation for this class was generated from the following file:
Framework/Crystal/inc/MantidCrystal/ICluster.h