Mantid: Mantid::Geometry::OrientedLattice Class Reference
Mantid::Geometry::OrientedLattice Class Reference
Class to implement UB matrix.
#include <Geometry/Crystal/OrientedLattice.h>
Public Member Functions
Kernel::V3D cosFromDir (const Kernel::V3D &dir) const
Calculate the direction cosine corresponding to a given direction.
const Kernel::DblMatrix & getModUB () const
const Kernel::DblMatrix & getU () const
Get the U matrix.
const Kernel::DblMatrix & getUB () const
Get the UB matrix.
Kernel::V3D getuVector () const
gets a vector along beam direction when goniometers are at 0.
Kernel::V3D getvVector () const
gets a vector in the horizontal plane, perpendicular to the beam direction when goniometers are at 0.
Kernel::V3D hklFromQ (const Kernel::V3D &Q) const
Calculate the hkl corresponding to a given Q-vector.
void loadNexus (Nexus::File *file, const std::string &group)
Load the object from an open NeXus file.
bool operator!= (const OrientedLattice &other) const
bool operator== (const OrientedLattice &other) const
OrientedLattice (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true), const int angleunit=angDegrees)
Constructor.
OrientedLattice (const double _a, const double _b, const double _c, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
Constructor.
OrientedLattice (const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
Default constructor.
OrientedLattice (const UnitCell &uc, const Kernel::DblMatrix &Umatrix=Kernel::DblMatrix(3, 3, true))
UnitCell constructor.
Kernel::V3D qFromHKL (const Kernel::V3D &hkl) const
Calculate the hkl corresponding to a given Q-vector.
void saveNexus (Nexus::File *file, const std::string &group) const
Save the object to an open NeXus file.
void setModUB (const Kernel::DblMatrix &newModUB)
Sets the Modulation UB matrix.
void setU (const Kernel::DblMatrix &newU, const bool force=true)
Sets the U matrix.
void setUB (const Kernel::DblMatrix &newUB)
Sets the UB matrix and recalculates lattice parameters.
const Kernel::DblMatrix & setUFromVectors (const Kernel::V3D &u, const Kernel::V3D &v)
Set the U rotation matrix, to provide the transformation, which translate an arbitrary vector V expressed in RLU (hkl) into another coordinate system defined by vectors u and v, expressed in RLU (hkl) Author: Alex Buts.
Public Member Functions inherited from Mantid::Geometry::UnitCell
double a () const
Get lattice parameter.
double a (int nd) const
Get lattice parameter a1-a3 as function of index (0-2)
double a1 () const
Get lattice parameter.
double a2 () const
Get lattice parameter.
double a3 () const
Get lattice parameter.
double alpha () const
Get lattice parameter.
double alpha1 () const
Get lattice parameter.
double alpha2 () const
Get lattice parameter.
double alpha3 () const
Get lattice parameter.
double alphastar () const
Get reciprocal lattice parameter.
double astar () const
Get reciprocal lattice parameter.
double b () const
Get lattice parameter.
double b1 () const
Get reciprocal lattice parameter.
double b2 () const
Get reciprocal lattice parameter.
double b3 () const
Get reciprocal lattice parameter.
double beta () const
Get lattice parameter.
double beta1 () const
Get reciprocal lattice parameter.
double beta2 () const
Get reciprocal lattice parameter.
double beta3 () const
Get reciprocal lattice parameter.
double betastar () const
Get reciprocal lattice parameter.
double bstar () const
Get reciprocal lattice parameter.
double c () const
Get lattice parameter.
double cstar () const
Get reciprocal lattice parameter.
double d (const Kernel::V3D &hkl) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double d (double h, double k, double l) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double dstar (const Kernel::V3D &hkl) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double dstar (double h, double k, double l) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double errora () const
Get lattice parameter error.
double erroralpha (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorb () const
Get lattice parameter error.
double errorbeta (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorc () const
Get lattice parameter error.
double errorgamma (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorvolume () const
Get lattice parameter error.
double gamma () const
Get lattice parameter.
double gammastar () const
Get reciprocal lattice parameter.
const Kernel::DblMatrix & getB () const
Get the B-matrix.
const Kernel::DblMatrix & getBinv () const
Get the inverse of the B-matrix.
bool getCrossTerm () const
Get cross term boolean.
double getdh (int j) const
Get modulation vectors for satellites.
double getdherr (int j) const
Get error of modulation vectors for satellites.
double getdk (int j) const
Get modulation vectors for satellites.
double getdkerr (int j) const
Get error of modulation vectors for satellites.
double getdl (int j) const
Get modulation vectors for satellites.
double getdlerr (int j) const
Get error of modulation vectors for satellites.
const Kernel::DblMatrix & getG () const
Get the metric tensor.
const Kernel::DblMatrix & getGstar () const
Get the reciprocal metric tensor.
int getMaxOrder () const
Get max order.
const Kernel::DblMatrix & getModHKL () const
Get modulation vectors for satellites.
const Kernel::V3D getModVec (int j) const
Get modulation vectors for satellites.
const Kernel::V3D getVecErr (int j) const
Get errors for modulation vectors for satellites.
bool operator!= (const UnitCell &other) const
bool operator== (const UnitCell &other) const
double recAngle (double h1, double k1, double l1, double h2, double k2, double l2, const int angleunit=angDegrees) const
Calculate the angle in degrees or radians between two reciprocal vectors (h1,k1,l1) and (h2,k2,l2)
double recVolume () const
Volume of the reciprocal lattice.
void set (double _a, double _b, double _c, double _alpha, double _beta, double _gamma, const int angleunit=angDegrees)
Set lattice parameters.
void seta (double _a)
Set lattice parameter.
void setalpha (double _alpha, const int angleunit=angDegrees)
Set lattice parameter.
void setb (double _b)
Set lattice parameter.
void setbeta (double _beta, const int angleunit=angDegrees)
Set lattice parameter.
void setc (double _c)
Set lattice parameter.
void setCrossTerm (bool CT)
Set modulation vectors for satellites.
void setError (double _aerr, double _berr, double _cerr, double _alphaerr, double _betaerr, double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter errors.
void setErrora (double _aerr)
Set lattice parameter error.
void setErroralpha (double _alphaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorb (double _berr)
Set lattice parameter error.
void setErrorbeta (double _betaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorc (double _cerr)
Set lattice parameter error.
void setErrorgamma (double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorModHKL (const Kernel::DblMatrix &newErrorModHKL)
Set modulation vectors for satellites.
void setErrorModHKL (double _dh1err, double _dk1err, double _dl1err, double _dh2err, double _dk2err, double _dl2err, double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setgamma (double _gamma, const int angleunit=angDegrees)
Set lattice parameter.
void setMaxOrder (int MaxO)
Set modulation vectors for satellites.
void setModerr (int i, double _dherr, double _dkerr, double _dlerr)
Set modulation vectors for satellites.
void setModerr1 (double _dh1err, double _dk1err, double _dl1err)
Set modulation vectors for satellites.
void setModerr2 (double _dh2err, double _dk2err, double _dl2err)
Set modulation vectors for satellites.
void setModerr3 (double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setModHKL (const Kernel::DblMatrix &newModHKL)
Set modulation vectors for satellites.
void setModHKL (double _dh1, double _dk1, double _dl1, double _dh2, double _dk2, double _dl2, double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
void setModVec1 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec1 (double _dh1, double _dk1, double _dl1)
Set modulation vectors for satellites.
void setModVec2 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec2 (double _dh2, double _dk2, double _dl2)
Set modulation vectors for satellites.
void setModVec3 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec3 (double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
UnitCell ()
Default constructor.
UnitCell (const double _a, const double _b, const double _c)
Constructor.
UnitCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const int angleunit=angDegrees)
Constructor.
double volume () const
Volume of the direct unit-cell.
virtual ~UnitCell ()=default
Static Public Member Functions
static bool GetABC (const Kernel::DblMatrix &UB, Kernel::V3D &a_dir, Kernel::V3D &b_dir, Kernel::V3D &c_dir)
Get the real space edge vectors a,b,c corresponding to the UB matrix.
static bool GetUB (Kernel::DblMatrix &UB, const Kernel::V3D &a_dir, const Kernel::V3D &b_dir, const Kernel::V3D &c_dir)
Get the UB matrix corresponding to the real space edge vectors a,b,c.
Private Member Functions
void recalculate () override
Private function, called at initialization or whenever lattice parameters are changed.
void recalculateFromGstar (const Kernel::DblMatrix &NewGstar) override
Make recalculateFrom private.
Private Attributes
Kernel::DblMatrix ModUB
Kernel::DblMatrix U
Kernel::DblMatrix UB
Additional Inherited Members
Protected Member Functions inherited from Mantid::Geometry::UnitCell
void calculateB ()
Private function to calculate B matrix.
void calculateG ()
void calculateGstar ()
Private function to calculate Gstar matrix.
void calculateReciprocalLattice ()
Private function to calculate reciprocal lattice parameters.
Protected Attributes inherited from Mantid::Geometry::UnitCell
Kernel::DblMatrix B
B matrix for a right-handed coordinate system, in Busing-Levy convention.
Kernel::DblMatrix Binv
Inverse of the B matrix.
bool CrossTerm
std::vector< double > da
Lattice parameter a,b,c,alpha,beta,gamma (in \(\mbox{ \AA } \) and radians)
std::vector< double > errorda
Error in lattice parameters (in \(\mbox{ \AA } \) and radians)
Kernel::DblMatrix errorModHKL
Kernel::DblMatrix G
Metric tensor.
Kernel::DblMatrix Gstar
Reciprocal lattice tensor.
int MaxOrder
Kernel::DblMatrix ModHKL
std::vector< double > ra
Reciprocal lattice parameters (in \(\mbox{ \AA }^{-1} \) and radians)
Detailed Description
Class to implement UB matrix.
See documentation about UB matrix in the Mantid repository.
Author
Andrei Savici, SNS, ORNL
Date
2011-04-15
Definition at line 21 of file OrientedLattice.h.
Constructor & Destructor Documentation
OrientedLattice() [1/4]
Mantid::Geometry::OrientedLattice::OrientedLattice (const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
Default constructor.
Parameters
Umatrix :: orientation matrix U. By default this will be identity matrix
Definition at line 21 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Kernel::Matrix< T >::isRotation(), ModUB, U, and UB.
OrientedLattice() [2/4]
Mantid::Geometry::OrientedLattice::OrientedLattice (const double _a, const double _b, const double _c, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
Constructor.
Parameters
_a :: lattice parameter \(a \) with \(\alpha = \beta = \gamma = 90^\circ \)
_b :: lattice parameter \(b \) with \(\alpha = \beta = \gamma = 90^\circ \)
_c :: lattice parameter \(c \) with \(\alpha = \beta = \gamma = 90^\circ \)
Umatrix :: orientation matrix U
Definition at line 39 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Kernel::Matrix< T >::isRotation(), ModUB, U, and UB.
OrientedLattice() [3/4]
Mantid::Geometry::OrientedLattice::OrientedLattice (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true), const int angleunit = angDegrees)
Constructor.
Parameters
_a :: lattice parameter \(a \)
_b :: lattice parameter \(b \)
_c :: lattice parameter \(c \)
_alpha :: lattice parameter \(\alpha \)
_beta :: lattice parameter \(\beta \)
_gamma :: lattice parameter \(\gamma \)
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Umatrix :: orientation matrix U
Definition at line 59 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Kernel::Matrix< T >::isRotation(), ModUB, U, and UB.
OrientedLattice() [4/4]
Mantid::Geometry::OrientedLattice::OrientedLattice (const UnitCell & uc, const Kernel::DblMatrix & Umatrix = Kernel::DblMatrix(3, 3, true))
UnitCell constructor.
Parameters
uc :: UnitCell
Umatrix :: orientation matrix U. By default this will be identity matrix
Definition at line 74 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Kernel::Matrix< T >::isRotation(), ModUB, U, and UB.
Member Function Documentation
cosFromDir()
V3D Mantid::Geometry::OrientedLattice::cosFromDir (const Kernel::V3D & dir) const
Calculate the direction cosine corresponding to a given direction.
Parameters
dir :: a direction unit-vector in the sample frame
Returns
a V3D
Definition at line 156 of file OrientedLattice.cpp.
References getUB(), Mantid::Kernel::V3D::normalize(), and Mantid::Kernel::Matrix< T >::setRow().
Referenced by Mantid::Crystal::SaveHKL::exec().
GetABC()
bool Mantid::Geometry::OrientedLattice::GetABC (const Kernel::DblMatrix & UB, Kernel::V3D & a_dir, Kernel::V3D & b_dir, Kernel::V3D & c_dir) static
Get the real space edge vectors a,b,c corresponding to the UB matrix.
The rows of the inverse of the matrix with will be stored in a_dir, b_dir, c_dir.
Parameters
UB A 3x3 matrix containing a UB matrix.
a_dir Will be set to the real space edge vector for side a of the unit cell
b_dir Will be set to the real space edge vector for side b of the unit cell
c_dir Will be set to the real space edge vector for side c of the unit cell
Returns
true if the inverse of the matrix UB could be found and the a_dir, b_dir and c_dir vectors have been set to the rows of UB inverse.
Definition at line 381 of file OrientedLattice.cpp.
References Mantid::Kernel::Matrix< T >::Invert(), Mantid::Kernel::Matrix< T >::numCols(), Mantid::Kernel::Matrix< T >::numRows(), and UB.
Referenced by Mantid::Geometry::CompareABCsum(), Mantid::Geometry::GetDiffFrom90Sum(), Mantid::Geometry::ScalarUtils::GetRelatedUBs(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::ConventionalCell::SetSidesIncreasing(), Mantid::Geometry::ConventionalCell::StandardizeHexagonal(), and Mantid::Geometry::ConventionalCell::StandardizeTetragonal().
getModUB()
const DblMatrix & Mantid::Geometry::OrientedLattice::getModUB () const
Definition at line 97 of file OrientedLattice.cpp.
References ModUB.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), and export_OrientedLattice().
getU()
const DblMatrix & Mantid::Geometry::OrientedLattice::getU () const
Get the U matrix.
Returns
U :: U orientation matrix
Definition at line 85 of file OrientedLattice.cpp.
References U.
Referenced by Mantid::Algorithms::CopySample::copyParameters(), export_OrientedLattice(), and setUFromVectors().
getUB()
const DblMatrix & Mantid::Geometry::OrientedLattice::getUB () const
Get the UB matrix.
The UB Matrix uses the inelastic convention: q = UB . (hkl) where q is the wavevector transfer of the LATTICE (not the neutron). and |q| = 1.0/d_spacing
Returns
UB :: UB orientation matrix
Definition at line 95 of file OrientedLattice.cpp.
References UB.
Referenced by cosFromDir(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SCDCalibratePanels::exec(), Mantid::Crystal::ShowPossibleCells::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), export_OrientedLattice(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), hklFromQ(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), and setModUB().
GetUB()
bool Mantid::Geometry::OrientedLattice::GetUB (Kernel::DblMatrix & UB, const Kernel::V3D & a_dir, const Kernel::V3D & b_dir, const Kernel::V3D & c_dir) static
Get the UB matrix corresponding to the real space edge vectors a,b,c.
The inverse of the matrix with vectors a,b,c as rows will be stored in UB.
Parameters
UB A 3x3 matrix that will be set to the UB matrix.
a_dir The real space edge vector for side a of the unit cell
b_dir The real space edge vector for side b of the unit cell
c_dir The real space edge vector for side c of the unit cell
Returns
true if UB was set to the new matrix and false if UB could not be set since the matrix with a,b,c as rows could not be inverted.
Definition at line 348 of file OrientedLattice.cpp.
References Mantid::Kernel::Matrix< T >::Invert(), Mantid::Kernel::Matrix< T >::numCols(), Mantid::Kernel::Matrix< T >::numRows(), Mantid::Kernel::Matrix< T >::setRow(), and UB.
Referenced by Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::Geometry::ScalarUtils::GetRelatedUBs(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::Geometry::ConventionalCell::SetSidesIncreasing(), Mantid::Geometry::ConventionalCell::StandardizeHexagonal(), and Mantid::Geometry::ConventionalCell::StandardizeTetragonal().
getuVector()
Kernel::V3D Mantid::Geometry::OrientedLattice::getuVector () const
gets a vector along beam direction when goniometers are at 0.
Note, this vector is not unique, but all vectors can be obtaineb by multiplying with a scalar
Returns
u :: V3D vector along beam direction
Definition at line 182 of file OrientedLattice.cpp.
References Mantid::Kernel::Matrix< T >::Invert(), UB, and Mantid::Geometry::z.
Referenced by export_OrientedLattice().
getvVector()
Kernel::V3D Mantid::Geometry::OrientedLattice::getvVector () const
gets a vector in the horizontal plane, perpendicular to the beam direction when goniometers are at 0.
Note, this vector is not unique, but all vectors can be obtaineb by multiplying with a scalar
Returns
v :: V3D vector perpendicular to the beam direction, in the horizontal plane
Definition at line 195 of file OrientedLattice.cpp.
References Mantid::Kernel::Matrix< T >::Invert(), UB, and Mantid::Geometry::x.
Referenced by export_OrientedLattice().
hklFromQ()
V3D Mantid::Geometry::OrientedLattice::hklFromQ (const Kernel::V3D & Q) const
Calculate the hkl corresponding to a given Q-vector.
Parameters
Q :: Q-vector in $AA^-1 in the sample frame
Returns
a V3D with H,K,L
Definition at line 145 of file OrientedLattice.cpp.
References getUB(), and Mantid::Kernel::Matrix< T >::Invert().
loadNexus()
void Mantid::Geometry::OrientedLattice::loadNexus (Nexus::File * file, const std::string & group)
Load the object from an open NeXus file.
Parameters
file :: open NeXus file
group :: name of the group to open
Definition at line 295 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::errora(), Mantid::Geometry::UnitCell::erroralpha(), Mantid::Geometry::UnitCell::errorb(), Mantid::Geometry::UnitCell::errorbeta(), Mantid::Geometry::UnitCell::errorc(), Mantid::Geometry::UnitCell::errorgamma(), Mantid::Geometry::UnitCell::errorModHKL, group, maxOrder, Mantid::Geometry::UnitCell::setCrossTerm(), Mantid::Geometry::UnitCell::setError(), Mantid::Geometry::UnitCell::setErrorModHKL(), Mantid::Geometry::UnitCell::setMaxOrder(), setModUB(), and setUB().
operator!=()
bool Mantid::Geometry::OrientedLattice::operator!= (const OrientedLattice & other) const
Definition at line 405 of file OrientedLattice.cpp.
References UB.
operator==()
bool Mantid::Geometry::OrientedLattice::operator== (const OrientedLattice & other) const
Definition at line 404 of file OrientedLattice.cpp.
References UB.
qFromHKL()
V3D Mantid::Geometry::OrientedLattice::qFromHKL (const Kernel::V3D & hkl) const
Calculate the hkl corresponding to a given Q-vector.
Parameters
hkl a V3D with H,K,L
Returns
Q-vector in $AA^-1 in the sample frame
Definition at line 176 of file OrientedLattice.cpp.
References UB.
Referenced by Mantid::Crystal::SCDPanelErrors::eval().
recalculate()
void Mantid::Geometry::OrientedLattice::recalculate () override private virtual
Private function, called at initialization or whenever lattice parameters are changed.
Reimplemented from Mantid::Geometry::UnitCell.
Definition at line 400 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::recalculate(), U, and UB.
recalculateFromGstar()
void Mantid::Geometry::OrientedLattice::recalculateFromGstar (const Kernel::DblMatrix & NewGstar) inline override private virtual
Make recalculateFrom private.
Reimplemented from Mantid::Geometry::UnitCell.
Definition at line 73 of file OrientedLattice.h.
Referenced by setUB().
saveNexus()
void Mantid::Geometry::OrientedLattice::saveNexus (Nexus::File * file, const std::string & group) const
Save the object to an open NeXus file.
Parameters
file :: open NeXus file
group :: name of the group to create
Definition at line 261 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::a(), Mantid::Geometry::UnitCell::alpha(), Mantid::Geometry::UnitCell::b(), Mantid::Geometry::UnitCell::beta(), Mantid::Geometry::UnitCell::c(), Mantid::Geometry::UnitCell::errora(), Mantid::Geometry::UnitCell::erroralpha(), Mantid::Geometry::UnitCell::errorb(), Mantid::Geometry::UnitCell::errorbeta(), Mantid::Geometry::UnitCell::errorc(), Mantid::Geometry::UnitCell::errorgamma(), Mantid::Geometry::UnitCell::errorModHKL, Mantid::Geometry::UnitCell::gamma(), Mantid::Geometry::UnitCell::getCrossTerm(), Mantid::Geometry::UnitCell::getMaxOrder(), Mantid::Kernel::Matrix< T >::getVector(), group, ModUB, and UB.
setModUB()
void Mantid::Geometry::OrientedLattice::setModUB (const Kernel::DblMatrix & newModUB)
Sets the Modulation UB matrix.
Parameters
newModUB :: the new Modulation UB matrix
Definition at line 132 of file OrientedLattice.cpp.
References getUB(), Mantid::Kernel::Matrix< T >::Invert(), ModUB, and Mantid::Geometry::UnitCell::setModHKL().
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::Geometry::IndexingUtils::GetModulationVector(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and loadNexus().
setU()
void Mantid::Geometry::OrientedLattice::setU (const Kernel::DblMatrix & newU, const bool force = true)
Sets the U matrix.
Parameters
newU :: the new U matrix
force :: If true, do not check that U matrix is valid
Definition at line 103 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Kernel::Matrix< T >::isOrthogonal(), Mantid::Kernel::Matrix< T >::isRotation(), ModUB, U, and UB.
Referenced by Mantid::Algorithms::CopySample::copyParameters(), and setUFromVectors().
setUB()
void Mantid::Geometry::OrientedLattice::setUB (const Kernel::DblMatrix & newUB)
Sets the UB matrix and recalculates lattice parameters.
Parameters
newUB :: the new UB matrix
Definition at line 115 of file OrientedLattice.cpp.
References Mantid::Geometry::UnitCell::B, Mantid::Kernel::Matrix< T >::determinant(), Mantid::Geometry::UnitCell::getB(), Mantid::Kernel::Matrix< T >::Invert(), recalculateFromGstar(), Mantid::Kernel::Matrix< T >::Tprime(), U, and UB.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::Geometry::IndexingUtils::Find_UB(), Mantid::MDAlgorithms::MDNorm::getBinParameters(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::IndexingUtils::GetModulationVector(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and loadNexus().
setUFromVectors()
const DblMatrix & Mantid::Geometry::OrientedLattice::setUFromVectors (const Kernel::V3D & u, const Kernel::V3D & v)
Set the U rotation matrix, to provide the transformation, which translate an arbitrary vector V expressed in RLU (hkl) into another coordinate system defined by vectors u and v, expressed in RLU (hkl) Author: Alex Buts.
Parameters
u :: first vector of new coordinate system (in hkl units)
v :: second vector of the new coordinate system
Returns
the U matrix calculated The transformation from old coordinate system to new coordinate system is performed by the whole UB matrix
Definition at line 215 of file OrientedLattice.cpp.
References Mantid::Kernel::V3D::cross_prod(), Mantid::Geometry::UnitCell::getB(), getU(), Mantid::Kernel::V3D::norm(), Mantid::Kernel::V3D::norm2(), Mantid::Kernel::V3D::normalize(), and setU().
Referenced by Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace().
Member Data Documentation
ModUB
Kernel::DblMatrix Mantid::Geometry::OrientedLattice::ModUB private
Definition at line 70 of file OrientedLattice.h.
Referenced by getModUB(), OrientedLattice(), OrientedLattice(), OrientedLattice(), OrientedLattice(), saveNexus(), setModUB(), and setU().
U
Kernel::DblMatrix Mantid::Geometry::OrientedLattice::U private
Definition at line 68 of file OrientedLattice.h.
Referenced by getU(), OrientedLattice(), OrientedLattice(), OrientedLattice(), OrientedLattice(), recalculate(), setU(), and setUB().
UB
Kernel::DblMatrix Mantid::Geometry::OrientedLattice::UB private
Definition at line 69 of file OrientedLattice.h.
Referenced by GetABC(), getUB(), GetUB(), getuVector(), getvVector(), operator!=(), operator==(), OrientedLattice(), OrientedLattice(), OrientedLattice(), OrientedLattice(), qFromHKL(), recalculate(), saveNexus(), setU(), and setUB().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/OrientedLattice.h
Framework/Geometry/src/Crystal/OrientedLattice.cpp