Mantid: Mantid::MDAlgorithms::UserFunctionMD Class Reference
Mantid::MDAlgorithms::UserFunctionMD Class Reference
A user defined function.
#include <UserFunctionMD.h>
Public Member Functions
Attribute getAttribute (const std::string &attName) const override
Return Formula.
std::vector< std::string > getAttributeNames () const override
bool hasAttribute (const std::string &attName) const override
Has attribute "Formula".
void initDimensions () override
Defining function's parameters here, ie after the workspace is set and the dimensions are known.
std::string name () const override
Returns the function's name.
void setAttribute (const std::string &attName, const Attribute &attr) override
Set Formula.
UserFunctionMD ()
Default constructor.
Public Member Functions inherited from Mantid::API::IFunctionMD
std::shared_ptr< IFunction > clone () const override
Virtual copy constructor.
void function (const FunctionDomain &domain, FunctionValues &values) const override
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
void setWorkspace (std::shared_ptr< const Workspace > ws) override
Set the workspace.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void function (const FunctionDomain &domain, FunctionValues &values) const =0
Evaluates the function for all arguments in the domain.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies ()
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual void setUpForFit ()
Set up the function for a fit.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Protected Member Functions
double functionMD (const API::IMDIterator &r) const override
Calculate the function value at a point r in the MD workspace.
void setFormula ()
Initializes the mu::Parser.
Protected Member Functions inherited from Mantid::API::IFunctionMD
void evaluateFunction (const FunctionDomainMD &domain, FunctionValues &values) const
Performs the function evaluations on the MD domain.
virtual double functionMD (const IMDIterator &r) const =0
Does the function evaluation. Must be implemented in derived classes.
virtual void initDimensions ()
Do finction initialization after useAllDimensions() was called.
virtual void useDimension (const std::string &id)
User functions call this method in their constructors to set up the order of the dimensions.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Static Protected Member Functions
static double * AddVariable (const char *varName, void *pufun)
Static callback function used by MuParser to initialize variables implicitly.
Private Attributes
std::string m_formula
mu::Parser m_parser
Expression parser.
std::vector< std::string > m_varNames
std::vector< double > m_vars
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Attributes inherited from Mantid::API::IFunctionMD
std::map< std::string, size_t > m_dimensionIndexMap
maps dimension id to its index in m_dimensions
std::vector< std::shared_ptr< const Mantid::Geometry::IMDDimension > > m_dimensions
dimensions used in this function in the expected order
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
A user defined function.
Author
Roman Tolchenov, Tessella plc
Date
15/01/2010
Definition at line 26 of file UserFunctionMD.h.
Constructor & Destructor Documentation
UserFunctionMD()
Mantid::MDAlgorithms::UserFunctionMD::UserFunctionMD ()
Default constructor.
Definition at line 22 of file UserFunctionMD.cpp.
Member Function Documentation
AddVariable()
double * Mantid::MDAlgorithms::UserFunctionMD::AddVariable (const char * varName, void * pufun) static protected
Static callback function used by MuParser to initialize variables implicitly.
Parameters
varName :: The name of a new variable
pufun :: Pointer to the function
Definition at line 104 of file UserFunctionMD.cpp.
References Mantid::API::ParamFunction::declareParameter(), m_varNames, m_vars, and Mantid::Geometry::x.
Referenced by setFormula().
functionMD()
double Mantid::MDAlgorithms::UserFunctionMD::functionMD (const API::IMDIterator & r) const override protected virtual
Calculate the function value at a point r in the MD workspace.
Evaluate the function at MD iterator r.
Parameters
r :: MD workspace iterator with a reference to the current point
r :: MD iterator.
Implements Mantid::API::IFunctionMD.
Definition at line 77 of file UserFunctionMD.cpp.
References Mantid::API::IFunctionMD::function(), Mantid::API::IMDIterator::getCenter(), Mantid::API::IFunctionMD::m_dimensions, m_parser, m_vars, n, and PARALLEL_CRITICAL.
getAttribute()
UserFunctionMD::Attribute Mantid::MDAlgorithms::UserFunctionMD::getAttribute (const std::string & attName) const override virtual
Return Formula.
Reimplemented from Mantid::API::IFunction.
Definition at line 40 of file UserFunctionMD.cpp.
References m_formula, and UNUSED_ARG.
getAttributeNames()
std::vector< std::string > Mantid::MDAlgorithms::UserFunctionMD::getAttributeNames () const override virtual
Returns
A list of attribute names
Reimplemented from Mantid::API::IFunction.
Definition at line 34 of file UserFunctionMD.cpp.
hasAttribute()
bool Mantid::MDAlgorithms::UserFunctionMD::hasAttribute (const std::string & attName) const override virtual
Has attribute "Formula".
Reimplemented from Mantid::API::IFunction.
Definition at line 37 of file UserFunctionMD.cpp.
initDimensions()
void Mantid::MDAlgorithms::UserFunctionMD::initDimensions () override virtual
Defining function's parameters here, ie after the workspace is set and the dimensions are known.
Reimplemented from Mantid::API::IFunctionMD.
Definition at line 60 of file UserFunctionMD.cpp.
References Mantid::API::IFunctionMD::m_dimensionIndexMap, m_parser, m_varNames, m_vars, setFormula(), and std::to_string().
name()
std::string Mantid::MDAlgorithms::UserFunctionMD::name () const inline override virtual
Returns the function's name.
Implements Mantid::API::IFunction.
Definition at line 29 of file UserFunctionMD.h.
setAttribute()
void Mantid::MDAlgorithms::UserFunctionMD::setAttribute (const std::string & attName, const Attribute & attr) override virtual
Set Formula.
Parameters
attName :: Attribute name - must be "Formula"
attr :: Attribute value - the formula
Reimplemented from Mantid::API::IFunction.
Definition at line 49 of file UserFunctionMD.cpp.
References Mantid::API::IFunction::Attribute::asString(), m_formula, m_vars, setFormula(), and UNUSED_ARG.
setFormula()
void Mantid::MDAlgorithms::UserFunctionMD::setFormula () protected
Initializes the mu::Parser.
Definition at line 127 of file UserFunctionMD.cpp.
References AddVariable(), Mantid::API::ParamFunction::getParameterAddress(), m_formula, m_parser, m_varNames, m_vars, Mantid::API::ParamFunction::nParams(), and Mantid::API::ParamFunction::parameterName().
Referenced by initDimensions(), and setAttribute().
Member Data Documentation
m_formula
std::string Mantid::MDAlgorithms::UserFunctionMD::m_formula private
Definition at line 65 of file UserFunctionMD.h.
Referenced by getAttribute(), setAttribute(), and setFormula().
m_parser
mu::Parser Mantid::MDAlgorithms::UserFunctionMD::m_parser private
Expression parser.
Definition at line 61 of file UserFunctionMD.h.
Referenced by functionMD(), initDimensions(), and setFormula().
m_varNames
std::vector<std::string> Mantid::MDAlgorithms::UserFunctionMD::m_varNames private
Definition at line 64 of file UserFunctionMD.h.
Referenced by AddVariable(), initDimensions(), and setFormula().
m_vars
std::vector<double> Mantid::MDAlgorithms::UserFunctionMD::m_vars mutable private
Definition at line 63 of file UserFunctionMD.h.
Referenced by AddVariable(), functionMD(), initDimensions(), setAttribute(), and setFormula().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/UserFunctionMD.h
Framework/MDAlgorithms/src/UserFunctionMD.cpp