Mantid: MantidQt::API::FlowLayout Class Reference
MantidQt::API::FlowLayout Class Reference
#include <FlowLayout.h>
Public Member Functions
void addItem (QLayoutItem *item) override
int count () const override
Qt::Orientations expandingDirections () const override
FlowLayout (int margin=-1, int hSpacing=-1, int vSpacing=-1)
FlowLayout (QWidget *parent, int margin=-1, int hSpacing=-1, int vSpacing=-1)
bool hasHeightForWidth () const override
int heightForWidth (int) const override
int horizontalSpacing () const
QLayoutItem * itemAt (int index) const override
QSize minimumSize () const override
void setGeometry (const QRect &rect) override
QSize sizeHint () const override
QLayoutItem * takeAt (int index) override
int verticalSpacing () const
~FlowLayout () override
Private Member Functions
int doLayout (const QRect &rect, bool testOnly) const
int smartSpacing (QStyle::PixelMetric pm) const
Private Attributes
QList< QLayoutItem * > itemList
int m_hSpace
int m_vSpace
Detailed Description
Definition at line 51 of file FlowLayout.h.
Constructor & Destructor Documentation
FlowLayout() [1/2]
MantidQt::API::FlowLayout::FlowLayout (QWidget * parent, int margin = -1, int hSpacing = -1, int vSpacing = -1)
Definition at line 45 of file FlowLayout.cpp.
FlowLayout() [2/2]
MantidQt::API::FlowLayout::FlowLayout (int margin = -1, int hSpacing = -1, int vSpacing = -1)
Definition at line 50 of file FlowLayout.cpp.
~FlowLayout()
MantidQt::API::FlowLayout::~FlowLayout () override
Definition at line 54 of file FlowLayout.cpp.
References takeAt().
Member Function Documentation
addItem()
void MantidQt::API::FlowLayout::addItem (QLayoutItem * item) override
Definition at line 60 of file FlowLayout.cpp.
References itemList.
count()
int MantidQt::API::FlowLayout::count () const override
Definition at line 78 of file FlowLayout.cpp.
References itemList.
doLayout()
int MantidQt::API::FlowLayout::doLayout (const QRect & rect, bool testOnly) const private
Definition at line 114 of file FlowLayout.cpp.
References bottom, horizontalSpacing(), itemList, left, right, top, and verticalSpacing().
Referenced by heightForWidth(), and setGeometry().
expandingDirections()
Qt::Orientations MantidQt::API::FlowLayout::expandingDirections () const override
Definition at line 89 of file FlowLayout.cpp.
hasHeightForWidth()
bool MantidQt::API::FlowLayout::hasHeightForWidth () const override
Definition at line 91 of file FlowLayout.cpp.
heightForWidth()
int MantidQt::API::FlowLayout::heightForWidth (int width) const override
Definition at line 93 of file FlowLayout.cpp.
References doLayout(), and height.
horizontalSpacing()
int MantidQt::API::FlowLayout::horizontalSpacing () const
Definition at line 62 of file FlowLayout.cpp.
References m_hSpace, and smartSpacing().
Referenced by doLayout().
itemAt()
QLayoutItem * MantidQt::API::FlowLayout::itemAt (int index) const override
Definition at line 80 of file FlowLayout.cpp.
References index, and itemList.
minimumSize()
QSize MantidQt::API::FlowLayout::minimumSize () const override
Definition at line 105 of file FlowLayout.cpp.
References itemList.
Referenced by sizeHint().
setGeometry()
void MantidQt::API::FlowLayout::setGeometry (const QRect & rect) override
Definition at line 98 of file FlowLayout.cpp.
References doLayout().
sizeHint()
QSize MantidQt::API::FlowLayout::sizeHint () const override
Definition at line 103 of file FlowLayout.cpp.
References minimumSize().
smartSpacing()
int MantidQt::API::FlowLayout::smartSpacing (QStyle::PixelMetric pm) const private
Definition at line 146 of file FlowLayout.cpp.
Referenced by horizontalSpacing(), and verticalSpacing().
takeAt()
QLayoutItem * MantidQt::API::FlowLayout::takeAt (int index) override
Definition at line 82 of file FlowLayout.cpp.
References index, and itemList.
Referenced by ~FlowLayout().
verticalSpacing()
int MantidQt::API::FlowLayout::verticalSpacing () const
Definition at line 70 of file FlowLayout.cpp.
References m_vSpace, and smartSpacing().
Referenced by doLayout().
Member Data Documentation
itemList
QList<QLayoutItem *> MantidQt::API::FlowLayout::itemList private
Definition at line 74 of file FlowLayout.h.
Referenced by addItem(), count(), doLayout(), itemAt(), minimumSize(), and takeAt().
m_hSpace
int MantidQt::API::FlowLayout::m_hSpace private
Definition at line 75 of file FlowLayout.h.
Referenced by horizontalSpacing().
m_vSpace
int MantidQt::API::FlowLayout::m_vSpace private
Definition at line 76 of file FlowLayout.h.
Referenced by verticalSpacing().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FlowLayout.h
qt/widgets/common/src/FlowLayout.cpp