Mantid: Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator Class Reference
Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator Class Reference
#include <MSVesuvioHelpers.h>
Public Member Functions
double flat ()
Returns a flat random number between 0.0 & 1.0.
double gaussian (const double mean, const double sigma)
Returns a random number distributed by a normal distribution.
RandomVariateGenerator (const int seed)
Produces random numbers with various probability distributions.
Private Member Functions
RandomVariateGenerator ()
Private Attributes
std::mt19937 m_engine
Detailed Description
Definition at line 24 of file MSVesuvioHelpers.h.
Constructor & Destructor Documentation
RandomVariateGenerator() [1/2]
Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator::RandomVariateGenerator (const int seed)
Produces random numbers with various probability distributions.
Definition at line 273 of file MSVesuvioHelpers.cpp.
References m_engine.
RandomVariateGenerator() [2/2]
Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator::RandomVariateGenerator () private
Member Function Documentation
flat()
double Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator::flat ()
Returns a flat random number between 0.0 & 1.0.
Definition at line 277 of file MSVesuvioHelpers.cpp.
References m_engine.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::calculateCounts(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateDetectorPos(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateE0(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateE1(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateScatter(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateSrcPos(), and Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateTOF().
gaussian()
double Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator::gaussian (const double mean, const double sigma)
Returns a random number distributed by a normal distribution.
Returns a random number distributed following a normal distribution.
Definition at line 279 of file MSVesuvioHelpers.cpp.
References m_engine, and sigma.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateTOF().
Member Data Documentation
m_engine
std::mt19937 Mantid::CurveFitting::MSVesuvioHelper::RandomVariateGenerator::m_engine private
Definition at line 34 of file MSVesuvioHelpers.h.
Referenced by flat(), gaussian(), and RandomVariateGenerator().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/MSVesuvioHelpers.h
Framework/CurveFitting/src/MSVesuvioHelpers.cpp