Mantid: MantidQt::MantidWidgets::AlgorithmTreeWidget Class Reference
MantidQt::MantidWidgets::AlgorithmTreeWidget Class Reference
Tree widget with the categories and algorithms listed.
#include <AlgorithmSelectorWidget.h>
Public Slots
void update ()
Update the list of algos in the tree.
Signals
void executeAlgorithm (const QString &, int)
Signal emitted when the widget requests that we execute that algorithm.
Public Member Functions
AlgorithmTreeWidget (QWidget *w)
SelectedAlgorithm getSelectedAlgorithm ()
Return the selected algorithm in the tree.
void mouseDoubleClickEvent (QMouseEvent *e) override
SLOT called when double-clicking on an entry in the tree.
void mouseMoveEvent (QMouseEvent *e) override
SLOT called when dragging the mouse around the tree.
void mousePressEvent (QMouseEvent *e) override
SLOT called when clicking the mouse around the tree.
~AlgorithmTreeWidget () override=default
Private Attributes
QPoint m_dragStartPosition
Detailed Description
Tree widget with the categories and algorithms listed.
Definition at line 98 of file AlgorithmSelectorWidget.h.
Constructor & Destructor Documentation
AlgorithmTreeWidget()
MantidQt::MantidWidgets::AlgorithmTreeWidget::AlgorithmTreeWidget (QWidget * w) inline
Definition at line 101 of file AlgorithmSelectorWidget.h.
~AlgorithmTreeWidget()
MantidQt::MantidWidgets::AlgorithmTreeWidget::~AlgorithmTreeWidget () override default
Member Function Documentation
executeAlgorithm
void MantidQt::MantidWidgets::AlgorithmTreeWidget::executeAlgorithm (const QString & , int) signal
Signal emitted when the widget requests that we execute that algorithm.
Referenced by mouseDoubleClickEvent().
getSelectedAlgorithm()
SelectedAlgorithm MantidQt::MantidWidgets::AlgorithmTreeWidget::getSelectedAlgorithm ()
Return the selected algorithm in the tree.
Returns
:: algorithm selected by user
Definition at line 194 of file AlgorithmSelectorWidget.cpp.
References MantidQt::MantidWidgets::SelectedAlgorithm::name, and MantidQt::MantidWidgets::SelectedAlgorithm::version.
Referenced by MantidQt::MantidWidgets::AlgorithmSelectorWidget::getSelectedAlgorithm(), and mouseDoubleClickEvent().
mouseDoubleClickEvent()
void MantidQt::MantidWidgets::AlgorithmTreeWidget::mouseDoubleClickEvent (QMouseEvent * e) override
SLOT called when double-clicking on an entry in the tree.
Definition at line 244 of file AlgorithmSelectorWidget.cpp.
References executeAlgorithm(), and getSelectedAlgorithm().
mouseMoveEvent()
void MantidQt::MantidWidgets::AlgorithmTreeWidget::mouseMoveEvent (QMouseEvent * e) override
SLOT called when dragging the mouse around the tree.
Definition at line 225 of file AlgorithmSelectorWidget.cpp.
References m_dragStartPosition.
mousePressEvent()
void MantidQt::MantidWidgets::AlgorithmTreeWidget::mousePressEvent (QMouseEvent * e) override
SLOT called when clicking the mouse around the tree.
Definition at line 213 of file AlgorithmSelectorWidget.cpp.
References m_dragStartPosition.
update
void MantidQt::MantidWidgets::AlgorithmTreeWidget::update () slot
Update the list of algos in the tree.
Definition at line 256 of file AlgorithmSelectorWidget.cpp.
References n.
Referenced by MantidQt::MantidWidgets::AlgorithmSelectorWidget::update().
Member Data Documentation
m_dragStartPosition
QPoint MantidQt::MantidWidgets::AlgorithmTreeWidget::m_dragStartPosition private
Definition at line 116 of file AlgorithmSelectorWidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmSelectorWidget.h
qt/widgets/common/src/AlgorithmSelectorWidget.cpp