Mantid: ICat4::_ns1__login_credentials Class Reference
ICat4::_ns1__login_credentials Class Reference
#include <ICat4Stub.h>
Public Member Functions
_ns1__login_credentials ()
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
virtual ~_ns1__login_credentials ()=default
Public Attributes
std::vector< _ns1__login_credentials_entry > * entry
Detailed Description
Definition at line 942 of file ICat4Stub.h.
Constructor & Destructor Documentation
_ns1__login_credentials()
ICat4::_ns1__login_credentials::_ns1__login_credentials () inline
Definition at line 953 of file ICat4Stub.h.
~_ns1__login_credentials()
virtual ICat4::_ns1__login_credentials::~_ns1__login_credentials () virtual default
Member Function Documentation
soap_default()
void ICat4::_ns1__login_credentials::soap_default (struct soap * soap) virtual
Definition at line 5047 of file ICat4C.cpp.
Referenced by ICat4::soap_in__ns1__login_credentials(), ICat4::soap_new_req__ns1__login_credentials(), and ICat4::soap_new_set__ns1__login_credentials().
soap_get()
void * ICat4::_ns1__login_credentials::soap_get (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 5129 of file ICat4C.cpp.
References ICat4::soap_get__ns1__login_credentials().
soap_in()
void * ICat4::_ns1__login_credentials::soap_in (struct soap * soap, const char * tag, const char * type) virtual
Definition at line 5074 of file ICat4C.cpp.
References ICat4::soap_in__ns1__login_credentials().
Referenced by ICat4::soap_in__ns1__login_credentials().
soap_out()
int ICat4::_ns1__login_credentials::soap_out (struct soap * soap, const char * tag, int id, const char * type) const virtual
Definition at line 5060 of file ICat4C.cpp.
References ICat4::soap_out__ns1__login_credentials().
soap_put()
int ICat4::_ns1__login_credentials::soap_put (struct soap * soap, const char * tag, const char * type) const virtual
Definition at line 5122 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4__ns1__login_credentials.
soap_serialize()
void ICat4::_ns1__login_credentials::soap_serialize (struct soap * soap) const virtual
Definition at line 5052 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTostd__vectorTemplateOf_ns1__login_credentials_entry().
soap_type()
virtual int ICat4::_ns1__login_credentials::soap_type () const inline virtual
Definition at line 946 of file ICat4Stub.h.
Member Data Documentation
entry
std::vector<_ns1__login_credentials_entry>* ICat4::_ns1__login_credentials::entry
Definition at line 944 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp