Mantid: ISISRAW2 Class Reference
ISISRAW2 Class Reference
isis raw file.
#include <isisraw2.h>
Public Member Functions
void clear ()
Clears the output buffer.
int ioRAW (FILE *file, bool from_file, bool read_data=true) override
Loads the headers of the file, leaves the file pointer at a specific position.
ISISRAW2 ()
No arg Constructor.
bool readData (FILE *file, int i)
Read data.
void skipData (FILE *file, int i)
Skip data.
~ISISRAW2 () override
Public Member Functions inherited from ISISRAW
int getTimeChannels (float *rtcb1, int n)
rtcb1 is of size t_ntc1+1
int ioRAW (FILE *file, ADD_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, char **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, char *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, DAEP_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, DDES_STRUCT **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, DDES_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, DHDR_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, float **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, float *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, HDR_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, int **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, int *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, IVPB_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, LOG_LINE **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, LOG_LINE *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, LOG_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, RPB_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, SE_STRUCT **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, SE_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, SPB_STRUCT *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, uint32_t **s, int len, bool from_file)
stuff
int ioRAW (FILE *file, uint32_t *s, int len, bool from_file)
stuff
int ioRAW (FILE *file, USER_STRUCT *s, int len, bool from_file)
stuff
ISISRAW ()
stuff
ISISRAW (const ISISRAW &)=delete
ISISRAW (ISISCRPT_STRUCT *crpt)
stuff
ISISRAW (ISISCRPT_STRUCT *crpt, bool doUpdateFromCRPT)
stuff
ISISRAW & operator= (ISISRAW)=delete
int printInfo (std::ostream &os)
stuff
int readFromFile (const char *filename, bool read_data=true)
stuff
int size_check ()
stuff
int updateFromCRPT ()
stuff
virtual ~ISISRAW ()
stuff
Public Attributes
int ndes
ndes
Public Attributes inherited from ISISRAW
struct ADD_STRUCT add
9*4 bytes
int * code
code for UTn tables (size NDET)
int * crat
crate number for each detector (size NDET)
DAEP_STRUCT daep
DAE parameter block (size 64*4 bytes)
uint32_t * dat1
compressed data for (NTC1+1)*(NSP1+1)*NPER values
int data_format
data section format (0 = by TC, 1 = by spectrum)
DDES_STRUCT * ddes
(NSP1+1)*NPER items, totoal size (NSP1+1)*NPER*2*4 bytes
float * delt
hold off table (size NDET)
DHDR_STRUCT dhdr
size 32*4 bytes
int e_nse
number of controlled SEPs NSEP
SE_STRUCT * e_seblock
NSEP SE parameter blocks (total size NSEP*32*4 bytes)
int frmt_ver_no
format version number VER1 (=2)
HDR_STRUCT hdr
header block (80 bytes)
int i_det
number of detectors NDET
char i_inst [8]
instrument name
int i_mon
number of monitors NMON
int i_use
number of user defined UTn tables NUSE
IVPB_STRUCT ivpb
instrument parameter block (64*4 bytes)
float * len2
L2 table (size NDET)
LOG_STRUCT logsect
log section
int * mdet
detector number for monitors (size NMON)
int * modn
module number for each detector (size NDET)
int * monp
prescale value for each monitor (size NMON)
int * mpos
module position for each detector (size NDET)
int r_number
run number
char r_title [80]
run title
RPB_STRUCT rpb
run parameter block (32*4 bytes)
SPB_STRUCT spb
sample parameter block (64*4 bytes)
int * spec
spectrum number table (size NDET)
int t_nfpp
number of frames per period
int t_nper
number of periods
int t_nsp1
number of spectra in time regime 1
int t_ntc1
number of time channels in time regime 1
int t_ntrg
number of time regimes (=1)
int t_pmap [256]
period number for each basic period
int t_pre1
prescale for 32MHz clock
int * t_tcb1
time channel boundaries in clock pulses (size NTC1+1)
int t_tcm1 [5]
time channel mode
float t_tcp1 [5][4]
time channel parameters
int * timr
time regime for each detector (size NDET)
float * tthe
2theta scattering angle (size NDET)
float * u_dat
user defined data (ULEN, max size 400 words)
int u_len
length of user data section
int * udet
user detector number for each detector (size NDET)
USER_STRUCT user
user information (8*20 bytes)
float * ut
nuse UT* user tables (total size NUSE*NDET) ut01=phi
int ver2
run section version number VER2 (=1)
int ver3
instrument section version number (=2)
int ver4
SE section version number (=2)
int ver5
DAE section version number (=2)
int ver6
TCB section version number (=1)
int ver7
user version number (=1)
int ver8
data version number (=2)
Private Attributes
int m_bufferSize
char * outbuff
output buffer
Additional Inherited Members
Static Public Member Functions inherited from ISISRAW
static int vmstime (char *timbuf, int len, time_t time_value)
stuff
Detailed Description
isis raw file.
Definition at line 13 of file isisraw2.h.
Constructor & Destructor Documentation
ISISRAW2()
ISISRAW2::ISISRAW2 ()
No arg Constructor.
Definition at line 22 of file isisraw2.cpp.
References Mantid::Kernel::Logger::debug(), and m_bufferSize.
~ISISRAW2()
ISISRAW2::~ISISRAW2 () override
Definition at line 163 of file isisraw2.cpp.
References outbuff.
Member Function Documentation
clear()
void ISISRAW2::clear ()
Clears the output buffer.
Definition at line 169 of file isisraw2.cpp.
References outbuff.
ioRAW()
int ISISRAW2::ioRAW (FILE * file, bool from_file, bool read_data = true) override virtual
Loads the headers of the file, leaves the file pointer at a specific position.
Parameters
file :: The file handle to use
from_file :: Whether to read from or write to a file
read_data :: Whether to go on to read the data
Returns
file readin exit code, 0 is OK
Reimplemented from ISISRAW.
Definition at line 43 of file isisraw2.cpp.
References ADD_STRUCT::ad_dae, ADD_STRUCT::ad_data, ADD_STRUCT::ad_end, ADD_STRUCT::ad_inst, ADD_STRUCT::ad_log, ADD_STRUCT::ad_run, ADD_STRUCT::ad_se, ADD_STRUCT::ad_tcb, ADD_STRUCT::ad_user, ISISRAW::add, ISISRAW::code, ISISRAW::crat, ISISRAW::daep, ISISRAW::dat1, ISISRAW::data_format, ISISRAW::ddes, ISISRAW::delt, ISISRAW::dhdr, ISISRAW::e_nse, ISISRAW::e_seblock, Mantid::Kernel::Logger::error(), ISISRAW::frmt_ver_no, ISISRAW::hdr, ISISRAW::i_det, ISISRAW::i_inst, ISISRAW::i_mon, ISISRAW::i_use, ISISRAW::ioRAW(), ISISRAW::ivpb, ISISRAW::len2, m_bufferSize, ISISRAW::mdet, ISISRAW::modn, ISISRAW::monp, ISISRAW::mpos, ndes, outbuff, ISISRAW::r_title, ISISRAW::rpb, ISISRAW::spb, ISISRAW::spec, ISISRAW::t_nper, ISISRAW::t_nsp1, ISISRAW::t_ntc1, ISISRAW::t_pre1, ISISRAW::t_tcb1, ISISRAW::t_tcp1, ISISRAW::timr, ISISRAW::tthe, ISISRAW::u_dat, ISISRAW::u_len, ISISRAW::udet, ISISRAW::user, ISISRAW::ut, ISISRAW::ver3, ISISRAW::ver4, ISISRAW::ver5, ISISRAW::ver6, ISISRAW::ver7, and ISISRAW::ver8.
Referenced by Mantid::DataHandling::LoadRawHelper::ioRaw(), and Mantid::DataHandling::CreateSimulationWorkspace::loadMappingFromRAW().
readData()
bool ISISRAW2::readData (FILE * file, int i)
Read data.
Parameters
file :: The file pointer
i :: The amount of data to read
Returns
true on success
Definition at line 146 of file isisraw2.cpp.
References byte_rel_expn(), ISISRAW::dat1, ISISRAW::ddes, Mantid::Kernel::Logger::debug(), ISISRAW::ioRAW(), m_bufferSize, ndes, DDES_STRUCT::nwords, outbuff, and ISISRAW::t_ntc1.
Referenced by Mantid::DataHandling::LoadRawHelper::readData().
skipData()
void ISISRAW2::skipData (FILE * file, int i)
Skip data.
Parameters
file :: The file pointer
i :: The amount of data to skip
Definition at line 133 of file isisraw2.cpp.
References ISISRAW::ddes, ndes, and Mantid::Kernel::Logger::warning().
Referenced by Mantid::DataHandling::LoadRawHelper::skipData().
Member Data Documentation
m_bufferSize
int ISISRAW2::m_bufferSize private
Definition at line 27 of file isisraw2.h.
Referenced by ioRAW(), ISISRAW2(), and readData().
ndes
int ISISRAW2::ndes
ndes
Definition at line 24 of file isisraw2.h.
Referenced by ioRAW(), readData(), and skipData().
outbuff
char* ISISRAW2::outbuff private
output buffer
Definition at line 26 of file isisraw2.h.
Referenced by clear(), ioRAW(), readData(), and ~ISISRAW2().
The documentation for this class was generated from the following files:
Framework/DataHandling/src/LoadRaw/isisraw2.h
Framework/DataHandling/src/LoadRaw/isisraw2.cpp