Mantid: Mantid::Geometry::SolidAngleParams Class Reference
Mantid::Geometry::SolidAngleParams Class Reference
#include <SolidAngleParams.h>
Public Member Functions
const SolidAngleParams copyWithNewObserver (Kernel::V3D newObserver) const
int cylinderSlices () const
const Kernel::V3D & observer () const
SolidAngleParams (Kernel::V3D observer, int numberOfCylinderSlices=10)
Private Attributes
int m_numberOfCylinderSlices
Kernel::V3D m_observer
Detailed Description
Definition at line 16 of file SolidAngleParams.h.
Constructor & Destructor Documentation
SolidAngleParams()
Mantid::Geometry::SolidAngleParams::SolidAngleParams (Kernel::V3D observer, int numberOfCylinderSlices = 10) inline
Definition at line 18 of file SolidAngleParams.h.
Member Function Documentation
copyWithNewObserver()
const SolidAngleParams Mantid::Geometry::SolidAngleParams::copyWithNewObserver (Kernel::V3D newObserver) const inline
Definition at line 22 of file SolidAngleParams.h.
Referenced by Mantid::Geometry::ObjComponent::solidAngle(), and Mantid::Geometry::ComponentInfo::solidAngle().
cylinderSlices()
int Mantid::Geometry::SolidAngleParams::cylinderSlices () const inline
Definition at line 21 of file SolidAngleParams.h.
Referenced by Mantid::Geometry::CSGObject::triangulatedSolidAngle().
observer()
const Kernel::V3D & Mantid::Geometry::SolidAngleParams::observer () const inline
Definition at line 20 of file SolidAngleParams.h.
Referenced by Mantid::Geometry::ObjComponent::solidAngle(), Mantid::Geometry::ComponentInfo::solidAngle(), Mantid::Geometry::CSGObject::solidAngle(), Mantid::Geometry::MeshObject::solidAngle(), Mantid::Geometry::MeshObject2D::solidAngle(), Mantid::Geometry::CSGObject::triangulatedSolidAngle(), and Mantid::Geometry::CSGObject::triangulatedSolidAngle().
Member Data Documentation
m_numberOfCylinderSlices
int Mantid::Geometry::SolidAngleParams::m_numberOfCylinderSlices private
Definition at line 28 of file SolidAngleParams.h.
m_observer
Kernel::V3D Mantid::Geometry::SolidAngleParams::m_observer private
Definition at line 27 of file SolidAngleParams.h.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Instrument/SolidAngleParams.h