Mantid: Mantid::DataObjects::EventSortingTask Class Reference
Mantid::DataObjects::EventSortingTask Class Reference
Task for sorting an event list.
Public Member Functions
EventSortingTask (const EventWorkspace *WS, EventSortType sortType, Mantid::API::Progress *prog)
ctor
void operator() (const tbb::blocked_range< size_t > &range) const
Private Attributes
EventSortType m_sortType
How to sort.
const EventWorkspace * m_WS
EventWorkspace on which to sort.
Mantid::API::Progress * prog
Optional Progress dialog.
Detailed Description
Task for sorting an event list.
Definition at line 629 of file EventWorkspace.cpp.
Constructor & Destructor Documentation
EventSortingTask()
Mantid::DataObjects::EventSortingTask::EventSortingTask (const EventWorkspace * WS, EventSortType sortType, Mantid::API::Progress * prog) inline
ctor
Definition at line 632 of file EventWorkspace.cpp.
Member Function Documentation
operator()()
void Mantid::DataObjects::EventSortingTask::operator() (const tbb::blocked_range< size_t > & range) const inline
Definition at line 636 of file EventWorkspace.cpp.
References Mantid::DataObjects::EventWorkspace::getSpectrum(), m_sortType, m_WS, prog, Mantid::Kernel::ProgressBase::report(), and Mantid::DataObjects::EventList::sort().
Member Data Documentation
m_sortType
EventSortType Mantid::DataObjects::EventSortingTask::m_sortType private
How to sort.
Definition at line 647 of file EventWorkspace.cpp.
Referenced by operator()().
m_WS
const EventWorkspace* Mantid::DataObjects::EventSortingTask::m_WS private
EventWorkspace on which to sort.
Definition at line 649 of file EventWorkspace.cpp.
Referenced by operator()().
prog
Mantid::API::Progress* Mantid::DataObjects::EventSortingTask::prog private
Optional Progress dialog.
Definition at line 651 of file EventWorkspace.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
Framework/DataObjects/src/EventWorkspace.cpp