Mantid: MantidQt::MantidWidgets::PropertyHandler Class Reference
MantidQt::MantidWidgets::PropertyHandler Class Reference
Helps display and edit functions in FitPropertyBrowser.
#include <PropertyHandler.h>
Public Member Functions
void addConstraint (QtProperty *parProp, bool lo, bool up, double loBound, double upBound)
Add constraint to parameter property parProp.
PropertyHandler * addFunction (const std::string &fnName)
Add a function to the function handled by this handler.
void addTie (const QString &tieStr)
double base () const
void calcBase ()
Calculate m_base: the baseline level under the peak (if this function is a peak and auto background is on)
void calcBaseAll ()
If the handled function is composite calculate the peak baselines for all members.
double centre () const
std::shared_ptr< Mantid::API::CompositeFunction > cfun () const
std::shared_ptr< Mantid::API::IFunction > changeType (QtProperty *prop)
Change the type of the function (replace the function)
void clearErrors ()
Clear all parameter error values in the manager.
double EstimateFwhm () const
Estimate the FwHM for a peak.
std::shared_ptr< const Mantid::API::CompositeFunction > findCompositeFunction (QtBrowserItem *item) const
Returns 'this' if item == m_item and this is a composite function or calls findCompositeFunction recursively with all its children or zero.
std::shared_ptr< const Mantid::API::IFunction > findFunction (QtBrowserItem *item) const
Returns 'this' if item == m_item or calls findFunction recursively with all its children or zero.
PropertyHandler * findHandler (const Mantid::API::IFunction *fun)
PropertyHandler * findHandler (const Mantid::API::IFunction_const_sptr &fun)
PropertyHandler * findHandler (QtProperty *prop)
void fit ()
void fix (const QString &parName)
QString functionName () const
Creates name for this function to be displayed in the browser.
QString functionPrefix () const
double fwhm () const
std::string getCentreParameterName () const
PropertyHandler * getHandler (std::size_t i) const
QtProperty * getParameterProperty (const QString &parName) const
QtProperty * getParameterProperty (QtProperty *prop) const
QList< PropertyHandler * > getPeakList ()
Make a list of all peaks in this function.
QMap< QString, QtProperty * > getTies ()
std::string getWidthParameterName () const
bool hasPlot () const
bool hasTies ()
double height () const
std::shared_ptr< Mantid::API::IFunction > ifun () const
void init () override
overrides virtual init() which is called from IFunction::setHandler(...)
bool isParameter (QtProperty *prop)
bool isParameterExplicitlySet (const std::string &param) const
QtBrowserItem * item () const
PropertyHandler * parentHandler () const
std::shared_ptr< Mantid::API::IPeakFunction > pfun () const
PropertyHandler (const Mantid::API::IFunction_sptr &fun, std::shared_ptr< Mantid::API::CompositeFunction > parent, FitPropertyBrowser *browser, QtBrowserItem *item=nullptr)
void removeAllPlots ()
Remove all plots including children's.
void removeConstraint (QtProperty *parProp)
void removeFunction ()
void removeTie (const QString &propName)
Remove the tie.
void removeTie (QtProperty *prop)
Remove the tie.
void removeTie (QtProperty *prop, const std::string &globalName)
Remove the tie.
void renameChildren () const
void setAttribute (const QString &attName, const QString &attValue)
Set function's attribute of any type.
template<typename AttributeType >
void setAttribute (QString const &attName, AttributeType const &attValue)
Set function's attribute if it has type double or int.
void setAttribute (QString const &attName, Mantid::API::IFunction::Attribute const &attValue)
Set function attribute value.
bool setAttribute (QtProperty *prop, bool resetProperties=true)
Set function attribute value read from a QtProperty.
void setBase (const double &b)
void setCentre (const double &c)
Set the centre of the handled peak function.
void setFunctionWorkspace ()
void setFwhm (const double &w)
void setHasPlot (const bool state)
void setHeight (const double &h)
Set the height of the handled peak function.
bool setParameter (QtProperty *prop)
Set function parameter value read from a QtProperty.
void setVectorAttribute (QtProperty *prop)
Set function vector attribute value.
void updateAttributes ()
Sync all parameter values with the manager.
void updateErrors ()
Set all parameter error values in the manager.
void updateParameters ()
Sync all parameter values with the manager.
QString updateStructureTooltip ()
Update high-level structure tooltip and return it.
void updateWorkspaces (QStringList oldWorkspaces)
~PropertyHandler () override
Destructor.
Public Member Functions inherited from Mantid::API::FunctionHandler
IFunction_sptr function () const
Return the handled function.
FunctionHandler (const FunctionHandler &)=delete
Delete copy constructor and copy assignment operator.
FunctionHandler (IFunction_sptr fun)
Constructor.
virtual void init ()=0
abstract init method. It is called after setting handler to the function
FunctionHandler & operator= (const FunctionHandler &)=delete
virtual ~FunctionHandler ()=default
Virtual destructor.
Protected Slots
void plotRemoved ()
Remove the reference to the function curve as it has been deleted.
Protected Member Functions
void initAttributes ()
Create and attach QtProperties for function attributes.
void initParameters ()
void initTies ()
Populate ties on parameter properties of child functions.
void initWorkspace ()
Private Member Functions
void applyToAllAttributes (void(PropertyHandler::*func)(QtProperty *))
Applies given function to all the attribute properties recursively.
void applyToAllParameters (void(PropertyHandler::*func)(QtProperty *))
Applies given function to all the parameter properties recursively.
void clearError (QtProperty *prop)
Clear function parameter error in the manager.
void updateAttribute (QtProperty *prop)
Sync function attribute value with the manager.
void updateError (QtProperty *prop)
Set function parameter error in the manager.
void updateParameter (QtProperty *prop)
Sync function parameter value with the manager.
Private Attributes
QList< QtProperty * > m_attributes
double m_base
FitPropertyBrowser * m_browser
std::shared_ptr< Mantid::API::CompositeFunction > m_cf
int m_ci
QMap< QString, std::pair< QtProperty *, QtProperty * > > m_constraints
bool m_hasPlot
bool m_isMultispectral
true if fitting to multiple spectra using MultiBG
QtBrowserItem * m_item
QList< QtProperty * > m_parameters
std::shared_ptr< Mantid::API::CompositeFunction > m_parent
std::shared_ptr< Mantid::API::IPeakFunction > m_pf
QMap< QString, QtProperty * > m_ties
QtProperty * m_type
QList< QtProperty * > m_vectorMembers
QList< QtProperty * > m_vectorSizes
QtProperty * m_workspace
function
QtProperty * m_workspaceIndex
workspace index for multispectral fitting
Friends
class CreateAttributeProperty
Additional Inherited Members
Protected Attributes inherited from Mantid::API::FunctionHandler
IFunction_sptr m_fun
pointer to the handled function
Detailed Description
Helps display and edit functions in FitPropertyBrowser.
Definition at line 39 of file PropertyHandler.h.
Constructor & Destructor Documentation
PropertyHandler()
MantidQt::MantidWidgets::PropertyHandler::PropertyHandler (const Mantid::API::IFunction_sptr & fun, std::shared_ptr< Mantid::API::CompositeFunction > parent, FitPropertyBrowser * browser, QtBrowserItem * item = nullptr)
Definition at line 45 of file PropertyHandler.cpp.
~PropertyHandler()
MantidQt::MantidWidgets::PropertyHandler::~PropertyHandler () override default
Destructor.
Member Function Documentation
addConstraint()
void MantidQt::MantidWidgets::PropertyHandler::addConstraint (QtProperty * parProp, bool lo, bool up, double loBound, double upBound)
Add constraint to parameter property parProp.
Definition at line 1394 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, m_constraints, MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager, and Mantid::API::FunctionHandler::m_fun.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addConstraint(), MantidQt::MantidWidgets::FitPropertyBrowser::doubleChanged(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged().
addFunction()
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::addFunction (const std::string & fnName)
Add a function to the function handled by this handler.
Parameters
fnName :: A function name or full initialization string in the form name=FunctionName,param1=Value,param2=Value,...
Definition at line 353 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::disableUndo(), MantidQt::MantidWidgets::FitPropertyBrowser::endX(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_browser, m_cf, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, MantidQt::MantidWidgets::FitPropertyBrowser::reset(), setAttribute(), MantidQt::MantidWidgets::FitPropertyBrowser::setCurrentFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultBackgroundType(), MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultPeakType(), MantidQt::MantidWidgets::FitPropertyBrowser::setFitEnabled(), MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspace(), MantidQt::MantidWidgets::FitPropertyBrowser::startX(), MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName(), Mantid::Geometry::X, Mantid::Geometry::x, and Mantid::Geometry::Y.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::acceptFit(), MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), and MantidQt::MantidWidgets::FitPropertyBrowser::addFunction().
addTie()
void MantidQt::MantidWidgets::PropertyHandler::addTie (const QString & tieStr)
Definition at line 1102 of file PropertyHandler.cpp.
References cfun(), MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, m_parameters, MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager, and m_ties.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), and MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged().
applyToAllAttributes()
void MantidQt::MantidWidgets::PropertyHandler::applyToAllAttributes (void(PropertyHandler::*)(QtProperty *) func) private
Applies given function to all the attribute properties recursively.
Applies the given function to all the attribute properties recursively, within this context.
Parameters
func :: Function to apply
Definition at line 925 of file PropertyHandler.cpp.
References applyToAllAttributes(), getHandler(), m_attributes, and m_cf.
Referenced by applyToAllAttributes(), and updateAttributes().
applyToAllParameters()
void MantidQt::MantidWidgets::PropertyHandler::applyToAllParameters (void(PropertyHandler::*)(QtProperty *) func) private
Applies given function to all the parameter properties recursively.
Applies given function to all the parameter properties recursively, within this context.
Parameters
func :: Function to apply
Definition at line 956 of file PropertyHandler.cpp.
References applyToAllParameters(), getHandler(), m_cf, and m_parameters.
Referenced by applyToAllParameters(), clearErrors(), updateErrors(), and updateParameters().
base()
double MantidQt::MantidWidgets::PropertyHandler::base () const inline
Definition at line 176 of file PropertyHandler.h.
calcBase()
void MantidQt::MantidWidgets::PropertyHandler::calcBase ()
Calculate m_base: the baseline level under the peak (if this function is a peak and auto background is on)
Definition at line 1255 of file PropertyHandler.cpp.
References Mantid::API::FunctionHandler::function(), MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspace(), MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground, m_base, m_browser, m_ci, n, MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), Mantid::Geometry::X, Mantid::Geometry::x, Mantid::Geometry::Y, and Mantid::Geometry::y.
Referenced by calcBaseAll().
calcBaseAll()
void MantidQt::MantidWidgets::PropertyHandler::calcBaseAll ()
If the handled function is composite calculate the peak baselines for all members.
If auto background is off does nothing.
Definition at line 1283 of file PropertyHandler.cpp.
References calcBase(), calcBaseAll(), cfun(), getHandler(), MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground, m_browser, m_cf, and pfun().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), calcBaseAll(), and fit().
centre()
double MantidQt::MantidWidgets::PropertyHandler::centre () const
Definition at line 1356 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::endX(), m_browser, m_pf, and MantidQt::MantidWidgets::FitPropertyBrowser::startX().
cfun()
std::shared_ptr< Mantid::API::CompositeFunction > MantidQt::MantidWidgets::PropertyHandler::cfun () const inline
Definition at line 66 of file PropertyHandler.h.
Referenced by addTie(), calcBaseAll(), functionPrefix(), getPeakList(), removeFunction(), setAttribute(), and updateWorkspaces().
changeType()
Mantid::API::IFunction_sptr MantidQt::MantidWidgets::PropertyHandler::changeType (QtProperty * prop)
Change the type of the function (replace the function)
Parameters
prop :: The "Type" property with new value
Definition at line 1000 of file PropertyHandler.cpp.
References changeType(), MantidQt::MantidWidgets::FitPropertyBrowser::endX(), fit(), Mantid::API::FunctionHandler::function(), getHandler(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground, m_browser, m_cf, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_item, m_parent, m_pf, m_type, MantidQt::MantidWidgets::FitPropertyBrowser::removePlotSignal(), Mantid::API::IFunctionWithLocation::setCentre(), MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultBackgroundType(), MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultPeakType(), Mantid::API::IPeakFunction::setFwhm(), Mantid::API::IFunctionWithLocation::setHeight(), MantidQt::MantidWidgets::FitPropertyBrowser::startX(), MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), and MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName().
Referenced by changeType(), and MantidQt::MantidWidgets::FitPropertyBrowser::enumChanged().
clearError()
void MantidQt::MantidWidgets::PropertyHandler::clearError (QtProperty * prop) private
Clear function parameter error in the manager.
Parameters
prop :: Property of the parameter
Definition at line 994 of file PropertyHandler.cpp.
References m_browser, and MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager.
Referenced by clearErrors().
clearErrors()
void MantidQt::MantidWidgets::PropertyHandler::clearErrors ()
Clear all parameter error values in the manager.
Definition at line 972 of file PropertyHandler.cpp.
References applyToAllParameters(), and clearError().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::undoFit().
EstimateFwhm()
double MantidQt::MantidWidgets::PropertyHandler::EstimateFwhm () const
Estimate the FwHM for a peak.
Create a simple estimate of the full width half maximum.
Returns
and estimate of the peak width, or 0 if an error occurs
Definition at line 1211 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::endX(), fabs, fwhm(), MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspace(), m_base, m_browser, m_ci, n, MantidQt::MantidWidgets::FitPropertyBrowser::startX(), MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), Mantid::Geometry::X, and Mantid::Geometry::Y.
findCompositeFunction()
Mantid::API::CompositeFunction_const_sptr MantidQt::MantidWidgets::PropertyHandler::findCompositeFunction (QtBrowserItem * item) const
Returns 'this' if item == m_item and this is a composite function or calls findCompositeFunction recursively with all its children or zero.
Definition at line 545 of file PropertyHandler.cpp.
References findCompositeFunction(), getHandler(), item(), m_cf, and m_item.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::acceptFit(), MantidQt::MantidWidgets::FitPropertyBrowser::addFunction(), findCompositeFunction(), and MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu().
findFunction()
Mantid::API::IFunction_const_sptr MantidQt::MantidWidgets::PropertyHandler::findFunction (QtBrowserItem * item) const
Returns 'this' if item == m_item or calls findFunction recursively with all its children or zero.
Definition at line 561 of file PropertyHandler.cpp.
References findFunction(), Mantid::API::FunctionHandler::function(), getHandler(), item(), m_cf, and m_item.
Referenced by findFunction(), and MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu().
findHandler() [1/3]
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::findHandler (const Mantid::API::IFunction * fun)
Definition at line 624 of file PropertyHandler.cpp.
References findHandler(), Mantid::API::FunctionHandler::function(), getHandler(), and m_cf.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::acceptFit(), MantidQt::MantidWidgets::FitPropertyBrowser::addConstraint(), MantidQt::MantidWidgets::FitPropertyBrowser::addFixTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::boolChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::currentItemChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::deleteFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie(), MantidQt::MantidWidgets::FitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::enumChanged(), findHandler(), initTies(), MantidQt::MantidWidgets::FitPropertyBrowser::intChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu(), MantidQt::MantidWidgets::FitPropertyBrowser::removeBounds(), MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::vectorDoubleChanged(), and MantidQt::MantidWidgets::FitPropertyBrowser::vectorSizeChanged().
findHandler() [2/3]
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::findHandler (const Mantid::API::IFunction_const_sptr & fun)
Definition at line 611 of file PropertyHandler.cpp.
References findHandler(), Mantid::API::FunctionHandler::function(), getHandler(), and m_cf.
findHandler() [3/3]
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::findHandler (QtProperty * prop)
Definition at line 574 of file PropertyHandler.cpp.
References findHandler(), getHandler(), m_attributes, m_cf, m_constraints, m_item, m_parameters, m_ties, m_type, m_vectorMembers, m_vectorSizes, m_workspace, and m_workspaceIndex.
fit()
void MantidQt::MantidWidgets::PropertyHandler::fit ()
Definition at line 1555 of file PropertyHandler.cpp.
References calcBaseAll(), MantidQt::MantidWidgets::FitPropertyBrowser::endX(), MantidQt::MantidWidgets::FitPropertyBrowser::getHandler(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_browser, Mantid::API::FunctionHandler::m_fun, MantidQt::MantidWidgets::FitPropertyBrowser::startX(), updateParameters(), MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), and MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), changeType(), MantidQt::MantidWidgets::FitPropertyBrowser::refitAutoBackground(), and setAttribute().
fix()
void MantidQt::MantidWidgets::PropertyHandler::fix (const QString & parName)
Definition at line 1132 of file PropertyHandler.cpp.
References getParameterProperty(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, Mantid::API::FunctionHandler::m_fun, MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager, and m_ties.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addFixTie().
functionName()
QString MantidQt::MantidWidgets::PropertyHandler::functionName () const
Creates name for this function to be displayed in the browser.
Definition at line 499 of file PropertyHandler.cpp.
References Mantid::API::FunctionHandler::function(), and functionPrefix().
Referenced by init(), and renameChildren().
functionPrefix()
QString MantidQt::MantidWidgets::PropertyHandler::functionPrefix () const
Definition at line 508 of file PropertyHandler.cpp.
References cfun(), Mantid::API::FunctionHandler::function(), functionPrefix(), and parentHandler().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addTie(), functionName(), functionPrefix(), setParameter(), and MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged().
fwhm()
double MantidQt::MantidWidgets::PropertyHandler::fwhm () const
Definition at line 1363 of file PropertyHandler.cpp.
References m_pf.
Referenced by EstimateFwhm().
getCentreParameterName()
std::string MantidQt::MantidWidgets::PropertyHandler::getCentreParameterName () const
Definition at line 1377 of file PropertyHandler.cpp.
References m_pf.
getHandler()
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::getHandler (std::size_t i) const
Definition at line 535 of file PropertyHandler.cpp.
References m_cf.
Referenced by applyToAllAttributes(), applyToAllParameters(), calcBaseAll(), changeType(), findCompositeFunction(), findFunction(), findHandler(), getPeakList(), removeAllPlots(), renameChildren(), setAttribute(), setParameter(), updateStructureTooltip(), and updateWorkspaces().
getParameterProperty() [1/2]
QtProperty * MantidQt::MantidWidgets::PropertyHandler::getParameterProperty (const QString & parName) const
Definition at line 1083 of file PropertyHandler.cpp.
References m_parameters.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), fix(), removeTie(), and MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged().
getParameterProperty() [2/2]
QtProperty * MantidQt::MantidWidgets::PropertyHandler::getParameterProperty (QtProperty * prop) const
Definition at line 1092 of file PropertyHandler.cpp.
References m_parameters.
getPeakList()
QList< PropertyHandler * > MantidQt::MantidWidgets::PropertyHandler::getPeakList ()
Make a list of all peaks in this function.
Definition at line 1472 of file PropertyHandler.cpp.
References cfun(), getHandler(), getPeakList(), m_cf, m_pf, and pfun().
Referenced by getPeakList().
getTies()
QMap< QString, QtProperty * > MantidQt::MantidWidgets::PropertyHandler::getTies () inline
Definition at line 207 of file PropertyHandler.h.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie().
getWidthParameterName()
std::string MantidQt::MantidWidgets::PropertyHandler::getWidthParameterName () const
Definition at line 1370 of file PropertyHandler.cpp.
References m_pf.
hasPlot()
bool MantidQt::MantidWidgets::PropertyHandler::hasPlot () const inline
Definition at line 193 of file PropertyHandler.h.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), and MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu().
hasTies()
bool MantidQt::MantidWidgets::PropertyHandler::hasTies () inline
Definition at line 208 of file PropertyHandler.h.
height()
double MantidQt::MantidWidgets::PropertyHandler::height () const
Definition at line 1349 of file PropertyHandler.cpp.
References m_pf.
ifun()
std::shared_ptr< Mantid::API::IFunction > MantidQt::MantidWidgets::PropertyHandler::ifun () const inline
Definition at line 70 of file PropertyHandler.h.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::functionHelp(), and setFunctionWorkspace().
init()
void MantidQt::MantidWidgets::PropertyHandler::init () override virtual
overrides virtual init() which is called from IFunction::setHandler(...)
Implements Mantid::API::FunctionHandler.
Definition at line 56 of file PropertyHandler.cpp.
References functionName(), initAttributes(), initParameters(), initTies(), initWorkspace(), item(), MantidQt::MantidWidgets::FitPropertyBrowser::m_browser, m_browser, m_cf, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, Mantid::API::FunctionHandler::m_fun, MantidQt::MantidWidgets::FitPropertyBrowser::m_functionsGroup, MantidQt::MantidWidgets::FitPropertyBrowser::m_groupManager, m_item, m_parent, MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredFunctions, m_type, and parentHandler().
initAttributes()
void MantidQt::MantidWidgets::PropertyHandler::initAttributes () protected
Create and attach QtProperties for function attributes.
Definition at line 224 of file PropertyHandler.cpp.
References Mantid::API::IFunction::Attribute::apply(), Mantid::API::FunctionHandler::function(), Mantid::API::IFunction::Attribute::getValidator(), m_attributes, m_browser, m_item, m_vectorMembers, and tmp.
Referenced by init(), and setAttribute().
initParameters()
void MantidQt::MantidWidgets::PropertyHandler::initParameters () protected
Definition at line 243 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty(), Mantid::API::IConstraint::asString(), Mantid::API::FunctionHandler::function(), m_browser, m_constraints, MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager, Mantid::API::FunctionHandler::m_fun, m_item, MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager, m_parameters, MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager, and m_ties.
Referenced by init(), and setAttribute().
initTies()
void MantidQt::MantidWidgets::PropertyHandler::initTies () protected
Populate ties on parameter properties of child functions.
Definition at line 207 of file PropertyHandler.cpp.
References Mantid::API::ParameterTie::asString(), findHandler(), and m_cf.
Referenced by init().
initWorkspace()
void MantidQt::MantidWidgets::PropertyHandler::initWorkspace () protected
Definition at line 304 of file PropertyHandler.cpp.
References m_parent, m_workspace, and m_workspaceIndex.
Referenced by init().
isParameter()
bool MantidQt::MantidWidgets::PropertyHandler::isParameter (QtProperty * prop)
Definition at line 1081 of file PropertyHandler.cpp.
References m_parameters.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addFixTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTie(), MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), and MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu().
isParameterExplicitlySet()
bool MantidQt::MantidWidgets::PropertyHandler::isParameterExplicitlySet (const std::string & param) const
Definition at line 1384 of file PropertyHandler.cpp.
References m_pf.
item()
QtBrowserItem * MantidQt::MantidWidgets::PropertyHandler::item () const inline
Definition at line 72 of file PropertyHandler.h.
Referenced by findCompositeFunction(), findFunction(), init(), removeFunction(), renameChildren(), and MantidQt::MantidWidgets::FitPropertyBrowser::setCurrentFunction().
parentHandler()
PropertyHandler * MantidQt::MantidWidgets::PropertyHandler::parentHandler () const
Definition at line 528 of file PropertyHandler.cpp.
References m_parent.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::enumChanged(), functionPrefix(), init(), and removeFunction().
pfun()
std::shared_ptr< Mantid::API::IPeakFunction > MantidQt::MantidWidgets::PropertyHandler::pfun () const inline
Definition at line 68 of file PropertyHandler.h.
Referenced by calcBaseAll(), MantidQt::MantidWidgets::FitPropertyBrowser::centre(), MantidQt::MantidWidgets::FitPropertyBrowser::fwhm(), getPeakList(), MantidQt::MantidWidgets::FitPropertyBrowser::height(), and MantidQt::MantidWidgets::FitPropertyBrowser::isPeak().
plotRemoved
void MantidQt::MantidWidgets::PropertyHandler::plotRemoved () protected slot
Remove the reference to the function curve as it has been deleted.
Definition at line 1495 of file PropertyHandler.cpp.
References m_hasPlot.
removeAllPlots()
void MantidQt::MantidWidgets::PropertyHandler::removeAllPlots ()
Remove all plots including children's.
Definition at line 1546 of file PropertyHandler.cpp.
References getHandler(), m_browser, m_cf, removeAllPlots(), and MantidQt::MantidWidgets::FitPropertyBrowser::removePlotSignal().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::clear(), MantidQt::MantidWidgets::FitPropertyBrowser::loadFunction(), and removeAllPlots().
removeConstraint()
void MantidQt::MantidWidgets::PropertyHandler::removeConstraint (QtProperty * parProp)
Definition at line 1454 of file PropertyHandler.cpp.
References m_constraints, and Mantid::API::FunctionHandler::m_fun.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::removeBounds().
removeFunction()
void MantidQt::MantidWidgets::PropertyHandler::removeFunction ()
Definition at line 449 of file PropertyHandler.cpp.
References cfun(), Mantid::API::FunctionHandler::function(), item(), MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground, m_browser, m_item, parentHandler(), MantidQt::MantidWidgets::FitPropertyBrowser::removePlotSignal(), renameChildren(), and MantidQt::MantidWidgets::FitPropertyBrowser::setFitEnabled().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), and MantidQt::MantidWidgets::FitPropertyBrowser::removeFunction().
removeTie() [1/3]
void MantidQt::MantidWidgets::PropertyHandler::removeTie (const QString & parName)
Remove the tie.
Parameters
parName :: The name of the parameter
Definition at line 1201 of file PropertyHandler.cpp.
References m_ties, and removeTie().
removeTie() [2/3]
void MantidQt::MantidWidgets::PropertyHandler::removeTie (QtProperty * prop)
Remove the tie.
Parameters
prop :: The tie property to remove
Definition at line 1181 of file PropertyHandler.cpp.
References getParameterProperty(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, Mantid::API::FunctionHandler::m_fun, and m_ties.
removeTie() [3/3]
void MantidQt::MantidWidgets::PropertyHandler::removeTie (QtProperty * prop, const std::string & globalName)
Remove the tie.
Parameters
prop :: The tie property to remove
globalName :: Name of the parameter in compoite function (e.g. f1.omega)
Definition at line 1159 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), getParameterProperty(), index, m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, and m_ties.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie(), and removeTie().
renameChildren()
void MantidQt::MantidWidgets::PropertyHandler::renameChildren () const
Definition at line 469 of file PropertyHandler.cpp.
References Mantid::API::ParameterTie::asString(), functionName(), getHandler(), item(), m_browser, m_cf, MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled, Mantid::API::FunctionHandler::m_fun, MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager, m_ties, and renameChildren().
Referenced by removeFunction(), and renameChildren().
setAttribute() [1/4]
void MantidQt::MantidWidgets::PropertyHandler::setAttribute (const QString & attName, const QString & attValue)
Set function's attribute of any type.
Sets the function attribute value if it has type QString.
Parameters
attName :: The name of the attribute
attValue :: The new attribute value as a string. If the attValue's format doesn't match the attribute's type it is ignored.
attName :: The name of the attribute
attValue :: The value of the attribute
Definition at line 885 of file PropertyHandler.cpp.
References Mantid::API::IFunction::Attribute::apply(), MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), Mantid::API::IFunction::Attribute::fromString(), initAttributes(), initParameters(), m_attributes, m_browser, Mantid::API::FunctionHandler::m_fun, and tmp.
setAttribute() [2/4]
template<typename AttributeType > void MantidQt::MantidWidgets::PropertyHandler::setAttribute (QString const & attName, AttributeType const & attValue)
Set function's attribute if it has type double or int.
Sets the function attribute value if it has type double or int.
Parameters
attName :: The name of the attribute
attValue :: The new attribute value
attName :: The name of the attribute
attValue :: The value of the attribute
Definition at line 856 of file PropertyHandler.cpp.
References cfun(), MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), getHandler(), initAttributes(), initParameters(), m_attributes, m_browser, Mantid::API::FunctionHandler::m_fun, and setAttribute().
setAttribute() [3/4]
void MantidQt::MantidWidgets::PropertyHandler::setAttribute (QString const & attName, Mantid::API::IFunction::Attribute const & attValue)
Set function attribute value.
Parameters
attName :: The name of the attribute
attValue :: The new attribute value
attName :: The name of the attribute
attValue :: The value of the attribute
Definition at line 840 of file PropertyHandler.cpp.
References Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asInt(), Mantid::API::IFunction::Attribute::asString(), setAttribute(), and Mantid::API::IFunction::Attribute::type().
setAttribute() [4/4]
bool MantidQt::MantidWidgets::PropertyHandler::setAttribute (QtProperty * prop, bool resetProperties = true)
Set function attribute value read from a QtProperty.
Parameters
prop :: The property with the new attribute value
resetProperties :: Flag to reset all properties of the handled function.
Returns
true if successfull
Definition at line 795 of file PropertyHandler.cpp.
References Mantid::API::IFunction::Attribute::apply(), MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction(), fit(), getHandler(), Mantid::API::IFunction::Attribute::getValidator(), initAttributes(), initParameters(), m_attributes, MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground, m_browser, m_cf, Mantid::API::FunctionHandler::m_fun, setAttribute(), and tmp.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground(), addFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::FitPropertyBrowser::enactAttributeChange(), MantidQt::MantidWidgets::FitPropertyBrowser::intChanged(), setAttribute(), setVectorAttribute(), MantidQt::MantidWidgets::FitPropertyBrowser::setXRange(), and updateAttribute().
setBase()
void MantidQt::MantidWidgets::PropertyHandler::setBase (const double & b) inline
Definition at line 164 of file PropertyHandler.h.
setCentre()
void MantidQt::MantidWidgets::PropertyHandler::setCentre (const double & c)
Set the centre of the handled peak function.
Find m_ci: x-index of the peakcentre.
Definition at line 1311 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspace(), m_browser, m_ci, m_pf, n, MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex(), Mantid::Geometry::X, and Mantid::Geometry::x.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::setCentre().
setFunctionWorkspace()
void MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace ()
Definition at line 1601 of file PropertyHandler.cpp.
References MantidQt::MantidWidgets::FitPropertyBrowser::endX(), ifun(), index, Mantid::Kernel::SingletonHolder< T >::Instance(), m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, MantidQt::MantidWidgets::FitPropertyBrowser::m_intManager, m_item, m_workspace, m_workspaceIndex, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames, and MantidQt::MantidWidgets::FitPropertyBrowser::startX().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::intChanged().
setFwhm()
void MantidQt::MantidWidgets::PropertyHandler::setFwhm (const double & w)
Definition at line 1343 of file PropertyHandler.cpp.
References m_pf.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::setFwhm().
setHasPlot()
void MantidQt::MantidWidgets::PropertyHandler::setHasPlot (const bool state) inline
Definition at line 194 of file PropertyHandler.h.
setHeight()
void MantidQt::MantidWidgets::PropertyHandler::setHeight (const double & h)
Set the height of the handled peak function.
Definition at line 1301 of file PropertyHandler.cpp.
References m_base, and m_pf.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::setHeight().
setParameter()
bool MantidQt::MantidWidgets::PropertyHandler::setParameter (QtProperty * prop)
Set function parameter value read from a QtProperty.
Parameters
prop :: The (double) property with the new parameter value
Returns
true if successfull
Definition at line 642 of file PropertyHandler.cpp.
References functionPrefix(), getHandler(), m_browser, m_cf, Mantid::API::FunctionHandler::m_fun, MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager, m_parameters, MantidQt::MantidWidgets::FitPropertyBrowser::sendParameterChanged(), and setParameter().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::parameterChanged(), and setParameter().
setVectorAttribute()
void MantidQt::MantidWidgets::PropertyHandler::setVectorAttribute (QtProperty * prop)
Set function vector attribute value.
Parameters
prop :: A property for a member of a vector attribute.
Definition at line 909 of file PropertyHandler.cpp.
References m_attributes, m_vectorSizes, and setAttribute().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::enactAttributeChange().
updateAttribute()
void MantidQt::MantidWidgets::PropertyHandler::updateAttribute (QtProperty * attribute) private
Sync function attribute value with the manager.
Parameters
attribute :: An attribute of the function
Definition at line 944 of file PropertyHandler.cpp.
References Mantid::API::FunctionHandler::function(), m_attributes, and setAttribute().
Referenced by updateAttributes().
updateAttributes()
void MantidQt::MantidWidgets::PropertyHandler::updateAttributes ()
Sync all parameter values with the manager.
Updates all string, double and int attributes which have changed in a function.
Definition at line 939 of file PropertyHandler.cpp.
References applyToAllAttributes(), and updateAttribute().
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::updateAttributes().
updateError()
void MantidQt::MantidWidgets::PropertyHandler::updateError (QtProperty * prop) private
Set function parameter error in the manager.
Parameters
prop :: Property of the parameter
Definition at line 985 of file PropertyHandler.cpp.
References error, Mantid::API::FunctionHandler::function(), index, m_browser, and MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager.
Referenced by updateErrors().
updateErrors()
void MantidQt::MantidWidgets::PropertyHandler::updateErrors ()
Set all parameter error values in the manager.
Definition at line 970 of file PropertyHandler.cpp.
References applyToAllParameters(), and updateError().
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), and MantidQt::MantidWidgets::FitPropertyBrowser::updateBrowserFromFitResults().
updateParameter()
void MantidQt::MantidWidgets::PropertyHandler::updateParameter (QtProperty * prop) private
Sync function parameter value with the manager.
Parameters
prop :: Property of the parameter
Definition at line 977 of file PropertyHandler.cpp.
References Mantid::API::FunctionHandler::function(), m_browser, and MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager.
Referenced by updateParameters().
updateParameters()
void MantidQt::MantidWidgets::PropertyHandler::updateParameters ()
Sync all parameter values with the manager.
Definition at line 968 of file PropertyHandler.cpp.
References applyToAllParameters(), and updateParameter().
Referenced by fit(), MantidQt::MantidWidgets::FitPropertyBrowser::setCentre(), MantidQt::MantidWidgets::FitPropertyBrowser::setFwhm(), MantidQt::MantidWidgets::FitPropertyBrowser::setHeight(), and MantidQt::MantidWidgets::FitPropertyBrowser::updateParameters().
updateStructureTooltip()
QString MantidQt::MantidWidgets::PropertyHandler::updateStructureTooltip ()
Update high-level structure tooltip and return it.
Updates the high-level structure tooltip of this handler's property, updating those of sub-properties recursively first.
For non-empty composite functions: something like ((Gaussian * Lorentzian)
FlatBackground)
For non-composite functions: function()->name().
Returns
The new tooltip
Definition at line 1508 of file PropertyHandler.cpp.
References Mantid::API::FunctionHandler::function(), getHandler(), m_cf, and m_item.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::updateStructureTooltips().
updateWorkspaces()
void MantidQt::MantidWidgets::PropertyHandler::updateWorkspaces (QStringList oldWorkspaces)
Definition at line 1580 of file PropertyHandler.cpp.
References cfun(), getHandler(), index, m_browser, MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager, m_workspace, MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames, and updateWorkspaces().
Referenced by updateWorkspaces().
Friends And Related Function Documentation
CreateAttributeProperty
friend class CreateAttributeProperty friend
Definition at line 261 of file PropertyHandler.h.
Member Data Documentation
m_attributes
QList<QtProperty *> MantidQt::MantidWidgets::PropertyHandler::m_attributes private
Definition at line 228 of file PropertyHandler.h.
Referenced by applyToAllAttributes(), findHandler(), initAttributes(), setAttribute(), setVectorAttribute(), and updateAttribute().
m_base
double MantidQt::MantidWidgets::PropertyHandler::m_base private
Definition at line 238 of file PropertyHandler.h.
Referenced by calcBase(), EstimateFwhm(), and setHeight().
m_browser
FitPropertyBrowser* MantidQt::MantidWidgets::PropertyHandler::m_browser private
Definition at line 222 of file PropertyHandler.h.
Referenced by addConstraint(), addFunction(), addTie(), calcBase(), calcBaseAll(), centre(), changeType(), clearError(), EstimateFwhm(), fit(), fix(), init(), initAttributes(), initParameters(), removeAllPlots(), removeFunction(), removeTie(), renameChildren(), setAttribute(), setCentre(), setFunctionWorkspace(), setParameter(), updateError(), updateParameter(), and updateWorkspaces().
m_cf
std::shared_ptr<Mantid::API::CompositeFunction> MantidQt::MantidWidgets::PropertyHandler::m_cf private
Definition at line 223 of file PropertyHandler.h.
Referenced by addFunction(), applyToAllAttributes(), applyToAllParameters(), calcBaseAll(), changeType(), findCompositeFunction(), findFunction(), findHandler(), getHandler(), getPeakList(), init(), initTies(), removeAllPlots(), renameChildren(), setAttribute(), setParameter(), and updateStructureTooltip().
m_ci
int MantidQt::MantidWidgets::PropertyHandler::m_ci private
Definition at line 239 of file PropertyHandler.h.
Referenced by calcBase(), EstimateFwhm(), and setCentre().
m_constraints
QMap<QString, std::pair<QtProperty *, QtProperty *> > MantidQt::MantidWidgets::PropertyHandler::m_constraints private
Definition at line 231 of file PropertyHandler.h.
Referenced by addConstraint(), findHandler(), initParameters(), and removeConstraint().
m_hasPlot
bool MantidQt::MantidWidgets::PropertyHandler::m_hasPlot mutable private
Definition at line 241 of file PropertyHandler.h.
Referenced by plotRemoved().
m_isMultispectral
bool MantidQt::MantidWidgets::PropertyHandler::m_isMultispectral private
true if fitting to multiple spectra using MultiBG
Definition at line 234 of file PropertyHandler.h.
m_item
QtBrowserItem* MantidQt::MantidWidgets::PropertyHandler::m_item private
Definition at line 227 of file PropertyHandler.h.
Referenced by changeType(), findCompositeFunction(), findFunction(), findHandler(), init(), initAttributes(), initParameters(), removeFunction(), setFunctionWorkspace(), and updateStructureTooltip().
m_parameters
QList<QtProperty *> MantidQt::MantidWidgets::PropertyHandler::m_parameters private
Definition at line 229 of file PropertyHandler.h.
Referenced by addTie(), applyToAllParameters(), findHandler(), getParameterProperty(), initParameters(), isParameter(), and setParameter().
m_parent
std::shared_ptr<Mantid::API::CompositeFunction> MantidQt::MantidWidgets::PropertyHandler::m_parent private
Definition at line 225 of file PropertyHandler.h.
Referenced by changeType(), init(), initWorkspace(), and parentHandler().
m_pf
std::shared_ptr<Mantid::API::IPeakFunction> MantidQt::MantidWidgets::PropertyHandler::m_pf private
Definition at line 224 of file PropertyHandler.h.
Referenced by centre(), changeType(), fwhm(), getCentreParameterName(), getPeakList(), getWidthParameterName(), height(), isParameterExplicitlySet(), setCentre(), setFwhm(), and setHeight().
m_ties
QMap<QString, QtProperty *> MantidQt::MantidWidgets::PropertyHandler::m_ties private
Definition at line 230 of file PropertyHandler.h.
Referenced by addTie(), findHandler(), fix(), initParameters(), removeTie(), and renameChildren().
m_type
QtProperty* MantidQt::MantidWidgets::PropertyHandler::m_type private
Definition at line 226 of file PropertyHandler.h.
Referenced by changeType(), findHandler(), and init().
m_vectorMembers
QList<QtProperty *> MantidQt::MantidWidgets::PropertyHandler::m_vectorMembers private
Definition at line 232 of file PropertyHandler.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), findHandler(), and initAttributes().
m_vectorSizes
QList<QtProperty *> MantidQt::MantidWidgets::PropertyHandler::m_vectorSizes private
Definition at line 233 of file PropertyHandler.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), findHandler(), and setVectorAttribute().
m_workspace
QtProperty* MantidQt::MantidWidgets::PropertyHandler::m_workspace private
function
workspace name for multispectral fitting
Definition at line 236 of file PropertyHandler.h.
Referenced by findHandler(), initWorkspace(), setFunctionWorkspace(), and updateWorkspaces().
m_workspaceIndex
QtProperty* MantidQt::MantidWidgets::PropertyHandler::m_workspaceIndex private
workspace index for multispectral fitting
Definition at line 237 of file PropertyHandler.h.
Referenced by findHandler(), initWorkspace(), and setFunctionWorkspace().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/PropertyHandler.h
qt/widgets/common/src/PropertyHandler.cpp