Mantid: MantidQt::MantidWidgets::IFunctionView Class Reference
MantidQt::MantidWidgets::IFunctionView Class Reference abstract
The interface to a function view.
#include <IFunctionView.h>
Signals
void attributePropertyChanged (std::string const &attrName)
Function attribute gets changed.
void copyToClipboardRequest ()
User requested copy function to clipboard.
void currentFunctionChanged ()
User selects a different (sub)function (or one of it's sub-properties)
void functionAdded (std::string const &funStr)
User adds a function.
void functionHelpRequest ()
User requested function help.
void functionRemoved (std::string const &functionIndex)
User removes a function.
void functionRemovedString (std::string const &funStr)
User removes a function.
void functionReplaced (std::string const &funStr)
User replaces the whole function (eg, by pasting it from clipboard)
void globalsChanged (const std::vector< std::string > &)
User changed the list of global parameters.
void localParameterButtonClicked (std::string const &parameterName)
In multi-dataset context a button value editor was clicked.
void parameterChanged (std::string const &parameterName)
Function parameter gets changed.
void parameterConstraintAdded (std::string const &functionIndex, std::string const &constraint)
User sets a constraint.
void parameterConstraintRemoved (std::string const &parameterName)
User removes a constraint.
void parameterTieChanged (std::string const &parameterName, std::string const &tie)
User sets a tie.
Public Member Functions
virtual void clear ()=0
virtual void clearErrors ()=0
virtual std::optional< std::string > currentFunctionIndex () const =0
virtual IFunction::Attribute getAttribute (std::string const &attrName) const =0
virtual double getParameter (std::string const &parameterName) const =0
virtual IFunction_sptr getSelectedFunction ()=0
virtual bool hasFunction () const =0
IFunctionView (QWidget *parent=nullptr)
template<typename T >
void setAttributeValue (std::string const &attributeName, T &value)
virtual void setErrorsEnabled (bool enabled)=0
virtual void setFunction (IFunction_sptr fun)=0
virtual void setGlobalParameters (const std::vector< std::string > &)=0
virtual void setParameter (std::string const &parameterName, double value)=0
virtual void setParameterConstraint (std::string const &parameterName, std::string const &constraint)=0
virtual void setParameterError (std::string const &parameterName, double error)=0
virtual void setParameterTie (std::string const &parameterName, std::string const &tie)=0
virtual void showFunctionHelp (std::string const &) const =0
virtual ~IFunctionView ()=default
Protected Member Functions
virtual void setBooleanAttribute (std::string const &parameterName, bool value)=0
virtual void setDoubleAttribute (std::string const &parameterName, double value)=0
virtual void setIntAttribute (std::string const &parameterName, int value)=0
virtual void setStringAttribute (std::string const &parameterName, std::string &value)=0
virtual void setVectorAttribute (std::string const &parameterName, std::vector< double > &val)=0
Detailed Description
The interface to a function view.
Definition at line 26 of file IFunctionView.h.
Constructor & Destructor Documentation
IFunctionView()
MantidQt::MantidWidgets::IFunctionView::IFunctionView (QWidget * parent = nullptr) inline
Definition at line 29 of file IFunctionView.h.
~IFunctionView()
virtual MantidQt::MantidWidgets::IFunctionView::~IFunctionView () virtual default
Member Function Documentation
attributePropertyChanged
void MantidQt::MantidWidgets::IFunctionView::attributePropertyChanged (std::string const & attrName) signal
Function attribute gets changed.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::attributeChanged().
clear()
virtual void MantidQt::MantidWidgets::IFunctionView::clear () pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::clear().
clearErrors()
virtual void MantidQt::MantidWidgets::IFunctionView::clearErrors () pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::clearErrors().
copyToClipboardRequest
void MantidQt::MantidWidgets::IFunctionView::copyToClipboardRequest () signal
User requested copy function to clipboard.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::copyToClipboard().
currentFunctionChanged
void MantidQt::MantidWidgets::IFunctionView::currentFunctionChanged () signal
User selects a different (sub)function (or one of it's sub-properties)
Referenced by MantidQt::MantidWidgets::FunctionTreeView::updateCurrentFunctionIndex().
currentFunctionIndex()
virtual std::optional< std::string > MantidQt::MantidWidgets::IFunctionView::currentFunctionIndex () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::currentFunctionIndex(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewAddedFunction().
functionAdded
void MantidQt::MantidWidgets::IFunctionView::functionAdded (std::string const & funStr) signal
User adds a function.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addFunctionEnd().
functionHelpRequest
void MantidQt::MantidWidgets::IFunctionView::functionHelpRequest () signal
User requested function help.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::createActions().
functionRemoved
void MantidQt::MantidWidgets::IFunctionView::functionRemoved (std::string const & functionIndex) signal
User removes a function.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::removeFunction().
functionRemovedString
void MantidQt::MantidWidgets::IFunctionView::functionRemovedString (std::string const & funStr) signal
User removes a function.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::removeFunction().
functionReplaced
void MantidQt::MantidWidgets::IFunctionView::functionReplaced (std::string const & funStr) signal
User replaces the whole function (eg, by pasting it from clipboard)
Referenced by MantidQt::MantidWidgets::FunctionTreeView::attributeChanged(), and MantidQt::MantidWidgets::FunctionTreeView::pasteFromClipboard().
getAttribute()
virtual IFunction::Attribute MantidQt::MantidWidgets::IFunctionView::getAttribute (std::string const & attrName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedAttribute().
getParameter()
virtual double MantidQt::MantidWidgets::IFunctionView::getParameter (std::string const & parameterName) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedParameter().
getSelectedFunction()
virtual IFunction_sptr MantidQt::MantidWidgets::IFunctionView::getSelectedFunction () pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRequestedFunctionHelp().
globalsChanged
void MantidQt::MantidWidgets::IFunctionView::globalsChanged (const std::vector< std::string > &) signal
User changed the list of global parameters.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addFunctionEnd(), MantidQt::MantidWidgets::FunctionTreeView::globalChanged(), and MantidQt::MantidWidgets::FunctionTreeView::removeFunction().
hasFunction()
virtual bool MantidQt::MantidWidgets::IFunctionView::hasFunction () const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
localParameterButtonClicked
void MantidQt::MantidWidgets::IFunctionView::localParameterButtonClicked (std::string const & parameterName) signal
In multi-dataset context a button value editor was clicked.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::parameterButtonClicked().
parameterChanged
void MantidQt::MantidWidgets::IFunctionView::parameterChanged (std::string const & parameterName) signal
Function parameter gets changed.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::parameterPropertyChanged().
parameterConstraintAdded
void MantidQt::MantidWidgets::IFunctionView::parameterConstraintAdded (std::string const & functionIndex, std::string const & constraint) signal
User sets a constraint.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addConstraints(), MantidQt::MantidWidgets::FunctionTreeView::addConstraints10(), MantidQt::MantidWidgets::FunctionTreeView::addConstraints50(), MantidQt::MantidWidgets::FunctionTreeView::constraintChanged(), and MantidQt::MantidWidgets::FunctionTreeView::removeConstraint().
parameterConstraintRemoved
void MantidQt::MantidWidgets::IFunctionView::parameterConstraintRemoved (std::string const & parameterName) signal
User removes a constraint.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::removeConstraint(), and MantidQt::MantidWidgets::FunctionTreeView::removeConstraints().
parameterTieChanged
void MantidQt::MantidWidgets::IFunctionView::parameterTieChanged (std::string const & parameterName, std::string const & tie) signal
User sets a tie.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addTie(), MantidQt::MantidWidgets::FunctionTreeView::fixParameter(), MantidQt::MantidWidgets::FunctionTreeView::removeTie(), and MantidQt::MantidWidgets::FunctionTreeView::tieChanged().
setAttributeValue()
template<typename T > void MantidQt::MantidWidgets::IFunctionView::setAttributeValue (std::string const & attributeName, T & value) inline
Definition at line 47 of file IFunctionView.h.
References value.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewAttributesFromModel().
setBooleanAttribute()
virtual void MantidQt::MantidWidgets::IFunctionView::setBooleanAttribute (std::string const & parameterName, bool value) protected pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
setDoubleAttribute()
virtual void MantidQt::MantidWidgets::IFunctionView::setDoubleAttribute (std::string const & parameterName, double value) protected pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
setErrorsEnabled()
virtual void MantidQt::MantidWidgets::IFunctionView::setErrorsEnabled (bool enabled) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setErrorsEnabled().
setFunction()
virtual void MantidQt::MantidWidgets::IFunctionView::setFunction (IFunction_sptr fun) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setFunction(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setFunctionString().
setGlobalParameters()
virtual void MantidQt::MantidWidgets::IFunctionView::setGlobalParameters (const std::vector< std::string > &) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setGlobalParameters(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewAddedFunction(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRemovedFunction().
setIntAttribute()
virtual void MantidQt::MantidWidgets::IFunctionView::setIntAttribute (std::string const & parameterName, int value) protected pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
setParameter()
virtual void MantidQt::MantidWidgets::IFunctionView::setParameter (std::string const & parameterName, double value) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setBackgroundA0(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterValue(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterValue(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setParameter(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewFromModel().
setParameterConstraint()
virtual void MantidQt::MantidWidgets::IFunctionView::setParameterConstraint (std::string const & parameterName, std::string const & constraint) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterConstraint(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewFromModel().
setParameterError()
virtual void MantidQt::MantidWidgets::IFunctionView::setParameterError (std::string const & parameterName, double error) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterValue(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setParameterError(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewFromModel().
setParameterTie()
virtual void MantidQt::MantidWidgets::IFunctionView::setParameterTie (std::string const & parameterName, std::string const & tie) pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterFixed(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterTie(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewFromModel().
setStringAttribute()
virtual void MantidQt::MantidWidgets::IFunctionView::setStringAttribute (std::string const & parameterName, std::string & value) protected pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
setVectorAttribute()
virtual void MantidQt::MantidWidgets::IFunctionView::setVectorAttribute (std::string const & parameterName, std::vector< double > & val) protected pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
showFunctionHelp()
virtual void MantidQt::MantidWidgets::IFunctionView::showFunctionHelp (std::string const &) const pure virtual
Implemented in MantidQt::MantidWidgets::FunctionTreeView.
Referenced by MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRequestedFunctionHelp().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/IFunctionView.h