Mantid: V3DPickleSuite Class Reference
V3DPickleSuite Class Reference
Static Public Member Functions
static dict getstate (const V3D &vector)
static void setstate (V3D &vector, dict state)
Detailed Description
Definition at line 79 of file V3D.cpp.
Member Function Documentation
getstate()
static dict V3DPickleSuite::getstate (const V3D & vector) inline static
Definition at line 81 of file V3D.cpp.
References Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
setstate()
static void V3DPickleSuite::setstate (V3D & vector, dict state) inline static
Definition at line 89 of file V3D.cpp.
References Mantid::Kernel::V3D::setX(), Mantid::Kernel::V3D::setY(), and Mantid::Kernel::V3D::setZ().
The documentation for this class was generated from the following file:
Framework/PythonInterface/mantid/kernel/src/Exports/V3D.cpp