Mantid: Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor Class Reference
Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor Class Reference
Small helper class to extract HKLs as V3D from table columns.
#include <PawleyFit.h>
Public Member Functions
Kernel::V3D operator() (const API::Column_const_sptr &hklColumn, size_t i) const
Tries to extract Miller indices as V3D from column.
Protected Member Functions
Kernel::V3D getHKLFromString (const std::string &hklString) const
Try to extract a V3D from the given string with different separators.
Kernel::V3D getHKLFromStringColumn (const API::Column_const_sptr &hklColumn, size_t i) const
Pass the cell value as string to getHKLFromString.
Kernel::V3D getHKLFromV3DColumn (const API::Column_const_sptr &hklColumn, size_t i) const
Returns the i-th cell of a V3D column.
Detailed Description
Small helper class to extract HKLs as V3D from table columns.
The table column can either store V3D directly, or a string with various separators: , ; [ ] (space)
Definition at line 27 of file PawleyFit.h.
Member Function Documentation
getHKLFromString()
V3D Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromString (const std::string & hklString) const protected
Try to extract a V3D from the given string with different separators.
Definition at line 372 of file PawleyFit.cpp.
References Mantid::Kernel::V3D::setX(), Mantid::Kernel::V3D::setY(), and Mantid::Kernel::V3D::setZ().
Referenced by getHKLFromStringColumn().
getHKLFromStringColumn()
V3D Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromStringColumn (const API::Column_const_sptr & hklColumn, size_t i) const protected
Pass the cell value as string to getHKLFromString.
Definition at line 366 of file PawleyFit.cpp.
References getHKLFromString().
Referenced by operator()().
getHKLFromV3DColumn()
V3D Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromV3DColumn (const API::Column_const_sptr & hklColumn, size_t i) const protected
Returns the i-th cell of a V3D column.
Definition at line 361 of file PawleyFit.cpp.
Referenced by operator()().
operator()()
V3D Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::operator() (const API::Column_const_sptr & hklColumn, size_t i) const
Tries to extract Miller indices as V3D from column.
Definition at line 352 of file PawleyFit.cpp.
References getHKLFromStringColumn(), and getHKLFromV3DColumn().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/PawleyFit.h
Framework/CurveFitting/src/Algorithms/PawleyFit.cpp