Mantid: MantidQt::MantidWidgets::ADSAdapter Class Reference
MantidQt::MantidWidgets::ADSAdapter Class Reference
#include <ADSAdapter.h>
Public Member Functions
ADSAdapter ()
bool doesWorkspaceExist (const std::string &wsname) const override
std::string getNewName () const override
std::string getOldName () const override
void registerPresenter (Presenter_wptr presenter) override
std::map< std::string, Mantid::API::Workspace_sptr > topLevelItems () const override
~ADSAdapter () override
Public Member Functions inherited from MantidQt::MantidWidgets::WorkspaceProvider
virtual ~WorkspaceProvider ()=default
Private Member Functions
void handleAddWorkspace (Mantid::API::WorkspaceAddNotification_ptr pNf)
void handleClearADS (Mantid::API::ClearADSNotification_ptr pNf)
void handleDeleteWorkspace (Mantid::API::WorkspacePostDeleteNotification_ptr pNf)
void handleGroupWorkspaces (Mantid::API::WorkspacesGroupedNotification_ptr pNf)
void handleRenameWorkspace (Mantid::API::WorkspaceRenameNotification_ptr pNf)
void handleReplaceWorkspace (Mantid::API::WorkspaceAfterReplaceNotification_ptr pNf)
void handleUnGroupWorkspace (Mantid::API::WorkspaceUnGroupingNotification_ptr pNf)
void handleWorkspaceGroupUpdate (Mantid::API::GroupUpdatedNotification_ptr pNf)
Presenter_sptr lockPresenter ()
Locks the presenter as shared_ptr for use internally.
Private Attributes
Poco::NObserver< ADSAdapter, Mantid::API::WorkspaceAddNotification > m_addObserver
Poco::NObserver< ADSAdapter, Mantid::API::ClearADSNotification > m_clearADSObserver
Poco::NObserver< ADSAdapter, Mantid::API::WorkspacePostDeleteNotification > m_deleteObserver
Poco::NObserver< ADSAdapter, Mantid::API::WorkspacesGroupedNotification > m_groupworkspacesObserver
std::string m_newName
std::string m_oldName
Presenter_wptr m_presenter
Poco::NObserver< ADSAdapter, Mantid::API::WorkspaceRenameNotification > m_renameObserver
Poco::NObserver< ADSAdapter, Mantid::API::WorkspaceAfterReplaceNotification > m_replaceObserver
Poco::NObserver< ADSAdapter, Mantid::API::WorkspaceUnGroupingNotification > m_ungroupworkspaceObserver
Poco::NObserver< ADSAdapter, Mantid::API::GroupUpdatedNotification > m_workspaceGroupUpdateObserver
Detailed Description
Author
Lamar Moore
Date
24-08-2016
Version
1.0
Definition at line 22 of file ADSAdapter.h.
Constructor & Destructor Documentation
ADSAdapter()
MantidQt::MantidWidgets::ADSAdapter::ADSAdapter () explicit
Definition at line 16 of file ADSAdapter.cpp.
References m_addObserver, m_clearADSObserver, m_deleteObserver, m_groupworkspacesObserver, m_renameObserver, m_replaceObserver, m_ungroupworkspaceObserver, and m_workspaceGroupUpdateObserver.
~ADSAdapter()
MantidQt::MantidWidgets::ADSAdapter::~ADSAdapter () override
Definition at line 37 of file ADSAdapter.cpp.
References m_addObserver, m_clearADSObserver, m_deleteObserver, m_groupworkspacesObserver, m_renameObserver, m_replaceObserver, m_ungroupworkspaceObserver, and m_workspaceGroupUpdateObserver.
Member Function Documentation
doesWorkspaceExist()
bool MantidQt::MantidWidgets::ADSAdapter::doesWorkspaceExist (const std::string & wsname) const override virtual
Implements MantidQt::MantidWidgets::WorkspaceProvider.
Definition at line 52 of file ADSAdapter.cpp.
getNewName()
std::string MantidQt::MantidWidgets::ADSAdapter::getNewName () const override virtual
Implements MantidQt::MantidWidgets::WorkspaceProvider.
Definition at line 71 of file ADSAdapter.cpp.
References m_newName.
getOldName()
std::string MantidQt::MantidWidgets::ADSAdapter::getOldName () const override virtual
Implements MantidQt::MantidWidgets::WorkspaceProvider.
Definition at line 70 of file ADSAdapter.cpp.
References m_oldName.
handleAddWorkspace()
void MantidQt::MantidWidgets::ADSAdapter::handleAddWorkspace (Mantid::API::WorkspaceAddNotification_ptr pNf) private
Definition at line 74 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceLoaded.
handleClearADS()
void MantidQt::MantidWidgets::ADSAdapter::handleClearADS (Mantid::API::ClearADSNotification_ptr pNf) private
Definition at line 89 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesCleared.
handleDeleteWorkspace()
void MantidQt::MantidWidgets::ADSAdapter::handleDeleteWorkspace (Mantid::API::WorkspacePostDeleteNotification_ptr pNf) private
Definition at line 84 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceDeleted.
handleGroupWorkspaces()
void MantidQt::MantidWidgets::ADSAdapter::handleGroupWorkspaces (Mantid::API::WorkspacesGroupedNotification_ptr pNf) private
Definition at line 102 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesGrouped.
handleRenameWorkspace()
void MantidQt::MantidWidgets::ADSAdapter::handleRenameWorkspace (Mantid::API::WorkspaceRenameNotification_ptr pNf) private
Definition at line 94 of file ADSAdapter.cpp.
References lockPresenter(), m_newName, m_oldName, and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceRenamed.
handleReplaceWorkspace()
void MantidQt::MantidWidgets::ADSAdapter::handleReplaceWorkspace (Mantid::API::WorkspaceAfterReplaceNotification_ptr pNf) private
Definition at line 79 of file ADSAdapter.cpp.
References MantidQt::MantidWidgets::WorkspaceProviderNotifiable::GenericUpdateNotification, and lockPresenter().
handleUnGroupWorkspace()
void MantidQt::MantidWidgets::ADSAdapter::handleUnGroupWorkspace (Mantid::API::WorkspaceUnGroupingNotification_ptr pNf) private
Definition at line 107 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspacesUngrouped.
handleWorkspaceGroupUpdate()
void MantidQt::MantidWidgets::ADSAdapter::handleWorkspaceGroupUpdate (Mantid::API::GroupUpdatedNotification_ptr pNf) private
Definition at line 112 of file ADSAdapter.cpp.
References lockPresenter(), and MantidQt::MantidWidgets::WorkspaceProviderNotifiable::WorkspaceGroupUpdated.
lockPresenter()
Presenter_sptr MantidQt::MantidWidgets::ADSAdapter::lockPresenter () private
Locks the presenter as shared_ptr for use internally.
Definition at line 61 of file ADSAdapter.cpp.
References m_presenter.
Referenced by handleAddWorkspace(), handleClearADS(), handleDeleteWorkspace(), handleGroupWorkspaces(), handleRenameWorkspace(), handleReplaceWorkspace(), handleUnGroupWorkspace(), and handleWorkspaceGroupUpdate().
registerPresenter()
void MantidQt::MantidWidgets::ADSAdapter::registerPresenter (Presenter_wptr presenter) override virtual
Implements MantidQt::MantidWidgets::WorkspaceProvider.
Definition at line 50 of file ADSAdapter.cpp.
References m_presenter.
topLevelItems()
std::map< std::string, Mantid::API::Workspace_sptr > MantidQt::MantidWidgets::ADSAdapter::topLevelItems () const override virtual
Implements MantidQt::MantidWidgets::WorkspaceProvider.
Definition at line 56 of file ADSAdapter.cpp.
Member Data Documentation
m_addObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspaceAddNotification> MantidQt::MantidWidgets::ADSAdapter::m_addObserver private
Definition at line 44 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_clearADSObserver
Poco::NObserver<ADSAdapter, Mantid::API::ClearADSNotification> MantidQt::MantidWidgets::ADSAdapter::m_clearADSObserver private
Definition at line 53 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_deleteObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspacePostDeleteNotification> MantidQt::MantidWidgets::ADSAdapter::m_deleteObserver private
Definition at line 50 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_groupworkspacesObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspacesGroupedNotification> MantidQt::MantidWidgets::ADSAdapter::m_groupworkspacesObserver private
Definition at line 59 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_newName
std::string MantidQt::MantidWidgets::ADSAdapter::m_newName private
Definition at line 36 of file ADSAdapter.h.
Referenced by getNewName(), and handleRenameWorkspace().
m_oldName
std::string MantidQt::MantidWidgets::ADSAdapter::m_oldName private
Definition at line 35 of file ADSAdapter.h.
Referenced by getOldName(), and handleRenameWorkspace().
m_presenter
Presenter_wptr MantidQt::MantidWidgets::ADSAdapter::m_presenter private
Definition at line 38 of file ADSAdapter.h.
Referenced by lockPresenter(), and registerPresenter().
m_renameObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspaceRenameNotification> MantidQt::MantidWidgets::ADSAdapter::m_renameObserver private
Definition at line 56 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_replaceObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspaceAfterReplaceNotification> MantidQt::MantidWidgets::ADSAdapter::m_replaceObserver private
Definition at line 47 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_ungroupworkspaceObserver
Poco::NObserver<ADSAdapter, Mantid::API::WorkspaceUnGroupingNotification> MantidQt::MantidWidgets::ADSAdapter::m_ungroupworkspaceObserver private
Definition at line 62 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
m_workspaceGroupUpdateObserver
Poco::NObserver<ADSAdapter, Mantid::API::GroupUpdatedNotification> MantidQt::MantidWidgets::ADSAdapter::m_workspaceGroupUpdateObserver private
Definition at line 65 of file ADSAdapter.h.
Referenced by ADSAdapter(), and ~ADSAdapter().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/ADSAdapter.h
qt/widgets/common/src/WorkspacePresenter/ADSAdapter.cpp