Mantid: Mantid::DataHandling::LoadBinaryStl Class Reference
Mantid::DataHandling::LoadBinaryStl Class Reference
#include <LoadBinaryStl.h>
Public Member Functions
LoadBinaryStl (std::string filename, ScaleUnits scaleType)
LoadBinaryStl (std::string filename, ScaleUnits scaleType, ReadMaterial::MaterialParameters params)
std::unique_ptr< Geometry::MeshObject > readShape () override
Public Member Functions inherited from Mantid::DataHandling::LoadStl
LoadStl (std::string filename, std::ios_base::openmode mode, ScaleUnits scaleType)
LoadStl (std::string filename, std::ios_base::openmode mode, ScaleUnits scaleType, ReadMaterial::MaterialParameters params)
virtual ~LoadStl () override=default
Public Member Functions inherited from Mantid::DataHandling::LoadSingleMesh
LoadSingleMesh (std::string filename, std::ios_base::openmode mode, ScaleUnits scaleType)
virtual ~LoadSingleMesh ()
Public Member Functions inherited from Mantid::DataHandling::MeshFileIO
Kernel::V3D createScaledV3D (double xVal, double yVal, double zVal)
scales a 3D point according the units defined in the MeshFileIO class
ScaleUnits getScaleType ()
std::shared_ptr< Geometry::MeshObject > rotate (std::shared_ptr< Geometry::MeshObject > environmentMesh, double xRotation, double yRotation, double zRotation)
Rotates the environment by a generated matrix.
std::shared_ptr< Geometry::MeshObject > translate (std::shared_ptr< Geometry::MeshObject > environmentMesh, const std::vector< double > &translationVector)
translates the environment by a provided matrix
Static Public Member Functions
static bool isBinarySTL (const std::string &filename)
Static Public Attributes
static constexpr int HEADER_SIZE = 80
static constexpr std::ios_base::openmode openMode = std::ios::in | std::ios::binary
static constexpr uint32_t TRIANGLE_COUNT_DATA_SIZE = 4
static constexpr uint32_t TRIANGLE_DATA_SIZE = 50
static constexpr uint32_t VECTOR_DATA_SIZE = 12
Private Member Functions
void readTriangle (Kernel::BinaryStreamReader, uint32_t &vertexCount)
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataHandling::LoadStl
bool areEqualVertices (Kernel::V3D const &v1, Kernel::V3D const &v2) const
void changeToVector ()
Protected Member Functions inherited from Mantid::DataHandling::MeshFileIO
MeshFileIO (ScaleUnits scaleType)
MeshFileIO (ScaleUnits scaleType, std::vector< uint32_t > triangles, std::vector< Kernel::V3D > vertices)
float removeScale (double value)
double scaleValue (double val)
void setScaleType (const ScaleUnits scaleType)
Protected Attributes inherited from Mantid::DataHandling::LoadStl
ReadMaterial::MaterialParameters m_params
bool m_setMaterial
std::unordered_set< std::pair< Kernel::V3D, uint32_t >, HashV3DPair, V3DTrueComparator > vertexSet
Protected Attributes inherited from Mantid::DataHandling::LoadSingleMesh
std::ifstream m_file
const std::string m_filename
Protected Attributes inherited from Mantid::DataHandling::MeshFileIO
ScaleUnits m_scaleType
std::vector< uint32_t > m_triangle
std::vector< Kernel::V3D > m_vertices
Detailed Description
Definition at line 24 of file LoadBinaryStl.h.
Constructor & Destructor Documentation
LoadBinaryStl() [1/2]
Mantid::DataHandling::LoadBinaryStl::LoadBinaryStl (std::string filename, ScaleUnits scaleType) inline
Definition at line 31 of file LoadBinaryStl.h.
LoadBinaryStl() [2/2]
Mantid::DataHandling::LoadBinaryStl::LoadBinaryStl (std::string filename, ScaleUnits scaleType, ReadMaterial::MaterialParameters params) inline
Definition at line 33 of file LoadBinaryStl.h.
Member Function Documentation
isBinarySTL()
bool Mantid::DataHandling::LoadBinaryStl::isBinarySTL (const std::string & filename) static
Definition at line 25 of file LoadBinaryStl.cpp.
References HEADER_SIZE, openMode, TRIANGLE_COUNT_DATA_SIZE, and TRIANGLE_DATA_SIZE.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL().
readShape()
std::unique_ptr< Geometry::MeshObject > Mantid::DataHandling::LoadBinaryStl::readShape () override virtual
Implements Mantid::DataHandling::LoadSingleMesh.
Definition at line 51 of file LoadBinaryStl.cpp.
References Mantid::DataHandling::ReadMaterial::buildMaterial(), Mantid::DataHandling::LoadStl::changeToVector(), HEADER_SIZE, Mantid::DataHandling::LoadSingleMesh::m_file, Mantid::DataHandling::LoadStl::m_params, Mantid::DataHandling::LoadStl::m_setMaterial, Mantid::DataHandling::MeshFileIO::m_triangle, Mantid::DataHandling::MeshFileIO::m_vertices, Mantid::Kernel::BinaryStreamReader::moveStreamToPosition(), readTriangle(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), std::to_string(), TRIANGLE_COUNT_DATA_SIZE, TRIANGLE_DATA_SIZE, and VECTOR_DATA_SIZE.
readTriangle()
void Mantid::DataHandling::LoadBinaryStl::readTriangle (Kernel::BinaryStreamReader streamReader, uint32_t & vertexCount) private
Definition at line 86 of file LoadBinaryStl.cpp.
References Mantid::DataHandling::MeshFileIO::createScaledV3D(), Mantid::DataHandling::MeshFileIO::m_triangle, vec, and Mantid::DataHandling::LoadStl::vertexSet.
Referenced by readShape().
Member Data Documentation
HEADER_SIZE
constexpr int Mantid::DataHandling::LoadBinaryStl::HEADER_SIZE = 80 static constexpr
Definition at line 26 of file LoadBinaryStl.h.
Referenced by isBinarySTL(), and readShape().
openMode
constexpr std::ios_base::openmode Mantid::DataHandling::LoadBinaryStl::openMode = std::ios::in | std::ios::binary static constexpr
Definition at line 30 of file LoadBinaryStl.h.
Referenced by isBinarySTL().
TRIANGLE_COUNT_DATA_SIZE
constexpr uint32_t Mantid::DataHandling::LoadBinaryStl::TRIANGLE_COUNT_DATA_SIZE = 4 static constexpr
Definition at line 28 of file LoadBinaryStl.h.
Referenced by isBinarySTL(), and readShape().
TRIANGLE_DATA_SIZE
constexpr uint32_t Mantid::DataHandling::LoadBinaryStl::TRIANGLE_DATA_SIZE = 50 static constexpr
Definition at line 27 of file LoadBinaryStl.h.
Referenced by isBinarySTL(), and readShape().
VECTOR_DATA_SIZE
constexpr uint32_t Mantid::DataHandling::LoadBinaryStl::VECTOR_DATA_SIZE = 12 static constexpr
Definition at line 29 of file LoadBinaryStl.h.
Referenced by readShape().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadBinaryStl.h
Framework/DataHandling/src/LoadBinaryStl.cpp