Mantid: Mantid::Kernel::MaterialXMLParser Class Reference
Mantid::Kernel::MaterialXMLParser Class Reference
Read an XML definition of a Material and produce a new Material object.
#include <MaterialXMLParser.h>
Public Member Functions
Material parse (Poco::XML::Element *node, const std::string &XMLFilePath="") const
Takes a pointer to an XML node that is assumed to point at a "material" tag.
Material parse (std::istream &istr) const
Takes a stream that is assumed to contain a single complete material definition, reads the definition and produces a new Material object.
Static Public Attributes
static constexpr const char * MATERIAL_TAG = "material"
Detailed Description
Read an XML definition of a Material and produce a new Material object.
Definition at line 25 of file MaterialXMLParser.h.
Member Function Documentation
parse() [1/2]
Material Mantid::Kernel::MaterialXMLParser::parse (Poco::XML::Element * element, const std::string & XMLFilePath = "") const
Takes a pointer to an XML node that is assumed to point at a "material" tag.
It reads the definition and produces a new Material object.
Parameters
element A pointer to an Element node that is a "material" tag
XMLFilePath path of the sample environment file where the material specification was read from (if any)
Returns
A new Material object
Definition at line 194 of file MaterialXMLParser.cpp.
References Mantid::Kernel::MaterialBuilder::build(), Mantid::Kernel::MaterialBuilder::setAttenuationSearchPath(), and Mantid::Kernel::MaterialBuilder::setName().
parse() [2/2]
Material Mantid::Kernel::MaterialXMLParser::parse (std::istream & istr) const
Takes a stream that is assumed to contain a single complete material definition, reads the definition and produces a new Material object.
If many definitions are present then the first one is read
Parameters
istr A reference to a stream
Returns
A new Material object
Definition at line 147 of file MaterialXMLParser.cpp.
References MATERIAL_TAG, and parse().
Referenced by Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), parse(), and Mantid::DataHandling::SampleEnvironmentSpecParser::parseMaterials().
Member Data Documentation
MATERIAL_TAG
constexpr const char* Mantid::Kernel::MaterialXMLParser::MATERIAL_TAG = "material" static constexpr
Definition at line 27 of file MaterialXMLParser.h.
Referenced by parse().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MaterialXMLParser.h
Framework/Kernel/src/MaterialXMLParser.cpp