Mantid: Mantid::API::OperatorOverloads Namespace Reference
Mantid::API::OperatorOverloads Namespace Reference
Functions
template MANTID_API_DLL IMDHistoWorkspace_sptr executeBinaryOperation (const std::string &, const IMDHistoWorkspace_sptr, const IMDHistoWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL IMDHistoWorkspace_sptr executeBinaryOperation (const std::string &, const IMDHistoWorkspace_sptr, const MatrixWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL IMDWorkspace_sptr executeBinaryOperation (const std::string &, const IMDWorkspace_sptr, const IMDWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL IMDWorkspace_sptr executeBinaryOperation (const std::string &, const IMDWorkspace_sptr, const MatrixWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL WorkspaceGroup_sptr executeBinaryOperation (const std::string &, const IMDWorkspace_sptr, const WorkspaceGroup_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL IMDHistoWorkspace_sptr executeBinaryOperation (const std::string &, const MatrixWorkspace_sptr, const IMDHistoWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL IMDWorkspace_sptr executeBinaryOperation (const std::string &, const MatrixWorkspace_sptr, const IMDWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL MatrixWorkspace_sptr executeBinaryOperation (const std::string &, const MatrixWorkspace_sptr, const MatrixWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL WorkspaceGroup_sptr executeBinaryOperation (const std::string &, const MatrixWorkspace_sptr, const WorkspaceGroup_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL WorkspaceGroup_sptr executeBinaryOperation (const std::string &, const WorkspaceGroup_sptr, const IMDWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL WorkspaceGroup_sptr executeBinaryOperation (const std::string &, const WorkspaceGroup_sptr, const MatrixWorkspace_sptr, bool, bool, const std::string &, bool)
template MANTID_API_DLL WorkspaceGroup_sptr executeBinaryOperation (const std::string &, const WorkspaceGroup_sptr, const WorkspaceGroup_sptr, bool, bool, const std::string &, bool)
template<typename LHSType , typename RHSType , typename ResultType >
ResultType executeBinaryOperation (const std::string &algorithmName, const LHSType lhs, const RHSType rhs, bool lhsAsOutput, bool child, const std::string &name, bool rethrow)
Performs a binary operation on two workspaces.
template<typename LHSType , typename RHSType , typename ResultType >
DLLExport ResultType executeBinaryOperation (const std::string &algorithmName, const LHSType lhs, const RHSType rhs, bool lhsAsOutput=false, bool child=true, const std::string &name="", bool rethrow=false)
Performs a binary operation on two workspaces.
Function Documentation
executeBinaryOperation() [1/14]
template MANTID_API_DLL IMDHistoWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const IMDHistoWorkspace_sptr , const IMDHistoWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [2/14]
template MANTID_API_DLL IMDHistoWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const IMDHistoWorkspace_sptr , const MatrixWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [3/14]
template MANTID_API_DLL IMDWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const IMDWorkspace_sptr , const IMDWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [4/14]
template MANTID_API_DLL IMDWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const IMDWorkspace_sptr , const MatrixWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [5/14]
template MANTID_API_DLL WorkspaceGroup_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const IMDWorkspace_sptr , const WorkspaceGroup_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [6/14]
template MANTID_API_DLL IMDHistoWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const MatrixWorkspace_sptr , const IMDHistoWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [7/14]
template MANTID_API_DLL IMDWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const MatrixWorkspace_sptr , const IMDWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [8/14]
template MANTID_API_DLL MatrixWorkspace_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const MatrixWorkspace_sptr , const MatrixWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [9/14]
template MANTID_API_DLL WorkspaceGroup_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const MatrixWorkspace_sptr , const WorkspaceGroup_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [10/14]
template MANTID_API_DLL WorkspaceGroup_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const WorkspaceGroup_sptr , const IMDWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [11/14]
template MANTID_API_DLL WorkspaceGroup_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const WorkspaceGroup_sptr , const MatrixWorkspace_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [12/14]
template MANTID_API_DLL WorkspaceGroup_sptr Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & , const WorkspaceGroup_sptr , const WorkspaceGroup_sptr , bool , bool , const std::string & , bool)
References executeBinaryOperation().
executeBinaryOperation() [13/14]
template<typename LHSType , typename RHSType , typename ResultType > ResultType Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & algorithmName, const LHSType lhs, const RHSType rhs, bool lhsAsOutput, bool child, const std::string & name, bool rethrow)
Performs a binary operation on two workspaces.
Parameters
algorithmName :: The name of the binary operation to perform
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
lhsAsOutput :: If true, indicates that the lhs input is the same workspace as the output one
child :: If true the algorithm is run as a child
name :: If child is true and this is not an inplace operation then this name is used as output
rethrow :: A flag indicating whether to rethrow exceptions
Returns
The result in a workspace shared pointer
Definition at line 37 of file WorkspaceOpOverloads.cpp.
References executeBinaryOperation(), name, and rhs.
Referenced by executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), and executeBinaryOperation().
executeBinaryOperation() [14/14]
template<typename LHSType , typename RHSType , typename ResultType > DLLExport ResultType Mantid::API::OperatorOverloads::executeBinaryOperation (const std::string & algorithmName, const LHSType lhs, const RHSType rhs, bool lhsAsOutput, bool child, const std::string & name, bool rethrow)
Performs a binary operation on two workspaces.
Parameters
algorithmName :: The name of the binary operation to perform
lhs :: left hand side workspace shared pointer
rhs :: right hand side workspace shared pointer
lhsAsOutput :: If true, indicates that the lhs input is the same workspace as the output one
child :: If true the algorithm is run as a child
name :: If child is true and this is not an inplace operation then this name is used as output
rethrow :: A flag indicating whether to rethrow exceptions
Returns
The result in a workspace shared pointer
Definition at line 37 of file WorkspaceOpOverloads.cpp.
References executeBinaryOperation(), name, and rhs.
Referenced by executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), executeBinaryOperation(), and executeBinaryOperation().