Mantid: MantidQt::MantidWidgets::ImageInfoModelMD Class Reference
MantidQt::MantidWidgets::ImageInfoModelMD Class Reference
#include <ImageInfoModelMD.h>
Public Member Functions
ImageInfoModel::ImageInfo info (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues) const override
Creates a list with information about the coordinates in the workspace.
Public Member Functions inherited from MantidQt::MantidWidgets::ImageInfoModel
virtual ImageInfoModel::ImageInfo info (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues) const =0
Creates information about the point at the given coordinates in the workspace.
virtual ~ImageInfoModel ()=default
Additional Inherited Members
Static Public Member Functions inherited from MantidQt::MantidWidgets::ImageInfoModel
static const QString defaultFormat (const double x)
static const QString defaultFormat (const int x)
Static Public Attributes inherited from MantidQt::MantidWidgets::ImageInfoModel
static constexpr auto DecimalFormat = 'f'
Default float format.
static constexpr auto FourDigitPrecision = 4
Default float precision.
static const QString MissingValue = QString("-")
MissingValue identifier.
static constexpr auto UnsetValue = std::numeric_limits<double>::max()
Value to indicate that a MissingValue should be shown.
Detailed Description
Definition at line 17 of file ImageInfoModelMD.h.
Member Function Documentation
info()
ImageInfoModel::ImageInfo MantidQt::MantidWidgets::ImageInfoModelMD::info (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues) const override virtual
Creates a list with information about the coordinates in the workspace.
Creates information about the point at the given coordinates in the workspace.
Parameters
x x data coordinate
y y data coordinate
signal the signal value at x, y
extraValues extra values to be displayed in the image info table
Returns
An ImageInfo object describing the point
Parameters
x x data coordinate
y y data coordinate
signal the signal value at x, y
extraValues extra values to be displayed in the image info table
Returns
An ImageInfo object
Implements MantidQt::MantidWidgets::ImageInfoModel.
Definition at line 14 of file ImageInfoModelMD.cpp.
References MantidQt::MantidWidgets::ImageInfoModel::defaultFormat(), info(), MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::m_names, MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::m_values, MantidQt::MantidWidgets::ImageInfoModel::MissingValue, MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::setValue(), MantidQt::MantidWidgets::ImageInfoModel::UnsetValue, value, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by info().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoModelMD.h
qt/widgets/common/src/ImageInfoModelMD.cpp