Mantid: Framework/PythonInterface/mantid/api/src/Exports/AlgorithmHistory.cpp File Reference
AlgorithmHistory.cpp File Reference
#include "MantidAPI/AlgorithmHistory.h"
#include "MantidAPI/IAlgorithm.h"
#include "MantidKernel/PropertyHistory.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/list.hpp>
#include <boost/python/operators.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/return_internal_reference.hpp>
#include <boost/python/self.hpp>
Functions
void export_AlgorithmHistory ()
boost::python::list getChildrenAsList (const std::shared_ptr< AlgorithmHistory > &self)
Return a Python list of child history objects from the history as this is far easier to work with than a set.
boost::python::list getPropertiesAsList (const AlgorithmHistory &self)
Return a Python list of property history objects from the history.
Function Documentation
export_AlgorithmHistory()
void export_AlgorithmHistory ()
Definition at line 53 of file AlgorithmHistory.cpp.
References Mantid::API::AlgorithmHistory::childHistorySize(), Mantid::API::AlgorithmHistory::execCount(), Mantid::API::AlgorithmHistory::executionDate(), Mantid::API::AlgorithmHistory::executionDuration(), Mantid::API::AlgorithmHistory::getChildAlgorithm(), Mantid::API::AlgorithmHistory::getChildAlgorithmHistory(), getChildrenAsList(), getPropertiesAsList(), Mantid::API::AlgorithmHistory::getPropertyValue(), Mantid::API::AlgorithmHistory::getStoreInADS(), Mantid::API::AlgorithmHistory::name(), and Mantid::API::AlgorithmHistory::version().
getChildrenAsList()
boost::python::list getChildrenAsList (const std::shared_ptr< AlgorithmHistory > & self)
Return a Python list of child history objects from the history as this is far easier to work with than a set.
Parameters
self :: A reference to the AlgorithmHistory that called this method
Returns
A python list created from the set of child algorithm histories
Definition at line 29 of file AlgorithmHistory.cpp.
References history.
Referenced by export_AlgorithmHistory().
getPropertiesAsList()
boost::python::list getPropertiesAsList (const AlgorithmHistory & self)
Return a Python list of property history objects from the history.
Parameters
self :: A reference to the AlgorithmHistory that called this method
Returns
A python list created from the set of property histories
Definition at line 44 of file AlgorithmHistory.cpp.
References Mantid::API::AlgorithmHistory::getProperties(), and history.
Referenced by export_AlgorithmHistory().