Mantid: ProgressPresenter Class Reference
ProgressPresenter Class Reference
#include <ProgressPresenter.h>
Public Member Functions
void clear ()
void doReport (const std::string &) override
Pure virtual method that does the progress reporting, to be overridden.
ProgressPresenter (double start, double end, int64_t nSteps, MantidQt::MantidWidgets::ProgressableView *const progressableView)
void setAsEndlessIndicator ()
void setAsPercentageIndicator ()
virtual ~ProgressPresenter ()=default
Public Member Functions inherited from Mantid::Kernel::ProgressBase
virtual void doReport (const std::string &msg="")=0
Pure virtual method that does the progress reporting, to be overridden.
double getEstimatedTime () const
Returns the estimated number of seconds until the algorithm completes.
virtual bool hasCancellationBeenRequested () const
Override so that the reporter can inform whether a cancellation request has been used.
ProgressBase & operator= (const ProgressBase &rhs)
ProgressBase ()
Default constructor.
ProgressBase (const ProgressBase &source)
Copy constructor that builds a new ProgressBase object.
ProgressBase (double start, double end, int64_t numSteps)
Creates a ProgressBase instance.
void report ()
Increments the loop counter by 1, then sends the progress notification on behalf of its algorithm.
void report (const std::string &msg)
Increments the loop counter by 1, then sends the progress notification on behalf of its algorithm.
void report (int64_t i, const std::string &msg="")
Sends the progress notification on behalf of its algorithm.
void reportIncrement (int inc, const std::string &msg="")
Sends the progress notification and increment the loop counter by more than one.
void reportIncrement (size_t inc, const std::string &msg="")
Sends the progress notification and increment the loop counter by more than one.
void resetNumSteps (int64_t nsteps, double start, double end)
Change the number of steps between start/end.
void setNotifyStep (double notifyStepPct)
Override the frequency at which notifications are sent out.
void setNumSteps (int64_t nsteps)
Change the number of steps between start/end.
virtual ~ProgressBase ()
Destructor.
Private Attributes
MantidQt::MantidWidgets::ProgressableView *const m_progressableView
Additional Inherited Members
Protected Attributes inherited from Mantid::Kernel::ProgressBase
double m_end
Ending progress.
std::atomic< int64_t > m_i
Loop counter.
int64_t m_ifirst
Loop counter initial value.
std::atomic< int64_t > m_last_reported
Last loop counter value the was a peport.
int64_t m_notifyStep
Frequency of sending the notification (every m_step times)
double m_notifyStepPct
Frequency of sending the notification (as a min percentage step, e.g.
int m_notifyStepPrecision
Digits of precision in the reporting.
int64_t m_numSteps
Loop counter upper bound.
double m_start
Starting progress.
double m_step
Progress increment at each loop.
std::unique_ptr< Kernel::Timer > m_timeElapsed
Timer that is started when the progress bar is constructed.
Detailed Description
Definition at line 12 of file ProgressPresenter.h.
Constructor & Destructor Documentation
ProgressPresenter()
ProgressPresenter::ProgressPresenter (double start, double end, int64_t nSteps, MantidQt::MantidWidgets::ProgressableView *const progressableView) inline
Definition at line 17 of file ProgressPresenter.h.
References MantidQt::MantidWidgets::ProgressableView::clearProgress(), m_progressableView, and MantidQt::MantidWidgets::ProgressableView::setProgressRange().
~ProgressPresenter()
virtual ProgressPresenter::~ProgressPresenter () virtual default
Member Function Documentation
clear()
void ProgressPresenter::clear () inline
Definition at line 32 of file ProgressPresenter.h.
References MantidQt::MantidWidgets::ProgressableView::clearProgress(), and m_progressableView.
doReport()
void ProgressPresenter::doReport (const std::string & msg) inline override virtual
Pure virtual method that does the progress reporting, to be overridden.
Implements Mantid::Kernel::ProgressBase.
Definition at line 28 of file ProgressPresenter.h.
References MantidQt::MantidWidgets::ProgressableView::isPercentageIndicator(), Mantid::Kernel::ProgressBase::m_i, m_progressableView, and MantidQt::MantidWidgets::ProgressableView::setProgress().
setAsEndlessIndicator()
void ProgressPresenter::setAsEndlessIndicator () inline
Definition at line 34 of file ProgressPresenter.h.
References m_progressableView, and MantidQt::MantidWidgets::ProgressableView::setAsEndlessIndicator().
setAsPercentageIndicator()
void ProgressPresenter::setAsPercentageIndicator () inline
Definition at line 33 of file ProgressPresenter.h.
References m_progressableView, and MantidQt::MantidWidgets::ProgressableView::setAsPercentageIndicator().
Member Data Documentation
m_progressableView
MantidQt::MantidWidgets::ProgressableView* const ProgressPresenter::m_progressableView private
Definition at line 14 of file ProgressPresenter.h.
Referenced by clear(), doReport(), ProgressPresenter(), setAsEndlessIndicator(), and setAsPercentageIndicator().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/ProgressPresenter.h