Mantid: qt/widgets/common/inc/MantidQtWidgets/Common/Batch/AssertOrThrow.h File Reference
AssertOrThrow.h File Reference
#include <stdexcept>
#include <string>
Functions
void assertOrThrow (bool condition, std::string const &message)
See the developer documentation for Batch Widget at developer.mantidproject.org/BatchWidget/index.html.
Function Documentation
assertOrThrow()
void assertOrThrow (bool condition, std::string const & message) inline
See the developer documentation for Batch Widget at developer.mantidproject.org/BatchWidget/index.html.
Definition at line 15 of file AssertOrThrow.h.
Referenced by MantidQt::MantidWidgets::Batch::fromFilteredModel(), MantidQt::MantidWidgets::Batch::fromMainModel(), MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf(), MantidQt::MantidWidgets::Batch::modelItemFromIndex(), MantidQt::MantidWidgets::Batch::RowLocation::parent(), MantidQt::MantidWidgets::Batch::pathsSameUntilDepth(), MantidQt::MantidWidgets::Batch::RowLocation::relativeTo(), MantidQt::MantidWidgets::Batch::JobTreeView::removeRowAt(), and MantidQt::MantidWidgets::Batch::JobTreeView::replaceRows().