Mantid: Framework/PythonInterface/mantid/api/src/Exports/IPeaksWorkspace.cpp File Reference
IPeaksWorkspace.cpp File Reference
#include "MantidAPI/IPeaksWorkspace.h"
#include "MantidAPI/Run.h"
#include "MantidGeometry/Crystal/IPeak.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/api/RegisterWorkspacePtrToPython.h"
#include "MantidPythonInterface/core/Converters/PyObjectToV3D.h"
#include "MantidPythonInterface/core/Converters/PySequenceToVector.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/none.hpp>
#include <boost/python/class.hpp>
#include <boost/python/iterator.hpp>
#include <boost/python/manage_new_object.hpp>
#include <boost/python/return_internal_reference.hpp>
#include <optional>
#include <utility>
Functions
void export_IPeaksWorkspace ()
void export_IPeaksWorkspaceIterator ()
Function Documentation
export_IPeaksWorkspace()
void export_IPeaksWorkspace ()
Definition at line 266 of file IPeaksWorkspace.cpp.
References Mantid::API::IPeaksWorkspace::getNumberPeaks(), Mantid::API::IPeaksWorkspace::getPeakPtr(), Mantid::API::IPeaksWorkspace::hasIntegratedPeaks(), and Mantid::API::IPeaksWorkspace::peakInfoNumber().
export_IPeaksWorkspaceIterator()
void export_IPeaksWorkspaceIterator ()
Definition at line 260 of file IPeaksWorkspace.cpp.