Mantid: Mantid::DataObjects::SpecialWorkspace2D Class Reference
Mantid::DataObjects::SpecialWorkspace2D Class Reference
#include <SpecialWorkspace2D.h>
Public Member Functions
void binaryOperation (const std::shared_ptr< const SpecialWorkspace2D > &ws, const unsigned int operatortype)
Return the result of operator & @ parameter @ return.
void binaryOperation (const unsigned int operatortype)
Return the result of operator & @ parameter @ return.
void buildDetectorIDMapping ()
std::unique_ptr< SpecialWorkspace2D > clone () const
Returns a clone of the workspace.
std::unique_ptr< SpecialWorkspace2D > cloneEmpty () const
Returns a default-initialized clone of the workspace.
bool contains (const detid_t detectorID) const
virtual void copyFrom (std::shared_ptr< const SpecialWorkspace2D > sourcews)
Duplicate SpecialWorkspace2D.
std::set< detid_t > getDetectorIDs (const std::size_t workspaceIndex) const
Return the detector ID at the given workspace index (i.e., spectrum/histogram index)
double getValue (const detid_t detectorID) const
Return the special value (Y) in the workspace at the given detector ID.
double getValue (const detid_t detectorID, const double defaultValue) const
Return the special value (Y) in the workspace at the given detector ID, but returns a default value instead of throwing if detector is not found.
const std::string id () const override
Gets the name of the workspace type.
bool isDetectorIDMappingEmpty () const
SpecialWorkspace2D & operator= (const SpecialWorkspace2D &)=delete
void setValue (const detid_t detectorID, const double value, const double error=0.)
Set the special value (Y) in the workspace at the given detector ID.
void setValue (const std::set< detid_t > &detectorIDs, const double value, const double error=0.)
Set the special value (Y) in the workspace at the given detector IDs.
SpecialWorkspace2D ()=default
SpecialWorkspace2D (const API::MatrixWorkspace_const_sptr &parent)
Constructor, building from a MatrixWorkspace.
SpecialWorkspace2D (const Geometry::Instrument_const_sptr &inst, const bool includeMonitors=false)
Constructor, building from an instrument.
Public Member Functions inherited from Mantid::DataObjects::Workspace2D
std::size_t blocksize () const override
get the size of each vector
std::unique_ptr< Workspace2D > clone () const
Returns a clone of the workspace.
std::unique_ptr< Workspace2D > cloneEmpty () const
Returns a default-initialized clone of the workspace.
void generateHistogram (const std::size_t index, const MantidVec &X, MantidVec &Y, MantidVec &E, bool skipError=false) const override
Generate a new histogram by rebinning the existing histogram.
std::size_t getMaxNumberBins () const override
Returns the maximum number of bins in a workspace (works on ragged data).
std::size_t getNumberBins (const std::size_t &index) const override
Returns the number of bins for a given histogram index.
std::size_t getNumberHistograms () const override
Returns the histogram number.
const Histogram1D & getSpectrum (const size_t index) const override
Return const reference to Histogram1D at the given workspace index.
Histogram1D & getSpectrum (const size_t index) override
Return the underlying ISpectrum ptr at the given workspace index.
const std::string id () const override
Gets the name of the workspace type.
bool isRaggedWorkspace () const override
Returns true if the workspace is ragged (has differently sized spectra).
Workspace2D & operator= (const Workspace2D &other)=delete
void setImageE (const API::MantidImage &image, size_t start=0, bool parallelExecution=true) override
Copy the data from an image to this workspace's errors.
void setImageY (const API::MantidImage &image, size_t start=0, bool parallelExecution=true) override
Copy the data (Y's) from an image to this workspace.
void setImageYAndE (const API::MantidImage &imageY, const API::MantidImage &imageE, size_t start=0, bool loadAsRectImg=false, double scale_1=1.0, bool parallelExecution=true)
Copy the data from an image to this workspace's (Y's) and errors.
void setMonitorList (const std::vector< specnum_t > &mList)
sets the monitorWorkspace indexlist
std::size_t size () const override
get pseudo size
Workspace2D ()
Constructor.
~Workspace2D () override
Destructor.
Public Member Functions inherited from Mantid::API::HistoWorkspace
std::unique_ptr< HistoWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< HistoWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
HistoWorkspace ()
Public Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace_uptr clone () const
Returns a clone of the workspace.
MatrixWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const Indexing::IndexInfo & indexInfo () const
Returns a const reference to the IndexInfo object of the workspace.
void initialize (const Indexing::IndexInfo &indexInfo, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const HistogramData::Histogram &histogram)
void initialize (const std::size_t &NVectors, const std::size_t &XLength, const std::size_t &YLength)
Initialize the workspace.
MatrixWorkspace & operator= (const MatrixWorkspace &other)=delete
void setIndexInfo (const Indexing::IndexInfo &indexInfo)
Sets the IndexInfo object of the workspace.
~MatrixWorkspace () override
Delete.
std::shared_ptr< const Geometry::IDetector > getDetector (const size_t workspaceIndex) const
Get the effective detector for the given spectrum.
double detectorTwoTheta (const Geometry::IDetector &det) const
Returns the 2Theta scattering angle for a detector.
double detectorSignedTwoTheta (const Geometry::IDetector &det) const
Returns the signed 2Theta scattering angle for a detector.
virtual void updateSpectraUsing (const SpectrumDetectorMapping &map)
void rebuildSpectraMapping (const bool includeMonitors=true, const specnum_t specNumOffset=1)
Build the default spectra mapping, most likely wanted after an instrument update.
spec2index_map getSpectrumToWorkspaceIndexMap () const
Return a map where: KEY is the Spectrum # VALUE is the Workspace Index.
detid2index_map getDetectorIDToWorkspaceIndexMap (bool throwIfMultipleDets=false, bool ignoreIfNoValidDets=false) const
Return a map where: KEY is the DetectorID (pixel ID) VALUE is the Workspace Index.
virtual std::vector< size_t > getDetectorIDToWorkspaceIndexVector (detid_t &offset, bool throwIfMultipleDets=false) const
Return a vector where: The index into the vector = DetectorID (pixel ID) + offset The value at that index = the corresponding Workspace Index.
virtual std::vector< size_t > getSpectrumToWorkspaceIndexVector (specnum_t &offset) const
Return a vector where: The index into the vector = spectrum number + offset The value at that index = the corresponding Workspace Index.
std::vector< size_t > getIndicesFromSpectra (const std::vector< specnum_t > &spectraList) const
Converts a list of spectrum numbers to the corresponding workspace indices.
size_t getIndexFromSpectrumNumber (const specnum_t specNo) const
Given a spectrum number, find the corresponding workspace index.
std::vector< size_t > getIndicesFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding workspace indices.
std::vector< specnum_t > getSpectraFromDetectorIDs (const std::vector< detid_t > &detIdList) const
Converts a list of detector IDs to the corresponding spectrum numbers.
bool hasGroupedDetectors () const
Does the workspace has any grouped detectors?
size_t getMemorySize () const override
Get the footprint in memory in bytes.
virtual size_t getMemorySizeForXAxes () const
Returns the memory used (in bytes) by the X axes, handling ragged bins.
void setTitle (const std::string &) override
Sets MatrixWorkspace title.
const std::string getTitle () const override
Gets MatrixWorkspace title (same as Run object run_title property)
void setPlotType (const std::string &)
Sets MatrixWorkspace plot_type.
std::string getPlotType () const
Gets MatrixWorkspace plot_type.
void setMarkerStyle (const std::string &markerType)
Set the marker style for plotting.
std::string getMarkerStyle () const
Get the marker style for plotting.
void setMarkerSize (const float markerSize)
Set the size of the marker for plotting.
float getMarkerSize () const
Get the size of the marker for plotting.
virtual Types::Core::DateAndTime getFirstPulseTime () const
Return the time of the first pulse received, by accessing the run's sample logs to find the proton_charge.
Types::Core::DateAndTime getLastPulseTime () const
Return the time of the last pulse received, by accessing the run's sample logs to find the proton_charge.
std::size_t yIndexOfX (const double xValue, const std::size_t &index=0, const double tolerance=0.0) const
Returns the y index which corresponds to the X Value provided.
HistogramData::Histogram histogram (const size_t index) const
Returns the Histogram at the given workspace index.
template<typename... T>
void setHistogram (const size_t index, T &&...data) &
void convertToCounts (const size_t index)
void convertToFrequencies (const size_t index)
HistogramData::BinEdges binEdges (const size_t index) const
HistogramData::Points points (const size_t index) const
HistogramData::PointStandardDeviations pointStandardDeviations (const size_t index) const
template<typename... T>
void setBinEdges (const size_t index, T &&...data) &
template<typename... T>
void setPoints (const size_t index, T &&...data) &
template<typename... T>
void setPointVariances (const size_t index, T &&...data) &
template<typename... T>
void setPointStandardDeviations (const size_t index, T &&...data) &
HistogramData::Counts counts (const size_t index) const
HistogramData::CountVariances countVariances (const size_t index) const
HistogramData::CountStandardDeviations countStandardDeviations (const size_t index) const
HistogramData::Frequencies frequencies (const size_t index) const
HistogramData::FrequencyVariances frequencyVariances (const size_t index) const
HistogramData::FrequencyStandardDeviations frequencyStandardDeviations (const size_t index) const
template<typename... T>
void setCounts (const size_t index, T &&...data) &
template<typename... T>
void setCountVariances (const size_t index, T &&...data) &
template<typename... T>
void setCountStandardDeviations (const size_t index, T &&...data) &
template<typename... T>
void setFrequencies (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyVariances (const size_t index, T &&...data) &
template<typename... T>
void setFrequencyStandardDeviations (const size_t index, T &&...data) &
const HistogramData::HistogramX & x (const size_t index) const
const HistogramData::HistogramY & y (const size_t index) const
const HistogramData::HistogramE & e (const size_t index) const
const HistogramData::HistogramDx & dx (const size_t index) const
HistogramData::HistogramX & mutableX (const size_t index) &
HistogramData::HistogramDx & mutableDx (const size_t index) &
HistogramData::HistogramY & mutableY (const size_t index) &
HistogramData::HistogramE & mutableE (const size_t index) &
Kernel::cow_ptr< HistogramData::HistogramX > sharedX (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramY > sharedY (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramE > sharedE (const size_t index) const
Kernel::cow_ptr< HistogramData::HistogramDx > sharedDx (const size_t index) const
void setSharedX (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &x) &
void setSharedDx (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramDx > &dx) &
void setSharedY (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramY > &y) &
void setSharedE (const size_t index, const Kernel::cow_ptr< HistogramData::HistogramE > &e) &
void resizeHistogram (const size_t index, size_t n) &
size_t histogramSize (const size_t index) const
const MantidVec & readX (std::size_t const index) const
Deprecated, use x() instead.
const MantidVec & readY (std::size_t const index) const
Deprecated, use y() instead.
const MantidVec & readE (std::size_t const index) const
Deprecated, use e() instead.
const MantidVec & readDx (size_t const index) const
Deprecated, use dx() instead.
virtual MantidVec & dataX (const std::size_t index)
Deprecated, use mutableX() instead. Returns the x data.
virtual MantidVec & dataY (const std::size_t index)
Deprecated, use mutableY() instead. Returns the y data.
virtual MantidVec & dataE (const std::size_t index)
Deprecated, use mutableE() instead. Returns the error data.
virtual MantidVec & dataDx (const std::size_t index)
Deprecated, use mutableDx() instead. Returns the x error data.
virtual const MantidVec & dataX (const std::size_t index) const
Deprecated, use x() instead. Returns the x data const.
virtual const MantidVec & dataY (const std::size_t index) const
Deprecated, use y() instead. Returns the y data const.
virtual const MantidVec & dataE (const std::size_t index) const
Deprecated, use e() instead. Returns the error const.
virtual const MantidVec & dataDx (const std::size_t index) const
Deprecated, use dx() instead. Returns the error const.
virtual double getXMin () const
virtual double getXMax () const
virtual void getXMinMax (double &xmin, double &xmax) const
virtual Kernel::cow_ptr< HistogramData::HistogramX > refX (const std::size_t index) const
Deprecated, use sharedX() instead. Returns a pointer to the x data.
virtual void setX (const std::size_t index, const Kernel::cow_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual void setX (const std::size_t index, const std::shared_ptr< HistogramData::HistogramX > &X)
Deprecated, use setSharedX() instead.
virtual bool hasDx (const std::size_t index) const
Probes if DX (X Error) values were set on a particular spectrum.
virtual void getIntegratedSpectra (std::vector< double > &out, const double minX, const double maxX, const bool entireRange) const
Return a vector with the integrated counts for all spectra withing the given range.
std::vector< double > getIntegratedCountsForWorkspaceIndices (const std::vector< size_t > &workspaceIndices, const double minX, const double maxX, const bool entireRange) const
std::pair< size_t, double > getXIndex (size_t i, double x, bool isLeft=true, size_t start=0) const
Return an index in the X vector for an x-value close to a given value.
int axes () const
virtual Axis * getAxis (const std::size_t &axisIndex) const
Get a non owning pointer to a workspace axis.
void replaceAxis (const std::size_t &axisIndex, std::unique_ptr< Axis > newAxis)
Replaces one of the workspace's axes with the new one provided.
size_t numberOfAxis () const
Will return the number of Axis currently stored in the workspace it is not always safe to assume it is just 2.
virtual bool isCommonLogBins () const
Returns true if the workspace contains common X bins with log spacing.
virtual bool isHistogramData () const
Returns true if the workspace contains data in histogram form (as opposed to point-like)
virtual bool isCommonBins () const
Returns true if the workspace contains common X bins.
virtual bool isIntegerBins () const
Returns true if the workspace has common, integer X bins.
const std::string & YUnit () const
void setYUnit (const std::string &newUnit)
Sets a new unit for the data (Y axis) in the workspace.
std::string YUnitLabel (bool useLatex=false, bool plotAsDistribution=false) const
Returns a caption for the units of the data in the workspace.
void setYUnitLabel (const std::string &newLabel)
Sets a new caption for the data (Y axis) in the workspace.
bool isDistribution () const
Are the Y-values dimensioned?
void setDistribution (bool newValue)
Set the flag for whether the Y-values are dimensioned.
void maskBin (const size_t &workspaceIndex, const size_t &binIndex, const double &weight=1.0)
Called by the algorithm MaskBins to mask a single bin for the first time, algorithms that later propagate the the mask from an input to the output should call flagMasked() instead.
void flagMasked (const size_t &index, const size_t &binIndex, const double &weight=1.0)
Writes the masking weight to m_masks (doesn't alter y-values).
bool hasMaskedBins (const size_t &workspaceIndex) const
Does this spectrum contain any masked bins.
bool hasAnyMaskedBins () const
Does this workspace contain any masked bins.
const MaskList & maskedBins (const size_t &workspaceIndex) const
Returns the list of masked bins for a spectrum.
std::vector< size_t > maskedBinsIndices (const size_t &workspaceIndex) const
void setMaskedBins (const size_t workspaceIndex, const MaskList &maskedBins)
Set the list of masked bins for given workspaceIndex.
void setUnmaskedBins (const size_t workspaceIndex)
Removes the mask from an index.
virtual void setMonitorWorkspace (const std::shared_ptr< MatrixWorkspace > &monitorWS)
Sets the internal monitor workspace to the provided workspace.
std::shared_ptr< MatrixWorkspace > monitorWorkspace () const
Returns a pointer to the internal monitor workspace.
void loadInstrumentNexus (Nexus::File *file)
size_t getNumDims () const override
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const override
Get a dimension.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const override
Get a dimension.
uint64_t getNPoints () const override
Gets the number of points available on the workspace.
uint64_t getNEvents () const override
Get the number of points available on the workspace.
LinePlot getLinePlot (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const override
Generate a line plot through the matrix workspace.
signal_t getSignalAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
signal_t getSignalWithMaskAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const override
Get the signal at a coordinate in the workspace.
std::vector< std::unique_ptr< IMDIterator > > createIterators (size_t suggestedNumCores=1, Mantid::Geometry::MDImplicitFunction *function=nullptr) const override
Create iterators.
void setMDMasking (std::unique_ptr< Mantid::Geometry::MDImplicitFunction > maskingRegion) override
Apply masking.
void clearMDMasking () override
Clear exsting masking.
Mantid::Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const override
virtual bool hasOrientedLattice () const override
virtual std::pair< int64_t, int64_t > findY (double value, const std::pair< int64_t, int64_t > &idx={0, 0}) const
Find first index in Y equal to value.
std::pair< size_t, size_t > getImageStartEndXIndices (size_t i, double startX, double endX) const
Get start and end x indices for images.
MantidImage_sptr getImageY (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Ys.
MantidImage_sptr getImageE (size_t start=0, size_t stop=0, size_t width=0, double startX=EMPTY_DBL(), double endX=EMPTY_DBL()) const
Create an image of Es.
void invalidateCachedSpectrumNumbers ()
void invalidateCommonBinsFlag ()
Invalidates the commons bins flag.
Public Member Functions inherited from Mantid::API::IMDWorkspace
std::string changeQConvention ()
virtual void clearFileBacked (bool)
if a workspace was filebacked, this should clear file-based status, delete file-based information and close related files.
std::unique_ptr< IMDWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< IMDWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
std::unique_ptr< IMDIterator > createIterator (Mantid::Geometry::MDImplicitFunction *function=nullptr) const
Creates a single iterator and returns it.
virtual MDNormalization displayNormalization () const
virtual MDNormalization displayNormalizationHisto () const
const std::string & getConvention () const
signal_t getSignalAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates.
signal_t getSignalWithMaskAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates or 0 if masked.
IMDWorkspace ()
Default constructor.
virtual bool isMDHistoWorkspace () const
virtual ITableWorkspace_sptr makeBoxTable (size_t, size_t)
this is the method to build table workspace from any workspace.
IMDWorkspace & operator= (const IMDWorkspace &other)=delete
void setConvention (std::string convention)
Sets the convention of the workspace.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::MDGeometry
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (Nexus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instrument group if found there.
void loadSampleAndLogInfoNexus (Nexus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (Nexus::File *file, const Mantid::Nexus::NexusDescriptor &fileInfo, const std::string &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (Nexus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (Nexus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Protected Member Functions
void binaryAND (const std::shared_ptr< const SpecialWorkspace2D > &ws)
AND operator.
void binaryNOT ()
NOT operator.
void binaryOR (const std::shared_ptr< const SpecialWorkspace2D > &ws)
OR operator.
void binaryXOR (const std::shared_ptr< const SpecialWorkspace2D > &ws)
Excluded Or operator.
void init (const HistogramData::Histogram &histogram) override
void init (const size_t &NVectors, const size_t &XLength, const size_t &YLength) override
Sets the size of the workspace and initializes arrays to zero.
SpecialWorkspace2D (const SpecialWorkspace2D &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Return human-readable string.
Protected Member Functions inherited from Mantid::DataObjects::Workspace2D
void init (const HistogramData::Histogram &histogram) override
void init (const std::size_t &NVectors, const std::size_t &XLength, const std::size_t &YLength) override
Called by initialize()
Workspace2D (const Workspace2D &other)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::API::MatrixWorkspace
MatrixWorkspace (const MatrixWorkspace &other)
Protected copy constructor. May be used by childs for cloning.
MatrixWorkspace ()
Default constructor.
void updateCachedDetectorGrouping (const size_t index) const override
Update detector grouping for spectrum with given index.
std::string getDimensionIdFromAxis (const int &axisIndex) const
Getter for the dimension id based on the axis.
Protected Member Functions inherited from Mantid::API::IMDWorkspace
IMDWorkspace (const IMDWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void makeSinglePointWithNaN (std::vector< coord_t > &x, std::vector< signal_t > &y, std::vector< signal_t > &e) const
Make a single point with NaN as the signal and error This can be returned when there would otherwise be nothing to plot.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::MDGeometry
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
Protected Attributes
std::map< detid_t, std::size_t > detID_to_WI
Map with key = detector ID, and value = workspace index.
Protected Attributes inherited from Mantid::DataObjects::Workspace2D
std::vector< std::unique_ptr< Histogram1D > > data
A vector that holds the 1D histograms.
std::vector< specnum_t > m_monitorList
a vector holding workspace index of monitors in the workspace
Protected Attributes inherited from Mantid::API::MatrixWorkspace
std::vector< std::unique_ptr< Axis > > m_axes
A vector of pointers to the axes for this workspace.
Protected Attributes inherited from Mantid::API::MDGeometry
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Private Member Functions
SpecialWorkspace2D * doClone () const override
Virtual clone method. Not implemented to force implementation in children.
SpecialWorkspace2D * doCloneEmpty () const override
Virtual cloneEmpty method.
bool isCompatible (const std::shared_ptr< const SpecialWorkspace2D > &ws)
Additional Inherited Members
Public Types inherited from Mantid::API::MatrixWorkspace
using MaskList = std::map< size_t, double >
Masked bins for each spectrum are stored as a set of pairs containing <bin index, weight>
Static Public Attributes inherited from Mantid::API::MatrixWorkspace
static const std::string xDimensionId = "xDimension"
Dimension id for x-dimension.
static const std::string yDimensionId = "yDimension"
Dimensin id for y-dimension.
Detailed Description
Definition at line 31 of file SpecialWorkspace2D.h.
Constructor & Destructor Documentation
SpecialWorkspace2D() [1/4]
Mantid::DataObjects::SpecialWorkspace2D::SpecialWorkspace2D () default
SpecialWorkspace2D() [2/4]
Mantid::DataObjects::SpecialWorkspace2D::SpecialWorkspace2D (const Geometry::Instrument_const_sptr & inst, const bool includeMonitors = false)
Constructor, building from an instrument.
Parameters
inst :: input instrument that is the base for this workspace
includeMonitors :: If false the monitors are not included
Definition at line 33 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::rebuildSpectraMapping().
SpecialWorkspace2D() [3/4]
Mantid::DataObjects::SpecialWorkspace2D::SpecialWorkspace2D (const API::MatrixWorkspace_const_sptr & parent)
Constructor, building from a MatrixWorkspace.
Parameters
parent :: input workspace that is the base for this workspace
Definition at line 52 of file SpecialWorkspace2D.cpp.
References buildDetectorIDMapping(), Mantid::API::MatrixWorkspace::initialize(), and Mantid::Kernel::SingletonHolder< T >::Instance().
SpecialWorkspace2D() [4/4]
Mantid::DataObjects::SpecialWorkspace2D::SpecialWorkspace2D (const SpecialWorkspace2D &) protected default
Protected copy constructor. May be used by childs for cloning.
References Mantid::Kernel::toString().
Member Function Documentation
binaryAND()
void Mantid::DataObjects::SpecialWorkspace2D::binaryAND (const std::shared_ptr< const SpecialWorkspace2D > & ws) protected
AND operator.
Definition at line 249 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by binaryOperation().
binaryNOT()
void Mantid::DataObjects::SpecialWorkspace2D::binaryNOT () protected
NOT operator.
Definition at line 309 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by binaryOperation().
binaryOperation() [1/2]
void Mantid::DataObjects::SpecialWorkspace2D::binaryOperation (const std::shared_ptr< const SpecialWorkspace2D > & ws, const unsigned int operatortype)
Return the result of operator & @ parameter @ return.
Definition at line 204 of file SpecialWorkspace2D.cpp.
References Mantid::DataObjects::BinaryOperator::AND, binaryAND(), binaryOR(), binaryXOR(), isCompatible(), Mantid::DataObjects::BinaryOperator::OR, and Mantid::DataObjects::BinaryOperator::XOR.
binaryOperation() [2/2]
void Mantid::DataObjects::SpecialWorkspace2D::binaryOperation (const unsigned int operatortype)
Return the result of operator & @ parameter @ return.
Definition at line 233 of file SpecialWorkspace2D.cpp.
References binaryNOT(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, and Mantid::DataObjects::BinaryOperator::NOT.
binaryOR()
void Mantid::DataObjects::SpecialWorkspace2D::binaryOR (const std::shared_ptr< const SpecialWorkspace2D > & ws) protected
OR operator.
Definition at line 266 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by binaryOperation().
binaryXOR()
void Mantid::DataObjects::SpecialWorkspace2D::binaryXOR (const std::shared_ptr< const SpecialWorkspace2D > & ws) protected
Excluded Or operator.
Definition at line 291 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by binaryOperation().
buildDetectorIDMapping()
void Mantid::DataObjects::SpecialWorkspace2D::buildDetectorIDMapping ()
Definition at line 91 of file SpecialWorkspace2D.cpp.
References detID_to_WI, getDetectorIDs(), and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by SpecialWorkspace2D().
clone()
std::unique_ptr< SpecialWorkspace2D > Mantid::DataObjects::SpecialWorkspace2D::clone () const inline
Returns a clone of the workspace.
Definition at line 38 of file SpecialWorkspace2D.h.
cloneEmpty()
std::unique_ptr< SpecialWorkspace2D > Mantid::DataObjects::SpecialWorkspace2D::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 40 of file SpecialWorkspace2D.h.
References workspace.
contains()
bool Mantid::DataObjects::SpecialWorkspace2D::contains (const detid_t detectorID) const
Definition at line 101 of file SpecialWorkspace2D.cpp.
References detID_to_WI.
Referenced by Mantid::DataObjects::MaskWorkspace::containsDetID(), and Mantid::DataObjects::MaskWorkspace::isMasked().
copyFrom()
void Mantid::DataObjects::SpecialWorkspace2D::copyFrom (std::shared_ptr< const SpecialWorkspace2D > sourcews) virtual
Duplicate SpecialWorkspace2D.
Reimplemented in Mantid::DataObjects::MaskWorkspace.
Definition at line 361 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataE(), Mantid::API::MatrixWorkspace::dataX(), Mantid::API::MatrixWorkspace::dataY(), detID_to_WI, and Mantid::DataObjects::Workspace2D::getNumberHistograms().
Referenced by Mantid::DataObjects::MaskWorkspace::copyFrom().
doClone()
SpecialWorkspace2D * Mantid::DataObjects::SpecialWorkspace2D::doClone () const inline override private virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::HistoWorkspace.
Definition at line 67 of file SpecialWorkspace2D.h.
doCloneEmpty()
SpecialWorkspace2D * Mantid::DataObjects::SpecialWorkspace2D::doCloneEmpty () const inline override private virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::HistoWorkspace.
Definition at line 68 of file SpecialWorkspace2D.h.
getDetectorIDs()
set< detid_t > Mantid::DataObjects::SpecialWorkspace2D::getDetectorIDs (const std::size_t workspaceIndex) const
Return the detector ID at the given workspace index (i.e., spectrum/histogram index)
Parameters
workspaceIndex
Returns
Definition at line 193 of file SpecialWorkspace2D.cpp.
References Mantid::API::ISpectrum::getDetectorIDs(), Mantid::DataObjects::Workspace2D::getNumberHistograms(), and Mantid::DataObjects::Workspace2D::getSpectrum().
Referenced by buildDetectorIDMapping(), Mantid::DataObjects::GroupingWorkspace::getDetectorIDsOfGroup(), Mantid::DataObjects::MaskWorkspace::getMaskedDetectors(), Mantid::DataObjects::MaskWorkspace::getNumberMasked(), Mantid::DataObjects::GroupingWorkspace::makeDetectorIDToGroupMap(), and Mantid::DataObjects::GroupingWorkspace::makeDetectorIDToGroupVector().
getValue() [1/2]
double Mantid::DataObjects::SpecialWorkspace2D::getValue (const detid_t detectorID) const
Return the special value (Y) in the workspace at the given detector ID.
Parameters
detectorID :: detector ID to look up
Returns
the Y value for that detector ID.
Exceptions
std::invalid_argument if the detector ID was not found
Definition at line 113 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), detID_to_WI, and Mantid::API::Workspace::getName().
Referenced by Mantid::DataObjects::MaskWorkspace::isMasked().
getValue() [2/2]
double Mantid::DataObjects::SpecialWorkspace2D::getValue (const detid_t detectorID, const double defaultValue) const
Return the special value (Y) in the workspace at the given detector ID, but returns a default value instead of throwing if detector is not found.
Parameters
detectorID :: detector ID to look up
defaultValue :: value returned if the ID is not found.
Returns
the Y value for that detector ID.
Definition at line 134 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataY(), Mantid::Kernel::Logger::debug(), detID_to_WI, Mantid::API::g_log, and Mantid::DataObjects::Workspace2D::getNumberHistograms().
id()
const std::string Mantid::DataObjects::SpecialWorkspace2D::id () const inline override virtual
Gets the name of the workspace type.
Returns
Standard string name
Implements Mantid::Kernel::DataItem.
Definition at line 48 of file SpecialWorkspace2D.h.
init() [1/2]
void Mantid::DataObjects::SpecialWorkspace2D::init (const HistogramData::Histogram & histogram) override protected virtual
Implements Mantid::API::MatrixWorkspace.
Definition at line 73 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::histogram(), and Mantid::DataObjects::Workspace2D::init().
init() [2/2]
void Mantid::DataObjects::SpecialWorkspace2D::init (const size_t & NVectors, const size_t & XLength, const size_t & YLength) override protected
Sets the size of the workspace and initializes arrays to zero.
Parameters
NVectors :: The number of vectors/histograms/detectors in the workspace
XLength :: Must be 1
YLength :: Must be 1
Definition at line 66 of file SpecialWorkspace2D.cpp.
References Mantid::DataObjects::Workspace2D::init().
Referenced by Mantid::DataObjects::MaskWorkspace::MaskWorkspace().
isCompatible()
bool Mantid::DataObjects::SpecialWorkspace2D::isCompatible (const std::shared_ptr< const SpecialWorkspace2D > & ws) private
Definition at line 326 of file SpecialWorkspace2D.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::API::ISpectrum::getDetectorIDs(), Mantid::DataObjects::Workspace2D::getNumberHistograms(), and Mantid::DataObjects::Workspace2D::getSpectrum().
Referenced by binaryOperation().
isDetectorIDMappingEmpty()
bool Mantid::DataObjects::SpecialWorkspace2D::isDetectorIDMappingEmpty () const inline
Definition at line 50 of file SpecialWorkspace2D.h.
operator=()
SpecialWorkspace2D & Mantid::DataObjects::SpecialWorkspace2D::operator= (const SpecialWorkspace2D &) delete
setValue() [1/2]
void Mantid::DataObjects::SpecialWorkspace2D::setValue (const detid_t detectorID, const double value, const double error = 0.)
Set the special value (Y) in the workspace at the given detector ID.
Parameters
detectorID :: detector ID to look up
value :: holder for the Y value
error :: the Y value for that detector ID.
Exceptions
std::invalid_argument if the detector ID was not found
Definition at line 158 of file SpecialWorkspace2D.cpp.
References Mantid::API::MatrixWorkspace::dataE(), Mantid::API::MatrixWorkspace::dataY(), detID_to_WI, error, and value.
Referenced by Mantid::DataObjects::MaskWorkspace::setMasked(), and setValue().
setValue() [2/2]
void Mantid::DataObjects::SpecialWorkspace2D::setValue (const std::set< detid_t > & detectorIDs, const double value, const double error = 0.)
Set the special value (Y) in the workspace at the given detector IDs.
This is a convenience function that just calls setValue(const detid_t, double, double).
Parameters
detectorIDs :: detector IDs to look up
value :: holder for the Y value
error :: the Y value for the detector IDs.
Exceptions
std::invalid_argument if any of the detector IDs are not found
Definition at line 180 of file SpecialWorkspace2D.cpp.
References error, setValue(), and value.
toString()
const std::string Mantid::DataObjects::SpecialWorkspace2D::toString () const override protected virtual
Return human-readable string.
Returns
A string containing the workspace description
Reimplemented from Mantid::API::MatrixWorkspace.
Definition at line 84 of file SpecialWorkspace2D.cpp.
References Mantid::DataObjects::Workspace2D::getNumberHistograms(), and Mantid::API::MatrixWorkspace::getTitle().
Referenced by Mantid::DataObjects::MaskWorkspace::toString().
Member Data Documentation
detID_to_WI
std::map<detid_t, std::size_t> Mantid::DataObjects::SpecialWorkspace2D::detID_to_WI protected
Map with key = detector ID, and value = workspace index.
Definition at line 87 of file SpecialWorkspace2D.h.
Referenced by buildDetectorIDMapping(), contains(), copyFrom(), getValue(), getValue(), and setValue().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/SpecialWorkspace2D.h
Framework/DataObjects/src/SpecialWorkspace2D.cpp