Mantid: MantidQt::MantidWidgets::MantidDisplayBase Class Reference
MantidQt::MantidWidgets::MantidDisplayBase Class Reference abstract
#include <MantidDisplayBase.h>
Public Member Functions
virtual Mantid::API::IAlgorithm_sptr createAlgorithm (const QString &algName, int version=-1)=0
virtual Table * createDetectorTable (const QString &wsName, const std::vector< int > &indices, bool include_data=false)=0
virtual MantidWSIndexDialog * createWorkspaceIndexDialog (int flags, const QStringList &wsNames, bool showWaterfall, bool showPlotAll, bool showTiledOpt, bool isAdvanced=false)=0
virtual void deleteWorkspaces (const QStringList &wsNames=QStringList())=0
virtual void disableSaveNexus ()=0
virtual void drawColorFillPlots (const QStringList &wsNames, GraphOptions::CurveType curveType=GraphOptions::ColorMap)=0
virtual void enableSaveNexus (const QString &wsName)=0
virtual void executeAlgorithm (Mantid::API::IAlgorithm_sptr alg)=0
virtual bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=false)=0
virtual QWidget * getParent ()=0
virtual Mantid::API::Workspace_const_sptr getWorkspace (const QString &workspaceName)=0
virtual void importBoxDataTable ()=0
virtual MantidMatrix * importMatrixWorkspace (const Mantid::API::MatrixWorkspace_sptr workspace, int lower=-1, int upper=-1, bool showDlg=true)=0
virtual void importTransposed ()=0
virtual void importWorkspace ()=0
virtual void importWorkspace (const QString &wsName, bool showDlg=true, bool makeVisible=true)=0
virtual MultiLayer * plot1D (const QMultiMap< QString, std::set< int > > &toPlot, bool spectrumPlot, MantidQt::DistributionFlag distr=MantidQt::DistributionDefault, bool errs=false, MultiLayer *plotWindow=nullptr, bool clearWindow=false, bool waterfallPlot=false, const QString &log="", const std::set< double > &customLogValues=std::set< double >())=0
virtual void plotContour (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames)=0
virtual MultiLayer * plotSubplots (const QMultiMap< QString, std::set< int > > &toPlot, MantidQt::DistributionFlag distr=MantidQt::DistributionDefault, bool errs=false, MultiLayer *plotWindow=nullptr)=0
virtual void plotSurface (bool accepted, int plotIndex, const QString &axisName, const QString &logName, const std::set< double > &customLogValues, const QList< QString > &workspaceNames)=0
virtual void renameWorkspace (QStringList=QStringList())=0
virtual void showAlgorithmDialog (const QString &algName, int version=-1)=0
virtual void showAlgorithmDialog (const QString &algName, QHash< QString, QString > paramList, Mantid::API::AlgorithmObserver *obs=nullptr, int version=-1)=0
virtual void showAlgorithmHistory ()=0
virtual void showCritical (const QString &)
virtual void showListData ()=0
virtual void showLogFileWindow ()=0
virtual void showMantidInstrumentSelected ()=0
virtual void showMDPlot ()=0
virtual void showSampleMaterialWindow ()=0
virtual void showSliceViewer ()=0
virtual void showSpectrumViewer ()=0
virtual void updateProject ()=0
virtual void updateRecentFilesList (const QString &fname)=0
virtual ~MantidDisplayBase ()=default
Detailed Description
Definition at line 43 of file MantidDisplayBase.h.
Constructor & Destructor Documentation
~MantidDisplayBase()
virtual MantidQt::MantidWidgets::MantidDisplayBase::~MantidDisplayBase () virtual default
Member Function Documentation
createAlgorithm()
virtual Mantid::API::IAlgorithm_sptr MantidQt::MantidWidgets::MantidDisplayBase::createAlgorithm (const QString & algName, int version = -1) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
Referenced by MantidQt::MantidWidgets::MantidTreeWidget::dropEvent(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::saveToProgram().
createDetectorTable()
virtual Table * MantidQt::MantidWidgets::MantidDisplayBase::createDetectorTable (const QString & wsName, const std::vector< int > & indices, bool include_data = false) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showDetectorsTable().
createWorkspaceIndexDialog()
virtual MantidWSIndexDialog * MantidQt::MantidWidgets::MantidDisplayBase::createWorkspaceIndexDialog (int flags, const QStringList & wsNames, bool showWaterfall, bool showPlotAll, bool showTiledOpt, bool isAdvanced = false) pure virtual
Referenced by MantidQt::MantidWidgets::MantidTreeWidget::chooseSpectrumFromSelected().
deleteWorkspaces()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::deleteWorkspaces (const QStringList & wsNames = QStringList()) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::deleteWorkspaces().
disableSaveNexus()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::disableSaveNexus () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::onTreeSelectionChanged().
drawColorFillPlots()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::drawColorFillPlots (const QStringList & wsNames, GraphOptions::CurveType curveType = GraphOptions::ColorMap) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showColourFillPlot().
enableSaveNexus()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::enableSaveNexus (const QString & wsName) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::onTreeSelectionChanged(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::workspaceSelected().
executeAlgorithm()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::executeAlgorithm (Mantid::API::IAlgorithm_sptr alg) pure virtual
executeAlgorithmAsync()
virtual bool MantidQt::MantidWidgets::MantidDisplayBase::executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait = false) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
Referenced by MantidQt::MantidWidgets::MantidTreeWidget::dropEvent(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::executeAlgorithmAsync().
getParent()
virtual QWidget * MantidQt::MantidWidgets::MantidDisplayBase::getParent () pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
getWorkspace()
virtual Mantid::API::Workspace_const_sptr MantidQt::MantidWidgets::MantidDisplayBase::getWorkspace (const QString & workspaceName) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
importBoxDataTable()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::importBoxDataTable () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showBoxDataTable().
importMatrixWorkspace()
virtual MantidMatrix * MantidQt::MantidWidgets::MantidDisplayBase::importMatrixWorkspace (const Mantid::API::MatrixWorkspace_sptr workspace, int lower = -1, int upper = -1, bool showDlg = true) pure virtual
importTransposed()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::importTransposed () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showTransposed().
importWorkspace() [1/2]
virtual void MantidQt::MantidWidgets::MantidDisplayBase::importWorkspace () pure virtual
Referenced by MantidQt::MantidWidgets::MantidTreeWidget::MantidTreeWidget(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::showWorkspaceData().
importWorkspace() [2/2]
virtual void MantidQt::MantidWidgets::MantidDisplayBase::importWorkspace (const QString & wsName, bool showDlg = true, bool makeVisible = true) pure virtual
plot1D()
virtual MultiLayer * MantidQt::MantidWidgets::MantidDisplayBase::plot1D (const QMultiMap< QString, std::set< int > > & toPlot, bool spectrumPlot, MantidQt::DistributionFlag distr = MantidQt::DistributionDefault, bool errs = false, MultiLayer * plotWindow = nullptr, bool clearWindow = false, bool waterfallPlot = false, const QString & log = "", const std::set< double > & customLogValues = std::set< double >()) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::plotSpectrum().
plotContour()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::plotContour (bool accepted, int plotIndex, const QString & axisName, const QString & logName, const std::set< double > & customLogValues, const QList< QString > & workspaceNames) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::plotSpectrum().
plotSubplots()
virtual MultiLayer * MantidQt::MantidWidgets::MantidDisplayBase::plotSubplots (const QMultiMap< QString, std::set< int > > & toPlot, MantidQt::DistributionFlag distr = MantidQt::DistributionDefault, bool errs = false, MultiLayer * plotWindow = nullptr) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::plotSpectrum().
plotSurface()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::plotSurface (bool accepted, int plotIndex, const QString & axisName, const QString & logName, const std::set< double > & customLogValues, const QList< QString > & workspaceNames) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::plotSpectrum().
renameWorkspace()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::renameWorkspace (QStringList = QStringList()) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showRenameDialog().
showAlgorithmDialog() [1/2]
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmDialog (const QString & algName, int version = -1) pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::convertMDHistoToMatrixWorkspace(), MantidQt::MantidWidgets::WorkspaceTreeWidget::convertToMatrixWorkspace(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::saveWorkspace().
showAlgorithmDialog() [2/2]
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmDialog (const QString & algName, QHash< QString, QString > paramList, Mantid::API::AlgorithmObserver * obs = nullptr, int version = -1) pure virtual
showAlgorithmHistory()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showAlgorithmHistory () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showAlgorithmHistory().
showCritical()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showCritical (const QString &) inline virtual
Definition at line 104 of file MantidDisplayBase.h.
showListData()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showListData () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showListData().
showLogFileWindow()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showLogFileWindow () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showLogs().
showMantidInstrumentSelected()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showMantidInstrumentSelected () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showInstrumentView().
showMDPlot()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showMDPlot () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showMDPlot().
showSampleMaterialWindow()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showSampleMaterialWindow () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showSampleMaterialWindow().
showSliceViewer()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showSliceViewer () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showSliceViewer().
showSpectrumViewer()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::showSpectrumViewer () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::showSpectrumViewer().
updateProject()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::updateProject () pure virtual
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::handleClearView(), and MantidQt::MantidWidgets::WorkspaceTreeWidget::handleUpdateTree().
updateRecentFilesList()
virtual void MantidQt::MantidWidgets::MantidDisplayBase::updateRecentFilesList (const QString & fname) pure virtual
Implemented in MantidQt::MantidWidgets::MantidTreeModel.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::onLoadAccept().
The documentation for this class was generated from the following file:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidDisplayBase.h