Mantid: Mantid::DataHandling::LoadMuonNexus1 Class Reference
Mantid::DataHandling::LoadMuonNexus1 Class Reference
#include <LoadMuonNexus1.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
int confidence (Kernel::NexusDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadMuonNexus1 ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::DataHandling::LoadMuonNexus
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
int confidence (Kernel::NexusDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadMuonNexus ()
Default constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::NexusDescriptor >
virtual int confidence (Kernel::NexusDescriptor &descriptor) const=0
Returns a confidence value that this algorithm can load a file.
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Protected Member Functions
void exec () override
Overwrites Algorithm method.
Protected Member Functions inherited from Mantid::DataHandling::LoadMuonNexus
void addToSampleLog (const std::string &logName, const int logNumber, DataObjects::Workspace2D_sptr &ws)
Function to add a single int as a sample log to a workspace.
void addToSampleLog (const std::string &logName, const std::string &log, DataObjects::Workspace2D_sptr &ws)
Fucntion to add a single string as a sample log to a workspace.
void checkOptionalProperties ()
Validates the optional 'spectra to read' properties, if they have been set.
Mantid::API::Algorithm_sptr createSampleLogAlgorithm (DataObjects::Workspace2D_sptr &ws)
Create Algorithm to add a sample log to a workspace.
void runLoadInstrument (const DataObjects::Workspace2D_sptr &)
Run the Child Algorithm LoadInstrument.
virtual void runLoadInstrumentFromNexus (DataObjects::Workspace2D_sptr)
Protected Member Functions inherited from Mantid::API::ParallelAlgorithm
Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const override
Get correct execution mode based on input storage modes for an MPI run.
~ParallelAlgorithm ()=default
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Private Member Functions
void addGoodFrames (const DataObjects::Workspace2D_sptr &localWorkspace, int64_t period, int nperiods)
void addPeriodLog (const DataObjects::Workspace2D_sptr &localWorkspace, int64_t period)
Add the 'period i' log to a workspace.
DataObjects::TableWorkspace_sptr createDeadTimeTable (std::vector< int > specToLoad, std::vector< double > deadTimes)
Creates Dead Time Table using all the data between begin and end.
DataObjects::TableWorkspace_sptr createDetectorGroupingTable (std::vector< int > specToLoad, std::vector< int > grouping)
Creates Detector Grouping Table using all the data from the range.
void loadData (size_t hist, specnum_t &i, specnum_t specNo, MuonNexusReader &nxload, const int64_t lengthIn, const DataObjects::Workspace2D_sptr &localWorkspace)
Load in a single spectrum taken from a NeXus file.
void loadDeadTimes (Mantid::NeXus::NXRoot &root)
Loads dead time table for the detector.
API::Workspace_sptr loadDetectorGrouping (Mantid::NeXus::NXRoot &root, const Mantid::Geometry::Instrument_const_sptr &inst)
Loads detector grouping information.
void loadRunDetails (const DataObjects::Workspace2D_sptr &localWorkspace)
Log the run details from the file.
void runLoadLog (const DataObjects::Workspace2D_sptr &)
Run the LoadLog Child Algorithm.
void runLoadMappingTable (DataObjects::Workspace2D_sptr)
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::DataHandling::LoadMuonNexus
std::string m_entry_name
The first top-level entry name in the file.
int64_t m_entrynumber
The number of the input entry.
std::string m_filename
The name and path of the input file.
std::vector< detid_t > m_groupings
The group which each detector belongs to in order.
std::string m_instrument_name
The instrument name from Nexus.
bool m_interval
Have the spectrum_min/max properties been set?
bool m_list
Has the spectrum_list property been set?
int64_t m_numberOfPeriods
The number of periods in the raw file.
specnum_t m_numberOfSpectra
The number of spectra in the raw file.
std::string m_samplename
The sample name read from Nexus.
std::vector< specnum_t > m_spec_list
The value of the spectrum_list property.
specnum_t m_spec_max
The value of the spectrum_max property.
specnum_t m_spec_min
The value of the spectrum_min property.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Definition at line 55 of file LoadMuonNexus1.h.
Constructor & Destructor Documentation
LoadMuonNexus1()
Mantid::DataHandling::LoadMuonNexus1::LoadMuonNexus1 ()
Default constructor.
Empty default constructor.
Definition at line 61 of file LoadMuonNexus1.cpp.
Member Function Documentation
addGoodFrames()
void Mantid::DataHandling::LoadMuonNexus1::addGoodFrames (const DataObjects::Workspace2D_sptr & localWorkspace, int64_t period, int nperiods) private
Definition at line 795 of file LoadMuonNexus1.cpp.
References error, Mantid::API::g_log, Mantid::DataHandling::LoadMuonNexus::m_filename, and Mantid::Kernel::Logger::warning().
Referenced by exec().
addPeriodLog()
void Mantid::DataHandling::LoadMuonNexus1::addPeriodLog (const DataObjects::Workspace2D_sptr & localWorkspace, int64_t period) private
Add the 'period i' log to a workspace.
Parameters
localWorkspace A workspace to add the log to.
period A period for this workspace.
Definition at line 784 of file LoadMuonNexus1.cpp.
References Mantid::DataHandling::ISISRunLogs::addPeriodLog(), and Mantid::DataHandling::ISISRunLogs::addPeriodLogs().
Referenced by exec().
category()
const std::string Mantid::DataHandling::LoadMuonNexus1::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::DataHandling::LoadMuonNexus.
Definition at line 72 of file LoadMuonNexus1.h.
confidence()
int Mantid::DataHandling::LoadMuonNexus1::confidence (Kernel::NexusDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Reimplemented from Mantid::DataHandling::LoadMuonNexus.
Definition at line 880 of file LoadMuonNexus1.cpp.
References Mantid::Kernel::NexusDescriptor::data(), Mantid::Kernel::NexusDescriptor::firstEntryNameType(), Mantid::Kernel::NexusDescriptor::pathExists(), and version().
Referenced by Mantid::DataHandling::LoadMuonNexus2::exec().
createDeadTimeTable()
TableWorkspace_sptr Mantid::DataHandling::LoadMuonNexus1::createDeadTimeTable (std::vector< int > specToLoad, std::vector< double > deadTimes) private
Creates Dead Time Table using all the data between begin and end.
Parameters
specToLoad :: vector containing the spectrum numbers to load
deadTimes :: vector containing the corresponding dead times
Returns
Dead Time Table create using the data
Definition at line 604 of file LoadMuonNexus1.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by loadDeadTimes().
createDetectorGroupingTable()
TableWorkspace_sptr Mantid::DataHandling::LoadMuonNexus1::createDetectorGroupingTable (std::vector< int > specToLoad, std::vector< int > grouping) private
Creates Detector Grouping Table using all the data from the range.
Creates Detector Grouping Table using all the data between begin and end.
Parameters
specToLoad :: Vector containing the spectrum list to load
grouping :: Vector containing corresponding grouping
Returns
Detector Grouping Table create using the data
Definition at line 626 of file LoadMuonNexus1.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Referenced by loadDetectorGrouping().
exec()
void Mantid::DataHandling::LoadMuonNexus1::exec () override protected virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Exceptions
Exception::FileError If the Nexus file cannot be found/opened
std::invalid_argument If the optional properties are set to invalid values
Implements Mantid::API::Algorithm.
Definition at line 70 of file LoadMuonNexus1.cpp.
References addGoodFrames(), addPeriodLog(), Mantid::DataHandling::LoadMuonNexus::addToSampleLog(), Mantid::NeXus::NXObject::attributes, Mantid::DataHandling::LoadMuonNexus::checkOptionalProperties(), Mantid::DataObjects::create(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::DataHandling::createTimeZeroTable(), Mantid::API::Algorithm::existsProperty(), Mantid::API::g_log, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::NeXus::NXClass::getFloat(), MuonNexusReader::getInstrumentName(), Mantid::NeXus::NXClass::getInt(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::NeXus::NXClass::getString(), Mantid::Kernel::SingletonHolder< T >::Instance(), loadData(), loadDeadTimes(), loadDetectorGrouping(), loadRunDetails(), Mantid::DataHandling::LoadMuonNexus::m_entrynumber, Mantid::DataHandling::LoadMuonNexus::m_filename, MuonNexusReader::m_framesPeriodsRaw, MuonNexusReader::m_framesPeriodsRequested, Mantid::DataHandling::LoadMuonNexus::m_instrument_name, Mantid::DataHandling::LoadMuonNexus::m_interval, Mantid::DataHandling::LoadMuonNexus::m_list, Mantid::DataHandling::LoadMuonNexus::m_numberOfPeriods, Mantid::DataHandling::LoadMuonNexus::m_numberOfSpectra, MuonNexusReader::m_numPeriodSequences, MuonNexusReader::m_periodNames, MuonNexusReader::m_periodsCounts, MuonNexusReader::m_periodsOutput, MuonNexusReader::m_periodTypes, Mantid::DataHandling::LoadMuonNexus::m_spec_list, Mantid::DataHandling::LoadMuonNexus::m_spec_max, Mantid::DataHandling::LoadMuonNexus::m_spec_min, Mantid::Kernel::Units::Symbol::Microsecond, Mantid::NeXus::NXRoot::openEntry(), Mantid::NeXus::NXClass::openNXInt(), Mantid::API::Algorithm::progress(), MuonNexusReader::readFromFile(), Mantid::DataHandling::LoadMuonNexus::runLoadInstrument(), runLoadLog(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::NeXus::NXInfo::stat, MuonNexusReader::t_nper, MuonNexusReader::t_nsp1, MuonNexusReader::t_ntc1, std::to_string(), Mantid::NeXus::NXInfo::type, and Mantid::Kernel::Logger::warning().
loadData()
void Mantid::DataHandling::LoadMuonNexus1::loadData (size_t hist, specnum_t & i, specnum_t specNo, MuonNexusReader & nxload, const int64_t lengthIn, const DataObjects::Workspace2D_sptr & localWorkspace) private
Load in a single spectrum taken from a NeXus file.
Parameters
hist :: The workspace index
i :: The spectrum number
specNo :: The spectrum number
nxload :: A reference to the MuonNeXusReader object
lengthIn :: The number of elements in a spectrum
localWorkspace :: A pointer to the workspace in which the data will be stored
Definition at line 661 of file LoadMuonNexus1.cpp.
References MuonNexusReader::getTimeChannels(), and MuonNexusReader::m_counts.
Referenced by exec().
loadDeadTimes()
void Mantid::DataHandling::LoadMuonNexus1::loadDeadTimes (Mantid::NeXus::NXRoot & root) private
Loads dead time table for the detector.
Parameters
root :: Root entry of the Nexus to read dead times from
Definition at line 367 of file LoadMuonNexus1.cpp.
References createDeadTimeTable(), Mantid::NeXus::NXDataSet::dim0(), Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::API::Algorithm::getPropertyValue(), index, Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::DataHandling::LoadMuonNexus::m_filename, Mantid::DataHandling::LoadMuonNexus::m_interval, Mantid::DataHandling::LoadMuonNexus::m_list, Mantid::DataHandling::LoadMuonNexus::m_numberOfPeriods, Mantid::DataHandling::LoadMuonNexus::m_numberOfSpectra, Mantid::DataHandling::LoadMuonNexus::m_spec_list, Mantid::DataHandling::LoadMuonNexus::m_spec_max, Mantid::DataHandling::LoadMuonNexus::m_spec_min, Mantid::NeXus::NXRoot::openEntry(), Mantid::NeXus::NXClass::openNXFloat(), Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::NeXus::NXInfo::stat.
Referenced by exec().
loadDetectorGrouping()
Workspace_sptr Mantid::DataHandling::LoadMuonNexus1::loadDetectorGrouping (Mantid::NeXus::NXRoot & root, const Mantid::Geometry::Instrument_const_sptr & inst) private
Loads detector grouping information.
Loads detector grouping.
If no entry in NeXus file for grouping, load it from the IDF.
Parameters
root :: Root entry of the Nexus file to read from
inst :: Pointer to instrument (to use if IDF needed)
Returns
:: Grouping table - or tables, if per period
Definition at line 468 of file LoadMuonNexus1.cpp.
References createDetectorGroupingTable(), Mantid::NeXus::NXDataSet::dim0(), Mantid::API::g_log, Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::API::GroupingLoader::getDummyGrouping(), Mantid::API::GroupingLoader::getGroupingFromIDF(), Mantid::API::Algorithm::getProperty(), index, Mantid::NeXus::NXDataSetTyped< T >::load(), Mantid::DataHandling::LoadMuonNexus::m_entrynumber, Mantid::DataHandling::LoadMuonNexus::m_filename, Mantid::DataHandling::LoadMuonNexus::m_interval, Mantid::DataHandling::LoadMuonNexus::m_list, Mantid::DataHandling::LoadMuonNexus::m_numberOfPeriods, Mantid::DataHandling::LoadMuonNexus::m_numberOfSpectra, Mantid::DataHandling::LoadMuonNexus::m_spec_list, Mantid::DataHandling::LoadMuonNexus::m_spec_max, Mantid::DataHandling::LoadMuonNexus::m_spec_min, Mantid::NeXus::NXRoot::openEntry(), Mantid::NeXus::NXClass::openNXInt(), Mantid::NeXus::NXInfo::stat, and Mantid::Kernel::Logger::warning().
Referenced by exec().
loadRunDetails()
void Mantid::DataHandling::LoadMuonNexus1::loadRunDetails (const DataObjects::Workspace2D_sptr & localWorkspace) private
Log the run details from the file.
Parameters
localWorkspace :: The workspace details to use
Definition at line 684 of file LoadMuonNexus1.cpp.
References Mantid::API::LogManager::addProperty(), Mantid::NeXus::NXClass::containsDataSet(), Mantid::API::g_log, Mantid::NeXus::NXClass::getFloat(), Mantid::NeXus::NXClass::getString(), Mantid::DataHandling::LoadMuonNexus::m_filename, Mantid::NeXus::NXRoot::openEntry(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
name()
const std::string Mantid::DataHandling::LoadMuonNexus1::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Reimplemented from Mantid::DataHandling::LoadMuonNexus.
Definition at line 60 of file LoadMuonNexus1.h.
runLoadLog()
void Mantid::DataHandling::LoadMuonNexus1::runLoadLog (const DataObjects::Workspace2D_sptr & localWorkspace) private
Run the LoadLog Child Algorithm.
Definition at line 731 of file LoadMuonNexus1.cpp.
References Mantid::DataHandling::ISISRunLogs::addStatusLog(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, Mantid::NeXus::NXClass::getString(), Mantid::DataHandling::LoadMuonNexus::m_filename, Mantid::NeXus::NXClass::openNXChar(), Mantid::Geometry::orientation(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by exec().
runLoadMappingTable()
void Mantid::DataHandling::LoadMuonNexus1::runLoadMappingTable (DataObjects::Workspace2D_sptr) private
summary()
const std::string Mantid::DataHandling::LoadMuonNexus1::summary () const inline override virtual
Summary of algorithms purpose.
Reimplemented from Mantid::DataHandling::LoadMuonNexus.
Definition at line 62 of file LoadMuonNexus1.h.
version()
int Mantid::DataHandling::LoadMuonNexus1::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Reimplemented from Mantid::DataHandling::LoadMuonNexus.
Definition at line 70 of file LoadMuonNexus1.h.
Referenced by confidence().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexus1.h
Framework/DataHandling/src/LoadMuonNexus1.cpp