Mantid: Mantid::Kernel::SpinStateValidator Class Reference
Mantid::Kernel::SpinStateValidator Class Reference
#include <SpinStateValidator.h>
Public Member Functions
Kernel::IValidator_sptr clone () const override
SpinStateValidator (std::unordered_set< int > allowedNumbersOfSpins, const bool acceptSingleStates=false, const std::string &paraIndicator="0", const std::string &antiIndicator="1", const bool optional=false, const std::string &extraIndicator="")
Static Public Member Functions
static bool anyOfIsInSet (const std::vector< std::string > &anyOf, const std::unordered_set< std::string > &set)
static bool setContains (const std::unordered_set< std::string > &set, const std::string &s)
Private Member Functions
std::string checkValidity (const std::string &input) const override
const std::unordered_set< std::string > getAllowedPairStates () const
const std::unordered_set< std::string > getAllowedSingleStates () const
Private Attributes
bool m_acceptSingleStates = false
std::unordered_set< int > m_allowedNumbersOfSpins = {1, 2, 3, 4}
const std::string m_anti
const std::string m_extra
bool m_optional = false
const std::string m_para
Detailed Description
Definition at line 23 of file SpinStateValidator.h.
Constructor & Destructor Documentation
SpinStateValidator()
Mantid::Kernel::SpinStateValidator::SpinStateValidator (std::unordered_set< int > allowedNumbersOfSpins, const bool acceptSingleStates = false, const std::string & paraIndicator = "0", const std::string & antiIndicator = "1", const bool optional = false, const std::string & extraIndicator = "")
Definition at line 16 of file SpinStateValidator.cpp.
Member Function Documentation
anyOfIsInSet()
bool Mantid::Kernel::SpinStateValidator::anyOfIsInSet (const std::vector< std::string > & anyOf, const std::unordered_set< std::string > & set) static
Definition at line 81 of file SpinStateValidator.cpp.
Referenced by checkValidity().
checkValidity()
std::string Mantid::Kernel::SpinStateValidator::checkValidity (const std::string & input) const override private
Definition at line 27 of file SpinStateValidator.cpp.
References anyOfIsInSet(), getAllowedPairStates(), getAllowedSingleStates(), m_acceptSingleStates, m_allowedNumbersOfSpins, m_anti, m_extra, m_optional, m_para, and Mantid::Kernel::SpinStateHelpers::splitSpinStateString().
clone()
Kernel::IValidator_sptr Mantid::Kernel::SpinStateValidator::clone () const override
Definition at line 23 of file SpinStateValidator.cpp.
References m_acceptSingleStates, and m_allowedNumbersOfSpins.
getAllowedPairStates()
const std::unordered_set< std::string > Mantid::Kernel::SpinStateValidator::getAllowedPairStates () const private
Definition at line 87 of file SpinStateValidator.cpp.
References m_anti, m_extra, and m_para.
Referenced by checkValidity().
getAllowedSingleStates()
const std::unordered_set< std::string > Mantid::Kernel::SpinStateValidator::getAllowedSingleStates () const private
Definition at line 96 of file SpinStateValidator.cpp.
References m_anti, m_extra, and m_para.
Referenced by checkValidity().
setContains()
static bool Mantid::Kernel::SpinStateValidator::setContains (const std::unordered_set< std::string > & set, const std::string & s) inline static
Definition at line 31 of file SpinStateValidator.h.
Member Data Documentation
m_acceptSingleStates
bool Mantid::Kernel::SpinStateValidator::m_acceptSingleStates = false private
Definition at line 40 of file SpinStateValidator.h.
Referenced by checkValidity(), and clone().
m_allowedNumbersOfSpins
std::unordered_set<int> Mantid::Kernel::SpinStateValidator::m_allowedNumbersOfSpins = {1, 2, 3, 4} private
Definition at line 37 of file SpinStateValidator.h.
Referenced by checkValidity(), and clone().
m_anti
const std::string Mantid::Kernel::SpinStateValidator::m_anti private
Definition at line 42 of file SpinStateValidator.h.
Referenced by checkValidity(), getAllowedPairStates(), and getAllowedSingleStates().
m_extra
const std::string Mantid::Kernel::SpinStateValidator::m_extra private
Definition at line 45 of file SpinStateValidator.h.
Referenced by checkValidity(), getAllowedPairStates(), and getAllowedSingleStates().
m_optional
bool Mantid::Kernel::SpinStateValidator::m_optional = false private
Definition at line 43 of file SpinStateValidator.h.
Referenced by checkValidity().
m_para
const std::string Mantid::Kernel::SpinStateValidator::m_para private
Definition at line 41 of file SpinStateValidator.h.
Referenced by checkValidity(), getAllowedPairStates(), and getAllowedSingleStates().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/SpinStateValidator.h
Framework/Kernel/src/SpinStateValidator.cpp