Mantid: Framework/PythonInterface/mantid/geometry/src/Exports/IMDDimension.cpp File Reference
IMDDimension.cpp File Reference
#include "MantidGeometry/MDGeometry/IMDDimension.h"
#include "MantidGeometry/MDGeometry/MDFrame.h"
#include "MantidKernel/UnitLabel.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <memory>
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/return_internal_reference.hpp>
Functions
void export_IMDDimension ()
std::string getName (const IMDDimension &self)
Function Documentation
export_IMDDimension()
void export_IMDDimension ()
Definition at line 55 of file IMDDimension.cpp.
References Mantid::Geometry::IMDDimension::getBinWidth(), Mantid::Geometry::IMDDimension::getDimensionId(), Mantid::Geometry::IMDDimension::getMaximum(), Mantid::Geometry::IMDDimension::getMinimum(), Mantid::Geometry::IMDDimension::getName(), getName(), Mantid::Geometry::IMDDimension::getNBins(), Mantid::Geometry::IMDDimension::getNBoundaries(), and Mantid::Geometry::IMDDimension::getX().
getName()
std::string getName (const IMDDimension & self)
Parameters
self Reference to the calling object
Returns
name of the dimension.
Definition at line 50 of file IMDDimension.cpp.
References Mantid::Geometry::IMDDimension::getName().
Referenced by Mantid::API::WorkspaceGroup::add(), Mantid::Crystal::SaveIsawPeaks::bankMasked(), Mantid::Geometry::edgePixel(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::MDAlgorithms::MergeMD::exec(), export_IMDDimension(), Mantid::Crystal::LoadIsawPeaks::findPixelID(), Mantid::Crystal::SaveIsawPeaks::findPixelPos(), Mantid::DataHandling::SaveIsawDetCal::findPixelPos(), Mantid::API::MDGeometry::getDimensionIndexByName(), Mantid::DataHandling::Load::loadMultipleFiles(), Mantid::API::ImplicitFunctionParameter::parameterXMLTemplate(), Mantid::API::WorkspaceGroup::remove(), Mantid::API::renameWorkspacesInQENSFit(), Mantid::API::renameWorkspacesWith(), Mantid::DataHandling::SaveNXTomo::setupFile(), Mantid::Crystal::SaveIsawPeaks::sizeBanks(), Mantid::DataHandling::SaveIsawDetCal::sizeBanks(), Mantid::API::WorkspaceGroup::sortByName(), Mantid::Algorithms::Stitch1DMany::validateInputs(), and Mantid::API::MultiPeriodGroupWorker::validateMultiPeriodGroupInputs().