Mantid: MantidQt::MantidWidgets::InputControllerSelection Class Reference
MantidQt::MantidWidgets::InputControllerSelection Class Reference
Controller for erasing peaks on an unwrapped surface.
#include <InputController.h>
Signals
void selection (const QRect &)
Signals inherited from MantidQt::MantidWidgets::InputController
void disabled ()
void enabled ()
void touchPointAt (int, int)
Public Member Functions
InputControllerSelection (QObject *parent, QPixmap *icon)
void onPaint (QPainter &) override
To be called after the owner widget has drawn its content.
~InputControllerSelection () override
Public Member Functions inherited from MantidQt::MantidWidgets::InputControllerDraw
void enterEvent (QEvent *) override
InputControllerDraw (QObject *parent)
Constructor.
void leaveEvent (QEvent *) override
void mouseMoveEvent (QMouseEvent *) override
Process the mouse move event.
void mousePressEvent (QMouseEvent *) override
Process the mouse press event.
void mouseReleaseEvent (QMouseEvent *) override
Process the mouse button release event.
void wheelEvent (QWheelEvent *) override
~InputControllerDraw () override
Public Member Functions inherited from MantidQt::MantidWidgets::InputController
bool canShowContextMenu () const
Returns true if a surface using this controller can show a context menu on right-click.
virtual void enterEvent (QEvent *)
virtual void freezeRotation (bool)
InputController (QObject *parent, bool contextAllowed=true)
virtual void keyPressEvent (QKeyEvent *)
virtual void leaveEvent (QEvent *)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *)
virtual void mouseReleaseEvent (QMouseEvent *)
virtual void onDisabled ()
To be called when this controller looses control.
virtual void onEnabled ()
To be called when this controller takes control of the input.
virtual void onPaint (QPainter &)
To be called after the owner widget has drawn its content.
virtual void wheelEvent (QWheelEvent *)
~InputController () override=default
Private Member Functions
void drawCursor (QPixmap *cursor) override
void resize () override
void setPosition (const QPoint &pos) override
void signalLeftClick () override
Private Attributes
QPixmap * m_image
QRect m_rect
Additional Inherited Members
Protected Member Functions inherited from MantidQt::MantidWidgets::InputControllerDraw
int cursorSize () const
bool isActive () const
bool isLeftButtonPressed () const
bool isRightButtonPressed () const
Detailed Description
Controller for erasing peaks on an unwrapped surface.
Definition at line 257 of file InputController.h.
Constructor & Destructor Documentation
InputControllerSelection()
MantidQt::MantidWidgets::InputControllerSelection::InputControllerSelection (QObject * parent, QPixmap * icon)
Definition at line 355 of file InputController.cpp.
References m_image.
~InputControllerSelection()
MantidQt::MantidWidgets::InputControllerSelection::~InputControllerSelection () override
Definition at line 360 of file InputController.cpp.
References m_image.
Member Function Documentation
drawCursor()
void MantidQt::MantidWidgets::InputControllerSelection::drawCursor (QPixmap * cursor) override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 368 of file InputController.cpp.
References MantidQt::MantidWidgets::InputControllerDraw::cursorSize().
onPaint()
void MantidQt::MantidWidgets::InputControllerSelection::onPaint (QPainter &) override virtual
To be called after the owner widget has drawn its content.
Reimplemented from MantidQt::MantidWidgets::InputController.
Definition at line 362 of file InputController.cpp.
References MantidQt::MantidWidgets::InputControllerDraw::isActive(), MantidQt::MantidWidgets::InputControllerDraw::isLeftButtonPressed(), m_image, and m_rect.
resize()
void MantidQt::MantidWidgets::InputControllerSelection::resize () override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 389 of file InputController.cpp.
References MantidQt::MantidWidgets::InputControllerDraw::cursorSize(), and m_rect.
selection
void MantidQt::MantidWidgets::InputControllerSelection::selection (const QRect &) signal
Referenced by signalLeftClick().
setPosition()
void MantidQt::MantidWidgets::InputControllerSelection::setPosition (const QPoint & pos) override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 387 of file InputController.cpp.
References m_rect.
signalLeftClick()
void MantidQt::MantidWidgets::InputControllerSelection::signalLeftClick () override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 394 of file InputController.cpp.
References m_rect, and selection().
Member Data Documentation
m_image
QPixmap* MantidQt::MantidWidgets::InputControllerSelection::m_image private
Definition at line 274 of file InputController.h.
Referenced by InputControllerSelection(), onPaint(), and ~InputControllerSelection().
m_rect
QRect MantidQt::MantidWidgets::InputControllerSelection::m_rect private
Definition at line 275 of file InputController.h.
Referenced by onPaint(), resize(), setPosition(), and signalLeftClick().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InputController.h
qt/widgets/common/src/InputController.cpp