Mantid: ICat4::ns1__dataCollectionParameter Class Reference
ICat4::ns1__dataCollectionParameter Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__dataCollectionParameter ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__parameter
ns1__parameter ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__dataCollection * dataCollection
Public Attributes inherited from ICat4::ns1__parameter
time_t * dateTimeValue
double * error
double * numericValue
double * rangeBottom
double * rangeTop
std::string * stringValue
ns1__parameterType * type
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2229 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__dataCollectionParameter()
ICat4::ns1__dataCollectionParameter::ns1__dataCollectionParameter () inline
Definition at line 2240 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__dataCollectionParameter::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 11843 of file ICat4C.cpp.
Referenced by ICat4::soap_in_ns1__dataCollectionParameter(), ICat4::soap_new_req_ns1__dataCollectionParameter(), and ICat4::soap_new_set_ns1__dataCollectionParameter().
soap_get()
void * ICat4::ns1__dataCollectionParameter::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 12039 of file ICat4C.cpp.
References ICat4::soap_get_ns1__dataCollectionParameter().
soap_in()
void * ICat4::ns1__dataCollectionParameter::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 11902 of file ICat4C.cpp.
References ICat4::soap_in_ns1__dataCollectionParameter().
Referenced by ICat4::soap_in_ns1__dataCollectionParameter().
soap_out()
int ICat4::ns1__dataCollectionParameter::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 11861 of file ICat4C.cpp.
References ICat4::soap_out_ns1__dataCollectionParameter().
soap_put()
int ICat4::ns1__dataCollectionParameter::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 12032 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__dataCollectionParameter.
soap_serialize()
void ICat4::ns1__dataCollectionParameter::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 11851 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__dataCollection().
soap_type()
int ICat4::ns1__dataCollectionParameter::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__parameter.
Definition at line 2233 of file ICat4Stub.h.
Member Data Documentation
dataCollection
ns1__dataCollection* ICat4::ns1__dataCollectionParameter::dataCollection
Definition at line 2231 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp