Mantid: Mantid::MDAlgorithms::FindPeaksMD Class Reference
Mantid::MDAlgorithms::FindPeaksMD Class Reference final
FindPeaksMD : TODO: DESCRIPTION.
#include <FindPeaksMD.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
FindPeaksMD ()
Constructor.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
std::map< std::string, std::string > validateInputs () override
Validate the inputs.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Types
enum eDimensionType { HKL , QLAB , QSAMPLE }
Enum describing which type of dimensions in the MDEventWorkspace.
Private Member Functions
void addLeanElasticPeak (const Mantid::Kernel::V3D &Q, const double binCount, const bool useGoniometer=false)
Adds a peak based on Q, bin count.
void addPeak (const Mantid::Kernel::V3D &Q, const double binCount, const Geometry::InstrumentRayTracer &tracer)
Adds a peak based on Q, bin count & a set of detector IDs.
void checkWorkspaceDims (const Mantid::API::IMDWorkspace_sptr &ws)
std::shared_ptr< DataObjects::LeanElasticPeak > createLeanElasticPeak (const Mantid::Kernel::V3D &Q, const double binCount, const bool useGoniometer=false)
Adds a peak based on Q, bin count.
std::shared_ptr< DataObjects::Peak > createPeak (const Mantid::Kernel::V3D &Q, const double binCount, const Geometry::InstrumentRayTracer &tracer)
Adds a peak based on Q, bin count.
void determineOutputType (const std::string &peakType, const uint16_t numExperimentInfo)
void exec () override
Run the algorithm.
template<typename MDE , size_t nd>
void findPeaks (typename DataObjects::MDEventWorkspace< MDE, nd >::sptr ws)
Run find peaks on an MDEventWorkspace.
void findPeaksHisto (const Mantid::DataObjects::MDHistoWorkspace_sptr &ws)
Run find peaks on a histo workspace.
void init () override
Initialise the properties.
void readExperimentInfo (const Mantid::API::ExperimentInfo_sptr &ei)
Read member variables from experiment info.
Private Attributes
double DensityThresholdFactor
Thresholding factor.
eDimensionType dimType
Dimension type.
Mantid::Geometry::Instrument_const_sptr inst
Instrument.
bool m_addDetectors
Flag to include the detectors within the peak.
signal_t m_densityScaleFactor
Arbitrary scaling factor for density to make more manageable numbers, especially for older file formats.
int m_edge
Number of edge pixels with no peaks.
Mantid::Kernel::Matrix< double > m_goniometer
Goniometer matrix.
bool m_leanElasticPeak = false
int64_t m_maxPeaks
Max # of peaks.
int m_runNumber
Run number of the peaks.
double m_signalThresholdFactor = 1.5
Signal density factor.
bool m_useNumberOfEventsNormalization = false
Use number of events normalization for event workspaces.
coord_t peakRadiusSquared
Estimated radius of peaks. Boxes closer than this are rejected.
Mantid::API::IPeaksWorkspace_sptr peakWS
Output PeaksWorkspace.
std::unique_ptr< Mantid::API::Progress > prog = nullptr
Progress reporter.
Static Private Attributes
static const std::string numberOfEventsNormalization = "NumberOfEventsNormalization"
NumberOfEventNormalization.
static const std::string volumeNormalization = "VolumeNormalization"
VolumeNormalization.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
FindPeaksMD : TODO: DESCRIPTION.
Author
Date
2011-06-02
Definition at line 33 of file FindPeaksMD.h.
Member Enumeration Documentation
eDimensionType
enum Mantid::MDAlgorithms::FindPeaksMD::eDimensionType private
Enum describing which type of dimensions in the MDEventWorkspace.
Enumerator
HKL
QLAB
QSAMPLE
Definition at line 108 of file FindPeaksMD.h.
Constructor & Destructor Documentation
FindPeaksMD()
Mantid::MDAlgorithms::FindPeaksMD::FindPeaksMD ()
Constructor.
Definition at line 108 of file FindPeaksMD.cpp.
Member Function Documentation
addLeanElasticPeak()
void Mantid::MDAlgorithms::FindPeaksMD::addLeanElasticPeak (const Mantid::Kernel::V3D & Q, const double binCount, const bool useGoniometer = false) private
Adds a peak based on Q, bin count.
Create and add a LeanElasticPeak to the output workspace.
Parameters
Q :: Q_lab or Q_sample, depending on workspace
binCount :: bin count to give to the peak.
useGoniometer :: if to include set goniometer from the input workspace in the peak
Definition at line 293 of file FindPeaksMD.cpp.
References createLeanElasticPeak(), and peakWS.
Referenced by findPeaks(), and findPeaksHisto().
addPeak()
void Mantid::MDAlgorithms::FindPeaksMD::addPeak (const Mantid::Kernel::V3D & Q, const double binCount, const Geometry::InstrumentRayTracer & tracer) private
Adds a peak based on Q, bin count & a set of detector IDs.
Create and add a Peak to the output workspace.
Parameters
Q :: Q_lab or Q_sample, depending on workspace
binCount :: bin count to give to the peak.
tracer :: Ray tracer to use for detector finding
Definition at line 271 of file FindPeaksMD.cpp.
References createPeak(), Mantid::Geometry::edgePixel(), Mantid::API::Algorithm::g_log, inst, m_edge, Mantid::Kernel::Logger::notice(), and peakWS.
Referenced by findPeaksHisto().
category()
const std::string Mantid::MDAlgorithms::FindPeaksMD::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 48 of file FindPeaksMD.h.
checkWorkspaceDims()
void Mantid::MDAlgorithms::FindPeaksMD::checkWorkspaceDims (const Mantid::API::IMDWorkspace_sptr & ws) private
Definition at line 234 of file FindPeaksMD.cpp.
References dimType, HKL, QLAB, and QSAMPLE.
Referenced by exec().
createLeanElasticPeak()
std::shared_ptr< DataObjects::LeanElasticPeak > Mantid::MDAlgorithms::FindPeaksMD::createLeanElasticPeak (const Mantid::Kernel::V3D & Q, const double binCount, const bool useGoniometer = false) private
Adds a peak based on Q, bin count.
Creates a Peak object from Q & bin count.
Definition at line 355 of file FindPeaksMD.cpp.
References dimType, m_goniometer, m_runNumber, and QSAMPLE.
Referenced by addLeanElasticPeak().
createPeak()
std::shared_ptr< DataObjects::Peak > Mantid::MDAlgorithms::FindPeaksMD::createPeak (const Mantid::Kernel::V3D & Q, const double binCount, const Geometry::InstrumentRayTracer & tracer) private
Adds a peak based on Q, bin count.
Creates a Peak object from Q & bin count.
Definition at line 301 of file FindPeaksMD.cpp.
References Mantid::Geometry::Goniometer::calcFromQSampleAndWavelength(), dimType, Mantid::API::Algorithm::g_log, Mantid::Geometry::Goniometer::getEulerAngles(), Mantid::API::Algorithm::getProperty(), Mantid::Geometry::Goniometer::getR(), Mantid::Kernel::Logger::information(), inst, m_goniometer, m_runNumber, QLAB, and QSAMPLE.
Referenced by addPeak(), and findPeaks().
determineOutputType()
void Mantid::MDAlgorithms::FindPeaksMD::determineOutputType (const std::string & peakType, const uint16_t numExperimentInfo) private
Definition at line 248 of file FindPeaksMD.cpp.
References m_leanElasticPeak.
Referenced by exec().
exec()
void Mantid::MDAlgorithms::FindPeaksMD::exec () override private virtual
Run the algorithm.
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 778 of file FindPeaksMD.cpp.
References CALL_MDEVENT_FUNCTION3, checkWorkspaceDims(), DensityThresholdFactor, determineOutputType(), findPeaks(), findPeaksHisto(), Mantid::API::Algorithm::getProperty(), m_edge, m_leanElasticPeak, m_maxPeaks, m_signalThresholdFactor, m_useNumberOfEventsNormalization, numberOfEventsNormalization, peakRadiusSquared, peakWS, Mantid::Geometry::IPeak::setPeakNumber(), and Mantid::Kernel::IPropertyManager::setProperty().
findPeaks()
template<typename MDE , size_t nd> void Mantid::MDAlgorithms::FindPeaksMD::findPeaks (typename DataObjects::MDEventWorkspace< MDE, nd >::sptr ws) private
Run find peaks on an MDEventWorkspace.
Integrate the peaks of the workspace using parameters saved in the algorithm class.
Parameters
ws :: MDEventWorkspace to integrate
Definition at line 376 of file FindPeaksMD.cpp.
References addLeanElasticPeak(), Mantid::API::IMDNode::calculateCentroid(), count, createPeak(), Mantid::Geometry::d, Mantid::Kernel::Logger::debug(), DensityThresholdFactor, Mantid::Geometry::edgePixel(), Mantid::API::Algorithm::g_log, Mantid::DataObjects::MDEventWorkspace< MDE, nd >::getBox(), Mantid::API::IMDNode::getCentroid(), Mantid::DataObjects::MDBox::getEvents(), Mantid::API::MultipleExperimentInfos::getExperimentInfo(), Mantid::API::IMDNode::getNPoints(), Mantid::API::MultipleExperimentInfos::getNumExperimentInfo(), Mantid::API::IMDNode::getSignalByNEvents(), Mantid::DataObjects::MDBoxBase::getSignalNormalized(), Mantid::DataObjects::MDEventWorkspace< MDE, nd >::id(), Mantid::Kernel::Logger::information(), inst, m_addDetectors, m_densityScaleFactor, m_edge, m_goniometer, m_leanElasticPeak, m_maxPeaks, m_signalThresholdFactor, m_useNumberOfEventsNormalization, Mantid::Kernel::Logger::notice(), peakRadiusSquared, peakWS, prog, Mantid::API::Algorithm::progress(), readExperimentInfo(), value, and Mantid::Kernel::Logger::warning().
Referenced by exec().
findPeaksHisto()
void Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto (const Mantid::DataObjects::MDHistoWorkspace_sptr & ws) private
Run find peaks on a histo workspace.
Find peaks in the given MDHistoWorkspace.
Parameters
ws :: MDHistoWorkspace
Definition at line 629 of file FindPeaksMD.cpp.
References addLeanElasticPeak(), addPeak(), Mantid::Geometry::d, Mantid::Kernel::Logger::debug(), DensityThresholdFactor, Mantid::API::Algorithm::g_log, index, Mantid::Kernel::Logger::information(), inst, m_densityScaleFactor, m_leanElasticPeak, m_maxPeaks, Mantid::Kernel::Logger::notice(), peakRadiusSquared, peakWS, prog, Mantid::API::Algorithm::progress(), readExperimentInfo(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
init()
void Mantid::MDAlgorithms::FindPeaksMD::init () override private virtual
Initialise the properties.
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 115 of file FindPeaksMD.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::Kernel::Direction::Input, Mantid::Kernel::IS_EQUAL_TO, Mantid::Kernel::IS_NOT_DEFAULT, numberOfEventsNormalization, Mantid::Kernel::Direction::Output, Mantid::Kernel::IPropertyManager::setPropertySettings(), and volumeNormalization.
name()
const std::string Mantid::MDAlgorithms::FindPeaksMD::name () const inline override virtual
Algorithm's name for identification.
Implements Mantid::API::Algorithm.
Definition at line 37 of file FindPeaksMD.h.
readExperimentInfo()
void Mantid::MDAlgorithms::FindPeaksMD::readExperimentInfo (const Mantid::API::ExperimentInfo_sptr & ei) private
Read member variables from experiment info.
Extract needed data from the workspace's experiment info.
Definition at line 217 of file FindPeaksMD.cpp.
References Mantid::API::Algorithm::g_log, inst, m_goniometer, m_runNumber, and Mantid::Kernel::Logger::warning().
Referenced by findPeaks(), and findPeaksHisto().
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::FindPeaksMD::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 46 of file FindPeaksMD.h.
summary()
const std::string Mantid::MDAlgorithms::FindPeaksMD::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 39 of file FindPeaksMD.h.
validateInputs()
std::map< std::string, std::string > Mantid::MDAlgorithms::FindPeaksMD::validateInputs (void) override virtual
Validate the inputs.
Reimplemented from Mantid::API::Algorithm.
Definition at line 852 of file FindPeaksMD.cpp.
References Mantid::API::Algorithm::getProperty(), and numberOfEventsNormalization.
version()
int Mantid::MDAlgorithms::FindPeaksMD::version () const inline override virtual
Algorithm's version for identification.
Implements Mantid::API::Algorithm.
Definition at line 45 of file FindPeaksMD.h.
Member Data Documentation
DensityThresholdFactor
double Mantid::MDAlgorithms::FindPeaksMD::DensityThresholdFactor private
Thresholding factor.
Definition at line 89 of file FindPeaksMD.h.
Referenced by exec(), findPeaks(), and findPeaksHisto().
dimType
eDimensionType Mantid::MDAlgorithms::FindPeaksMD::dimType private
Dimension type.
Definition at line 115 of file FindPeaksMD.h.
Referenced by checkWorkspaceDims(), createLeanElasticPeak(), and createPeak().
inst
Mantid::Geometry::Instrument_const_sptr Mantid::MDAlgorithms::FindPeaksMD::inst private
Instrument.
Definition at line 111 of file FindPeaksMD.h.
Referenced by addPeak(), createPeak(), findPeaks(), findPeaksHisto(), and readExperimentInfo().
m_addDetectors
bool Mantid::MDAlgorithms::FindPeaksMD::m_addDetectors private
Flag to include the detectors within the peak.
Definition at line 98 of file FindPeaksMD.h.
Referenced by findPeaks().
m_densityScaleFactor
signal_t Mantid::MDAlgorithms::FindPeaksMD::m_densityScaleFactor private
Arbitrary scaling factor for density to make more manageable numbers, especially for older file formats.
Definition at line 102 of file FindPeaksMD.h.
Referenced by findPeaks(), and findPeaksHisto().
m_edge
int Mantid::MDAlgorithms::FindPeaksMD::m_edge private
Number of edge pixels with no peaks.
Definition at line 95 of file FindPeaksMD.h.
Referenced by addPeak(), exec(), and findPeaks().
m_goniometer
Mantid::Kernel::Matrix<double> Mantid::MDAlgorithms::FindPeaksMD::m_goniometer private
Goniometer matrix.
Definition at line 117 of file FindPeaksMD.h.
Referenced by createLeanElasticPeak(), createPeak(), findPeaks(), and readExperimentInfo().
m_leanElasticPeak
bool Mantid::MDAlgorithms::FindPeaksMD::m_leanElasticPeak = false private
Definition at line 128 of file FindPeaksMD.h.
Referenced by determineOutputType(), exec(), findPeaks(), and findPeaksHisto().
m_maxPeaks
int64_t Mantid::MDAlgorithms::FindPeaksMD::m_maxPeaks private
Max # of peaks.
Definition at line 92 of file FindPeaksMD.h.
Referenced by exec(), findPeaks(), and findPeaksHisto().
m_runNumber
int Mantid::MDAlgorithms::FindPeaksMD::m_runNumber private
Run number of the peaks.
Definition at line 113 of file FindPeaksMD.h.
Referenced by createLeanElasticPeak(), createPeak(), and readExperimentInfo().
m_signalThresholdFactor
double Mantid::MDAlgorithms::FindPeaksMD::m_signalThresholdFactor = 1.5 private
Signal density factor.
Definition at line 122 of file FindPeaksMD.h.
Referenced by exec(), and findPeaks().
m_useNumberOfEventsNormalization
bool Mantid::MDAlgorithms::FindPeaksMD::m_useNumberOfEventsNormalization = false private
Use number of events normalization for event workspaces.
Definition at line 120 of file FindPeaksMD.h.
Referenced by exec(), and findPeaks().
numberOfEventsNormalization
const std::string Mantid::MDAlgorithms::FindPeaksMD::numberOfEventsNormalization = "NumberOfEventsNormalization" static private
NumberOfEventNormalization.
Definition at line 126 of file FindPeaksMD.h.
Referenced by exec(), init(), and validateInputs().
peakRadiusSquared
coord_t Mantid::MDAlgorithms::FindPeaksMD::peakRadiusSquared private
Estimated radius of peaks. Boxes closer than this are rejected.
Definition at line 86 of file FindPeaksMD.h.
Referenced by exec(), findPeaks(), and findPeaksHisto().
peakWS
Mantid::API::IPeaksWorkspace_sptr Mantid::MDAlgorithms::FindPeaksMD::peakWS private
Output PeaksWorkspace.
Definition at line 83 of file FindPeaksMD.h.
Referenced by addLeanElasticPeak(), addPeak(), exec(), findPeaks(), and findPeaksHisto().
prog
std::unique_ptr<Mantid::API::Progress> Mantid::MDAlgorithms::FindPeaksMD::prog = nullptr private
Progress reporter.
Definition at line 105 of file FindPeaksMD.h.
Referenced by findPeaks(), and findPeaksHisto().
volumeNormalization
const std::string Mantid::MDAlgorithms::FindPeaksMD::volumeNormalization = "VolumeNormalization" static private
VolumeNormalization.
Definition at line 124 of file FindPeaksMD.h.
Referenced by init().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/FindPeaksMD.h
Framework/MDAlgorithms/src/FindPeaksMD.cpp