Mantid: Mantid::MDAlgorithms::ConvToMDEventsWS Class Reference
Mantid::MDAlgorithms::ConvToMDEventsWS Class Reference
The class specializes ConvToDataObjectsBase for the case when the conversion occurs from Events WS to the MD events WS.
#include <ConvToMDEventsWS.h>
Public Member Functions
size_t initialize (const MDWSDescription &WSD, std::shared_ptr< MDEventWSWrapper > inWSWrapper, bool ignoreZeros) override
method sets up all internal variables necessary to convert from Event Workspace to MDEvent workspace
void runConversion (API::Progress *pProgress) override
method which starts the conversion procedure
Public Member Functions inherited from Mantid::MDAlgorithms::ConvToMDBase
ConvToMDBase ()
empty default constructor
UnitsConversionHelper & getUnitConversionHelper ()
method returns unit conversion helper, used to convert input workspace units to the units, used by appropriate MD transformation (if such conversion is necessary)
virtual void setDisplayNormalization (Mantid::API::IMDEventWorkspace_sptr mdWorkspace, const Mantid::API::MatrixWorkspace_sptr &underlyingWorkspace)
Set the normalization options.
virtual ~ConvToMDBase ()=default
virtual destructor
Protected Attributes
DataObjects::EventWorkspace_const_sptr m_EventWS
Protected Attributes inherited from Mantid::MDAlgorithms::ConvToMDBase
std::vector< coord_t > m_Coord
Mantid::Kernel::SpecialCoordinateSystem m_coordinateSystem
Any special coordinate system used.
std::vector< int32_t > m_detID
std::vector< size_t > m_detIDMap
uint16_t m_ExpInfoIndex
bool m_ignoreZeros
API::MatrixWorkspace_const_sptr m_InWS2D
size_t m_NDims
number of target ws dimensions
uint32_t m_NSpectra
int m_NumThreads
std::shared_ptr< MDEventWSWrapper > m_OutWSWrapper
MDTransf_sptr m_QConverter
UnitsConversionHelper m_UnitConversion
Private Member Functions
virtual void appendEventsFromInputWS (API::Progress *pProgress, const API::BoxController_sptr &bc)
size_t conversionChunk (size_t workspaceIndex) override
The method runs conversion for a single event list, corresponding to a particular workspace index.
template<class T >
size_t convertEventList (size_t workspaceIndex)
function converts particular type of events into MD space and add these events to the workspace itself
Additional Inherited Members
Static Protected Attributes inherited from Mantid::MDAlgorithms::ConvToMDBase
static Mantid::Kernel::Logger g_Log
Detailed Description
The class specializes ConvToDataObjectsBase for the case when the conversion occurs from Events WS to the MD events WS.
The detailed description of the algorithm is provided at dev-docs/source/WritingCustomConvertToMDTransformation.rst.
Definition at line 34 of file ConvToMDEventsWS.h.
Member Function Documentation
appendEventsFromInputWS()
void Mantid::MDAlgorithms::ConvToMDEventsWS::appendEventsFromInputWS (API::Progress * pProgress, const API::BoxController_sptr & bc) private virtual
Reimplemented in Mantid::MDAlgorithms::ConvToMDEventsWSIndexing, Mantid::MDAlgorithms::ConvToMDEventsWSIndexing, and Mantid::MDAlgorithms::ConvToMDEventsWSIndexing.
Definition at line 131 of file ConvToMDEventsWS.cpp.
References conversionChunk(), Mantid::MDAlgorithms::ConvToMDBase::m_NSpectra, Mantid::MDAlgorithms::ConvToMDBase::m_NumThreads, Mantid::MDAlgorithms::ConvToMDBase::m_OutWSWrapper, Mantid::Kernel::ProgressBase::report(), Mantid::Kernel::ProgressBase::resetNumSteps(), Mantid::Kernel::ThreadSchedulerFIFO::size(), and tp.
Referenced by runConversion().
conversionChunk()
size_t Mantid::MDAlgorithms::ConvToMDEventsWS::conversionChunk (size_t workspaceIndex) override private virtual
The method runs conversion for a single event list, corresponding to a particular workspace index.
Implements Mantid::MDAlgorithms::ConvToMDBase.
Definition at line 78 of file ConvToMDEventsWS.cpp.
References m_EventWS, Mantid::API::TOF, Mantid::API::WEIGHTED, and Mantid::API::WEIGHTED_NOTIME.
Referenced by appendEventsFromInputWS().
convertEventList()
template<class T > size_t Mantid::MDAlgorithms::ConvToMDEventsWS::convertEventList (size_t workspaceIndex) private
function converts particular type of events into MD space and add these events to the workspace itself
function converts particular list of events of type T into MD workspace and adds these events to the workspace itself
Definition at line 14 of file ConvToMDEventsWS.cpp.
References Mantid::MDAlgorithms::UnitsConversionHelper::convertUnits(), Mantid::DataObjects::getEventsFrom(), Mantid::DataObjects::EventList::getNumberEvents(), Mantid::MDAlgorithms::ConvToMDBase::m_Coord, Mantid::MDAlgorithms::ConvToMDBase::m_detID, m_EventWS, Mantid::MDAlgorithms::ConvToMDBase::m_ExpInfoIndex, Mantid::MDAlgorithms::ConvToMDBase::m_NDims, Mantid::MDAlgorithms::ConvToMDBase::m_OutWSWrapper, Mantid::MDAlgorithms::ConvToMDBase::m_QConverter, Mantid::MDAlgorithms::ConvToMDBase::m_UnitConversion, Mantid::DataHandling::numEvents(), and Mantid::MDAlgorithms::UnitsConversionHelper::updateConversion().
initialize()
size_t Mantid::MDAlgorithms::ConvToMDEventsWS::initialize (const MDWSDescription & WSD, std::shared_ptr< MDEventWSWrapper > inWSWrapper, bool ignoreZeros) override virtual
method sets up all internal variables necessary to convert from Event Workspace to MDEvent workspace
Parameters
WSD – the class describing the target MD workspace, sorurce Event workspace and the transformations, necessary to perform on these workspaces
inWSWrapper – the class wrapping the target MD workspace
ignoreZeros – if zero value signals should be rejected
Reimplemented from Mantid::MDAlgorithms::ConvToMDBase.
Reimplemented in Mantid::MDAlgorithms::ConvToMDEventsWSIndexing.
Definition at line 100 of file ConvToMDEventsWS.cpp.
References Mantid::MDAlgorithms::MDWSDescription::getCoordinateSystem(), Mantid::MDAlgorithms::ConvToMDBase::initialize(), Mantid::MDAlgorithms::ConvToMDBase::m_coordinateSystem, m_EventWS, and Mantid::MDAlgorithms::ConvToMDBase::m_InWS2D.
Referenced by Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::initialize().
runConversion()
void Mantid::MDAlgorithms::ConvToMDEventsWS::runConversion (API::Progress *) override virtual
method which starts the conversion procedure
Set the special coordinate system flag on the output workspace.
Implements Mantid::MDAlgorithms::ConvToMDBase.
Definition at line 113 of file ConvToMDEventsWS.cpp.
References appendEventsFromInputWS(), Mantid::MDAlgorithms::ConvToMDBase::m_Coord, Mantid::MDAlgorithms::ConvToMDBase::m_coordinateSystem, Mantid::MDAlgorithms::ConvToMDBase::m_NDims, Mantid::MDAlgorithms::ConvToMDBase::m_OutWSWrapper, Mantid::MDAlgorithms::ConvToMDBase::m_QConverter, and Mantid::Kernel::ProgressBase::report().
Member Data Documentation
m_EventWS
DataObjects::EventWorkspace_const_sptr Mantid::MDAlgorithms::ConvToMDEventsWS::m_EventWS protected
Definition at line 41 of file ConvToMDEventsWS.h.
Referenced by Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::appendEvents(), conversionChunk(), convertEventList(), Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::convertEvents(), and initialize().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/ConvToMDEventsWS.h
Framework/MDAlgorithms/src/ConvToMDEventsWS.cpp