Mantid: Mantid::Kernel::StringTokenizer Class Reference
Mantid::Kernel::StringTokenizer Class Reference final
#include <StringTokenizer.h>
Public Types
using ConstIterator = std::vector< std::string >::const_iterator
using Iterator = std::vector< std::string >::iterator
enum Options { TOK_IGNORE_EMPTY = 1 , TOK_TRIM = 2 , TOK_IGNORE_FINAL_EMPTY_TOKEN = 4 }
Specify tokenizer options. These can be combined using + or |.
using TokenVec = std::vector< std::string >
Public Member Functions
const TokenVec & asVector ()
Returns a vector of tokenized strings.
std::string & at (std::size_t index)
Get a reference to the index'th token.
const std::string & at (std::size_t index) const
Get a const reference to the index'th token.
Iterator begin ()
Iterator referring to first element in the container.
ConstIterator begin () const
Const iterator referring to first element in the container.
ConstIterator cbegin () const
Const iterator referring to first element in the container.
ConstIterator cend () const
Const iterator referring to the past-the-end element in the container.
std::size_t count () const
Get the total number of tokens.
Iterator end ()
Iterator referring to the past-the-end element in the container.
ConstIterator end () const
Const iterator referring to the past-the-end element in the container.
std::string & operator[] (std::size_t index)
Get a const reference to the index'th token.
const std::string & operator[] (std::size_t index) const
Get a const reference to the index'th token.
std::size_t size () const noexcept
Get the total number of tokens.
StringTokenizer ()=default
Constructs an object from an empty string.
StringTokenizer (const std::string &str, const std::string &separators, unsigned options=0)
Constructor requiring a string to tokenize and a string of separators.
~StringTokenizer ()=default
Destroys the tokenizer.
Private Attributes
std::vector< std::string > m_tokens
Detailed Description
Definition at line 27 of file StringTokenizer.h.
Member Typedef Documentation
ConstIterator
using Mantid::Kernel::StringTokenizer::ConstIterator = std::vector<std::string>::const_iterator
Definition at line 37 of file StringTokenizer.h.
Iterator
using Mantid::Kernel::StringTokenizer::Iterator = std::vector<std::string>::iterator
Definition at line 36 of file StringTokenizer.h.
TokenVec
using Mantid::Kernel::StringTokenizer::TokenVec = std::vector<std::string>
Definition at line 35 of file StringTokenizer.h.
Member Enumeration Documentation
Options
enum Mantid::Kernel::StringTokenizer::Options
Specify tokenizer options. These can be combined using + or |.
Enumerator
TOK_IGNORE_EMPTY
ignore empty tokens
TOK_TRIM
remove leading and trailing whitespace from tokens
TOK_IGNORE_FINAL_EMPTY_TOKEN
ignore an empty token at the end of the string.
Definition at line 30 of file StringTokenizer.h.
Constructor & Destructor Documentation
StringTokenizer() [1/2]
Mantid::Kernel::StringTokenizer::StringTokenizer () default
Constructs an object from an empty string.
StringTokenizer() [2/2]
Mantid::Kernel::StringTokenizer::StringTokenizer (const std::string & str, const std::string & separators, unsigned options = 0)
Constructor requiring a string to tokenize and a string of separators.
Parameters
str Input string to be separated into tokens.
separators List of characters used to separate the input string.
options tokenizer settings. The number can be found using the StringTokenizer::Options enum
Exceptions
Throws std::runtime_error if options > 7.
Definition at line 92 of file StringTokenizer.cpp.
References m_tokens, std::to_string(), TOK_IGNORE_EMPTY, TOK_IGNORE_FINAL_EMPTY_TOKEN, and TOK_TRIM.
~StringTokenizer()
Mantid::Kernel::StringTokenizer::~StringTokenizer () default
Destroys the tokenizer.
Member Function Documentation
asVector()
const TokenVec & Mantid::Kernel::StringTokenizer::asVector () inline
Returns a vector of tokenized strings.
Definition at line 91 of file StringTokenizer.h.
Referenced by Mantid::API::IFunction::categories(), Mantid::API::Algorithm::categories(), Mantid::DataHandling::getGroupNames(), Mantid::Geometry::operator>>(), Mantid::Kernel::UserStringParser::separateComma(), Mantid::Algorithms::SampleLogsBehaviour::setSampleMap(), Mantid::Kernel::Strings::StrParts(), Mantid::Kernel::UserStringParser::Tokenize(), and Mantid::API::Algorithm::workspaceMethodOn().
at() [1/2]
std::string & Mantid::Kernel::StringTokenizer::at (std::size_t index) inline
Get a reference to the index'th token.
Parameters
index Index of the requested token.
Returns
a reference to the index'th token.
Exceptions
Throws std::out_of_range if the index is out of range.
Definition at line 105 of file StringTokenizer.h.
References index.
at() [2/2]
const std::string & Mantid::Kernel::StringTokenizer::at (std::size_t index) const inline
Get a const reference to the index'th token.
Parameters
index Index of the requested token.
Returns
a const reference to the index'th token.
Exceptions
Throws std::out_of_range if the index is out of range.
Definition at line 98 of file StringTokenizer.h.
References index.
begin() [1/2]
Iterator Mantid::Kernel::StringTokenizer::begin () inline
Iterator referring to first element in the container.
Returns
an iterator referring to the first element in the container.
Definition at line 49 of file StringTokenizer.h.
Referenced by Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::API::AlgorithmFactoryImpl::fillHiddenCategories(), Mantid::API::FileFinderImpl::findRuns(), Mantid::API::FunctionFactoryImpl::getFunctionNamesGUI(), Mantid::DataHandling::GroupDetectors2::RangeHelper::getList(), Mantid::API::Expression::parse(), Mantid::DataHandling::UpdateInstrumentFromFile::parseAsciiHeader(), Mantid::CurveFitting::Functions::CrystalFieldControl::parseStringListAttribute(), Mantid::DataHandling::GroupDetectors2::readInt(), Mantid::API::ExperimentInfo::readParameterMap(), Mantid::DataHandling::PDLoadCharacterizations::readVersion1(), Mantid::Algorithms::ReadGroupsFromFile::readXMLGroupingFile(), Mantid::Algorithms::SampleLogsBehaviour::setSampleMap(), Mantid::Kernel::SpinStateHelpers::splitSpinStateString(), Mantid::DataHandling::CheckMantidVersion::splitVersionString(), and Mantid::Kernel::toValue().
begin() [2/2]
ConstIterator Mantid::Kernel::StringTokenizer::begin () const inline
Const iterator referring to first element in the container.
Returns
a const iterator referring to the first element in the container.
Definition at line 59 of file StringTokenizer.h.
cbegin()
ConstIterator Mantid::Kernel::StringTokenizer::cbegin () const inline
Const iterator referring to first element in the container.
Returns
a const iterator referring to the first element in the container.
Definition at line 69 of file StringTokenizer.h.
Referenced by Mantid::API::BoxControllerSettingsAlgorithm::initBoxControllerProps(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::Geometry::IsotropicAtomBraggScattererParser::operator()(), Mantid::DataHandling::SampleEnvironmentSpecParser::parseTranslationVector(), Mantid::DataHandling::LoadSpec::readLine(), Mantid::DataHandling::LoadRKH::readUnit(), Mantid::Geometry::strToUnitCell(), Mantid::Kernel::detail::toValue(), and Mantid::Kernel::VMDBase< TYPE >::VMDBase().
cend()
ConstIterator Mantid::Kernel::StringTokenizer::cend () const inline
Const iterator referring to the past-the-end element in the container.
Returns
a const iterator referring to the past-the-end element in the container.
Definition at line 74 of file StringTokenizer.h.
Referenced by Mantid::API::BoxControllerSettingsAlgorithm::initBoxControllerProps(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::Geometry::IsotropicAtomBraggScattererParser::operator()(), Mantid::DataHandling::SampleEnvironmentSpecParser::parseTranslationVector(), Mantid::DataHandling::LoadSpec::readLine(), Mantid::DataHandling::LoadRKH::readUnit(), Mantid::Geometry::strToUnitCell(), Mantid::Kernel::detail::toValue(), and Mantid::Kernel::VMDBase< TYPE >::VMDBase().
count()
std::size_t Mantid::Kernel::StringTokenizer::count () const inline
Get the total number of tokens.
Returns
the total number of tokens.
Definition at line 110 of file StringTokenizer.h.
Referenced by Mantid::DataHandling::LoadSpec::confidence(), Mantid::API::FileFinderImpl::findRuns(), Mantid::DataHandling::GroupDetectors2::RangeHelper::getList(), Mantid::API::getWordsInString(), Mantid::DataHandling::LoadNexusProcessed::getWordsInString(), Mantid::API::getWordsInString(), Mantid::DataHandling::LoadNexusProcessed::getWordsInString(), Mantid::API::BoxControllerSettingsAlgorithm::initBoxControllerProps(), Mantid::CurveFitting::Algorithms::makeNames(), Mantid::Kernel::operator>>(), Mantid::DataHandling::UpdateInstrumentFromFile::parseAsciiHeader(), Mantid::DataHandling::SampleEnvironmentSpecParser::parseTranslationVector(), Mantid::CurveFitting::Algorithms::parseValueRange(), Mantid::DataHandling::LoadRKH::read2DHeader(), Mantid::DataHandling::GroupDetectors2::readInt(), Mantid::API::ExperimentInfo::readParameterMap(), Mantid::DataHandling::LoadRKH::readUnit(), Mantid::Kernel::Strings::splitToKeyValues(), Mantid::Kernel::toValue(), Mantid::Kernel::detail::toValue(), and Mantid::Kernel::detail::toValue().
end() [1/2]
Iterator Mantid::Kernel::StringTokenizer::end () inline
Iterator referring to the past-the-end element in the container.
Returns
an iterator referring to the past-the-end element in the container.
Definition at line 54 of file StringTokenizer.h.
Referenced by Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::API::AlgorithmFactoryImpl::fillHiddenCategories(), Mantid::API::FileFinderImpl::findRuns(), Mantid::API::FunctionFactoryImpl::getFunctionNamesGUI(), Mantid::DataHandling::GroupDetectors2::RangeHelper::getList(), Mantid::DataHandling::UpdateInstrumentFromFile::parseAsciiHeader(), Mantid::CurveFitting::Functions::CrystalFieldControl::parseStringListAttribute(), Mantid::DataHandling::GroupDetectors2::readInt(), Mantid::API::ExperimentInfo::readParameterMap(), Mantid::DataHandling::PDLoadCharacterizations::readVersion1(), Mantid::Algorithms::ReadGroupsFromFile::readXMLGroupingFile(), Mantid::Algorithms::SampleLogsBehaviour::setSampleMap(), Mantid::DataHandling::CheckMantidVersion::splitVersionString(), and Mantid::Kernel::toValue().
end() [2/2]
ConstIterator Mantid::Kernel::StringTokenizer::end () const inline
Const iterator referring to the past-the-end element in the container.
Returns
a const iterator referring to the past-the-end element in the container.
Definition at line 64 of file StringTokenizer.h.
operator[]() [1/2]
std::string & Mantid::Kernel::StringTokenizer::operator[] (std::size_t index) inline
Get a const reference to the index'th token.
Indexing an out-of-range element won't throw, but is otherwise undefined behavior.
Parameters
index Index of the requested token.
Returns
a const reference to the index'th token.
Definition at line 88 of file StringTokenizer.h.
References index.
operator[]() [2/2]
const std::string & Mantid::Kernel::StringTokenizer::operator[] (std::size_t index) const inline
Get a const reference to the index'th token.
Indexing an out-of-range element won't throw, but is otherwise undefined behavior.
Parameters
index Index of the requested token.
Returns
a const reference to the index'th token.
Definition at line 81 of file StringTokenizer.h.
References index.
size()
std::size_t Mantid::Kernel::StringTokenizer::size () const inline noexcept
Get the total number of tokens.
Returns
the total number of tokens.
Definition at line 115 of file StringTokenizer.h.
Referenced by Mantid::API::FileFinderImpl::findRuns(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::Geometry::IsotropicAtomBraggScattererParser::operator()(), Mantid::DataHandling::LoadSpec::readLine(), and Mantid::Geometry::strToUnitCell().
Member Data Documentation
m_tokens
std::vector<std::string> Mantid::Kernel::StringTokenizer::m_tokens private
Definition at line 118 of file StringTokenizer.h.
Referenced by StringTokenizer().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/StringTokenizer.h
Framework/Kernel/src/StringTokenizer.cpp