Mantid: ICat4::xsd__boolean Class Reference
ICat4::xsd__boolean Class Reference
#include <ICat4Stub.h>
Public Member Functions
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
xsd__boolean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
bool __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 122 of file ICat4Stub.h.
Constructor & Destructor Documentation
xsd__boolean()
ICat4::xsd__boolean::xsd__boolean () inline
Definition at line 134 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::xsd__boolean::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24255 of file ICat4C.cpp.
References __item, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_bool().
Referenced by ICat4::soap_in_xsd__boolean(), ICat4::soap_new_req_xsd__boolean(), and ICat4::soap_new_set_xsd__boolean().
soap_get()
void * ICat4::xsd__boolean::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24310 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_xsd__boolean().
soap_in()
void * ICat4::xsd__boolean::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24277 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_xsd__boolean().
Referenced by ICat4::soap_in_xsd__boolean().
soap_out()
int ICat4::xsd__boolean::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24268 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_xsd__boolean().
Referenced by soap_put().
soap_put()
int ICat4::xsd__boolean::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24303 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_xsd__boolean.
soap_serialize()
void ICat4::xsd__boolean::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24261 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_serialize().
soap_type()
int ICat4::xsd__boolean::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 127 of file ICat4Stub.h.
Member Data Documentation
__item
bool ICat4::xsd__boolean::__item
Definition at line 124 of file ICat4Stub.h.
Referenced by soap_default().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp