Mantid: ICat4::ns1__datafileFormat Class Reference
ICat4::ns1__datafileFormat Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__datafileFormat ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< ns1__datafile * > datafiles
std::string * description
ns1__facility * facility
std::string * name
std::string * type
std::string * version
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1680 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__datafileFormat()
ICat4::ns1__datafileFormat::ns1__datafileFormat () inline
Definition at line 1696 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__datafileFormat::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15261 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__datafile().
Referenced by ICat4::soap_in_ns1__datafileFormat(), ICat4::soap_new_req_ns1__datafileFormat(), and ICat4::soap_new_set_ns1__datafileFormat().
soap_get()
void * ICat4::ns1__datafileFormat::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15443 of file ICat4C.cpp.
References ICat4::soap_get_ns1__datafileFormat().
soap_in()
void * ICat4::ns1__datafileFormat::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15323 of file ICat4C.cpp.
References ICat4::soap_in_ns1__datafileFormat().
Referenced by ICat4::soap_in_ns1__datafileFormat().
soap_out()
int ICat4::ns1__datafileFormat::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15287 of file ICat4C.cpp.
References ICat4::soap_out_ns1__datafileFormat().
soap_put()
int ICat4::ns1__datafileFormat::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15436 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__datafileFormat.
soap_serialize()
void ICat4::ns1__datafileFormat::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 15273 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__datafile().
soap_type()
int ICat4::ns1__datafileFormat::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1689 of file ICat4Stub.h.
Member Data Documentation
datafiles
std::vector<ns1__datafile *> ICat4::ns1__datafileFormat::datafiles
Definition at line 1682 of file ICat4Stub.h.
description
std::string* ICat4::ns1__datafileFormat::description
Definition at line 1683 of file ICat4Stub.h.
facility
ns1__facility* ICat4::ns1__datafileFormat::facility
Definition at line 1684 of file ICat4Stub.h.
name
std::string* ICat4::ns1__datafileFormat::name
Definition at line 1685 of file ICat4Stub.h.
type
std::string* ICat4::ns1__datafileFormat::type
Definition at line 1686 of file ICat4Stub.h.
version
std::string* ICat4::ns1__datafileFormat::version
Definition at line 1687 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp