Mantid: Mantid::CurveFitting::MuonHelper Namespace Reference
Mantid::CurveFitting::MuonHelper Namespace Reference
Functions
double MANTID_CURVEFITTING_DLL getActivationFunc (double xValue, const double attemptRate, const double barrier, const double unitMultipy)
double MANTID_CURVEFITTING_DLL getAttemptRateDiff (double xValue, const double barrier, const double unitMultipy)
double MANTID_CURVEFITTING_DLL getAz (double xValue, const double charField)
double MANTID_CURVEFITTING_DLL getBarrierDiff (double xValue, const double attemptRate, const double barrier, const double unitMultipy)
double MANTID_CURVEFITTING_DLL getDiffAz (double xValue, const double charField)
Function Documentation
getActivationFunc()
double Mantid::CurveFitting::MuonHelper::getActivationFunc (double xValue, const double attemptRate, const double barrier, const double unitMultipy)
Definition at line 34 of file MuonHelpers.cpp.
Referenced by Mantid::CurveFitting::Functions::ActivationK::function1D(), and Mantid::CurveFitting::Functions::ActivationmeV::function1D().
getAttemptRateDiff()
double Mantid::CurveFitting::MuonHelper::getAttemptRateDiff (double xValue, const double barrier, const double unitMultipy)
Definition at line 38 of file MuonHelpers.cpp.
Referenced by Mantid::CurveFitting::Functions::ActivationK::functionDeriv1D(), and Mantid::CurveFitting::Functions::ActivationmeV::functionDeriv1D().
getAz()
double Mantid::CurveFitting::MuonHelper::getAz (double xValue, const double charField)
Definition at line 15 of file MuonHelpers.cpp.
References fabs.
Referenced by Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong::function1D(), Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot::function1D(), Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong::functionDeriv1D(), and Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot::functionDeriv1D().
getBarrierDiff()
double Mantid::CurveFitting::MuonHelper::getBarrierDiff (double xValue, const double attemptRate, const double barrier, const double unitMultipy)
Definition at line 42 of file MuonHelpers.cpp.
Referenced by Mantid::CurveFitting::Functions::ActivationK::functionDeriv1D(), and Mantid::CurveFitting::Functions::ActivationmeV::functionDeriv1D().
getDiffAz()
double Mantid::CurveFitting::MuonHelper::getDiffAz (double xValue, const double charField)
Definition at line 23 of file MuonHelpers.cpp.
Referenced by Mantid::CurveFitting::Functions::DecoupAsymPowderMagLong::functionDeriv1D(), and Mantid::CurveFitting::Functions::DecoupAsymPowderMagRot::functionDeriv1D().