Mantid: Mantid::Kernel::V3D Class Reference
Mantid::Kernel::V3D Class Reference final
Class for 3D vectors.
#include <Kernel\V3D.h>
Public Member Functions
V3D absoluteValue () const
Absolute value.
double angle (const V3D &) const
Angle between this and another vector.
void azimuth_polar_SNS (const double R, const double azimuth, const double polar) noexcept
Sets the vector position based on azimuth and polar angle, in RADIANS, in the SNS instrument coordinate system, where +Z = beam direction, +Y = vertical.
bool coLinear (const V3D &, const V3D &) const noexcept
Determines if this,B,C are colinear.
double cosAngle (const V3D &) const
cos(Angle) between this and another vector
constexpr V3D cross_prod (const V3D &v) const noexcept
Cross product (this * argument)
V3D directionAngles (bool inDegrees=true) const
Direction angles.
double distance (const V3D &v) const noexcept
Calculates the distance between two vectors.
void fromString (const std::string &str)
Sets the vector using a string.
void getSpherical (double &R, double &theta, double &phi) const noexcept
Return the vector's position in spherical coordinates.
double hklError () const
Calculates the error in hkl.
void loadNexus (Nexus::File *file, const std::string &name)
Load the object from an open NeXus file.
int masterDir (const double Tol=1e-3) const noexcept
Determine if there is a master direction.
int maxCoeff () const
Maximum absolute integer value.
double norm () const noexcept
constexpr double norm2 () const noexcept
Vector length squared.
double normalize ()
Make a normalized vector (return norm value)
bool nullVector (const double tolerance=1e-3) const noexcept
Determine if the point is null.
operator std::vector< double > () const
bool operator!= (const V3D &other) const noexcept
Not equals operator with tolerance factor.
void operator() (const double xx, const double yy, const double zz) noexcept
Sets the vector position from a triplet of doubles x,y,z.
constexpr V3D operator* (const double D) const noexcept
Scalar product.
constexpr V3D operator* (const V3D &v) const noexcept
Inner product.
V3D & operator*= (const double D) noexcept
Scalar product.
V3D & operator*= (const V3D &v) noexcept
Self-Inner product.
constexpr V3D operator+ (const V3D &v) const noexcept
Addtion operator.
V3D & operator+= (const V3D &v) noexcept
Self-Addition operator.
constexpr V3D operator- () const noexcept
Negation.
constexpr V3D operator- (const V3D &v) const noexcept
Subtraction operator.
V3D & operator-= (const V3D &v) noexcept
Self-Subtraction operator.
constexpr V3D operator/ (const double D) const noexcept
Scalar divsion.
constexpr V3D operator/ (const V3D &v) const noexcept
Inner division.
V3D & operator/= (const double D) noexcept
Scalar division.
V3D & operator/= (const V3D &v) noexcept
Self-Inner division.
constexpr bool operator< (const V3D &V) const noexcept
compare
bool operator== (const V3D &v) const noexcept
Equals operator with tolerance factor.
constexpr bool operator> (const V3D &rhs) const noexcept
Comparison operator greater than.
constexpr double operator[] (const size_t index) const noexcept
Returns the axis value based in the index provided.
double & operator[] (const size_t index) noexcept
Returns the axis value based in the index provided.
void printSelf (std::ostream &) const
Prints a text representation of itself in format "[x,y,z]".
void read (std::istream &)
Read data from a stream.
void readPrinted (std::istream &)
Read data from a stream in the format returned by printSelf ("[x,y,z]").
int reBase (const V3D &, const V3D &, const V3D &) noexcept
rebase to new basis vector
void rotate (const Matrix< double > &) noexcept
Rotate a point by a matrix.
void round () noexcept
Round each component to the nearest integer.
void saveNexus (Nexus::File *file, const std::string &name) const
Save the object to an open NeXus file.
constexpr double scalar_prod (const V3D &v) const noexcept
Calculates the cross product.
void setX (const double xx) noexcept
Set is x position.
void setY (const double yy) noexcept
Set is y position.
void setZ (const double zz) noexcept
Set is z position.
std::size_t size () const noexcept
Number of components in V3D.
void spherical (const double R, const double theta, const double phi) noexcept
Sets the vector position based on spherical coordinates.
void spherical_rad (const double R, const double polar, const double azimuth) noexcept
Sets the vector position based on spherical coordinates, in radians.
double toMillerIndexes (double eps=1.e-3)
transform vector into form, used to describe directions in crystallogaphical coodinate system
std::string toString () const
bool unitVector (const double tolerance=Kernel::Tolerance) const noexcept
constexpr V3D () noexcept
constexpr V3D (double xx, double yy, double zz) noexcept
double volume () const noexcept
Calculate the volume of a cube X*Y*Z.
void write (std::ostream &) const
Write out the point values.
constexpr double X () const noexcept
Get x.
constexpr double Y () const noexcept
Get y.
constexpr double Z () const noexcept
Get z.
double zenith (const V3D &) const noexcept
Zenith (theta) angle between this and another vector.
Static Public Member Functions
static bool compareMagnitude (const Kernel::V3D &v1, const Kernel::V3D &v2)
Convenience method for sorting list of V3D objects based on magnitude.
static bool isnan (V3D const &vec)
Determine if a V3D can be considered nan.
static std::vector< V3D > makeVectorsOrthogonal (const std::vector< V3D > &vectors)
Take a list of 2 vectors and makes a 3D orthogonal system out of them The first vector i0 is taken as such.
Private Attributes
std::array< double, 3 > m_pt
Detailed Description
Class for 3D vectors.
Author
Laurent C Chapon, ISIS, RAL
Date
09/10/2007
Definition at line 34 of file V3D.h.
Constructor & Destructor Documentation
V3D() [1/2]
constexpr Mantid::Kernel::V3D::V3D () inline constexpr noexcept
Definition at line 36 of file V3D.h.
Referenced by absoluteValue(), and directionAngles().
V3D() [2/2]
constexpr Mantid::Kernel::V3D::V3D (double xx, double yy, double zz) inline constexpr noexcept
Definition at line 37 of file V3D.h.
Member Function Documentation
absoluteValue()
V3D Mantid::Kernel::V3D::absoluteValue () const
Absolute value.
Calculates the absolute value.
Returns
The absolute value
Definition at line 516 of file V3D.cpp.
References m_pt, and V3D().
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec().
angle()
double Mantid::Kernel::V3D::angle (const V3D & v) const
Angle between this and another vector.
Calculates the angle between this and another vector.
Parameters
v :: The other vector
Returns
The angle between the vectors in radians (0 < theta < pi)
Definition at line 162 of file V3D.cpp.
References cosAngle().
Referenced by Mantid::MDAlgorithms::calculate2Theta(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::calculateCounts(), Mantid::DataHandling::LoadILLDiffraction::calculateRelativeRotations(), Mantid::Geometry::IndexingUtils::DiscardDuplicates(), Mantid::DataHandling::LoadIsawDetCal::doRotation(), Mantid::Algorithms::HRPDSlabCanAbsorption::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), export_V3D(), Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateDetectorPos(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::Geometry::GetDiffFrom90Sum(), Mantid::DataObjects::Peak::getDSpacing(), Mantid::Geometry::ScalarUtils::GetRelatedUBs(), Mantid::DataObjects::Peak::getScattering(), Mantid::Geometry::Detector::getSignedTwoTheta(), Mantid::Geometry::DetectorGroup::getSignedTwoTheta(), Mantid::Geometry::Detector::getTwoTheta(), Mantid::Geometry::DetectorGroup::getTwoTheta(), Mantid::Geometry::NiggliCell::HasNiggliAngles(), Mantid::Geometry::InstrumentDefinitionParser::makeXYplaneFaceComponent(), Mantid::Kernel::Quat::operator()(), Mantid::Geometry::ConventionalCell::StandardizeHexagonal(), and Mantid::Algorithms::MCInteractionStatistics::UpdateScatterAngleStats().
azimuth_polar_SNS()
void Mantid::Kernel::V3D::azimuth_polar_SNS (const double R, const double azimuth, const double polar) noexcept
Sets the vector position based on azimuth and polar angle, in RADIANS, in the SNS instrument coordinate system, where +Z = beam direction, +Y = vertical.
Parameters
R :: The R value (distance)
azimuth :: The azimuthal angle (in Radians)
polar :: The polar value (in Radians)
Definition at line 94 of file V3D.cpp.
References Mantid::Kernel::Tolerance.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::calculateCounts().
coLinear()
bool Mantid::Kernel::V3D::coLinear (const V3D & Bv, const V3D & Cv) const noexcept
Determines if this,B,C are colinear.
Parameters
Bv :: Vector to test
Cv :: Vector to test
Returns
false if no colinear and true if they are (within Tolerance)
Definition at line 227 of file V3D.cpp.
References norm(), and Mantid::Kernel::Tolerance.
Referenced by Mantid::Crystal::CalculateUMatrix::exec().
compareMagnitude()
bool Mantid::Kernel::V3D::compareMagnitude (const Kernel::V3D & v1, const Kernel::V3D & v2) static
Convenience method for sorting list of V3D objects based on magnitude.
Comparator function for sorting list of 3D vectors based on their magnitude.
Parameters
v1 first vector
v2 seconde vector
Returns
true if v1.norm() < v2.norm().
Definition at line 475 of file V3D.cpp.
Referenced by Mantid::Geometry::IndexingUtils::FFTScanFor_Directions(), Mantid::Geometry::IndexingUtils::Find_UB(), Mantid::Geometry::IndexingUtils::Find_UB(), Mantid::Geometry::IndexingUtils::Find_UB(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), and Mantid::Geometry::ConventionalCell::SetSidesIncreasing().
cosAngle()
double Mantid::Kernel::V3D::cosAngle (const V3D & v) const
cos(Angle) between this and another vector
Calculates the cosine of angle between this and another vector.
Parameters
v :: The other vector
Returns
cosine of the angle between the vectors
Definition at line 177 of file V3D.cpp.
References norm(), and scalar_prod().
Referenced by angle(), export_V3D(), Mantid::DataObjects::Peak::findDetector(), Mantid::Algorithms::SolidAngleHelpers::Rectangle::solidAngle(), and Mantid::Algorithms::SolidAngleHelpers::Wing::solidAngle().
cross_prod()
constexpr V3D Mantid::Kernel::V3D::cross_prod (const V3D & v) const inline constexpr noexcept
Cross product (this * argument)
Definition at line 284 of file V3D.h.
Referenced by Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::Geometry::Rasterize::calculateCylinder(), Mantid::Geometry::Rasterize::calculateHollowCylinder(), Mantid::Kernel::VMDBase< TYPE >::cross_prod(), Mantid::Geometry::Plane::crossProd(), Mantid::DataHandling::LoadIsawDetCal::doRotation(), export_V3D(), Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::MDAlgorithms::IntegratePeaksMD2::getPinv(), Mantid::Geometry::Detector::getSignedTwoTheta(), Mantid::Geometry::DetectorGroup::getSignedTwoTheta(), Mantid::Geometry::MeshObjectCommon::getTriangleSolidAngle(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::Geometry::IndexingUtils::MakeCircleDirections(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), makeVectorsOrthogonal(), Mantid::Geometry::InstrumentDefinitionParser::makeXYplaneFaceComponent(), Mantid::Kernel::Quat::operator()(), Mantid::API::Projection::Projection(), Mantid::API::Projection::Projection(), Mantid::Kernel::Quat::Quat(), Mantid::Geometry::MeshObjectCommon::rayIntersectsTriangle(), Mantid::Geometry::CSGObject::rayTraceSolidAngle(), Mantid::MDAlgorithms::LoadSQW2::readSingleSPEHeader(), Mantid::Geometry::ConventionalCell::SetSidesIncreasing(), Mantid::Geometry::OrientedLattice::setUFromVectors(), Mantid::API::PanelsSurfaceCalculator::setupBasisAxes(), Mantid::MDAlgorithms::MDWSTransform::setUVvectors(), Mantid::Crystal::PeaksOnSurface::validateExtentsInput(), Mantid::Geometry::CSGObject::volume(), Mantid::Geometry::MeshObject::volume(), and Mantid::DataHandling::Mantid3MFFileIO::writeMeshObject().
directionAngles()
V3D Mantid::Kernel::V3D::directionAngles (bool inDegrees = true) const
Direction angles.
Get direction angles from direction cosines.
Parameters
inDegrees : optional argument for specifying in radians (false). Defaults to true.
Returns
V3D containing anlges.
Definition at line 487 of file V3D.cpp.
References m_pt, norm(), and V3D().
Referenced by export_V3D().
distance()
double Mantid::Kernel::V3D::distance (const V3D & v) const inline noexcept
Calculates the distance between two vectors.
Parameters
v :: The second vector to include in the calculation
Returns
The distance between the two vectors
Definition at line 293 of file V3D.h.
Referenced by Mantid::Geometry::Track::addPoint(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::cacheInstrumentGeometry(), Mantid::Algorithms::Q1DWeighted::calculate(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::calculateCounts(), Mantid::Algorithms::ModeratorTzeroLinear::calculateTfLi(), Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), Mantid::Geometry::MeshObject2D::distance(), Mantid::Geometry::Cylinder::distance(), Mantid::Geometry::Quadratic::distance(), Mantid::Geometry::MeshObject::distance(), export_V3D(), Mantid::Geometry::Component::getDistance(), Mantid::Algorithms::RadiusSum::getMaxDistance(), Mantid::Geometry::ObjComponent::interceptSurface(), Mantid::Crystal::PeakBackground::isBackground(), Mantid::Geometry::MeshObject::isValid(), Mantid::Geometry::Track::nonComplete(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), Mantid::DataObjects::PeaksWorkspace::peakInfoNumber(), Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration(), and Mantid::Geometry::Sphere::write().
fromString()
void Mantid::Kernel::V3D::fromString (const std::string & str)
Sets the vector using a string.
Parameters
str :: the vector as a string "X Y Z"
Definition at line 340 of file V3D.cpp.
References read().
Referenced by Mantid::Geometry::ComponentParser::endElement().
getSpherical()
void Mantid::Kernel::V3D::getSpherical (double & R, double & theta, double & phi) const noexcept
Return the vector's position in spherical coordinates.
Parameters
R :: Returns the radial distance
theta :: Returns the theta angle in degrees
phi :: Returns the phi (azimuthal) angle in degrees
Definition at line 116 of file V3D.cpp.
References Mantid::DataHandling::rad2deg.
Referenced by Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::Algorithms::CalculateDynamicRange::calculateQMinMax(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertToConstantL2::exec(), Mantid::DataHandling::ModifyDetectorDotDatFile::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Algorithms::RingProfile::getBinForPixel(), Mantid::Algorithms::RadiusSum::getBinForPixelPos(), Mantid::Geometry::DetectorGroup::getPhi(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::DataHandling::LoadILLIndirect2::moveComponent(), Mantid::DataHandling::LoadILLPolarizedDiffraction::moveTwoTheta(), Mantid::Algorithms::CreateDetectorTable::populateTable(), Mantid::Geometry::Instrument::saveDetectorSetInfoToNexus(), Mantid::DataHandling::SaveNexusProcessed::saveSpectraDetectorMapNexus(), Mantid::API::PanelsSurfaceCalculator::setupBasisAxes(), and Mantid::DataHandling::LoadEMU< FD >::updateNeutronicPostions().
hklError()
double Mantid::Kernel::V3D::hklError () const
Calculates the error in hkl.
Calculates the error of the HKL to compare with tolerance.
Returns
The error
Definition at line 522 of file V3D.cpp.
References m_pt.
Referenced by Mantid::Geometry::IndexingUtils::CalculateMillerIndices().
isnan()
static bool Mantid::Kernel::V3D::isnan (V3D const & vec) inline static
Determine if a V3D can be considered nan.
Parameters
vec
Returns
True if any of x, y, or z is nan; False otherwise
Definition at line 337 of file V3D.h.
References vec.
Referenced by Mantid::DataObjects::TableColumn< Type >::compareVectors(), and Mantid::DataObjects::TableColumn< Type >::compareVectorsRelError().
loadNexus()
void Mantid::Kernel::V3D::loadNexus (Nexus::File * file, const std::string & name)
Load the object from an open NeXus file.
Parameters
file :: open NeXus file
name :: name of the data to open
Definition at line 415 of file V3D.cpp.
References m_pt, and name.
Referenced by Mantid::Geometry::GoniometerAxis::loadNexus().
makeVectorsOrthogonal()
std::vector< V3D > Mantid::Kernel::V3D::makeVectorsOrthogonal (const std::vector< V3D > & vectors) static
Take a list of 2 vectors and makes a 3D orthogonal system out of them The first vector i0 is taken as such.
The second vector is made perpendicular to i0, in the plane of i0-i1 The third vector is made perpendicular to the plane i0-i1 by performing the cross product of 0 and 1
Parameters
vectors :: list of 2 vectors
Returns
list of 3 vectors
Definition at line 290 of file V3D.cpp.
References cross_prod(), Mantid::Kernel::normalize(), Mantid::Kernel::Quat::rotate(), and Mantid::Kernel::Quat::setRotation().
Referenced by Mantid::MDAlgorithms::MDWSTransform::buildQTrahsf(), Mantid::Kernel::VMDBase< TYPE >::makeVectorsOrthogonal(), and Mantid::MDAlgorithms::MDWSTransform::setQ3DDimensionsNames().
masterDir()
int Mantid::Kernel::V3D::masterDir (const double tolerance = 1e-3) const noexcept
Determine if there is a master direction.
Calculates the index of the primary direction (if there is one)
Parameters
tolerance :: Tolerance accepted
Return values
range -3,-2,-1 1,2,3 if the vector is orientaged within tolerance on the x,y,z direction (the sign indecates the direction to the +ve side)
0 :: No master direction
Definition at line 256 of file V3D.cpp.
References tolerance.
maxCoeff()
int Mantid::Kernel::V3D::maxCoeff () const
Maximum absolute integer value.
Vector maximum absolute integer value.
Returns
maxCoeff()
Definition at line 501 of file V3D.cpp.
References m_pt.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec().
norm()
double Mantid::Kernel::V3D::norm () const inline noexcept
Definition at line 269 of file V3D.h.
Referenced by Mantid::Geometry::CoplanarChecks::allCoplanar(), Mantid::Geometry::BoundingBox::angularWidth(), Mantid::DataHandling::LoadStl::areEqualVertices(), Mantid::API::WorkspaceNearestNeighbours::build(), Mantid::Algorithms::GravitySANSHelper::calcSinTheta(), Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::MDAlgorithms::IntegratePeaksMD2::calculateDistanceToEdge(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Crystal::IntegratePeakTimeSlices::CalculatePositionSpan(), Mantid::Crystal::IntegratePeakTimeSlices::CalculateTimeChannelSpan(), Mantid::DataObjects::BasePeak::calculateWavelengthFromQLab(), Mantid::Geometry::Sphere::centreToPoint(), coLinear(), Mantid::Geometry::CompareABCsum(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::API::DetectorSearcher::convertQtoDirection(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertSpiceMatrixToMomentumMDEvents(), cosAngle(), Mantid::MDAlgorithms::LoadSQW2::createQDimension(), Mantid::MDAlgorithms::Integrate3DEvents::detectorQ(), Mantid::MDAlgorithms::IntegrateQLabEvents::detectorQ(), directionAngles(), Mantid::Geometry::IndexingUtils::DiscardDuplicates(), Mantid::Geometry::Cone::distance(), Mantid::Geometry::Sphere::distance(), Mantid::Geometry::Torus::distance(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), export_V3D(), Mantid::Geometry::IndexingUtils::FFTScanFor_Directions(), Mantid::MDAlgorithms::IntegratePeaksMD2::findEllipsoid(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::DataObjects::Peak::getDetectorDirectionSampleFrame(), Mantid::DataObjects::LeanElasticPeak::getDSpacing(), Mantid::Geometry::IndexingUtils::GetIndexedPeaks_1D(), Mantid::Geometry::Instrument::getInstrumentParameters(), Mantid::DataObjects::Peak::getL1(), Mantid::Algorithms::RadiusSum::getMinBinSizeForInstrument(), Mantid::Crystal::PredictPeaks::getPeakParametersFromQ(), Mantid::MDAlgorithms::IntegratePeaksMD2::getPinv(), Mantid::DataObjects::Peak::getQLabFrame(), Mantid::Geometry::ScalarUtils::GetRelatedUBs(), Mantid::DataObjects::Peak::getSourceDirectionSampleFrame(), Mantid::Geometry::MeshObjectCommon::getTriangleSolidAngle(), Mantid::Geometry::MeshObject2D::initialize(), Mantid::Crystal::lineIntersectsSphere(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::makeIntegrationParameters(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::InstrumentDefinitionParser::makeXYplaneFaceComponent(), normalize(), Mantid::Geometry::IndexingUtils::NumberIndexed_1D(), Mantid::Geometry::IndexingUtils::NumberIndexed_3D(), Mantid::DataHandling::V3DTrueComparator::operator()(), Mantid::DataObjects::PeaksWorkspace::peakInfo(), Mantid::DataObjects::PeaksWorkspace::peakInfoNumber(), Mantid::DataHandling::SetScalingPSD::processScalingFile(), Mantid::Algorithms::SANSCollimationLengthEstimator::provideCollimationLength(), Mantid::Geometry::CSGObject::rayTraceSolidAngle(), Mantid::Geometry::IndexingUtils::ScanFor_Directions(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::scatter(), Mantid::Geometry::Cone::setNorm(), Mantid::Geometry::Torus::setNorm(), Mantid::DataObjects::Peak::setQLabFrame(), Mantid::Geometry::OrientedLattice::setUFromVectors(), Mantid::Geometry::ConventionalCell::StandardizeTetragonal(), Mantid::Algorithms::SmoothNeighbours::translateToMeters(), Mantid::Algorithms::LinearWeighting::weightAt(), Mantid::Algorithms::GaussianWeightingnD::weightAt(), and Mantid::Kernel::withinRelativeDifference< V3D, double >().
norm2()
constexpr double Mantid::Kernel::V3D::norm2 () const inline constexpr noexcept
Vector length squared.
Definition at line 271 of file V3D.h.
Referenced by Mantid::Crystal::PeakStatisticsTools::UniqueReflectionCollection::addObservations(), Mantid::Crystal::PredictPeaks::exec(), export_V3D(), Mantid::Geometry::IsotropicAtomBraggScatterer::getDebyeWallerFactor(), Mantid::DataObjects::BasePeak::getValueByColName(), Mantid::Geometry::Line::intersect(), Mantid::Geometry::HKLFilterWavelength::isAllowed(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), Mantid::Geometry::MeshObject2D::pointsCoplanar(), Mantid::Geometry::OrientedLattice::setUFromVectors(), Mantid::Crystal::PeaksOnSurface::validateExtentsInput(), and Mantid::Kernel::withinRelativeDifference< V3D, double >().
normalize()
double Mantid::Kernel::V3D::normalize ()
Make a normalized vector (return norm value)
Normalises the vector and returns its original length.
Returns
the norm of the vector before normalization
Definition at line 129 of file V3D.cpp.
References norm(), and operator/=().
Referenced by Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::cacheInputs(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::API::PanelsSurfaceCalculator::calculateBankNormal(), Mantid::Algorithms::He3TubeEfficiency::calculateExponential(), Mantid::Geometry::Rasterize::calculateHollowCylinder(), Mantid::API::DetectorSearcher::convertQtoDirection(), Mantid::Algorithms::DetectorEfficiencyCor::correctForEfficiency(), Mantid::Geometry::OrientedLattice::cosFromDir(), Mantid::Geometry::ShapeFactory::createGeometryHandler(), Mantid::DataHandling::LoadIsawDetCal::doRotation(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::Crystal::PredictPeaks::getPeakParametersFromQ(), Mantid::Geometry::CSGObject::isOnSide(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::Geometry::IndexingUtils::MakeCircleDirections(), Mantid::Kernel::normalize(), Mantid::Geometry::Line::rotate(), Mantid::Geometry::Cylinder::rotate(), Mantid::Geometry::Plane::rotate(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::scatter(), Mantid::Geometry::IndexingUtils::SelectDirection(), Mantid::DataObjects::Peak::setQLabFrame(), Mantid::Geometry::Plane::setSurface(), Mantid::Geometry::OrientedLattice::setUFromVectors(), Mantid::API::PanelsSurfaceCalculator::setupBasisAxes(), and Mantid::Geometry::Quadratic::surfaceNormal().
nullVector()
bool Mantid::Kernel::V3D::nullVector (const double tolerance = 1e-3) const noexcept
Determine if the point is null.
Checks the size of the vector.
Parameters
tolerance :: size of the biggest zero vector allowed.
Returns
true if the vector's elements are less in magnitude than tolerance
Definition at line 238 of file V3D.cpp.
References tolerance.
Referenced by Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::API::MatrixWorkspace::detectorSignedTwoTheta(), Mantid::API::MatrixWorkspace::detectorTwoTheta(), Mantid::DataHandling::LoadIsawDetCal::doRotation(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::API::DetectorSearcher::findDetectorIndex(), Mantid::Kernel::Quat::operator()(), Mantid::Kernel::Quat::Quat(), Mantid::Geometry::CSGObject::rayTraceSolidAngle(), Mantid::Geometry::Line::setLine(), and Mantid::API::PanelsSurfaceCalculator::tubeDetectorParentIDs().
operator std::vector< double >()
Mantid::Kernel::V3D::operator std::vector< double > () const inline
Definition at line 43 of file V3D.h.
operator!=()
bool Mantid::Kernel::V3D::operator!= (const V3D & other) const inline noexcept
Not equals operator with tolerance factor.
Parameters
other :: The V3D to compare against
Returns
True if the vectors are different
Definition at line 190 of file V3D.h.
References std::operator==().
operator()()
void Mantid::Kernel::V3D::operator() (const double xx, const double yy, const double zz) inline noexcept
Sets the vector position from a triplet of doubles x,y,z.
Parameters
xx :: The X coordinate
yy :: The Y coordinate
zz :: The Z coordinate
Definition at line 213 of file V3D.h.
operator*() [1/2]
constexpr V3D Mantid::Kernel::V3D::operator* (const double D) const inline constexpr noexcept
Scalar product.
Parameters
D :: value to scale
Returns
this * D
Definition at line 140 of file V3D.h.
operator*() [2/2]
constexpr V3D Mantid::Kernel::V3D::operator* (const V3D & v) const inline constexpr noexcept
Inner product.
Parameters
v :: Vector to sub.
Returns
*this * v;
Definition at line 74 of file V3D.h.
operator*=() [1/2]
V3D & Mantid::Kernel::V3D::operator*= (const double D) inline noexcept
Scalar product.
Parameters
D :: value to scale
Returns
this *= D
Definition at line 154 of file V3D.h.
operator*=() [2/2]
V3D & Mantid::Kernel::V3D::operator*= (const V3D & v) inline noexcept
Self-Inner product.
Parameters
v :: Vector to multiply
Returns
this=v;
Definition at line 116 of file V3D.h.
References m_pt.
Referenced by toMillerIndexes().
operator+()
constexpr V3D Mantid::Kernel::V3D::operator+ (const V3D & v) const inline constexpr noexcept
Addtion operator.
Parameters
v :: Vector to add
Returns
*this+v;
Definition at line 56 of file V3D.h.
operator+=()
V3D & Mantid::Kernel::V3D::operator+= (const V3D & v) inline noexcept
Self-Addition operator.
Parameters
v :: Vector to add.
Returns
*this+=v;
Definition at line 92 of file V3D.h.
References m_pt.
operator-() [1/2]
constexpr V3D Mantid::Kernel::V3D::operator- () const inline constexpr noexcept
Negation.
Returns
a vector with same magnitude but in opposite direction
Definition at line 174 of file V3D.h.
operator-() [2/2]
constexpr V3D Mantid::Kernel::V3D::operator- (const V3D & v) const inline constexpr noexcept
Subtraction operator.
Parameters
v :: Vector to sub.
Returns
*this-v;
Definition at line 65 of file V3D.h.
operator-=()
V3D & Mantid::Kernel::V3D::operator-= (const V3D & v) inline noexcept
Self-Subtraction operator.
Parameters
v :: Vector to sub.
Returns
*this-v;
Definition at line 104 of file V3D.h.
References m_pt.
operator/() [1/2]
constexpr V3D Mantid::Kernel::V3D::operator/ (const double D) const inline constexpr noexcept
Scalar divsion.
Parameters
D :: value to scale
Returns
this / D
Definition at line 147 of file V3D.h.
operator/() [2/2]
constexpr V3D Mantid::Kernel::V3D::operator/ (const V3D & v) const inline constexpr noexcept
Inner division.
Parameters
v :: Vector to divide
Returns
*this * v;
Definition at line 83 of file V3D.h.
operator/=() [1/2]
V3D & Mantid::Kernel::V3D::operator/= (const double D) inline noexcept
Scalar division.
Parameters
D :: value to scale
Returns
this /= D
Todo:
ADD TOLERANCE
Definition at line 165 of file V3D.h.
operator/=() [2/2]
V3D & Mantid::Kernel::V3D::operator/= (const V3D & v) inline noexcept
Self-Inner division.
Parameters
v :: Vector to divide
Returns
this=v;
Definition at line 128 of file V3D.h.
References m_pt.
Referenced by normalize().
operator<()
constexpr bool Mantid::Kernel::V3D::operator< (const V3D & V) const inline constexpr noexcept
compare
Returns
true if V is greater
Definition at line 196 of file V3D.h.
operator==()
bool Mantid::Kernel::V3D::operator== (const V3D & v) const inline noexcept
Equals operator with tolerance factor.
Parameters
v :: V3D for comparison
Returns
true if the items are equal
Definition at line 181 of file V3D.h.
References Mantid::Kernel::Tolerance.
operator>()
constexpr bool Mantid::Kernel::V3D::operator> (const V3D & rhs) const inline constexpr noexcept
Comparison operator greater than.
Definition at line 205 of file V3D.h.
References rhs.
operator[]() [1/2]
constexpr double Mantid::Kernel::V3D::operator[] (const size_t index) const inline constexpr noexcept
Returns the axis value based in the index provided.
Parameters
index :: 0=x, 1=y, 2=z
Returns
a double value of the requested axis
Definition at line 247 of file V3D.h.
References index.
operator[]() [2/2]
double & Mantid::Kernel::V3D::operator[] (const size_t index) inline noexcept
Returns the axis value based in the index provided.
Parameters
index :: 0=x, 1=y, 2=z
Returns
a double value of the requested axis
Definition at line 257 of file V3D.h.
References index.
printSelf()
void Mantid::Kernel::V3D::printSelf (std::ostream & os) const
Prints a text representation of itself in format "[x,y,z]".
Parameters
os :: the Stream to output to
Definition at line 349 of file V3D.cpp.
References m_pt.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD2::calcCovar(), and Mantid::Kernel::operator<<().
read()
void Mantid::Kernel::V3D::read (std::istream & IX)
Read data from a stream.
Todo:
Check Error handling
Parameters
IX :: Input Stream
Definition at line 320 of file V3D.cpp.
References m_pt.
Referenced by fromString().
readPrinted()
void Mantid::Kernel::V3D::readPrinted (std::istream & IX)
Read data from a stream in the format returned by printSelf ("[x,y,z]").
Parameters
IX :: Input Stream
Exceptions
std::runtime_error if the input is of wrong format
Definition at line 356 of file V3D.cpp.
References m_pt.
Referenced by Mantid::DataHandling::SaveParameterFile::exec(), Mantid::Kernel::operator>>(), and Mantid::DataHandling::LoadAscii2::readTable().
reBase()
int Mantid::Kernel::V3D::reBase (const V3D & A, const V3D & B, const V3D & C) noexcept
rebase to new basis vector
Re-express this point as components of A,B,C.
Assuming that A,B,C form a basis set (which does not have to be orthonormal).
Parameters
A :: Unit vector in basis
B :: Unit vector in basis
C :: Unit vector in basis
Return values
-1 :: The points do not form a basis set.
0 :: Vec3D has successfully been re-expressed.
Definition at line 196 of file V3D.cpp.
References Mantid::Kernel::Matrix< T >::Invert().
rotate()
void Mantid::Kernel::V3D::rotate (const Matrix< double > & A) noexcept
Rotate a point by a matrix.
Parameters
A :: Rotation matrix (needs to be >= 3x3)
Definition at line 214 of file V3D.cpp.
Referenced by Mantid::Geometry::ShapeFactory::parseCuboid(), Mantid::Geometry::ShapeFactory::parseCylinder(), Mantid::Geometry::ShapeFactory::parseHollowCylinder(), Mantid::Geometry::ShapeFactory::parseInfiniteCylinder(), Mantid::Geometry::ShapeFactory::parseInfinitePlane(), Mantid::Geometry::ShapeFactory::parseSliceOfCylinderRing(), Mantid::Geometry::ShapeFactory::parseSphere(), Mantid::Geometry::ShapeFactory::parseTaperedGuide(), Mantid::Geometry::Line::rotate(), Mantid::Geometry::Cone::rotate(), Mantid::Geometry::Cylinder::rotate(), Mantid::Geometry::Plane::rotate(), Mantid::Geometry::Sphere::rotate(), Mantid::Geometry::Torus::rotate(), Mantid::Geometry::CuboidCorners::rotatePoints(), and Mantid::Geometry::Hexahedron::rotatePoints().
round()
void Mantid::Kernel::V3D::round () noexcept
Round each component to the nearest integer.
Definition at line 139 of file V3D.cpp.
References m_pt.
Referenced by Mantid::Crystal::PeakIntensityVsRadius::exec(), and Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingPeaksWorkspace().
saveNexus()
void Mantid::Kernel::V3D::saveNexus (Nexus::File * file, const std::string & name) const
Save the object to an open NeXus file.
Parameters
file :: open NeXus file
name :: name of the data to create
Definition at line 404 of file V3D.cpp.
References NXnumtype::FLOAT64, m_pt, and name.
Referenced by Mantid::Geometry::GoniometerAxis::saveNexus().
scalar_prod()
constexpr double Mantid::Kernel::V3D::scalar_prod (const V3D & v) const inline constexpr noexcept
Calculates the cross product.
Returns (this * v).
Parameters
v :: The second vector to include in the calculation
Returns
The cross product of the two vectors (this * v)
Definition at line 280 of file V3D.h.
Referenced by Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::Algorithms::GravitySANSHelper::calcSinTheta(), Mantid::API::TimeAtSampleStrategyElastic::calculate(), Mantid::API::TimeAtSampleStrategyIndirect::calculate(), Mantid::MDAlgorithms::IntegratePeaksMD2::calculateDistanceToEdge(), Mantid::Algorithms::He3TubeEfficiency::calculateExponential(), Mantid::Geometry::IsotropicAtomBraggScatterer::calculateStructureFactor(), Mantid::DataObjects::BasePeak::calculateWavelengthFromQLab(), Mantid::Crystal::PeaksInRegion::checkTouchPoint(), Mantid::Crystal::PeaksOnSurface::checkTouchPoint(), Mantid::API::DetectorSearcher::convertQtoDirection(), Mantid::Algorithms::DetectorEfficiencyCor::correctForEfficiency(), cosAngle(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::MDAlgorithms::Integrate3DEvents::detectorQ(), Mantid::MDAlgorithms::IntegrateQLabEvents::detectorQ(), Mantid::Geometry::Plane::displace(), Mantid::Geometry::MeshObject2D::distance(), Mantid::Geometry::Line::distance(), Mantid::Geometry::Cone::distance(), Mantid::Geometry::Cylinder::distance(), export_V3D(), Mantid::Geometry::IndexingUtils::FormUB_From_abc_Vectors(), Mantid::Geometry::IndexingUtils::GetIndexedPeaks_1D(), Mantid::Geometry::IndexingUtils::GetIndexedPeaks_3D(), Mantid::Geometry::IndexingUtils::GetMagFFT(), Mantid::Crystal::PredictPeaks::getPeakParametersFromQ(), Mantid::MDAlgorithms::IntegratePeaksMD2::getPinv(), Mantid::Geometry::Detector::getSignedTwoTheta(), Mantid::Geometry::DetectorGroup::getSignedTwoTheta(), Mantid::Geometry::MeshObjectCommon::getTriangleSolidAngle(), Mantid::Geometry::MeshObject2D::interceptSurface(), Mantid::Geometry::Line::intersect(), Mantid::Geometry::Line::intersect(), Mantid::Geometry::MeshObjectCommon::isOnTriangle(), Mantid::Geometry::ReferenceFrame::isVectorPointingAlongBeam(), Mantid::Geometry::Plane::LineIntersectionWithPlane(), Mantid::Crystal::lineIntersectsSphere(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::IndexingUtils::NumberIndexed_1D(), Mantid::Geometry::IndexingUtils::NumberIndexed_3D(), Mantid::Geometry::Cone::onSurface(), Mantid::API::Projection::Projection(), Mantid::Kernel::Quat::Quat(), Mantid::Geometry::MeshObjectCommon::rayIntersectsTriangle(), Mantid::Geometry::IndexingUtils::ScanFor_Directions(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::Geometry::IndexingUtils::SelectDirection(), Mantid::Geometry::Cone::setBaseEqn(), Mantid::Geometry::Cylinder::setBaseEqn(), Mantid::Geometry::Sphere::setBaseEqn(), Mantid::Geometry::Plane::setPlane(), Mantid::DataObjects::Peak::setQLabFrame(), Mantid::Geometry::ConventionalCell::SetSidesIncreasing(), Mantid::Geometry::Plane::setSurface(), Mantid::Crystal::IntegratePeakTimeSlices::SetUpData1(), Mantid::Geometry::Plane::side(), Mantid::Geometry::Cone::side(), Mantid::API::PanelsSurfaceCalculator::transformedBoundingBoxPoints(), Mantid::Crystal::PeaksOnSurface::validateExtentsInput(), Mantid::Geometry::CSGObject::volume(), and Mantid::Geometry::MeshObject::volume().
setX()
void Mantid::Kernel::V3D::setX (const double xx) inline noexcept
Set is x position.
Parameters
xx :: The X coordinate
Definition at line 224 of file V3D.h.
Referenced by Mantid::Geometry::ParameterMap::addPositionCoordinate(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromString(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::SolidAngleHelpers::AlphaAngleHorizontal::project(), V3DPickleSuite::setstate(), Mantid::Geometry::PeakTransform::transform(), and Mantid::Geometry::PeakTransform::transformBack().
setY()
void Mantid::Kernel::V3D::setY (const double yy) inline noexcept
Set is y position.
Parameters
yy :: The Y coordinate
Definition at line 230 of file V3D.h.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromString(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::SolidAngleHelpers::AlphaAngleVertical::project(), V3DPickleSuite::setstate(), Mantid::Geometry::PeakTransform::transform(), and Mantid::Geometry::PeakTransform::transformBack().
setZ()
void Mantid::Kernel::V3D::setZ (const double zz) inline noexcept
Set is z position.
Parameters
zz :: The Z coordinate
Definition at line 236 of file V3D.h.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::CurveFitting::Algorithms::V3DFromHKLColumnExtractor::getHKLFromString(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), V3DPickleSuite::setstate(), Mantid::Geometry::PeakTransform::transform(), and Mantid::Geometry::PeakTransform::transformBack().
size()
std::size_t Mantid::Kernel::V3D::size () const inline noexcept
Number of components in V3D.
Returns
3
Definition at line 49 of file V3D.h.
Referenced by Mantid::Algorithms::RadiusSum::centerIsInsideLimits(), Mantid::DataHandling::LoadHelper::fillStaticWorkspace(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Geometry::MeshObject::getTriangle(), Mantid::Geometry::MeshObject::numberOfTriangles(), and Mantid::API::PanelsSurfaceCalculator::tubeDetectorParentIDs().
spherical()
void Mantid::Kernel::V3D::spherical (const double R, const double theta, const double phi) noexcept
Sets the vector position based on spherical coordinates.
Parameters
R :: The R value (distance)
theta :: The theta value (in degrees) = the polar angle away from the +Z axis.
phi :: The phi value (in degrees) = the azimuthal angle, where 0 points along +X and rotates clockwise in the XY plane
Definition at line 56 of file V3D.cpp.
References Mantid::Geometry::deg2rad.
Referenced by Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::DataHandling::LoadGSS::createInstrumentGeometry(), Mantid::Algorithms::ConvertToConstantL2::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::SetScalingPSD::getDetPositionsFromRaw(), Mantid::Geometry::InstrumentDefinitionParser::getRelativeTranslation(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::DataHandling::LoadILLIndirect2::moveComponent(), Mantid::Geometry::InstrumentDefinitionParser::parseFacingElementToV3D(), Mantid::Geometry::InstrumentDefinitionParser::parsePosition(), Mantid::Geometry::ShapeFactory::parsePosition(), Mantid::API::ExperimentInfo::populateInstrumentParameters(), Mantid::DataHandling::SetScalingPSD::processScalingFile(), Mantid::DataHandling::UpdateInstrumentFromFile::setDetectorPosition(), and Mantid::DataHandling::LoadDetectorInfo::updateParameterMap().
spherical_rad()
void Mantid::Kernel::V3D::spherical_rad (const double R, const double polar, const double azimuth) noexcept
Sets the vector position based on spherical coordinates, in radians.
Parameters
R :: The R value (distance)
polar :: the polar angle (in radians) away from the +Z axis.
azimuth :: the azimuthal angle (in radians), where 0 points along +X and rotates clockwise in the XY plane
Definition at line 69 of file V3D.cpp.
References Mantid::Kernel::Tolerance.
toMillerIndexes()
double Mantid::Kernel::V3D::toMillerIndexes (double eps = 1.e-3)
transform vector into form, used to describe directions in crystallogaphical coodinate system
Definition at line 423 of file V3D.cpp.
References m_pt, and operator*=().
toString()
std::string Mantid::Kernel::V3D::toString () const
Returns
the vector as a string "X Y Z"
Definition at line 332 of file V3D.cpp.
References write().
Referenced by Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertSpiceMatrixToMomentumMDEvents(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getPeakInformation(), Mantid::DataObjects::Peak::setQLabFrame(), Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration(), and Mantid::Geometry::Component::writeXML().
unitVector()
bool Mantid::Kernel::V3D::unitVector (const double tolerance = Kernel::Tolerance) const noexcept
Definition at line 242 of file V3D.cpp.
References tolerance.
Referenced by Mantid::Geometry::Track::reset(), and Mantid::Geometry::Track::Track().
volume()
double Mantid::Kernel::V3D::volume () const inline noexcept
Calculate the volume of a cube X*Y*Z.
Definition at line 321 of file V3D.h.
write()
void Mantid::Kernel::V3D::write (std::ostream & OX) const
Write out the point values.
Parameters
OX :: Output stream
Definition at line 322 of file V3D.cpp.
Referenced by Mantid::Geometry::Component::appendXML(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), and toString().
X()
constexpr double Mantid::Kernel::V3D::X () const inline constexpr noexcept
Get x.
Definition at line 238 of file V3D.h.
Referenced by Mantid::Geometry::CoplanarChecks::allCoplanar(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::API::WorkspaceNearestNeighbours::build(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::Geometry::CSGObject::calcBoundingBoxByGeometry(), Mantid::Algorithms::GravitySANSHelper::calcComponents(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::MDAlgorithms::CalculateCoverageDGS::calculateIntersections(), Mantid::MDAlgorithms::MDNormDirectSC::calculateIntersections(), Mantid::MDAlgorithms::MDNormSCD::calculateIntersections(), Mantid::MDAlgorithms::MDNorm::calculateIntersections(), ComponentCreationHelper::cappedCylinderXML(), Mantid::Crystal::PredictPeaks::checkBeamDirection(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertToQSample(), WorkspaceCreationHelper::create2DWorkspaceWithReflectometryInstrumentMultiDetector(), Mantid::Algorithms::CreateSampleWorkspace::createCappedCylinder(), Mantid::DataHandling::SetSample::createCylinderLikeXML(), Mantid::DataHandling::SetSample::createFlatPlateXML(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::createHKLMDWorkspace(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::Algorithms::CreateSampleWorkspace::createSphere(), ComponentCreationHelper::cuboidXML(), Mantid::Algorithms::AnnularRingAbsorption::cylinderXML(), Mantid::Algorithms::RectangularBeamProfile::defineActiveRegion(), Mantid::Algorithms::CircularBeamProfile::defineActiveRegion(), Mantid::MDAlgorithms::IntegratePeaksMD::detectorQ(), Mantid::Geometry::SymmetryElementWithAxisGenerator::determineAxis(), Mantid::Geometry::MeshObject2D::distanceToPlane(), Mantid::Geometry::BoundingBox::doesLineIntersect(), Mantid::Algorithms::ApplyCalibration::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Crystal::CalculateUMatrix::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PeaksOnSurface::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::ScaleInstrumentComponent::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), export_V3D(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::Algorithms::WorkspaceBoundingBox::findNewCenterPosition(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::DataObjects::Peak::getAzimuthal(), Mantid::Geometry::ObjComponent::getBoundingBox(), Mantid::Geometry::Cone::getBoundingBox(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::Geometry::HKLGenerator::getEndHKL(), Mantid::Crystal::IntegratePeakTimeSlices::getNeighborPixIDs(), Mantid::Crystal::PeakHKLErrors::getNewInstrument(), Mantid::Geometry::HKLGenerator::getSize(), V3DPickleSuite::getstate(), Mantid::Geometry::ObjComponent::getWidth(), ComponentCreationHelper::hollowCylinderXML(), Mantid::Geometry::MeshObject2D::initialize(), Mantid::Geometry::BoundingBox::isPointInside(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::makeAxisName(), Mantid::DataHandling::LoadILLSANS::moveDetectorDistance(), Mantid::DataHandling::LoadILLSANS::moveDetectorVertical(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::Geometry::AtomPositionsEqual::operator()(), Mantid::Geometry::AtomPositionsLessThan::operator()(), Mantid::Kernel::Matrix< T >::operator*(), Mantid::Algorithms::ParallaxCorrection::performCorrection(), Mantid::API::PanelsSurfaceCalculator::retrievePanelCorners(), Mantid::Algorithms::CylinderAbsorption::sampleXML(), Mantid::Algorithms::FlatPlateAbsorption::sampleXML(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), Mantid::Crystal::SCDCalibratePanels::saveXmlFile(), Mantid::Crystal::SCDCalibratePanels2::saveXmlFile(), Mantid::DataObjects::BasePeak::setHKL(), Mantid::Geometry::Sphere::side(), Mantid::Geometry::ComponentHelper::sphereXML(), ComponentCreationHelper::sphereXML(), Mantid::Geometry::InstrumentDefinitionParser::translateRotateXMLcuboid(), Mantid::Algorithms::Qhelper::waveLengthCutOff(), Mantid::Algorithms::ParabolicWeighting::weightAt(), Mantid::Kernel::withinRelativeDifference< V3D, double >(), and Mantid::DataHandling::SaveStl::writeTriangle().
Y()
constexpr double Mantid::Kernel::V3D::Y () const inline constexpr noexcept
Get y.
Definition at line 239 of file V3D.h.
Referenced by Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::API::WorkspaceNearestNeighbours::build(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::Geometry::CSGObject::calcBoundingBoxByGeometry(), Mantid::Algorithms::GravitySANSHelper::calcComponents(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::MDAlgorithms::CalculateCoverageDGS::calculateIntersections(), Mantid::MDAlgorithms::MDNormDirectSC::calculateIntersections(), Mantid::MDAlgorithms::MDNormSCD::calculateIntersections(), Mantid::MDAlgorithms::MDNorm::calculateIntersections(), ComponentCreationHelper::cappedCylinderXML(), Mantid::Crystal::PredictPeaks::checkBeamDirection(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertToQSample(), WorkspaceCreationHelper::create2DWorkspaceWithReflectometryInstrumentMultiDetector(), Mantid::Algorithms::CreateSampleWorkspace::createCappedCylinder(), Mantid::DataHandling::SetSample::createCylinderLikeXML(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::createHKLMDWorkspace(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::Algorithms::CreateSampleWorkspace::createSphere(), Mantid::Algorithms::AnnularRingAbsorption::cylinderXML(), Mantid::Algorithms::RectangularBeamProfile::defineActiveRegion(), Mantid::Algorithms::CircularBeamProfile::defineActiveRegion(), Mantid::MDAlgorithms::IntegratePeaksMD::detectorQ(), Mantid::Geometry::SymmetryElementWithAxisGenerator::determineAxis(), Mantid::Geometry::MeshObject2D::distanceToPlane(), Mantid::Geometry::BoundingBox::doesLineIntersect(), Mantid::Algorithms::ApplyCalibration::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Crystal::CalculateUMatrix::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PeaksOnSurface::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::ScaleInstrumentComponent::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), export_V3D(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::Algorithms::WorkspaceBoundingBox::findNewCenterPosition(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::DataObjects::Peak::getAzimuthal(), Mantid::Geometry::ObjComponent::getBoundingBox(), Mantid::Geometry::Cone::getBoundingBox(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::Geometry::HKLGenerator::getEndHKL(), Mantid::Geometry::ObjComponent::getHeight(), Mantid::Crystal::IntegratePeakTimeSlices::getNeighborPixIDs(), Mantid::Crystal::PeakHKLErrors::getNewInstrument(), Mantid::Geometry::HKLGenerator::getSize(), V3DPickleSuite::getstate(), ComponentCreationHelper::hollowCylinderXML(), Mantid::Geometry::MeshObject2D::initialize(), Mantid::Geometry::BoundingBox::isPointInside(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::makeAxisName(), Mantid::DataHandling::LoadILLSANS::moveDetectorDistance(), Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::Geometry::AtomPositionsEqual::operator()(), Mantid::Geometry::AtomPositionsLessThan::operator()(), Mantid::Algorithms::ParallaxCorrection::performCorrection(), Mantid::DataHandling::LoadSwans::placeDetectorInSpace(), Mantid::Algorithms::CylinderAbsorption::sampleXML(), Mantid::Algorithms::FlatPlateAbsorption::sampleXML(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), Mantid::Crystal::SCDCalibratePanels::saveXmlFile(), Mantid::Crystal::SCDCalibratePanels2::saveXmlFile(), Mantid::Geometry::Sphere::side(), Mantid::Geometry::ComponentHelper::sphereXML(), ComponentCreationHelper::sphereXML(), Mantid::Geometry::InstrumentDefinitionParser::translateRotateXMLcuboid(), Mantid::Algorithms::Qhelper::waveLengthCutOff(), Mantid::Algorithms::ParabolicWeighting::weightAt(), Mantid::Kernel::withinRelativeDifference< V3D, double >(), and Mantid::DataHandling::SaveStl::writeTriangle().
Z()
constexpr double Mantid::Kernel::V3D::Z () const inline constexpr noexcept
Get z.
Definition at line 240 of file V3D.h.
Referenced by Mantid::DataHandling::AvrgDetector::addDetInfo(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::API::WorkspaceNearestNeighbours::build(), Mantid::API::PanelsSurfaceCalculator::calcBankRotation(), Mantid::Geometry::CSGObject::calcBoundingBoxByGeometry(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackgroundSingleFoil(), Mantid::MDAlgorithms::CalculateCoverageDGS::calculateIntersections(), Mantid::MDAlgorithms::MDNormDirectSC::calculateIntersections(), Mantid::MDAlgorithms::MDNormSCD::calculateIntersections(), Mantid::MDAlgorithms::MDNorm::calculateIntersections(), Mantid::Crystal::IntegratePeakTimeSlices::CalculatePositionSpan(), ComponentCreationHelper::cappedCylinderXML(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertToQSample(), WorkspaceCreationHelper::create2DWorkspaceWithReflectometryInstrumentMultiDetector(), Mantid::Algorithms::CreateSampleWorkspace::createCappedCylinder(), Mantid::DataHandling::SetSample::createCylinderLikeXML(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::createHKLMDWorkspace(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::Crystal::PredictSatellitePeaks::createPeakForOutputWorkspace(), Mantid::Algorithms::CreateSampleWorkspace::createSphere(), Mantid::Algorithms::AnnularRingAbsorption::cylinderXML(), Mantid::Algorithms::RectangularBeamProfile::defineActiveRegion(), Mantid::Algorithms::CircularBeamProfile::defineActiveRegion(), Mantid::MDAlgorithms::IntegratePeaksMD::detectorQ(), Mantid::Geometry::SymmetryElementWithAxisGenerator::determineAxis(), Mantid::Geometry::MeshObject2D::distanceToPlane(), Mantid::Geometry::BoundingBox::doesLineIntersect(), Mantid::Algorithms::ApplyCalibration::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Crystal::CalculateUMatrix::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PeaksOnSurface::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::ScaleInstrumentComponent::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), export_V3D(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::Crystal::IntegratePeakTimeSlices::FindPlane(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::Geometry::ObjComponent::getBoundingBox(), Mantid::Geometry::Cone::getBoundingBox(), Mantid::Geometry::ObjComponent::getDepth(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::Geometry::HKLGenerator::getEndHKL(), Mantid::Crystal::IntegratePeakTimeSlices::getNeighborPixIDs(), Mantid::Crystal::PeakHKLErrors::getNewInstrument(), Mantid::Geometry::HKLGenerator::getSize(), V3DPickleSuite::getstate(), ComponentCreationHelper::hollowCylinderXML(), Mantid::Geometry::MeshObject2D::initialize(), Mantid::Geometry::HKLFilterWavelength::isAllowed(), Mantid::Geometry::BoundingBox::isPointInside(), Mantid::Geometry::RandomPoint::localPointInCylinder(), Mantid::MDAlgorithms::makeAxisName(), Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal(), Mantid::DataHandling::LoadILLSANS::moveDetectorVertical(), Mantid::Geometry::AtomPositionsEqual::operator()(), Mantid::Geometry::AtomPositionsLessThan::operator()(), Mantid::Algorithms::ParallaxCorrection::performCorrection(), Mantid::Geometry::CSGObject::rayTraceSolidAngle(), Mantid::Algorithms::CylinderAbsorption::sampleXML(), Mantid::Algorithms::FlatPlateAbsorption::sampleXML(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), Mantid::Crystal::SCDCalibratePanels::saveXmlFile(), Mantid::Crystal::SCDCalibratePanels2::saveXmlFile(), Mantid::Geometry::Sphere::side(), Mantid::Geometry::ComponentHelper::sphereXML(), ComponentCreationHelper::sphereXML(), Mantid::Geometry::InstrumentDefinitionParser::translateRotateXMLcuboid(), Mantid::Kernel::withinRelativeDifference< V3D, double >(), and Mantid::DataHandling::SaveStl::writeTriangle().
zenith()
double Mantid::Kernel::V3D::zenith (const V3D & v) const noexcept
Zenith (theta) angle between this and another vector.
Calculates the zenith angle (theta) of this vector with respect to another.
Parameters
v :: The other vector
Returns
The azimuthal angle in radians (0 < theta < pi)
Definition at line 147 of file V3D.cpp.
Referenced by export_V3D().
Member Data Documentation
m_pt
std::array<double, 3> Mantid::Kernel::V3D::m_pt private
Definition at line 340 of file V3D.h.
Referenced by absoluteValue(), directionAngles(), hklError(), loadNexus(), maxCoeff(), operator*=(), operator+=(), operator-=(), operator/=(), printSelf(), read(), readPrinted(), round(), saveNexus(), and toMillerIndexes().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/V3D.h
Framework/Kernel/src/V3D.cpp