Mantid: MantidQt::CustomDialogs::MWPropertiesWidget Class Reference
MantidQt::CustomDialogs::MWPropertiesWidget Class Reference
Widgets to set properties for a MatrixWorkspace: WorkspaceIndex, StartX, EndX.
#include <FitDialog.h>
Public Member Functions
void init () override
Initialize the child widgets with stored and allowed values.
MWPropertiesWidget (InputWorkspaceWidget *parent)
Constructor.
void setProperties () override
Set all workspace properties.
Public Member Functions inherited from MantidQt::CustomDialogs::DynamicPropertiesWidget
DynamicPropertiesWidget (InputWorkspaceWidget *parent)
Constructor.
Private Attributes
QLineEdit * m_endX
QSpinBox * m_maxSize
QLineEdit * m_startX
QSpinBox * m_workspaceIndex
Additional Inherited Members
Protected Attributes inherited from MantidQt::CustomDialogs::DynamicPropertiesWidget
InputWorkspaceWidget * m_wsWidget
Parent InputWorkspaceWidget.
Detailed Description
Widgets to set properties for a MatrixWorkspace: WorkspaceIndex, StartX, EndX.
Definition at line 175 of file FitDialog.h.
Constructor & Destructor Documentation
MWPropertiesWidget()
MantidQt::CustomDialogs::MWPropertiesWidget::MWPropertiesWidget (InputWorkspaceWidget * parent)
Constructor.
Definition at line 175 of file FitDialog.cpp.
References MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainType(), MantidQt::CustomDialogs::InputWorkspaceWidget::getWorkspaceName(), m_endX, m_maxSize, m_startX, and m_workspaceIndex.
Member Function Documentation
init()
void MantidQt::CustomDialogs::MWPropertiesWidget::init () override virtual
Initialize the child widgets with stored and allowed values.
Implements MantidQt::CustomDialogs::DynamicPropertiesWidget.
Definition at line 219 of file FitDialog.cpp.
setProperties()
void MantidQt::CustomDialogs::MWPropertiesWidget::setProperties () override virtual
Set all workspace properties.
Implements MantidQt::CustomDialogs::DynamicPropertiesWidget.
Definition at line 224 of file FitDialog.cpp.
References MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainIndex(), MantidQt::CustomDialogs::InputWorkspaceWidget::getDomainType(), m_endX, m_maxSize, m_startX, m_workspaceIndex, MantidQt::CustomDialogs::DynamicPropertiesWidget::m_wsWidget, MantidQt::CustomDialogs::InputWorkspaceWidget::setPropertyValue(), and value.
Member Data Documentation
m_endX
QLineEdit* MantidQt::CustomDialogs::MWPropertiesWidget::m_endX private
Definition at line 189 of file FitDialog.h.
Referenced by MWPropertiesWidget(), and setProperties().
m_maxSize
QSpinBox* MantidQt::CustomDialogs::MWPropertiesWidget::m_maxSize private
Definition at line 190 of file FitDialog.h.
Referenced by MWPropertiesWidget(), and setProperties().
m_startX
QLineEdit* MantidQt::CustomDialogs::MWPropertiesWidget::m_startX private
Definition at line 187 of file FitDialog.h.
Referenced by MWPropertiesWidget(), and setProperties().
m_workspaceIndex
QSpinBox* MantidQt::CustomDialogs::MWPropertiesWidget::m_workspaceIndex private
Definition at line 184 of file FitDialog.h.
Referenced by MWPropertiesWidget(), and setProperties().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/FitDialog.h
qt/widgets/plugins/algorithm_dialogs/src/FitDialog.cpp