Mantid: Mantid::DataHandling::MeshFileIO Class Reference
Mantid::DataHandling::MeshFileIO Class Reference
#include <MeshFileIO.h>
Public Member Functions
Kernel::V3D createScaledV3D (double xVal, double yVal, double zVal)
scales a 3D point according the units defined in the MeshFileIO class
ScaleUnits getScaleType ()
std::shared_ptr< Geometry::MeshObject > rotate (std::shared_ptr< Geometry::MeshObject > environmentMesh, double xRotation, double yRotation, double zRotation)
Rotates the environment by a generated matrix.
std::shared_ptr< Geometry::MeshObject > translate (std::shared_ptr< Geometry::MeshObject > environmentMesh, const std::vector< double > &translationVector)
translates the environment by a provided matrix
Protected Member Functions
MeshFileIO (ScaleUnits scaleType)
MeshFileIO (ScaleUnits scaleType, std::vector< uint32_t > triangles, std::vector< Kernel::V3D > vertices)
float removeScale (double value)
double scaleValue (double val)
void setScaleType (const ScaleUnits scaleType)
Protected Attributes
ScaleUnits m_scaleType
std::vector< uint32_t > m_triangle
std::vector< Kernel::V3D > m_vertices
Detailed Description
Definition at line 23 of file MeshFileIO.h.
Constructor & Destructor Documentation
MeshFileIO() [1/2]
Mantid::DataHandling::MeshFileIO::MeshFileIO (ScaleUnits scaleType) inline protected
Definition at line 35 of file MeshFileIO.h.
MeshFileIO() [2/2]
Mantid::DataHandling::MeshFileIO::MeshFileIO (ScaleUnits scaleType, std::vector< uint32_t > triangles, std::vector< Kernel::V3D > vertices) inline protected
Definition at line 36 of file MeshFileIO.h.
Member Function Documentation
createScaledV3D()
Kernel::V3D Mantid::DataHandling::MeshFileIO::createScaledV3D (double xVal, double yVal, double zVal)
scales a 3D point according the units defined in the MeshFileIO class
Parameters
xVal The x coordinate to be scaled
yVal The y coordinate to be scaled
zVal The z coordinate to be scaled
Returns
a 3D vector containing the scaled coordinates
Definition at line 53 of file MeshFileIO.cpp.
References scaleValue().
Referenced by Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::DataHandling::LoadOff::readOFFVertices(), Mantid::DataHandling::LoadAsciiStl::readSTLVertex(), Mantid::DataHandling::LoadBinaryStl::readTriangle(), and translate().
getScaleType()
ScaleUnits Mantid::DataHandling::MeshFileIO::getScaleType () inline
Definition at line 32 of file MeshFileIO.h.
removeScale()
float Mantid::DataHandling::MeshFileIO::removeScale (double value) inline protected
Definition at line 50 of file MeshFileIO.h.
References value.
Referenced by Mantid::DataHandling::SaveStl::writeTriangle().
rotate()
std::shared_ptr< Geometry::MeshObject > Mantid::DataHandling::MeshFileIO::rotate (std::shared_ptr< Geometry::MeshObject > environmentMesh, double xRotation, double yRotation, double zRotation)
Rotates the environment by a generated matrix.
Parameters
environmentMesh The environment to rotate
xRotation The x rotation required in radians
yRotation The y rotation required in radians
zRotation The z rotation required in radians
Returns
a shared pointer to the newly rotated environment
Definition at line 20 of file MeshFileIO.cpp.
References Mantid::Geometry::ShapeFactory::generateMatrix().
scaleValue()
double Mantid::DataHandling::MeshFileIO::scaleValue (double val) inline protected
Definition at line 39 of file MeshFileIO.h.
Referenced by createScaledV3D(), and Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject().
setScaleType()
void Mantid::DataHandling::MeshFileIO::setScaleType (const ScaleUnits scaleType) inline protected
Definition at line 67 of file MeshFileIO.h.
Referenced by Mantid::DataHandling::Mantid3MFFileIO::LoadFile().
translate()
std::shared_ptr< Geometry::MeshObject > Mantid::DataHandling::MeshFileIO::translate (std::shared_ptr< Geometry::MeshObject > environmentMesh, const std::vector< double > & translationVector)
translates the environment by a provided matrix
Parameters
environmentMesh The environment to translate
translationVector The 3D translation to apply
Returns
a shared pointer to the newly translated environment
Definition at line 33 of file MeshFileIO.cpp.
References createScaledV3D(), and translate().
Referenced by translate().
Member Data Documentation
m_scaleType
ScaleUnits Mantid::DataHandling::MeshFileIO::m_scaleType protected
Definition at line 63 of file MeshFileIO.h.
Referenced by Mantid::DataHandling::SaveStl::writeHeader().
m_triangle
std::vector<uint32_t> Mantid::DataHandling::MeshFileIO::m_triangle protected
Definition at line 64 of file MeshFileIO.h.
Referenced by Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::DataHandling::LoadOff::readOFFMeshObject(), Mantid::DataHandling::LoadOff::readOFFTriangles(), Mantid::DataHandling::LoadAsciiStl::readShape(), Mantid::DataHandling::LoadBinaryStl::readShape(), Mantid::DataHandling::LoadBinaryStl::readTriangle(), Mantid::DataHandling::SaveStl::writeStl(), and Mantid::DataHandling::SaveStl::writeTriangle().
m_vertices
std::vector<Kernel::V3D> Mantid::DataHandling::MeshFileIO::m_vertices protected
Definition at line 65 of file MeshFileIO.h.
Referenced by Mantid::DataHandling::LoadStl::changeToVector(), Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::DataHandling::LoadOff::readOFFMeshObject(), Mantid::DataHandling::LoadOff::readOFFVertices(), Mantid::DataHandling::LoadAsciiStl::readShape(), Mantid::DataHandling::LoadBinaryStl::readShape(), and Mantid::DataHandling::SaveStl::writeTriangle().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/MeshFileIO.h
Framework/DataHandling/src/MeshFileIO.cpp