Mantid: Mantid::DataObjects::BoxControllerNeXusIO Class Reference
Mantid::DataObjects::BoxControllerNeXusIO Class Reference
The class responsible for saving events into nexus file using generic box controller interface Expected to provide thread-safe file access.
#include <BoxControllerNeXusIO.h>
Public Types
enum class EventDataVersion : size_t { EDVLean = 2 , EDVOriginal = 4 , EDVGoniometer = 5 }
The version of the "event_data" Nexus dataset.
Public Types inherited from Mantid::Kernel::DiskBuffer
using freeSpace_bySize_t = freeSpace_t::nth_index< 1 >::type
A way to index the free space by their size.
using freeSpace_t = boost::multi_index::multi_index_container< FreeBlock, boost::multi_index::indexed_by< boost::multi_index::ordered_non_unique< ::boost::multi_index::const_mem_fun< FreeBlock, uint64_t, &FreeBlock::getFilePosition > >, boost::multi_index::ordered_non_unique< ::boost::multi_index::const_mem_fun< FreeBlock, uint64_t, &FreeBlock::getSize > > > >
A map for the list of free space blocks in the file.
Public Member Functions
template<typename FloatOrDouble >
void adjustEventDataBlock (std::vector< FloatOrDouble > &Block, const std::string &accessMode) const
Insert goniometer info in a block of event data, if necessary.
BoxControllerNeXusIO (API::BoxController *const bc)
Constructor.
void closeFile () override
flush disk buffer data from memory and close underlying NeXus file
void copyFileTo (const std::string &destFilename) override
Copy the file contents to a new location.
uint64_t dataEventCount (void) const
Number of data items in Nexus dataset "data_event" associated with the particular event data version.
void flushData () const override
Clear NeXus internal cache.
size_t getDataChunk () const override
Return the size of the NeXus data block used in NeXus data array.
void getDataType (size_t &CoordSize, std::string &typeName) const override
As save/load operations use void data type, these function allow set up/get the type name provided for the IO operations and the size of the data type in bytes (e.g.
EventDataVersion getEventDataVersion () const
Nexus::File * getFile ()
const std::string & getFileName () const override
get the full file name of the file used for IO operations
int64_t getNDataColums () const
bool isOpened () const override
void loadBlock (std::vector< double > &, const uint64_t, const size_t) const override
Load double data block from the opened NeXus file.
void loadBlock (std::vector< float > &, const uint64_t, const size_t) const override
Load float data block from the opened NeXus file.
bool openFile (const std::string &fileName, const std::string &mode) override
Open the file to use in IO operations with events.
void saveBlock (const std::vector< double > &, const uint64_t) const override
Save double precision data block on specific position within properly opened NeXus data array.
void saveBlock (const std::vector< float > &, const uint64_t) const override
Save float data block on specific position within properly opened NeXus data array.
void setDataType (const size_t blockSize, const std::string &typeName) override
The optional method to set up the event type and the size of the event coordinate As save/load operations use void data type, these function allow set up/get the type name provided for the IO operations and the size of the data type in bytes (e.g.
void setEventDataVersion (const EventDataVersion &version)
void setEventDataVersion (const size_t &traitsCount)
set the data version based on the number of attributes of the event, not counting its coordinates.
~BoxControllerNeXusIO () override
Public Member Functions inherited from Mantid::Kernel::DiskBuffer
uint64_t allocate (uint64_t const newSize)
Allocate a block of the given size in a free spot in the file, or at the end of the file if there is no space.
void defragFreeBlocks ()
Method that defrags free blocks by combining adjacent ones together NOTE: This is not necessary to run since the freeBlock() methods automatically defrags neighboring blocks.
DiskBuffer ()
Constructor.
DiskBuffer (const DiskBuffer &)=delete
DiskBuffer (uint64_t m_writeBufferSize)
Constructor.
void flushCache ()
Flush out all the data in the memory; and writes out everything in the to-write cache.
void freeBlock (uint64_t const pos, uint64_t const size)
This method is called by this->relocate when object that has shrunk and so has left a bit of free space after itself on the file; or when an object gets moved to a new spot.
uint64_t getFileLength () const
freeSpace_t & getFreeSpaceMap ()
void getFreeSpaceVector (std::vector< uint64_t > &free) const
Returns a vector with two entries per free block: position and size.
std::string getMemoryStr () const
uint64_t getWriteBufferSize () const
uint64_t getWriteBufferUsed () const
void objectDeleted (ISaveable *item)
Call this method when an object that might be in the cache is getting deleted.
DiskBuffer & operator= (const DiskBuffer &)=delete
uint64_t relocate (uint64_t const oldPos, uint64_t const oldSize, const uint64_t newSize)
This method is called by an ISaveable object that has outgrown its space allocated on file and needs to relocate.
void setFileLength (const uint64_t length) const
Set the length of the file that this MRU writes to.
void setFreeSpaceVector (std::vector< uint64_t > const &free)
Sets the free space map.
void setWriteBufferSize (uint64_t buffer)
Set the size of the to-write buffer, in number of events.
void toWrite (ISaveable *item)
Call this method when an object is ready to be written out to disk.
virtual ~DiskBuffer ()=default
Private Types
enum { DATA_CHUNK = 10000 }
Default size of the events block which can be written in the NeXus array at once identified by efficiency or some other external reasons.
enum CoordConversion { noConversion , floatToDouble , doubleToFolat }
the enum, which suggests the way (currently)two possible data types are converted to each other
enum EventType { LeanEvent = 0 , FatEvent = 1 }
possible event types this class understands.
Private Member Functions
void CreateEventGroup ()
Create group responsible for keeping events and add necessary attributes to it.
void getDiskBufferFileData ()
Load free space blocks from the data file or create the NeXus place to read/write them.
template<typename Type >
void loadGenericBlock (std::vector< Type > &Block, const uint64_t blockPosition, const size_t nPoints) const
Load generic data block from the opened NeXus file.
void OpenAndCheckEventGroup ()
Open existing Event group and check the attributes necessary for this algorithm to work.
void prepareNxSdata_CurVersion ()
Open the NXS data blocks for loading/saving.
void prepareNxSToWrite_CurVersion ()
Helper function which prepares NeXus event structure to accept events
template<typename Type >
void saveGenericBlock (const std::vector< Type > &DataBlock, const uint64_t blockPosition) const
Save generc data block on specific position within properly opened NeXus data array.
Static Private Member Functions
static EventType TypeFromString (const std::vector< std::string > &typesSupported, const std::string &typeName)
get event type form its string representation
Private Attributes
API::BoxController *const m_bc
shared pointer to the box controller, which is repsoponsible for this IO
Nexus::DimVector m_BlockSize
the vector, which describes the event specific data size, namely how many column an event is composed into and this class reads/writres
Nexus::DimVector m_BlockStart
the start of the current data block to read from.
unsigned int m_CoordSize
number of bytes in the event coordinates (coord_t length).
size_t m_dataChunk
The size of the events block which can be written in the neXus array at once (continuous part of the data block)
EventDataVersion m_EventDataVersion
"data_event" dataset version in the current Nexus file
std::vector< std::string > m_EventsTypeHeaders
data headers used for different events types
std::vector< std::string > m_EventsTypesSupported
the symbolic description of the event types currently supported by the class
std::string m_EventsVersion
The version of the md events data block.
enum Mantid::DataObjects::BoxControllerNeXusIO::EventType m_EventType
std::unique_ptr< Nexus::File > m_File
the file Handler responsible for Nexus IO operations;
std::mutex m_fileMutex
lock Nexus file operations as Nexus is not thread safe
std::string m_fileName
full file name (with path) of the Nexis file responsible for the IO operations (as NeXus filename has very strange properties and often truncated to 64 bytes)
enum Mantid::DataObjects::BoxControllerNeXusIO::CoordConversion m_ReadConversion
bool m_ReadOnly
identifier if the file open only for reading or is in read/write
Static Private Attributes
static std::string g_DBDataName
the group name to save disk buffer data
static std::string g_EventGroupName
the name of the Nexus data group for saving the events
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::DiskBuffer
void writeOldObjects ()
Method to write out the old objects that have been stored in the "toWrite" buffer.
Protected Attributes inherited from Mantid::Kernel::DiskBuffer
uint64_t m_fileLength
Length of the file. This is where new blocks that don't fit get placed.
freeSpace_t m_free
Map of the free blocks in the file.
freeSpace_bySize_t & m_free_bySize
Index into m_free, but indexed by block size.
std::mutex m_freeMutex
Mutex for modifying the free space list.
std::mutex m_mutex
Mutex for modifying the toWrite buffer.
size_t m_nObjectsToWrite
number of objects stored in to write buffer list
std::list< ISaveable * > m_toWriteBuffer
A forward list for the buffer of "toWrite" objects.
size_t m_writeBufferSize
Do we use the write buffer? Always now.
size_t m_writeBufferUsed
Total amount of memory in the "toWrite" buffer.
Detailed Description
The class responsible for saving events into nexus file using generic box controller interface Expected to provide thread-safe file access.
Date
March 15, 2013
Definition at line 26 of file BoxControllerNeXusIO.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Default size of the events block which can be written in the NeXus array at once identified by efficiency or some other external reasons.
Enumerator
DATA_CHUNK
Definition at line 112 of file BoxControllerNeXusIO.h.
CoordConversion
enum Mantid::DataObjects::BoxControllerNeXusIO::CoordConversion private
the enum, which suggests the way (currently)two possible data types are converted to each other
Enumerator
noConversion
floatToDouble
doubleToFolat
conversion btween fload/double requested by the client
Definition at line 180 of file BoxControllerNeXusIO.h.
EventDataVersion
enum class Mantid::DataObjects::BoxControllerNeXusIO::EventDataVersion : size_t strong
The version of the "event_data" Nexus dataset.
The "event_data" Nexus dataset may contain all or only a subset of the attributes of the current event object.
| class | attributes stored (besides coordinates)
MDLeanEvent | signal, error MDEvent | signal, error, run-index, detector-index MDEvent | signal, error, run-index, goniometer-index, detector-index
The number of attributes stored (neglecting coordinates) define the version
Enumerator
EDVLean
EDVOriginal
EDVGoniometer
Definition at line 76 of file BoxControllerNeXusIO.h.
EventType
enum Mantid::DataObjects::BoxControllerNeXusIO::EventType private
possible event types this class understands.
The enum numbers have to correspond to the numbers of symbolic event types, defined in EVENT_TYPES_SUPPORTED vector
Enumerator
LeanEvent
FatEvent
Definition at line 145 of file BoxControllerNeXusIO.h.
Constructor & Destructor Documentation
BoxControllerNeXusIO()
Mantid::DataObjects::BoxControllerNeXusIO::BoxControllerNeXusIO (API::BoxController *const bc)
Constructor.
Parameters
bc shared pointer to the box controller which uses this IO operations
Definition at line 36 of file BoxControllerNeXusIO.cpp.
References Mantid::DataObjects::EventHeaders, FatEvent, Mantid::API::BoxController::getNDims(), Mantid::DataObjects::MDEvent< nd >::getTypeName(), Mantid::DataObjects::MDLeanEvent< nd >::getTypeName(), LeanEvent, m_bc, m_BlockSize, m_EventsTypeHeaders, and m_EventsTypesSupported.
~BoxControllerNeXusIO()
Mantid::DataObjects::BoxControllerNeXusIO::~BoxControllerNeXusIO () override
Definition at line 603 of file BoxControllerNeXusIO.cpp.
References closeFile().
Member Function Documentation
adjustEventDataBlock()
template<typename FloatOrDouble > template DLLExport void Mantid::DataObjects::BoxControllerNeXusIO::adjustEventDataBlock< double > (std::vector< FloatOrDouble > & Block, const std::string & accessMode) const
Insert goniometer info in a block of event data, if necessary.
The dataset "event_data" in old Nexus files lack goniometer info, thus it's necessary to insert the default goniometerIndex value into a data-block that has been read from the file before it's consumed by MDEvent::dataToEvents()
Parameters
Block : the storage vector containing the event data
accessMode : string specifying if we're reading from or writing to file. Valid values are "READ" and "WRITE"
Definition at line 413 of file BoxControllerNeXusIO.cpp.
References dataEventCount(), EDVGoniometer, EDVLean, EDVOriginal, and m_EventDataVersion.
Referenced by loadGenericBlock().
closeFile()
void Mantid::DataObjects::BoxControllerNeXusIO::closeFile () override virtual
flush disk buffer data from memory and close underlying NeXus file
Implements Mantid::API::IBoxControllerIO.
Definition at line 576 of file BoxControllerNeXusIO.cpp.
References Mantid::Kernel::DiskBuffer::flushCache(), g_DBDataName, Mantid::Kernel::DiskBuffer::getFreeSpaceVector(), m_File, m_fileMutex, and m_ReadOnly.
Referenced by copyFileTo(), and ~BoxControllerNeXusIO().
copyFileTo()
void Mantid::DataObjects::BoxControllerNeXusIO::copyFileTo (const std::string & destFilename) override virtual
Copy the file contents to a new location.
Copy the underlying file to the given destination.
If the file is opened and locked then it is closed, the copy made and the file is reopened again with the same mode
Parameters
destFilename A filepath to copy the file to.
Implements Mantid::API::IBoxControllerIO.
Definition at line 173 of file BoxControllerNeXusIO.cpp.
References closeFile(), getFileName(), m_ReadOnly, and openFile().
CreateEventGroup()
void Mantid::DataObjects::BoxControllerNeXusIO::CreateEventGroup () private
Create group responsible for keeping events and add necessary attributes to it.
Definition at line 195 of file BoxControllerNeXusIO.cpp.
References g_EventGroupName, m_EventsVersion, m_File, m_fileName, and m_ReadOnly.
Referenced by openFile().
dataEventCount()
uint64_t Mantid::DataObjects::BoxControllerNeXusIO::dataEventCount (void) const
Number of data items in Nexus dataset "data_event" associated with the particular event data version.
Definition at line 394 of file BoxControllerNeXusIO.cpp.
References EDVGoniometer, EDVLean, EDVOriginal, m_BlockSize, and m_EventDataVersion.
Referenced by adjustEventDataBlock(), and loadGenericBlock().
flushData()
void Mantid::DataObjects::BoxControllerNeXusIO::flushData () const override virtual
Clear NeXus internal cache.
Implements Mantid::API::IBoxControllerIO.
Definition at line 571 of file BoxControllerNeXusIO.cpp.
References m_File, and m_fileMutex.
getDataChunk()
size_t Mantid::DataObjects::BoxControllerNeXusIO::getDataChunk () const inline override virtual
Return the size of the NeXus data block used in NeXus data array.
Implements Mantid::API::IBoxControllerIO.
Definition at line 38 of file BoxControllerNeXusIO.h.
getDataType()
void Mantid::DataObjects::BoxControllerNeXusIO::getDataType (size_t & CoordSize, std::string & typeName) const override virtual
As save/load operations use void data type, these function allow set up/get the type name provided for the IO operations and the size of the data type in bytes (e.g.
the class dependent physical meaning of the blockSize and blockPosition used by save/load operations
Parameters
CoordSize – size (in bytes) of the blockPosition and blockSize used in save/load operations
typeName – the name of the event used in the operations. The name itself defines the size and the format of the event
Implements Mantid::API::IBoxControllerIO.
Definition at line 105 of file BoxControllerNeXusIO.cpp.
References m_CoordSize, m_EventsTypesSupported, and m_EventType.
Referenced by setEventDataVersion().
getDiskBufferFileData()
void Mantid::DataObjects::BoxControllerNeXusIO::getDiskBufferFileData () private
Load free space blocks from the data file or create the NeXus place to read/write them.
Definition at line 291 of file BoxControllerNeXusIO.cpp.
References g_DBDataName, Mantid::Kernel::DiskBuffer::getFreeSpaceVector(), m_dataChunk, m_File, m_fileName, m_ReadOnly, and Mantid::Kernel::DiskBuffer::setFreeSpaceVector().
Referenced by openFile().
getEventDataVersion()
EventDataVersion Mantid::DataObjects::BoxControllerNeXusIO::getEventDataVersion () const inline
Definition at line 78 of file BoxControllerNeXusIO.h.
getFile()
Nexus::File * Mantid::DataObjects::BoxControllerNeXusIO::getFile () inline
Definition at line 61 of file BoxControllerNeXusIO.h.
getFileName()
const std::string & Mantid::DataObjects::BoxControllerNeXusIO::getFileName () const inline override virtual
get the full file name of the file used for IO operations
Implements Mantid::API::IBoxControllerIO.
Definition at line 33 of file BoxControllerNeXusIO.h.
Referenced by copyFileTo().
getNDataColums()
int64_t Mantid::DataObjects::BoxControllerNeXusIO::getNDataColums () const inline
Definition at line 59 of file BoxControllerNeXusIO.h.
isOpened()
bool Mantid::DataObjects::BoxControllerNeXusIO::isOpened () const inline override virtual
Returns
true if the file to write events is opened and false otherwise
Implements Mantid::API::IBoxControllerIO.
Definition at line 31 of file BoxControllerNeXusIO.h.
loadBlock() [1/2]
void Mantid::DataObjects::BoxControllerNeXusIO::loadBlock (std::vector< double > & Block, const uint64_t blockPosition, const size_t nPoints) const override virtual
Load double data block from the opened NeXus file.
Parameters
Block – the storage vector to place data into
blockPosition – The starting place to read data from
nPoints – number of data points (events) to read
Implements Mantid::API::IBoxControllerIO.
Definition at line 552 of file BoxControllerNeXusIO.cpp.
References Mantid::DataObjects::convertFormats(), floatToDouble, loadGenericBlock(), m_fileName, m_ReadConversion, noConversion, and tmp.
loadBlock() [2/2]
void Mantid::DataObjects::BoxControllerNeXusIO::loadBlock (std::vector< float > & Block, const uint64_t blockPosition, const size_t nPoints) const override virtual
Load float data block from the opened NeXus file.
Parameters
Block – the storage vector to place data into
blockPosition – The starting place to read data from
nPoints – number of data points (events) to read
Implements Mantid::API::IBoxControllerIO.
Definition at line 532 of file BoxControllerNeXusIO.cpp.
References Mantid::DataObjects::convertFormats(), doubleToFolat, loadGenericBlock(), m_fileName, m_ReadConversion, noConversion, and tmp.
loadGenericBlock()
template<typename Type > void Mantid::DataObjects::BoxControllerNeXusIO::loadGenericBlock (std::vector< Type > & Block, const uint64_t blockPosition, const size_t nPoints) const private
Load generic data block from the opened NeXus file.
Definition at line 500 of file BoxControllerNeXusIO.cpp.
References adjustEventDataBlock(), dataEventCount(), Mantid::Kernel::DiskBuffer::getFileLength(), m_BlockSize, m_File, m_fileMutex, and m_fileName.
Referenced by loadBlock(), and loadBlock().
OpenAndCheckEventGroup()
void Mantid::DataObjects::BoxControllerNeXusIO::OpenAndCheckEventGroup () private
Open existing Event group and check the attributes necessary for this algorithm to work.
Definition at line 210 of file BoxControllerNeXusIO.cpp.
References g_EventGroupName, m_EventsVersion, m_File, and m_fileName.
Referenced by openFile().
openFile()
bool Mantid::DataObjects::BoxControllerNeXusIO::openFile (const std::string & fileName, const std::string & mode) override virtual
Open the file to use in IO operations with events.
Parameters
fileName – the name of the file to open. Search for file performed within the Mantid search path.
mode – opening mode (read or read/write)
Implements Mantid::API::IBoxControllerIO.
Definition at line 118 of file BoxControllerNeXusIO.cpp.
References CreateEventGroup(), Mantid::DataObjects::MDBoxFlatTree::createOrOpenMDWSgroup(), g_EventGroupName, getDiskBufferFileData(), Mantid::API::BoxController::getNDims(), m_bc, m_EventsTypesSupported, m_EventType, m_File, m_fileMutex, m_fileName, m_ReadOnly, OpenAndCheckEventGroup(), prepareNxSdata_CurVersion(), and prepareNxSToWrite_CurVersion().
Referenced by copyFileTo().
prepareNxSdata_CurVersion()
void Mantid::DataObjects::BoxControllerNeXusIO::prepareNxSdata_CurVersion () private
Open the NXS data blocks for loading/saving.
The data should have been created before.
Definition at line 256 of file BoxControllerNeXusIO.cpp.
References Mantid::Nexus::Info::dims, doubleToFolat, NXnumtype::FLOAT32, NXnumtype::FLOAT64, floatToDouble, Mantid::API::BoxController::getNDims(), m_bc, m_CoordSize, m_File, m_fileName, m_ReadConversion, noConversion, setEventDataVersion(), Mantid::Kernel::DiskBuffer::setFileLength(), and Mantid::Nexus::Info::type.
Referenced by openFile(), and prepareNxSToWrite_CurVersion().
prepareNxSToWrite_CurVersion()
void Mantid::DataObjects::BoxControllerNeXusIO::prepareNxSToWrite_CurVersion () private
Helper function which prepares NeXus event structure to accept events
Definition at line 223 of file BoxControllerNeXusIO.cpp.
References NXnumtype::FLOAT32, NXnumtype::FLOAT64, m_BlockSize, m_CoordSize, m_dataChunk, m_EventsTypeHeaders, m_EventType, m_File, NONE, NX_UNLIMITED(), prepareNxSdata_CurVersion(), and Mantid::Kernel::DiskBuffer::setFileLength().
Referenced by openFile().
saveBlock() [1/2]
void Mantid::DataObjects::BoxControllerNeXusIO::saveBlock (const std::vector< double > & DataBlock, const uint64_t blockPosition) const override virtual
Save double precision data block on specific position within properly opened NeXus data array.
Parameters
DataBlock – the vector with data to write
blockPosition – The starting place to save data to
Implements Mantid::API::IBoxControllerIO.
Definition at line 356 of file BoxControllerNeXusIO.cpp.
References saveGenericBlock().
saveBlock() [2/2]
void Mantid::DataObjects::BoxControllerNeXusIO::saveBlock (const std::vector< float > & DataBlock, const uint64_t blockPosition) const override virtual
Save float data block on specific position within properly opened NeXus data array.
Parameters
DataBlock – the vector with data to write
blockPosition – The starting place to save data to
Implements Mantid::API::IBoxControllerIO.
Definition at line 349 of file BoxControllerNeXusIO.cpp.
References saveGenericBlock().
saveGenericBlock()
template<typename Type > void Mantid::DataObjects::BoxControllerNeXusIO::saveGenericBlock (const std::vector< Type > & DataBlock, const uint64_t blockPosition) const private
Save generc data block on specific position within properly opened NeXus data array.
Parameters
DataBlock – the vector with data to write
blockPosition – The starting place to save data to
Definition at line 324 of file BoxControllerNeXusIO.cpp.
References Mantid::Kernel::DiskBuffer::getFileLength(), m_BlockSize, m_File, m_fileMutex, and Mantid::Kernel::DiskBuffer::setFileLength().
Referenced by saveBlock(), and saveBlock().
setDataType()
void Mantid::DataObjects::BoxControllerNeXusIO::setDataType (const size_t blockSize, const std::string & typeName) override virtual
The optional method to set up the event type and the size of the event coordinate As save/load operations use void data type, these function allow set up/get the type name provided for the IO operations and the size of the data type in bytes (e.g.
the class dependent physical meaning of the blockSize and blockPosition used by save/load operations
Parameters
blockSize – size (in bytes) of the blockPosition and blockSize used in save/load operations. 4 and 8 are supported only e.g. float and double
typeName – the name of the event used in the operations. The name itself defines the size and the format of the event The events described in the class header are supported only
Implements Mantid::API::IBoxControllerIO.
Definition at line 71 of file BoxControllerNeXusIO.cpp.
References EDVGoniometer, EDVLean, FatEvent, Mantid::API::BoxController::getNDims(), LeanEvent, m_bc, m_BlockSize, m_CoordSize, m_EventsTypesSupported, m_EventType, setEventDataVersion(), and TypeFromString().
setEventDataVersion() [1/2]
void Mantid::DataObjects::BoxControllerNeXusIO::setEventDataVersion (const EventDataVersion & version)
Definition at line 360 of file BoxControllerNeXusIO.cpp.
References getDataType(), and m_EventDataVersion.
Referenced by prepareNxSdata_CurVersion(), setDataType(), and setEventDataVersion().
setEventDataVersion() [2/2]
void Mantid::DataObjects::BoxControllerNeXusIO::setEventDataVersion (const size_t & traitsCount)
set the data version based on the number of attributes of the event, not counting its coordinates.
Definition at line 379 of file BoxControllerNeXusIO.cpp.
References setEventDataVersion().
TypeFromString()
BoxControllerNeXusIO::EventType Mantid::DataObjects::BoxControllerNeXusIO::TypeFromString (const std::vector< std::string > & typesSupported, const std::string & typeName) static private
get event type form its string representation
Definition at line 49 of file BoxControllerNeXusIO.cpp.
Referenced by setDataType().
Member Data Documentation
g_DBDataName
std::string Mantid::DataObjects::BoxControllerNeXusIO::g_DBDataName static private
the group name to save disk buffer data
Definition at line 167 of file BoxControllerNeXusIO.h.
Referenced by closeFile(), and getDiskBufferFileData().
g_EventGroupName
std::string Mantid::DataObjects::BoxControllerNeXusIO::g_EventGroupName static private
the name of the Nexus data group for saving the events
Definition at line 165 of file BoxControllerNeXusIO.h.
Referenced by CreateEventGroup(), OpenAndCheckEventGroup(), and openFile().
m_bc
API::BoxController* const Mantid::DataObjects::BoxControllerNeXusIO::m_bc private
shared pointer to the box controller, which is repsoponsible for this IO
Definition at line 126 of file BoxControllerNeXusIO.h.
Referenced by BoxControllerNeXusIO(), openFile(), prepareNxSdata_CurVersion(), and setDataType().
m_BlockSize
Nexus::DimVector Mantid::DataObjects::BoxControllerNeXusIO::m_BlockSize private
the vector, which describes the event specific data size, namely how many column an event is composed into and this class reads/writres
Definition at line 133 of file BoxControllerNeXusIO.h.
Referenced by BoxControllerNeXusIO(), dataEventCount(), loadGenericBlock(), prepareNxSToWrite_CurVersion(), saveGenericBlock(), and setDataType().
m_BlockStart
Nexus::DimVector Mantid::DataObjects::BoxControllerNeXusIO::m_BlockStart private
the start of the current data block to read from.
It related to current physical representation of the data in NeXus file
Definition at line 130 of file BoxControllerNeXusIO.h.
m_CoordSize
unsigned int Mantid::DataObjects::BoxControllerNeXusIO::m_CoordSize private
number of bytes in the event coordinates (coord_t length).
Set by setDataType but can be defined statically with coord_t
Definition at line 141 of file BoxControllerNeXusIO.h.
Referenced by getDataType(), prepareNxSdata_CurVersion(), prepareNxSToWrite_CurVersion(), and setDataType().
m_dataChunk
size_t Mantid::DataObjects::BoxControllerNeXusIO::m_dataChunk private
The size of the events block which can be written in the neXus array at once (continuous part of the data block)
Definition at line 124 of file BoxControllerNeXusIO.h.
Referenced by getDiskBufferFileData(), and prepareNxSToWrite_CurVersion().
m_EventDataVersion
EventDataVersion Mantid::DataObjects::BoxControllerNeXusIO::m_EventDataVersion private
"data_event" dataset version in the current Nexus file
Definition at line 156 of file BoxControllerNeXusIO.h.
Referenced by adjustEventDataBlock(), dataEventCount(), and setEventDataVersion().
m_EventsTypeHeaders
std::vector<std::string> Mantid::DataObjects::BoxControllerNeXusIO::m_EventsTypeHeaders private
data headers used for different events types
Definition at line 162 of file BoxControllerNeXusIO.h.
Referenced by BoxControllerNeXusIO(), and prepareNxSToWrite_CurVersion().
m_EventsTypesSupported
std::vector<std::string> Mantid::DataObjects::BoxControllerNeXusIO::m_EventsTypesSupported private
the symbolic description of the event types currently supported by the class
Definition at line 160 of file BoxControllerNeXusIO.h.
Referenced by BoxControllerNeXusIO(), getDataType(), openFile(), and setDataType().
m_EventsVersion
std::string Mantid::DataObjects::BoxControllerNeXusIO::m_EventsVersion private
The version of the md events data block.
Definition at line 153 of file BoxControllerNeXusIO.h.
Referenced by CreateEventGroup(), and OpenAndCheckEventGroup().
m_EventType
enum Mantid::DataObjects::BoxControllerNeXusIO::EventType Mantid::DataObjects::BoxControllerNeXusIO::m_EventType private
Referenced by getDataType(), openFile(), prepareNxSToWrite_CurVersion(), and setDataType().
m_File
std::unique_ptr<Nexus::File> Mantid::DataObjects::BoxControllerNeXusIO::m_File private
the file Handler responsible for Nexus IO operations;
Definition at line 119 of file BoxControllerNeXusIO.h.
Referenced by closeFile(), CreateEventGroup(), flushData(), getDiskBufferFileData(), loadGenericBlock(), OpenAndCheckEventGroup(), openFile(), prepareNxSdata_CurVersion(), prepareNxSToWrite_CurVersion(), and saveGenericBlock().
m_fileMutex
std::mutex Mantid::DataObjects::BoxControllerNeXusIO::m_fileMutex mutable private
lock Nexus file operations as Nexus is not thread safe
Definition at line 135 of file BoxControllerNeXusIO.h.
Referenced by closeFile(), flushData(), loadGenericBlock(), openFile(), and saveGenericBlock().
m_fileName
std::string Mantid::DataObjects::BoxControllerNeXusIO::m_fileName private
full file name (with path) of the Nexis file responsible for the IO operations (as NeXus filename has very strange properties and often truncated to 64 bytes)
Definition at line 117 of file BoxControllerNeXusIO.h.
Referenced by CreateEventGroup(), getDiskBufferFileData(), loadBlock(), loadBlock(), loadGenericBlock(), OpenAndCheckEventGroup(), openFile(), and prepareNxSdata_CurVersion().
m_ReadConversion
enum Mantid::DataObjects::BoxControllerNeXusIO::CoordConversion Mantid::DataObjects::BoxControllerNeXusIO::m_ReadConversion private
Referenced by loadBlock(), loadBlock(), and prepareNxSdata_CurVersion().
m_ReadOnly
bool Mantid::DataObjects::BoxControllerNeXusIO::m_ReadOnly private
identifier if the file open only for reading or is in read/write
Definition at line 121 of file BoxControllerNeXusIO.h.
Referenced by closeFile(), copyFileTo(), CreateEventGroup(), getDiskBufferFileData(), and openFile().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/BoxControllerNeXusIO.h
Framework/DataObjects/src/BoxControllerNeXusIO.cpp