Mantid: Mantid::API::FunctionValues Class Reference
Mantid::API::FunctionValues Class Reference
A class to store values calculated by a function.
#include <FunctionValues.h>
Public Member Functions
void addToCalculated (size_t i, double value)
Add a number to a calculated value.
void addToCalculated (size_t start, const FunctionValues &values)
Add other calculated values with offset.
void expand (size_t n)
Expand values to a new size, preserve stored values.
FunctionValues (const FunctionDomain &domain)
Constructor.
FunctionValues (size_t n=0)
Constructor.
double getCalculated (size_t i) const
Get i-th calculated value.
double getFitData (size_t i) const
Get a fitting data value.
double getFitWeight (size_t i) const
Get a fitting weight.
double * getPointerToCalculated (size_t i)
Get a pointer to calculated data at index i.
FunctionValues & operator*= (const FunctionValues &values)
Multiply by other calculated values.
FunctionValues & operator+= (const FunctionValues &values)
Add other calculated values.
double operator[] (size_t i) const
Get i-th calculated value.
void reset (const FunctionDomain &domain)
Reset the values to match a new domain.
void setCalculated (double value)
set all calculated values to same number
void setCalculated (size_t i, double value)
Store i-th calculated value.
void setFitData (const std::vector< double > &values)
Set all fitting data values.
void setFitData (size_t i, double value)
Set a fitting data value.
void setFitDataFromCalculated (const FunctionValues &values)
Set all calculated values by copying them from another FunctionValues instance.
void setFitWeight (size_t i, double value)
Set a fitting weight.
void setFitWeights (const double &value)
Set all fitting weights to a number.
void setFitWeights (const std::vector< double > &values)
Set all fitting weights.
size_t size () const
Return the number of values.
std::vector< double > toVector () const
Return the calculated values as a vector.
void zeroCalculated ()
Set all calculated values to zero.
Protected Member Functions
void add (double *to) const
Add calculated values to values in a buffer and save result to the buffer.
void copyTo (double *to) const
Copy calculated values to a buffer.
void multiply (double *to) const
Multiply calculated values by values in a buffer and save result to the buffer.
Protected Attributes
std::vector< double > m_calculated
buffer for calculated values
std::vector< double > m_data
buffer for fit data
std::vector< double > m_weights
buffer for fitting weights (reciprocal errors)
Detailed Description
A class to store values calculated by a function.
It also can contain data a function can fit to.
Author
Roman Tolchenov, Tessella plc
Date
15/11/2011
Definition at line 25 of file FunctionValues.h.
Constructor & Destructor Documentation
FunctionValues() [1/2]
Mantid::API::FunctionValues::FunctionValues (size_t n = 0) explicit
Constructor.
Parameters
n :: A number of values to store.
Definition at line 18 of file FunctionValues.cpp.
References m_calculated, and n.
FunctionValues() [2/2]
Mantid::API::FunctionValues::FunctionValues (const FunctionDomain & domain) explicit
Constructor.
Constructs a set of output values based on the given domain.
Parameters
domain :: A reference to the domain over which the function is calculated
Definition at line 29 of file FunctionValues.cpp.
References reset().
Member Function Documentation
add()
void Mantid::API::FunctionValues::add (double * to) const protected
Add calculated values to values in a buffer and save result to the buffer.
Parameters
to :: Pointer to the buffer, it must be large enough
Definition at line 84 of file FunctionValues.cpp.
References m_calculated.
Referenced by addToCalculated(), and operator+=().
addToCalculated() [1/2]
void Mantid::API::FunctionValues::addToCalculated (size_t i, double value) inline
Add a number to a calculated value.
Parameters
i :: An index of a value 0 <= i < size() to update.
value :: A value to add
Definition at line 58 of file FunctionValues.h.
References value.
Referenced by Mantid::CurveFitting::Functions::PawleyFunction::function(), and Mantid::API::MultiDomainFunction::function().
addToCalculated() [2/2]
void Mantid::API::FunctionValues::addToCalculated (size_t start, const FunctionValues & values)
Add other calculated values with offset.
Add other calculated values to these values starting from some index.
Parameters
start :: A starting index for addition
values :: An instance of FunctionValues to be added to this. The size mustn't exceed the number of values in this from start to the end.
Returns
A reference to this values.
Definition at line 132 of file FunctionValues.cpp.
References add(), getPointerToCalculated(), and size().
copyTo()
void Mantid::API::FunctionValues::copyTo (double * to) const protected
Copy calculated values to a buffer.
Parameters
to :: Pointer to the buffer
Definition at line 79 of file FunctionValues.cpp.
References m_calculated.
expand()
void Mantid::API::FunctionValues::expand (size_t n)
Expand values to a new size, preserve stored values.
Expand to a new size.
Preserve old values. Do not contract.
Parameters
n :: A new size, must be greater than the current size.
Definition at line 43 of file FunctionValues.cpp.
References m_calculated, m_data, m_weights, n, and size().
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::calcExcitations(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), and Mantid::CurveFitting::Functions::CrystalFieldPeaks::functionGeneral().
getCalculated()
double Mantid::API::FunctionValues::getCalculated (size_t i) const inline
Get i-th calculated value.
Parameters
i :: An index of a value 0 <= i < size()
Definition at line 51 of file FunctionValues.h.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldUtils::buildSpectrumFunction(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::calcChiSquared(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateDerivative(), Mantid::Algorithms::FitPeaks::calculateFittedPeaks(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateHessian(), Mantid::API::IFunction::calNumericalDeriv(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), Mantid::CurveFitting::Algorithms::ConvolveWorkspaces::exec(), Mantid::Algorithms::PeakParameterHelper::observePeakCenter(), Mantid::Algorithms::PeakParameterHelper::observePeakFwhm(), and Mantid::CurveFitting::Functions::CrystalFieldUtils::updateSpectrumFunction().
getFitData()
double Mantid::API::FunctionValues::getFitData (size_t i) const
Get a fitting data value.
Parameters
i :: A value index
Definition at line 167 of file FunctionValues.cpp.
References m_calculated, and m_data.
Referenced by Mantid::CurveFitting::Algorithms::CalculateChiSquared::calcChiSquared(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateDerivative(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateHessian(), and Mantid::CurveFitting::ParameterEstimator::extractValues().
getFitWeight()
double Mantid::API::FunctionValues::getFitWeight (size_t i) const
Get a fitting weight.
Parameters
i :: A value index.
Definition at line 208 of file FunctionValues.cpp.
References m_calculated, and m_weights.
Referenced by Mantid::CurveFitting::Algorithms::CalculateChiSquared::calcChiSquared().
getPointerToCalculated()
double * Mantid::API::FunctionValues::getPointerToCalculated (size_t i)
Get a pointer to calculated data at index i.
Parameters
i :: Index.
Definition at line 65 of file FunctionValues.cpp.
References m_calculated, and size().
Referenced by addToCalculated(), Mantid::CurveFitting::Functions::PawleyFunction::calculateFunctionValues(), Mantid::API::IFunction1D::derivative(), Mantid::MDAlgorithms::EvaluateMDFunction::exec(), Mantid::API::IFunction1D::function(), Mantid::CurveFitting::Functions::Convolution::functionDirectMode(), Mantid::CurveFitting::Functions::Convolution::functionFFTMode(), operator*=(), and operator+=().
multiply()
void Mantid::API::FunctionValues::multiply (double * to) const protected
Multiply calculated values by values in a buffer and save result to the buffer.
Parameters
to :: Pointer to the buffer, it must be large enough
Definition at line 92 of file FunctionValues.cpp.
References m_calculated.
Referenced by operator*=().
operator*=()
FunctionValues & Mantid::API::FunctionValues::operator*= (const FunctionValues & values)
Multiply by other calculated values.
Parameters
values :: An instance of FunctionValues to multiply to this. Must have the same size to this.
Returns
A reference to this values.
Definition at line 116 of file FunctionValues.cpp.
References getPointerToCalculated(), multiply(), and size().
operator+=()
FunctionValues & Mantid::API::FunctionValues::operator+= (const FunctionValues & values)
Add other calculated values.
Add other calculated values to this.
Parameters
values :: An instance of FunctionValues to be added to this. Must have the same size to this.
Returns
A reference to this values.
Definition at line 102 of file FunctionValues.cpp.
References add(), getPointerToCalculated(), and size().
operator[]()
double Mantid::API::FunctionValues::operator[] (size_t i) const inline
Get i-th calculated value.
Parameters
i :: An index of a value 0 <= i < size()
Definition at line 54 of file FunctionValues.h.
reset()
void Mantid::API::FunctionValues::reset (const FunctionDomain & domain)
Reset the values to match a new domain.
Definition at line 32 of file FunctionValues.cpp.
References m_calculated, and Mantid::API::FunctionDomain::size().
Referenced by Mantid::CurveFitting::Functions::PawleyFunction::calculateFunctionValues(), and FunctionValues().
setCalculated() [1/2]
void Mantid::API::FunctionValues::setCalculated (double value)
set all calculated values to same number
Set all calculated values to same number.
Parameters
value :: A new value.
Definition at line 59 of file FunctionValues.cpp.
References m_calculated, and value.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::calcExcitations(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), Mantid::API::IFunctionMD::evaluateFunction(), Mantid::CurveFitting::Functions::CrystalFieldPeaks::functionGeneral(), Mantid::CurveFitting::LatticeFunction::functionLattice(), and zeroCalculated().
setCalculated() [2/2]
void Mantid::API::FunctionValues::setCalculated (size_t i, double value) inline
Store i-th calculated value.
Parameters
i :: Index of the stored value 0 <= i < size()
value :: A value to store.
Definition at line 48 of file FunctionValues.h.
References value.
setFitData() [1/2]
void Mantid::API::FunctionValues::setFitData (const std::vector< double > & values)
Set all fitting data values.
Parameters
values :: A vector of values for fitting. Must have the same size as this.
Definition at line 156 of file FunctionValues.cpp.
References m_data.
setFitData() [2/2]
void Mantid::API::FunctionValues::setFitData (size_t i, double value)
Set a fitting data value.
Parameters
i :: A value index
value :: A new value to set.
Definition at line 144 of file FunctionValues.cpp.
References m_calculated, m_data, and value.
setFitDataFromCalculated()
void Mantid::API::FunctionValues::setFitDataFromCalculated (const FunctionValues & values)
Set all calculated values by copying them from another FunctionValues instance.
Set fitting data copied from other FunctionValues' calculated values.
Parameters
values :: An instance of FunctionValues to copy the data from.
Definition at line 219 of file FunctionValues.cpp.
References m_calculated, and m_data.
setFitWeight()
void Mantid::API::FunctionValues::setFitWeight (size_t i, double value)
Set a fitting weight.
Parameters
i :: A value index
value :: A new value for the weight.
Definition at line 179 of file FunctionValues.cpp.
References m_calculated, m_weights, and value.
setFitWeights() [1/2]
void Mantid::API::FunctionValues::setFitWeights (const double & value)
Set all fitting weights to a number.
Set all weights to the same value.
Parameters
value :: The value to set.
Definition at line 202 of file FunctionValues.cpp.
References m_calculated, m_weights, and value.
setFitWeights() [2/2]
void Mantid::API::FunctionValues::setFitWeights (const std::vector< double > & values)
Set all fitting weights.
Parameters
values :: A vector of fitting weights. Must have the same size as this.
Definition at line 191 of file FunctionValues.cpp.
References m_weights.
size()
size_t Mantid::API::FunctionValues::size () const inline
Return the number of values.
Definition at line 32 of file FunctionValues.h.
Referenced by addToCalculated(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::calcChiSquared(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateD2TOFFunction(), Mantid::CurveFitting::Functions::CrystalFieldUtils::calculateNPeaks(), Mantid::API::IFunction::calNumericalDeriv(), Mantid::MDAlgorithms::EvaluateMDFunction::exec(), expand(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::API::IFunctionGeneral::function(), Mantid::API::MultiDomainFunction::function(), Mantid::CurveFitting::Functions::CrystalFieldPeaks::functionGeneral(), Mantid::CurveFitting::LatticeFunction::functionLattice(), Mantid::Algorithms::GeneratePeaks::generatePeaks(), getPointerToCalculated(), Mantid::Algorithms::PeakParameterHelper::observePeakFwhm(), operator*=(), and operator+=().
toVector()
std::vector< double > Mantid::API::FunctionValues::toVector () const inline
Return the calculated values as a vector.
Definition at line 86 of file FunctionValues.h.
Referenced by Mantid::CurveFitting::Algorithms::estimateBackgroundCoarse(), Mantid::Algorithms::CreateSampleWorkspace::evalFunction(), Mantid::CurveFitting::Functions::evaluateFunctionOnRange(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::genOutputWorkspace(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), and Mantid::Algorithms::FitPeak::setupOutput().
zeroCalculated()
void Mantid::API::FunctionValues::zeroCalculated ()
Set all calculated values to zero.
Definition at line 73 of file FunctionValues.cpp.
References setCalculated().
Referenced by Mantid::CurveFitting::Functions::Convolution::function(), Mantid::CurveFitting::Functions::PawleyFunction::function(), Mantid::API::CompositeFunction::function(), Mantid::API::MultiDomainFunction::function(), Mantid::CurveFitting::Functions::Convolution::functionDirectMode(), and Mantid::CurveFitting::Functions::Convolution::functionFFTMode().
Member Data Documentation
m_calculated
std::vector<double> Mantid::API::FunctionValues::m_calculated protected
buffer for calculated values
Definition at line 100 of file FunctionValues.h.
Referenced by add(), copyTo(), expand(), FunctionValues(), getFitData(), getFitWeight(), getPointerToCalculated(), multiply(), reset(), setCalculated(), setFitData(), setFitDataFromCalculated(), setFitWeight(), and setFitWeights().
m_data
std::vector<double> Mantid::API::FunctionValues::m_data protected
buffer for fit data
Definition at line 102 of file FunctionValues.h.
Referenced by expand(), getFitData(), setFitData(), and setFitDataFromCalculated().
m_weights
std::vector<double> Mantid::API::FunctionValues::m_weights protected
buffer for fitting weights (reciprocal errors)
Definition at line 104 of file FunctionValues.h.
Referenced by expand(), getFitWeight(), setFitWeight(), and setFitWeights().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/FunctionValues.h
Framework/API/src/FunctionValues.cpp