Mantid: Mantid::DataObjects::CalculateReflectometryP Class Reference
Mantid::DataObjects::CalculateReflectometryP Class Reference
class CalculateReflectometryP: p-type transformation calculator
#include <CalculateReflectometryP.h>
Public Member Functions
double calculateDim0 (double wavelength) const override
Executes the calculation to determine PSum.
double calculateDim1 (double wavelength) const override
Executes the calculation to determine PDiff.
CalculateReflectometryP (int version)
Constructor.
Mantid::Geometry::Quadrilateral createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) override
void setThetaFinal (double thetaFinal) override
Setter for the final theta value require for the calculation.
void setTwoTheta (double twoTheta) override
Set the final theta value from the detector twoTheta angle.
void updateThetaIncident (double thetaIncident) override
Setter for the incident theta value require for the calculation.
Public Member Functions inherited from Mantid::DataObjects::CalculateReflectometry
virtual double calculateDim0 (double wavelength) const =0
Executes the calculation on dimension 0.
virtual double calculateDim1 (double wavelength) const =0
Executes the calculation on dimension 1.
CalculateReflectometry (int version)
virtual Mantid::Geometry::Quadrilateral createQuad (double lamLower, double lamUpper, double thetaLower, double thetaUpper)=0
virtual void setThetaFinal (double thetaFinal)=0
Setter for the final theta value require for the calculation.
void setThetaIncident (double thetaIncident)
Setter for the incident theta value require for the calculation.
virtual void setTwoTheta (double twoTheta)=0
Set the final theta value from the detector twoTheta angle.
virtual void updateThetaIncident (double thetaIncident)=0
Derived class setter for the final theta value require for the calculation.
virtual ~CalculateReflectometry ()=default
Private Attributes
double m_sin_theta_f
double m_sin_theta_i
Additional Inherited Members
Protected Attributes inherited from Mantid::DataObjects::CalculateReflectometry
double m_theta_i {0.0}
int m_version
const double to_radians_factor = M_PI / 180.0
Detailed Description
class CalculateReflectometryP: p-type transformation calculator
Definition at line 16 of file CalculateReflectometryP.h.
Constructor & Destructor Documentation
CalculateReflectometryP()
Mantid::DataObjects::CalculateReflectometryP::CalculateReflectometryP (int version) inline
Constructor.
Definition at line 25 of file CalculateReflectometryP.h.
Member Function Documentation
calculateDim0()
double Mantid::DataObjects::CalculateReflectometryP::calculateDim0 (double wavelength) const inline override virtual
Executes the calculation to determine PSum.
Parameters
wavelength : wavelength in Angstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 56 of file CalculateReflectometryP.h.
References m_sin_theta_f, and m_sin_theta_i.
Referenced by createQuad().
calculateDim1()
double Mantid::DataObjects::CalculateReflectometryP::calculateDim1 (double wavelength) const inline override virtual
Executes the calculation to determine PDiff.
Parameters
wavelength : wavelength in Angstroms
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 67 of file CalculateReflectometryP.h.
References m_sin_theta_f, and m_sin_theta_i.
Referenced by createQuad().
createQuad()
Mantid::Geometry::Quadrilateral Mantid::DataObjects::CalculateReflectometryP::createQuad (double lamUpper, double lamLower, double thetaUpper, double thetaLower) inline override virtual
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 73 of file CalculateReflectometryP.h.
References Mantid::Geometry::Quadrilateral::at(), calculateDim0(), calculateDim1(), setTwoTheta(), Mantid::Geometry::Quadrilateral::shiftVertexesClockwise(), Mantid::Kernel::V2D::X(), and Mantid::Kernel::V2D::Y().
setThetaFinal()
void Mantid::DataObjects::CalculateReflectometryP::setThetaFinal (double thetaFinal) inline override virtual
Setter for the final theta value require for the calculation.
Internally pre-calculates and caches to cos theta for speed.
Parameters
thetaFinal final theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 39 of file CalculateReflectometryP.h.
References m_sin_theta_f, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Referenced by setTwoTheta().
setTwoTheta()
void Mantid::DataObjects::CalculateReflectometryP::setTwoTheta (double twoTheta) inline override virtual
Set the final theta value from the detector twoTheta angle.
Parameters
twoTheta detector twoTheta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 45 of file CalculateReflectometryP.h.
References Mantid::DataObjects::CalculateReflectometry::m_theta_i, Mantid::DataObjects::CalculateReflectometry::m_version, setThetaFinal(), and Mantid::Kernel::twoTheta.
Referenced by createQuad().
updateThetaIncident()
void Mantid::DataObjects::CalculateReflectometryP::updateThetaIncident (double thetaIncident) inline override virtual
Setter for the incident theta value require for the calculation.
Internally pre-calculates and caches to cos theta for speed.
Parameters
thetaIncident incident theta value in degrees
Implements Mantid::DataObjects::CalculateReflectometry.
Definition at line 32 of file CalculateReflectometryP.h.
References m_sin_theta_i, and Mantid::DataObjects::CalculateReflectometry::to_radians_factor.
Member Data Documentation
m_sin_theta_f
double Mantid::DataObjects::CalculateReflectometryP::m_sin_theta_f private
Definition at line 19 of file CalculateReflectometryP.h.
Referenced by calculateDim0(), calculateDim1(), and setThetaFinal().
m_sin_theta_i
double Mantid::DataObjects::CalculateReflectometryP::m_sin_theta_i private
Definition at line 18 of file CalculateReflectometryP.h.
Referenced by calculateDim0(), calculateDim1(), and updateThetaIncident().
The documentation for this class was generated from the following file:
Framework/DataObjects/inc/MantidDataObjects/CalculateReflectometryP.h