Mantid: MantidQt::CustomDialogs::StartLiveDataDialog Class Reference
MantidQt::CustomDialogs::StartLiveDataDialog Class Reference
#include <StartLiveDataDialog.h>
Public Slots
void changePostProcessingAlgorithm ()
Slot called when picking a different algorithm in the AlgorithmSelectorWidget.
void changeProcessingAlgorithm ()
Slot called when picking a different algorithm in the AlgorithmSelectorWidget.
void chkPreserveEventsToggled ()
Slot called when the preserve events checkbox changes.
void radioPostProcessClicked ()
Slot called when one of the radio buttons in "processing" are picked.
void radioProcessClicked ()
Slot called when one of the radio buttons in "processing" are picked.
void radioTimeClicked ()
Slot called when one of the radio buttons in "starting time" are picked.
Public Member Functions
StartLiveDataDialog (QWidget *parent=nullptr)
Default Constructor.
~StartLiveDataDialog () override
Destructor.
Public Member Functions inherited from MantidQt::API::AlgorithmDialog
AlgorithmDialog (QWidget *parent=nullptr)
DefaultConstructor.
void initializeLayout ()
Create the layout of the widget. Can only be called once.
bool isInitialized () const
Is this dialog initialized.
bool isShowKeepOpen () const
Set if the keep open option is shown.
void setShowKeepOpen (const bool showOption)
Set if the keep open option is shown.
~AlgorithmDialog () override
Destructor.
void setAlgorithm (const Mantid::API::IAlgorithm_sptr &)
The following methods were made public for testing in GenericDialogDemo.cpp.
void setPresetValues (const QHash< QString, QString > &presetValues)
Set a list of suggested values.
void isForScript (bool forScript)
Set whether this is intended for use from a script or not.
void executeOnAccept (bool on)
If true then execute the algorithm on acceptance.
void setOptionalMessage (const QString &message)
Set an optional message to be displayed at the top of the dialog.
void addEnabledAndDisableLists (const QStringList &enabled, const QStringList &disabled)
Set comma-separated-list of enabled parameter names.
void addAlgorithmObserver (Mantid::API::AlgorithmObserver *observer)
Add an AlgorithmObserver to the algorithm.
Private Slots
void accept () override
void initListenerPropLayout ()
Update the Listener Properties group box for the current LiveListener.
void setDefaultAccumulationMethod (const QString &)
Slot called when picking a different instrument.
void updateConnectionChoices (const QString &inst_name)
Slot to update list of available connections when instrument is changed.
void updateConnectionDetails (const QString &connection)
Slot to update connection parameters when connection selected.
void updateUiElements (const QString &)
Another slot called when picking a different instrument.
Private Member Functions
Mantid::API::Algorithm_sptr changeAlgorithm (MantidQt::MantidWidgets::AlgorithmSelectorWidget *selector, MantidQt::API::AlgorithmPropertiesWidget *propWidget)
void initLayout () override
Initialize the layout.
void parseInput () override
Parse the input from the dialog when it has been accepted.
Private Attributes
Mantid::API::Algorithm_sptr m_postProcessingAlg
The algorithm for processing the accumulated workspace.
Mantid::API::Algorithm_sptr m_processingAlg
The algorithm for processing chunks.
API::WidgetScrollbarDecorator m_scrollbars
This dialog needs scrollbars on small screens.
bool m_usePostProcessAlgo
bool m_usePostProcessScript
bool m_useProcessAlgo
bool m_useProcessScript
Ui::StartLiveDataDialog ui
The form generated by Qt Designer.
Static Private Attributes
static const QString CUSTOM_CONNECTION = "[Custom]"
Constant used for custom listener connection setups.
Additional Inherited Members
Signals inherited from MantidQt::API::AlgorithmDialog
void algCompletedSignal ()
Emitted when alg completes and dialog is staying open.
void closeEventCalled ()
Protected Slots inherited from MantidQt::API::AlgorithmDialog
void accept () override
A default slot that can be used for an OK button.
void reject () override
A default slot that can be used for a rejected button.
virtual void helpClicked ()
Help button clicked;.
virtual void keepOpenChanged (int state)
Keep open checkbox clicked;.
virtual void algorithmCompleted ()
Keep the running algorithm has completed.
virtual void executeAlgorithmAsync ()
Executes the algorithm in a separate thread.
virtual void removeAlgorithmFromManager ()
Removes the algorithm from the manager.
void enableExitButton ()
Enable to exit button.
Protected Member Functions inherited from MantidQt::API::AlgorithmDialog
virtual void saveInput ()
Save the input history of an accepted dialog.
const QString & getOptionalMessage () const
Get the message string.
void addOptionalMessage (QVBoxLayout *mainLay)
Add the optional message to the given layout.
bool isForScript () const
Get the usage boolean value.
bool isMessageAvailable () const
Is there a message string available.
bool isWidgetEnabled (const QString &propName) const
Check is a given property should have its control enabled or not.
Mantid::API::IAlgorithm_sptr getAlgorithm () const
Get the algorithm pointer.
Mantid::Kernel::Property * getAlgorithmProperty (const QString &propName) const
Get a pointer to the named property.
bool requiresUserInput (const QString &propName) const
Return a true if the given property requires user input.
QString getInputValue (const QString &propName) const
Get an input value from the form, dealing with blank inputs etc.
QLabel * getValidatorMarker (const QString &propname)
Get a property validator label.
void storePropertyValue (const QString &name, const QString &value)
Adds a property (name,value) pair to the stored map.
void removePropertyValue (const QString &name)
Removes a property (name, value) pair from the stored map.
bool setPropertyValues (const QStringList &skipList=QStringList())
Set properties on this algorithm by pulling values from the tied widgets.
bool setPropertyValue (const QString &pName, bool validateOthers)
Sets the value of a single property, using the value previously stored using storePropertyValue()
void showValidators ()
Show the validators for all the properties.
QWidget * tie (QWidget *widget, const QString &property, QLayout *parent_layout=nullptr, bool readHistory=true)
Tie a widget to a property.
void untie (const QString &property)
Untie a widget to a property.
QString openFileDialog (const QString &propName)
Open a file dialog to select a file.
QStringList openMultipleFileDialog (const QString &propName)
Open a file dialog to select many file.
void fillAndSetComboBox (const QString &propName, QComboBox *optionsBox) const
Fill a combo box for the named algorithm's allowed values.
void fillLineEdit (const QString &propName, QLineEdit *field)
Fill in the necessary input for a text field.
QLayout * createDefaultButtonLayout (const QString &helpText=QString("?"), const QString &loadText=QString("Run"), const QString &cancelText=QString("Close"), const QString &keepOpenText=QString("Keep Open"))
Create a row layout of buttons with specified text.
QPushButton * createHelpButton (const QString &helpText=QString("?")) const
Create a help button for this algorithm.
void flagInputWS (QWidget *inputWidget)
Flag an input workspace combobox with its property name.
QString getValue (QWidget *widget)
Retrieve a text value for a property from a widget.
void parse ()
Parse out the input from the dialog.
bool requestedToKeepEnabled (const QString &propName) const
Test if the given name's widget has been explicity asked to be enabled.
QString getPreviousValue (const QString &propName) const
Get the property value from either the previous input store or from Python argument.
void setPreviousValue (QWidget *widget, const QString &property)
Set a value based on any old input that we have.
void finishHandle (const Mantid::API::IAlgorithm *alg) override
Handle completion of algorithm started while staying open.
void errorHandle (const Mantid::API::IAlgorithm *alg, const std::string &what) override
Handle completion of algorithm started while staying open.
void closeEvent (QCloseEvent *evt) override
Only allow close when close is enabled.
Protected Attributes inherited from MantidQt::API::AlgorithmDialog
Mantid::API::IAlgorithm_sptr m_algorithm
The algorithm associated with this dialog.
QString m_algName
The name of the algorithm.
QStringList m_algProperties
The properties associated with this dialog.
QHash< QString, QString > m_propertyValueMap
A map of property <name, value> pairs that have been taken from the dialog.
QHash< QString, QWidget * > m_tied_properties
A list pointers to the widget for each property.
bool m_forScript
A boolean indicating whether this is for a script or not.
QStringList m_python_arguments
A list of property names that have been passed from Python.
QStringList m_enabled
A list of property names that should have their widgets enabled.
QStringList m_disabled
A list of property names that the user has requested to be disabled (overrides those in enabled)
QString m_strMessage
The message string to be displayed at the top of the widget; if it exists.
bool m_keepOpen
Whether to keep the dialog box open after alg execution.
bool m_msgAvailable
Is the message string empty or not.
bool m_isInitialized
Whether the layout has been initialized.
bool m_autoParseOnInit
Flag if the input should be parsed automatically on initialization.
QHash< QString, QLabel * > m_validators
A list of labels to use as validation markers.
QHash< QString, QString > m_errors
A map where key = property name; value = the error for this property (i.e.
QStringList m_noValidation
A list of property names whose widgets handle their own validation.
QVector< QWidget * > m_inputws_opts
Store a list of the names of input workspace boxes.
QVector< QLineEdit * > m_outputws_fields
Store a list of output workspace text edits.
QHash< QPushButton *, int > m_wsbtn_tracker
A map to keep track of replace workspace button presses.
QCheckBox * m_keepOpenCheckBox
QPushButton * m_okButton
QPushButton * m_exitButton
std::vector< Mantid::API::AlgorithmObserver * > m_observers
A list of AlgorithmObservers to add to the algorithm prior to execution.
QTimer m_btnTimer
Enable the close button when the timer fires.
bool m_statusTracked
A flag to track whether the status of the algorithm is being tracked.
Detailed Description
Definition at line 21 of file StartLiveDataDialog.h.
Constructor & Destructor Documentation
StartLiveDataDialog()
MantidQt::CustomDialogs::StartLiveDataDialog::StartLiveDataDialog (QWidget * parent = nullptr)
Default Constructor.
Constructor.
Definition at line 78 of file StartLiveDataDialog.cpp.
~StartLiveDataDialog()
MantidQt::CustomDialogs::StartLiveDataDialog::~StartLiveDataDialog () override
Destructor.
Definition at line 86 of file StartLiveDataDialog.cpp.
Member Function Documentation
accept
void MantidQt::CustomDialogs::StartLiveDataDialog::accept () override private slot
Definition at line 377 of file StartLiveDataDialog.cpp.
References MantidQt::API::AlgorithmDialog::accept(), MantidQt::API::AlgorithmDialog::storePropertyValue(), and ui.
changeAlgorithm()
Mantid::API::Algorithm_sptr MantidQt::CustomDialogs::StartLiveDataDialog::changeAlgorithm (MantidQt::MantidWidgets::AlgorithmSelectorWidget * selector, MantidQt::API::AlgorithmPropertiesWidget * propWidget) private
changePostProcessingAlgorithm
void MantidQt::CustomDialogs::StartLiveDataDialog::changePostProcessingAlgorithm () slot
Slot called when picking a different algorithm in the AlgorithmSelectorWidget.
Definition at line 310 of file StartLiveDataDialog.cpp.
References m_postProcessingAlg, and ui.
Referenced by initLayout().
changeProcessingAlgorithm
void MantidQt::CustomDialogs::StartLiveDataDialog::changeProcessingAlgorithm () slot
Slot called when picking a different algorithm in the AlgorithmSelectorWidget.
Definition at line 300 of file StartLiveDataDialog.cpp.
References m_processingAlg, and ui.
Referenced by initLayout().
chkPreserveEventsToggled
void MantidQt::CustomDialogs::StartLiveDataDialog::chkPreserveEventsToggled () slot
Slot called when the preserve events checkbox changes.
Definition at line 293 of file StartLiveDataDialog.cpp.
References ui.
Referenced by initLayout().
initLayout()
void MantidQt::CustomDialogs::StartLiveDataDialog::initLayout () override private virtual
Initialize the layout.
Set up the dialog layout.
Implements MantidQt::API::AlgorithmDialog.
Definition at line 93 of file StartLiveDataDialog.cpp.
References changePostProcessingAlgorithm(), changeProcessingAlgorithm(), chkPreserveEventsToggled(), MantidQt::API::AlgorithmDialog::createDefaultButtonLayout(), MantidQt::API::AlgorithmDialog::fillAndSetComboBox(), initListenerPropLayout(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_scrollbars, radioPostProcessClicked(), radioProcessClicked(), radioTimeClicked(), setDefaultAccumulationMethod(), MantidQt::API::WidgetScrollbarDecorator::setEnabled(), MantidQt::API::AlgorithmDialog::tie(), ui, updateConnectionChoices(), updateConnectionDetails(), and updateUiElements().
initListenerPropLayout
void MantidQt::CustomDialogs::StartLiveDataDialog::initListenerPropLayout () private slot
Update the Listener Properties group box for the current LiveListener.
Definition at line 395 of file StartLiveDataDialog.cpp.
References MantidQt::API::AlgorithmDialog::m_algorithm, MantidQt::API::AlgorithmDialog::m_algProperties, MantidQt::API::AlgorithmDialog::tie(), and ui.
Referenced by initLayout().
parseInput()
void MantidQt::CustomDialogs::StartLiveDataDialog::parseInput () override private virtual
Parse the input from the dialog when it has been accepted.
Parse input when the dialog is accepted.
Reimplemented from MantidQt::API::AlgorithmDialog.
Definition at line 225 of file StartLiveDataDialog.cpp.
References m_postProcessingAlg, m_processingAlg, m_usePostProcessAlgo, m_usePostProcessScript, m_useProcessAlgo, m_useProcessScript, MantidQt::API::AlgorithmDialog::storePropertyValue(), and ui.
radioPostProcessClicked
void MantidQt::CustomDialogs::StartLiveDataDialog::radioPostProcessClicked () slot
Slot called when one of the radio buttons in "processing" are picked.
Definition at line 278 of file StartLiveDataDialog.cpp.
References m_usePostProcessAlgo, m_usePostProcessScript, and ui.
Referenced by initLayout().
radioProcessClicked
void MantidQt::CustomDialogs::StartLiveDataDialog::radioProcessClicked () slot
Slot called when one of the radio buttons in "processing" are picked.
Definition at line 269 of file StartLiveDataDialog.cpp.
References m_useProcessAlgo, m_useProcessScript, and ui.
Referenced by initLayout().
radioTimeClicked
void MantidQt::CustomDialogs::StartLiveDataDialog::radioTimeClicked () slot
Slot called when one of the radio buttons in "starting time" are picked.
Definition at line 290 of file StartLiveDataDialog.cpp.
References ui.
Referenced by initLayout().
setDefaultAccumulationMethod
void MantidQt::CustomDialogs::StartLiveDataDialog::setDefaultAccumulationMethod (const QString & listener) private slot
Slot called when picking a different instrument.
Disables the 'Add' option if the listener is going to pass back histograms.
Parameters
listener :: The listener class name.
Definition at line 322 of file StartLiveDataDialog.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance(), and ui.
Referenced by initLayout().
updateConnectionChoices
void MantidQt::CustomDialogs::StartLiveDataDialog::updateConnectionChoices (const QString & inst_name) private slot
Slot to update list of available connections when instrument is changed.
Parameters
inst_name Name of selected instrument
Definition at line 451 of file StartLiveDataDialog.cpp.
References CUSTOM_CONNECTION, index, and ui.
Referenced by initLayout().
updateConnectionDetails
void MantidQt::CustomDialogs::StartLiveDataDialog::updateConnectionDetails (const QString & connection) private slot
Slot to update connection parameters when connection selected.
Parameters
connection Name of selected live listener connection
Definition at line 477 of file StartLiveDataDialog.cpp.
References CUSTOM_CONNECTION, index, and ui.
Referenced by initLayout().
updateUiElements
void MantidQt::CustomDialogs::StartLiveDataDialog::updateUiElements (const QString & inst) private slot
Another slot called when picking a different instrument.
Disables UI elements that are not used by the instrument Currently, only TOPAZ listener uses this (and only for the "Starting Time" group.
Parameters
inst :: The instrument name.
Definition at line 359 of file StartLiveDataDialog.cpp.
References ui.
Referenced by initLayout().
Member Data Documentation
CUSTOM_CONNECTION
const QString MantidQt::CustomDialogs::StartLiveDataDialog::CUSTOM_CONNECTION = "[Custom]" static private
Constant used for custom listener connection setups.
Definition at line 74 of file StartLiveDataDialog.h.
Referenced by updateConnectionChoices(), and updateConnectionDetails().
m_postProcessingAlg
Mantid::API::Algorithm_sptr MantidQt::CustomDialogs::StartLiveDataDialog::m_postProcessingAlg private
The algorithm for processing the accumulated workspace.
Definition at line 71 of file StartLiveDataDialog.h.
Referenced by changePostProcessingAlgorithm(), and parseInput().
m_processingAlg
Mantid::API::Algorithm_sptr MantidQt::CustomDialogs::StartLiveDataDialog::m_processingAlg private
The algorithm for processing chunks.
Definition at line 68 of file StartLiveDataDialog.h.
Referenced by changeProcessingAlgorithm(), and parseInput().
m_scrollbars
API::WidgetScrollbarDecorator MantidQt::CustomDialogs::StartLiveDataDialog::m_scrollbars private
This dialog needs scrollbars on small screens.
Definition at line 60 of file StartLiveDataDialog.h.
Referenced by initLayout().
m_usePostProcessAlgo
bool MantidQt::CustomDialogs::StartLiveDataDialog::m_usePostProcessAlgo private
Definition at line 64 of file StartLiveDataDialog.h.
Referenced by parseInput(), and radioPostProcessClicked().
m_usePostProcessScript
bool MantidQt::CustomDialogs::StartLiveDataDialog::m_usePostProcessScript private
Definition at line 65 of file StartLiveDataDialog.h.
Referenced by parseInput(), and radioPostProcessClicked().
m_useProcessAlgo
bool MantidQt::CustomDialogs::StartLiveDataDialog::m_useProcessAlgo private
Definition at line 62 of file StartLiveDataDialog.h.
Referenced by parseInput(), and radioProcessClicked().
m_useProcessScript
bool MantidQt::CustomDialogs::StartLiveDataDialog::m_useProcessScript private
Definition at line 63 of file StartLiveDataDialog.h.
Referenced by parseInput(), and radioProcessClicked().
ui
Ui::StartLiveDataDialog MantidQt::CustomDialogs::StartLiveDataDialog::ui private
The form generated by Qt Designer.
Definition at line 57 of file StartLiveDataDialog.h.
Referenced by accept(), changePostProcessingAlgorithm(), changeProcessingAlgorithm(), chkPreserveEventsToggled(), initLayout(), initListenerPropLayout(), parseInput(), radioPostProcessClicked(), radioProcessClicked(), radioTimeClicked(), setDefaultAccumulationMethod(), updateConnectionChoices(), updateConnectionDetails(), and updateUiElements().
The documentation for this class was generated from the following files:
qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/StartLiveDataDialog.h
qt/widgets/plugins/algorithm_dialogs/src/StartLiveDataDialog.cpp