Mantid: Mantid::API::IAlgorithmRuntimeProps Class Reference
Mantid::API::IAlgorithmRuntimeProps Class Reference abstract
#include <IAlgorithmRuntimeProps.h>
Public Member Functions
virtual TypedValue getProperty (const std::string &name) const override=0
Get the value of a property.
IAlgorithmRuntimeProps ()=default
virtual bool operator== (const Mantid::Kernel::IPropertyManager &)=delete
template<typename T >
void setProperty (const std::string &name, const T &value)
virtual void setPropertyValue (const std::string &, const std::string &) override=0
Sets property value from a string.
virtual ~IAlgorithmRuntimeProps ()=default
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Detailed Description
Definition at line 13 of file IAlgorithmRuntimeProps.h.
Constructor & Destructor Documentation
IAlgorithmRuntimeProps()
Mantid::API::IAlgorithmRuntimeProps::IAlgorithmRuntimeProps () default
~IAlgorithmRuntimeProps()
virtual Mantid::API::IAlgorithmRuntimeProps::~IAlgorithmRuntimeProps () virtual default
Member Function Documentation
getProperty()
virtual TypedValue Mantid::API::IAlgorithmRuntimeProps::getProperty (const std::string & name) const override pure virtual
Get the value of a property.
Implements Mantid::Kernel::IPropertyManager.
Implemented in Mantid::API::AlgorithmRuntimeProps.
operator==()
virtual bool Mantid::API::IAlgorithmRuntimeProps::operator== (const Mantid::Kernel::IPropertyManager &) virtual delete
Reimplemented in Mantid::API::AlgorithmRuntimeProps.
setProperty()
template<typename T > void Mantid::API::IAlgorithmRuntimeProps::setProperty (const std::string & name, const T & value) inline
Definition at line 24 of file IAlgorithmRuntimeProps.h.
References name, Mantid::Kernel::IPropertyManager::setProperty(), and value.
Referenced by Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), Mantid::API::AlgorithmProperties::update(), and Mantid::API::AlgorithmProperties::update().
setPropertyValue()
virtual void Mantid::API::IAlgorithmRuntimeProps::setPropertyValue (const std::string & name, const std::string & value) override pure virtual
Sets property value from a string.
Parameters
name :: Property name
value :: New property value
Implements Mantid::Kernel::IPropertyManager.
Implemented in Mantid::API::AlgorithmRuntimeProps.
Referenced by Mantid::API::AlgorithmProperties::update().
The documentation for this class was generated from the following file:
Framework/API/inc/MantidAPI/IAlgorithmRuntimeProps.h