Mantid: Mantid::Kernel::ReciprocalLatticeUnit Class Reference
Mantid::Kernel::ReciprocalLatticeUnit Class Reference
Dimensionless RLU.
#include <MDUnit.h>
Public Member Functions
bool canConvertTo (const MDUnit &other) const override
ReciprocalLatticeUnit * clone () const override
UnitLabel getUnitLabel () const override
ReciprocalLatticeUnit ()
ReciprocalLatticeUnit (UnitLabel unitLabel)
Public Member Functions inherited from Mantid::Kernel::QUnit
bool isQUnit () const override
Public Member Functions inherited from Mantid::Kernel::MDUnit
virtual bool canConvertTo (const MDUnit &other) const =0
virtual MDUnit * clone () const =0
virtual UnitLabel getUnitLabel () const =0
virtual bool isQUnit () const =0
bool operator== (const MDUnit &other) const
virtual ~MDUnit ()=default
Private Member Functions
bool isSpecialRLUUnitLabel () const
Private Attributes
UnitLabel m_unitLabel
Detailed Description
Dimensionless RLU.
Definition at line 37 of file MDUnit.h.
Constructor & Destructor Documentation
ReciprocalLatticeUnit() [1/2]
Mantid::Kernel::ReciprocalLatticeUnit::ReciprocalLatticeUnit ()
Definition at line 31 of file MDUnit.cpp.
Referenced by clone().
ReciprocalLatticeUnit() [2/2]
Mantid::Kernel::ReciprocalLatticeUnit::ReciprocalLatticeUnit (UnitLabel unitLabel)
Definition at line 33 of file MDUnit.cpp.
Member Function Documentation
canConvertTo()
bool Mantid::Kernel::ReciprocalLatticeUnit::canConvertTo (const MDUnit & other) const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 43 of file MDUnit.cpp.
clone()
ReciprocalLatticeUnit * Mantid::Kernel::ReciprocalLatticeUnit::clone () const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 45 of file MDUnit.cpp.
References isSpecialRLUUnitLabel(), m_unitLabel, and ReciprocalLatticeUnit().
getUnitLabel()
UnitLabel Mantid::Kernel::ReciprocalLatticeUnit::getUnitLabel () const override virtual
Implements Mantid::Kernel::MDUnit.
Definition at line 35 of file MDUnit.cpp.
References isSpecialRLUUnitLabel(), m_unitLabel, and Mantid::Kernel::Units::Symbol::RLU.
isSpecialRLUUnitLabel()
bool Mantid::Kernel::ReciprocalLatticeUnit::isSpecialRLUUnitLabel () const private
Definition at line 53 of file MDUnit.cpp.
References Mantid::Kernel::UnitLabel::ascii(), and m_unitLabel.
Referenced by clone(), and getUnitLabel().
Member Data Documentation
m_unitLabel
UnitLabel Mantid::Kernel::ReciprocalLatticeUnit::m_unitLabel private
Definition at line 47 of file MDUnit.h.
Referenced by clone(), getUnitLabel(), and isSpecialRLUUnitLabel().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MDUnit.h
Framework/Kernel/src/MDUnit.cpp