Mantid: Mantid::Geometry::IsotropicAtomBraggScattererParser Class Reference
Mantid::Geometry::IsotropicAtomBraggScattererParser Class Reference
#include <IsotropicAtomBraggScatterer.h>
Public Member Functions
IsotropicAtomBraggScattererParser (std::string scattererString)
Constructor for vector with IsotropicAtomBraggScatterers from a string.
std::vector< BraggScatterer_sptr > operator() () const
Operator that returns vector of IsotropicAtomBraggScatterers.
Private Member Functions
std::vector< std::string > getCleanScattererTokens (const std::vector< std::string > &tokens) const
Converts tokens for getScatterer method so they can be processed by factory.
BraggScatterer_sptr getScatterer (const std::string &singleScatterer) const
Returns IsotropicAtomBraggScatterer for string with format "Element x y z occupancy u_iso".
Private Attributes
std::string m_scattererString
Detailed Description
Definition at line 110 of file IsotropicAtomBraggScatterer.h.
Constructor & Destructor Documentation
IsotropicAtomBraggScattererParser()
Mantid::Geometry::IsotropicAtomBraggScattererParser::IsotropicAtomBraggScattererParser (std::string scattererString)
Constructor for vector with IsotropicAtomBraggScatterers from a string.
The functor expects to be constructed from a string in the following format:
Element x y z occupancy u_iso; Element x y z occupancy u_iso; ...
It generates an IsotropicAtomBraggScatterer for each specified atom.
Parameters
scattererString :: String in the format specified above
Definition at line 131 of file IsotropicAtomBraggScatterer.cpp.
Member Function Documentation
getCleanScattererTokens()
std::vector< std::string > Mantid::Geometry::IsotropicAtomBraggScattererParser::getCleanScattererTokens (const std::vector< std::string > & tokens) const private
Converts tokens for getScatterer method so they can be processed by factory.
Definition at line 169 of file IsotropicAtomBraggScatterer.cpp.
Referenced by getScatterer().
getScatterer()
BraggScatterer_sptr Mantid::Geometry::IsotropicAtomBraggScattererParser::getScatterer (const std::string & singleScatterer) const private
Returns IsotropicAtomBraggScatterer for string with format "Element x y z occupancy u_iso".
Definition at line 146 of file IsotropicAtomBraggScatterer.cpp.
References getCleanScattererTokens().
operator()()
std::vector< BraggScatterer_sptr > Mantid::Geometry::IsotropicAtomBraggScattererParser::operator() () const
Operator that returns vector of IsotropicAtomBraggScatterers.
Definition at line 135 of file IsotropicAtomBraggScatterer.cpp.
References Mantid::Kernel::StringTokenizer::cbegin(), Mantid::Kernel::StringTokenizer::cend(), m_scattererString, Mantid::Kernel::StringTokenizer::size(), and Mantid::Kernel::StringTokenizer::TOK_TRIM.
Member Data Documentation
m_scattererString
std::string Mantid::Geometry::IsotropicAtomBraggScattererParser::m_scattererString private
Definition at line 120 of file IsotropicAtomBraggScatterer.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/IsotropicAtomBraggScatterer.h
Framework/Geometry/src/Crystal/IsotropicAtomBraggScatterer.cpp