Mantid: Mantid::CurveFitting::Functions::Convolution::HalfComplex Class Reference
Mantid::CurveFitting::Functions::Convolution::HalfComplex Class Reference
Class for helping to read the transformed data.
#include <Convolution.h>
Public Member Functions
HalfComplex (double *data, const size_t &n)
Constructor.
double imag (size_t i) const
The imaginary part of i-th transform coefficient.
double real (size_t i) const
The real part of i-th transform coefficient.
void set (size_t i, const double &re, const double &im)
Set a new value for i-th complex coefficient.
size_t size () const
Returns the size of the transform.
Private Attributes
double * m_data
pointer to the transformed data
bool m_even
true if the size of the original data is even
size_t m_size
size of the transformed data
Detailed Description
Class for helping to read the transformed data.
It represent an output of the GSL real fast fourier transform routine. The routine transforms an array of n real numbers into an array of about n/2 complex numbers which are the amplitudes of the positive frequencies of the full complex fourier transform.
Definition at line 39 of file Convolution.h.
Constructor & Destructor Documentation
HalfComplex()
Mantid::CurveFitting::Functions::Convolution::HalfComplex::HalfComplex (double * data, const size_t & n) inline
Constructor.
Parameters
data :: A pointer to the transformed complex data
n :: The size of untransformed real data
Definition at line 49 of file Convolution.h.
Member Function Documentation
imag()
double Mantid::CurveFitting::Functions::Convolution::HalfComplex::imag (size_t i) const inline
The imaginary part of i-th transform coefficient.
Parameters
i :: The index of the complex transform coefficient
Returns
The imaginary part
Definition at line 69 of file Convolution.h.
References m_data, and m_size.
Referenced by Mantid::CurveFitting::Functions::Convolution::functionFFTMode().
real()
double Mantid::CurveFitting::Functions::Convolution::HalfComplex::real (size_t i) const inline
The real part of i-th transform coefficient.
Parameters
i :: The index of the complex transform coefficient
Returns
The real part
Definition at line 57 of file Convolution.h.
References m_data, and m_size.
Referenced by Mantid::CurveFitting::Functions::Convolution::functionFFTMode().
set()
void Mantid::CurveFitting::Functions::Convolution::HalfComplex::set (size_t i, const double & re, const double & im) inline
Set a new value for i-th complex coefficient.
Parameters
i :: The index of the coefficient
re :: The real part of the new value
im :: The imaginary part of the new value
Definition at line 84 of file Convolution.h.
References m_data, and m_size.
Referenced by Mantid::CurveFitting::Functions::Convolution::functionFFTMode().
size()
size_t Mantid::CurveFitting::Functions::Convolution::HalfComplex::size () const inline
Returns the size of the transform.
Definition at line 51 of file Convolution.h.
References m_size.
Referenced by Mantid::CurveFitting::Functions::Convolution::functionFFTMode().
Member Data Documentation
m_data
double* Mantid::CurveFitting::Functions::Convolution::HalfComplex::m_data private
pointer to the transformed data
Definition at line 41 of file Convolution.h.
m_even
bool Mantid::CurveFitting::Functions::Convolution::HalfComplex::m_even private
true if the size of the original data is even
Definition at line 42 of file Convolution.h.
m_size
size_t Mantid::CurveFitting::Functions::Convolution::HalfComplex::m_size private
size of the transformed data
Definition at line 40 of file Convolution.h.
The documentation for this class was generated from the following file:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/Convolution.h