Mantid: Mantid::Algorithms::BeamProfileFactory Class Reference
Mantid::Algorithms::BeamProfileFactory Class Reference
#include <BeamProfileFactory.h>
Static Public Member Functions
static std::unique_ptr< IBeamProfile > createBeamProfile (const Geometry::Instrument &instrument, const API::Sample &sample)
Detailed Description
Definition at line 16 of file BeamProfileFactory.h.
Member Function Documentation
createBeamProfile()
std::unique_ptr< IBeamProfile > Mantid::Algorithms::BeamProfileFactory::createBeamProfile (const Geometry::Instrument & instrument, const API::Sample & sample) static
Definition at line 17 of file BeamProfileFactory.cpp.
References Mantid::Geometry::SampleEnvironment::boundingBox(), Mantid::Geometry::BoundingBox::centrePoint(), Mantid::Geometry::IObject::getBoundingBox(), Mantid::API::Sample::getEnvironment(), Mantid::Geometry::Instrument::getReferenceFrame(), Mantid::API::Sample::getShape(), Mantid::Geometry::Instrument::getSource(), Mantid::API::Sample::hasEnvironment(), Mantid::Geometry::IObject::hasValidShape(), and Mantid::Geometry::BoundingBox::width().
Referenced by Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareSampleBeamGeometry().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/BeamProfileFactory.h
Framework/Algorithms/src/BeamProfileFactory.cpp