Mantid: Mantid::Geometry::PeakTransformSelector Class Reference
Mantid::Geometry::PeakTransformSelector Class Reference
Used to choose an appropriate PeakTransformFactory.
#include <PeakTransformSelector.h>
Public Member Functions
bool hasFactoryForTransform (const std::string &labelX, const std::string &labelY) const
Has a factory capable of the requested transform.
PeakTransformFactory_sptr makeChoice (const std::string &labelX, const std::string &labelY) const
Make choice.
PeakTransformFactory_sptr makeDefaultChoice () const
Make default choice.
size_t numberRegistered () const
Get the number of registered factories.
PeakTransformSelector ()
Constructor.
void registerCandidate (const PeakTransformFactory_sptr &candidate)
Register a candidate factory.
Private Types
using Factories = std::set< PeakTransformFactory_sptr >
Collection of candidate factories.
Private Member Functions
PeakTransformSelector & operator= (const PeakTransformSelector &)
Disabled assigment operator.
PeakTransformSelector (const PeakTransformSelector &)
Disabled copy constructor.
Private Attributes
Factories m_candidateFactories
Detailed Description
Used to choose an appropriate PeakTransformFactory.
Definition at line 18 of file PeakTransformSelector.h.
Member Typedef Documentation
Factories
using Mantid::Geometry::PeakTransformSelector::Factories = std::set<PeakTransformFactory_sptr> private
Collection of candidate factories.
Definition at line 39 of file PeakTransformSelector.h.
Constructor & Destructor Documentation
PeakTransformSelector() [1/2]
Mantid::Geometry::PeakTransformSelector::PeakTransformSelector () default
Constructor.
PeakTransformSelector() [2/2]
Mantid::Geometry::PeakTransformSelector::PeakTransformSelector (const PeakTransformSelector &) private
Disabled copy constructor.
Member Function Documentation
hasFactoryForTransform()
bool Mantid::Geometry::PeakTransformSelector::hasFactoryForTransform (const std::string & labelX, const std::string & labelY) const
Has a factory capable of the requested transform.
Can any of the registered peak transform factories peform the requested transformation.
Parameters
labelX X-label to use in determining selection.
labelY Y-label to use in determining selection.
Returns
TRUE only if such a factory is available.
Definition at line 98 of file PeakTransformSelector.cpp.
References hasFactoryForTransform(), and makeChoice().
Referenced by hasFactoryForTransform().
makeChoice()
PeakTransformFactory_sptr Mantid::Geometry::PeakTransformSelector::makeChoice (const std::string & labelX, const std::string & labelY) const
Make choice.
Make a choice for the peak transform factory.
Parameters
labelX X-label to use in determining selection.
labelY Y-label to use in determining selection.
Returns
selected factory
Definition at line 59 of file PeakTransformSelector.cpp.
References m_candidateFactories, and numberRegistered().
Referenced by hasFactoryForTransform().
makeDefaultChoice()
PeakTransformFactory_sptr Mantid::Geometry::PeakTransformSelector::makeDefaultChoice () const
Make default choice.
Make a choice for the peak transform factory, but use the default labels known to each factory.
Returns
selected factory
Definition at line 32 of file PeakTransformSelector.cpp.
References m_candidateFactories, and numberRegistered().
numberRegistered()
size_t Mantid::Geometry::PeakTransformSelector::numberRegistered () const
Get the number of registered factories.
Returns
the number of registered candidates.
Definition at line 25 of file PeakTransformSelector.cpp.
References m_candidateFactories.
Referenced by makeChoice(), and makeDefaultChoice().
operator=()
PeakTransformSelector & Mantid::Geometry::PeakTransformSelector::operator= (const PeakTransformSelector &) private
Disabled assigment operator.
registerCandidate()
void Mantid::Geometry::PeakTransformSelector::registerCandidate (const PeakTransformFactory_sptr & candidate)
Register a candidate factory.
Register a peak transform factory as a candidate.
Parameters
candidate : candidate peak transform factory
Definition at line 18 of file PeakTransformSelector.cpp.
References m_candidateFactories.
Member Data Documentation
m_candidateFactories
Factories Mantid::Geometry::PeakTransformSelector::m_candidateFactories private
Definition at line 40 of file PeakTransformSelector.h.
Referenced by makeChoice(), makeDefaultChoice(), numberRegistered(), and registerCandidate().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/PeakTransformSelector.h
Framework/Geometry/src/Crystal/PeakTransformSelector.cpp