Mantid: Mantid::DataHandling::LoadEventPreNexus2 Class Reference
Mantid::DataHandling::LoadEventPreNexus2 Class Reference
A data loading routine for SNS pre-nexus event files.
#include <LoadEventPreNexus2.h>
Public Member Functions
const std::string alias () const override
Algorithm's aliases.
const std::string category () const override
Algorithm's category for identification.
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadEventPreNexus2 ()
Constructor.
const std::string name () const override
Algorithm's name.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Public Member Functions inherited from Mantid::API::DeprecatedAlgorithm
DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
void deprecatedDate (const std::string &)
The date the algorithm was deprecated on.
std::string deprecationMsg (const IAlgorithm *)
This merely prints the deprecation error for people to see.
void useAlgorithm (const std::string &, const int version=-1)
The algorithm to use instead of this one.
virtual ~DeprecatedAlgorithm ()
Does nothing other than make the compiler happy.
Private Member Functions
void addToWorkspaceLog (const std::string &logtitle, size_t mindex)
Add absolute time series to log.
void createOutputWorkspace (const std::string &event_filename)
Create and set up output Event Workspace.
void debugOutput (bool doit, size_t mindex)
void exec () override
Execution code.
void fixPixelId (PixelType &pixel, uint32_t &period) const
Turn a pixel id into a "corrected" pixelid and period.
API::MatrixWorkspace_sptr generateEventDistribtionWorkspace ()
Generate a workspace with distribution of events with pulse Workspace has 2 spectrum.
void init () override
Initialisation code.
void loadPixelMap (const std::string &filename)
Load a pixel mapping file.
void openEventFile (const std::string &filename)
Open an event file.
void processImbedLogs ()
Process imbed logs (marked by bad pixel IDs)
void processInvestigationInputs ()
Processing the input properties for purpose of investigation.
void procEvents (DataObjects::EventWorkspace_sptr &workspace)
Process the event file properly in parallel.
void procEventsLinear (DataObjects::EventWorkspace_sptr &workspace, std::vector< Types::Event::TofEvent > **arrayOfVectors, DasEvent *event_buffer, size_t current_event_buffer_size, size_t fileOffset, bool dbprint)
Linear-version of the procedure to process the event file properly.
void readPulseidFile (const std::string &filename, const bool throwError)
Read a pulse ID file.
void runLoadInstrument (const std::string &eventfilename, const API::MatrixWorkspace_sptr &localWorkspace)
Load the instrument geometry File.
void setProtonCharge (DataObjects::EventWorkspace_sptr &workspace)
Add a sample environment log for the proton chage (charge of the pulse in picoCoulombs) and set the scalar value (total proton charge, microAmps*hours, on the sample)
void unmaskVetoEventIndex ()
Some Pulse ID and event indexes might be wrong.
Private Attributes
Mantid::detid_t detid_max
The maximum detector ID possible.
std::vector< uint64_t > event_indices
The index of the first event in each pulse.
std::unique_ptr< Mantid::Kernel::BinaryFile< DasEvent > > eventfile
Handles loading from the event file.
std::size_t first_event
The first event to load (count from zero)
bool loadOnlySomeSpectra
For loading only some spectra.
DataObjects::EventWorkspace_sptr localWorkspace
double longest_tof
Longest TOF limit.
int m_dbOpBlockNumber
size_t m_dbOpNumEvents
size_t m_dbOpNumPulses
bool m_dbOutput
Investigation properties.
std::size_t max_events
Number of events to load.
std::vector< detid_t > mSEids
sample environment event
std::map< size_t, detid_t > mSEmap
std::vector< std::vector< int64_t > > mSEpulseids
std::vector< std::vector< double > > mSEtofs
std::size_t num_bad_events
The number of bad events.
std::size_t num_error_events
The number of error events encountered.
std::size_t num_events
The number of events in the file.
std::size_t num_good_events
The number of good events loaded.
std::size_t num_ignored_events
the number of events that were ignored (not loaded) because, e.g.
std::size_t num_pulses
the number of pulses
std::size_t num_wrongdetid_events
The number of events with wrong.
uint32_t numpixel
the number of pixels
bool parallelProcessing
Flag to allow for parallel loading.
std::vector< std::size_t > pixel_to_wkspindex
The value of the vector is the workspace index.
std::vector< PixelType > pixelmap
Map between the DAS pixel IDs and our pixel IDs, used while loading.
std::unique_ptr< Mantid::API::Progress > prog = nullptr
std::vector< double > proton_charge
The proton charge on a pulse by pulse basis.
double proton_charge_tot
The total proton charge for the run.
std::vector< Types::Core::DateAndTime > pulsetimes
The times for each pulse.
bool pulsetimesincreasing
Whether or not the pulse times are sorted in increasing order.
double shortest_tof
Shortest TOF limit.
std::vector< int64_t > spectra_list
the list of Spectra
std::map< int64_t, bool > spectraLoadMap
Handle to the loaded spectra map.
bool using_mapping_file
Set to true if a valid Mapping file was provided.
std::vector< std::vector< Types::Core::DateAndTime > > wrongdetid_pulsetimes
std::vector< std::vector< double > > wrongdetid_tofs
std::map< PixelType, size_t > wrongdetidmap
std::set< PixelType > wrongdetids
detector IDs. Part of error events.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
A data loading routine for SNS pre-nexus event files.
Definition at line 78 of file LoadEventPreNexus2.h.
Constructor & Destructor Documentation
LoadEventPreNexus2()
Mantid::DataHandling::LoadEventPreNexus2::LoadEventPreNexus2 ()
Constructor.
Definition at line 228 of file LoadEventPreNexus2.cpp.
References Mantid::API::DeprecatedAlgorithm::deprecatedDate().
Member Function Documentation
addToWorkspaceLog()
void Mantid::DataHandling::LoadEventPreNexus2::addToWorkspaceLog (const std::string & logtitle, size_t mindex) private
Add absolute time series to log.
Use TOF as log value for this type of events
Parameters
logtitle :: name of the log
mindex :: index of the log in pulse time ...
mindex: index of the series in the list
Definition at line 544 of file LoadEventPreNexus2.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), localWorkspace, wrongdetid_pulsetimes, and wrongdetid_tofs.
Referenced by processImbedLogs().
alias()
const std::string Mantid::DataHandling::LoadEventPreNexus2::alias () const inline override virtual
Algorithm's aliases.
Reimplemented from Mantid::API::Algorithm.
Definition at line 91 of file LoadEventPreNexus2.h.
category()
const std::string Mantid::DataHandling::LoadEventPreNexus2::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 89 of file LoadEventPreNexus2.h.
confidence()
int Mantid::DataHandling::LoadEventPreNexus2::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 201 of file LoadEventPreNexus2.cpp.
References Mantid::Kernel::FileDescriptor::data(), Mantid::Kernel::FileDescriptor::extension(), and Mantid::Kernel::FileDescriptor::isAscii().
createOutputWorkspace()
void Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace (const std::string & event_filename) private
Create and set up output Event Workspace.
Definition at line 388 of file LoadEventPreNexus2.cpp.
References Mantid::API::Algorithm::g_log, Mantid::DataHandling::generateMappingfileName(), Mantid::API::Algorithm::getPropertyValue(), Mantid::DataHandling::getRunnumber(), Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), loadPixelMap(), localWorkspace, Mantid::DataHandling::MAP_PARAM(), num_pulses, prog, pulsetimes, runLoadInstrument(), spectra_list, and tmp.
Referenced by exec().
debugOutput()
void Mantid::DataHandling::LoadEventPreNexus2::debugOutput (bool doit, size_t mindex) private
exec()
void Mantid::DataHandling::LoadEventPreNexus2::exec () override private virtual
Execution code.
Execute the algorithm Procedure:
check all the inputs
create an EventWorkspace object
process events
set out output
Implements Mantid::API::Algorithm.
Definition at line 321 of file LoadEventPreNexus2.cpp.
References createOutputWorkspace(), Mantid::DataHandling::EVENT_PARAM(), Mantid::API::Algorithm::g_log, generateEventDistribtionWorkspace(), Mantid::DataHandling::generatePulseidName(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), localWorkspace, openEventFile(), Mantid::DataHandling::OUT_PARAM(), Mantid::DataHandling::PID_PARAM(), processImbedLogs(), processInvestigationInputs(), procEvents(), prog, Mantid::DataHandling::PULSEID_PARAM(), readPulseidFile(), Mantid::Kernel::IPropertyManager::setProperty(), spectra_list, and unmaskVetoEventIndex().
fixPixelId()
void Mantid::DataHandling::LoadEventPreNexus2::fixPixelId (PixelType & pixel, uint32_t & period) const inline private
Turn a pixel id into a "corrected" pixelid and period.
Definition at line 611 of file LoadEventPreNexus2.cpp.
References numpixel, pixelmap, and using_mapping_file.
generateEventDistribtionWorkspace()
API::MatrixWorkspace_sptr Mantid::DataHandling::LoadEventPreNexus2::generateEventDistribtionWorkspace () private
Generate a workspace with distribution of events with pulse Workspace has 2 spectrum.
spectrum 0 is the number of events in one pulse. specrum 1 is the accumulated number of events
Definition at line 473 of file LoadEventPreNexus2.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::Logger::debug(), event_indices, Mantid::API::Algorithm::g_log, Mantid::Kernel::SingletonHolder< T >::Instance(), and pulsetimes.
Referenced by exec().
init()
void Mantid::DataHandling::LoadEventPreNexus2::init () override private virtual
Initialisation code.
Initialize the algorithm, i.e, declare properties.
Implements Mantid::API::Algorithm.
Definition at line 241 of file LoadEventPreNexus2.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_INT(), Mantid::DataHandling::EVENT_EXTS, Mantid::DataHandling::EVENT_PARAM(), Mantid::Kernel::IS_NOT_DEFAULT, Mantid::API::FileProperty::Load, Mantid::DataHandling::MAP_PARAM(), Mantid::DataHandling::NUM_EXT, Mantid::API::PropertyMode::Optional, Mantid::API::FileProperty::OptionalLoad, Mantid::DataHandling::OUT_PARAM(), Mantid::Kernel::Direction::Output, Mantid::DataHandling::PID_PARAM(), Mantid::DataHandling::PULSE_EXTS, Mantid::DataHandling::PULSEID_PARAM(), Mantid::Kernel::IPropertyManager::setPropertyGroup(), and Mantid::Kernel::IPropertyManager::setPropertySettings().
loadPixelMap()
void Mantid::DataHandling::LoadEventPreNexus2::loadPixelMap (const std::string & filename) private
Load a pixel mapping file.
Parameters
filename :: Path to file.
Definition at line 1146 of file LoadEventPreNexus2.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::Kernel::BinaryFile< T >::getNumElements(), Mantid::Kernel::Logger::information(), Mantid::Kernel::BinaryFile< T >::loadAllIntoVector(), numpixel, pixelmap, using_mapping_file, and Mantid::Kernel::Logger::warning().
Referenced by createOutputWorkspace().
name()
const std::string Mantid::DataHandling::LoadEventPreNexus2::name () const inline override virtual
Algorithm's name.
Implements Mantid::API::Algorithm.
Definition at line 84 of file LoadEventPreNexus2.h.
openEventFile()
void Mantid::DataHandling::LoadEventPreNexus2::openEventFile (const std::string & filename) private
Open an event file.
Parameters
filename :: file to open.
Definition at line 1187 of file LoadEventPreNexus2.cpp.
References Mantid::Kernel::Logger::debug(), eventfile, first_event, Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), Mantid::API::Algorithm::isEmpty(), max_events, and num_events.
Referenced by exec().
processImbedLogs()
void Mantid::DataHandling::LoadEventPreNexus2::processImbedLogs () private
Process imbed logs (marked by bad pixel IDs)
Definition at line 512 of file LoadEventPreNexus2.cpp.
References addToWorkspaceLog(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::Logger::notice(), wrongdetid_pulsetimes, wrongdetidmap, and wrongdetids.
Referenced by exec().
processInvestigationInputs()
void Mantid::DataHandling::LoadEventPreNexus2::processInvestigationInputs () private
Processing the input properties for purpose of investigation.
Process input properties for purpose of investigation.
Definition at line 1285 of file LoadEventPreNexus2.cpp.
References Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::isEmpty(), m_dbOpBlockNumber, m_dbOpNumEvents, m_dbOpNumPulses, and m_dbOutput.
Referenced by exec().
procEvents()
void Mantid::DataHandling::LoadEventPreNexus2::procEvents (DataObjects::EventWorkspace_sptr & workspace) private
Process the event file properly in parallel.
Parameters
workspace :: EventWorkspace to write to.
Pointer to the vector of events
Bare array of arrays of pointers to the EventVectors
How many threads will we use?
Definition at line 626 of file LoadEventPreNexus2.cpp.
References Mantid::DataObjects::EventList::clear(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::DEFAULT_BLOCK_SIZE, detid_max, eventfile, first_event, Mantid::API::Algorithm::g_log, Mantid::DataObjects::EventList::getEvents(), Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Logger::information(), loadOnlySomeSpectra, longest_tof, m_dbOpBlockNumber, m_dbOutput, max_events, Mantid::DataHandling::MAX_TOF_UINT32, Mantid::Kernel::Logger::notice(), num_bad_events, num_error_events, num_good_events, num_ignored_events, num_wrongdetid_events, Mantid::DataHandling::numEvents(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_CRITICAL, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_GET_MAX_THREADS, PARALLEL_START_INTERRUPT_REGION, PARALLEL_THREAD_NUMBER, parallelProcessing, pixel_to_wkspindex, PRAGMA_OMP, procEventsLinear(), prog, Mantid::DataObjects::EventList::reserve(), Mantid::API::ISpectrum::setDetectorID(), setProtonCharge(), Mantid::API::ISpectrum::setSpectrumNo(), shortest_tof, spectra_list, spectraLoadMap, workspace, wrongdetid_pulsetimes, wrongdetidmap, and wrongdetids.
Referenced by exec().
procEventsLinear()
void Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear (DataObjects::EventWorkspace_sptr & workspace, std::vector< Types::Event::TofEvent > ** arrayOfVectors, DasEvent * event_buffer, size_t current_event_buffer_size, size_t fileOffset, bool dbprint) private
Linear-version of the procedure to process the event file properly.
Parameters
workspace :: EventWorkspace to write to.
arrayOfVectors :: For speed up: this is an array, of size detid_max+1, where the index is a pixel ID, and the value is a pointer to the vector<tofEvent> in the given EventList.
event_buffer :: The buffer containing the DAS events
current_event_buffer_size :: The length of the given DAS buffer
fileOffset :: Value for an offset into the binary file
dbprint :: flag to print out events information
Definition at line 912 of file LoadEventPreNexus2.cpp.
References Mantid::Kernel::Logger::debug(), detid_max, Mantid::DataHandling::ERROR_PID, event_indices, Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), loadOnlySomeSpectra, longest_tof, m_dbOpNumEvents, Mantid::DataHandling::MAX_TOF_UINT32, num_bad_events, num_error_events, num_good_events, num_ignored_events, num_pulses, num_wrongdetid_events, numpixel, PARALLEL_CRITICAL, Mantid::DataHandling::DasEvent::pid, pixelmap, pulsetimes, shortest_tof, spectraLoadMap, Mantid::DataHandling::DasEvent::tof, Mantid::DataHandling::TOF_CONVERSION, using_mapping_file, Mantid::Kernel::Logger::warning(), wrongdetid_pulsetimes, wrongdetid_tofs, wrongdetidmap, and wrongdetids.
Referenced by procEvents().
readPulseidFile()
void Mantid::DataHandling::LoadEventPreNexus2::readPulseidFile (const std::string & filename, const bool throwError) private
Read a pulse ID file.
Parameters
filename :: file to load.
throwError :: Flag to trigger error throwing instead of just logging
Definition at line 1217 of file LoadEventPreNexus2.cpp.
References Mantid::DataHandling::CURRENT_CONVERSION, event_indices, Mantid::API::Algorithm::g_log, Mantid::Kernel::BinaryFile< T >::getNumElements(), Mantid::Kernel::Logger::information(), Mantid::Kernel::BinaryFile< T >::loadAll(), m_dbOpNumPulses, num_pulses, proton_charge, proton_charge_tot, pulsetimes, pulsetimesincreasing, and Mantid::Kernel::Logger::warning().
Referenced by exec().
runLoadInstrument()
void Mantid::DataHandling::LoadEventPreNexus2::runLoadInstrument (const std::string & eventfilename, const API::MatrixWorkspace_sptr & localWorkspace) private
Load the instrument geometry File.
Parameters
eventfilename :: Used to pick the instrument.
localWorkspace :: MatrixWorkspace in which to put the instrument geometry
Definition at line 571 of file LoadEventPreNexus2.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::DataHandling::EVENT_EXTS, localWorkspace, and Mantid::DataHandling::NUM_EXT.
Referenced by createOutputWorkspace().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::LoadEventPreNexus2::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 87 of file LoadEventPreNexus2.h.
setProtonCharge()
void Mantid::DataHandling::LoadEventPreNexus2::setProtonCharge (DataObjects::EventWorkspace_sptr & workspace) private
Add a sample environment log for the proton chage (charge of the pulse in picoCoulombs) and set the scalar value (total proton charge, microAmps*hours, on the sample)
Parameters
workspace :: Event workspace to set the proton charge on
TODO set the units for the log
Definition at line 1119 of file LoadEventPreNexus2.cpp.
References Mantid::API::LogManager::addLogData(), Mantid::Kernel::TimeSeriesProperty< TYPE >::addValues(), Mantid::API::Algorithm::g_log, Mantid::API::Run::getProtonCharge(), Mantid::Kernel::Logger::information(), Mantid::API::Run::integrateProtonCharge(), proton_charge, pulsetimes, Mantid::Kernel::Property::setUnits(), and workspace.
Referenced by procEvents().
summary()
const std::string Mantid::DataHandling::LoadEventPreNexus2::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 93 of file LoadEventPreNexus2.h.
unmaskVetoEventIndex()
void Mantid::DataHandling::LoadEventPreNexus2::unmaskVetoEventIndex () private
Some Pulse ID and event indexes might be wrong.
Remove them.
Definition at line 443 of file LoadEventPreNexus2.cpp.
References event_indices, Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), max_events, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_NO_WSP_CHECK, PARALLEL_START_INTERRUPT_REGION, and Mantid::DataHandling::VETOFLAG().
Referenced by exec().
version()
int Mantid::DataHandling::LoadEventPreNexus2::version () const inline override virtual
Algorithm's version.
Implements Mantid::API::Algorithm.
Definition at line 86 of file LoadEventPreNexus2.h.
Member Data Documentation
detid_max
Mantid::detid_t Mantid::DataHandling::LoadEventPreNexus2::detid_max private
The maximum detector ID possible.
Definition at line 126 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
event_indices
std::vector<uint64_t> Mantid::DataHandling::LoadEventPreNexus2::event_indices private
The index of the first event in each pulse.
Definition at line 114 of file LoadEventPreNexus2.h.
Referenced by generateEventDistribtionWorkspace(), procEventsLinear(), readPulseidFile(), and unmaskVetoEventIndex().
eventfile
std::unique_ptr<Mantid::Kernel::BinaryFile<DasEvent> > Mantid::DataHandling::LoadEventPreNexus2::eventfile private
Handles loading from the event file.
Definition at line 129 of file LoadEventPreNexus2.h.
Referenced by openEventFile(), and procEvents().
first_event
std::size_t Mantid::DataHandling::LoadEventPreNexus2::first_event private
The first event to load (count from zero)
Definition at line 148 of file LoadEventPreNexus2.h.
Referenced by openEventFile(), and procEvents().
loadOnlySomeSpectra
bool Mantid::DataHandling::LoadEventPreNexus2::loadOnlySomeSpectra private
For loading only some spectra.
Definition at line 155 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
localWorkspace
DataObjects::EventWorkspace_sptr Mantid::DataHandling::LoadEventPreNexus2::localWorkspace private
Definition at line 108 of file LoadEventPreNexus2.h.
Referenced by addToWorkspaceLog(), createOutputWorkspace(), exec(), and runLoadInstrument().
longest_tof
double Mantid::DataHandling::LoadEventPreNexus2::longest_tof private
Longest TOF limit.
Definition at line 160 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
m_dbOpBlockNumber
int Mantid::DataHandling::LoadEventPreNexus2::m_dbOpBlockNumber private
Definition at line 178 of file LoadEventPreNexus2.h.
Referenced by processInvestigationInputs(), and procEvents().
m_dbOpNumEvents
size_t Mantid::DataHandling::LoadEventPreNexus2::m_dbOpNumEvents private
Definition at line 179 of file LoadEventPreNexus2.h.
Referenced by processInvestigationInputs(), and procEventsLinear().
m_dbOpNumPulses
size_t Mantid::DataHandling::LoadEventPreNexus2::m_dbOpNumPulses private
Definition at line 180 of file LoadEventPreNexus2.h.
Referenced by processInvestigationInputs(), and readPulseidFile().
m_dbOutput
bool Mantid::DataHandling::LoadEventPreNexus2::m_dbOutput private
Investigation properties.
Definition at line 177 of file LoadEventPreNexus2.h.
Referenced by processInvestigationInputs(), and procEvents().
max_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::max_events private
Number of events to load.
Definition at line 149 of file LoadEventPreNexus2.h.
Referenced by openEventFile(), procEvents(), and unmaskVetoEventIndex().
mSEids
std::vector<detid_t> Mantid::DataHandling::LoadEventPreNexus2::mSEids private
sample environment event
Definition at line 171 of file LoadEventPreNexus2.h.
mSEmap
std::map<size_t, detid_t> Mantid::DataHandling::LoadEventPreNexus2::mSEmap private
Definition at line 172 of file LoadEventPreNexus2.h.
mSEpulseids
std::vector<std::vector<int64_t> > Mantid::DataHandling::LoadEventPreNexus2::mSEpulseids private
Definition at line 173 of file LoadEventPreNexus2.h.
mSEtofs
std::vector<std::vector<double> > Mantid::DataHandling::LoadEventPreNexus2::mSEtofs private
Definition at line 174 of file LoadEventPreNexus2.h.
num_bad_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_bad_events private
The number of bad events.
Part of error events
Definition at line 136 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
num_error_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_error_events private
The number of error events encountered.
Definition at line 135 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
num_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_events private
The number of events in the file.
Definition at line 130 of file LoadEventPreNexus2.h.
Referenced by openEventFile().
num_good_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_good_events private
The number of good events loaded.
Definition at line 134 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
num_ignored_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_ignored_events private
the number of events that were ignored (not loaded) because, e.g.
of only loading some spectra.
Definition at line 147 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
num_pulses
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_pulses private
the number of pulses
Definition at line 131 of file LoadEventPreNexus2.h.
Referenced by createOutputWorkspace(), procEventsLinear(), and readPulseidFile().
num_wrongdetid_events
std::size_t Mantid::DataHandling::LoadEventPreNexus2::num_wrongdetid_events private
The number of events with wrong.
Definition at line 138 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
numpixel
uint32_t Mantid::DataHandling::LoadEventPreNexus2::numpixel private
the number of pixels
Definition at line 132 of file LoadEventPreNexus2.h.
Referenced by fixPixelId(), loadPixelMap(), and procEventsLinear().
parallelProcessing
bool Mantid::DataHandling::LoadEventPreNexus2::parallelProcessing private
Flag to allow for parallel loading.
Definition at line 165 of file LoadEventPreNexus2.h.
Referenced by procEvents().
pixel_to_wkspindex
std::vector<std::size_t> Mantid::DataHandling::LoadEventPreNexus2::pixel_to_wkspindex private
The value of the vector is the workspace index.
The index into it is the pixel ID from DAS
Definition at line 121 of file LoadEventPreNexus2.h.
Referenced by procEvents().
pixelmap
std::vector<PixelType> Mantid::DataHandling::LoadEventPreNexus2::pixelmap private
Map between the DAS pixel IDs and our pixel IDs, used while loading.
Definition at line 123 of file LoadEventPreNexus2.h.
Referenced by fixPixelId(), loadPixelMap(), and procEventsLinear().
prog
std::unique_ptr<Mantid::API::Progress> Mantid::DataHandling::LoadEventPreNexus2::prog = nullptr private
Definition at line 106 of file LoadEventPreNexus2.h.
Referenced by createOutputWorkspace(), exec(), and procEvents().
proton_charge
std::vector<double> Mantid::DataHandling::LoadEventPreNexus2::proton_charge private
The proton charge on a pulse by pulse basis.
Definition at line 116 of file LoadEventPreNexus2.h.
Referenced by readPulseidFile(), and setProtonCharge().
proton_charge_tot
double Mantid::DataHandling::LoadEventPreNexus2::proton_charge_tot private
The total proton charge for the run.
Definition at line 118 of file LoadEventPreNexus2.h.
Referenced by readPulseidFile().
pulsetimes
std::vector<Types::Core::DateAndTime> Mantid::DataHandling::LoadEventPreNexus2::pulsetimes private
The times for each pulse.
Definition at line 112 of file LoadEventPreNexus2.h.
Referenced by createOutputWorkspace(), generateEventDistribtionWorkspace(), procEventsLinear(), readPulseidFile(), and setProtonCharge().
pulsetimesincreasing
bool Mantid::DataHandling::LoadEventPreNexus2::pulsetimesincreasing private
Whether or not the pulse times are sorted in increasing order.
Definition at line 168 of file LoadEventPreNexus2.h.
Referenced by readPulseidFile().
shortest_tof
double Mantid::DataHandling::LoadEventPreNexus2::shortest_tof private
Shortest TOF limit.
Definition at line 162 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
spectra_list
std::vector<int64_t> Mantid::DataHandling::LoadEventPreNexus2::spectra_list private
the list of Spectra
Definition at line 109 of file LoadEventPreNexus2.h.
Referenced by createOutputWorkspace(), exec(), and procEvents().
spectraLoadMap
std::map<int64_t, bool> Mantid::DataHandling::LoadEventPreNexus2::spectraLoadMap private
Handle to the loaded spectra map.
Definition at line 157 of file LoadEventPreNexus2.h.
Referenced by procEvents(), and procEventsLinear().
using_mapping_file
bool Mantid::DataHandling::LoadEventPreNexus2::using_mapping_file private
Set to true if a valid Mapping file was provided.
Definition at line 152 of file LoadEventPreNexus2.h.
Referenced by fixPixelId(), loadPixelMap(), and procEventsLinear().
wrongdetid_pulsetimes
std::vector<std::vector<Types::Core::DateAndTime> > Mantid::DataHandling::LoadEventPreNexus2::wrongdetid_pulsetimes private
Definition at line 142 of file LoadEventPreNexus2.h.
Referenced by addToWorkspaceLog(), processImbedLogs(), procEvents(), and procEventsLinear().
wrongdetid_tofs
std::vector<std::vector<double> > Mantid::DataHandling::LoadEventPreNexus2::wrongdetid_tofs private
Definition at line 143 of file LoadEventPreNexus2.h.
Referenced by addToWorkspaceLog(), and procEventsLinear().
wrongdetidmap
std::map<PixelType, size_t> Mantid::DataHandling::LoadEventPreNexus2::wrongdetidmap private
Definition at line 141 of file LoadEventPreNexus2.h.
Referenced by processImbedLogs(), procEvents(), and procEventsLinear().
wrongdetids
std::set<PixelType> Mantid::DataHandling::LoadEventPreNexus2::wrongdetids private
detector IDs. Part of error events.
set of all wrong detector IDs
Definition at line 140 of file LoadEventPreNexus2.h.
Referenced by processImbedLogs(), procEvents(), and procEventsLinear().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadEventPreNexus2.h
Framework/DataHandling/src/LoadEventPreNexus2.cpp