Mantid: ICat4::ns1__instrument Class Reference
ICat4::ns1__instrument Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__instrument ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * description
ns1__facility * facility
std::string * fullName
std::vector< ns1__instrumentScientist * > instrumentScientists
std::vector< ns1__investigationInstrument * > investigationInstruments
std::string * name
std::string * type
std::string * url
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1746 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__instrument()
ICat4::ns1__instrument::ns1__instrument () inline
Definition at line 1766 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__instrument::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14567 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__instrumentScientist(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationInstrument().
Referenced by ICat4::soap_in_ns1__instrument(), ICat4::soap_new_req_ns1__instrument(), and ICat4::soap_new_set_ns1__instrument().
soap_get()
void * ICat4::ns1__instrument::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14773 of file ICat4C.cpp.
References ICat4::soap_get_ns1__instrument().
soap_in()
void * ICat4::ns1__instrument::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14642 of file ICat4C.cpp.
References ICat4::soap_in_ns1__instrument().
Referenced by ICat4::soap_in_ns1__instrument().
soap_out()
int ICat4::ns1__instrument::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14601 of file ICat4C.cpp.
References ICat4::soap_out_ns1__instrument().
soap_put()
int ICat4::ns1__instrument::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14766 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__instrument.
soap_serialize()
void ICat4::ns1__instrument::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14583 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__instrumentScientist(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationInstrument().
soap_type()
int ICat4::ns1__instrument::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1759 of file ICat4Stub.h.
Member Data Documentation
description
std::string* ICat4::ns1__instrument::description
Definition at line 1748 of file ICat4Stub.h.
facility
ns1__facility* ICat4::ns1__instrument::facility
Definition at line 1749 of file ICat4Stub.h.
fullName
std::string* ICat4::ns1__instrument::fullName
Definition at line 1750 of file ICat4Stub.h.
instrumentScientists
std::vector<ns1__instrumentScientist *> ICat4::ns1__instrument::instrumentScientists
Definition at line 1751 of file ICat4Stub.h.
investigationInstruments
std::vector<ns1__investigationInstrument *> ICat4::ns1__instrument::investigationInstruments
Definition at line 1753 of file ICat4Stub.h.
name
std::string* ICat4::ns1__instrument::name
Definition at line 1755 of file ICat4Stub.h.
type
std::string* ICat4::ns1__instrument::type
Definition at line 1756 of file ICat4Stub.h.
url
std::string* ICat4::ns1__instrument::url
Definition at line 1757 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp