Mantid: Mantid::WorkflowAlgorithms::LoadEventAndCompress Class Reference
Mantid::WorkflowAlgorithms::LoadEventAndCompress Class Reference
LoadEventAndCompress : TODO: DESCRIPTION.
#include <LoadEventAndCompress.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Protected Member Functions
API::ITableWorkspace_sptr determineChunk (const std::string &filename) override
API::MatrixWorkspace_sptr loadChunk (const size_t rowIndex) override
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Private Member Functions
void exec () override
Execute the algorithm.
void init () override
Initialize the algorithm's properties.
Private Attributes
API::ITableWorkspace_sptr m_chunkingTable
double m_filterBadPulses
Detailed Description
LoadEventAndCompress : TODO: DESCRIPTION.
Definition at line 18 of file LoadEventAndCompress.h.
Member Function Documentation
category()
const string Mantid::WorkflowAlgorithms::LoadEventAndCompress::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 37 of file LoadEventAndCompress.cpp.
determineChunk()
ITableWorkspace_sptr Mantid::WorkflowAlgorithms::LoadEventAndCompress::determineChunk (const std::string & filename) override protected virtual
See also
DataProcessorAlgorithm::determineChunk(const std::string &)
Reimplemented from Mantid::API::GenericDataProcessorAlgorithm< Base >.
Definition at line 104 of file LoadEventAndCompress.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::API::g_log, Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), and Mantid::Kernel::Logger::information().
Referenced by exec().
exec()
void Mantid::WorkflowAlgorithms::LoadEventAndCompress::exec () override private
Execute the algorithm.
Definition at line 185 of file LoadEventAndCompress.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), determineChunk(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue(), loadChunk(), m_chunkingTable, m_filterBadPulses, Mantid::Kernel::ProgressBase::report(), and Mantid::Kernel::ProgressBase::resetNumSteps().
init()
void Mantid::WorkflowAlgorithms::LoadEventAndCompress::init () override private
Initialize the algorithm's properties.
Definition at line 45 of file LoadEventAndCompress.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::copyProperty(), and Mantid::Kernel::IS_EQUAL_TO.
loadChunk()
MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::LoadEventAndCompress::loadChunk (const size_t rowIndex) override protected virtual
See also
DataProcessorAlgorithm::loadChunk(const size_t)
Reimplemented from Mantid::API::GenericDataProcessorAlgorithm< Base >.
Definition at line 122 of file LoadEventAndCompress.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::g_log, Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), m_chunkingTable, and m_filterBadPulses.
Referenced by exec().
name()
const string Mantid::WorkflowAlgorithms::LoadEventAndCompress::name () const override
Algorithms name for identification.
See also
Algorithm::name
Definition at line 31 of file LoadEventAndCompress.cpp.
seeAlso()
const std::vector< std::string > Mantid::WorkflowAlgorithms::LoadEventAndCompress::seeAlso () const inline override
Definition at line 22 of file LoadEventAndCompress.h.
summary()
const string Mantid::WorkflowAlgorithms::LoadEventAndCompress::summary () const override
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Definition at line 40 of file LoadEventAndCompress.cpp.
version()
int Mantid::WorkflowAlgorithms::LoadEventAndCompress::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 34 of file LoadEventAndCompress.cpp.
Member Data Documentation
m_chunkingTable
API::ITableWorkspace_sptr Mantid::WorkflowAlgorithms::LoadEventAndCompress::m_chunkingTable private
Definition at line 34 of file LoadEventAndCompress.h.
Referenced by exec(), and loadChunk().
m_filterBadPulses
double Mantid::WorkflowAlgorithms::LoadEventAndCompress::m_filterBadPulses private
Definition at line 35 of file LoadEventAndCompress.h.
Referenced by exec(), and loadChunk().
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/LoadEventAndCompress.h
Framework/WorkflowAlgorithms/src/LoadEventAndCompress.cpp