Mantid: Mantid::Crystal::PeakBackground Class Reference
Mantid::Crystal::PeakBackground Class Reference
PeakBackground : Extension of HardThresholdBackground to consider regions of the image as background if they are outside the peaks radius limits (no mater what their theshold is).
#include <PeakBackground.h>
Public Member Functions
PeakBackground * clone () const override
Virutal constructor.
void configureIterator (Mantid::API::IMDIterator *const iterator) const override
Overriden configure iterator function.
bool isBackground (Mantid::API::IMDIterator *iterator) const override
Overriden is background function.
PeakBackground (Mantid::API::IPeaksWorkspace_const_sptr peaksWS, const double &radiusEstimate, const double &thresholdSignal, const Mantid::API::MDNormalization normalisation, const Mantid::Kernel::SpecialCoordinateSystem coordinates)
Constructor.
Public Member Functions inherited from Mantid::Crystal::HardThresholdBackground
HardThresholdBackground (const double thresholdSignal, const Mantid::API::MDNormalization normalization)
Contructor.
Public Member Functions inherited from Mantid::Crystal::BackgroundStrategy
virtual ~BackgroundStrategy ()=default
Private Attributes
boost::function< Mantid::Kernel::V3D(const Mantid::Geometry::IPeak *)> m_coordFunction
Pointer to member function used for coordinate determination.
Mantid::Kernel::SpecialCoordinateSystem m_mdCoordinates
MD coordinates to use.
Mantid::API::IPeaksWorkspace_const_sptr m_peaksWS
Peak workspace containing peaks of interest.
double m_radiusEstimate
Radius estimate.
Detailed Description
PeakBackground : Extension of HardThresholdBackground to consider regions of the image as background if they are outside the peaks radius limits (no mater what their theshold is).
For pixels inside the radius, they must also be above the threshold value.
Definition at line 29 of file PeakBackground.h.
Constructor & Destructor Documentation
PeakBackground()
Mantid::Crystal::PeakBackground::PeakBackground (Mantid::API::IPeaksWorkspace_const_sptr peaksWS, const double & radiusEstimate, const double & thresholdSignal, const Mantid::API::MDNormalization normalisation, const Mantid::Kernel::SpecialCoordinateSystem coordinates)
Constructor.
Definition at line 22 of file PeakBackground.cpp.
References Mantid::Geometry::IPeak::getHKL(), Mantid::Geometry::IPeak::getQLabFrame(), Mantid::Geometry::IPeak::getQSampleFrame(), Mantid::Kernel::HKL, m_coordFunction, and m_mdCoordinates.
Member Function Documentation
clone()
PeakBackground * Mantid::Crystal::PeakBackground::clone () const override virtual
Virutal constructor.
Reimplemented from Mantid::Crystal::HardThresholdBackground.
Definition at line 40 of file PeakBackground.cpp.
configureIterator()
void Mantid::Crystal::PeakBackground::configureIterator (Mantid::API::IMDIterator *const iterator) const override virtual
Overriden configure iterator function.
Reimplemented from Mantid::Crystal::HardThresholdBackground.
Definition at line 60 of file PeakBackground.cpp.
isBackground()
bool Mantid::Crystal::PeakBackground::isBackground (Mantid::API::IMDIterator * iterator) const override virtual
Overriden is background function.
Reimplemented from Mantid::Crystal::HardThresholdBackground.
Definition at line 42 of file PeakBackground.cpp.
References Mantid::Kernel::V3D::distance(), Mantid::API::IMDIterator::getCenter(), Mantid::Crystal::HardThresholdBackground::isBackground(), m_coordFunction, m_peaksWS, and m_radiusEstimate.
Member Data Documentation
m_coordFunction
boost::function<Mantid::Kernel::V3D(const Mantid::Geometry::IPeak *)> Mantid::Crystal::PeakBackground::m_coordFunction private
Pointer to member function used for coordinate determination.
Definition at line 38 of file PeakBackground.h.
Referenced by isBackground(), and PeakBackground().
m_mdCoordinates
Mantid::Kernel::SpecialCoordinateSystem Mantid::Crystal::PeakBackground::m_mdCoordinates private
MD coordinates to use.
Definition at line 36 of file PeakBackground.h.
Referenced by PeakBackground().
m_peaksWS
Mantid::API::IPeaksWorkspace_const_sptr Mantid::Crystal::PeakBackground::m_peaksWS private
Peak workspace containing peaks of interest.
Definition at line 32 of file PeakBackground.h.
Referenced by isBackground().
m_radiusEstimate
double Mantid::Crystal::PeakBackground::m_radiusEstimate private
Radius estimate.
Definition at line 34 of file PeakBackground.h.
Referenced by isBackground().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/PeakBackground.h
Framework/Crystal/src/PeakBackground.cpp