Mantid: Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy Class Reference
Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy Class Reference abstract
#include <FindSXPeaksHelper.h>
Public Member Functions
virtual std::vector< SXPeak > reduce (const std::vector< SXPeak > &peaks, Mantid::Kernel::ProgressBase &progress) const =0
ReducePeakListStrategy (const CompareStrategy *compareStrategy)
void setMaxNSpectraPerPeak (int maxSpectrasForPeak)
void setMinNSpectraPerPeak (int minSpectrasForPeak)
virtual ~ReducePeakListStrategy ()=default
Protected Attributes
const CompareStrategy * m_compareStrategy
int m_maxNSpectraPerPeak = EMPTY_INT()
int m_minNSpectraPerPeak = EMPTY_INT()
Detailed Description
Definition at line 264 of file FindSXPeaksHelper.h.
Constructor & Destructor Documentation
ReducePeakListStrategy()
Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::ReducePeakListStrategy (const CompareStrategy * compareStrategy)
Definition at line 627 of file FindSXPeaksHelper.cpp.
~ReducePeakListStrategy()
virtual Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::~ReducePeakListStrategy () virtual default
Member Function Documentation
reduce()
virtual std::vector< SXPeak > Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::reduce (const std::vector< SXPeak > & peaks, Mantid::Kernel::ProgressBase & progress) const pure virtual
Implemented in Mantid::Crystal::FindSXPeaksHelper::SimpleReduceStrategy, and Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy.
setMaxNSpectraPerPeak()
void Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::setMaxNSpectraPerPeak (int maxSpectrasForPeak)
Definition at line 634 of file FindSXPeaksHelper.cpp.
References m_maxNSpectraPerPeak.
setMinNSpectraPerPeak()
void Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::setMinNSpectraPerPeak (int minSpectrasForPeak)
Definition at line 630 of file FindSXPeaksHelper.cpp.
References m_minNSpectraPerPeak.
Member Data Documentation
m_compareStrategy
const CompareStrategy* Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_compareStrategy protected
Definition at line 275 of file FindSXPeaksHelper.h.
Referenced by Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getPeakGroups().
m_maxNSpectraPerPeak
int Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_maxNSpectraPerPeak = EMPTY_INT() protected
Definition at line 277 of file FindSXPeaksHelper.h.
Referenced by Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getFinalPeaks(), Mantid::Crystal::FindSXPeaksHelper::SimpleReduceStrategy::reducePeaksFromNumberOfSpectras(), and setMaxNSpectraPerPeak().
m_minNSpectraPerPeak
int Mantid::Crystal::FindSXPeaksHelper::ReducePeakListStrategy::m_minNSpectraPerPeak = EMPTY_INT() protected
Definition at line 276 of file FindSXPeaksHelper.h.
Referenced by Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getFinalPeaks(), Mantid::Crystal::FindSXPeaksHelper::SimpleReduceStrategy::reducePeaksFromNumberOfSpectras(), and setMinNSpectraPerPeak().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
Framework/Crystal/src/FindSXPeaksHelper.cpp