Mantid: Mantid::DataHandling::DataBlock Class Reference
Mantid::DataHandling::DataBlock Class Reference
DataBlock: The DataBlock class holds information about a contiguous block of spectrum numbers.
#include <DataBlock.h>
Public Member Functions
DataBlock ()
DataBlock (const Mantid::NeXus::NXInt &data)
DataBlock (int numberOfperiods, size_t numberOfSpectra, size_t numberOfChannels)
virtual std::unique_ptr< DataBlockGenerator > getGenerator () const
virtual specnum_t getMaxSpectrumID () const
virtual specnum_t getMinSpectrumID () const
virtual size_t getNumberOfChannels () const
virtual int getNumberOfPeriods () const
virtual size_t getNumberOfSpectra () const
bool operator== (const DataBlock &other) const
virtual void setMaxSpectrumID (specnum_t minSpecID)
virtual void setMinSpectrumID (specnum_t minSpecID)
virtual ~DataBlock ()=default
Protected Attributes
specnum_t m_maxSpectraID
specnum_t m_minSpectraID
size_t m_numberOfChannels
int m_numberOfPeriods
size_t m_numberOfSpectra
Detailed Description
DataBlock: The DataBlock class holds information about a contiguous block of spectrum numbers.
It contains information about the min and max number of that range as well as the number of channels and periods that are associated with the spectra in the nexus file.
Definition at line 26 of file DataBlock.h.
Constructor & Destructor Documentation
DataBlock() [1/3]
Mantid::DataHandling::DataBlock::DataBlock ()
Definition at line 17 of file DataBlock.cpp.
DataBlock() [2/3]
Mantid::DataHandling::DataBlock::DataBlock (const Mantid::NeXus::NXInt & data)
Definition at line 21 of file DataBlock.cpp.
DataBlock() [3/3]
Mantid::DataHandling::DataBlock::DataBlock (int numberOfperiods, size_t numberOfSpectra, size_t numberOfChannels)
Definition at line 25 of file DataBlock.cpp.
~DataBlock()
virtual Mantid::DataHandling::DataBlock::~DataBlock () virtual default
References std::operator==().
Member Function Documentation
getGenerator()
std::unique_ptr< DataBlockGenerator > Mantid::DataHandling::DataBlock::getGenerator () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 43 of file DataBlock.cpp.
References m_maxSpectraID, and m_minSpectraID.
getMaxSpectrumID()
specnum_t Mantid::DataHandling::DataBlock::getMaxSpectrumID () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 33 of file DataBlock.cpp.
References m_maxSpectraID.
Referenced by Mantid::DataHandling::DataBlockComposite::truncate().
getMinSpectrumID()
specnum_t Mantid::DataHandling::DataBlock::getMinSpectrumID () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 29 of file DataBlock.cpp.
References m_minSpectraID.
getNumberOfChannels()
size_t Mantid::DataHandling::DataBlock::getNumberOfChannels () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 41 of file DataBlock.cpp.
References m_numberOfChannels.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock().
getNumberOfPeriods()
int Mantid::DataHandling::DataBlock::getNumberOfPeriods () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 39 of file DataBlock.cpp.
References m_numberOfPeriods.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock().
getNumberOfSpectra()
size_t Mantid::DataHandling::DataBlock::getNumberOfSpectra () const virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 37 of file DataBlock.cpp.
References m_numberOfSpectra.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock().
operator==()
bool Mantid::DataHandling::DataBlock::operator== (const DataBlock & other) const
Definition at line 48 of file DataBlock.cpp.
References m_maxSpectraID, m_minSpectraID, m_numberOfChannels, m_numberOfPeriods, and m_numberOfSpectra.
setMaxSpectrumID()
void Mantid::DataHandling::DataBlock::setMaxSpectrumID (specnum_t minSpecID) virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 35 of file DataBlock.cpp.
References m_maxSpectraID.
Referenced by Mantid::DataHandling::populateDataBlockCompositeWithContainer(), Mantid::DataHandling::DataBlockComposite::removeSpectra(), and Mantid::DataHandling::DataBlockComposite::truncate().
setMinSpectrumID()
void Mantid::DataHandling::DataBlock::setMinSpectrumID (specnum_t minSpecID) virtual
Reimplemented in Mantid::DataHandling::DataBlockComposite.
Definition at line 31 of file DataBlock.cpp.
References m_minSpectraID.
Referenced by Mantid::DataHandling::populateDataBlockCompositeWithContainer(), Mantid::DataHandling::DataBlockComposite::removeSpectra(), and Mantid::DataHandling::DataBlockComposite::truncate().
Member Data Documentation
m_maxSpectraID
specnum_t Mantid::DataHandling::DataBlock::m_maxSpectraID protected
Definition at line 58 of file DataBlock.h.
Referenced by getGenerator(), getMaxSpectrumID(), operator==(), and setMaxSpectrumID().
m_minSpectraID
specnum_t Mantid::DataHandling::DataBlock::m_minSpectraID protected
Definition at line 56 of file DataBlock.h.
Referenced by getGenerator(), getMinSpectrumID(), operator==(), and setMinSpectrumID().
m_numberOfChannels
size_t Mantid::DataHandling::DataBlock::m_numberOfChannels protected
Definition at line 53 of file DataBlock.h.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock(), getNumberOfChannels(), and operator==().
m_numberOfPeriods
int Mantid::DataHandling::DataBlock::m_numberOfPeriods protected
Definition at line 49 of file DataBlock.h.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock(), getNumberOfPeriods(), and operator==().
m_numberOfSpectra
size_t Mantid::DataHandling::DataBlock::m_numberOfSpectra protected
Definition at line 51 of file DataBlock.h.
Referenced by Mantid::DataHandling::DataBlockComposite::addDataBlock(), getNumberOfSpectra(), and operator==().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/DataBlock.h
Framework/DataHandling/src/DataBlock.cpp