Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames Namespace Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames Namespace Reference
Functions
const std::string ALLOW_LOGS ("LogAllowList")
const std::string AZIMUTHALS ("Azimuthal")
const std::string BANK_NUMBER ("BankNumber")
const std::string BIN_UNITS ("BinningUnits")
const std::string BINMODE ("BinningMode")
const std::string BLOCK_LOGS ("LogBlockList")
const std::string CAL_FILE ("CalFileName")
const std::string CORRECTION_TO_SAMPLE ("CorrectionToSample")
const std::string EVENTS_PER_THREAD ("EventsPerThread")
const std::string FILENAME ("Filename")
const std::string FILTER_BAD_PULSES ("FilterBadPulses")
const std::string FILTER_BAD_PULSES_LOWER_CUTOFF ("BadPulsesLowerCutoff")
const std::string FILTER_TIMESTART ("FilterByTimeStart")
const std::string FILTER_TIMESTOP ("FilterByTimeStop")
const std::string FULL_TIME ("UseFullTime")
const std::string GROUPING_WS ("GroupingWorkspace")
const std::string L1 ("L1")
const std::string L2 ("L2")
const std::string OUTPUT_WKSP ("OutputWorkspace")
const std::string POLARS ("Polar")
const std::string PROCESS_BANK_SPLIT_TASK ("ProcessBankSplitTask")
const std::string READ_SIZE_FROM_DISK ("ReadSizeFromDisk")
const std::string SPLITTER_RELATIVE ("RelativeTime")
const std::string SPLITTER_WS ("SplitterWorkspace")
const std::string X_DELTA ("XDelta")
const std::string X_MAX ("XMax")
const std::string X_MIN ("XMin")
Function Documentation
ALLOW_LOGS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::ALLOW_LOGS ("LogAllowList") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
AZIMUTHALS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::AZIMUTHALS ("Azimuthal") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
BANK_NUMBER()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::BANK_NUMBER ("BankNumber") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
BIN_UNITS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::BIN_UNITS ("BinningUnits") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
BINMODE()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::BINMODE ("BinningMode") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
BLOCK_LOGS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::BLOCK_LOGS ("LogBlockList") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
CAL_FILE()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::CAL_FILE ("CalFileName") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
CORRECTION_TO_SAMPLE()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::CORRECTION_TO_SAMPLE ("CorrectionToSample") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
EVENTS_PER_THREAD()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::EVENTS_PER_THREAD ("EventsPerThread") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
FILENAME()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FILENAME ("Filename") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
FILTER_BAD_PULSES()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FILTER_BAD_PULSES ("FilterBadPulses") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
FILTER_BAD_PULSES_LOWER_CUTOFF()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FILTER_BAD_PULSES_LOWER_CUTOFF ("BadPulsesLowerCutoff") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
FILTER_TIMESTART()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FILTER_TIMESTART ("FilterByTimeStart") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
FILTER_TIMESTOP()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FILTER_TIMESTOP ("FilterByTimeStop") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
FULL_TIME()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::FULL_TIME ("UseFullTime") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
GROUPING_WS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::GROUPING_WS ("GroupingWorkspace") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
L1()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::L1 ("L1") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
L2()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::L2 ("L2") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
OUTPUT_WKSP()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::OUTPUT_WKSP ("OutputWorkspace") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
POLARS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::POLARS ("Polar") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
PROCESS_BANK_SPLIT_TASK()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::PROCESS_BANK_SPLIT_TASK ("ProcessBankSplitTask") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
READ_SIZE_FROM_DISK()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::READ_SIZE_FROM_DISK ("ReadSizeFromDisk") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
SPLITTER_RELATIVE()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::SPLITTER_RELATIVE ("RelativeTime") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
SPLITTER_WS()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::SPLITTER_WS ("SplitterWorkspace") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init().
X_DELTA()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::X_DELTA ("XDelta") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
X_MAX()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::X_MAX ("XMax") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().
X_MIN()
const std::string Mantid::DataHandling::AlignAndFocusPowderSlim::PropertyNames::X_MIN ("XMin") private
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), and Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::validateInputs().