Mantid: MantidQt::MantidWidgets::MuonFitDataSelector Class Reference
MantidQt::MantidWidgets::MuonFitDataSelector Class Reference
MuonFitDataSelector : Selects runs, groups, periods for fit.
#include <MuonFitDataSelector.h>
Public Slots
void checkForMultiGroupPeriodSelection ()
Called when group/period box selection changes.
void fitTypeChanged (bool state)
Called when fit type changed.
void setEndTime (double end) override
Set end time for fit.
void setEndTimeQuietly (double end) override
Set end time without sending a signal.
void setStartTime (double start) override
Set start time for fit.
void setStartTimeQuietly (double start) override
Set start time without sending a signal.
void setWorkspaceDetails (const QString &runNumbers, const QString &instName, const std::optional< QString > &filePath) override
Set starting run number, instrument and (optionally) file path.
void updateNormalizationFromDropDown (int)
void userChangedRuns ()
Called when user changes runs.
Signals
void dataPropertiesChanged ()
Edited the start or end fields.
void datasetIndexChanged (int index)
Dataset index changed.
void nameChanged (QString name)
void simulLabelChanged ()
Simultaneous fit label changed.
void workspaceChanged ()
Changed the workspace.
Signals inherited from MantidQt::API::MantidWidget
void runAsPythonScript (const QString &code, bool)
Public Member Functions
bool askUserWhetherToOverwrite () override
Ask user whether to overwrite label or not.
QStringList getChosenGroups () const override
Get names of chosen groups.
int getDatasetIndex () const override
Get index of selected dataset.
QString getDatasetName () const override
Get name of selected dataset.
double getEndTime () const override
Get selected end time.
QStringList getFilenames () const override
Get selected filenames.
IMuonFitDataSelector::FitType getFitType () const override
Get type of fit.
QString getInstrumentName () const override
Get instrument name.
QStringList getPeriodSelections () const override
Get selected periods.
QString getRuns () const override
Get selected run numbers.
QString getSimultaneousFitLabel () const override
Get label for simultaneous fit.
double getStartTime () const override
Get selected start time.
QVariant getUserInput () const override
Get user input through a common interface.
MuonFitDataSelector (QWidget *parent)
Basic constructor.
MuonFitDataSelector (QWidget *parent, int runNumber, const QString &instName)
Constructor with more options.
void setDatasetNames (const QStringList &datasetNames) override
Set names of datasets for selection.
void setGroupsSelected (const QStringList &groups)
Set chosen group/period.
void setPeriodsSelected (const QStringList &periods)
void setSimultaneousFitLabel (const QString &label) override
Set label for simultaneous fit.
void setUserInput (const QVariant &value) override
Set user input through a common interface.
Public Member Functions inherited from MantidQt::MantidWidgets::IMuonFitDataSelector
virtual void setEndTime (double end)=0
virtual void setEndTimeQuietly (double end)=0
virtual void setStartTime (double start)=0
virtual void setStartTimeQuietly (double start)=0
virtual void setWorkspaceDetails (const QString &runNumbers, const QString &instName, const std::optional< QString > &filePath)=0
virtual ~IMuonFitDataSelector ()=default
Private Slots
void setNextDataset ()
Change dataset to next one.
void setPreviousDataset ()
Change dataset to previous one.
void unsetBusyState ()
Set normal cursor and enable input.
Private Member Functions
void setBusyState ()
Set busy cursor and disable input.
void setDefaultValues ()
Set default values in some input controls.
void setFitType (IMuonFitDataSelector::FitType type)
Set type for fit.
void setUpConnections ()
Set up connections for signals/slots.
Private Attributes
QStringList m_chosenGroups
QStringList m_chosenPeriods
double m_endX
bool m_multiFit
double m_startX
Ui::MuonFitDataSelector m_ui
Member - user interface.
Additional Inherited Members
Public Types inherited from MantidQt::MantidWidgets::IMuonFitDataSelector
enum class FitType { Single , CoAdd , Simultaneous }
Protected Member Functions inherited from MantidQt::API::MantidWidget
MantidWidget (QWidget *parent=nullptr)
Default constructor.
QString runPythonCode (const QString &code, bool no_output=false)
Run python code that is passed to it and, optionally, return anything it wrote to standard output as a string.
Detailed Description
MuonFitDataSelector : Selects runs, groups, periods for fit.
Widget to select data to fit for MuonAnalysis
Implements IMuonFitDataSelector
Definition at line 25 of file MuonFitDataSelector.h.
Constructor & Destructor Documentation
MuonFitDataSelector() [1/2]
MantidQt::MantidWidgets::MuonFitDataSelector::MuonFitDataSelector (QWidget * parent) explicit
Basic constructor.
Parameters
parent :: [input] Parent dialog for the widget
Definition at line 25 of file MuonFitDataSelector.cpp.
References m_multiFit, m_ui, MantidQt::API::FileFinderWidget::None, setDefaultValues(), and setUpConnections().
MuonFitDataSelector() [2/2]
MantidQt::MantidWidgets::MuonFitDataSelector::MuonFitDataSelector (QWidget * parent, int runNumber, const QString & instName)
Constructor with more options.
Constructor for the widget.
Parameters
parent :: [input] Parent dialog for the widget
runNumber :: [input] Run number of initial workspace
instName :: [input] Name of instrument from initial workspace
Definition at line 42 of file MuonFitDataSelector.cpp.
References m_multiFit, and setWorkspaceDetails().
Member Function Documentation
askUserWhetherToOverwrite()
bool MantidQt::MantidWidgets::MuonFitDataSelector::askUserWhetherToOverwrite () override virtual
Ask user whether to overwrite label or not.
Ask the user whether to overwrite the fit results with the current label, if those results already exist.
Raises a messagebox with a yes/no choice.
Returns
:: True if user chose to overwrite, false if not.
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 439 of file MuonFitDataSelector.cpp.
References getSimultaneousFitLabel().
checkForMultiGroupPeriodSelection
void MantidQt::MantidWidgets::MuonFitDataSelector::checkForMultiGroupPeriodSelection () slot
Called when group/period box selection changes.
Enable the "Label" textbox if multiple groups or periods are selected.
Called when groups/periods selection changes.
Definition at line 357 of file MuonFitDataSelector.cpp.
References getFitType(), m_chosenGroups, m_chosenPeriods, m_ui, and MantidQt::MantidWidgets::IMuonFitDataSelector::Simultaneous.
Referenced by setFitType(), and setUpConnections().
dataPropertiesChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::dataPropertiesChanged () signal
Edited the start or end fields.
Referenced by setEndTime(), and setStartTime().
datasetIndexChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::datasetIndexChanged (int index) signal
Dataset index changed.
Referenced by setUpConnections().
fitTypeChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::fitTypeChanged (bool state) slot
Called when fit type changed.
Emit a signal.
Parameters
state :: [input] Unused.
Definition at line 77 of file MuonFitDataSelector.cpp.
References workspaceChanged().
Referenced by setUpConnections().
getChosenGroups()
QStringList MantidQt::MantidWidgets::MuonFitDataSelector::getChosenGroups () const override virtual
Get names of chosen groups.
Returns a list of the selected groups (checked boxes)
Returns
:: list of selected groups
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 204 of file MuonFitDataSelector.cpp.
References m_chosenGroups.
Referenced by getUserInput().
getDatasetIndex()
int MantidQt::MantidWidgets::MuonFitDataSelector::getDatasetIndex () const override virtual
Get index of selected dataset.
Return index of currently selected dataset.
Returns
:: index of dataset selected in combobox
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 366 of file MuonFitDataSelector.cpp.
References m_ui.
getDatasetName()
QString MantidQt::MantidWidgets::MuonFitDataSelector::getDatasetName () const override virtual
Get name of selected dataset.
Return name of currently selected dataset.
Returns
:: name of dataset selected in combobox
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 372 of file MuonFitDataSelector.cpp.
References m_ui.
getEndTime()
double MantidQt::MantidWidgets::MuonFitDataSelector::getEndTime () const override virtual
Get selected end time.
Get the user's supplied end time (default 10)
Returns
:: start time input by user in microseconds
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 127 of file MuonFitDataSelector.cpp.
References m_endX.
Referenced by getUserInput().
getFilenames()
QStringList MantidQt::MantidWidgets::MuonFitDataSelector::getFilenames () const override virtual
Get selected filenames.
Get the filenames of the supplied run numbers.
Returns
:: list of run filenames
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 148 of file MuonFitDataSelector.cpp.
References m_ui.
getFitType()
IMuonFitDataSelector::FitType MantidQt::MantidWidgets::MuonFitDataSelector::getFitType () const override virtual
Get type of fit.
Returns the selected fit type.
If only one run is selected, this is a single fit UNLESS multiple groups/periods are selected, in which case it's simultaneous.
If multiple runs are selected, the user has the option of co-adding them or doing a simultaneous fit, chosen via the radio buttons.
Returns
:: fit type from enum
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 259 of file MuonFitDataSelector.cpp.
References MantidQt::MantidWidgets::IMuonFitDataSelector::CoAdd, m_chosenGroups, m_chosenPeriods, m_multiFit, m_ui, MantidQt::MantidWidgets::IMuonFitDataSelector::Simultaneous, and MantidQt::MantidWidgets::IMuonFitDataSelector::Single.
Referenced by checkForMultiGroupPeriodSelection().
getInstrumentName()
QString MantidQt::MantidWidgets::MuonFitDataSelector::getInstrumentName () const override virtual
Get instrument name.
Return the instrument name currently set as the override for the data selector.
Returns
:: instrument name
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 296 of file MuonFitDataSelector.cpp.
References m_ui.
getPeriodSelections()
QStringList MantidQt::MantidWidgets::MuonFitDataSelector::getPeriodSelections () const override virtual
Get selected periods.
Returns a list of periods and combinations chosen in UI.
Returns
:: list of periods e.g. "1", "3", "1+2-3+4", or "" if single-period
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 198 of file MuonFitDataSelector.cpp.
References m_chosenPeriods.
Referenced by getUserInput().
getRuns()
QString MantidQt::MantidWidgets::MuonFitDataSelector::getRuns () const override virtual
Get selected run numbers.
Return the runs entered by the user.
Returns
:: run number string if valid, else empty string
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 302 of file MuonFitDataSelector.cpp.
References m_ui.
Referenced by getUserInput(), and userChangedRuns().
getSimultaneousFitLabel()
QString MantidQt::MantidWidgets::MuonFitDataSelector::getSimultaneousFitLabel () const override virtual
Get label for simultaneous fit.
Get text entered as the simultaneous fit label.
Returns
:: text entered in the textbox
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 332 of file MuonFitDataSelector.cpp.
References m_ui.
Referenced by askUserWhetherToOverwrite().
getStartTime()
double MantidQt::MantidWidgets::MuonFitDataSelector::getStartTime () const override virtual
Get selected start time.
Get the user's supplied start time (default 0)
Returns
:: start time input by user in microseconds
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 103 of file MuonFitDataSelector.cpp.
References m_startX.
Referenced by getUserInput().
getUserInput()
QVariant MantidQt::MantidWidgets::MuonFitDataSelector::getUserInput () const override virtual
Get user input through a common interface.
Gets user input in the form of a QVariant.
This is implemented as the "standard" way of getting input from a MantidWidget. In practice it is probably easier to get the input using other methods.
The returned QVariant is a QVariantMap of (parameter, value) pairs.
Returns
:: QVariant containing a QVariantMap
Reimplemented from MantidQt::API::MantidWidget.
Definition at line 216 of file MuonFitDataSelector.cpp.
References getChosenGroups(), getEndTime(), getPeriodSelections(), getRuns(), and getStartTime().
nameChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::nameChanged (QString name) signal
Referenced by updateNormalizationFromDropDown().
setBusyState()
void MantidQt::MantidWidgets::MuonFitDataSelector::setBusyState () private
Set busy cursor and disable input.
Sets busy cursor and disables input while file search in progress.
Connects up slot to reset busy state when search done.
Definition at line 323 of file MuonFitDataSelector.cpp.
References m_ui, and unsetBusyState().
Referenced by setWorkspaceDetails().
setDatasetNames()
void MantidQt::MantidWidgets::MuonFitDataSelector::setDatasetNames (const QStringList & datasetNames) override virtual
Set names of datasets for selection.
Replaces list of dataset names with the supplied list.
Parameters
datasetNames :: [input] List of names to use
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 378 of file MuonFitDataSelector.cpp.
References count, and m_ui.
setDefaultValues()
void MantidQt::MantidWidgets::MuonFitDataSelector::setDefaultValues () private
Set default values in some input controls.
Set default values in some input controls Defaults copy those previously used in muon fit property browser.
Definition at line 188 of file MuonFitDataSelector.cpp.
References m_ui, setEndTime(), setStartTime(), and simulLabelChanged().
Referenced by MuonFitDataSelector().
setEndTime
void MantidQt::MantidWidgets::MuonFitDataSelector::setEndTime (double end) override slot
Set end time for fit.
Set the end time in the UI, and send signal.
Parameters
end :: [input] End time in microseconds
Definition at line 139 of file MuonFitDataSelector.cpp.
References dataPropertiesChanged(), and setEndTimeQuietly().
Referenced by setDefaultValues(), and setUserInput().
setEndTimeQuietly
void MantidQt::MantidWidgets::MuonFitDataSelector::setEndTimeQuietly (double end) override slot
Set end time without sending a signal.
Set the end time in the UI WITHOUT sending signal.
Parameters
end :: [input] End time in microseconds
Definition at line 133 of file MuonFitDataSelector.cpp.
References m_endX.
Referenced by setEndTime().
setFitType()
void MantidQt::MantidWidgets::MuonFitDataSelector::setFitType (IMuonFitDataSelector::FitType type) private
Set type for fit.
Sets the fit type.
If single, disables radio buttons. Otherwise, enables buttons and selects the correct one.
Parameters
type :: [input] Fit type to set (from enum)
Definition at line 280 of file MuonFitDataSelector.cpp.
References checkForMultiGroupPeriodSelection(), MantidQt::MantidWidgets::IMuonFitDataSelector::CoAdd, m_multiFit, m_ui, MantidQt::MantidWidgets::IMuonFitDataSelector::Simultaneous, and MantidQt::MantidWidgets::IMuonFitDataSelector::Single.
Referenced by setWorkspaceDetails(), and userChangedRuns().
setGroupsSelected()
void MantidQt::MantidWidgets::MuonFitDataSelector::setGroupsSelected (const QStringList & groups) inline
Set chosen group/period.
Definition at line 49 of file MuonFitDataSelector.h.
setNextDataset
void MantidQt::MantidWidgets::MuonFitDataSelector::setNextDataset () private slot
Change dataset to next one.
Called when "next dataset" is clicked.
Changes combobox to next dataset, which will raise an event. If there is no next dataset, does nothing.
Definition at line 426 of file MuonFitDataSelector.cpp.
References index, and m_ui.
Referenced by setUpConnections().
setPeriodsSelected()
void MantidQt::MantidWidgets::MuonFitDataSelector::setPeriodsSelected (const QStringList & periods) inline
Definition at line 50 of file MuonFitDataSelector.h.
setPreviousDataset
void MantidQt::MantidWidgets::MuonFitDataSelector::setPreviousDataset () private slot
Change dataset to previous one.
Called when "previous dataset" is clicked.
Changes combobox to previous dataset, which will raise an event. If there is no previous dataset, does nothing.
Definition at line 414 of file MuonFitDataSelector.cpp.
References index, and m_ui.
Referenced by setUpConnections().
setSimultaneousFitLabel()
void MantidQt::MantidWidgets::MuonFitDataSelector::setSimultaneousFitLabel (const QString & label) override virtual
Set label for simultaneous fit.
Set text of simultaneous fit label.
Parameters
label :: [input] Text to set as label
Implements MantidQt::MantidWidgets::IMuonFitDataSelector.
Definition at line 338 of file MuonFitDataSelector.cpp.
References index, and m_ui.
setStartTime
void MantidQt::MantidWidgets::MuonFitDataSelector::setStartTime (double start) override slot
Set start time for fit.
Set the start time in the UI, and send signal.
Parameters
start :: [input] Start time in microseconds
Definition at line 118 of file MuonFitDataSelector.cpp.
References dataPropertiesChanged(), and setStartTimeQuietly().
Referenced by setDefaultValues(), and setUserInput().
setStartTimeQuietly
void MantidQt::MantidWidgets::MuonFitDataSelector::setStartTimeQuietly (double start) override slot
Set start time without sending a signal.
Set the start time in the UI WITHOUT sending signal.
Parameters
start :: [input] Start time in microseconds
Definition at line 112 of file MuonFitDataSelector.cpp.
References m_startX.
Referenced by setStartTime().
setUpConnections()
void MantidQt::MantidWidgets::MuonFitDataSelector::setUpConnections () private
Set up connections for signals/slots.
Connect signals from UI elements to re-emit a signal that "user has changed something".
Definition at line 62 of file MuonFitDataSelector.cpp.
References checkForMultiGroupPeriodSelection(), datasetIndexChanged(), fitTypeChanged(), m_ui, setNextDataset(), setPreviousDataset(), simulLabelChanged(), updateNormalizationFromDropDown(), userChangedRuns(), and workspaceChanged().
Referenced by MuonFitDataSelector().
setUserInput()
void MantidQt::MantidWidgets::MuonFitDataSelector::setUserInput (const QVariant & value) override virtual
Set user input through a common interface.
Sets user input in the form of a QVariant.
This is implemented as the "standard" way of setting input in a MantidWidget. In practice it is probably easier to set the input using other methods.
This function doesn't support setting runs, groups or periods.
The input QVariant is a QVariantMap of (parameter, value) pairs.
Parameters
value :: [input] QVariant containing a QVariantMap
Reimplemented from MantidQt::API::MantidWidget.
Definition at line 239 of file MuonFitDataSelector.cpp.
References setEndTime(), setStartTime(), and value.
setWorkspaceDetails
void MantidQt::MantidWidgets::MuonFitDataSelector::setWorkspaceDetails (const QString & runNumbers, const QString & instName, const std::optional< QString > & filePath) override slot
Set starting run number, instrument and (optionally) file path.
Set up run finder with initial run number and instrument.
Parameters
runNumbers :: [input] Run numbers from loaded workspace
instName :: [input] Instrument name from loaded workspace
filePath :: [input] Optional path to the data file - this is important in the case of "load current run" when the file may have a special name like MUSRauto_E.tmp
Definition at line 158 of file MuonFitDataSelector.cpp.
References MantidQt::MantidWidgets::IMuonFitDataSelector::CoAdd, m_ui, setBusyState(), setFitType(), and MantidQt::MantidWidgets::IMuonFitDataSelector::Single.
Referenced by MuonFitDataSelector().
simulLabelChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::simulLabelChanged () signal
Simultaneous fit label changed.
Referenced by setDefaultValues(), and setUpConnections().
unsetBusyState
void MantidQt::MantidWidgets::MuonFitDataSelector::unsetBusyState () private slot
Set normal cursor and enable input.
Slot: called when file finding finished.
Resets the cursor for this widget back to the normal, non-busy state.
Definition at line 314 of file MuonFitDataSelector.cpp.
References m_ui, and unsetBusyState().
Referenced by setBusyState(), and unsetBusyState().
updateNormalizationFromDropDown
void MantidQt::MantidWidgets::MuonFitDataSelector::updateNormalizationFromDropDown (int j) slot
Definition at line 400 of file MuonFitDataSelector.cpp.
References m_ui, name, and nameChanged().
Referenced by setUpConnections().
userChangedRuns
void MantidQt::MantidWidgets::MuonFitDataSelector::userChangedRuns () slot
Called when user changes runs.
Slot: called when user edits runs box.
Check for single run and enable/disable radio buttons, and emit signal that runs have changed.
Definition at line 87 of file MuonFitDataSelector.cpp.
References getRuns(), m_multiFit, setFitType(), MantidQt::MantidWidgets::IMuonFitDataSelector::Single, and workspaceChanged().
Referenced by setUpConnections().
workspaceChanged
void MantidQt::MantidWidgets::MuonFitDataSelector::workspaceChanged () signal
Changed the workspace.
Referenced by fitTypeChanged(), setUpConnections(), and userChangedRuns().
Member Data Documentation
m_chosenGroups
QStringList MantidQt::MantidWidgets::MuonFitDataSelector::m_chosenGroups private
Definition at line 115 of file MuonFitDataSelector.h.
Referenced by checkForMultiGroupPeriodSelection(), getChosenGroups(), and getFitType().
m_chosenPeriods
QStringList MantidQt::MantidWidgets::MuonFitDataSelector::m_chosenPeriods private
Definition at line 116 of file MuonFitDataSelector.h.
Referenced by checkForMultiGroupPeriodSelection(), getFitType(), and getPeriodSelections().
m_endX
double MantidQt::MantidWidgets::MuonFitDataSelector::m_endX private
Definition at line 114 of file MuonFitDataSelector.h.
Referenced by getEndTime(), and setEndTimeQuietly().
m_multiFit
bool MantidQt::MantidWidgets::MuonFitDataSelector::m_multiFit private
Definition at line 117 of file MuonFitDataSelector.h.
Referenced by getFitType(), MuonFitDataSelector(), MuonFitDataSelector(), setFitType(), and userChangedRuns().
m_startX
double MantidQt::MantidWidgets::MuonFitDataSelector::m_startX private
Definition at line 113 of file MuonFitDataSelector.h.
Referenced by getStartTime(), and setStartTimeQuietly().
m_ui
Ui::MuonFitDataSelector MantidQt::MantidWidgets::MuonFitDataSelector::m_ui private
Member - user interface.
Definition at line 112 of file MuonFitDataSelector.h.
Referenced by checkForMultiGroupPeriodSelection(), getDatasetIndex(), getDatasetName(), getFilenames(), getFitType(), getInstrumentName(), getRuns(), getSimultaneousFitLabel(), MuonFitDataSelector(), setBusyState(), setDatasetNames(), setDefaultValues(), setFitType(), setNextDataset(), setPreviousDataset(), setSimultaneousFitLabel(), setUpConnections(), setWorkspaceDetails(), unsetBusyState(), and updateNormalizationFromDropDown().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MuonFitDataSelector.h
qt/widgets/common/src/MuonFitDataSelector.cpp