Mantid: Mantid::DTriple< F, S, T > Class Template Reference
Mantid::DTriple< F, S, T > Class Template Reference
Triple of three different things.
#include <Triple.h>
Public Member Functions
DTriple ()
Standard Constructor.
DTriple (const DTriple< F, S, T > &)
Standard Copy Constructor.
DTriple (const F &, const S &, const T &)
Constructor from a 3 value input.
bool operator!= (const DTriple< F, S, T > &) const
Operator!= any component is not equal.
bool operator< (const DTriple< F, S, T > &) const
Operator< takes first to last precidence.
DTriple< F, S, T > & operator= (const DTriple< F, S, T > &)
Assignment from a 3 value input.
bool operator== (const DTriple< F, S, T > &) const
Operator== all components must be equal.
bool operator> (const DTriple< F, S, T > &) const
Operator> takes first to last precidence.
~DTriple ()
Standard Destructor.
Public Attributes
F first
First item.
S second
Second item.
T third
Third item.
Detailed Description
template<typename F, typename S, typename T>
class Mantid::DTriple< F, S, T >
Triple of three different things.
Author
S. Ansell
Date
April 2005
Version
1.0
Class maintians a different type first/second/third triple All are of a different type
Definition at line 53 of file Triple.h.
Constructor & Destructor Documentation
DTriple() [1/3]
template<typename F , typename S , typename T > Mantid::DTriple< F, S, T >::DTriple
Standard Constructor.
Definition at line 164 of file Triple.cpp.
DTriple() [2/3]
template<typename F , typename S , typename T > Mantid::DTriple< F, S, T >::DTriple (const DTriple< F, S, T > & A)
Standard Copy Constructor.
Parameters
A :: DTriple Item to copy
Definition at line 172 of file Triple.cpp.
DTriple() [3/3]
template<typename F , typename S , typename T > Mantid::DTriple< F, S, T >::DTriple (const F & A, const S & B, const T & C)
Constructor from a 3 value input.
Parameters
A :: first item
B :: second item
C :: third item
Definition at line 181 of file Triple.cpp.
~DTriple()
template<typename F , typename S , typename T > Mantid::DTriple< F, S, T >::~DTriple () default
Standard Destructor.
References std::operator!=(), std::operator<(), std::operator==(), and std::operator>().
Member Function Documentation
operator!=()
template<typename F , typename S , typename T > bool Mantid::DTriple< F, S, T >::operator!= (const DTriple< F, S, T > & A) const
Operator!= any component is not equal.
Definition at line 226 of file Triple.cpp.
operator<()
template<typename F , typename S , typename T > bool Mantid::DTriple< F, S, T >::operator< (const DTriple< F, S, T > & A) const
Operator< takes first to last precidence.
Parameters
A :: Triple to compare
Returns
this < A
Definition at line 235 of file Triple.cpp.
operator=()
template<typename F , typename S , typename T > DTriple< F, S, T > & Mantid::DTriple< F, S, T >::operator= (const DTriple< F, S, T > & A)
Assignment from a 3 value input.
Parameters
A :: DTriple to copy from
Returns
*this
Definition at line 192 of file Triple.cpp.
References Mantid::DTriple< F, S, T >::first, Mantid::DTriple< F, S, T >::second, and Mantid::DTriple< F, S, T >::third.
operator==()
template<typename F , typename S , typename T > bool Mantid::DTriple< F, S, T >::operator== (const DTriple< F, S, T > & A) const
Operator== all components must be equal.
Parameters
A :: Object to compare
Returns
A==*this
Definition at line 215 of file Triple.cpp.
operator>()
template<typename F , typename S , typename T > bool Mantid::DTriple< F, S, T >::operator> (const DTriple< F, S, T > & A) const
Operator> takes first to last precidence.
Parameters
A :: Triple to compare
Returns
this < A
Definition at line 256 of file Triple.cpp.
Member Data Documentation
first
template<typename F , typename S , typename T > F Mantid::DTriple< F, S, T >::first
First item.
Definition at line 55 of file Triple.h.
Referenced by Mantid::Geometry::Rule::makeCNFcopy(), Mantid::DTriple< F, S, T >::operator=(), and Mantid::Geometry::Rule::removeComplementary().
second
template<typename F , typename S , typename T > S Mantid::DTriple< F, S, T >::second
Second item.
Definition at line 56 of file Triple.h.
Referenced by Mantid::Geometry::Rule::makeCNFcopy(), and Mantid::DTriple< F, S, T >::operator=().
third
template<typename F , typename S , typename T > T Mantid::DTriple< F, S, T >::third
Third item.
Definition at line 57 of file Triple.h.
Referenced by Mantid::Geometry::Rule::makeCNFcopy(), Mantid::DTriple< F, S, T >::operator=(), and Mantid::Geometry::Rule::removeComplementary().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Math/Triple.h
Framework/Geometry/src/Math/Triple.cpp