Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase Class Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase Class Reference
#include <ProcessBankTaskBase.h>
Public Member Functions
const std::string & bankName (const size_t wksp_index) const
BankCalibration getCalibration (const std::string &tof_unit, const size_t wksp_index) const
std::vector< BankCalibration > getCalibrations (const std::string &tof_unit, const size_t bank_index) const
std::stack< EventROI > getEventIndexRanges (H5::Group &event_group, const uint64_t number_events, std::unique_ptr< std::vector< uint64_t > > *event_index=nullptr) const
std::stack< std::pair< int, EventROI > > getEventIndexSplitRanges (H5::Group &event_group, const uint64_t number_events) const
void loadEvents (H5::DataSet &detID_SDS, H5::DataSet &tof_SDS, const std::vector< size_t > &offsets, const std::vector< size_t > &slabsizes, std::unique_ptr< std::vector< uint32_t > > &detId_vec, std::unique_ptr< std::vector< float > > &tof_vec) const
Load detid and tof at the same time.
ProcessBankTaskBase (std::vector< std::string > &bankEntryNames, std::shared_ptr< NexusLoader > loader, const BankCalibrationFactory &calibFactory)
Private Attributes
const std::vector< std::string > m_bankEntries
const BankCalibrationFactory & m_calibFactory
used to generate actual calibration
std::shared_ptr< const NexusLoader > m_loader
Detailed Description
Definition at line 16 of file ProcessBankTaskBase.h.
Constructor & Destructor Documentation
ProcessBankTaskBase()
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::ProcessBankTaskBase (std::vector< std::string > & bankEntryNames, std::shared_ptr< NexusLoader > loader, const BankCalibrationFactory & calibFactory)
Definition at line 18 of file ProcessBankTaskBase.cpp.
Member Function Documentation
bankName()
const std::string & Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::bankName (const size_t wksp_index) const
Definition at line 22 of file ProcessBankTaskBase.cpp.
References m_bankEntries.
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().
getCalibration()
BankCalibration Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getCalibration (const std::string & tof_unit, const size_t wksp_index) const
Definition at line 23 of file ProcessBankTaskBase.cpp.
References Mantid::DataHandling::AlignAndFocusPowderSlim::BankCalibrationFactory::getCalibration(), m_calibFactory, and Mantid::Kernel::Units::timeConversionValue().
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()().
getCalibrations()
std::vector< BankCalibration > Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getCalibrations (const std::string & tof_unit, const size_t bank_index) const
Definition at line 32 of file ProcessBankTaskBase.cpp.
References Mantid::DataHandling::AlignAndFocusPowderSlim::BankCalibrationFactory::getCalibrations(), m_calibFactory, and Mantid::Kernel::Units::timeConversionValue().
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().
getEventIndexRanges()
std::stack< EventROI > Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getEventIndexRanges (H5::Group & event_group, const uint64_t number_events, std::unique_ptr< std::vector< uint64_t > > * event_index = nullptr) const
Definition at line 53 of file ProcessBankTaskBase.cpp.
References m_loader.
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().
getEventIndexSplitRanges()
std::stack< std::pair< int, EventROI > > Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getEventIndexSplitRanges (H5::Group & event_group, const uint64_t number_events) const
Definition at line 58 of file ProcessBankTaskBase.cpp.
References m_loader.
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()().
loadEvents()
void Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::loadEvents (H5::DataSet & detID_SDS, H5::DataSet & tof_SDS, const std::vector< size_t > & offsets, const std::vector< size_t > & slabsizes, std::unique_ptr< std::vector< uint32_t > > & detId_vec, std::unique_ptr< std::vector< float > > & tof_vec) const
Load detid and tof at the same time.
Parameters
detID_SDS : HDF5 dataset for detector IDs
tof_SDS : HDF5 dataset for time-of-flights
offsets : offsets to read from each dataset
slabsizes : slab sizes to read from each dataset
detId_vec : output vector for detector IDs
tof_vec : output vector for time-of-flights
Definition at line 39 of file ProcessBankTaskBase.cpp.
References m_loader.
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), and Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()().
Member Data Documentation
m_bankEntries
const std::vector<std::string> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::m_bankEntries private
Definition at line 45 of file ProcessBankTaskBase.h.
Referenced by bankName().
m_calibFactory
const BankCalibrationFactory& Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::m_calibFactory private
used to generate actual calibration
Definition at line 48 of file ProcessBankTaskBase.h.
Referenced by getCalibration(), and getCalibrations().
m_loader
std::shared_ptr<const NexusLoader> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::m_loader private
Definition at line 46 of file ProcessBankTaskBase.h.
Referenced by getEventIndexRanges(), getEventIndexSplitRanges(), and loadEvents().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim/ProcessBankTaskBase.h
Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankTaskBase.cpp