Mantid: Mantid::MDAlgorithms::CutMD Class Reference
Mantid::MDAlgorithms::CutMD Class Reference
CutMD : Slices multidimensional workspaces.
#include <CutMD.h>
Public Member Functions
const std::string category () const override
void exec () override
void init () override
const std::string name () const override
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
int version () const override
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Static Public Attributes
static const std::string AutoMethod = "Auto"
static const std::string InvAngstromMethod = "Q in A^-1"
static const std::string InvAngstromSymbol = "a"
static const std::string RLUMethod = "RLU"
static const std::string RLUSymbol = "r"
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
CutMD : Slices multidimensional workspaces.
Date
2015-03-20
Definition at line 24 of file CutMD.h.
Member Function Documentation
category()
const std::string Mantid::MDAlgorithms::CutMD::category () const inline override
Definition at line 33 of file CutMD.h.
exec()
void Mantid::MDAlgorithms::CutMD::exec () override
Definition at line 272 of file CutMD.cpp.
References AutoMethod, Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::MDAlgorithms::findOriginalQUnits(), Mantid::API::g_log, Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), Mantid::API::Projection::getUnit(), Mantid::Kernel::Matrix< T >::getVector(), Mantid::Kernel::Logger::information(), InvAngstromSymbol, Mantid::API::RLU, RLUMethod, RLUSymbol, Mantid::Kernel::Matrix< T >::setRow(), std::to_string(), Mantid::API::Projection::U(), Mantid::API::Projection::V(), value, vec, Mantid::API::Projection::W(), and Mantid::Kernel::Logger::warning().
init()
void Mantid::MDAlgorithms::CutMD::init () override
Definition at line 228 of file CutMD.cpp.
References AutoMethod, Mantid::Kernel::Direction::Input, InvAngstromMethod, Mantid::API::PropertyMode::Optional, Mantid::Kernel::Direction::Output, and RLUMethod.
name()
const std::string Mantid::MDAlgorithms::CutMD::name () const inline override
Definition at line 26 of file CutMD.h.
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::CutMD::seeAlso () const inline override
Definition at line 28 of file CutMD.h.
summary()
const std::string Mantid::MDAlgorithms::CutMD::summary () const inline override
Definition at line 29 of file CutMD.h.
version()
int Mantid::MDAlgorithms::CutMD::version () const inline override
Definition at line 27 of file CutMD.h.
Member Data Documentation
AutoMethod
const std::string Mantid::MDAlgorithms::CutMD::AutoMethod = "Auto" static
Definition at line 40 of file CutMD.h.
Referenced by exec(), and init().
InvAngstromMethod
const std::string Mantid::MDAlgorithms::CutMD::InvAngstromMethod = "Q in A^-1" static
Definition at line 42 of file CutMD.h.
Referenced by init().
InvAngstromSymbol
const std::string Mantid::MDAlgorithms::CutMD::InvAngstromSymbol = "a" static
Definition at line 38 of file CutMD.h.
Referenced by exec(), and Mantid::MDAlgorithms::findOriginalQUnits().
RLUMethod
const std::string Mantid::MDAlgorithms::CutMD::RLUMethod = "RLU" static
Definition at line 41 of file CutMD.h.
Referenced by exec(), and init().
RLUSymbol
const std::string Mantid::MDAlgorithms::CutMD::RLUSymbol = "r" static
Definition at line 39 of file CutMD.h.
Referenced by exec(), and Mantid::MDAlgorithms::findOriginalQUnits().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/CutMD.h
Framework/MDAlgorithms/src/CutMD.cpp