Mantid: Mantid::Kernel::Units::DeltaE Class Reference
Mantid::Kernel::Units::DeltaE Class Reference
Energy transfer in milli-electronvolts.
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
This function returns maximal TOF value still reversibly convertible into the unit.
double conversionTOFMin () const override
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
DeltaE ()
Constructor.
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"DeltaE"
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Protected Member Functions
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes
double efixed
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
double t_other
Energy mode dependent factor in to conversion.
double t_otherFrom
Energy mode dependent factor in from conversion.
double unitScaling
Apply unit scaling to energy value.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
Energy transfer in milli-electronvolts.
Definition at line 477 of file Unit.h.
Constructor & Destructor Documentation
DeltaE()
Mantid::Kernel::Units::DeltaE::DeltaE ()
Constructor.
Definition at line 915 of file Unit.cpp.
References Mantid::Kernel::Unit::addConversion(), Mantid::PhysicalConstants::meVtoFrequency, and Mantid::PhysicalConstants::meVtoWavenumber.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::DeltaE::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 480 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::DeltaE::clone () const override virtual
Returns
a cloned instance of the other
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 1039 of file Unit.cpp.
References DeltaE().
conversionTOFMax()
double Mantid::Kernel::Units::DeltaE::conversionTOFMax () const override virtual
This function returns maximal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 1030 of file Unit.cpp.
References efixed, factorFrom, and t_otherFrom.
Referenced by Mantid::Kernel::Units::DeltaE_inWavenumber::conversionTOFMax(), Mantid::Kernel::Units::DeltaE_inFrequency::conversionTOFMax(), and singleToTOF().
conversionTOFMin()
double Mantid::Kernel::Units::DeltaE::conversionTOFMin () const override virtual
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 1024 of file Unit.cpp.
References Mantid::Kernel::Unit::emode, and t_otherFrom.
Referenced by Mantid::Kernel::Units::DeltaE_inWavenumber::conversionTOFMin(), and Mantid::Kernel::Units::DeltaE_inFrequency::conversionTOFMin().
init()
void Mantid::Kernel::Units::DeltaE::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 944 of file Unit.cpp.
References Mantid::Kernel::efixed, efixed, Mantid::Kernel::Unit::emode, factorFrom, factorTo, Mantid::Kernel::Unit::l1, Mantid::Kernel::l2, Mantid::Kernel::Unit::m_params, Mantid::PhysicalConstants::meV, Mantid::PhysicalConstants::NeutronMass, t_other, t_otherFrom, and unitScaling.
Referenced by Mantid::Kernel::Units::DeltaE_inWavenumber::init(), and Mantid::Kernel::Units::DeltaE_inFrequency::init().
label()
const UnitLabel Mantid::Kernel::Units::DeltaE::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Definition at line 913 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::MilliElectronVolts.
singleFromTOF()
double Mantid::Kernel::Units::DeltaE::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Implements Mantid::Kernel::Unit.
Definition at line 1001 of file Unit.cpp.
References efixed, Mantid::Kernel::Unit::emode, factorFrom, t_otherFrom, and unitScaling.
singleToTOF()
double Mantid::Kernel::Units::DeltaE::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Implements Mantid::Kernel::Unit.
Definition at line 977 of file Unit.cpp.
References conversionTOFMax(), efixed, Mantid::Kernel::Unit::emode, factorTo, t_other, unitScaling, and Mantid::Geometry::x.
unitID()
const std::string Mantid::Kernel::Units::DeltaE::unitID () const override virtual
"DeltaE"
Implements Mantid::Kernel::Unit.
Reimplemented in Mantid::Kernel::Units::DeltaE_inWavenumber, and Mantid::Kernel::Units::DeltaE_inFrequency.
Referenced by validateUnitParams().
validateUnitParams()
void Mantid::Kernel::Units::DeltaE::validateUnitParams (const int emode, const UnitParametersMap & params) override protected virtual
Reimplemented from Mantid::Kernel::Unit.
Definition at line 921 of file Unit.cpp.
References Mantid::Kernel::efixed, efixed, Mantid::Kernel::Unit::emode, Mantid::Kernel::l2, and unitID().
Member Data Documentation
efixed
double Mantid::Kernel::Units::DeltaE::efixed protected
Definition at line 496 of file Unit.h.
Referenced by conversionTOFMax(), init(), singleFromTOF(), singleToTOF(), and validateUnitParams().
factorFrom
double Mantid::Kernel::Units::DeltaE::factorFrom protected
Constant factor for from conversion.
Definition at line 498 of file Unit.h.
Referenced by conversionTOFMax(), init(), and singleFromTOF().
factorTo
double Mantid::Kernel::Units::DeltaE::factorTo protected
Constant factor for to conversion.
Definition at line 497 of file Unit.h.
Referenced by init(), and singleToTOF().
t_other
double Mantid::Kernel::Units::DeltaE::t_other protected
Energy mode dependent factor in to conversion.
Definition at line 499 of file Unit.h.
Referenced by init(), and singleToTOF().
t_otherFrom
double Mantid::Kernel::Units::DeltaE::t_otherFrom protected
Energy mode dependent factor in from conversion.
Definition at line 500 of file Unit.h.
Referenced by conversionTOFMax(), conversionTOFMin(), init(), and singleFromTOF().
unitScaling
double Mantid::Kernel::Units::DeltaE::unitScaling protected
Apply unit scaling to energy value.
Definition at line 501 of file Unit.h.
Referenced by init(), Mantid::Kernel::Units::DeltaE_inWavenumber::init(), Mantid::Kernel::Units::DeltaE_inFrequency::init(), singleFromTOF(), and singleToTOF().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp