Mantid: Framework/PythonInterface/mantid/geometry/src/Exports/Instrument.cpp File Reference
Instrument.cpp File Reference
#include "MantidGeometry/Instrument.h"
#include "MantidGeometry/Instrument/ReferenceFrame.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/register_ptr_to_python.hpp>
Functions
void export_Instrument ()
Function Documentation
export_Instrument()
void export_Instrument ()
Definition at line 37 of file Instrument.cpp.
References Mantid::Geometry::Instrument::baseInstrument(), Mantid::Geometry::Instrument::findGridDetectors(), Mantid::Geometry::Instrument::findRectDetectors(), Mantid::Geometry::Instrument::getDefaultView(), Mantid::Geometry::Instrument::getDetector(), Mantid::Geometry::Instrument::getFilename(), Mantid::Geometry::Instrument::getNumberDetectors(), Mantid::Geometry::Instrument::getReferenceFrame(), Mantid::Geometry::Instrument::getSample(), Mantid::Geometry::Instrument::getSource(), Mantid::Geometry::Instrument::getValidFromDate(), Mantid::Geometry::Instrument::getValidToDate(), and Mantid::Geometry::Instrument::setFilename().