Mantid: Mantid::DataObjects::LeanElasticPeak Class Reference
Mantid::DataObjects::LeanElasticPeak Class Reference
Structure describing a single-crystal peak.
#include <LeanElasticPeak.h>
Public Member Functions
double getAzimuthal () const override
Calculate the azimuthal angle of the peak
int getCol () const override
returns the column (x) of the pixel of the detector, throws NotImplementedError for LeanElasticPeak
double getDSpacing () const override
Calculate the d-spacing of the peak, in 1/Angstroms
double getEnergyTransfer () const override
Get the difference between the initial and final neutron energy in meV, elastic so always 0.
double getFinalEnergy () const override
Get the final neutron energy in meV.
double getInitialEnergy () const override
Get the initial (incident) neutron energy in meV.
double getL1 () const override
Return the L1 flight path length (source to sample), in meters.
double getL2 () const override
Return the L2 flight path length (sample to detector), in meters.
Mantid::Kernel::V3D getQLabFrame () const override
Return the Q change (of the lattice, k_i - k_f) for this peak.
Mantid::Kernel::V3D getQSampleFrame () const override
Return the Q change (of the lattice, k_i - k_f) for this peak.
std::shared_ptr< const Geometry::ReferenceFrame > getReferenceFrame () const override
Return a shared ptr to the reference frame for this peak.
int getRow () const override
returns the row (y) of the pixel of the detector, throws NotImplementedError for LeanElasticPeak
double getScattering () const override
Calculate the scattering angle of the peak
double getTOF () const override
Calculate the time of flight (in microseconds) of the neutrons for this peak, using the geometry of the detector
double getWavelength () const override
Return the neutron wavelength (in angstroms)
LeanElasticPeak ()
Default constructor.
LeanElasticPeak (const Geometry::IPeak &ipeak)
Constructor making a LeanElasticPeak from IPeak interface.
LeanElasticPeak (const LeanElasticPeak &other)
Copy constructor.
LeanElasticPeak (const Mantid::Kernel::V3D &QSampleFrame)
Constructor that uses the Q position of the peak (in the sample frame) and a goniometer rotation matrix.
LeanElasticPeak (const Mantid::Kernel::V3D &QSampleFrame, const Mantid::Kernel::Matrix< double > &goniometer, boost::optional< std::shared_ptr< const Geometry::ReferenceFrame > > refFrame=boost::none)
Constructor that uses the Q position of the peak (in the lab frame).
LeanElasticPeak (const Mantid::Kernel::V3D &QSampleFrame, double wavelength)
Constructor that uses the Q position of the peak (in the sample frame) and a goniometer rotation matrix.
LeanElasticPeak (LeanElasticPeak &&) noexcept=default
LeanElasticPeak & operator= (const LeanElasticPeak &other)
Assignment.
LeanElasticPeak & operator= (LeanElasticPeak &&) noexcept=default
void setFinalEnergy (double m_finalEnergy) override
Set the final energy.
void setInitialEnergy (double m_initialEnergy) override
Set the initial energy.
void setQLabFrame (const Mantid::Kernel::V3D &qLab, boost::optional< double >=boost::none) override
Set the peak using the peak's position in reciprocal space, in the lab frame.
void setQSampleFrame (const Mantid::Kernel::V3D &QSampleFrame, boost::optional< double >=boost::none) override
Set the peak using the peak's position in reciprocal space, in the sample frame.
void setQSampleFrame (const Mantid::Kernel::V3D &QSampleFrame, const Mantid::Kernel::Matrix< double > &goniometer)
void setWavelength (double wavelength) override
Set the wavelength of the neutron.
Public Member Functions inherited from Mantid::DataObjects::BasePeak
BasePeak ()
Default constructor.
BasePeak (BasePeak &&) noexcept=default
BasePeak (const BasePeak &other)
Copy constructor.
BasePeak (const Geometry::IPeak &ipeak)
Constructor making a LeanPeak from IPeak interface.
BasePeak (const Mantid::Kernel::Matrix< double > &goniometer)
Constructor including goniometer.
double getAbsorptionWeightedPathLength () const override
Gets the absorption weighted path length.
double getBinCount () const override
Return the # of counts in the bin at its peak.
Mantid::Kernel::Matrix< double > getGoniometerMatrix () const override
Get the goniometer rotation matrix at which this peak was measured.
double getH () const override
Get the H index of the peak.
Mantid::Kernel::V3D getHKL () const override
Return the HKL vector.
double getIntensity () const override
Return the integrated peak intensity.
double getIntensityOverSigma () const override
Return the peak intensity divided by the error in the intensity.
Mantid::Kernel::V3D getIntHKL () const override
Return the int HKL vector.
Mantid::Kernel::V3D getIntMNP () const override
Return the int MNP vector.
Mantid::Kernel::Matrix< double > getInverseGoniometerMatrix () const
Get the goniometer rotation matrix at which this peak was measured.
double getK () const override
Get the K index of the peak.
double getL () const override
Get the L index of the peak.
double getMonitorCount () const override
Return the monitor count stored in this peak.
int getPeakNumber () const override
Returns the unique peak number Returns -1 if it could not find it.
const Mantid::Geometry::PeakShape & getPeakShape () const override
Get the peak shape.
int getRunNumber () const override
Return the run number this peak was measured at.
Mantid::Kernel::V3D getSamplePos () const override
Return the sample position vector.
double getSigmaIntensity () const override
Return the error on the integrated peak intensity.
virtual double getValueByColName (std::string colName) const
Helper function for displaying/sorting peaks.
bool isIndexed () const override
Return True if the peak has been indexed.
BasePeak & operator= (BasePeak &&) noexcept=default
BasePeak & operator= (const BasePeak &other)
Assignment.
void setAbsorptionWeightedPathLength (double pathLength) override
Set the absorption weighted path length.
void setBinCount (double m_binCount) override
Set the # of counts in the bin at its peak.
void setGoniometerMatrix (const Mantid::Kernel::Matrix< double > &goniometerMatrix) override
Set the goniometer rotation matrix at which this peak was measured.
void setH (double m_H) override
Set the H index of this peak.
void setHKL (const Mantid::Kernel::V3D &HKL) override
Set all HKL.
void setHKL (double H, double K, double L) override
Set all three H,K,L indices of the peak.
void setIntensity (double m_intensity) override
Set the integrated peak intensity.
void setIntHKL (const Kernel::V3D &HKL) override
Set int HKL.
void setIntMNP (const Mantid::Kernel::V3D &MNP) override
Sets the modulated peak structure number.
void setK (double m_K) override
Set the K index of this peak.
void setL (double m_L) override
Set the L index of this peak.
void setMonitorCount (double m_monitorCount) override
Set the monitor count for this peak.
void setPeakNumber (int m_peakNumber) override
Sets the unique peak number.
void setPeakShape (Mantid::Geometry::PeakShape *shape) override
Set the PeakShape.
void setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape) override
Set the PeakShape.
void setRunNumber (int m_runNumber) override
Set the run number that measured this peak.
void setSamplePos (const Mantid::Kernel::V3D &XYZ) override
Set sample position.
void setSamplePos (double samX, double samY, double samZ) override
Set sample position.
void setSigmaIntensity (double m_sigmaIntensity) override
Set the error on the integrated peak intensity.
Public Member Functions inherited from Mantid::Geometry::IPeak
virtual double getAbsorptionWeightedPathLength () const =0
virtual double getAzimuthal () const =0
virtual double getBinCount () const =0
virtual int getCol () const =0
virtual double getDSpacing () const =0
virtual double getEnergyTransfer () const =0
virtual double getFinalEnergy () const =0
virtual Mantid::Kernel::Matrix< double > getGoniometerMatrix () const =0
virtual double getH () const =0
virtual Mantid::Kernel::V3D getHKL () const =0
virtual double getInitialEnergy () const =0
virtual double getIntensity () const =0
virtual double getIntensityOverSigma () const =0
virtual Mantid::Kernel::V3D getIntHKL () const =0
virtual Mantid::Kernel::V3D getIntMNP () const =0
virtual double getK () const =0
virtual double getL () const =0
virtual double getL1 () const =0
virtual double getL2 () const =0
virtual double getMonitorCount () const =0
virtual int getPeakNumber () const =0
virtual const Mantid::Geometry::PeakShape & getPeakShape () const =0
virtual Mantid::Kernel::V3D getQLabFrame () const =0
virtual Mantid::Kernel::V3D getQSampleFrame () const =0
virtual std::shared_ptr< const Geometry::ReferenceFrame > getReferenceFrame () const =0
virtual int getRow () const =0
virtual int getRunNumber () const =0
virtual Mantid::Kernel::V3D getSamplePos () const =0
virtual double getScattering () const =0
virtual double getSigmaIntensity () const =0
virtual double getTOF () const =0
virtual double getWavelength () const =0
virtual bool isIndexed () const =0
virtual void setAbsorptionWeightedPathLength (double pathLength)=0
virtual void setBinCount (double m_BinCount)=0
virtual void setFinalEnergy (double m_FinalEnergy)=0
virtual void setGoniometerMatrix (const Mantid::Kernel::Matrix< double > &m_GoniometerMatrix)=0
virtual void setH (double m_H)=0
virtual void setHKL (const Mantid::Kernel::V3D &HKL)=0
virtual void setHKL (double H, double K, double L)=0
virtual void setInitialEnergy (double m_InitialEnergy)=0
virtual void setIntensity (double m_Intensity)=0
virtual void setIntHKL (const Mantid::Kernel::V3D &HKL)=0
virtual void setIntMNP (const Mantid::Kernel::V3D &MNP)=0
virtual void setK (double m_K)=0
virtual void setL (double m_L)=0
virtual void setMonitorCount (double m_MonitorCount)=0
virtual void setPeakNumber (int m_PeakNumber)=0
virtual void setPeakShape (Mantid::Geometry::PeakShape *shape)=0
virtual void setPeakShape (Mantid::Geometry::PeakShape_const_sptr shape)=0
virtual void setQLabFrame (const Mantid::Kernel::V3D &QLabFrame, boost::optional< double > detectorDistance)=0
virtual void setQSampleFrame (const Mantid::Kernel::V3D &QSampleFrame, boost::optional< double > detectorDistance)=0
virtual void setRunNumber (int m_RunNumber)=0
virtual void setSamplePos (const Mantid::Kernel::V3D &XYZ)=0
virtual void setSamplePos (double samX, double samY, double samZ)=0
virtual void setSigmaIntensity (double m_SigmaIntensity)=0
virtual void setWavelength (double wavelength)=0
virtual ~IPeak ()=default
Private Member Functions
void setReferenceFrame (std::shared_ptr< const Geometry::ReferenceFrame > frame)
Setter for the reference frame.
Private Attributes
Mantid::Kernel::V3D m_Qsample
Q_sample vector.
std::shared_ptr< const Geometry::ReferenceFrame > m_refFrame
double m_wavelength
Wavelength of neutrons at the peak.
Static Private Attributes
static Mantid::Kernel::Logger g_log
Static logger.
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataObjects::BasePeak
double calculateWavelengthFromQLab (const Mantid::Kernel::V3D &qLab)
Protected Attributes inherited from Mantid::DataObjects::BasePeak
std::string m_convention
Mantid::Kernel::V3D m_samplePos
Cached sample position.
Detailed Description
Structure describing a single-crystal peak.
This is a version of Peak that doesn't require the instrument and also assuming elastic scattering. The peak is described only by the Q-sample position. Optionally if the wavelength and goniometer is provided other properties can be calculated.
Definition at line 30 of file LeanElasticPeak.h.
Constructor & Destructor Documentation
LeanElasticPeak() [1/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak ()
Default constructor.
Definition at line 29 of file LeanElasticPeak.cpp.
LeanElasticPeak() [2/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (const Mantid::Kernel::V3D & QSampleFrame)
Constructor that uses the Q position of the peak (in the sample frame) and a goniometer rotation matrix.
No detector ID is set.
Parameters
QSampleFrame :: Q of the center of the peak, in reciprocal space, in the sample frame (goniometer rotation accounted for).
Definition at line 39 of file LeanElasticPeak.cpp.
LeanElasticPeak() [3/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (const Mantid::Kernel::V3D & QSampleFrame, const Mantid::Kernel::Matrix< double > & goniometer, boost::optional< std::shared_ptr< const Geometry::ReferenceFrame > > refFrame = boost::none)
Constructor that uses the Q position of the peak (in the lab frame).
No detector ID is set.
Parameters
QSampleFrame :: Q of the center of the peak, in reciprocal space
goniometer :: a 3x3 rotation matrix
refFrame :: optional reference frame, will default to beam along +Z
Definition at line 50 of file LeanElasticPeak.cpp.
References setQSampleFrame(), and setReferenceFrame().
LeanElasticPeak() [4/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (const Mantid::Kernel::V3D & QSampleFrame, double wavelength)
Constructor that uses the Q position of the peak (in the sample frame) and a goniometer rotation matrix.
No detector ID is set.
Parameters
QSampleFrame :: Q of the center of the peak, in reciprocal space, in the sample frame (goniometer rotation accounted for).
wavelength :: wavelength in Angstroms.
Definition at line 68 of file LeanElasticPeak.cpp.
LeanElasticPeak() [5/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (const LeanElasticPeak & other) default
Copy constructor.
Parameters
other : Source
LeanElasticPeak() [6/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (LeanElasticPeak &&) default noexcept
LeanElasticPeak() [7/7]
Mantid::DataObjects::LeanElasticPeak::LeanElasticPeak (const Geometry::IPeak & ipeak) explicit
Constructor making a LeanElasticPeak from IPeak interface.
Parameters
ipeak :: const reference to an IPeak object
Definition at line 82 of file LeanElasticPeak.cpp.
Member Function Documentation
getAzimuthal()
double Mantid::DataObjects::LeanElasticPeak::getAzimuthal () const override virtual
Calculate the azimuthal angle of the peak
Implements Mantid::Geometry::IPeak.
Definition at line 131 of file LeanElasticPeak.cpp.
References getQLabFrame(), getReferenceFrame(), and Mantid::DataObjects::BasePeak::m_convention.
getCol()
int Mantid::DataObjects::LeanElasticPeak::getCol () const override virtual
returns the column (x) of the pixel of the detector, throws NotImplementedError for LeanElasticPeak
Implements Mantid::Geometry::IPeak.
Definition at line 121 of file LeanElasticPeak.cpp.
getDSpacing()
double Mantid::DataObjects::LeanElasticPeak::getDSpacing () const override virtual
Calculate the d-spacing of the peak, in 1/Angstroms
Implements Mantid::Geometry::IPeak.
Definition at line 144 of file LeanElasticPeak.cpp.
References m_Qsample, and Mantid::Kernel::V3D::norm().
Referenced by getScattering(), and Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus().
getEnergyTransfer()
double Mantid::DataObjects::LeanElasticPeak::getEnergyTransfer () const override virtual
Get the difference between the initial and final neutron energy in meV, elastic so always 0.
Implements Mantid::Geometry::IPeak.
Definition at line 216 of file LeanElasticPeak.cpp.
getFinalEnergy()
double Mantid::DataObjects::LeanElasticPeak::getFinalEnergy () const override virtual
Get the final neutron energy in meV.
Implements Mantid::Geometry::IPeak.
Definition at line 202 of file LeanElasticPeak.cpp.
References energy, Mantid::PhysicalConstants::h, m_wavelength, Mantid::PhysicalConstants::meV, and Mantid::PhysicalConstants::NeutronMass.
Referenced by getInitialEnergy().
getInitialEnergy()
double Mantid::DataObjects::LeanElasticPeak::getInitialEnergy () const override virtual
Get the initial (incident) neutron energy in meV.
Implements Mantid::Geometry::IPeak.
Definition at line 212 of file LeanElasticPeak.cpp.
References getFinalEnergy().
getL1()
double Mantid::DataObjects::LeanElasticPeak::getL1 () const override virtual
Return the L1 flight path length (source to sample), in meters.
Implements Mantid::Geometry::IPeak.
Definition at line 230 of file LeanElasticPeak.cpp.
getL2()
double Mantid::DataObjects::LeanElasticPeak::getL2 () const override virtual
Return the L2 flight path length (sample to detector), in meters.
Implements Mantid::Geometry::IPeak.
Definition at line 236 of file LeanElasticPeak.cpp.
getQLabFrame()
Mantid::Kernel::V3D Mantid::DataObjects::LeanElasticPeak::getQLabFrame () const override virtual
Return the Q change (of the lattice, k_i - k_f) for this peak.
The Q is in the Lab frame: the goniometer rotation was NOT taken out.
Note: There is a 2*pi factor used, so |Q| = 2*pi/wavelength.
Implements Mantid::Geometry::IPeak.
Definition at line 152 of file LeanElasticPeak.cpp.
References Mantid::DataObjects::BasePeak::getGoniometerMatrix(), and m_Qsample.
Referenced by getAzimuthal(), Mantid::DataObjects::Peak::Peak(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and setQSampleFrame().
getQSampleFrame()
Mantid::Kernel::V3D Mantid::DataObjects::LeanElasticPeak::getQSampleFrame () const override virtual
Return the Q change (of the lattice, k_i - k_f) for this peak.
The Q is in the Sample frame: the goniometer rotation WAS taken out.
Implements Mantid::Geometry::IPeak.
Definition at line 157 of file LeanElasticPeak.cpp.
References m_Qsample.
getReferenceFrame()
std::shared_ptr< const Geometry::ReferenceFrame > Mantid::DataObjects::LeanElasticPeak::getReferenceFrame () const override virtual
Return a shared ptr to the reference frame for this peak.
Implements Mantid::Geometry::IPeak.
Definition at line 93 of file LeanElasticPeak.cpp.
References m_refFrame.
Referenced by getAzimuthal().
getRow()
int Mantid::DataObjects::LeanElasticPeak::getRow () const override virtual
returns the row (y) of the pixel of the detector, throws NotImplementedError for LeanElasticPeak
Implements Mantid::Geometry::IPeak.
Definition at line 116 of file LeanElasticPeak.cpp.
getScattering()
double Mantid::DataObjects::LeanElasticPeak::getScattering () const override virtual
Calculate the scattering angle of the peak
Implements Mantid::Geometry::IPeak.
Definition at line 127 of file LeanElasticPeak.cpp.
References getDSpacing(), and getWavelength().
Referenced by Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus().
getTOF()
double Mantid::DataObjects::LeanElasticPeak::getTOF () const override virtual
Calculate the time of flight (in microseconds) of the neutrons for this peak, using the geometry of the detector
Implements Mantid::Geometry::IPeak.
Definition at line 111 of file LeanElasticPeak.cpp.
getWavelength()
double Mantid::DataObjects::LeanElasticPeak::getWavelength () const override virtual
Return the neutron wavelength (in angstroms)
Implements Mantid::Geometry::IPeak.
Definition at line 105 of file LeanElasticPeak.cpp.
References m_wavelength.
Referenced by getScattering(), and Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus().
operator=() [1/2]
LeanElasticPeak & Mantid::DataObjects::LeanElasticPeak::operator= (const LeanElasticPeak & other)
Assignment.
Assignement operator overload.
Parameters
other : Other peak object to assign from
Returns
this
Definition at line 245 of file LeanElasticPeak.cpp.
References m_Qsample, m_wavelength, and Mantid::DataObjects::BasePeak::operator=().
operator=() [2/2]
LeanElasticPeak & Mantid::DataObjects::LeanElasticPeak::operator= (LeanElasticPeak &&) default noexcept
setFinalEnergy()
void Mantid::DataObjects::LeanElasticPeak::setFinalEnergy (double m_finalEnergy) override virtual
Set the final energy.
Implements Mantid::Geometry::IPeak.
Definition at line 219 of file LeanElasticPeak.cpp.
setInitialEnergy()
void Mantid::DataObjects::LeanElasticPeak::setInitialEnergy (double m_initialEnergy) override virtual
Set the initial energy.
Implements Mantid::Geometry::IPeak.
Definition at line 224 of file LeanElasticPeak.cpp.
setQLabFrame()
void Mantid::DataObjects::LeanElasticPeak::setQLabFrame (const Mantid::Kernel::V3D & qLab, boost::optional< double > = boost::none) override virtual
Set the peak using the peak's position in reciprocal space, in the lab frame.
Parameters
qLab :: Q of the center of the peak, in reciprocal space. This is in inelastic convention: momentum transfer of the LATTICE! Also, q does have a 2pi factor = it is equal to 2pi/wavelength (in Angstroms).
Implements Mantid::Geometry::IPeak.
Definition at line 196 of file LeanElasticPeak.cpp.
References Mantid::DataObjects::BasePeak::getInverseGoniometerMatrix(), and setQSampleFrame().
setQSampleFrame() [1/2]
void Mantid::DataObjects::LeanElasticPeak::setQSampleFrame (const Mantid::Kernel::V3D & QSampleFrame, boost::optional< double > = boost::none) override virtual
Set the peak using the peak's position in reciprocal space, in the sample frame.
Parameters
QSampleFrame :: Q of the center of the peak, in reciprocal space This is in inelastic convention: momentum transfer of the LATTICE! Also, q does NOT have a 2pi factor = it is equal to 1/wavelength.
Implements Mantid::Geometry::IPeak.
Definition at line 167 of file LeanElasticPeak.cpp.
References m_Qsample.
Referenced by LeanElasticPeak(), and setQLabFrame().
setQSampleFrame() [2/2]
void Mantid::DataObjects::LeanElasticPeak::setQSampleFrame (const Mantid::Kernel::V3D & QSampleFrame, const Mantid::Kernel::Matrix< double > & goniometer)
Definition at line 171 of file LeanElasticPeak.cpp.
References Mantid::DataObjects::BasePeak::calculateWavelengthFromQLab(), g_log, getQLabFrame(), Mantid::Kernel::Logger::information(), m_Qsample, Mantid::DataObjects::BasePeak::setGoniometerMatrix(), and setWavelength().
setReferenceFrame()
void Mantid::DataObjects::LeanElasticPeak::setReferenceFrame (std::shared_ptr< const Geometry::ReferenceFrame > frame) private
Setter for the reference frame.
Parameters
frame : reference frame object to use.
Definition at line 101 of file LeanElasticPeak.cpp.
References m_refFrame.
Referenced by LeanElasticPeak().
setWavelength()
void Mantid::DataObjects::LeanElasticPeak::setWavelength (double wavelength) override virtual
Set the wavelength of the neutron.
Assumes elastic scattering.
Parameters
wavelength :: wavelength in Angstroms.
Implements Mantid::Geometry::IPeak.
Definition at line 90 of file LeanElasticPeak.cpp.
References m_wavelength.
Referenced by setQSampleFrame().
Member Data Documentation
g_log
Mantid::Kernel::Logger Mantid::DataObjects::LeanElasticPeak::g_log static private
Static logger.
Definition at line 100 of file LeanElasticPeak.h.
Referenced by setQSampleFrame().
m_Qsample
Mantid::Kernel::V3D Mantid::DataObjects::LeanElasticPeak::m_Qsample private
Q_sample vector.
Definition at line 92 of file LeanElasticPeak.h.
Referenced by getDSpacing(), getQLabFrame(), getQSampleFrame(), operator=(), and setQSampleFrame().
m_refFrame
std::shared_ptr<const Geometry::ReferenceFrame> Mantid::DataObjects::LeanElasticPeak::m_refFrame private
Definition at line 97 of file LeanElasticPeak.h.
Referenced by getReferenceFrame(), and setReferenceFrame().
m_wavelength
double Mantid::DataObjects::LeanElasticPeak::m_wavelength private
Wavelength of neutrons at the peak.
Definition at line 95 of file LeanElasticPeak.h.
Referenced by getFinalEnergy(), getWavelength(), operator=(), and setWavelength().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/LeanElasticPeak.h
Framework/DataObjects/src/LeanElasticPeak.cpp