Mantid: ICat4::ns1__parameter Class Reference
ICat4::ns1__parameter Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__parameter ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
time_t * dateTimeValue
double * error
double * numericValue
double * rangeBottom
double * rangeTop
std::string * stringValue
ns1__parameterType * type
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2018 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__parameter()
ICat4::ns1__parameter::ns1__parameter () inline
Definition at line 2035 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__parameter::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11500 of file ICat4C.cpp.
References dateTimeValue, error, numericValue, rangeBottom, rangeTop, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), stringValue, and type.
Referenced by ICat4::ns1__dataCollectionParameter::soap_default(), ICat4::ns1__datafileParameter::soap_default(), ICat4::ns1__datasetParameter::soap_default(), ICat4::ns1__investigationParameter::soap_default(), ICat4::ns1__sampleParameter::soap_default(), ICat4::soap_in_ns1__parameter(), ICat4::soap_new_req_ns1__parameter(), and ICat4::soap_new_set_ns1__parameter().
soap_get()
void * ICat4::ns1__parameter::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11692 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_get_ns1__parameter(), and type.
soap_in()
void * ICat4::ns1__parameter::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11564 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_in_ns1__parameter(), and type.
Referenced by ICat4::soap_in_ns1__parameter().
soap_out()
int ICat4::ns1__parameter::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11528 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, ICat4::soap_out_ns1__parameter(), and type.
Referenced by soap_put().
soap_put()
int ICat4::ns1__parameter::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11685 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), SOAP_TYPE_ICat4_ns1__parameter, and type.
soap_serialize()
void ICat4::ns1__parameter::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 11513 of file ICat4C.cpp.
References dateTimeValue, error, numericValue, rangeBottom, rangeTop, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTodouble(), ICat4::soap_serialize_PointerTons1__parameterType(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), stringValue, and type.
Referenced by ICat4::ns1__dataCollectionParameter::soap_serialize(), ICat4::ns1__datafileParameter::soap_serialize(), ICat4::ns1__datasetParameter::soap_serialize(), ICat4::ns1__investigationParameter::soap_serialize(), and ICat4::ns1__sampleParameter::soap_serialize().
soap_type()
int ICat4::ns1__parameter::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Reimplemented in ICat4::ns1__sampleParameter.
Definition at line 2028 of file ICat4Stub.h.
Member Data Documentation
dateTimeValue
time_t* ICat4::ns1__parameter::dateTimeValue
Definition at line 2020 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
error
double* ICat4::ns1__parameter::error
Definition at line 2021 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
numericValue
double* ICat4::ns1__parameter::numericValue
Definition at line 2022 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
rangeBottom
double* ICat4::ns1__parameter::rangeBottom
Definition at line 2023 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
rangeTop
double* ICat4::ns1__parameter::rangeTop
Definition at line 2024 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
stringValue
std::string* ICat4::ns1__parameter::stringValue
Definition at line 2025 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
type
ns1__parameterType* ICat4::ns1__parameter::type
Definition at line 2026 of file ICat4Stub.h.
Referenced by soap_default(), soap_get(), ICat4::ns1__dataCollectionParameter::soap_get(), ICat4::ns1__datafileParameter::soap_get(), ICat4::ns1__datasetParameter::soap_get(), ICat4::ns1__investigationParameter::soap_get(), ICat4::ns1__sampleParameter::soap_get(), soap_in(), ICat4::ns1__dataCollectionParameter::soap_in(), ICat4::ns1__datafileParameter::soap_in(), ICat4::ns1__datasetParameter::soap_in(), ICat4::ns1__investigationParameter::soap_in(), ICat4::ns1__sampleParameter::soap_in(), ICat4::soap_in_ns1__dataCollectionParameter(), ICat4::soap_in_ns1__datafileParameter(), ICat4::soap_in_ns1__datasetParameter(), ICat4::soap_in_ns1__investigationParameter(), ICat4::soap_in_ns1__parameter(), ICat4::soap_in_ns1__sampleParameter(), soap_out(), ICat4::ns1__dataCollectionParameter::soap_out(), ICat4::ns1__datafileParameter::soap_out(), ICat4::ns1__datasetParameter::soap_out(), ICat4::ns1__investigationParameter::soap_out(), ICat4::ns1__sampleParameter::soap_out(), soap_put(), ICat4::ns1__dataCollectionParameter::soap_put(), ICat4::ns1__datafileParameter::soap_put(), ICat4::ns1__datasetParameter::soap_put(), ICat4::ns1__investigationParameter::soap_put(), ICat4::ns1__sampleParameter::soap_put(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp