Mantid: Mantid::Algorithms::CarpenterSampleCorrection Class Reference
Mantid::Algorithms::CarpenterSampleCorrection Class Reference
Multiple scattering absorption correction, originally used to correct vanadium spectrum at IPNS.
#include <CarpenterSampleCorrection.h>
Public Member Functions
const std::string alias () const override
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
API::WorkspaceGroup_sptr calculateCorrection (API::MatrixWorkspace_sptr &inputWksp, double radius, double coeff1, double coeff2, double coeff3, bool doAbs, bool doMS)
void exec () override
Execute the algorithm.
void init () override
Initialize the properties to default values.
API::MatrixWorkspace_sptr minus (const API::MatrixWorkspace_sptr &lhsWS, const API::MatrixWorkspace_sptr &rhsWS)
API::MatrixWorkspace_sptr multiply (const API::MatrixWorkspace_sptr &lhsWS, const API::MatrixWorkspace_sptr &rhsWS)
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
Workspace_sptr assemble (const std::string &partialWSName, const std::string &outputWSName)
Assemble the partial workspaces from all MPI processes.
Workspace_sptr assemble (Workspace_sptr partialWS)
Assemble the partial workspaces from all MPI processes.
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
int getNThreads ()
Return the number of MPI processes running.
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
bool isMainThread ()
Return true if we are running on the main thread.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Protected Attributes inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
bool m_useMPI
MPI option. If false, we will use one job event if MPI is available.
Detailed Description
Multiple scattering absorption correction, originally used to correct vanadium spectrum at IPNS.
Algorithm originally worked out by Jack Carpenter and Asfia Huq and implmented in Java by Alok Chatterjee. Translated to C++ by Dennis Mikkelson.
Definition at line 20 of file CarpenterSampleCorrection.h.
Member Function Documentation
alias()
const std::string Mantid::Algorithms::CarpenterSampleCorrection::alias () const inline override
Definition at line 46 of file CarpenterSampleCorrection.h.
calculateCorrection()
WorkspaceGroup_sptr Mantid::Algorithms::CarpenterSampleCorrection::calculateCorrection (API::MatrixWorkspace_sptr & inputWksp, double radius, double coeff1, double coeff2, double coeff3, bool doAbs, bool doMS) private
Definition at line 105 of file CarpenterSampleCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and radius.
Referenced by exec().
category()
const std::string Mantid::Algorithms::CarpenterSampleCorrection::category () const override
Algorithm's category for identification overriding a virtual method.
Definition at line 30 of file CarpenterSampleCorrection.cpp.
exec()
void Mantid::Algorithms::CarpenterSampleCorrection::exec () override private
Execute the algorithm.
Definition at line 59 of file CarpenterSampleCorrection.cpp.
References calculateCorrection(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), minus(), multiply(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_FOR_IF, PARALLEL_START_INTERRUPT_REGION, radius, Mantid::Kernel::threadSafe(), and Mantid::Geometry::y.
init()
void Mantid::Algorithms::CarpenterSampleCorrection::init () override private
Initialize the properties to default values.
Definition at line 35 of file CarpenterSampleCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::copyProperty(), Mantid::Kernel::Direction::Input, Mantid::Kernel::SingletonHolder< T >::Instance(), and Mantid::Kernel::Direction::Output.
minus()
MatrixWorkspace_sptr Mantid::Algorithms::CarpenterSampleCorrection::minus (const API::MatrixWorkspace_sptr & lhsWS, const API::MatrixWorkspace_sptr & rhsWS) private
Definition at line 121 of file CarpenterSampleCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and minus().
Referenced by exec(), and minus().
multiply()
MatrixWorkspace_sptr Mantid::Algorithms::CarpenterSampleCorrection::multiply (const API::MatrixWorkspace_sptr & lhsWS, const API::MatrixWorkspace_sptr & rhsWS) private
Definition at line 131 of file CarpenterSampleCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and multiply().
Referenced by exec(), and multiply().
name()
const std::string Mantid::Algorithms::CarpenterSampleCorrection::name () const override
Algorithm's name for identification overriding a virtual method.
Definition at line 26 of file CarpenterSampleCorrection.cpp.
seeAlso()
const std::vector< std::string > Mantid::Algorithms::CarpenterSampleCorrection::seeAlso () const inline override
Definition at line 27 of file CarpenterSampleCorrection.h.
summary()
const std::string Mantid::Algorithms::CarpenterSampleCorrection::summary () const inline override
Summary of algorithms purpose.
Definition at line 40 of file CarpenterSampleCorrection.h.
version()
int Mantid::Algorithms::CarpenterSampleCorrection::version () const override
Algorithm's version for identification overriding a virtual method.
Definition at line 28 of file CarpenterSampleCorrection.cpp.
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/CarpenterSampleCorrection.h
Framework/Algorithms/src/CarpenterSampleCorrection.cpp