Mantid: MantidQt::MantidWidgets::SelectWorkspacesDialog Class Reference
MantidQt::MantidWidgets::SelectWorkspacesDialog Class Reference
This is a dialog for selecting workspaces.
#include <SelectWorkspacesDialog.h>
Public Member Functions
QStringList getSelectedNames () const
Return the selected names.
SelectWorkspacesDialog (QWidget *parent=nullptr, const std::string &typeFilter="", const std::string &customButtonLabel="", QAbstractItemView::SelectionMode mode=QAbstractItemView::MultiSelection)
Constructor.
Static Public Attributes
static const int CustomButton = 45654
return value of the Custom button
Private Slots
void customButtonPress ()
slot to handle the custom button press
void selectionChanged ()
Slot to monitor the workspace selection status.
Private Attributes
QPushButton * m_customButton
The OK button.
QPushButton * m_okButton
The OK button.
QListWidget * m_wsList
Displays available workspace names.
Detailed Description
This is a dialog for selecting workspaces.
Author
Roman Tolchenov, Tessella plc
Date
22/06/2010
Definition at line 28 of file SelectWorkspacesDialog.h.
Constructor & Destructor Documentation
SelectWorkspacesDialog()
MantidQt::MantidWidgets::SelectWorkspacesDialog::SelectWorkspacesDialog (QWidget * parent = nullptr, const std::string & typeFilter = "", const std::string & customButtonLabel = "", QAbstractItemView::SelectionMode mode = QAbstractItemView::MultiSelection)
Constructor.
Parameters
parent : Parent widget
typeFilter : optional filter for filtering workspaces by type.
customButtonLabel : optional label for another custom button, return code for this is defined by CustomButton.
mode : optional selection mode for the list widget, default is MultiSelection
Definition at line 55 of file SelectWorkspacesDialog.cpp.
References customButtonPress(), Mantid::Kernel::DataService< T >::getObjects(), m_customButton, m_okButton, m_wsList, selectionChanged(), and tmp.
Member Function Documentation
customButtonPress
void MantidQt::MantidWidgets::SelectWorkspacesDialog::customButtonPress () private slot
slot to handle the custom button press
Definition at line 115 of file SelectWorkspacesDialog.cpp.
References CustomButton.
Referenced by SelectWorkspacesDialog().
getSelectedNames()
QStringList MantidQt::MantidWidgets::SelectWorkspacesDialog::getSelectedNames () const
Return the selected names.
Definition at line 102 of file SelectWorkspacesDialog.cpp.
References m_wsList.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::addWorkspace().
selectionChanged
void MantidQt::MantidWidgets::SelectWorkspacesDialog::selectionChanged () private slot
Slot to monitor the workspace selection status.
Definition at line 112 of file SelectWorkspacesDialog.cpp.
References m_okButton, and m_wsList.
Referenced by SelectWorkspacesDialog().
Member Data Documentation
CustomButton
const int MantidQt::MantidWidgets::SelectWorkspacesDialog::CustomButton = 45654 static
return value of the Custom button
Definition at line 33 of file SelectWorkspacesDialog.h.
Referenced by customButtonPress().
m_customButton
QPushButton* MantidQt::MantidWidgets::SelectWorkspacesDialog::m_customButton private
The OK button.
Definition at line 58 of file SelectWorkspacesDialog.h.
Referenced by SelectWorkspacesDialog().
m_okButton
QPushButton* MantidQt::MantidWidgets::SelectWorkspacesDialog::m_okButton private
The OK button.
Definition at line 56 of file SelectWorkspacesDialog.h.
Referenced by selectionChanged(), and SelectWorkspacesDialog().
m_wsList
QListWidget* MantidQt::MantidWidgets::SelectWorkspacesDialog::m_wsList private
Displays available workspace names.
Definition at line 54 of file SelectWorkspacesDialog.h.
Referenced by getSelectedNames(), selectionChanged(), and SelectWorkspacesDialog().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/SelectWorkspacesDialog.h
qt/widgets/common/src/SelectWorkspacesDialog.cpp