Mantid: Mantid::PropertyNames Namespace Reference
Mantid::PropertyNames Namespace Reference
Functions
const std::string BINMODE ("BinningMode")
const std::string BINWIDTH ("BinWidth")
const std::string CALIB_WKSP ("CalibrationWorkspace")
const std::string FULL_BIN_ONLY ("FullBinsOnly")
const std::string IGNR_BIN_ERR ("IgnoreBinErrors")
const std::string INPUT_WKSP ("InputWorkspace")
const std::string OFFSET_MODE ("OffsetMode")
const std::string OFFSTS_WKSP ("OffsetsWorkspace")
const std::string OUTPUT_WKSP ("OutputWorkspace")
const std::string PARAMS ("Params")
const std::string POWER ("Power")
const std::string PRSRV_EVENTS ("PreserveEvents")
const std::string RVRS_LOG_BIN ("UseReverseLogarithmic")
Function Documentation
BINMODE()
const std::string Mantid::PropertyNames::BINMODE ("BinningMode")
Referenced by Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::createOutputWorkspace(), Mantid::Algorithms::Rebin::init(), and Mantid::Algorithms::Rebin::validateInputs().
BINWIDTH()
const std::string Mantid::PropertyNames::BINWIDTH ("BinWidth")
Referenced by Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::CalculateDIFC::validateInputs(), and Mantid::Algorithms::ConvertDiffCal::validateInputs().
CALIB_WKSP()
const std::string Mantid::PropertyNames::CALIB_WKSP ("CalibrationWorkspace")
Referenced by Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::CalculateDIFC::validateInputs(), and Mantid::Algorithms::ConvertDiffCal::validateInputs().
FULL_BIN_ONLY()
const std::string Mantid::PropertyNames::FULL_BIN_ONLY ("FullBinsOnly")
Referenced by Mantid::Algorithms::Rebin::exec(), and Mantid::Algorithms::Rebin::init().
IGNR_BIN_ERR()
const std::string Mantid::PropertyNames::IGNR_BIN_ERR ("IgnoreBinErrors")
Referenced by Mantid::Algorithms::Rebin::exec(), and Mantid::Algorithms::Rebin::init().
INPUT_WKSP()
const std::string Mantid::PropertyNames::INPUT_WKSP ("InputWorkspace")
Referenced by Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::Algorithms::AddLogInterpolated::init(), Mantid::Algorithms::AddLogSmoothed::init(), Mantid::Algorithms::ApplyTransmissionCorrection::init(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::EstimateResolutionDiffraction::init(), Mantid::Algorithms::FilterByTime::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::LorentzCorrection::init(), Mantid::Algorithms::Rebin::init(), Mantid::DataHandling::LoadDetectorsGroupingFile::init(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::init(), Mantid::Algorithms::EstimateResolutionDiffraction::processAlgProperties(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::Algorithms::AddLogInterpolated::validateInputs(), Mantid::Algorithms::AddLogSmoothed::validateInputs(), Mantid::Algorithms::ApplyTransmissionCorrection::validateInputs(), Mantid::Algorithms::LorentzCorrection::validateInputs(), Mantid::Algorithms::Rebin::validateInputs(), and Mantid::WorkflowAlgorithms::AlignAndFocusPowder::validateInputs().
OFFSET_MODE()
const std::string Mantid::PropertyNames::OFFSET_MODE ("OffsetMode")
Referenced by Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::CalculateDIFC::validateInputs(), and Mantid::Algorithms::ConvertDiffCal::validateInputs().
OFFSTS_WKSP()
const std::string Mantid::PropertyNames::OFFSTS_WKSP ("OffsetsWorkspace")
Referenced by Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::ConvertDiffCal::init(), and Mantid::Algorithms::CalculateDIFC::validateInputs().
OUTPUT_WKSP()
const std::string Mantid::PropertyNames::OUTPUT_WKSP ("OutputWorkspace")
Referenced by Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::CombineDiffCal::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::EstimateResolutionDiffraction::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::init(), Mantid::Algorithms::CalculateDIFC::init(), Mantid::Algorithms::CombineDiffCal::init(), Mantid::Algorithms::ConvertDiffCal::init(), Mantid::Algorithms::EstimateResolutionDiffraction::init(), Mantid::Algorithms::FilterByTime::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::LorentzCorrection::init(), Mantid::Algorithms::Rebin::init(), Mantid::DataHandling::LoadDetectorsGroupingFile::init(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::init(), Mantid::Algorithms::FitPeaks::processOutputs(), and Mantid::WorkflowAlgorithms::AlignAndFocusPowder::validateInputs().
PARAMS()
const std::string Mantid::PropertyNames::PARAMS ("Params")
Referenced by Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::AddLogSmoothed::init(), Mantid::Algorithms::Rebin::init(), Mantid::Algorithms::AddLogSmoothed::validateInputs(), and Mantid::Algorithms::Rebin::validateInputs().
POWER()
const std::string Mantid::PropertyNames::POWER ("Power")
Referenced by Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin::init(), and Mantid::Algorithms::Rebin::validateInputs().
PRSRV_EVENTS()
const std::string Mantid::PropertyNames::PRSRV_EVENTS ("PreserveEvents")
Referenced by Mantid::Algorithms::Rebin::exec(), and Mantid::Algorithms::Rebin::init().
RVRS_LOG_BIN()
const std::string Mantid::PropertyNames::RVRS_LOG_BIN ("UseReverseLogarithmic")
Referenced by Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin::init(), and Mantid::Algorithms::Rebin::validateInputs().