Mantid: MantidQt::API::PropertyWidgetFactory Class Reference
MantidQt::API::PropertyWidgetFactory Class Reference
PropertyWidgetFactory : TODO: DESCRIPTION.
#include <PropertyWidgetFactory.h>
Public Member Functions
PropertyWidgetFactory ()
Constructor.
virtual ~PropertyWidgetFactory ()
Destructor.
Static Public Member Functions
static PropertyWidget * createWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Create the appropriate PropertyWidget for the given Property.
Detailed Description
PropertyWidgetFactory : TODO: DESCRIPTION.
Date
2012-02-17
Definition at line 27 of file PropertyWidgetFactory.h.
Constructor & Destructor Documentation
PropertyWidgetFactory()
MantidQt::API::PropertyWidgetFactory::PropertyWidgetFactory () default
Constructor.
~PropertyWidgetFactory()
MantidQt::API::PropertyWidgetFactory::~PropertyWidgetFactory () virtual default
Destructor.
Member Function Documentation
createWidget()
PropertyWidget * MantidQt::API::PropertyWidgetFactory::createWidget (Mantid::Kernel::Property * prop, QWidget * parent = nullptr, QGridLayout * layout = nullptr, int row = -1) static
Create the appropriate PropertyWidget for the given Property.
Parameters
prop :: property for the widget
parent :: parent widget
layout :: QGridLayout of the parent, in the case of the GenericDialog
row :: row in the above QGridLayout, if specified
Returns
the right PropertyWidget * subclass
Definition at line 41 of file PropertyWidgetFactory.cpp.
References Mantid::Kernel::Property::allowedValues(), and Mantid::Kernel::Property::isMultipleSelectionAllowed().
Referenced by MantidQt::API::AlgorithmPropertiesWidget::hideOrDisableProperties(), and MantidQt::API::AlgorithmPropertiesWidget::initLayout().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/PropertyWidgetFactory.h
qt/widgets/common/src/PropertyWidgetFactory.cpp