Mantid: Mantid::DataHandling::EMU::EventProcessor Class Reference
Mantid::DataHandling::EMU::EventProcessor Class Reference abstract
Public Member Functions
void addEvent (size_t x, size_t p, double tdop, double taux)
double duration () const
EventProcessor (const std::vector< bool > &roi, const std::vector< size_t > &mapIndex, const size_t stride, const double framePeriod, const double gatePeriod, TimeLimits timeBoundary, TimeLimits directLimits, TimeLimits analysedLimits, bool includeBM)
int64_t frameStart () const
void newFrame ()
bool validFrame () const
Protected Member Functions
virtual void addEventImpl (size_t id, size_t x, size_t y, double tof)=0
virtual void addPseudoBMEventImpl (size_t id, double tobs)=0
Protected Attributes
const TimeLimits m_analysedTaux
const TimeLimits m_directTaux
const double m_framePeriod
size_t m_frames
size_t m_framesValid
const double m_gatePeriod
const bool m_includeBM
const std::vector< size_t > & m_mapIndex
const std::vector< bool > & m_roi
const size_t m_stride
const TimeLimits m_timeBoundary
Detailed Description
Definition at line 375 of file LoadEMU.cpp.
Constructor & Destructor Documentation
EventProcessor()
Mantid::DataHandling::EMU::EventProcessor::EventProcessor (const std::vector< bool > & roi, const std::vector< size_t > & mapIndex, const size_t stride, const double framePeriod, const double gatePeriod, TimeLimits timeBoundary, TimeLimits directLimits, TimeLimits analysedLimits, bool includeBM) inline
Definition at line 399 of file LoadEMU.cpp.
Member Function Documentation
addEvent()
void Mantid::DataHandling::EMU::EventProcessor::addEvent (size_t x, size_t p, double tdop, double taux) inline
Definition at line 428 of file LoadEMU.cpp.
References addEventImpl(), addPseudoBMEventImpl(), m_analysedTaux, m_directTaux, m_gatePeriod, m_mapIndex, m_roi, m_stride, validFrame(), Mantid::Geometry::x, and Mantid::Geometry::y.
addEventImpl()
virtual void Mantid::DataHandling::EMU::EventProcessor::addEventImpl (size_t id, size_t x, size_t y, double tof) protected pure virtual
Implemented in Mantid::DataHandling::EMU::EventAssigner, and Mantid::DataHandling::EMU::EventCounter.
Referenced by addEvent().
addPseudoBMEventImpl()
virtual void Mantid::DataHandling::EMU::EventProcessor::addPseudoBMEventImpl (size_t id, double tobs) protected pure virtual
Implemented in Mantid::DataHandling::EMU::EventAssigner, and Mantid::DataHandling::EMU::EventCounter.
Referenced by addEvent().
duration()
double Mantid::DataHandling::EMU::EventProcessor::duration () const inline
Definition at line 417 of file LoadEMU.cpp.
References m_framePeriod, and m_frames.
Referenced by Mantid::DataHandling::LoadEMU< FD >::exec().
frameStart()
int64_t Mantid::DataHandling::EMU::EventProcessor::frameStart () const inline
Definition at line 422 of file LoadEMU.cpp.
References m_framePeriod, and m_frames.
Referenced by Mantid::DataHandling::EMU::EventAssigner::addEventImpl(), and Mantid::DataHandling::EMU::EventAssigner::addPseudoBMEventImpl().
newFrame()
void Mantid::DataHandling::EMU::EventProcessor::newFrame () inline
Definition at line 406 of file LoadEMU.cpp.
References m_frames, m_framesValid, and validFrame().
validFrame()
bool Mantid::DataHandling::EMU::EventProcessor::validFrame () const inline
Definition at line 412 of file LoadEMU.cpp.
References m_framePeriod, m_frames, and m_timeBoundary.
Referenced by addEvent(), and newFrame().
Member Data Documentation
m_analysedTaux
const TimeLimits Mantid::DataHandling::EMU::EventProcessor::m_analysedTaux protected
Definition at line 391 of file LoadEMU.cpp.
Referenced by addEvent().
m_directTaux
const TimeLimits Mantid::DataHandling::EMU::EventProcessor::m_directTaux protected
Definition at line 390 of file LoadEMU.cpp.
Referenced by addEvent().
m_framePeriod
const double Mantid::DataHandling::EMU::EventProcessor::m_framePeriod protected
Definition at line 381 of file LoadEMU.cpp.
Referenced by duration(), frameStart(), and validFrame().
m_frames
size_t Mantid::DataHandling::EMU::EventProcessor::m_frames protected
Definition at line 385 of file LoadEMU.cpp.
Referenced by duration(), frameStart(), newFrame(), and validFrame().
m_framesValid
size_t Mantid::DataHandling::EMU::EventProcessor::m_framesValid protected
Definition at line 386 of file LoadEMU.cpp.
Referenced by newFrame(), and Mantid::DataHandling::EMU::EventCounter::numFrames().
m_gatePeriod
const double Mantid::DataHandling::EMU::EventProcessor::m_gatePeriod protected
Definition at line 382 of file LoadEMU.cpp.
Referenced by addEvent().
m_includeBM
const bool Mantid::DataHandling::EMU::EventProcessor::m_includeBM protected
Definition at line 393 of file LoadEMU.cpp.
Referenced by Mantid::DataHandling::EMU::EventAssigner::addPseudoBMEventImpl(), and Mantid::DataHandling::EMU::EventCounter::addPseudoBMEventImpl().
m_mapIndex
const std::vector<size_t>& Mantid::DataHandling::EMU::EventProcessor::m_mapIndex protected
Definition at line 379 of file LoadEMU.cpp.
Referenced by addEvent().
m_roi
const std::vector<bool>& Mantid::DataHandling::EMU::EventProcessor::m_roi protected
Definition at line 378 of file LoadEMU.cpp.
Referenced by addEvent().
m_stride
const size_t Mantid::DataHandling::EMU::EventProcessor::m_stride protected
Definition at line 380 of file LoadEMU.cpp.
Referenced by addEvent().
m_timeBoundary
const TimeLimits Mantid::DataHandling::EMU::EventProcessor::m_timeBoundary protected
Definition at line 389 of file LoadEMU.cpp.
Referenced by validFrame().
The documentation for this class was generated from the following file:
Framework/DataHandling/src/LoadEMU.cpp