Mantid: Mantid::Algorithms::LoqMeta Struct Reference
Mantid::Algorithms::LoqMeta Struct Reference
Static Public Member Functions
static constexpr int HAB1IndexStop ()
static constexpr int HAB2IndexStop ()
static constexpr int HAB3IndexStop ()
static constexpr int HABIndexStart ()
static constexpr int HABIndividualBanks ()
static constexpr int HABTotalBanks ()
static constexpr int histograms ()
static constexpr int LABIndexStart ()
static constexpr int LABTotalBanks ()
Detailed Description
Definition at line 29 of file GenerateFlatCellWorkspaceLOQ.cpp.
Member Function Documentation
HAB1IndexStop()
static constexpr int Mantid::Algorithms::LoqMeta::HAB1IndexStop () inline static constexpr
Definition at line 36 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
HAB2IndexStop()
static constexpr int Mantid::Algorithms::LoqMeta::HAB2IndexStop () inline static constexpr
Definition at line 37 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
HAB3IndexStop()
static constexpr int Mantid::Algorithms::LoqMeta::HAB3IndexStop () inline static constexpr
Definition at line 38 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
HABIndexStart()
static constexpr int Mantid::Algorithms::LoqMeta::HABIndexStart () inline static constexpr
Definition at line 35 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::createAndSaveMaskWorkspace(), and Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
HABIndividualBanks()
static constexpr int Mantid::Algorithms::LoqMeta::HABIndividualBanks () inline static constexpr
Definition at line 34 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
HABTotalBanks()
static constexpr int Mantid::Algorithms::LoqMeta::HABTotalBanks () inline static constexpr
Definition at line 33 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
histograms()
static constexpr int Mantid::Algorithms::LoqMeta::histograms () inline static constexpr
Definition at line 30 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::exec(), Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::integrateInput(), and Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::validateInputs().
LABIndexStart()
static constexpr int Mantid::Algorithms::LoqMeta::LABIndexStart () inline static constexpr
Definition at line 31 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::createAndSaveMaskWorkspace(), Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::integrateInput(), and Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
LABTotalBanks()
static constexpr int Mantid::Algorithms::LoqMeta::LABTotalBanks () inline static constexpr
Definition at line 32 of file GenerateFlatCellWorkspaceLOQ.cpp.
Referenced by Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::createAndSaveMaskWorkspace(), and Mantid::Algorithms::GenerateFlatCellWorkspaceLOQ::normalizeBanks().
The documentation for this struct was generated from the following file:
Framework/Algorithms/src/GenerateFlatCellWorkspaceLOQ.cpp