Mantid: Mantid::Geometry::Rule Class Reference
Mantid::Geometry::Rule Class Reference abstract
Object generation rule tree.
#include <Rules.h>
Public Member Functions
int checkParents () const
Debug test for parents.
virtual std::string className () const
Returns class name as string.
std::unique_ptr< Rule > clone () const
int commonType () const
Gets a common type.
virtual std::string display () const =0
Abstract Display.
virtual std::string displayAddress () const =0
Abstract Display Address.
int Eliminate ()
elimination not written
virtual Rule * findKey (const int)=0
Abstract key find.
virtual int findLeaf (const Rule *) const =0
Abstract find.
virtual void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin)=0
Abstract getBoundingBox.
int getKeyList (std::vector< int > &) const
Generate the key list given an insertion type object.
Rule * getParent () const
Returns the parent object.
virtual int isComplementary () const
Always returns false (0)
virtual bool isValid (const Kernel::V3D &) const =0
Abstract: The point is within the object.
virtual bool isValid (const std::map< int, int > &) const =0
Abstract Validity based on surface true/false map.
virtual Rule * leaf (const int=0) const
No leaf for a base rule.
void makeParents ()
This is initialisation code that populates all the parents in the rule tree.
Rule ()
Standard Constructor.
Rule (Rule *)
Constructor copies.
virtual void setLeaf (std::unique_ptr< Rule >, const int=0)=0
Abstract set.
virtual void setLeaves (std::unique_ptr< Rule >, std::unique_ptr< Rule >)=0
abstract set leaves
void setParent (Rule *)
Sets the parent object (not check for A==this)
virtual int simplify ()=0
Abstract: Can the rule be simplified.
int substituteSurf (const int SurfN, const int newSurfN, const std::shared_ptr< Surface > &SPtr)
Substitues a surface item if within a rule.
virtual int type () const
Null rule.
virtual ~Rule ()=default
Static Public Member Functions
static int makeCNF (std::unique_ptr< Rule > &)
Make Rule into a CNF format.
static int makeCNFcopy (std::unique_ptr< Rule > &)
Make Rule into a CNF format (slow)
static int makeFullDNF (std::unique_ptr< Rule > &)
Make Rule into a full DNF format.
static int removeComplementary (std::unique_ptr< Rule > &)
NOT WORKING.
static int removeItem (std::unique_ptr< Rule > &TRule, const int SurfN)
Given an item as a surface name, remove the surface from the Rule tree.
Protected Member Functions
Rule & operator= (const Rule &)
Assignment operator= does not set parent as Rules are cloned.
Rule (const Rule &)
Constructor copies.
Private Member Functions
virtual Rule * doClone () const =0
abstract clone object
int getBaseKeys (std::vector< int > &) const
Fills the vector with the surfaces.
Static Private Member Functions
static int addToKey (std::vector< int > &AV, const int passN=-1)
Static function :: Given a vector AV increase the number from lowest to highest in an iterative counting chain.
Private Attributes
Rule * Parent
Parent object (for tree)
Detailed Description
Object generation rule tree.
Author
S.Ansell
Version
1.0
Date
April 2005
Base class for a rule item in the tree.
Definition at line 33 of file Rules.h.
Constructor & Destructor Documentation
Rule() [1/3]
Mantid::Geometry::Rule::Rule (const Rule &) protected
Constructor copies.
Parent set to 0
Definition at line 429 of file Rules.cpp.
Rule() [2/3]
Mantid::Geometry::Rule::Rule ()
Standard Constructor.
Definition at line 422 of file Rules.cpp.
Rule() [3/3]
Mantid::Geometry::Rule::Rule (Rule * A)
Constructor copies.
Parent set to A
Parameters
A :: Parent value
Definition at line 437 of file Rules.cpp.
~Rule()
virtual Mantid::Geometry::Rule::~Rule () virtual default
Member Function Documentation
addToKey()
int Mantid::Geometry::Rule::addToKey (std::vector< int > & AV, const int passN = -1) static private
Static function :: Given a vector AV increase the number from lowest to highest in an iterative counting chain.
(effectively an N-bit binary number++)
Parameters
AV :: vector of the N-bit array
passN :: number that is to be skipped
Return values
bit number that was set from 0 to 1
-1 if the a carry flag is set
Definition at line 35 of file Rules.cpp.
Referenced by Eliminate().
checkParents()
int Mantid::Geometry::Rule::checkParents () const
Debug test for parents.
This code checks if a parent tree is valid.
Return values
0 on failure
1 on success
Definition at line 500 of file Rules.cpp.
References getParent(), and leaf().
className()
virtual std::string Mantid::Geometry::Rule::className () const inline virtual
Returns class name as string.
Reimplemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Definition at line 56 of file Rules.h.
clone()
std::unique_ptr< Rule > Mantid::Geometry::Rule::clone () const inline
Definition at line 54 of file Rules.h.
Referenced by makeCNF(), makeCNFcopy(), and removeItem().
commonType()
int Mantid::Geometry::Rule::commonType () const
Gets a common type.
Function to return the common type of an rule.
Return values
1 :: every rule is an intersection or component
-1 :: every rule is an union or component
0 :: mixed rule group or only component
Definition at line 527 of file Rules.cpp.
References leaf(), and type().
Referenced by removeComplementary().
display()
virtual std::string Mantid::Geometry::Rule::display () const pure virtual
Abstract Display.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Referenced by Mantid::Geometry::CSGObject::cellStr().
displayAddress()
virtual std::string Mantid::Geometry::Rule::displayAddress () const pure virtual
Abstract Display Address.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
doClone()
virtual Rule * Mantid::Geometry::Rule::doClone () const private pure virtual
abstract clone object
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Eliminate()
int Mantid::Geometry::Rule::Eliminate ()
elimination not written
This rule eliminates any unnecessary rules.
Todo:
Currently does not work since removeItem changes the top rule (so should this)
Returns
number of items eliminated
Definition at line 619 of file Rules.cpp.
References addToKey(), getKeyList(), and isValid().
findKey()
virtual Rule * Mantid::Geometry::Rule::findKey (const int) pure virtual
Abstract key find.
Implemented in Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, and Mantid::Geometry::BoolValue.
Referenced by Mantid::Geometry::Intersection::findKey(), Mantid::Geometry::Union::findKey(), removeItem(), and substituteSurf().
findLeaf()
virtual int Mantid::Geometry::Rule::findLeaf (const Rule *) const pure virtual
Abstract find.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Referenced by makeCNF(), Mantid::Geometry::CSGObject::procComp(), and removeComplementary().
getBaseKeys()
int Mantid::Geometry::Rule::getBaseKeys (std::vector< int > &) const private
Fills the vector with the surfaces.
getBoundingBox()
virtual void Mantid::Geometry::Rule::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) pure virtual
Abstract getBoundingBox.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
getKeyList()
int Mantid::Geometry::Rule::getKeyList (std::vector< int > & IList) const
Generate the key list given an insertion type object.
The list is a unique list.
Parameters
IList :: place to put keyList
Returns
number of object inserted
Definition at line 582 of file Rules.cpp.
References leaf().
Referenced by Eliminate().
getParent()
Rule * Mantid::Geometry::Rule::getParent () const
Returns the parent object.
Returns
Parent
Definition at line 467 of file Rules.cpp.
References Parent.
Referenced by checkParents(), makeCNF(), Mantid::Geometry::CSGObject::procComp(), removeComplementary(), and removeItem().
isComplementary()
virtual int Mantid::Geometry::Rule::isComplementary () const inline virtual
Always returns false (0)
Reimplemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::CompObj, and Mantid::Geometry::CompGrp.
Definition at line 82 of file Rules.h.
isValid() [1/2]
virtual bool Mantid::Geometry::Rule::isValid (const Kernel::V3D &) const pure virtual
Abstract: The point is within the object.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Referenced by Eliminate(), and Mantid::Geometry::CompGrp::isValid().
isValid() [2/2]
virtual bool Mantid::Geometry::Rule::isValid (const std::map< int, int > &) const pure virtual
Abstract Validity based on surface true/false map.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
leaf()
virtual Rule * Mantid::Geometry::Rule::leaf (const int = 0) const inline virtual
No leaf for a base rule.
Reimplemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::CompGrp, Mantid::Geometry::SurfPoint, and Mantid::Geometry::BoolValue.
Definition at line 59 of file Rules.h.
Referenced by checkParents(), commonType(), Mantid::Geometry::CSGObject::createSurfaceList(), getKeyList(), makeCNF(), makeCNFcopy(), makeParents(), Mantid::Geometry::CSGObject::populate(), Mantid::Geometry::CSGObject::print(), removeComplementary(), and removeItem().
makeCNF()
int Mantid::Geometry::Rule::makeCNF (std::unique_ptr< Rule > & TopRule) static
Make Rule into a CNF format.
Static Function::
Function to make the tree into CNF (conditional normal form)
Parameters
TopRule :: Rule to simplify.
We do not use *this :: The reason is that we need to change the toprule type e.g. from an intersection to a union. Since the type of a class can't be changed it is necessary to have a static function, so that the place that TopRule points is changable
Return values
0 on failure
1 on success
Definition at line 264 of file Rules.cpp.
References clone(), count, findLeaf(), getParent(), leaf(), setLeaf(), and type().
makeCNFcopy()
int Mantid::Geometry::Rule::makeCNFcopy (std::unique_ptr< Rule > & TopRule) static
Make Rule into a CNF format (slow)
Static Function::
Function to make the tree into CNF (conditional normal form)
Parameters
TopRule :: Rule to simplify.
We do not use *this :: The reason is that we need to change the toprule type eg from an intersection to a union. Since the type of a class can't be changed it is necessary to have a static function, so that the place that TopRule points is changable
Returns
number of changes
Definition at line 135 of file Rules.cpp.
References clone(), count, Mantid::DTriple< F, S, T >::first, leaf(), Mantid::DTriple< F, S, T >::second, Mantid::DTriple< F, S, T >::third, and type().
makeFullDNF()
static int Mantid::Geometry::Rule::makeFullDNF (std::unique_ptr< Rule > &) static
Make Rule into a full DNF format.
makeParents()
void Mantid::Geometry::Rule::makeParents ()
This is initialisation code that populates all the parents in the rule tree.
Definition at line 476 of file Rules.cpp.
References leaf(), and setParent().
operator=()
Rule & Mantid::Geometry::Rule::operator= (const Rule &) protected
Assignment operator= does not set parent as Rules are cloned.
Returns
*this
Definition at line 447 of file Rules.cpp.
Referenced by Mantid::Geometry::BoolValue::operator=(), Mantid::Geometry::CompGrp::operator=(), Mantid::Geometry::Intersection::operator=(), and Mantid::Geometry::Union::operator=().
removeComplementary()
int Mantid::Geometry::Rule::removeComplementary (std::unique_ptr< Rule > & TopRule) static
NOT WORKING.
Given a rule tree remove any parts that are (-A B C D A) -> (B C D) and (A B C D A) -> (A B C D) Code is borrowed from makeCNF.
See comments within that for a better howto. Currently it passes the line down
Return values
1 :: some simplification
0 :: no simplification
Definition at line 58 of file Rules.cpp.
References commonType(), findLeaf(), Mantid::DTriple< F, S, T >::first, getParent(), leaf(), setLeaf(), simplify(), and Mantid::DTriple< F, S, T >::third.
removeItem()
int Mantid::Geometry::Rule::removeItem (std::unique_ptr< Rule > & TRule, const int SurfN) static
Given an item as a surface name, remove the surface from the Rule tree.
If the found leaf is on a
Parameters
TRule :: Top rule to down search
SurfN :: Surface key number to remove
Returns
Number of instances removed
Not the top level
New Top rule
Definition at line 376 of file Rules.cpp.
References clone(), findKey(), getParent(), leaf(), setLeaf(), and setParent().
Referenced by Mantid::Geometry::CSGObject::removeSurface().
setLeaf()
virtual void Mantid::Geometry::Rule::setLeaf (std::unique_ptr< Rule > , const int = 0) pure virtual
Abstract set.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::CompGrp, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, and Mantid::Geometry::BoolValue.
Referenced by makeCNF(), Mantid::Geometry::CSGObject::procComp(), removeComplementary(), and removeItem().
setLeaves()
virtual void Mantid::Geometry::Rule::setLeaves (std::unique_ptr< Rule > , std::unique_ptr< Rule >) pure virtual
abstract set leaves
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
setParent()
void Mantid::Geometry::Rule::setParent (Rule * A)
Sets the parent object (not check for A==this)
Parameters
A :: Partent Object Ptr
Definition at line 458 of file Rules.cpp.
References Parent.
Referenced by Mantid::Geometry::CompGrp::CompGrp(), Mantid::Geometry::Intersection::Intersection(), Mantid::Geometry::Intersection::Intersection(), makeParents(), removeItem(), Mantid::Geometry::Union::Union(), and Mantid::Geometry::Union::Union().
simplify()
virtual int Mantid::Geometry::Rule::simplify () pure virtual
Abstract: Can the rule be simplified.
Implemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Referenced by removeComplementary().
substituteSurf()
int Mantid::Geometry::Rule::substituteSurf (const int SurfN, const int newSurfN, const std::shared_ptr< Surface > & SPtr)
Substitues a surface item if within a rule.
Parameters
SurfN :: Number number to change
newSurfN :: New surface number (if -ve then the key is reversed)
SPtr :: New surface Pointer
Returns
number of substitutions
Definition at line 561 of file Rules.cpp.
References findKey(), and Mantid::Geometry::SurfPoint::setKeyN().
type()
virtual int Mantid::Geometry::Rule::type () const inline virtual
Null rule.
Reimplemented in Mantid::Geometry::Intersection, Mantid::Geometry::Union, Mantid::Geometry::SurfPoint, Mantid::Geometry::CompObj, Mantid::Geometry::CompGrp, and Mantid::Geometry::BoolValue.
Definition at line 73 of file Rules.h.
Referenced by commonType(), makeCNF(), and makeCNFcopy().
Member Data Documentation
Parent
Rule* Mantid::Geometry::Rule::Parent private
Parent object (for tree)
Definition at line 35 of file Rules.h.
Referenced by getParent(), and setParent().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Objects/Rules.h
Framework/Geometry/src/Objects/Rules.cpp