Mantid: Mantid::Kernel::IPropertyManager Class Reference
Mantid::Kernel::IPropertyManager Class Reference abstract
Interface to PropertyManager.
#include <Kernel/IPropertyManager.h>
Classes
struct TypedValue
Utility class that enables the getProperty() method to effectively be templated on the return type.
Public Member Functions
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Protected Member Functions
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Private Member Functions
template<typename T >
IPropertyManager * doSetProperty (const std::string &name, const std::shared_ptr< T > &value)
Helper method to set the value of a PropertyWithValue, variant for shared_ptr types.
template<typename T >
IPropertyManager * doSetProperty (const std::string &name, const T &value)
Helper method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setTypedProperty (const std::string &name, const T &value, const std::false_type &)
Set a property value that is not convertible to a DataItem_sptr.
template<typename T >
IPropertyManager * setTypedProperty (const std::string &name, const T &value, const std::true_type &)
Set a property value that is convertible to a DataItem_sptr.
template<typename T >
IPropertyManager * setTypedProperty (const std::string &name, std::unique_ptr< T > value, const std::true_type &)
Set a property value from std::unique_ptr that is convertible to a DataItem_sptr.
Detailed Description
Interface to PropertyManager.
Author
Russell Taylor, Tessella Support Services plc
Based on the Gaudi class PropertyMgr (see http://proj-gaudi.web.cern.ch/proj-gaudi/)
Date
20/11/2007
Author
Roman Tolchenov, Tessella plc
Date
02/03/2009
Definition at line 59 of file IPropertyManager.h.
Constructor & Destructor Documentation
~IPropertyManager()
virtual Mantid::Kernel::IPropertyManager::~IPropertyManager () virtual default
Member Function Documentation
afterPropertySet()
virtual void Mantid::Kernel::IPropertyManager::afterPropertySet (const std::string &) inline protected virtual
Override this method to perform a custom action right after a property was set.
The argument is the property name. Default - do nothing.
Reimplemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManagerOwner, Mantid::Geometry::BraggScattererInCrystalStructure, Mantid::Geometry::CompositeBraggScatterer, and Mantid::CurveFitting::IFittingAlgorithm.
Definition at line 370 of file IPropertyManager.h.
Referenced by Mantid::Kernel::PropertyManager::setPropertyOrdinal(), Mantid::Kernel::PropertyManager::setPropertyValue(), and Mantid::Kernel::PropertyManager::setPropertyValueFromJson().
asJson()
virtual ::Json::Value Mantid::Kernel::IPropertyManager::asJson (bool withDefaultValues = false) const pure virtual
Return the property manager serialized as a json object.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
asString()
virtual std::string Mantid::Kernel::IPropertyManager::asString (bool withDefaultValues = false) const pure virtual
Return the property manager serialized as a string.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
clear()
virtual void Mantid::Kernel::IPropertyManager::clear () protected pure virtual
Clears all properties under management.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManagerOwner, and Mantid::Kernel::PropertyManager.
declareOrReplaceProperty()
virtual void Mantid::Kernel::IPropertyManager::declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string & doc = "") pure virtual
Function to declare properties (i.e. store them)
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by Mantid::Kernel::PropertyManager::setProperties().
declareProperty() [1/7]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const std::string & doc, IValidator_sptr validator = std::make_shared<NullValidator>(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The (optional) documentation string
validator :: Pointer to the (optional) validator. Ownership will be taken over.
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 166 of file IPropertyManager.h.
References name, and value.
declareProperty() [2/7]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, const unsigned int direction) inline
Add a property of string type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 183 of file IPropertyManager.h.
References name, and value.
declareProperty() [3/7]
void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, const char * value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = std::string(), const unsigned int direction = Direction::Input) inline
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
The validator, if provided, needs to be a string validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator. Ownership will be taken over.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
std::invalid_argument if value is a nullptr
Definition at line 137 of file IPropertyManager.h.
References name, and value.
declareProperty() [4/7]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const std::string & doc, const unsigned int direction = Direction::Input) inline
Add a property to the list of managed properties with no validator.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
doc :: The documentation string
direction :: The (optional) direction of the property, in (default), out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 98 of file IPropertyManager.h.
References name, and value.
declareProperty() [5/7]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, const unsigned int direction) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
direction :: The direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 113 of file IPropertyManager.h.
References name, and value.
declareProperty() [6/7]
template<typename T > void Mantid::Kernel::IPropertyManager::declareProperty (const std::string & name, T value, IValidator_sptr validator = std::make_shared<NullValidator>(), const std::string & doc = "", const unsigned int direction = Direction::Input) inline
Add a property of the template type to the list of managed properties.
Parameters
name :: The name to assign to the property
value :: The initial value to assign to the property
validator :: Pointer to the (optional) validator.
doc :: The (optional) documentation string
direction :: The (optional) direction of the property, in, out or inout
Exceptions
Exception::ExistsError if a property with the given name already exists
std::invalid_argument if the name argument is empty
Definition at line 81 of file IPropertyManager.h.
References name, and value.
declareProperty() [7/7]
virtual void Mantid::Kernel::IPropertyManager::declareProperty (std::unique_ptr< Property > p, const std::string & doc = "") pure virtual
Function to declare properties (i.e. store them)
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, Mantid::Kernel::PropertyManagerOwner, Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by Mantid::Crystal::ModulationProperties::appendTo(), and Mantid::API::IDomainCreator::declareProperty().
doSetProperty() [1/2]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::doSetProperty (const std::string & name, const std::shared_ptr< T > & value) inline private
Helper method to set the value of a PropertyWithValue, variant for shared_ptr types.
This variant is required to enforce checks for complete types, do not remove it.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 455 of file IPropertyManager.h.
References name, and value.
doSetProperty() [2/2]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::doSetProperty (const std::string & name, const T & value) inline private
Helper method to set the value of a PropertyWithValue.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 440 of file IPropertyManager.h.
References name, and value.
existsProperty()
virtual bool Mantid::Kernel::IPropertyManager::existsProperty (const std::string & name) const pure virtual
Checks whether the named property is already in the list of managed property.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by MantidQt::MantidWidgets::FitOptionsBrowser::copyPropertiesToAlgorithm(), Mantid::CurveFitting::FitMW::declareDatasetProperties(), Mantid::CurveFitting::IMWDomainCreator::declareDatasetProperties(), Mantid::CurveFitting::TableWorkspaceDomainCreator::declareDatasetProperties(), Mantid::MDAlgorithms::FitMD::declareDatasetProperties(), export_IPropertyManager(), MantidQt::MantidWidgets::FitPropertyBrowser::finishHandle(), Mantid::CurveFitting::GeneralDomainCreator::getInputWorkspace(), and Mantid::API::IDomainCreator::initFunction().
filterByProperty()
virtual void Mantid::Kernel::IPropertyManager::filterByProperty (Mantid::Kernel::LogFilter * , const std::vector< std::string > &) inline virtual
Reimplemented in Mantid::Kernel::PropertyManager.
Definition at line 344 of file IPropertyManager.h.
getDeclaredPropertyNames()
virtual std::vector< std::string > Mantid::Kernel::IPropertyManager::getDeclaredPropertyNames () const pure virtual noexcept
Get the list of managed property names.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by MantidQt::MantidWidgets::convertAlgPropsToString().
getPointerToProperty()
virtual Property * Mantid::Kernel::IPropertyManager::getPointerToProperty (const std::string & name) const pure virtual
Get a pointer to property by name.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by Mantid::Kernel::SetDefaultWhenProperty::applyChanges(), Mantid::Kernel::SetValueWhenProperty::applyChanges(), Mantid::Algorithms::MonIDPropChanger::applyChanges(), Mantid::Kernel::EnabledWhenProperty::checkCriterion(), Mantid::API::EnabledWhenWorkspaceIsType< T >::checkCriterion(), MockAlgorithm::expectGetProperty(), export_IPropertyManager(), Mantid::Kernel::EnabledWhenProperty::getPropertyValue(), getValue(), and Mantid::Kernel::SetValueWhenProperty::isConditionChanged().
getPointerToPropertyOrdinal()
virtual Property * Mantid::Kernel::IPropertyManager::getPointerToPropertyOrdinal (const int & index) const protected pure virtual
Get a property by an index.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
getProperties()
virtual const std::vector< Property * > & Mantid::Kernel::IPropertyManager::getProperties () const pure virtual
Get the list of managed properties.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by Mantid::API::MultiPeriodGroupWorker::copyInputWorkspaceProperties(), and export_IPropertyManager().
getPropertiesInGroup()
std::vector< Property * > Mantid::Kernel::IPropertyManager::getPropertiesInGroup (const std::string & group) const
Get the list of managed properties in a given group.
getProperty()
virtual TypedValue Mantid::Kernel::IPropertyManager::getProperty (const std::string & name) const pure virtual
Get the value of a property.
Implemented in Mantid::API::Algorithm, Mantid::API::AlgorithmRuntimeProps, Mantid::Kernel::PropertyManager, Mantid::Kernel::PropertyManagerOwner, and Mantid::API::IAlgorithmRuntimeProps.
Referenced by Mantid::Algorithms::MonIDPropChanger::applyChanges(), Mantid::Crystal::ModulationProperties::create(), MockAlgorithm::expectGetProperty(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterSimultaneousFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterTFSimultaneousFit(), MantidQt::MantidWidgets::FitPropertyBrowser::finishHandle(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandleNormal(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandleTF(), Mantid::CurveFitting::GeneralDomainCreator::getInputWorkspace(), Mantid::API::IDomainCreator::initFunction(), Mantid::Algorithms::MonIDPropChanger::isConditionChanged(), Mantid::Algorithms::MonIDPropChanger::isEnabled(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::CurveFitting::Algorithms::setMultiDataProperties(), Mantid::CurveFitting::IMWDomainCreator::setParameters(), Mantid::CurveFitting::TableWorkspaceDomainCreator::setParameters(), Mantid::MDAlgorithms::FitMD::setParameters(), Mantid::CurveFitting::FitMW::setParameters(), Mantid::CurveFitting::SeqDomainSpectrumCreator::setParametersFromPropertyManager(), Mantid::CurveFitting::LatticeDomainCreator::setWorkspaceFromPropertyManager(), and Mantid::CurveFitting::TableWorkspaceDomainCreator::setXYEColumnNames().
getPropertyValue()
virtual std::string Mantid::Kernel::IPropertyManager::getPropertyValue (const std::string & name) const pure virtual
Get the value of a property as a string.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by MantidQt::MantidWidgets::convertAlgPropsToString(), Mantid::CurveFitting::GeneralDomainCreator::createDomain(), Mantid::CurveFitting::GeneralDomainCreator::createOutputWorkspace(), export_IPropertyManager(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterSimultaneousFit(), MantidQt::MantidWidgets::FitPropertyBrowser::finishHandle(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishHandleTF().
getValue() [1/3]
template<typename T > T Mantid::Kernel::IPropertyManager::getValue (const std::string & name) const protected
Templated method to get the value of a property.
No generic definition, only specialised ones. Although the definitions are mostly the same, Visual Studio can't cope with
Parameters
name :: The name of the property (case insensitive)
Returns
The value of the property
Exceptions
std::runtime_error If an attempt is made to assign a property to a different type
Exception::NotFoundError If the property requested does not exist
Referenced by Mantid::Kernel::IPropertyManager::TypedValue::operator Matrix< T >(), Mantid::Kernel::IPropertyManager::TypedValue::operator std::shared_ptr< const T >(), Mantid::Kernel::IPropertyManager::TypedValue::operator std::shared_ptr< T >(), Mantid::Kernel::IPropertyManager::TypedValue::operator std::vector< std::vector< T > >(), and Mantid::Kernel::IPropertyManager::TypedValue::operator std::vector< T >().
getValue() [2/3]
template<> MANTID_KERNEL_DLL PropertyManager_sptr Mantid::Kernel::IPropertyManager::getValue (const std::string & name) const protected
Definition at line 136 of file PropertyManagerProperty.cpp.
References getPointerToProperty(), and name.
getValue() [3/3]
template<> MANTID_KERNEL_DLL PropertyManager_const_sptr Mantid::Kernel::IPropertyManager::getValue (const std::string & name) const protected
Definition at line 147 of file PropertyManagerProperty.cpp.
References getPointerToProperty(), and name.
isPropertyEnabled()
bool Mantid::Kernel::IPropertyManager::isPropertyEnabled (const std::string & name) const
Test if a given property should be enabled.
Referenced by Mantid::Kernel::PropertyManager::asJson(), and export_IPropertyManager().
isPropertyVisible()
bool Mantid::Kernel::IPropertyManager::isPropertyVisible (const std::string & name) const
Test if a given property should be visible.
Referenced by export_IPropertyManager().
propertyCount()
virtual size_t Mantid::Kernel::IPropertyManager::propertyCount () const pure virtual
Returns the number of properties under management.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by export_IPropertyManager().
removeProperty()
virtual void Mantid::Kernel::IPropertyManager::removeProperty (const std::string & name, const bool delproperty = true) pure virtual
Removes the property from management.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
resetProperties()
virtual void Mantid::Kernel::IPropertyManager::resetProperties () pure virtual
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
setProperties() [1/2]
virtual void Mantid::Kernel::IPropertyManager::setProperties (const ::Json::Value & jsonValue, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set< std::string >(), bool createMissing = false) pure virtual
Sets all the properties from a json object.
Parameters
jsonValue :: A json name value pair collection
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
setProperties() [2/2]
virtual void Mantid::Kernel::IPropertyManager::setProperties (const std::string & propertiesJson, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set< std::string >(), bool createMissing = false) pure virtual
Sets all properties from a string.
Parameters
propertiesJson :: A string of name = value pairs formatted as a json name value pair collection
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
createMissing :: If the property does not exist then create it
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
setPropertiesWithString()
virtual void Mantid::Kernel::IPropertyManager::setPropertiesWithString (const std::string & propertiesString, const std::unordered_set< std::string > & ignoreProperties = std::unordered_set< std::string >()) pure virtual
Sets all the declared properties from a string.
Parameters
propertiesString :: A list of name = value pairs separated by a semicolon
ignoreProperties :: A set of names of any properties NOT to set from the propertiesArray
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
setProperty() [1/4]
IPropertyManager * Mantid::Kernel::IPropertyManager::setProperty (const std::string & name, const char * value) inline
Specialised version of setProperty template method to handle const char *.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property
std::invalid_argument If value is a nullptr of different type
Definition at line 296 of file IPropertyManager.h.
References name, and value.
setProperty() [2/4]
IPropertyManager * Mantid::Kernel::IPropertyManager::setProperty (const std::string & name, const std::string & value) inline
Specialised version of setProperty template method to handle std::string.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 309 of file IPropertyManager.h.
References name, and value.
setProperty() [3/4]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::setProperty (const std::string & name, const T & value) inline
Templated method to set the value of a PropertyWithValue.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 270 of file IPropertyManager.h.
References name, and value.
Referenced by Mantid::DataHandling::LoadCanSAS1D::appendDataToOutput(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Algorithms::PolarizerEfficiency::calculatePolarizerEfficiency(), Mantid::Algorithms::DepolarizedAnalyserTransmission::calcWavelengthDependentTransmission(), Mantid::Algorithms::PointByPointVCorrection::check_validity(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::API::MultiPeriodGroupWorker::copyInputWorkspaceProperties(), Mantid::Algorithms::SumEventsByLogValue::createBinnedOutput(), Mantid::DataHandling::LoadNGEM::createCountWorkspace(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), Mantid::DataHandling::SetSample::createFlatPlateHolderXML(), Mantid::DataHandling::GenerateGroupingPowder::createGroups(), Mantid::MDAlgorithms::FitMD::createHistoOutputWorkspace(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::CurveFitting::Algorithms::DoublePulseFit::createOutput(), Mantid::Algorithms::Transpose::createOutputWorkspace(), Mantid::CurveFitting::IMWDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::LatticeDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::MultiDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::TableWorkspaceDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::GeneralDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::SeqDomainSpectrumCreator::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::createResultsTable(), Mantid::Algorithms::SumEventsByLogValue::createTableOutput(), Mantid::Algorithms::RemoveBins::crop(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::Algorithms::DetectorEfficiencyVariation::doDetectorTests(), Mantid::DataHandling::LoadFITS::doLoadFiles(), Mantid::Crystal::StatisticsOfPeaksWorkspace::doSortHKL(), Mantid::Algorithms::AbsorptionCorrection::exec(), Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AnnularRingAbsorption::exec(), Mantid::Algorithms::AppendSpectra::exec(), Mantid::Algorithms::ApplyDetailedBalance::exec(), Mantid::Algorithms::ApplyFloodWorkspace::exec(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::Bin2DPowderDiffraction::exec(), Mantid::Algorithms::BinaryOperateMasks::exec(), Mantid::Algorithms::BinaryOperation::exec(), Mantid::Algorithms::CalculateDIFC::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateEfficiency2::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CalculateIqt::exec(), Mantid::Algorithms::CalculatePlaczek::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering::exec(), Mantid::Algorithms::CalculatePlaczekSelfScattering2::exec(), Mantid::Algorithms::CalculatePolynomialBackground::exec(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::CalculateZscore::exec(), Mantid::Algorithms::ChangeBinOffset::exec(), Mantid::Algorithms::ChangeLogTime::exec(), Mantid::Algorithms::ChangePulsetime::exec(), Mantid::Algorithms::ChangePulsetime2::exec(), Mantid::Algorithms::ChangeTimeZero::exec(), Mantid::Algorithms::ChopData::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::CombineDiffCal::exec(), Mantid::Algorithms::CombineTableWorkspaces::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::ConjoinWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::ConvertDiffCal::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::ConvertSpectrumAxis2::exec(), Mantid::Algorithms::ConvertTableToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertToConstantL2::exec(), Mantid::Algorithms::ConvertToEventWorkspace::exec(), Mantid::Algorithms::ConvertToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CopyDataRange::exec(), Mantid::Algorithms::CopyDetectorMapping::exec(), Mantid::Algorithms::CopyLogs::exec(), Mantid::Algorithms::CopySample::exec(), Mantid::Algorithms::CorelliCalibrationApply::exec(), Mantid::Algorithms::CorelliCalibrationDatabase::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CorrectToFile::exec(), Mantid::Algorithms::CreateBootstrapWorkspaces::exec(), Mantid::Algorithms::CreateEPP::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::CreateFloodWorkspace::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogPropertyTable::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreateMonteCarloWorkspace::exec(), Mantid::Algorithms::CreatePeaksWorkspace::exec(), Mantid::Algorithms::CreatePSDBleedMask::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateSingleValuedWorkspace::exec(), Mantid::Algorithms::CreateUserDefinedBackground::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::CropWorkspace::exec(), Mantid::Algorithms::CropWorkspaceRagged::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DetectorDiagnostic::exec(), Mantid::Algorithms::DetectorEfficiencyCor::exec(), Mantid::Algorithms::DetectorEfficiencyCorUser::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::DirectILLTubeBackground::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::EstimateResolutionDiffraction::exec(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::exec(), Mantid::Algorithms::ExportTimeSeriesLog::exec(), Mantid::Algorithms::ExtractFFTSpectrum::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::ExtractSpectra::exec(), Mantid::Algorithms::ExtractSpectra2::exec(), Mantid::Algorithms::ExtractUnmaskedSpectra::exec(), Mantid::Algorithms::FFT::exec(), Mantid::Algorithms::FFTSmooth::exec(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FilterByLogValue::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::FilterByXValue::exec(), Mantid::Algorithms::FilterEvents::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::FindEPP::exec(), Mantid::Algorithms::FindPeakBackground::exec(), Mantid::Algorithms::FindPeaks::exec(), Mantid::Algorithms::GeneralisedSecondDifference::exec(), Mantid::Algorithms::GenerateEventsFilter::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GeneratePeaks::exec(), Mantid::Algorithms::GeneratePythonFitScript::exec(), Mantid::Algorithms::GetAllEi::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::GetEi::exec(), Mantid::Algorithms::GetEi2::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::GetQsInQENSData::exec(), Mantid::Algorithms::GetTimeSeriesLogInformation::exec(), Mantid::Algorithms::GroupToXResolution::exec(), Mantid::Algorithms::GroupWorkspaces::exec(), Mantid::Algorithms::He3TubeEfficiency::exec(), Mantid::Algorithms::HRPDSlabCanAbsorption::exec(), Mantid::Algorithms::HyspecScharpfCorrection::exec(), Mantid::Algorithms::IdentifyNoisyDetectors::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::IntegrateEPP::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::InterpolatingRebin::exec(), Mantid::Algorithms::InvertMask::exec(), Mantid::Algorithms::IQTransform::exec(), Mantid::Algorithms::LineProfile::exec(), Mantid::Algorithms::LorentzCorrection::exec(), Mantid::Algorithms::MagFormFactorCorrection::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskBinsFromWorkspace::exec(), Mantid::Algorithms::MaskBinsIf::exec(), Mantid::Algorithms::MaskInstrument::exec(), Mantid::Algorithms::MaskNonOverlappingBins::exec(), Mantid::Algorithms::Max::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::MedianDetectorTest::exec(), Mantid::Algorithms::MergeLogs::exec(), Mantid::Algorithms::Min::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::MonitorEfficiencyCorUser::exec(), Mantid::Algorithms::MonteCarloAbsorption::exec(), Mantid::Algorithms::MostLikelyMean::exec(), Mantid::Algorithms::MultipleScatteringCorrection::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::NormaliseByCurrent::exec(), Mantid::Algorithms::NormaliseByDetector::exec(), Mantid::Algorithms::NormaliseToMonitor::exec(), Mantid::Algorithms::NormaliseToUnity::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::PaddingAndApodization::exec(), Mantid::Algorithms::ParallaxCorrection::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::PolarizationCorrectionFredrikze::exec(), Mantid::Algorithms::FlipperEfficiency::exec(), Mantid::Algorithms::HeliumAnalyserEfficiencyTime::exec(), Mantid::Algorithms::PolarizationCorrectionWildes::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::ReadGroupsFromFile::exec(), Mantid::Algorithms::RealFFT::RealFFT::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::Rebin2D::exec(), Mantid::Algorithms::RebinByTimeBase::exec(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::RebinToWorkspace::exec(), Mantid::Algorithms::Rebunch::exec(), Mantid::Algorithms::Regroup::exec(), Mantid::Algorithms::RemoveBackground::exec(), Mantid::Algorithms::RemoveBins::exec(), Mantid::Algorithms::RemoveInstrumentGeometry::exec(), Mantid::Algorithms::RemoveLowResTOF::exec(), Mantid::Algorithms::RemoveMaskedSpectra::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::RenameWorkspace::exec(), Mantid::Algorithms::RenameWorkspaces::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::ResetNegatives::exec(), Mantid::Algorithms::RingProfile::exec(), Mantid::Algorithms::MayersSampleCorrection::exec(), Mantid::Algorithms::Scale::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Algorithms::SetUncertainties::exec(), Mantid::Algorithms::ShiftLogTime::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::Algorithms::SofQWPolygon::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::SortXAxis::exec(), Mantid::Algorithms::SphericalAbsorption::exec(), Mantid::Algorithms::Stitch::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Algorithms::StripPeaks::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumNeighbours::exec(), Mantid::Algorithms::SumOverlappingTubes::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Algorithms::UnaryOperation::exec(), Mantid::Algorithms::UnwrapMonitor::exec(), Mantid::Algorithms::UnwrapMonitorsInTOF::exec(), Mantid::Algorithms::UnwrapSNS::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::Algorithms::WeightedMeanOfWorkspace::exec(), Mantid::Algorithms::WienerSmooth::exec(), Mantid::Algorithms::XDataConverter::exec(), Mantid::Algorithms::XrayAbsorptionCorrection::exec(), Mantid::Crystal::AnvredCorrection::exec(), Mantid::Crystal::CalculatePeaksHKL::exec(), Mantid::Crystal::ClearUB::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::ConvertPeaksWorkspace::exec(), Mantid::Crystal::CountReflections::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::Crystal::FilterPeaks::exec(), Mantid::Crystal::FindClusterFaces::exec(), Mantid::Crystal::FindGoniometerAngles::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::HasUB::exec(), Mantid::Crystal::IndexPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::LoadIsawPeaks::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::Crystal::NormaliseVanadium::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::Crystal::PredictFractionalPeaks::exec(), Mantid::Crystal::PredictSatellitePeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SelectCellOfType::exec(), Mantid::Crystal::SelectCellWithForm::exec(), Mantid::Crystal::SetCrystalLocation::exec(), Mantid::Crystal::SetUB::exec(), Mantid::Crystal::ShowPeakHKLOffsets::exec(), Mantid::Crystal::ShowPossibleCells::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::Crystal::SortPeaksWorkspace::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::exec(), Mantid::CurveFitting::Algorithms::ConvolveWorkspaces::exec(), Mantid::CurveFitting::CrystalFieldEnergies::exec(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), Mantid::CurveFitting::Algorithms::LeBailFit::exec(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::exec(), Mantid::CurveFitting::Algorithms::SplineBackground::exec(), Mantid::CurveFitting::Algorithms::SplineInterpolation::exec(), Mantid::CurveFitting::Algorithms::SplineSmoothing::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::CompressEvents::exec(), Mantid::DataHandling::CreateChunkingFromInstrument::exec(), Mantid::DataHandling::CreatePolarizationEfficienciesBase::exec(), Mantid::DataHandling::CreateSimulationWorkspace::exec(), Mantid::DataHandling::DeleteTableRows::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadFile::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::ExtractMonitorWorkspace::exec(), Mantid::DataHandling::ExtractPolarizationEfficiencies::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::GroupDetectors2::exec(), Mantid::DataHandling::ISISJournalGetExperimentRuns::exec(), Mantid::DataHandling::Load::exec(), Mantid::DataHandling::LoadAscii::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadCalFile::exec(), Mantid::DataHandling::LoadCanSAS1D::exec(), Mantid::DataHandling::LoadCSNSNexus::exec(), Mantid::DataHandling::LoadDaveGrp::exec(), Mantid::DataHandling::LoadDetectorsGroupingFile::exec(), Mantid::DataHandling::LoadDNSEvent::exec(), Mantid::DataHandling::LoadEmptyInstrument::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadGSS::exec(), Mantid::DataHandling::LoadHFIRSANS::exec(), Mantid::DataHandling::LoadILLDiffraction::exec(), Mantid::DataHandling::LoadILLIndirect2::exec(), Mantid::DataHandling::LoadILLLagrange::exec(), Mantid::DataHandling::LoadILLPolarizationFactors::exec(), Mantid::DataHandling::LoadILLPolarizedDiffraction::exec(), Mantid::DataHandling::LoadILLReflectometry::exec(), Mantid::DataHandling::LoadILLSANS::exec(), Mantid::DataHandling::LoadILLTOF2::exec(), Mantid::DataHandling::LoadILLTOF3::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadIsawDetCal::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMask::exec(), Mantid::DataHandling::LoadMcStasNexus::exec(), Mantid::DataHandling::LoadMLZ::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::LoadNGEM::exec(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadPDFgetNFile::exec(), Mantid::DataHandling::LoadPreNexus::exec(), Mantid::DataHandling::LoadPreNexusMonitors::exec(), Mantid::DataHandling::LoadPSIMuonBin::exec(), Mantid::DataHandling::LoadQKK::exec(), Mantid::DataHandling::LoadRKH::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::DataHandling::LoadSampleShape::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSESANS::exec(), Mantid::DataHandling::LoadSINQFocus::exec(), Mantid::DataHandling::LoadSPE::exec(), Mantid::DataHandling::LoadSpec::exec(), Mantid::DataHandling::LoadSpice2D::exec(), Mantid::DataHandling::LoadSpiceAscii::exec(), Mantid::DataHandling::LoadSpiceXML2DDet::exec(), Mantid::DataHandling::LoadSwans::exec(), Mantid::DataHandling::LoadTBL::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::MaskDetectorsInShape::exec(), Mantid::DataHandling::MaskSpectra::exec(), Mantid::DataHandling::PDLoadCharacterizations::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::SortTableWorkspace::exec(), Mantid::DataHandling::UpdateInstrumentFromFile::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::ICat::CatalogGetDataFiles::exec(), Mantid::ICat::CatalogGetDataSets::exec(), Mantid::ICat::CatalogListInstruments::exec(), Mantid::ICat::CatalogListInvestigationTypes::exec(), Mantid::ICat::CatalogLogin::exec(), Mantid::ICat::CatalogMyDataSearch::exec(), Mantid::ICat::CatalogPublish::exec(), Mantid::ICat::CatalogSearch::exec(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::exec(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::BinaryOperationMD::exec(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::ChangeQConvention::exec(), Mantid::MDAlgorithms::CloneMDWorkspace::exec(), Mantid::MDAlgorithms::CompactMD::exec(), Mantid::MDAlgorithms::CompareMDWorkspaces::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::MDAlgorithms::ConvertHFIRSCDtoMDE::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::exec(), Mantid::MDAlgorithms::CreateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::exec(), Mantid::MDAlgorithms::EvaluateMDFunction::exec(), Mantid::MDAlgorithms::FindPeaksMD::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::exec(), Mantid::MDAlgorithms::ImportMDEventWorkspace::exec(), Mantid::MDAlgorithms::ImportMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::MDAlgorithms::IntegrateFlux::exec(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegratePeaksCWSD::exec(), Mantid::MDAlgorithms::IntegratePeaksMDHKL::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::LoadGaussCube::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MDNormDirectSC::exec(), Mantid::MDAlgorithms::MDNormSCD::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::MDAlgorithms::MergeMDFiles::exec(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::exec(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::exec(), Mantid::MDAlgorithms::QTransform::exec(), Mantid::MDAlgorithms::QueryMDWorkspace::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::MDAlgorithms::ReplicateMD::exec(), Mantid::MDAlgorithms::SaveIsawQvector::exec(), Mantid::MDAlgorithms::SetMDUsingMask::exec(), Mantid::MDAlgorithms::SmoothMD::exec(), Mantid::MDAlgorithms::SpectralMomentMD::exec(), Mantid::MDAlgorithms::ThresholdMD::exec(), Mantid::MDAlgorithms::TransformMD::exec(), Mantid::MDAlgorithms::TransposeMD::exec(), Mantid::MDAlgorithms::UnaryOperationMD::exec(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::DgsRemap::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::HFIRSANSNormalise::exec(), Mantid::Algorithms::ProcessIndirectFitParameters::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::WorkflowAlgorithms::StepScan::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::Algorithms::CropToComponent::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::Crystal::PredictSatellitePeaks::exec_peaks(), Mantid::Algorithms::FFTDerivative::execComplexFFT(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::execConcrete(), Mantid::CurveFitting::Algorithms::CalculateCostFunction::execConcrete(), Mantid::CurveFitting::Algorithms::EstimateFitParameters::execConcrete(), Mantid::CurveFitting::Algorithms::EvaluateFunction::execConcrete(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::execConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::execConcrete(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Algorithms::He3TubeEfficiency::execEvent(), Mantid::Algorithms::HyspecScharpfCorrection::execEvent(), Mantid::Algorithms::MergeRuns::execEvent(), Mantid::Algorithms::ModeratorTzeroLinear::execEvent(), Mantid::Algorithms::ScaleX::execEvent(), Mantid::Algorithms::UnaryOperation::execEvent(), Mantid::Algorithms::UnwrapSNS::execEvent(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::DataHandling::GroupDetectors2::execEvent(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::execEvent(), Mantid::MDAlgorithms::MinusMD::execEvent(), Mantid::MDAlgorithms::PlusMD::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::Algorithms::SmoothNeighbours::execEvent(), Mantid::Algorithms::PolarizationEfficiencyCor::execFredrikze(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::DataHandling::LoadBBY2::execLoader(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::DataHandling::LoadMcStas::execLoader(), Mantid::DataHandling::LoadMuonNexusV2::execLoader(), Mantid::DataHandling::LoadNexusProcessed::execLoader(), Mantid::MDAlgorithms::LoadMD::execLoader(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), Mantid::Crystal::PeaksIntersection::executePeaksIntersection(), Mantid::Algorithms::PolarizationEfficiencyCor::execWildes(), Mantid::Algorithms::SmoothNeighbours::execWorkspace2D(), Mantid::CurveFitting::Algorithms::LeBailFit::exportBraggPeakParameterToTable(), Mantid::CurveFitting::Algorithms::LeBailFit::exportInstrumentParameterToTable(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspaceRaw(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::MDAlgorithms::LoadSQW2::finalize(), Mantid::Algorithms::Q1DWeighted::finalize(), Mantid::DataHandling::Load::findFilenameProperty(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::MDAlgorithms::QueryMDWorkspace::getBoxData(), Mantid::DataHandling::Load::getFileLoader(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset(), Mantid::Algorithms::EQSANSTofStructure::getTofOffset(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::Algorithms::BinaryOperation::handleSpecialDivideMinus(), Mantid::Algorithms::RebinToWorkspace::histogram(), Mantid::Crystal::CentroidPeaks::integrate(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Crystal::CentroidPeaks::integrateEvent(), Mantid::MDAlgorithms::LoadMD::loadHisto(), Mantid::DataHandling::Load::loadMultipleFiles(), Mantid::DataHandling::LoadMuonNexusV2::loadMuonProperties(), Mantid::DataHandling::LoadILLSALSA::loadNexusV1(), Mantid::DataHandling::LoadILLSALSA::loadNexusV2(), Mantid::DataHandling::Load::loadSingleFile(), Mantid::DataHandling::NXcanSAS::LoadNXcanSAS::loadTransmission(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make1DWorkspace(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make2DWorkspace(), Mantid::DataHandling::LoadPSIMuonBin::makeDeadTimeTable(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::DataHandling::SetSample::materialSettingsEnsureLegacyCompatibility(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputChains(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputConvergedChains(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputCostFunctionTable(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputParameterTable(), Mantid::Algorithms::Qhelper::outputParts(), Mantid::Algorithms::FindPeaksConvolve::outputResults(), Mantid::Algorithms::MaskDetectorsIf::outputToWorkspace(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::CurveFitting::Functions::UserFunction1D::prepare(), Mantid::Algorithms::HeliumAnalyserEfficiency::prepareOutputs(), Mantid::API::Algorithm::processGroups(), Mantid::Algorithms::CalculateEfficiency2::processGroups(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::API::MultiPeriodGroupWorker::processGroups(), Mantid::Algorithms::FitPeaks::processOutputs(), Mantid::DataHandling::LoadCanSAS1D2::processTransmission(), Mantid::DataHandling::PDLoadCharacterizations::readFocusInfo(), Mantid::Crystal::LoadIsawUB::readModulatedUB(), Mantid::DataHandling::PDLoadCharacterizations::readVersion0(), Mantid::Algorithms::RebinToWorkspace::rebin(), SANSInstrumentCreationHelper::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadMonitors(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::PythonInterface::Registry::MappingTypeHandler::set(), Mantid::PythonInterface::Registry::TypedPropertyValueHandler< std::shared_ptr< T >, std::enable_if< std::is_base_of< API::Workspace, T >::value >::type >::set(), Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType >::set(), Mantid::PythonInterface::Registry::TypedPropertyValueHandler< ValueType, Enable >::set(), Mantid::PythonInterface::Registry::PythonObjectTypeHandler::set(), Mantid::DataHandling::LoadPSIMuonBin::setDetectorGroupingTable(), Mantid::CurveFitting::Algorithms::setMultiDataProperties(), Mantid::DataHandling::SaveGSS::setOtherProperties(), Mantid::Algorithms::PolarizationEfficienciesWildes::setOutputs(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::DataHandling::LoadNexus::setOutputWorkspace(), Mantid::API::IAlgorithmRuntimeProps::setProperty(), Mantid::Algorithms::CreateDetectorTable::setTableToOutput(), Mantid::Algorithms::FilterEvents::setupDetectorTOFCalibration(), Mantid::CurveFitting::Functions::ProcessBackground::setupDummyOutputWSes(), Mantid::Algorithms::FitPeak::setupOutput(), Mantid::Algorithms::Qxy::setUpOutputWorkspace(), Mantid::Algorithms::RadiusSum::setUpOutputWorkspace(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData(), Mantid::Algorithms::SmoothNeighbours::spreadPixels(), Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace(), Mantid::API::BoxControllerSettingsAlgorithm::takeDefaultsFromInstrument(), Mantid::Algorithms::UnwrapMonitor::unwrapX(), Mantid::Algorithms::Rebin::validateInputs(), and Mantid::DataHandling::LoadEventNexus::validateInputs().
setProperty() [4/4]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::setProperty (const std::string & name, std::unique_ptr< T > value) inline
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 282 of file IPropertyManager.h.
References name, and value.
setPropertyGroup()
void Mantid::Kernel::IPropertyManager::setPropertyGroup (const std::string & name, const std::string & group) inline
Set the group for a given property.
Parameters
name :: property name
group :: Name of the group it belongs to
Definition at line 335 of file IPropertyManager.h.
References group, name, and Mantid::Kernel::Property::setGroup().
Referenced by export_IPropertyManager(), Mantid::Geometry::BraggScatterer::exposePropertyToComposite(), Mantid::Crystal::LoadIsawSpectrum::getInstrument3WaysInit(), Mantid::Algorithms::CalculateCountRate::init(), Mantid::Algorithms::CreateGroupingWorkspace::init(), Mantid::Algorithms::CreateSampleWorkspace::init(), Mantid::Algorithms::DetectorDiagnostic::init(), Mantid::Algorithms::FilterEvents::init(), Mantid::Algorithms::FitPeaks::init(), Mantid::Algorithms::PDCalibration::init(), Mantid::Algorithms::PDFFourierTransform::init(), Mantid::Algorithms::PDFFourierTransform2::init(), Mantid::Algorithms::DepolarizedAnalyserTransmission::init(), Mantid::Algorithms::HeliumAnalyserEfficiency::init(), Mantid::Algorithms::PolarizationEfficienciesWildes::init(), Mantid::Algorithms::RadiusSum::init(), Mantid::Algorithms::SmoothNeighbours::init(), Mantid::Crystal::FilterPeaks::init(), Mantid::Crystal::FindSXPeaks::init(), Mantid::Crystal::OptimizeCrystalPlacement::init(), Mantid::Crystal::PeakIntensityVsRadius::init(), Mantid::Crystal::SCDCalibratePanels::init(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::init(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::init(), Mantid::DataHandling::CreateChunkingFromInstrument::init(), Mantid::DataHandling::LoadBBY::init(), Mantid::DataHandling::LoadBBY2::init(), Mantid::DataHandling::LoadCSNSNexus::init(), Mantid::DataHandling::LoadDiffCal::init(), Mantid::DataHandling::LoadEventNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::LoadPLN::init(), Mantid::DataHandling::LoadSampleEnvironment::init(), Mantid::DataHandling::PatchBBY::init(), Mantid::DataHandling::SetSampleMaterial::init(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::init(), Mantid::MDAlgorithms::BinMD::init(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::init(), Mantid::MDAlgorithms::IntegratePeaksMD2::init(), Mantid::MDAlgorithms::MDNorm::init(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::init(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::init(), Mantid::API::BoxControllerSettingsAlgorithm::initBoxControllerProps(), Mantid::MDAlgorithms::SlicingAlgorithm::initSlicingProps(), and Mantid::Geometry::BraggScatterer::unexposePropertyFromComposite().
setPropertyOrdinal()
virtual void Mantid::Kernel::IPropertyManager::setPropertyOrdinal (const int & index, const std::string & value) pure virtual
Set the value of a property by an index.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
setPropertySettings()
void Mantid::Kernel::IPropertyManager::setPropertySettings (const std::string & name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
Referenced by Mantid::Algorithms::AddAbsorptionWeightedPathLengths::init(), Mantid::Algorithms::CalculateFlatBackground::init(), Mantid::Algorithms::CopySample::init(), Mantid::Algorithms::DetectorDiagnostic::init(), Mantid::Algorithms::FFT::init(), Mantid::Algorithms::FilterEvents::init(), Mantid::Algorithms::GenerateEventsFilter::init(), Mantid::Algorithms::GetAllEi::init(), Mantid::Algorithms::GetEiMonDet3::init(), Mantid::Algorithms::NormaliseToMonitor::init(), Mantid::Algorithms::PDFFourierTransform2::init(), Mantid::Algorithms::PolarizationEfficienciesWildes::init(), Mantid::Algorithms::PolarizationEfficiencyCor::init(), Mantid::Algorithms::RadiusSum::init(), Mantid::Algorithms::RemoveLowResTOF::init(), Mantid::Algorithms::ResetNegatives::init(), Mantid::Algorithms::SassenaFFT::init(), Mantid::Algorithms::SetUncertainties::init(), Mantid::Algorithms::SmoothNeighbours::init(), Mantid::Algorithms::Stitch::init(), Mantid::Algorithms::SumOverlappingTubes::init(), Mantid::Algorithms::SumSpectra::init(), Mantid::Crystal::CombinePeaksWorkspaces::init(), Mantid::Crystal::FindClusterFaces::init(), Mantid::Crystal::FindSXPeaks::init(), Mantid::Crystal::OptimizeCrystalPlacement::init(), Mantid::Crystal::PeaksInRegion::init(), Mantid::Crystal::PredictPeaks::init(), Mantid::Crystal::PredictSatellitePeaks::init(), Mantid::Crystal::SetGoniometer::init(), Mantid::CurveFitting::Algorithms::LeBailFit::init(), Mantid::CurveFitting::Functions::ProcessBackground::init(), Mantid::DataHandling::ApplyDiffCal::init(), Mantid::DataHandling::LoadAscii2::init(), Mantid::DataHandling::LoadEventNexus::init(), Mantid::DataHandling::LoadEventPreNexus2::init(), Mantid::DataHandling::LoadILLPolarizedDiffraction::init(), Mantid::DataHandling::LoadPreNexus::init(), Mantid::DataHandling::LoadSampleEnvironment::init(), Mantid::DataHandling::MaskDetectors::init(), Mantid::DataHandling::SaveAscii::init(), Mantid::DataHandling::SaveAscii2::init(), Mantid::DataHandling::SaveGSS::init(), Mantid::DataHandling::SaveNexusProcessed::init(), Mantid::DataHandling::SetSampleMaterial::init(), Mantid::MDAlgorithms::BaseConvertToDiffractionMDWorkspace::init(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::init(), Mantid::MDAlgorithms::ConvertToMDParent::init(), Mantid::MDAlgorithms::FindPeaksMD::init(), Mantid::MDAlgorithms::IntegratePeaksMD2::init(), Mantid::MDAlgorithms::LoadMD::init(), Mantid::MDAlgorithms::MDNorm::init(), Mantid::MDAlgorithms::QueryMDWorkspace::init(), Mantid::MDAlgorithms::ThresholdMD::init(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::init(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::init(), and Mantid::MDAlgorithms::SlicingAlgorithm::initSlicingProps().
setPropertyValue()
virtual void Mantid::Kernel::IPropertyManager::setPropertyValue (const std::string & name, const std::string & value) pure virtual
Sets property value from a string.
Parameters
name :: Property name
value :: New property value
Implemented in Mantid::API::IAlgorithmRuntimeProps, Mantid::API::Algorithm, Mantid::API::AlgorithmRuntimeProps, Mantid::DataHandling::Load, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by MantidQt::MantidWidgets::FitOptionsBrowser::copyPropertiesToAlgorithm(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), Mantid::MDAlgorithms::FitMD::createHistoOutputWorkspace(), Mantid::CurveFitting::IMWDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::LatticeDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::MultiDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::TableWorkspaceDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::GeneralDomainCreator::createOutputWorkspace(), Mantid::CurveFitting::SeqDomainSpectrumCreator::createOutputWorkspace(), export_IPropertyManager(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::performFit(), Mantid::DataHandling::SaveCanSAS1D::setOtherProperties(), Mantid::API::Algorithm::setOtherProperties(), Mantid::DataHandling::SaveGSS::setOtherProperties(), Mantid::DataHandling::SaveFocusedXYE::setOtherProperties(), Mantid::DataHandling::SaveNexus::setOtherProperties(), Mantid::DataHandling::SaveNexusProcessed::setOtherProperties(), and Mantid::Kernel::PropertyManager::setProperties().
setPropertyValueFromJson()
virtual void Mantid::Kernel::IPropertyManager::setPropertyValueFromJson (const std::string & name, const Json::Value & value) pure virtual
Sets property value from a Json::Value.
Parameters
name :: Property name
value :: New property value
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
Referenced by Mantid::Kernel::PropertyManager::setProperties().
setTypedProperty() [1/3]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::setTypedProperty (const std::string & name, const T & value, const std::false_type &) inline private
Set a property value that is not convertible to a DataItem_sptr.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 477 of file IPropertyManager.h.
References name, and value.
setTypedProperty() [2/3]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::setTypedProperty (const std::string & name, const T & value, const std::true_type &) inline private
Set a property value that is convertible to a DataItem_sptr.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 495 of file IPropertyManager.h.
References error, name, and value.
setTypedProperty() [3/3]
template<typename T > IPropertyManager * Mantid::Kernel::IPropertyManager::setTypedProperty (const std::string & name, std::unique_ptr< T > value, const std::true_type &) inline private
Set a property value from std::unique_ptr that is convertible to a DataItem_sptr.
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError If the named property is unknown
std::invalid_argument If an attempt is made to assign to a property of different type
Definition at line 515 of file IPropertyManager.h.
References error, name, and value.
takeProperty()
virtual std::unique_ptr< Property > Mantid::Kernel::IPropertyManager::takeProperty (const size_t index) pure virtual
Removes the property from management and returns a pointer to it.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
updatePropertyValues()
void Mantid::Kernel::IPropertyManager::updatePropertyValues (const IPropertyManager & other)
Update values of the existing properties.
Referenced by Mantid::API::LiveListener::setAlgorithm().
validateProperties()
virtual bool Mantid::Kernel::IPropertyManager::validateProperties () const pure virtual
Validates all the properties in the collection.
Implemented in Mantid::API::Algorithm, Mantid::Kernel::PropertyManager, and Mantid::Kernel::PropertyManagerOwner.
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/IPropertyManager.h
Framework/Kernel/src/PropertyManagerProperty.cpp