Mantid: Mantid::DataHandling::SinglePeriodLoadMuonStrategy Class Reference
Mantid::DataHandling::SinglePeriodLoadMuonStrategy Class Reference
#include <SinglePeriodLoadMuonStrategy.h>
Public Member Functions
void applyTimeZeroCorrection () override
Performs time-zero correction on the loaded workspace.
API::Workspace_sptr getTimeZeroTable () override
Gets time zero table from loaded time zeros.
API::Workspace_sptr loadDeadTimeTable () const override
Loads deadtime table from nexus file.
API::Workspace_sptr loadDetectorGrouping () const override
Loads detector grouping.
void loadGoodFrames () override
Loads the good frames data into the stored workspace object.
void loadMuonLogData () override
Loads Muon specific logs into the stored workspace These are logs which are not loaded by LoadISISNexus.
SinglePeriodLoadMuonStrategy (Kernel::Logger &g_log, const std::string &filename, LoadMuonNexusV2NexusHelper &nexusLoader, DataObjects::Workspace2D &workspace, int entryNumber, bool isFileMultiPeriod)
Public Member Functions inherited from Mantid::DataHandling::LoadMuonStrategy
LoadMuonStrategy (Kernel::Logger &g_log, std::string filename, LoadMuonNexusV2NexusHelper &nexusLoader)
virtual ~LoadMuonStrategy ()=default
Private Member Functions
std::vector< detid_t > getLoadedDetectors ()
Finds the detectors which are loaded in the stored workspace.
Private Attributes
std::vector< detid_t > m_detectors
int m_entryNumber
bool m_isFileMultiPeriod
DataObjects::Workspace2D & m_workspace
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataHandling::LoadMuonStrategy
DataObjects::TableWorkspace_sptr createDeadTimeTable (const std::vector< detid_t > &detectorsLoaded, const std::vector< double > &deadTimes) const
Creates the deadtime table for the loaded detectors .
std::optional< DataObjects::TableWorkspace_sptr > createDetectorGroupingTable (const std::vector< detid_t > &specToLoad, const std::optional< std::vector< detid_t > > &grouping) const
Creates Detector Grouping Table .
std::vector< detid_t > getLoadedDetectorsFromWorkspace (const DataObjects::Workspace2D &localWorkspace) const
Determines the detectors loaded in the input workspace.
API::Workspace_sptr loadDefaultDetectorGrouping (const DataObjects::Workspace2D &localWorkspace) const
Loads default detector grouping, if this isn't present return dummy grouping.
Protected Attributes inherited from Mantid::DataHandling::LoadMuonStrategy
const std::string m_filename
Kernel::Logger & m_logger
LoadMuonNexusV2NexusHelper & m_nexusLoader
Detailed Description
Definition at line 13 of file SinglePeriodLoadMuonStrategy.h.
Constructor & Destructor Documentation
SinglePeriodLoadMuonStrategy()
Mantid::DataHandling::SinglePeriodLoadMuonStrategy::SinglePeriodLoadMuonStrategy (Kernel::Logger & g_log, const std::string & filename, LoadMuonNexusV2NexusHelper & nexusLoader, DataObjects::Workspace2D & workspace, int entryNumber, bool isFileMultiPeriod)
Definition at line 23 of file SinglePeriodLoadMuonStrategy.cpp.
Member Function Documentation
applyTimeZeroCorrection()
void Mantid::DataHandling::SinglePeriodLoadMuonStrategy::applyTimeZeroCorrection () override virtual
Performs time-zero correction on the loaded workspace.
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 98 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataObjects::Workspace2D::getNumberHistograms(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroFromNexusFile(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspace, and Mantid::API::MatrixWorkspace::mutableX().
getLoadedDetectors()
std::vector< detid_t > Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getLoadedDetectors () private
Finds the detectors which are loaded in the stored workspace.
Definition at line 109 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonStrategy::getLoadedDetectorsFromWorkspace(), and m_workspace.
getTimeZeroTable()
Workspace_sptr Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getTimeZeroTable () override virtual
Gets time zero table from loaded time zeros.
Returns
:: Time zero table
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 90 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::createTimeZeroTable(), Mantid::DataObjects::Workspace2D::getNumberHistograms(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroListFromNexusFile(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, and m_workspace.
loadDeadTimeTable()
Workspace_sptr Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDeadTimeTable () const override virtual
Loads deadtime table from nexus file.
Returns
:: Dead time table
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 82 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonStrategy::createDeadTimeTable(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDeadTimesFromNexus(), m_detectors, m_entryNumber, m_isFileMultiPeriod, and Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader.
loadDetectorGrouping()
Workspace_sptr Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping () const override virtual
Loads detector grouping.
If no entry in NeXus file for grouping, load it from the IDF. stored
Returns
:: Grouping table
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 70 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonStrategy::createDetectorGroupingTable(), Mantid::DataHandling::LoadMuonStrategy::loadDefaultDetectorGrouping(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDetectorGroupingFromNexus(), m_detectors, m_entryNumber, m_isFileMultiPeriod, Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, and m_workspace.
loadGoodFrames()
void Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadGoodFrames () override virtual
Loads the good frames data into the stored workspace object.
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 50 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadGoodFramesDataFromNexus(), m_entryNumber, m_isFileMultiPeriod, Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspace, Mantid::API::ExperimentInfo::mutableRun(), and Mantid::API::LogManager::removeProperty().
loadMuonLogData()
void Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadMuonLogData () override virtual
Loads Muon specific logs into the stored workspace These are logs which are not loaded by LoadISISNexus.
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 34 of file SinglePeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadFirstGoodDataFromNexus(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadMainFieldDirectionFromNexus(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadSampleInformationFromNexus(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspace, and Mantid::API::ExperimentInfo::mutableRun().
Member Data Documentation
m_detectors
std::vector<detid_t> Mantid::DataHandling::SinglePeriodLoadMuonStrategy::m_detectors private
Definition at line 36 of file SinglePeriodLoadMuonStrategy.h.
Referenced by loadDeadTimeTable(), and loadDetectorGrouping().
m_entryNumber
int Mantid::DataHandling::SinglePeriodLoadMuonStrategy::m_entryNumber private
Definition at line 34 of file SinglePeriodLoadMuonStrategy.h.
Referenced by loadDeadTimeTable(), loadDetectorGrouping(), and loadGoodFrames().
m_isFileMultiPeriod
bool Mantid::DataHandling::SinglePeriodLoadMuonStrategy::m_isFileMultiPeriod private
Definition at line 35 of file SinglePeriodLoadMuonStrategy.h.
Referenced by loadDeadTimeTable(), loadDetectorGrouping(), and loadGoodFrames().
m_workspace
DataObjects::Workspace2D& Mantid::DataHandling::SinglePeriodLoadMuonStrategy::m_workspace private
Definition at line 33 of file SinglePeriodLoadMuonStrategy.h.
Referenced by applyTimeZeroCorrection(), getLoadedDetectors(), getTimeZeroTable(), loadDetectorGrouping(), loadGoodFrames(), and loadMuonLogData().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/SinglePeriodLoadMuonStrategy.h
Framework/DataHandling/src/SinglePeriodLoadMuonStrategy.cpp