Mantid: ICat4::ns1__entityField Class Reference
ICat4::ns1__entityField Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__entityField ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * comment
std::string * name
bool notNullable
enum ns1__relType * relType
int * stringLength
std::string * type
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1149 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__entityField()
ICat4::ns1__entityField::ns1__entityField () inline
Definition at line 1165 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__entityField::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7704 of file ICat4C.cpp.
References ICat4::soap_default_bool().
Referenced by ICat4::soap_in_ns1__entityField(), ICat4::soap_new_req_ns1__entityField(), and ICat4::soap_new_set_ns1__entityField().
soap_get()
void * ICat4::ns1__entityField::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7848 of file ICat4C.cpp.
References ICat4::soap_get_ns1__entityField().
soap_in()
void * ICat4::ns1__entityField::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7752 of file ICat4C.cpp.
References ICat4::soap_in_ns1__entityField().
Referenced by ICat4::soap_in_ns1__entityField().
soap_out()
int ICat4::ns1__entityField::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7727 of file ICat4C.cpp.
References ICat4::soap_out_ns1__entityField().
soap_put()
int ICat4::ns1__entityField::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7841 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__entityField.
soap_serialize()
void ICat4::ns1__entityField::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7715 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerToint(), ICat4::soap_serialize_PointerTons1__relType(), and ICat4::soap_serialize_PointerTostd__string().
soap_type()
int ICat4::ns1__entityField::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1158 of file ICat4Stub.h.
Member Data Documentation
comment
std::string* ICat4::ns1__entityField::comment
Definition at line 1151 of file ICat4Stub.h.
name
std::string* ICat4::ns1__entityField::name
Definition at line 1152 of file ICat4Stub.h.
notNullable
bool ICat4::ns1__entityField::notNullable
Definition at line 1153 of file ICat4Stub.h.
relType
enum ns1__relType* ICat4::ns1__entityField::relType
Definition at line 1154 of file ICat4Stub.h.
stringLength
int* ICat4::ns1__entityField::stringLength
Definition at line 1155 of file ICat4Stub.h.
type
std::string* ICat4::ns1__entityField::type
Definition at line 1156 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp