Mantid: Mantid::Geometry::PeakShape Class Reference
Mantid::Geometry::PeakShape Class Reference abstract
PeakShape : Abstract type to describes the shape of a peak.
#include <PeakShape.h>
Public Types
enum RadiusType { Radius = 0 , OuterRadius = 1 , InnerRadius = 2 }
For selecting different radius types.
Public Member Functions
virtual std::string algorithmName () const =0
Algorithm.
virtual int algorithmVersion () const =0
Algorithm Version.
virtual PeakShape * clone () const =0
Deep copy this.
virtual Mantid::Kernel::SpecialCoordinateSystem frame () const =0
Coordinte frame used upon creation.
virtual std::optional< double > radius (RadiusType type) const =0
Radius.
virtual std::string shapeName () const =0
Shape name.
virtual std::string toJSON () const =0
Serialize.
virtual ~PeakShape ()=default
Destructor.
Detailed Description
PeakShape : Abstract type to describes the shape of a peak.
Definition at line 20 of file PeakShape.h.
Member Enumeration Documentation
RadiusType
enum Mantid::Geometry::PeakShape::RadiusType
For selecting different radius types.
Enumerator
Radius
OuterRadius
InnerRadius
Definition at line 35 of file PeakShape.h.
Constructor & Destructor Documentation
~PeakShape()
virtual Mantid::Geometry::PeakShape::~PeakShape () virtual default
Destructor.
Member Function Documentation
algorithmName()
virtual std::string Mantid::Geometry::PeakShape::algorithmName () const pure virtual
Algorithm.
Implemented in Mantid::DataObjects::NoShape, and Mantid::DataObjects::PeakShapeBase.
Referenced by export_PeakShape().
algorithmVersion()
virtual int Mantid::Geometry::PeakShape::algorithmVersion () const pure virtual
Algorithm Version.
Implemented in Mantid::DataObjects::NoShape, and Mantid::DataObjects::PeakShapeBase.
Referenced by export_PeakShape().
clone()
virtual PeakShape * Mantid::Geometry::PeakShape::clone () const pure virtual
Deep copy this.
Implemented in Mantid::DataObjects::NoShape, Mantid::DataObjects::PeakShapeDetectorBin, Mantid::DataObjects::PeakShapeEllipsoid, and Mantid::DataObjects::PeakShapeSpherical.
frame()
virtual Mantid::Kernel::SpecialCoordinateSystem Mantid::Geometry::PeakShape::frame () const pure virtual
Coordinte frame used upon creation.
Implemented in Mantid::DataObjects::NoShape, and Mantid::DataObjects::PeakShapeBase.
radius()
virtual std::optional< double > Mantid::Geometry::PeakShape::radius (RadiusType type) const pure virtual
Radius.
Implemented in Mantid::DataObjects::PeakShapeEllipsoid, Mantid::DataObjects::PeakShapeSpherical, Mantid::DataObjects::NoShape, and Mantid::DataObjects::PeakShapeDetectorBin.
shapeName()
virtual std::string Mantid::Geometry::PeakShape::shapeName () const pure virtual
Shape name.
Implemented in Mantid::DataObjects::NoShape, Mantid::DataObjects::PeakShapeDetectorBin, Mantid::DataObjects::PeakShapeEllipsoid, and Mantid::DataObjects::PeakShapeSpherical.
Referenced by Mantid::DataObjects::PeakShapeBase::buildCommon(), and export_PeakShape().
toJSON()
virtual std::string Mantid::Geometry::PeakShape::toJSON () const pure virtual
Serialize.
Implemented in Mantid::DataObjects::NoShape, Mantid::DataObjects::PeakShapeDetectorBin, Mantid::DataObjects::PeakShapeEllipsoid, and Mantid::DataObjects::PeakShapeSpherical.
Referenced by export_PeakShape(), Mantid::DataObjects::LeanElasticPeaksWorkspace::saveNexus(), and Mantid::DataObjects::PeaksWorkspace::saveNexus().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/PeakShape.h