Mantid: Mantid::API::IMDHistoWorkspace Class Reference
Mantid::API::IMDHistoWorkspace Class Reference abstract
Abstract interface to MDHistoWorkspace, for use in exposing to Python.
#include <IMDHistoWorkspace.h>
Public Member Functions
IMDHistoWorkspace_uptr clone () const
Returns a clone of the workspace.
IMDHistoWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
virtual signal_t & errorSquaredAt (size_t index)=0
virtual Mantid::Kernel::VMD getCenter (size_t linearIndex) const =0
virtual signal_t getErrorAt (size_t index) const =0
virtual signal_t getErrorAt (size_t index1, size_t index2) const =0
virtual signal_t getErrorAt (size_t index1, size_t index2, size_t index3) const =0
virtual signal_t getErrorAt (size_t index1, size_t index2, size_t index3, size_t index4) const =0
virtual signal_t getErrorNormalizedAt (size_t index) const =0
virtual signal_t getErrorNormalizedAt (size_t index1, size_t index2) const =0
virtual signal_t getErrorNormalizedAt (size_t index1, size_t index2, size_t index3) const =0
virtual signal_t getErrorNormalizedAt (size_t index1, size_t index2, size_t index3, size_t index4) const =0
virtual const signal_t * getErrorSquaredArray () const =0
virtual coord_t getInverseVolume () const =0
See the MDHistoWorkspace definition for descriptions of these.
virtual size_t getLinearIndex (size_t index1, size_t index2) const =0
virtual size_t getLinearIndex (size_t index1, size_t index2, size_t index3) const =0
virtual size_t getLinearIndex (size_t index1, size_t index2, size_t index3, size_t index4) const =0
virtual LinePlot getLineData (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const =0
virtual const signal_t * getNumEventsArray () const =0
virtual const signal_t * getSignalArray () const =0
virtual signal_t getSignalAt (size_t index) const =0
virtual signal_t getSignalAt (size_t index1, size_t index2) const =0
virtual signal_t getSignalAt (size_t index1, size_t index2, size_t index3) const =0
virtual signal_t getSignalAt (size_t index1, size_t index2, size_t index3, size_t index4) const =0
virtual signal_t getSignalNormalizedAt (size_t index) const =0
virtual signal_t getSignalNormalizedAt (size_t index1, size_t index2) const =0
virtual signal_t getSignalNormalizedAt (size_t index1, size_t index2, size_t index3) const =0
virtual signal_t getSignalNormalizedAt (size_t index1, size_t index2, size_t index3, size_t index4) const =0
virtual bool hasOrientedLattice () const override
IMDHistoWorkspace ()=default
virtual signal_t * mutableErrorSquaredArray ()=0
virtual signal_t * mutableNumEventsArray ()=0
virtual signal_t * mutableSignalArray ()=0
IMDHistoWorkspace & operator= (const IMDHistoWorkspace &)=delete
virtual double & operator[] (const size_t &index)=0
virtual void setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem)=0
virtual void setDisplayNormalization (const Mantid::API::MDNormalization &preferredNormalization)=0
virtual void setErrorSquaredAt (size_t index, signal_t value)=0
virtual void setSignalAt (size_t index, signal_t value)=0
virtual void setTo (signal_t signal, signal_t errorSquared, signal_t numEvents)=0
virtual signal_t & signalAt (size_t index)=0
Public Member Functions inherited from Mantid::API::IMDWorkspace
std::string changeQConvention ()
virtual void clearFileBacked (bool)
if a workspace was filebacked, this should clear file-based status, delete file-based information and close related files.
virtual void clearMDMasking ()=0
Clear existing masks.
std::unique_ptr< IMDWorkspace > clone () const
Returns a clone of the workspace.
std::unique_ptr< IMDWorkspace > cloneEmpty () const
Returns a default-initialized clone of the workspace.
std::unique_ptr< IMDIterator > createIterator (Mantid::Geometry::MDImplicitFunction *function=nullptr) const
Creates a single iterator and returns it.
virtual std::vector< std::unique_ptr< IMDIterator > > createIterators (size_t suggestedNumCores=1, Mantid::Geometry::MDImplicitFunction *function=nullptr) const =0
Creates a new iterator pointing to the first cell in the workspace.
virtual MDNormalization displayNormalization () const
virtual MDNormalization displayNormalizationHisto () const
const std::string & getConvention () const
virtual LinePlot getLinePlot (const Mantid::Kernel::VMD &start, const Mantid::Kernel::VMD &end, Mantid::API::MDNormalization normalize) const
Method to generate a line plot through a MD-workspace.
virtual uint64_t getNEvents () const =0
virtual uint64_t getNPoints () const =0
Get the number of points associated with the workspace.
virtual signal_t getSignalAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const =0
Returns the (normalized) signal at a given coordinates.
signal_t getSignalAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates.
virtual signal_t getSignalWithMaskAtCoord (const coord_t *coords, const Mantid::API::MDNormalization &normalization) const =0
Returns the (normalized) signal at a given coordinates or 0 if the value.
signal_t getSignalWithMaskAtVMD (const Mantid::Kernel::VMD &coords, const Mantid::API::MDNormalization &normalization=Mantid::API::VolumeNormalization) const
Returns the signal (normalized by volume) at a given coordinates or 0 if masked.
virtual Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const =0
IMDWorkspace ()
Default constructor.
virtual bool isMDHistoWorkspace () const
virtual ITableWorkspace_sptr makeBoxTable (size_t, size_t)
this is the method to build table workspace from any workspace.
IMDWorkspace & operator= (const IMDWorkspace &other)=delete
void setConvention (std::string convention)
Sets the convention of the workspace.
virtual void setMDMasking (std::unique_ptr< Mantid::Geometry::MDImplicitFunction > maskingRegion)=0
Setter for the masking region.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
virtual size_t getMemorySize () const =0
Get the footprint in memory in bytes.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
virtual const std::string getTitle () const
Get the workspace title.
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
virtual void setTitle (const std::string &)
Set the title of the workspace.
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
virtual const std::string id () const =0
A string ID for the class.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::MDGeometry
void addDimension (const std::shared_ptr< Mantid::Geometry::IMDDimension > &dim)
Add a dimension.
void addDimension (Mantid::Geometry::IMDDimension *dim)
Add a dimension.
bool allBasisNormalized () const
void clearOriginalWorkspaces ()
Clear original workspaces.
void clearTransforms ()
Clear transforms.
virtual std::vector< coord_t > estimateResolution () const
Mantid::Kernel::VMD & getBasisVector (size_t index)
Get the basis vector (in the original workspace) for a dimension of this workspace.
const Mantid::Kernel::VMD & getBasisVector (size_t index) const
Get the basis vector (in the original workspace) for a dimension of this workspace.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimension (size_t index) const
Get a dimension.
size_t getDimensionIndexById (const std::string &id) const
Get the index of the dimension that matches the ID given.
size_t getDimensionIndexByName (const std::string &name) const
Get the index of the dimension that matches the name given.
virtual std::shared_ptr< const Mantid::Geometry::IMDDimension > getDimensionWithId (std::string id) const
Get a dimension.
std::string getGeometryXML () const
std::vector< std::shared_ptr< const Geometry::IMDDimension > > getNonIntegratedDimensions () const
Get non-collapsed dimensions.
size_t getNumberTransformsFromOriginal () const
Get the number of transforms defined from the original coordinate system.
size_t getNumberTransformsToOriginal () const
Get the number of transforms defined to the original coordinate system.
virtual size_t getNumDims () const
virtual size_t getNumNonIntegratedDims () const
Mantid::Kernel::VMD & getOrigin ()
const Mantid::Kernel::VMD & getOrigin () const
std::shared_ptr< Workspace > getOriginalWorkspace (size_t index=0) const
Get the "original" workspace (the workspace that was the source for a binned MDWorkspace).
std::shared_ptr< const Mantid::Geometry::IMDDimension > getTDimension () const
Get the t-dimension mapping.
Mantid::API::CoordTransform const * getTransformFromOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
Mantid::API::CoordTransform const * getTransformToOriginal (size_t index=0) const
Get the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
const Kernel::DblMatrix & getWTransf () const
get the transformation from Qin crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
std::shared_ptr< const Mantid::Geometry::IMDDimension > getXDimension () const
Get the x-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getYDimension () const
Get the y-dimension mapping.
std::shared_ptr< const Mantid::Geometry::IMDDimension > getZDimension () const
Get the z-dimension mapping.
bool hasOriginalWorkspace (size_t index=0) const
void initGeometry (const std::vector< std::shared_ptr< Geometry::IMDDimension > > &dimensions)
Initialize the geometry.
MDGeometry ()
Constructor.
MDGeometry (const MDGeometry &other)
Copy Constructor.
size_t numOriginalWorkspaces () const
MDGeometry & operator= (const MDGeometry &other)
void setBasisVector (size_t index, const Mantid::Kernel::VMD &vec)
Set the basis vector (in the original workspace) for a dimension of this workspace.
void setOrigin (const Mantid::Kernel::VMD &orig)
Sets the origin of this geometry.
void setOriginalWorkspace (std::shared_ptr< Workspace > ws, size_t index=0)
Set the "original" workspace (the workspace that was the source for a binned MDWorkspace).
void setTransformFromOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
void setTransformToOriginal (Mantid::API::CoordTransform *transform, size_t index=0)
Sets the Coordinate Transformation that goes from THIS workspace's coordinates to the ORIGINAL workspace's coordinates.
void setWTransf (const Kernel::DblMatrix &WTransf)
set the transformation from Q in crystal cartezian coordinate system to Q in orthogonal or real HKL coordiate system alined with arbitrary slicing plane
void transformDimensions (std::vector< double > const &scaling, std::vector< double > const &offset)
Transform the dimensions contained in this geometry x' = x*scaling + offset.
virtual ~MDGeometry ()
Destructor.
Public Member Functions inherited from Mantid::API::MultipleExperimentInfos
uint16_t addExperimentInfo (const ExperimentInfo_sptr &ei)
Add a new ExperimentInfo to this MDEventWorkspace.
void copyExperimentInfos (const MultipleExperimentInfos &other)
Copy the experiment infos from another.
ExperimentInfo_sptr getExperimentInfo (const uint16_t expInfoIndex)
Get the ExperimentInfo for the given Experiment-Info Index.
ExperimentInfo_const_sptr getExperimentInfo (const uint16_t expInfoIndex) const
Get the ExperimentInfo for the given Experiment-Info Index.
uint16_t getNumExperimentInfo () const
bool hasOrientedLattice () const
MultipleExperimentInfos ()=default
MultipleExperimentInfos (const MultipleExperimentInfos &other)
Copy constructor.
MultipleExperimentInfos & operator= (const MultipleExperimentInfos &other)
void setExperimentInfo (const uint16_t expInfoIndex, ExperimentInfo_sptr ei)
Replace the ExperimentInfo entry at a given place.
virtual ~MultipleExperimentInfos ()=default
Protected Member Functions
IMDHistoWorkspace (const IMDHistoWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::IMDWorkspace
IMDWorkspace (const IMDWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void makeSinglePointWithNaN (std::vector< coord_t > &x, std::vector< signal_t > &y, std::vector< signal_t > &e) const
Make a single point with NaN as the signal and error This can be returned when there would otherwise be nothing to plot.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::MDGeometry
void deleteNotificationReceived (const std::shared_ptr< const Workspace > &replaced)
Function called when observer objects recieves a notification.
void replaceNotificationReceived (const std::shared_ptr< const Workspace > &deleted)
Function called when observer detects a workspace is replaced.
Protected Member Functions inherited from Mantid::API::MultipleExperimentInfos
const std::string toString () const
Returns a string description of the object.
Private Member Functions
IMDHistoWorkspace * doClone () const override=0
Virtual clone method. Not implemented to force implementation in children.
IMDHistoWorkspace * doCloneEmpty () const override=0
Virtual cloneEmpty method.
Additional Inherited Members
Protected Attributes inherited from Mantid::API::MDGeometry
std::vector< Mantid::Kernel::VMD > m_basisVectors
Vector of the basis vector (in the original workspace) for each dimension of this workspace.
std::vector< std::shared_ptr< Geometry::IMDDimension > > m_dimensions
Vector of the dimensions used, in the order X Y Z t, etc.
std::unique_ptr< MDGeometryNotificationHelper > m_notificationHelper
Helper that deals with notifications and observing the ADS.
Mantid::Kernel::VMD m_origin
Vector of the origin (in the original workspace) that corresponds to 0,0,0... in this workspace.
std::vector< std::shared_ptr< Workspace > > m_originalWorkspaces
Pointer to the original workspace(s), if this workspace is a coordinate transformation from an original workspace.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_FromOriginal
Coordinate Transformation that goes from the original workspace to this workspace's coordinates.
std::vector< std::shared_ptr< const Mantid::API::CoordTransform > > m_transforms_ToOriginal
Coordinate Transformation that goes from this workspace's coordinates to the original workspace coordinates.
Kernel::DblMatrix m_Wtransf
the matrix which transforms momentums from orthogonal Q-system to Orthogonal HKL or non-orthogonal HKL system alighned WRT to arbitrary coordinate system requested See the UB matrix formalizm, pg 7 for further details on implementation.
Detailed Description
Abstract interface to MDHistoWorkspace, for use in exposing to Python.
Date
2011-11-09
Definition at line 22 of file IMDHistoWorkspace.h.
Constructor & Destructor Documentation
IMDHistoWorkspace() [1/2]
Mantid::API::IMDHistoWorkspace::IMDHistoWorkspace () default
IMDHistoWorkspace() [2/2]
Mantid::API::IMDHistoWorkspace::IMDHistoWorkspace (const IMDHistoWorkspace &) protected default
Protected copy constructor. May be used by childs for cloning.
References Mantid::Kernel::toString().
Member Function Documentation
clone()
IMDHistoWorkspace_uptr Mantid::API::IMDHistoWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 27 of file IMDHistoWorkspace.h.
cloneEmpty()
IMDHistoWorkspace_uptr Mantid::API::IMDHistoWorkspace::cloneEmpty () const inline
Returns a default-initialized clone of the workspace.
Definition at line 29 of file IMDHistoWorkspace.h.
doClone()
IMDHistoWorkspace * Mantid::API::IMDHistoWorkspace::doClone () const override private pure virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
doCloneEmpty()
IMDHistoWorkspace * Mantid::API::IMDHistoWorkspace::doCloneEmpty () const override private pure virtual
Virtual cloneEmpty method.
Not implemented to force implementation in children.
Implements Mantid::API::IMDWorkspace.
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
errorSquaredAt()
virtual signal_t & Mantid::API::IMDHistoWorkspace::errorSquaredAt (size_t index) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
getCenter()
virtual Mantid::Kernel::VMD Mantid::API::IMDHistoWorkspace::getCenter (size_t linearIndex) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
getErrorAt() [1/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorAt (size_t index) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorAt() [2/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorAt (size_t index1, size_t index2) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorAt() [3/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorAt (size_t index1, size_t index2, size_t index3) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorAt() [4/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorAt (size_t index1, size_t index2, size_t index3, size_t index4) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorNormalizedAt() [1/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorNormalizedAt (size_t index) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorNormalizedAt() [2/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorNormalizedAt (size_t index1, size_t index2) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorNormalizedAt() [3/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorNormalizedAt (size_t index1, size_t index2, size_t index3) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorNormalizedAt() [4/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getErrorNormalizedAt (size_t index1, size_t index2, size_t index3, size_t index4) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getErrorSquaredArray()
virtual const signal_t * Mantid::API::IMDHistoWorkspace::getErrorSquaredArray () const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getInverseVolume()
virtual coord_t Mantid::API::IMDHistoWorkspace::getInverseVolume () const pure virtual
See the MDHistoWorkspace definition for descriptions of these.
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
getLinearIndex() [1/3]
virtual size_t Mantid::API::IMDHistoWorkspace::getLinearIndex (size_t index1, size_t index2) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
getLinearIndex() [2/3]
virtual size_t Mantid::API::IMDHistoWorkspace::getLinearIndex (size_t index1, size_t index2, size_t index3) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getLinearIndex() [3/3]
virtual size_t Mantid::API::IMDHistoWorkspace::getLinearIndex (size_t index1, size_t index2, size_t index3, size_t index4) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getLineData()
virtual LinePlot Mantid::API::IMDHistoWorkspace::getLineData (const Mantid::Kernel::VMD & start, const Mantid::Kernel::VMD & end, Mantid::API::MDNormalization normalize) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getNumEventsArray()
virtual const signal_t * Mantid::API::IMDHistoWorkspace::getNumEventsArray () const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalArray()
virtual const signal_t * Mantid::API::IMDHistoWorkspace::getSignalArray () const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalAt() [1/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalAt (size_t index) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalAt() [2/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalAt (size_t index1, size_t index2) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalAt() [3/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalAt (size_t index1, size_t index2, size_t index3) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalAt() [4/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalAt (size_t index1, size_t index2, size_t index3, size_t index4) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalNormalizedAt() [1/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalNormalizedAt (size_t index) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalNormalizedAt() [2/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalNormalizedAt (size_t index1, size_t index2) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalNormalizedAt() [3/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalNormalizedAt (size_t index1, size_t index2, size_t index3) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
getSignalNormalizedAt() [4/4]
virtual signal_t Mantid::API::IMDHistoWorkspace::getSignalNormalizedAt (size_t index1, size_t index2, size_t index3, size_t index4) const pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
hasOrientedLattice()
virtual bool Mantid::API::IMDHistoWorkspace::hasOrientedLattice () const inline override virtual
Implements Mantid::API::IMDWorkspace.
Definition at line 77 of file IMDHistoWorkspace.h.
mutableErrorSquaredArray()
virtual signal_t * Mantid::API::IMDHistoWorkspace::mutableErrorSquaredArray () pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
mutableNumEventsArray()
virtual signal_t * Mantid::API::IMDHistoWorkspace::mutableNumEventsArray () pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
mutableSignalArray()
virtual signal_t * Mantid::API::IMDHistoWorkspace::mutableSignalArray () pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
operator=()
IMDHistoWorkspace & Mantid::API::IMDHistoWorkspace::operator= (const IMDHistoWorkspace &) delete
operator[]()
virtual double & Mantid::API::IMDHistoWorkspace::operator[] (const size_t & index) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
setCoordinateSystem()
virtual void Mantid::API::IMDHistoWorkspace::setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
setDisplayNormalization()
virtual void Mantid::API::IMDHistoWorkspace::setDisplayNormalization (const Mantid::API::MDNormalization & preferredNormalization) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
setErrorSquaredAt()
virtual void Mantid::API::IMDHistoWorkspace::setErrorSquaredAt (size_t index, signal_t value) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace.
Referenced by export_IMDHistoWorkspace().
setSignalAt()
virtual void Mantid::API::IMDHistoWorkspace::setSignalAt (size_t index, signal_t value) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace.
setTo()
virtual void Mantid::API::IMDHistoWorkspace::setTo (signal_t signal, signal_t errorSquared, signal_t numEvents) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace.
Referenced by export_IMDHistoWorkspace().
signalAt()
virtual signal_t & Mantid::API::IMDHistoWorkspace::signalAt (size_t index) pure virtual
Implemented in Mantid::DataObjects::MDHistoWorkspace, and MDHistoWorkspaceTester.
Referenced by export_IMDHistoWorkspace().
toString()
const std::string Mantid::API::IMDHistoWorkspace::toString () const override protected virtual
Serializes the object to a string.
Implements Mantid::Kernel::DataItem.
Reimplemented in MDHistoWorkspaceTester.
Definition at line 23 of file IMDHistoWorkspace.cpp.
References Mantid::API::MultipleExperimentInfos::toString(), and Mantid::API::IMDWorkspace::toString().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IMDHistoWorkspace.h
Framework/API/src/IMDHistoWorkspace.cpp