Mantid: Mantid::Geometry::FitParameter Class Reference
Mantid::Geometry::FitParameter Class Reference
Store information about a fitting parameter such as its value if it is constrained or tied.
#include <FitParameter.h>
Public Member Functions
FitParameter ()
Constructor.
std::string getConstraint () const
get constraint
const std::string & getConstraintPenaltyFactor () const
get penalty factor
const std::string & getFormula () const
get formula
const std::string & getFormulaUnit () const
get formula unit, and Empty string is no unit has been specified
const std::string & getFunction () const
get function
const Kernel::Interpolation & getLookUpTable () const
get look up table
const std::string & getName () const
get name
const std::string & getResultUnit () const
get result formula unit, and Empty string is no unit has been specified
const std::string & getTie () const
get tie
double getValue () const
get paramter value
double getValue (const double &at) const
get paramter value
void printSelf (std::ostream &os) const
Prints object to stream.
void setConstraintMax (const std::string &constraintMax)
set constraint max
void setConstraintMin (const std::string &constraintMin)
set constraint min
void setConstraintPenaltyFactor (const std::string &constraintPenaltyFactor)
set the constraint penalty
void setFormula (const std::string &formula)
set formula
void setFormulaUnit (const std::string &formulaUnit)
set formula unit
void setFunction (const std::string &function)
set function
void setLookUpTable (const Kernel::Interpolation &lookupTable)
set look up table
void setName (const std::string &name)
set name
void setResultUnit (const std::string &resultUnit)
set result formula unit
void setTie (const std::string &tie)
set tie
void setValue (double value)
set parameter value
Private Attributes
std::string m_constraintMax
constraint max boundary
std::string m_constraintMin
constraint min boundary
std::string m_constraintPenaltyFactor
the penalty factor
std::string m_formula
the formula
std::string m_formulaUnit
the unit that the formula expects
std::string m_function
name of fitting function
Kernel::Interpolation m_lookUpTable
look up table
std::string m_name
name of parameter
std::string m_resultUnit
the result unit
std::string m_tie
tie of parameter
double m_value
value of parameter
Detailed Description
Store information about a fitting parameter such as its value if it is constrained or tied.
Main purpose is to use this class as a type for storing information about a fitting parameter in the parameter map of the workspace.
Author
Anders Markvardsen, ISIS, RAL
Date
26/2/2010
Definition at line 26 of file FitParameter.h.
Constructor & Destructor Documentation
FitParameter()
Mantid::Geometry::FitParameter::FitParameter () inline
Constructor.
Definition at line 29 of file FitParameter.h.
Member Function Documentation
getConstraint()
std::string Mantid::Geometry::FitParameter::getConstraint () const
get constraint
Get constraint string.
Returns
Constraint string
Definition at line 28 of file FitParameter.cpp.
References m_constraintMax, m_constraintMin, m_name, and m_value.
getConstraintPenaltyFactor()
const std::string & Mantid::Geometry::FitParameter::getConstraintPenaltyFactor () const inline
get penalty factor
Definition at line 44 of file FitParameter.h.
getFormula()
const std::string & Mantid::Geometry::FitParameter::getFormula () const inline
get formula
Definition at line 54 of file FitParameter.h.
Referenced by Mantid::Algorithms::NormaliseByDetector::processHistogram().
getFormulaUnit()
const std::string & Mantid::Geometry::FitParameter::getFormulaUnit () const inline
get formula unit, and Empty string is no unit has been specified
Definition at line 58 of file FitParameter.h.
getFunction()
const std::string & Mantid::Geometry::FitParameter::getFunction () const inline
get function
Definition at line 66 of file FitParameter.h.
Referenced by Mantid::DataHandling::SaveParameterFile::exec(), and Mantid::Algorithms::NormaliseByDetector::processHistogram().
getLookUpTable()
const Kernel::Interpolation & Mantid::Geometry::FitParameter::getLookUpTable () const inline
get look up table
Definition at line 74 of file FitParameter.h.
getName()
const std::string & Mantid::Geometry::FitParameter::getName () const inline
get name
Definition at line 70 of file FitParameter.h.
Referenced by Mantid::Algorithms::NormaliseByDetector::processHistogram().
getResultUnit()
const std::string & Mantid::Geometry::FitParameter::getResultUnit () const inline
get result formula unit, and Empty string is no unit has been specified
Definition at line 62 of file FitParameter.h.
Referenced by Mantid::Algorithms::NormaliseByDetector::processHistogram().
getTie()
const std::string & Mantid::Geometry::FitParameter::getTie () const inline
get tie
Definition at line 38 of file FitParameter.h.
getValue() [1/2]
double Mantid::Geometry::FitParameter::getValue () const
get paramter value
Get parameter value.
Returns
the value of the fit parameter
Definition at line 113 of file FitParameter.cpp.
References m_value.
getValue() [2/2]
double Mantid::Geometry::FitParameter::getValue (const double & at) const
get paramter value
Get parameter value.
The default parameter 'at' is ignored expect if the value of the parameter is determined from a look up table or a formula.
Parameters
at :: number to return the value at
Returns
the value of the fit parameter
Definition at line 69 of file FitParameter.cpp.
References Mantid::Kernel::Interpolation::containData(), Mantid::Kernel::Logger::error(), Mantid::Geometry::g_log, m_formula, m_lookUpTable, m_value, and Mantid::Kernel::Interpolation::value().
Referenced by Mantid::Geometry::Component::getFittingParameter().
printSelf()
void Mantid::Geometry::FitParameter::printSelf (std::ostream & os) const
Prints object to stream.
Parameters
os :: the Stream to output to
Definition at line 119 of file FitParameter.cpp.
References m_constraintMax, m_constraintMin, m_constraintPenaltyFactor, m_formula, m_formulaUnit, m_function, m_lookUpTable, m_name, m_resultUnit, m_tie, and m_value.
Referenced by Mantid::Geometry::operator<<().
setConstraintMax()
void Mantid::Geometry::FitParameter::setConstraintMax (const std::string & constraintMax) inline
set constraint max
Definition at line 48 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setConstraintMin()
void Mantid::Geometry::FitParameter::setConstraintMin (const std::string & constraintMin) inline
set constraint min
Definition at line 46 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setConstraintPenaltyFactor()
void Mantid::Geometry::FitParameter::setConstraintPenaltyFactor (const std::string & constraintPenaltyFactor) inline
set the constraint penalty
Definition at line 50 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setFormula()
void Mantid::Geometry::FitParameter::setFormula (const std::string & formula) inline
set formula
Definition at line 56 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setFormulaUnit()
void Mantid::Geometry::FitParameter::setFormulaUnit (const std::string & formulaUnit) inline
set formula unit
Definition at line 60 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setFunction()
void Mantid::Geometry::FitParameter::setFunction (const std::string & function) inline
set function
Definition at line 68 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setLookUpTable()
void Mantid::Geometry::FitParameter::setLookUpTable (const Kernel::Interpolation & lookupTable) inline
set look up table
Definition at line 76 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setName()
void Mantid::Geometry::FitParameter::setName (const std::string & name) inline
set name
Definition at line 72 of file FitParameter.h.
References name.
Referenced by Mantid::Geometry::operator>>().
setResultUnit()
void Mantid::Geometry::FitParameter::setResultUnit (const std::string & resultUnit) inline
set result formula unit
Definition at line 64 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setTie()
void Mantid::Geometry::FitParameter::setTie (const std::string & tie) inline
set tie
Definition at line 40 of file FitParameter.h.
Referenced by Mantid::Geometry::operator>>().
setValue()
void Mantid::Geometry::FitParameter::setValue (double value) inline
set parameter value
Definition at line 36 of file FitParameter.h.
References m_value, and value.
Referenced by Mantid::Geometry::operator>>().
Member Data Documentation
m_constraintMax
std::string Mantid::Geometry::FitParameter::m_constraintMax private
constraint max boundary
Definition at line 87 of file FitParameter.h.
Referenced by getConstraint(), and printSelf().
m_constraintMin
std::string Mantid::Geometry::FitParameter::m_constraintMin private
constraint min boundary
Definition at line 86 of file FitParameter.h.
Referenced by getConstraint(), and printSelf().
m_constraintPenaltyFactor
std::string Mantid::Geometry::FitParameter::m_constraintPenaltyFactor private
the penalty factor
Definition at line 88 of file FitParameter.h.
Referenced by printSelf().
m_formula
std::string Mantid::Geometry::FitParameter::m_formula private
the formula
Definition at line 96 of file FitParameter.h.
Referenced by getValue(), and printSelf().
m_formulaUnit
std::string Mantid::Geometry::FitParameter::m_formulaUnit private
the unit that the formula expects
Definition at line 97 of file FitParameter.h.
Referenced by printSelf().
m_function
std::string Mantid::Geometry::FitParameter::m_function private
name of fitting function
Definition at line 90 of file FitParameter.h.
Referenced by printSelf().
m_lookUpTable
Kernel::Interpolation Mantid::Geometry::FitParameter::m_lookUpTable private
look up table
Definition at line 94 of file FitParameter.h.
Referenced by getValue(), and printSelf().
m_name
std::string Mantid::Geometry::FitParameter::m_name private
name of parameter
Definition at line 92 of file FitParameter.h.
Referenced by getConstraint(), and printSelf().
m_resultUnit
std::string Mantid::Geometry::FitParameter::m_resultUnit private
the result unit
Definition at line 98 of file FitParameter.h.
Referenced by printSelf().
m_tie
std::string Mantid::Geometry::FitParameter::m_tie private
tie of parameter
Definition at line 85 of file FitParameter.h.
Referenced by printSelf().
m_value
double Mantid::Geometry::FitParameter::m_value mutable private
value of parameter
Definition at line 83 of file FitParameter.h.
Referenced by getConstraint(), getValue(), getValue(), and printSelf().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/FitParameter.h
Framework/Geometry/src/Instrument/FitParameter.cpp