Mantid: MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple Class Reference
MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple Class Reference
WorkspaceTreeWidget implementation for the Workbench - required for some function overides.
#include <WorkspaceTreeWidgetSimple.h>
Signals
void contextMenuAboutToShow (void)
void overplotMDHistoClicked (const QStringList &workspaceNames)
void overplotMDHistoWithErrorsClicked (const QStringList &workspaceNames)
void overplotSpectrumClicked (const QStringList &workspaceNames)
void overplotSpectrumWithErrorsClicked (const QStringList &workspaceNames)
void plotAdvancedClicked (const QStringList &workspaceNames)
void plotBinClicked (const QStringList &workspaceNames)
void plotColorfillClicked (const QStringList &workspaceNames)
void plotContourClicked (const QStringList &workspaceNames)
void plotMDHistoClicked (const QStringList &workspaceNames)
void plotMDHistoWithErrorsClicked (const QStringList &workspaceNames)
void plotSpectrumClicked (const QStringList &workspaceNames)
void plotSpectrumWithErrorsClicked (const QStringList &workspaceNames)
void plotSurfaceClicked (const QStringList &workspaceNames)
void plotWireframeClicked (const QStringList &workspaceNames)
void sampleLogsClicked (const QStringList &workspaceName)
void sampleMaterialClicked (const QStringList &workspaceNames)
void sampleShapeClicked (const QStringList &workspaceNames)
void showAlgorithmHistoryClicked (const QStringList &workspaceNames)
void showDataClicked (const QStringList &workspaceNames)
void showDetectorsClicked (const QStringList &workspaceNames)
void showInstrumentClicked (const QStringList &workspaceNames)
void sliceViewerClicked (const QStringList &workspaceName)
void superplotBinsClicked (const QStringList &workspaceNames)
void superplotBinsWithErrsClicked (const QStringList &workspaceNames)
void superplotClicked (const QStringList &workspaceNames)
void superplotWithErrsClicked (const QStringList &workspaceNames)
void treeSelectionChanged ()
void workspaceDoubleClicked (const QString &workspaceName)
Signals inherited from MantidQt::MantidWidgets::WorkspaceTreeWidget
void signalClearView ()
void signalUpdateTree (const TopLevelItems &)
Public Member Functions
void popupContextMenu () override
void setOverplotDisabled (bool disabled)
WorkspaceTreeWidgetSimple (bool viewOnly=false, QWidget *parent=nullptr)
~WorkspaceTreeWidgetSimple ()
Public Member Functions inherited from MantidQt::MantidWidgets::WorkspaceTreeWidget
bool askUserYesNo (const std::string &caption, const std::string &message) const override
void clearView () override
bool clearWorkspacesConfirmation () const override
Gets confirmation from user that they meant to press clear workspaces button.
void convertMDHistoToMatrixWorkspace () override
void convertToMatrixWorkspace () override
bool deleteConfirmation () const override
void deleteWorkspaces (const MantidQt::MantidWidgets::StringList &wsNames) override
void dropEvent (QDropEvent *de) override
Accept a drag drop event and process the data appropriately.
void enableClearButton (bool enable) override
Enables and disables the Clear Workspaces Button.
void enableDeletePrompt (bool enable) override
bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=true) override
Allows asynchronous execution of algorithms.
void filterWorkspaces (const std::string &filterText) override
std::string getFilterText () const override
MantidQt::MantidWidgets::WorkspacePresenterWN_wptr getPresenterWeakPtr () override
SaveFileType getSaveFileType () const override
Mantid::API::Workspace_sptr getSelectedWorkspace () const override
Returns a pointer to the selected workspace (the first if multiple workspaces selected)
MantidQt::MantidWidgets::StringList getSelectedWorkspaceNames () const override
Returns the names of the selected workspaces in the dock.
QStringList getSelectedWorkspaceNamesAsQList () const
SortCriteria getSortCriteria () const override
SortDirection getSortDirection () const override
bool isPromptDelete () const override
void plotSpectrum (const std::string &type) override
Plots one or more spectra from each selected workspace.
void popupContextMenu () override
void recordWorkspaceRename (const std::string &oldName, const std::string &newName) override
Save the old and the new name in m_renameMap.
void refreshWorkspaces () override
void saveToProgram () override
Saves a workspace based on the program the user chooses to save to.
void saveWorkspace (const std::string &wsName, SaveFileType type) override
void saveWorkspaces (const MantidQt::MantidWidgets::StringList &wsNames) override
void showAlgorithmHistory () override
void showBoxDataTable () override
void showColourFillPlot () override
Draw a color fill plot of the workspaces that are currently selected.
void showCriticalUserMessage (const std::string &caption, const std::string &message) const override
void showDetectorsTable () override
void showInstrumentView () override
void showListData () override
void showLiveDataDialog () override
void showLoadDialog () override
void showLogs () override
void showMDPlot () override
void showRenameDialog (const MantidQt::MantidWidgets::StringList &wsNames) override
void showSampleMaterialWindow () override
void showSliceViewer () override
void showSpectrumViewer () override
void showTransposed () override
void showWorkspaceData () override
void sortWorkspaces (SortCriteria criteria, SortDirection direction) override
WorkspaceTreeWidget (MantidQt::MantidWidgets::MantidDisplayBase *mdb, bool viewOnly=false, QWidget *parent=nullptr)
~WorkspaceTreeWidget ()
Public Member Functions inherited from MantidQt::MantidWidgets::IWorkspaceDockView
virtual bool askUserYesNo (const std::string &caption, const std::string &message) const =0
virtual void clearView ()=0
virtual bool clearWorkspacesConfirmation () const =0
virtual void convertMDHistoToMatrixWorkspace ()=0
virtual void convertToMatrixWorkspace ()=0
virtual bool deleteConfirmation () const =0
virtual void deleteWorkspaces (const StringList &wsNames)=0
virtual void enableClearButton (bool enable)=0
virtual void enableDeletePrompt (bool enable)=0
virtual bool executeAlgorithmAsync (Mantid::API::IAlgorithm_sptr alg, const bool wait=true)=0
virtual void filterWorkspaces (const std::string &filterText)=0
virtual std::string getFilterText () const =0
virtual WorkspacePresenterWN_wptr getPresenterWeakPtr ()=0
virtual SaveFileType getSaveFileType () const =0
virtual Mantid::API::Workspace_sptr getSelectedWorkspace () const =0
virtual StringList getSelectedWorkspaceNames () const =0
virtual SortCriteria getSortCriteria () const =0
virtual SortDirection getSortDirection () const =0
virtual bool isPromptDelete () const =0
virtual void plotSpectrum (const std::string &type)=0
virtual void popupContextMenu ()=0
virtual void recordWorkspaceRename (const std::string &oldName, const std::string &newName)=0
virtual void refreshWorkspaces ()=0
virtual void saveToProgram ()=0
virtual void saveWorkspace (const std::string &wsName, const SaveFileType type)=0
virtual void saveWorkspaces (const StringList &wsNames)=0
virtual void showAlgorithmHistory ()=0
virtual void showBoxDataTable ()=0
virtual void showColourFillPlot ()=0
virtual void showCriticalUserMessage (const std::string &caption, const std::string &message) const =0
virtual void showDetectorsTable ()=0
virtual void showInstrumentView ()=0
virtual void showListData ()=0
virtual void showLiveDataDialog ()=0
virtual void showLoadDialog ()=0
virtual void showLogs ()=0
virtual void showMDPlot ()=0
virtual void showRenameDialog (const StringList &wsNames)=0
virtual void showSampleMaterialWindow ()=0
virtual void showSliceViewer ()=0
virtual void showSpectrumViewer ()=0
virtual void showTransposed ()=0
virtual void showWorkspaceData ()=0
virtual void sortWorkspaces (SortCriteria criteria, SortDirection direction)=0
virtual void updateTree (const std::map< std::string, Mantid::API::Workspace_sptr > &items)=0
virtual ~IWorkspaceDockView ()
Private Slots
void onOverPlotMDHistoWorkspaceClicked ()
void onOverPlotMDHistoWorkspaceWithErrorsClicked ()
void onOverplotSpectrumClicked ()
void onOverplotSpectrumWithErrorsClicked ()
void onPlotAdvancedClicked ()
void onPlotBinClicked ()
void onPlotColorfillClicked ()
void onPlotContourClicked ()
void onPlotMDHistoWorkspaceClicked ()
void onPlotMDHistoWorkspaceWithErrorsClicked ()
void onPlotSpectrumClicked ()
void onPlotSpectrumWithErrorsClicked ()
void onPlotSurfaceClicked ()
void onPlotWireframeClicked ()
void onSampleLogsClicked ()
void onSampleMaterialClicked ()
void onSampleShapeClicked ()
void onShowAlgorithmHistoryClicked ()
void onShowDataClicked ()
void onShowDetectorsClicked ()
void onShowInstrumentClicked ()
void onSliceViewerClicked ()
void onSuperplotBinsClicked ()
void onSuperplotBinsWithErrsClicked ()
void onSuperplotClicked ()
void onSuperplotWithErrsClicked ()
Private Member Functions
void addGeneralWorkspaceActions (QMenu *menu) const
void addMatrixWorkspaceActions (QMenu *menu, const Mantid::API::MatrixWorkspace &workspace)
void addMDWorkspaceActions (QMenu *menu, const Mantid::API::IMDWorkspace &workspace)
void addTableWorkspaceActions (QMenu *menu, const Mantid::API::ITableWorkspace &workspace)
void addWorkspaceGroupActions (QMenu *menu, const Mantid::API::WorkspaceGroup &workspace)
QMenu * createMatrixWorkspacePlotMenu (QWidget *parent, bool hasMultipleBins)
QMenu * createWorkspaceContextMenu (const Mantid::API::Workspace &workspace)
Create a new QMenu object filled with appropriate items for the given workspace The created object has this as its parent and WA_DeleteOnClose set.
Private Attributes
QAction * m_overplotMDHisto1D
QAction * m_overplotMDHisto1DWithErrs
QAction * m_overplotSpectrum
QAction * m_overplotSpectrumWithErrs
QAction * m_plotAdvanced
QAction * m_plotBin
QAction * m_plotColorfill
QAction * m_plotContour
QAction * m_plotMDHisto1D
QAction * m_plotMDHisto1DWithErrs
QAction * m_plotSpectrum
QAction * m_plotSpectrumWithErrs
QAction * m_plotSurface
QAction * m_plotWireframe
QAction * m_sampleLogs
QAction * m_sampleMaterial
QAction * m_sampleShape
QAction * m_showAlgorithmHistory
QAction * m_showData
QAction * m_showDetectors
QAction * m_showInstrument
QAction * m_sliceViewer
QAction * m_superplot
QAction * m_superplotBins
QAction * m_superplotBinsWithErrs
QAction * m_superplotWithErrs
Additional Inherited Members
Public Types inherited from MantidQt::MantidWidgets::IWorkspaceDockView
enum class SaveFileType { Nexus , ASCII }
enum class SortCriteria { ByName , ByLastModified , ByMemorySize }
enum class SortDirection { Ascending , Descending }
Public Slots inherited from MantidQt::MantidWidgets::WorkspaceTreeWidget
void chooseByLastModified ()
void chooseByMemorySize ()
void chooseByName ()
void clickedWorkspace (QTreeWidgetItem *, int)
void keyPressEvent (QKeyEvent *) override
void onClickClearWorkspaces ()
Handles clear button trigger.
void onClickDeleteWorkspaces ()
Handles delete button/menu item triggers.
void onClickSaveToProgram (const QString &name)
void populateChildData (QTreeWidgetItem *item)
When an item is expanded, populate the child data for this item.
void renameWorkspace ()
void saveWorkspaceCollection ()
void sortAscending ()
void sortDescending ()
Protected Slots inherited from MantidQt::MantidWidgets::WorkspaceTreeWidget
void popupMenu (const QPoint &pos)
Handles display of the workspace context menu.
void workspaceSelected ()
Protected Attributes inherited from MantidQt::MantidWidgets::WorkspaceTreeWidget
QAction * m_delete
QMenu * m_loadMenu
QPoint m_menuPosition
QAction * m_program
QSignalMapper * m_programMapper
QAction * m_rename
QAction * m_saveNexus
QMenu * m_saveToProgram
MantidTreeWidget * m_tree
QString selectedWsName
Detailed Description
WorkspaceTreeWidget implementation for the Workbench - required for some function overides.
Definition at line 31 of file WorkspaceTreeWidgetSimple.h.
Constructor & Destructor Documentation
WorkspaceTreeWidgetSimple()
MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::WorkspaceTreeWidgetSimple (bool viewOnly = false, QWidget * parent = nullptr) explicit
Definition at line 47 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::MantidTreeWidget::m_doubleClickAction, m_overplotMDHisto1D, m_overplotMDHisto1DWithErrs, m_overplotSpectrum, m_overplotSpectrumWithErrs, m_plotAdvanced, m_plotBin, m_plotColorfill, m_plotContour, m_plotMDHisto1D, m_plotMDHisto1DWithErrs, m_plotSpectrum, m_plotSpectrumWithErrs, m_plotSurface, m_plotWireframe, m_sampleLogs, m_sampleMaterial, m_sampleShape, m_showAlgorithmHistory, m_showData, m_showDetectors, m_showInstrument, m_sliceViewer, m_superplot, m_superplotBins, m_superplotBinsWithErrs, m_superplotWithErrs, MantidQt::MantidWidgets::WorkspaceTreeWidget::m_tree, onOverPlotMDHistoWorkspaceClicked(), onOverPlotMDHistoWorkspaceWithErrorsClicked(), onOverplotSpectrumClicked(), onOverplotSpectrumWithErrorsClicked(), onPlotAdvancedClicked(), onPlotBinClicked(), onPlotColorfillClicked(), onPlotContourClicked(), onPlotMDHistoWorkspaceClicked(), onPlotMDHistoWorkspaceWithErrorsClicked(), onPlotSpectrumClicked(), onPlotSpectrumWithErrorsClicked(), onPlotSurfaceClicked(), onPlotWireframeClicked(), onSampleLogsClicked(), onSampleMaterialClicked(), onSampleShapeClicked(), onShowAlgorithmHistoryClicked(), onShowDataClicked(), onShowDetectorsClicked(), onShowInstrumentClicked(), onSliceViewerClicked(), onSuperplotBinsClicked(), onSuperplotBinsWithErrsClicked(), onSuperplotClicked(), onSuperplotWithErrsClicked(), treeSelectionChanged(), and workspaceDoubleClicked().
~WorkspaceTreeWidgetSimple()
MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::~WorkspaceTreeWidgetSimple () default
Member Function Documentation
addGeneralWorkspaceActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addGeneralWorkspaceActions (QMenu * menu) const private
Definition at line 342 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::m_delete, MantidQt::MantidWidgets::WorkspaceTreeWidget::m_rename, and MantidQt::MantidWidgets::WorkspaceTreeWidget::m_saveNexus.
Referenced by createWorkspaceContextMenu().
addMatrixWorkspaceActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addMatrixWorkspaceActions (QMenu * menu, const Mantid::API::MatrixWorkspace & workspace) private
Definition at line 249 of file WorkspaceTreeWidgetSimple.cpp.
References createMatrixWorkspacePlotMenu(), m_sampleLogs, m_sampleMaterial, m_sampleShape, m_showAlgorithmHistory, m_showData, m_showDetectors, m_showInstrument, m_sliceViewer, MantidQt::MantidWidgets::WorkspaceTreeWidget::m_tree, and workspace.
Referenced by createWorkspaceContextMenu().
addMDWorkspaceActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addMDWorkspaceActions (QMenu * menu, const Mantid::API::IMDWorkspace & workspace) private
Definition at line 280 of file WorkspaceTreeWidgetSimple.cpp.
References m_overplotMDHisto1D, m_overplotMDHisto1DWithErrs, m_plotMDHisto1D, m_plotMDHisto1DWithErrs, m_sampleLogs, m_showAlgorithmHistory, m_sliceViewer, and workspace.
Referenced by createWorkspaceContextMenu().
addTableWorkspaceActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addTableWorkspaceActions (QMenu * menu, const Mantid::API::ITableWorkspace & workspace) private
Definition at line 272 of file WorkspaceTreeWidgetSimple.cpp.
References m_showAlgorithmHistory, m_showData, m_showDetectors, and workspace.
Referenced by createWorkspaceContextMenu().
addWorkspaceGroupActions()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::addWorkspaceGroupActions (QMenu * menu, const Mantid::API::WorkspaceGroup & workspace) private
Definition at line 317 of file WorkspaceTreeWidgetSimple.cpp.
References createMatrixWorkspacePlotMenu(), m_showDetectors, and workspace.
Referenced by createWorkspaceContextMenu().
contextMenuAboutToShow
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::contextMenuAboutToShow (void) signal
Referenced by popupContextMenu().
createMatrixWorkspacePlotMenu()
QMenu * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::createMatrixWorkspacePlotMenu (QWidget * parent, bool hasMultipleBins) private
Definition at line 350 of file WorkspaceTreeWidgetSimple.cpp.
References m_overplotSpectrum, m_overplotSpectrumWithErrs, m_plotAdvanced, m_plotBin, m_plotColorfill, m_plotContour, m_plotSpectrum, m_plotSpectrumWithErrs, m_plotSurface, m_plotWireframe, m_superplot, m_superplotBins, m_superplotBinsWithErrs, and m_superplotWithErrs.
Referenced by addMatrixWorkspaceActions(), and addWorkspaceGroupActions().
createWorkspaceContextMenu()
QMenu * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::createWorkspaceContextMenu (const Mantid::API::Workspace & workspace) private
Create a new QMenu object filled with appropriate items for the given workspace The created object has this as its parent and WA_DeleteOnClose set.
Definition at line 229 of file WorkspaceTreeWidgetSimple.cpp.
References addGeneralWorkspaceActions(), addMatrixWorkspaceActions(), addMDWorkspaceActions(), addTableWorkspaceActions(), addWorkspaceGroupActions(), and workspace.
Referenced by popupContextMenu().
onOverPlotMDHistoWorkspaceClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverPlotMDHistoWorkspaceClicked () private slot
Definition at line 193 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and overplotMDHistoClicked().
Referenced by WorkspaceTreeWidgetSimple().
onOverPlotMDHistoWorkspaceWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverPlotMDHistoWorkspaceWithErrorsClicked () private slot
Definition at line 201 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and overplotMDHistoWithErrorsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onOverplotSpectrumClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverplotSpectrumClicked () private slot
Definition at line 142 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and overplotSpectrumClicked().
Referenced by WorkspaceTreeWidgetSimple().
onOverplotSpectrumWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onOverplotSpectrumWithErrorsClicked () private slot
Definition at line 150 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and overplotSpectrumWithErrorsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotAdvancedClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotAdvancedClicked () private slot
Definition at line 176 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotAdvancedClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotBinClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotBinClicked () private slot
Definition at line 140 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotBinClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotColorfillClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotColorfillClicked () private slot
Definition at line 154 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotColorfillClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotContourClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotContourClicked () private slot
Definition at line 186 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotContourClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotMDHistoWorkspaceClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotMDHistoWorkspaceClicked () private slot
Definition at line 189 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotMDHistoClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotMDHistoWorkspaceWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotMDHistoWorkspaceWithErrorsClicked () private slot
Definition at line 197 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotMDHistoWithErrorsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotSpectrumClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSpectrumClicked () private slot
Definition at line 136 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotSpectrumClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotSpectrumWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSpectrumWithErrorsClicked () private slot
Definition at line 146 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotSpectrumWithErrorsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotSurfaceClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotSurfaceClicked () private slot
Definition at line 180 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotSurfaceClicked().
Referenced by WorkspaceTreeWidgetSimple().
onPlotWireframeClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onPlotWireframeClicked () private slot
Definition at line 182 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and plotWireframeClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSampleLogsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleLogsClicked () private slot
Definition at line 158 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and sampleLogsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSampleMaterialClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleMaterialClicked () private slot
Definition at line 205 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and sampleMaterialClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSampleShapeClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSampleShapeClicked () private slot
Definition at line 209 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and sampleShapeClicked().
Referenced by WorkspaceTreeWidgetSimple().
onShowAlgorithmHistoryClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowAlgorithmHistoryClicked () private slot
Definition at line 168 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and showAlgorithmHistoryClicked().
Referenced by WorkspaceTreeWidgetSimple().
onShowDataClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowDataClicked () private slot
Definition at line 166 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and showDataClicked().
Referenced by WorkspaceTreeWidgetSimple().
onShowDetectorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowDetectorsClicked () private slot
Definition at line 172 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and showDetectorsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onShowInstrumentClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onShowInstrumentClicked () private slot
Definition at line 162 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and showInstrumentClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSliceViewerClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSliceViewerClicked () private slot
Definition at line 160 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and sliceViewerClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSuperplotBinsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotBinsClicked () private slot
Definition at line 217 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and superplotBinsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSuperplotBinsWithErrsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotBinsWithErrsClicked () private slot
Definition at line 221 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and superplotBinsWithErrsClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSuperplotClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotClicked () private slot
Definition at line 211 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and superplotClicked().
Referenced by WorkspaceTreeWidgetSimple().
onSuperplotWithErrsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::onSuperplotWithErrsClicked () private slot
Definition at line 213 of file WorkspaceTreeWidgetSimple.cpp.
References MantidQt::MantidWidgets::WorkspaceTreeWidget::getSelectedWorkspaceNamesAsQList(), and superplotWithErrsClicked().
Referenced by WorkspaceTreeWidgetSimple().
overplotMDHistoClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::overplotMDHistoClicked (const QStringList & workspaceNames) signal
Referenced by onOverPlotMDHistoWorkspaceClicked().
overplotMDHistoWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::overplotMDHistoWithErrorsClicked (const QStringList & workspaceNames) signal
Referenced by onOverPlotMDHistoWorkspaceWithErrorsClicked().
overplotSpectrumClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::overplotSpectrumClicked (const QStringList & workspaceNames) signal
Referenced by onOverplotSpectrumClicked().
overplotSpectrumWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::overplotSpectrumWithErrorsClicked (const QStringList & workspaceNames) signal
Referenced by onOverplotSpectrumWithErrorsClicked().
plotAdvancedClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotAdvancedClicked (const QStringList & workspaceNames) signal
Referenced by onPlotAdvancedClicked().
plotBinClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotBinClicked (const QStringList & workspaceNames) signal
Referenced by onPlotBinClicked().
plotColorfillClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotColorfillClicked (const QStringList & workspaceNames) signal
Referenced by onPlotColorfillClicked().
plotContourClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotContourClicked (const QStringList & workspaceNames) signal
Referenced by onPlotContourClicked().
plotMDHistoClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotMDHistoClicked (const QStringList & workspaceNames) signal
Referenced by onPlotMDHistoWorkspaceClicked().
plotMDHistoWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotMDHistoWithErrorsClicked (const QStringList & workspaceNames) signal
Referenced by onPlotMDHistoWorkspaceWithErrorsClicked().
plotSpectrumClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotSpectrumClicked (const QStringList & workspaceNames) signal
Referenced by onPlotSpectrumClicked().
plotSpectrumWithErrorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotSpectrumWithErrorsClicked (const QStringList & workspaceNames) signal
Referenced by onPlotSpectrumWithErrorsClicked().
plotSurfaceClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotSurfaceClicked (const QStringList & workspaceNames) signal
Referenced by onPlotSurfaceClicked().
plotWireframeClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::plotWireframeClicked (const QStringList & workspaceNames) signal
Referenced by onPlotWireframeClicked().
popupContextMenu()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::popupContextMenu () override virtual
Reimplemented from MantidQt::MantidWidgets::WorkspaceTreeWidget.
Definition at line 108 of file WorkspaceTreeWidgetSimple.cpp.
References contextMenuAboutToShow(), createWorkspaceContextMenu(), Mantid::Kernel::SingletonHolder< T >::Instance(), MantidQt::MantidWidgets::WorkspaceTreeWidget::m_loadMenu, MantidQt::MantidWidgets::WorkspaceTreeWidget::m_menuPosition, MantidQt::MantidWidgets::WorkspaceTreeWidget::m_tree, MantidQt::MantidWidgets::WorkspaceTreeWidget::selectedWsName, and workspace.
sampleLogsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::sampleLogsClicked (const QStringList & workspaceName) signal
Referenced by onSampleLogsClicked().
sampleMaterialClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::sampleMaterialClicked (const QStringList & workspaceNames) signal
Referenced by onSampleMaterialClicked().
sampleShapeClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::sampleShapeClicked (const QStringList & workspaceNames) signal
Referenced by onSampleShapeClicked().
setOverplotDisabled()
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::setOverplotDisabled (bool disabled)
Definition at line 103 of file WorkspaceTreeWidgetSimple.cpp.
References m_overplotSpectrum, and m_overplotSpectrumWithErrs.
showAlgorithmHistoryClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::showAlgorithmHistoryClicked (const QStringList & workspaceNames) signal
Referenced by onShowAlgorithmHistoryClicked().
showDataClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::showDataClicked (const QStringList & workspaceNames) signal
Referenced by onShowDataClicked().
showDetectorsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::showDetectorsClicked (const QStringList & workspaceNames) signal
Referenced by onShowDetectorsClicked().
showInstrumentClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::showInstrumentClicked (const QStringList & workspaceNames) signal
Referenced by onShowInstrumentClicked().
sliceViewerClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::sliceViewerClicked (const QStringList & workspaceName) signal
Referenced by onSliceViewerClicked().
superplotBinsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::superplotBinsClicked (const QStringList & workspaceNames) signal
Referenced by onSuperplotBinsClicked().
superplotBinsWithErrsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::superplotBinsWithErrsClicked (const QStringList & workspaceNames) signal
Referenced by onSuperplotBinsWithErrsClicked().
superplotClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::superplotClicked (const QStringList & workspaceNames) signal
Referenced by onSuperplotClicked().
superplotWithErrsClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::superplotWithErrsClicked (const QStringList & workspaceNames) signal
Referenced by onSuperplotWithErrsClicked().
treeSelectionChanged
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::treeSelectionChanged () signal
Referenced by WorkspaceTreeWidgetSimple().
workspaceDoubleClicked
void MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::workspaceDoubleClicked (const QString & workspaceName) signal
Referenced by WorkspaceTreeWidgetSimple().
Member Data Documentation
m_overplotMDHisto1D
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_overplotMDHisto1D private
Definition at line 117 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_overplotMDHisto1DWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_overplotMDHisto1DWithErrs private
Definition at line 117 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_overplotSpectrum
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_overplotSpectrum private
Definition at line 114 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), setOverplotDisabled(), and WorkspaceTreeWidgetSimple().
m_overplotSpectrumWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_overplotSpectrumWithErrs private
Definition at line 114 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), setOverplotDisabled(), and WorkspaceTreeWidgetSimple().
m_plotAdvanced
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotAdvanced private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotBin
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotBin private
Definition at line 114 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotColorfill
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotColorfill private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotContour
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotContour private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotMDHisto1D
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotMDHisto1D private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_plotMDHisto1DWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotMDHisto1DWithErrs private
Definition at line 117 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_plotSpectrum
QAction* MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotSpectrum private
Definition at line 114 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotSpectrumWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotSpectrumWithErrs private
Definition at line 114 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotSurface
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotSurface private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_plotWireframe
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_plotWireframe private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_sampleLogs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_sampleLogs private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_sampleMaterial
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_sampleMaterial private
Definition at line 117 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_sampleShape
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_sampleShape private
Definition at line 117 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_showAlgorithmHistory
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_showAlgorithmHistory private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), addMDWorkspaceActions(), addTableWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_showData
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_showData private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), addTableWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_showDetectors
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_showDetectors private
Definition at line 116 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), addTableWorkspaceActions(), addWorkspaceGroupActions(), and WorkspaceTreeWidgetSimple().
m_showInstrument
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_showInstrument private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_sliceViewer
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_sliceViewer private
Definition at line 115 of file WorkspaceTreeWidgetSimple.h.
Referenced by addMatrixWorkspaceActions(), addMDWorkspaceActions(), and WorkspaceTreeWidgetSimple().
m_superplot
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_superplot private
Definition at line 118 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_superplotBins
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_superplotBins private
Definition at line 118 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_superplotBinsWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_superplotBinsWithErrs private
Definition at line 118 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
m_superplotWithErrs
QAction * MantidQt::MantidWidgets::WorkspaceTreeWidgetSimple::m_superplotWithErrs private
Definition at line 118 of file WorkspaceTreeWidgetSimple.h.
Referenced by createMatrixWorkspacePlotMenu(), and WorkspaceTreeWidgetSimple().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h
qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp