Mantid: MantidQt::API::TextPropertyWidget Class Reference
MantidQt::API::TextPropertyWidget Class Reference
The most generic widgets for Property's that are only a simple string.
#include <TextPropertyWidget.h>
Public Member Functions
QWidget * getMainWidget () override
QString getValue () const override
void setValueImpl (const QString &value) override
Set the value into the GUI.
TextPropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
~TextPropertyWidget () override
Destructor.
Public Member Functions inherited from MantidQt::API::PropertyWidget
void addReplaceWSButton ()
Create and show the "Replace WS" button.
QGridLayout * getGridLayout ()
int getGridRow ()
virtual QWidget * getMainWidget ()=0
Mantid::Kernel::Property * getProperty ()
virtual QString getValue () const =0
Return the value of the property given the GUI state.
bool inGrid () const
PropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
void setEnabled (bool val)
Sets all widgets contained within to Enabled.
void setError (const QString &error)
Externally set an error string to display in the validator.
void setPreviousValue (const QString &previousValue)
Set this widget's previously-entered value.
void setValue (const QString &value)
Set the value of the property given into the GUI state.
void setVisible (bool val) override
Sets all widgets contained within to Visible.
~PropertyWidget () override
Destructor.
Protected Attributes
QLabel * m_label
Label (name of the property)
QLineEdit * m_textbox
The text box to edit.
Protected Attributes inherited from MantidQt::API::PropertyWidget
QString m_doc
Documentation string (tooltip)
QString m_enteredValue
Stored the last non-previously-entered value entered entered by the user.
QString m_error
Error message received when trying to set the value.
QGridLayout * m_gridLayout
Grid layout of the dialog to which we are adding widgets.
QMap< Info, ClickableLabel * > m_icons
Allow icon access by Info enum.
bool m_isOutputWsProp
Whether or not the property is an output workspace.
QWidget * m_parent
Parent widget to add sub-widgets to.
QString m_previousValue
Stores the previously entered value when this dialog was last open.
Mantid::Kernel::Property * m_prop
Property being looked at. This is NOT owned by the widget.
QPushButton * m_replaceWSButton
Button to "replace input workspace".
int m_row
If using the GridLayout, this is the row where the widget was inserted.
bool m_useHistory
History on/off flag.
QVector< QWidget * > m_widgets
All contained widgets.
Additional Inherited Members
Public Types inherited from MantidQt::API::PropertyWidget
enum Info { INVALID , REPLACE , RESTORE }
Public Slots inherited from MantidQt::API::PropertyWidget
void replaceWSButtonClicked ()
Deal with the "replace workspace" button being clicked.
void toggleUseHistory ()
Toggle whether or not to use the previously-entered value.
void updateIconVisibility (const QString &error="")
Update which icons should be shown.
void userEditedProperty ()
To be called when a user edits a property, as opposed to one being set programmatically.
void valueChangedSlot ()
Emits a signal that the value of the property was changed.
Signals inherited from MantidQt::API::PropertyWidget
void replaceWorkspaceName (const QString &propName)
Signal is emitted whenever someone clicks the replace WS button.
void userChangedProperty ()
void valueChanged (const QString &propName)
Signal is emitted whenever the value (as entered by the user) in the GUI changes.
Static Public Member Functions inherited from MantidQt::API::PropertyWidget
static void setFieldPlaceholderText (Mantid::Kernel::Property *prop, QLineEdit *field)
Set the placeholder text of the given field based on the default value of the given property.
Static Protected Member Functions inherited from MantidQt::API::PropertyWidget
static void setLabelFont (Mantid::Kernel::Property *prop, QWidget *label)
Set the font of the given label based on the optional/required status of the given property.
Detailed Description
The most generic widgets for Property's that are only a simple string.
Date
2012-02-16
Definition at line 22 of file TextPropertyWidget.h.
Constructor & Destructor Documentation
TextPropertyWidget()
MantidQt::API::TextPropertyWidget::TextPropertyWidget (Mantid::Kernel::Property * prop, QWidget * parent = nullptr, QGridLayout * layout = nullptr, int row = -1)
Constructor.
Definition at line 18 of file TextPropertyWidget.cpp.
References MantidQt::API::PropertyWidget::m_doc, MantidQt::API::PropertyWidget::m_gridLayout, m_label, MantidQt::API::PropertyWidget::m_parent, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::PropertyWidget::m_row, m_textbox, MantidQt::API::PropertyWidget::m_widgets, Mantid::Kernel::Property::name(), MantidQt::API::PropertyWidget::setFieldPlaceholderText(), MantidQt::API::PropertyWidget::setLabelFont(), MantidQt::API::PropertyWidget::setValue(), MantidQt::API::PropertyWidget::userEditedProperty(), and Mantid::Kernel::Property::value().
~TextPropertyWidget()
MantidQt::API::TextPropertyWidget::~TextPropertyWidget () override default
Destructor.
Member Function Documentation
getMainWidget()
QWidget * MantidQt::API::TextPropertyWidget::getMainWidget () inline override virtual
Returns
the main widget of this combo of widgets
Implements MantidQt::API::PropertyWidget.
Definition at line 33 of file TextPropertyWidget.h.
getValue()
QString MantidQt::API::TextPropertyWidget::getValue () const override virtual
Returns
the value of the property, as typed in the GUI, as a string
Implements MantidQt::API::PropertyWidget.
Definition at line 53 of file TextPropertyWidget.cpp.
References m_textbox.
setValueImpl()
void MantidQt::API::TextPropertyWidget::setValueImpl (const QString & value) override virtual
Set the value into the GUI.
Parameters
value :: string representation of the value
Implements MantidQt::API::PropertyWidget.
Definition at line 59 of file TextPropertyWidget.cpp.
References m_textbox, and value.
Member Data Documentation
m_label
QLabel* MantidQt::API::TextPropertyWidget::m_label protected
Label (name of the property)
Definition at line 37 of file TextPropertyWidget.h.
Referenced by TextPropertyWidget().
m_textbox
QLineEdit* MantidQt::API::TextPropertyWidget::m_textbox protected
The text box to edit.
Definition at line 40 of file TextPropertyWidget.h.
Referenced by MantidQt::API::FilePropertyWidget::browseClicked(), getValue(), setValueImpl(), and TextPropertyWidget().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/TextPropertyWidget.h
qt/widgets/common/src/TextPropertyWidget.cpp