Mantid: Mantid::API::FunctionGenerator Class Reference
Mantid::API::FunctionGenerator Class Reference abstract
FunctionGenerator is a partial implementation of IFunction that defines a function consisting of two parts: the source and the target.
#include <FunctionGenerator.h>
Public Member Functions
FunctionGenerator (const IFunction_sptr &source)
Constructor.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Attributes
IFunction_sptr m_source
Function that calculates parameters of the target function.
IFunction_sptr m_target
Function that actually calculates the output.
size_t m_nOwnParams
Cached number of parameters in m_source.
bool m_dirty
Flag indicating that updateTargetFunction() is required.
size_t nAttributes () const override
Returns the number of attributes associated with the function.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names.
Attribute getAttribute (const std::string &name) const override
Return a value of attribute attName.
void setAttribute (const std::string &name, const Attribute &) override
Set a value to attribute attName.
bool hasAttribute (const std::string &name) const override
Check if attribute attName exists.
std::string attributeName (size_t i) const override
Return the name of the ith attribute.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluate the function.
void init () override
overwrite IFunction base class method, which declare function parameters
void setSource (IFunction_sptr source) const
Set the source function.
virtual bool isSourceName (const std::string &aName) const
Test if a name (parameter's or attribute's) belongs to m_source.
virtual void updateTargetFunction () const =0
Update target function.
void checkTargetFunction () const
Update target function if necessary.
Overrides implementing composition of two functions:
m_source and m_target.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
double getParameter (size_t i) const override
Get i-th parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
double getParameter (const std::string &name) const override
Get parameter by name.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
size_t nParams () const override
Total number of parameters.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
void setUpForFit () override
Set up the function for a fit.
ParameterTie * getTie (size_t i) const override
Get the tie for i-th parameter.
IConstraint * getConstraint (size_t i) const override
Get the i-th constraint.
virtual void buildTargetFunction () const =0
Build target function.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Member Functions inherited from Mantid::API::IFunction
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
FunctionGenerator is a partial implementation of IFunction that defines a function consisting of two parts: the source and the target.
The source function generates the target function which in turn is used to calculate the output. Concrete functions subclassing FunctionGenerator must implement the following virtual methods:
name() category() buildTargetFunction() updateTargetFunction()
Parameters and attributes of both source and target functions become parameters (attributes) of FunctionGenerator without changing names. Virtual method isSourceName(name) decides to which function a parameter belongs to. By default if a name has the signature of a composite function (f<number>.name) then it is attributed to the target function.
Definition at line 31 of file FunctionGenerator.h.
Constructor & Destructor Documentation
FunctionGenerator()
Mantid::API::FunctionGenerator::FunctionGenerator (const IFunction_sptr & source)
Constructor.
Definition at line 18 of file FunctionGenerator.cpp.
References Mantid::API::IFunction::declareAttribute(), and m_nOwnParams.
Member Function Documentation
attributeName()
std::string Mantid::API::FunctionGenerator::attributeName (size_t i) const override virtual
Return the name of the ith attribute.
This method assumes that: The first [0,IFunction::nAttributes()) belong to the function held in this class. The next [IFunction::nAttributes, IFunction::nAttributes + m_source->nAttributes()) belong to the m_source function. And finally, the remaining attributes belong to the m_target function
Parameters
i,: Index of the attribute to return
Reimplemented from Mantid::API::IFunction.
Definition at line 273 of file FunctionGenerator.cpp.
References Mantid::API::IFunction::attributeName(), m_source, m_target, Mantid::API::IFunction::nAttributes(), and nAttributes().
buildTargetFunction()
virtual void Mantid::API::FunctionGenerator::buildTargetFunction () const pure virtual
Build target function.
Implemented in Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum, and Mantid::CurveFitting::Functions::CrystalFieldSpectrum.
checkTargetFunction()
void Mantid::API::FunctionGenerator::checkTargetFunction () const protected
Update target function if necessary.
Update spectrum function if necessary.
Definition at line 304 of file FunctionGenerator.cpp.
References m_dirty, m_target, and updateTargetFunction().
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::createEquivalentFunctions(), getAttribute(), getAttributeNames(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), hasAttribute(), hasParameter(), isExplicitlySet(), nAttributes(), nParams(), parameterDescription(), parameterIndex(), parameterName(), setAttribute(), setError(), setParameter(), setParameterDescription(), and setParameterStatus().
declareParameter()
void Mantid::API::FunctionGenerator::declareParameter (const std::string & name, double initValue = 0, const std::string & description = "") override protected virtual
Declare a new parameter.
Implements Mantid::API::IFunction.
Definition at line 209 of file FunctionGenerator.cpp.
function()
void Mantid::API::FunctionGenerator::function (const FunctionDomain & domain, FunctionValues & values) const override virtual
Evaluate the function.
Implements Mantid::API::IFunction.
Definition at line 286 of file FunctionGenerator.cpp.
References m_target, and updateTargetFunction().
getAttribute()
IFunction::Attribute Mantid::API::FunctionGenerator::getAttribute (const std::string & name) const override virtual
Return a value of attribute attName.
Reimplemented from Mantid::API::IFunction.
Definition at line 227 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::IFunction::getAttribute(), Mantid::API::IFunction::hasAttribute(), isSourceName(), m_source, and m_target.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildPhysprop(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
getAttributeNames()
std::vector< std::string > Mantid::API::FunctionGenerator::getAttributeNames () const override virtual
Returns a list of attribute names.
Reimplemented from Mantid::API::IFunction.
Definition at line 221 of file FunctionGenerator.cpp.
References checkTargetFunction(), and Mantid::API::IFunction::getAttributeNames().
Referenced by Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
getConstraint()
IConstraint * Mantid::API::FunctionGenerator::getConstraint (size_t i) const override virtual
Get the i-th constraint.
Reimplemented from Mantid::API::IFunction.
Definition at line 329 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::IFunction::getConstraint(), m_nOwnParams, m_source, and m_target.
getError() [1/2]
double Mantid::API::FunctionGenerator::getError (const std::string & name) const override virtual
Get the fitting error for a parameter by name.
Implements Mantid::API::IFunction.
Definition at line 147 of file FunctionGenerator.cpp.
References getError(), index, Mantid::API::IFunction::name(), and parameterIndex().
getError() [2/2]
double Mantid::API::FunctionGenerator::getError (size_t i) const override virtual
Get the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 137 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
Referenced by getError().
getParameter() [1/2]
double Mantid::API::FunctionGenerator::getParameter (const std::string & name) const override virtual
Get parameter by name.
Implements Mantid::API::IFunction.
Definition at line 85 of file FunctionGenerator.cpp.
References getParameter(), Mantid::API::IFunction::name(), and parameterIndex().
getParameter() [2/2]
double Mantid::API::FunctionGenerator::getParameter (size_t i) const override virtual
Get i-th parameter.
Implements Mantid::API::IFunction.
Definition at line 53 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), getParameter(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateSpectrum(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
getParameterIndex()
size_t Mantid::API::FunctionGenerator::getParameterIndex (const ParameterReference & ref) const override virtual
Return parameter index from a parameter reference.
Implements Mantid::API::IFunction.
Definition at line 189 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::ParameterReference::getLocalFunction(), Mantid::API::ParameterReference::getLocalIndex(), index, m_nOwnParams, m_target, and nParams().
getParameterStatus()
IFunction::ParameterStatus Mantid::API::FunctionGenerator::getParameterStatus (size_t i) const override protected virtual
Get status of parameter.
Implements Mantid::API::IFunction.
Definition at line 179 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
getTie()
ParameterTie * Mantid::API::FunctionGenerator::getTie (size_t i) const override virtual
Get the tie for i-th parameter.
Reimplemented from Mantid::API::IFunction.
Definition at line 314 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::IFunction::getTie(), m_nOwnParams, m_source, m_target, and Mantid::API::IFunction::tie().
hasAttribute()
bool Mantid::API::FunctionGenerator::hasAttribute (const std::string & name) const override virtual
Check if attribute attName exists.
Reimplemented from Mantid::API::IFunction.
Definition at line 254 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::IFunction::hasAttribute(), isSourceName(), m_source, and m_target.
hasParameter()
bool Mantid::API::FunctionGenerator::hasParameter (const std::string & name) const override virtual
Check if function has a parameter with this name.
Check if function has a parameter with a particular name.
Implements Mantid::API::IFunction.
Definition at line 63 of file FunctionGenerator.cpp.
References checkTargetFunction(), isSourceName(), m_source, m_target, and Mantid::API::IFunction::name().
init()
void Mantid::API::FunctionGenerator::init () override protected virtual
overwrite IFunction base class method, which declare function parameters
Reimplemented from Mantid::API::IFunction.
Reimplemented in Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum, and Mantid::CurveFitting::Functions::CrystalFieldSpectrum.
Definition at line 25 of file FunctionGenerator.cpp.
isExplicitlySet()
bool Mantid::API::FunctionGenerator::isExplicitlySet (size_t i) const override virtual
Checks if a parameter has been set explicitly.
Implements Mantid::API::IFunction.
Definition at line 127 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
isSourceName()
bool Mantid::API::FunctionGenerator::isSourceName (const std::string & aName) const protected virtual
Test if a name (parameter's or attribute's) belongs to m_source.
Parameters
aName :: A name to test.
Definition at line 296 of file FunctionGenerator.cpp.
Referenced by getAttribute(), hasAttribute(), hasParameter(), parameterIndex(), and setAttribute().
nAttributes()
size_t Mantid::API::FunctionGenerator::nAttributes () const override virtual
Returns the number of attributes associated with the function.
Reimplemented from Mantid::API::IFunction.
Definition at line 215 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_source, m_target, and Mantid::API::IFunction::nAttributes().
Referenced by attributeName().
nParams()
size_t Mantid::API::FunctionGenerator::nParams () const override virtual
Total number of parameters.
Implements Mantid::API::IFunction.
Definition at line 91 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_source, and m_target.
Referenced by getParameterIndex().
parameterDescription()
std::string Mantid::API::FunctionGenerator::parameterDescription (size_t i) const override virtual
Returns the description of parameter i.
Implements Mantid::API::IFunction.
Definition at line 117 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
parameterIndex()
size_t Mantid::API::FunctionGenerator::parameterIndex (const std::string & name) const override virtual
Returns the index of parameter name.
Implements Mantid::API::IFunction.
Definition at line 97 of file FunctionGenerator.cpp.
References checkTargetFunction(), isSourceName(), m_nOwnParams, m_source, m_target, and Mantid::API::IFunction::name().
Referenced by getError(), getParameter(), setError(), setParameter(), and setParameterDescription().
parameterName()
std::string Mantid::API::FunctionGenerator::parameterName (size_t i) const override virtual
Returns the name of parameter i.
Implements Mantid::API::IFunction.
Definition at line 107 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
setAttribute()
void Mantid::API::FunctionGenerator::setAttribute (const std::string & name, const Attribute & att) override virtual
Set a value to attribute attName.
Reimplemented from Mantid::API::IFunction.
Reimplemented in Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum.
Definition at line 239 of file FunctionGenerator.cpp.
References checkTargetFunction(), Mantid::API::IFunction::hasAttribute(), isSourceName(), m_dirty, m_source, m_target, and Mantid::API::IFunction::setAttribute().
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute().
setError() [1/2]
void Mantid::API::FunctionGenerator::setError (const std::string & name, double err) override virtual
Set the fitting error for a parameter by name.
Implements Mantid::API::IFunction.
Definition at line 163 of file FunctionGenerator.cpp.
References index, Mantid::API::IFunction::name(), parameterIndex(), and setError().
setError() [2/2]
void Mantid::API::FunctionGenerator::setError (size_t i, double err) override virtual
Set the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 153 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
Referenced by setError().
setParameter() [1/2]
void Mantid::API::FunctionGenerator::setParameter (const std::string & name, const double & value, bool explicitlySet = true) override virtual
Set parameter by name.
Implements Mantid::API::IFunction.
Definition at line 73 of file FunctionGenerator.cpp.
References Mantid::API::IFunction::name(), parameterIndex(), setParameter(), and value.
setParameter() [2/2]
void Mantid::API::FunctionGenerator::setParameter (size_t i, const double & value, bool explicitlySet = true) override virtual
Set i-th parameter.
Implements Mantid::API::IFunction.
Definition at line 32 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_dirty, m_nOwnParams, m_source, m_target, and value.
Referenced by setParameter().
setParameterDescription() [1/2]
void Mantid::API::FunctionGenerator::setParameterDescription (const std::string & name, const std::string & description) override virtual
Set description of parameter by name.
Implements Mantid::API::IFunction.
Definition at line 79 of file FunctionGenerator.cpp.
References Mantid::API::IFunction::name(), parameterIndex(), and setParameterDescription().
setParameterDescription() [2/2]
void Mantid::API::FunctionGenerator::setParameterDescription (size_t i, const std::string & description) override virtual
Set i-th parameter description.
Implements Mantid::API::IFunction.
Definition at line 43 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
Referenced by setParameterDescription().
setParameterStatus()
void Mantid::API::FunctionGenerator::setParameterStatus (size_t i, IFunction::ParameterStatus status) override protected virtual
Change status of parameter.
Implements Mantid::API::IFunction.
Definition at line 169 of file FunctionGenerator.cpp.
References checkTargetFunction(), m_nOwnParams, m_source, and m_target.
setSource()
void Mantid::API::FunctionGenerator::setSource (IFunction_sptr source) const protected
Set the source function.
Parameters
source :: New source function.
Definition at line 29 of file FunctionGenerator.cpp.
References m_source.
setUpForFit()
void Mantid::API::FunctionGenerator::setUpForFit () override virtual
Set up the function for a fit.
Reimplemented from Mantid::API::IFunction.
Definition at line 203 of file FunctionGenerator.cpp.
References Mantid::API::IFunction::setUpForFit(), and updateTargetFunction().
updateTargetFunction()
virtual void Mantid::API::FunctionGenerator::updateTargetFunction () const protected pure virtual
Update target function.
Implemented in Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum, and Mantid::CurveFitting::Functions::CrystalFieldSpectrum.
Referenced by checkTargetFunction(), function(), and setUpForFit().
Member Data Documentation
m_dirty
bool Mantid::API::FunctionGenerator::m_dirty mutable protected
Flag indicating that updateTargetFunction() is required.
Definition at line 133 of file FunctionGenerator.h.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), checkTargetFunction(), setAttribute(), setParameter(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateTargetFunction(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
m_nOwnParams
size_t Mantid::API::FunctionGenerator::m_nOwnParams mutable protected
Cached number of parameters in m_source.
Definition at line 131 of file FunctionGenerator.h.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::calcExcitations(), FunctionGenerator(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), parameterDescription(), parameterIndex(), parameterName(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
m_source
IFunction_sptr Mantid::API::FunctionGenerator::m_source mutable protected
Function that calculates parameters of the target function.
Definition at line 127 of file FunctionGenerator.h.
Referenced by attributeName(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), getAttribute(), getConstraint(), getError(), getParameter(), getParameterStatus(), getTie(), hasAttribute(), hasParameter(), isExplicitlySet(), nAttributes(), nParams(), parameterDescription(), parameterIndex(), parameterName(), setAttribute(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::setAttribute(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), setSource(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
m_target
IFunction_sptr Mantid::API::FunctionGenerator::m_target mutable protected
Function that actually calculates the output.
Definition at line 129 of file FunctionGenerator.h.
Referenced by attributeName(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::buildTargetFunction(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::buildTargetFunction(), checkTargetFunction(), function(), getAttribute(), getConstraint(), getError(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::getNumberDomains(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), hasAttribute(), hasParameter(), isExplicitlySet(), nAttributes(), nParams(), parameterDescription(), parameterIndex(), parameterName(), setAttribute(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::updateTargetFunction(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::updateTargetFunction().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/FunctionGenerator.h
Framework/API/src/FunctionGenerator.cpp