Mantid: Mantid::IndirectFitDataCreationHelper Namespace Reference
Mantid::IndirectFitDataCreationHelper Namespace Reference
Classes
struct AreSpectraEqual
This is used to compare Spectra which is implemented as a boost::variant.
struct SetUpADSWithWorkspace
Simple struct used to access features of the ADS No destructor so ensure you tearDown the ADS.
Functions
Mantid::API::WorkspaceGroup_sptr createGroupWorkspace (std::size_t const &numberOfWorkspaces, int const &numberOfSpectra, int const &numberOfBins=10)
Mantid::API::WorkspaceGroup_sptr createGroupWorkspaceWithTextAxes (std::size_t const &numberOfWorkspaces, std::vector< std::string > const &labels, int const &numberOfSpectra, int const &numberOfBins=10)
Mantid::API::MatrixWorkspace_sptr createInstrumentWorkspace (int const &xLength, int const &yLength)
Mantid::API::MatrixWorkspace_sptr createWorkspace (int const &numberOfSpectra, int const &numberOfBins=10)
Functions used in the creation of workspaces.
Mantid::API::MatrixWorkspace_sptr createWorkspaceWithBinValues (int const &numberOfSpectra, std::vector< double > const &labels, int const &numberOfBins=10)
Mantid::API::MatrixWorkspace_sptr createWorkspaceWithInelasticInstrument (int const &yLength)
Mantid::API::MatrixWorkspace_sptr createWorkspaceWithInstrument (int const &xLength, int const &yLength)
Mantid::API::MatrixWorkspace_sptr createWorkspaceWithTextAxis (int const &numberOfSpectra, std::vector< std::string > const &labels, int const &numberOfBins=10)
int const END_X_COLUMN (3)
int const EXCLUDE_REGION_COLUMN (4)
Mantid::API::NumericAxis * getNumericAxis (int const &numberOfLabels, std::vector< double > const &values)
Mantid::API::TextAxis * getTextAxis (int const &numberOfSpectra, std::vector< std::string > const &labels)
Mantid::API::MatrixWorkspace_sptr setWorkspaceBinEdges (Mantid::API::MatrixWorkspace_sptr workspace, int const &xLength, int const &yLength)
Mantid::API::MatrixWorkspace_sptr setWorkspaceBinEdges (Mantid::API::MatrixWorkspace_sptr workspace, int const &yLength, Mantid::HistogramData::BinEdges const &binEdges)
Mantid::API::MatrixWorkspace_sptr setWorkspaceEFixed (Mantid::API::MatrixWorkspace_sptr workspace, int const &xLength)
Mantid::API::MatrixWorkspace_sptr setWorkspaceProperties (Mantid::API::MatrixWorkspace_sptr workspace, int const &xLength, int const &yLength)
int const START_X_COLUMN (2)
Commonly used constant variables.
Function Documentation
createGroupWorkspace()
WorkspaceGroup_sptr Mantid::IndirectFitDataCreationHelper::createGroupWorkspace (std::size_t const & numberOfWorkspaces, int const & numberOfSpectra, int const & numberOfBins = 10)
Definition at line 42 of file IndirectFitDataCreationHelper.cpp.
References Mantid::API::createWorkspace().
createGroupWorkspaceWithTextAxes()
WorkspaceGroup_sptr Mantid::IndirectFitDataCreationHelper::createGroupWorkspaceWithTextAxes (std::size_t const & numberOfWorkspaces, std::vector< std::string > const & labels, int const & numberOfSpectra, int const & numberOfBins = 10)
Definition at line 50 of file IndirectFitDataCreationHelper.cpp.
References createWorkspaceWithTextAxis().
createInstrumentWorkspace()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createInstrumentWorkspace (int const & xLength, int const & yLength)
Definition at line 17 of file IndirectFitDataCreationHelper.cpp.
References WorkspaceCreationHelper::create2DWorkspaceWithFullInstrument().
Referenced by createWorkspaceWithInstrument().
createWorkspace()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createWorkspace (int const & numberOfSpectra, int const & numberOfBins = 10)
Functions used in the creation of workspaces.
Definition at line 13 of file IndirectFitDataCreationHelper.cpp.
References WorkspaceCreationHelper::create2DWorkspace().
createWorkspaceWithBinValues()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createWorkspaceWithBinValues (int const & numberOfSpectra, std::vector< double > const & labels, int const & numberOfBins = 10)
Definition at line 32 of file IndirectFitDataCreationHelper.cpp.
References Mantid::API::createWorkspace(), getNumericAxis(), and workspace.
createWorkspaceWithInelasticInstrument()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createWorkspaceWithInelasticInstrument (int const & yLength)
Definition at line 106 of file IndirectFitDataCreationHelper.cpp.
References WorkspaceCreationHelper::createProcessedInelasticWS().
createWorkspaceWithInstrument()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createWorkspaceWithInstrument (int const & xLength, int const & yLength)
Definition at line 100 of file IndirectFitDataCreationHelper.cpp.
References createInstrumentWorkspace(), setWorkspaceProperties(), and workspace.
createWorkspaceWithTextAxis()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::createWorkspaceWithTextAxis (int const & numberOfSpectra, std::vector< std::string > const & labels, int const & numberOfBins = 10)
Definition at line 22 of file IndirectFitDataCreationHelper.cpp.
References Mantid::API::createWorkspace(), getTextAxis(), and workspace.
Referenced by createGroupWorkspaceWithTextAxes().
END_X_COLUMN()
int const Mantid::IndirectFitDataCreationHelper::END_X_COLUMN (3)
EXCLUDE_REGION_COLUMN()
int const Mantid::IndirectFitDataCreationHelper::EXCLUDE_REGION_COLUMN (4)
getNumericAxis()
NumericAxis * Mantid::IndirectFitDataCreationHelper::getNumericAxis (int const & numberOfLabels, std::vector< double > const & values)
Definition at line 66 of file IndirectFitDataCreationHelper.cpp.
References index.
Referenced by createWorkspaceWithBinValues().
getTextAxis()
TextAxis * Mantid::IndirectFitDataCreationHelper::getTextAxis (int const & numberOfSpectra, std::vector< std::string > const & labels)
Definition at line 59 of file IndirectFitDataCreationHelper.cpp.
References index.
Referenced by createWorkspaceWithTextAxis().
setWorkspaceBinEdges() [1/2]
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::setWorkspaceBinEdges (Mantid::API::MatrixWorkspace_sptr workspace, int const & xLength, int const & yLength)
Definition at line 86 of file IndirectFitDataCreationHelper.cpp.
References setWorkspaceBinEdges(), and workspace.
setWorkspaceBinEdges() [2/2]
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::setWorkspaceBinEdges (Mantid::API::MatrixWorkspace_sptr workspace, int const & yLength, Mantid::HistogramData::BinEdges const & binEdges)
Definition at line 79 of file IndirectFitDataCreationHelper.cpp.
References workspace.
Referenced by setWorkspaceBinEdges(), and setWorkspaceProperties().
setWorkspaceEFixed()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::setWorkspaceEFixed (Mantid::API::MatrixWorkspace_sptr workspace, int const & xLength)
Definition at line 73 of file IndirectFitDataCreationHelper.cpp.
References workspace.
Referenced by setWorkspaceProperties().
setWorkspaceProperties()
MatrixWorkspace_sptr Mantid::IndirectFitDataCreationHelper::setWorkspaceProperties (Mantid::API::MatrixWorkspace_sptr workspace, int const & xLength, int const & yLength)
Definition at line 94 of file IndirectFitDataCreationHelper.cpp.
References setWorkspaceBinEdges(), setWorkspaceEFixed(), and workspace.
Referenced by createWorkspaceWithInstrument().
START_X_COLUMN()
int const Mantid::IndirectFitDataCreationHelper::START_X_COLUMN (2)
Commonly used constant variables.