Mantid: MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter Class Reference
MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter Class Reference
#include <JobTreeViewSignalAdapter.h>
Signals
void appendAndEditAtChildRowRequested ()
void appendAndEditAtRowBelowRequested ()
void cellTextChanged (MantidQt::MantidWidgets::Batch::RowLocation const &itemIndex, int column, std::string const &oldValue, std::string const &newValue)
void copyRowsRequested ()
void cutRowsRequested ()
void editAtRowAboveRequested ()
void filterReset ()
void pasteRowsRequested ()
void removeRowsRequested (std::vector< MantidQt::MantidWidgets::Batch::RowLocation > const &locationsOfRowsToRemove)
void rowInserted (MantidQt::MantidWidgets::Batch::RowLocation const &newRowLocation)
void selectionChanged ()
Public Member Functions
JobTreeViewSignalAdapter (JobTreeView &view, QObject *parent=nullptr)
void notifyAppendAndEditAtChildRowRequested () override
void notifyAppendAndEditAtRowBelowRequested () override
void notifyCellTextChanged (RowLocation const &itemIndex, int column, std::string const &oldValue, std::string const &newValue) override
void notifyCopyRowsRequested () override
void notifyCutRowsRequested () override
void notifyEditAtRowAboveRequested () override
void notifyFilterReset () override
void notifyPasteRowsRequested () override
void notifyRemoveRowsRequested (std::vector< RowLocation > const &locationsOfRowsToRemove) override
void notifyRowInserted (RowLocation const &newRowLocation) override
void notifySelectionChanged () override
Public Member Functions inherited from MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber
virtual void notifyAppendAndEditAtChildRowRequested ()=0
virtual void notifyAppendAndEditAtRowBelowRequested ()=0
virtual void notifyCellTextChanged (RowLocation const &itemIndex, int column, std::string const &oldValue, std::string const &newValue)=0
virtual void notifyCopyRowsRequested ()=0
virtual void notifyCutRowsRequested ()=0
virtual void notifyEditAtRowAboveRequested ()=0
virtual void notifyFilterReset ()=0
virtual void notifyPasteRowsRequested ()=0
virtual void notifyRemoveRowsRequested (std::vector< RowLocation > const &locationsOfRowsToRemove)=0
virtual void notifyRowInserted (RowLocation const &newRowLocation)=0
virtual void notifySelectionChanged ()=0
virtual ~JobTreeViewSubscriber ()=default
Detailed Description
Definition at line 17 of file JobTreeViewSignalAdapter.h.
Constructor & Destructor Documentation
JobTreeViewSignalAdapter()
MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::JobTreeViewSignalAdapter (JobTreeView & view, QObject * parent = nullptr)
Definition at line 10 of file JobTreeViewSignalAdapter.cpp.
References MantidQt::MantidWidgets::Batch::JobTreeView::subscribe().
Member Function Documentation
appendAndEditAtChildRowRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::appendAndEditAtChildRowRequested () signal
Referenced by notifyAppendAndEditAtChildRowRequested().
appendAndEditAtRowBelowRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::appendAndEditAtRowBelowRequested () signal
Referenced by notifyAppendAndEditAtRowBelowRequested().
cellTextChanged
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::cellTextChanged (MantidQt::MantidWidgets::Batch::RowLocation const & itemIndex, int column, std::string const & oldValue, std::string const & newValue) signal
Referenced by notifyCellTextChanged().
copyRowsRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::copyRowsRequested () signal
Referenced by notifyCopyRowsRequested().
cutRowsRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::cutRowsRequested () signal
Referenced by notifyCutRowsRequested().
editAtRowAboveRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::editAtRowAboveRequested () signal
Referenced by notifyEditAtRowAboveRequested().
filterReset
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::filterReset () signal
Referenced by notifyFilterReset().
notifyAppendAndEditAtChildRowRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyAppendAndEditAtChildRowRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 27 of file JobTreeViewSignalAdapter.cpp.
References appendAndEditAtChildRowRequested().
notifyAppendAndEditAtRowBelowRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyAppendAndEditAtRowBelowRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 29 of file JobTreeViewSignalAdapter.cpp.
References appendAndEditAtRowBelowRequested().
notifyCellTextChanged()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyCellTextChanged (RowLocation const & itemIndex, int column, std::string const & oldValue, std::string const & newValue) override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 16 of file JobTreeViewSignalAdapter.cpp.
References cellTextChanged().
notifyCopyRowsRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyCopyRowsRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 37 of file JobTreeViewSignalAdapter.cpp.
References copyRowsRequested().
notifyCutRowsRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyCutRowsRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 39 of file JobTreeViewSignalAdapter.cpp.
References cutRowsRequested().
notifyEditAtRowAboveRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyEditAtRowAboveRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 31 of file JobTreeViewSignalAdapter.cpp.
References editAtRowAboveRequested().
notifyFilterReset()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyFilterReset () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 43 of file JobTreeViewSignalAdapter.cpp.
References filterReset().
notifyPasteRowsRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyPasteRowsRequested () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 41 of file JobTreeViewSignalAdapter.cpp.
References pasteRowsRequested().
notifyRemoveRowsRequested()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyRemoveRowsRequested (std::vector< RowLocation > const & locationsOfRowsToRemove) override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 33 of file JobTreeViewSignalAdapter.cpp.
References removeRowsRequested().
notifyRowInserted()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifyRowInserted (RowLocation const & newRowLocation) override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 23 of file JobTreeViewSignalAdapter.cpp.
References rowInserted().
notifySelectionChanged()
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::notifySelectionChanged () override virtual
Implements MantidQt::MantidWidgets::Batch::JobTreeViewSubscriber.
Definition at line 21 of file JobTreeViewSignalAdapter.cpp.
References selectionChanged().
pasteRowsRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::pasteRowsRequested () signal
Referenced by notifyPasteRowsRequested().
removeRowsRequested
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::removeRowsRequested (std::vector< MantidQt::MantidWidgets::Batch::RowLocation > const & locationsOfRowsToRemove) signal
Referenced by notifyRemoveRowsRequested().
rowInserted
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::rowInserted (MantidQt::MantidWidgets::Batch::RowLocation const & newRowLocation) signal
Referenced by notifyRowInserted().
selectionChanged
void MantidQt::MantidWidgets::Batch::JobTreeViewSignalAdapter::selectionChanged () signal
Referenced by notifySelectionChanged().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/JobTreeViewSignalAdapter.h
qt/widgets/common/src/Batch/JobTreeViewSignalAdapter.cpp