Mantid: Mantid::Crystal::FindSXPeaksHelper::StrongestPeaksStrategy Class Reference
Mantid::Crystal::FindSXPeaksHelper::StrongestPeaksStrategy Class Reference
#include <FindSXPeaksHelper.h>
Public Member Functions
PeakList dofindSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const HistogramData::HistogramE &e, Bound low, Bound high, const int workspaceIndex) const override
StrongestPeaksStrategy (const BackgroundStrategy *backgroundStrategy, const API::SpectrumInfo &spectrumInfo, const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
Public Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
PeakList findSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const HistogramData::HistogramE &e, const int workspaceIndex) const
PeakFindingStrategy (const BackgroundStrategy *backgroundStrategy, const API::SpectrumInfo &spectrumInfo, const double minValue=EMPTY_DBL(), const double maxValue=EMPTY_DBL(), const XAxisUnit units=XAxisUnit::TOF)
void setMinNBinsPerPeak (int minBinsPerPeak)
virtual ~PeakFindingStrategy ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
double calculatePhi (size_t workspaceIndex) const
Calculates the average phi value if the workspace contains multiple detectors per spectrum, or returns the value of phi if it is a single detector to spectrum mapping.
PeakList convertToSXPeaks (const HistogramData::HistogramX &x, const HistogramData::HistogramY &y, const std::vector< std::unique_ptr< PeakContainer > > &peaks, const int workspaceIndex) const
double convertToTOF (const double xValue, const size_t workspaceIndex) const
void filterPeaksForMinBins (std::vector< std::unique_ptr< PeakContainer > > &inputPeakList) const
BoundsIterator getBounds (const HistogramData::HistogramX &x) const
double getXValue (const HistogramData::HistogramX &x, const size_t peakLocation) const
Protected Attributes inherited from Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy
const BackgroundStrategy * m_backgroundStrategy
const double m_maxValue = EMPTY_DBL()
int m_minNBinsPerPeak = EMPTY_INT()
const double m_minValue = EMPTY_DBL()
const API::SpectrumInfo & m_spectrumInfo
const XAxisUnit m_units
Detailed Description
Definition at line 184 of file FindSXPeaksHelper.h.
Constructor & Destructor Documentation
StrongestPeaksStrategy()
Mantid::Crystal::FindSXPeaksHelper::StrongestPeaksStrategy::StrongestPeaksStrategy (const BackgroundStrategy * backgroundStrategy, const API::SpectrumInfo & spectrumInfo, const double minValue = EMPTY_DBL(), const double maxValue = EMPTY_DBL(), const XAxisUnit units = XAxisUnit::TOF)
Definition at line 414 of file FindSXPeaksHelper.cpp.
Member Function Documentation
dofindSXPeaks()
PeakList Mantid::Crystal::FindSXPeaksHelper::StrongestPeaksStrategy::dofindSXPeaks (const HistogramData::HistogramX & x, const HistogramData::HistogramY & y, const HistogramData::HistogramE & e, Bound low, Bound high, const int workspaceIndex) const override virtual
Implements Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy.
Definition at line 419 of file FindSXPeaksHelper.cpp.
References Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::calculatePhi(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::convertToTOF(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::getXValue(), Mantid::Crystal::FindSXPeaksHelper::BackgroundStrategy::isBelowBackground(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::m_backgroundStrategy, Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::m_spectrumInfo, Mantid::Geometry::x, and Mantid::Geometry::y.
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
Framework/Crystal/src/FindSXPeaksHelper.cpp