Mantid: Mantid::DataHandling::ANSTO::FastReadOnlyFile Class Reference
Mantid::DataHandling::ANSTO::FastReadOnlyFile Class Reference
#include <LoadANSTOHelper.h>
Public Member Functions
void close ()
FastReadOnlyFile (const char *filename)
FastReadOnlyFile (const FastReadOnlyFile &)=delete
void * handle () const
FastReadOnlyFile & operator= (FastReadOnlyFile)=delete
bool read (void *buffer, uint32_t size)
bool seek (int64_t offset, int whence, int64_t *newPosition=nullptr)
~FastReadOnlyFile ()
Private Attributes
FILE * m_handle
Detailed Description
Definition at line 142 of file LoadANSTOHelper.h.
Constructor & Destructor Documentation
FastReadOnlyFile() [1/2]
Mantid::DataHandling::ANSTO::FastReadOnlyFile::FastReadOnlyFile (const char * filename)
Definition at line 176 of file LoadANSTOHelper.cpp.
References m_handle.
~FastReadOnlyFile()
Mantid::DataHandling::ANSTO::FastReadOnlyFile::~FastReadOnlyFile ()
Definition at line 177 of file LoadANSTOHelper.cpp.
References close().
FastReadOnlyFile() [2/2]
Mantid::DataHandling::ANSTO::FastReadOnlyFile::FastReadOnlyFile (const FastReadOnlyFile &) delete
Member Function Documentation
close()
void Mantid::DataHandling::ANSTO::FastReadOnlyFile::close ()
Definition at line 179 of file LoadANSTOHelper.cpp.
References m_handle.
Referenced by Mantid::DataHandling::ANSTO::Tar::File::close(), and ~FastReadOnlyFile().
handle()
void * Mantid::DataHandling::ANSTO::FastReadOnlyFile::handle () const
Definition at line 178 of file LoadANSTOHelper.cpp.
References m_handle.
Referenced by Mantid::DataHandling::ANSTO::Tar::File::File().
operator=()
FastReadOnlyFile & Mantid::DataHandling::ANSTO::FastReadOnlyFile::operator= (FastReadOnlyFile) delete
read()
bool Mantid::DataHandling::ANSTO::FastReadOnlyFile::read (void * buffer, uint32_t size)
Definition at line 183 of file LoadANSTOHelper.cpp.
References m_handle.
Referenced by Mantid::DataHandling::ANSTO::Tar::File::File(), Mantid::DataHandling::ANSTO::Tar::File::read(), and Mantid::DataHandling::ANSTO::Tar::File::read_byte().
seek()
bool Mantid::DataHandling::ANSTO::FastReadOnlyFile::seek (int64_t offset, int whence, int64_t * newPosition = nullptr)
Definition at line 186 of file LoadANSTOHelper.cpp.
References m_handle.
Referenced by Mantid::DataHandling::ANSTO::Tar::File::File(), Mantid::DataHandling::ANSTO::Tar::File::select(), and Mantid::DataHandling::ANSTO::Tar::File::skip().
Member Data Documentation
m_handle
FILE* Mantid::DataHandling::ANSTO::FastReadOnlyFile::m_handle private
Definition at line 147 of file LoadANSTOHelper.h.
Referenced by close(), FastReadOnlyFile(), handle(), read(), and seek().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadANSTOHelper.h
Framework/DataHandling/src/LoadANSTOHelper.cpp