Mantid: Framework/PythonInterface/mantid/api/src/Exports/ExperimentInfo.cpp File Reference
ExperimentInfo.cpp File Reference
#include "MantidAPI/ExperimentInfo.h"
#include "MantidAPI/InstrumentFileFinder.h"
#include "MantidAPI/Run.h"
#include "MantidAPI/Sample.h"
#include "MantidAPI/SpectrumInfo.h"
#include "MantidGeometry/IDTypes.h"
#include "MantidGeometry/Instrument/ComponentInfo.h"
#include "MantidGeometry/Instrument/DetectorInfo.h"
#include "MantidKernel/WarningSuppressions.h"
#include "MantidPythonInterface/core/Converters/PySequenceToVector.h"
#include "MantidPythonInterface/core/Converters/ToPyList.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/Policies/RemoveConst.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/list.hpp>
#include <boost/python/overloads.hpp>
#include <boost/python/register_ptr_to_python.hpp>
Functions
void export_ExperimentInfo ()
std::string getInstrumentFilenameWarn (const std::string &instName, const std::string &date="")
list getResourceFilenames (const std::string &prefix, const list &fileFormats, const list &directoryNames, const std::string &date)
Converter from C++ signature to python signature.
Function Documentation
export_ExperimentInfo()
void export_ExperimentInfo ()
Definition at line 66 of file ExperimentInfo.cpp.
References Mantid::API::ExperimentInfo::componentInfo(), Mantid::API::ExperimentInfo::detectorInfo(), Mantid::API::ExperimentInfo::getEFixed(), Mantid::API::ExperimentInfo::getEMode(), Mantid::API::ExperimentInfo::getInstrument(), Mantid::API::InstrumentFileFinder::getInstrumentFilename(), getResourceFilenames(), Mantid::API::ExperimentInfo::getRunNumber(), Mantid::API::ExperimentInfo::mutableRun(), Mantid::API::ExperimentInfo::mutableSample(), Mantid::API::ExperimentInfo::run(), Mantid::API::ExperimentInfo::sample(), Mantid::API::ExperimentInfo::setEFixed(), and Mantid::API::ExperimentInfo::spectrumInfo().
getInstrumentFilenameWarn()
std::string getInstrumentFilenameWarn (const std::string & instName, const std::string & date = "")
Definition at line 46 of file ExperimentInfo.cpp.
References Mantid::API::InstrumentFileFinder::getInstrumentFilename().
getResourceFilenames()
list getResourceFilenames (const std::string & prefix, const list & fileFormats, const list & directoryNames, const std::string & date)
Converter from C++ signature to python signature.
Definition at line 39 of file ExperimentInfo.cpp.
References Mantid::API::InstrumentFileFinder::getResourceFilenames().
Referenced by export_ExperimentInfo().