Mantid: Mantid::Kernel::MersenneTwister Class Reference
Mantid::Kernel::MersenneTwister Class Reference final
This implements the the Mersenne Twister 19937 pseudo-random number generator algorithm as a specialzation of the PseudoRandomNumberGenerator interface.
#include <MersenneTwister.h>
Public Member Functions
double max () const override
Return the maximum value of the range.
MersenneTwister ()
Construct the generator using time stamp for the initial seed.
MersenneTwister (const double start, const double end)
Construct the generator with an initial range and default seed.
MersenneTwister (const MersenneTwister &)=delete
MersenneTwister (const size_t seedValue)
Construct the generator with an initial seed.
MersenneTwister (const size_t seedValue, const double start, const double end)
Construct the generator with an initial seed and range.
double min () const override
Return the minimum value of the range.
int nextInt (int start, int end) override
Return the next integer in the sequence within the given range.
double nextValue () override
Generate the next random number in the sequence within the given range default range.
double nextValue (double start, double end) override
Generate the next random number in the sequence within the given range.
MersenneTwister & operator= (const MersenneTwister &)=delete
void restart () override
Resets the generator.
void restore () override
Restores the generator to the last saved point, or the beginning if nothing has been saved.
void save () override
Saves the current state of the generator.
void setRange (const double start, const double end) override
Sets the range of the subsequent calls to next.
void setSeed (const size_t seedValue) override
Set the random number seed.
Public Member Functions inherited from Mantid::Kernel::PseudoRandomNumberGenerator
void generateNextPoint () override
Generates the next point.
virtual double max () const =0
Return the maximum value of the range.
virtual double min () const =0
Return the minimum value of the range.
virtual int nextInt (int start, int end)=0
Return the next integer in the sequence.
virtual double nextValue ()=0
Return the next double in the sequence.
virtual double nextValue (double start, double end)=0
Return the next double in the sequence overriding the default range.
double operator() ()
Return next random value.
PseudoRandomNumberGenerator & operator= (const PseudoRandomNumberGenerator &)=delete
Disable assignment operator.
PseudoRandomNumberGenerator ()
Default constructor setting the dimension to 1.
PseudoRandomNumberGenerator (const PseudoRandomNumberGenerator &)=delete
Disable copy operator.
virtual void setRange (const double start, const double end)=0
Sets the range of the subsequent calls to nextValue;.
virtual void setSeed (const size_t seedValue)=0
Set the random number seed.
Public Member Functions inherited from Mantid::Kernel::NDRandomNumberGenerator
NDRandomNumberGenerator ()=delete
Disable default constructor.
NDRandomNumberGenerator (const NDRandomNumberGenerator &)=delete
Disable copy operator.
NDRandomNumberGenerator (const unsigned int ndims)
Constructor.
const std::vector< double > & nextPoint ()
Generate the next set of values that form a point in ND space.
unsigned int numberOfDimensions () const
Returns the number of dimensions the point will be generated in, i.e.
NDRandomNumberGenerator & operator= (const NDRandomNumberGenerator &)=delete
Disable assignment operator.
virtual void restart ()=0
Restarts the generator from the beginning of the sequence.
virtual void restore ()=0
Restores the generator to the last saved point, or the beginning if nothing has been saved.
virtual void save ()=0
Saves the current state of the generator.
virtual ~NDRandomNumberGenerator ()=default
Virtual destructor to ensure that all inheriting classes have one.
Private Attributes
double m_end
Maximum in range.
std::mt19937 m_engine
The engine.
std::unique_ptr< std::mt19937 > m_savedEngine
A generator that will take the value when save is requested.
std::mt19937::result_type m_seed
The current seed.
double m_start
Minimum in range.
std::uniform_real_distribution< double > uniformRealDistribution
Uniform Real distribution.
Additional Inherited Members
Public Types inherited from Mantid::Kernel::PseudoRandomNumberGenerator
using result_type = double
Result (output) value type.
Protected Member Functions inherited from Mantid::Kernel::NDRandomNumberGenerator
void cacheGeneratedValue (const size_t index, const double value)
Cache a value for a given dimension index, i.e. 0->ND-1.
void cacheNextPoint (const std::vector< double > &nextPoint)
Cache the while point in one go.
virtual void generateNextPoint ()=0
Generate the next point. Override this in you concrete implementation.
std::vector< double > & getNextPointCache ()
Some generators need direct access to the cache.
Detailed Description
This implements the the Mersenne Twister 19937 pseudo-random number generator algorithm as a specialzation of the PseudoRandomNumberGenerator interface.
Definition at line 24 of file MersenneTwister.h.
Constructor & Destructor Documentation
MersenneTwister() [1/5]
Mantid::Kernel::MersenneTwister::MersenneTwister ()
Construct the generator using time stamp for the initial seed.
Construct the generator time stamp for the initial seed.
The range is set to [0.0, 1.0]
Definition at line 32 of file MersenneTwister.cpp.
MersenneTwister() [2/5]
Mantid::Kernel::MersenneTwister::MersenneTwister (const double start, const double end)
Construct the generator with an initial range and default seed.
Constructor taking a range.
Parameters
start :: The minimum value a generated number should take
end :: The maximum value a generated number should take
Definition at line 39 of file MersenneTwister.cpp.
MersenneTwister() [3/5]
Mantid::Kernel::MersenneTwister::MersenneTwister (const size_t seedValue) explicit
Construct the generator with an initial seed.
Constructor taking a seed value.
It can be reseeded using setSeed.
Sets the range to [0.0,1.0]
Parameters
seedValue :: The initial seed
Definition at line 26 of file MersenneTwister.cpp.
MersenneTwister() [4/5]
Mantid::Kernel::MersenneTwister::MersenneTwister (const size_t seedValue, const double start, const double end)
Construct the generator with an initial seed and range.
Constructor taking a seed value and a range.
Parameters
seedValue :: The initial seed
start :: The minimum value a generated number should take
end :: The maximum value a generated number should take
Definition at line 48 of file MersenneTwister.cpp.
References setSeed().
MersenneTwister() [5/5]
Mantid::Kernel::MersenneTwister::MersenneTwister (const MersenneTwister &) delete
Member Function Documentation
max()
double Mantid::Kernel::MersenneTwister::max () const inline override virtual
Return the maximum value of the range.
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 63 of file MersenneTwister.h.
min()
double Mantid::Kernel::MersenneTwister::min () const inline override virtual
Return the minimum value of the range.
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 61 of file MersenneTwister.h.
nextInt()
int Mantid::Kernel::MersenneTwister::nextInt (int start, int end) override virtual
Return the next integer in the sequence within the given range.
Returns the next integer in the pseudo-random sequence generated by the Mersenne Twister 19937 algorithm.
Parameters
start Start of the requested range
end End of the requested range
Returns
An integer in the defined range
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 81 of file MersenneTwister.cpp.
References m_engine.
nextValue() [1/2]
double Mantid::Kernel::MersenneTwister::nextValue () inline override virtual
Generate the next random number in the sequence within the given range default range.
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 46 of file MersenneTwister.h.
Referenced by WorkspaceCreationHelper::addNoise(), WorkspaceCreationHelper::create1DWorkspaceRand(), WorkspaceCreationHelper::createRandomEventWorkspace(), and Mantid::Kernel::Matrix< T >::setRandom().
nextValue() [2/2]
double Mantid::Kernel::MersenneTwister::nextValue (double start, double end) inline override virtual
Generate the next random number in the sequence within the given range.
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 48 of file MersenneTwister.h.
operator=()
MersenneTwister & Mantid::Kernel::MersenneTwister::operator= (const MersenneTwister &) delete
restart()
void Mantid::Kernel::MersenneTwister::restart () override virtual
Resets the generator.
Resets the generator using the value given at the last call to setSeed.
Implements Mantid::Kernel::NDRandomNumberGenerator.
Definition at line 88 of file MersenneTwister.cpp.
References m_seed, and setSeed().
Referenced by restore().
restore()
void Mantid::Kernel::MersenneTwister::restore () override virtual
Restores the generator to the last saved point, or the beginning if nothing has been saved.
Implements Mantid::Kernel::NDRandomNumberGenerator.
Definition at line 95 of file MersenneTwister.cpp.
References m_engine, m_savedEngine, and restart().
save()
void Mantid::Kernel::MersenneTwister::save () override virtual
Saves the current state of the generator.
Implements Mantid::Kernel::NDRandomNumberGenerator.
Definition at line 91 of file MersenneTwister.cpp.
References m_engine, and m_savedEngine.
setRange()
void Mantid::Kernel::MersenneTwister::setRange (const double start, const double end) override virtual
Sets the range of the subsequent calls to next.
Sets the range of the subsequent calls to nextValue()
Parameters
start :: The lowest value a call to nextValue() will produce
end :: The largest value a call to nextValue() will produce
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 68 of file MersenneTwister.cpp.
References m_end, m_start, and uniformRealDistribution.
setSeed()
void Mantid::Kernel::MersenneTwister::setSeed (const size_t seedValue) override virtual
Set the random number seed.
(Re-)seed the generator.
This resets the current saved state
Parameters
seedValue :: A seed for the generator
Implements Mantid::Kernel::PseudoRandomNumberGenerator.
Definition at line 57 of file MersenneTwister.cpp.
References m_engine, m_savedEngine, and m_seed.
Referenced by MersenneTwister(), and restart().
Member Data Documentation
m_end
double Mantid::Kernel::MersenneTwister::m_end private
Maximum in range.
Definition at line 73 of file MersenneTwister.h.
Referenced by setRange().
m_engine
std::mt19937 Mantid::Kernel::MersenneTwister::m_engine private
The engine.
Definition at line 67 of file MersenneTwister.h.
Referenced by nextInt(), restore(), save(), and setSeed().
m_savedEngine
std::unique_ptr<std::mt19937> Mantid::Kernel::MersenneTwister::m_savedEngine private
A generator that will take the value when save is requested.
Pointer so that it is only instantiated when required
Definition at line 78 of file MersenneTwister.h.
Referenced by restore(), save(), and setSeed().
m_seed
std::mt19937::result_type Mantid::Kernel::MersenneTwister::m_seed private
The current seed.
Definition at line 75 of file MersenneTwister.h.
Referenced by restart(), and setSeed().
m_start
double Mantid::Kernel::MersenneTwister::m_start private
Minimum in range.
Definition at line 71 of file MersenneTwister.h.
Referenced by setRange().
uniformRealDistribution
std::uniform_real_distribution<double> Mantid::Kernel::MersenneTwister::uniformRealDistribution private
Uniform Real distribution.
Definition at line 69 of file MersenneTwister.h.
Referenced by setRange().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MersenneTwister.h
Framework/Kernel/src/MersenneTwister.cpp