Mantid: Mantid::Geometry::vtkGeometryCacheWriter Class Reference
Mantid::Geometry::vtkGeometryCacheWriter Class Reference
Writes the Geometry from Object to Cache.
#include <vtkGeometryCacheWriter.h>
Public Member Functions
void addObject (CSGObject const *obj)
Adds the geometry of the Object to the document.
vtkGeometryCacheWriter & operator= (const vtkGeometryCacheWriter)=delete
vtkGeometryCacheWriter (const vtkGeometryCacheWriter &)=delete
vtkGeometryCacheWriter (std::string)
Constructor.
void write ()
Write the XML to a file.
~vtkGeometryCacheWriter ()
Destructor.
Private Member Functions
void createVTKFileHeader ()
creates VTK XML header <VTKFile type="PolyData" version="1.0" byte_order="LittleEndian"> <PolyData> </PolyData> </VTKFile>
void Init ()
Initialises the XML Document with the required vtk XML Headings.
Private Attributes
Poco::XML::Document * m_doc
The XML document.
std::string m_filename
The file name.
Poco::XML::Element * m_root
The root XML element.
Detailed Description
Writes the Geometry from Object to Cache.
Author
Srikanth Nagella
Date
January 2009
Version
1.0
This class writes the geometry (triangles) cached from Object to the vtk format file.
Definition at line 32 of file vtkGeometryCacheWriter.h.
Constructor & Destructor Documentation
vtkGeometryCacheWriter() [1/2]
Mantid::Geometry::vtkGeometryCacheWriter::vtkGeometryCacheWriter (std::string filename)
Constructor.
Definition at line 43 of file vtkGeometryCacheWriter.cpp.
References Init().
~vtkGeometryCacheWriter()
Mantid::Geometry::vtkGeometryCacheWriter::~vtkGeometryCacheWriter ()
Destructor.
Definition at line 51 of file vtkGeometryCacheWriter.cpp.
References m_doc, and m_root.
vtkGeometryCacheWriter() [2/2]
Mantid::Geometry::vtkGeometryCacheWriter::vtkGeometryCacheWriter (const vtkGeometryCacheWriter &) delete
Member Function Documentation
addObject()
void Mantid::Geometry::vtkGeometryCacheWriter::addObject (CSGObject const * obj)
Adds the geometry of the Object to the document.
Parameters
obj :: The object to add
Definition at line 83 of file vtkGeometryCacheWriter.cpp.
References m_doc, m_root, name, and obj.
createVTKFileHeader()
void Mantid::Geometry::vtkGeometryCacheWriter::createVTKFileHeader () private
creates VTK XML header <VTKFile type="PolyData" version="1.0" byte_order="LittleEndian"> <PolyData> </PolyData> </VTKFile>
Definition at line 70 of file vtkGeometryCacheWriter.cpp.
References m_doc, and m_root.
Referenced by Init().
Init()
void Mantid::Geometry::vtkGeometryCacheWriter::Init () private
Initialises the XML Document with the required vtk XML Headings.
Definition at line 59 of file vtkGeometryCacheWriter.cpp.
References createVTKFileHeader(), m_doc, and m_root.
Referenced by vtkGeometryCacheWriter().
operator=()
vtkGeometryCacheWriter & Mantid::Geometry::vtkGeometryCacheWriter::operator= (const vtkGeometryCacheWriter) delete
write()
void Mantid::Geometry::vtkGeometryCacheWriter::write ()
Write the XML to a file.
Write the XML to the file.
Definition at line 165 of file vtkGeometryCacheWriter.cpp.
References Mantid::Kernel::Logger::error(), Mantid::Geometry::g_log, Mantid::Kernel::Logger::information(), m_doc, and m_filename.
Member Data Documentation
m_doc
Poco::XML::Document* Mantid::Geometry::vtkGeometryCacheWriter::m_doc private
The XML document.
Definition at line 34 of file vtkGeometryCacheWriter.h.
Referenced by addObject(), createVTKFileHeader(), Init(), write(), and ~vtkGeometryCacheWriter().
m_filename
std::string Mantid::Geometry::vtkGeometryCacheWriter::m_filename private
The file name.
Definition at line 36 of file vtkGeometryCacheWriter.h.
Referenced by write().
m_root
Poco::XML::Element* Mantid::Geometry::vtkGeometryCacheWriter::m_root private
The root XML element.
Definition at line 35 of file vtkGeometryCacheWriter.h.
Referenced by addObject(), createVTKFileHeader(), Init(), and ~vtkGeometryCacheWriter().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Rendering/vtkGeometryCacheWriter.h
Framework/Geometry/src/Rendering/vtkGeometryCacheWriter.cpp