Mantid: MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView Class Reference
MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView Class Reference
Attribute visitor to create a QtProperty.
Public Member Functions
CreateAttributePropertyForFunctionTreeView (FunctionTreeView *browser, QtProperty *parent, const QString &attName)
Public Member Functions inherited from Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >
FunctionTreeView::AProperty operator() (const bool &b) const
implements static_visitor's operator() for bool
FunctionTreeView::AProperty operator() (const double &d) const
implements static_visitor's operator() for double
FunctionTreeView::AProperty operator() (const int &i) const
implements static_visitor's operator() for int
FunctionTreeView::AProperty operator() (const std::string &str) const
implements static_visitor's operator() for std::string
FunctionTreeView::AProperty operator() (const std::vector< double > &v) const
implements static_visitor's operator() for vector
virtual ~ConstAttributeVisitor ()=default
Virtual destructor.
Protected Member Functions
FunctionTreeView::AProperty apply (const bool &b) const override
Create bool property.
FunctionTreeView::AProperty apply (const double &d) const override
Create double property.
FunctionTreeView::AProperty apply (const int &i) const override
Create int property.
FunctionTreeView::AProperty apply (const std::string &str) const override
Create string property.
FunctionTreeView::AProperty apply (const std::vector< double > &v) const override
Create vector property.
Protected Member Functions inherited from Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >
virtual FunctionTreeView::AProperty apply (const bool &i) const=0
Implement this mathod to access attribute as bool.
virtual FunctionTreeView::AProperty apply (const double &d) const=0
Implement this mathod to access attribute as double.
virtual FunctionTreeView::AProperty apply (const int &i) const=0
Implement this mathod to access attribute as int.
virtual FunctionTreeView::AProperty apply (const std::string &str) const=0
Implement this mathod to access attribute as string.
virtual FunctionTreeView::AProperty apply (const std::vector< double > &) const=0
Implement this mathod to access attribute as vector.
void evaluateValidator (T1 &inputData) const
Evaluates the validator associated with attribute this visitor is to visit.
Private Attributes
QString m_attName
FunctionTreeView * m_browser
QtProperty * m_parent
Additional Inherited Members
Protected Attributes inherited from Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >
Mantid::Kernel::IValidator_sptr m_validator
Validator against which to evaluate attribute value to set.
Detailed Description
Attribute visitor to create a QtProperty.
Depending on the attribute type the appropriate apply() method is used.
Definition at line 469 of file FunctionTreeView.cpp.
Constructor & Destructor Documentation
CreateAttributePropertyForFunctionTreeView()
MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::CreateAttributePropertyForFunctionTreeView (FunctionTreeView * browser, QtProperty * parent, const QString & attName) inline
Definition at line 472 of file FunctionTreeView.cpp.
References m_browser, MantidQt::MantidWidgets::FunctionTreeView::m_functionManager, and m_parent.
Member Function Documentation
apply() [1/5]
FunctionTreeView::AProperty MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::apply (const bool & b) const inline override protected virtual
Create bool property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >.
Definition at line 525 of file FunctionTreeView.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::addProperty(), m_attName, MantidQt::MantidWidgets::FunctionTreeView::m_attributeBoolManager, m_browser, and m_parent.
apply() [2/5]
FunctionTreeView::AProperty MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::apply (const double & d) const inline override protected virtual
Create double property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >.
Definition at line 509 of file FunctionTreeView.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::addProperty(), Mantid::Geometry::d, m_attName, MantidQt::MantidWidgets::FunctionTreeView::m_attributeDoubleManager, m_browser, and m_parent.
apply() [3/5]
FunctionTreeView::AProperty MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::apply (const int & i) const inline override protected virtual
Create int property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >.
Definition at line 517 of file FunctionTreeView.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::addProperty(), m_attName, MantidQt::MantidWidgets::FunctionTreeView::m_attributeIntManager, m_browser, and m_parent.
apply() [4/5]
FunctionTreeView::AProperty MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::apply (const std::string & str) const inline override protected virtual
Create string property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >.
Definition at line 483 of file FunctionTreeView.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::addProperty(), m_attName, MantidQt::MantidWidgets::FunctionTreeView::m_attributeStringManager, m_browser, MantidQt::MantidWidgets::FunctionTreeView::m_filenameManager, MantidQt::MantidWidgets::FunctionTreeView::m_formulaManager, m_parent, and MantidQt::MantidWidgets::FunctionTreeView::m_workspaceManager.
apply() [5/5]
FunctionTreeView::AProperty MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::apply (const std::vector< double > & v) const inline override protected virtual
Create vector property.
Implements Mantid::API::IFunction::ConstAttributeVisitor< FunctionTreeView::AProperty >.
Definition at line 533 of file FunctionTreeView.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::addProperty(), MantidQt::MantidWidgets::FunctionTreeView::AProperty::item, m_attName, MantidQt::MantidWidgets::FunctionTreeView::m_attributeSizeManager, MantidQt::MantidWidgets::FunctionTreeView::m_attributeVectorDoubleManager, MantidQt::MantidWidgets::FunctionTreeView::m_attributeVectorManager, MantidQt::MantidWidgets::FunctionTreeView::m_browser, m_browser, and m_parent.
Member Data Documentation
m_attName
QString MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::m_attName private
Definition at line 560 of file FunctionTreeView.cpp.
Referenced by apply().
m_browser
FunctionTreeView* MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::m_browser private
Definition at line 558 of file FunctionTreeView.cpp.
Referenced by apply(), and CreateAttributePropertyForFunctionTreeView().
m_parent
QtProperty* MantidQt::MantidWidgets::CreateAttributePropertyForFunctionTreeView::m_parent private
Definition at line 559 of file FunctionTreeView.cpp.
Referenced by apply(), and CreateAttributePropertyForFunctionTreeView().
The documentation for this class was generated from the following file:
qt/widgets/common/src/FunctionTreeView.cpp