Mantid: Mantid::Algorithms::FFTSmooth::PropertyNames Namespace Reference
Mantid::Algorithms::FFTSmooth::PropertyNames Namespace Reference
Functions
std::string const ALL_SPECTRA ("AllSpectra")
std::string const FILTER ("Filter")
std::string const IGNORE_X_BINS ("IgnoreXBins")
std::string const INPUT_WKSP ("InputWorkspace")
std::string const OUTPUT_WKSP ("OutputWorkspace")
std::string const PARAMS ("Params")
std::string const WKSP_INDEX ("WorkspaceIndex")
Function Documentation
ALL_SPECTRA()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::ALL_SPECTRA ("AllSpectra") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().
FILTER()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::FILTER ("Filter") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().
IGNORE_X_BINS()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::IGNORE_X_BINS ("IgnoreXBins") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::actuallyValidateInputs(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().
INPUT_WKSP()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::INPUT_WKSP ("InputWorkspace") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::actuallyValidateInputs(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::init(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::validateInputs().
OUTPUT_WKSP()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::OUTPUT_WKSP ("OutputWorkspace") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().
PARAMS()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::PARAMS ("Params") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::actuallyValidateInputs(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().
WKSP_INDEX()
std::string const Mantid::Algorithms::FFTSmooth::PropertyNames::WKSP_INDEX ("WorkspaceIndex") inline private
Referenced by Mantid::Algorithms::FFTSmooth::FFTSmooth2::actuallyValidateInputs(), Mantid::Algorithms::FFTSmooth::FFTSmooth2::exec(), and Mantid::Algorithms::FFTSmooth::FFTSmooth2::init().