Mantid: Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType > Struct Template Reference
Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType > Struct Template Reference
A specialisation of PropertyValueHander to handle coercing a Python value into a C++ sequence/array property.
#include <SequenceTypeHandler.h>
Public Member Functions
std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator, const unsigned int direction) const override
Call to create a name property where the value is some container type.
void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::object &value) const override
Call to set a named property where the value is some container type.
Public Member Functions inherited from Mantid::PythonInterface::Registry::TypedPropertyValueHandler< ContainerType >
std::unique_ptr< Kernel::Property > create (const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator, const unsigned int direction) const override
Create a PropertyWithValue from the given python object value.
void set (Kernel::IPropertyManager *alg, const std::string &name, const boost::python::object &value) const override
Set function to handle Python -> C++ calls and get the correct type.
Public Member Functions inherited from Mantid::PythonInterface::Registry::PropertyValueHandler
virtual ~PropertyValueHandler ()=default
Virtual Destructor.
Additional Inherited Members
Public Types inherited from Mantid::PythonInterface::Registry::TypedPropertyValueHandler< ContainerType >
using HeldType = ContainerType
Type required by TypeRegistry framework.
Detailed Description
template<typename ContainerType>
struct Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType >
A specialisation of PropertyValueHander to handle coercing a Python value into a C++ sequence/array property.
The template type ContainerType should contain a type called value_type indicating the element type.
Definition at line 19 of file SequenceTypeHandler.h.
Member Function Documentation
create()
template<typename ContainerType > std::unique_ptr< Kernel::Property > Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType >::create (const std::string & name, const boost::python::object & defaultValue, const boost::python::object & validator, const unsigned int direction) const override virtual
Call to create a name property where the value is some container type.
Create a PropertyWithValue from the given python object value.
Parameters
name :: The name of the property
defaultValue :: The defaultValue of the property. The object attempts to extract a value of type ContainerType from the python object
validator :: A python object pointing to a validator instance, which can be None.
direction :: The direction of the property
Returns
A pointer to a newly constructed property instance
Implements Mantid::PythonInterface::Registry::PropertyValueHandler.
Definition at line 81 of file SequenceTypeHandler.cpp.
References Mantid::Kernel::IValidator::clone(), Mantid::PythonInterface::isNone(), and name.
set()
template<typename ContainerType > void Mantid::PythonInterface::Registry::SequenceTypeHandler< ContainerType >::set (Kernel::IPropertyManager * alg, const std::string & name, const boost::python::object & value) const override virtual
Call to set a named property where the value is some container type.
Set function to handle Python -> C++ calls to a property manager and get the correct type.
Parameters
alg :: A pointer to an IPropertyManager
name :: The name of the property
value :: A boost python object that stores the container values
Implements Mantid::PythonInterface::Registry::PropertyValueHandler.
Definition at line 45 of file SequenceTypeHandler.cpp.
References Mantid::PythonInterface::NDArray::check(), name, Mantid::Kernel::IPropertyManager::setProperty(), and value.
The documentation for this struct was generated from the following files:
Framework/PythonInterface/mantid/kernel/inc/MantidPythonInterface/kernel/Registry/SequenceTypeHandler.h
Framework/PythonInterface/mantid/kernel/src/Registry/SequenceTypeHandler.cpp