Mantid: MantidQt::API::QtJobRunner Class Reference
MantidQt::API::QtJobRunner Class Reference
#include <QtJobRunner.h>
Public Member Functions
void cancelAlgorithmQueue () override
void clearAlgorithmQueue () override
void executeAlgorithm (MantidQt::API::IConfiguredAlgorithm_sptr algorithm) override
void executeAlgorithmQueue () override
QtJobRunner (bool const stopOnFailure=false)
void setAlgorithmQueue (std::deque< MantidQt::API::IConfiguredAlgorithm_sptr > algorithms) override
void subscribe (JobRunnerSubscriber *notifyee) override
Public Member Functions inherited from MantidQt::API::IJobRunner
virtual ~IJobRunner ()=default
Private Slots
void onAlgorithmComplete (MantidQt::API::IConfiguredAlgorithm_sptr algorithm)
void onAlgorithmError (MantidQt::API::IConfiguredAlgorithm_sptr algorithm, const std::string &errorMessage)
void onAlgorithmStarted (MantidQt::API::IConfiguredAlgorithm_sptr algorithm)
void onBatchCancelled ()
void onBatchComplete (bool error)
Private Member Functions
void connectBatchAlgoRunnerSlots ()
Private Attributes
MantidQt::API::BatchAlgorithmRunner m_batchAlgoRunner
JobRunnerSubscriber * m_notifyee
Detailed Description
Definition at line 22 of file QtJobRunner.h.
Constructor & Destructor Documentation
QtJobRunner()
MantidQt::API::QtJobRunner::QtJobRunner (bool const stopOnFailure = false)
Definition at line 18 of file QtJobRunner.cpp.
References connectBatchAlgoRunnerSlots(), m_batchAlgoRunner, and MantidQt::API::BatchAlgorithmRunner::stopOnFailure().
Member Function Documentation
cancelAlgorithmQueue()
void MantidQt::API::QtJobRunner::cancelAlgorithmQueue () override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 38 of file QtJobRunner.cpp.
References MantidQt::API::BatchAlgorithmRunner::cancelBatch(), and m_batchAlgoRunner.
clearAlgorithmQueue()
void MantidQt::API::QtJobRunner::clearAlgorithmQueue () override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 26 of file QtJobRunner.cpp.
References MantidQt::API::BatchAlgorithmRunner::clearQueue(), and m_batchAlgoRunner.
connectBatchAlgoRunnerSlots()
void MantidQt::API::QtJobRunner::connectBatchAlgoRunnerSlots () private
Definition at line 40 of file QtJobRunner.cpp.
References m_batchAlgoRunner, onAlgorithmComplete(), onAlgorithmError(), onAlgorithmStarted(), onBatchCancelled(), and onBatchComplete().
Referenced by QtJobRunner().
executeAlgorithm()
void MantidQt::API::QtJobRunner::executeAlgorithm (MantidQt::API::IConfiguredAlgorithm_sptr algorithm) override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 34 of file QtJobRunner.cpp.
References MantidQt::API::BatchAlgorithmRunner::executeAlgorithmAsync(), and m_batchAlgoRunner.
executeAlgorithmQueue()
void MantidQt::API::QtJobRunner::executeAlgorithmQueue () override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 32 of file QtJobRunner.cpp.
References MantidQt::API::BatchAlgorithmRunner::executeBatchAsync(), and m_batchAlgoRunner.
onAlgorithmComplete
void MantidQt::API::QtJobRunner::onAlgorithmComplete (MantidQt::API::IConfiguredAlgorithm_sptr algorithm) private slot
Definition at line 59 of file QtJobRunner.cpp.
References m_notifyee, and MantidQt::API::JobRunnerSubscriber::notifyAlgorithmComplete().
Referenced by connectBatchAlgoRunnerSlots().
onAlgorithmError
void MantidQt::API::QtJobRunner::onAlgorithmError (MantidQt::API::IConfiguredAlgorithm_sptr algorithm, const std::string & errorMessage) private slot
Definition at line 63 of file QtJobRunner.cpp.
References m_notifyee, and MantidQt::API::JobRunnerSubscriber::notifyAlgorithmError().
Referenced by connectBatchAlgoRunnerSlots().
onAlgorithmStarted
void MantidQt::API::QtJobRunner::onAlgorithmStarted (MantidQt::API::IConfiguredAlgorithm_sptr algorithm) private slot
Definition at line 55 of file QtJobRunner.cpp.
References m_notifyee, and MantidQt::API::JobRunnerSubscriber::notifyAlgorithmStarted().
Referenced by connectBatchAlgoRunnerSlots().
onBatchCancelled
void MantidQt::API::QtJobRunner::onBatchCancelled () private slot
Definition at line 53 of file QtJobRunner.cpp.
References m_notifyee, and MantidQt::API::JobRunnerSubscriber::notifyBatchCancelled().
Referenced by connectBatchAlgoRunnerSlots().
onBatchComplete
void MantidQt::API::QtJobRunner::onBatchComplete (bool error) private slot
Definition at line 51 of file QtJobRunner.cpp.
References error, m_notifyee, and MantidQt::API::JobRunnerSubscriber::notifyBatchComplete().
Referenced by connectBatchAlgoRunnerSlots().
setAlgorithmQueue()
void MantidQt::API::QtJobRunner::setAlgorithmQueue (std::deque< MantidQt::API::IConfiguredAlgorithm_sptr > algorithms) override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 28 of file QtJobRunner.cpp.
References m_batchAlgoRunner, and MantidQt::API::BatchAlgorithmRunner::setQueue().
subscribe()
void MantidQt::API::QtJobRunner::subscribe (JobRunnerSubscriber * notifyee) override virtual
Implements MantidQt::API::IJobRunner.
Definition at line 24 of file QtJobRunner.cpp.
References m_notifyee.
Member Data Documentation
m_batchAlgoRunner
MantidQt::API::BatchAlgorithmRunner MantidQt::API::QtJobRunner::m_batchAlgoRunner private
Definition at line 41 of file QtJobRunner.h.
Referenced by cancelAlgorithmQueue(), clearAlgorithmQueue(), connectBatchAlgoRunnerSlots(), executeAlgorithm(), executeAlgorithmQueue(), QtJobRunner(), and setAlgorithmQueue().
m_notifyee
JobRunnerSubscriber* MantidQt::API::QtJobRunner::m_notifyee private
Definition at line 42 of file QtJobRunner.h.
Referenced by onAlgorithmComplete(), onAlgorithmError(), onAlgorithmStarted(), onBatchCancelled(), onBatchComplete(), and subscribe().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/QtJobRunner.h
qt/widgets/common/src/QtJobRunner.cpp