Mantid: Mantid::API::WorkspaceHelpers Struct Reference
Mantid::API::WorkspaceHelpers Struct Reference
A collection of static functions for use with workspaces.
#include <WorkspaceOpOverloads.h>
Static Public Member Functions
static void makeDistribution (const MatrixWorkspace_sptr &workspace, const bool forwards=true)
Divides the data in a workspace by the bin width to make it a distribution.
static bool matchingBins (const MatrixWorkspace &ws1, const MatrixWorkspace &ws2, const bool firstOnly=false)
Checks whether the bins (X values) of two workspace are the same.
static bool sharedXData (const MatrixWorkspace &WS)
Checks whether all the X vectors in a workspace are the same one underneath.
Detailed Description
A collection of static functions for use with workspaces.
Author
Russell Taylor, Tessella Support Services plc
Date
19/09/2008
Definition at line 55 of file WorkspaceOpOverloads.h.
Member Function Documentation
makeDistribution()
void Mantid::API::WorkspaceHelpers::makeDistribution (const MatrixWorkspace_sptr & workspace, const bool forwards = true) static
Divides the data in a workspace by the bin width to make it a distribution.
Can also reverse this operation (i.e. multiply by the bin width). Sets the isDistribution() flag accordingly.
Parameters
workspace :: The workspace on which to carry out the operation
forwards :: If true (the default) divides by bin width, if false multiplies
Definition at line 441 of file WorkspaceOpOverloads.cpp.
References workspace.
Referenced by Mantid::Algorithms::GetEi2::calculatePeakPosition(), Mantid::Algorithms::ConvertFromDistribution::exec(), Mantid::Algorithms::ConvertToDistribution::exec(), Mantid::Algorithms::InterpolatingRebin::exec(), and Mantid::Algorithms::GetEi::getPeakCentre().
matchingBins()
bool Mantid::API::WorkspaceHelpers::matchingBins (const MatrixWorkspace & ws1, const MatrixWorkspace & ws2, const bool firstOnly = false) static
Checks whether the bins (X values) of two workspace are the same.
Parameters
ws1 :: The first workspace
ws2 :: The second workspace
firstOnly :: If true, only the first spectrum is checked. If false (the default), all spectra are checked and the two workspaces must have the same number of spectra
Returns
True if the test passes
Definition at line 369 of file WorkspaceOpOverloads.cpp.
References Mantid::API::MatrixWorkspace::getNumberHistograms(), sharedXData(), Mantid::API::MatrixWorkspace::size(), and Mantid::API::MatrixWorkspace::x().
Referenced by Mantid::Algorithms::PointByPointVCorrection::check_validity(), Mantid::Algorithms::MergeRuns::checkRebinning(), Mantid::Algorithms::BinaryOperation::checkSizeCompatibility(), Mantid::Algorithms::Divide::checkSizeCompatibility(), Mantid::Algorithms::Multiply::checkSizeCompatibility(), Mantid::Algorithms::CalculateTransmission::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::NormaliseToMonitor::getMonitorWorkspace(), and Mantid::Algorithms::Divide::setOutputUnits().
sharedXData()
bool Mantid::API::WorkspaceHelpers::sharedXData (const MatrixWorkspace & WS) static
Checks whether all the X vectors in a workspace are the same one underneath.
Definition at line 424 of file WorkspaceOpOverloads.cpp.
References Mantid::API::MatrixWorkspace::getNumberHistograms(), and Mantid::API::MatrixWorkspace::x().
Referenced by Mantid::Algorithms::XDataConverter::exec(), and matchingBins().
The documentation for this struct was generated from the following files:
Framework/API/inc/MantidAPI/WorkspaceOpOverloads.h
Framework/API/src/WorkspaceOpOverloads.cpp