Mantid: Mantid::DataHandling::ReadMaterial::MaterialParameters Struct Reference
Mantid::DataHandling::ReadMaterial::MaterialParameters Struct Reference
This struct contains the parameters for constructing a material, and gives them a default value for ease of testing.
#include <ReadMaterial.h>
Public Attributes
int atomicNumber = 0
The atomic number to set, defaults to 0.
std::string attenuationProfileFileName = ""
The name or path of a file containing an attenuation profile.
double attenuationXSection = EMPTY_DBL()
The absorption cross section to set, defaults to EMPTY_DBL()
std::string chemicalSymbol = ""
The chemical formula to set, defaults to the empty string.
double coherentXSection = EMPTY_DBL()
The coherent scattering cross section to set, defaults to EMPTY_DBL()
double incoherentXSection = EMPTY_DBL()
The incoherent scattering cross section to set, defaults to EMPTY_DBL()
double mass = EMPTY_DBL()
The sample mass to set, defaults to EMPTY_DBL()
double massDensity = EMPTY_DBL()
The sample mass density to set, defaults to EMPTY_DBL()
int massNumber = 0
The mass number to set, defaults to 0.
double numberDensity = EMPTY_DBL()
The sample number density to set, defaults to EMPTY_DBL()
double numberDensityEffective = EMPTY_DBL()
The sample effective number density.
Kernel::MaterialBuilder::NumberDensityUnit numberDensityUnit = Kernel::MaterialBuilder::NumberDensityUnit::Atoms
A flag indicating the unit of sampleNumberDensity.
double packingFraction = EMPTY_DBL()
The sample packing fraction.
double scatteringXSection = EMPTY_DBL()
The total scattering cross section to set, defaults to EMPTY_DBL()
double unitCellVolume = EMPTY_DBL()
The unit cell volume to set, defaults to EMPTY_DBL()
double volume = EMPTY_DBL()
The sample volume to set, defaults to EMPTY_DBL()
std::string xRayAttenuationProfileFileName = ""
The name or path of a file containing an x ray attenuation profile.
double zParameter = EMPTY_DBL()
The zParameter to set, defaults to EMPTY_DBL()
Detailed Description
This struct contains the parameters for constructing a material, and gives them a default value for ease of testing.
Definition at line 32 of file ReadMaterial.h.
Member Data Documentation
atomicNumber
int Mantid::DataHandling::ReadMaterial::MaterialParameters::atomicNumber = 0
The atomic number to set, defaults to 0.
Definition at line 36 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
attenuationProfileFileName
std::string Mantid::DataHandling::ReadMaterial::MaterialParameters::attenuationProfileFileName = ""
The name or path of a file containing an attenuation profile.
Definition at line 64 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
attenuationXSection
double Mantid::DataHandling::ReadMaterial::MaterialParameters::attenuationXSection = EMPTY_DBL()
The absorption cross section to set, defaults to EMPTY_DBL()
Definition at line 60 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
chemicalSymbol
std::string Mantid::DataHandling::ReadMaterial::MaterialParameters::chemicalSymbol = ""
The chemical formula to set, defaults to the empty string.
Definition at line 34 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
coherentXSection
double Mantid::DataHandling::ReadMaterial::MaterialParameters::coherentXSection = EMPTY_DBL()
The coherent scattering cross section to set, defaults to EMPTY_DBL()
Definition at line 56 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
incoherentXSection
double Mantid::DataHandling::ReadMaterial::MaterialParameters::incoherentXSection = EMPTY_DBL()
The incoherent scattering cross section to set, defaults to EMPTY_DBL()
Definition at line 58 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
mass
double Mantid::DataHandling::ReadMaterial::MaterialParameters::mass = EMPTY_DBL()
The sample mass to set, defaults to EMPTY_DBL()
Definition at line 52 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), and Mantid::DataHandling::SetSampleMaterial::validateInputs().
massDensity
double Mantid::DataHandling::ReadMaterial::MaterialParameters::massDensity = EMPTY_DBL()
The sample mass density to set, defaults to EMPTY_DBL()
Definition at line 50 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
massNumber
int Mantid::DataHandling::ReadMaterial::MaterialParameters::massNumber = 0
The mass number to set, defaults to 0.
Definition at line 38 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
numberDensity
double Mantid::DataHandling::ReadMaterial::MaterialParameters::numberDensity = EMPTY_DBL()
The sample number density to set, defaults to EMPTY_DBL()
Definition at line 40 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
numberDensityEffective
double Mantid::DataHandling::ReadMaterial::MaterialParameters::numberDensityEffective = EMPTY_DBL()
The sample effective number density.
Definition at line 42 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
numberDensityUnit
Kernel::MaterialBuilder::NumberDensityUnit Mantid::DataHandling::ReadMaterial::MaterialParameters::numberDensityUnit = Kernel::MaterialBuilder::NumberDensityUnit::Atoms
A flag indicating the unit of sampleNumberDensity.
Definition at line 68 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), and Mantid::DataHandling::SetSampleMaterial::validateInputs().
packingFraction
double Mantid::DataHandling::ReadMaterial::MaterialParameters::packingFraction = EMPTY_DBL()
The sample packing fraction.
Definition at line 44 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
scatteringXSection
double Mantid::DataHandling::ReadMaterial::MaterialParameters::scatteringXSection = EMPTY_DBL()
The total scattering cross section to set, defaults to EMPTY_DBL()
Definition at line 62 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
unitCellVolume
double Mantid::DataHandling::ReadMaterial::MaterialParameters::unitCellVolume = EMPTY_DBL()
The unit cell volume to set, defaults to EMPTY_DBL()
Definition at line 48 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
volume
double Mantid::DataHandling::ReadMaterial::MaterialParameters::volume = EMPTY_DBL()
The sample volume to set, defaults to EMPTY_DBL()
Definition at line 54 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::SetSample::setSampleEnvironmentFromXML(), and Mantid::DataHandling::SetSampleMaterial::validateInputs().
xRayAttenuationProfileFileName
std::string Mantid::DataHandling::ReadMaterial::MaterialParameters::xRayAttenuationProfileFileName = ""
The name or path of a file containing an x ray attenuation profile.
Definition at line 66 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::ReadMaterial::setMaterialParameters(), and Mantid::DataHandling::SetSampleMaterial::validateInputs().
zParameter
double Mantid::DataHandling::ReadMaterial::MaterialParameters::zParameter = EMPTY_DBL()
The zParameter to set, defaults to EMPTY_DBL()
Definition at line 46 of file ReadMaterial.h.
Referenced by Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::SetSample::setMaterial(), Mantid::DataHandling::ReadMaterial::setMaterialParameters(), Mantid::DataHandling::LoadSampleEnvironment::validateInputs(), Mantid::DataHandling::SetSampleMaterial::validateInputs(), and Mantid::DataHandling::ReadMaterial::validateInputs().
The documentation for this struct was generated from the following file:
Framework/DataHandling/inc/MantidDataHandling/ReadMaterial.h