Mantid: MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark Class Reference
MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark Class Reference
Auxiliary class to wrap the QLineEdit allowing warning to the user for invalid inputs.
Public Member Functions
QLineEdit * lineEdit ()
provide acess to the QLineEdit
QLineEditWithErrorMark (QWidget *parent=nullptr)
constructor to join together the QLineEdit and an 'invisible'
label.
void setError (const QString &error)
if Error is not empty, it will make the * label visible and set the tooltip as the error.
~QLineEditWithErrorMark () override
virtual destructor to allow Qt to deallocate all objects
Private Attributes
QLineEdit * _lineEdit
QLabel * m_validLbl
Detailed Description
Auxiliary class to wrap the QLineEdit allowing warning to the user for invalid inputs.
Definition at line 207 of file MantidWSIndexDialog.h.
Constructor & Destructor Documentation
QLineEditWithErrorMark()
MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::QLineEditWithErrorMark (QWidget * parent = nullptr) explicit
constructor to join together the QLineEdit and an 'invisible'
label.
Definition at line 1236 of file MantidWSIndexDialog.cpp.
References _lineEdit, and m_validLbl.
~QLineEditWithErrorMark()
MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::~QLineEditWithErrorMark () inline override
virtual destructor to allow Qt to deallocate all objects
Definition at line 214 of file MantidWSIndexDialog.h.
Member Function Documentation
lineEdit()
QLineEdit * MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::lineEdit () inline
provide acess to the QLineEdit
Definition at line 216 of file MantidWSIndexDialog.h.
Referenced by MantidQt::MantidWidgets::MantidWSIndexWidget::editedSpectraField(), MantidQt::MantidWidgets::MantidWSIndexWidget::editedWsField(), MantidQt::MantidWidgets::MantidWSIndexWidget::getAxisName(), MantidQt::MantidWidgets::MantidWSIndexWidget::getCustomLogValues(), MantidQt::MantidWidgets::MantidWSIndexWidget::initLogs(), MantidQt::MantidWidgets::MantidWSIndexWidget::initSpectraBox(), MantidQt::MantidWidgets::MantidWSIndexWidget::initWorkspaceBox(), MantidQt::MantidWidgets::MantidWSIndexWidget::onLogSelected(), MantidQt::MantidWidgets::MantidWSIndexWidget::onPlotOptionChanged(), MantidQt::MantidWidgets::MantidWSIndexWidget::plotRequested(), and MantidQt::MantidWidgets::MantidWSIndexWidget::validatePlotOptions().
setError()
void MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::setError (const QString & error)
if Error is not empty, it will make the * label visible and set the tooltip as the error.
Definition at line 1249 of file MantidWSIndexDialog.cpp.
References error.
Referenced by MantidQt::MantidWidgets::MantidWSIndexWidget::editedSpectraField(), MantidQt::MantidWidgets::MantidWSIndexWidget::editedWsField(), MantidQt::MantidWidgets::MantidWSIndexWidget::plotRequested(), and MantidQt::MantidWidgets::MantidWSIndexWidget::validatePlotOptions().
Member Data Documentation
_lineEdit
QLineEdit* MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::_lineEdit private
Definition at line 222 of file MantidWSIndexDialog.h.
Referenced by QLineEditWithErrorMark().
m_validLbl
QLabel* MantidQt::MantidWidgets::MantidWSIndexWidget::QLineEditWithErrorMark::m_validLbl private
Definition at line 223 of file MantidWSIndexDialog.h.
Referenced by QLineEditWithErrorMark().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidWSIndexDialog.h
qt/widgets/common/src/MantidWSIndexDialog.cpp