Mantid: ICat4::ns1__login Class Reference
ICat4::ns1__login Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__login ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
_ns1__login_credentials credentials
std::string * plugin
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 961 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__login()
ICat4::ns1__login::ns1__login () inline
Definition at line 973 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__login::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18457 of file ICat4C.cpp.
References credentials, plugin, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::soap_in_ns1__login(), ICat4::soap_new_req_ns1__login(), and ICat4::soap_new_set_ns1__login().
soap_get()
void * ICat4::ns1__login::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18561 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__login().
soap_in()
void * ICat4::ns1__login::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18489 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__login().
Referenced by ICat4::soap_in_ns1__login().
soap_out()
int ICat4::ns1__login::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18473 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__login().
Referenced by soap_put().
soap_put()
int ICat4::ns1__login::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18554 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__login.
soap_serialize()
void ICat4::ns1__login::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 18464 of file ICat4C.cpp.
References credentials, plugin, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::_ns1__login_credentials::soap_serialize(), and ICat4::soap_serialize_PointerTostd__string().
Referenced by ICat4::soap_serialize_PointerTons1__IcatException().
soap_type()
int ICat4::ns1__login::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 966 of file ICat4Stub.h.
Member Data Documentation
credentials
_ns1__login_credentials ICat4::ns1__login::credentials
Definition at line 964 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
plugin
std::string* ICat4::ns1__login::plugin
Definition at line 963 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp