Mantid: Mantid::MDAlgorithms Namespace Reference
Mantid::MDAlgorithms Namespace Reference
Namespaces
namespace CnvrtToMD
The class defines default axis names/dimension ID-s for MD workspace which can be obtained/used in the MD transformations converting matrix workspace to Q or Q-dE space.
namespace LoadSQWHelper
LoadSQW : Load an SQW file and read observations in as events to generate a IMDEventWorkspace, with events in reciprocal space (Qx, Qy, Qz)
namespace MDAlgorithmsTestHelper
Classes
class AccumulateMD
AccumulateMD : Algorithm for appending new data to a MDHistoWorkspace.
class AndMD
AndMD : Perform the And boolean operation on two MDHistoWorkspaces.
class ApplyDetailedBalanceMD
ApplyDetailedBalance : Convert to chi'' of an MDEvent workspace.
class BaseConvertToDiffractionMDWorkspace
BaseConvertToDiffractionMDWorkspace.
class BinaryOperationMD
Abstract base class for binary operations on IMDWorkspaces, e.g.
class BinMD
Take a MDEventWorkspace and bin it to a dense histogram in a MDHistoWorkspace.
class BooleanBinaryOperationMD
BooleanBinaryOperationMD : base class for boolean-type operations on MDHistoWorkspaces.
class CalculateCoverageDGS
CalculateCoverageDGS : Calculate coverage for single crystal direct geometry scattering.
struct CellCoords
Partition QLab space into a cubic lattice.
class CentroidPeaksMD2
Find the centroid of single-crystal peaks in a MDEventWorkspace, in order to refine their positions.
class ChangeQConvention
Save a MDEventWorkspace to a .nxs file.
class CloneMDWorkspace
Algorithm to clone a MDEventWorkspace to a new one.
class CompactMD
class CompareMDWorkspaces
Compare two MDWorkspaces for equality.
class ConvertCWPDMDToSpectra
ConvertCWPDMDToSpectra : Convert one MDWorkspaces containing reactor-source powder diffractometer's data to single spectrum matrix workspace by merging and binning the detectors' counts by their 2theta value.
class ConvertCWSDExpToMomentum
ConvertCWSDExpToMomentum : TODO: DESCRIPTION.
class ConvertCWSDMDtoHKL
ConvertCWSDMDtoHKL : TODO: DESCRIPTION.
class ConvertHFIRSCDtoMDE
ConvertHFIRSCDtoMDE : TODO: DESCRIPTION.
class ConvertMDHistoToMatrixWorkspace
Creates a single spectrum Workspace2D with X,Y, and E copied from an first non-integrated dimension of a IMDHistoWorkspace.
class ConvertSpiceDataToRealSpace
ConvertSpiceDataToRealSpace : Convert data from SPICE file to singals in real space contained in MDEventWrokspaces.
class ConvertToDetectorFaceMD
Convert a MatrixWorkspace containing to a MD workspace for viewing the detector face.
class ConvertToDiffractionMDWorkspace
ConvertToDiffractionMDWorkspace : Create a MDEventWorkspace with events in reciprocal space (Qx, Qy, Qz) from an input EventWorkspace.
class ConvertToDiffractionMDWorkspace2
ConvertToDiffractionMDWorkspace2 : Create a MDEventWorkspace with events in reciprocal space (Qx, Qy, Qz) from an input EventWorkspace.
class ConvertToDiffractionMDWorkspace3
ConvertToDiffractionMDWorkspace3 : Create a MDEventWorkspace with events in reciprocal space (Qx, Qy, Qz) from an input EventWorkspace.
class ConvertToMD
ConvertToMD : Transform a workspace into MD workspace with components defined by user.
class ConvertToMDMinMaxGlobal
ConvertToMDMinMaxGlobal : Algorithm to calculate limits for ConvertToMD transformation which can be observed using an instrument which covers whole MD-space The current version knows.
class ConvertToMDMinMaxLocal
ConvertToMDMinMaxLocal : Algorithm to calculate limits for ConvertToMD.
class ConvertToMDParent
ConvertToMDParent : Main part of two algorithms which use ConvertToMD factory to transform points from instrument space to physical MD space.
class ConvToMDBase
Class describes the interface to the methods, which perform conversion from usual workspaces to MDEventWorkspace.
class ConvToMDEventsWS
The class specializes ConvToDataObjectsBase for the case when the conversion occurs from Events WS to the MD events WS.
class ConvToMDEventsWSIndexing
This class creates the MDWorkspace from the collection of ToF events: converts to the MD events with proper Nd coordinate and than assigns the groups of them to the spatial tree-like box structure.
class ConvToMDHistoWS
The class to transform matrix workspace into MDEvent workspace when matrix workspace is ragged 2D workspace See dev-docs/source/WritingCustomConvertToMDTransformation.rst for detailed description of this class place in the algorithms hierarchy.
class ConvToMDSelector
small class to select proper solver as function of the workspace kind and (possibly, in a future) other workspace parameters.
class CreateMD
CreateMD : This workflow algorithm creates MDWorkspaces in the Q3D, HKL frame using ConvertToMD.
class CreateMDHistoWorkspace
CreateMDHistoWorkspace.
class CreateMDWorkspace
CreateMDWorkspace :
class CutMD
CutMD : Slices multidimensional workspaces.
class DebyeWallerFactorCorrectionMD
DebyeWallerCorrectionMD : Correct event signal and error values for Debye-Waller factor.
class DgsScatteredTransmissionCorrectionMD
class DisabledProperty
Small class to diable propery on interface.
class DisplayNormalizationSetter
DisplayNormalizationSetter: Sets the displaynormalization on a workspace based on several parameters such as workspace-type, energy-transfer-mode and if we are dealing with Q3D.
class DivideMD
DivideMD : divide operation for MDWorkspaces.
class EqualToMD
EqualToMD : boolean operation on MDHistoWorkspaces.
class EvaluateMDFunction
EvaluateMDFunction : TODO: DESCRIPTION.
class ExponentialMD
ExponentialMD : exponential function on MDHistoWorkspace.
class FakeMDEventData
FakeMDEventData : Algorithm to create fake multi-dimensional event data that gets added to MDEventWorkspace, for use in testing.
class FindPeaksMD
FindPeaksMD : TODO: DESCRIPTION.
class FitMD
Creates FunctionDomainMD from an IMDWorkspace.
class FlippingRatioCorrectionMD
FlippingRatioCorrectionMD : Algorithm to correct MDEvents for flipping ratio.
class GetSpiceDataRawCountsFromMD
GetSpiceDataRawCountsFromMD : Export raw detectors' counts or sample log values from IMDEventWorkspaces from the output of algorithm ConvertSpiceDataToRealSpace.
class GreaterThanMD
GreaterThanMD : boolean operation on MDHistoWorkspaces.
class IDynamicRebinning
Class provides commont interface for various classes performing rebinning operations;.
class ImportMDEventWorkspace
ImportMDEventWorkspace : Loads a file containing dimensionality and data for an MDEventWorkspace.
class ImportMDHistoWorkspace
ImportMDHistoWorkspace : Takes a text file containing structured signal and error information and imports it as a new MDHistoWorkspace.
class ImportMDHistoWorkspaceBase
ImportMDHistoWorkspaceBase : Base class for algorithms Importing data as MDHistoWorkspaces.
struct InputArgument
Local type to group min, max extents with a dimension index.
class Integrate3DEvents
This is a low-level class to construct a map with lists of events near each peak Q-vector, shifted to be centered at (0,0,0).
class IntegrateEllipsoids
class IntegrateEllipsoidsTwoStep
IntegrateEllipsoidsTwoStep provides a two pass peak integration algorithm.
class IntegrateEllipsoidsV1
class IntegrateEllipsoidsV2
class IntegrateFlux
Algorithm IntegrateFlux.
class IntegrateMDHistoWorkspace
IntegrateMDHistoWorkspace : Algorithm to perform axis aligned integration of an MDHistoWorkspace.
class IntegratePeaksCWSD
Integrate single-crystal peaks in reciprocal-space.
class IntegratePeaksMD
Integrate single-crystal peaks in reciprocal-space.
class IntegratePeaksMD2
Integrate single-crystal peaks in reciprocal-space.
class IntegratePeaksMDHKL
Integrate single-crystal peaks in reciprocal-space.
class IntegrateQLabEvents
This is a low-level class to construct a map with lists of events near each peak Q-vector in the lab frame.
struct IntegrationParameters
class InvalidParameter
Invalid parameter type.
class InvalidParameterParser
XML Parser for invalid parameter types.
struct LessThanIndex
Comparator to allow sorting by dimension index.
class LessThanMD
LessThanMD : boolean operation on MDHistoWorkspaces.
class LoadDNSSCD
LoadDNSSCD : Load a list of DNS .d_dat files into a MDEventWorkspace.
class LoadGaussCube
LoadGaussCube : TODO: DESCRIPTION.
class LoadMD
Load a .nxs file into a MDEventWorkspace.
class LoadSQW
class LoadSQW2
class LogarithmMD
LogarithmMD : natural logarithm of a MDHistoWorkspace.
class LOOP
class LOOP< 0 >
class MagneticFormFactorCorrectionMD
MagneticFormFactorCorrectionMD : Correct event signal and error values for magnetic form factor.
class MaskMD
MaskMD : Mask an MDWorkspace.
class MDEventTreeBuilder
Class to create the box structure of MDWorkspace.
class MDEventWSWrapper
class MDNorm
MDNormalization : Bin single crystal diffraction or direct geometry inelastic data and calculate the corresponding statistical weight.
class MDNormDirectSC
MDNormSCD : Generate MD normalization for single crystal diffraction.
class MDNormSCD
MDNormSCD : Generate MD normalization for single crystal diffraction.
class MDTransfAxisNames
class MDTransfFactoryImpl
Creates instances of concrete transformations into multidimensional (MD) coordinates.
class MDTransfInterface
Interface to set of sub-classes used by ConvertToMD algorithm and responsible for conversion of input workspace data into MD events.
class MDTransfModQ
Class responsible for conversion of input workspace data into proper number of output dimensions for ModQ case.
class MDTransfNoQ
Class responsible for conversion of input workspace data into proper number of output dimensions in NoQ case, when the data from a ws are just copied to MD WS.
class MDTransfQ3D
Class responsible for conversion of input workspace data into proper number of output dimensions for Q3D case.
class MDWSDescription
helper class describes the properties of target MD workspace, which should be obtained as the result of conversion algorithm.
class MDWSTransform
class MergeMD
Merge several MDWorkspaces into one.
class MergeMDFiles
Algorithm to merge multiple MDEventWorkspaces from files that obey a common box format.
class MinusMD
MinusMD : minus operation for MDWorkspaces.
class MultiplyMD
MultiplyMD : multiplication operation for MDWorkspaces.
class NotMD
NotMD : boolean negation of a MDHistoWorkspace.
struct OccupiedCell
class OrMD
OrMD : boolean operation on MDHistoWorkspaces.
class PlusMD
Sum two MDWorkspaces together.
class PolarizationAngleCorrectionMD
PolarizationAngleCorrection : Perform polarization angle correction to an MDEventWorkspace.
class PowerMD
PowerMD : raise a MDHistoWorkspace to a power.
class PreprocessDetectorsToMD
This is helper algorithm used to preprocess detector's positions namely to perform generic part of the transformation from a matrix workspace of a real instrument to physical MD workspace of an experimental results (e.g Q-space).
struct Product
Functor to compute the product of the set.
class QTransform
QTransform : Base algorithm for transforming |Q| values in an MD workspace.
class QueryMDWorkspace
QueryMDWorkspace : Query an MDWorkspace in order to extract overview information as a table workspace.
class RecalculateTrajectoriesExtents
RecalculateTrajectoriesExtents :
class ReplicateMD
ReplicateMD : Algorithm header for ReplicateMD.
class SaveIsawQvector
SaveIsawQvector.
class SaveMD
Save a MDEventWorkspace to a .nxs file.
class SaveMD2
Save a MDEventWorkspace to a .nxs file.
class SaveZODS
Save a MDHistoWorkspace to a HDF5 format for use with the ZODS analysis software.
class SetMDFrame
SetMDFrame : This algorithm changes the MDFrame stored alongside the dimension of MDWorkspaes.The algorithm should primarily be used to introduce the correct MDFrame type to workspaces based on legacy files.
class SetMDUsingMask
Algorithm to set a MDHistoWorkspace in points determined by a mask boolean MDHistoWorkspace.
class SimpleMDEvent
class SliceMD
Algorithm that can take a slice out of an original MDEventWorkspace while preserving all the events contained wherein.
class SlicingAlgorithm
Abstract Algorithm class that will be used by: BinMD and SliceMD and shares code for getting a slice from one workspace to another.
class SmoothMD
SmoothMD : Algorithm for smoothing MDHistoWorkspaces.
class SpectralMomentMD
SpectralMomentMD : Multiply MD events by DeltaE^n.
struct Square
Helper type to compute the square in-place.
class ThresholdMD
ThresholdMD : TODO: DESCRIPTION.
class TransformMD
Scale and/or offset the coordinates of a MDWorkspace.
class TransposeMD
TransposeMD : Transpose an MDWorkspace.
class UnaryOperationMD
Abstract base class for unary operations (e.g.
class UnitsConversionHelper
class UserFunctionMD
A user defined function.
class Vector3DParameter
Vector3DParameter is abstract type implementing curiously recurring template pattern to implement common code associated with vector storage.
class Vector3DParameterParser
XML parser for vector value (3 elements) parameter types.
class WeightedMeanMD
WeightedMeanMD : Find the weighted mean of two MDWorkspaces.
class XorMD
XorMD : boolean operation on MDHistoWorkspaces.
Typedefs
using EventListMap = std::unordered_map< int64_t, std::vector< std::pair< std::pair< double, double >, Mantid::Kernel::V3D > > >
using fpAddData = void(MDEventWSWrapper::*)(const float *, const uint16_t *, const uint16_t *, const uint32_t *, const coord_t *, size_t) const
signature for the internal templated function pointer to add data to an existing workspace
using fpCreateWS = void(MDEventWSWrapper::*)(const MDWSDescription &)
signature for the internal templated function pointer to create workspace
using fpVoidMethod = void(MDEventWSWrapper::*)()
signature to void templated function
using MDE = DataObjects::MDLeanEvent< 3 >
Our MDLeanEvent dimension.
using MDTransf_const_sptr = std::shared_ptr< const MDTransfInterface >
using MDTransf_sptr = std::shared_ptr< MDTransfInterface >
using MDTransfFactory = Kernel::SingletonHolder< MDTransfFactoryImpl >
The specialization of the SingletonHolder class that holds the MDTransformations Factory.
using PeakQMap = std::unordered_map< int64_t, Mantid::Kernel::V3D >
using SlimEvent = std::pair< std::pair< double, double >, V3D >
using SlimEvents = std::vector< SlimEvent >
using Strings = std::vector< std::string >
The class which wraps MD Events factory and allow to work with a N-dimensional templated MDEvent workspace like usuall class with n-dimension as a parameter.
using VectorDoubleProperty = Kernel::PropertyWithValue< std::vector< double > >
Enumerations
enum wsType { Matrix2DWS , EventWS , Undefined }
Functions
bool all_given (const std::vector< std::vector< double > > &params)
bool any_given (const std::vector< std::vector< double > > &params)
bool appearsInCurrentData (const std::string &data_source, const std::vector< std::string > &current_data)
Check if the named data source is in the vector of data currently in the workspace.
const std::size_t BUFF_SIZE (DIMS *sizeof(float))
Constant for the size of the buffer to write to disk.
double calcualte2ThetaFromQ (const double &q, const double &wavelength)
Calculate detector's 2theta value from Q 2theta = 2*asin(lambda*Q/(4pi))
double calculate2Theta (const Kernel::V3D &detpos, const Kernel::V3D &samplepos)
Calculate 2theta value of detector postion from sample position.
double calculate2ThetaFromD (const double &dspace, const double &wavelength)
Calcualte detector's 2theta value from d-spacing value 2theta = 2*asin(lamba/2/d)
double calculateDspaceFrom2Theta (const double &twotheta, const double &wavelength)
Calculate d-space value from detector's position (2theta/theta) and wavelength.
double calculateQFrom2Theta (const double &twotheta, const double &wavelength)
Calculate Q value from detector's positin (2theta/theta) and wavelength q = 2 k sin(theta) = (4 pi)/(lambda) * sin(theta)
bool compareSimpleEvents (const SimpleMDEvent &self, const SimpleMDEvent &other)
template<size_t nd, size_t ond>
void copyEvent (const MDEvent< nd > &srcEvent, MDEvent< ond > &newEvent)
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
template<size_t nd, size_t ond>
void copyEvent (const MDEvent< nd > &srcEvent, MDEvent< ond > &newEvent, const uint16_t expInfoIndexOffset)
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
template<size_t nd, size_t ond>
void copyEvent (const MDLeanEvent< nd > &srcEvent, MDLeanEvent< ond > &newEvent)
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
template<size_t nd, size_t ond>
void copyEvent (const MDLeanEvent< nd > &srcEvent, MDLeanEvent< ond > &newEvent, const uint16_t expInfoIndexOffset)
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
bool MANTID_MDALGORITHMS_DLL dataExists (const std::string &data_name)
Check if the named data source is an existing workspace or file.
const std::size_t DIMS (3)
Q-vector is always three dimensional.
const std::string ELASTIC ("Elastic")
This only works for diffraction.
constexpr double EMPTY_FLT () noexcept
double f_eval (double x, void *params)
double f_eval2 (double x, void *params)
bool fileExists (const std::string &filename)
Test if a file with the given full path name exists.
std::string MANTID_MDALGORITHMS_DLL filterToExistingSources (std::vector< std::string > &input_data, std::vector< double > &psi, std::vector< double > &gl, std::vector< double > &gs, std::vector< double > &efix)
Reduce the vector of input data to only data files and workspaces which can be found.
std::string MANTID_MDALGORITHMS_DLL filterToNew (std::vector< std::string > &input_data, const std::vector< std::string > &current_data, std::vector< double > &psi, std::vector< double > &gl, std::vector< double > &gs, std::vector< double > &efix)
Reduce the vector of input data to only data files and workspaces which are not found in the vector of data currently in the workspace.
std::vector< std::string > DLLExport findOriginalQUnits (const IMDWorkspace_const_sptr &inws, Mantid::Kernel::Logger &logger)
Determine the original q units.
DLLExport std::vector< double > gaussianKernel (const double fwhm)
std::vector< std::string > getHistoricalDataSources (const API::WorkspaceHistory &ws_history, const std::string &create_alg_name, const std::string &accumulate_alg_name)
Return a vector of the names of files and workspaces which have been previously added to the workspace.
int getIndexCount (PeaksWorkspace_sptr peakWorkspace)
int getSatelliteIndexCount (PeaksWorkspace_sptr peakWorkspace)
std::string GreaterThan ()
bool inRange (const double &xMin, const double &xMax, const double &val)
bool inRange (const std::pair< double, double > &range, const double &val)
void MANTID_MDALGORITHMS_DLL insertDataSources (const std::string &data_sources, std::unordered_set< std::string > &historical_data_sources)
Extract names of data sources from workspace history and form a set of historical data sources.
template<class T >
bool isNaN (T val)
Template to check if a variable equal to NaN.
std::string LessThan ()
std::string DLLExport makeAxisName (const Kernel::V3D &Dir, const std::vector< std::string > &QNames)
function to build mslice-like axis name from the vector, which describes crystallographic direction along this axis
static const std::string MAXRECURSIONDEPTH ("20")
std::string noNormalisationOption ()
Non-member defining the no normalisation option.
DLLExport std::vector< double > normaliseKernel (std::vector< double > kernel)
std::string numberOfEventsNormalisationOption ()
Non-member defining the number of events normalisation option.
void MANTID_MDALGORITHMS_DLL padParameterVector (std::vector< double > &param_vector, const size_t grow_to_size)
Pad vector of parameters to given length.
std::vector< std::string > MANTID_MDALGORITHMS_DLL parseDimensionNames (const std::string &names_string)
std::vector< std::string > MANTID_MDALGORITHMS_DLL parseNames (const std::string &names_string)
const std::string Q3D ("Q3D")
Only convert to Q-vector.
DLLExport std::vector< double > renormaliseKernel (std::vector< double > kernel, const std::vector< bool > &validity)
static const std::string SPLITINTO ("2")
static const std::string SPLITTHRESHOLD ("500")
std::string DLLExport sprintfd (const double data, const double eps)
creates string representation of the number with accuracy, cpecified by eps
size_t tryFetchDimensionIndex (const Mantid::API::IMDWorkspace_sptr &ws, const std::string &candidateNameOrId)
Free helper function.
template<typename T >
std::string versus (T a, T b)
Return a string "(a vs b)".
std::string volumeNormalisationOption ()
Non-member defining the volume normalisation option.
Mantid::API::MDNormalization whichNormalisation (const std::string &strNormalisation)
Non-member method to interpret an normalisation option.
Variables
const double BIGNUMBER = 1.0E100
bool DODEBUG = true
const signal_t THRESHOLD_SIGNAL = 0
Typedef Documentation
EventListMap
using Mantid::MDAlgorithms::EventListMap = typedef std::unordered_map<int64_t, std::vector<std::pair<std::pair<double, double>, Mantid::Kernel::V3D> >>
Definition at line 51 of file Integrate3DEvents.h.
fpAddData
using Mantid::MDAlgorithms::fpAddData = typedef void (MDEventWSWrapper::*)(const float *, const uint16_t *, const uint16_t *, const uint32_t *, const coord_t *, size_t) const
signature for the internal templated function pointer to add data to an existing workspace
Definition at line 38 of file MDEventWSWrapper.h.
fpCreateWS
using Mantid::MDAlgorithms::fpCreateWS = typedef void (MDEventWSWrapper::*)(const MDWSDescription &)
signature for the internal templated function pointer to create workspace
Definition at line 41 of file MDEventWSWrapper.h.
fpVoidMethod
using Mantid::MDAlgorithms::fpVoidMethod = typedef void (MDEventWSWrapper::*)()
signature to void templated function
Definition at line 35 of file MDEventWSWrapper.h.
MDE
using Mantid::MDAlgorithms::MDE = typedef DataObjects::MDLeanEvent<3>
Our MDLeanEvent dimension.
Definition at line 119 of file ConvertToDiffractionMDWorkspace.cpp.
MDTransf_const_sptr
using Mantid::MDAlgorithms::MDTransf_const_sptr = typedef std::shared_ptr<const MDTransfInterface>
Definition at line 207 of file MDTransfInterface.h.
MDTransf_sptr
using Mantid::MDAlgorithms::MDTransf_sptr = typedef std::shared_ptr<MDTransfInterface>
Definition at line 206 of file MDTransfInterface.h.
MDTransfFactory
using Mantid::MDAlgorithms::MDTransfFactory = typedef Kernel::SingletonHolder<MDTransfFactoryImpl>
The specialization of the SingletonHolder class that holds the MDTransformations Factory.
Definition at line 80 of file MDTransfFactory.h.
PeakQMap
using Mantid::MDAlgorithms::PeakQMap = typedef std::unordered_map<int64_t, Mantid::Kernel::V3D>
Definition at line 53 of file Integrate3DEvents.h.
SlimEvent
using Mantid::MDAlgorithms::SlimEvent = typedef std::pair<std::pair<double, double>, V3D>
Definition at line 63 of file IntegrateQLabEvents.h.
SlimEvents
using Mantid::MDAlgorithms::SlimEvents = typedef std::vector<SlimEvent>
Definition at line 64 of file IntegrateQLabEvents.h.
Strings
using Mantid::MDAlgorithms::Strings = typedef std::vector<std::string>
The class which wraps MD Events factory and allow to work with a N-dimensional templated MDEvent workspace like usuall class with n-dimension as a parameter.
Introduced to decrease code bloat and increase efficiency of methods and
algorithms, which use DataObjects write interface and run-time defined number of dimensions
Date
2011-28-12 vectors of strings are often used here
Definition at line 27 of file MDEventWSWrapper.h.
VectorDoubleProperty
using Mantid::MDAlgorithms::VectorDoubleProperty = typedef Kernel::PropertyWithValue<std::vector<double> >
Definition at line 21 of file RecalculateTrajectoriesExtents.cpp.
Enumeration Type Documentation
wsType
enum Mantid::MDAlgorithms::wsType
Enumerator
Matrix2DWS
EventWS
Undefined
Definition at line 17 of file ConvToMDSelector.cpp.
Function Documentation
all_given()
bool Mantid::MDAlgorithms::all_given (const std::vector< std::vector< double > > & params)
Definition at line 73 of file CreateMD.cpp.
Referenced by Mantid::MDAlgorithms::CreateMD::single_run().
any_given()
bool Mantid::MDAlgorithms::any_given (const std::vector< std::vector< double > > & params)
Definition at line 56 of file CreateMD.cpp.
Referenced by Mantid::MDAlgorithms::CreateMD::single_run().
appearsInCurrentData()
bool Mantid::MDAlgorithms::appearsInCurrentData (const std::string & data_source, const std::vector< std::string > & current_data)
Check if the named data source is in the vector of data currently in the workspace.
Definition at line 128 of file AccumulateMD.cpp.
Referenced by filterToNew().
BUFF_SIZE()
const std::size_t Mantid::MDAlgorithms::BUFF_SIZE (DIMS * sizeoffloat)
Constant for the size of the buffer to write to disk.
Referenced by Mantid::MDAlgorithms::SaveIsawQvector::exec().
calcualte2ThetaFromQ()
double Mantid::MDAlgorithms::calcualte2ThetaFromQ (const double & q, const double & wavelength) inline
Calculate detector's 2theta value from Q 2theta = 2*asin(lambda*Q/(4pi))
calcualte2ThetaFromQ
Parameters
q
wavelength
Returns
Definition at line 63 of file ConvertCWPDMDToSpectra.h.
calculate2Theta()
double Mantid::MDAlgorithms::calculate2Theta (const Kernel::V3D & detpos, const Kernel::V3D & samplepos) inline
Calculate 2theta value of detector postion from sample position.
calculate2Theta
Parameters
detpos
samplepos
Returns
Definition at line 74 of file ConvertCWPDMDToSpectra.h.
References Mantid::Kernel::V3D::angle().
Referenced by Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), and Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary().
calculate2ThetaFromD()
double Mantid::MDAlgorithms::calculate2ThetaFromD (const double & dspace, const double & wavelength) inline
Calcualte detector's 2theta value from d-spacing value 2theta = 2*asin(lamba/2/d)
calculate2ThetaFromD
Parameters
dspace
wavelength
Returns
Definition at line 39 of file ConvertCWPDMDToSpectra.h.
calculateDspaceFrom2Theta()
double Mantid::MDAlgorithms::calculateDspaceFrom2Theta (const double & twotheta, const double & wavelength) inline
Calculate d-space value from detector's position (2theta/theta) and wavelength.
calculateDspaceFrom2Theta
Parameters
twotheta
wavelength
Returns
Definition at line 27 of file ConvertCWPDMDToSpectra.h.
Referenced by Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), and Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary().
calculateQFrom2Theta()
double Mantid::MDAlgorithms::calculateQFrom2Theta (const double & twotheta, const double & wavelength) inline
Calculate Q value from detector's positin (2theta/theta) and wavelength q = 2 k sin(theta) = (4 pi)/(lambda) * sin(theta)
calculateQ
Parameters
twotheta
wavelength
Returns
Definition at line 51 of file ConvertCWPDMDToSpectra.h.
Referenced by Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), and Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary().
compareSimpleEvents()
bool Mantid::MDAlgorithms::compareSimpleEvents (const SimpleMDEvent & self, const SimpleMDEvent & other)
Definition at line 143 of file CompareMDWorkspaces.cpp.
copyEvent() [1/4]
template<size_t nd, size_t ond> void Mantid::MDAlgorithms::copyEvent (const MDEvent< nd > & srcEvent, MDEvent< ond > & newEvent) inline
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
Parameters
srcEvent :: the source event, being copied
newEvent :: the destination event
Definition at line 87 of file SliceMD.cpp.
References Mantid::DataObjects::MDEvent< nd >::getDetectorID(), Mantid::DataObjects::MDEvent< nd >::getExpInfoIndex(), Mantid::DataObjects::MDEvent< nd >::setDetectorId(), and Mantid::DataObjects::MDEvent< nd >::setExpInfoIndex().
copyEvent() [2/4]
template<size_t nd, size_t ond> void Mantid::MDAlgorithms::copyEvent (const MDEvent< nd > & srcEvent, MDEvent< ond > & newEvent, const uint16_t expInfoIndexOffset) inline
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
Parameters
srcEvent :: the source event, being copied
newEvent :: the destination event
expInfoIndexOffset :: offset to be added to the expInfoIndex
Definition at line 177 of file MergeMD.cpp.
References Mantid::DataObjects::MDEvent< nd >::getDetectorID(), Mantid::DataObjects::MDEvent< nd >::getExpInfoIndex(), Mantid::DataObjects::MDEvent< nd >::setDetectorId(), and Mantid::DataObjects::MDEvent< nd >::setExpInfoIndex().
copyEvent() [3/4]
template<size_t nd, size_t ond> void Mantid::MDAlgorithms::copyEvent (const MDLeanEvent< nd > & srcEvent, MDLeanEvent< ond > & newEvent) inline
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
Parameters
srcEvent :: the source event, being copied
newEvent :: the destination event
Definition at line 73 of file SliceMD.cpp.
References UNUSED_ARG.
copyEvent() [4/4]
template<size_t nd, size_t ond> void Mantid::MDAlgorithms::copyEvent (const MDLeanEvent< nd > & srcEvent, MDLeanEvent< ond > & newEvent, const uint16_t expInfoIndexOffset) inline
Copy the extra data (not signal, error or coordinates) from one event to another with different numbers of dimensions.
Parameters
srcEvent :: the source event, being copied
newEvent :: the destination event
expInfoIndexOffset :: offset to be added to the expInfoIndex
Definition at line 161 of file MergeMD.cpp.
References UNUSED_ARG.
Referenced by Mantid::MDAlgorithms::MergeMD::doPlus(), and Mantid::MDAlgorithms::SliceMD::slice().
dataExists()
bool Mantid::MDAlgorithms::dataExists (const std::string & data_name)
Check if the named data source is an existing workspace or file.
Definition at line 67 of file AccumulateMD.cpp.
References fileExists().
Referenced by filterToExistingSources(), and Mantid::MDAlgorithms::CreateMD::validateInputs().
DIMS()
const std::size_t Mantid::MDAlgorithms::DIMS (3)
Q-vector is always three dimensional.
Referenced by Mantid::MDAlgorithms::SaveIsawQvector::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromEventWS(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::qListFromEventWS(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::qListFromEventWS(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromHistoWS(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::qListFromHistoWS(), and Mantid::MDAlgorithms::IntegrateEllipsoidsV2::qListFromHistoWS().
ELASTIC()
const std::string Mantid::MDAlgorithms::ELASTIC ("Elastic")
This only works for diffraction.
Referenced by Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initTargetWSDescr(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initTargetWSDescr(), Mantid::MDAlgorithms::SaveIsawQvector::initTargetWSDescr(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromEventWS(), and Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromHistoWS().
EMPTY_FLT()
constexpr double Mantid::MDAlgorithms::EMPTY_FLT () constexpr noexcept
Definition at line 30 of file DgsScatteredTransmissionCorrectionMD.cpp.
f_eval()
double Mantid::MDAlgorithms::f_eval (double x, void * params)
Definition at line 620 of file IntegratePeaksMD.cpp.
References Mantid::Geometry::x.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD::integrate().
f_eval2()
double Mantid::MDAlgorithms::f_eval2 (double x, void * params)
Definition at line 1291 of file IntegratePeaksMD2.cpp.
References Mantid::Geometry::x.
Referenced by Mantid::MDAlgorithms::IntegratePeaksMD2::integrate().
fileExists()
bool Mantid::MDAlgorithms::fileExists (const std::string & filename)
Test if a file with the given full path name exists.
Definition at line 82 of file AccumulateMD.cpp.
Referenced by dataExists().
filterToExistingSources()
std::string Mantid::MDAlgorithms::filterToExistingSources (std::vector< std::string > & input_data, std::vector< double > & psi, std::vector< double > & gl, std::vector< double > & gs, std::vector< double > & efix)
Reduce the vector of input data to only data files and workspaces which can be found.
Definition at line 46 of file AccumulateMD.cpp.
References dataExists().
Referenced by Mantid::MDAlgorithms::AccumulateMD::exec().
filterToNew()
std::string Mantid::MDAlgorithms::filterToNew (std::vector< std::string > & input_data, const std::vector< std::string > & current_data, std::vector< double > & psi, std::vector< double > & gl, std::vector< double > & gs, std::vector< double > & efix)
Reduce the vector of input data to only data files and workspaces which are not found in the vector of data currently in the workspace.
Definition at line 103 of file AccumulateMD.cpp.
References appearsInCurrentData().
Referenced by Mantid::MDAlgorithms::AccumulateMD::exec().
findOriginalQUnits()
std::vector< std::string > Mantid::MDAlgorithms::findOriginalQUnits (const IMDWorkspace_const_sptr & inws, Mantid::Kernel::Logger & logger)
Determine the original q units.
Assumes first 3 dimensions by index are r,l,d
Parameters
inws : Input workspace to extract dimension info from
logger : logging object
Returns
vector of markers
Definition at line 198 of file CutMD.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::MDAlgorithms::CutMD::InvAngstromSymbol, and Mantid::MDAlgorithms::CutMD::RLUSymbol.
Referenced by Mantid::MDAlgorithms::CutMD::exec().
gaussianKernel()
KernelVector Mantid::MDAlgorithms::gaussianKernel (const double fwhm)
Definition at line 77 of file SmoothMD.cpp.
References normaliseKernel(), and sigma.
getHistoricalDataSources()
std::vector< std::string > Mantid::MDAlgorithms::getHistoricalDataSources (const API::WorkspaceHistory & ws_history, const std::string & create_alg_name, const std::string & accumulate_alg_name)
Return a vector of the names of files and workspaces which have been previously added to the workspace.
Definition at line 140 of file AccumulateMD.cpp.
References Mantid::API::WorkspaceHistory::createView(), and insertDataSources().
Referenced by Mantid::MDAlgorithms::AccumulateMD::exec().
getIndexCount()
int Mantid::MDAlgorithms::getIndexCount (PeaksWorkspace_sptr peakWorkspace)
Definition at line 40 of file IntegrateEllipsoids.cpp.
Referenced by Mantid::MDAlgorithms::IntegrateEllipsoids::exec().
getSatelliteIndexCount()
int Mantid::MDAlgorithms::getSatelliteIndexCount (PeaksWorkspace_sptr peakWorkspace)
Definition at line 51 of file IntegrateEllipsoids.cpp.
Referenced by Mantid::MDAlgorithms::IntegrateEllipsoids::exec().
GreaterThan()
std::string Mantid::MDAlgorithms::GreaterThan ()
Definition at line 27 of file ThresholdMD.cpp.
Referenced by Mantid::MDAlgorithms::ThresholdMD::exec(), and Mantid::MDAlgorithms::ThresholdMD::init().
inRange() [1/2]
bool Mantid::MDAlgorithms::inRange (const double & xMin, const double & xMax, const double & val) inline
Definition at line 108 of file UnitsConversionHelper.cpp.
inRange() [2/2]
bool Mantid::MDAlgorithms::inRange (const std::pair< double, double > & range, const double & val) inline
Definition at line 103 of file UnitsConversionHelper.cpp.
Referenced by Mantid::MDAlgorithms::UnitsConversionHelper::getConversionRange().
insertDataSources()
void Mantid::MDAlgorithms::insertDataSources (const std::string & data_sources, std::unordered_set< std::string > & historical_data_sources)
Extract names of data sources from workspace history and form a set of historical data sources.
Definition at line 175 of file AccumulateMD.cpp.
Referenced by getHistoricalDataSources().
isNaN()
template<class T > bool Mantid::MDAlgorithms::isNaN (T val) inline
Template to check if a variable equal to NaN.
Definition at line 14 of file ConvToMDHistoWS.cpp.
Referenced by Mantid::MDAlgorithms::ConvToMDHistoWS::conversionChunk().
LessThan()
std::string Mantid::MDAlgorithms::LessThan ()
Definition at line 25 of file ThresholdMD.cpp.
Referenced by Mantid::MDAlgorithms::ThresholdMD::init().
makeAxisName()
std::string Mantid::MDAlgorithms::makeAxisName (const Kernel::V3D & Dir, const std::vector< std::string > & QNames)
function to build mslice-like axis name from the vector, which describes crystallographic direction along this axis
Definition at line 62 of file MDTransfAxisNames.cpp.
References fabs, name, sprintfd(), Mantid::Kernel::V3D::X(), Mantid::Kernel::V3D::Y(), and Mantid::Kernel::V3D::Z().
Referenced by Mantid::MDAlgorithms::MDWSTransform::setQ3DDimensionsNames().
MAXRECURSIONDEPTH()
static const std::string Mantid::MDAlgorithms::MAXRECURSIONDEPTH ("20") static
Referenced by Mantid::MDAlgorithms::CreateMD::convertToMD(), and Mantid::MDAlgorithms::CreateMD::merge_runs().
noNormalisationOption()
std::string Mantid::MDAlgorithms::noNormalisationOption ()
Non-member defining the no normalisation option.
Returns
no normalisation option.
Definition at line 33 of file QueryMDWorkspace.cpp.
Referenced by Mantid::MDAlgorithms::QueryMDWorkspace::init(), and whichNormalisation().
normaliseKernel()
KernelVector Mantid::MDAlgorithms::normaliseKernel (std::vector< double > kernel)
Definition at line 131 of file SmoothMD.cpp.
References value.
Referenced by gaussianKernel(), and renormaliseKernel().
numberOfEventsNormalisationOption()
std::string Mantid::MDAlgorithms::numberOfEventsNormalisationOption ()
Non-member defining the number of events normalisation option.
Returns
number of events normalisation.
Definition at line 45 of file QueryMDWorkspace.cpp.
Referenced by Mantid::MDAlgorithms::QueryMDWorkspace::init().
padParameterVector()
void Mantid::MDAlgorithms::padParameterVector (std::vector< double > & param_vector, const size_t grow_to_size) extern
Pad vector of parameters to given length.
Definition at line 40 of file CreateMD.cpp.
Referenced by Mantid::MDAlgorithms::AccumulateMD::exec(), and Mantid::MDAlgorithms::CreateMD::exec().
parseDimensionNames()
std::vector< std::string > Mantid::MDAlgorithms::parseDimensionNames (const std::string & names_string)
Definition at line 29 of file MaskMD.cpp.
Referenced by Mantid::MDAlgorithms::MaskMD::exec(), and Mantid::MDAlgorithms::MaskMD::validateInputs().
parseNames()
std::vector< std::string > Mantid::MDAlgorithms::parseNames (const std::string & names_string)
Definition at line 40 of file CreateMDWorkspace.cpp.
Referenced by Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::LoadGaussCube::exec(), and Mantid::MDAlgorithms::LoadGaussCube::validateInputs().
Q3D()
const std::string Mantid::MDAlgorithms::Q3D ("Q3D")
Only convert to Q-vector.
Referenced by Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initTargetWSDescr(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initTargetWSDescr(), Mantid::MDAlgorithms::SaveIsawQvector::initTargetWSDescr(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromEventWS(), and Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::qListFromHistoWS().
renormaliseKernel()
KernelVector Mantid::MDAlgorithms::renormaliseKernel (std::vector< double > kernel, const std::vector< bool > & validity)
Definition at line 114 of file SmoothMD.cpp.
References normaliseKernel().
Referenced by Mantid::MDAlgorithms::SmoothMD::gaussianSmooth().
SPLITINTO()
static const std::string Mantid::MDAlgorithms::SPLITINTO ("2") static
Referenced by Mantid::MDAlgorithms::CreateMD::convertToMD(), and Mantid::MDAlgorithms::CreateMD::merge_runs().
SPLITTHRESHOLD()
static const std::string Mantid::MDAlgorithms::SPLITTHRESHOLD ("500") static
Referenced by Mantid::MDAlgorithms::CreateMD::convertToMD(), and Mantid::MDAlgorithms::CreateMD::merge_runs().
sprintfd()
std::string DLLExport Mantid::MDAlgorithms::sprintfd (const double data, const double eps)
creates string representation of the number with accuracy, cpecified by eps
Definition at line 96 of file MDTransfAxisNames.cpp.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createQDimension(), makeAxisName(), and Mantid::MDAlgorithms::MDWSTransform::setQ3DDimensionsNames().
tryFetchDimensionIndex()
size_t Mantid::MDAlgorithms::tryFetchDimensionIndex (const Mantid::API::IMDWorkspace_sptr & ws, const std::string & candidateNameOrId)
Free helper function.
try to fetch the workspace index.
Parameters
ws : The workspace to find the dimensions in
candidateNameOrId Either the name or the id of a dimension in the workspace.
Returns
the index of the dimension in the workspace.
Exceptions
runtime_error if the requested dimension is unknown either by id, or by name in the workspace.
Definition at line 104 of file MaskMD.cpp.
Referenced by Mantid::MDAlgorithms::MaskMD::exec(), and Mantid::MDAlgorithms::MaskMD::validateInputs().
versus()
template<typename T > std::string Mantid::MDAlgorithms::versus (T a, T b)
Return a string "(a vs b)".
Definition at line 187 of file CompareMDWorkspaces.cpp.
References Mantid::Kernel::Strings::toString().
Referenced by Mantid::MDAlgorithms::CompareMDWorkspaces::compare(), Mantid::MDAlgorithms::CompareMDWorkspaces::compareMDHistoWorkspaces(), and Mantid::MDAlgorithms::CompareMDWorkspaces::compareTol().
volumeNormalisationOption()
std::string Mantid::MDAlgorithms::volumeNormalisationOption ()
Non-member defining the volume normalisation option.
Returns
volume normalisation option.
Definition at line 39 of file QueryMDWorkspace.cpp.
Referenced by Mantid::MDAlgorithms::QueryMDWorkspace::init(), and whichNormalisation().
whichNormalisation()
Mantid::API::MDNormalization Mantid::MDAlgorithms::whichNormalisation (const std::string & strNormalisation)
Non-member method to interpret an normalisation option.
Parameters
strNormalisation string normalisation property value.
Returns
MDNormalisation option.
Definition at line 52 of file QueryMDWorkspace.cpp.
References noNormalisationOption(), Mantid::API::NoNormalization, Mantid::API::NumEventsNormalization, volumeNormalisationOption(), and Mantid::API::VolumeNormalization.
Referenced by Mantid::MDAlgorithms::QueryMDWorkspace::exec().
Variable Documentation
BIGNUMBER
const double Mantid::MDAlgorithms::BIGNUMBER = 1.0E100
Definition at line 34 of file ConvertCWPDMDToSpectra.cpp.
Referenced by Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary().
DODEBUG
bool Mantid::MDAlgorithms::DODEBUG = true
Definition at line 43 of file ConvertToDiffractionMDWorkspace.cpp.
Referenced by Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec().
THRESHOLD_SIGNAL
const signal_t Mantid::MDAlgorithms::THRESHOLD_SIGNAL = 0
Definition at line 29 of file IntegratePeaksCWSD.cpp.
Referenced by Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration().