Mantid: Mantid::DataObjects::MDHistoWorkspaceIterator Class Reference
Mantid::DataObjects::MDHistoWorkspaceIterator Class Reference
An implementation of IMDIterator that iterates through a MDHistoWorkspace.
#include <MDHistoWorkspaceIterator.h>
Public Member Functions
std::vector< size_t > findNeighbourIndexes () const override
Gets indexes of bins/pixels/boxes neighbouring the present iterator location.
std::vector< size_t > findNeighbourIndexesByWidth (const int &width) const
Find vertex-touching neighbours.
std::vector< size_t > findNeighbourIndexesByWidth (const std::vector< int > &widths) const
Find vertex-touching neighbours.
std::pair< std::vector< size_t >, std::vector< bool > > findNeighbourIndexesByWidth1D (const int &width, const int &width_dimension) const
Find vertex-touching neighbours.
std::vector< size_t > findNeighbourIndexesFaceTouching () const override
Find neighbor indexes, but only return those that are face-touching.
VecMDExtents getBoxExtents () const
Get the extents in n-dimensions corresponding to the position of the box of the current iterator.
Mantid::Kernel::VMD getCenter () const override
Returns the position of the center of the box pointed to.
size_t getDataSize () const override
signal_t getError () const override
Returns the error for this box, same as innerError.
int32_t getInnerDetectorID (size_t index) const override
For a given event/point in this box, return the detector ID.
signal_t getInnerError (size_t index) const override
Returns the error of a given event.
uint16_t getInnerExpInfoIndex (size_t index) const override
For a given event/point in this box, return the associated experiment-info index.
uint16_t getInnerGoniometerIndex (size_t index) const override
For a given event/point in this box, return the goniometer index.
coord_t getInnerPosition (size_t index, size_t dimension) const override
Returns the position of a given event for a given dimension.
signal_t getInnerSignal (size_t index) const override
Returns the signal of a given event.
bool getIsMasked () const override
Returns true if masking is used.
size_t getLinearIndex () const override
Getter for the linear index.
signal_t getNormalizedError () const override
Returns the normalized error for this box.
signal_t getNormalizedSignal () const override
Returns the normalized signal for this box.
size_t getNumEvents () const override
Returns the number of events/points contained in this box.
virtual signal_t getNumEventsFraction () const
Returns the number of events/points contained in this box.
signal_t getSignal () const override
Returns the signal for this box, same as innerSignal.
std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices) const override
Return a list of vertexes defining the volume pointed to.
std::unique_ptr< coord_t[]> getVertexesArray (size_t &numVertices, const size_t outDimensions, const bool *maskDim) const override
Return a list of vertexes defining the volume pointed to, enable masking of dimensions.
void init (const MDHistoWorkspace *workspace, Mantid::Geometry::MDImplicitFunction *function, size_t beginPos=0, size_t endPos=size_t(-1))
Constructor helper.
bool isWithinBounds (size_t index) const override
void jumpTo (size_t index) override
Jump to the index^th cell.
virtual coord_t jumpToNearest (const Mantid::Kernel::VMD &fromLocation)
Jump the iterator to the nearest valid position correspoinding to the centre current position of the desired iterator position.
MDHistoWorkspaceIterator (const MDHistoWorkspace *workspace, Mantid::Geometry::MDImplicitFunction *function=nullptr, size_t beginPos=0, size_t endPos=size_t(-1))
Constructor.
MDHistoWorkspaceIterator (const MDHistoWorkspace *workspace, SkippingPolicy *skippingPolicy, Mantid::Geometry::MDImplicitFunction *function=nullptr, size_t beginPos=0, size_t endPos=size_t(-1))
Constructor.
MDHistoWorkspaceIterator (const MDHistoWorkspace_const_sptr &workspace, Mantid::Geometry::MDImplicitFunction *function=nullptr, size_t beginPos=0, size_t endPos=size_t(-1))
Constructor.
MDHistoWorkspaceIterator (const MDHistoWorkspace_const_sptr &workspace, SkippingPolicy *skippingPolicy, Mantid::Geometry::MDImplicitFunction *function=nullptr, size_t beginPos=0, size_t endPos=size_t(-1))
Constructor.
bool next () override
Advance to the next cell.
bool next (size_t skip) override
Advance, skipping a certain number of cells.
size_t permutationCacheSize () const
bool valid () const override
~MDHistoWorkspaceIterator () override
Destructor.
Public Member Functions inherited from Mantid::API::IMDIterator
Mantid::API::MDNormalization getNormalization () const
IMDIterator ()
Default constructor.
void setNormalization (Mantid::API::MDNormalization normalization)
Set how the signal will be normalized when calling getNormalizedSignal()
virtual ~IMDIterator ()=default
Protected Member Functions
std::vector< int64_t > createPermutations (const std::vector< int > &widths) const
Create or fetch permutations relating to a given neighbour width.
Protected Attributes
uint64_t m_begin
The beginning linear index in the workspace.
coord_t * m_binWidth
Width of each bin in each dimension.
coord_t * m_center
Center of the current box. Not set until getCenter() is called.
std::unique_ptr< Mantid::Geometry::MDImplicitFunction > m_function
Implicit function to limit volume searched.
size_t * m_index
Index into each dimension.
size_t * m_indexMaker
Array to find indices from linear indices.
size_t * m_indexMax
Index into each dimension.
uint64_t m_max
The maximum linear index in the workspace.
size_t m_nd
Number of dimensions.
coord_t * m_origin
Origin (index 0,0,0) in the space = the minimum of each dimension.
std::vector< int64_t > m_permutationsFaceTouching
Neigbour finding permutations for face touching neighbours (3 by 3 width).
PermutationsMap m_permutationsVertexTouchingMap
Neighbour finding permutations map for vertex touching.
uint64_t m_pos
The linear position/index into the MDHistoWorkspace.
SkippingPolicy_scptr m_skippingPolicy
Skipping policy.
const MDHistoWorkspace * m_ws
The MDHistoWorkspace being iterated.
Protected Attributes inherited from Mantid::API::IMDIterator
Mantid::API::MDNormalization m_normalization
Normalization method for getNormalizedSignal()
Detailed Description
An implementation of IMDIterator that iterates through a MDHistoWorkspace.
It treats the bin in the workspace as a box containing a single "event", at the center of each bin and with the proper signal/error.
Author
Janik Zikovsky
Date
2011-10-06
Definition at line 36 of file MDHistoWorkspaceIterator.h.
Constructor & Destructor Documentation
MDHistoWorkspaceIterator() [1/4]
Mantid::DataObjects::MDHistoWorkspaceIterator::MDHistoWorkspaceIterator (const MDHistoWorkspace_const_sptr & workspace, SkippingPolicy * skippingPolicy, Mantid::Geometry::MDImplicitFunction * function = nullptr, size_t beginPos = 0, size_t endPos = size_t(-1))
Constructor.
Parameters
workspace :: MDHistoWorkspace_sptr being iterated
skippingPolicy :: The skipping policy to use.
function :: The implicit function to use. Becomes owned by this object.
beginPos :: Start position
endPos :: End position
Definition at line 112 of file MDHistoWorkspaceIterator.cpp.
References init(), and workspace.
MDHistoWorkspaceIterator() [2/4]
Mantid::DataObjects::MDHistoWorkspaceIterator::MDHistoWorkspaceIterator (const MDHistoWorkspace * workspace, SkippingPolicy * skippingPolicy, Mantid::Geometry::MDImplicitFunction * function = nullptr, size_t beginPos = 0, size_t endPos = size_t(-1))
Constructor.
Parameters
workspace :: MDHistoWorkspace_sptr being iterated
function :: The implicit function to use. Becomes owned by this object.
skippingPolicy :: The skipping policy to use
beginPos :: Start position
endPos :: End position
Definition at line 130 of file MDHistoWorkspaceIterator.cpp.
References init(), and workspace.
MDHistoWorkspaceIterator() [3/4]
Mantid::DataObjects::MDHistoWorkspaceIterator::MDHistoWorkspaceIterator (const MDHistoWorkspace_const_sptr & workspace, Mantid::Geometry::MDImplicitFunction * function = nullptr, size_t beginPos = 0, size_t endPos = size_t(-1))
Constructor.
Parameters
workspace :: MDHistoWorkspace_sptr being iterated
function :: The implicit function to use. Becomes owned by this object.
beginPos :: start position
endPos :: end position
Definition at line 81 of file MDHistoWorkspaceIterator.cpp.
References init(), and workspace.
MDHistoWorkspaceIterator() [4/4]
Mantid::DataObjects::MDHistoWorkspaceIterator::MDHistoWorkspaceIterator (const MDHistoWorkspace * workspace, Mantid::Geometry::MDImplicitFunction * function = nullptr, size_t beginPos = 0, size_t endPos = size_t(-1))
Constructor.
Parameters
workspace :: MDHistoWorkspace_sptr being iterated
function :: The implicit function to use. Becomes owned by this object.
beginPos
endPos
Definition at line 96 of file MDHistoWorkspaceIterator.cpp.
References init(), and workspace.
~MDHistoWorkspaceIterator()
Mantid::DataObjects::MDHistoWorkspaceIterator::~MDHistoWorkspaceIterator () override
Destructor.
Definition at line 224 of file MDHistoWorkspaceIterator.cpp.
References m_binWidth, m_center, m_index, m_indexMaker, m_indexMax, and m_origin.
Member Function Documentation
createPermutations()
std::vector< int64_t > Mantid::DataObjects::MDHistoWorkspaceIterator::createPermutations (const std::vector< int > & widths) const protected
Create or fetch permutations relating to a given neighbour width.
This is to create the permutations needed to operate find neighbours in the vertex-touching schenarios Rather than having to fabricate what the possible permutations are each time the iterator is moved and the method is called, we can cache the results, and re-use them as the only factors are the and the dimensionality, the width (n-neighbours).
Parameters
widths : vector of integer widths.
Returns
index permutations
Definition at line 519 of file MDHistoWorkspaceIterator.cpp.
References Mantid::API::MDGeometry::getDimension(), Mantid::Geometry::m, m_nd, m_permutationsVertexTouchingMap, and m_ws.
Referenced by findNeighbourIndexesByWidth(), and findNeighbourIndexesByWidth1D().
findNeighbourIndexes()
std::vector< size_t > Mantid::DataObjects::MDHistoWorkspaceIterator::findNeighbourIndexes () const override virtual
Gets indexes of bins/pixels/boxes neighbouring the present iterator location.
Return all vertex touching neighbours. The number of neighbour indexes returned will depend upon the dimensionality of the workspace as well as the presence of boundaries and edges.
FindNeighbours will return the indexes of neighbours even if they are unreachable from the current iterator. To verify that the indexes are reachable from the current iterator, run isWithinBounds. Note that this is only a concern where the workspace iteration is portioned up amongst >1 iterators.
Returns
vector of linear indexes to neighbour locations.
Implements Mantid::API::IMDIterator.
Definition at line 468 of file MDHistoWorkspaceIterator.cpp.
References findNeighbourIndexesByWidth().
findNeighbourIndexesByWidth() [1/2]
std::vector< size_t > Mantid::DataObjects::MDHistoWorkspaceIterator::findNeighbourIndexesByWidth (const int & width) const
Find vertex-touching neighbours.
Expands out the width to make a n-dimensional vector filled with the requested width.
Parameters
width : Odd number of pixels for all dimensions.
Returns
collection of indexes.
Definition at line 582 of file MDHistoWorkspaceIterator.cpp.
References findNeighbourIndexesByWidth(), and m_nd.
Referenced by findNeighbourIndexes(), and findNeighbourIndexesByWidth().
findNeighbourIndexesByWidth() [2/2]
std::vector< size_t > Mantid::DataObjects::MDHistoWorkspaceIterator::findNeighbourIndexesByWidth (const std::vector< int > & widths) const
Find vertex-touching neighbours.
Parameters
widths : Vector containing odd number of pixels per dimension. Entries match dimensions of iterator.
Returns
collection of indexes.
Definition at line 593 of file MDHistoWorkspaceIterator.cpp.
References createPermutations(), Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), Mantid::Kernel::Utils::isNeighbourOfSubject(), m_index, m_indexMaker, m_indexMax, m_nd, and m_pos.
findNeighbourIndexesByWidth1D()
std::pair< std::vector< size_t >, std::vector< bool > > Mantid::DataObjects::MDHistoWorkspaceIterator::findNeighbourIndexesByWidth1D (const int & width, const int & width_dimension) const
Find vertex-touching neighbours.
This function always returns a vector of indexes which has a size equal to the product of the widths. This is because it also returns a vector of bools (of the same size) which records the validity of each index, rather than removing invalid indexes from the list. This function only allows a width vector to have one non-singleton dimension. NB, the index of the central pixel is included in the output array.
Parameters
width : Width in the non-singleton dimension
width_dimension : The non-singleton dimension of the widths vector
Returns
collection of indexes.
Definition at line 636 of file MDHistoWorkspaceIterator.cpp.
References createPermutations(), Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), Mantid::Kernel::Utils::isNeighbourOfSubject(), m_index, m_indexMaker, m_indexMax, m_nd, and m_pos.
findNeighbourIndexesFaceTouching()
std::vector< size_t > Mantid::DataObjects::MDHistoWorkspaceIterator::findNeighbourIndexesFaceTouching () const override virtual
Find neighbor indexes, but only return those that are face-touching.
Will return the indexes of neighbours even if they are unreachable from the current iterator. To verify that the indexes are reachable from the current iterator, run isWithinBounds. Note that this is only a concern where the workspace iteration is portioned up amongst >1 iterators.
Returns
Implements Mantid::API::IMDIterator.
Definition at line 483 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), Mantid::Kernel::Utils::isNeighbourOfSubject(), m_index, m_indexMaker, m_indexMax, m_nd, m_permutationsFaceTouching, and m_pos.
getBoxExtents()
VecMDExtents Mantid::DataObjects::MDHistoWorkspaceIterator::getBoxExtents () const
Get the extents in n-dimensions corresponding to the position of the box of the current iterator.
Returns
pairs of min/max extents.
Definition at line 387 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Geometry::d, Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), m_binWidth, m_index, m_indexMaker, m_indexMax, m_nd, m_origin, and m_pos.
Referenced by performWeightedSum().
getCenter()
Mantid::Kernel::VMD Mantid::DataObjects::MDHistoWorkspaceIterator::getCenter () const override virtual
Returns the position of the center of the box pointed to.
Implements Mantid::API::IMDIterator.
Definition at line 372 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Geometry::d, Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), m_binWidth, m_center, m_index, m_indexMaker, m_indexMax, m_nd, m_origin, and m_pos.
getDataSize()
size_t Mantid::DataObjects::MDHistoWorkspaceIterator::getDataSize () const override virtual
Returns
the number of points to be iterated on
Implements Mantid::API::IMDIterator.
Definition at line 234 of file MDHistoWorkspaceIterator.cpp.
References m_begin, and m_max.
getError()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getError () const override virtual
Returns the error for this box, same as innerError.
Implements Mantid::API::IMDIterator.
Definition at line 353 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getErrorAt(), m_pos, and m_ws.
Referenced by performWeightedSum().
getInnerDetectorID()
int32_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerDetectorID (size_t index) const override virtual
For a given event/point in this box, return the detector ID.
Implements Mantid::API::IMDIterator.
Definition at line 428 of file MDHistoWorkspaceIterator.cpp.
getInnerError()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerError (size_t index) const override virtual
Returns the error of a given event.
Implements Mantid::API::IMDIterator.
Definition at line 443 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getErrorAt(), m_pos, and m_ws.
getInnerExpInfoIndex()
uint16_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerExpInfoIndex (size_t index) const override virtual
For a given event/point in this box, return the associated experiment-info index.
Implements Mantid::API::IMDIterator.
Definition at line 414 of file MDHistoWorkspaceIterator.cpp.
getInnerGoniometerIndex()
uint16_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerGoniometerIndex (size_t index) const override virtual
For a given event/point in this box, return the goniometer index.
Implements Mantid::API::IMDIterator.
Definition at line 421 of file MDHistoWorkspaceIterator.cpp.
getInnerPosition()
coord_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerPosition (size_t index, size_t dimension) const override virtual
Returns the position of a given event for a given dimension.
Implements Mantid::API::IMDIterator.
Definition at line 435 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getCenter(), m_pos, and m_ws.
getInnerSignal()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getInnerSignal (size_t index) const override virtual
Returns the signal of a given event.
Implements Mantid::API::IMDIterator.
Definition at line 440 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getSignalAt(), m_pos, and m_ws.
getIsMasked()
bool Mantid::DataObjects::MDHistoWorkspaceIterator::getIsMasked () const override virtual
Returns true if masking is used.
Implements Mantid::API::IMDIterator.
Definition at line 445 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getIsMaskedAt(), m_pos, and m_ws.
Referenced by performWeightedSum().
getLinearIndex()
size_t Mantid::DataObjects::MDHistoWorkspaceIterator::getLinearIndex () const override virtual
Getter for the linear index.
Returns
the linear index.
Implements Mantid::API::IMDIterator.
Definition at line 451 of file MDHistoWorkspaceIterator.cpp.
References m_pos.
Referenced by Mantid::MDAlgorithms::ReplicateMD::exec().
getNormalizedError()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getNormalizedError () const override virtual
Returns the normalized error for this box.
Implements Mantid::API::IMDIterator.
Definition at line 334 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getErrorAt(), Mantid::DataObjects::MDHistoWorkspace::getInverseVolume(), Mantid::DataObjects::MDHistoWorkspace::getNumEventsAt(), Mantid::API::IMDIterator::m_normalization, m_pos, m_ws, Mantid::API::NoNormalization, Mantid::API::NumEventsNormalization, and Mantid::API::VolumeNormalization.
getNormalizedSignal()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getNormalizedSignal () const override virtual
Returns the normalized signal for this box.
Implements Mantid::API::IMDIterator.
Definition at line 318 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getInverseVolume(), Mantid::DataObjects::MDHistoWorkspace::getNumEventsAt(), Mantid::DataObjects::MDHistoWorkspace::getSignalAt(), Mantid::API::IMDIterator::m_normalization, m_pos, m_ws, Mantid::API::NoNormalization, Mantid::API::NumEventsNormalization, and Mantid::API::VolumeNormalization.
getNumEvents()
size_t Mantid::DataObjects::MDHistoWorkspaceIterator::getNumEvents () const override virtual
Returns the number of events/points contained in this box.
Returns
truncated number of events
Implements Mantid::API::IMDIterator.
Definition at line 405 of file MDHistoWorkspaceIterator.cpp.
References getNumEventsFraction().
getNumEventsFraction()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getNumEventsFraction () const virtual
Returns the number of events/points contained in this box.
Returns
eact number of events (weights may be applied)
Definition at line 410 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getNumEventsAt(), m_pos, and m_ws.
Referenced by getNumEvents(), and performWeightedSum().
getSignal()
signal_t Mantid::DataObjects::MDHistoWorkspaceIterator::getSignal () const override virtual
Returns the signal for this box, same as innerSignal.
Implements Mantid::API::IMDIterator.
Definition at line 350 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getSignalAt(), m_pos, and m_ws.
Referenced by performWeightedSum().
getVertexesArray() [1/2]
std::unique_ptr< coord_t[]> Mantid::DataObjects::MDHistoWorkspaceIterator::getVertexesArray (size_t & numVertices) const override virtual
Return a list of vertexes defining the volume pointed to.
Implements Mantid::API::IMDIterator.
Definition at line 356 of file MDHistoWorkspaceIterator.cpp.
References Mantid::DataObjects::MDHistoWorkspace::getVertexesArray(), m_pos, and m_ws.
getVertexesArray() [2/2]
std::unique_ptr< coord_t[]> Mantid::DataObjects::MDHistoWorkspaceIterator::getVertexesArray (size_t & numVertices, const size_t outDimensions, const bool * maskDim) const override virtual
Return a list of vertexes defining the volume pointed to, enable masking of dimensions.
Implements Mantid::API::IMDIterator.
Definition at line 361 of file MDHistoWorkspaceIterator.cpp.
References UNUSED_ARG.
init()
void Mantid::DataObjects::MDHistoWorkspaceIterator::init (const MDHistoWorkspace * workspace, Mantid::Geometry::MDImplicitFunction * function, size_t beginPos = 0, size_t endPos = size_t(-1))
Constructor helper.
Parameters
workspace :: MDWorkspace
function :: implicit function or NULL for none. Gains ownership of the pointer.
beginPos :: Start position
endPos :: End position
Definition at line 145 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Geometry::d, Mantid::API::MDGeometry::getDimension(), Mantid::Kernel::Utils::NestedForLoop::GetIndicesFromLinearIndex(), Mantid::DataObjects::MDHistoWorkspace::getNPoints(), Mantid::API::MDGeometry::getNumDims(), m_begin, m_binWidth, m_center, m_function, m_index, m_indexMaker, m_indexMax, m_max, m_nd, m_origin, m_permutationsFaceTouching, m_pos, m_ws, next(), Mantid::Kernel::Utils::NestedForLoop::SetUp(), Mantid::Kernel::Utils::NestedForLoop::SetUpIndexMaker(), valid(), and workspace.
Referenced by MDHistoWorkspaceIterator(), MDHistoWorkspaceIterator(), MDHistoWorkspaceIterator(), and MDHistoWorkspaceIterator().
isWithinBounds()
bool Mantid::DataObjects::MDHistoWorkspaceIterator::isWithinBounds (size_t index) const override virtual
Parameters
index : linear index to inspect against iterator
Returns
True only if the index is between the min and max bounds of the iterator.
Implements Mantid::API::IMDIterator.
Definition at line 507 of file MDHistoWorkspaceIterator.cpp.
References index, m_begin, and m_max.
jumpTo()
void Mantid::DataObjects::MDHistoWorkspaceIterator::jumpTo (size_t index) override virtual
Jump to the index^th cell.
No range checking is performed, for performance reasons!
Parameters
index :: point to jump to. Must be 0 <= index < getDataSize().
Implements Mantid::API::IMDIterator.
Definition at line 242 of file MDHistoWorkspaceIterator.cpp.
References index, m_begin, and m_pos.
Referenced by jumpToNearest().
jumpToNearest()
Mantid::coord_t Mantid::DataObjects::MDHistoWorkspaceIterator::jumpToNearest (const Mantid::Kernel::VMD & fromLocation) virtual
Jump the iterator to the nearest valid position correspoinding to the centre current position of the desired iterator position.
Parameters
fromLocation : destination or nearest to.
Returns
absolute distance of end position from requested position.
Definition at line 250 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Geometry::d, Mantid::Kernel::Utils::NestedForLoop::GetLinearIndex(), jumpTo(), m_binWidth, m_indexMaker, m_indexMax, m_nd, and m_origin.
next() [1/2]
bool Mantid::DataObjects::MDHistoWorkspaceIterator::next () override virtual
Advance to the next cell.
If the current cell is the last one in the workspace do nothing and return false.
Returns
true if you can continue iterating
Implements Mantid::API::IMDIterator.
Definition at line 280 of file MDHistoWorkspaceIterator.cpp.
References Mantid::Geometry::d, Mantid::Kernel::Utils::NestedForLoop::Increment(), m_binWidth, m_center, m_function, m_index, m_indexMax, m_max, m_nd, m_origin, m_pos, and m_skippingPolicy.
Referenced by init().
next() [2/2]
bool Mantid::DataObjects::MDHistoWorkspaceIterator::next (size_t skip) override virtual
Advance, skipping a certain number of cells.
Parameters
skip :: how many to increase. If 1, then every point will be sampled.
Implements Mantid::API::IMDIterator.
Definition at line 310 of file MDHistoWorkspaceIterator.cpp.
References m_max, and m_pos.
permutationCacheSize()
size_t Mantid::DataObjects::MDHistoWorkspaceIterator::permutationCacheSize () const
Returns
The size of the permutation cache.
Definition at line 676 of file MDHistoWorkspaceIterator.cpp.
References m_permutationsVertexTouchingMap.
valid()
bool Mantid::DataObjects::MDHistoWorkspaceIterator::valid () const override virtual
Returns
true if the iterator is valid. Check this at the start of an iteration, in case the very first point is not valid.
Implements Mantid::API::IMDIterator.
Definition at line 273 of file MDHistoWorkspaceIterator.cpp.
References m_max, and m_pos.
Referenced by init().
Member Data Documentation
m_begin
uint64_t Mantid::DataObjects::MDHistoWorkspaceIterator::m_begin protected
The beginning linear index in the workspace.
Definition at line 126 of file MDHistoWorkspaceIterator.h.
Referenced by getDataSize(), init(), isWithinBounds(), and jumpTo().
m_binWidth
coord_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_binWidth protected
Width of each bin in each dimension.
Definition at line 144 of file MDHistoWorkspaceIterator.h.
Referenced by getBoxExtents(), getCenter(), init(), jumpToNearest(), next(), and ~MDHistoWorkspaceIterator().
m_center
coord_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_center protected
Center of the current box. Not set until getCenter() is called.
Definition at line 138 of file MDHistoWorkspaceIterator.h.
Referenced by getCenter(), init(), next(), and ~MDHistoWorkspaceIterator().
m_function
std::unique_ptr<Mantid::Geometry::MDImplicitFunction> Mantid::DataObjects::MDHistoWorkspaceIterator::m_function protected
Implicit function to limit volume searched.
Definition at line 132 of file MDHistoWorkspaceIterator.h.
Referenced by init(), and next().
m_index
size_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_index protected
Index into each dimension.
Definition at line 147 of file MDHistoWorkspaceIterator.h.
Referenced by findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth1D(), findNeighbourIndexesFaceTouching(), getBoxExtents(), getCenter(), init(), next(), and ~MDHistoWorkspaceIterator().
m_indexMaker
size_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_indexMaker protected
Array to find indices from linear indices.
Definition at line 153 of file MDHistoWorkspaceIterator.h.
Referenced by findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth1D(), findNeighbourIndexesFaceTouching(), getBoxExtents(), getCenter(), init(), jumpToNearest(), and ~MDHistoWorkspaceIterator().
m_indexMax
size_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_indexMax protected
Index into each dimension.
Definition at line 150 of file MDHistoWorkspaceIterator.h.
Referenced by findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth1D(), findNeighbourIndexesFaceTouching(), getBoxExtents(), getCenter(), init(), jumpToNearest(), next(), and ~MDHistoWorkspaceIterator().
m_max
uint64_t Mantid::DataObjects::MDHistoWorkspaceIterator::m_max protected
The maximum linear index in the workspace.
Definition at line 129 of file MDHistoWorkspaceIterator.h.
Referenced by getDataSize(), init(), isWithinBounds(), next(), next(), and valid().
m_nd
size_t Mantid::DataObjects::MDHistoWorkspaceIterator::m_nd protected
Number of dimensions.
Definition at line 135 of file MDHistoWorkspaceIterator.h.
Referenced by createPermutations(), findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth1D(), findNeighbourIndexesFaceTouching(), getBoxExtents(), getCenter(), init(), jumpToNearest(), and next().
m_origin
coord_t* Mantid::DataObjects::MDHistoWorkspaceIterator::m_origin protected
Origin (index 0,0,0) in the space = the minimum of each dimension.
Definition at line 141 of file MDHistoWorkspaceIterator.h.
Referenced by getBoxExtents(), getCenter(), init(), jumpToNearest(), next(), and ~MDHistoWorkspaceIterator().
m_permutationsFaceTouching
std::vector<int64_t> Mantid::DataObjects::MDHistoWorkspaceIterator::m_permutationsFaceTouching mutable protected
Neigbour finding permutations for face touching neighbours (3 by 3 width).
Definition at line 156 of file MDHistoWorkspaceIterator.h.
Referenced by findNeighbourIndexesFaceTouching(), and init().
m_permutationsVertexTouchingMap
PermutationsMap Mantid::DataObjects::MDHistoWorkspaceIterator::m_permutationsVertexTouchingMap mutable protected
Neighbour finding permutations map for vertex touching.
Keyed via the width (n-pixels) of neighbours required.
Definition at line 160 of file MDHistoWorkspaceIterator.h.
Referenced by createPermutations(), and permutationCacheSize().
m_pos
uint64_t Mantid::DataObjects::MDHistoWorkspaceIterator::m_pos protected
The linear position/index into the MDHistoWorkspace.
Definition at line 123 of file MDHistoWorkspaceIterator.h.
Referenced by findNeighbourIndexesByWidth(), findNeighbourIndexesByWidth1D(), findNeighbourIndexesFaceTouching(), getBoxExtents(), getCenter(), getError(), getInnerError(), getInnerPosition(), getInnerSignal(), getIsMasked(), getLinearIndex(), getNormalizedError(), getNormalizedSignal(), getNumEventsFraction(), getSignal(), getVertexesArray(), init(), jumpTo(), next(), next(), and valid().
m_skippingPolicy
SkippingPolicy_scptr Mantid::DataObjects::MDHistoWorkspaceIterator::m_skippingPolicy protected
Skipping policy.
Definition at line 163 of file MDHistoWorkspaceIterator.h.
Referenced by next().
m_ws
const MDHistoWorkspace* Mantid::DataObjects::MDHistoWorkspaceIterator::m_ws protected
The MDHistoWorkspace being iterated.
Definition at line 120 of file MDHistoWorkspaceIterator.h.
Referenced by createPermutations(), getError(), getInnerError(), getInnerPosition(), getInnerSignal(), getIsMasked(), getNormalizedError(), getNormalizedSignal(), getNumEventsFraction(), getSignal(), getVertexesArray(), and init().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/MDHistoWorkspaceIterator.h
Framework/DataObjects/src/MDHistoWorkspaceIterator.cpp