Mantid: MantidQt::API::AlgorithmRuntimeProps Class Reference
MantidQt::API::AlgorithmRuntimeProps Class Reference final
#include <AlgorithmRuntimeProps.h>
Public Member Functions
AlgorithmRuntimeProps ()=default
AlgorithmRuntimeProps (AlgorithmRuntimeProps &&)=default
AlgorithmRuntimeProps (const AlgorithmRuntimeProps &)=default
TypedValue getProperty (const std::string &name) const noexcept override
Get the value of a property.
bool operator== (const Mantid::Kernel::IPropertyManager &other) override=delete
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
~AlgorithmRuntimeProps ()=default
Public Member Functions inherited from MantidQt::API::IAlgorithmRuntimeProps
virtual TypedValue getProperty (const std::string &name) const noexcept override=0
Get the value of a property.
IAlgorithmRuntimeProps ()=default
virtual bool operator== (const Mantid::Kernel::IPropertyManager &)=delete
template<typename T >
void setProperty (const std::string &name, const T &value)
virtual void setPropertyValue (const std::string &, const std::string &) override=0
Sets property value from a string.
virtual ~IAlgorithmRuntimeProps ()=default
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Private Member Functions inherited from Mantid::Kernel::PropertyManager
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
void clear () override
Clears the whole property map.
void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add or replace a property in the list of managed properties.
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
void declareProperty (std::unique_ptr< Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
void filterByProperty (const TimeSeriesProperty< bool > &filter, const std::vector< std::string > &excludedFromFiltering=std::vector< std::string >()) override
Filter the managed properties by the given boolean property mask.
void filterByTime (const Types::Core::DateAndTime &start, const Types::Core::DateAndTime &stop) override
Filter out a run by time.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
const std::vector< Property * > & getProperties () const override
Get the list of managed properties.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
bool operator!= (const PropertyManager &other) const
PropertyManager & operator+= (const PropertyManager &rhs)
Addition operator.
PropertyManager & operator= (const PropertyManager &)
Assignment operator - performs a deep copy.
bool operator== (const PropertyManager &other) const
size_t propertyCount () const override
Count the number of properties under management.
PropertyManager ()
Default constructor.
PropertyManager (const PropertyManager &)
copy constructor
void removeProperty (const std::string &name, const bool delproperty=true) override
removes the property from properties map
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by a json value collection.
void setProperties (const ::Json::Value &jsonValue, IPropertyManager *targetPropertyManager, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)
Set the ordered list of properties by a json value collection.
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const std::string &propertiesJson, IPropertyManager *targetPropertyManager, const std::unordered_set< std::string > &ignoreProperties, bool createMissing=false)
Set the ordered list of properties by one string of values, separated by semicolons.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value.
void splitByTime (std::vector< SplittingInterval > &splitter, std::vector< PropertyManager * > outputs) const override
Split a run by time (splits the TimeSeriesProperties contained).
std::unique_ptr< Property > takeProperty (const size_t index) override
removes the property from the properties map and returns a pointer to it
bool validateProperties () const override
Validates all the properties in the collection.
virtual ~PropertyManager () override
Virtual destructor.
Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
Property * getPointerToPropertyOrNull (const std::string &name) const
Get a property by name.
Private Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Private Member Functions inherited from Mantid::Kernel::PropertyManager
static std::string getInvalidValuesFilterLogName (const std::string &logName)
Gets the correct log name for the matching invalid values log for a given log name.
static std::string getLogNameFromInvalidValuesFilter (const std::string &logName)
static bool isAnInvalidValuesFilterLog (const std::string &logName)
Static Private Attributes inherited from Mantid::Kernel::PropertyManager
static const std::string INVALID_VALUES_SUFFIX = "_invalid_values"
Detailed Description
Definition at line 14 of file AlgorithmRuntimeProps.h.
Constructor & Destructor Documentation
AlgorithmRuntimeProps() [1/3]
MantidQt::API::AlgorithmRuntimeProps::AlgorithmRuntimeProps () default
AlgorithmRuntimeProps() [2/3]
MantidQt::API::AlgorithmRuntimeProps::AlgorithmRuntimeProps (const AlgorithmRuntimeProps &) default
AlgorithmRuntimeProps() [3/3]
MantidQt::API::AlgorithmRuntimeProps::AlgorithmRuntimeProps (AlgorithmRuntimeProps &&) default
~AlgorithmRuntimeProps()
MantidQt::API::AlgorithmRuntimeProps::~AlgorithmRuntimeProps () default
Member Function Documentation
getProperty()
Mantid::Kernel::IPropertyManager::TypedValue MantidQt::API::AlgorithmRuntimeProps::getProperty (const std::string & name) const override virtual noexcept
Get the value of a property.
Allows you to assign directly to a variable of the property's type (if a supported type).
*** This method does NOT work for assigning to an existing std::string. In this case you have to use getPropertyValue() instead. Note that you can, though, construct a local string variable by writing, e.g. std::string s = getProperty("myProperty"). ***
Parameters
name :: The name of the property
Returns
The value of the property. Will be cast to the desired type (if a supported type).
Exceptions
std::runtime_error If an attempt is made to assign a property to a different type
Exception::NotFoundError If the property requested does not exist
Reimplemented from Mantid::Kernel::PropertyManager.
Definition at line 15 of file AlgorithmRuntimeProps.cpp.
References Mantid::Kernel::PropertyManager::getProperty().
operator==()
bool MantidQt::API::AlgorithmRuntimeProps::operator== (const Mantid::Kernel::IPropertyManager & other) override virtual delete
Reimplemented from MantidQt::API::IAlgorithmRuntimeProps.
setPropertyValue()
void MantidQt::API::AlgorithmRuntimeProps::setPropertyValue (const std::string & name, const std::string & value) override virtual
Set the value of a property by string N.B.
bool properties must be set using 1/0 rather than true/false
Parameters
name :: The name of the property (case insensitive)
value :: The value to assign to the property
Exceptions
Exception::NotFoundError if the named property is unknown
std::invalid_argument If the value is not valid for the property given
Reimplemented from Mantid::Kernel::PropertyManager.
Definition at line 18 of file AlgorithmRuntimeProps.cpp.
References Mantid::Kernel::PropertyManager::declareProperty(), Mantid::Kernel::PropertyManager::existsProperty(), Mantid::Kernel::PropertyManager::setPropertyValue(), and value.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmRuntimeProps.h
qt/widgets/common/src/AlgorithmRuntimeProps.cpp