Mantid: Mantid::API::ParameterReference Class Reference
Mantid::API::ParameterReference Class Reference
A reference to a parameter in a function.
#include <ParameterReference.h>
Public Member Functions
IFunction * getLocalFunction () const
Return pointer to the local function.
std::size_t getLocalIndex () const
Return parameter index in the local function.
double getParameter () const
Get the value of the parameter.
bool isDefault () const
Returns the default value flag.
bool isParameterOf (const IFunction *fun) const
Find out if this refers to a parameter of a function: direct or via composite function member.
IFunction * ownerFunction () const
std::size_t parameterIndex () const
Return parameter index in the owning function.
std::string parameterName () const
Return parameter name in the owning function.
ParameterReference ()
Default constructor.
ParameterReference (IFunction *fun, std::size_t index, bool isDefault=false)
Constructor.
void setParameter (const double &value, bool isExplicitlySet=true)
Set the parameter.
virtual ~ParameterReference ()=default
Protected Member Functions
void reset (IFunction *fun, std::size_t index, bool isDefault=false)
Reset the reference.
Private Attributes
IFunction * m_function
Function that together with m_index uniquely identify the parameter.
std::size_t m_index
Index of the parameter in m_function.
bool m_isDefault
Flag to mark as default the value of an object associated with this reference: a tie or a constraint.
IFunction * m_owner
Function-owner of this reference.
Detailed Description
A reference to a parameter in a function.
To uniquely identify a parameter in a composite function
Author
Roman Tolchenov, Tessella Support Services plc
Date
26/02/2010
Definition at line 25 of file ParameterReference.h.
Constructor & Destructor Documentation
ParameterReference() [1/2]
Mantid::API::ParameterReference::ParameterReference ()
Default constructor.
Definition at line 13 of file ParameterReference.cpp.
ParameterReference() [2/2]
Mantid::API::ParameterReference::ParameterReference (IFunction * fun, std::size_t index, bool isDefault = false)
Constructor.
Parameters
fun :: Pointer to a function (composite or simple).
index :: Index of a parameter of fun
isDefault :: Flag to mark as default the value of an object associated with this reference: a tie or a constraint.
Definition at line 23 of file ParameterReference.cpp.
References index, isDefault(), and reset().
~ParameterReference()
virtual Mantid::API::ParameterReference::~ParameterReference () virtual default
Member Function Documentation
getLocalFunction()
IFunction * Mantid::API::ParameterReference::getLocalFunction () const
Return pointer to the local function.
Definition at line 29 of file ParameterReference.cpp.
References m_function.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), Mantid::API::ParameterTie::asString(), MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie(), Mantid::API::ParameterTie::findParametersOf(), Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameterIndex(), Mantid::API::CompositeFunction::getParameterIndex(), Mantid::API::FunctionGenerator::getParameterIndex(), Mantid::API::FunctionParameterDecorator::getParameterIndex(), and Mantid::API::ParamFunction::getParameterIndex().
getLocalIndex()
std::size_t Mantid::API::ParameterReference::getLocalIndex () const
Return parameter index in the local function.
Definition at line 32 of file ParameterReference.cpp.
References m_index.
Referenced by MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction(), MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie(), Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameterIndex(), Mantid::API::CompositeFunction::getParameterIndex(), Mantid::API::FunctionGenerator::getParameterIndex(), Mantid::API::FunctionParameterDecorator::getParameterIndex(), and Mantid::API::ParamFunction::getParameterIndex().
getParameter()
double Mantid::API::ParameterReference::getParameter () const
Get the value of the parameter.
Definition at line 76 of file ParameterReference.cpp.
References Mantid::API::IFunction::getParameter(), m_function, and m_index.
Referenced by Mantid::CurveFitting::Constraints::BoundaryConstraint::check(), Mantid::CurveFitting::Constraints::BoundaryConstraint::checkDeriv(), Mantid::CurveFitting::Constraints::BoundaryConstraint::checkDeriv2(), and Mantid::CurveFitting::Constraints::BoundaryConstraint::setParamToSatisfyConstraint().
isDefault()
bool Mantid::API::ParameterReference::isDefault () const
Returns the default value flag.
Definition at line 81 of file ParameterReference.cpp.
References m_isDefault.
Referenced by Mantid::CurveFitting::Constraints::BoundaryConstraint::BoundaryConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::BoundaryConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::initialize(), ParameterReference(), and reset().
isParameterOf()
bool Mantid::API::ParameterReference::isParameterOf (const IFunction * fun) const
Find out if this refers to a parameter of a function: direct or via composite function member.
Parameters
fun :: A function to check.
Definition at line 86 of file ParameterReference.cpp.
References Mantid::API::CompositeFunction::functionIndex(), m_function, and m_index.
ownerFunction()
IFunction * Mantid::API::ParameterReference::ownerFunction () const
Definition at line 78 of file ParameterReference.cpp.
References m_owner.
Referenced by Mantid::CurveFitting::Functions::CrystalFieldFunction::ignoreTie().
parameterIndex()
std::size_t Mantid::API::ParameterReference::parameterIndex () const
Return parameter index in the owning function.
Definition at line 35 of file ParameterReference.cpp.
References Mantid::API::IFunction::getParameterIndex(), and m_owner.
Referenced by parameterName().
parameterName()
std::string Mantid::API::ParameterReference::parameterName () const
Return parameter name in the owning function.
Definition at line 38 of file ParameterReference.cpp.
References m_owner, parameterIndex(), and Mantid::API::IFunction::parameterName().
Referenced by Mantid::CurveFitting::Constraints::BoundaryConstraint::asString(), Mantid::CurveFitting::Constraints::BoundaryConstraint::check(), Mantid::CurveFitting::Constraints::BoundaryConstraint::setParamToSatisfyConstraint(), and Mantid::CurveFitting::Functions::CrystalFieldSpectrum::writeToString().
reset()
void Mantid::API::ParameterReference::reset (IFunction * fun, std::size_t index, bool isDefault = false) protected
Reset the reference.
Parameters
fun :: Pointer to a function (composite or simple).
index :: Index of a parameter of fun
isDefault :: Flag to mark as default the value of an object associated with this reference: a tie or a constraint.
Definition at line 48 of file ParameterReference.cpp.
References Mantid::API::CompositeFunction::functionIndex(), Mantid::API::IFunction::getFunction(), index, isDefault(), m_function, m_index, m_isDefault, m_owner, and Mantid::API::IFunction::parameterIndex().
Referenced by Mantid::CurveFitting::Constraints::BoundaryConstraint::BoundaryConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::BoundaryConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::initialize(), and ParameterReference().
setParameter()
void Mantid::API::ParameterReference::setParameter (const double & value, bool isExplicitlySet = true)
Set the parameter.
Parameters
value :: A value to set.
isExplicitlySet :: Flag that user explicitly set this parameter.
Definition at line 71 of file ParameterReference.cpp.
References m_function, m_index, Mantid::API::IFunction::setParameter(), and value.
Referenced by Mantid::API::ParameterTie::eval(), and Mantid::CurveFitting::Constraints::BoundaryConstraint::setParamToSatisfyConstraint().
Member Data Documentation
m_function
IFunction* Mantid::API::ParameterReference::m_function private
Function that together with m_index uniquely identify the parameter.
Definition at line 48 of file ParameterReference.h.
Referenced by getLocalFunction(), getParameter(), isParameterOf(), reset(), and setParameter().
m_index
std::size_t Mantid::API::ParameterReference::m_index private
Index of the parameter in m_function.
It is assumed that this index uniquely identifies the parameter withing m_function
Definition at line 51 of file ParameterReference.h.
Referenced by getLocalIndex(), getParameter(), isParameterOf(), reset(), and setParameter().
m_isDefault
bool Mantid::API::ParameterReference::m_isDefault private
Flag to mark as default the value of an object associated with this reference: a tie or a constraint.
Definition at line 54 of file ParameterReference.h.
Referenced by isDefault(), and reset().
m_owner
IFunction* Mantid::API::ParameterReference::m_owner private
Function-owner of this reference.
parameterName() and parameterIndex() return values relative to this function.
Definition at line 46 of file ParameterReference.h.
Referenced by ownerFunction(), parameterIndex(), parameterName(), and reset().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/ParameterReference.h
Framework/API/src/ParameterReference.cpp