Mantid: Mantid::DataObjects::NoShape Class Reference
Mantid::DataObjects::NoShape Class Reference
PeakShapeNone : No peak shape.
#include <NoShape.h>
Public Member Functions
std::string algorithmName () const override
Return the algorithn name.
int algorithmVersion () const override
Return the algorithm version.
NoShape * clone () const override
Clone.
Kernel::SpecialCoordinateSystem frame () const override
Get the coordinate frame.
boost::optional< double > radius (RadiusType) const override
Radius.
std::string shapeName () const override
Return the shape name.
std::string toJSON () const override
Serialize.
Public Member Functions inherited from Mantid::Geometry::PeakShape
virtual std::string algorithmName () const =0
Algorithm.
virtual int algorithmVersion () const =0
Algorithm Version.
virtual PeakShape * clone () const =0
Deep copy this.
virtual Mantid::Kernel::SpecialCoordinateSystem frame () const =0
Coordinte frame used upon creation.
virtual boost::optional< double > radius (RadiusType type) const =0
Radius.
virtual std::string shapeName () const =0
Shape name.
virtual std::string toJSON () const =0
Serialize.
virtual ~PeakShape ()=default
Destructor.
Static Public Member Functions
static const std::string noShapeName ()
Return the shape name.
Additional Inherited Members
Public Types inherited from Mantid::Geometry::PeakShape
enum RadiusType { Radius = 0 , OuterRadius = 1 , InnerRadius = 2 }
For selecting different radius types.
Detailed Description
PeakShapeNone : No peak shape.
Null Object. For unintegrated peaks.
Definition at line 17 of file NoShape.h.
Member Function Documentation
algorithmName()
std::string Mantid::DataObjects::NoShape::algorithmName () const override virtual
Return the algorithn name.
Implements Mantid::Geometry::PeakShape.
Definition at line 33 of file NoShape.cpp.
algorithmVersion()
int Mantid::DataObjects::NoShape::algorithmVersion () const override virtual
Return the algorithm version.
Implements Mantid::Geometry::PeakShape.
Definition at line 35 of file NoShape.cpp.
clone()
NoShape * Mantid::DataObjects::NoShape::clone () const override virtual
Clone.
Clone object as deep copy.
Returns
pointer to new object
Implements Mantid::Geometry::PeakShape.
Definition at line 31 of file NoShape.cpp.
frame()
Kernel::SpecialCoordinateSystem Mantid::DataObjects::NoShape::frame () const override virtual
Get the coordinate frame.
Implements Mantid::Geometry::PeakShape.
Definition at line 43 of file NoShape.cpp.
References Mantid::Kernel::None.
noShapeName()
const std::string Mantid::DataObjects::NoShape::noShapeName () static
Return the shape name.
Definition at line 45 of file NoShape.cpp.
Referenced by shapeName().
radius()
boost::optional< double > Mantid::DataObjects::NoShape::radius (RadiusType type) const inline override virtual
Radius.
Implements Mantid::Geometry::PeakShape.
Definition at line 32 of file NoShape.h.
shapeName()
std::string Mantid::DataObjects::NoShape::shapeName () const override virtual
Return the shape name.
Return the unique shape name associated with this type.
Returns
Shape name
Implements Mantid::Geometry::PeakShape.
Definition at line 41 of file NoShape.cpp.
References noShapeName().
Referenced by toJSON().
toJSON()
std::string Mantid::DataObjects::NoShape::toJSON () const override virtual
Serialize.
Serialize to JSON object.
Returns
JSON object as std::string
Implements Mantid::Geometry::PeakShape.
Definition at line 18 of file NoShape.cpp.
References shapeName().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/NoShape.h
Framework/DataObjects/src/NoShape.cpp