Mantid: Mantid::API::IPeaksWorkspace Class Reference
Mantid::API::IPeaksWorkspace Class Reference abstract
Interface to the class Mantid::DataObjects::PeaksWorkspace.
#include <IPeaksWorkspace.h>
Public Member Functions
virtual void addPeak (const Kernel::V3D &position, const Kernel::SpecialCoordinateSystem &frame)=0
Add a peak to the list.
virtual void addPeak (const Mantid::Geometry::IPeak &ipeak)=0
Add a peak to the list.
IPeaksWorkspace_uptr clone () const
Returns a clone of the workspace.
virtual API::ITableWorkspace_sptr createDetectorTable () const =0
Creates a new TableWorkspace giving the IDs of the detectors that contribute to the peak.
virtual std::unique_ptr< Geometry::IPeak > createPeak () const =0
Create an instance of a peak using default constructor.
virtual std::unique_ptr< Mantid::Geometry::IPeak > createPeak (const Mantid::Kernel::V3D &position, const Mantid::Kernel::SpecialCoordinateSystem &frame) const =0
Create an instance of a Peak.
virtual std::unique_ptr< Geometry::IPeak > createPeak (const Mantid::Kernel::V3D &QLabFrame, std::optional< double > detectorDistance=std::nullopt) const =0
Create an instance of a Peak.
virtual std::unique_ptr< Geometry::IPeak > createPeakHKL (const Mantid::Kernel::V3D &HKL) const =0
Create an instance of a peak using a V3D.
virtual std::unique_ptr< Mantid::Geometry::IPeak > createPeakQSample (const Mantid::Kernel::V3D &position) const =0
Create an instance of a Peak.
virtual std::string getConvention () const =0
virtual int getNumberPeaks () const =0
virtual const Mantid::Geometry::IPeak & getPeak (size_t const peakNum) const =0
Return a reference to the Peak (const version)
virtual Mantid::Geometry::IPeak & getPeak (size_t const peakNum)=0
Return a reference to the Peak.
Mantid::Geometry::IPeak * getPeakPtr (size_t const peakNum)
Return a pointer to the Peak.
virtual Kernel::SpecialCoordinateSystem getSpecialCoordinateSystem () const =0
Get the special coordinate system.
virtual bool hasIntegratedPeaks () const =0
Determine if the workspace has been integrated using a peaks integration algorithm.
IPeaksWorkspace ()
Ctor.
IPeaksWorkspace & operator= (const IPeaksWorkspace &other)=delete
virtual std::vector< std::pair< std::string, std::string > > peakInfo (const Kernel::V3D &QFrame, bool labCoords) const =0
virtual int peakInfoNumber (const Kernel::V3D &qLabFrame, bool labCoords) const =0
virtual void removePeak (int peakNum)=0
Removes the indicated peak.
virtual void removePeaks (std::vector< int > badPeaks)=0
virtual void saveNexus (Nexus::File *file) const =0
virtual void setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem)=0
Set the special coordinate system.
Public Member Functions inherited from Mantid::API::ITableWorkspace
virtual Column_sptr addColumn (const std::string &type, const std::string &name)=0
Creates a new column.
virtual bool addColumns (const std::string &type, const std::string &name, size_t n)
Creates n new columns of the same type.
TableRowHelper appendRow ()
Appends a row.
Boolean & Bool (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is bool.
template<class T >
T & cell (size_t row, size_t col)
Get the reference to the element in row row and column col.
ITableWorkspace_uptr clone () const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneColumns (const std::vector< std::string > &colNames) const
Returns a clone of the workspace.
ITableWorkspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
virtual size_t columnCount () const =0
Number of columns in the workspace.
virtual bool customSort () const
Does this type of TableWorkspace need a custom sorting call (e.g.
double & Double (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is double.
virtual void find (API::Boolean value, size_t &row, size_t col)=0
find method to get the index of API::Boolean value cell in a table workspace
virtual void find (const Mantid::Kernel::V3D &value, size_t &row, size_t col)=0
find method to get the index of Mantid::Kernel::V3D cell value in a table workspace
virtual void find (const std::string &value, size_t &row, size_t col)=0
find method to get the index of cellstd::string value in a table workspace
virtual void find (double value, size_t &row, size_t col)=0
find method to get the index of double cell value in a table workspace
virtual void find (float value, size_t &row, size_t col)=0
find method to get the index of float cell value in a table workspace
virtual void find (size_t value, size_t &row, size_t col)=0
find method to get the index of integer cell value in a table workspace
virtual Column_const_sptr getColumn (const std::string &name) const =0
Gets the shared pointer to a column by name.
virtual Column_sptr getColumn (const std::string &name)=0
Gets the shared pointer to a column by name.
virtual Column_const_sptr getColumn (size_t index) const =0
Gets the shared pointer to a column by index - return none-modifyable column.
virtual Column_sptr getColumn (size_t index)=0
Gets the shared pointer to a column by index.
virtual std::vector< std::string > getColumnNames () const =0
Returns a vector of all column names.
TableRowHelper getFirstRow ()
Creates a TableRow object for the first row (row == 0).
virtual API::LogManager_const_sptr getLogs () const =0
Get constant access to shared pointer containing workspace properties.
template<class T >
T & getRef (const std::string &name, size_t index)
Get a reference to a data element.
TableRowHelper getRow (size_t row)
Creates a TableRow object for row row.
TableColumnHelper getVector (const std::string &name)
Access the column with name name trough a ColumnVector object.
TableConstColumnHelper getVector (const std::string &name) const
Access the column with name name trough a ColumnVector object.
const std::string id () const override
Return the workspace typeID.
virtual size_t insertRow (size_t index)=0
Inserts a row before row pointed to by index and fills it with default vales.
int & Int (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is int.
ITableWorkspace ()
Constructor.
virtual API::LogManager_sptr logs ()=0
Get access to shared pointer containing workspace properties.
void modified ()
If the workspace is the AnalysisDataService sends AfterReplaceNotification.
ITableWorkspace & operator= (const ITableWorkspace &)=delete
virtual void removeColumn (const std::string &name)=0
Removes a column.
virtual void removeRow (size_t index)=0
Delets a row if it exists.
virtual size_t rowCount () const =0
Number of rows in the workspace.
virtual void setRowCount (size_t count)=0
Resizes the workspace.
virtual void sort (std::vector< std::pair< std::string, bool > > &criteria)
Overridable method to custom-sort the workspace.
std::string & String (size_t row, size_t col)
Get the reference to the element in row row and column col if its type is std::string.
const std::string toString () const override
Serializes the object to a string.
Public Member Functions inherited from Mantid::API::Workspace
Workspace_uptr clone () const
Returns a clone (copy) of the workspace with covariant return type in all derived classes.
Workspace_uptr cloneEmpty () const
Returns a default-initialized clone of the workspace.
const std::string & getComment () const
Get the workspace comment.
const WorkspaceHistory & getHistory () const
Returns a reference to the WorkspaceHistory const.
virtual size_t getMemorySize () const =0
Get the footprint in memory in bytes.
std::string getMemorySizeAsStr () const
Returns the memory footprint in sensible units.
const std::string & getName () const override
Get the workspace name.
const std::string & getPythonVariableName () const
virtual const std::string getTitle () const
Get the workspace title.
WorkspaceHistory & history ()
Returns a reference to the WorkspaceHistory.
bool isDirty (const int n=1) const
Check whether other algorithms have been applied to the workspace by checking the history length.
virtual bool isGroup () const
Workspace & operator= (const Workspace &other)=delete
void setComment (const std::string &)
Set the comment field of the workspace.
void setPythonVariableName (const std::string &)
virtual void setTitle (const std::string &)
Set the title of the workspace.
bool threadSafe () const override
Marks the workspace as safe for multiple threads to edit data simutaneously.
Workspace ()
~Workspace ()
Public Member Functions inherited from Mantid::Kernel::DataItem
DataItem ()
Default constructor.
DataItem (const DataItem &other)
Copy constructor Always makes a unique lock.
virtual ~DataItem ()
Destructor.
void readLock ()
Acquires a read lock.
void unlock ()
Public Member Functions inherited from Mantid::API::ExperimentInfo
virtual ExperimentInfo * cloneExperimentInfo () const
Clone us.
const Geometry::ComponentInfo & componentInfo () const
const Geometry::ParameterMap & constInstrumentParameters () const
Const version.
void copyExperimentInfoFrom (const ExperimentInfo *other)
Copy everything from the given experiment object.
const Geometry::DetectorInfo & detectorInfo () const
Return a const reference to the DetectorInfo object.
ExperimentInfo ()
Default constructor.
ExperimentInfo (const ExperimentInfo &)
Copy constructor.
std::string getAvailableWorkspaceEndDate () const
Return workspace end date as a formatted string (strftime style, as returned by Kernel::DateAdnTime) string, if available.
std::string getAvailableWorkspaceStartDate () const
Return workspace start date as a formatted string (strftime, as returned by Types::Core::DateAndTime) string, if available.
double getEFixed (const detid_t detID) const
Easy access to the efixed value for this run & detector ID.
double getEFixed (const std::shared_ptr< const Geometry::IDetector > &detector=std::shared_ptr< const Geometry::IDetector >{nullptr}) const
Easy access to the efixed value for this run & optional detector.
double getEFixedForIndirect (const std::shared_ptr< const Geometry::IDetector > &detector, const std::vector< std::string > &parameterNames) const
double getEFixedGivenEMode (const std::shared_ptr< const Geometry::IDetector > &detector, const Kernel::DeltaEMode::Type emode) const
Easy access to the efixed value for this run & detector.
Kernel::DeltaEMode::Type getEMode () const
Returns the emode for this run.
Geometry::Instrument_const_sptr getInstrument () const
Returns the parameterized instrument.
Kernel::Property * getLog (const std::string &log) const
Access a log for this experiment.
double getLogAsSingleValue (const std::string &log) const
Access a single value from a log for this experiment.
int getRunNumber () const
Utility method to get the run number.
std::string getWorkspaceStartDate () const
Returns the start date for this experiment (or current time if no info available)
Geometry::ParameterMap & instrumentParameters ()
Returns a modifiable set of instrument parameters.
const Geometry::ParameterMap & instrumentParameters () const
Returns the set of parameters modifying the base instrument (const-version)
void invalidateSpectrumDefinition (const size_t index)
Notifies the ExperimentInfo that a spectrum definition has changed.
void loadExperimentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Loads an experiment description from the open NeXus file.
void loadExperimentInfoNexus (std::string const &nxFilename, Nexus::File *file, std::string &parameterStr, std::string const &prefix)
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file)
Load the instrument from an open NeXus file without reading any parameters.
void loadInstrumentInfoNexus (const std::string &nxFilename, Nexus::File *file, std::string &parameterStr)
Load the instrument from an open NeXus file.
void loadInstrumentParametersNexus (Nexus::File *file, std::string &parameterStr)
Load instrument parameters from an open Nexus file in Instrument group if found there.
void loadSampleAndLogInfoNexus (Nexus::File *file)
Load the sample and log info from an open NeXus file.
void loadSampleAndLogInfoNexus (Nexus::File *file, std::string const &prefix)
Load the sample and log info from an open NeXus file.
Geometry::ComponentInfo & mutableComponentInfo ()
Geometry::DetectorInfo & mutableDetectorInfo ()
Return a non-const reference to the DetectorInfo object.
Run & mutableRun ()
Writable version of the run object.
Sample & mutableSample ()
Writable version of the sample object.
SpectrumInfo & mutableSpectrumInfo ()
Return a non-const reference to the SpectrumInfo object.
ExperimentInfo & operator= (const ExperimentInfo &)
Implements the copy assignment operator.
void populateInstrumentParameters ()
Add parameters to the instrument parameter map that are defined in instrument definition file or parameter file, which may contain parameters that require logfile data to be available.
void readParameterMap (const std::string &parameterStr)
Populate the parameter map given a string.
const Run & run () const
Run details object access.
const Sample & sample () const
Sample accessors.
void saveExperimentInfoNexus (Nexus::File *file, bool saveInstrument, bool saveSample, bool saveLogs) const
Saves this experiment description to the open NeXus file.
void saveExperimentInfoNexus (Nexus::File *file, bool saveLegacyInstrument=true) const
Saves this experiment description to the open NeXus file.
void setDetectorGrouping (const size_t index, const std::set< detid_t > &detIDs) const
Sets the detector grouping for the spectrum with the given index.
void setEFixed (const detid_t detID, const double value)
Set the efixed value for a given detector ID.
void setInstrument (const Geometry::Instrument_const_sptr &instr)
Instrument accessors.
void setNumberOfDetectorGroups (const size_t count) const
Sets the number of detector groups.
void setSharedRun (Kernel::cow_ptr< Run > run)
Set the run object. Use in particular to clear run without copying old run.
Kernel::cow_ptr< Run > sharedRun ()
Return the cow ptr of the run.
const SpectrumInfo & spectrumInfo () const
Return a reference to the SpectrumInfo object.
const std::string toString () const
Returns a string description of the object.
void updateSpectrumDefinitionIfNecessary (const size_t index) const
virtual ~ExperimentInfo ()
Virtual destructor.
Public Attributes
std::string m_convention
Protected Member Functions
IPeaksWorkspace (const IPeaksWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
const std::string toString () const override
Serializes the object to a string.
Protected Member Functions inherited from Mantid::API::ITableWorkspace
void insertInColumn (Column *c, size_t index)
Insert a new element into a column.
ITableWorkspace (const ITableWorkspace &)=default
Protected copy constructor. May be used by childs for cloning.
void removeFromColumn (Column *c, size_t index)
Remove an element from a column.
void resizeColumn (Column *c, size_t size)
Resize a column.
Protected Member Functions inherited from Mantid::API::Workspace
Workspace (const Workspace &)
Protected copy constructor. May be used by childs for cloning.
Protected Member Functions inherited from Mantid::Kernel::DataItem
Poco::RWLock * getLock () const
Private method to access the RWLock object.
Protected Member Functions inherited from Mantid::API::ExperimentInfo
size_t numberOfDetectorGroups () const
Returns the number of detector groups.
virtual void populateIfNotLoaded () const
Called as the first operation of most public methods.
void setSpectrumDefinitions (Kernel::cow_ptr< std::vector< SpectrumDefinition > > spectrumDefinitions)
Sets the SpectrumDefinition for all spectra.
virtual void updateCachedDetectorGrouping (const size_t index) const
Update detector grouping for spectrum with given index.
Private Member Functions
IPeaksWorkspace * doClone () const override=0
Virtual clone method. Not implemented to force implementation in children.
Additional Inherited Members
Protected Attributes inherited from Mantid::API::ExperimentInfo
std::shared_ptr< Geometry::ParameterMap > m_parmap
Parameters modifying the base instrument.
Geometry::Instrument_const_sptr sptr_instrument
The base (unparametrized) instrument.
Detailed Description
Interface to the class Mantid::DataObjects::PeaksWorkspace.
The class PeaksWorkspace stores information about a set of SCD peaks.
Author
Ruth Mikkelson, SNS ORNL
Date
3/10/2010
Definition at line 33 of file IPeaksWorkspace.h.
Constructor & Destructor Documentation
IPeaksWorkspace() [1/2]
Mantid::API::IPeaksWorkspace::IPeaksWorkspace () inline
Ctor.
Definition at line 36 of file IPeaksWorkspace.h.
IPeaksWorkspace() [2/2]
Mantid::API::IPeaksWorkspace::IPeaksWorkspace (const IPeaksWorkspace &) protected default
Protected copy constructor. May be used by childs for cloning.
References Mantid::Kernel::toString().
Member Function Documentation
addPeak() [1/2]
virtual void Mantid::API::IPeaksWorkspace::addPeak (const Kernel::V3D & position, const Kernel::SpecialCoordinateSystem & frame) pure virtual
Add a peak to the list.
Parameters
position :: V3D positon of the peak.
frame :: Coordinate system frame of the peak position.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
addPeak() [2/2]
virtual void Mantid::API::IPeaksWorkspace::addPeak (const Mantid::Geometry::IPeak & ipeak) pure virtual
Add a peak to the list.
Parameters
ipeak :: Peak object to add (copy) into this.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
Referenced by Mantid::Crystal::FilterPeaks::filterPeaks(), and Mantid::Crystal::FilterPeaks::filterPeaksStr().
clone()
IPeaksWorkspace_uptr Mantid::API::IPeaksWorkspace::clone () const inline
Returns a clone of the workspace.
Definition at line 41 of file IPeaksWorkspace.h.
createDetectorTable()
virtual API::ITableWorkspace_sptr Mantid::API::IPeaksWorkspace::createDetectorTable () const pure virtual
Creates a new TableWorkspace giving the IDs of the detectors that contribute to the peak.
Returns
A shared pointer to a TableWorkspace containing the information
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
createPeak() [1/3]
virtual std::unique_ptr< Geometry::IPeak > Mantid::API::IPeaksWorkspace::createPeak () const pure virtual
Create an instance of a peak using default constructor.
Returns
a pointer to a new Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
createPeak() [2/3]
virtual std::unique_ptr< Mantid::Geometry::IPeak > Mantid::API::IPeaksWorkspace::createPeak (const Mantid::Kernel::V3D & position, const Mantid::Kernel::SpecialCoordinateSystem & frame) const pure virtual
Create an instance of a Peak.
Parameters
position :: enter of the peak in the specified frame
frame :: the coordinate frame that the position is specified in.
Returns
a pointer to a new Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
createPeak() [3/3]
virtual std::unique_ptr< Geometry::IPeak > Mantid::API::IPeaksWorkspace::createPeak (const Mantid::Kernel::V3D & QLabFrame, std::optional< double > detectorDistance = std::nullopt) const pure virtual
Create an instance of a Peak.
Parameters
QLabFrame :: Q of the center of the peak in the lab frame, in reciprocal space
detectorDistance :: Optional distance between the sample and the detector. Calculated if not provided.
Returns
a pointer to a new Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
createPeakHKL()
virtual std::unique_ptr< Geometry::IPeak > Mantid::API::IPeaksWorkspace::createPeakHKL (const Mantid::Kernel::V3D & HKL) const pure virtual
Create an instance of a peak using a V3D.
Parameters
HKL V3D
Returns
a pointer to a new Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
createPeakQSample()
virtual std::unique_ptr< Mantid::Geometry::IPeak > Mantid::API::IPeaksWorkspace::createPeakQSample (const Mantid::Kernel::V3D & position) const pure virtual
Create an instance of a Peak.
Parameters
position :: enter of the peak in the sample frame
Returns
a pointer to a new Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
doClone()
IPeaksWorkspace * Mantid::API::IPeaksWorkspace::doClone () const override private pure virtual
Virtual clone method. Not implemented to force implementation in children.
Implements Mantid::API::Workspace.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
getConvention()
virtual std::string Mantid::API::IPeaksWorkspace::getConvention () const pure virtual
Returns
the number of peaks
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
getNumberPeaks()
virtual int Mantid::API::IPeaksWorkspace::getNumberPeaks () const pure virtual
Returns
the number of peaks
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
Referenced by export_IPeaksWorkspace(), Mantid::Crystal::FilterPeaks::filterPeaks(), and Mantid::Crystal::FilterPeaks::filterPeaksStr().
getPeak() [1/2]
virtual const Mantid::Geometry::IPeak & Mantid::API::IPeaksWorkspace::getPeak (size_t const peakNum) const pure virtual
Return a reference to the Peak (const version)
Parameters
peakNum :: index of the peak to get.
Returns
a reference to a Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
getPeak() [2/2]
virtual Mantid::Geometry::IPeak & Mantid::API::IPeaksWorkspace::getPeak (size_t const peakNum) pure virtual
Return a reference to the Peak.
Parameters
peakNum :: index of the peak to get.
Returns
a reference to a Peak object.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
Referenced by Mantid::Crystal::FilterPeaks::filterPeaks(), and Mantid::Crystal::FilterPeaks::filterPeaksStr().
getPeakPtr()
Mantid::Geometry::IPeak * Mantid::API::IPeaksWorkspace::getPeakPtr (size_t const peakNum) inline
Return a pointer to the Peak.
Parameters
peakNum :: index of the peak to get.
Returns
a pointer to a Peak object.
Definition at line 93 of file IPeaksWorkspace.h.
Referenced by export_IPeaksWorkspace().
getSpecialCoordinateSystem()
virtual Kernel::SpecialCoordinateSystem Mantid::API::IPeaksWorkspace::getSpecialCoordinateSystem () const pure virtual
Get the special coordinate system.
Returns
special Q3D coordinate system to use being used by this PeaksWorkspace object. Probably the one the workspace was generated with.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
hasIntegratedPeaks()
virtual bool Mantid::API::IPeaksWorkspace::hasIntegratedPeaks () const pure virtual
Determine if the workspace has been integrated using a peaks integration algorithm.
Returns
TRUE if the workspace has been integrated.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
Referenced by export_IPeaksWorkspace().
operator=()
IPeaksWorkspace & Mantid::API::IPeaksWorkspace::operator= (const IPeaksWorkspace & other) delete
peakInfo()
virtual std::vector< std::pair< std::string, std::string > > Mantid::API::IPeaksWorkspace::peakInfo (const Kernel::V3D & QFrame, bool labCoords) const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
peakInfoNumber()
virtual int Mantid::API::IPeaksWorkspace::peakInfoNumber (const Kernel::V3D & qLabFrame, bool labCoords) const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
Referenced by export_IPeaksWorkspace().
removePeak()
virtual void Mantid::API::IPeaksWorkspace::removePeak (int peakNum) pure virtual
Removes the indicated peak.
Parameters
peakNum the peak to remove. peakNum starts at 0
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
removePeaks()
virtual void Mantid::API::IPeaksWorkspace::removePeaks (std::vector< int > badPeaks) pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
saveNexus()
virtual void Mantid::API::IPeaksWorkspace::saveNexus (Nexus::File * file) const pure virtual
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
setCoordinateSystem()
virtual void Mantid::API::IPeaksWorkspace::setCoordinateSystem (const Kernel::SpecialCoordinateSystem coordinateSystem) pure virtual
Set the special coordinate system.
Parameters
coordinateSystem : Special Q3D coordinate system to use.
Implemented in Mantid::DataObjects::LeanElasticPeaksWorkspace, and Mantid::DataObjects::PeaksWorkspace.
toString()
const std::string Mantid::API::IPeaksWorkspace::toString () const override protected virtual
Serializes the object to a string.
Implements Mantid::Kernel::DataItem.
Definition at line 18 of file IPeaksWorkspace.cpp.
References m_convention, Mantid::API::ExperimentInfo::toString(), and Mantid::API::ITableWorkspace::toString().
Member Data Documentation
m_convention
std::string Mantid::API::IPeaksWorkspace::m_convention
Definition at line 172 of file IPeaksWorkspace.h.
Referenced by Mantid::DataObjects::LeanElasticPeaksWorkspace::getConvention(), Mantid::DataObjects::PeaksWorkspace::getConvention(), and toString().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/IPeaksWorkspace.h
Framework/API/src/IPeaksWorkspace.cpp