Mantid: MantidQt::MantidWidgets::ImageInfoWidgetMini Class Reference
MantidQt::MantidWidgets::ImageInfoWidgetMini Class Reference
A table widget containing information about the pixel the mouse is over in an image.
#include <ImageInfoWidgetMini.h>
Public Member Functions
void cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > &extraValues) override
void hideColumn (const int index) override
ImageInfoWidgetMini (QWidget *parent=nullptr)
Constructor.
void setColumnCount (const int count) override
void setItem (const int rowIndex, const int columnIndex, QTableWidgetItem *item) override
void setRowCount (const int count) override
void setWorkspace (const Mantid::API::Workspace_sptr &ws) override
Set the workspace to probe for information.
void showColumn (const int index) override
void showInfo (const ImageInfoModel::ImageInfo &info) override
Display the information provided within the table cells.
Public Member Functions inherited from MantidQt::MantidWidgets::IImageInfoWidget
virtual ~IImageInfoWidget ()=default
Private Attributes
std::unique_ptr< ImageInfoPresenter > m_presenter
Detailed Description
A table widget containing information about the pixel the mouse is over in an image.
Definition at line 22 of file ImageInfoWidgetMini.h.
Constructor & Destructor Documentation
ImageInfoWidgetMini()
MantidQt::MantidWidgets::ImageInfoWidgetMini::ImageInfoWidgetMini (QWidget * parent = nullptr)
Constructor.
Parameters
parent A QWidget to act as the parent widget
Definition at line 20 of file ImageInfoWidgetMini.cpp.
Member Function Documentation
cursorAt()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::cursorAt (const double x, const double y, const double signal, const QMap< QString, QString > & extraValues) override virtual
Parameters
x X position if the cursor
y Y position if the cursor
signal Signal value at cursor position
extraValues A map of extra column names and values to display
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 29 of file ImageInfoWidgetMini.cpp.
References m_presenter, Mantid::Geometry::x, and Mantid::Geometry::y.
hideColumn()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::hideColumn (const int index) override virtual
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 61 of file ImageInfoWidgetMini.cpp.
setColumnCount()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::setColumnCount (const int count) override virtual
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 59 of file ImageInfoWidgetMini.cpp.
setItem()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::setItem (const int rowIndex, const int columnIndex, QTableWidgetItem * item) override virtual
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 60 of file ImageInfoWidgetMini.cpp.
setRowCount()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::setRowCount (const int count) override virtual
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 58 of file ImageInfoWidgetMini.cpp.
setWorkspace()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::setWorkspace (const Mantid::API::Workspace_sptr & ws) override virtual
Set the workspace to probe for information.
Parameters
ws A pointer to a Workspace object
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 56 of file ImageInfoWidgetMini.cpp.
References m_presenter.
showColumn()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::showColumn (const int index) override virtual
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 62 of file ImageInfoWidgetMini.cpp.
showInfo()
void MantidQt::MantidWidgets::ImageInfoWidgetMini::showInfo (const ImageInfoModel::ImageInfo & info) override virtual
Display the information provided within the table cells.
Parameters
info A reference to a collection of header/value pairs
Implements MantidQt::MantidWidgets::IImageInfoWidget.
Definition at line 38 of file ImageInfoWidgetMini.cpp.
References MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::empty(), MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::name(), and MantidQt::MantidWidgets::ImageInfoModel::ImageInfo::value().
Member Data Documentation
m_presenter
std::unique_ptr<ImageInfoPresenter> MantidQt::MantidWidgets::ImageInfoWidgetMini::m_presenter private
Definition at line 41 of file ImageInfoWidgetMini.h.
Referenced by cursorAt(), and setWorkspace().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ImageInfoWidgetMini.h
qt/widgets/common/src/ImageInfoWidgetMini.cpp