Mantid: MantidQt::MantidWidgets::Batch::Cell Class Reference
MantidQt::MantidWidgets::Batch::Cell Class Reference
#include <Cell.h>
Public Types
enum class Direction { INPUT , OUTPUT }
Public Member Functions
std::string const & backgroundColor () const
std::string const & borderColor () const
int borderOpacity () const
int borderThickness () const
Cell (std::string contentText)
Cell (std::string contentText, std::string backgroundColor, int borderThickness, std::string color, int borderOpacity, bool isEditable)
std::string const & contentText () const
void disableEditing ()
void enableEditing ()
std::string const & foregroundColor () const
std::string const & iconFilePath () const
bool isEditable () const
bool isInput () const
bool isOutput () const
void setBackgroundColor (std::string const &backgroundColor)
void setBorderColor (std::string const &borderColor)
void setBorderOpacity (int transparency)
void setBorderThickness (int borderThickness)
void setContentText (std::string const &contentText)
void setEditable (bool isEditable)
void setForegroundColor (std::string const &foregroundColor)
void setIconFilePath (std::string const &iconPath)
void setInput ()
void setOutput ()
void setToolTip (std::string const &toolTip)
std::string const & toolTip () const
Static Public Attributes
static constexpr const char * INPUT_FOREGROUND_COLOR = "#000000"
static constexpr const char * OUTPUT_FOREGROUND_COLOR = "#808080"
Private Attributes
std::string m_backgroundColor
std::string m_borderColor
int m_borderOpacity
int m_borderThickness
std::string m_contentText
Direction m_direction
std::string m_foregroundColor
std::string m_iconFilePath
bool m_isEditable
std::string m_toolTip
Detailed Description
Definition at line 20 of file Cell.h.
Member Enumeration Documentation
Direction
enum class MantidQt::MantidWidgets::Batch::Cell::Direction strong
Enumerator
INPUT
OUTPUT
Definition at line 23 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/2]
MantidQt::MantidWidgets::Batch::Cell::Cell (std::string contentText)
Definition at line 19 of file Cell.cpp.
Cell() [2/2]
MantidQt::MantidWidgets::Batch::Cell::Cell (std::string contentText, std::string backgroundColor, int borderThickness, std::string color, int borderOpacity, bool isEditable)
Definition at line 13 of file Cell.cpp.
Member Function Documentation
backgroundColor()
std::string const & MantidQt::MantidWidgets::Batch::Cell::backgroundColor () const
Definition at line 53 of file Cell.cpp.
References m_backgroundColor.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), and setBackgroundColor().
borderColor()
std::string const & MantidQt::MantidWidgets::Batch::Cell::borderColor () const
Definition at line 31 of file Cell.cpp.
References m_borderColor.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), MantidQt::MantidWidgets::Batch::operator==(), and setBorderColor().
borderOpacity()
int MantidQt::MantidWidgets::Batch::Cell::borderOpacity () const
Definition at line 33 of file Cell.cpp.
References m_borderOpacity.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), and setBorderOpacity().
borderThickness()
int MantidQt::MantidWidgets::Batch::Cell::borderThickness () const
Definition at line 29 of file Cell.cpp.
References m_borderThickness.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), MantidQt::MantidWidgets::Batch::operator==(), and setBorderThickness().
contentText()
std::string const & MantidQt::MantidWidgets::Batch::Cell::contentText () const
Definition at line 23 of file Cell.cpp.
References m_contentText.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), MantidQt::MantidWidgets::Batch::JobTreeView::commitData(), MantidQt::MantidWidgets::Batch::operator<<(), MantidQt::MantidWidgets::Batch::operator==(), and setContentText().
disableEditing()
void MantidQt::MantidWidgets::Batch::Cell::disableEditing ()
Definition at line 65 of file Cell.cpp.
References m_isEditable.
enableEditing()
void MantidQt::MantidWidgets::Batch::Cell::enableEditing ()
Definition at line 67 of file Cell.cpp.
References m_isEditable.
foregroundColor()
std::string const & MantidQt::MantidWidgets::Batch::Cell::foregroundColor () const
Definition at line 55 of file Cell.cpp.
References m_foregroundColor.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), and setForegroundColor().
iconFilePath()
std::string const & MantidQt::MantidWidgets::Batch::Cell::iconFilePath () const
Definition at line 61 of file Cell.cpp.
References m_iconFilePath.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), and setIconFilePath().
isEditable()
bool MantidQt::MantidWidgets::Batch::Cell::isEditable () const
Definition at line 27 of file Cell.cpp.
References m_isEditable.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), MantidQt::MantidWidgets::Batch::JobTreeView::closeEditorIfCellIsUneditable(), MantidQt::MantidWidgets::Batch::operator==(), and setEditable().
isInput()
bool MantidQt::MantidWidgets::Batch::Cell::isInput () const
Definition at line 69 of file Cell.cpp.
References INPUT, and m_direction.
isOutput()
bool MantidQt::MantidWidgets::Batch::Cell::isOutput () const
Definition at line 71 of file Cell.cpp.
References m_direction, and OUTPUT.
setBackgroundColor()
void MantidQt::MantidWidgets::Batch::Cell::setBackgroundColor (std::string const & backgroundColor)
Definition at line 43 of file Cell.cpp.
References backgroundColor(), and m_backgroundColor.
setBorderColor()
void MantidQt::MantidWidgets::Batch::Cell::setBorderColor (std::string const & borderColor)
Definition at line 41 of file Cell.cpp.
References borderColor(), and m_borderColor.
setBorderOpacity()
void MantidQt::MantidWidgets::Batch::Cell::setBorderOpacity (int transparency)
Definition at line 57 of file Cell.cpp.
References borderOpacity(), and m_borderOpacity.
setBorderThickness()
void MantidQt::MantidWidgets::Batch::Cell::setBorderThickness (int borderThickness)
Definition at line 39 of file Cell.cpp.
References borderThickness(), and m_borderThickness.
setContentText()
void MantidQt::MantidWidgets::Batch::Cell::setContentText (std::string const & contentText)
Definition at line 35 of file Cell.cpp.
References contentText(), and m_contentText.
setEditable()
void MantidQt::MantidWidgets::Batch::Cell::setEditable (bool isEditable)
Definition at line 63 of file Cell.cpp.
References isEditable(), and m_isEditable.
setForegroundColor()
void MantidQt::MantidWidgets::Batch::Cell::setForegroundColor (std::string const & foregroundColor)
Definition at line 45 of file Cell.cpp.
References foregroundColor(), INPUT, m_direction, m_foregroundColor, OUTPUT, and OUTPUT_FOREGROUND_COLOR.
setIconFilePath()
void MantidQt::MantidWidgets::Batch::Cell::setIconFilePath (std::string const & iconPath)
Definition at line 59 of file Cell.cpp.
References iconFilePath(), and m_iconFilePath.
setInput()
void MantidQt::MantidWidgets::Batch::Cell::setInput ()
Definition at line 73 of file Cell.cpp.
References INPUT, INPUT_FOREGROUND_COLOR, m_direction, and m_foregroundColor.
setOutput()
void MantidQt::MantidWidgets::Batch::Cell::setOutput ()
Definition at line 78 of file Cell.cpp.
References m_direction, m_foregroundColor, OUTPUT, and OUTPUT_FOREGROUND_COLOR.
setToolTip()
void MantidQt::MantidWidgets::Batch::Cell::setToolTip (std::string const & toolTip)
Definition at line 37 of file Cell.cpp.
References m_toolTip, and toolTip().
toolTip()
std::string const & MantidQt::MantidWidgets::Batch::Cell::toolTip () const
Definition at line 25 of file Cell.cpp.
References m_toolTip.
Referenced by MantidQt::MantidWidgets::Batch::applyCellPropertiesToItem(), and setToolTip().
Member Data Documentation
INPUT_FOREGROUND_COLOR
constexpr const char* MantidQt::MantidWidgets::Batch::Cell::INPUT_FOREGROUND_COLOR = "#000000" static constexpr
Definition at line 24 of file Cell.h.
Referenced by setInput().
m_backgroundColor
std::string MantidQt::MantidWidgets::Batch::Cell::m_backgroundColor private
Definition at line 66 of file Cell.h.
Referenced by backgroundColor(), and setBackgroundColor().
m_borderColor
std::string MantidQt::MantidWidgets::Batch::Cell::m_borderColor private
Definition at line 70 of file Cell.h.
Referenced by borderColor(), and setBorderColor().
m_borderOpacity
int MantidQt::MantidWidgets::Batch::Cell::m_borderOpacity private
Definition at line 69 of file Cell.h.
Referenced by borderOpacity(), and setBorderOpacity().
m_borderThickness
int MantidQt::MantidWidgets::Batch::Cell::m_borderThickness private
Definition at line 68 of file Cell.h.
Referenced by borderThickness(), and setBorderThickness().
m_contentText
std::string MantidQt::MantidWidgets::Batch::Cell::m_contentText private
Definition at line 65 of file Cell.h.
Referenced by contentText(), and setContentText().
m_direction
Direction MantidQt::MantidWidgets::Batch::Cell::m_direction private
Definition at line 74 of file Cell.h.
Referenced by isInput(), isOutput(), setForegroundColor(), setInput(), and setOutput().
m_foregroundColor
std::string MantidQt::MantidWidgets::Batch::Cell::m_foregroundColor private
Definition at line 67 of file Cell.h.
Referenced by foregroundColor(), setForegroundColor(), setInput(), and setOutput().
m_iconFilePath
std::string MantidQt::MantidWidgets::Batch::Cell::m_iconFilePath private
Definition at line 71 of file Cell.h.
Referenced by iconFilePath(), and setIconFilePath().
m_isEditable
bool MantidQt::MantidWidgets::Batch::Cell::m_isEditable private
Definition at line 72 of file Cell.h.
Referenced by disableEditing(), enableEditing(), isEditable(), and setEditable().
m_toolTip
std::string MantidQt::MantidWidgets::Batch::Cell::m_toolTip private
Definition at line 73 of file Cell.h.
Referenced by setToolTip(), and toolTip().
OUTPUT_FOREGROUND_COLOR
constexpr const char* MantidQt::MantidWidgets::Batch::Cell::OUTPUT_FOREGROUND_COLOR = "#808080" static constexpr
Definition at line 25 of file Cell.h.
Referenced by setForegroundColor(), and setOutput().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/Cell.h
qt/widgets/common/src/Batch/Cell.cpp