Mantid: Mantid::API::NumericAxis Class Reference
Mantid::API::NumericAxis Class Reference
Class to represent a numeric axis of a workspace.
#include <NumericAxis.h>
Public Member Functions
Axis * clone (const MatrixWorkspace *const parentWorkspace) override
Virtual constructor.
Axis * clone (const std::size_t length, const MatrixWorkspace *const parentWorkspace) override
Virtual constructor for axis of different length.
virtual std::vector< double > createBinBoundaries () const
Create bin boundaries from the point values.
virtual bool equalWithinTolerance (const Axis &axis2, const double tolerance) const
Check if two numeric axis are equivalent to a given tolerance.
double getMax () const override
returns max value defined on axis
double getMin () const override
returns min value defined on axis
virtual const std::vector< double > & getValues () const
Return a const reference to the values.
size_t indexOfValue (const double value) const override
Returns the index of the value wrt bin edge representation of the axis.
bool isNumeric () const override
Is the axis numeric - always true for this class.
std::string label (const std::size_t &index) const override
Returns a text label which shows the value corresponding to a bin index.
std::size_t length () const override
Get the length of the axis.
NumericAxis (const std::size_t &length)
Constructor.
NumericAxis (std::vector< double > centres)
Constructor taking a set of centre point values.
double operator() (const std::size_t &index, const std::size_t &verticalIndex=0) const override
Get a value at the specified index.
bool operator== (const Axis &) const override
Check if two axis defined as spectra or numeric axis are equivalent.
bool operator== (const NumericAxis &) const
Check if two NumericAxis are equivalent.
void setValue (const std::size_t &index, const double &value) override
Set the value at a specific index.
Public Member Functions inherited from Mantid::API::Axis
Axis ()
Constructor.
double getValue (const std::size_t &index, const std::size_t &verticalIndex=0) const
Gets the value at the specified index.
virtual bool isSpectra () const
Returns true is the axis is a Spectra axis.
virtual bool isText () const
Returns true if the axis is Text.
virtual const std::shared_ptr< Kernel::Unit > & setUnit (const std::string &unitName)
Set the unit on the Axis.
virtual specnum_t spectraNo (const std::size_t &index) const
Get the spectrum number.
std::string & title ()
Returns a reference to the user-defined title for this axis.
const std::string & title () const
Returns the user-defined title for this axis.
std::shared_ptr< Kernel::Unit > & unit ()
The unit object for this workspace (non const version)
const std::shared_ptr< Kernel::Unit > & unit () const
The unit for this axis.
virtual ~Axis ()=default
Protected Member Functions
std::string formatLabel (const double value) const
Get number label.
NumericAxis ()
Default constructor.
Protected Member Functions inherited from Mantid::API::Axis
Axis (const Axis &)=default
Axis & operator= (const Axis &)=default
Protected Attributes
std::vector< double > m_values
A vector holding the centre values.
Detailed Description
Class to represent a numeric axis of a workspace.
Author
Roman Tolchenov, Tessella plc
Date
05/07/2010
Definition at line 29 of file NumericAxis.h.
Constructor & Destructor Documentation
NumericAxis() [1/3]
Mantid::API::NumericAxis::NumericAxis (const std::size_t & length)
Constructor.
Parameters
length size of the numeric axis
Definition at line 61 of file NumericAxis.cpp.
NumericAxis() [2/3]
Mantid::API::NumericAxis::NumericAxis (std::vector< double > centres)
Constructor taking a set of centre point values.
Parameters
centres A vector of values to assign to the axis
Definition at line 67 of file NumericAxis.cpp.
NumericAxis() [3/3]
Mantid::API::NumericAxis::NumericAxis () protected default
Default constructor.
Sets values vectors to zero size.
Referenced by clone(), and clone().
Member Function Documentation
clone() [1/2]
Axis * Mantid::API::NumericAxis::clone (const MatrixWorkspace *const parentWorkspace) override virtual
Virtual constructor.
Parameters
parentWorkspace :: The workspace is not used in this implementation
Returns
A pointer to a copy of the NumericAxis on which the method is called
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 74 of file NumericAxis.cpp.
References NumericAxis(), and UNUSED_ARG.
clone() [2/2]
Axis * Mantid::API::NumericAxis::clone (const std::size_t length, const MatrixWorkspace *const parentWorkspace) override virtual
Virtual constructor for axis of different length.
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 79 of file NumericAxis.cpp.
References length(), NumericAxis(), and UNUSED_ARG.
createBinBoundaries()
std::vector< double > Mantid::API::NumericAxis::createBinBoundaries () const virtual
Create bin boundaries from the point values.
Create a set of bin boundaries from the centre point values.
Returns
A vector of bin boundaries
Reimplemented in Mantid::API::BinEdgeAxis, and Mantid::API::RefAxis.
Definition at line 180 of file NumericAxis.cpp.
References Mantid::Kernel::VectorHelper::convertToBinBoundary(), and m_values.
Referenced by Mantid::Algorithms::Rebin2D::exec().
equalWithinTolerance()
bool Mantid::API::NumericAxis::equalWithinTolerance (const Axis & axis2, const double tolerance) const virtual
Check if two numeric axis are equivalent to a given tolerance.
Parameters
axis2 :: Reference to the axis to compare to
tolerance :: Tolerance to compare to
Returns
true if self and second axis are equal
Reimplemented in Mantid::API::RefAxis.
Definition at line 133 of file NumericAxis.cpp.
References Mantid::API::Axis::length(), length(), m_values, and tolerance.
Referenced by operator==(), and operator==().
formatLabel()
std::string Mantid::API::NumericAxis::formatLabel (const double value) const protected
Get number label.
Formats a numeric label to a string.
Parameters
value the numeric value of the label
Returns
formatted value as string
Definition at line 157 of file NumericAxis.cpp.
References value.
Referenced by Mantid::API::BinEdgeAxis::label(), and label().
getMax()
double Mantid::API::NumericAxis::getMax () const inline override virtual
returns max value defined on axis
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 55 of file NumericAxis.h.
Referenced by Mantid::Algorithms::RingProfile::checkInputsForNumericWorkspace(), and Mantid::Algorithms::RadiusSum::getBoundariesOfNumericImage().
getMin()
double Mantid::API::NumericAxis::getMin () const inline override virtual
returns min value defined on axis
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 53 of file NumericAxis.h.
Referenced by Mantid::Algorithms::RingProfile::checkInputsForNumericWorkspace(), and Mantid::Algorithms::RadiusSum::getBoundariesOfNumericImage().
getValues()
const std::vector< double > & Mantid::API::NumericAxis::getValues () const virtual
Return a const reference to the values.
Get a const reference to the vector of values in this axis.
Returns
the values vector
Reimplemented in Mantid::API::RefAxis.
Definition at line 191 of file NumericAxis.cpp.
References m_values.
Referenced by Mantid::API::MatrixWorkspaceMDIterator::calcWorkspacePos(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::convertWsBothAxesToPoints(), Mantid::API::BinEdgeAxis::createBinBoundaries(), Mantid::Algorithms::Bin2DPowderDiffraction::normalizeToBinArea(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::validateInputs().
indexOfValue()
size_t Mantid::API::NumericAxis::indexOfValue (const double value) const override virtual
Returns the index of the value wrt bin edge representation of the axis.
Parameters
value A value to find in a bin
Returns
The index of the bin holding the value
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 54 of file NumericAxis.cpp.
References Mantid::Kernel::VectorHelper::indexOfValueFromCenters(), m_values, and value.
isNumeric()
bool Mantid::API::NumericAxis::isNumeric () const inline override virtual
Is the axis numeric - always true for this class.
Reimplemented from Mantid::API::Axis.
Definition at line 37 of file NumericAxis.h.
label()
std::string Mantid::API::NumericAxis::label (const std::size_t & index) const override virtual
Returns a text label which shows the value corresponding to a bin index.
Parameters
index :: The index of the bin, matches with the index of the value
Returns
the formatted string
Implements Mantid::API::Axis.
Definition at line 150 of file NumericAxis.cpp.
References formatLabel(), and index.
length()
std::size_t Mantid::API::NumericAxis::length () const inline override virtual
Get the length of the axis.
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 38 of file NumericAxis.h.
Referenced by Mantid::API::BinEdgeAxis::BinEdgeAxis(), Mantid::API::BinEdgeAxis::clone(), clone(), equalWithinTolerance(), Mantid::API::BinEdgeAxis::label(), Mantid::Algorithms::Bin2DPowderDiffraction::normalizeToBinArea(), operator()(), Mantid::API::BinEdgeAxis::setValue(), and setValue().
operator()()
double Mantid::API::NumericAxis::operator() (const std::size_t & index, const std::size_t & verticalIndex = 0) const override virtual
Get a value at the specified index.
Get the axis value at the position given.
Parameters
index The position along the axis for which the value is required
verticalIndex Needed for the subclass (RefAxis) method, but ignored (and defaulted) here
Returns
The value of the axis as a double
Exceptions
IndexError If the index requested is not in the range of this axis
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 94 of file NumericAxis.cpp.
References index, length(), m_values, and UNUSED_ARG.
operator==() [1/2]
bool Mantid::API::NumericAxis::operator== (const Axis & axis2) const override virtual
Check if two axis defined as spectra or numeric axis are equivalent.
Parameters
axis2 :: Reference to the axis to compare to
Returns
true if self and second axis are equal
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 126 of file NumericAxis.cpp.
References equalWithinTolerance().
operator==() [2/2]
bool Mantid::API::NumericAxis::operator== (const NumericAxis & axis2) const
Check if two NumericAxis are equivalent.
Parameters
axis2 :: Reference to the axis to compare to
Returns
true if self and second axis are equal
Definition at line 120 of file NumericAxis.cpp.
References equalWithinTolerance().
setValue()
void Mantid::API::NumericAxis::setValue (const std::size_t & index, const double & value) override virtual
Set the value at a specific index.
Sets the axis value at a given position.
Parameters
index :: The position along the axis for which to set the value
value :: The new value
Exceptions
IndexError If the index requested is not in the range of this axis
Implements Mantid::API::Axis.
Reimplemented in Mantid::API::RefAxis.
Definition at line 108 of file NumericAxis.cpp.
References index, length(), m_values, and value.
Referenced by Mantid::Algorithms::ExtractSpectra2::exec(), and Mantid::Algorithms::Integration::exec().
Member Data Documentation
m_values
std::vector<double> Mantid::API::NumericAxis::m_values protected
A vector holding the centre values.
Definition at line 62 of file NumericAxis.h.
Referenced by Mantid::API::BinEdgeAxis::BinEdgeAxis(), Mantid::API::BinEdgeAxis::BinEdgeAxis(), createBinBoundaries(), equalWithinTolerance(), getValues(), Mantid::API::BinEdgeAxis::indexOfValue(), indexOfValue(), operator()(), Mantid::API::BinEdgeAxis::setValue(), and setValue().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/NumericAxis.h
Framework/API/src/NumericAxis.cpp