Mantid: ICat4::ns1__searchText Class Reference
ICat4::ns1__searchText Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__searchText ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * entityName
int maxCount
std::string * query
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1206 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__searchText()
ICat4::ns1__searchText::ns1__searchText () inline
Definition at line 1220 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__searchText::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7276 of file ICat4C.cpp.
References entityName, maxCount, query, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_int().
Referenced by ICat4::soap_in_ns1__searchText(), ICat4::soap_new_req_ns1__searchText(), and ICat4::soap_new_set_ns1__searchText().
soap_get()
void * ICat4::ns1__searchText::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7401 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__searchText().
soap_in()
void * ICat4::ns1__searchText::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7317 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__searchText().
Referenced by ICat4::soap_in_ns1__searchText().
soap_out()
int ICat4::ns1__searchText::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7296 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__searchText().
Referenced by soap_put().
soap_put()
int ICat4::ns1__searchText::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7394 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__searchText.
soap_serialize()
void ICat4::ns1__searchText::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7285 of file ICat4C.cpp.
References entityName, maxCount, query, sessionId, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerTostd__string(), and SOAP_TYPE_ICat4_int.
Referenced by ICat4::soap_serialize_PointerTons1__getRemainingMinutesResponse().
soap_type()
int ICat4::ns1__searchText::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1213 of file ICat4Stub.h.
Member Data Documentation
entityName
std::string* ICat4::ns1__searchText::entityName
Definition at line 1211 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
maxCount
int ICat4::ns1__searchText::maxCount
Definition at line 1210 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
query
std::string* ICat4::ns1__searchText::query
Definition at line 1209 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
sessionId
std::string* ICat4::ns1__searchText::sessionId
Definition at line 1208 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp