Mantid: ICat4::ns1__facilityCycle Class Reference
ICat4::ns1__facilityCycle Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__facilityCycle ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * description
time_t * endDate
ns1__facility * facility
std::string * name
time_t * startDate
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1724 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__facilityCycle()
ICat4::ns1__facilityCycle::ns1__facilityCycle () inline
Definition at line 1739 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__facilityCycle::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14824 of file ICat4C.cpp.
Referenced by ICat4::soap_in_ns1__facilityCycle(), ICat4::soap_new_req_ns1__facilityCycle(), and ICat4::soap_new_set_ns1__facilityCycle().
soap_get()
void * ICat4::ns1__facilityCycle::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14997 of file ICat4C.cpp.
References ICat4::soap_get_ns1__facilityCycle().
soap_in()
void * ICat4::ns1__facilityCycle::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14881 of file ICat4C.cpp.
References ICat4::soap_in_ns1__facilityCycle().
Referenced by ICat4::soap_in_ns1__facilityCycle().
soap_out()
int ICat4::ns1__facilityCycle::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14848 of file ICat4C.cpp.
References ICat4::soap_out_ns1__facilityCycle().
soap_put()
int ICat4::ns1__facilityCycle::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14990 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__facilityCycle.
soap_serialize()
void ICat4::ns1__facilityCycle::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 14835 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_PointerTotime().
soap_type()
int ICat4::ns1__facilityCycle::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1732 of file ICat4Stub.h.
Member Data Documentation
description
std::string* ICat4::ns1__facilityCycle::description
Definition at line 1726 of file ICat4Stub.h.
endDate
time_t* ICat4::ns1__facilityCycle::endDate
Definition at line 1727 of file ICat4Stub.h.
facility
ns1__facility* ICat4::ns1__facilityCycle::facility
Definition at line 1728 of file ICat4Stub.h.
name
std::string* ICat4::ns1__facilityCycle::name
Definition at line 1729 of file ICat4Stub.h.
startDate
time_t* ICat4::ns1__facilityCycle::startDate
Definition at line 1730 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp