Mantid: Mantid::Geometry::SampleEnvironment Class Reference
Mantid::Geometry::SampleEnvironment Class Reference
Defines a single instance of a SampleEnvironment.
#include <SampleEnvironment.h>
Public Member Functions
void add (const IObject_const_sptr &component)
Geometry::BoundingBox boundingBox () const
const std::string containerID () const
const IObject & getComponent (const size_t index) const
Returns the requested IObject.
const IObject_const_sptr getComponentPtr (const size_t index) const
const Container & getContainer () const
int interceptSurfaces (Track &track) const
Update the given track with intersections within the environment.
bool isValid (const Kernel::V3D &point) const
Is the point given a valid point within the environment.
const std::string name () const
size_t nelements () const
SampleEnvironment (std::string name, const Container_const_sptr &getContainer)
Constructor specifying a name for the environment.
Private Attributes
std::vector< IObject_const_sptr > m_components
std::string m_name
Detailed Description
Defines a single instance of a SampleEnvironment.
It houses a single can along with the other components specified by a SampleEnvironmentSpec.
Definition at line 26 of file SampleEnvironment.h.
Constructor & Destructor Documentation
SampleEnvironment()
Mantid::Geometry::SampleEnvironment::SampleEnvironment (std::string name, const Container_const_sptr & container)
Constructor specifying a name for the environment.
It is empty by default and required by various other users of it
Parameters
name A human-readable name for the kit
container The object that represents the can
Definition at line 30 of file SampleEnvironment.cpp.
Member Function Documentation
add()
void Mantid::Geometry::SampleEnvironment::add (const IObject_const_sptr & component)
Parameters
component An object defining some component of the environment
Definition at line 86 of file SampleEnvironment.cpp.
References m_components.
boundingBox()
Geometry::BoundingBox Mantid::Geometry::SampleEnvironment::boundingBox () const
Returns
An axis-aligned BoundingBox object that encompasses the whole kit.
Definition at line 54 of file SampleEnvironment.cpp.
References Mantid::Geometry::BoundingBox::grow(), and m_components.
Referenced by Mantid::Algorithms::BeamProfileFactory::createBeamProfile(), Mantid::Algorithms::MCInteractionVolume::getFullBoundingBox(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareSampleBeamGeometry().
containerID()
const std::string Mantid::Geometry::SampleEnvironment::containerID () const inline
Returns
The name of can
Definition at line 33 of file SampleEnvironment.h.
getComponent()
const IObject & Mantid::Geometry::SampleEnvironment::getComponent (const size_t index) const
Returns the requested IObject.
The zero-th index is considered the container
Exceptions
std::out_of_range
Definition at line 33 of file SampleEnvironment.cpp.
References index, m_components, and nelements().
Referenced by Mantid::Algorithms::AbsorptionCorrection::constructSample(), export_SampleEnvironment(), Mantid::Algorithms::MCInteractionVolume::generatePointInObjectByIndex(), Mantid::Algorithms::MCInteractionStatistics::MCInteractionStatistics(), Mantid::Algorithms::MCInteractionVolume::MCInteractionVolume(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors().
getComponentPtr()
const IObject_const_sptr Mantid::Geometry::SampleEnvironment::getComponentPtr (const size_t index) const
Definition at line 42 of file SampleEnvironment.cpp.
References index, m_components, and nelements().
Referenced by Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors().
getContainer()
const Container & Mantid::Geometry::SampleEnvironment::getContainer () const inline
Returns
A const ptr to the can instance
Definition at line 35 of file SampleEnvironment.h.
Referenced by Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructSample(), export_SampleEnvironment(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors(), and Mantid::DataHandling::SetSample::setSampleShape().
interceptSurfaces()
int Mantid::Geometry::SampleEnvironment::interceptSurfaces (Track & track) const
Update the given track with intersections within the environment.
Parameters
track The track is updated with an intersection with the environment
Returns
The total number of segments added to the track
Definition at line 78 of file SampleEnvironment.cpp.
References m_components.
Referenced by Mantid::Algorithms::MCInteractionVolume::calculateBeforeAfterTrack(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::scatter(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::start_point().
isValid()
bool Mantid::Geometry::SampleEnvironment::isValid (const Kernel::V3D & point) const
Is the point given a valid point within the environment.
Parameters
point Is the point valid within the environment
Returns
True if the point is within the environment
Definition at line 67 of file SampleEnvironment.cpp.
References m_components.
name()
const std::string Mantid::Geometry::SampleEnvironment::name () const inline
Returns
The name of kit
Definition at line 31 of file SampleEnvironment.h.
nelements()
size_t Mantid::Geometry::SampleEnvironment::nelements () const inline
Returns
The number of elements the environment is composed of
Definition at line 42 of file SampleEnvironment.h.
Referenced by export_SampleEnvironment(), getComponent(), Mantid::Algorithms::MCInteractionVolume::getComponentIndex(), getComponentPtr(), Mantid::Algorithms::MCInteractionStatistics::MCInteractionStatistics(), Mantid::Algorithms::MCInteractionVolume::MCInteractionVolume(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::scatter(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::start_point().
Member Data Documentation
m_components
std::vector<IObject_const_sptr> Mantid::Geometry::SampleEnvironment::m_components private
Definition at line 62 of file SampleEnvironment.h.
Referenced by add(), boundingBox(), getComponent(), getComponentPtr(), interceptSurfaces(), and isValid().
m_name
std::string Mantid::Geometry::SampleEnvironment::m_name private
Definition at line 60 of file SampleEnvironment.h.
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/SampleEnvironment.h
Framework/Geometry/src/Instrument/SampleEnvironment.cpp