Mantid: Mantid::API::FuncMinimizerFactoryImpl Class Reference
Mantid::API::FuncMinimizerFactoryImpl Class Reference
The FuncMinimizerFactory class is in charge of the creation of concrete instances of minimizers.
#include <FuncMinimizerFactory.h>
Public Member Functions
std::shared_ptr< IFuncMinimizer > createMinimizer (const std::string &str) const
Creates an instance of a minimizer.
Public Member Functions inherited from Mantid::Kernel::DynamicFactory< IFuncMinimizer >
virtual std::shared_ptr< IFuncMinimizer > create (const std::string &className) const
Creates a new instance of the class with the given name.
virtual IFuncMinimizer * createUnwrapped (const std::string &className) const
Creates a new instance of the class with the given name, which is not wrapped in a boost shared_ptr.
void disableNotifications ()
Disable notifications.
DynamicFactory (const DynamicFactory &)=delete
void enableNotifications ()
Enable notifications.
bool exists (const std::string &className) const
Returns true if the given class is currently registered.
virtual const std::vector< std::string > getKeys () const
Returns the keys in the map.
DynamicFactory & operator= (const DynamicFactory &)=delete
void subscribe (const std::string &className)
Registers the instantiator for the given class with the DynamicFactory.
void subscribe (const std::string &className, std::unique_ptr< AbstractFactory > pAbstractFactory, SubscribeAction replace=ErrorIfExists)
Registers the instantiator for the given class with the DynamicFactory.
void unsubscribe (const std::string &className)
Unregisters the given class and deletes the instantiator for the class.
virtual ~DynamicFactory ()=default
Destroys the DynamicFactory and deletes the instantiators for all registered classes.
Private Member Functions
FuncMinimizerFactoryImpl ()
Private Constructor for singleton class.
Friends
struct Mantid::Kernel::CreateUsingNew< FuncMinimizerFactoryImpl >
Additional Inherited Members
Public Types inherited from Mantid::Kernel::DynamicFactory< IFuncMinimizer >
using AbstractFactory = AbstractInstantiator< IFuncMinimizer >
A typedef for the instantiator.
enum NotificationStatus
Defines the whether notifications are dispatched.
enum SubscribeAction
Defines replacement behaviour.
Public Attributes inherited from Mantid::Kernel::DynamicFactory< IFuncMinimizer >
Poco::NotificationCenter notificationCenter
Sends notifications to observers.
Protected Member Functions inherited from Mantid::Kernel::DynamicFactory< IFuncMinimizer >
DynamicFactory ()
Protected constructor for base class.
Detailed Description
The FuncMinimizerFactory class is in charge of the creation of concrete instances of minimizers.
It inherits most of its implementation from the Dynamic Factory base class. It is implemented as a singleton class.
Author
Anders Markvardsen, ISIS, RAL
Date
20/05/2010
Definition at line 36 of file FuncMinimizerFactory.h.
Constructor & Destructor Documentation
FuncMinimizerFactoryImpl()
Mantid::API::FuncMinimizerFactoryImpl::FuncMinimizerFactoryImpl () private
Private Constructor for singleton class.
Definition at line 16 of file FuncMinimizerFactory.cpp.
References Mantid::Kernel::SingletonHolder< T >::Instance().
Member Function Documentation
createMinimizer()
std::shared_ptr< IFuncMinimizer > Mantid::API::FuncMinimizerFactoryImpl::createMinimizer (const std::string & str) const
Creates an instance of a minimizer.
Parameters
str :: The minimizer initialization string which includes its type and optionally properties: "type,prop1=value1,prop2=value2"
Returns
A pointer to the created minimizer
Definition at line 29 of file FuncMinimizerFactory.cpp.
References Mantid::Kernel::DynamicFactory< IFuncMinimizer >::create(), n, Mantid::API::Expression::parse(), Mantid::API::Expression::size(), Mantid::API::Expression::str(), and Mantid::API::Expression::toList().
Friends And Related Function Documentation
Mantid::Kernel::CreateUsingNew< FuncMinimizerFactoryImpl >
friend struct Mantid::Kernel::CreateUsingNew< FuncMinimizerFactoryImpl > friend
Definition at line 39 of file FuncMinimizerFactory.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/FuncMinimizerFactory.h
Framework/API/src/FuncMinimizerFactory.cpp