Mantid: AlgHistoryProperties Class Reference
AlgHistoryProperties Class Reference
#include <AlgorithmHistoryWindow.h>
Public Slots
void copySelectedItemText ()
void popupMenu (const QPoint &pos)
Public Member Functions
AlgHistoryProperties (QWidget *w, std::vector< Mantid::Kernel::PropertyHistory_sptr > propHist)
void clearData ()
void displayAlgHistoryProperties ()
Populates the Algorithm History display with property names, values, directions and whether their values were the defaults.
const Mantid::Kernel::PropertyHistories & getAlgProperties ()
void setAlgProperties (const std::vector< Mantid::Kernel::PropertyHistory_sptr > &histProp)
Public Attributes
QTreeWidget * m_histpropTree
Private Attributes
QMenu * m_contextMenu
QAction * m_copyAction
std::vector< Mantid::Kernel::PropertyHistory_sptr > m_Histprop
QString m_selectedItemText
Detailed Description
Definition at line 181 of file AlgorithmHistoryWindow.h.
Constructor & Destructor Documentation
AlgHistoryProperties()
AlgHistoryProperties::AlgHistoryProperties (QWidget * w, std::vector< Mantid::Kernel::PropertyHistory_sptr > propHist)
Definition at line 511 of file AlgorithmHistoryWindow.cpp.
References copySelectedItemText(), m_contextMenu, m_copyAction, m_histpropTree, and popupMenu().
Member Function Documentation
clearData()
void AlgHistoryProperties::clearData ()
Definition at line 536 of file AlgorithmHistoryWindow.cpp.
References m_histpropTree.
Referenced by AlgorithmHistoryWindow::updateAlgHistoryProperties().
copySelectedItemText
void AlgHistoryProperties::copySelectedItemText () slot
Definition at line 561 of file AlgorithmHistoryWindow.cpp.
References m_selectedItemText.
Referenced by AlgHistoryProperties().
displayAlgHistoryProperties()
void AlgHistoryProperties::displayAlgHistoryProperties ()
Populates the Algorithm History display with property names, values, directions and whether their values were the defaults.
If a value was unset and its default value is EMPTY_INT, EMPTY_DBL or EMPTY_LONG, display an empty space to the user rather than the internal numeric representation of an empty value.
Definition at line 577 of file AlgorithmHistoryWindow.cpp.
References m_Histprop, and m_histpropTree.
Referenced by AlgorithmHistoryWindow::createAlgHistoryPropWindow(), and AlgorithmHistoryWindow::updateAlgHistoryProperties().
getAlgProperties()
const PropertyHistories & AlgHistoryProperties::getAlgProperties ()
Definition at line 550 of file AlgorithmHistoryWindow.cpp.
References m_Histprop.
popupMenu
void AlgHistoryProperties::popupMenu (const QPoint & pos) slot
Definition at line 552 of file AlgorithmHistoryWindow.cpp.
References m_contextMenu, m_histpropTree, and m_selectedItemText.
Referenced by AlgHistoryProperties().
setAlgProperties()
void AlgHistoryProperties::setAlgProperties (const std::vector< Mantid::Kernel::PropertyHistory_sptr > & histProp)
Definition at line 546 of file AlgorithmHistoryWindow.cpp.
References m_Histprop.
Referenced by AlgorithmHistoryWindow::updateAlgHistoryProperties().
Member Data Documentation
m_contextMenu
QMenu* AlgHistoryProperties::m_contextMenu private
Definition at line 202 of file AlgorithmHistoryWindow.h.
Referenced by AlgHistoryProperties(), and popupMenu().
m_copyAction
QAction* AlgHistoryProperties::m_copyAction private
Definition at line 201 of file AlgorithmHistoryWindow.h.
Referenced by AlgHistoryProperties().
m_Histprop
std::vector<Mantid::Kernel::PropertyHistory_sptr> AlgHistoryProperties::m_Histprop private
Definition at line 205 of file AlgorithmHistoryWindow.h.
Referenced by displayAlgHistoryProperties(), getAlgProperties(), and setAlgProperties().
m_histpropTree
QTreeWidget* AlgHistoryProperties::m_histpropTree
Definition at line 198 of file AlgorithmHistoryWindow.h.
Referenced by AlgHistoryProperties(), AlgorithmHistoryWindow::AlgorithmHistoryWindow(), clearData(), displayAlgHistoryProperties(), and popupMenu().
m_selectedItemText
QString AlgHistoryProperties::m_selectedItemText private
Definition at line 203 of file AlgorithmHistoryWindow.h.
Referenced by copySelectedItemText(), and popupMenu().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmHistoryWindow.h
qt/widgets/common/src/AlgorithmHistoryWindow.cpp