Mantid: Mantid::Geometry::BaseVisit Class Reference
Mantid::Geometry::BaseVisit Class Reference abstract
Adds the main.
#include <BaseVisit.h>
Public Member Functions
virtual void Accept (const Cone &)=0
Accept a cone.
virtual void Accept (const Cylinder &)=0
Accept a cylinder.
virtual void Accept (const General &)=0
Accept a general surface.
virtual void Accept (const Plane &)=0
Accept a plane.
virtual void Accept (const Sphere &)=0
Accept a sphere.
virtual void Accept (const Surface &)=0
Accept a surface.
virtual ~BaseVisit ()=default
Destructor.
Detailed Description
Adds the main.
Version
1.0
Author
S. Ansell
Definition at line 31 of file BaseVisit.h.
Constructor & Destructor Documentation
~BaseVisit()
virtual Mantid::Geometry::BaseVisit::~BaseVisit () virtual default
Destructor.
Member Function Documentation
Accept() [1/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const Cone &) pure virtual
Accept a cone.
Implemented in Mantid::Geometry::LineIntersectVisit.
Accept() [2/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const Cylinder &) pure virtual
Accept a cylinder.
Implemented in Mantid::Geometry::LineIntersectVisit.
Accept() [3/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const General &) pure virtual
Accept a general surface.
Implemented in Mantid::Geometry::LineIntersectVisit.
Accept() [4/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const Plane &) pure virtual
Accept a plane.
Implemented in Mantid::Geometry::LineIntersectVisit.
Accept() [5/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const Sphere &) pure virtual
Accept a sphere.
Implemented in Mantid::Geometry::LineIntersectVisit.
Accept() [6/6]
virtual void Mantid::Geometry::BaseVisit::Accept (const Surface &) pure virtual
Accept a surface.
Implemented in Mantid::Geometry::LineIntersectVisit.
Referenced by Mantid::Geometry::Surface::acceptVisitor(), Mantid::Geometry::Cone::acceptVisitor(), Mantid::Geometry::Cylinder::acceptVisitor(), Mantid::Geometry::Plane::acceptVisitor(), Mantid::Geometry::Quadratic::acceptVisitor(), Mantid::Geometry::Sphere::acceptVisitor(), and Mantid::Geometry::Torus::acceptVisitor().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Surfaces/BaseVisit.h