Mantid: Mantid::Geometry::IDetector Class Reference
Mantid::Geometry::IDetector Class Reference abstract
Interface class for detector objects.
#include <IDetector.h>
Public Member Functions
virtual IDetector * cloneParameterized (const ParameterMap *map) const =0
Create a cloned instance with a parameter map applied.
double getDistance (const IComponent &comp) const override=0
Get the distance of this detector object from another Component.
virtual detid_t getID () const =0
Get the detector ID.
virtual double getPhi () const =0
Gives the phi of this detector object in radians.
virtual double getPhiOffset (const double &offset) const =0
Gives the phi of this detector offset from y=0 by offset.
virtual double getSignedTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis, const Kernel::V3D &instrumentUp) const =0
Gives the signed angle of this detector object with respect to an axis.
virtual det_topology getTopology (Kernel::V3D &center) const =0
returns the geometry of detectors, meaningful for groups, rectangular for single; returns the centre of a detector
virtual double getTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis) const =0
Gives the angle of this detector object with respect to an axis.
IDetector ()
(Empty) Constructor.
virtual size_t index () const =0
Helper for legacy access mode. Returns the index of the detector.
virtual std::size_t nDets () const =0
Get the number of physical detectors this object represents.
virtual const ParameterMap & parameterMap () const =0
Helper for legacy access mode. Returns a reference to the ParameterMap.
Public Member Functions inherited from Mantid::Geometry::IObjComponent
IComponent * clone () const override=0
Virtual Copy Constructor.
virtual void draw () const =0
Draws the objcomponent.
virtual void drawObject () const =0
Draws the Object.
virtual int getPointInObject (Kernel::V3D &point) const =0
Try to find a point that lies within (or on) the object.
GeometryHandler * Handle () const
Gets the GeometryHandler.
virtual void initDraw () const =0
Initializes the ObjComponent for rendering, this function should be called before rendering.
virtual int interceptSurface (Track &track) const =0
Checks whether the track given will pass through this Component.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
virtual bool isOnSide (const Kernel::V3D &point) const =0
Does the point given lie on the surface of this object component?
virtual bool isValid (const Kernel::V3D &point) const =0
Does the point given lie within this object component?
virtual const Kernel::Material material () const =0
Returns the material of the Object.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
virtual const std::shared_ptr< const IObject > shape () const =0
Returns the shape of the Object.
virtual double solidAngle (const Geometry::SolidAngleParams &params) const =0
Finds the approximate solid angle covered by the component when viewed from the point given.
std::string type () const override
type string
~IObjComponent () override
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual std::vector< std::shared_ptr< const IComponent > > getAncestors () const =0
Return an array of all ancestors, the nearest first.
virtual const IComponent * getBareParent () const =0
Returns the bare pointer to the IComponent parent.
virtual IComponent const * getBaseComponent () const =0
Returns const pointer to base component if this component is parametrized.
virtual void getBoundingBox (BoundingBox &boundingBox) const =0
Get the bounding box for this component and store it in the given argument.
virtual ComponentID getComponentID () const =0
Returns the ComponentID - a unique identifier of the component.
virtual std::string getFullName () const =0
Get the IComponent full path name.
virtual std::string getName () const =0
Get the IComponent name.
virtual std::shared_ptr< const IComponent > getParent () const =0
Return a pointer to the current parent.
virtual Kernel::V3D getPos () const =0
Get the position of the IComponent. Tree structure is traverse through the.
virtual Kernel::V3D getRelativePos () const =0
Get the position relative to the parent IComponent (absolute if no parent)
virtual Kernel::Quat getRelativeRot () const =0
Get the relative Orientation.
virtual Kernel::Quat getRotation () const =0
Get the absolute orientation of the IComponent.
virtual Kernel::V3D getScaleFactor () const
Gets the scaling factor of the object for the Object Component.
virtual std::optional< Kernel::V2D > getSideBySideViewPos () const =0
Get the position of the IComponent for display on the side by side instrument view.
virtual void rotate (const Kernel::Quat &)=0
Rotate the IComponent. This is relative to parent.
virtual void rotate (double, const Kernel::V3D &)=0
Rotate the IComponent by an angle in degrees with respect to an axis.
virtual void setName (const std::string &)=0
Set the IComponent name.
virtual void setParent (IComponent *)=0
Assign a parent IComponent. Previous parent link is lost.
virtual void setPos (const Kernel::V3D &)=0
Set the position of the component The position is with respect to the parent component.
virtual void setPos (double, double, double)=0
Set the IComponent position, x, y, z respective to parent (if present)
virtual void setRot (const Kernel::Quat &)=0
Set the orientation Kernel::Quaternion relative to parent (if present)
virtual void setSideBySideViewPos (const Kernel::V2D &)=0
virtual void translate (const Kernel::V3D &)=0
Copy the Rotation from another IComponent.
virtual void translate (double, double, double)=0
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual ~IComponent ()=default
Destructor.
virtual std::set< std::string > getParameterNames (bool recursive=true) const =0
Return the names of the parameters for this component.
virtual std::map< std::string, ComponentID > getParameterNamesByComponent () const =0
return the parameter names and the component they are from
virtual bool hasParameter (const std::string &name, bool recursive=true) const =0
Returns a boolean indicating if the component has the named parameter.
virtual std::string getParameterType (const std::string &pname, bool recursive=true) const =0
virtual std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a double.
virtual std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a Kernel::V3D.
virtual std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a Kernel::Quaternion.
virtual std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a string.
virtual std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as an integer.
virtual std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const =0
Get a parameter defined as a boolean.
virtual std::string getParameterAsString (const std::string &pname, bool recursive=true) const =0
get a string representation of a parameter
virtual bool getParameterVisible (const std::string &pname, bool recursive=true) const =0
get visibility attribute of a parameter
virtual void printSelf (std::ostream &) const =0
Prints a text representation of itself.
virtual bool isParametrized () const =0
Returns true if the Component is parametrized (has a parameter map)
virtual size_t registerContents (class ComponentVisitor &component) const =0
Additional Inherited Members
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Detailed Description
Interface class for detector objects.
Author
Russell Taylor, Tessella Support Services plc
Date
08/04/2008
Definition at line 43 of file IDetector.h.
Constructor & Destructor Documentation
IDetector()
Mantid::Geometry::IDetector::IDetector () inline
(Empty) Constructor.
prevent Warning C4436 and many failing unit tests on MSVC 2015.
Definition at line 96 of file IDetector.h.
Member Function Documentation
cloneParameterized()
virtual IDetector * Mantid::Geometry::IDetector::cloneParameterized (const ParameterMap * map) const pure virtual
Create a cloned instance with a parameter map applied.
Implemented in Mantid::Geometry::DetectorGroup, Mantid::Geometry::Detector, and Mantid::Geometry::GridDetectorPixel.
Referenced by Mantid::Geometry::ParComponentFactory::createDetector().
getDistance()
double Mantid::Geometry::IDetector::getDistance (const IComponent & comp) const override pure virtual
Get the distance of this detector object from another Component.
Parameters
comp :: The component to give the distance to
Returns
The distance
Implements Mantid::Geometry::IComponent.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector().
getID()
virtual detid_t Mantid::Geometry::IDetector::getID () const pure virtual
Get the detector ID.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::Geometry::ParameterMap::asString(), Mantid::DataHandling::FindDetectorsPar::calcDetPar(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::createCollimatorHexahedronShape(), Mantid::Geometry::DetectorInfo::detid(), Mantid::DataHandling::SaveParameterFile::exec(), export_IDetector(), Mantid::Algorithms::He3TubeEfficiency::getDetectorGeometry(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::API::TimeAtSampleStrategyIndirect::getEfixed(), Mantid::API::WorkspaceNearestNeighbourInfo::getNeighbours(), Mantid::Geometry::Instrument::markAsDetector(), Mantid::Geometry::Instrument::markAsDetectorIncomplete(), Mantid::Geometry::Instrument::markAsMonitor(), Mantid::Geometry::InstrumentVisitor::registerDetector(), Mantid::Geometry::Instrument::removeDetector(), and Mantid::Crystal::FindSXPeaksHelper::SXPeak::SXPeak().
getPhi()
virtual double Mantid::Geometry::IDetector::getPhi () const pure virtual
Gives the phi of this detector object in radians.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Crystal::FindSXPeaksHelper::PeakFindingStrategy::calculatePhi(), Mantid::Algorithms::AddPeak::exec(), and export_IDetector().
getPhiOffset()
virtual double Mantid::Geometry::IDetector::getPhiOffset (const double & offset) const pure virtual
Gives the phi of this detector offset from y=0 by offset.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
getSignedTwoTheta()
virtual double Mantid::Geometry::IDetector::getSignedTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis, const Kernel::V3D & instrumentUp) const pure virtual
Gives the signed angle of this detector object with respect to an axis.
Parameters
observer :: The point to calculate the angle relative to (typically the sample position)
axis :: The axis to which the required angle is relative
instrumentUp :: Direction corresponding to the instrument up direction. Used to determine signs.
Returns
The angle in radians
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::API::MatrixWorkspace::detectorSignedTwoTheta().
getTopology()
virtual det_topology Mantid::Geometry::IDetector::getTopology (Kernel::V3D & center) const pure virtual
returns the geometry of detectors, meaningful for groups, rectangular for single; returns the centre of a detector
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
getTwoTheta()
virtual double Mantid::Geometry::IDetector::getTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis) const pure virtual
Gives the angle of this detector object with respect to an axis.
Parameters
observer :: The point to calculate the angle relative to (typically the sample position)
axis :: The axis to which the required angle is relative
Returns
The angle in radians
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::calculateE1(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::calculateE1(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::calculateE1(), Mantid::MDAlgorithms::IntegratePeaksMD2::calculateE1(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), Mantid::API::MatrixWorkspace::detectorTwoTheta(), and export_IDetector().
index()
virtual size_t Mantid::Geometry::IDetector::index () const pure virtual
Helper for legacy access mode. Returns the index of the detector.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
nDets()
virtual std::size_t Mantid::Geometry::IDetector::nDets () const pure virtual
Get the number of physical detectors this object represents.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
Referenced by Mantid::DataHandling::FindDetectorsPar::calcDetPar(), Mantid::Algorithms::AbsorptionCorrection::calculateDistances(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::calculateDistances(), Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds(), and Mantid::Algorithms::MultipleScatteringCorrection::calculateL2Ds().
parameterMap()
virtual const ParameterMap & Mantid::Geometry::IDetector::parameterMap () const pure virtual
Helper for legacy access mode. Returns a reference to the ParameterMap.
Implemented in Mantid::Geometry::Detector, and Mantid::Geometry::DetectorGroup.
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/IDetector.h