Mantid: Framework/PythonInterface/mantid/kernel/src/Exports/UsageService.cpp File Reference
UsageService.cpp File Reference
#include "MantidKernel/UsageService.h"
#include "MantidPythonInterface/core/Converters/PySequenceToVector.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/reference_existing_object.hpp>
#include <mutex>
Typedefs
using ExtractStdString = boost::python::extract< std::string >
Functions
void export_UsageService ()
Typedef Documentation
ExtractStdString
using ExtractStdString = boost::python::extract<std::string>
Definition at line 19 of file UsageService.cpp.
Function Documentation
export_UsageService()
void export_UsageService ()
Definition at line 58 of file UsageService.cpp.
References Mantid::Kernel::Algorithm, Mantid::Kernel::Feature, Mantid::Kernel::UsageServiceImpl::flush(), Mantid::Kernel::UsageServiceImpl::getApplicationName(), Mantid::Kernel::UsageServiceImpl::getStartTime(), Mantid::Kernel::UsageServiceImpl::getUpTime(), Mantid::Kernel::Interface, Mantid::Kernel::UsageServiceImpl::isEnabled(), Mantid::Kernel::UsageServiceImpl::registerStartup(), Mantid::Kernel::UsageServiceImpl::setApplicationName(), Mantid::Kernel::UsageServiceImpl::setEnabled(), and Mantid::Kernel::UsageServiceImpl::shutdown().