Mantid: ICat4::ns1__searchTextResponse Class Reference
ICat4::ns1__searchTextResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__searchTextResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< xsd__anyType * > return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1227 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__searchTextResponse()
ICat4::ns1__searchTextResponse::ns1__searchTextResponse () inline
Definition at line 1243 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__searchTextResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7130 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerToxsd__anyType().
Referenced by ICat4::ICATPortBindingProxy::searchText(), ICat4::soap_in_ns1__searchTextResponse(), ICat4::soap_new_req_ns1__searchTextResponse(), and ICat4::soap_new_set_ns1__searchTextResponse().
soap_get()
void * ICat4::ns1__searchTextResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7222 of file ICat4C.cpp.
References ICat4::soap_get_ns1__searchTextResponse().
Referenced by ICat4::ICATPortBindingProxy::searchText().
soap_in()
void * ICat4::ns1__searchTextResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7160 of file ICat4C.cpp.
References ICat4::soap_in_ns1__searchTextResponse().
Referenced by ICat4::soap_in_ns1__searchTextResponse().
soap_out()
int ICat4::ns1__searchTextResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7144 of file ICat4C.cpp.
References ICat4::soap_out_ns1__searchTextResponse().
soap_put()
int ICat4::ns1__searchTextResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7215 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__searchTextResponse.
soap_serialize()
void ICat4::ns1__searchTextResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7136 of file ICat4C.cpp.
References ICat4::soap_serialize_std__vectorTemplateOfPointerToxsd__anyType().
soap_type()
int ICat4::ns1__searchTextResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1236 of file ICat4Stub.h.
Member Data Documentation
return_
std::vector<xsd__anyType *> ICat4::ns1__searchTextResponse::return_
Definition at line 1229 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp