Mantid: ICat4::ns1__investigation Class Reference
ICat4::ns1__investigation Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__investigation ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< ns1__dataset * > datasets
std::string * doi
time_t * endDate
ns1__facility * facility
std::vector< class ns1__investigationInstrument * > investigationInstruments
std::vector< ns1__investigationUser * > investigationUsers
std::vector< ns1__keyword * > keywords
std::string * name
std::vector< class ns1__investigationParameter * > parameters
std::vector< ns1__publication * > publications
time_t * releaseDate
std::vector< ns1__sample * > samples
std::vector< ns1__shift * > shifts
time_t * startDate
std::vector< ns1__studyInvestigation * > studyInvestigations
std::string * summary
std::string * title
ns1__investigationType * type
std::string * visitId
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1570 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__investigation()
ICat4::ns1__investigation::ns1__investigation () inline
Definition at line 1600 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__investigation::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16223 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataset(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationInstrument(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationParameter(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__investigationUser(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__keyword(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__publication(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__sample(), ICat4::soap_default_std__vectorTemplateOfPointerTons1__shift(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__studyInvestigation().
Referenced by ICat4::soap_in_ns1__investigation(), ICat4::soap_new_req_ns1__investigation(), and ICat4::soap_new_set_ns1__investigation().
soap_get()
void * ICat4::ns1__investigation::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16531 of file ICat4C.cpp.
References ICat4::soap_get_ns1__investigation().
soap_in()
void * ICat4::ns1__investigation::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16347 of file ICat4C.cpp.
References ICat4::soap_in_ns1__investigation().
Referenced by ICat4::soap_in_ns1__investigation().
soap_out()
int ICat4::ns1__investigation::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16281 of file ICat4C.cpp.
References ICat4::soap_out_ns1__investigation().
soap_put()
int ICat4::ns1__investigation::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16524 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__investigation.
soap_serialize()
void ICat4::ns1__investigation::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 16251 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTons1__investigationType(), ICat4::soap_serialize_PointerTostd__string(), ICat4::soap_serialize_PointerTotime(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataset(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationInstrument(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationParameter(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__investigationUser(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__keyword(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__publication(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__sample(), ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__shift(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__studyInvestigation().
soap_type()
int ICat4::ns1__investigation::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 1593 of file ICat4Stub.h.
Member Data Documentation
datasets
std::vector<ns1__dataset *> ICat4::ns1__investigation::datasets
Definition at line 1572 of file ICat4Stub.h.
doi
std::string* ICat4::ns1__investigation::doi
Definition at line 1573 of file ICat4Stub.h.
endDate
time_t* ICat4::ns1__investigation::endDate
Definition at line 1574 of file ICat4Stub.h.
facility
ns1__facility* ICat4::ns1__investigation::facility
Definition at line 1575 of file ICat4Stub.h.
investigationInstruments
std::vector<class ns1__investigationInstrument *> ICat4::ns1__investigation::investigationInstruments
Definition at line 1576 of file ICat4Stub.h.
investigationUsers
std::vector<ns1__investigationUser *> ICat4::ns1__investigation::investigationUsers
Definition at line 1578 of file ICat4Stub.h.
keywords
std::vector<ns1__keyword *> ICat4::ns1__investigation::keywords
Definition at line 1579 of file ICat4Stub.h.
name
std::string* ICat4::ns1__investigation::name
Definition at line 1580 of file ICat4Stub.h.
parameters
std::vector<class ns1__investigationParameter *> ICat4::ns1__investigation::parameters
Definition at line 1581 of file ICat4Stub.h.
publications
std::vector<ns1__publication *> ICat4::ns1__investigation::publications
Definition at line 1582 of file ICat4Stub.h.
releaseDate
time_t* ICat4::ns1__investigation::releaseDate
Definition at line 1583 of file ICat4Stub.h.
samples
std::vector<ns1__sample *> ICat4::ns1__investigation::samples
Definition at line 1584 of file ICat4Stub.h.
shifts
std::vector<ns1__shift *> ICat4::ns1__investigation::shifts
Definition at line 1585 of file ICat4Stub.h.
startDate
time_t* ICat4::ns1__investigation::startDate
Definition at line 1586 of file ICat4Stub.h.
studyInvestigations
std::vector<ns1__studyInvestigation *> ICat4::ns1__investigation::studyInvestigations
Definition at line 1587 of file ICat4Stub.h.
summary
std::string* ICat4::ns1__investigation::summary
Definition at line 1588 of file ICat4Stub.h.
title
std::string* ICat4::ns1__investigation::title
Definition at line 1589 of file ICat4Stub.h.
type
ns1__investigationType* ICat4::ns1__investigation::type
Definition at line 1590 of file ICat4Stub.h.
visitId
std::string* ICat4::ns1__investigation::visitId
Definition at line 1591 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp