Mantid: Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask Class Reference
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask Class Reference
#include <ProcessBankSplitTask.h>
Public Member Functions
void operator() (const tbb::blocked_range< size_t > &range) const
ProcessBankSplitTask (std::vector< std::string > &bankEntryNames, H5::H5File &h5file, std::shared_ptr< NexusLoader > loader, std::vector< int > &workspaceIndices, std::vector< API::MatrixWorkspace_sptr > &wksps, const BankCalibrationFactory &calibFactory, const size_t events_per_chunk, const size_t grainsize_event, std::shared_ptr< API::Progress > &progress)
Public Member Functions inherited from Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase
const std::string & bankName (const size_t wksp_index) const
BankCalibration getCalibration (const std::string &tof_unit, const size_t wksp_index) const
std::stack< EventROI > getEventIndexRanges (H5::Group &event_group, const uint64_t number_events, std::unique_ptr< std::vector< uint64_t > > *event_index=nullptr) const
std::stack< std::pair< int, EventROI > > getEventIndexSplitRanges (H5::Group &event_group, const uint64_t number_events) const
void loadEvents (H5::DataSet &detID_SDS, H5::DataSet &tof_SDS, const std::vector< size_t > &offsets, const std::vector< size_t > &slabsizes, std::unique_ptr< std::vector< uint32_t > > &detId_vec, std::unique_ptr< std::vector< float > > &tof_vec) const
Load detid and tof at the same time.
ProcessBankTaskBase (std::vector< std::string > &bankEntryNames, std::shared_ptr< NexusLoader > loader, const BankCalibrationFactory &calibFactory)
Private Attributes
const size_t m_events_per_chunk
number of events to read from disk at one time
const size_t m_grainsize_event
number of events to histogram in a single thread
H5::H5File m_h5file
std::shared_ptr< API::Progress > m_progress
std::vector< API::MatrixWorkspace_sptr > m_wksps
std::vector< int > m_workspaceIndices
Detailed Description
Definition at line 24 of file ProcessBankSplitTask.h.
Constructor & Destructor Documentation
ProcessBankSplitTask()
Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::ProcessBankSplitTask (std::vector< std::string > & bankEntryNames, H5::H5File & h5file, std::shared_ptr< NexusLoader > loader, std::vector< int > & workspaceIndices, std::vector< API::MatrixWorkspace_sptr > & wksps, const BankCalibrationFactory & calibFactory, const size_t events_per_chunk, const size_t grainsize_event, std::shared_ptr< API::Progress > & progress)
Definition at line 27 of file ProcessBankSplitTask.cpp.
Member Function Documentation
operator()()
void Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator() (const tbb::blocked_range< size_t > & range) const
Definition at line 35 of file ProcessBankSplitTask.cpp.
References Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::bankName(), Mantid::Kernel::Logger::debug(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::DETID(), Mantid::API::g_log, Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getCalibration(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::getEventIndexSplitRanges(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTaskBase::loadEvents(), m_events_per_chunk, m_h5file, m_progress, m_wksps, m_workspaceIndices, Mantid::Nexus::H5Util::readStringAttribute(), Mantid::DataHandling::AlignAndFocusPowderSlim::NxsFieldNames::TIME_OF_FLIGHT(), and Mantid::DataHandling::AlignAndFocusPowderSlim::toLogString().
Member Data Documentation
m_events_per_chunk
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_events_per_chunk private
number of events to read from disk at one time
Definition at line 39 of file ProcessBankSplitTask.h.
Referenced by operator()().
m_grainsize_event
const size_t Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_grainsize_event private
number of events to histogram in a single thread
Definition at line 41 of file ProcessBankSplitTask.h.
m_h5file
H5::H5File Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_h5file private
Definition at line 35 of file ProcessBankSplitTask.h.
Referenced by operator()().
m_progress
std::shared_ptr<API::Progress> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_progress private
Definition at line 42 of file ProcessBankSplitTask.h.
Referenced by operator()().
m_wksps
std::vector<API::MatrixWorkspace_sptr> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_wksps private
Definition at line 37 of file ProcessBankSplitTask.h.
Referenced by operator()().
m_workspaceIndices
std::vector<int> Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::m_workspaceIndices private
Definition at line 36 of file ProcessBankSplitTask.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim/ProcessBankSplitTask.h
Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankSplitTask.cpp