Mantid: Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks Class Reference
Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks Class Reference final
FitPowderDiffPeaks : Fit peaks in powder diffraction pattern.
#include <FitPowderDiffPeaks.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification overriding a virtual method.
FitPowderDiffPeaks ()
Constructor.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Types
enum { ROBUSTFIT , TRUSTINPUTFIT }
Fit mode.
enum { HKLCALCULATION , FROMBRAGGTABLE }
Choice to generate peak profile paramter starting value.
Private Member Functions
DataObjects::Workspace2D_sptr buildPartialWorkspace (const API::MatrixWorkspace_sptr &sourcews, size_t workspaceindex, double leftbound, double rightbound)
Build partial workspace for fitting.
void calculate1PeakGroup (std::vector< size_t > peakindexes, Functions::BackgroundFunction_sptr background)
Calcualte the value of a single peak in a given range.
double calculatePeakCentreTOF (int h, int k, int l)
Calculate a Bragg peak's centre in TOF from its Miller indices.
void calculatePeakFitBoundary (size_t ileftpeak, size_t irightpeak, double &peakleftboundary, double &peakrightboundary)
Calculate the range to fit peak/peaks group.
void cropWorkspace (double tofmin, double tofmax)
Crop data workspace.
bool doFit1PeakBackground (const DataObjects::Workspace2D_sptr &dataws, size_t wsindex, const Functions::BackToBackExponential_sptr &peak, const Functions::BackgroundFunction_sptr &backgroundfunction, double &chi2)
Fit 1 peak and background.
bool doFit1PeakSequential (const DataObjects::Workspace2D_sptr &dataws, size_t workspaceindex, const Functions::BackToBackExponential_sptr &peakfunction, std::vector< std::string > minimzernames, std::vector< size_t > maxiterations, const std::vector< double > &dampfactors, double &chi2)
Fit 1 peak by using a sequential of minimizer.
bool doFit1PeakSimple (const DataObjects::Workspace2D_sptr &dataws, size_t workspaceindex, const Functions::BackToBackExponential_sptr &peakfunction, const std::string &minimzername, size_t maxiteration, double &chi2)
Fit 1 peak by 1 minimizer of 1 call of minimzer (simple version)
bool doFitBackground (DataObjects::Workspace2D_sptr dataws, Functions::BackgroundFunction_sptr background, double leftpeakbound, double rightpeakbound)
Fit background function by removing the peak properly.
bool doFitGaussianPeak (const DataObjects::Workspace2D_sptr &dataws, size_t workspaceindex, double in_center, double leftfwhm, double rightfwhm, double &center, double &sigma, double &height)
Fit background-removed peak by Gaussian.
bool doFitMultiplePeaks (const DataObjects::Workspace2D_sptr &dataws, size_t wsindex, const API::CompositeFunction_sptr &peaksfunc, std::vector< Functions::BackToBackExponential_sptr > peakfuncs, std::vector< bool > &vecfitgood, std::vector< double > &vecchi2s)
Fit multiple (overlapped) peaks.
bool doFitNPeaksSimple (const DataObjects::Workspace2D_sptr &dataws, size_t wsindex, const API::CompositeFunction_sptr &peaksfunc, const std::vector< Functions::BackToBackExponential_sptr > &peakfuncs, const std::string &minimizername, size_t maxiteration, double &chi2)
Fit N overlapped peaks in a simple manner.
std::pair< bool, double > doFitPeak (const DataObjects::Workspace2D_sptr &dataws, const Functions::BackToBackExponential_sptr &peakfunction, double guessedfwhm)
Fit peak with flexiblity in multiple steps Prerequisit:
std::pair< bool, double > doFitPeak_Old (DataObjects::Workspace2D_sptr dataws, Functions::BackToBackExponential_sptr peak, double guessedfwhm, bool calchi2)
Fit single peak without background.
bool estimateFWHM (DataObjects::Workspace2D_sptr dataws, size_t wsindex, double tof_h, double &leftfwhm, double &rightfwhm)
Estimate FWHM for the peak observed.
void estimatePeakHeightsLeBail (const DataObjects::Workspace2D_sptr &dataws, size_t wsindex, std::vector< Functions::BackToBackExponential_sptr > peaks)
Use Le Bail method to estimate and set the peak heights.
bool estimateSinglePeakRange (Functions::BackToBackExponential_sptr peak, Functions::BackgroundFunction_sptr background, Functions::BackToBackExponential_sptr rightpeak, double fwhm, bool ismostright, size_t m_wsIndex, double &chi2)
Build a partial workspace from source.
void exec () override
Implement abstract Algorithm methods.
bool findMaxHeight (API::MatrixWorkspace_sptr dataws, size_t wsindex, double xmin, double xmax, double &center, double &centerleftbound, double &centerrightbound, int &errordirection)
Find max height (peak center)
bool fitOverlappedPeaks (std::vector< Functions::BackToBackExponential_sptr > peaks, const Functions::BackgroundFunction_sptr &backgroundfunction, double gfwhm)
Fit peaks with confidence in fwhm and etc.
bool fitPeak (Functions::BackToBackExponential_sptr peak, Functions::BackgroundFunction_sptr background, double leftdev, double rightdev, size_t m_wsIndex, double &chi2)
Fit a single peak.
void fitPeaksGroup (std::vector< size_t > peakindexes)
Fit peaks in the same group (i.e., single peak or overlapped peaks)
void fitPeaksRobust ()
Fit peaks in robust algorithm.
void fitPeaksWithGoodStartingValues ()
Fit peaks.
bool fitSinglePeakConfident (const Functions::BackToBackExponential_sptr &peak, const Functions::BackgroundFunction_sptr &backgroundfunction, double leftbound, double rightbound, double &chi2, bool &annhilatedpeak)
Fit peak with trustful peak parameters.
bool fitSinglePeakConfidentX (Functions::BackToBackExponential_sptr peak)
Fit peak with confidence of the centre.
bool fitSinglePeakConfidentY (DataObjects::Workspace2D_sptr dataws, Functions::BackToBackExponential_sptr peak, double dampingfactor)
Fit peak with confident parameters.
bool fitSinglePeakRobust (const Functions::BackToBackExponential_sptr &peak, const Functions::BackgroundFunction_sptr &backgroundfunction, double peakleftbound, double peakrightbound, const std::map< std::string, double > &rightpeakparammap, double &finalchi2)
Fit single peak in robust mode (no hint)
bool fitSinglePeakSimulatedAnnealing (const Functions::BackToBackExponential_sptr &peak, const std::vector< std::string > &paramtodomc)
Fit signle peak by Monte Carlo/simulated annealing.
DataObjects::Workspace2D_sptr genOutputFittedPatternWorkspace (std::vector< double > pattern, int workspaceindex)
Create a Workspace2D for fitted peaks (pattern)
Functions::BackToBackExponential_sptr genPeak (std::map< std::string, int > hklmap, std::map< std::string, double > parammap, std::map< std::string, std::string > bk2bk2braggmap, bool &good, std::vector< int > &hkl, double &d_h)
Generate a peak.
DataObjects::Workspace2D_sptr genPeakParameterDataWorkspace ()
Create data workspace for X0, A, B and S of peak with good fit.
std::pair< DataObjects::TableWorkspace_sptr, DataObjects::TableWorkspace_sptr > genPeakParametersWorkspace ()
Generate output peak parameters workspace.
void genPeaksFromTable (const DataObjects::TableWorkspace_sptr &peakparamws)
Generate peaks from input table workspace.
bool getHKLFromMap (std::map< std::string, int > intmap, std::vector< int > &hkl)
Get (HKL) from a map; Return false if the information is incomplete.
double getParameter (const std::string &parname)
Get parameter value from m_instrumentParameters.
void importInstrumentParameterFromTable (const DataObjects::TableWorkspace_sptr &parameterWS)
Import instrument parameters from (input) table workspace.
void init () override
Implement abstract Algorithm methods.
void observePeakRange (const Functions::BackToBackExponential_sptr &thispeak, const Functions::BackToBackExponential_sptr &rightpeak, double refpeakshift, double &peakleftbound, double &peakrightbound)
Observe peak range with hint from right peak's properties.
void parseBraggPeakTable (const DataObjects::TableWorkspace_sptr &peakws, std::vector< std::map< std::string, double > > &parammaps, std::vector< std::map< std::string, int > > &hklmaps)
Import Bragg peak table workspace.
std::string parseFitParameterWorkspace (const API::ITableWorkspace_sptr &paramws)
Parse Fit() output parameter workspace.
std::string parseFitResult (const API::IAlgorithm_sptr &fitalg, double &chi2, bool &fitsuccess)
Parse the fitting result.
void plotFunction (const API::IFunction_sptr &peakfunction, const Functions::BackgroundFunction_sptr &background, const API::FunctionDomain1DVector &domain)
Plot a single peak to output vector.
void processInputProperties ()
Process input properties.
void restoreFunctionParameters (const API::IFunction_sptr &function, std::map< std::string, double > parammap)
Restore the function's parameter values from a map.
void setOverlappedPeaksConstraints (const std::vector< Functions::BackToBackExponential_sptr > &peaks)
Set constraints on a group of overlapped peaks for fitting.
void storeFunctionParameters (const API::IFunction_sptr &function, std::map< std::string, double > &parammaps)
Store the function's parameter values to a map.
void subtractBackground (DataObjects::Workspace2D_sptr dataws)
Estimate background.
Private Attributes
std::vector< double > m_chi2GoodFitPeaks
bool m_confidentInInstrumentParameters
Flag to show whether input instrument parameters is trustful.
API::MatrixWorkspace_sptr m_dataWS
Data.
enum Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks:: { ... } m_fitMode
Fit mode.
bool m_fitPeakBackgroundComposite
Fit peak + background as the last step.
enum Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks:: { ... } m_genPeakStartingValue
Choice to generate peak profile paramter starting value.
std::vector< bool > m_goodFit
Peak fitting status.
std::vector< size_t > m_indexGoodFitPeaks
std::map< std::string, double > m_instrumentParmaeters
Map for function (instrument parameter)
std::vector< int > m_minimumHKL
Minimum HKL.
double m_minPeakHeight
Minimum peak height for peak to be refined.
int m_numPeaksLowerToMin
Number of peaks to fit lower to minimum HKL.
std::vector< double > m_peakData
Data for each individual peaks. (HKL)^2, vector index, function values.
std::vector< double > m_peakFitChi2
Peak fitting information.
DataObjects::TableWorkspace_sptr m_peakParamTable
Bragg peak parameter.
DataObjects::TableWorkspace_sptr m_profileTable
Instrument profile parameter table workspace.
std::vector< int > m_rightmostPeakHKL
Right most peak HKL.
double m_rightmostPeakLeftBound
Right most peak's left boundary.
double m_rightmostPeakRightBound
Right most peak's right boundary.
double m_tofMax
double m_tofMin
TOF Min and TOF Max.
Geometry::UnitCell m_unitCell
Unit cell of powder crystal.
bool m_useGivenTOFh
Flag to use given Bragg peaks' centre in TOF.
std::vector< std::pair< double, std::pair< std::vector< int >, Functions::BackToBackExponential_sptr > > > m_vecPeakFunctions
Sorted vector for peaks. double = d_h, vector = (HKL), peak.
int m_wsIndex
TOF vector of data workspace to process with.
std::vector< std::string > mPeakParameterNames
Peak parmeter names.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
FitPowderDiffPeaks : Fit peaks in powder diffraction pattern.
Mode Confident: In this mode, the starting values of parameters except height will be given in input table workspace; Use case 1: user has some pre-knowledge of the peak shape parameters, i.e, the analytical function to describe all peaks. Use case 2: user has no pre-knowledge of the peak shape parameters, but have some single peaks fitted; The best starting value/estimation is from its right peak with proper fit Solution: Let them compete!
Its application is to serve as the first step for refining powder diffractomer instrument parameters. Its output will be used by RefinePowderInstrumentParameters().
Definition at line 45 of file FitPowderDiffPeaks.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Fit mode.
Enumerator
ROBUSTFIT
TRUSTINPUTFIT
Definition at line 322 of file FitPowderDiffPeaks.h.
anonymous enum
anonymous enum private
Choice to generate peak profile paramter starting value.
Enumerator
HKLCALCULATION
FROMBRAGGTABLE
Definition at line 325 of file FitPowderDiffPeaks.h.
Constructor & Destructor Documentation
FitPowderDiffPeaks()
Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::FitPowderDiffPeaks ()
Constructor.
Definition at line 70 of file FitPowderDiffPeaks.cpp.
Member Function Documentation
buildPartialWorkspace()
Workspace2D_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::buildPartialWorkspace (const API::MatrixWorkspace_sptr & sourcews, size_t workspaceindex, double leftbound, double rightbound) private
Build partial workspace for fitting.
Build a partial workspace from original data workspace.
Parameters
sourcews data workspace which the new workspace is built from
workspaceindex workspace index of the source spectrum in sourcews
leftbound lower boundary of the source data
rightbound upper boundary of the source data
Definition at line 2832 of file FitPowderDiffPeaks.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by fitOverlappedPeaks(), fitSinglePeakConfident(), and fitSinglePeakRobust().
calculate1PeakGroup()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::calculate1PeakGroup (std::vector< size_t > peakindexes, Functions::BackgroundFunction_sptr background) private
Calcualte the value of a single peak in a given range.
calculatePeakCentreTOF()
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::calculatePeakCentreTOF (int h, int k, int l) private
Calculate a Bragg peak's centre in TOF from its Miller indices.
calculatePeakFitBoundary()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::calculatePeakFitBoundary (size_t ileftpeak, size_t irightpeak, double & peakleftboundary, double & peakrightboundary) private
Calculate the range to fit peak/peaks group.
Calculate the range to fit peak/peaks group by avoiding including the tails of the neighboring peaks.
Assumption: all peaks' parameters on centre and FWHM are close to the true value
Parameters
ileftpeak :: index of the left most peak in the peak groups;
irightpeak :: index of the right most peak in the peak groups;
peakleftboundary :: left boundary of the peak for fitting (output)
peakrightboundary :: right boundary of the peak for fitting (output)
Definition at line 1359 of file FitPowderDiffPeaks.cpp.
References m_tofMin, m_vecPeakFunctions, PEAKBOUNDARYFACTOR, and PEAKFITRANGEFACTOR.
Referenced by fitPeaksWithGoodStartingValues().
category()
const std::string Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::category () const inline override virtual
Algorithm's category for identification overriding a virtual method.
Reimplemented from Mantid::API::Algorithm.
Definition at line 59 of file FitPowderDiffPeaks.h.
cropWorkspace()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::cropWorkspace (double tofmin, double tofmax) private
Crop data workspace.
Crop data workspace: the original workspace will not be affected.
Parameters
tofmin minimum value for cropping
tofmax maximum value for cropping
Definition at line 2776 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_dataWS, and m_wsIndex.
Referenced by exec().
doFit1PeakBackground()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakBackground (const DataObjects::Workspace2D_sptr & dataws, size_t wsindex, const Functions::BackToBackExponential_sptr & peak, const Functions::BackgroundFunction_sptr & backgroundfunction, double & chi2) private
Fit 1 peak and background.
Fit single peak with background to raw data Note 1: in a limited range (4*FWHM)
Fit single peak with background to raw data
Definition at line 759 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::CurveFitting::Algorithms::getFunctionInfo(), Mantid::Kernel::Logger::notice(), and parseFitResult().
Referenced by fitSinglePeakRobust().
doFit1PeakSequential()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSequential (const DataObjects::Workspace2D_sptr & dataws, size_t workspaceindex, const Functions::BackToBackExponential_sptr & peakfunction, std::vector< std::string > minimzernames, std::vector< size_t > maxiterations, const std::vector< double > & dampfactors, double & chi2) private
Fit 1 peak by using a sequential of minimizer.
Parameters
dataws :: A data aworkspace
workspaceindex :: A histogram index
peakfunction :: An instance of the BackToBackExponential function
minimzernames :: A vector of the minimizer names
maxiterations :: A vector if maximum numbers of iterations
dampfactors :: A vector of damping factors
chi2 :: The chi squared value (output)
Definition at line 1603 of file FitPowderDiffPeaks.cpp.
References doFit1PeakSimple(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::Logger::notice(), restoreFunctionParameters(), and storeFunctionParameters().
Referenced by doFitPeak(), and fitSinglePeakRobust().
doFit1PeakSimple()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple (const DataObjects::Workspace2D_sptr & dataws, size_t workspaceindex, const Functions::BackToBackExponential_sptr & peakfunction, const std::string & minimzername, size_t maxiteration, double & chi2) private
Fit 1 peak by 1 minimizer of 1 call of minimzer (simple version)
Parameters
dataws :: A data aworkspace
workspaceindex :: A histogram index
peakfunction :: An instance of the BackToBackExponential function
minimzername :: A name of the minimizer to use
maxiteration :: A maximum number of iterations
chi2 :: The chi squared value (output)
Return
fit success?
chi2
Definition at line 1539 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), name(), parseFitParameterWorkspace(), and parseFitResult().
Referenced by doFit1PeakSequential(), and fitSinglePeakConfident().
doFitBackground()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitBackground (DataObjects::Workspace2D_sptr dataws, Functions::BackgroundFunction_sptr background, double leftpeakbound, double rightpeakbound) private
Fit background function by removing the peak properly.
doFitGaussianPeak()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitGaussianPeak (const DataObjects::Workspace2D_sptr & dataws, size_t workspaceindex, double in_center, double leftfwhm, double rightfwhm, double & center, double & sigma, double & height) private
Fit background-removed peak by Gaussian.
Definition at line 1658 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, height, Mantid::Kernel::Logger::information(), Mantid::Kernel::SingletonHolder< T >::Instance(), parseFitParameterWorkspace(), parseFitResult(), sigma, Mantid::Kernel::Logger::warning(), Mantid::Geometry::X, and Mantid::Geometry::Y.
Referenced by fitSinglePeakRobust().
doFitMultiplePeaks()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitMultiplePeaks (const DataObjects::Workspace2D_sptr & dataws, size_t wsindex, const API::CompositeFunction_sptr & peaksfunc, std::vector< Functions::BackToBackExponential_sptr > peakfuncs, std::vector< bool > & vecfitgood, std::vector< double > & vecchi2s) private
Fit multiple (overlapped) peaks.
Definition at line 1807 of file FitPowderDiffPeaks.cpp.
References doFitNPeaksSimple(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::Logger::notice(), restoreFunctionParameters(), Mantid::API::FunctionDomain1D::size(), and storeFunctionParameters().
Referenced by fitOverlappedPeaks().
doFitNPeaksSimple()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitNPeaksSimple (const DataObjects::Workspace2D_sptr & dataws, size_t wsindex, const API::CompositeFunction_sptr & peaksfunc, const std::vector< Functions::BackToBackExponential_sptr > & peakfuncs, const std::string & minimizername, size_t maxiteration, double & chi2) private
Fit N overlapped peaks in a simple manner.
Definition at line 1977 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), name(), parseFitParameterWorkspace(), and parseFitResult().
Referenced by doFitMultiplePeaks().
doFitPeak()
std::pair< bool, double > Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitPeak (const DataObjects::Workspace2D_sptr & dataws, const Functions::BackToBackExponential_sptr & peakfunction, double guessedfwhm) private
Fit peak with flexiblity in multiple steps Prerequisit:
Peak parameters are set up to the peak function
Background is removed
Parameters
dataws :: The data workspace
peakfunction :: An instance of the BackToBackExponential peak function
guessedfwhm Guessed fwhm in order to constain the peak. If negative, then no constraint
Definition at line 1407 of file FitPowderDiffPeaks.cpp.
References Mantid::Kernel::Logger::debug(), doFit1PeakSequential(), Mantid::API::Algorithm::g_log, restoreFunctionParameters(), and storeFunctionParameters().
doFitPeak_Old()
std::pair< bool, double > Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitPeak_Old (DataObjects::Workspace2D_sptr dataws, Functions::BackToBackExponential_sptr peak, double guessedfwhm, bool calchi2) private
Fit single peak without background.
estimateFWHM()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::estimateFWHM (DataObjects::Workspace2D_sptr dataws, size_t wsindex, double tof_h, double & leftfwhm, double & rightfwhm) private
Estimate FWHM for the peak observed.
estimatePeakHeightsLeBail()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::estimatePeakHeightsLeBail (const DataObjects::Workspace2D_sptr & dataws, size_t wsindex, std::vector< Functions::BackToBackExponential_sptr > peaks) private
Use Le Bail method to estimate and set the peak heights.
Parameters
dataws workspace containing the background-removed data
wsindex workspace index of the data without background
peaks :: A vector of instances of BackToBackExponential function
Definition at line 1915 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::g_log, height, Mantid::Kernel::Logger::information(), and Mantid::API::FunctionDomain1D::size().
Referenced by fitOverlappedPeaks().
estimateSinglePeakRange()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::estimateSinglePeakRange (Functions::BackToBackExponential_sptr peak, Functions::BackgroundFunction_sptr background, Functions::BackToBackExponential_sptr rightpeak, double fwhm, bool ismostright, size_t m_wsIndex, double & chi2) private
Build a partial workspace from source.
Estimate the range of a single peak
exec()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec () override private virtual
Implement abstract Algorithm methods.
Main execution.
Implements Mantid::API::Algorithm.
Definition at line 190 of file FitPowderDiffPeaks.cpp.
References cropWorkspace(), Mantid::EMPTY_DBL(), Mantid::Kernel::Logger::error(), fitPeaksRobust(), fitPeaksWithGoodStartingValues(), Mantid::API::Algorithm::g_log, genOutputFittedPatternWorkspace(), genPeakParameterDataWorkspace(), genPeakParametersWorkspace(), genPeaksFromTable(), getParameter(), importInstrumentParameterFromTable(), Mantid::Kernel::Logger::information(), m_chi2GoodFitPeaks, m_dataWS, m_fitMode, m_goodFit, m_indexGoodFitPeaks, m_peakData, m_peakFitChi2, m_peakParamTable, m_profileTable, m_tofMax, m_tofMin, m_unitCell, m_vecPeakFunctions, m_wsIndex, processInputProperties(), ROBUSTFIT, Mantid::Geometry::UnitCell::set(), Mantid::Kernel::IPropertyManager::setProperty(), and TRUSTINPUTFIT.
findMaxHeight()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::findMaxHeight (API::MatrixWorkspace_sptr dataws, size_t wsindex, double xmin, double xmax, double & center, double & centerleftbound, double & centerrightbound, int & errordirection) private
Find max height (peak center)
fitOverlappedPeaks()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitOverlappedPeaks (std::vector< Functions::BackToBackExponential_sptr > peaks, const Functions::BackgroundFunction_sptr & backgroundfunction, double gfwhm) private
Fit peaks with confidence in fwhm and etc.
Parameters
peaks :: A vector of instances of BackToBackExponential
backgroundfunction :: An instance of BackgroundFunction
gfwhm : guessed fwhm. If negative, then use the input value
Definition at line 1733 of file FitPowderDiffPeaks.cpp.
References buildPartialWorkspace(), doFitMultiplePeaks(), Mantid::CurveFitting::Algorithms::estimateBackgroundCoarse(), estimatePeakHeightsLeBail(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_dataWS, m_wsIndex, plotFunction(), and setOverlappedPeaksConstraints().
Referenced by fitPeaksWithGoodStartingValues().
fitPeak()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeak (Functions::BackToBackExponential_sptr peak, Functions::BackgroundFunction_sptr background, double leftdev, double rightdev, size_t m_wsIndex, double & chi2) private
Fit a single peak.
fitPeaksGroup()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksGroup (std::vector< size_t > peakindexes) private
Fit peaks in the same group (i.e., single peak or overlapped peaks)
fitPeaksRobust()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksRobust () private
Fit peaks in robust algorithm.
Fit peaks in Robust mode.
Prerequisite:
There are not any peaks that overlap to others; Algorithm: All peaks are fit individually Challenge:
Starting geometry parameters can be off
Peak profile parameters cannot be trusted at all.
Definition at line 339 of file FitPowderDiffPeaks.cpp.
References fitSinglePeakRobust(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_minPeakHeight, m_peakFitChi2, m_rightmostPeakHKL, m_rightmostPeakLeftBound, m_rightmostPeakRightBound, m_vecPeakFunctions, Mantid::Kernel::Logger::notice(), observePeakRange(), storeFunctionParameters(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
fitPeaksWithGoodStartingValues()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksWithGoodStartingValues () private
Fit peaks.
Fit individual peak or group of overlapped peaks with good starting values.
Strategy:
From high d-spacing, search for peak or overlapped peaks
Output: (1) goodfitpeaks, (2) goodfitchi2
Definition at line 1027 of file FitPowderDiffPeaks.cpp.
References calculatePeakFitBoundary(), fitOverlappedPeaks(), fitSinglePeakConfident(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_chi2GoodFitPeaks, m_goodFit, m_indexGoodFitPeaks, m_peakFitChi2, and m_vecPeakFunctions.
Referenced by exec().
fitSinglePeakConfident()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident (const Functions::BackToBackExponential_sptr & peak, const Functions::BackgroundFunction_sptr & backgroundfunction, double leftbound, double rightbound, double & chi2, bool & annhilatedpeak) private
Fit peak with trustful peak parameters.
Parameters
peak :: A peak BackToBackExponential function
backgroundfunction :: A background function
leftbound :: left boundary of the peak for fitting
rightbound :: right boundary of the peak for fitting
chi2 :: The output chi squared
annhilatedpeak :: (output) annhilatedpeak
Definition at line 1129 of file FitPowderDiffPeaks.cpp.
References buildPartialWorkspace(), doFit1PeakSimple(), Mantid::Kernel::Logger::error(), Mantid::CurveFitting::Algorithms::estimateBackgroundCoarse(), Mantid::CurveFitting::Algorithms::findMaxValue(), Mantid::API::Algorithm::g_log, m_dataWS, m_minPeakHeight, m_wsIndex, Mantid::Kernel::Logger::notice(), plotFunction(), restoreFunctionParameters(), and storeFunctionParameters().
Referenced by fitPeaksWithGoodStartingValues().
fitSinglePeakConfidentX()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfidentX (Functions::BackToBackExponential_sptr peak) private
Fit peak with confidence of the centre.
fitSinglePeakConfidentY()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfidentY (DataObjects::Workspace2D_sptr dataws, Functions::BackToBackExponential_sptr peak, double dampingfactor) private
Fit peak with confident parameters.
fitSinglePeakRobust()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust (const Functions::BackToBackExponential_sptr & peak, const Functions::BackgroundFunction_sptr & backgroundfunction, double peakleftbound, double peakrightbound, const std::map< std::string, double > & rightpeakparammap, double & finalchi2) private
Fit single peak in robust mode (no hint)
Fit a single peak including its background by a robust algorithm Algorithm will.
Locate Maximum 2.
Assumption:
peak must be in the range of [input peak center - leftdev, + rightdev]
Prerequisites: -— NONE!
Algorithms:
Build partial workspace for peak
Estimate background
Estimate peak position and height (by observing)
Fit peak by Gaussian for more accurate peak position, height and sigma
Peak Fit Algorithms: 4 different approaches are used. 3 of them use normal minimzers such that
Use X0 and I calculated by Gaussian, then use A, B, S from input;
Use X0, I and S calculated by Gaussian, then use A and B from input;
Use X0, I and S calculated by Gaussian, then use A and B from right peak;
Use X0, I and S calculated by Gaussian, then use simulated annealing on A and B;
Arguments
Parameters
peak :: A peak function.
backgroundfunction :: A background function
peakleftbound :: peak left bound
peakrightbound :: peak right bound
rightpeakparammap :: peakrightbound
finalchi2 :: (output) chi square of the fit result
Arguments:
leftdev, rightdev: search range for the peak from the estimatio (theoretical) Return: chi2 ... all the other parameter should be just in peak
Definition at line 555 of file FitPowderDiffPeaks.cpp.
References buildPartialWorkspace(), Mantid::Kernel::Logger::debug(), doFit1PeakBackground(), doFit1PeakSequential(), doFitGaussianPeak(), Mantid::Kernel::Logger::error(), Mantid::CurveFitting::Algorithms::estimateBackgroundCoarse(), fitSinglePeakSimulatedAnnealing(), Mantid::API::Algorithm::g_log, Mantid::CurveFitting::Algorithms::getFunctionInfo(), height, Mantid::Kernel::Logger::information(), m_dataWS, m_fitPeakBackgroundComposite, m_minPeakHeight, m_wsIndex, Mantid::Kernel::Logger::notice(), Mantid::CurveFitting::Algorithms::observePeakParameters(), plotFunction(), restoreFunctionParameters(), sigma, storeFunctionParameters(), and Mantid::Kernel::Logger::warning().
Referenced by fitPeaksRobust().
fitSinglePeakSimulatedAnnealing()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakSimulatedAnnealing (const Functions::BackToBackExponential_sptr & peak, const std::vector< std::string > & paramtodomc) private
Fit signle peak by Monte Carlo/simulated annealing.
Definition at line 823 of file FitPowderDiffPeaks.cpp.
References UNUSED_ARG.
Referenced by fitSinglePeakRobust().
genOutputFittedPatternWorkspace()
Workspace2D_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genOutputFittedPatternWorkspace (std::vector< double > pattern, int workspaceindex) private
Create a Workspace2D for fitted peaks (pattern)
Create a Workspace2D for fitted peaks (pattern) and also the workspace for Zscores!
Definition at line 2174 of file FitPowderDiffPeaks.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::SingletonHolder< T >::Instance(), m_dataWS, and Mantid::Geometry::X.
Referenced by exec().
genPeak()
BackToBackExponential_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak (std::map< std::string, int > hklmap, std::map< std::string, double > parammap, std::map< std::string, std::string > bk2bk2braggmap, bool & good, std::vector< int > & hkl, double & d_h) private
Generate a peak.
Parameters
hklmap a map containing one (HKL) entry
parammap :: a map of parameters
bk2bk2braggmap :: bk2bk2braggmap
good :: (output) peak is valid
hkl : (output) (HKL) of the peak generated.
d_h :: (output) d_h
Returns
: BackToBackExponential peak
Definition at line 2539 of file FitPowderDiffPeaks.cpp.
References Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::calThermalNeutronTOF(), Mantid::API::IPowderDiffPeakFunction::centre(), Mantid::Geometry::UnitCell::d(), Mantid::EMPTY_DBL(), Mantid::Kernel::Logger::error(), FROMBRAGGTABLE, Mantid::API::Algorithm::g_log, Mantid::CurveFitting::Algorithms::getFunctionInfo(), getHKLFromMap(), getParameter(), Mantid::API::IFunction::getParameterNames(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::getPeakParameter(), HKLCALCULATION, Mantid::Kernel::Logger::information(), Mantid::API::IFunction::initialize(), m_genPeakStartingValue, m_instrumentParmaeters, m_unitCell, mPeakParameterNames, Mantid::Kernel::Logger::notice(), Mantid::API::IPowderDiffPeakFunction::setMillerIndex(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::setParameter(), and Mantid::Kernel::Logger::warning().
Referenced by genPeaksFromTable().
genPeakParameterDataWorkspace()
Workspace2D_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeakParameterDataWorkspace () private
Create data workspace for X0, A, B and S of peak with good fit.
Definition at line 2217 of file FitPowderDiffPeaks.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_peakFitChi2, and m_vecPeakFunctions.
Referenced by exec().
genPeakParametersWorkspace()
pair< TableWorkspace_sptr, TableWorkspace_sptr > Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeakParametersWorkspace () private
Generate output peak parameters workspace.
Generate a TableWorkspace for peaks with good fitting.
Table has column as H, K, L, d_h, X0, A(lpha), B(eta), S(igma), Chi2 Each row is a peak
Definition at line 2281 of file FitPowderDiffPeaks.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, Mantid::Kernel::getZscore(), m_peakFitChi2, and m_vecPeakFunctions.
Referenced by exec().
genPeaksFromTable()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable (const DataObjects::TableWorkspace_sptr & peakparamws) private
Generate peaks from input table workspace.
Genearte peaks from input workspace; Each peak within requirement will put into both (1) m_peaks and (2) m_peaksmap.
Definition at line 2415 of file FitPowderDiffPeaks.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, genPeak(), Mantid::API::IFunction::getParameterNames(), Mantid::Kernel::Logger::information(), Mantid::API::IFunction::initialize(), m_dataWS, m_minimumHKL, m_numPeaksLowerToMin, m_vecPeakFunctions, m_wsIndex, mPeakParameterNames, Mantid::Kernel::Logger::notice(), parseBraggPeakTable(), and Mantid::Kernel::Logger::warning().
Referenced by exec().
getHKLFromMap()
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::getHKLFromMap (std::map< std::string, int > intmap, std::vector< int > & hkl) private
Get (HKL) from a map; Return false if the information is incomplete.
Get (HKL) from a map Return false if the information is incomplete.
Parameters
intmap map as a pair of string and integer
hkl output integer vector for miller index
Definition at line 2750 of file FitPowderDiffPeaks.cpp.
Referenced by genPeak().
getParameter()
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::getParameter (const std::string & parname) private
Get parameter value from m_instrumentParameters.
Get parameter value from m_instrumentParameters Exception: throw runtime error if there is no such parameter.
Parameters
parname parameter name to get from m_instrumentParameters
Definition at line 2810 of file FitPowderDiffPeaks.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, and m_instrumentParmaeters.
Referenced by exec(), and genPeak().
importInstrumentParameterFromTable()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::importInstrumentParameterFromTable (const DataObjects::TableWorkspace_sptr & parameterWS) private
Import instrument parameters from (input) table workspace.
Import TableWorkspace containing the parameters for fitting the diffrotometer geometry parameters.
Definition at line 2084 of file FitPowderDiffPeaks.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, m_instrumentParmaeters, Mantid::Kernel::Logger::notice(), and value.
Referenced by exec().
init()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::init () override private virtual
Implement abstract Algorithm methods.
Parameter declaration.
Implements Mantid::API::Algorithm.
Definition at line 79 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::Kernel::Direction::InOut, Mantid::Kernel::Direction::Input, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 50 of file FitPowderDiffPeaks.h.
Referenced by doFit1PeakSimple(), and doFitNPeaksSimple().
observePeakRange()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::observePeakRange (const Functions::BackToBackExponential_sptr & thispeak, const Functions::BackToBackExponential_sptr & rightpeak, double refpeakshift, double & peakleftbound, double & peakrightbound) private
Observe peak range with hint from right peak's properties.
Observe peak range with hint from right peak's properties Assumption: the background is reasonably flat within peak range.
Definition at line 473 of file FitPowderDiffPeaks.cpp.
References Mantid::CurveFitting::Algorithms::findMaxValue(), Mantid::API::Algorithm::g_log, m_dataWS, m_wsIndex, and Mantid::Kernel::Logger::warning().
Referenced by fitPeaksRobust().
parseBraggPeakTable()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseBraggPeakTable (const DataObjects::TableWorkspace_sptr & peakws, std::vector< std::map< std::string, double > > & parammaps, std::vector< std::map< std::string, int > > & hklmaps) private
Import Bragg peak table workspace.
Definition at line 2125 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::g_log, and Mantid::Kernel::Logger::information().
Referenced by genPeaksFromTable().
parseFitParameterWorkspace()
std::string Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseFitParameterWorkspace (const API::ITableWorkspace_sptr & paramws) private
Parse Fit() output parameter workspace.
Parse parameter workspace returned from Fit()
Definition at line 2055 of file FitPowderDiffPeaks.cpp.
References Mantid::API::Algorithm::g_log, and Mantid::Kernel::Logger::warning().
Referenced by doFit1PeakSimple(), doFitGaussianPeak(), and doFitNPeaksSimple().
parseFitResult()
std::string Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseFitResult (const API::IAlgorithm_sptr & fitalg, double & chi2, bool & fitsuccess) private
Parse the fitting result.
Parse fit result.
Definition at line 2039 of file FitPowderDiffPeaks.cpp.
Referenced by doFit1PeakBackground(), doFit1PeakSimple(), doFitGaussianPeak(), and doFitNPeaksSimple().
plotFunction()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::plotFunction (const API::IFunction_sptr & peakfunction, const Functions::BackgroundFunction_sptr & background, const API::FunctionDomain1DVector & domain) private
Plot a single peak to output vector.
Parameters
domain domain/region of the peak to plot. It is very localized.
peakfunction function to plot
background background of the peak
Definition at line 2715 of file FitPowderDiffPeaks.cpp.
References m_dataWS, m_peakData, m_wsIndex, and Mantid::API::FunctionDomain1D::size().
Referenced by fitOverlappedPeaks(), fitSinglePeakConfident(), and fitSinglePeakRobust().
processInputProperties()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::processInputProperties () private
Process input properties.
Process input parameters.
Definition at line 253 of file FitPowderDiffPeaks.cpp.
References Mantid::EMPTY_DBL(), Mantid::Kernel::Logger::error(), FROMBRAGGTABLE, Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), HKLCALCULATION, m_dataWS, m_fitMode, m_fitPeakBackgroundComposite, m_genPeakStartingValue, m_minimumHKL, m_minPeakHeight, m_numPeaksLowerToMin, m_peakParamTable, m_profileTable, m_rightmostPeakHKL, m_rightmostPeakLeftBound, m_rightmostPeakRightBound, m_tofMax, m_tofMin, m_useGivenTOFh, m_wsIndex, ROBUSTFIT, and TRUSTINPUTFIT.
Referenced by exec().
restoreFunctionParameters()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::restoreFunctionParameters (const API::IFunction_sptr & function, std::map< std::string, double > parammap) private
Restore the function's parameter values from a map.
Definition at line 1517 of file FitPowderDiffPeaks.cpp.
Referenced by doFit1PeakSequential(), doFitMultiplePeaks(), doFitPeak(), fitSinglePeakConfident(), and fitSinglePeakRobust().
seeAlso()
const std::vector< std::string > Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 56 of file FitPowderDiffPeaks.h.
setOverlappedPeaksConstraints()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::setOverlappedPeaksConstraints (const std::vector< Functions::BackToBackExponential_sptr > & peaks) private
Set constraints on a group of overlapped peaks for fitting.
Definition at line 1961 of file FitPowderDiffPeaks.cpp.
Referenced by fitOverlappedPeaks().
storeFunctionParameters()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::storeFunctionParameters (const API::IFunction_sptr & function, std::map< std::string, double > & parammaps) private
Store the function's parameter values to a map.
Definition at line 1507 of file FitPowderDiffPeaks.cpp.
Referenced by doFit1PeakSequential(), doFitMultiplePeaks(), doFitPeak(), fitPeaksRobust(), fitSinglePeakConfident(), and fitSinglePeakRobust().
subtractBackground()
void Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::subtractBackground (DataObjects::Workspace2D_sptr dataws) private
Estimate background.
Subtract background (This is an operation within the specially defined data workspace for peak fitting)
summary()
const std::string Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 52 of file FitPowderDiffPeaks.h.
version()
int Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Definition at line 55 of file FitPowderDiffPeaks.h.
Member Data Documentation
m_chi2GoodFitPeaks
std::vector<double> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_chi2GoodFitPeaks private
Definition at line 319 of file FitPowderDiffPeaks.h.
Referenced by exec(), and fitPeaksWithGoodStartingValues().
m_confidentInInstrumentParameters
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_confidentInInstrumentParameters private
Flag to show whether input instrument parameters is trustful.
Definition at line 310 of file FitPowderDiffPeaks.h.
m_dataWS
API::MatrixWorkspace_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_dataWS private
Data.
Definition at line 269 of file FitPowderDiffPeaks.h.
Referenced by cropWorkspace(), exec(), fitOverlappedPeaks(), fitSinglePeakConfident(), fitSinglePeakRobust(), genOutputFittedPatternWorkspace(), genPeaksFromTable(), observePeakRange(), plotFunction(), and processInputProperties().
enum { ... } Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_fitMode
Fit mode.
Referenced by exec(), and processInputProperties().
m_fitPeakBackgroundComposite
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_fitPeakBackgroundComposite private
Fit peak + background as the last step.
Definition at line 343 of file FitPowderDiffPeaks.h.
Referenced by fitSinglePeakRobust(), and processInputProperties().
enum { ... } Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_genPeakStartingValue
Choice to generate peak profile paramter starting value.
Referenced by genPeak(), and processInputProperties().
m_goodFit
std::vector<bool> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_goodFit private
Peak fitting status.
Definition at line 288 of file FitPowderDiffPeaks.h.
Referenced by exec(), and fitPeaksWithGoodStartingValues().
m_indexGoodFitPeaks
std::vector<size_t> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_indexGoodFitPeaks private
Definition at line 318 of file FitPowderDiffPeaks.h.
Referenced by exec(), and fitPeaksWithGoodStartingValues().
m_instrumentParmaeters
std::map<std::string, double> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_instrumentParmaeters private
Map for function (instrument parameter)
Definition at line 291 of file FitPowderDiffPeaks.h.
Referenced by genPeak(), getParameter(), and importInstrumentParameterFromTable().
m_minimumHKL
std::vector<int> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_minimumHKL private
Minimum HKL.
Definition at line 313 of file FitPowderDiffPeaks.h.
Referenced by genPeaksFromTable(), and processInputProperties().
m_minPeakHeight
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_minPeakHeight private
Minimum peak height for peak to be refined.
Definition at line 337 of file FitPowderDiffPeaks.h.
Referenced by fitPeaksRobust(), fitSinglePeakConfident(), fitSinglePeakRobust(), and processInputProperties().
m_numPeaksLowerToMin
int Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_numPeaksLowerToMin private
Number of peaks to fit lower to minimum HKL.
Definition at line 316 of file FitPowderDiffPeaks.h.
Referenced by genPeaksFromTable(), and processInputProperties().
m_peakData
std::vector<double> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_peakData private
Data for each individual peaks. (HKL)^2, vector index, function values.
Definition at line 294 of file FitPowderDiffPeaks.h.
Referenced by exec(), and plotFunction().
m_peakFitChi2
std::vector<double> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_peakFitChi2 private
Peak fitting information.
Definition at line 285 of file FitPowderDiffPeaks.h.
Referenced by exec(), fitPeaksRobust(), fitPeaksWithGoodStartingValues(), genPeakParameterDataWorkspace(), and genPeakParametersWorkspace().
m_peakParamTable
DataObjects::TableWorkspace_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_peakParamTable private
Bragg peak parameter.
Definition at line 272 of file FitPowderDiffPeaks.h.
Referenced by exec(), and processInputProperties().
m_profileTable
DataObjects::TableWorkspace_sptr Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_profileTable private
Instrument profile parameter table workspace.
Definition at line 275 of file FitPowderDiffPeaks.h.
Referenced by exec(), and processInputProperties().
m_rightmostPeakHKL
std::vector<int> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_rightmostPeakHKL private
Right most peak HKL.
Definition at line 328 of file FitPowderDiffPeaks.h.
Referenced by fitPeaksRobust(), and processInputProperties().
m_rightmostPeakLeftBound
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_rightmostPeakLeftBound private
Right most peak's left boundary.
Definition at line 331 of file FitPowderDiffPeaks.h.
Referenced by fitPeaksRobust(), and processInputProperties().
m_rightmostPeakRightBound
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_rightmostPeakRightBound private
Right most peak's right boundary.
Definition at line 334 of file FitPowderDiffPeaks.h.
Referenced by fitPeaksRobust(), and processInputProperties().
m_tofMax
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_tofMax private
Definition at line 304 of file FitPowderDiffPeaks.h.
Referenced by exec(), and processInputProperties().
m_tofMin
double Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_tofMin private
TOF Min and TOF Max.
Definition at line 303 of file FitPowderDiffPeaks.h.
Referenced by calculatePeakFitBoundary(), exec(), and processInputProperties().
m_unitCell
Geometry::UnitCell Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_unitCell private
Unit cell of powder crystal.
Definition at line 340 of file FitPowderDiffPeaks.h.
Referenced by exec(), and genPeak().
m_useGivenTOFh
bool Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_useGivenTOFh private
Flag to use given Bragg peaks' centre in TOF.
Definition at line 307 of file FitPowderDiffPeaks.h.
Referenced by processInputProperties().
m_vecPeakFunctions
std::vector<std::pair<double, std::pair<std::vector<int>, Functions::BackToBackExponential_sptr> > > Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_vecPeakFunctions private
Sorted vector for peaks. double = d_h, vector = (HKL), peak.
Definition at line 282 of file FitPowderDiffPeaks.h.
Referenced by calculatePeakFitBoundary(), exec(), fitPeaksRobust(), fitPeaksWithGoodStartingValues(), genPeakParameterDataWorkspace(), genPeakParametersWorkspace(), and genPeaksFromTable().
m_wsIndex
int Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::m_wsIndex private
TOF vector of data workspace to process with.
Definition at line 300 of file FitPowderDiffPeaks.h.
Referenced by cropWorkspace(), exec(), fitOverlappedPeaks(), fitSinglePeakConfident(), fitSinglePeakRobust(), genPeaksFromTable(), observePeakRange(), plotFunction(), and processInputProperties().
mPeakParameterNames
std::vector<std::string> Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::mPeakParameterNames private
Peak parmeter names.
Definition at line 297 of file FitPowderDiffPeaks.h.
Referenced by genPeak(), and genPeaksFromTable().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/FitPowderDiffPeaks.h
Framework/CurveFitting/src/Algorithms/FitPowderDiffPeaks.cpp