Mantid: MantidQt::MantidWidgets Namespace Reference
MantidQt::MantidWidgets Namespace Reference
Namespaces
namespace Batch
namespace DropEventHelper
namespace QSettingsHelper
namespace WorkspaceUtils
Classes
class AddWorkspaceDialog
class AddWorkspaceMultiDialog
class ADSAdapter
class AlgorithmFinishObserver
class AlgorithmHintStrategy
AlgorithmHintStrategy : Produces hints using a given algorithm's properties.
class AlgorithmProgressDialogPresenter
class AlgorithmProgressDialogWidget
class AlgorithmProgressDialogWidgetCancelButton
class AlgorithmProgressModel
class AlgorithmProgressPresenter
class AlgorithmProgressPresenterBase
class AlgorithmProgressWidget
class AlgorithmSelectorWidget
A widget consisting of a ComboBox and a TreeWidget to allow a user to select an algorithm either by category or by typing.
class AlgorithmTreeWidget
Tree widget with the categories and algorithms listed.
struct ApplyEnumeratedSpectra
struct ApplySpectra
class BinMDDialog
class CatalogHelper
class CatalogSearch
This class defines the interface and functionality for the cataloging system within Mantid.
class CatalogSelector
class CheckboxHeader
This class subclasses and overwrites QHeaderView methods to enable checkboxes to exist in the table header.
class Configurable
Defines an interface for an object to load and store any configuration settings that should persist between objects.
class ConvolutionFunctionModel
class CreateAttributeProperty
Attribute visitor to create a QtProperty.
class CreateAttributePropertyForFunctionTreeView
Attribute visitor to create a QtProperty.
class CustomItemDelegate
This class is used for formating the type of data allowed in each of the tables columns.
class DataSelector
This class defines a widget for selecting a workspace of file path by using a combination of two child MantidWidgets: FileFinderWidget and WorkspaceSelector.
class DiagResults
class EditLocalParameterDialog
A dialog for displaying and editing values of local parameters.
class FilenameDialogEditor
A stringDialogEditor for editing file names.
class FilenameDialogEditorFactory
The factory for the FilenameDialogEditor.
class FindAlgComboBox
ComboBox for finding algorithms.
class FindPeakConvolveStrategy
class FindPeakDefaultStrategy
class FindPeakStrategy
class FindPeakStrategyGeneric
class FitDomain
This class is used to store all data relating to a single domain to be fitted.
class FitOptionsBrowser
Class FitOptionsBrowser implements QtPropertyBrowser to display and set properties of Fit algorithm (excluding Function and Workspace)
class FitPropertyBrowser
Class FitPropertyBrowser implements QtPropertyBrowser to display and control fitting function parameters and settings.
class FitScriptGeneratorDataTable
This class represents the table widget which holds domain data for the FitScriptGenerator interface.
class FitScriptGeneratorModel
This class stores the domain and fit data to be fitted to.
class FitScriptGeneratorPresenter
class FitScriptGeneratorView
class FitScriptOptionsBrowser
The BasicFitOptionsBrowser class implements a QtPropertyBrowser to display fitting properties found in the Fit algorithm.
class FunctionBrowser
Class FitPropertyBrowser implements QtPropertyBrowser to display and control fitting function parameters and settings.
class FunctionModel
struct FunctionModelDataset
class FunctionModelSpectra
class FunctionMultiDomainPresenter
class FunctionTreeView
Class FitPropertyBrowser implements QtPropertyBrowser to display and control fitting function parameters and settings.
struct GlobalParameter
This struct stores the name of a global parameter which is shared across ALL domains in a multi dataset fit.
struct GlobalTie
This struct stores the data associated with a global tie.
class Hint
class HintingLineEdit
HintingLineEdit : A QLineEdit widget providing autocompletion.
class HintingLineEditFactory
HintingLineEditFactory : A QStyledItemDelegate that produces HintingLineEdits using the given hint strategy.
class HintStrategy
HintStrategy : Provides an interface for generating hints to be used by a HintingLineEdit.
class IAddWorkspaceDialog
class IAlgorithmProgressDialogWidget
class IAlgorithmProgressWidget
class IFitScriptGeneratorModel
class IFitScriptGeneratorPresenter
class IFitScriptGeneratorView
class IFunctionBrowser
IFunctionBrowser: interface for FunctionBrowser.
class IFunctionModel
class IFunctionView
The interface to a function view.
class IImageInfoWidget
class ImageInfoModel
class ImageInfoModelMatrixWS
Model to support looking up information about a given point with a MatrixWorkspace.
class ImageInfoModelMD
class ImageInfoPresenter
A table widget containing information about the pixel the mouse is over in an image.
class ImageInfoWidget
A table widget containing information about the pixel the mouse is over in an image.
class ImageInfoWidgetMini
A table widget containing information about the pixel the mouse is over in an image.
class IMessageHandler
class IMuonFitDataModel
IMuonFitDataModel: set data to fit for a muon fit property browser.
class IMuonFitDataSelector
Interface for MuonFitDataSelector.
class IMuonFitFunctionModel
IMuonFitFunctionModel: set function to fit for a muon fit property browser.
class IndexCollectionType
A class which wraps a vector so that you supply not only the value type but also the expected index type.
struct IndexType
A struct to impliment strongly typed integers, without implicit conversion.
class InputController
The base class for the mouse and keyboard controllers to work with ProjectionSurfaces.
class InputController3DMove
Controller for moving the instrument on Projection3D surface: translation, rotation and zooming.
class InputControllerDraw
Controller for free drawing on an unwrapped surface.
class InputControllerDrawAndErase
Controller for drawing and erasing arbitrary shapes on an unwrapped surface.
class InputControllerDrawShape
Controller for drawing mask shapes.
class InputControllerMoveUnwrapped
Controller for moving the instrument on an unwrapped surface.
class InputControllerPick
Controller for picking detectors.
class InputControllerSelection
Controller for erasing peaks on an unwrapped surface.
class InputFunctionNameDialog
A dialog to enter a category and function name for a new function for saving.
class InstrumentSelector
This class defines a widget for selecting an instrument known to Mantid.
class Interval
class IntervalList
class IntervalListValidator
class IProjectSaveView
IProjectSaveView is the interface for defining the functions that the project save view needs to implement.
class ISlitCalculator
class IWorkspaceDockView
class IWorkspaceFitControl
IWorkspaceFitControl: set data to fit for a fit property browser.
class LineEditWithClear
class LocalParameterEditor
An editor widget for editing a local parameter value.
class LocalParameterItemDelegate
A custom item delegate - an object controlling display and editing of a cell in a table widget.
class LogValueFinder
MDFLogValueFinder : Holds a collection of workspace names, and finds log values from them.
class LogValueSelector
LogValueSelector : Select a log name and mean/min/max/first/last.
class MantidDisplayBase
class MantidTreeModel
class MantidTreeWidget
class MantidTreeWidgetItem
A class derived from QTreeWidgetItem, to accomodate sorting on the items in a MantidTreeWidget.
class MantidWSIndexDialog
class MantidWSIndexWidget
class Message
Provides a simple binding of a text message with a priority.
class MessageDisplay
Provides a widget for display messages in a text box It deals with Message objects which in turn hide whether a message is a framework Poco message or a simple string.
class MessageHandler
class MultifitSetupDialog
This is a dialog for doing setting up the MultiBG function.
class MuonFitDataSelector
MuonFitDataSelector : Selects runs, groups, periods for fit.
class MuonFitPropertyBrowser
class MuonFunctionBrowser
MuonFunctionBrowser : Subclasses FunctionBrowser for muon-specific use.
class MuonPeriodInfo
A widget used in the Muon GUI's to display period information in a readable format.
class NotificationService
This is a singleton providing a notification service for the Mantid Qt based applications.
class NumericInputDelegate
struct PlotMenuActions
class ProcessingAlgoWidget
A widget containing an algorithm selector and algorithm properties list, or a script editor window.
class ProgressableView
ProgressableView : Abstract view useful for indicating progress.
class ProjectSaveModel
class ProjectSavePresenter
Implements a presenter for the project saving dialog.
class PropertyHandler
Helps display and edit functions in FitPropertyBrowser.
class PythonHelpBridge
class PythonHelpWindow
class QtSignalChannel
Provides a translation layer that takes a Poco::Message and converts it to a Qt signal.
class RegexInputDelegate
class RenameParDialog
A dialog for renaming parameters for a user function.
class SaveWorkspaces
Implements a dialog box that allows users to save multiple Mantid workspaces.
class ScopedFalse
struct SelectedAlgorithm
Represents the algorithm selected by the user Contains name and version.
class SelectFunctionDialog
Select a function type out of a list of available ones.
class SelectWorkspacesDialog
This is a dialog for selecting workspaces.
class SequentialFitDialog
This is a dialog for doing sequential fit.
class SetAttribute
Visitor setting new attribute value.
class SetAttributeFromProperty
Attribute visitor to set an attribute from a QtProperty.
class SetAttributeProperty
Visitor setting new attribute value.
class SliceMDDialog
class SlicingAlgorithmDialog
class SlitCalculator
SlitCalculator : A calculator for Reflectometry instrument slits.
class TrackedAction
TrackedAction : This is a version of QAction that tracks usage through the Mantid usage service.
class UserFunctionDialog
A dialog for construction a user fitting function from existing components.
class ViewNotifiable
struct WindowInfo
struct WorkspaceInfo
class WorkspaceIsNotOfType
Helper comparitor class used to determine if a workspace is not of a given type.
class WorkspaceMultiSelector
This class defines a widget for selecting multiple workspace present in the AnalysisDataService and adding to a QTableWidget.
class WorkspacePresenter
Presenter class for Workspace dock in MantidPlot UI.
class WorkspaceProvider
class WorkspaceProviderNotifiable
class WorkspaceSelector
This class defines a widget for selecting a workspace present in the AnalysisDataService.
class WorkspaceTreeWidget
class WorkspaceTreeWidgetSimple
WorkspaceTreeWidget implementation for the Workbench - required for some function overides.
Typedefs
using ADSAdapter_uptr = std::unique_ptr< WorkspaceProvider >
using ButtonOpts = API::FileFinderWidget::ButtonOpts
using ColumnIndex = FitScriptGeneratorDataTable::ColumnIndex
using FitDomainIndex = IndexType< 0 >
using LiveButtonOpts = API::FileFinderWidget::LiveButtonOpts
using MenuActions = std::vector< QAction * >
using Presenter_sptr = std::shared_ptr< WorkspaceProviderNotifiable >
using Presenter_wptr = std::weak_ptr< WorkspaceProviderNotifiable >
using PropertyDimensionMap = QMap< QString, QString >
using StringList = std::vector< std::string >
using ViewEvent = IFitScriptGeneratorView::Event
using WorkspaceID = IndexType< 2 >
using WorkspaceIndex = IndexType< 1 >
using WorkspacePresenterVN_sptr = std::shared_ptr< ViewNotifiable >
using WorkspacePresenterWN_wptr = std::weak_ptr< WorkspaceProviderNotifiable >
Enumerations
enum class FittingMode { SEQUENTIAL , SIMULTANEOUS , SEQUENTIAL_AND_SIMULTANEOUS }
enum class MantidItemSortScheme { ByName , ByLastModified , ByMemorySize }
enum RegexValidatorStrings { MaskValidator , SpectraValidator }
Functions
std::string EXPORT_OPT_MANTIDQT_COMMON convertAlgPropsToString (Mantid::API::IAlgorithmRuntimeProps const &options)
QString EXPORT_OPT_MANTIDQT_COMMON convertMapToString (const std::map< QString, QString > &optionsMap, const char separator=',', const bool quoteValues=true)
Convert an options map to a string.
std::string EXPORT_OPT_MANTIDQT_COMMON convertMapToString (const std::map< std::string, std::string > &optionsMap, const char separator, const bool quoteValues)
Convert an options map to a comma-separated list of key=value pairs.
QVector< QString > EXPORT_OPT_MANTIDQT_COMMON convertStdStringVector (const std::vector< std::string > &stringVec)
QString formatNonAlignedDimensionInput (const Mantid::Geometry::IMDDimension_const_sptr &)
Create a formatted string for the dimension input based on an existing dimension.
QString formattedAlignedDimensionInput (const Mantid::Geometry::IMDDimension_const_sptr &dim)
Create a formatted string for the dimension input based on an existing dimension.
EXPORT_OPT_MANTIDQT_COMMON std::size_t getFunctionIndexAt (std::string const &parameter, std::size_t const &index)
Returns the function index found at index of a parameter.
EXPORT_OPT_MANTIDQT_COMMON IFunction_sptr getFunctionWithPrefix (std::string const &prefix, const IFunction_sptr &fun)
Get a child function of a parent function whose parameters start with a given prefix.
EXPORT_OPT_MANTIDQT_COMMON std::string getRegexValidatorString (const RegexValidatorStrings &validatorMask)
EXPORT_OPT_MANTIDQT_COMMON bool isNumber (std::string const &str)
Checks if a string contains a number, or whether it contains characters.
EXPORT_OPT_MANTIDQT_COMMON QString makeQStringNumber (double value, int precision)
EXPORT_OPT_MANTIDQT_COMMON bool operator!= (Hint const &lhs, Hint const &rhs)
template<int Class>
std::ostream & operator<< (std::ostream &os, const IndexType< Class > &value)
EXPORT_OPT_MANTIDQT_COMMON bool operator== (Hint const &lhs, Hint const &rhs)
std::string EXPORT_OPT_MANTIDQT_COMMON optionsToString (std::map< std::string, std::string > const &options, const bool quoteValues=true, const std::string &separator=", ")
int EXPORT_OPT_MANTIDQT_COMMON parseDenaryInteger (QString const &in)
Converts a string denoting a denary integer to it.
double EXPORT_OPT_MANTIDQT_COMMON parseDouble (QString const &in)
std::map< QString, QString > DLLExport parseKeyValueQString (const QString &qstr, const std::string &separator)
Parses a string in the format ‘a = 1,b=2, c = "1,2,3,4", d = 5.0, e='a,b,c’` into a map of key/value pairs.
std::map< std::string, std::string > DLLExport parseKeyValueString (const std::string &str, const std::string &separator)
Parses a string in the format ‘a = 1,b=2, c = "1,2,3,4", d = 5.0, e='a,b,c’` into a map of key/value pairs.
std::vector< std::string > EXPORT_OPT_MANTIDQT_COMMON qListToStdVector (QList< std::string > const &qList)
std::vector< std::string > EXPORT_OPT_MANTIDQT_COMMON qStringListToStdVector (QStringList const &qList)
std::map< std::string, double > readMultipleNormalization ()
Reads the normalization constants and which WS they belong to.
EXPORT_OPT_MANTIDQT_COMMON std::pair< std::string, std::pair< std::string, std::string > > splitConstraintString (const std::string &constraint)
Split a constraint definition into a parameter name and a pair of bounds, for example -1 < f0.A1 < 2 ==> (f0.A1, (-1, 2))
EXPORT_OPT_MANTIDQT_COMMON std::pair< std::string, int > splitFunctionPrefix (std::string const &prefix)
Split a function (eg f0.f3.f1.) into the parent prefix (f0.f3.) and the index of the child function (1).
EXPORT_OPT_MANTIDQT_COMMON std::pair< std::string, std::string > splitParameterName (std::string const &parameterName)
Split a qualified parameter name into function index and local parameter name.
EXPORT_OPT_MANTIDQT_COMMON std::vector< std::string > splitStringBy (std::string const &str, std::string const &delimiter)
Splits the string by the given delimiters.
QStringList EXPORT_OPT_MANTIDQT_COMMON stdVectorToQStringList (std::vector< std::string > const &vec)
void trimWhitespaceAndQuotes (const QString &valueIn)
void trimWhitespaceAndQuotes (QString &value)
Trim whitespace and quotes from the start/end of a string.
void trimWhitespaceQuotesAndEmptyValues (QStringList &values)
Trim whitespace and quotes from the start/end for all strings in the given list, and subsequently remove any empty strings from the list.
template<class T >
std::vector< T > vectorFromString (const std::string &listString)
Typedef Documentation
ADSAdapter_uptr
using MantidQt::MantidWidgets::ADSAdapter_uptr = typedef std::unique_ptr<WorkspaceProvider>
Definition at line 21 of file WorkspacePresenter.h.
ButtonOpts
using MantidQt::MantidWidgets::ButtonOpts = typedef API::FileFinderWidget::ButtonOpts
Definition at line 21 of file DataSelector.h.
ColumnIndex
typedef FitScriptGeneratorDataTable::ColumnIndex MantidQt::MantidWidgets::ColumnIndex
Definition at line 93 of file FitScriptGeneratorDataTable.h.
FitDomainIndex
using MantidQt::MantidWidgets::FitDomainIndex = typedef IndexType<0>
Definition at line 59 of file IndexTypes.h.
LiveButtonOpts
using MantidQt::MantidWidgets::LiveButtonOpts = typedef API::FileFinderWidget::LiveButtonOpts
Definition at line 22 of file DataSelector.h.
MenuActions
using MantidQt::MantidWidgets::MenuActions = typedef std::vector<QAction *>
Definition at line 24 of file WorkspaceTreeWidgetSimple.h.
Presenter_sptr
using MantidQt::MantidWidgets::Presenter_sptr = typedef std::shared_ptr<WorkspaceProviderNotifiable>
Definition at line 19 of file WorkspaceProvider.h.
Presenter_wptr
using MantidQt::MantidWidgets::Presenter_wptr = typedef std::weak_ptr<WorkspaceProviderNotifiable>
Definition at line 20 of file WorkspaceProvider.h.
PropertyDimensionMap
using MantidQt::MantidWidgets::PropertyDimensionMap = typedef QMap<QString, QString>
Definition at line 22 of file SlicingAlgorithmDialog.h.
StringList
using MantidQt::MantidWidgets::StringList = typedef std::vector<std::string>
Definition at line 21 of file IWorkspaceDockView.h.
ViewEvent
typedef IFitScriptGeneratorView::Event MantidQt::MantidWidgets::ViewEvent
Definition at line 22 of file IFitScriptGeneratorPresenter.h.
WorkspaceID
using MantidQt::MantidWidgets::WorkspaceID = typedef IndexType<2>
Definition at line 63 of file IndexTypes.h.
WorkspaceIndex
using MantidQt::MantidWidgets::WorkspaceIndex = typedef IndexType<1>
Definition at line 61 of file IndexTypes.h.
WorkspacePresenterVN_sptr
using MantidQt::MantidWidgets::WorkspacePresenterVN_sptr = typedef std::shared_ptr<ViewNotifiable>
Definition at line 20 of file IWorkspaceDockView.h.
WorkspacePresenterWN_wptr
using MantidQt::MantidWidgets::WorkspacePresenterWN_wptr = typedef std::weak_ptr<WorkspaceProviderNotifiable>
Definition at line 19 of file IWorkspaceDockView.h.
Enumeration Type Documentation
FittingMode
enum class MantidQt::MantidWidgets::FittingMode strong
Enumerator
SEQUENTIAL
SIMULTANEOUS
SEQUENTIAL_AND_SIMULTANEOUS
Definition at line 12 of file FittingMode.h.
MantidItemSortScheme
enum class MantidQt::MantidWidgets::MantidItemSortScheme strong
Enumerator
ByName
ByLastModified
ByMemorySize
Definition at line 22 of file MantidTreeWidget.h.
RegexValidatorStrings
enum MantidQt::MantidWidgets::RegexValidatorStrings
Enumerator
MaskValidator
SpectraValidator
Definition at line 21 of file TableWidgetValidators.h.
Function Documentation
convertAlgPropsToString()
std::string MantidQt::MantidWidgets::convertAlgPropsToString (Mantid::API::IAlgorithmRuntimeProps const & options)
Definition at line 265 of file ParseKeyValueString.cpp.
References Mantid::Kernel::IPropertyManager::getDeclaredPropertyNames(), and Mantid::Kernel::IPropertyManager::getPropertyValue().
convertMapToString() [1/2]
QString MantidQt::MantidWidgets::convertMapToString (const std::map< QString, QString > & optionsMap, const char separator = ',', const bool quoteValues = true)
Convert an options map to a string.
Convert an options map to a comma-separated list of key=value pairs.
Definition at line 190 of file ParseKeyValueString.cpp.
References value.
convertMapToString() [2/2]
std::string MantidQt::MantidWidgets::convertMapToString (const std::map< std::string, std::string > & optionsMap, const char separator, const bool quoteValues)
Convert an options map to a comma-separated list of key=value pairs.
Definition at line 217 of file ParseKeyValueString.cpp.
References value.
convertStdStringVector()
QVector< QString > MantidQt::MantidWidgets::convertStdStringVector (const std::vector< std::string > & stringVec)
Definition at line 306 of file ParseKeyValueString.cpp.
formatNonAlignedDimensionInput()
QString MantidQt::MantidWidgets::formatNonAlignedDimensionInput (const Mantid::Geometry::IMDDimension_const_sptr &)
Create a formatted string for the dimension input based on an existing dimension.
As the input it is expected the dimension to format the string.
It is expected that inherited classes will be able to implement this method, but this class can not obviously define how the basis vectors could be automatically formed, so, it retuns always an empty string.
Returns
: empty string.
Definition at line 122 of file SlicingAlgorithmDialog.cpp.
Referenced by MantidQt::MantidWidgets::SlicingAlgorithmDialog::buildDimensionInputs().
formattedAlignedDimensionInput()
QString MantidQt::MantidWidgets::formattedAlignedDimensionInput (const Mantid::Geometry::IMDDimension_const_sptr & dim)
Create a formatted string for the dimension input based on an existing dimension.
Parameters
dim : dimension to format to string.
Definition at line 99 of file SlicingAlgorithmDialog.cpp.
References name.
Referenced by MantidQt::MantidWidgets::SlicingAlgorithmDialog::buildDimensionInputs().
getFunctionIndexAt()
std::size_t MantidQt::MantidWidgets::getFunctionIndexAt (std::string const & parameter, std::size_t const & index)
Returns the function index found at index of a parameter.
Definition at line 136 of file FunctionBrowserUtils.cpp.
References index, isNumber(), and splitStringBy().
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentParameterTieForDomain(), MantidQt::MantidWidgets::FitDomain::updateParameterConstraint(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterValueInGlobalTie().
getFunctionWithPrefix()
IFunction_sptr MantidQt::MantidWidgets::getFunctionWithPrefix (std::string const & prefix, const IFunction_sptr & fun)
Get a child function of a parent function whose parameters start with a given prefix.
Parameters
prefix :: A prefix of the form f0.f1. If en empty string is given then the parent function is returned.
fun :: The parent function.
Definition at line 31 of file FunctionBrowserUtils.cpp.
References getFunctionWithPrefix().
Referenced by MantidQt::MantidWidgets::FunctionModel::addConstraint(), MantidQt::MantidWidgets::FunctionModel::addFunction(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFunctionByIndex(), getFunctionWithPrefix(), MantidQt::MantidWidgets::FunctionModel::removeFunction(), and MantidQt::MantidWidgets::FunctionModel::setLocalParameterConstraint().
getRegexValidatorString()
std::string MantidQt::MantidWidgets::getRegexValidatorString (const RegexValidatorStrings & validatorMask)
Definition at line 38 of file TableWidgetValidators.cpp.
References MaskValidator, and SpectraValidator.
Referenced by MantidQt::MantidWidgets::AddWorkspaceDialog::AddWorkspaceDialog(), and MantidQt::MantidWidgets::WorkspaceMultiSelector::setupTable().
isNumber()
bool MantidQt::MantidWidgets::isNumber (std::string const & str)
Checks if a string contains a number, or whether it contains characters.
Definition at line 123 of file FunctionBrowserUtils.cpp.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorModel::getAdjustedFunctionIndex(), MantidQt::MantidWidgets::FitScriptGeneratorModel::getEquivalentParameterTieForDomain(), MantidQt::MantidWidgets::FitScriptGeneratorModel::getFullTie(), MantidQt::MantidWidgets::FunctionTreeView::getFullTie(), getFunctionIndexAt(), MantidQt::MantidWidgets::FitDomain::getTieValue(), MantidQt::MantidWidgets::FitDomain::isValidParameterTie(), MantidQt::MantidWidgets::LocalParameterEditor::setEditorState(), MantidQt::MantidWidgets::FitScriptGeneratorModel::validGlobalTie(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::validTie().
makeQStringNumber()
QString MantidQt::MantidWidgets::makeQStringNumber (double value, int precision)
Definition at line 49 of file TableWidgetValidators.cpp.
References value.
Referenced by MantidQt::MantidWidgets::NumericInputDelegate::setEditorData().
operator!=()
bool MantidQt::MantidWidgets::operator!= (Hint const & lhs, Hint const & rhs)
Definition at line 21 of file Hint.cpp.
References rhs.
operator<<()
template<int Class> std::ostream & MantidQt::MantidWidgets::operator<< (std::ostream & os, const IndexType< Class > & value) inline
Definition at line 54 of file IndexTypes.h.
References value.
operator==()
bool MantidQt::MantidWidgets::operator== (Hint const & lhs, Hint const & rhs)
Definition at line 17 of file Hint.cpp.
References MantidQt::MantidWidgets::Hint::description(), rhs, and MantidQt::MantidWidgets::Hint::word().
optionsToString()
std::string MantidQt::MantidWidgets::optionsToString (std::map< std::string, std::string > const & options, const bool quoteValues = true, const std::string & separator = ", ")
Definition at line 243 of file ParseKeyValueString.cpp.
parseDenaryInteger()
int MantidQt::MantidWidgets::parseDenaryInteger (QString const & in)
Converts a string denoting a denary integer to it.
Definition at line 20 of file ParseNumerics.cpp.
parseDouble()
double MantidQt::MantidWidgets::parseDouble (QString const & in)
Definition at line 11 of file ParseNumerics.cpp.
parseKeyValueQString()
std::map< QString, QString > MantidQt::MantidWidgets::parseKeyValueQString (const QString & qstr, const std::string & separator)
Parses a string in the format ‘a = 1,b=2, c = "1,2,3,4", d = 5.0, e='a,b,c’` into a map of key/value pairs.
Parameters
qstr The input string
separator The character between each key=value pair
Exceptions
std::runtime_error on an invalid input string
Returns
: a map of key/value pairs as QStrings
Definition at line 148 of file ParseKeyValueString.cpp.
References value.
parseKeyValueString()
std::map< std::string, std::string > MantidQt::MantidWidgets::parseKeyValueString (const std::string & str, const std::string & separator)
Parses a string in the format ‘a = 1,b=2, c = "1,2,3,4", d = 5.0, e='a,b,c’` into a map of key/value pairs.
Parameters
str The input string
separator The character between each key=value pair
Exceptions
std::runtime_error on an invalid input string
Returns
: a map of key/value pairs as strings
Definition at line 97 of file ParseKeyValueString.cpp.
References value.
qListToStdVector()
std::vector< std::string > MantidQt::MantidWidgets::qListToStdVector (QList< std::string > const & qList)
Definition at line 292 of file ParseKeyValueString.cpp.
References vec.
qStringListToStdVector()
std::vector< std::string > MantidQt::MantidWidgets::qStringListToStdVector (QStringList const & qList)
Definition at line 284 of file ParseKeyValueString.cpp.
References vec.
Referenced by MantidQt::MantidWidgets::FitScriptGeneratorView::getEditLocalParameterResults().
readMultipleNormalization()
std::map< std::string, double > MantidQt::MantidWidgets::readMultipleNormalization ()
Reads the normalization constants and which WS they belong to.
Returns
:: A map of normalization constants and WS names
Definition at line 726 of file MuonFitPropertyBrowser.cpp.
References readMultipleNormalization().
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), readMultipleNormalization(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization().
splitConstraintString()
std::pair< std::string, std::pair< std::string, std::string > > MantidQt::MantidWidgets::splitConstraintString (const std::string & constraint)
Split a constraint definition into a parameter name and a pair of bounds, for example -1 < f0.A1 < 2 ==> (f0.A1, (-1, 2))
Definition at line 62 of file FunctionBrowserUtils.cpp.
References error, Mantid::API::Expression::name(), name, Mantid::API::Expression::operator_name(), Mantid::API::Expression::parse(), Mantid::API::Expression::size(), and Mantid::API::Expression::str().
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addConstraintProperties(), and MantidQt::MantidWidgets::FunctionModel::setLocalParameterConstraint().
splitFunctionPrefix()
std::pair< std::string, int > MantidQt::MantidWidgets::splitFunctionPrefix (std::string const & prefix)
Split a function (eg f0.f3.f1.) into the parent prefix (f0.f3.) and the index of the child function (1).
Definition at line 52 of file FunctionBrowserUtils.cpp.
Referenced by MantidQt::MantidWidgets::FunctionModel::removeFunction().
splitParameterName()
std::pair< std::string, std::string > MantidQt::MantidWidgets::splitParameterName (std::string const & parameterName)
Split a qualified parameter name into function index and local parameter name.
Parameters
parameterName :: Fully qualified parameter name (includes function prefix) for example: f0.f1.A0
Returns
:: A pair with the first item is the function index and the second item is the param local name.
Definition at line 18 of file FunctionBrowserUtils.cpp.
Referenced by MantidQt::MantidWidgets::FunctionTreeView::addConstraints(), MantidQt::MantidWidgets::FunctionTreeView::addConstraints10(), MantidQt::MantidWidgets::FunctionTreeView::addConstraints50(), MantidQt::MantidWidgets::FunctionTreeView::getAttributeProperty(), MantidQt::MantidWidgets::FunctionTreeView::getFunctionAndConstraint(), MantidQt::MantidWidgets::FunctionTreeView::getParameterProperty(), MantidQt::MantidWidgets::FunctionModel::setLocalParameterConstraint(), MantidQt::MantidWidgets::FunctionTreeView::setParameterError(), and MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedParameter().
splitStringBy()
std::vector< std::string > MantidQt::MantidWidgets::splitStringBy (std::string const & str, std::string const & delimiter)
Splits the string by the given delimiters.
Definition at line 127 of file FunctionBrowserUtils.cpp.
Referenced by getFunctionIndexAt(), and MantidQt::MantidWidgets::FitScriptGeneratorModel::validTie().
stdVectorToQStringList()
QStringList MantidQt::MantidWidgets::stdVectorToQStringList (std::vector< std::string > const & vec)
Definition at line 276 of file ParseKeyValueString.cpp.
References vec.
Referenced by MantidQt::MantidWidgets::EditLocalParameterDialog::doSetup(), and MantidQt::MantidWidgets::FitScriptGeneratorView::openEditLocalParameterDialog().
trimWhitespaceAndQuotes() [1/2]
void MantidQt::MantidWidgets::trimWhitespaceAndQuotes (const QString & valueIn)
Referenced by trimWhitespaceAndQuotes(), and trimWhitespaceQuotesAndEmptyValues().
trimWhitespaceAndQuotes() [2/2]
void MantidQt::MantidWidgets::trimWhitespaceAndQuotes (QString & value)
Trim whitespace and quotes from the start/end of a string.
Edits the value in-place.
Parameters
value [inout]: the value to trim
Definition at line 61 of file ParseKeyValueString.cpp.
References trimWhitespaceAndQuotes(), and value.
trimWhitespaceQuotesAndEmptyValues()
void MantidQt::MantidWidgets::trimWhitespaceQuotesAndEmptyValues (QStringList & values)
Trim whitespace and quotes from the start/end for all strings in the given list, and subsequently remove any empty strings from the list.
Edits the list in-place.
Parameters
values : the list of values to trim
Definition at line 82 of file ParseKeyValueString.cpp.
References trimWhitespaceAndQuotes(), and value.
vectorFromString()
template<class T > std::vector< T > MantidQt::MantidWidgets::vectorFromString (const std::string & listString)
Definition at line 88 of file FunctionModelSpectra.h.