Mantid: Mantid::API::FileLoaderRegistryImpl Class Reference
Mantid::API::FileLoaderRegistryImpl Class Reference
Keeps a registry of algorithm's that are file loading algorithms to allow them to be searched to find the correct one to load a particular file.
#include <FileLoaderRegistry.h>
Classes
struct SubscriptionValidator
Helper for subscribe to check base class.
Public Types
enum LoaderFormat { LegacyNexus , Generic , Nexus }
Defines types of possible file.
Public Member Functions
bool canLoad (const std::string &algorithmName, const std::string &filename) const
Checks whether the given algorithm can load the file.
const std::shared_ptr< IAlgorithm > chooseLoader (const std::string &filename) const
Returns the name of an Algorithm that can load the given filename.
size_t size () const
template<typename Type >
void subscribe (LoaderFormat format)
Registers a loader whose format is one of the known formats given in LoaderFormat.
void unsubscribe (const std::string &name, const int version=-1)
Unsubscribe a named algorithm and version from the loader registration.
Private Member Functions
FileLoaderRegistryImpl ()
Default constructor (for singleton)
void removeAlgorithm (const std::string &name, const int version, std::multimap< std::string, int > &typedLoaders)
Remove a named algorithm & version from the given map.
~FileLoaderRegistryImpl ()
Destructor.
Private Attributes
Kernel::Logger m_log
Reference to a logger.
std::array< std::multimap< std::string, int >, 3 > m_names
The list of names.
size_t m_totalSize
Total number of names registered.
Friends
struct Mantid::Kernel::CreateUsingNew< FileLoaderRegistryImpl >
Friend so that CreateUsingNew.
Detailed Description
Keeps a registry of algorithm's that are file loading algorithms to allow them to be searched to find the correct one to load a particular file.
A macro, DECLARE_FILELOADER_ALGORITHM is defined in RegisterFileLoader.h. Use this in place of the standard DECLARE_ALGORITHM macro
Definition at line 42 of file FileLoaderRegistry.h.
Member Enumeration Documentation
LoaderFormat
enum Mantid::API::FileLoaderRegistryImpl::LoaderFormat
Defines types of possible file.
Enumerator
LegacyNexus
Generic
Nexus
Definition at line 45 of file FileLoaderRegistry.h.
Constructor & Destructor Documentation
FileLoaderRegistryImpl()
Mantid::API::FileLoaderRegistryImpl::FileLoaderRegistryImpl () private
Default constructor (for singleton)
Creates an empty registry.
m_names is initialized in the header
Definition at line 211 of file FileLoaderRegistry.cpp.
~FileLoaderRegistryImpl()
Mantid::API::FileLoaderRegistryImpl::~FileLoaderRegistryImpl () private default
Destructor.
Member Function Documentation
canLoad()
bool Mantid::API::FileLoaderRegistryImpl::canLoad (const std::string & algorithmName, const std::string & filename) const
Checks whether the given algorithm can load the file.
Perform a check that that the given algorithm can load the file.
Parameters
algorithmName The name of the algorithm to check
filename The name of file to check
Returns
True if the algorithm can load the file, false otherwise
Exceptions
std::invalid_argument if the loader does not exist
Definition at line 167 of file FileLoaderRegistry.cpp.
References Mantid::Kernel::Logger::debug(), Generic, LegacyNexus, m_log, m_names, and Nexus.
Referenced by export_FileLoaderRegistry().
chooseLoader()
const std::shared_ptr< IAlgorithm > Mantid::API::FileLoaderRegistryImpl::chooseLoader (const std::string & filename) const
Returns the name of an Algorithm that can load the given filename.
Queries each registered algorithm and asks it how confident it is that it can load the given file.
The name of the one with the highest confidence is returned.
Parameters
filename A full file path pointing to an existing file
Returns
A string containing the name of an algorithm to load the file
Exceptions
Exception::NotFoundError if an algorithm cannot be found
Definition at line 114 of file FileLoaderRegistry.cpp.
References Mantid::Kernel::Logger::debug(), Generic, LegacyNexus, m_log, m_names, and Nexus.
Referenced by export_FileLoaderRegistry().
removeAlgorithm()
void Mantid::API::FileLoaderRegistryImpl::removeAlgorithm (const std::string & name, const int version, std::multimap< std::string, int > & typedLoaders) private
Remove a named algorithm & version from the given map.
Parameters
name A string containing the algorithm name
version The version to remove. -1 indicates all instances
typedLoaders A map of names to version numbers
Definition at line 220 of file FileLoaderRegistry.cpp.
References name.
Referenced by unsubscribe().
size()
size_t Mantid::API::FileLoaderRegistryImpl::size () const inline
Returns
the number of entries in the registry
Definition at line 49 of file FileLoaderRegistry.h.
subscribe()
template<typename Type > void Mantid::API::FileLoaderRegistryImpl::subscribe (LoaderFormat format) inline
Registers a loader whose format is one of the known formats given in LoaderFormat.
It also passes this registration on to the AlgorithmFactory so that it can be created. The template type should be the class being registered. The name is taken from the string returned by the name() method on the object.
Parameters
format The type of loader being subscribed, see LoaderFormat
Exceptions
std::invalid_argument if an entry with this name already exists
Definition at line 62 of file FileLoaderRegistry.h.
unsubscribe()
void Mantid::API::FileLoaderRegistryImpl::unsubscribe (const std::string & name, const int version = -1)
Unsubscribe a named algorithm and version from the loader registration.
If the name does not exist then it does nothing.
Parameters
name Name of the algorithm to remove from the search list
version An optional version to remove. -1 indicates remove all (Default=-1)
Definition at line 99 of file FileLoaderRegistry.cpp.
References m_names, name, and removeAlgorithm().
Friends And Related Symbol Documentation
Mantid::Kernel::CreateUsingNew< FileLoaderRegistryImpl >
friend struct Mantid::Kernel::CreateUsingNew< FileLoaderRegistryImpl > friend
Friend so that CreateUsingNew.
Definition at line 77 of file FileLoaderRegistry.h.
Member Data Documentation
m_log
Kernel::Logger Mantid::API::FileLoaderRegistryImpl::m_log mutable private
Reference to a logger.
Definition at line 129 of file FileLoaderRegistry.h.
Referenced by canLoad(), and chooseLoader().
m_names
std::array<std::multimap<std::string, int>, 3> Mantid::API::FileLoaderRegistryImpl::m_names private
The list of names.
The index pointed to by LoaderFormat defines a set for that format. The length is equal to the length of the LoaderFormat enum
Definition at line 124 of file FileLoaderRegistry.h.
Referenced by canLoad(), chooseLoader(), and unsubscribe().
m_totalSize
size_t Mantid::API::FileLoaderRegistryImpl::m_totalSize private
Total number of names registered.
Definition at line 126 of file FileLoaderRegistry.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/FileLoaderRegistry.h
Framework/API/src/FileLoaderRegistry.cpp