Mantid: Mantid::Geometry::UnitCell Class Reference
Mantid::Geometry::UnitCell Class Reference
Class to implement unit cell of crystals.
#include <Geometry/Crystal/UnitCell.h>
Public Member Functions
double a () const
Get lattice parameter.
double a (int nd) const
Get lattice parameter a1-a3 as function of index (0-2)
double a1 () const
Get lattice parameter.
double a2 () const
Get lattice parameter.
double a3 () const
Get lattice parameter.
double alpha () const
Get lattice parameter.
double alpha1 () const
Get lattice parameter.
double alpha2 () const
Get lattice parameter.
double alpha3 () const
Get lattice parameter.
double alphastar () const
Get reciprocal lattice parameter.
double astar () const
Get reciprocal lattice parameter.
double b () const
Get lattice parameter.
double b1 () const
Get reciprocal lattice parameter.
double b2 () const
Get reciprocal lattice parameter.
double b3 () const
Get reciprocal lattice parameter.
double beta () const
Get lattice parameter.
double beta1 () const
Get reciprocal lattice parameter.
double beta2 () const
Get reciprocal lattice parameter.
double beta3 () const
Get reciprocal lattice parameter.
double betastar () const
Get reciprocal lattice parameter.
double bstar () const
Get reciprocal lattice parameter.
double c () const
Get lattice parameter.
double cstar () const
Get reciprocal lattice parameter.
double d (const Kernel::V3D &hkl) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double d (double h, double k, double l) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
double dstar (const Kernel::V3D &hkl) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double dstar (double h, double k, double l) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
double errora () const
Get lattice parameter error.
double erroralpha (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorb () const
Get lattice parameter error.
double errorbeta (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorc () const
Get lattice parameter error.
double errorgamma (const int angleunit=angDegrees) const
Get lattice parameter error.
double errorvolume () const
Get lattice parameter error.
double gamma () const
Get lattice parameter.
double gammastar () const
Get reciprocal lattice parameter.
const Kernel::DblMatrix & getB () const
Get the B-matrix.
const Kernel::DblMatrix & getBinv () const
Get the inverse of the B-matrix.
bool getCrossTerm () const
Get cross term boolean.
double getdh (int j) const
Get modulation vectors for satellites.
double getdherr (int j) const
Get error of modulation vectors for satellites.
double getdk (int j) const
Get modulation vectors for satellites.
double getdkerr (int j) const
Get error of modulation vectors for satellites.
double getdl (int j) const
Get modulation vectors for satellites.
double getdlerr (int j) const
Get error of modulation vectors for satellites.
const Kernel::DblMatrix & getG () const
Get the metric tensor.
const Kernel::DblMatrix & getGstar () const
Get the reciprocal metric tensor.
int getMaxOrder () const
Get max order.
const Kernel::DblMatrix & getModHKL () const
Get modulation vectors for satellites.
const Kernel::V3D getModVec (int j) const
Get modulation vectors for satellites.
const Kernel::V3D getVecErr (int j) const
Get errors for modulation vectors for satellites.
bool operator!= (const UnitCell &other) const
bool operator== (const UnitCell &other) const
virtual void recalculateFromGstar (const Kernel::Matrix< double > &NewGstar)
Recalculate lattice from reciprocal metric tensor (Gstar=transpose(UB)*UB)
double recAngle (double h1, double k1, double l1, double h2, double k2, double l2, const int angleunit=angDegrees) const
Calculate the angle in degrees or radians between two reciprocal vectors (h1,k1,l1) and (h2,k2,l2)
double recVolume () const
Volume of the reciprocal lattice.
void set (double _a, double _b, double _c, double _alpha, double _beta, double _gamma, const int angleunit=angDegrees)
Set lattice parameters.
void seta (double _a)
Set lattice parameter.
void setalpha (double _alpha, const int angleunit=angDegrees)
Set lattice parameter.
void setb (double _b)
Set lattice parameter.
void setbeta (double _beta, const int angleunit=angDegrees)
Set lattice parameter.
void setc (double _c)
Set lattice parameter.
void setCrossTerm (bool CT)
Set modulation vectors for satellites.
void setError (double _aerr, double _berr, double _cerr, double _alphaerr, double _betaerr, double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter errors.
void setErrora (double _aerr)
Set lattice parameter error.
void setErroralpha (double _alphaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorb (double _berr)
Set lattice parameter error.
void setErrorbeta (double _betaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorc (double _cerr)
Set lattice parameter error.
void setErrorgamma (double _gammaerr, const int angleunit=angDegrees)
Set lattice parameter error.
void setErrorModHKL (const Kernel::DblMatrix &newErrorModHKL)
Set modulation vectors for satellites.
void setErrorModHKL (double _dh1err, double _dk1err, double _dl1err, double _dh2err, double _dk2err, double _dl2err, double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setgamma (double _gamma, const int angleunit=angDegrees)
Set lattice parameter.
void setMaxOrder (int MaxO)
Set modulation vectors for satellites.
void setModerr (int i, double _dherr, double _dkerr, double _dlerr)
Set modulation vectors for satellites.
void setModerr1 (double _dh1err, double _dk1err, double _dl1err)
Set modulation vectors for satellites.
void setModerr2 (double _dh2err, double _dk2err, double _dl2err)
Set modulation vectors for satellites.
void setModerr3 (double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
void setModHKL (const Kernel::DblMatrix &newModHKL)
Set modulation vectors for satellites.
void setModHKL (double _dh1, double _dk1, double _dl1, double _dh2, double _dk2, double _dl2, double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
void setModVec1 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec1 (double _dh1, double _dk1, double _dl1)
Set modulation vectors for satellites.
void setModVec2 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec2 (double _dh2, double _dk2, double _dl2)
Set modulation vectors for satellites.
void setModVec3 (const Kernel::V3D &newModVec)
Set modulation vectors for satellites.
void setModVec3 (double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
UnitCell ()
Default constructor.
UnitCell (const double _a, const double _b, const double _c)
Constructor.
UnitCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const int angleunit=angDegrees)
Constructor.
double volume () const
Volume of the direct unit-cell.
virtual ~UnitCell ()=default
Protected Member Functions
void calculateB ()
Private function to calculate B matrix.
void calculateG ()
void calculateGstar ()
Private function to calculate Gstar matrix.
void calculateReciprocalLattice ()
Private function to calculate reciprocal lattice parameters.
virtual void recalculate ()
Private function, called at initialization or whenever lattice parameters are changed.
Protected Attributes
Kernel::DblMatrix B
B matrix for a right-handed coordinate system, in Busing-Levy convention.
Kernel::DblMatrix Binv
Inverse of the B matrix.
bool CrossTerm
std::vector< double > da
Lattice parameter a,b,c,alpha,beta,gamma (in \(\mbox{ \AA } \) and radians)
std::vector< double > errorda
Error in lattice parameters (in \(\mbox{ \AA } \) and radians)
Kernel::DblMatrix errorModHKL
Kernel::DblMatrix G
Metric tensor.
Kernel::DblMatrix Gstar
Reciprocal lattice tensor.
int MaxOrder
Kernel::DblMatrix ModHKL
std::vector< double > ra
Reciprocal lattice parameters (in \(\mbox{ \AA }^{-1} \) and radians)
Detailed Description
Class to implement unit cell of crystals.
It is based on code by Laurent Chapon. It does not contain information about lattice orientation. See documentation about UB matrix in the Mantid repository.
For documentation purposes, units for lengths are assumed to be \(\mbox{ \AA } \), and for reciprocal lattice lengths \(\mbox{ \AA }^{-1} \), but can be anything, as long as used consistently. Note that the convention used for reciprocal lattice follows the one in International Tables for Crystallography, meaning that for an orthogonal lattice \(a^{*} = 1/a \) , not \(a^{*} = 2 \pi /a \)
References:
International Tables for Crystallography (2006). Vol. B, ch. 1.1, pp. 2-9
W. R. Busing and H. A. Levy, Angle calculations for 3- and 4-circle X-ray and neutron diffractometers - Acta Cryst. (1967). 22, 457-464
Author
Andrei Savici, SNS, ORNL
Date
2011-03-23
Definition at line 44 of file UnitCell.h.
Constructor & Destructor Documentation
UnitCell() [1/3]
Mantid::Geometry::UnitCell::UnitCell ()
Default constructor.
\(a = b = c = 1 \mbox{\AA, } \alpha = \beta = \gamma = 90^\circ \)
Definition at line 26 of file UnitCell.cpp.
References CrossTerm, da, errorda, MaxOrder, and recalculate().
Referenced by errorvolume().
UnitCell() [2/3]
Mantid::Geometry::UnitCell::UnitCell (const double _a, const double _b, const double _c)
Constructor.
Parameters
_a,_b,_c :: lattice parameters \(a, b, c \)
with \(\alpha = \beta = \gamma = 90^\circ \)
Definition at line 38 of file UnitCell.cpp.
References CrossTerm, da, errorda, MaxOrder, and recalculate().
UnitCell() [3/3]
Mantid::Geometry::UnitCell::UnitCell (const double _a, const double _b, const double _c, const double _alpha, const double _beta, const double _gamma, const int angleunit = angDegrees)
Constructor.
Parameters
_a,_b,_c,_alpha,_beta,_gamma :: lattice parameters
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 55 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, CrossTerm, da, Mantid::Geometry::deg2rad, errorda, MaxOrder, and recalculate().
~UnitCell()
virtual Mantid::Geometry::UnitCell::~UnitCell () virtual default
References Mantid::Geometry::d.
Member Function Documentation
a() [1/2]
double Mantid::Geometry::UnitCell::a () const
Get lattice parameter.
Returns
a :: lattice parameter \(a \) (in \(\mbox{\AA} \))
See also
a1()
Definition at line 118 of file UnitCell.cpp.
References da.
Referenced by errorvolume(), export_UnitCell(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), and Mantid::Geometry::OrientedLattice::saveNexus().
a() [2/2]
double Mantid::Geometry::UnitCell::a (int nd) const
Get lattice parameter a1-a3 as function of index (0-2)
Returns
a_n :: lattice parameter \(a,b or c \) (in \(\mbox{\AA} \))
Definition at line 94 of file UnitCell.cpp.
References da.
Referenced by Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::MDNorm::getBinParameters(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::HKLFilterDRange::HKLFilterDRange(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
a1()
double Mantid::Geometry::UnitCell::a1 () const
Get lattice parameter.
Returns
a1 :: lattice parameter \(a \) (in \(\mbox{\AA} \))
See also
a()
Definition at line 79 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
a2()
double Mantid::Geometry::UnitCell::a2 () const
Get lattice parameter.
Returns
a2 :: lattice parameter \(b \) (in \(\mbox{\AA} \))
See also
b()
Definition at line 84 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
a3()
double Mantid::Geometry::UnitCell::a3 () const
Get lattice parameter.
Returns
a3 :: lattice parameter \(c \) (in \(\mbox{\AA} \))
See also
c()
Definition at line 90 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
alpha()
double Mantid::Geometry::UnitCell::alpha () const
Get lattice parameter.
Returns
alpha :: lattice parameter \(\alpha \) (in degrees)
See also
alpha1()
Definition at line 133 of file UnitCell.cpp.
References da, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), export_UnitCell(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::NiggliCell::HasNiggliAngles(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::OrientedLattice::saveNexus(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
alpha1()
double Mantid::Geometry::UnitCell::alpha1 () const
Get lattice parameter.
Returns
alpha1 :: lattice parameter \(\alpha \) (in radians)
See also
alpha()
Definition at line 103 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
alpha2()
double Mantid::Geometry::UnitCell::alpha2 () const
Get lattice parameter.
Returns
alpha2 :: lattice parameter \(\beta \) (in radians)
See also
beta()
Definition at line 108 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
alpha3()
double Mantid::Geometry::UnitCell::alpha3 () const
Get lattice parameter.
Returns
alpha3 :: lattice parameter \(\gamma \) (in radians)
See also
gamma()
Definition at line 113 of file UnitCell.cpp.
References da.
Referenced by export_UnitCell().
alphastar()
double Mantid::Geometry::UnitCell::alphastar () const
Get reciprocal lattice parameter.
Returns
alphastar :: lattice parameter \(\alpha^{*} \) (in degrees)
See also
beta1()
Definition at line 193 of file UnitCell.cpp.
References ra, and Mantid::Geometry::rad2deg.
Referenced by export_UnitCell().
astar()
double Mantid::Geometry::UnitCell::astar () const
Get reciprocal lattice parameter.
Returns
astar :: lattice parameter \(a^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
b1()
Definition at line 178 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
b()
double Mantid::Geometry::UnitCell::b () const
Get lattice parameter.
Returns
b :: lattice parameter \(b \) (in \(\mbox{\AA} \))
See also
a2()
Definition at line 123 of file UnitCell.cpp.
References da.
Referenced by errorvolume(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), export_UnitCell(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::MDNorm::getBinParameters(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::HKLFilterDRange::HKLFilterDRange(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::OrientedLattice::saveNexus(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
b1()
double Mantid::Geometry::UnitCell::b1 () const
Get reciprocal lattice parameter.
Returns
b1 :: lattice parameter \(a^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
astar()
Definition at line 148 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
b2()
double Mantid::Geometry::UnitCell::b2 () const
Get reciprocal lattice parameter.
Returns
b2 :: lattice parameter \(b^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
bstar()
Definition at line 153 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
b3()
double Mantid::Geometry::UnitCell::b3 () const
Get reciprocal lattice parameter.
Returns
b3 :: lattice parameter \(c^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
cstar()
Definition at line 158 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
beta()
double Mantid::Geometry::UnitCell::beta () const
Get lattice parameter.
Returns
beta :: lattice parameter \(\beta \) (in degrees)
See also
alpha2()
Definition at line 138 of file UnitCell.cpp.
References da, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), export_UnitCell(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::NiggliCell::HasNiggliAngles(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::OrientedLattice::saveNexus(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
beta1()
double Mantid::Geometry::UnitCell::beta1 () const
Get reciprocal lattice parameter.
Returns
beta1 :: lattice parameter \(\alpha^{*} \) (in radians)
See also
alphastar()
Definition at line 163 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
beta2()
double Mantid::Geometry::UnitCell::beta2 () const
Get reciprocal lattice parameter.
Returns
beta2 :: lattice parameter \(\beta^{*} \) (in radians)
See also
betastar()
Definition at line 168 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
beta3()
double Mantid::Geometry::UnitCell::beta3 () const
Get reciprocal lattice parameter.
Returns
beta3 :: lattice parameter \(\gamma^{*} \) (in radians)
See also
gammastar()
Definition at line 173 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
betastar()
double Mantid::Geometry::UnitCell::betastar () const
Get reciprocal lattice parameter.
Returns
betastar:: lattice parameter \(\beta^{*} \) (in degrees)
See also
beta2()
Definition at line 198 of file UnitCell.cpp.
References ra, and Mantid::Geometry::rad2deg.
Referenced by export_UnitCell().
bstar()
double Mantid::Geometry::UnitCell::bstar () const
Get reciprocal lattice parameter.
Returns
bstar :: lattice parameter \(b^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
b2()
Definition at line 183 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
c()
double Mantid::Geometry::UnitCell::c () const
Get lattice parameter.
Returns
c :: lattice parameter \(c \) (in \(\mbox{\AA} \))
See also
a3()
Definition at line 128 of file UnitCell.cpp.
References da.
Referenced by errorvolume(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), export_UnitCell(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::MDNorm::getBinParameters(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::HKLFilterDRange::HKLFilterDRange(), Mantid::Geometry::NiggliCell::MakeNiggliUB(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::OrientedLattice::saveNexus(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
calculateB()
void Mantid::Geometry::UnitCell::calculateB () protected
Private function to calculate B matrix.
Now let's cache the inverse B
Definition at line 813 of file UnitCell.cpp.
References B, Binv, da, Mantid::Kernel::Matrix< T >::Invert(), and ra.
Referenced by recalculate(), and recalculateFromGstar().
calculateG()
void Mantid::Geometry::UnitCell::calculateG () protected
Definition at line 776 of file UnitCell.cpp.
References da, and G.
Referenced by recalculate().
calculateGstar()
void Mantid::Geometry::UnitCell::calculateGstar () protected
Private function to calculate Gstar matrix.
Definition at line 789 of file UnitCell.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), G, Gstar, and Mantid::Kernel::Matrix< T >::Invert().
Referenced by recalculate().
calculateReciprocalLattice()
void Mantid::Geometry::UnitCell::calculateReciprocalLattice () protected
Private function to calculate reciprocal lattice parameters.
Definition at line 802 of file UnitCell.cpp.
References Gstar, ra, and Mantid::Geometry::x.
Referenced by recalculate(), and recalculateFromGstar().
cstar()
double Mantid::Geometry::UnitCell::cstar () const
Get reciprocal lattice parameter.
Returns
cstar :: lattice parameter \(c^{*} \) (in \(\mbox{\AA}^{-1} \))
See also
b3()
Definition at line 188 of file UnitCell.cpp.
References ra.
Referenced by export_UnitCell().
d() [1/2]
double Mantid::Geometry::UnitCell::d (const Kernel::V3D & hkl) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
Definition at line 703 of file UnitCell.cpp.
References dstar().
d() [2/2]
double Mantid::Geometry::UnitCell::d (double h, double k, double l) const
Return d-spacing (\(\mbox{ \AA } \)) for a given h,k,l coordinate.
Definition at line 700 of file UnitCell.cpp.
References dstar().
Referenced by Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::Crystal::IndexSXPeaks::exec(), export_UnitCell(), Mantid::CurveFitting::LatticeFunction::functionLattice(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::Crystal::SortHKL::getDLimits(), Mantid::Geometry::LatticeSpacingCalculator::operator()(), and Mantid::CurveFitting::Functions::PawleyFunction::setPeakPositions().
dstar() [1/2]
double Mantid::Geometry::UnitCell::dstar (const Kernel::V3D & hkl) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
Definition at line 711 of file UnitCell.cpp.
References B.
dstar() [2/2]
double Mantid::Geometry::UnitCell::dstar (double h, double k, double l) const
Return d*=1/d (\(\mbox{ \AA }^{-1} \)) for a given h,k,l coordinate.
Definition at line 706 of file UnitCell.cpp.
References dstar().
Referenced by d(), d(), dstar(), export_UnitCell(), and recAngle().
errora()
double Mantid::Geometry::UnitCell::errora () const
Get lattice parameter error.
Returns
errora :: errorlattice parameter \(a \) (in \(\mbox{\AA} \))
Definition at line 208 of file UnitCell.cpp.
References errorda.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
erroralpha()
double Mantid::Geometry::UnitCell::erroralpha (const int angleunit = angDegrees) const
Get lattice parameter error.
Parameters
angleunit :: units for angle, of type AngleUnits . Default is degrees.
Returns
erroralpha :: errorlattice parameter \(alpha \) (in degrees or radians)
Definition at line 225 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, errorda, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
errorb()
double Mantid::Geometry::UnitCell::errorb () const
Get lattice parameter error.
Returns
errorb :: errorlattice parameter \(b \) (in \(\mbox{\AA} \))
Definition at line 213 of file UnitCell.cpp.
References errorda.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
errorbeta()
double Mantid::Geometry::UnitCell::errorbeta (const int angleunit = angDegrees) const
Get lattice parameter error.
Parameters
angleunit :: units for angle, of type AngleUnits . Default is degrees.
Returns
erroralpha :: errorlattice parameter \(beta \) (in degrees or radians)
Definition at line 239 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, errorda, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
errorc()
double Mantid::Geometry::UnitCell::errorc () const
Get lattice parameter error.
Returns
errorc :: errorlattice parameter \(c \) (in \(\mbox{\AA} \))
Definition at line 218 of file UnitCell.cpp.
References errorda.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
errorgamma()
double Mantid::Geometry::UnitCell::errorgamma (const int angleunit = angDegrees) const
Get lattice parameter error.
Parameters
angleunit :: units for angle, of type AngleUnits . Default is degrees.
Returns
erroralpha :: errorlattice parameter \(gamma \) (in degrees or radians)
Definition at line 252 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, errorda, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::operator<<(), and Mantid::Geometry::OrientedLattice::saveNexus().
errorvolume()
double Mantid::Geometry::UnitCell::errorvolume () const
Get lattice parameter error.
Returns
errorc :: errorlattice parameter \(volume \) (in \(\mbox{\AA} \))
Definition at line 264 of file UnitCell.cpp.
References a(), alpha(), b(), beta(), c(), errora(), erroralpha(), errorb(), errorbeta(), errorc(), errorgamma(), gamma(), UnitCell(), and volume().
Referenced by Mantid::Geometry::operator<<().
gamma()
double Mantid::Geometry::UnitCell::gamma () const
Get lattice parameter.
Returns
gamma :: lattice parameter \(\gamma \) (in degrees)
See also
alpha3()
Definition at line 143 of file UnitCell.cpp.
References da, and Mantid::Geometry::rad2deg.
Referenced by errorvolume(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawUB::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), export_UnitCell(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::NiggliCell::HasNiggliAngles(), Mantid::Geometry::operator<<(), Mantid::Crystal::SCDCalibratePanels2::parseLatticeConstant(), Mantid::Geometry::OrientedLattice::saveNexus(), Mantid::Geometry::IndexingUtils::ScanFor_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::setParametersFromUnitCell(), Mantid::API::ExperimentInfo::toString(), and Mantid::Geometry::unitCellToStr().
gammastar()
double Mantid::Geometry::UnitCell::gammastar () const
Get reciprocal lattice parameter.
Returns
gammastar:: lattice parameter \(\gamma^{*} \) (in degrees)
See also
beta3()
Definition at line 203 of file UnitCell.cpp.
References ra, and Mantid::Geometry::rad2deg.
Referenced by export_UnitCell().
getB()
const Kernel::DblMatrix & Mantid::Geometry::UnitCell::getB () const
Get the B-matrix.
Returns
B :: B matrix in Busing-Levy convention
Definition at line 758 of file UnitCell.cpp.
References B.
Referenced by export_UnitCell(), Mantid::Geometry::IsotropicAtomBraggScatterer::getDebyeWallerFactor(), Mantid::Geometry::NiggliCell::NiggliCell(), Mantid::Geometry::NiggliCell::NiggliCell(), Mantid::Geometry::NiggliCell::NiggliCell(), Mantid::Geometry::NiggliCell::NiggliCell(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::recalculate(), Mantid::Geometry::OrientedLattice::setU(), Mantid::Geometry::OrientedLattice::setUB(), and Mantid::Geometry::OrientedLattice::setUFromVectors().
getBinv()
const Kernel::DblMatrix & Mantid::Geometry::UnitCell::getBinv () const
Get the inverse of the B-matrix.
Returns
Binv :: inverse of the B matrix in Busing-Levy convention
Definition at line 762 of file UnitCell.cpp.
References Binv.
Referenced by Mantid::MDAlgorithms::LoadSQW2::cacheFrameTransforms(), and export_UnitCell().
getCrossTerm()
bool Mantid::Geometry::UnitCell::getCrossTerm () const
Get cross term boolean.
Returns
CrossTerm :: if true, use cross terms
Definition at line 602 of file UnitCell.cpp.
References CrossTerm.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), and Mantid::Geometry::OrientedLattice::saveNexus().
getdh()
double Mantid::Geometry::UnitCell::getdh (int j) const
Get modulation vectors for satellites.
Parameters
j index of vector to get
Returns
dh :: dh of modulation vector
Definition at line 555 of file UnitCell.cpp.
References ModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and getModVec().
getdherr()
double Mantid::Geometry::UnitCell::getdherr (int j) const
Get error of modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVecErr :: error of modulation vector
Definition at line 576 of file UnitCell.cpp.
References errorModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), and getVecErr().
getdk()
double Mantid::Geometry::UnitCell::getdk (int j) const
Get modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVec :: modulation vector
Definition at line 562 of file UnitCell.cpp.
References ModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and getModVec().
getdkerr()
double Mantid::Geometry::UnitCell::getdkerr (int j) const
Get error of modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVecErr :: error of modulation vector
Definition at line 583 of file UnitCell.cpp.
References errorModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), and getVecErr().
getdl()
double Mantid::Geometry::UnitCell::getdl (int j) const
Get modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVec :: modulation vector
Definition at line 569 of file UnitCell.cpp.
References ModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and getModVec().
getdlerr()
double Mantid::Geometry::UnitCell::getdlerr (int j) const
Get error of modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVecErr :: error of modulation vector
Definition at line 590 of file UnitCell.cpp.
References errorModHKL.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), and getVecErr().
getG()
const Kernel::DblMatrix & Mantid::Geometry::UnitCell::getG () const
Get the metric tensor.
Returns
G :: metric tensor
Definition at line 750 of file UnitCell.cpp.
References G.
Referenced by export_UnitCell(), and Mantid::Geometry::SpaceGroup::isAllowedUnitCell().
getGstar()
const Kernel::DblMatrix & Mantid::Geometry::UnitCell::getGstar () const
Get the reciprocal metric tensor.
Returns
Gstar :: metric tensor of the reciprocal lattice
Definition at line 754 of file UnitCell.cpp.
References Gstar.
Referenced by export_UnitCell().
getMaxOrder()
int Mantid::Geometry::UnitCell::getMaxOrder () const
Get max order.
Returns
MaxOrder :: maximum order
Definition at line 596 of file UnitCell.cpp.
References MaxOrder.
Referenced by Mantid::Crystal::SaveIsawUB::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), export_UnitCell(), and Mantid::Geometry::OrientedLattice::saveNexus().
getModHKL()
const Kernel::DblMatrix & Mantid::Geometry::UnitCell::getModHKL () const
Get modulation vectors for satellites.
Returns
ModHKL :: modulation vectors
Definition at line 548 of file UnitCell.cpp.
References ModHKL.
Referenced by Mantid::Crystal::TransformHKL::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), export_UnitCell(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), Mantid::Geometry::OrientedLattice::OrientedLattice(), and Mantid::Geometry::OrientedLattice::setU().
getModVec()
const Kernel::V3D Mantid::Geometry::UnitCell::getModVec (int j) const
Get modulation vectors for satellites.
Parameters
j index of vector to get
Returns
ModVec :: modulation vector
Definition at line 535 of file UnitCell.cpp.
References getdh(), getdk(), and getdl().
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Geometry::IndexingUtils::GetModulationVector(), Mantid::Geometry::IndexingUtils::GetModulationVectors(), and Mantid::Crystal::FindUBUsingIndexedPeaks::logLattice().
getVecErr()
const Kernel::V3D Mantid::Geometry::UnitCell::getVecErr (int j) const
Get errors for modulation vectors for satellites.
Parameters
j index of vector to get
Returns
VecErr :: error of modulation vector
Definition at line 542 of file UnitCell.cpp.
References getdherr(), getdkerr(), and getdlerr().
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::logLattice().
operator!=()
bool Mantid::Geometry::UnitCell::operator!= (const UnitCell & other) const
Definition at line 863 of file UnitCell.cpp.
References operator==().
operator==()
bool Mantid::Geometry::UnitCell::operator== (const UnitCell & other) const
Definition at line 860 of file UnitCell.cpp.
References da.
Referenced by operator!=().
recalculate()
void Mantid::Geometry::UnitCell::recalculate () protected virtual
Private function, called at initialization or whenever lattice parameters are changed.
Reimplemented in Mantid::Geometry::OrientedLattice.
Definition at line 766 of file UnitCell.cpp.
References calculateB(), calculateG(), calculateGstar(), calculateReciprocalLattice(), and da.
Referenced by Mantid::Geometry::OrientedLattice::recalculate(), set(), seta(), setalpha(), setb(), setbeta(), setc(), setgamma(), UnitCell(), UnitCell(), and UnitCell().
recalculateFromGstar()
void Mantid::Geometry::UnitCell::recalculateFromGstar (const Kernel::Matrix< double > & NewGstar) virtual
Recalculate lattice from reciprocal metric tensor (Gstar=transpose(UB)*UB)
Reimplemented in Mantid::Geometry::OrientedLattice.
Definition at line 836 of file UnitCell.cpp.
References calculateB(), calculateReciprocalLattice(), da, G, Gstar, Mantid::Kernel::Matrix< T >::Invert(), Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
recAngle()
double Mantid::Geometry::UnitCell::recAngle (double h1, double k1, double l1, double h2, double k2, double l2, const int angleunit = angDegrees) const
Calculate the angle in degrees or radians between two reciprocal vectors (h1,k1,l1) and (h2,k2,l2)
Definition at line 718 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, dstar(), Gstar, Mantid::Kernel::l2, and Mantid::Geometry::rad2deg.
Referenced by Mantid::Crystal::PeakCandidate::clean(), and export_UnitCell().
recVolume()
double Mantid::Geometry::UnitCell::recVolume () const
Volume of the reciprocal lattice.
Definition at line 743 of file UnitCell.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), and Gstar.
Referenced by export_UnitCell().
set()
void Mantid::Geometry::UnitCell::set (double _a, double _b, double _c, double _alpha, double _beta, double _gamma, const int angleunit = angDegrees)
Set lattice parameters.
Parameters
_a,_b,_c,_alpha,_beta,_gamma :: lattice parameters
angleunit :: units for angle, of type AngleUnits . Default is degrees.
Definition at line 303 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, da, Mantid::Geometry::deg2rad, and recalculate().
Referenced by Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), and export_UnitCell().
seta()
void Mantid::Geometry::UnitCell::seta (double _a)
Set lattice parameter.
Parameters
_a :: lattice parameter \(a \) (in \(\mbox{\AA} \))
Definition at line 606 of file UnitCell.cpp.
References da, and recalculate().
Referenced by export_UnitCell().
setalpha()
void Mantid::Geometry::UnitCell::setalpha (double _alpha, const int angleunit = angDegrees)
Set lattice parameter.
Parameters
_alpha :: lattice parameter \(\alpha \)
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 636 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, da, Mantid::Geometry::deg2rad, and recalculate().
Referenced by export_UnitCell().
setb()
void Mantid::Geometry::UnitCell::setb (double _b)
Set lattice parameter.
Parameters
_b :: lattice parameter \(b \) (in \(\mbox{\AA} \))
Definition at line 616 of file UnitCell.cpp.
References da, and recalculate().
Referenced by export_UnitCell().
setbeta()
void Mantid::Geometry::UnitCell::setbeta (double _beta, const int angleunit = angDegrees)
Set lattice parameter.
Parameters
_beta :: lattice parameter \(\beta \)
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 657 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, da, Mantid::Geometry::deg2rad, and recalculate().
Referenced by export_UnitCell().
setc()
void Mantid::Geometry::UnitCell::setc (double _c)
Set lattice parameter.
Parameters
_c :: lattice parameter \(c \) (in \(\mbox{\AA} \))
Definition at line 625 of file UnitCell.cpp.
References da, and recalculate().
Referenced by export_UnitCell().
setCrossTerm()
void Mantid::Geometry::UnitCell::setCrossTerm (bool CT)
Set modulation vectors for satellites.
Parameters
CT if true, use cross terms
Definition at line 528 of file UnitCell.cpp.
References CrossTerm.
Referenced by Mantid::Geometry::OrientedLattice::loadNexus().
setError()
void Mantid::Geometry::UnitCell::setError (double _aerr, double _berr, double _cerr, double _alphaerr, double _betaerr, double _gammaerr, const int angleunit = angDegrees)
Set lattice parameter errors.
Parameters
_aerr,_berr,_cerr,_alphaerr,_betaerr,_gammaerr :: lattice parameter errors
angleunit :: units for angle, of type AngleUnits . Default is degrees.
Definition at line 325 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, Mantid::Geometry::deg2rad, and errorda.
Referenced by Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::TransformHKL::exec(), export_UnitCell(), Mantid::Geometry::IndexingUtils::Find_UB(), Mantid::CurveFitting::Functions::PawleyParameterFunction::getUnitCellFromParameters(), and Mantid::Geometry::OrientedLattice::loadNexus().
setErrora()
void Mantid::Geometry::UnitCell::setErrora (double _aerr)
Set lattice parameter error.
Parameters
_aerr :: lattice parameter \(a \) error (in \(\mbox{\AA} \))
Definition at line 612 of file UnitCell.cpp.
References errorda.
Referenced by export_UnitCell().
setErroralpha()
void Mantid::Geometry::UnitCell::setErroralpha (double _alphaerr, const int angleunit = angDegrees)
Set lattice parameter error.
Parameters
_alphaerr :: lattice parameter \(\alpha \) error
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 647 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, Mantid::Geometry::deg2rad, and errorda.
Referenced by export_UnitCell().
setErrorb()
void Mantid::Geometry::UnitCell::setErrorb (double _berr)
Set lattice parameter error.
Parameters
_berr :: lattice parameter \(b \) error (in \(\mbox{\AA} \))
Definition at line 622 of file UnitCell.cpp.
References errorda.
Referenced by export_UnitCell().
setErrorbeta()
void Mantid::Geometry::UnitCell::setErrorbeta (double _betaerr, const int angleunit = angDegrees)
Set lattice parameter error.
Parameters
_betaerr :: lattice parameter \(\beta \) error
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 669 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, Mantid::Geometry::deg2rad, and errorda.
Referenced by export_UnitCell().
setErrorc()
void Mantid::Geometry::UnitCell::setErrorc (double _cerr)
Set lattice parameter error.
Parameters
_cerr :: lattice parameter \(c \) error (in \(\mbox{\AA} \))
Definition at line 631 of file UnitCell.cpp.
References errorda.
Referenced by export_UnitCell().
setErrorgamma()
void Mantid::Geometry::UnitCell::setErrorgamma (double _gammaerr, const int angleunit = angDegrees)
Set lattice parameter error.
Parameters
_gammaerr :: lattice parameter \(\gamma \) error
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 692 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, Mantid::Geometry::deg2rad, and errorda.
Referenced by export_UnitCell().
setErrorModHKL() [1/2]
void Mantid::Geometry::UnitCell::setErrorModHKL (const Kernel::DblMatrix & newErrorModHKL)
Set modulation vectors for satellites.
Parameters
newErrorModHKL errors for modulation vectors for HKL for three vectors
Definition at line 376 of file UnitCell.cpp.
References errorModHKL.
Referenced by Mantid::Geometry::OrientedLattice::loadNexus().
setErrorModHKL() [2/2]
void Mantid::Geometry::UnitCell::setErrorModHKL (double _dh1err, double _dk1err, double _dl1err, double _dh2err, double _dk2err, double _dl2err, double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
Parameters
_dh1err error for offset for H for first vector
_dk1err error for offset for K for first vector
_dl1err error for offset for l for first vector
_dh2err error for offset for H for second vector
_dk2err error for offset for K for second vector
_dl2err error for offset for l for second vector
_dh3err error for offset for H for third vector
_dk3err error for offset for K for third vector
_dl3err error for offset for l for third vector
Definition at line 390 of file UnitCell.cpp.
References errorModHKL.
setgamma()
void Mantid::Geometry::UnitCell::setgamma (double _gamma, const int angleunit = angDegrees)
Set lattice parameter.
Parameters
_gamma :: lattice parameter \(\gamma \)
angleunit :: units for angle, of type AngleUnits. Default is degrees.
Definition at line 680 of file UnitCell.cpp.
References Mantid::Geometry::angDegrees, da, Mantid::Geometry::deg2rad, and recalculate().
Referenced by export_UnitCell().
setMaxOrder()
void Mantid::Geometry::UnitCell::setMaxOrder (int MaxO)
Set modulation vectors for satellites.
Parameters
MaxO maximum order of modulation vectors
Definition at line 522 of file UnitCell.cpp.
References MaxOrder.
Referenced by export_UnitCell(), and Mantid::Geometry::OrientedLattice::loadNexus().
setModerr()
void Mantid::Geometry::UnitCell::setModerr (int i, double _dherr, double _dkerr, double _dlerr)
Set modulation vectors for satellites.
Parameters
i index of vector to set
_dherr error for offset for H for ith vector
_dkerr error for offset for K for ith vector
_dlerr error for offset for l for ith vector
Definition at line 476 of file UnitCell.cpp.
References errorModHKL.
setModerr1()
void Mantid::Geometry::UnitCell::setModerr1 (double _dh1err, double _dk1err, double _dl1err)
Set modulation vectors for satellites.
Parameters
_dh1err error for offset for H for first vector
_dk1err error for offset for K for first vector
_dl1err error for offset for l for first vector
Definition at line 488 of file UnitCell.cpp.
References errorModHKL.
setModerr2()
void Mantid::Geometry::UnitCell::setModerr2 (double _dh2err, double _dk2err, double _dl2err)
Set modulation vectors for satellites.
Parameters
_dh2err error for offset for H for second vector
_dk2err error for offset for K for second vector
_dl2err error for offset for l for second vector
Definition at line 500 of file UnitCell.cpp.
References errorModHKL.
setModerr3()
void Mantid::Geometry::UnitCell::setModerr3 (double _dh3err, double _dk3err, double _dl3err)
Set modulation vectors for satellites.
Parameters
_dh3err error for offset for H for third vector
_dk3err error for offset for K for third vector
_dl3err error for offset for l for third vector
Definition at line 512 of file UnitCell.cpp.
References errorModHKL.
setModHKL() [1/2]
void Mantid::Geometry::UnitCell::setModHKL (const Kernel::DblMatrix & newModHKL)
Set modulation vectors for satellites.
Parameters
newModHKL modulation vectors for HKL for three vectors
Definition at line 370 of file UnitCell.cpp.
References ModHKL.
setModHKL() [2/2]
void Mantid::Geometry::UnitCell::setModHKL (double _dh1, double _dk1, double _dl1, double _dh2, double _dk2, double _dl2, double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
Parameters
_dh1 offset for H for first vector
_dk1 offset for K for first vector
_dl1 offset for l for first vector
_dh2 offset for H for second vector
_dk2 offset for K for second vector
_dl2 offset for l for second vector
_dh3 offset for H for third vector
_dk3 offset for K for third vector
_dl3 offset for l for third vector
Definition at line 353 of file UnitCell.cpp.
References ModHKL.
Referenced by Mantid::Crystal::TransformHKL::exec(), and Mantid::Geometry::OrientedLattice::setModUB().
setModVec1() [1/2]
void Mantid::Geometry::UnitCell::setModVec1 (const Kernel::V3D & newModVec)
Set modulation vectors for satellites.
Parameters
newModVec modulation vectors for HKL for first vector
Definition at line 443 of file UnitCell.cpp.
References ModHKL.
setModVec1() [2/2]
void Mantid::Geometry::UnitCell::setModVec1 (double _dh1, double _dk1, double _dl1)
Set modulation vectors for satellites.
Parameters
_dh1 offset for H for first vector
_dk1 offset for K for first vector
_dl1 offset for l for first vector
Definition at line 409 of file UnitCell.cpp.
References ModHKL.
Referenced by export_UnitCell().
setModVec2() [1/2]
void Mantid::Geometry::UnitCell::setModVec2 (const Kernel::V3D & newModVec)
Set modulation vectors for satellites.
Parameters
newModVec modulation vectors for HKL for second vector
Definition at line 453 of file UnitCell.cpp.
References ModHKL.
setModVec2() [2/2]
void Mantid::Geometry::UnitCell::setModVec2 (double _dh2, double _dk2, double _dl2)
Set modulation vectors for satellites.
Parameters
_dh2 offset for H for second vector
_dk2 offset for K for second vector
_dl2 offset for l for second vector
Definition at line 421 of file UnitCell.cpp.
References ModHKL.
Referenced by export_UnitCell().
setModVec3() [1/2]
void Mantid::Geometry::UnitCell::setModVec3 (const Kernel::V3D & newModVec)
Set modulation vectors for satellites.
Parameters
newModVec modulation vectors for HKL for third vector
Definition at line 463 of file UnitCell.cpp.
References ModHKL.
setModVec3() [2/2]
void Mantid::Geometry::UnitCell::setModVec3 (double _dh3, double _dk3, double _dl3)
Set modulation vectors for satellites.
Parameters
_dh3 offset for H for third vector
_dk3 offset for K for third vector
_dl3 offset for l for third vector
Definition at line 433 of file UnitCell.cpp.
References ModHKL.
Referenced by export_UnitCell().
volume()
double Mantid::Geometry::UnitCell::volume () const
Volume of the direct unit-cell.
Definition at line 737 of file UnitCell.cpp.
References Mantid::Kernel::Matrix< T >::determinant(), G, and volume().
Referenced by errorvolume(), Mantid::Crystal::SaveIsawUB::exec(), export_UnitCell(), Mantid::Crystal::SaveIsawUB::getErrorVolume(), Mantid::Geometry::IndexingUtils::GetLatticeParameters(), Mantid::Geometry::operator<<(), and volume().
Member Data Documentation
B
Kernel::DblMatrix Mantid::Geometry::UnitCell::B protected
B matrix for a right-handed coordinate system, in Busing-Levy convention.
\[ \left(\begin{array}{ccc} a^* & b^*\cos(\gamma^*) & c^*\cos(\beta^*) \\ 0 & b^*\sin(\gamma^*) & -c^*\sin(\beta^*)\cos(\alpha) \\ 0 & 0 & 1/c \end{array} \right) \]
Definition at line 191 of file UnitCell.h.
Referenced by calculateB(), dstar(), getB(), and Mantid::Geometry::OrientedLattice::setUB().
Binv
Kernel::DblMatrix Mantid::Geometry::UnitCell::Binv protected
Inverse of the B matrix.
Definition at line 195 of file UnitCell.h.
Referenced by calculateB(), and getBinv().
CrossTerm
bool Mantid::Geometry::UnitCell::CrossTerm protected
Definition at line 203 of file UnitCell.h.
Referenced by getCrossTerm(), setCrossTerm(), UnitCell(), UnitCell(), and UnitCell().
da
std::vector<double> Mantid::Geometry::UnitCell::da protected
Lattice parameter a,b,c,alpha,beta,gamma (in \(\mbox{ \AA } \) and radians)
Definition at line 166 of file UnitCell.h.
Referenced by a(), a(), a1(), a2(), a3(), alpha(), alpha1(), alpha2(), alpha3(), b(), beta(), c(), calculateB(), calculateG(), gamma(), operator==(), recalculate(), recalculateFromGstar(), set(), seta(), setalpha(), setb(), setbeta(), setc(), setgamma(), UnitCell(), UnitCell(), and UnitCell().
errorda
std::vector<double> Mantid::Geometry::UnitCell::errorda protected
Error in lattice parameters (in \(\mbox{ \AA } \) and radians)
Definition at line 170 of file UnitCell.h.
Referenced by errora(), erroralpha(), errorb(), errorbeta(), errorc(), errorgamma(), setError(), setErrora(), setErroralpha(), setErrorb(), setErrorbeta(), setErrorc(), setErrorgamma(), UnitCell(), UnitCell(), and UnitCell().
errorModHKL
Kernel::DblMatrix Mantid::Geometry::UnitCell::errorModHKL protected
Definition at line 199 of file UnitCell.h.
Referenced by getdherr(), getdkerr(), getdlerr(), Mantid::Geometry::OrientedLattice::loadNexus(), Mantid::Geometry::OrientedLattice::saveNexus(), setErrorModHKL(), setErrorModHKL(), setModerr(), setModerr1(), setModerr2(), and setModerr3().
G
Kernel::DblMatrix Mantid::Geometry::UnitCell::G protected
Metric tensor.
\[ \left(\begin{array}{ccc} aa & ab\cos(\gamma) & ac\cos(\beta) \\ ab\cos(\gamma) & bb & bc\cos(\alpha) \\ ac\cos(\beta) & bc\cos(\alpha) & cc \end{array} \right) \]
Definition at line 177 of file UnitCell.h.
Referenced by calculateG(), calculateGstar(), getG(), recalculateFromGstar(), and volume().
Gstar
Kernel::DblMatrix Mantid::Geometry::UnitCell::Gstar protected
Reciprocal lattice tensor.
\[ \left(\begin{array}{ccc} a^*a^* & a^*b^*\cos(\gamma^*) & a^*c^*\cos(\beta^*) \\ a^*b^*\cos(\gamma^*) & b^*b^* & b^*c^*\cos(\alpha^*) \\ a^*c^*\cos(\beta^*) & b^*c^*\cos(\alpha^*) & c^*c^* \end{array} \right) \]
Definition at line 184 of file UnitCell.h.
Referenced by calculateGstar(), calculateReciprocalLattice(), getGstar(), recalculateFromGstar(), recAngle(), and recVolume().
MaxOrder
int Mantid::Geometry::UnitCell::MaxOrder protected
Definition at line 201 of file UnitCell.h.
Referenced by getMaxOrder(), setMaxOrder(), UnitCell(), UnitCell(), and UnitCell().
ModHKL
Kernel::DblMatrix Mantid::Geometry::UnitCell::ModHKL protected
Definition at line 197 of file UnitCell.h.
Referenced by getdh(), getdk(), getdl(), getModHKL(), setModHKL(), setModHKL(), setModVec1(), setModVec1(), setModVec2(), setModVec2(), setModVec3(), and setModVec3().
ra
std::vector<double> Mantid::Geometry::UnitCell::ra protected
Reciprocal lattice parameters (in \(\mbox{ \AA }^{-1} \) and radians)
Definition at line 168 of file UnitCell.h.
Referenced by alphastar(), astar(), b1(), b2(), b3(), beta1(), beta2(), beta3(), betastar(), bstar(), calculateB(), calculateReciprocalLattice(), cstar(), and gammastar().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Crystal/UnitCell.h
Framework/Geometry/src/Crystal/UnitCell.cpp