Mantid: Mantid::DataHandling::MultiPeriodLoadMuonStrategy Class Reference
Mantid::DataHandling::MultiPeriodLoadMuonStrategy Class Reference
#include <MultiPeriodLoadMuonStrategy.h>
Public Member Functions
void applyTimeZeroCorrection () override
Performs time-zero correction on the loaded workspace.
API::Workspace_sptr getTimeZeroTable () override
Gets time zero table from loaded time zeros Assumes all periods have same time zero.
API::Workspace_sptr loadDeadTimeTable () const override
API::Workspace_sptr loadDetectorGrouping () const override
Loads detector grouping.
void loadGoodFrames () override
Loads the good frames data into each of the stored workspace objects.
void loadMuonLogData () override
Loads Muon specific logs into each of the workspaces in the workspace group.
MultiPeriodLoadMuonStrategy (Kernel::Logger &g_log, const std::string &filename, LoadMuonNexusV2NexusHelper &nexusLoader, API::WorkspaceGroup &workspaceGroup)
Public Member Functions inherited from Mantid::DataHandling::LoadMuonStrategy
LoadMuonStrategy (Kernel::Logger &g_log, std::string filename, LoadMuonNexusV2NexusHelper &nexusLoader)
virtual ~LoadMuonStrategy ()=default
Private Member Functions
std::vector< detid_t > getLoadedDetectors ()
Finds the detectors which are loaded in the stored workspace group.
Private Attributes
std::vector< detid_t > m_detectors
API::WorkspaceGroup & m_workspaceGroup
Additional Inherited Members
Protected Member Functions inherited from Mantid::DataHandling::LoadMuonStrategy
DataObjects::TableWorkspace_sptr createDeadTimeTable (const std::vector< detid_t > &detectorsLoaded, const std::vector< double > &deadTimes) const
Creates the deadtime table for the loaded detectors .
std::optional< DataObjects::TableWorkspace_sptr > createDetectorGroupingTable (const std::vector< detid_t > &specToLoad, const std::optional< std::vector< detid_t > > &grouping) const
Creates Detector Grouping Table .
std::vector< detid_t > getLoadedDetectorsFromWorkspace (const DataObjects::Workspace2D &localWorkspace) const
Determines the detectors loaded in the input workspace.
API::Workspace_sptr loadDefaultDetectorGrouping (const DataObjects::Workspace2D &localWorkspace) const
Loads default detector grouping, if this isn't present return dummy grouping.
Protected Attributes inherited from Mantid::DataHandling::LoadMuonStrategy
const std::string m_filename
Kernel::Logger & m_logger
LoadMuonNexusV2NexusHelper & m_nexusLoader
Detailed Description
Definition at line 13 of file MultiPeriodLoadMuonStrategy.h.
Constructor & Destructor Documentation
MultiPeriodLoadMuonStrategy()
Mantid::DataHandling::MultiPeriodLoadMuonStrategy::MultiPeriodLoadMuonStrategy (Kernel::Logger & g_log, const std::string & filename, LoadMuonNexusV2NexusHelper & nexusLoader, API::WorkspaceGroup & workspaceGroup)
Definition at line 27 of file MultiPeriodLoadMuonStrategy.cpp.
Member Function Documentation
applyTimeZeroCorrection()
void Mantid::DataHandling::MultiPeriodLoadMuonStrategy::applyTimeZeroCorrection () override virtual
Performs time-zero correction on the loaded workspace.
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 89 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::API::WorkspaceGroup::getItem(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroFromNexusFile(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspaceGroup, and workspace.
getLoadedDetectors()
std::vector< detid_t > Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getLoadedDetectors () private
Finds the detectors which are loaded in the stored workspace group.
Definition at line 126 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::API::WorkspaceGroup::getItem(), Mantid::DataHandling::LoadMuonStrategy::getLoadedDetectorsFromWorkspace(), m_workspaceGroup, and workspace.
getTimeZeroTable()
Workspace_sptr Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getTimeZeroTable () override virtual
Gets time zero table from loaded time zeros Assumes all periods have same time zero.
Returns
:: Time zero table
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 116 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::createTimeZeroTable(), Mantid::API::WorkspaceGroup::getItem(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroListFromNexusFile(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspaceGroup, and workspace.
loadDeadTimeTable()
API::Workspace_sptr Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDeadTimeTable () const override virtual
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 101 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonStrategy::createDeadTimeTable(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDeadTimesFromNexus(), m_detectors, Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, and m_workspaceGroup.
loadDetectorGrouping()
Workspace_sptr Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping () const override virtual
Loads detector grouping.
If no entry in NeXus file for grouping, load it from the IDF. stored
Returns
:: TableWorkspace group containing each of the grouping tables
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 69 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::DataHandling::LoadMuonStrategy::createDetectorGroupingTable(), Mantid::API::WorkspaceGroup::getItem(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), Mantid::DataHandling::LoadMuonStrategy::loadDefaultDetectorGrouping(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDetectorGroupingFromNexus(), m_detectors, Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, and m_workspaceGroup.
loadGoodFrames()
void Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadGoodFrames () override virtual
Loads the good frames data into each of the stored workspace objects.
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 53 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::API::WorkspaceGroup::getItem(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadGoodFramesDataFromNexus(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspaceGroup, and workspace.
loadMuonLogData()
void Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadMuonLogData () override virtual
Loads Muon specific logs into each of the workspaces in the workspace group.
These are logs which are not loaded by LoadISISNexus
Implements Mantid::DataHandling::LoadMuonStrategy.
Definition at line 36 of file MultiPeriodLoadMuonStrategy.cpp.
References Mantid::API::WorkspaceGroup::getItem(), Mantid::API::WorkspaceGroup::getNumberOfEntries(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadFirstGoodDataFromNexus(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadMainFieldDirectionFromNexus(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadSampleInformationFromNexus(), Mantid::DataHandling::LoadMuonStrategy::m_nexusLoader, m_workspaceGroup, and workspace.
Member Data Documentation
m_detectors
std::vector<detid_t> Mantid::DataHandling::MultiPeriodLoadMuonStrategy::m_detectors private
Definition at line 33 of file MultiPeriodLoadMuonStrategy.h.
Referenced by loadDeadTimeTable(), and loadDetectorGrouping().
m_workspaceGroup
API::WorkspaceGroup& Mantid::DataHandling::MultiPeriodLoadMuonStrategy::m_workspaceGroup private
Definition at line 32 of file MultiPeriodLoadMuonStrategy.h.
Referenced by applyTimeZeroCorrection(), getLoadedDetectors(), getTimeZeroTable(), loadDeadTimeTable(), loadDetectorGrouping(), loadGoodFrames(), and loadMuonLogData().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/MultiPeriodLoadMuonStrategy.h
Framework/DataHandling/src/MultiPeriodLoadMuonStrategy.cpp