Mantid: Mantid::Geometry::Acomp Class Reference
Mantid::Geometry::Acomp Class Reference
Holds a state point in the decision tree.
#include <Acomp.h>
Public Member Functions
Acomp (int const =0)
Standard Constructor.
std::pair< Acomp, Acomp > algDiv (const Acomp &)
Carry out Algebric division.
void complement ()
Take complement of component.
int contains (const Acomp &) const
Checks the Units of A to see if they are in this->Units.
std::string display () const
Pretty print statment.
std::string displayDepth (int const =0) const
Really pretty print statment of tree.
void getAbsLiterals (std::map< int, int > &) const
Get literals (positve)
std::vector< int > getKeys () const
Get the key numbers in the system.
void getLiterals (std::map< int, int > &) const
Get literals (+/- different)
int isCNF () const
is Units only in intersections
int isDNF () const
is Units only in union
int isInter () const
Deterimine if inter/union.
int isNull () const
is nothing in the comp.
int isSimple () const
true if only Units
int isSingle () const
only one part
int isTrue (const std::map< int, int > &) const
Determine if the rule is true.
const Acomp * itemC (int const) const
returns a pointer to Comp (or zero)
int itemN (int const) const
returns an integer to Units (or zero)
int logicalEqual (const Acomp &) const
Test that the system that is logically the same:
int makeCNFobject ()
Make the object into CNF form (Product of Sums)
int makeDNFobject ()
Make the object into DNF form (Sum of Products)
bool operator!= (const Acomp &) const
Complementary operator.
Acomp & operator*= (const Acomp &)
This carries out the intersection operation with A.
Acomp & operator+= (const Acomp &)
Operator + (union addition)
Acomp & operator-= (const Acomp &)
Operator - (removal) This operation can be carried out in many ways.
bool operator< (const Acomp &) const
Comparitor operator:: Comparies the unit list (which is already sorted) part by part.
bool operator== (const Acomp &) const
Equals operator requires that the Units are equal and the Comp units are equal.
bool operator> (const Acomp &) const
Operator> takes first to last precidence.
void printImplicates (const std::vector< BnId > &, const Kernel::Matrix< int > &) const
Debug function to print out PI and Grid :
void setString (const std::string &)
Processes a line of type abc'+efg.
std::pair< int, int > size () const
get the size of the units and the Acomp sub-comp
void Sort ()
Sort the Units+Comp items.
void writeFull (std::ostream &, int const =0) const
Full write out to determine state.
Private Member Functions
void addComp (const Acomp &)
add a Component intelligently
void addUnit (const std::vector< int > &, const BnId &)
Adds a Binary state to the Component.
void addUnitItem (int const)
add an Unit intellgently
void assignCNF (const std::vector< int > &, const std::vector< BnId > &)
Assigns the Comp with the DNF.
void assignDNF (const std::vector< int > &, const std::vector< BnId > &)
Assigns the Comp with the DNF.
int copySimilar (const Acomp &)
Join two componenet of similar type.
void deleteComp ()
delete all of the Comp list
int getCNFobject (std::vector< int > &, std::vector< BnId > &) const
Creates the CNF items (ie the binary list of false statements) It forms a sum of products.
int getDNFobject (std::vector< int > &, std::vector< BnId > &) const
Creates the DNF items (ie the binary list of true statements) It forms a sum of products.
int getDNFpart (std::vector< Acomp > &) const
get the DNF parts (as Acomp)
int joinDepth ()
Search table to uplift objects.
int makeEPI (std::vector< BnId > &, std::vector< BnId > &) const
Creates an essentual PI list (note: this is not unique).
int makePI (std::vector< BnId > &) const
Calculate Principal Components.
int makeReadOnce ()
Factorize into a read once function.
void processIntersection (const std::string &)
Helper function :: assumes that Ln has been checked for bracket consistency.
void processUnion (const std::string &)
Helper function :: assumes that Ln has been checked for bracket consistency Units are sorted after this function is returned.
int removeEqComp ()
Remove non-unique items.
Private Attributes
std::vector< Acomp > Comp
Components in list.
int Intersect
Union/Intersection (0,1)
std::vector< int > Units
Units in list.
Detailed Description
Holds a state point in the decision tree.
Version
1.0
Author
S. Ansell
Date
April 2005
Holds the state of a logical unit. Either a state point and intersection or a unit A component, either a union or intersection. It has to have the ability to change the type from union/intersection in an instant. Hence the type flag. This currently works with forming disjunction form. The disjunction form is "or" [ v symbol ]. Thus is is a set of unions.
intersection : (logical and) : ^ : e.g abcd
union : (logical or) : v : e.g a+b+c+d
Definition at line 43 of file Acomp.h.
Constructor & Destructor Documentation
Acomp()
Mantid::Geometry::Acomp::Acomp (int const Tx = 0)
Standard Constructor.
Parameters
Tx :: 1 it means intersect 0 it meanse union
Definition at line 64 of file Acomp.cpp.
Member Function Documentation
addComp()
void Mantid::Geometry::Acomp::addComp (const Acomp & AX) private
add a Component intelligently
Adds a pointer to the Comp list.
If the pointer is singular, extracts the object and adds that componenet. Assumes that the component is sorted and inserts appropiately.
Parameters
AX :: Acomp component to add
Definition at line 308 of file Acomp.cpp.
References Comp, Intersect, isSingle(), size(), and Units.
Referenced by algDiv(), assignCNF(), assignDNF(), copySimilar(), operator*=(), operator+=(), operator-=(), processIntersection(), and processUnion().
addUnit()
void Mantid::Geometry::Acomp::addUnit (const std::vector< int > & Index, const BnId & BX) private
Adds a Binary state to the Component.
Given a single BnId unit and an index adds it to the main Units object.
Parameters
Index :: number , surfNumber
BX :: binary component
Definition at line 505 of file Acomp.cpp.
References Mantid::Geometry::BnId::Size(), Mantid::Geometry::split(), and Units.
Referenced by assignCNF(), assignDNF(), and getDNFpart().
addUnitItem()
void Mantid::Geometry::Acomp::addUnitItem (int const Item) private
add an Unit intellgently
Adds a unit to the Unit list (if it doesn't exist).
Parameters
Item :: Unit to add
Definition at line 346 of file Acomp.cpp.
References Units.
Referenced by algDiv(), getDNFpart(), and processIntersection().
algDiv()
std::pair< Acomp, Acomp > Mantid::Geometry::Acomp::algDiv (const Acomp & G)
Carry out Algebric division.
Carries out algebraic division.
Parameters
G :: The divisor
Returns
Pair of Divided + Remainder
Definition at line 1200 of file Acomp.cpp.
References addComp(), addUnitItem(), Comp, getDNFpart(), getLiterals(), isDNF(), isNull(), makeDNFobject(), and Units.
Referenced by Mantid::Geometry::Algebra::algDiv().
assignCNF()
void Mantid::Geometry::Acomp::assignCNF (const std::vector< int > & Index, const std::vector< BnId > & A) private
Assigns the Comp with the DNF.
Assign the object to the Essentual PI in the vector A.
This will make the form DNF.
Parameters
Index :: SurfNumbers
A :: Vector of BnId's that are valid
Definition at line 555 of file Acomp.cpp.
References addComp(), addUnit(), deleteComp(), Intersect, Mantid::Geometry::BnId::reverse(), Units, and Mantid::Geometry::X.
Referenced by makeCNFobject().
assignDNF()
void Mantid::Geometry::Acomp::assignDNF (const std::vector< int > & Index, const std::vector< BnId > & A) private
Assigns the Comp with the DNF.
Assign the object to the Essentual PI in the vector A.
This will make the form DNF.
Parameters
Index :: SurfNumbers
A :: Vector of BnId's that are valid
Definition at line 526 of file Acomp.cpp.
References addComp(), addUnit(), deleteComp(), Intersect, and Units.
Referenced by makeDNFobject().
complement()
void Mantid::Geometry::Acomp::complement ()
Take complement of component.
Take a complement of the current object This will reverse the type since union<->intersection as a+b -> a'b' and ab -> a'+b'.
Resort the list. use reverse?
Definition at line 1469 of file Acomp.cpp.
References Comp, complement(), Intersect, and Units.
Referenced by complement(), Mantid::Geometry::Algebra::Complement(), and setString().
contains()
int Mantid::Geometry::Acomp::contains (const Acomp & A) const
Checks the Units of A to see if they are in this->Units.
Assumes that Units is sorted.
Parameters
A :: Object to cross compare
Return values
0 :: all literals in A are in this
1 :: A is unique from this
Definition at line 1279 of file Acomp.cpp.
copySimilar()
int Mantid::Geometry::Acomp::copySimilar (const Acomp & A) private
Join two componenet of similar type.
Class to merge two list of similar objects.
Makes a full copy of the objects It requires that the Intersect is the same for both
Parameters
A :: Object to copy
Returns
0 on success -1 on failure
Definition at line 479 of file Acomp.cpp.
References addComp(), Comp, Intersect, and Units.
Referenced by operator*=(), and operator+=().
deleteComp()
void Mantid::Geometry::Acomp::deleteComp () private
delete all of the Comp list
Deletes everything in Composite.
Definition at line 300 of file Acomp.cpp.
References Comp.
Referenced by assignCNF(), assignDNF(), and setString().
display()
std::string Mantid::Geometry::Acomp::display () const
Pretty print statment.
Real pretty print out statement.
Returns
Full string of the output in abc+efg type form
Definition at line 1506 of file Acomp.cpp.
References Comp, Intersect, Mantid::Geometry::split(), and Units.
Referenced by Mantid::Geometry::Algebra::display(), Mantid::Geometry::operator<<(), setString(), and Mantid::Geometry::Algebra::writeMCNPX().
displayDepth()
std::string Mantid::Geometry::Acomp::displayDepth (int const dval = 0) const
Really pretty print statment of tree.
Real pretty print out statement :-)
Parameters
dval :: parameter to keep track of depth
Returns
Full string of print line
Definition at line 1539 of file Acomp.cpp.
References Mantid::Geometry::split().
getAbsLiterals()
void Mantid::Geometry::Acomp::getAbsLiterals (std::map< int, int > & literalMap) const
Get literals (positve)
get a map of the literals and the frequency that they occur.
This does not keep the +/- part of the literals separate
Parameters
literalMap :: Map the get the frequency of the literals
Definition at line 705 of file Acomp.cpp.
References Mantid::Geometry::split().
Referenced by getKeys().
getCNFobject()
int Mantid::Geometry::Acomp::getCNFobject (std::vector< int > & keyNumbers, std::vector< BnId > & CNFobj) const private
Creates the CNF items (ie the binary list of false statements) It forms a sum of products.
The original is not changed by the keynumbers and the DNF objects are output into the function parameters.
Parameters
keyNumbers :: index list of the CNFobj. The [bitNum]->rule/key number.
CNFobj :: write out the CNF object into BnId form
Return values
0 :: on success.
-1 :: on error.
Definition at line 1117 of file Acomp.cpp.
References Mantid::Geometry::BnId::mapState().
Referenced by makeCNFobject().
getDNFobject()
int Mantid::Geometry::Acomp::getDNFobject (std::vector< int > & keyNumbers, std::vector< BnId > & DNFobj) const private
Creates the DNF items (ie the binary list of true statements) It forms a sum of products.
The original is not changed by the keynumbers and the DNF objects are output into the function parameters.
Parameters
keyNumbers :: index list of the DNFobj. The [bitNum]->rule/key number.
DNFobj :: write out the DNF object into BnId form
Return values
0 :: on success.
-1 :: on error.
Definition at line 1006 of file Acomp.cpp.
References Mantid::Geometry::BnId::mapState().
Referenced by makeDNFobject().
getDNFpart()
int Mantid::Geometry::Acomp::getDNFpart (std::vector< Acomp > & Parts) const private
get the DNF parts (as Acomp)
Sets the object into parts of the DNF form then puts the object in the Parts section.
Parameters
Parts,: vector of the Parts found (Acomp units without component)
Returns
number of parts
Definition at line 1080 of file Acomp.cpp.
References addUnit(), addUnitItem(), and obj.
Referenced by algDiv(), and operator-=().
getKeys()
std::vector< int > Mantid::Geometry::Acomp::getKeys () const
Get the key numbers in the system.
Returns
Key of literals
Definition at line 990 of file Acomp.cpp.
References getAbsLiterals().
getLiterals()
void Mantid::Geometry::Acomp::getLiterals (std::map< int, int > & literalMap) const
Get literals (+/- different)
Get a map of the literals and the frequency that they occur.
This keeps + and - literals separate
Parameters
literalMap :: Map the get the frequency of the literals
Definition at line 730 of file Acomp.cpp.
Referenced by algDiv(), Mantid::Geometry::Algebra::countLiterals(), and makeReadOnce().
isCNF()
int Mantid::Geometry::Acomp::isCNF () const
is Units only in intersections
Determines if the component is in CNF form.
This Acomp needs to be an intersection of unions
Return values
1 :: DNF form
0 :: not DNF form
Definition at line 684 of file Acomp.cpp.
References Comp, and Intersect.
isDNF()
int Mantid::Geometry::Acomp::isDNF () const
is Units only in union
Determines if the component is in DNF form.
This Acomp needs to be a union of intersection.
Return values
1 :: DNF form
0 :: not DNF form
Definition at line 663 of file Acomp.cpp.
References Comp, and Intersect.
Referenced by algDiv().
isInter()
int Mantid::Geometry::Acomp::isInter () const inline
Deterimine if inter/union.
Definition at line 98 of file Acomp.h.
isNull()
int Mantid::Geometry::Acomp::isNull () const
is nothing in the comp.
Returns
1 if there are no memebers
Definition at line 655 of file Acomp.cpp.
References Comp, and Units.
Referenced by algDiv().
isSimple()
int Mantid::Geometry::Acomp::isSimple () const
true if only Units
Determines if there are not complex components.
Return values
1 :: Comp is empty
0 :: Contains Components.
Definition at line 754 of file Acomp.cpp.
References Comp.
isSingle()
int Mantid::Geometry::Acomp::isSingle () const
only one part
Deterimines if the item's singular.
Return values
1 if only one/zero item
0 if more than one item.
Definition at line 764 of file Acomp.cpp.
References Comp, and Units.
Referenced by addComp().
isTrue()
int Mantid::Geometry::Acomp::isTrue (const std::map< int, int > & Base) const
Determine if the rule is true.
Determines if the rule is true, given the Base state.
Parameters
Base :: map of <LiteralNumber, State>
Returns
1 if true and 0 if false
Definition at line 1158 of file Acomp.cpp.
References Mantid::Geometry::split().
itemC()
const Acomp * Mantid::Geometry::Acomp::itemC (int const Index) const
returns a pointer to Comp (or zero)
Assessor function to get a Comp points.
Parameters
Index :: Number of Comp to aquire
Returns
Comp[Index] or 0 on failure
Definition at line 1457 of file Acomp.cpp.
Referenced by joinDepth().
itemN()
int Mantid::Geometry::Acomp::itemN (int const Index) const
returns an integer to Units (or zero)
Assessor function to get a unit number.
Parameters
Index :: Number of Unit to aquire
Returns
Units[Index] or 0 on failure
Definition at line 1445 of file Acomp.cpp.
Referenced by joinDepth().
joinDepth()
int Mantid::Geometry::Acomp::joinDepth () private
Search table to uplift objects.
Searchs down the tree to find if any singles exist and up-promotes them.
Exceptions
ColErr::ExBase on mal-formed state
Returns
number of up-promotions.
Definition at line 1299 of file Acomp.cpp.
References Comp, Intersect, itemC(), itemN(), removeEqComp(), size(), Sort(), and Units.
Referenced by operator*=(), operator+=(), and operator-=().
logicalEqual()
int Mantid::Geometry::Acomp::logicalEqual (const Acomp & A) const
Test that the system that is logically the same:
Parameters
A :: Logical state to test
Return values
0 :: false
1 :: true
Definition at line 625 of file Acomp.cpp.
References Mantid::Geometry::BnId::mapState().
makeCNFobject()
int Mantid::Geometry::Acomp::makeCNFobject ()
Make the object into CNF form (Product of Sums)
Sets the object to the CNF form.
Return values
0 on failure
Number of CNF components
Definition at line 1063 of file Acomp.cpp.
References assignCNF(), getCNFobject(), and makePI().
Referenced by Mantid::Geometry::Algebra::makeCNF().
makeDNFobject()
int Mantid::Geometry::Acomp::makeDNFobject ()
Make the object into DNF form (Sum of Products)
Sets the object to the DNF form.
Return values
0 on failure
Number of DNF components
Definition at line 1046 of file Acomp.cpp.
References assignDNF(), getDNFobject(), and makePI().
Referenced by algDiv(), and Mantid::Geometry::Algebra::makeDNF().
makeEPI()
int Mantid::Geometry::Acomp::makeEPI (std::vector< BnId > & DNFobj, std::vector< BnId > & PIform) const private
Creates an essentual PI list (note: this is not unique).
Given the list form the EPI based on the Quine-McClusky method.
Parameters
DNFobj :: Object in DNF form
PIform :: List of rules in Prime Implicant form It is set on exit (to the EPI)
Returns
:: 1 if successful and 0 if failed
Definition at line 862 of file Acomp.cpp.
References cm.
makePI()
int Mantid::Geometry::Acomp::makePI (std::vector< BnId > & DNFobj) const private
Calculate Principal Components.
This method finds the principle implicants.
Parameters
DNFobj :: A vector of Binary ID from a true vectors of keyvalues.
Returns
number of PIs found.
Todo:
Can we set this up to get non-pairs i.e. one pass.
Definition at line 797 of file Acomp.cpp.
References Mantid::Geometry::BnId::setPI().
Referenced by makeCNFobject(), and makeDNFobject().
makeReadOnce()
int Mantid::Geometry::Acomp::makeReadOnce () private
Factorize into a read once function.
This function attempts to make the function a read one form.
Assumes that it is either DNF or CNF form
Return values
0 if fails
1 if success (and sets it into the appropiate form)
Definition at line 604 of file Acomp.cpp.
References getLiterals().
operator!=()
bool Mantid::Geometry::Acomp::operator!= (const Acomp & A) const
Complementary operator.
Inequality operator.
Parameters
A :: other Acomp item to compare
Returns
Not this==A
Definition at line 72 of file Acomp.cpp.
References Mantid::Geometry::operator==().
operator*=()
Acomp & Mantid::Geometry::Acomp::operator*= (const Acomp & A)
This carries out the intersection operation with A.
e.g. (a+b) * (ced) == (a+b)ced
Parameters
A :: Acomp unit to intersect
Returns
*this
Definition at line 271 of file Acomp.cpp.
References addComp(), Comp, copySimilar(), Intersect, joinDepth(), removeEqComp(), and Units.
Referenced by operator-=().
operator+=()
Acomp & Mantid::Geometry::Acomp::operator+= (const Acomp & A)
Operator + (union addition)
Parameters
A :: Object to union with this
Returns
*this
Definition at line 168 of file Acomp.cpp.
References addComp(), Comp, copySimilar(), Intersect, joinDepth(), removeEqComp(), and Units.
operator-=()
Acomp & Mantid::Geometry::Acomp::operator-= (const Acomp & A)
Operator - (removal) This operation can be carried out in many ways.
It is by direct pattern subtraction followed by complementary subtraction or the remainder Complementary subtraction is by making A-B == A*B'
Parameters
A :: Object to subtract
Returns
*this
Definition at line 194 of file Acomp.cpp.
References addComp(), Comp, getDNFpart(), Intersect, joinDepth(), operator*=(), removeEqComp(), Sort(), and Units.
operator<()
bool Mantid::Geometry::Acomp::operator< (const Acomp & A) const
Comparitor operator:: Comparies the unit list (which is already sorted) part by part.
The sort is ASSUMED. Then the Comp units (which are not) Order (low first)
Singulars
Intersections
Units (largest negative)
Acomps.
Parameters
A :: Object to compare
Returns
this
Definition at line 118 of file Acomp.cpp.
operator==()
bool Mantid::Geometry::Acomp::operator== (const Acomp & A) const
Equals operator requires that the Units are equal and the Comp units are equal.
Sort of the class is required.
Parameters
A :: other Acomp item to compare
Returns
A==*this
Definition at line 82 of file Acomp.cpp.
operator>()
bool Mantid::Geometry::Acomp::operator> (const Acomp & A) const
Operator> takes first to last precidence.
Uses operator< to obtain value. Note it does not uses 1-(A<this)
Parameters
A :: object to compare
Returns
this>A
Definition at line 259 of file Acomp.cpp.
printImplicates()
void Mantid::Geometry::Acomp::printImplicates (const std::vector< BnId > & PIform, const Kernel::Matrix< int > & Grid) const
Debug function to print out PI and Grid :
Parameters
PIform :: Principle implicates
Grid :: grid form
Definition at line 1577 of file Acomp.cpp.
processIntersection()
void Mantid::Geometry::Acomp::processIntersection (const std::string & Ln) private
Helper function :: assumes that Ln has been checked for bracket consistency.
Units are sorted after this function is returned.
Parameters
Ln :: String to processed as an intersection must not contain a toplevel +
Exceptions
ExBase on failure to pass string
Definition at line 359 of file Acomp.cpp.
References addComp(), addUnitItem(), Mantid::Kernel::Strings::convPartNum(), and setString().
Referenced by setString().
processUnion()
void Mantid::Geometry::Acomp::processUnion (const std::string & Ln) private
Helper function :: assumes that Ln has been checked for bracket consistency Units are sorted after this function is returned.
Parameters
Ln :: String to processed as a union (must contain one external +)
Exceptions
ExBase on failure to pass string
Definition at line 421 of file Acomp.cpp.
References addComp(), and setString().
Referenced by setString().
removeEqComp()
int Mantid::Geometry::Acomp::removeEqComp () private
Remove non-unique items.
Remove identical items.
Returns
number removed.
Definition at line 774 of file Acomp.cpp.
References Comp, and Units.
Referenced by joinDepth(), operator*=(), operator+=(), and operator-=().
setString()
void Mantid::Geometry::Acomp::setString (const std::string & Line)
Processes a line of type abc'+efg.
Sort out stuff like abc'+efg given a inner bracket expand that etc.
Parameters
Line :: string of for abc'.
Complementary object
Resort the list.
Definition at line 1371 of file Acomp.cpp.
References complement(), deleteComp(), display(), Intersect, processIntersection(), processUnion(), setString(), and Units.
Referenced by processIntersection(), processUnion(), Mantid::Geometry::Algebra::setFunction(), and setString().
size()
std::pair< int, int > Mantid::Geometry::Acomp::size () const
get the size of the units and the Acomp sub-comp
Gets the size of the Units and the Comp.
Returns
size of Unit, Comp
Definition at line 1436 of file Acomp.cpp.
References Comp, and Units.
Referenced by addComp(), and joinDepth().
Sort()
void Mantid::Geometry::Acomp::Sort ()
Sort the Units+Comp items.
Function to sort the components of the lists.
Decends down the Comp Tree.
Definition at line 591 of file Acomp.cpp.
References Comp, Sort(), and Units.
Referenced by joinDepth(), operator-=(), and Sort().
writeFull()
void Mantid::Geometry::Acomp::writeFull (std::ostream & OXF, int const Indent = 0) const
Full write out to determine state.
Real pretty print out statement :-)
Parameters
OXF :: output stream
Indent :: level of indentation (allows a cascaded call system)
Definition at line 1486 of file Acomp.cpp.
Member Data Documentation
Comp
std::vector<Acomp> Mantid::Geometry::Acomp::Comp private
Components in list.
Definition at line 48 of file Acomp.h.
Referenced by addComp(), algDiv(), complement(), copySimilar(), deleteComp(), display(), isCNF(), isDNF(), isNull(), isSimple(), isSingle(), joinDepth(), operator*=(), operator+=(), operator-=(), removeEqComp(), size(), and Sort().
Intersect
int Mantid::Geometry::Acomp::Intersect private
Union/Intersection (0,1)
Definition at line 46 of file Acomp.h.
Referenced by addComp(), assignCNF(), assignDNF(), complement(), copySimilar(), display(), isCNF(), isDNF(), joinDepth(), operator*=(), operator+=(), operator-=(), and setString().
Units
std::vector<int> Mantid::Geometry::Acomp::Units private
Units in list.
Definition at line 47 of file Acomp.h.
Referenced by addComp(), addUnit(), addUnitItem(), algDiv(), assignCNF(), assignDNF(), complement(), copySimilar(), display(), isNull(), isSingle(), joinDepth(), operator*=(), operator+=(), operator-=(), removeEqComp(), setString(), size(), and Sort().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Math/Acomp.h
Framework/Geometry/src/Math/Acomp.cpp