Mantid: Mantid::Crystal::Cluster Class Reference
Mantid::Crystal::Cluster Class Reference
Cluster : Image cluster used by connected component labeling.
#include <Cluster.h>
Public Member Functions
void addIndex (const size_t &index) override
Track a linear IMDHistoWorkspace index that belongs to the cluster.
Cluster (const size_t &label)
Constructor.
bool containsLabel (const size_t &label) const override
Does the cluster contain the label.
size_t getLabel () const override
Get the cluster label.
size_t getOriginalLabel () const override
Get the original label.
size_t getRepresentitiveIndex () const override
Get a representative index of the cluster.
ClusterIntegratedValues integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const override
integrate the cluster
bool operator== (const Cluster &other) const
Overloaded equals.
void setRootCluster (ICluster const *root) override
Set the root cluster.
size_t size () const override
Number of indexes tracked.
void toUniformMinimum (std::vector< DisjointElement > &disjointSet) override
Resolve the proper label for this cluster.
void writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const override
Apply labels to the workspace.
Public Member Functions inherited from Mantid::Crystal::ICluster
virtual void addIndex (const size_t &index)=0
Track a linear IMDHistoWorkspace index that belongs to the cluster.
virtual bool containsLabel (const size_t &label) const =0
Is the label contained in the cluster.
virtual size_t getLabel () const =0
Get the cluster label.
virtual size_t getOriginalLabel () const =0
Get the originally set label.
virtual size_t getRepresentitiveIndex () const =0
Get a represetiative index of the cluster.
virtual ClusterIntegratedValues integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const =0
integrate the cluster
virtual void setRootCluster (ICluster const *root)=0
Set the root cluster.
virtual size_t size () const =0
Number of indexes tracked.
virtual void toUniformMinimum (std::vector< DisjointElement > &disjointSet)=0
Resolve the proper label for this cluster.
virtual void writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const =0
Apply labels to the workspace.
virtual ~ICluster ()=default
Virtual destructor.
Private Member Functions
Cluster (const Cluster &)
Disabled copy construction.
Cluster & operator= (const Cluster &)
Disabled assignement.
Private Attributes
std::vector< size_t > m_indexes
indexes belonging to cluster. This is how we track cluster objects.
size_t m_originalLabel
original label on cluster
ICluster const * m_rootCluster
Root cluster.
Additional Inherited Members
Public Types inherited from Mantid::Crystal::ICluster
using ClusterIntegratedValues = boost::tuple< double, double >
Detailed Description
Cluster : Image cluster used by connected component labeling.
Definition at line 22 of file Cluster.h.
Constructor & Destructor Documentation
Cluster() [1/2]
Mantid::Crystal::Cluster::Cluster (const size_t & label)
Constructor.
Parameters
label : Label (taken as original) for Cluster
Definition at line 20 of file Cluster.cpp.
References m_indexes.
Cluster() [2/2]
Mantid::Crystal::Cluster::Cluster (const Cluster &) private
Disabled copy construction.
Member Function Documentation
addIndex()
void Mantid::Crystal::Cluster::addIndex (const size_t & index) override virtual
Track a linear IMDHistoWorkspace index that belongs to the cluster.
Add the index to the cluster.
Parameters
index : index to add
Implements Mantid::Crystal::ICluster.
Definition at line 51 of file Cluster.cpp.
References m_indexes.
containsLabel()
bool Mantid::Crystal::Cluster::containsLabel (const size_t & label) const override virtual
Does the cluster contain the label.
Parameters
label : Label to find
Returns
: True only if the label exists.
Implements Mantid::Crystal::ICluster.
Definition at line 121 of file Cluster.cpp.
References getLabel().
getLabel()
size_t Mantid::Crystal::Cluster::getLabel () const override virtual
Get the cluster label.
Get the label.
Returns
: Return label.
Implements Mantid::Crystal::ICluster.
Definition at line 26 of file Cluster.cpp.
References Mantid::Crystal::ICluster::getLabel(), m_originalLabel, and m_rootCluster.
Referenced by containsLabel(), operator==(), and writeTo().
getOriginalLabel()
size_t Mantid::Crystal::Cluster::getOriginalLabel () const override virtual
Get the original label.
Returns
: Original label
Implements Mantid::Crystal::ICluster.
Definition at line 38 of file Cluster.cpp.
References m_originalLabel.
getRepresentitiveIndex()
size_t Mantid::Crystal::Cluster::getRepresentitiveIndex () const override virtual
Get a representative index of the cluster.
Get a representative index which is part of this cluster.
Returns
Implements Mantid::Crystal::ICluster.
Definition at line 101 of file Cluster.cpp.
References m_indexes.
integrate()
ICluster::ClusterIntegratedValues Mantid::Crystal::Cluster::integrate (std::shared_ptr< const Mantid::API::IMDHistoWorkspace > ws) const override virtual
integrate the cluster
Integrate the image over cluster region.
Parameters
ws : Image
Returns
: Integrated values
Implements Mantid::Crystal::ICluster.
Definition at line 70 of file Cluster.cpp.
References m_indexes.
operator=()
Cluster & Mantid::Crystal::Cluster::operator= (const Cluster &) private
Disabled assignement.
operator==()
bool Mantid::Crystal::Cluster::operator== (const Cluster & other) const
Overloaded equals.
Overlaoded equals operator.
Parameters
other : To compare with
Returns
True only if the objects are equal
Definition at line 114 of file Cluster.cpp.
References getLabel().
setRootCluster()
void Mantid::Crystal::Cluster::setRootCluster (ICluster const * root) override virtual
Set the root cluster.
Parameters
root : Root cluster
Implements Mantid::Crystal::ICluster.
Definition at line 107 of file Cluster.cpp.
References m_rootCluster.
size()
size_t Mantid::Crystal::Cluster::size () const override virtual
Number of indexes tracked.
Get the number of indexes which are part of this cluster.
i.e. the size of the cluster
Returns
: Cluster size
Implements Mantid::Crystal::ICluster.
Definition at line 45 of file Cluster.cpp.
References m_indexes.
toUniformMinimum()
void Mantid::Crystal::Cluster::toUniformMinimum (std::vector< DisjointElement > & disjointSet) override virtual
Resolve the proper label for this cluster.
Allow the cluster to adopt the uniform minimum value.
Parameters
disjointSet
Implements Mantid::Crystal::ICluster.
Definition at line 87 of file Cluster.cpp.
References Mantid::Crystal::ICluster::getRepresentitiveIndex(), m_indexes, and m_rootCluster.
writeTo()
void Mantid::Crystal::Cluster::writeTo (std::shared_ptr< Mantid::API::IMDHistoWorkspace > ws) const override virtual
Apply labels to the workspace.
Apply the cluster to the image.
Parameters
ws : Image to stencil itself onto
Implements Mantid::Crystal::ICluster.
Definition at line 57 of file Cluster.cpp.
References getLabel(), and m_indexes.
Member Data Documentation
m_indexes
std::vector<size_t> Mantid::Crystal::Cluster::m_indexes private
indexes belonging to cluster. This is how we track cluster objects.
Definition at line 69 of file Cluster.h.
Referenced by addIndex(), Cluster(), getRepresentitiveIndex(), integrate(), size(), toUniformMinimum(), and writeTo().
m_originalLabel
size_t Mantid::Crystal::Cluster::m_originalLabel private
original label on cluster
Definition at line 67 of file Cluster.h.
Referenced by getLabel(), and getOriginalLabel().
m_rootCluster
ICluster const* Mantid::Crystal::Cluster::m_rootCluster private
Root cluster.
Definition at line 71 of file Cluster.h.
Referenced by getLabel(), setRootCluster(), and toUniformMinimum().
The documentation for this class was generated from the following files:
Framework/Crystal/inc/MantidCrystal/Cluster.h
Framework/Crystal/src/Cluster.cpp