Mantid: ICat4::xsd__dateTime Class Reference
ICat4::xsd__dateTime Class Reference
#include <ICat4Stub.h>
Public Member Functions
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
xsd__dateTime ()
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
time_t __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 141 of file ICat4Stub.h.
Constructor & Destructor Documentation
xsd__dateTime()
ICat4::xsd__dateTime::xsd__dateTime () inline
Definition at line 153 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::xsd__dateTime::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24148 of file ICat4C.cpp.
References ICat4::soap_default_time().
Referenced by ICat4::soap_in_xsd__dateTime(), ICat4::soap_new_req_xsd__dateTime(), and ICat4::soap_new_set_xsd__dateTime().
soap_get()
void * ICat4::xsd__dateTime::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24204 of file ICat4C.cpp.
References ICat4::soap_get_xsd__dateTime().
soap_in()
void * ICat4::xsd__dateTime::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24171 of file ICat4C.cpp.
References ICat4::soap_in_xsd__dateTime().
Referenced by ICat4::soap_in_xsd__dateTime().
soap_out()
int ICat4::xsd__dateTime::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24162 of file ICat4C.cpp.
References ICat4::soap_out_xsd__dateTime().
soap_put()
int ICat4::xsd__dateTime::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24197 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_xsd__dateTime.
soap_serialize()
void ICat4::xsd__dateTime::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24154 of file ICat4C.cpp.
References SOAP_TYPE_ICat4_time.
soap_type()
int ICat4::xsd__dateTime::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 146 of file ICat4Stub.h.
Member Data Documentation
__item
time_t ICat4::xsd__dateTime::__item
Definition at line 143 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp