Mantid: Mantid::Kernel::DllOpen Class Reference
Mantid::Kernel::DllOpen Class Reference
Simple class for opening shared libraries at run-time.
#include <DllOpen.h>
Public Member Functions
DllOpen ()=delete
DllOpen (const DllOpen &)=delete
~DllOpen ()=delete
Static Public Member Functions
static void closeDll (void *handle)
Static method for closing the shared library.
static bool isValidFilename (const std::string &filename)
Check if the filename conforms to the expected style for this platform.
static void * openDll (const std::string &filepath)
Static method for opening the shared library.
Detailed Description
Simple class for opening shared libraries at run-time.
Works for Windows and Linux.
Author
ISIS, STFC
Date
25/10/2007
Definition at line 24 of file DllOpen.h.
Constructor & Destructor Documentation
DllOpen() [1/2]
Mantid::Kernel::DllOpen::DllOpen () delete
DllOpen() [2/2]
Mantid::Kernel::DllOpen::DllOpen (const DllOpen &) delete
~DllOpen()
Mantid::Kernel::DllOpen::~DllOpen () delete
Member Function Documentation
closeDll()
void Mantid::Kernel::DllOpen::closeDll (void * handle) static
Static method for closing the shared library.
Definition at line 105 of file DllOpen.cpp.
References UNUSED_ARG.
Referenced by Mantid::Kernel::LibraryWrapper::~LibraryWrapper().
isValidFilename()
bool Mantid::Kernel::DllOpen::isValidFilename (const std::string & filename) static
Check if the filename conforms to the expected style for this platform.
Does the file have the expected form for this platform.
Parameters
filename The file name of the library
Returns
True if it matches the expected format, false otherwise
Definition at line 86 of file DllOpen.cpp.
References Mantid::Kernel::LIB_PREFIX.
Referenced by Mantid::Kernel::LibraryManagerImpl::shouldBeLoaded().
openDll()
void * Mantid::Kernel::DllOpen::openDll (const std::string & filepath) static
Static method for opening the shared library.
Definition at line 94 of file DllOpen.cpp.
References Mantid::Kernel::Logger::error(), and Mantid::Kernel::DateAndTimeHelpers::g_log.
Referenced by Mantid::Kernel::LibraryWrapper::openLibrary().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/DllOpen.h
Framework/Kernel/src/DllOpen.cpp