Mantid: Mantid::CurveFitting::Functions::ComptonProfile Class Reference
Mantid::CurveFitting::Functions::ComptonProfile Class Reference abstract
This class serves as a base-class for ComptonProfile type functions.
#include <ComptonProfile.h>
Public Member Functions
ComptonProfile ()
Default constructor required for factory.
virtual size_t fillConstraintMatrix (Kernel::DblMatrix &cmatrix, const size_t start, const HistogramData::HistogramE &errors) const =0
Fill the appropriate columns of the given matrix with the values of the mass profile.
virtual std::vector< size_t > intensityParameterIndices () const =0
Returns the indices of the intensity parameters.
virtual void massProfile (double *result, const size_t nData) const =0
Override to calculate the value of the profile for this mass and store in the given array.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t i, const double &value, bool explicitlySet=true) override
Set i-th parameter.
Function evaluation
void function1D (double *out, const double *xValues, const size_t nData) const override
Calculates the value of the function for each x value and stores in the given output array.
void setUpForFit () override
Ensure the object is ready to be fitted.
void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wsIndex, double startX, double endX) override
Cache a copy of the workspace pointer and pull out the parameters.
void buildCaches ()
Initiate a Y-space value chache rebuild when workspace of mass are changed.
void cacheYSpaceValues (const HistogramData::Points &tseconds, const Algorithms::DetectorParams &detpar, const ResolutionParams &respar)
Pre-calculate the Y-space values with specified resolution parameters.
virtual void cacheYSpaceValues (const HistogramData::Points &tseconds, const Algorithms::DetectorParams &detpar)
Pre-calculate the Y-space values.
void disableLogging ()
Turn off logger.
Public Member Functions inherited from Mantid::API::ParamFunction
IFunction_sptr getContainingFunction (const ParameterReference &ref) const
Get the containing function.
IFunction_sptr getContainingFunction (IFunction_sptr fun)
Get the containing function.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const ParameterReference &ref) const override
Return parameter index from a parameter reference.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
ParamFunction ()
Default constructor.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
virtual ParameterTie * getTie (size_t i) const
Get the tie of i-th parameter.
virtual bool ignoreTie (const ParameterTie &) const
Ignore a tie.
void sortTies (const bool checkOnly=false)
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual IConstraint * getConstraint (size_t i) const
Get constraint of i-th parameter.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual size_t nAttributes () const
Returns the number of attributes associated with the function.
virtual std::vector< std::string > getAttributeNames () const
Returns a list of attribute names.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
virtual Attribute getAttribute (const std::string &name) const
Return a value of attribute attName.
virtual void setAttribute (const std::string &name, const Attribute &)
Set a value to attribute attName.
virtual bool hasAttribute (const std::string &name) const
Check if attribute attName exists.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
virtual size_t getNumberDomains () const
Get number of domains required by this function.
virtual std::vector< std::shared_ptr< IFunction > > createEquivalentFunctions () const
Split this function (if needed) into a list of independent functions.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Public Member Functions inherited from Mantid::API::IFunction1D
virtual void derivative (const FunctionDomain &domain, FunctionValues &values, const size_t order=1) const
virtual void derivative1D (double *out, const double *xValues, const size_t nData, const size_t order) const
Function to calculate the derivatives of the data set.
void function (const FunctionDomain &domain, FunctionValues &values) const override
Evaluates the function for all arguments in the domain.
void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian) override
Derivatives of function with respect to active parameters.
virtual void functionDeriv1D (Jacobian *jacobian, const double *xValues, const size_t nData)
Derivatives of function with respect to active parameters.
Protected Member Functions
void declareParameters () override
Declare parameters that will never participate in the fit.
const std::vector< double > & e0 () const
Access e0 values.
double mass () const
Access the mass.
const std::vector< double > & modQ () const
Access Q values cache.
void voigtApprox (std::vector< double > &voigt, const std::vector< double > &yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const
Compute Voigt function.
void voigtApproxDiff (std::vector< double > &voigtDiff, const std::vector< double > &yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const
Compute Voigt function interpolated around the given values.
const std::vector< double > & ySpace () const
Access y-values cache.
Protected Member Functions inherited from Mantid::API::ParamFunction
void clearAllParameters ()
Nonvirtual member which removes all declared parameters.
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
virtual double * getParameterAddress (size_t i)
Get the address of the parameter. For use in UserFunction with mu::Parser.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Member Functions inherited from Mantid::API::IFunction1D
template<typename EvaluationMethod >
void calcNumericalDerivative1D (Jacobian *jacobian, EvaluationMethod func1D, const double *xValues, const size_t nData)
Calculate a numerical derivative for the 1D data.
virtual void histogram1D (double *out, double left, const double *right, const size_t nBins) const
Calculate histogram data for the given bin boundaries.
virtual void histogramDerivative1D (Jacobian *jacobian, double left, const double *right, const size_t nBins) const
Derivatives of the histogram1D with respect to active parameters.
Protected Attributes
double m_endX
Kernel::Logger m_log
Logger.
std::shared_ptr< VesuvioResolution > m_resolutionFunction
Vesuvio resolution function.
double m_startX
std::shared_ptr< API::IPeakFunction > m_voigt
Voigt function.
std::shared_ptr< const API::MatrixWorkspace > m_workspace
Current workspace.
size_t m_wsIndex
Current workspace index, required to access instrument parameters.
Caches for commonly used values
std::vector< double > m_yspace
std::vector< double > m_modQ
Q-values.
std::vector< double > m_e0
Incident energies.
double m_mass
Atomic mass.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Types inherited from Mantid::API::IFunction1D
template<typename FunctionType >
using Function1DMethod = void(FunctionType::*)(double *, const double *, const size_t) const
Static Protected Attributes inherited from Mantid::API::IFunction1D
static Kernel::Logger g_log
Logger instance.
Detailed Description
This class serves as a base-class for ComptonProfile type functions.
See also
GaussianComptonProfile, GramCharlierComptonProfile
Definition at line 30 of file ComptonProfile.h.
Constructor & Destructor Documentation
ComptonProfile()
Mantid::CurveFitting::Functions::ComptonProfile::ComptonProfile ()
Default constructor required for factory.
Definition at line 30 of file ComptonProfile.cpp.
Member Function Documentation
buildCaches()
void Mantid::CurveFitting::Functions::ComptonProfile::buildCaches ()
Initiate a Y-space value chache rebuild when workspace of mass are changed.
Definition at line 88 of file ComptonProfile.cpp.
References cacheYSpaceValues(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::getDetectorParameters(), m_endX, m_mass, m_resolutionFunction, m_startX, m_workspace, m_wsIndex, and std::to_string().
Referenced by setMatrixWorkspace(), and setParameter().
cacheYSpaceValues() [1/2]
void Mantid::CurveFitting::Functions::ComptonProfile::cacheYSpaceValues (const HistogramData::Points & tseconds, const Algorithms::DetectorParams & detpar) virtual
Pre-calculate the Y-space values.
Parameters
tseconds A vector containing the time-of-flight values in seconds
detpar Structure containing detector parameters
Reimplemented in Mantid::CurveFitting::Functions::GramCharlierComptonProfile.
Definition at line 114 of file ComptonProfile.cpp.
References Mantid::CurveFitting::Algorithms::ConvertToYSpace::calculateY(), Mantid::PhysicalConstants::E_mev_toNeutronWavenumberSq, Mantid::CurveFitting::Algorithms::DetectorParams::efixed, m_e0, m_mass, m_modQ, m_yspace, Mantid::PhysicalConstants::meV, and Mantid::PhysicalConstants::NeutronMass.
cacheYSpaceValues() [2/2]
void Mantid::CurveFitting::Functions::ComptonProfile::cacheYSpaceValues (const HistogramData::Points & tseconds, const Algorithms::DetectorParams & detpar, const ResolutionParams & respar)
Pre-calculate the Y-space values with specified resolution parameters.
Definition at line 103 of file ComptonProfile.cpp.
References cacheYSpaceValues(), m_mass, and m_resolutionFunction.
Referenced by buildCaches(), Mantid::CurveFitting::Functions::GramCharlierComptonProfile::cacheYSpaceValues(), and cacheYSpaceValues().
declareParameters()
void Mantid::CurveFitting::Functions::ComptonProfile::declareParameters () override protected virtual
Declare parameters that will never participate in the fit.
Reimplemented from Mantid::API::IFunction.
Reimplemented in Mantid::CurveFitting::Functions::GaussianComptonProfile, Mantid::CurveFitting::Functions::GramCharlierComptonProfile, and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile.
Definition at line 137 of file ComptonProfile.cpp.
References Mantid::API::ParamFunction::declareParameter().
Referenced by Mantid::CurveFitting::Functions::GaussianComptonProfile::declareParameters(), Mantid::CurveFitting::Functions::GramCharlierComptonProfile::declareParameters(), and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile::declareParameters().
disableLogging()
void Mantid::CurveFitting::Functions::ComptonProfile::disableLogging () inline
Turn off logger.
Definition at line 56 of file ComptonProfile.h.
e0()
const std::vector< double > & Mantid::CurveFitting::Functions::ComptonProfile::e0 () const inline protected
Access e0 values.
Definition at line 84 of file ComptonProfile.h.
Referenced by Mantid::CurveFitting::Functions::GramCharlierComptonProfile::convoluteVoigt(), and Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile().
fillConstraintMatrix()
virtual size_t Mantid::CurveFitting::Functions::ComptonProfile::fillConstraintMatrix (Kernel::DblMatrix & cmatrix, const size_t start, const HistogramData::HistogramE & errors) const pure virtual
Fill the appropriate columns of the given matrix with the values of the mass profile.
Implemented in Mantid::CurveFitting::Functions::GaussianComptonProfile, Mantid::CurveFitting::Functions::GramCharlierComptonProfile, and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile.
function1D()
void Mantid::CurveFitting::Functions::ComptonProfile::function1D (double * out, const double * xValues, const size_t nData) const override virtual
Calculates the value of the function for each x value and stores in the given output array.
Calculate the function
Parameters
out An array of size nData to store the results
xValues The input X data array of size nData. It is assumed to be times in microseconds
nData The length of the out & xValues arrays
Implements Mantid::API::IFunction1D.
Definition at line 47 of file ComptonProfile.cpp.
References m_log, massProfile(), Mantid::Kernel::Logger::setEnabled(), and UNUSED_ARG.
intensityParameterIndices()
virtual std::vector< size_t > Mantid::CurveFitting::Functions::ComptonProfile::intensityParameterIndices () const pure virtual
Returns the indices of the intensity parameters.
Implemented in Mantid::CurveFitting::Functions::GaussianComptonProfile, Mantid::CurveFitting::Functions::GramCharlierComptonProfile, and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile.
mass()
double Mantid::CurveFitting::Functions::ComptonProfile::mass () const inline protected
Access the mass.
Definition at line 86 of file ComptonProfile.h.
Referenced by Mantid::CurveFitting::Functions::GramCharlierComptonProfile::convoluteVoigt(), and Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile().
massProfile()
virtual void Mantid::CurveFitting::Functions::ComptonProfile::massProfile (double * result, const size_t nData) const pure virtual
Override to calculate the value of the profile for this mass and store in the given array.
Implemented in Mantid::CurveFitting::Functions::GaussianComptonProfile, Mantid::CurveFitting::Functions::GramCharlierComptonProfile, and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile.
Referenced by function1D().
modQ()
const std::vector< double > & Mantid::CurveFitting::Functions::ComptonProfile::modQ () const inline protected
Access Q values cache.
Definition at line 82 of file ComptonProfile.h.
Referenced by Mantid::CurveFitting::Functions::GramCharlierComptonProfile::cacheYSpaceValues(), Mantid::CurveFitting::Functions::GramCharlierComptonProfile::convoluteVoigt(), Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile(), and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile::massProfile().
setMatrixWorkspace()
void Mantid::CurveFitting::Functions::ComptonProfile::setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wsIndex, double startX, double endX) override virtual
Cache a copy of the workspace pointer and pull out the parameters.
Also caches parameters from the instrument.
Parameters
workspace The workspace set as input
wsIndex A workspace index
startX Starting x-vaue (unused).
endX Ending x-vaue (unused).
Reimplemented from Mantid::API::IFunction.
Reimplemented in Mantid::CurveFitting::Functions::GramCharlierComptonProfile.
Definition at line 72 of file ComptonProfile.cpp.
References buildCaches(), m_endX, m_startX, m_workspace, m_wsIndex, and workspace.
Referenced by Mantid::CurveFitting::Functions::GramCharlierComptonProfile::setMatrixWorkspace().
setParameter() [1/2]
void Mantid::CurveFitting::Functions::ComptonProfile::setParameter (const std::string & name, const double & value, bool explicitlySet = true) inline override virtual
Set parameter by name.
Sets a new value to a parameter by name.
Parameters
name :: The name of the parameter.
value :: The new value
explicitlySet :: A boolean flagging the parameter as explicitly set (by user)
Reimplemented from Mantid::API::ParamFunction.
Definition at line 71 of file ComptonProfile.h.
References name, and value.
setParameter() [2/2]
void Mantid::CurveFitting::Functions::ComptonProfile::setParameter (size_t i, const double & value, bool explicitlySet = true) override virtual
Set i-th parameter.
Sets a new value to the i-th parameter.
Parameters
i :: The parameter index
value :: The new value
explicitlySet :: A boolean falgging the parameter as explicitly set (by user)
Reimplemented from Mantid::API::ParamFunction.
Definition at line 139 of file ComptonProfile.cpp.
References buildCaches(), m_mass, m_resolutionFunction, m_workspace, Mantid::API::ParamFunction::parameterIndex(), Mantid::API::ParamFunction::setParameter(), and value.
setUpForFit()
void Mantid::CurveFitting::Functions::ComptonProfile::setUpForFit () override virtual
Ensure the object is ready to be fitted.
Reimplemented from Mantid::API::IFunction.
Definition at line 58 of file ComptonProfile.cpp.
References m_resolutionFunction, and m_voigt.
voigtApprox()
void Mantid::CurveFitting::Functions::ComptonProfile::voigtApprox (std::vector< double > & voigt, const std::vector< double > & yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const protected
Compute Voigt function.
voigtApproxDiff()
void Mantid::CurveFitting::Functions::ComptonProfile::voigtApproxDiff (std::vector< double > & voigtDiff, const std::vector< double > & yspace, const double lorentzPos, const double lorentzAmp, const double lorentzWidth, const double gaussWidth) const protected
Compute Voigt function interpolated around the given values.
Transforms the input y coordinates using a difference if Voigt functions across the whole range.
Parameters
voigtDiff [Out] Output values (vector is expected to be of the correct size)
yspace Input y coordinates
lorentzPos LorentzPos parameter
lorentzAmp LorentzAmp parameter
lorentzWidth LorentzFWHM parameter
gaussWidth GaussianFWHM parameter
Definition at line 163 of file ComptonProfile.cpp.
References m_resolutionFunction.
Referenced by Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile().
ySpace()
const std::vector< double > & Mantid::CurveFitting::Functions::ComptonProfile::ySpace () const inline protected
Access y-values cache.
Definition at line 80 of file ComptonProfile.h.
Referenced by Mantid::CurveFitting::Functions::GramCharlierComptonProfile::cacheYSpaceValues(), Mantid::CurveFitting::Functions::GaussianComptonProfile::fillConstraintMatrix(), Mantid::CurveFitting::Functions::GramCharlierComptonProfile::fillConstraintMatrix(), Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile::fillConstraintMatrix(), Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile(), and Mantid::CurveFitting::Functions::MultivariateGaussianComptonProfile::massProfile().
Member Data Documentation
m_e0
std::vector<double> Mantid::CurveFitting::Functions::ComptonProfile::m_e0 protected
Incident energies.
Definition at line 119 of file ComptonProfile.h.
Referenced by cacheYSpaceValues().
m_endX
double Mantid::CurveFitting::Functions::ComptonProfile::m_endX protected
Definition at line 105 of file ComptonProfile.h.
Referenced by buildCaches(), and setMatrixWorkspace().
m_log
Kernel::Logger Mantid::CurveFitting::Functions::ComptonProfile::m_log mutable protected
Logger.
Definition at line 97 of file ComptonProfile.h.
Referenced by function1D().
m_mass
double Mantid::CurveFitting::Functions::ComptonProfile::m_mass protected
Atomic mass.
Definition at line 121 of file ComptonProfile.h.
Referenced by buildCaches(), cacheYSpaceValues(), cacheYSpaceValues(), and setParameter().
m_modQ
std::vector<double> Mantid::CurveFitting::Functions::ComptonProfile::m_modQ protected
Q-values.
Definition at line 117 of file ComptonProfile.h.
Referenced by cacheYSpaceValues().
m_resolutionFunction
std::shared_ptr<VesuvioResolution> Mantid::CurveFitting::Functions::ComptonProfile::m_resolutionFunction protected
Vesuvio resolution function.
Definition at line 110 of file ComptonProfile.h.
Referenced by buildCaches(), Mantid::CurveFitting::Functions::GramCharlierComptonProfile::cacheYSpaceValues(), cacheYSpaceValues(), Mantid::CurveFitting::Functions::GaussianComptonProfile::massProfile(), setParameter(), setUpForFit(), and voigtApproxDiff().
m_startX
double Mantid::CurveFitting::Functions::ComptonProfile::m_startX protected
Definition at line 104 of file ComptonProfile.h.
Referenced by buildCaches(), and setMatrixWorkspace().
m_voigt
std::shared_ptr<API::IPeakFunction> Mantid::CurveFitting::Functions::ComptonProfile::m_voigt protected
Voigt function.
Definition at line 108 of file ComptonProfile.h.
Referenced by setUpForFit().
m_workspace
std::shared_ptr<const API::MatrixWorkspace> Mantid::CurveFitting::Functions::ComptonProfile::m_workspace protected
Current workspace.
Definition at line 100 of file ComptonProfile.h.
Referenced by buildCaches(), setMatrixWorkspace(), and setParameter().
m_wsIndex
size_t Mantid::CurveFitting::Functions::ComptonProfile::m_wsIndex protected
Current workspace index, required to access instrument parameters.
Definition at line 102 of file ComptonProfile.h.
Referenced by buildCaches(), and setMatrixWorkspace().
m_yspace
std::vector<double> Mantid::CurveFitting::Functions::ComptonProfile::m_yspace protected
Y-values
Definition at line 115 of file ComptonProfile.h.
Referenced by cacheYSpaceValues().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/ComptonProfile.h
Framework/CurveFitting/src/Functions/ComptonProfile.cpp