Mantid: Mantid::WorkflowAlgorithms::SofTwoThetaTOF Class Reference
Mantid::WorkflowAlgorithms::SofTwoThetaTOF Class Reference
SofTwoThetaTOF : Convert a S(spectrum number, TOF) workspace to S(twoTheta, TOF) workspace.
#include <SofTwoThetaTOF.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
double clarifyAngleStep (API::MatrixWorkspace const &ws)
API::MatrixWorkspace_sptr convertToConstantL2 (API::MatrixWorkspace_sptr &ws)
API::MatrixWorkspace_sptr convertToTwoTheta (API::MatrixWorkspace_sptr &ws)
void exec () override
Execute the algorithm.
API::MatrixWorkspace_sptr groupByTwoTheta (API::MatrixWorkspace_sptr &ws, double const twoThetaStep)
void init () override
Initialize the algorithm's properties.
API::MatrixWorkspace_sptr maskEmptyBins (API::MatrixWorkspace_sptr &maskable, API::MatrixWorkspace_sptr &comparison)
API::MatrixWorkspace_sptr rebinToNonRagged (API::MatrixWorkspace_sptr &ws)
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
SofTwoThetaTOF : Convert a S(spectrum number, TOF) workspace to S(twoTheta, TOF) workspace.
Definition at line 17 of file SofTwoThetaTOF.h.
Member Function Documentation
category()
const std::string Mantid::WorkflowAlgorithms::SofTwoThetaTOF::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 104 of file SofTwoThetaTOF.cpp.
clarifyAngleStep()
double Mantid::WorkflowAlgorithms::SofTwoThetaTOF::clarifyAngleStep (API::MatrixWorkspace const & ws) private
Definition at line 145 of file SofTwoThetaTOF.cpp.
References Mantid::API::ExperimentInfo::constInstrumentParameters(), Mantid::Geometry::ParameterMap::getDouble(), Mantid::API::ExperimentInfo::getInstrument(), and Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty().
Referenced by exec().
convertToConstantL2()
API::MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SofTwoThetaTOF::convertToConstantL2 (API::MatrixWorkspace_sptr & ws) private
Definition at line 164 of file SofTwoThetaTOF.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by exec().
convertToTwoTheta()
API::MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SofTwoThetaTOF::convertToTwoTheta (API::MatrixWorkspace_sptr & ws) private
Definition at line 172 of file SofTwoThetaTOF.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by exec().
exec()
void Mantid::WorkflowAlgorithms::SofTwoThetaTOF::exec () override private
Execute the algorithm.
Definition at line 135 of file SofTwoThetaTOF.cpp.
References clarifyAngleStep(), convertToConstantL2(), convertToTwoTheta(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), groupByTwoTheta(), maskEmptyBins(), and rebinToNonRagged().
groupByTwoTheta()
API::MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SofTwoThetaTOF::groupByTwoTheta (API::MatrixWorkspace_sptr & ws, double const twoThetaStep) private
Definition at line 181 of file SofTwoThetaTOF.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), and Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty().
Referenced by exec().
init()
void Mantid::WorkflowAlgorithms::SofTwoThetaTOF::init () override private
Initialize the algorithm's properties.
Definition at line 114 of file SofTwoThetaTOF.cpp.
References Mantid::EMPTY_DBL(), Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::OptionalSave, and Mantid::Kernel::Direction::Output.
maskEmptyBins()
API::MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SofTwoThetaTOF::maskEmptyBins (API::MatrixWorkspace_sptr & maskable, API::MatrixWorkspace_sptr & comparison) private
Definition at line 216 of file SofTwoThetaTOF.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by exec().
name()
const std::string Mantid::WorkflowAlgorithms::SofTwoThetaTOF::name () const override
Algorithms name for identification.
See also
Algorithm::name
Definition at line 98 of file SofTwoThetaTOF.cpp.
rebinToNonRagged()
API::MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SofTwoThetaTOF::rebinToNonRagged (API::MatrixWorkspace_sptr & ws) private
Definition at line 229 of file SofTwoThetaTOF.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm().
Referenced by exec().
summary()
const std::string Mantid::WorkflowAlgorithms::SofTwoThetaTOF::summary () const override
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Definition at line 107 of file SofTwoThetaTOF.cpp.
version()
int Mantid::WorkflowAlgorithms::SofTwoThetaTOF::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 101 of file SofTwoThetaTOF.cpp.
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/SofTwoThetaTOF.h
Framework/WorkflowAlgorithms/src/SofTwoThetaTOF.cpp