Mantid: Mantid::PythonInterface::AnalysisDataServiceObserverAdapter Class Reference
Mantid::PythonInterface::AnalysisDataServiceObserverAdapter Class Reference
A wrapper class helping to export AnalysisDataServiceObserver to python.
#include <AnalysisDataServiceObserverAdapter.h>
Public Member Functions
void addHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a workspace is added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
AnalysisDataServiceObserverAdapter (const AnalysisDataServiceObserverAdapter &)=delete
AnalysisDataServiceObserverAdapter (PyObject *self)
void anyChangeHandle () override
If anyChange to the ADS occurs then this function will trigger, works by overloading this class and overriding this function.
void clearHandle () override
If the ADS is cleared, then this function will trigger, works by overloading this class and overriding this function.
void deleteHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a workspace is deleted from the ADS, then this function will trigger, works by overloading this class and overriding this function.
void groupHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a group is created/added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
void groupUpdateHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a group has a workspace added/removed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
AnalysisDataServiceObserverAdapter & operator= (const AnalysisDataServiceObserverAdapter &)=delete
void renameHandle (const std::string &wsName, const std::string &newName) override
If a workspace is renamed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
void replaceHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a workspace is replaced in the ADS, then this function will trigger, works by overloading this class and overriding this function.
void unGroupHandle (const std::string &wsName, const Workspace_sptr &ws) override
If a group is removed from the ADS, then this function will trigger, works by overloading this class and overriding this function.
Public Member Functions inherited from Mantid::API::AnalysisDataServiceObserver
AnalysisDataServiceObserver ()
void observeAdd (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is added to it.
void observeAll (bool turnOn=true)
Function will turn on/off all observers for the ADS.
void observeClear (bool turnOn=true)
Function will add/remove the observer to the ADS for when the ADS is cleared.
void observeDelete (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is deleted.
void observeGroup (bool turnOn=true)
Function will add/remove the observer to the ADS for when a group is added/created in the ADS.
void observeGroupUpdate (bool turnOn=true)
Function will add/remove the observer to the ADS for if a workspace is added to a group or removed.
void observeRename (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is renamed.
void observeReplace (bool turnOn=true)
Function will add/remove the observer to the ADS for when a workspace is replaced.
void observeUnGroup (bool turnOn=true)
Function will add/remove the observer to the ADS for when a group is removed/delete from the ADS.
virtual ~AnalysisDataServiceObserver ()
Private Member Functions
PyObject * getSelf () const
Return the PyObject that owns this wrapper, i.e. self.
Private Attributes
PyObject * m_self
Value of "self" used by python to refer to an instance of this class.
Detailed Description
A wrapper class helping to export AnalysisDataServiceObserver to python.
It provides access from the C++ side to methods defined in python on subclasses of AnalysisDataServiceObserver. This allows the virtual methods to be overriden by python subclasses.
Definition at line 22 of file AnalysisDataServiceObserverAdapter.h.
Constructor & Destructor Documentation
AnalysisDataServiceObserverAdapter() [1/2]
Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::AnalysisDataServiceObserverAdapter (PyObject * self) explicit
Definition at line 13 of file AnalysisDataServiceObserverAdapter.cpp.
AnalysisDataServiceObserverAdapter() [2/2]
Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::AnalysisDataServiceObserverAdapter (const AnalysisDataServiceObserverAdapter &) delete
Member Function Documentation
addHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::addHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a workspace is added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace added
ws Workspace_sptr; the Workspace that is added
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 24 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
anyChangeHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::anyChangeHandle () override virtual
If anyChange to the ADS occurs then this function will trigger, works by overloading this class and overriding this function.
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 16 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
clearHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::clearHandle () override virtual
If the ADS is cleared, then this function will trigger, works by overloading this class and overriding this function.
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 48 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
deleteHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::deleteHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a workspace is deleted from the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
ws Workspace_sptr; the Workspace that is deleted
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 40 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
getSelf()
PyObject * Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::getSelf () const inline private
Return the PyObject that owns this wrapper, i.e. self.
Definition at line 40 of file AnalysisDataServiceObserverAdapter.h.
References m_self.
Referenced by addHandle(), anyChangeHandle(), clearHandle(), deleteHandle(), groupHandle(), groupUpdateHandle(), renameHandle(), replaceHandle(), and unGroupHandle().
groupHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::groupHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a group is created/added to the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
ws Workspace_sptr; the WorkspaceGroup that was added/created
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 64 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
groupUpdateHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::groupUpdateHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a group has a workspace added/removed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
ws Workspace_sptr; the WorkspaceGroup that was updated
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 80 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
operator=()
AnalysisDataServiceObserverAdapter & Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::operator= (const AnalysisDataServiceObserverAdapter &) delete
renameHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::renameHandle (const std::string & wsName, const std::string & newName) override virtual
If a workspace is renamed in the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
newName std::string; the new name of the workspace
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 56 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
replaceHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::replaceHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a workspace is replaced in the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace replacing
ws Workspace_sptr; the Workspace that is replacing
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 32 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
unGroupHandle()
void Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::unGroupHandle (const std::string & wsName, const Workspace_sptr & ws) override virtual
If a group is removed from the ADS, then this function will trigger, works by overloading this class and overriding this function.
Parameters
wsName std::string; the name of the workspace
ws Workspace_sptr; the WorkspaceGroup that was ungrouped
Reimplemented from Mantid::API::AnalysisDataServiceObserver.
Definition at line 72 of file AnalysisDataServiceObserverAdapter.cpp.
References getSelf().
Member Data Documentation
m_self
PyObject* Mantid::PythonInterface::AnalysisDataServiceObserverAdapter::m_self private
Value of "self" used by python to refer to an instance of this class.
Definition at line 42 of file AnalysisDataServiceObserverAdapter.h.
The documentation for this class was generated from the following files:
Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/AnalysisDataServiceObserverAdapter.h
Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataServiceObserverAdapter.cpp