Mantid: AlgorithmHistoryWindow Class Reference
AlgorithmHistoryWindow Class Reference
#include <AlgorithmHistoryWindow.h>
Public Slots
void copytoClipboard ()
void doRoll (int index)
void doUnroll (const std::vector< int > &unrollIndicies)
void unrollAll (int state)
void updateAll (const Mantid::API::AlgorithmHistory_const_sptr &algHistmakeory)
void writeToScriptFile ()
Signals
void updateAlgorithmHistoryWindow (QString algName)
Public Member Functions
AlgorithmHistoryWindow (QWidget *parent, const QString &workspaceName)
AlgorithmHistoryWindow (QWidget *parent, const std::shared_ptr< const Mantid::API::Workspace > &)
void closeEvent (QCloseEvent *ce) override
~AlgorithmHistoryWindow () override
Private Member Functions
AlgHistoryProperties * createAlgHistoryPropWindow ()
AlgEnvHistoryGrpBox * createEnvHistGrpBox (const Mantid::Kernel::EnvironmentHistory &envHistory)
AlgExecSummaryGrpBox * createExecSummaryGrpBox ()
QFileDialog * createScriptDialog (const QString &algName)
std::string getScriptVersionMode ()
Used by the save script to clipboard/file buttons to select which versioning.
void updateAlgHistoryProperties (const Mantid::API::AlgorithmHistory_const_sptr &algHistory)
void updateExecSummaryGrpBox (const Mantid::API::AlgorithmHistory_const_sptr &algHistory)
Private Attributes
const Mantid::API::WorkspaceHistory & m_algHist
AlgEnvHistoryGrpBox * m_envHistGrpBox
AlgExecSummaryGrpBox * m_execSumGrpBox
AlgHistoryTreeWidget * m_Historytree
AlgHistoryProperties * m_histPropWindow
QPushButton * m_scriptButtonClipboard
QPushButton * m_scriptButtonFile
QComboBox * m_scriptComboMode
QLabel * m_scriptVersionLabel
QCheckBox * m_unrollAllHistoryCheckbox
std::shared_ptr< Mantid::API::HistoryView > m_view
QString m_wsName
Detailed Description
Definition at line 134 of file AlgorithmHistoryWindow.h.
Constructor & Destructor Documentation
AlgorithmHistoryWindow() [1/2]
AlgorithmHistoryWindow::AlgorithmHistoryWindow (QWidget * parent, const std::shared_ptr< const Mantid::API::Workspace > & wsptr)
Definition at line 200 of file AlgorithmHistoryWindow.cpp.
References copytoClipboard(), createAlgHistoryPropWindow(), createEnvHistGrpBox(), createExecSummaryGrpBox(), doRoll(), doUnroll(), Mantid::API::WorkspaceHistory::empty(), m_algHist, m_envHistGrpBox, m_execSumGrpBox, m_Historytree, AlgHistoryProperties::m_histpropTree, m_histPropWindow, m_scriptButtonClipboard, m_scriptButtonFile, m_scriptComboMode, m_scriptVersionLabel, m_unrollAllHistoryCheckbox, AlgHistoryTreeWidget::populateAlgHistoryTreeWidget(), unrollAll(), updateAlgorithmHistoryWindow(), updateAll(), and writeToScriptFile().
AlgorithmHistoryWindow() [2/2]
AlgorithmHistoryWindow::AlgorithmHistoryWindow (QWidget * parent, const QString & workspaceName)
Definition at line 304 of file AlgorithmHistoryWindow.cpp.
~AlgorithmHistoryWindow()
AlgorithmHistoryWindow::~AlgorithmHistoryWindow () override
Definition at line 309 of file AlgorithmHistoryWindow.cpp.
References m_envHistGrpBox, m_execSumGrpBox, m_Historytree, and m_histPropWindow.
Member Function Documentation
closeEvent()
void AlgorithmHistoryWindow::closeEvent (QCloseEvent * ce) override
Definition at line 330 of file AlgorithmHistoryWindow.cpp.
copytoClipboard
void AlgorithmHistoryWindow::copytoClipboard () slot
Definition at line 471 of file AlgorithmHistoryWindow.cpp.
References Mantid::API::ScriptBuilder::build(), getScriptVersionMode(), and m_view.
Referenced by AlgorithmHistoryWindow().
createAlgHistoryPropWindow()
AlgHistoryProperties * AlgorithmHistoryWindow::createAlgHistoryPropWindow () private
Definition at line 364 of file AlgorithmHistoryWindow.cpp.
References AlgHistoryProperties::displayAlgHistoryProperties(), Mantid::API::WorkspaceHistory::getAlgorithmHistories(), and m_algHist.
Referenced by AlgorithmHistoryWindow().
createEnvHistGrpBox()
AlgEnvHistoryGrpBox * AlgorithmHistoryWindow::createEnvHistGrpBox (const Mantid::Kernel::EnvironmentHistory & envHistory) private
Definition at line 354 of file AlgorithmHistoryWindow.cpp.
References AlgEnvHistoryGrpBox::fillEnvHistoryGroupBox().
Referenced by AlgorithmHistoryWindow().
createExecSummaryGrpBox()
AlgExecSummaryGrpBox * AlgorithmHistoryWindow::createExecSummaryGrpBox () private
Definition at line 335 of file AlgorithmHistoryWindow.cpp.
References Mantid::API::WorkspaceHistory::getAlgorithmHistory(), m_algHist, AlgExecSummaryGrpBox::setData(), and Mantid::API::WorkspaceHistory::size().
Referenced by AlgorithmHistoryWindow().
createScriptDialog()
QFileDialog * AlgorithmHistoryWindow::createScriptDialog (const QString & algName) private
doRoll
void AlgorithmHistoryWindow::doRoll (int index) slot
Definition at line 490 of file AlgorithmHistoryWindow.cpp.
References index, and m_view.
Referenced by AlgorithmHistoryWindow().
doUnroll
void AlgorithmHistoryWindow::doUnroll (const std::vector< int > & unrollIndicies) slot
Definition at line 484 of file AlgorithmHistoryWindow.cpp.
References m_view.
Referenced by AlgorithmHistoryWindow().
getScriptVersionMode()
std::string AlgorithmHistoryWindow::getScriptVersionMode () private
Used by the save script to clipboard/file buttons to select which versioning.
Definition at line 388 of file AlgorithmHistoryWindow.cpp.
References m_scriptComboMode.
Referenced by copytoClipboard(), and writeToScriptFile().
unrollAll
void AlgorithmHistoryWindow::unrollAll (int state) slot
Definition at line 492 of file AlgorithmHistoryWindow.cpp.
References m_Historytree.
Referenced by AlgorithmHistoryWindow().
updateAlgHistoryProperties()
void AlgorithmHistoryWindow::updateAlgHistoryProperties (const Mantid::API::AlgorithmHistory_const_sptr & algHistory) private
Definition at line 454 of file AlgorithmHistoryWindow.cpp.
References AlgHistoryProperties::clearData(), AlgHistoryProperties::displayAlgHistoryProperties(), m_histPropWindow, and AlgHistoryProperties::setAlgProperties().
Referenced by updateAll().
updateAlgorithmHistoryWindow
void AlgorithmHistoryWindow::updateAlgorithmHistoryWindow (QString algName) signal
Referenced by AlgorithmHistoryWindow().
updateAll
void AlgorithmHistoryWindow::updateAll (const Mantid::API::AlgorithmHistory_const_sptr & algHistmakeory) slot
Definition at line 449 of file AlgorithmHistoryWindow.cpp.
References updateAlgHistoryProperties(), and updateExecSummaryGrpBox().
Referenced by AlgorithmHistoryWindow().
updateExecSummaryGrpBox()
void AlgorithmHistoryWindow::updateExecSummaryGrpBox (const Mantid::API::AlgorithmHistory_const_sptr & algHistory) private
Definition at line 463 of file AlgorithmHistoryWindow.cpp.
References m_execSumGrpBox, and AlgExecSummaryGrpBox::setData().
Referenced by updateAll().
writeToScriptFile
void AlgorithmHistoryWindow::writeToScriptFile () slot
Definition at line 403 of file AlgorithmHistoryWindow.cpp.
References Mantid::API::ScriptBuilder::build(), getScriptVersionMode(), Mantid::Kernel::SingletonHolder< T >::Instance(), and m_view.
Referenced by AlgorithmHistoryWindow().
Member Data Documentation
m_algHist
const Mantid::API::WorkspaceHistory& AlgorithmHistoryWindow::m_algHist private
Definition at line 167 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), createAlgHistoryPropWindow(), and createExecSummaryGrpBox().
m_envHistGrpBox
AlgEnvHistoryGrpBox* AlgorithmHistoryWindow::m_envHistGrpBox private
Definition at line 176 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), and ~AlgorithmHistoryWindow().
m_execSumGrpBox
AlgExecSummaryGrpBox* AlgorithmHistoryWindow::m_execSumGrpBox private
Definition at line 175 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), updateExecSummaryGrpBox(), and ~AlgorithmHistoryWindow().
m_Historytree
AlgHistoryTreeWidget* AlgorithmHistoryWindow::m_Historytree private
Definition at line 173 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), unrollAll(), and ~AlgorithmHistoryWindow().
m_histPropWindow
AlgHistoryProperties* AlgorithmHistoryWindow::m_histPropWindow private
Definition at line 174 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), updateAlgHistoryProperties(), and ~AlgorithmHistoryWindow().
m_scriptButtonClipboard
QPushButton* AlgorithmHistoryWindow::m_scriptButtonClipboard private
Definition at line 172 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow().
m_scriptButtonFile
QPushButton* AlgorithmHistoryWindow::m_scriptButtonFile private
Definition at line 171 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow().
m_scriptComboMode
QComboBox* AlgorithmHistoryWindow::m_scriptComboMode private
Definition at line 169 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow(), and getScriptVersionMode().
m_scriptVersionLabel
QLabel* AlgorithmHistoryWindow::m_scriptVersionLabel private
Definition at line 168 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow().
m_unrollAllHistoryCheckbox
QCheckBox* AlgorithmHistoryWindow::m_unrollAllHistoryCheckbox private
Definition at line 170 of file AlgorithmHistoryWindow.h.
Referenced by AlgorithmHistoryWindow().
m_view
std::shared_ptr<Mantid::API::HistoryView> AlgorithmHistoryWindow::m_view private
Definition at line 178 of file AlgorithmHistoryWindow.h.
Referenced by copytoClipboard(), doRoll(), doUnroll(), and writeToScriptFile().
m_wsName
QString AlgorithmHistoryWindow::m_wsName private
Definition at line 177 of file AlgorithmHistoryWindow.h.
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmHistoryWindow.h
qt/widgets/common/src/AlgorithmHistoryWindow.cpp