Mantid: ICat4::ns1__getEntityNamesResponse Class Reference
ICat4::ns1__getEntityNamesResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__getEntityNamesResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< std::string > return_
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 674 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__getEntityNamesResponse()
ICat4::ns1__getEntityNamesResponse::ns1__getEntityNamesResponse () inline
Definition at line 690 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__getEntityNamesResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20211 of file ICat4C.cpp.
References ICat4::soap_default_std__vectorTemplateOfstd__string().
Referenced by ICat4::ICATPortBindingProxy::getEntityNames(), ICat4::soap_in_ns1__getEntityNamesResponse(), ICat4::soap_new_req_ns1__getEntityNamesResponse(), and ICat4::soap_new_set_ns1__getEntityNamesResponse().
soap_get()
void * ICat4::ns1__getEntityNamesResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20304 of file ICat4C.cpp.
References ICat4::soap_get_ns1__getEntityNamesResponse().
Referenced by ICat4::ICATPortBindingProxy::getEntityNames().
soap_in()
void * ICat4::ns1__getEntityNamesResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20240 of file ICat4C.cpp.
References ICat4::soap_in_ns1__getEntityNamesResponse().
Referenced by ICat4::soap_in_ns1__getEntityNamesResponse().
soap_out()
int ICat4::ns1__getEntityNamesResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20225 of file ICat4C.cpp.
References ICat4::soap_out_ns1__getEntityNamesResponse().
soap_put()
int ICat4::ns1__getEntityNamesResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20297 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__getEntityNamesResponse.
soap_serialize()
void ICat4::ns1__getEntityNamesResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20217 of file ICat4C.cpp.
References ICat4::soap_serialize_std__vectorTemplateOfstd__string().
soap_type()
int ICat4::ns1__getEntityNamesResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 683 of file ICat4Stub.h.
Member Data Documentation
return_
std::vector<std::string> ICat4::ns1__getEntityNamesResponse::return_
Definition at line 676 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp