Mantid: Mantid::DataObjects Namespace Reference
Mantid::DataObjects Namespace Reference
Namespaces
namespace detail
Factory methods for creating MatrixWorkspaces.
namespace FractionalRebinning
FractionalRebinning helper functionality, used by the Rebin2D algorithm.
namespace MDEventsTestHelper
Set of helper methods for testing MDEventWorkspace things.
Classes
class AffineMatrixParameter
Type to wrap an affine matrix and allow serialization via xml.
class AffineMatrixParameterParser
Parser for a parameter of type affinematrixparameter.
class BasePeak
Structure describing a single-crystal peak.
class BinaryOperator
An SpecialWorkspace2D is a specialized Workspace2D where the Y value at each pixel will be used for a special meaning.
class BoxControllerNeXusIO
The class responsible for saving events into nexus file using generic box controller interface Expected to provide thread-safe file access.
class CalculateReflectometry
Provides a common interface to Reflectometry Transform calculators.
class CalculateReflectometryKiKf
class CalculateReflectometryKiKf: Calculation type for converting to ki or kf given a theta value (in degrees) and a wavelength
class CalculateReflectometryP
class CalculateReflectometryP: p-type transformation calculator
class CalculateReflectometryQxQz
Converts from inputs of wavelength, incident theta and final theta to Qx and Qz for reflectometry experiments.
struct comparePulseTimeTOFDelta
class CoordTransformAffine
Generic class to transform from M input dimensions to N output dimensions.
class CoordTransformAffineParser
A parser for processing coordinate transform xml.
class CoordTransformAligned
Unique type declaration for which dimensions are used in the input workspace.
class CoordTransformDistance
Unique CoordCenterVectorParam type declaration for ndimensional coordinate centers.
class CoordTransformDistanceParser
A parser for processing coordinate transform xml.
struct DetectorAngularCache
Simple container for porting detector angular information.
struct EventAccessor
Structure to mark the classes, which can switch the "physical" meaning of the union used in MDLeanEvent to store coordinates or index.
class EventList
A class for holding :
class EventSortingTask
Task for sorting an event list.
class EventWorkspace
This class is intended to fulfill the design specified in <https://github.com/mantidproject/documents/tree/master/Design/Event WorkspaceDetailed Design Document.doc>
struct EventWorkspaceHelpers
A collection of functions that help for EventWorkspaces.
class EventWorkspaceMRU
This is a container for the MRU (most-recently-used) list of generated histograms.
class FakeMD
Provides a helper class to add fake data to an MD workspace.
struct FindBin
class GroupingWorkspace
A GroupingWorkspace is a subclass of Workspace2D where each spectrum has a single number entry, the value of which signifies to which group that workspace index belongs.
class Histogram1D
1D histogram implementation.
struct IF
struct IF< MDLeanEvent< nd >, nd >
struct IF_EVENT
struct IF_EVENT< MDLeanEvent< nd >, nd >
class LeanElasticPeak
Structure describing a single-crystal peak.
class LeanElasticPeaksWorkspace
The class LeanElasticPeaksWorkspace stores information about a set of SCD lean peaks.
class LOOP
MDEventFactory : collection of methods to create MDLeanEvent* instances, by specifying the number of dimensions as a parameter.
class LOOP< 0 >
class MaskWorkspace
class MDBin
MDBin : Class describing a single bin in a dense, Multidimensional histogram.
class MDBox
Templated class for a multi-dimensional event "box".
class MDBoxBase
Templated super-class of a multi-dimensional event "box".
class MDBoxFlatTree
The class responsible for saving/loading MD boxes structure to/from HDD and for flattening/restoring the interconnected box structure (customized linked list) of MD workspace.
class MDBoxIterator
MDBoxIterator: iterate through MDBoxBase hierarchy down to a given maximum depth.
class MDBoxSaveable
Two classes responsible for implementing methods which automatically save/load MDBox in conjuction with DiskBuffer One class responsible for saving events into nexus and another one – for identifying the data positions in a file in conjuction with DB.
class MDDimensionStats
A simple class holding some statistics on the distribution of events in a particular dimension.
class MDEvent
Templated class holding data about a neutron detection event in N-dimensions (for example, Qx, Qy, Qz, E).
class MDEventFactory
class MDEventInserter
MDEventInserter : Helper class that provides a generic interface for adding events to an MDWorkspace without knowing whether the workspace is storing MDLeanEvents or full MDEvents.
class MDEventWorkspace
Templated class for the multi-dimensional event workspace.
class MDFramesToSpecialCoordinateSystem
MDFrameFromMDWorkspace: Each dimension of the MDWorkspace contains an MDFrame.
class MDGridBox
Templated class for a GRIDDED multi-dimensional event "box".
class MDHistoWorkspace
MDHistoWorkspace:
class MDHistoWorkspaceIterator
An implementation of IMDIterator that iterates through a MDHistoWorkspace.
class MDLeanEvent
Templated class holding data about a neutron detection event in N-dimensions (for example, Qx, Qy, Qz, E).
class MementoTableWorkspace
Variation on the TableWorkspace with a set of pre-defined columns used to store diffs on Workspaces.
class NoShape
PeakShapeNone : No peak shape.
struct NullDeleter
class OffsetsWorkspace
An OffsetsWorkspace is a specialized Workspace2D where the Y value at each pixel is the offset to be used for correcting calculations.
class Peak
Structure describing a single-crystal peak.
class PeakColumn
PeakColumn : a Column sub-class used to display peak information as a TableWorkspace.
class PeakComparator
Comparator class for sorting peaks by one or more criteria.
class PeakNoShapeFactory
PeakNoShapeFactory : Factory method for types of NoShape.
class PeakShapeBase
PeakShapeBase : Base class for concrete PeakShapes containing common code.
class PeakShapeDetectorBin
PeakShapeDetectorBin : PeakShape representing detector ids and integration limits of a peak.
class PeakShapeDetectorBinFactory
PeakShapeDetectorBinFactory : Factory for DetectorBin peak shapes for de-serializing from JSON.
class PeakShapeEllipsoid
PeakShapeEllipsoid : PeakShape representing a 3D ellipsoid.
class PeakShapeEllipsoidFactory
PeakShapeEllipsoidFactory : Create ellipsoid peak shapes.
class PeakShapeFactory
PeakShapeFactory : Factory for creating peak shapes.
class PeakShapeSpherical
PeakShapeSpherical : PeakShape for a spherical peak.
class PeakShapeSphericalFactory
PeakShapeSphericalFactory : Factory for spherical peak shapes for de-serializing from JSON.
class PeaksWorkspace
The class PeaksWorkspace stores information about a set of SCD peaks.
class RebinnedOutput
RebinnedOutput.
class ReflectometryTransform
ReflectometryMDTransform : Base type for reflectometry transforms to MDWorkspaces.
class ScanningWorkspaceBuilder
ScanningWorkspaceBuilder : This is a helper class to make it easy to build a scanning workspace (a workspace with moving detectors), where all the information about the scan is known in advance.
class SkipMaskedBins
Policy that indicates skipping of masked bins.
class SkipNothing
Policy that indicates no skipping should be applied.
class SkippingPolicy
SkippingPolicy : Policy types for skipping in MDiterators.
class SpecialWorkspace2D
class SplittersWorkspace
SplittersWorkspace : A TableWorkspace to contain TimeSplitters.
class TableColumn
Class TableColumn implements abstract class Column for any copyable data type.
class TableColumn_ptr
Shared pointer to a column with automatic type cast and data type check.
class TableColumn_ptr< bool >
Special case of bool.
class TableWorkspace
TableWorkspace is an implementation of Workspace in which the data are organised in columns of same size.
class TableWorkspaceNotEmptyValidator
A validator which checks that the table workspace is not empty.
class TableWorkspaceValidator
An interface for those validators that require the MatrixWorkspace interface.
class TimeSplitter
class TypeWithMarker
This little class holds data and an index marker that is used for uniqueness.
class VectorColumn
VectorColumn : table column type capable of storing vectors of primitive types.
class WeightedEvent
Info about a single neutron detection event, including a weight and error value:
class WeightedEventNoTime
Info about a single neutron detection event, including a weight and error value, but excluding the pulsetime to save memory:
class Workspace2D
Concrete workspace implementation.
class WorkspaceSingleValue
Concrete workspace implementation.
Typedefs
using AffineMatrixType = Mantid::Kernel::Matrix< coord_t >
Convenience typedef for a specific matrix type.
using EventWorkspace_const_sptr = std::shared_ptr< const EventWorkspace >
shared pointer to a const Workspace2D
using EventWorkspace_const_uptr = std::unique_ptr< const EventWorkspace >
unique pointer to Mantid::DataObjects::EventWorkspace (const version)
using EventWorkspace_sptr = std::shared_ptr< EventWorkspace >
shared pointer to the EventWorkspace class
using EventWorkspace_uptr = std::unique_ptr< EventWorkspace >
unique pointer to Mantid::DataObjects::EventWorkspace
using GroupingWorkspace_const_sptr = std::shared_ptr< const GroupingWorkspace >
shared pointer to a const GroupingWorkspace
using GroupingWorkspace_sptr = std::shared_ptr< GroupingWorkspace >
shared pointer to the GroupingWorkspace class
using LeanElasticPeaksWorkspace_const_sptr = std::shared_ptr< const LeanElasticPeaksWorkspace >
Typedef for a shared pointer to a const peaks workspace.
using LeanElasticPeaksWorkspace_sptr = std::shared_ptr< LeanElasticPeaksWorkspace >
Typedef for a shared pointer to a peaks workspace.
using MaskWorkspace_const_sptr = std::shared_ptr< const MaskWorkspace >
shared pointer to a const MaskWorkspace
using MaskWorkspace_sptr = std::shared_ptr< MaskWorkspace >
shared pointer to the MaskWorkspace class
using MDBin1 = MDBin< MDEvent< 1 >, 1 >
Typedef for a MDBin with 1 dimension.
using MDBin1Lean = MDBin< MDLeanEvent< 1 >, 1 >
Typedef for a MDBin with 1 dimension.
using MDBin2 = MDBin< MDEvent< 2 >, 2 >
Typedef for a MDBin with 2 dimensions.
using MDBin2Lean = MDBin< MDLeanEvent< 2 >, 2 >
Typedef for a MDBin with 2 dimensions.
using MDBin3 = MDBin< MDEvent< 3 >, 3 >
Typedef for a MDBin with 3 dimensions.
using MDBin3Lean = MDBin< MDLeanEvent< 3 >, 3 >
Typedef for a MDBin with 3 dimensions.
using MDBin4 = MDBin< MDEvent< 4 >, 4 >
Typedef for a MDBin with 4 dimensions.
using MDBin4Lean = MDBin< MDLeanEvent< 4 >, 4 >
Typedef for a MDBin with 4 dimensions.
using MDBin5 = MDBin< MDEvent< 5 >, 5 >
Typedef for a MDBin with 5 dimensions.
using MDBin5Lean = MDBin< MDLeanEvent< 5 >, 5 >
Typedef for a MDBin with 5 dimensions.
using MDBin6 = MDBin< MDEvent< 6 >, 6 >
Typedef for a MDBin with 6 dimensions.
using MDBin6Lean = MDBin< MDLeanEvent< 6 >, 6 >
Typedef for a MDBin with 6 dimensions.
using MDBin7 = MDBin< MDEvent< 7 >, 7 >
Typedef for a MDBin with 7 dimensions.
using MDBin7Lean = MDBin< MDLeanEvent< 7 >, 7 >
Typedef for a MDBin with 7 dimensions.
using MDBin8 = MDBin< MDEvent< 8 >, 8 >
Typedef for a MDBin with 8 dimensions.
using MDBin8Lean = MDBin< MDLeanEvent< 8 >, 8 >
Typedef for a MDBin with 8 dimensions.
using MDBin9 = MDBin< MDEvent< 9 >, 9 >
Typedef for a MDBin with 9 dimensions.
using MDBin9Lean = MDBin< MDLeanEvent< 9 >, 9 >
Typedef for a MDBin with 9 dimensions.
using MDBox1 = MDBox< MDEvent< 1 >, 1 >
Typedef for a MDBox with 1 dimension.
using MDBox1Lean = MDBox< MDLeanEvent< 1 >, 1 >
Typedef for a MDBox with 1 dimension.
using MDBox2 = MDBox< MDEvent< 2 >, 2 >
Typedef for a MDBox with 2 dimensions.
using MDBox2Lean = MDBox< MDLeanEvent< 2 >, 2 >
Typedef for a MDBox with 2 dimensions.
using MDBox3 = MDBox< MDEvent< 3 >, 3 >
Typedef for a MDBox with 3 dimensions.
using MDBox3Lean = MDBox< MDLeanEvent< 3 >, 3 >
Typedef for a MDBox with 3 dimensions.
using MDBox4 = MDBox< MDEvent< 4 >, 4 >
Typedef for a MDBox with 4 dimensions.
using MDBox4Lean = MDBox< MDLeanEvent< 4 >, 4 >
Typedef for a MDBox with 4 dimensions.
using MDBox5 = MDBox< MDEvent< 5 >, 5 >
Typedef for a MDBox with 5 dimensions.
using MDBox5Lean = MDBox< MDLeanEvent< 5 >, 5 >
Typedef for a MDBox with 5 dimensions.
using MDBox6 = MDBox< MDEvent< 6 >, 6 >
Typedef for a MDBox with 6 dimensions.
using MDBox6Lean = MDBox< MDLeanEvent< 6 >, 6 >
Typedef for a MDBox with 6 dimensions.
using MDBox7 = MDBox< MDEvent< 7 >, 7 >
Typedef for a MDBox with 7 dimensions.
using MDBox7Lean = MDBox< MDLeanEvent< 7 >, 7 >
Typedef for a MDBox with 7 dimensions.
using MDBox8 = MDBox< MDEvent< 8 >, 8 >
Typedef for a MDBox with 8 dimensions.
using MDBox8Lean = MDBox< MDLeanEvent< 8 >, 8 >
Typedef for a MDBox with 8 dimensions.
using MDBox9 = MDBox< MDEvent< 9 >, 9 >
Typedef for a MDBox with 9 dimensions.
using MDBox9Lean = MDBox< MDLeanEvent< 9 >, 9 >
Typedef for a MDBox with 9 dimensions.
using MDBoxBase1 = MDBoxBase< MDEvent< 1 >, 1 >
Typedef for a MDBoxBase with 1 dimension.
using MDBoxBase1Lean = MDBoxBase< MDLeanEvent< 1 >, 1 >
Typedef for a MDBoxBase with 1 dimension.
using MDBoxBase2 = MDBoxBase< MDEvent< 2 >, 2 >
Typedef for a MDBoxBase with 2 dimensions.
using MDBoxBase2Lean = MDBoxBase< MDLeanEvent< 2 >, 2 >
Typedef for a MDBoxBase with 2 dimensions.
using MDBoxBase3 = MDBoxBase< MDEvent< 3 >, 3 >
Typedef for a MDBoxBase with 3 dimensions.
using MDBoxBase3Lean = MDBoxBase< MDLeanEvent< 3 >, 3 >
Typedef for a MDBoxBase with 3 dimensions.
using MDBoxBase4 = MDBoxBase< MDEvent< 4 >, 4 >
Typedef for a MDBoxBase with 4 dimensions.
using MDBoxBase4Lean = MDBoxBase< MDLeanEvent< 4 >, 4 >
Typedef for a MDBoxBase with 4 dimensions.
using MDBoxBase5 = MDBoxBase< MDEvent< 5 >, 5 >
Typedef for a MDBoxBase with 5 dimensions.
using MDBoxBase5Lean = MDBoxBase< MDLeanEvent< 5 >, 5 >
Typedef for a MDBoxBase with 5 dimensions.
using MDBoxBase6 = MDBoxBase< MDEvent< 6 >, 6 >
Typedef for a MDBoxBase with 6 dimensions.
using MDBoxBase6Lean = MDBoxBase< MDLeanEvent< 6 >, 6 >
Typedef for a MDBoxBase with 6 dimensions.
using MDBoxBase7 = MDBoxBase< MDEvent< 7 >, 7 >
Typedef for a MDBoxBase with 7 dimensions.
using MDBoxBase7Lean = MDBoxBase< MDLeanEvent< 7 >, 7 >
Typedef for a MDBoxBase with 7 dimensions.
using MDBoxBase8 = MDBoxBase< MDEvent< 8 >, 8 >
Typedef for a MDBoxBase with 8 dimensions.
using MDBoxBase8Lean = MDBoxBase< MDLeanEvent< 8 >, 8 >
Typedef for a MDBoxBase with 8 dimensions.
using MDBoxBase9 = MDBoxBase< MDEvent< 9 >, 9 >
Typedef for a MDBoxBase with 9 dimensions.
using MDBoxBase9Lean = MDBoxBase< MDLeanEvent< 9 >, 9 >
Typedef for a MDBoxBase with 9 dimensions.
using MDEventWorkspace1 = MDEventWorkspace< MDEvent< 1 >, 1 >
Typedef for a MDEventWorkspace with 1 dimension.
using MDEventWorkspace1Lean = MDEventWorkspace< MDLeanEvent< 1 >, 1 >
Typedef for a MDEventWorkspace with 1 dimension.
using MDEventWorkspace2 = MDEventWorkspace< MDEvent< 2 >, 2 >
Typedef for a MDEventWorkspace with 2 dimensions.
using MDEventWorkspace2Lean = MDEventWorkspace< MDLeanEvent< 2 >, 2 >
Typedef for a MDEventWorkspace with 2 dimensions.
using MDEventWorkspace3 = MDEventWorkspace< MDEvent< 3 >, 3 >
Typedef for a MDEventWorkspace with 3 dimensions.
using MDEventWorkspace3Lean = MDEventWorkspace< MDLeanEvent< 3 >, 3 >
Typedef for a MDEventWorkspace with 3 dimensions.
using MDEventWorkspace4 = MDEventWorkspace< MDEvent< 4 >, 4 >
Typedef for a MDEventWorkspace with 4 dimensions.
using MDEventWorkspace4Lean = MDEventWorkspace< MDLeanEvent< 4 >, 4 >
Typedef for a MDEventWorkspace with 4 dimensions.
using MDEventWorkspace5 = MDEventWorkspace< MDEvent< 5 >, 5 >
Typedef for a MDEventWorkspace with 5 dimensions.
using MDEventWorkspace5Lean = MDEventWorkspace< MDLeanEvent< 5 >, 5 >
Typedef for a MDEventWorkspace with 5 dimensions.
using MDEventWorkspace6 = MDEventWorkspace< MDEvent< 6 >, 6 >
Typedef for a MDEventWorkspace with 6 dimensions.
using MDEventWorkspace6Lean = MDEventWorkspace< MDLeanEvent< 6 >, 6 >
Typedef for a MDEventWorkspace with 6 dimensions.
using MDEventWorkspace7 = MDEventWorkspace< MDEvent< 7 >, 7 >
Typedef for a MDEventWorkspace with 7 dimensions.
using MDEventWorkspace7Lean = MDEventWorkspace< MDLeanEvent< 7 >, 7 >
Typedef for a MDEventWorkspace with 7 dimensions.
using MDEventWorkspace8 = MDEventWorkspace< MDEvent< 8 >, 8 >
Typedef for a MDEventWorkspace with 8 dimensions.
using MDEventWorkspace8Lean = MDEventWorkspace< MDLeanEvent< 8 >, 8 >
Typedef for a MDEventWorkspace with 8 dimensions.
using MDEventWorkspace9 = MDEventWorkspace< MDEvent< 9 >, 9 >
Typedef for a MDEventWorkspace with 9 dimensions.
using MDEventWorkspace9Lean = MDEventWorkspace< MDLeanEvent< 9 >, 9 >
Typedef for a MDEventWorkspace with 9 dimensions.
template<size_t nd>
using MDEventWS = MDEventWorkspace< MDEvent< nd >, nd >
using MDExtentPair = boost::tuple< Mantid::coord_t, Mantid::coord_t >
using MDGridBox1 = MDGridBox< MDEvent< 1 >, 1 >
Typedef for a MDGridBox with 1 dimension.
using MDGridBox1Lean = MDGridBox< MDLeanEvent< 1 >, 1 >
Typedef for a MDGridBox with 1 dimension.
using MDGridBox2 = MDGridBox< MDEvent< 2 >, 2 >
Typedef for a MDGridBox with 2 dimensions.
using MDGridBox2Lean = MDGridBox< MDLeanEvent< 2 >, 2 >
Typedef for a MDGridBox with 2 dimensions.
using MDGridBox3 = MDGridBox< MDEvent< 3 >, 3 >
Typedef for a MDGridBox with 3 dimensions.
using MDGridBox3Lean = MDGridBox< MDLeanEvent< 3 >, 3 >
Typedef for a MDGridBox with 3 dimensions.
using MDGridBox4 = MDGridBox< MDEvent< 4 >, 4 >
Typedef for a MDGridBox with 4 dimensions.
using MDGridBox4Lean = MDGridBox< MDLeanEvent< 4 >, 4 >
Typedef for a MDGridBox with 4 dimensions.
using MDGridBox5 = MDGridBox< MDEvent< 5 >, 5 >
Typedef for a MDGridBox with 5 dimensions.
using MDGridBox5Lean = MDGridBox< MDLeanEvent< 5 >, 5 >
Typedef for a MDGridBox with 5 dimensions.
using MDGridBox6 = MDGridBox< MDEvent< 6 >, 6 >
Typedef for a MDGridBox with 6 dimensions.
using MDGridBox6Lean = MDGridBox< MDLeanEvent< 6 >, 6 >
Typedef for a MDGridBox with 6 dimensions.
using MDGridBox7 = MDGridBox< MDEvent< 7 >, 7 >
Typedef for a MDGridBox with 7 dimensions.
using MDGridBox7Lean = MDGridBox< MDLeanEvent< 7 >, 7 >
Typedef for a MDGridBox with 7 dimensions.
using MDGridBox8 = MDGridBox< MDEvent< 8 >, 8 >
Typedef for a MDGridBox with 8 dimensions.
using MDGridBox8Lean = MDGridBox< MDLeanEvent< 8 >, 8 >
Typedef for a MDGridBox with 8 dimensions.
using MDGridBox9 = MDGridBox< MDEvent< 9 >, 9 >
Typedef for a MDGridBox with 9 dimensions.
using MDGridBox9Lean = MDGridBox< MDLeanEvent< 9 >, 9 >
Typedef for a MDGridBox with 9 dimensions.
using MDHistoWorkspace_const_sptr = std::shared_ptr< const MDHistoWorkspace >
A shared pointer to a const MDHistoWorkspace.
using MDHistoWorkspace_sptr = std::shared_ptr< MDHistoWorkspace >
A shared pointer to a MDHistoWorkspace.
template<size_t nd>
using MDLeanEventWS = MDEventWorkspace< MDLeanEvent< nd >, nd >
using OffsetsWorkspace_const_sptr = std::shared_ptr< const OffsetsWorkspace >
shared pointer to a const OffsetsWorkspace
using OffsetsWorkspace_sptr = std::shared_ptr< OffsetsWorkspace >
shared pointer to the OffsetsWorkspace class
using Peak_uptr = std::unique_ptr< Peak >
typedef std::array< double, PEAK_ELLIPSOID_DIMS > PeakEllipsoidExtent
typedef std::array< Kernel::V3D, PEAK_ELLIPSOID_DIMS > PeakEllipsoidFrame
using PeakShapeDetectorTOF_const_sptr = std::shared_ptr< const PeakShapeDetectorBin >
using PeakShapeDetectorTOF_sptr = std::shared_ptr< PeakShapeDetectorBin >
using PeakShapeEllipsoid_const_sptr = std::shared_ptr< const PeakShapeEllipsoid >
using PeakShapeEllipsoid_sptr = std::shared_ptr< PeakShapeEllipsoid >
using PeakShapeFactory_const_sptr = std::shared_ptr< const PeakShapeFactory >
Helper typedef.
using PeakShapeFactory_sptr = std::shared_ptr< PeakShapeFactory >
Helper typedef.
using PeaksWorkspace_const_sptr = std::shared_ptr< const PeaksWorkspace >
Typedef for a shared pointer to a const peaks workspace.
using PeaksWorkspace_sptr = std::shared_ptr< PeaksWorkspace >
Typedef for a shared pointer to a peaks workspace.
using PermutationsMap = std::map< std::vector< int >, std::vector< int64_t > >
using RebinnedOutput_const_sptr = std::shared_ptr< const RebinnedOutput >
shared pointer to a const RebinnedOutput
using RebinnedOutput_sptr = std::shared_ptr< RebinnedOutput >
shared pointer to the RebinnedOutput class
using ReflectometryTransform_sptr = std::shared_ptr< ReflectometryTransform >
using SkippingPolicy_scptr = boost::scoped_ptr< SkippingPolicy >
using SpecialWorkspace2D_const_sptr = std::shared_ptr< const SpecialWorkspace2D >
shared pointer to a const SpecialWorkspace2D
using SpecialWorkspace2D_sptr = std::shared_ptr< SpecialWorkspace2D >
shared pointer to the SpecialWorkspace2D class
using SplittersWorkspace_const_sptr = std::shared_ptr< const SplittersWorkspace >
using SplittersWorkspace_sptr = std::shared_ptr< SplittersWorkspace >
using TableWorkspace_const_sptr = std::shared_ptr< const TableWorkspace >
shared pointer to Mantid::DataObjects::TableWorkspace (const version)
using TableWorkspace_const_uptr = std::unique_ptr< const TableWorkspace >
unique pointer to Mantid::DataObjects::TableWorkspace (const version)
using TableWorkspace_sptr = std::shared_ptr< TableWorkspace >
shared pointer to Mantid::DataObjects::TableWorkspace
using TableWorkspace_uptr = std::unique_ptr< TableWorkspace >
unique pointer to Mantid::DataObjects::TableWorkspace
using VecMDExtents = std::vector< MDExtentPair >
using Workspace2D_const_sptr = std::shared_ptr< const Workspace2D >
shared pointer to Mantid::DataObjects::Workspace2D (const version)
using Workspace2D_const_uptr = std::unique_ptr< const Workspace2D >
unique pointer to Mantid::DataObjects::Workspace2D (const version)
using Workspace2D_sptr = std::shared_ptr< Workspace2D >
shared pointer to Mantid::DataObjects::Workspace2D
using Workspace2D_uptr = std::unique_ptr< Workspace2D >
unique pointer to Mantid::DataObjects::Workspace2D
using WorkspaceSingleValue_const_sptr = std::shared_ptr< const WorkspaceSingleValue >
using WorkspaceSingleValue_sptr = std::shared_ptr< WorkspaceSingleValue >
shared pointer to the WorkspaceSingleValue class
Enumerations
enum EventSortType {
UNSORTED , TOF_SORT , PULSETIME_SORT , PULSETIMETOF_SORT ,
PULSETIMETOF_DELTA_SORT , TIMEATSAMPLE_SORT
}
How the event list is sorted.
Functions
bool compareEventPulseTime (const TofEvent &e1, const TofEvent &e2)
Compare two events' FRAME id, return true if e1 should be before e2.
bool compareEventPulseTimeTOF (const TofEvent &e1, const TofEvent &e2)
Compare two events' FRAME id, return true if e1 should be before e2.
template<typename FROM , typename TO >
void convertFormats (const std::vector< FROM > &inData, std::vector< TO > &outData)
Helper funcion which allows to convert one data fomat into another.
template<class T , class IndexArg , class HistArg , typename std::enable_if<!std::is_base_of< API::MatrixWorkspace, IndexArg >::value >::type * = nullptr>
std::unique_ptr< T > create (const IndexArg &indexArg, const HistArg &histArg)
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr>
std::unique_ptr< T > create (const P &parent)
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr>
std::unique_ptr< T > create (const P &parent, const HistogramData::BinEdges &binEdges)
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr>
std::unique_ptr< T > create (const P &parent, const HistogramData::Histogram &histogram)
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr>
std::unique_ptr< T > create (const P &parent, const HistogramData::Points &points)
template<class T , class P , class IndexArg , class HistArg , class = typename std::enable_if<std::is_base_of<API::MatrixWorkspace, P>::value>::type>
std::unique_ptr< T > create (const P &parent, const IndexArg &indexArg, const HistArg &histArg)
This is the create() method that all the other create() methods call.
template<class T , class IndexArg , class HistArg , typename std::enable_if<!std::is_base_of< API::MatrixWorkspace, IndexArg >::value >::type * = nullptr>
std::unique_ptr< T > create (const std::shared_ptr< const Geometry::Instrument > &instrument, const IndexArg &indexArg, const HistArg &histArg)
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr>
std::unique_ptr< T > createRagged (const P &parent)
MANTID_DATAOBJECTS_DLL void createVerticalAxis (Mantid::API::MatrixWorkspace *const ws, const MantidVec &xAxisVec, const double gradY, const double cyToUnit, const size_t nBins, const std::string &caption, const std::string &units)
Create a new y(vertical)-axis for the output workspace.
MANTID_DATAOBJECTS_DLL MantidVec createXAxis (Mantid::API::MatrixWorkspace *const ws, const double gradX, const double cxToUnit, const size_t nBins, const std::string &caption, const std::string &units)
Create a new x-axis for the output workspace.
template<class T >
static std::vector< T >::const_iterator findFirstEvent (const std::vector< T > &events, T seek_tof)
Utility function: Returns the iterator into events of the first TofEvent with tof() > seek_tof Will return events.end() if nothing is found!
template<class T >
static std::vector< T >::iterator findFirstEvent (std::vector< T > &events, T seek_tof)
Utility function: Returns the iterator into events of the first TofEvent with tof() > seek_tof Will return events.end() if nothing is found!
void getEventsFrom (const EventList &el, std::vector< TofEvent > const *&events)
DLLExport void getEventsFrom (const EventList &el, std::vector< Types::Event::TofEvent > const *&events)
DLLExport void getEventsFrom (const EventList &el, std::vector< WeightedEvent > const *&events)
DLLExport void getEventsFrom (const EventList &el, std::vector< WeightedEventNoTime > const *&events)
void getEventsFrom (EventList &el, std::vector< TofEvent > *&events)
Get the vector of events contained in an EventList; this is overloaded by event type.
DLLExport void getEventsFrom (EventList &el, std::vector< Types::Event::TofEvent > *&events)
DLLExport void getEventsFrom (EventList &el, std::vector< WeightedEvent > *&events)
Get the vector of events contained in an EventList; this is overloaded by event type.
DLLExport void getEventsFrom (EventList &el, std::vector< WeightedEventNoTime > *&events)
Get the vector of events contained in an EventList; this is overloaded by event type.
MANTID_DATAOBJECTS_DLL DetectorAngularCache initAngularCaches (const Mantid::API::MatrixWorkspace *const workspace)
Create angular caches.
ostream & operator<< (ostream &os, const WeightedEvent &event)
Output a string representation of the event to a stream.
bool pointInWorkspace (const MDHistoWorkspace *ws, const VMD &point)
template<typename T >
void saveMatrix (Mantid::Nexus::File *const file, const std::string &name, Kernel::Matrix< T > &m, NXnumtype type, const std::string &tag)
Save routine for a generic matrix.
template<typename BOXTYPE >
bool SortBoxesByID (const BOXTYPE &a, const BOXTYPE &b)
Comparator for sorting MDBoxBase'es by ID.
void swap (CoordTransformAffine &obj1, CoordTransformAffine &obj2)
template<size_t nd>
void swap (MDLeanEvent< nd > &first, MDLeanEvent< nd > &second)
template<size_t ND>
void swap (MDLeanEvent< ND > &first, MDLeanEvent< ND > &second)
Variables
const char * EventHeaders []
Mantid::Kernel::Logger g_log ("PeaksWorkspace")
Register the workspace as a type.
template class DLLExport MDBin< MDEvent< 1 >, 1 >
template class DLLExport MDBin< MDEvent< 2 >, 2 >
template class DLLExport MDBin< MDEvent< 3 >, 3 >
template class DLLExport MDBin< MDEvent< 4 >, 4 >
template class DLLExport MDBin< MDEvent< 5 >, 5 >
template class DLLExport MDBin< MDEvent< 6 >, 6 >
template class DLLExport MDBin< MDEvent< 7 >, 7 >
template class DLLExport MDBin< MDEvent< 8 >, 8 >
template class DLLExport MDBin< MDEvent< 9 >, 9 >
template class DLLExport MDBin< MDLeanEvent< 1 >, 1 >
template class DLLExport MDBin< MDLeanEvent< 2 >, 2 >
template class DLLExport MDBin< MDLeanEvent< 3 >, 3 >
template class DLLExport MDBin< MDLeanEvent< 4 >, 4 >
template class DLLExport MDBin< MDLeanEvent< 5 >, 5 >
template class DLLExport MDBin< MDLeanEvent< 6 >, 6 >
template class DLLExport MDBin< MDLeanEvent< 7 >, 7 >
template class DLLExport MDBin< MDLeanEvent< 8 >, 8 >
template class DLLExport MDBin< MDLeanEvent< 9 >, 9 >
template class DLLExport MDBox< MDEvent< 1 >, 1 >
template class DLLExport MDBox< MDEvent< 2 >, 2 >
template class DLLExport MDBox< MDEvent< 3 >, 3 >
template class DLLExport MDBox< MDEvent< 4 >, 4 >
template class DLLExport MDBox< MDEvent< 5 >, 5 >
template class DLLExport MDBox< MDEvent< 6 >, 6 >
template class DLLExport MDBox< MDEvent< 7 >, 7 >
template class DLLExport MDBox< MDEvent< 8 >, 8 >
template class DLLExport MDBox< MDEvent< 9 >, 9 >
template class DLLExport MDBox< MDLeanEvent< 1 >, 1 >
template class DLLExport MDBox< MDLeanEvent< 2 >, 2 >
template class DLLExport MDBox< MDLeanEvent< 3 >, 3 >
template class DLLExport MDBox< MDLeanEvent< 4 >, 4 >
template class DLLExport MDBox< MDLeanEvent< 5 >, 5 >
template class DLLExport MDBox< MDLeanEvent< 6 >, 6 >
template class DLLExport MDBox< MDLeanEvent< 7 >, 7 >
template class DLLExport MDBox< MDLeanEvent< 8 >, 8 >
template class DLLExport MDBox< MDLeanEvent< 9 >, 9 >
template class DLLExport MDBoxBase< MDEvent< 1 >, 1 >
template class DLLExport MDBoxBase< MDEvent< 2 >, 2 >
template class DLLExport MDBoxBase< MDEvent< 3 >, 3 >
template class DLLExport MDBoxBase< MDEvent< 4 >, 4 >
template class DLLExport MDBoxBase< MDEvent< 5 >, 5 >
template class DLLExport MDBoxBase< MDEvent< 6 >, 6 >
template class DLLExport MDBoxBase< MDEvent< 7 >, 7 >
template class DLLExport MDBoxBase< MDEvent< 8 >, 8 >
template class DLLExport MDBoxBase< MDEvent< 9 >, 9 >
template class DLLExport MDBoxBase< MDLeanEvent< 1 >, 1 >
template class DLLExport MDBoxBase< MDLeanEvent< 2 >, 2 >
template class DLLExport MDBoxBase< MDLeanEvent< 3 >, 3 >
template class DLLExport MDBoxBase< MDLeanEvent< 4 >, 4 >
template class DLLExport MDBoxBase< MDLeanEvent< 5 >, 5 >
template class DLLExport MDBoxBase< MDLeanEvent< 6 >, 6 >
template class DLLExport MDBoxBase< MDLeanEvent< 7 >, 7 >
template class DLLExport MDBoxBase< MDLeanEvent< 8 >, 8 >
template class DLLExport MDBoxBase< MDLeanEvent< 9 >, 9 >
template class DLLExport MDBoxIterator< MDEvent< 1 >, 1 >
template class DLLExport MDBoxIterator< MDEvent< 2 >, 2 >
template class DLLExport MDBoxIterator< MDEvent< 3 >, 3 >
template class DLLExport MDBoxIterator< MDEvent< 4 >, 4 >
template class DLLExport MDBoxIterator< MDEvent< 5 >, 5 >
template class DLLExport MDBoxIterator< MDEvent< 6 >, 6 >
template class DLLExport MDBoxIterator< MDEvent< 7 >, 7 >
template class DLLExport MDBoxIterator< MDEvent< 8 >, 8 >
template class DLLExport MDBoxIterator< MDEvent< 9 >, 9 >
template class DLLExport MDBoxIterator< MDLeanEvent< 1 >, 1 >
template class DLLExport MDBoxIterator< MDLeanEvent< 2 >, 2 >
template class DLLExport MDBoxIterator< MDLeanEvent< 3 >, 3 >
template class DLLExport MDBoxIterator< MDLeanEvent< 4 >, 4 >
template class DLLExport MDBoxIterator< MDLeanEvent< 5 >, 5 >
template class DLLExport MDBoxIterator< MDLeanEvent< 6 >, 6 >
template class DLLExport MDBoxIterator< MDLeanEvent< 7 >, 7 >
template class DLLExport MDBoxIterator< MDLeanEvent< 8 >, 8 >
template class DLLExport MDBoxIterator< MDLeanEvent< 9 >, 9 >
template class DLLExport MDEvent< 1 >
template class DLLExport MDEvent< 2 >
template class DLLExport MDEvent< 3 >
template class DLLExport MDEvent< 4 >
template class DLLExport MDEvent< 5 >
template class DLLExport MDEvent< 6 >
template class DLLExport MDEvent< 7 >
template class DLLExport MDEvent< 8 >
template class DLLExport MDEvent< 9 >
template class DLLExport MDEventWorkspace< MDEvent< 1 >, 1 >
template class DLLExport MDEventWorkspace< MDEvent< 2 >, 2 >
template class DLLExport MDEventWorkspace< MDEvent< 3 >, 3 >
template class DLLExport MDEventWorkspace< MDEvent< 4 >, 4 >
template class DLLExport MDEventWorkspace< MDEvent< 5 >, 5 >
template class DLLExport MDEventWorkspace< MDEvent< 6 >, 6 >
template class DLLExport MDEventWorkspace< MDEvent< 7 >, 7 >
template class DLLExport MDEventWorkspace< MDEvent< 8 >, 8 >
template class DLLExport MDEventWorkspace< MDEvent< 9 >, 9 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 1 >, 1 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 2 >, 2 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 3 >, 3 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 4 >, 4 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 5 >, 5 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 6 >, 6 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 7 >, 7 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 8 >, 8 >
template class DLLExport MDEventWorkspace< MDLeanEvent< 9 >, 9 >
template class DLLExport MDGridBox< MDEvent< 1 >, 1 >
template class DLLExport MDGridBox< MDEvent< 2 >, 2 >
template class DLLExport MDGridBox< MDEvent< 3 >, 3 >
template class DLLExport MDGridBox< MDEvent< 4 >, 4 >
template class DLLExport MDGridBox< MDEvent< 5 >, 5 >
template class DLLExport MDGridBox< MDEvent< 6 >, 6 >
template class DLLExport MDGridBox< MDEvent< 7 >, 7 >
template class DLLExport MDGridBox< MDEvent< 8 >, 8 >
template class DLLExport MDGridBox< MDEvent< 9 >, 9 >
template class DLLExport MDGridBox< MDLeanEvent< 1 >, 1 >
template class DLLExport MDGridBox< MDLeanEvent< 2 >, 2 >
template class DLLExport MDGridBox< MDLeanEvent< 3 >, 3 >
template class DLLExport MDGridBox< MDLeanEvent< 4 >, 4 >
template class DLLExport MDGridBox< MDLeanEvent< 5 >, 5 >
template class DLLExport MDGridBox< MDLeanEvent< 6 >, 6 >
template class DLLExport MDGridBox< MDLeanEvent< 7 >, 7 >
template class DLLExport MDGridBox< MDLeanEvent< 8 >, 8 >
template class DLLExport MDGridBox< MDLeanEvent< 9 >, 9 >
template class DLLExport MDLeanEvent< 1 >
template class DLLExport MDLeanEvent< 2 >
template class DLLExport MDLeanEvent< 3 >
template class DLLExport MDLeanEvent< 4 >
template class DLLExport MDLeanEvent< 5 >
template class DLLExport MDLeanEvent< 6 >
template class DLLExport MDLeanEvent< 7 >
template class DLLExport MDLeanEvent< 8 >
template class DLLExport MDLeanEvent< 9 >
constexpr size_t PEAK_ELLIPSOID_DIMS {3}
Typedef Documentation
AffineMatrixType
using Mantid::DataObjects::AffineMatrixType = typedef Mantid::Kernel::Matrix<coord_t>
Convenience typedef for a specific matrix type.
Definition at line 17 of file AffineMatrixParameter.h.
EventWorkspace_const_sptr
typedef std::shared_ptr< const EventWorkspace > Mantid::DataObjects::EventWorkspace_const_sptr
shared pointer to a const Workspace2D
shared pointer to Mantid::DataObjects::EventWorkspace (const version)
Definition at line 172 of file EventWorkspace.h.
EventWorkspace_const_uptr
using Mantid::DataObjects::EventWorkspace_const_uptr = typedef std::unique_ptr<const EventWorkspace>
unique pointer to Mantid::DataObjects::EventWorkspace (const version)
Definition at line 26 of file EventWorkspace_fwd.h.
EventWorkspace_sptr
typedef std::shared_ptr< EventWorkspace > Mantid::DataObjects::EventWorkspace_sptr
shared pointer to the EventWorkspace class
shared pointer to Mantid::DataObjects::EventWorkspace
Definition at line 170 of file EventWorkspace.h.
EventWorkspace_uptr
using Mantid::DataObjects::EventWorkspace_uptr = typedef std::unique_ptr<EventWorkspace>
unique pointer to Mantid::DataObjects::EventWorkspace
Definition at line 24 of file EventWorkspace_fwd.h.
GroupingWorkspace_const_sptr
using Mantid::DataObjects::GroupingWorkspace_const_sptr = typedef std::shared_ptr<const GroupingWorkspace>
shared pointer to a const GroupingWorkspace
Definition at line 62 of file GroupingWorkspace.h.
GroupingWorkspace_sptr
using Mantid::DataObjects::GroupingWorkspace_sptr = typedef std::shared_ptr<GroupingWorkspace>
shared pointer to the GroupingWorkspace class
Definition at line 59 of file GroupingWorkspace.h.
LeanElasticPeaksWorkspace_const_sptr
using Mantid::DataObjects::LeanElasticPeaksWorkspace_const_sptr = typedef std::shared_ptr<const LeanElasticPeaksWorkspace>
Typedef for a shared pointer to a const peaks workspace.
Definition at line 258 of file LeanElasticPeaksWorkspace.h.
LeanElasticPeaksWorkspace_sptr
using Mantid::DataObjects::LeanElasticPeaksWorkspace_sptr = typedef std::shared_ptr<LeanElasticPeaksWorkspace>
Typedef for a shared pointer to a peaks workspace.
Definition at line 255 of file LeanElasticPeaksWorkspace.h.
MaskWorkspace_const_sptr
using Mantid::DataObjects::MaskWorkspace_const_sptr = typedef std::shared_ptr<const MaskWorkspace>
shared pointer to a const MaskWorkspace
Definition at line 93 of file MaskWorkspace.h.
MaskWorkspace_sptr
using Mantid::DataObjects::MaskWorkspace_sptr = typedef std::shared_ptr<MaskWorkspace>
shared pointer to the MaskWorkspace class
Definition at line 90 of file MaskWorkspace.h.
MDBin1
using Mantid::DataObjects::MDBin1 = typedef MDBin<MDEvent<1>, 1>
Typedef for a MDBin with 1 dimension.
Definition at line 539 of file MDEventFactory.h.
MDBin1Lean
using Mantid::DataObjects::MDBin1Lean = typedef MDBin<MDLeanEvent<1>, 1>
Typedef for a MDBin with 1 dimension.
Definition at line 521 of file MDEventFactory.h.
MDBin2
using Mantid::DataObjects::MDBin2 = typedef MDBin<MDEvent<2>, 2>
Typedef for a MDBin with 2 dimensions.
Definition at line 541 of file MDEventFactory.h.
MDBin2Lean
using Mantid::DataObjects::MDBin2Lean = typedef MDBin<MDLeanEvent<2>, 2>
Typedef for a MDBin with 2 dimensions.
Definition at line 523 of file MDEventFactory.h.
MDBin3
using Mantid::DataObjects::MDBin3 = typedef MDBin<MDEvent<3>, 3>
Typedef for a MDBin with 3 dimensions.
Definition at line 543 of file MDEventFactory.h.
MDBin3Lean
using Mantid::DataObjects::MDBin3Lean = typedef MDBin<MDLeanEvent<3>, 3>
Typedef for a MDBin with 3 dimensions.
Definition at line 525 of file MDEventFactory.h.
MDBin4
using Mantid::DataObjects::MDBin4 = typedef MDBin<MDEvent<4>, 4>
Typedef for a MDBin with 4 dimensions.
Definition at line 545 of file MDEventFactory.h.
MDBin4Lean
using Mantid::DataObjects::MDBin4Lean = typedef MDBin<MDLeanEvent<4>, 4>
Typedef for a MDBin with 4 dimensions.
Definition at line 527 of file MDEventFactory.h.
MDBin5
using Mantid::DataObjects::MDBin5 = typedef MDBin<MDEvent<5>, 5>
Typedef for a MDBin with 5 dimensions.
Definition at line 547 of file MDEventFactory.h.
MDBin5Lean
using Mantid::DataObjects::MDBin5Lean = typedef MDBin<MDLeanEvent<5>, 5>
Typedef for a MDBin with 5 dimensions.
Definition at line 529 of file MDEventFactory.h.
MDBin6
using Mantid::DataObjects::MDBin6 = typedef MDBin<MDEvent<6>, 6>
Typedef for a MDBin with 6 dimensions.
Definition at line 549 of file MDEventFactory.h.
MDBin6Lean
using Mantid::DataObjects::MDBin6Lean = typedef MDBin<MDLeanEvent<6>, 6>
Typedef for a MDBin with 6 dimensions.
Definition at line 531 of file MDEventFactory.h.
MDBin7
using Mantid::DataObjects::MDBin7 = typedef MDBin<MDEvent<7>, 7>
Typedef for a MDBin with 7 dimensions.
Definition at line 551 of file MDEventFactory.h.
MDBin7Lean
using Mantid::DataObjects::MDBin7Lean = typedef MDBin<MDLeanEvent<7>, 7>
Typedef for a MDBin with 7 dimensions.
Definition at line 533 of file MDEventFactory.h.
MDBin8
using Mantid::DataObjects::MDBin8 = typedef MDBin<MDEvent<8>, 8>
Typedef for a MDBin with 8 dimensions.
Definition at line 553 of file MDEventFactory.h.
MDBin8Lean
using Mantid::DataObjects::MDBin8Lean = typedef MDBin<MDLeanEvent<8>, 8>
Typedef for a MDBin with 8 dimensions.
Definition at line 535 of file MDEventFactory.h.
MDBin9
using Mantid::DataObjects::MDBin9 = typedef MDBin<MDEvent<9>, 9>
Typedef for a MDBin with 9 dimensions.
Definition at line 555 of file MDEventFactory.h.
MDBin9Lean
using Mantid::DataObjects::MDBin9Lean = typedef MDBin<MDLeanEvent<9>, 9>
Typedef for a MDBin with 9 dimensions.
Definition at line 537 of file MDEventFactory.h.
MDBox1
using Mantid::DataObjects::MDBox1 = typedef MDBox<MDEvent<1>, 1>
Typedef for a MDBox with 1 dimension.
Definition at line 383 of file MDEventFactory.h.
MDBox1Lean
using Mantid::DataObjects::MDBox1Lean = typedef MDBox<MDLeanEvent<1>, 1>
Typedef for a MDBox with 1 dimension.
Definition at line 365 of file MDEventFactory.h.
MDBox2
using Mantid::DataObjects::MDBox2 = typedef MDBox<MDEvent<2>, 2>
Typedef for a MDBox with 2 dimensions.
Definition at line 385 of file MDEventFactory.h.
MDBox2Lean
using Mantid::DataObjects::MDBox2Lean = typedef MDBox<MDLeanEvent<2>, 2>
Typedef for a MDBox with 2 dimensions.
Definition at line 367 of file MDEventFactory.h.
MDBox3
using Mantid::DataObjects::MDBox3 = typedef MDBox<MDEvent<3>, 3>
Typedef for a MDBox with 3 dimensions.
Definition at line 387 of file MDEventFactory.h.
MDBox3Lean
using Mantid::DataObjects::MDBox3Lean = typedef MDBox<MDLeanEvent<3>, 3>
Typedef for a MDBox with 3 dimensions.
Definition at line 369 of file MDEventFactory.h.
MDBox4
using Mantid::DataObjects::MDBox4 = typedef MDBox<MDEvent<4>, 4>
Typedef for a MDBox with 4 dimensions.
Definition at line 389 of file MDEventFactory.h.
MDBox4Lean
using Mantid::DataObjects::MDBox4Lean = typedef MDBox<MDLeanEvent<4>, 4>
Typedef for a MDBox with 4 dimensions.
Definition at line 371 of file MDEventFactory.h.
MDBox5
using Mantid::DataObjects::MDBox5 = typedef MDBox<MDEvent<5>, 5>
Typedef for a MDBox with 5 dimensions.
Definition at line 391 of file MDEventFactory.h.
MDBox5Lean
using Mantid::DataObjects::MDBox5Lean = typedef MDBox<MDLeanEvent<5>, 5>
Typedef for a MDBox with 5 dimensions.
Definition at line 373 of file MDEventFactory.h.
MDBox6
using Mantid::DataObjects::MDBox6 = typedef MDBox<MDEvent<6>, 6>
Typedef for a MDBox with 6 dimensions.
Definition at line 393 of file MDEventFactory.h.
MDBox6Lean
using Mantid::DataObjects::MDBox6Lean = typedef MDBox<MDLeanEvent<6>, 6>
Typedef for a MDBox with 6 dimensions.
Definition at line 375 of file MDEventFactory.h.
MDBox7
using Mantid::DataObjects::MDBox7 = typedef MDBox<MDEvent<7>, 7>
Typedef for a MDBox with 7 dimensions.
Definition at line 395 of file MDEventFactory.h.
MDBox7Lean
using Mantid::DataObjects::MDBox7Lean = typedef MDBox<MDLeanEvent<7>, 7>
Typedef for a MDBox with 7 dimensions.
Definition at line 377 of file MDEventFactory.h.
MDBox8
using Mantid::DataObjects::MDBox8 = typedef MDBox<MDEvent<8>, 8>
Typedef for a MDBox with 8 dimensions.
Definition at line 397 of file MDEventFactory.h.
MDBox8Lean
using Mantid::DataObjects::MDBox8Lean = typedef MDBox<MDLeanEvent<8>, 8>
Typedef for a MDBox with 8 dimensions.
Definition at line 379 of file MDEventFactory.h.
MDBox9
using Mantid::DataObjects::MDBox9 = typedef MDBox<MDEvent<9>, 9>
Typedef for a MDBox with 9 dimensions.
Definition at line 399 of file MDEventFactory.h.
MDBox9Lean
using Mantid::DataObjects::MDBox9Lean = typedef MDBox<MDLeanEvent<9>, 9>
Typedef for a MDBox with 9 dimensions.
Definition at line 381 of file MDEventFactory.h.
MDBoxBase1
using Mantid::DataObjects::MDBoxBase1 = typedef MDBoxBase<MDEvent<1>, 1>
Typedef for a MDBoxBase with 1 dimension.
Definition at line 422 of file MDEventFactory.h.
MDBoxBase1Lean
using Mantid::DataObjects::MDBoxBase1Lean = typedef MDBoxBase<MDLeanEvent<1>, 1>
Typedef for a MDBoxBase with 1 dimension.
Definition at line 404 of file MDEventFactory.h.
MDBoxBase2
using Mantid::DataObjects::MDBoxBase2 = typedef MDBoxBase<MDEvent<2>, 2>
Typedef for a MDBoxBase with 2 dimensions.
Definition at line 424 of file MDEventFactory.h.
MDBoxBase2Lean
using Mantid::DataObjects::MDBoxBase2Lean = typedef MDBoxBase<MDLeanEvent<2>, 2>
Typedef for a MDBoxBase with 2 dimensions.
Definition at line 406 of file MDEventFactory.h.
MDBoxBase3
using Mantid::DataObjects::MDBoxBase3 = typedef MDBoxBase<MDEvent<3>, 3>
Typedef for a MDBoxBase with 3 dimensions.
Definition at line 426 of file MDEventFactory.h.
MDBoxBase3Lean
using Mantid::DataObjects::MDBoxBase3Lean = typedef MDBoxBase<MDLeanEvent<3>, 3>
Typedef for a MDBoxBase with 3 dimensions.
Definition at line 408 of file MDEventFactory.h.
MDBoxBase4
using Mantid::DataObjects::MDBoxBase4 = typedef MDBoxBase<MDEvent<4>, 4>
Typedef for a MDBoxBase with 4 dimensions.
Definition at line 428 of file MDEventFactory.h.
MDBoxBase4Lean
using Mantid::DataObjects::MDBoxBase4Lean = typedef MDBoxBase<MDLeanEvent<4>, 4>
Typedef for a MDBoxBase with 4 dimensions.
Definition at line 410 of file MDEventFactory.h.
MDBoxBase5
using Mantid::DataObjects::MDBoxBase5 = typedef MDBoxBase<MDEvent<5>, 5>
Typedef for a MDBoxBase with 5 dimensions.
Definition at line 430 of file MDEventFactory.h.
MDBoxBase5Lean
using Mantid::DataObjects::MDBoxBase5Lean = typedef MDBoxBase<MDLeanEvent<5>, 5>
Typedef for a MDBoxBase with 5 dimensions.
Definition at line 412 of file MDEventFactory.h.
MDBoxBase6
using Mantid::DataObjects::MDBoxBase6 = typedef MDBoxBase<MDEvent<6>, 6>
Typedef for a MDBoxBase with 6 dimensions.
Definition at line 432 of file MDEventFactory.h.
MDBoxBase6Lean
using Mantid::DataObjects::MDBoxBase6Lean = typedef MDBoxBase<MDLeanEvent<6>, 6>
Typedef for a MDBoxBase with 6 dimensions.
Definition at line 414 of file MDEventFactory.h.
MDBoxBase7
using Mantid::DataObjects::MDBoxBase7 = typedef MDBoxBase<MDEvent<7>, 7>
Typedef for a MDBoxBase with 7 dimensions.
Definition at line 434 of file MDEventFactory.h.
MDBoxBase7Lean
using Mantid::DataObjects::MDBoxBase7Lean = typedef MDBoxBase<MDLeanEvent<7>, 7>
Typedef for a MDBoxBase with 7 dimensions.
Definition at line 416 of file MDEventFactory.h.
MDBoxBase8
using Mantid::DataObjects::MDBoxBase8 = typedef MDBoxBase<MDEvent<8>, 8>
Typedef for a MDBoxBase with 8 dimensions.
Definition at line 436 of file MDEventFactory.h.
MDBoxBase8Lean
using Mantid::DataObjects::MDBoxBase8Lean = typedef MDBoxBase<MDLeanEvent<8>, 8>
Typedef for a MDBoxBase with 8 dimensions.
Definition at line 418 of file MDEventFactory.h.
MDBoxBase9
using Mantid::DataObjects::MDBoxBase9 = typedef MDBoxBase<MDEvent<9>, 9>
Typedef for a MDBoxBase with 9 dimensions.
Definition at line 438 of file MDEventFactory.h.
MDBoxBase9Lean
using Mantid::DataObjects::MDBoxBase9Lean = typedef MDBoxBase<MDLeanEvent<9>, 9>
Typedef for a MDBoxBase with 9 dimensions.
Definition at line 420 of file MDEventFactory.h.
MDEventWorkspace1
using Mantid::DataObjects::MDEventWorkspace1 = typedef MDEventWorkspace<MDEvent<1>, 1>
Typedef for a MDEventWorkspace with 1 dimension.
Definition at line 500 of file MDEventFactory.h.
MDEventWorkspace1Lean
using Mantid::DataObjects::MDEventWorkspace1Lean = typedef MDEventWorkspace<MDLeanEvent<1>, 1>
Typedef for a MDEventWorkspace with 1 dimension.
Definition at line 482 of file MDEventFactory.h.
MDEventWorkspace2
using Mantid::DataObjects::MDEventWorkspace2 = typedef MDEventWorkspace<MDEvent<2>, 2>
Typedef for a MDEventWorkspace with 2 dimensions.
Definition at line 502 of file MDEventFactory.h.
MDEventWorkspace2Lean
using Mantid::DataObjects::MDEventWorkspace2Lean = typedef MDEventWorkspace<MDLeanEvent<2>, 2>
Typedef for a MDEventWorkspace with 2 dimensions.
Definition at line 484 of file MDEventFactory.h.
MDEventWorkspace3
using Mantid::DataObjects::MDEventWorkspace3 = typedef MDEventWorkspace<MDEvent<3>, 3>
Typedef for a MDEventWorkspace with 3 dimensions.
Definition at line 504 of file MDEventFactory.h.
MDEventWorkspace3Lean
using Mantid::DataObjects::MDEventWorkspace3Lean = typedef MDEventWorkspace<MDLeanEvent<3>, 3>
Typedef for a MDEventWorkspace with 3 dimensions.
Definition at line 486 of file MDEventFactory.h.
MDEventWorkspace4
using Mantid::DataObjects::MDEventWorkspace4 = typedef MDEventWorkspace<MDEvent<4>, 4>
Typedef for a MDEventWorkspace with 4 dimensions.
Definition at line 506 of file MDEventFactory.h.
MDEventWorkspace4Lean
using Mantid::DataObjects::MDEventWorkspace4Lean = typedef MDEventWorkspace<MDLeanEvent<4>, 4>
Typedef for a MDEventWorkspace with 4 dimensions.
Definition at line 488 of file MDEventFactory.h.
MDEventWorkspace5
using Mantid::DataObjects::MDEventWorkspace5 = typedef MDEventWorkspace<MDEvent<5>, 5>
Typedef for a MDEventWorkspace with 5 dimensions.
Definition at line 508 of file MDEventFactory.h.
MDEventWorkspace5Lean
using Mantid::DataObjects::MDEventWorkspace5Lean = typedef MDEventWorkspace<MDLeanEvent<5>, 5>
Typedef for a MDEventWorkspace with 5 dimensions.
Definition at line 490 of file MDEventFactory.h.
MDEventWorkspace6
using Mantid::DataObjects::MDEventWorkspace6 = typedef MDEventWorkspace<MDEvent<6>, 6>
Typedef for a MDEventWorkspace with 6 dimensions.
Definition at line 510 of file MDEventFactory.h.
MDEventWorkspace6Lean
using Mantid::DataObjects::MDEventWorkspace6Lean = typedef MDEventWorkspace<MDLeanEvent<6>, 6>
Typedef for a MDEventWorkspace with 6 dimensions.
Definition at line 492 of file MDEventFactory.h.
MDEventWorkspace7
using Mantid::DataObjects::MDEventWorkspace7 = typedef MDEventWorkspace<MDEvent<7>, 7>
Typedef for a MDEventWorkspace with 7 dimensions.
Definition at line 512 of file MDEventFactory.h.
MDEventWorkspace7Lean
using Mantid::DataObjects::MDEventWorkspace7Lean = typedef MDEventWorkspace<MDLeanEvent<7>, 7>
Typedef for a MDEventWorkspace with 7 dimensions.
Definition at line 494 of file MDEventFactory.h.
MDEventWorkspace8
using Mantid::DataObjects::MDEventWorkspace8 = typedef MDEventWorkspace<MDEvent<8>, 8>
Typedef for a MDEventWorkspace with 8 dimensions.
Definition at line 514 of file MDEventFactory.h.
MDEventWorkspace8Lean
using Mantid::DataObjects::MDEventWorkspace8Lean = typedef MDEventWorkspace<MDLeanEvent<8>, 8>
Typedef for a MDEventWorkspace with 8 dimensions.
Definition at line 496 of file MDEventFactory.h.
MDEventWorkspace9
using Mantid::DataObjects::MDEventWorkspace9 = typedef MDEventWorkspace<MDEvent<9>, 9>
Typedef for a MDEventWorkspace with 9 dimensions.
Definition at line 516 of file MDEventFactory.h.
MDEventWorkspace9Lean
using Mantid::DataObjects::MDEventWorkspace9Lean = typedef MDEventWorkspace<MDLeanEvent<9>, 9>
Typedef for a MDEventWorkspace with 9 dimensions.
Definition at line 498 of file MDEventFactory.h.
MDEventWS
template<size_t nd> using Mantid::DataObjects::MDEventWS = typedef MDEventWorkspace<MDEvent<nd>, nd>
Definition at line 30 of file PropertyWithValue.cpp.
MDExtentPair
using Mantid::DataObjects::MDExtentPair = typedef boost::tuple<Mantid::coord_t, Mantid::coord_t>
Definition at line 24 of file MDHistoWorkspaceIterator.h.
MDGridBox1
using Mantid::DataObjects::MDGridBox1 = typedef MDGridBox<MDEvent<1>, 1>
Typedef for a MDGridBox with 1 dimension.
Definition at line 461 of file MDEventFactory.h.
MDGridBox1Lean
using Mantid::DataObjects::MDGridBox1Lean = typedef MDGridBox<MDLeanEvent<1>, 1>
Typedef for a MDGridBox with 1 dimension.
Definition at line 443 of file MDEventFactory.h.
MDGridBox2
using Mantid::DataObjects::MDGridBox2 = typedef MDGridBox<MDEvent<2>, 2>
Typedef for a MDGridBox with 2 dimensions.
Definition at line 463 of file MDEventFactory.h.
MDGridBox2Lean
using Mantid::DataObjects::MDGridBox2Lean = typedef MDGridBox<MDLeanEvent<2>, 2>
Typedef for a MDGridBox with 2 dimensions.
Definition at line 445 of file MDEventFactory.h.
MDGridBox3
using Mantid::DataObjects::MDGridBox3 = typedef MDGridBox<MDEvent<3>, 3>
Typedef for a MDGridBox with 3 dimensions.
Definition at line 465 of file MDEventFactory.h.
MDGridBox3Lean
using Mantid::DataObjects::MDGridBox3Lean = typedef MDGridBox<MDLeanEvent<3>, 3>
Typedef for a MDGridBox with 3 dimensions.
Definition at line 447 of file MDEventFactory.h.
MDGridBox4
using Mantid::DataObjects::MDGridBox4 = typedef MDGridBox<MDEvent<4>, 4>
Typedef for a MDGridBox with 4 dimensions.
Definition at line 467 of file MDEventFactory.h.
MDGridBox4Lean
using Mantid::DataObjects::MDGridBox4Lean = typedef MDGridBox<MDLeanEvent<4>, 4>
Typedef for a MDGridBox with 4 dimensions.
Definition at line 449 of file MDEventFactory.h.
MDGridBox5
using Mantid::DataObjects::MDGridBox5 = typedef MDGridBox<MDEvent<5>, 5>
Typedef for a MDGridBox with 5 dimensions.
Definition at line 469 of file MDEventFactory.h.
MDGridBox5Lean
using Mantid::DataObjects::MDGridBox5Lean = typedef MDGridBox<MDLeanEvent<5>, 5>
Typedef for a MDGridBox with 5 dimensions.
Definition at line 451 of file MDEventFactory.h.
MDGridBox6
using Mantid::DataObjects::MDGridBox6 = typedef MDGridBox<MDEvent<6>, 6>
Typedef for a MDGridBox with 6 dimensions.
Definition at line 471 of file MDEventFactory.h.
MDGridBox6Lean
using Mantid::DataObjects::MDGridBox6Lean = typedef MDGridBox<MDLeanEvent<6>, 6>
Typedef for a MDGridBox with 6 dimensions.
Definition at line 453 of file MDEventFactory.h.
MDGridBox7
using Mantid::DataObjects::MDGridBox7 = typedef MDGridBox<MDEvent<7>, 7>
Typedef for a MDGridBox with 7 dimensions.
Definition at line 473 of file MDEventFactory.h.
MDGridBox7Lean
using Mantid::DataObjects::MDGridBox7Lean = typedef MDGridBox<MDLeanEvent<7>, 7>
Typedef for a MDGridBox with 7 dimensions.
Definition at line 455 of file MDEventFactory.h.
MDGridBox8
using Mantid::DataObjects::MDGridBox8 = typedef MDGridBox<MDEvent<8>, 8>
Typedef for a MDGridBox with 8 dimensions.
Definition at line 475 of file MDEventFactory.h.
MDGridBox8Lean
using Mantid::DataObjects::MDGridBox8Lean = typedef MDGridBox<MDLeanEvent<8>, 8>
Typedef for a MDGridBox with 8 dimensions.
Definition at line 457 of file MDEventFactory.h.
MDGridBox9
using Mantid::DataObjects::MDGridBox9 = typedef MDGridBox<MDEvent<9>, 9>
Typedef for a MDGridBox with 9 dimensions.
Definition at line 477 of file MDEventFactory.h.
MDGridBox9Lean
using Mantid::DataObjects::MDGridBox9Lean = typedef MDGridBox<MDLeanEvent<9>, 9>
Typedef for a MDGridBox with 9 dimensions.
Definition at line 459 of file MDEventFactory.h.
MDHistoWorkspace_const_sptr
using Mantid::DataObjects::MDHistoWorkspace_const_sptr = typedef std::shared_ptr<const MDHistoWorkspace>
A shared pointer to a const MDHistoWorkspace.
Definition at line 462 of file MDHistoWorkspace.h.
MDHistoWorkspace_sptr
using Mantid::DataObjects::MDHistoWorkspace_sptr = typedef std::shared_ptr<MDHistoWorkspace>
A shared pointer to a MDHistoWorkspace.
Definition at line 459 of file MDHistoWorkspace.h.
MDLeanEventWS
template<size_t nd> using Mantid::DataObjects::MDLeanEventWS = typedef MDEventWorkspace<MDLeanEvent<nd>, nd>
Definition at line 31 of file PropertyWithValue.cpp.
OffsetsWorkspace_const_sptr
using Mantid::DataObjects::OffsetsWorkspace_const_sptr = typedef std::shared_ptr<const OffsetsWorkspace>
shared pointer to a const OffsetsWorkspace
Definition at line 50 of file OffsetsWorkspace.h.
OffsetsWorkspace_sptr
using Mantid::DataObjects::OffsetsWorkspace_sptr = typedef std::shared_ptr<OffsetsWorkspace>
shared pointer to the OffsetsWorkspace class
Definition at line 47 of file OffsetsWorkspace.h.
Peak_uptr
using Mantid::DataObjects::Peak_uptr = typedef std::unique_ptr<Peak>
Definition at line 174 of file Peak.h.
PeakEllipsoidExtent
typedef std::array<double, PEAK_ELLIPSOID_DIMS> Mantid::DataObjects::PeakEllipsoidExtent
Definition at line 15 of file PeakShapeEllipsoid_fwd.h.
PeakEllipsoidFrame
typedef std::array<Kernel::V3D, PEAK_ELLIPSOID_DIMS> Mantid::DataObjects::PeakEllipsoidFrame
Definition at line 16 of file PeakShapeEllipsoid_fwd.h.
PeakShapeDetectorTOF_const_sptr
using Mantid::DataObjects::PeakShapeDetectorTOF_const_sptr = typedef std::shared_ptr<const PeakShapeDetectorBin>
Definition at line 44 of file PeakShapeDetectorBin.h.
PeakShapeDetectorTOF_sptr
using Mantid::DataObjects::PeakShapeDetectorTOF_sptr = typedef std::shared_ptr<PeakShapeDetectorBin>
Definition at line 43 of file PeakShapeDetectorBin.h.
PeakShapeEllipsoid_const_sptr
typedef std::shared_ptr< const PeakShapeEllipsoid > Mantid::DataObjects::PeakShapeEllipsoid_const_sptr
Definition at line 67 of file PeakShapeEllipsoid.h.
PeakShapeEllipsoid_sptr
typedef std::shared_ptr< PeakShapeEllipsoid > Mantid::DataObjects::PeakShapeEllipsoid_sptr
Definition at line 66 of file PeakShapeEllipsoid.h.
PeakShapeFactory_const_sptr
using Mantid::DataObjects::PeakShapeFactory_const_sptr = typedef std::shared_ptr<const PeakShapeFactory>
Helper typedef.
Definition at line 36 of file PeakShapeFactory.h.
PeakShapeFactory_sptr
using Mantid::DataObjects::PeakShapeFactory_sptr = typedef std::shared_ptr<PeakShapeFactory>
Helper typedef.
Definition at line 34 of file PeakShapeFactory.h.
PeaksWorkspace_const_sptr
using Mantid::DataObjects::PeaksWorkspace_const_sptr = typedef std::shared_ptr<const PeaksWorkspace>
Typedef for a shared pointer to a const peaks workspace.
Definition at line 247 of file PeaksWorkspace.h.
PeaksWorkspace_sptr
using Mantid::DataObjects::PeaksWorkspace_sptr = typedef std::shared_ptr<PeaksWorkspace>
Typedef for a shared pointer to a peaks workspace.
Definition at line 244 of file PeaksWorkspace.h.
PermutationsMap
using Mantid::DataObjects::PermutationsMap = typedef std::map<std::vector<int>, std::vector<int64_t> >
Definition at line 22 of file MDHistoWorkspaceIterator.h.
RebinnedOutput_const_sptr
using Mantid::DataObjects::RebinnedOutput_const_sptr = typedef std::shared_ptr<const RebinnedOutput>
shared pointer to a const RebinnedOutput
Definition at line 94 of file RebinnedOutput.h.
RebinnedOutput_sptr
using Mantid::DataObjects::RebinnedOutput_sptr = typedef std::shared_ptr<RebinnedOutput>
shared pointer to the RebinnedOutput class
Definition at line 92 of file RebinnedOutput.h.
ReflectometryTransform_sptr
using Mantid::DataObjects::ReflectometryTransform_sptr = typedef std::shared_ptr<ReflectometryTransform>
Definition at line 94 of file ReflectometryTransform.h.
SkippingPolicy_scptr
using Mantid::DataObjects::SkippingPolicy_scptr = typedef boost::scoped_ptr<SkippingPolicy>
Definition at line 51 of file SkippingPolicy.h.
SpecialWorkspace2D_const_sptr
using Mantid::DataObjects::SpecialWorkspace2D_const_sptr = typedef std::shared_ptr<const SpecialWorkspace2D>
shared pointer to a const SpecialWorkspace2D
Definition at line 94 of file SpecialWorkspace2D.h.
SpecialWorkspace2D_sptr
using Mantid::DataObjects::SpecialWorkspace2D_sptr = typedef std::shared_ptr<SpecialWorkspace2D>
shared pointer to the SpecialWorkspace2D class
Definition at line 91 of file SpecialWorkspace2D.h.
SplittersWorkspace_const_sptr
using Mantid::DataObjects::SplittersWorkspace_const_sptr = typedef std::shared_ptr<const SplittersWorkspace>
Definition at line 59 of file SplittersWorkspace.h.
SplittersWorkspace_sptr
using Mantid::DataObjects::SplittersWorkspace_sptr = typedef std::shared_ptr<SplittersWorkspace>
Definition at line 58 of file SplittersWorkspace.h.
TableWorkspace_const_sptr
using Mantid::DataObjects::TableWorkspace_const_sptr = typedef std::shared_ptr<const TableWorkspace>
shared pointer to Mantid::DataObjects::TableWorkspace (const version)
Definition at line 22 of file TableWorkspace_fwd.h.
TableWorkspace_const_uptr
using Mantid::DataObjects::TableWorkspace_const_uptr = typedef std::unique_ptr<const TableWorkspace>
unique pointer to Mantid::DataObjects::TableWorkspace (const version)
Definition at line 26 of file TableWorkspace_fwd.h.
TableWorkspace_sptr
using Mantid::DataObjects::TableWorkspace_sptr = typedef std::shared_ptr<TableWorkspace>
shared pointer to Mantid::DataObjects::TableWorkspace
Definition at line 20 of file TableWorkspace_fwd.h.
TableWorkspace_uptr
using Mantid::DataObjects::TableWorkspace_uptr = typedef std::unique_ptr<TableWorkspace>
unique pointer to Mantid::DataObjects::TableWorkspace
Definition at line 24 of file TableWorkspace_fwd.h.
VecMDExtents
using Mantid::DataObjects::VecMDExtents = typedef std::vector<MDExtentPair>
Definition at line 26 of file MDHistoWorkspaceIterator.h.
Workspace2D_const_sptr
using Mantid::DataObjects::Workspace2D_const_sptr = typedef std::shared_ptr<const Workspace2D>
shared pointer to Mantid::DataObjects::Workspace2D (const version)
Definition at line 21 of file Workspace2D_fwd.h.
Workspace2D_const_uptr
using Mantid::DataObjects::Workspace2D_const_uptr = typedef std::unique_ptr<const Workspace2D>
unique pointer to Mantid::DataObjects::Workspace2D (const version)
Definition at line 25 of file Workspace2D_fwd.h.
Workspace2D_sptr
using Mantid::DataObjects::Workspace2D_sptr = typedef std::shared_ptr<Workspace2D>
shared pointer to Mantid::DataObjects::Workspace2D
Definition at line 19 of file Workspace2D_fwd.h.
Workspace2D_uptr
using Mantid::DataObjects::Workspace2D_uptr = typedef std::unique_ptr<Workspace2D>
unique pointer to Mantid::DataObjects::Workspace2D
Definition at line 23 of file Workspace2D_fwd.h.
WorkspaceSingleValue_const_sptr
using Mantid::DataObjects::WorkspaceSingleValue_const_sptr = typedef std::shared_ptr<const WorkspaceSingleValue>
Definition at line 87 of file WorkspaceSingleValue.h.
WorkspaceSingleValue_sptr
using Mantid::DataObjects::WorkspaceSingleValue_sptr = typedef std::shared_ptr<WorkspaceSingleValue>
shared pointer to the WorkspaceSingleValue class
Definition at line 86 of file WorkspaceSingleValue.h.
Enumeration Type Documentation
EventSortType
enum Mantid::DataObjects::EventSortType
How the event list is sorted.
Enumerator
UNSORTED
TOF_SORT
PULSETIME_SORT
PULSETIMETOF_SORT
PULSETIMETOF_DELTA_SORT
TIMEATSAMPLE_SORT
Definition at line 32 of file EventList.h.
Function Documentation
compareEventPulseTime()
bool Mantid::DataObjects::compareEventPulseTime (const TofEvent & e1, const TofEvent & e2)
Compare two events' FRAME id, return true if e1 should be before e2.
------------------ TofEvent Comparators
Parameters
e1 :: first event
e2 :: second event
Definition at line 99 of file EventList.cpp.
Referenced by Mantid::DataObjects::EventList::sortPulseTime().
compareEventPulseTimeTOF()
bool Mantid::DataObjects::compareEventPulseTimeTOF (const TofEvent & e1, const TofEvent & e2)
Compare two events' FRAME id, return true if e1 should be before e2.
Assuming that if e1's pulse time is earlier than e2's, then e1 must be earlier regardless TOF value
Parameters
e1 :: first event
e2 :: second event
Definition at line 107 of file EventList.cpp.
Referenced by Mantid::DataObjects::EventList::sortPulseTimeTOF().
convertFormats()
template<typename FROM , typename TO > void Mantid::DataObjects::convertFormats (const std::vector< FROM > & inData, std::vector< TO > & outData)
Helper funcion which allows to convert one data fomat into another.
Definition at line 521 of file BoxControllerNeXusIO.cpp.
Referenced by Mantid::DataObjects::BoxControllerNeXusIO::loadBlock(), and Mantid::DataObjects::BoxControllerNeXusIO::loadBlock().
create() [1/7]
template<class T , class IndexArg , class HistArg , typename std::enable_if<!std::is_base_of< API::MatrixWorkspace, IndexArg >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const IndexArg & indexArg, const HistArg & histArg)
Definition at line 168 of file WorkspaceCreation.h.
References create().
create() [2/7]
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const P & parent)
Definition at line 200 of file WorkspaceCreation.h.
References create(), and Mantid::DataObjects::detail::stripData().
create() [3/7]
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const P & parent, const HistogramData::BinEdges & binEdges)
Definition at line 221 of file WorkspaceCreation.h.
References create().
create() [4/7]
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const P & parent, const HistogramData::Histogram & histogram)
Definition at line 216 of file WorkspaceCreation.h.
References create().
create() [5/7]
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const P & parent, const HistogramData::Points & points)
Definition at line 226 of file WorkspaceCreation.h.
References create().
create() [6/7]
template<class T , class P , class IndexArg , class HistArg , class = typename std::enable_if<std::is_base_of<API::MatrixWorkspace, P>::value>::type> std::unique_ptr< T > Mantid::DataObjects::create (const P & parent, const IndexArg & indexArg, const HistArg & histArg)
This is the create() method that all the other create() methods call.
And it is also called directly.
Definition at line 132 of file WorkspaceCreation.h.
References create(), and Mantid::DataObjects::detail::fixDistributionFlag().
Referenced by Mantid::Geometry::ParameterMap::add(), Mantid::DataHandling::LoadFITS::addAxesInfoAndLogs(), Mantid::MDAlgorithms::LoadSQW::addDimsToWs(), Mantid::CurveFitting::Functions::ProcessBackground::addRegion(), Mantid::DataHandling::LoadMuonNexusV2::applyTimeAxisUnitCorrection(), Mantid::DataHandling::LoadPSIMuonBin::assignOutputWorkspaceParticulars(), Mantid::API::Axis::Axis(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::buildPartialWorkspace(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::CurveFitting::Algorithms::ChiSlice::ChiSlice(), Mantid::Geometry::ParameterMap::componentIds(), Mantid::Geometry::StructureFactorCalculatorFactory::create(), create(), create(), create(), create(), create(), create(), create(), Mantid::Geometry::GroupFactory::create(), Mantid::Geometry::GroupFactory::create(), WorkspaceCreationHelper::create2DWorkspaceFromFunction(), Mantid::DataHandling::LoadNGEM::createCountWorkspace(), Mantid::DataHandling::LoadILLSANS::createEmptyWorkspace(), Mantid::DataHandling::LoadSpiceXML2DDet::createMatrixWorkspace(), Mantid::CurveFitting::Algorithms::LeBailFit::createOutputDataWorkspace(), Mantid::CurveFitting::SeqDomainSpectrumCreator::createOutputWorkspace(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::createOutputWorkspace(), Mantid::Algorithms::FFT::createUnitsLabels(), Mantid::DataHandling::LoadHFIRSANS::createWorkspace(), Mantid::DataHandling::LoadRawHelper::createWorkspace(), Mantid::DataHandling::LoadSpice2D::createWorkspace(), Mantid::DataHandling::LoadRawHelper::createWorkspace(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertTableToMatrixWorkspace::exec(), Mantid::Algorithms::ReadGroupsFromFile::exec(), Mantid::Crystal::LoadIsawSpectrum::exec(), Mantid::CurveFitting::Algorithms::ConvolveWorkspaces::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::DataHandling::GroupDetectors2::exec(), Mantid::DataHandling::LoadDNSEvent::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadSpec::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::DataHandling::GroupDetectors2::execEvent(), Mantid::Algorithms::SmoothNeighbours::execEvent(), Mantid::Algorithms::SmoothNeighbours::execWorkspace2D(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::Crystal::SCDCalibratePanels::findL1(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::DataHandling::LoadPDFgetNFile::generateDataWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::generateEventDistribtionWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genOutputFittedPatternWorkspace(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::genOutputWorkspace(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeakParameterDataWorkspace(), Mantid::CurveFitting::IFittingAlgorithm::getCostFunctionInitialized(), Mantid::Crystal::SCDCalibratePanels2::getIdealQSampleAsHistogram1D(), Mantid::CurveFitting::Algorithms::DoublePulseFit::initConcrete(), Mantid::CurveFitting::Algorithms::Fit::initConcrete(), Mantid::CurveFitting::Algorithms::QENSFitSimultaneous::initConcrete(), Mantid::DataHandling::LoadILLPolarizedDiffraction::initStaticWorkspace(), Mantid::Kernel::Interpolation::Interpolation(), Mantid::DataHandling::LoadNexusProcessed::loadEventEntry(), Mantid::DataHandling::LoadSassena::loadFQ(), Mantid::DataHandling::LoadSassena::loadFQT(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make1DWorkspace(), Mantid::MDAlgorithms::ConvertMDHistoToMatrixWorkspace::make2DWorkspace(), Mantid::DataHandling::LoadFITS::makeWorkspace(), Mantid::API::AlgorithmFactoryImpl::operator=(), Mantid::API::ImplicitFunctionFactoryImpl::operator=(), Mantid::API::ImplicitFunctionParameterParserFactoryImpl::operator=(), Mantid::API::ImplicitFunctionParserFactoryImpl::operator=(), Mantid::API::WorkspaceFactoryImpl::operator=(), Mantid::Algorithms::MaxEnt::populateImageWS(), Mantid::DataHandling::LoadAscii::readData(), Mantid::Geometry::ReflectionGenerator::ReflectionGenerator(), Mantid::CurveFitting::Functions::RemovePeaks::removePeaks(), Mantid::DataHandling::SampleEnvironmentFactory::SampleEnvironmentFactory(), Mantid::DataObjects::MDBoxFlatTree::saveBoxStructure(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveIsawDetCal(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::CurveFitting::Functions::ProcessBackground::setupDummyOutputWSes(), Mantid::DataHandling::LoadDaveGrp::setupWorkspace(), Mantid::Algorithms::SmoothNeighbours::spreadPixels(), Mantid::Geometry::StructureFactorCalculatorSummation::StructureFactorCalculatorSummation(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseDetectorNode(), Mantid::Geometry::MDGeometryBuilderXML< CheckDimensionPolicy >::~MDGeometryBuilderXML(), and Mantid::Kernel::TimeSeriesProperty< TYPE >::~TimeSeriesProperty().
create() [7/7]
template<class T , class IndexArg , class HistArg , typename std::enable_if<!std::is_base_of< API::MatrixWorkspace, IndexArg >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::create (const std::shared_ptr< const Geometry::Instrument > & instrument, const IndexArg & indexArg, const HistArg & histArg)
Definition at line 176 of file WorkspaceCreation.h.
References create().
createRagged()
template<class T , class P , typename std::enable_if< std::is_base_of< API::MatrixWorkspace, P >::value >::type * = nullptr> std::unique_ptr< T > Mantid::DataObjects::createRagged (const P & parent)
Definition at line 185 of file WorkspaceCreation.h.
createVerticalAxis()
void Mantid::DataObjects::createVerticalAxis (MatrixWorkspace *const ws, const MantidVec & xAxisVec, const double gradY, const double cyToUnit, const size_t nBins, const std::string & caption, const std::string & units)
Create a new y(vertical)-axis for the output workspace.
Create a new Y, or Vertical Axis for the output workspace.
Parameters
ws : Workspace to attache the vertical axis to
xAxisVec : Vector of x axis increments
gradY : Gradient used in linear transform from index to Y-scale
cyToUnit : C-offset used in the linear transform
nBins : Number of bins along the axis
caption : Caption for the axis
units : Units label for the axis
Definition at line 183 of file ReflectometryTransform.cpp.
References Mantid::API::MatrixWorkspace::replaceAxis(), and Mantid::API::MatrixWorkspace::setX().
Referenced by Mantid::DataObjects::ReflectometryTransform::execute().
createXAxis()
MantidVec Mantid::DataObjects::createXAxis (MatrixWorkspace *const ws, const double gradX, const double cxToUnit, const size_t nBins, const std::string & caption, const std::string & units)
Create a new x-axis for the output workspace.
Create a new X-Axis for the output workspace.
Parameters
ws : Workspace to attach the axis to
gradX : Gradient used in the linear transform from index to X-scale
cxToUnit : C-offset used in the linear transform
nBins : Number of bins along this axis
caption : Caption for the axis
units : Units label for the axis
Returns
Vector containing increments along the axis.
Definition at line 152 of file ReflectometryTransform.cpp.
References Mantid::API::MatrixWorkspace::replaceAxis().
Referenced by Mantid::DataObjects::ReflectometryTransform::execute().
findFirstEvent() [1/2]
template<class T > static std::vector< T >::const_iterator Mantid::DataObjects::findFirstEvent (const std::vector< T > & events, T seek_tof) static
Utility function: Returns the iterator into events of the first TofEvent with tof() > seek_tof Will return events.end() if nothing is found!
Parameters
events :: event vector in which to look.
seek_tof :: tof to find (typically the first bin X[0])
Returns
iterator where the first event matching it is.
Definition at line 2037 of file EventList.cpp.
References Mantid::Geometry::x.
Referenced by Mantid::DataObjects::EventList::divideHistogramHelper(), Mantid::DataObjects::EventList::generateCountsHistogram(), Mantid::DataObjects::EventList::histogramForWeightsHelper(), and Mantid::DataObjects::EventList::multiplyHistogramHelper().
findFirstEvent() [2/2]
template<class T > static std::vector< T >::iterator Mantid::DataObjects::findFirstEvent (std::vector< T > & events, T seek_tof) static
Utility function: Returns the iterator into events of the first TofEvent with tof() > seek_tof Will return events.end() if nothing is found!
Parameters
events :: event vector in which to look.
seek_tof :: tof to find (typically the first bin X[0])
Returns
iterator where the first event matching it is.
Definition at line 2104 of file EventList.cpp.
References Mantid::Geometry::x.
getEventsFrom() [1/8]
void Mantid::DataObjects::getEventsFrom (const EventList & el, std::vector< TofEvent > const *& events)
Definition at line 4424 of file EventList.cpp.
References Mantid::DataObjects::EventList::getEvents().
getEventsFrom() [2/8]
DLLExport void Mantid::DataObjects::getEventsFrom (const EventList & el, std::vector< Types::Event::TofEvent > const *& events)
getEventsFrom() [3/8]
void Mantid::DataObjects::getEventsFrom (const EventList & el, std::vector< WeightedEvent > const *& events)
Definition at line 4436 of file EventList.cpp.
References Mantid::DataObjects::EventList::getWeightedEvents().
getEventsFrom() [4/8]
void Mantid::DataObjects::getEventsFrom (const EventList & el, std::vector< WeightedEventNoTime > const *& events)
Definition at line 4448 of file EventList.cpp.
References Mantid::DataObjects::EventList::getWeightedEventsNoTime().
getEventsFrom() [5/8]
void Mantid::DataObjects::getEventsFrom (EventList & el, std::vector< TofEvent > *& events)
Get the vector of events contained in an EventList; this is overloaded by event type.
Parameters
el :: The EventList to retrieve
[out] events :: reference to a pointer to a vector of this type of event. The pointer will be set to point to the vector.
Exceptions
runtime_error if you call this on the wrong type of EventList.
Definition at line 4423 of file EventList.cpp.
References Mantid::DataObjects::EventList::getEvents().
getEventsFrom() [6/8]
DLLExport void Mantid::DataObjects::getEventsFrom (EventList & el, std::vector< Types::Event::TofEvent > *& events)
Referenced by Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::convertEventList(), Mantid::MDAlgorithms::ConvToMDEventsWS::convertEventList(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::convertEventList(), Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::convertEvents(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadBBY2::exec(), Mantid::MDAlgorithms::IntegrateFlux::integrateSpectraEvents(), Mantid::DataHandling::DefaultEventLoader::makeMapToEventLists(), Mantid::DataHandling::LoadEMU< FD >::prepareEventStorage(), and Mantid::DataHandling::LoadPLN::prepareEventStorage().
getEventsFrom() [7/8]
void Mantid::DataObjects::getEventsFrom (EventList & el, std::vector< WeightedEvent > *& events)
Get the vector of events contained in an EventList; this is overloaded by event type.
Parameters
el :: The EventList to retrieve
[out] events :: reference to a pointer to a vector of this type of event. The pointer will be set to point to the vector.
Exceptions
runtime_error if you call this on the wrong type of EventList.
Definition at line 4435 of file EventList.cpp.
References Mantid::DataObjects::EventList::getWeightedEvents().
getEventsFrom() [8/8]
void Mantid::DataObjects::getEventsFrom (EventList & el, std::vector< WeightedEventNoTime > *& events)
Get the vector of events contained in an EventList; this is overloaded by event type.
Parameters
el :: The EventList to retrieve
[out] events :: reference to a pointer to a vector of this type of event. The pointer will be set to point to the vector.
Exceptions
runtime_error if you call this on the wrong type of EventList.
Definition at line 4447 of file EventList.cpp.
References Mantid::DataObjects::EventList::getWeightedEventsNoTime().
initAngularCaches()
DetectorAngularCache Mantid::DataObjects::initAngularCaches (const MatrixWorkspace *const workspace)
Create angular caches.
A map detector ID and Q ranges This method looks unnecessary as it could be calculated on the fly but the parallelization means that lazy instantation slows it down due to the necessary CRITICAL sections required to update the cache.
The Q range values are required very frequently so the total time is more than offset by this precaching step
Determine width from shape geometry. A group is assumed to contain detectors with the same shape & r, twoTheta value, i.e. a ring mapped-group The shape is retrieved and rotated to match the rotation of the detector. The angular width is computed using the l2 distance from the sample
Determine width from shape geometry. A group is assumed to contain detectors with the same shape & r, twoTheta value, i.e. a ring mapped-group The shape is retrieved and rotated to match the rotation of the detector. The angular width is computed using the l2 distance from the sample
Definition at line 211 of file ReflectometryTransform.cpp.
References Mantid::DataObjects::DetectorAngularCache::detectorHeights, Mantid::Kernel::l2, Mantid::Geometry::BoundingBox::maxPoint(), Mantid::Geometry::BoundingBox::minPoint(), Mantid::Geometry::rad2deg, Mantid::Kernel::twoTheta, Mantid::DataObjects::DetectorAngularCache::twoThetas, Mantid::DataObjects::DetectorAngularCache::twoThetaWidths, and workspace.
Referenced by Mantid::DataObjects::ReflectometryTransform::executeNormPoly().
operator<<()
ostream & Mantid::DataObjects::operator<< (std::ostream & os, const WeightedEvent & event)
Output a string representation of the event to a stream.
Parameters
os :: Stream
event :: WeightedEvent to output to the stream
Definition at line 115 of file Events.cpp.
pointInWorkspace()
bool Mantid::DataObjects::pointInWorkspace (const MDHistoWorkspace * ws, const VMD & point)
Returns
true if the point is within the workspace (including the max edges)
Definition at line 447 of file MDHistoWorkspace.cpp.
References Mantid::Geometry::d, Mantid::API::MDGeometry::getDimension(), and Mantid::API::MDGeometry::getNumDims().
Referenced by Mantid::DataObjects::MDHistoWorkspace::getBinBoundariesOnLine().
saveMatrix()
template<typename T > void Mantid::DataObjects::saveMatrix (Mantid::Nexus::File *const file, const std::string & name, Kernel::Matrix< T > & m, NXnumtype type, const std::string & tag)
Save routine for a generic matrix.
Parameters
file : pointer to the NeXus file
name : the tag in the NeXus file to save under
m : matrix to save
type : NXnumtype for the matrix data
tag : id for an affine matrix conversion
Definition at line 856 of file MDBoxFlatTree.cpp.
References Mantid::Geometry::m, and name.
SortBoxesByID()
template<typename BOXTYPE > bool Mantid::DataObjects::SortBoxesByID (const BOXTYPE & a, const BOXTYPE & b)
Comparator for sorting MDBoxBase'es by ID.
Definition at line 443 of file MDEventWorkspace.hxx.
References SortBoxesByID().
Referenced by SortBoxesByID().
swap() [1/3]
void Mantid::DataObjects::swap (CoordTransformAffine & obj1, CoordTransformAffine & obj2)
Definition at line 53 of file CoordTransformAffine.cpp.
swap() [2/3]
template<size_t nd> void Mantid::DataObjects::swap (MDLeanEvent< nd > & first, MDLeanEvent< nd > & second)
Referenced by Mantid::Algorithms::DiffractionFocussing2::cleanup(), and Mantid::DataObjects::MDLeanEvent< nd >::operator=().
swap() [3/3]
template<size_t ND> void Mantid::DataObjects::swap (MDLeanEvent< ND > & first, MDLeanEvent< ND > & second)
Definition at line 390 of file MDLeanEvent.h.
References Mantid::DataObjects::MDLeanEvent< nd >::errorSquared, Mantid::DataObjects::MDLeanEvent< nd >::index, and Mantid::DataObjects::MDLeanEvent< nd >::signal.
Variable Documentation
EventHeaders
const char* Mantid::DataObjects::EventHeaders[]
Initial value:
= {"signal, errorSquared, center (each dim.)",
                              "signal, errorSquared, expInfoIndex, goniometerIndex, detectorId, center (each "
                              "dim.)"}
Definition at line 26 of file BoxControllerNeXusIO.cpp.
Referenced by Mantid::DataObjects::BoxControllerNeXusIO::BoxControllerNeXusIO().
g_log
Mantid::Kernel::Logger Mantid::DataObjects::g_log("PeaksWorkspace") ("PeaksWorkspace")
Register the workspace as a type.
MDBin< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 1 >, 1 >
Definition at line 149 of file MDEventFactory.cpp.
MDBin< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 2 >, 2 >
Definition at line 150 of file MDEventFactory.cpp.
MDBin< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 3 >, 3 >
Definition at line 151 of file MDEventFactory.cpp.
MDBin< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 4 >, 4 >
Definition at line 152 of file MDEventFactory.cpp.
MDBin< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 5 >, 5 >
Definition at line 153 of file MDEventFactory.cpp.
MDBin< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 6 >, 6 >
Definition at line 154 of file MDEventFactory.cpp.
MDBin< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 7 >, 7 >
Definition at line 155 of file MDEventFactory.cpp.
MDBin< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 8 >, 8 >
Definition at line 156 of file MDEventFactory.cpp.
MDBin< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBin< MDEvent< 9 >, 9 >
Definition at line 157 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 1 >, 1 >
Definition at line 140 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 2 >, 2 >
Definition at line 141 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 3 >, 3 >
Definition at line 142 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 4 >, 4 >
Definition at line 143 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 5 >, 5 >
Definition at line 144 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 6 >, 6 >
Definition at line 145 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 7 >, 7 >
Definition at line 146 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 8 >, 8 >
Definition at line 147 of file MDEventFactory.cpp.
MDBin< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBin< MDLeanEvent< 9 >, 9 >
Definition at line 148 of file MDEventFactory.cpp.
MDBox< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 1 >, 1 >
Definition at line 89 of file MDEventFactory.cpp.
MDBox< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 2 >, 2 >
Definition at line 90 of file MDEventFactory.cpp.
MDBox< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 3 >, 3 >
Definition at line 91 of file MDEventFactory.cpp.
MDBox< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 4 >, 4 >
Definition at line 92 of file MDEventFactory.cpp.
MDBox< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 5 >, 5 >
Definition at line 93 of file MDEventFactory.cpp.
MDBox< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 6 >, 6 >
Definition at line 94 of file MDEventFactory.cpp.
MDBox< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 7 >, 7 >
Definition at line 95 of file MDEventFactory.cpp.
MDBox< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 8 >, 8 >
Definition at line 96 of file MDEventFactory.cpp.
MDBox< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBox< MDEvent< 9 >, 9 >
Definition at line 97 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 1 >, 1 >
Definition at line 80 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 2 >, 2 >
Definition at line 81 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 3 >, 3 >
Definition at line 82 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 4 >, 4 >
Definition at line 83 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 5 >, 5 >
Definition at line 84 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 6 >, 6 >
Definition at line 85 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 7 >, 7 >
Definition at line 86 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 8 >, 8 >
Definition at line 87 of file MDEventFactory.cpp.
MDBox< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBox< MDLeanEvent< 9 >, 9 >
Definition at line 88 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 1 >, 1 >
Definition at line 69 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 2 >, 2 >
Definition at line 70 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 3 >, 3 >
Definition at line 71 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 4 >, 4 >
Definition at line 72 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 5 >, 5 >
Definition at line 73 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 6 >, 6 >
Definition at line 74 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 7 >, 7 >
Definition at line 75 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 8 >, 8 >
Definition at line 76 of file MDEventFactory.cpp.
MDBoxBase< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDEvent< 9 >, 9 >
Definition at line 77 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 1 >, 1 >
Definition at line 60 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 2 >, 2 >
Definition at line 61 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 3 >, 3 >
Definition at line 62 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 4 >, 4 >
Definition at line 63 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 5 >, 5 >
Definition at line 64 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 6 >, 6 >
Definition at line 65 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 7 >, 7 >
Definition at line 66 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 8 >, 8 >
Definition at line 67 of file MDEventFactory.cpp.
MDBoxBase< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBoxBase< MDLeanEvent< 9 >, 9 >
Definition at line 68 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 1 >, 1 >
Definition at line 169 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 2 >, 2 >
Definition at line 170 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 3 >, 3 >
Definition at line 171 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 4 >, 4 >
Definition at line 172 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 5 >, 5 >
Definition at line 173 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 6 >, 6 >
Definition at line 174 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 7 >, 7 >
Definition at line 175 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 8 >, 8 >
Definition at line 176 of file MDEventFactory.cpp.
MDBoxIterator< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDEvent< 9 >, 9 >
Definition at line 177 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 1 >, 1 >
Definition at line 160 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 2 >, 2 >
Definition at line 161 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 3 >, 3 >
Definition at line 162 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 4 >, 4 >
Definition at line 163 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 5 >, 5 >
Definition at line 164 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 6 >, 6 >
Definition at line 165 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 7 >, 7 >
Definition at line 166 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 8 >, 8 >
Definition at line 167 of file MDEventFactory.cpp.
MDBoxIterator< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDBoxIterator< MDLeanEvent< 9 >, 9 >
Definition at line 168 of file MDEventFactory.cpp.
MDEvent< 1 >
template class DLLExport Mantid::DataObjects::MDEvent< 1 >
Definition at line 50 of file MDEventFactory.cpp.
MDEvent< 2 >
template class DLLExport Mantid::DataObjects::MDEvent< 2 >
Definition at line 51 of file MDEventFactory.cpp.
MDEvent< 3 >
template class DLLExport Mantid::DataObjects::MDEvent< 3 >
Definition at line 52 of file MDEventFactory.cpp.
MDEvent< 4 >
template class DLLExport Mantid::DataObjects::MDEvent< 4 >
Definition at line 53 of file MDEventFactory.cpp.
MDEvent< 5 >
template class DLLExport Mantid::DataObjects::MDEvent< 5 >
Definition at line 54 of file MDEventFactory.cpp.
MDEvent< 6 >
template class DLLExport Mantid::DataObjects::MDEvent< 6 >
Definition at line 55 of file MDEventFactory.cpp.
MDEvent< 7 >
template class DLLExport Mantid::DataObjects::MDEvent< 7 >
Definition at line 56 of file MDEventFactory.cpp.
MDEvent< 8 >
template class DLLExport Mantid::DataObjects::MDEvent< 8 >
Definition at line 57 of file MDEventFactory.cpp.
MDEvent< 9 >
template class DLLExport Mantid::DataObjects::MDEvent< 9 >
Definition at line 58 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 1 >, 1 >
Definition at line 109 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 2 >, 2 >
Definition at line 110 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 3 >, 3 >
Definition at line 111 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 4 >, 4 >
Definition at line 112 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 5 >, 5 >
Definition at line 113 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 6 >, 6 >
Definition at line 114 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 7 >, 7 >
Definition at line 115 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 8 >, 8 >
Definition at line 116 of file MDEventFactory.cpp.
MDEventWorkspace< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDEvent< 9 >, 9 >
Definition at line 117 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 1 >, 1 >
Definition at line 100 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 2 >, 2 >
Definition at line 101 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 3 >, 3 >
Definition at line 102 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 4 >, 4 >
Definition at line 103 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 5 >, 5 >
Definition at line 104 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 6 >, 6 >
Definition at line 105 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 7 >, 7 >
Definition at line 106 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 8 >, 8 >
Definition at line 107 of file MDEventFactory.cpp.
MDEventWorkspace< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDEventWorkspace< MDLeanEvent< 9 >, 9 >
Definition at line 108 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 1 >, 1 >
Definition at line 129 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 2 >, 2 >
Definition at line 130 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 3 >, 3 >
Definition at line 131 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 4 >, 4 >
Definition at line 132 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 5 >, 5 >
Definition at line 133 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 6 >, 6 >
Definition at line 134 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 7 >, 7 >
Definition at line 135 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 8 >, 8 >
Definition at line 136 of file MDEventFactory.cpp.
MDGridBox< MDEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDEvent< 9 >, 9 >
Definition at line 137 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 1 >, 1 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 1 >, 1 >
Definition at line 120 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 2 >, 2 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 2 >, 2 >
Definition at line 121 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 3 >, 3 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 3 >, 3 >
Definition at line 122 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 4 >, 4 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 4 >, 4 >
Definition at line 123 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 5 >, 5 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 5 >, 5 >
Definition at line 124 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 6 >, 6 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 6 >, 6 >
Definition at line 125 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 7 >, 7 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 7 >, 7 >
Definition at line 126 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 8 >, 8 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 8 >, 8 >
Definition at line 127 of file MDEventFactory.cpp.
MDGridBox< MDLeanEvent< 9 >, 9 >
template class DLLExport Mantid::DataObjects::MDGridBox< MDLeanEvent< 9 >, 9 >
Definition at line 128 of file MDEventFactory.cpp.
MDLeanEvent< 1 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 1 >
Definition at line 40 of file MDEventFactory.cpp.
MDLeanEvent< 2 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 2 >
Definition at line 41 of file MDEventFactory.cpp.
MDLeanEvent< 3 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 3 >
Definition at line 42 of file MDEventFactory.cpp.
MDLeanEvent< 4 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 4 >
Definition at line 43 of file MDEventFactory.cpp.
MDLeanEvent< 5 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 5 >
Definition at line 44 of file MDEventFactory.cpp.
MDLeanEvent< 6 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 6 >
Definition at line 45 of file MDEventFactory.cpp.
MDLeanEvent< 7 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 7 >
Definition at line 46 of file MDEventFactory.cpp.
MDLeanEvent< 8 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 8 >
Definition at line 47 of file MDEventFactory.cpp.
MDLeanEvent< 9 >
template class DLLExport Mantid::DataObjects::MDLeanEvent< 9 >
Definition at line 48 of file MDEventFactory.cpp.
PEAK_ELLIPSOID_DIMS
constexpr size_t Mantid::DataObjects::PEAK_ELLIPSOID_DIMS {3} constexpr
Definition at line 14 of file PeakShapeEllipsoid_fwd.h.