Mantid: Mantid::NeXus::NXObject Class Reference
Mantid::NeXus::NXObject Class Reference abstract
The base abstract class for NeXus classes and data sets.
#include <NexusClasses.h>
Public Member Functions
std::string name () const
Returns the name of the object.
virtual std::string NX_class () const =0
Return the NX class name for a class (HDF group) or "SDS" for a data set;.
NXObject (const NXhandle fileID, const NXClass *parent, const std::string &name)
NXObject constructor.
std::string path () const
Returns the absolute path to the object.
virtual ~NXObject ()=default
Public Attributes
NXAttributes attributes
Attributes.
NXhandle m_fileID
Nexus file id.
Protected Attributes
bool m_open
Set to true if the object has been open.
std::string m_path
Keeps the absolute path to the object.
Private Member Functions
void getAttributes ()
Reads in attributes.
NXObject ()
Private default constructor.
Friends
class NXClass
a friend class declaration
class NXDataSet
a friend class declaration
class NXRoot
a friend class declaration
Detailed Description
The base abstract class for NeXus classes and data sets.
NX classes and data sets are defined at www.nexusformat.org
Definition at line 93 of file NexusClasses.h.
Constructor & Destructor Documentation
NXObject() [1/2]
Mantid::NeXus::NXObject::NXObject (const NXhandle fileID, const NXClass * parent, const std::string & name)
NXObject constructor.
Parameters
fileID :: The Nexus file id
parent :: The parent Nexus class. In terms of HDF it is the group containing the object.
name :: The name of the object relative to its parent
Definition at line 70 of file NexusClasses.cpp.
References m_path, name(), and path().
~NXObject()
virtual Mantid::NeXus::NXObject::~NXObject () virtual default
NXObject() [2/2]
Mantid::NeXus::NXObject::NXObject () inline private
Private default constructor.
Definition at line 119 of file NexusClasses.h.
Member Function Documentation
getAttributes()
void Mantid::NeXus::NXObject::getAttributes () private
Reads in attributes.
Definition at line 87 of file NexusClasses.cpp.
References attributes, m_fileID, Mantid::NeXus::NXAttributes::set(), and value.
Referenced by Mantid::NeXus::NXDataSet::open(), and Mantid::NeXus::NXDataSet::openLocal().
name()
std::string Mantid::NeXus::NXObject::name () const
Returns the name of the object.
Definition at line 77 of file NexusClasses.cpp.
References m_path.
Referenced by Mantid::NeXus::NXClass::close(), Mantid::NeXus::NXLog::createSingleValueProperty(), Mantid::NeXus::NXLog::createTimeSeries(), Mantid::NeXus::NXClass::getDataSetInfo(), Mantid::NeXus::NXClass::getDouble(), Mantid::NeXus::NXClass::getFloat(), Mantid::NeXus::NXClass::getInt(), Mantid::NeXus::NXClass::getString(), NXObject(), Mantid::NeXus::NXClass::open(), and Mantid::NeXus::NXClass::openLocal().
NX_class()
virtual std::string Mantid::NeXus::NXObject::NX_class () const pure virtual
Return the NX class name for a class (HDF group) or "SDS" for a data set;.
Implemented in Mantid::NeXus::NXDataSet, Mantid::NeXus::NXClass, Mantid::NeXus::NXLog, Mantid::NeXus::NXNote, Mantid::NeXus::NXData, Mantid::NeXus::NXDetector, Mantid::NeXus::NXDiskChopper, Mantid::NeXus::NXInstrument, Mantid::NeXus::NXEntry, and Mantid::NeXus::NXRoot.
path()
std::string Mantid::NeXus::NXObject::path () const inline
Returns the absolute path to the object.
Definition at line 107 of file NexusClasses.h.
Referenced by Mantid::NeXus::NXDataSetTyped< T >::alloc(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::NeXus::NXClass::isValid(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), NXObject(), Mantid::NeXus::NXDataSetTyped< T >::operator()(), and Mantid::NeXus::NXDataSetTyped< T >::operator[]().
Friends And Related Function Documentation
NXClass
friend class NXClass friend
a friend class declaration
Definition at line 95 of file NexusClasses.h.
NXDataSet
friend class NXDataSet friend
a friend class declaration
Definition at line 94 of file NexusClasses.h.
NXRoot
friend class NXRoot friend
a friend class declaration
Definition at line 96 of file NexusClasses.h.
Member Data Documentation
attributes
NXAttributes Mantid::NeXus::NXObject::attributes
Attributes.
Definition at line 111 of file NexusClasses.h.
Referenced by Mantid::NeXus::NXLog::createTimeSeries(), Mantid::DataHandling::LoadMuonNexus1::exec(), getAttributes(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadNexusProcessed::loadEventEntry(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadFirstGoodDataFromNexus(), Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadLastGoodDataFromNexus(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadNexusProcessed::loadNumericColumn(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), Mantid::DataHandling::LoadISISNexusHelper::loadRunDetails(), Mantid::DataHandling::LoadNexusProcessed::loadTableEntry(), Mantid::DataHandling::LoadNexusProcessed::loadV3DColumn(), Mantid::DataHandling::LoadNexusProcessed::loadVectorColumn(), and Mantid::NeXus::NXData::openData().
m_fileID
NXhandle Mantid::NeXus::NXObject::m_fileID
Nexus file id.
Definition at line 113 of file NexusClasses.h.
Referenced by Mantid::NeXus::NXBinary::binary(), Mantid::NeXus::NXClass::close(), Mantid::NeXus::NXNote::data(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadNexusProcessed::exec(), getAttributes(), Mantid::NeXus::NXDataSet::getData(), Mantid::NeXus::NXClass::getNextEntry(), Mantid::NeXus::NXDataSet::getSlab(), Mantid::NeXus::NXClass::isValid(), Mantid::NeXus::NXRoot::NXRoot(), Mantid::NeXus::NXDataSet::open(), Mantid::NeXus::NXClass::open(), Mantid::NeXus::NXDataSet::openLocal(), Mantid::NeXus::NXClass::openLocal(), Mantid::NeXus::NXClass::readAllInfo(), Mantid::NeXus::NXClass::reset(), and Mantid::NeXus::NXRoot::~NXRoot().
m_open
bool Mantid::NeXus::NXObject::m_open protected
Set to true if the object has been open.
Definition at line 117 of file NexusClasses.h.
Referenced by Mantid::NeXus::NXClass::close(), Mantid::NeXus::NXClass::open(), and Mantid::NeXus::NXClass::openLocal().
m_path
std::string Mantid::NeXus::NXObject::m_path protected
Keeps the absolute path to the object.
Definition at line 116 of file NexusClasses.h.
Referenced by Mantid::NeXus::NXClass::close(), name(), NXObject(), Mantid::NeXus::NXDataSet::open(), and Mantid::NeXus::NXClass::open().
The documentation for this class was generated from the following files:
Framework/Nexus/inc/MantidNexus/NexusClasses.h
Framework/Nexus/src/NexusClasses.cpp