Mantid: Mantid::Kernel::Detail Namespace Reference
Mantid::Kernel::Detail Namespace Reference
Classes
struct IsEmpty
Defines the concept of emptiness.
Functions
template<>
DLLExport bool checkIsEmpty (const double &value)
Specialization of checkIsEmpty for double values.
template<>
DLLExport bool checkIsEmpty (const int &value)
Specialization of checkIsEmpty for int.
template<>
DLLExport bool checkIsEmpty (const long &value)
Specialization of checkIsEmpty for long.
template<>
DLLExport bool checkIsEmpty (const OptionalBool &value)
Specialization of checkIsEmpty for OptionalBool.
template<>
DLLExport bool checkIsEmpty (const std::string &value)
Specialization of checkIsEmpty for string.
template<typename T >
bool checkIsEmpty (const std::vector< T > &value)
Specialization for any vector type.
template<typename T >
DLLExport bool checkIsEmpty (const T &)
Forward declare checking function.
Function Documentation
checkIsEmpty() [1/7]
template<> DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const double & value)
Specialization of checkIsEmpty for double values.
Parameters
value :: A double
Returns
True if the value is considered empty, see EmptyValues.h
Definition at line 27 of file MandatoryValidator.cpp.
References Mantid::EMPTY_DBL(), and value.
checkIsEmpty() [2/7]
template<> DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const int & value)
Specialization of checkIsEmpty for int.
Parameters
value :: A int value
Returns
True if the value is considered empty, see EmptyValues.h
Definition at line 33 of file MandatoryValidator.cpp.
References Mantid::EMPTY_INT(), and value.
checkIsEmpty() [3/7]
template<> DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const long & value)
Specialization of checkIsEmpty for long.
Parameters
value :: A long value
Returns
True if the value is considered empty, see EmptyValues.h
Definition at line 39 of file MandatoryValidator.cpp.
References Mantid::EMPTY_LONG(), and value.
checkIsEmpty() [4/7]
template<> DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const OptionalBool & value)
Specialization of checkIsEmpty for OptionalBool.
Parameters
value :: A long value
Returns
True if the value is considered empty, see EmptyValues.h
Definition at line 56 of file MandatoryValidator.cpp.
References Mantid::Kernel::OptionalBool::Unset, and value.
checkIsEmpty() [5/7]
template<> DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const std::string & value)
Specialization of checkIsEmpty for string.
Parameters
value :: A string object
Returns
True if the string is considered empty
Definition at line 21 of file MandatoryValidator.cpp.
References value.
checkIsEmpty() [6/7]
template<typename T > bool Mantid::Kernel::Detail::checkIsEmpty (const std::vector< T > & value)
Specialization for any vector type.
Definition at line 20 of file MandatoryValidator.h.
References value.
checkIsEmpty() [7/7]
template<typename T > DLLExport bool Mantid::Kernel::Detail::checkIsEmpty (const T &)
Forward declare checking function.
Referenced by Mantid::Kernel::Detail::IsEmpty< T >::check().