Mantid: Mantid::Geometry::Detector Class Reference
Mantid::Geometry::Detector Class Reference
This class represents a detector - i.e.
#include <Detector.h>
Public Member Functions
Component * clone () const override
Virtual Copy Constructor.
Detector * cloneParameterized (const ParameterMap *map) const override
Create a cloned instance with a parameter map applied.
Detector (const std::string &name, int id, const std::shared_ptr< IObject > &shape, IComponent *parent)
Constructor.
Detector (const std::string &name, int id, IComponent *parent)
Constructor.
double getDistance (const IComponent &comp) const override
Get the distance between the detector and another component.
detid_t getID () const override
Gets the detector id.
double getPhi () const override
Get the phi angle between the detector with reference to the origin This function will not be supported in Instrument-2.0 due to its ambiguity.
double getPhiOffset (const double &offset) const override
Calculate the phi angle between detector and beam, and then offset.
double getSignedTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis, const Kernel::V3D &instrumentUp) const override
Get the two theata angle signed according the quadrant.
det_topology getTopology (Kernel::V3D &center) const override
returns the detector's topology, namely, the meaning of the detector's angular measurements.
double getTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis) const override
Get the twotheta angle between the detector and an observer.
size_t index () const override
Helper for legacy access mode. Returns the index of the detector.
std::size_t nDets () const override
A Detector object represents a single physical detector.
const ParameterMap & parameterMap () const override
Helper for legacy access mode. Returns a reference to the ParameterMap.
virtual size_t registerContents (class ComponentVisitor &componentVisitor) const override
std::string type () const override
A string representation of the component type.
Public Member Functions inherited from Mantid::Geometry::IDetector
IDetector ()
(Empty) Constructor.
Public Member Functions inherited from Mantid::Geometry::IObjComponent
GeometryHandler * Handle () const
Gets the GeometryHandler.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
~IObjComponent () override
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual ~IComponent ()=default
Destructor.
Public Member Functions inherited from Mantid::Geometry::ObjComponent
void boundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) const
IComponent * clone () const override
Virtual Copy Constructor.
void draw () const override
Draws the objcomponent, If the handler is not set then this function does nothing.
void drawObject () const override
Draws the Object.
void getBoundingBox (BoundingBox &absoluteBB) const override
get bounding box, which may or may not be axis aligned;
virtual double getDepth () const
get Depth (Z-dimension) value for component
virtual double getHeight () const
get Height (Y-dimension) value for component
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
virtual double getWidth () const
get Width (X-dimension) value for component
void initDraw () const override
Initializes the ObjComponent for rendering, this function should be called before rendering.
int interceptSurface (Track &track) const override
Checks whether the track given will pass through this Component.
bool isOnSide (const Kernel::V3D &point) const override
Does the point given lie on the surface of this object component?
bool isValid (const Kernel::V3D &point) const override
Does the point given lie within this object component?
const Kernel::Material material () const override
Return the material this component is made from.
ObjComponent (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
ObjComponent (const std::string &name, IComponent *parent=nullptr)
Constructor.
ObjComponent (const std::string &name, std::shared_ptr< const IObject > shape, IComponent *parent=nullptr)
Constructor.
void setShape (std::shared_ptr< const IObject > newShape)
Set a new shape on the component void setShape(std::shared_ptr<const IObject> newShape);.
const std::shared_ptr< const IObject > shape () const override
Return the shape of the component.
double solidAngle (const Geometry::SolidAngleParams &params) const override
Finds the approximate solid angle covered by the component when viewed from the point given.
std::string type () const override
type string
Public Member Functions inherited from Mantid::Geometry::Component
Component ()
Create Empty Component at Origin, with no orientation and null parent.
Component (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
Component (std::string name, const Kernel::V3D &position, const Kernel::Quat &rotation, IComponent *parent=nullptr)
Create a named component with positioning vector, orientation and parent.
Component (std::string name, const Kernel::V3D &position, IComponent *parent=nullptr)
Create a named component with positioning vector, and parent component.
Component (std::string name, IComponent *parent=nullptr)
Create a named component with a parent component (optional)
std::vector< std::shared_ptr< const IComponent > > getAncestors () const override
Return an array of all ancestors.
IComponent const * getBaseComponent () const override
Returns const pointer to base component if this component is parametrized.
ComponentID getComponentID () const override
Returns the ComponentID - a unique identifier of the component.
std::string getFullName () const override
Get the full pathname.
std::string getName () const override
Get the IComponent name.
std::shared_ptr< const IComponent > getParent () const override
Return a pointer to the current parent. as shared pointer.
Kernel::V3D getPos () const override
Get the position of the IComponent. Tree structure is traverse through the.
Kernel::V3D getRelativePos () const override
Get the position relative to the parent IComponent (absolute if no parent)
Kernel::Quat getRelativeRot () const override
Get the relative Orientation.
Kernel::Quat getRotation () const override
Get the absolute orientation of the IComponent.
std::optional< Kernel::V2D > getSideBySideViewPos () const override
Return the position of the component required on the instrument side by side view.
bool isParentNamed (const std::string &expectedName, int maxDepth=-1) const
Return true if one of the parents of this component is named something.
void rotate (const Kernel::Quat &) override
Rotate the IComponent. This is relative to parent.
void rotate (double, const Kernel::V3D &) override
Rotate the IComponent by an angle in degrees with respect to an axis.
void setName (const std::string &) override
Set the IComponent name.
void setParent (IComponent *) override
Assign a parent IComponent. Previous parent link is lost.
void setPos (const Kernel::V3D &) override
Set the position of the Component The position is with respect to the parent Component.
void setPos (double, double, double) override
Set the IComponent position, x, y, z respective to parent (if present)
void setRot (const Kernel::Quat &) override
Set the orientation Kernel::Quaternion relative to parent (if present)
void setSideBySideViewPos (const Kernel::V2D &) override
Set the IComponent position in the side by side instrument view.
void translate (const Kernel::V3D &) override
Translate the IComponent (vector form). This is relative to parent if.
void translate (double, double, double) override
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string typeName () const
std::set< std::string > getParameterNames (bool recursive=true) const override
Return the parameter names.
std::map< std::string, ComponentID > getParameterNamesByComponent () const override
return the parameter names and the component they are from
bool hasParameter (const std::string &name, bool recursive=true) const override
Returns a boolean indicating if the component has the named parameter.
std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a double.
std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an int.
std::string getParameterType (const std::string &pname, bool recursive=true) const override
Get a parameter's type – this is HACK until Python can export property regardless of the property type.
std::string getDescription () const
Get this component parameter's description – no recursive search within children.
std::string getParamDescription (const std::string &pname, bool recursive=true) const
Get description of a parameter attached to this component
std::string getParamShortDescription (const std::string &pname, bool recursive=true) const
Get a component's parameter short description.
std::string getShortDescription () const
Get a components's short description.
void setDescription (const std::string &descr)
Set components description.
std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a bool.
std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::V3D.
std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::Quaternion.
std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a string.
std::string getParameterAsString (const std::string &pname, bool recursive=true) const override
get a string representation of a parameter
bool getParameterVisible (const std::string &p_name, bool recursive) const override
Get a visibility attribute of a parameter from the parameter map.
double getFittingParameter (const std::string &pname, double xvalue) const
Get fitting parameter.
void printSelf (std::ostream &) const override
Prints a text representation of itself.
const IComponent * base () const
Returns the address of the base component.
Kernel::V3D getScaleFactor () const override
Returns the ScaleFactor.
const IComponent * getBareParent () const override
Returns the bare pointer to the IComponent parent.
virtual void readXMLAttributes (const Poco::XML::Attributes &attr)
Reads the XML attributes from Poco XML parser.
virtual void writeXML (Poco::XML::XMLWriter &writer) const
virtual void appendXML (std::ostream &xmlStream) const
Append to an open XML string.
bool isParametrized () const override
Return true if the Component is, in fact, parametrized (that is - it has a valid parameter map)
bool hasComponentInfo () const
size_t index () const
Helper for legacy access mode. Returns the index of the component.
Protected Member Functions
Detector (const Detector *base, const ParameterMap *map)
Constructor for parametrized version.
bool hasDetectorInfo () const
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Protected Member Functions inherited from Mantid::Geometry::ObjComponent
const Kernel::V3D factorOutComponentPosition (const Kernel::V3D &point) const
Find the point that's in the same place relative to the constituent geometrical Object if the position and rotation introduced by the Component is ignored.
const Kernel::V3D takeOutRotation (Kernel::V3D point) const
Rotates a point by the reverse of the component's rotation.
Protected Member Functions inherited from Mantid::Geometry::Component
template<class TYPE >
std::vector< TYPE > getParameter (const std::string &p_name, bool recursive) const
Get a parameter from the parameter map.
void swap (const Component *base, const ParameterMap *pmap)
Swap the current references to the un-parameterized component and parameter map for new ones.
Private Attributes
const detid_t m_id
The detector id.
Additional Inherited Members
Protected Attributes inherited from Mantid::Geometry::ObjComponent
std::shared_ptr< const IObject > m_shape
The physical geometry representation.
Protected Attributes inherited from Mantid::Geometry::Component
const IComponent * m_parent
Parent component in the tree.
const Component * m_base
The base component - this is the unmodified component (without the parameters).
const ParameterMap * m_map
A pointer to const ParameterMap containing the parameters.
std::string m_name
Name of the component.
Kernel::V3D m_pos
Position w.
Kernel::Quat m_rot
Orientation.
std::optional< Kernel::V2D > m_sidebysideviewpos
Position of component in instrument viewer side by side view.
Detailed Description
This class represents a detector - i.e.
a single pixel in an instrument. It is An extension of the ObjectComponent class to add a detector id.
Version
A
Author
Laurent C Chapon, ISIS RAL
Date
01/11/2007
Definition at line 30 of file Detector.h.
Constructor & Destructor Documentation
Detector() [1/3]
Mantid::Geometry::Detector::Detector (const std::string & name, int id, IComponent * parent)
Constructor.
Parameters
name :: The name of the component
id :: Index for the component
parent :: The parent component
Definition at line 35 of file Detector.cpp.
Detector() [2/3]
Mantid::Geometry::Detector::Detector (const std::string & name, int id, const std::shared_ptr< IObject > & shape, IComponent * parent)
Constructor.
Parameters
name :: The name of the component
id :: Index for the component
shape :: A pointer to the object describing the shape of this component
parent :: The parent component
Definition at line 45 of file Detector.cpp.
Detector() [3/3]
Mantid::Geometry::Detector::Detector (const Detector * base, const ParameterMap * map) protected
Constructor for parametrized version.
Constructor for a parametrized Detector.
Parameters
base the base (un-parametrized) IComponent
map pointer to the ParameterMap
Definition at line 28 of file Detector.cpp.
Member Function Documentation
clone()
Component * Mantid::Geometry::Detector::clone () const inline override virtual
Virtual Copy Constructor.
Returns
A pointer to a copy of the input ObjComponent
Implements Mantid::Geometry::IObjComponent.
Definition at line 38 of file Detector.h.
cloneParameterized()
Detector * Mantid::Geometry::Detector::cloneParameterized (const ParameterMap * map) const inline override virtual
Create a cloned instance with a parameter map applied.
Implements Mantid::Geometry::IDetector.
Reimplemented in Mantid::Geometry::GridDetectorPixel.
Definition at line 41 of file Detector.h.
getDistance()
double Mantid::Geometry::Detector::getDistance (const IComponent & comp) const override virtual
Get the distance between the detector and another component.
Parameters
comp :: The other component
Returns
The distance
Implements Mantid::Geometry::IDetector.
Definition at line 65 of file Detector.cpp.
References Mantid::Geometry::IComponent::getDistance().
getID()
detid_t Mantid::Geometry::Detector::getID () const override virtual
Gets the detector id.
Returns
the detector id
Implements Mantid::Geometry::IDetector.
Definition at line 51 of file Detector.cpp.
References Mantid::Geometry::d, getID(), Mantid::Geometry::Component::m_base, m_id, and Mantid::Geometry::Component::m_map.
Referenced by InstrumentCreationHelper::addFullInstrumentToWorkspace(), Mantid::Crystal::SaveIsawPeaks::bankMasked(), Mantid::Geometry::InstrumentDefinitionParser::createDetectorOrMonitor(), and getID().
getPhi()
double Mantid::Geometry::Detector::getPhi () const override virtual
Get the phi angle between the detector with reference to the origin This function will not be supported in Instrument-2.0 due to its ambiguity.
DO NOT USE IN NEW CODE
Returns
The angle
Implements Mantid::Geometry::IDetector.
Definition at line 100 of file Detector.cpp.
References Mantid::Geometry::Component::getPos().
Referenced by getPhiOffset().
getPhiOffset()
double Mantid::Geometry::Detector::getPhiOffset (const double & offset) const override virtual
Calculate the phi angle between detector and beam, and then offset.
Parameters
offset in radians
Returns
offset phi angle in radians.
Implements Mantid::Geometry::IDetector.
Definition at line 110 of file Detector.cpp.
References getPhi().
getSignedTwoTheta()
double Mantid::Geometry::Detector::getSignedTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis, const Kernel::V3D & instrumentUp) const override virtual
Get the two theata angle signed according the quadrant.
Parameters
observer :: The observer position
axis :: The axis
instrumentUp :: instrument up direction.
Returns
The angle
Implements Mantid::Geometry::IDetector.
Definition at line 83 of file Detector.cpp.
References Mantid::Kernel::V3D::angle(), Mantid::Kernel::V3D::cross_prod(), Mantid::Geometry::Component::getPos(), and Mantid::Kernel::V3D::scalar_prod().
getTopology()
det_topology Mantid::Geometry::Detector::getTopology (Kernel::V3D & center) const override virtual
returns the detector's topology, namely, the meaning of the detector's angular measurements.
It is different in cartesian and cylindrical (surrounding the beam) coordinate system
Implements Mantid::Geometry::IDetector.
Definition at line 120 of file Detector.cpp.
References Mantid::Geometry::Component::getPos(), and Mantid::Geometry::rect.
getTwoTheta()
double Mantid::Geometry::Detector::getTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis) const override virtual
Get the twotheta angle between the detector and an observer.
Parameters
observer :: The observer position
axis :: The axis
Returns
The angle
Implements Mantid::Geometry::IDetector.
Definition at line 71 of file Detector.cpp.
References Mantid::Kernel::V3D::angle(), and Mantid::Geometry::Component::getPos().
hasDetectorInfo()
bool Mantid::Geometry::Detector::hasDetectorInfo () const protected
Definition at line 135 of file Detector.cpp.
References Mantid::Geometry::IComponent::getBareParent(), Mantid::Geometry::ParameterMap::hasDetectorInfo(), Mantid::Geometry::Component::m_base, and Mantid::Geometry::Component::m_map.
Referenced by Mantid::Geometry::GridDetectorPixel::getRelativePos().
index()
size_t Mantid::Geometry::Detector::index () const override virtual
Helper for legacy access mode. Returns the index of the detector.
Implements Mantid::Geometry::IDetector.
Definition at line 129 of file Detector.cpp.
References Mantid::Geometry::ParameterMap::detectorIndex(), m_id, and Mantid::Geometry::Component::m_map.
nDets()
std::size_t Mantid::Geometry::Detector::nDets () const inline override virtual
A Detector object represents a single physical detector.
Implements Mantid::Geometry::IDetector.
Definition at line 43 of file Detector.h.
parameterMap()
const ParameterMap & Mantid::Geometry::Detector::parameterMap () const override virtual
Helper for legacy access mode. Returns a reference to the ParameterMap.
Implements Mantid::Geometry::IDetector.
Definition at line 126 of file Detector.cpp.
References Mantid::Geometry::Component::m_map.
registerContents()
size_t Mantid::Geometry::Detector::registerContents (class ComponentVisitor & componentVisitor) const override virtual
Implements Mantid::Geometry::IComponent.
Definition at line 131 of file Detector.cpp.
References Mantid::Geometry::ComponentVisitor::registerDetector().
type()
std::string Mantid::Geometry::Detector::type () const inline override virtual
A string representation of the component type.
Reimplemented from Mantid::Geometry::IComponent.
Reimplemented in Mantid::Geometry::GridDetectorPixel.
Definition at line 33 of file Detector.h.
Member Data Documentation
m_id
const detid_t Mantid::Geometry::Detector::m_id private
The detector id.
Definition at line 64 of file Detector.h.
Referenced by getID(), and index().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/Detector.h
Framework/Geometry/src/Instrument/Detector.cpp