Mantid: Mantid::Kernel::TopicInfo Class Reference
Mantid::Kernel::TopicInfo Class Reference
TopicInfo : Class that holds information on a kafka topic.
#include <TopicInfo.h>
Public Member Functions
const std::string & name () const
TopicInfo (InstrumentInfo *inst, const Poco::XML::Element *elem)
TopicInfo (std::string name, TopicType type)
TopicType type () const
Private Attributes
std::string m_name
TopicType m_type
Detailed Description
TopicInfo : Class that holds information on a kafka topic.
Definition at line 32 of file TopicInfo.h.
Constructor & Destructor Documentation
TopicInfo() [1/2]
Mantid::Kernel::TopicInfo::TopicInfo (InstrumentInfo * inst, const Poco::XML::Element * elem)
Definition at line 38 of file TopicInfo.cpp.
References Mantid::Kernel::Chopper, Mantid::Kernel::Event, Mantid::Kernel::DateAndTimeHelpers::g_log, m_name, m_type, Mantid::Kernel::Monitor, Mantid::Kernel::InstrumentInfo::name(), Mantid::Kernel::Run, Mantid::Kernel::Sample, type(), and Mantid::Kernel::Logger::warning().
TopicInfo() [2/2]
Mantid::Kernel::TopicInfo::TopicInfo (std::string name, TopicType type)
Definition at line 60 of file TopicInfo.cpp.
Member Function Documentation
name()
const std::string & Mantid::Kernel::TopicInfo::name () const inline
Definition at line 36 of file TopicInfo.h.
Referenced by Mantid::Kernel::operator<<().
type()
TopicType Mantid::Kernel::TopicInfo::type () const inline
Definition at line 37 of file TopicInfo.h.
Referenced by Mantid::Kernel::operator<<(), and TopicInfo().
Member Data Documentation
m_name
std::string Mantid::Kernel::TopicInfo::m_name private
Definition at line 40 of file TopicInfo.h.
Referenced by TopicInfo().
m_type
TopicType Mantid::Kernel::TopicInfo::m_type private
Definition at line 41 of file TopicInfo.h.
Referenced by TopicInfo().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/TopicInfo.h
Framework/Kernel/src/TopicInfo.cpp