Mantid: Mantid::DataHandling::SaveGSASInstrumentFile Class Reference
Mantid::DataHandling::SaveGSASInstrumentFile Class Reference final
SaveGSASInstrumentFile : Convert Fullprof"s instrument resolution file (.irf) to GSAS"s instrument file (.iparm/.prm).
#include <SaveGSASInstrumentFile.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name.
SaveGSASInstrumentFile ()
Constructor.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
const Parallel::Communicator & communicator () const
Returns a const reference to the (MPI) communicator of the algorithm.
void setCommunicator (const Parallel::Communicator &communicator)
Sets the (MPI) communicator of the algorithm.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &) override
void splitByTime (std::vector< Kernel::SplittingInterval > &, std::vector< Kernel::PropertyManager * >) const override
void filterByProperty (const Kernel::TimeSeriesProperty< bool > &, const std::vector< std::string > &) override
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
virtual void addObserver (const Poco::AbstractObserver &observer) const =0
Add an observer for a notification.
virtual const std::string alias () const =0
function to return any aliases of the algorithm.
virtual const std::string aliasDeprecated () const =0
Expiration date (in ISO8601 format) for the algorithm aliases. Empty if no expiration date.
virtual void cancel ()=0
Raises the cancel flag.
virtual const std::vector< std::string > categories () const =0
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const =0
function to return a category of the algorithm.
virtual const std::string categorySeparator () const =0
Function to return the separator token for the category string.
virtual void enableHistoryRecordingForChild (const bool on)=0
If true history will be recorded for a child.
virtual bool execute ()=0
System execution.
virtual void executeAsChildAlg ()=0
Execute as a Child Algorithm, with try/catch.
virtual Poco::ActiveResult< bool > executeAsync ()=0
Asynchronous execution of the algorithm.
virtual ExecutionState executionState () const =0
Gets the current execution state.
virtual AlgorithmID getAlgorithmID () const =0
Algorithm ID.
virtual bool getAlgStartupLogging () const =0
get the state of Logging of start and end messages
virtual bool getAlwaysStoreInADS () const =0
To query whether the output is stored in the analysis data service.
virtual int getLoggingOffset () const =0
returns the logging priority offset
virtual const std::string helpURL () const =0
function to return an optional URL for documentation.
virtual void initialize ()=0
Initialization method invoked by the framework.
virtual bool isChild () const =0
To query whether algorithm is a child. Default to false.
virtual bool isExecuted () const =0
Check whether the algorithm has been executed sucessfully.
virtual bool isInitialized () const =0
Check whether the algorithm is initialized properly.
virtual bool isLogging () const =0
returns the status of logging, True = enabled
virtual bool isReadyForGarbageCollection () const =0
True if the algorithm is ready for garbage collection.
virtual bool isRunning () const =0
True if the algorithm is running.
virtual const std::string name () const =0
function to return a name of the algorithm, must be overridden in all algorithms
virtual void removeObserver (const Poco::AbstractObserver &observer) const =0
Remove an observer.
virtual ResultState resultState () const =0
Gets the currnet result State.
virtual const std::vector< std::string > seeAlso () const =0
Function to return all of the seeAlso algorithms related to this algorithm.
virtual void setAlgStartupLogging (const bool enabled)=0
disable Logging of start and end messages
virtual void setAlwaysStoreInADS (const bool doStore)=0
Set whether we always store the output in the analysis data service.
virtual void setChild (const bool isChild)=0
To set whether algorithm is a child.
virtual void setChildEndProgress (const double endProgress) const =0
setting the child end progress
virtual void setChildStartProgress (const double startProgress) const =0
setting the child start progress
virtual void setLogging (const bool value)=0
Logging can be disabled by passing a value of false.
virtual void setLoggingOffset (const int value)=0
gets the logging priority offset
virtual void setRethrows (const bool rethrow)=0
To query whether an algorithm should rethrow exceptions when executing.
virtual const std::string summary () const =0
function returns a summary message that will be displayed in the default GUI, and in the help.
virtual ::Json::Value toJson () const =0
Serialize an algorithm as Json.
virtual std::string toString () const =0
Serialize an algorithm.
virtual std::map< std::string, std::string > validateInputs ()=0
Method checking errors on ALL the inputs, before execution.
virtual int version () const =0
function to return a version of the algorithm, must be overridden in all algorithms
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual ::Json::Value asJson (bool withDefaultValues=false) const =0
Return the property manager serialized as a json object.
virtual std::string asString (bool withDefaultValues=false) const =0
Return the property manager serialized as a string.
virtual void declareOrReplaceProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
virtual bool existsProperty (const std::string &name) const =0
Checks whether the named property is already in the list of managed property.
virtual void filterByProperty (const TimeSeriesProperty< bool > &, const std::vector< std::string > &)=0
virtual void filterByTime (const Types::Core::DateAndTime &, const Types::Core::DateAndTime &)=0
virtual std::vector< std::string > getDeclaredPropertyNames () const noexcept=0
Get the list of managed property names.
virtual Property * getPointerToProperty (const std::string &name) const =0
Get a pointer to property by name.
virtual const std::vector< Property * > & getProperties () const =0
Get the list of managed properties.
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
virtual TypedValue getProperty (const std::string &name) const =0
Get the value of a property.
virtual std::string getPropertyValue (const std::string &name) const =0
Get the value of a property as a string.
virtual size_t propertyCount () const =0
Returns the number of properties under management.
virtual void removeProperty (const std::string &name, const bool delproperty=true)=0
Removes the property from management.
virtual void resetProperties ()=0
virtual void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all the properties from a json object.
virtual void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false)=0
Sets all properties from a string.
virtual void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >())=0
Sets all the declared properties from a string.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
virtual void setPropertyOrdinal (const int &index, const std::string &value)=0
Set the value of a property by an index.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
virtual void setPropertyValue (const std::string &name, const std::string &value)=0
Sets property value from a string.
virtual void setPropertyValueFromJson (const std::string &name, const Json::Value &value)=0
Sets property value from a Json::Value.
virtual void splitByTime (std::vector< SplittingInterval > &, std::vector< PropertyManager * >) const =0
virtual std::unique_ptr< Property > takeProperty (const size_t index)=0
Removes the property from management and returns a pointer to it.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual bool validateProperties () const =0
Validates all the properties in the collection.
virtual ~IPropertyManager ()=default
Private Member Functions
double aaba (double n, double ea1, double ea2, double ta1, double ta2, double dsp)
Calculate a value related to (alph0, alph1, alph0t, alph1t) or (beta0, beta1, beta0t, beta1t)
void buildGSASTabulatedProfile (const std::map< unsigned int, std::map< std::string, double > > &bankprofilemap, unsigned int bankid)
Build a data structure for GSAS's tabulated peak profile.
double calDspRange (double dtt1, double zero, double tof)
Calcualte d-space value.
double calL2FromDtt1 (double difc, double L1, double twotheta)
Caclualte L2 from DIFFC and L1.
double calTOF (double n, double ep, double eq, double er, double tp, double tq, double tr, double dsp)
Calculate TOF difference.
void convertToGSAS (const std::vector< unsigned int > &outputbankids, const std::string &gsasinstrfilename, const std::map< unsigned int, std::map< std::string, double > > &bankprofilemap)
Convert to GSAS instrument file.
double erfc (double xx)
Complementary error function.
void exec () override
Execution code.
double getProfileParameterValue (const std::map< std::string, double > &profilemap, const std::string &paramname)
Get parameter value from class storage.
double getValueFromMap (const std::map< std::string, double > &profilemap, const std::string &parname)
Get parameter value from a map.
void init () override
Initialisation code.
void initConstants (const std::map< unsigned int, std::map< std::string, double > > &profmap)
Set up some constant by default.
void loadFullprofResolutionFile (const std::string &irffilename)
Load fullprof resolution file.
void parseProfileTableWorkspace (const API::ITableWorkspace_sptr &ws, std::map< unsigned int, std::map< std::string, double > > &profilemap)
Parse profile table workspace to a map.
void processProperties ()
Process properties.
std::shared_ptr< ChopperConfiguration > setupInstrumentConstants (const std::map< unsigned int, std::map< std::string, double > > &profmap)
Set up chopper/instrument constant parameters from profile map.
std::shared_ptr< ChopperConfiguration > setupNOMConstants (int intfrequency)
Set up for NOM chopper constants.
std::shared_ptr< ChopperConfiguration > setupPG3Constants (int intfrequency)
Set up for PG3 chopper constants.
void writePRMHeader (const std::vector< unsigned int > &banks, const std::string &prmfilename)
Write the header of the file.
void writePRMSingleBank (const std::map< unsigned int, std::map< std::string, double > > &bankprofilemap, unsigned int bankid, const std::string &prmfilename)
Write out .prm/.iparm file.
Private Attributes
double m_2theta
2Theta
std::map< unsigned int, double > m_bank_mndsp
std::map< unsigned int, double > m_bank_mxtof
std::shared_ptr< ChopperConfiguration > m_configuration
Chopper configuration.
int m_frequency
Frequency.
std::vector< double > m_galpha
std::vector< double > m_gbeta
std::vector< double > m_gdsp
std::vector< double > m_gdt
std::string m_gsasFileName
Output file name.
std::string m_id_line
User input ID line.
API::ITableWorkspace_sptr m_inpWS
Input workspace.
std::string m_instrument
Instrument.
double m_L1
L1.
double m_L2
L2.
std::map< unsigned int, std::map< std::string, double > > m_profileMap
Profile parameter map.
std::string m_sample
Sample.
std::vector< unsigned int > m_vecBankID2File
Banks IDs to process.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
void exec (Parallel::ExecutionMode executionMode)
Runs the algorithm with the specified execution mode.
virtual void execDistributed ()
Runs the algorithm in distributed execution mode.
virtual void execMasterOnly ()
Runs the algorithm in master-only execution mode.
virtual Parallel::ExecutionMode getParallelExecutionMode (const std::map< std::string, Parallel::StorageMode > &storageModes) const
Get correct execution mode based on input storage modes for an MPI run.
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history for input workspaces to output workspaces and record the history for ths algorithm.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
virtual void afterPropertySet (const std::string &)
Override this method to perform a custom action right after a property was set.
virtual void clear ()=0
Clears all properties under management.
virtual Property * getPointerToPropertyOrdinal (const int &index) const =0
Get a property by an index.
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
SaveGSASInstrumentFile : Convert Fullprof"s instrument resolution file (.irf) to GSAS"s instrument file (.iparm/.prm).
Definition at line 24 of file SaveGSASInstrumentFile.h.
Constructor & Destructor Documentation
SaveGSASInstrumentFile()
Mantid::DataHandling::SaveGSASInstrumentFile::SaveGSASInstrumentFile ()
Constructor.
Definition at line 263 of file SaveGSASInstrumentFile.cpp.
Member Function Documentation
aaba()
double Mantid::DataHandling::SaveGSASInstrumentFile::aaba (double n, double ea1, double ea2, double ta1, double ta2, double dsp) private
Calculate a value related to (alph0, alph1, alph0t, alph1t) or (beta0, beta1, beta0t, beta1t)
Calculate a value related to alph0, alph1, alph0t, alph1t or beta0, beta1, beta0t, beta1t.
Definition at line 931 of file SaveGSASInstrumentFile.cpp.
References n.
Referenced by buildGSASTabulatedProfile().
buildGSASTabulatedProfile()
void Mantid::DataHandling::SaveGSASInstrumentFile::buildGSASTabulatedProfile (const std::map< unsigned int, std::map< std::string, double > > & bankprofilemap, unsigned int bankid) private
Build a data structure for GSAS's tabulated peak profile.
Build a data structure for GSAS"s tabulated peak profile from Fullprof"s TOF peak profile.
Parameters
bankprofilemap :: map of all banks' peak profile that is stored in map;
bankid :: the ID of the bank to be converted
Definition at line 687 of file SaveGSASInstrumentFile.cpp.
References aaba(), calTOF(), Mantid::Kernel::Logger::debug(), erfc(), Mantid::API::Algorithm::g_log, getProfileParameterValue(), m_configuration, m_galpha, m_gbeta, m_gdsp, and m_gdt.
Referenced by convertToGSAS().
calDspRange()
double Mantid::DataHandling::SaveGSASInstrumentFile::calDspRange (double dtt1, double zero, double tof) private
Calcualte d-space value.
Calcualte range of data on d-spacing from TOF.
Algorithm: use the approximation from Dtt1. The part with thermal neutron has complex operation on d ralated.
Returns
:: d-space value
Definition at line 986 of file SaveGSASInstrumentFile.cpp.
Referenced by setupInstrumentConstants().
calL2FromDtt1()
double Mantid::DataHandling::SaveGSASInstrumentFile::calL2FromDtt1 (double difc, double L1, double twotheta) private
Caclualte L2 from DIFFC and L1.
Calculate L2 from DIFFC and L1 DIFC = 252.816*2sin(theta)sqrt(L1+L2)
Definition at line 896 of file SaveGSASInstrumentFile.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::Kernel::difc, Mantid::API::Algorithm::g_log, and Mantid::Kernel::l2.
Referenced by writePRMSingleBank().
calTOF()
double Mantid::DataHandling::SaveGSASInstrumentFile::calTOF (double n, double ep, double eq, double er, double tp, double tq, double tr, double dsp) private
Calculate TOF difference.
Calculate TOF from d-space value of thermal neutron back-to-back exponential conv.
pseudo-voigt Epithermal: te = zero + d*dtt1 + 0.5*dtt2*erfc((1/d-1.05)*10); Thermal: tt = zerot + d*dtt1t + dtt2t/d; Total TOF: t = n*te + (1-n) tt
Parameters
n :: ratio between thermal neutron and epithermal neutron
ep :: zero
eq :: dtt1
er :: dtt2
tp :: zerot
tq :: dtt1t
tr :: dtt2t
dsp :: d-space value
Definition at line 918 of file SaveGSASInstrumentFile.cpp.
References erfc(), n, and tp.
Referenced by buildGSASTabulatedProfile().
category()
const std::string Mantid::DataHandling::SaveGSASInstrumentFile::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 40 of file SaveGSASInstrumentFile.h.
convertToGSAS()
void Mantid::DataHandling::SaveGSASInstrumentFile::convertToGSAS (const std::vector< unsigned int > & outputbankids, const std::string & gsasinstrfilename, const std::map< unsigned int, std::map< std::string, double > > & bankprofilemap) private
Convert to GSAS instrument file.
Parameters
outputbankids : list of banks (sorted) to .iparm or prm file
gsasinstrfilename string
bankprofilemap :: map containing each bank's profile parameter stored in map.
Definition at line 634 of file SaveGSASInstrumentFile.cpp.
References buildGSASTabulatedProfile(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_bank_mndsp, m_bank_mxtof, m_configuration, writePRMHeader(), and writePRMSingleBank().
Referenced by exec().
erfc()
double Mantid::DataHandling::SaveGSASInstrumentFile::erfc (double xx) private
Complementary error function.
Definition at line 1024 of file SaveGSASInstrumentFile.cpp.
References fabs, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by buildGSASTabulatedProfile(), and calTOF().
exec()
void Mantid::DataHandling::SaveGSASInstrumentFile::exec () override private virtual
Execution code.
Main execution body.
Implements Mantid::API::Algorithm.
Definition at line 314 of file SaveGSASInstrumentFile.cpp.
References convertToGSAS(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, initConstants(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_gsasFileName, m_inpWS, m_vecBankID2File, parseProfileTableWorkspace(), and processProperties().
getProfileParameterValue()
double Mantid::DataHandling::SaveGSASInstrumentFile::getProfileParameterValue (const std::map< std::string, double > & profilemap, const std::string & paramname) private
Get parameter value from class storage.
Get parameter value from m_configuration/m_profile.
Definition at line 961 of file SaveGSASInstrumentFile.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and value.
Referenced by buildGSASTabulatedProfile(), setupInstrumentConstants(), and writePRMSingleBank().
getValueFromMap()
double Mantid::DataHandling::SaveGSASInstrumentFile::getValueFromMap (const std::map< std::string, double > & profilemap, const std::string & parname) private
Get parameter value from a map.
Definition at line 943 of file SaveGSASInstrumentFile.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and value.
init()
void Mantid::DataHandling::SaveGSASInstrumentFile::init () override private virtual
Initialisation code.
Declare properties.
Implements Mantid::API::Algorithm.
Definition at line 271 of file SaveGSASInstrumentFile.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, Mantid::API::FileProperty::OptionalLoad, and Mantid::API::FileProperty::Save.
initConstants()
void Mantid::DataHandling::SaveGSASInstrumentFile::initConstants (const std::map< unsigned int, std::map< std::string, double > > & profmap) private
Set up some constant by default.
Set up some constant by default Output--> m_configuration.
Parameters
profmap :: map of parameters
Definition at line 441 of file SaveGSASInstrumentFile.cpp.
References m_configuration, and setupInstrumentConstants().
Referenced by exec().
loadFullprofResolutionFile()
void Mantid::DataHandling::SaveGSASInstrumentFile::loadFullprofResolutionFile (const std::string & irffilename) private
Load fullprof resolution file.
call LoadFullprofResolution
set output table workspace to m_inpWS
Parameters
irffilename
Definition at line 997 of file SaveGSASInstrumentFile.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and m_inpWS.
Referenced by processProperties().
name()
const std::string Mantid::DataHandling::SaveGSASInstrumentFile::name () const inline override virtual
Algorithm's name.
Implements Mantid::API::Algorithm.
Definition at line 28 of file SaveGSASInstrumentFile.h.
parseProfileTableWorkspace()
void Mantid::DataHandling::SaveGSASInstrumentFile::parseProfileTableWorkspace (const API::ITableWorkspace_sptr & ws, std::map< unsigned int, std::map< std::string, double > > & profilemap) private
Parse profile table workspace to a map.
Parse profile table workspace to a map (the new ...
Definition at line 465 of file SaveGSASInstrumentFile.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), and Mantid::API::TableRow::size().
Referenced by exec().
processProperties()
void Mantid::DataHandling::SaveGSASInstrumentFile::processProperties () private
Process properties.
Process input properties.
Definition at line 359 of file SaveGSASInstrumentFile.cpp.
References Mantid::EMPTY_DBL(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), Mantid::API::Algorithm::isEmpty(), loadFullprofResolutionFile(), m_2theta, m_frequency, m_gsasFileName, m_id_line, m_inpWS, m_instrument, m_L1, m_L2, m_sample, and m_vecBankID2File.
Referenced by exec().
seeAlso()
const std::vector< std::string > Mantid::DataHandling::SaveGSASInstrumentFile::seeAlso () const inline override virtual
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
Reimplemented from Mantid::API::Algorithm.
Definition at line 38 of file SaveGSASInstrumentFile.h.
setupInstrumentConstants()
ChopperConfiguration_sptr Mantid::DataHandling::SaveGSASInstrumentFile::setupInstrumentConstants (const std::map< unsigned int, std::map< std::string, double > > & profmap) private
Set up chopper/instrument constant parameters from profile map.
Definition at line 517 of file SaveGSASInstrumentFile.cpp.
References calDspRange(), Mantid::API::Algorithm::g_log, getProfileParameterValue(), and Mantid::Kernel::Logger::information().
Referenced by initConstants().
setupNOMConstants()
ChopperConfiguration_sptr Mantid::DataHandling::SaveGSASInstrumentFile::setupNOMConstants (int intfrequency) private
Set up for NOM chopper constants.
Set up the converting constants for NOMAD.
Parameters
intfrequency :: frequency in integer
Definition at line 602 of file SaveGSASInstrumentFile.cpp.
setupPG3Constants()
ChopperConfiguration_sptr Mantid::DataHandling::SaveGSASInstrumentFile::setupPG3Constants (int intfrequency) private
Set up for PG3 chopper constants.
Set up the chopper/instrument constant parameters for PG3.
Definition at line 557 of file SaveGSASInstrumentFile.cpp.
summary()
const std::string Mantid::DataHandling::SaveGSASInstrumentFile::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 30 of file SaveGSASInstrumentFile.h.
version()
int Mantid::DataHandling::SaveGSASInstrumentFile::version () const inline override virtual
Algorithm's version.
Implements Mantid::API::Algorithm.
Definition at line 37 of file SaveGSASInstrumentFile.h.
writePRMHeader()
void Mantid::DataHandling::SaveGSASInstrumentFile::writePRMHeader (const std::vector< unsigned int > & banks, const std::string & prmfilename) private
Write the header of the file.
Definition at line 756 of file SaveGSASInstrumentFile.cpp.
References m_id_line, and m_L1.
Referenced by convertToGSAS().
writePRMSingleBank()
void Mantid::DataHandling::SaveGSASInstrumentFile::writePRMSingleBank (const std::map< unsigned int, std::map< std::string, double > > & bankprofilemap, unsigned int bankid, const std::string & prmfilename) private
Write out .prm/.iparm file.
Parameters
bankid : integer as the ID of the bank to be written to file
bankprofilemap map of all banks' profile parameters stored in map
prmfilename output file name
Definition at line 782 of file SaveGSASInstrumentFile.cpp.
References calL2FromDtt1(), Mantid::Kernel::Logger::debug(), Mantid::EMPTY_DBL(), Mantid::API::Algorithm::g_log, getProfileParameterValue(), m_2theta, m_configuration, m_frequency, m_galpha, m_gbeta, m_gdsp, m_gdt, m_instrument, m_L1, m_L2, and m_sample.
Referenced by convertToGSAS().
Member Data Documentation
m_2theta
double Mantid::DataHandling::SaveGSASInstrumentFile::m_2theta private
2Theta
Definition at line 118 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMSingleBank().
m_bank_mndsp
std::map<unsigned int, double> Mantid::DataHandling::SaveGSASInstrumentFile::m_bank_mndsp private
Definition at line 144 of file SaveGSASInstrumentFile.h.
Referenced by convertToGSAS().
m_bank_mxtof
std::map<unsigned int, double> Mantid::DataHandling::SaveGSASInstrumentFile::m_bank_mxtof private
Definition at line 145 of file SaveGSASInstrumentFile.h.
Referenced by convertToGSAS().
m_configuration
std::shared_ptr<ChopperConfiguration> Mantid::DataHandling::SaveGSASInstrumentFile::m_configuration private
Chopper configuration.
Definition at line 133 of file SaveGSASInstrumentFile.h.
Referenced by buildGSASTabulatedProfile(), convertToGSAS(), initConstants(), and writePRMSingleBank().
m_frequency
int Mantid::DataHandling::SaveGSASInstrumentFile::m_frequency private
Frequency.
Definition at line 120 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMSingleBank().
m_galpha
std::vector<double> Mantid::DataHandling::SaveGSASInstrumentFile::m_galpha private
Definition at line 141 of file SaveGSASInstrumentFile.h.
Referenced by buildGSASTabulatedProfile(), and writePRMSingleBank().
m_gbeta
std::vector<double> Mantid::DataHandling::SaveGSASInstrumentFile::m_gbeta private
Definition at line 142 of file SaveGSASInstrumentFile.h.
Referenced by buildGSASTabulatedProfile(), and writePRMSingleBank().
m_gdsp
std::vector<double> Mantid::DataHandling::SaveGSASInstrumentFile::m_gdsp private
Definition at line 139 of file SaveGSASInstrumentFile.h.
Referenced by buildGSASTabulatedProfile(), and writePRMSingleBank().
m_gdt
std::vector<double> Mantid::DataHandling::SaveGSASInstrumentFile::m_gdt private
Definition at line 140 of file SaveGSASInstrumentFile.h.
Referenced by buildGSASTabulatedProfile(), and writePRMSingleBank().
m_gsasFileName
std::string Mantid::DataHandling::SaveGSASInstrumentFile::m_gsasFileName private
Output file name.
Definition at line 130 of file SaveGSASInstrumentFile.h.
Referenced by exec(), and processProperties().
m_id_line
std::string Mantid::DataHandling::SaveGSASInstrumentFile::m_id_line private
User input ID line.
Definition at line 122 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMHeader().
m_inpWS
API::ITableWorkspace_sptr Mantid::DataHandling::SaveGSASInstrumentFile::m_inpWS private
Input workspace.
Definition at line 108 of file SaveGSASInstrumentFile.h.
Referenced by exec(), loadFullprofResolutionFile(), and processProperties().
m_instrument
std::string Mantid::DataHandling::SaveGSASInstrumentFile::m_instrument private
Instrument.
Definition at line 112 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMSingleBank().
m_L1
double Mantid::DataHandling::SaveGSASInstrumentFile::m_L1 private
L1.
Definition at line 114 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), writePRMHeader(), and writePRMSingleBank().
m_L2
double Mantid::DataHandling::SaveGSASInstrumentFile::m_L2 private
L2.
Definition at line 116 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMSingleBank().
m_profileMap
std::map<unsigned int, std::map<std::string, double> > Mantid::DataHandling::SaveGSASInstrumentFile::m_profileMap private
Profile parameter map.
Definition at line 136 of file SaveGSASInstrumentFile.h.
m_sample
std::string Mantid::DataHandling::SaveGSASInstrumentFile::m_sample private
Sample.
Definition at line 124 of file SaveGSASInstrumentFile.h.
Referenced by processProperties(), and writePRMSingleBank().
m_vecBankID2File
std::vector<unsigned int> Mantid::DataHandling::SaveGSASInstrumentFile::m_vecBankID2File private
Banks IDs to process.
Definition at line 127 of file SaveGSASInstrumentFile.h.
Referenced by exec(), and processProperties().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/SaveGSASInstrumentFile.h
Framework/DataHandling/src/SaveGSASInstrumentFile.cpp