Mantid: Mantid::Geometry::DetectorGroup Class Reference
Mantid::Geometry::DetectorGroup Class Reference
Holds a collection of detectors.
#include <DetectorGroup.h>
Public Member Functions
void addDetector (const IDetector_const_sptr &det)
Add a detector to the collection.
IDetector * cloneParameterized (const ParameterMap *) const override
Create a cloned instance with a parameter map applied.
DetectorGroup ()
Default constructor.
DetectorGroup (const std::vector< IDetector_const_sptr > &dets)
Constructor that takes a list of detectors to add.
void getBoundingBox (BoundingBox &boundingBox) const override
Get the bounding box for this component and store it in the given argument.
std::vector< detid_t > getDetectorIDs () const
What detectors are contained in the group?
std::vector< IDetector_const_sptr > getDetectors () const
What detectors are contained in the group?
double getDistance (const IComponent &comp) const override
Gives the average distance of a group of detectors from the given component.
detid_t getID () const override
Get the detector ID.
double getPhi () const override
Computes the average position and returns the phi value.
double getPhiOffset (const double &offset) const override
Computes the average position and returns the phi value.
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
Kernel::V3D getPos () const override
Returns the position of the DetectorGroup.
std::optional< Kernel::V2D > getSideBySideViewPos () const override
Side by side view override doesn't make sense for a detector group so return empty.
double getSignedTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis, const Kernel::V3D &instrumentUp) const override
Gives the signed angle of this detector object with respect to an axis.
double getTwoTheta (const Kernel::V3D &observer, const Kernel::V3D &axis) const override
Gives the average angle of a group of detectors from the observation point, relative to the axis given.
bool isOnSide (const Kernel::V3D &point) const override
Does the point given lie on the surface of one of the detectors.
bool isParametrized () const override
Return true if any detector in the group is parametrized.
bool isValid (const Kernel::V3D &point) const override
isValid() is true if the point is inside any of the detectors, i.e.
std::size_t nDets () const override
Get the number of physical detectors this object represents.
double solidAngle (const Geometry::SolidAngleParams &params) const override
Gives the total solid angle subtended by a group of detectors by summing the contributions from the individual detectors.
Public Member Functions inherited from Mantid::Geometry::IDetector
IDetector ()
(Empty) Constructor.
Public Member Functions inherited from Mantid::Geometry::IObjComponent
GeometryHandler * Handle () const
Gets the GeometryHandler.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
std::string type () const override
type string
~IObjComponent () override
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual Kernel::V3D getScaleFactor () const
Gets the scaling factor of the object for the Object Component.
virtual ~IComponent ()=default
Destructor.
ParameterMap access
using DetCollection = std::map< int, IDetector_const_sptr >
The type of collection used for the detectors.
int m_id
The ID of this effective detector.
DetCollection m_detectors
The collection of grouped detectors.
det_topology group_topology
the parameter describes the topology of the detector's group namely if detectors form a box or a ring.
Kernel::V3D groupCentre
group centre is the geometrical centre of the detectors group calculated when the calculate group topology is invoked
std::set< std::string > getParameterNames (bool recursive=true) const override
Return the parameter names.
std::map< std::string, ComponentID > getParameterNamesByComponent () const override
return the parameter names and the component they are from
bool hasParameter (const std::string &name, bool recursive=true) const override
Returns a boolean indicating whether the parameter exists or not.
std::string getParameterType (const std::string &name, bool recursive=true) const override
Detectors group assumed to be non-parameterized.
std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a double.
std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::V3D.
std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::Quaternion.
std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a string.
std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an integer.
std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an integer.
std::string getParameterAsString (const std::string &pname, bool recursive=true) const override
Get a string representation of a parameter.
bool getParameterVisible (const std::string &pname, bool recursive=true) const override
Get a visibility attribute of a parameter.
det_topology getTopology (Kernel::V3D &center) const override
returns the detector's group topology if it has been calculated before or invokes the procedure of calculating such topology if it was not
std::string getNameSeparator () const
Return separator for list of names of detectors.
IComponent const * getBaseComponent () const override
Returns const pointer to itself.
const ParameterMap & parameterMap () const override
Helper for legacy access mode. Always throws for DetectorGroup.
size_t index () const override
Helper for legacy access mode. Always throws for DetectorGroup.
virtual size_t registerContents (class ComponentVisitor &visitor) const override
Component * clone () const override
Virtual Copy Constructor.
ComponentID getComponentID () const override
Returns the ComponentID - a unique identifier of the component.
std::shared_ptr< const IComponent > getParent () const override
Return a pointer to the current parent.
const IComponent * getBareParent () const override
Returns the bare pointer to the IComponent parent.
std::vector< std::shared_ptr< const IComponent > > getAncestors () const override
Return an array of all ancestors, the nearest first.
std::string getName () const override
Get the IComponent name.
std::string getFullName () const override
Get the IComponent full path name.
void setParent (IComponent *) override
Assign a parent IComponent. Previous parent link is lost.
void setName (const std::string &) override
Set the IComponent name.
void setPos (double, double, double) override
Set the IComponent position, x, y, z respective to parent (if present)
void setPos (const Kernel::V3D &) override
Set the position of the component The position is with respect to the parent component.
void setSideBySideViewPos (const Kernel::V2D &) override
void setRot (const Kernel::Quat &) override
Set the orientation Kernel::Quaternion relative to parent (if present)
void copyRot (const IComponent &)
int interceptSurface (Track &) const override
Checks whether the track given will pass through this Component.
void translate (const Kernel::V3D &) override
Copy the Rotation from another IComponent.
void translate (double, double, double) override
Translate the IComponent (x,y,z form). This is relative to parent if.
void rotate (const Kernel::Quat &) override
Rotate the IComponent. This is relative to parent.
void rotate (double, const Kernel::V3D &) override
Rotate the IComponent by an angle in degrees with respect to an axis.
Kernel::V3D getRelativePos () const override
Get the position relative to the parent IComponent (absolute if no parent)
Kernel::Quat getRelativeRot () const override
Get the relative Orientation.
Kernel::Quat getRotation () const override
Get the absolute orientation of the IComponent.
void printSelf (std::ostream &) const override
Prints a text representation of itself.
void getBoundingBox (double &, double &, double &, double &, double &, double &) const
void draw () const override
Draws the objcomponent.
void drawObject () const override
Draws the Object.
void initDraw () const override
Initializes the ObjComponent for rendering, this function should be called before rendering.
const std::shared_ptr< const IObject > shape () const override
Returns the shape of the Object.
const Kernel::Material material () const override
Returns the material of the Object.
DetectorGroup (const DetectorGroup &)
Private, unimplemented copy constructor.
DetectorGroup & operator= (const DetectorGroup &)
Private, unimplemented copy assignment operator.
void calculateGroupTopology () const
function calculates the detectors arrangement (topology)
Additional Inherited Members
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Detailed Description
Holds a collection of detectors.
Responds to IDetector methods as though it were a single detector. Currently, detectors in a group are treated as pointlike (or at least) homogenous entities. This means that it's up to the use to make only sensible groupings of similar detectors since no weighting according to solid angle size takes place and the DetectorGroup's position is just a simple average of its constituents.
Author
Russell Taylor, Tessella Support Services plc
Date
08/04/2008
Definition at line 27 of file DetectorGroup.h.
Member Typedef Documentation
DetCollection
using Mantid::Geometry::DetectorGroup::DetCollection = std::map<int, IDetector_const_sptr> protected
The type of collection used for the detectors.
a map of detector pointers with the detector ID as the key
Definition at line 166 of file DetectorGroup.h.
Constructor & Destructor Documentation
DetectorGroup() [1/3]
Mantid::Geometry::DetectorGroup::DetectorGroup ()
Default constructor.
Definition at line 30 of file DetectorGroup.cpp.
DetectorGroup() [2/3]
Mantid::Geometry::DetectorGroup::DetectorGroup (const std::vector< IDetector_const_sptr > & dets)
Constructor that takes a list of detectors to add.
Parameters
dets :: The vector of IDetector pointers that this virtual detector will hold
Exceptions
std::invalid_argument If an empty vector is passed as argument
Definition at line 37 of file DetectorGroup.cpp.
References addDetector(), Mantid::Kernel::Logger::error(), and Mantid::Geometry::g_log.
DetectorGroup() [3/3]
Mantid::Geometry::DetectorGroup::DetectorGroup (const DetectorGroup &) private
Private, unimplemented copy constructor.
Member Function Documentation
addDetector()
void Mantid::Geometry::DetectorGroup::addDetector (const IDetector_const_sptr & det)
Add a detector to the collection.
Parameters
det :: A pointer to the detector to add
Definition at line 52 of file DetectorGroup.cpp.
References group_topology, m_detectors, m_id, and Mantid::Geometry::undef.
Referenced by DetectorGroup().
calculateGroupTopology()
void Mantid::Geometry::DetectorGroup::calculateGroupTopology () const private
function calculates the detectors arrangement (topology)
the private function calculates the topology of the detector's group, namely if the detectors arranged into a ring or into a rectangle.
Uses assumption that a ring has hole inside, so geometrical centre of the shape does not belong to a ring but does belong to a rectangle
Definition at line 371 of file DetectorGroup.cpp.
References Mantid::Geometry::cyl, getPos(), group_topology, groupCentre, isValid(), m_detectors, Mantid::Geometry::rect, Mantid::Geometry::undef, and Mantid::Geometry::BoundingBox::width().
Referenced by getTopology().
clone()
Component * Mantid::Geometry::DetectorGroup::clone () const inline override protected virtual
Virtual Copy Constructor.
Returns
A pointer to a copy of the input ObjComponent
Implements Mantid::Geometry::IObjComponent.
Definition at line 179 of file DetectorGroup.h.
cloneParameterized()
IDetector * Mantid::Geometry::DetectorGroup::cloneParameterized (const ParameterMap * map) const inline override virtual
Create a cloned instance with a parameter map applied.
Implements Mantid::Geometry::IDetector.
Definition at line 35 of file DetectorGroup.h.
copyRot()
void Mantid::Geometry::DetectorGroup::copyRot (const IComponent &) inline protected
Definition at line 195 of file DetectorGroup.h.
draw()
void Mantid::Geometry::DetectorGroup::draw () const inline override protected virtual
Draws the objcomponent.
Implements Mantid::Geometry::IObjComponent.
Definition at line 214 of file DetectorGroup.h.
drawObject()
void Mantid::Geometry::DetectorGroup::drawObject () const inline override protected virtual
Draws the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 215 of file DetectorGroup.h.
getAncestors()
std::vector< std::shared_ptr< const IComponent > > Mantid::Geometry::DetectorGroup::getAncestors () const inline override protected virtual
Return an array of all ancestors, the nearest first.
Implements Mantid::Geometry::IComponent.
Definition at line 183 of file DetectorGroup.h.
getBareParent()
const IComponent * Mantid::Geometry::DetectorGroup::getBareParent () const inline override protected virtual
Returns the bare pointer to the IComponent parent.
Implements Mantid::Geometry::IComponent.
Definition at line 182 of file DetectorGroup.h.
getBaseComponent()
IComponent const * Mantid::Geometry::DetectorGroup::getBaseComponent () const inline override virtual
Returns const pointer to itself.
This currently (2914/04/24) contradicts the logic behind getComponentID overload, so CopyInstrumentParameters will fail on grouped instrument but it is something TO DO:
Implements Mantid::Geometry::IComponent.
Definition at line 154 of file DetectorGroup.h.
getBoolParameter()
std::vector< bool > Mantid::Geometry::DetectorGroup::getBoolParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as an integer.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 353 of file DetectorGroup.cpp.
getBoundingBox() [1/2]
void Mantid::Geometry::DetectorGroup::getBoundingBox (BoundingBox & boundingBox) const override virtual
Get the bounding box for this component and store it in the given argument.
Get the bounding box for this group of detectors.
It is simply the sum of the bounding boxes of its constituents.
Parameters
boundingBox :: [Out] The resulting bounding box is stored here.
Implements Mantid::Geometry::IComponent.
Definition at line 295 of file DetectorGroup.cpp.
References Mantid::Geometry::BoundingBox::getCoordSystem(), Mantid::Geometry::BoundingBox::grow(), Mantid::Geometry::BoundingBox::isAxisAligned(), m_detectors, and Mantid::Geometry::BoundingBox::realign().
getBoundingBox() [2/2]
void Mantid::Geometry::DetectorGroup::getBoundingBox (double & , double & , double & , double & , double & , double &) const inline protected
Definition at line 212 of file DetectorGroup.h.
getComponentID()
ComponentID Mantid::Geometry::DetectorGroup::getComponentID () const inline override protected virtual
Returns the ComponentID - a unique identifier of the component.
Implements Mantid::Geometry::IComponent.
Definition at line 180 of file DetectorGroup.h.
getDetectorIDs()
std::vector< detid_t > Mantid::Geometry::DetectorGroup::getDetectorIDs () const
What detectors are contained in the group?
Return IDs for the detectors grouped.
Returns
vector of detector IDs
Definition at line 161 of file DetectorGroup.cpp.
References m_detectors.
Referenced by Mantid::DataHandling::GenerateGroupingPowder::createGroups(), export_DetectorGroup(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesNonPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesTable(), and Mantid::DataHandling::GenerateGroupingPowder::saveAsPAR().
getDetectors()
std::vector< IDetector_const_sptr > Mantid::Geometry::DetectorGroup::getDetectors () const
What detectors are contained in the group?
Return the list of detectors held within this group.
Returns
A vector of IDetector pointers
Definition at line 175 of file DetectorGroup.cpp.
References m_detectors.
Referenced by Mantid::Algorithms::CreatePSDBleedMask::exec().
getDistance()
double Mantid::Geometry::DetectorGroup::getDistance (const IComponent & comp) const override virtual
Gives the average distance of a group of detectors from the given component.
Implements Mantid::Geometry::IDetector.
Definition at line 96 of file DetectorGroup.cpp.
References m_detectors.
getFullName()
std::string Mantid::Geometry::DetectorGroup::getFullName () const override protected virtual
Get the IComponent full path name.
Implements Mantid::Geometry::IComponent.
Definition at line 421 of file DetectorGroup.cpp.
References getNameSeparator(), and m_detectors.
getID()
detid_t Mantid::Geometry::DetectorGroup::getID () const override virtual
Get the detector ID.
Implements Mantid::Geometry::IDetector.
Definition at line 64 of file DetectorGroup.cpp.
References m_id.
getIntParameter()
std::vector< int > Mantid::Geometry::DetectorGroup::getIntParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as an integer.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 348 of file DetectorGroup.cpp.
getName()
std::string Mantid::Geometry::DetectorGroup::getName () const override protected virtual
Get the IComponent name.
Implements Mantid::Geometry::IComponent.
Definition at line 412 of file DetectorGroup.cpp.
References getNameSeparator(), and m_detectors.
getNameSeparator()
std::string Mantid::Geometry::DetectorGroup::getNameSeparator () const inline
Return separator for list of names of detectors.
Definition at line 149 of file DetectorGroup.h.
Referenced by export_DetectorGroup(), getFullName(), and getName().
getNumberParameter()
std::vector< double > Mantid::Geometry::DetectorGroup::getNumberParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as a double.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 328 of file DetectorGroup.cpp.
getParameterAsString()
std::string Mantid::Geometry::DetectorGroup::getParameterAsString (const std::string & pname, bool recursive = true) const override virtual
Get a string representation of a parameter.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A empty string as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 271 of file DetectorGroup.cpp.
getParameterNames()
std::set< std::string > Mantid::Geometry::DetectorGroup::getParameterNames (bool recursive = true) const override virtual
Return the parameter names.
Get the names of the parameters for this component.
Parameters
recursive :: If true, the parameters for all of the parent components are also included
Returns
A set of strings giving the parameter names for this component
Implements Mantid::Geometry::IComponent.
Definition at line 249 of file DetectorGroup.cpp.
getParameterNamesByComponent()
std::map< std::string, ComponentID > Mantid::Geometry::DetectorGroup::getParameterNamesByComponent () const override virtual
return the parameter names and the component they are from
Get the names of the parameters for this component and it's parents.
Returns
A map of strings giving the parameter names and the component they are from, warning this contains shared pointers keeping transient objects alive, do not keep longer than needed
Implements Mantid::Geometry::IComponent.
Definition at line 260 of file DetectorGroup.cpp.
getParameterType()
std::string Mantid::Geometry::DetectorGroup::getParameterType (const std::string & name, bool recursive = true) const override virtual
Detectors group assumed to be non-parameterized.
Implements Mantid::Geometry::IComponent.
Definition at line 323 of file DetectorGroup.cpp.
getParameterVisible()
bool Mantid::Geometry::DetectorGroup::getParameterVisible (const std::string & pname, bool recursive = true) const override virtual
Get a visibility attribute of a parameter.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A boolean containing the visibility attribute of the parameter, false if does not exist
Implements Mantid::Geometry::IComponent.
Definition at line 284 of file DetectorGroup.cpp.
getParent()
std::shared_ptr< const IComponent > Mantid::Geometry::DetectorGroup::getParent () const inline override protected virtual
Return a pointer to the current parent.
Implements Mantid::Geometry::IComponent.
Definition at line 181 of file DetectorGroup.h.
getPhi()
double Mantid::Geometry::DetectorGroup::getPhi () const override virtual
Computes the average position and returns the phi value.
Implements Mantid::Geometry::IDetector.
Definition at line 144 of file DetectorGroup.cpp.
References getPos(), and Mantid::Kernel::V3D::getSpherical().
Referenced by getPhiOffset().
getPhiOffset()
double Mantid::Geometry::DetectorGroup::getPhiOffset (const double & offset) const override virtual
Computes the average position and returns the phi value.
Implements Mantid::Geometry::IDetector.
Definition at line 152 of file DetectorGroup.cpp.
References getPhi().
getPointInObject()
int Mantid::Geometry::DetectorGroup::getPointInObject (Kernel::V3D & point) const override virtual
Try to find a point that lies within (or on) the object.
tries to find a point that lies on or within the first detector in the storage found in the storage map
Parameters
point :: if a point is found its coordinates will be stored in this varible
Returns
1 if point found, 0 otherwise
Implements Mantid::Geometry::IObjComponent.
Definition at line 235 of file DetectorGroup.cpp.
References m_detectors.
getPos()
V3D Mantid::Geometry::DetectorGroup::getPos () const override virtual
Returns the position of the DetectorGroup.
In the absence of a full surface/solid angle implementation, this is a simple average of the component detectors (i.e. there's no weighting for size or if one or more of the detectors is masked). Also, no regard is made to whether a constituent detector is itself a DetectorGroup - it's just treated as a single, pointlike object with the same weight as any other detector.
Returns
a V3D object of the detector group position
Implements Mantid::Geometry::IComponent.
Definition at line 76 of file DetectorGroup.cpp.
References m_detectors, and Mantid::Kernel::Tolerance.
Referenced by calculateGroupTopology(), and getPhi().
getPositionParameter()
std::vector< V3D > Mantid::Geometry::DetectorGroup::getPositionParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as a Kernel::V3D.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 333 of file DetectorGroup.cpp.
getRelativePos()
Kernel::V3D Mantid::Geometry::DetectorGroup::getRelativePos () const inline override protected virtual
Get the position relative to the parent IComponent (absolute if no parent)
Implements Mantid::Geometry::IComponent.
Definition at line 201 of file DetectorGroup.h.
getRelativeRot()
Kernel::Quat Mantid::Geometry::DetectorGroup::getRelativeRot () const inline override protected virtual
Get the relative Orientation.
Implements Mantid::Geometry::IComponent.
Definition at line 204 of file DetectorGroup.h.
getRotation()
Kernel::Quat Mantid::Geometry::DetectorGroup::getRotation () const inline override protected virtual
Get the absolute orientation of the IComponent.
Implements Mantid::Geometry::IComponent.
Definition at line 207 of file DetectorGroup.h.
getRotationParameter()
std::vector< Quat > Mantid::Geometry::DetectorGroup::getRotationParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as a Kernel::Quaternion.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 338 of file DetectorGroup.cpp.
getSideBySideViewPos()
std::optional< Kernel::V2D > Mantid::Geometry::DetectorGroup::getSideBySideViewPos () const override virtual
Side by side view override doesn't make sense for a detector group so return empty.
Implements Mantid::Geometry::IComponent.
Definition at line 93 of file DetectorGroup.cpp.
getSignedTwoTheta()
double Mantid::Geometry::DetectorGroup::getSignedTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis, const Kernel::V3D & instrumentUp) const override virtual
Gives the signed angle of this detector object with respect to an axis.
Parameters
observer :: The point to calculate the angle relative to (typically the sample position)
axis :: The axis to which the required angle is relative
instrumentUp :: Direction corresponding to the instrument up direction. Used to determine signs.
Returns
The angle in radians
Implements Mantid::Geometry::IDetector.
Definition at line 125 of file DetectorGroup.cpp.
References Mantid::Kernel::V3D::angle(), Mantid::Kernel::V3D::cross_prod(), m_detectors, and Mantid::Kernel::V3D::scalar_prod().
getStringParameter()
std::vector< std::string > Mantid::Geometry::DetectorGroup::getStringParameter (const std::string & pname, bool recursive = true) const override virtual
Get a parameter defined as a string.
Default implementation.
Parameters
pname :: The name of the parameter
recursive :: If true the search will walk up through the parent components
Returns
A list of size 0 as this is not a parameterized component
Implements Mantid::Geometry::IComponent.
Definition at line 343 of file DetectorGroup.cpp.
getTopology()
det_topology Mantid::Geometry::DetectorGroup::getTopology (Kernel::V3D & center) const override virtual
returns the detector's group topology if it has been calculated before or invokes the procedure of calculating such topology if it was not
Implements Mantid::Geometry::IDetector.
Definition at line 358 of file DetectorGroup.cpp.
References calculateGroupTopology(), group_topology, groupCentre, and Mantid::Geometry::undef.
getTwoTheta()
double Mantid::Geometry::DetectorGroup::getTwoTheta (const Kernel::V3D & observer, const Kernel::V3D & axis) const override virtual
Gives the average angle of a group of detectors from the observation point, relative to the axis given.
Implements Mantid::Geometry::IDetector.
Definition at line 105 of file DetectorGroup.cpp.
References Mantid::Kernel::V3D::angle(), and m_detectors.
hasParameter()
bool Mantid::Geometry::DetectorGroup::hasParameter (const std::string & name, bool recursive = true) const override virtual
Returns a boolean indicating whether the parameter exists or not.
Returns a boolean indicating if the component has the named parameter.
Parameters
name :: The name of the parameter
recursive :: If true the parent components will also be searched (Default: true)
Returns
A boolean indicating if the search was successful or not. Always false as this is not parameterized
Implements Mantid::Geometry::IComponent.
Definition at line 317 of file DetectorGroup.cpp.
References name.
index()
size_t Mantid::Geometry::DetectorGroup::index () const override virtual
Helper for legacy access mode. Always throws for DetectorGroup.
Implements Mantid::Geometry::IDetector.
Definition at line 438 of file DetectorGroup.cpp.
initDraw()
void Mantid::Geometry::DetectorGroup::initDraw () const inline override protected virtual
Initializes the ObjComponent for rendering, this function should be called before rendering.
Implements Mantid::Geometry::IObjComponent.
Definition at line 216 of file DetectorGroup.h.
interceptSurface()
int Mantid::Geometry::DetectorGroup::interceptSurface (Track & track) const inline override protected virtual
Checks whether the track given will pass through this Component.
Implements Mantid::Geometry::IObjComponent.
Definition at line 196 of file DetectorGroup.h.
isOnSide()
bool Mantid::Geometry::DetectorGroup::isOnSide (const Kernel::V3D & point) const override virtual
Does the point given lie on the surface of one of the detectors.
Parameters
point :: the point that is tested to see if it is one of the detectors
Returns
true if the point is on the side of a detector else it returns false
Implements Mantid::Geometry::IObjComponent.
Definition at line 223 of file DetectorGroup.cpp.
References m_detectors.
isParametrized()
bool Mantid::Geometry::DetectorGroup::isParametrized () const override virtual
Return true if any detector in the group is parametrized.
Implements Mantid::Geometry::IComponent.
Definition at line 202 of file DetectorGroup.cpp.
References m_detectors.
isValid()
bool Mantid::Geometry::DetectorGroup::isValid (const Kernel::V3D & point) const override virtual
isValid() is true if the point is inside any of the detectors, i.e.
one of the detectors has isValid() == true
Parameters
point :: this point is tested to see if it is one of the detectors
Returns
if the point is in a detector it returns true else it returns false
Implements Mantid::Geometry::IObjComponent.
Definition at line 213 of file DetectorGroup.cpp.
References m_detectors.
Referenced by calculateGroupTopology().
material()
const Kernel::Material Mantid::Geometry::DetectorGroup::material () const override protected virtual
Returns the material of the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 430 of file DetectorGroup.cpp.
nDets()
std::size_t Mantid::Geometry::DetectorGroup::nDets () const override virtual
Get the number of physical detectors this object represents.
Implements Mantid::Geometry::IDetector.
Definition at line 66 of file DetectorGroup.cpp.
References m_detectors.
operator=()
DetectorGroup & Mantid::Geometry::DetectorGroup::operator= (const DetectorGroup &) private
Private, unimplemented copy assignment operator.
parameterMap()
const ParameterMap & Mantid::Geometry::DetectorGroup::parameterMap () const override virtual
Helper for legacy access mode. Always throws for DetectorGroup.
Implements Mantid::Geometry::IDetector.
Definition at line 433 of file DetectorGroup.cpp.
printSelf()
void Mantid::Geometry::DetectorGroup::printSelf (std::ostream &) const inline override protected virtual
Prints a text representation of itself.
Implements Mantid::Geometry::IComponent.
Definition at line 208 of file DetectorGroup.h.
registerContents()
size_t Mantid::Geometry::DetectorGroup::registerContents (class ComponentVisitor & visitor) const override virtual
Implements Mantid::Geometry::IComponent.
Definition at line 440 of file DetectorGroup.cpp.
rotate() [1/2]
void Mantid::Geometry::DetectorGroup::rotate (const Kernel::Quat &) inline override protected virtual
Rotate the IComponent. This is relative to parent.
Implements Mantid::Geometry::IComponent.
Definition at line 199 of file DetectorGroup.h.
rotate() [2/2]
void Mantid::Geometry::DetectorGroup::rotate (double , const Kernel::V3D &) inline override protected virtual
Rotate the IComponent by an angle in degrees with respect to an axis.
Implements Mantid::Geometry::IComponent.
Definition at line 200 of file DetectorGroup.h.
setName()
void Mantid::Geometry::DetectorGroup::setName (const std::string &) inline override protected virtual
Set the IComponent name.
Implements Mantid::Geometry::IComponent.
Definition at line 189 of file DetectorGroup.h.
setParent()
void Mantid::Geometry::DetectorGroup::setParent (IComponent *) inline override protected virtual
Assign a parent IComponent. Previous parent link is lost.
Implements Mantid::Geometry::IComponent.
Definition at line 188 of file DetectorGroup.h.
setPos() [1/2]
void Mantid::Geometry::DetectorGroup::setPos (const Kernel::V3D &) inline override protected virtual
Set the position of the component The position is with respect to the parent component.
Implements Mantid::Geometry::IComponent.
Definition at line 192 of file DetectorGroup.h.
setPos() [2/2]
void Mantid::Geometry::DetectorGroup::setPos (double , double , double) inline override protected virtual
Set the IComponent position, x, y, z respective to parent (if present)
Implements Mantid::Geometry::IComponent.
Definition at line 191 of file DetectorGroup.h.
setRot()
void Mantid::Geometry::DetectorGroup::setRot (const Kernel::Quat &) inline override protected virtual
Set the orientation Kernel::Quaternion relative to parent (if present)
Implements Mantid::Geometry::IComponent.
Definition at line 194 of file DetectorGroup.h.
setSideBySideViewPos()
void Mantid::Geometry::DetectorGroup::setSideBySideViewPos (const Kernel::V2D &) inline override protected virtual
Implements Mantid::Geometry::IComponent.
Definition at line 193 of file DetectorGroup.h.
shape()
const std::shared_ptr< const IObject > Mantid::Geometry::DetectorGroup::shape () const inline override protected virtual
Returns the shape of the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 219 of file DetectorGroup.h.
solidAngle()
double Mantid::Geometry::DetectorGroup::solidAngle (const Geometry::SolidAngleParams & params) const override virtual
Gives the total solid angle subtended by a group of detectors by summing the contributions from the individual detectors.
Parameters
params :: The point from which the detector is being viewed, and number of cylinder slices
Returns
The solid angle in steradians
Exceptions
NullPointerException If geometrical form of any detector has not been provided in the instrument definition file
Implements Mantid::Geometry::IObjComponent.
Definition at line 192 of file DetectorGroup.cpp.
References m_detectors.
translate() [1/2]
void Mantid::Geometry::DetectorGroup::translate (const Kernel::V3D &) inline override protected virtual
Copy the Rotation from another IComponent.
Translate the IComponent (vector form). This is relative to parent if
Implements Mantid::Geometry::IComponent.
Definition at line 197 of file DetectorGroup.h.
translate() [2/2]
void Mantid::Geometry::DetectorGroup::translate (double , double , double) inline override protected virtual
Translate the IComponent (x,y,z form). This is relative to parent if.
Implements Mantid::Geometry::IComponent.
Definition at line 198 of file DetectorGroup.h.
Member Data Documentation
group_topology
det_topology Mantid::Geometry::DetectorGroup::group_topology mutable protected
the parameter describes the topology of the detector's group namely if detectors form a box or a ring.
the topology is undefined on construction and calculated on first request
Definition at line 173 of file DetectorGroup.h.
Referenced by addDetector(), calculateGroupTopology(), and getTopology().
groupCentre
Kernel::V3D Mantid::Geometry::DetectorGroup::groupCentre mutable protected
group centre is the geometrical centre of the detectors group calculated when the calculate group topology is invoked
Definition at line 176 of file DetectorGroup.h.
Referenced by calculateGroupTopology(), and getTopology().
m_detectors
DetCollection Mantid::Geometry::DetectorGroup::m_detectors protected
The collection of grouped detectors.
Definition at line 168 of file DetectorGroup.h.
Referenced by addDetector(), calculateGroupTopology(), getBoundingBox(), getDetectorIDs(), getDetectors(), getDistance(), getFullName(), getName(), getPointInObject(), getPos(), getSignedTwoTheta(), getTwoTheta(), isOnSide(), isParametrized(), isValid(), nDets(), and solidAngle().
m_id
int Mantid::Geometry::DetectorGroup::m_id protected
The ID of this effective detector.
Definition at line 162 of file DetectorGroup.h.
Referenced by addDetector(), and getID().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/DetectorGroup.h
Framework/Geometry/src/Instrument/DetectorGroup.cpp