Mantid: Mantid::Algorithms Namespace Reference
Mantid::Algorithms Namespace Reference
Namespaces
namespace ApodizationFunctions
namespace Arithmetic
namespace ColNames
namespace ColumnNames
A private namespace holding the column names of the EPP table.
namespace CorelliCalibration
namespace DirectionChoices
A private namespace for the options for the Direction property.
namespace EPPTableLiterals
A private namespace holding some column names for FindEPP algorithm's output table.
namespace FFTSmooth
namespace FitPeaksAlgorithm
namespace Fitting
namespace FlipperConfigurations
namespace IndexTypes
A private namespace listing the different ways to index spectra in Mantid.
namespace MergeRunsParameter
Combines the data contained in an arbitrary number of input workspaces.
namespace ModeChoices
A private namespace for the mode options.
namespace Operation
namespace PeakParameterHelper
namespace PolarizationCorrectionsHelpers
namespace PropertyNames
A private namespace for property names.
namespace RealFFT
namespace RunCombinationOptions
RunCombinationHelper : This holds some useful utilities for operations involving transformations of lists of workspaces into single one.
namespace SampleLog
A private namespace listing some sample log entries.
namespace SampleLogs
A private namespace holding names for sample log entries.
namespace SolidAngleHelpers
namespace SolidAngleMethods
namespace SparseInstrument
namespace SpinStateConfigurationsFredrikze
namespace SpinStateConfigurationsWildes
namespace SpinStatesORSO
Classes
class AbsorptionCorrection
A base class for absorption correction algorithms.
class AddAbsorptionWeightedPathLengths
Calculates the absorption weighted path length for each peak in a peaks workspace and saves it to the tbar column in the workspace.
class AddLogDerivative
Takes an existing sample log, and calculates its first or second derivative, and adds it as a new log.
class AddLogInterpolated
Takes an existing sample log and interpolates it according to the time axis of another log.
class AddLogSmoothed
Takes an existing sample log and smooths it using a selected method.
class AddPeak
Add a peak to a PeaksWorkspace.
class AddSampleLog
Used to insert a single string into the sample in a workspace.
class AddTimeSeriesLog
class AnnularRingAbsorption
Constructs a hollow sample shape, defines material for the sample and runs the MonteCarloAbsorption algorithm.
class AnyShapeAbsorption
Calculates an approximation of the attenuation due to absorption and scattering in a generic sample shape.
class AppendSpectra
Joins two partial, non-overlapping workspaces into one.
class ApplyCalibration
Update detector positions from input table workspace.
class ApplyDetailedBalance
ApplyDetailedBalance : The algorithm calculates the imaginary part of the dynamic susceptibility chi''=Pi*(1-exp(-E/T))*S.
class ApplyFloodWorkspace
Algorithm to apply a flood correction workspace to a reflectometry data workspace.
class ApplyInstrumentToPeaks
ApplyInstrumentToPeaks : TODO: DESCRIPTION.
class ApplyTransmissionCorrection
Apply angle-dependent transmission correction from zero-angle transmission measurement.
class AverageLogData
AverageLogData : TODO: DESCRIPTION.
class BackgroundHelper
Performs removal of constant (and possibly non-constant after simple modification) background calculated in TOF units from a matrix workspace, expressed in units, different from TOF.
class BeamProfileFactory
class Bin2DPowderDiffraction
Bin2DPowderDiffraction :
class BinaryOperateMasks
BinaryOperateMasks : TODO: DESCRIPTION.
class BinaryOperation
BinaryOperation supports the implementation of a binary operation on two input workspaces.
class CalculateCarpenterSampleCorrection
Multiple scattering absorption correction, originally used to correct vanadium spectrum at IPNS.
class CalculateCountRate
In normal circumstances an instrument in event mode counts neutrons with constant steady rate which depends on beam intensity, instrument settings and sample.
class CalculateDIFC
CalculateDIFC : Calculate the DIFC for every pixel.
class CalculateDynamicRange
CalculateDynamicRange Calculates the Qmin and Qmax of SANS workspace, sets to sample logs.
class CalculateEfficiency
Compute relative detector pixel efficiency from flood data as part of SANS reduction.
class CalculateEfficiency2
Compute relative detector pixel efficiency from flood data as part of SANS reduction.
class CalculateFlatBackground
Finds a constant background value of each desired spectrum and optionally subtracts that value from the entire spectrum.
class CalculateIqt
class CalculatePlaczek
CalculatePlaczek : Placzek 1st&2nd order correction for inelastic scattering.
class CalculatePlaczekSelfScattering
CalculatePlaczekSelfScattering : This algorithm calculates a correction for an incident spectrum defracted by a sample.
class CalculatePlaczekSelfScattering2
CalculatePlaczekSelfScattering2 : TODO: DESCRIPTION.
class CalculatePolynomialBackground
CalculatePolynomialBackground : This algorithm fits a polynomial background to an input workspace and returns the evaluated background as the output workspace.
class CalculateTransmission
Calculates the transmission correction, as a function of wavelength, for a SANS instrument.
class CalculateTransmissionBeamSpreader
Calculates the transmission correction, as a function of wavelength, for a SANS instrument.
class CalculateZscore
CalculateZscore : Calculate Zscore for a Matrix Workspace.
class CarpenterSampleCorrection
Multiple scattering absorption correction, originally used to correct vanadium spectrum at IPNS.
class ChangeBinOffset
Takes a workspace and adjusts all the time bin values by the same amount.
class ChangeLogTime
class ChangePulsetime
ChangePulsetime : TODO: DESCRIPTION.
class ChangePulsetime2
ChangePulsetime : TODO: DESCRIPTION.
class ChangeTimeZero
class ChopData
For use in TOSCA reduction.
class CircularBeamProfile
Defines a flat, circular beam profile that has a radius and center point.
class ClearCache
ClearCache : TODO: DESCRIPTION.
class ClearInstrumentParameters
ClearInstrumentParameters : Clear out an instrument's parameters.
class ClearMaskFlag
ClearMaskFlag : Delete the mask flag/bit on all spectra in a workspace.
class CloneWorkspace
Creates a copy of the input workspace.
struct CollimatorInfo
Object for holding collimator parameteres loaded from instrument parameters file.
class CombineDiffCal
CombineDiffCal : Calibrate groups of pixels after cross correlation so that diffraction peaks can be adjusted to the correct positions.
class CombineTableWorkspaces
CombineTableWorkspaces : Take a pair of table workspaces and combine them into a single table by appending the rows of the second onto the first.
class Comment
Comment : Adds a note into the history record of a workspace.
class CommutativeBinaryOperation
CommutativeBinaryOperation supports commutative binary operations on two input workspaces.
class CompareWorkspaces
Compares two workspaces for equality.
struct ComponentScatterPoint
struct ComponentWorkspaceMapping
class ConjoinWorkspaces
Joins two partial, non-overlapping workspaces into one.
class ConjoinXRuns
ConjoinXRuns : This algorithms joins the input workspaces horizontally, i.e.
class ConvertAxesToRealSpace
ConvertAxesToRealSpace : Converts the spectrum and TOF axes to real space values, integrating the data in the process.
class ConvertAxisByFormula
ConvertAxisByFormula : Performs a unit conversion based on a supplied formula.
class ConvertDiffCal
ConvertDiffCal : TODO: DESCRIPTION.
class ConvertFromDistribution
Converts a histogram workspace from a distribution.
class ConvertSpectrumAxis
Converts the representation of the vertical axis (the one up the side of a matrix) of a Workspace2D from its default of holding the spectrum number to the target unit given.
class ConvertSpectrumAxis2
Converts the representation of the vertical axis (the one up the side of a matrix) of a Workspace2D from its default of holding the spectrum number to the target unit given - theta, elastic Q and elastic Q^2.
class ConvertTableToMatrixWorkspace
Creates a single spectrum matrix workspace from some columns of a table workspace.
class ConvertToConstantL2
Convert workspace to have a constant L2.
class ConvertToDistribution
Makes a histogram workspace a distribution.
class ConvertToEventWorkspace
Perform a conversion for a Workspace2D to an equivalent EventWorkspace.
class ConvertToHistogram
Converts a histogram workspace to point data by simply taking the centre point of the bin as the new point on the X axis.
class ConvertToMatrixWorkspace
Creates a copy of the matrix workspace representation of the input workspace.
class ConvertToPointData
Converts a histogram workspace to point data by simply taking the centre point of the bin as the new point on the X axis.
class ConvertToRelativeTime
Helper method to transform a MantidVector containing absolute times in nanoseconds to relative times in seconds given an offset.
class ConvertUnits
Converts the units in which a workspace is represented.
class CopyDataRange
CopyDataRange : This algorithm takes a continuous block of data from an input workspace specified by spectra indices and x indices and replaces a block of data within a destination workspace.
class CopyDetectorMapping
Algorithm to copy spectra-detector mapping from one matrix workspace to another.
class CopyInstrumentParameters
Transfers an instrument from one workspace to another workspace with the same base instrument.
class CopyLogs
CopyLogs.
class CopySample
CopySample : The algorithm copies some/all the sample information from one workspace to another.
class CorelliCalibrationApply
Apply calibration table for Corelli Powder Diffraction.
class CorelliCalibrationDatabase
CorelliCalibrationDatabase: blablabla TODO.
class CorelliCrossCorrelate
CorelliCrossCorrelate : TODO: DESCRIPTION.
class CorrectKiKf
Multiplies the workspace with k_i/k_f The initial workspace must have energy transfer units.
class CorrectTOFAxis
CorrectTOFAxis : Corrects the time-of-flight axis with regards to the incident energy and the L1+L2 distance or a reference workspace.
class CorrectToFile
Required properties:
class CreateBootstrapWorkspaces
CreateBootstrapWorkspaces: The algorithm generates several simulated workspaces by sampling randomly from the input data, useful for doing a Bootstrap Analysis.
class CreateCalFileByNames
Create a calibration file for diffraction focussing (*.cal old Ariel format) based on list of names of the instrument tree.
class CreateDetectorTable
class CreateDummyCalFile
Create a calibration file for diffraction focussing (*.cal old Ariel format) based on list of names of the instrument tree.
class CreateEPP
CreateEPP : Calculates the nominal elastic time-of flights for each spectrum and creates an elastic peak position table (EPP) like the one returned by the FindEPP algorithm.
class CreateFlatEventWorkspace
CreateFlatEventWorkspace : Creates a flat event workspace that can be used for background removal.
class CreateFloodWorkspace
Algorithm to create a flood correction workspace for reflectometry data reduction.
class CreateGroupingWorkspace
Creates a new GroupingWorkspace using an instrument from one of: an input workspace, an instrument name, or an instrument IDF file.
class CreateLogPropertyTable
class CreateLogTimeCorrection
CreateLogTimeCorrection : Create correction file and workspace to correct event time against recorded log time for each pixel.
class CreateMonteCarloWorkspace
CreateMonteCarloWorkspace : The algorithm generates a simulated workspace by sampling from the probability distribution of input data, useful for testing of fitting functions and modeling.
class CreatePeaksWorkspace
Create an empty PeaksWorkspace.
class CreatePSDBleedMask
This algorithm implements a "bleed" diagnostic for PSD detectors (i.e.
class CreateSampleWorkspace
CreateSampleWorkspace : This algorithm is intended for the creation of sample workspaces for usage examples and other situations.
class CreateSingleValuedWorkspace
Required properties:
class CreateUserDefinedBackground
CreateUserDefinedBackground : Given an input workspace containing data with a background and a table of user-selected points defining the background, creates a new workspace containing background data that can be subtracted from the original data.
class CreateWorkspace
CreateWorkspace Algorithm.
class CropToComponent
CropToComponent : Crops a workspace to a set of components.
class CropWorkspace
Extracts a 'block' from a workspace and places it in a new workspace.
class CropWorkspaceRagged
Extracts a 'block' from a workspace and places it in a new workspace.
class CrossCorrelate
Compute the cross correlation function for a range of spectra with respect to a reference spectrum.
class CuboidGaugeVolumeAbsorption
Calculates attenuation due to absorption and scattering in a generic sample, considering only the scattering within a cuboid shaped 'gauge volume'.
class CylinderAbsorption
Calculates attenuation due to absorption and scattering in a cylindrical sample.
class DeadTimeCorrection
DeadTimeCorrection : Performs dead time correction.
class DeleteLog
class DeleteWorkspace
A simple algorithm to remove a workspace from the ADS.
class DeleteWorkspaces
A simple algorithm to remove multiple workspaces from the ADS.
class DepolarizedAnalyserTransmission
class DetectorDiagnostic
A base class for a detector diagnostic algorithm.
class DetectorEfficiencyCor
Returns efficiency of cylindrical helium gas tube.
class DetectorEfficiencyCorUser
DetectorEfficiencyCorUser :
class DetectorEfficiencyVariation
Required Properties:
class DetectorGridDefinition
DetectorGridDefinition is a helper class for building the sparse instrument in MonteCarloAbsorption.
class DetermineSpinStateOrder
DetermineSpinStateOrder : Takes a workspace group of Polarised SANS run periods and returns a string (e.g '11, 10, 01, 00') of their corresponding flipper/analyser states.
class DiffractionEventCalibrateDetectors
Find the offsets for each detector.
class DiffractionFocussing
This is a parent algorithm that uses several different child algorithms to perform it's task.
class DiffractionFocussing2
Algorithm to focus powder diffraction data into a number of histograms according to a grouping scheme defined in a file.
class DirectILLTubeBackground
DirectILLTubeBackground : Fits polynomial backgrounds over the pixels of position sensitive tubes.
struct DiscusData1D
class DiscusData2D
class DiscusMultipleScatteringCorrection
Calculates a multiple scattering correction Based on Muscat Fortran code provided by Spencer Howells.
class Divide
Divide performs the division of two input workspaces.
class EditInstrumentGeometry
EditInstrumentGeometry : TODO: DESCRIPTION.
class ElasticWindow
class EQSANSCorrectFrame
Apply correction to EQSANS data to account for its TOF structure.
class EQSANSResolution
Computes the resolution on EQSANS data Required Properties:
class EQSANSTofStructure
class EstimateDivergence
EstimateDivergence : Calculate the instrument divergence according to Windsor.
class EstimateResolutionDiffraction
EstimateResolutionDiffraction : TODO: DESCRIPTION.
class EstimateScatteringVolumeCentreOfMass
struct EventWorkspaceAccess
class Exponential
Exponential performs the exponential function on an input workspace.
class ExponentialCorrection
Corrects the data and error values on a workspace by the value of an exponential function which is evaluated at the X value of each data point: c0*exp(-c1*x).
class ExportTimeSeriesLog
ExportTimeSeriesLog : Read a TimeSeries log and return some information required by users.
class ExtractFFTSpectrum
This algorithm performs a Fast Fourier Transform on each spectra of the input workspace.
class ExtractMask
Extract the masking from a given workspace.
class ExtractMaskToTable
ExtractMaskToTable : Extract the mask in a workspace to a table workspace.
class ExtractQENSMembers
ExtractQENSMembers : Extracts the fit members from a QENS fit.
class ExtractSingleSpectrum
Copies a single spectrum from a 2D Workspace into a new workspace.
class ExtractSpectra
Extracts specified spectra from a workspace and places them in a new workspace.
class ExtractSpectra2
Extracts specified spectra from a workspace and places them in a new workspace.
class ExtractUnmaskedSpectra
ExtractUnmaskedSpectra : TODO: DESCRIPTION.
class FFT
Performs a Fast Fourier Transform of data.
class FFTDerivative
Calculates derivatives of the spectra in a MatrixWorkspace using a Fast Fourier Transform.
class FFTSmooth
Data smoothing using the FFT algorithm and various filters.
class FilterBadPulses
Filters out events associated with pulses that happen when proton charge is lower than a given percentage of the average.
class FilterByLogValue
Filters events in an EventWorkspace using values in a SampleLog.
class FilterByTime
Filters an EventWorkspace by wall-clock time, and outputs to a new event workspace or replaces the existing one.
class FilterByXValue
Filters the events in an event workspace according to a minimum and/or maximum value of X.
class FilterEvents
FilterEvents : Filter Events in EventWorkspace to multiple EventsWorkspace by Splitters.
class FindCenterOfMassPosition
Part of data reduction for SANS.
class FindCenterOfMassPosition2
Part of data reduction for SANS.
class FindDeadDetectors
Takes a workspace as input and identifies all of the spectra that have a value across all time bins less or equal to than the threshold 'dead' value.
class FindDetectorsOutsideLimits
Takes a workspace as input and identifies all spectra where the sum of the counts in all bins is outside a range.
class FindEPP
Performs Gaussian fits over each spectrum to find the Elastic Peak Position (EPP).
class FindPeakBackground
FindPeakBackground : Calculate Zscore for a Matrix Workspace.
class FindPeaks
This algorithm searches for peaks in a dataset.
class FindPeaksConvolve
FindPeaksConvolve : Finds peak centres using convolution with a shoebox kernel to approximate the second derivative, taking maxima above an I/Sigma threshold.
class FitOneSinglePeak
FitOneSinglePeak: a class to perform peak fitting on a single peak.
class FitPeak
FitPeak : Fit a single peak.
class FitPeaks
class FixGSASInstrumentFile
FixGSASInstrumentFile : TODO: DESCRIPTION.
class FlatPlateAbsorption
Calculates attenuation due to absorption and scattering in a flat plate/slab sample.
class FlatWeighting
class FlipperEfficiency
class GaussianWeightingnD
class GeneralisedSecondDifference
Compute the generalised second difference of a spectrum or several spectra based on the method described by M.A.
class GenerateEventsFilter
GenerateEventsFilter : Generate an events-filter, i.e., a SplittersWorkspace according to user's request.
class GenerateFlatCellWorkspaceLOQ
Generates the FlatCell workspace for ISIS SANS reduction of LOQ.
class GenerateGoniometerIndependentBackground
GenerateGoniometerIndependentBackground : TODO: DESCRIPTION.
class GenerateIPythonNotebook
GenerateIPythonNotebook.
class GeneratePeaks
GeneratePeaks : Generate peaks from a table workspace containing peak parameters.
class GeneratePythonFitScript
class GeneratePythonScript
GeneratePythonScript : TODO: DESCRIPTION.
class GetAllEi
Estimate all incident energies, used by chopper instrument.
class GetDetectorOffsets
Find the offsets for each detector.
class GetEi
Requires an estimate for the initial neutron energy which it uses to search for monitor peaks and from these calculate an accurate energy.
class GetEi2
Requires an estimate for the initial neutron energy which it uses to search for monitor peaks and from these calculate an accurate energy.
class GetEiMonDet3
Estimates the incident neutron energy from the time of flight between a monitor and a set of detectors.
class GetQsInQENSData
Extracts Q-values from a workspace containing QENS data.
class GetTimeSeriesLogInformation
GetTimeSeriesLogInformation : Read a TimeSeries log and return some information required by users.
class GravitySANSHelper
A helper class for calculating neutron's gravitional drop.
class GroupToXResolution
GroupToXResolution : Groups points within intervals defined by Dx into a single point.
class GroupWorkspaces
Takes workspaces as input and groups the workspaces.
class He3TubeEfficiency
Corrects the input workspace for helium3 tube efficiency based on an exponential parameterization.
class HeliumAnalyserEfficiency
class HeliumAnalyserEfficiencyTime
class HRPDSlabCanAbsorption
Calculates attenuation due to absorption and scattering in an HRPD 'slab' can.
class HyspecScharpfCorrection
HyspecScharpfCorrection : Divide by cos(2alpha) where alpha is the angle between incident beam and the polarization direction.
class IBeamProfile
Base class for all classes defining a beam profile.
class IdentifyNoisyDetectors
Identifies "bad" detectors based on their standard deviation, and how this differs from the standard deviation of other detectors.
class IMCAbsorptionStrategy
Defines a base class for objects that calculate correction factors for self-attenuation.
class IMCInteractionVolume
Defines a base class for objects describing a volume where interactions of Tracks and Objects can take place.
class IntegrateByComponent
IntegrateByComponent : The algorithm integrates up the instrument hierarchy, and each pixel will contain the average value for the component.
class IntegrateEPP
IntegrateEPP : Integrate a workspace around the elastic peak positions given by a EPP table.
class Integration
Takes a workspace as input and sums each spectrum contained within it, storing the result as a workspace of spectra with one Y & E value and two X values indicating the range which the integration covers.
class InterpolatingRebin
Uses cubic splines to interpolate the mean rate of change of the integral over the inputed data bins to that for the user supplied bins.
class InterpolationOption
Class to provide a consistent interface to an interpolation option on algorithms.
class InvertMask
InvertMask : TODO: DESCRIPTION.
class IQTransform
This algorithm permits the linearisation of reduced SANS data by applying a chosen transformation to the input data.
class LinearWeighting
class LineProfile
LineProfile : Calculates a horizontal or vertical line profile over a MatrixWorkspace.
class Logarithm
Takes a workspace as input and calculates the natural logarithm of number of counts for each 1D spectrum.
struct LoqMeta
class LorentzCorrection
LorentzCorrection : Algorithm Performs a lorentz correction (sin(theta)^2)/(wavelength^4) on a MatrixWorkspace in units of wavelength.
class MagFormFactorCorrection
MagneticFormFactors scales the input workspace by the 1/F(Q) where F(Q) is the magnetic form factor for the given magnetic ion.
class MaskBins
Masks bins in a workspace.
class MaskBinsFromTable
MaskBinsFromTable : TODO: DESCRIPTION.
class MaskBinsFromWorkspace
class MaskBinsIf
MaskBinsIf : Masks bins based on muparser expression.
class MaskDetectorsIf
This algorithm is used to select/deselect detectors in a *.cal file.
class MaskInstrument
Mask specified detectors in an instrument.
class MaskNonOverlappingBins
MaskNonOverlappingBins : Compares the X ranges of two workspace and masks the non-overlapping bins in the first workspace.
struct MatrixWorkspaceAccess
class Max
Takes a 2D workspace as input and find the maximum in each 1D spectrum.
class MaxEnt
MaxEnt : Entropy maximization algorithm following the approach described in the article by J.
class MaxentCalculator
MaxentCalculator : This class performs one maxent iteration and calculates chi-sq, angle between gradient of S and gradient of chi-sq, search directions and quadratic coefficients.
class MaxentEntropy
MaxentEntropy : Abstract base class defining the necessary methods to calculate any type of entropy to be used by MaxEnt.
class MaxentEntropyNegativeValues
MaxentEntropyNegativeValues : Class defining the entropy of a 'PosNeg' image (i.e.
class MaxentEntropyPositiveValues
MaxentEntropyPositiveValues : Class defining the entropy of a positive image (i.e.
class MaxentSpace
MaxentSpace : Abstract base class defining a MaxentSpace.
class MaxentSpaceComplex
MaxentSpaceComplex : Defines a space of complex numbers.
class MaxentSpaceReal
MaxentSpaceReal : Defines the space of real numbers.
class MaxentTransform
MaxentTransform : Abstract base class defining MaxEnt transformations from image space to data space and vice-versa.
class MaxentTransformFourier
MaxentTransformFourier : Defines a transformation from data space to image space (and vice-versa) where spaces are related by a 1D Fourier Transform.
class MaxentTransformMultiFourier
MaxentTransformMultiFourier : Defines a transformation from data space to image space (and vice-versa) where spaces are related by a 1D Fourier Transform, in which which the data has multiple spectra concatenatenated.
class MaxMin
Takes a 2D workspace as input and find the maximum(minimum) in each 1D spectrum.
class MayersSampleCorrection
Corrects for the effects of absorption and multiple scattering using the algorithm of Jerry Mayers.
class MayersSampleCorrectionStrategy
Applies the procedure found in section 4 of https://inis.iaea.org/search/search.aspx?orig_q=RN:20000574 for an array of tof, signal & error values.
class MCAbsorptionStrategy
Implements the algorithm for calculating the correction factor for self-attenuation and single wavelength using a Monte Carlo.
class MCInteractionStatistics
Stores statistics relating to the tracks generated in MCInteractionVolume for a specific detector.
class MCInteractionVolume
Defines a volume where interactions of Tracks and Objects can take place.
class MedianDetectorTest
Takes a workspace as input and finds all the detectors with solid angle corrected signals that deviate far enough from median value of all detectors to be suspious.
class MergeLogs
class MergeRuns
class Min
Takes a 2D workspace as input and find the minimum in each 1D spectrum.
class Minus
Minus performs the difference of two input workspaces.
class ModeratorTzero
class ModeratorTzeroLinear
class MonIDPropChanger
class MonitorEfficiencyCorUser
class MonteCarloAbsorption
Calculates attenuation due to absorption and scattering in a sample + its environment using a Monte Carlo algorithm.
class MostLikelyMean
MostLikelyMean : Computes the most likely mean of the array by minimizing the taxicab distance of the elements from the rest.
class MultipleScatteringCorrection
MultipleScatteringCorrection : TODO: DESCRIPTION.
class MultipleScatteringCorrectionDistGraber
MultipleScatteringCorrectionDistGraber : This is a helper class to calculate the distance from source to sample voxel.
class MultipleScatteringCylinderAbsorption
Multiple scattering absorption correction, originally used to correct vanadium spectrum at IPNS.
class Multiply
Multiply performs the product of two input workspaces.
class MultiplyRange
An algorithm to multiply a range of bins in a workspace by the factor given.
class NormaliseByCurrent
Normalises a workspace according to the good proton charge figure taken from the raw file (and stored in the Sample object).
class NormaliseByDetector
NormaliseByDetector : Normalises a workspace with respect to the detector efficiency function stored against components in the instrument parameters.
class NormaliseToMonitor
Normalizes a 2D workspace by a specified monitor spectrum.
class NormaliseToUnity
Takes a workspace as input and normalises it to 1.
class NullWeighting
class OneMinusExponentialCor
Corrects the data and error values on a workspace by one minus the value of an exponential function which is evaluated at the X value of each data point: c1(1-exp(-c*x)).
class PaalmanPingsAbsorptionCorrection
PaalmanPingsAbsorptionCorrection : calculate paalman-pings absorption terms.
class PaddingAndApodization
Takes a workspace as input and applies a apodization function and/or padding.
class ParabolicWeighting
class ParallaxCorrection
ParallaxCorrection : Performs geometrical correction for parallax effect in tube based SANS instruments.
class Pause
Pause a script for a given duration.
class PDCalibration
PDCalibration : TODO: DESCRIPTION.
class PDDetermineCharacterizations
PDDetermineCharacterizations.
class PDFFourierTransform
PDFFourierTransform : TODO: DESCRIPTION.
class PDFFourierTransform2
PDFFourierTransform : TODO: DESCRIPTION.
class PerformIndexOperations
PerformIndexOperations : Crop and sum a workspace according to the parsed workspace index operations provided.
class Plus
Plus performs the addition of two input workspaces.
class PointByPointVCorrection
First attempt at spectrum by spectrum division for vanadium normalisation correction.
class PoissonErrors
Takes a Data workspace and an original counts workspace input and updates the error values in the data workspace to be the same fractionally as the counts workspace.
class PolarizationCorrectionFredrikze
PolarizationCorrectionFredrikze : Algorithm to perform polarisation corrections on multi-period group workspaces that implements the Fredrikze (Dutch) method.
class PolarizationCorrectionWildes
PolarizationCorrectionWildes : This algorithm corrects for non-ideal component efficiencies in polarized neutron analysis.
class PolarizationEfficienciesWildes
class PolarizationEfficiencyCor
PolarizationEfficiencyCor: a generalised polarization correction algorithm.
class PolarizerEfficiency
class PolynomialCorrection
Corrects the data and error values on a workspace by the value of a polynomial function which is evaluated at the X value of each data point.
class Power
Provides the ability to raise the values in the workspace to a specified power.
class PowerLawCorrection
Corrects the data and error values on a workspace by the value of an exponential function which is evaluated at the X value of each data point: c0*x^C1.
class ProcessIndirectFitParameters
ProcessIndirectFitParameters : Convert a parameter table output by PlotPeakByLogValue to a MatrixWorkspace.
class Q1D2
Takes account of the effects of gravity for instruments where the y-axis points upwards, for example SANS instruments.
class Q1DWeighted
Part of data reduction for SANS.
class Qhelper
Helper class for the Q1D and Qxy algorithms.
class Qxy
This algorithm rebins a 2D workspace in units of wavelength into 2D Q.
class RadiusFilter
class RadiusSum
RadiusSum :
class RayTracerTester
Algorithm to test ray tracer by spraying evenly spaced rays around.
class ReadGroupsFromFile
Read a diffraction calibration file (*.cal) and an instrument name, and output a 2D workspace containing on the Y-axis the values of the Group each detector belongs to.
class Rebin
Takes a workspace as input and rebins the data according to the input rebin parameters.
class Rebin2D
Rebins both axes of a two-dimensional workspace to the given parameters.
class RebinByPulseTimes
RebinByPulseTimes : Rebin an input EventWorkspace according to the pulse times of the events.
class RebinByTimeAtSample
RebinByTimeAtSample : Rebins an event workspace to a histogram workspace with time at sample along the x-axis.
class RebinByTimeBase
RebinByTimeBase : Algorithm base class for algorithms performing rebinning by an absolute time axis.
class RebinRagged
RebinRagged : TODO: DESCRIPTION.
class RebinToWorkspace
Rebins a workspace so that the binning, for all its spectra, match that of the first spectrum of a second workspace.
class Rebunch
Takes a workspace as input and rebunches the data according to the input rebunch parameters.
class RectangularBeamProfile
Defines a flat, rectangular beam profile that has a width, height and center point.
class Regroup
Takes a 2D workspace as input and regroups the data according to the input regroup parameters.
class RemoveBackground
class RemoveBins
Removes bins from a workspace.
class RemoveInstrumentGeometry
RemoveInstrumentGeometry :
class RemoveLowResTOF
class RemoveMaskedSpectra
RemoveMaskedSpectra removes all masked spectra.
class RemovePromptPulse
RemovePromptPulse : TODO: DESCRIPTION.
class RemoveSpectra
class RemoveWorkspaceHistory
RemoveWorkspaceHistory.
class RenameWorkspace
Renames a workspace to a different name in the data service.
class RenameWorkspaces
Renames a workspace to a different name in the data service.
class ReplaceSpecialValues
Replaces instances of NaN and infinity in the workspace with user defined numbers.
class ResampleX
ResampleX : TODO: DESCRIPTION.
class ResetNegatives
ResetNegatives : Reset negative values to something else.
class ResizeRectangularDetector
ResizeRectangularDetector : TODO: DESCRIPTION.
class RingProfile
Calculates the sum of the counts against a circular ring.
class RunCombinationHelper
class SampleLogsBehaviour
SampleLogsBehaviour : This class holds information relating to the behaviour of the sample log merging.
class SANSCollimationLengthEstimator
class SassenaFFT
Perform Fourier Transform of the Sassena Intermediate Scattering Function.
class Scale
Scales an input workspace by the given factor, which can be either multiplicative or additive.
class ScaleX
Takes a workspace and adjusts all the time bin values by the same multiplicative factor.
struct ScatterPointStat
class Segfault
Segfault : TODO: DESCRIPTION.
class SetInstrumentParameter
SetInstrumentParameter : A simple algorithm to add or set the value of an instrument parameter.
class SetUncertainties
Set the uncertainties of the data to zero.
class ShiftLogTime
ShiftLogTime : TODO: DESCRIPTION.
class SignalOverError
Calculate Y/E for a Workspace2D.
class SmoothData
Smooths the data of the input workspace by making each point the mean average of itself and one or more points lying symmetrically either side of it.
class SmoothNeighbours
Smooth neighboring pixels.
struct SofQCommon
class SofQW
class SofQWCentre
Converts a 2D workspace that has axes of energy transfer against spectrum number to one that gives intensity as a function of momentum transfer against energy.
class SofQWNormalisedPolygon
Converts a 2D workspace that has axes of energy transfer against spectrum number to one that gives intensity as a function of momentum transfer against energy.
class SofQWPolygon
Converts a 2D workspace that has axes of energy transfer against spectrum number to one that gives intensity as a function of momentum transfer against energy.
class SolidAngle
Calculates and outputs the solid angles for each detector in the instrument.
class SortEvents
Takes an EventWorkspace and sorts by TOF or frame_index.
class SortXAxis
SortXAxis will take Histogram or Point data and reorder it based on the X Axis' values, whilst maintaining it's Dx, Y and E axis relative values.
class SparseWorkspace
Defines functions and utilities to create and deal with sparse instruments.
class SpatialGrouping
This algorithm creates an XML Grouping File for use in the GroupDetectors (v2) or ReadGroupsFromFile algorithms.
class SpectrumAlgorithm
SpectrumAlgorithm is a base class for algorithms that work with MatrixWorkspace.
class SphericalAbsorption
A spherical absorption correction algorithm.
class Stitch
Stitches overlapping spectra from multiple 2D workspaces.
class Stitch1D
Stitch1D : Stitches two Matrix Workspaces together into a single output.
class Stitch1DMany
Stitch1DMany : Stitches multiple Matrix Workspaces together into a single output.
class StripPeaks
This algorithm calls FindPeaks as a ChildAlgorithm and then subtracts all the peaks found from the data, leaving just the 'background'.
class StripVanadiumPeaks
StripVanadiumPeaks algorithm.
class StripVanadiumPeaks2
StripVanadiumPeaks2.
class SumEventsByLogValue
Produces a table or single spectrum workspace containing the total summed events in the workspace as a function of a specified log.
class SumNeighbours
Sums neighboring pixels on rectangular detectors.
class SumOverlappingTubes
SumOverlappingTubes : Converts workspaces containing an instrument with PSD tubes into a workspace with counts as a function of height and scattering angle.
class SumRowColumn
This algorithm is the equivalent of the COLETTE "DISPLAY H/V" command.
class SumSpectra
Takes a workspace as input and sums all of the spectra within it maintaining the existing bin structure and units.
class TOFSANSResolution
Computes the resolution on TOF SANS data Required Properties:
class TOFSANSResolutionByPixel
Calculates the TOF-SANS Q-resolution for each wavelenght and pixel using formula by Mildner and Carpenter.
class TOFSANSResolutionByPixelCalculator
Helper class which provides the uncertainty calculations for the TOFSANSResolutionByPixel class.
struct tolerant_less
Std-style comparision function object (satisfies the requirements of Compare)
class Transpose
This algorithm "transposes" the bins of the input workspace into a single spectra.
class UnaryOperation
UnaryOperation supports the implementation of a Unary operation on an input workspace.
class UnGroupWorkspace
Takes the name of a group workspace as input and ungroups the workspaces.
class UnwrapMonitor
Takes an input Workspace2D that contains 'raw' data, unwraps the data according to the reference flightpath provided and converts the units to wavelength.
class UnwrapMonitorsInTOF
UnwrapMonitorsInTOF : Handles workspaces which contain monitors that recorded data which spills over from the previous frame.
class UnwrapSNS
Takes an input Workspace2D that contains 'raw' data, unwraps the data according to the reference flightpath provided and converts the units to wavelength.
class UpdateScriptRepository
UpdateScriptRepository : Check the MantidWeb, for updates of the ScriptRepository.
class VesuvioL1ThetaResolution
VesuvioL1ThetaResolution.
class WeightedMean
An algorithm to calculate the weighted mean of two workspaces.
class WeightedMeanOfWorkspace
WeightedMeanOfWorkspace This algorithm calculates the weighted mean for a single workspace from all the detector (non-monitor, not masked) spectra in that workspace.
class WeightingStrategy
WeightingStrategy :
class WienerSmooth
WienerSmooth algorithm performes smoothing data in a spectrum of a matrix workspace using the Wiener filter smoothing.
class WorkflowAlgorithmRunner
Controls the data flow and the order of algorithm execution.
class WorkspaceBoundingBox
class WorkspaceJoiners
A base class to hold code common to two algorithms that bolt two workspaces together spectra-wise - ConjoinWorkspaces & AppendSpectra.
class XDataConverter
This is an abstract base class for sharing methods between algorithms that operate only on X data.
class XrayAbsorptionCorrection
Calculates attenuation of xrays due to absorption in a sample.
Typedefs
using DetConstPtr = Geometry::IDetector_const_sptr
using fptr = double(*)(const double, const double)
using MaxentEntropy_sptr = std::shared_ptr< MaxentEntropy >
using MaxentSpace_sptr = std::shared_ptr< MaxentSpace >
using MaxentSpaceComplex_sptr = std::shared_ptr< Mantid::Algorithms::MaxentSpaceComplex >
using MaxentSpaceReal_sptr = std::shared_ptr< Mantid::Algorithms::MaxentSpaceReal >
using MaxentTransform_sptr = std::shared_ptr< MaxentTransform >
using SparseWorkspace_sptr = std::shared_ptr< SparseWorkspace >
using SparseWorkspace_uptr = std::unique_ptr< SparseWorkspace >
unique pointer to Mantid::API::SparseWorkspace
using SpectraDistanceMap = std::map< specnum_t, Mantid::Kernel::V3D >
using SpectrumAlgorithm_sptr = std::shared_ptr< SpectrumAlgorithm >
Typedef for a shared pointer to a SpectrumAlgorithm.
using TrackPair = std::tuple< bool, std::shared_ptr< Geometry::Track >, std::shared_ptr< Geometry::Track > >
using VectorPair = std::pair< std::vector< double >, std::vector< double > >
Enumerations
enum class Modes { LINEAR_FIT , MEAN , MOVING_AVERAGE }
Enumeration for the different operating modes.
enum OperandType { eEventList = 0 , eHistogram = 1 , eNumber = 2 }
Functions
void addRowFromPreviousCalibration (DataObjects::TableWorkspace_sptr &ws, const DataObjects::TableWorkspace_sptr &previousTable, const std::size_t rowNum)
std::shared_ptr< Mantid::API::TableRow > binarySearchForRow (const API::ITableWorkspace_sptr &ws, const int detid, const size_t lastStart)
double calcD (double wavelength, double sintheta)
double calcDPerp (double wavelength, double logcostheta)
std::string CENTRE ("Centre")
template<typename NumT >
std::string checkValues (const std::vector< NumT > &thingy, const size_t numHist)
template<typename MAP >
void cleanPropertyTable (const ITableWorkspace_sptr &table, const MAP &ioMapping)
Transforms a setup table to an empty property table.
bool closeEnough (const double left, const double right)
Compare two numbers to be in agreement within 5%.
std::string createTruncatedList (const std::set< int > &elements)
Converts a list to a string, shortened if necessary.
string determineXMinMax (const MatrixWorkspace_sptr &inputWS, vector< double > &xmins, vector< double > &xmaxs)
Determine the min and max x-values for each spectrum and error check the pairs.
bool findColumn (const std::vector< std::string > &columnNames, const std::string &name)
std::string generateErrorString (const DataObjects::TableWorkspace_sptr &ws)
std::vector< std::string > getColumnNames ()
These should match those in LoadPDCharacterizations.
size_t getIndex (const HistogramData::HistogramX &vecx, double x)
Get an index of a value in a sorted vector.
size_t getIndex (const HistogramX &vecx, double x)
Get an index of a value in a sorted vector.
bool groupnumber (std::string groupi, std::string groupj)
Use group numbers for sorting.
static double gsl_costFunction (const gsl_vector *v, void *params)
The gsl_costFunction is optimized by GSL simplex.
VecCommands interpret (const std::string &processingInstructions)
Interpret the instructions as an ordered list of commands that can be executed later.
bool isHardCodedWorkspaceName (const std::string &s)
Checks if a string is a hard coded workspace name.
template<typename Comparator >
bool isItSorted (Comparator const &compare, const Mantid::API::MatrixWorkspace &inputWorkspace)
determines whether or not a given spectrum is sorted based on a passed comparator
std::string LEFT ("Left")
std::map< detid_t, int > makeGroupingByNames (std::string GroupNames, const Instrument_const_sptr &inst, Progress &prog, bool sortnames)
Use bank names to build grouping.
std::map< detid_t, int > makeGroupingByNumGroups (const std::string &compName, int numGroups, const Instrument_const_sptr &inst, Progress &prog)
Creates a mapping based on a fixed number of groups for a given instrument component.
std::map< detid_t, int > readGroupingFile (const std::string &groupingFileName, Progress &prog)
Read old-style .cal file to get the grouping.
Histogram smooth (const Histogram &histogram, unsigned int const npts)
Returns a smoothed version of histogram. npts must be odd.
HistogramData::Histogram smooth (const HistogramData::Histogram &histogram, unsigned int const npts)
template<typename Comparator >
void sortByXValue (std::vector< std::size_t > &workspaceIndices, const Mantid::API::MatrixWorkspace &inputWorkspace, unsigned int specNum, Comparator const &compare)
A template for sorting the values given a comparator.
bool spectrumDefinitionsMatchTimeIndex (const SpectrumDefinition &specDef, const size_t timeIndex)
std::string tidyWorkspaceName (const std::string &s)
Removes first and last character of a string.
void validateGroupItem (API::MatrixWorkspace_sptr const &workspace, std::map< std::string, std::string > &errorList, const std::string &spinFlipperLogName="")
Variables
const double CHOPPER_ANGLE [4] = {129.605, 179.989, 230.010, 230.007}
const double CHOPPER_LOCATION [4] = {5700., 7800., 9497., 9507.}
const double CHOPPER_PHASE_OFFSET [2][4] = {{9507., 9471., 9829.7, 9584.3}, {19024., 18820., 19714., 19360.}}
Kernel::Logger g_log ("DetermineSpinStateOrder")
constexpr double LAMBDA_CONVERSION_FACTOR = 0.0733
const size_t LINESIZE = 80
const double PULSEWIDTH = 20.0
Apply correction to EQSANS data to account for its TOF structure.
Typedef Documentation
DetConstPtr
using Mantid::Algorithms::DetConstPtr = typedef Geometry::IDetector_const_sptr
Definition at line 246 of file SofQWNormalisedPolygon.cpp.
fptr
using Mantid::Algorithms::fptr = typedef double (*)(const double, const double)
Definition at line 132 of file PaddingAndApodization.cpp.
MaxentEntropy_sptr
using Mantid::Algorithms::MaxentEntropy_sptr = typedef std::shared_ptr<MaxentEntropy>
Definition at line 33 of file MaxentEntropy.h.
MaxentSpace_sptr
typedef std::shared_ptr< MaxentSpace > Mantid::Algorithms::MaxentSpace_sptr
Definition at line 33 of file MaxentSpace.h.
MaxentSpaceComplex_sptr
typedef std::shared_ptr< MaxentSpaceComplex > Mantid::Algorithms::MaxentSpaceComplex_sptr
Definition at line 24 of file MaxentSpaceComplex.h.
MaxentSpaceReal_sptr
using Mantid::Algorithms::MaxentSpaceReal_sptr = typedef std::shared_ptr<Mantid::Algorithms::MaxentSpaceReal>
Definition at line 24 of file MaxentSpaceReal.h.
MaxentTransform_sptr
using Mantid::Algorithms::MaxentTransform_sptr = typedef std::shared_ptr<MaxentTransform>
Definition at line 31 of file MaxentTransform.h.
SparseWorkspace_sptr
using Mantid::Algorithms::SparseWorkspace_sptr = typedef std::shared_ptr<SparseWorkspace>
Definition at line 62 of file SparseWorkspace.h.
SparseWorkspace_uptr
using Mantid::Algorithms::SparseWorkspace_uptr = typedef std::unique_ptr<SparseWorkspace>
unique pointer to Mantid::API::SparseWorkspace
Definition at line 61 of file SparseWorkspace.h.
SpectraDistanceMap
typedef std::map< specnum_t, Mantid::Kernel::V3D > Mantid::Algorithms::SpectraDistanceMap
Definition at line 20 of file SmoothNeighbours.h.
SpectrumAlgorithm_sptr
using Mantid::Algorithms::SpectrumAlgorithm_sptr = typedef std::shared_ptr<SpectrumAlgorithm>
Typedef for a shared pointer to a SpectrumAlgorithm.
Definition at line 150 of file SpectrumAlgorithm.h.
TrackPair
using Mantid::Algorithms::TrackPair = typedef std::tuple<bool, std::shared_ptr<Geometry::Track>, std::shared_ptr<Geometry::Track> >
Definition at line 30 of file IMCInteractionVolume.h.
VectorPair
using Mantid::Algorithms::VectorPair = typedef std::pair<std::vector<double>, std::vector<double> >
Definition at line 20 of file HeliumAnalyserEfficiency.h.
Enumeration Type Documentation
Modes
enum class Mantid::Algorithms::Modes strong
Enumeration for the different operating modes.
Enumerator
LINEAR_FIT
MEAN
MOVING_AVERAGE
Definition at line 37 of file CalculateFlatBackground.cpp.
OperandType
enum Mantid::Algorithms::OperandType
Enumerator
eEventList
eHistogram
eNumber
Definition at line 22 of file BinaryOperation.h.
Function Documentation
addRowFromPreviousCalibration()
void Mantid::Algorithms::addRowFromPreviousCalibration (DataObjects::TableWorkspace_sptr & ws, const DataObjects::TableWorkspace_sptr & previousTable, const std::size_t rowNum)
Definition at line 229 of file CombineDiffCal.cpp.
References Mantid::Kernel::difa, Mantid::Kernel::difc, and Mantid::Kernel::tzero.
Referenced by Mantid::Algorithms::CombineDiffCal::exec().
binarySearchForRow()
std::shared_ptr< Mantid::API::TableRow > Mantid::Algorithms::binarySearchForRow (const API::ITableWorkspace_sptr & ws, const int detid, const size_t lastStart)
Definition at line 191 of file CombineDiffCal.cpp.
Referenced by Mantid::Algorithms::CombineDiffCal::exec().
calcD()
double Mantid::Algorithms::calcD (double wavelength, double sintheta)
Definition at line 370 of file Bin2DPowderDiffraction.cpp.
Referenced by Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace().
calcDPerp()
double Mantid::Algorithms::calcDPerp (double wavelength, double logcostheta)
Definition at line 372 of file Bin2DPowderDiffraction.cpp.
Referenced by Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace().
CENTRE()
std::string Mantid::Algorithms::CENTRE ("Centre")
Referenced by Mantid::Algorithms::FilterByLogValue::exec(), and Mantid::Algorithms::FilterByLogValue::init().
checkValues()
template<typename NumT > std::string Mantid::Algorithms::checkValues (const std::vector< NumT > & thingy, const size_t numHist)
Definition at line 84 of file EditInstrumentGeometry.cpp.
Referenced by Mantid::Algorithms::EditInstrumentGeometry::validateInputs().
cleanPropertyTable()
template<typename MAP > void Mantid::Algorithms::cleanPropertyTable (const ITableWorkspace_sptr & table, const MAP & ioMapping)
Transforms a setup table to an empty property table.
Clear cells referred to in ioMapping, if they do not contain hard coded values. In the case of hard coded values, removes '"' and ''' characters.
Template Parameters
MAP a type with std::map like iterators
Parameters
[in,out] table the table to be cleaned
[in] ioMapping input/output property lookup table
Exceptions
std::runtime_error in case of errorneous entries in table
Definition at line 60 of file WorkflowAlgorithmRunner.cpp.
References isHardCodedWorkspaceName(), and tidyWorkspaceName().
Referenced by Mantid::Algorithms::WorkflowAlgorithmRunner::exec().
closeEnough()
bool Mantid::Algorithms::closeEnough (const double left, const double right)
Compare two numbers to be in agreement within 5%.
Parameters
left
right
Returns
Definition at line 143 of file PDDetermineCharacterizations.cpp.
References fabs, left, and right.
Referenced by Mantid::Algorithms::PDDetermineCharacterizations::getInformationFromTable().
createTruncatedList()
std::string Mantid::Algorithms::createTruncatedList (const std::set< int > & elements)
Converts a list to a string, shortened if necessary.
Converts a set of ints to a string with each element separated by a comma.
If there are more than 10 elements, the format "a,b...(n more)...y,z" is used.
Parameters
elements :: The set of elements to be converted
Returns
The truncated list as a string
Definition at line 354 of file CreateDetectorTable.cpp.
References std::to_string().
Referenced by Mantid::Algorithms::CreateDetectorTable::populateTable().
determineXMinMax()
string Mantid::Algorithms::determineXMinMax (const MatrixWorkspace_sptr & inputWS, vector< double > & xmins, vector< double > & xmaxs)
Determine the min and max x-values for each spectrum and error check the pairs.
Parameters
inputWS The workspace to check the numbers for.
xmins The input/output that will hold the x-mins.
xmaxs The input/output that will hold the x-maxs.
Returns
Any error messages generated during the execution. If empty everything went according to plan.
Definition at line 107 of file ResampleX.cpp.
References value.
Referenced by Mantid::Algorithms::ResampleX::exec().
findColumn()
bool Mantid::Algorithms::findColumn (const std::vector< std::string > & columnNames, const std::string & name)
Definition at line 98 of file CombineDiffCal.cpp.
References name.
Referenced by generateErrorString().
generateErrorString()
std::string Mantid::Algorithms::generateErrorString (const DataObjects::TableWorkspace_sptr & ws)
Definition at line 102 of file CombineDiffCal.cpp.
References error, and findColumn().
Referenced by Mantid::Algorithms::CombineDiffCal::validateInputs().
getColumnNames()
std::vector< std::string > Mantid::Algorithms::getColumnNames ()
These should match those in LoadPDCharacterizations.
"frequency" double
"wavelength" (double)
"bank" (integer)
"container" (string)
"vanadium" (string)
"vanadium_background" (string)
"empty" (string)
"d_min" (string)
"d_max" (string)
"tof_min" (double)
"tof_max" (double)
"wavelength_min" (double)
"wavelength_max" (double)
Returns
The list of expected column names
Definition at line 70 of file PDDetermineCharacterizations.cpp.
Referenced by Mantid::Algorithms::PDDetermineCharacterizations::exec(), and Mantid::Algorithms::PDDetermineCharacterizations::validateInputs().
getIndex() [1/2]
size_t Mantid::Algorithms::getIndex (const HistogramData::HistogramX & vecx, double x)
Get an index of a value in a sorted vector.
The index should be the item with value nearest to X
Referenced by Mantid::Algorithms::FitOneSinglePeak::setFitWindow(), Mantid::Algorithms::FitOneSinglePeak::setPeakRange(), Mantid::Algorithms::FitOneSinglePeak::setupGuessedFWHM(), and Mantid::Algorithms::FitPeak::setupOutput().
getIndex() [2/2]
size_t Mantid::Algorithms::getIndex (const HistogramX & vecx, double x)
Get an index of a value in a sorted vector.
The index should be the item with value nearest to X
Definition at line 1468 of file FitPeak.cpp.
References index, and Mantid::Geometry::x.
groupnumber()
bool Mantid::Algorithms::groupnumber (std::string groupi, std::string groupj)
Use group numbers for sorting.
Parameters
groupi :: first group string
groupj :: second group string
Returns
true if first group number is less than second group number
Definition at line 458 of file CreateGroupingWorkspace.cpp.
References Mantid::Kernel::Strings::convert().
Referenced by makeGroupingByNames().
gsl_costFunction()
static double Mantid::Algorithms::gsl_costFunction (const gsl_vector * v, void * params) static
The gsl_costFunction is optimized by GSL simplex.
Parameters
v :: vector containing center position and rotations
params :: names of detector, workspace, and instrument
Definition at line 50 of file DiffractionEventCalibrateDetectors.cpp.
References Mantid::Algorithms::DiffractionEventCalibrateDetectors::intensity(), Mantid::Geometry::x, Mantid::Geometry::y, and Mantid::Geometry::z.
Referenced by Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec().
interpret()
VecCommands Mantid::Algorithms::interpret (const std::string & processingInstructions)
Interpret the instructions as an ordered list of commands that can be executed later.
Parameters
processingInstructions : Instructions to process
Returns
Vector of Commands. Commands wrap mantid-algorithmic steps to achieve the desired result.
Definition at line 276 of file PerformIndexOperations.cpp.
Referenced by Mantid::Algorithms::PerformIndexOperations::exec().
isHardCodedWorkspaceName()
bool Mantid::Algorithms::isHardCodedWorkspaceName (const std::string & s)
Checks if a string is a hard coded workspace name.
Parameters
s string to be checked
Returns
return true if s is surrounded by '"' or '''
Definition at line 30 of file WorkflowAlgorithmRunner.cpp.
Referenced by cleanPropertyTable(), and Mantid::Algorithms::WorkflowAlgorithmRunner::configureRow().
isItSorted()
template<typename Comparator > bool Mantid::Algorithms::isItSorted (Comparator const & compare, const Mantid::API::MatrixWorkspace & inputWorkspace)
determines whether or not a given spectrum is sorted based on a passed comparator
Template Parameters
Comparator
Parameters
compare std::less<double> for descending and std::greater<double> for ascending
inputWorkspace the unsorted input workspace
Returns
true if it is sorted
false if it is not sorted
Definition at line 197 of file SortXAxis.cpp.
References Mantid::API::MatrixWorkspace::getNumberHistograms(), rhs, and Mantid::API::MatrixWorkspace::x().
Referenced by Mantid::Algorithms::SortXAxis::determineIfHistogramIsValid().
LEFT()
std::string Mantid::Algorithms::LEFT ("Left")
Referenced by Mantid::Algorithms::FilterByLogValue::init().
makeGroupingByNames()
std::map< detid_t, int > Mantid::Algorithms::makeGroupingByNames (std::string GroupNames, const Instrument_const_sptr & inst, Progress & prog, bool sortnames)
Use bank names to build grouping.
Parameters
GroupNames :: comma-sep list of bank names
inst :: instrument
prog :: progress report
sortnames :: sort names - a boolean
Returns
:: map of detID to group number
Definition at line 481 of file CreateGroupingWorkspace.cpp.
References groupnumber(), index, Mantid::Kernel::ProgressBase::report(), and Mantid::Kernel::ProgressBase::setNumSteps().
Referenced by Mantid::Algorithms::CreateGroupingWorkspace::exec().
makeGroupingByNumGroups()
std::map< detid_t, int > Mantid::Algorithms::makeGroupingByNumGroups (const std::string & compName, int numGroups, const Instrument_const_sptr & inst, Progress & prog)
Creates a mapping based on a fixed number of groups for a given instrument component.
Parameters
compName Name of component in instrument
numGroups Number of groups to group detectors into
inst Pointer to instrument
prog Progress reporter
Returns
:: Map of detector IDs to group number
Definition at line 419 of file CreateGroupingWorkspace.cpp.
References Mantid::Kernel::ProgressBase::report().
Referenced by Mantid::Algorithms::CreateGroupingWorkspace::exec().
readGroupingFile()
std::map< detid_t, int > Mantid::Algorithms::readGroupingFile (const std::string & groupingFileName, Progress & prog)
Read old-style .cal file to get the grouping.
Parameters
groupingFileName :: path to .cal multi-col ascii
prog :: progress reporter
Returns
:: map of key=detectorID, value=group number.
Definition at line 386 of file CreateGroupingWorkspace.cpp.
References group, n, and Mantid::Kernel::ProgressBase::report().
Referenced by Mantid::Algorithms::CreateGroupingWorkspace::exec().
smooth() [1/2]
Histogram Mantid::Algorithms::smooth (const Histogram & histogram, unsigned int const npts)
Returns a smoothed version of histogram. npts must be odd.
Definition at line 133 of file SmoothData.cpp.
References Mantid::Kernel::Smoothing::boxcarErrorSmooth(), Mantid::Kernel::Smoothing::boxcarSmooth(), and Mantid::Geometry::Y.
smooth() [2/2]
HistogramData::Histogram Mantid::Algorithms::smooth (const HistogramData::Histogram & histogram, unsigned int const npts)
Referenced by Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SumNeighbours::exec(), and Mantid::Algorithms::FindPeaks::smoothData().
sortByXValue()
template<typename Comparator > void Mantid::Algorithms::sortByXValue (std::vector< std::size_t > & workspaceIndices, const Mantid::API::MatrixWorkspace & inputWorkspace, unsigned int specNum, Comparator const & compare)
A template for sorting the values given a comparator.
Template Parameters
Comparator
Parameters
workspaceIndices the vector of indices values
inputWorkspace the original workspace
specNum the Spectrum number to be sorted
compare std::less<double> for Ascending order std::greater<double> for descending order
Definition at line 100 of file SortXAxis.cpp.
References rhs.
Referenced by Mantid::Algorithms::SortXAxis::sortIndicesByX().
spectrumDefinitionsMatchTimeIndex()
bool Mantid::Algorithms::spectrumDefinitionsMatchTimeIndex (const SpectrumDefinition & specDef, const size_t timeIndex)
Definition at line 150 of file NormaliseToMonitor.cpp.
Referenced by Mantid::Algorithms::NormaliseToMonitor::normaliseBinByBin(), and Mantid::Algorithms::NormaliseToMonitor::performHistogramDivision().
tidyWorkspaceName()
std::string Mantid::Algorithms::tidyWorkspaceName (const std::string & s)
Removes first and last character of a string.
Parameters
s string to be tidied
Returns
tidied string
Exceptions
std::runtime_error if s is too short
Definition at line 44 of file WorkflowAlgorithmRunner.cpp.
Referenced by cleanPropertyTable(), and Mantid::Algorithms::WorkflowAlgorithmRunner::configureRow().
validateGroupItem()
void Mantid::Algorithms::validateGroupItem (API::MatrixWorkspace_sptr const & workspace, std::map< std::string, std::string > & errorList, const std::string & spinFlipperLogName = "")
Definition at line 71 of file DetermineSpinStateOrder.cpp.
References workspace.
Referenced by Mantid::Algorithms::DetermineSpinStateOrder::validateInputs().
Variable Documentation
CHOPPER_ANGLE
const double Mantid::Algorithms::CHOPPER_ANGLE[4] = {129.605, 179.989, 230.010, 230.007}
Definition at line 34 of file EQSANSTofStructure.h.
Referenced by Mantid::Algorithms::EQSANSTofStructure::getTofOffset().
CHOPPER_LOCATION
const double Mantid::Algorithms::CHOPPER_LOCATION[4] = {5700., 7800., 9497., 9507.}
Definition at line 36 of file EQSANSTofStructure.h.
Referenced by Mantid::Algorithms::EQSANSTofStructure::getTofOffset().
CHOPPER_PHASE_OFFSET
const double Mantid::Algorithms::CHOPPER_PHASE_OFFSET[2][4] = {{9507., 9471., 9829.7, 9584.3}, {19024., 18820., 19714., 19360.}}
Definition at line 32 of file EQSANSTofStructure.h.
Referenced by Mantid::Algorithms::EQSANSTofStructure::getTofOffset().
g_log
Kernel::Logger Mantid::Algorithms::g_log("DetermineSpinStateOrder") ("DetermineSpinStateOrder")
Referenced by Mantid::Algorithms::CorrectTOFAxis::averageL2(), Mantid::Algorithms::CorrectTOFAxis::averageL2AndEPP(), Mantid::Algorithms::MergeRuns::buildScanningOutputWorkspace(), Mantid::Algorithms::WeightedMean::checkCompatibility(), Mantid::Algorithms::ConjoinWorkspaces::checkForOverlap(), Mantid::Algorithms::MergeRuns::checkRebinning(), Mantid::Algorithms::Minus::checkUnitCompatibility(), Mantid::Algorithms::Plus::checkUnitCompatibility(), Mantid::Algorithms::AnyShapeAbsorption::constructGaugeVolume(), Mantid::Algorithms::CorrectTOFAxis::correctManually(), Mantid::Algorithms::InterpolatingRebin::cubicInterpolation(), Mantid::Algorithms::ResampleX::determineBinning(), Mantid::Algorithms::MedianDetectorTest::doDetectorTests(), Mantid::Algorithms::AppendSpectra::exec(), Mantid::Algorithms::CalculateCarpenterSampleCorrection::exec(), Mantid::Algorithms::ConjoinWorkspaces::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::CreatePSDBleedMask::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::InterpolatingRebin::exec(), Mantid::Algorithms::MedianDetectorTest::exec(), Mantid::Algorithms::MergeRuns::exec(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::SofQWCentre::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::Algorithms::MergeRuns::execEvent(), Mantid::Algorithms::MergeRuns::execHistogram(), Mantid::Algorithms::SANSCollimationLengthEstimator::getGuideValue(), Mantid::Algorithms::MedianDetectorTest::getSolidAngles(), Mantid::CurveFitting::Algorithms::getWorkspace(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesNonPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesTable(), Mantid::Algorithms::FlatPlateAbsorption::initialiseCachedDistances(), Mantid::Algorithms::SofQWPolygon::initThetaCache(), Mantid::Algorithms::ConvertToHistogram::isProcessingRequired(), Mantid::Algorithms::ConvertToPointData::isProcessingRequired(), Mantid::Algorithms::WorkspaceBoundingBox::isValidIndex(), Mantid::Algorithms::InterpolatingRebin::outputYandEValues(), Mantid::Algorithms::Divide::performBinaryOperation(), Mantid::Algorithms::CreatePSDBleedMask::performBleedTest(), Mantid::Algorithms::SANSCollimationLengthEstimator::provideCollimationLength(), Mantid::Algorithms::MedianDetectorTest::retrieveProperties(), Mantid::Algorithms::CylinderAbsorption::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyVariation::retrieveProperties(), Mantid::Algorithms::SparseWorkspace::SparseWorkspace(), Mantid::Algorithms::InterpolatingRebin::validateInputs(), Mantid::Algorithms::MergeRuns::validateInputsForEventWorkspaces(), and Mantid::Algorithms::RunCombinationHelper::validateInputWorkspaces().
LAMBDA_CONVERSION_FACTOR
constexpr double Mantid::Algorithms::LAMBDA_CONVERSION_FACTOR = 0.0733 constexpr
Definition at line 36 of file HeliumAnalyserEfficiency.cpp.
Referenced by Mantid::Algorithms::HeliumAnalyserEfficiencyTime::calculateOutputs(), Mantid::Algorithms::HeliumAnalyserEfficiency::convertToTheoreticalEfficiencies(), and Mantid::Algorithms::HeliumAnalyserEfficiency::exec().
LINESIZE
const size_t Mantid::Algorithms::LINESIZE = 80
Definition at line 32 of file FixGSASInstrumentFile.cpp.
Referenced by Mantid::Algorithms::FixGSASInstrumentFile::exec().
PULSEWIDTH
const double Mantid::Algorithms::PULSEWIDTH = 20.0
Apply correction to EQSANS data to account for its TOF structure.
The algorithm modifies the TOF values to correct for the fact that T_0 is not properly recorded by the DAS.
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 30 of file EQSANSTofStructure.h.
Referenced by Mantid::Algorithms::EQSANSTofStructure::getTofOffset().