Mantid: Mantid::PythonInterface::std_set_exporter< ElementType > Struct Template Reference
Mantid::PythonInterface::std_set_exporter< ElementType > Struct Template Reference
std::set wrapper
#include <StlExportDefinitions.h>
Public Types
using e_t = ElementType
using w_t = std::set< ElementType >
Static Public Member Functions
static bool contains (w_t const &self, e_t const &x)
static boost::python::tuple getinitargs (w_t const &self)
static e_t getitem (w_t const &self, std::size_t i)
static void insert_element (w_t &self, e_t const &x)
static void insert_set (w_t &self, w_t const &other)
static std::string to_string (const w_t &values)
static void wrap (std::string const &python_name)
Detailed Description
template<typename ElementType>
struct Mantid::PythonInterface::std_set_exporter< ElementType >
std::set wrapper
Definition at line 95 of file StlExportDefinitions.h.
Member Typedef Documentation
e_t
template<typename ElementType > using Mantid::PythonInterface::std_set_exporter< ElementType >::e_t = ElementType
Definition at line 97 of file StlExportDefinitions.h.
w_t
template<typename ElementType > using Mantid::PythonInterface::std_set_exporter< ElementType >::w_t = std::set<ElementType>
Definition at line 96 of file StlExportDefinitions.h.
Member Function Documentation
contains()
template<typename ElementType > static bool Mantid::PythonInterface::std_set_exporter< ElementType >::contains (w_t const & self, e_t const & x) inline static
Definition at line 103 of file StlExportDefinitions.h.
References Mantid::Geometry::x.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
getinitargs()
template<typename ElementType > static boost::python::tuple Mantid::PythonInterface::std_set_exporter< ElementType >::getinitargs (w_t const & self) inline static
Definition at line 113 of file StlExportDefinitions.h.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
getitem()
template<typename ElementType > static e_t Mantid::PythonInterface::std_set_exporter< ElementType >::getitem (w_t const & self, std::size_t i) inline static
Definition at line 105 of file StlExportDefinitions.h.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
insert_element()
template<typename ElementType > static void Mantid::PythonInterface::std_set_exporter< ElementType >::insert_element (w_t & self, e_t const & x) inline static
Definition at line 99 of file StlExportDefinitions.h.
References Mantid::Geometry::x.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
insert_set()
template<typename ElementType > static void Mantid::PythonInterface::std_set_exporter< ElementType >::insert_set (w_t & self, w_t const & other) inline static
Definition at line 101 of file StlExportDefinitions.h.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
to_string()
template<typename ElementType > static std::string Mantid::PythonInterface::std_set_exporter< ElementType >::to_string (const w_t & values) inline static
Definition at line 117 of file StlExportDefinitions.h.
Referenced by Mantid::PythonInterface::std_set_exporter< ElementType >::wrap().
wrap()
template<typename ElementType > static void Mantid::PythonInterface::std_set_exporter< ElementType >::wrap (std::string const & python_name) inline static
Definition at line 126 of file StlExportDefinitions.h.
References Mantid::PythonInterface::std_set_exporter< ElementType >::contains(), Mantid::PythonInterface::std_set_exporter< ElementType >::getinitargs(), Mantid::PythonInterface::std_set_exporter< ElementType >::getitem(), Mantid::PythonInterface::std_set_exporter< ElementType >::insert_element(), Mantid::PythonInterface::std_set_exporter< ElementType >::insert_set(), and Mantid::PythonInterface::std_set_exporter< ElementType >::to_string().
Referenced by exportStlContainers().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/StlExportDefinitions.h