Mantid: Mantid::Kernel::Units::SpinEchoTime Class Reference
Mantid::Kernel::Units::SpinEchoTime Class Reference
SpinEchoTime in ns.
#include <Unit.h>
Public Member Functions
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
double conversionTOFMin () const override
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
SpinEchoTime ()
Constructor.
const std::string unitID () const override
"SpinEchoTime"
Public Member Functions inherited from Mantid::Kernel::Units::Wavelength
const std::string caption () const override
The full name of the unit.
Unit * clone () const override
double conversionTOFMax () const override
double conversionTOFMin () const override
void init () override
Finalize the initialization.
const UnitLabel label () const override
A label for the unit to be printed on axes,.
double singleFromTOF (const double tof) const override
Convert a single tof value to this unit.
double singleToTOF (const double x) const override
Convert a single X value to TOF.
const std::string unitID () const override
"Wavelength"
Wavelength ()
Constructor.
Public Member Functions inherited from Mantid::Kernel::Unit
virtual const std::string caption () const =0
The full name of the unit.
virtual Unit * clone () const =0
virtual std::pair< double, double > conversionRange () const
The range where conversion to TOF from given units is monotonic and reversible.
virtual double conversionTOFMax () const =0
This function returns maximal TOF value still reversibly convertible into the unit.
virtual double conversionTOFMin () const =0
some units can be converted from TOF only in the range of TOF ; This function returns minimal TOF value still reversibly convertible into the unit.
double convertSingleFromTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the time-of-flight to the concrete unit.
double convertSingleToTOF (const double xvalue, const double &l1, const int &emode, const UnitParametersMap &params)
Convert from the concrete unit to time-of-flight.
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void fromTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from time-of-flight to the concrete unit.
virtual void init ()=0
Finalize the initialization.
void initialize (const double &_l1, const int &_emode, const UnitParametersMap &params)
Initialize the unit to perform conversion using singleToTof() and singleFromTof()
virtual bool isConvertible () const
Returns if the unit can be used in conversions.
bool isInitialized () const
virtual const UnitLabel label () const =0
A label for the unit to be printed on axes,.
bool operator!= (const Unit &u) const
bool operator== (const Unit &u) const
bool quickConversion (const Unit &destination, double &factor, double &power) const
Is conversion by constant multiplication possible?
bool quickConversion (std::string destUnitName, double &factor, double &power) const
Is conversion by constant multiplication possible?
virtual double singleFromTOF (const double tof) const =0
Convert a single tof value to this unit.
virtual double singleToTOF (const double x) const =0
Convert a single X value to TOF.
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, const UnitParametersMap &params)
void toTOF (std::vector< double > &xdata, std::vector< double > &ydata, const double &_l1, const int &_emode, std::initializer_list< std::pair< const UnitParams, double > > params)
Convert from the concrete unit to time-of-flight.
Unit ()
(Empty) Constructor
virtual const std::string unitID () const =0
The name of the unit.
virtual ~Unit ()=default
Virtual destructor.
Private Attributes
double efixed
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::Units::Wavelength
void validateUnitParams (const int emode, const UnitParametersMap &params) override
Protected Member Functions inherited from Mantid::Kernel::Unit
void addConversion (std::string to, const double &factor, const double &power=1.0) const
Add a 'quick conversion' from the unit class on which this method is called.
virtual void validateUnitParams (const int emode, const UnitParametersMap &params)
Protected Attributes inherited from Mantid::Kernel::Units::Wavelength
bool do_sfpFrom
Apply the sfpFrom value.
double efixed
double factorFrom
Constant factor for from conversion.
double factorTo
Constant factor for to conversion.
double sfpFrom
Extra correction factor in from conversion.
double sfpTo
Extra correction factor in to conversion.
Protected Attributes inherited from Mantid::Kernel::Unit
int emode
emode :: The energy mode (0=elastic, 1=direct geometry, 2=indirect geometry)
bool initialized
The unit values have been initialized.
double l1
l1 :: The source-sample distance (in metres)
const UnitParametersMap * m_params
additional parameters l2 :: distance from sample to detector (in metres) twoTheta :: scattering angle in radians efixed :: Value of fixed energy: EI (emode=1) or EF (emode=2) (in meV) difc :: diffractometer constant DIFC
Detailed Description
SpinEchoTime in ns.
Definition at line 588 of file Unit.h.
Constructor & Destructor Documentation
SpinEchoTime()
Mantid::Kernel::Units::SpinEchoTime::SpinEchoTime ()
Constructor.
Definition at line 1275 of file Unit.cpp.
Referenced by clone().
Member Function Documentation
caption()
const std::string Mantid::Kernel::Units::SpinEchoTime::caption () const inline override virtual
The full name of the unit.
Returns
The unit caption
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 591 of file Unit.h.
clone()
Unit * Mantid::Kernel::Units::SpinEchoTime::clone () const override virtual
Returns
a cloned instance of the other
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1307 of file Unit.cpp.
References SpinEchoTime().
conversionTOFMax()
double Mantid::Kernel::Units::SpinEchoTime::conversionTOFMax () const override virtual
Returns
Maximal time of flight, which can be reversively converted into wavelength
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1294 of file Unit.cpp.
References efixed.
conversionTOFMin()
double Mantid::Kernel::Units::SpinEchoTime::conversionTOFMin () const override virtual
Returns
Minimal time of flight, which can be reversively converted into wavelength
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1293 of file Unit.cpp.
init()
void Mantid::Kernel::Units::SpinEchoTime::init () override virtual
Finalize the initialization.
This will be overridden by subclasses as needed.
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1277 of file Unit.cpp.
References Mantid::Kernel::efixed, efixed, Mantid::Kernel::Unit::emode, Mantid::Kernel::Units::Wavelength::init(), and Mantid::Kernel::Unit::m_params.
label()
const UnitLabel Mantid::Kernel::Units::SpinEchoTime::label () const override virtual
A label for the unit to be printed on axes,.
See also
UnitLabel
Returns
The unit label
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1273 of file Unit.cpp.
References Mantid::Kernel::Units::Symbol::Nanosecond.
singleFromTOF()
double Mantid::Kernel::Units::SpinEchoTime::singleFromTOF (const double tof) const override virtual
Convert a single tof value to this unit.
Parameters
tof value to convert
Returns
the value in this unit as converted.
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1301 of file Unit.cpp.
References efixed, Mantid::Kernel::Units::Wavelength::singleFromTOF(), and Mantid::Geometry::x.
singleToTOF()
double Mantid::Kernel::Units::SpinEchoTime::singleToTOF (const double x) const override virtual
Convert a single X value to TOF.
Parameters
x value to convert
Returns
the TOF as converted.
Reimplemented from Mantid::Kernel::Units::Wavelength.
Definition at line 1288 of file Unit.cpp.
References efixed, Mantid::Kernel::Units::Wavelength::singleToTOF(), and Mantid::Geometry::x.
unitID()
const std::string Mantid::Kernel::Units::SpinEchoTime::unitID () const override virtual
"SpinEchoTime"
Reimplemented from Mantid::Kernel::Units::Wavelength.
Member Data Documentation
efixed
double Mantid::Kernel::Units::SpinEchoTime::efixed private
Definition at line 605 of file Unit.h.
Referenced by conversionTOFMax(), init(), singleFromTOF(), and singleToTOF().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Unit.h
Framework/Kernel/src/Unit.cpp