Mantid: Framework/CurveFitting/src/Algorithms/LeBailFit.cpp File Reference
LeBailFit.cpp File Reference
#include "MantidCurveFitting/Algorithms/LeBailFit.h"
#include "MantidAPI/FuncMinimizerFactory.h"
#include "MantidAPI/FunctionFactory.h"
#include "MantidAPI/TableRow.h"
#include "MantidAPI/TextAxis.h"
#include "MantidAPI/WorkspaceFactory.h"
#include "MantidCurveFitting/Algorithms/Fit.h"
#include "MantidCurveFitting/Functions/BackgroundFunction.h"
#include "MantidHistogramData/HistogramX.h"
#include "MantidHistogramData/HistogramY.h"
#include "MantidKernel/ArrayProperty.h"
#include "MantidKernel/ListValidator.h"
#include "MantidKernel/VisibleWhenProperty.h"
#include <boost/algorithm/string.hpp>
#include <cctype>
#include <fstream>
#include <iomanip>
Namespaces
namespace Mantid
Helper class which provides the Collimation Length for SANS instruments.
namespace Mantid::CurveFitting
namespace Mantid::CurveFitting::Algorithms
Functions
const int CALBKGDINDEX (4)
const int CALDATAINDEX (1)
const int CALPUREPEAKINDEX (3)
const int DATADIFFINDEX (2)
const double EPSILON (1.0E-10)
const int INPUTBKGDINDEX (6)
const int INPUTPUREPEAKINDEX (7)
const double NOBOUNDARYLIMIT (1.0E10)
const int OBSDATAINDEX (0)
void Mantid::CurveFitting::Algorithms::writeRfactorsToFile (const std::vector< double > &vecX, const std::vector< Kernel::Rfactor > &vecR, const std::string &filename)
Write a set of (XY) data to a column file.
Variables
const Rfactor Mantid::CurveFitting::Algorithms::badR (DBL_MAX, DBL_MAX)
Function Documentation
CALBKGDINDEX()
const int CALBKGDINDEX (4)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground().
CALDATAINDEX()
const int CALDATAINDEX (1)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer().
CALPUREPEAKINDEX()
const int CALPUREPEAKINDEX (3)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground().
DATADIFFINDEX()
const int DATADIFFINDEX (2)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer().
EPSILON()
const double EPSILON (1.0E- 10)
Referenced by Mantid::Geometry::classify(), Mantid::Geometry::crossingPoint(), Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain(), Mantid::API::MatrixWorkspace::isCommonBins(), Mantid::API::MatrixWorkspace::isCommonLogBins(), Mantid::Geometry::orientation(), and Mantid::Geometry::MeshObjectCommon::rayIntersectsTriangle().
INPUTBKGDINDEX()
const int INPUTBKGDINDEX (6)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer().
INPUTPUREPEAKINDEX()
const int INPUTPUREPEAKINDEX (7)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::CurveFitting::Algorithms::LeBailFit::execRandomWalkMinimizer(), and Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground().
NOBOUNDARYLIMIT()
const double NOBOUNDARYLIMIT (1. 0E10)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::limitProposedValueInBound().
OBSDATAINDEX()
const int OBSDATAINDEX (0)
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::createOutputDataWorkspace(), and Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation().