Mantid: Mantid::DataHandling::ParallelEventLoader Class Reference
Mantid::DataHandling::ParallelEventLoader Class Reference
Loader for event data from Nexus files with parallelism based on multiple processes (MPI or MultiProcessing) for performance.
#include <ParallelEventLoader.h>
Static Public Member Functions
static void loadMPI (DataObjects::EventWorkspace &ws, const std::string &filename, const std::string &groupName, const std::vector< std::string > &bankNames, const bool eventIDIsSpectrumNumber)
Load events from given banks into given EventWorkspace using MPI.
static void loadMultiProcess (DataObjects::EventWorkspace &ws, const std::string &filename, const std::string &groupName, const std::vector< std::string > &bankNames, const bool eventIDIsSpectrumNumber, const bool precalcEvents)
Load events from given banks into given EventWorkspace using boost::interprocess.
Detailed Description
Loader for event data from Nexus files with parallelism based on multiple processes (MPI or MultiProcessing) for performance.
This class provides integration of the low level loader component Parallel::IO::EventLoader with higher level concepts such as DataObjects::EventWorkspace and the instrument.
Author
Simon Heybrock
Date
2017
Definition at line 28 of file ParallelEventLoader.h.
Member Function Documentation
loadMPI()
void Mantid::DataHandling::ParallelEventLoader::loadMPI (DataObjects::EventWorkspace & ws, const std::string & filename, const std::string & groupName, const std::vector< std::string > & bankNames, const bool eventIDIsSpectrumNumber) static
Load events from given banks into given EventWorkspace using MPI.
Definition at line 96 of file ParallelEventLoader.cpp.
References Mantid::DataHandling::getOffsets(), Mantid::DataHandling::getResultVector(), and Mantid::API::MatrixWorkspace::indexInfo().
loadMultiProcess()
void Mantid::DataHandling::ParallelEventLoader::loadMultiProcess (DataObjects::EventWorkspace & ws, const std::string & filename, const std::string & groupName, const std::vector< std::string > & bankNames, const bool eventIDIsSpectrumNumber, const bool precalcEvents) static
Load events from given banks into given EventWorkspace using boost::interprocess.
Definition at line 106 of file ParallelEventLoader.cpp.
References Mantid::DataHandling::getOffsets(), and Mantid::DataHandling::getResultVector().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/ParallelEventLoader.h
Framework/DataHandling/src/ParallelEventLoader.cpp