Mantid: ICat4::ns1__dataCollectionDataset Class Reference
ICat4::ns1__dataCollectionDataset Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__dataCollectionDataset ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__dataCollection * dataCollection
ns1__dataset * dataset
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1520 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__dataCollectionDataset()
ICat4::ns1__dataCollectionDataset::ns1__dataCollectionDataset () inline
Definition at line 1532 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__dataCollectionDataset::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 16889 of file ICat4C.cpp.
References dataCollection, dataset, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::ns1__entityBaseBean::soap_default().
Referenced by ICat4::soap_in_ns1__dataCollectionDataset(), ICat4::soap_new_req_ns1__dataCollectionDataset(), and ICat4::soap_new_set_ns1__dataCollectionDataset().
soap_get()
void * ICat4::ns1__dataCollectionDataset::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17037 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__dataCollectionDataset().
soap_in()
void * ICat4::ns1__dataCollectionDataset::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 16935 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__dataCollectionDataset().
Referenced by ICat4::soap_in_ns1__dataCollectionDataset().
soap_out()
int ICat4::ns1__dataCollectionDataset::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 16907 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__dataCollectionDataset().
Referenced by soap_put().
soap_put()
int ICat4::ns1__dataCollectionDataset::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 17030 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__dataCollectionDataset.
soap_serialize()
void ICat4::ns1__dataCollectionDataset::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 16897 of file ICat4C.cpp.
References dataCollection, dataset, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__dataCollection(), and ICat4::soap_serialize_PointerTons1__dataset().
Referenced by ICat4::soap_serialize_PointerTons1__dataCollectionParameter().
soap_type()
int ICat4::ns1__dataCollectionDataset::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1525 of file ICat4Stub.h.
Member Data Documentation
dataCollection
ns1__dataCollection* ICat4::ns1__dataCollectionDataset::dataCollection
Definition at line 1522 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
dataset
ns1__dataset* ICat4::ns1__dataCollectionDataset::dataset
Definition at line 1523 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp