Mantid: Mantid::MDAlgorithms::InvalidParameter Class Reference
Mantid::MDAlgorithms::InvalidParameter Class Reference
Invalid parameter type.
#include <InvalidParameter.h>
Public Member Functions
Mantid::MDAlgorithms::InvalidParameter * clone () const override
std::string getName () const override
std::string getValue () const
InvalidParameter ()
InvalidParameter (std::string value)
bool isValid () const override
std::string toXMLString () const override
Public Member Functions inherited from Mantid::API::ImplicitFunctionParameter
virtual ImplicitFunctionParameter * clone () const =0
virtual std::string getName () const =0
virtual bool isValid () const =0
virtual std::string toXMLString () const =0
virtual ~ImplicitFunctionParameter ()=default
Static Public Member Functions
static std::string parameterName ()
Private Attributes
std::string m_value
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::ImplicitFunctionParameter
std::string parameterXMLTemplate (const std::string &valueXMLtext) const
Protected Attributes inherited from Mantid::API::ImplicitFunctionParameter
bool m_isValid {false}
Detailed Description
Invalid parameter type.
Modelled from Null object pattern.
Author
Owen Arnold, Tessella plc
Date
01/10/2010
Definition at line 24 of file InvalidParameter.h.
Constructor & Destructor Documentation
InvalidParameter() [1/2]
Mantid::MDAlgorithms::InvalidParameter::InvalidParameter () default
Referenced by clone().
InvalidParameter() [2/2]
Mantid::MDAlgorithms::InvalidParameter::InvalidParameter (std::string value)
Definition at line 14 of file InvalidParameter.cpp.
Member Function Documentation
clone()
InvalidParameter * Mantid::MDAlgorithms::InvalidParameter::clone () const override virtual
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 22 of file InvalidParameter.cpp.
References InvalidParameter(), and m_value.
getName()
std::string Mantid::MDAlgorithms::InvalidParameter::getName () const override virtual
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 16 of file InvalidParameter.cpp.
References parameterName().
getValue()
std::string Mantid::MDAlgorithms::InvalidParameter::getValue () const
Definition at line 18 of file InvalidParameter.cpp.
References m_value.
isValid()
bool Mantid::MDAlgorithms::InvalidParameter::isValid () const override virtual
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 20 of file InvalidParameter.cpp.
parameterName()
static std::string Mantid::MDAlgorithms::InvalidParameter::parameterName () inline static
Definition at line 43 of file InvalidParameter.h.
Referenced by getName().
toXMLString()
std::string Mantid::MDAlgorithms::InvalidParameter::toXMLString () const override virtual
Implements Mantid::API::ImplicitFunctionParameter.
Definition at line 24 of file InvalidParameter.cpp.
Member Data Documentation
m_value
std::string Mantid::MDAlgorithms::InvalidParameter::m_value private
Definition at line 26 of file InvalidParameter.h.
Referenced by clone(), and getValue().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/InvalidParameter.h
Framework/MDAlgorithms/src/InvalidParameter.cpp