Mantid: Mantid::Kernel::MultiFileNameParsing Namespace Reference
Mantid::Kernel::MultiFileNameParsing Namespace Reference
Namespaces
namespace Regexs
Regexs used to match / parse various strings.
Classes
class GenerateFileName
A functor that generates a vector of file names from the given vector of runs, and other state passed to it when constructed.
class Parser
This class takes a string representing multiple files and parses it into a vector of vectors of file names.
class ReverseCaselessCompare
Comparator for set that holds instrument names in Parser.
class RunRangeList
A class that holds a list of ranges of runs.
Functions
MANTID_KERNEL_DLL std::string suggestWorkspaceName (const std::vector< std::string > &fileNames)
Suggests a workspace name, given a vector of file names.
Function Documentation
suggestWorkspaceName()
std::string Mantid::Kernel::MultiFileNameParsing::suggestWorkspaceName (const std::vector< std::string > & fileNames)
Suggests a workspace name, given a vector of file names.
Suggests a workspace name for the given vector of file names (which, because they are in the same vector, we will assume they are to be added.) Example:
(Which we assume will be added.)
Parsing ["INST_4.ext", "INST_5.ext", "INST_6.ext", "INST_8.ext"] will return "INST_4_to_6_and_8" as a suggested workspace name.
Parameters
fileNames :: a vector of file names
Returns
a string containing a suggested workspace name.
Exceptions
std::runtime_error when runString provided is in an incorrect format.
Definition at line 96 of file MultiFileNameParser.cpp.
References Mantid::Kernel::MultiFileNameParsing::RunRangeList::addRun(), Mantid::Kernel::MultiFileNameParsing::Parser::instString(), Mantid::Kernel::MultiFileNameParsing::Parser::parse(), Mantid::Kernel::MultiFileNameParsing::Parser::runs(), Mantid::Kernel::toString(), and Mantid::Kernel::MultiFileNameParsing::Parser::underscoreString().