Mantid: Mantid::MDAlgorithms::IntegrateEllipsoids Class Reference
Mantid::MDAlgorithms::IntegrateEllipsoids Class Reference final
#include <IntegrateEllipsoids.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name for identification.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Summary of algorithm's purpose.
int version () const override
Algorithm's version for identification.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
void exec () override
void init () override
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
Definition at line 15 of file IntegrateEllipsoids.h.
Member Function Documentation
category()
const std::string Mantid::MDAlgorithms::IntegrateEllipsoids::category () const override
Algorithm's category for identification.
See also
Algorithm::category
Definition at line 32 of file IntegrateEllipsoids.cpp.
exec()
void Mantid::MDAlgorithms::IntegrateEllipsoids::exec () override private
Definition at line 62 of file IntegrateEllipsoids.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::MDAlgorithms::getIndexCount(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), and Mantid::MDAlgorithms::getSatelliteIndexCount().
init()
void Mantid::MDAlgorithms::IntegrateEllipsoids::init () override private
Definition at line 35 of file IntegrateEllipsoids.cpp.
References Mantid::MDAlgorithms::IntegrateEllipsoidsV1::initInstance(), and Mantid::MDAlgorithms::IntegrateEllipsoidsV2::initInstance().
name()
const std::string Mantid::MDAlgorithms::IntegrateEllipsoids::name () const override
Algorithm's name for identification.
See also
Algorithm::name
Definition at line 26 of file IntegrateEllipsoids.cpp.
seeAlso()
const std::vector< std::string > Mantid::MDAlgorithms::IntegrateEllipsoids::seeAlso () const inline override
Definition at line 25 of file IntegrateEllipsoids.h.
summary()
const std::string Mantid::MDAlgorithms::IntegrateEllipsoids::summary () const inline override
Summary of algorithm's purpose.
Definition at line 19 of file IntegrateEllipsoids.h.
version()
int Mantid::MDAlgorithms::IntegrateEllipsoids::version () const override
Algorithm's version for identification.
See also
Algorithm::version
Definition at line 29 of file IntegrateEllipsoids.cpp.
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegrateEllipsoids.h
Framework/MDAlgorithms/src/IntegrateEllipsoids.cpp