Mantid: Mantid::Kernel::fft Namespace Reference
Mantid::Kernel::fft Namespace Reference
Classes
struct GSLFree
Functor to free GSL objects in a unique pointer.
Typedefs
using hc_wt_uptr = std::unique_ptr< gsl_fft_halfcomplex_wavetable, GSLFree >
using real_ws_uptr = std::unique_ptr< gsl_fft_real_workspace, GSLFree >
using real_wt_uptr = std::unique_ptr< gsl_fft_real_wavetable, GSLFree >
Functions
hc_wt_uptr make_gsl_hc_wavetable (std::size_t dn)
real_wt_uptr make_gsl_real_wavetable (std::size_t dn)
real_ws_uptr make_gsl_real_workspace (std::size_t dn)
Typedef Documentation
hc_wt_uptr
using Mantid::Kernel::fft::hc_wt_uptr = typedef std::unique_ptr<gsl_fft_halfcomplex_wavetable, GSLFree>
Definition at line 31 of file GSL_Helpers.h.
real_ws_uptr
using Mantid::Kernel::fft::real_ws_uptr = typedef std::unique_ptr<gsl_fft_real_workspace, GSLFree>
Definition at line 30 of file GSL_Helpers.h.
real_wt_uptr
using Mantid::Kernel::fft::real_wt_uptr = typedef std::unique_ptr<gsl_fft_real_wavetable, GSLFree>
Definition at line 29 of file GSL_Helpers.h.
Function Documentation
make_gsl_hc_wavetable()
hc_wt_uptr Mantid::Kernel::fft::make_gsl_hc_wavetable (std::size_t dn) inline
Definition at line 35 of file GSL_Helpers.h.
Referenced by Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Kernel::Smoothing::fft::fftSmoothWithFilter().
make_gsl_real_wavetable()
real_wt_uptr Mantid::Kernel::fft::make_gsl_real_wavetable (std::size_t dn) inline
Definition at line 33 of file GSL_Helpers.h.
Referenced by Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Kernel::Smoothing::fft::fftSmoothWithFilter().
make_gsl_real_workspace()
real_ws_uptr Mantid::Kernel::fft::make_gsl_real_workspace (std::size_t dn) inline
Definition at line 34 of file GSL_Helpers.h.
Referenced by Mantid::Algorithms::RealFFT::RealFFT::exec(), and Mantid::Kernel::Smoothing::fft::fftSmoothWithFilter().