Mantid: MantidQt::API::FilePropertyWidget Class Reference
MantidQt::API::FilePropertyWidget Class Reference
Widget for FileProperty, which has a "Browse" button.
#include <FilePropertyWidget.h>
Public Slots
void browseClicked ()
Slot called when the browse button is clicked.
Public Slots inherited from MantidQt::API::PropertyWidget
void replaceWSButtonClicked ()
Deal with the "replace workspace" button being clicked.
void toggleUseHistory ()
Toggle whether or not to use the previously-entered value.
void updateIconVisibility (const QString &error="")
Update which icons should be shown.
void userEditedProperty ()
To be called when a user edits a property, as opposed to one being set programmatically.
void valueChangedSlot ()
Emits a signal that the value of the property was changed.
Public Member Functions
FilePropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
~FilePropertyWidget () override
Destructor.
Public Member Functions inherited from MantidQt::API::TextPropertyWidget
QWidget * getMainWidget () override
QString getValue () const override
void setValueImpl (const QString &value) override
Set the value into the GUI.
TextPropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
~TextPropertyWidget () override
Destructor.
Public Member Functions inherited from MantidQt::API::PropertyWidget
void addReplaceWSButton ()
Create and show the "Replace WS" button.
QGridLayout * getGridLayout ()
int getGridRow () const
Mantid::Kernel::Property * getProperty ()
const Mantid::Kernel::Property * getProperty () const
bool inGrid () const
PropertyWidget (Mantid::Kernel::Property *prop, QWidget *parent=nullptr, QGridLayout *layout=nullptr, int row=-1)
Constructor.
void setEnabled (bool val)
Sets all widgets contained within to Enabled.
void setError (const QString &error)
Externally set an error string to display in the validator.
void setPrevious_isDynamicDefault (bool flag)
Set the isDynamicDefault flag associated with the previously-entered value.
void setPreviousValue (const QString &previousValue)
Set this widget's previously-entered value.
void setValue (const QString &value)
Set the value of the property given into the GUI state.
void setVisible (bool val) override
Sets all widgets contained within to Visible.
void transferHistoryState (const PropertyWidget *other, const PropertyWidget *upstream=nullptr)
Transfer the history state from another PropertyWidget, possibly additionally depending on the history state of an upstream property.
~PropertyWidget () override
Destructor.
Static Public Member Functions
static QString openFileDialog (Mantid::Kernel::Property *baseProp)
Open the file dialog for a given property.
static QStringList openMultipleFileDialog (Mantid::Kernel::Property *baseProp)
Open a file selection box to select Multiple files to load.
Static Public Member Functions inherited from MantidQt::API::PropertyWidget
static void setFieldPlaceholderText (Mantid::Kernel::Property *prop, QLineEdit *field)
Set the placeholder text of the given field based on the default value of the given property.
Protected Attributes
QPushButton * m_browseButton
"Browse" button
Mantid::API::FileProperty * m_fileProp
Is a file property.
Mantid::API::MultipleFileProperty * m_multipleFileProp
Is a multiple file property.
Protected Attributes inherited from MantidQt::API::TextPropertyWidget
QLabel * m_label
Label (name of the property)
QLineEdit * m_textbox
The text box to edit.
Protected Attributes inherited from MantidQt::API::PropertyWidget
QString m_doc
Documentation string (tooltip)
bool m_entered_isDynamicDefault
Stores the isDynamicDefault flag corresponding to the last value entered by the user.
QString m_enteredValue
Stores the last value entered by the user.
QString m_error
Error message received when trying to set the value.
QGridLayout * m_gridLayout
Grid layout of the dialog to which we are adding widgets.
QMap< Info, ClickableLabel * > m_icons
Allow icon access by Info enum.
bool m_isOutputWsProp
Whether or not the property is an output workspace.
QString m_lastValue
Last modified value.
QWidget * m_parent
Parent widget to add sub-widgets to.
bool m_previous_isDynamicDefault
Stores the isDynamicDefault flag corresponding to the previously entered value.
QString m_previousValue
Stores the previously entered value when this dialog was last open.
Mantid::Kernel::Property * m_prop
Property being looked at. This is NOT owned by the widget.
QPushButton * m_replaceWSButton
Button to "replace input workspace".
int m_row
If using the GridLayout, this is the row where the widget was inserted.
bool m_useHistory
History on/off flag.
QVector< QWidget * > m_widgets
All contained widgets.
Additional Inherited Members
Public Types inherited from MantidQt::API::PropertyWidget
enum Info { INVALID , REPLACE , RESTORE }
Signals inherited from MantidQt::API::PropertyWidget
void replaceWorkspaceName (const QString &propName)
Signal is emitted whenever someone clicks the replace WS button.
void userChangedProperty ()
void valueChanged (const QString &propName)
Signal is emitted whenever the value (as entered by the user) in the GUI changes.
Static Protected Member Functions inherited from MantidQt::API::PropertyWidget
static void setLabelFont (Mantid::Kernel::Property *prop, QWidget *label)
Set the font of the given label based on the optional/required status of the given property.
Detailed Description
Widget for FileProperty, which has a "Browse" button.
Date
2012-02-17
Definition at line 24 of file FilePropertyWidget.h.
Constructor & Destructor Documentation
FilePropertyWidget()
MantidQt::API::FilePropertyWidget::FilePropertyWidget (Mantid::Kernel::Property * prop, QWidget * parent = nullptr, QGridLayout * layout = nullptr, int row = -1)
Constructor.
Definition at line 20 of file FilePropertyWidget.cpp.
References browseClicked(), m_browseButton, m_fileProp, MantidQt::API::PropertyWidget::m_gridLayout, m_multipleFileProp, MantidQt::API::PropertyWidget::m_parent, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::PropertyWidget::m_row, MantidQt::API::PropertyWidget::m_widgets, MantidQt::API::PropertyWidget::setValue(), and Mantid::Kernel::Property::value().
~FilePropertyWidget()
MantidQt::API::FilePropertyWidget::~FilePropertyWidget () override default
Destructor.
Member Function Documentation
browseClicked
void MantidQt::API::FilePropertyWidget::browseClicked () slot
Slot called when the browse button is clicked.
Definition at line 44 of file FilePropertyWidget.cpp.
References m_fileProp, m_multipleFileProp, MantidQt::API::PropertyWidget::m_prop, MantidQt::API::TextPropertyWidget::m_textbox, openFileDialog(), openMultipleFileDialog(), and MantidQt::API::PropertyWidget::userEditedProperty().
Referenced by FilePropertyWidget().
openFileDialog()
QString MantidQt::API::FilePropertyWidget::openFileDialog (Mantid::Kernel::Property * baseProp) static
Open the file dialog for a given property.
Parameters
baseProp :: Property pointer
Returns
full path to the file(s) to load/save
Definition at line 91 of file FilePropertyWidget.cpp.
References MantidQt::API::FileDialogHandler::getCaption(), MantidQt::API::FileDialogHandler::getFilter(), and MantidQt::API::FileDialogHandler::getSaveFileName().
Referenced by browseClicked(), and MantidQt::API::AlgorithmDialog::openFileDialog().
openMultipleFileDialog()
QStringList MantidQt::API::FilePropertyWidget::openMultipleFileDialog (Mantid::Kernel::Property * baseProp) static
Open a file selection box to select Multiple files to load.
Parameters
baseProp,: pointer to an instance of MultipleFileProperty used to set up the valid extensions for opening multiple file dialog.
Returns
list of full paths to files
Definition at line 131 of file FilePropertyWidget.cpp.
References MantidQt::API::FileDialogHandler::getFilter().
Referenced by browseClicked().
Member Data Documentation
m_browseButton
QPushButton* MantidQt::API::FilePropertyWidget::m_browseButton protected
"Browse" button
Definition at line 40 of file FilePropertyWidget.h.
Referenced by FilePropertyWidget().
m_fileProp
Mantid::API::FileProperty* MantidQt::API::FilePropertyWidget::m_fileProp protected
Is a file property.
Definition at line 43 of file FilePropertyWidget.h.
Referenced by browseClicked(), and FilePropertyWidget().
m_multipleFileProp
Mantid::API::MultipleFileProperty* MantidQt::API::FilePropertyWidget::m_multipleFileProp protected
Is a multiple file property.
Definition at line 46 of file FilePropertyWidget.h.
Referenced by browseClicked(), and FilePropertyWidget().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FilePropertyWidget.h
qt/widgets/common/src/FilePropertyWidget.cpp