Mantid: Mantid::CurveFitting::Functions::CrystalFieldFunction Class Reference
Mantid::CurveFitting::Functions::CrystalFieldFunction Class Reference
Calculates crystal field spectra.
#include <CrystalFieldFunction.h>
Public Member Functions
const std::string category () const override
The categories the Fit function belong to.
std::vector< API::IFunction_sptr > createEquivalentFunctions () const override
Split this function (if needed) into a list of independent functions.
CrystalFieldFunction ()
Constructor.
void function (const API::FunctionDomain &domain, API::FunctionValues &values) const override
Evaluate the function.
API::IConstraint * getConstraint (size_t i) const override
Get the i-th constraint.
double getError (const std::string &name) const override
Get the fitting error for a parameter by name.
double getError (size_t i) const override
Get the fitting error for a parameter.
size_t getNumberDomains () const override
Get number of domains required by this function.
double getParameter (const std::string &name) const override
Get parameter by name.
double getParameter (size_t i) const override
Get i-th parameter.
size_t getParameterIndex (const API::ParameterReference &ref) const override
Return parameter index from a parameter reference.
API::ParameterTie * getTie (size_t i) const override
Get the tie for i-th parameter.
bool hasParameter (const std::string &name) const override
Check if function has a parameter with this name.
bool ignoreTie (const API::ParameterTie &tie) const override
Checks if whether tie should be ignored.
bool isExplicitlySet (size_t i) const override
Checks if a parameter has been set explicitly.
std::string name () const override
Returns the function's name.
size_t nParams () const override
Total number of parameters.
std::string parameterDescription (size_t i) const override
Returns the description of parameter i.
size_t parameterIndex (const std::string &name) const override
Returns the index of parameter name.
std::string parameterName (size_t i) const override
Returns the name of parameter i.
void setError (const std::string &name, double err) override
Set the fitting error for a parameter by name.
void setError (size_t i, double err) override
Set the fitting error for a parameter.
void setParameter (const std::string &name, const double &value, bool explicitlySet=true) override
Set parameter by name.
void setParameter (size_t, const double &value, bool explicitlySet=true) override
Set i-th parameter.
void setParameterDescription (const std::string &name, const std::string &description) override
Set description of parameter by name.
void setParameterDescription (size_t, const std::string &description) override
Set i-th parameter description.
void setUpForFit () override
Set up the function for a fit.
Attributes
size_t nAttributes () const override
Returns the number of attributes associated with the function.
std::vector< std::string > getAttributeNames () const override
Returns a list of attribute names.
Attribute getAttribute (const std::string &name) const override
Return a value of attribute attName.
void setAttribute (const std::string &name, const Attribute &) override
Set a value to attribute attName.
bool hasAttribute (const std::string &name) const override
Check if attribute attName exists.
Public Member Functions inherited from Mantid::API::IFunction
std::string asString () const
Writes itself into a string.
bool cancellationRequestReceived () const
Returns true if a progress reporter is set & evalaution has been requested to stop.
virtual const std::vector< std::string > categories () const
Function to return all of the categories that contain this algorithm.
virtual const std::string category () const
The categories the Fit function belong to.
virtual const std::string categorySeparator () const
Function to return the sperator token for the category string.
virtual std::shared_ptr< IFunction > clone () const
Virtual copy constructor.
virtual int64_t estimateNoProgressCalls () const
Returns an estimate of the number of progress reports a single evaluation of the function will have.
virtual void function (const FunctionDomain &domain, FunctionValues &values) const =0
Evaluates the function for all arguments in the domain.
virtual void functionDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Derivatives of function with respect to active parameters.
IFunction ()
Constructor.
IFunction (const IFunction &)=delete
No copying.
virtual void initialize ()
Iinialize the function.
virtual void iterationFinished ()
Called at the end of an iteration.
virtual void iterationStarting ()
Called at the start of each iteration.
virtual std::string name () const =0
Returns the function's name.
IFunction & operator= (const IFunction &)=delete
No copying.
virtual void registerFunctionUsage (bool internal)
Registers the usage of the algorithm with the UsageService.
void reportProgress (const std::string &msg="") const
Reports progress with an optional message.
virtual void setMatrixWorkspace (std::shared_ptr< const API::MatrixWorkspace > workspace, size_t wi, double startX, double endX)
Set matrix workspace.
void setProgressReporter (std::shared_ptr< Kernel::ProgressBase > reporter)
Attach a progress reporter.
virtual void setWorkspace (std::shared_ptr< const Workspace > ws)
Set the workspace.
virtual ~IFunction ()
Virtual destructor.
bool isFixed (size_t i) const
Check if a parameter i is fixed.
bool isFixedByDefault (size_t i) const
Check if a parameter i is fixed by default (not by user).
void fix (size_t i, bool isDefault=false)
Removes a parameter i from the list of active.
void unfix (size_t i)
Restores a declared parameter i to the active status.
void fixParameter (const std::string &name, bool isDefault=false)
Fix a parameter.
void unfixParameter (const std::string &name)
Free a parameter.
void fixAll (bool isDefault=false)
Fix all parameters.
void unfixAll ()
Free all parameters.
void unfixAllDefault ()
Free all parameters fixed by default.
void fixAllActive (bool isDefault=false)
Fix all active parameters.
std::vector< std::string > getParameterNames () const
Return a vector with all parameter names.
virtual double activeParameter (size_t i) const
Value of i-th active parameter.
virtual void setActiveParameter (size_t i, double value)
Set new value of i-th active parameter.
virtual std::string nameOfActive (size_t i) const
Returns the name of active parameter i.
virtual std::string descriptionOfActive (size_t i) const
Returns the name of active parameter i.
bool isActive (size_t i) const
Check if an active parameter i is actually active.
virtual void tie (const std::string &parName, const std::string &expr, bool isDefault=false)
Tie a parameter to other parameters (or a constant)
virtual void addTies (const std::string &ties, bool isDefault=false)
Add several ties.
virtual void applyTies ()
Apply the ties.
virtual void removeTie (const std::string &parName)
Removes the tie off a parameter.
virtual void clearTies ()
Remove all ties.
virtual bool removeTie (size_t i)
Removes i-th parameter's tie.
void sortTies ()
Put all ties in order in which they will be applied correctly.
std::string writeTies () const
Write a parameter tie to a string.
virtual void addConstraints (const std::string &str, bool isDefault=false)
Add a list of conatraints from a string.
virtual void addConstraint (std::unique_ptr< IConstraint > ic)
Add a constraint to function.
virtual void removeConstraint (const std::string &parName)
Remove a constraint.
virtual void setConstraintPenaltyFactor (const std::string &parName, const double &c)
Set a constraint penalty.
std::string writeConstraints () const
Write a parameter constraint to a string.
virtual void clearConstraints ()
Remove all constraints.
virtual std::string attributeName (size_t index) const
Get name of ith attribute.
template<typename T >
void setAttributeValue (const std::string &attName, const T &value)
Set an attribute value.
void setAttributeValue (const std::string &attName, const char *value)
Overload for const char* values.
void setAttributeValue (const std::string &attName, const std::string &value)
Set string attribute by value.
virtual std::shared_ptr< IFunction > getFunction (size_t i) const
Returns the pointer to i-th child function.
virtual std::size_t nFunctions () const
Number of child functions.
virtual size_t getValuesSize (const FunctionDomain &domain) const
Get number of values for a given domain.
void calNumericalDeriv (const FunctionDomain &domain, Jacobian &jacobian)
Calculate numerical derivatives.
double calculateStepSize (const double parameterValue) const
Calculate step size for the given parameter value.
void setCovarianceMatrix (const std::shared_ptr< Kernel::Matrix< double > > &covar)
Set the covariance matrix.
std::shared_ptr< const Kernel::Matrix< double > > getCovarianceMatrix () const
Get the covariance matrix.
void setReducedChiSquared (double chi2)
Set the reduced chi^2.
double getReducedChiSquared () const
Get the reduced chi^2.
void setParallel (bool on)
Set the parallel hint.
bool isParallel () const
Get the parallel hint.
void setHandler (std::unique_ptr< FunctionHandler > handler)
Set a function handler.
FunctionHandler * getHandler () const
Return the handler.
virtual void setStepSizeMethod (const StepSizeMethod method)
Sets the StepSizeMethod to use when calculation the step size.
Checks
CrystalFieldControl m_control
Function that creates the source function.
API::IFunction_sptr m_source
Function that calculates parameters of the target function.
API::CompositeFunction_sptr m_target
Function that actually calculates the output.
size_t m_nControlParams
Cached number of parameters in m_control.
size_t m_nControlSourceParams
Cached number of parameters in m_control and m_source.
bool m_dirtyTarget
Flag indicating that updateTargetFunction() is required.
std::unordered_map< std::string, size_t > m_mapNames2Indices
Map parameter names to indices.
std::vector< std::string > m_mapIndices2Names
Map parameter indices to names.
std::vector< std::string > m_attributeNames
Attribute names.
std::unordered_map< std::string, API::IFunction_sptr > m_mapPrefixes2PhysProps
Map parameter/attribute prefixes to pointers to phys prop functions.
std::vector< double > m_parameterResetCache
Temporary cache for parameter values during source function resetting.
std::vector< bool > m_fixResetCache
bool isMultiSite () const
Check if the function is set up for a multi-site calculations.
bool isMultiSpectrum () const
Check if the function is set up for a multi-spectrum calculations (Multiple temperatures defined)
bool hasBackground () const
Check if the spectra have a background.
bool hasPeaks () const
Check if there are peaks (there is at least one spectrum).
bool hasPhysProperties () const
Check if there are any phys. properties.
void checkSourceFunction () const
Build source function if necessary.
void buildTargetFunction () const
Build target function.
size_t nSpectra () const
Get number of the number of spectra (excluding phys prop data).
void declareParameter (const std::string &name, double initValue=0, const std::string &description="") override
Declare a new parameter.
void setParameterStatus (size_t i, ParameterStatus status) override
Change status of parameter.
ParameterStatus getParameterStatus (size_t i) const override
Get status of parameter.
void buildSourceFunction () const
Build the source function.
void updateTargetFunction () const
Update the target function.
void buildSingleSite () const
Build the target function in a single site case.
void buildMultiSite () const
Build the target function in a multi site case.
void buildSingleSiteSingleSpectrum () const
Build the target function in a single site - single spectrum case.
void buildSingleSiteMultiSpectrum () const
Build the target function in a single site - multi spectrum case.
void buildMultiSiteSingleSpectrum () const
Build the target function in a multi site - single spectrum case.
void buildMultiSiteMultiSpectrum () const
Build the target function in a multi site - multi spectrum case.
void updateSingleSite () const
Update the target function in a single site case.
void updateMultiSite () const
Update the target function in a multi site case.
void updateSingleSiteSingleSpectrum () const
Update the target function in a single site - single spectrum case.
void updateSingleSiteMultiSpectrum () const
Update the target function in a single site - multi spectrum case.
void updateMultiSiteSingleSpectrum () const
Update the target function in a multi site - single spectrum case.
void updateMultiSiteMultiSpectrum () const
Update the target function in a multi site - multi spectrum case.
API::IFunction_sptr buildSpectrum (int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf, double temperature, double fwhm, size_t i, bool addBackground, double intensityScaling) const
Build a function for a single spectrum.
void updateSpectrum (API::IFunction &spectrum, int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf, double temperature, double fwhm, size_t iSpec, size_t iFirst, double intensityScaling) const
Update a function for a single spectrum.
void calcExcitations (int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf, double temperature, API::FunctionValues &values, double intensityScaling) const
Calculate excitations at given temperature.
API::IFunction_sptr buildPhysprop (int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf, const ComplexFortranMatrix &ham, const std::string &propName) const
Build a physical property function.
void updatePhysprop (int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf, const ComplexFortranMatrix &ham, API::IFunction &fun) const
Update a physical property function.
void setSource (API::IFunction_sptr source) const
Set the source function.
void checkTargetFunction () const
Update target function if necessary.
API::CompositeFunction & compositeSource () const
Get a reference to the source function if it's composite.
std::pair< API::IFunction *, std::string > getAttributeReference (const std::string &attName) const
Get a reference to an attribute.
void buildAttributeNames () const
Build and cache the attribute names.
void makeMaps () const
Make maps between parameter names and indices.
void makeMapsSingleSiteSingleSpectrum () const
Parameter-index map for single-site single-spectrum.
void makeMapsSingleSiteMultiSpectrum () const
Parameter-index map for single-site multi-spectrum.
void makeMapsMultiSiteSingleSpectrum () const
Parameter-index map for multi-site single-spectrum.
void makeMapsMultiSiteMultiSpectrum () const
Parameter-index map for multi-site multi-spectrum.
size_t makeMapsForFunction (const IFunction &fun, size_t iFirst, const std::string &prefix) const
Make parameter names from names of a function and map them to indices.
void cacheSourceParameters () const
Temporary cache parameter values of the source function if it's initialised.
Additional Inherited Members
Public Types inherited from Mantid::API::IFunction
enum ParameterStatus { Active , Fixed , FixedByDefault , Tied }
Describe parameter status in relation to fitting: Active: Fit varies such parameter directly.
enum class StepSizeMethod { DEFAULT , SQRT_EPSILON }
Describes the method in which the step size will be calculated: DEFAULT: Uses the traditional Mantid method of calculating the step size.
Protected Member Functions inherited from Mantid::API::IFunction
virtual void init ()
Function initialization. Declare function parameters in this method.
double convertValue (double value, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert a value from one unit (inUnit) to unit defined in workspace (ws)
void convertValue (std::vector< double > &values, Kernel::Unit_sptr &outUnit, const std::shared_ptr< const MatrixWorkspace > &ws, size_t wsIndex) const
Convert values from unit defined in workspace (ws) to outUnit.
virtual void declareAttributes ()
Override to declare function attributes.
virtual void declareParameters ()
Override to declare function parameters.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue)
Declare a single attribute.
void declareAttribute (const std::string &name, const API::IFunction::Attribute &defaultValue, const Kernel::IValidator &validator)
Declare a single attribute with validator.
void checkAttributeName (const std::string &name)
Check Attribute to declare does not already exist.
void storeAttributeValue (const std::string &name, const API::IFunction::Attribute &value)
Store an attribute's value.
void storeReadOnlyAttribute (const std::string &name, const API::IFunction::Attribute &value) const
A read-only ("mutable") attribute can be stored in a const method.
virtual void addTie (std::unique_ptr< ParameterTie > tie)
Add a new tie. Derived classes must provide storage for ties.
bool hasOrderedTies () const
void applyOrderedTies ()
virtual std::string writeToString (const std::string &parentLocalAttributesStr="") const
Writes itself into a string.
Protected Attributes inherited from Mantid::API::IFunction
bool m_isParallel
Flag to hint that the function is being used in parallel computations.
std::unique_ptr< FunctionHandler > m_handler
Pointer to a function handler.
std::shared_ptr< Kernel::ProgressBase > m_progReporter
Pointer to the progress handler.
Detailed Description
Calculates crystal field spectra.
Definition at line 22 of file CrystalFieldFunction.h.
Constructor & Destructor Documentation
CrystalFieldFunction()
Mantid::CurveFitting::Functions::CrystalFieldFunction::CrystalFieldFunction ()
Constructor.
Definition at line 99 of file CrystalFieldFunction.cpp.
Member Function Documentation
buildAttributeNames()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildAttributeNames () const private
Build and cache the attribute names.
Definition at line 399 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::attributeName(), checkSourceFunction(), checkTargetFunction(), Mantid::API::IFunction::getAttributeNames(), Mantid::API::CompositeFunction::getFunction(), m_attributeNames, m_control, m_target, name(), Mantid::API::IFunction::nAttributes(), Mantid::API::CompositeFunction::nFunctions(), nSpectra(), and std::to_string().
Referenced by getAttributeNames(), and nAttributes().
buildMultiSite()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSite () const private
Build the target function in a multi site case.
Definition at line 690 of file CrystalFieldFunction.cpp.
References buildMultiSiteMultiSpectrum(), buildMultiSiteSingleSpectrum(), and isMultiSpectrum().
Referenced by buildTargetFunction().
buildMultiSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteMultiSpectrum () const private
Build the target function in a multi site - multi spectrum case.
Definition at line 814 of file CrystalFieldFunction.cpp.
References buildPhysprop(), buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::calculateEigenSystem(), compositeSource(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getFunction(), m_control, m_mapPrefixes2PhysProps, m_target, nSpectra(), Mantid::CurveFitting::Functions::CrystalFieldControl::physProps(), Mantid::CurveFitting::Functions::CrystalFieldControl::temperatures(), and std::to_string().
Referenced by buildMultiSite().
buildMultiSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildMultiSiteSingleSpectrum () const private
Build the target function in a multi site - single spectrum case.
Definition at line 771 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asInt(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asUnquotedString(), Mantid::API::IFunction::Attribute::asVector(), Mantid::CurveFitting::Functions::CrystalFieldUtils::buildSpectrumFunction(), Mantid::API::IFunction::CompositeFunction, compositeSource(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getAttribute(), getAttribute(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_control, m_target, and Mantid::API::FunctionValues::size().
Referenced by buildMultiSite().
buildPhysprop()
API::IFunction_sptr Mantid::CurveFitting::Functions::CrystalFieldFunction::buildPhysprop (int nre, const DoubleFortranVector & energies, const ComplexFortranMatrix & waveFunctions, const ComplexFortranMatrix & hamiltonian, const std::string & propName) const private
Build a physical property function.
Parameters
nre :: An id of the ion.
energies :: A vector with energies.
waveFunctions :: A matrix with wave functions.
hamiltonian :: A matrix with the hamiltonian.
propName :: the name of the physical property.
Definition at line 945 of file CrystalFieldFunction.cpp.
Referenced by buildMultiSiteMultiSpectrum(), and buildSingleSiteMultiSpectrum().
buildSingleSite()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSite () const private
Build the target function in a single site case.
Definition at line 681 of file CrystalFieldFunction.cpp.
References buildSingleSiteMultiSpectrum(), buildSingleSiteSingleSpectrum(), and isMultiSpectrum().
Referenced by buildTargetFunction().
buildSingleSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteMultiSpectrum () const private
Build the target function in a single site - multi spectrum case.
Definition at line 736 of file CrystalFieldFunction.cpp.
References buildPhysprop(), buildSpectrum(), Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::calculateEigenSystem(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getFunction(), m_control, m_mapPrefixes2PhysProps, m_target, nSpectra(), Mantid::CurveFitting::Functions::CrystalFieldControl::physProps(), and Mantid::CurveFitting::Functions::CrystalFieldControl::temperatures().
Referenced by buildSingleSite().
buildSingleSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSingleSiteSingleSpectrum () const private
Build the target function in a single site - single spectrum case.
Definition at line 699 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asInt(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asUnquotedString(), Mantid::API::IFunction::Attribute::asVector(), Mantid::CurveFitting::Functions::CrystalFieldUtils::buildSpectrumFunction(), Mantid::API::IFunction::CompositeFunction, Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getAttribute(), getAttribute(), Mantid::Kernel::SingletonHolder< T >::Instance(), m_control, m_source, m_target, and Mantid::API::FunctionValues::size().
Referenced by buildSingleSite().
buildSourceFunction()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSourceFunction () const protected
Build the source function.
Definition at line 642 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::buildSource(), m_control, m_fixResetCache, m_nControlParams, m_nControlSourceParams, m_parameterResetCache, m_source, Mantid::API::CompositeFunction::nParams(), and setSource().
Referenced by checkSourceFunction().
buildSpectrum()
API::IFunction_sptr Mantid::CurveFitting::Functions::CrystalFieldFunction::buildSpectrum (int nre, const DoubleFortranVector & energies, const ComplexFortranMatrix & waveFunctions, double temperature, double fwhm, size_t iSpec, bool addBackground, double intensityScaling) const private
Build a function for a single spectrum.
Parameters
nre :: An id of the ion.
energies :: A vector with energies.
waveFunctions :: A matrix with wave functions.
temperature :: A temperature of the spectrum.
fwhm :: A full width at half maximum to set to each peak.
iSpec :: An index of the created spectrum in m_target composite function.
addBackground :: An option to add a background to the spectrum.
intensityScaling :: A scaling factor for the peak intensities.
Definition at line 910 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asInt(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asUnquotedString(), Mantid::CurveFitting::Functions::CrystalFieldUtils::buildSpectrumFunction(), calcExcitations(), Mantid::API::IFunction::CompositeFunction, getAttribute(), Mantid::API::CompositeFunction::getFunction(), Mantid::Kernel::SingletonHolder< T >::Instance(), and m_control.
Referenced by buildMultiSiteMultiSpectrum(), and buildSingleSiteMultiSpectrum().
buildTargetFunction()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::buildTargetFunction () const
Build target function.
Uses source to calculate peak centres and intensities then populates m_spectrum with peaks of type given in PeakShape attribute.
Definition at line 669 of file CrystalFieldFunction.cpp.
References buildMultiSite(), buildSingleSite(), checkSourceFunction(), isMultiSite(), m_attributeNames, and m_dirtyTarget.
Referenced by getNumberDomains(), and updateTargetFunction().
cacheSourceParameters()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::cacheSourceParameters () const private
Temporary cache parameter values of the source function if it's initialised.
Definition at line 1353 of file CrystalFieldFunction.cpp.
References m_fixResetCache, m_parameterResetCache, and m_source.
Referenced by setAttribute().
calcExcitations()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::calcExcitations (int nre, const DoubleFortranVector & energies, const ComplexFortranMatrix & waveFunctions, double temperature, API::FunctionValues & values, double intensityScaling) const private
Calculate excitations at given temperature.
Parameters
nre :: An id of the ion.
energies :: A vector with energies.
waveFunctions :: A matrix with wave functions.
temperature :: A temperature of the spectrum.
values :: An object to receive computed excitations.
intensityScaling :: A scaling factor for the intensities.
Definition at line 879 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asDouble(), Mantid::CurveFitting::Functions::calculateExcitations(), Mantid::CurveFitting::Functions::calculateIntensities(), Mantid::API::FunctionValues::expand(), Mantid::CurveFitting::EigenVector::get(), getAttribute(), Mantid::API::FunctionValues::setCalculated(), and Mantid::CurveFitting::EigenVector::size().
Referenced by buildSpectrum(), and updateSpectrum().
category()
const std::string Mantid::CurveFitting::Functions::CrystalFieldFunction::category () const inline override virtual
The categories the Fit function belong to.
Categories must be listed as a semi colon separated list. For example: "General, Muon\\Custom" which adds a function to the category "General" and the sub-category "Muon\\Custom"
Reimplemented from Mantid::API::IFunction.
Definition at line 26 of file CrystalFieldFunction.h.
checkSourceFunction()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::checkSourceFunction () const
Build source function if necessary.
Definition at line 635 of file CrystalFieldFunction.cpp.
References buildSourceFunction(), and m_source.
Referenced by buildAttributeNames(), buildTargetFunction(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), nParams(), parameterDescription(), parameterIndex(), parameterName(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), and setUpForFit().
checkTargetFunction()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::checkTargetFunction () const private
Update target function if necessary.
Update spectrum function if necessary.
Definition at line 658 of file CrystalFieldFunction.cpp.
References m_dirtyTarget, m_target, and updateTargetFunction().
Referenced by buildAttributeNames(), createEquivalentFunctions(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), nParams(), parameterDescription(), parameterIndex(), parameterName(), setError(), setParameter(), setParameterDescription(), and setParameterStatus().
compositeSource()
API::CompositeFunction & Mantid::CurveFitting::Functions::CrystalFieldFunction::compositeSource () const private
Get a reference to the source function if it's composite.
Definition at line 626 of file CrystalFieldFunction.cpp.
References m_source.
Referenced by buildMultiSiteMultiSpectrum(), buildMultiSiteSingleSpectrum(), makeMapsMultiSiteMultiSpectrum(), makeMapsMultiSiteSingleSpectrum(), updateMultiSiteMultiSpectrum(), and updateMultiSiteSingleSpectrum().
createEquivalentFunctions()
std::vector< IFunction_sptr > Mantid::CurveFitting::Functions::CrystalFieldFunction::createEquivalentFunctions () const override virtual
Split this function (if needed) into a list of independent functions.
The number of functions must be the number of domains this function is working on (== getNumberDomains()). The result of evaluation of the created functions on their domains must be the same as if this function was evaluated on the composition of those domains.
Reimplemented from Mantid::API::IFunction.
Definition at line 126 of file CrystalFieldFunction.cpp.
References Mantid::API::CompositeFunction::checkFunction(), checkTargetFunction(), and Mantid::API::CompositeFunction::getFunction().
declareParameter()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::declareParameter (const std::string & name, double initValue = 0, const std::string & description = "") override protected virtual
Declare a new parameter.
Implements Mantid::API::IFunction.
Definition at line 393 of file CrystalFieldFunction.cpp.
function()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::function (const API::FunctionDomain & domain, API::FunctionValues & values) const override virtual
Evaluate the function.
Implements Mantid::API::IFunction.
Definition at line 103 of file CrystalFieldFunction.cpp.
References m_target, and updateTargetFunction().
Referenced by updatePhysprop().
getAttribute()
IFunction::Attribute Mantid::CurveFitting::Functions::CrystalFieldFunction::getAttribute (const std::string & attName) const override virtual
Return a value of attribute attName.
Parameters
attName :: Name of an attribute.
Reimplemented from Mantid::API::IFunction.
Definition at line 487 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::getAttribute(), and getAttributeReference().
Referenced by buildMultiSiteSingleSpectrum(), buildSingleSiteSingleSpectrum(), buildSpectrum(), calcExcitations(), hasBackground(), updateMultiSiteSingleSpectrum(), and updateSpectrum().
getAttributeNames()
std::vector< std::string > Mantid::CurveFitting::Functions::CrystalFieldFunction::getAttributeNames () const override virtual
Returns a list of attribute names.
Reimplemented from Mantid::API::IFunction.
Definition at line 480 of file CrystalFieldFunction.cpp.
References buildAttributeNames(), and m_attributeNames.
getAttributeReference()
std::pair< API::IFunction *, std::string > Mantid::CurveFitting::Functions::CrystalFieldFunction::getAttributeReference (const std::string & attName) const private
Get a reference to an attribute.
Parameters
attName :: A name of an attribute. It can be a code rather than an actual name. This method interprets the code and finds the function and attribute it refers to.
Returns
:: A pair (IFunction, attribute_name) where attribute_name is a name that the IFunction has.
Definition at line 527 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::buildControls(), Mantid::API::CompositeFunction::getFunction(), m_control, m_mapPrefixes2PhysProps, name(), and Mantid::API::CompositeFunction::nFunctions().
Referenced by getAttribute(), hasAttribute(), and setAttribute().
getConstraint()
IConstraint * Mantid::CurveFitting::Functions::CrystalFieldFunction::getConstraint (size_t i) const override virtual
Get the i-th constraint.
Reimplemented from Mantid::API::IFunction.
Definition at line 587 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::IFunction::getConstraint(), Mantid::API::CompositeFunction::getConstraint(), m_control, m_nControlParams, m_nControlSourceParams, m_source, and m_target.
getError() [1/2]
double Mantid::CurveFitting::Functions::CrystalFieldFunction::getError (const std::string & name) const override virtual
Get the fitting error for a parameter by name.
Get the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 301 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::CompositeFunction::getError(), index, m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, name(), and parameterIndex().
getError() [2/2]
double Mantid::CurveFitting::Functions::CrystalFieldFunction::getError (size_t i) const override virtual
Get the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 288 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::CompositeFunction::getError(), m_control, m_nControlParams, m_nControlSourceParams, m_source, and m_target.
getNumberDomains()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::getNumberDomains () const override virtual
Get number of domains required by this function.
If it returns a number greater than 1 then the domain passed to function(domain, values) method must have a CompositeDomain type with the same number of parts.
Reimplemented from Mantid::API::IFunction.
Definition at line 115 of file CrystalFieldFunction.cpp.
References buildTargetFunction(), and m_target.
getParameter() [1/2]
double Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameter (const std::string & name) const override virtual
Get parameter by name.
Implements Mantid::API::IFunction.
Definition at line 213 of file CrystalFieldFunction.cpp.
References getParameter(), index, name(), and parameterIndex().
getParameter() [2/2]
double Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameter (size_t i) const override virtual
Get i-th parameter.
Implements Mantid::API::IFunction.
Definition at line 170 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::CompositeFunction::getParameter(), m_control, m_nControlParams, m_nControlSourceParams, m_source, and m_target.
Referenced by getParameter().
getParameterIndex()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameterIndex (const API::ParameterReference & ref) const override virtual
Return parameter index from a parameter reference.
Implements Mantid::API::IFunction.
Definition at line 368 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::ParameterReference::getLocalFunction(), Mantid::API::ParameterReference::getLocalIndex(), Mantid::API::CompositeFunction::getParameterIndex(), index, m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and nParams().
getParameterStatus()
IFunction::ParameterStatus Mantid::CurveFitting::Functions::CrystalFieldFunction::getParameterStatus (size_t i) const override protected virtual
Get status of parameter.
Implements Mantid::API::IFunction.
Definition at line 355 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::CompositeFunction::getParameterStatus(), m_control, m_nControlParams, m_nControlSourceParams, m_source, and m_target.
getTie()
ParameterTie * Mantid::CurveFitting::Functions::CrystalFieldFunction::getTie (size_t i) const override virtual
Get the tie for i-th parameter.
Reimplemented from Mantid::API::IFunction.
Definition at line 562 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::IFunction::getTie(), Mantid::API::CompositeFunction::getTie(), m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and Mantid::API::IFunction::tie().
hasAttribute()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::hasAttribute (const std::string & name) const override virtual
Check if attribute attName exists.
Reimplemented from Mantid::API::IFunction.
Definition at line 513 of file CrystalFieldFunction.cpp.
References getAttributeReference().
Referenced by hasBackground().
hasBackground()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::hasBackground () const
Check if the spectra have a background.
Definition at line 612 of file CrystalFieldFunction.cpp.
References getAttribute(), hasAttribute(), and Mantid::API::IFunction::Attribute::isEmpty().
Referenced by makeMapsMultiSiteMultiSpectrum(), makeMapsMultiSiteSingleSpectrum(), makeMapsSingleSiteMultiSpectrum(), makeMapsSingleSiteSingleSpectrum(), updateMultiSiteMultiSpectrum(), updateMultiSiteSingleSpectrum(), updateSingleSiteMultiSpectrum(), and updateSingleSiteSingleSpectrum().
hasParameter()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::hasParameter (const std::string & name) const override virtual
Check if function has a parameter with this name.
Implements Mantid::API::IFunction.
Definition at line 183 of file CrystalFieldFunction.cpp.
References name(), and parameterIndex().
hasPeaks()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::hasPeaks () const
Check if there are peaks (there is at least one spectrum).
Definition at line 620 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::hasPeaks(), and m_control.
hasPhysProperties()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::hasPhysProperties () const
Check if there are any phys. properties.
Definition at line 623 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::hasPhysProperties(), and m_control.
ignoreTie()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::ignoreTie (const API::ParameterTie & tie) const override virtual
Checks if whether tie should be ignored.
Reimplemented from Mantid::API::IFunction.
Definition at line 580 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::tie().
isExplicitlySet()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::isExplicitlySet (size_t i) const override virtual
Checks if a parameter has been set explicitly.
Implements Mantid::API::IFunction.
Definition at line 275 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), Mantid::API::CompositeFunction::isExplicitlySet(), m_control, m_nControlParams, m_nControlSourceParams, m_source, and m_target.
isMultiSite()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::isMultiSite () const
Check if the function is set up for a multi-site calculations.
(Multiple ions defined)
Definition at line 605 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::isMultiSite(), and m_control.
Referenced by buildTargetFunction(), makeMaps(), and updateTargetFunction().
isMultiSpectrum()
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::isMultiSpectrum () const
Check if the function is set up for a multi-spectrum calculations (Multiple temperatures defined)
Definition at line 609 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldControl::isMultiSpectrum(), and m_control.
Referenced by buildMultiSite(), buildSingleSite(), makeMaps(), updateMultiSite(), and updateSingleSite().
makeMaps()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMaps () const private
Make maps between parameter names and indices.
Definition at line 1170 of file CrystalFieldFunction.cpp.
References isMultiSite(), isMultiSpectrum(), m_mapIndices2Names, m_mapNames2Indices, makeMapsMultiSiteMultiSpectrum(), makeMapsMultiSiteSingleSpectrum(), makeMapsSingleSiteMultiSpectrum(), makeMapsSingleSiteSingleSpectrum(), and nParams().
Referenced by parameterIndex(), and parameterName().
makeMapsForFunction()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsForFunction (const IFunction & fun, size_t iFirst, const std::string & prefix) const private
Make parameter names from names of a function and map them to indices.
Parameters
fun :: A function to get parameter names from.
iFirst :: An index that maps to the first parameter of fun.
prefix :: A prefix to add to all parameters
Definition at line 1192 of file CrystalFieldFunction.cpp.
References m_mapIndices2Names, m_mapNames2Indices, n, name(), Mantid::API::IFunction::nParams(), and Mantid::API::IFunction::parameterName().
Referenced by makeMapsMultiSiteMultiSpectrum(), makeMapsMultiSiteSingleSpectrum(), makeMapsSingleSiteMultiSpectrum(), and makeMapsSingleSiteSingleSpectrum().
makeMapsMultiSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsMultiSiteMultiSpectrum () const private
Parameter-index map for multi-site multi-spectrum.
Definition at line 1296 of file CrystalFieldFunction.cpp.
References compositeSource(), Mantid::API::CompositeFunction::getFunction(), hasBackground(), m_control, m_target, makeMapsForFunction(), Mantid::API::CompositeFunction::nFunctions(), nSpectra(), and std::to_string().
Referenced by makeMaps().
makeMapsMultiSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsMultiSiteSingleSpectrum () const private
Parameter-index map for multi-site single-spectrum.
Definition at line 1263 of file CrystalFieldFunction.cpp.
References compositeSource(), hasBackground(), m_target, makeMapsForFunction(), and std::to_string().
Referenced by makeMaps().
makeMapsSingleSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsSingleSiteMultiSpectrum () const private
Parameter-index map for single-site multi-spectrum.
Definition at line 1224 of file CrystalFieldFunction.cpp.
References Mantid::API::CompositeFunction::getFunction(), hasBackground(), m_control, m_source, m_target, makeMapsForFunction(), Mantid::API::CompositeFunction::nFunctions(), nSpectra(), Mantid::CurveFitting::Functions::CrystalFieldControl::physProps(), and std::to_string().
Referenced by makeMaps().
makeMapsSingleSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::makeMapsSingleSiteSingleSpectrum () const private
Parameter-index map for single-site single-spectrum.
Definition at line 1205 of file CrystalFieldFunction.cpp.
References hasBackground(), m_source, m_target, makeMapsForFunction(), and std::to_string().
Referenced by makeMaps().
name()
std::string Mantid::CurveFitting::Functions::CrystalFieldFunction::name () const inline override virtual
Returns the function's name.
Implements Mantid::API::IFunction.
Definition at line 25 of file CrystalFieldFunction.h.
Referenced by buildAttributeNames(), getAttributeReference(), getError(), getParameter(), hasParameter(), makeMapsForFunction(), parameterIndex(), setError(), setParameter(), and setParameterDescription().
nAttributes()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::nAttributes () const override virtual
Returns the number of attributes associated with the function.
Reimplemented from Mantid::API::IFunction.
Definition at line 474 of file CrystalFieldFunction.cpp.
References buildAttributeNames(), and m_attributeNames.
nParams()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::nParams () const override virtual
Total number of parameters.
Implements Mantid::API::IFunction.
Definition at line 219 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_nControlSourceParams, m_source, and m_target.
Referenced by getParameterIndex(), makeMaps(), parameterIndex(), and parameterName().
nSpectra()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::nSpectra () const
Get number of the number of spectra (excluding phys prop data).
Definition at line 556 of file CrystalFieldFunction.cpp.
References m_control, and Mantid::API::CompositeFunction::nFunctions().
Referenced by buildAttributeNames(), buildMultiSiteMultiSpectrum(), buildSingleSiteMultiSpectrum(), makeMapsMultiSiteMultiSpectrum(), and makeMapsSingleSiteMultiSpectrum().
parameterDescription()
std::string Mantid::CurveFitting::Functions::CrystalFieldFunction::parameterDescription (size_t i) const override virtual
Returns the description of parameter i.
Implements Mantid::API::IFunction.
Definition at line 262 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and Mantid::API::CompositeFunction::parameterDescription().
parameterIndex()
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::parameterIndex (const std::string & name) const override virtual
Returns the index of parameter name.
Returns the index of a parameter with a given name.
Parameters
name :: Name of a parameter.
Implements Mantid::API::IFunction.
Definition at line 234 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_mapIndices2Names, m_mapNames2Indices, makeMaps(), name(), and nParams().
Referenced by getError(), getParameter(), hasParameter(), setError(), setParameter(), and setParameterDescription().
parameterName()
std::string Mantid::CurveFitting::Functions::CrystalFieldFunction::parameterName (size_t i) const override virtual
Returns the name of parameter i.
Implements Mantid::API::IFunction.
Definition at line 248 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_mapIndices2Names, makeMaps(), nParams(), and std::to_string().
setAttribute()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setAttribute (const std::string & name, const Attribute & attr) override virtual
Set a value to attribute attName.
Perform custom actions on setting certain attributes.
Reimplemented from Mantid::API::IFunction.
Definition at line 497 of file CrystalFieldFunction.cpp.
References cacheSourceParameters(), getAttributeReference(), m_control, m_dirtyTarget, m_source, and Mantid::API::IFunction::setAttribute().
setError() [1/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setError (const std::string & name, double err) override virtual
Set the fitting error for a parameter by name.
Set the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 328 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), index, m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, name(), parameterIndex(), and Mantid::API::CompositeFunction::setError().
setError() [2/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setError (size_t i, double err) override virtual
Set the fitting error for a parameter.
Implements Mantid::API::IFunction.
Definition at line 315 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and Mantid::API::CompositeFunction::setError().
setParameter() [1/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setParameter (const std::string & name, const double & value, bool explicitlySet = true) override virtual
Set parameter by name.
Implements Mantid::API::IFunction.
Definition at line 193 of file CrystalFieldFunction.cpp.
References index, name(), parameterIndex(), setParameter(), and value.
setParameter() [2/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setParameter (size_t i, const double & value, bool explicitlySet = true) override virtual
Set i-th parameter.
Implements Mantid::API::IFunction.
Definition at line 142 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_control, m_dirtyTarget, m_nControlParams, m_nControlSourceParams, m_source, m_target, Mantid::API::CompositeFunction::setParameter(), and value.
Referenced by setParameter().
setParameterDescription() [1/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setParameterDescription (const std::string & name, const std::string & description) override virtual
Set description of parameter by name.
Implements Mantid::API::IFunction.
Definition at line 207 of file CrystalFieldFunction.cpp.
References index, name(), parameterIndex(), and setParameterDescription().
setParameterDescription() [2/2]
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setParameterDescription (size_t i, const std::string & description) override virtual
Set i-th parameter description.
Implements Mantid::API::IFunction.
Definition at line 157 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and Mantid::API::CompositeFunction::setParameterDescription().
Referenced by setParameterDescription().
setParameterStatus()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setParameterStatus (size_t i, IFunction::ParameterStatus status) override protected virtual
Change status of parameter.
Implements Mantid::API::IFunction.
Definition at line 342 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), checkTargetFunction(), m_control, m_nControlParams, m_nControlSourceParams, m_source, m_target, and Mantid::API::CompositeFunction::setParameterStatus().
setSource()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setSource (API::IFunction_sptr source) const private
Set the source function.
Parameters
source :: New source function.
Definition at line 113 of file CrystalFieldFunction.cpp.
References m_source.
Referenced by buildSourceFunction().
setUpForFit()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::setUpForFit () override virtual
Set up the function for a fit.
Reimplemented from Mantid::API::IFunction.
Definition at line 386 of file CrystalFieldFunction.cpp.
References checkSourceFunction(), Mantid::API::IFunction::setUpForFit(), and updateTargetFunction().
updateMultiSite()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSite () const private
Update the target function in a multi site case.
Definition at line 1028 of file CrystalFieldFunction.cpp.
References isMultiSpectrum(), updateMultiSiteMultiSpectrum(), and updateMultiSiteSingleSpectrum().
Referenced by updateTargetFunction().
updateMultiSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteMultiSpectrum () const private
Update the target function in a multi site - multi spectrum case.
Definition at line 1106 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::calculateEigenSystem(), compositeSource(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getFunction(), hasBackground(), m_control, m_mapPrefixes2PhysProps, m_target, Mantid::CurveFitting::Functions::CrystalFieldControl::temperatures(), std::to_string(), updatePhysprop(), and updateSpectrum().
Referenced by updateMultiSite().
updateMultiSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateMultiSiteSingleSpectrum () const private
Update the target function in a multi site - single spectrum case.
Definition at line 1083 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asVector(), compositeSource(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getAttribute(), getAttribute(), hasBackground(), m_control, m_target, and Mantid::CurveFitting::Functions::CrystalFieldUtils::updateSpectrumFunction().
Referenced by updateMultiSite().
updatePhysprop()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updatePhysprop (int nre, const DoubleFortranVector & energies, const ComplexFortranMatrix & waveFunctions, const ComplexFortranMatrix & hamiltonian, API::IFunction & function) const private
Update a physical property function.
Parameters
nre :: An id of the ion.
energies :: A vector with energies.
waveFunctions :: A matrix with wave functions.
hamiltonian :: A matrix with the hamiltonian.
function :: A function to update.
Definition at line 980 of file CrystalFieldFunction.cpp.
References function(), Mantid::CurveFitting::Functions::CrystalFieldSusceptibilityCalculation::setEigensystem(), Mantid::CurveFitting::Functions::CrystalFieldHeatCapacityCalculation::setEnergy(), Mantid::CurveFitting::Functions::CrystalFieldMagnetisationCalculation::setHamiltonian(), and Mantid::CurveFitting::Functions::CrystalFieldMomentCalculation::setHamiltonian().
Referenced by updateMultiSiteMultiSpectrum(), and updateSingleSiteMultiSpectrum().
updateSingleSite()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSite () const private
Update the target function in a single site case.
Definition at line 1019 of file CrystalFieldFunction.cpp.
References isMultiSpectrum(), updateSingleSiteMultiSpectrum(), and updateSingleSiteSingleSpectrum().
Referenced by updateTargetFunction().
updateSingleSiteMultiSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteMultiSpectrum () const private
Update the target function in a single site - multi spectrum case.
Definition at line 1057 of file CrystalFieldFunction.cpp.
References Mantid::CurveFitting::Functions::CrystalFieldPeaksBase::calculateEigenSystem(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getFunction(), hasBackground(), m_control, m_mapPrefixes2PhysProps, Mantid::CurveFitting::Functions::CrystalFieldControl::temperatures(), updatePhysprop(), and updateSpectrum().
Referenced by updateSingleSite().
updateSingleSiteSingleSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSingleSiteSingleSpectrum () const private
Update the target function in a single site - single spectrum case.
Definition at line 1037 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asString(), Mantid::API::IFunction::Attribute::asVector(), Mantid::CurveFitting::Functions::CrystalFieldControl::FWHMs(), Mantid::API::CompositeFunction::getAttribute(), hasBackground(), m_control, m_source, m_target, and Mantid::CurveFitting::Functions::CrystalFieldUtils::updateSpectrumFunction().
Referenced by updateSingleSite().
updateSpectrum()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateSpectrum (API::IFunction & spectrum, int nre, const DoubleFortranVector & energies, const ComplexFortranMatrix & waveFunctions, double temperature, double fwhm, size_t iSpec, size_t iFirst, double intensityScaling) const private
Update a function for a single spectrum.
Parameters
spectrum :: A Spectrum function to update.
nre :: An id of the ion.
energies :: A vector with energies.
waveFunctions :: A matrix with wave functions.
temperature :: A temperature of the spectrum.
fwhm :: A full width at half maximum to set to each peak.
iSpec :: An index of the created spectrum in m_target composite function.
iFirst :: An index of the first peak in spectrum composite function.
intensityScaling :: A scaling factor for the intensities.
Definition at line 1153 of file CrystalFieldFunction.cpp.
References Mantid::API::IFunction::Attribute::asBool(), Mantid::API::IFunction::Attribute::asDouble(), Mantid::API::IFunction::Attribute::asString(), calcExcitations(), getAttribute(), Mantid::API::CompositeFunction::getFunction(), m_control, and Mantid::CurveFitting::Functions::CrystalFieldUtils::updateSpectrumFunction().
Referenced by updateMultiSiteMultiSpectrum(), and updateSingleSiteMultiSpectrum().
updateTargetFunction()
void Mantid::CurveFitting::Functions::CrystalFieldFunction::updateTargetFunction () const protected
Update the target function.
Update m_spectrum function.
Definition at line 1004 of file CrystalFieldFunction.cpp.
References buildTargetFunction(), isMultiSite(), m_dirtyTarget, m_target, updateMultiSite(), and updateSingleSite().
Referenced by checkTargetFunction(), function(), and setUpForFit().
Member Data Documentation
m_attributeNames
std::vector<std::string> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_attributeNames mutable private
Attribute names.
Definition at line 210 of file CrystalFieldFunction.h.
Referenced by buildAttributeNames(), buildTargetFunction(), getAttributeNames(), and nAttributes().
m_control
CrystalFieldControl Mantid::CurveFitting::Functions::CrystalFieldFunction::m_control mutable private
Function that creates the source function.
Definition at line 194 of file CrystalFieldFunction.h.
Referenced by buildAttributeNames(), buildMultiSiteMultiSpectrum(), buildMultiSiteSingleSpectrum(), buildSingleSiteMultiSpectrum(), buildSingleSiteSingleSpectrum(), buildSourceFunction(), buildSpectrum(), getAttributeReference(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), hasPeaks(), hasPhysProperties(), isExplicitlySet(), isMultiSite(), isMultiSpectrum(), makeMapsMultiSiteMultiSpectrum(), makeMapsSingleSiteMultiSpectrum(), nSpectra(), parameterDescription(), setAttribute(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), updateMultiSiteMultiSpectrum(), updateMultiSiteSingleSpectrum(), updateSingleSiteMultiSpectrum(), updateSingleSiteSingleSpectrum(), and updateSpectrum().
m_dirtyTarget
bool Mantid::CurveFitting::Functions::CrystalFieldFunction::m_dirtyTarget mutable private
Flag indicating that updateTargetFunction() is required.
Definition at line 204 of file CrystalFieldFunction.h.
Referenced by buildTargetFunction(), checkTargetFunction(), setAttribute(), setParameter(), and updateTargetFunction().
m_fixResetCache
std::vector<bool> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_fixResetCache mutable private
Definition at line 215 of file CrystalFieldFunction.h.
Referenced by buildSourceFunction(), and cacheSourceParameters().
m_mapIndices2Names
std::vector<std::string> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_mapIndices2Names mutable private
Map parameter indices to names.
Definition at line 208 of file CrystalFieldFunction.h.
Referenced by makeMaps(), makeMapsForFunction(), parameterIndex(), and parameterName().
m_mapNames2Indices
std::unordered_map<std::string, size_t> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_mapNames2Indices mutable private
Map parameter names to indices.
Definition at line 206 of file CrystalFieldFunction.h.
Referenced by makeMaps(), makeMapsForFunction(), and parameterIndex().
m_mapPrefixes2PhysProps
std::unordered_map<std::string, API::IFunction_sptr> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_mapPrefixes2PhysProps mutable private
Map parameter/attribute prefixes to pointers to phys prop functions.
Definition at line 212 of file CrystalFieldFunction.h.
Referenced by buildMultiSiteMultiSpectrum(), buildSingleSiteMultiSpectrum(), getAttributeReference(), updateMultiSiteMultiSpectrum(), and updateSingleSiteMultiSpectrum().
m_nControlParams
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::m_nControlParams mutable private
Cached number of parameters in m_control.
Definition at line 200 of file CrystalFieldFunction.h.
Referenced by buildSourceFunction(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), parameterDescription(), setError(), setParameter(), setParameterDescription(), and setParameterStatus().
m_nControlSourceParams
size_t Mantid::CurveFitting::Functions::CrystalFieldFunction::m_nControlSourceParams mutable private
Cached number of parameters in m_control and m_source.
Definition at line 202 of file CrystalFieldFunction.h.
Referenced by buildSourceFunction(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), nParams(), parameterDescription(), setError(), setParameter(), setParameterDescription(), and setParameterStatus().
m_parameterResetCache
std::vector<double> Mantid::CurveFitting::Functions::CrystalFieldFunction::m_parameterResetCache mutable private
Temporary cache for parameter values during source function resetting.
Definition at line 214 of file CrystalFieldFunction.h.
Referenced by buildSourceFunction(), and cacheSourceParameters().
m_source
API::IFunction_sptr Mantid::CurveFitting::Functions::CrystalFieldFunction::m_source mutable private
Function that calculates parameters of the target function.
Definition at line 196 of file CrystalFieldFunction.h.
Referenced by buildSingleSiteSingleSpectrum(), buildSourceFunction(), cacheSourceParameters(), checkSourceFunction(), compositeSource(), getConstraint(), getError(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), makeMapsSingleSiteMultiSpectrum(), makeMapsSingleSiteSingleSpectrum(), nParams(), parameterDescription(), setAttribute(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), setSource(), and updateSingleSiteSingleSpectrum().
m_target
API::CompositeFunction_sptr Mantid::CurveFitting::Functions::CrystalFieldFunction::m_target mutable private
Function that actually calculates the output.
Definition at line 198 of file CrystalFieldFunction.h.
Referenced by buildAttributeNames(), buildMultiSiteMultiSpectrum(), buildMultiSiteSingleSpectrum(), buildSingleSiteMultiSpectrum(), buildSingleSiteSingleSpectrum(), checkTargetFunction(), function(), getConstraint(), getError(), getNumberDomains(), getParameter(), getParameterIndex(), getParameterStatus(), getTie(), isExplicitlySet(), makeMapsMultiSiteMultiSpectrum(), makeMapsMultiSiteSingleSpectrum(), makeMapsSingleSiteMultiSpectrum(), makeMapsSingleSiteSingleSpectrum(), nParams(), parameterDescription(), setError(), setParameter(), setParameterDescription(), setParameterStatus(), updateMultiSiteMultiSpectrum(), updateMultiSiteSingleSpectrum(), updateSingleSiteSingleSpectrum(), and updateTargetFunction().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldFunction.h
Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp