Mantid: Mantid::Geometry::SurfPoint Class Reference
Mantid::Geometry::SurfPoint Class Reference
Surface leaf node.
#include <Rules.h>
Public Member Functions
std::string className () const override
Returns class name as string.
std::unique_ptr< SurfPoint > clone () const
Clone constructor.
std::string display () const override
Returns the signed surface number as a string.
std::string displayAddress () const override
Returns the memory address as a string.
Rule * findKey (const int KeyNum) override
Finds the leaf with the surface number KeyN.
int findLeaf (const Rule *) const override
Determines if this rule is a particular leaf value uses memory address to compare.
void getBoundingBox (double &xmax, double &ymax, double &zmax, double &xmin, double &ymin, double &zmin) override
gets the bounding box for the surface object held by SurfPoint
Surface * getKey () const
Get Surface Ptr.
int getKeyN () const
Get Key.
int getSign () const
Get Sign.
bool isValid (const Kernel::V3D &) const override
Determines if a point is valid.
bool isValid (const std::map< int, int > &) const override
Use MX to determine if the surface truth etc is valid.
Rule * leaf (const int=0) const override
No Leaves.
void setKey (const std::shared_ptr< Surface > &Spoint)
Sets the key pointer.
void setKeyN (const int Ky)
set keyNumber
void setLeaf (std::unique_ptr< Rule >, const int=0) override
Replaces a leaf with a rule.
void setLeaves (std::unique_ptr< Rule >, std::unique_ptr< Rule >) override
Replaces a leaf with a rule.
int simplify () override
Impossible to simplify a simple rule leaf.
SurfPoint ()
Constructor with null key/number.
int type () const override
Effective name.
Public Member Functions inherited from Mantid::Geometry::Rule
int checkParents () const
Debug test for parents.
std::unique_ptr< Rule > clone () const
int commonType () const
Gets a common type.
int Eliminate ()
elimination not written
int getKeyList (std::vector< int > &) const
Generate the key list given an insertion type object.
Rule * getParent () const
Returns the parent object.
virtual int isComplementary () const
Always returns false (0)
void makeParents ()
This is initialisation code that populates all the parents in the rule tree.
Rule ()
Standard Constructor.
Rule (Rule *)
Constructor copies.
void setParent (Rule *)
Sets the parent object (not check for A==this)
int substituteSurf (const int SurfN, const int newSurfN, const std::shared_ptr< Surface > &SPtr)
Substitues a surface item if within a rule.
virtual ~Rule ()=default
Private Member Functions
SurfPoint * doClone () const override
Clone constructor.
Private Attributes
int keyN
Key Number (identifer)
std::shared_ptr< Surface > m_key
Actual Surface Base Object.
int sign
+/- in Object unit
Additional Inherited Members
Static Public Member Functions inherited from Mantid::Geometry::Rule
static int makeCNF (std::unique_ptr< Rule > &)
Make Rule into a CNF format.
static int makeCNFcopy (std::unique_ptr< Rule > &)
Make Rule into a CNF format (slow)
static int makeFullDNF (std::unique_ptr< Rule > &)
Make Rule into a full DNF format.
static int removeComplementary (std::unique_ptr< Rule > &)
NOT WORKING.
static int removeItem (std::unique_ptr< Rule > &TRule, const int SurfN)
Given an item as a surface name, remove the surface from the Rule tree.
Protected Member Functions inherited from Mantid::Geometry::Rule
Rule & operator= (const Rule &)
Assignment operator= does not set parent as Rules are cloned.
Rule (const Rule &)
Constructor copies.
Detailed Description
Surface leaf node.
Author
S.Ansell
Version
1.0
Date
August 2005
This class acts as an interface between a general surface and a rule. Allowing an Rule chain to be calculated
Definition at line 213 of file Rules.h.
Constructor & Destructor Documentation
SurfPoint()
Mantid::Geometry::SurfPoint::SurfPoint ()
Constructor with null key/number.
Definition at line 667 of file RuleItems.cpp.
Referenced by doClone().
Member Function Documentation
className()
std::string Mantid::Geometry::SurfPoint::className () const inline override virtual
Returns class name as string.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 221 of file Rules.h.
clone()
std::unique_ptr< SurfPoint > Mantid::Geometry::SurfPoint::clone () const
Clone constructor.
Returns
new(*this)
Definition at line 683 of file RuleItems.cpp.
References doClone().
display()
std::string Mantid::Geometry::SurfPoint::display () const override virtual
Returns the signed surface number as a string.
Returns
string of the value
Implements Mantid::Geometry::Rule.
Definition at line 801 of file RuleItems.cpp.
References keyN, and sign.
displayAddress()
std::string Mantid::Geometry::SurfPoint::displayAddress () const override virtual
Returns the memory address as a string.
Returns
memory address as string
Implements Mantid::Geometry::Rule.
Definition at line 813 of file RuleItems.cpp.
doClone()
SurfPoint * Mantid::Geometry::SurfPoint::doClone () const override private virtual
Clone constructor.
Returns
new(*this)
Implements Mantid::Geometry::Rule.
Definition at line 674 of file RuleItems.cpp.
References SurfPoint().
Referenced by clone().
findKey()
Rule * Mantid::Geometry::SurfPoint::findKey (const int KeyNum) override virtual
Finds the leaf with the surface number KeyN.
Parameters
KeyNum :: Number to search for
Return values
0 :: no leaf with that key number availiable
Rule* if an appropiate leaf is found
Implements Mantid::Geometry::Rule.
Definition at line 731 of file RuleItems.cpp.
References keyN.
findLeaf()
int Mantid::Geometry::SurfPoint::findLeaf (const Rule * A) const override virtual
Determines if this rule is a particular leaf value uses memory address to compare.
Parameters
A :: Rule to check
Returns
0 if true and -1 if false.
Implements Mantid::Geometry::Rule.
Definition at line 720 of file RuleItems.cpp.
getBoundingBox()
void Mantid::Geometry::SurfPoint::getBoundingBox (double & xmax, double & ymax, double & zmax, double & xmin, double & ymin, double & zmin) override virtual
gets the bounding box for the surface object held by SurfPoint
Parameters
xmax :: Maximum value for the bounding box in x direction
ymax :: Maximum value for the bounding box in y direction
zmax :: Maximum value for the bounding box in z direction
xmin :: Minimum value for the bounding box in x direction
ymin :: Minimum value for the bounding box in y direction
zmin :: Minimum value for the bounding box in z direction
Implements Mantid::Geometry::Rule.
Definition at line 834 of file RuleItems.cpp.
References m_key, and sign.
getKey()
Surface * Mantid::Geometry::SurfPoint::getKey () const inline
Get Surface Ptr.
Definition at line 240 of file Rules.h.
References m_key.
getKeyN()
int Mantid::Geometry::SurfPoint::getKeyN () const inline
Get Key.
Definition at line 237 of file Rules.h.
getSign()
int Mantid::Geometry::SurfPoint::getSign () const inline
Get Sign.
Definition at line 236 of file Rules.h.
isValid() [1/2]
bool Mantid::Geometry::SurfPoint::isValid (const Kernel::V3D & Pt) const override virtual
Determines if a point is valid.
Parameters
Pt :: Point to test
Return values
1 :: Pt is the +ve side of the surface or on the surface
0 :: Pt is on the -ve side of the surface
Implements Mantid::Geometry::Rule.
Definition at line 771 of file RuleItems.cpp.
References m_key.
isValid() [2/2]
bool Mantid::Geometry::SurfPoint::isValid (const std::map< int, int > & MX) const override virtual
Use MX to determine if the surface truth etc is valid.
Parameters
MX :: map of key + logical value XOR sign
Returns
MX.second if key found or 0
Implements Mantid::Geometry::Rule.
Definition at line 786 of file RuleItems.cpp.
leaf()
Rule * Mantid::Geometry::SurfPoint::leaf (const int = 0) const inline override virtual
No Leaves.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 224 of file Rules.h.
setKey()
void Mantid::Geometry::SurfPoint::setKey (const std::shared_ptr< Surface > & Spoint)
Sets the key pointer.
The class takes ownership.
Parameters
Spoint :: new key values
Definition at line 752 of file RuleItems.cpp.
References m_key.
Referenced by Mantid::Geometry::CSGObject::populate().
setKeyN()
void Mantid::Geometry::SurfPoint::setKeyN (const int Ky)
set keyNumber
Sets the key and the sign.
Parameters
Ky :: key value (+/- is used for sign)
Definition at line 742 of file RuleItems.cpp.
References keyN, and sign.
Referenced by Mantid::Geometry::Rule::substituteSurf().
setLeaf()
void Mantid::Geometry::SurfPoint::setLeaf (std::unique_ptr< Rule > nR, const int = 0) override virtual
Replaces a leaf with a rule.
This REQUIRES that nR is of type SurfPoint
Parameters
nR :: new rule
: ignored
Implements Mantid::Geometry::Rule.
Definition at line 692 of file RuleItems.cpp.
setLeaves()
void Mantid::Geometry::SurfPoint::setLeaves (std::unique_ptr< Rule > aR, std::unique_ptr< Rule >) override virtual
Replaces a leaf with a rule.
This REQUIRES that nR is of type SurfPoint
Parameters
aR :: new rule
Implements Mantid::Geometry::Rule.
Definition at line 707 of file RuleItems.cpp.
simplify()
int Mantid::Geometry::SurfPoint::simplify () override virtual
Impossible to simplify a simple rule leaf.
Therefore returns 0
Returns
0
Implements Mantid::Geometry::Rule.
Definition at line 761 of file RuleItems.cpp.
type()
int Mantid::Geometry::SurfPoint::type () const inline override virtual
Effective name.
Reimplemented from Mantid::Geometry::Rule.
Definition at line 230 of file Rules.h.
Member Data Documentation
keyN
int Mantid::Geometry::SurfPoint::keyN private
Key Number (identifer)
Definition at line 217 of file Rules.h.
Referenced by display(), findKey(), and setKeyN().
m_key
std::shared_ptr<Surface> Mantid::Geometry::SurfPoint::m_key private
Actual Surface Base Object.
Definition at line 215 of file Rules.h.
Referenced by getBoundingBox(), and setKey().
sign
int Mantid::Geometry::SurfPoint::sign private
+/- in Object unit
Definition at line 218 of file Rules.h.
Referenced by display(), getBoundingBox(), and setKeyN().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Objects/Rules.h
Framework/Geometry/src/Objects/RuleItems.cpp