Mantid: ICat4::ns1__sampleType Class Reference
ICat4::ns1__sampleType Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__sampleType ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
ns1__facility * facility
std::string * molecularFormula
std::string * name
std::string * safetyInformation
std::vector< ns1__sample * > samples
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 2083 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__sampleType()
ICat4::ns1__sampleType::ns1__sampleType () inline
Definition at line 2098 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__sampleType::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9866 of file ICat4C.cpp.
References facility, molecularFormula, name, safetyInformation, samples, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__sample().
Referenced by ICat4::soap_in_ns1__sampleType(), ICat4::soap_new_req_ns1__sampleType(), and ICat4::soap_new_set_ns1__sampleType().
soap_get()
void * ICat4::ns1__sampleType::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10039 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__sampleType().
soap_in()
void * ICat4::ns1__sampleType::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9923 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__sampleType().
Referenced by ICat4::soap_in_ns1__sampleType().
soap_out()
int ICat4::ns1__sampleType::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9890 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__sampleType().
Referenced by soap_put().
soap_put()
int ICat4::ns1__sampleType::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 10032 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__sampleType.
soap_serialize()
void ICat4::ns1__sampleType::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 9877 of file ICat4C.cpp.
References facility, molecularFormula, name, safetyInformation, samples, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__sample().
Referenced by ICat4::soap_serialize_PointerTons1__investigationParameter().
soap_type()
int ICat4::ns1__sampleType::soap_type () const inline override virtual
Reimplemented from ICat4::ns1__entityBaseBean.
Definition at line 2091 of file ICat4Stub.h.
Member Data Documentation
facility
ns1__facility* ICat4::ns1__sampleType::facility
Definition at line 2085 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
molecularFormula
std::string* ICat4::ns1__sampleType::molecularFormula
Definition at line 2086 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__sampleType::name
Definition at line 2087 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
safetyInformation
std::string* ICat4::ns1__sampleType::safetyInformation
Definition at line 2088 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
samples
std::vector<ns1__sample *> ICat4::ns1__sampleType::samples
Definition at line 2089 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp