Mantid: MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation Class Reference
MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation Class Reference
#include <QtTreeCursorNavigation.h>
Public Member Functions
QModelIndex firstCellOnNextRow (QModelIndex const &rowAbove) const
bool isNotFirstCellInThisRow (QModelIndex const &index) const
bool isNotFirstRowInThisNode (QModelIndex const &index) const
bool isNotLastCellOnThisRow (QModelIndex const &index) const
bool isNotLastRowInThisNode (QModelIndex const &index) const
QModelIndex lastCellInParentRowElseNone (QModelIndex const &index) const
QModelIndex lastCellInPreviousRow (QModelIndex const &index) const
QModelIndex lastRowInThisNode (QModelIndex const &index) const
QtTreeCursorNavigationResult moveCursorNext (QModelIndex const &currentIndex) const
QModelIndex moveCursorPrevious (QModelIndex const &currentIndex) const
QModelIndex nextCellOnThisRow (QModelIndex const &index) const
QModelIndex previousCellInThisRow (QModelIndex const &index) const
QtTreeCursorNavigation (QAbstractItemModel const *model)
Private Member Functions
QtTreeCursorNavigationResult withAppendedRow (QModelIndex const &index) const
QtTreeCursorNavigationResult withoutAppendedRow (QModelIndex const &index) const
Private Attributes
QAbstractItemModel const * m_model
Detailed Description
Definition at line 19 of file QtTreeCursorNavigation.h.
Constructor & Destructor Documentation
QtTreeCursorNavigation()
MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::QtTreeCursorNavigation (QAbstractItemModel const * model)
Definition at line 12 of file QtTreeCursorNavigation.cpp.
Member Function Documentation
firstCellOnNextRow()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::firstCellOnNextRow (QModelIndex const & rowAbove) const
Definition at line 72 of file QtTreeCursorNavigation.cpp.
References index.
Referenced by moveCursorNext().
isNotFirstCellInThisRow()
bool MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotFirstCellInThisRow (QModelIndex const & index) const
Definition at line 46 of file QtTreeCursorNavigation.cpp.
References MantidQt::MantidWidgets::Batch::hasCellOnTheLeft(), and index.
Referenced by moveCursorPrevious().
isNotFirstRowInThisNode()
bool MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotFirstRowInThisNode (QModelIndex const & index) const
Definition at line 48 of file QtTreeCursorNavigation.cpp.
References MantidQt::MantidWidgets::Batch::hasRowAbove(), and index.
Referenced by moveCursorPrevious().
isNotLastCellOnThisRow()
bool MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotLastCellOnThisRow (QModelIndex const & index) const
Definition at line 78 of file QtTreeCursorNavigation.cpp.
References MantidQt::MantidWidgets::Batch::hasCellOnTheRight(), and index.
Referenced by moveCursorNext().
isNotLastRowInThisNode()
bool MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::isNotLastRowInThisNode (QModelIndex const & index) const
Definition at line 80 of file QtTreeCursorNavigation.cpp.
References MantidQt::MantidWidgets::Batch::hasRowBelow(), and index.
Referenced by moveCursorNext().
lastCellInParentRowElseNone()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::lastCellInParentRowElseNone (QModelIndex const & index) const
Definition at line 64 of file QtTreeCursorNavigation.cpp.
References index, and m_model.
Referenced by moveCursorPrevious().
lastCellInPreviousRow()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::lastCellInPreviousRow (QModelIndex const & index) const
Definition at line 52 of file QtTreeCursorNavigation.cpp.
References index, and m_model.
Referenced by moveCursorPrevious().
lastRowInThisNode()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::lastRowInThisNode (QModelIndex const & index) const
Definition at line 60 of file QtTreeCursorNavigation.cpp.
References MantidQt::MantidWidgets::Batch::lastChildRowOf(), and m_model.
moveCursorNext()
std::pair< bool, QModelIndex > MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::moveCursorNext (QModelIndex const & currentIndex) const
Definition at line 22 of file QtTreeCursorNavigation.cpp.
References firstCellOnNextRow(), isNotLastCellOnThisRow(), isNotLastRowInThisNode(), nextCellOnThisRow(), withAppendedRow(), and withoutAppendedRow().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::moveNextUntilEditable().
moveCursorPrevious()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::moveCursorPrevious (QModelIndex const & currentIndex) const
Definition at line 34 of file QtTreeCursorNavigation.cpp.
References isNotFirstCellInThisRow(), isNotFirstRowInThisNode(), lastCellInParentRowElseNone(), lastCellInPreviousRow(), and previousCellInThisRow().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::movePreviousUntilEditable().
nextCellOnThisRow()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::nextCellOnThisRow (QModelIndex const & index) const
Definition at line 76 of file QtTreeCursorNavigation.cpp.
References index, and MantidQt::MantidWidgets::Batch::rightOf().
Referenced by moveCursorNext().
previousCellInThisRow()
QModelIndex MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::previousCellInThisRow (QModelIndex const & index) const
Definition at line 50 of file QtTreeCursorNavigation.cpp.
References index, and MantidQt::MantidWidgets::Batch::leftOf().
Referenced by moveCursorPrevious().
withAppendedRow()
QtTreeCursorNavigationResult MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::withAppendedRow (QModelIndex const & index) const private
Definition at line 18 of file QtTreeCursorNavigation.cpp.
References index.
Referenced by moveCursorNext().
withoutAppendedRow()
QtTreeCursorNavigationResult MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::withoutAppendedRow (QModelIndex const & index) const private
Definition at line 14 of file QtTreeCursorNavigation.cpp.
References index.
Referenced by moveCursorNext().
Member Data Documentation
m_model
QAbstractItemModel const* MantidQt::MantidWidgets::Batch::QtTreeCursorNavigation::m_model private
Definition at line 38 of file QtTreeCursorNavigation.h.
Referenced by lastCellInParentRowElseNone(), lastCellInPreviousRow(), and lastRowInThisNode().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/QtTreeCursorNavigation.h
qt/widgets/common/src/Batch/QtTreeCursorNavigation.cpp