Mantid: Mantid::DataHandling::ANSTO::Tar::File Class Reference
Mantid::DataHandling::ANSTO::Tar::File Class Reference
#include <LoadANSTOHelper.h>
Classes
struct FileInfo
Public Member Functions
void close ()
File (const std::string &path)
const std::vector< std::string > & files () const
bool good () const
size_t read (void *dst, size_t size)
int read_byte ()
bool select (const char *file)
const std::string & selected_name () const
int64_t selected_position () const
int64_t selected_size () const
bool skip (uint64_t offset)
Static Public Member Functions
static bool append (const std::string &path, const std::string &name, const void *buffer, size_t size)
Private Member Functions
File (const File &)=delete
File & operator= (const File &)=delete
Private Attributes
uint8_t m_buffer [BUFFER_SIZE]
size_t m_bufferAvailable
size_t m_bufferPosition
FastReadOnlyFile m_file
std::vector< FileInfo > m_fileInfos
std::vector< std::string > m_fileNames
bool m_good
int64_t m_position
size_t m_selected
int64_t m_size
Static Private Attributes
static const auto BUFFER_SIZE = 4096
Detailed Description
Definition at line 200 of file LoadANSTOHelper.h.
Constructor & Destructor Documentation
File() [1/2]
Mantid::DataHandling::ANSTO::Tar::File::File (const File &) private delete
File() [2/2]
Mantid::DataHandling::ANSTO::Tar::File::File (const std::string & path) explicit
Definition at line 253 of file LoadANSTOHelper.cpp.
References Mantid::DataHandling::ANSTO::FastReadOnlyFile::handle(), m_file, m_fileInfos, m_fileNames, m_good, Mantid::DataHandling::ANSTO::Tar::File::FileInfo::Offset, position, Mantid::DataHandling::ANSTO::FastReadOnlyFile::read(), Mantid::DataHandling::ANSTO::FastReadOnlyFile::seek(), Mantid::DataHandling::ANSTO::Tar::File::FileInfo::Size, and TarTypeFlag_NormalFile.
Member Function Documentation
append()
bool Mantid::DataHandling::ANSTO::Tar::File::append (const std::string & path, const std::string & name, const void * buffer, size_t size) static
Definition at line 416 of file LoadANSTOHelper.cpp.
References name, position, and TarTypeFlag_NormalFile.
Referenced by Mantid::DataHandling::PatchBBY::exec().
close()
void Mantid::DataHandling::ANSTO::Tar::File::close ()
Definition at line 287 of file LoadANSTOHelper.cpp.
References Mantid::DataHandling::ANSTO::FastReadOnlyFile::close(), m_bufferAvailable, m_bufferPosition, m_file, m_fileInfos, m_fileNames, m_good, m_position, m_selected, and m_size.
Referenced by Mantid::DataHandling::PatchBBY::exec().
files()
const std::vector< std::string > & Mantid::DataHandling::ANSTO::Tar::File::files () const
Definition at line 301 of file LoadANSTOHelper.cpp.
References m_fileNames.
Referenced by Mantid::DataHandling::LoadBBY::confidence(), Mantid::DataHandling::LoadEMUTar::confidence(), Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMUTar::exec(), Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::LoadBBY::loadEvents().
good()
bool Mantid::DataHandling::ANSTO::Tar::File::good () const
Definition at line 300 of file LoadANSTOHelper.cpp.
References m_good.
Referenced by Mantid::DataHandling::LoadBBY::confidence(), Mantid::DataHandling::LoadEMUTar::confidence(), Mantid::DataHandling::LoadBBY::exec(), Mantid::DataHandling::LoadEMUTar::exec(), and Mantid::DataHandling::PatchBBY::exec().
operator=()
File & Mantid::DataHandling::ANSTO::Tar::File::operator= (const File &) private delete
read()
size_t Mantid::DataHandling::ANSTO::Tar::File::read (void * dst, size_t size)
Definition at line 354 of file LoadANSTOHelper.cpp.
References m_buffer, m_bufferAvailable, m_bufferPosition, m_file, m_good, m_position, m_selected, m_size, and Mantid::DataHandling::ANSTO::FastReadOnlyFile::read().
Referenced by Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadEMUTar::exec(), and Mantid::DataHandling::PatchBBY::exec().
read_byte()
int Mantid::DataHandling::ANSTO::Tar::File::read_byte ()
Definition at line 393 of file LoadANSTOHelper.cpp.
References m_buffer, m_bufferAvailable, m_bufferPosition, m_file, m_good, m_position, m_selected, m_size, and Mantid::DataHandling::ANSTO::FastReadOnlyFile::read().
Referenced by Mantid::DataHandling::LoadBBY::loadEvents().
select()
bool Mantid::DataHandling::ANSTO::Tar::File::select (const char * file)
Definition at line 307 of file LoadANSTOHelper.cpp.
References m_bufferAvailable, m_bufferPosition, m_file, m_fileInfos, m_fileNames, m_good, m_position, m_selected, m_size, Mantid::DataHandling::ANSTO::Tar::File::FileInfo::Offset, Mantid::DataHandling::ANSTO::FastReadOnlyFile::seek(), and Mantid::DataHandling::ANSTO::Tar::File::FileInfo::Size.
Referenced by Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadEMUTar::exec(), Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::LoadBBY::loadEvents().
selected_name()
const std::string & Mantid::DataHandling::ANSTO::Tar::File::selected_name () const
Definition at line 302 of file LoadANSTOHelper.cpp.
References m_fileNames, and m_selected.
selected_position()
int64_t Mantid::DataHandling::ANSTO::Tar::File::selected_position () const
Definition at line 303 of file LoadANSTOHelper.cpp.
References m_position.
Referenced by Mantid::DataHandling::LoadBBY::loadEvents().
selected_size()
int64_t Mantid::DataHandling::ANSTO::Tar::File::selected_size () const
Definition at line 304 of file LoadANSTOHelper.cpp.
References m_size.
Referenced by Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::PatchBBY::exec(), and Mantid::DataHandling::LoadBBY::loadEvents().
skip()
bool Mantid::DataHandling::ANSTO::Tar::File::skip (uint64_t offset)
Definition at line 332 of file LoadANSTOHelper.cpp.
References m_bufferAvailable, m_bufferPosition, m_file, m_good, m_position, m_selected, m_size, and Mantid::DataHandling::ANSTO::FastReadOnlyFile::seek().
Referenced by Mantid::DataHandling::LoadBBY::loadEvents().
Member Data Documentation
BUFFER_SIZE
const auto Mantid::DataHandling::ANSTO::Tar::File::BUFFER_SIZE = 4096 static private
Definition at line 202 of file LoadANSTOHelper.h.
m_buffer
uint8_t Mantid::DataHandling::ANSTO::Tar::File::m_buffer[BUFFER_SIZE] private
Definition at line 220 of file LoadANSTOHelper.h.
Referenced by read(), and read_byte().
m_bufferAvailable
size_t Mantid::DataHandling::ANSTO::Tar::File::m_bufferAvailable private
Definition at line 222 of file LoadANSTOHelper.h.
Referenced by close(), read(), read_byte(), select(), and skip().
m_bufferPosition
size_t Mantid::DataHandling::ANSTO::Tar::File::m_bufferPosition private
Definition at line 221 of file LoadANSTOHelper.h.
Referenced by close(), read(), read_byte(), select(), and skip().
m_file
FastReadOnlyFile Mantid::DataHandling::ANSTO::Tar::File::m_file private
Definition at line 212 of file LoadANSTOHelper.h.
Referenced by close(), File(), read(), read_byte(), select(), and skip().
m_fileInfos
std::vector<FileInfo> Mantid::DataHandling::ANSTO::Tar::File::m_fileInfos private
Definition at line 214 of file LoadANSTOHelper.h.
Referenced by close(), File(), and select().
m_fileNames
std::vector<std::string> Mantid::DataHandling::ANSTO::Tar::File::m_fileNames private
Definition at line 213 of file LoadANSTOHelper.h.
Referenced by close(), File(), files(), select(), and selected_name().
m_good
bool Mantid::DataHandling::ANSTO::Tar::File::m_good private
Definition at line 211 of file LoadANSTOHelper.h.
Referenced by close(), File(), good(), read(), read_byte(), select(), and skip().
m_position
int64_t Mantid::DataHandling::ANSTO::Tar::File::m_position private
Definition at line 217 of file LoadANSTOHelper.h.
Referenced by close(), read(), read_byte(), select(), selected_position(), and skip().
m_selected
size_t Mantid::DataHandling::ANSTO::Tar::File::m_selected private
Definition at line 216 of file LoadANSTOHelper.h.
Referenced by close(), read(), read_byte(), select(), selected_name(), and skip().
m_size
int64_t Mantid::DataHandling::ANSTO::Tar::File::m_size private
Definition at line 218 of file LoadANSTOHelper.h.
Referenced by close(), read(), read_byte(), select(), selected_size(), and skip().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadANSTOHelper.h
Framework/DataHandling/src/LoadANSTOHelper.cpp