Mantid: Mantid::Algorithms::MonIDPropChanger Class Reference
Mantid::Algorithms::MonIDPropChanger Class Reference
#include <NormaliseToMonitor.h>
Public Member Functions
bool applyChanges (const Mantid::Kernel::IPropertyManager *algo, const std::string &propName) const override
Overload this virtual function in order to modify the current property based on changes to other properties.
IPropertySettings * clone () const override
Make a copy of the present type of IPropertySettings.
bool isConditionChanged (const Mantid::Kernel::IPropertyManager *algo, const std::string &changedPropName="") const override
to verify if the properties, this one depends on have changed or other special condition occurs which needs the framework to react to
bool isEnabled (const Mantid::Kernel::IPropertyManager *algo) const override
Is the property to be shown as "enabled" in the GUI.
MonIDPropChanger (const std::string &WSProperty, const std::string &SpectrToNormByProperty, const std::string &MonitorWorkspace)
Public Member Functions inherited from Mantid::Kernel::IPropertySettings
virtual std::vector< std::string > dependsOn (const std::string &) const
Other properties that this property depends on.
IPropertySettings ()=default
Constructor.
virtual bool isVisible (const IPropertyManager *algo) const
Is the property to be shown in the GUI? Default true.
virtual ~IPropertySettings ()=default
Destructor.
Private Member Functions
bool monitorIdReader (const API::MatrixWorkspace_const_sptr &inputWS) const
Private Attributes
std::string hostWSname
std::vector< int > iExistingAllowedValues
bool is_enabled
std::string MonitorWorkspaceProp
std::string SpectraNum
Additional Inherited Members
Protected Member Functions inherited from Mantid::Kernel::IPropertySettings
IPropertySettings (const IPropertySettings &)=default
Detailed Description
Definition at line 121 of file NormaliseToMonitor.h.
Constructor & Destructor Documentation
MonIDPropChanger()
Mantid::Algorithms::MonIDPropChanger::MonIDPropChanger (const std::string & WSProperty, const std::string & SpectrToNormByProperty, const std::string & MonitorWorkspace) inline
Definition at line 126 of file NormaliseToMonitor.h.
Member Function Documentation
applyChanges()
bool Mantid::Algorithms::MonIDPropChanger::applyChanges (const Mantid::Kernel::IPropertyManager * algo, const std::string & currentPropName) const override virtual
Overload this virtual function in order to modify the current property based on changes to other properties.
Returns
: whether or not the current property was changed.
Reimplemented from Mantid::Kernel::IPropertySettings.
Definition at line 75 of file NormaliseToMonitor.cpp.
References Mantid::Kernel::IPropertyManager::getPointerToProperty(), Mantid::Kernel::IPropertyManager::getProperty(), hostWSname, and iExistingAllowedValues.
clone()
IPropertySettings * Mantid::Algorithms::MonIDPropChanger::clone () const inline override virtual
Make a copy of the present type of IPropertySettings.
Implements Mantid::Kernel::IPropertySettings.
Definition at line 137 of file NormaliseToMonitor.h.
isConditionChanged()
bool Mantid::Algorithms::MonIDPropChanger::isConditionChanged (const Mantid::Kernel::IPropertyManager * algo, const std::string & changedPropName = "") const override virtual
to verify if the properties, this one depends on have changed or other special condition occurs which needs the framework to react to
Reimplemented from Mantid::Kernel::IPropertySettings.
Definition at line 64 of file NormaliseToMonitor.cpp.
References Mantid::Kernel::IPropertyManager::getProperty(), hostWSname, is_enabled, monitorIdReader(), and UNUSED_ARG.
isEnabled()
bool Mantid::Algorithms::MonIDPropChanger::isEnabled (const Mantid::Kernel::IPropertyManager * algo) const override virtual
Is the property to be shown as "enabled" in the GUI.
Default true.
Reimplemented from Mantid::Kernel::IPropertySettings.
Definition at line 40 of file NormaliseToMonitor.cpp.
References Mantid::Kernel::IPropertyManager::getProperty(), is_enabled, MonitorWorkspaceProp, and SpectraNum.
monitorIdReader()
bool Mantid::Algorithms::MonIDPropChanger::monitorIdReader (const API::MatrixWorkspace_const_sptr & inputWS) const private
Definition at line 98 of file NormaliseToMonitor.cpp.
References iExistingAllowedValues.
Referenced by isConditionChanged().
Member Data Documentation
hostWSname
std::string Mantid::Algorithms::MonIDPropChanger::hostWSname private
Definition at line 144 of file NormaliseToMonitor.h.
Referenced by applyChanges(), and isConditionChanged().
iExistingAllowedValues
std::vector<int> Mantid::Algorithms::MonIDPropChanger::iExistingAllowedValues mutable private
Definition at line 153 of file NormaliseToMonitor.h.
Referenced by applyChanges(), and monitorIdReader().
is_enabled
bool Mantid::Algorithms::MonIDPropChanger::is_enabled mutable private
Definition at line 155 of file NormaliseToMonitor.h.
Referenced by isConditionChanged(), and isEnabled().
MonitorWorkspaceProp
std::string Mantid::Algorithms::MonIDPropChanger::MonitorWorkspaceProp private
Definition at line 150 of file NormaliseToMonitor.h.
Referenced by isEnabled().
SpectraNum
std::string Mantid::Algorithms::MonIDPropChanger::SpectraNum private
Definition at line 147 of file NormaliseToMonitor.h.
Referenced by isEnabled().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/NormaliseToMonitor.h
Framework/Algorithms/src/NormaliseToMonitor.cpp