Mantid: Mantid::CurveFitting::MSVesuvioHelper Namespace Reference
Mantid::CurveFitting::MSVesuvioHelper Namespace Reference
Classes
class RandomVariateGenerator
struct Simulation
struct SimulationAggregator
struct SimulationWithErrors
Functions
double finalEnergyAuDD (const double randv)
Generate the final energy of a neutron for gold foil analyser at 293K in double-difference mode:
double finalEnergyAuYap (const double randv)
Generate the final energy of a neutron for gold foil analyser at 293K with number density of 7.35E19 atoms/cm^2 in yap difference mode.
double finalEnergyUranium (const double randv)
Generate the final energy of a neutron for uranium foil analyser at 293K with number density of 1.456E20 atoms/cm^2 in double-difference mode.
Function Documentation
finalEnergyAuDD()
double Mantid::CurveFitting::MSVesuvioHelper::finalEnergyAuDD (const double randv)
Generate the final energy of a neutron for gold foil analyser at 293K in double-difference mode:
THIN FOIL NUMBER DENSITY = 1.456E20 ATOMS/SQ CM.
THICK FOIL NUMBER DENSITY = 3.0* 1.456E20 ATOMS/SQ CM.
Parameters
randv A random number between 0.0 & 1.0, sample from a flat distribution
Returns
A value to use for the final energy
Definition at line 26 of file MSVesuvioHelpers.cpp.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateE1().
finalEnergyAuYap()
double Mantid::CurveFitting::MSVesuvioHelper::finalEnergyAuYap (const double randv)
Generate the final energy of a neutron for gold foil analyser at 293K with number density of 7.35E19 atoms/cm^2 in yap difference mode.
Parameters
randv A random number between 0.0 & 1.0, sample from a flat distribution
Returns
A value to use for the final energy
Definition at line 102 of file MSVesuvioHelpers.cpp.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateE1().
finalEnergyUranium()
double Mantid::CurveFitting::MSVesuvioHelper::finalEnergyUranium (const double randv)
Generate the final energy of a neutron for uranium foil analyser at 293K with number density of 1.456E20 atoms/cm^2 in double-difference mode.
Parameters
randv A random number between 0.0 & 1.0, sample from a flat distribution
Returns
A value to use for the final energy
Definition at line 220 of file MSVesuvioHelpers.cpp.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::generateE1().