Mantid: ICat4::ns1__datasetType Class Reference
ICat4::ns1__datasetType Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__datasetType ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::ns1__entityBaseBean
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::vector< ns1__dataset * > datasets
std::string * description
ns1__facility * facility
std::string * name
Public Attributes inherited from ICat4::ns1__entityBaseBean
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1703 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__datasetType()
ICat4::ns1__datasetType::ns1__datasetType () inline
Definition at line 1717 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__datasetType::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15049 of file ICat4C.cpp.
References datasets, description, facility, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), ICat4::ns1__entityBaseBean::soap_default(), and ICat4::soap_default_std__vectorTemplateOfPointerTons1__dataset().
Referenced by ICat4::soap_in_ns1__datasetType(), ICat4::soap_new_req_ns1__datasetType(), and ICat4::soap_new_set_ns1__datasetType().
soap_get()
void * ICat4::ns1__datasetType::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15210 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__datasetType().
soap_in()
void * ICat4::ns1__datasetType::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15102 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__datasetType().
Referenced by ICat4::soap_in_ns1__datasetType().
soap_out()
int ICat4::ns1__datasetType::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15071 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__datasetType().
Referenced by soap_put().
soap_put()
int ICat4::ns1__datasetType::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15203 of file ICat4C.cpp.
References ICat4::ns1__entityBaseBean::id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__datasetType.
soap_serialize()
void ICat4::ns1__datasetType::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 15059 of file ICat4C.cpp.
References datasets, description, facility, name, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::ns1__entityBaseBean::soap_serialize(), ICat4::soap_serialize_PointerTons1__facility(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_std__vectorTemplateOfPointerTons1__dataset().
Referenced by ICat4::soap_serialize_PointerTons1__datasetParameter().
soap_type()
int ICat4::ns1__datasetType::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1710 of file ICat4Stub.h.
Member Data Documentation
datasets
std::vector<ns1__dataset *> ICat4::ns1__datasetType::datasets
Definition at line 1705 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
description
std::string* ICat4::ns1__datasetType::description
Definition at line 1706 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
facility
ns1__facility* ICat4::ns1__datasetType::facility
Definition at line 1707 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
name
std::string* ICat4::ns1__datasetType::name
Definition at line 1708 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp