Mantid: Mantid::DataHandling::LoadRawHelper Class Reference
Mantid::DataHandling::LoadRawHelper Class Reference
Helper class for LoadRaw algorithms.
#include <LoadRawHelper.h>
Public Member Functions
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadRawHelper ()
Default constructor.
void loadRunParameters (const API::MatrixWorkspace_sptr &localWorkspace, ISISRAW *const =nullptr) const
Read in run parameters Public so that LoadRaw2 can use it.
const std::string name () const override
Algorithm's name for identification overriding a virtual method.
FILE * openRawFile (const std::string &fileName)
Opens Raw File.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification overriding a virtual method.
~LoadRawHelper () override
Destructor.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Static Public Member Functions
static API::WorkspaceGroup_sptr createGroupWorkspace ()
creates shared pointer to group workspace
static void createMonitorWorkspace (DataObjects::Workspace2D_sptr &monws_sptr, const DataObjects::Workspace2D_sptr &normalws_sptr, API::WorkspaceGroup_sptr &mongrp_sptr, const int64_t mwsSpecs, const int64_t nwsSpecs, const int64_t numberOfPeriods, const int64_t lengthIn, const std::string &title, API::Algorithm *const pAlg)
creates monitor workspace
static DataObjects::Workspace2D_sptr createWorkspace (const DataObjects::Workspace2D_sptr &ws_sptr, int64_t nVectors=-1, int64_t xLengthIn=-1, int64_t yLengthIn=-1)
creates shared pointer to workspace from parent workspace
static DataObjects::Workspace2D_sptr createWorkspace (int64_t nVectors, int64_t xlengthIn, int64_t ylengthIn, const std::string &title)
overloaded method to create shared pointer to workspace
static Types::Core::DateAndTime extractEndTime (ISISRAW &isisRaw)
Extract the end time from a raw file.
static Types::Core::DateAndTime extractStartTime (ISISRAW &isisRaw)
Extract the start time from a raw file.
static bool isExcludeMonitors (const std::string &monitorOption)
returns true if the Exclude Monitor option(property) selected
static bool isIncludeMonitors (const std::string &monitorOption)
returns true if the Include Monitor Option selected
static bool isSeparateMonitors (const std::string &monitorOption)
returns true if the Separate Monitor Option selected
static void ProcessLoadMonitorOptions (bool &bincludeMonitors, bool &bseparateMonitors, bool &bexcludeMonitors, const API::Algorithm *pAlgo)
The method to interpret LoadMonitors property options and convert then into boolean values.
static std::list< std::string > searchForLogFiles (const std::filesystem::path &pathToRawFile)
Search for the log files in the workspace, and output their names as a list.
static void setWorkspaceProperty (const DataObjects::Workspace2D_sptr &ws_sptr, const API::WorkspaceGroup_sptr &grpws_sptr, const int64_t period, bool bmonitors, API::Algorithm *const pAlg)
overloaded method to set the workspace property
static void setWorkspaceProperty (const std::string &propertyName, const std::string &title, const API::WorkspaceGroup_sptr &grpws_sptr, const DataObjects::Workspace2D_sptr &ws_sptr, int64_t numberOfPeriods, bool bMonitor, API::Algorithm *const pAlg)
sets the workspace property
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Protected Member Functions
specnum_t calculateWorkspaceSize ()
calculate workspace size
void calculateWorkspacesizes (const std::vector< specnum_t > &monitorSpecList, specnum_t &normalwsSpecs, specnum_t &monitorwsSpecs)
calculate workspace sizes if separate or exclude monitors are selected
void checkOptionalProperties ()
Validates the optional 'spectra to read' properties, if they have been set.
void createPeriodLogs (int64_t period, const DataObjects::Workspace2D_sptr &local_workspace)
Create the period specific logs.
std::vector< specnum_t > getmonitorSpectrumList (const API::SpectrumDetectorMapping &mapping)
gets the monitor spectrum list from the workspace
int getNumberofTimeRegimes ()
number of time regimes
float getProtonCharge () const
get proton charge from raw file
std::vector< std::shared_ptr< HistogramData::HistogramX > > getTimeChannels (const int64_t &regimes, const int64_t &lengthIn)
Constructs the time channel (X) vector(s)
void init () override
Overwrites Algorithm method.
void ioRaw (FILE *file, bool from_file)
calls isisRaw ioraw
ISISRAW2 & isisRaw () const
return an reference to the ISISRAW2 reader
void loadSpectra (FILE *file, const int &period, const int &total_specs, const DataObjects::Workspace2D_sptr &ws_sptr, const std::vector< std::shared_ptr< HistogramData::HistogramX > > &)
load the spectra
bool readData (FILE *file, int hist)
reads data
bool readData (FILE *file, int64_t hist)
void readTitle (FILE *file, std::string &title)
Reads title from the isisraw class.
void readworkspaceParameters (specnum_t &numberOfSpectra, int &numberOfPeriods, int64_t &lengthIn, int64_t &noTimeRegimes)
reads workspace parameters like number of histograms,size of vectors etc
void reset ()
resets the isisraw shared pointer
void runLoadInstrument (const std::string &fileName, const DataObjects::Workspace2D_sptr &, double, double)
loadinstrument Child Algorithm
void runLoadInstrumentFromRaw (const std::string &fileName, const DataObjects::Workspace2D_sptr &)
loadinstrumentfromraw algorithm
void runLoadLog (const std::string &fileName, const DataObjects::Workspace2D_sptr &, double, double)
load log algorithm
void runLoadMappingTable (const std::string &fileName, const DataObjects::Workspace2D_sptr &)
loadinstrumentfromraw Child Algorithm
void setOptionalProperties (const int &spec_min, const int &spec_max, const std::vector< int > &spec_list)
sets optional properties like spec_min,spec_max etc
void setProtonCharge (API::Run &run)
set proton charge
void setRunNumber (API::Run &run)
Stores the run number in the sample's logs.
void setWorkspaceData (const DataObjects::Workspace2D_sptr &newWorkspace, const std::vector< std::shared_ptr< HistogramData::HistogramX > > &timeChannelsVec, int64_t wsIndex, specnum_t nspecNum, int64_t noTimeRegimes, int64_t lengthIn, int64_t binStart)
This method sets the raw file data to workspace vectors.
void skipData (FILE *file, int hist)
skips histrogram data from raw file.
void skipData (FILE *file, int64_t hist)
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Protected Attributes
bool m_interval
Have the spectrum_min/max properties been set?
bool m_list
Has the spectrum_list property been set?
int m_numberOfPeriods
The number of periods in the raw file.
std::vector< specnum_t > m_spec_list
The value of the spectrum_list property.
specnum_t m_spec_max
The value of the spectrum_max property.
specnum_t m_spec_min
The value of the spectrum_min property.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Private Member Functions
void exec () override
Overwrites Algorithm method.
std::string extractLogName (const std::string &path)
Extract the log name from the path to the specific log file.
Static Private Member Functions
static std::string convertMonthLabelToIntStr (std::string month)
convert month label to int string
Private Attributes
bool m_bmspeclist
boolean for list spectra options
std::vector< std::string > m_cache_options
Allowed values for the cache property.
std::unique_ptr< ISISRAW2 > m_isis_raw
ISISRAW class instance which does raw file reading.
std::unique_ptr< API::ISISRunLogs > m_logCreator
A ptr to the log creator.
std::vector< specnum_t > m_monitordetectorList
a vector holding the indexes of monitors
specnum_t m_numberOfSpectra
number of spectra
double m_prog
The current value of the progress counter.
std::map< specnum_t, specnum_t > m_specTimeRegimes
A map for storing the time regime for each spectrum.
specnum_t m_total_specs
the total nuumber of spectra
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Helper class for LoadRaw algorithms.
Definition at line 38 of file LoadRawHelper.h.
Constructor & Destructor Documentation
LoadRawHelper()
Mantid::DataHandling::LoadRawHelper::LoadRawHelper ()
Default constructor.
Constructor.
Definition at line 101 of file LoadRawHelper.cpp.
~LoadRawHelper()
Mantid::DataHandling::LoadRawHelper::~LoadRawHelper () override default
Destructor.
Member Function Documentation
calculateWorkspaceSize()
specnum_t Mantid::DataHandling::LoadRawHelper::calculateWorkspaceSize () protected
calculate workspace size
Calculates the total number of spectra in the workspace, given the input properties.
Returns
the size of the workspace (number of spectra)
Definition at line 951 of file LoadRawHelper.cpp.
References m_interval, m_list, m_numberOfSpectra, m_spec_list, m_spec_max, m_spec_min, and m_total_specs.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), and Mantid::DataHandling::LoadRawBin0::exec().
calculateWorkspacesizes()
void Mantid::DataHandling::LoadRawHelper::calculateWorkspacesizes (const std::vector< specnum_t > & monitorSpecList, specnum_t & normalwsSpecs, specnum_t & monitorwsSpecs) protected
calculate workspace sizes if separate or exclude monitors are selected
calculate workspace sizes.
Parameters
monitorSpecList :: the vector of the monitor spectra
normalwsSpecs :: the spectra for the detector workspace
monitorwsSpecs :: the spectra for the monitor workspace
Definition at line 991 of file LoadRawHelper.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, m_bmspeclist, m_interval, m_spec_list, m_spec_max, m_spec_min, and m_total_specs.
Referenced by Mantid::DataHandling::LoadRaw3::exec().
checkOptionalProperties()
void Mantid::DataHandling::LoadRawHelper::checkOptionalProperties () protected
Validates the optional 'spectra to read' properties, if they have been set.
Definition at line 909 of file LoadRawHelper.cpp.
References Mantid::EMPTY_INT(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, m_bmspeclist, m_interval, m_list, m_numberOfSpectra, m_spec_list, m_spec_max, and m_spec_min.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), and Mantid::DataHandling::LoadRawBin0::exec().
confidence()
int Mantid::DataHandling::LoadRawHelper::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with which this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 1098 of file LoadRawHelper.cpp.
References confidence(), and Mantid::Kernel::FileDescriptor::data().
Referenced by confidence(), and Mantid::DataHandling::UpdateInstrumentFromFile::exec().
convertMonthLabelToIntStr()
std::string Mantid::DataHandling::LoadRawHelper::convertMonthLabelToIntStr (std::string month) static private
convert month label to int string
To help transforming date stored in ISIS raw file into iso 8601.
Parameters
month
Returns
month as string integer e.g. 01
Definition at line 867 of file LoadRawHelper.cpp.
Referenced by extractEndTime(), and extractStartTime().
createGroupWorkspace()
WorkspaceGroup_sptr Mantid::DataHandling::LoadRawHelper::createGroupWorkspace () static
creates shared pointer to group workspace
This method creates pointer to group workspace.
Returns
WorkspaceGroup_sptr shared pointer to the workspace
Definition at line 481 of file LoadRawHelper.cpp.
Referenced by createMonitorWorkspace(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
createMonitorWorkspace()
void Mantid::DataHandling::LoadRawHelper::createMonitorWorkspace (DataObjects::Workspace2D_sptr & monws_sptr, const DataObjects::Workspace2D_sptr & normalws_sptr, API::WorkspaceGroup_sptr & mongrp_sptr, const int64_t mwsSpecs, const int64_t nwsSpecs, const int64_t numberOfPeriods, const int64_t lengthIn, const std::string & title, API::Algorithm *const pAlg) static
creates monitor workspace
Parameters
monws_sptr :: shared pointer to monitor workspace
normalws_sptr :: shared pointer to output workspace
mongrp_sptr :: shared pointer to monitor group workspace
mwsSpecs :: number of spectra in the monitor workspace
nwsSpecs :: number of spectra in the output workspace
numberOfPeriods :: total number of periods from raw file
lengthIn :: size of workspace vectors
title :: title of the workspace
pAlg :: pointer to the algorithm, this method works with.
Definition at line 293 of file LoadRawHelper.cpp.
References createGroupWorkspace(), createWorkspace(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::declareProperty(), Mantid::API::Algorithm::getLogger(), Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Direction::Output, and setWorkspaceProperty().
Referenced by Mantid::DataHandling::LoadRaw3::exec().
createPeriodLogs()
void Mantid::DataHandling::LoadRawHelper::createPeriodLogs (int64_t period, const DataObjects::Workspace2D_sptr & local_workspace) protected
Create the period specific logs.
Creates period log data in the workspace.
Parameters
period :: period number
local_workspace :: workspace to add period log data to.
Definition at line 763 of file LoadRawHelper.cpp.
References m_logCreator.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
createWorkspace() [1/2]
DataObjects::Workspace2D_sptr Mantid::DataHandling::LoadRawHelper::createWorkspace (const DataObjects::Workspace2D_sptr & ws_sptr, int64_t nVectors = -1, int64_t xLengthIn = -1, int64_t yLengthIn = -1) static
creates shared pointer to workspace from parent workspace
This method creates shared pointer to a workspace.
Parameters
ws_sptr :: shared pointer to the parent workspace
nVectors :: number of histograms in the workspace
xLengthIn :: size of workspace X vector
yLengthIn :: size of workspace Y vector
Returns
an empty workspace of the given parameters
Definition at line 249 of file LoadRawHelper.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
Referenced by createMonitorWorkspace(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
createWorkspace() [2/2]
DataObjects::Workspace2D_sptr Mantid::DataHandling::LoadRawHelper::createWorkspace (int64_t nVectors, int64_t xlengthIn, int64_t ylengthIn, const std::string & title) static
overloaded method to create shared pointer to workspace
This method creates pointer to workspace.
Parameters
nVectors :: The number of vectors/histograms in the workspace
xlengthIn :: The number of X data points/bin boundaries in each vector
ylengthIn :: The number of Y data points/bin boundaries in each vector
title :: title of the workspace
Returns
Workspace2D_sptr shared pointer to the workspace
Definition at line 268 of file LoadRawHelper.cpp.
References Mantid::DataObjects::create(), Mantid::Kernel::SingletonHolder< T >::Instance(), and workspace.
exec()
void Mantid::DataHandling::LoadRawHelper::exec () override private virtual
Overwrites Algorithm method.
Executes the algorithm.
Reading in the file and creating and populating the output workspace
Exceptions
Exception::FileError If the RAW file cannot be found/opened
std::invalid_argument If the optional properties are set to invalid values
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadRawSpectrum0.
Definition at line 343 of file LoadRawHelper.cpp.
extractEndTime()
Types::Core::DateAndTime Mantid::DataHandling::LoadRawHelper::extractEndTime (ISISRAW & isisRaw) static
Extract the end time from a raw file.
Extracts the end time from the Raw file.
Parameters
isisRaw pointer to the raw file
Returns
the endtime
Definition at line 843 of file LoadRawHelper.cpp.
References convertMonthLabelToIntStr(), isisRaw(), RPB_STRUCT::r_enddate, RPB_STRUCT::r_endtime, and ISISRAW::rpb.
Referenced by loadRunParameters().
extractLogName()
std::string Mantid::DataHandling::LoadRawHelper::extractLogName (const std::string & path) private
Extract the log name from the path to the specific log file.
Extract the log name from the path to the log file.
Parameters
path :: Path to the log file
Returns
logName :: The name of the log file.
Definition at line 751 of file LoadRawHelper.cpp.
Referenced by runLoadLog().
extractStartTime()
Types::Core::DateAndTime Mantid::DataHandling::LoadRawHelper::extractStartTime (ISISRAW & isisRaw) static
Extract the start time from a raw file.
Extracts the start time from the Raw file.
Parameters
isisRaw pointer to the raw file
Returns
the start time
Definition at line 856 of file LoadRawHelper.cpp.
References convertMonthLabelToIntStr(), HDR_STRUCT::hd_date, HDR_STRUCT::hd_time, ISISRAW::hdr, and isisRaw().
Referenced by loadRunParameters().
getmonitorSpectrumList()
std::vector< specnum_t > Mantid::DataHandling::LoadRawHelper::getmonitorSpectrumList (const API::SpectrumDetectorMapping & mapping) protected
gets the monitor spectrum list from the workspace
This method returns the monitor spectrum list.
Parameters
mapping The spectrum number to detector mapping
Returns
monitorSpecList The spectrum numbers of the monitors
Definition at line 455 of file LoadRawHelper.cpp.
References Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, Mantid::API::SpectrumDetectorMapping::getMapping(), and m_monitordetectorList.
Referenced by Mantid::DataHandling::LoadRaw3::exec().
getNumberofTimeRegimes()
int Mantid::DataHandling::LoadRawHelper::getNumberofTimeRegimes () protected
number of time regimes
Definition at line 185 of file LoadRawHelper.cpp.
References ISISRAW::daep, isisRaw(), and DAEP_STRUCT::n_tr_shift.
Referenced by loadSpectra().
getProtonCharge()
float Mantid::DataHandling::LoadRawHelper::getProtonCharge () const protected
get proton charge from raw file
Definition at line 209 of file LoadRawHelper.cpp.
References isisRaw(), RPB_STRUCT::r_gd_prtn_chrg, and ISISRAW::rpb.
Referenced by setProtonCharge().
getTimeChannels()
std::vector< std::shared_ptr< HistogramData::HistogramX > > Mantid::DataHandling::LoadRawHelper::getTimeChannels (const int64_t & regimes, const int64_t & lengthIn) protected
Constructs the time channel (X) vector(s)
Parameters
regimes :: The number of time regimes (if 1 regime, will actually contain 0)
lengthIn :: The number of time channels
Returns
The vector(s) containing the time channel boundaries, in a vector of shared ptrs
Definition at line 490 of file LoadRawHelper.cpp.
References Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, ISISRAW::getTimeChannels(), isisRaw(), and m_specTimeRegimes.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
init()
void Mantid::DataHandling::LoadRawHelper::init () override protected virtual
Overwrites Algorithm method.
Initialisation method.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadRawSpectrum0.
Definition at line 110 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, m_cache_options, and Mantid::Kernel::Direction::Output.
Referenced by Mantid::DataHandling::LoadRaw3::init(), Mantid::DataHandling::LoadRawBin0::init(), and Mantid::DataHandling::LoadRawSpectrum0::init().
ioRaw()
void Mantid::DataHandling::LoadRawHelper::ioRaw (FILE * file, bool from_file) protected
calls isisRaw ioraw
calls isisRaw ioRaw.
Parameters
file :: the file pointer
from_file :: unknown
Definition at line 184 of file LoadRawHelper.cpp.
References ISISRAW2::ioRAW(), and isisRaw().
Referenced by readTitle().
isExcludeMonitors()
bool Mantid::DataHandling::LoadRawHelper::isExcludeMonitors (const std::string & monitorOption) static
returns true if the Exclude Monitor option(property) selected
This method checks the value of LoadMonitors property and returns true or false.
Returns
true if Exclude Monitors option is selected,otherwise false
Definition at line 1176 of file LoadRawHelper.cpp.
Referenced by ProcessLoadMonitorOptions().
isIncludeMonitors()
bool Mantid::DataHandling::LoadRawHelper::isIncludeMonitors (const std::string & monitorOption) static
returns true if the Include Monitor Option selected
This method checks the value of LoadMonitors property and returns true or false.
Returns
true if Include Monitors option is selected,otherwise false
Definition at line 1182 of file LoadRawHelper.cpp.
Referenced by ProcessLoadMonitorOptions().
isisRaw()
ISISRAW2 & Mantid::DataHandling::LoadRawHelper::isisRaw () const protected
return an reference to the ISISRAW2 reader
Lazy-instantiation of the ISISRAW reader.
Returns
A reference to the internal ISISRAW reader instance.
Definition at line 191 of file LoadRawHelper.cpp.
References m_isis_raw.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), extractEndTime(), extractStartTime(), getNumberofTimeRegimes(), getProtonCharge(), getTimeChannels(), ioRaw(), loadRunParameters(), loadSpectra(), readData(), readTitle(), readworkspaceParameters(), runLoadInstrument(), setRunNumber(), setWorkspaceData(), and skipData().
isSeparateMonitors()
bool Mantid::DataHandling::LoadRawHelper::isSeparateMonitors (const std::string & monitorOption) static
returns true if the Separate Monitor Option selected
This method checks the value of LoadMonitors property and returns true or false.
Returns
true if Separate Monitors option is selected,otherwise false
Definition at line 1188 of file LoadRawHelper.cpp.
Referenced by ProcessLoadMonitorOptions().
loadRunParameters()
void Mantid::DataHandling::LoadRawHelper::loadRunParameters (const API::MatrixWorkspace_sptr & localWorkspace, ISISRAW * const rawFile = nullptr) const
Read in run parameters Public so that LoadRaw2 can use it.
Pulls the run parameters from the ISIS Raw RPB structure and stores them as log entries on the workspace run object.
Parameters
localWorkspace :: The workspace to attach the information to
rawFile :: The handle to an ISIS Raw file
Definition at line 774 of file LoadRawHelper.cpp.
References Mantid::API::LogManager::addProperty(), extractEndTime(), extractStartTime(), HDR_STRUCT::hd_dur, HDR_STRUCT::hd_user, ISISRAW::hdr, HDR_STRUCT::inst_abrv, isisRaw(), RPB_STRUCT::r_dmp, RPB_STRUCT::r_dmp_freq, RPB_STRUCT::r_dmp_units, RPB_STRUCT::r_dur, RPB_STRUCT::r_dur_freq, RPB_STRUCT::r_dur_secs, RPB_STRUCT::r_dur_wanted, RPB_STRUCT::r_durunits, RPB_STRUCT::r_freq, RPB_STRUCT::r_gd_prtn_chrg, RPB_STRUCT::r_goodfrm, RPB_STRUCT::r_mon_sum1, RPB_STRUCT::r_mon_sum2, RPB_STRUCT::r_mon_sum3, RPB_STRUCT::r_prop, RPB_STRUCT::r_rawfrm, RPB_STRUCT::r_tot_prtn_chrg, ISISRAW::rpb, Mantid::DataHandling::RawFileInfo::runHeader(), Mantid::DataHandling::RawFileInfo::runTitle(), ISISRAW::t_nper, ISISRAW::t_nsp1, and ISISRAW::t_ntc1.
Referenced by Mantid::DataHandling::LoadRaw3::exec().
loadSpectra()
void Mantid::DataHandling::LoadRawHelper::loadSpectra (FILE * file, const int & period, const int & total_specs, const DataObjects::Workspace2D_sptr & ws_sptr, const std::vector< std::shared_ptr< HistogramData::HistogramX > > & timeChannelsVec) protected
load the spectra
Definition at line 1050 of file LoadRawHelper.cpp.
References getNumberofTimeRegimes(), Mantid::API::Algorithm::interruption_point(), isisRaw(), m_list, m_numberOfSpectra, m_prog, m_spec_list, m_spec_max, m_spec_min, Mantid::API::Algorithm::progress(), readData(), setWorkspaceData(), and skipData().
name()
const std::string Mantid::DataHandling::LoadRawHelper::name () const inline override virtual
Algorithm's name for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadRawSpectrum0.
Definition at line 46 of file LoadRawHelper.h.
openRawFile()
FILE * Mantid::DataHandling::LoadRawHelper::openRawFile (const std::string & fileName)
Opens Raw File.
opens the raw file and returns the file pointer
Parameters
fileName :: name of the raw file
Returns
file pointer
Definition at line 147 of file LoadRawHelper.cpp.
References Mantid::Kernel::FileDescriptor::isAscii().
Referenced by Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
ProcessLoadMonitorOptions()
void Mantid::DataHandling::LoadRawHelper::ProcessLoadMonitorOptions (bool & bincludeMonitors, bool & bseparateMonitors, bool & bexcludeMonitors, const API::Algorithm * pAlgo) static
The method to interpret LoadMonitors property options and convert then into boolean values.
Parameters
bincludeMonitors :: if monitors requested to be included with workspace
bseparateMonitors :: if monitors requested to be loaded separately from the workspace
bexcludeMonitors :: if monitors should not be loaded at all.
pAlgo :: pointer to the algorithm, which has LoadMonitors property.
Definition at line 1199 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::getProperty(), isExcludeMonitors(), isIncludeMonitors(), and isSeparateMonitors().
Referenced by Mantid::DataHandling::LoadISISNexus2::exec(), and Mantid::DataHandling::LoadRaw3::exec().
readData() [1/2]
bool Mantid::DataHandling::LoadRawHelper::readData (FILE * file, int hist) protected
reads data
reads the histogram from raw file
Parameters
file :: pointer to the raw file
hist :: postion in the file to read
Returns
flag is data is read
Definition at line 206 of file LoadRawHelper.cpp.
References isisRaw(), and ISISRAW2::readData().
Referenced by Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), readData(), and Mantid::DataHandling::LoadRaw3::separateMonitors().
readData() [2/2]
bool Mantid::DataHandling::LoadRawHelper::readData (FILE * file, int64_t hist) protected
Definition at line 207 of file LoadRawHelper.cpp.
References readData().
readTitle()
void Mantid::DataHandling::LoadRawHelper::readTitle (FILE * file, std::string & title) protected
Reads title from the isisraw class.
Reads the run title and creates a string from it.
Parameters
file :: pointer to the raw file
title :: An output parameter that will contain the workspace title
Definition at line 170 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), ioRaw(), and isisRaw().
Referenced by Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
readworkspaceParameters()
void Mantid::DataHandling::LoadRawHelper::readworkspaceParameters (specnum_t & numberOfSpectra, int & numberOfPeriods, int64_t & lengthIn, int64_t & noTimeRegimes) protected
reads workspace parameters like number of histograms,size of vectors etc
reads workspace dimensions,number of periods etc from raw data
Parameters
numberOfSpectra :: number of spectra
numberOfPeriods :: number of periods
lengthIn :: size of workspace vectors
noTimeRegimes :: number of time regime.
Definition at line 229 of file LoadRawHelper.cpp.
References ISISRAW::daep, isisRaw(), m_numberOfSpectra, DAEP_STRUCT::n_tr_shift, ISISRAW::t_nper, ISISRAW::t_nsp1, and ISISRAW::t_ntc1.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
reset()
void Mantid::DataHandling::LoadRawHelper::reset () protected
resets the isisraw shared pointer
Definition at line 199 of file LoadRawHelper.cpp.
References m_isis_raw.
Referenced by Mantid::DataHandling::LoadRaw3::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
runLoadInstrument()
void Mantid::DataHandling::LoadRawHelper::runLoadInstrument (const std::string & fileName, const DataObjects::Workspace2D_sptr & localWorkspace, double progStart, double progEnd) protected
loadinstrument Child Algorithm
Run the Child Algorithm LoadInstrument (or LoadInstrumentFromRaw)
Parameters
fileName :: the raw file filename
localWorkspace :: The workspace to load the instrument for
progStart :: progress at start
progEnd :: progress at end
Definition at line 538 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::API::Algorithm::g_log, ISISRAW::i_inst, Mantid::Kernel::Logger::information(), isisRaw(), m_monitordetectorList, m_prog, Mantid::API::Algorithm::progress(), Mantid::API::Algorithm::progressObserver(), runLoadInstrumentFromRaw(), Mantid::API::Algorithm::setChildEndProgress(), Mantid::API::Algorithm::setChildStartProgress(), and value.
Referenced by Mantid::DataHandling::LoadRaw3::exec().
runLoadInstrumentFromRaw()
void Mantid::DataHandling::LoadRawHelper::runLoadInstrumentFromRaw (const std::string & fileName, const DataObjects::Workspace2D_sptr & localWorkspace) protected
loadinstrumentfromraw algorithm
Run LoadInstrumentFromRaw as a Child Algorithm (only if loading from instrument definition file fails)
Parameters
fileName :: the raw file filename
localWorkspace :: The workspace to load the instrument for
Definition at line 618 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, and m_monitordetectorList.
Referenced by runLoadInstrument().
runLoadLog()
void Mantid::DataHandling::LoadRawHelper::runLoadLog (const std::string & fileName, const DataObjects::Workspace2D_sptr & localWorkspace, double progStart, double progEnd) protected
load log algorithm
Run the LoadLog Child Algorithm.
Parameters
fileName :: the raw file filename
localWorkspace :: The workspace to load the logs for
progStart :: starting progress fraction
progEnd :: ending progress fraction
Definition at line 670 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), extractLogName(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), Mantid::Kernel::FileDescriptor::isEmpty(), m_logCreator, m_prog, Mantid::API::Algorithm::progress(), Mantid::API::Algorithm::progressObserver(), searchForLogFiles(), Mantid::API::Algorithm::setChildEndProgress(), Mantid::API::Algorithm::setChildStartProgress(), and Mantid::Kernel::Logger::warning().
Referenced by Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
runLoadMappingTable()
void Mantid::DataHandling::LoadRawHelper::runLoadMappingTable (const std::string & fileName, const DataObjects::Workspace2D_sptr & localWorkspace) protected
loadinstrumentfromraw Child Algorithm
Run the LoadMappingTable Child Algorithm to fill the SpectraToDetectorMap.
Parameters
fileName :: the raw file filename
localWorkspace :: The workspace to load the mapping table for
Definition at line 644 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::Kernel::Logger::debug(), Mantid::Kernel::Logger::error(), Mantid::API::Algorithm::g_log, m_prog, and Mantid::API::Algorithm::progress().
searchForLogFiles()
std::list< std::string > Mantid::DataHandling::LoadRawHelper::searchForLogFiles (const std::filesystem::path & pathToRawFile) static
Search for the log files in the workspace, and output their names as a list.
Searches for log files related to RAW file loaded using LoadLog algorithm.
Parameters
pathToRawFile The path and name of the raw file.
Returns
A set containing paths to log files related to RAW file used.
read list of log files from alternate data stream
Definition at line 1118 of file LoadRawHelper.cpp.
References Mantid::Kernel::Glob::glob().
Referenced by runLoadLog().
setOptionalProperties()
void Mantid::DataHandling::LoadRawHelper::setOptionalProperties (const int & spec_min, const int & spec_max, const std::vector< int > & spec_list) protected
sets optional properties like spec_min,spec_max etc
sets optional properties for the loadraw algorithm
Parameters
spec_min :: The minimum spectra number
spec_max :: The maximum spectra number
spec_list :: The list of Spectra to be included
Definition at line 902 of file LoadRawHelper.cpp.
References m_spec_list, m_spec_max, and m_spec_min.
setProtonCharge()
void Mantid::DataHandling::LoadRawHelper::setProtonCharge (API::Run & run) protected
set proton charge
Set the proton charge on the run object.
Parameters
run :: The run object
Definition at line 215 of file LoadRawHelper.cpp.
References getProtonCharge(), and Mantid::API::Run::setProtonCharge().
Referenced by Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
setRunNumber()
void Mantid::DataHandling::LoadRawHelper::setRunNumber (API::Run & run) protected
Stores the run number in the sample's logs.
Stores the run number in the run logs.
Parameters
run :: the workspace's run object
Definition at line 219 of file LoadRawHelper.cpp.
References Mantid::API::LogManager::addLogData(), isisRaw(), and std::to_string().
Referenced by Mantid::DataHandling::LoadRaw3::exec().
setWorkspaceData()
void Mantid::DataHandling::LoadRawHelper::setWorkspaceData (const DataObjects::Workspace2D_sptr & newWorkspace, const std::vector< std::shared_ptr< HistogramData::HistogramX > > & timeChannelsVec, int64_t wsIndex, specnum_t nspecNum, int64_t noTimeRegimes, int64_t lengthIn, int64_t binStart) protected
This method sets the raw file data to workspace vectors.
Parameters
newWorkspace :: shared pointer to the workspace
timeChannelsVec :: vector holding the X data
wsIndex variable used for indexing the output workspace
nspecNum spectrum number
noTimeRegimes :: regime no.
lengthIn :: length of the workspace
binStart :: start of bin
Definition at line 417 of file LoadRawHelper.cpp.
References isisRaw(), m_specTimeRegimes, and Mantid::Geometry::Y.
Referenced by Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), and Mantid::DataHandling::LoadRaw3::separateMonitors().
setWorkspaceProperty() [1/2]
void Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty (const DataObjects::Workspace2D_sptr & ws_sptr, const API::WorkspaceGroup_sptr & grpws_sptr, const int64_t period, bool bmonitors, API::Algorithm *const pAlg) static
overloaded method to set the workspace property
sets the workspace properties
Parameters
ws_sptr :: shared pointer to workspace
grpws_sptr :: shared pointer to group workspace
period period number
bmonitors :: boolean flag to name the workspaces
pAlg :: pointer to algorithm this method works with.
Definition at line 352 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::Algorithm::getProperty(), Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setProperty().
setWorkspaceProperty() [2/2]
void Mantid::DataHandling::LoadRawHelper::setWorkspaceProperty (const std::string & propertyName, const std::string & title, const API::WorkspaceGroup_sptr & grpws_sptr, const DataObjects::Workspace2D_sptr & ws_sptr, int64_t numberOfPeriods, bool bMonitor, API::Algorithm *const pAlg) static
sets the workspace property
This method sets the workspace property.
Parameters
propertyName :: property name for the workspace
title :: title of the workspace
grpws_sptr :: shared pointer to group workspace
ws_sptr :: shared pointer to workspace
numberOfPeriods :: number periods in the raw file
bMonitor to identify the workspace is an output workspace or monitor workspace
pAlg :: pointer to algorithm this method works with.
Definition at line 388 of file LoadRawHelper.cpp.
References Mantid::API::Algorithm::getProperty(), and Mantid::Kernel::IPropertyManager::setProperty().
Referenced by createMonitorWorkspace(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), and Mantid::DataHandling::LoadRawSpectrum0::exec().
skipData() [1/2]
void Mantid::DataHandling::LoadRawHelper::skipData (FILE * file, int hist) protected
skips histrogram data from raw file.
skips the histogram from raw file
Parameters
file :: pointer to the raw file
hist :: postion in the file to skip
Definition at line 179 of file LoadRawHelper.cpp.
References isisRaw(), and ISISRAW2::skipData().
Referenced by Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), Mantid::DataHandling::LoadRaw3::separateMonitors(), skipData(), and Mantid::DataHandling::LoadRaw3::skipPeriod().
skipData() [2/2]
void Mantid::DataHandling::LoadRawHelper::skipData (FILE * file, int64_t hist) protected
Definition at line 180 of file LoadRawHelper.cpp.
References skipData().
summary()
const std::string Mantid::DataHandling::LoadRawHelper::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadRawSpectrum0.
Definition at line 50 of file LoadRawHelper.h.
version()
int Mantid::DataHandling::LoadRawHelper::version () const inline override virtual
Algorithm's version for identification overriding a virtual method.
Implements Mantid::API::Algorithm.
Reimplemented in Mantid::DataHandling::LoadRawSpectrum0.
Definition at line 48 of file LoadRawHelper.h.
Member Data Documentation
m_bmspeclist
bool Mantid::DataHandling::LoadRawHelper::m_bmspeclist private
boolean for list spectra options
Definition at line 210 of file LoadRawHelper.h.
Referenced by calculateWorkspacesizes(), and checkOptionalProperties().
m_cache_options
std::vector<std::string> Mantid::DataHandling::LoadRawHelper::m_cache_options private
Allowed values for the cache property.
Definition at line 197 of file LoadRawHelper.h.
Referenced by init().
m_interval
bool Mantid::DataHandling::LoadRawHelper::m_interval protected
Have the spectrum_min/max properties been set?
Definition at line 178 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), calculateWorkspacesizes(), and checkOptionalProperties().
m_isis_raw
std::unique_ptr<ISISRAW2> Mantid::DataHandling::LoadRawHelper::m_isis_raw mutable private
ISISRAW class instance which does raw file reading.
Definition at line 195 of file LoadRawHelper.h.
Referenced by isisRaw(), and reset().
m_list
bool Mantid::DataHandling::LoadRawHelper::m_list protected
Has the spectrum_list property been set?
Definition at line 176 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), and Mantid::DataHandling::LoadRaw3::separateMonitors().
m_logCreator
std::unique_ptr<API::ISISRunLogs> Mantid::DataHandling::LoadRawHelper::m_logCreator private
A ptr to the log creator.
Definition at line 216 of file LoadRawHelper.h.
Referenced by createPeriodLogs(), and runLoadLog().
m_monitordetectorList
std::vector<specnum_t> Mantid::DataHandling::LoadRawHelper::m_monitordetectorList private
a vector holding the indexes of monitors
Definition at line 207 of file LoadRawHelper.h.
Referenced by getmonitorSpectrumList(), runLoadInstrument(), and runLoadInstrumentFromRaw().
m_numberOfPeriods
int Mantid::DataHandling::LoadRawHelper::m_numberOfPeriods protected
The number of periods in the raw file.
Definition at line 186 of file LoadRawHelper.h.
Referenced by Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), Mantid::DataHandling::LoadRaw3::separateMonitors(), and Mantid::DataHandling::LoadRaw3::setOptionalProperties().
m_numberOfSpectra
specnum_t Mantid::DataHandling::LoadRawHelper::m_numberOfSpectra private
number of spectra
Definition at line 204 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), checkOptionalProperties(), loadSpectra(), and readworkspaceParameters().
m_prog
double Mantid::DataHandling::LoadRawHelper::m_prog private
The current value of the progress counter.
Definition at line 201 of file LoadRawHelper.h.
Referenced by loadSpectra(), runLoadInstrument(), runLoadLog(), and runLoadMappingTable().
m_spec_list
std::vector<specnum_t> Mantid::DataHandling::LoadRawHelper::m_spec_list protected
The value of the spectrum_list property.
Definition at line 180 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), calculateWorkspacesizes(), checkOptionalProperties(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), Mantid::DataHandling::LoadRaw3::separateMonitors(), Mantid::DataHandling::LoadRaw3::setOptionalProperties(), Mantid::DataHandling::LoadRawBin0::setOptionalProperties(), and setOptionalProperties().
m_spec_max
specnum_t Mantid::DataHandling::LoadRawHelper::m_spec_max protected
The value of the spectrum_max property.
Definition at line 184 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), calculateWorkspacesizes(), checkOptionalProperties(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), Mantid::DataHandling::LoadRaw3::separateMonitors(), Mantid::DataHandling::LoadRaw3::setOptionalProperties(), Mantid::DataHandling::LoadRawBin0::setOptionalProperties(), and setOptionalProperties().
m_spec_min
specnum_t Mantid::DataHandling::LoadRawHelper::m_spec_min protected
The value of the spectrum_min property.
Definition at line 182 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), calculateWorkspacesizes(), checkOptionalProperties(), Mantid::DataHandling::LoadRaw3::excludeMonitors(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRaw3::includeMonitors(), loadSpectra(), Mantid::DataHandling::LoadRaw3::separateMonitors(), Mantid::DataHandling::LoadRaw3::setOptionalProperties(), Mantid::DataHandling::LoadRawBin0::setOptionalProperties(), and setOptionalProperties().
m_specTimeRegimes
std::map<specnum_t, specnum_t> Mantid::DataHandling::LoadRawHelper::m_specTimeRegimes private
A map for storing the time regime for each spectrum.
Definition at line 199 of file LoadRawHelper.h.
Referenced by getTimeChannels(), and setWorkspaceData().
m_total_specs
specnum_t Mantid::DataHandling::LoadRawHelper::m_total_specs private
the total nuumber of spectra
Definition at line 213 of file LoadRawHelper.h.
Referenced by calculateWorkspaceSize(), and calculateWorkspacesizes().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadRawHelper.h
Framework/DataHandling/src/LoadRawHelper.cpp