Mantid: Mantid::PythonInterface::DataProcessorAdapter< Base > Class Template Reference
Mantid::PythonInterface::DataProcessorAdapter< Base > Class Template Reference
Provides a layer class for boost::python to allow C++ virtual functions to be overridden in a Python object that is derived an DataProcessorAlgorithm.
#include <DataProcessorAdapter.h>
Public Member Functions
API::Workspace_sptr assembleProxy (const std::string &partialWSName, const std::string &outputWSName)
void copyPropertiesProxy (const std::string &algName, const boost::python::object &propNames, const int version=-1)
DataProcessorAdapter ()=delete
Disable default constructor - The PyObject must be supplied to construct the object.
DataProcessorAdapter (const DataProcessorAdapter &)=delete
Disable copy operator.
DataProcessorAdapter (PyObject *self)
A constructor that looks like a Python init method.
API::ITableWorkspace_sptr determineChunkProxy (const std::string &filename)
void forwardPropertiesProxy ()
int getNThreadsProxy ()
std::shared_ptr< Kernel::PropertyManager > getProcessPropertiesProxy (const std::string &propertyManager=std::string())
bool isMainThreadProxy ()
void loadChunkProxy (const size_t rowIndex)
API::Workspace_sptr loadProxy (const std::string &inputData, const bool loadQuiet=false)
DataProcessorAdapter & operator= (const DataProcessorAdapter &)=delete
Disable assignment operator.
void saveNexusProxy (const std::string &outputWSName, const std::string &outputFile)
void setAccumAlgProxy (const std::string &alg)
void setLoadAlgFilePropProxy (const std::string &filePropName)
void setLoadAlgProxy (const std::string &alg)
std::vector< std::string > splitInputProxy (const std::string &input)
Public Member Functions inherited from Mantid::PythonInterface::AlgorithmAdapter< API::GenericDataProcessorAlgorithm< Base > >
AlgorithmAdapter ()=delete
Disable default constructor - The PyObject must be supplied to construct the object.
AlgorithmAdapter (const AlgorithmAdapter &)=delete
Disable copy operator.
AlgorithmAdapter (PyObject *self)
A constructor that looks like a Python init method.
AlgorithmAdapter & operator= (const AlgorithmAdapter &)=delete
Disable assignment operator.
void setWikiSummary (const std::string &summary)
Set the summary text.
const std::string name () const override
Returns the name of the algorithm.
int version () const override
Returns a version of the algorithm.
const std::string summary () const override
Returns the summary for the algorithm.
const std::string category () const override
Returns a category of the algorithm.
const std::vector< std::string > seeAlso () const override
Returns seeAlso related algorithms.
const std::string alias () const override
Allow the method returning the algorithm aliases to be overridden.
const std::string aliasDeprecated () const override
Returns optional documentation URL of the algorithm.
const std::string helpURL () const override
Optional documentation URL of the algorithm, empty string if not overridden.
bool isRunning () const override
Allow the isRunning method to be overridden.
void cancel () override
Allow the cancel method to be overridden.
bool checkGroups () override
A return of false will allow processing workspace groups as a whole.
std::map< std::string, std::string > validateInputs () override
Returns the validateInputs result of the algorithm.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Additional Inherited Members
Static Public Member Functions inherited from Mantid::PythonInterface::AlgorithmAdapter< API::GenericDataProcessorAlgorithm< Base > >
static void declarePyAlgProperty (boost::python::object &self, Kernel::Property *prop, const std::string &doc="")
Declare a preconstructed property.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const boost::python::object &validator=boost::python::object(), const std::string &doc="", const int direction=Kernel::Direction::Input)
Declare a property using the type of the defaultValue with a validator and doc string.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const std::string &doc, const int direction=Kernel::Direction::Input)
Declare a property with a documentation string.
static void declarePyAlgProperty (boost::python::object &self, const std::string &name, const boost::python::object &defaultValue, const int direction)
Declare a property using the type of the defaultValue.
Protected Member Functions inherited from Mantid::PythonInterface::AlgorithmAdapter< API::GenericDataProcessorAlgorithm< Base > >
PyObject * getSelf () const
Returns the PyObject that owns this wrapper, i.e.
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
Workspace_sptr assemble (const std::string &partialWSName, const std::string &outputWSName)
Assemble the partial workspaces from all MPI processes.
Workspace_sptr assemble (Workspace_sptr partialWS)
Assemble the partial workspaces from all MPI processes.
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
int getNThreads ()
Return the number of MPI processes running.
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
bool isMainThread ()
Return true if we are running on the main thread.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Protected Attributes inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
bool m_useMPI
MPI option. If false, we will use one job event if MPI is available.
Detailed Description
template<class Base>
class Mantid::PythonInterface::DataProcessorAdapter< Base >
Provides a layer class for boost::python to allow C++ virtual functions to be overridden in a Python object that is derived an DataProcessorAlgorithm.
It also provides access to the protected methods on DataProcessorAlgorithm from the type exported to Python
Definition at line 28 of file DataProcessorAdapter.h.
Constructor & Destructor Documentation
DataProcessorAdapter() [1/3]
template<class Base > Mantid::PythonInterface::DataProcessorAdapter< Base >::DataProcessorAdapter (PyObject * self)
A constructor that looks like a Python init method.
Construct the "wrapper" and stores the reference to the PyObject.
Parameters
self A reference to the calling Python object
Definition at line 19 of file DataProcessorAdapter.cpp.
DataProcessorAdapter() [2/3]
template<class Base > Mantid::PythonInterface::DataProcessorAdapter< Base >::DataProcessorAdapter () delete
Disable default constructor - The PyObject must be supplied to construct the object.
DataProcessorAdapter() [3/3]
template<class Base > Mantid::PythonInterface::DataProcessorAdapter< Base >::DataProcessorAdapter (const DataProcessorAdapter< Base > &) delete
Disable copy operator.
Member Function Documentation
assembleProxy()
template<class Base > API::Workspace_sptr Mantid::PythonInterface::DataProcessorAdapter< Base >::assembleProxy (const std::string & partialWSName, const std::string & outputWSName) inline
Definition at line 101 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::assemble().
copyPropertiesProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::copyPropertiesProxy (const std::string & algName, const boost::python::object & propNames, const int version = -1) inline
Definition at line 61 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::copyProperty(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::PythonInterface::isNone(), Mantid::PythonInterface::AlgorithmAdapter< API::GenericDataProcessorAlgorithm< Base > >::name(), and Mantid::PythonInterface::AlgorithmAdapter< API::GenericDataProcessorAlgorithm< Base > >::version().
determineChunkProxy()
template<class Base > API::ITableWorkspace_sptr Mantid::PythonInterface::DataProcessorAdapter< Base >::determineChunkProxy (const std::string & filename) inline
Definition at line 57 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::determineChunk().
forwardPropertiesProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::forwardPropertiesProxy () inline
Definition at line 94 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::forwardProperties().
getNThreadsProxy()
template<class Base > int Mantid::PythonInterface::DataProcessorAdapter< Base >::getNThreadsProxy () inline
Definition at line 111 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getNThreads().
getProcessPropertiesProxy()
template<class Base > std::shared_ptr< Kernel::PropertyManager > Mantid::PythonInterface::DataProcessorAdapter< Base >::getProcessPropertiesProxy (const std::string & propertyManager = std::string()) inline
Definition at line 97 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::getProcessProperties().
isMainThreadProxy()
template<class Base > bool Mantid::PythonInterface::DataProcessorAdapter< Base >::isMainThreadProxy () inline
Definition at line 109 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::isMainThread().
loadChunkProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::loadChunkProxy (const size_t rowIndex) inline
Definition at line 59 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::loadChunk().
loadProxy()
template<class Base > API::Workspace_sptr Mantid::PythonInterface::DataProcessorAdapter< Base >::loadProxy (const std::string & inputData, const bool loadQuiet = false) inline
Definition at line 88 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::load().
operator=()
template<class Base > DataProcessorAdapter & Mantid::PythonInterface::DataProcessorAdapter< Base >::operator= (const DataProcessorAdapter< Base > &) delete
Disable assignment operator.
saveNexusProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::saveNexusProxy (const std::string & outputWSName, const std::string & outputFile) inline
Definition at line 105 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::saveNexus().
setAccumAlgProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::setAccumAlgProxy (const std::string & alg) inline
Definition at line 55 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::setAccumAlg().
setLoadAlgFilePropProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::setLoadAlgFilePropProxy (const std::string & filePropName) inline
Definition at line 53 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::setLoadAlgFileProp().
setLoadAlgProxy()
template<class Base > void Mantid::PythonInterface::DataProcessorAdapter< Base >::setLoadAlgProxy (const std::string & alg) inline
Definition at line 51 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::setLoadAlg().
splitInputProxy()
template<class Base > std::vector< std::string > Mantid::PythonInterface::DataProcessorAdapter< Base >::splitInputProxy (const std::string & input) inline
Definition at line 92 of file DataProcessorAdapter.h.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::splitInput().
The documentation for this class was generated from the following files:
Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/PythonAlgorithm/DataProcessorAdapter.h
Framework/PythonInterface/mantid/api/src/PythonAlgorithm/DataProcessorAdapter.cpp