Mantid: ICat4::ns1__parameterValueType_ Class Reference
ICat4::ns1__parameterValueType_ Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__parameterValueType_ ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
enum ns1__parameterValueType __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 278 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__parameterValueType_()
ICat4::ns1__parameterValueType_::ns1__parameterValueType_ () inline
Definition at line 290 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__parameterValueType_::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5393 of file ICat4C.cpp.
References __item, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_ns1__parameterValueType().
Referenced by ICat4::soap_in_ns1__parameterValueType_(), ICat4::soap_new_req_ns1__parameterValueType_(), and ICat4::soap_new_set_ns1__parameterValueType_().
soap_get()
void * ICat4::ns1__parameterValueType_::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5452 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__parameterValueType_().
soap_in()
void * ICat4::ns1__parameterValueType_::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5417 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__parameterValueType_().
Referenced by ICat4::soap_in_ns1__parameterValueType_().
soap_out()
int ICat4::ns1__parameterValueType_::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5407 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__parameterValueType_().
Referenced by soap_put().
soap_put()
int ICat4::ns1__parameterValueType_::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5445 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__parameterValueType_.
soap_serialize()
void ICat4::ns1__parameterValueType_::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 5399 of file ICat4C.cpp.
References __item, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), and SOAP_TYPE_ICat4_ns1__parameterValueType.
soap_type()
int ICat4::ns1__parameterValueType_::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 283 of file ICat4Stub.h.
Member Data Documentation
__item
enum ns1__parameterValueType ICat4::ns1__parameterValueType_::__item
Definition at line 280 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp