Mantid: Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection Class Reference
Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection Class Reference
Performs beam flux correction on TOF SANS data.
#include <SANSBeamFluxCorrection.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithm's name.
const std::vector< std::string > seeAlso () const override
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version.
Public Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
GenericDataProcessorAlgorithm ()
Constructor.
Kernel::IPropertyManager::TypedValue getProperty (const std::string &name) const override
Get the property held by this object.
std::string getPropertyValue (const std::string &name) const override
Get the property held by this object.
Private Member Functions
void exec () override
Execution code.
void execEvent ()
void init () override
Initialisation code.
API::MatrixWorkspace_sptr loadReference ()
It's assumed that both the flux reference files are simple Nexus files since they have to produced by hand by the instrument scientists.
Private Attributes
std::string m_output_message
std::shared_ptr< Kernel::PropertyManager > m_reductionManager
Additional Inherited Members
Protected Member Functions inherited from Mantid::API::GenericDataProcessorAlgorithm< Base >
void copyProperty (const API::Algorithm_sptr &alg, const std::string &name)
Copy a property from an existing algorithm.
std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1) override
Create a Child Algorithm.
virtual ITableWorkspace_sptr determineChunk (const std::string &filename)
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Divide a matrix workspace by a single value.
MatrixWorkspace_sptr divide (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Divide a matrix workspace by another matrix workspace.
void forwardProperties ()
std::shared_ptr< Kernel::PropertyManager > getProcessProperties (const std::string &propertyManager=std::string()) const
Get the property manager object of a given name from the property manager data service, or create a new one.
Workspace_sptr load (const std::string &inputData, const bool loadQuiet=false)
Determine what kind of input data we have and load it.
virtual MatrixWorkspace_sptr loadChunk (const size_t rowIndex)
void mapPropertyName (const std::string &nameInProp, const std::string &nameInPropManager)
Declare mapping of property name to name in the PropertyManager.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Subract a single value from a matrix workspace.
MatrixWorkspace_sptr minus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Subract a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Multiply a matrix workspace by a single value.
MatrixWorkspace_sptr multiply (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Multiply a matrix workspace by another matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const double &rhsValue)
Add a single value to a matrix workspace.
MatrixWorkspace_sptr plus (const MatrixWorkspace_sptr lhs, const MatrixWorkspace_sptr rhs)
Add a matrix workspace to another matrix workspace.
void saveNexus (const std::string &outputWSName, const std::string &outputFile)
Save a workspace as a nexus file, with check for which thread we are executing in.
void setAccumAlg (const std::string &alg)
void setLoadAlg (const std::string &alg)
void setLoadAlgFileProp (const std::string &filePropName)
void setPropManagerPropName (const std::string &propName)
std::vector< std::string > splitInput (const std::string &input)
Detailed Description
Performs beam flux correction on TOF SANS data.
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 22 of file SANSBeamFluxCorrection.h.
Member Function Documentation
category()
const std::string Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::category () const inline override
Algorithm's category for identification.
Definition at line 32 of file SANSBeamFluxCorrection.h.
exec()
void Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::exec () override private
Execution code.
Definition at line 39 of file SANSBeamFluxCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProcessProperties(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getProperty(), loadReference(), m_output_message, m_reductionManager, Mantid::Kernel::ProgressBase::report(), and Mantid::Kernel::toString().
execEvent()
void Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::execEvent () private
init()
void Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::init () override private
Initialisation code.
Definition at line 23 of file SANSBeamFluxCorrection.cpp.
References Mantid::Kernel::Direction::Input, Mantid::API::FileProperty::Load, and Mantid::Kernel::Direction::Output.
loadReference()
MatrixWorkspace_sptr Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::loadReference () private
It's assumed that both the flux reference files are simple Nexus files since they have to produced by hand by the instrument scientists.
A simple Load algorithm should suffice.
Definition at line 105 of file SANSBeamFluxCorrection.cpp.
References Mantid::API::GenericDataProcessorAlgorithm< Base >::createChildAlgorithm(), Mantid::API::GenericDataProcessorAlgorithm< Base >::getPropertyValue(), Mantid::Kernel::Direction::InOut, m_output_message, and m_reductionManager.
Referenced by exec().
name()
const std::string Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::name () const inline override
Algorithm's name.
Definition at line 25 of file SANSBeamFluxCorrection.h.
seeAlso()
const std::vector< std::string > Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::seeAlso () const inline override
Definition at line 30 of file SANSBeamFluxCorrection.h.
summary()
const std::string Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::summary () const inline override
Summary of algorithms purpose.
Definition at line 27 of file SANSBeamFluxCorrection.h.
version()
int Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::version () const inline override
Algorithm's version.
Definition at line 29 of file SANSBeamFluxCorrection.h.
Member Data Documentation
m_output_message
std::string Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::m_output_message private
Definition at line 45 of file SANSBeamFluxCorrection.h.
Referenced by exec(), and loadReference().
m_reductionManager
std::shared_ptr<Kernel::PropertyManager> Mantid::WorkflowAlgorithms::SANSBeamFluxCorrection::m_reductionManager private
Definition at line 44 of file SANSBeamFluxCorrection.h.
Referenced by exec(), and loadReference().
The documentation for this class was generated from the following files:
Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/SANSBeamFluxCorrection.h
Framework/WorkflowAlgorithms/src/SANSBeamFluxCorrection.cpp