Mantid: Framework/PythonInterface/mantid/geometry/src/Exports/UnitCell.cpp File Reference
UnitCell.cpp File Reference
#include "MantidGeometry/Crystal/UnitCell.h"
#include "MantidPythonInterface/core/Converters/MatrixToNDArray.h"
#include "MantidPythonInterface/core/Converters/PyObjectToMatrix.h"
#include "MantidPythonInterface/core/Converters/PyObjectToV3D.h"
#include "MantidPythonInterface/core/Policies/MatrixToNumpy.h"
#include <boost/python/class.hpp>
#include <boost/python/enum.hpp>
#include <boost/python/operators.hpp>
#include <boost/python/scope.hpp>
#include <boost/python/self.hpp>
Functions
void export_UnitCell ()
Function Documentation
export_UnitCell()
void export_UnitCell ()
return_value_policy for read-only numpy array
Definition at line 71 of file UnitCell.cpp.
References Mantid::Geometry::UnitCell::a(), Mantid::Geometry::UnitCell::a1(), Mantid::Geometry::UnitCell::a2(), Mantid::Geometry::UnitCell::a3(), Mantid::Geometry::UnitCell::alpha(), Mantid::Geometry::UnitCell::alpha1(), Mantid::Geometry::UnitCell::alpha2(), Mantid::Geometry::UnitCell::alpha3(), Mantid::Geometry::UnitCell::alphastar(), Mantid::Geometry::angDegrees, Mantid::Geometry::angRadians, Mantid::Geometry::UnitCell::astar(), Mantid::Geometry::UnitCell::b(), Mantid::Geometry::UnitCell::b1(), Mantid::Geometry::UnitCell::b2(), Mantid::Geometry::UnitCell::b3(), Mantid::Geometry::UnitCell::beta(), Mantid::Geometry::UnitCell::beta1(), Mantid::Geometry::UnitCell::beta2(), Mantid::Geometry::UnitCell::beta3(), Mantid::Geometry::UnitCell::betastar(), Mantid::Geometry::UnitCell::bstar(), Mantid::Geometry::UnitCell::c(), Mantid::Geometry::UnitCell::cstar(), Mantid::Geometry::UnitCell::d(), Mantid::Geometry::deg2rad, Mantid::Geometry::UnitCell::dstar(), Mantid::Geometry::UnitCell::errora(), Mantid::Geometry::UnitCell::erroralpha(), Mantid::Geometry::UnitCell::errorb(), Mantid::Geometry::UnitCell::errorbeta(), Mantid::Geometry::UnitCell::errorc(), Mantid::Geometry::UnitCell::errorgamma(), Mantid::Geometry::UnitCell::gamma(), Mantid::Geometry::UnitCell::gammastar(), Mantid::Geometry::UnitCell::getB(), Mantid::Geometry::UnitCell::getBinv(), Mantid::Geometry::UnitCell::getG(), Mantid::Geometry::UnitCell::getGstar(), Mantid::Geometry::UnitCell::getMaxOrder(), Mantid::Geometry::UnitCell::getModHKL(), Mantid::Geometry::UnitCell::getModVec(), Mantid::Geometry::rad2deg, Mantid::Geometry::UnitCell::recAngle(), Mantid::Geometry::UnitCell::recVolume(), Mantid::Geometry::UnitCell::set(), Mantid::Geometry::UnitCell::seta(), Mantid::Geometry::UnitCell::setalpha(), Mantid::Geometry::UnitCell::setb(), Mantid::Geometry::UnitCell::setbeta(), Mantid::Geometry::UnitCell::setc(), Mantid::Geometry::UnitCell::setError(), Mantid::Geometry::UnitCell::setErrora(), Mantid::Geometry::UnitCell::setErroralpha(), Mantid::Geometry::UnitCell::setErrorb(), Mantid::Geometry::UnitCell::setErrorbeta(), Mantid::Geometry::UnitCell::setErrorc(), Mantid::Geometry::UnitCell::setErrorgamma(), Mantid::Geometry::UnitCell::setgamma(), Mantid::Geometry::UnitCell::setMaxOrder(), Mantid::Geometry::UnitCell::setModVec1(), Mantid::Geometry::UnitCell::setModVec2(), Mantid::Geometry::UnitCell::setModVec3(), and Mantid::Geometry::UnitCell::volume().