Mantid: Mantid::Kernel::Logger Class Reference
Mantid::Kernel::Logger Class Reference
The Logger class is in charge of the publishing messages from the framework through various channels.
#include <Kernel/Logger.h>
Public Types
using Priority = Poco::Message::Priority
Public Member Functions
void accumulate (const std::string &msg)
accumulates a message
std::ostream & debug ()
Logs at debug level.
void debug (const std::string &msg)
Logs at debug level.
void dump (const std::string &msg, const void *buffer, std::size_t length)
Logs the given message at debug level, followed by the data in buffer.
std::ostream & error ()
Logs at error level.
void error (const std::string &msg)
Logs at error level.
std::ostream & fatal ()
Logs at Fatal level.
void fatal (const std::string &msg)
Logs at Fatal level.
void flush ()
flushes accumulated messages to the current level
void flush (Priority)
flushes accumulated messages to the given priority
void flushDebug ()
flushes the accumulated message with debug priority
void flushError ()
flushes the accumulated message with error priority
void flushFatal ()
flushes the accumulated message with fatal priority
void flushInformation ()
flushes the accumulated message with information priority
void flushNotice ()
flushes the accumulated message with notice priority
void flushWarning ()
flushes the accumulated message with warning priority
bool getEnabled () const
returns true if the log is enabled
int getLevel () const
Returns the Logger's log level.
std::string getLevelName () const
int getLevelOffset () const
Gets the Logger's log offset level.
std::ostream & getLogStream (const Priority &priority)
gets the correct log stream for a priority
std::ostream & information ()
Logs at information level.
void information (const std::string &msg)
Logs at information level.
bool is (int level) const
Returns true if at least the given log level is set.
bool isDebug () const
Returns true if log level is at least debug.
void log (const std::string &message, const Priority &priority)
Log a message at a given priority.
Logger (const std::string &name)
Constructor giving the logger name.
std::ostream & notice ()
Logs at notice level.
void notice (const std::string &msg)
Logs at notice level.
void purge ()
flushes the accumulated messages without logging them
void setEnabled (const bool enabled)
set if the logging is enabled
void setLevel (const std::string &level)
Sets the Logger's log level using a symbolic value.
void setLevel (int level)
Sets the Logger's log level.
void setLevelOffset (int level)
Sets the Logger's log offset level.
void setName (const std::string &name)
Update the name of the logger.
std::ostream & warning ()
Logs at warning level.
void warning (const std::string &msg)
Logs at warning level.
Static Public Member Functions
static void setLevelForAll (const int level)
Sets the log level for all Loggers created so far, including the root logger.
static void setLevelForAll (const std::string &level)
static void shutdown ()
Shuts down the logging framework and releases all Loggers.
Static Public Attributes
static const std::array< std::string, 9 > PriorityNames
Private Member Functions
Priority applyLevelOffset (Priority proposedLevel)
Return a log stream set with the given priority.
Logger ()
Logger (const Logger &)
Disable copying.
Logger & operator= (const Logger &)
Disable assignment.
Private Attributes
bool m_enabled
The state of this logger, disabled loggers send no messages.
int m_levelOffset
The offset of the logger.
Poco::Logger * m_log
Internal handle to third party logging objects.
std::unique_ptr< ThreadSafeLogStream > m_logStream
Allows stream operators for a logger.
Detailed Description
The Logger class is in charge of the publishing messages from the framework through various channels.
The static methods on the class are responsible for the creation of Logger objects on request. This class currently uses the Logging functionality provided through the POCO (portable components) library.
Usage example:
    Logger ls(someLogger);
    ls.error("Some informational message");
    ls.error() << "Some error message\n";
Author
Nicholas Draper, Tessella Support Services plc
Date
12/10/2007
Definition at line 51 of file Logger.h.
Member Typedef Documentation
Priority
using Mantid::Kernel::Logger::Priority = Poco::Message::Priority
Definition at line 54 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/3]
Mantid::Kernel::Logger::Logger (const std::string & name)
Constructor giving the logger name.
Constructor.
Parameters
name :: The class name invoking this logger
Definition at line 62 of file Logger.cpp.
Logger() [2/3]
Mantid::Kernel::Logger::Logger () private
Logger() [3/3]
Mantid::Kernel::Logger::Logger (const Logger &) private
Disable copying.
Member Function Documentation
accumulate()
void Mantid::Kernel::Logger::accumulate (const std::string & msg)
accumulates a message
accumulates a message to the buffer
Parameters
msg the log message
Definition at line 285 of file Logger.cpp.
References m_logStream.
Referenced by export_Logger().
applyLevelOffset()
Logger::Priority Mantid::Kernel::Logger::applyLevelOffset (Logger::Priority proposedLevel) private
Return a log stream set with the given priority.
Adjust a log priority level based off the m_levelOffset.
Parameters
proposedLevel :: The proposed level
Returns
The offseted level
Definition at line 440 of file Logger.cpp.
References m_levelOffset.
Referenced by getLogStream(), and log().
debug() [1/2]
std::ostream & Mantid::Kernel::Logger::debug ()
Logs at debug level.
This class implements an ostream interface to the Logger for debug messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 279 of file Logger.cpp.
References getLogStream().
debug() [2/2]
void Mantid::Kernel::Logger::debug (const std::string & msg)
Logs at debug level.
If the Logger's log level is at least Poco::Message::PRIO_DEBUG, creates a Message with priority Poco::Message::PRIO_DEBUG and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 145 of file Logger.cpp.
References log().
Referenced by Mantid::CurveFitting::Algorithms::LeBailFit::acceptOrDeny(), Mantid::Kernel::DataService< T >::add(), MantidQt::API::BatchAlgorithmRunner::addAlgorithm(), Mantid::DataHandling::LoadILLTOF2::addAllNexusFieldsAsProperties(), Mantid::DataHandling::LoadILLTOF3::addAllNexusFieldsAsProperties(), Mantid::Algorithms::FindPeaks::addInfoRow(), Mantid::Kernel::TimeROI::addMask(), Mantid::Kernel::DataService< T >::addOrReplace(), Mantid::DataObjects::TimeSplitter::addROI(), Mantid::Kernel::TimeROI::addROI(), Mantid::DataHandling::LoadHFIRSANS::addRunProperty(), Mantid::DataHandling::LoadHFIRSANS::addRunTimeSeriesProperty(), Mantid::DataHandling::ProcessBankCompressed::addToEventLists(), Mantid::Algorithms::GroupWorkspaces::addToGroup(), Mantid::Algorithms::ExtractMaskToTable::addToTableWorkspace(), Mantid::API::AlgorithmFactoryImpl::AlgorithmFactoryImpl(), Mantid::API::AlgorithmManagerImpl::AlgorithmManagerImpl(), Mantid::DataHandling::MaskDetectors::appendToIndexListFromMaskWS(), Mantid::Algorithms::CalculateEfficiency2::averageAndNormalizePixels(), Mantid::Algorithms::CorrectTOFAxis::averageL2(), Mantid::Algorithms::CorrectTOFAxis::averageL2AndEPP(), Mantid::DataHandling::LoadMask::bankToDetectors(), Mantid::MDAlgorithms::BinMD::binByIterating(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::DataHandling::SaveGSASInstrumentFile::buildGSASTabulatedProfile(), Mantid::API::ScriptBuilder::buildPropertyString(), Mantid::API::NotebookBuilder::buildPropertyString(), Mantid::Algorithms::RadiusSum::cacheInputPropertyValues(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::cacheWorkspaceInfo(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::Algorithms::RemoveLowResTOF::calcTofMin(), Mantid::Algorithms::VesuvioL1ThetaResolution::calculateDetector(), Mantid::CurveFitting::Algorithms::LeBailFit::calculateDiffractionPattern(), Mantid::Crystal::ConnectedComponentLabeling::calculateDisjointTree(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Algorithms::MonitorEfficiencyCorUser::calculateFormulaValue(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateFunctionStatistic(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculateGroupPeakIntensities(), Mantid::Algorithms::DetectorDiagnostic::calculateMedian(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculatePeaksIntensities(), Mantid::DataHandling::LoadILLDiffraction::calculateRelativeRotations(), Mantid::Algorithms::ModeratorTzeroLinear::calculateTfLi(), Mantid::DataHandling::LoadRawHelper::calculateWorkspacesizes(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calHandEta(), Mantid::DataHandling::SaveGSASInstrumentFile::calL2FromDtt1(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calOmega(), Mantid::API::FileLoaderRegistryImpl::canLoad(), Mantid::Algorithms::CompareWorkspaces::checkAxes(), Mantid::Algorithms::CompareWorkspaces::checkData(), Mantid::Kernel::DataService< T >::checkForEmptyName(), Mantid::Kernel::DataService< T >::checkForNullPointer(), Mantid::API::FrameworkManagerImpl::checkIfNewerVersionIsAvailable(), Mantid::Algorithms::RingProfile::checkInputsForSpectraWorkspace(), Mantid::Algorithms::CompareWorkspaces::checkInstrument(), Mantid::Algorithms::GetTimeSeriesLogInformation::checkLogValueChanging(), Mantid::Algorithms::CompareWorkspaces::checkMasking(), Mantid::Algorithms::CompareWorkspaces::checkRunProperties(), Mantid::Algorithms::CompareWorkspaces::checkSample(), Mantid::Kernel::FileValidator::checkValidity(), Mantid::API::FileLoaderRegistryImpl::chooseLoader(), MantidQt::API::InterfaceManager::cleanup(), Mantid::Kernel::DataService< T >::clear(), MantidQt::API::InterfaceManager::closeHelpWindow(), Mantid::DataHandling::ProcessBankCompressed::collectEvents(), Mantid::MDAlgorithms::CompareMDWorkspaces::compare2Boxes(), Mantid::MDAlgorithms::CompareMDWorkspaces::compareMDEventWorkspaces(), Mantid::DataHandling::LoadMask::componentToDetectors(), Mantid::Algorithms::FindPeaks::computePhi(), Mantid::Kernel::ConfigServiceImpl::ConfigServiceImpl(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertSpiceMatrixToMomentumMDEvents(), Mantid::DataHandling::SaveDetectorsGrouping::convertToDetectorsRanges(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::convertToMatrixWorkspace(), Mantid::Algorithms::MaskBinsFromTable::convertToSpectraList(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::MDAlgorithms::ConvertToMD::copyMetaData(), Mantid::Algorithms::CorrectTOFAxis::correctManually(), Mantid::API::LiveListenerFactoryImpl::create(), Mantid::API::AlgorithmManagerImpl::create(), Mantid::CurveFitting::Functions::ProcessBackground::createBackgroundFunction(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::createConstraintMatrices(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::createDataMDWorkspace(), Mantid::Algorithms::GeneratePeaks::createDataWorkspace(), MantidQt::API::InterfaceManager::createDialog(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::createExperimentMDWorkspace(), Mantid::DataHandling::LoadGSS::createInstrumentGeometry(), Mantid::ICat::ICat4Catalog::createMantidDataset(), Mantid::DataHandling::LoadRawHelper::createMonitorWorkspace(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::Algorithms::Bin2DPowderDiffraction::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::DataHandling::LoadSpiceAscii::createRunInfoWS(), Mantid::Algorithms::AnnularRingAbsorption::createSampleShapeXML(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::DataHandling::SaveCanSAS1D::createSASRunElement(), Mantid::DataHandling::LoadEventNexus::createSpectraMapping(), MantidQt::API::InterfaceManager::createSubWindow(), MantidQt::API::UserSubWindowFactoryImpl::createUnwrapped(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), Mantid::API::AlgorithmFactoryImpl::decodeName(), Mantid::Algorithms::ClearCache::deleteFiles(), Mantid::DataHandling::LoadSpice2D::detectorDistance(), Mantid::DataHandling::LoadSpice2D::detectorTranslation(), Mantid::Algorithms::ResampleX::determineBinning(), Mantid::Algorithms::MedianDetectorTest::doDetectorTests(), Mantid::DataHandling::SaveNexusProcessed::doExec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doFitFunction(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitPeak(), Mantid::MDAlgorithms::LoadMD::doLoad(), Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::doParameterSpaceRandomWalk(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::CompareWorkspaces::doTableComparison(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::Kernel::InternetHelper::downloadFile(), Mantid::MDAlgorithms::IntegrateQLabEvents::ellipseIntegrateEvents(), Mantid::Kernel::ErrorReporter::ErrorReporter(), Mantid::CurveFitting::Functions::PseudoVoigt::estimate_parameter_value(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::Bin2DPowderDiffraction::exec(), Mantid::Algorithms::CalculateCarpenterSampleCorrection::exec(), Mantid::Algorithms::CalculateEfficiency::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::CorelliCalibrationDatabase::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CreateFlatEventWorkspace::exec(), Mantid::Algorithms::DiffractionFocussing2::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::FilterByTime::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GetAllEi::exec(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::InterpolatingRebin::exec(), Mantid::Algorithms::MedianDetectorTest::exec(), Mantid::Algorithms::ModeratorTzero::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDDetermineCharacterizations::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::RingProfile::exec(), Mantid::Algorithms::SofQWCentre::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::Algorithms::UnwrapMonitor::exec(), Mantid::Algorithms::UnwrapSNS::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::PeakIntensityVsRadius::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::FindDetectorsInShape::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadIDFFromNexus::exec(), Mantid::DataHandling::LoadMcStasNexus::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::LoadPreNexusMonitors::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveDetectorsGrouping::exec(), Mantid::DataHandling::SaveGSASInstrumentFile::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SaveVTK::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::MDAlgorithms::CalculateCoverageDGS::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::MaskMD::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::MDAlgorithms::SpectralMomentMD::exec(), Mantid::MDAlgorithms::ThresholdMD::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::DataHandling::LoadNexusLogs::execLoader(), Mantid::DataHandling::MaskDetectors::execPeaks(), Mantid::Crystal::ConnectedComponentLabeling::executeAndFetchClusters(), Mantid::API::Algorithm::executeInternal(), Mantid::Algorithms::ExportTimeSeriesLog::exportLog(), Mantid::Algorithms::ExtractMaskToTable::extractMaskFromMatrixWorkspace(), Mantid::CurveFitting::Functions::FunctionQDepends::extractQValues(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspace(), Mantid::MDAlgorithms::LoadDNSSCD::fillOutputWorkspaceRaw(), Mantid::DataHandling::LoadILLTOF2::fillStaticWorkspace(), Mantid::DataHandling::LoadILLTOF3::fillStaticWorkspace(), Mantid::Algorithms::FilterEvents::filterEvents(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), Mantid::DataHandling::SampleEnvironmentSpecFileFinder::find(), Mantid::Algorithms::FindPeakBackground::findBackground(), Mantid::Algorithms::GetAllEi::findBinRanges(), Mantid::Algorithms::GetEi::findHalfLoc(), Mantid::CurveFitting::Algorithms::SplineInterpolation::findInterpolationRange(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::Algorithms::GetAllEi::findMonitorPeak(), Mantid::Algorithms::SmoothNeighbours::findNeighboursRectangular(), Mantid::Algorithms::SmoothNeighbours::findNeighboursUbiquitous(), Mantid::MDAlgorithms::findOriginalQUnits(), Mantid::Algorithms::FindPeaks::findPeakBackground(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::Algorithms::FindPeaks::findPeaksGivenStartingPoints(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::Algorithms::FindPeaks::findPeaksUsingMariscotti(), Mantid::API::FileFinderImpl::findRun(), Mantid::API::FileFinderImpl::findRuns(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Kernel::TimeSeriesProperty< TYPE >::firstTime(), Mantid::Kernel::TimeSeriesProperty< TYPE >::firstValue(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), Mantid::Algorithms::CalculateTransmission::fit(), Mantid::Algorithms::FitPeaks::fitBackground(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitFunction(), Mantid::Algorithms::FitPeaks::fitFunctionSD(), Mantid::Algorithms::FindEPP::fitGaussian(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::Algorithms::FindPeaks::fitSinglePeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak(), Mantid::CurveFitting::Algorithms::LeBailFunction::fixPeakParameter(), Mantid::DataHandling::GroupDetectors2::formGroupsEvent(), Mantid::API::FrameworkManagerImpl::FrameworkManagerImpl(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::function(), Mantid::Crystal::PeakHKLErrors::function1D(), Mantid::CurveFitting::Functions::BivariateNormal::function1D(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::function1D(), Mantid::CurveFitting::Functions::InelasticDiffSphere::function1D(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::function1D(), Mantid::CurveFitting::Functions::BivariateNormal::functionDeriv1D(), Mantid::Crystal::PeakHKLErrors::functionDeriv1D(), Mantid::CurveFitting::Functions::Bk2BkExpConvPV::functionLocal(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::fwhm(), Mantid::DataHandling::LoadEventPreNexus2::generateEventDistribtionWorkspace(), Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspaceParallel(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeakParametersWorkspace(), Mantid::DataHandling::LoadFullprofResolution::genTableWorkspace(), Mantid::DataHandling::LoadGSASInstrumentFile::genTableWorkspace(), Mantid::CurveFitting::Functions::PseudoVoigt::get_parameter_to_calculate_from_set(), Mantid::DataHandling::ORNLDataArchive::getArchivePath(), Mantid::DataHandling::ISISDataArchive::getArchivePath(), Mantid::API::FileFinderImpl::getArchivePath(), Mantid::API::FileFinderImpl::getArchiveSearch(), Mantid::MDAlgorithms::ConvertToDetectorFaceMD::getBanks(), Mantid::Geometry::ObjCompAssembly::getComponentByName(), Mantid::DataHandling::LoadSpice2D::getData(), Mantid::DataHandling::LoadILLSANS::getDataDimensions(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getDetCounts(), Mantid::API::MatrixWorkspace::getDetector(), Mantid::API::MatrixWorkspace::getDetectorIDToWorkspaceIndexVector(), Mantid::DataHandling::LoadILLSANS::getDetectorPositionD33(), Mantid::API::SpectrumInfo::getDetectorValues(), Mantid::Algorithms::GetEi2::getDistanceFromSource(), Mantid::ICat::ICat4Catalog::getDownloadURL(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::Algorithms::ConvertSpectrumAxis2::getEfixed(), Mantid::Algorithms::CorrectKiKf::getEfixedFromParameterMap(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::getEi(), MantidQt::MantidWidgets::WorkspaceUtils::getEMode(), Mantid::API::FileFinderImpl::getExtension(), Mantid::DataHandling::PDLoadCharacterizations::getFilenames(), Mantid::API::ISISInstrumentDataCache::getFileParentDirectoryPath(), Mantid::Kernel::ConfigServiceImpl::getFullPath(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::API::FileFinderImpl::getInstrument(), Mantid::Kernel::ConfigServiceImpl::getInstrument(), Mantid::DataHandling::LoadDiffCal::getInstrument(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentDoubleParameter(), Mantid::API::InstrumentFileFinder::getInstrumentFilename(), Mantid::DataHandling::SNSAppendGeometryToNexus::getInstrumentName(), Mantid::Algorithms::ConvertToConstantL2::getInstrumentProperty(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentStringParameter(), Mantid::ICat::ICat4Catalog::getMantidDatasetId(), Mantid::ICat::ICat4Catalog::getNumberOfSearchResults(), Mantid::Kernel::ConfigServiceImpl::getOSVersionReadable(), Mantid::DataHandling::Load::getOutputWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::getParameter(), Mantid::API::InstrumentFileFinder::getParameterPath(), Mantid::DataHandling::ISISDataArchive::getPath(), Mantid::API::FileFinderImpl::getPath(), Mantid::Algorithms::GetEi::getPeakEstimates(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::getResidualVariance(), Mantid::API::InstrumentFileFinder::getResourceFilenames(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::getSampleLogValues(), Mantid::Kernel::TimeSeriesProperty< TYPE >::getSingleValue(), Mantid::Kernel::TimeSeriesProperty< TYPE >::getSingleValue(), Mantid::Algorithms::MedianDetectorTest::getSolidAngles(), Mantid::DataHandling::LoadHFIRSANS::getSourceToSampleDistance(), Mantid::Algorithms::GeneratePeaks::getSpectraSet(), Mantid::Kernel::ConfigServiceImpl::getString(), Mantid::DataHandling::LoadRawHelper::getTimeChannels(), Mantid::ICat::ICat4Catalog::getUploadURL(), Mantid::Algorithms::MonitorEfficiencyCorUser::getValFromInstrumentDef(), Mantid::DataObjects::SpecialWorkspace2D::getValue(), Mantid::DataHandling::LoadILLReflectometry::getXValues(), Mantid::CurveFitting::Algorithms::LeBailFunction::groupPeaks(), Mantid::DataHandling::MaskDetectors::handleMaskByMaskWorkspace(), Mantid::Algorithms::GeneratePeaks::importPeaksFromTable(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::info(), Mantid::Algorithms::GeneratePeaks::init(), Mantid::Kernel::MemoryOptions::initAllocatorOptions(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesNonPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesTable(), Mantid::DataHandling::LoadMLZ::initInstrumentSpecific(), Mantid::DataHandling::LoadILLDiffraction::initMovingWorkspace(), Mantid::DataHandling::LoadILLReflectometry::initNames(), Mantid::DataHandling::LoadILLTOF2::initWorkspace(), Mantid::DataHandling::LoadSINQFocus::initWorkSpace(), Mantid::DataHandling::LoadILLTOF3::initWorkspace(), Mantid::DataHandling::LoadMLZ::initWorkspace(), Mantid::DataHandling::LoadILLReflectometry::initWorkspace(), Mantid::DataHandling::LoadILLSANS::initWorkSpace(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD11B(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD22B(), Mantid::DataHandling::LoadILLSANS::initWorkSpaceD33(), Mantid::Algorithms::ConvertToConstantL2::initWorkspaces(), Mantid::Algorithms::RadiusSum::inputValidationSanityCheck(), Mantid::Kernel::FacilityInfo::instrument(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Algorithms::DetectorDiagnostic::integrateSpectra(), Mantid::Algorithms::SumRowColumn::integrateWorkspace(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::intensity(), Mantid::DataObjects::SpecialWorkspace2D::isCompatible(), Mantid::Crystal::IntegratePeakTimeSlices::isGoodFit(), ISISRAW2::ISISRAW2(), Mantid::API::WorkspaceGroup::isMultiperiod(), Mantid::API::WorkspaceProperty< TYPE >::isValidGroup(), Mantid::Kernel::TimeSeriesProperty< TYPE >::lastTime(), Mantid::Kernel::TimeSeriesProperty< TYPE >::lastValue(), Mantid::Kernel::LibraryManagerImpl::LibraryManagerImpl(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::linearInterpolation(), Mantid::DataHandling::LoadTOFRawNexus::loadBank(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::loadCalFile(), Mantid::WorkflowAlgorithms::LoadEventAndCompress::loadChunk(), Mantid::DataHandling::LoadILLSANS::loadDataFromMonitors(), Mantid::DataHandling::LoadMLZ::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadSINQFocus::loadDataIntoTheWorkSpace(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::API::ExperimentInfo::loadEmbeddedInstrumentInfoNexus(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventIndex(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::DataHandling::LoadFITS::loadHeader(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::WorkflowAlgorithms::DgsReduction::loadInputData(), Mantid::Algorithms::VesuvioL1ThetaResolution::loadInstrument(), Mantid::DataHandling::LoadILLTOF2::loadInstrumentDetails(), Mantid::DataHandling::LoadILLTOF3::loadInstrumentDetails(), Mantid::DataHandling::LoadMLZ::loadInstrumentDetails(), Mantid::API::ExperimentInfo::loadInstrumentParametersNexus(), Mantid::API::ExperimentInfo::loadInstrumentXML(), Mantid::DataHandling::LoadEventNexus::loadISISVMSSpectraMapping(), Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::DataHandling::LoadILLDiffraction::loadMetaData(), Mantid::DataHandling::LoadILLLagrange::loadMetaData(), Mantid::DataHandling::LoadILLPolarizedDiffraction::loadMetaData(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::DataHandling::LoadILLSANS::loadMetaData(), Mantid::DataHandling::LoadILLIndirect2::loadNexusEntriesIntoProperties(), Mantid::Algorithms::CorelliCalibrationDatabase::loadNonCalibratedComponentDatabase(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadNexusLogs::loadNPeriods(), Mantid::DataHandling::LoadNexusLogs::loadNXLog(), Mantid::DataHandling::LoadISISNexus2::loadPeriodData(), Mantid::DataHandling::LoadEventPreNexus2::loadPixelMap(), Mantid::API::FrameworkManagerImpl::loadPluginsUsingKey(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::loadRunToMatrixWS(), Mantid::DataHandling::LoadISISNexus2::loadSampleData(), Mantid::MDAlgorithms::LoadMD::loadSlab(), Mantid::DataHandling::LoadILLTOF2::loadTimeDetails(), Mantid::DataHandling::LoadILLTOF3::loadTimeDetails(), Mantid::DataHandling::LoadMLZ::loadTimeDetails(), Mantid::API::Algorithm::lockWorkspaces(), Mantid::Kernel::InternetHelper::logDebugRequestSending(), Mantid::Algorithms::He3TubeEfficiency::logErrors(), Mantid::Algorithms::DetectorEfficiencyCor::logErrors(), Mantid::DataHandling::SaveSPE::logMissingMasked(), Mantid::API::ISISInstrumentDataCache::makeIndexFilePath(), Mantid::Algorithms::IntegrateByComponent::makeMap(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::DataHandling::LoadMLZ::maskDetectors(), Mantid::WorkflowAlgorithms::SANSBeamFinder::maskEdges(), Mantid::Algorithms::CalculateEfficiency::maskEdges(), Mantid::DataHandling::LoadILLIndirect2::moveComponent(), Mantid::DataHandling::LoadHFIRSANS::moveDetector(), Mantid::DataHandling::LoadILLSANS::moveDetectorDistance(), Mantid::DataHandling::LoadILLSANS::moveDetectorHorizontal(), Mantid::DataHandling::LoadILLSANS::moveDetectorVertical(), Mantid::DataHandling::GroupDetectors2::moveOthers(), Mantid::DataHandling::SetScalingPSD::movePos(), Mantid::DataHandling::LoadILLIndirect2::moveSingleDetectors(), Mantid::DataHandling::LoadILLDiffraction::moveTwoThetaZero(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::Algorithms::RadiusSum::normalizeOutputByRadius(), Mantid::Algorithms::Bin2DPowderDiffraction::normalizeToBinArea(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthInterval(), Mantid::Kernel::FilteredTimeSeriesProperty< HeldType >::nthInterval(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthTime(), Mantid::Kernel::TimeSeriesProperty< TYPE >::nthValue(), Mantid::Kernel::FilteredTimeSeriesProperty< HeldType >::nthValue(), Mantid::API::ISISInstrumentDataCache::openCacheJsonFile(), Mantid::DataHandling::LoadEventPreNexus2::openEventFile(), Mantid::Kernel::LibraryManagerImpl::openLibraries(), Mantid::Kernel::LibraryManagerImpl::openLibrary(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitFullTimeTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankSplitTask::operator()(), Mantid::DataHandling::AlignAndFocusPowderSlim::ProcessBankTask::operator()(), Mantid::Algorithms::InterpolatingRebin::outputYandEValues(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::pairBraggSatellitePeaks(), Mantid::DataHandling::LoadDNSEvent::parse_File(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBackgroundTableWorkspace(), Mantid::DataHandling::LoadFullprofResolution::parseBankLine(), Mantid::CurveFitting::Algorithms::LeBailFit::parseInstrumentParametersTable(), Mantid::DataHandling::LoadFullprofResolution::parseResolutionStrings(), Mantid::DataHandling::LoadPreNexus::parseRuninfo(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::parseSampleLogs(), Mantid::DataHandling::LoadSpiceAscii::parseSPICEAscii(), Mantid::Algorithms::ExtractMaskToTable::parseStringToVector(), Mantid::DataHandling::SaveFullprofResolution::parseTableWorkspace(), Mantid::Algorithms::GetAllEi::peakGuess(), Mantid::ICat::ICat4Catalog::performSearch(), Mantid::DataHandling::LoadILLSANS::placeD16(), Mantid::Crystal::IntegratePeakTimeSlices::PreFit(), Mantid::DataHandling::LoadBankFromDiskTask::prepareEventId(), Mantid::API::WorkspaceGroup::print(), Mantid::Algorithms::GetAllEi::printDebugModeInfo(), Mantid::DataHandling::SaveDetectorsGrouping::printToXML(), Mantid::Kernel::MemoryStats::process_mem_system(), Mantid::Kernel::GitHubApiHelper::processAnonymousRequest(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::processDetectorsPositions(), Mantid::Kernel::InternetHelper::processErrorStates(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::Algorithms::FitPeaks::processInputs(), Mantid::DataHandling::LoadSpiceXML2DDet::processInputs(), Mantid::Algorithms::RadiusSum::processInstrumentRadiusSum(), Mantid::Algorithms::RingProfile::processInstrumentRingProfile(), Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter(), Mantid::Algorithms::MaskBinsFromTable::processMaskBinWorkspace(), Mantid::DataHandling::LoadMask::processMaskOnDetectors(), Mantid::DataHandling::LoadMask::processMaskOnWorkspaceIndex(), Mantid::Algorithms::RadiusSum::processNumericImageRadiusSum(), Mantid::Algorithms::FitPeaks::processOutputs(), Mantid::Kernel::GitHubApiHelper::processResponseHeaders(), Mantid::Algorithms::FitPeaks::processSinglePeakFitResult(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear(), Mantid::CurveFitting::Algorithms::LeBailFit::proposeNewValues(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::proposeNewValues(), Mantid::MDAlgorithms::LoadDNSSCD::read_data(), Mantid::Geometry::vtkGeometryCacheReader::readCacheForObject(), Mantid::DataHandling::PDLoadCharacterizations::readCharInfo(), Mantid::DataHandling::LoadHFIRSANS::readData(), ISISRAW2::readData(), Mantid::DataHandling::PDLoadCharacterizations::readExpIni(), Mantid::DataHandling::LoadMcStas::readHistogramData(), Mantid::DataHandling::GroupDetectors2::readInt(), Mantid::MDAlgorithms::LoadSQW2::readMainHeader(), Mantid::MDAlgorithms::LoadSQW2::readPixelDataIntoWorkspace(), Mantid::MDAlgorithms::LoadSQW2::readSingleSPEHeader(), Mantid::DataHandling::GroupDetectors2::readSpectraIndexes(), Mantid::MDAlgorithms::LoadSQW2::readSQWDimensions(), Mantid::DataHandling::PDLoadCharacterizations::readVersion0(), Mantid::DataHandling::PDLoadCharacterizations::readVersion1(), Mantid::Algorithms::UnwrapMonitor::rebin(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::reducePowderData(), Mantid::Kernel::DataService< T >::remove(), Mantid::Algorithms::BackgroundHelper::removeBackground(), Mantid::API::AlgorithmManagerImpl::removeById(), Mantid::DataHandling::DownloadInstrument::removeOrphanedFiles(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::Algorithms::ConvertUnits::removeUnphysicalBins(), Mantid::Kernel::DataService< T >::rename(), Mantid::API::Algorithm::reportCompleted(), Mantid::DataHandling::LoadILLDiffraction::resolveInstrument(), Mantid::DataObjects::MDBoxFlatTree::restoreBoxTree(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveFormula(), Mantid::Algorithms::DetectorEfficiencyCor::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyCorUser::retrieveProperties(), Mantid::DataHandling::LoadILLSANS::rotateInstrument(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::LoadEmptyInstrument::runLoadIDFFromNexus(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), Mantid::DataHandling::LoadMLZ::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrumentFromRaw(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadRawHelper::runLoadMappingTable(), Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadInstrument::runLoadParameterFile(), Mantid::CurveFitting::Algorithms::Fit::runMinimizer(), MantidQt::API::PythonRunner::runPythonCode(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::runSingleFit(), Mantid::DataObjects::MDBoxFlatTree::saveAffineTransformMatrix(), Mantid::DataHandling::LoadFullprofResolution::scanBanks(), Mantid::PythonInterface::RunPythonScript::scriptCode(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::Kernel::ErrorReporter::sendErrorReport(), Mantid::Kernel::UsageServiceImpl::sendFeatureUsageReport(), Mantid::Kernel::InternetHelper::sendRequestAndProcess(), Mantid::Kernel::GitHubApiHelper::sendRequestAndProcess(), Mantid::Kernel::UsageServiceImpl::sendStartupReport(), Mantid::CurveFitting::ParameterEstimator::setBackToBackExponential(), Mantid::DataHandling::LoadHFIRSANS::setBeamDiameter(), Mantid::DataHandling::LoadHFIRSANS::setBeamTrapRunProperty(), Mantid::DataHandling::LoadSpice2D::setBeamTrapRunProperty(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByComponents(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByDetectors(), Mantid::DataHandling::LoadHFIRSANS::setDetectorDistance(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::DataHandling::LoadILLSANS::setFinalProperties(), Mantid::CurveFitting::Algorithms::LeBailFunction::setFitProfileParameter(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setFixedParameterValues(), Mantid::CurveFitting::Functions::PseudoVoigt::setHeight(), Mantid::DataHandling::LoadSpice2D::setInputPropertiesAsMemberProperties(), Mantid::DataHandling::LoadILLSANS::setInstrumentName(), Mantid::DataHandling::LoadILLIndirect2::setInstrumentName(), Mantid::API::ExperimentInfo::setInstumentFromXML(), Mantid::DataHandling::Mantid3MFFileIO::setMaterialOnObject(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setMatrixWorkspace(), Mantid::API::IFunction::setMatrixWorkspace(), Mantid::DataHandling::LoadSpice2D::setMetadataAsRunProperties(), Mantid::API::FrameworkManagerImpl::setNumOMPThreads(), Mantid::CurveFitting::Functions::PseudoVoigt::setParameter(), Mantid::CurveFitting::Functions::PseudoVoigt::setParameter(), Mantid::CurveFitting::Algorithms::LeBailFunction::setProfileParameterValues(), Mantid::DataObjects::Peak::setQLabFrame(), MantidQt::API::BatchAlgorithmRunner::setQueue(), Mantid::DataHandling::LoadHFIRSANS::setSansSpiceXmlFormatVersion(), Mantid::DataHandling::LoadSpice2D::setSansSpiceXmlFormatVersion(), Mantid::Algorithms::CalculateCountRate::setSourceWSandXRanges(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::setUnitsInfo(), Mantid::MDAlgorithms::LoadSQW2::setupBoxController(), Mantid::Crystal::SCDPanelErrors::setupData(), Mantid::CurveFitting::Functions::TabulatedFunction::setupData(), Mantid::Algorithms::FilterEvents::setupDirectTOFCorrection(), Mantid::Algorithms::RadiusSum::setUpOutputWorkspace(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::setupSampleLogs(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::setupTransferMatrix(), Mantid::API::MultipleFileProperty::setValue(), Mantid::API::MultipleFileProperty::setValueAsSingleFile(), Mantid::DataHandling::LoadHFIRSANS::setWavelength(), Mantid::DataHandling::LoadSpice2D::setWavelength(), MantidQt::API::HelpWindow::showAlgorithm(), MantidQt::API::HelpWindow::showCustomInterface(), Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration(), Mantid::MDAlgorithms::LoadSQW2::skipDetectorSection(), Mantid::Algorithms::WienerSmooth::smoothSingleSpectrum(), Mantid::DataHandling::LoadHFIRSANS::storeMetaDataIntoWS(), Mantid::Algorithms::IQTransform::subtractBackgroundWS(), Mantid::Algorithms::CalculateEfficiency2::sumUnmaskedAndDeadPixels(), Mantid::Algorithms::CalculateEfficiency::sumUnmaskedDetectors(), Mantid::API::FileFinderImpl::toInstrumentAndNumber(), Mantid::DataHandling::traceStatistics(), Mantid::Algorithms::RemoveBins::transformRangeUnit(), Mantid::DataHandling::SetSample::tryCreateXMLFromArgsOnly(), Mantid::API::Algorithm::unlockWorkspaces(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::updateCMatrixValues(), Mantid::Algorithms::CorelliCalibrationDatabase::updateComponentDatabaseFiles(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromAscii(), MantidQt::MantidWidgets::InstrumentSelector::updateInstrument(), Mantid::API::FrameworkManagerImpl::updateInstrumentDefinitions(), Mantid::Crystal::IntegratePeakTimeSlices::updatePeakInformation(), Mantid::API::MatrixWorkspace::updateSpectraUsing(), Mantid::Kernel::UsageServiceImpl::UsageServiceImpl(), Mantid::Algorithms::DiffractionFocussing2::validateSpectrumInGroup(), Mantid::Algorithms::SmoothData::validateSpectrumInGroup(), Mantid::API::WorkspaceFactoryImpl::WorkspaceFactoryImpl(), Mantid::DataHandling::Mantid3MFFileIO::writeMeshObject(), Mantid::DataHandling::SaveGSASInstrumentFile::writePRMSingleBank(), Mantid::DataHandling::SaveGSS::writeSLOGdata(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseDetectorNode(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseSpice().
dump()
void Mantid::Kernel::Logger::dump (const std::string & msg, const void * buffer, std::size_t length)
Logs the given message at debug level, followed by the data in buffer.
The data in buffer is written in canonical hex+ASCII form: Offset (4 bytes) in hexadecimal, followed by sixteen space-separated, two column, hexadecimal bytes, followed by the same sixteen bytes as ASCII characters. For bytes outside the range 32 .. 127, a dot is printed. Note all Dump messages go out at Debug message level
Parameters
msg :: The message to log
buffer :: the binary data to log
length :: The length of the binaary data to log
Definition at line 160 of file Logger.cpp.
References m_enabled, and m_log.
error() [1/2]
std::ostream & Mantid::Kernel::Logger::error ()
Logs at error level.
This class implements an ostream interface to the Logger for error messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 240 of file Logger.cpp.
References getLogStream().
error() [2/2]
void Mantid::Kernel::Logger::error (const std::string & msg)
Logs at error level.
If the Logger's log level is at least Poco::Message::PRIO_ERROR, creates a Message with priority Poco::Message::PRIO_ERROR and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 108 of file Logger.cpp.
References log().
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), Mantid::Kernel::DataService< T >::add(), MantidQt::MantidWidgets::FitDomain::addFunctionToExisting(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::addMDEvents(), Mantid::CurveFitting::Algorithms::LeBailFit::addParameterToMCMinimize(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::addParameterToMCMinimize(), Mantid::CurveFitting::Algorithms::LeBailFunction::addPeaks(), Mantid::CurveFitting::Functions::ProcessBackground::addRegion(), Mantid::Algorithms::AddSampleLog::addSingleValueProperty(), Mantid::Algorithms::AddSampleLog::addTimeSeriesProperty(), Mantid::Algorithms::ExtractMaskToTable::addToTableWorkspace(), Mantid::Crystal::LoadIsawPeaks::appendFile(), Mantid::Geometry::Instrument::appendPlottable(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::appendSampleLogs(), Mantid::DataHandling::MaskDetectors::appendToDetectorListFromComponentList(), Mantid::CurveFitting::Algorithms::LeBailFit::applyParameterValues(), FileComparisonHelper::areIteratorsEqual(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::DataObjects::SpecialWorkspace2D::binaryOperation(), Mantid::DataHandling::LoadSpiceXML2DDet::binaryParseIntegers(), Mantid::API::ScriptBuilder::buildAlgorithmString(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::calcAveragePosition(), Mantid::DataHandling::FindDetectorsPar::calcDetPar(), Mantid::Algorithms::FitOneSinglePeak::calChiSquareSD(), Mantid::CurveFitting::Algorithms::LeBailFit::calculateDiffractionPattern(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Algorithms::ExportTimeSeriesLog::calculateFirstDerivative(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateFunctionStatistic(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculateGroupPeakIntensities(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::Algorithms::GetTimeSeriesLogInformation::calDistributions(), Mantid::CurveFitting::Functions::Bk2BkExpConvPV::calHandEta(), Mantid::CurveFitting::Algorithms::LeBailFunction::calPeak(), Mantid::DataHandling::LoadNexusMonitors2::canOpenAsNeXus(), Mantid::Algorithms::PointByPointVCorrection::check_validity(), Mantid::Algorithms::BinaryOperation::checkCompatibility(), Mantid::Algorithms::WeightedMean::checkCompatibility(), Mantid::Geometry::InstrumentDefinitionParser::checkComponentContainsLocationElement(), Mantid::DataHandling::SaveReflectometryAscii::checkFile(), Mantid::Algorithms::ConjoinWorkspaces::checkForOverlap(), Mantid::Geometry::InstrumentDefinitionParser::checkIdListExistsAndDefinesEnoughIDs(), Mantid::MDAlgorithms::ApplyDetailedBalanceMD::checkInputMDDimension(), Mantid::MDAlgorithms::DgsScatteredTransmissionCorrectionMD::checkInputMDDimensions(), Mantid::DataHandling::LoadSESANS::checkMandatoryHeaders(), Mantid::Crystal::LoadIsawPeaks::checkNumberPeaks(), Mantid::DataHandling::LoadRawHelper::checkOptionalProperties(), Mantid::DataHandling::SaveVTK::checkOptionalProperties(), Mantid::DataHandling::LoadNexusProcessed::checkOptionalProperties(), Mantid::Algorithms::CalculateFlatBackground::checkRange(), Mantid::Algorithms::MergeRuns::checkRebinning(), Mantid::DataHandling::LoadPDFgetNFile::checkSameSize(), Mantid::Algorithms::Minus::checkUnitCompatibility(), Mantid::Algorithms::Plus::checkUnitCompatibility(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::combineBtnPressed(), Mantid::Kernel::ConfigServiceImpl::ConfigServiceImpl(), Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructSample(), Mantid::DataHandling::SaveGSASInstrumentFile::convertToGSAS(), Mantid::API::IFunction::convertValue(), Mantid::API::AlgorithmFactoryImpl::create(), Mantid::API::AlgorithmManagerImpl::create(), Mantid::API::WorkspaceFactoryImpl::create(), Mantid::API::TransformScaleFactoryImpl::create(), Mantid::CurveFitting::Functions::ProcessBackground::createBackgroundFunction(), Mantid::Algorithms::GeneratePeaks::createDataWorkspace(), Mantid::Geometry::InstrumentDefinitionParser::createDetectorOrMonitor(), MantidQt::API::UserSubWindowFactoryImpl::createFromAlias(), Mantid::Algorithms::FitPeak::createFunctions(), MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::Kernel::LogParser::createLogProperty(), Mantid::Algorithms::MaskDetectorsIf::createNewCalFile(), Mantid::MDAlgorithms::ConvertToMD::createNewMDWorkspace(), Mantid::Crystal::PeakHKLErrors::createNewPeak(), Mantid::Algorithms::GeneratePeaks::createOutputWorkspace(), Mantid::Geometry::XMLInstrumentParameter::createParamValue(), MantidQt::API::InterfaceManager::createSubWindow(), MantidQt::API::UserSubWindowFactoryImpl::createUnwrapped(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::cropWorkspace(), Mantid::API::FrameworkManagerImpl::deleteWorkspace(), Mantid::Geometry::DetectorGroup::DetectorGroup(), Mantid::ICat::CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitNPeaksSimple(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::doParameterSpaceRandomWalk(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), Mantid::Algorithms::AppendSpectra::exec(), Mantid::Algorithms::BinaryOperation::exec(), Mantid::Algorithms::CalculateDynamicRange::exec(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::exec(), Mantid::Algorithms::ConjoinWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::CreateCalFileByNames::exec(), Mantid::Algorithms::CreateDummyCalFile::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::DeleteWorkspaces::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::FFTSmooth::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FixGSASInstrumentFile::exec(), Mantid::Algorithms::GetQsInQENSData::exec(), Mantid::Algorithms::GetTimeSeriesLogInformation::exec(), Mantid::Algorithms::InvertMask::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaskDetectorsIf::exec(), Mantid::Algorithms::ModeratorTzero::exec(), Mantid::Algorithms::ModeratorTzeroLinear::exec(), Mantid::Algorithms::MultiplyRange::exec(), Mantid::Algorithms::ParallaxCorrection::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::ScaleX::exec(), Mantid::Algorithms::Segfault::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::StripVanadiumPeaks::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::IntegratePeakTimeSlices::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::PeakIntegration::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::Crystal::ShowPeakHKLOffsets::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), Mantid::CurveFitting::Algorithms::LeBailFit::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::exec(), Mantid::CurveFitting::Functions::ProcessBackground::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DefineGaugeVolume::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::LoadAscii::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadBBY2::exec(), Mantid::DataHandling::LoadEmptyInstrument::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadMask::exec(), Mantid::DataHandling::LoadNexus::exec(), Mantid::DataHandling::LoadNexusProcessed::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::DataHandling::LoadRawBin0::exec(), Mantid::DataHandling::LoadRawSpectrum0::exec(), Mantid::DataHandling::LoadRKH::exec(), Mantid::DataHandling::LoadSampleDetailsFromRaw::exec(), Mantid::DataHandling::LoadSampleEnvironment::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSESANS::exec(), Mantid::DataHandling::LoadSPE::exec(), Mantid::DataHandling::MoveInstrumentComponent::exec(), Mantid::DataHandling::RawFileInfo::exec(), Mantid::DataHandling::RotateInstrumentComponent::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveBankScatteringAngles::exec(), Mantid::DataHandling::SaveCSV::exec(), Mantid::DataHandling::SaveDaveGrp::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveGSASInstrumentFile::exec(), Mantid::DataHandling::SaveNISTDAT::exec(), Mantid::DataHandling::SavePHX::exec(), Mantid::DataHandling::SaveRKH::exec(), Mantid::DataHandling::SaveSESANS::exec(), Mantid::DataHandling::SaveVTK::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxGlobal::exec(), Mantid::MDAlgorithms::ConvertToMDMinMaxLocal::exec(), Mantid::MDAlgorithms::FlippingRatioCorrectionMD::exec(), Mantid::MDAlgorithms::ImportMDEventWorkspace::exec(), Mantid::MDAlgorithms::ImportMDHistoWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::WorkflowAlgorithms::ComputeSensitivity::exec(), Mantid::WorkflowAlgorithms::DgsReduction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction::exec(), Mantid::WorkflowAlgorithms::EQSANSDarkCurrentSubtraction2::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::exec(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::exec(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::exec(), Mantid::DataHandling::LoadPLN::exec(), Mantid::Crystal::PredictSatellitePeaks::exec_peaks(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::Algorithms::MergeRuns::execHistogram(), MantidQt::API::AlgorithmDialog::executeAlgorithmAsync(), MantidQt::MantidWidgets::MantidTreeModel::executeAlgorithmAsync(), Mantid::API::Algorithm::executeInternal(), Mantid::CurveFitting::Algorithms::LeBailFit::exportBraggPeakParameterToTable(), Mantid::Algorithms::ExportTimeSeriesLog::exportLog(), Mantid::Algorithms::NormaliseByCurrent::extractCharge(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::extractValidSampleObject(), Mantid::WorkflowAlgorithms::SANSSensitivityCorrection::fileCheck(), Mantid::Kernel::FacilityInfo::fillArchiveNames(), Mantid::Kernel::FacilityInfo::fillExtensions(), Mantid::Kernel::InstrumentInfo::fillLiveData(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::Algorithms::GetEi::findHalfLoc(), Mantid::Crystal::SCDCalibratePanels::findL1(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Crystal::IntegratePeakTimeSlices::Fit(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Algorithms::CalculateTransmission::fitData(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitFunction(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionMD(), Mantid::Algorithms::FitOneSinglePeak::fitFunctionSD(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::Algorithms::CalculateTransmission::fitPolynomial(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::Algorithms::FitPeaks::fitSpectrumPeaks(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::fitToData(), Mantid::Algorithms::IQTransform::general(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genOutputFittedPatternWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeaksFromTable(), Mantid::DataHandling::FindDetectorsPar::get_ASCII_header(), Mantid::DataHandling::LoadSpice2D::getData(), Mantid::DataHandling::SetScalingPSD::getDetPositionsFromRaw(), Mantid::DataHandling::DownloadInstrument::getFileShas(), Mantid::Algorithms::GetEi::getGeometry(), Mantid::API::GridDomain::getGrid(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::DataHandling::LoadSpiceXML2DDet::getHB3AWavelength(), MantidQt::MantidWidgets::SequentialFitDialog::getIndex(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::DataHandling::LoadRawHelper::getmonitorSpectrumList(), Mantid::Algorithms::GetEi::getMonitorWsIndexs(), Mantid::Crystal::PeakHKLErrors::getNewInstrument(), Mantid::Geometry::InstrumentDefinitionParser::getParentComponent(), Mantid::API::FileFinderImpl::getPath(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeak(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakMaximumValue(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::getPeakParameter(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakParameter(), Mantid::CurveFitting::Algorithms::LeBailFunction::getPeakParameter(), Mantid::DataHandling::SaveGSASInstrumentFile::getProfileParameterValue(), Mantid::Kernel::Quat::getRotation(), Mantid::Geometry::Instrument::getSample(), Mantid::Geometry::Instrument::getSource(), Mantid::API::MatrixWorkspace::getSpectrumToWorkspaceIndexMap(), Mantid::Geometry::FitParameter::getValue(), Mantid::DataHandling::SaveGSASInstrumentFile::getValueFromMap(), Mantid::Algorithms::Q1DWeighted::getViewportParams(), Mantid::DataHandling::SaveNexusProcessed::getWSIndexList(), Mantid::DataHandling::LoadILLReflectometry::getXValues(), Mantid::Algorithms::FilterEvents::groupOutputWorkspace(), Mantid::CurveFitting::Algorithms::LeBailFunction::groupPeaks(), Mantid::DataHandling::LoadFITS::headerSanityCheck(), Mantid::Algorithms::FitOneSinglePeak::highBkgdFit(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::importInstrumentParameterFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::importMonteCarloParametersFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::importParametersFromTable(), Mantid::CurveFitting::Functions::CrystalFieldMultiSpectrum::init(), Mantid::CurveFitting::Functions::CrystalFieldSpectrum::init(), Mantid::Algorithms::FlatPlateAbsorption::initialiseCachedDistances(), Mantid::CurveFitting::Constraints::BoundaryConstraint::initialize(), Mantid::DataHandling::LoadMask::initializeXMLParser(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::intensity(), Mantid::DataHandling::LoadMask::intializeMaskWorkspace(), ISISRAW2::ioRAW(), Mantid::Kernel::LiveListenerInfo::LiveListenerInfo(), Mantid::DataHandling::FindDetectorsPar::load_plain(), Mantid::Kernel::ConfigServiceImpl::loadConfig(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataHandling::LoadFullprofResolution::loadFile(), Mantid::DataHandling::LoadGSASInstrumentFile::loadFile(), Mantid::DataHandling::LoadSassena::loadFQ(), Mantid::DataHandling::LoadSassena::loadFQT(), Mantid::DataHandling::SaveGSASInstrumentFile::loadFullprofResolutionFile(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::DataHandling::LoadSpiceXML2DDet::loadInstrument(), Mantid::API::ExperimentInfo::loadInstrumentXML(), Mantid::DataHandling::LoadSwans::loadMetaData(), Mantid::DataHandling::FindDetectorsPar::loadParFile(), Mantid::DataHandling::LoadSassena::loadQvectors(), Mantid::DataHandling::LoadSingleMesh::LoadSingleMesh(), Mantid::DataHandling::LoadMLZ::loadTimeDetails(), Mantid::DataHandling::LoadFITS::mapHeaderKeys(), Mantid::Algorithms::MaskBinsFromTable::maskBins(), Mantid::Algorithms::CalculateEfficiency::normalizeDetectors(), Mantid::Kernel::DllOpen::openDll(), Mantid::DataHandling::SaveOpenGenieAscii::openFileStream(), MantidQt::API::ScriptRepositoryView::openFolderLink(), Mantid::Kernel::LibraryManagerImpl::openLibraries(), Mantid::Kernel::LibraryManagerImpl::openLibraries(), Mantid::Algorithms::InterpolatingRebin::outputYandEValues(), Mantid::DataHandling::LoadDNSEvent::parse_andAddEvent(), Mantid::DataHandling::LoadDNSEvent::parse_File(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBackgroundTableWorkspace(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBraggPeaksParametersTable(), Mantid::DataHandling::LoadPDFgetNFile::parseColumnNameLine(), Mantid::DataHandling::LoadPDFgetNFile::parseDataFile(), Mantid::CurveFitting::Algorithms::LeBailFit::parseInstrumentParametersTable(), Mantid::Algorithms::ExtractMaskToTable::parseMaskTable(), Mantid::DataHandling::SaveGDA::parseParamsFile(), Mantid::DataHandling::LoadFullprofResolution::parseResolutionStrings(), Mantid::Algorithms::ExtractMaskToTable::parseStringToVector(), Mantid::DataHandling::LoadMask::parseXML(), Mantid::Geometry::InstrumentDefinitionParser::parseXML(), Mantid::Algorithms::CreatePSDBleedMask::performBleedTest(), Mantid::Algorithms::FindPeaksConvolve::performConvolution(), Mantid::Geometry::InstrumentDefinitionParser::populateIdList(), Mantid::Algorithms::CreateDetectorTable::populateTable(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::processDetectorsPositions(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::Algorithms::SassenaFFT::processGroups(), Mantid::DataHandling::LoadEventPreNexus2::processImbedLogs(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::Algorithms::FitPeaks::processInputPeakTolerance(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::processInputProperties(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputProperties(), Mantid::DataHandling::LoadMask::processMaskOnWorkspaceIndex(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::DataHandling::SaveFullprofResolution::processProperties(), Mantid::DataHandling::SaveGSASInstrumentFile::processProperties(), Mantid::DataHandling::SetScalingPSD::processScalingFile(), Mantid::Algorithms::GetTimeSeriesLogInformation::processTimeRange(), Mantid::CurveFitting::Algorithms::LeBailFit::proposeNewValues(), Mantid::Algorithms::SANSCollimationLengthEstimator::provideCollimationLength(), Mantid::ICat::CatalogPublish::publish(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::rasterizeGaugeVolumeAndCalculateMeanElementPosition(), Mantid::DataObjects::PeakColumn< T >::read(), Mantid::DataObjects::PeakColumn< T >::read(), Mantid::DataHandling::LoadRKH::read1D(), Mantid::WorkflowAlgorithms::EQSANSLoad::readConfigFile(), Mantid::DataHandling::LoadHFIRSANS::readData(), Mantid::DataHandling::LoadAscii::readData(), Mantid::DataHandling::LoadMcStas::readEventData(), Mantid::DataHandling::LoadNexusMonitors2::readEventMonitorEntry(), Mantid::Algorithms::ReadGroupsFromFile::readGroupingFile(), Mantid::Algorithms::DiffractionFocussing::readGroupingFile(), Mantid::Crystal::LoadIsawPeaks::readHeader(), Mantid::DataHandling::LoadIDFFromNexus::readParameterCorrectionFile(), Mantid::Geometry::vtkGeometryCacheReader::readPoints(), Mantid::Geometry::vtkGeometryCacheReader::readTriangles(), Mantid::Algorithms::Regroup::rebin(), Mantid::Crystal::FindSXPeaks::reducePeakList(), Mantid::DataObjects::TableWorkspace::removeColumn(), Mantid::DataHandling::DownloadInstrument::removeOrphanedFiles(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::DataObjects::SplittersWorkspace::removeSplitter(), Mantid::Algorithms::ConvertUnits::removeUnphysicalBins(), Mantid::Kernel::DataService< T >::rename(), Mantid::DataHandling::LoadSPE::reportFormatError(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::MaskDetectorsInShape::runFindDetectorsInShape(), Mantid::DataHandling::LoadEmptyInstrument::runLoadIDFFromNexus(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadInstrument(), Mantid::DataHandling::LoadPreNexusMonitors::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrumentFromRaw(), Mantid::DataHandling::LoadNexus::runLoadIsisNexus(), Mantid::DataHandling::LoadNexusMonitors2::runLoadLogs(), Mantid::DataHandling::LoadRawHelper::runLoadMappingTable(), Mantid::DataHandling::LoadNexus::runLoadMuonNexus(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadNexus::runLoadNexusProcessed(), Mantid::DataHandling::LoadNexus::runLoadTOFRawNexus(), Mantid::DataHandling::SaveNexus::runSaveNexusProcessed(), Mantid::DataHandling::GenerateGroupingPowder::saveAsPAR(), Mantid::DataHandling::GenerateGroupingPowder::saveAsXML(), Mantid::Kernel::ConfigServiceImpl::saveConfig(), Mantid::Algorithms::CreateCalFileByNames::saveGroupingFile(), Mantid::Algorithms::CreateDummyCalFile::saveGroupingFile(), Mantid::DataHandling::SaveNexusESS::saveNexusGeometry(), Mantid::DataHandling::SaveNexusProcessed::saveSpectraDetectorMapNexus(), MantidQt::API::ScriptRepositoryView::ScriptRepositoryView(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::API::LogarithmScale::setBase(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByComponents(), Mantid::DataHandling::LoadDetectorsGroupingFile::setByDetectors(), Mantid::DataHandling::LoadDetectorsGroupingFile::setBySpectrumNos(), Mantid::Geometry::InstrumentDefinitionParser::setComponentLinks(), Mantid::Kernel::ConfigServiceImpl::setFacility(), Mantid::Geometry::InstrumentDefinitionParser::setFacing(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterFitSetups(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterValues(), Mantid::DataHandling::LoadILLIndirect2::setInstrumentName(), MantidQt::MantidWidgets::FunctionModel::setLocalParameterConstraint(), MantidQt::MantidWidgets::FunctionModel::setLocalParameterTie(), Mantid::Geometry::InstrumentDefinitionParser::setLogfile(), Mantid::API::IFunction::setMatrixWorkspace(), Mantid::API::Column::setPlotType(), Mantid::CurveFitting::Algorithms::LeBailFunction::setProfileParameterValues(), Mantid::Algorithms::SampleLogsBehaviour::setSampleMap(), Mantid::DataHandling::LoadEventNexus::setTopEntryName(), Mantid::DataHandling::DetermineChunking::setTopEntryName(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::DataHandling::LoadSpiceAscii::setupRunStartTime(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupSensitivity(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::API::MultipleFileProperty::setValueAsMultipleFiles(), MantidQt::MantidWidgets::MantidTreeModel::showAlgorithmDialog(), MantidQt::API::HelpWindow::showConcept(), MantidQt::API::HelpWindow::showFitFunction(), MantidQt::API::HelpWindow::showPage(), MantidQt::API::HelpWindow::showPage(), Mantid::Kernel::UsageServiceImpl::shutdown(), Mantid::Algorithms::FitOneSinglePeak::simpleFit(), Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData(), Mantid::DataHandling::CheckMantidVersion::splitVersionString(), Mantid::DataHandling::LoadSESANS::throwFormatError(), Mantid::Geometry::InstrumentDefinitionParser::throwIfTypeNameNotUnique(), Mantid::DataHandling::SaveFullprofResolution::toProf10IrfString(), Mantid::DataHandling::SaveFullprofResolution::toProf9IrfString(), Mantid::API::LogarithmScale::transform(), Mantid::Kernel::ConfigServiceImpl::updateFacilities(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromRaw(), Mantid::MDAlgorithms::MDNorm::validateBinningForTemporaryDataWorkspace(), Mantid::Algorithms::RemoveBins::validateInputs(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::validateInputs(), Mantid::Algorithms::MergeRuns::validateInputsForEventWorkspaces(), Mantid::Algorithms::RunCombinationHelper::validateInputWorkspaces(), Mantid::DataHandling::LoadSpiceAscii::validateLogNamesType(), Mantid::Kernel::PropertyManager::validateProperties(), Mantid::Kernel::Interpolation::value(), MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedAttribute(), wrapMeshWithNDArray(), Mantid::Geometry::vtkGeometryCacheWriter::write(), Mantid::Geometry::InstrumentDefinitionParser::writeAndApplyCache(), Mantid::DataHandling::SaveGSS::writeBufferToFile(), Mantid::Algorithms::CreateLogTimeCorrection::writeCorrectionToFile(), Mantid::Algorithms::FitPeaks::writeFitResult(), Mantid::DataHandling::SaveGSS::writeSLOGdata(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseSpice().
fatal() [1/2]
std::ostream & Mantid::Kernel::Logger::fatal ()
Logs at Fatal level.
This class implements an ostream interface to the Logger for fatal messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 231 of file Logger.cpp.
References getLogStream().
fatal() [2/2]
void Mantid::Kernel::Logger::fatal (const std::string & msg)
Logs at Fatal level.
If the Logger's log level is at least Poco::Message::PRIO_FATAL, creates a Message with priority Poco::Message::PRIO_FATAL and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 99 of file Logger.cpp.
References log().
Referenced by Mantid::API::Algorithm::initialize().
flush() [1/2]
void Mantid::Kernel::Logger::flush ()
flushes accumulated messages to the current level
Flushes the accumulated message to the current channel.
Definition at line 290 of file Logger.cpp.
References getLevel(), log(), and m_logStream.
Referenced by export_Logger(), flushDebug(), flushError(), flushFatal(), flushInformation(), flushNotice(), and flushWarning().
flush() [2/2]
void Mantid::Kernel::Logger::flush (Priority priority)
flushes accumulated messages to the given priority
Flushes the accumulated message to the given priority.
Parameters
priority the log level priority
Definition at line 296 of file Logger.cpp.
References log(), and m_logStream.
flushDebug()
void Mantid::Kernel::Logger::flushDebug ()
flushes the accumulated message with debug priority
Definition at line 299 of file Logger.cpp.
References flush().
Referenced by export_Logger().
flushError()
void Mantid::Kernel::Logger::flushError ()
flushes the accumulated message with error priority
Definition at line 311 of file Logger.cpp.
References flush().
Referenced by export_Logger().
flushFatal()
void Mantid::Kernel::Logger::flushFatal ()
flushes the accumulated message with fatal priority
Definition at line 314 of file Logger.cpp.
References flush().
Referenced by export_Logger().
flushInformation()
void Mantid::Kernel::Logger::flushInformation ()
flushes the accumulated message with information priority
Definition at line 302 of file Logger.cpp.
References flush().
Referenced by export_Logger().
flushNotice()
void Mantid::Kernel::Logger::flushNotice ()
flushes the accumulated message with notice priority
Definition at line 305 of file Logger.cpp.
References flush().
Referenced by export_Logger().
flushWarning()
void Mantid::Kernel::Logger::flushWarning ()
flushes the accumulated message with warning priority
Definition at line 308 of file Logger.cpp.
References flush().
Referenced by export_Logger().
getEnabled()
bool Mantid::Kernel::Logger::getEnabled () const
returns true if the log is enabled
Returns true if the log is enabled.
Return values
true - logging is enabled
false - all messages are ignored.
Definition at line 83 of file Logger.cpp.
References m_enabled.
Referenced by Mantid::API::Algorithm::isLogging().
getLevel()
int Mantid::Kernel::Logger::getLevel () const
Returns the Logger's log level.
Definition at line 217 of file Logger.cpp.
References m_log.
Referenced by Mantid::Algorithms::GetDetectorOffsets::exec(), flush(), getLevelName(), and Mantid::Kernel::ConfigServiceImpl::setLogLevel().
getLevelName()
std::string Mantid::Kernel::Logger::getLevelName () const
Definition at line 219 of file Logger.cpp.
References getLevel(), and PriorityNames.
Referenced by Mantid::Kernel::ConfigServiceImpl::getLogLevel(), Mantid::Kernel::ConfigServiceImpl::setLogLevel(), and Mantid::Kernel::ConfigServiceImpl::setLogLevel().
getLevelOffset()
int Mantid::Kernel::Logger::getLevelOffset () const
Gets the Logger's log offset level.
Returns
The offset level Gets the Logger's log offset level.
Definition at line 467 of file Logger.cpp.
References m_levelOffset.
Referenced by Mantid::API::Algorithm::getLoggingOffset().
getLogStream()
std::ostream & Mantid::Kernel::Logger::getLogStream (const Priority & priority)
gets the correct log stream for a priority
Log a given message at a given priority.
Parameters
priority :: The priority level
Returns
:: the stream
Definition at line 404 of file Logger.cpp.
References applyLevelOffset(), m_enabled, and m_logStream.
Referenced by debug(), error(), Mantid::Algorithms::GetDetectorOffsets::exec(), Mantid::Algorithms::PDCalibration::exec(), fatal(), information(), notice(), and warning().
information() [1/2]
std::ostream & Mantid::Kernel::Logger::information ()
Logs at information level.
This class implements an ostream interface to the Logger for information messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 270 of file Logger.cpp.
References getLogStream().
information() [2/2]
void Mantid::Kernel::Logger::information (const std::string & msg)
Logs at information level.
If the Logger's log level is at least Poco::Message::PRIO_INFORMATION, creates a Message with priority Poco::Message::PRIO_INFORMATION and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 136 of file Logger.cpp.
References log().
Referenced by Mantid::CurveFitting::Algorithms::LeBailFunction::addBackgroundFunction(), Mantid::Kernel::ConfigServiceImpl::addDirectoryifExists(), Mantid::Algorithms::FindPeaks::addNonFitRecord(), Mantid::CurveFitting::Algorithms::LeBailFunction::addPeaks(), Mantid::Algorithms::AddSampleLog::addSingleValueProperty(), Mantid::DataHandling::LoadEventPreNexus2::addToWorkspaceLog(), Mantid::DataHandling::CreateSimulationWorkspace::adjustInstrument(), Mantid::MDAlgorithms::ConvToMDEventsWSIndexing::appendEvents(), Mantid::Geometry::InstrumentDefinitionParser::applyCache(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::applyCorrection(), Mantid::API::FrameworkManagerImpl::asynchronousStartupTasks(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::Algorithms::CorrectTOFAxis::averageL2(), Mantid::Algorithms::CorrectTOFAxis::averageL2AndEPP(), Mantid::DataHandling::LoadSpiceXML2DDet::binaryParseIntegers(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::Algorithms::MergeRuns::buildScanningOutputWorkspace(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::cacheInstrumentGeometry(), Mantid::CurveFitting::Functions::VesuvioResolution::cacheResolutionComponents(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::calculateBackground(), Mantid::CurveFitting::Functions::CubicSpline::calculateDerivative(), Mantid::CurveFitting::Algorithms::LeBailFit::calculateDiffractionPattern(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculateGroupPeakIntensities(), Mantid::Algorithms::DetectorDiagnostic::calculateMedian(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calculateParameters(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSampleAndContainer(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSingleComponent(), Mantid::CurveFitting::Functions::CubicSpline::calculateSpline(), Mantid::Algorithms::FindPeaks::callFitPeak(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::DataHandling::SaveReflectometryAscii::checkFile(), Mantid::MDAlgorithms::PolarizationAngleCorrectionMD::checkInputMDDimension(), Mantid::Algorithms::NormaliseToMonitor::checkProperties(), Mantid::DataHandling::LoadPDFgetNFile::checkSameSize(), MantidQt::API::ScriptRepositoryView::chooseLocationAndInstall(), Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::MDAlgorithms::CompareMDWorkspaces::compareMDEventWorkspaces(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::compressEventsOutputWS(), Mantid::Kernel::ConfigServiceImpl::ConfigServiceImpl(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::conjoinWorkspaces(), Mantid::Algorithms::AnyShapeAbsorption::constructGaugeVolume(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::constructGaugeVolume(), Mantid::Algorithms::AbsorptionCorrection::constructSample(), Mantid::DataHandling::LoadSESANS::consumeData(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::convertSpiceMatrixToMomentumMDEvents(), Mantid::DataHandling::SaveGSASInstrumentFile::convertToGSAS(), Mantid::Algorithms::DetectorDiagnostic::convertToRate(), Mantid::Algorithms::PDFFourierTransform2::convertToSQMinus1(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::convertUnits(), Mantid::Algorithms::DiffractionFocussing::convertUnitsToDSpacing(), Mantid::MDAlgorithms::ConvertToMD::copyMetaData(), Mantid::Algorithms::CorrectTOFAxis::correctManually(), Mantid::DataHandling::LoadTOFRawNexus::countPixels(), Mantid::DataHandling::LoadMuonStrategy::createDetectorGroupingTable(), Mantid::Algorithms::FindPeaks::createFunctions(), Mantid::MDAlgorithms::SlicingAlgorithm::createGeneralTransform(), MantidQt::API::InterfaceManager::createHelpWindow(), Mantid::DataHandling::LoadSpiceXML2DDet::createMatrixWorkspace(), Mantid::CurveFitting::Algorithms::LeBailFit::createOutputDataWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::createOutputWorkspace(), Mantid::MDAlgorithms::GetSpiceDataRawCountsFromMD::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::MDAlgorithms::FindPeaksMD::createPeak(), Mantid::DataObjects::PeaksWorkspace::createPeakQSample(), Mantid::DataHandling::SaveCanSAS1D2::createSASProcessElement(), Mantid::Algorithms::PDCalibration::createTOFPeakCenterFitWindowWorkspaces(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::createVirtualInstrument(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::cropWorkspace(), Mantid::Algorithms::InterpolatingRebin::cubicInterpolation(), Mantid::WorkflowAlgorithms::LoadEventAndCompress::determineChunk(), Mantid::Algorithms::PDFFourierTransform2::determineMaxIndex(), Mantid::Algorithms::PDFFourierTransform2::determineMinIndex(), Mantid::Algorithms::PDFFourierTransform::determineQmaxIndex(), Mantid::Algorithms::PDFFourierTransform::determineQminIndex(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::diffractionFocus(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::diffractionFocusRaggedRebinInDspace(), Mantid::DataHandling::LoadNexusProcessed::doAccelleratedMultiPeriodLoading(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::Algorithms::MedianDetectorTest::doDetectorTests(), Mantid::ICat::CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(), Mantid::MDAlgorithms::MergeMDFiles::doExecByCloning(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSequential(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSimple(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doFitFunction(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitGaussianPeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitMultiplePeaks(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitNPeaksSimple(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::MDAlgorithms::LoadMD::doLoad(), Mantid::DataHandling::LoadFITS::doLoadFiles(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::editInstrument(), Mantid::Algorithms::FindPeakBackground::estimateBackground(), Mantid::Algorithms::EstimateResolutionDiffraction::estimateDetectorResolution(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::estimatePeakHeightsLeBail(), Mantid::Algorithms::FindPeaks::estimatePeakParameters(), Mantid::Algorithms::CreateSampleWorkspace::evalFunction(), Mantid::Algorithms::AbsorptionCorrection::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::CalculateCarpenterSampleCorrection::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CloneWorkspace::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::ConvertToMatrixWorkspace::exec(), Mantid::Algorithms::ConvertUnits::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectKiKf::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateLogTimeCorrection::exec(), Mantid::Algorithms::CreatePSDBleedMask::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DetectorDiagnostic::exec(), Mantid::Algorithms::DiffractionEventCalibrateDetectors::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::EditInstrumentGeometry::exec(), Mantid::Algorithms::ElasticWindow::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FilterByLogValue::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::FindDetectorsOutsideLimits::exec(), Mantid::Algorithms::FindPeaks::exec(), Mantid::Algorithms::FitPeak::exec(), Mantid::Algorithms::GeneralisedSecondDifference::exec(), Mantid::Algorithms::GenerateGoniometerIndependentBackground::exec(), Mantid::Algorithms::GenerateIPythonNotebook::exec(), Mantid::Algorithms::GeneratePythonScript::exec(), Mantid::Algorithms::GetEi::exec(), Mantid::Algorithms::IntegrateByComponent::exec(), Mantid::Algorithms::MaxEnt::exec(), Mantid::Algorithms::MedianDetectorTest::exec(), Mantid::Algorithms::NormaliseByCurrent::exec(), Mantid::Algorithms::PaalmanPingsAbsorptionCorrection::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::RayTracerTester::exec(), Mantid::Algorithms::Rebin::exec(), Mantid::Algorithms::RebinRagged::exec(), Mantid::Algorithms::RebinToWorkspace::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::ResampleX::exec(), Mantid::Algorithms::ResetNegatives::exec(), Mantid::Algorithms::SassenaFFT::exec(), Mantid::Algorithms::SmoothData::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Algorithms::VesuvioL1ThetaResolution::exec(), Mantid::Crystal::CountReflections::exec(), Mantid::Crystal::FindGoniometerAngles::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::PredictSatellitePeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::exec(), Mantid::CurveFitting::Algorithms::PawleyFit::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::exec(), Mantid::CurveFitting::Algorithms::VesuvioCalculateMS::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::ApplyDiffCal::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadFile::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::LoadCSNSNexus::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventPreNexus2::exec(), Mantid::DataHandling::LoadInstrumentFromRaw::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMask::exec(), Mantid::DataHandling::LoadMcStasNexus::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::LoadNexusProcessed::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadParameterFile::exec(), Mantid::DataHandling::LoadPreNexusMonitors::exec(), Mantid::DataHandling::LoadRaw3::exec(), Mantid::DataHandling::LoadRKH::exec(), Mantid::DataHandling::LoadSassena::exec(), Mantid::DataHandling::LoadSESANS::exec(), Mantid::DataHandling::MaskDetectors::exec(), Mantid::DataHandling::MaskDetectorsInShape::exec(), Mantid::DataHandling::SaveDiffCal::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveFullprofResolution::exec(), Mantid::DataHandling::SaveMask::exec(), Mantid::DataHandling::SetSampleMaterial::exec(), Mantid::ICat::CatalogDownloadDataFiles::exec(), Mantid::MDAlgorithms::ChangeQConvention::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::CutMD::exec(), Mantid::MDAlgorithms::IntegrateMDHistoWorkspace::exec(), Mantid::MDAlgorithms::LoadMD::exec(), Mantid::MDAlgorithms::MergeMD::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsReduction::exec(), Mantid::WorkflowAlgorithms::EQSANSLoad::exec(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::DataHandling::SaveFITS::exec(), Mantid::Algorithms::CorrectKiKf::execEvent(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Algorithms::He3TubeEfficiency::execEvent(), Mantid::Algorithms::HyspecScharpfCorrection::execEvent(), Mantid::Algorithms::MergeRuns::execEvent(), Mantid::Algorithms::ModeratorTzeroLinear::execEvent(), Mantid::Algorithms::ScaleX::execEvent(), Mantid::Algorithms::UnaryOperation::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::Algorithms::ModeratorTzero::execEvent(), Mantid::DataHandling::LoadEventNexus::execLoader(), Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::DataHandling::MaskDetectors::execPeaks(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), MantidQt::API::BatchAlgorithmRunner::executeAlgo(), MantidQt::API::BatchAlgorithmRunner::executeBatchAsyncImpl(), Mantid::Algorithms::SmoothNeighbours::execWorkspace2D(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exportEvents(), Mantid::Algorithms::NormaliseByCurrent::extractCharge(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::extractSpectrum(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::extractValidSampleObject(), Mantid::Crystal::PredictPeaks::fillPossibleHKLsUsingGenerator(), Mantid::DataHandling::LoadEventNexus::filterEventsByTime(), Mantid::CurveFitting::Functions::ProcessBackground::filterForBackground(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::filterResonances(), Mantid::MDAlgorithms::MergeMDFiles::finalizeOutput(), Mantid::MDAlgorithms::ConvertToMD::findMinMax(), Mantid::Algorithms::FindPeaks::findPeakBackground(), Mantid::Algorithms::StripPeaks::findPeaks(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::Algorithms::FindPeaks::findPeaksGivenStartingPoints(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::API::FileFinderImpl::findRun(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), Mantid::Algorithms::CalculateTransmission::fit(), Mantid::CurveFitting::Functions::ProcessBackground::fitBackgroundFunction(), Mantid::Algorithms::CalculateTransmission::fitData(), Mantid::Algorithms::FindEPP::fitGaussian(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::fitInstrumentParameters(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitOverlappedPeaks(), Mantid::Algorithms::FindPeaks::fitPeakGivenFWHM(), Mantid::Algorithms::FindPeaks::fitPeakInWindow(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksRobust(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksWithGoodStartingValues(), Mantid::Algorithms::FindPeaks::fitSinglePeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::CalculateTransmissionBeamSpreader::fitToData(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak(), Mantid::CurveFitting::Algorithms::LeBailFunction::function(), Mantid::Algorithms::GenerateEventsFilter::generateSplittersInMatrixWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeakCentersWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::genPeaksFromTable(), Mantid::DataHandling::FindDetectorsPar::get_my_line(), Mantid::API::ExperimentInfo::getAvailableWorkspaceEndDate(), Mantid::API::ExperimentInfo::getAvailableWorkspaceStartDate(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getEfficiencyCoefficient2(), Mantid::Algorithms::Stitch1D::getEndOverlap(), Mantid::DataHandling::DetermineChunking::getFileType(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::getFilterROI(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient1(), Mantid::Algorithms::CalculatePlaczek::getFluxCoefficient2(), Mantid::Algorithms::EstimateScatteringVolumeCentreOfMass::getGaugeVolumeObject(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::Algorithms::SumOverlappingTubes::getHeightAxis(), Mantid::Algorithms::PDDetermineCharacterizations::getInformationFromTable(), Mantid::DataHandling::CreateChunkingFromInstrument::getInstrument(), Mantid::DataHandling::LoadDiffCal::getInstrument(), Mantid::Algorithms::PDDetermineCharacterizations::getLogValue(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getMonitorCounts(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getPeakInformation(), Mantid::Kernel::Quat::getRotation(), Mantid::Algorithms::SumOverlappingTubes::getScatteringAngleBinning(), Mantid::DataHandling::LoadHFIRSANS::getSourceToSampleDistance(), Mantid::Algorithms::Stitch1D::getStartOverlap(), Mantid::Algorithms::Q1DWeighted::getTableShapes(), Mantid::Algorithms::RemoveLowResTOF::getTminData(), Mantid::WorkflowAlgorithms::EQSANSMonitorTOF::getTofOffset(), Mantid::Algorithms::EQSANSTofStructure::getTofOffset(), Mantid::Algorithms::UnwrapSNS::getTofRangeData(), Mantid::API::ExperimentInfo::getWorkspaceStartDate(), Mantid::Algorithms::CreateCalFileByNames::groupingFileDoesExist(), Mantid::Algorithms::CreateDummyCalFile::groupingFileDoesExist(), Mantid::CurveFitting::Algorithms::LeBailFunction::groupPeaks(), MantidQt::API::RepoModel::handleExceptions(), Mantid::Algorithms::GeneratePeaks::importPeaksFromTable(), Mantid::MDAlgorithms::ConvToMDBase::initialize(), Mantid::DataHandling::LoadMask::initializeXMLParser(), Mantid::Algorithms::SofQWPolygon::initThetaCache(), Mantid::Algorithms::RadiusSum::inputValidationSanityCheck(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::Algorithms::FindDeadDetectors::integrateWorkspace(), Mantid::Algorithms::Stitch1D::integration(), Mantid::DataHandling::LoadFITS::isInstrOtherThanIMAT(), Mantid::CurveFitting::Algorithms::LeBailFunction::isParameterValid(), Mantid::Algorithms::ConvertToHistogram::isProcessingRequired(), Mantid::Algorithms::ConvertToPointData::isProcessingRequired(), Mantid::MDAlgorithms::LoadMD::loadAffineMatrix(), Mantid::DataHandling::LoadTOFRawNexus::loadBank(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::loadCalFile(), Mantid::DataHandling::LoadILLIndirect2::loadDataDetails(), Mantid::DataHandling::LoadMuonStrategy::loadDefaultDetectorGrouping(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadEventNexus::loadEvents(), Mantid::DataObjects::MDBoxFlatTree::loadExperimentInfos(), Mantid::DataObjects::MDBoxFlatTree::loadExperimentInfos(), Mantid::DataHandling::LoadDiffCal::loadGroupingFromAlternateFile(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::MDAlgorithms::LoadMD::loadHisto(), Mantid::Algorithms::CorrectToFile::loadInFile(), Mantid::Algorithms::VesuvioL1ThetaResolution::loadInstrument(), Mantid::DataHandling::LoadSwans::loadInstrument(), Mantid::API::ExperimentInfo::loadInstrumentParametersNexus(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadILLSANS::loadMetaData(), Mantid::DataHandling::LoadIDFFromNexus::loadParameterFile(), Mantid::DataHandling::LoadNexusProcessed::loadPeaksEntry(), Mantid::DataHandling::LoadEventPreNexus2::loadPixelMap(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::loadRunToMatrixWS(), Mantid::DataHandling::Load::loadSingleFile(), Mantid::DataHandling::LoadNGEM::loadSingleFile(), Mantid::DataHandling::LoadLog::LoadSNSText(), Mantid::Algorithms::CreateLogTimeCorrection::logGeometryInformation(), Mantid::Algorithms::CalculateTransmission::logIfNotMonitor(), Mantid::DataHandling::SaveSPE::logMissingMasked(), Mantid::Kernel::LogParser::LogParser(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::DataHandling::LoadDiffCal::makeGroupingWorkspace(), Mantid::DataHandling::LoadDiffCal::makeMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog(), Mantid::WorkflowAlgorithms::EQSANSLoad::moveToBeamCenter(), Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter(), Mantid::DataHandling::LoadEventPreNexus2::openEventFile(), Mantid::DataHandling::SaveCanSAS1D::openForAppending(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBackgroundTableWorkspace(), Mantid::CurveFitting::Algorithms::LeBailFit::parseBraggPeaksParametersTable(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseBraggPeakTable(), Mantid::DataHandling::LoadPDFgetNFile::parseColumnNameLine(), Mantid::Algorithms::MultipleScatteringCorrection::parseInputs(), Mantid::CurveFitting::Algorithms::LeBailFit::parseInstrumentParametersTable(), Mantid::DataHandling::SaveGSASInstrumentFile::parseProfileTableWorkspace(), Mantid::DataHandling::LoadMask::parseXML(), Mantid::DataObjects::PeakColumn< T >::PeakColumn(), Mantid::Algorithms::GetAllEi::peakGuess(), Mantid::DataHandling::LoadSwans::placeDetectorInSpace(), Mantid::API::ExperimentInfo::populateInstrumentParameters(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::prepareStructureFactors(), Mantid::MDAlgorithms::PreprocessDetectorsToMD::processDetectorsPositions(), Mantid::DataHandling::SaveNexusESS::processGroups(), Mantid::DataHandling::SaveNexusProcessed::processGroups(), Mantid::DataHandling::LoadAscii2::processHeader(), Mantid::DataHandling::LoadAscii::processHeader(), Mantid::DataHandling::LoadEventPreNexus2::processImbedLogs(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputBackground(), Mantid::Algorithms::GenerateEventsFilter::processInputTime(), Mantid::Algorithms::RadiusSum::processInstrumentRadiusSum(), Mantid::Algorithms::RingProfile::processInstrumentRingProfile(), Mantid::Algorithms::GenerateEventsFilter::processIntegerValueFilter(), Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters(), Mantid::Kernel::InternetHelper::processRelocation(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear(), Mantid::CurveFitting::Algorithms::LeBailFit::proposeNewBackgroundValues(), Mantid::DataHandling::LoadRKH::read1D(), Mantid::DataHandling::LoadRKH::read2D(), Mantid::Nexus::H5Util::readArray1DCoerce(), Mantid::Nexus::H5Util::readArray1DCoerce(), Mantid::Algorithms::Bin2DPowderDiffraction::ReadBinsFromFile(), Mantid::WorkflowAlgorithms::EQSANSLoad::readConfigFile(), Mantid::MDAlgorithms::LoadSQW::readEvents(), Mantid::DataHandling::LoadEventPreNexus2::readPulseidFile(), Mantid::DataHandling::LoadNexusProcessed2::readSpectraToDetectorMapping(), Mantid::DataHandling::LoadRawHelper::readTitle(), Mantid::DataHandling::PDLoadCharacterizations::readVersion1(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::rebin(), Mantid::Algorithms::PDCalibration::rebin(), Mantid::Algorithms::Stitch1D::rebin(), Mantid::Algorithms::Rebin::rebinParamsFromInput(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::rebinRagged(), Mantid::Algorithms::DiffractionFocussing::RebinWorkspace(), Mantid::Geometry::Goniometer::recalculateR(), Mantid::Algorithms::CreateFloodWorkspace::removeBackground(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::Algorithms::CylinderAbsorption::retrieveProperties(), Mantid::DataHandling::LoadEmptyInstrument::runLoadIDFFromNexus(), Mantid::DataHandling::LoadEventNexus::runLoadIDFFromNexus(), Mantid::DataHandling::LoadHFIRSANS::runLoadInstrument(), Mantid::DataHandling::LoadSINQFocus::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadInstrument(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadInstrument(), Mantid::DataHandling::LoadCanSAS1D::runLoadInstrument(), Mantid::DataHandling::LoadSpice2D::runLoadInstrument(), Mantid::DataHandling::LoadPreNexusMonitors::runLoadInstrument(), Mantid::DataHandling::LoadEventNexus::runLoadInstrument(), Mantid::DataHandling::LoadISISNexus2::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadNexusMonitors2::runLoadLogs(), Mantid::DataHandling::LoadEventNexus::runLoadMonitors(), Mantid::DataHandling::SNSAppendGeometryToNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadInstrument::runLoadParameterFile(), Mantid::DataHandling::SaveCalFile::saveCalFile(), Mantid::Algorithms::CreateFloodWorkspace::scaleToCentralPixel(), MantidQt::API::ScriptRepositoryView::ScriptRepositoryView(), Mantid::API::DetectorSearcher::searchUsingNearestNeighbours(), Mantid::Kernel::ErrorReporter::sendReport(), Mantid::Kernel::UsageServiceImpl::sendReport(), Mantid::DataHandling::UpdateInstrumentFromFile::setDetectorPositions(), Mantid::Algorithms::GenerateEventsFilter::setFilterByLogValue(), Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterValues(), Mantid::MDAlgorithms::LoadMD::setMDFrameOnWorkspaceFromLegacyFile(), Mantid::DataHandling::FindDetectorsPar::setOutputTable(), Mantid::DataHandling::LoadEventPreNexus2::setProtonCharge(), Mantid::DataObjects::LeanElasticPeak::setQSampleFrame(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupBackground(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupBackground(), Mantid::CurveFitting::Algorithms::LeBailFit::setupBuiltInRandomWalkStrategy(), Mantid::DataHandling::SaveGSASInstrumentFile::setupInstrumentConstants(), Mantid::CurveFitting::Algorithms::LeBailFit::setupRandomWalkStrategyFromTable(), Mantid::DataHandling::LoadSpiceAscii::setupRunStartTime(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogs(), Mantid::WorkflowAlgorithms::SetupEQSANSReduction::setupTransmission(), Mantid::WorkflowAlgorithms::SetupHFIRReduction::setupTransmission(), Mantid::Algorithms::SmoothNeighbours::setWeightingStrategy(), Mantid::CurveFitting::Functions::InelasticDiffRotDiscreteCircle::setWorkspace(), Mantid::CurveFitting::Functions::InelasticDiffSphere::setWorkspace(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::shouldCompressUnfocused(), Mantid::Kernel::TimeSeriesProperty< TYPE >::sortIfNecessary(), Mantid::Algorithms::SmoothNeighbours::spreadPixels(), Mantid::Algorithms::FindCenterOfMassPosition2::storeOutputWorkspace(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataHandling::LoadEventPreNexus2::unmaskVetoEventIndex(), Mantid::Algorithms::UnwrapMonitor::unwrapX(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromNeXus(), Mantid::DataHandling::UpdateInstrumentFromFile::updateFromRaw(), Mantid::Algorithms::Rebin::validateInputs(), Mantid::Geometry::vtkGeometryCacheWriter::write(), Mantid::Geometry::InstrumentDefinitionParser::writeAndApplyCache(), Mantid::DataHandling::SaveAscii2::writeSpectrum(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlParseDetectorNode().
is()
bool Mantid::Kernel::Logger::is (int level) const
Returns true if at least the given log level is set.
Parameters
level :: The logging level it is best to use the Logger::Priority enum (7=debug, 6=information, 4=warning, 3=error, 2=critical, 1=fatal)
Returns
true if at least the given log level is set.
Definition at line 177 of file Logger.cpp.
References m_log.
Referenced by Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::applyCorrection(), Mantid::CurveFitting::Algorithms::VesuvioCalculateGammaBackground::cacheInstrumentGeometry(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::Algorithms::SplineBackground::calculateBinWeight(), Mantid::Algorithms::CompareWorkspaces::checkData(), Mantid::Algorithms::CompareWorkspaces::checkRunProperties(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::createConstraintMatrices(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::AddAbsorptionWeightedPathLengths::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::SofQWNormalisedPolygon::exec(), Mantid::CurveFitting::Algorithms::NormaliseByPeakArea::fitToMassPeak(), Mantid::DataHandling::ISISDataArchive::getArchivePath(), Mantid::Algorithms::GetEi2::getDistanceFromSource(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::getResidualVariance(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesNonPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesPSD(), Mantid::Algorithms::SofQWNormalisedPolygon::initAngularCachesTable(), isDebug(), Mantid::DataHandling::LoadSampleEnvironment::loadEnvironmentFromSTL(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog(), Mantid::Kernel::LibraryManagerImpl::openLibrary(), Mantid::Algorithms::Integration::rangeFilterEventWorkspace(), Mantid::MDAlgorithms::LoadSQW2::readMainHeader(), Mantid::MDAlgorithms::LoadSQW2::readSingleSPEHeader(), Mantid::MDAlgorithms::LoadSQW2::readSQWDimensions(), Mantid::Algorithms::AnnularRingAbsorption::runCreateSampleShape(), Mantid::Algorithms::AnnularRingAbsorption::runMonteCarloAbsorptionCorrection(), MantidQt::API::PythonRunner::runPythonCode(), Mantid::Algorithms::AnnularRingAbsorption::runSetSampleMaterial(), Mantid::PythonInterface::RunPythonScript::scriptCode(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setFixedParameterValues(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::setMatrixWorkspace(), MantidQt::MantidWidgets::ImageInfoModelMatrixWS::setUnitsInfo(), Mantid::MDAlgorithms::LoadSQW2::skipDetectorSection(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::start_point(), Mantid::DataHandling::SetSample::tryCreateXMLFromArgsOnly(), Mantid::CurveFitting::Functions::ComptonScatteringCountRate::updateCMatrixValues(), and Mantid::Algorithms::DiscusMultipleScatteringCorrection::updateWeightAndPosition().
isDebug()
bool Mantid::Kernel::Logger::isDebug () const
Returns true if log level is at least debug.
Definition at line 189 of file Logger.cpp.
References is().
Referenced by Mantid::DataHandling::ProcessBankCompressed::addToEventLists(), Mantid::DataHandling::ProcessBankCompressed::collectEvents(), Mantid::DataHandling::LoadBankFromDiskTask::run(), and Mantid::DataHandling::traceStatistics().
log()
void Mantid::Kernel::Logger::log (const std::string & message, const Priority & priority)
Log a message at a given priority.
Parameters
message :: The message to log
priority :: The priority level
Definition at line 359 of file Logger.cpp.
References applyLevelOffset(), m_enabled, and m_log.
Referenced by debug(), error(), fatal(), flush(), flush(), information(), notice(), Mantid::Kernel::ConfigServiceImpl::setLogLevel(), Mantid::Kernel::ConfigServiceImpl::setLogLevel(), and warning().
notice() [1/2]
std::ostream & Mantid::Kernel::Logger::notice ()
Logs at notice level.
This class implements an ostream interface to the Logger for notice messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 260 of file Logger.cpp.
References getLogStream().
notice() [2/2]
void Mantid::Kernel::Logger::notice (const std::string & msg)
Logs at notice level.
If the Logger's log level is at least Poco::Message::PRIO_NOTICE, creates a Message with priority Poco::Message::PRIO_NOTICE and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 126 of file Logger.cpp.
References log().
Referenced by Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::addMDEvents(), Mantid::MDAlgorithms::FindPeaksMD::addPeak(), Mantid::Crystal::SCDCalibratePanels2::adjustComponent(), Mantid::Algorithms::EstimateResolutionDiffraction::calcCentreVelocity(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::Algorithms::MultipleScatteringCorrection::calculateLS1s(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSampleAndContainer(), Mantid::Algorithms::MultipleScatteringCorrection::calculateSingleComponent(), Mantid::Algorithms::GetTimeSeriesLogInformation::calDistributions(), Mantid::Algorithms::RingProfile::checkInputsForNumericWorkspace(), Mantid::Algorithms::GetTimeSeriesLogInformation::checkLogBasicInforamtion(), Mantid::Algorithms::MergeRuns::checkRebinning(), Mantid::Crystal::ClearUB::clearSingleExperimentInfo(), Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::Algorithms::GetEiMonDet3::computeTOF(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::convertFromQSampleToHKL(), Mantid::Algorithms::GeneratePeaks::createOutputWorkspace(), Mantid::MDAlgorithms::IntegratePeaksCWSD::createPeakworkspace(), Mantid::DataHandling::SaveCanSAS1D::createSASDetectorElement(), Mantid::MDAlgorithms::SlicingAlgorithm::createTransform(), Mantid::MDAlgorithms::CloneMDWorkspace::doClone(), Mantid::MDAlgorithms::MergeMDFiles::doExecByCloning(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakBackground(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFit1PeakSequential(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitMultiplePeaks(), Mantid::Algorithms::CompareWorkspaces::doLeanElasticPeaksComparison(), Mantid::CurveFitting::Algorithms::LeBailFit::doMarkovChain(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::doParameterSpaceRandomWalk(), Mantid::Algorithms::CompareWorkspaces::doPeaksComparison(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doSimulatedAnnealing(), Mantid::Kernel::TimeSeriesProperty< TYPE >::eliminateDuplicates(), Mantid::MDAlgorithms::IntegrateQLabEvents::ellipseIntegrateEvents(), Mantid::Algorithms::EstimateResolutionDiffraction::estimateDetectorResolution(), Mantid::Algorithms::FilterEvents::examineEventWS(), Mantid::Algorithms::AddLogDerivative::exec(), Mantid::Algorithms::AddLogInterpolated::exec(), Mantid::Algorithms::AddLogSmoothed::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::CorelliCalibrationApply::exec(), Mantid::Algorithms::DetectorEfficiencyVariation::exec(), Mantid::Algorithms::DetermineSpinStateOrder::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::ExtractMaskToTable::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FindDeadDetectors::exec(), Mantid::Algorithms::GetEi::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::Pause::exec(), Mantid::Algorithms::PDCalibration::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::PolarizationCorrectionFredrikze::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Algorithms::RemovePromptPulse::exec(), Mantid::Algorithms::Stitch1D::exec(), Mantid::Algorithms::TOFSANSResolutionByPixel::exec(), Mantid::Crystal::ConvertPeaksWorkspace::exec(), Mantid::Crystal::FindUBUsingFFT::exec(), Mantid::Crystal::FindUBUsingIndexedPeaks::exec(), Mantid::Crystal::FindUBUsingLatticeParameters::exec(), Mantid::Crystal::GoniometerAnglesFromPhiRotation::exec(), Mantid::Crystal::IndexPeaks::exec(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::OptimizeCrystalPlacement::exec(), Mantid::Crystal::OptimizeLatticeForCellType::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SelectCellOfType::exec(), Mantid::Crystal::SelectCellWithForm::exec(), Mantid::Crystal::ShowPossibleCells::exec(), Mantid::Crystal::TransformHKL::exec(), Mantid::CurveFitting::Algorithms::LeBailFit::exec(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::DetermineChunking::exec(), Mantid::DataHandling::DownloadInstrument::exec(), Mantid::DataHandling::LoadAscii2::exec(), Mantid::DataHandling::LoadIDFFromNexus::exec(), Mantid::DataHandling::SaveAscii::exec(), Mantid::DataHandling::SaveAscii2::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::ICat::CatalogLogin::exec(), Mantid::ICat::CatalogPublish::exec(), Mantid::MDAlgorithms::AccumulateMD::exec(), Mantid::MDAlgorithms::CompareMDWorkspaces::exec(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::exec(), Mantid::MDAlgorithms::ConvertCWSDMDtoHKL::exec(), Mantid::MDAlgorithms::CreateMDWorkspace::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsTwoStep::exec(), Mantid::MDAlgorithms::IntegrateEllipsoidsV1::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::WorkflowAlgorithms::DgsAbsoluteUnitsReduction::exec(), Mantid::WorkflowAlgorithms::DgsConvertToEnergyTransfer::exec(), Mantid::WorkflowAlgorithms::DgsDiagnose::exec(), Mantid::WorkflowAlgorithms::DgsPreprocessData::exec(), Mantid::WorkflowAlgorithms::DgsProcessDetectorVanadium::exec(), Mantid::WorkflowAlgorithms::DgsReduction::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::execConcrete(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::execFitParametersMC(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::execFitParametersNonMC(), Mantid::DataHandling::LoadNexusLogs::execLoader(), Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::CurveFitting::Algorithms::LeBailFit::execRefineBackground(), Mantid::Algorithms::GetTimeSeriesLogInformation::exportErrorLog(), Mantid::Algorithms::ExtractMaskToTable::extractMaskFromMatrixWorkspace(), Mantid::Kernel::FacilityInfo::fillTimezone(), Mantid::DataHandling::LoadEventNexus::filterDuringPause(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), Mantid::MDAlgorithms::MergeMDFiles::finalizeOutput(), Mantid::Crystal::SCDCalibratePanels::findL1(), Mantid::Crystal::SCDCalibratePanels::findL2(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::Crystal::SCDCalibratePanels::findT0(), Mantid::Crystal::SCDCalibratePanels::findU(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::fitFunction(), Mantid::Algorithms::FindEPP::fitGaussian(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksRobust(), Mantid::Algorithms::CalculateTransmission::fitPolynomial(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakConfident(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::GetDetectorOffsets::fitSpectra(), Mantid::API::FrameworkManagerImpl::FrameworkManagerImpl(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::function(), Mantid::Crystal::SCDCalibratePanels2::generateCalibrationTable(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable(), Mantid::DataHandling::LoadFullprofResolution::genTableWorkspace(), Mantid::DataHandling::LoadGSASInstrumentFile::genTableWorkspace(), Mantid::DataHandling::LoadSpiceXML2DDet::getHB3AWavelength(), Mantid::API::Run::getProtonCharge(), Mantid::Algorithms::Qxy::getQminFromWs(), Mantid::DataHandling::MaskDetectors::handleMaskByMaskWorkspace(), Mantid::DataHandling::MaskDetectors::handleMaskByMatrixWorkspace(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::importInstrumentParameterFromTable(), Mantid::Algorithms::GeneratePeaks::importPeaksFromTable(), Mantid::Algorithms::RadiusSum::inputValidationSanityCheck(), Mantid::MDAlgorithms::MergeMDFiles::loadBoxData(), Mantid::DataHandling::LoadILLDiffraction::loadDataScan(), Mantid::DataHandling::LoadNexusProcessed::loadLeanElasticPeaksEntry(), Mantid::DataHandling::LoadIDFFromNexus::loadParameterFile(), Mantid::DataHandling::LoadIDFFromNexus::LoadParameters(), Mantid::Crystal::FindUBUsingIndexedPeaks::logLattice(), Mantid::Algorithms::FitPeaks::logNoOffset(), Mantid::Crystal::PredictPeaks::logNumberOfPeaksFound(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues(), Mantid::Crystal::SCDCalibratePanels2::optimizeBanks(), Mantid::Crystal::SCDCalibratePanels2::optimizeL1(), Mantid::Crystal::SCDCalibratePanels2::optimizeSamplePos(), Mantid::Crystal::SCDCalibratePanels2::optimizeT0(), Mantid::MDAlgorithms::IntegrateEllipsoidsV2::outputAxisProfiles(), Mantid::DataHandling::LoadPDFgetNFile::parseDataFile(), Mantid::DataHandling::LoadSpice2D::parseDetectorDimensions(), Mantid::DataHandling::LoadHFIRSANS::parseDetectorDimensions(), Mantid::Algorithms::CompareWorkspaces::processGroups(), Mantid::Algorithms::RenameWorkspace::processGroups(), Mantid::DataHandling::LoadEventPreNexus2::processImbedLogs(), Mantid::Algorithms::FitPeaks::processInputPeakCenters(), Mantid::DataHandling::LoadEventPreNexus2::procEvents(), Mantid::Crystal::SCDCalibratePanels2::profileBanks(), Mantid::Crystal::SCDCalibratePanels2::profileL1(), Mantid::Crystal::SCDCalibratePanels2::profileL1T0(), Mantid::Crystal::SCDCalibratePanels2::profileT0(), Mantid::Algorithms::SANSCollimationLengthEstimator::provideCollimationLength(), Mantid::DataHandling::LoadPSIMuonBin::readInTemperatureFile(), Mantid::DataHandling::LoadIDFFromNexus::readParameterCorrectionFile(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::refineInstrumentParametersMC(), Mantid::API::Algorithm::reportCompleted(), Mantid::Crystal::AnvredCorrection::retrieveBaseProperties(), Mantid::DataHandling::LoadHFIRSANS::rotateDetector(), Mantid::DataHandling::LoadSpice2D::rotateDetector(), Mantid::DataHandling::LoadPreNexus::runLoadNexusLogs(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveIsawDetCal(), Mantid::Crystal::SCDCalibratePanels::saveXmlFile(), Mantid::Crystal::SCDCalibratePanels2::saveXmlFile(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setFunctionParameterFitSetups(), Mantid::CurveFitting::Algorithms::LeBailFit::setupBuiltInRandomWalkStrategy(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::setupRandomWalkStrategy(), Mantid::MDAlgorithms::IntegratePeaksCWSD::simplePeakIntegration(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::DataHandling::SaveRKH::write1D(), Mantid::Geometry::InstrumentDefinitionParser::writeAndApplyCache(), Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceKnownGeometry(), and Mantid::DataHandling::LoadSpiceXML2DDet::xmlCreateMatrixWorkspaceUnknowGeometry().
operator=()
Logger & Mantid::Kernel::Logger::operator= (const Logger &) private
Disable assignment.
purge()
void Mantid::Kernel::Logger::purge ()
flushes the accumulated messages without logging them
Definition at line 317 of file Logger.cpp.
References m_logStream.
Referenced by export_Logger().
setEnabled()
void Mantid::Kernel::Logger::setEnabled (const bool enabled)
set if the logging is enabled
Parameters
enabled :: true - logging is enabled, false - all messages are ignored.
Definition at line 90 of file Logger.cpp.
References m_enabled.
Referenced by Mantid::CurveFitting::Functions::ComptonProfile::function1D(), and Mantid::API::Algorithm::setLogging().
setLevel() [1/2]
void Mantid::Kernel::Logger::setLevel (const std::string & level)
Sets the Logger's log level using a symbolic value.
Parameters
level :: Valid values are: fatal, critical, error, warning, notice, information, debug, trace
Definition at line 206 of file Logger.cpp.
References m_log.
setLevel() [2/2]
void Mantid::Kernel::Logger::setLevel (int level)
Sets the Logger's log level.
Definition at line 191 of file Logger.cpp.
References m_log.
setLevelForAll() [1/2]
void Mantid::Kernel::Logger::setLevelForAll (const int level) static
Sets the log level for all Loggers created so far, including the root logger.
Parameters
level :: the priority level to set for the loggers
Definition at line 337 of file Logger.cpp.
Referenced by MantidQt::MantidWidgets::QtSignalChannel::setGlobalLogLevel(), setLevelForAll(), Mantid::Kernel::ConfigServiceImpl::setLogLevel(), and Mantid::Kernel::ConfigServiceImpl::setLogLevel().
setLevelForAll() [2/2]
void Mantid::Kernel::Logger::setLevelForAll (const std::string & level) static
Definition at line 350 of file Logger.cpp.
References setLevelForAll().
setLevelOffset()
void Mantid::Kernel::Logger::setLevelOffset (int level)
Sets the Logger's log offset level.
Parameters
level :: The level offset to use
Definition at line 461 of file Logger.cpp.
References m_levelOffset.
Referenced by Mantid::API::Algorithm::setLoggingOffset().
setName()
void Mantid::Kernel::Logger::setName (const std::string & name)
Update the name of the logger.
Parameters
name The new name
Definition at line 69 of file Logger.cpp.
References m_log, m_logStream, name, and Mantid::Kernel::swap().
Referenced by Mantid::API::Algorithm::initialize().
shutdown()
void Mantid::Kernel::Logger::shutdown () static
Shuts down the logging framework and releases all Loggers.
Static method.
Definition at line 322 of file Logger.cpp.
Referenced by Mantid::Kernel::ConfigServiceImpl::~ConfigServiceImpl(), and LoggingCleaner::~LoggingCleaner().
warning() [1/2]
std::ostream & Mantid::Kernel::Logger::warning ()
Logs at warning level.
This class implements an ostream interface to the Logger for warning messages.
The stream's buffer appends all characters written to it to a string. As soon as a CR or LF (std::endl) is written, the string is sent to the Logger.
Returns
an std::ostream reference.
Definition at line 250 of file Logger.cpp.
References getLogStream().
warning() [2/2]
void Mantid::Kernel::Logger::warning (const std::string & msg)
Logs at warning level.
If the Logger's log level is at least Poco::Message::PRIO_WARNING, creates a Message with priority Poco::Message::PRIO_WARNING and the given message text and sends it to the attached channel.
Parameters
msg :: The message to log.
Definition at line 117 of file Logger.cpp.
References log().
Referenced by Mantid::CurveFitting::Algorithms::LeBailFunction::addBackgroundFunction(), MantidQt::MantidWidgets::MuonPeriodInfo::addInfo(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::addMDEvents(), Mantid::Geometry::ParameterMap::addPositionCoordinate(), Mantid::Geometry::ParameterMap::addRotationParam(), Mantid::Algorithms::AddSampleLog::addTimeSeriesProperty(), Mantid::Algorithms::ExtractMaskToTable::addToTableWorkspace(), Mantid::API::WorkspaceGroup::addWorkspace(), Mantid::Geometry::InstrumentDefinitionParser::appendAssembly(), Mantid::DataHandling::MaskDetectors::appendToDetectorListFromComponentList(), Mantid::Kernel::SetDefaultWhenProperty::applyChanges(), Mantid::Kernel::SetValueWhenProperty::applyChanges(), Mantid::API::ISISRunLogs::applyLogFiltering(), Mantid::DataHandling::SaveGSS::areAllDetectorsValid(), Mantid::DataHandling::LoadPSIMuonBin::assignOutputWorkspaceParticulars(), Mantid::Geometry::InstrumentDefinitionParser::attrToDouble(), Mantid::CurveFitting::Functions::ProcessBackground::autoBackgroundSelection(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::binMD(), Mantid::CurveFitting::Algorithms::LeBailFit::bookKeepBestMCResult(), Mantid::Algorithms::Q1DWeighted::bootstrap(), Mantid::MDAlgorithms::ConvertToMD::buildTargetWSDescription(), Mantid::Algorithms::CalculateCountRate::buildVisWSNormalization(), Mantid::MDAlgorithms::IntegratePeaksMD2::calcCovar(), Mantid::Algorithms::RemoveLowResTOF::calcTofMin(), Mantid::API::Run::calculateAverageGoniometerMatrix(), Mantid::API::PanelsSurfaceCalculator::calculateBankNormal(), Mantid::CurveFitting::Algorithms::SplineBackground::calculateBinWeight(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::calculateConvChainAndBestParameters(), Mantid::Algorithms::GetEi2::calculateEi(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::calculateFunctionError(), Mantid::CurveFitting::Algorithms::LeBailFunction::calculateGroupPeakIntensities(), Mantid::Algorithms::GetEi2::calculatePeakWidthAtHalfHeight(), Mantid::Algorithms::PolarizationEfficienciesWildes::calculatePolarizerAndAnalyserEfficiencies(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters::calculateThermalNeutronSpecial(), Mantid::Algorithms::ExportTimeSeriesLog::calculateTimeSeriesRangeByTime(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calHandEta(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calHandEta(), Mantid::CurveFitting::Functions::NeutronBk2BkExpConvPVoigt::calOmega(), Mantid::CurveFitting::Functions::ThermalNeutronBk2BkExpConvPVoigt::calOmega(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::calWavelengthAtEachDataPoint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::check(), Mantid::Algorithms::PointByPointVCorrection::check_masks(), Mantid::Algorithms::PointByPointVCorrection::check_validity(), Mantid::Algorithms::CalculateCountRate::checkAndInitVisWorkspace(), Mantid::DataHandling::SaveReflectometryAscii::checkFile(), Mantid::DataHandling::SaveReflectometryAscii::checkGroups(), Mantid::Algorithms::Q1DWeighted::checkIfSuperposedWedges(), Mantid::Algorithms::GetTimeSeriesLogInformation::checkLogBasicInforamtion(), Mantid::MDAlgorithms::IntegratePeaksMD2::checkOverlap(), Mantid::Algorithms::CopyInstrumentParameters::checkProperties(), Mantid::Algorithms::NormaliseToMonitor::checkProperties(), Mantid::Algorithms::SampleLogsBehaviour::checkWarnProperty(), Mantid::Algorithms::CompareWorkspaces::compareEventWorkspaces(), Mantid::DataHandling::LoadMask::componentToDetectors(), Mantid::Algorithms::CreateMonteCarloWorkspace::computeNormalizedCDF(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::constFunction(), Mantid::DataHandling::LoadSESANS::consumeData(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::convergenceCheck(), Mantid::CurveFitting::Algorithms::SplineInterpolation::convertBinnedData(), Mantid::Algorithms::PDFFourierTransform2::convertFromSQMinus1(), Mantid::Algorithms::FitPeaks::convertParametersNameToIndex(), Mantid::Algorithms::MaskBinsFromTable::convertToSpectraList(), Mantid::Algorithms::PDFFourierTransform2::convertToSQMinus1(), Mantid::Algorithms::ConvertUnits::convertViaTOF(), Mantid::MDAlgorithms::SlicingAlgorithm::createAlignedTransform(), Mantid::API::SpectrumInfo::createDetectorIdLogMessages(), Mantid::Geometry::InstrumentDefinitionParser::createDetectorOrMonitor(), Mantid::DataHandling::LoadBBY::createInstrument(), Mantid::DataHandling::LoadBBY2::createInstrument(), Mantid::DataHandling::LoadGSS::createInstrumentGeometry(), Mantid::Kernel::LogParser::createLogProperty(), Mantid::Geometry::ObjCompAssembly::createOutline(), Mantid::DataHandling::LoadNexusMonitors2::createOutputWorkspace(), Mantid::Algorithms::FilterEvents::createOutputWorkspaces(), Mantid::Geometry::ShapeFactory::createShape(), Mantid::Geometry::ShapeFactory::createShape(), Mantid::DataHandling::LoadEventNexus::createSpectraMapping(), Mantid::Algorithms::SumEventsByLogValue::createTableOutput(), Mantid::Algorithms::ConvertSpectrumAxis2::createThetaMap(), Mantid::Kernel::ConfigServiceImpl::createUserPropertiesFile(), Mantid::CurveFitting::Algorithms::LeBailFit::cropWorkspace(), MantidQt::MantidWidgets::FitPropertyBrowser::defaultPeakType(), Mantid::Algorithms::ClearCache::deleteFiles(), Mantid::API::DeprecatedAlgorithm::deprecationMsg(), Mantid::DataHandling::LoadILLReflectometry::detectorRotation(), Mantid::Algorithms::ResampleX::determineBinning(), Mantid::DataHandling::SaveOpenGenieAscii::determineEnginXBankId(), Mantid::Algorithms::CalculateCountRate::disableNormalization(), Mantid::DataHandling::SaveNexusProcessed::doExec(), MantidQt::MantidWidgets::FitPropertyBrowser::doFit(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doFitFunction(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::doFitGaussianPeak(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::doSimulatedAnnealing(), Mantid::Algorithms::MonteCarloAbsorption::doSimulation(), Mantid::Algorithms::CorrectToFile::doWkspAlgebra(), MantidQt::MantidWidgets::FitPropertyBrowser::enactAttributeChange(), Mantid::Algorithms::FilterEvents::examineEventWS(), Mantid::Algorithms::ApplyTransmissionCorrection::exec(), Mantid::Algorithms::AverageLogData::exec(), Mantid::Algorithms::CalculateFlatBackground::exec(), Mantid::Algorithms::CompareWorkspaces::exec(), Mantid::Algorithms::ConjoinXRuns::exec(), Mantid::Algorithms::ConvertAxesToRealSpace::exec(), Mantid::Algorithms::ConvertAxisByFormula::exec(), Mantid::Algorithms::ConvertSpectrumAxis::exec(), Mantid::Algorithms::CopyInstrumentParameters::exec(), Mantid::Algorithms::CopySample::exec(), Mantid::Algorithms::CorelliCrossCorrelate::exec(), Mantid::Algorithms::CorrectToFile::exec(), Mantid::Algorithms::CreateEPP::exec(), Mantid::Algorithms::CreateGroupingWorkspace::exec(), Mantid::Algorithms::CreateMonteCarloWorkspace::exec(), Mantid::Algorithms::CreateSampleWorkspace::exec(), Mantid::Algorithms::CreateWorkspace::exec(), Mantid::Algorithms::CrossCorrelate::exec(), Mantid::Algorithms::DeadTimeCorrection::exec(), Mantid::Algorithms::DeleteLog::exec(), Mantid::Algorithms::DiffractionFocussing::exec(), Mantid::Algorithms::DiscusMultipleScatteringCorrection::exec(), Mantid::Algorithms::EQSANSCorrectFrame::exec(), Mantid::Algorithms::ExtractMask::exec(), Mantid::Algorithms::FilterBadPulses::exec(), Mantid::Algorithms::FilterEvents::exec(), Mantid::Algorithms::FindCenterOfMassPosition::exec(), Mantid::Algorithms::GetEiMonDet3::exec(), Mantid::Algorithms::Integration::exec(), Mantid::Algorithms::IQTransform::exec(), Mantid::Algorithms::MaskBins::exec(), Mantid::Algorithms::MaxMin::exec(), Mantid::Algorithms::MergeRuns::exec(), Mantid::Algorithms::PDDetermineCharacterizations::exec(), Mantid::Algorithms::PDFFourierTransform::exec(), Mantid::Algorithms::PDFFourierTransform2::exec(), Mantid::Algorithms::Q1D2::exec(), Mantid::Algorithms::Qxy::exec(), Mantid::Algorithms::Rebin2D::exec(), Mantid::Algorithms::RemoveSpectra::exec(), Mantid::Algorithms::SetInstrumentParameter::exec(), Mantid::Algorithms::SolidAngle::exec(), Mantid::Algorithms::SpatialGrouping::exec(), Mantid::Algorithms::Stitch1DMany::exec(), Mantid::Algorithms::StripPeaks::exec(), Mantid::Algorithms::SumRowColumn::exec(), Mantid::Algorithms::SumSpectra::exec(), Mantid::Algorithms::TOFSANSResolution::exec(), Mantid::Algorithms::UpdateScriptRepository::exec(), Mantid::Crystal::AnvredCorrection::exec(), Mantid::Crystal::CombinePeaksWorkspaces::exec(), Mantid::Crystal::DiffPeaksWorkspaces::exec(), Mantid::Crystal::FindClusterFaces::exec(), Mantid::Crystal::FindSXPeaks::exec(), Mantid::Crystal::IndexPeaks::exec(), Mantid::Crystal::IndexSXPeaks::exec(), Mantid::Crystal::IntegratePeaksHybrid::exec(), Mantid::Crystal::IntegratePeaksUsingClusters::exec(), Mantid::Crystal::LoadHKL::exec(), Mantid::Crystal::MaskPeaksWorkspace::exec(), Mantid::Crystal::PredictPeaks::exec(), Mantid::Crystal::SaveHKL::exec(), Mantid::Crystal::SaveIsawPeaks::exec(), Mantid::Crystal::SaveLauenorm::exec(), Mantid::Crystal::SCDCalibratePanels2::exec(), Mantid::Crystal::SetGoniometer::exec(), Mantid::Crystal::SetUB::exec(), Mantid::Crystal::SortHKL::exec(), Mantid::CurveFitting::Algorithms::ConvertToYSpace::exec(), Mantid::CurveFitting::Algorithms::EstimatePeakErrors::exec(), Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::LeBailFit::exec(), Mantid::CurveFitting::Algorithms::PlotPeakByLogValue::exec(), Mantid::CurveFitting::Algorithms::SplineInterpolation::exec(), Mantid::DataHandling::AlignAndFocusPowderSlim::AlignAndFocusPowderSlim::exec(), Mantid::DataHandling::CheckMantidVersion::exec(), Mantid::DataHandling::FindDetectorsPar::exec(), Mantid::DataHandling::GroupDetectors::exec(), Mantid::DataHandling::LoadEMUHdf::exec(), Mantid::DataHandling::LoadErrorEventsNexus::exec(), Mantid::DataHandling::LoadEventAsWorkspace2D::exec(), Mantid::DataHandling::LoadFullprofResolution::exec(), Mantid::DataHandling::LoadGSASInstrumentFile::exec(), Mantid::DataHandling::LoadInstrument::exec(), Mantid::DataHandling::LoadISISNexus2::exec(), Mantid::DataHandling::LoadMappingTable::exec(), Mantid::DataHandling::LoadNexusMonitors2::exec(), Mantid::DataHandling::LoadNXSPE::exec(), Mantid::DataHandling::LoadTOFRawNexus::exec(), Mantid::DataHandling::MaskDetectors::exec(), Mantid::DataHandling::MoveInstrumentComponent::exec(), Mantid::DataHandling::RotateSampleShape::exec(), Mantid::DataHandling::SaveFocusedXYE::exec(), Mantid::DataHandling::SaveIsawDetCal::exec(), Mantid::DataHandling::SaveParameterFile::exec(), Mantid::DataHandling::SNSAppendGeometryToNexus::exec(), Mantid::MDAlgorithms::AccumulateMD::exec(), Mantid::MDAlgorithms::BinaryOperationMD::exec(), Mantid::MDAlgorithms::BinMD::exec(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::exec(), Mantid::MDAlgorithms::ConvertSpiceDataToRealSpace::exec(), Mantid::MDAlgorithms::ConvertToDiffractionMDWorkspace::exec(), Mantid::MDAlgorithms::ConvertToMD::exec(), Mantid::MDAlgorithms::CutMD::exec(), Mantid::MDAlgorithms::ImportMDEventWorkspace::exec(), Mantid::MDAlgorithms::LoadDNSSCD::exec(), Mantid::MDAlgorithms::LoadSQW::exec(), Mantid::MDAlgorithms::MDNorm::exec(), Mantid::MDAlgorithms::MDNormDirectSC::exec(), Mantid::MDAlgorithms::MDNormSCD::exec(), Mantid::MDAlgorithms::RecalculateTrajectoriesExtents::exec(), Mantid::MDAlgorithms::SaveZODS::exec(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::exec(), Mantid::WorkflowAlgorithms::EQSANSPatchSensitivity::exec(), Mantid::WorkflowAlgorithms::EQSANSQ2D::exec(), Mantid::WorkflowAlgorithms::HFIRLoad::exec(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::exec(), Mantid::Algorithms::ClearCache::exec(), Mantid::CurveFitting::Algorithms::CalculateChiSquared::execConcrete(), Mantid::Algorithms::DiffractionFocussing2::execEvent(), Mantid::Crystal::AnvredCorrection::execEvent(), Mantid::WorkflowAlgorithms::SANSSolidAngleCorrection::execEvent(), Mantid::Algorithms::RemoveLowResTOF::execEvent(), Mantid::Algorithms::EQSANSTofStructure::execEvent(), Mantid::DataHandling::LoadNexusLogs::execLoader(), Mantid::CurveFitting::Algorithms::LeBailFit::execPatternCalculation(), Mantid::DataHandling::MaskDetectors::execPeaks(), MantidQt::API::BatchAlgorithmRunner::executeAlgo(), MantidQt::API::BatchAlgorithmRunner::executeBatchAsyncImpl(), Mantid::API::Algorithm::executeInternal(), Mantid::DataHandling::LoadNexusProcessed2::extractMappingInfoNew(), Mantid::MDAlgorithms::SlicingAlgorithm::extractMDFrameForNonAxisAligned(), Mantid::DataHandling::MaskDetectors::fillIndexListFromSpectra(), Mantid::Kernel::FacilityInfo::fillInstruments(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::finalize(), Mantid::CurveFitting::Algorithms::Fit::finalizeMinimizer(), Mantid::Algorithms::FindCenterOfMassPosition2::findCenterOfMass(), Mantid::MDAlgorithms::FindPeaksMD::findPeaks(), Mantid::Algorithms::FindPeaks::findPeaksGivenStartingPoints(), Mantid::MDAlgorithms::FindPeaksMD::findPeaksHisto(), Mantid::API::FileFinderImpl::findRun(), Mantid::DataHandling::LoadISISNexus2::findSpectraDetRangeInFile(), Mantid::MDAlgorithms::ConvertCWPDMDToSpectra::findXBoundary(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterSimultaneousFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::finishAfterTFSimultaneousFit(), Mantid::DataHandling::firstLastPulseTimes(), Mantid::CurveFitting::Algorithms::RefinePowderInstrumentParameters3::fitFunction(), Mantid::Algorithms::FitPeaks::fitFunctionSD(), Mantid::Algorithms::FindPeaks::fitPeakInWindow(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitPeaksRobust(), Mantid::Algorithms::FindPeaks::fitSinglePeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::fitSinglePeakRobust(), Mantid::Algorithms::FitPeaks::fitSpectrumPeaks(), Mantid::CurveFitting::Functions::IkedaCarpenterPV::functionLocal(), Mantid::DataHandling::LoadDetectorsGroupingFile::generateNoInstrumentGroupWorkspace(), Mantid::DataHandling::SaveGSS::generateOutFileNames(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeak(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::genPeaksFromTable(), Mantid::Geometry::Torus::getBoundingBox(), Mantid::Geometry::Goniometer::getConventionFromMotorAxes(), Mantid::API::SpectrumInfo::getDetectorValues(), Mantid::Algorithms::ConvertSpectrumAxis::getEfixed(), Mantid::Algorithms::ConvertSpectrumAxis2::getEfixed(), Mantid::Algorithms::Stitch1D::getEndOverlap(), MantidQt::MantidWidgets::FunctionTreeView::getFunction(), Mantid::MDAlgorithms::SlicingAlgorithm::getGeneralImplicitFunction(), Mantid::DataHandling::GroupDetectors2::getGroups(), Mantid::Algorithms::SANSCollimationLengthEstimator::getGuideValue(), Mantid::DataHandling::LoadSpiceXML2DDet::getHB3AWavelength(), Mantid::Algorithms::FindPeaks::getIndex(), Mantid::Algorithms::PDDetermineCharacterizations::getInformationFromTable(), Mantid::MDAlgorithms::ConvertCWSDExpToMomentum::getInputs(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentDoubleParameter(), Mantid::DataHandling::LoadHFIRSANS::getInstrumentStringParameter(), Mantid::Geometry::PointGroup::getLauePointGroupSymbol(), Mantid::Algorithms::PDDetermineCharacterizations::getLogValue(), Mantid::MDAlgorithms::IntegratePeaksCWSD::getMeasureTime(), Mantid::Kernel::ConfigServiceImpl::getOSArchitecture(), Mantid::API::ParamFunction::getParameter(), Mantid::Crystal::FindSXPeaksHelper::FindMaxReduceStrategy::getPeakGroups(), Mantid::Crystal::SortHKL::getPointgroup(), Mantid::API::Run::getProtonCharge(), Mantid::Algorithms::Qxy::getQminFromWs(), Mantid::Geometry::Instrument::getSample(), Mantid::Algorithms::SumOverlappingTubes::getScatteringAngleBinning(), Mantid::Algorithms::MedianDetectorTest::getSolidAngles(), Mantid::Geometry::Instrument::getSource(), Mantid::DataHandling::LoadHFIRSANS::getSourceToSampleDistance(), Mantid::Algorithms::Stitch1D::getStartOverlap(), Mantid::Algorithms::Q1DWeighted::getViewportParams(), Mantid::DataHandling::LoadNexusProcessed::getWordsInString(), Mantid::DataHandling::LoadNexusProcessed::getWordsInString(), Mantid::CurveFitting::Algorithms::getWorkspace(), Mantid::DataHandling::LoadILLReflectometry::getXValues(), Mantid::Algorithms::UnwrapMonitor::handleFrameOverlapped(), Mantid::DataHandling::MaskDetectors::handleMaskByMatrixWorkspace(), Mantid::Algorithms::FitOneSinglePeak::highBkgdFit(), Mantid::Algorithms::GeneratePeaks::importPeaksFromTable(), Mantid::Kernel::Units::dSpacing::init(), Mantid::CurveFitting::MultiDomainCreator::initFunction(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::initSimulatedAnnealing(), Mantid::MDAlgorithms::CentroidPeaksMD2::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD::integrate(), Mantid::MDAlgorithms::IntegratePeaksMD2::integrate(), Mantid::API::Run::integrateProtonCharge(), Mantid::Algorithms::CreateMonteCarloWorkspace::integrateYData(), Mantid::API::PanelsSurfaceCalculator::isBankFlat(), MantidQt::MantidWidgets::FitDomain::isParameterValueWithinConstraints(), Mantid::Algorithms::WorkspaceBoundingBox::isValidIndex(), MantidQt::MantidWidgets::FitDomain::isValidParameterConstraint(), Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate(), Mantid::CurveFitting::FuncMinimisers::DampedGaussNewtonMinimizer::iterate(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::jumpUpdate(), Mantid::Algorithms::CalculateFlatBackground::LinearFit(), Mantid::DataHandling::LoadTOFRawNexus::loadBank(), Mantid::DataHandling::LoadSwans::loadData(), Mantid::DataHandling::LoadNexusProcessed::loadEntry(), Mantid::DataHandling::LoadCanSAS1D2::loadEntry(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventId(), Mantid::DataHandling::LoadBBY::loadEvents(), Mantid::DataHandling::LoadBankFromDiskTask::loadEventWeights(), Mantid::DataHandling::Mantid3MFFileIO::LoadFile(), Mantid::WorkflowAlgorithms::DgsReduction::loadGroupingFile(), Mantid::DataHandling::LoadGSS::loadGSASFile(), Mantid::DataHandling::LoadFITS::loadHeader(), Mantid::DataHandling::LoadBBY::loadInstrumentParameters(), Mantid::DataHandling::LoadBBY2::loadInstrumentParameters(), Mantid::DataHandling::LoadISISNexus2::loadLogs(), Mantid::DataHandling::Mantid3MFFileIO::loadMeshObject(), Mantid::API::WorkspaceHistory::loadNestedHistory(), Mantid::API::WorkspaceHistory::loadNexus(), Mantid::DataHandling::LoadNexusProcessed2::loadNexusGeometry(), Mantid::DataHandling::LoadNexusProcessed::loadNonEventEntry(), Mantid::DataHandling::LoadNexusLogs::loadNXLog(), Mantid::DataHandling::LoadEventPreNexus2::loadPixelMap(), Mantid::DataHandling::LoadBankFromDiskTask::loadPulseTimes(), Mantid::DataHandling::LoadMLZ::loadRunDetails(), Mantid::DataHandling::LoadNexusLogs::loadSELog(), Mantid::DataHandling::LoadNGEM::loadSingleFile(), Mantid::DataHandling::LoadLog::loadThreeColumnLogFile(), Mantid::DataHandling::LoadBankFromDiskTask::loadTof(), Mantid::Algorithms::He3TubeEfficiency::logErrors(), Mantid::Algorithms::DetectorEfficiencyCor::logErrors(), Mantid::Algorithms::FitPeaks::logNoOffset(), Mantid::Kernel::ConfigServiceImpl::makeAbsolute(), Mantid::DataHandling::LoadDiffCal::makeCalWorkspace(), Mantid::Algorithms::GenerateEventsFilter::makeFilterBySingleValue(), Mantid::Algorithms::DetectorDiagnostic::makeMap(), Mantid::Algorithms::IntegrateByComponent::makeMap(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValues(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesParallel(), Mantid::Algorithms::GenerateEventsFilter::makeMultipleFiltersByValuesPartialLog(), Mantid::Crystal::ConvertPeaksWorkspace::makePeaksWorkspace(), Mantid::Geometry::Instrument::markAsSamplePos(), Mantid::Geometry::Instrument::markAsSource(), Mantid::Algorithms::CalculateEfficiency::maskComponent(), Mantid::DataHandling::LoadMLZ::maskDetectors(), Mantid::WorkflowAlgorithms::SANSBeamFinder::maskEdges(), Mantid::Algorithms::CalculateEfficiency::maskEdges(), Mantid::Algorithms::NormaliseToMonitor::normaliseBinByBin(), Mantid::Algorithms::RadiusSum::numBinsIsReasonable(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::observePeakRange(), Mantid::Geometry::operator>>(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputConvergedChains(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputCostFunctionTable(), Mantid::CurveFitting::FuncMinimisers::FABADAMinimizer::outputPDF(), Mantid::Algorithms::FindPeaksConvolve::outputResults(), Mantid::API::WorkspaceHistory::parseAlgorithmHistory(), Mantid::DataHandling::LoadGSASInstrumentFile::parseBank(), Mantid::DataHandling::LoadPDFgetNFile::parseDataLine(), Mantid::DataHandling::LoadFullprofResolution::parseDoubleValue(), Mantid::DataHandling::LoadGroupMapFile::parseFile(), Mantid::CurveFitting::Algorithms::FitPowderDiffPeaks::parseFitParameterWorkspace(), MantidQt::API::TSVSerialiser::parseLines(), Mantid::DataHandling::LoadFullprofResolution::parseResolutionStrings(), Mantid::Geometry::ShapeFactory::parseSliceOfCylinderRing(), Mantid::DataHandling::LoadSpiceAscii::parseSPICEAscii(), Mantid::Algorithms::Divide::performBinaryOperation(), Mantid::Algorithms::ParallaxCorrection::performCorrection(), Mantid::DataHandling::LoadDNSEvent::populate_EventWorkspace(), MantidQt::MantidWidgets::FitPropertyBrowser::populateFunctionNames(), Mantid::Kernel::MemoryStats::process_mem_system(), Mantid::Algorithms::FilterEvents::processAlgorithmProperties(), Mantid::Algorithms::FindPeaks::processAlgorithmProperties(), Mantid::DataHandling::GroupDetectors2::processFile(), Mantid::Algorithms::GenerateEventsFilter::processInOutWorkspaces(), Mantid::CurveFitting::Algorithms::LeBailFit::processInputBackground(), Mantid::Algorithms::FitPeaks::processInputFunctions(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processInputs(), Mantid::Algorithms::MaskBinsFromTable::processMaskBinWorkspace(), Mantid::DataHandling::LoadMask::processMaskOnDetectors(), Mantid::MDAlgorithms::IntegratePeaksCWSD::processMaskWorkspace(), Mantid::Algorithms::GenerateEventsFilter::processMultipleValueFilters(), Mantid::Algorithms::FitPeaks::processOutputs(), Mantid::Algorithms::FitPeak::processProperties(), Mantid::Kernel::InternetHelper::processRelocation(), Mantid::Algorithms::GeneratePeaks::processTableColumnNames(), Mantid::DataHandling::GroupDetectors2::processXMLFile(), Mantid::DataHandling::LoadEventPreNexus2::procEventsLinear(), Mantid::Geometry::Goniometer::pushAxis(), Mantid::DataHandling::LoadCalFile::readCalFile(), Mantid::DataHandling::LoadMcStas::readEventData(), Mantid::MDAlgorithms::FindPeaksMD::readExperimentInfo(), Mantid::DataHandling::LoadDetectorInfo::readLibisisNxs(), Mantid::API::ExperimentInfo::readParameterMap(), Mantid::MDAlgorithms::LoadSQW2::readPixelDataIntoWorkspace(), Mantid::DataHandling::LoadEventPreNexus2::readPulseidFile(), MantidQt::MantidWidgets::MuonPeriodInfo::readSampleLog(), Mantid::DataHandling::LoadAscii2::readTable(), Mantid::WorkflowAlgorithms::AlignAndFocusPowder::rebin(), Mantid::DataHandling::LoadHelper::recurseAndAddNexusFieldsToWsRun(), Mantid::DataHandling::LoadILLReflectometry::reflectometryPeak(), Mantid::DataHandling::LoadNexusProcessed::reinitSpecialWorkspace2D(), Mantid::Algorithms::StripPeaks::removePeaks(), Mantid::Kernel::DataService< T >::rename(), Mantid::API::WorkspaceGroup::reorderMembersWithIndices(), Mantid::Algorithms::MedianDetectorTest::retrieveProperties(), Mantid::Algorithms::DetectorEfficiencyVariation::retrieveProperties(), Mantid::DataHandling::LoadILLIndirect2::rotateTubes(), Mantid::DataHandling::LoadBankFromDiskTask::run(), Mantid::DataHandling::LoadMLZ::runLoadInstrument(), Mantid::DataHandling::LoadRawHelper::runLoadLog(), Mantid::DataHandling::LoadPreNexus::runLoadMonitors(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::LoadEventNexus::runLoadNexusLogs(), Mantid::DataHandling::SaveAscii2::sampleLogValueUnit(), Mantid::DataHandling::SaveCalFile::saveCalFile(), Mantid::DataObjects::MDBoxFlatTree::saveExperimentInfos(), Mantid::Crystal::SCDCalibratePanels2::saveIsawDetCal(), Mantid::Geometry::Instrument::saveNexus(), Mantid::API::LogManager::saveNexus(), Mantid::Algorithms::Stitch1D::scaleWorkspace(), MantidQt::API::ScriptRepositoryView::ScriptRepositoryView(), Mantid::CurveFitting::Functions::ProcessBackground::selectFromGivenXValues(), Mantid::DataHandling::ISISDataArchive::sendRequest(), Mantid::Kernel::InternetHelper::sendRequestAndProcess(), Mantid::Kernel::GitHubApiHelper::sendRequestAndProcess(), Mantid::Geometry::InstrumentDefinitionParser::setComponentLinks(), Mantid::API::IFunction::setConstraintPenaltyFactor(), Mantid::Geometry::Instrument::setDefaultView(), Mantid::Algorithms::GenerateEventsFilter::setFilterByTimeOnly(), Mantid::Algorithms::GetAllEi::setFilterLog(), Mantid::Algorithms::FitOneSinglePeak::setFitPeakCriteria(), Mantid::Algorithms::NormaliseToMonitor::setIntegrationProps(), Mantid::Geometry::InstrumentDefinitionParser::setLogfile(), Mantid::API::IFunction::setMatrixWorkspace(), Mantid::MDAlgorithms::LoadMD::setMDFrameOnWorkspaceFromLegacyFile(), Mantid::DataHandling::EventWorkspaceCollection::setNPeriods(), Mantid::Algorithms::CalculateCountRate::setOutLogParameters(), MantidQt::MantidWidgets::FitDomain::setParameterTie(), Mantid::CurveFitting::Constraints::BoundaryConstraint::setParamToSatisfyConstraint(), Mantid::CurveFitting::Constraints::BoundaryConstraint::setPenaltyFactor(), Mantid::DataHandling::LoadPDFgetNFile::setUnit(), Mantid::Algorithms::FilterEvents::setupCustomizedTOFCorrection(), Mantid::API::CompositeFunction::setUpForFit(), Mantid::CurveFitting::Functions::CubicSpline::setupInput(), Mantid::DataHandling::LoadSpiceAscii::setupRunStartTime(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogFromSpiceTable(), Mantid::DataHandling::LoadSpiceXML2DDet::setupSampleLogs(), Mantid::MDAlgorithms::CreateMD::single_run(), ISISRAW2::skipData(), Mantid::MDAlgorithms::SliceMD::slice(), Mantid::Algorithms::WienerSmooth::smoothSingleSpectrum(), Mantid::Algorithms::SparseWorkspace::SparseWorkspace(), Mantid::DataHandling::LoadNexusMonitors2::splitMutiPeriodHistrogramData(), Mantid::Kernel::TimeSeriesProperty< TYPE >::timeAverageValue(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::DataObjects::TimeSplitter::TimeSplitter(), Mantid::Kernel::TopicInfo::TopicInfo(), Mantid::Algorithms::NormaliseByDetector::tryParseFunctionParameter(), Mantid::API::AlgorithmFactoryImpl::unsubscribe(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateGlobalParameterTie(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateLocalParameterTie(), MantidQt::MantidWidgets::FitScriptGeneratorModel::updateParameterTie(), Mantid::Kernel::EqualBinsChecker::validate(), Mantid::MDAlgorithms::MDNorm::validateBinningForTemporaryDataWorkspace(), Mantid::Algorithms::GetAllEi::validateInputs(), Mantid::Crystal::IndexPeaks::validateInputs(), Mantid::DataHandling::LoadEventNexus::validateInputs(), Mantid::DataHandling::LoadISISNexus2::validateMultiPeriodLogs(), Mantid::Kernel::DateAndTimeHelpers::verifyAndSanitizeISO8601(), Mantid::DataHandling::LoadNGEM::verifyFileSize(), Mantid::MDAlgorithms::LoadSQW2::warnIfMemoryInsufficient(), Mantid::Crystal::SetSpecialCoordinates::writeCoordinatesToMDEventWorkspace(), Mantid::Crystal::SetSpecialCoordinates::writeCoordinatesToMDHistoWorkspace(), and Mantid::DataHandling::SaveAscii2::writeTableWorkspace().
Member Data Documentation
m_enabled
bool Mantid::Kernel::Logger::m_enabled private
The state of this logger, disabled loggers send no messages.
Definition at line 167 of file Logger.h.
Referenced by dump(), getEnabled(), getLogStream(), log(), and setEnabled().
m_levelOffset
int Mantid::Kernel::Logger::m_levelOffset private
The offset of the logger.
Definition at line 165 of file Logger.h.
Referenced by applyLevelOffset(), getLevelOffset(), and setLevelOffset().
m_log
Poco::Logger* Mantid::Kernel::Logger::m_log private
Internal handle to third party logging objects.
Definition at line 160 of file Logger.h.
Referenced by dump(), getLevel(), is(), log(), setLevel(), setLevel(), and setName().
m_logStream
std::unique_ptr<ThreadSafeLogStream> Mantid::Kernel::Logger::m_logStream private
Allows stream operators for a logger.
Definition at line 162 of file Logger.h.
Referenced by accumulate(), flush(), flush(), getLogStream(), purge(), and setName().
PriorityNames
const std::array< std::string, 9 > Mantid::Kernel::Logger::PriorityNames static
Initial value:
{"none",   "fatal",       "critical", "error", "warning",
                                                       "notice", "information", "debug",    "trace"}
Definition at line 56 of file Logger.h.
Referenced by getLevelName(), and Mantid::Kernel::ConfigServiceImpl::setLogLevel().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/Logger.h
Framework/Kernel/src/Logger.cpp