Mantid: Framework/PythonInterface/mantid/geometry/src/Exports/CSGObject.cpp File Reference
CSGObject.cpp File Reference
#include "MantidGeometry/Objects/CSGObject.h"
#include "MantidGeometry/Rendering/GeometryTriangulator.h"
#include "MantidPythonInterface/core/Converters/NDArrayTypeIndex.h"
#include "MantidPythonInterface/core/Converters/WrapWithNDArray.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <boost/python/self.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
#include <numpy/arrayobject.h>
Macros
#define NO_IMPORT_ARRAY
#define PY_ARRAY_UNIQUE_SYMBOL GEOMETRY_ARRAY_API
Functions
void export_Object ()
boost::python::object wrapMeshWithNDArray (const CSGObject *self)
Macro Definition Documentation
NO_IMPORT_ARRAY
#define NO_IMPORT_ARRAY
Definition at line 22 of file CSGObject.cpp.
PY_ARRAY_UNIQUE_SYMBOL
#define PY_ARRAY_UNIQUE_SYMBOL GEOMETRY_ARRAY_API
Definition at line 21 of file CSGObject.cpp.
Function Documentation
export_Object()
void export_Object ()
Definition at line 55 of file CSGObject.cpp.
References Mantid::Geometry::CSGObject::getBoundingBox(), Mantid::Geometry::CSGObject::getShapeXML(), Mantid::Geometry::CSGObject::volume(), and wrapMeshWithNDArray().
wrapMeshWithNDArray()
boost::python::object wrapMeshWithNDArray (const CSGObject * self)
Definition at line 33 of file CSGObject.cpp.
References Mantid::PythonInterface::Converters::Impl::wrapWithNDArray().
Referenced by export_Object().