Mantid: Mantid::Algorithms::ApodizationFunctions Namespace Reference
Mantid::Algorithms::ApodizationFunctions Namespace Reference
Functions
double gaussian (const double time, const double decayConstant)
Returns the evaluation of the Gaussian apodization function at a time (t) and decay constant tau: f =exp(-time^2/(2*tau^2))
double lorentz (const double time, const double decayConstant)
Returns the evaluation of the Lorentz (an exponential decay) apodization function at a time (t) and decay constant tau: f = exp(-t/tau)
double none (const double, const double)
Returns no apodization function.
Function Documentation
gaussian()
double Mantid::Algorithms::ApodizationFunctions::gaussian (const double time, const double decayConstant)
Returns the evaluation of the Gaussian apodization function at a time (t) and decay constant tau: f =exp(-time^2/(2*tau^2))
Parameters
time :: [input] current time (t)
decayConstant :: [input] the decay constant (tau)
Returns
:: Function evaluation
Definition at line 35 of file ApodizationFunctions.cpp.
Referenced by Mantid::Algorithms::PaddingAndApodization::getApodizationFunction().
lorentz()
double Mantid::Algorithms::ApodizationFunctions::lorentz (const double time, const double decayConstant)
Returns the evaluation of the Lorentz (an exponential decay) apodization function at a time (t) and decay constant tau: f = exp(-t/tau)
Parameters
time :: [input] current time (t)
decayConstant :: [input] the decay constant (tau)
Returns
:: Function evaluation
Definition at line 25 of file ApodizationFunctions.cpp.
Referenced by Mantid::Algorithms::PaddingAndApodization::getApodizationFunction().
none()
double Mantid::Algorithms::ApodizationFunctions::none (const double , const double)
Returns no apodization function.
i.e. the data is unchanged
Parameters
: [input] current time (t)
: [input] the decay constant (tau)
Returns
:: Function evaluation
Definition at line 46 of file ApodizationFunctions.cpp.
Referenced by Mantid::Algorithms::PaddingAndApodization::getApodizationFunction().