Mantid: Mantid::DataObjects::PeakShapeEllipsoid Class Reference
Mantid::DataObjects::PeakShapeEllipsoid Class Reference
PeakShapeEllipsoid : PeakShape representing a 3D ellipsoid.
#include <PeakShapeEllipsoid.h>
Public Member Functions
const std::vector< double > & abcRadii () const
Get radii.
const std::vector< double > & abcRadiiBackgroundInner () const
Get background inner radii.
const std::vector< double > & abcRadiiBackgroundOuter () const
Get background outer radii.
PeakShapeEllipsoid * clone () const override
Clone ellipsoid.
const std::vector< Mantid::Kernel::V3D > & directions () const
Get ellipsoid directions.
std::vector< Kernel::V3D > getDirectionInSpecificFrame (Kernel::Matrix< double > &invertedGoniometerMatrix) const
Get ellipsoid directions in a specified frame.
bool operator== (const PeakShapeEllipsoid &other) const
Equals operator.
PeakShapeEllipsoid (const std::vector< Mantid::Kernel::V3D > &directions, const std::vector< double > &abcRadii, const std::vector< double > &abcRadiiBackgroundInner, const std::vector< double > &abcRadiiBackgroundOuter, Kernel::SpecialCoordinateSystem frame, std::string algorithmName=std::string(), int algorithmVersion=-1, const Mantid::Kernel::V3D &translation={0.0, 0.0, 0.0})
Constructor.
boost::optional< double > radius (RadiusType type=RadiusType::Radius) const override
PeakBase interface.
std::string shapeName () const override
Get the peak shape.
std::string toJSON () const override
PeakShape interface.
const Kernel::V3D & translation () const
Get translation of center.
Public Member Functions inherited from Mantid::DataObjects::PeakShapeBase
std::string algorithmName () const override
Get the name of the algorithm used to make this shape.
int algorithmVersion () const override
Get the version of the algorithm used to make this shape.
Kernel::SpecialCoordinateSystem frame () const override
Get the coordinate frame.
PeakShapeBase (Kernel::SpecialCoordinateSystem frame, std::string algorithmName=std::string(), int algorithmVersion=-1)
Constructor.
Public Member Functions inherited from Mantid::Geometry::PeakShape
virtual std::string algorithmName () const =0
Algorithm.
virtual int algorithmVersion () const =0
Algorithm Version.
virtual PeakShape * clone () const =0
Deep copy this.
virtual Mantid::Kernel::SpecialCoordinateSystem frame () const =0
Coordinte frame used upon creation.
virtual boost::optional< double > radius (RadiusType type) const =0
Radius.
virtual std::string shapeName () const =0
Shape name.
virtual std::string toJSON () const =0
Serialize.
virtual ~PeakShape ()=default
Destructor.
Static Public Member Functions
static const std::string ellipsoidShapeName ()
Private Attributes
std::vector< double > m_abc_radii
radii
std::vector< double > m_abc_radiiBackgroundInner
inner radii
std::vector< double > m_abc_radiiBackgroundOuter
outer radii
std::vector< Mantid::Kernel::V3D > m_directions
principle axis
Mantid::Kernel::V3D m_translation
translation of center
Additional Inherited Members
Public Types inherited from Mantid::Geometry::PeakShape
enum RadiusType { Radius = 0 , OuterRadius = 1 , InnerRadius = 2 }
For selecting different radius types.
Protected Member Functions inherited from Mantid::DataObjects::PeakShapeBase
void buildCommon (Json::Value &root) const
Build common parts of outgoing JSON serialization.
PeakShapeBase & operator= (const PeakShapeBase &)=default
Assignment operator.
bool operator== (const PeakShapeBase &other) const
Equals operator.
PeakShapeBase (const PeakShapeBase &)=default
Copy constructor.
Protected Attributes inherited from Mantid::DataObjects::PeakShapeBase
std::string m_algorithmName
Generating algorithm name.
int m_algorithmVersion
Generating algorithm version.
Mantid::Kernel::SpecialCoordinateSystem m_frame
Special coordinate system.
Detailed Description
PeakShapeEllipsoid : PeakShape representing a 3D ellipsoid.
Definition at line 18 of file PeakShapeEllipsoid.h.
Constructor & Destructor Documentation
PeakShapeEllipsoid()
Mantid::DataObjects::PeakShapeEllipsoid::PeakShapeEllipsoid (const std::vector< Mantid::Kernel::V3D > & directions, const std::vector< double > & abcRadii, const std::vector< double > & abcRadiiBackgroundInner, const std::vector< double > & abcRadiiBackgroundOuter, Kernel::SpecialCoordinateSystem frame, std::string algorithmName = std::string(), int algorithmVersion = -1, const Mantid::Kernel::V3D & translation = {0.0, 0.0, 0.0})
Constructor.
Definition at line 16 of file PeakShapeEllipsoid.cpp.
References abcRadii(), abcRadiiBackgroundInner(), abcRadiiBackgroundOuter(), and directions().
Member Function Documentation
abcRadii()
const std::vector< double > & Mantid::DataObjects::PeakShapeEllipsoid::abcRadii () const
Get radii.
Definition at line 46 of file PeakShapeEllipsoid.cpp.
References m_abc_radii.
Referenced by operator==(), and PeakShapeEllipsoid().
abcRadiiBackgroundInner()
const std::vector< double > & Mantid::DataObjects::PeakShapeEllipsoid::abcRadiiBackgroundInner () const
Get background inner radii.
Definition at line 48 of file PeakShapeEllipsoid.cpp.
References m_abc_radiiBackgroundInner.
Referenced by operator==(), and PeakShapeEllipsoid().
abcRadiiBackgroundOuter()
const std::vector< double > & Mantid::DataObjects::PeakShapeEllipsoid::abcRadiiBackgroundOuter () const
Get background outer radii.
Definition at line 50 of file PeakShapeEllipsoid.cpp.
References m_abc_radiiBackgroundOuter.
Referenced by operator==(), and PeakShapeEllipsoid().
clone()
PeakShapeEllipsoid * Mantid::DataObjects::PeakShapeEllipsoid::clone () const override virtual
Clone ellipsoid.
Implements Mantid::Geometry::PeakShape.
Definition at line 98 of file PeakShapeEllipsoid.cpp.
directions()
const std::vector< Kernel::V3D > & Mantid::DataObjects::PeakShapeEllipsoid::directions () const
Get ellipsoid directions.
Definition at line 52 of file PeakShapeEllipsoid.cpp.
References m_directions.
Referenced by operator==(), and PeakShapeEllipsoid().
ellipsoidShapeName()
const std::string Mantid::DataObjects::PeakShapeEllipsoid::ellipsoidShapeName () static
Definition at line 118 of file PeakShapeEllipsoid.cpp.
Referenced by Mantid::DataObjects::PeakShapeEllipsoidFactory::create(), and shapeName().
getDirectionInSpecificFrame()
std::vector< Kernel::V3D > Mantid::DataObjects::PeakShapeEllipsoid::getDirectionInSpecificFrame (Kernel::Matrix< double > & invertedGoniometerMatrix) const
Get ellipsoid directions in a specified frame.
Definition at line 57 of file PeakShapeEllipsoid.cpp.
References m_directions, Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
operator==()
bool Mantid::DataObjects::PeakShapeEllipsoid::operator== (const PeakShapeEllipsoid & other) const
Equals operator.
Definition at line 39 of file PeakShapeEllipsoid.cpp.
References abcRadii(), abcRadiiBackgroundInner(), abcRadiiBackgroundOuter(), directions(), Mantid::DataObjects::PeakShapeBase::operator==(), and translation().
radius()
boost::optional< double > Mantid::DataObjects::PeakShapeEllipsoid::radius (RadiusType type = RadiusType::Radius) const override virtual
PeakBase interface.
Implements Mantid::Geometry::PeakShape.
Definition at line 102 of file PeakShapeEllipsoid.cpp.
References Mantid::Geometry::PeakShape::InnerRadius, m_abc_radii, m_abc_radiiBackgroundInner, m_abc_radiiBackgroundOuter, Mantid::Geometry::PeakShape::OuterRadius, and Mantid::Geometry::PeakShape::Radius.
shapeName()
std::string Mantid::DataObjects::PeakShapeEllipsoid::shapeName () const override virtual
Get the peak shape.
Implements Mantid::Geometry::PeakShape.
Definition at line 100 of file PeakShapeEllipsoid.cpp.
References ellipsoidShapeName().
toJSON()
std::string Mantid::DataObjects::PeakShapeEllipsoid::toJSON () const override virtual
PeakShape interface.
Implements Mantid::Geometry::PeakShape.
Definition at line 72 of file PeakShapeEllipsoid.cpp.
References Mantid::DataObjects::PeakShapeBase::buildCommon(), m_abc_radii, m_abc_radiiBackgroundInner, m_abc_radiiBackgroundOuter, m_directions, and m_translation.
translation()
const Kernel::V3D & Mantid::DataObjects::PeakShapeEllipsoid::translation () const
Get translation of center.
Definition at line 54 of file PeakShapeEllipsoid.cpp.
References m_translation.
Referenced by operator==().
Member Data Documentation
m_abc_radii
std::vector<double> Mantid::DataObjects::PeakShapeEllipsoid::m_abc_radii private
radii
Definition at line 56 of file PeakShapeEllipsoid.h.
Referenced by abcRadii(), radius(), and toJSON().
m_abc_radiiBackgroundInner
std::vector<double> Mantid::DataObjects::PeakShapeEllipsoid::m_abc_radiiBackgroundInner private
inner radii
Definition at line 58 of file PeakShapeEllipsoid.h.
Referenced by abcRadiiBackgroundInner(), radius(), and toJSON().
m_abc_radiiBackgroundOuter
std::vector<double> Mantid::DataObjects::PeakShapeEllipsoid::m_abc_radiiBackgroundOuter private
outer radii
Definition at line 60 of file PeakShapeEllipsoid.h.
Referenced by abcRadiiBackgroundOuter(), radius(), and toJSON().
m_directions
std::vector<Mantid::Kernel::V3D> Mantid::DataObjects::PeakShapeEllipsoid::m_directions private
principle axis
Definition at line 54 of file PeakShapeEllipsoid.h.
Referenced by directions(), getDirectionInSpecificFrame(), and toJSON().
m_translation
Mantid::Kernel::V3D Mantid::DataObjects::PeakShapeEllipsoid::m_translation private
translation of center
Definition at line 62 of file PeakShapeEllipsoid.h.
Referenced by toJSON(), and translation().
The documentation for this class was generated from the following files:
Framework/DataObjects/inc/MantidDataObjects/PeakShapeEllipsoid.h
Framework/DataObjects/src/PeakShapeEllipsoid.cpp