Mantid: Mantid::Kernel::SplittingInterval Class Reference
Mantid::Kernel::SplittingInterval Class Reference
Class holding a start/end time and a destination for splitting event lists and logs.
#include <TimeSplitter.h>
Public Member Functions
double duration () const
Returns the duration in seconds.
int index () const
Return the index (destination of this split time block)
bool operator< (const SplittingInterval &b) const
Compare two splitter by the begin time.
bool operator> (const SplittingInterval &b) const
Compare two splitter by the begin time.
SplittingInterval operator| (const SplittingInterval &b) const
Or operator. Return the largest time interval.
bool overlaps (const SplittingInterval &b) const
Return true if the b SplittingInterval overlaps with this one.
SplittingInterval ()
Default constructor.
SplittingInterval (const Types::Core::DateAndTime &start, const Types::Core::DateAndTime &stop, const int index=0)
Constructor using DateAndTime.
Types::Core::DateAndTime start () const
Return the start time.
Types::Core::DateAndTime stop () const
Return the stop time.
Private Attributes
int m_index
Index of the destination.
Types::Core::DateAndTime m_start
begin
Types::Core::DateAndTime m_stop
end
Detailed Description
Class holding a start/end time and a destination for splitting event lists and logs.
The start/stop times are saved internally as DateAndTime, for fastest event list splitting.
Author: Janik Zikovsky, SNS
Definition at line 23 of file TimeSplitter.h.
Constructor & Destructor Documentation
SplittingInterval() [1/2]
Mantid::Kernel::SplittingInterval::SplittingInterval ()
Default constructor.
Definition at line 15 of file TimeSplitter.cpp.
SplittingInterval() [2/2]
Mantid::Kernel::SplittingInterval::SplittingInterval (const Types::Core::DateAndTime & start, const Types::Core::DateAndTime & stop, const int index = 0)
Constructor using DateAndTime.
Definition at line 18 of file TimeSplitter.cpp.
Member Function Documentation
duration()
double Mantid::Kernel::SplittingInterval::duration () const
Returns the duration in seconds.
Definition at line 29 of file TimeSplitter.cpp.
References m_start, and m_stop.
index()
int Mantid::Kernel::SplittingInterval::index () const
Return the index (destination of this split time block)
Definition at line 32 of file TimeSplitter.cpp.
References m_index.
Referenced by Mantid::DataObjects::SplittersWorkspace::addSplitter(), and Mantid::Algorithms::FilterEvents::convertSplittersWorkspaceToVectors().
operator<()
bool Mantid::Kernel::SplittingInterval::operator< (const SplittingInterval & b) const
Compare two splitter by the begin time.
Definition at line 71 of file TimeSplitter.cpp.
References m_start.
operator>()
bool Mantid::Kernel::SplittingInterval::operator> (const SplittingInterval & b) const
Compare two splitter by the begin time.
Definition at line 74 of file TimeSplitter.cpp.
References m_start.
operator|()
DOXYGEN_BUG SplittingInterval Mantid::Kernel::SplittingInterval::operator| (const SplittingInterval & b) const
Or operator. Return the largest time interval.
Definition at line 56 of file TimeSplitter.cpp.
References m_start, m_stop, and overlaps().
overlaps()
bool Mantid::Kernel::SplittingInterval::overlaps (const SplittingInterval & b) const
Return true if the b SplittingInterval overlaps with this one.
Definition at line 35 of file TimeSplitter.cpp.
References m_start, and m_stop.
Referenced by operator|().
start()
DateAndTime Mantid::Kernel::SplittingInterval::start () const
Return the start time.
Definition at line 23 of file TimeSplitter.cpp.
References m_start.
Referenced by Mantid::DataObjects::SplittersWorkspace::addSplitter(), Mantid::Kernel::compareSplittingInterval(), and Mantid::Algorithms::FilterEvents::convertSplittersWorkspaceToVectors().
stop()
DateAndTime Mantid::Kernel::SplittingInterval::stop () const
Return the stop time.
Definition at line 26 of file TimeSplitter.cpp.
References m_stop.
Referenced by Mantid::DataObjects::SplittersWorkspace::addSplitter(), and Mantid::Algorithms::FilterEvents::convertSplittersWorkspaceToVectors().
Member Data Documentation
m_index
int Mantid::Kernel::SplittingInterval::m_index private
Index of the destination.
Definition at line 52 of file TimeSplitter.h.
Referenced by index().
m_start
Types::Core::DateAndTime Mantid::Kernel::SplittingInterval::m_start private
begin
Definition at line 48 of file TimeSplitter.h.
Referenced by duration(), operator<(), operator>(), operator|(), overlaps(), and start().
m_stop
Types::Core::DateAndTime Mantid::Kernel::SplittingInterval::m_stop private
end
Definition at line 50 of file TimeSplitter.h.
Referenced by duration(), operator|(), overlaps(), and stop().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/TimeSplitter.h
Framework/Kernel/src/TimeSplitter.cpp