Mantid: Mantid::MDAlgorithms::LoadSQW Class Reference
Mantid::MDAlgorithms::LoadSQW Class Reference
#include <LoadSQW.h>
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
int confidence (Kernel::FileDescriptor &descriptor) const override
Returns a confidence value that this algorithm can load a file.
LoadSQW ()
Constructor.
const std::string name () const override
Algorithm's name for identification.
const std::string summary () const override
Summary of algorithms purpose.
int version () const override
Algorithm's version for identification.
~LoadSQW () override
Destructor.
Public Member Functions inherited from Mantid::API::IFileLoader< Kernel::FileDescriptor >
virtual bool loadMutipleAsOne ()
Returns a value indicating whether or not loader wants to load multiple files into a single workspace.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings > settings)
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Protected Member Functions
void addDimsToWs (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > *ws, std::vector< Mantid::Geometry::MDHistoDimensionBuilder > &DimVector)
add range of dimensions to the workspace;
virtual void addLattice (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > *ws)
Extract lattice information.
void buildMDDimsBase (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > &DimVector)
build an initial range of 4 dimensions
void parseMetadata (const std::string &fileName)
Parse metadata from file.
void readBoxSizes ()
read real box sizes for all Horace Boxes;
void readDNDDimensions (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > &DimVectorOut, bool arrangeByMDImage=true)
Read DND dimensions.
virtual void readEvents (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > *ws)
Read events onto the workspace.
void readSQWDimensions (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > &DimVectorOut)
Read SQW dimensions.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Protected Attributes
std::vector< uint64_t > m_boxSizes
LoadSQWHelper::dataPositions m_dataPositions
Instance of helper type, which describes the positions of the data within binary Horace file.
std::string m_fileName
the name of the file to work with
std::ifstream m_fileStream
File stream containing binary file data.
size_t m_mdImageSize
std::vector< size_t > m_nBins
number of bins in every non-integrated dimension
uint64_t m_nDataPoints
size_t m_nDims
std::string m_outputFile
OutputFilename param.
Mantid::API::Progress * m_prog
Progress bar.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Private Member Functions
void exec () override
Execute the algorithm.
void init () override
Provide wiki documentation.
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
Definition at line 83 of file LoadSQW.h.
Constructor & Destructor Documentation
LoadSQW()
Mantid::MDAlgorithms::LoadSQW::LoadSQW ()
Constructor.
Definition at line 54 of file LoadSQW.cpp.
~LoadSQW()
Mantid::MDAlgorithms::LoadSQW::~LoadSQW () override
Destructor.
Definition at line 78 of file LoadSQW.cpp.
References m_prog.
Member Function Documentation
addDimsToWs()
void Mantid::MDAlgorithms::LoadSQW::addDimsToWs (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > * ws, std::vector< Mantid::Geometry::MDHistoDimensionBuilder > & DimVector) protected
add range of dimensions to the workspace;
Definition at line 589 of file LoadSQW.cpp.
References Mantid::DataObjects::create().
Referenced by exec().
addLattice()
void Mantid::MDAlgorithms::LoadSQW::addLattice (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > * ws) protected virtual
Extract lattice information.
Extract the b-matrix from a SQW file.
Create experiment info with oriented lattice and add to workspace.
Parameters
ws : Workspace to modify.
Definition at line 361 of file LoadSQW.cpp.
References Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::geom_start, m_dataPositions, and m_fileStream.
Referenced by exec().
buildMDDimsBase()
void Mantid::MDAlgorithms::LoadSQW::buildMDDimsBase (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > & DimVector) protected
build an initial range of 4 dimensions
Definition at line 382 of file LoadSQW.cpp.
Referenced by readDNDDimensions(), and readSQWDimensions().
category()
const std::string Mantid::MDAlgorithms::LoadSQW::category () const inline override virtual
Algorithm's category for identification.
Reimplemented from Mantid::API::Algorithm.
Definition at line 99 of file LoadSQW.h.
confidence()
int Mantid::MDAlgorithms::LoadSQW::confidence (Kernel::FileDescriptor & descriptor) const override virtual
Returns a confidence value that this algorithm can load a file.
Return the confidence with this algorithm can load the file.
Parameters
descriptor A descriptor for the file
Returns
An integer specifying the confidence level. 0 indicates it will not be used
Implements Mantid::API::IFileLoader< Kernel::FileDescriptor >.
Definition at line 64 of file LoadSQW.cpp.
References Mantid::Kernel::FileDescriptor::extension(), and Mantid::Kernel::FileDescriptor::isAscii().
exec()
void Mantid::MDAlgorithms::LoadSQW::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 101 of file LoadSQW.cpp.
References addDimsToWs(), addLattice(), Mantid::Kernel::MemoryStats::availMem(), Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), m_fileName, m_nBins, m_nDataPoints, m_outputFile, m_prog, Mantid::Kernel::Logger::notice(), parseMetadata(), Mantid::API::Algorithm::progress(), readBoxSizes(), readDNDDimensions(), readEvents(), readSQWDimensions(), Mantid::Kernel::ProgressBase::resetNumSteps(), Mantid::Kernel::IPropertyManager::setProperty(), and Mantid::Kernel::Logger::warning().
init()
void Mantid::MDAlgorithms::LoadSQW::init () override private virtual
Provide wiki documentation.
Initialize the algorithm
Implements Mantid::API::Algorithm.
Definition at line 83 of file LoadSQW.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::API::FileProperty::Load, Mantid::API::FileProperty::OptionalSave, and Mantid::Kernel::Direction::Output.
name()
const std::string Mantid::MDAlgorithms::LoadSQW::name () const inline override virtual
Algorithm's name for identification.
Implements Mantid::API::Algorithm.
Definition at line 89 of file LoadSQW.h.
Referenced by readDNDDimensions().
parseMetadata()
void Mantid::MDAlgorithms::LoadSQW::parseMetadata (const std::string & fileName) protected
Parse metadata from file.
Function provides seam on to access axillary functions ported from MD_FileHoraceReader.
Definition at line 626 of file LoadSQW.cpp.
References Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::component_headers_starts, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::data_start, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::detectors_start, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::if_sqw_start, m_dataPositions, m_fileStream, m_nBins, m_nDataPoints, m_nDims, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::parse_component_header(), Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::parse_data_locations(), Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::parse_sqw_detpar(), and Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::parse_sqw_main_header().
Referenced by exec().
readBoxSizes()
void Mantid::MDAlgorithms::LoadSQW::readBoxSizes () protected
read real box sizes for all Horace Boxes;
Definition at line 657 of file LoadSQW.cpp.
References m_boxSizes, m_dataPositions, m_fileStream, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::mdImageSize, and Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::n_cell_pix_start.
Referenced by exec().
readDNDDimensions()
void Mantid::MDAlgorithms::LoadSQW::readDNDDimensions (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > & DimVectorOut, bool arrangeByMDImage = true) protected
Read DND dimensions.
Add a dimension after reading info from file.
Definition at line 401 of file LoadSQW.cpp.
References buildMDDimsBase(), Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::geom_start, m_dataPositions, m_fileStream, m_nBins, and name().
Referenced by exec().
readEvents()
void Mantid::MDAlgorithms::LoadSQW::readEvents (Mantid::DataObjects::MDEventWorkspace< DataObjects::MDEvent< 4 >, 4 > * ws) protected virtual
Read events onto the workspace.
Add events after reading pixels/datapoints from file.
Definition at line 200 of file LoadSQW.cpp.
References Mantid::Kernel::DiskBuffer::flushCache(), Mantid::API::Algorithm::g_log, Mantid::Kernel::Logger::information(), m_dataPositions, m_fileStream, m_nDataPoints, m_prog, PARALLEL_FOR_NO_WSP_CHECK, Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::pix_start, Mantid::Kernel::ProgressBase::report(), Mantid::Kernel::ProgressBase::setNotifyStep(), Mantid::Kernel::ProgressBase::setNumSteps(), and tp.
Referenced by exec().
readSQWDimensions()
void Mantid::MDAlgorithms::LoadSQW::readSQWDimensions (std::vector< Mantid::Geometry::MDHistoDimensionBuilder > & DimVectorOut) protected
Read SQW dimensions.
Add a dimension after reading info from file.
Definition at line 598 of file LoadSQW.cpp.
References buildMDDimsBase(), m_dataPositions, m_fileStream, m_nBins, and Mantid::MDAlgorithms::LoadSQWHelper::dataPositions::min_max_start.
Referenced by exec().
summary()
const std::string Mantid::MDAlgorithms::LoadSQW::summary () const inline override virtual
Summary of algorithms purpose.
Implements Mantid::API::Algorithm.
Definition at line 91 of file LoadSQW.h.
version()
int Mantid::MDAlgorithms::LoadSQW::version () const inline override virtual
Algorithm's version for identification.
Implements Mantid::API::Algorithm.
Definition at line 97 of file LoadSQW.h.
Member Data Documentation
m_boxSizes
std::vector<uint64_t> Mantid::MDAlgorithms::LoadSQW::m_boxSizes protected
Definition at line 148 of file LoadSQW.h.
Referenced by readBoxSizes().
m_dataPositions
LoadSQWHelper::dataPositions Mantid::MDAlgorithms::LoadSQW::m_dataPositions protected
Instance of helper type, which describes the positions of the data within binary Horace file.
Definition at line 146 of file LoadSQW.h.
Referenced by addLattice(), parseMetadata(), readBoxSizes(), readDNDDimensions(), readEvents(), and readSQWDimensions().
m_fileName
std::string Mantid::MDAlgorithms::LoadSQW::m_fileName protected
the name of the file to work with
Definition at line 134 of file LoadSQW.h.
Referenced by exec().
m_fileStream
std::ifstream Mantid::MDAlgorithms::LoadSQW::m_fileStream protected
File stream containing binary file data.
Definition at line 136 of file LoadSQW.h.
Referenced by addLattice(), parseMetadata(), readBoxSizes(), readDNDDimensions(), readEvents(), and readSQWDimensions().
m_mdImageSize
size_t Mantid::MDAlgorithms::LoadSQW::m_mdImageSize protected
Definition at line 151 of file LoadSQW.h.
m_nBins
std::vector<size_t> Mantid::MDAlgorithms::LoadSQW::m_nBins protected
number of bins in every non-integrated dimension
Definition at line 154 of file LoadSQW.h.
Referenced by exec(), parseMetadata(), readDNDDimensions(), and readSQWDimensions().
m_nDataPoints
uint64_t Mantid::MDAlgorithms::LoadSQW::m_nDataPoints protected
Definition at line 150 of file LoadSQW.h.
Referenced by exec(), parseMetadata(), and readEvents().
m_nDims
size_t Mantid::MDAlgorithms::LoadSQW::m_nDims protected
Definition at line 152 of file LoadSQW.h.
Referenced by parseMetadata().
m_outputFile
std::string Mantid::MDAlgorithms::LoadSQW::m_outputFile protected
OutputFilename param.
Definition at line 142 of file LoadSQW.h.
Referenced by exec().
m_prog
Mantid::API::Progress* Mantid::MDAlgorithms::LoadSQW::m_prog protected
Progress bar.
Definition at line 139 of file LoadSQW.h.
Referenced by exec(), readEvents(), and ~LoadSQW().
The documentation for this class was generated from the following files:
Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadSQW.h
Framework/MDAlgorithms/src/LoadSQW.cpp