Mantid: Mantid::API::AlgorithmFactoryObserver Class Reference
Mantid::API::AlgorithmFactoryObserver Class Reference
#include <AlgorithmFactoryObserver.h>
Public Member Functions
AlgorithmFactoryObserver ()
void observeUpdate (bool turnOn=true)
Function will add/remove the observer to the AlgorithmFactory when something is subscribed to it.
virtual void updateHandle ()
If something subscribes to the AlgorithmFactory, then this function will trigger.
virtual ~AlgorithmFactoryObserver ()
Private Member Functions
void _updateHandle (AlgorithmFactoryUpdateNotification_ptr pNf)
Private Attributes
bool m_observingUpdate {false}
Poco::NObserver< AlgorithmFactoryObserver, AlgorithmFactoryUpdateNotification > m_updateObserver
Poco::NObserver for SubscribeNotification.
Detailed Description
Definition at line 33 of file AlgorithmFactoryObserver.h.
Constructor & Destructor Documentation
AlgorithmFactoryObserver()
Mantid::API::AlgorithmFactoryObserver::AlgorithmFactoryObserver ()
Definition at line 22 of file AlgorithmFactoryObserver.cpp.
~AlgorithmFactoryObserver()
Mantid::API::AlgorithmFactoryObserver::~AlgorithmFactoryObserver () virtual
Definition at line 25 of file AlgorithmFactoryObserver.cpp.
References observeUpdate().
Member Function Documentation
_updateHandle()
void Mantid::API::AlgorithmFactoryObserver::_updateHandle (AlgorithmFactoryUpdateNotification_ptr pNf) private
Definition at line 60 of file AlgorithmFactoryObserver.cpp.
References UNUSED_ARG, and updateHandle().
observeUpdate()
void Mantid::API::AlgorithmFactoryObserver::observeUpdate (bool turnOn = true)
Function will add/remove the observer to the AlgorithmFactory when something is subscribed to it.
Parameters
turnOn bool; if this is True then, if not already present, the observer will be added else removed if it's false.
Definition at line 41 of file AlgorithmFactoryObserver.cpp.
References m_observingUpdate, and m_updateObserver.
Referenced by ~AlgorithmFactoryObserver().
updateHandle()
void Mantid::API::AlgorithmFactoryObserver::updateHandle () virtual
If something subscribes to the AlgorithmFactory, then this function will trigger.
works by overloading this class and overriding this function.
Reimplemented in Mantid::PythonInterface::AlgorithmFactoryObserverAdapter.
Definition at line 55 of file AlgorithmFactoryObserver.cpp.
Referenced by _updateHandle().
Member Data Documentation
m_observingUpdate
bool Mantid::API::AlgorithmFactoryObserver::m_observingUpdate {false} private
Definition at line 43 of file AlgorithmFactoryObserver.h.
Referenced by observeUpdate().
m_updateObserver
Poco::NObserver<AlgorithmFactoryObserver, AlgorithmFactoryUpdateNotification> Mantid::API::AlgorithmFactoryObserver::m_updateObserver private
Poco::NObserver for SubscribeNotification.
Definition at line 48 of file AlgorithmFactoryObserver.h.
Referenced by observeUpdate().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/AlgorithmFactoryObserver.h
Framework/API/src/AlgorithmFactoryObserver.cpp