Mantid: Framework/Nexus/inc/MantidNexus/NexusAddress.h File Reference
NexusAddress.h File Reference
#include "MantidNexus/DllConfig.h"
#include <filesystem>
#include <memory>
#include <vector>
Classes
class Mantid::Nexus::NexusAddress
This simple class encapsulates some methods for working with paths inside a Nexus file.
Namespaces
namespace Mantid
Helper class which provides the Collimation Length for SANS instruments.
namespace Mantid::Nexus
Header for a base Nexus::Exception.
Functions
MANTID_NEXUS_DLL bool operator!= (std::string const &s, Mantid::Nexus::NexusAddress const &p)
MANTID_NEXUS_DLL std::string operator+ (char const s[], Mantid::Nexus::NexusAddress const &p)
MANTID_NEXUS_DLL std::string operator+ (std::string const &s, Mantid::Nexus::NexusAddress const &p)
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream &os, Mantid::Nexus::NexusAddress const &p)
MANTID_NEXUS_DLL bool operator== (std::string const &s, Mantid::Nexus::NexusAddress const &p)
Function Documentation
operator!=()
MANTID_NEXUS_DLL bool operator!= (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 139 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator+() [1/2]
MANTID_NEXUS_DLL std::string operator+ (char const s[], Mantid::Nexus::NexusAddress const & p)
Definition at line 143 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator+() [2/2]
MANTID_NEXUS_DLL std::string operator+ (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 141 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator<<()
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream & os, Mantid::Nexus::NexusAddress const & p)
Definition at line 145 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().
operator==()
MANTID_NEXUS_DLL bool operator== (std::string const & s, Mantid::Nexus::NexusAddress const & p)
Definition at line 137 of file NexusAddress.cpp.
References Mantid::Nexus::NexusAddress::string().