Mantid: Mantid::Geometry::StructuredDetector Class Reference
Mantid::Geometry::StructuredDetector Class Reference
StructuredDetector is a type of CompAssembly, an assembly of components.
#include <StructuredDetector.h>
Public Member Functions
IComponent * clone () const override
Make a clone of the present component.
void draw () const override
Draws the objcomponent.
void drawObject () const override
Draws the Object.
std::shared_ptr< Detector > getAtXY (const size_t x, const size_t y) const
Return a pointer to the component in the assembly at the (X,Y) pixel position.
std::vector< int > const & getB () const
Returns the blue color channel for detector colors.
void getBoundingBox (BoundingBox &assemblyBox) const override
Get the bounding box for this component and store it in the given argument.
void getBoundingBox (BoundingBox &assemblyBox) const override
Retrieve the cached bounding box.
std::shared_ptr< const IComponent > getComponentByName (const std::string &cname, int nlevels=0) const override
Returns a pointer to the first component of assembly encountered with the given name.
detid_t getDetectorIDAtXY (const size_t X, const size_t Y) const
Return the detector ID corresponding to the component in the assembly at the (X,Y) pixel position.
std::vector< int > const & getG () const
Returns the green color channel for detector colors.
int getPointInObject (Kernel::V3D &point) const override
Try to find a point that lies within (or on) the object.
std::vector< int > const & getR () const
Returns the red color channel for detector colors.
std::vector< double > const & getXValues () const
std::pair< size_t, size_t > getXYForDetectorID (const detid_t detectorID) const
Given a detector ID, return the X,Y coords into the structured detector.
std::vector< double > const & getYValues () const
bool idFillByFirstY () const
Returns the idFillByFirstY.
detid_t idStart () const
Returns the idStart.
int idStep () const
Returns the idStep.
int idStepByRow () const
Returns the idStepByRow.
void initDraw () const override
Initializes the ObjComponent for rendering, this function should be called before rendering.
void initialize (size_t xPixels, size_t yPixels, std::vector< double > &&x, std::vector< double > &&y, bool isZBeam, detid_t idStart, bool idFillByFirstY, int idStepByRow, int idStep=1)
Create all the detector pixels of this rectangular detector.
int interceptSurface (Track &track) const override
Checks whether the track given will pass through this Component.
bool isOnSide (const Kernel::V3D &point) const override
Does the point given lie on the surface of this object component?
bool isValid (const Kernel::V3D &point) const override
Does the point given lie within this object component?
const Kernel::Material material () const override
Returns the material of the detector.
detid_t maxDetectorID ()
maximum detector id
detid_t minDetectorID ()
minimum detector id
virtual size_t registerContents (class ComponentVisitor &componentVisitor) const override
Register the structured detector for Instrument 2.0 usage.
void setColors (const std::vector< int > &r, const std::vector< int > &g, const std::vector< int > &b) const
Sets the colours for detector IDs based on color maps created by instrument actor.
const std::shared_ptr< const IObject > shape () const override
Returns the shape of the Object.
double solidAngle (const Geometry::SolidAngleParams &params) const override
Finds the approximate solid angle covered by the component when viewed from the point given.
StructuredDetector ()
Empty constructor.
StructuredDetector (const std::string &name, IComponent *reference=nullptr)
Constructor with a name and parent reference.
StructuredDetector (const StructuredDetector *base, const ParameterMap *map)
Parametrized constructor.
std::string type () const override
String description of the type of component.
size_t xPixels () const
Returns the number of pixels in the X direction.
size_t yPixels () const
Returns the number of pixels in the Y direction.
Public Member Functions inherited from Mantid::Geometry::CompAssembly
int add (IComponent *) override
Add a component to the assembly.
void addChildren (IComponent *comp)
Add a copy (clone) of a component.
int addCopy (IComponent *) override
AddCopy method.
int addCopy (IComponent *, const std::string &) override
Add a copy (clone) of a component and rename it.
CompAssembly ()
Empty constructor.
CompAssembly (const CompAssembly &)
Copy constructor.
CompAssembly (const IComponent *base, const ParameterMap *map)
Constructor for parametrized version.
CompAssembly (const std::string &, IComponent *reference=nullptr)
Constructor with a name and parent reference.
std::shared_ptr< IComponent > getChild (const int i) const override
Get a pointer to the ith component within the assembly. Easier to use than.
void getChildren (std::vector< IComponent_const_sptr > &outVector, bool recursive) const override
Returns a vector of all children contained.
Kernel::V3D getPos () const override
Gets the absolute position of the Parametrized CompAssembly This attempts to read the cached position value from the parameter map, and creates it if it is not available.
Kernel::Quat getRotation () const override
Gets the absolute position of the Parametrized CompAssembly This attempts to read the cached position value from the parameter map, and creates it if it is not available.
int nelements () const override
Return the number of elements in the assembly.
CompAssembly & operator= (const CompAssembly &other)
std::shared_ptr< IComponent > operator[] (int i) const override
Get a pointer to the ith component in the assembly.
void printChildren (std::ostream &) const override
Print information about all children.
void printTree (std::ostream &) const override
Print information about all the elements in the tree to a stream Loops through all components in the tree and call printSelf(os).
int remove (IComponent *)
Remove a component from the assembly.
void testIntersectionWithChildren (Track &testRay, std::deque< IComponent_const_sptr > &searchQueue) const override
Test the intersection of the ray with the children of the component assembly, for InstrumentRayTracer
~CompAssembly () override
Destructor.
Public Member Functions inherited from Mantid::Geometry::ICompAssembly
ICompAssembly ()
Public Member Functions inherited from Mantid::Geometry::IComponent
virtual ~IComponent ()=default
Destructor.
Public Member Functions inherited from Mantid::Geometry::Component
Component ()
Create Empty Component at Origin, with no orientation and null parent.
Component (const IComponent *base, const ParameterMap *map)
Constructor for parametrized component.
Component (std::string name, const Kernel::V3D &position, const Kernel::Quat &rotation, IComponent *parent=nullptr)
Create a named component with positioning vector, orientation and parent.
Component (std::string name, const Kernel::V3D &position, IComponent *parent=nullptr)
Create a named component with positioning vector, and parent component.
Component (std::string name, IComponent *parent=nullptr)
Create a named component with a parent component (optional)
std::vector< std::shared_ptr< const IComponent > > getAncestors () const override
Return an array of all ancestors.
IComponent const * getBaseComponent () const override
Returns const pointer to base component if this component is parametrized.
ComponentID getComponentID () const override
Returns the ComponentID - a unique identifier of the component.
double getDistance (const IComponent &) const override
Get the distance to another IComponent.
std::string getFullName () const override
Get the full pathname.
std::string getName () const override
Get the IComponent name.
std::shared_ptr< const IComponent > getParent () const override
Return a pointer to the current parent. as shared pointer.
Kernel::V3D getPos () const override
Get the position of the IComponent. Tree structure is traverse through the.
Kernel::V3D getRelativePos () const override
Get the position relative to the parent IComponent (absolute if no parent)
Kernel::Quat getRelativeRot () const override
Get the relative Orientation.
Kernel::Quat getRotation () const override
Get the absolute orientation of the IComponent.
std::optional< Kernel::V2D > getSideBySideViewPos () const override
Return the position of the component required on the instrument side by side view.
bool isParentNamed (const std::string &expectedName, int maxDepth=-1) const
Return true if one of the parents of this component is named something.
void rotate (const Kernel::Quat &) override
Rotate the IComponent. This is relative to parent.
void rotate (double, const Kernel::V3D &) override
Rotate the IComponent by an angle in degrees with respect to an axis.
void setName (const std::string &) override
Set the IComponent name.
void setParent (IComponent *) override
Assign a parent IComponent. Previous parent link is lost.
void setPos (const Kernel::V3D &) override
Set the position of the Component The position is with respect to the parent Component.
void setPos (double, double, double) override
Set the IComponent position, x, y, z respective to parent (if present)
void setRot (const Kernel::Quat &) override
Set the orientation Kernel::Quaternion relative to parent (if present)
void setSideBySideViewPos (const Kernel::V2D &) override
Set the IComponent position in the side by side instrument view.
void translate (const Kernel::V3D &) override
Translate the IComponent (vector form). This is relative to parent if.
void translate (double, double, double) override
Translate the IComponent (x,y,z form). This is relative to parent if.
virtual std::string typeName () const
std::set< std::string > getParameterNames (bool recursive=true) const override
Return the parameter names.
std::map< std::string, ComponentID > getParameterNamesByComponent () const override
return the parameter names and the component they are from
bool hasParameter (const std::string &name, bool recursive=true) const override
Returns a boolean indicating if the component has the named parameter.
std::vector< double > getNumberParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a double.
std::vector< int > getIntParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as an int.
std::string getParameterType (const std::string &pname, bool recursive=true) const override
Get a parameter's type – this is HACK until Python can export property regardless of the property type.
std::string getDescription () const
Get this component parameter's description – no recursive search within children.
std::string getParamDescription (const std::string &pname, bool recursive=true) const
Get description of a parameter attached to this component
std::string getParamShortDescription (const std::string &pname, bool recursive=true) const
Get a component's parameter short description.
std::string getShortDescription () const
Get a components's short description.
void setDescription (const std::string &descr)
Set components description.
std::vector< bool > getBoolParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a bool.
std::vector< Kernel::V3D > getPositionParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::V3D.
std::vector< Kernel::Quat > getRotationParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a Kernel::Quaternion.
std::vector< std::string > getStringParameter (const std::string &pname, bool recursive=true) const override
Get a parameter defined as a string.
std::string getParameterAsString (const std::string &pname, bool recursive=true) const override
get a string representation of a parameter
bool getParameterVisible (const std::string &p_name, bool recursive) const override
Get a visibility attribute of a parameter from the parameter map.
double getFittingParameter (const std::string &pname, double xvalue) const
Get fitting parameter.
void printSelf (std::ostream &) const override
Prints a text representation of itself.
const IComponent * base () const
Returns the address of the base component.
Kernel::V3D getScaleFactor () const override
Returns the ScaleFactor.
const IComponent * getBareParent () const override
Returns the bare pointer to the IComponent parent.
virtual void readXMLAttributes (const Poco::XML::Attributes &attr)
Reads the XML attributes from Poco XML parser.
virtual void writeXML (Poco::XML::XMLWriter &writer) const
virtual void appendXML (std::ostream &xmlStream) const
Append to an open XML string.
bool isParametrized () const override
Return true if the Component is, in fact, parametrized (that is - it has a valid parameter map)
bool hasComponentInfo () const
size_t index () const
Helper for legacy access mode. Returns the index of the component.
Public Member Functions inherited from Mantid::Geometry::IObjComponent
GeometryHandler * Handle () const
Gets the GeometryHandler.
IObjComponent ()
IObjComponent (const IObjComponent &)
Copy constructor.
IObjComponent (GeometryHandler *the_handler)
Constructor, specifying the GeometryHandler (renderer engine) for this IObjComponent.
IObjComponent & operator= (const IObjComponent &rhs)
Assignment operator.
~IObjComponent () override
Static Public Member Functions
static bool compareName (const std::string &proposedMatch)
Matches name to Structured Detector.
Private Member Functions
Detector * addDetector (CompAssembly *parent, const std::string &name, size_t x, size_t y, detid_t id)
Creates new hexahedral detector pixel at row x column y using the detector vertex values.
void createDetectors ()
Creates all detector pixels within the StructuredDetector.
void init ()
initialize members to bare defaults
StructuredDetector & operator= (const ICompAssembly &)
Private copy assignment operator.
Private Attributes
std::vector< int > b
std::vector< int > g
const StructuredDetector * m_base
Pointer to the base RectangularDetector, for parametrized instruments.
bool m_idFillByFirstY
IDs are filled in Y fastest.
detid_t m_idStart
IDs start here.
int m_idStep
Step size in ID in each col.
int m_idStepByRow
Step size in ID in each row.
detid_t m_maxDetId
maximum detector id
detid_t m_minDetId
minimum detector id
size_t m_xPixels
The number of pixels in the X (horizontal) direction;.
std::vector< double > m_xvalues
size_t m_yPixels
The number of pixels in the Y (vertical) direction;.
std::vector< double > m_yvalues
std::vector< int > r
Additional Inherited Members
Protected Types inherited from Mantid::Geometry::CompAssembly
using comp_it = std::vector< IComponent * >::iterator
Iterator type.
using const_comp_it = std::vector< IComponent * >::const_iterator
Const iterator type.
Protected Member Functions inherited from Mantid::Geometry::ICompAssembly
ICompAssembly (const ICompAssembly &)=default
Protected copy constructor.
Protected Member Functions inherited from Mantid::Geometry::Component
template<class TYPE >
std::vector< TYPE > getParameter (const std::string &p_name, bool recursive) const
Get a parameter from the parameter map.
void swap (const Component *base, const ParameterMap *pmap)
Swap the current references to the un-parameterized component and parameter map for new ones.
Protected Member Functions inherited from Mantid::Geometry::IObjComponent
void setGeometryHandler (GeometryHandler *h)
Reset the current geometry handler.
Protected Attributes inherited from Mantid::Geometry::CompAssembly
BoundingBox * m_cachedBoundingBox
A cached bounding box.
std::vector< IComponent * > m_children
the group of child components
Protected Attributes inherited from Mantid::Geometry::Component
const IComponent * m_parent
Parent component in the tree.
const Component * m_base
The base component - this is the unmodified component (without the parameters).
const ParameterMap * m_map
A pointer to const ParameterMap containing the parameters.
std::string m_name
Name of the component.
Kernel::V3D m_pos
Position w.
Kernel::Quat m_rot
Orientation.
std::optional< Kernel::V2D > m_sidebysideviewpos
Position of component in instrument viewer side by side view.
Detailed Description
StructuredDetector is a type of CompAssembly, an assembly of components.
It is designed to be a more efficient way of defining instruments which are topologically regular but geometrically irregular.
Assembly of Detector objects with topological regularity and geometrical irregularity
Author
Lamar Moore, ISIS
Date
07-March-2016
Definition at line 31 of file StructuredDetector.h.
Constructor & Destructor Documentation
StructuredDetector() [1/3]
Mantid::Geometry::StructuredDetector::StructuredDetector ()
Empty constructor.
Definition at line 30 of file StructuredDetector.cpp.
References init().
Referenced by clone().
StructuredDetector() [2/3]
Mantid::Geometry::StructuredDetector::StructuredDetector (const std::string & name, IComponent * reference = nullptr)
Constructor with a name and parent reference.
Valued constructor.
Parameters
name :: name of the assembly
reference :: the parent Component
If the reference is an object of class Component,
normal parenting apply. If the reference object is an assembly itself, then in addition to parenting this is registered as a children of reference.
Definition at line 41 of file StructuredDetector.cpp.
References init(), and Mantid::Geometry::IComponent::setName().
StructuredDetector() [3/3]
Mantid::Geometry::StructuredDetector::StructuredDetector (const StructuredDetector * base, const ParameterMap * map)
Parametrized constructor.
Constructor for a parametrized StructuredrDetector.
Parameters
base the base (un-parametrized) StructuredDetector
map pointer to the ParameterMap
Definition at line 51 of file StructuredDetector.cpp.
References init().
Member Function Documentation
addDetector()
Detector * Mantid::Geometry::StructuredDetector::addDetector (CompAssembly * parent, const std::string & name, size_t x, size_t y, detid_t id) private
Creates new hexahedral detector pixel at row x column y using the detector vertex values.
Parameters
parent :: The parent component assembly
name :: The pixel name identifier
x :: The pixel row
y :: The pixel column
id :: The pixel ID
Returns
newly created detector.
Definition at line 366 of file StructuredDetector.cpp.
References Mantid::Geometry::ShapeFactory::createHexahedralShape(), m_xPixels, m_xvalues, m_yvalues, name, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by createDetectors().
clone()
IComponent * Mantid::Geometry::StructuredDetector::clone () const override virtual
Make a clone of the present component.
Clone method Make a copy of the component assembly.
Returns
new(*this)
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 80 of file StructuredDetector.cpp.
References StructuredDetector().
compareName()
bool Mantid::Geometry::StructuredDetector::compareName (const std::string & proposedMatch) static
Matches name to Structured Detector.
Definition at line 56 of file StructuredDetector.cpp.
Referenced by Mantid::Geometry::InstrumentDefinitionParser::appendLeaf(), and Mantid::Geometry::InstrumentDefinitionParser::createStructuredDetector().
createDetectors()
void Mantid::Geometry::StructuredDetector::createDetectors () private
Creates all detector pixels within the StructuredDetector.
Definition at line 320 of file StructuredDetector.cpp.
References Mantid::Geometry::CompAssembly::add(), addDetector(), Mantid::Geometry::CompAssembly::CompAssembly(), getDetectorIDAtXY(), Mantid::Geometry::IComponent::getName(), m_idStart, m_maxDetId, m_minDetId, m_xPixels, and m_yPixels.
Referenced by initialize().
draw()
void Mantid::Geometry::StructuredDetector::draw () const override virtual
Draws the objcomponent.
Draws the objcomponent, If the handler is not set then this function does nothing.
Implements Mantid::Geometry::IObjComponent.
Definition at line 515 of file StructuredDetector.cpp.
References Mantid::Geometry::IObjComponent::Handle(), and Mantid::Geometry::GeometryHandler::render().
drawObject()
void Mantid::Geometry::StructuredDetector::drawObject () const override virtual
Draws the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 525 of file StructuredDetector.cpp.
getAtXY()
std::shared_ptr< Detector > Mantid::Geometry::StructuredDetector::getAtXY (const size_t x, const size_t y) const
Return a pointer to the component in the assembly at the (X,Y) pixel position.
Parameters
x :: index from 0..m_xPixels-1
y :: index from 0..m_yPixels-1
Returns
a pointer to the component in the assembly at the (X,Y) pixel position
Exceptions
runtime_error if the x/y pixel width is not set, or X/Y are out of range
Definition at line 93 of file StructuredDetector.cpp.
References Mantid::Geometry::CompAssembly::getChild(), Mantid::Geometry::x, xPixels(), Mantid::Geometry::y, and yPixels().
Referenced by getBoundingBox().
getB()
std::vector< int > const & Mantid::Geometry::StructuredDetector::getB () const
Returns the blue color channel for detector colors.
Returns
blue color channel
Definition at line 194 of file StructuredDetector.cpp.
References b, getB(), m_base, and Mantid::Geometry::Component::m_map.
Referenced by getB().
getBoundingBox() [1/2]
void Mantid::Geometry::CompAssembly::getBoundingBox (BoundingBox & assemblyBox) const override virtual
Get the bounding box for this component and store it in the given argument.
Get the bounding box for this assembly.
It is simply the sum of the bounding boxes of its children
Parameters
assemblyBox :: [Out] The resulting bounding box is stored here.
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 80 of file CompAssembly.cpp.
getBoundingBox() [2/2]
void Mantid::Geometry::StructuredDetector::getBoundingBox (BoundingBox & assemblyBox) const override virtual
Retrieve the cached bounding box.
Get the bounding box and store it in the given object.
This is cached after the first call.
Parameters
assemblyBox :: A BoundingBox object that will be overwritten
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 484 of file StructuredDetector.cpp.
References Mantid::Geometry::ComponentInfo::boundingBox(), Mantid::Geometry::ParameterMap::componentInfo(), getAtXY(), Mantid::Geometry::BoundingBox::grow(), Mantid::Geometry::Component::hasComponentInfo(), Mantid::Geometry::Component::index(), Mantid::Geometry::CompAssembly::m_cachedBoundingBox, Mantid::Geometry::Component::m_map, xPixels(), and yPixels().
getComponentByName()
std::shared_ptr< const IComponent > Mantid::Geometry::StructuredDetector::getComponentByName (const std::string & cname, int nlevels = 0) const override virtual
Returns a pointer to the first component of assembly encountered with the given name.
Find a component by name.
Parameters
cname :: The name of the component. If there are multiple matches, the first one found is returned. If the name contains '/', it will search for the component whose name occurs before the '/' then within that component's assembly, search the component whose name occurs after the '/' and so on with any subsequent '/'. For example to find 'tube020' in 'panel07', one could use the cname 'panel07/tube020', given that tube020 is unique within panel07.
nlevels :: Optional argument to limit number of levels searched. If cname has a '/', then nlevels will apply to each step delimited by the '/'s, rather than the whole search. In particular, nlevels=1, would force cname to be a full path name.
Returns
A shared pointer to the component
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 427 of file StructuredDetector.cpp.
References Mantid::Geometry::CompAssembly::getComponentByName(), and Mantid::Geometry::IComponent::getName().
getDetectorIDAtXY()
detid_t Mantid::Geometry::StructuredDetector::getDetectorIDAtXY (const size_t x, const size_t y) const
Return the detector ID corresponding to the component in the assembly at the (X,Y) pixel position.
No bounds check is made!
Parameters
x :: index from 0..m_xPixels-1
y :: index from 0..m_yPixels-1
Returns
detector ID int
Exceptions
runtime_error if the x/y pixel width is not set, or X/Y are out of range
Definition at line 115 of file StructuredDetector.cpp.
References m_base, m_idFillByFirstY, m_idStart, m_idStep, m_idStepByRow, Mantid::Geometry::Component::m_map, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by createDetectors().
getG()
std::vector< int > const & Mantid::Geometry::StructuredDetector::getG () const
Returns the green color channel for detector colors.
Returns
green color channel
Definition at line 185 of file StructuredDetector.cpp.
References g, getG(), m_base, and Mantid::Geometry::Component::m_map.
Referenced by getG().
getPointInObject()
int Mantid::Geometry::StructuredDetector::getPointInObject (Kernel::V3D & point) const override virtual
Try to find a point that lies within (or on) the object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 475 of file StructuredDetector.cpp.
getR()
std::vector< int > const & Mantid::Geometry::StructuredDetector::getR () const
Returns the red color channel for detector colors.
Returns
red color channel
Definition at line 176 of file StructuredDetector.cpp.
References getR(), m_base, Mantid::Geometry::Component::m_map, and r.
Referenced by getR().
getXValues()
std::vector< double > const & Mantid::Geometry::StructuredDetector::getXValues () const
Definition at line 242 of file StructuredDetector.cpp.
References getXValues(), m_base, Mantid::Geometry::Component::m_map, and m_xvalues.
Referenced by getXValues().
getXYForDetectorID()
std::pair< size_t, size_t > Mantid::Geometry::StructuredDetector::getXYForDetectorID (const detid_t detectorID) const
Given a detector ID, return the X,Y coords into the structured detector.
Parameters
detectorID :: detectorID
Returns
pair of (x,y)
Definition at line 129 of file StructuredDetector.cpp.
References m_base, m_idFillByFirstY, m_idStart, m_idStep, m_idStepByRow, and Mantid::Geometry::Component::m_map.
getYValues()
std::vector< double > const & Mantid::Geometry::StructuredDetector::getYValues () const
Definition at line 249 of file StructuredDetector.cpp.
References getYValues(), m_base, Mantid::Geometry::Component::m_map, and m_yvalues.
Referenced by getYValues().
idFillByFirstY()
bool Mantid::Geometry::StructuredDetector::idFillByFirstY () const
Returns the idFillByFirstY.
Definition at line 219 of file StructuredDetector.cpp.
References m_base, m_idFillByFirstY, and Mantid::Geometry::Component::m_map.
Referenced by initialize().
idStart()
detid_t Mantid::Geometry::StructuredDetector::idStart () const
Returns the idStart.
Definition at line 211 of file StructuredDetector.cpp.
References m_base, m_idStart, and Mantid::Geometry::Component::m_map.
Referenced by initialize().
idStep()
int Mantid::Geometry::StructuredDetector::idStep () const
Returns the idStep.
Definition at line 235 of file StructuredDetector.cpp.
References m_base, m_idStep, and Mantid::Geometry::Component::m_map.
Referenced by initialize().
idStepByRow()
int Mantid::Geometry::StructuredDetector::idStepByRow () const
Returns the idStepByRow.
Definition at line 227 of file StructuredDetector.cpp.
References m_base, m_idStepByRow, and Mantid::Geometry::Component::m_map.
Referenced by initialize().
init()
void Mantid::Geometry::StructuredDetector::init () private
initialize members to bare defaults
Definition at line 63 of file StructuredDetector.cpp.
References Mantid::Geometry::IObjComponent::GeometryHandler, m_idFillByFirstY, m_idStart, m_idStep, m_idStepByRow, m_maxDetId, m_minDetId, m_xPixels, m_yPixels, and Mantid::Geometry::IObjComponent::setGeometryHandler().
Referenced by StructuredDetector(), StructuredDetector(), and StructuredDetector().
initDraw()
void Mantid::Geometry::StructuredDetector::initDraw () const override virtual
Initializes the ObjComponent for rendering, this function should be called before rendering.
Implements Mantid::Geometry::IObjComponent.
Definition at line 531 of file StructuredDetector.cpp.
References Mantid::Geometry::IObjComponent::Handle(), and Mantid::Geometry::GeometryHandler::initialize().
initialize()
void Mantid::Geometry::StructuredDetector::initialize (size_t xPixels, size_t yPixels, std::vector< double > && x, std::vector< double > && y, bool isZBeam, detid_t idStart, bool idFillByFirstY, int idStepByRow, int idStep = 1)
Create all the detector pixels of this rectangular detector.
Initialize a StructuredDetector by creating all of the pixels contained within it.
You should have set the name, position and rotation and facing of this object BEFORE calling this. NB xPixels and yPixels requires (xPixels+1)*(yPixels+1) vertices
Parameters
xPixels :: number of pixels in X
yPixels :: number of pixels in Y
x :: X vertices
y :: Y vertices
isZBeam :: Whether or not the alongBeam axis is z
idStart :: detector ID of the first pixel
idFillByFirstY :: set to true if ID numbers increase with Y indices first. That is: (0,0)=0; (0,1)=1, (0,2)=2 and so on.
idStepByRow :: amount to increase the ID number on each row. e.g, if you fill by Y first, and set idStepByRow = 100, and have 50 Y pixels, you would get: (0,0)=0; (0,1)=1; ... (0,49)=49; (1,0)=100; (1,1)=101; etc.
idStep :: amount to increase each individual ID number with a row. e.g, if you fill by Y first, and idStep=100 and idStart=1 then (0,0)=1; (0,1)=101; and so on
IDs start here
IDs are filled in Y fastest
Step size in ID in each row
Step size in ID in each col
Definition at line 278 of file StructuredDetector.cpp.
References createDetectors(), idFillByFirstY(), idStart(), idStep(), idStepByRow(), m_idFillByFirstY, m_idStart, m_idStep, m_idStepByRow, Mantid::Geometry::Component::m_map, m_xPixels, m_xvalues, m_yPixels, m_yvalues, Mantid::Geometry::x, xPixels(), Mantid::Geometry::y, and yPixels().
interceptSurface()
int Mantid::Geometry::StructuredDetector::interceptSurface (Track & track) const override virtual
Checks whether the track given will pass through this Component.
Implements Mantid::Geometry::IObjComponent.
Definition at line 464 of file StructuredDetector.cpp.
isOnSide()
bool Mantid::Geometry::StructuredDetector::isOnSide (const Kernel::V3D & point) const override virtual
Does the point given lie on the surface of this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 459 of file StructuredDetector.cpp.
isValid()
bool Mantid::Geometry::StructuredDetector::isValid (const Kernel::V3D & point) const override virtual
Does the point given lie within this object component?
Implements Mantid::Geometry::IObjComponent.
Definition at line 454 of file StructuredDetector.cpp.
material()
const Kernel::Material Mantid::Geometry::StructuredDetector::material () const override virtual
Returns the material of the detector.
Implements Mantid::Geometry::IObjComponent.
Definition at line 586 of file StructuredDetector.cpp.
maxDetectorID()
int Mantid::Geometry::StructuredDetector::maxDetectorID ()
maximum detector id
Returns the maximum detector id.
Returns
maximum detector id
Definition at line 421 of file StructuredDetector.cpp.
References m_base, Mantid::Geometry::Component::m_map, and m_maxDetId.
minDetectorID()
int Mantid::Geometry::StructuredDetector::minDetectorID ()
minimum detector id
Returns the minimum detector id.
Returns
minimum detector id
Definition at line 411 of file StructuredDetector.cpp.
References m_base, Mantid::Geometry::Component::m_map, and m_minDetId.
operator=()
StructuredDetector & Mantid::Geometry::StructuredDetector::operator= (const ICompAssembly &) private
Private copy assignment operator.
registerContents()
size_t Mantid::Geometry::StructuredDetector::registerContents (class ComponentVisitor & componentVisitor) const override virtual
Register the structured detector for Instrument 2.0 usage.
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 612 of file StructuredDetector.cpp.
References Mantid::Geometry::ComponentVisitor::registerStructuredBank().
setColors()
void Mantid::Geometry::StructuredDetector::setColors (const std::vector< int > & r, const std::vector< int > & g, const std::vector< int > & b) const
Sets the colours for detector IDs based on color maps created by instrument actor.
Parameters
r red color channel
g green color channel
b blue color channel
Definition at line 163 of file StructuredDetector.cpp.
References b, g, m_base, Mantid::Geometry::Component::m_map, r, and setColors().
Referenced by setColors().
shape()
const std::shared_ptr< const IObject > Mantid::Geometry::StructuredDetector::shape () const override virtual
Returns the shape of the Object.
Implements Mantid::Geometry::IObjComponent.
Definition at line 539 of file StructuredDetector.cpp.
References Mantid::Geometry::ShapeFactory::createShape(), m_xPixels, m_xvalues, m_yPixels, m_yvalues, and xPixels().
solidAngle()
double Mantid::Geometry::StructuredDetector::solidAngle (const Geometry::SolidAngleParams & params) const override virtual
Finds the approximate solid angle covered by the component when viewed from the point given.
Implements Mantid::Geometry::IObjComponent.
Definition at line 470 of file StructuredDetector.cpp.
type()
std::string Mantid::Geometry::StructuredDetector::type () const inline override virtual
String description of the type of component.
Reimplemented from Mantid::Geometry::CompAssembly.
Definition at line 34 of file StructuredDetector.h.
xPixels()
size_t Mantid::Geometry::StructuredDetector::xPixels () const
Returns the number of pixels in the X direction.
Returns
number of X pixels
Definition at line 150 of file StructuredDetector.cpp.
References m_base, Mantid::Geometry::Component::m_map, and m_xPixels.
Referenced by getAtXY(), getBoundingBox(), initialize(), and shape().
yPixels()
size_t Mantid::Geometry::StructuredDetector::yPixels () const
Returns the number of pixels in the Y direction.
Returns
number of Y pixels
Definition at line 203 of file StructuredDetector.cpp.
References m_base, Mantid::Geometry::Component::m_map, and m_yPixels.
Referenced by getAtXY(), getBoundingBox(), and initialize().
Member Data Documentation
b
std::vector<int> Mantid::Geometry::StructuredDetector::b mutable private
Definition at line 166 of file StructuredDetector.h.
Referenced by getB(), and setColors().
g
std::vector<int> Mantid::Geometry::StructuredDetector::g mutable private
Definition at line 165 of file StructuredDetector.h.
Referenced by getG(), and setColors().
m_base
const StructuredDetector* Mantid::Geometry::StructuredDetector::m_base private
Pointer to the base RectangularDetector, for parametrized instruments.
Definition at line 138 of file StructuredDetector.h.
Referenced by getB(), getDetectorIDAtXY(), getG(), getR(), getXValues(), getXYForDetectorID(), getYValues(), idFillByFirstY(), idStart(), idStep(), idStepByRow(), maxDetectorID(), minDetectorID(), setColors(), xPixels(), and yPixels().
m_idFillByFirstY
bool Mantid::Geometry::StructuredDetector::m_idFillByFirstY private
IDs are filled in Y fastest.
Definition at line 155 of file StructuredDetector.h.
Referenced by getDetectorIDAtXY(), getXYForDetectorID(), idFillByFirstY(), init(), and initialize().
m_idStart
detid_t Mantid::Geometry::StructuredDetector::m_idStart private
IDs start here.
Definition at line 153 of file StructuredDetector.h.
Referenced by createDetectors(), getDetectorIDAtXY(), getXYForDetectorID(), idStart(), init(), and initialize().
m_idStep
int Mantid::Geometry::StructuredDetector::m_idStep private
Step size in ID in each col.
Definition at line 159 of file StructuredDetector.h.
Referenced by getDetectorIDAtXY(), getXYForDetectorID(), idStep(), init(), and initialize().
m_idStepByRow
int Mantid::Geometry::StructuredDetector::m_idStepByRow private
Step size in ID in each row.
Definition at line 157 of file StructuredDetector.h.
Referenced by getDetectorIDAtXY(), getXYForDetectorID(), idStepByRow(), init(), and initialize().
m_maxDetId
detid_t Mantid::Geometry::StructuredDetector::m_maxDetId private
maximum detector id
Definition at line 150 of file StructuredDetector.h.
Referenced by createDetectors(), init(), and maxDetectorID().
m_minDetId
detid_t Mantid::Geometry::StructuredDetector::m_minDetId private
minimum detector id
Definition at line 148 of file StructuredDetector.h.
Referenced by createDetectors(), init(), and minDetectorID().
m_xPixels
size_t Mantid::Geometry::StructuredDetector::m_xPixels private
The number of pixels in the X (horizontal) direction;.
Definition at line 143 of file StructuredDetector.h.
Referenced by addDetector(), createDetectors(), init(), initialize(), shape(), and xPixels().
m_xvalues
std::vector<double> Mantid::Geometry::StructuredDetector::m_xvalues private
Definition at line 161 of file StructuredDetector.h.
Referenced by addDetector(), getXValues(), initialize(), and shape().
m_yPixels
size_t Mantid::Geometry::StructuredDetector::m_yPixels private
The number of pixels in the Y (vertical) direction;.
Definition at line 145 of file StructuredDetector.h.
Referenced by createDetectors(), init(), initialize(), shape(), and yPixels().
m_yvalues
std::vector<double> Mantid::Geometry::StructuredDetector::m_yvalues private
Definition at line 162 of file StructuredDetector.h.
Referenced by addDetector(), getYValues(), initialize(), and shape().
r
std::vector<int> Mantid::Geometry::StructuredDetector::r mutable private
Definition at line 164 of file StructuredDetector.h.
Referenced by getR(), and setColors().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/Instrument/StructuredDetector.h
Framework/Geometry/src/Instrument/StructuredDetector.cpp