Mantid: Mantid::DataHandling::LoadMuonNexusV2NexusHelper Class Reference
Mantid::DataHandling::LoadMuonNexusV2NexusHelper Class Reference
#include <LoadMuonNexusV2NexusHelper.h>
Public Member Functions
std::vector< int > getIntVector (const int &numPeriods, const std::string &name) const
int getNumberOfPeriods () const
std::string getPeriodFramesRequested (const int &numPeriods) const
std::string getPeriodLabels () const
std::string getPeriodOutput (const int &numPeriods) const
std::string getPeriodRawFrames (const int &numPeriods) const
std::string getPeriodSequenceString (const int &numPeriods) const
std::string getPeriodTotalCounts () const
std::string getPeriodTypes (const int &numPeriods) const
std::vector< double > loadDeadTimesFromNexus (const std::vector< detid_t > &loadedDetectors, bool isFileMultiPeriod, int periodNumber)
std::optional< std::vector< detid_t > > loadDetectorGroupingFromNexus (const std::vector< detid_t > &loadedDetectors, bool isFileMultiPeriod, int periodNumber)
double loadFirstGoodDataFromNexus ()
Nexus::NXInt loadGoodFramesDataFromNexus (bool isFileMultiPeriod)
double loadLastGoodDataFromNexus ()
std::string loadMainFieldDirectionFromNexus ()
LoadMuonNexusV2NexusHelper (const Nexus::NXEntry &entry)
MuonNexus::SampleInformation loadSampleInformationFromNexus ()
double loadTimeZeroFromNexusFile ()
std::vector< double > loadTimeZeroListFromNexusFile (size_t numSpectra)
Private Attributes
const Nexus::NXEntry & m_entry
Detailed Description
Definition at line 27 of file LoadMuonNexusV2NexusHelper.h.
Constructor & Destructor Documentation
LoadMuonNexusV2NexusHelper()
Mantid::DataHandling::LoadMuonNexusV2NexusHelper::LoadMuonNexusV2NexusHelper (const Nexus::NXEntry & entry)
Definition at line 61 of file LoadMuonNexusV2NexusHelper.cpp.
Member Function Documentation
getIntVector()
std::vector< int > Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getIntVector (const int & numPeriods, const std::string & name) const
Definition at line 258 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXDataSetTyped< T >::load(), m_entry, name, Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), and Mantid::DataHandling::NeXusEntry::PERIOD.
Referenced by getPeriodFramesRequested(), getPeriodOutput(), getPeriodRawFrames(), getPeriodSequenceString(), and getPeriodTypes().
getNumberOfPeriods()
int Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getNumberOfPeriods () const
Definition at line 248 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXClass::getInt(), m_entry, Mantid::Nexus::NXClass::openNXGroup(), and Mantid::DataHandling::NeXusEntry::PERIOD.
getPeriodFramesRequested()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodFramesRequested (const int & numPeriods) const
Definition at line 278 of file LoadMuonNexusV2NexusHelper.cpp.
References getIntVector(), and Mantid::DataHandling::NeXusEntry::REQUESTED.
getPeriodLabels()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodLabels () const
Definition at line 253 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXClass::getString(), m_entry, Mantid::Nexus::NXClass::openNXGroup(), and Mantid::DataHandling::NeXusEntry::PERIOD.
getPeriodOutput()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodOutput (const int & numPeriods) const
Definition at line 284 of file LoadMuonNexusV2NexusHelper.cpp.
References getIntVector(), and Mantid::DataHandling::NeXusEntry::PERIODOUTPUT.
getPeriodRawFrames()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodRawFrames (const int & numPeriods) const
Definition at line 281 of file LoadMuonNexusV2NexusHelper.cpp.
References getIntVector(), and Mantid::DataHandling::NeXusEntry::RAWFRAMES.
getPeriodSequenceString()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodSequenceString (const int & numPeriods) const
Definition at line 270 of file LoadMuonNexusV2NexusHelper.cpp.
References getIntVector(), and Mantid::DataHandling::NeXusEntry::SEQUENCES.
getPeriodTotalCounts()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodTotalCounts () const
Definition at line 288 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXDataSetTyped< T >::load(), m_entry, Mantid::Nexus::NXClass::openNXFloat(), Mantid::Nexus::NXClass::openNXGroup(), Mantid::DataHandling::NeXusEntry::PERIOD, Mantid::DataHandling::NeXusEntry::PERIODCOUNTS, and Mantid::Nexus::NXDataSetTyped< T >::vecBuffer().
getPeriodTypes()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::getPeriodTypes (const int & numPeriods) const
Definition at line 274 of file LoadMuonNexusV2NexusHelper.cpp.
References getIntVector(), and Mantid::DataHandling::NeXusEntry::TYPE.
loadDeadTimesFromNexus()
std::vector< double > Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDeadTimesFromNexus (const std::vector< detid_t > & loadedDetectors, bool isFileMultiPeriod, int periodNumber)
Definition at line 133 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXClass::containsDataSet(), Mantid::DataHandling::NeXusEntry::DEADTIME, Mantid::DataHandling::NeXusEntry::DETECTOR, Mantid::Nexus::NXDataSetTyped< T >::load(), m_entry, Mantid::Nexus::NXClass::openNXFloat(), and Mantid::Nexus::NXClass::openNXGroup().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDeadTimeTable(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDeadTimeTable().
loadDetectorGroupingFromNexus()
std::optional< std::vector< detid_t > > Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadDetectorGroupingFromNexus (const std::vector< detid_t > & loadedDetectors, bool isFileMultiPeriod, int periodNumber)
Definition at line 92 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXClass::containsDataSet(), Mantid::DataHandling::NeXusEntry::DETECTOR, Mantid::DataHandling::NeXusEntry::GROUPING, Mantid::Nexus::NXDataSetTyped< T >::load(), m_entry, Mantid::Nexus::NXClass::openNXGroup(), and Mantid::Nexus::NXClass::openNXInt().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadDetectorGrouping(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadDetectorGrouping().
loadFirstGoodDataFromNexus()
double Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadFirstGoodDataFromNexus ()
Definition at line 159 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXDataSet::attributes, Mantid::DataHandling::NeXusEntry::COUNTS, Mantid::DataHandling::NeXusEntry::DETECTOR, Mantid::DataHandling::NeXusEntry::FIRSTGOODBIN, NXnumtype::FLOAT32, Mantid::Nexus::NXClass::getDataSetInfo(), Mantid::Nexus::NXClass::getFloat(), Mantid::Nexus::NXClass::getInt(), NXnumtype::INT32, m_entry, Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), Mantid::DataHandling::NeXusEntry::RESOLUTION, and Mantid::Nexus::NXInfo::type.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadMuonLogData(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadMuonLogData().
loadGoodFramesDataFromNexus()
NXInt Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadGoodFramesDataFromNexus (bool isFileMultiPeriod)
Definition at line 64 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::DataHandling::NeXusEntry::GOODFRAMES, Mantid::Nexus::NXDataSetTyped< T >::load(), m_entry, Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), and Mantid::DataHandling::NeXusEntry::PERIOD.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadGoodFrames(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadGoodFrames().
loadLastGoodDataFromNexus()
double Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadLastGoodDataFromNexus ()
Definition at line 184 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::Nexus::NXDataSet::attributes, Mantid::DataHandling::NeXusEntry::COUNTS, Mantid::DataHandling::NeXusEntry::DETECTOR, NXnumtype::FLOAT32, Mantid::Nexus::NXClass::getDataSetInfo(), Mantid::Nexus::NXClass::getFloat(), Mantid::Nexus::NXClass::getInt(), NXnumtype::INT32, Mantid::DataHandling::NeXusEntry::LASTGOODBIN, m_entry, Mantid::Nexus::NXClass::openNXGroup(), Mantid::Nexus::NXClass::openNXInt(), Mantid::DataHandling::NeXusEntry::RESOLUTION, and Mantid::Nexus::NXInfo::type.
loadMainFieldDirectionFromNexus()
std::string Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadMainFieldDirectionFromNexus ()
Definition at line 117 of file LoadMuonNexusV2NexusHelper.cpp.
References m_entry, Mantid::Nexus::NXClass::openNXChar(), Mantid::Geometry::orientation(), and Mantid::DataHandling::NeXusEntry::ORIENTATON.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadMuonLogData(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadMuonLogData().
loadSampleInformationFromNexus()
MuonNexus::SampleInformation Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadSampleInformationFromNexus ()
Definition at line 235 of file LoadMuonNexusV2NexusHelper.cpp.
References m_entry, Mantid::DataHandling::MuonNexus::SampleInformation::magneticField, Mantid::DataHandling::NeXusEntry::MAGNETICFIELD, Mantid::Nexus::NXClass::openNXGroup(), Mantid::DataHandling::NeXusEntry::SAMPLE, Mantid::DataHandling::MuonNexus::SampleInformation::temperature, and Mantid::DataHandling::NeXusEntry::TEMPERATURE.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::loadMuonLogData(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::loadMuonLogData().
loadTimeZeroFromNexusFile()
double Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroFromNexusFile ()
Definition at line 209 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::DataHandling::NeXusEntry::DETECTOR, Mantid::Nexus::NXClass::getFloat(), m_entry, Mantid::Nexus::NXClass::openNXGroup(), and Mantid::DataHandling::NeXusEntry::TIMEZERO.
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::applyTimeZeroCorrection(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::applyTimeZeroCorrection().
loadTimeZeroListFromNexusFile()
std::vector< double > Mantid::DataHandling::LoadMuonNexusV2NexusHelper::loadTimeZeroListFromNexusFile (size_t numSpectra)
Definition at line 219 of file LoadMuonNexusV2NexusHelper.cpp.
References Mantid::DataHandling::NeXusEntry::DETECTOR, Mantid::Nexus::NXClass::getFloat(), m_entry, Mantid::Nexus::NXClass::openNXDouble(), Mantid::Nexus::NXClass::openNXGroup(), Mantid::DataHandling::NeXusEntry::TIMEZERO, and Mantid::Nexus::NXDataSetTyped< T >::vecBuffer().
Referenced by Mantid::DataHandling::MultiPeriodLoadMuonStrategy::getTimeZeroTable(), and Mantid::DataHandling::SinglePeriodLoadMuonStrategy::getTimeZeroTable().
Member Data Documentation
m_entry
const Nexus::NXEntry& Mantid::DataHandling::LoadMuonNexusV2NexusHelper::m_entry private
Definition at line 63 of file LoadMuonNexusV2NexusHelper.h.
Referenced by getIntVector(), getNumberOfPeriods(), getPeriodLabels(), getPeriodTotalCounts(), loadDeadTimesFromNexus(), loadDetectorGroupingFromNexus(), loadFirstGoodDataFromNexus(), loadGoodFramesDataFromNexus(), loadLastGoodDataFromNexus(), loadMainFieldDirectionFromNexus(), loadSampleInformationFromNexus(), loadTimeZeroFromNexusFile(), and loadTimeZeroListFromNexusFile().
The documentation for this class was generated from the following files:
Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexusV2NexusHelper.h
Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp