Mantid: MantidQt::MantidWidgets::Batch::RowLocationAdapter Class Reference
MantidQt::MantidWidgets::Batch::RowLocationAdapter Class Reference
#include <RowLocationAdapter.h>
Public Member Functions
RowLocation atIndex (QModelIndexForMainModel const &index) const
QModelIndexForMainModel indexAt (RowLocation const &location, int column=0) const
boost::optional< QModelIndexForMainModel > indexIfExistsAt (RowLocation const &location, int column=0) const
RowLocationAdapter (QStandardItemModel const &model)
Private Member Functions
QModelIndex walkFromRootToParentIndexOf (RowLocation const &location) const
Private Attributes
QStandardItemModel const & m_model
Detailed Description
Definition at line 21 of file RowLocationAdapter.h.
Constructor & Destructor Documentation
RowLocationAdapter()
MantidQt::MantidWidgets::Batch::RowLocationAdapter::RowLocationAdapter (QStandardItemModel const & model)
Definition at line 10 of file RowLocationAdapter.cpp.
Member Function Documentation
atIndex()
RowLocation MantidQt::MantidWidgets::Batch::RowLocationAdapter::atIndex (QModelIndexForMainModel const & index) const
Definition at line 12 of file RowLocationAdapter.cpp.
References index.
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf(), MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult(), MantidQt::MantidWidgets::Batch::JobTreeView::insertChildRowOf(), and MantidQt::MantidWidgets::Batch::FilteredTreeModel::rowLocationAt().
indexAt()
QModelIndexForMainModel MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexAt (RowLocation const & location, int column = 0) const
Definition at line 48 of file RowLocationAdapter.cpp.
References indexIfExistsAt().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::appendChildRowOf(), MantidQt::MantidWidgets::Batch::JobTreeView::appendSubtreeAt(), MantidQt::MantidWidgets::Batch::JobTreeView::cellAt(), MantidQt::MantidWidgets::Batch::BuildSubtreeItems::modelIndexAt(), MantidQt::MantidWidgets::Batch::JobTreeView::removeRowAt(), MantidQt::MantidWidgets::Batch::JobTreeView::replaceSubtreeAt(), MantidQt::MantidWidgets::Batch::JobTreeView::setCellAt(), and MantidQt::MantidWidgets::Batch::JobTreeView::setCellsAt().
indexIfExistsAt()
boost::optional< QModelIndexForMainModel > MantidQt::MantidWidgets::Batch::RowLocationAdapter::indexIfExistsAt (RowLocation const & location, int column = 0) const
Definition at line 34 of file RowLocationAdapter.cpp.
References MantidQt::MantidWidgets::Batch::fromMainModel(), MantidQt::MantidWidgets::Batch::RowLocation::isRoot(), m_model, MantidQt::MantidWidgets::Batch::RowLocation::rowRelativeToParent(), and walkFromRootToParentIndexOf().
Referenced by MantidQt::MantidWidgets::Batch::JobTreeView::applyNavigationResult(), and indexAt().
walkFromRootToParentIndexOf()
QModelIndex MantidQt::MantidWidgets::Batch::RowLocationAdapter::walkFromRootToParentIndexOf (RowLocation const & location) const private
Definition at line 26 of file RowLocationAdapter.cpp.
References m_model, and MantidQt::MantidWidgets::Batch::RowLocation::path().
Referenced by indexIfExistsAt().
Member Data Documentation
m_model
QStandardItemModel const& MantidQt::MantidWidgets::Batch::RowLocationAdapter::m_model private
Definition at line 31 of file RowLocationAdapter.h.
Referenced by indexIfExistsAt(), and walkFromRootToParentIndexOf().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/Batch/RowLocationAdapter.h
qt/widgets/common/src/Batch/RowLocationAdapter.cpp