Mantid: Mantid::NexusGeometry::NexusFileReader Class Reference
Mantid::NexusGeometry::NexusFileReader Class Reference
#include <NexusFileReader.h>
Public Member Functions
void close ()
int countNXgroup (const FullNXPath &pathToGroup, const std::string &nxClass)
bool dataSetHasStrValue (const std::string &dataSetName, const std::string &dataSetValue, const FullNXPath &pathToGroup) const
bool groupHasNxClass (const std::string &attrVal, const std::string &pathToGroup) const
bool hasAttributeInDataSet (const std::string &dataSetName, const std::string &attrName, const std::string &attrVal, const FullNXPath &pathToGroup)
bool hasAttributeInGroup (const std::string &attrName, const std::string &attrVal, const FullNXPath &pathToGroup)
bool hasDataset (const std::string &dsetName, const FullNXPath &pathToGroup)
bool hasDatasetWithAttribute (const std::string &pathToGroup, const std::string &attributeVal, const std::string &attrName)
bool hasDatasetWithNXAttribute (const std::string &pathToGroup, const std::string &nx_attributeVal)
bool hasNXAttributeInDataSet (const std::string &dataSetName, const std::string &attrVal, const FullNXPath &pathToGroup)
bool hasNXAttributeInGroup (const std::string &attrVal, const FullNXPath &pathToGroup)
NexusFileReader (const std::string &fullPath)
H5::Group openfullH5Path (const FullNXPath &pathList) const
bool parentNXgroupHasChildNXgroup (const std::string &parentNX_CLASS_TYPE, const std::string &childNX_CLASS_TYPE)
template<typename T >
std::vector< T > readDataSetMultidimensional (FullNXPath &pathToGroup, const std::string &dataSetName)
double readDoubleFromDataset (const std::string &datasetName, const FullNXPath &pathToGroup)
std::vector< double > readDoubleVectorFrom_d_Attribute (const std::string &attrName, const std::string &datasetName, const FullNXPath &pathToGroup)
~NexusFileReader ()
Private Attributes
H5::H5File m_file
bool m_open = false
Detailed Description
Definition at line 70 of file NexusFileReader.h.
Constructor & Destructor Documentation
NexusFileReader()
Mantid::NexusGeometry::NexusFileReader::NexusFileReader (const std::string & fullPath) inline
Definition at line 75 of file NexusFileReader.h.
References m_file, m_open, and tmp.
~NexusFileReader()
Mantid::NexusGeometry::NexusFileReader::~NexusFileReader () inline
Definition at line 388 of file NexusFileReader.h.
References close().
Member Function Documentation
close()
void Mantid::NexusGeometry::NexusFileReader::close () inline
Definition at line 381 of file NexusFileReader.h.
References m_file, and m_open.
Referenced by ~NexusFileReader().
countNXgroup()
int Mantid::NexusGeometry::NexusFileReader::countNXgroup (const FullNXPath & pathToGroup, const std::string & nxClass) inline
Definition at line 86 of file NexusFileReader.h.
References openfullH5Path().
dataSetHasStrValue()
bool Mantid::NexusGeometry::NexusFileReader::dataSetHasStrValue (const std::string & dataSetName, const std::string & dataSetValue, const FullNXPath & pathToGroup) const inline
Definition at line 315 of file NexusFileReader.h.
References openfullH5Path().
groupHasNxClass()
bool Mantid::NexusGeometry::NexusFileReader::groupHasNxClass (const std::string & attrVal, const std::string & pathToGroup) const inline
Definition at line 304 of file NexusFileReader.h.
References m_file.
hasAttributeInDataSet()
bool Mantid::NexusGeometry::NexusFileReader::hasAttributeInDataSet (const std::string & dataSetName, const std::string & attrName, const std::string & attrVal, const FullNXPath & pathToGroup) inline
Definition at line 356 of file NexusFileReader.h.
References openfullH5Path().
hasAttributeInGroup()
bool Mantid::NexusGeometry::NexusFileReader::hasAttributeInGroup (const std::string & attrName, const std::string & attrVal, const FullNXPath & pathToGroup) inline
Definition at line 333 of file NexusFileReader.h.
References openfullH5Path().
hasDataset()
bool Mantid::NexusGeometry::NexusFileReader::hasDataset (const std::string & dsetName, const FullNXPath & pathToGroup) inline
Definition at line 288 of file NexusFileReader.h.
References openfullH5Path().
hasDatasetWithAttribute()
bool Mantid::NexusGeometry::NexusFileReader::hasDatasetWithAttribute (const std::string & pathToGroup, const std::string & attributeVal, const std::string & attrName) inline
Definition at line 267 of file NexusFileReader.h.
References m_file.
hasDatasetWithNXAttribute()
bool Mantid::NexusGeometry::NexusFileReader::hasDatasetWithNXAttribute (const std::string & pathToGroup, const std::string & nx_attributeVal) inline
Definition at line 246 of file NexusFileReader.h.
References m_file.
hasNXAttributeInDataSet()
bool Mantid::NexusGeometry::NexusFileReader::hasNXAttributeInDataSet (const std::string & dataSetName, const std::string & attrVal, const FullNXPath & pathToGroup) inline
Definition at line 369 of file NexusFileReader.h.
References openfullH5Path().
hasNXAttributeInGroup()
bool Mantid::NexusGeometry::NexusFileReader::hasNXAttributeInGroup (const std::string & attrVal, const FullNXPath & pathToGroup) inline
Definition at line 345 of file NexusFileReader.h.
References openfullH5Path().
openfullH5Path()
H5::Group Mantid::NexusGeometry::NexusFileReader::openfullH5Path (const FullNXPath & pathList) const inline
Definition at line 136 of file NexusFileReader.h.
References m_file.
Referenced by countNXgroup(), dataSetHasStrValue(), hasAttributeInDataSet(), hasAttributeInGroup(), hasDataset(), hasNXAttributeInDataSet(), hasNXAttributeInGroup(), readDataSetMultidimensional(), readDoubleFromDataset(), and readDoubleVectorFrom_d_Attribute().
parentNXgroupHasChildNXgroup()
bool Mantid::NexusGeometry::NexusFileReader::parentNXgroupHasChildNXgroup (const std::string & parentNX_CLASS_TYPE, const std::string & childNX_CLASS_TYPE) inline
Definition at line 152 of file NexusFileReader.h.
References m_file.
readDataSetMultidimensional()
template<typename T > std::vector< T > Mantid::NexusGeometry::NexusFileReader::readDataSetMultidimensional (FullNXPath & pathToGroup, const std::string & dataSetName) inline
Definition at line 118 of file NexusFileReader.h.
References openfullH5Path().
readDoubleFromDataset()
double Mantid::NexusGeometry::NexusFileReader::readDoubleFromDataset (const std::string & datasetName, const FullNXPath & pathToGroup) inline
Definition at line 209 of file NexusFileReader.h.
References openfullH5Path(), and value.
readDoubleVectorFrom_d_Attribute()
std::vector< double > Mantid::NexusGeometry::NexusFileReader::readDoubleVectorFrom_d_Attribute (const std::string & attrName, const std::string & datasetName, const FullNXPath & pathToGroup) inline
Definition at line 225 of file NexusFileReader.h.
References openfullH5Path(), and value.
Member Data Documentation
m_file
H5::H5File Mantid::NexusGeometry::NexusFileReader::m_file private
Definition at line 391 of file NexusFileReader.h.
Referenced by close(), groupHasNxClass(), hasDatasetWithAttribute(), hasDatasetWithNXAttribute(), NexusFileReader(), openfullH5Path(), and parentNXgroupHasChildNXgroup().
m_open
bool Mantid::NexusGeometry::NexusFileReader::m_open = false private
Definition at line 72 of file NexusFileReader.h.
Referenced by close(), and NexusFileReader().
The documentation for this class was generated from the following file:
Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h