Mantid: Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp File Reference
IAlgorithm.cpp File Reference
#include "MantidAPI/IAlgorithm.h"
#include "MantidPythonInterface/api/AlgorithmIDProxy.h"
#include "MantidKernel/Strings.h"
#include "MantidPythonInterface/core/Converters/MapToPyDictionary.h"
#include "MantidPythonInterface/core/GetPointer.h"
#include "MantidPythonInterface/core/GlobalInterpreterLock.h"
#include "MantidPythonInterface/core/IsNone.h"
#include "MantidPythonInterface/core/Policies/VectorToNumpy.h"
#include "MantidPythonInterface/core/ReleaseGlobalInterpreterLock.h"
#include <Poco/ActiveResult.h>
#include <Poco/Thread.h>
#include <boost/python/arg_from_python.hpp>
#include <boost/python/bases.hpp>
#include <boost/python/class.hpp>
#include <boost/python/object.hpp>
#include <boost/python/operators.hpp>
#include <boost/python/register_ptr_to_python.hpp>
#include <unordered_map>
Functions
void export_ialgorithm ()
Function Documentation
export_ialgorithm()
void export_ialgorithm ()
Definition at line 360 of file IAlgorithm.cpp.
References Mantid::API::IAlgorithm::alias(), Mantid::API::IAlgorithm::aliasDeprecated(), Mantid::API::IAlgorithm::cancel(), Mantid::API::IAlgorithm::categories(), Mantid::API::IAlgorithm::category(), Mantid::API::IAlgorithm::enableHistoryRecordingForChild(), Mantid::API::IAlgorithm::getAlgStartupLogging(), Mantid::API::IAlgorithm::helpURL(), Mantid::API::IAlgorithm::isChild(), Mantid::API::IAlgorithm::isExecuted(), Mantid::API::IAlgorithm::isInitialized(), Mantid::API::IAlgorithm::isLogging(), Mantid::API::IAlgorithm::isRunning(), Mantid::API::IAlgorithm::name(), Mantid::API::IAlgorithm::seeAlso(), Mantid::API::IAlgorithm::setAlgStartupLogging(), Mantid::API::IAlgorithm::setAlwaysStoreInADS(), Mantid::API::IAlgorithm::setChild(), Mantid::API::IAlgorithm::setLogging(), Mantid::API::IAlgorithm::setRethrows(), Mantid::API::IAlgorithm::summary(), Mantid::API::IAlgorithm::toString(), Mantid::API::IAlgorithm::version(), Mantid::API::IAlgorithm::workspaceMethodInputProperty(), Mantid::API::IAlgorithm::workspaceMethodName(), and Mantid::API::IAlgorithm::workspaceMethodOn().