Mantid: Mantid::Kernel::MDUnit Class Reference
Mantid::Kernel::MDUnit Class Reference abstract
MDUnit : Unit type for multidimensional data types.
#include <MDUnit.h>
Public Member Functions
virtual bool canConvertTo (const MDUnit &other) const =0
virtual MDUnit * clone () const =0
virtual UnitLabel getUnitLabel () const =0
virtual bool isQUnit () const =0
bool operator== (const MDUnit &other) const
virtual ~MDUnit ()=default
Detailed Description
MDUnit : Unit type for multidimensional data types.
Not convertable to/from TOF unlike Unit.
Definition at line 20 of file MDUnit.h.
Constructor & Destructor Documentation
~MDUnit()
virtual Mantid::Kernel::MDUnit::~MDUnit () virtual default
Member Function Documentation
canConvertTo()
virtual bool Mantid::Kernel::MDUnit::canConvertTo (const MDUnit & other) const pure virtual
Implemented in Mantid::Kernel::ReciprocalLatticeUnit, Mantid::Kernel::InverseAngstromsUnit, and Mantid::Kernel::LabelUnit.
Referenced by operator==().
clone()
virtual MDUnit * Mantid::Kernel::MDUnit::clone () const pure virtual
Implemented in Mantid::Kernel::ReciprocalLatticeUnit, Mantid::Kernel::InverseAngstromsUnit, and Mantid::Kernel::LabelUnit.
Referenced by Mantid::Geometry::GeneralFrame::setMDUnit(), and Mantid::Geometry::HKL::setMDUnit().
getUnitLabel()
virtual UnitLabel Mantid::Kernel::MDUnit::getUnitLabel () const pure virtual
Implemented in Mantid::Kernel::ReciprocalLatticeUnit, Mantid::Kernel::InverseAngstromsUnit, and Mantid::Kernel::LabelUnit.
Referenced by Mantid::Kernel::LabelUnit::canConvertTo().
isQUnit()
virtual bool Mantid::Kernel::MDUnit::isQUnit () const pure virtual
Implemented in Mantid::Kernel::QUnit, and Mantid::Kernel::LabelUnit.
operator==()
bool Mantid::Kernel::MDUnit::operator== (const MDUnit & other) const
Definition at line 14 of file MDUnit.cpp.
References canConvertTo().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/MDUnit.h
Framework/Kernel/src/MDUnit.cpp