Mantid: VectorByteStream Class Reference
VectorByteStream Class Reference
#include <BitStream.h>
Public Member Functions
bool eof () const
template<typename T >
VectorByteStream & operator>> (T &val)
uint8_t peek ()
template<std::size_t bytecount, typename T >
VectorByteStream & read (T &result)
template<typename T >
T readRaw (T &&result)
template<std::size_t bytecount, typename T >
VectorByteStream & readRaw (T &result)
template<typename T >
VectorByteStream & readRaw (T &result)
template<typename T >
VectorByteStream & readRaw (T &result, const std::size_t &bytecount)
template<size_t bytecount>
VectorByteStream & skip ()
VectorByteStream (const std::vector< uint8_t > &vector)
Private Member Functions
template<typename T >
char * getResultPointer (T *const result, const std::size_t &bytecount) const
bool streameof () const
void streamignore (const std::size_t &bytecount)
unsigned streampeek () const
void streamread (char *dest, const std::size_t &bytecount)
Private Attributes
std::vector< uint8_t >::const_iterator end
std::vector< uint8_t >::const_iterator pos
Detailed Description
Definition at line 74 of file BitStream.h.
Constructor & Destructor Documentation
VectorByteStream()
VectorByteStream::VectorByteStream (const std::vector< uint8_t > & vector) inline explicit
Definition at line 76 of file BitStream.h.
Member Function Documentation
eof()
bool VectorByteStream::eof () const inline
Definition at line 125 of file BitStream.h.
References streameof().
Referenced by Mantid::DataHandling::LoadDNSEvent::parse_BlockList().
getResultPointer()
template<typename T > char * VectorByteStream::getResultPointer (T *const result, const std::size_t & bytecount) const inline private
Definition at line 82 of file BitStream.h.
Referenced by readRaw().
operator>>()
template<typename T > VectorByteStream & VectorByteStream::operator>> (T & val) inline
Definition at line 132 of file BitStream.h.
References read().
peek()
uint8_t VectorByteStream::peek () inline
Definition at line 123 of file BitStream.h.
References streampeek().
Referenced by Mantid::DataHandling::LoadDNSEvent::parse_BlockList().
read()
template<std::size_t bytecount, typename T > VectorByteStream & VectorByteStream::read (T & result) inline
Definition at line 117 of file BitStream.h.
Referenced by operator>>(), Mantid::DataHandling::LoadDNSEvent::parse_andAddEvent(), and Mantid::DataHandling::LoadDNSEvent::parse_DataBufferHeader().
readRaw() [1/4]
template<typename T > T VectorByteStream::readRaw (T && result) inline
Definition at line 112 of file BitStream.h.
readRaw() [2/4]
template<std::size_t bytecount, typename T > VectorByteStream & VectorByteStream::readRaw (T & result) inline
Definition at line 104 of file BitStream.h.
References getResultPointer(), and streamread().
readRaw() [3/4]
template<typename T > VectorByteStream & VectorByteStream::readRaw (T & result) inline
Definition at line 110 of file BitStream.h.
readRaw() [4/4]
template<typename T > VectorByteStream & VectorByteStream::readRaw (T & result, const std::size_t & bytecount) inline
Definition at line 98 of file BitStream.h.
References getResultPointer(), and streamread().
Referenced by Mantid::DataHandling::LoadDNSEvent::parse_BlockSeparator().
skip()
template<size_t bytecount> VectorByteStream & VectorByteStream::skip () inline
Definition at line 127 of file BitStream.h.
References streamignore().
Referenced by Mantid::DataHandling::LoadDNSEvent::parse_DataBufferHeader().
streameof()
bool VectorByteStream::streameof () const inline private
Definition at line 95 of file BitStream.h.
References end, and pos.
Referenced by eof().
streamignore()
void VectorByteStream::streamignore (const std::size_t & bytecount) inline private
Definition at line 91 of file BitStream.h.
References pos.
Referenced by skip().
streampeek()
unsigned VectorByteStream::streampeek () const inline private
Definition at line 93 of file BitStream.h.
References pos.
Referenced by peek().
streamread()
void VectorByteStream::streamread (char * dest, const std::size_t & bytecount) inline private
Definition at line 86 of file BitStream.h.
References pos.
Referenced by readRaw().
Member Data Documentation
end
std::vector<uint8_t>::const_iterator VectorByteStream::end private
Definition at line 80 of file BitStream.h.
Referenced by streameof().
pos
std::vector<uint8_t>::const_iterator VectorByteStream::pos private
Definition at line 79 of file BitStream.h.
Referenced by streameof(), streamignore(), streampeek(), and streamread().
The documentation for this class was generated from the following file:
Framework/DataHandling/inc/MantidDataHandling/BitStream.h