Mantid: MantidQt::MantidWidgets::MantidTreeWidgetItem Class Reference
MantidQt::MantidWidgets::MantidTreeWidgetItem Class Reference
A class derived from QTreeWidgetItem, to accomodate sorting on the items in a MantidTreeWidget.
#include <MantidTreeWidgetItem.h>
Public Member Functions
void disableIfNode (bool)
int getSortPos () const
MantidTreeWidgetItem (const QStringList &, MantidTreeWidget *)
Constructor.
MantidTreeWidgetItem (MantidTreeWidget *)
Constructor.
void setSortPos (int o)
Private Member Functions
std::size_t getMemorySize () const
bool operator< (const QTreeWidgetItem &other) const override
Overidden operator.
Static Private Member Functions
static Mantid::Types::Core::DateAndTime getLastModified (const QTreeWidgetItem *)
Finds the date and time of the last modification made to the workspace who's details are found in the given QTreeWidgetItem.
Private Attributes
MantidTreeWidget * m_parent
int m_sortPos
Detailed Description
A class derived from QTreeWidgetItem, to accomodate sorting on the items in a MantidTreeWidget.
Definition at line 22 of file MantidTreeWidgetItem.h.
Constructor & Destructor Documentation
MantidTreeWidgetItem() [1/2]
MantidQt::MantidWidgets::MantidTreeWidgetItem::MantidTreeWidgetItem (MantidTreeWidget * parent) explicit
Constructor.
Must be passed its parent MantidTreeWidget, to facilitate correct sorting.
Definition at line 21 of file MantidTreeWidgetItem.cpp.
MantidTreeWidgetItem() [2/2]
MantidQt::MantidWidgets::MantidTreeWidgetItem::MantidTreeWidgetItem (const QStringList & list, MantidTreeWidget * parent)
Constructor.
Must be passed its parent MantidTreeWidget, to facilitate correct sorting.
Definition at line 27 of file MantidTreeWidgetItem.cpp.
Member Function Documentation
disableIfNode()
void MantidQt::MantidWidgets::MantidTreeWidgetItem::disableIfNode (bool)
getLastModified()
DateAndTime MantidQt::MantidWidgets::MantidTreeWidgetItem::getLastModified (const QTreeWidgetItem * item) static private
Finds the date and time of the last modification made to the workspace who's details are found in the given QTreeWidgetItem.
Definition at line 97 of file MantidTreeWidgetItem.cpp.
References Mantid::API::WorkspaceHistory::size(), and workspace.
Referenced by operator<().
getMemorySize()
std::size_t MantidQt::MantidWidgets::MantidTreeWidgetItem::getMemorySize () const private
Definition at line 111 of file MantidTreeWidgetItem.cpp.
References getMemorySize().
Referenced by getMemorySize(), and operator<().
getSortPos()
int MantidQt::MantidWidgets::MantidTreeWidgetItem::getSortPos () const inline
Definition at line 28 of file MantidTreeWidgetItem.h.
Referenced by operator<().
operator<()
bool MantidQt::MantidWidgets::MantidTreeWidgetItem::operator< (const QTreeWidgetItem & other) const override private
Overidden operator.
Must be passed its parent MantidTreeWidget, to facilitate correct sorting.
Definition at line 33 of file MantidTreeWidgetItem.cpp.
References MantidQt::MantidWidgets::ByMemorySize, MantidQt::MantidWidgets::ByName, getLastModified(), getMemorySize(), MantidQt::MantidWidgets::MantidTreeWidget::getSortOrder(), getSortPos(), MantidQt::MantidWidgets::MantidTreeWidget::getSortScheme(), MantidQt::MantidWidgets::MantidTreeWidget::logWarningMessage(), m_parent, and m_sortPos.
setSortPos()
void MantidQt::MantidWidgets::MantidTreeWidgetItem::setSortPos (int o) inline
Definition at line 27 of file MantidTreeWidgetItem.h.
Referenced by MantidQt::MantidWidgets::WorkspaceTreeWidget::excludeItemFromSort().
Member Data Documentation
m_parent
MantidTreeWidget* MantidQt::MantidWidgets::MantidTreeWidgetItem::m_parent private
Definition at line 32 of file MantidTreeWidgetItem.h.
Referenced by operator<().
m_sortPos
int MantidQt::MantidWidgets::MantidTreeWidgetItem::m_sortPos private
Definition at line 35 of file MantidTreeWidgetItem.h.
Referenced by operator<().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/MantidTreeWidgetItem.h
qt/widgets/common/src/MantidTreeWidgetItem.cpp