Mantid: Mantid::WorkflowAlgorithms::HFIRInstrument Namespace Reference
Mantid::WorkflowAlgorithms::HFIRInstrument Namespace Reference
Functions
void getCoordinateFromPixel (const double &pixel_x, const double &pixel_y, const API::MatrixWorkspace_sptr &dataWS, double &x, double &y)
void getDefaultBeamCenter (const API::MatrixWorkspace_sptr &dataWS, double &pixel_x, double &pixel_y)
int getDetectorFromPixel (const int &pixel_x, const int &pixel_y, const API::MatrixWorkspace_sptr &dataWS)
void getPixelFromCoordinate (const double &x, const double &y, const API::MatrixWorkspace_sptr &dataWS, double &pixel_x, double &pixel_y)
double getSourceToSampleDistance (const API::MatrixWorkspace_sptr &dataWS)
double readInstrumentParameter (const std::string &parameter, const API::MatrixWorkspace_sptr &dataWS)
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Function Documentation
getCoordinateFromPixel()
void Mantid::WorkflowAlgorithms::HFIRInstrument::getCoordinateFromPixel (const double & pixel_x, const double & pixel_y, const API::MatrixWorkspace_sptr & dataWS, double & x, double & y)
Definition at line 55 of file HFIRInstrument.cpp.
References readInstrumentParameter(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter().
getDefaultBeamCenter()
void Mantid::WorkflowAlgorithms::HFIRInstrument::getDefaultBeamCenter (const API::MatrixWorkspace_sptr & dataWS, double & pixel_x, double & pixel_y)
Definition at line 87 of file HFIRInstrument.cpp.
References getPixelFromCoordinate().
Referenced by Mantid::WorkflowAlgorithms::HFIRLoad::exec(), and Mantid::WorkflowAlgorithms::HFIRLoad::moveToBeamCenter().
getDetectorFromPixel()
int Mantid::WorkflowAlgorithms::HFIRInstrument::getDetectorFromPixel (const int & pixel_x, const int & pixel_y, const API::MatrixWorkspace_sptr & dataWS)
Definition at line 46 of file HFIRInstrument.cpp.
References UNUSED_ARG.
getPixelFromCoordinate()
void Mantid::WorkflowAlgorithms::HFIRInstrument::getPixelFromCoordinate (const double & x, const double & y, const API::MatrixWorkspace_sptr & dataWS, double & pixel_x, double & pixel_y)
Definition at line 73 of file HFIRInstrument.cpp.
References readInstrumentParameter(), Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by Mantid::WorkflowAlgorithms::SANSBeamFinder::exec(), and getDefaultBeamCenter().
getSourceToSampleDistance()
double Mantid::WorkflowAlgorithms::HFIRInstrument::getSourceToSampleDistance (const API::MatrixWorkspace_sptr & dataWS)
Definition at line 98 of file HFIRInstrument.cpp.
Referenced by Mantid::WorkflowAlgorithms::HFIRLoad::exec().
readInstrumentParameter()
double Mantid::WorkflowAlgorithms::HFIRInstrument::readInstrumentParameter (const std::string & parameter, const API::MatrixWorkspace_sptr & dataWS)
File change history is stored at: https://github.com/mantidproject/mantid Code Documentation is available at: http://doxygen.mantidproject.org
Definition at line 36 of file HFIRInstrument.cpp.
Referenced by getCoordinateFromPixel(), and getPixelFromCoordinate().