Mantid: Framework/Nexus/inc/MantidNexus/UniqueID.h File Reference
UniqueID.h File Reference
#include "MantidNexus/DllConfig.h"
#include "MantidNexus/NexusFile_fwd.h"
Classes
class Mantid::Nexus::UniqueID< D >
A wrapper class for managing HDF5 object handles (hid_t).
Namespaces
namespace Mantid
Helper class which provides the Collimation Length for SANS instruments.
namespace Mantid::Nexus
Header for a base Nexus::Exception.
Macros
#define MYH5DLL
Functions
MYH5DLL herr_t H5Fclose (hid_t)
MYH5DLL herr_t H5garbage_collect ()
MYH5DLL herr_t H5Iis_valid (hid_t)
Macro Definition Documentation
MYH5DLL
#define MYH5DLL
Definition at line 12 of file UniqueID.h.
Function Documentation
H5Fclose()
MYH5DLL herr_t H5Fclose (hid_t)
Referenced by Mantid::Nexus::UniqueID< D >::close().
H5garbage_collect()
MYH5DLL herr_t H5garbage_collect ()
Referenced by Mantid::Nexus::UniqueID< D >::close().
H5Iis_valid()
MYH5DLL herr_t H5Iis_valid (hid_t)
Referenced by Mantid::Nexus::UniqueID< D >::isValid().