Mantid: Mantid::API::AlgorithmProperties Namespace Reference
Mantid::API::AlgorithmProperties Namespace Reference
Functions
std::string boolToString (bool value)
std::string getOutputWorkspace (const IAlgorithm_sptr &algorithm, std::string const &property)
std::string MANTID_API_DLL getOutputWorkspace (const Mantid::API::IAlgorithm_sptr &algorithm, std::string const &property)
void MANTID_API_DLL update (std::string const &property, bool value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, double value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, IFunction_sptr const &function, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, int value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, MatrixWorkspace_sptr const &workspace, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, size_t value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, std::optional< double > const &value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, std::optional< std::string > const &value, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL update (std::string const &property, std::string const &value, IAlgorithmRuntimeProps &properties)
template<typename VALUE_TYPE >
void update (std::string const &property, std::vector< VALUE_TYPE > const &values, Mantid::API::IAlgorithmRuntimeProps &properties, bool const convertToString=true)
void MANTID_API_DLL update (std::string const &property, Workspace_sptr const &workspace, IAlgorithmRuntimeProps &properties)
void MANTID_API_DLL updateFromMap (IAlgorithmRuntimeProps &properties, std::map< std::string, std::string > const &parameterMap)
Function Documentation
boolToString()
std::string Mantid::API::AlgorithmProperties::boolToString (bool value)
Definition at line 16 of file AlgorithmProperties.cpp.
References value.
getOutputWorkspace() [1/2]
std::string Mantid::API::AlgorithmProperties::getOutputWorkspace (const IAlgorithm_sptr & algorithm, std::string const & property)
Definition at line 66 of file AlgorithmProperties.cpp.
getOutputWorkspace() [2/2]
std::string MANTID_API_DLL Mantid::API::AlgorithmProperties::getOutputWorkspace (const Mantid::API::IAlgorithm_sptr & algorithm, std::string const & property)
update() [1/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, bool value, IAlgorithmRuntimeProps & properties)
Definition at line 28 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and value.
update() [2/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, double value, IAlgorithmRuntimeProps & properties)
Definition at line 40 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and value.
update() [3/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, IFunction_sptr const & function, IAlgorithmRuntimeProps & properties)
Definition at line 57 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty().
update() [4/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, int value, IAlgorithmRuntimeProps & properties)
Definition at line 32 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and value.
update() [5/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, MatrixWorkspace_sptr const & workspace, IAlgorithmRuntimeProps & properties)
Definition at line 53 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and workspace.
update() [6/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, size_t value, IAlgorithmRuntimeProps & properties)
Definition at line 36 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and value.
update() [7/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, std::optional< double > const & value, IAlgorithmRuntimeProps & properties)
Definition at line 44 of file AlgorithmProperties.cpp.
References update(), and value.
update() [8/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, std::optional< std::string > const & value, IAlgorithmRuntimeProps & properties)
Definition at line 23 of file AlgorithmProperties.cpp.
References update(), and value.
update() [9/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, std::string const & value, IAlgorithmRuntimeProps & properties)
Definition at line 18 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setPropertyValue(), and value.
Referenced by MantidQt::MantidWidgets::AddWorkspaceMultiDialog::setLoadProperty(), MantidQt::MantidWidgets::DataSelector::setLoadProperty(), update(), update(), update(), and updateFromMap().
update() [10/11]
template<typename VALUE_TYPE > void Mantid::API::AlgorithmProperties::update (std::string const & property, std::vector< VALUE_TYPE > const & values, Mantid::API::IAlgorithmRuntimeProps & properties, bool const convertToString = true)
Definition at line 58 of file AlgorithmProperties.h.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), Mantid::Kernel::Strings::simpleJoin(), update(), and value.
update() [11/11]
void Mantid::API::AlgorithmProperties::update (std::string const & property, Workspace_sptr const & workspace, IAlgorithmRuntimeProps & properties)
Definition at line 49 of file AlgorithmProperties.cpp.
References Mantid::API::IAlgorithmRuntimeProps::setProperty(), and workspace.
updateFromMap()
void Mantid::API::AlgorithmProperties::updateFromMap (IAlgorithmRuntimeProps & properties, std::map< std::string, std::string > const & parameterMap)
Definition at line 61 of file AlgorithmProperties.cpp.
References update().