Mantid: Mantid::API::ImplicitFunctionParserFactoryImpl Class Reference
Mantid::API::ImplicitFunctionParserFactoryImpl Class Reference
#include <ImplicitFunctionParserFactory.h>
Public Member Functions
std::shared_ptr< ImplicitFunctionParser > create (const std::string &xmlString) const override
Creates a new instance of the class with the given name.
ImplicitFunctionParser * createImplicitFunctionParserFromXML (const std::string &functionXML) const
ImplicitFunctionParser * createImplicitFunctionParserFromXML (Poco::XML::Element *functionElement) const
ImplicitFunctionParserFactoryImpl (const ImplicitFunctionParserFactoryImpl &)=delete
ImplicitFunctionParserFactoryImpl & operator= (const ImplicitFunctionParserFactoryImpl &)=delete
Public Member Functions inherited from Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >
virtual std::shared_ptr< ImplicitFunctionParser > create (const std::string &className) const
Creates a new instance of the class with the given name.
virtual ImplicitFunctionParser * createUnwrapped (const std::string &className) const
Creates a new instance of the class with the given name, which is not wrapped in a boost shared_ptr.
void disableNotifications ()
Disable notifications.
DynamicFactory (const DynamicFactory &)=delete
void enableNotifications ()
Enable notifications.
bool exists (const std::string &className) const
Returns true if the given class is currently registered.
virtual const std::vector< std::string > getKeys () const
Returns the keys in the map.
DynamicFactory & operator= (const DynamicFactory &)=delete
void subscribe (const std::string &className)
Registers the instantiator for the given class with the DynamicFactory.
void subscribe (const std::string &className, std::unique_ptr< AbstractFactory > pAbstractFactory, SubscribeAction replace=ErrorIfExists)
Registers the instantiator for the given class with the DynamicFactory.
void unsubscribe (const std::string &className)
Unregisters the given class and deletes the instantiator for the class.
virtual ~DynamicFactory ()=default
Destroys the DynamicFactory and deletes the instantiators for all registered classes.
Private Member Functions
ImplicitFunctionParserFactoryImpl ()=default
Private Constructor for singleton class.
~ImplicitFunctionParserFactoryImpl () override=default
Private Destructor.
Friends
struct Mantid::Kernel::CreateUsingNew< ImplicitFunctionParserFactoryImpl >
Additional Inherited Members
Public Types inherited from Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >
using AbstractFactory = AbstractInstantiator< ImplicitFunctionParser >
A typedef for the instantiator.
enum NotificationStatus
Defines the whether notifications are dispatched.
enum SubscribeAction
Defines replacement behaviour.
Public Attributes inherited from Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >
Poco::NotificationCenter notificationCenter
Sends notifications to observers.
Protected Member Functions inherited from Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >
DynamicFactory ()
Protected constructor for base class.
Detailed Description
Definition at line 27 of file ImplicitFunctionParserFactory.h.
Constructor & Destructor Documentation
ImplicitFunctionParserFactoryImpl() [1/2]
Mantid::API::ImplicitFunctionParserFactoryImpl::ImplicitFunctionParserFactoryImpl (const ImplicitFunctionParserFactoryImpl &) delete
ImplicitFunctionParserFactoryImpl() [2/2]
Mantid::API::ImplicitFunctionParserFactoryImpl::ImplicitFunctionParserFactoryImpl () private default
Private Constructor for singleton class.
~ImplicitFunctionParserFactoryImpl()
Mantid::API::ImplicitFunctionParserFactoryImpl::~ImplicitFunctionParserFactoryImpl () override private default
Private Destructor.
Member Function Documentation
create()
std::shared_ptr< ImplicitFunctionParser > Mantid::API::ImplicitFunctionParserFactoryImpl::create (const std::string & className) const override virtual
Creates a new instance of the class with the given name.
The class must have been registered with subscribe() (typically done via a macro). If the class name is unknown, a NotFoundException is thrown.
Parameters
className :: the name of the class you wish to create
Returns
a shared pointer ot the base class
Reimplemented from Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >.
Definition at line 16 of file ImplicitFunctionParserFactory.cpp.
References UNUSED_ARG.
createImplicitFunctionParserFromXML() [1/2]
ImplicitFunctionParser * Mantid::API::ImplicitFunctionParserFactoryImpl::createImplicitFunctionParserFromXML (const std::string & functionXML) const
Definition at line 64 of file ImplicitFunctionParserFactory.cpp.
References createImplicitFunctionParserFromXML().
Referenced by createImplicitFunctionParserFromXML().
createImplicitFunctionParserFromXML() [2/2]
ImplicitFunctionParser * Mantid::API::ImplicitFunctionParserFactoryImpl::createImplicitFunctionParserFromXML (Poco::XML::Element * functionElement) const
Definition at line 23 of file ImplicitFunctionParserFactory.cpp.
References createImplicitFunctionParserFromXML(), Mantid::Kernel::DynamicFactory< ImplicitFunctionParser >::createUnwrapped(), Mantid::Kernel::SingletonHolder< T >::Instance(), Mantid::API::ImplicitFunctionParser::setParameterParser(), and Mantid::API::ImplicitFunctionParser::setSuccessorParser().
operator=()
ImplicitFunctionParserFactoryImpl & Mantid::API::ImplicitFunctionParserFactoryImpl::operator= (const ImplicitFunctionParserFactoryImpl &) delete
References Mantid::DataObjects::create().
Friends And Related Function Documentation
Mantid::Kernel::CreateUsingNew< ImplicitFunctionParserFactoryImpl >
friend struct Mantid::Kernel::CreateUsingNew< ImplicitFunctionParserFactoryImpl > friend
Definition at line 34 of file ImplicitFunctionParserFactory.h.
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/ImplicitFunctionParserFactory.h
Framework/API/src/ImplicitFunctionParserFactory.cpp