Mantid: ICat4::ns1__entityBaseBean Class Reference
ICat4::ns1__entityBaseBean Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__entityBaseBean ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
std::string * createId
time_t * createTime
LONG64 * id
std::string * modId
time_t * modTime
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 408 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__entityBaseBean()
ICat4::ns1__entityBaseBean::ns1__entityBaseBean () inline
Definition at line 423 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__entityBaseBean::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22089 of file ICat4C.cpp.
References createId, createTime, id, modId, modTime, ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::ns1__datafile::soap_default(), ICat4::ns1__dataCollectionDatafile::soap_default(), ICat4::ns1__dataCollection::soap_default(), ICat4::ns1__dataCollectionDataset::soap_default(), ICat4::ns1__dataset::soap_default(), ICat4::ns1__investigation::soap_default(), ICat4::ns1__facility::soap_default(), ICat4::ns1__application::soap_default(), ICat4::ns1__job::soap_default(), ICat4::ns1__datafileFormat::soap_default(), ICat4::ns1__datasetType::soap_default(), ICat4::ns1__facilityCycle::soap_default(), ICat4::ns1__instrument::soap_default(), ICat4::ns1__instrumentScientist::soap_default(), ICat4::ns1__user::soap_default(), ICat4::ns1__investigationUser::soap_default(), ICat4::ns1__study::soap_default(), ICat4::ns1__studyInvestigation::soap_default(), ICat4::ns1__userGroup::soap_default(), ICat4::ns1__grouping::soap_default(), ICat4::ns1__rule::soap_default(), ICat4::ns1__investigationInstrument::soap_default(), ICat4::ns1__investigationType::soap_default(), ICat4::ns1__parameterType::soap_default(), ICat4::ns1__parameter::soap_default(), ICat4::ns1__permissibleStringValue::soap_default(), ICat4::ns1__sample::soap_default(), ICat4::ns1__sampleType::soap_default(), ICat4::ns1__keyword::soap_default(), ICat4::ns1__publication::soap_default(), ICat4::ns1__shift::soap_default(), ICat4::ns1__relatedDatafile::soap_default(), ICat4::ns1__log::soap_default(), ICat4::ns1__publicStep::soap_default(), ICat4::ns1__dataCollectionParameter::soap_default(), ICat4::ns1__datafileParameter::soap_default(), ICat4::ns1__datasetParameter::soap_default(), ICat4::ns1__investigationParameter::soap_default(), ICat4::ns1__sampleParameter::soap_default(), ICat4::soap_in_ns1__entityBaseBean(), ICat4::soap_new_req_ns1__entityBaseBean(), and ICat4::soap_new_set_ns1__entityBaseBean().
soap_get()
void * ICat4::ns1__entityBaseBean::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22220 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__entityBaseBean().
soap_in()
void * ICat4::ns1__entityBaseBean::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22134 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__entityBaseBean().
Referenced by ICat4::soap_in_ns1__entityBaseBean().
soap_out()
int ICat4::ns1__entityBaseBean::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22111 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__entityBaseBean().
Referenced by soap_put().
soap_put()
int ICat4::ns1__entityBaseBean::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22213 of file ICat4C.cpp.
References id, ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__entityBaseBean.
soap_serialize()
void ICat4::ns1__entityBaseBean::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 22099 of file ICat4C.cpp.
References createId, createTime, id, modId, modTime, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), ICat4::soap_serialize_PointerToLONG64(), ICat4::soap_serialize_PointerTostd__string(), and ICat4::soap_serialize_PointerTotime().
Referenced by ICat4::ns1__datafile::soap_serialize(), ICat4::ns1__dataCollectionDatafile::soap_serialize(), ICat4::ns1__dataCollection::soap_serialize(), ICat4::ns1__dataCollectionDataset::soap_serialize(), ICat4::ns1__dataset::soap_serialize(), ICat4::ns1__investigation::soap_serialize(), ICat4::ns1__facility::soap_serialize(), ICat4::ns1__application::soap_serialize(), ICat4::ns1__job::soap_serialize(), ICat4::ns1__datafileFormat::soap_serialize(), ICat4::ns1__datasetType::soap_serialize(), ICat4::ns1__facilityCycle::soap_serialize(), ICat4::ns1__instrument::soap_serialize(), ICat4::ns1__instrumentScientist::soap_serialize(), ICat4::ns1__user::soap_serialize(), ICat4::ns1__investigationUser::soap_serialize(), ICat4::ns1__study::soap_serialize(), ICat4::ns1__studyInvestigation::soap_serialize(), ICat4::ns1__userGroup::soap_serialize(), ICat4::ns1__grouping::soap_serialize(), ICat4::ns1__rule::soap_serialize(), ICat4::ns1__investigationInstrument::soap_serialize(), ICat4::ns1__investigationType::soap_serialize(), ICat4::ns1__parameterType::soap_serialize(), ICat4::ns1__parameter::soap_serialize(), ICat4::ns1__permissibleStringValue::soap_serialize(), ICat4::ns1__sample::soap_serialize(), ICat4::ns1__sampleType::soap_serialize(), ICat4::ns1__keyword::soap_serialize(), ICat4::ns1__publication::soap_serialize(), ICat4::ns1__shift::soap_serialize(), ICat4::ns1__relatedDatafile::soap_serialize(), ICat4::ns1__log::soap_serialize(), ICat4::ns1__publicStep::soap_serialize(), ICat4::ns1__dataCollectionParameter::soap_serialize(), ICat4::ns1__datafileParameter::soap_serialize(), ICat4::ns1__datasetParameter::soap_serialize(), ICat4::ns1__investigationParameter::soap_serialize(), and ICat4::ns1__sampleParameter::soap_serialize().
soap_type()
int ICat4::ns1__entityBaseBean::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Reimplemented in ICat4::ns1__investigation, ICat4::ns1__facility, ICat4::ns1__job, ICat4::ns1__facilityCycle, ICat4::ns1__instrument, ICat4::ns1__instrumentScientist, ICat4::ns1__user, ICat4::ns1__investigationUser, ICat4::ns1__study, ICat4::ns1__studyInvestigation, ICat4::ns1__userGroup, ICat4::ns1__grouping, ICat4::ns1__rule, ICat4::ns1__investigationInstrument, ICat4::ns1__investigationType, ICat4::ns1__parameterType, ICat4::ns1__parameter, ICat4::ns1__permissibleStringValue, ICat4::ns1__sample, ICat4::ns1__sampleType, ICat4::ns1__keyword, ICat4::ns1__publication, ICat4::ns1__shift, ICat4::ns1__relatedDatafile, ICat4::ns1__log, ICat4::ns1__publicStep, ICat4::ns1__investigationParameter, and ICat4::ns1__sampleParameter.
Definition at line 416 of file ICat4Stub.h.
Member Data Documentation
createId
std::string* ICat4::ns1__entityBaseBean::createId
Definition at line 410 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
createTime
time_t* ICat4::ns1__entityBaseBean::createTime
Definition at line 411 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
id
LONG64* ICat4::ns1__entityBaseBean::id
Definition at line 413 of file ICat4Stub.h.
Referenced by Mantid::ICat::ICat4Catalog::getPublishInvestigations(), soap_default(), soap_put(), ICat4::ns1__datafile::soap_put(), ICat4::ns1__dataCollectionDatafile::soap_put(), ICat4::ns1__dataCollection::soap_put(), ICat4::ns1__dataCollectionDataset::soap_put(), ICat4::ns1__dataset::soap_put(), ICat4::ns1__investigation::soap_put(), ICat4::ns1__facility::soap_put(), ICat4::ns1__application::soap_put(), ICat4::ns1__job::soap_put(), ICat4::ns1__datafileFormat::soap_put(), ICat4::ns1__datasetType::soap_put(), ICat4::ns1__facilityCycle::soap_put(), ICat4::ns1__instrument::soap_put(), ICat4::ns1__instrumentScientist::soap_put(), ICat4::ns1__user::soap_put(), ICat4::ns1__investigationUser::soap_put(), ICat4::ns1__study::soap_put(), ICat4::ns1__studyInvestigation::soap_put(), ICat4::ns1__userGroup::soap_put(), ICat4::ns1__grouping::soap_put(), ICat4::ns1__rule::soap_put(), ICat4::ns1__investigationInstrument::soap_put(), ICat4::ns1__investigationType::soap_put(), ICat4::ns1__parameterType::soap_put(), ICat4::ns1__parameter::soap_put(), ICat4::ns1__permissibleStringValue::soap_put(), ICat4::ns1__sample::soap_put(), ICat4::ns1__sampleType::soap_put(), ICat4::ns1__keyword::soap_put(), ICat4::ns1__publication::soap_put(), ICat4::ns1__shift::soap_put(), ICat4::ns1__relatedDatafile::soap_put(), ICat4::ns1__log::soap_put(), ICat4::ns1__publicStep::soap_put(), ICat4::ns1__dataCollectionParameter::soap_put(), ICat4::ns1__datafileParameter::soap_put(), ICat4::ns1__datasetParameter::soap_put(), ICat4::ns1__investigationParameter::soap_put(), ICat4::ns1__sampleParameter::soap_put(), and soap_serialize().
modId
std::string* ICat4::ns1__entityBaseBean::modId
Definition at line 414 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
modTime
time_t* ICat4::ns1__entityBaseBean::modTime
Definition at line 412 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp