Mantid: MantidQt::MantidWidgets::CatalogSelector Class Reference
MantidQt::MantidWidgets::CatalogSelector Class Reference
#include <CatalogSelector.h>
Public Member Functions
CatalogSelector (QWidget *parent=nullptr)
Default constructor.
std::vector< std::string > getSelectedCatalogSessions ()
Obtain the session information for the facilities selected.
void populateFacilitySelection ()
Populate the ListWidget with the facilities of the catalogs the user is logged in to.
Protected Attributes
Ui::CatalogSelector m_uiForm
The form generated by QT Designer.
Private Slots
void checkSelectedFacility (QListWidgetItem *item)
Checks the checkbox of the list item selected.
Private Member Functions
virtual void initLayout ()
Initialise the layout.
Detailed Description
Definition at line 14 of file CatalogSelector.h.
Constructor & Destructor Documentation
CatalogSelector()
MantidQt::MantidWidgets::CatalogSelector::CatalogSelector (QWidget * parent = nullptr)
Default constructor.
Constructor.
Definition at line 17 of file CatalogSelector.cpp.
References initLayout().
Member Function Documentation
checkSelectedFacility
void MantidQt::MantidWidgets::CatalogSelector::checkSelectedFacility (QListWidgetItem * item) private slot
Checks the checkbox of the list item selected.
SLOT: Checks the checkbox of the list item selected.
Definition at line 84 of file CatalogSelector.cpp.
Referenced by initLayout().
getSelectedCatalogSessions()
std::vector< std::string > MantidQt::MantidWidgets::CatalogSelector::getSelectedCatalogSessions ()
Obtain the session information for the facilities selected.
Returns
A vector holding the sessions ids of the selected facilities to search.
Definition at line 24 of file CatalogSelector.cpp.
References m_uiForm.
Referenced by MantidQt::MantidWidgets::CatalogSearch::populateInstrumentBox(), MantidQt::MantidWidgets::CatalogSearch::populateInvestigationTypeBox(), and MantidQt::MantidWidgets::CatalogSearch::searchClicked().
initLayout()
void MantidQt::MantidWidgets::CatalogSelector::initLayout () private virtual
Initialise the layout.
Initialise the default layout.
Definition at line 64 of file CatalogSelector.cpp.
References checkSelectedFacility(), m_uiForm, and populateFacilitySelection().
Referenced by CatalogSelector().
populateFacilitySelection()
void MantidQt::MantidWidgets::CatalogSelector::populateFacilitySelection ()
Populate the ListWidget with the facilities of the catalogs the user is logged in to.
Definition at line 38 of file CatalogSelector.cpp.
References m_uiForm.
Referenced by initLayout(), MantidQt::MantidWidgets::CatalogSearch::openFacilitySelection(), and MantidQt::MantidWidgets::CatalogSearch::searchClicked().
Member Data Documentation
m_uiForm
Ui::CatalogSelector MantidQt::MantidWidgets::CatalogSelector::m_uiForm protected
The form generated by QT Designer.
Definition at line 36 of file CatalogSelector.h.
Referenced by getSelectedCatalogSessions(), initLayout(), and populateFacilitySelection().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/CatalogSelector.h
qt/widgets/common/src/CatalogSelector.cpp