Mantid: Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator Struct Reference
Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator Struct Reference abstract
Returns the angle between the sample-to-pixel vector and its projection on the X-Z (vertical tube) or Y-Z (horizontal tube) plane.
Public Member Functions
AlphaAngleCalculator (const DetectorInfo &detectorInfo)
double getAlpha (size_t index) const
virtual void project (V3D &v) const =0
virtual ~AlphaAngleCalculator ()=default
Private Attributes
const DetectorInfo & m_detectorInfo
const V3D m_samplePos
Detailed Description
Returns the angle between the sample-to-pixel vector and its projection on the X-Z (vertical tube) or Y-Z (horizontal tube) plane.
Note, in all cases Y is assumed to be the pointing-up direction, Z is the beam direction.
Definition at line 52 of file SolidAngle.cpp.
Constructor & Destructor Documentation
AlphaAngleCalculator()
Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::AlphaAngleCalculator (const DetectorInfo & detectorInfo) inline
Definition at line 53 of file SolidAngle.cpp.
~AlphaAngleCalculator()
virtual Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::~AlphaAngleCalculator () virtual default
Member Function Documentation
getAlpha()
double Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::getAlpha (size_t index) const inline
Definition at line 55 of file SolidAngle.cpp.
References index, m_detectorInfo, m_samplePos, Mantid::Geometry::DetectorInfo::position(), and project().
project()
virtual void Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::project (V3D & v) const pure virtual
Implemented in Mantid::Algorithms::SolidAngleHelpers::AlphaAngleVertical, and Mantid::Algorithms::SolidAngleHelpers::AlphaAngleHorizontal.
Referenced by getAlpha().
Member Data Documentation
m_detectorInfo
const DetectorInfo& Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::m_detectorInfo private
Definition at line 65 of file SolidAngle.cpp.
Referenced by getAlpha().
m_samplePos
const V3D Mantid::Algorithms::SolidAngleHelpers::AlphaAngleCalculator::m_samplePos private
Definition at line 66 of file SolidAngle.cpp.
Referenced by getAlpha().
The documentation for this struct was generated from the following file:
Framework/Algorithms/src/SolidAngle.cpp