Mantid: Mantid::Kernel::ICatalogInfo Class Reference
Mantid::Kernel::ICatalogInfo Class Reference abstract
ICatalogInfo : An abstract class that holds information about catalogs.
#include <ICatalogInfo.h>
Public Member Functions
virtual const std::string catalogName () const =0
Obtain catalog name from the facility file.
virtual const std::string catalogPrefix () const =0
Obtain the regex prefix from the facility file.
virtual ICatalogInfo * clone () const =0
Clone.
virtual const std::string externalDownloadURL () const =0
Obtain the external download URL.
virtual const std::string linuxPrefix () const =0
Obtain Linux prefix from facility file.
virtual const std::string macPrefix () const =0
Obtain Macintosh prefix from facility file.
virtual const std::string soapEndPoint () const =0
Obtain soap end point from the facility file.
virtual std::string transformArchivePath (const std::string &path) const
Transform's the archive path based on operating system used.
virtual const std::string windowsPrefix () const =0
Obtain Windows prefix from the facility file.
virtual ~ICatalogInfo ()=default
virtual destructor
Private Member Functions
std::string replaceAllOccurences (const std::string &path, const std::string &search, const std::string &format) const
Replace all occurrences of the search string in the input with the format string.
std::string replacePrefix (const std::string &path, const std::string &regex, const std::string &prefix) const
Replace the content of a string using regex.
Detailed Description
ICatalogInfo : An abstract class that holds information about catalogs.
Definition at line 17 of file ICatalogInfo.h.
Constructor & Destructor Documentation
~ICatalogInfo()
virtual Mantid::Kernel::ICatalogInfo::~ICatalogInfo () virtual default
virtual destructor
Member Function Documentation
catalogName()
virtual const std::string Mantid::Kernel::ICatalogInfo::catalogName () const pure virtual
Obtain catalog name from the facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
catalogPrefix()
virtual const std::string Mantid::Kernel::ICatalogInfo::catalogPrefix () const pure virtual
Obtain the regex prefix from the facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
Referenced by transformArchivePath().
clone()
virtual ICatalogInfo * Mantid::Kernel::ICatalogInfo::clone () const pure virtual
Clone.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
externalDownloadURL()
virtual const std::string Mantid::Kernel::ICatalogInfo::externalDownloadURL () const pure virtual
Obtain the external download URL.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
linuxPrefix()
virtual const std::string Mantid::Kernel::ICatalogInfo::linuxPrefix () const pure virtual
Obtain Linux prefix from facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
Referenced by transformArchivePath().
macPrefix()
virtual const std::string Mantid::Kernel::ICatalogInfo::macPrefix () const pure virtual
Obtain Macintosh prefix from facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
Referenced by transformArchivePath().
replaceAllOccurences()
std::string Mantid::Kernel::ICatalogInfo::replaceAllOccurences (const std::string & path, const std::string & search, const std::string & format) const private
Replace all occurrences of the search string in the input with the format string.
Parameters
path :: An string to search and replace on.
search :: A substring to be searched for.
format :: A substitute string.
Returns
A string containing the replacement.
Definition at line 55 of file ICatalogInfo.cpp.
Referenced by transformArchivePath().
replacePrefix()
std::string Mantid::Kernel::ICatalogInfo::replacePrefix (const std::string & path, const std::string & regex, const std::string & prefix) const private
Replace the content of a string using regex.
Parameters
path :: An string to search and replace on.
regex :: The regex to search for.
prefix :: Replace result of regex with this prefix.
Returns
A string containing the replacement.
Definition at line 40 of file ICatalogInfo.cpp.
Referenced by transformArchivePath().
soapEndPoint()
virtual const std::string Mantid::Kernel::ICatalogInfo::soapEndPoint () const pure virtual
Obtain soap end point from the facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
transformArchivePath()
std::string Mantid::Kernel::ICatalogInfo::transformArchivePath (const std::string & path) const virtual
Transform's the archive path based on operating system used.
Definition at line 13 of file ICatalogInfo.cpp.
References catalogPrefix(), linuxPrefix(), macPrefix(), replaceAllOccurences(), replacePrefix(), and windowsPrefix().
Referenced by MantidQt::MantidWidgets::CatalogSearch::disableDownloadButtonIfArchives(), and Mantid::ICat::CatalogDownloadDataFiles::exec().
windowsPrefix()
virtual const std::string Mantid::Kernel::ICatalogInfo::windowsPrefix () const pure virtual
Obtain Windows prefix from the facility file.
Implemented in Mantid::Kernel::CatalogInfo, and Mantid::Kernel::UserCatalogInfo.
Referenced by transformArchivePath().
The documentation for this class was generated from the following files:
Framework/Kernel/inc/MantidKernel/ICatalogInfo.h
Framework/Kernel/src/ICatalogInfo.cpp