Mantid: MantidQt::MantidWidgets::ProjectSavePresenter Class Reference
MantidQt::MantidWidgets::ProjectSavePresenter Class Reference
Implements a presenter for the project saving dialog.
#include <ProjectSavePresenter.h>
Public Types
enum class Notification { UncheckWorkspace , CheckWorkspace , PrepareProjectFolder }
Public Member Functions
bool needsSizeWarning (const std::vector< std::string > &wsNames)
Find out if a project needs a save warning.
void notify (Notification notification)
Notify the presenter to do something.
ProjectSavePresenter (IProjectSaveView *view)
Construct a new presenter with a view.
Private Member Functions
void excludeWindowsForUncheckedWorkspace ()
Update the view to add excluded windows for a workspace.
void includeWindowsForCheckedWorkspace ()
Update the view to add included windows for a workspace.
void prepareProjectFolder ()
Prepare a project folder given the path.
Private Attributes
ProjectSaveModel m_model
Hold an instance of the model.
IProjectSaveView * m_view
Handle to the view for this presenter.
Detailed Description
Implements a presenter for the project saving dialog.
Definition at line 25 of file ProjectSavePresenter.h.
Member Enumeration Documentation
Notification
enum class MantidQt::MantidWidgets::ProjectSavePresenter::Notification strong
Enumerator
UncheckWorkspace
CheckWorkspace
PrepareProjectFolder
Definition at line 27 of file ProjectSavePresenter.h.
Constructor & Destructor Documentation
ProjectSavePresenter()
ProjectSavePresenter::ProjectSavePresenter (IProjectSaveView * view)
Construct a new presenter with a view.
Construct a new presenter with the given view.
Parameters
view :: a handle to a view for this presenter
Definition at line 26 of file ProjectSavePresenter.cpp.
References MantidQt::MantidWidgets::ProjectSaveModel::getAllPythonInterfaces(), MantidQt::MantidWidgets::ProjectSaveModel::getWindowInformation(), MantidQt::MantidWidgets::ProjectSaveModel::getWorkspaceInformation(), MantidQt::MantidWidgets::ProjectSaveModel::getWorkspaceNames(), m_model, m_view, MantidQt::MantidWidgets::IProjectSaveView::updateIncludedWindowsList(), MantidQt::MantidWidgets::IProjectSaveView::updateInterfacesList(), and MantidQt::MantidWidgets::IProjectSaveView::updateWorkspacesList().
Member Function Documentation
excludeWindowsForUncheckedWorkspace()
void ProjectSavePresenter::excludeWindowsForUncheckedWorkspace () private
Update the view to add excluded windows for a workspace.
Update the view with a new list of windows that are excluded from project saving based on the currently checked workspaces.
Definition at line 84 of file ProjectSavePresenter.cpp.
References MantidQt::MantidWidgets::IProjectSaveView::getUncheckedWorkspaceNames(), MantidQt::MantidWidgets::ProjectSaveModel::getWindowInformation(), MantidQt::MantidWidgets::ProjectSaveModel::getWindowNames(), m_model, m_view, MantidQt::MantidWidgets::IProjectSaveView::removeFromIncludedWindowsList(), and MantidQt::MantidWidgets::IProjectSaveView::updateExcludedWindowsList().
Referenced by notify().
includeWindowsForCheckedWorkspace()
void ProjectSavePresenter::includeWindowsForCheckedWorkspace () private
Update the view to add included windows for a workspace.
Update the view with a new list of windows that are included in project saving based on the currently checked workspaces.
Definition at line 71 of file ProjectSavePresenter.cpp.
References MantidQt::MantidWidgets::IProjectSaveView::getCheckedWorkspaceNames(), MantidQt::MantidWidgets::ProjectSaveModel::getWindowInformation(), MantidQt::MantidWidgets::ProjectSaveModel::getWindowNames(), m_model, m_view, MantidQt::MantidWidgets::IProjectSaveView::removeFromExcludedWindowsList(), and MantidQt::MantidWidgets::IProjectSaveView::updateIncludedWindowsList().
Referenced by notify().
needsSizeWarning()
bool ProjectSavePresenter::needsSizeWarning (const std::vector< std::string > & wsNames)
Find out if a project needs a save warning.
Check if the user needs to be warned about saving a large project.
Parameters
wsNames Vector of workspace names to check.
Returns
true If a warning is required.
false If a warning is not neccessary.
Definition at line 60 of file ProjectSavePresenter.cpp.
References m_model, and MantidQt::MantidWidgets::ProjectSaveModel::needsSizeWarning().
notify()
void ProjectSavePresenter::notify (Notification notification)
Notify the presenter to do something.
Notify the presenter to perform an action.
Parameters
notification :: notification to choose the action to perform
Definition at line 40 of file ProjectSavePresenter.cpp.
References CheckWorkspace, excludeWindowsForUncheckedWorkspace(), includeWindowsForCheckedWorkspace(), PrepareProjectFolder, prepareProjectFolder(), and UncheckWorkspace.
prepareProjectFolder()
void ProjectSavePresenter::prepareProjectFolder () private
Prepare a project folder given the path.
Prepare a project folder for serialistion.
This will check the file path and if necessary create a new project folder
Definition at line 97 of file ProjectSavePresenter.cpp.
References MantidQt::MantidWidgets::IProjectSaveView::getProjectPath(), m_view, and MantidQt::MantidWidgets::IProjectSaveView::setProjectPath().
Referenced by notify().
Member Data Documentation
m_model
ProjectSaveModel MantidQt::MantidWidgets::ProjectSavePresenter::m_model private
Hold an instance of the model.
Definition at line 49 of file ProjectSavePresenter.h.
Referenced by excludeWindowsForUncheckedWorkspace(), includeWindowsForCheckedWorkspace(), needsSizeWarning(), and ProjectSavePresenter().
m_view
IProjectSaveView* MantidQt::MantidWidgets::ProjectSavePresenter::m_view private
Handle to the view for this presenter.
Definition at line 47 of file ProjectSavePresenter.h.
Referenced by excludeWindowsForUncheckedWorkspace(), includeWindowsForCheckedWorkspace(), prepareProjectFolder(), and ProjectSavePresenter().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/ProjectSavePresenter.h
qt/widgets/common/src/ProjectSavePresenter.cpp