Mantid: MantidQt::MantidWidgets::FitPropertyBrowser Class Reference
MantidQt::MantidWidgets::FitPropertyBrowser Class Reference
Class FitPropertyBrowser implements QtPropertyBrowser to display and control fitting function parameters and settings.
#include <FitPropertyBrowser.h>
Public Slots
virtual void clear ()
Slot.
void clearBrowser ()
void executeClearCustomSetups ()
void executeCustomSetupRemove (const QString &name)
void executeDisplayMenu (const QString &)
virtual void executeFitMenu (const QString &)
void executePeakFindingAlgMenu (const QString &)
void executeSetupManageMenu (const QString &)
void executeSetupMenu (const QString &)
virtual void fit ()
Do the fit.
virtual void removePropertiesFromSettingsBrowser (const QStringList &propsToRemove)
Function to toggle the visibility of a settings group property exposed to python.
virtual void sequentialFit ()
void setPeakToolOn (bool on)
virtual void toggleSettingsBrowserVisible ()
Function to toggle the visibility of the settings browser.
virtual void toggleWsListVisible ()
void undoFit ()
Slot.
void workspaceDoubleClicked (QListWidgetItem *item)
Signals
void algorithmFailed ()
void algorithmFinished (const QString &)
void algorithmStarted (const QString &)
void changedParameterOf (const QString &prefix)
void changeWindowTitle (const QString &)
void currentChanged () const
void endXChanged (double)
void errorsEnabled (bool enabled)
void executeFit (QString, QHash< QString, QString >, Mantid::API::AlgorithmObserver *)
void fitResultsChanged (const QString &status)
void fittingDone (const QString &)
signal which can optionally be caught for customization after a fit has been done
void fitUndone ()
void functionChanged ()
void functionCleared ()
void functionFactoryUpdateReceived ()
void functionLoaded (const QString &)
void functionRemoved ()
void itemDoubleClicked (QListWidgetItem *item)
void multifitFinished ()
void parameterChanged (const Mantid::API::IFunction *)
void plotCurrentGuess ()
void plotGuess ()
void removeCurrentGuess ()
void removeFitCurves ()
void removeGuess ()
void removePlotSignal (MantidQt::MantidWidgets::PropertyHandler *)
void sequentialFitDone () const
void startXChanged (double)
void updatePlotSpectrum (int index)
void workspaceClicked (const QString &wsName)
void workspaceIndexChanged (int index)
void workspaceNameChanged (const QString &)
void wsChangePPAssign (const QString &)
void xRangeChanged (double, double)
Public Member Functions
void addAllowedSpectra (const QString &wsName, const QList< int > &wsIndices)
void addAllowedTableWorkspace (const QString &wsName)
void addAutoBackground ()
Creates and adds the autobackground.
void addFitResultWorkspacesToTableWidget ()
Adds the fit result workspaces to the QListWidget in the browser.
QString addFunction (const QString &fnName)
A specialisation of addFunction to be used in the workbench.
PropertyHandler * addFunction (const std::string &fnName)
Create a new function.
void addHandle (const std::string &wsName, const std::shared_ptr< Mantid::API::Workspace > &ws) override
workspace was added
void allowSequentialFits (bool allow) override
Allow or disallow sequential fits (depending on whether other conditions are met)
double centre () const
Centre of the current peak.
std::shared_ptr< Mantid::API::CompositeFunction > compositeFunction () const
Get Composite Function.
bool convolveMembers () const
Get the "ConvolveMembers" option.
std::string costFunction () const
Get the cost function.
int count () const
Get count.
bool createAndAddFunction (const Mantid::API::MatrixWorkspace_sptr inputWS, const size_t peakIndex, const std::unique_ptr< FindPeakStrategyGeneric > &findPeakStrategy)
void createCompositeFunction (const QString &str="")
Create CompositeFunction from string.
PropertyHandler * currentHandler () const
Get the current function.
const std::string & defaultBackgroundType () const
Get the default background type.
const std::string & defaultFunctionType () const
Get the default function type.
std::string defaultPeakType ()
Get the default peak type.
double endX () const
Get the end X.
void findPeaks (const std::unique_ptr< FindPeakStrategyGeneric > findPeakStrategy)
void finishHandle (const Mantid::API::IAlgorithm *alg) override
Called when the Fit is finished.
FitPropertyBrowser (QWidget *parent=nullptr, QObject *mantidui=nullptr)
Constructor.
double fwhm () const
Width of the current peak.
QString getAutoBackgroundString () const
std::string getCentreParameterNameOf (const QString &prefix)
QString getConstraintsString () const
Creates the "Constraints" property value for the Fit algorithm.
int getDecimals () const
Number of decimal places in double properties.
QString getErrColumnName () const
Get the name of the Error column.
std::string getExcludeRange () const
Get the excluded range for the fit.
const std::string & getFitAlgorithmOutputStatus () const
================================================================================================= Get Fit Algorithm output statuss
const std::string & getFitAlgorithmParameters () const
================================================================================================= Get Fit Algorithm parameters
QMenu * getFitMenu () const
Return the Fit menu.
Mantid::API::IFunction_sptr getFittingFunction () const
Return the fitting function.
Mantid::API::IFunction_sptr getFunctionAtIndex (std::size_t const &index) const
Return a function at a specific index in the composite function.
std::string getFunctionString () const
Get the function as a string.
PropertyHandler * getHandler () const
Get handler to the root composite function.
QString getOldExpressionAsString (const QString &parameterName) const
Get the tie expression stored in the function in case the new expression is invalid and the GUI needs to be reset.
QStringList getParameterNames () const
Get function parameter names.
QList< double > getParameterValues () const
Get function parameter values.
double getPeakCentreOf (const QString &prefix)
double getPeakFwhmOf (const QString &prefix)
PropertyHandler * getPeakHandler (const QString &prefix)
double getPeakHeightOf (const QString &prefix)
QStringList getPeakPrefixes () const
int getPeakRadius () const
Get the peak radius for peak functions.
QString getTieString () const
Creates the "Ties" property value for the Fit algorithm.
std::string getWidthParameterNameOf (const QString &prefix)
std::shared_ptr< Mantid::API::Workspace > getWorkspace () const
Get the workspace.
QListWidget * getWorkspaceList () const
Return the Fit menu.
const QStringList & getWorkspaceNames ()
Returns the list of workspaces that are currently been worked on by the fit property browser.
QString getXColumnName () const
Get the name of the X column.
QVector< double > getXRange ()
Get the X limits of the workspace.
QString getYColumnName () const
Get the name of the Y column.
double height () const
Height of the current peak.
bool ignoreInvalidData () const
Get the ignore invalid data option.
virtual void init ()
Initialise layout.
bool isAutoBack () const
bool isFitEnabled () const
Returns true if the function is ready for a fit.
bool isHistogramFit () const
Get "HistogramFit" option.
bool isParameterExplicitlySetOf (const QString &prefix, const std::string &param)
bool isPeak () const
Is the current function a peak?
bool isUndoEnabled () const
Tells if undo can be done.
void loadFunction (const QString &funcString)
Load function.
int maxIterations () const
Get the max number of iterations.
std::string minimizer (bool withProperties=false) const
Get the minimizer.
void normaliseData (bool on)
Set if the data must be normalised before fitting.
virtual std::string outputName () const
Get the output name.
bool plotCompositeMembers () const
Returns true if a composite's member functions should be plotted also.
bool plotDiff () const
Returns true if the difference plot should be drawn.
void postDeleteHandle (const std::string &wsName) override
workspace was removed
bool rawData () const override
Returns true if the fit should be done against binned (bunched) data.
void refitAutoBackground ()
const QStringList & registeredBackgrounds () const
Return a list of registered backgrounds.
const QStringList & registeredFunctions () const
Return a list of registered functions.
const QStringList & registeredOthers () const
Return a list of registered other functions.
const QStringList & registeredPeaks () const
Return a list of registered peaks.
virtual void removeFunction (PropertyHandler *handler)
Removes the function held by the property handler.
void removeWorkspace (const std::string &wsName)
void removeWorkspaceAndSpectra (const std::string &wsName)
void renameHandle (const std::string &oldName, const std::string &newName) override
Handler of the Rename notifications.
void saveFunction (const QString &fnName)
save function
void sendParameterChanged (const Mantid::API::IFunction *f)
void sendParameterChanged (const QString &prefix)
void sequentialFitFinished ()
void setADSObserveEnabled (bool enabled)
void setAutoBackgroundName (const QString &aName)
Remember a background function name to be used for creating auto-background.
void setCentre (double value)
Set centre of the current peak.
void setCurrentFunction (PropertyHandler *h) const
Set new current function.
void setDecimals (int d)
void setDefaultBackgroundType (const std::string &fnType)
Set the default background type.
void setDefaultFunctionType (const std::string &fnType)
Set the default function type.
void setDefaultPeakType (const std::string &fnType)
Set the default peak type.
void setEndX (double end) override
Set the end X.
virtual void setFitEnabled (bool enable)
Enable/disable the Fit buttons;.
void setFwhm (double value)
Set width of the current peak.
void setHeight (double value)
Set height of the current peak.
void setIgnoreInvalidData (bool on)
Set the ignore invalid data option.
void setOutputName (const std::string &)
Set the output name.
void setPeakCentreOf (const QString &prefix, double value)
void setPeakFwhmOf (const QString &prefix, double value)
void setPeakHeightOf (const QString &prefix, double value)
void setStartX (double start) override
Set the start X.
void setTextPlotGuess (const QString &text)
alter text of Plot Guess
void setTip (const QString &txt)
Display a tip.
void setWorkspaceIndex (int i) override
Set workspace index.
virtual void setWorkspaceName (const QString &wsName) override
Set the input workspace name.
void setXRange (double start, double end)
Set both start and end X.
int sizeOfFunctionsGroup () const
double startX () const
Get the start X.
std::shared_ptr< const Mantid::API::IFunction > theFunction () const
Get the current function.
void updateAttributes ()
Update the function attributes.
void updateParameters ()
Update the function parameters.
int workspaceIndex () const
Get workspace index.
std::string workspaceName () const
Get the input workspace name.
~FitPropertyBrowser () override
Destructor.
Public Member Functions inherited from Mantid::API::AlgorithmObserver
AlgorithmObserver ()
Default constructor.
AlgorithmObserver (const IAlgorithm_const_sptr &alg)
Constructs AlgorithmObserver and connects all its handlers to algorithm alg.
virtual void errorHandle (const IAlgorithm *alg, const std::string &what)
void observeAll (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe all its notifications.
void observeError (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its error notification.
void observeFinish (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its finish notification.
void observeProgress (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its progress notification.
void observeStart (const IAlgorithm_const_sptr &alg)
Connect to algorithm alg and observe its start notification.
void observeStarting ()
Connect to AlgorithmManager and observe its starting notifications.
virtual void progressHandle (const IAlgorithm *alg, double p, const std::string &msg, const double estimatedTime, const int progressPrecision)
virtual void startHandle (const IAlgorithm *alg)
virtual void startingHandle (IAlgorithm_sptr alg)
void stopObserving (const IAlgorithm_const_sptr &alg)
Disconnect from algorithm alg.
void stopObserving (const Mantid::API::IAlgorithm *alg)
void stopObservingManager ()
Disconnect from the algorithm manager.
virtual ~AlgorithmObserver ()
Virtual destructor.
Public Member Functions inherited from MantidQt::API::WorkspaceObserver
void observeAdd (bool on=true)
Observe additions.
void observeADSClear (bool on=true)
Observe clearances.
void observeAfterReplace (bool on=true)
Observe replacements.
void observePostDelete (bool on=true)
Observe workspace deletes.
void observePreDelete (bool on=true)
Observe workspace deletes.
void observeRename (bool on=true)
Observe renaming.
WorkspaceObserver ()
Default constructor.
virtual ~WorkspaceObserver ()
Destructor.
Public Member Functions inherited from MantidQt::MantidWidgets::IWorkspaceFitControl
virtual ~IWorkspaceFitControl ()=default
Protected Slots
virtual void boolChanged (QtProperty *prop)
Called when a bool property is changed.
virtual void doubleChanged (QtProperty *prop)
Called when a double property changed.
void enactAttributeChange (QtProperty *prop, PropertyHandler *h, const bool vectorAttribute=false)
virtual void enumChanged (QtProperty *prop)
Called when the function name property changed.
virtual void intChanged (QtProperty *prop)
Called when an int property changed.
virtual void populateFunctionNames ()
Get the registered function names.
Protected Member Functions
QtProperty * addDoubleProperty (const QString &name, QtDoublePropertyManager *manager=nullptr) const
Create a double property and set some settings.
virtual void addWorkspaceIndexToBrowser ()
Adds the workspace index property to the browser.
void createCompositeFunction (const Mantid::API::IFunction_sptr &func)
Create CompositeFunction from pointer.
void createEditors (QWidget *w)
Create editors and assign them to the managers.
void doFit (int maxIterations)
Do the fitting.
bool getShouldBeNormalised ()
void hideEvent (QHideEvent *e) override
actions to do before the browser is hidden
void initBasicLayout (QWidget *w)
Initialise the layout, except for the fit button in the menu bar.
void initLayout (QWidget *w)
Initialise the layout.
void minimizerChanged ()
Called when the minimizer changes. Creates minimizes's properties.
void modifyFitMenu (QAction *fitAction, bool enabled)
virtual void populateFitMenuButton (QSignalMapper *fitMapper, QMenu *fitMenu)
Populate the fit button.
void populateWorkspaceNames ()
Get and store available workspace names.
void setWorkspace (const Mantid::API::IFunction_sptr &function) const
Sets the workspace to a function.
void setWorkspaceProperties ()
Display properties relevant to the selected workspace.
void showEvent (QShowEvent *e) override
actions to do before the browser made visible
Mantid::API::IFunction_sptr tryCreateFitFunction (const QString &str)
Catches unexpected not found exceptions.
void updateBrowserFromFitResults (const Mantid::API::IFunction_sptr &finalFunction)
Set the parameters to the fit outcome.
void updateDecimals ()
impose a number of decimal places on all defined Double properties
Protected Member Functions inherited from MantidQt::API::WorkspaceObserver
void _addHandle (Mantid::API::WorkspaceAddNotification_ptr pNf)
Poco notification handler for DataService::DeleteNotification.
void _afterReplaceHandle (Mantid::API::WorkspaceAfterReplaceNotification_ptr pNf)
Poco notification handler for DataService::AfterReplaceNotification.
void _clearADSHandle (Mantid::API::ClearADSNotification_ptr)
ADS clear notification.
void _postDeleteHandle (Mantid::API::WorkspacePostDeleteNotification_ptr pNf)
Poco notification handler for DataService::PostDeleteNotification.
void _preDeleteHandle (Mantid::API::WorkspacePreDeleteNotification_ptr pNf)
Poco notification handler for DataService::PostDeleteNotification.
void _renameHandle (Mantid::API::WorkspaceRenameNotification_ptr pNf)
Poco notification handler for DataService::RenameNotification.
virtual void addHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the add notifications.
virtual void afterReplaceHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the AfterReplace notifications.
virtual void clearADSHandle ()
Handle an ADS clear notification.
virtual void preDeleteHandle (const std::string &wsName, const Mantid::API::Workspace_sptr &ws)
Handler of the delete notifications.
Protected Attributes
QtBoolPropertyManager * m_boolManager
QtTreePropertyBrowser * m_browser
bool m_changeSlotsEnabled
If false the change-slots (such as enumChanged(), doubleChanged()) are disabled.
QtEnumPropertyManager * m_columnManager
std::shared_ptr< Mantid::API::CompositeFunction > m_compositeFunction
A copy of the edited function.
QtProperty * m_convolveMembers
QtProperty * m_costFunction
QStringList m_costFunctions
A list of available cost functions.
QtBrowserItem * m_customSettingsGroup
Group for custom options available on muon analysis widget.
QtDoublePropertyManager * m_doubleManager
QtProperty * m_endX
QtEnumPropertyManager * m_enumManager
QtProperty * m_errColumn
QtProperty * m_evaluationType
QStringList m_evaluationTypes
A list of possible function evaluation types.
QtProperty * m_excludeRange
QtStringPropertyManager * m_filenameManager
QAction * m_fitActionEvaluate
QAction * m_fitActionFit
QAction * m_fitActionSeqFit
QAction * m_fitActionUndoFit
QtStringPropertyManager * m_formulaManager
QtBrowserItem * m_functionsGroup
Group for functions.
QtGroupPropertyManager * m_groupManager
Property managers:
bool m_guessOutputName
if true the output name will be guessed every time workspace name is changeed
QtProperty * m_ignoreInvalidData
std::vector< double > m_initialParameters
To keep a copy of the initial parameters in case for undo fit.
QtIntPropertyManager * m_intManager
QtProperty * m_maxIterations
QtProperty * m_minimizer
QList< QtProperty * > m_minimizerProperties
QStringList m_minimizers
A list of available minimizers.
QtProperty * m_output
ParameterPropertyManager * m_parameterManager
QtProperty * m_peakRadius
QtProperty * m_plotCompositeMembers
QtProperty * m_plotDiff
QtProperty * m_rawData
QStringList m_registeredBackgrounds
A list of registered backgrounds.
QStringList m_registeredFunctions
A list of registered functions.
QStringList m_registeredOther
A list of registered functions that are neither peaks nor backgrounds.
QStringList m_registeredPeaks
A list of registered peaks.
QtBrowserItem * m_settingsGroup
Group for input/output settings.
QtProperty * m_showParamErrors
QtProperty * m_startX
QtStringPropertyManager * m_stringManager
QtDoublePropertyManager * m_vectorDoubleManager
QtGroupPropertyManager * m_vectorManager
QtIntPropertyManager * m_vectorSizeManager
QtProperty * m_workspace
QtProperty * m_workspaceIndex
QStringList m_workspaceNames
A list of available workspaces.
QtProperty * m_xColumn
QtProperty * m_yColumn
Protected Attributes inherited from MantidQt::API::WorkspaceObserver
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceAddNotification > m_addObserver
Poco::NObserver for DataServise::AddNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceAfterReplaceNotification > m_afterReplaceObserver
Poco::NObserver for DataServise::AfterReplaceNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::ClearADSNotification > m_clearADSObserver
Clear notification observer.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspacePostDeleteNotification > m_postDeleteObserver
Poco::NObserver for DataServise::DeleteNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspacePreDeleteNotification > m_preDeleteObserver
Poco::NObserver for DataServise::DeleteNotification.
Poco::NObserver< WorkspaceObserver, Mantid::API::WorkspaceRenameNotification > m_renameObserver
Poco::NObserver for DataServise::RenameNotification.
Private Slots
void acceptFit ()
void addBothBounds ()
Slot.Adds lower and upper bounds to the selected parameter property.
void addBothBounds10 ()
Slot.Sets the lower and upper bounds of the selected parameter to 10% of its value.
void addBothBounds50 ()
Slot.Sets the lower and upper bounds of the selected parameter to 50% of its value.
void addConstraint (int f, bool lo, bool up)
Slot.
void addFixTie ()
Slot.
void addFunction ()
Slot.
void addLowerBound ()
Slot.
void addLowerBound10 ()
Slot.
void addLowerBound50 ()
Slot.
void addTie ()
Slot.
void addTieToFunction ()
Slot.
void addUpperBound ()
Slot.Adds upper bound to the selected parameter property.
void addUpperBound10 ()
Slot.Adds upper bound to the selected parameter property.
void addUpperBound50 ()
Slot.Adds upper bound to the selected parameter property.
void browserHelp ()
Open a web page with description of FitPropertyBrowser.
void clearAllPlots ()
void clearFitResultStatus ()
Clear the Fit status display.
void closeFit ()
void columnChanged (QtProperty *prop)
================================================================================================= Slot connected to the change signals of properties m_xColumn, m_yColumn, and m_errColumn.
void copy ()
Copy the function string to the clipboard.
void currentItemChanged (QtBrowserItem *)
Slot.
void deleteFunction ()
Slot.
void deleteTie ()
Slot.
void executeCustomSetupLoad (const QString &name)
void filenameChanged (QtProperty *prop)
Called when a filename property changed.
void functionHelp ()
Open a web page with description of the current function.
void loadFunction ()
void loadFunctionFromString ()
void parameterChanged (QtProperty *prop)
Called when one of the parameter values gets changed.
void paste ()
Paste a function string from the clipboard.
void plotGuessAll ()
Slot.
void plotGuessCurrent ()
Slot.
void plotOrRemoveGuessAll ()
void popupMenu (const QPoint &)
void processMultiBGResults ()
Process and create some output if it is a MultiBG fit.
void removeBounds ()
Slot.Removes lower and upper bounds from the selected parameter property.
void removeGuessAll ()
Slot.
void removeGuessCurrent ()
Slot.
void reset ()
reset the function part, renew function, all handlers are new
void saveFunction ()
void setupMultifit ()
Call MultifitSetupDialog to populate MultiBG function.
void showFitResultStatus (const QString &status)
Display the status string returned from Fit.
void stringChanged (QtProperty *prop)
Called when a string property changed.
void updateStructureTooltips ()
Update structure tooltips for all functions.
void vectorDoubleChanged (QtProperty *prop)
Slot.
void vectorSizeChanged (QtProperty *prop)
Slot.
Private Member Functions
QtProperty * addStringListProperty (const QString &name, const std::vector< std::string > &allowed_values) const
Create a string list property.
QtProperty * addStringProperty (const QString &name) const
Create a string property and set some settings.
void checkFunction ()
Check that the properties match the function.
QPushButton * createFitMenuButton (QWidget *w)
Initialise the layout for the fit button.
void disableUndo ()
disable undo when the function changes
QtBrowserItem * findItem (QtBrowserItem *parent, QtProperty *prop) const
Find QtBrowserItem for a property prop among the chidren of.
int getAllowedIndex (int currentIndex) const
Return the nearest allowed workspace index.
QString getStringPropertyValue (QtProperty *prop) const
QtProperty * getTieProperty (QtProperty *parProp) const
Returns the tie property for a parameter property, or NULL.
void handleFactoryUpdate (Mantid::API::FunctionFactoryUpdateNotification_ptr)
Callback for FunctionFactory update notifications.
void hasConstraints (QtProperty *parProp, bool &hasTie, bool &hasFix, bool &hasBounds) const
Does a parameter have a tie.
virtual bool isWorkspaceValid (Mantid::API::Workspace_sptr) const
Check if the workspace can be used in the fit.
void setCurrentFunction (const Mantid::API::IFunction_const_sptr &f) const
Set new current function.
void setStringPropertyValue (QtProperty *prop, const QString &value) const
Set a value to a string property.
void updateSetupMenus ()
Update setup menus according to how these are set in settings.
virtual void workspaceChange (const QString &wsName)
Sets the new workspace to the current one.
Private Attributes
QMap< QString, QList< int > > m_allowedSpectra
If non-empty it contains references to the spectra allowed to be fitted in this browser: keys are workspace names, values are lists of workspace indices.
QString m_allowedTableWorkspace
If set it contains the table workspace name to be fitted in this browser:
bool m_auto_back
If true background function will be included automatically.
PropertyHandler * m_autoBackground
The autobackground handler.
QString m_autoBgAttributes
List of attributes of the autobackground function as name=value pairs separated by spaces.
QString m_autoBgName
Name of the autobackground function.
PropertyHandler * m_currentHandler
QStringList m_dataTypes
A list of available data types.
int m_decimals
Number of decimal places in double properties.
std::string m_defaultBackground
Default background name.
std::string m_defaultFunction
Default function name.
std::string m_defaultPeak
Default peak name.
QAction * m_displayActionClearAll
QAction * m_displayActionPlotGuess
QAction * m_displayActionQuality
std::string m_fitAlgOutputStatus
std::string m_fitAlgParameters
QSignalMapper * m_fitMapper
Make sure m_groupMember belongs to the group.
QMenu * m_fitMenu
SelectFunctionDialog * m_fitSelector
QTreeWidget * m_fitTree
bool m_hideWsListWidget
bool to display ws list or not
QObject * m_mantidui
holds effectively a MantidUI for connecting
int m_oldWorkspaceIndex
Store workspace index to revert to in case validation fails.
bool m_peakToolOn
Shows if the PeakPickerTool is on.
QAction * m_setupActionCustomSetup
Setup menu.
QAction * m_setupActionRemove
bool m_shouldBeNormalised
Should the data be normalised before fitting?
QLabel * m_status
To display fit status.
std::string m_storedWorkspaceName
store current workspace name
QMap< QString, QtStringPropertyManager * > m_stringManagers
String property managers for special case attributes such as Filename or Formula <attribute_name,string_manager>
QLabel * m_tip
To display a tip text.
Poco::NObserver< FitPropertyBrowser, Mantid::API::FunctionFactoryUpdateNotification > m_updateObserver
Observes algorithm factory update notifications.
QString m_windowBaseString
QLabel * m_workspaceLabel
QListWidget * m_wsListWidget
Friends
class CreateAttributeProperty
class PropertyHandler
class SequentialFitDialog
class SetAttribute
class SetAttributeProperty
Detailed Description
Class FitPropertyBrowser implements QtPropertyBrowser to display and control fitting function parameters and settings.
Date
13/11/2009
Definition at line 66 of file FitPropertyBrowser.h.
Constructor & Destructor Documentation
FitPropertyBrowser()
MantidQt::MantidWidgets::FitPropertyBrowser::FitPropertyBrowser (QWidget * parent = nullptr, QObject * mantidui = nullptr)
Constructor.
Parameters
parent :: The parent widget - must be an ApplicationWindow
mantidui :: The UI form for MantidPlot
Definition at line 80 of file FitPropertyBrowser.cpp.
References m_autoBgName, m_boolManager, m_columnManager, m_defaultBackground, m_defaultFunction, m_defaultPeak, m_doubleManager, m_enumManager, m_filenameManager, m_formulaManager, m_groupManager, m_intManager, m_parameterManager, m_stringManager, m_vectorDoubleManager, m_vectorManager, m_vectorSizeManager, m_workspace, and setAutoBackgroundName().
~FitPropertyBrowser()
MantidQt::MantidWidgets::FitPropertyBrowser::~FitPropertyBrowser () override
Destructor.
Definition at line 684 of file FitPropertyBrowser.cpp.
References m_boolManager, m_browser, m_columnManager, m_compositeFunction, m_doubleManager, m_enumManager, m_filenameManager, m_formulaManager, m_intManager, m_parameterManager, m_stringManager, m_updateObserver, m_vectorDoubleManager, and m_vectorSizeManager.
Member Function Documentation
acceptFit
void MantidQt::MantidWidgets::FitPropertyBrowser::acceptFit () private slot
Definition at line 742 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addFunction(), closeFit(), MantidQt::MantidWidgets::PropertyHandler::findCompositeFunction(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), functionChanged(), MantidQt::MantidWidgets::SelectFunctionDialog::getFunction(), getHandler(), m_browser, and m_fitSelector.
Referenced by addFunction().
addAllowedSpectra()
void MantidQt::MantidWidgets::FitPropertyBrowser::addAllowedSpectra (const QString & wsName, const QList< int > & wsIndices)
Definition at line 3248 of file FitPropertyBrowser.cpp.
References intChanged(), m_allowedSpectra, m_workspaceIndex, name, and populateWorkspaceNames().
addAllowedTableWorkspace()
void MantidQt::MantidWidgets::FitPropertyBrowser::addAllowedTableWorkspace (const QString & wsName)
Definition at line 3279 of file FitPropertyBrowser.cpp.
References m_allowedTableWorkspace, and name.
addAutoBackground()
void MantidQt::MantidWidgets::FitPropertyBrowser::addAutoBackground ()
Creates and adds the autobackground.
Definition at line 2657 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::calcBaseAll(), currentHandler(), MantidQt::MantidWidgets::PropertyHandler::fit(), Mantid::API::FunctionHandler::function(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::hasPlot(), m_autoBackground, m_autoBgAttributes, m_autoBgName, name, plotCurrentGuess(), MantidQt::MantidWidgets::PropertyHandler::removeFunction(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), setCurrentFunction(), and value.
Referenced by createCompositeFunction().
addBothBounds
void MantidQt::MantidWidgets::FitPropertyBrowser::addBothBounds () private slot
Slot.Adds lower and upper bounds to the selected parameter property.
Definition at line 2401 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addBothBounds10
void MantidQt::MantidWidgets::FitPropertyBrowser::addBothBounds10 () private slot
Slot.Sets the lower and upper bounds of the selected parameter to 10% of its value.
Definition at line 2390 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addBothBounds50
void MantidQt::MantidWidgets::FitPropertyBrowser::addBothBounds50 () private slot
Slot.Sets the lower and upper bounds of the selected parameter to 50% of its value.
Definition at line 2396 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addConstraint
void MantidQt::MantidWidgets::FitPropertyBrowser::addConstraint (int f, bool lo, bool up) private slot
Slot.
Adds lower bound to the selected parameter property and sets it f % below parameter's current value
Definition at line 2342 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addConstraint(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), m_browser, and Mantid::Geometry::x.
Referenced by addBothBounds(), addBothBounds10(), addBothBounds50(), addLowerBound(), addLowerBound10(), addLowerBound50(), addUpperBound(), addUpperBound10(), and addUpperBound50().
addDoubleProperty()
QtProperty * MantidQt::MantidWidgets::FitPropertyBrowser::addDoubleProperty (const QString & name, QtDoublePropertyManager * manager = nullptr) const protected
Create a double property and set some settings.
Parameters
name :: The name of the new property
manager :: The current property manager
Returns
Pointer to the created property
Definition at line 2452 of file FitPropertyBrowser.cpp.
References m_decimals, m_doubleManager, and name.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addConstraint(), MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::CreateAttributeProperty::apply(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), and minimizerChanged().
addFitResultWorkspacesToTableWidget()
void MantidQt::MantidWidgets::FitPropertyBrowser::addFitResultWorkspacesToTableWidget ()
Adds the fit result workspaces to the QListWidget in the browser.
Definition at line 519 of file FitPropertyBrowser.cpp.
References m_hideWsListWidget, m_workspaceLabel, m_wsListWidget, name, and outputName().
addFixTie
void MantidQt::MantidWidgets::FitPropertyBrowser::addFixTie () private slot
Slot.
Adds a tie. The current item must be a function parameter
Definition at line 2223 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::findHandler(), MantidQt::MantidWidgets::PropertyHandler::fix(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::isParameter(), and m_browser.
Referenced by popupMenu().
addFunction [1/3]
void MantidQt::MantidWidgets::FitPropertyBrowser::addFunction () private slot
Slot.
Called to add a new function
Definition at line 727 of file FitPropertyBrowser.cpp.
References acceptFit(), closeFit(), MantidQt::MantidWidgets::PropertyHandler::findCompositeFunction(), getHandler(), m_browser, and m_fitSelector.
Referenced by addFunction(), createAndAddFunction(), and popupMenu().
addFunction() [2/3]
QString MantidQt::MantidWidgets::FitPropertyBrowser::addFunction (const QString & fnName)
A specialisation of addFunction to be used in the workbench.
It returns an id of the added function as a string of "f-dot" indices. This provides function identification that doesn't use PropertyHandlers and can be used on the python side.
Parameters
fnName :: Name of a function to add.
Returns
:: An ID string, eg: f0.f2.f1 (There is no dot at the end).
Definition at line 3297 of file FitPropertyBrowser.cpp.
References addFunction().
addFunction() [3/3]
PropertyHandler * MantidQt::MantidWidgets::FitPropertyBrowser::addFunction (const std::string & fnName)
Create a new function.
Definition at line 709 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addFunction(), functionChanged(), and getHandler().
addHandle()
void MantidQt::MantidWidgets::FitPropertyBrowser::addHandle (const std::string & wsName, const std::shared_ptr< Mantid::API::Workspace > & ws) override
workspace was added
Definition at line 1810 of file FitPropertyBrowser.cpp.
References isWorkspaceValid(), m_allowedSpectra, m_allowedTableWorkspace, m_enumManager, m_workspace, m_workspaceNames, and workspaceName().
addLowerBound
void MantidQt::MantidWidgets::FitPropertyBrowser::addLowerBound () private slot
Slot.
Adds lower bound to the selected parameter property
Definition at line 2359 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addLowerBound10
void MantidQt::MantidWidgets::FitPropertyBrowser::addLowerBound10 () private slot
Slot.
Adds lower bound to the selected parameter property
Definition at line 2364 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addLowerBound50
void MantidQt::MantidWidgets::FitPropertyBrowser::addLowerBound50 () private slot
Slot.
Adds lower bound to the selected parameter property
Definition at line 2369 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addStringListProperty()
QtProperty * MantidQt::MantidWidgets::FitPropertyBrowser::addStringListProperty (const QString & name, const std::vector< std::string > & allowed_values) const private
Create a string list property.
Create a string list property and selects a property manager for it based on the property name.
Parameters
name :: The name of the new property
allowed_values :: A list of the values allowed by the validator
Returns
Pointer to the created property
Definition at line 2487 of file FitPropertyBrowser.cpp.
References m_enumManager, and name.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply().
addStringProperty()
QtProperty * MantidQt::MantidWidgets::FitPropertyBrowser::addStringProperty (const QString & name) const private
Create a string property and set some settings.
Create a string property and selects a property manager for it based on the property name.
Parameters
name :: The name of the new property
Returns
Pointer to the created property
!! dont forget to change the manager !!!
Definition at line 2466 of file FitPropertyBrowser.cpp.
References m_filenameManager, m_formulaManager, m_stringManager, and name.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply().
addTie
void MantidQt::MantidWidgets::FitPropertyBrowser::addTie () private slot
Slot.
Adds a tie. Full expression to be entered <name>=<formula>
Definition at line 2149 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addTie(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), Mantid::API::FunctionHandler::function(), MantidQt::MantidWidgets::PropertyHandler::functionPrefix(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::isParameter(), and m_browser.
Referenced by popupMenu().
addTieToFunction
void MantidQt::MantidWidgets::FitPropertyBrowser::addTieToFunction () private slot
Slot.
Ties a parameter to a parameter with the same name of a different function
Definition at line 2177 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addTie(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), Mantid::API::FunctionHandler::function(), getHandler(), Mantid::API::ParameterReference::getLocalFunction(), Mantid::API::ParameterReference::getLocalIndex(), MantidQt::MantidWidgets::PropertyHandler::isParameter(), m_browser, m_compositeFunction, and Mantid::API::IFunction::parameterName().
Referenced by popupMenu().
addUpperBound
void MantidQt::MantidWidgets::FitPropertyBrowser::addUpperBound () private slot
Slot.Adds upper bound to the selected parameter property.
Definition at line 2384 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addUpperBound10
void MantidQt::MantidWidgets::FitPropertyBrowser::addUpperBound10 () private slot
Slot.Adds upper bound to the selected parameter property.
Definition at line 2374 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addUpperBound50
void MantidQt::MantidWidgets::FitPropertyBrowser::addUpperBound50 () private slot
Slot.Adds upper bound to the selected parameter property.
Definition at line 2379 of file FitPropertyBrowser.cpp.
References addConstraint().
Referenced by popupMenu().
addWorkspaceIndexToBrowser()
void MantidQt::MantidWidgets::FitPropertyBrowser::addWorkspaceIndexToBrowser () protected virtual
Adds the workspace index property to the browser.
Definition at line 3045 of file FitPropertyBrowser.cpp.
References m_browser, m_settingsGroup, m_workspace, and m_workspaceIndex.
Referenced by setWorkspaceProperties().
algorithmFailed
void MantidQt::MantidWidgets::FitPropertyBrowser::algorithmFailed () signal
Referenced by doFit().
algorithmFinished
void MantidQt::MantidWidgets::FitPropertyBrowser::algorithmFinished (const QString &) signal
Referenced by finishHandle().
algorithmStarted
void MantidQt::MantidWidgets::FitPropertyBrowser::algorithmStarted (const QString &) signal
Referenced by doFit().
allowSequentialFits()
void MantidQt::MantidWidgets::FitPropertyBrowser::allowSequentialFits (bool allow) override virtual
Allow or disallow sequential fits (depending on whether other conditions are met)
================================================================================================= Allow/disallow sequential fits, depending on whether other conditions are met
Parameters
allow :: [input] Allow or disallow
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Definition at line 3226 of file FitPropertyBrowser.cpp.
References m_compositeFunction, and m_fitActionSeqFit.
boolChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::boolChanged (QtProperty * prop) protected virtual slot
Called when a bool property is changed.
Called when a bool property changed.
Parameters
prop :: A pointer to the property
Definition at line 1287 of file FitPropertyBrowser.cpp.
References enactAttributeChange(), errorsEnabled(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), m_boolManager, m_changeSlotsEnabled, m_ignoreInvalidData, m_parameterManager, m_plotCompositeMembers, m_plotDiff, and m_showParamErrors.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), and initBasicLayout().
browserHelp
void MantidQt::MantidWidgets::FitPropertyBrowser::browserHelp () private slot
Open a web page with description of FitPropertyBrowser.
================================================================================================= Show online browser help
Definition at line 3217 of file FitPropertyBrowser.cpp.
References MantidQt::API::HelpWindow::showPage().
Referenced by popupMenu().
centre()
double MantidQt::MantidWidgets::FitPropertyBrowser::centre () const
Centre of the current peak.
Definition at line 1515 of file FitPropertyBrowser.cpp.
References m_currentHandler, and MantidQt::MantidWidgets::PropertyHandler::pfun().
changedParameterOf
void MantidQt::MantidWidgets::FitPropertyBrowser::changedParameterOf (const QString & prefix) signal
changeWindowTitle
void MantidQt::MantidWidgets::FitPropertyBrowser::changeWindowTitle (const QString &) signal
Referenced by finishHandle(), and initBasicLayout().
checkFunction()
void MantidQt::MantidWidgets::FitPropertyBrowser::checkFunction () private
Check that the properties match the function.
Definition at line 2522 of file FitPropertyBrowser.cpp.
clear
void MantidQt::MantidWidgets::FitPropertyBrowser::clear () virtual slot
Slot.
Removes all functions.
Definition at line 2086 of file FitPropertyBrowser.cpp.
References clearBrowser(), createCompositeFunction(), functionCleared(), getHandler(), and MantidQt::MantidWidgets::PropertyHandler::removeAllPlots().
Referenced by executeSetupMenu(), findPeaks(), and popupMenu().
clearAllPlots
void MantidQt::MantidWidgets::FitPropertyBrowser::clearAllPlots () private slot
Definition at line 2445 of file FitPropertyBrowser.cpp.
References removeFitCurves().
Referenced by executeDisplayMenu().
clearBrowser
void MantidQt::MantidWidgets::FitPropertyBrowser::clearBrowser () slot
Definition at line 2093 of file FitPropertyBrowser.cpp.
References m_functionsGroup.
Referenced by clear(), loadFunction(), and reset().
clearFitResultStatus
void MantidQt::MantidWidgets::FitPropertyBrowser::clearFitResultStatus () private slot
Clear the Fit status display.
Definition at line 1751 of file FitPropertyBrowser.cpp.
References m_status.
Referenced by initBasicLayout(), and undoFit().
closeFit
void MantidQt::MantidWidgets::FitPropertyBrowser::closeFit () private slot
Definition at line 758 of file FitPropertyBrowser.cpp.
References m_fitSelector.
Referenced by acceptFit(), and addFunction().
columnChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::columnChanged (QtProperty * prop) private slot
================================================================================================= Slot connected to the change signals of properties m_xColumn, m_yColumn, and m_errColumn.
Parameters
prop :: Property that changed.
Definition at line 3090 of file FitPropertyBrowser.cpp.
References m_columnManager, m_doubleManager, m_endX, m_startX, m_xColumn, and workspaceName().
Referenced by initBasicLayout().
compositeFunction()
std::shared_ptr< Mantid::API::CompositeFunction > MantidQt::MantidWidgets::FitPropertyBrowser::compositeFunction () const inline
Get Composite Function.
Definition at line 127 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::addTie(), MantidQt::MantidWidgets::MultifitSetupDialog::cellChanged(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), getOldExpressionAsString(), isUndoEnabled(), MantidQt::MantidWidgets::MultifitSetupDialog::MultifitSetupDialog(), processMultiBGResults(), removeFunction(), MantidQt::MantidWidgets::PropertyHandler::removeTie(), MantidQt::MantidWidgets::PropertyHandler::renameChildren(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), stringChanged(), undoFit(), and updateBrowserFromFitResults().
convolveMembers()
bool MantidQt::MantidWidgets::FitPropertyBrowser::convolveMembers () const
Get the "ConvolveMembers" option.
Definition at line 1190 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_convolveMembers.
Referenced by doFit().
copy
void MantidQt::MantidWidgets::FitPropertyBrowser::copy () private slot
Copy the function string to the clipboard.
Definition at line 2623 of file FitPropertyBrowser.cpp.
References theFunction().
Referenced by executeSetupManageMenu(), and popupMenu().
costFunction()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::costFunction () const
Get the cost function.
Definition at line 1182 of file FitPropertyBrowser.cpp.
References m_costFunction, m_costFunctions, and m_enumManager.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), and doFit().
count()
int MantidQt::MantidWidgets::FitPropertyBrowser::count () const
Get count.
Get number of functions in CompositeFunction.
Definition at line 1572 of file FitPropertyBrowser.cpp.
References m_compositeFunction.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::checkFitEnabled(), MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), isPeak(), and popupMenu().
createAndAddFunction()
bool MantidQt::MantidWidgets::FitPropertyBrowser::createAndAddFunction (const Mantid::API::MatrixWorkspace_sptr inputWS, const size_t peakIndex, const std::unique_ptr< FindPeakStrategyGeneric > & findPeakStrategy)
Definition at line 3301 of file FitPropertyBrowser.cpp.
References addFunction(), defaultPeakType(), endX(), startX(), and workspaceIndex().
Referenced by findPeaks().
createCompositeFunction() [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::createCompositeFunction (const Mantid::API::IFunction_sptr & func) protected
Create CompositeFunction from pointer.
Create CompositeFunction from function pointer.
Parameters
func :: [input] Pointer to function
Definition at line 764 of file FitPropertyBrowser.cpp.
References addAutoBackground(), disableUndo(), functionChanged(), functionRemoved(), m_auto_back, m_autoBackground, m_compositeFunction, setCurrentFunction(), setFitEnabled(), and setWorkspace().
createCompositeFunction() [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::createCompositeFunction (const QString & str = "")
Create CompositeFunction from string.
Parameters
str :: [input] Function string
Definition at line 799 of file FitPropertyBrowser.cpp.
References createCompositeFunction(), and tryCreateFitFunction().
Referenced by clear(), createCompositeFunction(), initBasicLayout(), loadFunction(), paste(), and reset().
createEditors()
void MantidQt::MantidWidgets::FitPropertyBrowser::createEditors (QWidget * w) protected
Create editors and assign them to the managers.
Associates a particular widget factory to each property manager. Thus, the factory will automatically create widgets befitting to edit the properties that we define.
Parameters
w :: widget showing the properties tree and the actions buttons
Definition at line 553 of file FitPropertyBrowser.cpp.
References m_boolManager, m_browser, m_columnManager, m_doubleManager, m_enumManager, m_filenameManager, m_formulaManager, m_intManager, m_parameterManager, m_stringManager, m_vectorDoubleManager, and m_vectorSizeManager.
Referenced by init(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
createFitMenuButton()
QPushButton * MantidQt::MantidWidgets::FitPropertyBrowser::createFitMenuButton (QWidget * w) private
Initialise the layout for the fit button.
This initialization includes:
SIGNALs/SLOTs when properties change.
Actions and associated SIGNALs/SLOTs.
Parameters
w widget parenting the action menus and the property tree browser
Returns
push botton for the fit menu
Definition at line 277 of file FitPropertyBrowser.cpp.
References executeFitMenu(), m_fitMapper, m_fitMenu, m_tip, and populateFitMenuButton().
Referenced by initBasicLayout().
currentChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::currentChanged () const signal
Referenced by currentItemChanged(), and setCurrentFunction().
currentHandler()
PropertyHandler * MantidQt::MantidWidgets::FitPropertyBrowser::currentHandler () const
Get the current function.
Definition at line 1575 of file FitPropertyBrowser.cpp.
References m_currentHandler.
Referenced by addAutoBackground(), and functionHelp().
currentItemChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::currentItemChanged (QtBrowserItem * current) private slot
Slot.
Responds to changing the current item
Definition at line 2042 of file FitPropertyBrowser.cpp.
References currentChanged(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), and m_currentHandler.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and initBasicLayout().
defaultBackgroundType()
const std::string & MantidQt::MantidWidgets::FitPropertyBrowser::defaultBackgroundType () const
Get the default background type.
Definition at line 1067 of file FitPropertyBrowser.cpp.
References m_defaultBackground.
defaultFunctionType()
const std::string & MantidQt::MantidWidgets::FitPropertyBrowser::defaultFunctionType () const
Get the default function type.
Definition at line 1047 of file FitPropertyBrowser.cpp.
References m_defaultFunction.
defaultPeakType()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::defaultPeakType ()
Get the default peak type.
Definition at line 1053 of file FitPropertyBrowser.cpp.
References Mantid::API::g_log, m_defaultPeak, m_registeredPeaks, setDefaultPeakType(), and Mantid::Kernel::Logger::warning().
Referenced by createAndAddFunction().
deleteFunction
void MantidQt::MantidWidgets::FitPropertyBrowser::deleteFunction () private slot
Slot.
Called to remove a function
Definition at line 1038 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), m_browser, and removeFunction().
Referenced by popupMenu().
deleteTie
void MantidQt::MantidWidgets::FitPropertyBrowser::deleteTie () private slot
Slot.
Deletes a tie.
Definition at line 2237 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::findHandler(), Mantid::API::FunctionHandler::function(), getHandler(), Mantid::API::ParameterReference::getLocalFunction(), Mantid::API::ParameterReference::getLocalIndex(), MantidQt::MantidWidgets::PropertyHandler::getTies(), m_browser, m_compositeFunction, Mantid::API::IFunction::parameterName(), and MantidQt::MantidWidgets::PropertyHandler::removeTie().
Referenced by popupMenu().
disableUndo()
void MantidQt::MantidWidgets::FitPropertyBrowser::disableUndo () private
disable undo when the function changes
Definition at line 2127 of file FitPropertyBrowser.cpp.
References m_fitActionUndoFit, and m_initialParameters.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), createCompositeFunction(), enumChanged(), and undoFit().
doFit()
void MantidQt::MantidWidgets::FitPropertyBrowser::doFit (int maxIterations) protected
Do the fitting.
Creates an instance of Fit algorithm, sets its properties and launches it.
Definition at line 1598 of file FitPropertyBrowser.cpp.
References algorithmFailed(), algorithmStarted(), compositeFunction(), convolveMembers(), costFunction(), endX(), Mantid::API::g_log, getErrColumnName(), getExcludeRange(), getPeakRadius(), getWorkspace(), getXColumnName(), getYColumnName(), ignoreInvalidData(), isHistogramFit(), m_fitActionUndoFit, m_fitAlgParameters, m_initialParameters, m_shouldBeNormalised, maxIterations(), minimizer(), Mantid::API::AlgorithmObserver::observeFinish(), outputName(), startX(), Mantid::Kernel::Logger::warning(), workspaceIndex(), and workspaceName().
Referenced by executeFitMenu(), and fit().
doubleChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::doubleChanged (QtProperty * prop) protected virtual slot
Called when a double property changed.
Parameters
prop :: A pointer to the property
Definition at line 1362 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addConstraint(), enactAttributeChange(), endX(), endXChanged(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::getParameterProperty(), m_changeSlotsEnabled, m_compositeFunction, m_doubleManager, m_endX, m_startX, MantidQt::MantidWidgets::PropertyHandler::setAttribute(), setWorkspace(), startX(), startXChanged(), value, and xRangeChanged().
Referenced by initBasicLayout(), and setXRange().
enactAttributeChange
void MantidQt::MantidWidgets::FitPropertyBrowser::enactAttributeChange (QtProperty * prop, PropertyHandler * h, const bool vectorAttribute = false) protected slot
Definition at line 1403 of file FitPropertyBrowser.cpp.
References Mantid::API::g_log, MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setVectorAttribute(), and Mantid::Kernel::Logger::warning().
Referenced by boolChanged(), doubleChanged(), intChanged(), vectorDoubleChanged(), and vectorSizeChanged().
endX()
double MantidQt::MantidWidgets::FitPropertyBrowser::endX () const
Get the end X.
Definition at line 1926 of file FitPropertyBrowser.cpp.
References m_doubleManager, and m_endX.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::centre(), MantidQt::MantidWidgets::PropertyHandler::changeType(), createAndAddFunction(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::PropertyHandler::EstimateFwhm(), findPeaks(), MantidQt::MantidWidgets::PropertyHandler::fit(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), setupMultifit(), and setWorkspace().
endXChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::endXChanged (double) signal
Referenced by doubleChanged(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged().
enumChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::enumChanged (QtProperty * prop) protected virtual slot
Called when the function name property changed.
Parameters
prop :: A pointer to the function name property m_functionName
Definition at line 1246 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::changeType(), disableUndo(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), functionChanged(), getHandler(), intChanged(), m_changeSlotsEnabled, m_compositeFunction, m_enumManager, m_evaluationType, m_minimizer, m_storedWorkspaceName, m_workspace, m_workspaceIndex, minimizerChanged(), MantidQt::MantidWidgets::PropertyHandler::parentHandler(), setCurrentFunction(), setWorkspaceProperties(), workspaceChange(), and workspaceName().
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), and initBasicLayout().
errorsEnabled
void MantidQt::MantidWidgets::FitPropertyBrowser::errorsEnabled (bool enabled) signal
Referenced by boolChanged().
executeClearCustomSetups
void MantidQt::MantidWidgets::FitPropertyBrowser::executeClearCustomSetups () slot
Definition at line 624 of file FitPropertyBrowser.cpp.
References updateSetupMenus().
Referenced by executeSetupManageMenu().
executeCustomSetupLoad
void MantidQt::MantidWidgets::FitPropertyBrowser::executeCustomSetupLoad (const QString & name) private slot
Definition at line 608 of file FitPropertyBrowser.cpp.
References loadFunction(), and name.
Referenced by updateSetupMenus().
executeCustomSetupRemove
void MantidQt::MantidWidgets::FitPropertyBrowser::executeCustomSetupRemove (const QString & name) slot
Definition at line 616 of file FitPropertyBrowser.cpp.
References name, and updateSetupMenus().
Referenced by updateSetupMenus().
executeDisplayMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::executeDisplayMenu (const QString & item) slot
Definition at line 652 of file FitPropertyBrowser.cpp.
References clearAllPlots(), and plotOrRemoveGuessAll().
Referenced by initBasicLayout().
executeFit
void MantidQt::MantidWidgets::FitPropertyBrowser::executeFit (QString , QHash< QString, QString > , Mantid::API::AlgorithmObserver *) signal
executeFitMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::executeFitMenu (const QString & item) virtual slot
Definition at line 640 of file FitPropertyBrowser.cpp.
References doFit(), fit(), sequentialFit(), and undoFit().
Referenced by createFitMenuButton(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::executeFitMenu().
executePeakFindingAlgMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::executePeakFindingAlgMenu (const QString & item) slot
Definition at line 660 of file FitPropertyBrowser.cpp.
References findPeaks().
Referenced by initBasicLayout().
executeSetupManageMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::executeSetupManageMenu (const QString & item) slot
Definition at line 672 of file FitPropertyBrowser.cpp.
References copy(), executeClearCustomSetups(), loadFunctionFromString(), and saveFunction().
Referenced by initBasicLayout().
executeSetupMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::executeSetupMenu (const QString & item) slot
Definition at line 667 of file FitPropertyBrowser.cpp.
References clear().
Referenced by initBasicLayout().
filenameChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::filenameChanged (QtProperty * prop) private slot
Called when a filename property changed.
Parameters
prop :: A pointer to the property
Definition at line 1506 of file FitPropertyBrowser.cpp.
References getHandler(), and m_changeSlotsEnabled.
findItem()
QtBrowserItem * MantidQt::MantidWidgets::FitPropertyBrowser::findItem (QtBrowserItem * parent, QtProperty * prop) const private
Find QtBrowserItem for a property prop among the chidren of.
Definition at line 2023 of file FitPropertyBrowser.cpp.
References findItem().
Referenced by findItem().
findPeaks()
void MantidQt::MantidWidgets::FitPropertyBrowser::findPeaks (const std::unique_ptr< FindPeakStrategyGeneric > findPeakStrategy)
Definition at line 2739 of file FitPropertyBrowser.cpp.
References clear(), createAndAddFunction(), endX(), startX(), workspaceIndex(), and workspaceName().
Referenced by executePeakFindingAlgMenu().
finishHandle()
void MantidQt::MantidWidgets::FitPropertyBrowser::finishHandle (const Mantid::API::IAlgorithm * alg) override virtual
Called when the Fit is finished.
Reimplemented from Mantid::API::AlgorithmObserver.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 1695 of file FitPropertyBrowser.cpp.
References algorithmFinished(), changeWindowTitle(), Mantid::Kernel::IPropertyManager::existsProperty(), fitResultsChanged(), fittingDone(), Mantid::Kernel::IPropertyManager::getProperty(), Mantid::Kernel::IPropertyManager::getPropertyValue(), m_compositeFunction, m_displayActionQuality, m_fitAlgOutputStatus, multifitFinished(), name, and updateBrowserFromFitResults().
fit
void MantidQt::MantidWidgets::FitPropertyBrowser::fit () virtual slot
Do the fit.
Definition at line 3056 of file FitPropertyBrowser.cpp.
References doFit(), m_intManager, and m_maxIterations.
Referenced by executeFitMenu(), and popupMenu().
fitResultsChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::fitResultsChanged (const QString & status) signal
Referenced by finishHandle(), and initBasicLayout().
fittingDone
void MantidQt::MantidWidgets::FitPropertyBrowser::fittingDone (const QString &) signal
signal which can optionally be caught for customization after a fit has been done
Referenced by finishHandle().
fitUndone
void MantidQt::MantidWidgets::FitPropertyBrowser::fitUndone () signal
Referenced by undoFit().
functionChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::functionChanged () signal
Referenced by acceptFit(), addFunction(), createCompositeFunction(), enumChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), initBasicLayout(), removeFunction(), and stringChanged().
functionCleared
void MantidQt::MantidWidgets::FitPropertyBrowser::functionCleared () signal
Referenced by clear().
functionFactoryUpdateReceived
void MantidQt::MantidWidgets::FitPropertyBrowser::functionFactoryUpdateReceived () signal
Referenced by handleFactoryUpdate(), and initBasicLayout().
functionHelp
void MantidQt::MantidWidgets::FitPropertyBrowser::functionHelp () private slot
Open a web page with description of the current function.
================================================================================================= Show online function help
Definition at line 3207 of file FitPropertyBrowser.cpp.
References currentHandler(), MantidQt::MantidWidgets::PropertyHandler::ifun(), and MantidQt::API::HelpWindow::showFitFunction().
Referenced by popupMenu().
functionLoaded
void MantidQt::MantidWidgets::FitPropertyBrowser::functionLoaded (const QString &) signal
Referenced by loadFunction().
functionRemoved
void MantidQt::MantidWidgets::FitPropertyBrowser::functionRemoved () signal
Referenced by createCompositeFunction(), and removeFunction().
fwhm()
double MantidQt::MantidWidgets::FitPropertyBrowser::fwhm () const
Width of the current peak.
Definition at line 1553 of file FitPropertyBrowser.cpp.
References m_currentHandler, and MantidQt::MantidWidgets::PropertyHandler::pfun().
getAllowedIndex()
int MantidQt::MantidWidgets::FitPropertyBrowser::getAllowedIndex (int currentIndex) const private
Return the nearest allowed workspace index.
If the current workspace index is set to a disallowed value this function returns the nearest allowed index.
Otherwise the current index is returned.
Definition at line 2528 of file FitPropertyBrowser.cpp.
References getWorkspace(), m_allowedSpectra, m_oldWorkspaceIndex, workspace, and workspaceName().
Referenced by intChanged(), and setWorkspaceIndex().
getAutoBackgroundString()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getAutoBackgroundString () const inline
Definition at line 243 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
getCentreParameterNameOf()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::getCentreParameterNameOf (const QString & prefix)
Definition at line 3368 of file FitPropertyBrowser.cpp.
References getPeakHandler().
getConstraintsString()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getConstraintsString () const
Creates the "Constraints" property value for the Fit algorithm.
getDecimals()
int MantidQt::MantidWidgets::FitPropertyBrowser::getDecimals () const inline
Number of decimal places in double properties.
Definition at line 246 of file FitPropertyBrowser.h.
getErrColumnName()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getErrColumnName () const
Get the name of the Error column.
Definition at line 2005 of file FitPropertyBrowser.cpp.
References getWorkspace(), m_columnManager, and m_errColumn.
Referenced by doFit().
getExcludeRange()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::getExcludeRange () const
Get the excluded range for the fit.
Get the excluded range.
Definition at line 1208 of file FitPropertyBrowser.cpp.
References m_excludeRange, and m_stringManager.
Referenced by doFit().
getFitAlgorithmOutputStatus()
const std::string & MantidQt::MantidWidgets::FitPropertyBrowser::getFitAlgorithmOutputStatus () const
================================================================================================= Get Fit Algorithm output statuss
Definition at line 3202 of file FitPropertyBrowser.cpp.
References m_fitAlgOutputStatus.
getFitAlgorithmParameters()
const std::string & MantidQt::MantidWidgets::FitPropertyBrowser::getFitAlgorithmParameters () const
================================================================================================= Get Fit Algorithm parameters
Definition at line 3197 of file FitPropertyBrowser.cpp.
References m_fitAlgParameters.
getFitMenu()
QMenu * MantidQt::MantidWidgets::FitPropertyBrowser::getFitMenu () const inline
Return the Fit menu.
This gives Python access to events emitted by this menu.
Definition at line 280 of file FitPropertyBrowser.h.
getFittingFunction()
Mantid::API::IFunction_sptr MantidQt::MantidWidgets::FitPropertyBrowser::getFittingFunction () const
Return the fitting function.
Return the function that will be passed to Fit.
Definition at line 1678 of file FitPropertyBrowser.cpp.
References getFunctionAtIndex(), and m_compositeFunction.
Referenced by getFunctionString().
getFunctionAtIndex()
Mantid::API::IFunction_sptr MantidQt::MantidWidgets::FitPropertyBrowser::getFunctionAtIndex (std::size_t const & index) const
Return a function at a specific index in the composite function.
Return the function within a composite function at the position specified.
Definition at line 1691 of file FitPropertyBrowser.cpp.
References index, and m_compositeFunction.
Referenced by getFittingFunction(), processMultiBGResults(), and setupMultifit().
getFunctionString()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::getFunctionString () const
Get the function as a string.
Definition at line 1731 of file FitPropertyBrowser.cpp.
References getFittingFunction().
getHandler()
PropertyHandler * MantidQt::MantidWidgets::FitPropertyBrowser::getHandler () const
Get handler to the root composite function.
Definition at line 705 of file FitPropertyBrowser.cpp.
References m_compositeFunction.
Referenced by acceptFit(), addAutoBackground(), addConstraint(), addFixTie(), addFunction(), addFunction(), addTie(), addTieToFunction(), boolChanged(), clear(), currentItemChanged(), deleteFunction(), deleteTie(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), enumChanged(), filenameChanged(), MantidQt::MantidWidgets::PropertyHandler::fit(), MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), getPeakHandler(), getPeakPrefixes(), intChanged(), loadFunction(), parameterChanged(), plotOrRemoveGuessAll(), popupMenu(), removeBounds(), removeFunction(), setCurrentFunction(), setXRange(), stringChanged(), undoFit(), updateAttributes(), updateBrowserFromFitResults(), updateParameters(), updateStructureTooltips(), vectorDoubleChanged(), and vectorSizeChanged().
getOldExpressionAsString()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getOldExpressionAsString (const QString & parameterName) const
Get the tie expression stored in the function in case the new expression is invalid and the GUI needs to be reset.
Parameters
parameterName :: A pointer to the parameter name
Definition at line 1483 of file FitPropertyBrowser.cpp.
References compositeFunction().
Referenced by stringChanged().
getParameterNames()
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::getParameterNames () const
Get function parameter names.
================================================================================================= Get parameter names
Definition at line 3184 of file FitPropertyBrowser.cpp.
References theFunction().
getParameterValues()
QList< double > MantidQt::MantidWidgets::FitPropertyBrowser::getParameterValues () const
Get function parameter values.
================================================================================================= Get function parameter values
Definition at line 3170 of file FitPropertyBrowser.cpp.
References theFunction().
getPeakCentreOf()
double MantidQt::MantidWidgets::FitPropertyBrowser::getPeakCentreOf (const QString & prefix)
Definition at line 3336 of file FitPropertyBrowser.cpp.
References getPeakHandler().
getPeakFwhmOf()
double MantidQt::MantidWidgets::FitPropertyBrowser::getPeakFwhmOf (const QString & prefix)
Definition at line 3358 of file FitPropertyBrowser.cpp.
References getPeakHandler().
getPeakHandler()
PropertyHandler * MantidQt::MantidWidgets::FitPropertyBrowser::getPeakHandler (const QString & prefix)
Definition at line 3317 of file FitPropertyBrowser.cpp.
References getHandler(), index, and n.
Referenced by getCentreParameterNameOf(), getPeakCentreOf(), getPeakFwhmOf(), getPeakHeightOf(), getWidthParameterNameOf(), isParameterExplicitlySetOf(), setPeakCentreOf(), setPeakFwhmOf(), and setPeakHeightOf().
getPeakHeightOf()
double MantidQt::MantidWidgets::FitPropertyBrowser::getPeakHeightOf (const QString & prefix)
Definition at line 3347 of file FitPropertyBrowser.cpp.
References getPeakHandler().
getPeakPrefixes()
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::getPeakPrefixes () const
Definition at line 3378 of file FitPropertyBrowser.cpp.
References getHandler().
getPeakRadius()
int MantidQt::MantidWidgets::FitPropertyBrowser::getPeakRadius () const
Get the peak radius for peak functions.
Definition at line 1205 of file FitPropertyBrowser.cpp.
References m_intManager, and m_peakRadius.
Referenced by doFit().
getShouldBeNormalised()
bool MantidQt::MantidWidgets::FitPropertyBrowser::getShouldBeNormalised () inline protected
Definition at line 459 of file FitPropertyBrowser.h.
getStringPropertyValue()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getStringPropertyValue (QtProperty * prop) const private
Definition at line 2512 of file FitPropertyBrowser.cpp.
Referenced by MantidQt::MantidWidgets::SetAttribute::apply().
getTieProperty()
QtProperty * MantidQt::MantidWidgets::FitPropertyBrowser::getTieProperty (QtProperty * parProp) const private
Returns the tie property for a parameter property, or NULL.
Returns the tie property for a parameter property, or nullptr.
Parameters
parProp :: parameter property
Definition at line 2312 of file FitPropertyBrowser.cpp.
References Mantid::Geometry::x.
getTieString()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getTieString () const
Creates the "Ties" property value for the Fit algorithm.
getWidthParameterNameOf()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::getWidthParameterNameOf (const QString & prefix)
Definition at line 3363 of file FitPropertyBrowser.cpp.
References getPeakHandler().
getWorkspace()
std::shared_ptr< Mantid::API::Workspace > MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspace () const
Get the workspace.
Definition at line 1074 of file FitPropertyBrowser.cpp.
References workspaceName().
Referenced by MantidQt::MantidWidgets::PropertyHandler::calcBase(), doFit(), MantidQt::MantidWidgets::PropertyHandler::EstimateFwhm(), getAllowedIndex(), getErrColumnName(), getXColumnName(), getXRange(), getYColumnName(), and MantidQt::MantidWidgets::PropertyHandler::setCentre().
getWorkspaceList()
QListWidget * MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspaceList () const inline
Return the Fit menu.
This gives Python access to events emitted by this menu.
Definition at line 284 of file FitPropertyBrowser.h.
getWorkspaceNames()
const QStringList & MantidQt::MantidWidgets::FitPropertyBrowser::getWorkspaceNames ()
Returns the list of workspaces that are currently been worked on by the fit property browser.
Returns the list of workspace names the fit property browser is working on.
Definition at line 2830 of file FitPropertyBrowser.cpp.
References m_workspaceNames.
getXColumnName()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getXColumnName () const
Get the name of the X column.
Definition at line 1975 of file FitPropertyBrowser.cpp.
References getWorkspace(), m_columnManager, and m_xColumn.
Referenced by doFit().
getXRange()
QVector< double > MantidQt::MantidWidgets::FitPropertyBrowser::getXRange ()
Get the X limits of the workspace.
Definition at line 1947 of file FitPropertyBrowser.cpp.
References getWorkspace(), m_columnManager, m_xColumn, and workspaceIndex().
getYColumnName()
QString MantidQt::MantidWidgets::FitPropertyBrowser::getYColumnName () const
Get the name of the Y column.
Definition at line 1990 of file FitPropertyBrowser.cpp.
References getWorkspace(), m_columnManager, and m_yColumn.
Referenced by doFit().
handleFactoryUpdate()
void MantidQt::MantidWidgets::FitPropertyBrowser::handleFactoryUpdate (Mantid::API::FunctionFactoryUpdateNotification_ptr notice) private
Callback for FunctionFactory update notifications.
Called when the function factory has been updated.
Parameters
notice A Poco notification object
Definition at line 2326 of file FitPropertyBrowser.cpp.
References functionFactoryUpdateReceived().
hasConstraints()
void MantidQt::MantidWidgets::FitPropertyBrowser::hasConstraints (QtProperty * parProp, bool & hasTie, bool & hasFix, bool & hasBounds) const private
Does a parameter have a tie.
Does a parameter have a tie, is fixed, or has bounds.
Parameters
parProp :: The property for a function parameter
hasTie :: Parameter has a tie
hasFix :: Parameter is fixed
hasBounds :: Parameter has bounds
Definition at line 2290 of file FitPropertyBrowser.cpp.
Referenced by popupMenu().
height()
double MantidQt::MantidWidgets::FitPropertyBrowser::height () const
Height of the current peak.
Definition at line 1534 of file FitPropertyBrowser.cpp.
References m_currentHandler, and MantidQt::MantidWidgets::PropertyHandler::pfun().
hideEvent()
void MantidQt::MantidWidgets::FitPropertyBrowser::hideEvent (QHideEvent * e) override protected
actions to do before the browser is hidden
Disconnect from the AnalysisDataService when hiden.
Definition at line 1798 of file FitPropertyBrowser.cpp.
References setADSObserveEnabled().
ignoreInvalidData()
bool MantidQt::MantidWidgets::FitPropertyBrowser::ignoreInvalidData () const
Get the ignore invalid data option.
Definition at line 1176 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_ignoreInvalidData.
Referenced by doFit().
init()
void MantidQt::MantidWidgets::FitPropertyBrowser::init () virtual
Initialise layout.
Initialise the fit property browser.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 149 of file FitPropertyBrowser.cpp.
References addDoubleProperty(), createEditors(), initLayout(), m_boolManager, m_browser, m_columnManager, m_convolveMembers, m_costFunction, m_costFunctions, m_endX, m_enumManager, m_errColumn, m_evaluationType, m_evaluationTypes, m_excludeRange, m_functionsGroup, m_groupManager, m_ignoreInvalidData, m_intManager, m_mantidui, m_maxIterations, m_minimizer, m_minimizers, m_output, m_parameterManager, m_peakRadius, m_plotCompositeMembers, m_plotDiff, m_settingsGroup, m_showParamErrors, m_startX, m_stringManager, m_workspace, m_workspaceIndex, m_xColumn, m_yColumn, setIgnoreInvalidData(), updateDecimals(), and xRangeChanged().
initBasicLayout()
void MantidQt::MantidWidgets::FitPropertyBrowser::initBasicLayout (QWidget * w) protected
Initialise the layout, except for the fit button in the menu bar.
This initialization includes:
SIGNALs/SLOTs when properties change.
Action menus and associated SIGNALs/SLOTs.
Initialize the CompositeFunction, the root from which to build the Model. 4. Update the list of available functions
Parameters
w widget parenting the action menus and the property tree browser
Definition at line 331 of file FitPropertyBrowser.cpp.
References boolChanged(), changeWindowTitle(), clearFitResultStatus(), columnChanged(), createCompositeFunction(), createFitMenuButton(), currentItemChanged(), doubleChanged(), enumChanged(), executeDisplayMenu(), executePeakFindingAlgMenu(), executeSetupManageMenu(), executeSetupMenu(), fitResultsChanged(), functionChanged(), functionFactoryUpdateReceived(), intChanged(), itemDoubleClicked(), m_boolManager, m_browser, m_changeSlotsEnabled, m_columnManager, m_displayActionClearAll, m_displayActionPlotGuess, m_displayActionQuality, m_doubleManager, m_enumManager, m_filenameManager, m_formulaManager, m_groupManager, m_intManager, m_parameterManager, m_setupActionCustomSetup, m_setupActionRemove, m_status, m_stringManager, m_tip, m_updateObserver, m_vectorDoubleManager, m_vectorSizeManager, m_workspaceLabel, m_wsListWidget, multifitFinished(), parameterChanged(), populateFunctionNames(), popupMenu(), processMultiBGResults(), showFitResultStatus(), stringChanged(), updateSetupMenus(), updateStructureTooltips(), vectorDoubleChanged(), vectorSizeChanged(), and workspaceDoubleClicked().
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and initLayout().
initLayout()
void MantidQt::MantidWidgets::FitPropertyBrowser::initLayout (QWidget * w) protected
Initialise the layout.
This initialization includes:
SIGNALs/SLOTs when properties change.
Action menus and associated SIGNALs/SLOTs.
Initialize the CompositeFunction, the root from which to build the Model. 4. Update the list of available functions
Parameters
w widget parenting the action menus and the property tree browser
Definition at line 267 of file FitPropertyBrowser.cpp.
References initBasicLayout().
Referenced by init().
intChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::intChanged (QtProperty * prop) protected virtual slot
Called when an int property changed.
Parameters
prop :: A pointer to the property
Definition at line 1314 of file FitPropertyBrowser.cpp.
References enactAttributeChange(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), getAllowedIndex(), getHandler(), index, m_changeSlotsEnabled, m_compositeFunction, m_intManager, m_maxIterations, m_oldWorkspaceIndex, m_peakRadius, m_workspaceIndex, sendParameterChanged(), MantidQt::MantidWidgets::PropertyHandler::setAttribute(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), setWorkspaceIndex(), updatePlotSpectrum(), workspaceIndex(), and workspaceIndexChanged().
Referenced by addAllowedSpectra(), enumChanged(), and initBasicLayout().
isAutoBack()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isAutoBack () const inline
Definition at line 240 of file FitPropertyBrowser.h.
isFitEnabled()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isFitEnabled () const
Returns true if the function is ready for a fit.
Definition at line 2144 of file FitPropertyBrowser.cpp.
References m_fitActionFit.
Referenced by popupMenu().
isHistogramFit()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isHistogramFit () const
Get "HistogramFit" option.
Definition at line 1193 of file FitPropertyBrowser.cpp.
References m_enumManager, m_evaluationType, and m_evaluationTypes.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), and doFit().
isParameterExplicitlySetOf()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isParameterExplicitlySetOf (const QString & prefix, const std::string & param)
Definition at line 3373 of file FitPropertyBrowser.cpp.
References getPeakHandler().
isPeak()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isPeak () const
Is the current function a peak?
Definition at line 1912 of file FitPropertyBrowser.cpp.
References count(), m_currentHandler, and MantidQt::MantidWidgets::PropertyHandler::pfun().
isUndoEnabled()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isUndoEnabled () const
Tells if undo can be done.
Definition at line 2133 of file FitPropertyBrowser.cpp.
References compositeFunction(), and m_initialParameters.
Referenced by popupMenu().
isWorkspaceValid()
bool MantidQt::MantidWidgets::FitPropertyBrowser::isWorkspaceValid (Mantid::API::Workspace_sptr ws) const private virtual
Check if the workspace can be used in the fit.
The accepted types are MatrixWorkspaces or TableWorkspaces
Parameters
ws :: The workspace
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 1906 of file FitPropertyBrowser.cpp.
Referenced by addHandle(), and populateWorkspaceNames().
itemDoubleClicked
void MantidQt::MantidWidgets::FitPropertyBrowser::itemDoubleClicked (QListWidgetItem * item) signal
Referenced by initBasicLayout().
loadFunction [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::loadFunction () private slot
Definition at line 2581 of file FitPropertyBrowser.cpp.
References loadFunction(), and name.
Referenced by executeCustomSetupLoad(), loadFunction(), loadFunctionFromString(), popupMenu(), and setupMultifit().
loadFunction() [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::loadFunction (const QString & funcString)
Load function.
Definition at line 2605 of file FitPropertyBrowser.cpp.
References clearBrowser(), createCompositeFunction(), functionLoaded(), getHandler(), m_auto_back, and MantidQt::MantidWidgets::PropertyHandler::removeAllPlots().
loadFunctionFromString
void MantidQt::MantidWidgets::FitPropertyBrowser::loadFunctionFromString () private slot
Definition at line 2597 of file FitPropertyBrowser.cpp.
References loadFunction().
Referenced by executeSetupManageMenu().
maxIterations()
int MantidQt::MantidWidgets::FitPropertyBrowser::maxIterations () const
Get the max number of iterations.
Definition at line 1202 of file FitPropertyBrowser.cpp.
References m_intManager, and m_maxIterations.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), and doFit().
minimizer()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::minimizer (bool withProperties = false) const
Get the minimizer.
Definition at line 1145 of file FitPropertyBrowser.cpp.
References m_boolManager, m_doubleManager, m_enumManager, m_intManager, m_minimizer, m_minimizerProperties, m_minimizers, m_stringManager, and value.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), and minimizerChanged().
minimizerChanged()
void MantidQt::MantidWidgets::FitPropertyBrowser::minimizerChanged () protected
Called when the minimizer changes. Creates minimizes's properties.
================================================================================================= Called when the minimizer changes.
Creates minimizes's properties.
Definition at line 3114 of file FitPropertyBrowser.cpp.
References addDoubleProperty(), m_boolManager, m_doubleManager, m_intManager, m_minimizerProperties, m_settingsGroup, m_stringManager, and minimizer().
Referenced by enumChanged().
modifyFitMenu()
void MantidQt::MantidWidgets::FitPropertyBrowser::modifyFitMenu (QAction * fitAction, bool enabled) protected
Definition at line 3236 of file FitPropertyBrowser.cpp.
References m_fitMenu.
multifitFinished
void MantidQt::MantidWidgets::FitPropertyBrowser::multifitFinished () signal
Referenced by finishHandle(), and initBasicLayout().
normaliseData()
void MantidQt::MantidWidgets::FitPropertyBrowser::normaliseData (bool on) inline
Set if the data must be normalised before fitting.
Definition at line 174 of file FitPropertyBrowser.h.
outputName()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::outputName () const virtual
Get the output name.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 1137 of file FitPropertyBrowser.cpp.
References m_output, and m_stringManager.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), addFitResultWorkspacesToTableWidget(), doFit(), and stringChanged().
parameterChanged [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::parameterChanged (const Mantid::API::IFunction *) signal
Referenced by initBasicLayout(), setCentre(), setFwhm(), and setHeight().
parameterChanged [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::parameterChanged (QtProperty * prop) private slot
Called when one of the parameter values gets changed.
This could be caused either by user setting the value or programmatically.
Parameters
prop :: Parameter property which value got changed
Definition at line 1423 of file FitPropertyBrowser.cpp.
References getHandler(), m_changeSlotsEnabled, and MantidQt::MantidWidgets::PropertyHandler::setParameter().
paste
void MantidQt::MantidWidgets::FitPropertyBrowser::paste () private slot
Paste a function string from the clipboard.
Definition at line 2628 of file FitPropertyBrowser.cpp.
References createCompositeFunction().
plotCompositeMembers()
bool MantidQt::MantidWidgets::FitPropertyBrowser::plotCompositeMembers () const
Returns true if a composite's member functions should be plotted also.
Returns
true if each function with a composite should also be plotted
Definition at line 2809 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_plotCompositeMembers.
plotCurrentGuess
void MantidQt::MantidWidgets::FitPropertyBrowser::plotCurrentGuess () signal
Referenced by addAutoBackground(), and plotGuessCurrent().
plotDiff()
bool MantidQt::MantidWidgets::FitPropertyBrowser::plotDiff () const
Returns true if the difference plot should be drawn.
Definition at line 2806 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_plotDiff.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
plotGuess
void MantidQt::MantidWidgets::FitPropertyBrowser::plotGuess () signal
Referenced by plotGuessAll().
plotGuessAll
void MantidQt::MantidWidgets::FitPropertyBrowser::plotGuessAll () private slot
Slot.
Sends a signal to plot the guess for the whole function
Definition at line 2424 of file FitPropertyBrowser.cpp.
References plotGuess().
Referenced by plotOrRemoveGuessAll(), and popupMenu().
plotGuessCurrent
void MantidQt::MantidWidgets::FitPropertyBrowser::plotGuessCurrent () private slot
Slot.
Sends a signal to plot the guess for the current (selected) function
Definition at line 2419 of file FitPropertyBrowser.cpp.
References plotCurrentGuess().
Referenced by popupMenu().
plotOrRemoveGuessAll
void MantidQt::MantidWidgets::FitPropertyBrowser::plotOrRemoveGuessAll () private slot
Definition at line 2437 of file FitPropertyBrowser.cpp.
References getHandler(), plotGuessAll(), and removeGuessAll().
Referenced by executeDisplayMenu().
populateFitMenuButton()
void MantidQt::MantidWidgets::FitPropertyBrowser::populateFitMenuButton (QSignalMapper * fitMapper, QMenu * fitMenu) protected virtual
Populate the fit button.
This initialization includes:
SIGNALs/SLOTs when properties change.
Actions and associated SIGNALs/SLOTs.
Parameters
fitMapper the QMap to the fit mapper
fitMenu the QMenu for the fit button
Definition at line 297 of file FitPropertyBrowser.cpp.
References m_fitActionEvaluate, m_fitActionFit, m_fitActionSeqFit, and m_fitActionUndoFit.
Referenced by createFitMenuButton().
populateFunctionNames
void MantidQt::MantidWidgets::FitPropertyBrowser::populateFunctionNames () protected virtual slot
Get the registered function names.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 1213 of file FitPropertyBrowser.cpp.
References Mantid::API::g_log, m_registeredBackgrounds, m_registeredFunctions, m_registeredOther, m_registeredPeaks, and Mantid::Kernel::Logger::warning().
Referenced by initBasicLayout().
populateWorkspaceNames()
void MantidQt::MantidWidgets::FitPropertyBrowser::populateWorkspaceNames () protected
Get and store available workspace names.
Definition at line 1757 of file FitPropertyBrowser.cpp.
References isWorkspaceValid(), m_allowedSpectra, m_allowedTableWorkspace, m_enumManager, m_workspace, m_workspaceNames, name, and setWorkspaceIndex().
Referenced by addAllowedSpectra(), setWorkspaceName(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceName(), and showEvent().
popupMenu
void MantidQt::MantidWidgets::FitPropertyBrowser::popupMenu (const QPoint &) private slot
Definition at line 821 of file FitPropertyBrowser.cpp.
References addBothBounds(), addBothBounds10(), addBothBounds50(), addFixTie(), addFunction(), addLowerBound(), addLowerBound10(), addLowerBound50(), addTie(), addTieToFunction(), addUpperBound(), addUpperBound10(), addUpperBound50(), browserHelp(), clear(), copy(), count(), deleteFunction(), deleteTie(), MantidQt::MantidWidgets::PropertyHandler::findCompositeFunction(), MantidQt::MantidWidgets::PropertyHandler::findFunction(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), fit(), functionHelp(), getHandler(), hasConstraints(), MantidQt::MantidWidgets::PropertyHandler::hasPlot(), isFitEnabled(), MantidQt::MantidWidgets::PropertyHandler::isParameter(), isUndoEnabled(), loadFunction(), m_browser, m_compositeFunction, m_functionsGroup, m_peakToolOn, m_settingsGroup, plotGuessAll(), plotGuessCurrent(), removeBounds(), removeGuessAll(), removeGuessCurrent(), saveFunction(), setupMultifit(), undoFit(), and workspaceName().
Referenced by initBasicLayout().
postDeleteHandle()
void MantidQt::MantidWidgets::FitPropertyBrowser::postDeleteHandle (const std::string & wsName) override virtual
workspace was removed
Reimplemented from MantidQt::API::WorkspaceObserver.
Definition at line 1840 of file FitPropertyBrowser.cpp.
References removeWorkspace().
processMultiBGResults
void MantidQt::MantidWidgets::FitPropertyBrowser::processMultiBGResults () private slot
Process and create some output if it is a MultiBG fit.
Definition at line 2870 of file FitPropertyBrowser.cpp.
References compositeFunction(), getFunctionAtIndex(), group, Mantid::Kernel::SingletonHolder< T >::Instance(), name, and workspaceName().
Referenced by initBasicLayout().
rawData()
bool MantidQt::MantidWidgets::FitPropertyBrowser::rawData () const override virtual
Returns true if the fit should be done against binned (bunched) data.
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Definition at line 2811 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_rawData.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::getUnnormName(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization().
refitAutoBackground()
void MantidQt::MantidWidgets::FitPropertyBrowser::refitAutoBackground ()
Definition at line 2699 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::fit(), and m_autoBackground.
registeredBackgrounds()
const QStringList & MantidQt::MantidWidgets::FitPropertyBrowser::registeredBackgrounds () const inline
Return a list of registered backgrounds.
Definition at line 208 of file FitPropertyBrowser.h.
registeredFunctions()
const QStringList & MantidQt::MantidWidgets::FitPropertyBrowser::registeredFunctions () const inline
Return a list of registered functions.
Definition at line 204 of file FitPropertyBrowser.h.
registeredOthers()
const QStringList & MantidQt::MantidWidgets::FitPropertyBrowser::registeredOthers () const inline
Return a list of registered other functions.
Definition at line 210 of file FitPropertyBrowser.h.
registeredPeaks()
const QStringList & MantidQt::MantidWidgets::FitPropertyBrowser::registeredPeaks () const inline
Return a list of registered peaks.
Definition at line 206 of file FitPropertyBrowser.h.
removeBounds
void MantidQt::MantidWidgets::FitPropertyBrowser::removeBounds () private slot
Slot.Removes lower and upper bounds from the selected parameter property.
Definition at line 2406 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::findHandler(), getHandler(), m_browser, and MantidQt::MantidWidgets::PropertyHandler::removeConstraint().
Referenced by popupMenu().
removeCurrentGuess
void MantidQt::MantidWidgets::FitPropertyBrowser::removeCurrentGuess () signal
Referenced by removeGuessCurrent().
removeFitCurves
void MantidQt::MantidWidgets::FitPropertyBrowser::removeFitCurves () signal
Referenced by clearAllPlots().
removeFunction()
void MantidQt::MantidWidgets::FitPropertyBrowser::removeFunction (PropertyHandler * handler) virtual
Removes the function held by the property handler.
Definition at line 715 of file FitPropertyBrowser.cpp.
References compositeFunction(), functionChanged(), functionRemoved(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::removeFunction(), and removePlotSignal().
Referenced by deleteFunction().
removeGuess
void MantidQt::MantidWidgets::FitPropertyBrowser::removeGuess () signal
Referenced by removeGuessAll().
removeGuessAll
void MantidQt::MantidWidgets::FitPropertyBrowser::removeGuessAll () private slot
Slot.
Sends a signal to remove the guess for the whole function
Definition at line 2435 of file FitPropertyBrowser.cpp.
References removeGuess().
Referenced by plotOrRemoveGuessAll(), and popupMenu().
removeGuessCurrent
void MantidQt::MantidWidgets::FitPropertyBrowser::removeGuessCurrent () private slot
Slot.
Sends a signal to remove the guess for the current (selected) function
Definition at line 2430 of file FitPropertyBrowser.cpp.
References removeCurrentGuess().
Referenced by popupMenu().
removePlotSignal
void MantidQt::MantidWidgets::FitPropertyBrowser::removePlotSignal (MantidQt::MantidWidgets::PropertyHandler *) signal
Referenced by MantidQt::MantidWidgets::PropertyHandler::changeType(), MantidQt::MantidWidgets::PropertyHandler::removeAllPlots(), MantidQt::MantidWidgets::PropertyHandler::removeFunction(), and removeFunction().
removePropertiesFromSettingsBrowser
void MantidQt::MantidWidgets::FitPropertyBrowser::removePropertiesFromSettingsBrowser (const QStringList & propsToRemove) virtual slot
Function to toggle the visibility of a settings group property exposed to python.
Definition at line 3073 of file FitPropertyBrowser.cpp.
References m_settingsGroup.
removeWorkspace()
void MantidQt::MantidWidgets::FitPropertyBrowser::removeWorkspace (const std::string & wsName)
Definition at line 1842 of file FitPropertyBrowser.cpp.
References m_enumManager, m_workspace, m_workspaceLabel, m_workspaceNames, m_wsListWidget, and workspaceName().
Referenced by postDeleteHandle(), and removeWorkspaceAndSpectra().
removeWorkspaceAndSpectra()
void MantidQt::MantidWidgets::FitPropertyBrowser::removeWorkspaceAndSpectra (const std::string & wsName)
Definition at line 3272 of file FitPropertyBrowser.cpp.
References m_allowedSpectra, and removeWorkspace().
renameHandle()
void MantidQt::MantidWidgets::FitPropertyBrowser::renameHandle (const std::string & oldName, const std::string & newName) override virtual
Handler of the Rename notifications.
Could be overriden in inherited classes. The default handler is provided (doing nothing).
Parameters
oldName :: The old name of a workspace
newName :: The new name of a workspace
Reimplemented from MantidQt::API::WorkspaceObserver.
Definition at line 1877 of file FitPropertyBrowser.cpp.
References m_allowedSpectra, m_enumManager, m_workspace, m_workspaceNames, m_wsListWidget, and workspaceChange().
reset
void MantidQt::MantidWidgets::FitPropertyBrowser::reset () private slot
reset the function part, renew function, all handlers are new
Definition at line 2634 of file FitPropertyBrowser.cpp.
References clearBrowser(), createCompositeFunction(), and theFunction().
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction().
saveFunction [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::saveFunction () private slot
Definition at line 2558 of file FitPropertyBrowser.cpp.
References saveFunction().
Referenced by executeSetupManageMenu(), popupMenu(), and saveFunction().
saveFunction() [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::saveFunction (const QString & fnName)
save function
Definition at line 2567 of file FitPropertyBrowser.cpp.
References theFunction(), and updateSetupMenus().
sendParameterChanged() [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::sendParameterChanged (const Mantid::API::IFunction * f) inline
Definition at line 233 of file FitPropertyBrowser.h.
Referenced by intChanged(), and MantidQt::MantidWidgets::PropertyHandler::setParameter().
sendParameterChanged() [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::sendParameterChanged (const QString & prefix) inline
Definition at line 236 of file FitPropertyBrowser.h.
sequentialFit
void MantidQt::MantidWidgets::FitPropertyBrowser::sequentialFit () virtual slot
Definition at line 2731 of file FitPropertyBrowser.cpp.
References m_mantidui, SequentialFitDialog, and workspaceName().
Referenced by executeFitMenu().
sequentialFitDone
void MantidQt::MantidWidgets::FitPropertyBrowser::sequentialFitDone () const signal
sequentialFitFinished()
void MantidQt::MantidWidgets::FitPropertyBrowser::sequentialFitFinished () inline
Definition at line 315 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::finishHandle().
setADSObserveEnabled()
void MantidQt::MantidWidgets::FitPropertyBrowser::setADSObserveEnabled (bool enabled)
Definition at line 1803 of file FitPropertyBrowser.cpp.
References MantidQt::API::WorkspaceObserver::observeAdd(), MantidQt::API::WorkspaceObserver::observePostDelete(), and MantidQt::API::WorkspaceObserver::observeRename().
Referenced by hideEvent(), and showEvent().
setAutoBackgroundName()
void MantidQt::MantidWidgets::FitPropertyBrowser::setAutoBackgroundName (const QString & aName)
Remember a background function name to be used for creating auto-background.
Parameters
aName :: A name of the auto-background. The may be followed by function attributes as name=value pairs separated by spaces.
Definition at line 2711 of file FitPropertyBrowser.cpp.
References m_auto_back, m_autoBgAttributes, m_autoBgName, and name.
Referenced by FitPropertyBrowser().
setCentre()
void MantidQt::MantidWidgets::FitPropertyBrowser::setCentre (double value)
Set centre of the current peak.
Parameters
value :: The new centre value
Definition at line 1525 of file FitPropertyBrowser.cpp.
References Mantid::API::FunctionHandler::function(), m_currentHandler, parameterChanged(), MantidQt::MantidWidgets::PropertyHandler::setCentre(), MantidQt::MantidWidgets::PropertyHandler::updateParameters(), and value.
setCurrentFunction() [1/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::setCurrentFunction (const Mantid::API::IFunction_const_sptr & f) const private
Set new current function.
Parameters
f :: New current function
Definition at line 1591 of file FitPropertyBrowser.cpp.
References getHandler(), and setCurrentFunction().
setCurrentFunction() [2/2]
void MantidQt::MantidWidgets::FitPropertyBrowser::setCurrentFunction (PropertyHandler * h) const
Set new current function.
Parameters
h :: New current function
Definition at line 1580 of file FitPropertyBrowser.cpp.
References currentChanged(), MantidQt::MantidWidgets::PropertyHandler::item(), m_browser, and m_currentHandler.
Referenced by addAutoBackground(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), createCompositeFunction(), enumChanged(), and setCurrentFunction().
setDecimals()
void MantidQt::MantidWidgets::FitPropertyBrowser::setDecimals (int d)
Definition at line 2798 of file FitPropertyBrowser.cpp.
References Mantid::Geometry::d, m_decimals, and updateDecimals().
setDefaultBackgroundType()
void MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultBackgroundType (const std::string & fnType)
Set the default background type.
Definition at line 1069 of file FitPropertyBrowser.cpp.
References m_defaultBackground, and setDefaultFunctionType().
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), and MantidQt::MantidWidgets::PropertyHandler::changeType().
setDefaultFunctionType()
void MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultFunctionType (const std::string & fnType)
Set the default function type.
Definition at line 1050 of file FitPropertyBrowser.cpp.
References m_defaultFunction.
Referenced by setDefaultBackgroundType(), and setDefaultPeakType().
setDefaultPeakType()
void MantidQt::MantidWidgets::FitPropertyBrowser::setDefaultPeakType (const std::string & fnType)
Set the default peak type.
Definition at line 1062 of file FitPropertyBrowser.cpp.
References m_defaultPeak, and setDefaultFunctionType().
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::changeType(), and defaultPeakType().
setEndX()
void MantidQt::MantidWidgets::FitPropertyBrowser::setEndX (double end) override virtual
Set the end X.
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Definition at line 1929 of file FitPropertyBrowser.cpp.
References m_doubleManager, m_endX, and value.
Referenced by setWorkspaceName().
setFitEnabled()
void MantidQt::MantidWidgets::FitPropertyBrowser::setFitEnabled (bool enable) virtual
Enable/disable the Fit buttons;.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 2138 of file FitPropertyBrowser.cpp.
References m_fitActionFit, and m_fitActionSeqFit.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), createCompositeFunction(), and MantidQt::MantidWidgets::PropertyHandler::removeFunction().
setFwhm()
void MantidQt::MantidWidgets::FitPropertyBrowser::setFwhm (double value)
Set width of the current peak.
Parameters
value :: The new width value
Definition at line 1563 of file FitPropertyBrowser.cpp.
References Mantid::API::FunctionHandler::function(), m_currentHandler, parameterChanged(), MantidQt::MantidWidgets::PropertyHandler::setFwhm(), MantidQt::MantidWidgets::PropertyHandler::updateParameters(), and value.
setHeight()
void MantidQt::MantidWidgets::FitPropertyBrowser::setHeight (double value)
Set height of the current peak.
Parameters
value :: The new height value
Definition at line 1544 of file FitPropertyBrowser.cpp.
References Mantid::API::FunctionHandler::function(), m_currentHandler, parameterChanged(), MantidQt::MantidWidgets::PropertyHandler::setHeight(), MantidQt::MantidWidgets::PropertyHandler::updateParameters(), and value.
setIgnoreInvalidData()
void MantidQt::MantidWidgets::FitPropertyBrowser::setIgnoreInvalidData (bool on)
Set the ignore invalid data option.
Definition at line 1179 of file FitPropertyBrowser.cpp.
References m_boolManager, and m_ignoreInvalidData.
Referenced by init().
setOutputName()
void MantidQt::MantidWidgets::FitPropertyBrowser::setOutputName (const std::string & name)
Set the output name.
Definition at line 1140 of file FitPropertyBrowser.cpp.
References m_output, m_stringManager, and name.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), and stringChanged().
setPeakCentreOf()
void MantidQt::MantidWidgets::FitPropertyBrowser::setPeakCentreOf (const QString & prefix, double value)
Definition at line 3330 of file FitPropertyBrowser.cpp.
References getPeakHandler(), and value.
setPeakFwhmOf()
void MantidQt::MantidWidgets::FitPropertyBrowser::setPeakFwhmOf (const QString & prefix, double value)
Definition at line 3352 of file FitPropertyBrowser.cpp.
References getPeakHandler(), and value.
setPeakHeightOf()
void MantidQt::MantidWidgets::FitPropertyBrowser::setPeakHeightOf (const QString & prefix, double value)
Definition at line 3341 of file FitPropertyBrowser.cpp.
References getPeakHandler(), and value.
setPeakToolOn
void MantidQt::MantidWidgets::FitPropertyBrowser::setPeakToolOn (bool on) slot
Definition at line 2778 of file FitPropertyBrowser.cpp.
References m_displayActionPlotGuess, and m_peakToolOn.
setStartX()
void MantidQt::MantidWidgets::FitPropertyBrowser::setStartX (double start) override virtual
Set the start X.
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Definition at line 1923 of file FitPropertyBrowser.cpp.
References m_doubleManager, m_startX, and value.
Referenced by setWorkspaceName().
setStringPropertyValue()
void MantidQt::MantidWidgets::FitPropertyBrowser::setStringPropertyValue (QtProperty * prop, const QString & value) const private
Set a value to a string property.
Parameters
prop :: A pointer to the property
value :: New value for the property
Definition at line 2505 of file FitPropertyBrowser.cpp.
References value.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), and MantidQt::MantidWidgets::SetAttributeProperty::apply().
setTextPlotGuess()
void MantidQt::MantidWidgets::FitPropertyBrowser::setTextPlotGuess (const QString & text)
alter text of Plot Guess
Definition at line 2813 of file FitPropertyBrowser.cpp.
References m_displayActionPlotGuess.
setTip()
void MantidQt::MantidWidgets::FitPropertyBrowser::setTip (const QString & txt)
Display a tip.
Parameters
txt :: The text to display
Definition at line 2336 of file FitPropertyBrowser.cpp.
References m_tip.
setupMultifit
void MantidQt::MantidWidgets::FitPropertyBrowser::setupMultifit () private slot
Call MultifitSetupDialog to populate MultiBG function.
Definition at line 2835 of file FitPropertyBrowser.cpp.
References endX(), getFunctionAtIndex(), loadFunction(), startX(), and workspaceName().
Referenced by popupMenu().
setWorkspace()
void MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspace (const Mantid::API::IFunction_sptr & function) const protected
Sets the workspace to a function.
Definition at line 2641 of file FitPropertyBrowser.cpp.
References endX(), startX(), workspaceIndex(), and workspaceName().
Referenced by MantidQt::MantidWidgets::PropertyHandler::addFunction(), createCompositeFunction(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), and setXRange().
setWorkspaceIndex()
void MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspaceIndex (int i) override virtual
Set workspace index.
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Definition at line 1127 of file FitPropertyBrowser.cpp.
References getAllowedIndex(), index, m_intManager, and m_workspaceIndex.
Referenced by intChanged(), populateWorkspaceNames(), setWorkspaceName(), and setWorkspaceProperties().
setWorkspaceName()
void MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspaceName (const QString & wsName) override virtual
Set the input workspace name.
Implements MantidQt::MantidWidgets::IWorkspaceFitControl.
Reimplemented in MantidQt::MantidWidgets::MuonFitPropertyBrowser.
Definition at line 1096 of file FitPropertyBrowser.cpp.
References m_enumManager, m_workspace, m_workspaceNames, populateWorkspaceNames(), setEndX(), setStartX(), setWorkspaceIndex(), and workspaceIndex().
setWorkspaceProperties()
void MantidQt::MantidWidgets::FitPropertyBrowser::setWorkspaceProperties () protected
Display properties relevant to the selected workspace.
Display properties relevant to the selected workspace: WorkspaceIndex, StartX, and EndX for a MatrixWorkspace; XColumn, YColumn, and ErrColumn for a TableWorkspace.
Definition at line 2944 of file FitPropertyBrowser.cpp.
References addWorkspaceIndexToBrowser(), m_browser, m_columnManager, m_customSettingsGroup, m_errColumn, m_evaluationType, m_settingsGroup, m_storedWorkspaceName, m_workspace, m_workspaceIndex, m_xColumn, m_yColumn, name, setWorkspaceIndex(), workspaceName(), and Mantid::Geometry::x.
Referenced by enumChanged().
setXRange()
void MantidQt::MantidWidgets::FitPropertyBrowser::setXRange (double start, double end)
Set both start and end X.
Definition at line 1931 of file FitPropertyBrowser.cpp.
References doubleChanged(), getHandler(), m_compositeFunction, m_doubleManager, m_endX, m_startX, MantidQt::MantidWidgets::PropertyHandler::setAttribute(), and setWorkspace().
showEvent()
void MantidQt::MantidWidgets::FitPropertyBrowser::showEvent (QShowEvent * e) override protected
actions to do before the browser made visible
Connect to the AnalysisDataService when shown.
Definition at line 1786 of file FitPropertyBrowser.cpp.
References populateWorkspaceNames(), and setADSObserveEnabled().
showFitResultStatus
void MantidQt::MantidWidgets::FitPropertyBrowser::showFitResultStatus (const QString & status) private slot
Display the status string returned from Fit.
Parameters
status :: A status string as returned by OutputStatus Fit property.
Definition at line 1738 of file FitPropertyBrowser.cpp.
References m_status.
Referenced by initBasicLayout().
sizeOfFunctionsGroup()
int MantidQt::MantidWidgets::FitPropertyBrowser::sizeOfFunctionsGroup () const
Definition at line 3244 of file FitPropertyBrowser.cpp.
startX()
double MantidQt::MantidWidgets::FitPropertyBrowser::startX () const
Get the start X.
Definition at line 1920 of file FitPropertyBrowser.cpp.
References m_doubleManager, and m_startX.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::centre(), MantidQt::MantidWidgets::PropertyHandler::changeType(), createAndAddFunction(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), MantidQt::MantidWidgets::PropertyHandler::EstimateFwhm(), findPeaks(), MantidQt::MantidWidgets::PropertyHandler::fit(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), setupMultifit(), and setWorkspace().
startXChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::startXChanged (double) signal
Referenced by doubleChanged(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged().
stringChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged (QtProperty * prop) private slot
Called when a string property changed.
Parameters
prop :: A pointer to the property
Definition at line 1433 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::addTie(), compositeFunction(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), functionChanged(), MantidQt::MantidWidgets::PropertyHandler::functionPrefix(), getHandler(), getOldExpressionAsString(), MantidQt::MantidWidgets::PropertyHandler::getParameterProperty(), m_changeSlotsEnabled, m_guessOutputName, m_output, m_stringManager, outputName(), setOutputName(), and workspaceName().
Referenced by initBasicLayout().
theFunction()
Mantid::API::IFunction_const_sptr MantidQt::MantidWidgets::FitPropertyBrowser::theFunction () const
Get the current function.
Definition at line 2520 of file FitPropertyBrowser.cpp.
References m_compositeFunction.
Referenced by copy(), getParameterNames(), getParameterValues(), reset(), and saveFunction().
toggleSettingsBrowserVisible
void MantidQt::MantidWidgets::FitPropertyBrowser::toggleSettingsBrowserVisible () virtual slot
Function to toggle the visibility of the settings browser.
Definition at line 3061 of file FitPropertyBrowser.cpp.
References m_browser, and m_settingsGroup.
toggleWsListVisible
void MantidQt::MantidWidgets::FitPropertyBrowser::toggleWsListVisible () virtual slot
Definition at line 3083 of file FitPropertyBrowser.cpp.
References m_hideWsListWidget.
tryCreateFitFunction()
Mantid::API::IFunction_sptr MantidQt::MantidWidgets::FitPropertyBrowser::tryCreateFitFunction (const QString & str) protected
Catches unexpected not found exceptions.
Definition at line 812 of file FitPropertyBrowser.cpp.
Referenced by createCompositeFunction().
undoFit
void MantidQt::MantidWidgets::FitPropertyBrowser::undoFit () slot
Slot.
Undoes the fit: restores the parameters to their initial values.
Definition at line 2113 of file FitPropertyBrowser.cpp.
References MantidQt::MantidWidgets::PropertyHandler::clearErrors(), clearFitResultStatus(), compositeFunction(), disableUndo(), fitUndone(), getHandler(), m_initialParameters, and updateParameters().
Referenced by executeFitMenu(), and popupMenu().
updateAttributes()
void MantidQt::MantidWidgets::FitPropertyBrowser::updateAttributes ()
Update the function attributes.
Update the function attributes which have changed.
Definition at line 2081 of file FitPropertyBrowser.cpp.
References getHandler(), and MantidQt::MantidWidgets::PropertyHandler::updateAttributes().
updateBrowserFromFitResults()
void MantidQt::MantidWidgets::FitPropertyBrowser::updateBrowserFromFitResults (const Mantid::API::IFunction_sptr & finalFunction) protected
Set the parameters to the fit outcome.
Definition at line 2101 of file FitPropertyBrowser.cpp.
References compositeFunction(), getHandler(), MantidQt::MantidWidgets::PropertyHandler::updateErrors(), and updateParameters().
Referenced by finishHandle().
updateDecimals()
void MantidQt::MantidWidgets::FitPropertyBrowser::updateDecimals () protected
impose a number of decimal places on all defined Double properties
Definition at line 2786 of file FitPropertyBrowser.cpp.
References m_decimals, and m_doubleManager.
Referenced by init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and setDecimals().
updateParameters()
void MantidQt::MantidWidgets::FitPropertyBrowser::updateParameters ()
Update the function parameters.
Update the function parameter properties.
Definition at line 2076 of file FitPropertyBrowser.cpp.
References getHandler(), and MantidQt::MantidWidgets::PropertyHandler::updateParameters().
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), undoFit(), and updateBrowserFromFitResults().
updatePlotSpectrum
void MantidQt::MantidWidgets::FitPropertyBrowser::updatePlotSpectrum (int index) signal
Referenced by intChanged().
updateSetupMenus()
void MantidQt::MantidWidgets::FitPropertyBrowser::updateSetupMenus () private
Update setup menus according to how these are set in settings.
Definition at line 578 of file FitPropertyBrowser.cpp.
References executeCustomSetupLoad(), executeCustomSetupRemove(), m_setupActionCustomSetup, and m_setupActionRemove.
Referenced by executeClearCustomSetups(), executeCustomSetupRemove(), initBasicLayout(), and saveFunction().
updateStructureTooltips
void MantidQt::MantidWidgets::FitPropertyBrowser::updateStructureTooltips () private slot
Update structure tooltips for all functions.
Recursively updates structure tooltips for all the functions.
Definition at line 635 of file FitPropertyBrowser.cpp.
References getHandler(), and MantidQt::MantidWidgets::PropertyHandler::updateStructureTooltip().
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and initBasicLayout().
vectorDoubleChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::vectorDoubleChanged (QtProperty * prop) private slot
Slot.
Responds to changing a vector attribute member
Parameters
prop :: A property managed by m_vectorDoubleManager.
Definition at line 2055 of file FitPropertyBrowser.cpp.
References enactAttributeChange(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), and getHandler().
Referenced by initBasicLayout().
vectorSizeChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::vectorSizeChanged (QtProperty * prop) private slot
Slot.
Responds to changing a vector attribute size
Parameters
prop :: A property managed by m_vectorSizeManager.
Definition at line 2066 of file FitPropertyBrowser.cpp.
References enactAttributeChange(), MantidQt::MantidWidgets::PropertyHandler::findHandler(), and getHandler().
Referenced by initBasicLayout().
workspaceChange()
void MantidQt::MantidWidgets::FitPropertyBrowser::workspaceChange (const QString & wsName) private virtual
Sets the new workspace to the current one.
Sets a new workspace.
Definition at line 2818 of file FitPropertyBrowser.cpp.
References m_guessOutputName, m_output, m_stringManager, workspaceName(), workspaceNameChanged(), and wsChangePPAssign().
Referenced by enumChanged(), and renameHandle().
workspaceClicked
void MantidQt::MantidWidgets::FitPropertyBrowser::workspaceClicked (const QString & wsName) signal
Referenced by workspaceDoubleClicked().
workspaceDoubleClicked
void MantidQt::MantidWidgets::FitPropertyBrowser::workspaceDoubleClicked (QListWidgetItem * item) slot
Definition at line 541 of file FitPropertyBrowser.cpp.
References workspaceClicked().
Referenced by initBasicLayout().
workspaceIndex()
int MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndex () const
Get workspace index.
Definition at line 1124 of file FitPropertyBrowser.cpp.
References m_intManager, and m_workspaceIndex.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::SequentialFitDialog::addWorkspaces(), MantidQt::MantidWidgets::PropertyHandler::calcBase(), MantidQt::MantidWidgets::PropertyHandler::changeType(), createAndAddFunction(), doFit(), MantidQt::MantidWidgets::PropertyHandler::EstimateFwhm(), findPeaks(), MantidQt::MantidWidgets::PropertyHandler::fit(), MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), getXRange(), intChanged(), MantidQt::MantidWidgets::PropertyHandler::setCentre(), setWorkspace(), and setWorkspaceName().
workspaceIndexChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::workspaceIndexChanged (int index) signal
Referenced by intChanged().
workspaceName()
std::string MantidQt::MantidWidgets::FitPropertyBrowser::workspaceName () const
Get the input workspace name.
Definition at line 1086 of file FitPropertyBrowser.cpp.
References m_enumManager, m_workspace, and m_workspaceNames.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), addHandle(), MantidQt::MantidWidgets::PropertyHandler::changeType(), columnChanged(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), enumChanged(), findPeaks(), MantidQt::MantidWidgets::PropertyHandler::fit(), getAllowedIndex(), MantidQt::MantidWidgets::SequentialFitDialog::getFitResults(), getWorkspace(), popupMenu(), processMultiBGResults(), removeWorkspace(), sequentialFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization(), setupMultifit(), setWorkspace(), setWorkspaceProperties(), stringChanged(), and workspaceChange().
workspaceNameChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::workspaceNameChanged (const QString &) signal
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), and workspaceChange().
wsChangePPAssign
void MantidQt::MantidWidgets::FitPropertyBrowser::wsChangePPAssign (const QString &) signal
Referenced by workspaceChange().
xRangeChanged
void MantidQt::MantidWidgets::FitPropertyBrowser::xRangeChanged (double , double) signal
Referenced by doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), and init().
Friends And Related Symbol Documentation
CreateAttributeProperty
friend class CreateAttributeProperty friend
Definition at line 702 of file FitPropertyBrowser.h.
PropertyHandler
friend class PropertyHandler friend
Definition at line 701 of file FitPropertyBrowser.h.
SequentialFitDialog
friend class SequentialFitDialog friend
Definition at line 705 of file FitPropertyBrowser.h.
Referenced by sequentialFit().
SetAttribute
friend class SetAttribute friend
Definition at line 703 of file FitPropertyBrowser.h.
SetAttributeProperty
friend class SetAttributeProperty friend
Definition at line 704 of file FitPropertyBrowser.h.
Member Data Documentation
m_allowedSpectra
QMap<QString, QList<int> > MantidQt::MantidWidgets::FitPropertyBrowser::m_allowedSpectra private
If non-empty it contains references to the spectra allowed to be fitted in this browser: keys are workspace names, values are lists of workspace indices.
Definition at line 695 of file FitPropertyBrowser.h.
Referenced by addAllowedSpectra(), addHandle(), getAllowedIndex(), populateWorkspaceNames(), removeWorkspaceAndSpectra(), and renameHandle().
m_allowedTableWorkspace
QString MantidQt::MantidWidgets::FitPropertyBrowser::m_allowedTableWorkspace private
If set it contains the table workspace name to be fitted in this browser:
Definition at line 697 of file FitPropertyBrowser.h.
Referenced by addAllowedTableWorkspace(), addHandle(), and populateWorkspaceNames().
m_auto_back
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_auto_back private
If true background function will be included automatically.
Definition at line 664 of file FitPropertyBrowser.h.
Referenced by createCompositeFunction(), loadFunction(), and setAutoBackgroundName().
m_autoBackground
PropertyHandler* MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBackground private
The autobackground handler.
Definition at line 673 of file FitPropertyBrowser.h.
Referenced by addAutoBackground(), MantidQt::MantidWidgets::PropertyHandler::calcBase(), MantidQt::MantidWidgets::PropertyHandler::calcBaseAll(), MantidQt::MantidWidgets::PropertyHandler::changeType(), createCompositeFunction(), refitAutoBackground(), MantidQt::MantidWidgets::PropertyHandler::removeFunction(), and MantidQt::MantidWidgets::PropertyHandler::setAttribute().
m_autoBgAttributes
QString MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBgAttributes private
List of attributes of the autobackground function as name=value pairs separated by spaces.
Definition at line 670 of file FitPropertyBrowser.h.
Referenced by addAutoBackground(), and setAutoBackgroundName().
m_autoBgName
QString MantidQt::MantidWidgets::FitPropertyBrowser::m_autoBgName private
Name of the autobackground function.
Definition at line 667 of file FitPropertyBrowser.h.
Referenced by addAutoBackground(), FitPropertyBrowser(), and setAutoBackgroundName().
m_boolManager
QtBoolPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_boolManager protected
Definition at line 498 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::SetAttribute::apply(), MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), boolChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), convolveMembers(), createEditors(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::executeFitMenu(), FitPropertyBrowser(), ignoreInvalidData(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), initBasicLayout(), minimizer(), minimizerChanged(), plotCompositeMembers(), plotDiff(), rawData(), setIgnoreInvalidData(), and ~FitPropertyBrowser().
m_browser
QtTreePropertyBrowser* MantidQt::MantidWidgets::FitPropertyBrowser::m_browser protected
Definition at line 533 of file FitPropertyBrowser.h.
Referenced by acceptFit(), addConstraint(), addFixTie(), addFunction(), addTie(), addTieToFunction(), addWorkspaceIndexToBrowser(), createEditors(), deleteFunction(), deleteTie(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), MantidQt::MantidWidgets::PropertyHandler::init(), initBasicLayout(), popupMenu(), removeBounds(), setCurrentFunction(), setWorkspaceProperties(), toggleSettingsBrowserVisible(), and ~FitPropertyBrowser().
m_changeSlotsEnabled
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_changeSlotsEnabled protected
If false the change-slots (such as enumChanged(), doubleChanged()) are disabled.
Definition at line 549 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addConstraint(), MantidQt::MantidWidgets::PropertyHandler::addFunction(), MantidQt::MantidWidgets::PropertyHandler::addTie(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), boolChanged(), MantidQt::MantidWidgets::PropertyHandler::changeType(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), enumChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), filenameChanged(), MantidQt::MantidWidgets::PropertyHandler::init(), initBasicLayout(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), intChanged(), parameterChanged(), MantidQt::MantidWidgets::PropertyHandler::removeTie(), MantidQt::MantidWidgets::PropertyHandler::removeTie(), MantidQt::MantidWidgets::PropertyHandler::renameChildren(), and stringChanged().
m_columnManager
QtEnumPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_columnManager protected
Definition at line 502 of file FitPropertyBrowser.h.
Referenced by columnChanged(), createEditors(), FitPropertyBrowser(), getErrColumnName(), getXColumnName(), getXRange(), getYColumnName(), init(), initBasicLayout(), setWorkspaceProperties(), and ~FitPropertyBrowser().
m_compositeFunction
std::shared_ptr<Mantid::API::CompositeFunction> MantidQt::MantidWidgets::FitPropertyBrowser::m_compositeFunction protected
A copy of the edited function.
Definition at line 531 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::SequentialFitDialog::accept(), addTieToFunction(), allowSequentialFits(), count(), createCompositeFunction(), deleteTie(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), enumChanged(), finishHandle(), getFittingFunction(), getFunctionAtIndex(), getHandler(), intChanged(), MantidQt::MantidWidgets::SequentialFitDialog::populateParameters(), popupMenu(), setXRange(), theFunction(), and ~FitPropertyBrowser().
m_convolveMembers
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_convolveMembers protected
Definition at line 521 of file FitPropertyBrowser.h.
Referenced by convolveMembers(), and init().
m_costFunction
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_costFunction protected
Definition at line 515 of file FitPropertyBrowser.h.
Referenced by costFunction(), init(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
m_costFunctions
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_costFunctions mutable protected
A list of available cost functions.
Definition at line 567 of file FitPropertyBrowser.h.
Referenced by costFunction(), init(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
m_currentHandler
PropertyHandler* MantidQt::MantidWidgets::FitPropertyBrowser::m_currentHandler mutable private
Definition at line 645 of file FitPropertyBrowser.h.
Referenced by centre(), currentHandler(), currentItemChanged(), fwhm(), height(), isPeak(), setCentre(), setCurrentFunction(), setFwhm(), and setHeight().
m_customSettingsGroup
QtBrowserItem* MantidQt::MantidWidgets::FitPropertyBrowser::m_customSettingsGroup protected
Group for custom options available on muon analysis widget.
Definition at line 545 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and setWorkspaceProperties().
m_dataTypes
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_dataTypes mutable private
A list of available data types.
Definition at line 648 of file FitPropertyBrowser.h.
m_decimals
int MantidQt::MantidWidgets::FitPropertyBrowser::m_decimals private
Number of decimal places in double properties.
Definition at line 676 of file FitPropertyBrowser.h.
Referenced by addDoubleProperty(), setDecimals(), and updateDecimals().
m_defaultBackground
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_defaultBackground private
Default background name.
Definition at line 655 of file FitPropertyBrowser.h.
Referenced by defaultBackgroundType(), FitPropertyBrowser(), and setDefaultBackgroundType().
m_defaultFunction
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_defaultFunction private
Default function name.
Definition at line 651 of file FitPropertyBrowser.h.
Referenced by defaultFunctionType(), FitPropertyBrowser(), and setDefaultFunctionType().
m_defaultPeak
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_defaultPeak private
Default peak name.
Definition at line 653 of file FitPropertyBrowser.h.
Referenced by defaultPeakType(), FitPropertyBrowser(), and setDefaultPeakType().
m_displayActionClearAll
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_displayActionClearAll private
Definition at line 618 of file FitPropertyBrowser.h.
Referenced by initBasicLayout().
m_displayActionPlotGuess
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_displayActionPlotGuess private
Definition at line 616 of file FitPropertyBrowser.h.
Referenced by initBasicLayout(), setPeakToolOn(), and setTextPlotGuess().
m_displayActionQuality
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_displayActionQuality private
Definition at line 617 of file FitPropertyBrowser.h.
Referenced by finishHandle(), and initBasicLayout().
m_doubleManager
QtDoublePropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_doubleManager protected
Definition at line 495 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::PropertyHandler::addConstraint(), addDoubleProperty(), MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttribute::apply(), columnChanged(), createEditors(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), endX(), FitPropertyBrowser(), initBasicLayout(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), minimizer(), minimizerChanged(), setEndX(), setStartX(), setXRange(), startX(), updateDecimals(), and ~FitPropertyBrowser().
m_endX
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_endX protected
Definition at line 511 of file FitPropertyBrowser.h.
Referenced by columnChanged(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), endX(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), setEndX(), and setXRange().
m_enumManager
QtEnumPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_enumManager protected
Definition at line 496 of file FitPropertyBrowser.h.
Referenced by addHandle(), addStringListProperty(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), MantidQt::MantidWidgets::PropertyHandler::changeType(), costFunction(), createEditors(), enumChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), FitPropertyBrowser(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), MantidQt::MantidWidgets::PropertyHandler::init(), initBasicLayout(), isHistogramFit(), minimizer(), populateWorkspaceNames(), removeWorkspace(), renameHandle(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setNormalization(), setWorkspaceName(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceName(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::updateGroupDisplay(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::updatePeriodDisplay(), MantidQt::MantidWidgets::PropertyHandler::updateWorkspaces(), workspaceName(), and ~FitPropertyBrowser().
m_errColumn
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_errColumn protected
Definition at line 525 of file FitPropertyBrowser.h.
Referenced by getErrColumnName(), init(), and setWorkspaceProperties().
m_evaluationType
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_evaluationType protected
Definition at line 527 of file FitPropertyBrowser.h.
Referenced by enumChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), isHistogramFit(), and setWorkspaceProperties().
m_evaluationTypes
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_evaluationTypes mutable protected
A list of possible function evaluation types.
Definition at line 569 of file FitPropertyBrowser.h.
Referenced by init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and isHistogramFit().
m_excludeRange
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_excludeRange protected
Definition at line 519 of file FitPropertyBrowser.h.
Referenced by getExcludeRange(), and init().
m_filenameManager
QtStringPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_filenameManager protected
Definition at line 500 of file FitPropertyBrowser.h.
Referenced by addStringProperty(), createEditors(), FitPropertyBrowser(), initBasicLayout(), and ~FitPropertyBrowser().
m_fitActionEvaluate
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionEvaluate protected
Definition at line 538 of file FitPropertyBrowser.h.
Referenced by populateFitMenuButton().
m_fitActionFit
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionFit protected
Definition at line 537 of file FitPropertyBrowser.h.
Referenced by isFitEnabled(), populateFitMenuButton(), setFitEnabled(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::setFitEnabled().
m_fitActionSeqFit
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionSeqFit protected
Definition at line 536 of file FitPropertyBrowser.h.
Referenced by allowSequentialFits(), populateFitMenuButton(), setFitEnabled(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::setFitEnabled().
m_fitActionUndoFit
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitActionUndoFit protected
Definition at line 535 of file FitPropertyBrowser.h.
Referenced by disableUndo(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), and populateFitMenuButton().
m_fitAlgOutputStatus
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_fitAlgOutputStatus private
Definition at line 689 of file FitPropertyBrowser.h.
Referenced by finishHandle(), and getFitAlgorithmOutputStatus().
m_fitAlgParameters
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_fitAlgParameters private
Definition at line 688 of file FitPropertyBrowser.h.
Referenced by doFit(), and getFitAlgorithmParameters().
m_fitMapper
QSignalMapper* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitMapper private
Make sure m_groupMember belongs to the group.
Fit and Display menu
Definition at line 614 of file FitPropertyBrowser.h.
Referenced by createFitMenuButton().
m_fitMenu
QMenu* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitMenu private
Definition at line 615 of file FitPropertyBrowser.h.
Referenced by createFitMenuButton(), and modifyFitMenu().
m_fitSelector
SelectFunctionDialog* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitSelector private
Definition at line 632 of file FitPropertyBrowser.h.
Referenced by acceptFit(), addFunction(), and closeFit().
m_fitTree
QTreeWidget* MantidQt::MantidWidgets::FitPropertyBrowser::m_fitTree private
Definition at line 634 of file FitPropertyBrowser.h.
m_formulaManager
QtStringPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_formulaManager protected
Definition at line 501 of file FitPropertyBrowser.h.
Referenced by addStringProperty(), createEditors(), FitPropertyBrowser(), initBasicLayout(), and ~FitPropertyBrowser().
m_functionsGroup
QtBrowserItem* MantidQt::MantidWidgets::FitPropertyBrowser::m_functionsGroup protected
Group for functions.
Definition at line 541 of file FitPropertyBrowser.h.
Referenced by clearBrowser(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), MantidQt::MantidWidgets::PropertyHandler::init(), and popupMenu().
m_groupManager
QtGroupPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_groupManager protected
Property managers:
Definition at line 494 of file FitPropertyBrowser.h.
Referenced by FitPropertyBrowser(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), MantidQt::MantidWidgets::PropertyHandler::init(), and initBasicLayout().
m_guessOutputName
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_guessOutputName protected
if true the output name will be guessed every time workspace name is changeed
Definition at line 552 of file FitPropertyBrowser.h.
Referenced by stringChanged(), and workspaceChange().
m_hideWsListWidget
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_hideWsListWidget private
bool to display ws list or not
Definition at line 661 of file FitPropertyBrowser.h.
Referenced by addFitResultWorkspacesToTableWidget(), and toggleWsListVisible().
m_ignoreInvalidData
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_ignoreInvalidData protected
Definition at line 514 of file FitPropertyBrowser.h.
Referenced by boolChanged(), ignoreInvalidData(), init(), and setIgnoreInvalidData().
m_initialParameters
std::vector<double> MantidQt::MantidWidgets::FitPropertyBrowser::m_initialParameters protected
To keep a copy of the initial parameters in case for undo fit.
Definition at line 572 of file FitPropertyBrowser.h.
Referenced by disableUndo(), doFit(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doTFAsymmFit(), isUndoEnabled(), and undoFit().
m_intManager
QtIntPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_intManager protected
Definition at line 497 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttribute::apply(), createEditors(), fit(), FitPropertyBrowser(), getPeakRadius(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), initBasicLayout(), intChanged(), maxIterations(), minimizer(), minimizerChanged(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), setWorkspaceIndex(), workspaceIndex(), and ~FitPropertyBrowser().
m_mantidui
QObject* MantidQt::MantidWidgets::FitPropertyBrowser::m_mantidui private
holds effectively a MantidUI for connecting
Definition at line 679 of file FitPropertyBrowser.h.
Referenced by init(), and sequentialFit().
m_maxIterations
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_maxIterations protected
Definition at line 516 of file FitPropertyBrowser.h.
Referenced by fit(), init(), intChanged(), and maxIterations().
m_minimizer
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_minimizer protected
Definition at line 513 of file FitPropertyBrowser.h.
Referenced by enumChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and minimizer().
m_minimizerProperties
QList<QtProperty *> MantidQt::MantidWidgets::FitPropertyBrowser::m_minimizerProperties protected
Definition at line 528 of file FitPropertyBrowser.h.
Referenced by minimizer(), and minimizerChanged().
m_minimizers
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_minimizers mutable protected
A list of available minimizers.
Definition at line 563 of file FitPropertyBrowser.h.
Referenced by init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and minimizer().
m_oldWorkspaceIndex
int MantidQt::MantidWidgets::FitPropertyBrowser::m_oldWorkspaceIndex private
Store workspace index to revert to in case validation fails.
Definition at line 699 of file FitPropertyBrowser.h.
Referenced by getAllowedIndex(), and intChanged().
m_output
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_output protected
Definition at line 512 of file FitPropertyBrowser.h.
Referenced by init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), outputName(), setOutputName(), stringChanged(), and workspaceChange().
m_parameterManager
ParameterPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_parameterManager protected
Definition at line 506 of file FitPropertyBrowser.h.
Referenced by boolChanged(), MantidQt::MantidWidgets::PropertyHandler::clearError(), createEditors(), FitPropertyBrowser(), MantidQt::MantidWidgets::PropertyHandler::fix(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), initBasicLayout(), MantidQt::MantidWidgets::PropertyHandler::initParameters(), MantidQt::MantidWidgets::PropertyHandler::setParameter(), MantidQt::MantidWidgets::PropertyHandler::updateError(), MantidQt::MantidWidgets::PropertyHandler::updateParameter(), and ~FitPropertyBrowser().
m_peakRadius
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_peakRadius protected
Definition at line 517 of file FitPropertyBrowser.h.
Referenced by getPeakRadius(), init(), and intChanged().
m_peakToolOn
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_peakToolOn private
Shows if the PeakPickerTool is on.
Definition at line 658 of file FitPropertyBrowser.h.
Referenced by popupMenu(), and setPeakToolOn().
m_plotCompositeMembers
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_plotCompositeMembers protected
Definition at line 520 of file FitPropertyBrowser.h.
Referenced by boolChanged(), init(), and plotCompositeMembers().
m_plotDiff
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_plotDiff protected
Definition at line 518 of file FitPropertyBrowser.h.
Referenced by boolChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and plotDiff().
m_rawData
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_rawData protected
Definition at line 522 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), and rawData().
m_registeredBackgrounds
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredBackgrounds mutable protected
A list of registered backgrounds.
Definition at line 559 of file FitPropertyBrowser.h.
Referenced by populateFunctionNames(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::populateFunctionNames().
m_registeredFunctions
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredFunctions mutable protected
A list of registered functions.
Definition at line 555 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::PropertyHandler::init(), populateFunctionNames(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::populateFunctionNames().
m_registeredOther
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredOther mutable protected
A list of registered functions that are neither peaks nor backgrounds.
Definition at line 561 of file FitPropertyBrowser.h.
Referenced by populateFunctionNames(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::populateFunctionNames().
m_registeredPeaks
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_registeredPeaks mutable protected
A list of registered peaks.
Definition at line 557 of file FitPropertyBrowser.h.
Referenced by defaultPeakType(), populateFunctionNames(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::populateFunctionNames().
m_settingsGroup
QtBrowserItem* MantidQt::MantidWidgets::FitPropertyBrowser::m_settingsGroup protected
Group for input/output settings.
Definition at line 543 of file FitPropertyBrowser.h.
Referenced by addWorkspaceIndexToBrowser(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), minimizerChanged(), popupMenu(), removePropertiesFromSettingsBrowser(), setWorkspaceProperties(), and toggleSettingsBrowserVisible().
m_setupActionCustomSetup
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_setupActionCustomSetup private
Setup menu.
Definition at line 622 of file FitPropertyBrowser.h.
Referenced by initBasicLayout(), and updateSetupMenus().
m_setupActionRemove
QAction* MantidQt::MantidWidgets::FitPropertyBrowser::m_setupActionRemove private
Definition at line 623 of file FitPropertyBrowser.h.
Referenced by initBasicLayout(), and updateSetupMenus().
m_shouldBeNormalised
bool MantidQt::MantidWidgets::FitPropertyBrowser::m_shouldBeNormalised private
Should the data be normalised before fitting?
Definition at line 685 of file FitPropertyBrowser.h.
Referenced by doFit().
m_showParamErrors
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_showParamErrors protected
Definition at line 526 of file FitPropertyBrowser.h.
Referenced by boolChanged(), init(), and MantidQt::MantidWidgets::MuonFitPropertyBrowser::init().
m_startX
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_startX protected
Definition at line 510 of file FitPropertyBrowser.h.
Referenced by columnChanged(), doubleChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::doubleChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), setStartX(), setXRange(), and startX().
m_status
QLabel* MantidQt::MantidWidgets::FitPropertyBrowser::m_status private
To display fit status.
Definition at line 629 of file FitPropertyBrowser.h.
Referenced by clearFitResultStatus(), initBasicLayout(), and showFitResultStatus().
m_storedWorkspaceName
std::string MantidQt::MantidWidgets::FitPropertyBrowser::m_storedWorkspaceName private
store current workspace name
Definition at line 682 of file FitPropertyBrowser.h.
Referenced by enumChanged(), and setWorkspaceProperties().
m_stringManager
QtStringPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManager protected
Definition at line 499 of file FitPropertyBrowser.h.
Referenced by addStringProperty(), MantidQt::MantidWidgets::PropertyHandler::addTie(), createEditors(), FitPropertyBrowser(), getExcludeRange(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), initBasicLayout(), minimizer(), minimizerChanged(), outputName(), MantidQt::MantidWidgets::PropertyHandler::renameChildren(), setOutputName(), stringChanged(), workspaceChange(), and ~FitPropertyBrowser().
m_stringManagers
QMap<QString, QtStringPropertyManager *> MantidQt::MantidWidgets::FitPropertyBrowser::m_stringManagers private
String property managers for special case attributes such as Filename or Formula <attribute_name,string_manager>
Definition at line 643 of file FitPropertyBrowser.h.
m_tip
QLabel* MantidQt::MantidWidgets::FitPropertyBrowser::m_tip private
To display a tip text.
Definition at line 627 of file FitPropertyBrowser.h.
Referenced by createFitMenuButton(), initBasicLayout(), and setTip().
m_updateObserver
Poco::NObserver<FitPropertyBrowser, Mantid::API::FunctionFactoryUpdateNotification> MantidQt::MantidWidgets::FitPropertyBrowser::m_updateObserver private
Observes algorithm factory update notifications.
Definition at line 608 of file FitPropertyBrowser.h.
Referenced by initBasicLayout(), and ~FitPropertyBrowser().
m_vectorDoubleManager
QtDoublePropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorDoubleManager protected
Definition at line 505 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttribute::apply(), createEditors(), FitPropertyBrowser(), initBasicLayout(), and ~FitPropertyBrowser().
m_vectorManager
QtGroupPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorManager protected
Definition at line 503 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), and FitPropertyBrowser().
m_vectorSizeManager
QtIntPropertyManager* MantidQt::MantidWidgets::FitPropertyBrowser::m_vectorSizeManager protected
Definition at line 504 of file FitPropertyBrowser.h.
Referenced by MantidQt::MantidWidgets::CreateAttributeProperty::apply(), MantidQt::MantidWidgets::SetAttribute::apply(), createEditors(), FitPropertyBrowser(), initBasicLayout(), and ~FitPropertyBrowser().
m_windowBaseString
QString MantidQt::MantidWidgets::FitPropertyBrowser::m_windowBaseString private
Definition at line 619 of file FitPropertyBrowser.h.
m_workspace
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_workspace protected
Definition at line 508 of file FitPropertyBrowser.h.
Referenced by addHandle(), addWorkspaceIndexToBrowser(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), enumChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), FitPropertyBrowser(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), populateWorkspaceNames(), removeWorkspace(), renameHandle(), setWorkspaceName(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceName(), setWorkspaceProperties(), and workspaceName().
m_workspaceIndex
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceIndex protected
Definition at line 509 of file FitPropertyBrowser.h.
Referenced by addAllowedSpectra(), addWorkspaceIndexToBrowser(), enumChanged(), init(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::init(), intChanged(), setWorkspaceIndex(), setWorkspaceProperties(), and workspaceIndex().
m_workspaceLabel
QLabel* MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceLabel private
Definition at line 638 of file FitPropertyBrowser.h.
Referenced by addFitResultWorkspacesToTableWidget(), initBasicLayout(), and removeWorkspace().
m_workspaceNames
QStringList MantidQt::MantidWidgets::FitPropertyBrowser::m_workspaceNames mutable protected
A list of available workspaces.
Definition at line 565 of file FitPropertyBrowser.h.
Referenced by addHandle(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::boolChanged(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::enumChanged(), getWorkspaceNames(), populateWorkspaceNames(), removeWorkspace(), renameHandle(), MantidQt::MantidWidgets::PropertyHandler::setFunctionWorkspace(), setWorkspaceName(), MantidQt::MantidWidgets::MuonFitPropertyBrowser::setWorkspaceName(), MantidQt::MantidWidgets::PropertyHandler::updateWorkspaces(), and workspaceName().
m_wsListWidget
QListWidget* MantidQt::MantidWidgets::FitPropertyBrowser::m_wsListWidget private
Definition at line 637 of file FitPropertyBrowser.h.
Referenced by addFitResultWorkspacesToTableWidget(), initBasicLayout(), removeWorkspace(), and renameHandle().
m_xColumn
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_xColumn protected
Definition at line 523 of file FitPropertyBrowser.h.
Referenced by columnChanged(), getXColumnName(), getXRange(), init(), and setWorkspaceProperties().
m_yColumn
QtProperty* MantidQt::MantidWidgets::FitPropertyBrowser::m_yColumn protected
Definition at line 524 of file FitPropertyBrowser.h.
Referenced by getYColumnName(), init(), and setWorkspaceProperties().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
qt/widgets/common/src/FitPropertyBrowser.cpp