Mantid: MantidQt::MantidWidgets::InputControllerDrawAndErase Class Reference
MantidQt::MantidWidgets::InputControllerDrawAndErase Class Reference
Controller for drawing and erasing arbitrary shapes on an unwrapped surface.
#include <InputController.h>
Public Slots
void startCreatingShape2D (const QColor &borderColor, const QColor &fillColor)
Signals
void addShape (const QPolygonF &poly, const QColor &borderColor, const QColor &fillColor)
void draw (const QPolygonF &)
void erase (const QPolygonF &)
Signals inherited from MantidQt::MantidWidgets::InputController
void disabled ()
void enabled ()
void touchPointAt (int, int)
Public Member Functions
InputControllerDrawAndErase (QObject *parent)
Public Member Functions inherited from MantidQt::MantidWidgets::InputControllerDraw
void enterEvent (QEvent *) override
InputControllerDraw (QObject *parent)
Constructor.
void leaveEvent (QEvent *) override
void mouseMoveEvent (QMouseEvent *) override
Process the mouse move event.
void mousePressEvent (QMouseEvent *) override
Process the mouse press event.
void mouseReleaseEvent (QMouseEvent *) override
Process the mouse button release event.
void wheelEvent (QWheelEvent *) override
~InputControllerDraw () override
Public Member Functions inherited from MantidQt::MantidWidgets::InputController
bool canShowContextMenu () const
Returns true if a surface using this controller can show a context menu on right-click.
virtual void enterEvent (QEvent *)
virtual void freezeRotation (bool)
InputController (QObject *parent, bool contextAllowed=true)
virtual void keyPressEvent (QKeyEvent *)
virtual void leaveEvent (QEvent *)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mousePressEvent (QMouseEvent *)
virtual void mouseReleaseEvent (QMouseEvent *)
virtual void onDisabled ()
To be called when this controller looses control.
virtual void onEnabled ()
To be called when this controller takes control of the input.
virtual void onPaint (QPainter &)
To be called after the owner widget has drawn its content.
virtual void wheelEvent (QWheelEvent *)
~InputController () override=default
Private Member Functions
void drawCursor (QPixmap *cursor) override
void makePolygon ()
void resize () override
void setPosition (const QPoint &pos) override
void signalLeftClick () override
void signalRightClick () override
Private Attributes
QColor m_borderColor
bool m_creating
QColor m_fillColor
QPoint m_pos
QPolygonF m_rect
Additional Inherited Members
Protected Member Functions inherited from MantidQt::MantidWidgets::InputControllerDraw
int cursorSize () const
bool isActive () const
bool isLeftButtonPressed () const
bool isRightButtonPressed () const
Detailed Description
Controller for drawing and erasing arbitrary shapes on an unwrapped surface.
Definition at line 281 of file InputController.h.
Constructor & Destructor Documentation
InputControllerDrawAndErase()
MantidQt::MantidWidgets::InputControllerDrawAndErase::InputControllerDrawAndErase (QObject * parent)
Definition at line 398 of file InputController.cpp.
References makePolygon().
Member Function Documentation
addShape
void MantidQt::MantidWidgets::InputControllerDrawAndErase::addShape (const QPolygonF & poly, const QColor & borderColor, const QColor & fillColor) signal
Referenced by signalLeftClick().
draw
void MantidQt::MantidWidgets::InputControllerDrawAndErase::draw (const QPolygonF &) signal
Referenced by signalLeftClick().
drawCursor()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::drawCursor (QPixmap * cursor) override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 429 of file InputController.cpp.
References MantidQt::MantidWidgets::InputControllerDraw::cursorSize(), and m_rect.
erase
void MantidQt::MantidWidgets::InputControllerDrawAndErase::erase (const QPolygonF &) signal
Referenced by signalRightClick().
makePolygon()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::makePolygon () private
Definition at line 403 of file InputController.cpp.
References MantidQt::MantidWidgets::InputControllerDraw::cursorSize(), m_rect, Mantid::Geometry::x, and Mantid::Geometry::y.
Referenced by InputControllerDrawAndErase(), and resize().
resize()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::resize () override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 453 of file InputController.cpp.
References makePolygon().
setPosition()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::setPosition (const QPoint & pos) override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 451 of file InputController.cpp.
References m_pos.
signalLeftClick()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::signalLeftClick () override private virtual
Implements MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 414 of file InputController.cpp.
References addShape(), draw(), m_borderColor, m_creating, m_fillColor, m_pos, and m_rect.
signalRightClick()
void MantidQt::MantidWidgets::InputControllerDrawAndErase::signalRightClick () override private virtual
Reimplemented from MantidQt::MantidWidgets::InputControllerDraw.
Definition at line 424 of file InputController.cpp.
References erase(), m_pos, and m_rect.
startCreatingShape2D
void MantidQt::MantidWidgets::InputControllerDrawAndErase::startCreatingShape2D (const QColor & borderColor, const QColor & fillColor) slot
Definition at line 455 of file InputController.cpp.
References m_borderColor, m_creating, and m_fillColor.
Member Data Documentation
m_borderColor
QColor MantidQt::MantidWidgets::InputControllerDrawAndErase::m_borderColor private
Definition at line 305 of file InputController.h.
Referenced by signalLeftClick(), and startCreatingShape2D().
m_creating
bool MantidQt::MantidWidgets::InputControllerDrawAndErase::m_creating private
Definition at line 306 of file InputController.h.
Referenced by signalLeftClick(), and startCreatingShape2D().
m_fillColor
QColor MantidQt::MantidWidgets::InputControllerDrawAndErase::m_fillColor private
Definition at line 305 of file InputController.h.
Referenced by signalLeftClick(), and startCreatingShape2D().
m_pos
QPoint MantidQt::MantidWidgets::InputControllerDrawAndErase::m_pos private
Definition at line 303 of file InputController.h.
Referenced by setPosition(), signalLeftClick(), and signalRightClick().
m_rect
QPolygonF MantidQt::MantidWidgets::InputControllerDrawAndErase::m_rect private
Definition at line 304 of file InputController.h.
Referenced by drawCursor(), makePolygon(), signalLeftClick(), and signalRightClick().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/InputController.h
qt/widgets/common/src/InputController.cpp