Mantid: Mantid::API::PreviewManagerImpl Class Reference
Mantid::API::PreviewManagerImpl Class Reference
PreviewManager : Manages the raw data previews.
#include <PreviewManager.h>
Public Member Functions
const IPreview & getPreview (const std::string &facility, const std::string &technique, const std::string &preview) const
std::vector< std::string > getPreviews (const std::string &facility, const std::string &technique="") const
PreviewManagerImpl & operator= (const PreviewManagerImpl &)=delete
PreviewManagerImpl ()=default
PreviewManagerImpl (const PreviewManagerImpl &)=delete
template<class T >
void subscribe ()
Private Member Functions
bool checkFacility (const std::string &facility) const
bool checkPreview (const std::string &facility, const std::string &technique, const std::string &preview) const
bool checkTechnique (const std::string &facility, const std::string &technique) const
Private Attributes
PreviewRegister m_previews
Detailed Description
PreviewManager : Manages the raw data previews.
Definition at line 26 of file PreviewManager.h.
Constructor & Destructor Documentation
PreviewManagerImpl() [1/2]
Mantid::API::PreviewManagerImpl::PreviewManagerImpl () default
PreviewManagerImpl() [2/2]
Mantid::API::PreviewManagerImpl::PreviewManagerImpl (const PreviewManagerImpl &) delete
Member Function Documentation
checkFacility()
bool Mantid::API::PreviewManagerImpl::checkFacility (const std::string & facility) const private
Definition at line 35 of file PreviewManager.cpp.
References m_previews.
Referenced by checkTechnique().
checkPreview()
bool Mantid::API::PreviewManagerImpl::checkPreview (const std::string & facility, const std::string & technique, const std::string & preview) const private
Definition at line 43 of file PreviewManager.cpp.
References checkTechnique(), and m_previews.
Referenced by getPreview().
checkTechnique()
bool Mantid::API::PreviewManagerImpl::checkTechnique (const std::string & facility, const std::string & technique) const private
Definition at line 36 of file PreviewManager.cpp.
References checkFacility(), and m_previews.
Referenced by checkPreview().
getPreview()
const IPreview & Mantid::API::PreviewManagerImpl::getPreview (const std::string & facility, const std::string & technique, const std::string & preview) const
Definition at line 26 of file PreviewManager.cpp.
References checkPreview(), and m_previews.
Referenced by export_PreviewManager().
getPreviews()
std::vector< std::string > Mantid::API::PreviewManagerImpl::getPreviews (const std::string & facility, const std::string & technique = "") const
Definition at line 11 of file PreviewManager.cpp.
References m_previews.
Referenced by export_PreviewManager().
operator=()
PreviewManagerImpl & Mantid::API::PreviewManagerImpl::operator= (const PreviewManagerImpl &) delete
subscribe()
template<class T > void Mantid::API::PreviewManagerImpl::subscribe () inline
Definition at line 34 of file PreviewManager.h.
References name.
Member Data Documentation
m_previews
PreviewRegister Mantid::API::PreviewManagerImpl::m_previews private
Definition at line 51 of file PreviewManager.h.
Referenced by checkFacility(), checkPreview(), checkTechnique(), getPreview(), and getPreviews().
The documentation for this class was generated from the following files:
Framework/API/inc/MantidAPI/PreviewManager.h
Framework/API/src/PreviewManager.cpp