Mantid: ICat4::ns1__luceneCommitResponse Class Reference
ICat4::ns1__luceneCommitResponse Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__luceneCommitResponse ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Additional Inherited Members
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 1190 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__luceneCommitResponse()
ICat4::ns1__luceneCommitResponse::ns1__luceneCommitResponse () inline
Definition at line 1199 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__luceneCommitResponse::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7452 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_default().
Referenced by ICat4::ICATPortBindingProxy::luceneCommit(), ICat4::soap_in_ns1__luceneCommitResponse(), ICat4::soap_new_req_ns1__luceneCommitResponse(), and ICat4::soap_new_set_ns1__luceneCommitResponse().
soap_get()
void * ICat4::ns1__luceneCommitResponse::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7508 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_ns1__luceneCommitResponse().
soap_in()
void * ICat4::ns1__luceneCommitResponse::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7473 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_ns1__luceneCommitResponse().
Referenced by ICat4::soap_in_ns1__luceneCommitResponse().
soap_out()
int ICat4::ns1__luceneCommitResponse::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7464 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_ns1__luceneCommitResponse().
Referenced by soap_put().
soap_put()
int ICat4::ns1__luceneCommitResponse::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7501 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__luceneCommitResponse.
soap_serialize()
void ICat4::ns1__luceneCommitResponse::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 7457 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::xsd__anyType::soap_serialize().
Referenced by ICat4::soap_serialize_PointerTons1__luceneCommit().
soap_type()
int ICat4::ns1__luceneCommitResponse::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 1192 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp