Mantid: Mantid::ICat::CatalogAlgorithmHelper Class Reference
Mantid::ICat::CatalogAlgorithmHelper Class Reference
#include <CatalogAlgorithmHelper.h>
Public Member Functions
const std::string getIDSError (const Poco::Net::HTTPResponse::HTTPStatus &HTTPStatus, std::istream &responseStream)
Obtain the error message returned by the IDS.
Detailed Description
Definition at line 18 of file CatalogAlgorithmHelper.h.
Member Function Documentation
getIDSError()
const std::string Mantid::ICat::CatalogAlgorithmHelper::getIDSError (const Poco::Net::HTTPResponse::HTTPStatus & HTTPStatus, std::istream & responseStream)
Obtain the error message returned by the IDS.
Parameters
HTTPStatus :: The HTTPStatus returned by the IDS.
responseStream :: The contents of the stream (a JSON stream) returned from the IDS.
Returns
An appropriate error message for the user if it exists. Otherwise an empty string.
Definition at line 25 of file CatalogAlgorithmHelper.cpp.
References std::to_string().
Referenced by Mantid::ICat::CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(), and Mantid::ICat::CatalogPublish::publish().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/CatalogAlgorithmHelper.h
Framework/ICat/src/CatalogAlgorithmHelper.cpp