Mantid: Mantid::Geometry::MatrixVectorPairParser< Iterator > Class Template Reference
Mantid::Geometry::MatrixVectorPairParser< Iterator > Class Template Reference
MatrixVectorPairParser.
#include <MatrixVectorPairParser.h>
Public Member Functions
MatrixVectorPairParser (MatrixVectorPairBuilder &builder)
Public Attributes
rule< Iterator, boost::spirit::qi::space_type > m_component
rule< Iterator, boost::spirit::qi::space_type > m_componentSeries
rule< Iterator, boost::spirit::qi::space_type > m_direction
rule< Iterator, boost::spirit::qi::space_type > m_parser
rule< Iterator, boost::spirit::qi::space_type > m_rational
rule< Iterator, boost::spirit::qi::space_type > m_sign
Detailed Description
template<typename Iterator>
class Mantid::Geometry::MatrixVectorPairParser< Iterator >
MatrixVectorPairParser.
MatrixVectorPairParser can parse matrix/vector pairs in Jones faithful notation of the form:
a/b-x, cy, -z
The resulting matrix/vector pair can be retrieved through a templated method that lets the caller decide on the numeric type stored in the matrix. The vector is currently always V3R.
To reuse the internally constructed boost::spirit-based parser, simply instantiate MatrixVectorPairParser once and use the parse-method.
@author Michael Wedel, ESS
@date 02/11/2015
Definition at line 173 of file MatrixVectorPairParser.h.
Constructor & Destructor Documentation
MatrixVectorPairParser()
template<typename Iterator > Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser (MatrixVectorPairBuilder & builder) inline
Definition at line 175 of file MatrixVectorPairParser.h.
References Mantid::Geometry::MatrixVectorPairBuilder::addCurrentStateToResult(), Mantid::Geometry::MatrixVectorPairBuilder::advanceRow(), Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_component, Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_componentSeries, Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_direction, Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_parser, Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_rational, Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_sign, Mantid::Geometry::MatrixVectorPairBuilder::setCurrentDirection(), Mantid::Geometry::MatrixVectorPairBuilder::setCurrentFactor(), Mantid::Geometry::MatrixVectorPairBuilder::setCurrentSignNegative(), and Mantid::Geometry::MatrixVectorPairBuilder::setCurrentSignPositive().
Member Data Documentation
m_component
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_component
Definition at line 233 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
m_componentSeries
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_componentSeries
Definition at line 233 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
m_direction
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_direction
Definition at line 233 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
m_parser
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_parser
Definition at line 234 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
m_rational
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_rational
Definition at line 233 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
m_sign
template<typename Iterator > rule<Iterator, boost::spirit::qi::space_type> Mantid::Geometry::MatrixVectorPairParser< Iterator >::m_sign
Definition at line 233 of file MatrixVectorPairParser.h.
Referenced by Mantid::Geometry::MatrixVectorPairParser< Iterator >::MatrixVectorPairParser().
The documentation for this class was generated from the following file:
Framework/Geometry/inc/MantidGeometry/Crystal/MatrixVectorPairParser.h