Mantid: Mantid::CurveFitting::EigenMatrix Class Reference
Mantid::CurveFitting::EigenMatrix Class Reference
A wrapper around Eigen::Matrix.
#include <EigenMatrix.h>
Public Member Functions
map_type copy_view () const
Get a copy of the Eigen matrix.
EigenVector copyColumn (size_t i) const
Copy a column into an EigenVector.
EigenVector copyRow (size_t i) const
Copy a row into an EigenVector.
double det () const
Calculate the determinant.
void diag (const EigenVector &d)
Set the matrix to be diagonal.
EigenMatrix ()=default
Constructor.
EigenMatrix (const EigenMatrix &M)
Copy constructor.
EigenMatrix (const Kernel::Matrix< double > &M)
Constructor.
EigenMatrix (const Kernel::Matrix< double > &M, size_t row, size_t col, size_t nRows, size_t nCols)
Constructor.
EigenMatrix (const size_t nx, const size_t ny)
Constructor.
EigenMatrix (EigenMatrix &M, size_t row, size_t col, size_t nRows, size_t nCols)
Create a submatrix.
EigenMatrix (std::initializer_list< std::initializer_list< double > > ilist)
Construct from an initialisation list.
void eigenSystem (EigenVector &eigenValues, EigenMatrix &eigenVectors)
Calculate the eigensystem of a symmetric matrix.
double get (size_t i, size_t j) const
Get an element.
void identity ()
Set this matrix to identity matrix.
const map_type inspector () const
Get a const copy of the Eigen matrix.
void invert ()
Invert this matrix.
bool isEmpty () const
Is matrix empty.
map_type & mutator ()
Get the map to Eigen matrix.
double & operator() (size_t i, size_t j)
Get the reference to the data element.
double operator() (size_t i, size_t j) const
The "index" operator.
EigenMatrix operator* (const EigenMatrix &m) const
Matrix by Matrix multiplication.
EigenVector operator* (const EigenVector &v) const
Matrix by vector multiplication.
EigenMatrix & operator*= (const double &d)
Multiply this matrix by a number.
EigenMatrix & operator+= (const double &d)
Add a constant to this matrix.
EigenMatrix & operator+= (const EigenMatrix &M)
Add a matrix to this.
EigenMatrix & operator-= (const double &d)
subtract a constant from this
EigenMatrix & operator-= (const EigenMatrix &M)
Subtract a matrix from this.
EigenMatrix & operator= (const Eigen::MatrixXd v)
Assignment operator - Eigen::MatrixXd.
EigenMatrix & operator= (const EigenMatrix &M)
Copy assignment operator.
void resize (const size_t nx, const size_t ny)
Resize the matrix.
void set (size_t i, size_t j, double value)
Set an element.
size_t size1 () const
First size of the matrix.
size_t size2 () const
Second size of the matrix.
void solve (const EigenVector &rhs, EigenVector &x)
Solve system of linear equations M*x == rhs, M is this matrix This matrix is destroyed.
EigenMatrix tr () const
Calculate the eigensystem of a symmetric matrix.
void zero ()
Set all elements to zero.
Protected Member Functions
EigenMatrix move ()
Create a new matrix and move the data to it.
Private Member Functions
EigenMatrix (std::vector< double > &&data, size_t nx, size_t ny)
"Move" constructor
EigenVector multiplyByVector (const EigenVector &v) const
Private Attributes
std::vector< double > m_data
Default element storage.
EigenMatrix_View m_view
The pointer to the vector.
Detailed Description
A wrapper around Eigen::Matrix.
Author
Roman Tolchenov, Tessella plc
Date
24/02/2012
Definition at line 33 of file EigenMatrix.h.
Constructor & Destructor Documentation
EigenMatrix() [1/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix () default
Constructor.
Referenced by move().
EigenMatrix() [2/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (const size_t nx, const size_t ny)
Constructor.
Parameters
nx :: First dimension
ny :: Second dimension
Definition at line 18 of file EigenMatrix.cpp.
EigenMatrix() [3/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (std::initializer_list< std::initializer_list< double > > ilist)
Construct from an initialisation list.
Parameters
ilist :: Initialisation list as a list of rows: {{M00, M01, M02, ...}, {M10, M11, M12, ...}, ... {Mn0, Mn1, Mn2, ...}}
Definition at line 27 of file EigenMatrix.cpp.
References set(), and size2().
EigenMatrix() [4/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (const EigenMatrix & M)
Copy constructor.
Parameters
M :: The other matrix.
Definition at line 43 of file EigenMatrix.cpp.
EigenMatrix() [5/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (EigenMatrix & M, size_t row, size_t col, size_t nRows, size_t nCols)
Create a submatrix.
A submatrix is a reference to part of the parent matrix.
Parameters
M :: The parent matrix.
row :: The first row in the submatrix.
col :: The first column in the submatrix.
nRows :: The number of rows in the submatrix.
nCols :: The number of columns in the submatrix.
Definition at line 52 of file EigenMatrix.cpp.
References m_data, m_view, mutator(), size1(), and size2().
EigenMatrix() [6/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (const Kernel::Matrix< double > & M)
Constructor.
Parameters
M :: A matrix to copy.
Definition at line 64 of file EigenMatrix.cpp.
References Mantid::Kernel::Matrix< T >::getVector(), m_data, Mantid::CurveFitting::EigenMatrix_View::matrix_mutator(), Mantid::Kernel::Matrix< T >::numCols(), and Mantid::Kernel::Matrix< T >::numRows().
EigenMatrix() [7/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (const Kernel::Matrix< double > & M, size_t row, size_t col, size_t nRows, size_t nCols)
Constructor.
Create a submatrix.
A submatrix is a reference to part of the parent matrix.
Parameters
M :: The parent matrix.
row :: The first row in the submatrix.
col :: The first column in the submatrix.
nRows :: The number of rows in the submatrix.
nCols :: The number of columns in the submatrix.
Definition at line 81 of file EigenMatrix.cpp.
References Mantid::Kernel::Matrix< T >::getVector(), m_data, Mantid::CurveFitting::EigenMatrix_View::matrix_mutator(), Mantid::Kernel::Matrix< T >::numCols(), Mantid::Kernel::Matrix< T >::numRows(), and resize().
EigenMatrix() [8/8]
Mantid::CurveFitting::EigenMatrix::EigenMatrix (std::vector< double > && data, size_t nx, size_t ny) private
"Move" constructor
Definition at line 98 of file EigenMatrix.cpp.
Member Function Documentation
copy_view()
map_type Mantid::CurveFitting::EigenMatrix::copy_view () const inline
Get a copy of the Eigen matrix.
Definition at line 60 of file EigenMatrix.h.
Referenced by copyColumn(), and copyRow().
copyColumn()
EigenVector Mantid::CurveFitting::EigenMatrix::copyColumn (size_t i) const
Copy a column into an EigenVector.
Copy a column into a EigenVector.
Parameters
i :: A column index.
Definition at line 335 of file EigenMatrix.cpp.
References copy_view(), Mantid::CurveFitting::EigenMatrix_View::innerStride(), Mantid::CurveFitting::EigenMatrix_View::matrix_mutator(), Mantid::CurveFitting::EigenMatrix_View::rows(), size1(), and size2().
copyRow()
EigenVector Mantid::CurveFitting::EigenMatrix::copyRow (size_t i) const
Copy a row into an EigenVector.
Copy a row into a EigenVector.
Parameters
i :: A row index.
Definition at line 322 of file EigenMatrix.cpp.
References Mantid::CurveFitting::EigenMatrix_View::cols(), copy_view(), Mantid::CurveFitting::EigenMatrix_View::matrix_mutator(), Mantid::CurveFitting::EigenMatrix_View::outerStride(), size1(), and size2().
det()
double Mantid::CurveFitting::EigenMatrix::det () const
Calculate the determinant.
Definition at line 286 of file EigenMatrix.cpp.
References inspector(), size1(), and size2().
Referenced by solve().
diag()
void Mantid::CurveFitting::EigenMatrix::diag (const EigenVector & d)
Set the matrix to be diagonal.
Parameters
d :: Values on the diagonal.
Definition at line 179 of file EigenMatrix.cpp.
References Mantid::Geometry::d, n, resize(), set(), and zero().
eigenSystem()
void Mantid::CurveFitting::EigenMatrix::eigenSystem (EigenVector & eigenValues, EigenMatrix & eigenVectors)
Calculate the eigensystem of a symmetric matrix.
Parameters
eigenValues :: Output variable that receives the eigenvalues of this matrix.
eigenVectors :: Output variable that receives the eigenvectors of this matrix.
Definition at line 299 of file EigenMatrix.cpp.
References inspector(), n, size1(), and size2().
Referenced by Mantid::CurveFitting::NLLS::allEigSymm().
get()
double Mantid::CurveFitting::EigenMatrix::get (size_t i, size_t j) const
Get an element.
get an element
Parameters
i :: The row
j :: The column
Definition at line 160 of file EigenMatrix.cpp.
References Mantid::CurveFitting::EigenMatrix_View::cols(), isEmpty(), m_view, Mantid::CurveFitting::EigenMatrix_View::matrix_inspector(), and Mantid::CurveFitting::EigenMatrix_View::rows().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateHessian(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calFittingErrors(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::execConcrete(), Mantid::CurveFitting::EigenJacobian::get(), and Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian().
identity()
void Mantid::CurveFitting::EigenMatrix::identity ()
Set this matrix to identity matrix.
Definition at line 172 of file EigenMatrix.cpp.
References m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
inspector()
const map_type Mantid::CurveFitting::EigenMatrix::inspector () const inline
Get a const copy of the Eigen matrix.
Definition at line 58 of file EigenMatrix.h.
Referenced by Mantid::CurveFitting::Algorithms::Fit::createOutput(), det(), eigenSystem(), Mantid::CurveFitting::NLLS::getSvdJ(), invert(), Mantid::CurveFitting::NLLS::matmultInner(), multiplyByVector(), Mantid::CurveFitting::NLLS::multJ(), Mantid::CurveFitting::NLLS::multJt(), operator*(), operator*(), operator+=(), operator-=(), solve(), and tr().
invert()
void Mantid::CurveFitting::EigenMatrix::invert ()
Invert this matrix.
Definition at line 278 of file EigenMatrix.cpp.
References inspector(), mutator(), size1(), and size2().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), and Mantid::CurveFitting::Algorithms::ProfileChiSquared1D::getCovarianceMatrix().
isEmpty()
bool Mantid::CurveFitting::EigenMatrix::isEmpty () const
Is matrix empty.
Definition at line 119 of file EigenMatrix.cpp.
References m_data.
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), get(), set(), and Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian().
move()
EigenMatrix Mantid::CurveFitting::EigenMatrix::move () protected
Create a new matrix and move the data to it.
Definition at line 347 of file EigenMatrix.cpp.
References EigenMatrix(), m_data, size1(), and size2().
multiplyByVector()
EigenVector Mantid::CurveFitting::EigenMatrix::multiplyByVector (const EigenVector & v) const private
Definition at line 349 of file EigenMatrix.cpp.
References inspector(), Mantid::CurveFitting::EigenVector::inspector(), Mantid::CurveFitting::EigenVector::size(), and size2().
mutator()
map_type & Mantid::CurveFitting::EigenMatrix::mutator () inline
Get the map to Eigen matrix.
Definition at line 56 of file EigenMatrix.h.
Referenced by Mantid::CurveFitting::EigenJacobian::addNumberToColumn(), EigenMatrix(), Mantid::CurveFitting::Functions::BSpline::evaluateBasisFnDerivatives(), Mantid::CurveFitting::EigenJacobian::getJ(), Mantid::CurveFitting::gsl_df(), invert(), Mantid::CurveFitting::NLLS::matmultInner(), Mantid::CurveFitting::NLLS::rankOneUpdate(), and Mantid::CurveFitting::Functions::ChebfunBase::roots().
operator()() [1/2]
double & Mantid::CurveFitting::EigenMatrix::operator() (size_t i, size_t j) inline
Get the reference to the data element.
Definition at line 150 of file EigenMatrix.h.
References m_data, m_view, and Mantid::CurveFitting::EigenMatrix_View::rows().
operator()() [2/2]
double Mantid::CurveFitting::EigenMatrix::operator() (size_t i, size_t j) const inline
The "index" operator.
Definition at line 147 of file EigenMatrix.h.
operator*() [1/2]
EigenMatrix Mantid::CurveFitting::EigenMatrix::operator* (const EigenMatrix & m) const
Matrix by Matrix multiplication.
Parameters
m :: A matrix to multiply by. Must have the same size1() as size2() of this matrix.
Returns
A Matrix - the result of the multiplication. Size of the returned vector equals size2() of first matrix by size1*() of second.
Exceptions
std::invalid_argument if the input matrix has a wrong size.
Definition at line 239 of file EigenMatrix.cpp.
References inspector(), Mantid::Geometry::m, and size2().
operator*() [2/2]
EigenVector Mantid::CurveFitting::EigenMatrix::operator* (const EigenVector & v) const
Matrix by vector multiplication.
Parameters
v :: A vector to multiply by. Must have the same size as size2().
Returns
A vector - the result of the multiplication. Size of the returned vector equals size1().
Exceptions
std::invalid_argument if the input vector has a wrong size.
Definition at line 224 of file EigenMatrix.cpp.
References inspector(), Mantid::CurveFitting::EigenVector::inspector(), Mantid::CurveFitting::EigenVector::size(), and size2().
operator*=()
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator*= (const double & d)
Multiply this matrix by a number.
multiply this matrix by a number
Parameters
d :: A number
Definition at line 214 of file EigenMatrix.cpp.
References Mantid::Geometry::d, m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
operator+=() [1/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator+= (const double & d)
Add a constant to this matrix.
add a constant to this matrix
Parameters
d :: A number
Definition at line 196 of file EigenMatrix.cpp.
References Mantid::Geometry::d, m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
operator+=() [2/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator+= (const EigenMatrix & M)
Add a matrix to this.
add a matrix to this
Parameters
M :: A matrix
Definition at line 190 of file EigenMatrix.cpp.
References inspector(), m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
operator-=() [1/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator-= (const double & d)
subtract a constant from this
Parameters
d :: A number
Definition at line 208 of file EigenMatrix.cpp.
References Mantid::Geometry::d, m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
operator-=() [2/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator-= (const EigenMatrix & M)
Subtract a matrix from this.
subtract a matrix from this
Parameters
M :: A matrix
Definition at line 202 of file EigenMatrix.cpp.
References inspector(), m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
operator=() [1/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator= (const Eigen::MatrixXd v)
Assignment operator - Eigen::MatrixXd.
Definition at line 109 of file EigenMatrix.cpp.
References Mantid::Geometry::m, m_data, m_view, and resize().
operator=() [2/2]
EigenMatrix & Mantid::CurveFitting::EigenMatrix::operator= (const EigenMatrix & M)
Copy assignment operator.
Definition at line 102 of file EigenMatrix.cpp.
References m_data, m_view, size1(), and size2().
resize()
void Mantid::CurveFitting::EigenMatrix::resize (const size_t nx, const size_t ny)
Resize the matrix.
Parameters
nx :: New first dimension
ny :: New second dimension
Definition at line 124 of file EigenMatrix.cpp.
References m_data, and m_view.
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncPoisson::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calTransformationMatrixNumerically(), diag(), Mantid::CurveFitting::EigenJacobian::EigenJacobian(), EigenMatrix(), operator=(), and Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian().
set()
void Mantid::CurveFitting::EigenMatrix::set (size_t i, size_t j, double value)
Set an element.
set an element
Parameters
i :: The row
j :: The column
value :: The new vaule
Definition at line 146 of file EigenMatrix.cpp.
References Mantid::CurveFitting::EigenMatrix_View::cols(), isEmpty(), m_view, Mantid::CurveFitting::EigenMatrix_View::matrix_mutator(), Mantid::CurveFitting::EigenMatrix_View::rows(), and value.
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncPoisson::calculateHessian(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calTransformationMatrixNumerically(), diag(), EigenMatrix(), Mantid::CurveFitting::Functions::ChebfunBase::roots(), Mantid::CurveFitting::EigenJacobian::set(), and Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian().
size1()
size_t Mantid::CurveFitting::EigenMatrix::size1 () const
First size of the matrix.
Definition at line 137 of file EigenMatrix.cpp.
References m_view, and Mantid::CurveFitting::EigenMatrix_View::rows().
Referenced by Mantid::CurveFitting::EigenJacobian::addNumberToColumn(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calFittingErrors(), copyColumn(), copyRow(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), det(), EigenMatrix(), eigenSystem(), invert(), move(), operator=(), and solve().
size2()
size_t Mantid::CurveFitting::EigenMatrix::size2 () const
Second size of the matrix.
Definition at line 140 of file EigenMatrix.cpp.
References Mantid::CurveFitting::EigenMatrix_View::cols(), and m_view.
Referenced by Mantid::CurveFitting::EigenJacobian::addNumberToColumn(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::addValDerivHessian(), Mantid::CurveFitting::CostFunctions::CostFuncUnweightedLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncLeastSquares::calActiveCovarianceMatrix(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::calFittingErrors(), copyColumn(), copyRow(), Mantid::CurveFitting::Algorithms::Fit::createOutput(), det(), EigenMatrix(), EigenMatrix(), eigenSystem(), invert(), move(), multiplyByVector(), operator*(), operator*(), operator=(), and solve().
solve()
void Mantid::CurveFitting::EigenMatrix::solve (const EigenVector & rhs, EigenVector & x)
Solve system of linear equations M*x == rhs, M is this matrix This matrix is destroyed.
Solve system of linear equations M*x == rhs, M is this matrix.
Parameters
rhs :: The right-hand-side vector
x :: The solution vector
Exceptions
std::invalid_argument if the input vectors have wrong sizes.
std::runtime_error if Eigen cannot produce a valid solution.
Definition at line 254 of file EigenMatrix.cpp.
References det(), inspector(), n, rhs, size1(), size2(), and Mantid::Geometry::x.
tr()
EigenMatrix Mantid::CurveFitting::EigenMatrix::tr () const
Calculate the eigensystem of a symmetric matrix.
Copy matrix, transpose, then return transposed copy.
Definition at line 360 of file EigenMatrix.cpp.
References inspector().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncFitting::calCovarianceMatrix(), and Mantid::CurveFitting::gsl_df().
zero()
void Mantid::CurveFitting::EigenMatrix::zero ()
Set all elements to zero.
Definition at line 175 of file EigenMatrix.cpp.
References m_view, and Mantid::CurveFitting::EigenMatrix_View::matrix_mutator().
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncPoisson::addValDerivHessian(), Mantid::CurveFitting::Functions::deg_on(), diag(), Mantid::CurveFitting::FuncMinimisers::TrustRegionMinimizer::evalHF(), Mantid::CurveFitting::Functions::ChebfunBase::roots(), Mantid::CurveFitting::CostFunctions::CostFuncFitting::valDerivHessian(), and Mantid::CurveFitting::EigenJacobian::zero().
Member Data Documentation
m_data
std::vector<double> Mantid::CurveFitting::EigenMatrix::m_data private
Default element storage.
Definition at line 126 of file EigenMatrix.h.
Referenced by EigenMatrix(), EigenMatrix(), EigenMatrix(), isEmpty(), move(), operator()(), operator=(), operator=(), and resize().
m_view
EigenMatrix_View Mantid::CurveFitting::EigenMatrix::m_view private
The pointer to the vector.
Definition at line 128 of file EigenMatrix.h.
Referenced by EigenMatrix(), get(), identity(), operator()(), operator*=(), operator+=(), operator+=(), operator-=(), operator-=(), operator=(), operator=(), resize(), set(), size1(), size2(), and zero().
The documentation for this class was generated from the following files:
Framework/CurveFitting/inc/MantidCurveFitting/EigenMatrix.h
Framework/CurveFitting/src/EigenMatrix.cpp