Mantid: Framework/Nexus/inc/MantidNexus/NexusFile_fwd.h File Reference
NexusFile_fwd.h File Reference
#include "MantidNexus/DllConfig.h"
#include "MantidNexus/NexusAddress.h"
#include <iosfwd>
#include <map>
#include <string>
#include <vector>
Classes
struct Mantid::Nexus::AttrInfo
Information about an attribute.
struct Mantid::Nexus::Info
This structure holds the type and dimensions of a primative field/array.
struct NXlink
Represents a link between entries in a Nexus file.
class NXnumtype
The primitive types published by this API.
Namespaces
namespace Mantid
Helper class which provides the Collimation Length for SANS instruments.
namespace Mantid::Nexus
Header for a base Nexus::Exception.
Typedefs
typedef hsize_t Mantid::Nexus::dimsize_t
typedef std::vector< dimsize_t > Mantid::Nexus::DimVector
typedef std::map< std::string, std::string > Mantid::Nexus::Entries
typedef std::pair< std::string, std::string > Mantid::Nexus::Entry
typedef int herr_t
typedef int64_t hid_t
This class defines data types which are used as part of the Nexus API.
typedef uint64_t hsize_t
Enumerations
enum class NXaccess : unsigned int { READ = 0x0000u , RDWR = 0x0001u , CREATE5 = 0x0002u }
Nexus file access codes.
enum class NXcompression {
CHUNK , NONE , LZW , RLE ,
HUF
}
The available compression types:
enum class NXentrytype : int { group = 0 , sds = 1 }
Describes the type of entry in a Nexus file, either group or dataset.
Functions
constexpr std::size_t NX_MAXRANK (32)
constexpr Mantid::Nexus::dimsize_t NX_UNLIMITED (-1)
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream &os, const NXaccess &value)
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream &os, const NXcompression &value)
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream &os, const NXnumtype &value)
Typedef Documentation
herr_t
typedef int herr_t
Definition at line 18 of file NexusFile_fwd.h.
hid_t
typedef int64_t hid_t
This class defines data types which are used as part of the Nexus API.
They should more properly be moved into NexusFile, when the nexus layer has been cleaned up. OR all type and enum definitions in NexusFile all moved here.
Definition at line 16 of file NexusFile_fwd.h.
hsize_t
typedef uint64_t hsize_t
Definition at line 17 of file NexusFile_fwd.h.
Enumeration Type Documentation
NXaccess
enum class NXaccess : unsigned int strong
Nexus file access codes.
these codes are taken directly from values used in hdf5 package https://github.com/HDFGroup/hdf5/blob/develop/src/H5Fpublic.h
READ read-only. Same as H5F_ACC_RDONLY
RDWR open an existing file for reading and writing. Same as H5F_ACC_RDWR.
CREATE5 create a Nexus HDF-5 file. Same as H5F_ACC_TRUNC.
Enumerator
READ
RDWR
CREATE5
Definition at line 28 of file NexusFile_fwd.h.
NXcompression
enum class NXcompression strong
The available compression types:
CHUNK chunk encoding
NONE no compression
LZW Lossless Lempel Ziv Welch compression (recommended)
RLE Run length encoding (only HDF-4)
HUF Huffmann encoding (only HDF-4)
Enumerator
CHUNK
NONE
LZW
RLE
HUF
Definition at line 108 of file NexusFile_fwd.h.
NXentrytype
enum class NXentrytype : int strong
Describes the type of entry in a Nexus file, either group or dataset.
group the entry is a group
sds the entry is a dataset (class SDS)
Enumerator
group
sds
Definition at line 37 of file NexusFile_fwd.h.
Function Documentation
NX_MAXRANK()
constexpr std::size_t NX_MAXRANK (32) constexpr
NX_UNLIMITED()
constexpr Mantid::Nexus::dimsize_t NX_UNLIMITED (- 1) constexpr
Referenced by Mantid::DataObjects::BoxControllerNeXusIO::prepareNxSToWrite_CurVersion(), Mantid::DataHandling::SaveNXTomo::processAll(), Mantid::DataHandling::SaveNXTomo::setupFile(), and Mantid::DataHandling::SaveNXTomo::writeLogValues().
operator<<() [1/3]
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream & os, const NXaccess & value)
operator<<() [2/3]
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream & os, const NXcompression & value)
operator<<() [3/3]
MANTID_NEXUS_DLL std::ostream & operator<< (std::ostream & os, const NXnumtype & value)