Mantid: AlgExecSummaryGrpBox Class Reference
AlgExecSummaryGrpBox Class Reference
#include <AlgorithmHistoryWindow.h>
Public Member Functions
AlgExecSummaryGrpBox (const QString &, QWidget *w)
AlgExecSummaryGrpBox (QWidget *w)
void setData (const double execDuration, const Mantid::Types::Core::DateAndTime execDate)
~AlgExecSummaryGrpBox () override
Private Member Functions
QLineEdit * getAlgExecDateCtrl () const
QLineEdit * getAlgExecDurationCtrl () const
Private Attributes
QString m_algexecDuration
QLabel * m_Datelabel
QLineEdit * m_execDateTimeEdit
QLineEdit * m_execDurationEdit
QLabel * m_execDurationlabel
Detailed Description
Definition at line 92 of file AlgorithmHistoryWindow.h.
Constructor & Destructor Documentation
AlgExecSummaryGrpBox() [1/2]
AlgExecSummaryGrpBox::AlgExecSummaryGrpBox (QWidget * w) explicit
Definition at line 60 of file AlgorithmHistoryWindow.cpp.
AlgExecSummaryGrpBox() [2/2]
AlgExecSummaryGrpBox::AlgExecSummaryGrpBox (const QString & title, QWidget * w)
Definition at line 64 of file AlgorithmHistoryWindow.cpp.
References m_Datelabel, m_execDateTimeEdit, m_execDurationEdit, and m_execDurationlabel.
~AlgExecSummaryGrpBox()
AlgExecSummaryGrpBox::~AlgExecSummaryGrpBox () override
Definition at line 91 of file AlgorithmHistoryWindow.cpp.
References m_Datelabel, m_execDateTimeEdit, m_execDurationEdit, and m_execDurationlabel.
Member Function Documentation
getAlgExecDateCtrl()
QLineEdit * AlgExecSummaryGrpBox::getAlgExecDateCtrl () const inline private
Definition at line 102 of file AlgorithmHistoryWindow.h.
References m_execDateTimeEdit.
Referenced by setData().
getAlgExecDurationCtrl()
QLineEdit * AlgExecSummaryGrpBox::getAlgExecDurationCtrl () const inline private
Definition at line 101 of file AlgorithmHistoryWindow.h.
References m_execDurationEdit.
Referenced by setData().
setData()
void AlgExecSummaryGrpBox::setData (const double execDuration, const Mantid::Types::Core::DateAndTime execDate)
Definition at line 109 of file AlgorithmHistoryWindow.cpp.
References getAlgExecDateCtrl(), and getAlgExecDurationCtrl().
Referenced by AlgorithmHistoryWindow::createExecSummaryGrpBox(), and AlgorithmHistoryWindow::updateExecSummaryGrpBox().
Member Data Documentation
m_algexecDuration
QString AlgExecSummaryGrpBox::m_algexecDuration private
Definition at line 109 of file AlgorithmHistoryWindow.h.
m_Datelabel
QLabel* AlgExecSummaryGrpBox::m_Datelabel private
Definition at line 107 of file AlgorithmHistoryWindow.h.
Referenced by AlgExecSummaryGrpBox(), and ~AlgExecSummaryGrpBox().
m_execDateTimeEdit
QLineEdit* AlgExecSummaryGrpBox::m_execDateTimeEdit private
Definition at line 108 of file AlgorithmHistoryWindow.h.
Referenced by AlgExecSummaryGrpBox(), getAlgExecDateCtrl(), and ~AlgExecSummaryGrpBox().
m_execDurationEdit
QLineEdit* AlgExecSummaryGrpBox::m_execDurationEdit private
Definition at line 106 of file AlgorithmHistoryWindow.h.
Referenced by AlgExecSummaryGrpBox(), getAlgExecDurationCtrl(), and ~AlgExecSummaryGrpBox().
m_execDurationlabel
QLabel* AlgExecSummaryGrpBox::m_execDurationlabel private
Definition at line 105 of file AlgorithmHistoryWindow.h.
Referenced by AlgExecSummaryGrpBox(), and ~AlgExecSummaryGrpBox().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmHistoryWindow.h
qt/widgets/common/src/AlgorithmHistoryWindow.cpp