Mantid: MantidQt::MantidWidgets::FunctionMultiDomainPresenter Class Reference
MantidQt::MantidWidgets::FunctionMultiDomainPresenter Class Reference
#include <FunctionMultiDomainPresenter.h>
Signals
void attributeChanged (std::string const &attributeName)
void functionStructureChanged ()
void parameterChanged (std::string const &funcIndex, std::string const &parameterName)
Public Member Functions
void addDatasets (const std::vector< std::string > &datasetNames)
void clear ()
void clearErrors ()
std::optional< std::string > currentFunctionIndex () const
FunctionMultiDomainPresenter (IFunctionView *view)
int getCurrentDataset () const
std::vector< std::string > getDatasetDomainNames () const
std::vector< std::string > getDatasetNames () const
IFunction_sptr getFitFunction () const
std::string getFitFunctionString () const
IFunction_sptr getFunction () const
IFunction_sptr getFunctionByIndex (std::string const &index)
std::string getFunctionString () const
std::vector< std::string > getGlobalParameters () const
std::string getLocalParameterConstraint (std::string const &parameterName, int i) const
std::vector< std::string > getLocalParameters () const
std::string getLocalParameterTie (std::string const &parameterName, int i) const
double getLocalParameterValue (std::string const &parameterName, int i) const
int getNumberOfDatasets () const
double getParameter (std::string const &parameterName)
std::string getParameterTie (std::string const &parameterName) const
bool hasFunction () const
void hideGlobals ()
bool isLocalParameterFixed (std::string const &parameterName, int i) const
bool isParameterFixed (std::string const &parameterName) const
void removeDatasets (QList< int > indices)
void setBackgroundA0 (double value)
void setColumnSizes (int s0, int s1, int s2)
void setCurrentDataset (int)
void setDatasets (const QList< FunctionModelDataset > &datasets)
void setDatasets (const std::vector< std::string > &datasetNames)
void setErrorsEnabled (bool enabled)
void setFunction (IFunction_sptr fun)
void setFunctionString (std::string const &funStr)
void setGlobalParameters (std::vector< std::string > const &globals)
void setLocalParameterConstraint (std::string const &parameterName, int i, std::string const &constraint)
void setLocalParameterFixed (std::string const &parameterName, int i, bool fixed)
void setLocalParameterTie (std::string const &parameterName, int i, std::string const &tie)
void setLocalParameterValue (std::string const &parameterName, int i, double value)
void setLocalParameterValue (std::string const &parameterName, int i, double value, double error)
void setNumberOfDatasets (int)
void setParameter (std::string const &parameterName, double value)
void setParameterError (std::string const &parameterName, double value)
void setStretchLastColumn (bool stretch)
void showGlobals ()
void updateMultiDatasetAttributes (const IFunction &fun)
void updateMultiDatasetParameters (const IFunction &fun)
void updateParameters (const IFunction &fun)
IFunctionView * view () const
Private Slots
void editLocalParameter (std::string const &parameterName)
Launches the Edit Local Parameter dialog and deals with the input from it.
void editLocalParameterFinish (int result)
void viewAddedConstraint (std::string const &functionIndex, std::string const &constraint)
void viewAddedFunction (std::string const &funStr)
void viewChangedAttribute (std::string const &attrName)
void viewChangedGlobals (const std::vector< std::string > &globalParameters)
void viewChangedParameter (std::string const &parameterName)
void viewChangedTie (std::string const &parameterName, std::string const &tie)
void viewPastedFunction (std::string const &funStr)
void viewRemovedConstraint (std::string const &parameterName)
void viewRemovedFunction (std::string const &functionIndex)
void viewRequestedCopyToClipboard ()
void viewRequestedFunctionHelp ()
Private Member Functions
void updateViewAttributesFromModel ()
void updateViewFromModel ()
Private Attributes
EditLocalParameterDialog * m_editLocalParameterDialog
std::unique_ptr< FunctionModel > m_model
IFunctionView * m_view
Detailed Description
Definition at line 28 of file FunctionMultiDomainPresenter.h.
Constructor & Destructor Documentation
FunctionMultiDomainPresenter()
MantidQt::MantidWidgets::FunctionMultiDomainPresenter::FunctionMultiDomainPresenter (IFunctionView * view)
Definition at line 31 of file FunctionMultiDomainPresenter.cpp.
References editLocalParameter(), m_view, parameterChanged(), viewAddedConstraint(), viewAddedFunction(), viewChangedAttribute(), viewChangedGlobals(), viewChangedParameter(), viewChangedTie(), viewPastedFunction(), viewRemovedConstraint(), viewRemovedFunction(), viewRequestedCopyToClipboard(), and viewRequestedFunctionHelp().
Member Function Documentation
addDatasets()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::addDatasets (const std::vector< std::string > & datasetNames)
Definition at line 128 of file FunctionMultiDomainPresenter.cpp.
References m_model.
attributeChanged
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::attributeChanged (std::string const & attributeName) signal
Referenced by viewChangedAttribute().
clear()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::clear ()
Definition at line 287 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::clear(), functionStructureChanged(), m_model, and m_view.
clearErrors()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::clearErrors ()
Definition at line 112 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::clearErrors(), and m_view.
currentFunctionIndex()
std::optional< std::string > MantidQt::MantidWidgets::FunctionMultiDomainPresenter::currentFunctionIndex () const
Definition at line 114 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::currentFunctionIndex(), and m_view.
editLocalParameter
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::editLocalParameter (std::string const & parameterName) private slot
Launches the Edit Local Parameter dialog and deals with the input from it.
Parameters
parameterName :: Name of parameter that button was clicked for.
Definition at line 328 of file FunctionMultiDomainPresenter.cpp.
References editLocalParameterFinish(), getDatasetDomainNames(), getDatasetNames(), getLocalParameterConstraint(), getLocalParameterTie(), getLocalParameterValue(), isLocalParameterFixed(), m_editLocalParameterDialog, m_view, and value.
Referenced by FunctionMultiDomainPresenter().
editLocalParameterFinish
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::editLocalParameterFinish (int result) private slot
Definition at line 352 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), MantidQt::MantidWidgets::EditLocalParameterDialog::getConstraints(), MantidQt::MantidWidgets::EditLocalParameterDialog::getFixes(), getNumberOfDatasets(), MantidQt::MantidWidgets::EditLocalParameterDialog::getParameterName(), MantidQt::MantidWidgets::EditLocalParameterDialog::getTies(), MantidQt::MantidWidgets::EditLocalParameterDialog::getValues(), m_editLocalParameterDialog, setLocalParameterConstraint(), setLocalParameterFixed(), setLocalParameterTie(), and setLocalParameterValue().
Referenced by editLocalParameter().
functionStructureChanged
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::functionStructureChanged () signal
Referenced by clear(), editLocalParameterFinish(), setFunction(), setFunctionString(), viewAddedConstraint(), viewAddedFunction(), viewChangedGlobals(), viewChangedTie(), viewPastedFunction(), viewRemovedConstraint(), and viewRemovedFunction().
getCurrentDataset()
int MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getCurrentDataset () const
Definition at line 140 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getDatasetDomainNames()
std::vector< std::string > MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getDatasetDomainNames () const
Definition at line 134 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
getDatasetNames()
std::vector< std::string > MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getDatasetNames () const
Definition at line 132 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
getFitFunction()
IFunction_sptr MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFitFunction () const
Definition at line 65 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getFitFunctionString()
std::string MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFitFunctionString () const
Definition at line 67 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getFunction()
IFunction_sptr MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFunction () const
Definition at line 285 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by viewRequestedCopyToClipboard().
getFunctionByIndex()
IFunction_sptr MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFunctionByIndex (std::string const & index)
Definition at line 71 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::getFunctionWithPrefix(), index, and m_model.
getFunctionString()
std::string MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getFunctionString () const
Definition at line 283 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getGlobalParameters()
std::vector< std::string > MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getGlobalParameters () const
Definition at line 211 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getLocalParameterConstraint()
std::string MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getLocalParameterConstraint (std::string const & parameterName, int i) const
Definition at line 164 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
getLocalParameters()
std::vector< std::string > MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getLocalParameters () const
Definition at line 220 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getLocalParameterTie()
std::string MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getLocalParameterTie (std::string const & parameterName, int i) const
Definition at line 160 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
getLocalParameterValue()
double MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getLocalParameterValue (std::string const & parameterName, int i) const
Definition at line 152 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
getNumberOfDatasets()
int MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getNumberOfDatasets () const
Definition at line 138 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameterFinish().
getParameter()
double MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getParameter (std::string const & parameterName)
Definition at line 85 of file FunctionMultiDomainPresenter.cpp.
References m_model.
getParameterTie()
std::string MantidQt::MantidWidgets::FunctionMultiDomainPresenter::getParameterTie (std::string const & parameterName) const
Definition at line 93 of file FunctionMultiDomainPresenter.cpp.
References m_model.
hasFunction()
bool MantidQt::MantidWidgets::FunctionMultiDomainPresenter::hasFunction () const
Definition at line 69 of file FunctionMultiDomainPresenter.cpp.
References m_model.
hideGlobals()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::hideGlobals ()
Definition at line 402 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::FunctionTreeView::hideGlobals(), and m_view.
isLocalParameterFixed()
bool MantidQt::MantidWidgets::FunctionMultiDomainPresenter::isLocalParameterFixed (std::string const & parameterName, int i) const
Definition at line 156 of file FunctionMultiDomainPresenter.cpp.
References m_model.
Referenced by editLocalParameter().
isParameterFixed()
bool MantidQt::MantidWidgets::FunctionMultiDomainPresenter::isParameterFixed (std::string const & parameterName) const
Definition at line 89 of file FunctionMultiDomainPresenter.cpp.
References m_model.
parameterChanged
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::parameterChanged (std::string const & funcIndex, std::string const & parameterName) signal
Referenced by FunctionMultiDomainPresenter(), and viewChangedParameter().
removeDatasets()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::removeDatasets (QList< int > indices)
Definition at line 147 of file FunctionMultiDomainPresenter.cpp.
References m_model, and setCurrentDataset().
setBackgroundA0()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setBackgroundA0 (double value)
Definition at line 224 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IFunctionView::setParameter(), and value.
setColumnSizes()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setColumnSizes (int s0, int s1, int s2)
Definition at line 293 of file FunctionMultiDomainPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::FunctionTreeView::setColumnSizes().
setCurrentDataset()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setCurrentDataset (int index)
Definition at line 142 of file FunctionMultiDomainPresenter.cpp.
References index, m_model, and updateViewFromModel().
Referenced by removeDatasets().
setDatasets() [1/2]
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setDatasets (const QList< FunctionModelDataset > & datasets)
Definition at line 124 of file FunctionMultiDomainPresenter.cpp.
References m_model.
setDatasets() [2/2]
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setDatasets (const std::vector< std::string > & datasetNames)
Definition at line 120 of file FunctionMultiDomainPresenter.cpp.
References m_model.
setErrorsEnabled()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setErrorsEnabled (bool enabled)
Definition at line 304 of file FunctionMultiDomainPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::IFunctionView::setErrorsEnabled().
setFunction()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setFunction (IFunction_sptr fun)
Definition at line 53 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setFunction().
setFunctionString()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setFunctionString (std::string const & funStr)
Definition at line 59 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setFunction().
setGlobalParameters()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setGlobalParameters (std::vector< std::string > const & globals)
Definition at line 215 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setGlobalParameters().
setLocalParameterConstraint()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterConstraint (std::string const & parameterName, int i, std::string const & constraint)
Definition at line 203 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setParameterConstraint().
Referenced by editLocalParameterFinish().
setLocalParameterFixed()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterFixed (std::string const & parameterName, int i, bool fixed)
Definition at line 184 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setParameterTie().
Referenced by editLocalParameterFinish().
setLocalParameterTie()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterTie (std::string const & parameterName, int i, std::string const & tie)
Definition at line 195 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setParameterTie().
Referenced by editLocalParameterFinish().
setLocalParameterValue() [1/2]
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterValue (std::string const & parameterName, int i, double value)
Definition at line 168 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IFunctionView::setParameter(), and value.
Referenced by editLocalParameterFinish().
setLocalParameterValue() [2/2]
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setLocalParameterValue (std::string const & parameterName, int i, double value, double error)
Definition at line 175 of file FunctionMultiDomainPresenter.cpp.
References error, m_model, m_view, MantidQt::MantidWidgets::IFunctionView::setParameter(), MantidQt::MantidWidgets::IFunctionView::setParameterError(), and value.
setNumberOfDatasets()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setNumberOfDatasets (int n)
Definition at line 118 of file FunctionMultiDomainPresenter.cpp.
References m_model, and n.
setParameter()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setParameter (std::string const & parameterName, double value)
Definition at line 75 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IFunctionView::setParameter(), and value.
setParameterError()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setParameterError (std::string const & parameterName, double value)
Definition at line 80 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, MantidQt::MantidWidgets::IFunctionView::setParameterError(), and value.
setStretchLastColumn()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::setStretchLastColumn (bool stretch)
Definition at line 299 of file FunctionMultiDomainPresenter.cpp.
References m_view.
showGlobals()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::showGlobals ()
Definition at line 409 of file FunctionMultiDomainPresenter.cpp.
References m_view, and MantidQt::MantidWidgets::FunctionTreeView::showGlobals().
updateMultiDatasetAttributes()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateMultiDatasetAttributes (const IFunction & fun)
Definition at line 107 of file FunctionMultiDomainPresenter.cpp.
References m_model, and updateViewFromModel().
updateMultiDatasetParameters()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateMultiDatasetParameters (const IFunction & fun)
Definition at line 102 of file FunctionMultiDomainPresenter.cpp.
References m_model, and updateViewFromModel().
updateParameters()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateParameters (const IFunction & fun)
Definition at line 97 of file FunctionMultiDomainPresenter.cpp.
References m_model, and updateViewFromModel().
updateViewAttributesFromModel()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewAttributesFromModel () private
Definition at line 392 of file FunctionMultiDomainPresenter.cpp.
References m_model, m_view, name, MantidQt::MantidWidgets::IFunctionView::setAttributeValue(), and value.
Referenced by updateViewFromModel(), and viewChangedAttribute().
updateViewFromModel()
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::updateViewFromModel () private
Definition at line 376 of file FunctionMultiDomainPresenter.cpp.
References index, m_model, m_view, name, MantidQt::MantidWidgets::IFunctionView::setParameter(), MantidQt::MantidWidgets::IFunctionView::setParameterConstraint(), MantidQt::MantidWidgets::IFunctionView::setParameterError(), MantidQt::MantidWidgets::IFunctionView::setParameterTie(), updateViewAttributesFromModel(), and value.
Referenced by setCurrentDataset(), updateMultiDatasetAttributes(), updateMultiDatasetParameters(), and updateParameters().
view()
IFunctionView * MantidQt::MantidWidgets::FunctionMultiDomainPresenter::view () const inline
Definition at line 109 of file FunctionMultiDomainPresenter.h.
viewAddedConstraint
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewAddedConstraint (std::string const & functionIndex, std::string const & constraint) private slot
Definition at line 254 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), and m_model.
Referenced by FunctionMultiDomainPresenter().
viewAddedFunction
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewAddedFunction (std::string const & funStr) private slot
Definition at line 235 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::currentFunctionIndex(), functionStructureChanged(), m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setGlobalParameters().
Referenced by FunctionMultiDomainPresenter().
viewChangedAttribute
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedAttribute (std::string const & attrName) private slot
Definition at line 313 of file FunctionMultiDomainPresenter.cpp.
References attributeChanged(), Mantid::Kernel::Logger::error(), Mantid::API::g_log, MantidQt::MantidWidgets::IFunctionView::getAttribute(), m_model, m_view, updateViewAttributesFromModel(), and value.
Referenced by FunctionMultiDomainPresenter().
viewChangedGlobals
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedGlobals (const std::vector< std::string > & globalParameters) private slot
Definition at line 272 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), and m_model.
Referenced by FunctionMultiDomainPresenter().
viewChangedParameter
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedParameter (std::string const & parameterName) private slot
Definition at line 306 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::getParameter(), m_model, m_view, parameterChanged(), MantidQt::MantidWidgets::splitParameterName(), and value.
Referenced by FunctionMultiDomainPresenter().
viewChangedTie
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewChangedTie (std::string const & parameterName, std::string const & tie) private slot
Definition at line 249 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), and m_model.
Referenced by FunctionMultiDomainPresenter().
viewPastedFunction
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewPastedFunction (std::string const & funStr) private slot
Definition at line 230 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), and m_model.
Referenced by FunctionMultiDomainPresenter().
viewRemovedConstraint
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRemovedConstraint (std::string const & parameterName) private slot
Definition at line 260 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), and m_model.
Referenced by FunctionMultiDomainPresenter().
viewRemovedFunction
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRemovedFunction (std::string const & functionIndex) private slot
Definition at line 243 of file FunctionMultiDomainPresenter.cpp.
References functionStructureChanged(), m_model, m_view, and MantidQt::MantidWidgets::IFunctionView::setGlobalParameters().
Referenced by FunctionMultiDomainPresenter().
viewRequestedCopyToClipboard
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRequestedCopyToClipboard () private slot
Definition at line 265 of file FunctionMultiDomainPresenter.cpp.
References getFunction().
Referenced by FunctionMultiDomainPresenter().
viewRequestedFunctionHelp
void MantidQt::MantidWidgets::FunctionMultiDomainPresenter::viewRequestedFunctionHelp () private slot
Definition at line 277 of file FunctionMultiDomainPresenter.cpp.
References MantidQt::MantidWidgets::IFunctionView::getSelectedFunction(), m_view, and MantidQt::MantidWidgets::IFunctionView::showFunctionHelp().
Referenced by FunctionMultiDomainPresenter().
Member Data Documentation
m_editLocalParameterDialog
EditLocalParameterDialog* MantidQt::MantidWidgets::FunctionMultiDomainPresenter::m_editLocalParameterDialog private
Definition at line 106 of file FunctionMultiDomainPresenter.h.
Referenced by editLocalParameter(), and editLocalParameterFinish().
m_model
std::unique_ptr<FunctionModel> MantidQt::MantidWidgets::FunctionMultiDomainPresenter::m_model private
Definition at line 105 of file FunctionMultiDomainPresenter.h.
Referenced by addDatasets(), clear(), getCurrentDataset(), getDatasetDomainNames(), getDatasetNames(), getFitFunction(), getFitFunctionString(), getFunction(), getFunctionByIndex(), getFunctionString(), getGlobalParameters(), getLocalParameterConstraint(), getLocalParameters(), getLocalParameterTie(), getLocalParameterValue(), getNumberOfDatasets(), getParameter(), getParameterTie(), hasFunction(), isLocalParameterFixed(), isParameterFixed(), removeDatasets(), setBackgroundA0(), setCurrentDataset(), setDatasets(), setDatasets(), setFunction(), setFunctionString(), setGlobalParameters(), setLocalParameterConstraint(), setLocalParameterFixed(), setLocalParameterTie(), setLocalParameterValue(), setLocalParameterValue(), setNumberOfDatasets(), setParameter(), setParameterError(), updateMultiDatasetAttributes(), updateMultiDatasetParameters(), updateParameters(), updateViewAttributesFromModel(), updateViewFromModel(), viewAddedConstraint(), viewAddedFunction(), viewChangedAttribute(), viewChangedGlobals(), viewChangedParameter(), viewChangedTie(), viewPastedFunction(), viewRemovedConstraint(), and viewRemovedFunction().
m_view
IFunctionView* MantidQt::MantidWidgets::FunctionMultiDomainPresenter::m_view private
Definition at line 104 of file FunctionMultiDomainPresenter.h.
Referenced by clear(), clearErrors(), currentFunctionIndex(), editLocalParameter(), FunctionMultiDomainPresenter(), hideGlobals(), setBackgroundA0(), setColumnSizes(), setErrorsEnabled(), setFunction(), setFunctionString(), setGlobalParameters(), setLocalParameterConstraint(), setLocalParameterFixed(), setLocalParameterTie(), setLocalParameterValue(), setLocalParameterValue(), setParameter(), setParameterError(), setStretchLastColumn(), showGlobals(), updateViewAttributesFromModel(), updateViewFromModel(), viewAddedFunction(), viewChangedAttribute(), viewChangedParameter(), viewRemovedFunction(), and viewRequestedFunctionHelp().
The documentation for this class was generated from the following files:
qt/widgets/common/inc/MantidQtWidgets/Common/FunctionMultiDomainPresenter.h
qt/widgets/common/src/FunctionMultiDomainPresenter.cpp