Mantid: ICat4::ns1__get Class Reference
ICat4::ns1__get Class Reference
#include <ICat4Stub.h>
Public Member Functions
ns1__get ()
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
Public Member Functions inherited from ICat4::xsd__anyType
virtual void soap_default (struct soap *)
virtual void * soap_get (struct soap *, const char *, const char *)
virtual void * soap_in (struct soap *, const char *, const char *)
virtual int soap_out (struct soap *, const char *, int, const char *) const
virtual int soap_put (struct soap *, const char *, const char *) const
virtual void soap_serialize (struct soap *) const
virtual int soap_type () const
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
LONG64 primaryKey
std::string * query
std::string * sessionId
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 615 of file ICat4Stub.h.
Constructor & Destructor Documentation
ns1__get()
ICat4::ns1__get::ns1__get () inline
Definition at line 628 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::ns1__get::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20608 of file ICat4C.cpp.
References ICat4::soap_default_LONG64().
Referenced by ICat4::soap_in_ns1__get(), ICat4::soap_new_req_ns1__get(), and ICat4::soap_new_set_ns1__get().
soap_get()
void * ICat4::ns1__get::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20721 of file ICat4C.cpp.
References ICat4::soap_get_ns1__get().
soap_in()
void * ICat4::ns1__get::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20644 of file ICat4C.cpp.
References ICat4::soap_in_ns1__get().
Referenced by ICat4::soap_in_ns1__get().
soap_out()
int ICat4::ns1__get::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20626 of file ICat4C.cpp.
References ICat4::soap_out_ns1__get().
soap_put()
int ICat4::ns1__get::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20714 of file ICat4C.cpp.
References ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_ns1__get.
soap_serialize()
void ICat4::ns1__get::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 20616 of file ICat4C.cpp.
References ICat4::soap_serialize_PointerTostd__string(), and SOAP_TYPE_ICat4_LONG64.
soap_type()
int ICat4::ns1__get::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 621 of file ICat4Stub.h.
Member Data Documentation
primaryKey
LONG64 ICat4::ns1__get::primaryKey
Definition at line 619 of file ICat4Stub.h.
query
std::string* ICat4::ns1__get::query
Definition at line 618 of file ICat4Stub.h.
sessionId
std::string* ICat4::ns1__get::sessionId
Definition at line 617 of file ICat4Stub.h.
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp