Mantid: Mantid::CurveFitting Namespace Reference
Mantid::CurveFitting Namespace Reference
Namespaces
namespace Algorithms
namespace Constraints
namespace CostFunctions
namespace FuncMinimisers
namespace Functions
namespace MSVesuvioHelper
namespace MuonHelper
namespace NLLS
namespace ParameterEstimator
namespace SpecialFunctionSupport
Classes
class AugmentedLagrangianOptimizer
Implements the Augmented Lagrangian optimization method of Birgin & Martinez.
class ComplexMatrix
A complex-valued matrix for linear algebra computations.
class ComplexVector
A complex-valued vector for linear algebra computations.
class CrystalFieldEnergies
CrystalFieldEnergies : Calculates crystal field energies and wave functions for rare earth ions given the field parameters.
class EigenJacobian
Two implementations of Jacobian.
class EigenMatrix
A wrapper around Eigen::Matrix.
class EigenMatrix_View
class EigenVector
A wrapper around Eigen::Vector.
class EigenVector_View
class ExcludeRangeFinder
ExcludeRangeFinder : Helper clss that finds if a point should be excluded from fit.
class FitMW
Creates FunctionDomain1D form a spectrum in a MatrixWorkspace.
class FortranMatrix
FortranMatrix is a wrapper template for EigenMatrix and EigenComplexMatrix to simplify porting fortran programs to C++.
class FortranVector
FortranVector is a wrapper template for EigenVactor and EigenComplexVector to simplify porting fortran programs to C++.
class FunctionDomain1DSpectrumCreator
FunctionDomain1DSpectrumCreator :
class GeneralDomainCreator
GeneralDomainCreator:
struct GSL_FitData
Various GSL specific functions used GSL specific minimizers.
class HalfComplex
Class for helping to read the transformed data.
class HistogramDomainCreator
HistogramDomainCreator:
class IFittingAlgorithm
A base class for fitting algorithms.
class IMWDomainCreator
A base class for domain creators taking 1D data from a spectrum of a matrix workspace.
class Jacobian
An implementation of Jacobian using std::vector.
class JacobianImpl1
The implementation of Jacobian.
class LatticeDomainCreator
LatticeDomainCreator.
class LatticeFunction
LatticeFunction.
class MultiDomainCreator
Creates a composite domain.
class ParDomain
An implementation of SeqDomain for parallel cost function and derivatives computation.
class SeqDomain
An implementation of CompositeDomain.
class SeqDomainSpectrumCreator
SeqDomainSpectrumCreator :
class TableWorkspaceDomainCreator
Typedefs
typedef Eigen::Map< Eigen::VectorXcd, 0, dynamic_stride > complex_vec_map_type
using ComplexFortranMatrix = FortranMatrix< ComplexMatrix >
using ComplexFortranVector = FortranVector< ComplexVector >
using ComplexType = std::complex< double >
typedef Eigen::Map< const Eigen::MatrixXd, 0, dynamic_stride > const_map_type
using DoubleFortranMatrix = FortranMatrix< EigenMatrix >
using DoubleFortranVector = FortranVector< EigenVector >
typedef Eigen::Stride< Eigen::Dynamic, Eigen::Dynamic > dynamic_stride
using IntFortranVector = FortranVector< std::vector< int > >
using LatticeFunction_sptr = std::shared_ptr< LatticeFunction >
typedef Eigen::Map< Eigen::MatrixXd, 0, dynamic_stride > map_type
typedef Eigen::Map< const Eigen::VectorXd, 0, dynamic_stride > vec_const_map_type
typedef Eigen::Map< Eigen::VectorXd, 0, dynamic_stride > vec_map_type
Enumerations
enum OptimizerResult { Failure = -1 , Success = 1 , FTolReached = 2 , XTolReached = 3 }
The results of the optimization.
Functions
gsl_matrix_view getGSLMatrixView (map_type &tr)
take data from an Eigen Matrix and return a transposed a gsl view.
gsl_matrix_const_view const getGSLMatrixView_const (const map_type m)
take data from a constEigen Matrix and return a transposed gsl view.
gsl_vector_view getGSLVectorView (vec_map_type &v)
take data from Eigen Vector and take a gsl view
gsl_vector_const_view const getGSLVectorView_const (const vec_map_type v)
take const data from Eigen Vector and take a gsl view
int gsl_df (const gsl_vector *x, void *params, gsl_matrix *J)
Fit GSL derivative function wrapper.
int gsl_f (const gsl_vector *x, void *params, gsl_vector *f)
Fit GSL function wrapper.
int gsl_fdf (const gsl_vector *x, void *params, gsl_vector *f, gsl_matrix *J)
Fit derivatives and function GSL wrapper.
std::ostream & operator<< (std::ostream &ostr, const ComplexMatrix &m)
The << operator. Prints a matrix in rows.
MANTID_CURVEFITTING_DLL std::ostream & operator<< (std::ostream &ostr, const ComplexVector &v)
The << operator.
std::ostream & operator<< (std::ostream &ostr, const EigenMatrix &m)
The << operator. Prints a matrix in rows.
MANTID_CURVEFITTING_DLL std::ostream & operator<< (std::ostream &ostr, const EigenVector &v)
The << operator.
Typedef Documentation
complex_vec_map_type
typedef Eigen::Map<Eigen::VectorXcd, 0, dynamic_stride> Mantid::CurveFitting::complex_vec_map_type
Definition at line 23 of file EigenComplexVector.h.
ComplexFortranMatrix
using Mantid::CurveFitting::ComplexFortranMatrix = typedef FortranMatrix<ComplexMatrix>
Definition at line 17 of file EigenFortranDefs.h.
ComplexFortranVector
using Mantid::CurveFitting::ComplexFortranVector = typedef FortranVector<ComplexVector>
Definition at line 19 of file EigenFortranDefs.h.
ComplexType
using Mantid::CurveFitting::ComplexType = typedef std::complex<double>
Definition at line 19 of file EigenComplexVector.h.
const_map_type
typedef Eigen::Map<const Eigen::MatrixXd, 0, dynamic_stride> Mantid::CurveFitting::const_map_type
Definition at line 19 of file EigenMatrixView.h.
DoubleFortranMatrix
using Mantid::CurveFitting::DoubleFortranMatrix = typedef FortranMatrix<EigenMatrix>
Definition at line 18 of file EigenFortranDefs.h.
DoubleFortranVector
using Mantid::CurveFitting::DoubleFortranVector = typedef FortranVector<EigenVector>
Definition at line 20 of file EigenFortranDefs.h.
dynamic_stride
typedef Eigen::Stride< Eigen::Dynamic, Eigen::Dynamic > Mantid::CurveFitting::dynamic_stride
Definition at line 22 of file EigenComplexVector.h.
IntFortranVector
using Mantid::CurveFitting::IntFortranVector = typedef FortranVector<std::vector<int> >
Definition at line 21 of file EigenFortranDefs.h.
LatticeFunction_sptr
using Mantid::CurveFitting::LatticeFunction_sptr = typedef std::shared_ptr<LatticeFunction>
Definition at line 49 of file LatticeFunction.h.
map_type
typedef Eigen::Map<Eigen::MatrixXd, 0, dynamic_stride> Mantid::CurveFitting::map_type
Definition at line 18 of file EigenMatrixView.h.
vec_const_map_type
typedef Eigen::Map<const Eigen::VectorXd, 0, dynamic_stride> Mantid::CurveFitting::vec_const_map_type
Definition at line 15 of file EigenVectorView.h.
vec_map_type
typedef Eigen::Map<Eigen::VectorXd, 0, dynamic_stride> Mantid::CurveFitting::vec_map_type
Definition at line 14 of file EigenVectorView.h.
Enumeration Type Documentation
OptimizerResult
enum Mantid::CurveFitting::OptimizerResult
The results of the optimization.
Enumerator
Failure
Success
FTolReached
XTolReached
Definition at line 19 of file AugmentedLagrangianOptimizer.h.
Function Documentation
getGSLMatrixView()
gsl_matrix_view Mantid::CurveFitting::getGSLMatrixView (map_type & tr) inline
take data from an Eigen Matrix and return a transposed a gsl view.
Definition at line 56 of file GSLFunctions.h.
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncFitting::calActiveCovarianceMatrix(), and Mantid::CurveFitting::Functions::ChebfunBase::roots().
getGSLMatrixView_const()
gsl_matrix_const_view const Mantid::CurveFitting::getGSLMatrixView_const (const map_type m) inline
take data from a constEigen Matrix and return a transposed gsl view.
Definition at line 63 of file GSLFunctions.h.
References Mantid::Geometry::m.
Referenced by Mantid::CurveFitting::CostFunctions::CostFuncFitting::calActiveCovarianceMatrix(), and Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate().
getGSLVectorView()
gsl_vector_view Mantid::CurveFitting::getGSLVectorView (vec_map_type & v) inline
take data from Eigen Vector and take a gsl view
Definition at line 54 of file GSLFunctions.h.
Referenced by Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate(), and Mantid::CurveFitting::FuncMinimisers::DampedGaussNewtonMinimizer::iterate().
getGSLVectorView_const()
gsl_vector_const_view const Mantid::CurveFitting::getGSLVectorView_const (const vec_map_type v) inline
take const data from Eigen Vector and take a gsl view
Definition at line 59 of file GSLFunctions.h.
Referenced by Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMDMinimizer::iterate().
gsl_df()
int Mantid::CurveFitting::gsl_df (const gsl_vector * x, void * params, gsl_matrix * J)
Fit GSL derivative function wrapper.
Parameters
x :: Input function arguments
params :: Input data
J :: Output derivatives
Returns
A GSL status information
Definition at line 84 of file GSLFunctions.cpp.
References Mantid::API::IConstraint::checkDeriv2(), Mantid::Geometry::m, Mantid::CurveFitting::EigenMatrix::mutator(), n, and Mantid::Geometry::x.
Referenced by Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::gsl_df(), Mantid::CurveFitting::Algorithms::gsl_fdf(), gsl_fdf(), and Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMinimizer::initialize().
gsl_f()
int Mantid::CurveFitting::gsl_f (const gsl_vector * x, void * params, gsl_vector * f)
Fit GSL function wrapper.
Parameters
x :: Input function parameters
params :: Input data
f :: Output function values = (y_cal-y_data)/sigma for each data point
Returns
A GSL status information
Definition at line 22 of file GSLFunctions.cpp.
References Mantid::API::IConstraint::checkDeriv(), Mantid::CurveFitting::GSL_FitData::function, n, and Mantid::Geometry::x.
Referenced by Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::gsl_f(), Mantid::CurveFitting::Algorithms::gsl_fdf(), gsl_fdf(), and Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMinimizer::initialize().
gsl_fdf()
int Mantid::CurveFitting::gsl_fdf (const gsl_vector * x, void * params, gsl_vector * f, gsl_matrix * J)
Fit derivatives and function GSL wrapper.
Parameters
x :: Input function arguments
params :: Input data
f :: Output function values = (y_cal-y_cal)/sigma for each data point
J :: Output derivatives
Returns
A GSL status information
Definition at line 158 of file GSLFunctions.cpp.
References gsl_df(), gsl_f(), and Mantid::Geometry::x.
Referenced by Mantid::CurveFitting::Algorithms::Fit1D::exec(), Mantid::CurveFitting::Algorithms::gsl_fdf(), and Mantid::CurveFitting::FuncMinimisers::LevenbergMarquardtMinimizer::initialize().
operator<<() [1/4]
std::ostream & Mantid::CurveFitting::operator<< (std::ostream & ostr, const ComplexMatrix & m) inline
The << operator. Prints a matrix in rows.
Definition at line 130 of file EigenComplexMatrix.h.
References Mantid::Geometry::m, and value.
operator<<() [2/4]
std::ostream & Mantid::CurveFitting::operator<< (std::ostream & ostr, const ComplexVector & v)
The << operator.
Definition at line 151 of file EigenComplexVector.cpp.
References Mantid::CurveFitting::ComplexVector::get(), Mantid::CurveFitting::ComplexVector::size(), and value.
operator<<() [3/4]
std::ostream & Mantid::CurveFitting::operator<< (std::ostream & ostr, const EigenMatrix & m) inline
The << operator. Prints a matrix in rows.
Definition at line 135 of file EigenMatrix.h.
References Mantid::Geometry::m.
operator<<() [4/4]
std::ostream & Mantid::CurveFitting::operator<< (std::ostream & ostr, const EigenVector & v)
The << operator.
Definition at line 282 of file EigenVector.cpp.
References Mantid::CurveFitting::EigenVector::size().