Mantid: Framework/DataHandling/src/LoadRaw/vms_convert.h File Reference
vms_convert.h File Reference
Typedefs
using fort_int = int
Functions
void ieee_double_to_local (const double *val, const int *n, int *errcode)
void ieee_float_to_local (const float *val, const int *n, int *errcode)
void local_to_ieee_double (const double *val, const int *n, int *errcode)
void local_to_ieee_float (const float *val, const int *n, int *errcode)
unsigned local_to_vax_int (const fort_int *i)
void local_to_vax_ints (const fort_int *ia, const fort_int *n)
unsigned short local_to_vax_short (const unsigned short *s)
void local_to_vax_shorts (const unsigned short *sa, const int *n)
void local_to_vaxf (float *val, const int *n, int *errcode)
unsigned vax_to_local_int (const fort_int *i)
void vax_to_local_ints (const fort_int *ia, const fort_int *n)
unsigned short vax_to_local_short (const unsigned short *s)
void vax_to_local_shorts (const unsigned short *sa, const int *n)
void vaxf_to_local (float *val, const int *n, int *errcode)
Typedef Documentation
fort_int
using fort_int = int
Definition at line 17 of file vms_convert.h.
Function Documentation
ieee_double_to_local()
void ieee_double_to_local (const double * val, const int * n, int * errcode)
Definition at line 415 of file vms_convert.cpp.
References n.
ieee_float_to_local()
void ieee_float_to_local (const float * val, const int * n, int * errcode)
Definition at line 395 of file vms_convert.cpp.
References n.
local_to_ieee_double()
void local_to_ieee_double (const double * val, const int * n, int * errcode)
Definition at line 457 of file vms_convert.cpp.
References n.
local_to_ieee_float()
void local_to_ieee_float (const float * val, const int * n, int * errcode)
Definition at line 436 of file vms_convert.cpp.
References n.
local_to_vax_int()
unsigned local_to_vax_int (const fort_int * i)
Definition at line 56 of file vms_convert.cpp.
References swap_int.
local_to_vax_ints()
void local_to_vax_ints (const fort_int * ia, const fort_int * n)
Definition at line 94 of file vms_convert.cpp.
References n, and swap_int.
local_to_vax_short()
unsigned short local_to_vax_short (const unsigned short * s)
Definition at line 40 of file vms_convert.cpp.
References swap_short.
local_to_vax_shorts()
void local_to_vax_shorts (const unsigned short * sa, const int * n)
Definition at line 72 of file vms_convert.cpp.
References n, and swap_short.
local_to_vaxf()
void local_to_vaxf (float * val, const int * n, int * errcode)
Definition at line 380 of file vms_convert.cpp.
References ieee_to_vax_float(), and n.
Referenced by ISISRAW::ioRAW().
vax_to_local_int()
unsigned vax_to_local_int (const fort_int * i)
Definition at line 64 of file vms_convert.cpp.
References swap_int.
vax_to_local_ints()
void vax_to_local_ints (const fort_int * ia, const fort_int * n)
Definition at line 106 of file vms_convert.cpp.
References n, and swap_int.
vax_to_local_short()
unsigned short vax_to_local_short (const unsigned short * s)
Definition at line 48 of file vms_convert.cpp.
References swap_short.
vax_to_local_shorts()
void vax_to_local_shorts (const unsigned short * sa, const int * n)
Definition at line 83 of file vms_convert.cpp.
References n, and swap_short.
vaxf_to_local()
void vaxf_to_local (float * val, const int * n, int * errcode)
Definition at line 353 of file vms_convert.cpp.
References n, and vax_to_ieee_float().
Referenced by ISISRAW::ioRAW().