Mantid: Mantid::PythonInterface::PyNativeTypeExtractor Struct Reference
Mantid::PythonInterface::PyNativeTypeExtractor Struct Reference
#include <PyNativeTypeExtractor.h>
Public Types
using PythonOutputT = boost::make_recursive_variant< bool, int, double, std::string, Mantid::API::Workspace_sptr, std::vector< boost::recursive_variant_ > >::type
Static Public Member Functions
static PythonOutputT convert (const boost::python::object &obj)
Static Private Member Functions
static PythonOutputT handleList (const boost::python::object &obj)
Detailed Description
Definition at line 27 of file PyNativeTypeExtractor.h.
Member Typedef Documentation
PythonOutputT
using Mantid::PythonInterface::PyNativeTypeExtractor::PythonOutputT = boost::make_recursive_variant<bool, int, double, std::string, Mantid::API::Workspace_sptr, std::vector<boost::recursive_variant_> >::type
Definition at line 28 of file PyNativeTypeExtractor.h.
Member Function Documentation
convert()
static PythonOutputT Mantid::PythonInterface::PyNativeTypeExtractor::convert (const boost::python::object & obj) inline static
Definition at line 31 of file PyNativeTypeExtractor.h.
References handleList(), and obj.
Referenced by handleList().
handleList()
static PythonOutputT Mantid::PythonInterface::PyNativeTypeExtractor::handleList (const boost::python::object & obj) inline static private
Definition at line 55 of file PyNativeTypeExtractor.h.
References convert(), n, obj, and vec.
Referenced by convert().
The documentation for this struct was generated from the following file:
Framework/PythonInterface/core/inc/MantidPythonInterface/core/Converters/PyNativeTypeExtractor.h