Mantid: Mantid::Geometry::MDHistoDimensionBuilder Class Reference
Mantid::Geometry::MDHistoDimensionBuilder Class Reference
MDHistoDimensionBuilder :
#include <MDHistoDimensionBuilder.h>
Public Member Functions
IMDDimension_sptr create ()
MDHistoDimension * createRaw ()
size_t getNumBins () const
MDHistoDimensionBuilder ()
Constructor.
void setFrameName (std::string frameName)
Setter for the frame name.
void setId (std::string id)
void setMax (double max)
void setMin (double min)
void setName (const std::string &name)
void setNumBins (size_t nbins)
void setUnits (const Kernel::UnitLabel &units)
Static Public Member Functions
template<typename CoordT >
static void resizeToFitMDBox (CoordT &min, CoordT &max)
Push the min/max values out by a defined amount.
Private Attributes
std::string m_frameName
Frame name.
std::string m_id
Cached id.
double m_max
Cached max.
bool m_maxSet
Flag indicating that max has been set.
double m_min
Cached min.
bool m_minSet
Flag indicating that min has been set.
std::string m_name
Cached name.
size_t m_nbins
Cached nbins.
Kernel::UnitLabel m_units
Cached units.
Detailed Description
MDHistoDimensionBuilder :
A builder for the MDHistogram workspace. Required to construct a valid MDHistogram dimension, where values can cannot easily be brought togeter at once. Also allows potential construction values to be overwritten simply.
Author
Owen Arnold @ Tessella/ISIS
Date
13/July/2011
Definition at line 28 of file MDHistoDimensionBuilder.h.
Constructor & Destructor Documentation
MDHistoDimensionBuilder()
Mantid::Geometry::MDHistoDimensionBuilder::MDHistoDimensionBuilder ()
Constructor.
Definition at line 17 of file MDHistoDimensionBuilder.cpp.
Member Function Documentation
create()
IMDDimension_sptr Mantid::Geometry::MDHistoDimensionBuilder::create ()
Definition at line 113 of file MDHistoDimensionBuilder.cpp.
References createRaw().
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
createRaw()
MDHistoDimension * Mantid::Geometry::MDHistoDimensionBuilder::createRaw ()
Definition at line 76 of file MDHistoDimensionBuilder.cpp.
References Mantid::Kernel::UnitLabel::ascii(), m_frameName, m_id, m_max, m_maxSet, m_min, m_minSet, m_name, m_nbins, m_units, and Mantid::Geometry::makeMDFrameFactoryChain().
Referenced by create().
getNumBins()
size_t Mantid::Geometry::MDHistoDimensionBuilder::getNumBins () const inline
Definition at line 60 of file MDHistoDimensionBuilder.h.
resizeToFitMDBox()
template<typename CoordT > static void Mantid::Geometry::MDHistoDimensionBuilder::resizeToFitMDBox (CoordT & min, CoordT & max) inline static
Push the min/max values out by a defined amount.
This is primarily used for moving the dimensions boundaries so that an MDGridBox can encompass all of the data and not chop of events if some events lie exactly on a boundary
Parameters
min A reference to the minimum value [InOut]
max A reference to the maximum value [InOut]
Definition at line 38 of file MDHistoDimensionBuilder.h.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::LoadSQW2::createQDimension(), and Mantid::MDAlgorithms::ConvertToMD::findMinMax().
setFrameName()
void Mantid::Geometry::MDHistoDimensionBuilder::setFrameName (std::string frameName)
Setter for the frame name.
Parameters
frameName the frame name
Definition at line 70 of file MDHistoDimensionBuilder.cpp.
References m_frameName.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setId()
void Mantid::Geometry::MDHistoDimensionBuilder::setId (std::string id)
Definition at line 34 of file MDHistoDimensionBuilder.cpp.
References m_id.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setMax()
void Mantid::Geometry::MDHistoDimensionBuilder::setMax (double max)
Definition at line 55 of file MDHistoDimensionBuilder.cpp.
References m_max, and m_maxSet.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setMin()
void Mantid::Geometry::MDHistoDimensionBuilder::setMin (double min)
Definition at line 46 of file MDHistoDimensionBuilder.cpp.
References m_min, and m_minSet.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setName()
void Mantid::Geometry::MDHistoDimensionBuilder::setName (const std::string & name)
Definition at line 25 of file MDHistoDimensionBuilder.cpp.
References m_name, name, and Mantid::Kernel::Strings::strip().
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setNumBins()
void Mantid::Geometry::MDHistoDimensionBuilder::setNumBins (size_t nbins)
Definition at line 64 of file MDHistoDimensionBuilder.cpp.
References m_nbins.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
setUnits()
void Mantid::Geometry::MDHistoDimensionBuilder::setUnits (const Kernel::UnitLabel & units)
Definition at line 40 of file MDHistoDimensionBuilder.cpp.
References m_units.
Referenced by Mantid::MDAlgorithms::LoadSQW2::createEnDimension(), Mantid::MDAlgorithms::FitMD::createEventOutputWorkspace(), and Mantid::MDAlgorithms::LoadSQW2::createQDimension().
Member Data Documentation
m_frameName
std::string Mantid::Geometry::MDHistoDimensionBuilder::m_frameName private
Frame name.
Definition at line 82 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setFrameName().
m_id
std::string Mantid::Geometry::MDHistoDimensionBuilder::m_id private
Cached id.
Definition at line 68 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setId().
m_max
double Mantid::Geometry::MDHistoDimensionBuilder::m_max private
Cached max.
Definition at line 74 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setMax().
m_maxSet
bool Mantid::Geometry::MDHistoDimensionBuilder::m_maxSet private
Flag indicating that max has been set.
Definition at line 80 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setMax().
m_min
double Mantid::Geometry::MDHistoDimensionBuilder::m_min private
Cached min.
Definition at line 72 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setMin().
m_minSet
bool Mantid::Geometry::MDHistoDimensionBuilder::m_minSet private
Flag indicating that min has been set.
Definition at line 78 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setMin().
m_name
std::string Mantid::Geometry::MDHistoDimensionBuilder::m_name private
Cached name.
Definition at line 66 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setName().
m_nbins
size_t Mantid::Geometry::MDHistoDimensionBuilder::m_nbins private
Cached nbins.
Definition at line 76 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setNumBins().
m_units
Kernel::UnitLabel Mantid::Geometry::MDHistoDimensionBuilder::m_units private
Cached units.
Definition at line 70 of file MDHistoDimensionBuilder.h.
Referenced by createRaw(), and setUnits().
The documentation for this class was generated from the following files:
Framework/Geometry/inc/MantidGeometry/MDGeometry/MDHistoDimensionBuilder.h
Framework/Geometry/src/MDGeometry/MDHistoDimensionBuilder.cpp