Mantid: Mantid::Kernel::ListValidator< TYPE > Class Template Reference
Mantid::Kernel::ListValidator< TYPE > Class Template Reference
ListValidator is a validator that requires the value of a property to be one of a defined list of possibilities.
#include <ListValidator.h>
Public Member Functions
void addAllowedValue (const TYPE &value)
Add value to the list of allowable values if it's not already there.
std::vector< std::string > allowedValues () const override
Returns the set of allowed values currently defined.
IValidator_sptr clone () const override
Clone the validator.
std::string getValueForAlias (const std::string &alias) const override
Return an allowed value (as a string) given an alias.
bool isMultipleSelectionAllowed () override
ListValidator ()
Default constructor. Sets up an empty list of valid values.
template<typename T >
ListValidator (const T &values, const std::map< std::string, std::string > &aliases=std::map< std::string, std::string >(), const bool allowMultiSelection=false)
Constructor.
void setMultipleSelectionAllowed (const bool isMultiSelectionAllowed)
Protected Member Functions
std::string checkValidity (const TYPE &value) const override
Checks if the string passed is in the list.
bool isAlias (const std::string &value) const
Test if a value is an alias of an alowed value.
template<typename T >
bool isAlias (const T &value) const
Test if a value is an alias of an alowed value.
bool isEmpty (const std::string &value) const
Is the value considered empty.
template<typename T >
bool isEmpty (const T &value) const
Is the value considered empty.
Protected Attributes
std::map< std::string, std::string > m_aliases
The optional aliases for the allowed values.
std::vector< TYPE > m_allowedValues
The set of valid values.
bool m_allowMultiSelection
if the validator should allow multiple selection
Detailed Description
template<typename TYPE>
class Mantid::Kernel::ListValidator< TYPE >
ListValidator is a validator that requires the value of a property to be one of a defined list of possibilities.
The default type is std::string
Author
Russell Taylor, Tessella Support Services plc
Date
18/06/2008
Definition at line 29 of file ListValidator.h.
Constructor & Destructor Documentation
ListValidator() [1/2]
template<typename TYPE > Mantid::Kernel::ListValidator< TYPE >::ListValidator () inline
Default constructor. Sets up an empty list of valid values.
Definition at line 32 of file ListValidator.h.
ListValidator() [2/2]
template<typename TYPE > template<typename T > Mantid::Kernel::ListValidator< TYPE >::ListValidator (const T & values, const std::map< std::string, std::string > & aliases = std::map<std::string, std::string>(), const bool allowMultiSelection = false) inline explicit
Constructor.
Parameters
values :: An iterable type of the valid values
aliases :: Optional aliases for the valid values.
allowMultiSelection :: True if the list allows multi selection
Definition at line 40 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_aliases, and Mantid::Kernel::ListValidator< TYPE >::m_allowMultiSelection.
Member Function Documentation
addAllowedValue()
template<typename TYPE > void Mantid::Kernel::ListValidator< TYPE >::addAllowedValue (const TYPE & value) inline
Add value to the list of allowable values if it's not already there.
Parameters
value :: A value of the templated type
Definition at line 76 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_allowedValues, and value.
allowedValues()
template<typename TYPE > std::vector< std::string > Mantid::Kernel::ListValidator< TYPE >::allowedValues () const inline override
Returns the set of allowed values currently defined.
Returns
A set of allowed values that this validator will currently allow
The interface requires strings
Definition at line 61 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_allowedValues.
checkValidity()
template<typename TYPE > std::string Mantid::Kernel::ListValidator< TYPE >::checkValidity (const TYPE & value) const inline override protected
Checks if the string passed is in the list.
Parameters
value :: The value to test
Returns
"" if the value is on the list, or "The value is not in the list of allowed values"
Definition at line 111 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::isAlias(), Mantid::Kernel::ListValidator< TYPE >::isEmpty(), Mantid::Kernel::ListValidator< TYPE >::m_allowedValues, and value.
clone()
template<typename TYPE > IValidator_sptr Mantid::Kernel::ListValidator< TYPE >::clone () const inline override
Clone the validator.
Definition at line 56 of file ListValidator.h.
getValueForAlias()
template<typename TYPE > std::string Mantid::Kernel::ListValidator< TYPE >::getValueForAlias (const std::string & alias) const inline override
Return an allowed value (as a string) given an alias.
Parameters
alias :: An alias string.
Returns
:: Allowed value or throw if alias is unknown.
Definition at line 88 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_aliases.
isAlias() [1/2]
template<typename TYPE > bool Mantid::Kernel::ListValidator< TYPE >::isAlias (const std::string & value) const inline protected
Test if a value is an alias of an alowed value.
Parameters
value :: Value to test.
Returns
:: True if it's an alias.
Definition at line 153 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_aliases, and value.
isAlias() [2/2]
template<typename TYPE > template<typename T > bool Mantid::Kernel::ListValidator< TYPE >::isAlias (const T & value) const inline protected
Test if a value is an alias of an alowed value.
Parameters
value :: Value to test.
Returns
:: True if it's an alias.
Definition at line 143 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_aliases, and value.
Referenced by Mantid::Kernel::ListValidator< TYPE >::checkValidity().
isEmpty() [1/2]
template<typename TYPE > bool Mantid::Kernel::ListValidator< TYPE >::isEmpty (const std::string & value) const inline protected
Is the value considered empty.
Specialized string version to use empty
Parameters
value :: The value to check
Returns
True if it is considered empty
Definition at line 136 of file ListValidator.h.
References value.
isEmpty() [2/2]
template<typename TYPE > template<typename T > bool Mantid::Kernel::ListValidator< TYPE >::isEmpty (const T & value) const inline protected
Is the value considered empty.
Parameters
value :: The value to check
Returns
True if it is considered empty
Definition at line 130 of file ListValidator.h.
References UNUSED_ARG, and value.
Referenced by Mantid::Kernel::StartsWithValidator::checkValidity(), and Mantid::Kernel::ListValidator< TYPE >::checkValidity().
isMultipleSelectionAllowed()
template<typename TYPE > bool Mantid::Kernel::ListValidator< TYPE >::isMultipleSelectionAllowed () inline override
Definition at line 96 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_allowMultiSelection.
setMultipleSelectionAllowed()
template<typename TYPE > void Mantid::Kernel::ListValidator< TYPE >::setMultipleSelectionAllowed (const bool isMultiSelectionAllowed) inline
Definition at line 98 of file ListValidator.h.
References Mantid::Kernel::ListValidator< TYPE >::m_allowMultiSelection.
Member Data Documentation
m_aliases
template<typename TYPE > std::map<std::string, std::string> Mantid::Kernel::ListValidator< TYPE >::m_aliases protected
The optional aliases for the allowed values.
Definition at line 158 of file ListValidator.h.
Referenced by Mantid::Kernel::ListValidator< TYPE >::getValueForAlias(), Mantid::Kernel::ListValidator< TYPE >::isAlias(), and Mantid::Kernel::ListValidator< TYPE >::ListValidator().
m_allowedValues
template<typename TYPE > std::vector<TYPE> Mantid::Kernel::ListValidator< TYPE >::m_allowedValues protected
The set of valid values.
Definition at line 156 of file ListValidator.h.
Referenced by Mantid::Kernel::ListValidator< TYPE >::addAllowedValue(), Mantid::Kernel::ListValidator< TYPE >::allowedValues(), Mantid::Kernel::StartsWithValidator::checkValidity(), and Mantid::Kernel::ListValidator< TYPE >::checkValidity().
m_allowMultiSelection
template<typename TYPE > bool Mantid::Kernel::ListValidator< TYPE >::m_allowMultiSelection protected
if the validator should allow multiple selection
Definition at line 161 of file ListValidator.h.
Referenced by Mantid::Kernel::ListValidator< TYPE >::isMultipleSelectionAllowed(), Mantid::Kernel::ListValidator< TYPE >::ListValidator(), and Mantid::Kernel::ListValidator< TYPE >::setMultipleSelectionAllowed().
The documentation for this class was generated from the following file:
Framework/Kernel/inc/MantidKernel/ListValidator.h