Mantid: Mantid::Algorithms::PDCalibration Class Reference
Mantid::Algorithms::PDCalibration Class Reference final
PDCalibration : TODO: DESCRIPTION.
#include <PDCalibration.h>
Classes
class FittedPeaks
private inner class
Public Member Functions
const std::string category () const override
Algorithm's category for identification.
const std::string name () const override
Algorithms name for identification.
PDCalibration ()
Constructor.
const std::string summary () const override
Algorithm's summary for use in the GUI and help.
int version () const override
Algorithm's version for identification.
~PDCalibration () override
Destructor.
Public Member Functions inherited from Mantid::API::Algorithm
Algorithm ()
Constructor.
Algorithm (const Algorithm &)=delete
Algorithm & operator= (const Algorithm &)=delete
~Algorithm () override
Virtual destructor.
void initialize () override
Initialization method invoked by the framework.
bool execute () override final
The actions to be performed by the algorithm on a dataset.
void addTimer (const std::string &name, const Kernel::time_point_ns &begin, const Kernel::time_point_ns &end)
void executeAsChildAlg () override
Execute as a Child Algorithm.
std::map< std::string, std::string > validateInputs () override
Perform validation of ALL the input properties of the algorithm.
ExecutionState executionState () const override
Gets the current execution state.
ResultState resultState () const override
Gets the current result State.
bool isInitialized () const override
Has the Algorithm already been initialized.
bool isExecuted () const override
Has the Algorithm already been executed successfully.
bool isRunning () const override
True if the algorithm is running.
bool isReadyForGarbageCollection () const override
True if the algorithm is ready for garbage collection.
bool isChild () const override
To query whether algorithm is a child.
void setChild (const bool isChild) override
To set whether algorithm is a child.
void enableHistoryRecordingForChild (const bool on) override
Change the state of the history recording flag.
bool isRecordingHistoryForChild ()
void setAlwaysStoreInADS (const bool doStore) override
Do we ALWAYS store in the AnalysisDataService? This is set to true for python algorithms' child algorithms.
bool getAlwaysStoreInADS () const override
Returns true if we always store in the AnalysisDataService.
void setRethrows (const bool rethrow) override
Set whether the algorithm will rethrow exceptions.
Poco::ActiveResult< bool > executeAsync () override
Asynchronous execution.
void addObserver (const Poco::AbstractObserver &observer) const override
Add an observer for a notification.
void removeObserver (const Poco::AbstractObserver &observer) const override
Remove an observer.
void cancel () override
Raises the cancel flag.
bool getCancel () const
Returns the cancellation state.
Kernel::Logger & getLogger () const
Returns a reference to the logger.
void setLogging (const bool value) override
Logging can be disabled by passing a value of false.
bool isLogging () const override
returns the status of logging, True = enabled
void setLoggingOffset (const int value) override
gets the logging priority offset
int getLoggingOffset () const override
returns the logging priority offset
void setAlgStartupLogging (const bool enabled) override
disable Logging of start and end messages
bool getAlgStartupLogging () const override
get the state of Logging of start and end messages
void setChildStartProgress (const double startProgress) const override
setting the child start progress
void setChildEndProgress (const double endProgress) const override
setting the child end progress
std::string toString () const override
Serialize an object to a string.
::Json::Value toJson () const override
Serialize an object to a json object.
virtual std::shared_ptr< Algorithm > createChildAlgorithm (const std::string &name, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true, const int &version=-1)
Create a Child Algorithm.
void setupAsChildAlgorithm (const Algorithm_sptr &algorithm, const double startProgress=-1., const double endProgress=-1., const bool enableLogging=true)
Setup algorithm as child algorithm.
void trackAlgorithmHistory (std::shared_ptr< AlgorithmHistory > parentHist)
set whether we wish to track the child algorithm's history and pass it the parent object to fill.
void findWorkspaces (WorkspaceVector &workspaces, unsigned int direction, bool checkADS=false) const
Populate lists of the workspace properties for a given direction (InOut workspaces are included in both input/output)
virtual bool checkGroups ()
Check the input workspace properties for groups.
virtual bool processGroups ()
Process WorkspaceGroup inputs.
void copyNonWorkspaceProperties (IAlgorithm *alg, int periodNum)
Copy all the non-workspace properties from this to alg.
void declareProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add a property to the list of managed properties.
void declareOrReplaceProperty (std::unique_ptr< Kernel::Property > p, const std::string &doc="") override
Add or replace property in the list of managed properties.
void resetProperties () override
Reset property values back to initial values (blank or default values)
void setProperties (const std::string &propertiesJson, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Set the ordered list of properties by one string of values, separated by semicolons.
void setProperties (const ::Json::Value &jsonValue, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >(), bool createMissing=false) override
Sets all the declared properties from a json object.
void setPropertiesWithString (const std::string &propertiesString, const std::unordered_set< std::string > &ignoreProperties=std::unordered_set< std::string >()) override
Sets all the declared properties from a string.
void setPropertyValue (const std::string &name, const std::string &value) override
Set the value of a property by string N.B.
void setPropertyValueFromJson (const std::string &name, const Json::Value &value) override
Set the value of a property by Json::Value object.
void setPropertyOrdinal (const int &index, const std::string &value) override
Set the value of a property by an index N.B.
virtual void copyPropertiesFrom (const Algorithm &alg)
Make m_properties point to the same PropertyManager as alg.m_properties.
bool existsProperty (const std::string &name) const override
Checks whether the named property is already in the list of managed property.
bool validateProperties () const override
Validates all the properties in the collection.
size_t propertyCount () const override
Count the number of properties under management.
std::string getPropertyValue (const std::string &name) const override
Get the value of a property as a string.
const std::vector< Kernel::Property * > & getProperties () const override
Get the list of managed properties.
std::vector< std::string > getDeclaredPropertyNames () const noexcept override
Return the list of declared property names.
TypedValue getProperty (const std::string &name) const override
Get the value of a property.
std::string asString (bool withDefaultValues=false) const override
Return the property manager serialized as a string.
::Json::Value asJson (bool withDefaultValues=false) const override
Return the property manager serialized as a json object.
bool isDefault (const std::string &name) const
void removeProperty (const std::string &name, const bool delproperty=true) override
Removes the property from management.
std::unique_ptr< Kernel::Property > takeProperty (const size_t index) override
Removes the property from management and returns a pointer to it.
void clear () override
Clears all properties under management.
void afterPropertySet (const std::string &) override
Override this method to perform a custom action right after a property was set.
Kernel::Property * getPointerToProperty (const std::string &name) const override
Get a property by name.
Kernel::Property * getPointerToPropertyOrdinal (const int &index) const override
Get a property by an index.
virtual void declareProperty (std::unique_ptr< Property > p, const std::string &doc="")=0
Function to declare properties (i.e. store them)
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
const std::string category () const override
function to return a category of the algorithm.
const std::vector< std::string > categories () const override
Function to return all of the categories that contain this algorithm.
const std::string categorySeparator () const override
Function to return the separator token for the category string.
const std::vector< std::string > seeAlso () const override
Function to return all of the seeAlso (these are not validated) algorithms related to this algorithm.A default implementation is provided.
const std::string alias () const override
function to return any aliases to the algorithm; A default implementation is provided
const std::string aliasDeprecated () const override
Expiration date (in ISO8601 format) for the algorithm aliases; default implementation for no expiration date.
const std::string helpURL () const override
function to return URL for algorithm documentation; A default implementation is provided.
template<typename T , typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
std::tuple< std::shared_ptr< T >, Indexing::SpectrumIndexSet > getWorkspaceAndIndices (const std::string &name) const
Mechanism for retriving the index property.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::shared_ptr< T1 > &wksp, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
template<typename T1 , typename T2 , typename = typename std::enable_if<std::is_convertible<T1 *, MatrixWorkspace *>::value>::type, typename = typename std::enable_if<std::is_convertible<T2 *, std::string *>::value || std::is_convertible<T2 *, std::vector<int64_t> *>::value>::type>
void setWorkspaceInputProperties (const std::string &name, const std::string &wsName, IndexType type, const T2 &list)
Mechanism for setting the index property with a workspace shared pointer.
const std::string workspaceMethodName () const override
const std::vector< std::string > workspaceMethodOn () const override
const std::string workspaceMethodInputProperty () const override
AlgorithmID getAlgorithmID () const override
Algorithm ID.
Algorithms As Methods
Public Member Functions inherited from Mantid::Kernel::IPropertyManager
void declareProperty (const std::string &name, const char *value, const std::string &doc, IValidator_sptr validator=std::make_shared< NullValidator >(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
void declareProperty (const std::string &name, const char *value, const unsigned int direction)
Add a property of string type to the list of managed properties.
void declareProperty (const std::string &name, const char *value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc=std::string(), const unsigned int direction=Direction::Input)
Specialised version of declareProperty template method to prevent the creation of a PropertyWithValue of type const char* if an argument in quotes is passed (it will be converted to a string).
template<typename T >
void declareProperty (const std::string &name, T value, const std::string &doc, const unsigned int direction=Direction::Input)
Add a property to the list of managed properties with no validator.
template<typename T >
void declareProperty (const std::string &name, T value, const unsigned int direction)
Add a property of the template type to the list of managed properties.
template<typename T >
void declareProperty (const std::string &name, T value, IValidator_sptr validator=std::make_shared< NullValidator >(), const std::string &doc="", const unsigned int direction=Direction::Input)
Add a property of the template type to the list of managed properties.
virtual void filterByProperty (Mantid::Kernel::LogFilter *, const std::vector< std::string > &)
std::vector< Property * > getPropertiesInGroup (const std::string &group) const
Get the list of managed properties in a given group.
bool isPropertyEnabled (const std::string &name) const
Test if a given property should be enabled.
bool isPropertyVisible (const std::string &name) const
Test if a given property should be visible.
IPropertyManager * setProperty (const std::string &name, const char *value)
Specialised version of setProperty template method to handle const char *.
IPropertyManager * setProperty (const std::string &name, const std::string &value)
Specialised version of setProperty template method to handle std::string.
template<typename T >
IPropertyManager * setProperty (const std::string &name, const T &value)
Templated method to set the value of a PropertyWithValue.
template<typename T >
IPropertyManager * setProperty (const std::string &name, std::unique_ptr< T > value)
Templated method to set the value of a PropertyWithValue from a std::unique_ptr.
void setPropertyGroup (const std::string &name, const std::string &group)
Set the group for a given property.
void setPropertySettings (const std::string &name, std::unique_ptr< IPropertySettings const > settings)
Add a PropertySettings instance to the chain of settings for a given property.
void updatePropertyValues (const IPropertyManager &other)
Update values of the existing properties.
virtual ~IPropertyManager ()=default
Private Member Functions
API::MatrixWorkspace_sptr calculateResolutionTable ()
void createCalTableFromExisting ()
Read a calibration table workspace provided by user, or load from a file provided by User.
void createCalTableHeader ()
void createCalTableNew ()
Initialize the calibration table workspace.
void createInformationWorkspaces ()
Table workspaces where the first column is the detector ID and subsequent columns are termed "@x.xxxxx" where x.xxxxx are the peak positions of the "PeakPositions" input property array (the nominal peak center positions)
std::pair< API::MatrixWorkspace_sptr, API::MatrixWorkspace_sptr > createTOFPeakCenterFitWindowWorkspaces (const API::MatrixWorkspace_sptr &dataws, const std::vector< double > &peakWindowMaxInDSpacing)
NEW: convert peak positions in dSpacing to peak centers workspace.
std::set< detid_t > detIdsForTable ()
std::vector< double > dSpacingWindows (const std::vector< double > &centres, const std::vector< double > &widthMax)
Fitting ranges to the left and right of peak center (the window cannot exceed half the distance to the adjacent peaks in either direction)
void exec () override
Execute the algorithm.
void fitDIFCtZeroDIFA_LM (const std::vector< double > &d, const std::vector< double > &tof, const std::vector< double > &height2, double &difc, double &t0, double &difa)
Fit the nominal peak center positions, in d-spacing against the fitted peak center positions, in TOF units.
std::tuple< double, double, double > getDSpacingToTof (const std::set< detid_t > &detIds)
Return a function that converts from d-spacing to TOF units for a particular pixel, evaulating the GSAS conversion formula: TOF = DIFCd + DIFAd^2 + TZERO.
std::vector< double > getTOFminmax (const double difc, const double difa, const double tzero)
Adjustment of TofMin and TofMax values, to ensure positive values of d-spacing when converting from TOF to d-spacing using the GSAS equation TOF = DIFCd + DIFAd^2 + TZERO See calcTofMin and calcTofMax for adjustments to TofMin and TofMax.
void init () override
Initialize the algorithm's properties.
API::MatrixWorkspace_sptr load (const std::string &filename)
API::MatrixWorkspace_sptr loadAndBin ()
load input workspace and rebin with parameters "TofBinning" provided by User
API::MatrixWorkspace_sptr rebin (API::MatrixWorkspace_sptr wksp)
void setCalibrationValues (const detid_t detid, const double difc, const double difa, const double tzero)
API::ITableWorkspace_sptr sortTableWorkspace (API::ITableWorkspace_sptr &table)
sort the calibration table according increasing values in column "detid"
std::map< std::string, std::string > validateInputs () override
Method checking errors on ALL the inputs, before execution.
Private Attributes
API::ITableWorkspace_sptr m_calibrationTable {nullptr}
std::map< detid_t, size_t > m_detidToRow
double m_difaMax {0.}
double m_difaMin {0.}
bool m_hasDasIds {false}
size_t m_numberMaxParams {0}
API::ITableWorkspace_sptr m_peakHeightTable {nullptr}
API::ITableWorkspace_sptr m_peakPositionTable {nullptr}
std::vector< double > m_peaksInDspacing
API::ITableWorkspace_sptr m_peakWidthTable {nullptr}
int m_startWorkspaceIndex
start index
int m_stopWorkspaceIndex
stop index (workspace index of the last spectrum included)
double m_tofMax {0.}
last bin boundary when rebinning in TOF (user input)
double m_tofMin {0.}
first bin boundary when rebinning in TOF (user input)
double m_tzeroMax {0.}
double m_tzeroMin {0.}
API::MatrixWorkspace_sptr m_uncalibratedWS {nullptr}
Additional Inherited Members
Public Types inherited from Mantid::API::Algorithm
using WorkspaceVector = std::vector< std::shared_ptr< Workspace > >
Static Public Member Functions inherited from Mantid::API::Algorithm
static IAlgorithm_sptr fromString (const std::string &input)
De-serialize an object from a string.
static IAlgorithm_sptr fromJson (const Json::Value &input)
De-serialize an object from a Json.
static IAlgorithm_sptr fromHistory (const AlgorithmHistory &history)
Construct an object from a history entry.
Public Attributes inherited from Mantid::API::Algorithm
bool calledByAlias = false
Flag to indicate if the algorithm is called by its alias.
Protected Member Functions inherited from Mantid::API::Algorithm
virtual const std::string workspaceMethodOnTypes () const
Returns a semi-colon separated list of workspace types to attach this algorithm.
void cacheWorkspaceProperties ()
Go through the properties and cache the input/output workspace properties for later use.
void cacheInputWorkspaceHistories ()
Cache the histories of any input workspaces so they can be copied over after algorithm completion.
void setExecutionState (const ExecutionState state)
Sets the current execution state.
void setResultState (const ResultState state)
Sets the result execution state.
void store ()
Stores any output workspaces into the AnalysisDataService.
void progress (double p, const std::string &msg="", double estimatedTime=0.0, int progressPrecision=0)
Sends ProgressNotification.
void interruption_point ()
This is called during long-running operations, and check if the algorithm has requested that it be cancelled.
Poco::NotificationCenter & notificationCenter () const
Return a reference to the algorithm's notification dispatcher.
void handleChildProgressNotification (const Poco::AutoPtr< ProgressNotification > &pNf)
Observation slot for child algorithm progress notification messages, these are scaled and then signalled for this algorithm.
const Poco::AbstractObserver & progressObserver () const
Return a reference to the algorithm's object that is reporting progress.
bool isWorkspaceProperty (const Kernel::Property *const prop) const
checks the property is a workspace property
bool trackingHistory ()
get whether we are tracking the history for this algorithm,
virtual void fillHistory ()
Copy workspace history from input workspaces to output workspaces and record the history for ths algorithm.
void fillHistory (const std::vector< Workspace_sptr > &outputWorkspaces)
Copy workspace history from input workspaces to provided vector of output workspaces.
virtual void setOtherProperties (IAlgorithm *alg, const std::string &propertyName, const std::string &propertyValue, int periodNum)
Virtual method to set the non workspace properties for this algorithm.
template<typename T , const int AllowedIndexTypes = static_cast<int>(IndexType::WorkspaceIndex), typename... WSPropArgs, typename = typename std::enable_if<std::is_convertible<T *, MatrixWorkspace *>::value>::type>
void declareWorkspaceInputProperties (const std::string &propertyName, const std::string &doc, WSPropArgs &&...wsPropArgs)
Declare a property which defines the workspace and allowed index types, as well as a property for capturing the indices all at once.
Protected Member Functions inherited from Mantid::Kernel::IPropertyManager
template<typename T >
T getValue (const std::string &name) const
Templated method to get the value of a property.
template<>
MANTID_KERNEL_DLL PropertyManager_sptr getValue (const std::string &name) const
template<>
MANTID_KERNEL_DLL PropertyManager_const_sptr getValue (const std::string &name) const
Static Protected Member Functions inherited from Mantid::API::Algorithm
template<typename NumT >
static bool isEmpty (const NumT toCheck)
checks that the value was not set by users, uses the value in empty double/int.
Protected Attributes inherited from Mantid::API::Algorithm
std::atomic< bool > m_cancel
Set to true to stop execution.
std::atomic< bool > m_parallelException
Set if an exception is thrown, and not caught, within a parallel region.
std::vector< IWorkspaceProperty * > m_inputWorkspaceProps
All the WorkspaceProperties that are Input or InOut. Set in execute()
std::shared_ptr< AlgorithmHistory > m_history
Pointer to the history for the algorithm being executed.
Kernel::Logger m_log
Logger for this algorithm.
Kernel::Logger & g_log
std::shared_ptr< AlgorithmHistory > m_parentHistory
Pointer to the parent history object (if set)
std::vector< WorkspaceVector > m_unrolledInputWorkspaces
One vector of workspaces for each input workspace property.
size_t m_groupSize
Size of the group(s) being processed.
bool m_usingBaseProcessGroups = false
distinguish between base processGroups() and overriden/algorithm specific versions
Static Protected Attributes inherited from Mantid::API::Algorithm
static size_t g_execCount = 0
Counter to keep track of algorithm execution order.
Detailed Description
PDCalibration : TODO: DESCRIPTION.
Definition at line 22 of file PDCalibration.h.
Constructor & Destructor Documentation
PDCalibration()
Mantid::Algorithms::PDCalibration::PDCalibration () default
Constructor.
~PDCalibration()
Mantid::Algorithms::PDCalibration::~PDCalibration () override default
Destructor.
References Mantid::Kernel::VectorHelper::rebin().
Member Function Documentation
calculateResolutionTable()
API::MatrixWorkspace_sptr Mantid::Algorithms::PDCalibration::calculateResolutionTable () private
Definition at line 1438 of file PDCalibration.cpp.
References m_peakPositionTable, m_peaksInDspacing, m_peakWidthTable, m_uncalibratedWS, and value.
Referenced by exec().
category()
const std::string Mantid::Algorithms::PDCalibration::category () const override virtual
Algorithm's category for identification.
See also
Algorithm::category
Implements Mantid::API::IAlgorithm.
Definition at line 183 of file PDCalibration.cpp.
createCalTableFromExisting()
void Mantid::Algorithms::PDCalibration::createCalTableFromExisting () private
Read a calibration table workspace provided by user, or load from a file provided by User.
Every pixel may need adjustment of TofMin and TofMax values, to ensure positive values of d-spacing when converting from TOF to d-spacing using the GSAS equation TOF = DIFCd + DIFAd^2 + TZERO. See calcTofMin and calcTofMax for adjustments to TofMin and TofMax.
The output calibration has columns "detid", "difc", "difa", "tzero", "tofmin", and "tofmax", and possible additional columns "dasid" and "offset"
Definition at line 1296 of file PDCalibration.cpp.
References createCalTableHeader(), Mantid::API::Algorithm::createChildAlgorithm(), detIdsForTable(), Mantid::Kernel::difa, Mantid::Kernel::difc, Mantid::API::Algorithm::getProperty(), getTOFminmax(), m_calibrationTable, m_detidToRow, m_hasDasIds, m_tofMax, m_tofMin, Mantid::API::ColumnVector< T >::size(), and Mantid::Kernel::tzero.
Referenced by exec().
createCalTableHeader()
void Mantid::Algorithms::PDCalibration::createCalTableHeader () private
Definition at line 1269 of file PDCalibration.cpp.
References m_calibrationTable, and m_hasDasIds.
Referenced by createCalTableFromExisting(), and createCalTableNew().
createCalTableNew()
void Mantid::Algorithms::PDCalibration::createCalTableNew () private
Initialize the calibration table workspace.
The output calibration has columns "detid", "difc", "difa", "tzero", "tofmin", and "tofmax". "difc" from the instrument geometry: m_n * (L1 + L2) * 2 * sin(theta) / h "difa", "tzero", and "tofmin" set to zero, "tofmax" to DBL_MAX
Definition at line 1351 of file PDCalibration.cpp.
References createCalTableHeader(), Mantid::API::Algorithm::createChildAlgorithm(), detIdsForTable(), m_calibrationTable, m_detidToRow, and m_uncalibratedWS.
Referenced by exec().
createInformationWorkspaces()
void Mantid::Algorithms::PDCalibration::createInformationWorkspaces () private
Table workspaces where the first column is the detector ID and subsequent columns are termed "@x.xxxxx" where x.xxxxx are the peak positions of the "PeakPositions" input property array (the nominal peak center positions)
Definition at line 1392 of file PDCalibration.cpp.
References m_detidToRow, m_peakHeightTable, m_peakPositionTable, m_peaksInDspacing, m_peakWidthTable, and UNUSED_ARG.
Referenced by exec().
createTOFPeakCenterFitWindowWorkspaces()
std::pair< API::MatrixWorkspace_sptr, API::MatrixWorkspace_sptr > Mantid::Algorithms::PDCalibration::createTOFPeakCenterFitWindowWorkspaces (const API::MatrixWorkspace_sptr & dataws, const std::vector< double > & peakWindow) private
NEW: convert peak positions in dSpacing to peak centers workspace.
Create a pair of workspaces, one containing the nominal peak centers in TOF units, the other containing the left and right fitting ranges around each nominal peak center, also in TOF units.
Because each pixel has a different set of difc, difa, and tzero values, the position of the nominal peak centers (and the fitting ranges) will be different when expressed in TOF units. Thus, they have to be calculated for each pixel.
Parameters
dataws :: input signal workspace
peakWindow,: A vector of boundaries in d-spacing (if the vector has only one element this is half the width of the window for all peaks) left and right of the nominal peak center to look for the peak
Definition at line 1505 of file PDCalibration.cpp.
References Mantid::Algorithms::PDCalibration::FittedPeaks::detid, Mantid::Kernel::difa, Mantid::Kernel::difc, dSpacingWindows(), Mantid::API::Algorithm::g_log, getDSpacingToTof(), Mantid::Kernel::Logger::information(), Mantid::Algorithms::PDCalibration::FittedPeaks::inTofPos, Mantid::Algorithms::PDCalibration::FittedPeaks::inTofWindows, m_peaksInDspacing, m_startWorkspaceIndex, m_stopWorkspaceIndex, PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, Mantid::Kernel::ProgressBase::report(), Mantid::Algorithms::PDCalibration::FittedPeaks::setPositions(), and Mantid::Kernel::tzero.
Referenced by exec().
detIdsForTable()
std::set< detid_t > Mantid::Algorithms::PDCalibration::detIdsForTable () private
Definition at line 1249 of file PDCalibration.cpp.
References Mantid::API::Algorithm::isDefault(), m_startWorkspaceIndex, m_stopWorkspaceIndex, and m_uncalibratedWS.
Referenced by createCalTableFromExisting(), and createCalTableNew().
dSpacingWindows()
vector< double > Mantid::Algorithms::PDCalibration::dSpacingWindows (const std::vector< double > & centres, const std::vector< double > & windows_in) private
Fitting ranges to the left and right of peak center (the window cannot exceed half the distance to the adjacent peaks in either direction)
Parameters
centres :: peak centers, in d-spacing
windows_in :: A vector of boundaries in d-sapcing (if only one element this is half the width of the window for all peaks)
Returns
array containing left and right ranges for first peak, left and right for second peak, and so on.
Definition at line 1102 of file PDCalibration.cpp.
References left, and right.
Referenced by createTOFPeakCenterFitWindowWorkspaces(), and exec().
exec()
void Mantid::Algorithms::PDCalibration::exec () override private virtual
Execute the algorithm.
Implements Mantid::API::Algorithm.
Definition at line 431 of file PDCalibration.cpp.
References calculateResolutionTable(), createCalTableFromExisting(), createCalTableNew(), Mantid::API::Algorithm::createChildAlgorithm(), createInformationWorkspaces(), createTOFPeakCenterFitWindowWorkspaces(), Mantid::Kernel::Logger::debug(), Mantid::Algorithms::PDCalibration::FittedPeaks::detid, Mantid::Kernel::difa, Mantid::Kernel::difc, dSpacingWindows(), fitDIFCtZeroDIFA_LM(), Mantid::API::Algorithm::g_log, getDSpacingToTof(), Mantid::Kernel::Logger::getLogStream(), Mantid::API::Algorithm::getProperty(), Mantid::API::Algorithm::getPropertyValue(), height, Mantid::Kernel::Logger::information(), Mantid::Kernel::Unit::initialize(), Mantid::Algorithms::PDCalibration::FittedPeaks::inTofWindows, Mantid::API::Algorithm::isDefault(), loadAndBin(), m_calibrationTable, m_detidToRow, m_difaMax, m_difaMin, m_numberMaxParams, m_peakHeightTable, m_peakPositionTable, m_peaksInDspacing, m_peakWidthTable, m_startWorkspaceIndex, m_stopWorkspaceIndex, m_tofMax, m_tofMin, m_tzeroMax, m_tzeroMin, m_uncalibratedWS, Mantid::Kernel::Logger::notice(), PARALLEL_CHECK_INTERRUPT_REGION, PARALLEL_END_INTERRUPT_REGION, PARALLEL_START_INTERRUPT_REGION, PRAGMA_OMP, Mantid::Kernel::ProgressBase::report(), setCalibrationValues(), Mantid::Algorithms::PDCalibration::FittedPeaks::setPositions(), Mantid::Kernel::IPropertyManager::setProperty(), Mantid::Kernel::Units::dSpacing::singleFromTOF(), sortTableWorkspace(), and Mantid::Kernel::tzero.
fitDIFCtZeroDIFA_LM()
void Mantid::Algorithms::PDCalibration::fitDIFCtZeroDIFA_LM (const std::vector< double > & d, const std::vector< double > & tof, const std::vector< double > & weights, double & difc, double & t0, double & difa) private
Fit the nominal peak center positions, in d-spacing against the fitted peak center positions, in TOF units.
We use the GSAS formula: TOF = DIFCd + DIFAd^2 + TZERO
No fitting is performed if the number of peaks is less than two.
Parameters
d :: nominal peak center positions, in d-spacing units
tof :: fitted peak center positions, in TOF units
weights :: weights for leastsq fit
difc :: output optimized DIFC parameter
t0 :: output optimized TZERO parameter
difa :: output optimized DIFA parameter
Definition at line 1017 of file PDCalibration.cpp.
References Mantid::Geometry::d, Mantid::Kernel::difa, Mantid::Kernel::difc, m_difaMax, m_difaMin, m_numberMaxParams, m_tzeroMax, and m_tzeroMin.
Referenced by exec().
getDSpacingToTof()
std::tuple< double, double, double > Mantid::Algorithms::PDCalibration::getDSpacingToTof (const std::set< detid_t > & detIds) private
Return a function that converts from d-spacing to TOF units for a particular pixel, evaulating the GSAS conversion formula: TOF = DIFCd + DIFAd^2 + TZERO.
Parameters
detIds :: set of detector IDs
Definition at line 1148 of file PDCalibration.cpp.
References Mantid::Kernel::difa, Mantid::Kernel::difc, m_calibrationTable, m_detidToRow, and Mantid::Kernel::tzero.
Referenced by createTOFPeakCenterFitWindowWorkspaces(), and exec().
getTOFminmax()
vector< double > Mantid::Algorithms::PDCalibration::getTOFminmax (const double difc, const double difa, const double tzero) private
Adjustment of TofMin and TofMax values, to ensure positive values of d-spacing when converting from TOF to d-spacing using the GSAS equation TOF = DIFCd + DIFAd^2 + TZERO See calcTofMin and calcTofMax for adjustments to TofMin and TofMax.
Returns
two-item array containing adjusted TofMin and TofMax values
Definition at line 1201 of file PDCalibration.cpp.
References Mantid::Kernel::Units::dSpacing::calcTofMax(), Mantid::Kernel::Units::dSpacing::calcTofMin(), Mantid::Kernel::difa, Mantid::Kernel::difc, m_tofMax, m_tofMin, and Mantid::Kernel::tzero.
Referenced by createCalTableFromExisting(), and setCalibrationValues().
init()
void Mantid::Algorithms::PDCalibration::init () override private virtual
Initialize the algorithm's properties.
Implements Mantid::API::Algorithm.
Definition at line 194 of file PDCalibration.cpp.
References Mantid::API::Algorithm::declareProperty(), Mantid::EMPTY_DBL(), Mantid::EMPTY_INT(), Mantid::Kernel::Direction::Input, Mantid::API::PropertyMode::Optional, Mantid::API::FileProperty::OptionalLoad, Mantid::Kernel::Direction::Output, and Mantid::Kernel::IPropertyManager::setPropertyGroup().
load()
MatrixWorkspace_sptr Mantid::Algorithms::PDCalibration::load (const std::string & filename) private
Definition at line 1210 of file PDCalibration.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::getProperty(), m_tofMax, m_tofMin, and workspace.
loadAndBin()
MatrixWorkspace_sptr Mantid::Algorithms::PDCalibration::loadAndBin () private
load input workspace and rebin with parameters "TofBinning" provided by User
Definition at line 1230 of file PDCalibration.cpp.
References Mantid::API::Algorithm::getProperty(), m_uncalibratedWS, and rebin().
Referenced by exec().
name()
const std::string Mantid::Algorithms::PDCalibration::name () const override virtual
Algorithms name for identification.
See also
Algorithm::name
Implements Mantid::API::Algorithm.
Definition at line 177 of file PDCalibration.cpp.
rebin()
API::MatrixWorkspace_sptr Mantid::Algorithms::PDCalibration::rebin (API::MatrixWorkspace_sptr wksp) private
Definition at line 1235 of file PDCalibration.cpp.
References Mantid::API::Algorithm::createChildAlgorithm(), Mantid::API::Algorithm::g_log, Mantid::API::Algorithm::getPropertyValue(), Mantid::Kernel::Logger::information(), and rebin().
Referenced by loadAndBin(), and rebin().
setCalibrationValues()
void Mantid::Algorithms::PDCalibration::setCalibrationValues (const detid_t detid, const double difc, const double difa, const double tzero) private
Definition at line 1169 of file PDCalibration.cpp.
References Mantid::Kernel::difa, Mantid::Kernel::difc, getTOFminmax(), m_calibrationTable, m_detidToRow, m_hasDasIds, and Mantid::Kernel::tzero.
Referenced by exec().
sortTableWorkspace()
API::ITableWorkspace_sptr Mantid::Algorithms::PDCalibration::sortTableWorkspace (API::ITableWorkspace_sptr & table) private
sort the calibration table according increasing values in column "detid"
Definition at line 1478 of file PDCalibration.cpp.
References Mantid::API::Algorithm::createChildAlgorithm().
Referenced by exec().
summary()
const std::string Mantid::Algorithms::PDCalibration::summary () const override virtual
Algorithm's summary for use in the GUI and help.
See also
Algorithm::summary
Implements Mantid::API::Algorithm.
Definition at line 186 of file PDCalibration.cpp.
validateInputs()
std::map< std::string, std::string > Mantid::Algorithms::PDCalibration::validateInputs () override private virtual
Method checking errors on ALL the inputs, before execution.
For use mostly in dialogs.
Implements Mantid::API::IAlgorithm.
Definition at line 356 of file PDCalibration.cpp.
References Mantid::API::Algorithm::getProperty().
version()
int Mantid::Algorithms::PDCalibration::version () const override virtual
Algorithm's version for identification.
See also
Algorithm::version
Implements Mantid::API::Algorithm.
Definition at line 180 of file PDCalibration.cpp.
Member Data Documentation
m_calibrationTable
API::ITableWorkspace_sptr Mantid::Algorithms::PDCalibration::m_calibrationTable {nullptr} private
Definition at line 62 of file PDCalibration.h.
Referenced by createCalTableFromExisting(), createCalTableHeader(), createCalTableNew(), exec(), getDSpacingToTof(), and setCalibrationValues().
m_detidToRow
std::map<detid_t, size_t> Mantid::Algorithms::PDCalibration::m_detidToRow private
Definition at line 67 of file PDCalibration.h.
Referenced by createCalTableFromExisting(), createCalTableNew(), createInformationWorkspaces(), exec(), getDSpacingToTof(), and setCalibrationValues().
m_difaMax
double Mantid::Algorithms::PDCalibration::m_difaMax {0.} private
Definition at line 75 of file PDCalibration.h.
Referenced by exec(), and fitDIFCtZeroDIFA_LM().
m_difaMin
double Mantid::Algorithms::PDCalibration::m_difaMin {0.} private
Definition at line 74 of file PDCalibration.h.
Referenced by exec(), and fitDIFCtZeroDIFA_LM().
m_hasDasIds
bool Mantid::Algorithms::PDCalibration::m_hasDasIds {false} private
Definition at line 76 of file PDCalibration.h.
Referenced by createCalTableFromExisting(), createCalTableHeader(), and setCalibrationValues().
m_numberMaxParams
size_t Mantid::Algorithms::PDCalibration::m_numberMaxParams {0} private
Definition at line 77 of file PDCalibration.h.
Referenced by exec(), and fitDIFCtZeroDIFA_LM().
m_peakHeightTable
API::ITableWorkspace_sptr Mantid::Algorithms::PDCalibration::m_peakHeightTable {nullptr} private
Definition at line 65 of file PDCalibration.h.
Referenced by createInformationWorkspaces(), and exec().
m_peakPositionTable
API::ITableWorkspace_sptr Mantid::Algorithms::PDCalibration::m_peakPositionTable {nullptr} private
Definition at line 63 of file PDCalibration.h.
Referenced by calculateResolutionTable(), createInformationWorkspaces(), and exec().
m_peaksInDspacing
std::vector<double> Mantid::Algorithms::PDCalibration::m_peaksInDspacing private
Definition at line 66 of file PDCalibration.h.
Referenced by calculateResolutionTable(), createInformationWorkspaces(), createTOFPeakCenterFitWindowWorkspaces(), and exec().
m_peakWidthTable
API::ITableWorkspace_sptr Mantid::Algorithms::PDCalibration::m_peakWidthTable {nullptr} private
Definition at line 64 of file PDCalibration.h.
Referenced by calculateResolutionTable(), createInformationWorkspaces(), and exec().
m_startWorkspaceIndex
int Mantid::Algorithms::PDCalibration::m_startWorkspaceIndex private
start index
Definition at line 68 of file PDCalibration.h.
Referenced by createTOFPeakCenterFitWindowWorkspaces(), detIdsForTable(), and exec().
m_stopWorkspaceIndex
int Mantid::Algorithms::PDCalibration::m_stopWorkspaceIndex private
stop index (workspace index of the last spectrum included)
Definition at line 69 of file PDCalibration.h.
Referenced by createTOFPeakCenterFitWindowWorkspaces(), detIdsForTable(), and exec().
m_tofMax
double Mantid::Algorithms::PDCalibration::m_tofMax {0.} private
last bin boundary when rebinning in TOF (user input)
Definition at line 71 of file PDCalibration.h.
Referenced by createCalTableFromExisting(), exec(), getTOFminmax(), and load().
m_tofMin
double Mantid::Algorithms::PDCalibration::m_tofMin {0.} private
first bin boundary when rebinning in TOF (user input)
Definition at line 70 of file PDCalibration.h.
Referenced by createCalTableFromExisting(), exec(), getTOFminmax(), and load().
m_tzeroMax
double Mantid::Algorithms::PDCalibration::m_tzeroMax {0.} private
Definition at line 73 of file PDCalibration.h.
Referenced by exec(), and fitDIFCtZeroDIFA_LM().
m_tzeroMin
double Mantid::Algorithms::PDCalibration::m_tzeroMin {0.} private
Definition at line 72 of file PDCalibration.h.
Referenced by exec(), and fitDIFCtZeroDIFA_LM().
m_uncalibratedWS
API::MatrixWorkspace_sptr Mantid::Algorithms::PDCalibration::m_uncalibratedWS {nullptr} private
Definition at line 61 of file PDCalibration.h.
Referenced by calculateResolutionTable(), createCalTableNew(), detIdsForTable(), exec(), and loadAndBin().
The documentation for this class was generated from the following files:
Framework/Algorithms/inc/MantidAlgorithms/PDCalibration.h
Framework/Algorithms/src/PDCalibration.cpp