Mantid: ICat4::xsd__double Class Reference
ICat4::xsd__double Class Reference
#include <ICat4Stub.h>
Public Member Functions
void soap_default (struct soap *) override
void * soap_get (struct soap *, const char *, const char *) override
void * soap_in (struct soap *, const char *, const char *) override
int soap_out (struct soap *, const char *, int, const char *) const override
int soap_put (struct soap *, const char *, const char *) const override
void soap_serialize (struct soap *) const override
int soap_type () const override
xsd__double ()
Public Member Functions inherited from ICat4::xsd__anyType
xsd__anyType ()
virtual ~xsd__anyType ()=default
Public Attributes
double __item
Public Attributes inherited from ICat4::xsd__anyType
char * __item
struct soap * soap
Detailed Description
Definition at line 160 of file ICat4Stub.h.
Constructor & Destructor Documentation
xsd__double()
ICat4::xsd__double::xsd__double () inline
Definition at line 172 of file ICat4Stub.h.
Member Function Documentation
soap_default()
void ICat4::xsd__double::soap_default (struct soap * soap) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24041 of file ICat4C.cpp.
References __item, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_default(), and ICat4::soap_default_double().
Referenced by ICat4::soap_in_xsd__double(), ICat4::soap_new_req_xsd__double(), and ICat4::soap_new_set_xsd__double().
soap_get()
void * ICat4::xsd__double::soap_get (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24097 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_get_xsd__double().
soap_in()
void * ICat4::xsd__double::soap_in (struct soap * soap, const char * tag, const char * type) override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24064 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_in_xsd__double().
Referenced by ICat4::soap_in_xsd__double().
soap_out()
int ICat4::xsd__double::soap_out (struct soap * soap, const char * tag, int id, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24055 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, and ICat4::soap_out_xsd__double().
Referenced by soap_put().
soap_put()
int ICat4::xsd__double::soap_put (struct soap * soap, const char * tag, const char * type) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24090 of file ICat4C.cpp.
References ICat4::xsd__anyType::soap, soap_out(), ICat4::soap_putindependent(), and SOAP_TYPE_ICat4_xsd__double.
soap_serialize()
void ICat4::xsd__double::soap_serialize (struct soap * soap) const override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 24047 of file ICat4C.cpp.
References __item, ICat4::xsd__anyType::soap, ICat4::xsd__anyType::soap_serialize(), and SOAP_TYPE_ICat4_double.
soap_type()
int ICat4::xsd__double::soap_type () const inline override virtual
Reimplemented from ICat4::xsd__anyType.
Definition at line 165 of file ICat4Stub.h.
Member Data Documentation
__item
double ICat4::xsd__double::__item
Definition at line 162 of file ICat4Stub.h.
Referenced by soap_default(), and soap_serialize().
The documentation for this class was generated from the following files:
Framework/ICat/inc/MantidICat/ICat4/GSoapGenerated/ICat4Stub.h
Framework/ICat/src/ICat4/GSoapGenerated/ICat4C.cpp